### ISSUE TITLE
Add editor nano to buildroot configuration for RaspberryMatic

### ISSUE THREAD

**Issue by drose28357** [jens-maus/RaspberryMatic#100]
Buildroot 2017.02.1has a new option to include the editor nano to the build prozess. Nano is a very convinient editor which alows editing by cursor movement.

As you can see [here](https://youtu.be/84T-P5ye864?list=PLWcAlqDr1RVHSiAnQYt4M2GbDHJ07KWyJ) at video position 12:14 nano is a simple config option among other editors in .config or rasberrypi3-devconfig.

Please enable this editor in buildroot for RaspberryMatic. It is more convinient than vi.

**Comment by jens-maus** [comment]
First of all thanks for the suggestion. I know that there is the possibility to install nano in build root. However, RaspberryMatic is not meant to be used like a normal linux system where a user regularly logs in or works on the console. For the few things to be modified via a ssh login, vi is perfectly fine. Furthermore, I don't want to install two different editor for the rare case that a user has to modify a text  only once a year. And then for probably 99% of the normal users they don't log in via SSH anyway and thus installing nano per default will just increase the overall image size. Thus, I would suggest you compile nano yourself and create a third-party CCU Addon for installing nano or you install nano yourself by hand if you really require it. Sorry, but don't get me wrong. I don't want to to simply reject your request, but I don't really see a big benefit in installing yet another editor engine for the rare case of modifying a file once per year which probably only very few people do anyway.
