### ISSUE TITLE
"user.warn kernel: WARN::dwc_otg_hcd_urb_dequeue:638: Timed out waiting for FSM NP transfer to complete on" im 10-Sekunden-Takt

### ISSUE THREAD

**Issue by diddi68** [jens-maus/RaspberryMatic#1002]
**Describe the bug**
Seit der neuen Version bekomme ich im Durchschnitt alle 10 Sekunden folgenden Log-Eintrag:
"HM-CCU user.warn kernel: [20844.551438] WARN::dwc_otg_hcd_urb_dequeue:638: Timed out waiting for FSM NP transfer to complete on 2". Die letzte Zahl ändert sich im einstelligen Bereich.
Das Ganze führt nach etwa 4 Tagen entweder zum Reset der RM oder zum kompletten Stillstand ohne jegliche Zugriffsmöglichkeit auf die RM.

**System information:**
 - RaspberryMatic Version: 3.53.34.20201121
 - Used Hardware: Raspberry PI 3B
 - Used HomeMatic RF-Module: RPI-RF-MOD

**Additional context**
Der Fehler tritt am USB-Port auf, an dem ein USB-zu-Serial-Adapter mit angeschlossenem Siemens TC35 hängt. Das Ganze wird über das Addon "Messenger" von "mule" angesteuert. Schalte ich den "Messenger" aus, ist der Fehler weg.

**Comment by TMatGH** [comment]
Habe das gleiche Problem: "WARN::dwc_otg_hcd_urb_dequeue:638: Timed out waiting for FSM NP transfer to complete"

Nachdem ich auf meinem RaspberryPI 3B von der, zugegeben etwas alten, RaspberryMatic-Version 3.45.5.20190330 auf die Version 3.53.34.20201121 upgedatet habe, bekomme ich häufig die o.g. Warnung bzgl. des USB-Transfers.

Ich nutze auch die USB-Schnittstelle, hier: ttyUSB0 mit einem USB-Optoumsetzer (CP2102 USB to UART Bridge Controller), um Daten mit meiner Vitodens Heiztherme von Viessmann auszutauschen. Dabei versende ich die Daten über ein TCL-Script (über CUxD aufgerufen) in regelmäßigen Abständen , z.B. alle 120s. Dieses öffnet ttyUSB0 und liest u.a. im "blocking mode" Character von dieser Schnittstelle. 

Seltsamerweise taucht diese Warnmeldung aber nicht bei jedem Aufruf auf... Auch kam es bei mir mit dieser Version schon zu zwei System-Abstürzen. Zunächst hatte ich den nächtlichen SD-Kartentest in Verdacht, aber auch die Nutzung einer anderen Karte löste das Problem der Abstürze scheinbar nicht - denn nach dem Wechsel gab es wieder einen Absturz. Hierbei stand der DutyCycle auf -1% ??? und das System bzw. Teile (z.B. WebUI) davon hingen fest. Nach einem Reset lief das System wieder. Habe von der Absturzzeit System-Logs. 

Habe mein System jetzt auf die alte RaspberryMatic-Version 3.45.5.20190330 zurückgesetzt. Nun gibt es wieder keine Warnmeldungen mehr - und bisher läuft das System auch einwandfrei. 

Liegt das Problem möglicherweise an dem neuen Linux-System und den zugehörigen USB-Treibern ?  

Vielleicht haben die Warnmeldungen bzgl. des USB-Treibers aber  gar nichts mit den Abstürzen zu tun. Und die Abstürze werden möglicherweise durch nach der alten Version eingeführte Änderungen, wie z.B. den SD-Kartentest, verursacht. Trotzdem wäre es natürlich gut, wenn die Warnmeldungen verschwinden würden.

**Comment by mule1972** [comment]
> Der Fehler tritt am USB-Port auf, an dem ein USB-zu-Serial-Adapter mit angeschlossenem Siemens TC35 hängt. Das Ganze wird über das Addon "Messenger" von "mule" angesteuert. Schalte ich den "Messenger" aus, ist der Fehler weg.

Hi, ich bin "mule" und habe diese Warnings natürlich auch in den Logs. Leider findet man im Netz nicht wirklich eine Ursache dafür, außer einem Hinweis, dass mit zu wenig Spannung auf den USB2.0-Ports etwas zu tun haben könnte. Daran glaube ich nicht, da die SMS-Platine ja mit einer eigenen Spannung versorgt wird. Daher tippe ich auf ein Kernel-/Treiber-Problem. Zumal das Problem ja in früheren Raspberrymatic-Versionen nicht auftrat. Allerdings konnte ich bisher bis auf die Warnings auch noch keine negativen Auswirkungen erkennen. Ist natürlich trotzdem unschön, dass das Log vollgespammt wird.

Auf der einen Seite finde ich es ja gut, dass bei Raspberrymatic auch Kernel&Co. aktuell gehalten werden. Allerdings bei einer Haimautomation bei der Stabilität im Vordergrund steht, sollte man hier eventuell einen Gang runterschrauben. Dies ist zumindest meine persönliche Meinung,

**Comment by jens-maus** [comment]
Da es sich bei der gezeigten Meldung um eine reine Warnung (siehe `user.warn`) handelt, halte ich dieses "Problem" rein kosmetischer Natur. Auch wurde ja schon bestätigt, dass es wohl keine negativen Effekte gibt. Insofern sehe ich hier keinerlei Handlungsbedarf solange nicht ursächlich aufgzeigt werden kann, dass diese mit irgendwelchen Abstürzen oder negativen Effekten unmittelbar in Verbindung gebracht werden können.

**Comment by mule1972** [comment]
Hallo Jens,

ich muss doch nochmal auf dieses USB-Problem zurückkommen, da es anscheinend nicht bei Warnings in den Logs bleibt, sondern zu Komplettabstürzen von Raspberrymatic führt.
Aber von Beginn an:
Am 31.12. habe ich die V3.55.5.20201226 installiert (vorher hatte ich noch V3.51.6.20200420 drauf). Zunächst konnte ich nur die bekannten Warnings wahrnehmen. Nach einigen Tagen erfolgte dann aber ein kompletter Crash von Raspberrymatic (ein per HDMI dann angeschlossener Monitor hat dann keinerlei Signal mehr bekommen und natürlich funktionierte auch kein Ping mehr, der PI war also komplett gecrashed). Es half letztendlich nur ein stromlos machen. 
Nach Neustart lief es dann wieder ein paar Tage und heute gab es einen erneuten Komplettcrash. Zum Zeitpunkt der beiden Crashes sollte immer ein Steuerbefehl mit einem an den PI angeschlossenen CUL-USB-Stick gesendet werden, welcher mit einem eigenentwickelten TCL-Script angesteuert wird.
Parellel habe ich dann ja auch noch das von mir entwickelte SMS Messenger-Addon laufen, bei dem ein per USB angeschlossenes GSM-Modul angesteuert wird. Beide Implementationen laufen seit Jahren stabil.
Ich habe mittlerweile durch Tests auch herausgefunden, dass nicht nur das USB-GSM-Modul die Warnings verursacht, sondern auch der bei mir angeschlossne CUL-Stick.
Nun könnte man meinen die Crashes sind meiner Installation geschuldet. Dies ist aber mit hoher Wahrscheinlichkeit nicht der Fall, da mir inzwischen mehrere User des Messenger-Addons ebenfalls von den Crashes nach einigen Tagen Betrieb berichtet haben. Die User berichteten zudem, dass nach Deaktivierung des Messenger-Addons die Crashes nicht mehr aufgetreten sind.
Nun könnte man meinen, dass es am Messenger-Addon liegt. Dies ist aber ausgeschlossen, denn es wurde seit 02-2019 nicht mehr weiterentwickelt und sowohl die anderen User, als auch ich selbst hatten in den letzten 2 Jahren damit keinerlei Probleme und schon gar keine kompletten Crashes von Raspberrymatic. Zumal das Addon auch nur aus einem TCL-Script besteht und keine eigenen Treiber o.ä. mitsich bringt.
Da ich wie Eingangs geschrieben einige Versionen von Raspberrymatic übersprungen habe, kann ich leider nicht genau sagen mit welcher Version die Probleme Einzug erhalten haben . User des Messenger-Addons berichteten mir aber, dass Sie seit der Version 3.53.34.20201121 die angesprochenen Warnings und Crashes beobachten. 
Ich würde Dich bitten den Issue wieder zu öffnen und Dich dem Thema anzunehmen. Für weitere Infos oder Tests stehe ich gerne jederzeit zur Verfügung!

**Comment by diddi68** [comment]
Ein paar Hinweise kann ich auch dazu liefern.
Erstmalig trat der Fehler bei mir mit der Version 3.55.5.20201226 auf. Ein anderer USB-to-Serial-Konverter brachte keine Änderung.
Ich hab den 8. Parameter (Frequenz des SMS-Empfangscheck in Sekunden) auf "0" gesetzt und damit abgeschaltet.
Den 6. Parameter (Frequenz des Modemchecks in Stunden) habe ich auf "24" gesetzt.
Damit reduzieren sich die Warnings auf etwa 4 pro Tag und seit mittlerweile 5 Tagen absturzfrei. Ich muß damit zwar auf den SMS-Empfang verzichten, da ich den Messenger aber überwiegend als Fallback-Benachrichtigung nutze, kann ich damit - zumindest vorübergehend - leben.

**Comment by mule1972** [comment]
@diddi68: Nutzt Du wie ich einen PI3 oder einen PI4? Eventuell gibt es ja die Probleme nur auf bestimmten HW-Versionen des PI.

**Comment by diddi68** [comment]
Ich hab eine CCU3 - also Pi3b+

**Comment by mule1972** [comment]
Ich nutze den Pi3b. Leider habe ich keinen 4er. Du eventuell?
Am Wochenende werde ich Raspberrymatic unter Promox als VM installieren und testen. Ich gehe davon aus, dass es dort diese Probleme nicht gibt.

**Comment by TMatGH** [comment]
Hallo, hatte ja auch schon einen Kommentar (s.o.) zu diesem Thema geschrieben. Bei mir  greife ich von von einem Raspberry-PI 3B (kein 3B+ !) über einen USB2Serial-Adapter auf meine Heiztherme zu. Außerdem lese ich mit einem anderen TCL-Treiber aus einem Arduino noch Zählerstände (Strom, Gas, Wasser) aus. Habe dabei auch die beschriebenen Fehlermeldungen. 

Da ich aktuell noch ein paar andere Fehler in meinem Log hatte, habe ich erstmal wieder auf meine alte Rapsberrymatic-Version aus 2019 downgegradet. Hier läuft nun inzwischen alles.

Werde es demnächst auch noch mal mit der aktuellen/neuen RaspberryMatic-Version versuchen, aber eure Kommentare machen ja leider wenig Mut. Eine Idee wäre noch die USB2Serial-Adapter über einen USB-Hub an die RaspberryMatic anzuschließen. Werde dies zunächst mal auf einem Raspberry PI 4 testen.

Wenn es tatsächlig mit dem USB-Treiber im Kernel Probleme gibt, sollte hier eine Lösung gefunden werden. Auch wenn dies kein sehr häufiger Anwendungsfall ist, sollten die USB-Treiber doch sauber laufen.

Gruß
Thomas

**Comment by diddi68** [comment]
`Eine Idee wäre noch die USB2Serial-Adapter über einen USB-Hub an die RaspberryMatic anzuschließen.`
Hab ich schon probiert > leider ohne Erfolg.

**Comment by mule1972** [comment]
> Werde dies zunächst mal auf einem Raspberry PI 4 testen.

Das wäre super. Ich habe da so ein Bauchgefühl ;-)

**Comment by TMatGH** [comment]
Habe inziwschen den Raspberry-PI 4 mit dem RaspberryMatic-3.55.5.20201226-rpi4.img frisch betankt und mein Backup eingespielt. Hatte zunächtst Probleme bei der Erkennung der USB2Serial-Adapter. Gerade für meinen Heizthermenanschluss (VIESSMANN 7856059 Anschlussleitung USB-Optolink mit CP2102 USB to UART Bridge Controller, 3m lang, plus weiterer 2m-USB-Verlängerung arbeite ich wohl am Rande der USB-Spezifikation. Abhilfe brachte dann ein DELOCK 82748 USB 2.0 Verlängerungskabel 10m aktiv 4Port Hub (Reichelt). 

Nun wurde neben meinem Arduino (Zähler für Strom...) auch dieser Adapter sauber erkannt. 

Nun das Beste, bisher läuft diese Konfiguartion jetzt schon mehrere Stunden ohne den alten Fehler. mule1972 hatte wohl das richte Bauchgefühl. Für den Raspberry-PI 4 wird ja eine andere Imagedatei genutzt. Somit könnte hier ein andere USB-Chip verbaut sein und/oder es wird ein anderer Treiber verwendet.

Aber bevor wir zu früh jubeln, ich lasse das Ganze mal laufen und berichte dann spätestens am Wochenende über mein Endergebnis.

**Comment by mule1972** [comment]
Super, vielen Dank für den Test. Dann drücken wir mal die Daumen, dass es so bleibt. Ich werde am Wochenende mal die verschiedenen Raspberrymatic-Versionen durchtesten, um herauszubekommen mit welcher Version das Problem erstmalig auftritt. Das sollte Jens erheblich helfen.

**Comment by jens-maus** [comment]
Ich würde eher darum bitten hier die Diskussion einzustellen! Dss ist ein Ticket/Issue und kein Diskussionsforum. Bitte solche diskussionen entweder im diskussionsteilndes github Projektes weiterführen oder im homematic forum!

**Comment by mule1972** [comment]
??? Es geht doch hier klar um ein Issue in den aktuellen Pi3-Raspberrymatic-Images bzw. 
im dort enthaltenen Kernel.

**Comment by jens-maus** [comment]
Ich hatte ja bereits vor schließen des issues geschrieben, das es sich hier meiner Meinung nach um ein rein kosmetisches problem handelt. Die Meldung wird ja klar als `user.warn` ausgegeben und das deutet auf eine reine Warnmeldung hin. Ich sehe hier auch momentan keinerlei ansatz für Verbesserungen oder Reparaturen innerhalb von RaspberryMatic. Auch der zusammenhang zu crashes kann ich aus dieser meldung nicht direkt herleiten. Hier müsste mir schon ein crashlog oder eine reproduzierbarer crash geliefert werden. Insofern sehe ich hier nicht wienich hier noch weiter aktiv werden klnnte und der verlauf der diskussion hier hilft bis jetzt auch nicht weiter da nicht klar erkennbar ist das die weiter auftauchenden Personen die exakt gleiche symptomatik haben. Daher eben die bitte das erst einmal ins Diskussionsforum zu verschieben und dort dann zusammen mögliche testszenarien zu diskutieren um eventl eine technischen Zusammenhang zu finden den man dann mit entsprechenden debuginfos untermauern kann um dann hierher irgendwannzurück zu kehren und ggf das ticket wieder zu öffnen (wenn man einen reproduzierbaren fall hat)

**Comment by mule1972** [comment]
Das es sich um ein rein kosmetisches Problem handelt ist eben gerade nicht der Fall, da alle User (inklusive mir) die von den Warnings im Zusammenhang mit USB-Devices berichten eben auch von Komplettabstürzen der Raspberrymatic berichten. Es handelt sich somit definitiv um die identische Symptomatik bei Einsatz verschiedener USB-Devices und dies vermutlich (Tests laufen ja gerade) ausschließlich auf dem Pi3 und nur mit aktuelleren (seit welcher Version genau wollte ich ja wie geschrieben am kommenden Wochenende testen) Raspberrymatic Versionen.
Gerne können wir den Weg zur Ursachenfindung des Issues auch im Forum weiterführen, wirklich verstehen kann ich die Bitte aber nicht, da die Issues unter Github ja eigentlich genau zum Zweck der Ursachenfindung und anschließenden Problembehebung da sind.
Ich werde aber wie gewünscht einen Thread im Forum aufmachen.

Ansonsten: Crashlog wird es leider nicht geben können, da sich Raspberrymatic auf einen Schlag komplett verabschiedetet. Wie gesagt liegt zum Zeitpunkt des Crashs nicht mal mehr ein Signal am HDMI-Port an. Ich hatte auch schon einen Syslog-Server laufen lassen, aber das Log endet dann einfach ohne wirklich interessante Einträge.

**Comment by jens-maus** [comment]
Gut, dann mach ich das Issue zumindest mal wieder auf. Aber ohne eine reproduzierbaren Fall wird das eben wie fischen im Trüben.

**Comment by jens-maus** [comment]
Nach kurzer Recherche, bitte mal folgende Quellen mit ähnlichem Fehlerbild prüfen:

https://github.com/raspberrypi/linux/issues/4074
https://github.com/raspberrypi/linux/issues/3401

Entsprechend eines dieser Tickets bitte mal prüfen ob die Meldung (und ggf. die Abstürze) bei hinzufügen der folgenden Option in der Datei `/boot/config.txt` das Problem lösen:

`dtoverlay=dwc2`

Das wäre dann zumindest ein erster Ansatz zu einer möglichen Lösung.

**Comment by mule1972** [comment]
Danke Dir und danke für die Links. Diese werde ich heute Abend bzw. morgen gleich testen.

Anbei der Link zum Thread im Forum: [https://homematic-forum.de/forum/viewtopic.php?f=65&t=64569](url)

**Comment by diddi68** [comment]
`Entsprechend eines dieser Tickets bitte mal prüfen ob die Meldung (und ggf. die Abstürze) bei hinzufügen der folgenden Option in der Datei /boot/config.txt das Problem lösen:

dtoverlay=dwc2`

Auf meinem Testsystem behebt der Eintrag den Fehler.

Zusatzfrage: Da `/boot` in der fstab als Read-Only gemountet ist, lies sich die `config.txt` nur ändern, indem die fstab geändert und danach neu gebootet wurde. Gibt es da einen einfacheren Weg?

**Comment by jens-maus** [comment]
> > Entsprechend eines dieser Tickets bitte mal prüfen ob die Meldung (und ggf. die Abstürze) bei hinzufügen der folgenden Option in der Datei /boot/config.txt das Problem lösen:<
> 
> > dtoverlay=dwc2<
>
> Auf meinem Testsystem behebt der Eintrag den Fehler.

Dann bitte beobachten/berichten ob damit auch die Abstürze weg sind. Ein generellles nutzen dieser Option muss ich jedoch erst einmal dann prüfen da dies ggf. andere Auswirkungen haben könnte die jetzt schwer abzuschätzen sind
 
> Zusatzfrage: Da `/boot` in der fstab als Read-Only gemountet ist, lies sich die `config.txt` nur ändern, indem die fstab geändert und danach neu gebootet wurde. Gibt es da einen einfacheren Weg?

Das ist vollkommen normal. Aber auch hier hätte ein einfaches `mount -o rw,remount /boot` gereicht. Ein generelles anpassen der fstab ist keine gute idee, denn diese änderung wird beim nächsten firmware-update dann wieder weg sein.

**Comment by mule1972** [comment]
Bei mir sind die Warnings in den Logs nun auch verschwunden. Werde nun beobachten, ob auch das Problem mit den Abstürzen beseitigt ist.

**Comment by mule1972** [comment]
@jens-maus 
Es läuft mit dem Config-Parameter bei mir nun seit 7 Tagen ohne jeglichen Absturz einwandfrei und die Warnings sind auch komplett verschwunden.

**Comment by diddi68** [comment]
> 
> 
> @jens-maus
> Es läuft mit dem Config-Parameter bei mir nun seit 7 Tagen ohne jeglichen Absturz einwandfrei und die Warnings sind auch komplett verschwunden.

Bei mir ebenso.

**Comment by jens-maus** [comment]
Danke für die Rückmeldung. Trotzdem streube ich mich diese Option jetzt als Standard zu machen, denn dadurch wird ein komplett anderer USB Treiber verwendet der andere gewisse Limitationen hat.

**Comment by mule1972** [comment]
Kann ich verstehen, habe mir die entsprechenden Beiträge zu den Unterschieden auch durchgelesen.
Die Frage ist aber, ob man dem eigentlichen Problem auf die Schliche kommen kann, denn ich setze Raspberrymatic seit der ersten Release-Version ein und weder gab es die Warnings, noch die Abstürze. Diese tauchten ja erst mit einer der letzten Versionen auf. Irgendetwas muss da ja durch die Kernel/Treiberentwickler verschlimmbessert worden sein und es kann ja eigentlich kein Raspberrymatic exklusives Problem sein.

**Comment by jens-maus** [comment]
Ist es ja auch nicht wie man in meinem kommentar weiter oben in den referenzen nachlesen kann (https://github.com/jens-maus/RaspberryMatic/issues/1002#issuecomment-760846074). Man kann dort jetzt nur das problem noch einmal vorbringen und auf zukünftige besserung hoffen. D.h. nur ein zukünftiges Kernel update kann das problem beheben. Fraglich wäre nur ob das wirklich nur mit einem Pi3B+ auftritt und die anderen Modelle nicht betroffen sind?!?

**Comment by mule1972** [comment]
Die bisherige Erkenntnis hier aus dem Issue-Thread zu den Pi-Modellen:
Pi3b betroffen
Pi3b+ betroffen
Pi4 nicht betroffen
