### ISSUE TITLE
HmIP Heizungsgruppe  ignoriert IST-Temperatur des Wandthermostates

### ISSUE THREAD

**Issue by Ximerox** [jens-maus/RaspberryMatic#1005]
**Describe the bug**
In einer neu angelegten HmIP-Heizungsgruppe wird die IST-Temperatur des Wandthermostates ignoriert, so dass die Heizungsthermostate die selbst gemessene Temperatur als Basis zur Steuerung nehmen. Fehler ist nicht eindeutig zu reproduzieren, denn manchmal funktioniert es.
Habe das ganze nun mehrfach nachgestellt und habe immer wieder das gleiche Ergebnis. Habe sogar die RapberryMatic komplett gelöscht und neu aufgesetzt und alle Komponenten resettet und neu angelernt. Leider mit dem gleichen Ergebnis.
Ergänzendes Problem: Selbst wenn IST-Temperatur irgendwann funktioniert (durch Resetten und neu Anlernen und Gruppieren der Komponenten - so lange, bis es klappt) bleibt folgendes ergänzendes Problem: Nach dem ein Fenster geöffnet wurde und die Gruppe auf die gewünschte Temperatur gestellt wird (also z.B. 12°C), dann stellt sich die Temperatur nach Schließden des Fensters nicht mehr zurück, sondern bleibt auf den 12°C, obwohl alle Komponenten ein geschlossenes Fenster melden.

**Steps to reproduce the behavior**
1. Komponenten für einen Raum anlernen und bezeichnen
2. Komponenten in einer Gruppe zusammenfassen und warten bis Direktverknüpfugen angelegt sind.
3. Nach etwas warten, die gemeldeten Werte und das Heizverhalten beobachten. 
4. SOLL-Temperatur wird von allen Komponenten der Gruppe übernommen. IST-Temperatur haben nicht alle Komponenten die gleiche Information

**** Zweites Problem, falls Gruppe dann irgendwann mal funktioniert:
1. Fenster öffnen, Temperatur wird abgesenkt
2. Fenster schließen
3. Alle Komponenten melden geschlossenes Fenster
4. SOLL-Temperatur verbleibt weiterhin auf der abgesenkten Temperatur

**Expected behavior**
Die IST-Temperatur wird von allen Heizungsthermostaten vom Wandthermostat übernommen, so dass diese korrekt Heizen.

SOLL-Temperatur stellt sich nach Schließen der Fenster wieder auf eingestellte Temperatur zurück

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: 3.53.34
 - Used Hardware: Raspberry Pi 4b mit RPI-RF-MOD
 - Used HomeMatic RF-Module: ...

**Additional context**
Thread im Homematic-Forum: https://homematic-forum.de/forum/viewtopic.php?f=19&t=62950

**Comment by ProfDrYoMan** [comment]
Ich habe hier bei einem Heizkörper und einem Wandthermostat das gleiche Problem.

In einem anderen Raum habe ich zwei HKs (gleicher Typ, FW) und ein Wandthermostat (gleicher Typ, FW) in einer Gruppe, da geht es.

Ich hatte schon Kontakt zu EQ3 und nach Anweisung von denen mehrfach alles ab und angelernt und die Gruppe neu angelegt. Kein Erfolg.

**Comment by Ximerox** [comment]
> Ich hatte schon Kontakt zu EQ3 und nach Anweisung von denen mehrfach alles ab und angelernt und die Gruppe neu angelegt. Kein Erfolg.

Ja genau das habe ich auch viele Male probiert. Sogar die Komponenten resettet. Manchmal hat das zum Erfolg geführt, aber leider nicht immer.

**Comment by ProfDrYoMan** [comment]
Ich habe immer komplett abgelernt UND die Komponenten zurück gesetzt.

**Comment by Ximerox** [comment]
> Ich habe immer komplett abgelernt UND die Komponenten zurück gesetzt.

Ja, das habe ich ja auch gemacht, hat aber auch nur manchmal funktioniert. Wenn dann noch eine Komponente dazu kam, dann fängt das Spiel von vorne an, alles wieder zurücksetzen und neu anlernen und Gruppe neu bilden. Wenn das nicht funktioniert, nochmal und nochmal und nochmal, so lange bis es geht. Das kann nicht so gewollt sein...

**Comment by ProfDrYoMan** [comment]
In dem einen Zimmer habe ich das dreimal hinter mir. Ohne Erfolg. Zum Glück sitze ich jetzt nah am HK, von daher stört es nicht nicht mehr so, dass es nicht so funktioniert wie gewünscht. Wenn du aber sagst, dass es irgendwann mal funktioniert, sollte ich es vllt. doch noch ein paarmal probieren.

Die IST  Temperaturen differieren teilweise um ein 0,1 oder 0,2 °C zwischen WandT und HK, aber es entspricht nie der "Wahrheit". Wenn es morgens kalt ist, ist es am Fenster problemlos fühlbar >> 1 °C Unterschied, aber Gruppe, HK und WandT zeigen auf max 0,2 C Differenz.

Das WandT is fast maximal weit vom Fenster/HW weg. 20 qm großes Zimmer mit fast 3m Deckenhöhe.

![image](https://user-images.githubusercontent.com/510353/101508533-17051580-3978-11eb-9da8-63f9b88b73e6.png)

Das entspricht ganz sicher nicht der Wahrheit, vor allem in der Heizphase morgens um 8 rum.

**Comment by Ximerox** [comment]
> Die IST Temperaturen differieren teilweise um ein 0,1 oder 0,2 °C zwischen WandT und HK, aber es entspricht nie der "Wahrheit".

Kleine Unterschiede sind ja auch wegen der unterschiedlichen Melde-Zeiten normal, d.h. wenn der WT 20°C zeigt und der HT noch 19,8°C, weil seine letzte Meldung schon 30min her ist. 
Das ist aber nicht das Problem. Mein Problem ist, dass der HT teilweise mehr als 5°C wärmer gemeldet hat, weil es nicht die Temp vom WT angenommen hat, sondern die selbst gemessene und dann nicht mehr geheizt hat, obwohl der Raum noch deutlich unter der gewünschten Temp lag. Beispiel: Wunschtemp: 20°C, WT misst 18°C, HT misst, weil die Heizung gerade an war und der HT es hinterm Vorhang schön warm hat 25°C. Da 25°C ja mehr als die gewünschten 20°C sind, geht das Ventil zu, obwohl der WT nur 18°C misst und die HT daher eigentlich weiter heizen sollte. Es ignoriert also einfach die gemessene Temp des WT und nimmt die selbst gemessene.

Ich bereits gerade dem Umzug von RaspberryMatic vom Raspi in eine virtuelle Maschine unter Proxmox vor. Hoffentlich gehen mir die funktionierenden Gruppen nicht kaputt...

**Comment by ProfDrYoMan** [comment]
Genau das was du beschreibst ist bei mir ja auch der Fall.

Soll 20C. HK schon bei 21C. WandT bei 18C. Gruppe bei 21C und nicht wie es sein sollte bei 18C. => Heizung geht aus.

Vllt. ist die Reihenfolge des Anlernens, Gruppenbildung relevant?

**Comment by ProfDrYoMan** [comment]
So, ich hatte jetzt mal Zeit. Ich habe es zweimal probiert.

- Ablernen der zwei Geräte (HK, WandT) mit Reset (nicht per HW)
- Gruppe löschen
- Anlernen der zwei Geräte
- Gruppe anlegen
- 1. Versuch: Zuerst HK, dann WandT anlernen
- 2. Versuch: Zuerst WandT, dann HK anlernen

Ergebnis: Kein Erfolg. Die Temperatur von HK und WandT (und der Gruppe) sind immer gleich.

Prüfung: WandT in einen geheizten Raum, während das Zimmer mit dem HK kalt ist. => Eindeutig fehlerhafte Funktion.

Ideen?

**Comment by Sineos** [comment]
RedMatic installieren und die Steuerung darüber machen 😉

**Comment by ProfDrYoMan** [comment]
Home Assistant läuft eh schon. Homematic stellt mir "nur" die Geräte bereit, ...

Aber im Wohnzimmer funktioniert es hinreichend gut. Ich habe keine Lust mir das eine Regelung zu implementieren, vor allem, weil man den Ventillevel nicht setzen kann.

**Comment by Ximerox** [comment]
> Ergebnis: Kein Erfolg. Die Temperatur von HK und WandT (und der Gruppe) sind immer gleich.

Ich nehme an, dass du "unterschiedlich" meinst, "gleich" wäre ja das was wir wollen

Steuerung über RedMatic würde ja gar nicht gehen, da der Thermostat den Ventillevel aufgrund von SOLL und IST setzt, den kann ich von außen nicht beeinflussen, nur ablesen.

**Comment by ProfDrYoMan** [comment]
Nein, gleich ist nicht das was ich wünsche.

Wenn das WandT (Wandthermostat) in einem geheizten Raum mit sagen wir 21C ist, wird es 21C anzeigen.
Der HK (Heizkörperthermostat) ist im ungeheizten Raum und hat sagen wir 18C.

In Homematic erwate ich:
- HK 18C
- WandT 21C
- Gruppe 21C (denn da soll das vom WandT übernommen werden.)

Ich habe für die Temperatur des HK immer auch die 21C was falsch ist.

So sieht es im WZ aus. Da ist es korrekt:

![image](https://user-images.githubusercontent.com/510353/102763930-a5b36280-437a-11eb-9e75-62fe5aecb3a1.png)

- Rot: HK rechts im Raum
- Cyan: HK links im Raum
- Blau: WandT

Ich habe um 9 man kurz den Fön an den rechten HK gehalten. Man sieht schön, wie der alleine hochgeht.
So erwarte ich das. Drei Messwerte die getrennt angezeigt werden.

Und nun im anderen Zimmer wo es nicht geht.

![image](https://user-images.githubusercontent.com/510353/102764112-e8753a80-437a-11eb-9838-e09e1d3fac1a.png)

- Rot: HK
- Cyan: WandT

Um 7:30 habe ich den WandT in eine geheiztest Zimmer gebracht. HK "geht mit" was falsch ist.

**Comment by jens-maus** [comment]
Tschuldigung wenn ich unterbreche. Aber das ist hier kein Diskussionsforum, sondern ein Bug/Issue-Tracker. Das Problem wurde hier bereits benannt und erläutert. Die anderen neulichen Informationen tragen jetzt aber IMHO nichts mehr zum ursprünglichen Problem bei soweit ich das überblicke. Also bitte Diskussionen ins homematic forum verlagern oder aber in den Diskussionsbereich hier im GitHub (siehe https://github.com/jens-maus/RaspberryMatic/discussions)

**Comment by Ximerox** [comment]
Das ist aber genau das Verhalten, das erwartet wird. Der HT muss ja die Temp vom WT haben, damit er korrekt heizen kann. Dein Problem ist genau anders herum und hat damit hier nichts verloren.

**Comment by jens-maus** [comment]
Also ich kann das Problem hier selbst nicht reproduzieren und in meinen eigenen HmIP Heizungsgruppen funktioniert die Temperatur/Ventilsteuerung wie erwartet auch unter einbeziehen des Wandthermostates. Inosfern sehe ich hier momentan keinen Handlungsbedarf. Darüberhinaus findet die Temperatursteuerung komplett mittels Direktverknüpfungen statt. D.h. Also komplett in den geräten selbst. Darauf hat die RaspberryMatic also keinerlei Einfluss.

**Comment by Ximerox** [comment]
Schade, da es bei mir immer noch nicht funktioniert - und das zu 100% reproduzierbar - finde ichs schade, dass das hier einfach geschlossen wird. Wäre dann wenigstens schön, einen Hinweis zu bekommen, wohin ich mich dann noch wenden kann. Ich habe mehrere 100€ für ein System in die Hand genommen, dass nicht funktioniert. Von 8 Räumen funktioniert es in einem.

**Comment by jens-maus** [comment]
@Ximerox Nun, dann solltest du in den üblichen Diskussionsforen (homematic-forum.de) z.B: Hilfe dafür suchen oder das Problem dort ausführlich diskutieren. Und wenn dabei rauskommt, dass es sich hier definitiv um ein Bug/Problem handelt ist hier der Hersteller (eQ3) natürlich zu informieren und einzubeziehen. Im Rahmen des RasberryMatic Projektes kann man nämlich hier keine Verbesserungen erwarten, denn die Komponente in der die gesamte Logik diesbzgl. steckt ist einerseits der `HmIPServer` der komplett closed source ist und zweitens steckt viel Logik in den HomeMatic Geräten selbst (Thermostaten, Heizkörperventilen) und auch dafür ist die Firmware komplett closed source und nur für den Hersteller (eQ3) einsehbar.

**Comment by Ximerox** [comment]
Ja, im Forum hatte ichs zuerst versucht, aber da konnte auch keiner weiterhelfen. Scheinbar bin ich damit recht alleine - was ich mir eigentlich nicht vorstellen kann. Das einzige was ich noch nicht versucht habe, ist eine original CCU3 zu verwenden (hatte bisher eine RasperryMatic und im Moment bin ich auf debmatic - aber überall das gleiche).
EQ3 habe ich auch schon angeschrieben - da warte ich noch auf Antwort.
