### ISSUE TITLE
cloudmatic Reverse proxy Dienst funktioniert nicht mehr

### ISSUE THREAD

**Issue by Matten-Matten** [jens-maus/RaspberryMatic#1006]
Hallo, seit der neuen Version im November funktioniert bei mir der cloudmatic  Reverse proxy Dienst nicht mehr. 

Es half nur ein downgrade auf die Version vom Oktober.

Gruß
Matten Matten

**Comment by jens-maus** [comment]
Bekannt und bereits auch für die nächste kommende Version repariert. Das nächste mal aber bitte das Ticket template komplett ausfüllen und nicht einfach löschen/ersetzen!

**Comment by Matten-Matten** [comment]
Hallo Jens-Maus,
Ich habe nichts gelöscht. 

Wenn man mit einem Mobiltelefon
Ein issue eröffnet und noch nicht angemeldet
Ist wird erst die Anmeldung vorgeschlagen und danach sind die Felder leer.
![Screenshot_20201208_093245](https://user-images.githubusercontent.com/32074970/101459725-e5b92500-3938-11eb-9e12-53d888b41a3c.jpg)

Aber trotzdem danke für die zügige Antwort

Schöne Grüße
Matten Matten
