### ISSUE TITLE
Enhancement: sSMTP als lightweight Postausgangsserver integrieren

### ISSUE THREAD

**Issue by beja-hs-furtwangen** [jens-maus/RaspberryMatic#1008]
**Is your feature request related to a problem? Please describe.**
Es wäre super, wenn man das E-Mail-Addon auch mit einem auf dem RaspberryMatic als localhost laufenden SMTP-Mailer verwenden könnte.

**Describe the solution you'd like**
Ein leichtgewichtiger SMTP-Mailer, bspw. sSMTP könnte dazu integriert oder als Addon angeboten werden.

**Describe alternatives you've considered**
Alternativen wären postfix o. ä., aber die sind deutlich komplexer zu konfigurieren.

**Additional context**
...

**Comment by jens-maus** [comment]
RaspberryMatic wird bereits, genauso wie eine Standard CCU3/CCU2 mit dem `msmtp` lightweight command-line tool ausgeliefert das bereits alle notwendigen funktionalitäten für das versenden von E-mails via SMTP verbindungen mit bringen sollte. Als CCU-Addon benutzt auch das CCU E-Mail addon bereits diesen kommandozeilen smtp client.

Insofern sehe ich keinen weiteren bedarf für irgendeinen anderen SMTP client.
