### ISSUE TITLE
Missing limitation in read.me

### ISSUE THREAD

**Issue by drose28357** [jens-maus/RaspberryMatic#101]
Shouldn´t we have this line in Limitation ? :

No firmware updates with HomeMatic-RF GPIO Funkmodul (HM-MOD-RPI-PCB) 

P.S. im Forum steht im Readme dieser Satz, bei dem die Semantik etwas unklar ist: 
Dies bringt eine Reihe **von Vorteilen** mit sich, die bei der Stabilität und Performance in der Kommunikation mit den HomeMatic-Geräten **von Vorteil** sein kann, ....

Vieleicht so:
Dies bringt eine Reihe von Vorteilen mit sich, die die Stabilität und Performance in der Kommunikation mit den HomeMatic-Geräten erhöhen kann, ....

**Comment by jens-maus** [comment]
@drose28357 Das generell keine firmware updates möglich sind stimmt so ja nicht ganz. es betrifft nur eine gewisse menge von geräten, aber eben nicht alle.
