### ISSUE TITLE
HMIP-HAP als Gateway mit laufendem Firmware führt zu DC 80%-100%

### ISSUE THREAD

**Issue by ThomasLoeffel** [jens-maus/RaspberryMatic#1013]
Hallo Jens,

danke für Deinen / Euren super Job.

### **Systeminformation:**
 - RaspberryMatic Version: 3.53.34.20201121
 - Hardware: Asus Tinker+, Charly
 - Used HomeMatic RF-Module: RPI-RF-MOD auf Tinker gesteckt.
 - Zwei HM-Gateways (original)
 - Ein HMIP-HAP als Gateway 
 - USB Stick

### **Fehlerbeschreibung:**
Alles läuft stabil und der DC verhält sich auch normal. Sobald ich die Firmware eines Aktors hinterlege steigt der DC gewohnt an. Schwingt so bis ca. 60% und dann wieder runter. Dieses natürlich in Abhängigkeit von der Grundlast.  

Diagramm nach einem Neustart (27.11)
![20201127_DutyCycle_2](https://user-images.githubusercontent.com/44590735/101998865-4d73c500-3cd7-11eb-85ba-a1cf39e901ad.JPG)

Nachdem ich den HAP stromlos mache sinkt der DC auch wieder.

Zur Reproduktion habe ich einmal den HAP wieder angeschlossen (13.12):
![20201212_dc](https://user-images.githubusercontent.com/44590735/101998882-814eea80-3cd7-11eb-9d6b-70060885e2f0.JPG)

Hier einmal eine Sicht der letzten 7 Tage (Firmware Update läuft):
![20201212_dc_2](https://user-images.githubusercontent.com/44590735/101998943-16ea7a00-3cd8-11eb-8f96-1c96361f2975.JPG)

### **Steps to reproduce the behavior:**
1. System beruhigen lassen
2. Firmware Aktoren einspielen
3. System beruhigen lassen
4. HAP an Strom anschließen

Dieses hat bei mir 4 Mal so funktioniert. Der DC ist verlässlich auf 100% gestiegen.

### **Expected behavior:**
Ich hatte erwartet das der DC im Vergleich zum Tinker ohne HAP sinkt. Da ja der HAP Aktoren erreicht (laut AskSin Analyser).

Meine laienhafte Vermutung ist das der DC bei angeschlossenem HAP in Verbindung mit einem Firmwarevorgang nicht richtig berechnet oder begrenzt wird.

Lieben Gruß Thomas Löffel

**Comment by ThomasLoeffel** [comment]
Hallo Jens,

was kann ich aus Deiner Sicht noch an Daten zusteuern? 

Da der DC beginnend mit unseren Familienaktivitäten sich immer gegen die 100% entwickelt habe ich den HAP Heute gegen ca. 11:00 Uhr wieder stromlos gemacht und es beruhigte sich wieder.

![image](https://user-images.githubusercontent.com/44590735/102011664-02dd6180-3d46-11eb-8a68-656fec975090.png)

Gruß Thomas Löffel

**Comment by ThomasLoeffel** [comment]
Hallo Jens,

was kann ich aus Deiner Sicht noch an Daten zusteuern? 

Da der DC beginnend mit unseren Familienaktivitäten sich immer gegen die 100% entwickelt habe ich den HAP Heute gegen ca. 11:00 Uhr wieder stromlos gemacht und es beruhigte sich wieder.

![image](https://user-images.githubusercontent.com/44590735/102011664-02dd6180-3d46-11eb-8a68-656fec975090.png)

Gruß Thomas Löffel


PS. Für die schnelle Reaktion :-).

**Comment by jens-maus** [comment]
> was kann ich aus Deiner Sicht noch an Daten zusteuern?

Gar nichts. Da kann ich auch nichts dran machen oder drehen, da das die Baustelle von eQ3 ist.

**Comment by ThomasLoeffel** [comment]
Hallo Jens,

danke für die schnelle Antwort. Ich lasse für die Firmwareupdates dann den HAP einfach stromlos.

Lieben Gruß und schönen dritten Advent :-).

Gruß Thomas

**Comment by jens-maus** [comment]
Wenn deine gesamte Installation auch gut ohne HmIP-HAP funktioniert dann würde ich dir sogar empfehlen komplett darauf zu verzichten. Dieses ganze "Advanced Routing" läuft momentan leider noch sehr suboptimal und macht IMHO mehr Probleme als es versucht Probleme zu lösen.
