### ISSUE TITLE
Internal updater installs wrong image for pi3 on pi2 - boot failes

### ISSUE THREAD

**Issue by makroground** [jens-maus/RaspberryMatic#1017]
I was at 3.53.30.20201024 and the Updater addons says to me, version 3.53.34.20201121 is availible for update. I clicked on the Update-Button (not insert any URL to an zip-file) and it starts to download the "*-rpi3.zip"-file, the recovery system flashes it also without any errors. Than die Pi restarts and could boot no more, because my Raspberry Pi is an Model 2 B, not a Model 3 B. 

Temporary fix: I removed the sdcard and inserted it to one of my other Pi's, which is indeed a Model 3 B and could get the raspberrymatic back to life, but I need this Pi and would like to go back to Pi 2 B immediately!

How can I now downgrade and change the system back to Raspberry Pi Model 2 B?

**Comment by jens-maus** [comment]
Sorry, but the "Updater Addon" (`System Update` button) is a third party addon and nothing directly integrated in RaspberryMatic. Thus, please complain/open your issue in this project instead (https://github.com/j-a-n/raspberrymatic-addon-rmupdate)

**Comment by makroground** [comment]
@jens-maus Thankyou for your quick reply and the hint to this other project page. I'll give it another try and hopefully stay positive against the help of @j-a-n !
