### ISSUE TITLE
Ankündigung neuer Gerätefirmware aktualisiert sich nicht automatisch

### ISSUE THREAD

**Issue by KnutSchweinfurth** [jens-maus/RaspberryMatic#1018]
**Describe the bug**
Wenn neuen Geräte-Firmware vorliegt, zeigt die WebUI dies an.
Aktualisiert man die Firmware eines oder mehrerer Geräte, wird diese Anzeige (Anzahl) nicht automatisch aktualisiert.
Man muss die WebUI neu starten, um den aktuellen Stand zu sehen.

**Steps to reproduce the behavior**
1. ...
2. ...
3. ...
4. ...

**Expected behavior**
Direkt nach dem Update sollte die Anzeige der zur Verfügung stehenden
Updates (Anzahl) aktualisert werden.

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: 3.53.34.20201121
 - Used Hardware: ...
 - Used HomeMatic RF-Module: ...

**Additional context**
...

**Comment by jp112sdl** [comment]
> Man muss die WebUI neu starten, um den aktuellen Stand zu sehen.

Ja, weil der Check nur 1x beim Laden der WebUI (clientseitig im Browser) erfolgt.
Wenn man das zyklisch alle paar Sekunden machen wollte, wird die (Browser-)Performance darunter leiden.

**Comment by jens-maus** [comment]
Genau so ist es, deshalb heisst es hier auch: "It's not a bug, it's a feature". Folglich schließe ich dieses Ticket hier weil das ein beabsichtigtest und gleichzeitig vernachlässigbares verhalten ist.
