### ISSUE TITLE
Teach In Module error message "BidCos-RF teach-in mode could not be activated"

### ISSUE THREAD

**Issue by Karl85** [jens-maus/RaspberryMatic#102]
When opening the RaspberryMatic http://homematic-raspi/ and starting the Teach In Module the error message "BidCos-RF teach-in mode could not be activated" (BidCos-RF Anlernmodus konnte nicht aktiviert werden.) is displayed
thanks for any help!

**Comment by jens-maus** [comment]
This is no support fora but a bug/issue tracker of KNOWN bugs in RaspberryMatic. If you cannot start the teach in mode this is certainly no general issue of RaspberryMatic but a user problem. So please go to http://homematic-forum.de/ and ask for help there instead. Only post issues here if you actually found a bug in RaspberryMatic or if you have an enhancement request to add a certain feature.
