### ISSUE TITLE
RM Gateway "verbunden" mit "-1%" im Status und keiner Verbindung zur RM

### ISSUE THREAD

**Issue by friedpa** [jens-maus/RaspberryMatic#1022]
**Describe the bug**
Ich habe eine RM mit einem RM Gateway und einem eQ3 Gateway in Betrieb. Das EQ3 GW hängt stabil seit Jahren an der RM. Das RM Gateway verabschiedet sich nach oft monatelangem Betrieb und ist dann zwar nach einem Reboot der RM wieder "online" geht aber nach zwei - drei Stunden "offline" Wundern tue ich mich über die Meldung:
![grafik](https://user-images.githubusercontent.com/42890695/102532847-deb2b500-40a4-11eb-804a-e54048b42787.png)
Dachte -1% bedeutet nicht verbunden? Man muss dann sehr oft die RM und das RM Gateway rebooten, irgendwann "erwischt" man dann das richtige Timing und man hat wieder Ruhe.
Vielleicht hat ja jemand ähnliche Probleme (gehabt) und weis eine Lösung?

**Expected behavior**
Stabile Verbindung zwischen RM und RM Gateway

**Screenshots**
siehe oben
![grafik](https://user-images.githubusercontent.com/42890695/102533880-41f11700-40a6-11eb-8910-972284d7c9ec.png)

**System information:**
 - RaspberryMatic Version: 3.53.34.20201121
 - Used Hardware: RPi4
 - Used HomeMatic RF-Module: ...

**Comment by thefox73** [comment]
I can confirm this issue. I'm running RaspBerrymatic on a RPi 3B. Additionally I'm using 3 LAN-Gateways

- a CCU2 configured as LAN-Gateway
- a RPi 1B with Raspberrymatic runnig as LAN-Gateway
- another RPi 1B with Raspberrymatic runnig as LAN-Gateway

Randomly one of the RPi gateways is losing connection to the RaspberryMatic as described by friedpa.
Always the same RPi is affected. After a FW-Upgrade or reboot the RPi-LAN-gateway is connected again.
It can happen that the connection is staying stable for several weeks, but then without any visible reason the gateway is losing connection again

**Comment by jens-maus** [comment]
Duplicate of #978
