### ISSUE TITLE
Falsche Nummer bei der automatischen Kanalbezeichnung

### ISSUE THREAD

**Issue by SukramJ** [jens-maus/RaspberryMatic#1023]
**Describe the bug**
Im Nightly (RaspberryMatic-3.55.5.20201218-512bb7-ova.zip) wird bei der (neuen) automatischen Kanalumbenennung eine um eins zu hohe Kanalnummer zugeordnet.

**Steps to reproduce the behavior**
1. Allgemeine Geräte Einstellungen öffen
2. Auf Kanäle umbenennen klicken
3. Kanale in Geräteliste anschauen

Dem Kanal 3 des "Bewegungsmelder" wurde die Bezeichnung Bewegungsmelder:4 zugeordnet

**Expected behavior**
Erwartet wird die wurde die Bezeichnung Bewegungsmelder:3
**Screenshots**
...

**System information:**
 - RaspberryMatic Version: RaspberryMatic-3.55.5.20201218-512bb7
 - Used Hardware: Proxmox VM
 - Used HomeMatic RF-Module: RPI-RF-MOD

**Additional context**
...

**Comment by jp112sdl** [comment]
Bitte Workaround aus dem Homematic Forum testen:
https://homematic-forum.de/forum/viewtopic.php?f=65&t=63716&start=10#p628130

**Comment by SukramJ** [comment]
Hmmh, wie kann ich webui.js editieren? Die Datei ist readonly.

**Comment by jp112sdl** [comment]
Schreibschutz aufheben per SSH:
`mount -o remount,rw /`

**Comment by jens-maus** [comment]
@jp112sdl Wenn du bis 1:00 noch nen PR dazu schickst schafft es das in den morgigen nightly build.

**Comment by SukramJ** [comment]
Der fix funktioniert für meine HMIP Geräte.
Vielen Dank.

**Comment by jens-maus** [comment]
@jp112sdl Danke für den PR. Dann bitte mit dem morgigen snapshot neu probieren ob dort auch das Problem beseitigt ist.
