### ISSUE TITLE
USB-Boot Mode Pi3B / Pi4B - Setup onboard LEDs schlägt fehl

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1028]
**Describe the bug**
Beim Start von RaspberryMatic auf Pi3B & Pi4B im USB-Boot Modus wird die "Funktion" der roten Onboard-LED des Raspi's nicht korrekt gesetzt. Beim Start sieht man am Monitor eine "Fehlermeldung" 
_Setup onboard LEDs: sh: write error: Invalid argument_

**Steps to reproduce the behavior**
1. RaspberryMatic im USB-Boot Modus starten
2. Ausgaben auf dem angeschlossenem Monitor betrachten

**Expected behavior**
Normalerweise wird ja der roten Raspi-LED über _/sys/class/leds/led1/trigger_ der "Status" mmc0 gesetzt. Das scheint hier fehlzuschlagen da der Befehl wegen fehlender mmc0 ins leere läuft. Hier müsste wohl der Pfad entsprechend dem BootMedium angepasst werden.
Des weiteren wäre "mmc0" beim USB-Boot Modus nicht zielführend da keine SD-Karte im System vorhanden ist. 
Dadurch das der Befehl ins leere läuft verbleibt _/sys/class/leds/led1/trigger_ auf "activity" was meines Erachtens auch die einzig nützliche Funktion für die rote Raspi-LED (in diesem Falle) ist.

**Das Ganze sehe ich eher als "Schönheitsfehler". Handlungsbedarf besteht nicht wirklich da die rote Raspi-LED den (aus meiner Sicht) einzig nützlichen Status wiedergibt.**

**System information:**
 - RaspberryMatic Version: 3.55.5.20201220 (Nightly Snapshot)
 - Used Hardware: Pi4B 2GB
 - Used HomeMatic RF-Module: HM-MOD-RPI-PCB auf HB-RF-ETH

**Comment by jens-maus** [comment]
Danke für die Info. Das scheint ein generelles problem im aktuellen Snapshot zu sein und nicht beschränkt auf einen USB Boot. Bitte mal bei den anderen Platformen noch testen wenn möglich.

**Comment by jens-maus** [comment]
Bitte mal kontrollieren das mit der Änderung aus https://github.com/jens-maus/RaspberryMatic/commit/eb8e5e4b1268604b51c191f0fb1ed8344193bed2 das problem beim starten beseitigt ist und keine Fehlermeldung mehr kommt. Dann bitte auch die anderen Platformen damit testen.

**Comment by Baxxy13** [comment]
> das mit der Änderung aus [eb8e5e4](https://github.com/jens-maus/RaspberryMatic/commit/eb8e5e4b1268604b51c191f0fb1ed8344193bed2) das problem beim starten beseitigt ist

Für von SD-Karte bootende Systeme sind die Fehlermeldungen weg.
Bei von USB bootenden Systemen tauchen sie weiterhin auf.

Getestet mit: RaspberryMatic-3.55.5.20201221-31097c-rpi4

**Comment by Baxxy13** [comment]
> Dann bitte auch die anderen Platformen damit testen.

Da das "Problem" weiterhin besteht, getestet mit RaspberryMatic 3.55.5.20201226 im USB-Boot Modus, wäre es wünschenswert wenn du das Ticket wieder öffnen würdest.

**Comment by jens-maus** [comment]
Ok ich hab das Issue wieder aufgemacht um mir es später noch einmal anzuschauen. Allerdings ist es so, das ich auf die schnelle keine Einstellung für das setzen der roten LED auf das genutzte USB Medium finden konnte. Diese werden ja als `/dev/sdX` eingebunden und bis jetzt habe ich dafür in der sysfs basierten LED Ansteuerung noch keine Möglichkeit gefunden diese auf die Schreiboperationen dieses mediums zu setzen. Daher wäre der einzige weg diese fehlerausgaben gänzlich zu vermeiden. Die rote LED wird dann aber trotzdem nicht mit den USB Operationen verbunden sein.

**Comment by Baxxy13** [comment]
Danke. Ist ja auch nicht soo wichtig. 
Hängt denn...
_Identifying onboard hardware: sh: write error: Invalid argument_
direkt damit zusammen?

Mein "Workaround" ist ein WebUI-Programm mit leerem Wenn und folgendem Scriptschnippsel.
`system.Exec("echo activity >/sys/class/leds/led1/trigger");`

Dadurch sehe ich dann wenn die SSD in Benutzung ist,

**Comment by jens-maus** [comment]
Ja, das hängt zusammen. Du kannst gerne mal den morgigen snapshot probieren. Dort sollte es jetzt zusätzlich ein `usb-host` trigger geben. Hab das noch nicht getestet, aber vielleicht lässt sich damit ja irgendwas abbilden bzgl. USB device aktivität.

**Comment by jens-maus** [comment]
> Mein "Workaround" ist ein WebUI-Programm mit leerem Wenn und folgendem Scriptschnippsel.
> `system.Exec("echo activity >/sys/class/leds/led1/trigger");`
> 
> Dadurch sehe ich dann wenn die SSD in Benutzung ist,

Das ist komisch, denn `activity` sollte auf CPU Aktivität zurückgehen und nicht auf Aktivität der SSD. Zumindest laut dokumentation ist der `activity` trigger mit der CPU Aktivität verbunden.

**Comment by Baxxy13** [comment]
> Das ist komisch,

Vielleicht täusch mich mein Pi4B auch. Zumindest flackert die rote Raspi-LED ordentlich wenn ich z.B. ein Backup erzeugen lasse oder der Historian auf die DB zugreift.

**Comment by jens-maus** [comment]
Nun, all das ist ja auch mit CPU Nutzung verbunden. Die Frage ist nur ob das wirklich NUR mit Disk nutzung korreliert, was ich bezweifle.

**Comment by Baxxy13** [comment]
> ob das wirklich NUR mit Disk nutzung korreliert, was ich bezweifle.

Wenn du eine Idee hast wie ich den Pi auslasten kann ohne Schreib/Lesezugriff auf die SSD dann könnte ich das gegenchecken.

**Comment by jens-maus** [comment]
> Wenn du eine Idee hast wie ich den Pi auslasten kann ohne Schreib/Lesezugriff auf die SSD dann könnte ich das gegenchecken.

Probier mal folgendes Kommando:

```
sha1sum /dev/zero | sha1sum /dev/zero | sha1sum /dev/zero | sha1sum /dev/zero
``` 

damit sollte nur die CPU ausgelastet werden ohne Diskzugriff.

**Comment by Baxxy13** [comment]
> Probier mal folgendes Kommando:

Schöner Test. Der Pi4 hat Herzrasen und Hitzewallungen bekommen. Konnte ich gleich mal ein paar frische WatchDog-Alarme sehen. 

Aber du lagst natürlich richtig, "activity" korreliert mit der Systemaktivität und nicht mit Schreib/Lesezugriffen auf die SSD.

Ich schaue mir dann morgen mal den Snapshot an.

Danke erstmal bis hier!

**Comment by Baxxy13** [comment]
> jetzt zusätzlich ein `usb-host` trigger geben.

`echo usb-host >/sys/class/leds/led1/trigger`
Sieht gut aus, aber nur solange man ein GPIO-Modul nutzt. Ist die HB-RF-USB im Einsatz (beim Pi4 ja fast zwingend notwendig) flackert die Rote Raspi-LED wegen der USB Kommunikation ordentlich vor sich hin.

Einen Trigger für /dev/sda gibt's nicht zufällig?

**Comment by jens-maus** [comment]
> Einen Trigger für /dev/sda gibt's nicht zufällig?

Also ich hab leider noch keinen Weg dafür gefunden einen LED trigger auf ein device zu setzen. Da gibt es wohl vom standard kernel aus keinen Weg und man müsste das über drittanbieter kernelmodule abdecken. Aber ob sich der Aufwand lohnt weiss ich nicht.

**Comment by jens-maus** [comment]
@Baxxy13 Ok, I habe nochmal nachgeschaut und konnte nun den `disk-activity` trigger noch aktivieren. Mit dem nächsten nigtly snapshot sollte der auch verfügbar sein. Bitte dann morgen noch einmal genau testen ob vielleicht dieser passfähiger wäre bzw. die SSD Aktivität wiedergibt wenn dieser entsprechend aktiviert wurde.

**Comment by Baxxy13** [comment]
> den `disk-activity` trigger

Habe alle Trigger mit `disk-xxx` ausprobiert. Leider keinerlei Reaktion der Raspi-LED. Weder bei Schreib/Lesezugriffen auf die SSD noch bei sonstigen Aktivitäten. Schade. 

Vielleicht fällt Dir ja dazu noch was ein, ist aber keinesfalls dringend.

**Comment by jens-maus** [comment]
@Baxxy13 Ok, danke. Kannst du mal dann schauen ob der `disk-activity` trigger auf Lese/Schreiboperationen auf die SD karte reagiert?

**Comment by Baxxy13** [comment]
> Lese/Schreiboperationen auf die microSD

Keine Reaktion der Raspi-LED bei aktivem `disk-activity` und Schreib/Lesevorgängen auf der SD-Karte sowie auf einem angeschlossenem USB-Stick.

Da es nix bringt kann's auch wieder raus denke ich. Teste aber gerne (nächstes Jahr) weiter sollte es noch Alternativen geben.

Den Trigger `usb-host` aber bitte belassen, der macht sich hier am Sekundärsystem gut da nix außer der SSD am USB hängt.

Für's zukünftige Hauptsystem ist es eigentlich ziemlich egal (momentane Wahl wäre `activity`), da System ist eh so versteckt verbaut das niemand die LED's sieht. ;-)

**Comment by jens-maus** [comment]
Gut, dann kommen wir wohl hier nicht weiter und ich werde zumindest schauen das die von dir benannten `sh: write error: Invalid argument` Fehlermeldungen weg sind. Zweitrangig und vernachlässigbar ist dann eben das die rote LED standardmäßig dann keinerlei funktion mehr hat wenn man via USB Boot arbeitet. Oder jemanden fällt noch eine Möglichkeit ein wie man dieses Feature dem Linux Kernel entlocken kann.

**Comment by jens-maus** [comment]
Ok, nun bitte mal schauen ob mit dem nächsten nightly snapshot die fehlermeldungen weg sind. Die LED wird dann zwar immer noch nicht die USB operationen wiedergeben, aber zumindest die fehlermeldungen sind dann hoffentlich weg.

**Comment by Baxxy13** [comment]
Rückmeldung:
Mit dem heutigen Snapshot 3.55.5.20201230-793738 sind die Fehlermeldungen weg und der Trigger für die rote Raspi-LED steht nach dem Booten auf "none".

Nun funktioniert mein Trick mit der rc.local (eingetragen _echo usb-host >/sys/class/leds/led1/trigger_) nicht mehr.
Wird die vor _/etc/init.d/S99SetupLEDs_ abgearbeitet?
Ist aber nicht dramatisch, über ein WebUI Programm mit Einzeilerscript _system.Exec("echo usb-host >/sys/class/leds/led1/trigger");_ funktioniert es dann wie geplant.
