### ISSUE TITLE
USB-Boot Mode Pi3B / Pi4B - Fehlermeldung beim booten "Identifying onboard Hardware"

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1029]
**Describe the bug**
Beim booten von USB sieht man bei angeschlossenem Monitor ziemlich am Anfang folgende Fehlermeldung:
_Identifying oboard hardware: sh: write error: Invalid argument_
Vermutlich möchte RaspberryMatic hier etwas in eine Datei schreiben was aber mangels korrektem Pfad (keine SD-Karte vorhanden) fehlschlägt. 

**Steps to reproduce the behavior**
1. RaspberryMatic im USB-Boot Modus starten
2. Ausgaben auf dem angeschlossenem Monitor betrachten

**System information:**
 - RaspberryMatic Version: 3.55.5.20201220 (Nightly Snapshot)
 - Used Hardware: Pi4B 2GB
 - Used HomeMatic RF-Module: HM-MOD-RPI-PCB auf HB-RF-ETH

**Additional context**
Ich konnte keine Einschränkungen oder Fehlfunktionen aufgrund der Fehlermeldung feststellen. Ich sehe das eher als "Schönheitsfehler".

**Comment by jens-maus** [comment]
Duplicate of #1028
