### ISSUE TITLE
Device Firmware Update lädt nicht

### ISSUE THREAD

**Issue by mh-82** [jens-maus/RaspberryMatic#1033]
### **Describe the bug**
Beim Versuch neue Device Firmware auf die CCU zu laden bleibt der Loading Screen noch vor dem Upload der Firmware stehen.
Die Seite muss neu geladen werden um wieder zu funktionieren.

### **Steps to reproduce the behavior**
Settings --> Device Firmware - Overview --> Device Firmware

### **Expected behavior**
Device Firmware upload sollte möglich sein

### **Screenshots**
![image](https://user-images.githubusercontent.com/76215948/102793994-f773e100-43aa-11eb-9eec-97d49141c31e.png)

### **System information**
RaspberryMatic Version: 3.53.34.20201121
Used Hardware: RaspberryPi 3b+
Used HomeMatic RF-Module: Raspberrymaticshop Funkmodul mit Stabantenne

### **Additional context**

- Raspberrymatic schon einmal komplett neu geflashed und backup eingespielt.
- Logfile nach neuem flash und test vorhanden.

Update:
- Keine Änderung nach Update auf 3.55.5.20201226

**Comment by slankes** [comment]
Duplicate of #882
