### ISSUE TITLE
Kommunikation zwischen RaspberryMatic über Mqtt + Redmatic mit anderen Geräten (Tasmota, Octoprint) nicht mehr möglich

### ISSUE THREAD

**Issue by Newbie-2** [jens-maus/RaspberryMatic#1034]
**Describe the bug**
Ich nutze Octoprint und Tasmota um mit der RaspberryMatic per Mqtt durch RedMatic V7.1.3 und Mosquitto V1.5.8+2 Daten auszutauschen. Mit der Version RaspberryMatic-3.53.30.20201024-rpi3 ist es problemlos möglich. 
Sobald ich die Version RaspberryMatic-3.53.34.20201121-rpi3 "..34..." installiere, verbindet sich Mqtt nicht mehr. Installiere ich wieder die ältere Version "...30..." wird die Mqtt Verbindung problemlos aufgebaut. 
  

**Steps to reproduce the behavior**
1. ...
2. ...
3. ...
4. ...

**Expected behavior**
...

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: RaspberryMatic-3.53.30.20201024
 - Used Hardware: Pi3
 - Used HomeMatic RF-Module: Kleinen ELV Funkmodul

**Additional context**
Kann der Fehler mit der neuen RaspberryMatic Version behoben werden ?

**Comment by jens-maus** [comment]
Das liegt am nicht mehr funktionierenden Mosquitto Addon seit der 3.53.34.20201121. Das Problem ist bereits beseitigt und wird mit dem nächsten Release behoben sein.

**Comment by Newbie-2** [comment]
Hallo Jens, man bist Du schnell. :-)
Nur zum Verständnis. Bedeutet das es wird ein neues  Mosquitto Addon geben, oder wird die neue Raspberry Matic an das alte Mosquitto V1.5.8+2 angepast ?

**Comment by jens-maus** [comment]
Es wird eine neue RaspberryMatic Version geben die dann wieder mit dem alten Mosquitto Addon funktioniert.
