### ISSUE TITLE
No reconnect after loss of connection at eth0 with RPi3b+

### ISSUE THREAD

**Issue by elbo78** [jens-maus/RaspberryMatic#1035]
**Describe the bug**
Eth0 hangs after disconnect on RPi3B+
**Steps to reproduce the behavior**
1. Disconnect LAN connection
2. Reconnect LAN
3. No access possible (Ping, WebGui, SSH)
4. After PowerOff Reset access possible

**Expected behavior**
Access shall be possible after reconnect

**Screenshots**
none

**System information:**
 - RaspberryMatic Version: 3.53.34.20201121
 - Used Hardware: Raspberry PI 3B+
 - Used HomeMatic RF-Module: RPI-RF-MOD

**Additional context**
Issue only occurs with Pi3B+. Pi3B works like expected. Possible root cause: different LAN Chip in 3B+.
Same Pi3B+ with RM 3.51.6.20200613 works also like expected.

[Thread in Homematic Forum](https://homematic-forum.de/forum/viewtopic.php?f=26&t=63807&start=10)

**Comment by jens-maus** [comment]
Please provide info on your current network setup. How did you configure the network settings in RaspberryMatic? Please provide your `/etc/config/netconfig` output here.

**Comment by Baxxy13** [comment]
Ich teste das gerade durch. 
Das gute Vorab... es betrifft nur den Pi3B+ und in der aktuellen Nightly existiert das Problem nicht mehr.

Viel zu sehen gab es nicht beim Pi3B+ mit RM 3.53.34.20201121

```
Dec 23 21:22:38 homematic-raspi daemon.info ifplugd(eth0)[615]: Link beat lost.
Dec 23 21:22:49 homematic-raspi daemon.info ifplugd(eth0)[615]: Executing '/etc/ifplugd/ifplugd.action eth0 down'.
Dec 23 21:22:49 homematic-raspi daemon.info ifplugd(eth0)[615]: Program executed successfully.
Dec 23 21:25:49 homematic-raspi user.warn monit[1049]: 'internetCheck' status failed (1) -- no output
Dec 23 21:26:07 homematic-raspi user.warn monit[1049]: 'internetCheck' status failed (1) -- no output
Dec 23 21:26:22 homematic-raspi daemon.info ifplugd(eth0)[615]: Link beat detected.
Dec 23 21:26:23 homematic-raspi daemon.info ifplugd(eth0)[615]: Executing '/etc/ifplugd/ifplugd.action eth0 up'.
Dec 23 21:26:23 homematic-raspi daemon.warn ifplugd(eth0)[615]: client: eth0: disabled, 
Dec 23 21:26:23 homematic-raspi daemon.info ifplugd(eth0)[615]: Program executed successfully.
Dec 23 21:26:23 homematic-raspi daemon.info ifplugd(eth0)[615]: Link beat lost.
Dec 23 21:26:25 homematic-raspi user.err monit[1049]: 'eth0' link down
Dec 23 21:26:25 homematic-raspi user.info monit[1049]: 'eth0' trying to restart
Dec 23 21:26:25 homematic-raspi user.warn monit[1049]: 'internetCheck' status failed (1) -- no output
Dec 23 21:26:27 homematic-raspi daemon.info ifplugd(eth0)[615]: Link beat detected.
Dec 23 21:26:43 homematic-raspi user.err monit[1049]: 'eth0LinkCheck' status failed (1) -- no output
Dec 23 21:26:43 homematic-raspi user.warn monit[1049]: 'internetCheck' status failed (1) -- no output
Dec 23 21:27:01 homematic-raspi user.warn monit[1049]: 'internetCheck' status failed (1) -- no output
```

**Comment by jens-maus** [comment]
> Ich teste das gerade durch.
> Das gute Vorab... es betrifft nur den Pi3B+ und in der aktuellen Nightly existiert das Problem nicht mehr.

Sehr gut, das vermutete ich bereits weil im aktuellsten Kernel der kommenden Version von der RaspberryPi Foundation wohl genau solche Probleme beseitigt wurden. Da gab es probleme mit der Erkennung eines Link Up/Down. Passt zu den hier dargelegten problemen. Insofern würde ich sagen kann man dieses Ticket gleich wieder zumachen und auf das kommende Release verweisen.

**Comment by elbo78** [comment]
Verbindung über Fritzbox 7590, Statische IP im DHCP Server der Fritzbox zugeordnet

root@homematic-ccu3:/usr/local/etc/config# cat netconfig
HOSTNAME=homematic-ccu3
MODE=DHCP
CURRENT_IP=192.168.1.30
CURRENT_NETMASK=255.255.255.0
CURRENT_GATEWAY=192.168.1.1
CURRENT_NAMESERVER1=192.168.1.1
CURRENT_NAMESERVER2=0.0.0.0
IP=192.168.1.30
NETMASK=255.255.255.0
GATEWAY=192.168.1.1
NAMESERVER1=192.168.1.1
NAMESERVER2=0.0.0.0
CRYPT=0

**Comment by jens-maus** [comment]
@elbo78 Danke, wenn du mutig bist kannst du gerne nach einem entsprechendem Backup mal die aktuellste Testversion (nightly snapshot) probieren und zurückmelden ob das Problem damit auch noch auftritt. @Baxxy13 scheint damit bereits kein problem mehr zu haben.

**Comment by elbo78** [comment]
@jens-maus Danke für die schnelle Reaktion. Wenn ich endlich mit GitHub klar komme, versuche ich es mal ;-)
Oder hast du vielleicht einen direkten Link zum Image? :-D

**Comment by jens-maus** [comment]
@elbo78 https://github.com/jens-maus/RaspberryMatic/releases/tag/snapshots

**Comment by Baxxy13** [comment]
Die Nightly's laufen bei mir sehr rund. Ich denke man kann die schon produktiv einsetzen. 
Der Sicherheit halber würde ich aber trotzdem eine neue SD nehmen und die momentan laufende erstmal gut wegpacken.

**Comment by elbo78** [comment]
Lauft mit RaspberryMatic-3.55.5.20201223-rpi3 wieder. Problem gelöst, Danke an @jens-maus und @Baxxy13
