### ISSUE TITLE
Firewall Konfiguration: Speichern nicht möglich, wenn leere Zeile am Ende

### ISSUE THREAD

**Issue by IT-VBFK** [jens-maus/RaspberryMatic#1036]
**Describe the bug**
Wenn unter "Einstellungen" -> "Systemsteuerung" -> "Firewall konfigurieren" im Feld für die IP-Adressen sich eine leere Zeile befindet, ist das Speichern unmöglich. 
Dies ist meiner Meinung nach unnötig frustrierend, weil man so ein Verhalten nicht erwartet...

**Steps to reproduce the behavior**
1. Einstellungen -> Systemsteuerung
2. Firewall konfigurieren
3. Leere Zeile zB ans Ende
4. Speichern ist nicht möglich

**Expected behavior**
Speichern ignoriert Zeilen, die "Zeile.Trim().Length == 0" sind

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: 3.53.34.20201121
 - Used Hardware: RPi3B+
 - Used HomeMatic RF-Module: Irrelevant

**Additional context**
Beim Beheben diese kleinen Bugs könnte man das auch gleich um eine Möglichkeit zum Kommentieren erweitern, zB mit vorangestelltem #

**Comment by jp112sdl** [comment]
Ich kann es nicht nachvollziehen, oder mache ich was (nach deiner Anleitung) falsch?

Hab einmal nur eine Leerzeile angehängt und einmal noch eine IP hinzugefügt inkl. Zeilenumbruch.

<img src="http://g.recordit.co/ZXYQhrWgaa.gif" width="400" />

**Comment by IT-VBFK** [comment]
Oh, sry.. hab vergessen zu erwähnen: das ist nur so, wenn sich hinter der letzten IP-Adresse ein ";" befindet.

Also ;\n => nicht gut :)

**Comment by jp112sdl** [comment]
>  Lustige Anekdote: bei den Ports kommt genau die selbe Lösung zum Einsatz

Nein, kommt sie nicht.

Ports:
`userPorts = this.m_portTextArea.getText().replace(/\s+/g, '').split(";"); `

IPs:
```   
    ips = this.m_ipTextArea.getText(),       
...
    ips = (ips.charAt(ips.length -1) == ";") ? ips.slice(0,-1) : ips;
    ips = ips.replace(/\s+/g, '').split(";");  
```               
, denn im Gegensatz zu den Ports erfolgt bei der IP noch eine Validierung mit 
```
...
        if (! isIPAddressValid(ip)) {
          isOk = false;
        }
...
```



Zurück zum Problem - das lässt sich lösen, indem man noch ein
`    ips = (ips.charAt(ips.length -1) == "\n") ? ips.slice(0,-1) : ips;                             `
vor dem
`    ips = (ips.charAt(ips.length -1) == ";") ? ips.slice(0,-1) : ips;                   `
macht.

P.S.: Für einen PR habe ich zurzeit keine Muße

**Comment by jens-maus** [comment]
> P.S.: Für einen PR habe ich zurzeit keine Muße

Schafft es ohnehin nicht mehr in den morgigen Release. Lass dir also Zeit und geniess besser die Ruhe mit der Familie :)

**Comment by IT-VBFK** [comment]
Ist ja auch nicht weiter schlimm.. Jetzt weiß ich ja woher der Fehler kommt und wie er sich (temporär) beheben lässt..
