### ISSUE TITLE
Keine Servicemeldung mehr bei nicht erreichen von Geräten

### ISSUE THREAD

**Issue by MartinEckes** [jens-maus/RaspberryMatic#1041]
**Describe the bug**
Ich habe von RaspberryMatic-3.53.30.20201024-tinkerboard auf RaspberryMatic-3.55.5.20201226-tinkerboard gestern aktualisiert. Ich hatte zufälligerweise ein Rauchmelder (HmIP-SWSD) zuvor angelernt den ich nicht in Betrieb genommen hatte. Diese wurde vor dem Update in den Servicemeldungen als Gerätekommunikation gestört angezeigt. Nach dem Update ist der Eintrag nicht mehr vorhanden.

Ich weiß nicht wie es zuvor war aber in der Geräte Überichtschtsliste ist auch keine Anzeige der Signalqualität mehr vorhanden. Es wird auch kein Unreach mehr angezeigt. Aktiviere ich das Gerät wird auch die Qualität wieder angezeigt.

**Steps to reproduce the behavior**
1. Rauchmelder (HmIP-SWSD) anlernen und dann nicht in Betrieb nehmen
2. Update auf 3.55.5.20201226

**Expected behavior**
Servicemeldung wenn Gerät nicht ereichbar ist.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/30924281/103290524-0f221980-49ea-11eb-9d74-b50d3a2a973a.png)

**System information:**
 - RaspberryMatic Version:  3.55.5.20201226
 - Used Hardware: Tinker Board S 
 - Used HomeMatic RF-Module: RPI-RF-MOD und HmIP-HAP

**Additional context**
Einfach bescheid geben was ich noch einreichen soll.

**Comment by jp112sdl** [comment]
> Diese wurde vor dem Update in den Servicemeldungen als Gerätekommunikation gestört angezeigt. Nach dem Update ist der Eintrag nicht mehr vorhanden.

Es dauert erst wieder bis zur Zeitüberschreitung, bis die Störung wieder nach einem CCU Neustart erscheint.

**Comment by jens-maus** [comment]
@MartinEckes Es ist genauso wie @jp112sdl es hier sagt. Das verhalten ist kein Bug und kein Problem. In Zukunft solche Dinge bitte im HomeMatic-Forum diskutieren und erst wenn sich daraus ein Bug herauskristallisiert hier bitte ein Ticket aufmachen.
