### ISSUE TITLE
Fehlerhafte Kanalnamen

### ISSUE THREAD

**Issue by go0sie** [jens-maus/RaspberryMatic#1042]
Wenn ich im WebUi mir einen Raum oder ein Gewerk aufrufe, werden die Kanalnamen Fehlerhaft angezeigt.
Statt zB. "Badezimmer, Fenster:1" steht der Gerätetyp vor den Kanalnamen das hieraus "HMIP-SWDOBadezimmer, Fenster:1
" wird. Das geschieht bei allein Geräten in den Ansichten Räume und Gewerke.

![2020-12-29](https://user-images.githubusercontent.com/76749457/103309001-2a098380-4a14-11eb-94d4-e46f614b2bf6.jpg)

Browser cache wiederholt gelöscht ohne Änderung.

 - RaspberryMatic Version: 3.55.5.20201226
 - Used Hardware: Raspberry Pi3b
 - Used HomeMatic RF-Module: ...

**Comment by jens-maus** [comment]
Das Problem ist bereits bekannt und geht auf einen upstream bug in der 3.55.5 version von eQ3 zurück. Für die nächste RaspberryMatic wurde hierfür bereits ein Patch entwickelt. Siehe https://github.com/jens-maus/RaspberryMatic/pull/1039
