### ISSUE TITLE
Kanalbezeichnung - Fehlendes Leer/Trennzeichen

### ISSUE THREAD

**Issue by DavidPasch** [jens-maus/RaspberryMatic#1044]
**Describe the bug**
Sowohl in der Geräte-Übersicht als auch Raum- und Gewerk Übersicht, fehlt in der Kanalbezeichnung zwischen der Typennummer und dem eigentlichen Namen ein Leer/Trennzeichen.

**Steps to reproduce the behavior**
1. Status & Bedienung > Geräte > ein Gerät auswählen > Rechts in der Haupttabelle erste Spalte.
2. Status & Bedienung > Gewerke > ein Gewerk auswählen > Rechts in der Haupttabelle erste Spalte.
3. ... 

**Expected behavior**
Ein Leer- bzw. Trennzeichen

**Screenshots**
[
![Bildschirmfoto 2020-12-30 um 13 56 59](https://user-images.githubusercontent.com/36208668/103352895-c16be680-4aa7-11eb-8ca2-324e4d33d717.png)
](url)

**System information:**
 - RaspberryMatic Version: 3.55.5.20201226
 - Used Hardware: RPI3
 - Used HomeMatic RF-Module: das alte

**Comment by jp112sdl** [comment]
Das ist ein Fehler in der CCU FW ab Werk. Und auch ein Duplicate zu #1042
Wird mit dem nächsten Release gefixt
