### ISSUE TITLE
Typenbezeichnung wird am Anfang des Gerätenamens angezeigt

### ISSUE THREAD

**Issue by Buddinski88** [jens-maus/RaspberryMatic#1046]
**Describe the bug**
Es werden jetzt immer die Typenbezeichnungen am Anfang des Namens angezeigt.

**Steps to reproduce the behavior**
1. Update auf Version `3.55.5.20201226` und Neustart des Systems.

**Expected behavior**

- Es sollten nur die definierten Gerätenamen angezeigt werden und nicht die Typenbezeichnungen am Anfang.
- In der XML-API steht noch der richtige Wert.  Bsp.:
```
<device name="BZ_DL" address="OEQ1147391" ise_id="1823" interface="BidCos-RF" device_type="HM-LC-Sw1-DR" ready_config="true">
<channel name="Badezimmer.Deckenlicht" type="26" address="OEQ1147391:1" ise_id="1856" direction="RECEIVER" parent_device="1823" index="1" group_partner="" aes_available="true" transmission_mode="DEFAULT" visible="true" ready_config="true" operate="true"/>
</device>
```

**Screenshots**

![image](https://user-images.githubusercontent.com/50332516/103397618-62ef4880-4b39-11eb-96be-5cd8f1d26c04.png)

**System information:**
 - RaspberryMatic Version: 3.55.5.20201226
 - Used Hardware: Raspberry Pi 3B
 - Used HomeMatic RF-Module: Funkmodul für Raspberry Pi HM-MOD-RPI-PCB

**Additional context**
...

**Comment by jens-maus** [comment]
Duplicate of #1042
