### ISSUE TITLE
node-raumserver as Add On

### ISSUE THREAD

**Issue by eXtreMUser** [jens-maus/RaspberryMatic#1047]
**Is your feature request related to a problem? Please describe.**
No. just want to run a small node.js program

**Describe the solution you'd like**
Like to have node-raumserver (https://github.com/ChriD/node-raumserver) as add on raspberrymatic to control my Raumfeld/Teufel Multiroom Soundsystem via the http// protocol

**Describe alternatives you've considered**
run the programm in the console works; but if session is closed, programme is closed; as systemctl/init.d are not part of raspberrymatic I cannnot autostart the program.

**Additional context**
Thank you

**Comment by jens-maus** [comment]
Sorry but RaspberryMatic does only provide the adequate Addon API for third party authors to implement their own ideas. It is not a project to collect or implement addons itself. So have a look at groups like @homematic-community which is a group of ccu addon developers or develop this addon yourself or in case of your wish you could suggest to the RedMatic authors to implement the respective node for RedMatic. But here is the wrong place for such suggestions, definitely!
