### ISSUE TITLE
Architecture mismatch für libNRJavaSerial

### ISSUE THREAD

**Issue by envas** [jens-maus/RaspberryMatic#1049]
**Describe the bug**
Der Befehl `/opt/java-azul/bin/java -jar /opt/HmIP/hmip-copro-update.jar -p /dev/ttyUSB0 -a -v`wirft ein error

```
java.lang.UnsatisfiedLinkError: /tmp/libNRJavaSerial_root_0/libNRJavaSerial.so: /tmp/libNRJavaSerial_root_0/libNRJavaSerial.so: wrong ELF class: ELFCLASS32 (Possible cause: architecture word width mismatch)
```
Java StackTrace mit Cause:

```
[ERROR] Load gnu.io.RXTXCommDriver failed.
java.lang.NoClassDefFoundError: Could not initialize class gnu.io.RXTXCommDriver
        at gnu.io.CommPortIdentifier.getPortIdentifiers(CommPortIdentifier.java:351)
        at gnu.io.CommPortIdentifier.getPortIdentifier(CommPortIdentifier.java:282)
        at de.eq3.cbcs.lib.nrjavaserialdevice.SerialCommDevice.open(SerialCommDevice.java:96)
        at de.eq3.cbcs.lib.hmiptrxcommadapter.HomeMaticIPTRXCommAdapter.open(HomeMaticIPTRXCommAdapter.java:894)
        at de.eq3.cbcs.lib.hmiptrxcommadapter.HomeMaticIPTRXCommAdapter.<init>(HomeMaticIPTRXCommAdapter.java:103)
        at de.eq3.cbcs.tools.copro.update.hmip.HmipCoproUpdater.main(HmipCoproUpdater.java:64)

```

**Steps to reproduce the behavior**
Obvious

**Expected behavior**
HmIP-RFUSB update oder mindestens ein fehlerfreier Ablauf.

**System information:**
 - RaspberryMatic Version:  3.55.5.20201226
 - Used Hardware: RaspberryPi 3B+
 - Used HomeMatic RF-Module:  HmIP-RFUSB

**Additional context**
Mit dem Stick kann ich keine Geräte anlernen, ich bin aber nicht sicher, ob es ein Zusammenhang gibt. Vielleicht als Info noch Inhalt von `/var/hm_mode`:

```
root@homematic-raspi:~# cat /var/hm_mode
HM_HMIP_ADDRESS='0xB2B966'
HM_HMIP_ADDRESS_ACTIVE='0xB2B966'
HM_HMIP_DEV='HMIP-RFUSB'
HM_HMIP_DEVNODE='/dev/ttyUSB0'
HM_HMIP_DEVTYPE='USB'
HM_HMIP_SERIAL='1BE99B38E1'
HM_HMIP_SGTIN='3014F711A000041BE99B38E1'
HM_HMIP_VERSION='2.8.6'
HM_HMRF_ADDRESS=''
HM_HMRF_ADDRESS_ACTIVE=''
HM_HMRF_DEV=''
HM_HMRF_DEVNODE=''
HM_HMRF_DEVTYPE=''
HM_HMRF_SERIAL=''
HM_HMRF_VERSION=''
HM_HOST='rpi3'
HM_LED_GREEN='/sys/class/leds/led0'
HM_LED_GREEN_MODE1='mmc0'
HM_LED_GREEN_MODE2='heartbeat'
HM_LED_RED='/sys/class/leds/led1'
HM_LED_RED_MODE1='timer'
HM_LED_RED_MODE2='mmc0'
HM_LED_YELLOW=''
HM_LED_YELLOW_MODE1='none'
HM_LED_YELLOW_MODE2='none'
HM_MODE='NORMAL'
HM_RTC=''
```

**Comment by jens-maus** [comment]
Es ist vollkommen normal das dieser manuelle Aufruf diesen Fehler wirft. Das liegt daran, das im `HMIPServer.jar` von eQ3 die 64bit aarch64 version dieser Library fehlt. Genau deshalb wird ja auch mit RaspberryMatic ein eigenes aarch64 Binary davon mit ausgeliefert und beim Start von `HMIPServer` angegeben.

Das ist also kein wirklicher Bug. Die Frage ist eher warum hier ein manueller Aufruf dieses Kommandos von nöten ist? RaspberryMatic updatet doch vollkommen eigenständig die Firmware eines HmIP-RFUSB wenn es davon eine neue version gibt. Ich sehe hier also keinerlei Zusammenhang und kann selbst perfekt HmIP Geräte mittels des HmIP-RFUSB anlernen.

**Comment by envas** [comment]
> Die Frage ist eher warum hier ein manueller Aufruf dieses Kommandos von nöten ist?

Ist natürlich nicht nötig, ich habe bloss gesucht, warum ich mit meinem Dongle keine Geräte anlernen kann. Der Befehl habe ich irgendwo im Forum gefunden, wo auch ein Problem von einem nicht-funktionierenden HmIP-RFUSB diskutiert wurde. 

Nachdem ich den Versuch mit dem CM3-Modul aufgegeben habe und der RF-USB nicht funktioniert, bin ich ziemlich skeptisch gegenüber dem gesamten Projekt.

**Comment by jens-maus** [comment]
Nun, dann nehm dich einfach die Standardkomponenten wie beschrieben: d.h. Ein RaspberryPi3 + RPI-RF-MOD Funkmodul und nicht diese HmIP-RFUSB Krücke wo man weiss das dieser nicht optimal ist. Und das CM3 zu nehmen ist ja auch nicht der Pi erster Wahl. Also erst einmal kleine Brötchen backen wenn man frisch anfängt ist doch eigentlich eine gute Herangehensweise, oder?

**Comment by envas** [comment]
Mache ich gerade, RPI-RF-MOD Kondensator gelötet, frisches Image eingespielt und los geht es. 

Warum ich CM3 und HmIP-RFUSB getestet habe? Als Berufsentwickler von embedded Systemen habe ich im Schubladen jede Menge vin industriellen Controllers, alle mit CM3 Modul. Ich wollte es einfach probieren. Resultat: auf 3 verschiedenen Geräten getestet, bei allen kommt die gleiche UBoot Fehlermeldung, bei 2 davon startet aber der Kernel trotzdem. Pigeon Controller ist anders - rebootet periodisch. Ich bin kein UBoot Experte, wir benutzen Barebox als Bootloader, ich nehme an das Problem ist, dass Pigeon ein ziemlich komplexer Controller ist, mit vielen GPIO In-/Outputs, CAN, RS-485, 1-wire etc, da klemmt sicher was bei der Hardware init. Und der RF-USB Stick - na ja, wenn man keine Diagnosemöglichkeiten hat, weiss man nicht, ob es ein Hardwarefehler ist ode ob es SW Problem ist. Jedenfalls die Software sieht für mich gut aus. 

Jetzt bin ich auf Raspberry 3B+ umgestiegen und probiere ich es mit der RPI-RF-MOD Karte.

**Comment by envas** [comment]
Just FYI: RPI-RF-MOD Karte funktioniert, obwohl mit allen wohl bekannten Problemen von einer Funktechnologie, die ich schon von EnOcean, Zwave und Zigbee kenne (5 Thremostats anlernen geht, der Fünfte muss man 4x probieren bis es geht, nach einem CCU Reboot von 12 Geräten ein verschwindet und um nach dem nächstem Reboot wieder aufzutauchen, etc.). Aber insgesamt OK, mache ich eher aus Neugier, für mich in meinem Heim zählt nur was über RS-485 verbunden ist :)

Heisst für mich entweder ist mein RF-USB defekt (neu gekauft!?) oder gibt es ein Bug in der Software. Dazu kann ich leider keine greifbare Daten liefern.
