### ISSUE TITLE
Raspimatic 3.53.30.20200919 speichert keine Aenderungen

### ISSUE THREAD

**Issue by sanktnelson** [jens-maus/RaspberryMatic#1050]
Meine Raspimatic speichert seit dem update auf 3.53.30.20200919 keine Aenderungen. Nach Neustart werden alle inzwischen angelernten Geraete vergessen und alle Programme und Variablen auf den letzten Stand vor dem update zurueckgesetzt. 
Jeder Reboot fuehrt zu einer "unclean shutdown" Alarmmeldung.
Ich konnte noch nicht auf die aktuelle version updaten, da ich nur remote-zugriff mit niedriger Bandbreite habe. Hardware ist ein Raspberry Pi 3 Model B Rev 1.2.

**Comment by jens-maus** [comment]
Das hört sich alles sehr stark nach einer defekten SD Karte an bzw nach einer SD Karte die kurz vor ihrem Ende ist. Ratschlag wäre hier eine frische, neue und high endurance karte zu verwenden. Ein generelles Problem kann das hier aber nicht sein, daher schließe ich dieses ticket hier nun und bitte bei weiteren Problemen bitte sich an das homematic forum zu wenden.
