### ISSUE TITLE
firmware update via direct download

### ISSUE THREAD

**Issue by sanktnelson** [jens-maus/RaspberryMatic#1051]
**Is your feature request related to a problem? Please describe.**
Updating raspimatic remotely is impractical since the update first has to be downloaded to the PC and then uploaded to the webUI, causing 500Mb of traffic at the PC for 250Mb on the raspimatic. Iff they are not on the same LAN this can be quite time-consuming, and if the PC has a mobile connection this may not succeed at all due to connection dropouts.

**Describe the solution you'd like**
a way for the raspimatic to download the new firmware directly by itself without going through the client PC, e.g. a field to paste a URL instead of uploading the image

**Describe alternatives you've considered**
getting a trained monkey to swap SD-cards...?

**Comment by IT-VBFK** [comment]
With version [3.55.5.20201226](https://github.com/jens-maus/RaspberryMatic/releases/tag/3.55.5.20201226) already included.

**Comment by sanktnelson** [comment]
Ah! Nice!
Pity that I can't update since I only have remote access at the moment :-/
