### ISSUE TITLE
ScriptRuntimeError unmittelbar nach Aufruf von RGB-Farbwähler-Steuerelemente

### ISSUE THREAD

**Issue by mbhomie007** [jens-maus/RaspberryMatic#1052]
https://homematic-forum.de/forum/viewtopic.php?p=631015#p631015

https://homematic-forum.de/forum/viewtopic.php?p=630978#p630978

https://homematic-forum.de/forum/viewtopic.php?p=631099#p631099

`Dec 29 15:58:42 Homematic-CCU local0.err ReGaHss: ERROR: ScriptRuntimeError: integer id = 1215; [ExecError():iseESPexec.cpp:12880]
Dec 29 15:59:50 Homematic-CCU local0.err ReGaHss: ERROR: ScriptRuntimeError: integer id = 1215; [ExecError():iseESPexec.cpp:12880]
Dec 29 15:59:56 Homematic-CCU local0.err ReGaHss: ERROR: ScriptRuntimeError: integer id = 1215; [ExecError():iseESPexec.cpp:12880]`

`Dec 30 22:00:56 Homematic-CCU local0.err ReGaHss: ERROR: ScriptRuntimeError:  {    object oRGB = cObj.DPByControl("RGBW_COLOR.RGBW");    integer rgbID = -1;   string rgbValue = "unknown";   string rgbDefaultValue = "rgb(255,255,255,255)";    if (oRGB) {     rgbID = oRGB.ID();     rgbValue = oRGB.Value();     rgbDefaultValue = oRGB.MetaData("DEFAULT").ToString();   }    WriteLine("<tr>");      WriteLine("<td>");       WriteLine("<table width='100%' _height='100%' cellspacing='4'>");         WriteLine("<tr>
);           WriteLine("<td>");             WriteLine("<table class='ControlBtnInfo' style='width: 250px;'>");               WriteLine("<tr>");                 WriteLine("<td style='text-align:left'>");                   WriteLine("<span>${lblColorValue}</span>");                 WriteLine("</td>");                 WriteLine("<td style='text-align:right'>");                   WriteLine("<input type='text' id='colorPicker"#chnId#"'></input>");                 WriteLine("</td>");               WriteLine("</
r>");             Wri
Dec 30 22:00:56 Homematic-CCU local0.err ReGaHss: ERROR: ScriptRuntimeError:  {    object oWhiteLevel = cObj.DPByControl("COLORTEMP.WHITE");    integer whiteLevelID = -1;   string whiteLevelValue = "-1";   real whiteLevelMin = 2700;   real whiteLevelMax = 6500;   real whiteLevelStep = 50;     if (oWhiteLevel) {     whiteLevelID = oWhiteLevel.ID();     whiteLevelValue = oWhiteLevel.Value();     whiteLevelMin   = oWhiteLevel.MetaData("MIN");     whiteLevelMax   = oWhiteLevel.MetaData("MAX");     ! Check if 
he parameter STEP exists whiteLevelStep   = oWhiteLevel.MetaData("STEP");    }    WriteLine("<tr>");    WriteLine("<td>");      WriteLine("<table class='ControlBtnInfo' style='width: 250px; margin-left: 5px;'>");         WriteLine("<tr>");           WriteLine("<td style='text-align:left'><span>${lblColorTemperatureBR}</span></td>");           WriteLine("<td class='CLASS02546' style='text-align:right'>");             WriteLine("<div class='PercBtn' style='height:35px; line-height:35px; width:100px; backgro
nd-color:#89989b; dis`

Das Thema wurde schon im Forum diskutiert und eine Lösung ist wohl auch schon in "Gedanken" vorhanden, müsste nur noch umgesetzt werden. 
Der ScriptRuntimeError wird unmittelbar nach dem Aufruf unter "Status und Bedienung" mit einem "Klick" auf einen RGB-Dimmer erzeugt. 

![Unbenannt](https://user-images.githubusercontent.com/64688879/103458463-d0050880-4d08-11eb-84db-1054f674b68b.jpg)

**Comment by jp112sdl** [comment]
Das Problem kommt _vermutlich_ von CUxD und ich hatte dazu mit Uwe am 30.12.2020 einen (sehr) kurzen Austausch.

Die Metadaten `DEFAULT`, `MIN` und `MAX` werden seiner Aussage nach von CUxD mit einem leeren String belegt.
Das führt meinen Recherchen nach wohl zu dem Skriptfehler.

Mein Vorschlag Uwe gegenüber war, die Werte wie folgt zu befüllen:
```
MIN = 2700
MAX = 6500
DEFAULT = "rgb(255,255,255,255)"
```

Bisher habe ich jedoch keine weitere (Rück)meldung von ihm erhalten.

**Comment by jens-maus** [comment]
@jp112sdl Kannst du nicht auch parallel dazu noch für RM einen PR fertig machen der einen Stringcheck einbaut ob der DEFAULT metadata wert der zurückgeliefert wird leer oder null ist und dann auf den default "rgb()" zurückgreift.

**Comment by mbhomie007** [comment]
Vielen Dank für die Fehlerbehebung. 😁

Mit dem Nightly Build habe ich es nochmal getestet. 
Die Error Meldungen weg, das Problem tritt nicht mehr auf!

**Comment by jp112sdl** [comment]
Klingt gut!

Ich stehe dennoch weiterhin mit Uwe in Kontakt, um die Ursache zu beheben (MetaData korrekt zu befüllen) und ich denke, wir sind da auf einem guten Weg.
