### ISSUE TITLE
Kommunikationsstörungen (Servicemeldungen) während "Bad-Block Check"

### ISSUE THREAD

**Issue by mbhomie007** [jens-maus/RaspberryMatic#1053]
https://homematic-forum.de/forum/viewtopic.php?f=65&t=64000

Bei mir treten nachts um 02:00 Uhr während des "Bad-Block Checks" immer wieder Kommunikationsstörungen (Servicemeldungen) auf.

Es sind Geräte die sonst unauffällig sind und keine Störungen verursachen. Mal sind es immer wieder die gleichen Geräte, mal aber auch unterschiedliche.

Aktuelle RaspberryMatic 3.55.5.20201226 auf Raspberry 3b+ mit RPI-RF-MOD Funkmodul.

`Dec 28 02:01:16 Homematic-CCU local0.warn ReGaHss: WARNING: XMLRPC 'setValue': rpcClient.isFault() failed (url: xmlrpc://127.0.0.1:32010, params: {"0005970XXXXXX:0","HEATING_COOLING",0}, result: [faultCode:-1,faultString:"Generic error (TIMEOUT)"]) [CallXmlrpcMethod():iseXmlRpc.cpp:2608]
Dec 28 02:01:16 Homematic-CCU local0.err ReGaHss: ERROR: XMLRPC 'setValue' call failed (interface: 1011, params: {"0005970XXXXXXX:0","HEATING_COOLING",0}) [CallSetValue():iseXmlRpc.cpp:1505]
Dec 28 02:01:16 Homematic-CCU local0.err ReGaHss: ERROR: rpc.CallSetValue failed; address = 000597XXXXXX:0 [WriteValue():iseDOMdpHSS.cpp:76]
Dec 28 02:01:21 Homematic-CCU local0.warn ReGaHss: WARNING: XMLRPC 'setValue': rpcClient.isFault() failed (url: xmlrpc://127.0.0.1:32010, params: {"0005970XXXXXXX:0","HEATING_COOLING",0}, result: [faultCode:-1,faultString:"Generic error (TIMEOUT)"]) [CallXmlrpcMethod():iseXmlRpc.cpp:2608]
Dec 28 02:01:21 Homematic-CCU local0.err ReGaHss: ERROR: XMLRPC 'setValue' call failed (interface: 1011, params: {"000597XXXXXXX:0","HEATING_COOLING",0}) [CallSetValue():iseXmlRpc.cpp:1505]
Dec 28 02:01:21 Homematic-CCU local0.err ReGaHss: ERROR: rpc.CallSetValue failed; address = 00059709XXXXXX:0 [WriteValue():iseDOMdpHSS.cpp:76]`

**Comment by jp112sdl** [comment]
> Bei mir

Aber auch nur dort... Deshalb weiß ich nicht, ob das ein Issue wert ist.
_Ich vermute mal, es ist eher ein Verzweiflungs-Ticket_

Probier zunächst mal ein anderes Netzteil

**Comment by jens-maus** [comment]
Auch könntest du einfach mal den BadBlocksCheck deaktivieren (`/etc/config/NoBadBlockCheck` anlegen) und schauen ob dieser wirklich ursächlich ist. Und selbst wenn, dann zeigt das nur das bei höherer CPU/Disk Aktivität wohl es zu stärkeren Störeinflüssen auf das Funkmodul kommt und daran kann RaspberryMatic als Betriebssystem auch nicht wirklich was dran ändern kann.

**Comment by mbhomie007** [comment]
> das bei höherer CPU/Disk Aktivität wohl es zu stärkeren Störeinflüssen auf das Funkmodul kommt

Wäre es möglich die CPU-Last nur während des Bad-Block Checks zu begrenzen (max), um somit solche Probleme vorzubeugen?

**Comment by jens-maus** [comment]
> Wäre es möglich die CPU-Last nur während des Bad-Block Checks zu begrenzen (max), um somit solche Probleme vorzubeugen?

Nein, und das wäre auch nur ein behandeln der Symptome. Bei anderer höherer CPU Last (z.B. durch Addons oder andere Prozesse mit hoher CPU Auslastung) wird es dann vmtl. nur erneut zu solchen Problemen kommen.

**Comment by mbhomie007** [comment]
Vielen Dank die Rückmeldung.

Ich habe die vergangenen Tage das Netzteil weit getrennt vom Raspberry eingesteckt. Bis jetzt keine weiteren Kommunikationsfehler während des Bad Block Checks. Mal abwarten...
