### ISSUE TITLE
Neue Systemvariable CCU_REBOOT

### ISSUE THREAD

**Issue by RoHa78** [jens-maus/RaspberryMatic#1057]
**Is your feature request related to a problem? Please describe.**
Da bei einem Reboot der CCU sämtliche Scripts gestartet werden, werden hier u.U. auch irgendwelche Aktionen ausgelöst, die in dieser Phase vielleicht nicht so gewünscht sind. Der Workaround sieht momentan so aus, das die nicht löschbare Systemvariable "Anwesenheit", die nach dem Reboot auf "true" gesetzt ist, dafür missbraucht wird und dann nach ca. einer Minute wieder auf "false" zurückgesetzt. Diese Variable wird dann in die entsprechenden Scripts als zusätzliche "Ausführbedingung" geknüpft.  

**Describe the solution you'd like**
Wäre es hier möglich, eine weitere System-Variable z.B. CCU_REBOOT o.ä. zu definieren (analog zu Anwesenheit), die nach dem Reboot einen definierten Logikwert hat und diese dann nach einer gewissen Zeitspanne automatisch auf den negierten Logikwert gesetzt wird?
(siehe https://smart-wohnen.org/homematic-ausfuehren-von-programmen-bei-einem-neustart-der-ccu-unterbinden/)
**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by jens-maus** [comment]
Duplicate of #223
