### ISSUE TITLE
Wrong Update message?

### ISSUE THREAD

**Issue by Schello805** [jens-maus/RaspberryMatic#106]
I installed Raspberrymatic know 3 times and the result don´t change. I can start den ready Installation on my PI. I receive the message of a new Version. I used the newest one (2.27.8.20170501), but it dosen´t work. Unfortunatly it seems to be an old one, or a bug. In den following picture, you can see, an availabe update for the newest Version.
![image](https://cloud.githubusercontent.com/assets/28543330/25821018/b629143e-3433-11e7-8608-8e9eae4ff44e.png)
Anyway, after i try to restore my backup of the ccu, den PI isnt available anymore. 3 times... It seems, I am doing something wrong. Could you please support me in this case?
If the versionbug is not the problem, maybe another thing?

**Comment by jens-maus** [comment]
Bitte den Browser Cache komplett löschen lassen. Dieses Problem tritt immer dann auf wenn man von der CCU2 zu RaspberryMatic wechselt und vergisst den Browser Cache zu löschen, denn die Information über eine neue Version cached der Browser und man muss daher den kompletten Browser Cache einmal löschen lassen und dann holt er sich die Information wieder frisch aus dem Internet.

**Comment by Schello805** [comment]
Halle Jens, Vielen Dank. Ich hatte nur die Cookies gelöscht, und nicht die restlichen Dateien. Nichts desto trotz, ist der Raspberry nach dem Restore nicht mehr erreichbar. Am PI hängt ein Monitor, der mir die IP anzeigt. Darunter ist aber nichts erreichbar. In der Annahme, dass das einspielen des Backups einige Minuten dauert, habe ich 15 Minuten gewartet, aber dennoch kann ich den PI nicht erreichen. Vermutlich sitzt das Problem mal wieder vorm Bildschirm. :-(
