### ISSUE TITLE
Kanäle werden seperat angezeigt

### ISSUE THREAD

**Issue by MathiasJZ** [jens-maus/RaspberryMatic#1067]
**Gerätekanäle werden in der Geräteliste seperat angezeigt.**
...

**Steps to reproduce the behavior**
1. ...
2. ...
3. ...
4. ...

**Expected behavior**
...

![Unbenannt](https://user-images.githubusercontent.com/20886303/103927213-47c4a000-511a-11eb-977d-88d79cb92958.JPG)

...

**System information:**
 - RaspberryMatic Version: 3.55.5.20210106
 - Used Hardware: Raspberry PI3 B+
 - Used HomeMatic RF-Module: RPI-RF-MOD

**Additional context**
...

**Comment by jens-maus** [comment]
Duplicate of #1042

**Comment by MathiasJZ** [comment]
Wenn das ein Duplikat von #1042 ist, warum habe ich es immer noch?
Das Issue wurde vor 8 Tagen geschlossen, ich benutze aber eine Testversion vom 06.01.2021.

**Comment by jens-maus** [comment]
Dann erkläre bitte gebauer statt nur ein Screenshot und einen satz in die ticketbeschreibung aufzunehmen. Was genau erwartest du anders zu sehen, wo genau siehst du hier einen Fehler? 

Mehr Details, bessere Kommunikation, schnellere/bessere Hilfe für die Entwickler..

**Comment by MathiasJZ** [comment]
früher war HR-Esszimmer:0 und die anderen Kanäle bei einander.
Man hat den Aktor nur einmal gesehen. Jetzt sieht man den Aktor zwei mal z.B.. HR_Esszimmer:0 und HR_Esszimmer:4.
Ist etwas irritierend, finde ich.

**Comment by jens-maus** [comment]
Also erst einmal sei gesagt, das du ja hier einen unstable snapshot verwendet der quasi WIP ist. Und das du jetzt den Kanal :0 zusätzlich siehst liegt einfach daran, das wir hier kürzlich (siehe #976) Verbesserungen umgesetzt haben die diese sogenannten MAINTENANCE Kanäle sichtbar bzw. überhaupt nutzbar machen. Wenn du diese also nicht mehr sichtbar haben willst musst du die jetzt explizit unter Einstellungen als nicht sichtbar markieren und dort eben den Haken rausmachen.

P.S: Und übrigens ist es nicht die feine englische Art das Issue Ticket einfach komplett unausgefüllt zu lassen (siehe alle ...). Bitte nicht einfach einen Einzeiler + Screenshot schnell reinstellen, sondern sich die Zeit nehmen detailliert zu beschreiben um was es geht und was man erwartet usw. Denn wie man hier gut sehen kann hat es erst nach dem 2. Anlauf bzw. Nachfragen geklappt herauszufinden was du erwartest und was ggf. nicht so ist wie du dir das vorstellst.

**Comment by MathiasJZ** [comment]
Was hätte ich sonst noch schreiben sollen?
Es ist doch alles im Screenshot verfügbar. Daß ich eine Testversion verwende ist mir durchaus bewusst. 
Aber gut, dann werde ich mal alles mit Aktor:0 abwählen.
Ich war mir sicher, es sei ein Bug. 
Gruß, 
Mathias

**Comment by Baxxy13** [comment]
Von welcher Stelle war der Screenshot?
Kanal:0 von HM Geräten sollte nun eigentlich nur bei aufgeklappter Struktur (+ vorm Gerät) bei _Startseite > Einstellungen > Geräte_
oder in der Kanalauswahl innerhalb der WebUI-Programme sichtbar sein.

**Comment by jens-maus** [comment]
> Was hätte ich sonst noch schreiben sollen?
> Es ist doch alles im Screenshot verfügbar. Daß ich eine Testversion verwende ist mir durchaus bewusst.

Na genau das was wir dann bei 2-3 maligem PingPong erst klären konnten. Wirklich @MathiasJZ, ist nicht böse gemeint. Aber halte dich an das prozedere. Die Templates gibt es nicht zum Spaß. Nur so ist geordnetes und schnelles Arbeiten möglich. Und je mehr du ausführlich gleich darlegst, desto einfach machst du es den Entwicklern probleme nicht nur zu reparieren, sondern auch überhaupt zu verstehen!

> Aber gut, dann werde ich mal alles mit Aktor:0 abwählen.
> Ich war mir sicher, es sei ein Bug.

Das können wir ja noch rausfinden, @Baxxy13 ist ja schon mit im Boot und sollte hier versuchen können dein angeblichen Problem zu reproduzieren.

**Comment by MathiasJZ** [comment]
Ich habe versucht, kanal:0 abzuwählen.
Das geht auch, aber der Kanal ist und bleibt sichtbar.
@Baxxy13 
Auch bei Dir bedanke ich mich für Deine Hilfe.
@jens-maus
Wenn es Dir hilft, kann ich gerne wieder die originale SD-Karte in den Raspberry schieben,
dann sehen wir ja, ob es bei der letzten Stable auch auftritt. 
Gruß,
Mathias

**Comment by Baxxy13** [comment]
@MathiasJZ Deine "Fehlerbeschreibung" ist echt unpräzise. 
Der Screenshot relativ nichtssagend weil man nicht sieht in welchem Bereich der WebUI dieser gemacht wurde.
Was meinst du mit 

> Geräteliste

?

Gut, gefunden... Ich würde sagen dein Screenshot stammt aus dem Popup "Kanalauswahl" das man z.B. innerhalb von Programmen (Geräteauswahl), sowie über _Einstellungen > Gewerke / Räume --> Kanal hinzufügen_ erreicht.

Hier war es aber schon immer so das alle Gerätekanäle untereinander aufgeführt wurden. 
![Kanalauswahl_alt](https://user-images.githubusercontent.com/54898249/104117854-d3118180-5324-11eb-9cb4-dc6e7e28d1ab.JPG)
(RM 3.53.30.20200916; leider ohne echte angelernte Geräte)
Das Kanal:0 von normalen HM-Geräten dort nun mit auftaucht (wie man sieht ging Kanal:0 von Gruppen schon immer) hängt mit den Änderungen aus #976 zusammen.

Ist das dein "Problem"?

**Comment by MathiasJZ** [comment]
Ich habe es nicht nur in der Kanalauswahl, sondern auch in den Geräteeinstellungen.
Dann habe ich in den Geräteeinstellungen den Heizregler:0 unsichtbar gemacht.
Das hat nur nichts gebracht. 
Aufgefallen ist es mir erst gestern, weil ich ein Programm ändern musste. 
Lebensnotwendig wäre eine Änderung jetzt nicht. Man gewöhnt sich irgendwann mal dran.

**Comment by jens-maus** [comment]
Na warum sollte der kanal :0 in den Geräteeinstellungen bitte verschwinden?!? Das sichtvar flag wirkt sich logischerweise ja nur auf "Status und Bedienung" aus. Warum sollte das anders sein?!?

**Comment by Baxxy13** [comment]
> sondern auch in den Geräteeinstellungen

Genau das war das Ziel von #976 . Damit man den Kanal:0 von HM-Geräten einem Raum / Gewerk zuweisen kann. Das er nun direkt nach Druck auf + vor dem Gerät zu sehen ist ist ein "Bonus" damit man nicht die nervige Baumstruktur öffnen muss.

Würdest du ihn an dieser Stelle "unsichtbar" machen können, wäre er weg und nur noch per Script / SDV wieder zurückzuholen.

Dran gewöhnen ist wohl die beste Option. ;-)

**Comment by jens-maus** [comment]
Ich denke nun ist ja alles klar und wir können dieses Ticket final zu machen.
