### ISSUE TITLE
HMIP-PS Taster (Kanal 1) kann nicht zu neuen Direkt-Verbindungen hinzugefügt werden

### ISSUE THREAD

**Issue by jonaswre** [jens-maus/RaspberryMatic#1068]
**Describe the bug**
HmIP-PS Kanal 1 kann nicht zu Programmen oder Direkt-Verbindungen hinzugefügt werden, wird aber in der internen Direkt-Verbindung verwendet. Profil Einstellungen können in der internen Verknüpfung erfolgreich bearbeitet werden. Bsp. es kann angepasst werden, das der Schalter das Gerät immer An schaltet.

Da dies für eine spezielle Hardware gilt, kann ich verstehen, dass es eventuell schwer nachzustellen ist. 

Wenn ich im Gerät "Protokolliert" einstelle, wird im Protokoll Kanal 1 nicht angezeigt. 

Im nachfolgenden ist das Protokoll nach einem nach einem Tastendruck gezeigt.

`CHANNEL-ID,CHANNEL,VALUE-ID,VALUE,UNIT,DATE TIME
00021BE99E3CF7:0,"HMIP-PS 00021BE99E3CF7:0",CONFIG_PENDING,0,,2021-01-08 12:10:45
00021BE99E3CF7:0,"HMIP-PS 00021BE99E3CF7:0",RSSI_DEVICE,214,,2021-01-08 12:10:45
00021BE99E3CF7:0,"HMIP-PS 00021BE99E3CF7:0",DUTY_CYCLE,0,,2021-01-08 12:10:45
00021BE99E3CF7:0,"HMIP-PS 00021BE99E3CF7:0",UNREACH,0,,2021-01-08 12:10:45
00021BE99E3CF7:2,"HMIP-PS 00021BE99E3CF7:2",SECTION_STATUS,0,,2021-01-08 12:10:45
00021BE99E3CF7:2,"HMIP-PS 00021BE99E3CF7:2",STATE,1,,2021-01-08 12:10:45
00021BE99E3CF7:2,"HMIP-PS 00021BE99E3CF7:2",SECTION,2,,2021-01-08 12:10:45
00021BE99E3CF7:2,"HMIP-PS 00021BE99E3CF7:2",PROCESS,0,,2021-01-08 12:10:45
00021BE99E3CF7:3,"HMIP-PS 00021BE99E3CF7:3",SECTION_STATUS,0,,2021-01-08 12:10:45
00021BE99E3CF7:3,"HMIP-PS 00021BE99E3CF7:3",STATE,1,,2021-01-08 12:10:45
00021BE99E3CF7:3,"HMIP-PS 00021BE99E3CF7:3",SECTION,2,,2021-01-08 12:10:45
00021BE99E3CF7:3,"HMIP-PS 00021BE99E3CF7:3",PROCESS,0,,2021-01-08 12:10:45
00021BE99E3CF7:4,"HMIP-PS 00021BE99E3CF7:4",SECTION_STATUS,0,,2021-01-08 12:10:45
00021BE99E3CF7:4,"HMIP-PS 00021BE99E3CF7:4",STATE,0,,2021-01-08 12:10:45
00021BE99E3CF7:4,"HMIP-PS 00021BE99E3CF7:4",SECTION,0,,2021-01-08 12:10:45
00021BE99E3CF7:4,"HMIP-PS 00021BE99E3CF7:4",PROCESS,0,,2021-01-08 12:10:45
00021BE99E3CF7:5,"HMIP-PS 00021BE99E3CF7:5",SECTION_STATUS,0,,2021-01-08 12:10:45
00021BE99E3CF7:5,"HMIP-PS 00021BE99E3CF7:5",STATE,0,,2021-01-08 12:10:45
00021BE99E3CF7:5,"HMIP-PS 00021BE99E3CF7:5",SECTION,0,,2021-01-08 12:10:45
00021BE99E3CF7:5,"HMIP-PS 00021BE99E3CF7:5",PROCESS,0,,2021-01-08 12:10:45`

**Steps to reproduce the behavior**
1. HMIP-PS Gerät anlernen
2. Direkt-Verbinungen öffnen 
3. Taster suchen

**Expected behavior**
Taster zu einer neuen Direktverbindung hinzufügen.

**Screenshots**
Profilbearbeitung:
![image](https://user-images.githubusercontent.com/3731681/104009538-85bdd480-51ab-11eb-8e2c-f6804c0d92ad.png)

Kanalauswahl in einer neuen Direkt-Verbindung
![image](https://user-images.githubusercontent.com/3731681/104009226-fadcda00-51aa-11eb-8ce5-55ae3d3a039b.png)

**System information:**
 - RaspberryMatic Version: 3.55.5.20201226
 - Used Hardware: CCU3
 - Used HomeMatic RF-Module: CCU3

**Comment by jp112sdl** [comment]
@Baxxy13 ist das das, worüber wir am Tel sprachen? 
Mit den separaten Tasterkanälen von den PS und PSM, die es nicht separat zur Auswahl gibt und auch nicht geben darf?

**Comment by Baxxy13** [comment]
Ja genau.
Es ist nicht vorgesehen die "Gerätetasten" von Schaltaktoren wie PS / PSM / PCBS(2) usw. mit anderen Geräten zu verknüpfen.
Hat man z.B. die "interne" Verknüpfung eines solchen Geräte trotz Warnung gelöscht besteht über die WebUI keine Möglichkeit diese wieder herzustellen. Da hilft nur ablernen (=Werksreset) und neu anlernen.

Aber: 
Der Homematic-Manager kann das. 
Die originalen DV's wiederherstellen habe ich mehrfach gemacht. Geht.

Ob jetzt eine DV von Taster-PS1 zu Kanal:X PS2 geht habe ich noch nie probiert. Sollte aber möglich sein.

**Comment by jonaswre** [comment]
Was bedeutet das ist nicht vorgesehen? Ist es in RaspberryMatic nicht vorhergesehen oder in der Firmware?

**Comment by Baxxy13** [comment]
In der Firmware allgemein ist das nicht vorgesehen. 
Hab es gerade getestet. Vorweg es geht nicht.
Es wird zwar eine DV angelegt...
![DV_Taster_PS_Kanal_PCBS2_DV](https://user-images.githubusercontent.com/54898249/104018846-cc66fb00-51ba-11eb-9503-56296c489250.JPG)
Diese funktioniert aber nicht und für meine HmIP-PSM kommt "Konfigurationsdaten stehen zur Übertragung an" was sich nicht beseitigen lässt.

Tut mir leid. Geht nicht.

**Comment by jonaswre** [comment]
Mir wären eigentlich die XML-RPC Events SHORT_PRESS und LONG_PRESS wichtiger als die Direkt Verbindung die bekomme ich aber auch nicht oder?

**Comment by Baxxy13** [comment]
Ich denke nicht. Der Tasterkanal scheint nicht wirklich seinen Status zu senden sondern nur intern zu arbeiten. Selbst mit "reportValueUsage 1" mittels Homematic-Manager kommt nix auf der Zentrale an. 
Daran könnte wohl höchstens eQ-3 was mittels FirmwareUpdate der Geräte ändern, wenn überhaupt.

**Comment by jonaswre** [comment]
reportValueUsage 1 hatte ich auch schon probiert. Hatte gehofft, dass es ein Problem in RaspberryMatic gibt das @jens-maus wie gewohnt in wenigen Minuten behebt. Wenn es aber an der Hardware liegt werde ich mal gucken ob ich bei eQ-3 was erreiche... Trotzdem vielen Dank

**Comment by Baxxy13** [comment]
Ich bin auch nur Anwender und stecke nicht so tief in der Materie. Was ich hier schreibe beruht auf meinen Tests / Erfahrungswerten. Es muss nicht alles 100%ig korrekt sein.

@jmaus steht da auf einem ganz anderem Level. 
Mal schauen ob es noch eine Information von ihm zum Thema gibt.
