### ISSUE TITLE
Upgrade to latest version fails for RaspberryPi2

### ISSUE THREAD

**Issue by kbabioch** [jens-maus/RaspberryMatic#1069]
**Describe the bug**
...

**Steps to reproduce the behavior**
1. I'm currently running `3.53.30.20200919` on a RPi2. The installation itself works fine as far as I can tell.
2. Trying to update to `3.55.5.20201226` fails:
3. If rebooting the RPi immediately before the update, the upload succeeds, I can accept the ToS and start the update. However, nothing seems to happen. When accessing the web interface, I will end up in the "recovery interface".
4. If not rebooting the RPi immediately before the update, the upload of the new image never completes.

**Expected behavior**
The upgrade should work fine and new version should be installed.

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: 3.53.30.20200919
 - Used Hardware: RPi2
 - Used HomeMatic RF-Module: 

**Additional context**
Obviously I could just re-flash the new version and import a backup. However there seems to be an issue in the upgrade process, so I would like to understand it and get it fixed :+1: 

I'm wondering what kind of information do you need in order to get a better understanding of the situation.

Here is some information:

```
root@hm:~# free -m
              total        used        free      shared  buff/cache   available
Mem:            968         154         635          11         178         801
Swap:             0           0           0

root@hm:~# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root               975.9M    473.3M    435.4M  52% /
devtmpfs                451.8M         0    451.8M   0% /dev
tmpfs                   484.3M         0    484.3M   0% /dev/shm
tmpfs                   484.3M     10.2M    474.1M   2% /tmp
tmpfs                   484.3M    108.0K    484.2M   0% /run
tmpfs                   484.3M      1.5M    482.8M   0% /var
tmpfs                   484.3M         0    484.3M   0% /media
/dev/mmcblk0p3            2.4G     76.0M      2.2G   3% /usr/local
/dev/mmcblk0p1          255.7M     47.3M    208.4M  18% /boot
/dev/sda1                29.1G    413.0M     28.7G   1% /media/usb1

root@hm:~# uptime
 14:51:27 up  1:45,  1 users,  load average: 0.20, 0.22, 0.32

root@hm:/etc# cat /etc/os-release 
NAME=Buildroot
VERSION=2.15.5-20151101-2539-gef0de0f6
ID=buildroot
VERSION_ID=2020.08
PRETTY_NAME="Buildroot 2020.08"
```

**Comment by dehsgr** [comment]
I can confirm this issue coming from 2020/11 release on RPi3 with HM-RF-MOD-PCB. I bypassed it by flashing a new SD card.

**Comment by kbabioch** [comment]
Probably same/similiar issues: https://homematic-forum.de/forum/viewtopic.php?f=65&t=64211&sid=e6d91350f9ad05aeb483b146dde3a3e6

**Comment by jens-maus** [comment]
@kbabioch
Sorry, but your issue description is not specific enough and it definitely does not match the issue discussed in the homematic-forum thread you linked. The issue discussed in the homematic forum is related to using a real eQ3 CCU3 device where RaspberryMatic had been simply installed via the WebUI. In this case the `/usr/local` partition is simply not large enough to hold the uploaded update data and thus runs out of disk space during update. This can be solved by performing a complete factory reset with RaspberryMatic because then RaspberryMatic resized the `/usr/local` partition to the maximum size of the SD card. And this is BTW already documented (see https://github.com/jens-maus/RaspberryMatic/wiki/Installation-CCU3).

Your case (you are using a rpi2) seems to be somewhat different here. To me it looks like you have enough space in `/usr/local` (but I would suggest to also use a larger SD card here (min. 8GB)). So it can also simply be a defective SD card which during reflashing shows disk errors (check `dmesg`), thus the system cannot be updated. So please, first try to use a fresh, new and >= 8GB large sd card and then report back if you can still reproduce the issue.

**Comment by kbabioch** [comment]
No interesting lines in `dmesg`, SD card seems to be okay (it is a 4 GB card for now).

So what exactly do you want me to try now? Install the new version to a new SD card? Install the old version to a new SD card and try to upgrade?

**Comment by Baxxy13** [comment]
Es scheint in der Tat ein Problem beim WebUI-Update (Pi2B) von RaspberryMatic-3.53.30.20200919-rpi3.zip auf RaspberryMatic-3.55.5.20201226-rpi2.zip zu geben. 
Nach dem erfolgreichem Upload über die WebUI und anschließendem Reboot landet man im Recovery.
Dort ein "Normal Reboot" startet das System mit der "alten" 3.53.30.20200919.

**Comment by jens-maus** [comment]
Ah, jetzt geht mir ein Licht auf! Natürlich muss man gerade bei Nutzung eines RaspberryPi2 die Hinweise des ChangeLog der 3.53.34.20201121 Version beachten die ja hier versucht wird zu überspringen:

https://github.com/jens-maus/RaspberryMatic/releases/tag/3.53.34.20201121#user-content-OS-Changes

Ganz oben steht eine "IMPORTANT NOTICE" die man bei einem RaspberryPi2 vor allem beachten muss.

Es ist ja so, das beginnend mit der 3.53.34.20201121 Version ein Architekturwechseln von einer reinen 32bit Platform hin zu einer 64bit Umgebung durchgeführt wurde. Hierdurch war es notwendig die Images der RaspberryPi2 und RaspberryPi3 zu trennen die vorher ja einheitlich immer die `*-rpi3.zip` Images genutzt hatten. Da aber der RaspberryPi2 ja keine 64bit CPU hat musste hier eben eine Trennung durchgeführt werden und nun muss man immer das `*-rpi2.zip` Image verwenden. Und so ist es eben so, das man einmal nun bei Umstieg von einer Version < 3.53.34.20201121 die SD karte nach erstellen eines Backups komplett neu flashen muss und danach das Backup wieder einspielen muss. Zukünftige versionen kann man dann ganz normal wieder updaten. Also bitte die oben verlinkten Hinweise noch einmal durchgehen und einmal die SD Karte neu flashen.

**Comment by Baxxy13** [comment]
> Ah, jetzt geht mir ein Licht auf!

Dann kann ich ja den Pi2B wieder in die Rümpelkiste schmeißen. ;-)

Ich hatte das mit der Umstellung zwar im Hinterkopf, aber man kann sich ja nicht alles merken.

**Comment by jens-maus** [comment]
So ging es mir ja selbst auch :) Ich hatte das auch ganz vergessen.

Und nur um nochmal klartext zu reden: RaspberryPi2 Nutzer müssen eben **einmalig** bei einem Upgrade auf die Version >= 3.53.34.20201121 das Update über ein komplettes neues flashen des Images (via Etcher) durchführen. Das WebUI update funktioniert dort (wie hier gesagt) nicht!
