### ISSUE TITLE
Asus Timkerboard S kein Einspielen des Backup möglich

### ISSUE THREAD

**Issue by UweGi** [jens-maus/RaspberryMatic#1072]
**Describe the bug**
Der ButtonDatei auswählen zum Aufspielen des Backups funktioniert nicht. Es erfolgt keine Auswahlmöglichkeit.

**Steps to reproduce the behavior**
1. ...
2. ...
3. ...
4. ...

**Expected behavior**
...

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: ...3.55.5.20201226
 - Used Hardware: ...ASUS Tinkerboard S
 - Used HomeMatic RF-Module: ... ext. Antennenbausatz 

**Additional context**
...

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!

**Comment by UweGi** [comment]
Hallo Jens
Danke für den Hinweis.
Dennoch möchte ich dir ein großes Kompliment für deine Arbeit auf diesem Wege aussprechen.

Gruß 
Uwe
