### ISSUE TITLE
Nightly RM-3.55.5.20210114 - erkennt Funkmodul nicht

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1077]
**Describe the bug**
Mit der Nightly RM-3.55.5.20210114 wird weder ein RPI-RF-MOD auf GPIO noch ein HM-MOD-RPI-PCB auf HB-RF-USB erkannt. 

**Steps to reproduce the behavior**
1. Nightly mit Funkmodul starten
2. Ausgabe auf dem Monitor betrachten. "no GPIO/USB connected RF-hardware found
3. oder in der WebUI auf "Geräte anlernen" gehen 

**Expected behavior**
Auch in der Nightly sollten alle Funkmodule sowie deren Anbindung erkannt werden.

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: RaspberryMatic-3.55.5.20210114-0a4711-rpi4.zip
 - Used Hardware: Pi4B-2GB
 - Used HomeMatic RF-Module: RPI-RF-MOD auf GPIO / HM-MOD-RPI-PCB auf HB-RF-USB

**Additional context**
...

**Comment by jens-maus** [comment]
Hast du irgendwelche Ausgabe, Debug Infos parat die du mir liefern kannst?

**Comment by Baxxy13** [comment]
Reicht das volle syslog vom Start?
Ansonsten müsstest du mir mal sagen was ich wo und wie loggen soll.

**Comment by jens-maus** [comment]
Ich schau mal selbst erst. Hab ne vermutung.

**Comment by Baxxy13** [comment]
Vielleicht hilft Dir das.
[Test_Kernel_log.txt](https://github.com/jens-maus/RaspberryMatic/files/5814792/Test_Kernel_log.txt)
[Test_Sys_log.txt](https://github.com/jens-maus/RaspberryMatic/files/5814795/Test_Sys_log.txt)
