### ISSUE TITLE
Nightly RM-3.55.5.20210115 - Fehlermeldung beim Start bezüglich chrony

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1078]
**Describe the bug**
Beim booten der oben angeführten Nightly ist eine Fehlermeldung bezüglich chrony zu sehen.
```
Starting chrony: Another chronyd may already be running (pid=562), check /var/run/chrony/chronyd.pid
FAIL
```
Schaut man nach dem booten ins syslog sieht man ähnliches.
```
Jan 15 13:41:59 Test-RM-Pi4B-USB-Boot daemon.info chronyd[562]: chronyd version 3.5.1 starting (+CMDMON +NTP +REFCLOCK +RTC -PRIVDROP -SCFILTER -SIGND +ASYNCDNS -SECHASH +IPV6 -DEBUG)
Jan 15 13:42:04 Test-RM-Pi4B-USB-Boot daemon.info chronyd[650]: chronyd version 3.5.1 starting (+CMDMON +NTP +REFCLOCK +RTC -PRIVDROP -SCFILTER -SIGND +ASYNCDNS -SECHASH +IPV6 -DEBUG)
Jan 15 13:42:04 Test-RM-Pi4B-USB-Boot daemon.crit chronyd[650]: Fatal error : Another chronyd may already be running (pid=562), check /var/run/chrony/chronyd.pid
Jan 15 13:43:07 Test-RM-Pi4B-USB-Boot daemon.info chronyd[562]: Selected source 194.36.144.87
```

**Steps to reproduce the behavior**
1. Nightly booten und Ausgabe am Monitor betrachten
2. nach dem booten im syslog nachsehen

**Expected behavior**
Es sollten keine Fehlermeldungen bezüglich chrony auftauchen

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: 3.55.5.20210115-67aab1-rpi4.zip
 - Used Hardware: Pi4B-2GB
 - Used HomeMatic RF-Module: RPI-RF-MOD auf GPIO

**Additional context**
...

**Comment by jens-maus** [comment]
Danke für den report. 👍 Sollte dann mit dem nächsten snapshot beseitigt sein. Bitte auch weiter so ausführlich testen, denn in den letzten tagen habe ich umfangreiche umstellungen an verschiedenen stellen vorgenommen die ggf. zu solchen problemen führen kann und es wäre gut die frühzeitig zu beseitigen bevor der nächste release ansteht.

**Comment by Baxxy13** [comment]
> Sollte dann mit dem nächsten snapshot beseitigt sein.

Rückmeldung. 
Das "Problem" besteht mit einer frisch geflashten RaspberryMatic-3.55.5.20210116-17bc77 weiterhin.
Gleiches Testequipment wie oben beschrieben.
