### ISSUE TITLE
Use full Linux system

### ISSUE THREAD

**Issue by NCC1701M** [jens-maus/RaspberryMatic#108]
Use full linux system like Ubuntu/Debian so people can install software and/or run other software on the RaspberryPi as well, like OpenHab.

**Comment by jens-maus** [comment]
Sorry, but this is not the mission of RaspberryMatic. If you want to have a CCU within an existing Ubuntu/Debian system you should better look at YAHM (https://github.com/leonsio/YAHM). Note, however, that you can still use OpenHab with RaspberryMatic. All you need is a developer (or yourself) creating a CCU Addon package that you can the install via the WebUI provided CCU Addon functionality.
