### ISSUE TITLE
Nightly RM-3.55.5.20210116 - kein Update über WebUI / Rcovery möglich

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1080]
**Describe the bug**
Das System (ausgehend von Nightly RM-3.55.5.20210115) lässt sich mit der heutigen Nightly weder über die WebUI noch über das Recoverysystem updaten

**Steps to reproduce the behavior**
1a. Update über die WebUI hochladen
1b. System landet mit Fehlermeldungen im Recovery 
2a. oder Update über das Recovery hochladen
2b. ausgaben im Browser beobachten

**Expected behavior**
Update sollte auf beiden Wegen fehlerfrei funktionieren

**Screenshots**
zu 1a/b:
![IMG_20210116_101340_1280x720](https://user-images.githubusercontent.com/54898249/104809520-28023b80-57ee-11eb-90bd-1a747c524dfd.jpg)

zu 2a/b:
```
[1/5] Processing uploaded data.............267624082 bytes received.
[2/5] Calculating SHA256 checksum: ERROR (sha256sum)

```
**System information:**
 - RaspberryMatic Version: Nightly 3.55.5.20210116-17bc77-rpi4.zip
 - Used Hardware: Pi4B-2GB (Boot über SD-Karte)
 - Used HomeMatic RF-Module: RPI-RF-MOD auf GPIO

**Additional context**
...

**Comment by jens-maus** [comment]
Danke für den Test. Bitte dann mit dem nächsten snapshot probieren. Sollte nun wieder gehen. Auch bitte weiter so ausführlich alle möglichen Firmware-Update methoden in der WebUI und im Recovery-System testen da hier wie gesagt einige Verbesserungen an den Verarbeitungsskripten vorgenommen wurden und es aber hier ggf. zu solchen regression probleme wie diesem hier kommen kann. Das muss alles nochmal sauber durchgetestet werden vor dem nächsten Release. Daher danke für diesen Bugreport!

**Comment by Baxxy13** [comment]
> mit dem nächsten snapshot probieren.

Gleicher Fehler mit der RaspberryMatic-3.55.5.20210117-07c40a. Kein Update via WebUI oder Recovery möglich.

**Comment by jens-maus** [comment]
Na wenn du versuchst kommend von der 3.55.5.202010116 auf die 3.55.5.20210117 zu wechseln ist es klar das das passiert. Die 3.55.5.202010116 ist ja kaputt und folglich auch das RecoverySystem der 3.55.5.202010116. Du musst also die 3.55.5.20210117 erst frisch auf die SD Karte wieder flashen weil du sonst mit der 3.55.5.202010116 gefangen bist.

**Comment by Baxxy13** [comment]
> weil du sonst mit der 3.55.5.202010116 gefangen bist.

Ok, ich teste mal eine andere Konstellation.

**Comment by MathiasJZ** [comment]
Da muß ich mich jetzt enklinken.
Ich hatte das Problem schon beim Wechsel von der 3.55.520210115 auf die3.55.5.20210116.
Gruß,
Mathias
