### ISSUE TITLE
Durchgangssensor

### ISSUE THREAD

**Issue by SvenZonZan** [jens-maus/RaspberryMatic#1082]
Es wäre schön wenn man den **Durchgangssensor** über die Zentrale zurücksetzen kann.
 Ohne das man den Deckel entfernen und wieder Rufsetzen muss.

**Comment by jens-maus** [comment]
Das sind dinge die in der Firmware des Gerätes erfolgen/geändert werden muss. Und die Gerätefirmware von HomeMatic Geräten ist ClosedSource und obliegt alleinig eQ3. Insofern gibt es hier im Rahmen des RaspberryMatic Projektes nichts zu verbessern/reparieren.
