### ISSUE TITLE
HMIP-PSM Eingabefeld im Webinterface fehlerhaft

### ISSUE THREAD

**Issue by dersimn** [jens-maus/RaspberryMatic#1084]
# 3.53.34.20201121

Hier können Float Werte für die unten markierten Felder eingestellt werden (das Gerät kann auch damit umgehen, das Beispiel unten sendet alle 10s einen Messwert, auch wenn dieser sich nicht geändert hat bzw. nur um 0.01 W geändert hat).

![Screenshot 2021-01-19 at 00 50 31](https://user-images.githubusercontent.com/3258452/104972137-2b194980-59f1-11eb-8c13-10c0d9af1b07.png)

# 3.55.5.20201226

Hier werden nach dem Übernehmen nur Integer Werte angezeigt. Das Gerät verhält sich außerdem so als wurde der Integer Wert auch fälschlicherweise gesetzt.

**Comment by jp112sdl** [comment]
siehe #1058

**Comment by jens-maus** [comment]
duplicate of #1058
