### ISSUE TITLE
Homematic IP devices from CCU2

### ISSUE THREAD

**Issue by penzler** [jens-maus/RaspberryMatic#109]
The Homematic IP devices are displayed in the WebUI after the import.
But not in pocket control HM.
The reason is that the HssType() script command does not provide a value for a Homematic IP device.
Something is probably still lazy at the import.

**Comment by jens-maus** [comment]
Sorry, but what should be the conclusion of this ticket? I really don't get it. If you have detailed information about HssType() returning incorrect data please explain in more detail. Apart from that I don't think that this is a specific bug/problem of RaspberryMatic.

**Comment by penzler** [comment]
Ich würde es lieber telefonisch besprechen.
Meine Telefonnummer ist auf meiner Website:
https://penzler.de/impressum.html

**Comment by jens-maus** [comment]
Tschuldigung, aber ich denke wir sollten erst einmal so klären was genau das Problem sein soll bevor wir hier ggf. telefonieren. Erst einmal ist es aber so das RaspberryMatic ja im Grunde nur die CCU2 Firmware auf den RaspberryPi bringt und daher eigentlich nichts anders sein sollte und das mit dem HssType() ja auch bei einer CCU2 auftreten sollte. Ich verstehe also nicht ganz warum das Ticket hier im RaspberryMatic GitHub geöffnet wurde.

**Comment by penzler** [comment]
Ok. In deutsch kommt es mir entgegen.
Ich habe meine CCU2 nach Anleitung in eine Neuinstallation von RaspberryMatic importiert.
Danach wurden alle Geräte, auch die Homematic IP Geräte, im WebUI angezeigt.
In pocket control HM fehlen die Homematic IP Geräte aber. Als Ursache habe ich herausgefunden, dass der Script-Befehl HssType (_string device.HssType() Liefert die Kurzbezeichnung des HomeMatic Gerätetyps_) bei den Homematic IP Geräten einen Leerstring liefert.
Danach habe ich eine die Neuinstallation mit Import zweimal wiederholt und hatte das gleiche Ergebnis.
Eine Neuinstallation ohne Import und mit den Anlernen von einem HmIP-WTH mit der App durch scannen des QR-Codes, hat funktioniert und hier zeigt sich das Problem mit dem HssType nicht.
Deshalb bin ich der Meinung, dass mit dem Import etwas nicht stimmt.

**Comment by jens-maus** [comment]
Das kann ich hier leider auf die schnelle nicht nachvollziehen. Hier liefert der folgende ReGa Skript das richtige Ergebnis:

```
object obj = dom.GetObject("Briefkasten-Klappe");
WriteLine(obj.HssType());
```

Ergebnis:
```
HMIP-SWDO
```

Allerdings bin ich mir nicht sicher ob ich dieses Gerät nicht nach dem Umstieg auf RaspberryMatic angelernt habe. Werde das ganze daher nochmal die nächsten Tage mit meiner alten CCU2 und einem zweiten RaspberryPi testen.

**Comment by penzler** [comment]
Genau so habe ich es hier auch getestet. mit der auf RaspberryMatic angelernten Gerät hat es funktioniert, aber mit keinem der von der CCU2 importierten 23 HmIP Geräten.
Danke für die Unterstützung.

**Comment by jens-maus** [comment]
Hab nun erneut mit der neuesten RaspberryMatic probiert ob es ein Problem bei der übernahem von HomeMaticIP Geräte von einer CCU2 zu RaspberryMatic gibt. Hier in meiner Testumgebung konnte ich keine Probleme feststellen und `HssType()` lieferte immer die richtige Information zurück. Ich kann das von dir beschriebene Verhalten daher leider nicht nachvollziehen. Für weitere Tests würde ich dein CCU2 Backup benötigen um zu schauen ob ich es damit auch reproduzieren kann. Bis auf weiteres schliesse ich aber dieses Ticket da auch niemand anders sich bisher gemeldet hat der ein ähnliches Problem hat.
