### ISSUE TITLE
Device firmware v1.8.4 for HmIP-MOIB cannot be uploaded to device

### ISSUE THREAD

**Issue by su-SH1** [jens-maus/RaspberryMatic#1093]
**Describe the bug**
Device firmware v1.8.4 for HmIP-MOIB cannot be uploaded to device.

See screenhots below:

![2021-01-23 21_16_59-Window](https://user-images.githubusercontent.com/77898933/105613067-671d2780-5dc0-11eb-9a4b-4eacf0c54c64.png)

![2021-01-23 21_09_16-Window](https://user-images.githubusercontent.com/77898933/105613066-66849100-5dc0-11eb-8dee-23cddc7a5b32.png)

![2021-01-23 21_07_45-Window](https://user-images.githubusercontent.com/77898933/105613068-67b5be00-5dc0-11eb-8262-12f0c7f32d6f.png)

**Steps to reproduce the behavior**
1. Downloaded and uploaded latest HmIP-MIOB Firmware, once Rasperrymatic has dirsplayed on welcome page, that there is a new update for this device available
2. After the upload, the newest firmware of the device isn't listed. 
3. I've double checked the content in /etc/config/firmware via SSH. Everything ist listed and uploaded to this DIR.

![2021-01-23 21_10_57-Window](https://user-images.githubusercontent.com/77898933/105613069-67b5be00-5dc0-11eb-900f-4cf14f7c391e.png)

**Expected behavior**
I can see only the current version 1.6.0 of the HmIP-MOIB device but not the expected one 1.8.4. 
The firmware upload to the device doesn't start as well.

**Screenshots**
see attached files

**System information:**
 - RaspberryMatic Version: latest release - 3.55.5.20201226
 - Used Hardware: Pi3b+
 - Used HomeMatic RF-Module: HM-MOD-RPI-PCB

**Additional context**

**Comment by jp112sdl** [comment]
Does a reboot of the RaspberryMatic solve the problem?

**Comment by su-SH1** [comment]
I've tried the following measures:

- Several reboots of "Zentrale"
- Safe Reboot of "Zentrale" without addons
- Re-install of latest Raspberrrymatic version
- Cleanup up /etc/config/firmware
- Re-config of affected MIOB device
- Factory-reset of affected MIOB device

**Comment by su-SH1** [comment]
Clean install of latest Raspberrymatic + backup restore didn't help
Revert back to version 3.53.34.20201121 didn't help as well

**Comment by jens-maus** [comment]
Sorry, but the whole firmware update handling is performed in the closed source part of the CCU firmware (HmIPServer) to which only eQ3 has access to. So please try this with the standard CCU3 firmware and if it also happens there, please report it to eQ3 as this is then clearly and issue in the CCU Firmware itself and not in RaspberryMatic only.

**Comment by su-SH1** [comment]
No worries. I will do so. Is there a newer Raspberrymatic beta version with an updates HmIP-Server module available, which I can test beforehand?

**Comment by jens-maus** [comment]
Sure, use one of the nightly snapshots. See releases section.

**Comment by su-SH1** [comment]
Sorry for asking, but were can I find the Nightly Images Files or RPi3 exactly?

**Comment by jp112sdl** [comment]
https://github.com/jens-maus/RaspberryMatic/releases/tag/snapshots

**Comment by su-SH1** [comment]
Sorry for asking once again Jens, but could you please verify the following: eQ3 released a new Falmot-C12 firmware 1.4.2.
The current version of Raspberrymatic identifies only the version Falmot 1.2.2. Could my issue also related to a wrong detection of firmware states? As you can see in one my screenshots, the uploaded version 1.8.4 for is not shown in the firmware table. Maybe that is the missing trigger, why the MIOB firmware cannot be pushed to the device. Many thanks.

**Comment by su-SH1** [comment]
Issue closed. Bug has been reported to HW manufacturer.
