### ISSUE TITLE
cache is not working in CI for docker

### ISSUE THREAD

**Issue by angelnu** [jens-maus/RaspberryMatic#1098]
**Describe the bug**
Caching the docker images is not working as seen at https://github.com/jens-maus/RaspberryMatic/actions/runs/508138473 If it fails the CI fails for the PR.

So we have two options
1. go back to the original idea of using docker save in CI second job-> build artifact -> docker load in CI third job
2. just run the test in the second job

I did not consider the above because docker save&load would only include the amd64 one and I intended to test with a matrix in parallel in all platforms. But since: a) testing for arm and arm64 does not work (qemu emulation not good enough for Java) b)test during CI should only be a quick test and not a full test (nightly independent check).

So my suggestion would be to go directly with option 2 but I let @jens-maus to decide. Please assign me the issue and I will work in a PR.

**Steps to reproduce the behavior**
1. ...
2. ...
3. ...
4. ...

**Expected behavior**
...

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: ...
 - Used Hardware: ...
 - Used HomeMatic RF-Module: ...

**Additional context**
...

**Comment by jens-maus** [comment]
go ahead!
