### ISSUE TITLE
RF-Gateway-Alarm	ausgelöst	RF-Gateway HM-CFG-USB (LEQxxxxx) not connected	 ausgelöst

### ISSUE THREAD

**Issue by kennerblick** [jens-maus/RaspberryMatic#1099]
Habe einen RaspberryMatic im Docker eingerichtet auf einem 64bit Ubuntu-Host (20.04). Am Host hängt ein 
lsusb:
Bus 003 Device 003: ID 1b1f:c00f eQ-3 Entwicklung GmbH HM-CFG-USB/HM-CFG-USB-2 [HomeMatic Configuration adapter]
Alle Voraussetzungen für den Rasperrymatic habe ich erfolgreich installiert.
Der Docker-Container wird per docker-compose gestartet:
version: '3'

networks:
  #network-zabbix:
  #  driver: bridge
  default:
    driver: bridge

services:

  ccu:
    image: ghcr.io/jens-maus/raspberrymatic:snapshot
    container_name: ccu
    hostname: homematic-raspi
    privileged: true
    #command: modprobe eq3_char_loop || true
    #command: echo eq3_char_loop>/etc/modules-load.d/eq3_char_loop.conf || true
    volumes:
      - /opt/docker/ccu:/usr/local
      - /opt/docker/ccu/log:/var/log
    tty: true
    ports:
      - "8085:80"
      - "6443:443"
      - "2001:2001"
      - "2010:2010"
      - "9292:9292"
      - "8181:8181"
    restart: unless-stopped
    stop_grace_period: 30s

Nach 1-6 Stunden erreict die CCU den USB-Stick und natürlich auch die HM-Geräte nicht mehr. Im Syslog finde ich keine Fehler die hiermit zu tun haben könnten,
Wo könnte ich noch suchen?
Besten Dank!

**Comment by jens-maus** [comment]
Als erstes muss natürlich gesagt werden das die Docker Unterstützung noch vollkommen experimentell ist. Wurde noch nicht offiziell releast und jeden tag gibt es dafür änderungen die beliebiges kaputt machen können. Und wenn du selbst nichts im syslog findest, was sollen wir/ich dann bitte mit diesen Infos anfangen? Auch scheint mir das hier kein wirkliches Bug Ticket/Issue zu sein, sondern lediglich ein Hilferuf nach Support und dafür ist ein Diskussionsforum das bessere Medium. Insofern bitte also im Diskussionsbereich (https://github.com/jens-maus/RaspberryMatic/discussions) diskutieren oder im HomeMatic Forum im passenden Beitrag zu der Entwicklung rund um die Docker Unterstützung unterbringen (https://homematic-forum.de/forum/viewtopic.php?f=65&t=64314).
