### ISSUE TITLE
Homematic-IP Geräte von CCU2 nicht in RaspberryMatic WebUI

### ISSUE THREAD

**Issue by homematic-giess** [jens-maus/RaspberryMatic#110]
Hallo nach erfolgreicher Installation und Einrichtung von RaspberryMatic auf meinem Raspberry Pi 3 habe ich leider feststellen müssen, das zwar alle HM-Devices und auch die HM-Wired Devices 1:1 in RaspberryMatic übernommen wurden. Aber leider fehlen alle HM-IP Devices. Ich habe daraufhin probiert diese neu anzulernen, aber auch das ist nicht möglich, da beim Klick auf "HM-IP-Gerät anlernen" der Anlernmodus offenbar nicht startet. Die gleiche Funktion für "HM-Gerät anlernen" funktioniert hingegen einwandfrei.
Es sei hier noch erwähnt, das ich RaspberyMatic ohne das Funkmodul im Raspby betreibe. Stattdessen nutze ich mein bereits vorhandenes HM-RF-LAN-Gateway für die Funkkommunikation.
Warum wurden die HM-IP Geräte nicht übernommen?
Hat das fehlende Funkmodul etwas damit zu tun?

**Comment by jens-maus** [comment]
Ein HM-RF-LAN Gateway unterstützt keine HMIP Geräte. Das ist beim betrieb mit einer CCU2 nicht anders. Dort wurden jedoch deine HMIP Geräte anscheinend von deiner CCU2 angesteuert/angefunkt. Insofern ist dieses Verhalten vollkommen normal. Du benötigst definitiv ein Funkmodul wenn du HmIP machen möchtest. Aber auch da kannst du dann nicht auf HM-RF-LAN Gateways setzen um z.B. die Reichweite für HmIP Geräte zu erweitern. Ein HM-RF-LAN Gateway kann keinerlei HmIP Geräte anfunken.

**Comment by homematic-giess** [comment]
Hallo Jens, besten Dank für die prompte Antwort, Jetzt wo Du das so deutlich erklärt hast, wird mir auch klar, warum ich die HM-IP Devices schon unter der CCU2 nicht dem  HM-RF-LAN-Gateway zuordnen konnte.
OK, wenn das so ist, würde es denn funktionieren, wenn ich z.B. 2-3 Raspby 3 verteilt im Haus, mit jeweils einer Raspberry Matic Instanz betreibe?
Kann man mehrere Raspberry Matic miteinander vernetzen?

**Comment by jens-maus** [comment]
Nein, auch ein RaspberryMatic im LAN GatewayModus kann keinerlei HmIP. Das ist eine Limitation des Gateway Protokolles das auch RaspberryMatic nicht eliminieren kann. Wenn du HmIP machst führt kein Weg daran vorbei eine bessere Antenne an das Funkmodul zu löten. Wenn du allerdings normales HmRF (BidCos-RF) nutzt kannst du natürlich mehrere RaspberryMatic miteinander vernetzen.

**Comment by homematic-giess** [comment]
Oh je, das hatte ich befürchtet. Sehr schade, als ich letztes Jahr auf HM umgestiegen bin, habe ich bewußt auf HM-IP gesetzt, da ich davon ausgegangen bin, das ich damit nach und nach das ganze entsprechnd weit ausbauen kann. Inzwischen habe ich leider lernen müssen, das dies wohl keine so gute Idee war. Dann werde ich es mal mit einer besseren Antenne versuchen, ich habe ja nun mal die HM-IP Devices angeschafft, die werde ich jetzt nicht wieder ersetzen. Vielen Dank nochmal für Deine Hilfe.
