### ISSUE TITLE
Raspberry 3 radio module does not work 

### ISSUE THREAD

**Issue by Nairolf85** [jens-maus/RaspberryMatic#1106]
**Describe the bug**
I followed the instructions "Installation Docker OCI" strictly:
https://github.com/jens-maus/RaspberryMatic/wiki/Installation-Docker-OCI#prerequisites-on-host-system
The container basically runs without any errors. I was also able to import a backup.
However, I cannot address or re-learn the actuators via the radio module. 

**Steps to reproduce the behavior**
1. Install Pi OS
2. Install Docker
3. Install pivccu-modules-dkms kernel modules 
wget -q -O - https://www.pivccu.de/piVCCU/public.key | sudo apt-key add -
sudo sh -c 'echo "deb https://www.pivccu.de/piVCCU stable main" >/etc/apt/sources.list.d/pivccu.list'
sudo apt update
sudo apt install build-essential bison flex libssl-dev
sudo apt install pivccu-modules-dkms
4. Install eq3_char_loop kernel module to automatic module load section: 
sudo sh -c 'echo eq3_char_loop >/etc/modules-load.d/eq3_char_loop.conf'
5.Start+Load all necessary kernel modules on host: 
sudo service pivccu-dkms start
sudo modprobe eq3_char_loop
6. Docker pull
7. Docker run

**Expected behavior**
The radio module will be recognized when the application is started 

**Screenshots**
Log:
Starting hs485d: no Hm-Wired hardware found
Starting multimacd: not required
Starting rfd: no BidCos-RF hardware found

![grafik](https://user-images.githubusercontent.com/78046748/106023277-f11e0680-60c6-11eb-9bd9-f1a01b6a7cdb.png)

**System information:**
 - RaspberryMatic Version: 3.55.10.20210126
 - Used Hardware: Raspberry Pi 3 Model B Rev 1.2
 - Used HomeMatic RF-Module: HM-MOD-RPI-PCB

**Additional context**
I have also written down the problem here:
https://homematic-forum.de/forum/viewtopic.php?f=65&t=64314&p=639660#p639432
The hardware has worked fine with the image in the past, so I can rule out a problem with the hardware. 

I would be very happy if you can fix the bug or implement the function. 
Thanks in advance!

**Comment by florie1706** [comment]
Same here, think it is not ready yet. @jens-maus if you need testers, I have rpi3s and rpi4s for testing. :)

**Comment by jens-maus** [comment]
Please see the updated documentation on the docker/OCI installation. Review especially point 5 on the installation of the necessary device-tree changes within PiOS.

**Comment by Nairolf85** [comment]
Thank you very much. It works fine and very quick!
I don't remember it that quickly.
I just had one problem with
'sudo modprobe eq3_char_loop'
I think a restart helped.

**Comment by Nairolf85** [comment]
Since the new snapshot from 05.02.2020 I have status "unhealthy".
Unfortunately, I don't know how to check this more closely:
bc8c79d5b9e7   ghcr.io/jens-maus/raspberrymatic:snapshot   "/sbin/init"   21 minutes ago   Up 16 minutes (unhealthy)                                                    ccu2

**Comment by jens-maus** [comment]
Log in via ssh an then enter

`monit report`

If this outputs a service as "down" this is the reason. And then check with `monit summary` or `monit status` which one is down and why.

**Comment by Nairolf85** [comment]
Unfortunately, I can't get into the container :-(
![grafik](https://user-images.githubusercontent.com/78046748/107132019-ebe96480-68db-11eb-84e5-63bff8d8ab6e.png)
Not even through the web application portainer.
![grafik](https://user-images.githubusercontent.com/78046748/107131995-b04e9a80-68db-11eb-958b-daf45d5f327f.png)

**Comment by jens-maus** [comment]
@Nairolf85 There is no `/bin/bash` in the container. Thus, use `/bin/sh` and you are in.

**Comment by Nairolf85** [comment]
So easy. Thank you:

/usr/local/etc/monit-redmatic.cfg:6: Program does not exist: '/etc/config/rc.d/redmatic'
/usr/local/etc/monit-redmatic.cfg:7: Program does not exist: '/etc/config/rc.d/redmatic'
/usr/local/etc/monit-redmatic.cfg:8: Program does not exist: '/etc/config/rc.d/redmatic'
/usr/local/etc/monit-redmatic.cfg:20: Program does not exist: '/usr/local/addons/redmatic/bin/monit-du'

okay, then I musst completely delete redmatic files. So it ist not a problem with docker. 
I tried redmatic for use apple home kit ...

**Comment by florie1706** [comment]
Sorry, maybe I am to stupid, but a **docker pull ghcr.io/jens-maus/raspberrymatic:latest** 

gives me a **Error response from daemon: name unknown** 

However I can ping ghcr.io from the rpi3.

Any suggestions?

**Comment by jens-maus** [comment]
We are still in the beta/development phase. So please use `:snapshot` rather than `:latest`

**Comment by florie1706** [comment]
That did the trick. Thanks. Is running after restore of my backup :)
