### ISSUE TITLE
OVA - CuxD installation not working

### ISSUE THREAD

**Issue by CSH1208** [jens-maus/RaspberryMatic#1112]
**Describe the bug**
In the OVA the installation of CuxD is not working properly with the latest build. 

**Steps to reproduce the behavior**
1. Import OVA (initial installation)
2. Run it 
3. try to install CuxD
4. no possibility to setup CuxD - redirect to "Raspberrymatic is noch nicht bereit" screen and login screen
5. installed version is not shown (see screenshot)
6. deinstallation of CuxD is also not possible
7. after Restart same behavior

**Expected behavior**
normal behavior of CuxD as on a CCU3, so that it can be configured

**Screenshots**
![image](https://user-images.githubusercontent.com/78371554/106513662-89572980-64d3-11eb-8e65-cf4bac1e4c8e.png)

**System information:**
 - RaspberryMatic Version: 3.55.5.20201226 (and 3.53.34.20201121)
 - Used Hardware: Synology DS920 8GB RAM 
 - Used HomeMatic RF-Module: actually without RF Modul

**Additional context**
I'm actually figuring out if I'm able to move my system from RPI4 to my Synology NAS. I'm preparing the transfer.

**Comment by jens-maus** [comment]
Please make sure to install the x86_64 version of CUxD after having switched to the OVA variant of RaspberryMatic!

**Comment by CSH1208** [comment]
it hardly works properly 👍🏻 
Thanks and sorry for bothering you
