### ISSUE TITLE
Auto reconnect HMIP RF USB on a Synology virtual machine

### ISSUE THREAD

**Issue by mike4president** [jens-maus/RaspberryMatic#1115]
Hi, I haven't found an issue regarding my question. I am sorry, if this question has been asked before. Whenever I restart my Synology NAS Raspberrymatic boots up like it should in Synology virtual machine manager. Unfortunately the HM RF USB isn't automatically reconnected and I have to do this manually after every reboot. Is there a way to to this automatically? It seem like the virtual machine starts too soon.

**Comment by jens-maus** [comment]
Sorry, but this is no support or discussion fora here. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. This was also already mentioned in the ticket template!
___
Tut mir leid, aber das hier ist kein Supportforum, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen.  Dies stand übrigens auch so im Ticket Template!
