### ISSUE TITLE
Optimierung für ArgonOne Gehäuse / ArgonFANHat Unterstützung

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1116]
**Is your feature request related to a problem? Please describe.**
Damit nach einem Stromausfall die RaspberryMatic im ArgonOne Gehäuse sofort wieder hochfährt (ohne auf die Power-Taste des Gehäuses drücken zu müssen) wird im Script (/opt/argononed/argononed.sh) der Befehl "/usr/sbin/i2cset -y 1 0x1a 0xfe" ausgeführt um das Gehäuse auf "always on" zu setzen. 
Bei meinem Gehäuse klappt das nicht, aber es hat einen internen "Switch" den ich auf "always on" gesetzt habe.
Das funktioniert auch wunderbar, aber dadurch läuft auch der Lüfter beim booten (mit unbekannter Drehzahl) an. 
Beim ersten Start des Scripts wird aber davon ausgegangen das der Lüfter aus ist und somit wird die Regelung erst aktiv wenn die erste Temperaturschwelle überschritten wird. Durch die super Kühlung des sich schon drehenden Lüfters kommt es aber quasi nie dazu. ;-) 

**Describe the solution you'd like**
Eine kleine Änderung im Script sorgt dafür das beim ersten Aufruf der Lüfter auf die, anhand der Temperaturschwellen definierte, korrekte Drehzahl gesetzt wird.

Hier der von mir "optimierte" Abschnitt aus /opt/argononed/argononed.sh
```sh
fancontrol()
{
  curspeed=-1
  dstspeed=0

  while true; do
    curtemp=$( (cat /sys/class/thermal/thermal_zone0/temp 2>/dev/null || echo 0) | awk '{printf "%.0f\n", $1/1000}' )
    if [[ ${curtemp} -ge 75 ]]; then
      dstspeed=50
    elif [[ ${curtemp} -ge 70 ]]; then
      dstspeed=10
    elif [[ ${curtemp} -ge 65 ]]; then
      dstspeed=3
    elif [[ ${curtemp} -ge 55 ]]; then
      dstspeed=1
    else
      dstspeed=0
    fi

    if [[ ${dstspeed} -ne ${curspeed} ]]; then
      /usr/sbin/i2cset -y 1 0x1a ${dstspeed}
      curspeed=${dstspeed}
    fi

    sleep 30
  done
}
```
**Additional context**
Das Gehäuse an sich kühlt den Pi4B schon ziemlich gut. Mit dem "Stresstest" 
`sha1sum /dev/zero | sha1sum /dev/zero | sha1sum /dev/zero | sha1sum /dev/zero`
habe ich noch die "Kühlleistung" der Lüfterstufen getestet und diese im Script angepasst sowie eine zusätzliche Stufe hinzugefügt.

Wäre schön wenn du das so "als Standard" mit übernehmen würdest.

**Comment by jens-maus** [comment]
Danke für den Verbesserungsvorschlag.  Wie du sehen kannst habe ich das ganze auch bereits mal übernommen. Das einzige was mir aufgefallen ist, ist das in deiner Variante nun der Fan ja niemals auf 100% gesetzt wird, sondern der höchste Wert max. 50% ist. Nun bin ich kein starker Nutzer des ArgoneOne/ArgoneFAN HAT, aber IMHO sollte man da schon etwas einbauen das bei sehr hohen Werten auch der Lüfter irgendwann dann mit maximaler Auslastung läuft (z.b. >= 80°C ?)

**Comment by Baxxy13** [comment]
Sehr gut. 
Naja, letztlich ist das nur ein Luftquirl der nach meinen Tests kaum Mehrleistung über den 50% bringt.
Aber ja, full Speed bei über 80°C macht natürlich trotzdem Sinn.

**Comment by jens-maus** [comment]
Ok, eingebaut. danke noch einmal!
