### ISSUE TITLE
HmIP BWTH mit Softwarestand 1.2.4 wird immer wieder aus den Geräten verloren und lässt sich nicht Konfigurieren

### ISSUE THREAD

**Issue by meistermolli** [jens-maus/RaspberryMatic#1117]
**Describe the bug**
Nach Update war das Thermostat nicht mehr vorhanden.
Ich habe es zurück gesetzt und neu angelernt.
Dann war es wieder vorhanden aber hatte keine Konfigurationsseite mehr auf den Geräteeinstellungen.
Ein Neustart hat dann das BWTH wieder gelösch und ich hatte Probleme mit der CCU.
Mit Addon HAP Homematic und das 

Habe das Thermostat wie folgt resetet und neu angelernt.
Dennoch gleiches Verhalten nach erneutem Anlernen.

Beitrag hier von Elkotek:
https://ch.elv.com/forum/nach-anlernen-an-ccu2-keine-konfigurationsaenderungen-am-geraet-moeglich-7669

1. Alle vorhanden Verknüpfungen (auch DV) incl. möglicher Systemvariablen löschen
2. Unter Einstellungen –-> Geräte –-> den Button Löschen betätigen – Auswahlfeld auswählen --> Gerät in den Werkzustand zurücksetzen auswählen ....bestätigen
3. Danach:..
*..WebUI- abmelden..nicht nur über Browser (X)
*..Browser cache leeren
*..CCU2/3 von der Betriebsspannung trennen
*..danach wieder unter Admin neu starten und den HmIP-BWTH neu anlernen

**System information:**
 - RaspberryMatic Version: 3.55.5.20201226
 - Used Hardware HomeMatic RF-Module: CCU3 elv Charly 

**Additional context**
Im Forum habe ich einen aktuellen Ähnlichen Fehler betreffend CCU2 Firmware gefunden
https://homematic-forum.de/forum/viewtopic.php?f=26&t=63917&p=630484&hilit=bwth+bug#p630484

**Firmware zurück gesetzt auf 3.53.34.20201121 und das BWTH funktioniert wieder normal.**

Gruß meistermolli

**Comment by jens-maus** [comment]
Sorry, but this is no support or discussion fora here. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. This was also already mentioned in the ticket template!
___
Tut mir leid, aber das hier ist kein Supportforum, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen.  Dies stand übrigens auch so im Ticket Template!

**Comment by meistermolli** [comment]
@jens-maus 
für mich ist das ein bug, wenn ein Gerät in version 3.53.34.20201121 funktioniert und in 3.55.5.20201226 nicht mehr!
Wenn man dann auf die alte Version zurück geht dann funktioniert es ja wieder.

Ich habe dir nur bsp. dazu geschrieben, dass es bei anderen auch so ist.

**Comment by jens-maus** [comment]
@meistermolli Auf Geräteintegrationen hat RaspberryMatic wenig bis keinerlei Einfluss. Sowas ist eQ3 (upstream) sache. Deshalb auch das flaggen als "upstream issue". Am besten einfach mit original CCU3 Firmware ausprobieren und wenn es da auch sich da auch exakt so verhält dann an eQ3 melden. Und wenn nicht (wenn du es mit der originalen CCU3 nicht reproduziert bekommst) dann eine komplett frische RaspberryMatic Zentrale mit der aktuellen version einrichten, und versuchen damit zu reproduzieren und wenn es dann mit einer CCU3 Firmware geht aber nicht mit einer RaspberryMatic dann kannst du dich hier gerne wieder melden. Und natürlich kannst du gerne Leidensgenossen im Forum finden die das selbe problem haben und die können dann entsprechend ihre Hand hier heben. Bis dahin ist es aber ein reines Nutzerproblem - auch weil ich einfach über keinlei HmIP-BWTH verfüge und es auch selbst nicht einfach schnell mal reproduzieren kann.

**Comment by meistermolli** [comment]
ok

**Comment by meistermolli** [comment]
@jens-maus scheint in 3.55.10.20210213 wieder zu funktionieren läuft seit heute nachmittag!

Hier wurde das Problem denke ich auch im Changelog erwähnt.

> `Einzelne Konfigurationsparameter einzelner Geräte konnten nicht verändert werden. Betroffen waren sowohl Homematic IP als auch Homematic Geräte. `


Merci
