### ISSUE TITLE
Kanal 0 - keine Gewerkzuordnung für nicht IP-Geräte seit Snapshot 3.55.10.20210206

### ISSUE THREAD

**Issue by mbhomie007** [jens-maus/RaspberryMatic#1118]
Ich habe die oben genannte Snapshot Testversion auf meinem Raspberry 3b+ installiert. 

Mir ist aufgefallen das der Kanal 0 bei nicht IP-Geräten keinem Gewerk zugeordnet werden kann, die Änderung ist nach einem Neustart der Zentrale weg. Unter Einstellungen - > Geräte nicht mehr zugewiesen. 

Unter Einstellungen - > Gewerke sind aber die Kanäle dem Gewerken richtig zugewiesen. 

Die Raumzuordnung wird hingegen korrekt gespeichert.

**Comment by jens-maus** [comment]
@jp112sdl Kannst du das hier vorgetragene reproduzieren bei dir? @Baxxy13, du vielleicht?

**Comment by jp112sdl** [comment]
Ich hab grad nur die Möglichkeit mit der `3.55.10.20210123` zu testen _(aktualisieren kann ich erst später)_ und da wird auch nach einem Reboot das Gewerk noch unter Einstellungen->Geräte beim Kanal 0 eines BidCos Geräts angezeigt.

Wobei sich zwischenzeitlich eigentlich nichts an der "Kanal 0"-Thematik geändert hatte?
Oder soll 3782253 solche Auswirkungen haben?

@mbhomie007 Ist in der Browserkonsole ein (Javascript-)Fehler erkennbar?

Vielleicht hat @Baxxy13 zwischenzeitlich Erkenntnisse mit dem aktuellen Snapshot.

**Comment by jp112sdl** [comment]
Konnte grad doch schnell mal auf `3.55.10.20210207` (RPi3b+) aktualisieren... Gewerk bleibt auch dort nach Reboot (bei mir) erhalten.

**Comment by Baxxy13** [comment]
Ich kann das mit 3.55.10.20210207 (Pi4B) auch nicht reproduzieren. 
Meine beiden HM-Testgeräte behalten ihr Gewerk (zugewiesen über _Einstellungen > Geräte_) auch nach dem Reboot bei.

**Comment by jens-maus** [comment]
Gut, dann reichen mir zwei Bestätigungen das es kein Problem gibt. Dann ist das sicher ein reines Nutzerproblem (nicht gespeichert oder ähnliches). @mbhomie007 Also bitte entsprechend in einem Diskussionsforum weiter dazu diskutieren um den eigenen Fehler dort herauszufinden.
