### ISSUE TITLE
Neustarts seit 3.55

### ISSUE THREAD

**Issue by Donni1966** [jens-maus/RaspberryMatic#1119]
**Describe the bug**
unmotivierter Crash, Shutdown, Neustart
der Effekt tritt mit der absolut identischen Hardware und Software Config erst seit der 3.55.x auf. Mit der 3.54 hatte ich diesen Effekt nicht

**Steps to reproduce the behavior**
Ich schreib hier mal hin was ich schon alles gemacht habe: 
- neue Speicherkarte mit neuer frischer Installation
- neue externe Speicherkarte
- alles "unnötige" deaktiviert
- 
**Expected behavior**
 dass sie keinen Neustart macht oder ich weiss warum ;-) 

**Screenshots**

Ich habe einen Fehler: 
![Bildschirmfoto 2021-02-08 um 08 54 10](https://user-images.githubusercontent.com/61660957/107191205-1f1b1900-69ec-11eb-8044-0742d2b5a7a1.png)
den zweiten den ich ab und auch noch habe die das der /bin/ReGaHss abgestürzt ist. Stand da auch in der Arlammeldungssektion

**System information:**
 - RaspberryMatic Version: 3.55.5
 - Used Hardware: Raspberry 4 mit 4 GB, 32 Gb Samsung SD, extern 8 GB SD, Curl Modul an Serial, HAP und RedMatic im Einsatz. Wie gesagt: absolut identisches Setup unter der 3.54
 - Used HomeMatic RF-Module auf der Platine gesteckt davon kenn ich keine Version. 
 - ich habe noch ne als CCU als Repeater laufen
 - generell helfe ich gerne, wenn es noch Infos braucht. 
 - meine Dutys sind unter 20%

**Additional context**
Eigentlich frage ich mir vor allem, wo ich den Fehler finde, WARUM er Neustartet. Ich habe das hmserver.log aber da steht meines Erachtens nix hilfreiches drin. Hatte das auch mit tail laufen lassen um es zu beobachten.

Mir fällt auf, dass nachts um 12:00 rum der Memory Bedarf steigt und das jeden Tag mehr. 
Also hab ich die Daten mal als Variable gespeichert und in einer INflux Datenbank mit Grafana visualisiert
![Bildschirmfoto 2021-02-08 um 09 09 24](https://user-images.githubusercontent.com/61660957/107192085-740b5f00-69ed-11eb-850b-f6cde8133698.png)
Da kann man schon die Neustarts sehen der letzten Tage. Auch dass die CPU nachts auch schon mal Ewas beschäftigt ist ( der Wert in der Grafik ist bei der CPU Last mal 10) 

Ich habe zwei Programm laufen, die sich nachts starten. Eines für die Haustür zu verschließen und ein IFTTTausführen um die Videoüberwachung zustatten und die Festtags, Arbeitstags Berechnung. Sonst nix. Ich hab auch so keine großartigen Skripte am Laufen, selbst wenn nur auf Anforderung. die Raspimatic hat dafür mehr zu tun und verbraucht 167 MB Speicher und ca 2% CPU Last. 

Also was kann ich an Logs einsehen um den Fehler auf die Schliche zu kommen.

**Comment by jens-maus** [comment]
Sorry, but this is no support or discussion fora here. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. This was also already mentioned in the ticket template!
___
Tut mir leid, aber das hier ist kein Supportforum, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen.  Dies stand übrigens auch so im Ticket Template!

**Comment by Donni1966** [comment]
aha ... ist halt ne Definition Frage. Ich finde das ist ein Fehler ... aber gut. Ich tue in Forum
