### ISSUE TITLE
CloudMatic connection problems

### ISSUE THREAD

**Issue by MgicEye66** [jens-maus/RaspberryMatic#112]
With the new image I could not connect anymore from outside with easy connect or alexia. I tried to remove the firewall settings, reboot, put in the needed ones, reboot without success. Removed the SD card with the new image and replaced it with the sd card of the former image - and worked without any modification of any rile..

**Comment by jens-maus** [comment]
Please try with the latest 2.27.8.20170620 version again. This should hopefully fix your problems.

**Comment by MgicEye66** [comment]
Hello, still the same issue with the new issue. Tested again.

**Comment by jens-maus** [comment]
Refering to your duplicate posting: You are stating that your "firewall issue" still exists. However, please be more specific. What exactly are you trying to do? I read something about "easy connect". So are you referring that you are using CloudMatic and your RaspberryMatic is loosing connection to CloudMatic from time to time?

**Comment by MgicEye66** [comment]
Hi Jens,
sorry for the duplicate posting. Thought that these are done and if issue pops up again I have to open a new one.. Lesson learned :). This issue is the following:
I try to connect through easy connect for using Alexa with Homematic on side and I try to connect through the vpn of easy-connect, former meine-homematic.de. Both connections are cut when I installed the newest image. On my former CCU2 you have to remove the IP entries in the settings, boot, insert settings, boot again and it worked again - that was also published on the easy connect web page.
For the image 2.27.8.20170501 everything works as expected. Both connections are stable and you can also connect through PocketControl, Easy App whatever.
Starting with the version after the one I mentioned the connection does not work anymore. Regardless if I remove the IP settings, boot, insert, boot again. Also with the current one it does not work at all. Removing the SD card with the current image and booting up the 501 image everything works fine from scratch. This can be replicated each time I change the SD cards.
Let me know if there is anything else I can provide.

**Comment by jens-maus** [comment]
There are current problems with RaspberryMatic+CloudMatic which the makers of CloudMatic are currently investigation. Please read+discuss here:

https://homematic-forum.de/forum/viewtopic.php?f=65&t=37661
https://homematic-forum.de/forum/viewtopic.php?f=65&t=37251
https://homematic-forum.de/forum/viewtopic.php?f=65&t=36221

**Comment by MgicEye66** [comment]
Hello Jens,
I read the articles and sorry I just wondering why this is working with 2.27.8.20170501 image and not with the current one. Everything is the same after the restore.. Just my thought maybe I'm missing something...

**Comment by jens-maus** [comment]
@MgicEye66 The only difference between the old final 20170501 version and the newer ones regarding CloudMatic is that the `cloudmaticcheck.sh` cronjob is not executed every minute anymore but was modified to be executed every 6 hours only like this is performed with a standard CCU2. Maybe this has some effect? You could try to change the cronjob (see `crontab -e` command) to be executed every minute again and test again.

**Comment by MgicEye66** [comment]
will do, good job Jens! Really like the RaspberryMatic as I have a large infrastructure and the CCU2 was totally overloaded with that task :) Hope my donation (just done) will help to keep this extraordinary project alive!

**Comment by jens-maus** [comment]
It should help, yes - thanks. :) But note that a regular donation would even be better since this would keep my motivation constant ;)

**Comment by MgicEye66** [comment]
Changed, reboot - working. It seems that helped!

**Comment by jens-maus** [comment]
What do you mean by "changed card"? I just changed the cloudmaticcheck.sh execution to be executed every minute again in commit d9fcfedf358f14c43a5d4af40a43a37d24f8e4ba. Perhaps that will help to keep the cloudmatic service connected all the time.

**Comment by MgicEye66** [comment]
sorry Jens, In changed the SD Card back to the old image. Yes, I changed it back to 1 Minute, reboot and was working for a couple of minutes then I could not log-in again. So I shut down, insert card with old image and since then it's working. So let me double check with your file and see if its working.
thanks for your help so far.

**Comment by MgicEye66** [comment]
Hello Jens,
had a typo. Changed, reboot and it seems to work now at least for the last 2 hours. Hope this is solved!

**Comment by MgicEye66** [comment]
Hello Jens,
still working, so it seems we found the issue. Thanks again!

**Comment by jens-maus** [comment]
@MgicEye66 Thanks for the report. However, during the last days I integrated a cloudmatic version update and I need someone to actually test it before I will release it with the next raspberrymatic update. So can you please replace your `/opt/mh` directory with the content of the attached file and reboot your RaspberryMatic? That would really help a lot!

[cloudmatic-2017020901.tar.gz](https://github.com/jens-maus/RaspberryMatic/files/1106388/cloudmatic-2017020901.tar.gz)

**Comment by MgicEye66** [comment]
Hi Jens, I'm not at home for the next week. Can I do this remote?

**Comment by jens-maus** [comment]
Well, if you have a connection from the internet to your ccu (not cloudmatic) then you can of course do it via remote ssh/scp executions. But of course you also risk to do a mistake and thus get your raspberrymatic unresponsive if you do something wrong.

**Comment by MgicEye66** [comment]
Hello Jens,
replaced the directory and reboot, works fine so far.
Hope this helps.

**Comment by jens-maus** [comment]
Thanks, so closing this issue as solved for the next upcoming raspberrymatic release.
