### ISSUE TITLE
Datei /www/api/methods/ccu/getversion.tcl (CCU.getversion) fehlt für JSON-API

### ISSUE THREAD

**Issue by PfisterDaniel** [jens-maus/RaspberryMatic#1123]
**Is your feature request related to a problem? Please describe.**
Ja, die Datei getversion.tlc fehlt. Doch sie ist in der JSON-RPC API deklariert.

**Describe the solution you'd like**
Lösungsvorschlag:
`/www/api/methods/ccu/getversion.tcl`
Content:
```javascript
##
# CCU.getversion
# Ermittelt, die aktuell laufende Version auf der CCU
#
# Parameter: <keine>
# 
##
# Rückgabewert: [string]

proc read_var { filename varname} {
    set fd [open $filename r]
    set var ""
    if { $fd >=0 } {
        while { [gets $fd buf] >=0 } {
          if [regexp "^ *$varname *= *(.*)$" $buf dummy var] break
        }
      close $fd
    }
    return $var
}

proc get_version { } {
    return [read_var /boot/VERSION VERSION]
}

jsonrpc_response [json_toString [get_version]]
```
Mein Source funktioniert sowohl bei RaspberryMatic wie auch auf der Originalen OCCU...
Ich denke es ist kein Aufwand diese Datei mit auf zu nehmen.

**Describe alternatives you've considered**
Aktuell muss ich die Datei nach jedem Release anlegen... 

Ja ich könnte dafür ein Addon schreiben, doch da es ja im System Dokumentiert ist siehe http://ccu/api/homematic.cgi sollte es vll doch in der Firmware gefixed werden.

**Comment by jens-maus** [comment]
Danke für den Hinweis. Habe die fehlende Datei soeben hinzugefügt. Sollte also mit der nächsten kommenden Version behoben sein.

**Comment by PfisterDaniel** [comment]
Krass was fürn schneller Support. Ich bin echt e begeistert von deiner Arbeit. Danke dafür

Gruß Pfister Daniel

Am 12.02.2021 um 19:09 schrieb Jens Maus <notifications@github.com>:

﻿

Danke für den Hinweis. Habe die fehlende Datei soeben hinzugefügt. Sollte also mit der nächsten kommenden Version behoben sein.
