### ISSUE TITLE
Teaching in several devices does not work 

### ISSUE THREAD

**Issue by Nairolf85** [jens-maus/RaspberryMatic#1124]
**Describe the bug**
Only one device can be taught at a time. Another device can only be added after restarting the container. 

**Steps to reproduce the behavior**
1. Teach in devices 
2.  enter serial number
3. Inbox
4. Finish and it works
5. Repeat Process ---> error

**Expected behavior**
More devices can be added 

**Screenshots**
...
![grafik](https://user-images.githubusercontent.com/78046748/107845402-5cf8b280-6ddb-11eb-96f7-05d246bdc76b.png)

**System information:**
    RaspberryMatic Version: 3.55.10.20210213
    Used Hardware: Raspberry Pi 3 Model B Rev 1.2
    Used HomeMatic RF-Module: HM-MOD-RPI-PCB

**Additional context**
Serial numbers are definitely correct.
I didn't notice the error before because I was working with a backup. However, the backup caused problems with the no longer available Redmagic (in this container).

**Comment by blackbasket** [comment]
Hi @Nairolf85 

Do you have the same issue with HmIP devices? I am seeing your behaviour with HM devices for years. Even on original eQ-3 FW. Maybe it is related to the hint, that the function is not working with all HM devices.

Regards,
Marcel

**Comment by Nairolf85** [comment]
Hello, thanks for your help. Unfortunately I don't have any HMIP devices. However, everything worked very well without Docker. Unfortunately, the workaround only worked twice. Now I can't train any devices at all.

**Comment by blackbasket** [comment]
Even with the auto learning function for HM devices it is not working?

**Comment by Nairolf85** [comment]
Unfortunately I do not know it. I didn't want to remove the actuators.
I have now installed Home Assistant and am waiting for the implementation of:
https://github.com/jens-maus/RaspberryMatic/issues/1087
Thanks for the help. I think we can close this bug for now. I would be happy to help with the home assistant again at a later date
