### ISSUE TITLE
Lost access to HM devices after the update to 3.55.10.20210213

### ISSUE THREAD

**Issue by angelnu** [jens-maus/RaspberryMatic#1131]
**Describe the bug**

After switching to the new 3.55.10.20210213 I lost all my Homematic devices. HMIP still work.

**Steps to reproduce the behavior**
1. upgrade to 3.55.10.20210213 using OCI means
2. after reboot Homematic devices are not shown. 
3. Teaching of Homematic devices works, Homematic IP devices work

**Expected behavior**
...

**Screenshots**

I see a lot of error logs from ReGaHss:

-0 local0.warn ReGaHss: WARNING: XMLRPC 'getValue': rpcClient.isFault() failed (url: xmlrpc_bin://127.0.0.1:32001, params: {"xxxxx:1","LEVEL"}, result: [faultCode:-2
-0 local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1007, params: {"xxx:1","LEVEL"}) [CallGetValue():iseXmlRpc.cpp:1435]  

**System information:**
 - RaspberryMatic Version: 3.55.10.20210213
 - Used Hardware: CCU on x86
 - Used HomeMatic RF-Module: HM-MOD-RPI-PCB/HB-RF-USB@usb-0000:00:14.0-6

**Additional context**

I restored an old backup but this did not help either.

**Comment by jens-maus** [comment]
Hmm, that's actually a hard one. Are the HomeMatic devices still visible in the WebUI or are they completely deleted there?

The error in your logs just state that communication with these devices is not possible. What about `rfd` process? Is it running? Also make sure multimacd and /dev/eq3loop is there.

**Comment by angelnu** [comment]
I am checking if this is https://github.com/jens-maus/RaspberryMatic/issues/903#issuecomment-762480343 back. Trying to remember where I added the mount option in Raspberrymatic ;-)

**Comment by angelnu** [comment]
It was indeed the inode problem @jens-maus - and after you run into it the CCU config is messed up and a restore from backup is needed.

Any place to documment this so others might find it (maybe my me in the future :-) )?

**Comment by jens-maus** [comment]
Feel free to add some "Known Limitations" section to the wiki documentation if you like and document it there.
