### ISSUE TITLE
channels 1 and 2 of HmIP-SMI and HmIP-SPI not shown in room and device overview

### ISSUE THREAD

**Issue by MarLos68** [jens-maus/RaspberryMatic#1137]
**Describe the bug**
since FW 3.55.5 from 26.12.2020 channels 1 and 2 from HmIP-SMI and HmIP-SPI are not shown in
room and device overview.

**Steps to reproduce the behavior**
1. ... 
2. ... 
3. ...
4. ...

**Expected behavior**
...

**Screenshots**
![github](https://user-images.githubusercontent.com/77498710/108318965-f8659b00-71c0-11eb-93a9-d940f195c832.PNG)

**System information:**
 - RaspberryMatic Version: 3.55.10.20210213
 - Used Hardware: Raspberry Pi4
 - Used HomeMatic RF-Module: ...

**Additional context**
...

**Comment by jens-maus** [comment]
This isn't a general problem/issue but must be related to your own installation only. See here:

<img width="1047" alt="Bildschirmfoto 2021-02-18 um 08 37 06" src="https://user-images.githubusercontent.com/5887769/108321503-8b540480-71c4-11eb-9530-a1c99194517a.png">

This is with 3.55.10.20210213. Please also check the browser console for any potential javascript errors. However, I still think that re-teaching the device might help to get the channels back.
