### ISSUE TITLE
unvollständige Datensicherung

### ISSUE THREAD

**Issue by KnutSchweinfurth** [jens-maus/RaspberryMatic#1145]
**Describe the bug**
Die Datensicherung speichert weder die Aktivierung des NEO-Servers, noch die einzelnen Tasks.
Mache ich ein Full-Backup, speichere diese auf Platte, bespeile neue SD-karte mit neuer RaspBerry-Matic Version,
dann sind diese Einstellungen beim Rückspielen des Backups nicht mehr da.
Leider weiß ich jetzt nicht, ob der Bug hier rein gehört oder in den GitHub des Backup-Programmes, weil ich nicht
weiß, was wodurch erledigt ist - falls Off-Topic, dann SORRY.

**Steps to reproduce the behavior**
1. Datensicherung (ich mache sie täglich nachts automatisiert per Script)
2. neue SD Karte bespielen mit RaspBerry-Matic Version
3. Datensicherung einlesen
4. ...

**Expected behavior**
Neo-Server hat den gleichen Zustand in der Datensicherung wie im System

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: war schon immer so.. ich musste es aber erstmal versuchen, nachzustellen
 - Used Hardware: ...
 - Used HomeMatic RF-Module: ...

**Additional context**
...

**Comment by jens-maus** [comment]
Von welchen Neo-Einstellungen redest du hier? Meines aktuellen Wissens nach wird lokal auf einer CCU Zentrale nichts gespeichert bzgl der eigentlichen Funktionalität von Mediola. Das einzige was ggf verloren geht weil nicht teil des Backups ist die Aktivierung des NeoServer Addons selbst. Hier sollte jedoch ein einzelner Klick reichen um den NEOserver wieder nach Backup zurückspielen zu reaktivieren. Wenn das das einzige ist, wäre dies aber wohl verschmerzbar.

**Comment by KnutSchweinfurth** [comment]
Sorry.. hatte ich nicht richtig beschrieben... die ganzen Tasks werden im NEO-Server gespeichert (also auf der CCU).

**Comment by jens-maus** [comment]
@KnutSchweinfurth Wo genau soll das bitte gespeichert werden? Das ist in der Tat eine neue Information für mich. Wenn, dann muss da ja irgendwas unter `/usr/local/addons/mediola/` gespeichert werden.

**Comment by KnutSchweinfurth** [comment]
@Jens Maus:
Ja - muss es irgendwo... ich suche noch...
Jedenfalls muss man seine Tasks auch explizit auf dem Server speichern.
Im Creator steht "Damit Tasks vom NEO Server ausgeführt werden, müssen diese vom Benutzer übertragen werden."
Ich habe mal einen zweiten Neo-Server auf einem anderen Gerät installiert, da sind dann andere Tasks gespeichert.
Also muss es irgendwo in der CCU stehen. Ich habe den gleichen Account genutzt - also ist auch nichts in der Mediola Cloud.
Habe jetzt mal einen neuen Task angelegt und übertragen, aber ich finde in der Tat keine aktualisierte Datei des Neo-Servers Automation Managers im CCU Verzeichnis /usr/local/addons/mediola/ oder den Unterordnern.
Ich frage mal bei Mediola im Forum nach.
Trotzdem erst einmal DANKE.

**Comment by jens-maus** [comment]
Es kann auch gut sein das die Tasks mit der CCU id in der Mediola Cloud verknüpft sind und daher nur auf der selben CCU sichtbar sind. Und da in der eQ3 CCU3 Firmware auch das backup keinerlei Mediola Dinge aufweist, gehe ich nun einfach davon aus das das jetzige verhalten so gewollt ist. Daher bitte entsprechend mit Mediola klären/erfragen und ggf. das Ticket hier wieder aufmachen wenn es hier doch ein Problem gibt (was ich aktuell bezweifle).
