### ISSUE TITLE
Ständige Meldungen: "under-voltage detected"

### ISSUE THREAD

**Issue by deeprain279** [jens-maus/RaspberryMatic#1146]
**Describe the bug**
Seit dem Update von Version 3.55.5.20201226 auf Version 3.55.10.20210213 erhalte ich alle 7 Minuten erhalte ich die Meldung "under-voltage detected" in RaspberryMatic in den Alarmmeldungen.
In der SysLog ausgabe erhalte erhalte ich folgender Meldungen:

```
monit[1138]: 'voltageCheck' status failed (0) -- no output
monit[1138]: 'voltageCheck' exec: '/bin/triggerAlarm.tcl under-voltage detected WatchDog-Alarm'
```
An der Stromversorgung, Image, Hardware etc. ist nichts angepasst oder verändert worden.
Stromversorgung konstant bei 4,9-5V.

**Steps to reproduce the behavior**
1. Update über Updatepfad mit lokaler Zwischenspeicherung eingespielt
2. Neustart der RaspberryMatic

**Expected behavior**
Keine Alarmmeldungen.

**Screenshots**
![Bildschirmfoto 2021-02-21 um 18 18 02](https://user-images.githubusercontent.com/63447514/108633120-d85d0280-7472-11eb-9f74-d4472f94108d.png)
![Bildschirmfoto 2021-02-21 um 18 18 20](https://user-images.githubusercontent.com/63447514/108633130-e448c480-7472-11eb-92a5-9cd6b9cb5c6f.png)

**System information:**
 - RaspberryMatic Version: 3.55.10.20210213
 - Used Hardware: Raspberry Pi 3B+
 - Used HomeMatic RF-Module: RPI-RF-MOD 

**Additional context**
Einbau der kompletten Umgebung im Verteilerschrank. Stromversorgung über RPI-RF-MOD Module, nicht über Raspberry Pi.

**Comment by ChristophStr** [comment]
Ich habe das gleiche Problem seit dem Update auf diese Version!

**Comment by jens-maus** [comment]
Die internen Routinen die für die Überwachung der "under-voltage" in RaspberryMatic existieren lesen lediglich Statusregister des RaspberryPi selbst aus. D.h. wenn eine solche "under-voltage" Meldung auftritt, dann gibt das nur das Statusregister wieder das der RaspberryPi völlig selbst verwaltet und auf das RaspberryMatic keinen Einfluss hat. Wenn mit dieser bzw. einer neuen Version jetzt solche "under-voltage" Meldungen vermehrt auftreten, dann kann das ausdruck dessen sein das gewisse Prozesse hier beim Hochfahren ggf. mehr Leistung vom verwendeten Netzteil abverlangen und es deshalb jetzt erst zu diesen Meldungen kommt.

Hier auch weitere Beiträge zu diesem Problem mit dem Hinweis, dass mit einem originalen RaspberryPi Netzteil das Problem wohl behoben wird:

https://homematic-forum.de/forum/viewtopic.php?f=65&t=65535&p=646586#p646586

**Comment by jp112sdl** [comment]
@jens-maus Käme auch die Möglichkeit in Betracht, dass sich mit einer neuen zugrunde liegende Kernel-Version / -Treiber, die Schwellwerte geändert haben so dass nun under-voltage früher ausgelöst wird?

**Comment by jens-maus** [comment]
@jp112sdl Nicht das ich wüsste. Meines Wissens findet die Erkennung einer "under-voltage" komplett in der RaspberryPi Firmware/Hardware statt und nicht im Linux Kernel oder einem etwaigen Treiber. Die von mir aber bereits vorgenommene Änderung (https://github.com/jens-maus/RaspberryMatic/commit/9252d142d67e8a0e438b01c3df782d253349fec0) sollte zumindest die Auswertung etwas abschwächen und etwas konservativer bei der Alarmierung sein - auch wenn ich weiterhin glaube das man dem Statusbit des RaspberryPi schon vertrauen kann.

**Comment by deeprain279** [comment]
Vielen Dank für die Antwort.
Keine Ahnung was mich geritten hat, aber ich habe mir damals 5V 0,88A Netzteile gekauft für die Hutschiene. Und das scheint das Problem zu sein. Ich habe nun testweise mal ein normales Netzteil dran mit 5V 2,5A und damit funktioniert alles prima seit gestern abend. Ich werde meine Netzteile ersetzen gegen 5V 2,4A Hutschienennetzteile.

**Comment by jens-maus** [comment]
@deeprain279 Noch besser wäre 5,1V mit 3A

**Comment by briearn** [comment]
Ich hatte genau das gleiche Problem. Seit der Version 2.55.5.20201226 ging hm_pdetect nicht mehr vernünftig. Es lieferte nur noch "AWAY". Es gab keine Konfigurationsänderungen außer dem Update der Raspimaticversion. Mit dem Update vom 13.Feb auf 3.55.10.20210213 kamen dann zusätzlich noch die undervoltage detection Fehler. Da ich das auf einem 15W Hutschienenteil habe, war ich etwas verblüfft und habe mit Abgreifklemmen auf dem GPIO gemessen. Resultat: Das Netzteil bringt 5,08V und auf dem GPIO geht es runter auf 4,65V. Klar das der Raspi da meckert. Ich bin dann per ssh da rauf und habe mal geschaut was er denn so macht. Die meisten Schleifen waren in der Tat von hm_pdetect und die load war meistens um die 0.9ish. 
Als nächsten Step habe ich hm_pdetedt vollkommen gelöscht und neu gestartet. Das Resultat war besser, aber nicht wirklich gut. Es kamen immernoch ein, zweimal die Stunde undervoltage detection messages. 
Das nächste, was ich getan habe, war den kompletten Raspi auf die Novemberversion zurückzusetzen. Zu meiner großen Überraschung hat auch das keine Veränderung gebracht. Messungen am GPIO vom Raspi mit Abgreifklemmen ergaben 5.05V welches ab und zu mal unter 4.85V fällt. Naja, so dachte ich, wenn auch das nichts bringt dann kann man ja wieder auf die Version 3.55.10.20210213 hochziehen. Gesagt getan. Und was soll ich sagen: Das Problem ist weg. Kein Voltage drop mehr. Spannung ist bei >5.03V. Also hm_pdetect wieder drauf und versucht das nochmal hervorzurufen. Aber nichts da, es läuft seit dem ohne ein einziges under-voltage Ereignis. Auch auf dem Ozzi, welches mit dem Abgreifklemmen am GPIO misst, gibt es keinen einzigen Zeitpunkt mit U<5.03V mehr. Leider geht hm_pdetect immer noch nicht wieder, aber das ist eine andere Geschichte.
@Jens: Wenn Du irgend etwas genauer wissen möchtest ping mich an.

**Comment by marabu02** [comment]
Seit dem Update von Version 3.55.5.20201226 auf Version 3.55.10.20210213 erhalte ich innerhalb weniger Minuten die Meldung "under-voltage detected" in RaspberryMatic in den Alarmmeldungen. Netzteil liefert 3,4A bei 4,9-5,2V. Nach Zurücksetzen auf Version 3.55.5.20201226 ist alles wieder in Ordnung..... :-)

**Comment by MulderXP** [comment]
Hallo zusammen, ich habe ELV Charly mit dem Original ELV-Netzteil und habe mit dieser Version auch Undervolting-Meldungen ohne Ende. Ich gehe auch zurück auf die Dezember-Version und warte, ob es hier Updates gibt bis ich das nächste Mal update :-)

**Comment by derdoerk** [comment]
Hallo zusammen. 
Ich habe das Problem mit der watchdog "under-voltage detected" seit dem update auf die Version "3.55.10.20210213". 

Ich verwende eine CCU3 mit dem mitgelieferten Standard Netzteil. Im log habe ich folgende Einträge gefunden (siehe unten). 

Kann es sein, dass er die Überprüfung nicht korrekt durchführt, da ja im Log immer steht "no output"

Gruß

Mar  1 17:13:45 homematic-raspi user.info monit[1086]: 'voltageCheck' exec: '/bin/triggerAlarm.tcl under-voltage detected WatchDog-Alarm'
Mar  1 17:14:04 homematic-raspi user.err monit[1086]: 'voltageCheck' status failed (0) -- no output
Mar  1 17:14:23 homematic-raspi user.err monit[1086]: 'voltageCheck' status failed (0) -- no output
Mar  1 17:14:43 homematic-raspi user.err monit[1086]: 'voltageCheck' status failed (0) -- no output
Mar  1 17:15:02 homematic-raspi user.err monit[1086]: 'voltageCheck' status failed (0) -- no output
Mar  1 17:15:21 homematic-raspi user.err monit[1086]: 'voltageCheck' status failed (0) -- no output
Mar  1 17:15:40 homematic-raspi user.err monit[1086]: 'voltageCheck' status failed (0) -- no output
Mar  1 17:15:59 homematic-raspi user.err monit[1086]: 'voltageCheck' status failed (0) -- no output
Mar  1 17:16:18 homematic-raspi user.err monit[1086]: 'voltageCheck' status failed (0) -- no output
Mar  1 17:16:38 homematic-raspi user.err monit[1086]: 'voltageCheck' status failed (0) -- no output
Mar  1 17:16:57 homematic-raspi user.err monit[1086]: 'voltageCheck' status failed (0) -- no output
Mar  1 17:17:16 homematic-raspi user.err monit[1086]: 'voltageCheck' status failed (0) -- no output
Mar  1 17:17:35 homematic-raspi user.err monit[1086]: 'voltageCheck' status failed (0) -- no output
Mar  1 17:17:54 homematic-raspi user.err monit[1086]: 'voltageCheck' status failed (0) -- no output
Mar  1 17:18:13 homematic-raspi user.err monit[1086]: 'voltageCheck' status failed (0) -- no output
Mar  1 17:18:33 homematic-raspi user.err monit[1086]: 'voltageCheck' status failed (0) -- no output
Mar  1 17:18:52 homematic-raspi user.err monit[1086]: 'voltageCheck' status failed (0) -- no output
Mar  1 17:19:11 homematic-raspi user.err monit[1086]: 'voltageCheck' status failed (0) -- no output
Mar  1 17:19:30 homematic-raspi user.err monit[1086]: 'voltageCheck' status failed (0) -- no output
Mar  1 17:19:49 homematic-raspi user.err monit[1086]: 'voltageCheck' status failed (0) -- no output
Mar  1 17:20:08 homematic-raspi user.err monit[1086]: 'voltageCheck' status failed (0) -- no output
Mar  1 17:20:28 homematic-raspi user.err monit[1086]: 'voltageCheck' status failed (0) -- no output
Mar  1 17:20:47 homematic-raspi user.err monit[1086]: 'voltageCheck' status failed (0) -- no output
Mar  1 17:21:06 homematic-raspi user.err monit[1086]: 'voltageCheck' status failed (0) -- no output
Mar  1 17:21:25 homematic-raspi user.err monit[1086]: 'voltageCheck' status failed (0) -- no output
Mar  1 17:21:25 homematic-raspi user.info monit[1086]: 'voltageCheck' exec: '/bin/triggerAlarm.tcl under-voltage detected WatchDog-Alarm'

**Comment by joscha82** [comment]
> @jp112sdl Nicht das ich wüsste. Meines Wissens findet die Erkennung einer "under-voltage" komplett in der RaspberryPi Firmware/Hardware statt und nicht im Linux Kernel oder einem etwaigen Treiber. Die von mir aber bereits vorgenommene Änderung ([9252d14](https://github.com/jens-maus/RaspberryMatic/commit/9252d142d67e8a0e438b01c3df782d253349fec0)) sollte zumindest die Auswertung etwas abschwächen und etwas konservativer bei der Alarmierung sein - auch wenn ich weiterhin glaube das man dem Statusbit des RaspberryPi schon vertrauen kann.

war ebenfalls betroffen.  ([9252d14](https://github.com/jens-maus/RaspberryMatic/commit/9252d142d67e8a0e438b01c3df782d253349fec0))  scheint das Problem bei mir zu lösen. 
Laut systemlog ist  bei mir 2x nach dem boot ein undervoltage aufgetreten:
[   58.926674] eq3loop: eq3loop_open_slave() mmd_hmip
[   58.926931] eq3loop: eq3loop_close_slave() mmd_hmip
[   58.938775] eq3loop: eq3loop_open_slave() mmd_hmip
[234223.730341] Under-voltage detected! (0x00050005)
[234227.764402] Voltage normalised (0x00000000)
[1456164.218370] Under-voltage detected! (0x00050005)
[1456168.250356] Voltage normalised (0x00000000)


Die Prüfung gegen Bit 19 (0x10000) prüfte allerdings wohl ob in der Vergangenheit einmal ein undervoltage aufgetreten ist. Die Prüfung gegen Bit 1 (0x1) prüft nur noch ob aktuell ein Undervoltage vorliegt. -> Ohne die Änderung wird auch ohne ein undervoltage alle 5 minuten ein undervoltage alarm getriggert wenn seit boot einmal ein undervoltage vorlag.

**Comment by vupls** [comment]
Bei mir genau die gleich Situation wie von deeprain279 beschrieben. Nach dem Update von Version 3.55.5.20201226 auf Version 3.55.10.20210213 kommen alle 7 Minuten undervoltage Fehler. Nach Durchmessen gibt es bei meinem Netzteil (8A auf Hutschiene) keinen Abfall der Spannung. Kann es sein, dass hier regelmäßig auf das Reboot-Ereignis reagiert wird. 
Bin dann am Abend wieder zurück auf die Vorgänger-Version (3.55.5.20201226). Hier ist der Fehler wieder weg.

**Comment by jens-maus** [comment]
> Kann es sein, dass hier regelmäßig auf das Reboot-Ereignis reagiert wird.

Das habe ich bereits hier beantwortet: https://github.com/jens-maus/RaspberryMatic/issues/1146#issuecomment-783633956  Mit der nächsten kommenden Version sollte sich das ganze also etwas entspannen weil dann nur auf aktuelle und nicht mehr auf vergangene under-voltage Events reagiert werden sollte.

**Comment by vupls** [comment]
:thumbsup:
