### ISSUE TITLE
"unendliche" Firmwareübertragung bei vielen Geräten desselben Typs

### ISSUE THREAD

**Issue by MattN82** [jens-maus/RaspberryMatic#1149]
**Describe the bug**
Ich hoffe ich bin hier richtig damit. Mein Problem ist: Ich habe durchaus viele HMIP-PSM Schalt-Mess-Steckdosen im Einsatz....24 an der Zahl. Vor 1 oder 2 Raspberrymaticversionen erschien zum ersten Mal (seit ich die Dinger habe und auf 2.6.2 geupdated habe) die Meldung "Firmwareupdate verfügbar" (2.18.14).

Ich habe die 2.18.14 auf meine RPM geladen und seither (seit, wie gesagt, 1 oder 2 RPM Versionen) steht unter "Geräte-Firmware Übersicht" hinter den PSMs "Updatedatei wird zum Gerät übertragen". Und es tut sich....nichts.
Am Anfang ist der Dutycycle hoch (um 60-70%)....aber je mehr Tage vergehen, desto eher pendelt es sich bei 30% ein. Fast als ob er aufhört die Daten zu übertragen.

Das Dumme ist jetzt: Mit jedem Neustart....jedem Update....kurz: Mit jeder Unterbrechung scheint er von vorne anzufangen.

Meine Vermutung: Das System ist mit der Anzahl total überfordert und friert ein. Da diese PSMs aber Teil eines Systems sind, das in Echtzeit den Stromfluss überwacht, kann ich schlecht alle einzeln anklemmen und warten bis das Update durch ist.

Wäre es nicht möglich das System dahingehend zu verändern, dass man einzelne Geräte eines Typs fürs Firmware-Update "markiert", damit sie nacheinander abgefrühstückt werden können?

Ich wäre natürlich auch für jede andere Lösung offen :-)

**Steps to reproduce the behavior**
1. Große Anzahl an PSMs anlernen
2. Updatedatei laden
3. Wochenlang (keine Übertreibung) warten und feststellen, dass nichts passiert
4. ...

**Expected behavior**
Ich denke es sollten die PSMs der Reihe nach für das update anwählbar sein.
Ein Statusbalken, der den Fortschritt der Übertragung anzeigt wäre wahrscheinlich auch nicht verkehrt.
Denn man sieht ja so garnichts. Es könnte bei 10% der Übertragung eingefroren sein und keiner würde es merken.

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: 3.55.10.20210213
 - Used Hardware: Synology DS918+, Virtual Machine Manager, 
 - Used HomeMatic RF-Module: CCU3 Funkmodul von Smartkram.de via USB

**Additional context**
...

**Comment by jens-maus** [comment]
Es tut mir leid, aber das Gerätefirmwaremanagement und die Auslieferung der Gerätefirmwares findet exklusiv im closed-source teil statt auf das die Entwicklung rund um RapberryMatic keinerlei Einfluss hat. Auch gibt es zu dieser problematik bereits etlige Beiträge im homematic forum und das hier ist kein Diskussionsforum, sondern ein Bug/Issue-Tracker. Und da die genannte Problematik exklusiv im closed-source teil der CCU liegt können wir daran auch nichts ändern.
