### ISSUE TITLE
Integrate SNMP support

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#115]
To monitor the health and status of RaspberryMatic it would be great to have SNMP support in RaspberryMatic so that monitoring system could query the status/health of the system remotely.

**Comment by FraatRamski** [comment]
great idea. I'm monitoring my Infrastructure with PRTG (https://www.de.paessler.com/)
Can you tell me the OID, SNMP port 161?, the Read Comunity, ...

**Comment by jens-maus** [comment]
No special OID and the standard SNMP port with public community credentials.
