### ISSUE TITLE
'replaceAll() not defined' in slightly aged browsers

### ISSUE THREAD

**Issue by Joerg-rw** [jens-maus/RaspberryMatic#1150]
**Describe the bug**
Beim Anlegen einer neuen Systemvariablen in
```
>>>  Startseite > Einstellungen > Systemvariablen > "Neu"    
```
wird ausschliesslich bei Auswahl "Typ=Zeichenkette" keine Aktion auf "OK" ausgefuehrt und damit auch die Systemvariable nicht angelegt.

**Steps to reproduce the behavior**
1. neue Systemvariable anlegen: Startseite > Einstellungen > Systemvariablen > "Neu" 
2. beliebigen Namen und Typ=Zeichenkette auswaehlen
3. "OK" button klicken

**Expected behavior**
Systemvariable wird angelegt, requester schliesst

**Screenshots**
![lvELn7S](https://user-images.githubusercontent.com/5887769/109011907-ba311580-76b1-11eb-9182-8821f88bb53d.png)

**System information:**
 - RaspberryMatic Version: 3.55.10.20210213
 - Used Hardware: CCU3
 - Used HomeMatic RF-Module: CCU3

**Additional context**
RPimatic "neuling", CCU3->diese firmware fand vor wenigen tagen statt. Ich kann weder ausschliessen dass bei der migration etwas schief lief, noch dass im verwendeten browser ein bug sein koennte

**Comment by jp112sdl** [comment]
> noch dass im verwendeten browser ein bug sein koennte

Hast du denn nicht zunächst erst einmal einen anderen Browser ausprobiert, um das ausschließen zu können?

`replaceAll` wird von `/www/webui/js/extern/codemirror/addon/search/search.js` bereitgestellt.

Warum die Funktion bei dir nicht läuft, ist rätselhaft.
Würde mich auch nicht wundern, wenn da mal wieder irgendein Internet Security / Antivieren Supertool etwas blockiert.

**Comment by Joerg-rw** [comment]
bisher getestet in (wird aktualisiert):

Firefox

Konqueror

selbes ergebnis in beiden

**Comment by jp112sdl** [comment]
Hmm, dann bin ich auch ratlos.

**Comment by jens-maus** [comment]
Tut mir leid, auch ich kann das nicht reproduzieren. @Joerg-rw Bitte selbst in einer frischen Installation probieren, wenn es dort geht dann liegt ein Fehler in der existenten Installation vor. Wenn nicht gerne das Bugticket wieder aufmachen.

**Comment by Joerg-rw** [comment]
letzte erfolgreich angelegte Zeichenketten-var, offenbar nicht ueber WebUI sondern remote von user-iPhone bei app-installation angelegt:

pocketControlPushMessage  ("Change the value to push. Do not delete")

Verdacht: die an den Browser uebergebene Liste(?) mit zeichenketten-systemvariablen enthaelt ein Element das JS nicht verarbeiten kann. Wie koennte man diese Liste anzeigen lassen?

**Comment by Joerg-rw** [comment]
pb += "string sValue = '"+$("txValue").value.replaceAll("'","\\'")+"';";

[screenshot](https://i.imgur.com/4DcxDAP.png)

**Comment by jens-maus** [comment]
BTW: Bitte Screenshots hier direkt in GitHub hochladen (Drag&Drop). Sowas gehört nicht irgendwo extern hin - hab deinen letzten jetzt hier mal integriert.

**Comment by Joerg-rw** [comment]
![Screenshot_20210225_010127](https://user-images.githubusercontent.com/19670108/109082842-00639480-7705-11eb-98e1-f21f2d8e59f8.png)
ich bin ratlos

**Comment by Joerg-rw** [comment]
> Was für ein browser ist das? Die `.replaceAll()` funktion sollte es in jedem halbwegs modernen browser geben. Die Fehlermeldung verstehe ich daher nicht ganz bzw. kann sie nicht nachvollziehen (siehe https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll)

Danke! :-) Das war wohl genau auf den Punkt
Ich weiss nicht ob man nicht sowas wie str.replace(/\\'/g, '\\\\\''); (oder so aehnlich ;-D ) stattdessen verwenden koennte. 
Der Vorteil waere: in FF z.B. definiert seit version 1 von 2004-11-09 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#browser_compatibility

**Comment by jens-maus** [comment]
Ok, also gehe ich davon aus hattest du eine Firefox Version < 77 im Einsatz? Welche genau?

**Comment by Joerg-rw** [comment]
> Ok, also gehe ich davon aus hattest du eine Firefox Version < 77 im Einsatz? Welche genau?

FF 68.2.0esr (64-bit), Konqueror, Chromium Version 78.0.3904.108 (openSUSE Build) (64-bit)

Danke :-)

**Comment by jp112sdl** [comment]
Zwar leicht OT: Aber mit meinem älteren Chrome (70.x irgendwas) gehen z.B. die neuen Translate-Funktionen nicht (WebUI Fix 0111). Nach dem Chrome Update ist alles schick.

Ist die Frage, inwieweit man hier (und an anderer Stelle) abwärtskompatibel sein möchte

**Comment by Joerg-rw** [comment]
> Zwar leicht OT: Aber mit meinem älteren Chrome (70.x irgendwas) gehen z.B. die neuen Translate-Funktionen nicht (WebUI Fix 0111). Nach dem Chrome Update ist alles schick.
> 
> Ist die Frage, inwieweit man hier (und an anderer Stelle) abwärtskompatibel sein möchte

Evtl zumindest sinnvoller einsatz von `try` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#conditional_catch-blocks ?
disclaimer: total JS noob here

**Comment by Joerg-rw** [comment]
> Zwar leicht OT: 

Auch leicht OT: wie kann man dich denn mal nerven mit fragen bezueglich der AskSin HomeBrew WebUI geraetedefinitionen? Ich moecht gern ein eigenes geraetchen bauen so in der art wie ein RFID leser aber doch mit leicht anderen eigenschaften (stichwort "kbd" - ja, ich weiss, duty cycle etc pp. Nur fuer PIN eingabe, und mit rate limit) und ich komm auf keinen gruenen zweig wo ich anfangen soll mit der definition der telegrammstruktur und der GUI elemente 
analog zu https://github.com/jp112sdl/JP-HB-Devices-addon - 
woher stammt die info die einen befaehigt sowas zu schreiben?

Gerne mich kontaktieren auf 
IRC:/freenode /query Joerg-Neo900
telegram https://t.me/joerg_rw
mailto:reisenweber@web.de

Danke!
jOERG

**Comment by jens-maus** [comment]
> Zwar leicht OT: Aber mit meinem älteren Chrome (70.x irgendwas) gehen z.B. die neuen Translate-Funktionen nicht (WebUI Fix 0111). Nach dem Chrome Update ist alles schick.
> 
> Ist die Frage, inwieweit man hier (und an anderer Stelle) abwärtskompatibel sein möchte

Diese Frage müsste @theimo1221 beantworten. Da er die Optimierungen im 0111 WebUI Patch vorgenommen hat, müsste er am besten eine Aussage darüber treffen können inwieweit man die Anpassungen noch kompatibler zu älteren Browserversionen bekommt. Wenn nicht oder das zuviel aufwand bedeuten würden, dann würde ich es allerdings verschmerzbar finden wenn so alte Browser wie Chrome 70.x dann nicht mehr gehen. Der ist ja von ca. 2018 und lässt sich ja auch problemlos updaten. :)

**Comment by theimo1221** [comment]
Werde ich mir später mal anschauen, an sich bin ich in dem Patch teilweise eher auf Standard JS zurückgegangen, könnte mir spontan nur vorstellen, dass da wegen der `??` Notation gemeckert wird.

**Comment by theimo1221** [comment]
> Werde ich mir später mal anschauen, an sich bin ich in dem Patch teilweise eher auf Standard JS zurückgegangen, könnte mir spontan nur vorstellen, dass da wegen der `??` Notation gemeckert wird.

Jo, ist die `??` Notation. Ich hoffe ich komme dazu das gleich noch zu ändern. Sind in der Firma gerade ordentlich am Gas geben :-)

**Comment by jens-maus** [comment]
> Jo, ist die `??` Notation. Ich hoffe ich komme dazu das gleich noch zu ändern. Sind in der Firma gerade ordentlich am Gas geben 😄

Super. Wäre in der Tat schön wenn du das noch flott reparieren könntest oder einfach kurz nen diff hier postest und dann integriere ich das schnell noch für die nächsten nightly snapshot.

**Comment by theimo1221** [comment]
> > Jo, ist die `??` Notation. Ich hoffe ich komme dazu das gleich noch zu ändern. Sind in der Firma gerade ordentlich am Gas geben 😄
> 
> Super. Wäre in der Tat schön wenn du das noch flott reparieren könntest oder einfach kurz nen diff hier postest und dann integriere ich das schnell noch für die nächsten nightly snapshot.

Siehe #1151....

Ich hoffe ich komme die Tage noch zu der ProofAndSetValue Thematik habe dafür hier auch schon vorbereiteten Code liegen, werde aber vermutlich erst Samstag dazu kommen.
