### ISSUE TITLE
Style vom Tabellenkopf in "Programme" bei Chrome falsch

### ISSUE THREAD

**Issue by jp112sdl** [jens-maus/RaspberryMatic#1152]
**Describe the bug**
Tabellenkopf in "Programme und Verknüpfungen" => "Programme und Zentralenverknüpfungen" wird unter Chrome anders dargestellt als bei Firefox / Safari

**Steps to reproduce the behavior**
1. "Programme und Verknüpfungen"
2. "Programme und Zentralenverknüpfungen"

**Expected behavior**

Darstellung in allen Browsern gleichermaßen.

**Screenshots**

**Firefox 86.0 & Safari 14.0.3**
<img width="342" alt="Bildschirmfoto 2021-02-26 um 10 55 44" src="https://user-images.githubusercontent.com/18190139/109300436-ce524f80-7836-11eb-9c55-c0ce22a00de9.png">

**Chrome Version 88.0.4324.192**
<img width="338" alt="Bildschirmfoto 2021-02-26 um 10 56 13" src="https://user-images.githubusercontent.com/18190139/109300425-cabec880-7836-11eb-9272-e3c930efdf95.png">

**System information:**
 - RaspberryMatic Version: 3.57.4.20210225
 - Used Hardware: RPi3b
 - Used HomeMatic RF-Module: RPI-RF-MOD

**Additional context**
...

**Comment by jens-maus** [comment]
@theimo1221 Kannst du dir das bitte mal anschauen (einfach sagen wenn du nicht als der WebUI-Generalist gelten willst) :)

**Comment by Baxxy13** [comment]
Wie schon im [Homematic-Forum](https://homematic-forum.de/forum/viewtopic.php?f=65&t=65840&start=10#p647301) geschrieben tritt der Effekt erst ab ca. Chromium 88.xxx auf. 
Ein Testbrowser basierend auf Chromium 87.0.4280.66 zeigt das Verhalten nicht.

**Comment by Baxxy13** [comment]
Kurze Rückmeldung:
Mit dem heutigen Snapshot (RaspberryMatic-3.57.4.20210227-4fdf7c) "sitzt" der Tabellenkopf wieder richtig.
