### ISSUE TITLE
Beim Ändern des ssh-Passwortes erscheint ein englischer Text im PopUp

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1155]
**Describe the bug**
Beim heutigen Test des Nightly Snapshots (RaspberryMatic-3.57.4.20210227-4fdf7c) bekam ich englischen Text im PopUp beim Ändern des ssh Passwortes zu sehen.

**Steps to reproduce the behavior**
1. in Systemsteuerung --> Sicherheit das ssh Passwort ändern und auf speichern klicken
2. im PopUp ist nun _dialogSettingsSecuritySSHMsgBoxSavePasswdContent_ zu lesen

**Expected behavior**
Es sollte entweder ein deutscher Text angezeigt werden oder wie früher kein Text

**Screenshots**
![save_SSH_pw](https://user-images.githubusercontent.com/54898249/109426094-f59e4d80-79eb-11eb-9af8-669c2624384f.jpg)

**System information:**
 - RaspberryMatic Version: 3.57.4.20210227-4fdf7c
 - Used Hardware: Pi4B-4GB
 - Used HomeMatic RF-Module: RPI-RF-MOD auf GPIO

**Additional context**
Könnte eine Nebenwirkung der kürzlichen "translate Optimierung" sein. 
Vielleicht kannst du mal schauen @theimo1221

**Comment by theimo1221** [comment]
Bist du dir sicher, dass diese Thematik nicht schon vorher bestand?

Generell wird der "Schlüssel" für die Textressource benutzt, wenn es keine Übersetzung gibt.
Dies war aber auch bereits vor meiner Änderung der Fall:
(Alte Code Stelle, welche dieses Verhalten zeigt)
`return unescape((langJSON[getLang()][key] != undefined) ? langJSON[getLang()][key] : key);`

Hier wird geprüft, ob es in der gewünschten Sprache diesen Text gibt und falls nicht der Key selbst ausgegeben.

Falls früher an der Stelle also nichts stand, dann müsste früher der zugehörige Text in der Übersetzungstabelle ein Leerstring gewesen sein.

**Comment by Baxxy13** [comment]
Ich bin meistens der "Fehlerfinder" und @jp112sdl dann der "Fehleranalytiker". ;-)
Daher verweise ich mal auf das Homematic-Forum. [Link](https://homematic-forum.de/forum/viewtopic.php?f=65&t=65840&start=40#p647837)

Ein Gegentest mit dem Nightly  3.57.4.20210224 zeigt den englischen Text nicht.

**Comment by jp112sdl** [comment]
Ich kann nur soviel sagen, als dass der Text schon immer leer war und in den letzten 6 Jahren nicht angefasst wurde (lt. Git Blame)
https://github.com/eq-3/occu/blob/e16174b500af33668f04d5409c2b76adb3cc1a33/WebUI/www/webui/js/lang/de/translate.lang.extension.js#L544

Und auch die Stelle, wo der Platzhalter verwendet wird, wurde seit 2 Jahren nicht verändert:
https://github.com/eq-3/occu/blob/e16174b500af33668f04d5409c2b76adb3cc1a33/WebUI/www/config/cp_security.cgi#L1381

**Comment by theimo1221** [comment]
> Falls früher an der Stelle also nichts stand, dann müsste früher der zugehörige Text in der Übersetzungstabelle ein Leerstring gewesen sein.

Diese Aussage ist damit richtig, meine neue Logik, mag dann scheinbar den Leerstring noch nicht, eben wegen folgendem:
`!"" //ist true`
`!undefined //ist true`

Werde ich dann passend nachziehen, danke für den Hinweis

**Comment by jens-maus** [comment]
@theimo1221 kamst du schon dazu dir das hier noch einmal anzuschauen?

**Comment by jens-maus** [comment]
@theimo1221 Kann ich bitte nochmal an dieses Ticket hier erinnern? Kannst du bitte nochmal danach schauen warum bei diesem Popup die optimierte Übersetzung nicht funktioniert und wie man das am besten lösen könnte.

**Comment by theimo1221** [comment]
Sorry war untergegangen
Spätestens Dienstag Abend hast du ein Update von mir

**Comment by jens-maus** [comment]
@theimo1221 Nach meinen eigenen aktuellen Tests scheint das Problem wie von @Baxxy13 gezeigt leider immer noch nicht (trotz deines PR #1219) behoben zu sein. Wäre also schön du könntest dir das noch einmal anschauen

**Comment by jens-maus** [comment]
@theimo1221 Ok, hab nun doch mal nen kurzen blick selbst draufgeworfen und das Problem wohl gefunden und beseitigt. Nun sollten leere Übersetzungstexte kein Problem mehr darstellen.

**Comment by theimo1221** [comment]
Sieht passend aus 👍
