### ISSUE TITLE
Progressbar aria-valuenow

### ISSUE THREAD

**Issue by chr1stianC** [jens-maus/RaspberryMatic#1156]
**Describe the bug**
Mit webui-patch 0110  #1074 wurde die Nutzung von `aria-valuenow` in die Anzeige des Duty Cycles eingebaut. 
Scheinbar ist der Wert hard-coded bei 0.

**Steps to reproduce the behavior**
Anzeige mit dem ObjectInspector

**Expected behavior**
`aria-valuenow` und der DC sollten übereinstimmen.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/58345194/109458982-2c14b080-7a5e-11eb-84ed-2f285738993e.jpg)

**System information:**
Raspberrymatic 3.55.10.20210213

**Comment by jens-maus** [comment]
Danke für die Info. Sollte mit dem nächsten Release behoben sein, auch wenn ich keine praktischen Einschränkungen wahrnehmen konnte.
