### ISSUE TITLE
Cannot read CPU Teperature from /sys/class/thermal/thermal_zone0/temp on Asus Tinker Board S with latest nightly build

### ISSUE THREAD

**Issue by hotroot** [jens-maus/RaspberryMatic#1159]
**Describe the bug**
With the today's nightly build it's not possible to get the CPU temperature from /sys/class/thermal/thermal_zone0/temp. This e.g. breaks the check_mk addon. 

**Steps to reproduce the behavior**
1. Login via SSH to RaspberryMatic
2. execute `cat /sys/class/thermal/thermal_zone0/temp`
3. notice the error-output `cat: read error: Invalid argument`

**Expected behavior**
`cat /sys/class/thermal/thermal_zone0/temp` should output the current CPU temperature

**Screenshots**
```
root@homematic-raspi:~# cat /sys/class/thermal/thermal_zone0/temp 
cat: read error: Invalid argument
```

**System information:**
 - RaspberryMatic Version: 3.57.4.20210302
 - Used Hardware: Asus Tinker Board S
 - Used HomeMatic RF-Module: RPI-RF-MOD

**Additional context**
...

**Comment by jens-maus** [comment]
Bitte mal `cat /sys/class/thermal/thermal_zone1/temp` bzw. `cat /sys/class/thermal/thermal_zone2/temp` testen und berichten ob diese ein Ersatz sein könnten?

**Comment by hotroot** [comment]
Hallo Jens,

hier kommt ein Wert zurück:
```
root@homematic-raspi:~# cat /sys/class/thermal/thermal_zone1/temp 
57727
root@homematic-raspi:~# cat /sys/class/thermal/thermal_zone2/temp 
56363
```

**Comment by jens-maus** [comment]
Ok, ich denke ich hab die Ursache gefunden warum plötzlich thermal_zone0 nicht mehr genutzt werden konnte. Nun sollte alles wieder beim alten sein mit dem nächsten nightly build.

**Comment by hotroot** [comment]
Kann bestätigen, das Auslesen der CPU-Temperatur über /sys/class/therman/thermal_zone0/temp funktioniert wieder
