### ISSUE TITLE
Version 2.27.8.20170615 crashes after a couple of hours

### ISSUE THREAD

**Issue by aberghoff** [jens-maus/RaspberryMatic#116]
The new versions runs inbetween 4 and 36 hours (I had to crashes). Then the Web-Interface and obviously the execution of programs, initiated by events, does not work.
The old version was stable over weeks.

**Comment by chrostek** [comment]
I have exactly the same problem

**Comment by anli-xsigns** [comment]
Are there entries in the log? What is the output of 'ps -ef' on the ssh console when the ccu2 is crashed? Maybe https://homematic-forum.de/forum/viewforum.php?f=65 is the better place to discuss until the problem/bug is found.

**Comment by jens-maus** [comment]
I already found and fixed the problem (it is an issue with the linux kernel) thanks for the reports. I will try to release a fixed version until monday

**Comment by anli-xsigns** [comment]
Great :-) Firmware 2.29 is on it's way too ;-)

**Comment by jens-maus** [comment]
Sure, but this will have to be integrated in another version.

**Comment by jens-maus** [comment]
Commit fd1c3c67b266cca783f18d7aa9cf1a6e771549ad should fix this problem.
