### ISSUE TITLE
Bedingungstext für Programme mit Negationen wird falsch generiert

### ISSUE THREAD

**Issue by Maik2208** [jens-maus/RaspberryMatic#1160]
**Describe the bug**
Beim Anlegen eines Programms generiert sich der Text in "Bedingung (Wenn...)" automatisch. Lege ich eine negierte Bedingung an "nicht bei", dann wird die Bedingung in dem Textfeld dennoch positiv formuliert.

**Steps to reproduce the behavior**
1. ...
2. ...
3. ...
4. ...

**Expected behavior**
Die Bedingung in dem Textfeld sollte ebenfalls negiert werden.

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: 3.55.10.20210213
 - Used Hardware: RPi3
 - Used HomeMatic RF-Module: MOD

**Additional context**
...

**Comment by jp112sdl** [comment]
Ich hab das Ticket inhaltlich nicht verstanden.
Wo ist welcher Text falsch (Screenshot?) ?

**Comment by Maik2208** [comment]
Hier ein Beispiel:
![Fehler 1](https://user-images.githubusercontent.com/79879510/109664149-235ed000-7b6d-11eb-8d71-2c7a904f823b.jpg)
![Fehler 2](https://user-images.githubusercontent.com/79879510/109664157-2659c080-7b6d-11eb-8d39-dc89487c17d2.jpg)

Ist bei den anderen negierten Bedingungen ebenfalls so.

**Comment by jp112sdl** [comment]
Ahh, jetzt hab' ich's kapiert

**Comment by jp112sdl** [comment]
@jens-maus Soll die kleine Anpassung mit in 0077-WebUI-NegateCondition.patch ?

**Comment by jens-maus** [comment]
> @jens-maus Soll die kleine Anpassung mit in 0077-WebUI-NegateCondition.patch ?

Ja, gerne!
