### ISSUE TITLE
Status des DockerImage ist immer unhealthy (Betrieb als LAN-Gateway)

### ISSUE THREAD

**Issue by Lehnerr** [jens-maus/RaspberryMatic#1163]
**Describe the bug**
Ich habe das DockerImage auf Ubuntu 20.04 installiert und betreibe es als LAN-GateWay.
Der LanGateway funktioniert einwandfrei nur der Status des dockerimages ist immer "unhealty" 

**Steps to reproduce the behavior**
1. Configure as LANgateway

**Expected behavior**
Status sollte healthy sein.

**Screenshots**
![image](https://user-images.githubusercontent.com/16813374/109683686-e2bc8200-7b7f-11eb-89a5-98722b1011e0.png)

**System information:**
 - RaspberryMatic Version:  ghcr.io/jens-maus/raspberrymatic:latest
 - Used Hardware: Docker
 - Used HomeMatic RF-Module: HMIPF-USB

**Additional context**
Vermute, dass das Healthsript nicht für LAN-Gateway funktioniert. Bevor ich es umgestellt habe lief es im Status healthy.

**Comment by jens-maus** [comment]
> Vermute, dass das Healthsript nicht für LAN-Gateway funktioniert. Bevor ich es umgestellt habe lief es im Status healthy.

Diese Vermutung ist vollkommen korrekt. Momentan unterstützen sicher so manche dinge nicht den LAN-Gateway Modus einer Docker-basierten RaspberryMatic Installation.

> * Used HomeMatic RF-Module: HMIPF-USB

BTW: Das beisst sich aber mit der Idee RaspberryMatic als LAN Gateway zu benutzen. Der LAN Gateway-Modus von RaspberryMatic funktioniert **NUR** für den alte BidCos-RF/HomeMatic Betrieb und ein HmIP-RFUSB USB Stick kann kein traditionelles BidCos-RF/HomeMatic, sondern nur homematicIP und das kann man nicht als LAN-Gateway via RaspberryMatic betreiben. D.h. auch wenn ich den healthy check korrigiere wird der LAN Gateway-Modus nicht mit einem HmIP-RFUSB funktionieren.

**Comment by jens-maus** [comment]
So, sollte mit dem nächsten Release dann behoben sein.

Mehr Infos zum LAN-Gateway-Betrieb findet man hier (auch bzgl. notwendigkeit ausgewählter Funkmodule):
https://github.com/jens-maus/RaspberryMatic/wiki/Experten-Features#lan-gateway-betrieb

**Comment by Lehnerr** [comment]
Komischerweise funktioniert es aber als LanGateway. Habe erfolgreich meine Tür und Fensterkontakte damit verknüpft.

Danke auf jedenfalls.

**Comment by jens-maus** [comment]
> Komischerweise funktioniert es aber als LanGateway. Habe erfolgreich meine Tür und Fensterkontakte damit verknüpft.

Das denkst du nur! Dann werden die Geräte von anderen BidCos-fähigen Funkmodulen angesteuert ohne das du das bemerkst und die Verknüpfung in der WebUI greift da definitiv nicht! Dass ist definitiv so: ein HmIP-RFUSB kann technisch bedingt kein BidCos-RG/HomeMatic!

**Comment by Lehnerr** [comment]
Hallo.
Ja das stimmt, Danke für die info.
