### ISSUE TITLE
Gibt es eine Möglichkeit die RaspberryMatic/CCU3 ohne Virtualisierung zu installieren?

### ISSUE THREAD

**Issue by DominikErnst** [jens-maus/RaspberryMatic#1165]
Hallo, ich möchte auf einem Raspberry 4 IOBroker und RaspberryMatic/CCU3 parallel laufen lassen und das ohne diesem nutzlosen und komplizierten Virtualisierunsgedöns.

Ist das möglich?
Wie installiere ich RaspberryMatic manuell?
IOBroker lässt sich "nur" noch über curl installieren, gibt es so ein script auch für RaspberryMatic?

Das ganze sollte natürlich auf dem original Raspi OS laufen. 

Vielen Dank.

**Comment by jens-maus** [comment]
Sorry, but this is no support or discussion fora here. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. This was also already mentioned in the ticket template!
___
Tut mir leid, aber das hier ist kein Supportforum, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen.  Dies stand übrigens auch so im Ticket Template!

**Comment by DominikErnst** [comment]
Yes, ok, sorry. Can't delete the entry :-( But I see it's not visible anymore.
