### ISSUE TITLE
Integrate xinetd support

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#117]
For allowing to more easily install certain inet services the `xinetd` daemon should be installed and configured to source typical xinetd config files from `/etc/config/xinetd.d` to provide users and addon developers the chance to create services that listen for a specific port like this is performed/supported on a standard linux system.

**Comment by migele99** [comment]
?Hi Jens, da ich stark Durch Deine Aktivitäten profitiere (Aufbau meiner HomeMatic anlage) würde ich gerne "etwas zurück geben" und Dich fragen, ob Du "Donations" annimmst? (wenn ja, bitte kurz bescheid geben wohin ich überweisen soll)

vg Michael

________________________________
Von: Jens Maus <notifications@github.com>
Gesendet: Montag, 19. Juni 2017 11:42
An: jens-maus/RaspberryMatic
Cc: Subscribed
Betreff: Re: [jens-maus/RaspberryMatic] Integrate xinetd support (#117)


Closed #117<https://github.com/jens-maus/RaspberryMatic/issues/117> via 0cf9e3c<https://github.com/jens-maus/RaspberryMatic/commit/0cf9e3cd1f969858daa1ff2388a166d0cdb983eb>.

-

**Comment by PhilipHanebeck** [comment]
schau einfach mal auf das Web-UI unter Einstellungen -> Systemsteuerung -> Zentralenwartung

**Comment by jens-maus** [comment]
@migele99 Na klar. Der PayPal Link ist sogar auf der Hauptseite des RaspberryMatic Projektes mehrfach zu finden:

https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=RAQSDY9YNZVCL

**Comment by migele99** [comment]
?done, vielen Dank noch einmal für Dein Engagement !

Michael


email: michael@mykrause.de

________________________________
Von: Jens Maus <notifications@github.com>
Gesendet: Montag, 19. Juni 2017 13:13
An: jens-maus/RaspberryMatic
Cc: Krause, Michael; Mention
Betreff: Re: [jens-maus/RaspberryMatic] Integrate xinetd support (#117)


@migele99<https://github.com/migele99> Na klar. Der PayPal Link ist sogar auf der Hauptseite des RaspberryMatic Projektes mehrfach zu finden:

https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=RAQSDY9YNZVCL

-

**Comment by jens-maus** [comment]
Danke für deine Spende. Das motiviert wirklich sehr weiter zu machen!

**Comment by migele99** [comment]
nein, wirklich ... great JOB !!! Hoffentlich unterstützt ELV auch so gut. Ich würde mir wünschen, wenn die Kollegen die CCU in Rente schicken und sich dafür auf Raspberry konzentrieren würden.

vg Michael

________________________________
Von: Jens Maus <notifications@github.com>
Gesendet: Montag, 19. Juni 2017 13:28
An: jens-maus/RaspberryMatic
Cc: Krause, Michael; Mention
Betreff: Re: [jens-maus/RaspberryMatic] Integrate xinetd support (#117)


Danke für deine Spende. Das motiviert wirklich sehr weiter zu machen!

-

**Comment by migele99** [comment]
Hallo Jens, ich wollte mir das neue Raspi-Matic auf einen USB Stick bruzzeln, konnte aber mit der Beschreibung nix anfangen:

Eine freie microSD Karte (2 GB minimum) mittels microSD-Card Reader an einen Rechner anbinden (Alternativ kann bei Einsatz eines RaspberryPi3 auch das Image auf einen USB stick oder USB Festplatte installiert werden - hierbei bitte beachten das wenn der Pi3 noch NIE von USB gebootet wurde muss für den ersten Boot zwingend RaspberryMatic mittels microSD Karte gebootet werden, danach kann dann von USB gebootet werden)

Was bedeutet das fett markierte konkret?
Vg Michael

Von: Krause, Michael
Gesendet: Dienstag, 20. Juni 2017 08:29
An: jens-maus/RaspberryMatic <reply@reply.github.com>
Betreff: AW: [jens-maus/RaspberryMatic] Integrate xinetd support (#117)


nein, wirklich ... great JOB !!! Hoffentlich unterstützt ELV auch so gut. Ich würde mir wünschen, wenn die Kollegen die CCU in Rente schicken und sich dafür auf Raspberry konzentrieren würden.

vg Michael

________________________________
Von: Jens Maus <notifications@github.com<mailto:notifications@github.com>>
Gesendet: Montag, 19. Juni 2017 13:28
An: jens-maus/RaspberryMatic
Cc: Krause, Michael; Mention
Betreff: Re: [jens-maus/RaspberryMatic] Integrate xinetd support (#117)


Danke für deine Spende. Das motiviert wirklich sehr weiter zu machen!

-

**Comment by jens-maus** [comment]
@migele99 Dies ist eine Frage für das homematic-forum und nicht für GitHub und vor allem nicht für dieses Ticket das bereits geschlossen ist. Also bitte nicht einfach auf GitHub Emails via Email antworten sondern über die GitHub Seiten ein neues Ticket öffnen (wenn es Probleme gibt) oder aber im homematic forum das problem diskutieren.
