### ISSUE TITLE
Systemvariable Typ Text lässt sich nicht bearbeiten wenn der enthaltene Text das Steuerzeichen für "new line" ( \n ) enthält

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1177]
**Describe the bug**
Übergibt man an eine Text-SysVar einen Text mit enthaltenem Steuerzeichen für "new line" ( \n ) ist diese anschließend nicht mehr über Einstellungen > Systemvariablen bearbeitbar. Es erscheint nur noch ein "leeres" PopUp (sieh Screenshots).

**Steps to reproduce the behavior**
1. Systemvariable Typ Text anlegen (Namensbeispiel: A_Test_komischer_Text)
2. SysVar mit Beispieltext (siehe Additional context) per Script beschreiben
3. in Einstellungen > Systemvariablen die entsprechende SysVar bearbeiten

**Expected behavior**
Ein Steuerzeichen für "new line" ( \n ) innerhalb eines Textes der SysVar sollte nicht dazu führen das sich diese nicht mehr bearbeiten lässt.

**Screenshots**
![SV_Text_unbearbeitbar_PopUp](https://user-images.githubusercontent.com/54898249/111308219-b3674400-865a-11eb-8d2d-125f60999301.JPG)
Die SyVar an sich wird unter Status und Bedienung > Systemvariablen korrekt dargestellt:
![SV_Text_unbearbeitbar_Ansicht ok](https://user-images.githubusercontent.com/54898249/111308333-d5f95d00-865a-11eb-822e-a67eb4c0d9ba.JPG)

**System information:**
 - RaspberryMatic Version: Nightly Snapshot 3.57.4.20210313
 - Used Hardware: Pi4B-4GB
 - Used HomeMatic RF-Module: RPI-RF-MOD auf GPIO

**Additional context**
Testscript:
`dom.GetObject (ID_SYSTEM_VARIABLES).Get ("A_Test_komischer_Text").State("Zeile 1 mit newLine\nZeile 2 ohne newLine");`

Das Problem trat kürzlich schon einmal in ähnlicher Form auf und sollte doch eigentlich durch #1111 gefixed sein.

**Comment by jens-maus** [comment]
Das liest sich nach arbeit für @jp112sdl :) da es ja sicher seine eingeführte Funktionalität für das Editieren des Inhaltes einer Systemvariable betrifft.

**Comment by jp112sdl** [comment]
Das Problem tritt auf, wenn `sval` den Linebreak enthält 
https://github.com/jens-maus/RaspberryMatic/blob/46a490944d7fe2484f9a9d94b71b58e139815f06/buildroot-external/patches/occu/0097-WebUI-SetSysvarValueByUser/occu/WebUI/www/rega/pages/tabs/admin/msg/newSysVar.htm#L466

und der Java-Methode `loadChar8859Edit` übergeben werden soll
https://github.com/jens-maus/RaspberryMatic/blob/46a490944d7fe2484f9a9d94b71b58e139815f06/buildroot-external/patches/occu/0097-WebUI-SetSysvarValueByUser/occu/WebUI/www/rega/pages/tabs/admin/msg/newSysVar.htm#L436-L444

Als quick&dirty Workaround geht es, wenn man nach Zeile 463 noch ein
```
        sval = sval.Replace("\n","MILF");^M                                                                                                                     
```
hinzufügt, um in Rega-TCL den Linefeed umzuwandeln und das anschließend wieder zurück ersetzt in Zeile 440 mit
```
    s += "<tr><td> <textarea id='txValue' rows='1'>"+sValue.replace(/MILF/g,"\n")+"</textarea> </td></tr>";                                              
```

_MILF steht hier für My Individual Line Feed_ 😋 

**Wie man es elegant lösen kann, weiß ich nicht. Aber @theimo1221  evtl.?**

**Comment by Baxxy13** [comment]
Kurze Rückmeldung:
Sieht mit dem heutigen Nightly (RaspberryMatic-3.57.4.20210317-c0e29e) sehr gut aus und funktioniert wie erwartet.
![Text_SV_mit_nl_working](https://user-images.githubusercontent.com/54898249/111434454-dac41c80-86ff-11eb-975c-78aab85a8550.JPG)

**Comment by jens-maus** [comment]
> Sieht mit dem heutigen Nightly (RaspberryMatic-3.57.4.20210317-c0e29e) sehr gut aus und funktioniert wie erwartet.

Danke für die Rückmeldung. Dann teste gerne noch ein paar mehr sonderzeichen die dir so einfallen bzw. über den Weg laufen. Bin mir sicher das das \n nicht das einzige ist das ggf. Probleme macht. Und immer schön die Fehlerkonsole des Browsers im Auge behalten beim testen ;)

**Comment by theimo1221** [comment]
> **Wie man es elegant lösen kann, weiß ich nicht. Aber @theimo1221 evtl.?**

![image](https://user-images.githubusercontent.com/20605452/111437489-7440fd80-8703-11eb-9796-9203f17207d9.png)

Base64 ist hier der einfachste Weg ;-)

**Comment by jens-maus** [comment]
> > **Wie man es elegant lösen kann, weiß ich nicht. Aber @theimo1221 evtl.?**
> 
> Base64 ist hier der einfachste Weg ;-)

Ist sicher auch ne lösung. Die frage wäre nur: 1. Wieviel overhead macht das und 2. bis zu welchen browser versionen funktioniert das `btoa()`/`atob()` in JS?

**Comment by theimo1221** [comment]
![image](https://user-images.githubusercontent.com/20605452/111439152-5eccd300-8705-11eb-9b04-668f1163e897.png)

Eigentlich jeder Browser seit etwa 2012. Und Java seitig ist seit Java 8 Base64 auch on Board (https://www.baeldung.com/java-base64-encode-and-decode)
Einzige Nachteil von Base64 sind non Latin Characters.

**Comment by jens-maus** [comment]
@theimo1221 Also der Hinweis mit dem base64 encoding/decoding war schonmal ein sehr guter! Musste nun aber auf URLencoding/decoding (`%20` == ` `) ausweichen, da der eine Teil ja in ReGa-Skripting passiert und da es keine native base64 encoding funktion gibt. Erscheint mir aber ohnehin ggf. die besser Lösung zu sein das via URLEncoding/Decoding zu erledigen. Wie oben zu sehen spart das nun auch den ursprünglichen fix (#1111) von @jp112sdl für das `'` und `\` gleich mit ein :)

Danke noch einmal für die Idee!
