### ISSUE TITLE
Schreibfehler auf Festplatte wird nicht gemeldet --> Geräte fehlen im Backup und verschwinden bei Neustart

### ISSUE THREAD

**Issue by theimo1221** [jens-maus/RaspberryMatic#1183]
**Describe the bug**
Seit mindestens 3.57.4.20210223 besteht bei mir ein Fehler, der dazu führt das neu angelernte Geräte beim Neustart "vergessen" werden. Sind die Geräte frisch angelernt so sind sie selbst in einem anschließend erstellten Backup nicht enthalten. Auf die neuste Version kann ich aktuell nicht einmal wechseln, es hängt bei Dateien werden übertragen.

**Steps to reproduce the behavior**
1. Geräte anlernen
2. Backup erstellen
3. RaspBerryMatic über das WebUI neustarten
4. Feststellen neue Geräte fehlen
5. Backup einspielen
6. Feststellen Geräte fehlen immer noch

**Expected behavior**
Selbst neue Geräte werden vor Neustart passend persistiert und sind im Backup enthalten.

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: 3.57.4.20210223
 - Used Hardware: RaspberryPi 4
 - Used HomeMatic RF-Module: RF USB Stick

**Additional context**
Etwa 100 Geräte im Verbund

**Comment by theimo1221** [comment]
Ich glaube meine Installation ist komplett im Eimer...

Neustart in den Recovery landet im normalen Webui. Neuere Version kann ich nicht reinladen (Hängt sich beim hochladen auf)

**Comment by jp112sdl** [comment]
Klingt nach kaputter SD Karte.

**Comment by theimo1221** [comment]
> Klingt nach kaputter SD Karte.

Dafür/Gegen haben wir keine Erkennungen?
Quasi Schreiben von Daten in internen Speicher fahlgeschlagen?

**Comment by jp112sdl** [comment]
Wenn du dich per SSH anmeldest, schau doch mal mit `dmesg`, ob da irgendwelche Kernel-Fehler/-Warnungen zu finden sind

**Comment by theimo1221** [comment]
[KernelLog.txt](https://github.com/jens-maus/RaspberryMatic/files/6171160/KernelLog.txt)
![image](https://user-images.githubusercontent.com/20605452/111782938-ed825100-88b9-11eb-9718-9809a77f7036.png)

**Comment by Baxxy13** [comment]
Um was für Geräte geht es eigentlich? HmIP, BidCos... etc?
Alle angelernten IP-Geräte sollten in _/usr/local/etc/config/crRFD/data_ gelistet sein.
Alle angelernten BidCos-Geräte sollten in _/usr/local/etc/config/rfd_ gelistet sein.

Zusätzlich müssten sich Verweise zu allen Geräten in der _/usr/local/etc/config/homematic.regadom_ finden lassen.

Wann genau alles nach dem Anlernen von Geräten gespeichert wird weiß ich nicht. Aber spätestens nach Ab/Neuanmeldung in der WebUI bzw. "Änderungen speichern" Button im WebUI-Kopf sollten die Daten persistent sein. 
Findest du dann keine Dateien vor riecht das wirklich stark nach defekter SD.

**Comment by theimo1221** [comment]
> Um was für Geräte geht es eigentlich? HmIP, BidCos... etc?
HmIP

Ich werde später eine neue SD Karte erhalten (Same Day Lieferung) und dort die neuste Version draufspielen.


In vim habe ich gerade die Meldung "read-only-filesystem" erhalten

**Comment by jp112sdl** [comment]
> In vim habe ich gerade die Meldung "read-only-filesystem" erhalten

Außer `/usr/local` ist alles (also die root-Partition) grundsätzlich read-only gemountet.

**Comment by theimo1221** [comment]
> > In vim habe ich gerade die Meldung "read-only-filesystem" erhalten
> 
> Außer `/usr/local` ist alles (also die root-Partition) grundsätzlich read-only gemountet.

hm, dann probiere ich später den Ordner mal aus
Sagt euch der Log etwas?

**Comment by theimo1221** [comment]
Mit einer neuen SD Karte und der neusten Version läuft es.

Dennoch würde ich es begrüßen wenn wir was einbauen können, wenn Schreibzugriffe auf die SD Karte fehlschlagen....

**Comment by jp112sdl** [comment]
Es läuft jede Nacht ein `badblocks` check, allerdings nur lesend.
Und es war in deinem Kernel-Log auch kein Hinweis auf ein Problem mit der SD Karte.
Ich hab zumindest keine Ahnung, wo man da grad noch ansetzen könnte

**Comment by jens-maus** [comment]
Auch ich wüsste nicht was man da "noch mehr" machen könnte diesbzgl. SD Karten sind bekanntermaßen eine Schwachstelle des Systems bzw. RaspberryPi. Deshalb entweder ein Tinkerboard mit eMMC nutzen oder eine externe SSD oder noch besser auf ein vollkommen virtuelles System umschwenken.

Insofern sehe ich hier keinen Weiteren Ansatz wie man hier noch etwas verbessern könnte.

**Comment by Baxxy13** [comment]
Mir kam da gerade eine Idee...

Die homematic.regadom wird doch zyklisch gespeichert (alle 12h wenn man ausgeloggt ist?). 
Ließe sich da nicht der Zeitstempel prüfen/überwachen und ein Alarm generieren wenn der letzte Zeitstempel länger her als der Zyklus ist?
Oder kann das System nicht selbst einen Alarm generieren wenn das speichern der homematic.regadom fehlschlägt?
