### ISSUE TITLE
AskSin Gardena Umbau - Update 3.57.4.20210320 - Kommunikation gestört

### ISSUE THREAD

**Issue by etofi** [jens-maus/RaspberryMatic#1185]
**Describe the bug**
Mein [AskSin Gardena Umbau](https://github.com/wolwin/WW-mySHP/tree/master/SHP_HM-LC-SW1-BA-PCB-GAR1251) funktioniert in der Version 3.55.10.20210213 einwandfrei.
Mit dem Update auf Version 3.57.4.20210320 erhalte ich permanent die Meldung "Kommunikation gestört".
Ich sehe zwar an den LEDs dass die Signale empfangen werden, aber irgendwie scheinen die Rückmeldungen nicht bei der CCU anzukommen.

**Steps to reproduce the behavior**
1. Update auf Version 3.57.4.20210320
2. Meldung "Kommunikation gestört"
3. Downgrade zur Version 3.55.10.20210213
4. Meldung "Kommunikation gestört" weg

**Expected behavior**
AskSin Gardena Umbau soll in der Version 3.57.4.20210320 genauso funktionieren wie mit der Version 3.55.10.20210213

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: ...
 - Used Hardware: ...
 - Used HomeMatic RF-Module: ...

**Additional context**
...

**Comment by Hypnos3** [comment]
Hallo,

mit der CCU FW Version 3.57.4 wird auch eine neue Firmware für das RPI-RF-MOD (4.2.14) geladen und in dieser gibt es Anpassung der Frequenz. Im Grunde ist das eine Korrektur. Die Frequenz des RPI-RF-MOD ist seit irgendeiner Firmware "verschoben" gewesen und das wurde jetzt korrigiert. Damit sind dann alle HomeMatic (nicht IP) Geräte wieder besser erreichbar.

ür die Selbstbau - AskSin Sensoren, welche evtl. mit dem FreqTest abgeglichenen wurden, bedeutet es aber dass diese damit erneut abgeglichen werden müssen oder diese sind nicht mehr (zuverlässig) erreichbar.

siehe auch
- [Informationen / “Known Bugs”](https://jp112sdl.github.io/JP-HB-Devices-addon/jphbInfoPage)
- [Homematic Forum](https://homematic-forum.de/forum/viewtopic.php?f=76&t=63125&p=648643#p648640)

**Comment by etofi** [comment]
Ich bin anscheinend nicht alleine mit dem Problem.
[Hier ein Post im Homematic Forum mit dem gleichen Problem](https://homematic-forum.de/forum/viewtopic.php?f=76&t=49719&start=110#p652295)

**Comment by Hypnos3** [comment]
Das Problem wird bei allen auftreten, welche das RPI-RF-MOD verwenden und AskSin Geräte zusammengebaut haben.

**Comment by jp112sdl** [comment]
Die Antwort ist etwas zu pauschal... Konkreter:
Es wird diejenigen betreffen, die einen FreqTest mit dem RPI-RF-MOD durchgeführt haben

**Comment by jens-maus** [comment]
Da dies kein Problem von RaspberryMatic selbst ist, aber hier eben bei AskSin Geräte ein neuer Frequenzabgleich gemacht werden muss schließe ich das Ticket hier entsprechend.
