### ISSUE TITLE
Renaming a device does not update name in tree

### ISSUE THREAD

**Issue by HolgerJeromin** [jens-maus/RaspberryMatic#1186]
**Steps to reproduce the behavior**
1. open setting/device
2. rename a device
3. tree is reloaded
4. The device is shown with the old name.

**Expected behavior**
The device should be shown with the new name.

**System information:**
 - RaspberryMatic Version: v3.57.4.20210320
 - Used Hardware: ccu3

**Additional context**
Probably a bug related to this optimisation #1136 
cc @theimo1221

**Comment by jens-maus** [comment]
@jp112sdl, @Baxxy13, @theimo1221 could you verify this issue? I doubt that renaming a device should really be an issue or otherwise our tests might have revealed it.

**Comment by jp112sdl** [comment]
No problem here (also using `3.57.4.20210320`)

**Comment by Baxxy13** [comment]
I also have no problems with that. 
After renaming a device or a channel the new name is showed correct and nearly instantly.

RM 3.57.4.20210320
(Tested with Firefox 86.0.1 (64-Bit) and Chromium 87.0.4280.66 based browser)

**Comment by Maik2208** [comment]
Das Problem hatte ich in der Februar-Version auch schon. Habe es aber nicht gemeldet, da ich es nicht sauber reproduzieren konnte. Scheint also etwas tricky zu sein.

**Comment by blackbasket** [comment]
I can confirm that the issue exists in 3.55.10.20210213 as well. As @Maik2208 says. I did not mention this because I migrated to the version in February the first time and thought, I did something wrong.

**Comment by jens-maus** [comment]
I am actually not sure what to do here. I also cannot reproduce this myself, thus we definitly need more information here or simply just a screencast demonstrating the issue.

**Comment by HolgerJeromin** [comment]
Hmm. Had this in my session after added a new HmIP-BSM. But now it works like a charme. 8-/
