### ISSUE TITLE
Add Raspberry Pi A/B to the list of supported devices

### ISSUE THREAD

**Issue by renne** [jens-maus/RaspberryMatic#119]
Please add Raspberry Pi A/B to the list of supported devices.

**Comment by jens-maus** [comment]
Have you verified that these models already work? Because I don't have test devices here to verify myself.

**Comment by renne** [comment]
The HM-MOD-RPI-PCB doesn't work with a RPi 1B. Syslog displays:
`bcm2835_raw_uart: invalid parameter 'uart0_base'`
`bcm2835_raw_uart: invalid parameter 'uart0_irq'`

**Comment by jens-maus** [comment]
Which version of RaspberryMatic are you using? If you use the plain 2.27.8.20170620 please apply the following patch and try again:

https://github.com/jens-maus/RaspberryMatic/commit/7ddb90307c88177264e60a50b7d46e728350876e

**Comment by renne** [comment]
@jens-maus The patch https://github.com/jens-maus/RaspberryMatic/commit/7ddb90307c88177264e60a50b7d46e728350876e works with plain 2.27.8.20170620 on the Pi B/512MB and HM-MOD-RPI-PCB. You can add the Pi B/512MB to the list of supported devices. :)

**Comment by jens-maus** [comment]
Ok, added to the list of supported devices. Thanks for the verification.
