### ISSUE TITLE
Proxmox: CUxD funktioniert nach Update (oder Neuinstallaiton) auf Version 3.57.4.20210320 nicht mehr

### ISSUE THREAD

**Issue by Piri22** [jens-maus/RaspberryMatic#1190]
Es scheint ein Problem mit CUxD und der neuen raspberrymatic-Version für Proxmox zu geben.
In der CCU3 Version ist unter "Zusatzsoftware-CUxD" zu lesen:
Installierte Version: 2.5.1
Verfügbare Version: 2.5.1
Außerdem gibt es einen Button als Link zum CUxD Deamon in der Systemsteuerung.
In der Proxmox Version ist unter "Zusatzsoftware-CUxD" zu lesen:
Installierte Version:
Verfügbare Version: 2.5.1
Außerdem existiert kein Button als Link zum CUxD Deamon in der Systemsteuerung.
Hat man keine Neuinstallation des Proxmox Containers vorgenommen, sondern ein Update, dann existiert der Button zwar noch, führt jedoch jedes Mal zu einem CCU Neustart.

**Comment by jens-maus** [comment]
Das kann ich aus eigener erfahrung nicht bestätigen. CUxD geht bei mir und bei vielen anderen auch problemlos.

**Comment by jens-maus** [comment]
Bzw. Natürlich muss man unter Proxmox, wegen dem Platform wechsel, auch das richtige CUxD binary installieren. Proxmox ist x86 und eine CCU3 ist ein RaspberryPi. Bitte also kontrollieren.

**Comment by Piri22** [comment]
Autsch. Blöder Anfängerfehler!
Jepp, das war es!
