### ISSUE TITLE
Zu viele Schreibzugriffe auf SD-Karte

### ISSUE THREAD

**Issue by rusitschka** [jens-maus/RaspberryMatic#1192]
**Describe the bug**
Raspberrymatic schreibt /etc/config/homematic.regadom viel zu häufig auf die SD-Karte. Die Datei ist bei mir 2.6 MB groß und wird bei meiner Docker-basierten Installation alle 30 Sekunden auf die SD-Karte geschrieben. Das sind 7.5 GB/Tag und im 24/7 Betrieb zu viele Schreibzugriffe für jede SD-Karte. Bei mir ist bereits eine SD-Karte vermutlich dadurch defekt geworden. [Issue 1183](https://github.com/jens-maus/RaspberryMatic/issues/1183) könnte auch damit zusammenhängen.

**Steps to reproduce the behavior**
1. iotop -a -o ein paar Minuten auf dem Host laufen lassen
2. ``` 4077 be/4 root          0.00 B     15.45 M  0.00 %  0.00 % ReGaHss -f /etc/rega.conf -l 2```
3. ReGaHss erzeugt ein hohes Schreibvolumen (15.45 MB nach 3 Minuten)

**Expected behavior**
Nur, wenn sich die Datei auch verändert, sollte sie geschrieben werden. Außerdem sollten volatile Daten, insbesondere der DutyCycle, nicht mit persistiert werden.

Langfristig sollte das Abspeichern einer 2.6 MB Datei komplett vermieden werden, nur weil sich eine einzige Variable ändert. Datenbank?

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: 3.57.4.20210320
 - Used Hardware: Raspberry Pi 3
 - Used HomeMatic RF-Module: RPI-RF-MOD

**Additional context**
Ich habe bereits einen Workaround gefunden über einen eigenen Entrypoint, aber ich denke das Problem muss in Raspberrymatic/OCCU/? gefixt werden, da es nicht nur für die Docker-basierte Installation gilt, sondern für alle. Durch den Workaround konnte ich die Schreibzugriffe auf 10% reduzieren. Noch nicht ideal, aber wesentlich besser, also zuvor.

Ich vermute, dass in 80% der Fälle die DutyCycle-Variable den Schreibvorgang erfordert. Meistens sieht ein diff folgendermaßen aus:
```xml
/ # diff -Nur /tmp/homematic.regadom /etc/config/homematic.regadom
--- /tmp/homematic.regadom
+++ /etc/config/homematic.regadom
@@ -12320,7 +12320,7 @@
 <type>0</type>
 </valdef>
 </dp>
-<var>24.000000</var>
+<var>25.000000</var>
 <varType>4</varType>
 </var-dp>
 </vardpmap>
```

24->25 war genau die Änderung des DutyCycles.

Hier ist der entrypoint.sh von meinem Workaround:
```sh
#!/bin/sh
set -e

TEMP_FOLDER="/tmp"
TEMP_DOM="$TEMP_FOLDER/homematic.regadom"
PERSISTENT_DOM="/etc/config/homematic.regadom"

sed 's|DomFileName=/etc/config|DomFileName=/tmp|' -i /etc/rega.conf

function persist_dom()
{
  while ! mount | grep "$TEMP_FOLDER" || ! test -e "$PERSISTENT_DOM"
  do
    echo "Waiting for temp folder and persistent file"
    sleep 1
  done

  echo "Putting homematic.regadom to RAM disk"
  cp "$PERSISTENT_DOM" "$TEMP_DOM"

  while true
  do
    if test -e "$TEMP_DOM" && test -e "$PERSISTENT_DOM"
    then
      while true
      do
        FILE_AGE=$(echo "$(date +'%s') - $(stat -c '%Y' $TEMP_DOM)" | bc)
        if test "$FILE_AGE" -gt 10
        then
          break
        fi
        sleep 1
      done
      while ! cmp -s "$TEMP_DOM" "$PERSISTENT_DOM"
      do
        echo "$(date) Persisting modified homematic.regadom"
        cp "$TEMP_DOM" "$PERSISTENT_DOM"
        sleep 1
      done
    fi
    sleep 120
  done
}

persist_dom &

exec /sbin/init
```

Verwendbar über
```sh
docker run -v $PWD/entrypoint.sh:/entrypoint.sh --entrypoint /entrypoint.sh ... ghcr.io/jens-maus/raspberrymatic
```

**Comment by jens-maus** [comment]
Danke erst einmal für dies Hinweise. Als erstes muss ich natürlich anmerken, dass eine SD-Karten basierte Lösung nie die optimalste sein kann. Es erscheint mir (gerade wenn man eine Docker-Umgebung einsetzt) ratsam über den Wechsel z.B. zu einem Tinkerboard mit eMMC oder die Nutzung einer externen SSD nachzudenken oder noch besser gleich auf ein voll virtuelles OVA System zu setzen das seine Daten nicht auf einer SD Karte ablegt.

> Raspberrymatic schreibt /etc/config/homematic.regadom viel zu häufig auf die SD-Karte. Die Datei ist bei mir 2.6 MB groß und wird bei meiner Docker-basierten Installation alle 30 Sekunden auf die SD-Karte geschrieben. Das sind 7.5 GB/Tag und im 24/7 Betrieb zu viele Schreibzugriffe für jede SD-Karte. Bei mir ist bereits eine SD-Karte vermutlich dadurch defekt geworden. [Issue 1183](https://github.com/jens-maus/RaspberryMatic/issues/1183) könnte auch damit zusammenhängen.

Eigentlich sollte die `ReGaHss` nur in gewissen Abständen (oder wenn sie dazu manuell genötigt wird) die regadom Datei neu schreiben (Bei Änderungen alle 10 Minuten und alle 12 Stunden eine erzwungene Speicherung). Es findet hier (genau aus den von dir genannten Gründen) ein internes Caching statt und zumindest in der Vergangenheit war es immer so, das die regadom Datei von ReGaHss selbst nur in diesen Abständen wirklich auf den Datenträger geschrieben wird und daher ein externen cacheing (wie du es als workaround vorstellst) nicht notwendig ist/war.

Nach einer kurzen Recherche in `ReGaHss` und der WebUI konnte ich folgende Situationen ausmachen die eine Speicherung der `homematic.regadom` Datei initiieren:

1. Prüfung alle 10 Minuten auf Änderung -> wenn ja, dann Speicherung (siehe `CheckModifiedCycle` in `/etc/rega.conf`).
2. Erzwungenes Speichern der regadom alle 12 Stunden (siehe `AutoSaveDOMOnExit` in `/etc/rega.conf`)
3. Manuelle Nutzung des `system.Save()` ReGa-Scripting Kommandos.
4. Manuelle Nutzung des `system.ClearSession()` ReGa-Scripting Kommando.
5. Bei Herunterfahren/Beenden von `ReGaHss` via init skript oder `monit`.
6. Bei Nutzung von `/bin/createBackup.sh` oder Backup via WebUI als Methode der Persistierung der Daten vor erstellen des Backups
7. Bei Nutzung der Methode `system.saveObjectModel()` via extern zugänglicher JSON API
8. Bei Wechseln in den Recovery-Modus oder abgesicherten Modus via WebUI
9. Bei Wechseln der SystemLanguage in der WebUI
10. Bei Erzeugen lassen eines neuen HTTP Zertifikates via WebUI
11. Beim starten eines Firmware-Updates via WebUI
12. Beim Ausloggen aus der WebUI bzw. beim Drücken von "Änderungen speichern" in der WebUI.

Aktuell kann ich mir also nicht erklären warum auf deinem System die regadom Datei alle 30 Sekunden geschrieben wird. Das sollte nicht passieren. Ich kann daher nur darauf tippen das hier ggf. eine externe App oder ähnliches diese Speicherung intervallgetrieben via der zugänglichen Remote-APIs auslöst.

Man müsste das also einmal näher analysieren. ggf. könntest du die ReGaHss in INFO Loglevel starten (`-l` Option) und dann sollte sie in `/var/log/messages` eine Ausgabe bringen wenn die regadom geschrieben wird. Und hilfreich wäre dabei auch das auf einer separaten/frischen Installation zu versuchen zu reproduzieren damit ausgeschlossen werden kann das keine externe App dieses erzwungene Schreiben der regadom initiiert.

**Comment by rusitschka** [comment]
Danke für die ausführliche Erklärung. Ich habe nun ReGaHss via ```/bin/ReGaHss -f /etc/rega.conf -l INFO``` gestarted aber es loggt nichts, obwohl die Datei geschrieben wird:
```
Mar 25 10:20:10 raspberrymatic local0.info ReGaHss: Info: wait for event ms= 4294967295 [ThreadFunction():iseRTScheduler.cpp:484]
Mar 25 10:24:00 raspberrymatic local0.debug ReGaHss: Verbose: wait max timeout = 240000 [ThreadFunction():iseRTEvent.cpp:69]
Mar 25 10:24:00 raspberrymatic local0.info ReGaHss: Info: check modified flag [ThreadFunction():iseRTDOM.cpp:88]
Mar 25 10:24:00 raspberrymatic local0.info ReGaHss: Info: wait next cycle, because seconds since last modified = 600 [ThreadFunction():iseRTDOM.cpp:99]
```
Dann kommt nichts mehr.

Aber die Datei wurde um 10:26 geschrieben
```
/ # ls -latr /tmp
...
-rw-r--r--    1 root     root           108 Mar 25 10:26 dutycycle.json
-rw-r--r--    1 root     root       2695593 Mar 25 10:26 homematic.regadom
```

Ich habe keine Scripte in der CCU am laufen sondern mache alles mit Home-Assistant.

Woran kann es liegen, dass die Datei geschrieben wird, ohne dass ReGaHss etwas loggt? Habe ich das Logging noch nicht richtig aktiviert?

**Comment by jens-maus** [comment]
> Danke für die ausführliche Erklärung. Ich habe nun ReGaHss via `/bin/ReGaHss -f /etc/rega.conf -l INFO` gestarted aber es loggt nichts, obwohl die Datei geschrieben wird:

Ok, dann hab ich mich missverständlich ausgedrückt. Meinte nicht das du da "INFO" dahinterschreiben sollst. Das Info-level hat die Nummer 1 (das kannst du mit `ReGaHss -h` sehen). D.h. du musst es mit `-l 1` aufrufen, dann sollte es geloggt werden.

**Comment by rusitschka** [comment]
Ich habe einen protokollierten Schreibvorgang gefunden:
```
Mar 25 10:34:00 raspberrymatic local0.info ReGaHss: Info: check modified flag [ThreadFunction():iseRTDOM.cpp:88]
Mar 25 10:34:00 raspberrymatic local0.info ReGaHss: Info: starting save to = /tmp/homematic.regadom [Save():iseRTDOM.cpp:56]
Mar 25 10:34:00 raspberrymatic local0.debug ReGaHss: Verbose: wait max timeout = 240000 [ThreadFunction():iseRTEvent.cpp:69]                                                                                               Mar 25 10:34:00 raspberrymatic local0.info ReGaHss: Info: open file succeeded, start save [SaveToFile():iseDOMpersist.cpp:265]
Mar 25 10:34:00 raspberrymatic local0.info ReGaHss: Info: start, count=1832 [RemoveUnreferencedObjects():iseDOMobj.cpp:638]
Mar 25 10:34:00 raspberrymatic local0.info ReGaHss: Info: removed 0 unreferenced objects, count=1832 [RemoveUnreferencedObjects():iseDOMobj.cpp:744]
Mar 25 10:34:02 raspberrymatic local0.info ReGaHss: Info: end save [SaveToFile():iseDOMpersist.cpp:271]
Mar 25 10:34:02 raspberrymatic local0.info ReGaHss: Info: end save to file= /tmp/homematic.regadom [SaveToFile():iseDOMpersist.cpp:279]
Mar 25 10:34:02 raspberrymatic local0.info ReGaHss: Info: SaveOM succeeded [Save():iseRTDOM.cpp:64]
```

Aber das ist der einzige bisher und die Datei wird nach wie vor alle 30 Sekunden neu geschrieben.

**Comment by jens-maus** [comment]
> Ich habe einen protokollierten Schreibvorgang gefunden:
> 
> [...]
> 
> Aber das ist der einzige bisher und die Datei wird nach wie vor alle 30 Sekunden neu geschrieben.

Kann dann aber nicht sein :) D.h. es muss dann jemand anders sein der dir die Datei dort neu schreibt oder aktualisiert.

**Comment by jens-maus** [comment]
Und auch auf dem Home Assistant Testsystem das ich am laufen habe sehe ich, das die Datei das letzte mal um 00:21 heute nacht aktualisiert wurde:

```
root@e4704d1b-raspberrymatic:~# ls -la /etc/config/homematic.regadom
-rw-r--r--    1 root     root        405356 Mar 25 00:21 /etc/config/homematic.regadom
```

**Comment by rusitschka** [comment]
Es lieft vermutlich noch ein ReGaHss mit -l 2. Nun habe ich folgendes gefunden:
```
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: start web processing, worker thread #0 {"HTTP-Listener"} [spawnNewProcess():httpListener.cpp:208]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: recvd 336 bytes by web server #1 [ThreadFunction():httpServer.cpp:797]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: IseSession GetSessionId from URL: /login.htm [GetSessionId():iseSession.cpp:185]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: IseSession Created: id: xxx Request URL: /login.htm [GetFreeSession():iseSession.cpp:127]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: start web processing, worker thread #0 {"HTTP-Listener"} [spawnNewProcess():httpListener.cpp:208]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: recvd 326 bytes by web server #1 [ThreadFunction():httpServer.cpp:797]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: IseSession GetSessionId from URL: /tclrega.exe [GetSessionId():iseSession.cpp:185]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: http id #1 sends parsed file [ParseFileAndSendWebResponse():httpServer.cpp:2079]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: start web processing, worker thread #0 {"HTTP-Listener"} [spawnNewProcess():httpListener.cpp:208]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: recvd 1356 bytes by web server #1 [ThreadFunction():httpServer.cpp:797]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: IseSession GetSessionId from URL: /tclrega.exe [GetSessionId():iseSession.cpp:185]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'UNIT' does not exist [GetUnitProperty():iseDOMdp.cpp:392]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'VALUE_LIST' does not exist [GetValueListProperty():iseDOMdp.cpp:425]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'BV0' does not exist [GetBinValueName0():iseDOMdp.cpp:458]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'BV1' does not exist [GetBinValueName1():iseDOMdp.cpp:495]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'MIN' does not exist [GetMinProperty():iseDOMdp.cpp:326]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'MAX' does not exist [GetMaxProperty():iseDOMdp.cpp:359]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'VALUE_LIST' does not exist [GetValueListProperty():iseDOMdp.cpp:425]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'BV0' does not exist [GetBinValueName0():iseDOMdp.cpp:458]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'BV1' does not exist [GetBinValueName1():iseDOMdp.cpp:495]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'MIN' does not exist [GetMinProperty():iseDOMdp.cpp:326]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'MAX' does not exist [GetMaxProperty():iseDOMdp.cpp:359]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'VALUE_LIST' does not exist [GetValueListProperty():iseDOMdp.cpp:425]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'UNIT' does not exist [GetUnitProperty():iseDOMdp.cpp:392]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'VALUE_LIST' does not exist [GetValueListProperty():iseDOMdp.cpp:425]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'BV0' does not exist [GetBinValueName0():iseDOMdp.cpp:458]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'BV1' does not exist [GetBinValueName1():iseDOMdp.cpp:495]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'UNIT' does not exist [GetUnitProperty():iseDOMdp.cpp:392]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'VALUE_LIST' does not exist [GetValueListProperty():iseDOMdp.cpp:425]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'BV0' does not exist [GetBinValueName0():iseDOMdp.cpp:458]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'BV1' does not exist [GetBinValueName1():iseDOMdp.cpp:495]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'UNIT' does not exist [GetUnitProperty():iseDOMdp.cpp:392]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'VALUE_LIST' does not exist [GetValueListProperty():iseDOMdp.cpp:425]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'BV0' does not exist [GetBinValueName0():iseDOMdp.cpp:458]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'BV1' does not exist [GetBinValueName1():iseDOMdp.cpp:495]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'MIN' does not exist [GetMinProperty():iseDOMdp.cpp:326]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'MAX' does not exist [GetMaxProperty():iseDOMdp.cpp:359]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: metadata property 'VALUE_LIST' does not exist [GetValueListProperty():iseDOMdp.cpp:425]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: http id #1 sends parsed file [ParseFileAndSendWebResponse():httpServer.cpp:2079]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: start web processing, worker thread #0 {"HTTP-Listener"} [spawnNewProcess():httpListener.cpp:208]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: recvd 117 bytes by web server #1 [ThreadFunction():httpServer.cpp:797]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: IseSession GetSessionId from URL: /tclrega.exe [GetSessionId():iseSession.cpp:185]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: open file succeeded, start save [SaveToFile():iseDOMpersist.cpp:265]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: start, count=1832 [RemoveUnreferencedObjects():iseDOMobj.cpp:638]
Mar 25 11:11:05 raspberrymatic local0.info ReGaHss: Info: removed 0 unreferenced objects, count=1832 [RemoveUnreferencedObjects():iseDOMobj.cpp:744]
Mar 25 11:11:07 raspberrymatic local0.info ReGaHss: Info: end save [SaveToFile():iseDOMpersist.cpp:271]
Mar 25 11:11:07 raspberrymatic local0.info ReGaHss: Info: end save to file= /etc/config/homematic.regadom.new [SaveToFile():iseDOMpersist.cpp:279]
Mar 25 11:11:07 raspberrymatic local0.info ReGaHss: Info: saved new file. [SaveOM():iseDOM.cpp:2495]
Mar 25 11:11:07 raspberrymatic local0.info ReGaHss: Info: rename file to bak. [SaveOM():iseDOM.cpp:2516]
Mar 25 11:11:07 raspberrymatic local0.info ReGaHss: Info: rename new file to original. [SaveOM():iseDOM.cpp:2522]
Mar 25 11:11:07 raspberrymatic local0.info ReGaHss: Info: http id #1 sends parsed file [ParseFileAndSendWebResponse():httpServer.cpp:2079]
```

**Comment by rusitschka** [comment]
Ich sehe gerade im Log: Wer ruft da eine .exe-Datei über HTTP auf? ```tclrega.exe```?

**Comment by jens-maus** [comment]
@rusitschka Das wäre die Frage. Das kannst nur du lokal rausfinden. Auch müsstest du in dem Logfile mal schauen ob auch das `SaveOM()` wirklich alle 30 sekunden aufgerufen wird und damit er wirklich alle 30 Sekunden die Datei wegschreibt.

**Comment by rusitschka** [comment]
SaveOM passiert alle 30-60 Sekunden:
```
/ # tail -F /var/log/messages |grep SaveOM
Mar 25 17:58:07 raspberrymatic local0.info ReGaHss: Info: saved new file. [SaveOM():iseDOM.cpp:2495]
Mar 25 17:58:07 raspberrymatic local0.info ReGaHss: Info: rename file to bak. [SaveOM():iseDOM.cpp:2516]
Mar 25 17:58:07 raspberrymatic local0.info ReGaHss: Info: rename new file to original. [SaveOM():iseDOM.cpp:2522]
Mar 25 17:58:43 raspberrymatic local0.info ReGaHss: Info: saved new file. [SaveOM():iseDOM.cpp:2495]
Mar 25 17:58:43 raspberrymatic local0.info ReGaHss: Info: rename file to bak. [SaveOM():iseDOM.cpp:2516]
Mar 25 17:58:43 raspberrymatic local0.info ReGaHss: Info: rename new file to original. [SaveOM():iseDOM.cpp:2522]
Mar 25 17:59:13 raspberrymatic local0.info ReGaHss: Info: saved new file. [SaveOM():iseDOM.cpp:2495]
Mar 25 17:59:13 raspberrymatic local0.info ReGaHss: Info: rename file to bak. [SaveOM():iseDOM.cpp:2516]
Mar 25 17:59:13 raspberrymatic local0.info ReGaHss: Info: rename new file to original. [SaveOM():iseDOM.cpp:2522]
Mar 25 18:00:13 raspberrymatic local0.info ReGaHss: Info: saved new file. [SaveOM():iseDOM.cpp:2495]
Mar 25 18:00:13 raspberrymatic local0.info ReGaHss: Info: rename file to bak. [SaveOM():iseDOM.cpp:2516]
Mar 25 18:00:13 raspberrymatic local0.info ReGaHss: Info: rename new file to original. [SaveOM():iseDOM.cpp:2522]
Mar 25 18:01:13 raspberrymatic local0.info ReGaHss: Info: saved new file. [SaveOM():iseDOM.cpp:2495]
Mar 25 18:01:13 raspberrymatic local0.info ReGaHss: Info: rename file to bak. [SaveOM():iseDOM.cpp:2516]
Mar 25 18:01:13 raspberrymatic local0.info ReGaHss: Info: rename new file to original. [SaveOM():iseDOM.cpp:2522]
```

Wenn ich Home-Assistant stoppe, hört der Spuk übrigens auf! Hier der relevante Auszug aus meiner Home-Assistant-Config:
```
homematic:
  local_port: 32001
  interfaces:
    rf:
      host: 192.168.218.5
      callback_ip: 192.168.218.10
      callback_port: 32001
      resolvenames: json
      username: !secret homematic_user
      password: !secret homematic_password
  hosts:
    ccu2:
      host: 192.168.218.5
      username: !secret homematic_user
      password: !secret homematic_password
```

**Comment by jens-maus** [comment]
Dann hast du vmtl irgendeine extern App oder Funktionalität die via RemoteAPI die ReGa dazu nötigt die regadom alle 30-60 Sekunden abzuspeichern. Von ReGaHss alleine passiert das wie gesagt nicht. Musst du also mal rausfinden wer so alles Requests dahin schickt.

**Comment by jens-maus** [comment]
Vielleicht ist es ja sogar die homematic integration in home assistant selbst oder du hast irgendeine automation in home assistant laufen die das auslöst.

**Comment by jens-maus** [comment]
Vielleicht kann @danielperna84 ja bei der Analyse hier weiterhelfen?!?

**Comment by rusitschka** [comment]
tcpdump zeigt mir, dass Home-Assistant alle 30 Sekunden Login,SysVar.getAll,Logout aufruft. Kann es daran liegen?
```
POST /api/homematic.cgi HTTP/1.1
Accept-Encoding: identity
Host: 192.168.218.5:80
User-Agent: Python-urllib/3.8
Content-Type: application/json
Content-Length: 123
Connection: close

{"method": "Session.login", "params": {"username": "homeassistant", "password": "xxx"}, "jsonrpc": "1.1", "id": 0}

HTTP/1.1 200 OK
CONTENT-TYPE: application/json; charset=utf-8
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: no-referrer
Cache-Control: private, no-cache, must-revalidate, no-transform, max-age=0
Transfer-Encoding: chunked
Connection: close



POST /api/homematic.cgi HTTP/1.1
Accept-Encoding: identity
Host: 192.168.218.5:80
User-Agent: Python-urllib/3.8
Content-Type: application/json
Content-Length: 96
Connection: close

{"method": "SysVar.getAll", "params": {"_session_id_": "xxx"}, "jsonrpc": "1.1", "id": 0}

HTTP/1.1 200 OK
CONTENT-TYPE: application/json; charset=utf-8
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: no-referrer
Cache-Control: private, no-cache, must-revalidate, no-transform, max-age=0
Transfer-Encoding: chunked
Connection: close


POST /api/homematic.cgi HTTP/1.1
Accept-Encoding: identity
Host: 192.168.218.5:80
User-Agent: Python-urllib/3.8
Content-Type: application/json
Content-Length: 97
Connection: close

{"method": "Session.logout", "params": {"_session_id_": "xxx"}, "jsonrpc": "1.1", "id": 0}

HTTP/1.1 200 OK
CONTENT-TYPE: application/json; charset=utf-8
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: no-referrer
Cache-Control: private, no-cache, must-revalidate, no-transform, max-age=0
Transfer-Encoding: chunked
Connection: close
```

**Comment by danielperna84** [comment]
Ja, das müsste das pollen der Variablen sein. Das passiert hier: https://github.com/danielperna84/pyhomematic/blob/b771ab8a0022ea4e6011fe433860a2b260a44891/pyhomematic/_hm.py#L815

**Comment by rusitschka** [comment]
> 12. Beim Ausloggen aus der WebUI bzw. beim Drücken von "Änderungen speichern" in der WebUI.
Ist es der logout?

**Comment by danielperna84** [comment]
Für die Ineffizient gibt's übrigens schon lange ein Issue: https://github.com/danielperna84/pyhomematic/issues/36

Aber meine Frage nach Hilfe ist bisher niemand nachgekommen. Vielleicht ändert sich das ja jetzt wo dieser Ansatz ein Problem darstellt. 😈

**Comment by jens-maus** [comment]
Nun, die Frage war ja eher warum und wie (wenn es an pyhomematic liegt) kommt es zu diesen regelmäßigen Schreiboperationen der regadom? Du schreibst in deinem Ticket ja etwas davon das du dich einloggen/ausloggen musst. Das alleine aber sollte ja keine Schreiboperation der regadom auslösen wie ich oben dargelegt habe...

**Comment by jens-maus** [comment]
... d.h. Ein Session.logout() sollte eigentlich bicht die Rega dazu bringen eine Schreiboperation zu machen.

**Comment by danielperna84** [comment]
Also pyhomematic holt sich die Daten von `http://...:80/api/homematic.cgi`. Damit das funktioniert braucht man einen User der ins UI kommt. Muss aber kein Admin sein (glaube ich, spielt für das Problem aber auch keine Rolle denke ich). Und als eben jener User wird sich alle 30 Sekunden ein- und ausgeloggt. Ob diese JSON-RPC API zum ReGa _zeigt_ weiß ich nicht (habe mich nie wirklich mit ReGa beschäftigt).

Ich kann aber bestätigen, dass auch bei mir die Datei alle 30 Sekunden neu geschrieben wird. Hab' die Variablen nun schon aus der Config in HA auskommentiert, kann aber wegen der anderen Bewohner im Haus gerade nicht neu starten. 😅

Auf jeden Fall aber eine super Beobachtung @rusitschka ! 👍 Wäre mir nie aufgefallen.

**Comment by rusitschka** [comment]
Ich habe gerade Zeile 796 in _hm.py von pyhomematic auskommentiert und nun wird die Datei nicht mehr geschrieben. Es ist definitiv der Logout.
```
#self.jsonRpcLogout(remote, session)
```

**Comment by jens-maus** [comment]
In der Tat eine interessante Beobachtung! Dann haben wir ja nun den Auslöser für die Schreiboperationen gefunden.

@danielperna84 kannst du mir bitte mal ein kurzen beispielskript liefern der das Verhalten nachstellt, dann kann ich mir anschauen ob ich das nachstellen und innerhalb der WebUI dann Verbesserungen vornehmen kann der diese Schreiboperationen verhindert. Das wäre super.

**Comment by danielperna84** [comment]
@jens-maus 

Bin gerade nicht mehr am PC. Aber probier' mal das hier: https://gist.github.com/danielperna84/e252a54f3f871bde7faa2726dda4dcdf

**Comment by jens-maus** [comment]
Ok, ich denke ich hab es. Du nutzt ja die `session.Logout()` JSON RPC Methode für den Logout und diese nutzt intern unter RaspberryMatic die `system.ClearSession()` ReGa Methode. Allerdings unter der Standard WebUI wird hier die `system.ClearSessionID()` Method verwendet und diese macht im Grunde das selbe, nur speichert sie eben die `homematic.regadom` vorher nicht ab (siehe https://github.com/eq-3/occu/blob/master/WebUI/www/api/methods/session/logout.tcl#L12) und das wohl (wie man hier sieht) aus gutem Grund. 

Reingekommen ist diese Änderung in RaspberryMatic im Zuge eines vermeintlichen Bugfixes in der WebUI (siehe https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0060-WebUI-Fix-SessionLogoutSave.patch). Nun muss ich mir das mal genauer anschauen wieso ich das damals von `ClearSessionID()` zu `ClearSession()` geändert habe. Aber auslösender Punkt wird genau das hier sein. Insofern ist das dann doch wohl meine Aufgabe hier etwas zu verbessern - und natürlich könnte in der Tat pyhomematic trotzdem nicht so offensiv mit den Sessions umgehen ;)

**Comment by jens-maus** [comment]
Ok, now I integrated a changes that reverts using `system.ClearSession()` rather than `system.ClearSessionID()` for the public JSON RPC API. So the next nightly snapshot should contain the change so that a `Session.logout()` JSON RPC call won't automatically save the regadom file but respects the corresponding caching intervals.

If you guys want to test it before the nightly snapshot simply change the `/www/api/methods/session/logout.tcl` file in your RaspberryMatic installation to use `system.ClearSessionID()` rather than `system.ClearSession()`.

And please report back if this indeed fixes the issue.

**Comment by danielperna84** [comment]
> If you guys want to test it before the nightly snapshot simply change the `/www/api/methods/session/logout.tcl` file in your RaspberryMatic installation to use `system.ClearSessionID()` rather than `system.ClearSession()`.

Since I only have my production System: is it safe to remount `/` to `rw` during runtime and edit the file in place? And does this require some sort of restart?

Apart from that, `vi` displays the file with DOS linebreaks (I'm still on an old rpi-matic version, this might have changed with an update I guess). Is this how it should be? Here's what it looks like:  

```
##^M
# Session.close^M
# Schliet eine Sitzung^M
#^M
# Parameter:^M
#   _session_id_: [string] Id des Session^M
#^M
# Rckgabewert: [bool]^M
#   true^M
##^M
^M
hmscript {system.ClearSession(_session_id_);} args^M
^M
jsonrpc_response true^M
```

I have seen code commited with the _wrong_ linebreaks unintentionally before in other projects, I thought I might mention it.

**Comment by rusitschka** [comment]
I'm running ghcr.io/jens-maus/raspberrymatic:3.57.4.20210326-e66b34e now and it solves the issue. My work-around is no longer required. **Thank you very much**, @jens-maus and @danielperna84 :-)

**Comment by jens-maus** [comment]
@rusitschka Great news and thanks again that you brought it up initially. It really helped to find the root cause of the regular write operations and probably a lot of other people using pyhomematic or the homematic integration of home assistant together with RaspberryMatic were hit by the same thing. So thanks again.
