### ISSUE TITLE
Bewegungsmelder ignorieren Einstellungen

### ISSUE THREAD

**Issue by theimo1221** [jens-maus/RaspberryMatic#1195]
**Describe the bug**
Meine Bewegungsmelder legen Zeiten regelmäßig scheinbar so aus wie sie wollen.

**Kontext:**
Ich nutze die Bewegungsmelder mittels ioBroker (rpc) in meiner eigenen HomeAutomation (NodeJS über Socket.io an ioBroker).
Falls Bewegungsmelder 10 Minuten keinen neuen Wert melden, interpretiere ich es lokal, als hätten sie sich selber zurückgesetzt.
Dies war eine Vorsichtsmaßnahme, nachdem sich sporadisch Bewegungsmelder selber nicht mehr gemeldet haben, dass nun die Bewegung wieder zu Ende ist.

Vermehrt tritt dieses Verhalten auf, wenn ein Bewegungsmelder vor Ablauf der Zurücksetzzeit erneut auslöst.

**Gegenbeispiel**
`I20210327-23:09:59.999(1)? Neuer Bewegunsstatus Wert für "Bewegungsmelder Treppenaufgang Oben": true`
...
`I20210327-23:14:58.601(1)? Neuer Bewegunsstatus Wert für "Bewegungsmelder Treppenaufgang Oben": false`

**Steps to reproduce the behavior**
1. Bewegungsmelder mit Einstellung `Mindestsendeabstand  = 2 Minuten; Zurücksetzen der Bewegung = 4 Minuten` betreiben
2. Eine Bewegung registrieren lassen
3. Differenzen der "Zurücksetz Zeit" festtellen

**Expected behavior**
Bewegungsmelder hält sich exakt an die vorgegebenen Zeiten

**Screenshots**
![image](https://user-images.githubusercontent.com/20605452/112736518-a2b8a700-8f53-11eb-9f8f-16567abc03da.png)

![image](https://user-images.githubusercontent.com/20605452/112736905-a1d54480-8f56-11eb-8c6c-cf95d8ad0581.png)

Im Abschnitt oben, sind die Zeiten generell spooky, da die Zweite Meldung nicht mind. 2 Minuten alt ist. 
Anschließend kommt erst nach 4,5 Minuten die erneute Meldung der erneuten Bewegung --> hier hätte ein "Keine Bewegung erkannt" nach 4 Minuten mit anschließendem "Neue Bewegung erkannt" erfolgen müssen

**System information:**
 - RaspberryMatic Version: 3.57.4.20210320
 - Used Hardware: RaspBerry Pi4
 - Used HomeMatic RF-Module: RF USB

**Comment by jens-maus** [comment]
Tut mir leider aber auf dieses Verhalten hat RaspberryMatic selbst keinerlei Einfluss, denn die Bewegungsmeldungen finden völlig autark im Bewegungsmelder selbst statt. RaspberryMatic kann hierbei nur die jeweiligen Parameter (Sendeabstand, Empfindlichkeit, etc.) im Bewegungsmelder einstellen. Die gesamte Bewegungserkennung und Meldelogik passiert im Gerät selber und darauf hat RaspberryMatic keinen Einfluss. D.h. es leitet die Eventmeldungen die vom Bewegungsmelder kommen einfach stumpf dann an die registrierten Schnittstellenprozesse (in deinem Fall ioBroker) weiter.

Und da die Firmware der Bewegungsmelder closed source ist kat RaspberryMatic selbst auf das Auslöseverhalten keinerlei Einfluss.

**Comment by theimo1221** [comment]
Hm....
Die RaspberryMatic, könnte allerdings selber einen Fallback auslösen, wenn das Gerät über die Rücksetzzeit hinaus nicht passend eine erneute Bewegung (oder seine Absenz) meldet, korrekt?

**Comment by jens-maus** [comment]
Inwiefern? Also zumindest wüsste ich nicht wie? Aber vielleicht hat ja @jp112sdl eine Idee dazu oder ich hab das Problem noch nicht ganz durchschaut. Wie gesagt findet die gesamte Auswertung der Bewegung komplett autark im Gerät selbst statt und RM hat darauf (ausser mittels umstellen der Parameter) keinerlei direkten Einfluss.

**Comment by theimo1221** [comment]
Unabhängig von dem falschen/autarken Verhalten des Gerätes selbst, wäre es m.E.n. nicht verkehrt, wenn die Raspberrymatic sagt: "Wenn ich nach einer gemeldeten Bewegung `Rücksetzzeit + x` nichts vom Gerät erhalte, dann gehe ich davon aus, dass die Bewegung aufgehört hat und setze den Wert in der Zentrale sicherheitshalber zurück auf false."

**Comment by jp112sdl** [comment]
> "Wenn ich nach einer gemeldeten Bewegung Rücksetzzeit + x nichts vom Gerät erhalte, dann gehe ich davon aus, dass die Bewegung aufgehört hat und setze den Wert in der Zentrale sicherheitshalber zurück auf false."

Das Problem ist meiner Meinung nach der Schnittstellenprozess. Dieser muss ja der ReGa das Event melden.
Heißt: Bei klassischen BidCos Geräten ist es der RFD, der die Events an die ReGa weiterreicht.
Bei HmIP ist es der HMIPServer Prozess.

So als Brainstorming Gedanke:

Du könntest versuchen, es mit einem Skript zu lösen und das Event faken.
Ich hatte da mal vor langer Zeit von Alchy ein Snippet erhalten, um eine ausgelöste "Batterie leer" Meldung wieder loszuwerden. 
```
string cmd = "/bin/sh -c '" # 'echo "load tclrpc.so; puts [xmlrpc http://127.0.0.1:1999/ event [list string BidCos-RF] [list string "'#sserial#'"] [list string LOWBAT] [list bool "'#bcmd#'"]];" |tclsh'# "'";
```
_Ich weiß aber nicht, ob es reicht, einfach aus BidCos-RF ein HmIP-RF zu machen._

Dann prüfst du zyklisch mit `.LastTimeStamp()` wann sich das Gerät das letzte Mal gemeldet hat und führst das Event-Skript ggf. aus.
