### ISSUE TITLE
HmIP-BDT Wochenprogramm wird nicht gespeichert.

### ISSUE THREAD

**Issue by JK081** [jens-maus/RaspberryMatic#1198]
**Describe the bug**
Nach dem wechsel eines Dimmaktor´s, ist mir aufgefallen, das sich das Wochenprogramm nicht mehr speichern lässt!
Auch nach länger Wartezeit!
Hilfe!!

**Steps to reproduce the behavior**
1. ...
2. ...
3. ...
4. ...

**Expected behavior**
...

**Screenshots**
...
![HmIP_BDT](https://user-images.githubusercontent.com/81523229/112757999-67b68200-8fec-11eb-8234-47913288bb2b.jpg)
![Software_Versionen](https://user-images.githubusercontent.com/81523229/112758028-79982500-8fec-11eb-801c-444f6547d165.jpg)

**System information:**
 - RaspberryMatic Version: 3.57.4.20210320
 - Used Hardware: ELV Raspberry Pi 3
 - Used HomeMatic RF-Module: ...

**Additional context**
...

**Comment by blackbasket** [comment]
Klingt ganz nach #1189

**Comment by jens-maus** [comment]
Klingt nicht nur danach, ist in der Tat ein Duplicate von #1189.
