### ISSUE TITLE
HmIP-BROLL: Keine Änderung von Wochenprogramm bei Rollläden/Jalousien mehr möglich

### ISSUE THREAD

**Issue by StefanS200** [jens-maus/RaspberryMatic#1199]
Wird versucht in der Geräteeinstellungen ein Wochenprogramm zu ändern, werden diese Daten nicht ans Gerät übermittelt. Die Meldung „ Einstellungen werden an Gerät übermittelt“ bleibt dauerhaft am Bildschirm
![7AA9AB69-4801-44B7-93DF-1A6FB0A9AA52](https://user-images.githubusercontent.com/66385918/112769350-d281b080-9020-11eb-8113-7969833b2245.jpeg)

**Comment by jens-maus** [comment]
Duplicate of #1189
