### ISSUE TITLE
2.27.8.20170620: Restore of *sbk-file from 2.27.8.20170501 isn't possible

### ISSUE THREAD

**Issue by Eckart0** [jens-maus/RaspberryMatic#120]
I have stored a backup of a well working Homematic configuration from RaspberryMatic 2.27.8.20170501.
It is possible to restore this file again to a bare RaspberryMatic 2.27.8.20170501 sd-card, but not to a bare RaspberryMatic 2.27.8.20170620 sd-card. No failure massage, restore seems to work, RM  reboots, but without my backuped configruation. 
Cf. [https://homematic-forum.de/forum/viewtopic.php?f=65&t=37694&p=369282#p369282](url)
Eckart0

**Comment by jens-maus** [comment]
Is it possible that you provide your backup file for debugging purposes? This would help to debug the potential problem and find a way to work around it. If possible please send me your sbk file in private mail or provide a path that I can access/download it somewhere.

**Comment by Eckart0** [comment]
I deliver my backup-file via Dropbox: https://www.dropbox.com/s/dunnc4v25zmq6o1/170626%20homematic-ccu2-2.27.8.20170501-2017-06-26-2310.sbk?dl=0

Hardware: RPi3. No security key set. Do you need the ssh-password?

Regards, Eckart

 

 

Von: Jens Maus [mailto:notifications@github.com] 
Gesendet: Dienstag, 27. Juni 2017 00:07
An: jens-maus/RaspberryMatic <RaspberryMatic@noreply.github.com>
Cc: Eckart0 <severing.eckart@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [jens-maus/RaspberryMatic] 2.27.8.20170620: Restore of *sbk-file from 2.27.8.20170501 isn't possible (#120)

 

Is it possible that you provide your backup file for debugging purposes? This would help to debug the potential problem and find a way to work around it. If possible please send me your sbk file in private mail or provide a path that I can access/download it somewhere.

**Comment by Eckart0** [comment]
… an I attach the syslog-file of the boot procedure of my working …20170501 configuration.

 

Von: Jens Maus [mailto:notifications@github.com] 
Gesendet: Dienstag, 27. Juni 2017 00:07
An: jens-maus/RaspberryMatic <RaspberryMatic@noreply.github.com>
Cc: Eckart0 <severing.eckart@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [jens-maus/RaspberryMatic] 2.27.8.20170620: Restore of *sbk-file from 2.27.8.20170501 isn't possible (#120)

 

Is it possible that you provide your backup file for debugging purposes? This would help to debug the potential problem and find a way to work around it. If possible please send me your sbk file in private mail or provide a path that I can access/download it somewhere.

**Comment by jens-maus** [comment]
Thanks again for the backup file. I tested it here but (of course) it worked for me out-of-the-box. Please explain which browser you are using and which RaspberryPi you use.

**Comment by Eckart0** [comment]
I use Chrome (browser cache empty) and RPi3. EckartS

**Comment by Eckart0** [comment]
Ok, 

now i tried IE as browser (cache empty): no restore poosible. No failure massage in WebUI, but no restore.

Then I used a direkt restore on the RasPi, as you described it [https://homematic-forum.de/forum/viewtopic.php?f=65&t=37728](url). That worked with the first reboot. The resored file seemed to work, just HmIP and VirualDevices stopped after using WebUI. tbd later.
But: The following reboots produced on the RasPi a file system failure message: 
"Ext4-fs error (device mmcblk0p3): ext4_mb_generate_buddy:758: group 1, block bitmap and by descriptor inconsistent: 23339 vs 2355 clusters" 
WebUI is frozen showing the bluescreen "Die RaspberryMatic ist noch nicht bereit ..."

You succeded in restoring my backup-file on v...20170620. Is it possible that you send my a link to access an image file of that restore? Just to exclude that there is any other problem, i.e. with my hardware?

Regards, EckartS

**Comment by jens-maus** [comment]
@Eckart0 The filesystem error you are seeing suggests that you should exchange your SD card to make sure it is not near end-of-life and thus produce these errors. This would then also explain your problem with the webui-based upload process. So please use a brand-new SD card and don't use a cheap one either :)

**Comment by Eckart0** [comment]
That was the crux of the matter. I tried two cheap 4GB SD-Cards. Now it works with to expensive 8GB cards. Sorry for the circumstancies and thanks for the advice. Eckart0

**Comment by jens-maus** [comment]
Ok thanks. Never use cheap sd cards with the raspberrypi. Always use high grade sandisk or kingston cards
