### ISSUE TITLE
Problem beim Update von Version 3.53.30.20201024

### ISSUE THREAD

**Issue by tampara** [jens-maus/RaspberryMatic#1200]
Guten Morgen,

folgende Situation ist hier gegeben:
- Raspberry PI 3 mit 128 GB MicroSD Karte
- HM-MOD-RPI-PCB
- RaspberryMatic Version 3.53.30.20201024

Ein Upgrade auf Version 3.57.4.20210320 via Web-Interface lässt sich normal installieren. Nach einem Neustart fährt der Pi allerdings nicht mehr hoch (circa 2 Stunden gewartet).

Eine frische MicroSD-Karte mit dem RaspberryMatic-Image 3.57.4.20210320 lässt den Pi auch nicht starten. Die LED leuchtet nur rot, keine weitern Aktivitäten ersichtbar. Auch das LAN-Interface startet am Pi nicht (keine LEDs sichtbar). 

Nur mit der Version 3.53.30.20201024 startet das Pi einwandfrei - inkl. LAN-Interface.

Liegt hier der Fehler zwischen den Ohren bzw. könnt ihr mich unterstützen?

Vielen Dank für eure Hilfe.
Stefan

**Comment by jens-maus** [comment]
Sorry, but this is no support or discussion fora here. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. This was also already mentioned in the ticket template!
___
Tut mir leid, aber das hier ist kein Supportforum, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen.  Dies stand übrigens auch so im Ticket Template!
