### ISSUE TITLE
Cronjobs für BadBlocksCheck und FSTrim auf andere Zeitpunkte festlegen

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1204]
**Is your feature request related to a problem? Please describe.**
Angeregt durch einen Verbesserungsvorschlag im Homematic-Forum ( [Link](https://homematic-forum.de/forum/viewtopic.php?f=65&t=41974&start=460#p654280) ) und um möglichen "Interferenzen" mit der zwei mal im Jahr stattfindenden Zeitumstellung aus dem Weg zu gehen wäre es vielleicht sinnvoll die Ausführungszeitpunkte der beiden Cronjobs (BadBlocksCheck & FSTrim) anzupassen.

**Describe the solution you'd like**
Der BadBlocksCheck sollte frühestens 03:15 starten so das sichergestellt ist das die Systemzeit korrekt gesetzt wurde (passiert alle 11 Minuten) und sich der Zeitpunkt außerhalb des Zeitumstellungsbereiches befindet. 
Da der BadblocksCheck je nach Größe der eingesetzten SD Karte auch eine Stunde oder mehr aktiv sein kann würde ich FSTrim
dann auf 04:45 setzen. 

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by jens-maus** [comment]
Also erst einmal müsste definitiv bestätigt werden das die aktuellen Uhrzeiten 02:00 und 03:00 für die beiden Checks ein Problem darstellen. Denn es kommt auf die konkrete cron daemon Implementierung an ob das ein problem darstellt oder nicht. Wurde das denn überhaupt bereits getestet und mit Beispielausgaben belegt das ein cronjob der für 02:00/03:00 Uhr terminiert ist nicht, oder doppelt stattfindet an der Zeit der Zeitumstellung?

Und woher kommt die Annahme das die Systemzeit alle 11 Minuten synchronisiert wird? Das sollte nicht der Fall sein, denn das Umschalten auf Sommer/Winterzeit ist vollkommen unabhängig von irgendwelchen NTP Servern. Und das was da im cronjob mit `*/11'  hinterlegt ist ist ja lediglich die synchronisation der aktuellen Systemzeit in die jeweilige hardware RTC und hat nichts mit irgendwelchen Zeitumstellungen zu tun.

**Comment by Baxxy13** [comment]
> Wurde das denn überhaupt bereits getestet und mit Beispielausgaben belegt

Soweit ich das gelesen habe, nein. 




> Und woher kommt die Annahme das die Systemzeit alle 11 Minuten synchronisiert wird?

Durch eine, durch Dich jetzt widerlegte, Annahme meinerseits. Ich hatte das so interpretiert das die RTC alle 11 Minuten "synchronisiert" wird und das System die Zeit aus der RTC bezieht.

Na dann hoffen wir mal das der "Wünscher" mit Fakten rüberkommt. Ich selbst kann keine liefern da meine System von SSD laufen und alle Checks deaktiviert sind.

**Comment by Baxxy13** [comment]
Da unser "Wünscher" momentan auch keine weiteren Fakten liefern kann bleibt erstmal nur seine Aussage...


> Ich kann aber recht sicher sagen, dass der Bad Block Check bei der Sommerzeitumstellung nicht gelaufen ist

sowie ein Screenshot des Temperaturverlauf's der CPU. Auf diesem sieht man das in der Zeitumstellungs-Nacht kein Temperaturanstieg zu verzeichnen ist und somit davon ausgegangen werden kann das der BB-Check nicht lief. 
[Link zum Screenshot](https://homematic-forum.de/forum/download/file.php?id=86684&mode=view)

Ich habe noch ein wenig zum Thema recherchiert. 
Die Informationen die ich fand "passen" aber nicht so recht zum gezeigten Verhalten.
Ich deute die Info aus [cron(8) - Linux man page](https://linux.die.net/man/8/cron)
>If time has moved forward, those jobs that would have run in the interval that has been skipped will be run immediately.

eher so das der Job dann direkt nach der Zeitumstellung hätte loslaufen müssen.

Zur Winterzeitumstellung sollte es keine Probleme geben...
>Conversely, if time has moved backward, care is taken to avoid running jobs twice.

Weitere Infos ([Link](http://linux-club.de/wiki/opensuse/Sommerzeit_vs_cron))
```
Zeitsprünge kleiner 3 Stunden 
Es kommt eine spezielle Logik zu tragen

beim zurückstellen der Uhr werden cronjobs nicht noch einmal gestartet
beim vorstellen der Uhr werden übersprungene Cronjobs nachgeholt
dabei werden aber nur Jobs berücksichtigt die eine Startfrequenz größer als 1 Stunde haben.

```

Kommentar: 
([Link](https://www.tralios.de/2016/10/30/zeitumstellung/))
`Problematisch ist aber z.B. die Umstellung von Winter- auf Sommerzeit, bei der alle Jobs, die normalerweise zwischen 2 und 3 Uhr nacheinander gestartet wären, schlagartig um 3 Uhr loslaufen. Ein guter Admin sollte daher nach Möglichkeit nie Cronjobs auf eine Zeit zwischen 2 und 3 Uhr nachts legen, um solche Probleme von vorneherein zu vermeiden.`

Bezieht sich aber auf den Bereich zwischen 02:00 und 03:00.

Zu Jobs die direkt um 02:00 oder um 03:00 laufen konnte ich keine verwertbaren Informationen finden.

**Comment by blackbasket** [comment]
Also von der CPU usage her, kann ich das bestätigen. In der Nacht von So fehlt der Peak.

**Comment by jens-maus** [comment]
Kann das mal jemand nachstellen? Einfach mal einen RaspberryPi mit RaspberryMatic hernehmen, NTP abschalten und die Uhrzeit fest auf den Tag/Uhrzeit unmittelbar vor der Zeitumstellung stellen, dann beobachten was passiert und ggf für den test extra cronjibs einrichten die nur in ein file in /tmp etwas loggen oder so...

**Comment by blackbasket** [comment]
Ich hab leider aktuell keine Testhardware zur Hand...

**Comment by Baxxy13** [comment]
> NTP abschalten

Da bräuchte ich Hilfe... den Rest bekomme ich hin.

**Comment by Baxxy13** [comment]
Danke, ich hatte im Monit nach irgendwas mit NTP gesucht.
Cronjobs angelegt, sollte reichen.
```
0 3 * * 0 /usr/bin/logger -t System -p user.info "Zeitumstellung Test - Cronjob FSTrim gestartet" >/dev/null 2>/dev/null
0 2 * * * /usr/bin/logger -t System -p user.info "Zeitumstellung Test - Cronjob BB-Check gestartet" >/dev/null 2>/dev/null
```

**Comment by jens-maus** [comment]
Sollte grundsätzlich reiche. Nur beachten das der erste um `0 3 * * 0` aber nur sonntags ausgeführt wird. Sollte aber für die Zeitumstellung passen. Damit solltest du dann beide Zeitpunkte der DST Umstellung testen können, ja.

**Comment by Baxxy13** [comment]
Umstellung auf Sommerzeit (hatte crond vorsichtshalber noch schnell neu getartet)
```
Mar 28 01:58:10 homematic-raspi user.info monit[1194]: 'crond' restart: '/etc/init.d/S98crond restart'
Mar 28 01:58:12 homematic-raspi user.info monit[1194]: 'crond' process is running with pid 27824
Mar 28 01:58:27 homematic-raspi user.err monit[1194]: 'crond' service restarted 1 times within 1 cycles(s) - exec
Mar 28 01:58:27 homematic-raspi user.info monit[1194]: 'crond' exec: '/bin/triggerAlarm.tcl crond restarted WatchDog-Alarm'
Mar 28 01:58:27 homematic-raspi user.info monit[1194]: 'crond' process is running after previous restart timeout (manually recovered?)
Mar 28 03:00:00 homematic-raspi user.info System: Zeitumstellung Test - Cronjob FSTrim gestartet
```

Umstellung auf Winterzeit:
`Oct 31 03:00:00 homematic-raspi user.info System: Zeitumstellung Test - Cronjob FSTrim gestartet`

Kein BB-Check, interessant. Die beiden NoXXX-Dateien sind nicht im Testsystem.

**Comment by jens-maus** [comment]
Ok danke. Meine Idee wäre dann wie folgt:

1. Verschieben des FSTrim cronjob von 03:00 Sonntag auf 03:00 Samstag (Zeitumstellungen sind immer Sonntag nacht)
2. Umstellen des BB-Checks von 02:00 auf 01:59.

Dies sollte meines Erachtens dann dafür sorgen das (1) nicht beide cronjobs parallel ablaufen können (weil fstrim nur samstags läuft) und (2) der BB-Check auch bei der Zeitumstellung dann berücksichtig wird.

Das könntest du ja beides dann bitte mal durchspielen an deinem Testsystem.

**Comment by Baxxy13** [comment]
So dann, oder?
```
59 1 * * * /usr/bin/logger -t System -p user.info "Zeitumstellung Test - Cronjob BB-Check gestartet" >/dev/null 2>/dev/null
0 3 * * 6 /usr/bin/logger -t System -p user.info "Zeitumstellung Test - Cronjob FSTrim gestartet" >/dev/null 2>/dev/null
```
Blieb dann noch das "mögliche Problem" das Samstags der BB-Check bei großen SD-Karten (>64GB) länger als eine Stunde braucht und noch läuft wenn FSTrim gestartet wird.

**Comment by jens-maus** [comment]
Ja, so könnte das gehen. Könnten natürlich auch den fstrim auf 04:00 Uhr setzen um da noch etwas luft zu geben, ja.
