### ISSUE TITLE
Reboot von Raspberrymatic schlägt fehlt, wenn LAN-Gateway nicht erreichbar ist.

### ISSUE THREAD

**Issue by Bockhorn-IT** [jens-maus/RaspberryMatic#1211]
**Describe the bug**
...

**Steps to reproduce the behavior**
1. Create a Lan Gateway, which is not reachable
2. Shutdown Raspberrymatic
3. Start Raspberrymatic
4. rfd Damon fails to start correctly

**Steps to reproduce the behavior**
1. Create a Lan Gateway, which is not reachable
2. Create backup
3. Reset Raspberrymatic
4. Restore Backup
5. rfd Damon fails to start correctly

**Expected behavior**
Reboot oder Einspielen eines Backups funktioniert trotz nicht erreichbaren Gateway.

**Screenshots**
```
Apr  1 22:20:02 homematic-ccu2 user.info root: Updating RF Lan Gateway Coprocessor Firmware
Apr  1 22:20:02 homematic-ccu2 user.debug update-coprocessor: firmware filename is: coprocessor_update_hm_only.eq3
Apr  1 22:20:02 homematic-ccu2 user.info root: Updating RF Lan Gateway Firmware
Apr  1 22:20:02 homematic-ccu2 user.info update-lgw-firmware: No gateway found in config file /etc/config/rfd.conf
Apr  1 22:20:37 homematic-ccu2 user.err rfd: LGWPortWrapper::SendData(): Send error
Apr  1 22:20:37 homematic-ccu2 user.err rfd: () CCU2CommController::getDutyCycle(): Could not get DutyCycle from coprocessor.
```

**System information:**
 - RaspberryMatic Version: 3.57.4.20210320
 - Used Hardware: PI 4B 4GB
 - Used HomeMatic RF-Module: HM-MOD-RPI-PCB

**Additional context**
Das Einrichten eines Gateway schlug fehl. Ich dachte er verbindet sich später. Dann lief die Installation mit über 100 Geräten wochenlang. Dann war nach einem Stromausfall, kein Reboot mehr möglich. Keine Version eines Backup ließ sich in eine Neuinstallation erfolgreich einspielen, nach einem Neustart gelang es dem System keine Verbindung zum rfd Damon herzustellen. Jede Funktion in der UI die rfd Daten braucht, hängt sich dann auf, Webseite reagiert nicht mehr. Erst als ich anhand der obigen Logzeilen eine Vermutung zum LAN Gateway herstellte und es schaffte diesen zu löschen, funktionierte das System nach einem Reboot wieder normal.

**Comment by fredster1979** [comment]
Gleiches oder Ähnliches Fehlerbild. Raspberry PI 3B ist über ethernet mit dem Router verbunden. Nach Stromausfall booted der Rasperry schneller als der Router, somit ist das LAN Gateway nicht erreichbar. Anschließend kann ich nicht mehr über das Webinterface zugreifen. Auch nach kurzer wartezeit verbindet sich der Raspberry nicht mit dem Router. 


System information:
    RaspberryMatic Version: 3.57.4.20210320
    Used Hardware: Raspberry Pi 3 B, 
    Used HomeMatic RF-Module: RPI-RF-MOD

**Comment by muellejo1955** [comment]
Ich verwende 2 CCU2 als LanGateways, und habe  gestern die gleiche Problematic wie fredster1979 erlebt. Raspberrymatic läßt sich nicht mehr starten…..(mindestens eine Komponente usw….) Werde das System wohl neu aufsetzen müssen.

System information:
RaspberryMatic Version:  3.57.5.20210525
Used Hardware: Raspberry Pi 3 B,
Used HomeMatic RF-Module: RPI-RF-MOD

**Comment by jens-maus** [comment]
Was heisst denn in dem Kontext „lässt sich nicht mehr starten“ was wird denn beim start von RM mit HDMI Monitor dran ausgegeben und was passiert genau wenn du versuchst zuzugreifen via Webbrowser. Also statt einfach hier alles neu aufzusetzen (ist ja kein windows!) würde es helfen zu verstehen was passiert, dann könnte ich hier einen fix erarbeiten!

**Comment by jens-maus** [comment]
Also ich bekomm das leider hier icht reproduziert. Ich kann hier beliebig viele invalide LAN-Gateways hinzufügen die natürlich dann nicht erreichbar sind beim Start. Trotzdem kommt man in die WebUI dann rein und kann diese normal bedienen. Natürlich geht dann keinerlei BidCos-RF und der Anlernmodus ist weg usw. aber das ist ja vollkommen normal. Was genau ist also hier das problem? Und was genau wird erwartet? Bitte detaillierter beschreiben.

**Comment by Bockhorn-IT** [comment]
Bei mir war das Fehlerbild, dass sich die WebUI aufhängt sobald man auf ein Menü zugreift, das scheinbar auf RF Funktionen zugreift. Es wird dann nach einer Weile der HMIP-Server durch den Watchdog neu gestartet. Dann hängt sich die WebUI wieder auf, sobald man auf ein Menü zugreift, das scheinbar auf RF Funktionen zugreift. Das erinnert mich an die Geschichte mit dem Hunde der dem Koch den Löffel stahl, ok OT :-)
Die Zentrale hat auch ohne Zugriff auf die WebUI nicht funktioniert.

Relevant ist glaube ich, dass die LAN Gateways schon mal funktioniert haben und nicht nur einfach ungültig hinzugefügt wurden. Evtl. muss auch die Kommunikation von einigen Geräten auf diese Gateways eingestellt sein.

Und ich glaube man konnte sich die Geräteliste auch anzeigen lassen, dies war noch kein RF relevantes Menü.

**Comment by jens-maus** [comment]
Nun, das kann schon sein das das dann dazu führt das die WebUI anfängt "zu hängen". Das ist aber leider vollkommen normal und auf dies kann RaspberryMatic schwerlich einen Einfluss nehmen. Wenn es ein BidCos-RF Gerät gibt, aber der rfd daemon eben nicht gestartet werden kann (weil die LAN Gateways nicht erreichbar sind), dann kommt es leider zu diesen "Hängern" und in der folge auch zu fehlermeldungen wie "Eine Komponente funktioniert nicht...". Auch das kann nicht wirklich verhindert werden und ist dem generellen Konzept geschuldet. Aktuell wüsste ich also nicht was ich da verbessern oder fixen sollte. Das Problem ist ja, das der rfd daemon eben laufen muss und dieser beendet sich aber wohl leider wenn kein LAN Gateway erreichbar ist und der rfd daemon ist eben leider einer dieser closed-source Teile in der CCU Software auf die RaspberryMatic keinen Zugriff hat. Folglich wüsste ich wie gesagt nicht wo ich hier ansetzen sollte.

**Comment by Bockhorn-IT** [comment]
Gibt es denn einen Bereich bei EQ3 wo man Fehler für den Closed Source Bereich melden kann? Weil das ein evtl. kaputtes LAN-Gateway (so war es bei mir) eine komplette Installation nach einem Reboot kaputt macht, klingt ja dann doch irgendwie nach Windows.

**Comment by jens-maus** [comment]
> Gibt es denn einen Bereich bei EQ3 wo man Fehler für den Closed Source Bereich melden kann?

Nicht wirklich. Du kannst das entweder im OCCU Github von denen melden - aber die tickets dort bearbeiten/lesen die da nicht wirklich - oder du meldest es offiziell als Bug via deren webseite, aber dann werden sie das bugticket ablehnen sobald du schreibst das du RaspberryMatic nutzt oder die fordern ein Backup von dir und dann werden sie es ablehnen weil sie sehen das du nicht die offizielle CCU3 firmware nutzt oder ein Add-on installiert hast. Ist leider sehr mühselig.

**Comment by TheUntouchable** [comment]
Hallo zusammen,

ich habe ein ganz ähnliches Bild, jedoch habe ich nichts an der Konfig die letzten 6 Monate geändert geschweige denn einen LAN Gateway (wissentlich) konfiguriert und plötzlich läuft der PI nicht mehr.. Während dem Betrieb konnte ich mit Tiny Matic plötzlich keine Daten mehr abgerufen und wurde aufgefordert, die CCU neuzustarten. Anschließend kam der PI nicht mehr hoch.

Beim Reboot wird immer versucht, ein LG Firmware Update durchzuführen. Dieser Status ändert sich auch nicht nach einer Stunde warten..
Lasse ich den PI unverbunden mit dem LAN gehts hier zwar weiter da dieses Update nach einer Zeit auf Error läuft, dann schlägt aber das starten des RFD Dienstes fehl, auch wenn ich davor das LAN Kabel wieder verbinde..

Letztendlich komme ich weder per SSH noch per HTTP auf den PI nach dem der Bootvorgang dann abgeschlossen ist.

Gibts hier vielleicht eine Lösung ohne das ich das System neu aufsetzen muss..?
