### ISSUE TITLE
3.57.4.20210320 RPI-RF-MOD kein anlernen von HMIP Geräten

### ISSUE THREAD

**Issue by boergl** [jens-maus/RaspberryMatic#1212]
Hallo zusammen,

ich habe das Problem, dass ich auf dem neuen Funkmodul RPI-RD-MOD keine HMIP Geräte anlernen kann. (Da ich das System um einen HMIP-DRAP erweitern möchte benötige ich es aber leider. Die Verbindung zum DRAP funktioniert wie gewünscht.) HMRF Geräte habe leider keine zum testen. 

Das Funkmodul ist über eine HB-RF-ETH verbunden. Raspberrymatic läuft unter HyperV (Wobei ich es zuvor auch auf einem Raspberry Pi3B+ auf den GPIO Pins versucht habe).

Ich habe es mit 2 Fabrikneuen und einem alten Aktor (Werkeinstellungen...) versucht. Sowohl online als auch offline.

Hier der Inhalt einiger Files:
**/var hm_mode**
HM_HMIP_ADDRESS='0x1EAA8C'
HM_HMIP_ADDRESS_ACTIVE=''
HM_HMIP_DEV='RPI-RF-MOD'
HM_HMIP_DEVNODE='/dev/raw-uart'
HM_HMIP_DEVTYPE='HB-RF-ETH@10.1.10.162'
HM_HMIP_SERIAL='58A9A70CF4'
HM_HMIP_SGTIN='3014F711A0001F58A9A70CF4'
HM_HMIP_VERSION='4.2.14'
HM_HMRF_ADDRESS='0xFF0CF4'
HM_HMRF_ADDRESS_ACTIVE='0xFF0CF4'
HM_HMRF_DEV='RPI-RF-MOD'
HM_HMRF_DEVNODE='/dev/raw-uart'
HM_HMRF_DEVTYPE='HB-RF-ETH@10.1.10.162'
HM_HMRF_SERIAL='58A9A70CF4'
HM_HMRF_VERSION='4.2.14'
HM_HOST='ova-Microsoft'
HM_LED_GREEN=''
HM_LED_GREEN_MODE1='none'
HM_LED_GREEN_MODE2='heartbeat'
HM_LED_RED=''
HM_LED_RED_MODE1='timer'
HM_LED_RED_MODE2='none'
HM_LED_YELLOW=''
HM_LED_YELLOW_MODE1='none'
HM_LED_YELLOW_MODE2='none'
HM_MODE='NORMAL'
HM_RTC='onboard'

**/var ids**
BidCoS-Address=0xFF0CF4
SerialNumber=58A9A70CF4

**/var board_serial**
58A9A70CF4

**/etc/config ids**
BidCoS-Address=0xFF0CF4
SerialNumber=58A9A70CF4

**HB-RF-ETH Daten**
Firmware: 1.2.9
Seriennummer: F008D1F43FEB
Seriennummer: 58A9A70CF4
Funkadresse (BidCos): 0xFF0CF4
Funkadresse (HmIP): 0xB96DA8
SGTIN: 3014F711A0001F58A9A70CF4

Bitte um unterstützung... Bin am verzweifeln :( 

LG, Michael

**Comment by jens-maus** [comment]
Sorry, but this is no support or discussion fora here. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. This was also already mentioned in the ticket template!
___
Tut mir leid, aber das hier ist kein Supportforum, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen.  Dies stand übrigens auch so im Ticket Template!
