### ISSUE TITLE
Firmware download overview should be sorted

### ISSUE THREAD

**Issue by drose28357** [jens-maus/RaspberryMatic#1215]
**Is your feature request related to a problem? Please describe.**
I logged in to rasperryMatic and look  at "Startseite".
I open the link following "Aktuelle Firmwareversion:" to view the avalibale firmware updates for download.
There is a long list of diffrent devices and device types.
In my case (see atachment) i have 3 devices of the same type "HmIP-FSI16", wich are mixed in rows of other devices. 
And there are **two different devicetypes** who have the **same relase version**.

Problem: i only need one download per device type and it is difficult to keep track of the propper downloads

**Describe the solution you'd like**

do a sort an the first row named "Gerät" / "Device", so that all device types types are shown together  eg. in subsequent rows.

**Describe alternatives you've considered**
Reduce the list für firmware downloading to one row per device type. 
disadvantage: one can not see, which devices still need an update.

**Additional context**
RaspberryMatic-Version:  
Aktuelle Firmwareversion: | 3.57.4.20210320

-- | --

![Firmware-Download-Box_unsortiert_Aufruf](https://user-images.githubusercontent.com/11533286/113550716-d3ec4380-95f3-11eb-9098-8baaf0a4b7da.PNG)
![Firmware-Download-Box_unsortiert](https://user-images.githubusercontent.com/11533286/113550723-d64e9d80-95f3-11eb-8d1c-35f60c84c6e9.PNG)

**Comment by Maik2208** [comment]
```JS
--- /www/webui/webui.js.orig
+++ /www/webui/webui.js
@@ -20568,6 +20568,15 @@
               }
               conInfo("Check firmware version of all devices - number of devices: " + self.devList.length);
               if (self.devList.length > 0) {
+		 function sortorder_devList( a, b ) {
+		   if (a.type == b.type){
+		     return ( a.address < b.address ) ? -1 : 1;
+                 }else{
+                   return ( a.type < b.type ) ? -1 : 1;
+                 }
+               }
+
+                self.devList.sort(sortorder_devList);
                 self.fetchAndSetDeviceVersion();
               }
             });
```
Testbar, in dem die Zeile
`if (devIsUpdatable && fwVersion && (fwVersion != "n/a") && (newFW != curFw)) {` 
temporär durch
`if (devIsUpdatable && fwVersion && (fwVersion != "n/a") && (newFW == curFw)) {` 
ersetzt wird, falls gerade keine Firmwareupdates anliegen

**Comment by Maik2208** [comment]
@jens-maus 
Besteht Interesse, dass ich mal versuche aus dieser Änderung einen Patch und einen PR zu machen?

Falls ja: neuer Patch oder in einen bestehenden integrieren?

**Comment by jens-maus** [comment]
Gerne. Und ja, ein neuer Patch natürlich.

**Comment by Maik2208** [comment]
Man wächst an seinen Herausforderungen :-)

Welche webui.js lege ich als Original in dem Patchordner ab? Die produktive aus dem aktuellen Build oder die originale von EQ3?

**Comment by Maik2208** [comment]
@jens-maus 
Ohje, sorry für das Chaos im PR. Der zweite Fix sollte in einen eigenen PR - nur irgendwie bin ich noch nicht ganz Herr über die Sache... 😰

**Comment by jens-maus** [comment]
PRs sendet man auchc kicht auf dem master branch ein. Für jeden PRs ein eigener branch in deinem fork machen der auf dem master basiert und nichts anderes. Deshalb zieh die PRs erstmal zurück und mach sie neu basierend auf separaten branches in deinem fork und dann gibt es da auch kein Durcheinander

**Comment by Maik2208** [comment]
Gucke ich mir nachher nochmal an...

**Comment by Maik2208** [comment]
Wurde mit PR #1370 gelöst.
