### ISSUE TITLE
Keine Verbindung zur RaspberryMatic nach Internet-Trennung / Neustart FritzBox

### ISSUE THREAD

**Issue by Dozer-hh** [jens-maus/RaspberryMatic#1223]
Seit dem letzten Update auf RaspberryMatic 3.57.4.20210320 habe ich folgendes Problem:
Wenn die Fritzbox die Internetverbindung verliert, z.B. durch Firmware-Update / Verbindungsprobleme / Neustart verliert die HomeMatic Zentrale die Verbindung und baut diese auch nach Wiederherstellung der Internetverbindung / Neustart der FritzBox nicht wieder auf.

Somit ist kein Zugriff auf die Zentrale mehr möglich, weder von außerhalb, noch lokal.
Erst ein kompletter Neustart des Raspberry führt zur erneuten Verbindung.

Mein System:
RaspberryMatic 3.57.4.20210320 auf Raspberry Pi 3 B+
Fritzbox 7490 mit FRITZ!OS 07.24-87448 
(Vorher: FRITZ!OS 07.24-87308)

**Comment by jens-maus** [comment]
Sorry, but this is no support or discussion fora here. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. This was also already mentioned in the ticket template!
___
Tut mir leid, aber das hier ist kein Supportforum, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen.  Dies stand übrigens auch so im Ticket Template!
