### ISSUE TITLE
HmIP-FROLL bearbeiten von Wochenprogrammen nicht möglich

### ISSUE THREAD

**Issue by md-tec** [jens-maus/RaspberryMatic#1230]
**Fehlerbeschreibung**
Bereits bestehende aber auch neue Wochenprogramme lassen sich nicht mehr zu HmIP-FROLL hinzufügen oder bearbeiten. Alle anderen Einstellungen können ohne Probleme angepasst werden und werden auch erfolgreich übertragen. Nach der Anpassung eines Wochenprogrammes erscheint die Meldung das Einstellungen übertragen werden, allerdings verschwindet diese nicht mehr und es wird auch unter dem Ladebalken kein Kanal angezeigt. Die Änderungen werden auch nicht in den Aktor geschrieben.

Die RaspberryMatic wurde bereits zurückgesetzt und neu aufgespielt, hat aber leider nix gebracht. Ein steuern der Aktoren über die RaspberryMatic ist auch problemlos möglich.

**Steps to reproduce the behavior**
1. Unter Geräte HmIP-FROLL Gerät Einstellungen auswählen
2. Kanal 7 Wochenprogramm bearbeiten (Ändern der Zeit oder Einträge hinzufügen/löschen)
3. Mit OK oder Übernehmen an Aktor übertragen

**Expected behavior**
Übertragung der Wochenprogramme an den HmIP-FROLL.

**Screenshots**
![image](https://user-images.githubusercontent.com/50334534/114990642-02420c80-9e99-11eb-8101-0cb24672be36.png)

**System information:**
 - RaspberryMatic Version:  3.57.4.20210320
 - Used Hardware: Raspberry Pi 3b, CCU Charly
 - Used HomeMatic RF-Module: RPI-RF-MOD
- Version HmIP-FROLL 1.8.12

Auf Anfrage bei ELV ob ein Firmware Fehler für die HmIP-FROLL 1.8.12 vorliegt habe ich leider keine Auskunft erhalten, da sie keinen Support für RaspberryMatic Systeme geben.

**Comment by blackbasket** [comment]
Duplicate zu #1189

**Comment by jens-maus** [comment]
Duplicate of #1189
