### ISSUE TITLE
Falsche Aktoren beim Tausch

### ISSUE THREAD

**Issue by Jan-Frankfurt** [jens-maus/RaspberryMatic#1234]
**Describe the bug**
Wenn ich ein neu angelerntes HM-LC-Sw2-FM Modul (2 Schalter/Relais) im Posteingang gegen ein vorhandenes defektes tauschen will, wird mir keines der 5 vorhandenen HM-LC-Sw2-FM Module zum Tausch angeboten sondern stattdessen die einkanalige Version HM-LC-Sw1-FM sowie die ebenfalls einkanaligen Schaltsteckdosen  HM-LC1-Pl.  

**Steps to reproduce the behavior**
1. ...
2. ...
3. ...
4. ...

**Expected behavior**
...

**Screenshots**
...
![Posteingang:neuer Aktor](https://user-images.githubusercontent.com/82943187/115541848-e1662680-a29f-11eb-98cf-2f016ea7ef9d.png)
![Liste der vorhandene n Aktoren](https://user-images.githubusercontent.com/82943187/115541875-eaef8e80-a29f-11eb-9364-c1f15133bdca.png)
![Tauschangebot](https://user-images.githubusercontent.com/82943187/115541888-f0e56f80-a29f-11eb-9778-80069c823911.png)

**System information:**
 - RaspberryMatic Version: ...3.57.4.20210320
 - Used Hardware: ...PI 4B
 - Used HomeMatic RF-Module: ...RPI RF Mod

**Additional context**
...

**Comment by jp112sdl** [comment]
Der neu angelernte Aktor scheint eine (zu) alte Firmware (1.5?) zu haben.
Den kannst du nur gegen einen HM-LC-Sw2-FM mit dem selben Firmwarestand tauschen.

Vorschlag: Lerne den neuen HM-LC-Sw2-FM erstmal ganz normal an und mach ein Firmware-Update (bzw. vergleiche, ob die Firmewareversion mit deinem gewünschtem Tauschgerät identisch ist).

**Comment by Jan-Frankfurt** [comment]
Danke für die Hilfe - der „neue“ Aktor ist in der Tat nicht gerade fabrikneu, der kam aus der Reserveschublade. Die Firmware ist 1.12, beim kaputten Aktor, den ich tauschen will, ist die FW 2.8.
Der eine einkanalige Aktor, den er mir zum Tausch anbietet ist auch auf FW 1.12.

Ich denke damit ist klar, dass Du Recht hast. Problem ist nur - die FW dieser Dinger kann man offenbar nicht updaten.

**Comment by jp112sdl** [comment]
> die FW dieser Dinger kann man offenbar nicht updaten. 

Hab mir grad mal die Geräte-XMLs angeschaut. FW Update können die wohl wirklich nicht. Wie ärgerlich
