### ISSUE TITLE
HmIP-BROLL nicht mehr konfigurierbar

### ISSUE THREAD

**Issue by dehell** [jens-maus/RaspberryMatic#1235]
**Describe the bug**
Die Konfiguration der Komponente HmIP-BROLL lässt sich nicht mehr verändern, bei der Übertragung bleibt der 'Laufbalken' auf Ewig stehen.

**Steps to reproduce the behavior**
1. Lokales LAN, Firefox oder Edge-Browser
2. HmIP-BROLL unter Einstellungen/Geräte aufrufen und einen Schaltpunkt verändern.
3. Über 'OK' die Einstellungen übernehmen.
4. Es erscheint das Übertragungsfenster mit dem Laufbalken. Das verschwindet nicht mehr.

**Expected behavior**
Die Komponente erhält sehr viele Konfigurationsdaten, weshalb es immer lange dauert, bis die OK-Meldung kommt. Dann sind die Daten aktuell.
Das gleiche Verhalten gab es vorher schon bei Programmierung über eine cloudmatic-Verbindung. Ursache sind wohl zu kleine Datenbuffer. Lokal ging es aber immer (zuletzt im September 20 getestet).

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: 3.57.4.20210320
 - Used Hardware: Rasperry Pi 3B
 - Used HomeMatic RF-Module: Das kleine Funkmodul, das es als erstes für Raspberry gab, Bezeichnung kenne ich nicht.

**Additional context**
...

**Comment by blackbasket** [comment]
Duplicate zu #1189

**Comment by jens-maus** [comment]
Duplicate of #1189
