### ISSUE TITLE
RPI2 startet nicht mit RaspberryMatic-3.55.5.20201226-rpi2

### ISSUE THREAD

**Issue by silverghost2** [jens-maus/RaspberryMatic#1237]
Ein direktes Update auf diese Version führt dazu, dass das System nicht mehr bootet (rote LED leuchtet dauerhaft, keine Ausgabe über HDMI). Ebenso verhält es sich beim externen Update über Etcher auf die SD Karte.
Die Vorgängerversion (RaspberryMatic-3.57.4.20210320-rpi2) hat diesen Fehler nicht.

**Comment by r4m3u5** [comment]
> 
> 
> Ein direktes Update auf diese Version führt dazu, dass das System nicht mehr bootet (rote LED leuchtet dauerhaft, keine Ausgabe über HDMI). Ebenso verhält es sich beim externen Update über Etcher auf die SD Karte.
> Die Vorgängerversion (RaspberryMatic-3.57.4.20210320-rpi2) hat diesen Fehler nicht.

Gleiches Verhalten hier. Analyse scheint bereits zu laufen, da das Image nicht mehr zum Download verfügbar ist.

**Comment by oradke** [comment]
Moin! Bei mir kein Problem (Pi4). Update heruntergeladen, über WebUI hochgeladen, Update-Prozeß wie immer, läuft.

**Comment by jens-maus** [comment]
> Moin! Bei mir kein Problem (Pi4). Update von GitHub per Browser, heruntergeladen, über WebUI auf Raspi hochgeladen, Update-Prozeß wie immer, läuft.

Das ist kein Diskussionsforum hier. Nur Probleme melden/bestätigen/wiederlegen wenn man die gleiche Hardware hat. Sonst ist dieses Issue hier bald voll mit Meldungen das es keine Probleme gibt.

**Comment by jens-maus** [comment]
Ok, nun sollte die reparierte rpi2 Version online sein und funktionieren.

**Comment by r4m3u5** [comment]
Gerade einen Pi2 Model B von v3.57.4 mit dem aktuell verfügbaren rpi2-Image (.zip SHA256: 3df07bf788af2719d5a7d0ed86687c1efc46883915eab435d44060e1554265ab) problemlos auf v3.57.5 aktualisiert.
Der zweite ist noch im Update-Prozess, sieht aber auch gut aus.
Danke für den schnellen Fix @jens-maus und noch einen schönen Sonntag!
