### ISSUE TITLE
Device HM-CC-RT-DN - Anzahl auszulassenden Statusmeldungen im WebUI ist nicht mutierbar

### ISSUE THREAD

**Issue by pstzh** [jens-maus/RaspberryMatic#1238]
**Describe the bug**
Im WebUI für das Gerät HM-CC-RT-DN (Heizkörperthemostat) kann der Wert der "Anzahl der auszulassenden Statusmeldungen" nicht geändert werden, da nach dem Verlassen des Feldes automatisch ein Float Wert (.0) daraus gemacht wird.
Beim Abspeichern erscheint dann die Fehlermeldung: "Das Profil konnte nicht gespeichert werden."

**Steps to reproduce the behavior**
1. WebUI: Menü Einstellungen-> Geräte
2. Beim Gerät Heizkörperthermostat (HM-CC-RT-DN) rechts Funktion "Einstellen" wählen
3. Wert in Feld hinter "Anzahl der auszulassenden Statusmeldungen" ändern

**Expected behavior**
Wert bleibt Ganzzahl und kann abgespeichert werden,  

**Screenshots**
Nach dem Verlassen des Feldes:
![image](https://user-images.githubusercontent.com/38691519/115995304-0ed20d80-a5db-11eb-8788-810c17764a87.png)

Fehlermeldung:
![image](https://user-images.githubusercontent.com/38691519/115995422-68d2d300-a5db-11eb-8d52-494a1784dd9a.png)

**System information:**
 - RaspberryMatic Version: 3.57.5.20210424
 - Used Hardware: Raspberry Pi 3
 - Used HomeMatic RF-Module: RPI-RF-MOD

**Additional context**
Der Fehler war schon in der letzten RaspberryMatic Version (3.57.4.20210320) vorhanden.

**Comment by pstzh** [comment]
Das war nun wirklich superschnell - Danke :-)

**Comment by Baxxy13** [comment]
Beim HM-CC-RT-DN gab es auch Probleme mit dem Eingabefeld für "Ventilstörungsposition". 
Siehe: [#1058](https://github.com/jens-maus/RaspberryMatic/issues/1058#issuecomment-808711344)
Vielleicht kannst du mal prüfen ob das mit diesen Änderungen nun funktional ist.

**Comment by jens-maus** [comment]
Danke für den Hinweis. Hab das gerade mal getestet und wie zu erwarten beseitigt mein Fix auch dieses Problem, ja. Werde die nächsten Tage mir dann mal alle diese `getMinValue()`/`getMaxValue()` Funktionen in den easymodes Profilen anschauen, da ich denke das die alle genauso verkurkst sein werden wie die des `HM-CC-RT-DN`. Zumindest zeigte das gestern ein erster Blick in andere easymode-Profile. Und da ja nun der neue Release draussen ist sollten wir dann genug Zeit zum ausführlichen Testen haben.
