### ISSUE TITLE
WebUI: Sorting of system log inverted after refresh

### ISSUE THREAD

**Issue by dehell** [jens-maus/RaspberryMatic#124]
If you go to 'Status und Bedienung' / 'Systemprotokoll' you normally get a date sorted list with increasing datestamps. If you click on 'Aktualisieren' (the button, not in browser), the list reloads, but is inverted, starting with the newest datestamp and decreasing.
Tested it with Crome and Firefox.

**Comment by jens-maus** [comment]
This doesn't seem to be a RaspberryMatic specific problem but will certainly also be a problem with a plain CCU2.

**Comment by jp112sdl** [comment]
fixed in [3.53.26](https://www.eq-3.de/downloads/software/firmware/ccu3-firmware/CCU3-Changelog.3.53.26.pdf) ?
`[HMCCU-645]Die Sortierreihenfolge imSystemprotokoll wechselte bei jeder Aktualisierung der Daten.`

**Comment by jens-maus** [comment]
should be indeed fixed with 3.53.x. Thanks for the hint.
