### ISSUE TITLE
HMIP-PSM: Energie-Zähler RaspMatic / Energie-Zähler Gerät und Reset-Datum

### ISSUE THREAD

**Issue by alexhass** [jens-maus/RaspberryMatic#1246]
Habe da ein Transparenzproblem mit dem Stromzählen.

```
Energie-Zähler RaspMatic
--
232.500 kWh
65.87 EUR

Energie-Zähler Gerät
--
224064.40 Wh
63.48 EUR
```

Folgende Probleme sehe ich hier:

- Aus dem Namen "Energie-Zähler RaspMatic" geht nicht hervor, was das sein könnte. Könnte man den Namen selbstredend benennen?
- "Energie-Zähler Gerät" ist auch nicht wirklich besser, aber dafür ist sicher EQ-3 zuständig. Verständlich ist das auf jeden Fall nicht. Und das es noch einen Unterschied zwischen beiden gibt lässt mich nur an der Vertrauenswürdigkeit der Zahlen zweifeln, nachvollziehen kann ich es nicht.
- Man weiß nicht ab "Wann" der Zähler zählt. Wenn man den Preis sieht, will man natürlich auch wissen, wieviel Tage das waren. Könnten auch Jahre/Monate sein. Ich kann mich nicht mehr erinnern, wann ich das Gerät angeschlossen habe. :(
- Finde ich es echt verwirrend, dass 232.500 kWh eigentlich nur 232,5 kWh sind und nicht 232500 kWh. Im deutschen nutzt man Kommas und keine Punkte. Punkte sind im deutschen Tausendertrennzeichen.

Kann man dort bitte das Datum vom letzten "Reset" einbauen? Das wäre extrem hilfreich!

**Comment by jens-maus** [comment]
Sorry, but this is no support or discussion fora here. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. This was also already mentioned in the ticket template!
___
Tut mir leid, aber das hier ist kein Supportforum, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen.  Dies stand übrigens auch so im Ticket Template!

**Comment by alexhass** [comment]
This was a FEATURE request per Github. Please reopen the feature request.

**Comment by alexhass** [comment]
Ich kann auch 4 Bug cases draus machen, wenn dir das lieber ist.

**Comment by alexhass** [comment]
Und im Homematic Forum hast Du nicht geantwortet.

**Comment by jens-maus** [comment]
Nun, also erstes wäre es gut gewesen du löscht nicht einfach das Ticket template, sondern hälst dich an die Vorgaben - die nicht zum Spaß gemacht wurden. Und zweitens erachte ich diese Dinge als Dinge für ein Diskussionsforum und wenn daraus ein gemeinsamer (nicht einzelner) Konsens daraus wird das es hier 1. ein allgemeiner User-Wunsch (von > 1-2 Personen) ist und es auch überhaupt ansatzpunkte für Verbesserungen gibt (weil vieles eben in closed-source dingen von eQ3 stecken oder eben zu sehr verworren/verkapsuliert im WebUI quellcode ist) dann kann man hier her kommen und ein Enhancement/Feature Ticket dazu gerne aufmachen und diese Dinge geordnet und im einzelnen vorbringen. Und wenn es eben im HomeMatic Forum dazu keine Antwort meinerseits gibt oder auch von anderen Personen nichts dergleichen, dann ist es auch kein adequates mittel hier ein Ticket aufzumachen in der Hoffnung damit den vermeintlichen "Druck" zu erhöhen oder auch nur sich mehr Gehör zu verschaffen weil man das selbst gerne haben möchte.

Eins aber kann ich bereits jetzt sagen: Auf meiner eigenen Agenda ist das jedoch nicht, da ich ohnehin die WebUI in dem Energie-Zähler Bereich für gänzlich ungeeignet finde und auch die Codebasis in dem Bereich mehr als verworren/undurchsichtig ist, sodass ich mich sicherlich schwer dazu motivieren kann hier selbst Hand anzulegen.

**Comment by alexhass** [comment]
Der Github-Tracker ist ein Bug und Feature Tracker

Das Forum ist Chaos. Im Chaos wird alles diskutiert, aber keine Features und Bugs. Dazu gibt es Bugtracker und Feature Tracker.

Ich kann den Code nicht beurteilen. Mit Druck hat das überhaupt nichts zu tun. Lediglich mir strukturiertem Tracking von Issues. Das ist keine Diskussion. Das waren valide Punkte.

Ich weiß noch immer nicht, was der Unterschied ist und was ein Raspberrymatic-Energiezähler sein soll.

**Comment by jens-maus** [comment]
> Der Github-Tracker ist ein Bug und Feature Tracker
> 
> Das Forum ist Chaos. Im Chaos wird alles diskutiert, aber keine Features und Bugs. Dazu gibt es Bugtracker und Feature Tracker.

Mit verlaubt, das entscheidest nicht du. Das vorgehen in diesem Projekt ist wie von mir skizziert: Bringe diese Dinge im Forum oder Diskussionsteil hier bei GitHub vor und wir können gerne drüber reden und ich dir dann erläutern wieso eine Umsetzung schwierig bis ggf. nicht umsetzbar ist.

> Ich kann den Code nicht beurteilen. Mit Druck hat das überhaupt nichts zu tun. Lediglich mir strukturiertem Tracking von Issues. Das ist keine Diskussion. Das waren valide Punkte.

Sagt ja auch keiner das das keine validen Punkte sind, aber sie gehören IMHO hier zumindest *noch* nicht her und vor allem nicht zusammengewürfelt.

**Comment by alexhass** [comment]
Vorschlag - Du änderst die Texte, wenn Du das anders siehst. Dann gibt es auch keine Missverständnisse.

![2021-04-30_174038](https://user-images.githubusercontent.com/4450722/116719432-57266c80-a9db-11eb-99f4-2546074a11d7.jpg)

**Comment by jens-maus** [comment]
Ich denke wir brauchen das hier nicht weiter diskutieren. Trotzdem nur soviel gesagt: Ich denke es steht in ausreichender Form genug im Ticket Template, das du übrigens trotz expliziter Anmerkung ignoriert/gelöscht hast. Und ich denke der letzte Satz in diesem Template ist mehr als eindeutig!

<img width="770" alt="Bildschirmfoto 2021-04-30 um 17 46 43" src="https://user-images.githubusercontent.com/5887769/116720243-3e6a8680-a9dc-11eb-973d-4898414b0ae8.png">
