### ISSUE TITLE
HM-CC-RT-DN Funk-Heizkörperthermostat Boost-Modus

### ISSUE THREAD

**Issue by vepman** [jens-maus/RaspberryMatic#1247]
**Describe the bug**
Für den Funk-Heizkörperthermostat HM-CC-RT-DN lässt sich unter  Einstellungen > Geräte > Geräte-/ Kanalparameter der vorgegebene Wert des Ventilöffnungsgrads von 80 % im Boost-Modus nicht ändern.
Beim Eintragen eines neuen Wertes, z.B. 90 wird sofort automatisch eine Null ergänzt ( 90.0).
Bei dem Versuch zu speichern, wird die Meldung "Das Profil konnte nicht gespeichert werden" ausgegeben.
Nur die Zeit der Boost-Dauer lässt sich ändern. Danach wird das Profil ordnungsgemäß gespeichert.

**Steps to reproduce the behavior**
1. manuelles Eintragen des neuen Wertes z. B. 90 oder 100
2. ...
3. ...
4. ...

**Expected behavior**
Ändern des Wertes.

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: 3.57.5.20210424
 - Used Hardware: HM-CC-RT-DN, CCU3
 - Used HomeMatic RF-Module: CCU3-RF

**Additional context**
...

**Comment by jens-maus** [comment]
Duplicate of #1238
