### ISSUE TITLE
Proxmox 100% CPU usage

### ISSUE THREAD

**Issue by theimo1221** [jens-maus/RaspberryMatic#1249]
**Describe the bug**
After running some days straight occasionally cpu starts clocking up to 100% of 2 cores.

**Steps to reproduce the behavior**
1. Start Rapsberrymatic 
2. Run it for some days
3. ?
4. See CPU usage beeing stuck on 100% and Raspberrymatic not responding

**Expected behavior**
CPU usage should maintain it´s level regardless of runtime.

**System information:**
 - RaspberryMatic Version: 3.57.5.20210424
 - Used Hardware: Proxmox with CPU(s) 32 x AMD Ryzen 9 5950X 16-Core Processor
 - Used HomeMatic RF-Module: USB V2

**Additional context**
I use Proxmox 6.4-4 running some VMs and LXC but the overall system has still plenty of air left, so this is not an issue with my server, it´s the raspberrymatic which uses both granted cores to 100%

**Comment by jens-maus** [comment]
Please check within RaspberryMatic which process might eat up CPU time. And please make sure you assigned a minimum of 2 cores to the vm or otherwise issues might arise.

**Comment by theimo1221** [comment]
![image](https://user-images.githubusercontent.com/20605452/116985084-4b34f600-accc-11eb-8130-95e2215defdb.png)
As you can see usage on that machine was 100% while after reboot it´s somewhere around 5%

![image](https://user-images.githubusercontent.com/20605452/116985226-791a3a80-accc-11eb-8f52-07bb67d09c9d.png)
I don´t have any console, or do I have to SSH into machine?

![image](https://user-images.githubusercontent.com/20605452/116985349-9e0ead80-accc-11eb-9d4d-9b0ccc253c1a.png)
This is my current configuration.

As normally the CPU usage is around that 5% personally I don't feel good about giving it 1 or 2 more cores, as that high usage must be the result of some rare bug.

**Comment by jens-maus** [comment]
> I don´t have any console, or do I have to SSH into machine?

Of course you can have a console. Like with a normal RaspberryPi you just have to press Alt+F2 to get the console prompt.

> As normally the CPU usage is around that 5% personally I don't feel good about giving it 1 or 2 more cores, as that high usage must be the result of some rare bug.

Well, I don't see other seeing the same issue here, so it would be good to first discuss this under the current Proxmox RaspberryMatic users, I guess. Under ESXi (which I use) I don't have these effects.

But as said:
Use the console/SSH login to debug the potential reason or identify the process within RaspberryMatic which might be responsible for the 100% cpu usage of that VM.

**Comment by JustXrv** [comment]
Unfortunately, as said by other people who have answered you before me, you should check what causes this intensive use of the cpu, otherwise you can opt to add more vcore but I suggest you check the reason for this use of the cpu. I remind you that you have the Proxmox console

**Comment by jens-maus** [comment]
BTW: Please note following homematic-forum article on a similar matter (high cpu on QEmu/KVM) which (because Proxmox uses QEmu/KVM as well) is also true for Proxmox:

https://homematic-forum.de/forum/viewtopic.php?f=65&t=58225&start=20#p579882

So it might simply be (if no process within RaspberryMatic utilized high CPU usage) that the web-based CPU usage display of Proxmox might be simply wrong.

**Comment by theimo1221** [comment]
Thanks for the information and shared keyboard shortcut

Regarding this:
> So it might simply be (if no process within RaspberryMatic utilized high CPU usage) that the web-based CPU usage display of Proxmox might be simply wrong.

As in these situation I cant even log into raspberrymatic web ui, additionaly my commands issued via iobroker aren't executed and pressing a button on HmIP wall switch not blinking green I'm very confident saying the Raspberrymatic itself is unresponsive for these kind of actions.

**Comment by theimo1221** [comment]
Looking at my home automation log files, there might have been some amount of commands issued around that time in a short time frame.

So there might be an issues if there are piling up plenty of commands in parallel.

**Comment by theimo1221** [comment]
Today it happened again
![image](https://user-images.githubusercontent.com/20605452/117983515-54127100-b337-11eb-8ce8-9295a55bf7ed.png)


Unfortunately pressing that Alt+F2 somehov the Raspberrymatic initialized a reboot, so I couldn't grab a list of processes and their respective cpu usage

**Comment by jens-maus** [comment]
Ok. too bad. Then make sure that you already pressed ALT+F2 now and probably keep the console logged in also already so next time you then just have to open the console in proxmox again and it will then be switched to ALT+F2 already.

**Comment by blackbasket** [comment]
Hi Thiemo,

do you see this behavior always after a similar time range?

Regards,
Marcel

**Comment by theimo1221** [comment]
Good Morning,

It seems Raspberrymatic now always uses more CPU in comparision to previous version.
![image](https://user-images.githubusercontent.com/20605452/118102845-8ffe1280-b3d9-11eb-88ad-eb925f81bedc.png)

Unfortunately this is the only view giving information about this.
So the first incident occured ~27.04.2021. The 2nd on 04.05.2021 (~+7 days). The 3rd yesterday 12.05.2021 (~+8days).

What confuses me most about the incident yesterday is, that I changed my own home automation logic (not in HomeMatic) to highly reduce issued commands in direction of RaspberryMatic. 

Best Regards
Thiemo

**Comment by blackbasket** [comment]
Have a look at #1207 ... it is about 7d in my case, too... cannot find the issue for now... even with a fresh install...

**Comment by jens-maus** [comment]
As said before: You guys have to debug that **within** the VM and not from the outside. Thus, login and keep the ssh login open or the console active an monitor cpu usage within the VM and wait until the VM is not responsive anymore and then check the console output of the VM. Just stating the symptoms won‘t really help to identify the root cause.

**Comment by blackbasket** [comment]
I totally agree, Jens. But in my case it is no VM... RM is running on RasPi3 (original CCU3 hardware, not even Charly)...

**Comment by jens-maus** [comment]
> I totally agree, Jens. But in my case it is no VM... RM is running on RasPi3 (original CCU3 hardware, not even Charly)...

Then connect a HDMI cable and usb keyboard an monitor it accordingly. And if you are using a rpi and theimo a vm reasons for regular issue might be simply completely different. In your case it might perfectly be an SD card issue while theimo might have other issues.

**Comment by theimo1221** [comment]
I have it now open like this, so as soon as we enter that critical state again we should be able to see the villain 😄 

![image](https://user-images.githubusercontent.com/20605452/118111897-980f7f80-b3e4-11eb-8978-778f8bfb0439.png)

**Comment by jens-maus** [comment]
And in that state with ~1%cpu usage, what does proxmox show how mich cpu is used? Because the difference is then the virtualization overhead.

**Comment by blackbasket** [comment]
> > I totally agree, Jens. But in my case it is no VM... RM is running on RasPi3 (original CCU3 hardware, not even Charly)...
> 
> 
> 
> Then connect a HDMI cable and usb keyboard an monitor it accordingly. And if you are using a rpi and theimo a vm reasons for regular issue might be simply completely different. In your case it might perfectly be an SD card issue while theimo might have other issues.
> 
> 

There is no need to... I know, that after 7d the java process is the issue... but I cannot figure out what makes this happening...

BTW: SD card was changed as well as my hardware...

**Comment by jens-maus** [comment]
> There is no need to... I know, that after 7d the java process is the issue... but I cannot figure out what makes this happening...

Well, if it really is the java process there is nothing we can do about it because that‘s completely closed-source with only eQ3 having access to the sources. All you can do is then raise de debug level of the HMIPServer and monitor the /var/log/hmserver.log logfile.

**Comment by blackbasket** [comment]
> > There is no need to... I know, that after 7d the java process is the issue... but I cannot figure out what makes this happening...
> 
> 
> 
> Well, if it really is the java process there is nothing we can do about it because that‘s completely closed-source with only eQ3 having access to the sources. All you can do is then raise de debug level of the HMIPServer and monitor the /var/log/hmserver.log logfile.
> 
> 

Thanks, Jens... I will go on investigating...

@theimo1221 : Are you using any virtual HmIP-Switches?

**Comment by theimo1221** [comment]
> > > There is no need to... I know, that after 7d the java process is the issue... but I cannot figure out what makes this happening...
> > 
> > 
> > Well, if it really is the java process there is nothing we can do about it because that‘s completely closed-source with only eQ3 having access to the sources. All you can do is then raise de debug level of the HMIPServer and monitor the /var/log/hmserver.log logfile.
> 
> Thanks, Jens... I will go on investigating...
> 
> @theimo1221 : Are you using any virtual HmIP-Switches?

Yes I got some of those Heating Groups which are virtual devices as well:
![image](https://user-images.githubusercontent.com/20605452/118124836-6ef7ea80-b3f6-11eb-9115-f4f1862753f0.png)

**Comment by blackbasket** [comment]
Hmm... I found some advise days ago, where someone had a similar behavior... he fixed it using the BidCos virtual switches... I had one virtual HmIP switch and changed this to BidCos two days ago... my heating group still exists... We will see in 5 days ;)

**Comment by theimo1221** [comment]
![image](https://user-images.githubusercontent.com/20605452/118406251-80055d80-b67b-11eb-8ec2-b5715538222d.png)

**Comment by blackbasket** [comment]
Looks familiar -.-

**Comment by jens-maus** [comment]
Well, looks like the java-based HmIP service daemon (HmIPServer) is bus doing stuff and is occupying a lot of CPU time. Thus, have a look into the `/var/log/hmserver.log` logfile to see if you find something relevant in there.

**Comment by theimo1221** [comment]
Unfortunately the logs from yesterday got overwritten by the server restart.
This is how my file looks now:

**Comment by blackbasket** [comment]
This looks regular to me... is it possible that you may delete the heating groups for testing? My 7d will end tomorrow, but I only "deleted" the virtual HmIP keys... my heating group still exists... otherwise I will do it after the (hopefully not happening) crash...

**Comment by blackbasket** [comment]
My RM crashed this nigh after about 7d 9h. I show you the logs, I got from the device as well as lsof and top, which are executed every 15 minutes by script. I raised the log levels to debug and started the syslog server again.




[hmserver.txt](https://github.com/jens-maus/RaspberryMatic/files/6506362/hmserver.txt)
[top-lsof_0202.txt](https://github.com/jens-maus/RaspberryMatic/files/6506363/top-lsof_0202.txt)
[top-lsof_0217.txt](https://github.com/jens-maus/RaspberryMatic/files/6506364/top-lsof_0217.txt)
[top-lsof_0232.txt](https://github.com/jens-maus/RaspberryMatic/files/6506365/top-lsof_0232.txt)
[top-lsof_0247.txt](https://github.com/jens-maus/RaspberryMatic/files/6506366/top-lsof_0247.txt)
[messages.txt](https://github.com/jens-maus/RaspberryMatic/files/6506370/messages.txt)

**Comment by jens-maus** [comment]
@blackbasket Well, first of all: This ticket here is about Proxmox and 100% CPU usage and you are using a RaspberryPi as it seems. Thus, your issue does not have to have the same root cause here. However, what I saw from your logfiles is:

1. @ ~2:00 the badblocks check was running. Thus, I would disable it to rule out that this might indeed have a negative effect on your performance or might be the root cause of bringing down your HmIPServer (`touch /etc/config/NoBadBlocksCheck`).
2. You are using the HAP-HomeMatic addon (https://github.com/thkl/hap-homematic). This addon was already responsible for several different things in respect of bringing down a whole CCU. In addition, the your top-lsof logfile you can see that when the issue happend the number of socket file descriptor increases for the HmIPServer as well as for HAP HomeMatic. Thus, disable/uninstall it completely and see if this solves your problems.

**Comment by blackbasket** [comment]
Thank you, @jens-maus ...

We are investigating HAP as well. I just got to this ticket, because to me, it seems like it's similar.

As I understand, you don't want me to update here. Should I go back to the discussion?

**Comment by jens-maus** [comment]
> As I understand, you don't want me to update here. Should I go back to the discussion?

You can of course post here as well and leave some sidenodes, but please don't hijack this issue simply because it mentions 100% cpu usage. IMHO your issue seems to have a different root cause. But we need of course @theimo1221 to jump in with some logfile outputs of `/var/log/hmserver.log`, etc. so that we can see if this might be related. But to me your issue seems to be HAP-HomeMatic related and that would be the first thing to switch off if I were you.

**Comment by blackbasket** [comment]
Hi,

today it happened again. I forgot to download logs from the RM prior restarting.

I only have the debug syslogs. In the moment the CPU usage steps up, I start seeing XmlRpc errors.

Do you want to take a look at this logs?

Regards,
Marcel

**Comment by blackbasket** [comment]
FYI: looks, like @jens-maus was right with the HAP hint. RM is running for >8d, now. It's the first time in 2021 ;) Thanks :)

**Comment by jens-maus** [comment]
> @jens-maus can we reopen this issue?

Well, I can of course reopen the ticket again, but as you are still the only one seeing this Proxmox 100%cpu usage I am sceptical that will identify any reason for that high cpu usage (which only proxmox reports, but within RM you are not seeing it). So what is your suggestion?

**Comment by jens-maus** [comment]
Well, then please show this high CPU usage again with potential log output. Unfortunately the whole HmIPServer is closed source software from eQ3. So there are low to no chances to get things fix in there ourself. Only if you have a reproducible case in a normal CCU3 system there might be chances to see this fixed in future!

**Comment by theimo1221** [comment]
Okay

Where how can I retrieve additional extensive logs form that Java prozess the text time this occures?
