### ISSUE TITLE
no virtual channels available

### ISSUE THREAD

**Issue by kieselbert** [jens-maus/RaspberryMatic#125]
![raspberrymatic](https://user-images.githubusercontent.com/4134726/27807654-ba7a3c8a-6042-11e7-9c46-d05ae485044a.png)
![lanadapter](https://user-images.githubusercontent.com/4134726/27807657-bf8d7c96-6042-11e7-9556-97b38cd33ec4.png)
In this pictures you can see the same device attached to the (old) Lan-Adapter and RaspberryMatic. In RaspberryMatic the virtual channels are missing.

**Comment by HMside** [comment]
Please check if you have disabled the "Expert mode not visible / Modus vereinfachte Verknüpfungskonfiguration aktivieren" in the user management. After that you will see virtual channels.
