### ISSUE TITLE
Regenmenge im Diagramm wird nicht aufgezeichnet bzw. angezeigt

### ISSUE THREAD

**Issue by Sydney1101** [jens-maus/RaspberryMatic#1250]
**Describe the bug**
Die Regenmenge der Wetterstation (HM-WDS100-C6-O-2) wird nicht im Diagramm angezeigt bzw. aufgezeichnet. Unter Status - Geräte oder auch unter RedMatic stimmen die Werte.

**Steps to reproduce the behavior**
1. Aktivierung der Aufzeichnung der Regenmenge im Diagramm
2. Während des Regens wird der Status unter Geräte angezeigt. Die Regenmenge wird hochgezählt.

**Expected behavior**
Die Regenmenge im Diagramm sollte mit dem Status bzw. den Werten in RedMatic übereinstimmen. Jedoch sind diese immer 0.

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: aktuelle (3.57.5.20210421)
 - Used Hardware: Raspberry PI 3+
 - Used HomeMatic RF-Module: HM-MOD-RPI-PCB

**Additional context**
...

**Comment by jens-maus** [comment]
Die gesamte Verarbeitung von Diagrammen läuft leider im exklusiven Closed-Source Teil der CCU/RaspberryMatic ab (sogenannter HmIPServer). Es gibt daher leider keinerlei Ansatzpunkt für Verbesserungen oder Fehlerbehebungen. Daher bitte direkt an eQ3 wenden.
