### ISSUE TITLE
HB-RF-ETH: Reconnect not working

### ISSUE THREAD

**Issue by hessijames79** [jens-maus/RaspberryMatic#1251]
Steps to reproduce:
Disconnect HB-RF-ETH from network.
Reconnect HB-RF-ETH to network.

Expected result:
Raspberrymatic reconnects to HB-RF-ETH

Actual result:
Raspberrymatic does not reconnect. Restarting the Raspberrymatic system solves the problem.

Syslog:
May  5 20:34:42 rpimatic-kvm-ccu kernel: [268266.369585] hb-rf-eth hb-rf-eth: Timeout occured while connecting to 192.168.0.195
May  5 20:34:42 rpimatic-kvm-ccu kernel: [268266.729526] hb-rf-eth hb-rf-eth: Error sending packet, not connected
May  5 20:34:42 rpimatic-kvm-ccu kernel: [268266.729531] hb-rf-eth hb-rf-eth: Error sending packet, not connected
May  5 20:34:43 rpimatic-kvm-ccu kernel: [268266.873559] hb-rf-eth hb-rf-eth: Trying to reconnect to 192.168.0.195
May  5 20:34:43 rpimatic-kvm-ccu kernel: [268266.893633] hb-rf-eth hb-rf-eth: Error sending packet, not connected
May  5 20:34:43 rpimatic-kvm-ccu kernel: [268266.977547] hb-rf-eth hb-rf-eth: Timeout occured while connecting to 192.168.0.195

System:
Raspberrymatic on kvm. Tested versions: 3.57.5.20210424 (current stable) and 3.57.5.20210505 (current nightly)

Patrick

**Comment by jens-maus** [comment]
> Raspberrymatic does not reconnect. Restarting the Raspberrymatic system solves the problem.

This is a known limitation of the HB-RF-ETH. As soon as the HB-RF-ETH is disconnected from power (either from microUSB or POE) the RF module on the HB-RF-ETH is not initialized anymore. Thus a reboot or reinit of certain processes is required.

See here for more information:
https://homematic-forum.de/forum/viewtopic.php?f=76&t=60150&start=350#p645378
