### ISSUE TITLE
Use PiModules UPS PIco HV3.0A buzzer as actuator for alarms/door bell

### ISSUE THREAD

**Issue by renne** [jens-maus/RaspberryMatic#126]
The buzzer of the UPS PIco HV3.0A can be controlled via I²C. It would be great to use it as an actuator in Homematic.

The I²C registers are listed on page 7 of the [UPS PIco Programmers Registers](https://www.modmypi.com/download/pimodules/_28_03_2017-register-list.pdf).

**Comment by jens-maus** [comment]
Sorry, but IMHO this is way to much for support of the PicoUPS in RaspberryMatic and would require substantial changes. However, you should be able to set/modify the buzzer or any other i2c related setting by uding the 'i2cset' command yourself. You should be able to write a honematic script within the WebUI which uses system.Exec() and executes the necessary 'i2cset' commands.
