### ISSUE TITLE
Messwerte werden im Gerätestatus nicht mehr angezeigt

### ISSUE THREAD

**Issue by benny200d** [jens-maus/RaspberryMatic#1262]
**Describe the bug**
Die Messwerte der Messkanäle werden nicht mehr in der Statusübersicht angezeigt nachdem die Bedienbarkeit einmal deaktiviert wurde.

**Steps to reproduce the behavior**
1. Am Hauptaktor Bedienbar deaktivieren -> Einstellung wird auf alle Kanäle übernommen
2. Schalt und Messkanäle werden im Status nicht mehr angezeigt
3. Wird am Hauptaktor Bedienbar wieder aktiviert kann der Schaltkanal wieder bedient werden, die Messwerte werden aber nicht wieder eingeblendet.

**Expected behavior**
...

**Screenshots**
![Bildschirmfoto 2021-05-12 um 18 01 37](https://user-images.githubusercontent.com/84091292/118007871-d6f1f680-b34c-11eb-9bd8-918c5e68c94c.png)
![Bildschirmfoto 2021-05-12 um 18 01 48](https://user-images.githubusercontent.com/84091292/118007877-d8232380-b34c-11eb-958f-7ec917835370.png)

**System information:**
 - RaspberryMatic Version: 3.57.5.20210424
 - Used Hardware: Raspberry Pi 3 B
 - Used HomeMatic RF-Module: RPI-RF-MOD

**Additional context**
Ich vermute hier ist das selbe Verhalten gemeint. #1137

**Comment by jens-maus** [comment]
Auch hier gilt das gleiche wie in #1137. Nämlich das dies kein generelles Problem sein kann, sondern irgend ein Effekt der lokalen Installation sein muss. Auch hier gilt "worksforme" und ich bekomme das nicht reproduziert.
