### ISSUE TITLE
Nach update auf release 3.57.5.20210424 nun wiederholt alle ca. 5 MInuten ein ``WatchDog-Alarm ausgelöst	under-voltage detected`` , Netzteil stabil mit 5V/3A... 

### ISSUE THREAD

**Issue by marabu02** [jens-maus/RaspberryMatic#1263]
**Describe the bug**
...

**Steps to reproduce the behavior**
1. ...
2. ...
3. ...
4. ...

**Expected behavior**
...

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: ...
 - Used Hardware: ...
 - Used HomeMatic RF-Module: ...

**Additional context**
...

**Comment by jens-maus** [comment]
Duplicate of #1146
