### ISSUE TITLE
Encoding Errors in HomeAssistant Addon

### ISSUE THREAD

**Issue by stefangries** [jens-maus/RaspberryMatic#1264]
**Describe the bug**
There are various places in RaspberryMatic with enconding problems (red circles) with umlauts and °C.

**Screenshots**
![rspmatic_ha_1](https://user-images.githubusercontent.com/10342151/118047863-affee900-b37b-11eb-8351-dbd78ce4f371.png)
![rspmatic_ha_2](https://user-images.githubusercontent.com/10342151/118047865-b0977f80-b37b-11eb-87f9-11fd454ac795.png)

**System information:**
 - RaspberryMatic Version: 3.57.5.20210424 Addon on HassOS 6.0.RC1 with supervisor-2021.05.dev1204
 - Used Hardware: Intel NUC
 - Used HomeMatic RF-Module: RPI-RF-MOD/HB-RF-USB-2

**Comment by stefangries** [comment]
In the current version of the addon the error appears again. Was there something reverted or does something new trigger the problem?

**Comment by jens-maus** [comment]
Nope, AFAIK there was nothing reverted. However, which Addon-version have you installed and can you please open the browser console and check which html code there is for these temperature units? And furthermore, please state the operating system and browser you are using to reproduce the issue as well as trying a different browser engine to see if in all browsers this glitch can be observed.

**Comment by stefangries** [comment]
The error can be observed in the Home Assistant macOS App, Opera on Windows, Firefox on Windows and Chrome on Windows.
The encoding problem only occurs when opening raspberrymatic via ingress. Direct acces via port is fine.

![image](https://user-images.githubusercontent.com/10342151/134909332-5753e9a9-4cb5-46bd-80bb-401f4987f480.png)

**Comment by jens-maus** [comment]
@stefangries Ok, thanks for this example. I think I squashed another bug where where unfortunately a direct latin1 encoded celcius unit was used instead of using the URL encoded `&deg;C` string use. So please, if you can, try the next upcoming nightly snapshot tomorrow and report back if this solves the issue or not.
