### ISSUE TITLE
Cannot Add Channel to Diagram in HomeAssistant Addon

### ISSUE THREAD

**Issue by stefangries** [jens-maus/RaspberryMatic#1265]
**Describe the bug**
The "Hinzufügen"-Button (green circle) does not do anything. On the browser-console you can see an error for each click on the button. For me, it looks like the "api/hassio_ingress"-part of the request URL is missing.

**Steps to reproduce the behavior**
1. Go to Einstellungen -> Diagramme
2. Create a New Temperature-Diagram
3. Click +
4. Click Hinzufügen
5. Nothing happens but errors on the browser-console

**Screenshots**
![rspmatic_ha_2](https://user-images.githubusercontent.com/10342151/118048230-4501e200-b37c-11eb-870f-9171606e167c.png)
![rspmatic_ha_3](https://user-images.githubusercontent.com/10342151/118048232-459a7880-b37c-11eb-8eac-4dffa1acfb4e.png)

**System information:**
 - RaspberryMatic Version: 3.57.5.20210424 Addon on HassOS 6.0.RC1 with supervisor-2021.05.dev1204
 - Used Hardware: Intel NUC
 - Used HomeMatic RF-Module: RPI-RF-MOD/HB-RF-USB-2

**Comment by jens-maus** [comment]
Can you please test if this issue is already solved by using the latest nightly experimental snapshot version of the addon (3.57.5.20210513-def6c02) from here: https://github.com/jens-maus/ha-addon-raspmatic

I think I already fixed this issue some days ago, see #1244 or https://github.com/jens-maus/RaspberryMatic/commit/7d2319844808edc178d6e1da93836d8569c60e5c

**Comment by stefangries** [comment]
Sorry, seems like I missed the notification mail for your reply.

Actually I cannot check, as restoring a backup does not work for me:
![image](https://user-images.githubusercontent.com/10342151/118393213-364a5200-b63e-11eb-9950-5f33b9b3d848.png)
(Secured Mode was disabled)

**Comment by jens-maus** [comment]
? Bit you wrote that you were able to restore a backup already? Thus, should work also a second time.

**Comment by stefangries** [comment]
In the other addon version at https://github.com/jens-maus/RaspberryMatic backup restore works, but not with the version at https://github.com/jens-maus/ha-addon-raspmatic

**Comment by jens-maus** [comment]
> https://github.com/jens-maus/ha-addon-raspmatic

Just tried it to restore a backup in a fresh RaspberryMatic add-on install from "ha-addon-raspmatic" and the backup restore worked fine. Please make sure you cleared the browser cache if you switch between the different Add-on versions.

**Comment by stefangries** [comment]
Clearing the cache did the trick.
I can confirm, that the button is now working correctly on 3.57.5.20210513-def6c02. 
Thanks for fixing this!

Now I'm getting the "Für dieses Diagramm stehen noch keine Daten zur Verfügung."-Error, but actually I don't know, how long it takes for them to show up. So actually, this might be normal behaviour.
