### ISSUE TITLE
Angelerntes Gerät hängt im Posteingang und ist nicht löschbar

### ISSUE THREAD

**Issue by nicx** [jens-maus/RaspberryMatic#1266]
**Describe the bug**
Ich habe einen HM-Sec-RHS angelernt, der wohl einen Defekt hat. Das Gerät hängt nun mit einer sehr seltsamen Seriennummer im Posteingang fest. Man kann nichts mehr tun, ausser den sich drehenden Ladekreis zu bestaunen. Ein Restart half leider nicht. Der HMIPServer schmiert zudem nun ständig ab.
Wie bekomme ich das Gerät gelöscht?

**Steps to reproduce the behavior**
1. ...
2. ...
3. ...
4. ...

**Expected behavior**
...

**Screenshots**
<img width="1041" alt="Bildschirmfoto 2021-05-13 um 22 23 09" src="https://user-images.githubusercontent.com/25152397/118183196-1f3b1280-b43a-11eb-8a92-d9243463db50.png">

**System information:**
 - RaspberryMatic Version: 3.57.5.20210424
 - Used Hardware: Docker
 - Used HomeMatic RF-Module: CFG-LAN-GW

**Additional context**
...

**Comment by jens-maus** [comment]
Sorry, but this is no support or discussion fora here. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. This was also already mentioned in the ticket template!
___
Tut mir leid, aber das hier ist kein Supportforum, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen.  Dies stand übrigens auch so im Ticket Template!
