### ISSUE TITLE
HMIPW-DRD3 unreachable service message but channel is inactive

### ISSUE THREAD

**Issue by Xsez** [jens-maus/RaspberryMatic#1270]
I installed the DRD3 about a year ago and finally connected the first channel recently. Back then I was running original CCU3 Firmware and set all channels to inactive, to disable the unreachable servicemessages. Now I'm running Raspberrymatic 3.57.5.20210424.

I enabled all channels and channel 1 is working fine. Channel 2 and 3 give out a servicemessage, as expected. I set channel 2 and 3 back to inactive but the service message won't disappear.

![Screenshot 2021-05-14 210404](https://user-images.githubusercontent.com/8041173/118317908-f4fc5a00-b4f8-11eb-8599-8a4c2ce76ea5.png)
![Screenshot 2021-05-14 210431](https://user-images.githubusercontent.com/8041173/118317911-f594f080-b4f8-11eb-8bce-c355ae356b16.png)

**Comment by jens-maus** [comment]
Sorry, but for me this perfectly works. In addition, the whole HmIP-Wired part is in the closed source software component (HMIPServer) to which RaspberryMatic has no source code access to. In addition, please first try to discuss and identify potential fixes in the discussion/RaspberryMatic fora before raising it as a potential bug issue here. Furthermore, please make sure to reboot your CCU which might remove these service messages.
