### ISSUE TITLE
Zustände der Kanälen batteriebetriebener Geräte bei CCU Restart behalten

### ISSUE THREAD

**Issue by etofi** [jens-maus/RaspberryMatic#1274]
**Is your feature request related to a problem? Please describe.**
Die CCU speichert die Zustände bei batteriebetreibenen Gerät nicht beim Restart (z.B. HM-SCI-3-FM)

**Describe the solution you'd like**
Je Kanal des Gerätes eine Option (Ja/Nein) einbauen um das Speichern des Zustandes beim CCU Reboot ein- bzw. auszuschalten.

**Describe alternatives you've considered**
- Generell den Zustand aller Kanäle so speichern dass diese auch beim Rebbot erhalten bleiben.
- Man kann je Kanal den Standardwert nach dem Reboot definieren.

**Additional context**
Ich weß es gibt die Lösung das über Systemvariable zu machen, aber es wäre deutlich einfacher wenn das ohne diesen Umweg möglich wäre.

**Comment by jens-maus** [comment]
Dies ist ein normales, vom Hersteller (eQ3) so spezifiziertes Verhalten auf das im Rahmen der RaspberryMatic leider keinerlei Einfluss/Veränderung genommen werden kann weil diese Dinge in Closed-Source Komponenten umgesetzt sind auf die nur der Hersteller zugriff hat.
