### ISSUE TITLE
BidCos-RF Anlernmodus konnte nicht aktiviert werden

### ISSUE THREAD

**Issue by ChristophNikolaus** [jens-maus/RaspberryMatic#128]
RaspberryMatic startet nach der ersten Installation normal, aber beim Anlernen Versuch bekomme ich die Fehlermeldung: "BidCos-RF Anlernmodus konnte nicht aktiviert werden"

Wenn ich per HDMI dem Raspberry beim Starten zusehe, bekomme ich folgende Meldungen:

```
[31.529374] bcm2835_raw_uart: ´' invalid for parameter 'uart0_base
[31.529691] bcm2835_raw_uart: ´' invalid for parameter 'uart0_irq
```

(Installiert auf dem Raspberry 1 B-Modell)

**Comment by jens-maus** [comment]
This issue had already been fixed quite a while in commit https://github.com/jens-maus/RaspberryMatic/commit/0d0ca0076729be0d7f5780c1778e2fae3b2f2589. Thus, the next release of RaspberryMatic should fix this issue.
