### ISSUE TITLE
LEDs (Heartbeat/SD access) not working as expected on Pi 1B (without "+")

### ISSUE THREAD

**Issue by klour** [jens-maus/RaspberryMatic#1284]
**Describe the bug**
The heartbeat LED does not seem to work like expected on my Raspberry Pi 1B (without "+"). Maybe the ACT LED is also affected. I use latest Raspberrymatic release: 3.57.5.20210525.
I am observing this issue now for numerous releases, you can say as long as I use Raspberrymatic on my Pi 1B.
The Pi 1B has five LEDs. I can observe following behaviour once Raspberrymatic is fully loaded:

- ACT: Always off, except while Bootloader is accessing the SD card during boot. As soon as Raspberrymatic starts booting up, the LED is always off again. Is this correct?
- PWR: Always on. Is this correct?
- FDX: Always on. Works like expected.
- LNK: Blinking showing network activity. Works like expected.
- 100: Always on. Works like expected.

Raspberrymatic WebUI does not show any errors.

**Steps to reproduce the behavior**
1. Booting Raspberrymatic
2. Operation of Raspberrymatic

**Expected behavior**
Actually I think the PWR and ACT LEDs are not working as expected. No LED shows a heartbeat to my Pi 1B.
The ACT LED is also not showing any activity as soon Raspberrymatic boots up and during its normal operation. SD card access does not show LED activity. PWR LED is always on.
Maybe this is related to the Pi 1B.

**Screenshots**
![Pi1B](https://user-images.githubusercontent.com/77859971/119953824-b2c62480-bf9e-11eb-8703-a41bc5d9d52e.PNG)

**System information:**
 - RaspberryMatic Version: 3.57.5.20210525
 - Used Hardware: Raspberry Pi 1B (without "+")
 - Used HomeMatic RF-Module: HM-MOD-RPI-PCB

**Additional context**
Greetings from NRW.

**Comment by jens-maus** [comment]
ok, I could reproduce the issue here and see that the `/sys/class/led` nodes for the `led0` led (which is equivalent to act-led) is missing in RaspberryMatic. However, in RaspberryPiOS it is there. Still don't know why but at least this is indeed a bug, thus a one with minor/low priority.

**Comment by klour** [comment]
Hi @jens-maus, 
Thank you very much for your quick response and confirmation. I am very happy about the ability to contribute a little to your lovely project.
In the past I also haven't paid a lot of attention to the LED misbehaviour on my Pi 1B, since it is for sure not a show stopper. However today I encouraged myself to report this to you. Absolutely agree, definitely a minor/low prio one. Looking forward to the bugfix.

With your valuable statement, I had also closer look to the `/sys/classes/leds` directory, comparing the Pi 1B with Raspberrymatic and a Pi 4B running Pi OS:

![sys_class_leds](https://user-images.githubusercontent.com/77859971/119982366-09435b00-bfbf-11eb-91ba-300b06cbff2b.png)

Very nice to see and to learn more about the device dependencies, references and internal stuff of how Linux works and ticks. Thanks for this. Enjoy the warm weather this weekend, after such a long period of rain and cold.
