### ISSUE TITLE
Zusätzlicher Button unter Status und Bedienung > Programme > Aktion, der das jeweilige Programm mit Bedingungsprüfung triggert

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1285]
**Is your feature request related to a problem? Please describe.**
Der Sinn des "Start"-Buttons hinter den Programmen bei "Status und Bedienung > Programme > Aktion" hat sich mir nie erschlossen. Bekanntlich wird damit zwar das Programm getriggert, aber dann ohne Bedingungsprüfung immer das erste DANN ausgeführt. So wie es auch `.ProgramExecute()` macht. 

**Describe the solution you'd like**
Es wäre praktisch hier einen zweiten Button "Start mit Bedingungsprüfung" zu haben der das Programm inklusive Bedingungsprüfung triggert. So wie es auch `dom.GetObject (ID_PROGRAMS).Get ("Testprogramm").State(1);` macht.

![Programme_Start_Button_Idee](https://user-images.githubusercontent.com/54898249/120715179-86da0000-c4c4-11eb-9d7e-5e0820f408ce.JPG)

**Describe alternatives you've considered**
Alternativ könnte man sicher auch den jetzigen "Start"-Button umprogrammieren, wäre aber zwecks Kompatibilität zur CCUx nur die 2. Wahl.

**Additional context**
Da ich keine Expertise in Sachen WebUI-Entwicklung habe kann ich erstmal nichts weiter für eine mögliche Umsetzung beisteuern.

**Comment by jp112sdl** [comment]
Ich hab hier mal noch eine Diskussion begonnen: https://github.com/jens-maus/RaspberryMatic/discussions/1337
