### ISSUE TITLE
ReGaHss Adapter Fehler und CCU3 mega langsam bei Start (reproduzierbar)

### ISSUE THREAD

**Issue by Michael-Dreibholz** [jens-maus/RaspberryMatic#1287]
Hallo zusammen,
ich bin langsam am Ende meiner Weisheit angekommen.
Bei mir wurde der Stromzähler getauscht und iobroker und CCU vorher runtergefahren.
Dann Neustart und seit diesem Zeitpunkt, ist meine CCU mega langsam nach Neustart und Bewegungsmelder usw. reagieren nicht mehr wirklich.
Firmware auf allen Komponenten aktuell, Mediola Server, CUXD alles aktuell.
Iobroker alle Adapter aktuell.
Im Log habe 100te solcher Fehler stehen.

faultCode:-5,faultString:"Unknown Parameter value for value key: SET_POINT_TEMPERATURE"]) [CallXmlrpcMethod():iseXmlRpc.cpp:2608]
Jun 4 15:00:59 CCU3 local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1011, params: {"000C9A49A7D34C:1","SET_POINT_TEMPERATURE"}) [CallGetValue():iseXmlRpc.cpp:1435]
Jun 4 15:00:59 CCU3 local0.err ReGaHss: ERROR: CallGetValue failed; sVal = 0.000000 [ReadValue():iseDOMdpHSS.cpp:124]
Jun 4 15:00:59 CCU3 local0.warn ReGaHss: WARNING: XMLRPC 'getValue': rpcClient.isFault() failed (url: xmlrpc://127.0.0.1:32010, params: {"000C9A49A7D34C:1","SWITCH_POINT_OCCURED"}, result: [faultCode:-5,faultString:"Unknown Parameter value for value key: SWITCH_POINT_OCCURED"]) [CallXmlrpcMethod():iseXmlRpc.cpp:2608]

Hat jemand einen Rat?

Vielen Dank für die Hilfe.

**Comment by jens-maus** [comment]
Sorry, but this is no support or discussion fora here. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. This was also already mentioned in the ticket template!
___
Tut mir leid, aber das hier ist kein Supportforum, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen.  Dies stand übrigens auch so im Ticket Template!
