### ISSUE TITLE
CuxD not working on Raspberry 1 Mod B

### ISSUE THREAD

**Issue by feli1** [jens-maus/RaspberryMatic#129]
after installing patch "github.com/jens-maus/RaspberryM ... ae3b2f2589" everything is running fine except CuxD.

**Comment by jens-maus** [comment]
This is not a bug in RaspberryMatic itself but with CUxD not providing binaries that can be used on the older "armv6" platform as well. See the following upstream bug report for this issue:

https://github.com/jens-maus/cuxd/issues/5
