### ISSUE TITLE
"Anzeige - Button" des Programmstatus unter Status und Bedienung > Programme > Aktion, umfunktionieren um damit das Programm aktiv/inaktiv zu schalten

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1292]
**Is your feature request related to a problem? Please describe.**
Der augenscheinliche Button "Aktiv" (unter Status und Bedienung > Programme > Aktion) der gar kein drückbarer Button ist könnte funktional sinnvoller genutzt werden. 
Momentan ist er als "drückbarer Butten" implementiert, ein Druck darauf bewirkt aber nichts. Er dient einzig zur Anzeige ob das zugehörige Programm aktiv...
![PRG_aktiv_inaktiv_Statusbutton](https://user-images.githubusercontent.com/54898249/121055151-4ed10680-c7bd-11eb-9cc7-69ba5fad38a7.JPG)
oder inaktiv ist...
![PRG_aktiv_inaktiv_Statusbutton_inaktiv](https://user-images.githubusercontent.com/54898249/121055220-5c868c00-c7bd-11eb-96d7-169e6e00f408.JPG)
 
**Describe the solution you'd like**
Mein Vorschlag wäre den Button als echten Button umzubauen der bei Druck auf selbigen den aktiv/inaktiv Status des zugehörigen Programms toggelt. Zusätzlich sollte die farbliche Unterlegung (passt schon) sowie der Statustext (passt nicht) dem aktuellen Programmstatus angepasst werden. 

**Describe alternatives you've considered**
Alternative A:
Wenn toggle aktiv/inaktiv des Programms mit einem Button nicht möglich ist könnte man auch 2 Schaltflächen implementieren (aktiv / inaktiv) welche den Staus des Programms einstellen und anzeigen.

Alternative B:
Alles so lassen wie es ist und nur die Haptik eines Buttons entfernen.

**Additional context**
Ich bin der Meinung: "Status und Bedienung" bedeutet auch das Programm zu bedienen, es also EIN/AUSschalten zu können.

Wird das wie im Feature-Request umgesetzt wäre auch hier ein zusätzlicher "Hilfe-Button" hilfreich welcher das Verhalten beim "aktivieren" beschreibt. Der Text könnte quasi der Selbe sein wie beim neuen "Ausführen-Button". (Es wird also das Programm getriggert mit Bedingungsprüfung und je nach "WAHRheitsgehalt" das entsprechende DANN oder SONST ausgeführt.)

**Comment by blackbasket** [comment]
Sofern technisch möglich, wäre ich für Variante A

**Comment by Baxxy13** [comment]
> wäre ich für Variante A

Variante A gibt's nicht. Aber ich weiß ja das du die Idee gut findest.  ;-)

**Comment by jp112sdl** [comment]
Meine Meinung: siehe https://github.com/jens-maus/RaspberryMatic/pull/1291#issuecomment-855988515


> Ich bin der Meinung: "Status und Bedienung" bedeutet auch das Programm zu bedienen, es also EIN/AUSschalten zu können.

Also darf das dann auch jeder Benutzer/Gast?
Weil ist ja ganz normale Bedienung?

Ich denke nicht, dass das erwünscht ist, dass Berechtigungen kleiner "Admin" sowas erlaubt wird.

Also wer auch immer das dann einbauen sollte:
Bitte daran denken, dass das (in)aktiv Schalten nur für Berechtigungsstufe "Admin" erlaubt sein darf.
Einstellungen/Änderungen an Programmen sind nur "Admin" gestattet.
_Dem Benutzer fehlt das Menü "Programme und Verknüpfungen" gänzlich._

**Comment by Baxxy13** [comment]
Sehr guter Einwand. Ich muss gestehen daß ich mich noch nie mit  den  Berechtigungsstufen  der unterschiedlichen Nutzer beschäftigt habe.  Das wäre dann in der Tat kritisch wenn ein Benutzer/Gast befähigt würde  Programme zu  aktivieren / deaktivieren.

**Comment by jens-maus** [comment]
> Also wer auch immer das dann einbauen sollte:
> Bitte daran denken, dass das (in)aktiv Schalten nur für Berechtigungsstufe "Admin" erlaubt sein darf.
> Einstellungen/Änderungen an Programmen sind nur "Admin" gestattet.
> _Dem Benutzer fehlt das Menü "Programme und Verknüpfungen" gänzlich._

Naja, so ganz strikt würde ich das nicht sehen. Das gesamte Benutzerverwaltungssystem in der WebUI ist ohnehin nonsense, denn ich kann hier dir gerne mal eine URL Zeile posten mit der du dich mit einer Benutzer- oder Gastsession selbstständig zu einem Admin machen kannst oder gar die gesamte Zentrale mit einem "system.Exec()" Remote Aufruf löschen lassen kannst. Deshalb habe ich eigentlich auch schon sehr lange auf der Agenda die gesamte Benutzerverwaltung wegzuschmeissen bzw. zumindest die Unterscheidung in Gast, Nutzer und Admin wegzumachen oder eben glasklare Warnungen auszugeben wenn man versucht einen Benutzer oder Gast anzulegen. Zumindest gehört auf jedenfall das Automatische Login Feature komplett weggeworfen IMHO weil das ein zu großes Sicherheitsrisiko darstellt. Nur hab ich mich bisher einfach nicht getraut weil ich den "Zorn" der vermeintlich Unbelehrbaren fürchte wenn dieses Feature plötzlich nicht mehr da ist. Fakt ist aber, das man besser darin beraten ist überhaupt keine Nutzer oder Gastzugänge einzurichten und sich auf einen Admin Zugang zu beschränken und den mit einem sicheren Passwort abzusichern. Das aber nur so nebenbei gesagt.

**Comment by blackbasket** [comment]
> Zumindest gehört auf jedenfall das Automatische Login Feature komplett weggeworfen IMHO weil das ein zu großes Sicherheitsrisiko darstellt. Nur hab ich mich bisher einfach nicht getraut weil ich den "Zorn" der vermeintlich Unbelehrbaren fürchte wenn dieses Feature plötzlich nicht mehr da ist. Fakt ist aber, das man besser darin beraten ist überhaupt keine Nutzer oder Gastzugänge einzurichten und sich auf einen Admin Zugang zu beschränken und den mit einem sicheren Passwort abzusichern. Das aber nur so nebenbei gesagt.
> 
> 

It's a bug, not a feature ;)

**Comment by jp112sdl** [comment]
Ist überhaupt die Frage, wie viel Energie man noch in die bisherige WebUI steckt...
Link: [HomeMatic und HomeAssistant - endlich die neue WebUI?](https://www.homematic-inside.de/blog/homematic-und-homeassistant-endlich-die-neue-webui)
🤷‍♂️☺️

**Comment by jens-maus** [comment]
> Ist überhaupt die Frage, wie viel Energie man noch in die bisherige WebUI steckt...
> Link: [HomeMatic und HomeAssistant - endlich die neue WebUI?](https://www.homematic-inside.de/blog/homematic-und-homeassistant-endlich-die-neue-webui)

Und hier meine Antwort darauf:
https://twitter.com/RaspberryMatic/status/1397651772483723271

Sehe das kritisch, dass hier wieder zweifelhafte kommerziell agierende Firmen versuchen auf den Zug aufzuspringen und sich bei der OpenSource/Hardware Community versuchen zu bedienen (RaspberryMatic als HomeMatic Addon in HA und dieses "PB-HULIP" als close hardware Projekt. In der Tat hatte ich die Idee HomeAssistant ggf. als zukünftige Basis zu verwenden schon von Anfang an. Aber das nur so nebenbei...

**Comment by Baxxy13** [comment]
Kurz drüber nachgedacht... 
wenn für weniger privilegierte Nutzer komplette Bereiche "ausgeblendet" werden ließe sich das sicher auch für den "toggle-Button" realisieren. Die Information ob ein Programm aktiv/inaktiv ist, ist ja für Benutzer eigentlich irrelevant.

**Comment by jp112sdl** [comment]
> wenn für weniger privilegierte Nutzer komplette Bereiche "ausgeblendet" werden ließe sich das sicher auch für den "toggle-Button" realisieren. Die Information ob ein Programm aktiv/inaktiv ist, ist ja für den Benutzer/Gast eigentlich irrelevant.

Natürlich. Muss halt nur beim Programmieren bedacht werden. Mehr wollte ich mit einem Einwand nicht zum Ausdruck bringen. :)

> Das gesamte Benutzerverwaltungssystem in der WebUI ist ohnehin nonsense, denn ich kann hier dir gerne mal eine URL Zeile posten mit der du dich mit einer Benutzer- oder Gastsession selbstständig zu einem Admin machen kannst oder gar die gesamte Zentrale mit einem "system.Exec()" Remote Aufruf löschen lassen kannst. 

Mag sein, wenn man es aus sicherheitskritischer Sicht ("die Hacker kommen") sieht.

Meine Frau kann jedenfalls als _Benutzer_ (und da ist sie auch glücklich drüber) nix versehentlich verfummeln und dennoch das System notfalls bedienen. Ist hier nur Fallback. Aber ich habe auch nicht-Admin-Konten eingerichtet.

**Comment by Baxxy13** [comment]
> Meine Frau kann jedenfalls als _Benutzer_ (und da ist sie auch glücklich drüber)

Meine hat dankend abgelehnt als sie die WebUI sah. Sie begnügt sich jetzt damit die Außenbeleuchtung unseres Ferienhäuschens per App zu schalten. Der Rest läuft quasi völlig autark und es sind selten Eingriffe in die Steuerung nötig. 
Demzufolge könnte ich auf Nutzerkonten mit geringeren Rechten verzichten.

An HA komme ich noch nicht so richtig ran, die Testversion lief einen Tag und das war's. Die Umstellung ist schon ziemlich groß, und solange CUxD nicht nutzbar ist, ist das für mich nicht relevant.

**Comment by jp112sdl** [comment]
> Meine hat dankend abgelehnt als sie die WebUI sah

Wie gesagt: Nur Fallback!

> Demzufolge könnte ich auf Nutzerkonten mit geringeren Rechten verzichten.

"_Ich_" zeigt in diesen Diskussionen halt immer wieder, wie vielfältig die Anwendungsszenarien sind ;)

**Comment by Maik2208** [comment]
Interessante Idee!
Habt ihr euch schon für Variante a oder b entschieden und wer es umsetzt?

Variante a habe ich eben in abgewandelter Form für mich gebaut. Wenn Interesse besteht, stelle ich es gerne zur Verfügung. Dass der Mauszeiger jetzt beim linken Knopf ein normaler Pfeil ist, sieht man leider auf dem Bild nicht:
![image](https://user-images.githubusercontent.com/79879510/124197909-da456b00-dacf-11eb-86a0-aeb798e16559.png)

Natürlich kann man das auch mit Variante b kombinieren. Dass ein normaler User diese Ansicht bekommt und ein Admin togglen kann.

**Comment by Baxxy13** [comment]
> Habt ihr euch schon für Variante a oder b entschieden und wer es umsetzt?

Weder noch. Aber mach doch mal eine Aufnahme mit GifCam (oder ähnlichem) das man das mal "live" sieht.

**Comment by Maik2208** [comment]
Mich hatte in der Nacht noch der große Ehrgeiz gepackt und es mich noch umsetzen lassen.

Also Stand bei mir:
aktive und nicht aktive Programme erhalten unterschiedliche Texte, wie auf dem Bild zu sehen. Gast und Benutzer haben einen normalen Mauszeiger und die Schaltfläche ist tot. Der Admin behält nach wie vor den Pointer/Finger und kann togglen.

Hier brauche ich nochmal etwas Hilfe, wie ich mit JS an den aktuellen Programmstatus komme. Aktuell behelfe ich mir mit einer Variable, die den aktuellen Status mithält.

Die Giffunktion schaue ich mir mal an.

**Comment by Maik2208** [comment]
Admin:
![Admin_Toggle](https://user-images.githubusercontent.com/79879510/124260692-45268e80-db30-11eb-901a-6ba09780715f.gif)

Benutzer:
![non_admin](https://user-images.githubusercontent.com/79879510/124260714-4a83d900-db30-11eb-8e51-b84c5376e109.gif)


Codeschnippsel:
```JS
--- /www/rega/esp/system.fn.orig
+++ /www/rega/esp/system.fn
@@ -1260,6 +1260,7 @@
 {
   integer pid = system.GetVar("progId");
   object objProg = dom.GetObject(pid);
+
   if( system.GetVar("iStatusOnly") == 1 )
   {
     Write("<table class='viewTbl CLASS02100' border='0' >");
@@ -1274,7 +1275,17 @@
   Write("<td>");
   string sClass = "ControlBtnOff";
   if( objProg.Active() ) { sClass = "ControlBtnOn"; }
-    Write("<table class='"#sClass#" CLASS02102' id='"#pid#"Act' >"); 
+  
+  integer uid = system.GetSessionVar("sessionUserID");
+  object oUser = dom.GetObject( uid );
+  if(oUser.UserLevel() == iulAdmin){
+    Write("<script type='text/javascript'>");
+    Write("IsActive_" #pid# " = " #objProg.Active() #";");
+    Write("</script>");
+    Write("<table class='"#sClass#" CLASS02102' id='"#pid#"Act' onclick='IsActive_" #pid# " = !IsActive_" #pid# ";isePrograms.SetActive("#pid#",IsActive_" #pid# ")'>"); 
+  }else{
+    Write("<table class='"#sClass#" CLASS02102 CURSOR_DEFAULT' id='"#pid#"Act'>"); 
+  }
     Write("<tr>");
     Write("<td  class='CLASS02103'>");
         Write("<div align='center'>");
@@ -1283,7 +1294,11 @@
       Write("</td>");
     Write("</tr>");
     !Write("<tr><td>Aktiv</td></tr>");
-    Write("<tr><td>${actionStatusControlLblActive}</td></tr>");
+    if( objProg.Active() ) {
+       Write("<tr><td>${actionStatusControlLblActive}</td></tr>");
+    }else{
+       Write("<tr><td>${actionStatusControlLblNotActive}</td></tr>");
+    }
     Write("</table>");
   Write("</td>");
   if (system.GetVar("iStatusOnly") == 0)



--- /www/webui/style.css.orig
+++ /www/webui/style.css
@@ -835,6 +835,10 @@
   cursor: pointer;
 }
 
+.CURSOR_DEFAULT {
+	cursor: default !IMPORTANT;
+}
+
 .PercBtn {
   background-color: $_(clickable); 
   color: $_(textColorA); `


--- /www/webui/js/lang/de/translate.lang.js.orig
+++ /www/webui/js/lang/de/translate.lang.js
@@ -785,7 +786,8 @@
     "dialogBackspacePrevent" : "Bitte verwenden Sie zum Navigieren die Bedienelemente der Weboberfl%E4che.",
     "commentDialogNewHelpEnd" : "***********************************************",
     "commentActionStatusControl" : "***********************************************",
-    "actionStatusControlLblActive" : "Aktiv",
+    "actionStatusControlLblActive" : "aktiv",
+    "actionStatusControlLblNotActive" : "nicht aktiv",
     "actionStatusControlLblStart" : "Start",
     "actionStatusControlLblOn" : "Ein",
     "actionStatusControlLblOff" : "Aus",


--- /www/webui/js/lang/en/translate.lang.js.orig
+++ /www/webui/js/lang/en/translate.lang.js
@@ -812,7 +813,8 @@
 
     "commentActionStatusControl" : "***********************************************",
 
-    "actionStatusControlLblActive" : "Active",
+    "actionStatusControlLblActive" : "active",
+    "actionStatusControlLblNotActive" : "not active",
     "actionStatusControlLblStart" : "Start",
     "actionStatusControlLblOn" : "On",
     "actionStatusControlLblOff" : "Off",

**Comment by Baxxy13** [comment]
Na das sieht doch schon sehr gut aus. Genau wie in meiner Vorstellung zu dieser Idee. 
Und das auch gleich noch zwischen Admin und Normalnutzer unterschieden wird... perfekt.

> Hier brauche ich nochmal etwas Hilfe, wie ich mit JS an den aktuellen Programmstatus komme. Aktuell behelfe ich mir mit einer Variable, die den aktuellen Status mithält.

Da kann ich leider nicht helfen. Vielleicht haben @jp112sdl oder @jens-maus Ideen dazu.

In der kommenden RM sieht der Bereich auch etwas anders aus, ich weiß daher nicht ob ein Patch für die jetzige Version auch mit der neuen funktionieren würde. 
![RM_WebUI_Programme](https://user-images.githubusercontent.com/54898249/124264965-6ccc2580-db35-11eb-9866-6844d86ab09d.JPG)

**Comment by Maik2208** [comment]
Wenn ich jetzt noch wüsste, was mich letzte Nacht dazu verleitet hatte das mit JS-Variablen zu lösen...
Die Seite wird doch jedes mal neu geladen, da kann ich den Wert auch direkt in die Funktion knallen:

```JS
--- /www/rega/esp/system.fn.orig
+++ /www/rega/esp/system.fn
@@ -1260,6 +1260,7 @@
 {
   integer pid = system.GetVar("progId");
   object objProg = dom.GetObject(pid);
+
   if( system.GetVar("iStatusOnly") == 1 )
   {
     Write("<table class='viewTbl CLASS02100' border='0' >");
@@ -1274,7 +1275,14 @@
   Write("<td>");
   string sClass = "ControlBtnOff";
   if( objProg.Active() ) { sClass = "ControlBtnOn"; }
-    Write("<table class='"#sClass#" CLASS02102' id='"#pid#"Act' >"); 
+  
+  integer uid = system.GetSessionVar("sessionUserID");
+  object oUser = dom.GetObject( uid );
+  if(oUser.UserLevel() == iulAdmin){
+    Write("<table class='"#sClass#" CLASS02102' id='"#pid#"Act' onclick='isePrograms.SetActive("#pid#",!" #objProg.Active() # ")'>"); 
+  }else{
+    Write("<table class='"#sClass#" CLASS02102 CURSOR_DEFAULT' id='"#pid#"Act'>"); 
+  }
     Write("<tr>");
     Write("<td  class='CLASS02103'>");
         Write("<div align='center'>");
@@ -1283,7 +1291,11 @@
       Write("</td>");
     Write("</tr>");
     !Write("<tr><td>Aktiv</td></tr>");
-    Write("<tr><td>${actionStatusControlLblActive}</td></tr>");
+    if( objProg.Active() ) {
+       Write("<tr><td>${actionStatusControlLblActive}</td></tr>");
+    }else{
+       Write("<tr><td>${actionStatusControlLblNotActive}</td></tr>");
+    }
     Write("</table>");
   Write("</td>");
   if (system.GetVar("iStatusOnly") == 0)

**Comment by jens-maus** [comment]
Ok, ich hab die von @Maik2208 vorgeschlagenen Änderungen nun mal umgesetzt und kurz getestet. Sieht für mich soweit i.O. aus. Habe es daher integriert und somit wird es teil des nächsten Snapshots sein. Danke nochmal für die Unterstützung!

**Comment by Baxxy13** [comment]
So nun konnte ich mir das auf meinem Testsystem Live angucken und testen.
Sehr gut implementiert und umgesetzt, man könnte denken das war / muss schon immer so.

Vielen Dank an @Maik2208 für die Umsetzung der Idee und an @jens-maus für's implementieren!
