### ISSUE TITLE
Keine Geräte mit im WebGUI nach Upgrade auf 	3.57.5.20210525

### ISSUE THREAD

**Issue by dirk99** [jens-maus/RaspberryMatic#1295]
Ich habe nach dem Update keine Geräte mehr in der Anzeige Einstellungen/Geräte. Die HM funktioniert sonst einwandfrei. Die Geräte sind alle vorhanden, wie ich unter Status/Geräte sehen kann. 

welche Logs bzw. Configfiles helfen bei der Fehlersuche?

Vielen Dank im Voraus 
Dirk

**Comment by jens-maus** [comment]
Sorry, but this is no support or discussion fora here. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. This was also already mentioned in the ticket template!
___
Tut mir leid, aber das hier ist kein Supportforum, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen.  Dies stand übrigens auch so im Ticket Template!
