### ISSUE TITLE
CCU3 hängt sich häufig auf

### ISSUE THREAD

**Issue by uwiuke** [jens-maus/RaspberryMatic#1297]
**Describe the bug**
... die CCU3 „hängt“ sich (nach zuvor wochenlangem problemlosen Agieren) regelmässig alle 1-4 Tage auf, sodaß auch ein Zugang nicht mehr möglich ist (WebUI).
Programme und restliche Einstellungen werden seit Wochen nicht mehr durchgeführt (also unveränderter Zustand).

**Steps to reproduce the behavior**
1. ...im Moment kann ich keine Reproduzierung ausmachen
2. ...was kann ich tun, damit ich die Fehlerursache erkennen kann; die LOG-Datei habe ich angehängt
3. ...
4. ...

**Expected behavior**
... fehlerfreies dauerhaftes Agieren.

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: ...3.57.5.20210525
 - Used Hardware: ...CCU3 von ElV
 - Used HomeMatic RF-Module: ...

**Additional context**
...
[ccu3-webui-2021-06-11.log](https://github.com/jens-maus/RaspberryMatic/files/6636123/ccu3-webui-2021-06-11.log)

**Comment by jens-maus** [comment]
Sorry, but this is no support or discussion fora here. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. This was also already mentioned in the ticket template!
___
Tut mir leid, aber das hier ist kein Supportforum, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen.  Dies stand übrigens auch so im Ticket Template!
