### ISSUE TITLE
Aktuelle Firmware lässt sich nicht auf einer CCU3 installieren

### ISSUE THREAD

**Issue by Soc007** [jens-maus/RaspberryMatic#1299]
Hallo Jens,

ich versuche von der Firmware 3.57.5.20210424 auf 3.57.5.20210525 zu wechseln und der Upload scheint zu hängen (direkte Installation sowie auch hochladen).
Die rote LED ist ständig an und blinkt teilweise vor sich hin.
Das geht so lange, bis ich den Stecker der CCU3 ziehe und neu starte.

Kannst Du mir schreiben wie ich da bei der Fehleranalyse vorgehen kann?

Danke und Gruß

Soc007

**Comment by jens-maus** [comment]
Sorry, but this is no support or discussion fora here. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. This was also already mentioned in the ticket template!
___
Tut mir leid, aber das hier ist kein Supportforum, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen.  Dies stand übrigens auch so im Ticket Template!
