### ISSUE TITLE
"Virtual Device not Working" error message

### ISSUE THREAD

**Issue by tobiasw83** [jens-maus/RaspberryMatic#130]
Shortly after the start of the CCU, the error message Virtual Device does not respond every time. Have already installed the latest software version and another SD card taken. Someone a hint?

Tobias

**Comment by HMside** [comment]
Perhaps an old CUxD version? This is not an general issue for more help use the homematic-forum.de

**Comment by tobiasw83** [comment]
Hi unfortunately can not help me there. Have the version 1.10b of cuxd.

**Comment by jens-maus** [comment]
Please provide more information. Which RaspberryMatic version, which hardware, does the error already appear in a clean installation or just after you have uploaded your backup? Please also monitor error output in `/var/log/hmserver.log` and report any errors here.

**Comment by happycrack1277** [comment]
I have the same error message on a clean installation, Version 2.29.18.20170731 on a RasPi 2 Modell B with LAN-Gateway.

In the hmserver.log every 7 minutes the following errors appear:
>Aug 2 07:34:00 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-0] SYSTEM ADVICE: long-lasting deployment, check deployment configuration - currently deployed 16 out of 18
>Aug 2 07:34:00 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-4] SYSTEM ADVICE: pre-conditions for deployment of LocalServerFirmwareUpdateInitialization still not met - check deployment configuration  (still unfulfilled: [connector.open])
>Aug 2 07:34:00 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-1] SYSTEM ADVICE: pre-conditions for deployment of LegacyInitializion still not met - check deployment configuration  (still unfulfilled: [connector.open])

Also some pages in the UI are blank. At every time I select these pages the following errors appear in the lighttpd-error.log:
>2017-08-02 12:22:36: (mod_proxy.c.1041) establishing connection failed: Connection refused
>2017-08-02 12:22:36: (mod_proxy.c.1153) proxy-server disabled: 127.0.0.1 9292 13
>2017-08-02 12:22:36: (mod_proxy.c.523) no proxy-handler found for: /pages/jpages/group/list
>2017-08-02 12:22:41: (mod_proxy.c.1417) proxy - re-enabled: 127.0.0.1 9292
>2017-08-02 12:23:29: (mod_proxy.c.1041) establishing connection failed: Connection refused
>2017-08-02 12:23:29: (mod_proxy.c.1153) proxy-server disabled: 127.0.0.1 9292 13
>2017-08-02 12:23:29: (mod_proxy.c.523) no proxy-handler found for: /pages/jpages/system/Coupling/show
>2017-08-02 12:23:34: (mod_proxy.c.1417) proxy - re-enabled: 127.0.0.1 9292
>2017-08-02 12:24:32: (mod_proxy.c.1041) establishing connection failed: Connection refused
>2017-08-02 12:24:32: (mod_proxy.c.1153) proxy-server disabled: 127.0.0.1 9292 13
>2017-08-02 12:24:32: (mod_proxy.c.523) no proxy-handler found for: /pages/jpages/devicefirmware
>2017-08-02 12:24:37: (mod_proxy.c.1417) proxy - re-enabled: 127.0.0.1 9292
