### ISSUE TITLE
Alle HMIP Geräte nach Update 3.57.5.20210525 mit Verbindungsstörung

### ISSUE THREAD

**Issue by osti1** [jens-maus/RaspberryMatic#1305]
**Describe the bug**
Nach gestrigen Update auf Version 3.57.5.20210525 haben alle HMIP ihre Verbindung verloren (Duty cycle liegt bei 1-3%). Da ich bereits mehrere Updates durchgeführt habe und bisher nie ein Problem gehabt habe, wollte ich kurz fragen, ob das Problem bei mehreren aufgetreten ist oder ein Problem meinerseits ist.

**Steps to reproduce the behavior**
1. Reboot
2. Power-on/off
3. Replace battery of the HMIP component
4. ...

**Expected behavior**
...

**Screenshots**
...
![grafik](https://user-images.githubusercontent.com/85924606/122253186-3a32f380-cecc-11eb-8841-84638b056656.png)

**System information:**
 - RaspberryMatic Version: 3.57.5.20210525
 - Used Hardware: Tinterboard
 - Used HomeMatic RF-Module: ...

**Additional context**
...

**Comment by otwien** [comment]
Bei mir das gleich problem. Duty cycle bei 1-2% und cs bei 40 %. habe nur HM-IPBroll und HmIP-SRH im einsatz. vorher ohne probleme und jetzt dauernd Gerätekomunikation gestört.

**Comment by jens-maus** [comment]
Ein generelles/allgemeines Problem kann das nicht sein, sonst wäre der Aufschrei bzw. die Problemlage größer. Wenn der CarrierSense natürlich auf 40% geht ist es teilweise nicht verwunderlich das es Kommunikationsstörungen gibt. Ein systematische Probleme sehe ich hier jedoch weiterhin nicht.

**Comment by fant42** [comment]
Ich habe ebenfalls sehr deutliche Verbindungsprobleme. Einige meiner Wired-IP-Gerät kann ich durch die Wandknöpfe nicht mehr ansprechen. Im Web-Interface gehen einige Rolläden, andere gehen nicht. Ich habe gleichzeitig auch den DRAC upgedatet. Vielleicht liegt es auch daran. Im Moment ist das System extrem unzuverlässig.
Die Rolladen-Funk-Aktoren mit und ohne IP scheinen zu funktionieren, ebenso die Fensterriegel-Sensoren.

**Comment by jens-maus** [comment]
Bitte hier nicht anfangen Dinge miteinander zu vermengen nur weil einem das Subject des Issue Tickets vielleicht gut zu seinem eigenen Problem passt. Verbindungsprobleme können vielfältig sein und verschiedene Ursachen. Sehe hier trotzdem weiterhin kein generelles/grundlegendes Problem - vor allem keins das im Rahmen der RaspberryMatic Entwicklung gelöst werden könnte. Wie gesagt, das ganze läuft auf zehntausenden Systemen und davon auf >98% der Systeme inkl. meins wohl tadellos. Wenn es da also etwas grundsätzliches geben würde dann müsste es bei >98% nicht laufen. Das ist aber nicht der Fall. Insofern bleibt es bei "worksforme" solange es hier keine weiteren technischen Erkenntnisse gibt ausser der Wahrnehmung das es irgendwelche Kommunikationsstörungen gibt die eben wie gesagt verschiedene Ursachen haben können.
