### ISSUE TITLE
Kanalaktion mit Einschaltdauer 31 Minuten nicht möglich

### ISSUE THREAD

**Issue by Maik2208** [jens-maus/RaspberryMatic#1306]
**Describe the bug**
Es ist nicht möglich, in einem Programm für einen Kanal eine Kanalaktion mit 31 Minuten Laufzeit zu hinterlegen. Der Kanal wird dann dauerhaft auf diesen Wert gesetzt. Laut Doku bedeuten aber 31 Stunden dauerhaft!

**Steps to reproduce the behavior**
1. Programm anlegen
2. einen Kanal eines Gerätes auswählen
3. Kanalaktion auswählen
4. Einschaltdauer auf 31 Minuten begrenzen

**Expected behavior**

**Screenshots**
Bitte nicht von der Programmbedingung irritieren lassen - war nur, damit das Testprogramm nicht meinen Garten absaufen lässt :-)

31 Minuten in den Kanalaktionen hinterlegen:
![image](https://user-images.githubusercontent.com/79879510/122370319-43b96b80-cf5f-11eb-9f08-f6cf69dbc837.png)

Ergibt dauerhafte Laufzeit:
![image](https://user-images.githubusercontent.com/79879510/122370423-56cc3b80-cf5f-11eb-8146-8a2c13ef091e.png)

1860 Sekunden hingegen
![image](https://user-images.githubusercontent.com/79879510/122370459-5cc21c80-cf5f-11eb-86e1-1319029a483d.png)

funktionieren
![image](https://user-images.githubusercontent.com/79879510/122370483-6186d080-cf5f-11eb-9d74-a2e8410441ef.png)

**System information:**
 - RaspberryMatic Version: 3.57.5.20210525
 - Used Hardware: RPi 3
 - Used HomeMatic RF-Module:  RPI-RF-MOD

**Additional context**
...

**Comment by jens-maus** [comment]
Bitte Beispiele zeigen MIT screenshots usw. und bitte detaillierter ausführen was genau gemeint ist. Auch fehlt der Eintrag von "Used Hardware" und "Used RF-Module" usw.

**Comment by Maik2208** [comment]
Sorry, habe die gewünschten Infos oben ergänzt.

**Comment by jens-maus** [comment]
Danke für die Ergänzung. Aber mal abgesehen von dem Problem hier: Sowas sollte man IMHO besser über eine Direktverknüpfung zwischen einem virtuellen HmIP-Taster und dem HmIPW-DRS erledigen und nicht in der Art in einem WebUI Programm die Parameter setzen lassen.

**Comment by jens-maus** [comment]
Ok, kann das Problem bestätigen. Scheint (mal wieder) ein reines WebUI Problem zu sein. Sieht man auch oben in den Screenshots, das er trotz Auswahl von 31 Minuten dort nicht ein `OT=1860` anhängt, sondern dann lediglich ein `S=true` im Feld landet. Insofern ist der Workaround via eingabe von `1860` vollkommen richtig. Nichts anderes würde passieren wenn das mit Eingabe von 31 Minuten klappen würde. Sieht man ja auch wenn man 30 Minuten mal zum testen angibt, dann landet da `OT=1800`, d.h. er rechnet da immer in Sekunden um.

@Maik2208 Es bleibt aber dabei: Praktisch erledigt man sowas via Direktverknüpfungen mit einem virtuellen Kanal und nicht via solcher einzelnen Kanalparameterzuweisungen in einem WebUI Programm.

**Comment by Maik2208** [comment]
@jens-maus 
Danke für's Kümmern und für den Hinweis auf die Direktverknüpfung. Diese habe ich tatsächlich bisher nur verwendet, wenn zwei Geräte miteinander kommunizieren sollten. Das Thema virtuelle Taster, welchen Einfluss das auf Retriggern hat etc. schaue ich mir mal an. Das ist Neuland für mich.

**Comment by jens-maus** [comment]
So, hab das Problem in dem Auswahldialog gefunden und repariert. Hier wurde versäumt bei dem Check nach "31" nur dann diese überprüfung zu machen wenn die Einheit auch auf Stunden gestellt war. Ab der nächsten Version sollte es also behoben sein.
