### ISSUE TITLE
HmIP-FROLL Positionierung

### ISSUE THREAD

**Issue by theimo1221** [jens-maus/RaspberryMatic#1308]
**Describe the bug**
After configuring timingsfor up/down, setting value to 50% in devices Tab results in driving to bottom/top.

Personally I think there might be an issue with the integer value taking 0.5 as the value.

**Steps to reproduce the behavior**
1. Wire an HMIP-FROLL
2. Measure Timings for up/down
3. Configure Timings in device settings
4. Move it completely down then up
5. Set it to 50% in Device Tab
6. Watch Roll ending in end position

**Expected behavior**
With the given time of 15s to reach bottom. Entering 50% should result in roll stopping after 7.5s coming from being completly up

**Screenshots**
  "![image](https://user-images.githubusercontent.com/20605452/122394739-98b4ac00-cf76-11eb-8aa8-339076cbec5b.png)" 

**System information:**
 - RaspberryMatic Version: 3.57.5.20210525
 - Used Hardware: Proxmox

**Comment by jens-maus** [comment]
Can you please provide a screenshot or screencast demonstrating the issue. That would really help. Clearly, this `integer iState = '0.5'` looks awkward, but still be need to identify the root cause here. And for this (since I don't have a HmIP-FROLL installed) it would good to see that issue in some kind of screencast or something like that.

**Comment by theimo1221** [comment]
![image](https://user-images.githubusercontent.com/20605452/122401776-327f5780-cf7d-11eb-8607-a368931adc1b.png)
I'm sorry Jens.

Even though it looked akward I found the reason:
Setting the checkbox resulted in the measurement of 12.7s for delayed motor start 🤦 

As my motors almost immediatly grip (I don't see/hear a delay) setting it to manual and 0s resolved it....

**Comment by jens-maus** [comment]
Thanks @theimo1221 for clearing it up. However, the `integer iState = '0.5'` in your screenshot still looks strange and should not happen / is invalid. If you can replicate/analyse that under which circumstances this happens we could potentially still squash another bug here...

**Comment by theimo1221** [comment]
`<prototypejs><![CDATA[string%20action%20%3D%20%27setDpState%27%3Binteger%20dpid%20%3D%209167%3Binteger%20iState%20%3D%20%270.5%27%3B]]></prototypejs>`

This is the url encoded Form Data send doing the following:

1. Go to Status --> Devices
2. Open a HmIp FROLL
3. Set Level to e.g. 50%
4. See request in network tab of browser

**Comment by jens-maus** [comment]
Ok danke. Ich denke, ich kann aber Entwarnung bzgl. des `integer iState = '0.5'` geben. Erst dachte ich, dass wäre Javascript an der Stelle. Aber dabei handelt es sich um ReGa-Skript Anweisungen. Und auch wenn es unschön aussieht und man meint das integer und 0.5 sich beisst, so passt das für die ReGa-Skriptsprache aber weil die variablen da variable typisierung haben. D.h. er wandelt dann automatisch das 0.5 in ein float um. Passt also alles soweit.
