### ISSUE TITLE
Einspielen eines Backup aus YAHM 

### ISSUE THREAD

**Issue by jp112sdl** [jens-maus/RaspberryMatic#131]
Wer von YAHM mit aktiviertem hm-mod-rpi-pcb Modul zu RaspberryMatic wechselt hat ein Problem.
Nach dem Einspielen eines Backups bleibt die Initialisierung von HMIPServer "stehen" (16 von 18 Threads) und es erscheint im hmserver.log auch nicht die Ausgabe von der Kommunikation mit dem TRX Adapter (de.eq3.cbcs.server.local.base.internal.HMIPTRXInitialResponseListener INFO).

2 Ursachen kommen m.E. in Frage:

1.) Der Parameter in der rfd.conf
`Improved Coprocessor Initialization = false`

Die multimacd.conf liegt ja bereits unter /var/... entgegen des "üblichen" init.d-Skripts der CCU2.

**Wäre es möglich, auch die rfd.conf an einen anderen Ort zu verschieben, so dass eine aus einem Backup eingespielte Version keine Beachtung findet?**

2.) Das Vorhandensein der Datei `/etc/config/no-coprocessor-update`

Hier ist es fraglich, wie man das Einspielen dieser Datei verhindert.

Als persönlichen "Notfall"-Workaround würde ich in YAHM die Datei no-coprocessor-update und rfd.conf unmittelbar vor Erstellen eines Backups umbenennen, damit diese gar nicht erst (mit Originalbezeichnung) ins Backup-File fließen.

Eine andere Möglichkeit wäre das Entpacken und "Ent-Taren" des usr_local Archivs im Backup, Entfernen der Dateien und erneutes Packen.
Das hat bei der originalen CCU2 schon erfolgreich geklappt, in RaspberryMatic leider nicht. 
Die Datei wurde dann nicht mehr als gültiges Backup erkannt. Vielleicht habe aber auch ich dabei einen Fehler gemacht und werde diese Möglichkeit noch mal näher betrachten.

**Comment by jens-maus** [comment]
Danke für die Hinweise. Ich denke aber das dies im Grunde  von YAHM geschaffene probleme sind. YAHM sollte z.b. Meiner Meinung nach die no-coprocessor-updates datei beim backup erstellen nicht mit einbeziehen wenn es diese datei selbst hinzufügt und das der nutzer nicht aktiv getan hat. Das selbe gilt meiner Meinung nach für die andere Sache. Insofern würde ich dies an das YAHM Projekt weiterleiten...

**Comment by jp112sdl** [comment]
Da ich in Kürze kein HomeMatic mehr einsetzen werde, kann der Issue hier meinetwegen zu.
