### ISSUE TITLE
WebUI: SysVar of type STRING with more than one consecutive space characters in its value is shown trimmed

### ISSUE THREAD

**Issue by jp112sdl** [jens-maus/RaspberryMatic#1310]
**Describe the bug**
If value of a system variable contains more than one space characters in a row, there's only one space characters shown in "Status und Bedienung" -> "Systemvariablen"

https://homematic-forum.de/forum/viewtopic.php?p=667763#p667762

<img width="421" alt="Bildschirmfoto 2021-06-19 um 20 41 21" src="https://user-images.githubusercontent.com/18190139/122655074-0cf67780-d150-11eb-954b-e599c2419330.png">

**Steps to reproduce the behavior**
1. Fill a system variable with a string containing more than one consecutive space characters
<img width="492" alt="Bildschirmfoto 2021-06-19 um 20 41 02" src="https://user-images.githubusercontent.com/18190139/122655042-c6a11880-d14f-11eb-801a-dd2f11a5dd3e.png">

**Expected behavior**
<img width="529" alt="Bildschirmfoto 2021-06-19 um 20 56 48" src="https://user-images.githubusercontent.com/18190139/122655053-dae51580-d14f-11eb-9fe8-3e6ac6af1113.png">

**Screenshots**

**System information:**
 - RaspberryMatic Version: 3.57.5.20210525

**Comment by ckoecher** [comment]
Apparently, this bug fix destroys HTML in variables. For example, I use HTML to display some statistics on the index page. One variable contains the following code
`</div><img src="/addons/figures/temperature.png" width="420" vspace="10" hspace="0" alt="pic">`
Firefox and Chrome do not display anything, but in the development tools one can find the following code:
`</div><img&nbsp;src=" addons="" figures="" temperature.png"&nbsp;width="420&nbsp;vspace=10&nbsp;hspace=0&nbsp;alt=pic">

</img&nbsp;src=">`

**Comment by jp112sdl** [comment]
Pls have a look at my notes at https://github.com/jens-maus/RaspberryMatic/commit/6bae3a0dc861d5bd4ae312f6f02ce2352def7976#r53018096

**Comment by ckoecher** [comment]
I've answered your note a while ago, but until now, there was no reaction. Maybe someone could reopen this ticket?

**Comment by jens-maus** [comment]
Well, before Incan do this we need to know how to proceed here. What is your proposal to solve your issue other than simply reverting the change which itself tried to fix another issue.

**Comment by ckoecher** [comment]
As proposed by @jp112sdl we should only replace multiple consecutive spaces by `&nbsp;&nbsp;`. A possible solution can be found in https://github.com/jens-maus/RaspberryMatic/commit/6bae3a0dc861d5bd4ae312f6f02ce2352def7976#r53025727
However, I'm still unable to test this patch (My RasPi 4 does not start with a self-compiled RaspiMatic and I don't know why, yet.)
