### ISSUE TITLE
enhance net-snmp build options

### ISSUE THREAD

**Issue by cactus-online** [jens-maus/RaspberryMatic#1312]
Hi Jens,

extension of snmp capabilities would be much easier with the extend mib module. Please add
`BR2_PACKAGE_NETSNMP_WITH_MIB_MODULES` `agent/extend` to the build options.

Thank you very much.

**Comment by jens-maus** [comment]
Thanks for the suggestion. Do you also have other potentially useful MIB modules in mind that I could also add to the SNMPD options?

**Comment by cactus-online** [comment]
The extend MIB is powerfull. I'll do further extensions for snmp with one of next version of RaspberryMatic. Because there is no own MIB for the Raspberry hardware, therefore now included MIBs might be sufficient.
I'm running RaspberryMatic on Raspberry 3 and will install a VM too for checking the virt parts of MIB. I'm using LibreNMS/Observium as NMS. This needs for example a file /etc/os-release with a content like this

```
PRETTY_NAME="RaspberryMatic 3.57.5.20210525"
NAME=RaspberryMatic
VERSION=<version, eg. 3.57.5.20210525>
ID=buildroot
ID_LIKE=<if it make sense, eg. debian/raspberrymatic/...>
VERSION_ID=<id, eg.2021.02.2>
HOME_URL="https://raspberrymatic.de/"
SUPPORT_URL="https://homematic-forum.de/forum/viewforum.php?f=65"
```
This system likes also a file called /usr/bin/distro from 
curl -o /usr/bin/distro https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/distro.
