### ISSUE TITLE
Watchdog-Alarm für schreibgeschütztes (möglicherweise defektes?) USB-Speichermedium integrieren

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1320]
**Is your feature request related to a problem? Please describe.**
Im Homematic Forum hatte ich es heute mit einem User zu tun dessen angestöpselter USB-Stick augenscheinlich defekt wurde und dadurch nur noch read-only im System zur Verfügung stand. Er hat irgendwann bemerkt das was nicht stimmt und den Stick getauscht. Der Haken an der Sache... der Stick war scheinbar schon 2 Monate defekt und nun fehlen ihm diese 2 Monate in der Historian Datenbank (und sicherlich auch Backups) da auch diese nicht mehr weiter beschrieben werden konnte.  Sowas kann natürlich immer mal passieren, ärgerlich ist es aber allemal.

Jetzt habe ich selbst mal eine SD-Karte im USB-Adapter als usb0 mit ro gemountet und musste feststellen das es RaspberryMatic überhaupt nicht juckt. Der externe Speicher wird mit "Status: externer Speicher vorhanden" angezeigt und gut ist. Selbst beim Backup-Cronjob kommt keinerlei Meldung das eine Speicherung nicht möglich ist. (OK, stimmt nicht ganz... manuell ausgeführt wird korrekt gemeckert...
```
root@homematic-raspi:~# /bin/cronBackup.sh
mkdir: can't create directory '/media/usb0/backup': Read-only file system
```

**Describe the solution you'd like**
Aus meiner Sicht wäre ein Watchdog sinnvoll der ein angeschlossenes Speichermedium zyklisch (oder zumindest beim Systemstart) prüft und Alarm schlägt sollte das Medium als ro eingebunden sein

**Describe alternatives you've considered**
Mann könnte auch cronBackup.sh um eine Fehlerrückgabe erweitern welche dann eine Alarmmeldung generiert mit dem Hinweis das das Backup fehlgeschlagen ist und das Speichermedium möglicherweise Probleme hat 

**Additional context**
Interessanterweise musste ich das Speichermedium händisch ro mounten, der "Lock"-Schiebeschalter der SD-Karte wurde einfach ignoriert.

**Comment by jens-maus** [comment]
@Baxxy13 wäre schön du könntest diese neue Feature bitte ausführlich testen

**Comment by Baxxy13** [comment]
Morgen Jens...
Danke für die schnelle Umsetzung. 
Es funktioniert sehr gut. Wechsel von `ro` zu `rw` (und umgedreht) sowie fehlgeschlagene Backups werden sauber alarmiert.

Nicht testen konnte ich ob ein (gleich bei Zentralenstart) als `ro` eingebundenes Speichermedium detektiert wird. Da weiß ich gerade nicht wo ich da ansetzen müsste. (Der physische Schreibschutz-Schalter der SD-Karte wird ja ignoriert)

Auf jeden Fall sollte das Usern mit runtergewirtschafteten Speichermedien helfen Probleme rechtzeitig zu erkennen. 
Sehr gut!
