### ISSUE TITLE
Kategorisierte WatchDog-Alarme

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1321]
**Is your feature request related to a problem? Please describe.**
Bei meinen Test's heute morgen zu den 2 neuen Watchdog-Alarmen fiel mir auf das es ja tatsächlich nur einen WatchDog-Alarm gibt, der aber jeweils eine angepasste Beschreibung enthält. Entstehen also mehrere WatchDog-Alarme sieht man das zwar an der "Anzahl der Auslösungen", was es aber war sieht man nicht mehr da die Beschreibung nur die des letzten Alarmes ist. Das finde ich etwas "unschön" gelöst. 

ein (nicht ganz Ernst gemeintes) Beispiel:
Der Backup CronJob schlägt fehl, es wird alarmiert. Bekommt erstmal keiner mit, ist ja zur Schlafenszeit. Etwas später fällt das Internet aus, es wird alarmiert, der Zähler geht auf 2. Bekommt auch keiner mit, wir schlafen immer noch. Der frühaufstehende Teenie schmeißt sein Schlafgewand genau auf die Zentrale, diese wird heiß, es wird alarmiert und der Zähler geht auf 3. 
Wir wachen auf, räumen die Teenie-Sachen weg und sehen die rote LED blinken.  Gucken uns dann die Alarmliste an, sehen... ok Zentrale heißgelaufen (3x ???), nehmen's mit einem Lächeln und drücken beherzt auf "Bestätigen"
Die beiden anderen Alarme gehen somit "unentdeckt" an uns vorbei (außer wir gucken ins Logfile) 

**Describe the solution you'd like**
Ich würde es gut finden wenn es mehrere WatchDog-Alarm Kategorien geben würde. Vielleicht 3 in denen passende Alarme zusammengefasst sind. Als erste Überlegung... 

- "Zentrale" mit Alarmen für Dateisystem, Temperatur, CPU usw.
- "Funk" mit DutyCycle, CarrierSense
- "Connection" mit Gateways, Internet usw. 

Hier müsste man noch etwas "Brainstorming" betreiben um sinnvolle Kategorien und Zusammenfassungen zu finden.

**Describe alternatives you've considered**
...

**Additional context**
So könnte das dann aussehen:
![RM-Alarmliste](https://user-images.githubusercontent.com/54898249/123287677-32e49900-d50f-11eb-8874-21baca747853.JPG)

**Comment by jens-maus** [comment]
Möglich wäre das schon, allerdings würde das dann dazu führen, dass dann bei hundert verschiedenen WatchDog Kategorien es dann auch hundert verschiedene Alarmvariablen geben wird, denn so funktioniert das WebUI System leider. Für jeden `triggerAlarm.tcl` aufruf mit unterschiedlichem Kategorienamen hinten wird auch jedesmal eine entsprechend Alarmvariable dann angelegt.

**Comment by Baxxy13** [comment]
Das ist mir bewusst. 
Daher ja auch der Gedanke das auf bspw. 3 sinnvolle Kategorien zu beschränken. Damit deckt man natürlich nicht alle möglichen Szenarien ab, aber allemal besser als eventuell einen "wichtigen" Alarm zu übersehen.
Auf mein Beispiel bezogen: der fehlgeschlagene Backup-Cronjob hätte für mich die höchste Priorität, Internet geht ja wieder und die Überhitzung ist auch vom Tisch.

**Comment by Baxxy13** [comment]
Ich habe mir jetzt erstmal alle `triggerAlarm.tcl` Aufrufe aus der `/etc/monitrc` rausgepickt und diese tabellarisch in 3 Kategorien eingeteilt. (+ die 2 Generierungen aus der `/bin/cronBackup.sh`)
### Systemdienste: 23
- hardware watchdog   restarted
- hss_led restarted
- klogd restarted
- syslogd restarted
- udevd restarted
- irqbalance restarted
- rngd restarted
- dbus restarted
- Chrony-NTP restarted
- NTP offset > 1 second
- eq3configd restarted
- lighttpd restarted
- HTTPS certificate expiring in < 30   days
- ssdpd restarted
- sshd restarted
- hs485d restarted
- multimacd restarted
- rfd restarted
- HMIPServer restarted
- ReGaHss restarted
- crond restarted
- ifplugd(eth0) restarted
- ifplugd(wlan0) restarted


### Zentrale: 6
- high CPU usage   (>95%) detected
- high memory usage (>95%) detected
- under-voltage detected
- Unclean shutdown or system crash   identified
- No internet connection detected
- HB-RF-ETH: no connection' 'HB-RF-ETH   Connection

### Dateisystem: 10
- rootfs (/): low   disk space
- userfs (/usr/local): low disk space
- userfs (/usr/local): changed fsflags   (potential disk error)
- usb1 (/media/usb1): low disk space
- usb1 (/media/usb1): changed fsflags   (potential disk error)
- eMMC life time >90% exceeded
- eMMC life time 100% exceeded
- cronBackup: Could not create ${BACKUPDIR}
- cronBackup: Backup job failed
- Bad blocks on main disk device detected

Die 23 "Systemdienste" kann man ja (wie bisher) als "Watchdog-Alarm" belassen.
Die 6 "Zentrale" könnten bspw. "Watchdog-Alarm-Zentrale" heißen
Die 10 "Dateisystem" könnten bspw. "Watchdog-Alarm-Dateisystem" heißen

(Somit hätte man nur 2 zusätzliche Alarm-Systemvariablen und keine "hundert") 

Die Generierungen in der `/bin/updateDCVars.tcl` tragen ja eh eigenen Namen, sind also außen vor.

Sind noch weitere Generierungen irgendwo versteckt?

**Comment by Baxxy13** [comment]
Ich habe meinen vorigen Post editiert. 
Es bleibt aber bei 2 zusätzlichen Kategorien. 
Durch die Kategorisierung könnten sich dann vermeintlich wichtige Alarme nicht gegenseitig überschreiben.

**Comment by jp112sdl** [comment]
Kann man nicht dem Alarmnamen einfach den Kurnamen ("Service Name") anhängen.
z.B.
`WatchDog-Alarm-sshd`,
`WatchDog-Alarm-internetCheck`

Dann ist jeder Alarm eindeutig, (in der Beschreibung steht auch immer die Detailinformation wie es bisher ist) und der Zähler zählt wirklich jeden Alarm - nicht nur kategorisiert zusammengefasst.

**Comment by Baxxy13** [comment]
Könnte man. Aber wie schon von Jens angemerkt hat man dann möglicherweise irgendwann 100 Alarmvariablen im System. Klar, die kann man wieder löschen aber so richtig gut fände ich das nicht.

**Comment by jp112sdl** [comment]
Man könnte die Variablen
a) nach dem Bestätigen wieder löschen
b) als 'intern' anlegen (wie die `svEnergyCounter...`), dann sind sie in der WebUI nicht sichtbar in den Systemvariablen

**Comment by jens-maus** [comment]
a) würde dazu führen das programme die ein nutzer angelegt haben dann immer ihre Referenz zur systemvariable verlieren.
b) wäre möglich. Aber ist das wirklich gewollt/sinnvoll das man die watchdog alarmvariablen dann so verstecken lässt?

**Comment by jp112sdl** [comment]
Die Kategorisierung ist ja evtl. ein Anfang.
Aber man hat dann trotzdem immer nur den letzten Alarm in der jeweiligen Kategorie.

Ich überleg grad, ob man eine Werteliste füttern könnte...
Jedes erneute Auftreten eines Alarms wird an diese angefügt (Zeitstempel+Beschreibung).
Wenn der Alarm quittiert wird, wird die Werteliste geleert.

**Comment by Baxxy13** [comment]
Also Variante b fände ich gar nicht so verkehrt. 
So bliebe die Möglichkeit auf einen (wiederkehrenden) Alarm per Programm zu reagieren. Viele Anwendungszenarien fallen mir da zwar spontan nicht ein, aber zumindest bei `No internet connection detected` könnte man den Router "zwangsresetten".  Und das Worst-Case-Szenario das sich tatsächlich alle Watchdog-Alarme im System tummeln wird wohl äußerst selten bis gar nicht eintreten.

"Wertelisten" klingt auch nicht schlecht. Mir fehlt es aber gerade an Vorstellungskraft wie das aussehen könnte.

**Comment by jp112sdl** [comment]
Eine einzelne SV mit dem Inhalt:
```
21.06.2021 22:30:00;No internet connection detected;21.06.2021 22:34:00;RF-Gateway ... not connected;21.06.2021 22:35:00;RF-Gateway ... not connected;...;21.06.2021 22:36:00;RF-Gateway ... not connected
```
Beim Bestätigen des Alarms wird die SV geleert.

Das hab ich aber grad wieder gedanklich verworfen.

Wenn man wirklich jedes Auftreten des Alarms mit Zeitstempel sammeln würde, könnte es im Falle von häufig wiederkehrenden Alarmen schnell zu einer endlos langen und nicht mehr sinnvoll ansehbaren Liste volllaufen.

<img width="476" alt="Bildschirmfoto 2021-06-26 um 06 28 42" src="https://user-images.githubusercontent.com/18190139/123501809-c325f980-d647-11eb-9b35-0c7ba881a50c.png">

**Comment by Baxxy13** [comment]
Ah ok. 
Sowas ähnliches nutze ich zum "loggen" von Systemzuständen. Da ist bei mir die maximale Anzahl der Einträge begrenzt, was aber für Alarme nicht sinnvoll wäre.
Man hat ja auch schon quasi eine "Liste" im Systemlog. Alle vom Monit getriggerten Alarme werden dort hinterlegt. 
```
Jun 24 16:55:57 homematic-raspi user.info monit[959]: 'uncleanShutdownCheck' exec: '/bin/sh -c /bin/triggerAlarm.tcl 'Unclean shutdown or system crash identified' WatchDog-Alarm ; rm -f /var/status/uncleanShutdown'
Jun 24 16:56:15 homematic-raspi user.info monit[959]: 'usb1' exec: '/bin/triggerAlarm.tcl usb1 (/media/usb1): changed fsflags (potential disk error) WatchDog-Alarm-FileSystem'
```
Wenn man die Triggerungen aus den Scripten  (`/bin/updateDCVars.tcl` `/bin/cronBackup.sh` ) um einem Logger-Eintrag erweitert und das Systemlog dann bspw. nach "triggerAlarm" filtert hätte man auch eine relativ gute Übersicht. 

Ich bin weiterhin der Meinung das nicht jeder mögliche Alarm eine eigene Alarmvariable benötigt. 
Aber meine 2 zusätzlichen Kategorien sind vielleicht doch etwas zu wenig.
Bei den Systemdiensten bin ich "unschlüssig" da ich die Relevanz der einzelnen Alarme nicht einschätzen kann.
Für den Rest mal folgender Entwurf:

### Zentrale: 3

- high CPU usage (>95%) detected
- high memory usage (>95%) detected
- under-voltage detected

### Systemstart: 1

- Unclean shutdown or system crash identified

### Internet: 1

- No internet connection detected

### Backup: 2

- cronBackup: Could not create ${BACKUPDIR}
- cronBackup: Backup job failed

### Dateisystem: 8 

- rootfs (/): low disk space
- userfs (/usr/local): low disk space
- userfs (/usr/local): changed fsflags (potential disk error)
- usb1 (/media/usb1): low disk space
- usb1 (/media/usb1): changed fsflags (potential disk error)
- eMMC life time >90% exceeded
- eMMC life time 100% exceeded
- Bad blocks on main disk device detected

**Comment by Baxxy13** [comment]
Nächster Entwurf:
(6 zusätzliche Kategorien zum normalen WatchDog-Alarm)

### WatchDog-Alarm RM-System (6)

- high CPU usage (>95%) detected
- high memory usage (>95%) detected
- high system temperature (> 80 deg) detected
- under-voltage detected
- eMMC life time >90% exceeded
- eMMC life time 100% exceeded

### WatchDog-Alarm RM-Filesystem (5)

- rootfs (/): low disk space
- userfs (/usr/local): low disk space
- userfs (/usr/local): changed fsflags (potential disk error)
- usb1 (/media/usb1): low disk space
- usb1 (/media/usb1): changed fsflags (potential disk error)

### WatchDog-Alarm RM-Crash / Shutdown (1)

- Unclean shutdown or system crash identified

### WatchDog-Alarm RM-BadBlocksCheck (1)

- Bad blocks on main disk device detected

### WatchDog-Alarm RM-InternetConnection (1)

- No internet connection detected

### WatchDog-Alarm RM-Backup (2)

- cronBackup: Could not create ${BACKUPDIR}
- cronBackup: Backup job failed

Das sähe dann etwa so aus:
![RM-WatchDog-Alarm-Kategorien](https://user-images.githubusercontent.com/54898249/124629718-feaf9780-de81-11eb-9f2e-a5134afb35d5.JPG)

**Comment by Baxxy13** [comment]
Habe das jetzt ne knappe Woche auf meinem Zweitsystem getestet und soweit für gut befunden.
Hier mal die diffs als Code.
```
--- /etc/monitrc.orig
+++ /etc/monitrc
@@ -361,9 +361,9 @@
 check system $HOST
     group system
     if cpu usage > 95% for 24 cycles then
-      exec "/bin/triggerAlarm.tcl 'high CPU usage (>95%) detected' WatchDog-Alarm"
+      exec "/bin/triggerAlarm.tcl 'high CPU usage (>95%) detected' 'WatchDog-Alarm RM-System';"
     if memory usage > 95% for 24 cycles then
-      exec "/bin/triggerAlarm.tcl 'high memory usage (>95%) detected' WatchDog-Alarm"
+      exec "/bin/triggerAlarm.tcl 'high memory usage (>95%) detected' 'WatchDog-Alarm RM-System';"
     if filedescriptors > 95% for 5 cycles then
       exec "/bin/triggerAlarm.tcl 'high filedescriptor usage (>95%) detected' WatchDog-Alarm"
 
@@ -371,21 +371,21 @@
 check filesystem rootfs with path /
     group system
     if space usage > 95% for 5 cycles then
-      exec "/bin/triggerAlarm.tcl 'rootfs (/): low disk space' WatchDog-Alarm"
+      exec "/bin/triggerAlarm.tcl 'rootfs (/): low disk space' 'WatchDog-Alarm RM-Filesystem';"
 
 check filesystem userfs with path /usr/local
     group system
     if space usage > 95% for 5 cycles then
-      exec "/bin/triggerAlarm.tcl 'userfs (/usr/local): low disk space' WatchDog-Alarm"
+      exec "/bin/triggerAlarm.tcl 'userfs (/usr/local): low disk space' 'WatchDog-Alarm RM-Filesystem';"
     if changed fsflags then
-      exec "/bin/triggerAlarm.tcl 'userfs (/usr/local): changed fsflags (potential disk error)' WatchDog-Alarm"
+      exec "/bin/triggerAlarm.tcl 'userfs (/usr/local): changed fsflags (potential disk error)' 'WatchDog-Alarm RM-Filesystem';"
 
 check filesystem usb1 with path /media/usb1
     group system
     if space usage > 95% for 5 cycles then
-      exec "/bin/triggerAlarm.tcl 'usb1 (/media/usb1): low disk space' WatchDog-Alarm"
+      exec "/bin/triggerAlarm.tcl 'usb1 (/media/usb1): low disk space' 'WatchDog-Alarm RM-Filesystem';"
     if changed fsflags then
-      exec "/bin/triggerAlarm.tcl 'usb1 (/media/usb1): changed fsflags (potential disk error)' WatchDog-Alarm"
+      exec "/bin/triggerAlarm.tcl 'usb1 (/media/usb1): changed fsflags (potential disk error)' 'WatchDog-Alarm RM-Filesystem';"
     depends on hasUSB
 
 check program hasUSB with path "/usr/bin/test -e /var/status/hasUSB"
@@ -396,7 +396,7 @@
 check program temperature with path /bin/sh -c "(cat /sys/class/thermal/thermal_zone0/temp 2>/dev/null || echo 0) | awk '{ print $1/1000; if($1/1000 < 80.0) { exit 10 } else { exit 20 } }';"
     group system
     if status != 10 for 5 cycles then
-      exec "/bin/triggerAlarm.tcl 'high system temperature (> 80 deg) detected' WatchDog-Alarm"
+      exec "/bin/triggerAlarm.tcl 'high system temperature (> 80 deg) detected' 'WatchDog-Alarm RM-System';"
       repeat every 24 cycles
 
 # network interface (eth0) monitoring
@@ -432,7 +432,7 @@
 check program voltageCheck with path /bin/sh -c "[ $(( $(/usr/bin/vcgencmd get_throttled | cut -f2 -d=) & 0x1 )) -eq $(( 0x1 )) ]"
     group system
     if status = 0 for 2 cycles then
-      exec "/bin/triggerAlarm.tcl 'under-voltage detected' WatchDog-Alarm"
+      exec "/bin/triggerAlarm.tcl 'under-voltage detected' 'WatchDog-Alarm RM-System';"
       repeat every 24 cycles
     depends on voltageCheckEnabled
 
@@ -444,7 +444,7 @@
 check program internetCheck with path "/usr/bin/test -e /var/status/hasInternet"
     group system
     if status != 0 for 24 cycles then
-      exec "/bin/triggerAlarm.tcl 'No internet connection detected' WatchDog-Alarm"
+      exec "/bin/triggerAlarm.tcl 'No internet connection detected' 'WatchDog-Alarm RM-InternetConnection';"
       repeat every 24 cycles
     depends on internetCheckEnabled
 
@@ -456,7 +456,7 @@
 check program badblocksCheck with path "/usr/bin/test -s /tmp/badblocks.txt"
     group system
     if status = 0 for 1 cycles then
-      exec "/bin/triggerAlarm.tcl 'Bad blocks on main disk device detected' WatchDog-Alarm"
+      exec "/bin/triggerAlarm.tcl 'Bad blocks on main disk device detected' 'WatchDog-Alarm RM-BadBlocksCheck';"
       repeat every 6700 cycles
     depends on crond
 
@@ -464,7 +464,7 @@
 check program uncleanShutdownCheck with path "/usr/bin/test -e /var/status/uncleanShutdown"
     group system
     if status = 0 for 1 cycles then
-      exec /bin/sh -c "/bin/triggerAlarm.tcl 'Unclean shutdown or system crash identified' WatchDog-Alarm ; rm -f /var/status/uncleanShutdown"
+      exec /bin/sh -c "/bin/triggerAlarm.tcl 'Unclean shutdown or system crash identified' 'WatchDog-Alarm RM-Crash / Shutdown' ; rm -f /var/status/uncleanShutdown"
       repeat every 24 cycles
 
 # check if a HB-RF-ETH is supposed to be connected and if it is not rais an alarm
@@ -484,10 +484,10 @@
     group system
     if status == 1 for 3 cycles then unmonitor
     if status == 2 for 5 cycles then
-      exec "/bin/triggerAlarm.tcl 'eMMC life time >90% exceeded' WatchDog-Alarm"
+      exec "/bin/triggerAlarm.tcl 'eMMC life time >90% exceeded' 'WatchDog-Alarm RM-System';"
       repeat every 280 cycles
     if status == 3 for 5 cycles then
-      exec "/bin/triggerAlarm.tcl 'eMMC life time 100% exceeded' WatchDog-Alarm"
+      exec "/bin/triggerAlarm.tcl 'eMMC life time 100% exceeded' 'WatchDog-Alarm RM-System';"
       repeat every 280 cycles
 
 # include user-defined configuration files
```
```
--- /bin/cronBackup.sh.orig
+++ /bin/cronBackup.sh
@@ -59,7 +59,7 @@
 # if BACKUPDIR does not exist, create it
 if [ ! -e "${BACKUPDIR}" ]; then
   if ! mkdir "${BACKUPDIR}"; then
-    /bin/triggerAlarm.tcl "cronBackup: Could not create ${BACKUPDIR}" WatchDog-Alarm
+    /bin/triggerAlarm.tcl "cronBackup: Could not create ${BACKUPDIR}" "WatchDog-Alarm RM-Backup"
     exit 1
   fi
 fi
@@ -72,7 +72,7 @@
 
 # create the backup in BACKUPDIR now
 if ! /bin/createBackup.sh "${BACKUPDIR}"; then
-  /bin/triggerAlarm.tcl "cronBackup: Backup job failed" WatchDog-Alarm
+  /bin/triggerAlarm.tcl "cronBackup: Backup job failed" "WatchDog-Alarm RM-Backup"
   exit 1
 fi
```

**Comment by jens-maus** [comment]
So, nun hab ich für den nächsten nightly snapshot mal eine erste Version der Umsetzung verbesserter WatchDog-Alarmierung umgesetzt. Nach dem Hinweis von @jp112sdl habe ich `triggerAlarm.tcl` nun so umgearbeitet, dass man damit nun auch rein "interne" Alarmvariablen generieren lassen kann damit diese in der Auflistung der Systemvariablen lediglich bei der generieren von Programmen ersichtlich werden aber eben auch in der Auflistung der Alarmmeldungen mit berücksichtigt werden. D.h. für jeden Alarmtyp gibt es nun eine eigene, individuelle Alarmvariable, sodass bei der Generierung mehrerer Alarme nun die Historie der Alarmierung besser zu erkennen sein sollte.

Bitte also mal mit der nächsten Version schauen ob das nun soweit passt und wo ggf. noch Verbessungsbedarf zu sehen ist.

**Comment by Baxxy13** [comment]
Ein erster Kurztest sieht hier erstmal gut aus.
Die `true / false` - Option für die überarbeitete `triggerAlarm.tcl` ist ja genial, so kann man bei eigens generierten Alarm-SysVars selbst entscheiden ob intern oder eben nicht.

Da meine Systeme ziemlich rund laufen darf die breite Masse dann ausgiebig testen. ;-)

**Comment by jens-maus** [comment]
Danke für die Rückmeldung. Die einzige Sache die mir bei der Entwicklung aufgefallen war ist, das man vllt darüber nachdenken könnte in der Systemsteuerung->Systemvariablen auch irgendeine Möglichkeit zu schaffen das man auch „interne“ Variablen auflisten und ggf bearbeiten/löschen kann. Momentan gibt es da ja keine Möglichkeit.

**Comment by jp112sdl** [comment]
Funktioniert die ReGa-Methode `EnumEnabledInternalIDs()` auch für Sysvar-Objekte?

Dann könnte man codeseitig vielleicht einiges aus "Programme" mitnehmen.
https://github.com/eq-3/occu/blob/f88d81a54e004fb895efbe7ec829c4d1ef28dd47/WebUI/www/rega/pages/tabs/admin/views/programlist.htm#L107

Die Sysvar selbst müsste dann in der WebUI neben "sichtbar" und "protokolliert" eine "intern"-Checkbox bekommen.

**Comment by jens-maus** [comment]
Das ist ja genau die Methode die ich im neuesten WebUI patch auch verwendet habe (siehe https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0133-WebUI-Fix-AlarmSysVarInternal.patch#L10). Bzw. die musste ich leider nehmen weil ich lernen musste das sich die Methode `EnumIDs()` leider zwischen `IseIdArray` objekten und anderen Array Objekten (wie z.b. das SysVarEnum Objekt) unterscheidet und ich das jetzt nicht in ReGaHss extra ändern wollte - obwohl man es eigentlich müsste um das anzugleichen.

@jp112sdl Also ja, das sollte auch für Sysvars so funktionieren wenn ich mich nicht irre. Wäre also in der Tat willkommen wenn du hier mal wieder aktiv werden könntest und vielleicht so ein WebUI Patch generierst, denn ich weiss nicht ob ich die nächste Woche da noch vor dem Release dazukomme. Und wenn dann sollte man hier vielleicht die SysVars die "intern" sind ähnlich abgehoben wie deaktivierte Programme in der Auflistung darstellen.
