### ISSUE TITLE
backup to FileShare not possible using CUxD

### ISSUE THREAD

**Issue by blackbasket** [jens-maus/RaspberryMatic#1326]
**Describe the bug**
With RM I cannot create backups using the CUxD backup file, because the variables may not exist.

**Steps to reproduce the behavior**
1. Testing the script on different RM versions
2. Testing the script on different eq3-CCU versions

**Expected behavior**
the backup should be successfull

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: 3.57.4.20210320
 - Used Hardware: CCU3

**Additional context**
```
:~# /usr/local/addons/cuxd/extra/ccu_backup
can't read "year": no such variable
    while executing
"set BACKUPFILE [set HOSTNAME]-$VERSION-$year-$month-$day-$hour$minute.sbk"
    (file "/usr/local/addons/cuxd/extra/ccu_backup" line 25)
```

**Comment by Baxxy13** [comment]
Das hatte Uwe doch in der aktuellen CUxD-Version eigentlich gefixed. 
Siehe [Homematic-Forum](https://homematic-forum.de/forum/viewtopic.php?f=37&t=67652&p=661832#p661832).
Welche CUxD-Version setzt du ein?

**Comment by blackbasket** [comment]
Oh, ok... prüfe ich nachher... ich war froh, endlich mal das Ticket geöffnet zu haben ;)

Danke erstmal @Baxxy13 :) hätte den Fehler aber ehrlich gesagt auch nicht in CUxD vermutet...

**Comment by blackbasket** [comment]
Läuft, danke :)
