### ISSUE TITLE
HA AddOn kann keine Verbindung zu DRAP aufbauen

### ISSUE THREAD

**Issue by TVR-X** [jens-maus/RaspberryMatic#1327]
**Describe the bug**

Hallo,
ich bin gerade dabei meine RaspberryMatic (ova auf einem ESXI Host) zu Home Assistant zu migrieren.
Soweit sieht nach der installation alles gut aus, HB-RF-ETH ist verbunden und wenn ich das backup einspiele laufen auch alle Funk Teilnehmer aber die Wired werden nur angezeigt machen aber nichts.

1. Der DRAP kann von dem HA Addon angepingt werden (per SSH auf der Raspberrrymatic) Ports sind bis auf den 1900er alle 1:1 durchgereicht (zum testen zumindest), der 1900er wird schon für was anderes verwendet ... auch wenn ich nicht weiß für was.
2.  wenn ich das ganze ohne backup teste und den DRAP auf Werkseinstellungen zurücksetzte bekomm ich ihn nicht angelernt und mit backup wird keine IP Adresse angezeigt unter Geräte an.
3. netstat -nlp sagt das er auf dem Port 43438 abhört, da es UDP ist weiß ich leider nicht wie ich testen könnte ob hier alles sauber durch geht

**System information:**
HA Core 2021.6.6
Supervisor 2021.06.3
OS 6.0 (nicht mehr RC)
RaspberryMatic 3.57.5.20210525 (sowohl als OVA aufm ESX als auch im HA)
Firmware HB-RF-ETH 1.2.9 mit Modul RPI-RF-MOD
Firmware DRAP 2.2.24

**Additional context**
HA, DRAP, Raspberrymatic, liegen in einem eigenen VLAN (davon bekommt das zeug aber nix mit weils "Untagged" am Cisco hängt) und der DRAP hat testweise ne reservierte Adresse von der Sophos Firewall (DHCP) bekommen und auch über den Netfinder eine Statische bekommen zum testen. Wobei ich nicht denke das hier ein Netzwerkproblem vorliegt weil mit der OVA installation funktioniert die Verbindung (auch bei einer neu Installation und DRAP reset kann dieser angelernt werden)

Hätte auch noch irgendwo diesen USB Adapter für RPI-RF-MOD rumliegen und evtl auch noch des kleine Steckmodul ohne RTC (ne alte CCU2 und ein HMIP-HAP könnte ich bestimmt auch zum testen auftreiben. Aber erstmal wollte ich wissen ob das schon jemals so getestet wurde oder obs evtl doch an mir liegt.

**Comment by TVR-X** [comment]
Dann werd ich mich mal mit meinem Fachinformatiker meines Vertrauens dran machen ne Test Umgebung auf der backup ESXI zu installieren und den HAP im Keller suchen. Ich befürchte nur da wir beide kaum/keine Erfahrung mim Shark haben das wir da warscheinlich etwas Unterstützung brauchen. Aber HW und Testumgebung sind kein Problem.

**Comment by mkoch5** [comment]
Gleiche bei mir auf einem Odroid N2+ und Raspi 4 ... konnte bisher keine Kommunikation aufbauen

**Comment by TheRealKillaruna** [comment]
Das ist doch genau das Problem, was jetzt in #1373 genauer analysiert wurde, oder?

**Comment by jens-maus** [comment]
In der Tat das gleiche wie #1373. daher geht es da weiter.
