### ISSUE TITLE
Button to teach devices is missing / devices not responding

### ISSUE THREAD

**Issue by eckhardtj** [jens-maus/RaspberryMatic#1329]
After upgrading the Home Assistant Addon RaspberryMatic to 3.57.5.20210525 the button to teach new devices is missing. Existing devices do not respond any more.
I'm running Home Asssistant core-2021.6.6 on Home Assistant OS 6.1

**Comment by jens-maus** [comment]
Sorry, but this is no support or discussion fora here. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. This was also already mentioned in the ticket template!
___
Tut mir leid, aber das hier ist kein Supportforum, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen.  Dies stand übrigens auch so im Ticket Template!
