### ISSUE TITLE
HmIP-BBL Jalosieaktor: Einstellungen lassen sich nicht speichern

### ISSUE THREAD

**Issue by banjamann** [jens-maus/RaspberryMatic#133]
Hallo *,

das o.a. Gerät ist ziemlich neu und lässt sich auch erst seit dem letzten Release anlernen.
Es funktioniert jedoch nur teilweise, da beim speichern der Einstellungen der Vorgang spätestens bei Channel:3 hängen bleibt.
F5 beendet der Vorgang - die vorausgegangenen Kanäle sind auch gespeichert aber insbesondere Channel:7 (Timer) lässt sich so nicht speichern/einrichten.

Mache ich etwas falsch oder muss hier etwas angepaßt werden?

Gruß
Ralf

**Comment by MgicEye66** [comment]
leider funktioniert auch der Zugriff über die WebUi nicht zuverlässig (auch nach Cache Löschen). Hoch/Runter z.B. erst nach ändern der Lamellenstellung mal gar nicht, mal funktioniert es. Dabei ist es egal ob über ein Script aufgerufen oder direkt in der WebUi

**Comment by banjamann** [comment]
Hallo MgicEye66,
das kann ich nicht bestätigen - via Script (Astro Funktion) funktioniert bei mir alles seht gut.
Auch die Skripte zur manuellen Steuerung (z.B. 0%, 55%, 100%) laufen ohne Probleme.

**Comment by banjamann** [comment]
Allerdings steuere ich damit einen Rolladen - keine Jalousie.

**Comment by MgicEye66** [comment]
jupp, beim Rolladen keine Probleme, das Problem tritt nur bei Jalousien auf. Habe davon 6 Stück im Einsatz und immer der gleiche Effekt.

**Comment by jens-maus** [comment]
mit dem kommenden release sollte dies behoben sein.

**Comment by banjamann** [comment]
Leider besteht der Fehler immer noch.
Mit dem aktuellen Release bleibt der Speichervorgang nun bei Channel 5 oder auch 6 hängen.
Diese beiden Kanäle sind in der Übersich gar nicht vorhanden.
Allerdings Channel 7 - selbiger ist für ein Wochenschaltprogramm vorgesehen damit der Rolladen auch autark mit der Astrofunktion laufen kann.
