### ISSUE TITLE
Backup lässt sich nicht einspielen (3.59.6.20210703 auf RPi [3b])

### ISSUE THREAD

**Issue by jp112sdl** [jens-maus/RaspberryMatic#1333]
**Describe the bug**
Der Versuch, ein Backup einzuspielen, läuft auf Fehler:
Kein Coprozessor verfügbar

**Steps to reproduce the behavior**
1. Backup einspielen

**Expected behavior**
Backup lässt sich einspielen

**Screenshots**
<img width="478" alt="Bildschirmfoto 2021-07-03 um 17 22 30" src="https://user-images.githubusercontent.com/18190139/124361784-23610080-dc31-11eb-9022-64212fd83a42.png">

**System information:**
 - RaspberryMatic Version: 3.59.6.20210703
 - Used Hardware: RaspberryPi 3b+
 - Used HomeMatic RF-Module: HM-MOD-RPI-PCB und RPI-RF-MOD

**Additional context**
- die Prozesse `HMIPServer` und `hss_led` stürzen ab
- es gibt keinerlei Fehlermeldungen in `/var/log/messages + hmserver.log`
- Der Fehler tritt in der OVA-Version nicht auf

**Comment by jens-maus** [comment]
Passiert das auch ganz ohne Funkmodul?

**Comment by jp112sdl** [comment]
Ja, passiert auch ohne Funkmodul.

**Comment by jp112sdl** [comment]
Halt Stop! 

Nein, ohne Funkmodul fliegt zwar auch der `HMIPServer` Prozess weg (hab die ganze Zeit mit `ps` draufgeschaut).
Der wird dann von `monit` neu gestartet und mittendrin war auf einmal die SSH-Verbindung weg, weil der Pi neustartete und siehe da in der WebUI stand der Hinweis, dass das Backup erfolgreich eingespielt wurde

**Comment by jens-maus** [comment]
Ok, dann schau mal bitte nach `/bin/checkUsrBackup.sh`. Das ist der Skript der die Backupprüfung druchführt in dem er HMIPServer aufruft. Denke auch das ich das Problem vielleicht sogar (ohne das selbst getestet zu haben) bereits gefunden habe. In dem Skript ist noch ne inzwischen obsolete unterscheidung für `aarch64` drin die raus muss. Vllt. kannst du das ja mal testen.

**Comment by jens-maus** [comment]
Ok, ich denke das war in der Tat der Grund für das Problem hier. Versuch einfach mal in der /bin/checkUsrBackup.sh das gesamte if (mit anweisung) für die `aarch64` Prüfung wie folgt rauszuwerfen:

```patch
--- a/buildroot-external/overlay/WebUI-raspmatic/bin/checkUsrBackup.sh
+++ b/buildroot-external/overlay/WebUI-raspmatic/bin/checkUsrBackup.sh
@@ -23,13 +23,6 @@ if [[ -n "${HM_HMIP_DEV}" ]]; then
   # get the architecture
   ARCH=$(uname -m)
 
-  # if we run on aarch64 we have to override the libNRJavaSerial definition
-  # so that the aarch64 (v8) version is used we supply our own
-  JAVAOPT=
-  if [[ "${ARCH}" == "aarch64" ]];then
-    JAVAOPT="-DlibNRJavaSerial.userlib=/opt/HMServer/libNRJavaSerialv8.so"
-  fi
-
   /opt/java/bin/java -Dos.arch="${ARCH}" ${JAVAOPT} -Dfile.encoding=ISO-8859-1 -Dvertx.cacheDirBase=/tmp/.vertx-backuprestore -Dgnu.io.rxtx.SerialPorts="${HM_SERVER_DEVNODE}" -cp "${HM_SERVER}" de.eq3.ccu.server.ip.validation.ValidateHmIPBackup ${HM_SERVER_ARGS} "${pathBackup}"
 
   case $? in
```

Das sollte das Problem dann hoffentlich beheben.

**Comment by jp112sdl** [comment]
Jap, damit funktioniert es bei mir

**Comment by jens-maus** [comment]
Super! Danke. Dann haben wir das Biest ja erwischt.

**Comment by emufan** [comment]
@jens-maus: Ich habe dies Problem auch mit 3.59.6.20210703. Komme von Standard-CCU3-Backup.

Leider ist der Bug ja schon geschlossen. Sollte es in dem Release schon behoben sein, oder nicht?

Was kann/muss ich als "Laie" machen?
