### ISSUE TITLE
Kein Update (mehr) möglich von 3.57.5.20210424 auf 3.59.20210703

### ISSUE THREAD

**Issue by agrimpelhuber** [jens-maus/RaspberryMatic#1336]
**Describe the bug**

Weder mit der Option "Direkt auf CCU laden und installieren" noch mit dem manuellen Update (Herunterladen / Hochladen) ist ein Update der beschriebenen Versionen möglich. Die Übertragung auf den Raspberry Pi dauert ewig (> 2 Tage war bisher der längste Versuch), ohne dass der Dialog "Hinweis! Das Firmware-Update ... übertragen" irgendwann verschwinden würde.

Dieselbe Vorgehensweise hat zuvor immer funktioniert. CCU funktioniert sonst auch einwandfrei. 

Zusätzlich fehlen mir Anhaltspunkte, um den Fehler auch nur einzugrenzen. Letzte erkennbar zusammenhängende Logeinträge:
```
Jul 3 10:23:19 de.eq3.cbcs.server.local.base.internal.LocalServerFirmwareUpdateInitialization INFO  [vert.x-eventloop-thread-1] SYSTEM: LocalServerFirmwareUpdateInitialization Verticle or Worker started 
Jul 3 10:23:19 de.eq3.cbcs.vertx.management.VertxManager INFO  [vert.x-eventloop-thread-0] SYSTEM: start of LocalServerFirmwareUpdateInitialization succeeded (91e8ab74-2ed9-4e2d-a36b-221dc3266272) 
```

**Steps to reproduce the behavior**
1. RaspberryMatic-WebUI in Chrome aufrufen, "Zentralenwartung" (Alternativ verwendet: Firefox)
2. "Direkt auf CCU laden und installieren" anklicken
3. Alternativ zu 2.: Schritte 1-3 im Dialog durchführen
4. Warten, bis der Dialog "Hinweis! ..." verschwindet (was er auch nach mehr als 48 Stunden nicht tut)

Zusatz:
* Im Abgesicherten Modus gleiches Verhalten
* Im Recovery-Modus geht der Menüpunkt "Firmware-Update" auf einen Fehler (Seite nicht zu erreichen)

**Expected behavior**
Wie zuvor (Update *auf* die aktuell installierte 3.57.5.20210424) sollte das Update zumindest nach einigen Stunden auf die RaspberryMatic hochgeladen, und das Update beginnen (bzw. "Update starten" anzuklicken sein).

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: 3.57.5.20210424 (rpi0-Version)
 - Used Hardware: Raspberry Pi 1 Mod. B+, 512MB, Sandisk 32GB A1 microSD, LAN-Verbindung direkt an Fritzbox-Router.
 - SD-Karte in allen Bereichen zu mehr als 50% frei
 - Mem: 465176K used, 7052K free, 184K shrd, 984K buff, 383172K cached
 - Used HomeMatic RF-Module: ELV Homematic IP ARR-Bausatz RF-USB-Stick

**Additional context**
Auch ein intensive Recherche hat leider keine Informationen für ein gezieltes Debugging ergeben. Für den Fall, dass evtl. ein unvollständiger Upload (falls das möglich ist) etwas blockiert, wäre ich an einem Weg interessiert, wie man ggf. das Update manuell (Upload des Updates per SFTP auf den Pi - wohin? Anstoßen des Updates per Shell - wie?) auslösen kann.

Ansonsten wären Infos über relevante Logs und entsprechende Loglevels hilfreich. Wie erkenne ich Fehler bei Hochladen?

**Comment by jens-maus** [comment]
> * Im Recovery-Modus geht der Menüpunkt "Firmware-Update" auf einen Fehler (Seite nicht zu erreichen)

Dieser Hinweis ist komisch. Diese Seite MUSS funktionieren. Bitte also den Fehler noch einmal nachstellen. Das Recovery System darf hier definitiv keinen Fehler zeigen und wenn ja, dann bitte hier entsprechend mit Screenshot, etc. belegen.

**Comment by Baxxy13** [comment]
Oh je, Pi1B... sowas habe ich nicht mal mehr zum testen hier.
Auch du könntest es mal mit dem [rmupdate-AddOn](https://github.com/j-a-n/raspberrymatic-addon-rmupdate) probieren, vielleicht läuft's damit durch. 
Die 3.57.5.20210424 verhielt sich bei vielen Usern zickig als es darum ging sie zu updaten.

**Comment by agrimpelhuber** [comment]
Danke für die Hinweise, mache ich! Den Pi1B verwende ich auch nur, *weil* RaspberryMatic damit anstandslos läuft (bzw. lief). Ist im Prinzip Recycling auf hohem Niveau. Deshalb werde ich auch da nur begrenzt Ressourcen aufs Debugging verwenden - vor allem, dass hier evtl. demnächst ein Hinweis "End of life für Pi < 2 erreicht stehen kann". Ein RPi 3B+ liegt als Reserve für meine Projekte eh schon im Regal.

Wenn es aber nur an der 3.57.5.20210424 lag, werde ich auch das berichten. 

Letzte Frage: Wenn alles nichts hilft, wäre es eine Lösung, "wie früher" auf die aktuelle Version über Backup - Flash - Backup zurückspielen zu gehen?

**Comment by Baxxy13** [comment]
> Letzte Frage:

Ja das geht grundsätzlich immer. Dummerweise hat die aktuelle 3.59.6.20210703 einen Bug der ein korrektes Einspielen des Backups verhindert. Nach einem Reboot ist es dann aber trotzdem drin.
Ob der Bug auch die Pi1 / Pi2 -Version betrifft weiß ich nicht. Also ausprobieren.

**Comment by agrimpelhuber** [comment]
Vorweg - ich habe ein erfolgreich aktualisiertes System hinbekommen. Stellt sich die Frage, ob angesichts des Pi1 ein Interesse besteht, den Problemen weiter auf den Grund zu gehen. Hier mal meine Lösungsansätze (Danke für die Hilfe und Hinweise), aber so richtig schlau bezüglich der Ursachen bin ich noch nicht geworden.

**Altsystem:** 
Auf dem "alten" System 3.57.5.20210424, welches ich auf einer Karte konserviert habe, treten immer noch folgende Probleme auf:
* Einspielen einer neuen Firmware in der Recovery stößt unweigerlich nach kurzer Zeit (zu kurz für einen Upload) auf diese Meldung:
![image](https://user-images.githubusercontent.com/35150551/124492518-dc037d00-ddb4-11eb-989c-2bfbe707d1fa.png)
* Update über "Zentralenwartung" geht weiterhin nicht, siehe oben.
* Update mit rmupdate-AddOn geht nicht (wartet ewig). Bietet auch nur die aktuelle Version 3.57.5.20210424 an.
* Auch das Update des Redmatic-AddOns (installierte Version 7.13) ging nicht über rmupdate

**Workarounds über Backup und neues System auf neuer Karte**
* Geht: Install 3.57.5.20210525, Update in Zentralenwartung auf 3.59.6.20210703, Einspielen des Backups in Recovery.
  * Aber seltsames Verhalten der Add-Ons (Interfaces unvollständig), so dass ich meine Bedenken hatte
* Geht nicht: Install 3.57.5.20210525, Einspielen des Backups in Recovery, dann Update über Zentralenwartung (läuft ewig)
  * In diesem Szenario aber erfolgreich Update über die Recovery auf 3.59.6.20210703

Weil ich deshalb den Verdacht habe, dass meine Konfiguration (=Backup) irgendwie korrupt ist oder anderweitig Probleme macht, und das evtl. mit Redmatic zu tun hat, habe ich letztendlich auf dem Altsystem 3.57.5.20210424 alle Add-Ons entfernt, dann ein Backup gemacht, die 3.57.5.20210525 neu installiert und dann das Backup in der Recorvery eingespielt - läuft. Über rmupdate lief danach auch ein Update auf die aktuelle 3.59.6.20210703, obwohl bei rmupdate nur die 3.57.5.20210525 angezeigt hatte (also Eingabe der URL zur 3.59.6.20210703). Update über Recovery geht natürlich, weil rmupdate die ja aufruft.

Was jetzt noch offen ist
* Frage: Geht jetzt auch wieder das Update über die Zentralenwartung (sehe ich beim nächten Mal)?
* Keine Ahnung, woran es jetzt lag. Aber ist das wichtig?

Wenn kein Interesse, dann schließen wir das Ticket, und es bleibt als Erfahrung für andere, und als Warnung :-)

**Comment by Baxxy13** [comment]
> * sehe ich beim nächten Mal

Na du kannst doch einfach mal versuchen die aktuell installierte Version nochmal per WebUI "drüberzuinstallieren".

Klappt das, dann kann das Ticket wohl ad acta gelegt werden.
