### ISSUE TITLE
"Der Kanal hat hier keine Funktion" HmIP-WRCC2, HmIP-KRC4 ,HmIP-RCB1 

### ISSUE THREAD

**Issue by Lehnerr** [jens-maus/RaspberryMatic#1338]
**Describe the bug**
Folgende Schalter zeigen in der GUI nur "Der Kanal hat hier keine Funktion" obwohl sich hinter jeden Taster ein Programm verbirgt das auch funktioniert:
HmIP-WRCC2, HmIP-KRC4 ,HmIP-RCB1 

**Steps to reproduce the behavior**
1. Ich installierte ein neues System
2. Lente die Geräte an
3. ERzeugt ein Program das auf Tasten druck Kurz oder Lang reagierte  

**Expected behavior**
Schalter sollten auch in der GUI verwendet werden können.

**Screenshots**
![image](https://user-images.githubusercontent.com/16813374/124974994-c9e04380-e02d-11eb-99ca-826436cca554.png)
![image](https://user-images.githubusercontent.com/16813374/124975060-de244080-e02d-11eb-8602-ca7b14a730e6.png)
![image](https://user-images.githubusercontent.com/16813374/124975100-eda38980-e02d-11eb-82ca-21b239edd284.png)

**System information:**
 - RaspberryMatic Version: RaspberryMatic-3.59.6.20210703-rpi3
 - Used Hardware: pi3
 - Used HomeMatic RF-Module: ...

**Additional context**
...

**Comment by Baxxy13** [comment]
Das ist nun mal bei allen IP-Tastern so. Die können nicht virtuell (per WebUI / App) gedrückt werden. 
Daran kann auch RaspberryMatic nichts ändern. 
Hier hilft es nur eQ-3 anzuschreiben und um die Implementierung einer solchen Funktion zu bitten.

**Comment by jens-maus** [comment]
Genau so wollte ich das auch erklären. Das hier aufgezeigte Verhalten bzw. die Anzeige "Der Kanal hat hier keine Funktion" ist vollkommen normal und kein Bug/Problem. Da es sich hier ja um Taster handelt kann die WebUI erstens nicht den aktuellen Livestatus davon darstellen und zweiten kann man auch deren Status nicht virtuell von der WebUI in irgendeiner weise ändern/beeinflussen. Insofern ist die Anzeige `Der Kanal hat hier keine Funktion` vollkommen korrekt und unproblematisch.

**Comment by Lehnerr** [comment]
Ich würde mir wie beim Taster HM-PB-6-WM55
folgendes erwarten.
![image](https://user-images.githubusercontent.com/16813374/125040247-b4076880-e097-11eb-822c-350de4ccdd15.png)
Man bnötigt keinen STatus bei einem Taster.
Wie kann man eQ-3 kontaktieren?

**Comment by jens-maus** [comment]
> Ich würde mir wie beim Taster HM-PB-6-WM55
> folgendes erwarten.

Eins übersiehst du ganz offensichtlich: wenn du wie beim HM-PB-6-WM55 über die WebUI dort "Kurzer Testendruck", "Langer Tastendruck" drückst, dann werden auch Direktverknüpfungen dieses Gerätes mit anderen Geräten (die ja unabhängig der CCU funktionieren) auch ausgelöst. Das ist ein integrales Feature dieses Gerätes. Bei den anderen von dir referenzierten HmIP Geräten ist das jedoch nicht der Fall. Diese unterstützen es nicht via eines Kanals aus der Ferne quasi einen Tastendruck auszulösen und damit auch deren Direktverknüpfungen via dieser Kanäle zu triggern. Genau deshalb hat eQ3 an diese Stelle auch den Hinweis `Der Kanal hat hier keine Funktion` hinterlegt. Denke also bitte nicht nur an WebUI Programme auf der CCU die du selbst zusammengeklickt hast die du da vermeintlich triggern lassen willst (sowas erledigst du am besten über die virtuellen Taster der CCU/RaspberryMatic selbst!), sondern diese Geräte unterstützen es eben firmwaretechnisch nicht das man aus der Ferne an dieser Stelle diesen Kanal eben triggern lassen kann. Das ist der Hintergrund dieser Anzeige.

> Wie kann man eQ-3 kontaktieren?

Schau auf deren Homepage. Ich mache dir aber wenig Hoffnung das du da irgendwie (genau aus dem oben genannten Grund) etwas bewirken wirst, denn das würde bedeuten das eQ3 für alle diese Geräte nicht nur firmware-updates herausbringen müsste, sondern integrale Features verändern müsste die aber eben aus gutem Grund (z.B. Stromeffizienz, etc.) genau so umgesetzt wurden.

**Comment by Baxxy13** [comment]
> Ich würde mir wie beim Taster HM-PB-6-WM55
> folgendes erwarten.

Da läuft das anders. Drückst du in der WebUI auf "den Taster" emuliert deine Zentrale das Gerät und den Tastendruck. Kann man gut testen indem man beim physischen Taster die Batterien entfernt.
Bei HMIP gibt es das nicht, möglicherweise wegen der Verschlüsselung des HmIP-Protokolls.
[Hier](https://homematic-forum.de/forum/viewtopic.php?f=59&t=59135&p=585665&hilit=virtuell#p585674) wurde das mal kurz technisch beschrieben.
