### ISSUE TITLE
Feature Request: Support SPI displays

### ISSUE THREAD

**Issue by renne** [jens-maus/RaspberryMatic#134]
For controlling the status of the OS/showing the IP address RaspberryMatic should support SPI displays.

Currently FBTFT is already compiled as modules.

Missing are the TFT overlays (e.g. waveshare35a-overlay.dtb for Kuman SC06 3,5" display) and a way to switch the RaspberryMatic console to /dev/fb1 or the fbcopy tool as a daemon.

**Comment by jens-maus** [comment]
Feel free to provide pull requests :) But please make sure to add these features optional as only a very minimal number of users might profit from these kind of features (RaspberryMatic is designed to be a headless system).

**Comment by renne** [comment]
How can a user add "dtoverlay=XXX" to /boot/config.txt surviving a RaspberryMatic upgrade?

**Comment by jens-maus** [comment]
currently not possible and I also don't know how to provide this kind of functionality yet. But honestly, we are probably talking about <1% of the RaspberryMatic users wanting such a feature and thus these <1% of users wanting/requiring a TFT probably already know how to manually tune /boot/config.txt, etc. themselves and change it again in future after a RaspberryMatic upgrade. And I hope you understand that it makes really no sense to deliver RaspberryMatic for all users with these kind of dtoverlay files if the majority of users won't use them at all.
