### ISSUE TITLE
Added support for "Raspberry Pi Imager" tool

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#1347]
**Is your feature request related to a problem? Please describe.**
Since mid of 2020, the Raspberry Pi organisation maintains an own imaging tool called "rpi-imager" (https://github.com/raspberrypi/rpi-imager). This tool allows to flash whole os images similar to how etcher or other imaging tools are doing this. In addition, this "rpi-imager" allows to directly download these images via a well-defined json file API.

**Describe the solution you'd like**
We already added the necessary changes (https://github.com/jens-maus/RaspberryMatic/commit/fb34bde0a620459c143b44cf115211c18709300c) to our repository to support integration into the "Raspberry Pi Imager" and are waiting for integration of these changes here:

https://github.com/raspberrypi/rpi-imager/issues/245

**Additional context**
To show support by the RaspberryMatic community, please consider raising a thumbs up (👍) in the linked rpi-imager ticket (https://github.com/raspberrypi/rpi-imager/issues/245)  so that the authors of rpi-imager can better consider integration.

**Comment by lurch** [comment]
Please don't add extra "Me too" comments to the Raspberry Pi Imager issue, it's not very helpful.

**Comment by jens-maus** [comment]
Exactly! It is enough to just put your „thumbs up“ by clicking the smiley smbol on the too right corner!

**Comment by maxnet** [comment]
Also no point in tagging me in each post, as I do not maintain the repository.
(And ironically enough had my own share of trademark problems albeit with a different piece of fruit).

**Comment by jens-maus** [comment]
Just FYI: The RaspberryPi Foundation has now finally integrated our proposed change. Thus, RaspberryMatic is now correctly listed and usable in the official "RaspberryPi Imager" tool. See:

![image](https://user-images.githubusercontent.com/5887769/152752970-c8431c6d-606f-4d5c-be26-69c38248fa19.png)

Therefore, the official RaspberryMatic documentation has also been already adapted to reflect that improvement:

https://github.com/jens-maus/RaspberryMatic/wiki/Installation-RaspberryPi
