### ISSUE TITLE
Raspberry als LAN-Gateway

### ISSUE THREAD

**Issue by Home-Solutions24** [jens-maus/RaspberryMatic#135]
Hallo,

ich habe gemäß Kurzanleitung einen Raspberry PI Zero als LAN Gateway konfiguriert.
nach dem Neustart fuhr dieser auch scheinbar korrekt hoch. Über SSH/SFTP kann ich auch
zugreifen.

Jedoch steht in der Kurzbeschriebung :

"... Danach sollte RaspberryMatic normal hochfahren, jedoch in der Ausgabezeile seiner Versionsnummer dann den String LAN-GW Mode (IP-Adresse) unter Angabe seiner IP-Adresse ausgeben..."

In welcher Ausgabezeile sehe ich die Versionsnummer? Über den Browser kann ich ja nicht mehr auf
den Raspberry zugreifen.

Ich habe im "Haupt"Raspberry daraufhin einfach ein neuses Gateway angelegt, die IP Adresse des Zero  angegeben und neu gestartet. Er scheint sich jedoch nicht mit dem Gateway zu verbinden. Ich habe mal testweise einen Sensor (Türkontakt) mit dem Gateway verbunden. Aber die Verbindung besteht weiterhin direkt mit dem "Haupt"Raspberry.

![gateway](https://user-images.githubusercontent.com/30926493/29210599-96fa714c-7e94-11e7-95eb-e1fcd4492de7.jpg)

Gibt es hier noch ein Missverständnis oder ist die Funktion noch fehlerhaft?

Danke.

**Comment by anli-xsigns** [comment]
Es ist die Ausgabe auf dem Bildschirm gemeint, via HDMI. Der wird angezeigt während des Bootens, wenn man HDMI später aktiviert ist der Bildschirm wahrscheinlich im Schlafmodus und muss erst durch Tastendruck aktiviert werden. Grundsätzlich sollten Anfragen nach Support besser im Forum gestellt werden: https://homematic-forum.de/forum/viewforum.php?f=65. Die Issues hier sind nur für Bugs und FeatureRequests vorgesehen.

**Comment by Home-Solutions24** [comment]
Danke trotzdem. Ich gelobe Besserung. Aber ich bin mir nicht sicher, ob hier nicht doch ein Bug vorliegt.
Werde aber das Thema neu einstellen.
