### ISSUE TITLE
Potential Mistake in translate.js leads to performance issue

### ISSUE THREAD

**Issue by theimo1221** [jens-maus/RaspberryMatic#1354]
Hello team,

why is here an `addBack`??!
![image](https://user-images.githubusercontent.com/20605452/127745464-04fb7546-675d-4d0e-9fba-60971ce2616f.png)

In some occasions this leads to document beeing included into the search, thus `find("*")` matches every single element on the page:

![image](https://user-images.githubusercontent.com/20605452/127745447-c4a4f388-2bb5-45c8-8c8e-0e4e15eb7545.png)

Yes, this is followed by some filters, but still, why do one pass a container to look in, when afterwards whole page gets scanned anyway?

![image](https://user-images.githubusercontent.com/20605452/127745542-e9417fdd-00a0-4c46-8cee-2133079ba395.png)

On my (quite strong) machine this leads to 360ms delay loading the devices.

Thanks and best regards 

Thiemo

**Comment by jens-maus** [comment]
Thanks @theimo1221 for this observation. In fact, this `addBack` was not added by a RaspberryMatic WebUI patch, but was added/developed by eQ3 themselves. So feel free to suggest chances or send in PR that optimize this use which we could then potentially integrate here in a WebUI patch.

**Comment by theimo1221** [comment]
@jens-maus I'm not yet quite sure why and where exactly those special translations are needed/used, with those specific `$(` text's.
This makes it somewhat harder for me to test/verify I don't destroy any specific functionality.

Quoting jQuery Documentation regarding `.addBack()`: 

> Description: Add the previous set of elements on the stack to the current set, optionally filtered by a selector.

![image](https://user-images.githubusercontent.com/20605452/127765557-5c04fd12-16c3-4c68-a28b-394e95f27c5c.png)

In this example `.addBack` is used to merge the results from the first query `$( "div.after-addback" )` with the second query `.find("p")`


In our scenario we don't have a first Query, thus in my opinion making the call for `.addBack()` programmatically obsolet and dangerous, as this is not well defined behaviour.

**BUT** it could be that the normal search -without `addBack()` including the whole document- could result in some elements being left out due to that search not beeing correct.

**Comment by theimo1221** [comment]
I guess I solved the puzzle:

![image](https://user-images.githubusercontent.com/20605452/127765912-93bdf050-91f2-49b4-9eff-b3c9e78ce103.png)

Calls:

1. their original one having 40625 matches.
2. Without the `.addBack()` having 0 matches
3. Checking which elements where selected before the filter
4. Swapping the order of `find("*")` and `.addBack()` resulting in 286 matches, all being within the specified container (`".j_rooms, .j_functions"`)

So in my opinion, they not just wanted to find those containers, but also all elements within those containers. Keeping that in mind `.addBack()` is definitly necessary but has to be after the lookup for all elements within.
So swapping lines 20 and 21 within translate.js results in following logic:

1. Find the desired containers
2. Find all the elements within the desired container
3. Merge both set of found elements
4. ....

I'll prepare a PR later on

**Comment by theimo1221** [comment]
Atleast on my machine switching the speed increased quite a lot:

![image](https://user-images.githubusercontent.com/20605452/127767433-d9343932-e177-4412-a129-af91c6e0191a.png)

360ms at the start and now 12ms

**Comment by jens-maus** [comment]
Then please prepare a PR so that we can review+test it accordingly and see if this would have any negative side effects

**Comment by theimo1221** [comment]
> Then please prepare a PR so that we can review+test it accordingly and see if this would have any negative side effects

I already did

**Comment by jens-maus** [comment]
Ok, integrated the proposed change from @theimo1221. So please test the next upcoming nightly snapshot extensively to rule put any negative side effects of that otherwise minor change.

**Comment by detLAN** [comment]
Ich kann bestätigen, dass mit dem **Experimental Nightly Build Snapshots RaspberryMatic-3.59.6.20210802-5f20a3-tinkerboard.zip** die Geräte jetzt merklich schneller geladen werden.

**Comment by detLAN** [comment]
Ich kann bestätigen, dass mit dem **Experimental Nightly Build Snapshots RaspberryMatic-3.59.6.20210802-5f20a3-rpi4.zip** die Geräte jetzt merklich schneller geladen werden.
