### ISSUE TITLE
Neuaufruf der Startseite setzt CS zurück

### ISSUE THREAD

**Issue by Maik2208** [jens-maus/RaspberryMatic#1356]
**Describe the bug**
Auf der Startseite werden DC und CS angezeigt. Beide Werte können mit der Zeit ansteigen. Drückt man erneut auf den Button Startseite, so wird CS auf 0 zurückgesetzt. Der DC wird weiterhin korrekt angezeigt.

**Steps to reproduce the behavior**
1. Startseite aufrufen
2. warten bis CS einen Wert größer 0 aufweist
3. Button Startseite drücken
4. wundern, dass CS wieder 0 ist

**Expected behavior**
Korrekte Anzeige des CS nach erneutem Aufruf der Startseite

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: 3.59.6.20210703
 - Used Hardware: RPi3
 - Used HomeMatic RF-Module: MOD

**Additional context**
...

**Comment by jens-maus** [comment]
Bitte dieses Verhalten hier einmal via der Aufnahme eines screencasts zeigen/belegen. Denn technisch kann das eigentlich nicht passieren.

Das einzige was passieren bzw. das erklären kann ist, das in dem moment in dem Refresh im Browser gedrückt wird eben der abruf des CS sich eben aktualisiert auf sen momentan aktuellen wert (in
Dem moment eben 0). Weil in der WebUI der refresh nur in gewissen abständen passiert.

**Comment by Maik2208** [comment]
Deine Vermutung könnte schon sein. Die ersten Tests haben grad gezeigt, dass die Anzeige im Balken deutlich träger ist als in dem Infofeld oben drüber. Treibt man den DC hoch, ändert sich erst oben die Anzeige und verzögert der Balken.![image](https://user-images.githubusercontent.com/79879510/127772785-c9a08681-16d2-4df4-99dd-4396381cdf49.jpeg)

**Comment by jens-maus** [comment]
So ist das, ja. Aber das ist kein Bug sondern ein Feature. Insofern sehe ich hier keinen Handlungsbedarf.
