### ISSUE TITLE
Experimental Nightly Build Snapshots - Sicherheit

### ISSUE THREAD

**Issue by detLAN** [jens-maus/RaspberryMatic#1357]
**Describe the bug**
Im Sicherheitsdialog fehlen die Texte

**Steps to reproduce the behavior**
1. Startseite > Einstellungen > Systemsteuerung
2. Sicherheit
3. ...
4. ...

**Expected behavior**
Aus dem Dialog sollte schon ersichtlich sein worum es geht

**Screenshots**
<img width="800" alt="Sicherheit" src="https://user-images.githubusercontent.com/64675966/127811211-209688df-6e31-4697-b0ab-c5f4c6a90941.png">

**System information:**
 - RaspberryMatic Version: RaspberryMatic-3.59.6.20210802-5f20a3
 - Used Hardware: Raspberry Pi 4
 - Used HomeMatic RF-Module: RPI-RF-MOD

**Additional context**
...

**Comment by jens-maus** [comment]
Das könnte ein Nebeneffekt von #1354 sein. @theimo1221 müsste das mal testen und entsprechend berichten ob das damit ggf zusammenhängt.

**Comment by theimo1221** [comment]
Guten Morgen zusammen,

jo, dass kann damit zusammen hängen.
Spontan würde ich vermuten, dass dies eine der Seiten ist, die keinen passenden Aufruf an `setTextContent` in translate.js macht.

Vorher war es eben durch den "Fehler" dort nicht aufgefallen, da jeder andere Call an `setTextContent` die ganze Seite durchsucht hat.

**Comment by jens-maus** [comment]
@theimo1221 Danke für die Info. Da wäre die Frage ob du vllt. einen Link/Hint geben kannst wie genau dieser ggf. fehlende `setTextContent` Aufruf auszusehen hat damit man da vllt. sogar via skripten mal alle anderen Stellen wo eigentlich solch ein Aufruf sein sollte prüfen lassen kann.

**Comment by jens-maus** [comment]
Ok, ich denke ich hab es. Ersetzt man die Zeile 1513 in `cp_security.cgi` die so aussieht:

```
puts "translatePage();"
```

gegen folgende

```
puts "translatePage('#messagebox');"
```

Dann wird die Seite mit korrekten Übersetzen angezeigt/dargestellt. Wäre einfach zu korrigieren. Die Frage ist nur ob @theimo1221 sich das erklären kann? Auch müsste man folglich mal suchen ob das `translatePage()` irgendwie wie hier ohne Argumente aufgerufen wird und das eigentlich ein valider aufruf ist/sein soll?!?

**Comment by jens-maus** [comment]
Zumindest das letzte (wo das `translatePage()` noch so ohne argumente aufgerufen wird) kann ich wie folgt beantworten:

```sh
root@homematic-raspi:/www# grep -R "translatePage()" *
config/easymodes/cc_tc_ch_master.tcl:  puts "<script type=\"text/javascript\">translatePage();</script>"
config/easymodes/cc_tc_ch_master_le_v1_9.tcl:  puts "<script type=\"text/javascript\">translatePage();</script>"
error/error-503.html:        translatePage();
error/error-500.html:        translatePage();
rega/pages/tabs/startpage.htm:  translatePage();
rega/pages/tabs/favViewer.htm:  translatePage();
```

Wäre also die Frage ob an diesen Stellen es ggf. ähnliche/gleiche Probleme nun zu erwarten sind?

**Comment by detLAN** [comment]
> Ok, ich denke ich hab es. Ersetzt man die Zeile 1513 in `cp_security.cgi` die so aussieht:
> 
> ```tcl
> puts "translatePage();"
> ```
> 
> gegen folgende
> 
> ```tcl
> puts "translatePage('#messagebox');"
> ```
> 
> Dann wird die Seite mit korrekten Übersetzen angezeigt/dargestellt. Wäre einfach zu korrigieren.

Hab ich so umgesetzt und funktioniert 😀

**Comment by jens-maus** [comment]
> > Dann wird die Seite mit korrekten Übersetzen angezeigt/dargestellt. Wäre einfach zu korrigieren.
> 
> Hab ich so umgesetzt und funktioniert 😀

Dann "klicker" dich mal hier/da durch um sicherzustellen das die Übersetzung nicht an anderen Stelle auch noch kaputt gegangen ist. Interessant wäre z.B. mal die Gerätekonfiguration eine HM-CC-TC Funk-Wandthermostates anzuzeigen um zu schauen ob es da ggf. irgendwelche Probleme gibt (sieht man ja in der Auflistung der `translatePage()` Nutzungen).

**Comment by detLAN** [comment]
Okay, mache ich gerne - kann aber nur HmIP Geräte prüfen.

**Comment by theimo1221** [comment]
> Die Frage ist nur ob @theimo1221 sich das erklären kann? 
Ja, weil translatePage eigentlich nur eine nach außen besser benamte Funktion ist, selber aber ja nur druchschleift:

![image](https://user-images.githubusercontent.com/20605452/127885760-6738f263-b174-421c-be33-6daddb62ceb6.png)


> Auch müsste man folglich mal suchen ob das `translatePage()` irgendwie wie hier ohne Argumente aufgerufen wird und das eigentlich ein valider aufruf ist/sein soll?!?

Ja vom Prinzip schon, denn dann werden die 4 Standardbereiche genommen (`#header, #menubar, #content, #footer`).
Sind dann aber wieder fast alle Elemente auf der Seite, da sollte man schon etwas präzisieren:

![image](https://user-images.githubusercontent.com/20605452/127886083-53cd27f3-d16e-409d-a944-3f94eba42c6f.png)

**Comment by jens-maus** [comment]
@theimo1221 Ok, dann bedeutet das, das an den anderen Stellen es durchaus valide sein kann `translatePage()` ohne Argumente zu schreiben weil dort nur `#header, #menubar, #content, #footer` gebraucht wird. Aber an der besagten Stelle wurde eben `#messagebox' benötigt und deshalb ging das schief. Müsste man nur mal schauen ob man die anderen Stellen noch irgendwie programmtechnisch kontrollieren könnte ob die nun valide sind oder nicht wenn sie translatePage ohne Argumente aufrufen.

**Comment by theimo1221** [comment]
Andere Bereiche haben hierbei auch "nur" 450 Elemente:
![image](https://user-images.githubusercontent.com/20605452/127886868-3d7e40b9-d264-4c92-b6e4-ae90ea48cc7c.png)

**Comment by jens-maus** [comment]
Der morgige nightly snapshot wird die änderung ja nun beinhalten. Lassen wir es einfach mal drauf ankommen ob es irgendwie Probleme geben wird. Denn abgesehen davon wüsste ich jetzt nicht wie ich die Stellen die ich noch aufgelistet habe irgendwie testen könnte ob ein translatePage Aufruf ohne Argument dort nun valide ist oder nicht.

**Comment by detLAN** [comment]
> > > Dann wird die Seite mit korrekten Übersetzen angezeigt/dargestellt. Wäre einfach zu korrigieren.
> > 
> > 
> > Hab ich so umgesetzt und funktioniert 😀
> 
> Dann "klicker" dich mal hier/da durch um sicherzustellen das die Übersetzung nicht an anderen Stelle auch noch kaputt gegangen ist. Interessant wäre z.B. mal die Gerätekonfiguration eine HM-CC-TC Funk-Wandthermostates anzuzeigen um zu schauen ob es da ggf. irgendwelche Probleme gibt (sieht man ja in der Auflistung der `translatePage()` Nutzungen).

Für die folgenden Geräte kann ich bestätigen, dass die Dialoge i.O. sind:

HmIP-ASIR-2
HmIP-BRC2
HmIP-BROLL
HmIP-BSM
HmIP-eTRV-2
HmIP-FSI16
HmIP-FSM
HmIP-PCB
HmIP-PCBS2
HMIP-PS
HMIP-PSM
HmIP-RC8
HmIP-SAM
HmIP-SCI
HmIP-SLO
HmIP-SMI
HmIP-SMI55
HmIP-SMO
HmIP-SRH
HmIP-STHD
HmIP-STHO
HmIP-SWDM
HMIP-SWDO
HMIP-SWDO-I
HmIP-SWO-PR
HmIP-SWSD
HMIP-WRC2
HmIP-WRCD
RPI-RF-MOD

**Comment by jens-maus** [comment]
So, mit dem aktuellen nightly snapshot sollte - soweit ich das sehe - das problem nun beseitigt sein.
