### ISSUE TITLE
WebUI: Infoseite im Loginscreen fehlt.

### ISSUE THREAD

**Issue by detLAN** [jens-maus/RaspberryMatic#1358]
**Describe the bug**
Die Informationsseite fehlt

**Steps to reproduce the behavior**
1. Im Anmeldebildschirm auf das Fragezeichen klicken.
2. ... 
3. ...
4. ...

**Expected behavior**
Darstellung der Informationsseite

**Screenshots**
<img width="673" alt="Info1" src="https://user-images.githubusercontent.com/64675966/127812287-1cca1f82-8a23-4fef-aa24-5cf1df26acf9.png">
<img width="673" alt="Info2" src="https://user-images.githubusercontent.com/64675966/127812331-8f88a5ce-4ae6-408c-ae7c-19425a28049d.png">

**System information:**
 - RaspberryMatic Version: RaspberryMatic-3.59.6.20210802-5f20a3
 - Used Hardware: Raspberry Pi 4
 - Used HomeMatic RF-Module: RPI-RF-MOD

**Additional context**
...

**Comment by jens-maus** [comment]
Ist das nur im nightly build so oder was sollte auf dieser infoseite zu sehen sein?

**Comment by detLAN** [comment]
Ich hab jetzt kein weiteres System hier um einen Screenshot davon zu machen, auch klicke ich da für gewöhnlich nicht drauf. Habe nur nach dem [#1357](https://github.com/jens-maus/RaspberryMatic/issues/1357#issue-957779262) gedacht, dass ich einfach mal alle Dialoge aufrufe. Auf der Infoseite stehen eigentlich Informationen zum System - Seriennummer, Copyright usw.

**Comment by Baxxy13** [comment]
Da ist schon ewig nichts mehr hinterlegt. Siehe [Thread zur 3.57.4.20210320](https://homematic-forum.de/forum/viewtopic.php?f=65&t=66446&p=652911#p652911)

**Comment by detLAN** [comment]
Habe gerade mal das originale, ursprüngliche CCU3 Image auf einen Raspberry Pi 3 eingespielt, um einen Screenshot der Infoseite anzufertigen. Leider hab ich vergessen, dass dieses Image sofort ein Update machen will, bevor es losgehen kann. Und wie @Baxxy13 bereits schrieb, ist dieser Fehler danach dann auch im original CCU3 Image vorhanden.

Aus diesem Grund mach ich hier zu. 

<img width="982" alt="Info3" src="https://user-images.githubusercontent.com/64675966/127821101-89029347-2adc-4210-974d-5db3698af784.png">

**Comment by detLAN** [comment]
Habe gerade mal das originale, ursprüngliche CCU3 Image auf einen Raspberry Pi 3 eingespielt, um einen Screenshot der Infoseite anzufertigen. Leider hab ich vergessen, dass dieses Image sofort ein Update machen will, bevor es losgehen kann. Und wie @Baxxy13 bereits schrieb, ist dieser Fehler danach dann auch im original CCU3 Image vorhanden.

Aus diesem Grund mach ich hier zu. 

<img width="982" alt="Info3" src="https://user-images.githubusercontent.com/64675966/127821101-89029347-2adc-4210-974d-5db3698af784.png">

**Comment by jens-maus** [comment]
Nun, wenn es definitiv ein Fehler auch in der CCu3 Firmware ist, so ergibt sich hier trotzdem potential für Verbesserungen bzw einen Dix. Man müsste das ganze also mal analysieren und schauen warum auf einer CCU3 firmware hier das auch nicht geht und dann für RaspberryMatic einen Fix erarbeiten. Insofern kann dieses issue gerne bis nach dieser analyse offen bleiben.

**Comment by detLAN** [comment]
Dabei kann ich jedoch leider nicht behilflich sein, bin kein Programmierer, "nur" Endanwender.

Bin aber gern bereits Test durchzuführen und hier zu berichten.

**Comment by Baxxy13** [comment]
Ein klick auf den Button gibt folgende Fehlermeldungen in der Console:
(CCU 3.59.6 / RM 3.59.6.20210728-3a216d-rpi3
```
Uncaught SyntaxError: unexpected token: identifier
    evalScripts http://192.168.1.66/webui/js/extern/prototype.js:399
    collect http://192.168.1.66/webui/js/extern/prototype.js:640
    each http://192.168.1.66/webui/js/extern/prototype.js:600
    each http://192.168.1.66/webui/js/extern/prototype.js:599
    collect http://192.168.1.66/webui/js/extern/prototype.js:639
    evalScripts http://192.168.1.66/webui/js/extern/prototype.js:399
    bind http://192.168.1.66/webui/js/extern/prototype.js:214
    delay http://192.168.1.66/webui/js/extern/prototype.js:236
    setTimeout handler*delay http://192.168.1.66/webui/js/extern/prototype.js:235
    curry http://192.168.1.66/webui/js/extern/prototype.js:229
    update http://192.168.1.66/webui/js/extern/prototype.js:1612
    _methodized http://192.168.1.66/webui/js/extern/prototype.js:251
    updateContent http://192.168.1.66/webui/js/extern/prototype.js:1471
    onComplete http://192.168.1.66/webui/js/extern/prototype.js:1450
    bind http://192.168.1.66/webui/js/extern/prototype.js:214
    respondToReadyState http://192.168.1.66/webui/js/extern/prototype.js:1322
    onStateChange http://192.168.1.66/webui/js/extern/prototype.js:1249
    bind http://192.168.1.66/webui/js/extern/prototype.js:214
    request http://192.168.1.66/webui/js/extern/prototype.js:1230
    initialize http://192.168.1.66/webui/js/extern/prototype.js:1190
    wrap http://192.168.1.66/webui/js/extern/prototype.js:243
    value http://192.168.1.66/webui/js/extern/prototype.js:92
    bind http://192.168.1.66/webui/js/extern/prototype.js:214
    initialize http://192.168.1.66/webui/js/extern/prototype.js:1454
    wrap http://192.168.1.66/webui/js/extern/prototype.js:243
    klass http://192.168.1.66/webui/js/extern/prototype.js:53
    loadHelp http://192.168.1.66/logout.htm?sid=@ZY3y2IX8zE@?lang=de:88
    onclick http://192.168.1.66/logout.htm?lang=de:1
```

Ich teste mal einen ältere CCU 3.51.6, weiter zurück kann ich leider nicht.

**Comment by detLAN** [comment]
Wenn Du weisst, wie man den Zwang zum Update beim originalen, ursprünglichen CCU3 Image unterbrechen kann, könnte ich Dir dies zur Verfügung stellten.

**Comment by Baxxy13** [comment]
Passt schon. ;-) Das "Original" Image ist ja eh keine vollwertige CCU-Software. Man muss immer irgendeine Firmware für vollen Funktionsumfang installieren. 
Meine 3.51.6 ist alt genug, da funktioniert das noch. :-)
![CCU3_3 51 6_Help_Button](https://user-images.githubusercontent.com/54898249/127875964-7d2e22d5-1c36-4c4c-8fd1-7757bbf8a426.JPG)
Grob gepeilt würde ich sagen es liegt an der fehlenden Session-ID die ja im ausgeloggten Zustand nicht existiert.
Ist aber nicht unbedingt mein Fachgebiet.
Hoffe das reicht für @jens-maus das Problem zu verifizieren.

**Comment by jens-maus** [comment]
Ja, danke das sollte in der Tat reichen das zu reproduzieren. Ist auf jeden fall kein nightly snapshot oder exklusives RaspberryMatic Problem. Leg es daher mal entsprechend "auf Halde" :)

**Comment by jens-maus** [comment]
So, denke ich hab das Problem gefunden und repariert. Scheint recht klein zu sein aber in der Tat ein upstream/CCU3 firmware problem. Siehe:

```patch
--- occu/WebUI/www/config/help.cgi.orig
+++ occu/WebUI/www/config/help.cgi
@@ -109,7 +109,7 @@
       puts "s += \"<table cellspacing='8' >\";"
       puts "s += \"<tbody>\";"
       puts "s += \"<tr>\";"
-      puts "s += \"<td style=\"vertical-align:middle;\" >\";"
+      puts "s += \"<td style='vertical-align:middle;' >\";"
       puts "s += \"<div class='FooterButton' onclick='goStart()'  style='text-align:center;'>Zur&uuml;ck\";"
       puts "s += \"</div>\";"
       puts "s += \"</td>\";"
```

D.h. hier hat einfach ein falsches Quoting in einer tabellendefinition die Anzeige der Webseite verhindert.

**Comment by detLAN** [comment]
Hab ich auch entsprechend angepasst und bekomme jetzt die Infoseite im Loginscreen angezeigt.
Die Sprungmarke **#memo-documentation** gibt es auf **https://raspberrymatic.de/** jedoch nicht.

<img width="734" alt="Info" src="https://user-images.githubusercontent.com/64675966/127889724-ebb8a3e3-f862-4359-a2d5-0e17af42e004.png">

**Comment by detLAN** [comment]
Hab ich auch entsprechend angepasst und bekomme jetzt die Infoseite im Loginscreen angezeigt.
Die Anker (Sprungmarke) **#memo-documentation** gibt es auf **https://raspberrymatic.de/** jedoch nicht (Link im linken Block).

<img width="734" alt="Info" src="https://user-images.githubusercontent.com/64675966/127890920-7a731651-9804-461e-9e80-4aa586c01446.png">
