### ISSUE TITLE
Gerät aus Heizungsgruppe entfernen nicht möglich

### ISSUE THREAD

**Issue by detLAN** [jens-maus/RaspberryMatic#1359]
**Describe the bug**
Gerät aus Heizungsgruppe entfernen nicht möglich 

**Steps to reproduce the behavior**
1. Startseite > Gruppen
2. Gruppe bearbeiten
3. Gerät entfernen
4. OK

**Expected behavior**
Gerät sollte aus der Gruppe entfernt werden.
**Screenshots**
<img width="1285" alt="Bild1" src="https://user-images.githubusercontent.com/64675966/127979845-c41f5eab-5372-4f41-a1f7-b02a7b894f4e.png">

<img width="1285" alt="Bild2" src="https://user-images.githubusercontent.com/64675966/127979867-0aee5397-a446-45c9-b925-4cb374965113.png">

<img width="1285" alt="Bild3" src="https://user-images.githubusercontent.com/64675966/127979887-c0e17d10-adbf-426b-80fd-cbdc394a3dbd.png">

**System information:**
 - RaspberryMatic Version: RaspberryMatic-3.59.6.20210803-07da2a
 - Used Hardware: Raspberry Pi 4
 - Used HomeMatic RF-Module: RPI-RF-MOD

**Additional context**
CCU bleibt im Dialog "Gruppe wird gespeichert ..." stehen und man muss sich an der CCU neu anmelden. Das Gerät ist dann jedoch immer noch in der Gruppe. Selbst verständlich habe ich es auch versucht und bei den Gruppengeräten die Systemtaste betätigt - gleiches Fehlerbild.

Bitte auch das zweite Bild betrachten, dort wird das Bild des entfernten Geräts nicht dargestellt.

**Comment by detLAN** [comment]
Ich kann [#1358](https://github.com/jens-maus/RaspberryMatic/issues/1358#issue-957787490) nicht wieder öffnen, deshalb hier kurz der Hinweis, dass der verlinkte Anker auf der RaspberryMatic Seite nicht existiert. Hatte ich gestern noch dazugeschrieben, als das Ticket schon geschlossen war.

**Comment by detLAN** [comment]
Das Problem besteht auch in der Release RaspberryMatic 3.59.6.20210703!

**Comment by jens-maus** [comment]
Das gesamte Heizungsgruppenmanagement findet im Closed-Source Teil der OCCU Firmware statt auf die das RaspberryMatic keinerlei Einfluss/Zugriff hat. Insofern kann diesbzgl. leider auch nichts unternommen werden. Ein generelles Problem existiert hier jedoch nicht und das muss eher gerätebezogen sein. Insofern sehe ich hier keinerlei Handlunsgbedarf.

**Comment by detLAN** [comment]
Habe jetzt wieder meinen Raspberry Pi 3 rausgekramt, das original CCU3 Image installiert und das Update auf 3.59.6 eingespielt. Hier genau das gleiche Problem, so dass ich dies einmal an eQ-3 melden werde.
