### ISSUE TITLE
WebUI: System variable look optimization

### ISSUE THREAD

**Issue by HMside** [jens-maus/RaspberryMatic#136]
Optimierung der Systemvariablen Darstellung:

1. Da der Name der jeweiligen Systemvariable in allen Ansichten (Status und Bedienung > Systemvariablen sowie Favoriten und Favoriten auf der Startseite) doppelt angezeigt wird, wurde der Name in der Wertespalte entfernt.

Erforderliche Änderungen:
In der www/rega/esp/datapointconfiguration.fn
Zeile 1192 löschen >> 
`WriteLine( '<span class="CLASS02534">'#sName#':  </span>' );`

2. Zur besseren Platzausnutzung der Favoriten auf der Startseite wurden die grauen und leeren Zeilen über und unter dem jeweiligen Eintrag entfernt.

Erforderliche Änderungen:
In der www/rega/pages/tabs/startpage.htm
Die Zeilen 117-119 und 143-145 löschen >>

```
Write('<tr>');
Write('<td class="CLASS01808"></td>');
Write('</tr>');
```

3. Zur besseren Platzausnutzung der Favoriten unter Status und Bedienung wurden die grauen und leeren Zeilen über und unter dem jeweiligen Eintrag entfernt.

Erforderliche Änderungen:
In der www/rega/esp/datapointconfiguration.fn
Die Zeilen 36-39 sowie 49-52 löschen >>

```
    WriteLine('<tr>');
      WriteLine('<td class="CLASS02506"></td>');
      WriteLine('<td class="CLASS02506"></td>');
    WriteLine('</tr>');
```

4. Stylesheet Anpassungen

Erforderliche Änderungen:
In der www/webui/style.css

Automatische Zeilen Höhe für die Favoriten auf der Starseite:
```
.CLASS01812 {
	background-color:$_(activeBackground);
	width:580px;
	height:auto;
	border:solid 1px $_(black); /* black */
	color: $_(textColorB); /* black */
}
```

Automatische Zeilen Höhe für Status und Bedienung > Favoriten:
```
.CLASS02508 {
	background-color:$_(activeBackground);
	width:520px;
	max-width:502px;
	height:auto;
	border:solid 1px $_(black); /* black */
	color: $_(textColorB); /* black */
	overflow:auto;
}
```

Anpassung für den Wert der Systemvariablen
```
.CLASS02535 {
  text-align:center;
  width: 98%;
  word-wrap: break-word;
  max-width: 480px;
}
```

Anpassung der ersten inneren Zelle
```
.CLASS02537 {
  padding: 5px;
  width: 100%;
  background-color: $_(activeBackground) ! important;
}
```

Anpassungen der zweiten inneren Zelle
```
.CLASS02538 {
  text-align: center;
  width: 98%;
  max-width: 480px;
  height: auto;
  background-color: #F0F0F0;
  color: black;
  border: 0;
}
```

Vorher/Nacher Vergleich:
![changes](https://user-images.githubusercontent.com/13312068/29217804-12d2378c-7eb3-11e7-9969-c67be3b120b7.jpg)

**Comment by jens-maus** [comment]
Danke erst einmal für diese ausführliche Beschreibung. Allerdings wäre es wirklich gut und würde die integration wesentlich vereinfachen wenn du entsprechende "diff" files bereit stellen könntest. D.h. z.b. ein `diff -u <ORIGINAL> <NEU>` unter Unix aufrufen und er sollte eine kompatible diff datei generieren.

**Comment by jens-maus** [comment]
Hast du dir auch mal angeschaut wie das ganze mit deinen Änderungen aussieht wenn du eine systemvariable so z.B. einem gerät zuordnen lässt? Siehe https://homematic-forum.de/forum/download/file.php?id=30833&mode=view

Ggf. führt deine Änderung des entfernen des zusätzlichen namens so ja dazu das dort die systemvariable nicht benannt wird.

**Comment by HMside** [comment]
Das mit dem diff-File schaue ich mir an. Bei Kanalzuordnung bleibt der Name erhalten und sieht aktuell so aus:

![bildschirmfoto 2017-08-11 um 17 22 15](https://user-images.githubusercontent.com/13312068/29219932-d4709e32-7eb9-11e7-8176-bcf893e890fe.png)

**Comment by jens-maus** [comment]
Danke für den Screenshot. Ich muss allerdings sagen das dies so doch wesentlich anders aussieht als bei einer Standard CCU2. Insofern werden die Chancen recht schlecht stehen das so integriert zu bekommen von eQ3. Zwei Dinge würde dich bitten bzgl. deiner Anpassungen noch verändern:

1. Bitte die normalerweise schwarze Umrandung beibehalten (gerade bei den Kanalzuordnungen sieht das ansonsten komisch aus)
2. Meiner Meinung nach sollte der Text der Systemvariablen rechtsbündig sein wie das auch in der Standard CCU2 der Fall ist. Du musst dabei daran denken das Systemvariablen mitunter  (und wohl sehr oft) Einheiten haben können und die ansonsten untereinander nicht geordnet dargestellt werden (siehe screenshot)
![screenshot_131](https://user-images.githubusercontent.com/5887769/29231105-33d62c1c-7ee6-11e7-9845-168398ca0433.png)
Oder ist dies bereits mit deinen Änderungen der Fall?

**Comment by HMside** [comment]
Ich habe mir das heute nochmal mit der Kanalzuordnung angeschaut, das neue Design sieht gerade dort echt bescheiden aus. Bin wieder zurück zum Ursprungsdesign mit entsprechenden Optimierungen. Werde wahrscheinlich morgen die diffs anfügen.

**Comment by HMside** [comment]
Anbei die mittels diff erstellten [patches.zip](https://github.com/jens-maus/RaspberryMatic/files/1222891/patches.zip).

In der style.css wird bei CLASS02532 darauf hingewiesen, dass die Zeilenhöhe lediglich 25px betragen darf, ich habe bisher keinen negativen Auswirkung durch meine Anpassung entdecken können.
`/* line-height:25px; problem with controls with a long parameter name */`

![changes](https://user-images.githubusercontent.com/13312068/29282399-f0600ebe-8122-11e7-9843-e8c7e967a7c7.png)

**Comment by jens-maus** [comment]
Danke, das sieht sehr viel besser aus! Da ich darüber hinaus eigentlich keinerlei weitere Probleme mehr mit deinen Anpassungen gefunden habe, habe ich diese kurzerhand integriert und sie sollten somit mit der nächsten RaspberryMatic Version ausgeliefert werden. Danke nochmal für dieses genial Patchset!

**Comment by jens-maus** [comment]
@HMside Nach weiteren Tests bzgl. deiner Anpassungen an den Look der Systemvariablen habe ich doch noch zwei Hinweise:

1. Leere Systemvariablen bekommen ein zu kleines graues Fenster - siehe Systemvariablen Auszug:
![screenshot_153](https://user-images.githubusercontent.com/5887769/29864887-4d8e39b4-8d74-11e7-9192-da8275361dd7.png)
Wie man sieht ist die mittlere Systemvariable komplett leer und dadurch wird die graue Box zu klein dargestellt. Wenn möglich sollte diese immer mindestens so groß sein wie wenn ein einzeiler Text sich darin befindet.

2. Wenn man Systemvariablen mit einem Device verknüpft gibt es den leicht grauen Hintergrund nicht mehr wie in vorherigen Versionen:
![screenshot_154](https://user-images.githubusercontent.com/5887769/29864927-6d37320c-8d74-11e7-9a30-5e9136165465.png)
Hier sollte hinter den Systemvariablen "Gas Verbrauch aktuell", etc. ein grauer Hintergrund sein damit klar gestellt ist das dies verknüpfte Systemvariablen sind und keine Aktor/Device-Eigenen Ausgaben.

Beide Dinge würde ich dich bitte noch anzupassen und ein entsprechendes Diff bereit zu stellen.
