### ISSUE TITLE
Unnötiger, nichtsaussagender Dialog

### ISSUE THREAD

**Issue by detLAN** [jens-maus/RaspberryMatic#1365]
**Describe the bug**
Ändern des Modus (Normal- / Flüsterbetrieb) in einer Heizungsgruppe

**Steps to reproduce the behavior**
1. Heizungsgruppe wählen
2. Modus ändern

**Expected behavior**
Ändert man den Modus nur beim Heizkörperthermostat, kommt kein Dialog. So sollte es eigentlich auch bei der Heizungsgruppe sein, da man ja immer die Gruppe ändern soll, anstatt den Heizkörperthermostat.

**Screenshots**
<img width="944" alt="2021-08-08_13-44-14" src="https://user-images.githubusercontent.com/64675966/128631042-aa7a0aff-6ff5-4ea4-b3d2-28059a094a09.png">

**System information:**
 - RaspberryMatic Version: 3.59.6.20210807
 - Used Hardware: Raspberry Pi 4
 - Used HomeMatic RF-Module: RPI-RF-MOD

**Additional context**
Wenn dies wieder im Closed-Source Teil der OCCU Firmware sein sollte, dann würde ich auch dies an eQ-3 weitergeben.

**Comment by Maik2208** [comment]
Der Fehler ist in der Datei `config/easymodes/etc/hmipChannelConfigDialogs.tcl`

> Wenn dies wieder im Closed-Source Teil der OCCU Firmware sein sollte, dann würde ich auch dies an eQ-3 weitergeben.

@jens-maus 
Ich bin jetzt etwas irritiert aber wenn ich die Lizenzbedingungen richtig verstehe, dann darf ich an tcl-Dateien ändern, oder?
--> Falls ja, mache ich gerne einen PR aus meiner Korrektur.

**Comment by jens-maus** [comment]
Ja klar darfst du die ändern - wenn du den PR dieses mal (wie man das macht) via einem separatem Branch einsendest und nicht basierend in dem master branch deines forks ;)

**Comment by detLAN** [comment]
Wenn Ihr die Zeile komplett entfernt, dann erhaltet ihr dies hier:

<img width="989" alt="2021-08-09_09-12-11" src="https://user-images.githubusercontent.com/64675966/128671497-10ed6862-fa2f-4927-a636-fe9de233e89c.png">

Ein Ändern des Modus wäre damit nicht mehr möglich.


Ihr dürft die Zeile nicht komplett löschen, sondern nur einen Teil daraus:
> append html "[get_ComboBox options $param separate_$CHANNEL\_$prn ps $param **_onchange=\"alert(this.value,$chn)\"_**]&nbsp;[getHelpIcon $param $hlpBoxWidth [expr $hlpBoxHeight * 0.75]]"

Die Zeile sollte dann so aussehen:
> append html "[get_ComboBox options $param separate_$CHANNEL\_$prn ps $param]&nbsp;[getHelpIcon $param $hlpBoxWidth [expr $hlpBoxHeight * 0.75]]"

**Comment by Maik2208** [comment]
Hab ich doch gemacht?!

**Comment by detLAN** [comment]
> Hab ich doch gemacht?!

Oh sorry, hab nur den ersten Teil gesehen. Also einfach meinen Post vergessen, alles prima.
