### ISSUE TITLE
WebUI: sticky Filter wird auch an falscher Stelle verwendet

### ISSUE THREAD

**Issue by NorfolkXX** [jens-maus/RaspberryMatic#1367]
a) Wenn in der Ansicht "Programme und Verknüpfungen">"Programme & Zentralenverknüpfung" in der 1. Spalte "Name" ein Filter gesetzt ist, dann wirkt dieser Filter fälschlicherweise auch beim Aufruf der Seite "Status und Bedienung">"Geräte" im rechten Bildteil auf die 1. Spalte "Kanal".  
Dies tritt immer bei Aufruf der Geräte-Seite über das Hauptmenü auf. Wird danach auf der Geräte-Seite ein Gerät ausgewählt, hebt dies den "falschen" Filter auf.

b) Die Seiten "Programme und Verknüpfungen">"Programme & Zentralenverknüpfung" und "Status und Bedienung">"Systemvariablen" verwenden in der 1. Spalte "Namen" den selben Filter, d.h. wird auf einer der zwei Seiten ein Filter hinterlegt/gelöscht, gilt dies auch für die andere der zwei seiten.

Das Problem besteht bei mir auf der RaspberryMatic 3.59.6.210703 auf "ELV-Charly" RPi3 mit RF-Mod, als Browser verwende ich Chrome 92.0.4515.131

**Comment by Baxxy13** [comment]
Ja, die lieben sticky Filter. 
Da klemmt's an einigen Stellen. Es gibt (gab) ja schon mehrere Tickets dazu. 
Auch von mir... #953

**Comment by jens-maus** [comment]
Duplicate of #953
