### ISSUE TITLE
Fehler bei Installation von Zusatzsoftware im Home Assistant Raspberrymatic Add On

### ISSUE THREAD

**Issue by king1979** [jens-maus/RaspberryMatic#1368]
**Describe the bug**
Ich habe das Update heute auf meinem HA Addon durchgeführt.
Danach wollte ich noch meine Zusatzsoftware (XML-API Addon 1.21, hm_pdetect 1_8) auf die aktuelle Version bringen.
Nach dem erfolgreichen Upload und dem klick auf Installation starten erscheint folgende Meldung:

> Error 102
Ein unerwarteter Fehler ist während der Addon-Installation aufgetreten.
Bei der hochgeladenen Datei handelt es sich entweder nicht um ein Addon-Archiv, ist defekt oder ist für eine andere Hardware vorgesehen.
Bitte versuchen Sie es erneut oder kontaktieren Sie den Autor des Addons.

**Steps to reproduce the behavior**
1. Einstellungen - Systemsoftware - Zusatzsoftware
2. Zusatzsoftware installieren / aktualisieren - Datei auswählen - hm_pdetect-1.8.tar.gz oder xmlapi_addon-1.21.tar.gz - Installieren
3. Datei wurde hochgeladen - Installation starten
4. Error 102

**Expected behavior**
...

**Screenshots**
![Fehler 102](https://user-images.githubusercontent.com/29041788/128639663-60c8316e-d796-45db-83fd-cfca5b33926d.png)

**System information:**
 - RaspberryMatic Version: 3.59.6.20210807
 - Used Hardware: Raspberry Pi 4 Mod. B 4GB Ram
 - Used HomeMatic RF-Module: HM-MOD-RPI-PCB / HB-RF-USB

**Additional context**
Home Assistant (Supervised): Core 2021.8.4
Supervisor: 2021.06.8
Thema im HomeMatic-Forum: [https://homematic-forum.de/forum/viewtopic.php?f=65&t=69013&p=674190#p674190](url)

**Comment by jens-maus** [comment]
Das Problem sollte mit dem nächsten nightly snapshot beseitigt sein.
