### ISSUE TITLE
Ventil-Öffnungsgrad zweimal beim HmIP-eTRV-C-2

### ISSUE THREAD

**Issue by detLAN** [jens-maus/RaspberryMatic#1374]
**Describe the bug**
Der Ventil-Öffnungsgrad wird beim HmIP-eTRV-C-2 zweimal darstellt.

**Steps to reproduce the behavior**
1. Startseite > Status und Bedienung > Geräte
2. HmIP-eTRV-C-2 auswählen

**Expected behavior**
Der Ventil-Öffnungsgrad sollte nur einmal dargestellt werden.

**Screenshots**
<img width="948" alt="2021-08-09_21-18-09" src="https://user-images.githubusercontent.com/64675966/128763415-58aa346b-355f-4d01-a8fd-1e719877ad67.png">

**System information:**
 - RaspberryMatic Version: 3.59.6.20210809
 - Used Hardware: Raspberry Pi 4
 - Used HomeMatic RF-Module: RF-Module: RPI-RF-MOD

**Additional context**
Beim HmIP-eTRV-2 ist es okay, aber evtl. ist auch der HmIP-eTRV-C betroffen.

**Comment by jens-maus** [comment]
Besteht das problem nach einem Reboot noch? Dieses verdoppeln von WebUI Elementen ist leider ein altbekannter Bug in der WebUI der auf ein fehlerhaftes Caching zurückzuführen ist und hierbei nur ein Neustart der Zentrale bzw. von `ReGaHss` zu helfen scheint.

**Comment by detLAN** [comment]
> Besteht das problem nach einem Reboot noch? Dieses verdoppeln von WebUI Elementen ist leider ein altbekannter Bug in der WebUI der auf ein fehlerhaftes Caching zurückzuführen ist und hierbei nur ein Neustart der Zentrale bzw. von `ReGaHss` zu helfen scheint.

Problem besteht nach Neustart von 'ReGaHss' weiter. Zur Sicherheit habe ich auch die Zentrale noch einmal neugestartet, was jedoch auch keine Besserung gebraucht hat.

**Comment by jens-maus** [comment]
Ok, dann ist das ggf in der Tat ein anderer Bug. Allerdings hab ich selbst keinen HmIP-eTRV-C-2 und so müssen wir mal warten wer noch so ggf darüber stolpert und das weiter analysieren kann.

**Comment by Maik2208** [comment]
Der obere Ventil-Öffnungsgrad enthält den Wert `cObj.DPByControl("HEATING_CONTROL_HMIP.LEVEL")`, der untere `cObj.DPByHssDP("LEVEL")`.

Wo jetzt der Unterschied liegt, weiß ich nicht.

**Comment by detLAN** [comment]
Ich hab mal den Thermostat arbeiten lassen, die beiden Werte für den Ventil-Öffnungsgrad sind immer identisch.

In welcher Datei sind die Werte versteckt? Ich könnte dann mal ausprobieren was passiert, wenn ich den einen oder andern ausklammere.

**Comment by jens-maus** [comment]
Ich denke ich hab den Grund gefunden. eQ3 hat wohl in einer der letzten CCU Firmware-Updates selbst funktionalität hinzugefügt um den Ventilöffnungslevel von HmIP Geräten in der WebUI darstellen zu lassen. Das hatten wir im Rahmen von RM ja im 0042 WebUI Patch damals umgesetzt. Die Lösung des ganzen sollte sein das du die folgende Zeile:

https://github.com/jens-maus/RaspberryMatic/blob/4397b7cf7460a6611042e5dfe2ed5dea33c8ef54/buildroot-external/patches/occu/0042-WebUI-HeatingControl-BatteryValveState/occu/WebUI/www/rega/esp/controls/heating_control.fn#L331

in der Datei `/www/rega/esp/controls/heating_control.fn`gegen diese auswechselst:

```tcl
if ((oValveLevel) && !(oLevel)) {
```

Danach dann ReGaHss neustarten.

Schau mal ob das funktioniert und ob dann nur noch eine Ventilöffnungslevelbox übrig bleibt. Auch bitte mal mit einem anderen HmIP-eTRV (nicht C-2) probieren ob es da auch noch passt nach dieser Änderung.

**Comment by jens-maus** [comment]
Ok, hab das nochmal etwas mehr überarbeitet weil mir die Anpassungen von eQ3 nicht wirklich zugesagt haben, denn wenn sich der ventilöffnungsgrad während der darstellung geändert hatte wurde der nicht zwangsläufig aktualisiert. das sollte jetzt der fall sein. Wer also gerne die Anpassungen vor dem nächsten nightly snapshot morgen testen möchte müsste diesen patch nun umsetzen:

https://github.com/jens-maus/RaspberryMatic/commit/934f70e01ac6f26c5338bba65a6adf0e305b6bcf#diff-ee3da58904dd28a78cb20131452430ff42fb85c24ab5893dcf5af7dc0b8a6bee

Ansonsten wie gesagt auf die morgigen nightly snapshot warten und dann entsprechend berichten ob es passt oder ob das Problem mit der doppelten Darstellung immer noch existiert.

**Comment by detLAN** [comment]
Da warte ich auf den neuen Snapshot und gebe dann bescheid.

**Comment by detLAN** [comment]
Mit der neuen Snapshot Version 3.59.6.20210811 ist der Fehler behoben, die Darstellung beim HmIP-eTRV-C-2 korrekt. Der HmIP-eTRV-2 ist nach wie vor korrekt. Vielen Dank.

P.S.: auf https://raspberrymatic.de/de/home/ fehlt eine Grafik (cropped-250297_w01_charly-trans-5.png)
