### ISSUE TITLE
Nightly RaspberryMatic-3.59.6.20210811-7ac604 --> kein Booten eines Pi3B / Pi3B+

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1378]
**Describe the bug**
Mit dem heutigen Nightly bootet ein Pi3B / Pi3B+ nicht mehr. Ein angeschlossener Monitor blitzt bloß kurz auf. Die grüne Raspi-LED blinkt in einem kurzen Rhythmus, weiter passiert nichts.

**Steps to reproduce the behavior**
1. Pi3B / Pi3B+ mit Nigtly 3.59.6.20210811-7ac604 versuchen zu booten
2. ...
3. ...
4. ...

**Expected behavior**
...

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: Nigtly 3.59.6.20210811-7ac604
 - Used Hardware: Pi3B / Pi3B+
 - Used HomeMatic RF-Module: none

**Additional context**
...

**Comment by Baxxy13** [comment]
Gleiches Problem mit Pi2B V1.1
rpi0 habe ich nicht und der rpi4 steht momentan nicht zum testen zur Verfügung.

**Comment by detLAN** [comment]
Raspberry Pi 4 Luft ganz normal mit der aktuellen Nigtly 3.59.6.20210811-7ac604, kein Problem beim booten.

**Comment by jens-maus** [comment]
Wie vielleicht gesehen, habe ich noch einmal etwas an diesem Ticket/Problematik verbessert. Darum würde ich bitte mit dem nächsten nightly snapshot von morgen bitte noch einmal ausführlich zu testen ob alle Pis weiterhin nun damit booten oder es zu irgendwelchen Problemen kommt. Bin aber zuversichtlich das ich den eigentlichen Ursprung des Problemes dieses Tickets hier gefunden und dauerhaft nun repariert habe.

**Comment by detLAN** [comment]
Auch mit dem Nightly Build Snapshots 3.59.6.20210813-4cee04 gibt es beim Booten des Raspberry Pi 4 keine Probleme.

**Comment by Baxxy13** [comment]
Für einen Pi3B / Pi3B+ kann ich bestätigen das diese (ab 3.59.6.20210813-4cee04) wieder korrekt booten.
