### ISSUE TITLE
WebUI: Add Filter/Sort for Programlist

### ISSUE THREAD

**Issue by HMside** [jens-maus/RaspberryMatic#138]
Mit dem angehängten Patch wird unter "Programme & Zentralenverknüpfung" das Filtern und Sortieren möglich.

![filter-sort](https://user-images.githubusercontent.com/13312068/29363661-29c67f2a-8291-11e7-9dd8-74906b12d507.png)

Zu patchen ist: /www/rega/pages/tabs/admin/views/programlist.htm

[programlist.htm.patch.zip](https://github.com/jens-maus/RaspberryMatic/files/1228180/programlist.htm.patch.zip)

**Comment by jens-maus** [comment]
Danke für diese weitere Änderung. Hab sie soeben direkt in RaspberryMatic integriert (siehe https://github.com/jens-maus/RaspberryMatic/commit/3c93ff5467d2b128f2379d01cd98d509ba6d3fe0). 

Für die Zukunft wäre es gut du könntest dir mal die Nutzung von Git bzw. GitHub und das Thema "Pull Requests" anschauen. Dann könntest du deine Anpassungen direkt als Pull Request senden. Das würde die integration wesentlich vereinfachen. Schau dir dazu einfach mal an welche Anpassungen ich so vorgenommen habe sodass du weisst welche Dateien du modifizieren musst. Im Grunde musst du lediglich im `buildroot-external/patches/homematic/homematic/` Pfad einmal die originale Datei als `*.orig` (aus dem aktuellen OCCU repo) und einmal in deiner Version nebeneinander ablegen, mehr nicht. Das Build Environment von RaspberryMatic macht dann den Rest.

**Comment by HMside** [comment]
Okay, das nächste Patch kommt via Pull Requests

**Comment by jens-maus** [comment]
Hab mir die Änderung (die inzwischen ja implementiert ist) nochmal angeschaut. Wirklich sehr brauchbar, danke. Wäre es aber möglich das du die gleiche Filterfunktion noch für das "Beschreibung" Feld hinzufügst?

**Comment by FraatRamski** [comment]
genau das habe ich mir schon immer gewünscht. Have ca. 100 Programme da ist das geht die Übersicht verloren. Hoffe die das nächste relase kommt bald mit dieser Erweiterung.
