### ISSUE TITLE
RaspberryMatic VM startet mit 3.59.6.20210807 nicht mehr (XCP-ng / Xen Server)

### ISSUE THREAD

**Issue by LaserPew** [jens-maus/RaspberryMatic#1381]
**Describe the bug**
Nach dem Upgrade auf 3.59.6.20210807 startet meine VM nicht mehr und bleibt beim booten beim Schritt "Starting xe-daemon..." hängen (siehe Screenshot). Auch eine Neuinstallation hat den gleichen Effekt. Nach einem downgrade auf 3.59.6.20210703 läuft wieder alles.

Ggf. eine Auswirkung von: "integrated improved XenServer support for the ova platform by modifying kernel configs and adding xe-guest-utilities as a dedicated buildroot package (cf. home-assistant/operating-system#1459)."?

**Steps to reproduce the behavior**
1. VM per WebUI (oder Recovery Mode) auf 3.59.6.20210807 updaten bzw. neue VM mit 3.59.6.20210807 aufsetzen.
2. VM starten.
3. VM bleibt beim Schritt "Starting xe-daemon..." hängen.

**Expected behavior**
VM sollte normal booten, wie in allen Versionen davor.

**Screenshots**
![Screenshot 2021-08-11 at 20 02 20](https://user-images.githubusercontent.com/222357/129094602-913a8c25-123a-4a14-869b-beabd789fedf.png)
![Screenshot 2021-08-11 at 21 28 34](https://user-images.githubusercontent.com/222357/129094620-b8b8e321-c73e-4721-b744-fcb637183d54.png)

**System information:**
 - RaspberryMatic Version: 3.59.6.20210807
 - Used Hardware: XCP-ng 8.2.0 (Xen Server) Hypervisor
 - Used HomeMatic RF-Module: HB-RF-ETH

**Comment by jens-maus** [comment]
So, das nächste nightly snapshot sollte das Problem beheben und die xe-guest-utilities nun korrekt hochfahren und nutzbarmachen für Xen-basierte VM Lösungen wie XCP-ng. 

Vielleicht könntest du das ja mit dem nächsten nightly snapshot (morgen) einmal testen und berichten. Schön wäre es auch noch wenn du vllt. basierend auf der Dokumentation der anderen Anleitungen zur Installation der ova von RM im Wiki (https://github.com/jens-maus/RaspberryMatic/wiki) einen entsprechenden Unterabschnitt zur Installation unter XCP-ng/XOA machen könntest und da vllt. sogar ein paar screenshots mitliefern könntest. Schön wäre es auch du könntest einmal dokumentieren wie man es schafft mittels XCP-ng das USB passthrough für die RM vm hinzubekommen. Das habe ich hier mit meinen Versuchen nicht so hinbekommen wie gedacht. Und andere Nutzer könnten das sicherlich auch gut finden. Hilfe / Unterstützung wäre hier also in der Tat eine gute Sache...

**Comment by LaserPew** [comment]
Kann ich gerne testen und auch entsprechend in der Wiki dokumentieren.
Wo finde ich denn das aktuelle Nightly OVA Image?

**Comment by LaserPew** [comment]
Habe die Nightly Builds gefunden, die `RaspberryMatic-3.59.6.20210815-84481c-ova.zip` eingespielt (per WebUI) und nun bootet die VM wieder ohne Probleme! ✅

Vielen Dank!

**Comment by jens-maus** [comment]
Super! Zusätzlich sollten nun auch Infos über die XE GuestAdditions in der VM auftauchen. Und bzgl Dokumentation hab ich prinzipiell schon angefangen da was zu dokumentieren. Siehe hier: https://github.com/jens-maus/RaspberryMatic/wiki/Installation-XCPng 

Was hier vor allem fehlt sind dann noch die schritte zum einbinden des hb-rf-usb. Das hab ich bei meiner testinstallation nicht hinbekommen. Hilfe wäre da angebracht.
