### ISSUE TITLE
NEO Addon Konfigurationsseite wird permanent "reloaded" bei HTTPS Umleitung

### ISSUE THREAD

**Issue by roe1974** [jens-maus/RaspberryMatic#1382]
**Describe the bug**
Nach Installation der aktuellen RM und Aufruf der Mediola Server Seite wir diese permanent "reloaded".
Wenn ein backup eingespielt wird, ist der Mediola Server nach dem reboot wieder "online" und die Seite verhält sich normal. Deaktiviert man jetzt den Mediola Server wieder mit einem `touch /usr/local/addons/mediola/Disabled` und rebootet die RM, dann ist der Aufruf der Mediola Seite wieder "fehlerhaft" (=permanentes reloading)

**System information:**
 - RaspberryMatic Version: ... 3.59.6.20210807
 - Used Hardware: ... Raspi P4B
 - Used HomeMatic RF-Module: ... RPI-RF-MOD

**Comment by jens-maus** [comment]
Ich kann das leider nicht nachvollziehen. Daher bitte mehr Infos. Welcher Browser, debug infos, usw. Denn hier kann ich die Datei `/usr/local/addons/mediola/Disabled` anlegen und sehe keinerlei permanentes reload im Browser (hier Chrome 92).

**Comment by roe1974** [comment]
Ich verwende Chrome Version 92.0.4515.131 (64-Bit)
Wenn ich eine neue leere RM installiere (dort ist ja /usr/local/addons/mediola/Disabled bereits vorhanden) habe ich das "Phänomen" sofort ...

**Comment by jens-maus** [comment]
Ich aber eben nicht. Dann zeig mal bitte welches "Phänomen" du genau meist. Mach mal bitte nen kurzen Screencast (animated gif) davon und zeig was du unter "permanent" reload verstehst. Denn hier sehe ich nicht das bei aufruf der Mediola NEO server systemsteuerung irgendetwas den browser dauerhaft "reloaded" wenn er da als status "disabled" zeigt.

**Comment by roe1974** [comment]
Der Fehler kommt/geht wenn Du unter "Sicherheit" ... "Umleitung auf HTTPS" aktivierst ..... ;-)

**Comment by jens-maus** [comment]
Na da haben wir es doch, ne neue Zusatzinfo ;) Probier ich später mal zu reproduzieren. In der Tat hat Mediola Ihr addon leider hier+da nicht so https fest gemacht bzw getestet und ich hab da schon vieles diesbzgl repariert.

**Comment by jens-maus** [comment]
Ok, konnte es nun reproduzieren. Nun muss ich nur noch den Fehler lokalisieren.
