### ISSUE TITLE
"Zusatzsoftware-Update verfügbar" auf Startseite anzeigen

### ISSUE THREAD

**Issue by jp112sdl** [jens-maus/RaspberryMatic#1384]
Bisher hat mich immer gestört, dass es keine Info gibt, wenn es Updates bzw. neue Versionen zu installierten Addons gibt.
Es wäre daher aus meiner Sicht praktisch, ähnlich wie eine neue RaspberryMatic Version oder Geräte-Updates, diese Info auf der Startseite mit anzuzeigen

<img width="712" alt="Bildschirmfoto 2021-08-18 um 19 58 44" src="https://user-images.githubusercontent.com/18190139/129948614-b06952b8-a5d1-43f5-823e-b8517573492b.png">

Kurz zum Workflow:
- ein Shell-Script prüft zyklisch (cron) die Updates online
  - _da dieser Abruf je nach Menge der installierten Addons lange dauert soll das nicht direkt im Browser laufen_
  - das Ergebnis wird im JSON-Format in einer Datei in `/tmp` abgelegt
 <details><summary>CODE</summary>
<p>

 ```BASH
  #!/bin/sh
jsonfile=/tmp/addon_updates.json
if [ ! -z "$(ls -A /etc/config/rc.d)" ]; then
  echo "[" > $jsonfile
  first=1
  for filename in /etc/config/rc.d/*; do
    if [ -f $filename ]; then
      DINFO=`$filename info`
      DNAME=`echo "$DINFO" | grep "Name: "|sed "s/Name: //g"`
      DVERSION=`echo "$DINFO" | grep "Version:"|awk '{print $2}'`
      DUPDATESCRIPT=`echo "$DINFO" | grep "Update:"|awk '{print $2}'`
      if [ ! -z $DUPDATESCRIPT ]; then
        QUERY_STRING='cmd=check_version\&version=$DVERSION'
        WEBRESULT=`export QUERY_STRING=$QUERY_STRING;tclsh /www${DUPDATESCRIPT}|grep "\."` 
        if [ "$first" -eq 1 ]; then 
          first=0
        else
          echo "," >> $jsonfile
        fi
        echo "{\"name\":\"$DNAME\",\"webversion\":\"$WEBRESULT\"}" >> $jsonfile
        if [ "$DVERSION" != "$WEBRESULT" ]; then
          echo "Update available for $DNAME ($DVERSION / $WEBRESULT)"
        fi
      fi
    fi
  done
  echo "]" >> $jsonfile
else
  [[ -f $jsonfile ]] && rm $jsonfile
fi
  ```

</p>
</details>

- beim Aufruf der WebUI wird die lokale Addon-Version mit der Version aus dem Online-Abruf in `/tmp` verglichen
- `/www/api/methods/ccu/getaddonversions.tcl`: 
<details><summary>CODE</summary>
<p>

```TCL
proc get_info {script array_var} {
  upvar $array_var arr
  foreach key [array names arr] { unset arr($key) }
  set lang "de"
  catch {
    set fd [open "|$script info.$lang" r]

   while { ! [eof $fd] } {
    set line [gets $fd]
    if { [regexp {^([^:]+): (.*)$} $line dummy key value] } {
      if { [info exists arr($key)] } {append arr($key) "\n"}
      append arr($key) $value
    }
  }
    close $fd
  }

  catch {
   set fd [open "|$script info" r]
   while { ! [eof $fd] } {
    set line [gets $fd]
    if { [regexp {^([^:]+): (.*)$} $line dummy key value] } {
      if { [info exists arr($key)] } {append arr($key) "\n"}
      append arr($key) $value
    }
  }
    close $fd
  }
}

set file "/tmp/addon_updates.json"
set result false
if { [file exists $file] == 1 } {
  catch {
    set result "{ \"online\":"
    set fd [open $file r]          
    while { ! [eof $fd] } {        
      append result [gets $fd]     
    }                              
    close $fd                     
  
    append result ", \"local\": \["
  
    set first 1
    set scripts ""
    catch { set scripts [glob /etc/config/rc.d/*] }
    foreach s $scripts {
      catch {
        if { ! [file executable $s] } continue
        array set sw_info ""
        get_info $s sw_info
        if { ![info exists sw_info(Name)] } continue
        if { [info exists sw_info(Version) ] } {
          if {1 != $first} then { append result "," } else { set first 0 }
          append result "\{\"name\":"
          append result "\"$sw_info(Name)\","
          append result "\"localversion\":"
          append result "\"$sw_info(Version)\""
          append result "\}"
        }
      }
    }
    append result "\]}"
  }
}
jsonrpc_response $result
#puts "$result"
```

</p>
</details>

- die Anzahl der Addons, für die es Update gibt, wird auf der Startseite angezeigt
- sind keine Updates vorhanden, wird die Zeile ausgeblendet (analog zu Geräte-Updates)

 <details><summary>Patch für die restlichen Anpassungen</summary>
<p>

 ```JS
--- ./www/api/methods.conf.orig
+++ ./www/api/methods.conf
@@ -1009,6 +1009,13 @@
   ARGUMENTS {_session_id_}
 }
 
+CCU.getAddonVersions {
+  LEVEL ADMIN
+  SCRIPT_FILE ccu/getaddonversions.tcl
+  INFO {Liefert die Firmware-Version der Zusatzsoftware}
+  ARGUMENTS {_session_id_}
+}
+
 CCU.getVersion {
   LEVEL ADMIN
   SCRIPT_FILE ccu/getversion.tcl
--- ./www/rega/pages/tabs/startpage.htm.orig
+++ ./www/rega/pages/tabs/startpage.htm
@@ -213,6 +213,12 @@
               <td>${deviceUpdate}</td>
               <td class="firmwareAvailable">${lblNewDeviceFirmwareAvailable}&nbsp;<span id="devFwAvailableCounter"></span></td>
             </tr>
+            
+            <!-- Addons -->
+            <tr id="addonUpdatesAvailable" class="hidden">
+              <td>${addonUpdate}</td>
+              <td class="firmwareAvailable">${lblNewAddonUpdatesAvailable}&nbsp;<span id="addonUpdatesAvailableCounter"></span></td>                        
+            </tr>
 
             <%
               object oUser = dom.GetObject( system.GetSessionVar('sessionUserID') );
@@ -283,6 +289,7 @@
       jQuery("#favSelector").show();
       jQuery("#favView").show();
       StartPage.showUpdate();
+      StartPage.showAddonUpdate();
       StartPage.showCurrentFirmware();
       StartPage.showAllDeviceFirmware();
       jQuery("#forceUpdate").remove();
--- ./www/webui/js/lang/de/translate.lang.extension.js.orig
+++ ./www/webui/js/lang/de/translate.lang.extension.js
@@ -7,6 +7,8 @@
     "ruleConditionSelectValue" : "Wert",
     "ruleConditionSelectText" : "Text",
     "btnChoice" : "Auswahl",
+    "addonUpdate" : "Zusatzsoftware-Update:",
+    "lblNewAddonUpdatesAvailable" : "aktualisierte Zusatzsoftware verf%FCgbar",    
     "btnAutoDetect" : "Automatisch ermitteln",
     "btnSelectRoomOrFunctionNew" : "Neu...",
     "btnSelectRoomOrFunctionClose" : "Schlie%DFen",
--- ./www/webui/js/lang/en/translate.lang.extension.js.orig
+++ ./www/webui/js/lang/en/translate.lang.extension.js
@@ -7,6 +7,8 @@
     "ruleConditionSelectValue": "Value",
     "ruleConditionSelectText": "Text",
     "btnChoice": "Selection",
+     "addonUpdate" : "Addon-Update:",
+    "lblNewAddonUpdatesAvailable" : "new addon software available",    
     "btnAutoDetect": "Auto discover",
     "btnSelectRoomOrFunctionNew": "New...",
     "btnSelectRoomOrFunctionClose": "Close",
--- ./www/webui/webui.js.orig
+++ ./www/webui/webui.js
@@ -20258,6 +20258,44 @@
     msgBoxHeight
     );
   },
+  
+  showAddonUpdate: function() {
+    addonUpdateCounter = 0;
+    var addonversions = homematic('CCU.getAddonVersions');
+    if (addonversions && addonversions !== "false") {
+      var localaddonversions = addonversions.local;
+      var onlineaddonversions = addonversions.online;
+      for(var l_obj in localaddonversions) {
+        if (typeof localaddonversions[l_obj] === "object") {
+        
+           for(var o_obj in onlineaddonversions) {
+             if (typeof onlineaddonversions[o_obj] === "object") {
+             
+               if (onlineaddonversions[o_obj].name == localaddonversions[l_obj].name) {
+                  //console.log(onlineaddonversions[o_obj].name +" local: "+localaddonversions[l_obj].localversion+", online: "+onlineaddonversions[o_obj].webversion);
+                  if (localaddonversions[l_obj].localversion != onlineaddonversions[o_obj].webversion) {
+                    addonUpdateCounter++;
+                  }
+               }
+             
+             }
+           }
+        }
+      } 
+    }
+    
+    if (addonUpdateCounter > 0) {
+      var self = this,
+      rowShowAddonUpdates = jQuery("#addonUpdatesAvailable"),
+      btnShowAddonUpdates = jQuery("#addonUpdatesAvailable .firmwareAvailable");
+      btnShowAddonUpdates.click(function () {
+        showSoftwareCP();
+      });
+      jQuery("#addonUpdatesAvailableCounter").text("(" + addonUpdateCounter + ")");
+      rowShowAddonUpdates.show();
+    }
+  },
+  
 
   showUpdate: function() {
     var fn = function() {
```

</p>
</details>

Ich habe leider nicht viel Zeit, um "viel Liebe" in den Code zu stecken (zumal mir auch TCL echt schwer fällt), würde dennoch aber meinen IST-Stand gern zur Verfügung stellen, wenn Interesse besteht.

VG,
Jérôme

**Comment by jens-maus** [comment]
Kannst du gerne als PR einreichen, ja. Dann können wir schauen was wir da daraus dann machen. Danke!

**Comment by jens-maus** [comment]
Ok, nach ein paar Modifikationen um das ganze IMHO noch etwas "runder" zu machen habe ich es nun entsprechend integriert. Neben ein paar administrativen Änderungen (wo die tcl hingehört) habe ich die shell syntax bzgl. des .sh noch etwas korrigiert und dann auch noch den cronjob auf 1x am tag beschränkt, denn ich denke das sollte doch vollkommen ausreichend sein wenn man sich mal anschaut wie regelmäßig neue updates von addons herauskommen. Hoffe es passt dir trotzdem so @jp112sdl Danke auf jeden fall für diesen neuen WebUI patch der sicherlich wieder auf einigen Zuspruch stoßen wird mit der nächsten kommenden Version.

**Comment by jp112sdl** [comment]
> Hoffe es passt dir trotzdem so

Klar! 
Ich hatte ja eingangs schon erwähnt, nur ein "working sample" zu haben, mit dem Potential für Verbesserungen, wofür mir aber die Zeit und Wissen fehlen ... 
Hab mir die Änderungen mal angeschaut, gerade bezüglich des Shell Skripts... muss ich mir mal in Ruhe anschauen, was deine Änderungen ausmachen / besser machen.

Wegen der Übersetzung von `Zusatzsoftware-Update[s]:`:
Ich hatte den Singular gewählt, weil eQ-3 bei den Geräte-Updates auch nur in Einzahl schreibt:
https://github.com/jens-maus/RaspberryMatic/blob/cc45bafaa4da5941019faf8842018a945d44fa61/buildroot-external/patches/occu/0131-WebUI-ShowAddonUpdatesOnStartpage/occu/WebUI/www/webui/js/lang/de/translate.lang.extension.js#L783

Das sieht dann auf der Startseite homogener aus ;-)
<img width="642" alt="Bildschirmfoto 2021-08-19 um 23 00 12" src="https://user-images.githubusercontent.com/18190139/130143248-81b4b154-dd94-495f-bb99-ec10207e1d76.png">

**Comment by detLAN** [comment]
Perfekt!

<img width="503" alt="2021-08-20_17-56-49" src="https://user-images.githubusercontent.com/64675966/130260841-0136c3a2-a8cb-4663-bd56-96ab0f1ba365.png">

Eine sehr hilfreiche Idee und so schnell umgesetzt - Danke.

**Comment by mbhomie007** [comment]
> Wegen der Übersetzung von `Zusatzsoftware-Update[s]:`:
> Ich hatte den Singular gewählt, weil eQ-3 bei den Geräte-Updates auch nur in Einzahl schreibt:
> https://github.com/jens-maus/RaspberryMatic/blob/cc45bafaa4da5941019faf8842018a945d44fa61/buildroot-external/patches/occu/0131-WebUI-ShowAddonUpdatesOnStartpage/occu/WebUI/www/webui/js/lang/de/translate.lang.extension.js#L783
> 
> Das sieht dann auf der Startseite homogener aus ;-)
> <img alt="Bildschirmfoto 2021-08-19 um 23 00 12" width="642" src="https://user-images.githubusercontent.com/18190139/130143248-81b4b154-dd94-495f-bb99-ec10207e1d76.png">


Nur eine Kleinigkeit:
Wurde dann wohl doch im Plural "Zusatzsoftware-Updates" integriert (siehe Screenshot oben).

@jp112sdl Vielen Dank für die super Idee! 🥇

**Comment by jp112sdl** [comment]
> Wurde dann wohl doch im Plural "Zusatzsoftware-Updates" integriert (siehe Screenshot oben).

@mbhomie007 Vielleicht wird aus "Geräte-Update" irgendwann noch "Geräte-Updates", dann passt es wieder ;-)
