### ISSUE TITLE
Authentifizierung per remote API schälgt fehl

### ISSUE THREAD

**Issue by chr1stianC** [jens-maus/RaspberryMatic#1388]
**Describe the bug**
per ioBroker soll eine Verbindung zur remote API aufgebaut werden. Die Authentifizierung schlägt fehl, wenn das Passwort ein ß, Ä, ä, Ö, ö, Ü, oder ü enthält.

**Steps to reproduce the behavior**
1. Einen neuen Benutzer mit einem Passwort anlegen, das min. ein o.g. Zeichen enthält (z.B. PqKfz4loJ1Öb)
2. Der hm-rega Adapter von ioBroker liefert die Fehlermeldung
`<-- invalid response: "<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n <head>\n <title>401 Unauthorized</title>\n </head>\n <body>\n <h1>401 Unauthorized</h1>\n </body>\n</html>\n"`
3. Ändern des Passworts in z.B. PqKfz4loJ1Ob
3. Die Verbindung zur Remote API ist möglich

**Expected behavior**
Alle erlaubten Sonderzeichen im Passwort sollten eine Verbindung per remote API zulassen (vielleicht ein Problem des Encodings?).

**System information:**
 - RaspberryMatic Version: 3.59.6.20210703
 - Used Hardware: Rpi 4
- ioBroker läuft im Docker auf einer Synology mit DSM 7

**Comment by jens-maus** [comment]
Ich bin mir nicht ganz sicher ob das nicht eher ein Problem / Bug im hm-rega/hm-rpc adapter von ioBroker ist. Vllt könnte daher @foxriver76 das ja mal entsprechend testen und berichten.

**Comment by foxriver76** [comment]
Ich habe mir den Code nochmal angeschaut. Es wird erfolgreich als Base64 verschlüsselt und via `Authorization` Header mitgesendet, lokal kann ich Passwörter mit Umlauten 1 zu 1 wieder korrekt entschlüsseln.

https://github.com/ioBroker/ioBroker.hm-rega/blob/60232ad492fc1c8df8b2987857302c709f4e7193/lib/rega.js#L276-L277

Wüsste hier auf hm-rega Seite keine Änderung die eine Verbesserung bringt.
