### ISSUE TITLE
WebUI: Add Script execute function to Script Editor

### ISSUE THREAD

**Issue by HMside** [jens-maus/RaspberryMatic#139]
Mit diesem Patch wird das Ausführen von Scripten auch im Script Editor möglich.

/www/rega/pages/msg/editScript.htm

[editScript.htm.patch.zip](https://github.com/jens-maus/RaspberryMatic/files/1228785/editScript.htm.patch.zip)

![runscript](https://user-images.githubusercontent.com/13312068/29372336-1e166e78-82ab-11e7-9e9b-fc0f475ccda2.png)

**Comment by jens-maus** [comment]
Danke für diesen genialen Patch. Was ich mir jedoch noch wünschen würde wäre beim "Script testen" Fenster das beim Ausführen eines Skriptes auch die Fehlerausgaben ausgegeben werden. So wie es aussieht wird bei der "Script testen" Funktion vorher kein `CheckSyntax()` aufgerufen wie das im editScript.htm für die "Skript bearbeiten" Funktion gemacht wird. Mir schwebt vor, vor jeder Ausführung von "Script testen" vor der eigentlichen Ausführung das "CheckSyntax()" aufzurufen und falls das einen Fehler bringt die Ausgabe darzustellen und nur für den Fall das CheckSyntax() keinen Fehler zurückgibt das `ReGa.runScript` aufzurufen.

**Comment by robdg80** [comment]
Super wäre es, wenn man die Größe des Script Fensters verändern könnte.

**Comment by robdg80** [comment]
Hallo,

wäre es umgedreht im Script-Testen Fenster Möglich einen "Fehlerprüfung" Button zu bekommen?

Danke & Gruß
Robert

**Comment by jens-maus** [comment]
Würde es nicht reichen einfach wie ich beschrieben habe immer vor jeder Ausführung eines Skriptes direkt vorher die Fehlerprüfung laufen zu lassen und falls die einen Fehler liefert erst gar nicht den Skript auszuführen und stattdessen die Fehlermeldung des Fehlertests darzustellen? Ich denke das würde mehr sinn machen. Warum sollte man einen separaten Button Fehlerprüfung haben? Ggf. könnte man das auch beim Skript bearbeiten  so machen und den Fehlerprüfung-Button dort auch einsparen...

**Comment by robdg80** [comment]
Ja, das würde für das Script-Testen Fenster reichen.

Ich rede von dem Fenster hier:
![image](https://user-images.githubusercontent.com/12692680/29567235-d72b329a-874c-11e7-8b49-cb4884722ec7.png)

Für das Script-Bearbeiten Fenster (was HMside  oben geändert hat), will ich aber unter Umständen nicht jedesmal ein Script Ausführen. Wenn ich ein Script hier ändere, will ich teilweise **nur** die Fehlerprüfung einzeln.

**Comment by jens-maus** [comment]
Das kann ich verstehen. Ich gehe jetzt mal davon aus das das prinzipiell möglich sein sollte. Wäre aber schön dafür nen extra neues Ticket zu haben da dies ja nichts mit diesem Ticket hier zu tun hat (das betrifft ja das "Skript bearbeiten" Fenster). Bitte also ein neues Ticket anlegen und ich/wir werden schauen was sich machen lässt.

**Comment by robdg80** [comment]
ist erledigt:
https://github.com/jens-maus/RaspberryMatic/issues/145
