### ISSUE TITLE
RM Gateway disconnect without indication

### ISSUE THREAD

**Issue by friedpa** [jens-maus/RaspberryMatic#1394]
Describe the bug
Ich habe zwei Gateways am laufen, ein Original eQ3 und einen Raspberry Pi3. Das RPi Gateway hängt sich immer wieder auf, tw ohne Anzeige in den Alarmmeldungen. Ich habe mir nun eine WhatsApp Benachrichtung eingerichtet die auf den DC von -1 triggert (siehe Screenshot). Das Verhalten ist meistens so, dass das Gateway nach einigen Tagen/Wochen die Connection verliert, dann immer öfters pro Tag bis es komplett wegfällt. Nach einem Reboot ist dann wieder für einige Zeit "Ruhe".

Expected behavior
a) Anzeige des RM Gateways in den Alarmmeldungen und b) weniger RM Gateway Connection losts.

Screenshots

![grafik](https://user-images.githubusercontent.com/42890695/130951081-88928442-fb48-4c74-8bc1-23aca2c820b4.png)
![grafik](https://user-images.githubusercontent.com/42890695/130951139-62a01e36-1718-41c4-8dab-d1f2108d7aff.png)

 
System information Zentrale:
•	RaspberryMatic Version: 3.59.6.20210807
•	Used Hardware: RPi 4
•	Used HomeMatic RF-Module: RPI-RF-MOD

Additional context
Bitte um Info welche Log Files ich nachreichen soll

**Comment by jens-maus** [comment]
Das hier genannte Problem scheint in Zusammenhang mit bzw. gleich #978 zu sein. Leider ist der "rfd" eine closed-source Komponente von OCCU bzw. der CCU Firmware und insofern kann hier leider zumindest bzgl. vermeidung dieser Verbindungsunterbrechungen nicht wirklich etwas von Seiten des RaspberryMatic Projektes verbessert werden.
