### ISSUE TITLE
Home Assistant Addon - USB Hub - HmIP-RFUSB 

### ISSUE THREAD

**Issue by egnerfl** [jens-maus/RaspberryMatic#1396]
The Addon works as expected if the Stick is directly connected to the raspberry pi but when using a generic USB 2.0 hub it's not recognized by RaspberryMatic.

**Steps to reproduce the behavior**
1. Install the RaspberryMatic Home Assistant Addon
2. Connect the HmIP-RFUSB via a USB Hub to the Host Device
3. HmIP-RFUSB won't be detected

**Expected behavior**
HmIP-RFUSB should be detected

**Screenshots**
<img width="604" alt="Screen Shot 2021-08-30 at 11 11 03" src="https://user-images.githubusercontent.com/4058299/131316564-9b5c7229-37e5-49c2-a35c-c5b97c51e7c3.png">
<img width="1067" alt="Screen Shot 2021-08-30 at 11 10 39" src="https://user-images.githubusercontent.com/4058299/131316575-f8328ea9-b696-4429-b18b-adcc10b7f3ad.png">

**System information:**
 - RaspberryMatic Version: 3.59.6.20210807 (Hassio Addon)
 - Used Hardware: Raspberry Pi 4 4GB - 512GB SSD (Home Assistant 2021.8.8 / Supervisor-2021.06.8)
 - Used HomeMatic RF-Module: HmIP-RFUSB

Feel free to reply in German :)

**Comment by jens-maus** [comment]
Please provide an output of `lsusb` within the RaspberryMatic Add-on and having the HmIP-RFUSB connected once directly to the RaspberryPi and once by having it connected to your USB hub.

**Comment by Packet-Pug** [comment]
Ich habe das selbe Problem nach dem Update war alles gut.
Musste den Rapi einmal Neustarten und der Stick blinkt die ganze Zeit.
Ein paar mal ein und Ausstecken und den CuxD Neustarten und es funktioniert. Der Stick wird erkannt, aber ich kann keine Homematic Geräte anlernen.

Nach dem Neustart fängt das ganze Spielchen wieder von vorne an.

RaspberryMatic Version: 3.59.6.20210807
Used Hardware: Raspberry Pi 4 4GB
Used HomeMatic RF-Module: HmIP-RFUSB

**Comment by jens-maus** [comment]
@egnerfl Why did you close this ticket? Please explain
