### ISSUE TITLE
Home Assistant Addon - RPI-RF-MOD not found

### ISSUE THREAD

**Issue by Julez318** [jens-maus/RaspberryMatic#1397]
**Describe the bug**
In the RaspberryMatic Addon for Home Assistant, my RPI-RF-MOD on RPI4 4GB can't be found.

**Steps to reproduce the behavior**
1. Install Addon RaspberryMatic in HassIO on a RPI 4 with RPI-RF-MOD
2. Check Protocoll
3. ...
4. ...

**Expected behavior**
RPI-RF-MOD should be found and installed

**Screenshots**
![image](https://user-images.githubusercontent.com/77839749/131827312-748d46e9-a264-40ae-a854-7d9a6ecb51e9.png)

**System information:**
 - RaspberryMatic Version: 3.59.6.20210807
 - Used Hardware: Raspberry Pi 4 4GB
 - Used HomeMatic RF-Module: RPI-RF-MOD

**Additional context**
...

**Comment by jens-maus** [comment]
Are you sure you have *disabled* the protection mode in the add-on configuration?

**Comment by Julez318** [comment]
Yes, it's disabled:
![image](https://user-images.githubusercontent.com/77839749/131831292-f08afa68-5a92-4e53-bfdc-335015616037.png)

**Comment by jens-maus** [comment]
Ok, and you have followed the instructions in the documentation to modify the `/mnt/boot/config.txt` file so that you enable the dtoverlay for the rpi-rf-mod, right? See (https://github.com/jens-maus/RaspberryMatic/wiki/Installation-HomeAssistant#using-homeassistant-os step 2.

**Comment by Julez318** [comment]
Yes, I made a new installation of the HassIO and the config.txt were already modified with the needed lines

**Comment by jens-maus** [comment]
Which HMos version have you installed? 6.2? And the 32bit or 64bit version?

**Comment by Julez318** [comment]
Now the 32bit Version of 6.2 is installed. Before that I tried the 64bit Version but there I had the same problem

**Comment by Julez318** [comment]
The lines in the /mnt/boot/config.txt file were not uncommented. Now it works, sry

**Comment by drMaxxi** [comment]
I tried to perform the installation too, but the /mnt folder does not have a subfolder /boot. The /mnt folder does not contain anything. Is there an alternative folder where I can find the config.txt in order to perform the necessary changes?

**Comment by KarlKaracho** [comment]
Hey,
i have the same problem like drMaxxi.
I run the Home Assistant OS 7.2 version, but the mnt folder is empty. no boot folder and no config.txt file.
Can somebody help me to fix that.

**Comment by eNBeWe** [comment]
> Hey, i have the same problem like drMaxxi. I run the Home Assistant OS 7.2 version, but the mnt folder is empty. no boot folder and no config.txt file. Can somebody help me to fix that.

I guess you are trying to edit the config.txt file with the sd card connected to your pc.
The boot partition is a separate partition on the card and has to be mounted separately. For some reason it isn't mounted automatically on my system either.
