### ISSUE TITLE
HA Addon Anzeigefehler und Backup/Software lässt sich nicht hochladen/installieren

### ISSUE THREAD

**Issue by Julez318** [jens-maus/RaspberryMatic#1398]
**Describe the bug**
Bei der Temperatureinstellung der HM IP Thermostate sind Anzeigefehler.
Backups und Zusatzsoftware lässt sich nicht hochladen.

**Steps to reproduce the behavior**
z.B. Backup versuchen einzuspielen
 

**Screenshots**
![image](https://user-images.githubusercontent.com/77839749/131870603-a0e4b4c5-1284-4b9d-bea0-ffbfab202306.png)
![image](https://user-images.githubusercontent.com/77839749/131870718-f8254603-0906-4bec-bdec-2ce238b02a13.png)
![image](https://user-images.githubusercontent.com/77839749/131870805-94c5eec4-591e-4fc3-8d9a-3f9359cb3e74.png)
![image](https://user-images.githubusercontent.com/77839749/131870873-456481f0-4fbe-486e-8625-dc8ad5cb101b.png)

**System information:**
 - RaspberryMatic Version: 3.59.6.20210807
 - Used Hardware: RaspberryPi 4 4gb
 - Used HomeMatic RF-Module: RPI-RF-MOD

**Additional context**

Danke und viele Grüße

**Comment by jens-maus** [comment]
Bitte nicht mehrere Sachen miteinander vermengen. One Bug, One Issue!

Und zumindest die zweite Sache (Upload von Dateien) wird mit der nächsten kommenden version bereits behoben sein. Eine suche hier im Ticket System hätte dich darauf gebracht (siehe #1368)

Und die andere Sache (Falsche Grad anzeige) wurde bereits prinzipiell einmal aufgezeigt. Eine Lösung gab es aber bisher dafür noch nicht (siehe https://github.com/jens-maus/RaspberryMatic/issues/1087#issuecomment-840101453).

**Comment by Julez318** [comment]
Okay tut mir leid, dass ich die beiden Themen vermengt habe.
Die Suche im Ticketsystem habe ich genutzt, und habe auch das von dir angehängte Issue gefunden, allerdings wir hier ja eine ganze andere Fehlermeldung gezeigt als bei mir, daher ist es für mich ein andere Fehler gewesen. Handelt es sich hier also trotz unterschiedlicher Fehlermeldung um das selbe Problem?

**Comment by jens-maus** [comment]
Welches der beiden Dinge meinst du denn nun genau? Die "kaputte" Grad anzeige oder der "kaputte" Upload der Dateien?

**Comment by Julez318** [comment]
Oh sry, den Upload des Backups oder Zusatzsoftware meine ich.
Der Anzeigefehler ist ja bei der Gradanzeige identisch, nur dass bei mir das der einzige Fehler ist und nicht bei jedem Umlaut noch.
