### ISSUE TITLE
Nach Update auf 3.59.6 startet rfd laufend neu

### ISSUE THREAD

**Issue by dplischke** [jens-maus/RaspberryMatic#1399]
Hallo zusammen,

seit dem Update meines ELV Charly startet der rfd laufend neu und eine normale Nutzung meines SmartHomes ist nicht mehr möglich.

Was ist passiert: Ich habe zwei unabhängige Charly Installationen und habe die kleinere (mit vorherigem Backup) von einer 3.57.x auf die aktuelle 3.59.6 geupdatet. Alles lief (wie bisher immer) problemlos. Danach habe ich meine große Installation (wie soll es anders sein, diesmal ohne vorheriges Backup) geupdatet. Danach lief mein SmartHome nicht mehr :-(

Was habe ich schon versucht: Ich habe festgestellt, dass der Charly beim Booten bei "Starting LGWFirmwareUpdate" hängen bleibt. Nach dem Löschen der S58LGWFirmwareUpdate fährt Charly (allerdings mit "Starting rfd: ...................ERROR") hoch. Es funktionieren natürlich keine Funkkomponenten, aber ich konnte ein Backup erstellen. Charly startet den rfd immerwieder neu (wiederholt sich alle ca. 90 Sekunden) und für einen kurzen Moment tut sich dann auch was auf der Funkschnittstelle. Ich habe ein Downgrade auf die 3.57.x versucht, ohne Erfolg. Ich habe eine 3.59.6 neu installiert und die Konfi nicht eingespielt, funktioiniert einwandfrei, also kein Hardwaredefekt.

Wie bekomme ich die Zentrale wieder normal ans Laufen? Ich bin kein Linux-Profi, kann aber mit einem Terminal, nach genauer Anweisung, umgehen ;-) 

In der messages habe ich folgende, sich ständig wiederholende Log-Einträge:
Sep  4 20:04:13 homematic-ccu2 user.err monit[975]: 'rfd' service restarted 1 times within 1 cycles(s) - exec
Sep  4 20:04:13 homematic-ccu2 user.info monit[975]: 'rfd' exec: '/bin/triggerAlarm.tcl rfd restarted WatchDog-Alarm'
Sep  4 20:04:13 homematic-ccu2 user.info monit[975]: 'rfd' process is running after previous exec error (slow starting or manually recovered?)
Sep  4 20:04:13 homematic-ccu2 user.info monit[975]: 'rfd' process is running after previous restart timeout (manually recovered?)
Sep  4 20:04:13 homematic-ccu2 user.err monit[975]: 'rfd' failed protocol test [DEFAULT] at [localhost]:32001 [TCP/IP] -- Connection refused
Sep  4 20:04:13 homematic-ccu2 user.info monit[975]: 'rfd' trying to restart
Sep  4 20:04:13 homematic-ccu2 user.info monit[975]: 'rfd' restart: '/etc/init.d/S61rfd restart'

Kann ich evtl. nur die Geräte und Programme in eine Neuinstallation importieren, so dass ich den Fehler nicht mitnehme?

Ich hoffe auf eure Unterstützung!

Viele Grüße Dominik.

**Comment by jens-maus** [comment]
Sorry, but this is no support or discussion fora here. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. This was also already mentioned in the ticket template!
___
Tut mir leid, aber das hier ist kein Supportforum, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen.  Dies stand übrigens auch so im Ticket Template!
