### ISSUE TITLE
Snapshot Version - RPI3 bootet nicht mehr

### ISSUE THREAD

**Issue by mbhomie007** [jens-maus/RaspberryMatic#1405]
Nach einem WEB-UI-Update von 3.59.6.20210901-f1326a-rpi3 auf 3.59.6.20210907-df7cabe-rpi3 oder auch 3.59.6.20210908-df7cab-rpi3 startet der Raspberry 3b+ nicht mehr.

Auch ein neues Flashen mit balenaEtcher der Version 3.59.6.20210907-df7cabe-rpi3 und auch 3.59.6.20210908-df7cab-rpi3 ging nicht, nach einstecken der SD-Karte blieb die rote LED dauerhaft an, kein Start wurde ausgeführt.

**Comment by jens-maus** [comment]
D.h. die letzte für dich funktionierende Version ist welche?

**Comment by mbhomie007** [comment]
Die 3.59.6.20210901-f1326a-rpi3 war die zuletzt funktionierende.
Auf nachfolgende Versionen ging das Update nicht.
Rote Heartbeat-LED dauerthaft rot.

**Comment by jens-maus** [comment]
Bitte mal die genaue Revision ID deines Pi3 ausgeben. Dafür bitte folgenden Befehl ausführen und die Ausgaben präsentieren:

```
cat /proc/cpuinfo | grep Revision
```

**Comment by mbhomie007** [comment]
Reicht dir das? 

Raspberry Pi 3 Model B Plus Rev 1.3 mit RPI-RF-MOD Funkmodul

Komme gerade per SSH nicht ran.

**Comment by mbhomie007** [comment]
Reicht dir das? 

Raspberry Pi 3 Model B Plus Rev 1.3 mit RPI-RF-MOD Funkmodul

Komme gerade per SSH nicht ran.

**Comment by jens-maus** [comment]
Nein, besser wäre die Revision Ausgabe. Wenn du nur per WebUI rankommst kannst du auch natürlich einfach das hier eingeben bei "Skript testen":

```
string stdout;
system.Exec("cat /proc/cpuinfo | grep Revision", &stdout);
WriteLine(stdout);
```

Und dann sollte es auch das besagte kommando und damit die Revision ausgeben.

**Comment by mbhomie007** [comment]
Revision	: a020d3

**Comment by jens-maus** [comment]
Ok, ich denke ich hab das Problem gefunden und gelöst. Bitte mit dem nächsten nightly snapshot probieren und falls es noch probleme gibt bitte zeitnah hier wieder melden.

**Comment by mbhomie007** [comment]
Vielen Dank für die schnelle Hilfe.
Werde ich nochmal testen.

**Comment by jens-maus** [comment]
@mbhomie007 Bist du schon zum testen der aktuellste nightly snapshot gekommen? Bitte ne kurze Rückmeldung geben ob ist mit der Version von heute klappt oder nicht damit das kommende Release nicht gefährdet wird.

**Comment by Baxxy13** [comment]
a020d3 ist nen Pi3B+, oder?

Ich hatte da mit den Nightlys der letzten Tage keinerlei Probleme, zumindest fiel mir nichts auf.
Aktuell läuft problemlos der heutige Nightly... RaspberryMatic-3.59.6.20210909-441817-rpi3.zip

**Comment by mbhomie007** [comment]
Habe es nun getestet:
Erfolgreich von 3.59.6.20210901-f1326a-rpi3 auf 3.59.6.20210909-441817-rpi3 geupdatet!

Läuft wieder! 💯

**Comment by mbhomie007** [comment]
> a020d3 ist nen Pi3B+, oder?

Genau!
