### ISSUE TITLE
Integration in Home Assistant 

### ISSUE THREAD

**Issue by maldag** [jens-maus/RaspberryMatic#1406]
I'm trying to install the RaspberryMagic Repository to my home assistant setup using Hass.io 2021.09.05.

Upon installing the addon from the custom add-on store I'm getting the following error:

```
Add-on konnte nicht installiert werden
Can't install ghcr.io/jens-maus/raspberrymatic:3.59.6.20210911: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=3.59.6.20210911&fromImage=ghcr.io%2Fjens-maus%2Fraspberrymatic: Internal Server Error ("manifest unknown")
```

RaspberryMatic CCU3.59.6.20210911

**Comment by jens-maus** [comment]
Sorry @maldag. The new release (3.59.6.20210911) is actually currently in the process of being created and you had the unlucky situation in trying to install it while this process is still not finished. So please wait a few hours or until the new release is officially released, then it should work!
