### ISSUE TITLE
After update the measurement doesn't work.

### ISSUE THREAD

**Issue by soosp** [jens-maus/RaspberryMatic#1410]
**Describe the bug**
After update the measurement doesn't work.

**Steps to reproduce the behavior**
1. Update to latest version.
2. Log into the WebUI
3. Navigate to Settings, Diagrams
4. ...

**Expected behavior**
Able to configure diagram settings

**Screenshots**
![HomeMatic-WebUI](https://user-images.githubusercontent.com/24782682/132982778-8d057040-da34-4f40-be87-a1ec6d1590dd.jpg)

**System information:**
 - RaspberryMatic Version: 3.59.6.20210911
 - Used Hardware: CCU3
 - Used HomeMatic RF-Module: CCU3

**Additional context**
The USB storage is present:
```
# mount | grep sd
/dev/sda1 on /media/usb1 type vfat (rw,nodev,noexec,noatime,nodiratime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro)
```

From the logs:
```
Sep 12 10:53:54 de.eq3.ccu.server.BaseHMServer INFO  [Thread-1] Create MeasurementService
Sep 12 10:53:54 de.eq3.ccu.server.BaseHMServer INFO  [Thread-1] Init MeasurementService
Sep 12 10:53:54 de.eq3.lib.datalogging.rrd.RrdDatalogging ERROR [Thread-1] Could not initialize rrd database
java.lang.IllegalArgumentException
        at java.nio.Buffer.position(Buffer.java:244)
        at org.rrd4j.core.RrdNioBackend.read(RrdNioBackend.java:116)
        at org.rrd4j.core.RrdBackend.readInt(RrdBackend.java:202)
        at org.rrd4j.core.RrdPrimitive.readInt(RrdPrimitive.java:38)
        at org.rrd4j.core.RrdInt.get(RrdInt.java:35)
        at org.rrd4j.core.Archive.<init>(Archive.java:45)
        at org.rrd4j.core.RrdDb.<init>(RrdDb.java:218)
        at org.rrd4j.core.RrdDb.<init>(RrdDb.java:174)
        at org.rrd4j.core.RrdDb.<init>(RrdDb.java:235)
        at de.eq3.lib.datalogging.rrd.RrdDatalogging.initialize(RrdDatalogging.java:463)
        at de.eq3.lib.measurement.MeasurementService.isDataloggingInitialized(MeasurementService.java:192)
        at de.eq3.lib.measurement.MeasurementService.init(MeasurementService.java:164)
        at de.eq3.ccu.server.BaseHMServer.initializeMeasurement(BaseHMServer.java:206)
        at de.eq3.ccu.server.ip.HMIPServer.initialize(HMIPServer.java:216)
        at de.eq3.ccu.server.ip.HMIPServer.<init>(HMIPServer.java:61)
        at de.eq3.ccu.server.ip.HMIPServer$2.run(HMIPServer.java:167)
        at java.lang.Thread.run(Thread.java:748)


```

**Comment by jp112sdl** [comment]
Can you show the output of `ls -l /media/usb1` and `ls -l /media/usb1/measurement/` ?

**Comment by jens-maus** [comment]
Also please show an output of `df -h` and `ls -la /media` here and also state if you have tried to freshly reformat the USB drive, then connect it and rebooted afterwards.

**Comment by soosp** [comment]
```
# ls -l /media/usb1
total 1304
-rwxr-xr-x    1 root     root       1314557 Oct 31  2020 BackupUSBStorage.tar.gz
drwxr-xr-x    2 root     root          4096 Sep 12 12:26 System Volume Information
-rwxr-xr-x    1 root     root           245 Jun 30  2019 auth.conf
drwxr-xr-x    2 root     root          8192 Sep 12 00:07 backup
drwxr-xr-x    2 root     root          4096 May 15  2020 measurement
```

```
# ls -l /media/usb1/measurement/
total 3388
-rwxr-xr-x    1 root     root          4096 Jun 17 01:30 1.rrd
-rwxr-xr-x    1 root     root       1410208 Aug 11  2019 2.rrd
-rwxr-xr-x    1 root     root        627168 Aug 11  2019 3.rrd
-rwxr-xr-x    1 root     root       1410208 Aug 11  2019 4.rrd
-rwxr-xr-x    1 root     root          4096 Jun 28 16:00 5.rrd
-rwxr-xr-x    1 root     root          4096 Jun 14 22:27 6.rrd
```

```
# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root               973.4M    545.7M    360.5M  60% /
devtmpfs                444.2M         0    444.2M   0% /dev
tmpfs                   477.8M         0    477.8M   0% /dev/shm
tmpfs                   477.8M      3.4M    474.4M   1% /tmp
tmpfs                   477.8M    124.0K    477.7M   0% /run
tmpfs                   477.8M      7.2M    470.7M   2% /var
tmpfs                   477.8M         0    477.8M   0% /media
/dev/mmcblk0p3           13.5G    344.0M     12.5G   3% /usr/local
/dev/mmcblk0p1          255.7M     68.8M    186.9M  27% /boot
/dev/sda1                 3.7G    325.3M      3.4G   8% /media/usb1
```

```
# ls -la /media
total 8
drwxrwxrwt   10 root     root           220 Sep 12 11:27 .
drwxr-xr-x   24 root     root          4096 Sep 11 12:19 ..
lrwxrwxrwx    1 root     root            11 Sep 12 11:27 usb0 -> /media/usb1
drwxr-xr-x    5 root     root          4096 Jan  1  1970 usb1
drwxrwxr-x    2 root     root            40 Sep 12 10:52 usb2
drwxrwxr-x    2 root     root            40 Sep 12 10:52 usb3
drwxrwxr-x    2 root     root            40 Sep 12 10:52 usb4
drwxrwxr-x    2 root     root            40 Sep 12 10:52 usb5
drwxrwxr-x    2 root     root            40 Sep 12 10:52 usb6
drwxrwxr-x    2 root     root            40 Sep 12 10:52 usb7
drwxrwxr-x    2 root     root            40 Sep 12 10:52 usb8
```

The media hasn't beed reformatted because I don't want to loose previous measurement data.
The system has been rebooted more times.

**Comment by jens-maus** [comment]
And what about `/etc/config/measurement/` please show the content of this one. IMHO this seems to point at the a faulty/broken rrd files in `/media/usb1/measurement`. So simply move the whole measurement directory away and let RaspberryMatic regenerate it and see if this solves the issue. If so, IMHO this points at broken rrd data to some extend.

Please note that this does not seem to point at any bug but rather an issue in your sole installation. So please next time open a discussion thread on the homematic forum or the github discussion part here and only open an issue here if you can reproduce the issue in a clean RaspberryMatic issue.

**Comment by soosp** [comment]
> 
> 
> And what about `/etc/config/measurement/` please show the content of this one. IMHO this seems to point at the a faulty/broken rrd files in `/media/usb1/measurement`. So simply move the whole measurement directory away and let RaspberryMatic regenerate it and see if this solves the issue. If so, IMHO this points at broken rrd data to some extend.

This is the solution, thanks!

> Please note that this does not seem to point at any bug but rather an issue in your sole installation. So please next time open a discussion thread on the homematic forum or the github discussion part here and only open an issue here if you can reproduce the issue in a clean RaspberryMatic issue.

Sure.
But the error message is somewhat misunderstandable.
