### ISSUE TITLE
StromPI 2 daemon gibt Fehler aus / startet nicht

### ISSUE THREAD

**Issue by RalphPungaKronbergs** [jens-maus/RaspberryMatic#1413]
**Describe the bug**
RM kann den StromPI2 daemon nicht starten, da dieser beim Start einen Fehler meldet.

**Steps to reproduce the behavior**
Trigger-File erstellen mittels 
```
touch /etc/config/strompi2
```

Ein manueller des StromPI2 daemons Start scheint erfolgreich:
```
/etc/init.d/S51strompi2d start
Starting StromPi2 UPS daemon: OK
```

Doch lässt sich der Daemon danach nicht ermitteln:
```
ps aux | grep strom
 2483 root      0:00 grep strom
```

Nutzt man das init.d Script zum Stoppen des Daemons, erhält man eine Fehlermeldung:
```
/etc/init.d/S51strompi2d stop
Stopping StromPi2 UPS daemon: start-stop-daemon: warning: killing process 2464: No such process
FAIL
```

Auch beim Versuch, das Script manuell zu starten, erhält man eine Fehlermeldung:
```
/opt/strompi2d# ./strompi2d.sh
sh: write error: Device or resource busy
```

Auch, wenn man das ganze Sytem neu startet und RM durch den Triggerfile den Daemon laden sollte, ist dieser nach dem Neustart nicht in der Prozessliste zu finden. Getestet mit der produktiven RM sowie einer blanken RM.

**Expected behavior**
StromPI2 daemon bricht den Start nicht mit einer Fehlermeldung ab

**System information:**
 - RaspberryMatic Version: 3.59.6.20210911
 - Used Hardware: Raspi 3b + StromPI 2
 - Used HomeMatic RF-Module: HM-MOD-RPI-PCB

**Comment by RalphPungaKronbergs** [comment]
Danke für die Fehlersuche!
Bei mir ist es jedoch so, dass ich das HM-MOD-RPI-PCB verwende und der Fehler ebenfalls auftritt.
Einzig wird noch eine PIFace RTC am PI zusätzlich betrieben.
Sollte damit dann nicht eigentlich die ursprünglich implementierte Variante funktionieren?

Laut StromPI2 Anleitung wäre vielleicht auch eine andere Lösung machbar:
"Mittels eines Pin-Connector-Kabels, kann dann der T-PIN an einen anderen freien GPIO-Pin des Raspberry Pis angeschlossen werden.". 
Liesse sich der PIN also bei der RM StromPI2 Implementierung frei definieren, könnte man im best case ohne Anpassung des daemons die Funktionstüchtigkeit wieder herstellen. Hier wäre dann nur nützlich zu ermitteln, welcher PIN dafür am besten nutzbar wäre.

**Comment by jens-maus** [comment]
> Bei mir ist es jedoch so, dass ich das HM-MOD-RPI-PCB verwende und der Fehler ebenfalls auftritt.

Das ist quasi unabhängig davon ob du konkret ein RPI-RF-MOD einsetzt oder nicht. Im OS werden die vom RPI-RF-MOD verwendbaren GPIOs für die Nutzung adressiert und stehen für gewisse Dinge dann nicht mehr zur Verfügung. Eine Erkennung des konkreten Funkmodultyps ist in dieser frühen Phase leider nicht möglich und so kann der strompi daemon eben diese GPIOs auf gewohntem nicht nutzen.

> Sollte damit dann nicht eigentlich die ursprünglich implementierte Variante funktionieren?

Nein, denn das Problem existiert weil über die Jahre eben die GPIO Einbindung für die Funkmodule erweitert wurde und der daemon somit nun anders auf den GPIO21 zugreifen muss als bisher.

Und das muss nun eben umgesetzt werden. Wann genau kann ich nicht sagen/versprechen. Du scheinst ja auf weiter flur ein einzelner nutzer zu sein und so gibt das eben wenig priorität. Auch zumal das StromPi ohnehin IMHO keine wirklich gute Lösung ist.

> Liesse sich der PIN also bei der RM StromPI2 Implementierung frei definieren, könnte man im best case ohne Anpassung des daemons die Funktionstüchtigkeit wieder herstellen. Hier wäre dann nur nützlich zu ermitteln, welcher PIN dafür am besten nutzbar wäre.

Es steht dir frei einen entsprechenden PullRequest einzusenden.

**Comment by RalphPungaKronbergs** [comment]
Danke für die Erläuterungen!

Ich arbeite mich mal in das Thema ein, vielleicht kann ich etwas in Sachen alternative PIN Nutzung beim StromPi2 beitragen.

**Comment by RalphPungaKronbergs** [comment]
Mein erster Versuch, die Funktionalität durch Umleitung des StromPi2 PowerLoss-Signals an GPIO PIN 13 wieder herzustellen, hat ergeben, dass der Daemon mit wenigen Anpassungen wie gewünscht funktioniert.

Vorgehensweise:
- Entfernen des "T-PIN" Jumpers auf der StromPi2 Platine
- Verbinden des äusseren der beiden "T-PIN" Jumper-PINs mit GPIO PIN 13
- Anpassung des Daemon-Scripts wie folgt:

`#!/bin/sh
# shellcheck shell=dash disable=SC2169 source=/dev/null

# source all data from /var/hm_mode
[[ -r /var/hm_mode ]] && . /var/hm_mode

# Command run on power loss
: "${POWER_LOSS_CMD:='/bin/triggerAlarm.tcl "Power Loss" "StromPi2-Alarm"'}"
: "${POWER_RETURN_CMD:='/bin/triggerAlarm.tcl "Power Restored" "StromPi2-Alarm"'}"

# File descriptors
if [[ "${HOST}" != "tinkerboard" ]]; then
  : "${GPIO_POWER:=**13**}"
else
  : "${GPIO_POWER:=188}"
fi

# Debounce time in while loop
: "${DEBOUNCE_TIME:='0.3s'}"

## Initialize GPIO file descriptor
# $1: File descriptor Value: decimal
# $2: Direction       Value: in|out
initFD() {
    eval "[ -e /sys/class/gpio/gpio\$$1/direction ]" || {
        eval "echo \$$1 > /sys/class/gpio/export || exit 1"
        sleep 0.1s
    }
    eval "echo $2 > /sys/class/gpio/gpio\$$1/direction || exit 1"
}

## Set GPIO Value
# $1: File descriptor Value: decimal
# $2: Value           Value: 0|1
setFDvalue() {
    eval "echo $2 > /sys/class/gpio/gpio\$$1/value || exit 1"
}

## get GPIO Value
# $1: File descriptor       Value: decimal
# $2: Target variable name  Value: 0|1
getFDvalue() {
    eval "read $2 < /sys/class/gpio/gpio\$$1/value || exit 1"
}

# Initialize GPIO_POWER file descriptor
initFD GPIO_POWER in

POWER_STATE=0
while getFDvalue GPIO_POWER POWER_STATE_NEW; do
    if [ ! "${POWER_STATE_NEW}" -eq "${POWER_STATE}" ]; then

      # execute POWER_LOSS_CMD in case power state is lost
      if [ 1 -eq "${POWER_STATE_NEW}" ]; then
        **/bin/triggerAlarm.tcl "Power Loss" "StromPi2-Alarm"**
      else
        **/bin/triggerAlarm.tcl "Power Restored" "StromPi2-Alarm" &**
      fi
	  
      # save POWER_STATE for next iteration
      POWER_STATE=${POWER_STATE_NEW}
    fi

    # Debouncing in software
    sleep **0.3s**
done

# Remove GPIO file descriptors
echo ${GPIO_POWER} >/sys/class/gpio/unexport`

Nötig waren die Anpassungen, da das Nutzen der Variablen POWER_LOSS_CMD, POWER_RETURN_CMD und DEBOUNCE_TIME bei der Scriptausführung Fehler erzeugt haben.

Die Frage wäre nun, ob man grundsätzlich PIN 13 als alternative Variante (mit einem anderen Trigger-File?) verwendet oder aber die Wahl des PINs durch eine Konfigurationsdatei ermöglicht. Leider habe ich diesbezüglich keine Kenntnisse vom RM Code, hoffe aber, dass meine Erkenntnisse helfen können, eine Lösung zu implementieren...

**Comment by jens-maus** [comment]
So, ich denke ich hab den daemon nun so angepasst das er mit der nächsten Version bzw. nächsten nightly snapshot funktionieren sollte. Zusätzlich kann man jetzt im `/etc/config/strompi2` File z.B. `GPIO_POWER=20` angeben und dann wird GPIO20 verwendet.

**Comment by RalphPungaKronbergs** [comment]
Perfekt! Vielen Dank für den schnelle Fix!
