### ISSUE TITLE
How to get a list of broadcasted entities 

### ISSUE THREAD

**Issue by maldag** [jens-maus/RaspberryMatic#1414]
I'm using raspberrymatic with hmip swo pl weather station. Looking at the device in raspberry matic shows the rain counter, rain today and rain yesterday. But only the overall rain counter gets published to home assistant.

How can I retrieve a list of those entities to be able to add the as custom sensor templates in home assistant?

**Comment by jens-maus** [comment]
Sorry, but this is no support or discussion fora here. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. This was also already mentioned in the ticket template!
___
Tut mir leid, aber das hier ist kein Supportforum, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen.  Dies stand übrigens auch so im Ticket Template!
