### ISSUE TITLE
WebUI nicht erreichbar -> "lighttpd expired sslcert"

### ISSUE THREAD

**Issue by r4m3u5** [jens-maus/RaspberryMatic#1416]
Lighttpd startet alle 24 Stunden mit folgender Fehlermeldung neu:

![image](https://user-images.githubusercontent.com/17406423/133920028-a921423a-21f7-4b9e-bdab-4d7eb3fa1e17.png)

Meist ist die WebUI noch erreichbar (-> Screenshot), oft nicht. Restart per SSH hilft. Problem tritt auf 2 RPI2 mit identischer Hardware auf.
Applikationen wie z.B. Symcon verlieren dabei komplett die Verbindung zur RaspiMatic.
"Downgrade" auf 3.59.6.20210807 behebt das Problem.

**System information:**
 - RaspberryMatic Version: RaspberryMatic-3.59.6.20210911-rpi2
 - Used Hardware: RPI2
 - Used HomeMatic RF-Module: HM-MOD-RPI-PCB

**Comment by ymichel** [comment]
Hi,
ich habe exakt das selbe Verhalten und wollte ebenso einen Issue öffnen.
Wie ich es aus /var/log/lighttpd-error.log entnehme beendet sich der daemon weil keine file-descriptoren mehr vorhanden sind… wie auch immer das passieren kann.

Ein los /proc/{pif_of_daemon}/fd|wc -l gibt einen kleineren Wert gerade aber im Moment läuft es ja auch. :-(
Der Wert max-fds steht auf 2048. 

Wenn ich irgendwelche Logs beitragen kann, gern.

Gruß
Yann

**Comment by jens-maus** [comment]
Ja, bitte entsprechend das `/var/log/lighttpd-error.log` hier liefern und auch das `/var/log/messages` damit man das Problem auch entsprechend sehen kann.

**Comment by r4m3u5** [comment]
Sehen bei mir identisch aus die Log-Einträge.
Ich habe 'server.max-fds' zum Test auf 4096 gesetzt. Mal schauen, ob's hilft.

**Comment by jens-maus** [comment]
> Ich habe 'server.max-fds' zum Test auf 4096 gesetzt. Mal schauen, ob's hilft.

Das ist/kann keine Lösung sein, denn eine solch hohe Anzahl von offenen file descriptoren ist definitiv nicht normal und ein einfaches hochsetzen des max-fds wertes verschiebt das Problem nur auf einen späteren Zeitpunkt. Wenn dauerhaft die anzahl von file descriptoren beim lighttpd so hoch ist, deutet das auf massive parallele zugriffe auf den webserver hin, die ergründet werden sollten statt die max-fds anzahl hochzusetzen.

**Comment by ymichel** [comment]
Moin,
gibt es inzwischen irgendeinen Anhaltspunkt woran das liegen könnte? Es ist irgendwie nicht so wirklich praktikabel immer wieder per SSH den lighthttpd neu starten zu müssen… :-(
Gerne trage ich auch irgendwelche Infos bei, wenn es denn hilft oder probiere Dinge aus.
Gruß & Dank
Yann

**Comment by ymichel** [comment]
Ich habe jetzt ein Downgrade zu  3.59.6.20210807 gemacht und werde das noch mal beobachten.

**Comment by ymichel** [comment]
Gleiches Phänomen auch nach dem Downgrade, leider.

**Comment by ymichel** [comment]
@r4m3u5 hat die Erhöhung denn geholfen?
