### ISSUE TITLE
Encoding problems when editing/viewing string parameters in the device configuration

### ISSUE THREAD

**Issue by mdzio** [jens-maus/RaspberryMatic#1417]
When entering and displaying **string parameters** in the device configuration (_Web-UI Einstellungen_ → _Geräte_ → Gerät auswählen → _Einstellen_), the following problems occurred. 

Background: The add-on [CCU-Jack](https://github.com/mdzio/ccu-jack) uses string master parameters in its virtual devices. I wonder, has any real device ever used string master parameter in the device configuration? Certainly, the entry here will only have a low priority, it then serves more documentation purposes for "known issues".

**Problem 1: Single and double quotation marks**

Single and double quotation marks can be entered and are also passed correctly to the interface process:
![string-parameter-quotes](https://user-images.githubusercontent.com/24684496/134178520-6b564aee-c30c-42d7-9bea-2c298c14b32e.png)

However, they are encoded as HTML special characters when displayed again:
![string-parameter-quotes-result](https://user-images.githubusercontent.com/24684496/134178544-88a39068-130f-4ae5-bac5-44196788ef54.png)

Apparently the HTML special characters are encoded **twice** for display.

**Problem 2: Character codes greater than 127**

If a string parameter of a device is written with the value `üöäÜÖß`, the call to the `putParamset` method of the interface process is made with the following content (code is ISO 8859-1 encoded):
```
<name>COMMAND_TOPIC</name><value>Ã¼Ã¶Ã¤ÃœÃ–Ã„ÃŸ</value>
```

Expected, however (code is ISO 8859-1 encoded):
```
<name>COMMAND_TOPIC</name><value>üöäÜÖÄß</value>
```

Apparently in the sent XML document with stated ISO-8859-1 character encoding, the value of the string parameter is sent encoded in UTF-8.

Analysis (partial):

The parameter value is correctly encoded with UTF-8 in the URL during the HTTP-GET call to `/config/ic_ifacecmd.cgi` (see also webui.js, SaveDeviceParameters, SendRequest):

Example for `ü`:
```
...&LONG_PATTERN=%C3%BC&...
```

Apparently the URL decoding of the parameters for `/config/ic_ifacecmd.cgi` is not done correctly. After the percentage decoding it seems that the character set ISO-8859-1 is used instead of UTF-8, or there is no conversion to ISO-8859-1 before the interface process is called.

**System information:**
 - RaspberryMatic Version: 3.59.6.20210911
 - Used Hardware: Raspberry 2B
 - Used HomeMatic RF-Module: HM-MOD-RPI-PCB

**Comment by jens-maus** [comment]
Can you please provide the payload output when issuing such requests to `/config/ic_ifacecmd.cgi` and getting responses from it. Only by helping somewhat further we would have a potential chance of fixing this well-known ISO-8859-1 <> UTF-8 conversion issues.

**Comment by mdzio** [comment]
`/config/ic_ifacecmd.cgi` generates a small piece of HTML code without error output.

I was able to follow the code up to the file `ic_common.tcl` line 332:
```
 if { ! [catch {xmlrpc $url putParamset [list string $address] [list string $peer] [list struct $struct]} ] } then {
```
With the following log line I was able to verify the correct passing of the parameters to tclrpc.so:
```
 set f [open /tmp/putParamset.log a+]; fconfigure $f -encoding unicode; puts $f "$address $peer $struct"; close $f
```
Apparently the encoding error is in `tclrpc.so`. I could not find any source code for this library.

**Comment by jens-maus** [comment]
Sorry, but I definitly need more details to debug this. I need a concrete example and a payload track of what you are trying to do, etc. So please try to prepare an example in a vanilla RaspberryMatic installation (without CCU Jack) that also demonstrates the issue. But be prepared: It is widely known that the tcl version currently used and ReGa can only manage iso-8859-1 and are not uft8 aware, thus there might be chances I cannot find a way to fix these issues.

Also note, that there are no character encoding conversion routines in `tclrpc.so` (which unfortunately is closed source). But there are chances that the tcl<>C++ api this `tclrpc.so` uses might mix up character encoding to some extend. But then, I would also need a concrete example and payload to actually reproduce this with an example. Best would be if you could provide a command-line only example script which demonstrates the issue in a vanilla installation.
