### ISSUE TITLE
Abnahme der Funkqualität // HmIP HAP wird nicht verwendet

### ISSUE THREAD

**Issue by MaZoresu** [jens-maus/RaspberryMatic#1419]
Nach dem Update nahm die Funkqualität ab. Geräte die direkt neben dem HAP AccessPoint stehen, haben 90+ dBm. Ich habe die Vermutung, dass das Gateway nicht mehr genutzt wird. (bereits neu angelernt - keine Verbesserung).

Mit dem Homematic LAN Gateway gibt es keine Probleme.

Ausserdem wird eine UNREACH Fehlermeldung angezeigt obwohl Geräte eine Gute Funkqualität besitzen. 

<img width="1403" alt="Bildschirmfoto 2021-09-21 um 22 14 42" src="https://user-images.githubusercontent.com/91158428/134241681-a2983230-b920-49c2-98d9-69a695c441ea.png">

<img width="1401" alt="Bildschirmfoto 2021-09-21 um 22 14 56" src="https://user-images.githubusercontent.com/91158428/134241699-ec46f116-b959-4537-b205-89b230aa8c72.png">

**System information:**
 - RaspberryMatic Version: 3.59.6.20210911
 - Used Hardware: CCU3
 - Used HomeMatic RF-Module: ...

**Comment by jens-maus** [comment]
Sorry, but this is no support or discussion fora here. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. This was also already mentioned in the ticket template!
___
Tut mir leid, aber das hier ist kein Supportforum, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen.  Dies stand übrigens auch so im Ticket Template!
