### ISSUE TITLE
ssh not working with putty and winscp

### ISSUE THREAD

**Issue by online-junkie** [jens-maus/RaspberryMatic#142]
Maybe it is only me but I cannot get putty and winscp running with raspberrymatic.

I've tried the same with all images up to 20170731

I enabled ssh in webui and applied a password
I can login with root locally
ps Aef | grep ssh  -> yes, sshd is running

ssh from other system works

not working is:
- putty (session is closed directly)

By using sshd_conf from native jessie at least I can get putty connects working, but cannot find out which parameter is making the change.

K

**Comment by jens-maus** [comment]
Update your putty version to the very latest version because this is mostly caused by an old putty version not using the latest secure ssl ciphers, the sshd on raspberrymatic is uisng
