### ISSUE TITLE
Bedarf an zusätzlicher "Eigene Aktion während des Bootvorganges" irgendwo zwischen S40network und S51nut

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1421]
**Is your feature request related to a problem? Please describe.**
Ich nutze für den Zugriff auf die RaspberryMatic fast ausschließlich die IP-Adresse des Wireguard-Interfaces. 
Das Wireguard-Interface wird über die `/usr/local/etc/rc.prelocal` aktiviert. 
Das klappt für alle Bereiche wie WebUI, Watchdog-Oberfläche, Historian-AddOn etc. problemlos.
 
Nur der NUT-Netserver kann aktuell nicht an die IP-Adresse des Wireguard-Interfaces gebunden werden.
Der Grund ist simpel, der NUT-Netserver (`S51nut`) startet bevor das Wireguard-Interface (`S55InitAddons`) aktiviert wird.

Früher starten lässt sich das Wireguard-Interface (offiziell) aktuell nicht, da während der Ausführung der `/usr/local/etc/rc.postinit` (`S06InitSystem`) das nötige Netzwerk noch nicht zur Verfügung steht.

**Describe the solution you'd like**
Eine zusätzliche `rc.xxx` bspw. `rc.postnetwork` ausgeführt irgendwo zwischen `S40network` und `S51nut`

**Describe alternatives you've considered**
NUT-Netserver später starten

**Additional context**
Ich weiß, ist wieder mal ziemlich speziell. Wenn der NUT-Netserver an die Wireguard-IP gebunden werden könnte, könnte ich mir das zusätzliche Routing der regulären RaspberryMatic-IP-Adresse über das WireGuard-Interface sparen.

Grüße, Baxxy

**Comment by jens-maus** [comment]
Die Frage die sich mir hier als erstes stellt ist, wieso du genau den NUT Server an das Wireguard-Interface binden willst und warum das nicht dynamisch funktioniert? Eigentlich sollte nut doch automatisch auf allen Interfaces (auch auf denen die später dynamisch hinzugefügt werden dann lauschen). Wie genau hast du NUT denn konfiguriert? Auch wäre die Frage warum du nicht einfach nach dem Hochfahren des Wireguard Interface hingehst und NUT dann ggf. nochmal via `/etc/init.d/S51nut restart` neustartest? Das wäre doch eigentlich auch eine praktible Lösung, oder?

**Comment by Baxxy13** [comment]
Hallo Jens, danke für die Rückmeldung.

Warum ich das machen möchte steht ja schon im "Additional context" oben.
Ziel: kompletter Zugriff einzig über die Wireguard-IP.

Die NUT-Einrichtung habe ich nach der [ELV-Anleitung](https://files.elv.com/Assets/Produkte/11/1155/115579/Downloads/115579_650_einrichtung_raspberrymatic_v2_um.pdf) gemacht.
Die `upsd.conf` enthält entsprechende eine weitere Zeile um am WG-Interface zu lauschen:
```
LISTEN 127.0.0.1 3493
LISTEN 192.168.1.27 3493
LISTEN 10.64.1.27 3493
```
Mit diese Konfiguration startet NUT oder vllt. besser gesagt der upsmon nicht korrekt weil das WG-Interface nicht verfügbar ist.
```
Sep 25 23:31:23 Test-CCU-RMatic-Pi3Bplus daemon.info usbhid-ups[790]: Startup successful
Sep 25 23:31:23 Test-CCU-RMatic-Pi3Bplus daemon.err upsd[791]: not listening on 10.64.1.27 port 3493
Sep 25 23:31:23 Test-CCU-RMatic-Pi3Bplus daemon.info upsd[791]: listening on 192.168.1.27 port 3493
Sep 25 23:31:23 Test-CCU-RMatic-Pi3Bplus daemon.info upsd[791]: listening on 127.0.0.1 port 3493
Sep 25 23:31:23 Test-CCU-RMatic-Pi3Bplus daemon.err upsd[791]: no listening interface available
Sep 25 23:31:23 Test-CCU-RMatic-Pi3Bplus daemon.info upsmon[793]: Startup successful
Sep 25 23:31:23 Test-CCU-RMatic-Pi3Bplus daemon.err upsmon[795]: UPS [eaton3s@localhost]: connect failed: Connection failure: Connection refused
Sep 25 23:31:23 Test-CCU-RMatic-Pi3Bplus daemon.notice upsmon[795]: Communications with UPS eaton3s@localhost lost
Sep 25 23:31:28 Test-CCU-RMatic-Pi3Bplus daemon.err upsmon[795]: UPS [eaton3s@localhost]: connect failed: Connection failure: Connection refused
Sep 25 23:31:28 Test-CCU-RMatic-Pi3Bplus daemon.notice upsmon[795]: UPS eaton3s@localhost is unavailable
Sep 25 23:31:33 Test-CCU-RMatic-Pi3Bplus daemon.err upsmon[795]: UPS [eaton3s@localhost]: connect failed: Connection failure: Connection refused
Sep 25 23:31:38 Test-CCU-RMatic-Pi3Bplus daemon.err upsmon[795]: UPS [eaton3s@localhost]: connect failed: Connection failure: Connection refused
Sep 25 23:31:43 Test-CCU-RMatic-Pi3Bplus daemon.err upsmon[795]: UPS [eaton3s@localhost]: connect failed: Connection failure: Connection refused
.
.
.
Sep 25 23:36:33 Test-CCU-RMatic-Pi3Bplus daemon.notice upsmon[795]: UPS eaton3s@localhost is unavailable

```
Test lokal per ssh:
```
root@Test-CCU-RMatic-Pi3Bplus:~# upsc eaton3s@localhost
Error: Connection failure: Connection refused
root@Test-CCU-RMatic-Pi3Bplus:~# upsc eaton3s@10.64.113.27
Error: Connection failure: Connection refused
root@Test-CCU-RMatic-Pi3Bplus:~# upsc eaton3s@192.168.113.27
Error: Connection failure: Connection refused
```
So richtig dynamisch sieht das für mich nicht aus.

> NUT dann ggf. nochmal via `/etc/init.d/S51nut restart` neustartest? Das wäre doch eigentlich auch eine praktible Lösung, oder?

Wie es häufig so ist sieht man manchmal den Wald vor lauter Bäumen nicht.
Ja, das einfügen von `/etc/init.d/S51nut restart` (nach dem Wireguard-Start) in der `/usr/local/etc/rc.prelocal` funktioniert.
Je nach Pollintervall tauchen noch 1-3 der Meldungen...
`Sep 26 00:05:36 Test-CCU-RMatic-Pi3Bplus daemon.err upsmon[793]: UPS [eaton3s@localhost]: connect failed: Connection failure: Connection refused `
im Log auf, nach `S51nut restart` passt dann aber alles.

**Comment by jens-maus** [comment]
Hast du mal probier die LISTEN Statements in upsd.conf gänzlich weg zu lassen? Vllt bringt das ja schon etwas.

**Comment by Baxxy13** [comment]
Ja, das hatte ich probiert. 
Dann wird nur der Default (`localhost`) genommen. So lese ich das auch aus der [Dokumentation zu upsd.conf](https://networkupstools.org/docs/man/upsd.conf.html).
Das bringt mir aber nix, denn "überwacht" werden soll die USV lokal (RM) und per Wireguard-VPN von zu Hause per Homeassistant oder ioBroker (primär zum Datenloggen).

Der Workaround mit dem  `/etc/init.d/S51nut restart` funktioniert ja. 
Auch wenn es vllt. nicht die "sauberste" Lösung ist reicht mir das, denn die von mir benötigte Funktonalität ist damit gegeben.

Du kannst entscheiden ob wir zumachen oder die Idee mit der zusätzlichen `rc.xxx` vielleicht noch anderweitig nützlich sein könnte.

**Comment by jens-maus** [comment]
Ich würfe sagen wir behalten die Idee mal im Hinterkopf und schauen ob hier noch irgendwann andere Anwendungen aufkommen die ähnliche Probleme haben.

D.h. Für den moment machen wir hier mal wieder zu.
