### ISSUE TITLE
Anzahl von Protokolleinträgen von 10.000 auf beliebig viele erhöhen - z.B. für PocketControl

### ISSUE THREAD

**Issue by TobiasSt78** [jens-maus/RaspberryMatic#1425]
Hey,
mit dem Update 3.45.7.20190504 wurde die Anzahl Protokolleinträge schon einmal von 3.000 auf 10.000 erhöht. Ich bin mir sicher, dass der Raspi auch 100.000 verkraften würde. Das würde in PocketControl deutlich aufschlussreichere Diagramme und Auswertungen erlauben.
Wäre cool entweder die Zahl hoch zu setzen oder dem User die Anzahl vorgeben zu lassen.

Danke und Gruß, 
Tobias.

**Comment by jens-maus** [comment]
> Hey, mit dem Update 3.45.7.20190504 wurde die Anzahl Protokolleinträge schon einmal von 3.000 auf 10.000 erhöht. Ich bin mir sicher, dass der Raspi auch 100.000 verkraften würde. Das würde in PocketControl deutlich aufschlussreichere Diagramme und Auswertungen erlauben. Wäre cool entweder die Zahl hoch zu setzen oder dem User die Anzahl vorgeben zu lassen.

Es ist bereits möglich die Anzahl maximaler Protokollanträge anzuheben. Der Standard wurde nur von 3000 auf 10000 erhöht. Die jeweilige App muss/kann hier vollkommen selbst entscheiden wieviele es sein sollen die ReGaHss vorhalten soll damit man diese abholen kann von der Zentrale. Ich gebe jedoch zu bedenken, das es keine gute Idee ist das setzen dieses Wertes jetzt gar dem Nutzer zu überlassen, denn auch wenn 100000 Einträge vllt. in den Speicher moderner Systeme passen sollte, die WebUI wird diesbzgl. dann definitiv in die Knie gehen da sie nicht für solch große Tabellendarstellungen optimiert ist. Auch bezweifle ich das man wirklich 100.000 Einträge braucht. Wenn man soweit auswerten will sollte man auf andere Methoden oder andere Systeme (ioBroker, etc.) ausweichen.
