### ISSUE TITLE
Gewerke und Räume werden in der Geräteansicht auf einem Kanal nicht angezeigt

### ISSUE THREAD

**Issue by fischmir** [jens-maus/RaspberryMatic#1430]
**Gewerke und Räume werden in der Geräteansicht auf einem Kanal nicht angezeigt**
...

**Steps to reproduce the behavior**
1. HM-PB-6-WM55 neu anlernen
2. Nach dem Anlernen im Posteingang einen eigenen Namen vergeben
3. In der Geräteübersicht alle Kanäle mit der entsprechenden Funktion umbenennen
4. Kanal einem Raum und ein Gewerk zuordnen

**Expected behavior**
In der Übersicht der Geräte sollten in den entsprechenden Spalten des Kanals Raum und Gewerk stehen. Tatsächlich sind beide Felder leer. Wenn ich anschließend den Kanal öffne, sehe ich aber beiden Haken Raum und Gewerk. Datenbanktechnisch scheint die ZuO gespeichert zu sein, aber in der WebUI wird sie nicht in der Geräteübersicht angezeigt.

**Screenshots**
![overview](https://user-images.githubusercontent.com/29099751/135649490-85e1f076-2918-4edf-8cb5-8334b73184b6.png)
![channel](https://user-images.githubusercontent.com/29099751/135649497-6b697cc7-abf4-4b88-98db-b87067e70271.png)

**System information:**
 - RaspberryMatic Version: 3.59.6.20210911
 - Used Hardware: Raspberry 3
 - Used HomeMatic RF-Module: ...

**Additional context**
...

**Comment by fischmir** [comment]
Nach F5-Refresh war das Problem verschwunden.

Ich lass es euch bewerten, was aus diesem Issue passiert.

**Comment by jens-maus** [comment]
@Baxxy13 @jp112sdl Lässt sich das reproduzieren das erst nach einem refresh der Geräteliste die Gewerke/Raumzuordnung sofort ersichtlich ist?

**Comment by jp112sdl** [comment]
Ich kann es nicht reproduzieren. Sieht so aus:
<img src="http://g.recordit.co/vaPqR9LOLH.gif" />

**Comment by jens-maus** [comment]
@jp112sdl Ich glaube was @fischmir hier aufzeigen wollte ist nicht das anlegen neuer Gruppen. Sondern wenn man in der Geräteliste ist und ein Gerät einem neuen Raum od. Gewerk zuordnet wird das nicht sofort in der Geräteliste dann instantan dargestellt, sondern es braucht einen refresh der Geräteliste danach bis die Änderung dargestellt wird in der Liste.

**Comment by jp112sdl** [comment]
Ah ja stimmt, hab ich falsch verstanden.
Dann lässt es sich auch reproduzieren.
<img src="http://g.recordit.co/XZroqwAO3O.gif" />

Die Spalte Raum und Gewerk bleiben nach Zuweisung leer.

**Comment by jens-maus** [comment]
D.h. wir müssten dann im Grunde nur nach dem Schließen des Dialogs (mit OK) ein refresh der Geräteliste triggern damit Raum+Gewerk dann sofort sichtbar wird, ja?

**Comment by Baxxy13** [comment]
Lässt sich hier auch reproduzieren.
Es tritt aber tatsächlich nur auf wenn man die "Kanäle umbenennen" Funktion genutzt hat.
Andernfalls wird gleich alles korrekt angezeigt.

**Comment by jp112sdl** [comment]
Ein kompletter Reload nach jedem Raum/Gewerk zuordnen ist auch eher lästig, wenn man jedes Mal wieder hinscrollen muss.
Ist die Frage, was schlimmer ist. 
Das, oder die fehlende vorübergehende Anzeige in der Spalte

**Comment by jens-maus** [comment]
@jp112sdl Dann vllt. ein Reload wenn man die Kanäle umbenennen Funktion verwendet/eingesetzt hat?

**Comment by jp112sdl** [comment]
Also ein komplettes `reloadPage()` hiernach?
https://github.com/jens-maus/RaspberryMatic/blob/979e83a1423f028cff4a650abf9136bf85b279b7/buildroot-external/patches/occu/0099-WebUI-Add-DeviceRenameAllChannels.patch#L178-L179

**Comment by jens-maus** [comment]
> Also ein komplettes `reloadPage()` hiernach?

Genau sowas in der Art.

**Comment by jens-maus** [comment]
Bekommen wir das irgendwie vor dem kommenden Release noch repariert? Lust einer dazu nen PR zu machen? ;)

**Comment by jp112sdl** [comment]
Grad nur mal fix getestet: Der Aufruf von `reloadPage()` bringt bei mir keine Verbesserung.

**Comment by jp112sdl** [comment]
Kann es sein, dass nach dem Batch-Rename noch irgendwas fehlt?
Braucht die ReGa noch sowas wie ein `dom.RTUpdate(0);` ?

**Comment by jens-maus** [comment]
> Kann es sein, dass nach dem Batch-Rename noch irgendwas fehlt? Braucht die ReGa noch sowas wie ein `dom.RTUpdate(0);` ?

Kann ich mir schwer vorstellen. Wenn ein kompletter refresh der Seite bereits hilft kann ich mir schwer vorstellen das irgendwas in der ReGa-DB nicht ganz synchron ist und via RTUpdate synchronisiert werden müsste. Das sieht immer noch nach einem reinen Webbrowser/Javascript-Cache Problem aus das auftritt weil die Kanäle umbenannt werden und dann die Anzeige nicht mehr zu dem aktuellen Stand, etc. passt.

**Comment by jp112sdl** [comment]
@Baxxy13 kannst du mal testen:
Die beiden Zeilen aus meinem Kommentar https://github.com/jens-maus/RaspberryMatic/issues/1430#issuecomment-933796000 entfernen und stattdessen 1 Zeile einfügen: 
`this.ok();`.

Bei mir scheint das zu funktionieren.

**Comment by jens-maus** [comment]
> @Baxxy13 kannst du mal testen? Die beiden Zeilen aus meinem Kommentar [#1430 (comment)](https://github.com/jens-maus/RaspberryMatic/issues/1430#issuecomment-933796000) entfernen und stattdessen 1 Zeile einfügen: `this.ok();`.
> 
> Bei mir scheint das zu funktionieren.

Hab das gerade mal selbst getestet und das scheint in der Tat zu gehen. Super. Dann bau ich das so um. Die letzte Frage bleibt allerdings: Warum wurde das `updateView` und `reload` überhaupt damals mit reingenommen?

**Comment by jp112sdl** [comment]
> Warum wurde das updateView und reload überhaupt damals mit reingenommen?

Wahrscheinlich deshalb. 🤓 

Ich kann mich noch erinnern, dass ich vor dem Problem stand, dass nach den Umbenenn-Routinen immer noch die alten Bezeichnungen in der Liste standen.
Auf das einfachste - den Dialog mit `ok()` zu schließen, so wie es der Button-Klick macht - war ich nicht gekommen und ein DeviceList Reload führte optisch erstmal zum gewünschten Ergebnis...

**Comment by jens-maus** [comment]
> Auf das einfachste - den Dialog mit `ok()` zu schließen, so wie es der Button-Klick macht - war ich nicht gekommen und ein DeviceList Reload führte optisch erstmal zum gewünschten Ergebnis...

Alles klar, dann ist das ja nun auch geklärt und schwups, wieder ein Bug weniger für die nächste Version ;) Danke!
