### ISSUE TITLE
Tinkerboard S : Fehlermeldungen beim Bootvorgang bezüglich ZRAM Swap

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1435]
**Describe the bug**
Beim testen heute mit einem Tinkerboard S (eMMC-Boot) sind mir einige Fehlermeldungen bezüglich ZRAM Swap beim booten aufgefallen.

**Steps to reproduce the behavior**
1. Tinkerboard S an einen Monitor hängen und von eMMC booten
2. Ausgabe am Monitor betrachten

**Expected behavior**
Keine Fehlermeldungen beim Bootvorgang

**Screenshots**
![Tinker_S_ZRAM_Fehler](https://user-images.githubusercontent.com/54898249/135764191-b81df3f3-d5fe-44a5-8cdc-4c7ad5592485.jpg)

**System information:**
 - RaspberryMatic Version: RaspberryMatic-3.59.6.20211003-af5de2-tinkerboard
 - Used Hardware: Tinkerboard S eMMC - Boot
 - Used HomeMatic RF-Module: keines

**Additional context**
Das Tinker S startet problemlos durch und läuft dann auch ohne Auffälligkeiten.

**Comment by jens-maus** [comment]
Ok, ich konnte/kann das Problem hier reproduzieren. Leider ist die Ursache davon allerdings nicht ganz so einfach zu fassen. Es scheint irgendetwas mit neueren Kernelversionen zu tun zu haben, denn mit Kernel 5.10.62 in 3.59.6.20210911 tritt es wohl das erst mal auf. Hinter diesen gezeigten Fehlermeldungen verbirgt sich wohl, das ganz zu Anfang des Systems kein kernel modul mit `modprobe` geladen werden kann, sondern es beim allersten `modprobe` aufruf zu "Exec format error" Ausgaben kommt. Jedes darauffolgende `modprobe` schlägt dann aber komischerweise nicht mehr fehl. Eine detailliertere Analyse steht hier allerdings noch aus.

**Comment by Baxxy13** [comment]
Liest sich kompliziert. 
Aber super das du das Problem so schnell gefunden und einen Workaround implementiert hast.

Tatsächlich hat sich das Tinker gestern noch recht komisch verhalten inklusive spontanen Reboots. Kann aber nicht sagen ob da eventuell ein Zusammenhang bestand.
