### ISSUE TITLE
HmIP-BROLL: CCU3 Webinterface zeigt aktuelle Behanghöhe nicht mehr an

### ISSUE THREAD

**Issue by alexhass** [jens-maus/RaspberryMatic#1439]
**Describe the bug**

Seit ein paar kleineren RaspMatic-Versionen (ich denke irgendwann ende 2020/anfang 2021 ist das kaputt gegangen) wird der %-Wert in den Kanälen nicht mehr auf die aktuelle Behanghöhe aktualisiert, nachdem man die Behanghöhe geändert hat.

**Steps to reproduce the behavior**
1. HmIP-BROLL über "Status und Bedienung" > Geräte > [Aktor] öffnen
2. Der Rolladen steht auf 100% (offen)
3. In z.b. Kanal 4 gehen (Eingabefeld steht auf 100%) und auf auf die Pfeiltasten nach unten drücken und fahren lassen.
4. Wenn der Rollo ein bisschen gefahren ist - "Stop" drücken
5. Jetzt wird im Kanal 3 das Bild aktualisiert der neue %-Wert angezeigt z.b. 51%
6. Unter Kanal 4 wird in dem Eingabekästchen 0% angezeigt. Hier müsste auch 51% angezeigt werden, es wird aber 0% angezeigt. Dies ist der Bug.

**Expected behavior**
Korrekte Anzeige der Behanghöhe in den Eingabefeldern der Kanäle.

**Screenshots**

![2021-10-07_173236](https://user-images.githubusercontent.com/4450722/136419701-7dcf9f08-d654-4f1d-89b2-cc84fff91a94.jpg)

**System information:**
 - RaspberryMatic Version: 3.59.6.20210911
 - Used Hardware: CCU3
 - Used HomeMatic RF-Module: ?
 - Google Chrome: Version 94.0.4606.71 (Offizieller Build) (64-Bit)

**Additional context**
Nicht bekannt

**Comment by MichaelN0815** [comment]
Vielleicht meldet sich @jens-maus  ja nochmal zu diesem Bug Report...

**Comment by MichaelN0815** [comment]
Ganz altes Thema, hier 2019
https://homematic-forum.de/forum/viewtopic.php?t=54471

**Comment by jens-maus** [comment]
> Es handelt sich hoer um einen defekt. Das war anders und hat mal richtig funktioniert

Dann zeig das andere bzw. falsche Verhalten bitte mit entsprechenden Vergleichen mit einer älteren Version auf und leg das hier konkret dar. Die bisherigen Meinungen von @jp112sdl und @MichaelN0815 sprechen bis jetzt jedoch dagegen, denn hier wird die Meinung vertreten das dies so momentan korrekt ist.

**Comment by alexhass** [comment]
> > Es handelt sich hoer um einen defekt. Das war anders und hat mal richtig funktioniert
> 
> Dann zeig das andere bzw. falsche Verhalten bitte mit entsprechenden Vergleichen mit einer älteren Version auf und leg das hier konkret dar. Die bisherigen Meinungen von @jp112sdl und @MichaelN0815 sprechen bis jetzt jedoch dagegen, denn hier wird die Meinung vertreten das dies so momentan korrekt ist.

Hast du eine ccu3 über für mich? Ich leider nicht und in einer vm kann man es auch nicht installieren ohne hardware. Von daher kann ich diesen usability fail nicht nachweisen ohne hardware zu kaufen
