### ISSUE TITLE
CC1101

### ISSUE THREAD

**Issue by celevra** [jens-maus/RaspberryMatic#144]
hi,

is it working with a CC1101 also?

regards

**Comment by jens-maus** [comment]
What is "CC1101"? Provide reference and more detailed questions than just a one-liner.

**Comment by celevra** [comment]
oh i'm sorry, thought it was known. 
Its a transreceiver used in conjunction with the raspberry and homegear (https://www.homegear.eu/index.php/Main_Page) or fhem (https://fhem.de/) to control homematic devices.
it could be seen as an alternative to the ccu2.
but as it is working like a charm i thought it must be possible to use the same transreceiver with raspberryMatic.

i want to try a hom.ee (https://hom.ee), it connects to the ccu2, but i don't want to buy a ccu2 so i thought i could use my raspberrypi with my CC1101 and raspberryMatic, is this possible?

**Comment by jens-maus** [comment]
No, this is not possible ATM. RaspberryMatic and its internal processes are expecting RF modules that are compatible to the eQ3 hardware the CCU2 is using itself. So either you use a "HM-MOD-RPI-PCB" or "HM-LGW-O-TW-W-EU" to connect to your homematic devices.
