### ISSUE TITLE
Entscheidungswert kein Lösch Button

### ISSUE THREAD

**Issue by daniel01705** [jens-maus/RaspberryMatic#1440]
**Describe the bug**
Direkte Verknüpfungen
- PSM Konfiguration Entscheidungswert kein Lösch Button

 
**Steps to reproduce the behavior**
1. Erstellung Schaltaktor (PSM) einer Direkete Verknüpfung Entscheidungswert mit einem Kanal des Selben Schaltaktor (PSM)
2. Direkete Verknüpfung kann nicht gelöscht werden nur wieder Bearbeitet

**Expected behavior**
...

**Screenshots**
![grafik](https://user-images.githubusercontent.com/92117557/136443212-ddc5c42b-b908-42c4-85bd-226a60b29d9d.png)

**System information:**
 - RaspberryMatic Version: 3.59.6.20210911
 - Used Hardware: PI 3
 - Used HomeMatic RF-Module: RPI-RF-MOD

**Additional context**

**Comment by Baxxy13** [comment]
Gerade frisch reingekommen.
Wenn du die DV bearbeitest gibt es oben im Kopfbereich auch einen "Löschen-Button". 
Funktioniert bestens.

**Comment by daniel01705** [comment]
Super danke. Den habe ich bis jetzt immer übersehen. Den gibt es ja auch bei den Werksseitigen DV.
 

Gesendet: Mittwoch, 03. November 2021 um 16:42 Uhr
Von: "Baxxy13" ***@***.***>
An: "jens-maus/RaspberryMatic" ***@***.***>
Cc: "daniel01705" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [jens-maus/RaspberryMatic] Entscheidungswert kein Lösch Button (#1440)


 

Gerade frisch reingekommen.
Wenn du die DV bearbeitest gibt es oben im Kopfbereich auch einen "Löschen-Button".
Funktioniert bestens.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
