### ISSUE TITLE
lblChannelNotLinkable fehlt plaintext

### ISSUE THREAD

**Issue by Joerg-rw** [jens-maus/RaspberryMatic#1441]
Fehlende (deutsche?) "Uebersetzung" fuer "lblChannelNotLinkable"
...

**Steps to reproduce the behavior**
1. WebUI user Systemsprache Deutsch 
2. Startseite > Einstellungen > Geräte
3. HM-Sec-SC-2 aufblaettern
4. subchannel "xxx:0" wird "lblChannelNotLinkable" angezeigt

**Expected behavior**
Anstatt "lblChannelNotLinkable" sowas wie "Kanal nicht verknuepfbar" oder so

**Screenshots**
![Screenshot_20211009_000402](https://user-images.githubusercontent.com/19670108/136629490-2fa6d7c1-fbe5-4b18-a269-6f16a65d3eed.png)

**System information:**
 - RaspberryMatic Version: RaspberryMatic 3.59.6.20210911
 - Used Hardware: CCU3
 - Used HomeMatic RF-Module n/a.

**Additional context**
... n/a

**Comment by jens-maus** [comment]
Bitte mal Browser Cache löschen und auch ein Neustart der Zentrale probieren. Sollte das nicht helfen das Problem zu beseitigen, dann bitte hier noch einmal melden. Vermutung ist allerdings, das das Problem damit gelöst sein wird.

**Comment by jens-maus** [comment]
Hier das selbe. Auch ich kann das leider nicht reproduzieren. Vermuting ist hier also in der Tat das entweder dies etwa browser-spezifisches ist (Addon blocker, etc.) oder die Installation einen "Schuss" hat. Also bitte einfach mal die aktuelle Version nochmal "drüberinstallieren". Reproduzieren lässt es sich aber definitiv hier nicht.
