### ISSUE TITLE
WebUI: Add Script-test function to "Script Test" Window

### ISSUE THREAD

**Issue by robdg80** [jens-maus/RaspberryMatic#145]
Bitte in dem [Script-Testen Fenster](https://user-images.githubusercontent.com/12692680/29567235-d72b329a-874c-11e7-8b49-cb4884722ec7.png) eine Möglich eine "Fehlerprüfung" einzubauen.
Entweder als extra Button oder wie von Jens in #139 vorgeschlagen hat:

> Würde es nicht reichen einfach wie ich beschrieben habe immer vor jeder Ausführung eines Skriptes direkt vorher die Fehlerprüfung laufen zu lassen und falls die einen Fehler liefert erst gar nicht den Skript auszuführen und stattdessen die Fehlermeldung des Fehlertests darzustellen? Ich denke das würde mehr sinn machen. Warum sollte man einen separaten Button Fehlerprüfung haben? Ggf. könnte man das auch beim Skript bearbeiten so machen und den Fehlerprüfung-Button dort auch einsparen...

**Comment by jens-maus** [comment]
Nach weiterer Überlegung würde ich vmtl. doch vorschlagen einen extra "Fehler überprüfen" button einzubauen der nur eine Fehlerprüfung durchführt, jedoch den "Ausführen" Button wie von mir beschrieben trotzdem so agieren lassen das er vor der Ausführung immer eine Fehlerüberprüfung vorher durchführt.

**Comment by robdg80** [comment]
Vielleicht könnte man im "Script Testen" Fenster auch noch die Möglichkeit einbauen die Ausgabe alternativ als JSON auszugeben wie das der [scriptparser ](https://github.com/litti/scriptparser) kann.

Dort sieht man manchmal mehr als in der einfachen Ausgabe. Gerade wenn die Ausgabe nichts zurückgibt, weil das kein konformes JSON zurückkommt.

**Comment by jens-maus** [comment]
Dies sollte in der nächsten Version umgesetzt sein und das "Script Testen" automatisch ein Syntax Check vornehmen und ggf. Fehler dann zurückgeben.
