### ISSUE TITLE
seit 2.29.18 werden integer als xx.0000000 formatiert

### ISSUE THREAD

**Issue by FraatRamski** [jens-maus/RaspberryMatic#146]
seit der Version 2.29.18 werden integer anders formatiert als zuvor, to string scheint auch nicht mehr zu funtionieren.

Systemvariable Sprinkler_Index > (Zahlt wischen 0 und 9) bei diesem Beispiel Sprinkler_Index = 5

```
var temp = dom.GetObject("Sprinkler_Index"); 
integer SprinklerIndex =  temp.Variable();
WriteLine("SprinklerIndex>: " # SprinklerIndex);
WriteLine("To String>: " #SprinklerIndex .ToString(0));
```
Ausgabe 2.29.18:
```
     SprinklerIndex>: 5.000000
     To String>: 5.000000
```

Ausgabe altäre Versionen:
```
      SprinklerIndex>: 5
      To String>: 5
``` 
mit der neuen Vormatiereung funtionieren meine script nicht mehr!

**Comment by jens-maus** [comment]
Bitte folgende Anweisung zum konvertieren in einen Integer verwenden:

```
integer SprinklerIndex = temp.Variable().ToInteger();
```

D.h. das `ToInteger()` muss explizit angegeben werden. Damit bekomme ich dann hier folgende Ausgaben:

```
SprinklerIndex>: 5
To String>: 5
```

**Comment by DrTob** [comment]
das ToInteger() sollte zumindest bei "ToString(0)" nicht nötig sein. Ich kann das Problem jedoch bei mir nicht nachstellen. (2.29.18 + Rega-Beta) ToString(0) liefert keine Nachkommastellen.

**Comment by jens-maus** [comment]
Wenn man eine floating point zahl in integer (ohne nachkommastellen) wandeln möchte sollte man immer `ToInteger()` nutzen und statt `ToString(0)` besser `ToInteger().ToString()` nutzen wenn man die Von einer Gleitkommazahl kommende Ganzzahl in einen String wandeln möchte.

**Comment by DrTob** [comment]
ToString(0) und ToInteger().ToString() ist ein sehr großer Unterschied.

ToString(n) rundet, ToInteger() schneidet einfach ab.

aber auch unabhängig davon ob man die Verwendung als sinnvoll betrachtet oder nicht: ToString(0) muss eine Ausgabe ohne Nachkommastellen produzieren. (Was bei mir ja auch der Fall ist)

**Comment by jens-maus** [comment]
Ich meinte natürlich `ToInteger().ToString(0)`.

Aber das ToString(0) immer eine Ausgabe ohne Nachkommastellen produziert ist hier zumindest nicht immer der Fall:

```
var obj = dom.GetObject("Test");
obj.State(5.12345);
real test = obj.Variable();
real test2 = 5.12345;
WriteLine("A: " # test);
WriteLine("B: " # test.ToString(0));
WriteLine("C: " # test2.ToString(0));
```

Das ergibt bei mir folgende Ausgaben:

```
A: 5.123450
B: 5.123450
C: 5
```

Nun müsste man noch schauen welche Ausgaben das bei einer alten CCU Firmware bzw. ReGaHss erzeugt.

**Comment by DrTob** [comment]
ok. B ist damit falsch.

**Comment by jens-maus** [comment]
Kommt drauf an, soweit ich weiss wurde das ToString() mit Parameter niemals in der offiziellen Doku dokumentiert und von daher ist das verhalten undefiniert. Nur wenn bei einer alten ReGa-Version sich das ganze anders verhält würde ich sagen gibt es nun einen Bug.

**Comment by DrTob** [comment]
doch, Beispiel in Kapitel 6.1.2.

**Comment by FraatRamski** [comment]
Vielen Dank für die schnelle Rückmeldung. Der work arround hat schon geholfen.



Am 26.08.2017 um 12:27 schrieb DrTob <notifications@github.com<mailto:notifications@github.com>>:


doch, Beispiel in Kapitel 6.1.2.

**Comment by DrTob** [comment]
ich sehe gerade das Problem:

ToString(n) funktioniert nicht bei einer in einem String gehaltenen Zahl. Also:

var x = "1.2";
WriteLine(x.ToString(0));
--> ausgabe "1.2".


(--> .Variable() liefert immer einen String, deshalb das Verhalten von B in deinem Beispiel)

Hier würde ich tatsächlich einfach vergleichen ob sich das Verhalten geändert hat. Wenn ja: Korrigieren. Wenn nein: so lassen. Dann muss man Strings halt vorher in eine Zahl wandeln. (entweder mit ToInteger, oder durch (was ja wieder geht) Addition zu 0.0)

**Comment by jens-maus** [comment]
Danke für die Info. Das macht Sinn. Dann bitte noch kurz testen wie es mit einer alten ReGa (z.B. 2.27.8) sich verhält. Trotzdem könnte ich überlegen bei einem ToString() Aufruf mit Parameter immer den String vorher in einen Float/Real zu wandeln, wenn das gut geht dann die nachkommastellen zu strippen und dann wieder in einen String zu wandeln. Sollte gehen.
