### ISSUE TITLE
HmIP-PCBS-BAT Issues with 3.59.6.20211009 

### ISSUE THREAD

**Issue by jschnorr** [jens-maus/RaspberryMatic#1460]
Communication issues with RaspberryMatic Version 3.59.6.20211009 and HmIP-PCBS-BAT. 

**Steps to reproduce the behavior**
1. New installation of RaspberryMatic 3.59.6.20211009 
2. HmIP-PCBS-BAT - Factory reset
3. Connect HmIP-PCBS-BAT with newly (clean) RaspberryMatic
4. Everything seems to work
5. After sometime it stops working
6. Issue: Communication issue with device
7. Can't turn device on/off from WebUI
8. Pushing the small switch on the device works, connection issue dis disappears
9. But after a short while issue comes back

I went thru this cycle with two RaspberryMatics and four HmIP-PCBS-BAR devices. Several times.
HmIP-PCBS-BAT works with previous Version 3.59.6.20210807.

**Expected behavior**
Like in version 3.59.6.20210807.

**Screenshots**
None

**System information:**
 - RaspberryMatic Version: 3.59.6.20211009 
 - Used Hardware: 2 x Charly-Kits (Raspberry Pi 3 B, RPI-RF-MOD)
 - Used HomeMatic RF-Module: RPI-RF-MOD

**Additional context**
https://homematic-forum.de/forum/viewtopic.php?f=65&t=70008

**Comment by jens-maus** [comment]
There is no technical difference between 3.59.6.20210807 and 3.59.6.20211009 that could explain this issue. Both versions are based on 3.59.6 of the OCCU/CCU firmware, thus there is no communication difference here. In addition, you are already discussing things on the homematic fora (https://homematic-forum.de/forum/viewtopic.php?f=65&t=70008), thus find someone else first who can reproduce this issue or discuss potential reasons for the behaviour you are seeing in your installation and then come back and reopen this issue if someone else can reproduce it.

Tickets/Issue opened here should only be opened if in a previous discussion consent has been found that the issue might be related to a bug in RaspberryMatic itself.
