### ISSUE TITLE
Web-UI: "CCU:"/"DC:"/"CS:" nicht beschrieben

### ISSUE THREAD

**Issue by buzo-ffm** [jens-maus/RaspberryMatic#1462]
Auf der Startseite der Web-Oberfläche fehlt eine Beschreibung für die Anzeigen _„DC: x %“_ und _„CS: x %“_. Auch in der Dokumentation konnte ich nichts dazu finden.

**Steps to reproduce the behavior**
1. Öffnen und Anmelden an der Web-Oberfläche

**Expected behavior**
* Die Abkürzungen „DC“ und „CS“ werden irgendwo erklärt, z. B. in einem Tooltip, wenn man die Maus darüber bewegt. _DC_ steht vermutlich für _Duty Cycle_, aber _CS_ kann ich leider nicht erraten.

**System information:**
 - RaspberryMatic Version: 3.59.6.20211009
 - Used Hardware: ELV Charlie
 - Used HomeMatic RF-Module: ELV Charlie

**Comment by IT-VBFK** [comment]
CS = CarrierSense

Mr. Google war freundlich: https://technikkram.net/blog/2021/04/13/quicktipp-raspberrymatic-ueberwachung-und-anzeige-des-carriersense-auf-dem-startbildschirm/
