### ISSUE TITLE
optische Kleinigkeiten

### ISSUE THREAD

**Issue by detLAN** [jens-maus/RaspberryMatic#1466]
**Describe the bug**
Ein paar optische Kleinigkeiten

**Steps to reproduce the behavior**
1. Startseite > Status und Bedienung > Geräte
2. Gerät auswählen: HmIP-BSM, HmIP-BROLL, HMIP-PS, HMIP-PSM, HmIP-RC8

**Expected behavior**
Das Feld des Geräte Icons sollte vollständig Blau sein

**Screenshots**
So sollte es aussehen:
![Bild01](https://user-images.githubusercontent.com/64675966/138440380-ea6628bd-cf02-4825-ae0f-0cee66d87252.png)

So sieht es aus:
![Bild02](https://user-images.githubusercontent.com/64675966/138440441-76f95680-624d-4e92-a509-163e30e5df17.png)
![Bild03](https://user-images.githubusercontent.com/64675966/138440455-448c35f1-75bc-497f-aded-2460e7805bab.png)
![Bild04](https://user-images.githubusercontent.com/64675966/138440505-26e01077-b314-49d7-83ee-698e9ef36c76.png)

**System information:**
 - RaspberryMatic Version: 3.59.6.20211019
 - Used Hardware: RaspberryPi 4
 - Used HomeMatic RF-Module: RPI-RF-MOD

**Additional context**
Ähnliche optische Kleinigkeiten - auch hier sind die Felder nicht komplett Blau unterlegt:
![Bild10](https://user-images.githubusercontent.com/64675966/138440718-3bb8b0a9-a874-41ee-85d1-2128f3392c03.png)
![Bild11](https://user-images.githubusercontent.com/64675966/138440732-34d7ac9e-a763-4720-9a82-e66747b24465.png)
![Bild12](https://user-images.githubusercontent.com/64675966/138440738-13894c29-dbea-44ea-987b-1cd3c18c2d1e.png)

**Comment by jens-maus** [comment]
Ich kann das hier mit aktuellen nightly snapshots auch nicht nachvollziehen. Daher schließe ich hier nun mal. Bitte beim nächsten mal für jedes einzelne Problem ein separates Ticket/Issue aufmachen das man das auch getrennt verfolgen kann.

**Comment by detLAN** [comment]
> Ich kann das hier mit aktuellen nightly snapshots auch nicht nachvollziehen. Daher schließe ich hier nun mal. Bitte beim nächsten mal für jedes einzelne Problem ein separates Ticket/Issue aufmachen das man das auch getrennt verfolgen kann.

Auch mit dem aktuellen nightly snapshots sind alle genannten optischen Mängel weiterhin unter Safari vorhanden.

Safari Version 15.1
