### ISSUE TITLE
Release 2.29.18.20170731, installed CUxD 1.11 does not work

### ISSUE THREAD

**Issue by Chris5917** [jens-maus/RaspberryMatic#147]
![raspberrymatic cuxd](https://user-images.githubusercontent.com/31392346/29753945-ec4d869a-8b7b-11e7-8e1a-ad3733208263.png)

Installed RaspberryMatic on empty SD Card, 
Installed CUxD (RaspberryMatic Version, 1.11),
after that reboot took place, CUxD is listed under additional Software

BUT
a) only a new section appeared in "Additional Software", CUx-Daemon
b) the CuX-Daemon on the right side doesn't Show any release Version, while on the CCU2 it is mentioned
c) installed Version stays empty, but mentiones the V1.11 to be available

FINALLY
I click on "set" or "einstellen", and it shows the following issue:
- the HomateSystem Reports "RasberryMatic ist noch nicht bereit" and it Looks jus like a reboot
- the CUx-Daemon stats Report and Setup Options do not appear
- the Settings are not configurable - and are not accessible

Did I miss something during the Installation or is it a bug ?

Looking Forward to any Feedback.

Tx

**Comment by jens-maus** [comment]
Sorry, but I cannot reproduce this problem. Here I already installed CUxD several times without any such issues. Please use a new SD card and reinstall again and make sure that while installing CUxD you are not switching of the RaspberryPi yourself but wait until it is rebooted automatically.

**Comment by Chris5917** [comment]
Dear Jens,

sorry, it's reproduceable.

So I took a new card (8 GB), format it, and transferred the image.

![raspberrymatic cuxd -1](https://user-images.githubusercontent.com/31392346/29790066-a08912de-8c38-11e7-953f-13e157743bb4.png)
![raspberrymatic cuxd -2](https://user-images.githubusercontent.com/31392346/29790072-a563819a-8c38-11e7-8e8a-10b131e10c1f.png)

After the first boot everything looks fine, performance is perfect.
I have plain and running new CCU
Download the CUxDaemon 1.11 from your Github source. (CCU2)

![raspberrymatic cuxd -3](https://user-images.githubusercontent.com/31392346/29790117-e0e01bac-8c38-11e7-8313-d44133f06034.png)

I enter the menu of the Settings/Control-Panel/Additional Software
![raspberrymatic cuxd -4](https://user-images.githubusercontent.com/31392346/29790188-3a8edab2-8c39-11e7-8ce2-8968c9ee7757.png)

Browse to my downloaded file, and hit the install button, wait for the upload and start the installation.
After a quite long reboot time, the  RMatic comes back:
![raspberrymatic cuxd -6](https://user-images.githubusercontent.com/31392346/29790236-64fbb9f0-8c39-11e7-9d10-62df94dadb81.png)

I again miss the installed version number and the usually printed version number on the right side (see the red boxes).

If I hit the "Set" button, the blue boot screen is shown...

![raspberrymatic cuxd -7](https://user-images.githubusercontent.com/31392346/29790297-9e45449c-8c39-11e7-83b0-33fe9a758385.png)

... and then I find myself back on the initial homescreen.

This is reproducible.

Please tell me what am I doing wrong here.

Thanks and looking forward to your reply.

BR

**Comment by jens-maus** [comment]
Why are you using the CCU2 version of CUxD? You have to use the RaspberryMatic version of CUxD or you will certain run into problems. So download cuxd_1.11_ccurm.tar.gz and install that instead.

**Comment by Chris5917** [comment]
Dear Jens,

good question, I was mislead by my CCU2 device and maybe it was too late on that day to read your very clear documentation correctly.

Following your advice fixed the whole issue.

![raspberrymatic cuxd](https://user-images.githubusercontent.com/31392346/29845219-52454892-8d12-11e7-80ed-2e524dbb8d7f.png)

Thanks for your support, case closed.

Chris
