### ISSUE TITLE
Button Beschriftung fehlt

### ISSUE THREAD

**Issue by widmann-it** [jens-maus/RaspberryMatic#148]
Bei der Rückmeldung des Verknüpfungs- und Programmstatus fehlt der Button. 
Version 2.29.18.20170731

![grafik](https://user-images.githubusercontent.com/13391650/29882834-8f22e638-8dae-11e7-9797-240792b77d87.png)

**Comment by jens-maus** [comment]
Auch hier muss ich leider sagen das das bei mir so nicht angezeigt wird und sich bisher auch kein anderer Nutzer gemeldet hat der das selbe Problem hat. Daher bitte auch hier eine frische SD karte nehmen und RaspberryMatic erneut installieren und schauen ob es dort auch bereits auftritt.

**Comment by HMside** [comment]
Entweder Browser Cache leeren oder auf die 2.29.22er Version für RasberryMatic warten. Auf der CCU wurde mit der 22er Version eine Button Übersetzung korrigiert.
