### ISSUE TITLE
HomeMatic Addon configuration, Home Assistant OS 6.5

### ISSUE THREAD

**Issue by DudeMasterDE** [jens-maus/RaspberryMatic#1481]
Moin Jens,
the installation and configuration of the RaspberryMatic Addon works like a charm.
I also could add my HomeMatic RF and IP devices without a problem.
I also added the code in the config.yaml. as you mentioned.

But after that I fail to get the HomeMatic Addon running to use the devices in Home Assistant.
What configuration do I need for this second Addon?
Even when I try to start the HomeMatic addon with the standard configuration of the Addon (RF, IP and wired deactivated)
the HomeMatic Addon won't start.
Do I need to enter the port of my HM-MOD-RPI-PCB here as well?
the Addon says the connected device does not exist on that port.
What ever I try, as soon as I want to start the HomeMatic Addon I get an message on it't gui
"502 Bad Gateway" and the log file of it only produces a couple of lines....
I already asked in Home Assistant Community, they couldn't help me.

Do you have a clue?

**Comment by Baxxy13** [comment]
Soweit ich weiß kann man nicht beide AddOns gleichzeitig betreiben.
Du musst dich entscheiden welches du nutzen willst.

**Comment by jens-maus** [comment]
@DudeMasterDE As @Baxxy13 pointed out: Both Add-ons are NOT meant to be installed/used in parallel. In fact, the RaspberryMatic HA Add-on is a drop-in replacement for the traditional "Homematic HA Add-on" the HA developers provide themselves. Thus, that's exactly the reason why there is no documentation about using both in parallel!. Therefore this is a usage error!
