### ISSUE TITLE
Verlinkung "Programme und Verknüpfungen" ist defekt.

### ISSUE THREAD

**Issue by mbhomie007** [jens-maus/RaspberryMatic#1484]
**Describe the bug**
Die Verlinkung "Programme und Verknüpfungen" ist defekt.

Geht man über den Reiter "Programme und Verknüpfungen" auf "Direkte Verknüpfungen" ist der Link
"Startseite > Programme und Verknüpfungen > Direkte Verknüpfungen" defekt.
Ein Klick auf "> Programme und Verknüpfungen >" ist nicht möglich.

Geht man z.B. über den Reiter "Programme und Verknüpfungen" auf "Programme & Zentralenverknüpfungen" und dann mit einem Klick auf "Programme und Verknüpfungen" kommt man zur Übersicht.

**Steps to reproduce the behavior**
1. Klick auf "Programme und Verknüpfungen"
2. Klick auf "Direkte Verknüpfungen"
3. Versuche im Reihenfolgebaum auf "Programme und Verknüpfungen" zu klicken. Funktioniert nicht!
![image](https://user-images.githubusercontent.com/64688879/139557579-67717190-beb9-4e5d-9b61-2d636ffac9f5.png)

**Expected behavior**
...

**Screenshots**
![image](https://user-images.githubusercontent.com/64688879/139557391-fdf201a3-8464-439f-a0af-1e7a52b62069.png)

**System information:**
 - RaspberryMatic Version: Snapshot RaspberryMatic-3.59.6.20211030-66ae1b-rpi3.zip
 - Used Hardware: Raspberry 3b+
 - Used HomeMatic RF-Module: RPI-RF-MOD Funkmodul

**Additional context**
...

**Comment by Baxxy13** [comment]
Habe ich noch nie benutzt... 
Aber ja, es gibt auch einen Fehler in der Browser-Konsole:
```
Uncaught ReferenceError: LinksAndPrograms is not defined
    at HTMLSpanElement.onclick (index.htm?sid=@SGCrFzCz0k@:1)
```
Denn der Link ist wohl falsch hinterlegt:
`<span onclick="WebUI.enter(LinksAndPrograms);">Programme und Verknüpfungen</span>`

Korrekt wäre der Link so:
`<span onclick="WebUI.enter(LinksAndProgramsPage);">Programme und Verknüpfungen</span>`

**Comment by jens-maus** [comment]
Na dann freue ich mich auf den PR dazu ;)

**Comment by Baxxy13** [comment]
Zu früh gefreut, du bekommst nur ein diff... ;-)

```
--- /www/config/ic_linkpeerlist.cgi.orig
+++ /www/config/ic_linkpeerlist.cgi
@@ -62,7 +62,7 @@
     puts "<div id=\"id_body\">"
 
       puts "<script type=\"text/javascript\">"
-      puts "  setPath(\"<span onclick='WebUI.enter(LinksAndPrograms);'>\"+ translateKey('menuProgramsLinksPage') +\"</span> &gt; <span onclick='WebUI.enter(LinkListPage);'>\" + translateKey('submenuDirectLinks') + \"</span>\");"
+      puts "  setPath(\"<span onclick='WebUI.enter(LinksAndProgramsPage);'>\"+ translateKey('menuProgramsLinksPage') +\"</span> &gt; <span onclick='WebUI.enter(LinkListPage);'>\" + translateKey('submenuDirectLinks') + \"</span>\");"
       puts "  var s = \"\";"
       puts "  s += \"<table cellspacing='8'>\";"
       puts "  s += \"<tr>\";"


```

Hoffe das passt so.
