### ISSUE TITLE
Lange Übersetzung: "{actionStatusControlActive}" wird angezeigt

### ISSUE THREAD

**Issue by mbhomie007** [jens-maus/RaspberryMatic#1485]
Wenn man auf "Status und Bedienung" auf "Programme" klickt wird kurz die ganze Spalte ausgefüllt und "{actionStatusControlActive}" wird angezeigt. 
Nach kurzer Zeit sieht es wieder normal aus.

![687474703a2f2f672e7265636f726469742e636f2f7a4a4e496774304950612e676966](https://user-images.githubusercontent.com/64688879/139557641-542904b5-3f63-46b7-a2b0-3ba3e4aea3c4.gif)

System information:
RaspberryMatic Version: Snapshot RaspberryMatic-3.59.6.20211030-66ae1b-rpi3.zip
Used Hardware: Raspberry 3b+
Used HomeMatic RF-Module: RPI-RF-MOD Funkmodul 

 #1453 "Bearbeiten" Button in Status und Bedienung > Programme

**Comment by jens-maus** [comment]
Ich kann das leider weiterhin nicht nachvollziehen hier in meinen Testumgebungen und auch in meiner produktiven Umgebung passiert das mit dem latest nightly snapshot nicht. Vielleicht haben aber @theimo1221 oder @ptweety eine Idee bzw. Web-Debugging-Tools an der Hand die diese Verzögerungen bei der Übersetzung mittels `translatePage()` erklären können?

**Comment by ptweety** [comment]
Hallo @jens-maus,

ich kann das bei mir schon nachvollziehen. Allerdings wäre mir das ohne den Hinweis von @mbhomie007 auch nicht aufgefallen.

Wenn man z.B. in Chrome die DeveloperTools nutzt und im Bereich Leistung eine Aufzeichnung des Seitenaufrufs startet, dann kann man gerade so den Übergang von der rohen / nicht übersetzten Seite zur fertigen Version mit Übersetzung beobachten.

Da das aber alles auf Client Seite passiert ist es natürlich nicht von der Performance der CCU, sondern des Browsers und des benutzen Computers abhängig, wie schnell das JS zur Übersetzung abläuft.

Eine Lösung habe ich dafür im Moment auch nicht. Vielleicht hängt es damit zusammen, dass `translatePage` mehrfach aufgerufen wird und schon mit dem 1. Aufruf die Seite sichtbar gemacht wird. Siehe `jQuery(invisibleBeforeTranslationSelector).show();`in der aufgerufenen Funktion `setTextContent`.

<img width="1170" alt="devtools" src="https://user-images.githubusercontent.com/24972862/139738050-9e79e843-18a5-42fe-b230-ee12b5cd817c.png">

**Comment by jens-maus** [comment]
> Eine Lösung habe ich dafür im Moment auch nicht. Vielleicht hängt es damit zusammen, dass `translatePage` mehrfach aufgerufen wird und schon mit dem 1. Aufruf die Seite sichtbar gemacht wird. Siehe `jQuery(invisibleBeforeTranslationSelector).show();`in der aufgerufenen Funktion `setTextContent`.

Ah, das ist ein guter Hinweis. Vielleicht könnte das das erklären? Weil dort wird ja folgendes definiert:

``` js
    invisibleBeforeTranslationSelector = ".j_translate";
[...]
jQuery(invisibleBeforeTranslationSelector).show();
```

Für mich liest sich das danach, das alle Elemente die der CSS Klasse `j_translate` zugeordnet sind dort direkt sichtbar gemacht werden am ende der `setTextContent()` Funktion. Müsste man also mal mit diese `j_translate` CSS Zuordnung ein wenig spielen/experimentieren und schauen wann genau auch das `setTextContent()` aufgerufen wird damit man hier ggf. Elemente aus der `j_translate` CSS Klasse herausnimmt oder die Verarbeitung entsprechend ändert.

**Comment by theimo1221** [comment]
@mbhomie007 Wie viele Daten hast du auf der Seite und/oder was sind die Rahmeninformationen zu deinem Rechner/Browser mit dem du auf die WebUi zugreifst?

Zumindest nach den letzten Optimierungen dauert bei mir der Aufruf der von dir genannten Programmseite 60ms mit einem einzigen Rendervorgang am Ende.

**Comment by mbhomie007** [comment]
@theimo1221

Windows 10 mit Browser Chrome in aktueller Version. 
Acer Predator (Gaming PC) mit Intel Core i7. 

Ich denke an der Performance sollte es nicht scheitern.

Der oben gezeigte Screencast ist von @jp112sdl , bei mir ist es aber ganz genauso. 

#1453

**Comment by theimo1221** [comment]
Wie viele Programme sind in deiner Liste?
Bei mir sind es etwa 24.

Generell sieht zumindest deine Aufnahme so aus, els wenn da etwas nachgeladen wird und der Ablauf dadurch verzögert wird.
Zumindest bei mir in Chrome cached er aber die Bilder etc. sprich nach dem Anfragen des Prog.html Inhalts ist 50ms später das Skript und die Anzeige passend fertig.

**Comment by mbhomie007** [comment]
@theimo1221

Es sind auf jeden Fall unter 100 Programme, 
100% kann ich das gerade nicht sagen.

Genau, erst seit den neuen Snapshot Versionen kommt dies vor. Mit der letzten "Stable Version" sieht alles normal aus, aber da war ja auch noch nicht #1453 implementiert.

**Comment by MichaelN0815** [comment]
Hier wurde auch über das Problem berichtet, vielleicht helfen die Infos:
https://homematic-forum.de/forum/viewtopic.php?f=65&t=41974&start=620

**Comment by jens-maus** [comment]
So, ich denke ich hab das Problem nun zumindest verstanden warum es erst seit den umfangreichen CSS Verbesserungen/Umstrukturierungen auftritt. Hier die kurze Zusammenfassung:

1. Im Zuge der Breitenanpassung der `Status und Bedienung -> Programme` Tabelle habe ich in der `style.css` folgenden Eintrag hinzugefügt (siehe https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0039-WebUI-Fix-Style-Glitches/occu/WebUI/www/webui/style.css#L177-L180): 
   ```css
   #prgcontent
   {
     display: contents;
   }               
   ```
2. Dadurch wird aber nicht nur die Tabelle dann auf die maximale zur verfügung stehende Breite des Browser-Fensters (minus margin) korrekt angepasst, auch setzt das wohl leider die `j_translate` Logik ausser Kraft. Diese lässt nämlich alle Elemente die der CSS Klasse `j_translate` zugeordnet sind standardmäßig hiden und erst durch das `translatePage()` dann dynamisch anzeigen (eben wenn die Übersetzung passiert ist). Da nun jedoch dieses neue `#prgcontent` CSS statement hinzugekommen ist, überschreibt es das `display:none` des `j_translate` (siehe https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0039-WebUI-Fix-Style-Glitches/occu/WebUI/www/webui/style.css#L10-L13).
3. Nun habe ich versucht mit einem zusätzlichen CSS statement dem Herr zu werden und habe folgendes mal testweise zur `style.css` hinzugefügt:
   ```css
   #prgcontent.j_translate
   {           
     display: none;            
   }
   ```
   Das funktioniert auch soweit da die spezifität dieser CSS Anweisung die allgemeine `#prgcontent` Anweisung überschreibt. Und nun tauchen diese frühzeitig/kurzzeitig sichtbaren `${XXXXX}` Identifier nicht mehr auf (eben weil `prgcontent` dann erst eingeblendet wird wenn `translatePage()` das auch so anweist.
4. Allerdings führt das leider dazu, das der `.show()` Aufruf in `setTextContent()` dann ein `display:block` hinzufügt welches dann leider die Programmtabelle nicht mehr auf die maximal Breite des Browserfensters vergrößert (das scheint aus irgendeinem Grund nur via `display:contents` möglich zu sein). Siehe:
<img width="823" alt="Bildschirmfoto 2021-11-03 um 09 10 16" src="https://user-images.githubusercontent.com/5887769/140026961-d973b931-05a5-4db4-ac8b-844d8d8ed8fa.png">
5. Auch klappt es leider nicht, das ich einfach dem `prgcontent` div die style anweisung `width: 100%` mitgebe, weil damit aus irgendwelchen Gründen das über die maximale browserbreite hinaus vergrößert wird und damit die tabelle horizontal scrollbar wird. Siehe:

![Nov-03-2021 09-13-48](https://user-images.githubusercontent.com/5887769/140027477-9a9e5c07-752d-4a47-8c77-e2aecb12b1db.gif)
 
Vielleicht sollte hier mal ein Web/CSS Experte drüberschauen ob er dafür irgendeine Lösung findet, denn mir ist es nicht gelungen die Breite von `prgcontent` auf die maximale breite des Browserfensters zu beschränken sodass die `ProgramListTable` nicht über das Browserfenster hinaus vergrößert wird. Oder jemand (@theimo1221 oder @MichaelN0815 ) findet einen Weg wie man das Problem mit dem `show()` und dem `display:block` löst. Denn wenn ich `prgcontent` das style attribute `display:contents` mit auf den Weg gebe wird die Tabelle korrekt dargestellt.

Auf jedenfall denke ich, hab ich das Problem des verzögerten `translatePage()` nun verstanden und könnte es reparieren - eben wenn mir ein Web/CSS Experte hier vielleicht mal ein paar Tipps gibt oder sich die Sache selbst anschaut.

**Comment by MichaelN0815** [comment]
Logisch ist das auf jeden Fall nciht, aber das ist im Webdesign leider immer wieder so. Vor allem wenn Formatierungen aus verschiedenen Design-Epochen zusammentreffen. Ich würde es als ersten Ansatz ganz pragmatisch mit width:97% versuchen. Wenn das nicht klappt mit margin-right rumspielen. Vielleicht finde ich heute abend Zeit mir das mal anzusehen.

**Comment by jens-maus** [comment]
> Ich würde es als ersten Ansatz ganz pragmatisch mit width:97%

Nene, all diese "krummen" width Angaben habe ich ja explizit versucht aus de zentralen css von eQ3 soweit es geht zu eliminieren weil die IMHO mehr auf design Fehler, workaround und schlicht Faulheit hinweisen. ;-)

**Comment by ptweety** [comment]
Hm, ich würde da nicht noch mehr am css rumspielen, sondern eher überlegen, ob nach translatePage nicht per JS das display: content gesetzt werden kann.

**Comment by jens-maus** [comment]
> Hm, ich würde da nicht noch mehr am css rumspielen, sondern eher überlegen, ob nach translatePage nicht per JS das display: content gesetzt werden kann.

Das habe ich auch überlegt, aber das `translatePage` wird ja auch an anderen stellen verwendet wo man vllt. kein `display: contents` haben mag. Müsste man testen, aber auch das liest sich für mich nach einem teilweisen workaround. Ich verstehe wirklich nicht warum es mit `width:100%` passiert das `prgcontent` und damit die `ProgramListTable` über die Browser-Grenzen hinaus vergrößert wird. Wäre schön da könnte mal ein Web/CSS Experte drüberschauen.

**Comment by ptweety** [comment]
Ich dachte nicht an eine Änderung innerhalb von translatePage, sondern eher an
$("#prgcontent").css("display", "contents");
nach dem Aufruf von translatePage("#prgcontent");

**Comment by jens-maus** [comment]
> Ich dachte nicht an eine Änderung innerhalb von translatePage, sondern eher an $("#prgcontent").css("display", "contents"); nach dem Aufruf von translatePage("#prgcontent");

Dann müsste man das ja für alle anderen Stellen (das Problem ist nicht nur auf die `ProgramListTable` begrenzt) auch so umsetzen.

**Comment by jens-maus** [comment]
Danke für den Denkanstoß @ptweety. Habe es nun so für #prgcontent und #ic_linkpeerlist umgesetzt da das wohl die einzigen beiden Stellen sind die `j_translate` in kombination mit `display:contents` nutzen. Hatte erst versucht irgendetwas dynamisches in translatePage() zu bauen, so nach dem Motto "wenn #prgcontent == display:contents in css stylesheet, dann setze nach show() wieder display:contents" aber es gibt wohl keine einfache möglichkeit sich aus dem CSS stylesheet eine definition rauszusuchen und zu schauen ob die gesetzt ist. Daher nun eben doch wie von dir angeregt.
