### ISSUE TITLE
RF-LAN Gateway mit RPI-RF-MOD

### ISSUE THREAD

**Issue by lukicsl** [jens-maus/RaspberryMatic#1486]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Es wäre gut wenn das Modul RPI-RF-MOD such den LAN Gateway modus unterstützen würde
Wenn auch noch ein HM-IP repeater funktionalitä dabei wäre, wäre das noch besser.

**Comment by jp112sdl** [comment]
Geht aufgrund interner Restriktionen des Herstellers nicht.
Das Modul gibt die Funktionalitäten für ein LAN Gateway nicht her.
Ein Repeater-Modus für HmIP ist auch nicht vorgesehen.

**Comment by jens-maus** [comment]
Das ist leider nichts was dieses Projekt (RaspberryMatic) leisten kann. Die Firmware des RPI-RF-MOD ist komplett closed-source genauso wie die entsprechenden counter-parts Betriebssystemweise (rfd, HMIPServer). Insofern ist es vollkommen unrealistische das hier jemals das RPI-RF-MOD ohne zutun von eQ3 die Möglichkeit erhält eine LAN-Gateway Funktion ähnlich wie das alte HM-MOD-RPI-PCB zu bekommen. Selbst beim HM-MOD-RPI-PCB muss hierfür eine (ver)altete Firmware geflasht werden da im Kombinationsbetrieb von BidCos+HmIP auch dort keinerlei LAN-Gateway funktionalität möglich ist.

**Comment by jens-maus** [comment]
Und der "Repeater-Modus" für HmIP heisst HmIP-HAP, btw.
