### ISSUE TITLE
CUxD Timer nicht mehr veraenderbar

### ISSUE THREAD

**Issue by dehell** [jens-maus/RaspberryMatic#1489]
**Describe the bug**
Die eingestellten Zeiten eines CUxD Timers lassen sich nicht mehr aendern.

**Steps to reproduce the behavior**
1. Unter Einstellungen/Geräte ein CUxD Timermodul wählen und auf Einstellungen gehen
2. Den eingestellten Timerwert "System Timer Preset", bei mir 06:01:00/06:15:00 auf 06:01:00/06:18:00 ändern.
3. Die Seite mit OK oder übernehmen / OK verlassen.
4. Erneut das Timermodul aufrufen, der Wert steht wieder auf 06:01:00/06:15:00

**Expected behavior**
Die Änderungen sollten übernommen werden.

**Screenshots**
...

**System information:**
 - Raspi 3.59.6.20211009
 - CUxD 2.1.6 und 2.6 getestet
 

**Additional context**
...

**Comment by Baxxy13** [comment]
Ok, kann ich reproduzieren.
Änderungen vor dem `/` werden sauber übernommen, alles was hinter dem `/` geändert wird, wird nicht übertragen.
Keine Fehlermeldungen in der Browserkonsole.
Scheint auch kein Problem bezüglich ProofAndSetValue zu sein.
`<input type="text" name="TIMER_PRESET" value="06:11:00/06:18:00" id="separate_CHANNEL_1_3">`

Vermutung: 
Irgendwas mit Escaping

Workaround: 

- Timer komplett rauslöschen
- Übernehmen klicken 
- neuen Timer eintragen
- Übernehmen oder OK klicken

**Comment by uwe111** [comment]
Dieser Fehler tritt nur in Verbindung mit Multitimern beim Ändern des **TIMER_PRESET** Parameters auf, wenn die Konfiguration des 1. Timers (hier 06:11:00) gleich bleibt. Beim Setzen des Timers mittels **TIMER_SET** Datenpunkt tritt dieser Fehler nicht auf.
In der nächsten CUxD-Version wird es repariert sein.

**Comment by jens-maus** [comment]
@uwe111 Danke für die Klarstellung Uwe. Dann ist das also nichts was hier im RaspberrryMatic Projekt addressiert werden muss.
