### ISSUE TITLE
Einbindung Homematic IP Präsenzmelder – innen - Bild fehlt

### ISSUE THREAD

**Issue by widmann-it** [jens-maus/RaspberryMatic#149]
Bei dem Präsenzmelder einbindung fehlt leider das Foto was bei der Einbindung in ein Programm zu einem kleinen Problem führt - Um den Melder anzuzeigen muss mehrfach rauf und runter gescrollt werden. Dann wird er Angezeigt mit der Meldung das das Bild fehlt.

![grafik](https://user-images.githubusercontent.com/13391650/29883137-901ca14a-8daf-11e7-9379-7b21aa7a7e60.png)

Version 2.29.18.20170731

**Comment by jens-maus** [comment]
Das Problem kann ich hier leider nicht bestätigen denn hier geht der HmIP-SPI ohne Probleme und wird auch in der Geräteliste korrekt angezeigt. Siehe:

![screenshot_145](https://user-images.githubusercontent.com/5887769/29892538-3990d3d0-8dcf-11e7-8994-6bf2fd7b4858.png)

Bitte einmal eine neue RaspberryMatic Installation auf einer frischen SD Karte durchführen und dort den Präsenzmelder einmal separat anmelden.
