### ISSUE TITLE
Darstellung Systemvariablen nicht mehr möglich (weiße Seite)

### ISSUE THREAD

**Issue by iversIO** [jens-maus/RaspberryMatic#1490]
**Describe the bug**
Leider ist das alte Problem (https://github.com/jens-maus/RaspberryMatic/issues/475) mit der Darstellung der Systemvariablen unter „Einstellungen“ - für mich - aktuell nicht mehr gelöst; die Werte aller Systemvariables kann ich mir problemlos ansehen (Status und Bedienung). Das aktuelle Problem entspricht also so ziemlich dem, wie es in dem Issue bereits beschrieben ist, nur das ich weit weniger als 600 Systemvariablen habe - dafür aber mit längeren Namen.

**Steps to reproduce the behavior**
siehe altes Issue

**Expected behavior**
siehe altes Issue

**Screenshots**
<img width="1256" alt="Bildschirmfoto 2021-10-31 um 18 13 58" src="https://user-images.githubusercontent.com/93486311/139594717-27662015-4034-45ad-b824-d9ed2328c01c.png">
<img width="1247" alt="Bildschirmfoto 2021-10-31 um 18 14 23" src="https://user-images.githubusercontent.com/93486311/139594719-49856053-e151-461b-bf04-7920a04b2efb.png">

**System information:**
 - RaspberryMatic Version: 3.59.6.20211009
 - Used Hardware: Synology NAS DS720+
 - Used HomeMatic RF-Module: HB-RF-USB-2

**Additional context**
-  https://github.com/jens-maus/RaspberryMatic/issues/475
- Problem trat "von jetzt auf gleich" auf
- Darstellung unter "Status und Bedienung" funktioniert derzeit (noch) fehlerfrei

**Comment by jens-maus** [comment]
> **Describe the bug** Leider ist das alte Problem (#475) mit der Darstellung der Systemvariablen unter „Einstellungen“ - für mich - aktuell nicht mehr gelöst; die Werte aller Systemvariables kann ich mir problemlos ansehen (Status und Bedienung). Das aktuelle Problem entspricht also so ziemlich dem, wie es in dem Issue bereits beschrieben ist, nur das ich weit weniger als 600 Systemvariablen habe - dafür aber mit längeren Namen.
> 
> **Steps to reproduce the behavior** siehe altes Issue
> 
> **Expected behavior** siehe altes Issue

Tut mir leid, aber du referenzierst hier einfach nen altes/geschlossenes Ticket das sich mit einer max. Anzahl  von Systemvariablen beschäftigt und dort Darstellungsprobleme benennt, sagst aber gleichzeitig das du weniger hast. Das passt nicht zusammen. 

Bitte neues Ticket aufmachen und das Problem beschreiben ohne jegliches Referenz zum alten Ticket, denn nur weil es sich "ähnlich liest" ist es nicht das gleiche. Beschreibe dein Problem komplett neu und geb beispiele, versuche die Systemvariable rauszufinden bei der du der Meinung bist das diese auf Grund ihrer Namenslänge probleme macht und benenne diese.
