### ISSUE TITLE
Gerätekommunikation gestört

### ISSUE THREAD

**Issue by rudi-liebl** [jens-maus/RaspberryMatic#1501]
Seit dem Update auf die Neu Version von Raspimatic (3.59.6.20211009) erhalt ich immer öfter die Meldnung Gerätelommuniktion gestört. Ich steuere mein Heizkörper und die Fußbodenheizung so wie die Fensterkontakte  über den Raspimatic (Funkverbindug). Ich kann die Störung beheben in den ich am Wandthermostat die Temperatur ändere und dann auf den Sendeknopf drücke. Aber die meisten Änderungen im Webbrowser bringen diese Meldung.

**Comment by jens-maus** [comment]
Sorry, but this is no support or discussion fora here. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. This was also already mentioned in the ticket template!
___
Tut mir leid, aber das hier ist kein Supportforum, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen.  Dies stand übrigens auch so im Ticket Template!

**Comment by blackbasket** [comment]
Exakt das selbe!

**Comment by jens-maus** [comment]
Kein Grund das HIER zu diskutieren. Das gehört in eine Diskussionsforum und nicht in ein Bug/Issue-Tracker.
