### ISSUE TITLE
Inkonsistenzen bezüglich Zurück-/Abbrechen- Button beseitigen

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1504]
**Describe the bug**
Kein Bug im eigentlichen Sinne.
Es gibt noch ein paar Stellen an denen der Button unten links mit "Abbrechen" statt "Zurück" beschriftet ist.
Gefunden habe ich den "Abbrechen-Button" beim:

> Bearbeiten von Direktverknüpfungen
> Bearbeiten von Favoriten
> Bearbeiten von Gruppen
> Bearbeiten von Systemvariablen (direkt im PopUp) 

**Steps to reproduce the behavior**
1. einen der erwähnten Bereiche bearbeiten
2. die "Abbrechen" - Beschriftung des Buttons sehen

**Expected behavior**
Konsistenz bei der Button - Beschriftung

**Screenshots**
![RM_Inkonsistenz Zurück Abbrechen Button](https://user-images.githubusercontent.com/54898249/140495399-c7176388-46ac-4c46-9311-48f7dd2694b1.JPG)

**System information:**
 - RaspberryMatic Version: Nightly 3.61.4.20211105
 - Used Hardware: Pi3B+
 - Used HomeMatic RF-Module: RPI-RF-MOD auf HB-RF-USB-2

**Additional context**
...

**Comment by mbhomie007** [comment]
Dabei finde ich, das das Wort "Abbrechen" die Aktion wesentlich besser ausdrückt.

**Comment by jens-maus** [comment]
> Dabei finde ich, das das Wort "Abbrechen" die Aktion wesentlich besser ausdrückt.

Ich nicht, da "bricht" man ja in dem Kontext nicht wirklich etwas "ab", sondern man kehrt damit zurück zu dem wo man vorher war.

**Comment by MichaelN0815** [comment]
Hoffen wir mal das die User, die eine verunglückte Bearbeitung abbrechen wollen, das auch so sehen.

**Comment by mbhomie007** [comment]
Inkonsistenz noch vorhanden.

**Comment by Baxxy13** [comment]
Inkonsistenz weiterhin vorhanden!

**Comment by mbhomie007** [comment]
Inkonsistenz weiterhin vorhanden.
