### ISSUE TITLE
"Status und Bedienung -> Gewerke" Sortierung/Reihenfolge (A-Z/0-9) fehlerhaft

### ISSUE THREAD

**Issue by mbhomie007** [jens-maus/RaspberryMatic#1508]
### Describe the issue you are experiencing

Hallo @jens-maus @ptweety
Wie in #1492 bereits dargestellt.
Mache dazu mal ein extra Ticket auf, damit es nicht in Vergessenheit kommt.

Unter "Status und Bedienung -> Gewerke" muss man 2 Mal auf den Tabellenkopf "Name" klicken um zur üblichen Sortierung (A-Z/0-9) zu kommen.
Verlässt man die Seite, so ist die Einstellung für die Sortierung wieder weg.

Unter "Status und Bedienung -> Geräte" hingegen bleibt die Sortierung richtig erhalten -> funktioniert.
Es wir standartmäßig von (A-Z/0-9) sortiert.

![](https://user-images.githubusercontent.com/64688879/140375143-9e880c64-188a-4b7a-a2a2-4e920b7cc174.png)

![](https://user-images.githubusercontent.com/64688879/140375289-7f05db33-d32f-4c4d-9c69-141d3669a895.png)

### Describe the behavior you expected

Gleiche Sortierung wie über "Status und Bedienung -> Geräte" (A-Z/0-9).
Die Einstellung sollte standartmäßig hinterlegt sein.

### Steps to reproduce the issue

1. Unter "Status und Bedienung -> Gewerke" muss man 2 Mal auf den Tabellenkopf "Name" klicken um zur üblichen Sortierung (A-Z/0-9) zu kommen.

### What is the version this bug report is based on?

Snapshot RaspberryMatic-3.61.4.20211106-aaec62-rpi3

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
-
```

**Comment by mbhomie007** [comment]
Bin der aktuellen Version 3.61.5.20211113 tritt das Problem leider weiterhin auf.

**Comment by mbhomie007** [comment]
Auch mit der aktuellsten Version 3.61.7.20220115 tritt das Problem weiterhin auf und kann reproduziert werden.

**Comment by mbhomie007** [comment]
Problem ist noch präsent.

**Comment by mbhomie007** [comment]
Problem besteht weiterhin

**Comment by mbhomie007** [comment]
Problem besteht weiterhin.

@ptweety

Hast du Kapazität das zu fixen?
Soweit ich weiß, warst du schonmal bei der Sortierung am werkeln.

**Comment by ptweety** [comment]
Leider habe ich von TCL zu wenig Ahnung und traue mich da nicht ran.

**Comment by mbhomie007** [comment]
Problem ist immer noch vorhanden.
