### ISSUE TITLE
Error: CompatibleForCompare of ISEVALUE

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#151]
Starting with 2.29.22.20170902 the following messages are emitted by ReGaHss if e.g. a system variable of type int (0 - 65000) is part of a program as a condition.

```
Error: CompatibleForCompare of ISEVALUE unknown not supported! [iseValue.cpp:411]
```

**Comment by jp112sdl** [comment]
Is there any workaround? 
The error only occurs on RaspberryMatic?

I created a program on the CCU2 that ran perfectly.

Now I recreated the same program in RaspberryMatic and I always get that error when I have a CUxD Dimmer Device as its condition :/

**Comment by jens-maus** [comment]
Nope, there isn't currently any workaround. The fix requires a new ReGaHss version which will be hopefully be released soon as a new beta20 version, then I will post information on a potential workaround.

**Comment by jens-maus** [comment]
beta20 of ReGaHss should fix this problem:
https://homematic-forum.de/forum/viewtopic.php?f=26&t=36623&start=570#p383585
