### ISSUE TITLE
Time triggers not executed logging error "ReGaHss: ERROR: interface pointer are not initialized [CheckValidTime():iseDOMdpCal.cpp:150]"

### ISSUE THREAD

**Issue by georgekue** [jens-maus/RaspberryMatic#1510]
### Describe the issue you are experiencing

After upgrade to version 3.59.6.20211009, one of my programs (no scripts included) stopped working correctly. This might only be a temporal coincidence with the version update.

The program consists of some logic in the IF part with sun elevation and azimuth angles. What is not working is the ELSE part where I straight forwardly use some time triggers to set a boolean system variable to FALSE. This unfortunately does not happen.

### Describe the behavior you expected

A system variable should be set to FALSE depending on some time triggers.

### Steps to reproduce the issue

This is the screenshot of the program.

![Screenshot 2021-11-07 at 14-52-25 HomeMatic WebUI](https://user-images.githubusercontent.com/6309860/140647901-e9929c5f-6d58-4de4-b9f5-f1e7e245a52b.png)

### What is the version this bug report is based on?

3.59.6.20211009

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

In the logs, I can see that both IF and ELSE parts are evaluated. However, there ist a Regass error message right bevore the evaluation of the current time, and I presume that this might be the cause of the problem:

```txt
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: called Program ID = 4075 'Rollladen Nachtbetrieb' with valNew = '15.992232' ; oidTrigger = 3486 [SetState():iseDOMPrg.cpp:483]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: DP_VALUE_CHECK_CHANGE is set, trigger dp exists  [CheckCondition2Data():iseCondition.cpp:528]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: type = DP_LESSOREQUAL, condition valL = 15.992232 valR1 = -5.000000 [Evaluate():iseCondition.cpp:338]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: sc = 0, condition result = 0 [Evaluate():iseCondition.cpp:1078]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: sc = 0, CONDITION_TRIGGER_EXECUTE is reset. [Evaluate():iseCondition.cpp:1116]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: sc = 0, condition result = 0 [Evaluate():iseCondition.cpp:1123]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: DP_VALUE_CHECK_ONLY is set, condition = 1 [CheckCondition2Data():iseCondition.cpp:488]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: type = 1, condition valL = 1 valR1 = 0 [Evaluate():iseCondition.cpp:392]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: sc = 1, condition result = 0 [Evaluate():iseCondition.cpp:1078]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: sc = 1, condition result = 0 [Evaluate():iseCondition.cpp:1123]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: DP_VALUE_CHECK_ONLY is set, condition = 1 [CheckCondition2Data():iseCondition.cpp:488]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: type = DP_GREATER, condition valL = 214.824527 valR1 = 180.000000 [Evaluate():iseCondition.cpp:317]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: sc = 2, condition result = 0 [Evaluate():iseCondition.cpp:1078]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: sc = 2, condition result = 0 [Evaluate():iseCondition.cpp:1123]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: c = 0, CONDITION_TRIGGER_EXECUTE is reset. [Evaluate():iseRule.cpp:227]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: c = 0, condition result = 0 [Evaluate():iseRule.cpp:235]
Nov  7 14:36:00 homematic-raspi local0.err ReGaHss: ERROR: interface pointer are not initialized [CheckValidTime():iseDOMdpCal.cpp:150]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: type = Timer Module (CalDaily), CheckValidTime() = false, current time = 2021-11-07 14:36:00 [Evaluate():iseCondition.cpp:274]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: sc = 0, condition result = 0 [Evaluate():iseCondition.cpp:1078]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: sc = 0, condition result = 0 [Evaluate():iseCondition.cpp:1123]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: DP_VALUE_CHECK_ONLY is set, condition = 1 [CheckCondition2Data():iseCondition.cpp:488]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: type = 1, condition valL = 0 valR1 = 0 [Evaluate():iseCondition.cpp:392]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: sc = 1, condition result = 0 [Evaluate():iseCondition.cpp:1078]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: sc = 1, condition result = 0 [Evaluate():iseCondition.cpp:1123]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: c = 0, condition result = 0 [Evaluate():iseRule.cpp:235]
Nov  7 14:36:00 homematic-raspi local0.err ReGaHss: ERROR: interface pointer are not initialized [CheckValidTime():iseDOMdpCal.cpp:150]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: type = Timer Module (CalDaily), CheckValidTime() = false, current time = 2021-11-07 14:36:00 [Evaluate():iseCondition.cpp:274]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: sc = 0, condition result = 0 [Evaluate():iseCondition.cpp:1078]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: sc = 0, condition result = 0 [Evaluate():iseCondition.cpp:1123]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: c = 1, condition result = 0 [Evaluate():iseRule.cpp:235]
Nov  7 14:36:00 homematic-raspi local0.err ReGaHss: ERROR: interface pointer are not initialized [CheckValidTime():iseDOMdpCal.cpp:150]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: type = Timer Module (CalDaily), CheckValidTime() = false, current time = 2021-11-07 14:36:00 [Evaluate():iseCondition.cpp:274]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: sc = 0, condition result = 0 [Evaluate():iseCondition.cpp:1078]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: sc = 0, condition result = 0 [Evaluate():iseCondition.cpp:1123]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: DP_VALUE_CHECK_ONLY is set, condition = 1 [CheckCondition2Data():iseCondition.cpp:488]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: type = 1, condition valL = 0 valR1 = 1 [Evaluate():iseCondition.cpp:392]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: sc = 1, condition result = 0 [Evaluate():iseCondition.cpp:1078]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: sc = 1, condition result = 0 [Evaluate():iseCondition.cpp:1123]
Nov  7 14:36:00 homematic-raspi local0.debug ReGaHss: Verbose: c = 2, condition result = 0 [Evaluate():iseRule.cpp:235]
Nov  7 14:36:00 homematic-raspi local0.info ReGaHss: Info: Rule evaluated state is FALSE by Program ID = 4075 'Rollladen Nachtbetrieb' [SetState():iseDOMPrg.cpp:536]
```

**Comment by MichaelN0815** [comment]
Dein Programm Konstrukt weckt in mir den Verdacht, daß Du die WebUI Logik noch nicht zu 100% verinnerlicht hast.

So komplett unterschiedliche Trigger gehören in unterschiedliche Programme, sonst kommen oft unerwartete Ergebnisse raus.

Jedes der Ereignisse kann das Programm triggern, egal ob im SONST oder im WENN. Und es wird dann von oben nach unten geprüft, bis zur ersten wahren Bedingung. Das muss nicht die auslösende sein! Dein 10 Uhr Zeitmodul zum Beispiel - löst aus und ist wahr. Wofür nochmal 10 Uhr mit einer weiteren Bedingung? Sinnlos.

Ja, Programm hat immer funktioniert... Wie lange? Letzten Herbst auch schon?

Es ist nicht auszuschließen, dass das Zeitmodul einen Schlag hat. Passiert wohl immer mal wieder. Aber ich würde dir eh dringend raten daraus 2 getrennte Programme zu machen und damit ist das Problem so oder so gelöst.

**Comment by georgekue** [comment]
Hi,

dass ODER-Bedingungen von oben nach unten bis zum ersten Treffer abgearbeitet werden, ist ja normal.

Am Screenshot siehst Du nicht, dass die 10-Uhr-Bedingungen sich auf verschiedene Tage beziehen (mal Werktage, mal Wochenenden, bei Werktagen nur, wenn die Variable "Feiertag" TRUE ist).

Das Problem ist , dass die Systemvariable "Nachtbetrieb" im Moment NIE auf "FALSE" gesetzt wird, es zieht also KEINE der ODER-Bedingungen.

OK, ich teile das Programm auf, obwohl es seit 18 Monaten zuverlässig seinen Dienst erfüllt hat. Wird damit halt unübersichtlicher.

**Comment by MichaelN0815** [comment]
OK, prinzipiell müsste es so gehen, auch wenn ich das vermeiden würde. Vielleicht kommt Jens mit deiner Meldung mal dem Problem auf die Spur.

**Comment by georgekue** [comment]
Ok, danke! Ich berichte, ob das Aufteilen funktioniert hat. Wird wohl so sein.

**Comment by jens-maus** [comment]
Also diese `ReGaHss: ERROR: interface pointer are not initialized [CheckValidTime():iseDOMdpCal.cpp:150]` Meldungen sind in der Tat komisch und deuten auf irgendein Initialisierungsproblem in den TimeModulen dieses Programmes hin. Interessant wäre also daher einmal die Einstellungen dieser beiden TimeModule Einträge detailliert zu sehen. Auch wäre es hilfreich wenn du versuchen könntest auf einer zweiten virtuellen Zentrale das Problem zu reproduzieren oder dein Backup zur Verfügung stellst damit ich versuchen kann das selbst einmal zu reproduzieren, denn eigentlich sollten dieser `interface pointer are not initialized` Meldungen sollten eigentlich nicht auftreten soweit ich das überblicke im Moment.

**Comment by georgekue** [comment]
OK, ich habe mein Programm auf @MichaelN0815 s Anregung aufgeteilt, so dass der ELSE-Zweig jetzt in einem eigenen Programm läuft. Das hat heute früh sauber funktioniert, und im Log gibt es die Fehlermeldung nicht mehr.
Vermutlich hat einfach die Neuanlage schon geholfen.
Weitere bestehende Programme mit fester Zeitsteuerung (um xyz Uhr) kommen mit der Weihnachtbeleuchtung ;-) dazu, diese Programme sind derzeit noch deaktiviert. Ich werde sie aktivieren und schauen, ob sie auch diesen Fehler produzieren.
@jens-maus Das Backup von VOR meiner Änderung gestern nachmittag kann ich gerne zur Verfügung stellen. Wohin damit? Muss ich was anonymisieren?

**Comment by jens-maus** [comment]
> @jens-maus Das Backup von VOR meiner Änderung gestern nachmittag kann ich gerne zur Verfügung stellen. Wohin damit? Muss ich was anonymisieren?

Du kannst es mir irgendwo ablegen und schickst mir dann am besten eine private Email mit der Info wo ich es runterladen kann. Anonymisieren musst du nur wenn du mir nicht vertraust das ich damit kein Schindluder treiben werde ;)

**Comment by georgekue** [comment]
@jens-maus  Danke, habe Dir das Backup per PM bereitgestellt. 

Das letzte Versionsupdate habe ich übrigens am 26.10. durchgeführt, und zwar 

- von 3.59.6.20210911
- auf 3.59.6.20211009

Ich könnte schwören (ich weiß: glauben ist nicht wissen), dass das Problem seither auftrat.

**Comment by jens-maus** [comment]
> Danke, habe Dir das Backup per PM bereitgestellt.

Alles klar, hab es heruntergeladen. Kannst es also wieder entfernen. Bitte aber jetzt nicht den Atem anhalten bis ich Zeit gefunden habe dort reinzuschauen. Auch kann es gut sein, das ich das nicht reproduziert bekomme weil mir natürlich die passenden Geräte dazu fehlen die nur in deiner Umgebung real zu finden sind.

**Comment by georgekue** [comment]
@jens-maus Alles gut, ich habe ja eine für mich lauffähige Lösung. Aber wenn mein bescheidener Beitrag hier hilft, die Software zu verbessern und vielleicht an dieser Ecke NOCH stabiler zu machen, wird es mich freuen.
