### ISSUE TITLE
HMW-LC-Dim1L-DR Dimmaktor: Aktueller Schaltzustand wird verzögert angezeigt/nachkorrigiert

### ISSUE THREAD

**Issue by mbhomie007** [jens-maus/RaspberryMatic#1513]
### Describe the issue you are experiencing

Bei der Snapshot Version 3.61.4.20211108 wird der Schaltzustand erst nach Aufbau der Seite korrekt angezeigt. Siehe Screencast. 

Gerät: HM-Wired: HMW-LC-Dim1L-DR Dimmaktor

Mit der letzten Stable Version 3.59.6.20211009 tritt das Problem nicht auf.

### Describe the behavior you expected

Zustand wird sofort beim Klick auf das Gerät korrekt anzeigt. 

### Steps to reproduce the issue

1. Auf "Status und Bedienung" - > "Geräte" klicken
2. Gerät auswählen 

### What is the version this bug report is based on?

Snapshot RaspberryMatic-3.61.4.20211108

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
No Log
```

### Additional information

![2021-11-09-at-15-30-30](https://user-images.githubusercontent.com/64688879/141009196-89dcc46c-d7a5-4174-b591-d7be02d98230.gif)

**Comment by mbhomie007** [comment]
Bin der aktuellen Version 3.61.5.20211113 tritt das Problem leider weiterhin auf.

**Comment by mbhomie007** [comment]
Auch mit der aktuellsten Version 3.61.7.20220115 tritt das Problem weiterhin auf und kann reproduziert werden.

**Comment by mbhomie007** [comment]
Problem ist noch präsent.

**Comment by mbhomie007** [comment]
Problem besteht weiterhin.

**Comment by mbhomie007** [comment]
Problem besteht weiterhin.

**Comment by mbhomie007** [comment]
Problem besteht weiterhin, auch mit der aktuellen Stable 3.67.10.20230114.
Das Problem erhielt Einzug mit der 3.61.4

Kann das jemand bestätigen?

**Comment by mbhomie007** [comment]
Problem besteht auch in der 3.69.6.20230407

Siehe Screencast oben.

**Comment by mbhomie007** [comment]
Problem still present.

**Comment by mbhomie007** [comment]
Hallo @jens-maus @Baxxy13 @jp112sdl 
ich würde gerne diesen älteren Bug weiter auf die Schliche gehen.
Könnt ihr mir sagen, wie ich das machen kann? In der Chrome Browserkonsole ist mir kein Fehler aufgefallen.
Die Version 3.59.6.20211009 war die letzte Version, wo der Bug noch nicht auftrat.
Alle nachfolgenden Versionen enthalten den Bug.

![image](https://github.com/jens-maus/RaspberryMatic/assets/64688879/75f6d85c-d16c-45fa-8b78-6c402516b315)

**Comment by jens-maus** [comment]
Also dieser "Fehler" hier mit dem `fieldtest-ccu-update` kommt daher das du fälschlicherweise gedacht hast es wäre eine gute Idee unter "Systemsteuerung -> Allgemeine Einstellungen -> Feld-Tester" dort die Funktion "Zeige unveröffentlichte Geräte-Fw." einzuschalten. Das ist aber nur explizit dafür freigeschaltene Kunden von eQ3 vorbehalten. Ergo abschalten und dieser Fehler verschwindet wieder.

Und er hat sicherlich nichts mit dem Problem hier bzgl. `HMW-LC-Dim1L-DR` zu tun. 

Diesbzgl. kann ich dir leider auch nicht weiterhelfen da ich schon nicht verstehe was genau das problem sein soll. Dein Screencast zeigt nur das nach aufbau der Seite der Status von "Ein" zu "Aus" springt. Wie es allerdings sein sollte zeigst du nicht. Was genau soll jetzt der korrekt status sein?

**Comment by mbhomie007** [comment]
Danke @jens-maus für die schnelle Antwort.

Das der Fehler nichts mit dem Bug zu tun hat, dachte ich mir schon. Danke für deine Erklärung.

Es geht darum, dass der Dimmer AUS ist und wenn man die Geräteseite aufruft, der Schaltzustand als EIN angezeigt wird.
Also der aktuelle Zustand wird nicht korrekt angezeigt. 
Wartet man nun 1 bis 2 Sekunden springt plötzlich der Schaltzustand auf AUS, wenn der Dimmer natürlich auch AUS ist.
Die Statusseite braucht also eine gewisse Zeit bis der reale IST-Zustand dargestellt wird.

Mit der Alt-Version war der Schaltzustand sofort nach Aufruf der Geräteseite richtig. So ist es ja auch bei jedem anderen Gerät.

**Comment by jens-maus** [comment]
> Es geht darum, dass der Dimmer AUS ist und wenn man die Geräteseite aufruft, der Schaltzustand als EIN angezeigt wird. Also der aktuelle Zustand wird nicht korrekt angezeigt. Wartet man nun 1 bis 2 Sekunden springt plötzlich der Schaltzustand auf AUS, wenn der Dimmer natürlich auch AUS ist. Die Statusseite braucht also eine gewisse Zeit bis der reale IST-Zustand dargestellt wird.

Na dann geht doch prinzipiell alles, nur eben etwas zeitversetzt, richtig? Unschön vielleicht, aber nicht tödlich würde ich sagen. Und da die CCU/RaspberryMatic WebUI ohnehin eher eine Konfigurationsoberfläche und keine Steueroberfläche ist halte ich dies in der Tat für verschmerzbar.

> Mit der Alt-Version war der Schaltzustand sofort nach Aufruf der Geräteseite richtig. So ist es ja auch bei jedem anderen Gerät.

D.h. nur exakt bei diesem HM-Wired gerät passiert das, bei keinem anderen HM-Wired, bei keinem anderen HM-RF oder ähnlich? Dann wir ein eventl. "Bugfix" bzw. mögliche Verbesserung das der Status unmittelbar und nicht zeitversetzt richtig angezeigt wird umso schwieriger, denn ich hab selbst kein HM-Wired und erst recht nicht diesen HMW-LC-Dim1L-DR Dimmaktor. Auch kommt noch hinzu das du aktuell wohl der einzigste mit diesem Problem bist und hier noch kein anderer HM-Wired Nutzer mit diesem Aktor das Problem bisher anscheinend benannt bzw. reproduziert hat. Vielleicht suchst du lieber erst einmal HM-Wired Leidensgenossen in den einschlägigen Foren und schaust ob diese das Problem reproduzieren können. 

Insofern wüsste ich nicht nun ehrlich gesagt nicht wie man hier also weitermachen sollte. Und es bringt auch nichts wenn du hier dauernd das ticket wieder aufmachst das ursprünglich vor 2 Jahren bereits gemeldet wurde....

**Comment by mbhomie007** [comment]
Ja, es funktioniert alles, nur eben zeitversetzt dargestellt.
Den Bugfix konnte ich bisher nur bei dem HMW-LC-Dim1L-DR Gerät feststellen.
Bei anderen HM-Wired, HM-RF oder HMIP-RF Geräten wird der Zustand ohne Zeitverzögerung sofort richtig dargestellt.

Ich hatte gehofft, das ich hier mit Hilfe den Fehler debuggen kann, aber scheint wohl nicht so einfach zu sein.

Vielen Dank für deine Erläuterungen.

**Comment by jp112sdl** [comment]
@mbhomie007
- Tritt das Problem auch unter "Status und Bedienung" -> "Gewerke" bzw. -> "Räume auf"?

**Comment by mbhomie007** [comment]
@jp112sdl
Ja, gleiches Problem unter GEWERKE und auch unter RÄUME.

Der Schaltzustand steht immer erst auf EIN und springt dann zeitverzögert auf AUS, wenn natürlich auch der Dimmer AUS ist.

**Comment by jp112sdl** [comment]
In den Commits im OCCU von 3.59 -> 3.61 habe ich erstmal nichts gefunden, was das Problem (für mich) auf Anhieb erklärt.

Die WebUI hat ja so nen Hintergrund-Poll alle 3 Sekunden.
Normalerweise werden beim Laden der Seite alle aktuellen Werte verarbeitet und angezeigt.
Hier scheint es so, als würde das erst beim ersten Poll erfolgen.

Öffne mal die Browserkonsole und häng an die URL hinter `?sid=....` noch `&debug=true` an.
In der Konsole siehst du dann ein paar mehr Ausgaben.

Evtl. bekommst du mit, was beim initialen Laden der Seite vs. nach 3 Sekunden unterschiedlich ist.

**Comment by mbhomie007** [comment]
@jp112sdl 
Mehr wird leider nicht angezeigt.

![image](https://github.com/jens-maus/RaspberryMatic/assets/64688879/98b4115f-5a38-494d-bdb5-6e6043cf164b)

**Comment by jp112sdl** [comment]
Bekommst du irgendwie einen Zeitstempel vor die Zeilen?
Oder ist alles ab 
- Alle Filter wurden zurückgesetzt
bis zum nächsten
- Alle Filter wurden zurückgesetzt
ein zusammenhängender Block und zwischen den Blöcken liegen so 2-3 Sekunden?

**Comment by jp112sdl** [comment]
Ich glaub du kannst aufhören zu suchen.
Bei mir ist der selbe Quark bei den BidCos Dimmern.

**Comment by mbhomie007** [comment]
Ab "Alle Filter wurden zurückgesetzt" bis zum nächsten "Alle Filter wurden zurückgesetzt" ist ein Block, ein Aufruf der Seite.
Also im Screenshot hatte ich den anderen Dimmer aufgerufen.

Wie bekomme ich den Zeitstempel hin?
Ganz oben im Screencast siehst du es in live.

**Comment by jens-maus** [comment]
> Ich glaub du kannst aufhören bei dir zu suchen.
> 
> Bei mir ist der selbe Quark bei den BidCos Dimmern.

Echt? Dann müsste ich mal nen alten aus der Kiste auspacken und testen. Oder hast du schon eine Erklärung für dieses Verhalten gefunden?

**Comment by jp112sdl** [comment]
> Oder hast du schon eine Erklärung für dieses Verhalten gefunden?

Nicht so richtig.
Beim initialen Bau der Dimmer-Controls wird jedenfalls der **EIN**-Button mit der Klasse `ControlBtnOn` und **AUS**-Button mit der Klasse `ControlBtnOff` hin gestellt.
https://github.com/eq-3/occu/blob/master/WebUI/www/rega/esp/controls/dimmer.fn#L68-L69

Was ich noch nicht gefunden habe ist die Methode, die dann im Nachgang aufgrund des tatsächlichen Zustands den beiden Elementen die Klassen korrekt zuweist.
Also bei ausgeschaltetem Dimmer dem **EIN**-Button die Klasse `ControlBtnOff` und **AUS**-Button die Klasse `ControlBtnOn`.
Muss irgendwo über die `webui.js` laufen.

Meine Überlegung wäre jedoch, schon direkt in der `dimmer.fn` die Klassen schon beim initialen Anzeigen richtig zuzuweisen.
Der Dimmer-Level ist ja bekannt (https://github.com/eq-3/occu/blob/9d76163c05c88210762f865682f23badf0333a6d/WebUI/www/rega/esp/controls/dimmer.fn#L21)

So könnte es schematisch evtl. aussehen:

```
string BtnOnState="On";
string BtnOffState="Off";
if (oLevel.Value() == 0) {
  BtnOnState="Off";
  BtnOffState="On";
}
            WriteLine("<tr><td><div id='"#chnId#"On'  class='ControlBtn"#BtnOnState#" CLASS02545 j_translate'>${actionStatusControlLblOn}</div></td></tr>");
            WriteLine("<tr><td><div id='"#chnId#"Off' class='ControlBtn"#BtnOffState#" CLASS02545 j_translate'>${actionStatusControlLblOff}</div></td></tr>");
```

@jens-maus Was meinst du dazu?

**Comment by jp112sdl** [comment]
Die Verzögerung kommt von der [webui.js#L35601-L35609](https://github.com/eq-3/occu/blob/9d76163c05c88210762f865682f23badf0333a6d/WebUI/www/webui/webui.js#L35601-L35609):
```JS
      window.setTimeout(function() {
        if (self.state > 0) {
          ControlBtn.on($(self.id + "On"));
          ControlBtn.off($(self.id + "Off"));
        } else {
          ControlBtn.off($(self.id + "On"));
          ControlBtn.on($(self.id + "Off"));
        }
      },1000);
```

Ohne `setTimeout` (mit `0` statt `1000`) passt die Anzeige der EIN-/AUS-Buttons sofort.

**Comment by jp112sdl** [comment]
P.S.: Ich habe jetzt noch die `dimmer.fn` und die Sektion der Klasse `iseButtonsDimmer` (innerhalb der `webui.js`) zwischen den OCCU Version 3.61.7 und 3.59.6 verglichen. Ich konnte keinen Unterschied feststellen.

Von daher kann ich mir nicht erklären, warum das Verhalten bis zur 3.59.6 scheinbar nicht da gewesen sein soll.

Das Timeout von 1000 war auch schon in der 3.59.6 so drin.

**Comment by jens-maus** [comment]
Danke @jp112sdl das du hier wieder richtig unterwegs war. Bleiben also nur zwei Fragen:

1. Warum 1s? Schätze das soll vmtl irgendwelche Verzögerungen in der Anzeige des korrekten states ausbügeln weil vllt der Dimmer oder der rfd oder so ne weile braucht? 
2. geht es denn auch ganz ohne timeout?
3. wer macht den webui Patch dazu? 😜

**Comment by jp112sdl** [comment]
> weil vllt der Dimmer oder der rfd oder so ne weile braucht?

Hmm... wird die Seite nicht synchron geladen, so dass ein Schnittstellen-Hänger auch zu einem Warten beim Seitenaufbau führt?
An der Stelle, wo das Javascript in den Dimmer-Control eingepflanzt wird (https://github.com/eq-3/occu/blob/master/WebUI/www/rega/esp/controls/dimmer.fn#L116-L121C7), ist die Schnittstellenabfrage eigentlich abgeschlossen.
_Zumal `iState`,das den Level repräsentiert, auch als Zahl in der Textbox von vornherein auch korrekt dargestellt wird._

> geht es denn auch ganz ohne timeout?

Bei mir zumindest ja. Habe aber nur einen `HM-LC-Dim1TPBU-FM` und einen `HM-LC-Dim1T-FM`.

> wer macht den webui Patch dazu? 😜

Immer der, der fragt. 
Ich kann einen bauen. Würde dann aber, um die Änderung ggü dem OCCU so klein wie möglich zu halten, die `setTimeout` Funktion drin lassen und nur dessen Timeout-Wert auf `0` setzen.

**Comment by jens-maus** [comment]
Ok, hab den PR mal integriert. Dann kann  @mbhomie007 das morgen am besten einfach mit dem nächsten nightly snapshot mal testen und zurückmelden ob das Problem damit wirklich gefixt ist.

**Comment by jp112sdl** [comment]
Jup, wird wohl so das beste sein 👍

**Comment by mbhomie007** [comment]
Das hört sich vielversprechend an. 😁
Ich werde den Nightly Snapshot nachher testen und hier eine Rückmeldung geben.

**Comment by mbhomie007** [comment]
Hallo @jens-maus @jp112sdl 
erstmal vielen Dank für das Angehen des Problems. 💯 

Nach Aufruf der Seite wird nun der Status ohne Verzögerung richtig dargestellt. Top!

Allerdings gibt es ein Problem, wenn ich den Dimmer per Web-UI ein- oder ausschalte.
Die Schaltzustände passen nicht mehr mit dem tatsächlichen/Ist-Zustand zusammen. 
Außerdem passt der Slider auch nicht mehr zum Schaltzustand.
Wenn ich die Seite refreshe passt wieder alles.


![image](https://github.com/jens-maus/RaspberryMatic/assets/64688879/15cdee13-9aa1-4f58-b179-f098d149bb2a)

![image](https://github.com/jens-maus/RaspberryMatic/assets/64688879/1f4593e5-3cae-45b1-8dcc-b9f8c4d9e885)

**Comment by jp112sdl** [comment]
>Ausser natürlich @jp112sdl hat noch irgendeine Idee ob man dieses (neue) Problem auch noch irgendwie umgehen/fixen kann?!? 

Wir lassen das Timeout so drin und setzen die Style-Klasse passend zum LEVEL ( > 0 = EIN sonst AUS)  wie hier vorgeschlagen: https://github.com/jens-maus/RaspberryMatic/issues/1513#issuecomment-1813120200

Dazu komme ich heute aber wahrscheinlich nicht mehr

**Comment by jens-maus** [comment]
Oder das timeout auf nur 200-300ms stellen?

**Comment by jp112sdl** [comment]
> Außerdem passt der Slider auch nicht mehr zum Schaltzustand.

Daran wurde ja nun gar nichts verändert. :/

> Allerdings gibt es ein Problem, wenn ich den Dimmer per Web-UI ein- oder ausschalte.
Die Schaltzustände passen nicht mehr mit dem tatsächlichen/Ist-Zustand zusammen.

Kann es grad nicht nachvollziehen. Hab es bei mir fix mal angeschaut, da ist alles schick.

**Comment by jens-maus** [comment]
Du hast noch nicht beantwortet ob es mit der vorherigen Version nicht auch schon so war..

**Comment by mbhomie007** [comment]
> Du hast noch nicht beantwortet ob es mit der vorherigen Version nicht auch schon so war..

Sorry, das kann ich nicht mehr genau sagen. Dort ist mir immer nur die Statusverzögerung aufgefallen.

**Comment by jens-maus** [comment]
Dann geh zurück und teste es.

**Comment by jp112sdl** [comment]
So sieht es bei mir aus

![](http://g.recordit.co/Fe3PcU7eqT.gif)

**Comment by mbhomie007** [comment]
> Dann geh zurück und teste es.

Also mit der vorherigen Version tritt das Problem nicht auf.

**Comment by jens-maus** [comment]
Hmm und wenn du einen kleinen timeout von 200ms Sekunden da reinbaust?

**Comment by jp112sdl** [comment]
Der Unterschied zw. BidCos und Wired wird sein, dass BidCos viel träger von der Kommunikation her ist.
Abgesehen davon habe ich auch eine Rampe von 0,5 Sekunden konfiguriert.

> Hmm und wenn du einen kleinen timeout von 200ms Sekunden da reinbaust?

Sieht es wieder "doof" aus. Dauert zwar keine Sekunde mehr, aber die Button-Farbe hüpft trotzdem.

![](http://g.recordit.co/ZrYTxUqXrU.gif)

**Comment by jens-maus** [comment]
Na dann vielleicht beide Buttons standardmäßig ausgeschalten darstellen lassen und dann wird nach X ms nur der jeweilige blau der blau werden soll? Oder eben deine zuerst vorgeschlagene Lösung?

**Comment by jp112sdl** [comment]
Ich versuch mal, die `dimmer.fn` umzubauen.
Ansonsten wäre
> vielleicht beide Buttons standardmäßig ausgeschalten darstellen lassen

auch eine Variante.

**Comment by jens-maus** [comment]
@mbhomie007 Bitte mit der nächsten kommenden nightly snapshot version nochmal testen ob jetzt alles diesbzgl. funktioniert und die neueste Anpassung von @jp112sdl den finalen Erfolg bringen bzgl. deines Dimmers.

**Comment by mbhomie007** [comment]
Heute werde ich nicht mehr zum Testen kommen. Ich melde mich morgen.

**Comment by mbhomie007** [comment]
@jens-maus @jp112sdl 
Habe nun die Nightly Version 3.73.9.20231119-fe2ab7-rpi3 installiert und getestet.

Alle Verzögerungen und Inkonsistenzen sind nun behoben. Läuft wie geschmiert! 
Vielen Dank für den Fix! 1A! 🥇 💯
