### ISSUE TITLE
Release: 3.59.6.20211009 - Watch-Dog: 404 Not Found

### ISSUE THREAD

**Issue by JungeG** [jens-maus/RaspberryMatic#1514]
### Describe the issue you are experiencing

Hi!
When I try to open watch-dog configuration: I get 404 Not Found. The page to open: **<ip raspberrymatic>/addons/hm-watchdog?sid=@xxxxxxxxxx@.**
All other services (CUxD, Update) can be opened.
Thanks for any hint.
Georg 

### Describe the behavior you expected

Page **<ip raspberrymatic>/addons/hm-watchdog**  should open

### Steps to reproduce the issue

1.
2.
3.
...

### What is the version this bug report is based on?

3.59.6.20211009

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
nothing
```

**Comment by MichaelN0815** [comment]
Siehe https://github.com/homematic-community/hm-watchdog 
Demzufolge ist das Addon auf einer RM nicht empfohlen. IMHO bringt RM diese Funktionalität selber mit.

**Comment by JungeG** [comment]
Danke für die schnelle Antwort:
aber es ist das "interne" Watchdog.
Ich möchte es gerne konfigurieren.

**Comment by jens-maus** [comment]
As @MichaelN0815 pointed out: your bug ticket is referencing the old and obsolete hm-watchdog which must not be used on RaspberryMatic anymore. If you want to have more control over the internal monit-based watchdog see here: https://github.com/jens-maus/RaspberryMatic/wiki/Experten-Features#monit-watchdog-weboberfl%C3%A4che

**Comment by JungeG** [comment]
Thanks Jens,
this link was unknown to me.
Short additional question:
How get I rid of the button (Watchdog) in System Control of the
[watchdog.pdf](https://github.com/jens-maus/RaspberryMatic/files/7511407/watchdog.pdf)
 Raspberrymatic - to avoid future problems.
Thanks Georg

**Comment by jens-maus** [comment]
Why the heck are you putting a pdf here? A screenshot is a jpg or png which you can directly drag&drop here.

Nevertheless: Removing the hm-watchdog addon will remove that button. If not, go to a discussion fora and discuss your problem there. This is not a discussion board here but a bug/issue tracker for development on RaspberryMatic and your problem is not related to that.
