### ISSUE TITLE
Raspberrymatic Home Assistant Addon upgrade fails

### ISSUE THREAD

**Issue by dm82m** [jens-maus/RaspberryMatic#1517]
### Describe the issue you are experiencing

On Home Assistant OS I wanted to upgrade to the newest released version but its failing with this error:

`Can't install ghcr.io/jens-maus/raspberrymatic:3.61.5.20211113: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=3.61.5.20211113&fromImage=ghcr.io%2Fjens-maus%2Fraspberrymatic: Internal Server Error ("manifest unknown")`

Doesn't look like a local problem.

### Describe the behavior you expected

The upgrade runs without an error.

### Steps to reproduce the issue

Having the last version installed and trying to install the newest version.

### What is the version this bug report is based on?

3.59.6.20211009

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
I am using the add-on in Home Assistant OS.
```

**Comment by jens-maus** [comment]
You are too early! This build is current (today!) in the making. So please wait until later the day until this release has been published!

**Comment by dm82m** [comment]
hehe, I am just new on home assistant OS with raspberrymatic. was on home assistant venv and pivccu. thought if home assistant OS is showing me an upgrade then there is one and I can update.

no worries, will try it in the evening.

thanks for your work jens, heavily appreciated!
