### ISSUE TITLE
WebUI: Beschriftung für Reedkontakte fehlt

### ISSUE THREAD

**Issue by widmann-it** [jens-maus/RaspberryMatic#152]
Hallo, 
die Beschriftung fehlt ;-) 
![grafik](https://user-images.githubusercontent.com/13391650/30076819-772678f8-927a-11e7-87e6-cbfd40dc12e1.png)

**Comment by jens-maus** [comment]
Das sollte auch in einer CCU2 bzw. OCCU mit gleicher Firmware so sein und ist somit kein RaspberryMatic spezifisches Problem.

**Comment by widmann-it** [comment]
Das kann ich mangels CCU2 nicht nachprüfen. Mir ist es beim Raspimatic aufgefallen ;-) Daherr habe ich es hier gemeldet ;-)

**Comment by HMside** [comment]
Hier fehlen die entsprechenden Einträge für die Übersetzung in der /www/webui/webui.js
`elvST['SHUTTER_CONTACT|EVENT_DELAYTIME'] = '${stringTableShutterContactEventDelayTime}';`
Sowie in der /www/config/stringtabel_de.txt
`SHUTTER_CONTACT|EVENT_DELAYTIME	${stringTableShutterContactEventDelayTime}`
Da diese auch auf der CCU fehlt, habe ich eQ-3 entsprechend informiert.

**Comment by jens-maus** [comment]
Danke für den Hinweis. IMHO sollten wir aber trotzdem entsprechende RaspberryMatic patches dafür aufnehmen bis eQ3 das Problem in OCCU selbst dann beseitigt hat. Auch schicke ich regelmäßig an eQ3 die Patches für einen entsprechenden Review und dann integrieren die gewisse patches davon..

**Comment by jp112sdl** [comment]
Mit der 2.31.16 ist es immer noch nicht bis zu Ende gedacht...
Die eigentliche Übersetzung in der `/www/webui/js/lang/de/translate.lang.stringtable.js` fehlt noch.

Oder der Vorschlag von @HMside wird von `${stringTableShutterContactEventDelayTime}` in `${stringTableEventDelayTime}` geändert, was eine zusätzliche Übersetzung sparen würde.
Denn ich vermute mal, dass beide Fälle mit "Meldeverzögerung" übersetzt werden sollten?

<img width="685" alt="bildschirmfoto 2018-07-22 um 12 13 54" src="https://user-images.githubusercontent.com/18190139/43044701-ea3ffcf6-8dab-11e8-9c2b-2ade9d02e568.png">

**Comment by jp112sdl** [comment]
Da die Übersetzung in FW 2.31.16 auf der CCU2 korrekt angezeigt wird, ist der Patch [0030](https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0030-WebUI-Fix-Shutter-contact-translation.patch) wohl obsolet und darf nicht mehr angewendet werden.

**Comment by HMside** [comment]
Korrekt, eQ-3 hat das gefixt, wodurch mein Patch nicht mehr benötigt wird.

**Comment by jp112sdl** [comment]
Fehler besteht auch in der Version 3.37.8.20180922 noch...

**Comment by jens-maus** [comment]
Ok, ich kann selbst bestätigen das das Problem anscheinend mit der 3.37.8 Firmware wieder existent ist. Müssen wir den Patch also wieder reaktivieren.

**Comment by jp112sdl** [comment]
Nicht ganz. 
Der Patch kam doch ursprünglich, weil `SHUTTER_CONTACT|EVENT_DELAYTIME` angezeigt wurde.

Dass dort `${stringTableShutterContactEventDelayTime}` steht, ist bereits seit FW 2.31 in allen Folge-FW kontinuierlich enthalten.

Da der Fehler auf der CCU2/3 nicht auftritt, denke ich, dass hier immer noch der Patch [0030-WebUI-Fix-Shutter-contact-translation](https://github.com/jens-maus/RaspberryMatic/tree/master/buildroot-external/patches/occu/0030-WebUI-Fix-Shutter-contact-translation/occu/WebUI/www) erfolgt, der nicht mehr erfolgen darf!?

**Comment by jens-maus** [comment]
@jp112sdl Danke Jerome. Das habe ich in der Tat ganz übersehen. Der Patch ist nun Geschichte und in der nächsten Version sollte das Problem Geschichte sein.
