### ISSUE TITLE
Systeminterne Programme werden über Geräte in WebUI nicht angezeigt

### ISSUE THREAD

**Issue by TomItNet** [jens-maus/RaspberryMatic#1520]
### Describe the issue you are experiencing

Ich verwende Neo. Alle Kommunikation mit Neo geschieht über Systemvariablen. Da Neo die Programme selbst nicht sehen soll, sind sämtliche Programme als „Systemintern“ gekennzeichnet.
Dies funktioniert auch gut, hat aber den nachfolgend beschriebenen Nachteil:
Die als „Systemintern“ gekennzeichneten Programme können in der WebUI über „Programme und Verknüpfungen“ --> „<|>Programme & Zentralenverknüpfungen“ mit dem Button „Systeminterne Programme einblenden“ angezeigt werden. Allerdings wird diese Auswahl nicht gespeichert.
Wenn auf der Seite „Einstellungen“ --> „Geräte“ bei einem Gerät, welches auch in Programmen verwendet wird der Button „Programme“ geklickt wird, so wird auf die Seite der Programme gewechselt, jedoch werden keine Programme angezeigt, obwohl zuvor „Systeminterne Programme anzeigen“ gewählt wurde. Diese Einstellung ist  nun nicht mehr da und man kann erneut auf „Systeminterne Programme anzeigen“ klicken, was allerdings dazu führt, dass wieder alle Programme angezeigt werden und nicht jene, in denen das zuvor gewählte Gerät verwendet wird.
Dieses Verhalten scheint nicht Browserabhängig zu sein, Jedenfalls verhält dies sich unter Firefox und MS Edge identisch.

### Describe the behavior you expected

Die Auswahl „Systeminterne Programme anzeigen“ sollte für die Session gespeichert werden bzw. durch die Auswahl „Programme“ auf einem Gerät nicht zurückgesetzt werden, sodass es möglich wird, die systeminterne Programme, die ein bestimmtes Gerät verwendet, anzuzeigen.

### Steps to reproduce the issue

1.	Ein Gerät muss verfügbar sein.
2.	Dieses Gerät muss in einem Programm verwendet werden, welches als „Systemintern“ gekennzeichnet ist.
3.	Unter „Programme und Verknüpfungen“ --> „<|>Programme & Zentralenverknüpfungen“ sollte der Button „Systeminterne Programme einblenden“ geklickt worden sein, sodass der Button nun „Systeminterne Programme ausblenden“ zeigt.
4.	Den Butten „Programme“ auf der Geräteseite für das entsprechende Gerät klicken.
5.	Das zuvor erstellte systeminterne Programm wird nicht angezeigt (was es jedoch sollte)

Dafür steht der Button unten wieder auf „Systeminterne Programme einblenden“ was nicht der Fall sein sollte. Er sollte weiterhin auf „Systeminterne Programme ausblenden“ stehen und die Programme (auch systeminternen) angezeigt werden, die das Gerät verwenden.

### What is the version this bug report is based on?

3.61.5.20211113

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
-none- only WebUI
```

**Comment by Baxxy13** [comment]
Ist mir in der Tat auch schon ab und zu aufgestoßen.
Idealerweise würde bei...


> 4\. Den Butten „Programme“ auf der Geräteseite für das entsprechende Gerät klicken.

...dann automatisch der Filter auf "systeminterne Programme einblenden" gesetzt.
