### ISSUE TITLE
WebUI-Filtertexte werden falsch übernommen

### ISSUE THREAD

**Issue by TomItNet** [jens-maus/RaspberryMatic#1521]
### Describe the issue you are experiencing

Wenn in einem Programm Systemvariablen verwendet werden, diese über den Dialog „Programme – Systemvariablenauswahl“ gewählt werden und dafür in diesem Dialog ein Filter verwendet wird, so befindet der Filtereintrag nach speichern des Programms (oder abbrechen) im Filter der Programme.
Dies ist besonders dann hinderlich, wenn es relativ viele Programme gibt und die zur Bearbeitung ausgesuchten zuvor mittels Filter bestimmt wurden, jedoch dieser Filtereintrag nun durch den Eintrag im Filter der Systemvariablen „überschrieben“ wurde.
Es besteht die Vermutung dass der Filtertext nur einmal gehalten wird, wobei es sich hier um unterschiedliche Variablen handeln müsste.

### Describe the behavior you expected

Die Filtertexte des Systemvariablenauswahldialog und der Programmansicht sollten unabhängig voneinander ihre zuletzt eingestellten Filtertexte behalten.

### Steps to reproduce the issue

1.	Systemvariable anlegen
2.	Programm anlegen, Namen vergeben und speichern.
3.	In der Liste der Programme Filter so setzen, dass das neue Programm angezeigt wird.
4.	Programm öffnen und Systemvariable hinzufügen und auf „Systemvariablenauswahl“ klicken.
5.	Hier nun einen Filter setzen um die Systemvariable zu wählen (sollte natürlich ein anderer Text sein als zuvor bei den Programmen).
6.	Systemvariable auswählen und Programm speichern.
7.	Der Filter in den Programmen enthält nun den Filtertext der für Systemvariablen eingetragen wurde, anstelle des zuvor für Programme vergebenen Filtertextes.

### What is the version this bug report is based on?

3.61.5.20211113

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
-none- only WebUI behaviour
```

**Comment by jp112sdl** [comment]
duplicate of #953
