### ISSUE TITLE
WebUI-Auswahldialog „Programme – Systemvariablenauswahl“ zeigt systeminterne Systemvariablen nicht an

### ISSUE THREAD

**Issue by TomItNet** [jens-maus/RaspberryMatic#1522]
### Describe the issue you are experiencing

Wenn in einem Programm Systemvariablen verwendet werden sollen und diese über den Dialog „Programme – Systemvariablenauswahl“ gewählt werden sollen, so werden systeminterne Systemvariablen nicht angezeigt.

### Describe the behavior you expected

Der Dialog „Programme – Systemvariablenauswahl“ sollte auch systeminterne Systemvariablen anzeigen oder eine Möglichkeit besitzen diese einzublenden.

### Steps to reproduce the issue

1.	Systemvariable anlegen
2.	Systemvariable als „systemintern“ kennzeichnen
3.	Programm anlegen, Systemvariable hinzufügen und mit „Systemvariablenauswahl“ den Dialog „Programme – Systemvariablenauswahl“ öffnen.
4.	Die zuvor angelegte Systemvariable wird nicht angezeigt.

### What is the version this bug report is based on?

3.61.5.20211113

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
-none- only WebUI
```

**Comment by Baxxy13** [comment]
Meiner Meinung nach ist das absichtlich so implementiert und auch ok.
Systemintern heißt für mich "von Userinteraktionen fernhalten".  
Du kannst sie doch erst in Programme implementieren und zum Schluss auf intern setzen.

**Comment by TomItNet** [comment]
Wenn ich zum Zeitpunkt der Programmierung die Programme und Systemvariablen noch nicht als „Systemintern“ gekennzeichnet habe, diese getestet habe und anschließend die Status auf „Systemintern“ gesetzt habe, kann es dennoch vorkommen, dass ich mir einen Überblick verschaffen möchte, in welchen Programmen eine bestimmte Systemvariable verwendet wird. Dies entspricht ja auch der ursprünglichen Funktion des Buttons „Programme“ bei der Systemvariablen.
Es wäre auch nicht besonders sinnvoll, wenn ich, um herauszufinden, in welchen Programmen eine bestimmte Systemvariable verwendet wird, zunächst in meinen geschätzt 100 Programmen den Status „Systemintern“ entfernen müsste, um dies dann zu sehen.

**Comment by Baxxy13** [comment]
Wie gesagt, systeminterne SysVars sind nicht dazu vorgesehen in Programmen verwendet zu werden.
Die Option SysVars intern zu machen gab es auch bis vor kurzem nicht. So wie ich mich erinnere wurde das "notgedrungen" eingeführt weil die ganzen neuen Watchdog-Alarm-SysVars intern erzeugt werden. Damit man dann auf diese in Programmen reagieren kann musste eine Option her das zu ermöglichen. Vorher ging das auch nicht, bzw. nur über Umwege interne SysVars in Programmen zu verwenden.
Auch hier wieder der Hinweis (weil der Bezug zu den anderen Tickets ersichtlich ist), deine externe Anwendung sollte die nicht benötigten SysVars ausblenden (können).

Für mich stellt das jedenfalls keinen Bug dar.

**Comment by jens-maus** [comment]
> Für mich stellt das jedenfalls keinen Bug dar.

In der Tat ist das kein Bug als mehr ein "missing Feature".  Trotzdem denke ich es könnte von Vorteil sein auch programme mit als "systemintern" markierten Systemvariablen anlegen zu können. Man könnte natürlich das Systemvariablen-Auswahlfenster der normalen Systemvariablenliste mit hintergrund-unterschied zwischen systemintern vs. non-systemintern übernehmen oder kurzerhand ein Button unten hinbauen ala "systeminterne Variablen einblenden/ausblenden" um den Unterschied zu verdeutlichen. Aber vllt. hat @jp112sdl ja noch ne Meinung dazu?

**Comment by jp112sdl** [comment]
> oder kurzerhand ein Button

Ob das so kurzerhand erledigt ist kann ich grad noch nicht beurteilen

Ansonsten bin ich da zweigeteilter Meinung.

Als WENN-Auswahl halte ich der Verwendung von systeminternen Variablen schon für sinnvoll.
Aber ob man sie im DANN einfach so beschreiben können sollen darf?
Wenn ich da an die ganzen energyCounter-Variablen denke, die von automatisch angelegten internen Programmen beschrieben werden, ...

Birgt auf jeden Fall Gefahrenpotenzial. Andererseits aber auch nur, wenn man sich bewusst ein Programm einrichtet.

**Comment by jens-maus** [comment]
> Birgt auf jeden Fall Gefahrenpotenzial. Andererseits aber auch nur, wenn man sich bewusst ein Programm einrichtet.

Deshalb denke ich eben, das es am besten/sichersten wäre wenn man das eben **nur** über solch einen einblenden/ausblenden Button machen kann und der sich auch bewusst nicht den Status für nächstes mal merkt. Dann muss man da bewusst zwei Aktionen tätigen zur Auswahl einer systeminternen variablen. Und ja, es KANN gefährlich sein, aber man kann auch bei "Skript testen" einfach `system.Exec("rm -rf /usr/local");` ausführen und hat bei weitem mehr negative Effekte zu befürchten ;)

**Comment by jp112sdl** [comment]
> nur über solch einen einblenden/ausblenden Button machen

Schau ich mir morgen mal an

> system.Exec("rm -rf /usr/local");

Grad mal probiert. Stimmt. 😛

**Comment by jens-maus** [comment]
> Hmm, wie wäre es denn wenn wir für Admins die Sichtbarkeit umdrehen?

Programme editieren können doch ohnehin nur Admins. Das wäre sinnfrei. Und nur weil jemand vermeintlich "Admin" ist, heisst das immer noch nicht das er weiss was er da tut ;) Ich bleibe daher dabei. der zusätzlich aufwand den "einblenden/ausblenden" button jedesmal drücken zu müssen ist eben die zusätzlich sicherheit und wer das nicht mag kann sich ja wie @jp112sdl auch das backup-requester wegpatchen oder eben die logik umdrehen. Aber für 99% der leute wird der default mit "ausblenden" und erzwungenem nutzen von "einblenden" gut und praktikabel sein damit man sich eben nicht in die Füße schießst.

**Comment by MichaelN0815** [comment]
Ich weiß nicht, ich sehe den Bedarf überhaupt nciht. Zu 99,9% wil ich die systeminterne SV gar nicht sehen. Und im Zweifel kann ich mir die Variablen doch sichtbar machen, indem ich den Status systeminterne deaktiviere. Wer so tief im System ist, der wird den einen Klick auch schaffen. 

Ich sehe keinen Handlungsbedarf.

**Comment by jp112sdl** [comment]
Stimmt auch wieder. Wozu das Attribut "systemintern", wenn man dann doch überall über einen extra Button ran kommt

**Comment by jp112sdl** [comment]
@jens-maus Hast du diesbezüglich gestern noch was gemacht?

Ich bekomme das eingangs geschilderte Verhalten nicht reproduziert.
Wenn ein Programm anlege mit `WENN Systemzustand [Systemvariablen]` sehe ich im Popup **alle** Variablen. 
Auch die internen.

**Comment by jens-maus** [comment]
Ja, aber auch im DANN sollte es IMHO umgesetzt werden bzw eben mit dem diskutierten einblenden/ausblenden Button.

**Comment by jp112sdl** [comment]
Ich hab den Button mal eingebaut.
2 Probleme (stehen auch im PR #1539) bei denen ich nicht weiterkomme:
- wenn mittels jQuery der Buttontext geändert wird, erscheint statt dem echten Zeilenumbruch die Ausschrift `<br/>` (evtl. ist `.text()` die falsche Methode, aber `innerHTML` geht nicht für `<div>`)
- ein bestehender Filter wird nach dem Toggeln nicht angewendet. Hab es daher erstmal so gebaut, dass beim Klick der Filter zurückgesetzt wird.

**Comment by jens-maus** [comment]
> Ich hab den Button mal eingebaut. 2 Probleme (stehen auch im PR #1539) bei denen ich nicht weiterkomme:
> 
> * wenn mittels jQuery der Buttontext geändert wird, erscheint statt dem echten Zeilenumbruch die Ausschrift `<br/>` (evtl. ist `.text()` die falsche Methode, aber `innerHTML` geht nicht für `<div>`)

Die `<br/>` in den Übersetzungstexten braucht man ohnehin nicht und ist stilistisch auch nicht IMHO i.O. weil man es schon dem Webbrowser überlassen kann den Text umzubrechen und nicht das nicht manuell erzwingen sollte.

> * ein bestehender Filter wird nach dem Toggeln nicht angewendet. Hab es daher erstmal so gebaut, dass beim Klick der Filter zurückgesetzt wird.

Das sollte für den Anfang so erst einmal i.O. sein. Denke so kann man das erst einmal lassen.
