### ISSUE TITLE
Geräte als „systemintern“ kennzeichnen

### ISSUE THREAD

**Issue by TomItNet** [jens-maus/RaspberryMatic#1523]
### Describe the solution you'd like

Nachdem nicht nur Programme, sondern auch Systemvariablen als systemintern gekennzeichnet werden können, wäre es logisch, dass auch Geräte die Kennung „systemintern“ erhalten können.
Dies würde z.B. ermöglichen Geräte für externe (z.B. Neo oder Node-Red) zu verbergen, was wiederum zu erhöhter Kapselung führt und unbeabsichtigte Zugriffe verhindert.
In der Tabelle „Geräte“ gibt es zwar eine Spalte „sichtbar“ (Auge), allerdings lässt sich die Sichtbarkeit weder für Geräte noch für einzelne Kanäle (jedenfalls insoweit ich dies gesehen habe) ändern.
Gewünscht wäre also eine Funktion, um Geräte z.B. für Neo zu verbergen, sodass diese bei einem Import nicht mehr angezeigt werden.

### Describe alternatives you've considered

- keine bekannt -

### Is your feature request related to a problem?

Kapselung

**Comment by Baxxy13** [comment]
Die Sichtbarkeit wirkt sich in der WebUI nur innerhalb Räumen / Gewerken aus. Ist aber eigentlich auch umsonst denn wenn ich da was nicht sehen will füge ich es nicht hinzu. Wie externe Anwendungen den "Sichtbarkeits-Status" auswerten/nutzen weiß ich nicht.

"Systemintern" hat nur noch wenige Auswirkungen an einigen Stellen in der WebUI die ich aber nicht mehr überblicke.
Auch weiß ich auch hier nicht wie externe Anwendungen den "Systemintern-Status" handhaben. 

Setzbar ist der "Systemintern-Status" auch bei Geräten und deren Kanälen. Nur aktuell eben nicht per Klick in der WebUI.
Man könnte sicher ein zusätzliches Kästchen zum anklicken implementieren, aber braucht man das wirklich?
Kann nicht die externe Anwendung das Gerät von sich aus ausblenden?

Du kannst den "Systemintern-Status" auch per Script oder recht komfortabel mit dem SDV von Black (homematic-forum)
setzen.

**Comment by MichaelN0815** [comment]
Meine Meinung : es kann nicht Aufgabe von RaspberryMatic sein die Daten für externe Systeme aufzubereiten. Ich würde das bei deren Programmierern adressieren.

**Comment by TomItNet** [comment]
Ich kenne die System-Interna nicht.
Bisher habe ich angenommen, dass der Status „Systemintern“ gerade für die Kapselung gedacht ist.
NodeRed zeigt Systemvariablen mit dem Status „Systemintern“ nicht an und in Neo werden diese nicht importiert. Weiter werden Programme mit dem Status „Systemintern“ in Neo nicht importiert.
Aufgrund dieses Verhaltens war ich (evtl. fälschlicher Weise) davon ausgegangen, dass der Status „Systemintern“ gerade dafür gedacht sei, Systemvariablen und Programme für Externe Programme zu verbergen.
Aufgrund dieser Annahme wäre es nur logisch gewesen, die für Geräte ebenso tun zu können.
Aus den Antworten habe ich jedoch herausgelesen, dass externe Programme immer alle Systemvariablen, Programme und Geräte sehen können und dann anhand des Status selbst entscheiden, wie diese damit umgehen. Ich hatte „Systemintern“ eher als eine Art „private“ oder „protected“ angesehen.
Aber selbst wenn keine strenge Kapselung vorhanden ist, würde ich die Möglichkeit des Setzens der Eigenschaft „Systemintern“ über die WebUI für Geräte dennoch begrüßen.

**Comment by Baxxy13** [comment]
Die WebUI ist ja "alt". 
Als die "Optionen" Intern und Sichtbar eingeführt wurden hat vermutlich noch niemand an Auswertung durch externe Anwendungen gedacht. Intern sind z.B. alle 0er Kanäle von HM Geräten und die SysVars die für die ganzen Zähler (Energie, Sonne; Regen usw). Halt Sachen die der normale User idealerweise nicht zu Gesicht bekommt und somit auch nicht manipulieren kann.

**Comment by jens-maus** [comment]
> Meine Meinung : es kann nicht Aufgabe von RaspberryMatic sein die Daten für externe Systeme aufzubereiten. Ich würde das bei deren Programmierern adressieren.

Ich sehe das genauso wie meine Vorredner: Es ist nicht Sinn und Zweck die Daten für externe Applikationen aufzubereiten. Diese Filterung sollte alleine auf der Ebene von den externen Applikationen passieren die die HomeMatic Geräte über die öffentlichen Schnittstellen (APIs) von RaspberryMatic/CCU abholen. Ergo sollte man diese Bitte (nach mehr filterfunktionen) an die externe Applikation (NEO) weiterleiten, denn es gibt sicherlich auch anwendungsfälle wo jemand zwar in seinem Neodisplay ein Gerät "hiden" lassen will, dann aber in seiner Smartphone App z.B. sichtbar haben will. Ergo muss IMHO die jeweilige Applikationen diese Funktionalität bringen/leisten und nicht RaspberryMatic bzw. die CCU.
