### ISSUE TITLE
Systeminterne Programme werden über Systemvariablen in WebUI nicht angezeigt

### ISSUE THREAD

**Issue by TomItNet** [jens-maus/RaspberryMatic#1524]
### Describe the issue you are experiencing

Ich verwende Neo. Alle Kommunikation mit Neo geschieht über Systemvariablen. Da Neo die Programme selbst nicht sehen soll, sind sämtliche Programme als „Systemintern“ gekennzeichnet.
Dies funktioniert auch gut, hat aber den nachfolgend beschriebenen Nachteil:
Die als „Systemintern“ gekennzeichneten Programme können in der WebUI über „Programme und Verknüpfungen“ --> „<|>Programme & Zentralenverknüpfungen“ mit dem Button „Systeminterne Programme einblenden“ angezeigt werden. Allerdings wird diese Auswahl nicht gespeichert.
Wenn auf der Seite „Einstellungen“ --> „Systemvariablen“ bei einer Systemvariablen, welche auch in Programmen verwendet wird, der Button „Programme“ geklickt wird, so wird auf die Seite der Programme gewechselt, jedoch werden keine Programme angezeigt, obwohl zuvor „Systeminterne Programme anzeigen“ gewählt wurde. Diese Einstellung ist nun nicht mehr da und man kann erneut auf „Systeminterne Programme anzeigen“ klicken, was allerdings dazu führt, dass wieder alle Programme angezeigt werden und nicht jene, in denen das zuvor gewählte Gerät verwendet wird.
Dieses Verhalten scheint nicht Browserabhängig zu sein, Jedenfalls verhält dies sich unter Firefox und MS Edge identisch.

### Describe the behavior you expected

Die Auswahl „Systeminterne Programme anzeigen“ sollte für die Session gespeichert werden bzw. durch die Auswahl „Programme“ auf einer Systemvariablen nicht zurückgesetzt werden, sodass es möglich wird, die systeminterne Programme, die eine bestimmtes Systemvariable verwendet, anzuzeigen.

### Steps to reproduce the issue

1.	Eine Systemvariable muss verfügbar sein.
2.	Diese Systemvariable muss in einem Programm verwendet werden, welches als „Systemintern“ gekennzeichnet ist.
3.	Unter „Programme und Verknüpfungen“ --> „<|>Programme & Zentralenverknüpfungen“ sollte der Button „Systeminterne Programme einblenden“ geklickt worden sein, sodass der Button nun „Systeminterne Programme ausblenden“ zeigt.
4.	Den Butten „Programme“ auf der Seite der Systemvariablen für die entsprechende Systemvariable klicken.
5.	Das zuvor erstellte systeminterne Programm wird nicht angezeigt (was es jedoch sollte)

Dafür steht der Button unten wieder auf „Systeminterne Programme einblenden“ was nicht der Fall sein sollte. Er sollte weiterhin auf „Systeminterne Programme ausblenden“ stehen und die Programme (auch systeminternen) angezeigt werden, welche die Systemvariable verwenden.

### What is the version this bug report is based on?

3.61.5.20211113

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
-none- only WebUI
```

**Comment by jp112sdl** [comment]
@jens-maus Die ReGa-Methode `DPEnumUsagePrograms()` liefert keine Programm-IDs von internen Programmen. 

https://github.com/eq-3/occu/blob/0d99a074354bcfeceb84168be53f4acc41bb3968/WebUI/www/rega/pages/tabs/admin/systemvars.htm#L250

Ansonsten sind m.E. keine weiteren Anpassungen an der WebUI notwendig

**Comment by Baxxy13** [comment]
Gibt's da eine "bessere" Methode? 
Dürfte dann ja auch für #1520 funktionieren.

**Comment by jp112sdl** [comment]
> Gibt's da eine "bessere" Methode?

Mir ist keine bekannt. 
Aus Kompatibilitätsgründen sollte man an der bestehenden wohl auch nichts ändern und stattdessen eine neue Methode schaffen `DPEnumUsageInternalPrograms()`. 
Dann könnte man beide Teilmengen zusammen mergen.
Oder  `DPEnumUsageInternalPrograms()`, die halt alle IDs enthält.

> Dürfte dann ja auch für #1520 funktionieren.

Ja, davon gehe ich aus
