### ISSUE TITLE
HmIP-MP3P: Es werden seit 3.61.5 nicht mehr als eine mp3 datei nacheinander abgespielt

### ISSUE THREAD

**Issue by je-bor** [jens-maus/RaspberryMatic#1525]
### Describe the issue you are experiencing

ich benutze ccu3 mit RaspberryMatic 
nach update auf 3.61.5.20211113 spielt HmIP-MP3P nicht mehr als eine mp3 datei ab
![2](https://user-images.githubusercontent.com/85819637/141691602-0a018b2a-39db-4911-aaae-ff2c72467f00.PNG)

### Describe the behavior you expected

vor dem update war es aber möglich

![1](https://user-images.githubusercontent.com/85819637/141691621-687c696b-da21-4e06-adb5-7e4f6e60b60e.PNG)

### Steps to reproduce the issue

1.?
2.?
3.?
...

### What is the version this bug report is based on?

3.61.5.20211113

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
nein leider nicht
```

**Comment by MichaelN0815** [comment]
Der Fehler scheint aus der OCCU 3. 61.5 zu stammen. 
Siehe https://homematic-forum.de/forum/viewtopic.php?f=26&t=70620&p=688063#p688047

**Comment by jens-maus** [comment]
@MichaelN0815 Danke für den Hinweis. Hatte auch schon vermutet das das kein RaspberryMatic spezifisches Problem ist/sein kann. Ergo nun flagged als "upstream issue".

**Comment by mbhomie007** [comment]
Sollte nun mit der 3.61.6 behoben sein.

**Comment by je-bor** [comment]
das würde mich sehr erfreuen ;-)

**Comment by jens-maus** [comment]
Das Problem sollte mit der 3.61.6 definitiv behoben sein.

**Comment by je-bor** [comment]
alles gut Jens, das habt ihr gut gemeistert!!!!!!!!!!!!!!!!!!

**Comment by jens-maus** [comment]
In dem Falle was das eQ3 selbst und nicht die Entwickler rund um RaspberryMatic
