### ISSUE TITLE
Berechnung stimmen nicht mehr

### ISSUE THREAD

**Issue by widmann-it** [jens-maus/RaspberryMatic#153]
Seit dem Update auf die Aktuelle Version stimmen die Berechnungen nicht mehr. 
Mit dem Skript möchte ich den Duty Cycle berechnen, das passt auch in der vorletzten Version.

```
dom.GetObject ("CUxD.CUX2801001:1.CMD_SETS").State("echo 'load tclrpc.so; puts [xmlrpc http://127.0.0.1:2001/ listBidcosInterfaces ]'|tclsh | awk '// { printf $10 }'");
dom.GetObject ("CUxD.CUX2801001:1.CMD_QUERY_RET").State(1);
string r = dom.GetObject("CUxD.CUX2801001:1.CMD_RETS").State();
dom.GetObject ("Duty Cycle").State (r.ToFloat());
```

In der aktuellen Version kommt da raus:
![grafik](https://user-images.githubusercontent.com/13391650/30077096-118ba62a-927b-11e7-9775-2745e730c85f.png)

Und im Terminal: 
![grafik](https://user-images.githubusercontent.com/13391650/30077166-463b4e3e-927b-11e7-92f4-8d08452ea130.png)

**Comment by jens-maus** [comment]
Inwiefern soll hier die Berechnung nicht stimmen? 82 ist von 76 jetzt nicht so weit weg und meine Vermutung ist das einfach zwischen den beiden aufrufen sich der DutyCycle verändert hat.

**Comment by widmann-it** [comment]
Die Anzeige bleibt bei 82 egal was passiert ;-( Ferner waren es vor dem Update 82 und nicht 82.000000

**Comment by jens-maus** [comment]
Das er das angeblich nicht aktualisiert schiebe ich jetzt mal auf CUxD oder darauf das die Zeitmodul-Einstellungen deines Programms jetzt nicht richtig funktionieren. Und das du eine Gleitkommazahl erhälst liegt sich an dem .ToFloat() das du nutzt und das besser ein .ToInteger() sein sollte.

Du kannst aber auch mal folgendes Programm verwenden welches seit 2.29.22.20170902 funktionieren sollte:

```
string stdout;
system.Exec("echo 'load tclrpc.so; puts [xmlrpc http://127.0.0.1:2001/ listBidcosInterfaces ]' | tclsh | awk '{ print $10 }'", &stdout);
dom.GetObject(ID_SYSTEM_VARIABLES).Get("Duty Cycle").State(stdout.ToInteger());
```

**Comment by widmann-it** [comment]
Hallo Jens, 
danke für deine Hilfe, mit deinem Skript geht es ;-)
