### ISSUE TITLE
Status und Bedienung: Transparenz bei CUxD Icons fehlt

### ISSUE THREAD

**Issue by jp112sdl** [jens-maus/RaspberryMatic#1531]
### Describe the issue you are experiencing

In Status und Bedienung -> Geräte werden die Geräte-Icons transparent angezeigt
<img width="409" alt="Bildschirmfoto 2021-11-15 um 22 49 47" src="https://user-images.githubusercontent.com/18190139/141858675-0465316a-52c1-4b83-975a-679787f4cea4.png">

Bei CUxD Geräten ist das nicht der Fall:
<img width="419" alt="Bildschirmfoto 2021-11-15 um 22 48 57" src="https://user-images.githubusercontent.com/18190139/141858607-13de3309-b9b7-4bef-b477-8b3761b03175.png">
obwohl die Bildquelle die selbe ist
`/config/img/devices/50/21_hm-rc-p1_thumb.png`

Auffällig ist, dass das CUxD Bild kurz transparent ist, bis alle Kanäle geladen sind. Dann ist die Transparenz weg.

### Describe the behavior you expected

Transparenz bei allen Geräten gleichermaßen 

### Steps to reproduce the issue

1.
2.
3.
...

### What is the version this bug report is based on?

3.61.5.20111113

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
.
```

**Comment by Baxxy13** [comment]
Hmm, kann ich bei all meinen CUxD-Geräten so nicht nachvollziehen.
![RM_CUxD_Transparenz](https://user-images.githubusercontent.com/54898249/141865723-e5ea28af-ddc4-4c71-8126-5ca349a25279.JPG)

**Comment by jp112sdl** [comment]
@Baxxy13 Danke fürs Gegenprüfen.
Hab jetzt mal einen anderen Browser probiert - mit Firefox tritt der Fehler bei mir auch nicht (mehr) auf.

**Comment by jens-maus** [comment]
Nur der komplett halber: Das CSS Statement das hier für die transparentmachung der Bilder verwendung findet ist `mix-blend-mode: multiply`. Laut doku (https://developer.mozilla.org/de/docs/Web/CSS/mix-blend-mode) sollte das ab Firefox 32 integriert/nutzbar sein. Also war das ggf. ein sehr alter Firefox den du da verwendet hast.

**Comment by jp112sdl** [comment]
> ggf. ein sehr alter Firefox

War der neueste Safari ;-) Da sollte dieser Mode ab Version 8 gehen... Aber Safari und WebUI waren noch nie Freunde.
Ich nutze gewöhnlich dafür auch nur den Firefox mit der Option `browser.cache.disk.enable = false` um auch ja keine Artefakte zu laden.

Keine Ahnung, wie ich da gestern Abend mit dem Safari drauf kam. -.-
