### ISSUE TITLE
WebUI Buttons - LAN Gateway - Display 

### ISSUE THREAD

**Issue by friedpa** [jens-maus/RaspberryMatic#1537]
### Describe the issue you are experiencing

Maybe a Browser Issue, if, I will close the Ticket.

Under Section LAN Gateway Configuration the display shows:

![grafik](https://user-images.githubusercontent.com/42890695/142168602-99497118-6bed-49d0-9e49-b0dd353f79ad.png)

When you change the zoom factor in the browser (e.g. Firefox) you are getting side-effects:

![grafik](https://user-images.githubusercontent.com/42890695/142170105-a9ebb241-1625-4c00-91c3-8cdc73a93bc3.png)

e.g. Above: Start Page / Favourits - Bold Message Frames

### Describe the behavior you expected

Text fits in Button, or Button has two lines
No bold lines in message frames

### Steps to reproduce the issue

1.
2.
3.
...

### What is the version this bug report is based on?

 	3.61.5.20211113

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Nope
```

### Additional information

Browser used: Firefox 94.0.1

**Comment by jens-maus** [comment]
First of all: One issue -> One ticket! Don't add several independent things to a single ticket.

Second: The report on the wrapped button text is valid. Will be fixed. The other one is "normal" because there are always limitations when using the browser zooming.
