### ISSUE TITLE
Maintenance channel 0 is no longer showing temperature for HmIP-PCBS since 3.61.5.20211113

### ISSUE THREAD

**Issue by cont1nuity** [jens-maus/RaspberryMatic#1538]
### Describe the issue you are experiencing

Since 3.61.5.20211113 the HmIP-PCBS maintenance channel does no longer show the value for ACTUAL_TEMPERATURE. This value is only available on the maintenance channel for this board. This is mainly a convenience issue, because I was able to track the temperature in a specific room directly this way.

### Describe the behavior you expected

I would expect to be able to show "non-standard" maintenance information, like ACTUAL_TEMPERATURE for the HmIP-PCBS on the maintenance channel.

### Steps to reproduce the issue

1. Add HmIP-PCBS to your CCU
2. Add the PCBS maintenance channel to any view (either favorite or room)
3. Check the view: The maintenance channel omits "non standard" information, such as ACTUAL_TEMPERATURE, which was shown in version 3.59.6.20211009

### What is the version this bug report is based on?

3.61.5.20211113

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
No.
```

### Additional information

After going through PRs, I assume it is related to the view cleanup in #1487.

**Comment by cont1nuity** [comment]
I have implemented a workaround through a variable (which is cleaner), but I still think that it is convenient to be able to see all available information on the maintenance channel.
As I am new to CCU / Raspberrymatic, I might just miss a setting somewhere to configure these views. If so, I'd be glad for any pointers.

**Comment by jens-maus** [comment]
Please provide a screenshot how this was displayed/shown in previous versions.

**Comment by cont1nuity** [comment]
Unfortunately, I don't have any screenshot from before the update.

This is how it looks like now: 
![image](https://user-images.githubusercontent.com/10164755/142193515-e8c8d62f-0157-4674-a85c-1eddbc1076b8.png)
There were three more fields visible, iirc, a total of 8. One of them being the temperature.

The information is still available on the channel:
![image](https://user-images.githubusercontent.com/10164755/142194018-f3df1ec6-cb9a-4f82-bf32-48c212976a53.png)

**Comment by Baxxy13** [comment]
Na dann steuere ich mal vorher (3.59.6.20211019) / nachher (3.61.5.20211113) Screenshots für eine PCBS-BAT bei.
Vorher:
![PCBS-BAT_CH0_bevore](https://user-images.githubusercontent.com/54898249/142206413-9b8a3ce4-3cba-41b6-b8d4-0388a7583d3b.JPG)
Nachher:
![PCBS-BAT_CH0_after](https://user-images.githubusercontent.com/54898249/142206463-17aa6c0a-55e0-461b-ae0c-ad7a476e67bd.JPG)

**Comment by cont1nuity** [comment]
> 
> 
> Na dann steuere ich mal vorher (3.59.6.20211019) / nachher (3.61.5.20211113) Screenshots für eine PCBS-BAT bei. Vorher: ![PCBS-BAT_CH0_bevore](https://user-images.githubusercontent.com/54898249/142206413-9b8a3ce4-3cba-41b6-b8d4-0388a7583d3b.JPG) Nachher: ![PCBS-BAT_CH0_after](https://user-images.githubusercontent.com/54898249/142206463-17aa6c0a-55e0-461b-ae0c-ad7a476e67bd.JPG)

Danke!

**Comment by jens-maus** [comment]
Auch von mir danke, dafür. Vllt. könntet ihr (@Baxxy13) ja mal auf die Suche nach der maximalen Menge an :0 Datenpunkten machen die es so über alle HmIP oder BidCos Geräte verteilt gibt, weil dann könnte man die auch gleich noch mit implementieren/umsetzen/erfassen wenn ich schon Hand anlege ;)

**Comment by cont1nuity** [comment]
Ich kann da leider nicht viel zu beitragen, da ich gerade erst einsteige und nur wenige Geräte habe.
Der HmIP-PCBS aus meinem Screenshot [oben](https://github.com/jens-maus/RaspberryMatic/issues/1538#issuecomment-971495500) ist mit 12 Datenpunkten bei mir der umfangreichste. Das deckt sich mit dem PCBS-BAT.

**Comment by Baxxy13** [comment]
Hab jetzt mal meinen IP-Fuhrpark durchgeschaut. Soweit ich gesehen habe sind 12 angezeigte DP's das Maximum. Die PCBS-BAT hat eigentlich 13, "INSTALL_TEST" wird aber nicht angezeigt. Kann ich auch nichts mit anfangen.

Interessant sind die DRSIx. Die haben 18 DP's. Die Anzeige sieht aber (alte Version) so aus:
 ![DRSIx_Kanal_0](https://user-images.githubusercontent.com/54898249/142228011-27455356-5029-4a4a-bbcb-109a9b1966e7.JPG)
Da dürften gerne noch ein paar mehr angezeigt werden. ;-)

**Comment by cont1nuity** [comment]
Danke!

**Comment by Baxxy13** [comment]
Sieht ganz gut aus.
Einzig RSSI Partner und RSSI Gerät fehlen nun bei allen Geräten.
![RM_Kanal_0_Datenpunkte](https://user-images.githubusercontent.com/54898249/143479216-f5ea9fe6-3673-4019-b939-73554bc26c3c.JPG)

**Comment by Baxxy13** [comment]
[Fehler gefunden](https://github.com/jens-maus/RaspberryMatic/commit/45d3eb0047f8a300245aee25c096bfa8d878323c#r60884597)
