### ISSUE TITLE
Invalid HTML in DutyCycle display on start page

### ISSUE THREAD

**Issue by ptweety** [jens-maus/RaspberryMatic#1540]
### Describe the issue you are experiencing

With 0057-WebUI-ImprovedDutyCycleDisplay we introduce an improved display of duty cycles and carrier sense levels

There is a minor bug in startpage.htm in these and similar lines:

https://github.com/jens-maus/RaspberryMatic/blob/cb5c14c8bff0bf733b63d0593474070861096665/buildroot-external/patches/occu/0057-WebUI-ImprovedDutyCycleDisplay/occu/WebUI/www/rega/pages/tabs/startpage.htm#L269

It should put a `>` after the `style`

```
<td id="dutyCycleAddr0" style="vertical-align: top;text-align: left;"></td>
```

### Describe the behavior you expected

n/a

### Steps to reproduce the issue

Have a look at the result with your browsers developer tools. E.g.:

`<td id="dutyCycleAddr1" style="vertical-align: top;text-align: left;" <="" td="">`

### What is the version this bug report is based on?

3.61.5.20211113

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
n/a
```

**Comment by ptweety** [comment]
Menno. Ich war auch gerade am pull request.

**Comment by jens-maus** [comment]
Oh, tschuldigung :) Hoffe du hast dir nicht zuviel arbeit schon gemacht.
