### ISSUE TITLE
Watchdog Alarm bei fehlendem Internet Access zu überempfindlich

### ISSUE THREAD

**Issue by alexhass** [jens-maus/RaspberryMatic#1545]
### Describe the issue you are experiencing

Der Watchdog ist aus meiner Sicht aktuell sehr überempfindlich. Nur weil einmal der Internet-Zugriff fehlschlägt sollte nicht direkt eine Alarmmeldung kommen. Der Check kann durchaus mal in die Zeit eines DSL-Zwangsdisconnect alle 24h fallen oder wenn man gerade ein Firmware Update seiner Fritzbox durchführt. Da sollte man nicht direkt alarmiert werden.

### Describe the behavior you expected

Grundsätzlich finde ich den Alarm sinnvoll, nur sollte man den Internet Access vielleicht erst 3 mal über 3min oder 15min versuchen, bevor man einen Alarm raushaut.

### Steps to reproduce the issue

1. Internet Access trennen während ein Check stattfindet.

### What is the version this bug report is based on?

3.61.5.20211113

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Habe eine CCU3
```

**Comment by jens-maus** [comment]
Schon jetzt kann dieser Internet access check individuell deaktiviert werden (via WebUI -> Erweitere Einstellungen oder via Anlegen der Datei `/etc/config/internetCheckDisabled`).

Des Weiteren ist die gewünschte Verzögerung der Alarmierung bereits jetzt umgesetzt, wie man hier erkennen kann:

https://github.com/jens-maus/RaspberryMatic/blob/4258c3f17ee2fea45810b82ed7cfda7208e8f857/buildroot-external/overlay/base-raspmatic/etc/monitrc#L443-L453

Dort sieht man, dass erst nach 24 "cycles" (1 cycle ist 13 sekunden), d.h. nach > ~5 Minuten eine Alarmierung ausgelöst wird. Und im RaspberryMatic Forum wurden diese max. ~5 Minuten bisher als gutes Threshold angesehen für eine Benachrichtigung das der Internet-Zugriff ausgefallen war/ist. Und nein, eine Konfigurationsmöglichkeit dieses Wertes ist nicht vorgesehen und momentan auch technisch nicht möglich.

**Comment by alexhass** [comment]
Ok, gut dass ihr das Thema doch schon mal bedacht hattet. Jetzt weiß ich auch wo es im Code steht. 

Ich habe bisher leider die persönliche Erfahrung gemacht, dass 1 von 7 Alarmen ein echter Alarm war - halt "einer" bei dem wirklich mal DSL kaputt war. Ansonsten leider nur "Fehlalarme". Abschalten will ich das Feature aber eigentlich auch nicht.

Heute Nacht wurde meine Fritzbox 7590 automatisch von v7.28 nach v7.29 aktualisiert. Leider kann ich nicht sehen wann sie runter gefahren ist, aber das Log sagt, dass sie um 4:25:27 wieder hoch kam und einen ftpuser ohne Passwort deaktiviert hat und die Internet Connection um 4:29:24 erfolgreich hergestellt wurde. Davor war DSL-Sync und anderes Zeugs. Zudem hat sie vor 4:25:27 auch noch das Firmware Update installiert...

Ich habe zwar keine Statistiken über durchschnittliche Firmwareupdate/Bootzeiten, aber wenn es schon über 4min vom Startup zur Internet Connection braucht, dann sind 5min in Raspmatic vielleicht zu knapp bemessen. Um da Safe zu sein ist man schon eher bei 15min. Mit Fibre geht es vielleicht schneller, aber mit DSL sind 5min bei einem normalen Reboot schon recht knapp bemessen.

**Comment by jens-maus** [comment]
> Ich habe bisher leider die persönliche Erfahrung gemacht, dass 1 von 7 Alarmen ein echter Alarm war - halt "einer" bei dem wirklich mal DSL kaputt war. Ansonsten leider nur "Fehlalarme". Abschalten will ich das Feature aber eigentlich auch nicht.

Das sind keine Fehlalarme. Wenn er nach 5 Minuten (aus welchen Gründen auch immer) nicht auf Google&Co zugreifen kann gibts halt die Alarmierung. Das kann aber natürlich unterschiedliche Ursachen haben, das kannst nur du wissen und beachten. Und du kannst den Alarm auch einfach nur bestätigen/wegklicken wenn du der Meinung bist das der nicht wichtig ist.

> Heute Nacht wurde meine Fritzbox 7590 automatisch von v7.28 nach v7.29 aktualisiert. Leider kann ich nicht sehen wann sie runter gefahren ist, aber das Log sagt, dass sie um 4:25:27 wieder hoch kam und einen ftpuser ohne Passwort deaktiviert hat und die Internet Connection um 4:29:24 erfolgreich hergestellt wurde. Davor war DSL-Sync und anderes Zeugs. Zudem hat sie vor 4:25:27 auch noch das Firmware Update installiert...

Das mag alles sein. Trotzdem war das Internet >5 Minuten weg und insofern hat RaspberryMatic vollkommen recht dich darüber zu informieren. Wenn du das nicht willst, schalte den Alarm ab.

> Ich habe zwar keine Statistiken über durchschnittliche Firmwareupdate/Bootzeiten, aber wenn es schon über 4min vom Startup zur Internet Connection braucht, dann sind 5min in Raspmatic vielleicht zu knapp bemessen. Um da Safe zu sein ist man schon eher bei 15min. Mit Fibre geht es vielleicht schneller, aber mit DSL sind 5min bei einem normalen Reboot schon recht knapp bemessen.

Auch das mag sein, Aber 5 Minuten ist eben der Threshold den es momentan dafür gibt. Dem einen sind 5 Minuten zu lange, dem anderen zu kurz. Es ist wie es ist und 5 Minuten sind eben der Wert wie er umgesetzt ist. Wenn dir das nicht passt schalt den Alarm ab, ein Problem oder einen Grund für Verbesserungen sehe ich hier zumindest nicht, denn der Großteil der Nutzer scheint damit konform zu gehen.
