### ISSUE TITLE
Pocket Control HM Pushmitteilungen / Geofencing-Zone

### ISSUE THREAD

**Issue by FriMatze** [jens-maus/RaspberryMatic#155]
Moin,

nach dem Update auf die Firmware 2.29.22.20170902 werden keine Pushmitteilungen, die über Pocket Control HM eingerichtet wurden, mehr gesendet. Die Systemvariabel wird dennoch geschrieben.

Des Weiteren wird die Geofencing Funktion der App nicht mehr unterstützt bzw. nicht mehr gesetzt.

Im vorrigen Release funktionierten die Funktionen noch.
#
Gruß

**Comment by jens-maus** [comment]
Dies ist ein bekanntes Problem mit Pocket Control HM der erst mit der aktuellen 2.29.22.20170902 Version von RaspberryMatic sichtbar geworden ist. Die Entwickler von Pocket Control sind darüber informiert und arbeiten an einer permanenten Lösung.

Als Workaround wird momentan empfohlen das systemuntere Programm das PocketControl selbst anlegt in der WebUI geringfügig anzupassen. Dieses wird in der Programliste mit dem Namen `Push Script for pocket control` geführt. Darin sollte die letzte Zeile des in diesem Programm befindlichen Skriptes in dem die Funktion `System.Exec()` verwendet wird wie folgt angepasst werden:

```
system.Exec("wget -q -O /dev/null --post-data='" # msg  # "' " # url # " &");
```

Danach sollten die Push Mitteilungen wieder funktionieren. Einen entsprechenden HomeMatic-Forum Eintrag gibt es hier:
https://homematic-forum.de/forum/viewtopic.php?f=65&t=38707#p381246

**Comment by jens-maus** [comment]
Bzgl. der Geofencing Funktion muss ich mich erst einmal schlau machen ob diese auch irgendeinen Skript einsetzt der nun ggf. nicht mehr funktioniert. Tauchen denn irgendwelche Fehler im Logfile der CCU auf wenn versucht wird die Geofencing Funktion zu nutzen bzw. einzurichten?

**Comment by FriMatze** [comment]
Push: Workaround  hat funktioniert. Homematic-Forum Post hatte ich übersehen.

Geofencing: Meine Frau hat heute bereits mehrmals die HomeZone verlassen bzw ist wieder eingetreten. Das verlassen wurde nicht geloggt. Habe ich Manuel angepasst. Das eintreten jedoch wurde geloggt. 

Leider kann ich den Systemlog nicht auswerten. Zu kryptisch! Habe ich als PDF mal angehangen.
[RaspberryMatic-2017-09-08 (2) -  (1).pdf](https://github.com/jens-maus/RaspberryMatic/files/1287396/RaspberryMatic-2017-09-08.2.-.1.pdf)

**Comment by FriMatze** [comment]
Moin, für dich zur Info. Geofencing Problem ist behoben. Wieso auch immer wurde nach dem Update auf Firmware 8.3.5 von Pocket Control HM die Hintergrundaktualisierung auf meinem iPhone und das meiner Frau deaktiviert. Ist mir gestern durch Zufall aufgefallen. Nach dem aktivieren funktioniert alles wieder wie gehabt..
