### ISSUE TITLE
Update auf Version 3.61.5.20211113 klappt nicht....

### ISSUE THREAD

**Issue by Harry423** [jens-maus/RaspberryMatic#1554]
### Describe the issue you are experiencing

Ich habe mir von Github die Datei RaspberryMatic-3.61.5.20211113-ccu3.tgz heruntergeladen und installiert. Nach dem Update ist die Version immer noch unverändert:

![Bildschirmfoto 2021-11-21 um 14 14 49](https://user-images.githubusercontent.com/73777886/142763386-123fd081-3557-4631-9756-f53595e52d98.jpg)

Ich habe die Datei sogar noch ein zweites mal herunter geladen  und installiert - gleiches Ergebnis.

Bei Update selbt fährt die Raspi-Box übrigens runter und muss dann manuell neu gestartet werden. Es ist aso kein wirkliches Reboot...
 

### Describe the behavior you expected

Alte Version wird immer noch angezeigt.

### Steps to reproduce the issue

Installation druchgeführt ohne, dass Versionswechsel erfolgt..

### What is the version this bug report is based on?

 3.59.6.20211009

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
.
```

**Comment by jens-maus** [comment]
Sorry, but this is no support or discussion fora here. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. This was also already mentioned in the ticket template!
___
Tut mir leid, aber das hier ist kein Supportforum, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen.  Dies stand übrigens auch so im Ticket Template!
