### ISSUE TITLE
Die Abfrage der Dimmwerte in Programmen auf <= 0.00 % klappt in meinen Programmen seit 2.29 nicht mehr

### ISSUE THREAD

**Issue by Berndpaulus** [jens-maus/RaspberryMatic#156]
Die Abfrage der Dimmwerte in Programmen auf <= 0.00 % klappt in meinen Programmen seit Version 2.29 nicht mehr. Stelle ich um auf "Realkanal" gehen die Programme wieder. Beim Dimmer HM-LC-Dim1T-FM ist das leider nicht möglich. Nehme ich den raus, dann funktioniert das Programm auf einem R3. 

Beispiel:(einschalten geht, Ausschalten nicht)
Bedingung: Wenn...
Geräteauswahl SZ_Dim_LL_Sanne:1 bei Dimmwert Realkanal im Wertebereich kleiner oder gleich 0.00 % bei Änderung auslösen  
UND
Geräteauswahl SZ_Dim_LL_Bernd:1 bei Dimmwert Realkanal im Wertebereich kleiner oder gleich 0.00 % bei Änderung auslösen  
UND
Geräteauswahl SZ-Decke:1 bei Dimmwert Realkanal im Wertebereich kleiner oder gleich 0.00 % bei Änderung auslösen  
UND
Geräteauswahl SZ-hinter-Bett:1 bei Schaltzustand: aus bei Änderung auslösen  
UND
Geräteauswahl SZ_unter_Bett:1 bei Schaltzustand: aus bei Änderung auslösen  
UND
**Geräteauswahl SZ_Dim_NTL_Bernd:1 bei Dimmwert** im Wertebereich von 0.00 % bis kleiner 0.00 % bei Änderung auslösen  
Aktivität: Dann...Vor dem Ausführen alle laufenden Verzögerungen für diese Aktivitäten beenden (z.B. Retriggern).
Systemzustand SA1-02 sofort  0.00  
Systemzustand zz_Statusanzeige1IconB04 sofort LAMPE_AUS  
Systemzustand zz_Statusanzeige1TextB04 sofort Licht Schlafzimmer aus {BidCoS-RF:11.PRESS_SHORT}  
Aktivität: Sonst...Vor dem Ausführen alle laufenden Verzögerungen für diese Aktivitäten beenden (z.B. Retriggern).
Systemzustand SA1-02 sofort  3.00  
Systemzustand zz_Statusanzeige1IconB04 sofort LAMPE_AN  
Systemzustand zz_Statusanzeige1TextB04 sofort Licht Schlafzimmer an {BidCoS-RF:11.PRESS_SHORT}

**Comment by jens-maus** [comment]
Das Problem ist bereits bekannt und repariert worden und wir in der nächsten kommenden RaspberryMatic Version korrigiert sein,

**Comment by Berndpaulus** [comment]
Danke!
