### ISSUE TITLE
Problem Programme innerhalb Raspberrymatic 

### ISSUE THREAD

**Issue by jjbbxx** [jens-maus/RaspberryMatic#1563]
### Describe the issue you are experiencing

![image](https://user-images.githubusercontent.com/94995556/143307848-cb910563-8ce3-4b76-a0ce-72de3d6d9306.png)
Seit den letzten Updates scheint mir die Unterscheidung "bei Aktualsierung" und "bei Änderung" nicht mehr richtig zu funktionieren. Bis zum Sommer gab es keine Auslösung des Programms, wenn die beiden Werte sich nicht ändern, auch wenn diese mit dem gleichen Wert neu geschrieben werden. Lediglich bei Änderungen z.B. von false auf true bzw. auf den Wert "close". So konnte hier der Rollladen immer angehalten werden und später geschlossen werden, jetzt wird nach wenigen Sekunden der Rollladen neu angetriggert.

### Describe the behavior you expected

Auslösung des Programms nur bei "Änderung" des Wertes gemäß Beschreibung. Ob dies in einer echten CCU anders ist, kann ich nicht sagen.

### Steps to reproduce the issue

1. 
2.
3.
...

### What is the version this bug report is based on?

3.59.6.20211009

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
not yet
```

**Comment by jens-maus** [comment]
Sorry, but this is no support or discussion fora here. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. This was also already mentioned in the ticket template!
___
Tut mir leid, aber das hier ist kein Supportforum, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen.  Dies stand übrigens auch so im Ticket Template!

**Comment by jjbbxx** [comment]
Hallo Jens, das sehe ich nicht so. Gemäß Anleitung und Support ist die gegebene Funktion "bei Änderung auslösen" wie von mir beschrieben dokumentiert. Die Funktion ist aber in der Version 3.59.6.20211009 nicht gegeben. Das Verhalten ist atypisch und somit als BUG richtig platziert.

**Comment by jens-maus** [comment]
> Das Verhalten ist atypisch und somit als BUG richtig platziert.

Das Verhalten ist ggf. in **deiner** Installation atypisch und könnte ggf unter umständen, eventl. ein Bug sein ja. Du zeigst aber keinen Bug hier auf. GitHub ist keine Diskussionsplatform aber eine Entwicklungsplatform. Ergo, bitte erst in geeigneten Foren (z.B. HomeMatic Forum) deine Beobachtung vorstellen/diskutieren und wenn sich daraus ergibt (z.B. durch klare reproduzierbarkeit auf einem frischen/jungfreulichen system) das die ein Bug ist, DANN hier her kommen und einen Bugreport aufmachen. So das gewollte Prozedere hier!
