### ISSUE TITLE
Ändern von SV-Werten via WebUI führt zu Mehrfacheinträgen im Systemprotokoll und Falsch-Triggern in Programmen

### ISSUE THREAD

**Issue by jp112sdl** [jens-maus/RaspberryMatic#1568]
### Describe the issue you are experiencing

Ändert man in der WebUI den Wert einer Systemvariable, so wird beim Speichern zunächst der Default-Wert mit `.State()` gesetzt und anschließend erst der User-Wert.
Das führt u.a. dazu, dass im Systemprotokoll bei 1 Änderung immer 2 Einträge erzeugt werden und auch ggf. Programme augenscheinlich falsch getriggert werden.

https://github.com/jens-maus/RaspberryMatic/blob/0136b7af345f511d63e20dab58c2a31b02af8463/buildroot-external/patches/occu/0097-WebUI-SetSysvarValueByUser/occu/WebUI/www/rega/esp/system.fn#L810-L863

Könnte ggf. so gelöst werden:
```TCL
  if (system.GetVar("sValue")) {
    sv.State(system.GetVar("sValue"));
  } else {
    if (ist == istAlarm)
    {
      sv.ValueType( ivtBinary );
      sv.ValueSubType( istAlarm );
      sv.ValueName1(system.GetVar("sTrue"));
      sv.ValueName0(system.GetVar("sFalse"));
      sv.AlType(atSystem);
      sv.AlArm(true);
    }
    elseif (ist == istBool)
    {
      sv.ValueType( ivtBinary );
      sv.ValueSubType( istBool );
      sv.ValueName1(system.GetVar("sTrue"));
      sv.ValueName0(system.GetVar("sFalse"));
      sv.State(false);
    }
    elseif (ist == istGeneric)
    {
      sv.ValueType( ivtFloat );
      sv.ValueSubType( istGeneric );
      sv.ValueMin(system.GetVar("iMinVal"));
      sv.ValueMax(system.GetVar("iMaxVal"));
      sv.State(system.GetVar("iMinVal"));
    }
    elseif (ist == istEnum)
    {
      sv.ValueType( ivtInteger );
      sv.ValueSubType( istEnum );
      sv.ValueList(system.GetVar("sValList"));
      sv.State(0);
    }
    elseif (ist == istChar8859)
    {
      sv.ValueType(ivtString);
      sv.ValueSubType(istChar8859);
      sv.State("");
    }
    
    if (oChn) 
    {
      oChn.DPs().Add( sv.ID() );
      sv.Channel( oChn.ID() );
    }
    else
    {
      oChn = dom.GetObject( sv.Channel() );
      if( oChn )
      {
        oChn.DPs().Remove( sv.ID() );
      }
      sv.Channel( ID_ERROR );
    }
  }
```

### Describe the behavior you expected

Ändern von SV-Inhalten führt nur ein Mal zu Schreiben von `.State()`

### Steps to reproduce the issue

1.
2.
3.
...

### What is the version this bug report is based on?

3.61.5.20211125

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
Nope
```

**Comment by jens-maus** [comment]
Na dann, her mit dem PR ;-)

**Comment by jp112sdl** [comment]
Das hätte jedoch auch zur Folge, dass neu angelegte Zeichenketten-SVen nicht mehr "???" vorbelegt hätten, sondern "" (leer) wären.

Denn wenn man eine Zeichenkette benutzerdefiniert leert (leerer String) ist die `if (system.GetVar("sValue"))`-Prüfung `false` und dann würde in den Default-Zweig für Zeichenketten-SVen abgebogen werden, wo momentan noch "???" drin steht

**Comment by jens-maus** [comment]
> Das hätte jedoch auch zur Folge, dass neu angelegte Zeichenketten-SVen nicht mehr mit "???" vorbelegt wären, sondern "" (leer) wären.

Das finde ich OK und vertretbar. Ergab noch nie sinn das die standardmäßig mit "???" belegt wird.

**Comment by jp112sdl** [comment]
Meine Idee ist doch nicht die Lösung... ich grübel mal noch etwas weiter

**Comment by jp112sdl** [comment]
So, nu sollte es passen
