### ISSUE TITLE
FHEM umstieg oder Erweitern mit RaspberryMatic?

### ISSUE THREAD

**Issue by Torben80** [jens-maus/RaspberryMatic#157]
Moin Moin,
ich habe an dieser Stelle eine kurze Frage an die Profis.

Derzeit betreibe ich eine Pi3 mit FHEM und habe einige Homematic - Geräte (Wandthermostate) angebunden.

Nun möchte ich auch noch HM-IP betreiben (Stellantriebe für Heizung). Jetzt kommt ja die CCU2 ins Spiel.

Ich habe nun die Möglichkeit die CCU2 zu kaufen und an mein FHEM zu koppeln oder weiche von meinem ganzen FHEM ab nutze nur noch RaspberryMatic. Das Problem was ich aber habe,
dass ich per HTTP-GET meine Alarmanlage abfragen kann und so den ZUSTAND der Anlage / der Kontakte erhalten kann. Kann ich das auch in RaspberryMatic irgendwie einbauen / umsetzen? Gibt es hier die Möglichkeit auch eine Art UI für das Tablet selber zu gestalten und dann als "Bilderrahmen" an die Wand zu nageln?

mfg Torben

**Comment by jens-maus** [comment]
Sorry, aber das ist ein Bug/Issue-Tracker und kein Support-Forum. Bitte an homematic-forum.de wenden und dort solche Dinge diskutieren.
