### ISSUE TITLE
HmIP-HAP update request, but it is a downgrade

### ISSUE THREAD

**Issue by FrodoVDR** [jens-maus/RaspberryMatic#1570]
### Describe the issue you are experiencing

I get the message that an update is available for HmIP-HAP. However, the device has version 2.2.24 and the version to install would be 2.2.18.
![image](https://user-images.githubusercontent.com/9979929/143679319-32a87140-e110-4c50-bfee-41140bb270b4.png)

### Describe the behavior you expected

Downgrade is no longer displayed as an update.

### Steps to reproduce the issue

1. You need a HmIP-HAP with firmware 2.2.24

### What is the version this bug report is based on?

3.61.5.20211113

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
no
```

**Comment by jens-maus** [comment]
This is not a bug, but a feature! Downgrades are also perfectly valid procedures as the CCU or RaspberryMatic firmware version has a well defined compatibility chain, thus the currently supported/validated firmware for the HmIP-HAP is 2.2.18. Thus, the suggestion to perform a downgrade is perfectly valid. However, it is up to you to perform it or not, of course. But simply don't complain if you are seeing issues with your HAP in combination with your CCU/RaspberryMatic
