### ISSUE TITLE
Migrate from VM with HM-CFG-LAN to CCU3: Config restore fails

### ISSUE THREAD

**Issue by kokel** [jens-maus/RaspberryMatic#1576]
### Describe the issue you are experiencing

I want to migrate my virtual Raspberrymatic (Qemu/KVM) with HM-CFG-LAN to a CCU3 device running the same Raspberrymatic version.
When I try to restore the backup from file in the CCU3 I get the following error:

Backup fehlerhaft/unvollständig (z.B. *.apkx Datei fehlt).

### Describe the behavior you expected

I have expected that I can migrate the configuration from virtual Raspberrymatic to CCU3 Raspberrymatic, easily using the backup/restore procedure.

### Steps to reproduce the issue

1.Create Backup on virtual Raspberrymatic
2.Restore Backup on CCU3 Raspberrymatic

### What is the version this bug report is based on?

3.61.5.20211113

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

HM-CFG-LAN

### Anything in the logs that might be useful for us?

```txt
No, if I can provide more information, tell me please how.
```

### Additional information

The dropdown menu for platform selection isn't complete.
I run Raspberrymatic in a virtual machine using Qemu/KVM on Archlinux in conjunction with the HM-CFG-LAN Gateway.
Now, I want to migrate the configuration to a CCU3 running the same Raspberrymatic version.

**Comment by kokel** [comment]
I have an update: After I give the CCU3 the same IP address my virtual instance had, I see that the config restore was successfull.
A new try to restore from backup failed again. But it seems I have my config on the CCU3 now.

**Comment by Baxxy13** [comment]
Die beschriebene Fehlermeldung... 

> Backup fehlerhaft/unvollständig (z.B. *.apkx Datei fehlt).

kommt immer dann, wenn am Zielsystem (wo das Backup eingespielt wird) kein aktives Funkmodul dran ist. 
Ein HM-CFG-LAN zählt da meines Wissens nicht (zu den aktiven Funkmodulen) dazu. 
Der Rat aus dem Homematic-Forum dazu lautete immer...
ignorieren, rebooten und dann ist dein Backup eingespielt.

In der Tat wäre aber hier eine aussagekräftigere Meldung sinnvoll.

**Comment by kokel** [comment]
> Die beschriebene Fehlermeldung...
> 
> > Backup fehlerhaft/unvollständig (z.B. *.apkx Datei fehlt).
> 
> kommt immer dann, wenn am Zielsystem (wo das Backup eingespielt wird) kein aktives Funkmodul dran ist. Ein HM-CFG-LAN zählt da meines Wissens nicht (zu den aktiven Funkmodulen) dazu. Der Rat aus dem Homematic-Forum dazu lautete immer... ignorieren, rebooten und dann ist dein Backup eingespielt.

Danke, so wars bei mir auch. Bin halt nicht sofort auf die Idee gekommen zu rebooten, dachte halt das Einspielen des Backups ist fehlgeschlagen.

+1 für sinnvollere Fehlerbeschreibung.

**Comment by jp112sdl** [comment]
Das Problem ist, dass der Return-Code aus dem closed-source HMIPServer kommt.
