### ISSUE TITLE
NUT Treiber aktualisieren

### ISSUE THREAD

**Issue by WK-Eider** [jens-maus/RaspberryMatic#1577]
### Describe the solution you'd like

Ich möchte gerne eine Eigenbau UPS für die RM einsetzen. 
Nach dem Vorschlag von:
      https://create.arduino.cc/projecthub/abratchik/hid-compliant-ups-with-arduino-75198c
Dazu fehlen aber die aktuellsten Treiber in der installierten NUT-Software
       https://github.com/networkupstools/nut/

### Describe alternatives you've considered

Selbst compelieren geht nicht, da auf dem RM diverse Programme fehlen ...
Ich habe die akt NUT-Software auf Ubuntu compeliert aber die Programmteile laufen auf dem RM natürlich nicht.
Auf Ubuntu läuft auch meine Hardware mit NUT.

### Is your feature request related to a problem?

ja, fehlende Treiber

### Additional information

Es wäre toll wenn die Treiber aktualisiert werden können.

Danke

**Comment by jens-maus** [comment]
Die jeweils ausgelieferte NUT Version wird momentan vom darunterliegenden Buildroot-System vorgegeben. D.h. wenn dort NUT nicht aktualisiert wird, passiert das zwangsläufig auch nicht in RaspberryMatic.

**Comment by WK-Eider** [comment]
Danke für die Info.
Hoffentlich bewegt sich bei "NUT" etwas.
