### ISSUE TITLE
Homematic IP Geräte Anlernen geht nicht

### ISSUE THREAD

**Issue by oliverboermel** [jens-maus/RaspberryMatic#1578]
### Describe the issue you are experiencing

Es ist nicht möglich Geräte anzuleren

### Describe the behavior you expected

Anlernen von Homematic IP Geräten geht nicht

### Steps to reproduce the issue

1. Bei jedem Gerät geht das Anlernen nicht
2.
3.
...

### What is the version this bug report is based on?

3.61.5.2021

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
ttyUSB0
/dev/serial/by-id/usb-Silicon_Labs_eQ-3_HmIP-RFUSB_3014F711A061A7C00010CECF-if00-port0
Subsystem:
tty
Gerätepfad:
/dev/ttyUSB0
ID:
/dev/serial/by-id/usb-Silicon_Labs_eQ-3_HmIP-RFUSB_3014F711A061A7C00010CECF-if00-port0

DEVLINKS: >-
  /dev/serial/by-id/usb-Silicon_Labs_eQ-3_HmIP-RFUSB_3014F711A061A7C00010CECF-if00-port0
  /dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.0-port0
DEVNAME: /dev/ttyUSB0
DEVPATH: >-
  /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.4/1-1.4:1.0/ttyUSB0/tty/ttyUSB0
ID_BUS: usb
ID_MODEL: eQ-3_HmIP-RFUSB
ID_MODEL_ENC: eQ-3\x20HmIP-RFUSB
ID_MODEL_ID: c020
ID_PATH: platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.0
ID_PATH_TAG: platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1_4_1_0
ID_REVISION: '0100'
ID_SERIAL: Silicon_Labs_eQ-3_HmIP-RFUSB_3014F711A061A7C00010CECF
ID_SERIAL_SHORT: 3014F711A061A7C00010CECF
ID_TYPE: generic
ID_USB_DRIVER: cp210x
ID_USB_INTERFACES: ':ff0000:'
ID_USB_INTERFACE_NUM: '00'
ID_VENDOR: Silicon_Labs
ID_VENDOR_ENC: Silicon\x20Labs
ID_VENDOR_ID: 1b1f
MAJOR: '188'
MINOR: '0'
SUBSYSTEM: tty
TAGS: ':systemd:'
USEC_INITIALIZED: '3957815'


Mounting /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying onboard hardware: oci, OK
Initializing RTC Clock: no hardware found
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.3, OK
Identifying Homematic RF-Hardware: ....HmRF: none, HmIP: HMIP-RFUSB/USB, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: 2.8.6, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: not required
Starting rfd: no BidCos-RF hardware found
Starting HMIPServer: .............OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
```

**Comment by Baxxy13** [comment]
Liegt möglicherweise an den Funkstöreigenschaften des Pi4B

- USB3 Anschlüsse nicht verwenden!
- HmIP-RFUSB mit USB-Verlängerung möglichst weit vom Pi4B absetzen

Mehr zum Thema: [Raspberry Pi 4 (Pi4B) als Homematic-Zentrale](https://homematic-forum.de/forum/viewtopic.php?f=31&t=65293)

**Comment by oliverboermel** [comment]
Moin

Das habe ich alles Getan.


ich hatte vorher die ander HomematicIP integration benutzt da konnte ich alle Geräte anlernen und da war das Problem das

sie weg waren nach jedem Neustart deswegen hab ich gewechselt ud nun kann ich nicht mal ein Gerät anlernen.

Ich hab das gefühl das das Problem existiert seit ich SSD habe.

Gruß

Oliver


Gesendet: Sonntag, 05. Dezember 2021 um 22:33 Uhr
Von: "Baxxy13" ***@***.***>
An: "jens-maus/RaspberryMatic" ***@***.***>
Cc: "oliverboermel" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [jens-maus/RaspberryMatic] Homematic IP Geräte Anlernen geht nicht (Issue #1578)


 

Liegt möglicherweise an den Funkstöreigenschaften des Pi4B


	USB3 Anschlüsse nicht verwenden!
	HmIP-RFUSB mit USB-Verlängerung möglichst weit vom Pi4B absetzen


Mehr zum Thema: Raspberry Pi 4 (Pi4B) als Homematic-Zentrale

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by oliverboermel** [comment]
Guten Morgen,

nein es lag daran das wohl eine SSD an einem USB3 Anschluss und der Homematic USB Stick 

nicht genug Power bekommen. USB Hub mit Stromversorgung und umstecken des Sticks

haben das Problem beseitigt.

Ticket kann geschlossen werden

 

 
 

Gesendet: Sonntag, 05. Dezember 2021 um 22:33 Uhr
Von: "Baxxy13" ***@***.***>
An: "jens-maus/RaspberryMatic" ***@***.***>
Cc: "oliverboermel" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [jens-maus/RaspberryMatic] Homematic IP Geräte Anlernen geht nicht (Issue #1578)


 

Liegt möglicherweise an den Funkstöreigenschaften des Pi4B


	USB3 Anschlüsse nicht verwenden!
	HmIP-RFUSB mit USB-Verlängerung möglichst weit vom Pi4B absetzen


Mehr zum Thema: Raspberry Pi 4 (Pi4B) als Homematic-Zentrale

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jens-maus** [comment]
> Guten Morgen, nein es lag daran das wohl eine SSD an einem USB3 Anschluss und der Homematic USB Stick  nicht genug Power bekommen. USB Hub mit Stromversorgung und umstecken des Sticks haben das Problem beseitigt. Ticket kann geschlossen werden

Ok, wird erledigt. Und für die Zukunft merken: NICHT direkt auf die GitHub Emails replien! Auch wenn das technisch geht ist es aber nicht sinnvoll. GitHub sollte man via Web bedienen und Tickets editieren via webbrowser und nicht via reply.
