### ISSUE TITLE
Raspberrymatic on Docker install "Paket linux-headers-5.10.63-v8 kann nicht gefunden werden"

### ISSUE THREAD

**Issue by guny74** [jens-maus/RaspberryMatic#1582]
### Describe the issue you are experiencing

Hallo,

ich versuche Raspberrymatic in einem Docker zu installieren.
Basis OS ist "dietpi" basierend auf Debian bullseye.
(inzwischen auch mit reiner 64bit Image von "Raspberry PI OS" mit gleichem Ergebnis)

Bei der Ausführung des "./deploy.sh" bekomme ich die Meldung / Abbruch  "Paket linux-headers-5.10.63-v8 kann nicht gefunden werden.", da beim "uname -r" --> 5.10.63-v8+
Ist hier irgendetwas zu neu ?

Danke

### Describe the behavior you expected

Erfolgreicher Abschluss  des Deloy Scriptes

### Steps to reproduce the issue

1. Saubere Basis Installation incl Docker 
2. Schritte und Befehle laut Anleitung bis "./deploy.sh"

### What is the version this bug report is based on?

3xxx

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
no
```

**Comment by guny74** [comment]
Ich glaube, dass Problem könnte sein, dass auch wenn man  "apt install linux-headers-5.10.63-v8+" das "+" als wildcard interpretiert wird....daher wird die Zeile `apt install "${FORCE}" "linux-headers-$(uname -r)" ` wohl fehl schlagen

**Comment by guny74** [comment]
Zwischenzeitlich dachte ich, ich hätte den Fehler gefunden. Es gibt den Hinweis bei Alexreinert, dass Systeme mit gemischten 32bit Libs und 64 Bit Kernel nicht supported werden. Daraufhin habe ich eine reine 64bit Image vom "Raspberry PI OS" genommen,
um schlussendlich auf den selben Fehler zu laufen.

**Comment by SaschaPeter** [comment]
Also unter Raspian hat das geholfen, mit DietPi habe ich noch nichts probiert :
sudo apt install raspberrypi-kernel-headers
geht aber noch nicht so lange, davor hatte ich 2 Scripte zum Aufbau der Kernel Header ausprobiert, da hatte man zwar Kernel Header für v8+ aber für dkms hat es nicht gereicht und ich bin zurück aus 32, jetzt läuft RM auf Docker und 5.10.63-v8+ aarch64. Hatte auch ein paar Anläufe in den letzten 5-6 Wochen, seit dem 3.12. läuft alles so wie ich es erwarte.

**Comment by guny74** [comment]
Hallo, 

das hatte ich bei der DietPi Variante zwar gemacht...auch bei der Raspberry PI OS (64bit lite) habe ich es erfolgreich installiert.

Das "deploy.sh" wirft aber den gleichen Fehler.

Reicht es aus dann die "pull docker Variante" zu nehmen ?

In dem DeployScript werden ja wohl auch noch andere Dinge wie udev Rules etc gesetzt, oder ?

**Comment by SaschaPeter** [comment]
Also ich bin mir nicht ganz sicher, ob ich dir folgen kann.
Oben schreibst du noch, dass es mit Raspberry PI OS genauso aussieht.
Wenn ich damit Probleme hatte dann schon hier:
sudo apt install pivccu-modules-dkms
bzw.
hier
sudo modprobe eq3_char_loop
lief das denn bei dir sauber durch?
Falls du dir nicht 100%ig  sicher bist, wiederhole "sudo modprobe eq3_char_loop" einfach noch einmal.

Denn mir ist es bisher nicht passiert, dass modprobe sauber durchgelaufen ist und ich dann Probleme mit dem Container hatte.
Von daher bin ich mir auch nicht sicher, ob dies hier der richtige Platz ist oder dass nicht besser im Forum aufgehoben ist.
Denn bisher hast du eigentlich ein Problem mit dem OS und nicht mit dem RM Image.

**Comment by guny74** [comment]
Hallo, 

im Ursprungseintrag habe ich geschrieben, dass es bei Raspberry PI OS das gleich Problem gab, aber ich habe gestern geschrieben, dass ich festgestellt habe, dass dies wohl eine "Mixed Image" (32bit Libs /64 bit Kernel) war. 
Nach Nutzung des reinen 64 Bit lite Image von "Raspberry PI OS" lief alles sauber durch **bis zu dem ".deploy.sh"**.

Bei der Nutzung des ".deply.sh" Scriptes erhalte ich weiterhin den Fehler `Paket linux-headers-5.10.63-v8 kann nicht gefunden werden`

Ich habe auch über die "Docker Pull" Variante (aus der Anleitung) ein Container am laufen, aber bisher ohne Funkmodul, da ich hier erstmal das Aufsetzten testen wollte.

Ich habe im .deploy.sh eben Kommandos gesehen wir z.b. 
`if [[ ! -e /etc/udev/rules.d/99-Homematic.rules ]]; then
  echo "Adding udev rule"
  check_sudo
  cat <<'EOF' >/etc/udev/rules.d/99-Homematic.rules` 

die nur in der Script Variante enthalten sind....und daher frage ich mich eben, ob es alles mit nur der "Docker Pull" Variante aus der Anleitung funktionieren kann ohne das "deploy.sh" Script durchlaufen zu haben.

**Comment by SaschaPeter** [comment]
Mir erschließt sich nicht ganz der warum man ohne Funkmodul starten will.
Welches konkrete Raspbian Image hast du denn genutzt?

Du schreibst auch nicht ob du nun "sudo apt install raspberrypi-kernel-headers mal ausgeführt hast.
Was gibt ls /lib/modules bei dir aus?

**Comment by guny74** [comment]
Hallo,

also vor 7 Stunden habe ich folgendes auf Ihren Hinweis zur Installation der Kernel Headers geantwortet:
"..._das hatte ich bei der DietPi Variante zwar gemacht...auch bei der Raspberry PI OS (64bit lite) habe ich es erfolgreich installiert._"

Ja, ich die Installation der Kernel Headers `sudo apt install raspberrypi-kernel-headers` erfolgreich durchgeführt und ich nutze "raspberry Pi OS 64bit lite" neuste Version  (bulls eye) vom 30.10.2021.

Ich habe eine Raspberrymatic Instanz als Standalone mit Redmatic, welches veraltet ist und Probleme macht.
Da ich alles (z.b. Node Red + Raspberrymatic) auf einer Maschine haben möchte, möchte ich eben schauen, dass es eben per Docker Instanzen auf einem Host läuft. Da ich die aktuelle Instanz natürlich noch in Nutzung habe und eben die Installationsroutine testen wollte, um eben solche Probleme wie jetzt auftreten, erstmal zu validieren, habe ich meine Funkmodul etc natürlich erstmal bei meiner produktiven Instanz im Einsatz.

Daher der Start "ohne" Funkmodul...
 
```
 ls /lib/modules

5.10.0-9-arm64 
5.10.63-v8+
```

`  uname -r
5.10.63-v8+
`

Daher hat mich ja auch gewundert, dass er in der Fehlermeldung (siehe meine Vermutung 2. Kommentar) nur etwas von "...v8" und nicht ...v8+"  steht.

Auch wenn ich `sudo apt install  "linux-headers-5.10.63-v8+"` versuche, kommt die Meldung `Paket linux-headers-5.10.63-v8 kann nicht gefunden werden`  als wenn es das "+" bei dem Befehl verschlucken würde.
Bin kein "shell/script" experte, aber vielleicht wird das "+" irgendwie falsch interpretiert und sucht daher nur nach "...v8" was natürlich nicht da ist

Vielleicht sollte ich dann doch besser auf die 32 Bit Variante wechseln....obwohl es schon schön wäre, wenn man die Basis schon auf 64 Bit hätte...

**Comment by jens-maus** [comment]
> Auch wenn ich `sudo apt install "linux-headers-5.10.63-v8+"` versuche, kommt die Meldung `Paket linux-headers-5.10.63-v8 kann nicht gefunden werden` als wenn es das "+" bei dem Befehl verschlucken würde. Bin kein "shell/script" experte, aber vielleicht wird das "+" irgendwie falsch interpretiert und sucht daher nur nach "...v8" was natürlich nicht da ist

Na dann änder doch mal den `deploy.sh` skript an der folgenden Stelle ab:

https://github.com/jens-maus/RaspberryMatic/blob/6ec4f78db7e256c466360fea28e00460fbd5a929/buildroot-external/board/oci/deploy.sh#L118

Und mach daraus sowas wie:

```
apt install "${FORCE}" \"linux-headers-$(uname -r)\" 
```

Wenn das geht könnte ich natürlich den Skript entsprechend fixen/anpassen.

**Comment by guny74** [comment]
Danke...

also 

 Meldung hat sich von  
```
E: Paket linux-headers-5.10.63-v8 kann nicht gefunden werden.
E: Mittels des Musters »linux-headers-5.10.63-v8« konnte kein Paket gefunden werden.

```

auf 

`E: Paket "linux-headers-5.10.63-v8+" kann nicht gefunden werden.`

geändert. Jetzt ist auch das "+" da, aber er findet es dennoch nicht, obwohl es unter `/lib/modules`  ein entsprechendes Verzeichnis gibt.

Ein gleiches "escapen" in Zeile 115 `elif ! pkg_installed \"linux-headers-$(uname -r)\"; then` hat leider auch keine Veränderung gebracht.
 
Weitere Ideen ?

**Comment by jens-maus** [comment]
Probier mal 

```
apt install "${FORCE}" \'linux-headers-$(uname -r)\' 
```

d.h. einfache hochkommata

**Comment by guny74** [comment]
Habe ich auch schon getestet 

`apt install "${FORCE}" \'linux-headers-$(uname -r)\' `

Ergebnis
`E: Paket 'linux-headers-5.10.63-v8+' kann nicht gefunden werden.`

weiterer Versucht von mir 

`apt install "${FORCE}" \linux-headers-$(uname -r)\ `

Ergebnis 

`E: Paket linux-headers-5.10.63-v8+  kann nicht gefunden werden.`

Hier sieht es aus als wäre das ein extra "blank" hinter

**Comment by jens-maus** [comment]
Na dann gibt es dieses Paket "linux-headers-5.10.63-v8+" bei neueren RaspberryPiOS Varianten vielleicht einfach nicht. Mach halt mal ein "apt search" danach und find heraus was da anders ist.

**Comment by guny74** [comment]
```
 sudo apt list linux-headers-*
Auflistung… Fertig
linux-headers-5.10.0-8-arm64/stable,stable-security 5.10.46-5 arm64
linux-headers-5.10.0-8-armmp-lpae/stable,stable-security 5.10.46-5 armhf
linux-headers-5.10.0-8-armmp/stable,stable-security 5.10.46-5 armhf
linux-headers-5.10.0-8-cloud-arm64/stable,stable-security 5.10.46-5 arm64
linux-headers-5.10.0-8-common-rt/stable,stable,stable-security,stable-security 5.10.46-5 all
linux-headers-5.10.0-8-common/stable,stable,stable-security,stable-security 5.10.46-5 all
linux-headers-5.10.0-8-rt-arm64/stable,stable-security 5.10.46-5 arm64
linux-headers-5.10.0-8-rt-armmp/stable,stable-security 5.10.46-5 armhf
linux-headers-5.10.0-9-arm64/stable,now 5.10.70-1 arm64  [Installiert,automatisch]
linux-headers-5.10.0-9-armmp-lpae/stable 5.10.70-1 armhf
linux-headers-5.10.0-9-armmp/stable 5.10.70-1 armhf
linux-headers-5.10.0-9-cloud-arm64/stable 5.10.70-1 arm64
linux-headers-5.10.0-9-common-rt/stable,stable 5.10.70-1 all
linux-headers-5.10.0-9-common/stable,stable,now 5.10.70-1 all  [Installiert,automatisch]
linux-headers-5.10.0-9-rt-arm64/stable 5.10.70-1 arm64
linux-headers-5.10.0-9-rt-armmp/stable 5.10.70-1 armhf
linux-headers-arm64/stable,now 5.10.70-1 arm64  [Installiert,automatisch]
linux-headers-armmp-lpae/stable 5.10.70-1 armhf
linux-headers-armmp/stable 5.10.70-1 armhf
linux-headers-cloud-arm64/stable 5.10.70-1 arm64
linux-headers-rt-arm64/stable 5.10.70-1 arm64
linux-headers-rt-armmp/stable 5.10.70-1 armhf

```

Hilft das ? das ist mal so gar nichts von 5.10.63...zu sehen.... bin aber auch keine Experte bei diesen Kernel sachen

**Comment by jens-maus** [comment]
Bitte mal ausgabe von `cat /etc/os-release` zeigen.

**Comment by guny74** [comment]
` cat /etc/os-release`

```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by SaschaPeter** [comment]
os-release sieht bei mir gleich aus(und bei mir läuft der Container, allerdings via docker-compose und mit Funkmodul),
kann also nicht sagen ob das Script bei mir auf einen Fehler laufen würde.
Die Ausgabe der Kernel Header sieht bei mir anders aus, keiner steht bei mir auf installiert:

sudo apt list linux-headers-*
Auflistung… Fertig
linux-headers-5.10.0-8-arm64/stable,stable-security 5.10.46-5 arm64
linux-headers-5.10.0-8-armmp-lpae/stable,stable-security 5.10.46-5 armhf
linux-headers-5.10.0-8-armmp/stable,stable-security 5.10.46-5 armhf
linux-headers-5.10.0-8-cloud-arm64/stable,stable-security 5.10.46-5 arm64
linux-headers-5.10.0-8-common-rt/stable,stable,stable-security,stable-security 5.10.46-5 all
linux-headers-5.10.0-8-common/stable,stable,stable-security,stable-security 5.10.46-5 all
linux-headers-5.10.0-8-rt-arm64/stable,stable-security 5.10.46-5 arm64
linux-headers-5.10.0-8-rt-armmp/stable,stable-security 5.10.46-5 armhf
linux-headers-5.10.0-9-arm64/stable 5.10.70-1 arm64
linux-headers-5.10.0-9-armmp-lpae/stable 5.10.70-1 armhf
linux-headers-5.10.0-9-armmp/stable 5.10.70-1 armhf
linux-headers-5.10.0-9-cloud-arm64/stable 5.10.70-1 arm64
linux-headers-5.10.0-9-common-rt/stable,stable 5.10.70-1 all
linux-headers-5.10.0-9-common/stable,stable 5.10.70-1 all
linux-headers-5.10.0-9-rt-arm64/stable 5.10.70-1 arm64
linux-headers-5.10.0-9-rt-armmp/stable 5.10.70-1 armhf
linux-headers-arm64/stable 5.10.70-1 arm64
linux-headers-armmp-lpae/stable 5.10.70-1 armhf
linux-headers-armmp/stable 5.10.70-1 armhf
linux-headers-cloud-arm64/stable 5.10.70-1 arm64
linux-headers-rt-arm64/stable 5.10.70-1 arm64
linux-headers-rt-armmp/stable 5.10.70-1 armhf

vielleicht solltest du mal schauen ob die  pivccu-modules-dkms ebenfalls so wie es ist installiert bekommst.

**Comment by guny74** [comment]
Also die  pivccu-modules-dkms hatte ich schon erfolgreich installier, ohne Fehler...habe es aber nochmal abgesetzt

 `sudo apt install pivccu-modules-dkms`

`pivccu-modules-dkms ist schon die neueste Version (1.0.68).`

Wie geschrieben: mit der "Docker pull" Variante habe ich auch einen Container zum laufen bekommen (ohne Funkmodul), aber ich bin mir halt nicht sicher, ob die anderen Anweisungen im Script ( wie z.b. die UDEV Rules (siehe oben) wichtig sind.

**Comment by SaschaPeter** [comment]
ls /lib/modules gibt bei mir nur 
5.10.63-v8+

und die Header sind dann auch über den symlink in modules unter /usr/src/linux-headers-5.10.63-v8+ zu finden

also die udev rules sind nicht zwingend erforderlich

**Comment by SaschaPeter** [comment]
Wie sieht den dein veraltetes Equipement aus, Funkmodul per USB oder GPIO?

**Comment by jens-maus** [comment]
Also ich brems euch hier ungern aus, aber ihr entfernt euch hier immer mehr von einem normalen Bug Issue-Ticket! Der gemdelete Fehler geht darüber das das "+" im apt install fehlt und damit geh ich auch konform und werd das fixen. Wenn ihr allerdings hier anfangt über eure Nutzererfahrungen zu diskutieren, dann verlagert das bitte in den Diskussionsteil auf GitHub oder ins homematic Forum. Das hier ist ein Entwicklungs-Ticketsystem und kein Diskussionsforum! Also bitte aufhören eure Problem lösen zu wollen, sondern alleinig auf den gemeldeten Inhalt konzentieren!

**Comment by guny74** [comment]
Sorry, ich möchte hier nur gerne das Script zum laufen bekommen (oder eine Alternative), um eine stabile Basis/saubere Installation zu erhalten.

**Comment by SaschaPeter** [comment]
Hatte ich weiter oben schon einmal angemerkt... @guny74 einfach ein hier gehts weiter Link und ich werde versuchen dort zu unterstützen, aber es geht auch ohne das deploy Script

**Comment by jens-maus** [comment]
> Sorry, ich möchte hier nur gerne das Script zum laufen bekommen (oder eine Alternative), um eine stabile Basis/saubere Installation zu erhalten.

Dann entwickle das `deploy.sh` Script auf deinem System so das es dort läuft und zeig die Unterschiede dazu auf oder sende einen PullRequest dann mit den Änderungen ein. Und wenn es diskussionsbedarf zur Entwicklung davon gibt mach ein diskussionsbeitrag dazu entsprechend auf. Aber das Ticketsystem nun dazu zu verwenden hier ausschweifend zu diskutieren obwohl der inhalt des issue/ticket über was anderes geht (nur ein teilproblem) ist nicht das richtig. Frei nach dem Motto: "One problem, one issue"

**Comment by guny74** [comment]
Nochmal Sorry, aber also ich wüsste nicht, wo wir abgeschweift sind...oder ich habe es nicht richtig verstanden. 

Ich habe gemeldet, dass ich bei meiner 64 bit Version bei der Installation über das Script den Fehler erhalte "`"Paket linux-headers-5.10.63-v8 kann nicht gefunden werden" `.

All meine Versuche und Diskussionen hier dienten dazu herauszufinden, ob es am Script liegt oder an der verwendeten "OS Image"/Installation. Auch "SaschaPeter"'s Bemühungen habe ich in die Richtung gedeutet, dass es darum geht, ggfs Fehler im OS zu finden. Wenn ich da hier irgendwie falsch gehandelt habe, entschuldige ich mich nochmals. 

Ich habe nur versucht ggfs selbstständig schonmal den Fehler einzukreisen.

Werde demnächst es nur melden und erstmal auf "Anweisung" warten.

Ich würde mich weiter freuen, wenn Du das Script entsprechend fixen könntest.

Vielen Dank

**Comment by guny74** [comment]
Danke, angepasstes Script hat bei mir wunderbar zur Erstinstallation funktioniert.
