### ISSUE TITLE
Empty string not written to a system variable

### ISSUE THREAD

**Issue by jp112sdl** [jens-maus/RaspberryMatic#159]
When I try to "clear" the text of a system variable of the type "Zeichenkette", nothing happens:
string a = "";
dom.GetObject("Systemvariable").State(a);

ReGa Version used: Beta 20

**Comment by jens-maus** [comment]
This bug should already be fixed in beta21 of ReGaHss which should be released soon.

**Comment by jens-maus** [comment]
beta21 has just been released. See here:
https://homematic-forum.de/forum/viewtopic.php?f=26&t=36623&p=386682#p386589
