### ISSUE TITLE
Nightly 3.61.6.20211211-e049e2 bootet nicht sauber durch wenn HB-RF-USB-2 mit RPI-RF-MOD angeschlossen ist

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1591]
### Describe the issue you are experiencing

Der heutige Nightly bootet nicht sauber durch. 
Trotz jungfräulichem Image auf frischer SD-Karte hängt der Bootvorgang irgendwie bei...
`Starting S.USV daemon:` 
Und das obwohl ich gar keine S.USV habe.
Nach dem Ausschlussverfahren habe ich alle externen Komponenten nach und nach entfernt (USB-USV, Shim-RTC, USB-SSD) und jedes mal hart rebootet. Bis hierher keine Besserung.
Der letzte Versuch war den Pi komplett "nackt" zu booten, also auch ohne HB-RF-USB-2.
Und siehe da...
`Starting S.USV daemon: no hardware found`
und das System bootete durch.

### Describe the behavior you expected

Problemloses booten mit angeschlossener HB-RF-USB-2, also wie üblich.

### Steps to reproduce the issue

1. Nightly 3.61.6.20211211-e049e2 mit angeschlossener HB-RF-USB-2 booten
2. Ausgabe am Monitor beobachten, hängt bei Starting S.USV daemon:
3.
...

### What is the version this bug report is based on?

3.61.6.20211211-e049e2 Nighly

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Pi3B+ 
RPI-RF-MOD auf HB-RF-USB-2
```

### Additional information

Komisch das versucht wird den S.USV daemon zu starten obwohl keinerlei S.USV Hardware vorhanden ist.
Könnte es was mit den neuen Treibern von @alexreinert zu tun haben?
e049e2f ?

**Comment by Baxxy13** [comment]
> ### Describe the issue you are experiencing
> Der heutige Nightly bootet nicht sauber durch. Trotz jungfräulichem Image auf frischer SD-Karte hängt der Bootvorgang irgendwie bei... `Starting S.USV daemon:` Und das obwohl ich gar keine S.USV habe. Nach dem Ausschlussverfahren habe ich alle externen Komponenten nach und nach entfernt (USB-USV, Shim-RTC, USB-SSD) und jedes mal hart rebootet. Bis hierher keine Besserung. Der letzte Versuch war den Pi komplett "nackt" zu booten, also auch ohne HB-RF-USB-TK. Und siehe da... `Starting S.USV daemon: no hardware found` und das System bootete durch.
> 
> ### Describe the behavior you expected
> Problemloses booten mit angeschlossener HB-RF-USB-TK, also wie üblich.
> 
> ### Steps to reproduce the issue
> 1. Nightly 3.61.6.20211211-e049e2 mit angeschlossener HB-RF-USB-TK booten
> 2. Ausgabe am Monitor beobachten, hängt bei Starting S.USV daemon:
> 
> ...
> 
> ### What is the version this bug report is based on?
> 3.61.6.20211211-e049e2 Nighly
> 
> ### Which base platform are you running?
> rpi3 (RaspberryPi3)
> 
> ### Which HomeMatic/homematicIP radio module are you using?
> RPI-RF-MOD
> 
> ### Anything in the logs that might be useful for us?
> ```
> Pi3B+ 
> RPI-RF-MOD auf HB-RF-USB-TK
> ```
> 
> ### Additional information
> Komisch das versucht wird den S.USV daemon zu starten obwohl keinerlei S.USV Hardware vorhanden ist.
> Könnte es was mit den neuen Treibern von @alexreinert zu tun haben?
> e049e2f75a65027a71a722b4c2f4505f5d149eb5 ?

**Comment by Baxxy13** [comment]
Habe jetzt noch ein paar Kreuztests gemacht:
RPI-RF-MOD auf HB-RF-USB-2 --> nicht ok
RPI-RF-MOD auf HB-RF-USB-TK --> ok
HM-MOD-RPI-PCB auf HB-RF-USB-2 --> ok
HM-MOD-RPI-PCB auf HB-RF-USB-TK --> ok

**Comment by jens-maus** [comment]
Ich konnte das jetzt entsprechend reproduzieren und sehe auch mit einem HB-RF-USB-2 + RPI-RF-MOD das beim Versuch die S.USV Erkennung mittels `i2cget` durchzuführen dieser Befehl leider stecken bleibt. Nachdem ich den SUSV startup skript testweise deaktiviert habe (oben einfach ein `exit 0` rein), der i2c Bus irgendwie komische Werte bringt. Siehe:

```
root@homematic-raspi:~# i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         08 09 0a 0b 0c 0d 0e 0f 
10: 10 11 12 13 14 15 16 17 18 19 1a 1b 1c 1d 1e 1f 
20: 20 21 22 23 24 25 26 27 28 29 2a 2b 2c 2d 2e 2f 
30: 30 31 32 33 34 35 36 37 38 39 3a 3b 3c 3d 3e 3f 
40: 40 41 42 43 44 45 46 47 48 49 4a 4b 4c 4d 4e 4f 
50: 50 51 52 53 54 55 56 57 58 59 5a 5b 5c 5d 5e 5f 
60: 60 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e 6f 
70: 70 71 72 73 74 75 76 77                         
```

Kannst du mal versuchen das zu reproduzieren? hier sollten eigentlich (wie ohne das HB-RF-USB-2) alles auf `00` stehen. Insofern müsste @alexreinert hier vielleicht mal überlegen ob das vom neuen `generic_raw_uart` kommen kann das mit einem rpi3 + HB-RF-USB-2 + RPI-RF-MOD der i2c bus irgendwie durcheinander kommt?!?

@Baxxy13 Und kannst du mal schauen ob das nur mit einem rpi3 passiert oder auch mit einem rpi4 oder rpi2 oder gar ova?

**Comment by alexreinert** [comment]
Auf einem Pi3 mit aktuellem Raspbian bekomme ich es nicht reprodziert. Mir fehlt da auch etwas die Phantasie, wie die Änderungen das Hervorrufen könnten, dass da Garbage mit exakt den i2c Adressen rauskommen kann. Könnte das nicht eher mit den gleichzeitig durchgeführten Kernel Updates liegen?

**Comment by alexreinert** [comment]
Was passiert denn, wenn kein oder ein altes Funkmodul aufgesteckt ist?

**Comment by Baxxy13** [comment]
Pi3B mit HB-RF-USB-2 (S.USV Startscript deaktiviert)
**ohne Funkmodul:**
```
root@homematic-raspi:~# i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```
**mit RPI-RF-MOD:**
```
root@homematic-raspi:~# i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         08 09 0a 0b 0c 0d 0e 0f
10: 10 11 12 13 14 15 16 17 18 19 1a 1b 1c 1d 1e 1f
20: 20 21 22 23 24 25 26 27 28 29 2a 2b 2c 2d 2e 2f
30: 30 31 32 33 34 35 36 37 38 39 3a 3b 3c 3d 3e 3f
40: 40 41 42 43 44 45 46 47 48 49 4a 4b 4c 4d 4e 4f
50: 50 51 52 53 54 55 56 57 58 59 5a 5b 5c 5d 5e 5f
60: 60 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e 6f
70: 70 71 72 73 74 75 76 77
```
**mit HM-MOD-RPI-PCB:**
```
root@homematic-raspi:~# i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

**Comment by Baxxy13** [comment]
**Pi2B** mit Nightly 3.61.6.20211212-99cc08 und HB-RF-USB-2 (S.USV Startscript deaktiviert)

**ohne Funkmodul:**
```
root@homematic-raspi:~# i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

**mit RPI-RF-MOD:**
- LED des Funkmoduls bleibt gelb
- System fährt nach ein paar Minuten selbständig herunter
```
root@homematic-raspi:~# i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         08 09 0a 0b 0c 0d 0e 0f
10: 10 11 12 13 14 15 16 17 18 19 1a 1b 1c 1d 1e 1f
20: 20 21 22 23 24 25 26 27 28 29 2a 2b 2c 2d 2e 2f
30: 30 31 32 33 34 35 36 37 38 39 3a 3b 3c 3d 3e 3f
40: 40 41 42 43 44 45 46 47 48 49 4a 4b 4c 4d 4e 4f
50: 50 51 52 53 54 55 56 57 58 59 5a 5b 5c 5d 5e 5f
60: 60 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e 6f
70: 70 71 72 73 74 75 76 77
```
**mit HM-MOD-RPI-PCB:**
```
root@homematic-raspi:~# i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

HA-OS AddOn --> OK
.ova --> nicht getestet
Pi4B --> nicht getestet

**Comment by Baxxy13** [comment]
Da ich hier noch ein Tinker S rumliegen hatte...
Das Teil reißt mit dem heutigen Nightly (3.61.6.20211212-99cc08-tinkerboard) und angeschlossener HB-RF-USB-2 + RPI-RF-MOD komplett während des Bootvorganges die Hufe hoch.
(Display Ausgabe weg / bunte Streifen, System LED's aus, RPI-RF-MOD LED rot)
Die Netzwerk LED's flackern noch, ssh Zugriff ist aber nicht möglich.
Kommt man nur auf die Harte Tour (Stecker ziehen) raus.

**Comment by eli4711** [comment]
Weis nicht ob es mit diesem Problem zusammen hängt, aber seit der 3.61.6.20211211-e049e2 funktionniert die Onboard LED des RPI-RF-MOD nicht mehr korrekt. Sie leuchtet durchgehend Grün, egal was an Servicemeldungen oder Alarmmeldungen ansteht. Blau leuchtet sie gar nicht mehr. Beim Update auf die 3.61.6.20211212 hat die LED dann den Updateprozess korrekt mit einem Violetten blinken angezeigt, aber danach ist sie wieder durchgehend Grün.

Testumgebung : HB-RF-USB-2 + RPI-RF-MOD + Intel Nuc NUC6CAYB

**Comment by alexreinert** [comment]
Ich habe das Problem möglicherweise gefunden, könnte ein Copy&Waste Fehler sein, ich schaue, dass ich nachher noch ein Update rausbringe.

**Comment by SaschaPeter** [comment]
pivccu-modules-dkms 1.0.70 hat bei mir die LED wieder unter Kontrolle gebracht, hoffe es gehört hier her, aber ein gewisser Zusammenhang bestand ja. Achso, es funktioniert bei mir mit 3.61.6.20211212 unter Docker.

Danke Alex.

**Comment by Baxxy13** [comment]
Kurze Rückmeldung:
Mit den aktualisierten Treibern (generic_raw_uart 1.11) startet der heutige Nightly auf einem Pi3B+ mit HB-RF-USB-2 + RPI-RF-MOD wieder problemlos.

**Comment by jens-maus** [comment]
Ok, kann nun selbst bestätigen das mit dem 1.11 des generic_raw_uart (4e9704cb04c9ca91e246a36c462555da17d1f8a6 ) alles wieder sowas funktioniert. Danke @alexreinert
