### ISSUE TITLE
ssh kann bei frischem System (Nightly-Snapshot) nicht sauber über die WebUI aktiviert werden

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1593]
### Describe the issue you are experiencing

Eine meiner ersten Aktionen nach dem Boot eines frischen Systems ist es, den ssh Zugang über die WebUI zu aktivieren.
Bei den letzten Nightly's hakt es da gewaltig, genauer gesagt die Seite friert ein und man kommt nur mit einem Seiten-Reload wieder raus. Das passiert beim aktivieren und deaktivieren.

### Describe the behavior you expected

Problemloses aktivieren / deaktivieren des ssh - Zugangs über die WebUI

### Steps to reproduce the issue

1. frisches System booten und die Ersteinrichtung erledigen
2. ssh Zugang aktivieren und Passwörter eintippen
3. Speichern klicken und abwarten
...

### What is the version this bug report is based on?

3.61.6.20211211-e049e2 Nighly (Pi3) und 3.61.6.20211212-99cc08 (Pi2)

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
-
```

### Additional information

![RM_save_ssh_settings](https://user-images.githubusercontent.com/54898249/145706246-6fb10e44-9ce7-4359-aa12-e646479abe61.JPG)

Aufgefallen ist folgendes:
Das ssh Passwort wird instant geändert (lokal auf der Konsole des Pi getestet) aber der ssh-Fernzugriff bleibt deaktiviert.
Ein Reboot des Systems aktiviert dann auch den ssh-Fernzugriff.
Pauschal würde ich sagen irgendwas  kann nicht korrekt geschrieben werden, denn beim 1.Reboot sieht man:
```
Starting ssdpd: OK
cp: can't stat '/usr/local/etc/ssh_host_*_key*' : No such file or directory
ssh-keygen: generating new host keys: RSA DSA ECDSA ED25519
```
Das habe ich früher noch nie so gesehen.

**Comment by jens-maus** [comment]
Kannst du mal schauen was beim ersten komplett frischen start ausgegeben wird? Normalerweise sollten die SSH keys auch ohne aktiviertem SSH bereits beim ersten start generiert werden. Ich denke das sollte der Grund sein warum die WebUI hängen bleibt beim ersten aktivieren - weil eben das generieren der keys sehr lange dauern kann und das dann zu einem Timeout führt wenn das das erste mal bei der WebUI passiert.

**Comment by jens-maus** [comment]
Ok, ist doch nicht so das die SSH keys in jedem fall angelegt werden. Da hatte ich mich geirrt. Dann muss ich mir das anschauen warum das WebUI da in einen Timeout rennt. Das liest sich in der Tat komisch. Bekommst du das in einer ova Umgebung reproduziert.

**Comment by jens-maus** [comment]
Also ich kann das selbst auch unter ova reproduzieren. Werd ich mir entsprechend dann mal zeitnah anschauen.

**Comment by Baxxy13** [comment]
Wollte gerade rückmelden das es auch mit .ova reproduzierbar ist.

**Comment by jens-maus** [comment]
Kannst du rausfinden mit welchem nightly das problem das erste mal auftritt?

**Comment by Baxxy13** [comment]
Puhh, ich habe zwar paar Nightlys für Pi3 rumliegen aber das dauert ewig. Die .ova wäre hier ideal zum testen aber die habe ich nicht weil ich die vorab Tests nur noch mit HA-AddOn mache. 
Wenn du den Zeitraum eingrenzen könntest würde das helfen.

**Comment by Baxxy13** [comment]
Irgendwo zwischen dem letzten Release 3.61.5.20211113
und dem Nightly 3.61.5.20211124.

Weiter eingrenzen kann ich es mangels vorhandener Nightlys nicht.

**Comment by jens-maus** [comment]
@Baxxy13 Ok, ich denke ich hab das Problem gefunden (siehe 9b0e60c). D.h. mit dem nächsten nightly build sollte sich SSH wieder problemlos an/ausschalten lassen via WebUI. Bitte dann entsprechend testen morgen und noch einmal zurückmelden.

**Comment by SaschaPeter** [comment]
Unter Docker, wenn gleich nicht das selbe Verhalten bzgl. Passwort, läuft es jetzt wieder. Danke

**Comment by Baxxy13** [comment]
So, der Test mit dem heutigen Nightly zeigte keine Auffälligkeiten.
ssh lässt sich wieder problemlos über die WebUI (de-) aktivieren.
Sehr gut!
