### ISSUE TITLE
Not possible to "teach-in" HmIP-MOD-OC8

### ISSUE THREAD

**Issue by itchy3344** [jens-maus/RaspberryMatic#1597]
### Describe the issue you are experiencing

I have two HMIP-MOD-OC8 (8-Kanal-Empfangsmodul) that I want to train on the RaspberryMatic. Both fail the teach-in process. 

In the past, they used to work with RaspberryMatic and Homematic CCU3 (cannot test the latter anymore, as no CCU3 is available). It appears to me that the device fails to bind on a newer Raspberrymatic

### Describe the behavior you expected

The Teach-in process should find the devices. 

### Steps to reproduce the issue

1. factory reset of the HMip-MOD-OC8
2. starting the teach-in process on the RaspberryMatic

### What is the version this bug report is based on?

3.61.5.20211113

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
.
```

### Additional information

Manual binding (without internet connection) doesn't work either.

**Comment by Baxxy13** [comment]
The Raspberry Pi4B has strong radio interference capatibilitys especially for HmIP. 
If your HM-MOD-RPI-PCB is connected directly to GPIO, then interferences are programmed.
Do not use the USB3 ports of the Pi4B and if possible put your RF-Module at least 50cm away from the Pi4B.
Use a GPIO extension cable or better the HB-RF-USB-2 or HB-RF-ETH.  
Tipps for using the Pi4B as Homematic-Central in the Homematic-Forum (in german) [>here<](https://homematic-forum.de/forum/viewtopic.php?f=31&t=65293)
