### ISSUE TITLE
Felder $val$, $this$ und $src$ beim Execute innerhalb des Programm-Editors ohne Funktion

### ISSUE THREAD

**Issue by Maik2208** [jens-maus/RaspberryMatic#1599]
### Describe the issue you are experiencing

Ich möchte nochmal an den Issues https://github.com/jens-maus/RaspberryMatic/issues/764 erinnern.
Die Felder $val$, $this$ und $src$ funktionieren nicht, im Scripteditor auf Execute klickt.

Dies ist ein sehr schlechter Umstand, wenn man Scripte testen möchte.

### Describe the behavior you expected

Es soll möglich sein, dass mein im Feld $src$ die interne ID des auslösenden Gerätes manuell eingeben kann um das Script testen zu können ohne immer die Hardware betätigen zu müssen.

### Steps to reproduce the issue

1. Programm anlegen
2. Script hinzufügen und $src$ darin nutzen
3. Interne ID bei $src$ eingeben und execute klicken.

### What is the version this bug report is based on?

3.61.5.20211113

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
keine
```

**Comment by jens-maus** [comment]
> Ich möchte nochmal an den Issues #764 erinnern.

Tut mir leid, aber so läuft das nicht. Wenn du denkst, das das ein issue ist das weiter bearbeitet werden sollte, dann kommentiere in dem alten Ticket und öffne nicht ein neues Ticket. Insofern ist das hier ein duplicate und gehört geschlossen.

**Comment by jens-maus** [comment]
Duplicate of #764
