### ISSUE TITLE
Ferhlermeldung "No IP address set", kein root login möglich

### ISSUE THREAD

**Issue by Robomate** [jens-maus/RaspberryMatic#160]
am Ende des Bootvorgangs: erscheint die Ferhlermeldung "No IP address set"

dann versucht mit ALT+F2 , danach Enter als root ohne passwort einzuloggen klappt nicht!!!

was muss ich also eingeben , um mich einzuloggen?

Problem siehe hier:
https://homematic-forum.de/forum/viewtopic.php?t=37648

**Comment by jens-maus** [comment]
Kommt drauf an ob vorher bereits ein vollwertiges RaspberryMatic drauf gelaufen ist bzw. was vorher in der WebUI vor Umstellung in den LAN gateway modus als SSH Passwort eingetragen wurde.

Bitte beachten das dies hier kein Support Forum ist. Es handelt sich hier um keinen Bug sondern um eine Fehlbedienung bzw. Problem das bitte besser weiter im Forum diskutiert gehört. Auch sehe ich nicht was die Frage mit dem referenzierten Beitrag zu tun hat. Dort geht/ging es inhaltlich ja um ein anderes Problem.

**Comment by Robomate** [comment]
wenn zum ersten Mal geflasht wurde und vorher formatiert wurde? der pi wird auch nicht im per lan im netz erkannt. gerade nochmal andere pis mit anderen images getestet, klappt dort problemlos.

**Comment by jens-maus** [comment]
Ich vermute Win32DiskImager verwendet?!? Dann mal gegen etcher (http://ethcher.io)

**Comment by dominikandreas** [comment]
wie richtet man das ganze denn dann auf einem pi zero ein? ohne default pw kann man sich nicht einloggen und ohne wlan kein pw setzen..

**Comment by GitTomahawk** [comment]
Ich habe das gleiche problem - wie soll ich auf dem zero w die wlan Zugangsdaten einrichten, wenn ich mich nicht anmelden kann?
Die wpa-supplicant.conf auf dem rootfs der sd zu editieren bringt scheinbar nix.
