### ISSUE TITLE
Es ist kein Ventilöffnungsgrad über 1 möglich

### ISSUE THREAD

**Issue by je-bor** [jens-maus/RaspberryMatic#1600]
### Describe the issue you are experiencing

Hallo  benutze eine CCU3 mit RaspberryMatic ,
ich wollte ein Programm erstellen wenn das Thermostat ein gewissen Ventilöffnungsgrad hat, die Heizungspumpe eingeschaltet wird.
Leider habe ich mit bedauern feststellen müssen das kein Wert über 1 eingegeben werden kann.
Belasse ich den Wert auf 1 reagiert das Programm aber auch nicht.
Bei meinem Fußbodenheizungprogramm funktioniert dies hervorragend.
Ich hoffe ihr könnt mir helfen, oder habe ich einen Denkfehler!?
Vielen Dank!
![Unbenannt](https://user-images.githubusercontent.com/85819637/146644334-11ced231-9b32-41e6-9418-34fbdbb4bc72.PNG)

### Describe the behavior you expected

siehe oben

### Steps to reproduce the issue

1.
2.
3.
...

### What is the version this bug report is based on?

3.61.5.20211113

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
nein
```

**Comment by Baxxy13** [comment]
Das ist kein Bug sondern per default so.
Du musst nur umrechnen. Willst du größer 25% gibst du größer 0.25 ein.

**Comment by jens-maus** [comment]
Genau so ist es und insofern ist das folglich auch kein Bug/Issue in RaspberryMatic.

**Comment by je-bor** [comment]
Okay Danke Euch sehr!!!!!!
Ihr seit meine Helden!!!!!
!!!!!!!!!!!!!!!!!!!!Ich wünsche Euch schöne und ruhige Festtage!!!!!!!!!!
