### ISSUE TITLE
Home Assistant - new version 3.61.7.20211218

### ISSUE THREAD

**Issue by hklages** [jens-maus/RaspberryMatic#1602]
### Describe the issue you are experiencing

After updating the Raspberrymatic container the new version is: 
3.61.7.20211218
but system shows that a new version 
3.61.5.20211113 available)
is available. 

### Describe the behavior you expected

obvious

### Steps to reproduce the issue

1. Using the Home Assistant build in function to update container
![update ](https://user-images.githubusercontent.com/17273119/146654318-d62b2b27-8db3-4959-8a82-c8b7fc777d4f.jpg)

### What is the version this bug report is based on?

3.61.7.20211218

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
no
```

### Additional information

Home Assistant does not show the update information - only inside the container, in Raspberrymatic / CCU update screen and on the home screen.

Low priority - I can live with it - just for your information because it might confuse others.

**Comment by jens-maus** [comment]
This is just a caching issue. Wait a few hours and it will be gone. Normal for early adopters.
