### ISSUE TITLE
hb_rf_eth module missing

### ISSUE THREAD

**Issue by ralfruether** [jens-maus/RaspberryMatic#1605]
### Describe the issue you are experiencing

hb_rf_eth not working after update to RaspberryMatic 3.61.7.20211218. 
Seems that driver module is missing, since also directories like /sys/module/hb_rf_eth/parameters/connect are not available.

### Describe the behavior you expected

Connection to hb_rf_eth should work like before.

### Steps to reproduce the issue

1. Update to newest version
2. try to connect hb_rf_eth

### What is the version this bug report is based on?

3.61.7.20211218

### Which base platform are you running?

oci (Open Container Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
modprobe: can't load module hb_rf_eth (updates/dkms/hb_rf_eth.ko): Invalid argument
/etc/init.d/S47InitRFHardware: line 58: can't create /sys/module/hb_rf_eth/parameters/connect: nonexistent directory
```

**Comment by jens-maus** [comment]
As you are using a docker/oci environment: the kernel drivers for the hb_rf_eth and others are not included in RaspberryMatic itself, but are part of the pivccu  dkms kernel packages you have to install separately (or which `deploy.sh` will install upon execution). So please make sure to have all necessary dependencies installed on your hist system and check the documentation here: https://github.com/jens-maus/RaspberryMatic/wiki/Installation-Docker-OCI

**Comment by ralfruether** [comment]
Well, I was using it successfully since a few month, until I have updated to the new release this morning. 
pivccu-modules-dkms is installed in version 1.0.68.

Have you been able to test it successfully before releasing the new version?

**Comment by ralfruether** [comment]
Figured out that my system also has updated pivccu-modules-dkms. The connection works again, after reverting back to 1.0.64.
