### ISSUE TITLE
WatchDog Alarme bezüglich eth0 auf Pi3B+ beim Zentralen-Update mittels "Direkt auf CCU laden und installieren"

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1606]
### Describe the issue you are experiencing

Beim heutigen Zentralen-Update meiner beiden Pi3B+ Testsysteme mittels "Direkt auf CCU laden und installieren" fiel mir auf das diese schon während des Hintergrund-Downloads Alarmmeldungen erzeugen.
Also habe ich den finalen Installationsschritt abgebrochen und mal geschaut.

Syslog:
```
Dec 19 12:05:36 RM-Test-Pi3Bplus-27 user.err monit[1540]: 'eth0' 330 download errors detected
Dec 19 12:05:36 RM-Test-Pi3Bplus-27 user.info monit[1540]: 'eth0' trying to restart
Dec 19 12:05:55 RM-Test-Pi3Bplus-27 user.err monit[1540]: 'eth0' service restarted 1 times within 1 cycles(s) - exec
Dec 19 12:05:55 RM-Test-Pi3Bplus-27 user.info monit[1540]: 'eth0' exec: '/bin/triggerAlarm.tcl eth0 interface: link down WatchDog: eth0-down true'
Dec 19 12:05:55 RM-Test-Pi3Bplus-27 user.info monit[1540]: 'eth0' link up
Dec 19 12:05:55 RM-Test-Pi3Bplus-27 user.err monit[1540]: 'eth0' link mode is now full-duplex
Dec 19 12:05:55 RM-Test-Pi3Bplus-27 user.info monit[1540]: 'eth0' exec: '/bin/triggerAlarm.tcl eth0 interface: link speed changed WatchDog: eth0-speed true'
Dec 19 12:05:55 RM-Test-Pi3Bplus-27 user.err monit[1540]: 'eth0' link speed changed to 1000 Mb/s
Dec 19 12:05:55 RM-Test-Pi3Bplus-27 user.info monit[1540]: 'eth0' exec: '/bin/triggerAlarm.tcl eth0 interface: link speed changed WatchDog: eth0-speed true'
Dec 19 12:06:15 RM-Test-Pi3Bplus-27 user.info monit[1540]: 'eth0' link mode has not changed since last cycle [current mode is full-duplex]
```
Screenshot:
![Watchdog_ETH_pi3bp](https://user-images.githubusercontent.com/54898249/146673074-e6525184-9b25-4492-bb94-305434b330a7.JPG)

Das lässt sich bei meinen beiden Pi3B+ (1x SD-Boot; 1x SSD-Boot) jedes mal reproduzieren wenn die Software über  "Direkt auf CCU laden und installieren" z.B. einfach drüberinstalliert werden soll.

### Describe the behavior you expected

Idealerweise sollte auch der Pi3B+ über "Direkt auf CCU laden und installieren" ohne Alarmmeldungen geupdated werden können.

### Steps to reproduce the issue

1. auf einem Pi3B+ mittels "Direkt auf CCU laden und installieren" das Update initialisieren
2. das Update abbrechen (letztes Fenster auf "zurück")
3. Alarmmeldungen und Syslog kontrollieren
...

### What is the version this bug report is based on?

3.61.7.20211218

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Dec 19 12:05:36 RM-Test-Pi3Bplus-27 user.err monit[1540]: 'eth0' 330 download errors detected
Dec 19 12:05:36 RM-Test-Pi3Bplus-27 user.info monit[1540]: 'eth0' trying to restart
Dec 19 12:05:55 RM-Test-Pi3Bplus-27 user.err monit[1540]: 'eth0' service restarted 1 times within 1 cycles(s) - exec
Dec 19 12:05:55 RM-Test-Pi3Bplus-27 user.info monit[1540]: 'eth0' exec: '/bin/triggerAlarm.tcl eth0 interface: link down WatchDog: eth0-down true'
Dec 19 12:05:55 RM-Test-Pi3Bplus-27 user.info monit[1540]: 'eth0' link up
Dec 19 12:05:55 RM-Test-Pi3Bplus-27 user.err monit[1540]: 'eth0' link mode is now full-duplex
Dec 19 12:05:55 RM-Test-Pi3Bplus-27 user.info monit[1540]: 'eth0' exec: '/bin/triggerAlarm.tcl eth0 interface: link speed changed WatchDog: eth0-speed true'
Dec 19 12:05:55 RM-Test-Pi3Bplus-27 user.err monit[1540]: 'eth0' link speed changed to 1000 Mb/s
Dec 19 12:05:55 RM-Test-Pi3Bplus-27 user.info monit[1540]: 'eth0' exec: '/bin/triggerAlarm.tcl eth0 interface: link speed changed WatchDog: eth0-speed true'
Dec 19 12:06:15 RM-Test-Pi3Bplus-27 user.info monit[1540]: 'eth0' link mode has not changed since last cycle [current mode is full-duplex]
```

### Additional information

Trotz der Alarmmeldungen werden die Pi3B+ Systeme mittels "Direkt auf CCU laden und installieren" problemlos geupdatet.
Es betrifft nur Pi3B+, bei getesteten Pi3B & Pi4B gibt es keine Alarmmeldungen.
Da ich normalerweise nur per Download / Upload update (geht ja mit den Nightly's nicht anders) ist mir das bisher noch nicht aufgefallen.

Funktionale Einschränkungen gibt es nicht, aber die rot blinkende RPI-RF-MOD LED bei Start des Update-Vorganges stiftet doch etwas Verwirrung.

**Comment by jens-maus** [comment]
> `Dec 19 12:05:36 RM-Test-Pi3Bplus-27 user.err monit[1540]: 'eth0' 330 download errors detected``

Das wird vmtl. die ursächliche Meldung für das darauf folgende neu initalisieren der Netzwerk-Interfaces sein. Hier müsstest du ggf. das nochmal versuchen zu reproduzieren bzw. auch ggf. durch andere Netzwerktests (z.B. scp transfer großer daten) verifizieren das das nicht ein generelles Netzwerk-Interface Problem der Pi3B+ ist. Hier ggf. z.b. den Befehl `ifconfig` nutzen um zu schauen ob die Anzahl der `errors` bzw. `overruns` unter `RX packets" bzw. `TX packets` groß wird bzw. kontinuierlich steigt bei starkem netzwerk transfer.

**Comment by Baxxy13** [comment]
Ok, ich kann hier gerne weiter testen. 
Bräuchte aber Schützenhilfe da ich nicht so reicht weiß wie ich konkret vorgehen muss.

Was ich schonmal sagen kann, wenn ich über das rmupdate-AddOn update, kommen auch die Watchdog-Alarme sowie die gleichen Meldungen im Syslog. Scheint also wirklich am Netzwerk-Interface des Pi3B+ zu liegen.

**Comment by Baxxy13** [comment]
Hier mal paar Ausgaben von `ifconfig`

Pi3B+ am Gigabit Switch
frisch nach Reboot:

```
eth0      Link encap:Ethernet  HWaddr B8:27:EB:B9:99:91
          RX packets:1186 errors:0 dropped:344 overruns:0 frame:0
          TX packets:651 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:188166 (183.7 KiB)  TX bytes:131920 (128.8 KiB)
```
und nach dem Download der Firmware über die WebUI:
```
eth0      Link encap:Ethernet  HWaddr B8:27:EB:B9:99:91
          RX packets:289632 errors:17944 dropped:402 overruns:0 frame:17944
          TX packets:55087 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:291061390 (277.5 MiB)  TX bytes:3602127 (3.4 MiB)
```

Die Errors bei RX gehen da ziemlich hoch.

Pi3B+ am 100Mbit Switch
nach dem Download der Firmware über die WebUI:
```
eth0      Link encap:Ethernet  HWaddr B8:27:EB:B9:99:91
          RX packets:289143 errors:91 dropped:155 overruns:0 frame:91
          TX packets:119467 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:290956586 (277.4 MiB)  TX bytes:7256134 (6.9 MiB)
```

Immer noch Errors, aber weit weniger.

Gegentest direkt an der Fritzbox mit GBit / 100MBit brachte ähnliche Ergebnisse.
Gegentest mit Tinkerboard-S, denselben LAN Kabeln und Anschlüssen brachte 0 Errors.

Also doch irgendwas mit dem Netzwerk des Pi3B+

**Comment by jens-maus** [comment]
Also ich bekomme hier das Problem in der Tat auch mit einem RaspberryPi3b+ reproduziert. Folgender Befehl reicht wohl schon dazu, die Anzahl der RX `errors:` so hochzutreiben, das im Anschluss der `monit` Watchdog der Meinung ist hier eine Fehlermeldung auszugeben:

```
wget -4 -c -O /dev/null https://github.com/jens-maus/RaspberryMatic/releases/download/3.61.7.20211218/RaspberryMatic-3.61.7.20211218-rpi3.zip
```

Interessanterweise passiert das aber nicht, wenn ich mit weitaus größeren Bandbreiten innerhalb des lokalen Netzwerkes (z.B. via scp) die gleiche Datei auf den Pi3b+ transferiere. Auch sei erwähnt, das eine gewisse Anzahl von errors nicht automatisch als schlimm einzuordnen ist. Interessant ist dieses Verhalten jedoch allemal und die Frage ist schon warum das nur bei einem PI3b+ passiert und auch nur wenn die Datei bei github liegt? Denn ich hab die selbe Datei mal auf einen anderen Server im Internet transferiert und den gleichen `wget` Befehl drauf losgelassen und dort kommt es zu keinerlei erhöhung der RX errors?!?

Vielleicht ist monit hier auch nur etwas zu empfindlich was die Erkennung der "download error" angeht oder es startet von sich aus zu früh den neustart des eth0 interfaces. Und leider habe ich bis jetzt noch keine Konfigurationsmöglichkeit für diese "download errors" in monit gefunden.

**Comment by Baxxy13** [comment]
Kurios ist das schon das der Pi3B+ bei Github Downloads so viele Errors generiert. Irgendwie fehlt mir da der Zusammenhang.
Etwas Recherche im Netz brachte erstmal keine nützlichen Erkenntnisse. 
Schlechte Stromversorgung war irgendwo zu lesen. Das kann ich zwar nicht 100%ig ausschließen, denke aber das die Pi4 Netzteile die ich nutze ausreichend für nen nackten Pi3B+ sind.
Die ganzen andern Pi3 / Pi4 die hier so rumschwirren erzeugen 0 Errors.
