### ISSUE TITLE
Anzeige der Zentralen-Hardware-Plattform im oberen Bereich von Einstellungen > Systemsteuerung > Zentralen-Wartung

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1607]
### Describe the solution you'd like

Da ich die Nightly's auf diversen Systemen teste kam es schon ab und zu vor das ich aus Versehen die falsche Version (bezüglich des Hardware Unterbaus) auf dem Testsystem installieren wollte.
Es passiert zwar im Endeffekt nix weil das System dann wegen inkorrekter Hardware im Recovery hängen bleibt, aber da muss man auch erstmal dran denken. Außerdem geht dann unnütz Zeit verloren.

Daher wäre es schön direkt zu sehen welchen Hardware-Unterbau man hat. Das könnte dann beispielhaft so aussehen:
![tempsnip_1](https://user-images.githubusercontent.com/54898249/146675449-cc30c4a6-1e80-4ead-9c69-8a92bd42ed33.jpg)

### Describe alternatives you've considered

Noch besser wäre natürlich wenn gleich beim Upload auf die korrekte (Hardware-)Version geprüft und bei Nichtübereinstimmung abgebrochen wird.

### Is your feature request related to a problem?

-

**Comment by jens-maus** [comment]
> Es passiert zwar im Endeffekt nix weil das System dann wegen inkorrekter Hardware im Recovery hängen bleibt, aber da muss man auch erstmal dran denken. Außerdem geht dann unnütz Zeit verloren.

Wenn man wirklich vorab (d.h. im Hauptsystem) die Korrektheit der Hardwareplatform abtesten möchte, müsste RaspberryMatic das `*.zip` Archiv ja auch direkt auspacken und dann dort versuchen die Platformanalyse genauso noch einmal stattfinden zu lassen wie das beim anwenden des Firmware-Updates innerhalb des Recovery-Systems ja stattfindet. Und das würde nur unnötig Zeit benötigen und ggf. erneut zu irgendwelchen Timeouts im Hauptsystem führen. Genau deshalb hab ich mich damals dagegen entschieden.

Und das man die zugrundelegende Hardwareplatform irgendwo noch vermerkt, darüber kann man natürlich nachdenken. Aber vllt. wäre das ja besser in dem von @jp112sdl angedachten PR #1604 auf der Infoseite aufgehoben?

**Comment by Baxxy13** [comment]
Die Vorab-Prüfung beim Upload war nur so ein Gedankenspiel. 
Ist schon klar das das zu aufwendig ist das Image im Archiv zu prüfen. Ich dachte auch eher an nen einfachen String-Vergleich mit dem Namen des Archiv's,  also... 
```
-rpi3.zip = Pi3
-tinkerboard.zip = Tinker   
```
Ist natürlich auch nicht 100%ig sicher.



> Aber vllt. wäre das ja besser in dem von @jp112sdl angedachten PR #1604 auf der Infoseite aufgehoben?

Na schauen wir dann mal. Ich fand die von mir gezeigte Stelle eigentlich ganz passend für diese Information.
