### ISSUE TITLE
Diskrepanz zwischen ReGa Metadaten und XMLRPC Abfrage bei BidCos Geräten

### ISSUE THREAD

**Issue by jp112sdl** [jens-maus/RaspberryMatic#1608]
### Describe the issue you are experiencing

Die Abfrage der Interface-Adresse eines Geräts über die ReGa-Metadaten liefert ein anderes Ergebnis als die XML-RPC Methode `getDeviceDescription`.

```
var device = dom.GetObject(ID_DEVICES).Get("Bodenfeuchtesensor");
string metaData = device.MetaData("DEVDESC");
WriteLine(metaData);

WriteLine("---");

string out;
system.Exec("echo 'load tclrpc.so; puts [xmlrpc http://127.0.0.1:2001/ getDeviceDescription [list string \"JPCAPM0001\"] ]'|tclsh", &out);
WriteLine(out);
```

liefert
```
[ADDRESS:"JPCAPM0001",CHILDREN:{"JPCAPM0001:0","JPCAPM0001:1","JPCAPM0001:2"},FIRMWARE:"1.0",FLAGS:1,INTERFACE:"OEQ0305586",PARAMSETS:{"MASTER"},PARENT:"",RF_ADDRESS:15929857,ROAMING:0,RX_MODE:28,TYPE:"HB-UNI-Sen-CAP-MOIST-T",UPDATABLE:1,VERSION:2]
---
ADDRESS JPCAPM0001 CHILDREN {JPCAPM0001:0 JPCAPM0001:1 JPCAPM0001:2} FIRMWARE 1.0 FLAGS 1 INTERFACE RPI4GW0001 PARAMSETS MASTER PARENT {} RF_ADDRESS 15929857 ROAMING 0 RX_MODE 28 TYPE HB-UNI-Sen-CAP-MOIST-T UPDATABLE 1 VERSION 2
```

- Metadaten: **INTERFACE:"OEQ0305586"** _(Adresse des lokalen Funkmoduls)_
- XMLRPC: **INTERFACE RPI4GW0001** _(Adresse des Gateways)_

**Das Ergebnis aus der XML-RPC Abfrage ist das tatsächliche/verwendete Interface!**

### Describe the behavior you expected

ReGa Metadaten liefern das selbe Ergebnis wie das XML-RPC Pendant

### Steps to reproduce the issue

1. Gerät anlernen
2. Gerät einem Gateway zuweisen
3. o.g. Abfrage ausführen

### What is the version this bug report is based on?

3.61.5.20211128

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Nö
```

**Comment by jens-maus** [comment]
Danke für den Hinweis. Die Frage wäre nur welche praktische Relevant bzw. Unterschied das hat ob nun an dieser stelle das `INTERFACE` bei den `DEVDESC` Metadaten unterschiedlich ist zu dem was der xmlrpc server des `rfd` direkt zurückgibt? Und wie steht es mit HmIP an dieser Stelle?

**Comment by jp112sdl** [comment]
> praktische Relevant 

**Stand gestern Abend:**

Ich bin gerade dabei, in der Geräteliste in der Spalte "Interface/Kategorie" anzuzeigen, ob ein Gerät einem Gateway zugeordnet ist.
<img width="436" alt="Bildschirmfoto 2021-12-20 um 08 50 08" src="https://user-images.githubusercontent.com/18190139/146731365-7fa14cad-01b1-4270-910b-fd3755311ec2.png">

Der (Um)Weg über die unfilterbare Seite Systemsteuerung->Gatewayzuordnung ist mir zu umständlich.
Zudem kann man dort nicht filtern


Die Abfrage eines jeden Geräts in der Geräteliste mittels XMLRPC dauert ein Vielfaches länger als die Abfrage über die Metadaten.

Asynchrones (Nach)Laden, wie die RSSI-Werte, ist dabei auch unschön und hakelig.


**Stand heute:**
Nachdem ich mich noch mal intensiver mit der Gateway-Konfigurations-Seite auseinandergesetzt habe, bin ich auf die 
https://github.com/eq-3/occu/blob/master/WebUI/www/api/methods/interface/listdevices.tcl
gestoßen.
Dort bekommt man auch das zugeordnete Interface zurück.

Insofern ist das Ticket hier aus meiner Sicht erstmal _low prio_ oder kann auch ganz und gar geschlossen werden.
