### ISSUE TITLE
Hardware Support for OrangePi board

### ISSUE THREAD

**Issue by schneidy76** [jens-maus/RaspberryMatic#161]
Es wäre super wenn Raspberrymatic auch den OPI unterstützen würde. Noch besser ein direkter iobroker Support mit dem OPI

**Comment by jens-maus** [comment]
Für Hardwarespenden bin ich prinzipiell immer offen :) Ob dann aber zeitnah support für den OrangePi rauskommt ist natürlich eine andere Frage. ;)

**Comment by schneidy76** [comment]
Der OPI plus 2 (e) ist echt super. ioBroker mit einer recht umfangreichen Installation rennt echt super schnell mit den 2GB und der MMC.

Das wäre eine super Bereicherung

 

Von: Jens Maus [mailto:notifications@github.com] 
Gesendet: Montag, 2. Oktober 2017 17:56
An: jens-maus/RaspberryMatic <RaspberryMatic@noreply.github.com>
Cc: Torsten Schneider <schneidy76@web.de>; Author <author@noreply.github.com>
Betreff: Re: [jens-maus/RaspberryMatic] Hardware Support für OrangePi (#161)

 

Für Hardwarespenden bin ich prinzipiell immer offen :) Ob dann aber zeitnah support für den OrangePi rauskommt ist natürlich eine andere Frage. ;)

**Comment by jens-maus** [comment]
Das zweifelt ja auch keiner an, allerdings muss man 1. erst einmal die Hardware haben und 2. zeit für die Implementierung haben. Wie gesagt, Hardware-Spenden sind immer willkommen und steigern die Wahrscheinlichkeit einer Umsetzung ungemein.

**Comment by jens-maus** [comment]
Sorry, but OrangePi support will not be worked on. Use Tinkerboard or RaspberryPi which are perfect matches.
