### ISSUE TITLE
HmIP-RFUSB für HmIP und HM?

### ISSUE THREAD

**Issue by timwegenerDE** [jens-maus/RaspberryMatic#1610]
### Describe the issue you are experiencing

Laut Wiki unterstützt der HmIP-RFUSB sowohl IP als auch nicht IP Geräte:
https://github.com/jens-maus/RaspberryMatic/wiki/Einleitung#voraussetzungen

Laut diverser Bewertungen und Foren Einträgen ist dies jedoch nicht der Fall. So z.B. hier: https://homematic-forum.de/forum/viewtopic.php?t=54796 in der Antwort von @jens-maus

### Describe the behavior you expected

Wiki korrigieren oder ein Hinweis, dass der Stick jetzt doch geht.

### Steps to reproduce the issue

1.
2.
3.
...

### What is the version this bug report is based on?

Wiki

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
-
```

**Comment by jens-maus** [comment]
Wenn du es nicht bekommen hast: Seit der vor ein paar Tagen freigegebenen 3.61.7.20211218 kann der HmIP-RFUSB beide Welten (BidCos+HmIP) bedienen. Insofern ist der Wiki hier vollkommen richtig!

Es steht dir natürlich vollkommen frei selbst entsprechende Hinweise in den verschiedenen alten Forenbeiträge im HomeMatic Forum nun unterzubringen, dass der RFUSB Stick nun doch durch das neue FirmwareUpdate BidCos+HmIP sprechen kann. Der Wiki liegt hier auf jedenfall richtig!

**Comment by hennedo** [comment]
Ich hoffe, es ist ok wenn ich mich hier nochmal kurz dranhänge...
Ich habe eine frische Installation von Heute (docker unter linux) und einen nigelnagelneuen HmIP-RFUSB Stick, Version von RaspberryMatic ist 3.61.7.20211218 und der Stick hat die Firmware 4.4.16
<img width="2050" alt="Screenshot 2021-12-22 at 01 23 20" src="https://user-images.githubusercontent.com/2435091/147014612-9d0e5685-e410-4139-8a9c-01a6fc30de28.png">

Wenn ich auf Geräte anlernen klicke, habe ich aber nur die Auswahl für HomematicIP. Was mache ich falsch?
<img width="962" alt="Screenshot 2021-12-22 at 01 26 26" src="https://user-images.githubusercontent.com/2435091/147014694-bc69d29e-dc98-4631-8808-c205d08d3c60.png">

Startup Log von dem Docker Container:
```
Identifying onboard hardware: oci, OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Starting logging: OK
Populating /dev using udev: done
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.31.4.2, OK
Identifying Homematic RF-Hardware: ....HmRF: none, HmIP: HMIP-RFUSB/USB, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: 4.4.16, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: not required
Starting rfd: no BidCos-RF hardware found
Starting HMIPServer: .......OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
```

**Comment by jens-maus** [comment]
Bitte Inhalt der `/var/hm_mode` hier zeigen.

**Comment by hennedo** [comment]
```
henne@server:~$ docker exec -it ccu /bin/sh
/ # cat /var/hm_mode
HM_HMIP_ADDRESS='0xB5B1ED'
HM_HMIP_ADDRESS_ACTIVE='0xB5B1ED'
HM_HMIP_DEV='HMIP-RFUSB'
HM_HMIP_DEVNODE='/dev/ttyUSB0'
HM_HMIP_DEVTYPE='USB'
HM_HMIP_SERIAL='----------'
HM_HMIP_SGTIN='----------------------------'
HM_HMIP_VERSION='4.4.16'
HM_HMRF_ADDRESS=''
HM_HMRF_ADDRESS_ACTIVE=''
HM_HMRF_DEV=''
HM_HMRF_DEVNODE=''
HM_HMRF_DEVTYPE=''
HM_HMRF_SERIAL=''
HM_HMRF_VERSION=''
HM_HOST='oci'
HM_LED_GREEN=''
HM_LED_GREEN_MODE1='none'
HM_LED_GREEN_MODE2='heartbeat'
HM_LED_RED=''
HM_LED_RED_MODE1='timer'
HM_LED_RED_MODE2='none'
HM_LED_YELLOW=''
HM_LED_YELLOW_MODE1='none'
HM_LED_YELLOW_MODE2='none'
HM_MODE='NORMAL'
HM_RTC='onboard'
HM_SUPERVISOR_TOKEN=''
```

**Comment by Elfe** [comment]
I was in the same situation and needed to update my host kernel modules and replug the device as well. (The 1.0.56 dkms on Arch is a bit dated...)

now the detect devices look like
```cat /var/hm_mode 
HM_HMIP_ADDRESS='0xB8....'
HM_HMIP_ADDRESS_ACTIVE='0xB8....'
HM_HMIP_DEV='HMIP-RFUSB'
HM_HMIP_DEVNODE='/dev/raw-uart'
HM_HMIP_DEVTYPE='eQ-3 HmIP-RFUSB@usb-0000:01:00.0-10'
HM_HMIP_SERIAL='1B...'
HM_HMIP_SGTIN='30...'
HM_HMIP_VERSION='4.4.16'
HM_HMRF_ADDRESS='0xFF....'
HM_HMRF_ADDRESS_ACTIVE='0xFF.....'
HM_HMRF_DEV='HMIP-RFUSB'
HM_HMRF_DEVNODE='/dev/raw-uart'
HM_HMRF_DEVTYPE='eQ-3 HmIP-RFUSB@usb-0000:01:00.0-10'
HM_HMRF_SERIAL='1B...'
HM_HMRF_VERSION='4.4.16'
HM_HOST='oci'
HM_LED_GREEN=''
HM_LED_GREEN_MODE1='none'
HM_LED_GREEN_MODE2='heartbeat'
HM_LED_RED=''
HM_LED_RED_MODE1='timer'
HM_LED_RED_MODE2='none'
HM_LED_YELLOW=''
HM_LED_YELLOW_MODE1='none'
HM_LED_YELLOW_MODE2='none'
HM_MODE='NORMAL'
HM_RTC='onboard'
HM_SUPERVISOR_TOKEN=''
```
no more HM_HMIP_DEVNODE='/dev/ttyUSB0'

**Comment by jens-maus** [comment]
> no more HM_HMIP_DEVNODE='/dev/ttyUSB0'

This is the expected behaviour since 3.61.7.20201218 which comes with the 4.4.16 firmware for the HmIP-RFUSB. Thus, now the HmIP-RFUSB is a full-fledged dual-copro aware RF module which you can address by using `/dev/raw-uart` instead of `/dev/ttyUSB0`. So nothing to be worried here.

**Comment by mistressofjellyfish** [comment]
@jens-maus @hennedo Hallo zusammen,

für alle, die dasselbe Problem haben: In der Installations-Doku steht, man soll eine udev-Regel anlegen, [Punkt 6 hier](https://github.com/jens-maus/RaspberryMatic/wiki/Installation-Docker-OCI):

![image](https://user-images.githubusercontent.com/7026857/195200709-be190a1d-8a01-4074-baed-e55da71b98eb.png)

Regel löschen, Pi neu starten, alles geht.

Schönen Gruß :)
