### ISSUE TITLE
Docker Health-Check "unhealthy" vermutlich wg. Fehler in Monit

### ISSUE THREAD

**Issue by dkadioglu** [jens-maus/RaspberryMatic#1611]
### Describe the issue you are experiencing

Der Docker-Container ist im Status unhealthy, mindestens seit 3.61.7.20211218, ob das schon vorher der Fall war, weiß ich ehrlich gesagt nicht. Beim Blick in /var/log/messages fällt folgendes auf, hier mal ein kleiner Auszug:
```
Dec 21 10:50:05 dkhm user.err monit[872]: 'dkhm' mem usage of 463493529600.0% matches resource limit [mem usage > 95.0%]
Dec 21 10:50:22 dkhm user.err monit[872]: 'dkhm' mem usage of 463493529600.0% matches resource limit [mem usage > 95.0%]
Dec 21 10:50:39 dkhm user.err monit[872]: 'dkhm' mem usage of 463493529600.0% matches resource limit [mem usage > 95.0%]
Dec 21 10:50:56 dkhm user.err monit[872]: 'dkhm' mem usage of 463493529600.0% matches resource limit [mem usage > 95.0%]
Dec 21 10:51:13 dkhm user.err monit[872]: 'dkhm' mem usage of 463493529600.0% matches resource limit [mem usage > 95.0%]
Dec 21 10:51:30 dkhm user.err monit[872]: 'dkhm' mem usage of 463493529600.0% matches resource limit [mem usage > 95.0%]
Dec 21 10:51:46 dkhm user.err monit[872]: 'dkhm' mem usage of 463493529600.0% matches resource limit [mem usage > 95.0%]
Dec 21 10:52:03 dkhm user.err monit[872]: 'dkhm' mem usage of 463493529600.0% matches resource limit [mem usage > 95.0%]
```
Dieser Wert erscheint mir unrealistisch und nicht richtig. Bei der Suche nach der Ursache bin ich über folgendes gestolpert:
https://bitbucket.org/tildeslash/monit/issues/1002/incorrect-memory-use-value-on-32bit-pae
Der darin referenzierte Commit zur Behebung des Problems wird wohl erst in monit 5.30 drin sein. Leider konnte ich keine Roadmap oder ähnliche Zeitangaben finden. Gegebenenfalls wäre es ja auch möglich, einen entsprechenden Patch für monit mit aufzunehmen?

### Describe the behavior you expected

Der Docker Container sollte healthy sein, da alles funktioniert und der Speicherverbrauch nicht höher als 95% ist.

### Steps to reproduce the issue

1. Starte einen RM Docker Container basierend auf dem Image 3.61.7.20211218 auf dem Raspberry Pi 4 mit 8GB RAM
2. Obwohl alles funktioniert, ist der Docker Container im Status unhealthy

### What is the version this bug report is based on?

3.61.7.20211218

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

Beim Blick in /var/log/messages fällt folgendes auf, hier mal ein kleiner Auszug:
```
Dec 21 10:50:05 dkhm user.err monit[872]: 'dkhm' mem usage of 463493529600.0% matches resource limit [mem usage > 95.0%]
Dec 21 10:50:22 dkhm user.err monit[872]: 'dkhm' mem usage of 463493529600.0% matches resource limit [mem usage > 95.0%]
Dec 21 10:50:39 dkhm user.err monit[872]: 'dkhm' mem usage of 463493529600.0% matches resource limit [mem usage > 95.0%]
Dec 21 10:50:56 dkhm user.err monit[872]: 'dkhm' mem usage of 463493529600.0% matches resource limit [mem usage > 95.0%]
Dec 21 10:51:13 dkhm user.err monit[872]: 'dkhm' mem usage of 463493529600.0% matches resource limit [mem usage > 95.0%]
Dec 21 10:51:30 dkhm user.err monit[872]: 'dkhm' mem usage of 463493529600.0% matches resource limit [mem usage > 95.0%]
Dec 21 10:51:46 dkhm user.err monit[872]: 'dkhm' mem usage of 463493529600.0% matches resource limit [mem usage > 95.0%]
Dec 21 10:52:03 dkhm user.err monit[872]: 'dkhm' mem usage of 463493529600.0% matches resource limit [mem usage > 95.0%]
```

### Additional information

Hardware: Raspberry Pi 4, 8GB RAM

**Comment by jens-maus** [comment]
Der Docker/OCI Heath-Check ist wie folgt definiert:

https://github.com/jens-maus/RaspberryMatic/blob/86d6dd15a2d7cef15e0db911d81defe8ebf8eda3/buildroot-external/board/oci/Dockerfile#L22

D.h. Du könntest innerhalb von RaspberryMatic dieses Kommando mal ausführen und solltest so erfahren warum der bei dir meldet das der Container unheathly läuft.

**Comment by jens-maus** [comment]
> 10:52:03 dkhm user.err monit[872]: 'dkhm' mem usage of 463493529600.0% matches resource limit [mem usage > 95.0%]

Das erscheint mir hier Grund zu sein und sieht mir nach einem upstream Problem im Monit zu sein. Bitte mal verraten welches Host-Betriebssystem du da auf dem RaspberryPi4 genau einsetzt um den RM Docker Container laufen zu lassen.

**Comment by dkadioglu** [comment]
> > 10:52:03 dkhm user.err monit[872]: 'dkhm' mem usage of 463493529600.0% matches resource limit [mem usage > 95.0%]
> 
> Das erscheint mir hier Grund zu sein und sieht mir nach einem upstream Problem im Monit zu sein. Bitte mal verraten welches Host-Betriebssystem du da auf dem RaspberryPi4 genau einsetzt um den RM Docker Container laufen zu lassen.

Ja genau, denke auch, dass das der Grund dafür sein dürfte. Auf dem RPi 4 läuft ein Arch Linux in der armv7h-Architektur, also noch kein 64-bit, sprich 32-bit, was dann zu dem verlinkten Bug-Report vpn monit passen sollte: https://bitbucket.org/tildeslash/monit/issues/1002/incorrect-memory-use-value-on-32bit-pae



> Der Docker/OCI Heath-Check ist wie folgt definiert:
> 
> https://github.com/jens-maus/RaspberryMatic/blob/86d6dd15a2d7cef15e0db911d81defe8ebf8eda3/buildroot-external/board/oci/Dockerfile#L22
> 
> D.h. Du könntest innerhalb von RaspberryMatic dieses Kommando mal ausführen und solltest so erfahren warum der bei dir meldet das der Container unheathly läuft.

Wenn ich das direkt im Container ausführe, erhalte ich leider keinen Output.
Wenn ich aber `/usr/bin/monit report down` ausführe, erhalte ich `1` als output. Wenn ich dann noch `/usr/bin/monit status` ausführe, sind alle Dienste entweder OK oder Not monitored, bis auf diesen Eintrag:

```
System 'dkhm'
  status                       Resource limit matched
  monitoring status            Monitored
  monitoring mode              active
  on reboot                    start
  load average                 [0.33] [0.56] [0.63]
  cpu                          4.9%usr 2.9%sys 0.0%nice 0.1%iowait 0.0%hardirq 0.2%softirq 0.0%steal 0.0%guest 0.0%guestnice 
  memory usage                 16 EB [463493529600.0%]
  swap usage                   0 B [0.0%]
  uptime                       22d 19h 36m
  boot time                    Sun, 28 Nov 2021 16:03:48
  filedescriptors              5344 [0.0% of 2147483647 limit]
  data collected               Tue, 21 Dec 2021 11:39:55
```

**Comment by jens-maus** [comment]
> Ja genau, denke auch, dass das der Grund dafür sein dürfte. Auf dem RPi 4 läuft ein Arch Linux in der armv7h-Architektur, also noch kein 64-bit, sprich 32-bit, was dann zu dem verlinkten Bug-Report vpn monit passen sollte: https://bitbucket.org/tildeslash/monit/issues/1002/incorrect-memory-use-value-on-32bit-pae

Danke für den Link. Nach kurzem Check scheint das in der Tat in Monit ein Problem zu sein das auch noch in der aktuellen 5.29.0 mit drin ist und wohl erst mit der kommenden 5.30.0 gefixt sein wird. Insofern flagge ich das mal als ein third-party-issue welches wir bis zur nächsten RM version dann entsprechend addressieren sollten durch ein Update von Monit bzw. einfließen lassen des entsprechenden Patches.
