### ISSUE TITLE
HmIP-RFUSB im Home Assistant Docker wird durch Raspberrymatic nicht erkannt.

### ISSUE THREAD

**Issue by JackNicholsen** [jens-maus/RaspberryMatic#1612]
### Describe the issue you are experiencing

Erst einmal vielen Dank für das tolle Produkt!!! Habe bereits sehr gute Erfahrungen in HASS.io damit gemacht. Unter dem Betriebssystems HASS.io lief RaspberryMatic mit dem gleichen HmIP-RFUSB einwandfrei. Dafür funktionierten andere Dienste nicht (z. B. ConBee), weshalb ein Umstieg auf das Superviced Docker Modell notwendig wurde.

HmIP-RFUSB ist im Home Assistant Docker sichtbar, wird durch RaspberryMatic aber nicht erkannt.
<img width="628" alt="image" src="https://user-images.githubusercontent.com/28046447/146936746-46b9a51a-9272-4408-b267-14b85daba638.png">

Sichbarkeit in Raspbian (lsusb):
```
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 1b1f:c020 eQ-3 Entwicklung GmbH HmIP-RFUSB
Bus 001 Device 003: ID 1cf1:0030 Dresden Elektronik ZigBee gateway [ConBee II]
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

Sichtbarkeit im Home Assistant unter "Hardware" im "Supervisor"->"Host":
Gerätepfad des HmIP-RFUSB:
```
BUSNUM: '001'
DEVNAME: /dev/bus/usb/001/004
DEVNUM: '004'
DEVPATH: >-
  /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.4
DEVTYPE: usb_device
DRIVER: usb
ID_BUS: usb
ID_FOR_SEAT: usb-platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1_4
ID_MODEL: eQ-3_HmIP-RFUSB
ID_MODEL_ENC: eQ-3\x20HmIP-RFUSB
ID_MODEL_FROM_DATABASE: HmIP-RFUSB
ID_MODEL_ID: c020
ID_PATH: platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4
ID_PATH_TAG: platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1_4
ID_REVISION: '0100'
ID_SERIAL: Silicon_Labs_eQ-3_HmIP-RFUSB_3014F711A061A7C00010CECF
ID_SERIAL_SHORT: 3014F711A061A7C00010CECF
ID_USB_INTERFACES: ':ff0000:'
ID_VENDOR: Silicon_Labs
ID_VENDOR_ENC: Silicon\x20Labs
ID_VENDOR_FROM_DATABASE: eQ-3 Entwicklung GmbH
ID_VENDOR_ID: 1b1f
MAJOR: '189'
MINOR: '3'
PRODUCT: 1b1f/c020/100
SUBSYSTEM: usb
TAGS: ':seat:'
TYPE: 0/0/0
USEC_INITIALIZED: '5972870'
```

Weitere USB-Belegungen:
```
BUSNUM: '001'
DEVNAME: /dev/bus/usb/001/002
DEVNUM: '002'
DEVPATH: >-
  /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1
DEVTYPE: usb_device
DRIVER: usb
ID_BUS: usb
ID_FOR_SEAT: usb-platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1
ID_MODEL: USB2.0_Hub
ID_MODEL_ENC: USB2.0\x20Hub
ID_MODEL_FROM_DATABASE: Hub
ID_MODEL_ID: '3431'
ID_PATH: platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1
ID_PATH_TAG: platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1
ID_REVISION: '0421'
ID_SERIAL: 2109_USB2.0_Hub
ID_USB_INTERFACES: ':090000:'
ID_VENDOR: '2109'
ID_VENDOR_ENC: '2109'
ID_VENDOR_FROM_DATABASE: VIA Labs, Inc.
ID_VENDOR_ID: '2109'
MAJOR: '189'
MINOR: '1'
PRODUCT: 2109/3431/421
SUBSYSTEM: usb
TAGS: ':seat:'
TYPE: 9/0/1
USEC_INITIALIZED: '5804192'

BUSNUM: '001'
DEVNAME: /dev/bus/usb/001/003
DEVNUM: '003'
DEVPATH: >-
  /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3
DEVTYPE: usb_device
DRIVER: usb
ID_BUS: usb
ID_MODEL: ConBee_II
ID_MODEL_ENC: ConBee\x20II
ID_MODEL_FROM_DATABASE: ZigBee gateway [ConBee II]
ID_MODEL_ID: '0030'
ID_PATH: platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.3
ID_PATH_TAG: platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1_3
ID_REVISION: '0100'
ID_SERIAL: dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2442815
ID_SERIAL_SHORT: DE2442815
ID_USB_INTERFACES: ':020201:0a0000:'
ID_VENDOR: dresden_elektronik_ingenieurtechnik_GmbH
ID_VENDOR_ENC: dresden\x20elektronik\x20ingenieurtechnik\x20GmbH
ID_VENDOR_FROM_DATABASE: Dresden Elektronik
ID_VENDOR_ID: 1cf1
MAJOR: '189'
MINOR: '2'
PRODUCT: 1cf1/30/100
SUBSYSTEM: usb
TYPE: 2/0/0
USEC_INITIALIZED: '6015918'
```

Log-File:
```
 Identifying Homematic RF-Hardware: HmRF: none, HmIP: none, OK
 Updating Homematic RF-Hardware: no GPIO/USB connected RF-hardware found
```

Umgebung:
```
 Betriebssystem: Raspbian 11 (Bulleye)
 Docker: 20.10.11
 Home Assistant Core: 2021.12.3
 RaspberryMatic: 3.61.7.20211220-36f15d1 (Snapshot) bzw. CCU Version 3.61.7.20211218 (beide reagieren gleich)
```

Viele Grüße
***Jacky***

### Describe the behavior you expected

Unter HASS.io wurde das Funkmodul einwandfrei erkannt. Das sollte auch in der Supervised Docker-Version passieren.

### Steps to reproduce the issue

1. Installieren Raspbian 11 (Bullseye)
2. Installieren Home Assistant Supervised
(https://peyanski.com/how-to-install-home-assistant-supervised-official-way/#How_to_Install_Home_Assistant_Supervised)
3. Installieren RaspberryMatic AddOn
4. Versuchen, ein neues Gerät anzulernen bzw. ein Backup einzuspielen (schlägt fehl ohne Fehlermeldung)
...

### What is the version this bug report is based on?

3.61.7.20211218

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Mounting /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying onboard hardware: oci, OK
Initializing RTC Clock: no hardware found
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.5, OK
Identifying Homematic RF-Hardware: HmRF: none, HmIP: none, OK
Updating Homematic RF-Hardware: no GPIO/USB connected RF-hardware found
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: not required
Starting rfd: no BidCos-RF hardware found
Starting HMIPServer: ....OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
```

### Additional information

<img width="882" alt="image" src="https://user-images.githubusercontent.com/28046447/146935868-07ba338e-802e-4428-a22d-f8b6e10b7679.png">
<img width="901" alt="image" src="https://user-images.githubusercontent.com/28046447/146935957-fc9ad063-a83c-431c-8912-9eb158993ab1.png">

**Comment by jens-maus** [comment]
Wurden denn die Punkte in der HomeAssistant Addon Installationanleitung bzgl. Supervised mode durchgeführt? Siehe:

https://github.com/jens-maus/RaspberryMatic/wiki/Installation-HomeAssistant#using-homeassistant-supervised

Hier muss man vor allem sicherstellen, das die `pivccu-modules-dkms` kernel module korrekt im Host system installiert sind damit für das `HmIP-RFUSB´ auch das `/dev/raw-uart` device korrekt eingerichtet wird das RaspberryMatic in der aktuellen Version nutzt. Ggf. muss man das `pivccu-modules-dkms` Paket aktuell aus dem `unstable` apt repo von pivccu installieren da die Funktionalität bzgl. HmIP-RFUSB und Dualcopro-Nutzung für Dual BidCos-RF/homematicIP momentan lediglich im testing repo von pivccu liegt.

**Comment by JackNicholsen** [comment]
Danke für die prompte Antwort!
Ja, piVCCU dkms habe ich nach Anleitung installiert. Um den Verdacht zu zerstreuen, ich hätte es vergessen, habe ich es nochmals versucht zu installieren. Aber es kommt überall 0 Files neu installiert/aktualisiert usw.:
![image](https://user-images.githubusercontent.com/28046447/146997501-c90a177f-02ac-492e-9471-4f0373f59104.png)
![image](https://user-images.githubusercontent.com/28046447/146997524-e86deb03-c621-43bf-8c2e-e378de8d4c69.png)
![image](https://user-images.githubusercontent.com/28046447/146997538-e53447c5-e2f1-4d4b-8a47-786ed56832f2.png)
![image](https://user-images.githubusercontent.com/28046447/146997545-0012de96-a434-4dc7-b2a3-186d526af3b4.png)

Ich habe versucht, dabei auf die "unstable" Version umzustellen (siehe 2. Screenshot unten). Aber der Parameter "unstable" wurde nicht berücksichtigt (siehe 3. Screenshot Mitte). Was habe ich falsch gemacht? Vielleicht wäre die unstable Version sowieso überflüssig, da ich nur HmIP und kein HmWired verwende (Dualcopro-Nutzung).

Außerdem habe ich auf den neuesten Home Assistent Core Version 2021.12.4 aktualisiert. Aber das Systemverhalten hat sich nicht geändert.

In /dev/raw-uart ist nur eine Datei rawctl zu finden. Wie kann ich prüfen, ob es richtig eingerichtet ist?
<img width="310" alt="image" src="https://user-images.githubusercontent.com/28046447/146998884-b1c6d7a8-d448-4d56-89c0-fa1c1493523f.png">

**Comment by jens-maus** [comment]
> Ich habe versucht, dabei auf die "unstable" Version umzustellen (siehe 2. Screenshot unten). Aber der Parameter "unstable" wurde nicht berücksichtigt (siehe 3. Screenshot Mitte). Was habe ich falsch gemacht? Vielleicht wäre die unstable Version sowieso überflüssig, da ich nur HmIP und kein HmWired verwende (Dualcopro-Nutzung).

Bist du sicher das am Schluss in der `/etc/apt/sources.list.d/pivccu.list` Datei auch wirklich `unstable` steht bevor du das finale `apt update` gemacht hast wo dann wieder was von "stable" steht?

**Comment by alexreinert** [comment]
Ich habe kein `unstable` APT Repository. Es gibt `stable` und `testing`.

**Comment by jens-maus** [comment]
Ah, mein Fehler! Dann bitte mit `testing` testen.

**Comment by JackNicholsen** [comment]
Danke! Der Tipp mit dem "testing" war sehr hilfreich. Man will sich ja nicht blamieren und fragt nicht gleich nach, wenn etwas nicht klappt. Insbesondere wenn man so wenig Ahnung und so viel Halbwissen hat, wie ich. So viel sehr guten Support bin ich gar nicht mehr gewohnt.
<img width="691" alt="image" src="https://user-images.githubusercontent.com/28046447/147056437-797b1cbe-704c-4dc9-9e69-cd7993ea8890.png">
Jetzt habe ich vergeblich versucht, mein Konfigurations-Backup einzuspielen, weil das Anlernen der vielen Geräte sehr viel Zeit benötigt. Aber es ist wie bei meinem letzten Umstieg Ende Mai diesen Jahres auf das neue RaspberryMatic-Plugin. Beim Einspielen öffnet sich nur ein weiteres leeres neues Fenster. Damals lag es am Node-Red-Plugin. Nach dem Herausnehmen aus dem Backup, klappte es. Darf ich hier fragen, was dieses Mal im RaspberryMatic verändert worden ist? Leider kommt im Log keine Meldung, woran es scheitert.

**Comment by jens-maus** [comment]
> Danke! Der Tipp mit dem "testing" war sehr hilfreich. Man will sich ja nicht blamieren und fragt nicht gleich nach, wenn etwas nicht klappt. Insbesondere wenn man so wenig Ahnung und so viel Halbwissen hat, wie ich. So viel sehr guten Support bin ich gar nicht mehr gewohnt.

Na das sieht doch schon sehr gut aus. Nach einem weiteren Neustart des Containers sollte er dann auch bei `HmRF:` korrekt das HMIP-RFUSB erkennen. Damit sollte doch dann dein ursprüngliches Problem das du hier reportet hast gelöst sein, oder?

> Jetzt habe ich vergeblich versucht, mein Konfigurations-Backup einzuspielen, weil das Anlernen der vielen Geräte sehr viel Zeit benötigt. Aber es ist wie bei meinem letzten Umstieg Ende Mai diesen Jahres auf das neue RaspberryMatic-Plugin. Beim Einspielen öffnet sich nur ein weiteres leeres neues Fenster. Damals lag es am Node-Red-Plugin. Nach dem Herausnehmen aus dem Backup, klappte es. Darf ich hier fragen, was dieses Mal im RaspberryMatic verändert worden ist? Leider kommt im Log keine Meldung, woran es scheitert.

Nun, das du dein Backup nicht einspielen kannst hat doch mit dem Problem das du hier beschrieben hast nicht wirklich was zu tun, oder? Insofern sind das doch zwei paar Schuhe und das ist hier ja kein Diskussionsforum. Ich würde also meinen das die beiden Probleme unabhängig von einander sind und du müsstest das bitte dann im Diskussionsteil bzw. im HomeMatic Forum noch einmal genau mit Detailinfos vorbringen.

**Comment by JackNicholsen** [comment]
Das Problem mit dem Erkennen des HmIP-USB ist damit gelöst. Besten Dank!
