### ISSUE TITLE
HMIP-PS Wochenprogramm lässt sich nicht Speichern (Error 414 Request-URI Too Long)

### ISSUE THREAD

**Issue by theexit** [jens-maus/RaspberryMatic#1613]
### Describe the issue you are experiencing

Wenn bei einem HMIP-PS ein Wochenprogramm angelegt wird und diese gespeichert wird, bleibt der Dialog "Geräte-/Kanaleinstellungen werden an Komponenten übertragen..." stehen.

### Describe the behavior you expected

Eigentlich sollte die Anpassung übernommen werden!

### Steps to reproduce the issue

1. Im HMIP-PS ein Wochenprogramm anlegen (Konfig ist Egal)
2. Speichern

### What is the version this bug report is based on?

3.61.7.20211218

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
In der Chrome Console findet sich ein Get-Error:
GET https://url/config/ic_ifacecmd.cgi?sid=%4...
414 (Request-URI Too Long)
```

**Comment by Baxxy13** [comment]
Eigentlich sollte das Problem nicht mehr existieren.
Hast du mal mit anderen Browsern probiert?
Ist das ein dediziertes RaspberryMatic System oder nutzt du das Homeassistant Add-On?

Ich nutze selbst nicht Chrome, aber "Chromium based" Browser, damit klappt das problemlos.

**Comment by jens-maus** [comment]
In der Tat würde mich das auch brennend interessieren bzw würdenich gerne mal die gesamte URI hier sehen wollen oder ein Screenshot der Browser Console. Vllt sind es ja irgendwelche speziellen Parameter die die URL die momentane max Länge hinaus verlängern lässt.

**Comment by theexit** [comment]
Ich verwende ein RaspberryMatic System auf einer CCU3.

Hier habe ich einen Screenshot der Settings:
[Screenshot-Settings](https://user-images.githubusercontent.com/16115327/147131915-20464131-afb0-467f-bbb3-142d49d1580a.png)
Hier die zulange Url:
[url.txt](https://github.com/jens-maus/RaspberryMatic/files/7764238/url.txt)
Und hier noch der Screenshot der Browser Console:
[Screenshot-Console](https://user-images.githubusercontent.com/16115327/147132247-7a4400ff-6b63-42a9-8b54-e1c2b36d99c2.png)

Ich habe folgende Browser getestet: 
Chrome (96.0.4664.110) auch im Inkognito Modus
Safari (15.2 (17612.3.6.1.6))
Firefox (95.0.2)

Überall dasselbe Ergebnis.

**Comment by jens-maus** [comment]
> Wenn ich die Update Url kürze, dann können die Konfigurationen gespeichert werden!

Dann versuche mal herauszufinden ab welcher Länge die update url funktioniert. Auch kannst du probieren den `server.max-request-field-size` Wert in der lighttpd config mal testweise zu vergrößern um zu schauen ob das das problem löst (siehe https://redmine.lighttpd.net/boards/2/topics/8283)

**Comment by jens-maus** [comment]
Auch kannst du mal die '/var/log/lighttpd-error.log` anschauen was/ob da was geloggt wird und dann hier zeigen.

**Comment by theexit** [comment]
Ich muss mich an dieser Stelle Entschuldigen.
Der Fehler liegt am Reverse-Proxy. Diesen hätte ich zuerst überprüfen sollen bzw. erwähnen.
Im GUI direkt funktioniert alles einwandfrei.

Sorry nochmal!

**Comment by Baxxy13** [comment]
Auf dem "Screenshot-Console" war zu sehen das da nicht direkt die Zentrale angesprochen wird.
Das wäre mein nächster Hinweis gewesen. Aber du hast ja inzwischen das Problem lokalisiert.
