### ISSUE TITLE
Backup einspiel button funktioniert nicht in Home Assistant OS 7.0 RaspberryMatic Add-On installation

### ISSUE THREAD

**Issue by markus3388** [jens-maus/RaspberryMatic#1616]
### Describe the issue you are experiencing

Siehe hier:

https://homematic-forum.de/forum/viewtopic.php?f=65&t=71451&start=80#p695843

**UND**
Gleiches Problem bei Zusatzsoftware installieren:  choose Software ---> Datei auswählen ---> installieren (dann öffnet sich nur ein leeres Fenster aber sonst passiert nichts)

### Describe the behavior you expected

siehe hier:
https://homematic-forum.de/forum/viewtopic.php?f=65&t=71451&start=80#p6958437

### Steps to reproduce the issue

siehe hier:
https://homematic-forum.de/forum/viewtopic.php?f=65&t=71451&start=80#p695843
2.
3.
...

### What is the version this bug report is based on?

RaspberryMatic Version (3.61.7.20211218) 

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
NO
```

**Comment by jens-maus** [comment]
duplicate of #1619
