### ISSUE TITLE
Bitte die Installation des CUx-Dämons im RaspberryMatic-Plugin für Home Assistant unterbinden!

### ISSUE THREAD

**Issue by JackNicholsen** [jens-maus/RaspberryMatic#1617]
### Describe the solution you'd like

Um zukünftig anderen Home Assistant Anwendern die Fehlersuche zu ersparen könnte RaspberryMatic die Installation von CUx verhindern (wie es schon bei NodeRed ohne Fehlermeldung läuft) und beim Versuch eine Fehlermeldung heraus geben. Bitte diese Fehlermeldung auch beim NodeRed Plugin für RaspberryMatic einbauen! Vielen Dank im Voraus!

### Describe alternatives you've considered

Wenn die Installation von CUx nicht verhindert werden soll, dann wenigstens ein Hinweis zu den möglichen Problemen, die man sich damit heran zieht.

### Is your feature request related to a problem?

Der CUx-Dämon https://www.homematic-inside.de/software/cuxd ist in Home Assistant überflüssig, da man dort die Kommunikation mit anderen Geräten auf andere Art löst. Der CUx-Dämon stört aber diese Kommunikation.

Ich bin im Mai 2021 RaspberryMatic in Home Assistant umgestiegen. Die Gerätekonfiguration habe ich mir aus meiner alten Installation per BackUp herüber geholt. Dabei wurden auch sämliche PlugIns (außer NodeRed) mit gezogen. Zusätzlich hatte ich mir zunächst einen CC2531 zigbee-Stick, dann einen ConBee II-Stick zugelegt, weil ich dachte, die Verbindungsabbrüche lägen an der Hardware. Jetzt habe ich dafür den CUx-Dämon lokalisiert, welcher sich permanent um eine Verbindung mit den anderen USB-Sticks bemüht, und dabei die eigentliche Kommunikation unterbricht - ein halbes Jahr Fehlersuche, weil dieses Problem genauso neu wie RaspberryMatic in Home Assistant ist.

**Comment by jens-maus** [comment]
Wieso sollte man die CUxD Nutzung bitte gänzlich verhindern? CUxD ist für mehr nützlich als nur die ANbindung weiterer/anderer USB RF Sticks. Es bietet eigene `system.Exec()` Ersatz und ausgefeilte Timerfunktionen die auch vollkommen ohne andere RF-USB Stick nutzung durchaus interessant sind. Das man sich damit in den Fuß schießen kann, steht natürlich ausser frage - aber das kann man auch bei anderen Dingen durchaus.

Bitte also genauer darlegen/auflisten welche Probleme ist gibt und dann kann man die zumindest in der Dokumentation als Limitationen hinterlegen.

**Comment by JackNicholsen** [comment]
Mit CUxD:
<img width="662" alt="image" src="https://user-images.githubusercontent.com/28046447/147099353-57ff7d91-90ef-4445-a649-7f018bc6e856.png">

Die Timeouts in der regulären ConBee-Kommunikation treten auf, wenn CUxD wieder zugeschlagen und den ConBee II-USB-Stick in Beschlag genommen hat.
Im CUxD-Protokoll:
<img width="822" alt="image" src="https://user-images.githubusercontent.com/28046447/147098667-fc958677-5f55-4e92-88c6-70c85bc0addb.png">

Im ConBee- bzw. deCONZ-Protokoll:
<img width="824" alt="image" src="https://user-images.githubusercontent.com/28046447/147098735-41b10226-411e-4237-98e2-c0f9bc0aabe5.png">
An den Zeitstempeln ist zu sehen, dass dies jeweils in sehr kurzen Zeitabständen passiert, weshalb eine normale Arbeit damit nicht möglich ist. Kein Sensor, kein Schalter u. ä. funktioniert mehr. Anlernen von Geräten geht gar nicht. Ich gehe davon aus, dass dies auch bei anderen USB-Sticks passiert (außer bei dem bekannten HmIP-RFUSB).
Fehlermeldung beim Deinstallieren (1. Screenshot, tritt auch bei den anderen Plugins in Raspberrymatic auf, weshalb es nicht an den Plugins sondern an Raspberrymatic liegen sollte):
<img width="325" alt="image" src="https://user-images.githubusercontent.com/28046447/147099489-7ef9705c-b208-4285-bcc8-0a02b0169622.png">
<img width="334" alt="image" src="https://user-images.githubusercontent.com/28046447/147099689-0b617112-fbae-412e-a17a-aec1358001b7.png">

Ohne CUxD erfolgt die Kommunikation mit den Geräten wieder normal:
<img width="831" alt="image" src="https://user-images.githubusercontent.com/28046447/147100379-597a82d4-682d-44aa-9112-fe6834571fdd.png">
Die Warnung mit der Network Adress 0xDDDD.. ist schnell manuell zu beheben. Ansonsten läuft ohne CUxD alles wieder korrekt.
Natürlich ist das eigentlich kein Problem von RaspberryMatic sondern des CUxD. Er sollte eine Möglichkeit besitzen, bestimmte Geräte auszuschließen. Aber ich bin mir nicht sicher, dass der Entwickler noch eifrig bei seinem Programm ist, da es ja sonst seine Funktion in HomeMatic recht gut erfüllt.

**Comment by MichaelN0815** [comment]
Ich denke das ist ein Fehler in cuxd, der dann auch dort adressiert werden sollte.

**Comment by JackNicholsen** [comment]
Das Problem ist, dass es dort niemand sucht. Und dass man es sich mit dem Einspielen des RasperryMatic-Backups herein holt. Wenn man weiß, dass das Problem von CUxD kommt, hat man auch schon die Lösung.

**Comment by Baxxy13** [comment]
Ich sehe hier auch kein Problem seitens CUxD.
Wenn man die CUxD-Doku konsultiert hat weiß man das sich der CUxD per Default zu allen seriellen USB Schnittstellen verbindet.
Um das zu unterbinden muss nur:
`TTYPARAM=NONE` in die CUxD-Konfig eingetragen werden.

Details dazu im CUxD-Handbuch (2.6) S. 155 ff
