### ISSUE TITLE
Protokoll zum BackUp in der Log-Datei

### ISSUE THREAD

**Issue by JackNicholsen** [jens-maus/RaspberryMatic#1618]
### Describe the solution you'd like

Bitte im Log protokollieren, warum ein Zurückspielen eines BackUps nicht funktioniert!

### Describe alternatives you've considered

Wenigstens eine Fehlermeldung, dass der Import des Backups nicht funktioniert hat.

### Is your feature request related to a problem?

Mit einem BackUp können Konfigurationen Installationsübergreifend übernommen werden, was auch so empfohlen wird. Trotzdem sind die unerschiedlichen HomeMatic-Landschaften nicht unbedingt kompatibel zueinander. Das Zurückspielen eines Backups bleibt in einem solchen Fall ergebnislos. Leider ist dann nirgendwo ein Hinweis zu finden, woran den der Import eines Backups gescheitert ist. Noch nicht einmal über das Scheitern gibt es eine Information. Beispiel: In einer reinen HomeMatic-Umgebung mit piVCCU oder RaspberryMatic ist das Plugin NodeRed nützlich. In Home Assistant (und anderen Hersteller übergreifenden Umgebungen) gibt es eine gesonderte Einbindung von Node Red. Eingebunden in Home Assistant ist das Importieren eines BackUps von einer anderen Installation mit NodeRed in RaspberryMatic nicht möglich. Leider besteht das Ergebnis nur darin, dass man feststellt, das nichts importiert worden ist. Keine Fehlermeldung und die Ursache bleibt im Dunkeln.

**Comment by jens-maus** [comment]
Da ist leider ein zu generell verfasster wunsch. In dem genannten/referenzierten Fall schläg das Backup zurückspielen nicht an den eigentlichen backuo restore methoden fehl, sondern hat ganz andere (Javascript in komb. Mit HomeAssistant) Ursachen und man kann nicht für jede eventualität etwas im Logfile vermerken.

**Comment by JackNicholsen** [comment]
Es ging nicht um jede Eventualität, sondern, wenn im Backup etwas inkompatibel liegt, es zu protokollieren. Und das war im Fall NodeRed anscheinend der Fall, denn nach dem Entfernen des Plugins lief die Portierung ja. Und die Eventualität des erfolgreichen Einspielens zu protokollieren ist zwar "Nice to Have" aber macht einen guten Eindruck. Und wenn die Anforderung des Einspielens bis zum RaspberryMatic durchkommt und nicht vorher schon durch den Browser abgefangen wird, dann könnte man wenigstens allgemein protokollieren, dass etwas schief gelaufen ist. Eine Fehlerursache würde allerdings nicht nur einen guten Eindruck hinterlassen sondern helfen. ;-) Aber es ist Dein Programm und Du entscheidest, was hinein kommt. Und meine Ausführungen zum guten Eindruck waren mehr scherzhaft gemeint. Ich möchte nicht belehrend rüber kommen. Du machst einen ausgezeichneten Job!

**Comment by jens-maus** [comment]
Wie schon gesagt: Konkrete Verbesserungen hier+da sind kein Problem und da gehe ich gerne drauf ein. Aber hier ist zu allgemein. Der konkrete fall wäre auch nicht durch besseres lighing aufgefallen, da das ein JavaScript error ist der im browser context auftritt. Insofern sehe ich hier aktuell keine konkreten Verbesserungsansätze.
