### ISSUE TITLE
RaspberryMatic constantly restarting on a Raspberry 1B+

### ISSUE THREAD

**Issue by JensMatic** [jens-maus/RaspberryMatic#162]
In the current backup I am using with the Raspberry 1 B+, the system keeps restarting irregulary stating that components are not available. Then the box restarts and works again upon the next reboot. First thought that this is based on the soldered RF module, but even with the module detached, it kept rebooting. 

The backup was taken from a former version, now the box is using 2.29.22.20170902

**Comment by jens-maus** [comment]
Which CCU Addons are you using? And please show the error messages you are seeing.

**Comment by JensMatic** [comment]
Well, the box simply reboots and the UI states the following messages:

~~~~~
VirtualDevices

Eine Komponente der HomeMatic Zentrale reagiert nicht mehr.

Hierfür kann es eine Reihe von Ursachen geben:
•es besteht keine Netzwerk-Verbindung
•die Stromversorung der HomeMatic Zentrale wurde unterbrochen
•mindestens eine Komponente der HomeMatic Zentrale ist abgestürzt

Überprüfen Sie die Netzwerk-Verbindung und die Stromversorgung der HomeMatic Zentrale. Starten Sie ggf. die HomeMatic Zentrale neu.
~~~~

Installed Add-Ons are:

XML-API 1.15
E-Mail 1.6.7c
WebMatic 2.2.3
CuX-Daemon 1.10b1
hm-watchdog 0.5

**Comment by jens-maus** [comment]
Uninstall hm-watchdog. It is not supported with RaspberryMatic anymore and needs an update that is not yet finished

**Comment by JensMatic** [comment]
Thanks, will do. Is this installed along the base image or was it part of the backup (Just in case for a restore) ?

**Comment by JensMatic** [comment]
The doc needs to be updated though: 

"
Unterstützte CCU Platformen 
•HomeMatic CCU1
•HomeMatic CCU2
•RaspberryMatic
"

**Comment by jens-maus** [comment]
Of course this is an optional install you did yourself and you broight in via your backup

**Comment by JensMatic** [comment]
Uninstall does not work, yielding:

---------------------------
Meldung von Webseite
---------------------------
Deinstallieren fehlgeschlagen:
Failure
Success

---------------------------
OK   
---------------------------

**Comment by JensMatic** [comment]
Seems to be uninstalled, after relaunching the Add-On Screen
