### ISSUE TITLE
Vermisster Hinweis: Mögliches Zusatzsoftware-Update wird auf Startseite nicht mehr angezeigt

### ISSUE THREAD

**Issue by ThomasLoeffel** [jens-maus/RaspberryMatic#1621]
### Describe the issue you are experiencing

Aus der Startseite vermisse ich den Hinweis eines mögliches Updates von Zusatzsoftware. Aufgefallen ist mir dieses bei der neuen Version CUXD

<img width="599" alt="image" src="https://user-images.githubusercontent.com/44590735/147390722-9b8f80e2-4a40-47d2-a1ad-052e29393b14.png">

In der näheren Vergangenheit konnte ich hier den Hinweis eines möglichen Updates sehen.

<img width="950" alt="image" src="https://user-images.githubusercontent.com/44590735/147390759-dc6bf62e-ba35-4d9b-a02f-785f47c8c113.png">

### Describe the behavior you expected

Updateinformation wird auf der ersten Seite angezeigt.

### Steps to reproduce the issue

1. System starten
2. Update liegt unter Zusatzsoftware vor
3. Startseite ansehen -> kein Hinweis
...

### What is the version this bug report is based on?

3.61.7.20211218

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
Funkmodul: HB-RF-ETH
```

**Comment by jens-maus** [comment]
Das ist nicht wirklich ein Bug, sondern eine gewisse Limitation die IMHO auch vernachlässigbar ist. Der Punkt ist, das die Anzeige auf Zusatzsoftware-Updates nur 1x am Tag (um 12:10) aktualisiert wird. Die angezeigten Versionsnummern beim Zusatzsoftware-Popup hingegen immer dann wenn man dieses öffnet (weil es eben im Browserkontext stattfindet). Daher kann es hier zu gewissen zeitlichen Diskrepanzen in der Darstellung/Aktualisierung dieser Anzeigen kommen. Spätesten morgen um 12:10 würde sich das Problem jedoch lösen weil dann eben eine aktualisierung der Datenbasis für die Anzeige auf der Startseite ansteht. Das ist aber IMHO völlig vernachlässigbar, weil eben Updates auch nicht täglich oder gar stündlich anstehen.

**Comment by mbhomie007** [comment]
@jens-maus @jp112sdl 

Dies ist ja schon mehreren Usern hin und wieder "aufgefallen".

Vielleicht kann man dort noch mehrere Aktualisierungszeiten hinterlegen oder nach einem WEB-UI Login die Aktualisierung/Anzeige anstoßen nach einer gewissen Zeit.

**Comment by jens-maus** [comment]
@mbhomie007 Wie gesagt, ich halte das für ein reines Luxus/Convienent-Problem bei dem es hunderte andere Dinge gibt die sicherlich wichtiger sind. Sehe also nicht wirklich das ich da selbst Hand diesbzgl. anlegen werden.

**Comment by mbhomie007** [comment]
Bei mir wird das Update bis dato noch immer nicht angezeigt.
Das Addon CUXD Version 2.7 -in diesem Beispiel- wurde vor 2 Tagen released.
Wenn die Anzeige sich jeden Tag um 12:10 Uhr aktualisiert, müsste es doch eigentlich schon angezeigt werden!?

**Comment by jens-maus** [comment]
> Wenn die Anzeige sich jeden Tag um 12:10 Uhr aktualisiert, müsste es doch eigentlich schon angezeigt werden!?

Das sollte so sein, ja. Schau mal in die Datei `/tmp/addon_updates.json`. Diese sollte die Infos über die aktuellen Updates beinhalten und eben wie gesagt m 12:10 jeden Tag via cronjob aktualisiert werden.

**Comment by jp112sdl** [comment]
Auf meinem produktiven System steht da
`{"name":"CUx-Daemon","webversion":"n/a"`
bei meinem Testsystem steht jedoch korrekt
`{"name":"CUx-Daemon","webversion":"2.7"}`

Da ging vielleicht irgendwas bei der Web-Abfrage schief (timeout oder so...)

**Comment by ThomasLoeffel** [comment]
Hallo Zusammen,

ich kann das gleiche bestätigen. Nur bei Cuxd steht es wie beschrieben ".....n/a" drin. Auf beiden Systemen die auf der Synology VM laufen.

Gruß Thomas

**Comment by ThomasLoeffel** [comment]
Nur Zusatz:

Wenn man die Datei von Hand ändert auf z.B. ...."2.6".... zeigt er auch die aktuelle Version zum Update an. Ggf. ein Problem mit der Web-Abfrage.

Gruß Thomas

**Comment by jens-maus** [comment]
@ThomasLoeffel Na dann führ halt mal den Befehl aus der diese `/tmp/addon_updates.json` erzeugt. Dieser lautet `/bin/checkAddonUpdates.sh` auf der RaspberryMatic

**Comment by ThomasLoeffel** [comment]
Hallo Zusammen,

nach dem ausführen dieses Befehls wurde die Datei geupdatet. Jetzt wird es auch angezeigt. Frage: Warum hat es dieses nicht von alleine gemacht. 

Gruß Thomas

**Comment by jp112sdl** [comment]
Eine Vermutung dazu habe ich ja bereits geäußert. Die wurde bisher weder bestätigt noch dementiert.
