### ISSUE TITLE
HmIP Geräte nach Umstieg von CCU3 auf RaspberryMatic nicht erreichbar

### ISSUE THREAD

**Issue by mrboost123** [jens-maus/RaspberryMatic#1624]
### Describe the issue you are experiencing

Ein direktes Update der CCU3 auf die RaspberryMatic 3.61.7.20211218  war nicht möglich  (rödelte Ewigkeiten ohne Erfolg). Daher wurde eine neue 32GB SD-Karte mit der 3.61.7.20211218 geflasht und in die CCU3 eingelegt. Daraufhin wurde das zuvor erstellte ConfigBackUp der CCU3 eingespielt. 
Alles Konfigurationen wurden soweit übernommen. Jedoch lassen sich mindestens 50% der Geräte nicht ansteuern. DutyCycle beträgt unter 10%. Ein Neustart der Zentrale bewirkt maximal ein Wechsel der Geräte welche fortan erreichbar ist. In Summe befinden sich ca. 20 angelernte Aktoren an der CCU3. 
Servicemeldungen zur gestörten Kommunikation erhalte ich keine. Manuelle Bedienung eines Aktors ergibt keine Besserung.
Möchten Daten zu einem nicht erreichbaren Aktor gesendet werden (z.B. Änderung im Wochenprogramm), erhalte ich nach der Übernahme die Meldung, dass das Gerät mit der Serienummer "XYZ...." nicht erreichbar ist.

### Describe the behavior you expected

funktionierende Geräte

### Steps to reproduce the issue

1.neue Firmware auf CCU3 installieren
2. BackUp einspielen

### What is the version this bug report is based on?

3.61.7.20211218

### Which base platform are you running?

rpi3 (RaspberryPi3) (CCU3)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB (CCU3)

### Anything in the logs that might be useful for us?

```txt
nein
```

**Comment by MichaelN0815** [comment]
Und wie hoch ist der CarrierSenseLevel?

**Comment by mrboost123** [comment]
CarrierSenseLevel liegt bei unter 5%.

**Comment by mrboost123** [comment]
Ich konnte das Problem beheben.

Nach mehrmaligen Flashen der SD-Karte mit der Raspberry-Matic Software klappt nun alles wie es soll.
Zusätzlich habe ich jegliche Zusatzsoftware vor dem Erstellen des Backups entfernt. Ich denke hier lag irgendwie das Problem.

Vielen Dank an alle Mitwirkenden des RaspberryMatic Projektes. Konnte nun einige Zusatzfunktionen installieren und nutzen :)
