### ISSUE TITLE
RM "hängt" beim Reboot / Shutdown wenn Netzwerkfreigaben gemounted sind

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1625]
### Describe the issue you are experiencing

Wenn man als User eigene Mountpoints zu Netzwerkfreigaben einrichtet um z.B. die CustomStoragePath - Option zu nutzen braucht RM für einen Reboot / Shutdown ungewöhnlich lange.
Beobachtet man den Shutdown / Reboot Prozess am Monitor sieht man das RM beim finalen Schritt "hängt". Gefühlt so 2 Minuten.

### Describe the behavior you expected

Keine Verzögerung bei Shutdown / Reboot bei Nutzung eigener Mountpoints.

### Steps to reproduce the issue

1. eine Netzwerkfreigabe z.B. nach `/usr/local/mnt` mounten
2. RM rebooten oder herunterfahren und die Ausgabe am Monitor betrachten
3. 
...

### What is the version this bug report is based on?

3.61.7.20211227 - Nightly

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
-
```

### Additional information

Im [Homematic-Forum](https://homematic-forum.de/forum/viewtopic.php?f=65&t=71630#p696833) wurde das Problem ja schon identifiziert.
Konkrete Lösungsvorschläge habe ich nicht. 
Wichtig wäre nur das der umount erst stattfindet wenn die AddOns (CUxD speichert das Logfile beim beenden) und der HmIP-Server (Diagramme auf dem Mount) down sind.
Ob das RaspberryMatic jetzt selbst an passender Stelle erledigt oder der User z.B. ein Gegenstück zur `/usr/local/etc/rc.prelocal`
(eben für den Shutdown / Reboot) bekommt ist eigentlich egal.
Letzteres hätte den Charme das man auch andere Aktionen (z.B. nen externen Historian stoppen) an einer zentralen Stelle anlegen könnte ohne sich jetzt mit start/stopp rc.d-Skripten auseinandersetzen zu müssen.

**Comment by jens-maus** [comment]
Bitte mal mit dem nächsten nightly snapshot probieren ob jetzt das herunterfahren etwas besser funktioniert mit aktiven Netzwerkfreigaben.

**Comment by Baxxy13** [comment]
Kurze Rückmeldung:
Habe den heutigen Nightly mehrfach rebootet bzw. heruntergefahren und konnte keine Verzögerung mehr feststellen.
Sieht also gut aus.

**Comment by jens-maus** [comment]
Wunderbar! Dann bitte nochmal mit dem morgigen nightly testen. Hab heute diesbzgl noch einmal ein paar kleinere Verbesserungen gemacht.
