### ISSUE TITLE
Gerätekommunikation managen

### ISSUE THREAD

**Issue by Jemeins** [jens-maus/RaspberryMatic#1628]
### Describe the solution you'd like

Die Zentrale (CCU) soll die zeitliche Abfolge der Gerätekommunikation managen.

### Describe alternatives you've considered

Das Anwenderprogramm übernimmt die Zeitliche Verzögerung für jeden Aktor.

### Is your feature request related to a problem?

Steuert man mehrere Aktoren gleichzeitig, dann bekommt man die Meldung: "Gerätekommunikation gestört".

### Additional information

Eine Automatische Abfolge der Gerätekommunikation wäre ebenfalls sehr hilfreich bei einer externen Steuerung von Aktoren (Redmatic ->HomeKit oder HAP).

**Comment by jens-maus** [comment]
Tut mir leid, aber ich kann nicht genau herauslesen was hier eigentlich gewünscht ist bzw. wo das Problem sein soll?!? Intern läuft die Gerätekommunikation natürlich völlig unabhängig und es kann auch nicht Aufgabe der Logikengine sein etwaige zeitliche Verzögerungen selbst bzw automatisch zu setzen. Es kommt immer auf den jeweiligen Anwendungsfall an den man in einem Programm im Blick hat. Wüsste also nicht wo genau man hier etwas verbessern könnte?!? Ergo sehe ich hier auch keinen Ansatz hier irgendetwas zu verbessern.
