### ISSUE TITLE
update Meldung in 2.29.22.20171007 falsch

### ISSUE THREAD

**Issue by thkl** [jens-maus/RaspberryMatic#163]
<img width="559" alt="bildschirmfoto 2017-10-07 um 14 57 36" src="https://user-images.githubusercontent.com/884355/31308054-f3762e40-ab6f-11e7-9ce3-c4afacc9996d.png">

**Comment by jens-maus** [comment]
1. browser cache leeren
2. bis spätestens morgen warten bis die cache server von github die update datei aktualisiert haben

Ergo, definitiv kein bug 😉

**Comment by thkl** [comment]
ok es war das github cache ... kannst du das nicht umgehen like 

`script.src = "https://gitcdn.xyz/repo/jens-maus/RaspberryMatic/master/release/LATEST-VERSION.js?bla=" + new Date();`

**Comment by jens-maus** [comment]
@thkl Kann man probieren, aber ist sicher zu viel des guten denn so oft ändert sich das ja auch nicht und es wäre IMHO etwas zuviel overhead jedesmal den download so zu erzwingen.

**Comment by thkl** [comment]
ja ok Date wäre übertrieben aber 

`script.src = "https://gitcdn.xyz/repo/jens-maus/RaspberryMatic/master/release/LATEST-VERSION.js?cversion=" + WEBUI_VERSION`

ändert sich ja nur wenn die FW sich ändert ...

**Comment by jens-maus** [comment]
Das könnte ich in der Tat für die nächste Version mal probieren. Danke für den Hinweis.
