### ISSUE TITLE
HmIP-RFUSB nicht mehr sichtbar nach Update auf 3.61.7.20211218

### ISSUE THREAD

**Issue by sMauldaeschle** [jens-maus/RaspberryMatic#1635]
### Describe the issue you are experiencing

Nach Update auf die neuste Software 3.61.7.20211218 haben plötzlich Geräte in RaspberryMatic gefehlt. Eine Wiederherstellung hat keine Abhilfe gebracht. Ein neues Einlernen war auch nicht möglich, da der HmIP-RFUSB Stick nicht mehr erkannt wurde (siehe Screenshot). In einem anderen Bug Report habe die Befehle "ls usb" und "cat /var/hm_mode" entdeckt. Diese habe ich bei mir ausgeführt. Mittels Vendor und Device ID konnte ich herausfinden, dass der Stick erkannt wird (ebenfalls getestet an weiterem RPi mit Debian und am Windows PC). Der zweite Befehl liefert jedoch nur leere Informationen (siehe zweiter Screenshot). In den Logdateien sieht man auch dass der Stick erkannt wird, irgendwann aber nur noch Fehler kommen. Erste Vermutung meinerseits ist ein zufällig aufgetretener HW-Defekt. Die Tatsache, dass er allerdings erkannt wird stimmt mich unsicher, ob es nicht doch eine Software-Abhängigkeit gibt. Daher der Bug Report.

<img width="701" alt="Screenshot 2021-12-30 194434" src="https://user-images.githubusercontent.com/45919533/147779769-5c0451f1-2c29-4e09-80f4-6b2afcbacc56.png">
<img width="501" alt="Screenshot 2021-12-30 194915" src="https://user-images.githubusercontent.com/45919533/147780045-6b04d66e-7fc9-473e-bef8-35e3022dbc1c.png">

### Describe the behavior you expected

Normaler Betrieb nach Update. Problemlose Erkennung des Stick.

### Steps to reproduce the issue

1. Update auf Software 3.61.7.20211218 --> Devices fehlen
2. Klick auf "teach-in devices" --> Fehlermeldung siehe Screenshot

### What is the version this bug report is based on?

3.61.7.20211218

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
USB Stick detected:
Jan  1 01:01:15 localhost kern.info kernel: [    3.593210] usb 1-1.5: new full-speed USB device number 4 using dwc_otg
Jan  1 01:01:15 localhost kern.info kernel: [    3.699993] usb 1-1.5: New USB device found, idVendor=1b1f, idProduct=c020, bcdDevice= 1.00
Jan  1 01:01:15 localhost kern.info kernel: [    3.700015] usb 1-1.5: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Jan  1 01:01:15 localhost kern.info kernel: [    3.700034] usb 1-1.5: Product: eQ-3 HmIP-RFUSB
Jan  1 01:01:15 localhost kern.info kernel: [    3.700052] usb 1-1.5: Manufacturer: Silicon Labs
Jan  1 01:01:15 localhost kern.info kernel: [    3.700071] usb 1-1.5: SerialNumber: 3014F711A061A7C00010CECF

Only errors at some point of time
Dec 30 17:01:21 homematic-raspi local0.err ReGaHss: ERROR: original file not exists, so try load new file. [LoadOM():iseDOM.cpp:2610]
Dec 30 17:01:21 homematic-raspi local0.err ReGaHss: ERROR: new file not exists, so try load bak file. [LoadOM():iseDOM.cpp:2622]
Dec 30 17:01:21 homematic-raspi local0.err ReGaHss: ERROR: failed open file= /etc/config/homematic.regadom.bak [LoadFromFile():iseDOMpersist.cpp:78]
Dec 30 17:01:21 homematic-raspi local0.err ReGaHss: ERROR: (202) failed! Already in map! [Insert():iseDOMobj.cpp:506]
Dec 30 17:01:21 homematic-raspi local0.err ReGaHss: ERROR: IseAddFavorite failed! ID=202 [IseAddFavorite():iseDOM.cpp:644]
Dec 30 17:01:21 homematic-raspi local0.err ReGaHss: ERROR: (203) failed! Already in map! [Insert():iseDOMobj.cpp:506]
Dec 30 17:01:21 homematic-raspi local0.err ReGaHss: ERROR: IseAddFavorite failed! ID=203 [IseAddFavorite():iseDOM.cpp:644]
Dec 30 17:01:21 homematic-raspi local0.err ReGaHss: ERROR: (204) failed! Already in map! [Insert():iseDOMobj.cpp:506]
Dec 30 17:01:21 homematic-raspi local0.err ReGaHss: ERROR: IseAddFavorite failed! ID=204 [IseAddFavorite():iseDOM.cpp:644]
Dec 30 17:01:23 homematic-raspi user.info homematic: meine-homematic.de Versions - Upgrade auf 1.503
Dec 30 17:01:23 homematic-raspi user.info homematic: meine-homematic.de VPN Dienst und Autoupdate DEAKTIVIERT
Dec 30 16:01:25 homematic-raspi daemon.info : starting pid 956, tty '/dev/null': '/usr/bin/monit -Ic /etc/monitrc'
Dec 30 17:01:25 homematic-raspi user.info monit[956]:  New Monit id: f2316c5471020f0c1505a0bb3dcb531d  Stored in '/usr/local/etc/monit.id'
Dec 30 17:01:25 homematic-raspi user.info monit[956]: Starting Monit 5.29.0 daemon with http interface at /var/run/monit.sock
Dec 30 17:01:25 homematic-raspi user.info monit[956]: 'homematic-raspi' Monit 5.29.0 started
Dec 30 17:01:35 homematic-raspi daemon.info chronyd[564]: Selected source 192.168.12.1
Dec 30 17:01:45 homematic-raspi user.err monit[956]: 'sshdEnabled' status failed (1) -- no output
Dec 30 17:01:45 homematic-raspi user.err monit[956]: 'hs485dEnabled' status failed (2) -- grep: /var/etc/hs485d.conf: No such file or directory
Dec 30 17:01:45 homematic-raspi user.err monit[956]: 'multimacdEnabled' status failed (1) -- no output
Dec 30 17:01:45 homematic-raspi user.err monit[956]: 'hmlangwEnabled' status failed (1) -- no output
Dec 30 17:01:45 homematic-raspi user.err monit[956]: 'rfdEnabled' status failed (1) -- no output
Dec 30 17:01:45 homematic-raspi user.warn monit[956]: 'hasUSB' status failed (1) -- no output
Dec 30 17:01:45 homematic-raspi user.err monit[956]: 'hb_rf_eth-CheckEnabled' status failed (1) -- no output
Dec 30 17:01:45 homematic-raspi user.warn monit[956]: 'eMMCLifeTimeCheck' status failed (1) -- no output
Dec 30 17:01:45 homematic-raspi user.warn monit[956]: 'rpi4usb3Check' status failed (1) -- no output
Dec 30 17:01:45 homematic-raspi user.err monit[956]: 'tailscaleEnabled' status failed (1) -- no output
Dec 30 17:01:45 homematic-raspi user.err monit[956]: Lookup for '/media/usb1' filesystem failed  -- not found in /proc/self/mounts
Dec 30 17:01:45 homematic-raspi user.err monit[956]: Filesystem '/media/usb1' not mounted
Dec 30 17:01:45 homematic-raspi user.err monit[956]: 'usb1' unable to read filesystem '/media/usb1' state
Dec 30 17:01:45 homematic-raspi user.info monit[956]: 'usb1' trying to restart
Dec 30 17:02:03 homematic-raspi user.warn monit[956]: 'hasUSB' status failed (1) -- no output
Dec 30 17:02:03 homematic-raspi user.err monit[956]: 'wlan0CheckEnabled' status failed (1) -- no output
Dec 30 17:02:03 homematic-raspi user.warn monit[956]: 'eMMCLifeTimeCheck' status failed (1) -- no output
Dec 30 17:02:03 homematic-raspi user.warn monit[956]: 'rpi4usb3Check' status failed (1) -- no output
Dec 30 17:02:03 homematic-raspi user.err monit[956]: Filesystem '/media/usb1' not mounted
Dec 30 17:02:03 homematic-raspi user.err monit[956]: 'usb1' unable to read filesystem '/media/usb1' state
Dec 30 17:02:03 homematic-raspi user.info monit[956]: 'usb1' trying to restart
Dec 30 17:02:21 homematic-raspi user.warn monit[956]: 'hasUSB' status failed (1) -- no output
Dec 30 17:02:21 homematic-raspi user.err monit[956]: 'eMMCLifeTimeCheck' status failed (1) -- no output
Dec 30 17:02:21 homematic-raspi user.err monit[956]: 'rpi4usb3Check' status failed (1) -- no output
Dec 30 17:02:21 homematic-raspi user.err monit[956]: Filesystem '/media/usb1' not mounted
Dec 30 17:02:21 homematic-raspi user.err monit[956]: 'usb1' unable to read filesystem '/media/usb1' state
Dec 30 17:02:21 homematic-raspi user.info monit[956]: 'usb1' trying to restart
Dec 30 17:02:39 homematic-raspi user.warn monit[956]: 'hasUSB' status failed (1) -- no output
Dec 30 17:02:39 homematic-raspi user.err monit[956]: Filesystem '/media/usb1' not mounted
Dec 30 17:02:39 homematic-raspi user.err monit[956]: 'usb1' unable to read filesystem '/media/usb1' state
Dec 30 17:02:39 homematic-raspi user.info monit[956]: 'usb1' trying to restart
Dec 30 17:02:57 homematic-raspi user.err monit[956]: 'hasUSB' status failed (1) -- no output
Dec 30 17:04:23 homematic-raspi user.info firewall: configuration set
Dec 30 17:04:26 homematic-raspi auth.info sshd[1491]: Server listening on 0.0.0.0 port 22.
Dec 30 17:04:26 homematic-raspi auth.info sshd[1491]: Server listening on :: port 22.
```

### Additional information

Logfile attache
[homematic-raspi-2021-12-30 (1).log](https://github.com/jens-maus/RaspberryMatic/files/7794217/homematic-raspi-2021-12-30.1.log)
d

**Comment by jens-maus** [comment]
Bitte mal folgenden Befehl ausführen:

`detect_radio_module /dev/raw-uart`

**Comment by ciB89** [comment]
Hi, ich schließe mich (mal wieder) an, `detect_radio_module /dev/raw-uart` ergibt 
**/dev/raw-uart could not be opened**

**Comment by jens-maus** [comment]
> Hi, ich schließe mich (mal wieder) an, `detect_radio_module /dev/raw-uart` ergibt 
> 
> **/dev/raw-uart could not be opened**

Dann bitte mal alternativ

`detect_radio_module /dev/raw-uart1`

> Ich muss allerdings dazu sagen, dass ich den Stick bis eben mit dem Snapshot 3.61.7.20211227-92a20b0 laufen hatten, und auf die stable wechseln wollte.

Ok, das könnte deine Probleme natürlich erklären wenn du den Stick schon früher mit einem nightly build verwendet hast.

Meine Vermutung ist, das der Stick momentan eine defekte Firmware intus bekommen hat die man ihm erst einmal abgewöhnen muss.

**Comment by ciB89** [comment]
Ich hatte beim Wechsel der Version (HA-Addon) lediglich vergessen, den geschützten Modus zu deaktivieren - es geht also alles noch ;-)

**Comment by Baxxy13** [comment]
> eine defekte Firmware intus

Hattest du nach der offiziellen 3.61.720211218 noch was bezüglich des FW-Updates für den HmIP-RFUSB geändert?
Mir hatte es heute auch nen nigelnagelneuen Stick firmwaremäßig zerlegt nachdem er mit dem HA-AddOn (Nightly von heute) gebootet werden sollte.

**Comment by jens-maus** [comment]
> Hattest du nach der offiziellen 3.61.720211218 noch was bezüglich des FW-Updates für den HmIP-RFUSB geändert?

Nein, da wurde diesbzgl nichts mehr geändert soweit ich das überblicke.

> Mir hatte es heute auch nen nigelnagelneuen Stick firmwaremäßig zerlegt nachdem er mit dem HA-AddOn (Nightly von heute) gebootet werden sollte.

Das ist in der Tat recht komisch und müsste mal weiter beobachtet werden ob das vermehrt auftritt.

**Comment by S7evinK** [comment]
Kann es daran liegen, dass die FW nicht mit dem `HmIP-RFUSB-TK` (den müsste ich haben) kompatibel ist, die für `HmIP-RFUSB` aber versucht wird zu flashen?
Hatte das Docker Image `44d3ada41cb9` ([3.61.5](https://github.com/jens-maus/RaspberryMatic/releases/tag/3.61.5.20211113)) ohne Probleme am laufen, nach dem Update auf `b83b979b359d` ([3.61.7](https://github.com/jens-maus/RaspberryMatic/releases/tag/3.61.7.20211218)) hatte ich die gleichen Probleme wie hier beschrieben.

> PLEASE NOTE: This new dualcopro firmware is only available for the HmIP-RFUSB sticks distributed by eQ3/ELV and NOT for the HmIP-RFUSB-TK which is the so-called "Telekom" version of the same RFUSB stick but meant to be used/supported only in combination with a Telekom SpeedPort router.

Auch `cat /var/hm_mode` hat mir nach dem Update eine Version angezeigt, vorher war keine Version vorhanden.

**Comment by Baxxy13** [comment]
> ist in der Tat recht komisch und müsste mal weiter beobachtet werden

Ja, das HA-AddOn hat da irgendwie Probleme. Da gibts auch kein BidCos-RF trotz FW: 4.4.16
Mache ich demnächst nen neues Ticket dazu auf.

**Comment by sMauldaeschle** [comment]
Antwort auf `detect_radio_module /dev/raw-uart`
`Error: Radio module was not detected`

Antwort auf `dmesg` nach Restart: siehe Anhang, ähnlich wie von @ciB89 beschrieben.

Antwort auf: `detect_radio_module /dev/raw-uart1`
`Error: Radio module was found, but did not respond correctly (maybe bricked App in flashrom)`
Klingt fast nach deiner Theorie mit der zerschossenen Firmwarm, oder? Ist die über einen PC flashbar? Bei ELV hab ich nichts gefunden. Damit könnte ich das Teil ja ggf. zurücksetzen.

[dmesg.txt](https://github.com/jens-maus/RaspberryMatic/files/7794693/dmesg.txt)

**Comment by jens-maus** [comment]
> Antwort auf: `detect_radio_module /dev/raw-uart1` `Error: Radio module was found, but did not respond correctly (maybe bricked App in flashrom)` Klingt fast nach deiner Theorie mit der zerschossenen Firmware, oder?

Wenn das Funkmodul prinzipiell "da" ist, aber eben leider die falsche bzw. defekte Firmware abbekommen hat solltest es sich mit folgendem Befehl wieder zum Leben erwecken lassen:

```
/opt/java/bin/java -Dos.arch=aarch64 -Dgnu.io.rxtx.SerialPorts=/dev/raw-uart1 -jar /opt/HmIP/hmip-copro-update.jar -p /dev/raw-uart1 -o -f /firmware/RPI-RF-MOD/dualcopro_update_blhmip-4.4.12.eq3
```

Danach dann einfach nochmal den `detect_radio_module /dev/raw-uart1` Befehl aufrufen und danach sollte sich dann das Funkmodul wieder normal melden und nach einem reboot von RaspberryMatic auch normal integrieren lassen.

**Comment by jens-maus** [comment]
@Baxxy13 
> Ja, das HA-AddOn hat da irgendwie Probleme. Da gibts auch kein BidCos-RF trotz FW: 4.4.16 Mache ich demnächst nen neues Ticket dazu auf.

Dazu braucht es kein extra Ticket. Das ist eine momentane Limitation des Add-on das das dualcopro BidCos-RF+HmIP damit gerade nicht geht. Das liegt aber nicht am add-on bzw. RaspberryMatic selbst, sondern es fehlt einfach im darunterliegenden HomeAssistantOS die aktualisierten `generic_raw_uart` Kerneltreiber. Das ganze ist allerdings bereits in Arbeit. Siehe:

https://github.com/home-assistant/operating-system/pull/1683

Und erste developer-build mit dem aktuellste `generic_raw_uart` unter dem dann auch das dualcopro BidCos+HmIP geht gibt es bereits hier:

https://os-builds.home-assistant.io/8.0.dev2021122901683/

Nach meinen ersten Tests damit geht dann eben auch BidCos+HmIP mit einem `HmIP-RFUSB` wie das auf einem nativen RaspberryMatic System der Fall ist.

**Comment by sMauldaeschle** [comment]
> Wenn das Funkmodul prinzipiell "da" ist, aber eben leider die falsche bzw. defekte Firmware abbekommen hat solltest es sich mit folgendem Befehl wieder zum Leben erwecken lassen:
> 
> ```shell
> /opt/java/bin/java -Dos.arch=$(uname -m) -Dgnu.io.rxtx.SerialPorts=/dev/raw-uart1 -jar /opt/HmIP/hmip-copro-update.jar -p /dev/raw-uart1 -o -f /firmware/RPI-RF-MOD/dualcopro_update_blhmip-4.4.12.eq3
> ```
> 
> Danach dann einfach nochmal den `detect_radio_module /dev/raw-uart1` Befehl aufrufen und danach sollte sich dann das Funkmodul wieder normal melden und nach einem reboot von RaspberryMatic auch normal integrieren lassen.

Das wollte noch nicht so recht funktionieren. Resultat:
```
root@homematic-raspi:~# /opt/java/bin/java -Dos.arch=$(uname -m) -Dgnu.io.rxtx.SerialPorts=/dev/raw-uart1 -jar /opt/HmIP/hmip-copro-up
date.jar -p /dev/raw-uart1 -o -f /firmware/RPI-RF-MOD/dualcopro_update_blhmip-4.4.12.eq3
[INFO] Homematic IP coprocessor update tool V1.0.10
[INFO] SGTIN = 3014F711A000041709ADFE0B
[INFO] Performing update with firmware file '/firmware/RPI-RF-MOD/dualcopro_update_blhmip-4.4.12.eq3' ...
[DEBUG] Start application ...
[ERROR] Error while reading current coprocessor application version:
java.lang.Exception: Failed to request application version.
        at de.eq3.cbcs.tools.copro.update.hmip.TRXAdapterUpdater.getApplicationVersion(TRXAdapterUpdater.java:255)
        at de.eq3.cbcs.tools.copro.update.hmip.TRXAdapterUpdater.updateTrxAdapter(TRXAdapterUpdater.java:116)
        at de.eq3.cbcs.tools.copro.update.hmip.HmipCoproUpdater.main(HmipCoproUpdater.java:89)
Caused by: java.lang.Exception: Failed to start application.
        at de.eq3.cbcs.tools.copro.update.hmip.TRXAdapterUpdater.getApplicationVersion(TRXAdapterUpdater.java:251)
        ... 2 more
[INFO] Updating regardless of the current version ...
[DEBUG] Start bootloader ...
[DEBUG] Already in Bootloader.
[INFO] Entering bootloader ...
[DEBUG] Start bootloader ...
[DEBUG] Already in Bootloader.
[DEBUG] Request bootloader version ...
[INFO] Bootloader version: 1.0.12
[DEBUG] Send update frames ...
[ERROR] No update performed.
[INFO] Exiting update tool.
```
Muss der Befehl eventuell angepasst werden, da es ein HmIP-RFUSB ist und kein RPI-RF-MOD? Oder ist das eh dieselbe Firmware?

**Comment by jens-maus** [comment]
> Muss der Befehl eventuell angepasst werden, da es ein HmIP-RFUSB ist und kein RPI-RF-MOD? Oder ist das eh dieselbe Firmware?

Ahja, tschuldigung. Natürlich mein Fehler. Der Befehl muss wie folgt sein:

```sh
/opt/java/bin/java -Dos.arch=$(uname -m) -Dgnu.io.rxtx.SerialPorts=/dev/raw-uart1 -jar /opt/HmIP/hmip-copro-update.jar -p /dev/raw-uart1 -o -f /firmware/HmIP-RFUSB-Beta/dualcopro_update_blhmip-4.4.16.eq3
```

**Comment by sMauldaeschle** [comment]
> > Muss der Befehl eventuell angepasst werden, da es ein HmIP-RFUSB ist und kein RPI-RF-MOD? Oder ist das eh dieselbe Firmware?
> 
> Ahja, tschuldigung. Natürlich mein Fehler. Der Befehl muss wie folgt sein:
> 
> ```shell
> /opt/java/bin/java -Dos.arch=$(uname -m) -Dgnu.io.rxtx.SerialPorts=/dev/raw-uart1 -jar /opt/HmIP/hmip-copro-update.jar -p /dev/raw-uart1 -o -f /firmware/HmIP-RFUSB-Beta/dualcopro_update_blhmip-4.4.16.eq3
> ```

Danke dir für die wahnsinnig schnellen Antworten mal so zwischendurch! Hat leider trotzdem noch nicht hingehauen. Sieht bei dem Protokoll aber eher nach einem Problem in der Kommunikation mit eq3 aus, oder? Zum Flashen kommt es ja erst gar nicht.
```
root@homematic-raspi:~# /opt/java/bin/java -Dos.arch=$(uname -m) -Dgnu.io.rxtx.SerialPorts=/dev/raw-uart1 -jar /opt/HmIP/hmip-copro-up
date.jar -p /dev/raw-uart1 -o -f /firmware/HmIP-RFUSB-Beta/dualcopro_update_blhmip-4.4.16.eq3
[INFO] Homematic IP coprocessor update tool V1.0.10
RXTX Warning:  Removing stale lock file. /var/lock/LCK..raw-uart1
[INFO] SGTIN = 3014F711A000041709ADFE0B
[INFO] Performing update with firmware file '/firmware/HmIP-RFUSB-Beta/dualcopro_update_blhmip-4.4.16.eq3' ...
[DEBUG] Start application ...
[ERROR] Error while reading current coprocessor application version:
java.lang.Exception: Failed to request application version.
        at de.eq3.cbcs.tools.copro.update.hmip.TRXAdapterUpdater.getApplicationVersion(TRXAdapterUpdater.java:255)
        at de.eq3.cbcs.tools.copro.update.hmip.TRXAdapterUpdater.updateTrxAdapter(TRXAdapterUpdater.java:116)
        at de.eq3.cbcs.tools.copro.update.hmip.HmipCoproUpdater.main(HmipCoproUpdater.java:89)
Caused by: java.lang.Exception: Failed to start application.
        at de.eq3.cbcs.tools.copro.update.hmip.TRXAdapterUpdater.getApplicationVersion(TRXAdapterUpdater.java:251)
        ... 2 more
[INFO] Updating regardless of the current version ...
[DEBUG] Start bootloader ...
[DEBUG] Already in Bootloader.
[INFO] Entering bootloader ...
[DEBUG] Start bootloader ...
[DEBUG] Already in Bootloader.
[DEBUG] Request bootloader version ...
[INFO] Bootloader version: 1.0.12
[DEBUG] Send update frames ...
[ERROR] No update performed.
[INFO] Exiting update tool.
```

**Comment by jens-maus** [comment]
> Danke dir für die wahnsinnig schnellen Antworten mal so zwischendurch! Hat leider trotzdem noch nicht hingehauen. Sieht bei dem Protokoll aber eher nach einem Problem in der Kommunikation mit eq3 aus, oder? Zum Flashen kommt es ja erst gar nicht.

Dann probier mal die 4.2.14 version der firmware von

```
/firmware/HmIP-RFUSB/dualcopro_update_blhmip-4.2.14.eq3
```

Und wenn das klappt danach nochmal die 4.4.16 wie im ursprünglichen kommando das ich dir als 1. genannt hatte.

**Comment by sMauldaeschle** [comment]
Sieht leider alles genau gleich aus. Den Fehler beim Lesen der `coprocessor application version` übergeht das Skript ja. Ein Ende findet der Ablauf dann immer mit `[ERROR] No update performed.`

**Comment by jens-maus** [comment]
> Sieht leider alles genau gleich aus. Den Fehler beim Lesen der `coprocessor application version` übergeht das Skript ja. 

Das ist kein Skript. Das ist ein Java programm und das macht halt einfach fleissig weiter.

> Ein Ende findet der Ablauf dann immer mit `[ERROR] No update performed.`

Das wundert mich. Zwischendrin bitte auch mal den Stick wieder abstecken und neu anschließen usw. damit er auch mal stromlos gemacht wird. Also die 4.2.14 Firmware muss er definitiv schlucken. Wenn nicht hat der Stick ein anderes Problem. Und die 4.4.16 firmware sollte die firmware sein die du anstreben solltest und die auf meinen drei Teststicks problemlos funktioniert.

**Comment by sMauldaeschle** [comment]
> Das ist kein Skript. Das ist ein Java programm und das macht halt einfach fleissig weiter.

Ja ok, seh mir diesen faux pas nach :) Ganz so tief bin ich nicht überall drin. 

> Das wundert mich. Zwischendrin bitte auch mal den Stick wieder abstecken und neu anschließen usw. damit er auch mal stromlos gemacht wird. Also die 4.2.14 Firmware muss er definitiv schlucken. Wenn nicht hat der Stick ein anderes Problem. Und die 4.4.16 firmware sollte die firmware sein die du anstreben solltest und die auf meinen drei Teststicks problemlos funktioniert.

Auf die Idee mit dem Neustart zwischendurch kam ich eben auch schon parallel zu deiner Nachricht. Nach dem Reboot hat das Update auf 4.2.14 funktioniert. Nach einem weiteren Reboot hab ich jetzt das Update auf 4.4.16 gemacht. PuTTY hat mir zwar nach der ersten Rückmeldung nichts mehr angezeigt, aber die RaspberryMatic zeigt die Device Firmware 4.4.16 an.

Erst mal ganz ganz herzlichen Dank dafür! Ich checke morgen ob das Einlernen der Geräte etc. wieder funktioniert. Spannend wäre jetzt natürlich wie es dazu kommen konnte. Kannst du da irgendwelche Log Dateien oder sonst etwas von mir dazu brauchen?

**Comment by jens-maus** [comment]
> Erst mal ganz ganz herzlichen Dank dafür! Ich checke morgen ob das Einlernen der Geräte etc. wieder funktioniert. Spannend wäre jetzt natürlich wie es dazu kommen konnte. Kannst du da irgendwelche Log Dateien oder sonst etwas von mir dazu brauchen?

Das einzige was du probieren kannst ist den Stick wieder auf die 4.2.14 zu setzen, dann einen Reboot zu machen um nachzustellen ob das automatische Update von der 4.2.14 zur 4.4.16 funktioniert oder nicht. Aber das hattest du ja gerade einmal durchgespielt. Meine aktuelle Vermutung ist, das beim ersten Upgrade von der 4.2.14 zur 4.4.16 etwas so schief gegangen ist das die Firmware in nem Zustand geblieben ist, das man eben erst manuell die firmware wieder aktualisieren musste (wie du es gerade getan hast).

**Comment by Baxxy13** [comment]
Bei einem DebMatic User trat übrigens das gleiche Problem auf. Auch da musste de HmIP-RFUSB neu geflashed werden.
[Link: Homematic-Forum](https://homematic-forum.de/forum/viewtopic.php?f=81&t=71360#p696869)

**Comment by jens-maus** [comment]
> Bei einem DebMatic User trat übrigens das gleiche Problem auf. Auch da musste de HmIP-RFUSB neu geflashed werden. [Link: Homematic-Forum](https://homematic-forum.de/forum/viewtopic.php?f=81&t=71360#p696869)

Danke für die Info. Dann müsste ich mal drüber nachdenken ob ich noch irgendwas an den firmware-Update routinen soweit verbessern kann das er im zweifel hart versucht die firmware-version erneut zu flashen.

**Comment by sMauldaeschle** [comment]
> > Erst mal ganz ganz herzlichen Dank dafür! Ich checke morgen ob das Einlernen der Geräte etc. wieder funktioniert. Spannend wäre jetzt natürlich wie es dazu kommen konnte. Kannst du da irgendwelche Log Dateien oder sonst etwas von mir dazu brauchen?
> 
> Das einzige was du probieren kannst ist den Stick wieder auf die 4.2.14 zu setzen, dann einen Reboot zu machen um nachzustellen ob das automatische Update von der 4.2.14 zur 4.4.16 funktioniert oder nicht. Aber das hattest du ja gerade einmal durchgespielt. Meine aktuelle Vermutung ist, das beim ersten Upgrade von der 4.2.14 zur 4.4.16 etwas so schief gegangen ist das die Firmware in nem Zustand geblieben ist, das man eben erst manuell die firmware wieder aktualisieren musste (wie du es gerade getan hast).

Ja so scheint es mir auch. Und exakt, genau das hab ich getan. Hat bestens funktioniert. Danke für deine bzw. eure Hilfe! Klasse!

**Comment by mulder999** [comment]
Following this thread really helped me unbrick my RPI-RF-MOD after an update that went bad
