### ISSUE TITLE
dom.GetObject throw ScriptRuntimeError without useless brackets

### ISSUE THREAD

**Issue by MichaelN0815** [jens-maus/RaspberryMatic#1637]
### Describe the issue you are experiencing

in case using nested dom.GetObject Commands without logical useless bracktes ReGa throw a ScriptRuntimeError

### Describe the behavior you expected

no ScriptRuntimeError for logical correct bracket using

### Steps to reproduce the issue

1. run this code with a valid ISE-ID for an HSSDP:
```
object hssdp=dom.GetObject("1537");
! geht
string works;
works=(dom.GetObject(dom.GetObject(hssdp).Channel())).Name();
WriteLine(works);
! geht NICHT
string breaks;
breaks=dom.GetObject(dom.GetObject(hssdp).Channel()).Name();
WriteLine(breaks);
WriteLine("DONE");    
```
2. the command for "works" needs additional (but logical useless) brackets
3. the logical correct command for "breaks" throw an error
4. the last two WriteLine commands will not be exuted

...

### What is the version this bug report is based on?

3.61.7.20211218

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Jan  2 16:38:54 ccu3-webui local0.err ReGaHss: ERROR: ScriptRuntimeError: object hssdp=dom.GetObject("1537");^M ! geht^M string works;^M works=(dom.GetObject(dom.GetObject(hssdp).Channel())).Name();^M WriteLine(works);^M ! geht NICHT^M string breaks;^M breaks=dom.GetObject(dom.GetObject(hssdp).Channel()).Name();^M WriteLine(breaks);^M WriteLine("DONE");^M ^M string sdvvars_=""; sdvvars_=sdvvars_#"breaks="#breaks.VarType();if (breaks.VarType()==9) {if(breaks){sdvvars_=sdvvars_#"|   (ID: "#breaks.ID()#" - TYPE: "#breaks.TypeName()#")";}}sdvvars_=sdvvars_#"\t"; sdvvars_=sdvvars_#"hssdp="#hssdp.VarType();if (hssdp.VarType()==9) {if(hssdp){sdvvars_=sdvvars_#"|   (ID: "#hssdp.ID()#" - TYPE: "#hssdp.TypeName()#")";}}sdvvars_=sdvvars_#"\t"; sdvvars_=sdvvars_#"works="#works.VarType();if (works.VarType()==9) {if(works){sdvvars_=sdvvars_#"|   (ID: "#works.ID()#" - TYPE: "#works.TypeName()#")";}}sdvvars_=sdvvars_#"\t";  [ExecError():iseESPexec.cpp:12883]
```

### Additional information

see also https://homematic-forum.de/forum/viewtopic.php?p=698022#p616267

**Comment by MichaelN0815** [comment]
Ich habe gerade gesehen,  Du hast dazu schon ein Ticket:
https://github.com/jens-maus/RaspberryMatic/issues/983

**Comment by jens-maus** [comment]
Vollkommen richtig! Ich werde alt 🤦‍♂️😜
