### ISSUE TITLE
Buildroot um "expect" erweitern

### ISSUE THREAD

**Issue by fhetty** [jens-maus/RaspberryMatic#164]
ist es moeglich, das Buildroot System mit "expect" zu erweitern?
Ich verwende expect z.B. zum fernsteuern unterschiedlichster Geraete per ssh.
z.B. spawn ssh USER@IP

Folgende Änderungen habe ich vorgenommen:
In folgender config Datei folgendes hinzufügen:
RaspberryMatic/buildroot-external/configs/raspmatic_rpi3_defconfig

Unter -> BR2_PACKAGE_FONTCONFIG=y
```
BR2_PACKAGE_TCL=y
BR2_PACKAGE_TCL_DEL_ENCODINGS=y
BR2_PACKAGE_TCL_SHLIB_ONLY=y
BR2_PACKAGE_EXPECT=y
```

**Comment by jens-maus** [comment]
Möglich ist natürlich (wie immer) alles :)

Allerdings stellt sich die Frage ob es ausreichend genug Leute gibt die das auch benötigen würden und das dann rechtfertigt wenn das Image dafür um einige MB größer werden würde.

Wenn du das ohnehin für dich durch eigene Anpassung der Buildroot Umgebung geschafft hast wäre ohnehin die Frage ob du damit nicht einfach leben könntest. Des Weiteren gäbe es ja auch noch die Möglichkeit das expect in ein CCU Addon Paket zu verwandeln sodass `expect` unter `/usr/local` wie ein addon installiert wird und so könnten dann Personen die das benötigen das einfach nachinstallieren. Das könnte doch ein extra Projekt von dir werden, oder? ;)

**Comment by fhetty** [comment]
Hi Jens,
OK, an die Möglichkeit mit dem Modul (CCU Addon) habe ich noch garnicht gedacht!
Gute Idee!
Dann werde ich mich mal an ein CCU Addon heranwagen.
Dann hätte mein Github Konto auch mal eine Sinn ;-)

Danke
Frank

**Comment by jens-maus** [comment]
Sehr gut. Man könnte sogar überlegen (die Idee hatte ich bereits selber) ein generelles CCU Addon zu machen das verschiedene Funktionalität auf einmal nachliefert (so z.B. expect oder andere unix-like tools)...

**Comment by fhetty** [comment]
Ja,
warum nicht!
Zum Glück habe ich noch ein Raspi2 und ein TinkerBoard (beide mit Hm-Funkmodul), und noch einige Aktoren.
Dann kann ich mal mit der Addon Erstellung experimentieren, ohne mir gleich mein Hauptsystem abzuschießen.
Werde aber vermutlich viel Hilfe benötigen. (Bin Elektronikentwickler und leider kein Programmieren)
Das geht vermutlich schon mit Github los :)
Gruß
Frank

**Comment by jens-maus** [comment]
Closing due to work on hm-tools Addon:
https://github.com/fhetty/hm-tools
