### ISSUE TITLE
Filterfunktion bei "direkten Verknüpfungen"

### ISSUE THREAD

**Issue by KnutSchweinfurth** [jens-maus/RaspberryMatic#1644]
### Describe the solution you'd like

Bei der Funktion "Programme und Verknüpfungen - Direkte Verknüpfungen"
gibt es keine Filterfunktion wie bei den anderen Geräte-Menüpunkten.
Bei vielen Direktprogrammen ist es somit sehr schwierig, den passenden Eintrag zu finden.

### Describe alternatives you've considered

-

### Is your feature request related to a problem?

feature request

### Additional information

-

**Comment by jens-maus** [comment]
Duplicate of #246
