### ISSUE TITLE
Zeitmodul um "das spätere von Astro oder fester Uhrzeit" erweitern

### ISSUE THREAD

**Issue by RettJay** [jens-maus/RaspberryMatic#1645]
### Describe the solution you'd like

Hallo, 
in den Homematic Rollladensteuerung (HmIP-BROLL) gibt es im Wochenprogramm die Möglichkeit "das spätere von Astro oder fester Uhrzeit" im Schalter zu konfigurieren. 
Ich möchte hier noch eine Bedingung einbinden und würde die Schalterkonfiguration in ein Programm auslagern. Im Programm-Zeitmodul gibt es allerdings diese sehr praktische Option nicht.
(Beispiel: Rolllade fahr herunter, wenn: das spätere von 30Min. nach Sonnenuntergang, oder 21:00Uhr, und wenn Variable GästeDa = False und Variable Terrassentüre = geschlossen)

"das spätere von Astro oder fester Uhrzeit"
"das frühere von Astro oder fester Uhrzeit"
... da gibt's glaub noch weitere Möglichkeiten

### Describe alternatives you've considered

Wenn man das natürlich ordentlich skripten könnte, wäre ich für ein Tipp dankbar.

### Is your feature request related to a problem?

nö

**Comment by MichaelN0815** [comment]
Du kannst beliebig Zeitmodule logisch miteinander verknüpfen - wie jede andere Bedingung auch. Daher ist dies bereits jetzt umsetzbar und erfordert keine Erweiterung des Zeitmodul. IMHO.

**Comment by jens-maus** [comment]
So sehe ich das auch und sehe keinerlei Bedarf für irgendwelche Anpassungen diesbzgl.. Dabei sollte man jedoch auch noch  erwähnen, das die Astrozeit Einstellungen die man direkt in einem Gerät umsetzen kann auch direkt auf diesem Gerät stattfinden völlig unabhängig von der CCU. D.h. selbst bei Ausfall der CCU/RaspberryMatic werden diese dann ausgeführt. Das sollte man immer mit bedenken wenn man statt Direktverknüpfungen oder direkte Einstellungen an einem Gerät auf WebUI programme oder WebUI-basierte Zeitmodule wechselt.
