### ISSUE TITLE
Device Firmware page column filters use German button labels when language is set to English

### ISSUE THREAD

**Issue by udochrist** [jens-maus/RaspberryMatic#1652]
### Describe the issue you are experiencing

The labels are „Setzen“ and „Schliessen“ instead of „Set“ and „Close“ as everywhere else when the language is set to English. 

![07AB02F6-2604-4563-BCAE-C0DA81FD92DD](https://user-images.githubusercontent.com/869637/148634347-ecb5953a-7439-448f-9752-9be32d3ae99f.jpeg)
![53DE4783-C7BA-4230-B228-185D7CAC46B8](https://user-images.githubusercontent.com/869637/148634349-3186ba88-36d6-4592-b5f9-cfce7bee0ae9.jpeg)

### Describe the behavior you expected

English naming is used when English language settings are active. 

### Steps to reproduce the issue

1. set language to English 
2. Open device firmware page
3. Open any column filter

### What is the version this bug report is based on?

3.61.7.20211218

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
None
```

### Additional information

None

**Comment by udochrist** [comment]
On a second note: I think the better English terms would be „Ok“ and „Cancel“ instead of Set and Close as this is what the buttons are supposed to do. However this would be a change affecting any such filter. So at least get them all to use the correct language.

**Comment by andrzejgilas** [comment]
![ee](https://user-images.githubusercontent.com/81189856/148646900-1a6aed47-3c32-48f9-9817-b26d875dd354.jpg)

RM 3.61.7.20220105 with Firefox - all is OK

**Comment by jens-maus** [comment]
@andrzejgilas You missed that the author of this ticket meant the `Settings -> Device firmware - overview` pages only. Because I can perfectly reproduce the issue here.

**Comment by andrzejgilas** [comment]
![2](https://user-images.githubusercontent.com/81189856/148647505-ca33d1d4-bb91-41ed-bc44-5c79acc99902.jpg)
that's right, my mistake :-)
