### ISSUE TITLE
Bild zuckt bei Programm - > Skript bearbeiten

### ISSUE THREAD

**Issue by mbhomie007** [jens-maus/RaspberryMatic#1653]
### Describe the issue you are experiencing

Bild zuckt im Takt des Himmbeer Icons oben links.
Siehe Screencast. 

### Describe the behavior you expected

Kein "zucken" des Bildes.

### Steps to reproduce the issue

1. Programm öffnen
2. Skript öffnen
3. Bild zuckt im Takt des Himmbeer Icons
...

### What is the version this bug report is based on?

3.61.7.20211218

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
-
```

### Additional information

https://user-images.githubusercontent.com/64688879/148700055-97b24b32-e6ee-4e5b-9ba4-fa3ebdcfc1b2.mp4

**Comment by friedpa** [comment]
**Describe the issue you are experiencing**
Kann ich so auf einem RPI4 bestätigen. Verwende die WebUI um ein Diagramm dauernd unter Chromium anzuzeigen.

**Describe the behavior you expected**
Kein "zucken" des Bildes.

**Steps to reproduce the issue**

    1. Diagramme Reiter auswählen
    2. beliebiges Diagramme auswählen
    3. Bild zuckt im Takt des Himmbeer Icons
    ...

**What is the version this bug report is based on?**
3.61.7.20211218

**Which base platform are you running?**
rpi4 (RaspberryPi4)

**Which HomeMatic/homematicIP radio module are you using?**
HB-RF-ETH

**Anything in the logs that might be useful for us?**
Nope

**Comment by roe1974** [comment]
Abhilfe schafft (bei mir zumindest) das Fenster einmal kurz zu verschieben .... dann ist Ruhe bis zum nächsten Aufruf des Script Editors

**Comment by Lindi01** [comment]
Bild zuckt

https://user-images.githubusercontent.com/97434328/148739380-c43d336f-d2e1-4178-8378-cbfe41a093c2.mp4

**Comment by Lindi01** [comment]
Wenn man langsam mit der Maus übern Bildschirm fährt dann kommt immer der Scrollbalken. als ob der Ausschit einmal zu groß ist.

**Comment by jens-maus** [comment]
Das scheinen mir hier zwei unterschiedliche/getrrennte Probleme zu sein. Bei @mbhomie007 sieht man eine "Zuckung" im vertikalen Bereich beim Skript Editor (wirklich nur da?) der mit der Blinkfrequenz des Logos einhergeht und bei @Lindi01 ist ein Zucken bei den Diagrammen zu erkennen der aber wohl uabhängig vom regelmäßigen Logoblinken ist.

**Comment by mbhomie007** [comment]
> Das scheinen mir hier zwei unterschiedliche/getrrennte Probleme zu sein. Bei @mbhomie007 sieht man eine "Zuckung" im vertikalen Bereich beim Skript Editor (wirklich nur da?) der mit der Blinkfrequenz des Logos einhergeht und bei @Lindi01 ist ein Zucken bei den Diagrammen zu erkennen der aber wohl uabhängig vom regelmäßigen Logoblinken ist.

Ja, ich konnte dies nur an dieser Stelle feststellen.
Wenn man z.B. nur ein Programm öffnet ist kein Zucken vorhanden, aber eben sobald man den Skript Editor öffnet.
Mir ist nun aufgefallen wenn man das Fester "Skript bearbeiten" etwas mit dem Mauszeiger hochzieht, hört das zucken auf.

Also müsste das Fenster unmittelbar nach dem Aufruf vielleicht etwas mittiger positioniert werden?
Im Moment ist das Fenster nach dem Aufruf ja sehr weit unten platziert (siehe Screencast).

Screencast oben Windows 10 mit Chrome 96.0.4664.110 
Gleiches Verhalten mit Edge 97.0.1072.55

Mit Firefox 91.0.1 tritt das Problem nicht auf.
Es wird rechts plötzlich ein Scrollbalken angezeigt

![image](https://user-images.githubusercontent.com/64688879/148779647-2472f2fe-a432-4d9a-aca2-06bd112d98e2.png)

**Comment by jens-maus** [comment]
Ok, nun bekomme ich es auch reproduziert (das Problem bzgl. Skript-Editor). Tritt wohl nur in Umgebungen auf (z.B. Linux, Windows) wo die Scrollbalken dynamisch eingeblendet werden. Unter macOS (wo ich eigentlich arbeite) passiert das nicht, weil da die Scrollbalken immer versteckt werden im Grunde. Hier scheint auch gerade das Skript-Editor PopUp nicht optimal designt worden zu sein und passt nicht gut zu den neuerlichen CSS Verbesserungen bzgl. Auto-Resize usw. Denn wenn man den Editor mal nach Rechts oder Unten aus dem Bild hinausschiebt bringt er eben diese Scrollbalken, die aber eigentlich nicht da sein sollten und die es bei anderen PopUps (auch nicht beim "Skript testen"-PopUp) auch nicht gibt.

Ob das allerdings das selbe/gleiche Problem wie bei dem Diagrammdarstellungen ist kann ich immer noch mangels Testmöglichkeiten noch nicht abschließend sagen.

**Comment by Lindi01** [comment]
Hallo Ich habe heute mit Windows Browser eine Seite Aufgemacht wo viel Werbung rechts immer neu patziert wird, da tritt auch ab und zu so ein Fehler auf. Ich habe ein Video gemacht da sieht man auf Seite 1 zuckt das Bild und Seite 2 ist es ruhig. Genauso wie meine Diagrammseite. Schaue ich die Seiten am Handy an , ist es ruhig. 
Vieleicht hilft das weiter.

https://user-images.githubusercontent.com/97434328/148800736-a81ba1cd-79bd-4add-a8fb-e3f8f1a91e0d.mp4

g

**Comment by jens-maus** [comment]
Nein, SPAM zeigen hat noch nie wirklich geholfen. Das ist wirklich was komplett anderes und es bringt nix auf ähnliche Probleme anderer Seiten zu verlinken.

Hab doch das issue bereits entsprechend markiert und arbeite an einer Lösung. Einfach bisschen Geduld haben.

**Comment by jens-maus** [comment]
Mit dem aktuellen nightly build sollte das Zucken ja nun zumindest bzgl. des Skript-Editors behoben sein. Hilfreich wäre noch, wenn jemand mit dem Zucken bzgl. Diagrammfunktion bitte mal mit dem aktuellsten nightly build schauen könnte ob dort auch das Problem nun beseitigt ist oder immer noch auftritt. Und wenn es immer noch auftritt, dann bitte ein anderes Issue-Ticket dazu aufmachen.

**Comment by Lindi01** [comment]
Hallo Jens
Wo finde ich die aktuelle Version.

Lindenthaler W.

Gesendet von Mail für Windows

Von: Jens Maus
Gesendet: Dienstag, 11. Jänner 2022 09:32
An: jens-maus/RaspberryMatic
Cc: Lindi01; Mention
Betreff: Re: [jens-maus/RaspberryMatic] Bild zuckt bei Programm - > Skriptbearbeiten (Issue #1653)

Mit dem aktuellen nightly build sollte das Zucken ja nun zumindest bzgl. des Skript-Editors behoben sein. Hilfreich wäre noch, wenn jemand mit dem Zucken bzgl. Diagrammfunktion bitte mal mit dem aktuellsten nightly build schauen könnte ob dort auch das Problem nun beseitigt ist oder immer noch auftritt. Und wenn es immer noch auftritt, dann bitte ein anderes Issue-Ticket dazu aufmachen.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jens-maus** [comment]
> Hallo Jens Wo finde ich die aktuelle Version. Lindenthaler W. Gesendet von Mail für Windows 

Erst einmal sei gesagt: Auf GitHub Benachrichtigungs-Emails antwortet man nicht via Email, denn ansonsten landet all das was du ggf. nicht willst (inkl. deines Realnames, etc.) im GitHub Issue Ticket!

Und die nightly snapshots bekommt man da wo es auch dokumentiert ist:
https://github.com/jens-maus/RaspberryMatic/releases/tag/snapshots

**Comment by Lindi01** [comment]
Mit der aktuellen nightly build ist das zucken im Diagramm auch behoben.

**Comment by mbhomie007** [comment]
Ich kann auch bestätigen das nun der Skript Editor nicht mehr "zuckt".

Vielen Dank für deinen Support! 🥇

**Comment by johnbubak** [comment]
Hallo,
Danke für die viele Arbeit die hier reingesteckt wird.

Mir fiel auf,  dass durch overflow: hidden im html tag es kaum noch möglich ist am Mobilen Gerät die Oberfläche zu bedienen.
Dazu fehlen jetzt die Scrollbalken. 

Mein Vorschlag wäre es mit overflow:scroll als Kompromiss für Funktionalität und flackerproblem zu versuchen.

Beste Grüße

**Comment by jens-maus** [comment]
Das Issue hier ist als close markiert und damit abgeschlossen und das ist hier auch kein Diskussionsforum. Auch sehe ich keinen Grund für irgendwelche Mobilgeräte Veränderungen vorzunehmen. Die CCU WebUI ist eine reine Konfigurationsoberfläche zum bearbeiten via Desktop Browsern. Insofern liegt der Fokus hier.
