### ISSUE TITLE
Bei Favoriten fehlen Kanäle

### ISSUE THREAD

**Issue by heitec11** [jens-maus/RaspberryMatic#1655]
### Describe the issue you are experiencing

Es fehlt in der Auswahlmöglichkeit bei Favoriten der Kanal 1, welcher die Temperatur beinhaltet.

Kanalauswahl bei Favoriten (nur Kanal 0 vorhanden):
![Kanal_Thermometer](https://user-images.githubusercontent.com/44260876/149074376-fde00911-8004-4761-91f4-1469dc9ece4f.jpg)

Werte des Kanal 1 von Status/Räume:
![Kanal_Thermometer_soll](https://user-images.githubusercontent.com/44260876/149074659-4c3ab6b8-2d24-4eb5-bb17-351487c1bc54.jpg)

### Describe the behavior you expected

?

### Steps to reproduce the issue

1. Einstellungen/Favoriten
2. Bearbeiten
3. Kanal hinzufügen
...

### What is the version this bug report is based on?

3.61.7.20211218

### Which base platform are you running?

rpi2 (RaspberryPi2)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
no
```

**Comment by jens-maus** [comment]
In der Überschrift schreibst du das allgemein. Das Beispiel zeigt aber nur ein Gerätetyp. Auch sehe ich nicht aus dem screenshot ob der kanal :1 nicht einfach weiter unten dann kommt.

**Comment by Baxxy13** [comment]
Kann ich so nicht bestätigen.
Tipp: 
Alle Kanäle eines Gerätes vernünftig benennen. 
Dann in der Kanalauswahl nach dem Namen oder nach Seriennummer filtern.
Beispiel:
![RM_Fav_alle_Kanäle](https://user-images.githubusercontent.com/54898249/149125189-f0703a02-3e9a-451e-863a-af70c1f5dd67.JPG)
