### ISSUE TITLE
WebUI: Setzen der Eventverzögerung bei HmIP-SAM nicht möglich.

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#1656]
Hier scheint es also in der Tat ein Problem bzgl. des Setzen der Werte der Eventverzögerung beim HmIP-SAM via WebUI zu geben. Folgende Ausgaben bekomme ich nämlich für die verschiedenen Units:

```xml
500ms:
<member><name>EVENT_DELAY_UNIT</name><value><i4>0</i4></value></member><member><name>EVENT_DELAY_VALUE</name><value><i4>5</i4></value></member>

30s:
<member><name>EVENT_DELAY_UNIT</name><value><i4>0</i4></value></member><member><name>EVENT_DELAY_VALUE</name><value><i4>30</i4></value></member>

15min:
<member><name>EVENT_DELAY_UNIT</name><value><i4>0</i4></value></member><member><name>EVENT_DELAY_VALUE</name><value><i4>15</i4></value></member>

1h:
<member><name>EVENT_DELAY_UNIT</name><value><i4>0</i4></value></member><member><name>EVENT_DELAY_VALUE</name><value><i4>1</i4></value></member>
```

Wie man unschwer sehen kann wird `EVENT_DELAY_UNIT` wohl gar nicht korrekt gesetzt von der WebUI.

_Originally posted by @jens-maus in https://github.com/jens-maus/RaspberryMatic/issues/1654#issuecomment-1011348431_

**Comment by Baxxy13** [comment]
Da ich die Änderungen nicht verstehe, kurze Frage dazu.

Ist/war das jetzt ein spezieller RaspberryMatic Fehler oder müsste der auch auf original CCUx auftreten?

**Comment by jens-maus** [comment]
Das tritt definitiv auch mit einer CCU3 Firmware auf.

**Comment by Baxxy13** [comment]
Ok, danke. 
Unser dtp (Torsten) aus dem Homematic-Forum will den SAM vielleicht am WE mal mit der orig. CCU testen.
Ich habe das Testsetup erweitert damit er dann nicht in diesen Bug läuft. 
[SAM Test an CCUx](https://homematic-forum.de/forum/viewtopic.php?f=26&t=68135#p700236)
