### ISSUE TITLE
"touch /usr/local/addons/mediola/Disabled" überlebt kein Update (SD-Kartenwechsel)

### ISSUE THREAD

**Issue by roe1974** [jens-maus/RaspberryMatic#1660]
### Describe the solution you'd like

Um den Mediola Server offline zu nehmen, benötigt es die Datei "Disabled" im Verzeichnis "/usr/local/addons/mediola".
Die Datei überlebt jedoch kein Updater der RM (SD Kartenwechsel) da dieser ordner durch ".nobackup" vom User-Backup ausgenommen ist.

### Describe alternatives you've considered

Ich schlage vor die Abfrage (sofern das nicht Bestandteil von Mediola selbst ist) so zu ändern, dass die Datei "Disabled" auch ein Backup überlebt.

### Is your feature request related to a problem?

No

**Comment by jens-maus** [comment]
Um den Mediola NeoServer dauerhaft  abzuschalten muss man ja die Datei `/etc/config/neoDisabled` anlegen (siehe https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/package/neoserver/overlay/etc/init.d/S97NeoServer#L14) und nicht die Disabled Datei wie du hier darlegst. Das ist eine rein interne Steuerdatei.

Der eigentliche Weg (und das ist seid ein paar Versionen der präferierte Weg) ist, unter dem neuen Einstellungs-PopUp `Einstellungen-> Systemsteuerung -> Erweiterte Einstellungen` den NEO Server Autostart via WebUI abzuschalten - das setzt nämlich genau diese `neoDisabled` Datei. Und diese ist dann auch Teil eines sbk Backups.

**Comment by roe1974** [comment]
Sorry ... "/etc/config/neoDisabled" hat in einigen Versionen nicht funktioniert .... werde es aber nochmal versuchen
DANKE !
lg RIchard

**Comment by roe1974** [comment]
funktioniert ! DANKE !!! ... da ist sogar der Button weg ... cool !
lg Richard
