### ISSUE TITLE
Darstellungsfehler in Einstellungen/Geräteübersicht, Unterer blauer Rand zu groß bei bestimmten Auflösungen 

### ISSUE THREAD

**Issue by drose28357** [jens-maus/RaspberryMatic#1661]
### Describe the issue you are experiencing

Bei Benutzung auf meinen Tablett ist der untere blaue Rand im Dialog Einstellungen/Geräteübersicht unter dem Button "zurück" zu groß. In den anderen Dialogen taucht dieses Problem nicht auf.

Der Bug ist sicherlich minor ;-)

### Describe the behavior you expected

Gleiches Verhalten bzgl. der Position des "zurück" Buttons wie bei den anderen Dialogen. Keinen ausgedehnten baluen bereich unter dem "zurück"-Button

### Steps to reproduce the issue

1. Einloggen in RM mit Chrome auf Windows 11
2. in Chrome die F12-Taste drücken für die Devtools-Konsole.
3. Dort eine andere Testauflösung "hier: responsive Design" auswählen. (Siehe anliegendem Video)
4. in der RM zu Einstellungen/Geräteübersicht springen.
5. Horizontal-Slider für die Bildschirmauflösung verschieben. ggf. den Zoom-Faktor anpassen. In bestimmten Situationen wird ein großer blauer Bereich angezeigt.
Siehe anliegendes Video.
ggf. mit anderen Dialogen wiederholen...

### What is the version this bug report is based on?

3.61.7.20220115

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
n.a.
```

### Additional information

https://user-images.githubusercontent.com/11533286/149662536-302ef05c-2900-4c2d-ad5a-c290b6392e17.mp4

**Comment by drose28357** [comment]
Noch drei weitere Dialoge gefunden. Siehe anliegende Screenshots und deren Dateinamen.
![RM_Direktverknüpfgungen_Screenshot 2022-01-16 145231](https://user-images.githubusercontent.com/11533286/149662942-8e67dff6-c65d-4462-bb0c-7b796106c312.png)
![RM_Status-Bedienung_Programme_Screenshot 2022-01-16 145411](https://user-images.githubusercontent.com/11533286/149662960-3be66d0d-2229-4ca1-935e-c6cd94b0e7f0.png)

![RM_Programmübersicht_Screenshot 2022-01-16 145141](https://user-images.githubusercontent.com/11533286/149662963-236e0441-e1b2-4b32-b34a-cf88669c0c15.png)

**Comment by jens-maus** [comment]
Ok, ich bekomm das mit Chrome entsprechend reproduziert. Jedoch nicht mit Firefox und anderen Browserengines. Vllt. hat @ptweety ja eine Idee wie man das Browser-übergreifend reparieren/optimieren kann damit der `footer` auch wirklich in jeder situation die selbe höhe hat und die dynamische `#content` Höhe `calc(100% - 168px)` wirklich immer passt. Ich hab schon ein bisschen versucht das zu optimieren/reparieren. Aber bisher leider ohne erfolg.

**Comment by drose28357** [comment]
Auffällig ist, das das Problem nur bei einigen Dialogen auftritt. Eigentlich sollte doch der Footer und dessen Einbindung in die Seite immer gleich funktionieren.

**Comment by ptweety** [comment]
Hi, das Problem ist zweischichtig.

1. Die WebUI ist nicht für Mobile Geräte / Tablets entwickelt und daher eigentlich nur für Desktop-Browser gedacht.
2. Mobile Geräte behandeln Web-Inhalte nicht so, wie ein Desktop-Browser und versuchen den Inhalt gemäß ihrer Display-Größe zu skalieren.

Hier hilft die explizite Definition des Viewport für Mobile Geräte in `www/rega/pages/index.htm`:

`<meta name="viewport" content="width=device-width, initial-scale=1.0">`

Zum verstehen hier noch ein kleines Video von YT: https://www.youtube.com/watch?v=SElOdK2qTpI

**Comment by ptweety** [comment]
@jens-maus 
ich habe gerade mal lokal _gespielt_ und denke, man könnte evtl. mit einer Anpassung bei der Skalierung knapp davonkommen:

`<meta name="viewport" content="width=device-width, initial-scale=0.8">`

Aber für mehr habe ich leider die Woche nicht die Zeit ...

**Comment by drose28357** [comment]
Gerätespezifische Skalierungen wird nicht die Ursache des Fehlers fixen. Mein S5e z.B. hat 2560x1600, die billigen Android-Tablets haben manchmal 1025x768.

Ein Test der Anzeige der Elemente in der Dev-Console von Chrome zeigt für Einstellungen/Geräte eine fehlerhafte Berechnung des body. Der Body in Geräte wird zu klein dargestellt. Vergleiche dazu auch die funktionierende Darstellung Einstellungen/Geräte-Firmware im Anhang. Bei "Geräte" sieht man, das der body zwar die gleichen Pixel-Dimensionen wie das gewählte Fenster hat, jedoch kleiner dargestellt wird. Im anderen Dialog ist dieser Fehler nicht zu sehen.     Da muss irgendetwas strukturell falsch sein.
![WebUI_Body-Frame_Geräte-Firmware_ok](https://user-images.githubusercontent.com/11533286/149910827-e93228eb-44c5-4426-9057-8d7f54b303a5.png)
![WebUI_Body-Frame_Geräte_zu_klein](https://user-images.githubusercontent.com/11533286/149910854-66a4450a-58fa-484e-b72b-f23b8eee76fd.png)

**Comment by jens-maus** [comment]
> Ein Test der Anzeige der Elemente in der Dev-Console von Chrome zeigt für Einstellungen/Geräte eine fehlerhafte Berechnung des body. Der Body in Geräte wird zu klein dargestellt. Vergleiche dazu auch die funktionierende Darstellung Einstellungen/Geräte-Firmware im Anhang. Bei "Geräte" sieht man, das der body zwar die gleichen Pixel-Dimensionen wie das gewählte Fenster hat, jedoch kleiner dargestellt wird. Im anderen Dialog ist dieser Fehler nicht zu sehen. Da muss irgendetwas strukturell falsch sein.

Das hast du prinzpiell fast richtig zusammengefasst. Der Ursprung bzw. Grund des Problem ist die `calc(100% - 168px)` CSS Anweisung in `#content`. Diese sollte eigentlich in Abhängigkeit der Browser-Höhe eben die `#content` Höhe auf 100% - 168px setzen was im normalen Falle auch funktioniert und andere Browsertypen (Safari, Firefox) wohl auch problemlos machen (soweit ich das testen konnte). Lediglich in Chrome/Chromium tritt dieser Fehler auf. Ich konnte bisher aber auch keinen anderen Weg finden der das Problem umgeht. In Chrome funktionierte zumindest einfach in der definition von `#Layer0` statt `position: absolute` auf `position: fixed` zu ändern und dann auch dort noch `width: 100%` hinzuzufügen. Allerdings hat das dann andere Probleme in Safari z.B. heraufbeschwört die ich mit dem entfernen des `width: 100%` bereits früher gefixt hatte.

Wenn jemand allerdings einen Fix/Workaround dafür findet der auf allen großen Browserengines reproduzierbar funktioniert wäre ich natürlich dankbar dafür. Momentan sieht es aber so aus, das der momentane Stand wohl den "besten" Kompromiss darstellt und ich hab keine Ahnung warum Chrome hier das `calc(100% - 168px)` ab einem gewissen punkt falsch berechnet wenn man es auf einem Tablet/Smartphone wie oben gezeigt anzeigen lässt.

**Comment by drose28357** [comment]
Oooh, ein Chrome-Fehler. ev. wird der Fehler auch in Edge auftauchen, wenn die die Chrome-Engine verwenden.
Dann sollten wir hier nicht weiter forschen und auf ein Chrome-Update hoffen. 

Nur der Vollständigkeit halber noch zwei Screenshots, die sich nur in der Menge der gefilterten Elemente unterscheiden. Aber wahrscheinlich helfen die jetzt hier mehr
![WebUI_Geräte_kein_Filter](https://user-images.githubusercontent.com/11533286/149914457-b9e34ab0-f5ab-47f5-b77a-8104162f3437.png)
![WebUI_Geräte_leeres Filterergebnis](https://user-images.githubusercontent.com/11533286/149914471-4034d1f8-a3a8-4969-898e-575a0095cba8.png)
.

**Comment by jens-maus** [comment]
> @drose28357 füge doch bitte mal das von mir oben genannte meta tag ein und lade die Rega neu. Dann kannst du deine Tests wiederholen, aber bitte nach jeder Größenänderung auch mal die Seite neu aufrufen und vergleichen, ob es damit gut ist.

Meine Tests mit der viewport Anpassung zeigen das es das Problem nur verschiebt aber nicht für alle Größeneinstellungen behebt. Auch halt ich es nicht für sinnvoll nun dauerhaft den viewport auf 0.8 zu skalieren nur damit man ggf. mit gewissen Tablets dann mehr Luft hat. Hier brauch es eine entsprechende Lösung oder detaillierte Analyse warum das `calc(100% - 168px)` für `#content` nicht immer zu funktionieren scheint.

**Comment by drose28357** [comment]
Ich stocher laienhaft in der Dev-Console herum. Habe zwei Fenster auf meine RM offen, eine mit Geräte, eine mit Geräte-Firmware.
Eine Calc-Berechnung sehe ich in 
#content {
    background-color: #ffffff;
    overflow: auto;
    display: flex;
    align-items: flex-start;
    outline: none;
    height: calc(100% - 168px);
}
Höhenberechnung (100%-168px) funktioniert in beiden Fenstern.
Nicht jedoch die width Berechnung. Die steht bei Geräte immer auf 1293.42px, es sei denn, ich verschiebe den Viewport in der X-Achse auf über 1300 px. Da also bei einem z.B. 1000px breitem Bildschirm eine Width von 1293 vorgegeben wird, skaliert irgendwer (flex ?) den content runter. Hier ein Beispiel im Anhang.

![WebUI_Width-Berechnung_falsch](https://user-images.githubusercontent.com/11533286/149932157-b5cb3503-3a19-4cc2-b1fb-e47d2f4f6f4d.png)
 
Irgendwo wird die width bei kleiner 1293 auf 1293 festgenagelt. Das scheint im #Layer0 zu passieren
![WebUI_Width-Berechnung_falsch_2](https://user-images.githubusercontent.com/11533286/149933061-cb433159-bc03-4922-b1bc-5b5d661f9976.png)

Ich verstehe die Struktur der CSS-Dateien nicht.
Aber in Style.cgi wird Layer0 definiert. Darin ist width nur für -moz- definiert ? 
/* Haupt-Fenster */
.Layer0 {
  height: 100%;
  width: -moz-available; /* otherwise firefox does not resize to max browser width */
}
Laut CSS-Definition ist der Default auto -> This is default. The browser calculates the height and width.
d.h. da hight auf 100% festgenagelt ist, kann bei chrome width = auto gesetzt sein, das aber nicht 100% sein muss.

Lösung: (zum Nachstellen: Man kann in der Dev-Console das CSS editieren !)
Wenn ich in der Dev-Console in style.cgi bei .Layer0 width auf  "auto;" ändere, bekomme ich meine fehlerhafte Darstellung. Ändere ich width auf 100%, ist die Darstellung korrekt !!!! 

So funktioniert es bei mir:
/* Haupt-Fenster */
.Layer0 {
  height: 100%;
  **width: 100%;**
  width: -moz-available; /* otherwise firefox does not resize to max browser width */
}

**Comment by jens-maus** [comment]
> So funktioniert es bei mir:
```
/* Haupt-Fenster _/ .Layer0 { height: 100%; width: 100%; width: -moz-available; /_ otherwise firefox does not resize to max browser width */ }
```

Klar funktioniert das so erst einmal augenscheinlich. Hatte ich ja so auch schon gesagt.

Nur hilft das nix wenn man dann Safari Nutzer ist, denn genau dieses `width: 100%` müsste ich ja bereits entfernen weil ansonsten mit Safari die Tabellen keinen word-wrap mehr machen (warum auch immer). Siehe https://github.com/jens-maus/RaspberryMatic/pull/1550#issuecomment-977642751.

Deshalb ist der Kompromiss zu `width: -moz-available` ja entstanden.

**Comment by drose28357** [comment]
Habe noch etwas vergleichende Forschung betrieben.
Wenn ich in der Geräte-Ansicht im Content das Element mit dem tbody (also die Tabelle) lösche, wird der footer wieder korrekt berechnet.
Generell sind die Tabellen in Geräte und Firmware-Übersicht komplett verschieden implementiert.
Hier die Zeile, die ich in der Dev-Console gelöscht habe:
![WebUI_Geräte_tdody](https://user-images.githubusercontent.com/11533286/149956827-a50bc1a4-d24a-467c-8485-12004336b3d1.png)
hier das ergebnis:
![WebUI_Geräte_tdody_gelöscht](https://user-images.githubusercontent.com/11533286/149957266-32177fcc-e161-4aaf-af47-75996ff2bca3.png)

**Comment by jens-maus** [comment]
> Habe noch etwas vergleichende Forschung betrieben.
> Wenn ich in der Geräte-Ansicht im Content das Element mit dem tbody (also die Tabelle) lösche, wird der footer wieder korrekt berechnet.

Das ist jetzt nur sehr eingeschränkt eine neue Erkenntnis, denn natürlich stimmt die Footer-Darstellung auch wenn nur 1 Gerät oder kein Gerät zu sehen ist. Es ist also stark davon abhängig wieviele Geräte in `DeviceListTable` am Schluss sind und ob damit `#content` überfüllt ist sodass man da scroll muss. Genau dann geht eben diese `calc(100% - 168px)` Berechnung falsch. Zumindest waren das meine Erkenntnisse bis dahin.

**Comment by drose28357** [comment]
Habe mir jetzt die TableRow (<tr>) von tbody in der DevConsole angesehen (Hier: Ansicht der Direkten Verknüpfungen).
Jedenfalls scheint das löschen von tbody Rückwirkungen auf die Berechnung der width in Layer0 zu haben. Unklar ist, warum es sich bei verschiedenen Tabelle(-Implementierungen) verschieden verhält.

Die TableRows scheinen auf mindest-Breiten festgelegt zu sein. In der Summer ergeben sie dann die festgelegte Breite von  1169,38, die sich nicht ändert, wenn man die Bildschirmbreit unterhalb von 1194 verschiebt. 
Diese Festgelegte Tabellenbreite wird dann irgendwie vom Browser in den Layer0 "hochvererbt". Dieser Zoom im Content kann man auch gut daran erkennen, das sich die Schriftgrößer verändert. Spooky ! In der class CLASS22106 wird jedenfalls keine Spaltenbreit festgelegt.
Vergrößert man die Bildschirmbreite über 1194 px darüber hinaus, wird z.B. die dritte Spalte (Name) größer, wären die ersten beiden weiterhin ihre feste breite haben. Damit passt auch der Footer wieder in den Content.

Breite in Pixcel	TableRow-Elemente in Direkte Verknüpfungen
**1169,38**		<tr>
201,89		<td class="CLASS22106">..</td>
130,18		<td class="CLASS22106">..</td>
216,15		<td>..</td>
199,89		<td style="background-color:#E0E0E0">..</td>
83,1		<td class="CLASS22106">..</td>
207,98		<td class="CLASS22106">..</td>
130,18		<td class="CLASS22106">..</td>
			</tr>
Summe:	
**1169,37**	

Vergleich mit der funktionierenden Firmware-Übersicht: Dort verhalten sich die festen Spaltenbreiten genauso. 
Ich gebe (für heute) auf ;-)

**Comment by drose28357** [comment]
Ich habe keine Ursache, bzw Lösung gefunden. Im Vergleich aller Tabellen ist mir aufgefallen, das anscheinend jede Tabelle anders implementiert ist, teilweise mit <thead>, teilweise nur mit <tr> etc etc. 
Wir sollten dieses Issue schließen und falls wir das WebUI neu und moderner implementieren, generalisierbare Lösungen für Tabellen und Tabellen-Köpfe (mit Spalten-Gruppen, Filter, Sortierung) entwerfen.

**Comment by jens-maus** [comment]
> Wir sollten dieses Issue schließen ...

Das sehe ich nicht so. Das Issue existiert und ggf. findet jemand ja einen Workaround der auf allen Browser-Engines greift. Habe immer noch Hoffnung das @ptweety irgendwann die Zeit findet da mal drüber zu schauen. Bis dahin bleibt das Issue offen.

**Comment by drose28357** [comment]
Nachgeprüft mit 3.63.9.20220521:
Fehler in meinen Testfällen nicht mehr vorhanden.
