### ISSUE TITLE
Unterschiedliche Schreibweise von "Ein" und "Aus" zwischen BidCos und HmIP-Geräten

### ISSUE THREAD

**Issue by kalwados** [jens-maus/RaspberryMatic#1662]
### Describe the issue you are experiencing

Kosmetisches Problem:
Im WebUI werden für HmIP- und BidCos-Geräte unterschiedliche Schreibweisen für die Schaltzustände "Ein" bzw "Aus" verwendet; siehe Screenshot:
HmIP:   Ein/Aus
BidCos: ein/aus

![RaspberryMatic-WebUI-GrossKleinscheibung](https://user-images.githubusercontent.com/11840444/149664534-0aea0e97-a808-4bff-a17b-7222b3a99f44.png)

### Describe the behavior you expected

Erwartet: Gleiche Schreibweise; unabhängig vom Gerätetyp.

### Steps to reproduce the issue

Steps: 
In einem Programm zwei Geräte unterschiedlicher Funksysteme verwenden, z.B. HmIP-PS und HM-LC-SW1

### What is the version this bug report is based on?

3.61.7.20220115

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
n/a
```

**Comment by blackbasket** [comment]
Kommt das nicht aus dem closed source?

**Comment by jp112sdl** [comment]
Nein, das kommt aus der `/www/webui/js/lang/.../translate.lang.stringtable.js` und wird so geschrieben, wie der Entwickler gerade Lust hatte:

grep Schaltzustand:
```
translate.lang.stringtable.js:    "stringTableAlarmActuatorStateFalse" : "Schaltzustand: Aus",
translate.lang.stringtable.js:    "stringTableAlarmActuatorStateTrue" : "Schaltzustand: Ein",
translate.lang.stringtable.js:    "stringTableDigitalAnalogInputStateFalse" : "Schaltzustand: aus",
translate.lang.stringtable.js:    "stringTableDigitalAnalogInputStateTrue" : "Schaltzustand: ein",
translate.lang.stringtable.js:    "stringTableDigitalAnalogOutputStateFalse" : "Schaltzustand: aus",
translate.lang.stringtable.js:    "stringTableDigitalAnalogOutputStateTrue" : "Schaltzustand: ein",
translate.lang.stringtable.js:    "stringTableDigitalInputStateFalse" : "Schaltzustand: aus",
translate.lang.stringtable.js:    "stringTableDigitalInputStateTrue" : "Schaltzustand: ein",
translate.lang.stringtable.js:    "stringTableDigitalOutputStateFalse" : "Schaltzustand: aus",
translate.lang.stringtable.js:    "stringTableDigitalOutputStateTrue" : "Schaltzustand: ein",
translate.lang.stringtable.js:    "stringTableInputOutputStateFalse" : "Schaltzustand: aus",
translate.lang.stringtable.js:    "stringTableInputOutputStateTrue" : "Schaltzustand: ein",
translate.lang.stringtable.js:    "stringTableStateFalse" : "Schaltzustand: Aus",
translate.lang.stringtable.js:    "stringTableStateTrue" : "Schaltzustand: Ein",
translate.lang.stringtable.js:    "stringTableStatusIndicatorStateFalse" : "Schaltzustand aus",
translate.lang.stringtable.js:    "stringTableStatusIndicatorStateTrue" : "Schaltzustand ein",
translate.lang.stringtable.js:    "stringTableSwitchStateFalse" : "Schaltzustand: aus",
translate.lang.stringtable.js:    "stringTableSwitchStateTrue" : "Schaltzustand: ein",
```

**Comment by jp112sdl** [comment]
Wenn es einen Konsens zur Schreibweise gibt, würde ich dafür mal einen Patch bauen.
Ich wäre für `Schaltzustand: ein`.  (Kleinschreibung)

_Und falls es funktioniert, würde ich die Übersetzung nur 1x hinzufügen und an den verwendeten Stellen dann nur verweisen,
wie bei der [translate.lang.js](https://github.com/eq-3/occu/blob/master/WebUI/www/webui/js/lang/de/translate.lang.js#L1-L33)_

**Comment by jens-maus** [comment]
> Wenn es einen Konsens zur Schreibweise gibt, würde ich dafür mal einen Patch bauen. Ich wäre für `Schaltzustand: ein`. (Kleinschreibung)

Ich plädiere wie immer dafür so wenig wie möglich Änderungen in der WebUI vorzunehmen. D.h. in der Tat die Kleinschreibung zu präferieren.

> _Und falls es funktioniert, würde ich die Übersetzung nur 1x hinzufügen und an den verwendeten Stellen dann nur verweisen, wie bei der [translate.lang.js](https://github.com/eq-3/occu/blob/master/WebUI/www/webui/js/lang/de/translate.lang.js#L1-L33)_

Das würde IMHO zu viele unnötige Änderungen hervorrufen, da du ja alle Stellen dann anpassen müsstest wo der String "Schaltzustand: ein/aus" gerade verwendet wird. Insofern würde ich alles so belassen und lediglich ein patch machen der die `translate.lang.stringtable.js` entsprechend an diesen 4 Stellen patcht. Fertig.

**Comment by jens-maus** [comment]
Und am besten integrierst du diesen Minor change einfach in den bereits bestehenden `0143-WebUI-Fix-Translation` WebUI patch.

**Comment by jp112sdl** [comment]
Jap, klingt am sinnvollsten. Mach ich so
