### ISSUE TITLE
fehlender Zeilenumbruch: Popup-Inhalte verschieben sich nach Datei-Auswahl bei Datei-Uploads

### ISSUE THREAD

**Issue by jp112sdl** [jens-maus/RaspberryMatic#1666]
### Describe the solution you'd like

Wird bei einem Datei-Upload (z.B. Einspielen eines Backups) eine Datei mit einem langen Dateinamen gewählt, so verschiebt sich der gesamte Popup-Inhalt:

<img width="184" alt="Bildschirmfoto 2022-01-18 um 08 16 34" src="https://user-images.githubusercontent.com/18190139/149903362-f59f70c7-a350-43aa-816e-863df3445ef6.png">

### Describe alternatives you've considered

Umgesetzte Lösung von hier: https://stackoverflow.com/questions/51078664/input-type-file-wrap-long-file-name-text

<img width="200" alt="Bildschirmfoto 2022-01-18 um 08 17 49" src="https://user-images.githubusercontent.com/18190139/149903631-167b42a4-211c-4740-9389-c43e0ef74bbd.png">

### Is your feature request related to a problem?

No

**Comment by jens-maus** [comment]
Mit welchem Webbrowser passiert denn das bitte das der Dateiname nicht abgebrochen oder abgekürzt wird? Weil hier mit Chrome unter macOS wird automatisch der Dateiname verkürzt (mit ...) dargestellt egal wie lange er ist:

<img width="801" alt="Bildschirmfoto 2022-01-18 um 15 10 20" src="https://user-images.githubusercontent.com/5887769/149953058-ec04803e-87ec-4598-8f0a-cfacb72534e8.png">

**Comment by jp112sdl** [comment]
> Mit welchem Webbrowser passiert denn das bitte das der Dateiname nicht abgebrochen oder abgekürzt wird?

Firefox 96.0.1 sowohl Mac als auch Win.

**Comment by jens-maus** [comment]
D.h. diese Patch bringt nur für Firefox etwas, so wie es aussieht. Denn selbst unter Safari wird automatisch der Dateiname via "..." abgekürzt. Die Frage wäre also ob es nicht irgendeine andere Art von Browser-Optimierung oder Workaround gibt die diese darstellung in Firefox wie bei Chrome+Safari aussehen lässt?

**Comment by jp112sdl** [comment]
Ja das ist ja echt nervig, dass der FF sich da wieder anders verhält.

Dann würde ich sagen, lass den Patch draußen, weil da ja doch ne Menge verändert wird.
Ich bau mir da selbst was für mich.

**Comment by jens-maus** [comment]
> Ja das ist ja echt nervig, dass der FF sich da wieder anders verhält.

Tja, da fühlt man sich gleich mal wieder in die Anfangszeit der Browserentwicklung ala Netscape vs. Internet Explorer zurückversetzt wo jeder Browser sein eigenes "Dinge" gemacht hat. Da kann man nur froh sein kein Webentwickler zu sein :) Die Hoffnung ist aber weiterhin das wenn wir erstmal vollwertig Bootstrap mit an Bord haben wir dann sukzessive das nehmen können und das kümmert sich ja dann genau um solche nervigen details.

> Dann würde ich sagen, lass den Patch draußen, weil da ja doch ne Menge verändert wird. Ich bau mir da selbst was für mich.

Och ne, jetzt hast du dir aber solch Mühe gemacht und wenn das trotzdem unter Safari+Chrome gut aussehen sollte würde ich weiterhin dafür plädieren deine Anpassungen zu übernehmen/integrieren.

**Comment by TomItNet** [comment]
Das Beschriebene Verhalten im Mozilla Firefox führt, glaube ich, dazu, dass das Backup nicht geladen werden kann, da der Klick auf den Button anscheinend nicht registriert wird. In jedem Fall gibt es keinerlei Rückmeldung. MS Edge zeigt in der Statusleiste den Status des Uploads in % an. Dies geschieht beim Firefox nicht oder nicht mehr (kann ich nicht genau sagen).
Ist es denkbar, dass durch die Verschiebung die Funktion des Buttons "Backup Einspielen" beeinträchtigt ist?

**Comment by jens-maus** [comment]
Von welcher Version redest du? Und bitte screencast zeigen damit man sich darunter auch etwas vorstellen kann.

**Comment by TomItNet** [comment]
Ich beziehe mich auf den obersten Screenshot in diesem Issue.

**Comment by TomItNet** [comment]
Version ist die aktuelle.

**Comment by jens-maus** [comment]
Das hier aufgezeigte Problem mit dem Popup wurde doch bereits im aktuellen nightly snapshot behoben (deshalb ist das Ticket/Issue ja auch "closed"). Insofern einfach auf das nächste offizielle Release warten.
