### ISSUE TITLE
Update Fehler

### ISSUE THREAD

**Issue by Phil7989** [jens-maus/RaspberryMatic#1668]
### Describe the issue you are experiencing

Update direkt auf CCU3 laden schlägt fehl.
![5F7CB6D2-2013-45F0-A1B2-E9FB447E3990](https://user-images.githubusercontent.com/19151312/149946391-15681070-c625-4c95-ba87-56107dedff54.jpeg)

### Describe the behavior you expected

Update direkt von der CCU ausführen. 
Hat beim letzten Mal auch geklappt.

### Steps to reproduce the issue

1. WebUI öffnen
2. Direkt auf CCU laden und installieren

### What is the version this bug report is based on?

3.61.7.20211218

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
/var/log
```

**Comment by jens-maus** [comment]
Nun, die Meldung ist wohl recht eindeutig! Du hast nicht genug Speicherplatz auf deiner CCU3 mehr frei um das Update durchzuführen. Vmtl. hast du beim Umstieg von der CCU3 Firmware zu RaspberryMatic nicht Schritt 9 der Installationsanleitung befolgt (siehe https://github.com/jens-maus/RaspberryMatic/wiki/Installation-CCU3). Dort wird explizit davon geschrieben das man nach der Installation von RaspberryMatic VOR einspielen des Backups noch ein kompletten System-Reset/Werks-Reset durchführen soll damit die Nutzerpartition der CCU3 auf die maximale Größe vergrößert wird.

Das solltest du also nun erledigen. D.h. ein Backup (*.sbk) anlegen, dann Werks-Reset machen, dann Backup wieder einspielen und dann sollte danach das Update auch funktionieren.
