### ISSUE TITLE
Hardware Support for BananaPi M3 board

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#167]
To support more 2GB type hardware board we should evaluate the possibilities to support the BananaPi M3 board in RaspberryMatic. See here for more information on the board:

http://www.banana-pi.org/m3.html

**Comment by jens-maus** [comment]
Sorry, but BananaPi-M3 support will not be worked on. Use Tinkerboard or RaspberryPi which are perfect matches.

**Comment by libertyx82** [comment]
And what about the Banana-Pi M4?
http://www.banana-pi.org/m4.html

It has also an PCIe M2 Slot :)

**Comment by jens-maus** [comment]
For RaspberryMatic to run on, we need ARM hardware that is able to run also a 32bit Linux. And I am not sure if the ARM on the BananaPi M4 allows that or if there is U-Boot support for that board with 32bit mode in mind.

**Comment by libertyx82** [comment]
According to the Wiki it supports an Debian buster 32Bit

http://wiki.banana-pi.org/Banana_Pi_BPI-M4#Debian_linux

**Comment by Tscherno** [comment]
Any chance with the new generation?
https://www.golem.de/news/bastelrechner-banana-pis-neuer-minirechner-ahmt-raspberry-pi-4b-nach-2012-152845.html

Main benefit: eMMC instead of SD storage.

**Comment by jens-maus** [comment]
@Tscherno Thanks for the hint. However, I am not sure if the number of users would be high enough to justify the work that has to be spent to get this board running with RaspberryMatic. Thus, if you just need eMMC you can take an "ASUS Tinkerboard S" instead and changes are hight that I will also support the new v2 version of the Tinkerboard anytime soon.
