### ISSUE TITLE
fehlerhafte Maßeinheit bei Energiezähler im Messkanal HmIP-BSM

### ISSUE THREAD

**Issue by Maik2208** [jens-maus/RaspberryMatic#1670]
### Describe the issue you are experiencing

Im Messwertkanal des HmIP-BSM wird die falsche Maßeinheit angeben. Mein Fernseher hat sicher keine 13.000kWh in den letzten Wochen verbraucht:
![image](https://user-images.githubusercontent.com/79879510/150020124-678fd3f8-a6af-40d7-94b1-e7229334d5c5.png)

### Describe the behavior you expected

Korrektur der Maßeinheit oder Austausch des Punktes gegen ein Komma.

### Steps to reproduce the issue

1. Status und Bedienung
2. Geräte
3. HmIP-BSM öffnen
4. Kanal 7 ansehen

### What is the version this bug report is based on?

3.61.7.20220115

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
nope
```

**Comment by Baxxy13** [comment]
Das ist doch kein Bug wenn einer zu viel fernsieht. ;-)
In der WebUI gibt es nun mal keine Komma's bei Zahlenwerten, es sei denn du schreibst sie in eine Text-SysVar.

**Comment by Maik2208** [comment]
Na dann musst du aber das k bei kWh entfernen oder eben auf ganze kWh runden. Aber 13tausend Kilowattstunden sind im Jahr allein knapp 4.000€ Strom für die Glotze 😁

**Comment by Baxxy13** [comment]
Na ich sehe da 13,212 kWh. 
Bei angenommenen 100W/h Verbrauch hast du also etwa 132h fern gesehen. 
Bei angenommenen 3h/d also 44 Tage.

Schaffe ich auch. :-D

**Comment by jp112sdl** [comment]
Ich bin da früher bei den HM Zwischensteckern auch schon drüber gestolpert.

Dadurch, dass Werte sonst überall mit 2 Nachkommastellen angezeigt werden, interpretiert man den Wert hier wohl sofort als vollen Tausender (wie im üblichen Schreibgebrauch), ohne Nachkomma.

Ist wirklich verwirrend und nicht schön. Das systemweit zu ändern wäre jedoch schon recht aufwendig, da `.ToString(2)` grundsätzlich einen Punkt als Dezimaltrenner verwendet.
Müsste man noch um einen Culture-Parameter erweitern, der je nach DE oder EN die Trenner "kulturkorrekt" ausgibt.

**Comment by jens-maus** [comment]
> Dadurch, dass Werte sonst überall mit 2 Nachkommastellen angezeigt werden, interpretiert man den Wert hier wohl sofort als vollen Tausender (wie im üblichen Schreibgebrauch), ohne Nachkomma.

Vllt. könnte man in der tat an der Stelle dafür sorgen das die dargestellten kWh Werte immer nur mit max 2 Nachkommastellen dargestellt werden. Dann sollte es zumindest etwas klarer sein.
 
>Das systemweit zu ändern wäre jedoch schon recht aufwendig, da `.ToString(2)` grundsätzlich einen Punkt als Dezimaltrenner verwendet. Müsste man noch um einen Culture-Parameter erweitern, der je nach DE oder EN die Trenner "kulturkorrekt" ausgibt.

Ich denke auch das es auf ein fast unendliches Unterfangen herauskommen würde jetzt zu versuchen überall ein `,` statt einem `.` in der WebUI für Gleitkommazahlen zu verwenden. Muss man halt einfach wissen das die WebUI keinerlei Tausendertrennung macht wie das im Deutschen vllt. hier/da üblich ist. Und International gesehen ist es eh doof das wir im deutschen ein `,` nutzen und kein `.` wie das eigentlich üblich ist.

**Comment by Baxxy13** [comment]
Muss man jetzt wirklich wegen 3 statt 2 "Nachkommastellen" da dran rumfummeln?

Gerade mal auf meinen digitalen Stromzähler geschaut...
`342.44 kWh` 
Auch mit `.` statt `,`... aber auch nur 2 Nachkommastellen.

**Comment by jp112sdl** [comment]
> aber auch nur 2 Nachkommastellen 

Bei 1,2 oder 4 Nachkommastellen kommt man auch nicht auf Idee, dass es sich um einen Tausendertrenner handeln könnte.

Nur 3 ist blöd... weil nach 999 nun Mal 1.000 kommt :) Oder doch 1000,000 ? Nee, das waren jetzt 1,000.

**Comment by jens-maus** [comment]
Ok, hab nun die besagte Stelle in der WebUI angepasst, sodass nun immer max. 2 Nachkommastellen angezeigt werden sollten. Das sollte das Problem / Verwirrung hoffentlich beseitigen.

**Comment by jp112sdl** [comment]
> Gerade mal auf meinen digitalen Stromzähler geschaut... 342.44 kWh

Bei mir sind es 4 Stellen. Am Gerät im Zählerschrank und auch in der WebUI:
<img width="240" alt="Bildschirmfoto 2022-01-19 um 21 08 57" src="https://user-images.githubusercontent.com/18190139/150205999-1f44a8e7-8fb6-4776-aa38-58181c5cb0ef.png">

Aber das kommt direkt vom Datenpunkt des HM-ES-TX-WM und sollte nicht von dem Fix betroffen sein.

> immer max. 2 Nachkommastellen angezeigt werden sollten. Das sollte das Problem / Verwirrung hoffentlich beseitigen.

Ja dann ist das einheitlich.

**Comment by Baxxy13** [comment]
27ct/kWh? Guter Preis. 
Meiner zeigt nur Wh an, ist per selbstgebautem S0-Adapter angeschlossen.
![RM-Stromzähler_WebUI](https://user-images.githubusercontent.com/54898249/150222606-505358d3-1f6d-49fd-bdec-2edef595c669.JPG)

**Comment by HolgerJeromin** [comment]
Ihr könntet auch 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString
nutzen. 
`13.219.toLocaleString(navigator.language)`
liefert mit mit einem auf deutsch eingestellten Browser
`'13,219'` 
und auf einem englischen Browser
`'13.219'`
jeweils devTools Ausgabe mit geladener WebGUI.
Interesse an einem PR?

**Comment by Maik2208** [comment]
Und wenn du statt navigator.language die in der GUI eingestellte Sprache einsetzt wäre es richtig geil 🤩

**Comment by jens-maus** [comment]
> Interesse an einem PR?

Wenn der PR nicht nur diese eine Stelle adressiert, sicherlich. Denn es gibt in der WebUI sicherlich zich stellen wo das anzeigen von float werten auch language-spezifisch angezeigt werden müsste.

**Comment by HolgerJeromin** [comment]
> Und wenn du statt navigator.language die in der GUI eingestellte Sprache einsetzt wäre es richtig geil 🤩

Das ist anders rum. Die webUI Sprache passt sich schon an navigator.language an.
In beiden getesteten Browsern nutzt die WebUI die jeweilige Sprache.

**Comment by Maik2208** [comment]
> Das ist anders rum. Die webUI Sprache passt sich schon an navigator.language an.


Aber nur, wenn die Sprache im Benutzerkonto auf Auto steht. Kannst du dort aber auch manuell auf Deutsch bzw. Englisch setzen.
