### ISSUE TITLE
Alle Geräte außer CUXD verschwunden

### ISSUE THREAD

**Issue by briearn** [jens-maus/RaspberryMatic#1673]
### Describe the issue you are experiencing

Update durchgeführt auf Version: 3.61.7.20220115 (rpi4)

dann auf Einstellungen - Geräte

und dann sind da normalerweise alle Wird Geräte, aber jetzt nicht mehr. Ausschließlich 2 CUXD Devices werden angezeigt.

Ein Reboot brachte keinerlei Änderung.
Auch bei "HM Wird Gerät suchen" wird nichts gefunden.

Die Direktverknüpfungen sind aber weiterhin vorhanden. Programme laufen auch weiterhin problemlos ab.

### Describe the behavior you expected

ich würde erwarten das die ganzen Geräte weiterhin angezeigt werden

### Steps to reproduce the issue

1.
2.
3.
...

### What is the version this bug report is based on?

3.61.7.20220115

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
/var/log/hmserver.log enthält nur INFO Meldungen

/var/log/messages enthält ERROR Meldungen zu vielen (vermutlich allen) Geräten:
Jan 20 20:20:08 raspimatic-pi4 local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1238, params: {"QEQ133XXXX:21","VALUE"}) [CallGetValue():iseXmlRpc.cpp:1435]
Jan 20 20:20:08 raspimatic-pi4 local0.err ReGaHss: ERROR: CallGetValue failed; sVal = 102.000000 [ReadValue():iseDOMdpHSS.cpp:124]
Jan 20 20:20:37 raspimatic-pi4 user.err hs485d: HSSParameter::GetValue() id=SENSOR failed getting physical value.
Jan 20 20:20:37 raspimatic-pi4 local0.warn ReGaHss: WARNING: XMLRPC 'getValue': rpcClient.isFault() failed (url: xmlrpc_bin://127.0.0.1:32000, params: {"OEQ010XXXX:6","SENSOR"}, result: [faultCode:-1,faultString:"Failure"]) [CallXmlrpcMethod():iseXmlRpc.cpp:2608]
```

**Comment by jens-maus** [comment]
Sorry, but this is no support or discussion fora here. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. This was also already mentioned in the ticket template!
___
Tut mir leid, aber das hier ist kein Supportforum, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen.  Dies stand übrigens auch so im Ticket Template!

**Comment by briearn** [comment]
Guten Abend Jens,

wenn die ganzen Geräte nach einem Upgrade weg sind, was meinst Du ganz persönlich und professionell was das ist? Ein Support request oder aber ein Bug?

Mit freundlichen Grüßen

Arne

**Comment by jens-maus** [comment]
Na wenn es bei zehntausend anderen prinzipiell funktioniert dann geh ich erst einmal von keinen Bug aus. Diskutiere das ganze erst in einem Diskussionsforum (das hier ist kein Diskussionforum!) und wenn sich da andere Nutzer finden die das selbe problem haben und man dort gemeinsam einen Bug identifizieren kann, dann kannst du hier gerne wieder herkommen.

**Comment by MichaelN0815** [comment]
Warscheinlich identisch mit https://github.com/jens-maus/RaspberryMatic/issues/1671

**Comment by jens-maus** [comment]
> Warscheinlich identisch mit #1671

Das kann natürlich gut sein. Müsste @briearn sagen ob er wirklich kein Funkmodul (RPI-RF-MOD, HM-MOD-RPI-PCB) nutzt oder doch...

**Comment by briearn** [comment]
ja, scheint identisch mit #1671 
ich benutze auch keinerlei Funkmodul. Wired Only....

**Comment by jens-maus** [comment]
Ok, dann wird es so sein.

**Comment by MichaelN0815** [comment]
Ist der Patch schon im aktuellen Nightly build?

**Comment by jp112sdl** [comment]
Ja, sollte drin sein.
