### ISSUE TITLE
Logdatei vom Startvorgang der Raspberrymatic erzeugen welche alles enthält was man sonst nur bei angeschlossenem Monitor sieht 

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1675]
### Describe the solution you'd like

Wie schon im [Homematic-Forum](https://homematic-forum.de/forum/viewtopic.php?f=56&t=70936&start=30#p702122) geschrieben würde ich es nützlich finden wenn das Startverhalten, zusätzlich zur Ausgabe auf einem angeschlossenen Monitor, in eine Logdatei geschrieben würde.

### Describe alternatives you've considered

-

### Is your feature request related to a problem?

Ich gucke mir bei den Tests der Nightlys auch meistens mindestens 1x den Bootvorgang an.
Mein Pi4B und das TinkerS harmonieren aber irgendwie nicht mit meinem WQHD Monitor, da muss ich jedes mal ein langes HDMI Kabel zum TV legen. 
Den Aufwand würde ich gerne einsparen. Da wäre eine Logdatei die ich nach dem Bootvorgang kontrollieren könnte recht praktisch.

**Comment by Baxxy13** [comment]
Getestet und für sehr gut befunden!

**Comment by jens-maus** [comment]
> Getestet und für sehr gut befunden!

Sehr gut. Aber bitte auch noch die anderen Platformen testen (z.B. HomeAssistant, usw.)

**Comment by kvsk48** [comment]
[Die Doku zu inittab](https://git.busybox.net/busybox/tree/examples/inittab) ermuntert nicht das 'id' Feld mehrfach zu benutzen. Ausser man nimmt "strange results" in Kauf. 
Und zu 'process' steht nicht, dass eine shell Syntax mit pipes und redirection erlaubt ist.
Traditionel ist inittab ein config file und kein Script. Je weniger da rein muss, desto besser.
Nach meiner Meinung  sollte die inittab so aussehen:
```
::sysinit:/etc/init.d/rcS.pre
tty3::respawn:/usr/bin/monit -Ic /etc/monitrc
tty2::askfirst:/sbin/getty -L tty2 0 vt100
::ctrlaltdel:/sbin/reboot
::shutdown:/etc/init.d/rcK
::shutdown:/bin/umount -a -r -f
::shutdown:/sbin/swapoff -a
```
/etc/init.d/rcS.pre so:
```
LOG=/tmp/boot.log
/bin/mount /proc
/bin/mount /sys
/bin/mkdir -p /dev/pts /dev/shm
/bin/mount /tmp
( /sbin/fsck -A -R -p
  /bin/mount -a
  /bin/mkdir -p /var/run /var/cache
  /sbin/ldconfig -C /var/cache/ld.so.cache
) 2>&1 | /usr/bin/tee -a $LOG
/usr/bin/psplash -n &
/etc/init.d/rcS 2>&1 | /usr/bin/tee -a $LOG
/bin/mv $LOG /var/log/boot.log
```
Die mount Aufrufe werden so gemacht, dass die Einstellungen von /etc/fstab übernommen werden, dann ist das konsistent.

Dieser Aufruf kommt dann noch in die rcK:
```
::shutdown:/usr/bin/monit unmonitor all
``` 

Unliebsame stdout/stderr Meldungen nach /dev/null zu schicken, erschwert die Fehlersuche, falls doch mal was schief geht.
Momentan ist mir das zuviel rumgebastelt.

**Comment by jens-maus** [comment]
> [Die Doku zu inittab](https://git.busybox.net/busybox/tree/examples/inittab) ermuntert nicht das 'id' Feld mehrfach zu benutzen. Ausser man nimmt "strange results" in Kauf.

Es sind aber keine "strange results" zu sehen und ich sehe auch keinerlei Problem darin bei jeder Ausgabe die in `tty2` landen soll auch dort tty2 hinzuschreiben. Und selbst in buildroot selbst wird in der `inittab` für mehrere Einträge hintereinander `null` verwendet (siehe https://github.com/buildroot/buildroot/blob/master/package/busybox/inittab). Kann hier also nichts kritisches oder gar verwerfliches erkennen.

> Und zu 'process' steht nicht, dass eine shell Syntax mit pipes und redirection erlaubt ist.

Es steht aber auch nicht das Gegenteil darin und es ist vollkommen valide und funktioniert ganz offensichtlich.

> Traditionel ist inittab ein config file und kein Script. Je weniger da rein muss, desto besser.

Da gebe ich dir prinzipiell recht. Da ich aber ohnehin mittelfristig auf OpenRC umstellen werde wird sich die `inittab` nutzung irgendwann komplett erübrigen. 

> Die mount Aufrufe werden so gemacht, dass die Einstellungen von /etc/fstab übernommen werden, dann ist das konsistent.

Kann man machen, muss man nicht.

> Dieser Aufruf kommt dann noch in die rcK:
> 
> ```
> ::shutdown:/usr/bin/monit unmonitor all
> ```

Ich erledige solche de-register dinge gerne (wenn es geht) an ort und stelle wo auch die entsprechende init funktion durchgeführt wurde. Eben damit man weiss warum das dort jetzt steht. Kann auch nichts kritisches daran erkennen monit innerhalb der inittab ein unmonitor zu schicken.

> Unliebsame stdout/stderr Meldungen nach /dev/null zu schicken, erschwert die Fehlersuche, falls doch mal was schief geht.

Das Leben ist voll von Kompromissen mit denen man Leben muss. Und wenn psplash mal nicht startet dann ist es auch nicht gar so schlimm nicht zu wissen wieso.

> Momentan ist mir das zuviel rumgebastelt.

Es steht dir frei RaspberryMatic nicht zu verwenden oder wegen dieser (deiner Meinung nach) inkonsistenten `inittab` einen Fork zu generieren. Oder noch besser: Du schickst einen entsprechenden PullRequest hier ein mit entsprechendem rationale, statt nur code-fetzen zu präsentieren.
