### ISSUE TITLE
Docker Netzwerk Hostmode und SSH aktiviert führt zu Container unhealthy

### ISSUE THREAD

**Issue by timwegenerDE** [jens-maus/RaspberryMatic#1676]
### Describe the issue you are experiencing

Hallo zusammen,
ich muss den Raspberrymatic Container im Hostmode betreiben, da ich das Plugin hap-homematic benutze. Wenn ich das richtig verstehe gibt dieses die Geräte über mDNS in Apples Homekit. Es gibt da scheinbar auch keine (schöne) Möglichkeit, mDNS im bridged Mode zu realisieren.

Das funktioniert im host mode aber soweit. Sobald ich jedoch in der Raspberrymatic UI SSH aktiviere und neustarte, wird mir der Container als „unhealthy“ angezeigt. Dazu wird fleißig mitgeloggt, dass sshd nicht an den Port 22 binden könnte, weil dieser schon benutzt wird.

Sowohl Raspberrymatic als auch SSH funktionieren m.E. aber fehlerfrei.

### Describe the behavior you expected

healthy

### Steps to reproduce the issue

1. Docker Container Netzwerk auf Host stellen
2. SSH in der Web UI aktivieren
3. Neustart
4. Container: unhealthy

### What is the version this bug report is based on?

3.61.7.20220115

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
SSHD kann nicht an Port 22 binden.
```

**Comment by jens-maus** [comment]
Wenn man RaspberryMatic so im Docker betreibt braucht man doch nicht zwingend ssh anschalten. Man kommt doch jederzeit vom docker host via `docker exec -it <CONTAINERID> /bin/sh` in den container rein.

Und wenn man den docker im hostmode betreibt, dann muss man natürlich dafür sorgen das auf dem host selbst dann auch port 22 (ssh) nicht selbst benutzt ist bevor man ssh anschaltet.

Insofern liest sich das hier viel mehr als ein Bedienungsproblem als ein bug/Unzulänglichkeit in RaspberryMatic selbst.

**Comment by timwegenerDE** [comment]
Ich komme dann aber gar nicht mehr per SSH auf den Raspberry, wenn ich das in der Web UI ausmache. Sobald der Raspberrymatic Container oben ist, überbügelt der mir das Setting aus der Raspi-Config.

Es läuft sonst nichts auf Port 22 (außer eben SSH vom Raspberry selbst).

**Comment by timwegenerDE** [comment]
Vielleicht hab ich mich schlecht ausgedrückt.
Die Web UI Einstellung überschreibt die SSH Einstellung des Host-Systems.

Da ja diverse Anwendungen (gerade im Smart Home Umfeld) auf mDNS angewiesen sind, werde ich wohl nicht der einzige sein, der auf den Betrieb im Host Mode angewiesen ist.

Wenn man auf dem selben Host noch Homebridge, Home Assistent (m.W. beides auf mDNS angewiesen) o.ä. ausführen will, kann es ja nicht die Lösung sein auf der ganzen Maschine SSH auszumachen.

Aber ja: Momentan „nur“ ein Schönheitsfehler, dass der Container als „unhealthy“ angezeigt wird. Zumindest konnte ich bisher keine negativen Auswirkungen (außer den fies klingenden Log-Eintrag) feststellen.

**Comment by jens-maus** [comment]
Das kann eigentlich nicht sein das bei deaktivieren von SSH in der WebUi von RaspberryMatic der SSH dienst des host systems mit deaktiviert wird.

Nochmal: du solltest in der RaspberryMatic ssh deaktiviert lassen und stattdessen im host system (dem docker host) ssh laufen lassen und dann via ssh somit in den host kommen und dann von dort (wenn du in das RaspberryMatic gelangen willst) das von mir benannte docker kommando nutzen.

Wenn du aber stattdessen via ssh zum host system immer im RaspberryMatic landen willst, dann muss du eben ssh im
Host system deaktiviert oder auf einen anderen port als 22 gelegt haben und dann in der WebUI von RaspberryMatic SSH aktivieren, dann können so auch zwei ssh daemons im gleichen hist netzwerk existieren - nur laufen sie dann eben auf unterschiedlichen ports.

**Comment by timwegenerDE** [comment]
Ich verstehe voll und ganz was du sagst, aber auf der Liste von Dingen die eigentlich nicht sein können, steht das bei mir sogar nur auf Platz 2. Auf Platz 1: Wenn ich den CCU Container runterfahre, geht der Host mit Down...

Aber jetzt nochmal zurück zum eigentlichen Problem:
- Auf dem Host ist SSH an, in Raspberrymatic auch.
- Ich mit im Terminal mit dem Host verbunden (sehe z.B. die Docker Volumes usw.)
- Ich deaktiviere in Raspberrymatic den Haken "SSH"
- Session friert ein, kein Verbinden mehr möglich
- Haken wieder setzen alles geht wieder.

Ich habe aber eine Lösung gefunden: Erst SSH in der Web UI deaktivieren, dann Docker Container beenden (Steht auf Unless Stopped). Dann stürzt der Host ab (oder fährt runter? Niemand weiss das), Strom weg, Strom dran, Maschine fährt ohne Raspberrymatic hoch, SSH im Host an, Docker Container starten (jetzt ja ohne SSH), alles geht, Container "healthy" 👍 

Kurzum: Danke für deinen (erneuten) Hinweis, dass das eigentlich nicht sein kann, das hat mich doch mal anders testen lassen.

Ich mach das hier mal zu, sollte jemand hier drüber stolpern und wissen, warum der Host mit dem Container down geht wäre ich für einen Hinweis dankbar - Kann ich aber (erstmal) mit leben. (Container ist mit dem Deploy-Script im Dezember 2020 installiert worden und nachträglich in den Host Mode gesetzt worden, Container sonst in der Standard Config).

**Comment by timwegenerDE** [comment]
Nehm ich zurück, hat 2 Minuten nach dem Start des Containers funktioniert. Jetzt komme ich mit SSH wieder nicht auf den Host.

**Comment by jens-maus** [comment]
Tut mir leid, aber das ist hier ja eigentlich kein Diskussions/Hilfe-Forum sondern ein Bug/Issue Tracker. Und ich mag hier weiterhin ehrlich gesagt kein bug oder issue in RM erkennen und für mich liest sich das alles immer noch mehr als ein Bedienungs/Einrichtungsproblem, denn ehrlich gesagt vermag ich immer noch nicht nachzuvollziehen wie man von innerhalb eines docker containers es schafft den hist herunterzufahren - ausser wie gesagt es wurde irgendwas nicht ganz korrekt eingerichtet/genutzt.

**Comment by timwegenerDE** [comment]
Alles gut, ich verstehe die Zweifel. Ich zweifle ja auch schon lange an mir, weil mir das nicht einleuchtet… Da der Container privileged läuft und ja mit pivccu auch (indirekt) bis auf den Host kommt kann ich mir das beides schon vorstellen ohne jetzt in die Tiefen des Codes abgetaucht zu sein… Wären die Raspberries aktuell nicht so unverschämt teuer, hätte ich auch ein Testsystem zur Hand auf dem ich das nochmal von Null an nachstellen könnte… Ich überleg mir mal was, um das nochmal nachzustellen und vielleicht etwas eingrenzen zu können.

**Comment by timwegenerDE** [comment]
Jetzt hab ich gerade noch einen Rpi 3 gefunden und wollte nochmal neu installieren zum Testen.

Bei `sudo modprobe eq3_char_loop` 
kann er jedoch das Modul nicht finden. Gibt es da aktuell ein Problem? Wenn ich pivccu vorher durchinstalliere via `sudo apt install pivccu3` funktioniert es. Allerdings weiß ich nicht, ob das andere Probleme verursacht?

Auf den ersten Blick konnte ich das o.a. Problem mit ssh und dem reboot in der leeren CCU nicht nachstellen, würde aber - wenn die Installation bezgl. des eq3_char_loop (wieder) durchläuft - es nochmal auf dem Rpi 4 nachstellen wollen (inkl. Config-Restore).

**Comment by timwegenerDE** [comment]
Nach einem Reboot nach der Umstellung des Netzwerk auf Host habe ich jetzt auch bei der frischen und leeren Installation das selbe Verhalten: SSH im Web UI steuert SSH des Hosts, Beenden des Containers (über Portainer: Container "Stop") fährt den Host herunter (oder führt zum Absturz des Hosts?). Einizger Unterscheid: Auf der Maschine musste ich bei der Installation den Weg über `install pivccu3` gehen, was ich auf meiner produktiv Umgebung m.W. nicht so gemacht habe. Aus meiner Sicht klar ein Bug (wenn es nicht an der vollen Installation von pivccu3 liegt).

**Comment by jens-maus** [comment]
Tut mir leid, aber ich kann dem ganzen immer noch nicht folgen. Innerhalb eines abgeschotteten Docker Containers kann man doch nicht (ohne weiteres) den Docker Host herunterfahren lassen oder gar dessen eigenen SSH daemon beenden lassen. Das sollte technisch doch schon nicht möglich sein wenn der Docker Container ordentlich gekapselt läuft.

Und tut mir leid, aber ich weiss auch ehrlich gesagt nicht warum du pivccu komplett installierst wenn du doch wie hier eigentlich RaspberryMatic im Docker haben willst?!?! Du musst dich da schon für eins der beiden entscheiden.

**Comment by timwegenerDE** [comment]
Probier es einfach aus, stell den Container auf Host Mode und schalte im Web UI SSH aus und schau ob du dich noch verbinden kannst bzw. fahr den Container einmal runter und schau was der Host macht. Ist doch in 3 Minuten nachgestellt (oder eben nicht).

Ich will pivccu3 nicht verwenden, aber wenn man der Anleitung [hier](https://github.com/jens-maus/RaspberryMatic/wiki/Installation-Docker-OCI) folgt, schlägt Schritt 7 fehl, weil das `eq3_char_loop` Modul fehlt. Da ich mir nicht anders zu helfen wusste, hab ich pivccu3 installiert, der das Modul an die richtige Stelle legt, womit Schritt 7 der Anleitung funktioniert und ich dann das deploy Skript ausführen konnte.

**Comment by timwegenerDE** [comment]
Mir ist das total klar und einleuchtend, dass der Container bridged laufen soll (sollten ja am besten alle), aber sobald jemand mDNS braucht gibt es einfach keinen ordentlichen Weg im im bridged Mode. Und im Smart Home Umfeld ist das jetzt nicht so selten, dass mDNS gebraucht wird (HomeKit, Home Assistent, ...).

Ich halte mich komplett an die Anleitung bis Schritt 7, aber das eq3_char_loop fehlt eben und ich habs nur mit `install pivccu3` an die richtige Stelle bekommen.

Nach Abschluss der Installation hab ich Portainer installiert wo ich dann einfach nur von Bridged auf Host stelle, sonst nichts. Alles Standard, frisches System, alle Updates drin...

**Comment by timwegenerDE** [comment]
Restart hab ich natürlich auch gemacht, nachdem ich diesen Kommentar gefunden habe: https://github.com/jens-maus/RaspberryMatic/issues/1106#issuecomment-774188200

**Comment by timwegenerDE** [comment]
Soooo den Fehler, warum `eq3_char_loop` nicht gefunden wird hab ich gefunden und ist ein Pi OS x64 spezifisches Problem.

Es fehlt der Kernel Header für die aktuellste x64-Version.

Vor der Installation sollten daher die Kernel Header aktualisiert werden:
```
sudo apt update
sudo apt install raspberrypi-kernel raspberrypi-kernel-headers raspberrypi-bootloader
```

Jetzt schau ich mal, ob sich beim Rest was getan hat...

**Comment by timwegenerDE** [comment]
Schon wieder zu früh gefreut. Nach ein paar Neustarts wieder das selbe: unhealthy und beim erneuten deployen des Containers über Portainer raucht der ganze Pi ab :-(

**Comment by timwegenerDE** [comment]
Jetzt habe ich gerade noch X-mal versucht den Raspi als SMB-Server einzurichten. Geht nicht; Keine Anmeldung möglich. Ich stelle den Container auf Bridged und es geht. Nicht dass ich das verstehe, aber im Host-Mode passieren Dinge!

**Comment by timwegenerDE** [comment]
Außerdem sehe ich im Log ca. jede Minute folgende Meldungen:

```
Feb  5 11:43:25 ccu auth.err sshd[412277]: error: Bind to port 22 on 0.0.0.0 failed: Address already in use.
Feb  5 11:43:25 ccu auth.err sshd[412277]: error: Bind to port 22 on :: failed: Address already in use.
Feb  5 11:43:25 ccu auth.crit sshd[412277]: fatal: Cannot bind any address.
Feb  5 11:43:56 ccu user.err monit[1086]: 'sshd' failed to restart (exit status 0) -- '/etc/init.d/S50sshd restart': Stopping sshd: OK Starting sshd: OK
Feb  5 11:44:09 ccu user.err : Invalid config, no current ip, restarting network
```

**Comment by fairtv-git** [comment]
Vielleicht kann ich ja was beitragen. 
Nach diversen Kleingefechten habe ich RapberryMatic auf einem Pi4 8GB in einem Docker Container (USB SSD Boot) am laufen und versuche nun auch den Rest wieder an den Start zu bringen.

Dass der Container als "unhealthy" gemeldet wird, habe ich auch im Portainer gesehen. 
Grund scheint der CCU eigene ssh-Dienst zu sein. Wie sinnvoll der in diesem Zusammenhang ist (ebenfalls hier schon angedeutet) kann eh bezweifelt werden. Mein Log sagt dazu (wiederholt sich alle 30/40 sec. ):
```Mar  5 14:36:27 ccu user.err monit[773]: 'sshd' service restarted 1 times within 1 cycles(s) - exec
Mar  5 14:36:27 ccu user.err monit[773]: 'sshd' process is not running
Mar  5 14:36:27 ccu user.info monit[773]: 'sshd' trying to restart
Mar  5 14:36:27 ccu user.info monit[773]: 'sshd' restart: '/etc/init.d/S50sshd restart'
Mar  5 14:36:58 ccu user.err monit[773]: 'sshd' failed to restart (exit status 1) -- '/etc/init.d/S50sshd restart': Could not stat /etc/ssh/ssh_host_rsa_key: Too many levels of symbolic links^M Could not stat /etc/ssh/ssh_host_dsa_key: Too many levels of symbolic links^M Could not stat /etc/ssh/ssh_host_ecdsa_key: Too many levels of symbolic links^M chmod: /usr/local/etc/
```

wobei:
```lrwxrwxrwx    1 root     root            31 Dec  8 20:15 /etc/ssh/ssh_host_rsa_key -> /usr/local/etc/ssh_host_rsa_key
/var/log # ls -la /usr/local/etc/ssh_host_rsa_key
lrwxrwxrwx    1 root     root            31 Mar  5 14:37 **/usr/local/etc/ssh_host_rsa_key -> /usr/local/etc/ssh_host_rsa_key**
```
letzteres scheint mir ein Zirkelbezug zu sein.

Schaltet man ssh in der Config zur CCU ab, ist sofort Frieden.


Viel mehr plagt mich das json-Logformat - hab noch nicht gefunden wo man das im Portainer umstellt, bzw. wie man damit umgeht.

Viele Grüße,
_fairtv_

**Comment by timwegenerDE** [comment]
Danke @fairtv-git für deine Ergänzungen.

Hast du auch das Problem, dass beim Neustart des Containers über die Portainer Oberfläche alles abraucht? Erst ein physikalischer Neustart hilft dann. Besonders beim Updaten des Containers super nervig…

**Comment by fairtv-git** [comment]
Kann ich noch nicht sagen, das Konstrukt steht erst seit heute morgen 4:00 Uhr.
Aber wenn ich mir die Schichten so ansehe, dann ist Container über Portainer neu starten vergleichbar mit Stecker ziehen, die HM-Logik läuft ja noch. Das mochte auch die CCU2 schon nicht so gerne.

Man müsste die vCCU/RaspberryMatic vorher graceful anhalten können, was zumindest bei der CCU2 nicht ging (sowas wie shutdown -h now).

Weitere Experimente, Erfolge und Rückschläge  stehen noch aus.

Viele Grüße,
_fairtv_

**Comment by timwegenerDE** [comment]
Die Problem ist leider auch mit der aktuellen Version unverändert.
- Ich komme weiterhin nicht um den Host-Netzwerkmode umher. 
- Der SSH-Zugriff des Hosts ändert sich mit den Einstellungen in der CCU.
- Bei aktiviertem SSH Zugriff in der CCU wird der Container unhealthy.
- Beim Stoppen des Containers über die Portainer-Oberfläche (z.B. beim Update des Images) geht der Host mit down.

Unabhängig davon, sollte m.E. der Hinweis auf das Kernelupdate in die Doku: https://github.com/jens-maus/RaspberryMatic/issues/1676#issuecomment-1026867320

**Comment by fairtv-git** [comment]
> * Beim Stoppen des Containers über die Portainer-Oberfläche (z.B. beim Update des Images) geht der Host mit down.
>
kann ich bei mir nicht bestätigten

Man muss vorher aber eh die RESTART POLICIES ändern, sonst fährt RM sofort wieder hoch.
IMO sind Container nach meiner aktuellen Erfahrung eine ungeeignete Lösung, sinnvoller ist vermutlich eine Virtualisierung.

**Comment by timwegenerDE** [comment]
> > * Beim Stoppen des Containers über die Portainer-Oberfläche (z.B. beim Update des Images) geht der Host mit down.
> 
> kann ich bei mir nicht bestätigten
> 
> Man muss vorher aber eh die RESTART POLICIES ändern, sonst fährt RM sofort wieder hoch. IMO sind Container nach meiner aktuellen Erfahrung eine ungeeignete Lösung, sinnvoller ist vermutlich eine Virtualisierung.

Die Restart-Policy hab ich auf „unless-stopped“, dann läuft der eben solange bis ich ihn gezielt abschalte und startet auch nach Neustart, wenn nicht gezielt abgeschaltet. @fairtv-git: Kannst du hier mal ein Screenshot von deinen Container-Capabilities, deinen Network-Settings und deinen Runtime & Ressources aus der Portainer-Oberfläche posten? Vielleicht könnte ich ja dann schon meinen größten „Pain“ beheben.

**Comment by jens-maus** [comment]
> Die Probleme sind leider auch mit der aktuellen Version unverändert.
> 
> * Ich komme weiterhin nicht um den Host-Netzwerkmode umher.
> * Der SSH-Zugriff des Hosts ändert sich mit den Einstellungen in der CCU.
> * Bei aktiviertem SSH Zugriff in der CCU wird der Container unhealthy.
> * Beim Stoppen des Containers über die Portainer-Oberfläche (z.B. beim Update des Images) geht der Host mit down.

Tut mir leid, aber auch ich kann das alles nicht reproduzieren. Hier muss wirklich (wie ich bereits früher gesagt hatte) eine grundlegende Fehlkonfiguration deiner kompletten Docker-Umgebung vorliegen. Es kann/darf nicht sein, das man von innerhalb eines Docker Containers das Host-System herunterfahren lassen kann. Genau für diese Trennung existiert ja Docker. Du machst hier also irgendetwas grundlegendes falsch bzw. es liegt eine grundlegende Fehlkonfiguration deiner Docker-Umgebung vor der du dir vielleicht einfach momentan noch nicht bewusst bist.

Es bringt hier auch nichts weiter zu diskutieren, denn das hier ist das Ticket/Issue System und kein Diskussionsforum. Bitte also deine Probleme im Diskussionsteil hier im GitHub nochmal hervorbringen oder im homematic forum.

> Unabhängig davon, sollte m.E. der Hinweis auf das Kernelupdate in die Doku: [#1676 (comment)](https://github.com/jens-maus/RaspberryMatic/issues/1676#issuecomment-1026867320)

Du kannst das gerne selbe im Dokumentationswiki entsprechend anpassen. Genau deshalb ist dieser nicht nur für jeden frei zugänglich, sondern es kann auch jeder dort Seiten selbst editieren.

**Comment by timwegenerDE** [comment]
Verstehe ich das richtig @jens-maus, KEINS der Probleme tritt bei dir im Netzwerkmode Host auf? Ich habe das System mehrfacher frisch nach Anleitung aufgesetzt und kein anderer Container verhält sich so…

**Comment by jens-maus** [comment]
> Verstehe ich das richtig @jens-maus, KEINS der Probleme tritt bei dir im Netzwerkmode Host auf? Ich habe das System mehrfacher frisch nach Anleitung aufgesetzt und kein anderer Container verhält sich so…

Ich nutze hier den Host Netzwerkmodus nicht und das ist auch insgesamt keine gute Idee (eben weil du dann die Netzwerkschnittstelle quasi unvirtualisiert betreibst und das gewisse negative effekte auf das gesamte Konstrukt hat rund um Docker). Und das im Host Netzwerkmode du dann kein SSH innerhalb von RaspberryMatic nutzen kannst ist ja auch eigentlich recht klar, denn das beisst sich ja dann mit dem SSH daemon auf deinem Host. Da musst du dann halt logischerweise auf SSH innerhalb von RaspberryMatic gänzlich verzichten (geht nicht anders!) oder auf einen anderen Port als 22 lenken. Das aber bei einem RaspberryMatic reboot dein gesamtes host system mit rebootet wird sollte und darf nicht sein und deutet daraufhin das da ggf. noch mehr im Argen ist. Ergo: Keine gute Idee den RaspberryMatic Docker Container im Netzwerk Hostmode zu betreiben und genau deshalb ist das so auch nicht dokumentiert und supportet und somit bewegst du dich ausserhalb der Specs!

**Comment by timwegenerDE** [comment]
Das ist doch mal eine Aussage; Das hätten wir also deutlich abkürzen können. Wie gesagt mDNS für hap-homematic setzt das leider voraus, womit ich nicht drumherum komme. Zu behaupten es getestet zu haben und mich für blöd zu verkaufen finde ich dagegen keinen coolen move. Trotzdem danke für deine Zeit.

Die Ergänzung im Wiki werde ich vornehmen.

**Comment by jens-maus** [comment]
> Das ist doch mal eine Aussage; Das hätten wir also deutlich abkürzen können. Wie gesagt mDNS für hap-homematic setzt das leider voraus, womit ich nicht drumherum komme.

Der Punkt ist: Dein Anwendungsfall passt nicht auf deine Auswahl der Lösung! D.h. du solltest hier kein Docker-basiertes RaspberryMatic einsetzen wenn du auf mDNS bzw. multicast UDP setzt weil sowas bekanntermaßen innerhalb eines Docker Containers nicht funktioniert und man zwangsläuftig auf Hostmode alles betreiben lassen muss - was jedoch security technisch komplett gegen Docker prinzipien verstößst zwecks Abkapselung und genau teilweise solche Probleme heraufbeschwört die du hier beschreibst.

Du bist hier besser damit beraten auf eine komplette Virtualisierung via Proxmox oder ähnlichem (OVA) zu setzen oder einen dedizierten Pi für RaspberryMatic zu nehmen und damit Abstand von einmer dockerisierten RaspberryMatic zu nehmen wenn du sowas wie mDNS brauchst/willst.

**Comment by timwegenerDE** [comment]
Mir geht es ja beim Einsatz von Docker nicht um security Aspekte sondern um Einfachheit, Wartbarkeit, Backup und Update Möglichkeiten sowie um geringen Ressourcen Verbrauch / Ressourcen-Sharing. Aber wie auch immer: Die Beteiligung hier war ja mäßig und für mein (Einzel-)Schicksal muss auch niemand ein Faß aufmachen.

Also: Host-Netzwerkmode ist zur Zeit nicht supported, bis noch ganz viele Leute ihr Interesse bekunden ;)

**Comment by jens-maus** [comment]
> Also: Host-Netzwerkmode ist zur Zeit nicht supported, bis noch ganz viele Leute ihr Interesse bekunden ;)

Falsch, Host-Netzwerkmodus nutzt man einfach nicht (wenn nicht unbedingt notwendig) und wenn doch, dann ist man bereit dafür den "Preis" zu zahlen.

**Comment by timwegenerDE** [comment]
Ich dokumentier für mich hier trotzdem weiter mit:

Wenn der Container nicht privileged ausgeführt wird und SSH im Raspberrymatic Web UI abgeschaltet ist, ist der Container healthy und auch das stoppen des Containers lässt die Umgebung nicht mehr crashen. M.E. macht der Host-Netzwerkmode also nur ein Problem sichtbar, was im bridged Mode nicht auffällt. Leider ist das keine echte Lösung, da der Container momentan nur mit privileged Rechten funktioniert, siehe https://github.com/jens-maus/RaspberryMatic/issues/1856

**Comment by timwegenerDE** [comment]
Sobald der Container die Net_Admin Capability hat, funkt der Container in die SSH-Einstellungen des Hosts rein. Sprich: Es zieht die Einstellung in der Raspberrymatic GUI ob SSH eingeschaltet ist oder nicht auch für den Host. Wenn der Host einen anderen SSH-Port verwendet, funktioniert der SSH Zugriff auf dem Host nicht mehr sobald der Container gestartet wird.

**Comment by timwegenerDE** [comment]
Durch ändern des Container-Ports in der `/etc/ssh/sshd_config` (Z. 13) weg von 22 (auf z.B. 2222) startet der sshd-Prozess wieder sauber im Container und der Container-Status geht auf healthy. Das ist ja schonmal was.

**Comment by hillinator** [comment]
Ich habe genau die identische Umgebung und auch das gleiche Problem. Danke für die Analyse bisher an alle beteiligten.
@timwegenerDE Kannst du nach der Änderung in der Container Config nun auch den Container stoppen bzw. einfach updaten?

**Comment by timwegenerDE** [comment]
@hillinator leider nein. Das löst das Problem nur kosmetisch. Ich hab mich jetzt daran gewöhnt, SSH auf der Umgebung ausgeschaltet zu lassen, wenn ich‘s nicht brauche, sonst über die Homematic GUI anzumachen. Updaten mache ich, indem ich den Container über Kill wirklich direkt abschieße, dann update und dann wieder starte. Leider sehr unschön.

**Comment by hillinator** [comment]
Ja nach dem kill kann ich auch wieder einen container aus aktuellem image erstellen. Danke für die Info.
SSH sollte man dann in dieser Konstellation deaktivieren, damit sich die Fehlermeldungen verringern.

**Comment by ntruchsess** [comment]
@timwegenerDE I suggest using a mDNS-proxy like https://github.com/geekman/mdns-repeater to avoid running the docker-container in host-mode.

**Comment by timwegenerDE** [comment]
@ntruchsess I tried some different approaches with some mdns repeater docker container, but none of them where working. With this one I was able to see the Homekit-Bridges in Homekit: https://github.com/monstrenyatko/docker-mdns-repeater but it could not be added to Homekit. Do you have any working mdns repeater for Homekit?
