### ISSUE TITLE
Integration von nodered 

### ISSUE THREAD

**Issue by NetHans** [jens-maus/RaspberryMatic#168]
Hallo,

besteht die Möglichkeit die Software Node-Red (https://nodered.org/)  in das Image von RaspberryMatic zu integrieren, bzw. Node-Red auf dem RaspberryMatic zu installieren? Eine Anbindung der CCU2 an das MQTT-Protokoll ist ja bereits hier vorgestellt worden: https://homematic-forum.de/forum/viewtopic.php?f=18&t=24109 Entsprechend würde eine Verbindung zwischen RaspberryMatic und Node-Red über MQTT erfolgen. Eine native MQTT-Anbindung von RaspberryMatic wäre allerdings von Vorteil, da so auch Sicherheitsprobleme besser behandelt werden könnten.

**Comment by jens-maus** [comment]
Tut mir leid, aber das sind alles Spezialanwendungen die besser in einem extra CCU Addon aufgehoben sind. Nur ein Bruchteil der RaspberryMatic Nutzer würde davon profitieren. Ich würde daher vorschlagen jemanden zu finden der ein entsprechendes CCU Addon mit NodeRed ähnlich dem mqtt addon generiert das man dann über die WebUI als Zusatzsoftware hochladen kann.

**Comment by NetHans** [comment]
Hallo Herr Maus,

ich kann verstehen, das Sie ungerne Software von anderen Anbietern direkt mit in die CCU bzw. in das RaspberryMatic integrieren möchten, aber Ihre Argumentation, das es sich hier um eine Spezialanwendung handelt, kann ich nicht wirklich nachvollziehen. 

Ich gehe davon aus, das Ihnen bekannt ist, worum es sich bei NodeRed handelt. Dennoch kurz erklärt - NodeRed ist ein Workflow System was über eine gute grafische Oberfläche verfügt und eine Ablaufsteuerung (Script) mittels grafischer Elemente ermöglicht. Wenn es sich an dieser Stelle wirklich um eine Spezialanwendung handelt würde, dann wäre die Script-Engine welche in der CCU bzw. im RaspberryMatic integriert ist, genauso eine Spezialanwendung und müsste über ein Addon bei bedarf nachinstalliert werden. NodeRed kann die Aufgaben der CCU-Script-Engine genau so übernehmen, wenn man die entsprechenden Nodes bereitstellt. Der Vorteil an NodeRed gegenüber der CCU-Script-Engine wäre, das es zum Einen durch die grafische Oberfläche intuitiver zu bedienen und somit mehr Benutzer erreichen und zum Anderen weit aus mehr Möglichkeiten der Kontrolle, Analyse und Steuerung bietet würde. 

Wieso richte ich dieses Anliegen überhaut an Sie? Ich wurde des öffteren von Anwendern des HomeMatic Systems gebeten für sie die Programme einzustellen, da die Inhaber des HomeMatic Systems die Oberfläche als zu unübersichtlich empfanden und somit abgeschrekt wurden. All diese Anwender waren keine Personen, welche gerne Basteln oder Tüfteln. Diese Anwender wünschen es so einfach wie möglich und grafische Oberlfächen mit bunten Bildchen sind da hilfreicher und einfacher als textbasierte Übersichten so wie es in der CCU aktuell der Fall ist. 

Das erwähnte MQTT-Protokoll war lediglich ein Beispiel, wie die CCU-Funktioalitäten an NodeRed angedockt werden könnte. Das wäre auch kein Muss, da es noch viele weitere Möglichkeiten gibt.

Selbstverständlich wäre ein Addon eine durchaus passable Lösung, aber eine native Integration mit entsprechenden Nodes vom Hersteller für die CCU-Funktionen (spetziell bei Triggern) wäre mit großer Sicherheit eine qualitative Verbesserung der CCU-Funktionalität. Ein Bereitstellen von neuen Funktionen wäre so auch aus Sicht der Entwicklung einfacher als bisher. Aus diesem Gründen möchte ich Sie erneut bitten, über die Integration von NodeRed inkl. passender Nodes noch einmal in Ruhe nachzudenken. Eine andere grafische Lösung wäre natürlich auch eine Option. 

Vielen Dank!

**Comment by robdg80** [comment]
Das hm2mqtt AddOn (https://github.com/owagner/hm2mqtt) für die CCU ist leider in dieser Form EndOfLife. Dieses wird nicht mehr weiterentwickelt und es ist eine Frage der Zeit und bereits Homematic-IP wird nicht unterstützt.

Die Entwicklung ist durch hobbyquaker übernommen worden, dieser entwickelt das MQTT leider nicht mehr als AddOn, Das Nachfolge-Projekt (https://github.com/hobbyquaker/hm2mqtt.js) benötigt somit eh einen extra Rechner, auf dem dann auch NodeRed laufen kann.

**Comment by hobbyquaker** [comment]
Ich hab Node-RED mal als Raspberrymatic Addon paketiert: https://github.com/hobbyquaker/ccu-addon-node-red

**Comment by NetHans** [comment]
@hobbyquaker 
Danke für die Umsetzung. Das System läuft seit längerer Zeit super :-)
