### ISSUE TITLE
Home assistant addon migration: no devices with HMIP-RFUSB-TK

### ISSUE THREAD

**Issue by sdirkwinkel** [jens-maus/RaspberryMatic#1681]
### Describe the issue you are experiencing

After migrating from the official home assistant addon I don't see any homematic-ip devices.
Restoring the backup complains about a missing *.apkx file

### Describe the behavior you expected

All my homematic-ip devices in the new addon

### Steps to reproduce the issue

1. Create backup in old homematic addon
2. Stop old addon
3. install new addon
4. import backup

### What is the version this bug report is based on?

3.61.7.20220115

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Mounting /data as /usr/local (Home Assistant Add-On): OK
Identifying onboard hardware: oci, OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: OK: backup successfully restored
Initializing System: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.3, OK
Identifying Homematic RF-Hardware: ....HmRF: none, HmIP: HMIP-RFUSB-TK/USB, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: 2.8.4=>4.4.16, ERROR (2.8.4 != 4.4.16); HMIP-RFUSB-TK: 2.8.4, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: not required
Starting rfd: no BidCos-RF hardware found
Starting HMIPServer: ............OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: OK
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
```

**Comment by jens-maus** [comment]
Apart from the shown error message in your boot log (which was a false error message I just fixed with bc2693a), I think you ran into the same issue like #1671 where the whole device list was shown empty in 3.61.7.20220115 in case no bidcos rf capable rf module was used. This has already been fixed for the next version. So please have a look if your hmip devices show up in the room/function lists and are just missing in the global device list. If so, this is the same issue like #1671.

**Comment by sdirkwinkel** [comment]
I've tried again with the snapshot image.

Home assistant log doesn't show any errors anymore.

I don't see any devices in room/functions

This is the last part of the downloadable log:

```
{"000A1BE98A07F7:0","LOW_BAT",0}, result: [faultCode:-2,faultString:"Invalid device"]) [CallXmlrpcMethod():iseXmlRpc.cpp:2608]
Jan 28 11:36:29 de838cd8-raspberrymatic-dev local0.err ReGaHss: ERROR: XMLRPC 'reportValueUsage' call failed (interface: 1008, params: {"000A1BE98A07F7:0","LOW_BAT",0}) [CallReportValueUsage():iseXmlRpc.cpp:1676]
Jan 28 11:36:29 de838cd8-raspberrymatic-dev local0.err ReGaHss: ERROR: rpc.CallReportValueUsage failed dp id = 1279 [RemoveDPFromCollections():iseManageDP.cpp:439]
Jan 28 11:36:29 de838cd8-raspberrymatic-dev local0.warn ReGaHss: WARNING: XMLRPC 'reportValueUsage': rpcClient.isFault() failed (url: xmlrpc://127.0.0.1:32010, params: {"000A1BE98A07F7:0","INSTALL_TEST",0}, result: [faultCode:-2,faultString:"Invalid device"]) [CallXmlrpcMethod():iseXmlRpc.cpp:2608]
Jan 28 11:36:29 de838cd8-raspberrymatic-dev local0.err ReGaHss: ERROR: XMLRPC 'reportValueUsage' call failed (interface: 1008, params: {"000A1BE98A07F7:0","INSTALL_TEST",0}) [CallReportValueUsage():iseXmlRpc.cpp:1676]
Jan 28 11:36:29 de838cd8-raspberrymatic-dev local0.err ReGaHss: ERROR: rpc.CallReportValueUsage failed dp id = 1278 [RemoveDPFromCollections():iseManageDP.cpp:439]
Jan 28 11:36:29 de838cd8-raspberrymatic-dev local0.warn ReGaHss: WARNING: XMLRPC 'reportValueUsage': rpcClient.isFault() failed (url: xmlrpc://127.0.0.1:32010, params: {"000A1BE98A07F7:0","DUTY_CYCLE",0}, result: [faultCode:-2,faultString:"Invalid device"]) [CallXmlrpcMethod():iseXmlRpc.cpp:2608]
Jan 28 11:36:29 de838cd8-raspberrymatic-dev local0.err ReGaHss: ERROR: XMLRPC 'reportValueUsage' call failed (interface: 1008, params: {"000A1BE98A07F7:0","DUTY_CYCLE",0}) [CallReportValueUsage():iseXmlRpc.cpp:1676]
Jan 28 11:36:29 de838cd8-raspberrymatic-dev local0.err ReGaHss: ERROR: rpc.CallReportValueUsage failed dp id = 1277 [RemoveDPFromCollections():iseManageDP.cpp:439]
Jan 28 11:36:29 de838cd8-raspberrymatic-dev local0.warn ReGaHss: WARNING: XMLRPC 'reportValueUsage': rpcClient.isFault() failed (url: xmlrpc://127.0.0.1:32010, params: {"000A1BE98A07F7:0","CONFIG_PENDING",0}, result: [faultCode:-2,faultString:"Invalid device"]) [CallXmlrpcMethod():iseXmlRpc.cpp:2608]
Jan 28 11:36:29 de838cd8-raspberrymatic-dev local0.err ReGaHss: ERROR: XMLRPC 'reportValueUsage' call failed (interface: 1008, params: {"000A1BE98A07F7:0","CONFIG_PENDING",0}) [CallReportValueUsage():iseXmlRpc.cpp:1676]
Jan 28 11:36:29 de838cd8-raspberrymatic-dev local0.err ReGaHss: ERROR: rpc.CallReportValueUsage failed dp id = 1273 [RemoveDPFromCollections():iseManageDP.cpp:439]
Jan 28 11:36:29 de838cd8-raspberrymatic-dev user.debug hm_deldev: event fired (delete 000A1BE98A07F7)
Jan 28 11:36:43 de838cd8-raspberrymatic-dev user.warn monit[618]: 'hasUSB' status failed (1) -- no output
Jan 28 11:36:44 de838cd8-raspberrymatic-dev user.warn monit[618]: 'rpi4usb3Check' status failed (1) -- no output
Jan 28 11:36:44 de838cd8-raspberrymatic-dev user.err monit[618]: Filesystem '/media/usb1' not mounted
Jan 28 11:36:44 de838cd8-raspberrymatic-dev user.err monit[618]: 'usb1' unable to read filesystem '/media/usb1' state
Jan 28 11:36:44 de838cd8-raspberrymatic-dev user.info monit[618]: 'usb1' trying to restart
Jan 28 11:36:59 de838cd8-raspberrymatic-dev user.warn monit[618]: 'hasUSB' status failed (1) -- no output
Jan 28 11:37:00 de838cd8-raspberrymatic-dev user.err monit[618]: 'rpi4usb3Check' status failed (1) -- no output
Jan 28 11:37:00 de838cd8-raspberrymatic-dev user.err monit[618]: Filesystem '/media/usb1' not mounted
Jan 28 11:37:00 de838cd8-raspberrymatic-dev user.err monit[618]: 'usb1' unable to read filesystem '/media/usb1' state
Jan 28 11:37:00 de838cd8-raspberrymatic-dev user.info monit[618]: 'usb1' trying to restart
Jan 28 11:37:16 de838cd8-raspberrymatic-dev user.warn monit[618]: 'hasUSB' status failed (1) -- no output
Jan 28 11:37:16 de838cd8-raspberrymatic-dev user.err monit[618]: Filesystem '/media/usb1' not mounted
Jan 28 11:37:16 de838cd8-raspberrymatic-dev user.err monit[618]: 'usb1' unable to read filesystem '/media/usb1' state
Jan 28 11:37:16 de838cd8-raspberrymatic-dev user.info monit[618]: 'usb1' trying to restart
Jan 28 11:37:32 de838cd8-raspberrymatic-dev user.err monit[618]: 'hasUSB' status failed (1) -- no output


***** hmserver.log *****
Jan 28 11:35:54 de.eq3.cbcs.server.core.vertx.KeyServerWorker ERROR [vert.x-worker-thread-1] Missing key server configuration parameter (Network.Key) for  mode: KEYSERVER_LOCAL 
```

I've looked for this and https://github.com/jens-maus/RaspberryMatic/issues/613 seems related but already fixed.

**Comment by jens-maus** [comment]
The issue seems to be that the backup migration has still a bug for which I already submitted a PR for integration (https://github.com/home-assistant/addons/pull/2366). So please wait until there will be a new HomeMatic CCU Add-on version (99.0.3) which hopefully will fix your backup import issues here.

**Comment by Nokius** [comment]
@jens-maus  does it mean backups before tv99.0.3 will be broken and can't be imported?
Currently in the migration and the old addon is already removed :|

**Comment by jens-maus** [comment]
> @jens-maus does it mean backups before tv99.0.3 will be broken and can't be imported? Currently in the migration and the old addon is already removed :|

Well, it means that this is the reason why homematicIP devices are missing (as stated here). So if you have missing homematicIP devices, restore your homematic add-on backup, wait for 99.0.3 and then redo the backup export.

**Comment by jens-maus** [comment]
The 99.0.3 old homematic ccu add-on had just been released yesterday. So please retry to export a sbk backup with that version and then report back here if HmIP device are correctly imported in the RaspberryMatic add-on afterwards.

**Comment by Nokius** [comment]
@jens-maus with the new version I get following error when creating the backup.
`An internal error was detected in the service software. The diagnostics are being emailed to the service system administrator (root).`

The log part is not spiting out any useful hint, complains about a missing mail relay. :-| any idea?

**Comment by sdirkwinkel** [comment]
I've looked into this and am fairly sure this is the remaining fix: https://github.com/home-assistant/addons/pull/2371
I created a backup with that fix applied and now have my homematic devices in raspberrymatic. 🎉

Thanks @jens-maus for the project!

**Comment by sdirkwinkel** [comment]
hm, for some reason it still doesn't work. I will investigate more later

**Comment by jens-maus** [comment]
> hm, for some reason it still doesn't work. I will investigate more later

What exactly does not work? Please be more precise. You said, with the fixed backup your homematic/homematicIP devices are in RaspberryMatic now. So *what* actually does not work?

**Comment by Nokius** [comment]
@jens-maus so I tried it again, the backup is created but the restore is failing. See the attached screenshot.  

![image](https://user-images.githubusercontent.com/879178/151963881-a67a5546-3e31-4a96-91d6-b98cd9ee15dd.png)

**Comment by jens-maus** [comment]
@Nokius Try to ignore that message and reboot the Add-on right away. Then have a look if everything is back. This error can occur if you don't have any homematic rf module connected to the Add-on while restoring the backup.

**Comment by sdirkwinkel** [comment]
> What exactly does not work? Please be more precise. You said, with the fixed backup your homematic/homematicIP devices are in RaspberryMatic now. So _what_ actually does not work?

Sorry, I wasn't sure what the issue was and didn't have time.
I thought the backup was fixed, because after importing a backup and restarting i saw devices in the homematic list.
These devices apparently disappear after a while.

It seems that my fix for ignoring mv error codes was not a good idea. I've now logged in docker exec and tested a better solution and will create a new pull request in a couple of minutes. I've now actually got devices in homematic. (checked by triggering boost)

**Comment by Nokius** [comment]
@Nokius I saw there is 99.0.5 in the pipeline. The restore didn't work. nothing was imported. :crossed_fingers:  that all will work with the new release :)

Thanks for all the work!

**Comment by Nokius** [comment]
need to wait a little bit more...
tried reboots not sure there is a way to force a check for new versions...

```
- description: HomeMatic central based on OCCU
  icon: true
  logo: true
  name: HomeMatic CCU
  repository: core
  slug: core_homematic
  state: started
  update_available: false
  version: 99.0.4
  version_latest: 99.0.4
  ```

**Comment by Nokius** [comment]
@jens-maus the backup was completed and a restore was working as well I see my devices again.
Looking into the HA -> raspberrymatic communication now :D
Thanks!

**Comment by Nokius** [comment]
@jens-maus all worked very well, may the documentation for the "Add a home assistant automation to connect to the raspberrymatic addon" could be improved a little. It toke me a few attempts to figure out how to set up the program/script.

Own you more then one beer, will ping you when I'm around Dresden next time.

**Comment by jens-maus** [comment]
> @jens-maus all worked very well, may the documentation for the "Add a home assistant automation to connect to the raspberrymatic addon" could be improved a little. It toke me a few attempts to figure out how to set up the program/script.

Feel free to edit the documentation yourself. That's exactly why this is a wiki!

**Comment by Nokius** [comment]
if I do so the preview is missing the images :(
