### ISSUE TITLE
tailscale vpn exportiert IPs als Netze

### ISSUE THREAD

**Issue by grunes** [jens-maus/RaspberryMatic#1683]
### Describe the issue you are experiencing

Das init script des tailscale daemons (/etc/init.d/S46tailscaled) exportiert nicht nur Netze sondern auch IPs wenn gleichzeitig noch z.B. OpenVPN im Einsatz ist.

```
# /etc/init.d# /sbin/ip route
default via 192.168.0.1 dev eth0  metric 10 
10.8.0.0/24 dev tun0 scope link  src 10.8.0.1 
192.168.0.0/24 dev eth0 scope link  src 192.168.0.10 
192.168.42.0/24 via 192.168.45.9 dev tun1 
192.168.45.0/24 via 192.168.45.9 dev tun1 
192.168.45.1 via 192.168.45.9 dev tun1 <-------------------
192.168.45.9 dev tun1 scope link  src 192.168.45.10 <------------------- 
```
Dies führt zu einer Fehlmeldung der tailscale app:

```
# tailscale up --advertise-routes $(/sbin/ip route | grep -v default | awk '{ print $1 }' | xargs | tr ' ' ',')
"192.168.45.1" is not a valid IP address or CIDR prefix
```

### Describe the behavior you expected

Es sollten nur Netze exportiert werden!

### Steps to reproduce the issue

1. /etc/init.d/S46tailscaled stop
2. /etc/init.d/S46tailscaled start
3. :-)

### What is the version this bug report is based on?

3.61.7.20220115

### Which base platform are you running?

tinkerboard (ASUS Tinkerboard)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Der Fehler entsteht beim erzeugen der Parameter:

`TAILSCALE_UP_ARGS="--advertise-exit-node --advertise-routes $(/sbin/ip route | grep -v default | awk '{ print $1 }' | xargs | tr ' ' ',')"`

Ich habe das Script folgendermaßen angepasst: (die default Route fällt automatisch mit raus da hier eine andere Notation verwendet wird)

`TAILSCALE_UP_ARGS="--advertise-exit-node --advertise-routes $(/sbin/ip route | egrep '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/' | awk '{ print $1 }' | xargs | tr ' ' ',') --accept-routes"`
```

**Comment by Baxxy13** [comment]
Du musst dafür nicht am init-Script rumfummeln. ;-)

Trage einfach deine Tailscale Konfiguration in die `/usr/local/etc/config/tailscaleEnabled` ein.
Das überschreibt die default Parameter.
Ich brauche z.B. weder `--advertise-routes` noch `--advertise-exit-node`,
daher sieht der Inhalt meiner `/usr/local/etc/config/tailscaleEnabled` so...
`TAILSCALE_UP_ARGS=""` aus.

**Comment by grunes** [comment]
Ja, den "--accept-routes" hätte ich dort einfügen können. Die Selektion der Netze ist trotzdem falsch und erzeugt einen Fehler der mit "2>/dev/null" ins Nirvana befördert wird. Schön ist anders! ;-)
