### ISSUE TITLE
Gerätefirmware - Upload nicht mehr möglich (Nightly-Snapshot)

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1684]
### Describe the issue you are experiencing

Mit aktuellem Nightly-Snapshot ist es nicht mehr möglich eine Geräte-Firmware auf die RM zu laden.
Drückt man im entsprechenden Bereich auf "Neu" lässt das PopUp keine Auswahl einer Datei zu.

### Describe the behavior you expected

Geräte-Firmware-Files uploaden sollte problemlos funktionieren

### Steps to reproduce the issue

1. aktuellen Nightly installieren (egal welche Hardware)
2. zu "Einstellungen > Geräte-Firmware - Übersicht" navigieren
3. Button "Geräte-Firmware" anklicken
4. Button "Neu" anklicken
5. fehlerhaftes "Upload-PopUp" begutachten

### What is the version this bug report is based on?

3.61.7.20220127 Nightly

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
-
```

### Additional information

![RM_Geräte_Firmware_Update_PopUp_nicht_funktional](https://user-images.githubusercontent.com/54898249/151377447-06ae2264-443b-4e96-87bf-80353ab0844b.JPG)

Mit der offiziellen 3.61.7.20220115 war das noch funktional.
Mit welchem Nightly sich das Problem eingeschlichen hat kann ich nicht sagen, in 3.61.7.20220123 ist es aber schon enthalten.

**Comment by jens-maus** [comment]
Oh ok. dann weiss ich schon wo ich ansetzen muss. Danke für die Info. Du kannst ja mal dann selbst nochmal alle Bereiche der WebUI in der Zwischenzeit durchgehen wo man prinzipiell Dateien hochladen können müsste und checken ob diese alle gehen. Und wenn nicht dann hier bitte ne kurze Rückmeldung geben welcher Bereich ggf. nicht geht dann kann ich den auch gleich reparieren.

**Comment by Baxxy13** [comment]
Die anderen beiden (mir bekannten) Upload-Stellen (Zentralen-Software-Update; Zusatzsoftware) arbeiten ja anders und funktionieren. Da geht direkt das Dateiauswahl-Fenster auf. 
Daher würde ich mal sagen das das Firmware-Upload-PopUp das einzige problematische ist.

**Comment by MichaelN0815** [comment]
In 3.61.7.20220120 ist der Fehler auch schon enthalten

**Comment by jens-maus** [comment]
Wie gesagt, der Fehler ist los lokalisiert. Einfach Geduld haben 😜
