### ISSUE TITLE
IP Actoren können mit der 2.29.23.20171022 nicht erreicht werden

### ISSUE THREAD

**Issue by bprskalo** [jens-maus/RaspberryMatic#169]
Danke für die Aktualisierung des RaspberryMatic und für Deine Riesen Leistung Jens!!

Ich habe eben die neue Version eingespeilt, hat schon mal alles wunderbar funktioniert (Backup / Restore). Da ich ein gemischtes Umfeld habe (RF und IP Aktoren) habe ich auch gleich festgestellt, dass meine IP Aktoren nicht gesteuert werden können.

Sie sind sichtbar, können aber nicht angesprochen werden ...

**Comment by jens-maus** [comment]
Würde mich schon sehr wundern wenn HomeMatic-IP damit nicht gehen sollte. Da bist du zumindest der erste der das meldet. Mal abwarten ob es noch andere gibt die das gleiche melden.

Ansonsten bitte mal die Hardware melden, kontrollieren ob der HmIP Anlernmodus startet und ob ein komplettes Trennen von der Stromverbrauch ggf den DutyCycle beruhigt und dann HmIP wieder geht.

**Comment by bprskalo** [comment]
ich hab die alte SD-Karte wieder eingesetzt .. und es ging alles gleich wieder .. 

ich kann so im Moment leben :-)

**Comment by jens-maus** [comment]
Das alleine heisst leider nichts und hilft auch nicht wirklich weiter. Bei einem CCU Update sollte man alleine schon wegen dem DutyCycle genug Geduld mitbringen und nicht sofort den Rückzug antreten wenn nucht gleich alles geht. Wie gesagt, bis dato bist du anscheinend der Einzige mit einem vermeintlichen Problem.

**Comment by bprskalo** [comment]
ich mache das ja nicht das erste mal :-) .. uns bisher ging das alles immer gleich auf anhieb. Mir ist klar dass der Austausch der Karte auf die Vorherige Version nichts heisst. Ich wollte damit auch nur vermitteln, das ich gern warten kann bis sich allenfalls jemand anders noch mit dem gleichen Problem melden würde und das es in meinem Fall keine Dringlichkeit gibt, das ich einen Workaround habe :-) 

und wenn dem dann nicht so wäre, kommt der DutyCycle zum zug :-)

**Comment by jens-maus** [comment]
Ok :) Das nächste mal wäre es aber auch gut erst einmal das ganze im homematic forum zu diskutieren statt hier gleich einen Bugreport aufzumachen, btw. :)

**Comment by bprskalo** [comment]
wird gemacht :-)

**Comment by bprskalo** [comment]
also .. nach dem ich das ganze nochmals gemacht habe (gleiche Karte), das Image neu eingespielt habe .. den gleichen Backup wieder eingespielt habe .. läuft es wie es soll... auf Anhieb .. 

somit issue geschlossen ... Danke :-) !!
