### ISSUE TITLE
Device values can be read but not changed after update

### ISSUE THREAD

**Issue by pahofmann** [jens-maus/RaspberryMatic#1693]
### Describe the issue you are experiencing

After the update to the lastest version I can no longer set values for my devices.  They are read properly when changed on the device (e.g. setPoint temp on a thermostat) but can't be changed from the raspberrymatic UI.

### Describe the behavior you expected

Chaning the value in raspberrymatic should change the value on the device.

### Steps to reproduce the issue

1. Install latest version
2. Connect HmIP BWTH
3. Change any value in RaspberryMatic UI

### What is the version this bug report is based on?

3.61.7.20220115

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Everytime I change a value some errors are logged:


Feb  2 00:26:58 homematic local0.warn ReGaHss: WARNING: XMLRPC 'setValue': rpcClient.isFault() failed (url: xmlrpc://127.0.0.1:32010, params: {"000C98A994FFA5:1","SET_POINT_TEMPERATURE",27.250000}, result: [faultCode:-1,faultString:"Generic error (TIMEOUT)"]) [CallXmlrpcMethod():iseXmlRpc.cpp:2608]
Feb  2 00:26:58 homematic local0.err ReGaHss: ERROR: XMLRPC 'setValue' call failed (interface: 1009, params: {"000C98A994FFA5:1","SET_POINT_TEMPERATURE",27.250000}) [CallSetValue():iseXmlRpc.cpp:1505]
Feb  2 00:26:58 homematic local0.err ReGaHss: ERROR: rpc.CallSetValue failed; address = 000C98A994FFA5:1 [WriteValue():iseDOMdpHSS.cpp:76]
```
```


### Additional information

I tried reflashing with the latest Raspberrymatic version and reconnecting all the devices, it lead to the same result.

**Comment by Baxxy13** [comment]
Wenn das wirklich ein Bug in der aktuellen Version wäre, müssten eigentlich ne Menge User betroffen sein.
Gelesen/gehört habe ich diesbezüglich (noch) nichts.

Fragen:

- Gibt es Servicemeldungen wie "Gerätekommunikation gestört"?
- Wie hoch ist dein Carrier Sense Level (Anzeige auf der Startseite)

Wenn die Zentrale die Daten ihrer Geräte empfängt aber keine "Befehle" an diese übertragen kann könnte das an einem Funkstörer liegen.

**Comment by pahofmann** [comment]
Würde ich eigentlich auch wundern wenn es am update liegt, sonst hat sich am Setup aber eigentlich nichts geändert.

Zu den Fragen:

- Ja, sobald ich einen Wert einstelle zeigt er den Fehler bei der Gerätekommunikation an, beim lesen tritt er nicht auf.
- Steht bei 10%

Funkstörer ist nichts dazu gekommen in letzter Zeit, der Raspi ist auch nur Luftlinie 3 Meter vom nahsten Thermostat entfernt.

Sonst könnte ich mir nur ein Defektes FUnkmodul vorstellen, leider nur noch eines da das kein HmIP supported um es zu testen.

**Comment by Nielsvo** [comment]
Ich glaube ich habe ein gleiches Problem, auch seit die neue Version. Sehen Sie auch hier: https://homematic-forum.de/forum/viewtopic.php?f=65&t=72085&start=130#p704048

**Comment by pahofmann** [comment]
> Dauerhaft?

Ist jetzt seit deinem Commentar wieder auf 0% runter und da geblieben, was höheres als 10% war mit bisher noch nicht aufgefallen.

**Comment by Baxxy13** [comment]
Hmm, ich denke weiterhin an einen Funkstörer auch wenn der CS nicht dauerhaft hoch ist.
Defektes Funkmodul ist zwar unwahrscheinlich, aber auch nicht auszuschließen.
Kannst du die Zentrale nicht mal testweise umziehen. Idealerweise an einen Ort wo wenig bis keine elektronischen Geräte sind.

**Comment by pahofmann** [comment]
Funkmodul zum testen ist auf dem weg, falls das nichts hilft versuch ich es mal mit einem anderen Platz.

Danke für die Hilfe, auch wenn es wohl Problem mit der Software selbst ist
