### ISSUE TITLE
Repository to use for fedora Core OS (Docker install)

### ISSUE THREAD

**Issue by DutchmanNL** [jens-maus/RaspberryMatic#1695]
### Describe the solution you'd like

I would like to use the Fender Core OS to run RasberryMatic as Docker instance.
Unfortunalty, fedora does not use the APT package registry of Debian but requires yum or DNF.

current instruction set is not covering how to import the gpg key and only provides the .list used on apt source list.
It would more than great if we can add the intruction/list settings for fedora based core systems

### Describe alternatives you've considered

tried several installation methods to get the required packages, yum and dnf made it possible to install the dependency but I am not able to add the provide list file into the fedora repo listening

### Is your feature request related to a problem?

No, its an improvement as fedora core OS is more lightweigted than detain related ditrubution and a core OS used for docker/virtualisations with a minimum as possible core base system

**Comment by jens-maus** [comment]
> It would more than great if we can add the intruction/list settings for fedora based core systems

Feel free to work on this and to modify the documentation in the [wiki](https://github.com/jens-maus/RaspberryMatic/wiki). Personally, I do not have any Fedora installation and also will not try to install/use it and thus will also not support it or work on this myself.

**Comment by DutchmanNL** [comment]
> > It would more than great if we can add the intruction/list settings for fedora based core systems
> 
> Feel free to work on this and to modify the documentation in the [wiki](https://github.com/jens-maus/RaspberryMatic/wiki). Personally, I do not have any Fedora installation and also will not try to install/use it and thus will also not support it or work on this myself.

Thank you, clear. I can start working on it but would need to translate the deb packages into .repo standard.
As the *.deb are sonly provided by thee source list, can you give me a hint were I can find the related .deb packages of the kernel modules ?

**Comment by jens-maus** [comment]
Well, instead of simply converting on `*.deb` conversion, you can directly contribute to the pivccu repository (https://github.com/alexreinert/piVCCU) from @alexreinert and submit a PR there which will automatically generate fedora-like install packages. Sorry, but as said. You are on your own here, because I neither use Fedora myself nor have great feelings about Fedora in general.

**Comment by DutchmanNL** [comment]
thank you @jens-maus ! I tried o compile them by myself and build the .rpm, unfortunalty running into some issue.l
Will try to get in contact with Alex maybe we can figure something out together https://github.com/alexreinert/piVCCU/issues/425
