### ISSUE TITLE
Import von Gräten in MEDIOLA AIO CREATOR NEO

### ISSUE THREAD

**Issue by henrydiesner** [jens-maus/RaspberryMatic#170]
Zunächst vielen Dank für die neue RaspberryMatic-Version.
Leider ist der Geräteimport im Mediola AIO Creator Neo noch nicht möglich. Das ging nur bis zur Version 2.29.22.20170902. Gibt es eine Möglichkeit, den Import wieder zu ermöglichen?

**Comment by jens-maus** [comment]
Hier gibt es in der Tat eine Möglichkeit. Das Problem ist ein Bug in Mediola der in der kommenden 2.2.0 Version beseitigt sein wird. In der aktuellen 2.2.0beta3 sind die Probleme bereits eliminiert.
