### ISSUE TITLE
Bedienfeld eines Geräts erscheint in der WebUI nach dem schalten ein zweites Mal

### ISSUE THREAD

**Issue by HookHM** [jens-maus/RaspberryMatic#1700]
### Describe the issue you are experiencing

Hallo, ich verwende die neueste Version von RM und die WebUI bedienstee ich mit dem neuesten macOS und dem neuesten Safari-Browser. Wenn ich ein Gerät in der WebUI beträgt und dann der Status aktualisiert wird, wird mir danach die oder die Tasten zum steuern des Geräts 2x angezeigt. Es ist egal, welches Gerät es handelt.

Vor dem Bedienung:Nach der Bedienung:   Hier noch ein Beispiel an einem anderen Gerät ...  Vorher:  Nachher: 

### Describe the behavior you expected

.

### Steps to reproduce the issue

1. WebUI aufrufen und zu Status und Bedienung > Geräte navidieren
2. Ein schaltbares Gerät raussuchen z.B. HmIP-BSM oder 
3. Z.B. an Kanal :4 unter Bedienung auf "Aus" drücken.
...

### What is the version this bug report is based on?

3.61.7.20220115

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
.
```

**Comment by jens-maus** [comment]
Duplicate of #1467
