### ISSUE TITLE
Ship current firmware of all Homematic devices with RaspberryMatic

### ISSUE THREAD

**Issue by renne** [jens-maus/RaspberryMatic#171]
Hi,

currently one has to search the eq3-website regularly for firmware-updates for specific devices. If a new firmware update is found it has to be downloaded to a PC and then uploaded to RaspberryMatic.

This costs a lot of time.

Please, ship the current firmware-updates of all Homematic devices with RaspberryMatic.

**Comment by jens-maus** [comment]
Sorry, but IMHO with the latest features in the 3.x.x firmware line this is not necessary anymore since the firmware will now notify if a new firmware is available.
