### ISSUE TITLE
Fehlermeldungen beim booten bezüglich raw-uart

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1711]
### Describe the issue you are experiencing

Beim Test des heutigen Nightlys 3.61.7.20220208-0d5cb4 sind mir ein paar Fehlermeldungen beim booten aufgefallen.

```
Starting tailscaled: OK
Identifying Homematic RF-Hardware: ....cat: can't open '/sys/devices/virtual/raw-uart/raw-uart/red_gpio_pin': No such file or directory
cat: can't open '/sys/devices/virtual/raw-uart/raw-uart/green_gpio_pin': No such file or directory
cat: can't open '/sys/devices/virtual/raw-uart/raw-uart/blue_gpio_pin': No such file or directory
HmRF: RPI-RF-MOD/HB-RF-USB-2@usb-0000:00:06.0-1, HmIP: RPI-RF-MOD/HB-RF-USB-2@usb-0000:00:06.0-1, OK
Updating Homematic RF-Hardware: RPI-RF-MOD: 4.4.12, not necessary, OK

```
Augenscheinlich schien alles zu funktionieren, bin aber trotzdem auf den gestrigen Nightly zurück.

### Describe the behavior you expected

Keinerlei Fehlermeldungen beim Bootvorgang

### Steps to reproduce the issue

1. heutigen Nightly installieren
2. Bootvorgang am Monitor beobachten oder in die `/var/log/boot.log` schauen
3.
...

### What is the version this bug report is based on?

3.61.7.20220208-0d5cb4 Nightly

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
-
```

### Additional information

RPI-RF-MOD auf HB-RF-USB-2

**Comment by Baxxy13** [comment]
Hatte ich vorhin gar nicht hingeguckt.
Die LED bleibt einfach gelb. Herbeigeführte Alarm oder Servicemeldungen ändern daran nichts.

**Comment by alexreinert** [comment]
/sys/devices/virtual/raw-uart scheint nicht auf allen Kernel Versionen verfügbar zu sein, daher sollte man lieber /sys/class/raw-uart verwenden.

**Comment by jens-maus** [comment]
Ok, danke. dann bitte mal mit dem nächsten nightly build noch einmal probieren. Habe nun alle `/sys/devices` uses with `/sys/class` ersetzt.

**Comment by Baxxy13** [comment]
Rückmeldung:
Nightly 3.61.7.20220209
Die Fehlermeldungen beim Booten sind weg und die LED des RPI-RF-MOD bekennt wieder Farbe.
Sehr gut!
