### ISSUE TITLE
Direkte Verknüpfung Empfänger hinzufügen

### ISSUE THREAD

**Issue by michael2321** [jens-maus/RaspberryMatic#172]
Ich wollte bei einer Direkten Verknüpfung einen weiteren Empfänger hinzufügen.

Leider ist der Button "Empfänger hinzufügen" , wenn die Liste nach Sender sortiert wird, nicht vorhanden.
Der Button "Sender hinzufügen" ist auf der anderen Seite vorhanden.
Ich arbeite mit der HM-CCU2 Firmware 2.29.23 auf einem Raspberry pi3.
Ich habe eine alte CCU2 mit der Firmware 2.29.23 aufgespielt dort war der Fehler nicht vorhanden.

**Comment by jens-maus** [comment]
Das verhalten kann ich leider nicht reproduzieren. RaspberryMatic verhält sich da komplett gleich wie eine CCU2 mit gleicher Firmware. Auch erscheint hier in meinen Testinstallationen immer der Knopf "Empfänger hinzufügen" wenn man nach Sender sortiert.

**Comment by elixier** [comment]
Habe leider das gleiche Problem. In Chrome und IE mit verschiedenen Skalierungen probiert. Nichts.
Wenn man nach Empfänger sortiert, wird allerdings Sender hinzufügen angezeigt.
Version: 2.29.23.20171022

**Comment by jens-maus** [comment]
Bitte ein Screenshot zeigen der das Problem demonstriert.

**Comment by michael2321** [comment]
![screenshot-2017-11-14 homematic webui 1](https://user-images.githubusercontent.com/33102059/32780791-da85125c-c942-11e7-8f1c-ccd68d108d2e.png)
![screenshot-2017-11-14 homematic webui 2](https://user-images.githubusercontent.com/33102059/32780792-daaea798-c942-11e7-9a1e-e86721117606.png)
![screenshot-2017-11-14 homematic webui](https://user-images.githubusercontent.com/33102059/32780793-dacbd91c-c942-11e7-9052-3db251108c0d.png)
