### ISSUE TITLE
HMIP-RFUSB: =>4.4.16, ERROR ( != 4.4.16)

### ISSUE THREAD

**Issue by ultimate-tester** [jens-maus/RaspberryMatic#1722]
### Describe the issue you are experiencing
I am a first time user, so the error is most likely on my end.
While booting up RaspberryMatic, I get the following in the log:

```
Identifying Homematic RF-Hardware: ...HmRF: none, HmIP: none, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: =>4.4.16, ERROR ( != 4.4.16)
Identifying Homematic RF-Hardware: ...HmRF: none, HmIP: none, OK
```

Some guidance would be greatly appreciated. I am unable to diagnose whether I have wrong soldering (all solders look quite alright) or if there's something else going wrong. Thanks in advance!

### Describe the behavior you expected

A successful boot, with a usable HMIP-RFUSB

### Steps to reproduce the issue

I have followed the official guide on how to run RaspberryMatic as an add-on in Home Assistant OS.

### What is the version this bug report is based on?

3.61.7.20220115

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Besides the above provided fragment, no other errors. All is OK.
```

**Comment by Makiese** [comment]
see here: [Home Assistant Add-on rfd & HMIPServer ERROR #1707](https://github.com/jens-maus/RaspberryMatic/issues/1707)

**Comment by ultimate-tester** [comment]
Thanks for the amazingly fast response, you must be the winner for 2022 already :)

Thanks to your link, it gave me the insight that disabling protection mode is a workaround:

```
Identifying Homematic RF-Hardware: ....HmRF: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-0000:00:19.0-2, HmIP: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-0000:00:19.0-2, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: 4.2.14=>4.4.16, OK
```

Keeping an eye on the versions to try to go away from a disabled protection mode asap but for now things seem to be working. On to the next step in this journey!

Thanks!
