### ISSUE TITLE
Broken GUI after Controlling HMIP-Froll via GUI

### ISSUE THREAD

**Issue by cavernerg** [jens-maus/RaspberryMatic#1726]
### Describe the issue you are experiencing

After using one of the buttons to control the shutter, the gui is broken: 

before: 
![grafik](https://user-images.githubusercontent.com/62744005/155737582-6f180366-967c-4b15-a891-ccd45d5347ac.png)

after: 
![grafik](https://user-images.githubusercontent.com/62744005/155737637-0dae3d6a-bcfe-420c-8b27-df1faf68fe68.png)

### Describe the behavior you expected

No broken gui :) 

### Steps to reproduce the issue

1. go to device (FROLL) control
2.use up or down

### What is the version this bug report is based on?

 	3.61.7.20220115

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
Didn't look
```

### Additional information

Hardware is original CCU3

**Comment by mbhomie007** [comment]
#1467
