### ISSUE TITLE
Blacklist für problematische UAS-fähige SATA-Controller mittels Parameter in der /boot/cmdline.txt (Pi4B)

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1727]
### Describe the solution you'd like

Der Pi4B macht erst richtig Spaß wenn man RaspberryMatic auf SSD betreibt welche an USB3 angeschlossen ist.
(Die dadurch möglichen Funkstörungen lassen wir hier mal außen vor)
Bei meinem Tests damals zum Thema bin ich ja auf viele USB3-SATA Controller gestoßen die arge Probleme bereiten wenn sie UAS fähig sind. Wie man die Probleme umgehen kann ist im Wiki beschrieben (mittels quirks Parameter in der `/boot/cmdline.txt`), das funktioniert auch.

Probleme bekommt man aber beim RM-Update, da nach dem flashen im Recovery beim anschließendem Reboot alle Parameter weg sind.

Nun habe ich gesehen das Homeassistant, genauer gesagt Homeassistant-OS eine default Blacklist via `/boot/cmdline.txt` eingeführt hat, welche bei bekannten problematischen Adaptern den UAS-Modus deaktiviert.
[#1743](https://github.com/home-assistant/operating-system/issues/1743)

Vielleicht könnte man das auch für RM umsetzen.

### Describe alternatives you've considered

-

### Is your feature request related to a problem?

-

**Comment by jens-maus** [comment]
> Nun habe ich gesehen das Homeassistant, genauer gesagt Homeassistant-OS eine default Blacklist via `/boot/cmdline.txt` eingeführt hat, welche bei bekannten problematischen Adaptern den UAS-Modus deaktiviert.
> [#1743](https://github.com/home-assistant/operating-system/issues/1743)

Danke für den Hint. Allerdings scheint mir das aktuell **noch** nicht in HomeAssistantOS konkret umgesetzt worden zu sein (Das ticket ist ja noch offen und diesbzgl. wurde wohl auch noch nix gemerged). Ich würde daher vorschlagen das weiter zu monitoren und zu schuaen was dabei rauskommt und dann die Änderungen ggf. zu übernehmen.

**Comment by Baxxy13** [comment]
Alles klar, behalten wir das mal im Auge.

**Comment by Baxxy13** [comment]
Hatte ja völlig übersehen das du das implementiert hast.
Danke dafür. 
Meine "eine-für-alles billig USB3-SSD" ist bei den quirks-Parametern mit bei und funktioniert nun "out-of-the-box" am USB3 des Pi4B. Erspart mir das jonglieren mit den SD-Karten bei der Testerei.

**Comment by jens-maus** [comment]
Ja, diese Änderungen habe ich vom HomeAssistantOS übernommen wo diese Anpassungen vor kurzem auch so integriert worden sind. Schön das es nun out of the box funktioniert.
