### ISSUE TITLE
Geräteeinstellungen fehlen für HmIP Aktoren mit neueren Firmware ständen (z.B. HmIP-FSM 1.6.2)

### ISSUE THREAD

**Issue by Gluehwurm** [jens-maus/RaspberryMatic#173]
Nach dem updaten des FSM fehlen die Geräteeinstellungen bei RaspiMatic. Mit der CCU2 neueste Firmware funktioniert das Teil problemlos. Wieder an RaspiMatic angelernt, Einstellmöglichkeiten fehlen.

Betrifft  homematic-raspi-2.29.23.20171022 und auch die 2.29.22.20171007.

https://homematic-forum.de/forum/viewtopic.php?f=58&t=39693

Gruß
Bruno

**Comment by jens-maus** [comment]
Bitte mal in /usr/local/tmp nachschauen ob dort Fehlermeldungen in einer cgimail datei auftauchen wenn versucht wird mit RaspberryMatic die Parameterseite anzuzeigen.

**Comment by Gluehwurm** [comment]
Gibt es, ja.

Inhalt (Kopfzeilen habe ich entfernt, sollten die nötig sein, bitte melden):

"cgi.tcl version: 1.8.0
input:
sid=@gKsGJ2TgA2@&iface=HmIP-RF&address=000895699E78BB&redirect_url=GO_BACK
cookie:
errorInfo:
can't read "ps(P1_HOUR_SATURDAY_1)": no such element in array
    while executing
"set timeoutHour     $ps(P1_HOUR_${day}_$i)"
    (procedure "getWeeklyProgram" line 24)
    invoked from within
"getWeeklyProgram $address ps"
    (procedure "set_htmlParams" line 10)
    invoked from within
"set_htmlParams $iface $ch_address ch_ps ch_ps_descr CHANNEL_$ch_descr(INDEX) """
    (procedure "put_channel_parameters" line 122)
    invoked from within
"put_channel_parameters"
    (procedure "put_page" line 45)
    invoked from within
"put_page"
"

**Comment by jens-maus** [comment]
Bitte mal überprüfen ob der folgende zusätzliche Eintrag in die `/etc/lighttpd/lighttpd.conf` Datei das Problem löst:

```
server.max-request-field-size = 65536
```

Diese Zeile bitte dort eintragen und dann RaspberryMatic neustarten und bitte erneut probieren.

Siehe:
https://github.com/jens-maus/RaspberryMatic/issues/187

**Comment by martz170** [comment]
server.max-request-field-size = 65536
hat für HMIP-BDT 1.4.8 keine Parameter sichtbar #174   nichts gebracht  - gleicher Fehler, gleiche Meldung

**Comment by schneidy76** [comment]
dito :-)

**Comment by schneidy76** [comment]
`cgi.tcl version: 1.8.0
input:
sid=@VXqZ38OUGK@&iface=HmIP-RF&address=0008D5699C6014&redirect_url=GO_BACK
cookie:
errorInfo:
can't read "ps(P1_HOUR_SATURDAY_1)": no such element in array
    while executing
"set timeoutHour     $ps(P1_HOUR_${day}_$i)"
    (procedure "getWeeklyProgram" line 24)
    invoked from within
"getWeeklyProgram $address ps"
    (procedure "set_htmlParams" line 11)
    invoked from within
"set_htmlParams $iface $ch_address ch_ps ch_ps_descr CHANNEL_$ch_descr(INDEX) """
    (procedure "put_channel_parameters" line 122)
    invoked from within
"put_channel_parameters"
    (procedure "put_page" line 45)
    invoked from within
"put_page"
`

**Comment by jens-maus** [comment]
This is nothing new and exactly the same like @Gluehwurm posted above. Yet I couldn't reproduce it because I don't have a HmIP-FSM or HmIP-BDT here.

**Comment by Gluehwurm** [comment]
Wie schon geschrieben, ändert die Zeile nichts. Siehe auch PN

Danke
