### ISSUE TITLE
HMIP-BDT 1.4.8 keine Parameter sichtbar

### ISSUE THREAD

**Issue by martz170** [jens-maus/RaspberryMatic#174]
Hallo Jens,
nach Firmwareupdate des Aktors sind keine Parameter mehr sichtbar. Reset und mehrfaches neues Anlernen brachte keinen Erfolg. Auch ein komplettes löschen aller IP Aktoren /usr/local/etc/config/crRFD...
brachte keinen Erfolg.
Getestet mit aktueller und vorheriger Version von Rasperrymatic.
Im einschlägigen Forum berichten mehrere User von dem gleichen Problem.
https://homematic-forum.de/forum/viewtopic.php?f=58&t=39350
https://homematic-forum.de/forum/viewtopic.php?f=58&t=34401&start=30

Beim öffnen der Aktoreinstellungsseite wird eine Fehlermeldungsmail an Root abgelegt mit folgendem Inhalt:
```
Return-Path: <CGI script - do not reply>
From:  <CGI script - do not reply>
To: root
Subject:  CGI problem

CGI environment:
REQUEST_METHOD: GET
SCRIPT_NAME: /config/ic_deviceparameters.cgi
HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0
HTTP_REFERER: http://192.168.33.15/pages/index.htm?sid=@Z86p38IAkt@&client=3
HTTP_HOST: 192.168.33.15
REMOTE_ADDR: 192.168.33.108
cgi.tcl version: 1.8.0
input:
sid=@Z86p38IAkt@&iface=HmIP-RF&address=0008D5699C6087&redirect_url=GO_BACK
cookie:
errorInfo:
can't read "ps(P1_HOUR_SATURDAY_1)": no such element in array
    while executing
"set timeoutHour     $ps(P1_HOUR_${day}_$i)"
    (procedure "getWeeklyProgram" line 24)
    invoked from within
"getWeeklyProgram $address ps"
    (procedure "set_htmlParams" line 11)
    invoked from within
"set_htmlParams $iface $ch_address ch_ps ch_ps_descr CHANNEL_$ch_descr(INDEX) """
    (procedure "put_channel_parameters" line 122)
    invoked from within
"put_channel_parameters"
    (procedure "put_page" line 45)
    invoked from within
"put_page"
```

**Comment by schneidy76** [comment]
bei mir auch...

**Comment by jens-maus** [comment]
Das scheint das gleiche Problem wie in #173 zu sein. Bitte daher dort weiter das Problem tracken.
