### ISSUE TITLE
Keine Kommunikation mit HM-IP nach Umstellung des Loglevels

### ISSUE THREAD

**Issue by mbhomie007** [jens-maus/RaspberryMatic#1742]
### Describe the issue you are experiencing

Nach Umstellung des Loglevels ist keine Kommunikation mehr mit Homematic-IP Geräten möglich.
Außerdem werden Änderungen von "Alles loggen" auf "Nur Warnungen" erst nach einem Neustart wirksam und nicht während des Betriebs. 
Erst nach einem Neustart der Zentrale funktioniert wieder alles. 

### Describe the behavior you expected

Änderungen werden während des Betriebes wirksam.
Kein Aufhängen der HM-IP Kommunikation. 

### Steps to reproduce the issue

1. Einstellungen
2. Zentralenwartung
3. Fehlerprotokoll
4. Loglevel ändern

### What is the version this bug report is based on?

3.61.7.20220226

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
-
```

**Comment by jens-maus** [comment]
Das die Loglevel-Änderungen erst nach einem Neustart aktiv werden ist für HmIPServer normal.

**Comment by mbhomie007** [comment]
@jp112sdl @Baxxy13 
#1682

https://homematic-forum.de/forum/viewtopic.php?p=708560#p708560

https://homematic-forum.de/forum/viewtopic.php?p=708573#p708573

**Comment by mbhomie007** [comment]
> Das die Loglevel-Änderungen erst nach einem Neustart aktiv werden ist für HmIPServer normal.

Okay, dann bleibt aber noch das Problem, dass keine Kommunikation mit HM-IP mehr stattfindet.

Nach einer Änderung des Loglevels kommt ein Fenster "Homematic-IP Server wird eventuell neu gestartet", danach funktioniert aber eben die Kommunikation nicht mehr.

**Comment by jens-maus** [comment]
Dann solltest du mal in die Logfiles unter `/var/log` reinschauen ob du da nach dem Umstellen des loglevels etwas verdächtiges findest warum der HMIPServer danach nicht mehr funktioniert?!?

**Comment by Baxxy13** [comment]
Ich hatte ja schon so meine Diskrepanzen mit #1682.
Das Ende der Geschichte ist, das ich dem HmIP-Server beim booten meine eigenen log4j.xml unterjubele und da im laufenden Betrieb tunlichst nichts an den Logging-Einstellungen ändere.

Meiner Meinung nach ist der Neustart des HmIP-Servers im laufenden System eine ganz schlechte Idee. Denn das kommt ja quasi einem halben Zentralen-Neustart gleich weil alle IP-Devices ihre default-Werte bekommen. Da hilft dann nicht mal mehr der beliebte "Programmstarts beim Reboot verhindern" Workaround weil die "Sicherheitsleine" (SysVar "Anwesenheit") sagt "alles ok, der Reboot ist lange vorbei".
Und die schlechte Idee wird noch schlechter wenn man den CCU-Jack drauf hat, der bekommt sich dann gar nicht mehr ein und versucht sich im Sekundentakt neu zu starten. (Ließe sich sicher durch Mathias fixen)

Auch wenn ich allgemein den Gedanken hinter dieser "IP-Loglevel im laufenden Betrieb ändern" Sache gut finde, bin ich der Meinung das das nicht so "aggressiv" umgesetzt sein sollte.

Mein Vorschlag wäre beim ändern des IP-Loglevel den HmIP-Server nicht neu zu starten, sondern darauf hinzuweisen das die Zentrale neu gestartet werden muss damit die geänderten Einstellungen wirksam sind. Mann könnte auch eine zusätzliche Checkbox (mit entsprechendem Hinweistext) implementieren, die bei "aktiv" den HmIP-Server direkt neu startet.

**Comment by Baxxy13** [comment]
Da es mir auch den CCU-Historian beim Umstellen des Loglevels wegsäbelt bin ich dafür den automatischen Restart des HmIP-Servers wieder zu entfernen.

**Comment by mbhomie007** [comment]
Hallo!
@jens-maus @Baxxy13 @jp112sdl 

Ich habe mal den aktuellen Snapshot 3.63.8.20220405 getestet.
Habe Homematic-IP von "Nur Warnungen" auf "Information" gestellt.

![image](https://user-images.githubusercontent.com/64688879/161981795-27ee3f6a-8691-48cb-b3f4-61530a3b22e6.png)

Im Browser erscheint das Fenster:

![image](https://user-images.githubusercontent.com/64688879/161981723-5782538a-e3d6-4765-b870-635fde32d519.png)

Der Neustart im laufenden Betrieb wurde ja rausgenommen, also wird nicht im Hintergrund neu gestartet, wie in der Meldung steht.

LOG:
`Apr  6 15:05:26 Homematic-CCU syslog.info syslogd exiting`
`Apr  6 15:05:26 Homematic-CCU syslog.info syslogd started: BusyBox v1.35.0`
`Apr  6 15:05:26 Homematic-CCU kern.notice kernel: klogd started: BusyBox v1.35.0 (2022-04-05 01:02:48 UTC)`

> Na dann autom. HMIPServer restart rausnehmen und statt dessen einen Hinweis einblenden, dass die Änderung erst nach einem CCU-Reboot aktiv wird.

Sollte nicht ein kleiner Hinweistext stattdessen angezeigt werden, dass die Änderung erst nach einem Neustart aktiv ist?
Z.B. im Browserfenster oder rechts in der Spalte "Fehlerprotokoll".

**Comment by jens-maus** [comment]
> Sollte nicht ein kleiner Hinweistext stattdessen angezeigt werden, dass die Änderung erst nach einem Neustart aktiv ist?
> 
> Z.B. im Browserfenster oder rechts in der Spalte "Fehlerprotokoll".

Na dann hinsetzen und einen PullRequest einreichen. Ich kann die Welt nicht alleine retten ;)

**Comment by mbhomie007** [comment]
Das ist ja eben mein Problem, so weit bin ich noch nicht. :-) Im Moment kann ich nur mit Tests unterstützen/nerven.

>Sollte nicht ein kleiner Hinweistext stattdessen angezeigt werden, dass die Änderung erst nach einem Neustart aktiv ist?
Z.B. im Browserfenster oder rechts in der Spalte "Fehlerprotokoll".

Aber dann wären hier eventuell Rückfragen durch Laien oder eben Unwissende ausgeschlossen/minimiert, mit einem kleinen Hinweis. 💯 

Aber die Funktion ist gegeben, die Kommunikation mit Hm-IP hängt sich nicht mehr auf nach einem Umstellen des LOG-Levels. 🥇
