### ISSUE TITLE
WatchDog: hs485d-restart

### ISSUE THREAD

**Issue by thomasschumacher** [jens-maus/RaspberryMatic#1743]
### Describe the issue you are experiencing

After upgrading to the latest version (downloaded today), reset to factory defaults and restore of the backup from the previous version, I get permanent restarts from watchdog.

### Describe the behavior you expected

install of latest version, reset and restore from backup file should result in a working installation

### Steps to reproduce the issue

1.
2.
3.
...

### What is the version this bug report is based on?

3.61.7.20220226

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
/var/log/messages contains multiple of the same 2 entries:

Mar  3 21:39:01 homematic-ccu2 user.crit hs485d: Could not find serial number and encryption key.
Mar  3 21:39:01 homematic-ccu2 user.crit hs485d: Could not gather indispensable information from /etc/config/hs485d.conf
Mar  3 21:39:01 homematic-ccu2 user.crit hs485d: Could not find serial number and encryption key.
Mar  3 21:39:01 homematic-ccu2 user.crit hs485d: Could not gather indispensable information from /etc/config/hs485d.conf
Mar  3 21:39:01 homematic-ccu2 user.crit hs485d: Could not find serial number and encryption key.
Mar  3 21:39:01 homematic-ccu2 user.crit hs485d: Could not gather indispensable information from /etc/config/hs485d.conf
Mar  3 21:39:01 homematic-ccu2 user.crit hs485d: Could not find serial number and encryption key.
Mar  3 21:39:01 homematic-ccu2 user.crit hs485d: Could not gather indispensable information from /etc/config/hs485d.conf
Mar  3 21:39:01 homematic-ccu2 user.crit hs485d: Could not find serial number and encryption key.
Mar  3 21:39:01 homematic-ccu2 user.crit hs485d: Could not gather indispensable information from /etc/config/hs485d.conf
Mar  3 21:39:01 homematic-ccu2 user.crit hs485d: Could not find serial number and encryption key.
Mar  3 21:39:01 homematic-ccu2 user.crit hs485d: Could not gather indispensable information from /etc/config/hs485d.conf
```

**Comment by jens-maus** [comment]
please show the content of your `/etc/config/hs485d.conf` file because the error output suggests that there might be an issue in it.

**Comment by thomasschumacher** [comment]
Problem has been solved meanwhile. In deed there was an issue in the config file.
