### ISSUE TITLE
Documentation issue: Wrong Entity Name 

### ISSUE THREAD

**Issue by breti** [jens-maus/RaspberryMatic#1744]
### Describe the issue you are experiencing

https://github.com/jens-maus/RaspberryMatic/wiki/Installation-HomeAssistant#add-a-home-assistant-automation-to-connect-to-the-raspberrymatic-addon

Step 3

This line is wrong:
`state: "{{ state_attr('homematic.ccu3', 'V_Last_Reboot') or '01.01.1970 00:00:00' }}"`

The entity is called "raspberrymatic" in the configuration.yaml example some lines above, so the line should be
`state: "{{ state_attr('homematic.raspberrymatic', 'V_Last_Reboot') or '01.01.1970 00:00:00' }}"`

### Describe the behavior you expected

n/a

### Steps to reproduce the issue

1. n/a
2.
3.
...

### What is the version this bug report is based on?

n/a

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
n/a
```

**Comment by Baxxy13** [comment]
Erledigt.
Ist ein Wiki, wenn du Fehler findest darfst du sie auch gerne selber korrigieren.
