### ISSUE TITLE
USB Cul Stick wird nicht ins Raspberrymatic addon eingebunden

### ISSUE THREAD

**Issue by turrican944** [jens-maus/RaspberryMatic#1745]
### Describe the issue you are experiencing

USB Culstick funktioniert nicht im CUXD. Der Stick wird im CUXD angezeigt verbindet sich aber nicht mehr mit CUXD. In früheren Versionen des Raspberrymatic Addons war das möglich, wenn der Sicherheitsmodus abgeschaltet wurde. Den gibt es nicht mehr. Eine möglichkeit ein USB Gerät ins Addon einzubinden, ist auf der Konfigurationsseite nicht gegeben.
Auch eine Komplette Neuinstallation des Addons und auch vom Homeassistant OS haben nichts verändert.

### Describe the behavior you expected

USB Culstick muss wohl in den Dockercontainer explizit eigebunden werden

### Steps to reproduce the issue

1. Raspberrymatic Addon im Homeassistant starten
2. Im CUXD UI  wird Kein TTY Device Connected angezeigt
3.
...

### What is the version this bug report is based on?

3.61.7.20220226

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
-
```

### Additional information

Hardware: Odroid N2+ , eigenbau Nanocul Stick. Funkmodul steckt auf HB RF ETH.

**Comment by jens-maus** [comment]
Welches `/dev/tty*` device wurde denn von den CUL Sticks genau genutzt als es noch mit abschalten des protected modes funktionierte?

**Comment by turrican944** [comment]
Es ist /dec/ttyUSB0 zumindest zeigt das Cux an.
Vielleicht habe ich auch etwas schlecht ausgedrückt es geht nur in der alten Version mit abgeschaltetem Sicherheitsmodus. In der neuen war der nach dem Update noch aus, ging aber schon nicht. Ich muss jetzt erstmal weg kann da, später nochmal weiter schauen.

**Comment by jens-maus** [comment]
dann bitte mal innerhalb des neuen Add-on folgende Befehle mal ausführen und die Ausgaben hier zeigen:

```
ls -la /dev/ttyUSB*
```

```
lsusb
```

**Comment by turrican944** [comment]
root@de838cd8-raspberrymatic:~# ls -la /dev/ttyUSB*
crw-rw----    1 root     dialout   188,   0 Mar  4 13:04 /dev/ttyUSB0
root@de838cd8-raspberrymatic:~# 
root@de838cd8-raspberrymatic:~# lsusb
Bus 001 Device 005: ID 0403:6001
Bus 001 Device 001: ID 1d6b:0002
Bus 001 Device 003: ID 0424:2514
Bus 001 Device 002: ID 0424:2514
Bus 001 Device 004: ID 0424:7800
root@de838cd8-raspberrymatic:~# 

es ist nur der CUL Stick am USB, ich habe das auf meinem Testsystem (Raspberry 3b+ mit Homeassistant OS) gemacht, sonst gibts ärger mit der Frau wenn ich am Odroid jetzt rumspiele, auf dem Raspberry aber das gleich, es wird im CUX nicht erkannt.

![Screenshot 2022-03-04 13 21 21](https://user-images.githubusercontent.com/70096465/156762649-4b3f65e1-abe6-48f1-82c1-1905b3b8b73f.png)

**Comment by jens-maus** [comment]
Thanks for the info. I now added `uart: true` to the addon snapshot version.

So please @turrican944, try the following:

1. Go to HomeAssistant and perform a "Check for Updates".
2. Install the current snapshot version of the RaspberryMatic Add-on and stop the normal non-snapshot version.
3. Install CUxD in the snapshot version and see if using the nanoCUL with CUxD works now in the snapshot version of the Add-on.

**Comment by turrican944** [comment]
I Test the snapshot in my testsystem (Raspberry 3b+) and it works with the Cul Stick in Cuxd.
I check this evening ob my Odroid too.
Thanks

**Comment by jens-maus** [comment]
Perfect! Then I can also add this minor change to the addon config of the stable version of the addon as well so that others will benefit from this fix immediately.
