### ISSUE TITLE
Energiemessgerät HM-ES-TX-WM und Energiesensor für Smart Meter ES-IEC zeigen zu wenig Ergebnisse

### ISSUE THREAD

**Issue by disasterdaddy** [jens-maus/RaspberryMatic#1746]
### Describe the solution you'd like

Hallo,
die beiden Geräte zeigen in der Raspberry Pi3 (Charly) in der WebUI zu wenige Ergebnisse an. Es werden angezeigt:
Energie-Zähler RaspMatic
4218.6853 kWh
1307.79 EUR
Es könnten aber noch mehr Werte angezeigt werden wie z.B. der momentane Verbrauch und anderes mehr. Wenn es nicht in der WebUI angezeigt wird, gibt es hierzu evtl. Scripte?
Mit freundlichen Grüßen
disasterdaddy

![HM-ES-TX-WM Konfiguration 1](https://user-images.githubusercontent.com/86557749/156881103-cf3e14a3-98f3-4764-8f10-686e0bf3ad9c.jpg)
![HM-ES-TX-WM Messwerte](https://user-images.githubusercontent.com/86557749/156881110-58e65200-9ef9-4e65-af3e-ac98d9b42856.jpg)
![HM-ES-TX-WM Sensor](https://user-images.githubusercontent.com/86557749/156881121-4a3079b2-207d-4cfd-8fa2-f00a2c160370.jpg)

### Describe alternatives you've considered

Hinzufügen weiterer Messergebnisse

### Is your feature request related to a problem?

Das ist eine Feature.

**Comment by jens-maus** [comment]
> Es könnten aber noch mehr Werte angezeigt werden wie z.B. der momentane Verbrauch und anderes mehr. Wenn es nicht in der WebUI angezeigt wird, gibt es hierzu evtl. Scripte?

Das hier ist kein Hilfeforum sondern ein Entwicklungswerkzeug, d.h. ein Bug- und Issue-Tracker! Bitte also ein entsprechendes Supportforum verwenden (z.B. homematic-forum.de) und dort die Suche bemühen. Eine kurze suche dort hätte dich direkt auf folgenden Beitrag gelenkt:

https://homematic-forum.de/forum/viewtopic.php?f=27&t=31353

Alles andere dort, denn wie gesagt ist das hier kein Diskussionsforum wo jeder seine Problemchen in der Bedienung der Zentrale vorbringen kann/sollte.

**Comment by disasterdaddy** [comment]
Hallo Jens,

 

vielen Dank für die schnelle Antwort. Und bitte nicht böse sein, dass ich das falsche Forum selektiert habe. Gelobe Besserung. :-)
 

Mit freundlichen Grüßen
Harald Kauffmann

Dutlhejjaj HoS

 
 

Gesendet: Samstag, 05. März 2022 um 12:44 Uhr
Von: "Jens Maus" ***@***.***>
An: "jens-maus/RaspberryMatic" ***@***.***>
Cc: "Harald Kauffmann" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [jens-maus/RaspberryMatic] Energiemessgerät HM-ES-TX-WM und Energiesensor für Smart Meter ES-IEC zeigen zu wenig Ergebnisse (Issue #1746)


 


Es könnten aber noch mehr Werte angezeigt werden wie z.B. der momentane Verbrauch und anderes mehr. Wenn es nicht in der WebUI angezeigt wird, gibt es hierzu evtl. Scripte?


Das hier ist kein Hilfeforum sondern ein Entwicklungswerkzeug, d.h. ein Bug- und Issue-Tracker! Bitte also ein entsprechendes Supportforum verwenden (z.B. homematic-forum.de) und dort die Suche bemühen. Eine kurze suche dort hätte dich direkt auf folgenden Beitrag gelenkt:

https://homematic-forum.de/forum/viewtopic.php?f=27&t=31353

Alles andere dort, denn wie gesagt ist das hier kein Diskussionsforum wo jeder seine Problemchen in der Bedienung der Zentrale vorbringen kann/sollte.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
