### ISSUE TITLE
Incident !  WebUI nicht erreichbar nach Zeitumstellung

### ISSUE THREAD

**Issue by martz170** [jens-maus/RaspberryMatic#175]
Das WebUI ist nach Zeitumstellung nicht erreichbar !

siehe:   https://homematic-forum.de/forum/viewtopic.php?f=65&t=39750

**Comment by anli-xsigns** [comment]
Momentan wird im Forum viel an den Threads organisiert um es übersichtlich zu halten, ich empfehle aktuell https://homematic-forum.de/forum/viewtopic.php?f=65&t=39780 als Einstiegspunkt.

**Comment by jens-maus** [comment]
Problem sollte inzwischen behoben sein:
https://homematic-forum.de/forum/viewtopic.php?f=26&t=36623&p=394878#p394878
