### ISSUE TITLE
[Docker] Invalid module format error

### ISSUE THREAD

**Issue by andyboeh** [jens-maus/RaspberryMatic#1750]
### Describe the issue you are experiencing

I'm running RaspberryMatic in a docker container on Arch Linux (Linux 5.16). eq3_char_loop-dkms and pivccu-modules-dkms are installed from the AUR (actually, a locally-updated pivccu-modules-dkms PKGBUILD, but that's not important for the issue).

When starting the docker container, multimacd reports the following error message:
`Starting multimacd: modprobe: can't load module eq3_char_loop (updates/dkms/eq3_char_loop.ko.zst): invalid module format`. The eq3_char_loop kernel driver cannot be loaded and the system does not work properly.

### Describe the behavior you expected

The eq3_char_loop driver should be loaded automatically.

### Steps to reproduce the issue

1. Start the docker container :)

### What is the version this bug report is based on?

3.61.7.20220226

### Which base platform are you running?

oci (Open Container Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
No
```

### Additional information

There is a workaround and a (hopefully) simple solution:

**Workaround**: Load eq3_char_loop on the host before starting the docker container. This works until the next restart of the container, because the eq3_char_loop driver is unloaded on shutdown.

**Probable cause**: Arch Linux uses ZSTD compressed kernel modules. The modprobe inside the container doesn't seem to know about this compression, as `modinfo eq3_char_loop` only prints the file name. The `zstd` command is not found.

**Probable solution**: I'm not sure if just adding the zstd utility is enough or if modprobe needs to be compiled with ZSTD support, but I suppose that this fixes the issue.

**Comment by jens-maus** [comment]
> **Probable solution**: I'm not sure if just adding the zstd utility is enough or if modprobe needs to be compiled with ZSTD support, but I suppose that this fixes the issue.

I added the relevant xz and zstd libraries now so that kmod/modprobe should now supported compressed kernel module loading in principle. However, please make sure to test this with the next nightly snapshot if possible and report back if it did not work as expected.

**Comment by andyboeh** [comment]
Thanks for the quick support! I just downloaded the current snapshot image and I can confirm that xz and zstd are now in the image. Unfortunately, it still doesn't work. I ran `LD_TRACE_LOADED_OBJECTS=1 modinfo` inside the container and this is the output:
```
        linux-vdso.so.1 (0x00007ffcf635b000)
        libm.so.6 => /lib/libm.so.6 (0x00007f56bc72f000)
        libresolv.so.2 => /lib/libresolv.so.2 (0x00007f56bc71c000)
        libc.so.6 => /lib/libc.so.6 (0x00007f56bc520000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f56bc80e000)
```
So it's still not linked against `libzstd.so`. Running the same on my host machine gives:

```
	linux-vdso.so.1 (0x00007ffcfbfc5000)
	libzstd.so.1 => /usr/lib/libzstd.so.1 (0x00007fc45ff95000)
	liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007fc45ff6c000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007fc45ff52000)
	libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007fc45fc71000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fc45fc56000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fc45fa4c000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fc45fa45000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fc45fa40000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc46008a000)
```

I had a look at the buildroot package's `kmod.mk`: It should have worked that way and it should have been built. I'll try to compile from source and see if I can find something.

**Comment by andyboeh** [comment]
I found it: For the OCI targets, `BR2_PACKAGE_KMOD_TOOLS` is not set, so the tools like `modprobe` aren't even built. The modprobe in the docker image is provided by busybox!

**Comment by jens-maus** [comment]
> For the OCI targets, `BR2_PACKAGE_KMOD_TOOLS` is not set,

Thx for the hint. I added `BR2_PACKAGE_KMOD_TOOLS` now, so please retry with the next nightly snapshot build again.

**Comment by andyboeh** [comment]
It's working properly now, thanks for the fix!
