### ISSUE TITLE
HmIP-DRSIx - Aktoren ignorieren den "Systeminterne Kanäle einblenden / ausblenden - Button"

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1751]
### Describe the issue you are experiencing

Nachdem ich nun nach 4 Monaten endlich mal mein Live-System wieder updaten konnte (läuft soweit problemlos), ist mir aufgefallen das meine beiden HmIP-DRSIx Aktoren unter "Status und Bedienung > Geräte" immer den Kanal:0 anzeigen.
Also völlig egal ob "systeminterne Kanäle einblenden" aktiv ist oder eben nicht.
Bei allen anderen IP-Geräten die ich so habe arbeitet der Button korrekt. 

### Describe the behavior you expected

Auch von den HmIP-DRSIx Aktoren sollte per default der Kanal:0 nicht angezeigt werden. Der Kanal:0 sollte erst nach Umschalten zu "systeminterne Kanäle einblenden" sichtbar sein.

### Steps to reproduce the issue

1. bei vorhandenen HmIP-DRSIx Aktoren in "Status und Bedienung > Geräte" die Kanäle "begutachten"
2. den Button "Systeminterne Kanäle einblenden / ausblenden" drücken
3. Kanal:0 von den HmIP-DRSIx Aktoren ist immer sichtbar
...

### What is the version this bug report is based on?

3.61.7.20220226

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
keinerlei Fehlermeldungen in der Browserkonsole oder in den Logfiles
```

### Additional information

Ich habe den Code von #1488 mal überflogen, aber das übersteigt meine Fähigkeiten.
Daher kann ich nicht erkennen warum die HmIP-DRSIx Aktoren ein anderes Verhalten zeigen.

**Comment by jp112sdl** [comment]
> Kanal:0 von den HmIP-DRSIx Aktoren ist immer sichtbar

Ist bei diesen der Kanal 0 "Internal"?
Ist Kanal 0 vom HssType "MAINTENANCE" ?

Ansonsten als Hinweis vielleicht noch: Zur 3.61 ist hier noch eine Sonderbehandlung für die DRSI reingekommen:
https://github.com/eq-3/occu/blame/master/WebUI/www/rega/esp/functions.fn#L393

**Comment by Baxxy13** [comment]
> Ist bei diesen der Kanal 0 "Internal"?

per default ist Kanal:0 nicht "Internal", ist aber bei allen IP-Geräten (die ich habe) so


> Ist Kanal 0 vom HssType "MAINTENANCE" ?

ja

![RM_DRSIx_Kanal_0](https://user-images.githubusercontent.com/54898249/157397023-838a94f8-f19d-49b9-87be-a09c95f8d9ed.JPG)

An der "Sonderbehandlung" ist was dran. So ganz erschließt sich mir zwar (noch) nicht was gemeint ist, vermutlich hat das aber was mit dieser "Beleuchtungsdauer-Regelung" von Display und Taste zu tun. Ich bräuchte das nicht zwingend dauerhaft angezeigt. 

![RM_DRSIx_Kanal_0_anzeige](https://user-images.githubusercontent.com/54898249/157399122-2d0bf3a6-5089-4061-a1bf-4199ff264533.JPG)
Jetzt sehe ich gerade noch das auch 2 Statuswerte doppelt angezeigt werden (Betriebsspannung / Status Betriebsspannung), ist aber halb so wild wenn man denn den ganzen Kanal ausblenden könnte.

**Comment by Baxxy13** [comment]
> Sonderbehandlung

Wie immer war das der entscheidende Hinweis.

Ändere ich die Abfragebedingung von...
`if ((oDevHssType.Substr(0,6) == "HmIPW-") || (oDevHssType == "HmIP-DRSI1") || (oDevHssType == "HmIP-DRSI4")) {`
zu...
`if (oDevHssType.Substr(0,6) == "HmIPW-") {`

Wird der Kanal:0 der DRSIx per default nicht angezeigt, lässt sich dann aber korrekt mit dem Button einblenden.

Ob man das so machen sollte weiß ich nicht, vor allem weil mir der "Hilfetext" bei der Bedingung so gar nichts sagt.
```
 ! A HmIPW-* device with a control for the parameter IDENTIFY_TARGET_LEVEL (MAINTENANCE channel)
 ! should be visible. So it's possible to use the identify function of wHmIPW-devices.
```

**Comment by jens-maus** [comment]
> Ob man das so machen sollte weiß ich nicht, vor allem weil mir der "Hilfetext" bei der Bedingung so gar nichts sagt.
> 
> ```
>  ! A HmIPW-* device with a control for the parameter IDENTIFY_TARGET_LEVEL (MAINTENANCE channel)
>  ! should be visible. So it's possible to use the identify function of wHmIPW-devices.
> ```

Das scheint mir die gleiche Herangehensweise von eQ3 zu sein wie bei den HmIP-Wired Aktoren. Dort ist ja der Maintenance-Channel auch immer sichtbar damit man eben die Beleuchtungsfunktion des Displays bzw. der Systemtaste jederzeit starten kann und nicht vorher den Maintenance-Channel ein/ausblenden lassen muss.

Ich schau mir das mal an, denke aber das es eigentlich richtige wäre dieses gesamte if() hier zu eliminieren (inkl. der Wired bedingung) eben weil WIR ja die möglichkeit jetzt erst geschaffen haben den Maintenance Channel ein/auszublenden und weil es wirklich nicht logisch ist warum für einige Geräte :0 immer angezeigt wird und für alle anderen nicht. Da hat eQ3 vmtl. zu kurz nachgedacht.

**Comment by jens-maus** [comment]
@Baxxy13 Nun hab ich es wie besprochen umgesetzt. Bitte mal schauen ob es mit dem nächsten nightly build nun passt.

**Comment by Baxxy13** [comment]
Das geht leider nicht. Die DRSIx sind im Hauptsystem und da habe ich aktuell keinen physischen Zugriff.
Bin erst in 3 Wochen wieder vor Ort.
Gehen wir einfach mal davon aus das du alles richtig gemacht hast. ;-)

**Comment by jens-maus** [comment]
Vielleicht dann einfach den folgenden patch aus der Ferne anwenden und schauen ob es geht?

https://github.com/jens-maus/RaspberryMatic/blob/fd8182b9e95177b332b22cb27e30e26ea25d09d0/buildroot-external/patches/occu/0133-WebUI-Fix-InternalIDExposure.patch#L14-L39

**Comment by Baxxy13** [comment]
Hmm, das ist nicht so meine Welt. Hab jetzt als Trockenübung mal versucht eine lokale .ova zu patchen.
```
root@RM-Test-OVA-18:/# mount -o remount,rw /
root@RM-Test-OVA-18:/# wget -O /tmp/drsi.patch https://raw.githubusercontent.com/jens-maus/RaspberryMatic/fd8182b9e95177b332b22cb27e30e26ea25d09d0/buildroot-external/patches/occu/0133-WebUI-Fix-In
ternalIDExposure.patch
--2022-03-11 09:20:56--  https://raw.githubusercontent.com/jens-maus/RaspberryMatic/fd8182b9e95177b332b22cb27e30e26ea25d09d0/buildroot-external/patches/occu/0133-WebUI-Fix-InternalIDExposure.patch
Resolving raw.githubusercontent.com... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9381 (9.2K) [text/plain]
Saving to: '/tmp/drsi.patch'

/tmp/drsi.patch                                  100%[==========================================================================================================>]   9.16K  --.-KB/s    in 0.002s

2022-03-11 09:20:57 (5.36 MB/s) - '/tmp/drsi.patch' saved [9381/9381]

root@RM-Test-OVA-18:/# cd /www
root@RM-Test-OVA-18:/www# patch -N -p3 -i /tmp/drsi.patch
```

Das schlägt aber fehl weil der gesamte Patch angewandt werden soll.
Mir ist nicht klar wie ich nur deine markierten Zeilen patchen kann.

**Comment by jens-maus** [comment]
> Das schlägt aber fehl weil der gesamte Patch angewandt werden soll.
> Mir ist nicht klar wie ich nur deine markierten Zeilen patchen kann.

Das einfachste ist du machst die Änderungen schnell von Hand ohne patch-tool. Sind ja nur ein paar Zeilen löschen oder auskommentieren, mehr nicht.

**Comment by Baxxy13** [comment]
War tatsächlich einfacher.
Änderungen händisch eingebaut...
ReGa neu gestartet...
Sieht gut aus!
