### ISSUE TITLE
"Starting multimacd: ...........ERROR" at HassOS

### ISSUE THREAD

**Issue by myrma** [jens-maus/RaspberryMatic#1752]
### Describe the issue you are experiencing

RaspberryMatic startet nicht mehr sauber und bringt im Protokol folgende drei Fehler
```
Starting multimacd: ...........ERROR
Starting rfd: ....................ERROR
Starting HMIPServer: .....................................................................................................ERROR
```

Ich habe inzwischen mein HassOS neu aufgesetzt und mehrfach versuch RaspberryMatic neu zu installieren. Manchmal hilft das deinstallieren und neu installieren des RaspberryMatic Add-on für kurze Zeit doch spätestens bei einem Reboot des RaspberryPi tritt das Problem erneut auf. 

### Describe the behavior you expected

Funktionsfähiges RaspberryMatic.

Die Möglichkeit auf ein downgrade einer ältere Version von RaspberryMatic wäre praktisch und könnte mir an dieser Stelle vielleicht ja schon weiterhelfen. 

### Steps to reproduce the issue

1. Installation von HassOS für RaspberryPi 4 (64-Bit)
2. Installation von RaspberryMatic

### What is the version this bug report is based on?

3.61.7.20220226

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Mounting /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying host system: oci, OK
Initializing RTC Clock: rx8130, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: OK: backup successfully restored
Initializing System: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.0, OK
Identifying Homematic RF-Hardware: ....HmRF: RPI-RF-MOD/GPIO, HmIP: RPI-RF-MOD/GPIO, OK
Updating Homematic RF-Hardware: RPI-RF-MOD: 4.4.12, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: ...........ERROR
Starting rfd: ....................ERROR
Starting HMIPServer: .....................................................................................................ERROR
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: OK
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.61.7.20220226 (raspmatic_oci_arm64)
```

### Additional information
Home Assistant OS 7.4
      --> core-2022.3.3
      --> supervisor-2022.01.1

_No response_

**Comment by jens-maus** [comment]
Welche HomeAssistantOS Version ist auf dem genutzten RaspberryPi System im Einsatz oder. wird HomeAssistant vielleicht sogar "supervised" innerhalb eines bestehenden Linux-Systems (RaspberryPiOS / Debian, etc.) betrieben?

**Comment by manu216** [comment]
Home Assistant OS 7.4
      --> core-2022.3.3
      --> supervisor-2022.01.1

**Comment by jens-maus** [comment]
Dann sollte das problemlos funktionieren. Was passiert wenn du das addon neu/frisch installierst und kein backup einspielst? Tritt dann der Fehler auch auf?

**Comment by ha48653** [comment]
Bei mir tritt der Fehler identisch auf:

Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: ...........ERROR
Starting rfd: ....................ERROR
Starting HMIPServer: .....................................................................................................ERROR
Starting ReGaHss: .OK
Starting CloudMatic: OK

Home Assistant OS 7.4
Version core-2022.3.2
Supervisor-Version supervisor-2022.03.2
VirtualBox
RaspberryMatic Addon 3.61.7.20220226 (raspmatic_oci_amd64)

**Comment by manu216** [comment]
@jens-maus 
Wenn ich das addon neu/frisch installiere und kein backup einspiele ist das verhalten genauso. Manchmal funktionierts für eine weile und manchmal nicht. Aber selbst wenn es funktioniert ist spätestens nach einem Reboot wieder schluss und es funktioniert wieder nicht.

**Comment by Masanetz** [comment]
Rollback auf RaspberryMatic Addon 3.61.7.20220115 hat bei mir geholfen, auch nach drei Reboots...

Home Assistant OS 7.4
Version core-2022.3.3
Supervisor-Version supervisor-2022.03.2
rpi4 (RaspberryPi4)
RPI-RF-MOD

**Comment by jens-maus** [comment]
Ich denke ich hab das Problem gefunden bzw. konnte es selbst mit einem RaspberryPi4 reproduzieren. Ein `sleep 5` nach dem modprobe scheint hier weiterhin notwendig zu sein um HomeAssistantOS genug zeit zu geben das `/dev/eq3loop` device dynamisch verfügbar zu machen (siehe https://github.com/jens-maus/RaspberryMatic/commit/a32b39d4ea530f99faedd3eea59750524ebc3432) Bitte also mit dem nächsten nightly snapshot einmal testen und zurückmelden ob es damit nun verlässlich (auch nach einem Reboot von HomeAssistantOS) funktioniert.

**Comment by eli4711** [comment]
Hallo Jens
Auf der NUC Plattform gibt es dieses Problem scheinbar auch. Seit der sleep delay wieder raus ist, ist der boot von rfd ein Zufallsprodukt.

**Comment by eli4711** [comment]
Hallo Jens
Mit der 3.61.7.20220315-a8d959-intelnuc tritt das Problem wieder auf. Der rfd startet nicht mehr.

![IMG_20220315_154650 1](https://user-images.githubusercontent.com/40276118/158409319-5bd12627-ea26-48bf-988a-51a9aa87d9c1.jpg)

Falls du irgend was an Log's oder so brauchst, einfach kurz melden.
Grüße Thomas

**Comment by jens-maus** [comment]
@eli4711 Das muss andere Ursachen haben. Würde mich wundern wenn ein `sleep 5` nicht langt nach dem `modprobe eq3_char_loop`. Kannst es ja gerne selbst mal hochsetzen. Meine aktuelle Vermutung ist das es irgendwas mit deinen BidCos-RF LAN Gateways zu tun hat. Und wie du am Titel dieses Tickets siehst kommt bei dir ja kein "Starting multimacd..." Fehler, sondern der Fehler passiert im `rfd` startup. Daher denke ich nicht das das hier her gehört.

**Comment by jens-maus** [comment]
Wie kommt man den darauf? Der Titel passt ja nichtmal zu deiner Ausgabe?!?

**Comment by eli4711** [comment]
Servus Jens

Na wegen des Ursprungs Issue #1707
Das ist genau das Fehlerbild was ich hatte. 

Aber du hattest vermutlich recht mit deiner Vermutung, habe den gesamten Netzwerk Pfad, zwischen CCU und Repeatern untersucht und festgestellt, das zwischen 2 Gigabit Switches noch ein Cat5 Kabel gepatcht war. Seit ich das gegen ein Cat5e Kabel getauscht hab, ist ruhe.

Grüße Thomas
