### ISSUE TITLE
JSON RPC API Method Session.login fails on Beta 3.61.7.20220311 (ova)

### ISSUE THREAD

**Issue by gerklu** [jens-maus/RaspberryMatic#1754]
### Describe the issue you are experiencing

Calling the Method "Session.login" fails with an JSONRPCError.

Example Request: 
`{"method":"Session.login","params":{"username":"Admin","password":"XXX-HIDDEN-XXX"}}`

Error Response:
```
{
  "version": "1.1",
  "result": null,
  "error": {
    "name": "JSONRPCError",
    "code": 200,
    "message": "internal error:\nUnsupported URL: 127.0.0.1\/login.htm\n    while executing\n\"::http::geturl $LOGIN_URL -query [::http::formatQuery tbUsername $username tbPassword $password]\"\n    (file \"\/www\/api\/methods\/session\/login.tcl\" line 45)\n    invoked from within\n\"source [file join $env(DOCUMENT_ROOT) \"api\/methods\/$method(SCRIPT_FILE)\"]\""
  }
}
```

### Describe the behavior you expected

Expected behaviour is, that a call of the method creates a valid Session (in case of valid credentials) and a valid JSON RPC Response:

`{"version": "1.1","result": "sessionid","error": null}`

### Steps to reproduce the issue

Send valid JSON RPC-Request for Method "Session.login"

### What is the version this bug report is based on?

3.61.7.20220311 (ova)

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
-empty-
```

**Comment by jens-maus** [comment]
Can you please provide a simple `curl` command-line call here with the error displayed. And also please state if the issue is also present in the latest stable build because you are using a nightly snapshot (not a beta!).

**Comment by jens-maus** [comment]
Ok, I worked out a `wget` command-line myself to reproduce the issue:

```
/usr/bin/wget -q -O - --post-data '{ "method": "Session.login", "params": { "username": "Admin", "password": "1234" }}' http://127.0.0.1/api/homematic.cgi
```

Executing this directly in a SSH session on the RaspberryMatic exhibits the error output mentioned here.

**Comment by jens-maus** [comment]
I think I found the issue. So please retry with the next nightly snapshot or apply the following patchset:

https://github.com/jens-maus/RaspberryMatic/blob/8e702bd7c9dd7ec7d76339125cfaac64d23a7ec3/buildroot-external/patches/occu/0167-WebUI-Fix-InternalTclURLs.patch

And then please report back if the issue is solved or not.

**Comment by gerklu** [comment]
Works again with latest nightly 👍
Thanks!
