### ISSUE TITLE
Beim Starten bleibt die "RasperryMatic ist noch nicht bereit"-Seite stehen!

### ISSUE THREAD

**Issue by sruhsam** [jens-maus/RaspberryMatic#176]
Habe heut ein Problem mit der RaspberryMatic entdeckt. Aktuell hatte ich die Version homematic-ccu2-2.27.8.20170501 !
Nachdem ich auf die Web-UI schauen wollte, wird die Seite "RaspberryMatic ist noch nicht bereit, bitte warten, Sie werden automatisch auf die Starseite weitergeleitet" angezeigt und verschwindet auch nach längerer (2h) nicht mehr. 
Nachdem habe ich die aktuellste img-Version "RaspberryMatic-2.29.23.20171022-rpi3" aufgespielt und gestartet. Nun kommt ich auch nach ein paar Minuten Wartezeit des ersten Starts wieder auf die Web-UI.
Da ich tägliche sbk-Backups mache, habe ich dies versucht zurückzuspielen. Habe welche nach dem 22.10. als auch vor dem 22.10. versucht, aber leider verschwindet dann die oben beschriebene Wartenseite nicht mehr.
Ich hoffe Ihr habt eine Idee und könnt mir helfen????
Grüße aus dem Aichtal
Stephan

**Comment by Torben80** [comment]
https://homematic-forum.de/forum/viewtopic.php?f=65&t=39750&start=170

Da sollte alles stehen...

**Comment by anli-xsigns** [comment]
Momentan wird im Forum viel an den Threads organisiert um es übersichtlich zu halten, ich empfehle aktuell https://homematic-forum.de/forum/viewtopic.php?f=65&t=39780 als Einstiegspunkt.

**Comment by Torben80** [comment]
Jap, das ist richtig,...
"anli" hat das schon gut zusammengefasst.

**Comment by sruhsam** [comment]
Super klasse, Danke für eure Antwort. Funktioniert alles wieder, soweit ich Beurteilen kann.
