### ISSUE TITLE
HM-MOD-Re-8 hat 9 Kanäle?

### ISSUE THREAD

**Issue by gerdfinder** [jens-maus/RaspberryMatic#1765]
### Describe the issue you are experiencing

RaspberryMatic-3.61.7.20220226-rpi0
hier gehen die Kanäle von 0 bis 8, also 9 Kanäle.
Die hat der Empfänger natürlich nicht.

Ob dieser Fehler in vorangegangenen Version ist/war ist mir nicht bekannt
![HM-MOD-Re-8](https://user-images.githubusercontent.com/29888008/158866650-92534aac-a505-454a-b5cd-f94070082896.png)

### Describe the behavior you expected

Kanal:0 gibt es nicht

### Steps to reproduce the issue

1. Empfänger neu angelernt und die 9 Kanäle sind da.
2. Empfänger abgelernt
3. Empfänger erneut angelernt und wieder 9 Kanäle.
...

### What is the version this bug report is based on?

3.61.7.20220226

### Which base platform are you running?

rpi0 (RaspberryPi)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
no
```

**Comment by jens-maus** [comment]
Das ist kein, sondern ein Feature! kanal :0 ist der sogenannte Maintenance Kanal wie bei allen Homematic/homematicIP Geräten schon immer existierte, nur eben nicht standardmäßig in der WebUI angezeigt wird.

Kann hier also keinen Fehler erkennen.

**Comment by gerdfinder** [comment]
OK, danke.
War verunsichert weil ich zunächst nur die beiden ersten Kanäle,
genauer gesagt :0 und :1  benutzen wollte und :0 obwohl als bedienbar angezeigt wurde
nicht in der Raumzuordnung zwar anhakbar ist, aber nicht so gespeichert wird.
Bei der Fehlersuche sah ich dann 0 bis 8,
also benutzbar wie beim Original (wo es keinen Kanal:0 gibt) sind 1 bis 8.

Nochmals danke.

Gerd
