### ISSUE TITLE
Show Hardware model in webinterface - Model im Webinterface anzeigen.

### ISSUE THREAD

**Issue by ChR-iSz** [jens-maus/RaspberryMatic#1775]
### Describe the solution you'd like

Hi,

can we show the hardware model in Webinterface ? For every Update i must search for the model, and download the right expected file for the Hardware, like rpi1, rpi2, rpi3, rpi4, etc...

The information are still available in backend:

```
root@homematic-ccu2:~# cat /sys/firmware/devicetree/base/model
Raspberry Pi 3 Model B Rev 1.2
```

**Comment by jens-maus** [comment]
Already the case. Go to help page!

**Comment by ChR-iSz** [comment]
Great. Dankeschön!
