### ISSUE TITLE
3.63.8.20220330 startet nicht auf RaspberryPi2 Model B

### ISSUE THREAD

**Issue by r4m3u5** [jens-maus/RaspberryMatic#1778]
### Describe the issue you are experiencing

Nach Update von 3.61.7.20220226 und auch mit "frischem" Image ohne Config bleibt RaspiMatic 3.63.8.20220330 beim Start hängen.
Es wird "Bitte warten. Sie werden automatisch auf die Startseite weitergeleitet." angezeigt und das war es. Getestet auf 2 verschiedenen Pi2 Mod. B.

### Describe the behavior you expected

Normaler Systemstart

### Steps to reproduce the issue

1. Update durchführen oder "RaspberryMatic-3.63.8.20220330-rpi2.zip" flashen
2. RPi2 Mod. B starten

### What is the version this bug report is based on?

3.63.8.20220330

### Which base platform are you running?

rpi2 (RaspberryPi2)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
n/a
```

**Comment by jens-maus** [comment]
Konnte das Problem reproduzieren. Ist jedoch in der Tat auf die RaspberryPi2 (rpi2) platform beschränkt.

**Comment by jens-maus** [comment]
Habe das Problem mit dem rpi2 Image nun repariert und selbst nochmal getestet das es nun gehen sollte. Hab auch entsprechend einen neuen Build für rpi2 erzeugt und entsprechend hochgeladen. Das neue rpi2 zip Archiv hat die sha256 checksumme: `c01907280f4a4dc2fd6723f46bdf8be8c86611a373cb3325d3b0dc217934f5a6`
