### ISSUE TITLE
Writeable directory which is not part of the CCU backup

### ISSUE THREAD

**Issue by mdzio** [jens-maus/RaspberryMatic#179]
A separate directory should be provided in which applications (add-ons) can store data that should **not** be part of the CCU backup. The directory should be writable.

An example application is the CCU Historian. The database greatly increases the size of the CCU backup.

**Comment by jens-maus** [comment]
Welches Directory schwebt dir da vor? `/usr/local/tmp` gibt es ja schon, das wird aber mit jedem reboot automatisch gelöscht.

**Comment by mdzio** [comment]
Mein Vorschlag ist ```/usr/local/var```. Eventuell noch ```/var/local``` als symbolischen Link anbieten.
Das Verzeichnis sollte nicht bei jedem Reboot geleert werden.

**Comment by jens-maus** [comment]
`/usr/local/var`wäre vermutlich zu generell weil unter var ja mitunter auch dinge gespeichert werden für das man ein backup haben möchte.

**Comment by jens-maus** [comment]
Ich sehe gerade das es beim `tar` eine Option `--exclude-tag-under=FILE` gibt die es erlaubt ein gesamtes Verzeichnis vom backup auszunehmen wenn in dem Verzeichnis eine Datei mit speziellem Namen gefunden wird. siehe https://www.gnu.org/software/tar/manual/html_section/tar_49.html

Ich könnte mir vorstellen das auszunutzen und zu definieren das wenn z.B. eine Datei `.nobackup` gefunden wird das gesamte Verzeichnis vom Backup auszunehmen. Hinweise/Anregungen dazu? Die Frage wäre ob man dann den gesamten subtree darunter auch auslassen sollte oder nur das Verzeichnis in dem das `.nobackup` gefunden wird? Es gibt da auch noch andere solche `--exclude-tag-XXXX` Optionen.

**Comment by jens-maus** [comment]
Ich würde vmtl. dafür plädieren die Option `--exclude-tag=.nobackup` zu verwenden. Laut Dokumentation (`Do not dump the contents of the directory, but dump the directory itself and the file.`) sollte das das Verzeichnis leer lassen, aber die `.nobackup` datei mit backupen, sodass bei einem Restore dann das Verzeichnis zumindest existiert und auch diese Datei damit für das nächste Backup klar ist das das wiederum das backup nicht über das Verzeichnis laufen soll. Anmerkungen?

**Comment by jens-maus** [comment]
Habe das ganze nun erst einmal so implementiert. Nun sollte es möglich sein als Addon Entwickler ein Unterverzeichnis unter `/usr/local/addons` anzulegen und dort mit `touch .nobackup` eine leere Datei in einem Unterverzeichnis anzulegen sodass die Backup Routinen dann damit angewiesen werden das Verzeichnis (und alle Unterverzeichnisse) entsprechend zu ignorieren (jedoch die `.nobackup` datei zu behalten). Hoffe das passt zu den Wünschen :)

**Comment by mdzio** [comment]
Ja, das ist eine gute generische Lösung.

**Comment by jens-maus** [comment]
Ok, dann sollte das mit der nächsten kommenden Version nun so funktionieren.
