### ISSUE TITLE
"maximale Ventilöffnungsposition" & "Ventil in Fehlerposition" auf 0% 

### ISSUE THREAD

**Issue by whistlerofficial** [jens-maus/RaspberryMatic#1791]
### Describe the issue you are experiencing

Nach dem Update auf 3.63.8.20220330 (welches ich vor ein paar Tagen installiert hatte) ist mir nun heute folgender Fehler aufgefallen:
- Die Werte "maximale Ventilöffnungsposition" und "Ventil in Fehlerposition" stehen nun in allen bestehenden Thermostaten auf 0%
- Nach der Übertragung der Config auf ein Thermostat öffnet dieses auch das Ventil überhaupt nicht mehr
- Nach dem ändern der Werte und erneutem Übertragen geht das Ventil wieder auf, aber der Wert wird in der CCU Config weiterhin mit 0% angezeigt

### Describe the behavior you expected

Thermostate öffnen das Ventil nicht mehr

### Steps to reproduce the issue

1. Config eines Thermostats öffnen
2. Prüfen welche werte für "maximale Ventilöffnungsposition" & "Ventil in Fehlerposition" vorhanden sind
3. Konfiguration übernehmen
4. beobachten wie die Heizung nicht mehr geht ;) sehr Nachhaltig :D
...

### What is the version this bug report is based on?

3.63.8.20220330

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
/
```

**Comment by jens-maus** [comment]
Duplicate of #1784
