### ISSUE TITLE
HmIP-eTRV-2: '100%' bei 'maximale Ventilöffnungsposition' fehlt

### ISSUE THREAD

**Issue by lodex2** [jens-maus/RaspberryMatic#1793]
### Describe the issue you are experiencing

Beim Einstellen eines HmIP-eTRV-2 oder HmIP-eTRV-C fehlt in Kanal 1 unter 'maximale Ventilöffnungsposition' die (default) Einstellung '100%'. Das hat zur Folge, dass '0%' voreingestellt wird und beim Speichern der Einstellung das Ventil immer bei 0% bleibt. Der einstellbare Bereich bewegt sich zwischen 0% und 95%.

### Describe the behavior you expected

Der default Wert von 100% ist gesetzt bzw. kann ausgewählt werden.

### Steps to reproduce the issue

1. Ein HmIP-eTRV-2 oder HmIP-eTRV-C anlernen
2. Unter Einstellungen -> Geräte das Gerät konfigurieren
3. Unter den Einstellungen für Kanal 1 fehlt die Einstellung '100%' für 'maximale Ventilöffnungsposition'

### What is the version this bug report is based on?

3.63.8.20220330

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Leider nein.
```

**Comment by jens-maus** [comment]
Duplicate of #1784
