### ISSUE TITLE
login.html als Bootstrap Form

### ISSUE THREAD

**Issue by chr1stianC** [jens-maus/RaspberryMatic#1795]
### Describe the solution you'd like

Als Zusatz zu PR #1511 habe ich einen Entwurf der `login.html` basierend auf dem aktuellen Bootstrap 5.1.3 erstellt.
Screenshots des Entwurfs anbei. Die Seite ist "from scratch" neu erstellt und basiert nicht auf der aktuellen Seite.
Das Layout ist natürlich weit entfernt von "fertig".

Basisfunktionalitäten wie automatischen Ausfüllen des Benutzernames und der Umschaltung zwischen Login Form / Info Form habe ich per "vanilla" JS umgesetzt, minimales eigenes css ist ebenfalls definiert.
<img width="1280" alt="helpForm" src="https://user-images.githubusercontent.com/58345194/162017910-81a5bfed-fce2-42c9-b95e-1bfe93881dc8.png">
<img width="1278" alt="loginForm" src="https://user-images.githubusercontent.com/58345194/162017929-60d80b83-99aa-452a-9868-3132fdb55828.png">

Sollte der Entwurf auf Interesse stoßen versuche ich gerne einen PR zu erstellen. Dies wäre mein erster PR im Umgang mit github, daher kann es etwas dauern, bis er fertig ist.

### Describe alternatives you've considered

Man müsste festlegen, wie viel Neues (`css`, `js`) benötigt wird und inwieweit die aktuelle Codebasis auf das geänderte Markup umgestellt werden kann.

Hier benötige ich definitiv Hilfe, mein Verständnis der Raspberrymatic Struktur ist begrenzt.

### Is your feature request related to a problem?

#1509

**Comment by jens-maus** [comment]
Sieht erst einmal interessant aus, in der Tat. Allerdings würde ich erst einmal gerne PR #1511 finalisiert und integriert wissen bevor man sich daran machen kann gewisse Komponenten der WebUI neu zu gestalten. Auch würde darum bitten hier nicht vor Integration von PR #1511 extra ein neues Ticket dafür aufzumachen, sondern dies in das PR ticket/issue von #1511 zu integrieren und dort vorzustellen. Bitte also da weitermachen!

Und unterm Strich bleibt es ja dabei, das wir vorsichtig damit sein müssen ganze Bereiche der WebUI einfach so neu zu designen und wir das zumindest in einer gewissen halbwegs kompatiblen Art&Weise umsetzen müssten damit zukünftige Anpassungen von Seiten von eQ3 immer noch relativ einfach in neue Version integriert werden können.
