### ISSUE TITLE
HmIP-eTRV-2 Thermostat / Ventilöffnungsgrad nicht einstellbar

### ISSUE THREAD

**Issue by andesse** [jens-maus/RaspberryMatic#1797]
### Describe the issue you are experiencing

Seit dem letzten Update funktioniert irgendwas mit den HmIP-eTRV-2 Thermostaten nicht. Ich hab mich gewundert warum es in der Wohnung so kalt war und habe dann festgestellt, das alle HmIP-eTRV-2 eine „maximale Ventilöffnungsposition“ von 0% haben. Wollte dann wieder 100% einstellen, der Wert ist jedoch gar nicht vorhanden. Habe dann 95% eingestellt und dann ging es einen Tag. Als ich dann heute nochmals reingeschaut habe stand der Wert wieder auf 0%. Die Temperatur war auf 20 Grad eingestellt, die Temperatur lag bei 18,6 Grad. Habe dann wieder auf 95% eingestellt und ich hörte das Thermostat fahren. Unter Status und Bedienung lag der Ventilöffnungsgrad jedoch bei 0%, wurde also nicht korrekt angezeigt. Habe dann dort auf AUS gestellt und das Ventil fuhr zu. Guckte wieder in die Einstellung und es stand wieder auf 0%.

Da scheint es einen Fehler zu geben. 

### Describe the behavior you expected

Thermostat öffnet bei geringer Temperatur im Auto Modus das Ventil

### Steps to reproduce the issue

Wie oben beschrieben

### What is the version this bug report is based on?

3.63.8.20220330

### Which base platform are you running?

tinkerboard (ASUS Tinkerboard)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
Nein
```

**Comment by mbhomie007** [comment]
Schon repariert. 

#1784

**Comment by jens-maus** [comment]
Duplicate of #1784

**Comment by andesse** [comment]
Sorry, habe nach dem Modell gesucht, hatte es aber auf Open stehen und nicht All. Wieder was gelernt!
