### ISSUE TITLE
Zertifikat erstellen bewirkt Neustart des Webservers

### ISSUE THREAD

**Issue by MichaelHuck** [jens-maus/RaspberryMatic#1798]
### Describe the issue you are experiencing

Wenn ich im Bereich Systemsteuerung, Netzwerk, Zertifikat erstellen auf den Button "Zertifikat erstellen" klicke, dann startet der Webserver einfach neu.
Auch das Löschen eines evtl. vorhandenen Zertifikates durch den Button "Löschen" und einem anschließenden Neustart löst das Problem nicht.

### Describe the behavior you expected

Ich erwarte, dass ein Zertifikat erstellt wird, das ich dann speichern kann. So wie es in der Anleitung steht.

### Steps to reproduce the issue

1. Systemsteuerung
2.Netzwerk
3.Zertifikat erstellen
...

### What is the version this bug report is based on?

3.63.8.20220330

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Do not know.
```

**Comment by jens-maus** [comment]
> Wenn ich im Bereich Systemsteuerung, Netzwerk, Zertifikat erstellen auf den Button "Zertifikat erstellen" klicke, dann startet der Webserver einfach neu.

Das ist kein Bug, sondern ein Feature! Im Gegensatz zur reinen CCU3 Firmware generiert bei "Zertifikat erstellen" RaspberryMatic das passende selbst-signierte Zertifikat im Hintergrund selbst und installiert es für den Webserver automatisch und start diesen dann zum Abschluss neu damit das Zertifikat gleich geladen wird. Ein Download des Zertifikates und darauf folgendes Hochladen des selbigen ist bei RaspberryMatic nicht notwendig.

**Comment by MichaelHuck** [comment]
Vielen Dank für die Klarstellung. Der Beitrag sollte stehen bleiben, weil ich im Internet gesehen habe, dass sich auch andere über das Verhalten wundern.
Könnte man nicht eine kleine Meldung machen der Art "Zertifikat wurde erzeugt und installiert"? Der Neustart des Webservers ohne Meldung fühlt sich wie eine Fehlfunktion an.

**Comment by jens-maus** [comment]
> Vielen Dank für die Klarstellung. Der Beitrag sollte stehen bleiben, weil ich im Internet gesehen habe, dass sich auch andere über das Verhalten wundern.

Das hier ist kein Diskussionsforum sonder ein Bug/Issueticket system. Insofern ist das such kein Beitrag und muss/sollte nicht dauerhaft stehen bleiben. Abgehakt ist Abgehakt.

> Könnte man nicht eine kleine Meldung machen der Art "Zertifikat wurde erzeugt und installiert"? Der Neustart des Webservers ohne Meldung fühlt sich wie eine Fehlfunktion an.

Dazu kannst du gerne ein extra enhancement ticket hier aufmachen damit das ggf bearbeitet werden kann.
