### ISSUE TITLE
 ReGaHss: Error: SetVar(): SetValue() failed: m_val.ivt = 16

### ISSUE THREAD

**Issue by FUEL4EP** [jens-maus/RaspberryMatic#180]
Since an upgrade to RaspberryMatic 2.29.23.20171022 a script to detect open windows doesn't work any more.  This script was working fine for more than a year so far. In the log file the following error message is shown each time when the script is executed:

```
Oct 31 17:15:00 homematic-raspi local0.err ReGaHss: Error: SetVar(): SetValue() failed: m_val.ivt = 16 pszVar =9369$0%10511$0%10677$0%10621$0%11108$0%12351$0%16381$0%17796$0%17851$0%13143$0 [iseDOMdpVar.h:62]
```
Let me know if you need further data for debugging this.

Thanks a lot in advance.

**Comment by jens-maus** [comment]
Please provide the script

**Comment by FUEL4EP** [comment]
Here we go:

[detect_open_windows.txt](https://github.com/jens-maus/RaspberryMatic/files/1431619/detect_open_windows.txt)

Thanks for your swift action!

**Comment by jens-maus** [comment]
Can you give some details in which line of your script the error output occurs?

**Comment by FUEL4EP** [comment]
Not yet. Since there is no single step debugging mode (I am aware of), it will take time to narrow this down. Let me try ..

**Comment by FUEL4EP** [comment]
Narrowing down succeeded by deleting parts of the script until the error message disappeared:

The error is generated by line 123:
OpenWindowArr.Variable(newString);

newString is this string:

9369$0%10511$0%10677$0%10621$0%11108$0%12351$0%16381$0%17796$0%17851$0%13143$0

Hope this helps.

BR

Ewald

**Comment by jens-maus** [comment]
And what kind of string should that be? what does that mean actually?

**Comment by FUEL4EP** [comment]
The string is encoding for each window the time when it has been opened. The delimiter between the windows is a ‚%´. The script is not originated by me, but just adapted to my needs. Interesting is that the log error message is containing the value of newString. The script was working for a CCU1 and for Raspberrymatic until the last release.

**Comment by FUEL4EP** [comment]
Usually the script is invoked every 5 minutes if there is any open window.

**Comment by jens-maus** [comment]
@FUEL4EP Can you please check that your "OpenWindowArr" Systemvariable is correctly set to "Zeichenkette" and not to some other type. Perhaps also try to recreate this system variable.

**Comment by FUEL4EP** [comment]
Hello Jens,

Indeed the type of the system variable "OpenWindowArr" was wrong. Setting it to 'Zeichenkette' fixed my problem. Thanks for your great 'razor-sharp' analysis and help.

We can close this issue.

Best regards,

Ewald
