### ISSUE TITLE
Hm-IP Broll/ Hm-IP Geräte Direktverknüpfungen fehlerhaft

### ISSUE THREAD

**Issue by pitje-87** [jens-maus/RaspberryMatic#1801]
### Describe the issue you are experiencing

Hallo zusammen,

ich habe einen neuen Rollladenaktor Hm-IP BROLL gekauft und habe ihn angelernt. Soweit problemlos.

Beim Erstellen von Direktverknüpfungen wird der Vorgang wie gewohnt durchgeführt. Nach anpassen der Verknüpfung kann man mit Übernehmen die Anpassungen übernehmen, bleibt aber im Configfenster. Beim Klick auf OK, wird der Ladenscreen im Loop angezeigt, nichts geht mehr. Rückmeldung der CCU nur mit F5 möglich, dann landet man wieder auf der Startseite. 

Direktverknüpfung wird zwar angezeigt, aber der Aktor reagiert nicht darauf.

Verwendung:
Ich verwende einen Virtuellen Taster mit dem ich alle Rollläden herunterfahren bzw. hochfahren lasse. Bei allen bereits angelernten Geräten funktioniert dies problemlos, nur bei dem neu angelernten Gerät nicht.

### Describe the behavior you expected

Beim Erstellen einer Direktverknüpfung und dem Klick im Configfenster auf Ok, sollte die Meldung kommen, das die Daten übertragen worden sind und die Anzeige auf die Geräteseite umspringen.

### Steps to reproduce the issue

1. Neue Direktverknüpfung erstellen, Geräte auswählen
2. Klick auf Erstellen und Bearbeiten
3. Verknüpfung wunschgemäß editieren
4. Klick auf OK
5. Jetzt kommt der Aktualisieren Bildschirm im loop und nichts geht mehr
6. Nach Klick F5 wird die Startseite angezeigt
7. Unter Direktverknüpfungen wird die Verknüpfung angezeigt, jedoch wird diese nicht berücksichtigt/ ausgeführt.

### What is the version this bug report is based on?

3.63.8.20220330

### Which base platform are you running?

tinkerboard (ASUS Tinkerboard)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
no
```

**Comment by Baxxy13** [comment]
Was für Direktverknüpfungen werden da genau angelegt? (Screenshots)
Lässt sich das mit anderen Aktoren (z.B. PS/PSM) reproduzieren?
Ich habe keinen BROLL um das nachzustellen.

**Comment by pitje-87** [comment]
Hallo zusammen,

entschuldigt die späte Rückmeldung. Ich hoffe ihr hattet alle ein frohes Osterfest.

Anbei mein Vorgehen:
1. Suchen der passenden Verknüpfung:
![Anlegen 1](https://user-images.githubusercontent.com/36817278/164021665-3045c717-bc1e-4d65-8d56-8a21db74e331.png)
2. Hinzufügen von "Empfängern"
![Anlegen 2](https://user-images.githubusercontent.com/36817278/164021673-572c431e-397c-4239-90f5-30c6754dbc15.png)
3. Verknüpfung "erstellen und bearbeiten"
![Anlegen 3](https://user-images.githubusercontent.com/36817278/164021677-2474eb7a-3b41-4c53-902a-97cad8d10c72.png)
4. Übertragung bestätigen
![Anlegen 4](https://user-images.githubusercontent.com/36817278/164021681-665968dd-8695-429c-8ad2-e38a4e210d09.png)
5. Verknüpfung editieren (hier auf hochfahren 100%) und auf Übernehmen
![Anlegen 5](https://user-images.githubusercontent.com/36817278/164021682-97bb1460-e7ba-46f5-a4ad-d0465f43c87e.png)
6. Übertragung bestätigen
![Anlegen 6](https://user-images.githubusercontent.com/36817278/164021683-413100fc-b693-4300-ba5b-ae662cd2a1df.png)
7. Verknüpfungseditor mit ok verlassen
![Anlegen 7](https://user-images.githubusercontent.com/36817278/164021685-661fc914-0d02-4bfb-bce3-2de757de1675.png)
8. Übertragung bestätigen
![Anlegen 8](https://user-images.githubusercontent.com/36817278/164021687-1d248991-aaa5-4afa-be5d-b5ece9b5a14f.png)

PS: Ja ich Weiß ggf. hätte ich auch ab Schritt 5 gleich mit OK beenden können.

Was mich wundert, dass nur die Übertragung an den Rollladenaktor erfolgt und nicht an die CCU. Ist dass ggf. ein Problem?

Ich probiere jetzt nochmal eine komplett neue Verknüpfung über Auswahl beider Partner zu erstellen. Mal sehen ob das klappt.

**Achtung:**
Als Workaround habe ich zwischenzeitlich den Aktor aus dem Programm heraus direkt angesprochen wobei heute morgen folgendes Aufgefallen ist:
- Der Aktur wurde um 0900 mit Behanghöhe 100% angesteuert, im Gerätestatus zeigt er auch an, dass er 100% geöffnet ist, ist aber tatsächlich geschlossen...


Danke euch.
