### ISSUE TITLE
Neu angelernte HMIP Heizkörperthermostate funktionieren nicht

### ISSUE THREAD

**Issue by fgum21** [jens-maus/RaspberryMatic#1803]
### Describe the issue you are experiencing

Seit Installation der neuen SW Version
Bei den Heizkörperthermostaten funktioniert nach der Neuinstallatin die Motoransteuerung nicht.
Heizkörperthermostat HMIP-eTVR-2(Firmware 2.2.8)
Heizkörperthermostat HMIP-eTVR-E (Firmware 1.0.10)
Bereits installierte Thermostate: Funktion i.O.
 

### Describe the behavior you expected

Nach rücksetzen auf Werkseinstellungen
>Motor fährt in „Valve adapt“ Position
>LED blinkt alle 10s
>Posteingang ok
CCU3  Startseite>Status und Bedienung> Geräte – Kommunikation o.k.
auch die Kommunikation zu Wandthermostat WTH-2 mit Luftfeuchtesensor i.O.
> aber keine Motorfahrt

### Steps to reproduce the issue

1. Gerät anlernen
2. Motor fährt in „Valve adapt“ Position i.O.
3. CCU3  Startseite>Status und Bedienung> Geräte 
4. Bedienung: Auto Modus, Manu Modus bei Themperaturänderung keine Motorfahrt
5. auch im Boost Modus keine Reaktion
6. Anzeige:Ventil-Öffnungsgrad 0%

### What is the version this bug report is based on?

3.63.8.20220330

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Bei dem Funkmodul ist das originale in der Smart Home Zentrale CCU3 in Verwendung
```

### Additional information

no

**Comment by Baxxy13** [comment]
Schlägt hier vielleicht der 0% "maximale Ventilöffnungsposition" Bug der aktuellen RM zu?
Bin mir nicht sicher ob das direkt nach dem Anlernen sein kann.
Mal in die Einstellungen des eTRV gehen, den Wert auf 95% setzen und dann nochmal testen.

**Comment by jens-maus** [comment]
Duplicate of #1784
