### ISSUE TITLE
Reset HM-MOD-RPI-PCB Duty Cycle

### ISSUE THREAD

**Issue by Torben80** [jens-maus/RaspberryMatic#181]
Hallo und ein vielen Dank ersteinmal für deine ganzen Mühen und dieses riesen Projekt.
Nach langen Wartezeiten uvm. habe ich von meiner CCU2 auf Raspberrymatic gewechselt, was ich auch bis jetzt nicht bereue.

Da ich aber noch im Aufbau meiner Anlage bin und viel testen und erklären muss, und die Funktionsweise der Alarmanlage und die sich daraus ableitetenden Änderungen am StatusDisplay HM-OU16 LED ,  vorzeigen / erklären muss, komme ich derzeit gaaaaanz schnell an meinen DC.

Ich habe gelesen, dass ich das Funkmodul reseten kann, über folgendes Script:
```
#!/bin/sh 
/etc/init.d/S61rfd stop 
echo 0 > /sys/class/gpio/gpio18/value 
sleep 0.1 
echo 1 > /sys/class/gpio/gpio18/value 
sleep 2 
/etc/init.d/S61rfd start
```

Mein DC lese ich aus und lasse ihn in eine Variable schreiben, zum Testen derzeit "minütlich".

Wenn ich gerade mal so um die 20 habe und dann das Script als root ausführe, sehe ich ja auch wie er den "rfd" stopppt und auch wieder startet, aber der DC ändert sich nicht.

Hat jemand eine Idee?

RaspberryMatic 2.29.22.20170902

mfg Torben

**Comment by jens-maus** [comment]
Es ist nicht möglich (und rechtlich auch nicht legal) den DutyCycle softwaretechnisch im Funkmodul zu resetten. Dieser wird hart in der Firmware des Funkmoduls berechnet und lediglich zum auslesen zur Verfügung gestellt. Lediglich das trennen des RaspberryPi von der externen Stromquelle schaltet den Coprocessor des Funkmoduls soweit aus, dass dieser bei Wiederkehr des Stroms einen DutyCycle von 0 aufweist. Auch ein einfacher software-reset des RaspberryPi schafft hier keine Abhilfe.
