### ISSUE TITLE
HmIP-WLAN-HAP als repeater

### ISSUE THREAD

**Issue by corsac82** [jens-maus/RaspberryMatic#1814]
### Describe the solution you'd like

hallo wäre es möglich den HmIP-WLAN-HAP als repeater einzubinden ?

### Describe alternatives you've considered

hallo wäre es möglich den HmIP-WLAN-HAP als repeater einzubinden ?

### Is your feature request related to a problem?

*

**Comment by jp112sdl** [comment]
Nein das ist nicht möglich.

**Comment by jens-maus** [comment]
Genau so ist es! Der HmIP-WLAN-HAP wird von eQ3 lediglich als HAP für die homematicIP-Cloudlösung unterstützt und nicht für die Nutzung mit einer CCU (und somit auch nicht mit einer RaspberryMatic) Hierfür fehlt schichtweg die notwendige Firmware für den HmIP-WLAN-HAP die nur eQ3 liefern kann.
