### ISSUE TITLE
HmIP-FALMOT-C12 nicht mehr konfigurierbar

### ISSUE THREAD

**Issue by uepsie** [jens-maus/RaspberryMatic#1815]
### Describe the issue you are experiencing

Nach dem Update auf 3.63.8.20220330 erscheint bei dem Klick auf (Einstellungen->Geräte) die Einstellen-Schaltfläche bei der HmIP-FALMOT-C12 nur noch 
![image](https://user-images.githubusercontent.com/304272/164970113-865b6031-2b34-4fa1-87c0-ff2cd13049e5.png)

es macht keinen Unterschied, ob die Einstellungen für das gesamte Gerät oder auf Einstellungen für einzelne Kanäle geklickt wird.

### Describe the behavior you expected

Einstellungen der HmIP-FALMOT-C12

### Steps to reproduce the issue

1. Einstellungen
2. Geräte
3. HmIP-FALMOT-C12 -> Aktion/Einstellen
...

### What is the version this bug report is based on?

3.63.8.20220330

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
kein Fehler in den Logs
```

**Comment by jens-maus** [comment]
Dieses Problem wurde bereits in Commit https://github.com/jens-maus/RaspberryMatic/commit/0d68a74bee1f6af46eea2363e1cb67a3257e3d9d behoben und wird folglich im nächsten kommendem Release behoben sein.
