### ISSUE TITLE
Button Ignorieren bei Datenübertragung zu Geräten falsch beschriftet

### ISSUE THREAD

**Issue by Stus2** [jens-maus/RaspberryMatic#182]
Der Button Igorieren bei der Fehlermeldung wenn für ein Gerät die Daten nicht übertragen werden können ist falsch beschriftet. Ich kenne nur die Beschriftung Meldung Ignorieren. Bei Raspberrymatic steht dort btnDirecctDeviceLinkIgnore! Schönheitsfehler ;-)

**Comment by jens-maus** [comment]
Bitte mal den Browser Cache löschen und neu probieren.

**Comment by jens-maus** [comment]
Und bitte auch einen screenshot zeigen
