### ISSUE TITLE
Missing deviceName and other information from raspberrymatic

### ISSUE THREAD

**Issue by beowulfof** [jens-maus/RaspberryMatic#1820]
### Describe the issue you are experiencing

I've setup Node-Red to connect to raspberrymatic via node-red-contrib-ccu and since Version 3.63.9.20220330 I dont get deviceNames, room descriptions and probably some other information from raspberrymatic. Using node-red-contrib-ccu mqtt node to put everything into mqtt shows the problem like this:

```json
{"topic":"caern/hm/status//STATE_NOTWORKING","payload":"{\"val\":true,\"ts\":1651473107142,\"lc\":1651473107142,\"hm\":{\"ccu\":\"192.168.178.2\",\"iface\":\"HmIP-RF\",\"device\":\"00021A4994AA0E\",\"deviceType\":\"HMIP-PS\",\"channel\":\"00021A4994AA0E:3\",\"channelType\":\"SWITCH_VIRTUAL_RECEIVER\",\"channelIndex\":3,\"datapoint\":\"STATE_NOTWORKING\",\"datapointName\":\"HmIP-RF.00021A4994AA0E:3.STATE_NOTWORKING\",\"datapointType\":\"BOOL\",\"datapointMin\":false,\"datapointMax\":true,\"datapointDefault\":false,\"datapointControl\":\"SWITCH.STATE\",\"valuePrevious\":false,\"valueStable\":true,\"rooms\":[],\"functions\":[],\"ts\":1651473107142,\"tsPrevious\":1651473106742,\"lc\":1651473107142,\"change\":true,\"cache\":false,\"uncertain\":false,\"working\":false,\"stable\":true}}","qos":0,"retain":true,"_msgid":"d569775fa299e938"}
```
Did I miss a new setting?

### Describe the behavior you expected

Before Version 3.63.9.20220330 device names and room list were properly transmitted. With actual Version 3.63.9.20220430 it still is the same issue.

### Steps to reproduce the issue

1. used builtin update-function
2.
3.
...

### What is the version this bug report is based on?

3.63.9.20220430

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
no
```

**Comment by jens-maus** [comment]
> I've setup Node-Red to connect to raspberrymatic via node-red-contrib-ccu

Sorry, Node-Red is a third-party thing. So what makes you sure that this isn't a bug in node-red-contrib-ccu instead? IMHO this issue should first be raised in the node-red-contrib-ccu project instead.

So please elaborate a bit more here and also please make sure the screenshots are added here correctly.

**Comment by beowulfof** [comment]
Since raspberrymatic had an update, while node-red-contrib-ccu doesn't - so change is only on your side.

**Comment by jens-maus** [comment]
> Since raspberrymatic had an update, while node-red-contrib-ccu doesn't - so change is only on your side.

This alone is a very loose observation or rational for reporting/verifying an issue. In fact, it is up to you to demonstrate the issue with enough technical details that actually convince the maintainers (e.g. me) that there is actually an issue. All you show here is a payload output on the current version and nothing more. For a proper investigation more information and technical details are required and as I don't use node-red myself it would be even more helpful if you would investigate this issue more deeply yourself.

**Comment by beowulfof** [comment]
Ah ok, so non-technical users are not allowed to raise an issue? Symptom is simple the previously shown field "deviceName" is missing since this update. Shouldn't be to hard to check - merely seconds if you know your code. And of course I look for error sources first, where the change happens.

**Comment by jens-maus** [comment]
> Ah ok, so non-technical users are not allowed to raise an issue?

You are of course allowed to report your observations, but you should expect that your raised issues might be simply rejected+closed simply because you are not providing enough detailed information or speaking not enough technical language here. That's the deal with using a development platform like GitHub for reporting issues. And if you cannot provide more technical details because you are lacking the technical knowhow, go to a discussion fora like homematic-forum.de or GitHub discussions here and hope that someone is going to help you who is also using node-red-contrib-ccu and is perhaps having the same issue.

But simply don't expect the developers to spent their precious time in first having to install a third-party application like Node-Red to reproduce your rational here. That's not how development goes: You have to provide enough technical details to convince the developers/maintainers that there IS actually an issue and not simply saying "there is something going wrong since the last version and it must be your piece of software simply because I only changed that one"... Sorry, but this is not enough, I am afraid.

**Comment by Baxxy13** [comment]
Da ich gerade etwas am Testen bin dachte ich das hier hätte eventuell was mit der Umlaut-Problematik zu tun.
Meine node-red-contrib-ccu ist davon aber unbeeindruckt und gibt auch mit aktueller RM (Nightly 3.63.9.20220502) alle Informationen raus (soweit ich sehen kann). Leider auch die krummen Umlaute.

Beispielausgabe: 

```json
{"ccu":"192.168.1.18","iface":"BidCos-RF","device":"OEQ1050013","deviceName":"HM-LC-Sw4-Ba-PCB OEQ1050013 -Ã¤Ã¶Ã¼Ã-","deviceType":"HM-LC-Sw4-Ba-PCB","channel":"OEQ1050013:1","channelName":"HM-LC-Sw4-Ba-PCB OEQ1050013:1 - KanÃ¼l-1","channelType":"SWITCH","channelIndex":1,"datapoint":"STATE","datapointName":"BidCos-RF.OEQ1050013:1.STATE","datapointType":"BOOL","datapointMin":false,"datapointMax":true,"datapointDefault":false,"datapointControl":"SWITCH.STATE","valuePrevious":true,"valueStable":false,"rooms":["Baxxys Räume"],"room":"Baxxys Räume","functions":["Baxxys Gewärk"],"function":"Baxxys Gewärk","ts":1651512952388,"tsPrevious":1651508937000,"lc":1651512952388,"change":true,"cache":false,"uncertain":false,"working":false,"stable":true}
```
