### ISSUE TITLE
Weiterhin Umlaut-Probleme in der WebUI

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1821]
### Describe the issue you are experiencing

Bei testen des heutigen Nightly's 3.63.9.20220502 bin ich wieder auf die Umlaut-Problematik gestoßen.

### Describe the behavior you expected

Korrekte Umlaut-Darstellung in der WebUI

### Steps to reproduce the issue

1. ein Gerät / Gerätekanal über "Einstellungen > Geräte" mit Umlauten (um)benennen
2. Ansicht in "Einstellungen > Geräte" ist dann korrekt (Umlaute werden korrekt dargestellt)
3. das Gerät / Gerätekanal in "Status und Bedienung > Geräte" ansehen 
4. Ansicht in "Status und Bedienung > Geräte" zeigt dann die Umlaut-Problematik

### What is the version this bug report is based on?

3.63.9.20220502 Nightly

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
-
```

### Additional information

"Einstellungen > Geräte"
![RM_Umlaute_Einst_Geräte](https://user-images.githubusercontent.com/54898249/166295668-1710c6d4-09c0-4c65-92c4-83fb81a5f7b3.JPG)

"Status und Bedienung > Geräte"
![RM_Umlaute_SuB_Geräte](https://user-images.githubusercontent.com/54898249/166295767-e8839ceb-4e65-4b91-a191-a2050a6fde45.JPG)

Frisch angelegte Räume und Gewerke (mit Umlauten) werden korrekt angezeigt.

**Comment by jens-maus** [comment]
Danke für den Hinweis. Kannst du dich bitte noch mehr durch die WebUI "fräsen" und an verschiedensten Stellen testen wo dir noch solche Umlaut-Probleme in der WebUI auffallen? Nach meinen kurzen Tests sollte das hoffentlich das letzte derartige Problem sein.

**Comment by jens-maus** [comment]
Nach weiteren kurzen Tests sieht es wohl so aus, das es daran liegt, das wenn man momentan den Namen eines Gerätes/Kanals via WebUI in dem bekannten Popup-Fenster unter "Einstellungen -> Geräte" editiert irgendwie UTF-8 Zeich am Schluss in `.Name()` des Rega-Objektes landen. Sehe kann man das z.B. mit folgenden angelehntem Skript:

```c++
object obj=dom.GetObject(1645);
WriteLine(obj.Name());
WriteLine(obj.Name().UriEncode());

object obj=dom.GetObject("HM-RCV-50 BidCoS-RFö");
WriteLine(obj.Name());
```

dies wirft die folgende Ausgabe:

```
HM-RCV-50 BidCoS-RFö
HM%2DRCV%2D50%20BidCoS%2DRF%C3%B6
null
```

D.h. das Objekt 1645 (welches normal `HM-RCV-50 BidCoS-RF` heisst) wird nach hinzufügen eine `ö` zwar bei "Skript testen" noch mit vermeintlich richtigem Namen ausgegeben, aber das `UriEncode()` verrät das am schluss ein `%C3%B6` für das `ö` genommen wurde und daher das nächste `dom.GetObject()` mit dem ö im Namen aber nicht zum gewünschten Ergebnis führt. Setzt man hingegen den Namen via ReGa-Skripting einfach neu (z.B. `obj.Name('HM-RCV-50 BidCoS-RFö')`  funktioniert das ganze und am schluss gibt er dann auch statt dem `%C3%B6` ein `%F6` aus welches eben korrekterweise einem `ö` in Latin1 (ISO-8859-1) entspricht.

Nun wäre eben die Frage an welchen anderen Stellen passiert aktuell ähnliches/gleiches? D.h. wenn man via WebUI z.B. den Namen einer Systemvariablen anpasst scheint das problemlos zu gehen und es landet kein Umlaut als UTF-8 in `.Name()` des ReGa objektes dieser Systemvariablen. Nun wäre es eben gut wenn jemand das mal ausführlich durchtesten könnte um ggf. noch andere Stellen zu finden wo am schluss fälschlicherweise Umlaute in ReGa landen die da eigentlich laut definition nicht hingehören weil ReGa und damit auch die WebUI eigentlich nur für ISO-8859-1 gemacht ist.

**Comment by jens-maus** [comment]
So, I denke ich hab den root-cause bzw. unterschied zur Vorversion gefunden und "repariert" welcher für das hier genannte Problem verantwortlich ist. D.h. mit dem nächsten nightly snapshot morgen sollte dieses Problem hier hoffentlich beseitigt sein.

Wichtig wäre natürlich aber weiterhin umfangreiche Tests an den verschiedensten Stellen in der WebUI zu tätigen wo man beliebigen Text eingeben kann um zu prüfen das am Schluss dann hoffentlich auch Umlaute korrekt kodiert in den ReGa Strukturen - aber auch via externer APIs wie JSON rpc api, XMLRPC, etc. - ausgegeben werden. Wäre also schön du könntest solche umfangreichen Tests vielleicht in nächster Zeit machen @Baxxy13

**Comment by Baxxy13** [comment]
Sehr gut!
Versprechen kann ich bezüglich Tests nichts... 
Aber da ich an einem Testsystem gleich 3 externe Steuerungen (ioBroker, NodeRed und HA) angedockt habe, werde ich ein wachsames Auge auf die Thematik haben und natürlich die WebUI bissel malträtieren.

**Comment by MichaelN0815** [comment]
Ich habe die ova Version der 3.63.9.20220513 in meiner VM (ohne Funkmodul) getestet:
Systemvariablen - Namen und Inhalt editiert, über WebUI und SDV -> OK
Programme - Namen und Beschreibung editiert, über WebUI und SDV -> OK
Gerätenamen - aufgrund der Beschränkung wg. fehlendem Funkmodul nur CuxD Devides - Namen und Kanäle editiert, über WebUI und SDV -> OK

Sowohl Status als auch Anzeige auf der Startseite getestet: alte und neue Inhalt mit Umlauten werden korrekt angezeigt. 
Nur DV's konnte ich nicht testen.
