### ISSUE TITLE
HMIP-RFUSB: 2.8.6=>4.4.16, ERROR (2.8.6 != 4.4.16)

### ISSUE THREAD

**Issue by heitec11** [jens-maus/RaspberryMatic#1823]
### Describe the issue you are experiencing

```
# USB HM/IP TRX Adapter Configuration
Adapter.1.Type=HMIP_CCU2
Adapter.1.Port=/dev/mmd_hmip
```

```
root@RaspberryMatic:~# /opt/java-azul/bin/java -jar /opt/HmIP/hmip-copro-update.jar -p /dev/mmd_hmip -f /firmware/HmIP-RFUSB/hmip_coprocessor_update-2.8.6.eq3 -o
[INFO] Homematic IP coprocessor update tool V1.0.10
[ERROR] Error while trying to open serial port: Exception while trying to open serial port. Check configured port '/dev/mmd_hmip'
[INFO] Exiting update tool.
```

### Describe the behavior you expected

System check

### Steps to reproduce the issue

1.
2.
3.
...

### What is the version this bug report is based on?

3.63.9.20220430

### Which base platform are you running?

rpi2 (RaspberryPi2)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Identifying Homematic RF-Hardware: ........HmRF: HM-MOD-RPI-PCB/GPIO@3f201000.serial, HmIP: HM-MOD-RPI-PCB/GPIO@3f201000.serial, OK
Updating Homematic RF-Hardware: HM-MOD-RPI-PCB: 2.8.6, not necessary, OK; HMIP-RFUSB: 2.8.6=>4.4.16, ERROR (2.8.6 != 4.4.16)
```

**Comment by jens-maus** [comment]
> Identifying Homematic RF-Hardware: ........HmRF: HM-MOD-RPI-PCB/GPIO@3f201000.serial, HmIP: HM-MOD-RPI-PCB/GPIO@3f201000.serial, OK
> Updating Homematic RF-Hardware: HM-MOD-RPI-PCB: 2.8.6, not necessary, OK; HMIP-RFUSB: 2.8.6=>4.4.16, ERROR (2.8.6 != 4.4.16)

This output reads like you have two Homematic RF modules connected to your rpi2 system, one HM-MOD-RPI-PCB and one HMIP-RFUSB. Is this correct? And if yes, why?

**Comment by jens-maus** [comment]
Das wird nicht gehen! Du darfst nur eins der beiden Funkmodule verwenden. Und weil du ein HAP nutzen willst wirst du auf das HmIP-RFUSB wechseln müssen und das GPIO Funkmodul gänzlich abstecken.

**Comment by jens-maus** [comment]
Ja, inzwischen trifft das nicht mehr zu.

**Comment by heitec11** [comment]
Schade,
das war die Grundlage den HmIP-RFUSB zu erwerben, da ein HAP nicht alleine läuft.

Trotz alle dem ist aber der Punkt, dass das Update auf 4.4.16 nicht funktioniert geblieben, oder.

**Comment by jens-maus** [comment]
Du scheinst nicht zu verstehen: der RFUSB kann alles und viel mehr als das alte RPI-PCB. Also steck es vom GPIO ab und nutze nur das RFUSB und schon wird das firmware update auch funktionieren. Aber das hier ist kein Diskussionsforum sondern ein bug/issue tracker. Also bitte das in ein Forum verlagern und dich dort weiter informieren udn weiterdiskutieren.
