### ISSUE TITLE
Email nicht mehr möglich; TCL update notwendig

### ISSUE THREAD

**Issue by heitec11** [jens-maus/RaspberryMatic#1824]
### Describe the issue you are experiencing

```
string stdout;
string stderr;
system.Exec("/etc/config/addons/email/email 01",&stdout,&stderr);
WriteLine("FEHLER:\n "#stderr);
WriteLine("AUSGABE:\n"#stdout);
```

FEHLER:
```
 application-specific initialization failed: Can't find a usable init.tcl in the following directories: 
    /usr/lib/tcl8.6 /lib/tcl8.6 /lib/tcl8.6 /library /library /tcl8.6.9/library /tcl8.6.9/library

/usr/lib/tcl8.6/init.tcl: version conflict for package "Tcl": have 8.6.9, need exactly 8.6.12
version conflict for package "Tcl": have 8.6.9, need exactly 8.6.12
    while executing
"package require -exact Tcl 8.6.12"
    (file "/usr/lib/tcl8.6/init.tcl" line 19)
    invoked from within
"source /usr/lib/tcl8.6/init.tcl"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list source $tclfile]"
```

This probably means that Tcl wasn't installed properly.

```
can't find package base64
    while executing
"package require base64"
    (file "/etc/config/addons/email/email" line 10)
```

AUSGABE:

### Describe the behavior you expected

```
find / -iname *init.tcl*

/www/api/methods/interface/init.tcl
/usr/lib/tcl8.6/init.tcl
/usr/local/addons/hm-tools/lib/tcl8.6/init.tcl
```

### Steps to reproduce the issue

1. missing Email
2.
3.
...

### What is the version this bug report is based on?

3.63.9.20220430

### Which base platform are you running?

rpi2 (RaspberryPi2)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

Wenn die Datei /usr/lib/tcl8.6/init.tcl
angepasst wird auf "package require -exact Tcl 8.6.9"
funktionieren die Mail wieder.

**Comment by heitec11** [comment]
Wenn die Datei /usr/lib/tcl8.6/init.tcl
angepasst wird auf "package require -exact Tcl 8.6.9"
funktionieren die Mail wieder.
Natürlich  kurzzeitig mit Änderung des Read-only file systems. 
Allerdings ist dann kein Zugriff auf WebUI möglich.
Die Mails vermisse ich sehr wahrscheinlich seit 3.63.8.20220330.

**Comment by jens-maus** [comment]
> ### Describe the behavior you expected
> ```
> find / -iname *init.tcl*
> 
> /www/api/methods/interface/init.tcl
> /usr/lib/tcl8.6/init.tcl
> /usr/local/addons/hm-tools/lib/tcl8.6/init.tcl
> ```

Tut mir leid, aber für mich sieht das nach einer Inkompatibilität zwischen dem `hm-tools` Addon und aktuellen RaspberryMatic Versionen aus die nun auch mit tcl 8.6.x ausgeliefert werden.

Ich bin mir relativ sicher, das das Problem verschwinden wird wenn man `hm-tools` einfach deinstalliert.

Insofern ist dies kein RaspberryMatic Problem, sondern ein Problem mit dem `hm-tools` Addon welches nun nicht mehr mit aktuellen RaspberryMatic Versionen kompatibel zu sein scheint.

**Comment by heitec11** [comment]
@ jens-maus: Habe  hm-tools einfach deinstalliert. Und nun werden Mails wieder versendet.
Danke für den Tip.

@ Baxxy13: der Button Testmail funktioniert interessanter weise. Aber nicht der auf der Hilfeseite von Mail-Addon angegebene Versuch per Script

**Comment by jens-maus** [comment]
> @jens-maus : Habe hm-tools einfach deinstalliert. Und nun werden Mails wieder versendet.
> Danke für den Tip. 👍

danke würde ich dich bitte im hm-tools projekt für @fhetty diesbzgl. noch ein issue ticket anzulegen damit er die expect unterstützung an die gegebenheiten neuerer RaspberryMatic Versionen anpassen kann.

Auf jedenfall ist das dann kein Bug/Issue für RaspberryMatic selbst. Insofern mache ich hier also nun zu.

**Comment by Baxxy13** [comment]
> Aber nicht der auf der Hilfeseite von Mail-Addon angegebene Versuch per Script (wie im wirklichen Leben zu verwenden :-) )

Ich habe es per Script gemacht, genauso wie du es oben aufgezeigt hattest. (Das ging / geht noch problemlos) 
Habe aber keinen Pi2 benutzt. Es liegt also vielleicht an der Systemarchitektur oder am Nightly.

Man kann sich ja die hm-tools auch selbst "zusammenstellen". 
Das tcl-Zeugs wird m.E. nur installiert wenn man expect mit drin hat. 
Ich nutze nur htop, nano und iostat. (für den Test aber das gesamte Paket)
3 Tools die gerne bei RM per default dabei sein dürften.  ;-)

**Comment by heitec11** [comment]
#Ich habe es per Script gemacht, genauso wie du es oben aufgezeigt hattest. (Das ging / geht noch problemlos)
Habe aber keinen Pi2 benutzt. Es liegt also vielleicht an der Systemarchitektur oder am Nightly.

Dann verstehe ich es auch nicht. Noch läuft der Pi2, aber eine Pi4 wollte ich nicht verwenden und einen Pi3 habe ich gerade nicht greifbar.

Danke für die Rückmeldungen.
