### ISSUE TITLE
Umlaute werden nicht korrekt angezeigt unter "Direkte Verknüpfungen"

### ISSUE THREAD

**Issue by mbhomie007** [jens-maus/RaspberryMatic#1825]
### Describe the issue you are experiencing

Umlaute werden nicht korrekt angezeigt seit Nightly Testversion 3.63.9.20220505.

### Describe the behavior you expected

Umlaute werden korrekt übersetzt.

### Steps to reproduce the issue

Klick auf "Direkte Verknüpfungen"
Klick auf "Programme"
Klick auf "Programme bearbeiten"

### What is the version this bug report is based on?

Nightly Testversion 3.63.9.20220505

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
-
```

### Additional information

![image](https://user-images.githubusercontent.com/64688879/166876030-57d94c7b-e818-4c26-81c7-9b5fc1b44f97.png)

![image](https://user-images.githubusercontent.com/64688879/166876098-f911f9e1-9c62-41c0-a2cd-6e5ce8f68c67.png)

![image](https://user-images.githubusercontent.com/64688879/166876146-a9f818f1-7ecf-4949-bf7c-768d83787add.png)

![image](https://user-images.githubusercontent.com/64688879/166876241-1e6b2876-2db6-4ac9-88dd-7b81910d2de9.png)

**Comment by mbhomie007** [comment]
@jens-maus @Baxxy13 #1821 Vielleicht mit dieser Anpassung zu tun?

Mit der Stable 3.63.9.20220430 wurde dort noch alles richtig übersetzt.

**Comment by mbhomie007** [comment]
Und dieser Eintrag ist mir noch im LOG aufgefallen, kann ich aber nicht genau zuordnen:

`May  5 09:07:00 Homematic-CCU cron.err crond[1231]: user root: parse error at 7`

**Comment by Baxxy13** [comment]
Aargh... hört das denn nie auf?
Genau an die Stelle hatte ich beim Testen nicht geguckt, sehe es aber jetzt bei mir auch.
Hier mal bei Schritt 1 für eine neue Verknüpfung:
![RM-DV-Umlaut-Probleme](https://user-images.githubusercontent.com/54898249/166878181-0b88c44e-b8b8-434e-92a5-274d5ae7296f.JPG)
Der Gerätename selbst, sowie Kanal:1 und :2 enthalten Umlaute. Diese werden in "Status und Bedienung > Geräte" sowie in "Einstellungen > Geräte" korrekt dargestellt.

Den parse error habe ich auch, gehört aber nicht hier rein. Probleme nicht mischen!

**Comment by Baxxy13** [comment]
Die letzten Anpassungen waren ja gestern drin. (3.63.9.20220504) 
Damit hatte ich speziell die Benamung der Geräte/Kanäle getestet und auch geprüft was ioBroker/NodeRed usw. dazu sagen.
Da konnte ich erstmal keine Probleme mehr entdecken. 

In die DV's hatte ich nicht reingeschaut, da das ja eigentlich schon gefixed war.
Aktuell bin ich auf dem heutigen Nightly (3.63.9.20220505) und es zeigt sich obiges Bild.
Ich habe nun mal die ersten beiden DV's gelöscht, Gerät und Kanäle nochmal neu umbenannt, dann die DV's neu angelegt und rebootet. Sieht nun so aus.
![RM-DV-Umlaut-Probleme_2](https://user-images.githubusercontent.com/54898249/166941090-38c9029a-ba37-434d-ae7e-0e0cf155f30b.JPG)
Sender und Empfänger werden korrekt angezeigt, die Beschreibung dagegen nicht. Der Text aus der Beschreibung entspricht dem der Kanalauswahl.
![RM-DV-Umlaut-Probleme_3](https://user-images.githubusercontent.com/54898249/166941724-c6c03c5a-4fce-438f-9f8e-b00106d7ee36.JPG)

**Comment by Baxxy13** [comment]
Nach Downgrade auf Nightly (3.63.9.20220502) sieht auf den ersten Blick alles gut aus:
![RM-DV-Umlaut-Probleme_4](https://user-images.githubusercontent.com/54898249/166944337-03a821e6-337d-4d0a-9ca3-c36d7d8c958a.JPG)
Aber legt man eine neue DV an...
![RM-DV-Umlaut-Probleme_5](https://user-images.githubusercontent.com/54898249/166944402-4d556fcb-5e35-4a11-a0fb-5771b70dfb3e.JPG)

**Comment by Baxxy13** [comment]
Seit der Änderung mit Nightly 3.63.9.20220504 werden Umlaute auch über das XML-API-AddOn falsch dargestellt:

Vor 3.63.9.20220504:
```xml
<device name="HM-LC-Sw4-Ba-PCB OEQ1050013 -Gerät-" address="OEQ1050013" ise_id="1419" interface="BidCos-RF" device_type="HM-LC-Sw4-Ba-PCB" ready_config="true">
<channel name="HM-LC-Sw4-Ba-PCB OEQ1050013:1 -Kanal-1-ö" type="26" address="OEQ1050013:1" ise_id="1452" direction="RECEIVER" parent_device="1419" index="1" group_partner="" aes_available="true" transmission_mode="DEFAULT" visible="true" ready_config="true" operate="true"/>
<channel name="HM-LC-Sw4-Ba-PCB OEQ1050013:2 - Kanüül-2" type="26" address="OEQ1050013:2" ise_id="1458" direction="RECEIVER" parent_device="1419" index="2" group_partner="" aes_available="true" transmission_mode="DEFAULT" visible="true" ready_config="true" operate="true"/>
<channel name="HM-LC-Sw4-Ba-PCB OEQ1050013:3 -Kanäl-3-" type="26" address="OEQ1050013:3" ise_id="1464" direction="RECEIVER" parent_device="1419" index="3" group_partner="" aes_available="true" transmission_mode="DEFAULT" visible="true" ready_config="true" operate="true"/>
<channel name="HM-LC-Sw4-Ba-PCB OEQ1050013:4" type="26" address="OEQ1050013:4" ise_id="1470" direction="RECEIVER" parent_device="1419" index="4" group_partner="" aes_available="true" transmission_mode="DEFAULT" visible="true" ready_config="true" operate="true"/>
</device>
```

Ab 3.63.9.20220504:
```xml
<device name="HM-LC-Sw4-Ba-PCB OEQ1050013 -GerÃ¤t-" address="OEQ1050013" ise_id="1419" interface="BidCos-RF" device_type="HM-LC-Sw4-Ba-PCB" ready_config="true">
<channel name="HM-LC-Sw4-Ba-PCB OEQ1050013:1 -Kanal-1-Ã¶" type="26" address="OEQ1050013:1" ise_id="1452" direction="RECEIVER" parent_device="1419" index="1" group_partner="" aes_available="true" transmission_mode="DEFAULT" visible="true" ready_config="true" operate="true"/>
<channel name="HM-LC-Sw4-Ba-PCB OEQ1050013:2 - KanÃ¼Ã¼l-2" type="26" address="OEQ1050013:2" ise_id="1458" direction="RECEIVER" parent_device="1419" index="2" group_partner="" aes_available="true" transmission_mode="DEFAULT" visible="true" ready_config="true" operate="true"/>
<channel name="HM-LC-Sw4-Ba-PCB OEQ1050013:3 -KanÃ¤l-3-" type="26" address="OEQ1050013:3" ise_id="1464" direction="RECEIVER" parent_device="1419" index="3" group_partner="" aes_available="true" transmission_mode="DEFAULT" visible="true" ready_config="true" operate="true"/>
<channel name="HM-LC-Sw4-Ba-PCB OEQ1050013:4" type="26" address="OEQ1050013:4" ise_id="1470" direction="RECEIVER" parent_device="1419" index="4" group_partner="" aes_available="true" transmission_mode="DEFAULT" visible="true" ready_config="true" operate="true"/>
</device>
```

Ändere ich beim AddOn z.B. in der `/usr/local/etc/config/addons/www/xmlapi/devicelist.cgi`
die Zeile:
```xml
<?xml version="1.0" encoding="ISO-8859-1" ?><deviceList>}
```
in:
```xml
<?xml version="1.0" encoding="UTF-8" ?><deviceList>}
```
dann werden die Umlaute korrekt dargestellt.

**Comment by jens-maus** [comment]
Nachdem ich mir das ganze rund um dieses ärgerliche charset encoding Problem nochmal genauer angeschaut habe, habe ich nun wie in https://github.com/jens-maus/RaspberryMatic/commit/e2e472f080d2a3c104cf0b03ae986d0b4d4637b2 zu sehen mehr oder weniger eine Revert zum Stand von 3.63.8.20220330 vorgenommen.

In Tests konnte ich kontrollieren, dass mit diesen Änderungen alle WebUI eigenen Kodierungsprobleme beseitigt sein sollten - es jedoch bei gewissen externen Addons (z.B. hm_pdetect) damit wie damals schon aufgezeigt noch gewisse Kodierungsproblem gibt die meines momentanen Erachtens jedoch in diesen Addons beseitigt gehören. In der WebUI selbst habe ich aber mit diesen Änderungen nun keine Kodierungsprobleme mehr feststellen können. Ich würde jedoch darum bitten nun das Ganze nochmal genauer zu testen und sämtliche Kombinationen und Umlauttexteingaben an den verschiedensten Stellen der WebUI vorzunehmen und dann ggf. hier darüber zu berichten.

Bitte also mit dem nächsten nightly snapshot nochmal alles gründlich durchtesten und hierbei auch externe Addons/Applikationen nicht aussparen.

**Comment by jens-maus** [comment]
> @jens-maus @Baxxy13 
> 
> 
> Ich habe nun ein Update von der Testversion 3.63.9.20220503-1fc2d11-rpi3 auf die heutige Testversion RaspberryMatic-3.63.9.20220513-d87db4-rpi3 gemacht.
> 
> Leider muss ich feststellen das die Umlaute immer noch nicht unter "Direkte Verknüpfungen" richtig angezeigt werden.

Das passiert nur wenn du diese mit eine der Vorversionen angelegt/modifiziert hattest. Leg die komplett frisch an bzw mach nen werksreset und es sollte gehen. Darf man halt nicht editiert/angelegt haben mit einer der kaputten snapshots zwischendrin.

**Comment by mbhomie007** [comment]
> bzw mach nen werksreset und es sollte gehen. Darf man halt nicht editiert/angelegt haben mit einer der kaputten snapshots zwischendrin.

Das heißt ein Werksreset mit der heutigen Testversion machen und dann das Backup von heute wieder einspielen??

Die DV sind schon viel älter... Wäre auf jeden fall mühselig alle manuell zu bearbeiten.

**Comment by Baxxy13** [comment]
Ob Werksreset + Backup einspielen was bringt? 
Da strings liegen doch (möglicherweise) falsch codiert in der homematic.regadom (die ja mit dem Backup wiederhergestellt wird).
Ich habe auch ein bisschen den Überblick verloren was wann wie und wo.  
Mein Live System ist auch noch auf 3.61.7.20220226 also völlig unberührt von irgendwelchen Umlaut-Problemen.
Bei den Testsystemen ist mir die Problematik eigentlich egal, da kommen und gehen die DV's. 

Ich würde mir entweder die Mühe machen und alles händisch korrigieren oder es einfach ignorieren.

**Comment by mbhomie007** [comment]
@Baxxy13 hatte Recht, nach einem Werksreset und dann Backup einspielen, sind die Umlautprobleme noch zu sehen.
Habe nun alle DVs manuell editiert und die Umlaute wieder korrigiert
Was für eine nervige Arbeit, aber mit sowas muss man eben rechnen, da es eine Testversion ist....

Vielen Dank für euren unermüdlichen Einsatz!! 🥇
