### ISSUE TITLE
Verlust individueller Namen für Räume, Gewerke, Variablen

### ISSUE THREAD

**Issue by stefanfejfar** [jens-maus/RaspberryMatic#183]
Nach dem Anlernen des HmIP-FSM16 (FW 1.2.4) verlor der RM (2.29.23.20171022) alle individuell vergebenen Namen bei Räumen, Gewerken und Variablen und setzt hierfür die Standardwerte oder bspw. ${funcLight 1}. Im Fall der Standard Variable "Anwesenheit", die ich zum Prüfen des CCU-Status verwende (und auch so heißt), bekommt diese wieder den Namen Anwesenheit. Zudem gibt es eine oder mehrere Variablen namens "Alarmzone 1". Die beschriebene Problematik konnte ich mehrfach reproduzieren.
Obwohl die Gewerke und Räume in der WebUI anders heißen, (Gewerk "Homekit" = "Verschluss") kann bspw. Homebridge alle Geräte, Programme und Variablen nach wie vor auslesen und ansteuern - bis zum Neustart des Services.

<img width="654" alt="bildschirmfoto 2017-11-02 um 20 27 24" src="https://user-images.githubusercontent.com/33330249/32346410-95392212-c00d-11e7-8ab6-6b276fd62aa7.png">

**Comment by jens-maus** [comment]
Duplicate of #199
