### ISSUE TITLE
Zeitverzögerung innerhalb eines Programmes lässt sich nicht einstellen

### ISSUE THREAD

**Issue by pitje-87** [jens-maus/RaspberryMatic#1832]
### Describe the issue you are experiencing

Beim Einstellen einer Zeitverzögerten Aktion werden Zeiteinheit und Wert nicht angenommen.

### Describe the behavior you expected

Gewählte Zeiteinheiten und Werte sollen angenommen werden.

### Steps to reproduce the issue

1. Neues Programm erstellen
2. Wenn Bereich ausfüllen
3. Dann bereich ausfüllen, Verzögerung einstellen und Versuchen die Werte/ Einheiten zu ändern.
...

https://user-images.githubusercontent.com/36817278/167478239-99f057a5-f026-49bc-b08f-2c7733d644da.mp4

### What is the version this bug report is based on?

3.63.9.20220430

### Which base platform are you running?

tinkerboard (ASUS Tinkerboard)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
no
```

### Additional information
Getestet mit Firefox 100.0 64 Bit und Brave V1.38.111

**Comment by Baxxy13** [comment]
Hmm, gerade mal auf die CCU3 3.63.8 geguckt. 
Selbes Verhalten und an sich nicht inkorrekt. 
Das maximale Delay ist 86399s, also 23h / 59m / 59s.
Kann aber nicht sagen ob das schon immer so war.

**Comment by MichaelN0815** [comment]
Unter RM 3.61.7.20220115 identisches Verhalten. Aber dies ist IMHO auch korrekt. 
@pitje-87 was willst Du denn damit demonstrieren? Das unplausible Eingaben nicht angenommen werden? Welche plausible Eingabe wird denn zurück gewiesen?

**Comment by pitje-87** [comment]
Hallo zusammen,

@MichaelN0815: scheint als hättest du die Logik meines Tests nicht verstanden. Anbei für dich die schriftliche Fassung:

1. Zunächst habe ich gezeigt, das bei Auswahl der Zeiteinheit die gewünschte Auswahl nicht angenommen wird. Das erkennst du daran, dass nach einem Klick auf "Minuten" die Einheit für einen Bruchteil wechselt und dann wieder auf "Sekunden" zurück fällt. Der Vollständigkeithalber auch für "Stunden" dargestellt.
2. Anschließend habe ich getestet, ob die automatische Umrechnung funktioniert. Dazu habe ich einen Wert von 600 Sekunden eingegeben, was korrekterweise in 10 Minuten umgerechner wird.
3. Der nachfolgende Test für die Umrechnung von Minuten in Stunden durch Eingabe von 3600 Minuten (entspricht 60 Stunden) hat leider nicht funktioniert.
4. Anschließend habe ich iterativ versucht, den Fehler einzugrenzen, was @Baxxy13 noch perfektioniert hat und das Limit ganz genau herausgefunden hat.

Letztendlich spielt es keine Rolle, welchen Werte ich eingebe. Ich würde gerne eine Verzögerung von 48 Stunden eingeben, was nicht geht. Das Feld ist ein Eingabefeld bzw. Dropdown, somit sollte es alles annehmen was ich eingebe. Sei es 10 Sekunden, 50 Minuten oder 60 Stunden. Fakt ist, dass es sich hierbei um einen Bug handelt (und nichts persönliches ist...)

@Baxxy13: Danke für deine Konkretisierung. Vielleicht hilft es @jens-maus.

LG

**Comment by Baxxy13** [comment]
Nunja, genau genommen ist die Eingabe der Verzögerung korrekt.
Man muss eben wissen was man eingeben "darf".

Das wären:
1 - 86399 Sekunden
oder
1 - 59 Minuten
oder
1 - 23 Stunden

Die Limitierung auf 23:59:59 scheint es schon immer zu geben. Zumindest mein Test mit einer 2 Jahre alten RM zeigte das gleiche Ergebnis.

Das kommt so aus der CCUx Firmware und ist m.E. nicht als Bug anzusehen. 
Ob sich das innerhalb RaspberryMatic "optimieren" ließe kann ich nicht sagen. 

Wenn du etwas mehr als 23:59:59 verzögert ausführen lassen willst, wirst du aktuell einen CUxD-Timer bemühen müssen.
Ich konnte zwar im Handbuch keine Angabe zur maximalen Timerzeit finden, 48h gehen aber definitiv.

**Comment by MichaelN0815** [comment]
It's not a bug, it's a feature.

Es gibt ein Limit auf weniger als 24 Stunden. Das hab es IMHO schon "immer".

**Comment by jp112sdl** [comment]
Die Begrenzung steht nicht mal im offiziellen WebUI Handbuch. 🙂 

Man könnte auch einen Hinweis einblenden, wenn die Grenze überschritten wird.
In der `/www/webui/webui.js` in der Methode `SetValueParam` der Klasse `ise.SingleDestination` hinzufügen:
```
if (parseInt(value.split(':')[0]) > 23) alert( 'Hoechstdauer fuer Verzoegerung maximal 23:59:59' );
```

Gibt dann ein Standard-Alert-Popup des Browsers:

![grafik](https://user-images.githubusercontent.com/18190139/167790356-9c0735d2-e0ba-4081-be96-6c44412bec98.png)

**Comment by Baxxy13** [comment]
Ich hatte gestern auch noch recherchiert ob irgendwo eine maximale Verzögerungsdauer angegeben ist. Wurde aber nicht fündig.
Die Idee mit dem Hinweis PopUp ist sehr gut.

**Comment by hugo18192** [comment]
> ### Describe the issue you are experiencing
> Beim Einstellen einer Zeitverzögerten Aktion werden Zeiteinheit und Wert nicht angenommen.
> 
> ### Describe the behavior you expected
> Gewählte Zeiteinheiten und Werte sollen angenommen werden.
> 
> ### Steps to reproduce the issue
> 1. Neues Programm erstellen
> 2. Wenn Bereich ausfüllen
> 3. Dann bereich ausfüllen, Verzögerung einstellen und Versuchen die Werte/ Einheiten zu ändern.
>    ...
> 
>  Zeitverzogerung.mp4 
> ### What is the version this bug report is based on?
> 3.63.9.20220430
> 
> ### Which base platform are you running?
> tinkerboard (ASUS Tinkerboard)
> 
> ### Which HomeMatic/homematicIP radio module are you using?
> RPI-RF-MOD
> 
> ### Anything in the logs that might be useful for us?
> ```
> no
> ```
> 
> ### Additional information
> Getestet mit Firefox 100.0 64 Bit und Brave V1.38.111


Hallo zusammen, 

Aktuell besteht diese Problem wieder bei mir. Selbes verhalten auch in der vor Version.

Aktuelle Firmwareversion: | 3.79.6.20241122
Plattform Proxmox 8.2.8
Homematic verbindung RPI-RF-MOD

Gruß

**Comment by jens-maus** [comment]
Dieses Issue ist geschlossen. Wenn Problem wieder existent bitte frisches/neues issue aufmachen und das hier nicht wiederbeleben.
