### ISSUE TITLE
HTTPS-Certificate generation doesn't restart lighthttpd correctly.

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#184]
Upon using the functionality to regenerate the HTTPS certificate lighttpd (as the main webserver) is usually automatically restarted. However, restart doesn't seem to work correctly and thus the WebUI cannot be accessed anymore after the regeneration of the SSL certificate is finished.

**Comment by mreschka** [comment]
The patch from 142f7c4 doesn't seem to work anymore due to the `/dev/null` modification, the current version does a restart again, /www/api/methods/user/restartlighttpd.tcl contains `exec -- /usr/bin/nohup /etc/init.d/S50lighttpd restart >/dev/null`

**Comment by jens-maus** [comment]
What kind of /dev/null modfication are you talking about? Please show!

**Comment by mreschka** [comment]
Your patch: `buildroot-external/patches/occu/0004-LocalSSLCert.patch`

```
...
--- occu/WebUI/www/api/methods/user/restartlighttpd.tcl.orig
+++ occu/WebUI/www/api/methods/user/restartlighttpd.tcl
...
-exec /etc/init.d/S50lighttpd restart
+exec /etc/init.d/S50lighttpd reload &
...
```
Reality in `/www/api/methods/user/restartlighttpd.tcl` in my installation 3.37.8.20180929

```
exec -- /usr/bin/nohup /etc/init.d/S50lighttpd restart >/dev/null
```

My conclusion: Your patch does not find the line anymore and restart is not rewritten in reload.

**Comment by mreschka** [comment]
Ah, I just saw this patch was removed in master - it is only available using the link in the commit 142f7c4 I gues it got lost? - the modifications to the lighthttp rc script are still there.

**Comment by caTenschert** [comment]
Rasp CCU:3.37.8 2018.08.29.
http don't restart, i get no cert. 
login on ssh and start S50Lighthttp manual

Beim erzeugen des Zertifikats, kommt nur die Meldung starte Webserver neu. Es wird kein Zertifikat erstellt. Login per ssh und manueller start von S50lighthttp startet zumindest.

gibt es eine Möglichkeit das Zertifikat selber zu erstellen, es muss ja dann nur hoch geladen werden?

**Comment by mreschka** [comment]
Kann ich so nicht bestätigten. Das Zertifikat wird bei mir direkt neu erstellt, es liegt dann unter `/etc/config/server.pem` Bei jedem mal Klicken wir es neu erzeugt, der Server ist dann halt erst mal weg. Wenn man den Server dann manuell über `/etc/init.d/S50lighttpd start` wieder startet wird es sogar direkt genutzt.

**Comment by caTenschert** [comment]
Ja da liegt es, bin davon ausgegangen das man es erst runter laden muss, in der Maske gibt es ja den Upload Button und den Hochladen Knopf
