### ISSUE TITLE
 "Starting rfd: ...........ERROR" in HA Supervised

### ISSUE THREAD

**Issue by cocktailyogi** [jens-maus/RaspberryMatic#1841]
### Describe the issue you are experiencing

Hi, I am basically having the same trouble than described in this issue #1800 on RPI4 with Debian 11.
I have read the warning in install manual regarding "Home Assistant Supervised" and added the option "systemd.unified_cgroup_hierarchy=false" in my /boot/cmdline.txt.

### Describe the behavior you expected

Stick RF-USB should be clean detected and usable.

### Steps to reproduce the issue

1. Install HA Addon on RPI 4 in HA Supervised according to manual
2. Start it

### What is the version this bug report is based on?

3.63.9.20220519

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Mounting /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying host system: oci, OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.0, OK
Identifying Homematic RF-Hardware: ....HmRF: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-0000:01:00.0-1.4, HmIP: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-0000:01:00.0-1.4, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: 4.4.16, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: .OK
Starting rfd: ....................ERROR
Starting HMIPServer: .......................................................................................................................................................ERROR
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.63.9.20220519 (raspmatic_oci_arm)
```

### Additional information

I have read the warning in install manual regarding "Home Assistant Supervised" and added the option "systemd.unified_cgroup_hierarchy=false" in my /boot/cmdline.txt.

**Comment by jens-maus** [comment]
Sorry, but your title does not match your log file output here. In the title you write something about "Starting multimacd: ...........ERROR" but your logfile shows rfd and HMIPServer not being able to be started.

Please note that running a HA Supervised installation has it clear limitations which are most often simply a fact/limitation of the underlaying operating system used (here in that case your Debian 11). And the workaround with `systemd.unified_cgroup_hierarchy=false` is just an example here. There might be apparmor things potentially blocking the hardware access, etc. etc. So please provide more detailed debug information and try to identify the reason why rfd isn't able to be started (probably because the `/dev/mmd_bidcos` and `/dev/mmd_hmip` device nodes are not available or accessible. But just showing the RaspberryMatic docker startup messages does not help, I am afraid.

**Comment by cocktailyogi** [comment]
> Sorry, but your title does not match your log file output here. In the title you write something about "Starting multimacd: ...........ERROR" but your logfile shows rfd and HMIPServer not being able to be started.
Sorry, you are right. I have read so much about these issues, that I confused myself when opening this issue. I have updated the titel. Sorry for that.

I will try to find more debug information regading /dev/mmd_hmip. have you any suggestions, where to find them?

**Comment by jens-maus** [comment]
> I will try to find more debug information regading /dev/mmd_hmip. have you any suggestions, where to find them?

Well, after multimacd startup there should be a `/dev/mmd_hmip` and `/dev/mmd_bidcos` device node on your debian system, which is actually the reason why the docker container requires raised privileges to actually create them. And also have a look for some strange output shown in `dmesg` which might be actually pointing at some permission issues, probably due to AppArmor restrictions similar like in #1834

**Comment by cocktailyogi** [comment]
Okay, on my host I can find in dmesg this lines after starting raspeberrymatic-addon-container:
[ 2581.689133] raw-uart raw-uart: Reset radio module
[ 2590.525930] eq3loop: created slave mmd_hmip
[ 2590.526308] eq3loop: created slave mmd_bidcos

If I open a shell in my container, I am getting same logs:
[ 2581.689133] raw-uart raw-uart: Reset radio module
[ 2590.525930] eq3loop: created slave mmd_hmip
[ 2590.526308] eq3loop: created slave mmd_bidcos

ls -l in conatiner gives this:
ls -l /dev/mmd*
crw-------    1 root     root      241,   2 May 20 09:16 /dev/mmd_bidcos
crw-------    1 root     root      241,   1 May 20 09:16 /dev/mmd_hmip

In dmesg I have this line, but I do not know, if it is good or bad:
cgroup: cgroup: disabling cgroup2 socket matching due to net_prio or net_cls activation

**Comment by cocktailyogi** [comment]
In hmserver.log I can find this lines:

de.eq3.cbcs.server.core.vertx.KeyServerWorker ERROR [vert.x-worker-thread-0] Missing key server configuration parameter (Network.Key) for  mode: KEYSERVER_LOCAL
de.eq3.cbcs.server.local.base.internal.LocalServerAdapterInitialization ERROR [vert.x-eventloop-thread-1] Error 'LOCAL_ADAPTER_NO_SUCH_PORT' while trying to open port '/dev/mmd_hmip':
de.eq3.cbcs.lib.commdevice.CommDeviceException: Exception while trying to open serial port. Check configured port '/dev/mmd_hmip'

**Comment by cocktailyogi** [comment]
There is file which seems to have more detailed messages:
/var/log/messages

`May 20 09:16:35 de838cd8-raspberrymatic-dev syslog.info syslogd started: BusyBox v1.35.0
May 20 09:16:36 de838cd8-raspberrymatic-dev user.info firewall: configuration set
May 20 09:16:40 de838cd8-raspberrymatic-dev daemon.err xinetd[370]: Unable to read included directory: /etc/config/xinetd.d [file=/etc/xinetd.conf] [line=14]
May 20 09:16:40 de838cd8-raspberrymatic-dev daemon.crit xinetd[370]: 370 {init_services} no services. Exiting...
May 20 09:16:40 de838cd8-raspberrymatic-dev user.info root: Updating RF Lan Gateway Coprocessor Firmware
May 20 09:16:40 de838cd8-raspberrymatic-dev user.debug update-coprocessor: firmware filename is: coprocessor_update_hm_only.eq3
May 20 09:16:40 de838cd8-raspberrymatic-dev user.info root: Updating RF Lan Gateway Firmware
May 20 09:16:40 de838cd8-raspberrymatic-dev user.info update-lgw-firmware: No gateway found in config file /etc/config/rfd.conf
May 20 09:16:47 de838cd8-raspberrymatic-dev user.err rfd: CCU2CommController::improvedInit() - Identify response string not handled:
May 20 09:16:52 de838cd8-raspberrymatic-dev user.err rfd: () CCU2CommController::setCSMACAEnabled(): Error disabling CSMA/CA.
May 20 09:16:52 de838cd8-raspberrymatic-dev user.err rfd: No BidCoS-Interface available
May 20 09:22:30 de838cd8-raspberrymatic-dev daemon.info : starting pid 916, tty '': '/bin/mv /tmp/boot.log /var/log/boot.log'
May 20 09:22:30 de838cd8-raspberrymatic-dev daemon.info : starting pid 917, tty '/dev/null': '/usr/bin/monit -Ic /etc/monitrc'
May 20 09:22:30 de838cd8-raspberrymatic-dev user.info monit[917]: Starting Monit 5.30.0 daemon with http interface at /var/run/monit.sock
May 20 09:22:30 de838cd8-raspberrymatic-dev user.info monit[917]: 'de838cd8-raspberrymatic-dev' Monit 5.30.0 started
May 20 09:22:35 de838cd8-raspberrymatic-dev local0.err ReGaHss: ERROR: XmlRpc: Error in XmlRpcClient::writeRequest: write error (error 111). [error():iseXmlRpc.h:281]
May 20 09:22:35 de838cd8-raspberrymatic-dev local0.warn ReGaHss: WARNING: XMLRPC 'init': rpcClient.execute() failed (url: xmlrpc_bin://127.0.0.1:32001, params: {"xmlrpc_bin://127.0.0.1:31999","1007"}, result: nil) [CallXmlrpcMethod():iseXmlRpc.cpp:2602]
May 20 09:22:35 de838cd8-raspberrymatic-dev local0.err ReGaHss: ERROR: XMLRPC 'init' call failed (interface: 1007, params: {"xmlrpc_bin://127.0.0.1:31999","1007"}) [CallInit():iseXmlRpc.cpp:1204]
May 20 09:22:35 de838cd8-raspberrymatic-dev local0.err ReGaHss: ERROR: failed CallInit() for interface=BidCos-RF [ThreadFunction():iseRTHss.cpp:163]
May 20 09:22:35 de838cd8-raspberrymatic-dev local0.err ReGaHss: ERROR: XmlRpc: Error in XmlRpcClient::writeRequest: write error (error 111). [error():iseXmlRpc.h:281]
May 20 09:22:35 de838cd8-raspberrymatic-dev local0.warn ReGaHss: WARNING: XMLRPC 'init': rpcClient.execute() failed (url: xmlrpc://127.0.0.1:39292/groups, params: {"xmlrpc_bin://127.0.0.1:31999","1008"}, result: nil) [CallXmlrpcMethod():iseXmlRpc.cpp:2602]
May 20 09:22:35 de838cd8-raspberrymatic-dev local0.err ReGaHss: ERROR: XMLRPC 'init' call failed (interface: 1008, params: {"xmlrpc_bin://127.0.0.1:31999","1008"}) [CallInit():iseXmlRpc.cpp:1204]
May 20 09:22:35 de838cd8-raspberrymatic-dev local0.err ReGaHss: ERROR: failed CallInit() for interface=VirtualDevices [ThreadFunction():iseRTHss.cpp:163]
May 20 09:22:35 de838cd8-raspberrymatic-dev local0.err ReGaHss: ERROR: XmlRpc: Error in XmlRpcClient::writeRequest: write error (error 111). [error():iseXmlRpc.h:281]
May 20 09:22:35 de838cd8-raspberrymatic-dev local0.warn ReGaHss: WARNING: XMLRPC 'init': rpcClient.execute() failed (url: xmlrpc://127.0.0.1:32010, params: {"xmlrpc_bin://127.0.0.1:31999","1009"}, result: nil) [CallXmlrpcMethod():iseXmlRpc.cpp:2602]
May 20 09:22:35 de838cd8-raspberrymatic-dev local0.err ReGaHss: ERROR: XMLRPC 'init' call failed (interface: 1009, params: {"xmlrpc_bin://127.0.0.1:31999","1009"}) [CallInit():iseXmlRpc.cpp:1204]
May 20 09:22:35 de838cd8-raspberrymatic-dev local0.err ReGaHss: ERROR: failed CallInit() for interface=HmIP-RF [ThreadFunction():iseRTHss.cpp:163]
May 20 09:22:45 de838cd8-raspberrymatic-dev user.err monit[917]: 'udevdEnabled' status failed (0) -- no output
May 20 09:22:46 de838cd8-raspberrymatic-dev user.err monit[917]: 'sshdEnabled' status failed (1) -- no output
May 20 09:22:46 de838cd8-raspberrymatic-dev user.err monit[917]: 'hs485dEnabled' status failed (2) -- grep: /var/etc/hs485d.conf: No such file or directory
May 20 09:22:47 de838cd8-raspberrymatic-dev user.err monit[917]: 'hmlangwEnabled' status failed (1) -- no output
May 20 09:22:47 de838cd8-raspberrymatic-dev user.warn monit[917]: 'HMIPServer' failed protocol test [DEFAULT] at [localhost]:39292 [TCP/IP] -- Connection refused
May 20 09:22:47 de838cd8-raspberrymatic-dev user.warn monit[917]: 'hasUSB' status failed (1) -- no output
May 20 09:22:47 de838cd8-raspberrymatic-dev user.err monit[917]: 'hb_rf_eth-CheckEnabled' status failed (1) -- no output
May 20 09:22:47 de838cd8-raspberrymatic-dev user.warn monit[917]: 'rpi4usb3Check' status failed (1) -- no output
May 20 09:22:47 de838cd8-raspberrymatic-dev user.err monit[917]: 'tailscaleEnabled' status failed (1) -- no output
May 20 09:22:47 de838cd8-raspberrymatic-dev user.err monit[917]: 'rfd' process is not running
May 20 09:22:47 de838cd8-raspberrymatic-dev user.info monit[917]: 'rfd' trying to restart
May 20 09:22:47 de838cd8-raspberrymatic-dev user.info monit[917]: 'rfd' restart: '/etc/init.d/S61rfd restart'
May 20 09:22:47 de838cd8-raspberrymatic-dev user.err rfd: CCU2CommController::improvedInit() - Identify response string not handled:
May 20 09:22:52 de838cd8-raspberrymatic-dev user.err rfd: () CCU2CommController::setCSMACAEnabled(): Error disabling CSMA/CA.
May 20 09:22:52 de838cd8-raspberrymatic-dev user.err rfd: No BidCoS-Interface available
May 20 09:23:17 de838cd8-raspberrymatic-dev user.err monit[917]: 'rfd' failed to restart (exit status -1) -- '/etc/init.d/S61rfd restart': Program timed out -- start-stop-daemon: warning: killing process 477: No such process
May 20 09:23:17 de838cd8-raspberrymatic-dev user.err monit[917]: Lookup for '/media/usb1' filesystem failed  -- not found in /proc/self/mounts
May 20 09:23:17 de838cd8-raspberrymatic-dev user.err monit[917]: Filesystem '/media/usb1' not mounted
May 20 09:23:17 de838cd8-raspberrymatic-dev user.err monit[917]: 'usb1' unable to read filesystem '/media/usb1' state
May 20 09:23:17 de838cd8-raspberrymatic-dev user.info monit[917]: 'usb1' trying to restart
May 20 09:23:31 de838cd8-raspberrymatic-dev user.warn monit[917]: 'HMIPServer' failed protocol test [DEFAULT] at [localhost]:39292 [TCP/IP] -- Connection refused
May 20 09:23:33 de838cd8-raspberrymatic-dev user.warn monit[917]: 'hasUSB' status failed (1) -- no output
May 20 09:23:33 de838cd8-raspberrymatic-dev user.warn monit[917]: 'rpi4usb3Check' status failed (1) -- no output
May 20 09:23:33 de838cd8-raspberrymatic-dev user.err monit[917]: 'rfd' service restarted 1 times within 1 cycles(s) - exec
May 20 09:23:33 de838cd8-raspberrymatic-dev user.info monit[917]: 'rfd' exec: '/bin/triggerAlarm.tcl rfd restarted WatchDog: rfd-restart true'
May 20 09:23:33 de838cd8-raspberrymatic-dev user.err monit[917]: 'rfd' process is not running
May 20 09:23:33 de838cd8-raspberrymatic-dev user.info monit[917]: 'rfd' trying to restart
May 20 09:23:33 de838cd8-raspberrymatic-dev user.info monit[917]: 'rfd' restart: '/etc/init.d/S61rfd restart'
May 20 09:23:33 de838cd8-raspberrymatic-dev user.err rfd: CCU2CommController::improvedInit() - Identify response string not handled:
May 20 09:23:38 de838cd8-raspberrymatic-dev user.err rfd: () CCU2CommController::setCSMACAEnabled(): Error disabling CSMA/CA.
May 20 09:23:38 de838cd8-raspberrymatic-dev user.err rfd: No BidCoS-Interface available
May 20 09:24:03 de838cd8-raspberrymatic-dev user.err monit[917]: 'rfd' failed to restart (exit status -1) -- '/etc/init.d/S61rfd restart': Program timed out -- start-stop-daemon: warning: killing process 1029: No such process
May 20 09:24:03 de838cd8-raspberrymatic-dev user.err monit[917]: Filesystem '/media/usb1' not mounted
May 20 09:24:03 de838cd8-raspberrymatic-dev user.err monit[917]: 'usb1' unable to read filesystem '/media/usb1' state
May 20 09:24:03 de838cd8-raspberrymatic-dev user.info monit[917]: 'usb1' trying to restart
May 20 09:24:17 de838cd8-raspberrymatic-dev user.warn monit[917]: 'HMIPServer' failed protocol test [DEFAULT] at [localhost]:39292 [TCP/IP] -- Connection refused
May 20 09:24:19 de838cd8-raspberrymatic-dev user.warn monit[917]: 'hasUSB' status failed (1) -- no output
May 20 09:24:19 de838cd8-raspberrymatic-dev user.err monit[917]: 'rpi4usb3Check' status failed (1) -- no output
May 20 09:24:19 de838cd8-raspberrymatic-dev user.err monit[917]: 'rfd' process is not running
May 20 09:24:19 de838cd8-raspberrymatic-dev user.info monit[917]: 'rfd' trying to restart
May 20 09:24:19 de838cd8-raspberrymatic-dev user.info monit[917]: 'rfd' restart: '/etc/init.d/S61rfd restart'
May 20 09:24:19 de838cd8-raspberrymatic-dev user.err rfd: CCU2CommController::improvedInit() - Identify response string not handled:
May 20 09:24:24 de838cd8-raspberrymatic-dev user.err rfd: () CCU2CommController::setCSMACAEnabled(): Error disabling CSMA/CA.
May 20 09:24:24 de838cd8-raspberrymatic-dev user.err rfd: No BidCoS-Interface available
May 20 09:24:49 de838cd8-raspberrymatic-dev user.err monit[917]: 'rfd' failed to restart (exit status -1) -- '/etc/init.d/S61rfd restart': Program timed out -- start-stop-daemon: warning: killing process 1140: No such process
May 20 09:24:49 de838cd8-raspberrymatic-dev user.err monit[917]: Filesystem '/media/usb1' not mounted
May 20 09:24:49 de838cd8-raspberrymatic-dev user.err monit[917]: 'usb1' unable to read filesystem '/media/usb1' state
May 20 09:24:49 de838cd8-raspberrymatic-dev user.info monit[917]: 'usb1' trying to restart
May 20 09:25:03 de838cd8-raspberrymatic-dev user.warn monit[917]: 'HMIPServer' failed protocol test [DEFAULT] at [localhost]:39292 [TCP/IP] -- Connection refused
May 20 09:25:04 de838cd8-raspberrymatic-dev user.warn monit[917]: 'hasUSB' status failed (1) -- no output
May 20 09:25:05 de838cd8-raspberrymatic-dev user.err monit[917]: 'rfd' service restarted 1 times within 1 cycles(s) - exec
May 20 09:25:05 de838cd8-raspberrymatic-dev user.err monit[917]: 'rfd' process is not running
May 20 09:25:05 de838cd8-raspberrymatic-dev user.info monit[917]: 'rfd' trying to restart
May 20 09:25:05 de838cd8-raspberrymatic-dev user.info monit[917]: 'rfd' restart: '/etc/init.d/S61rfd restart'
May 20 09:25:05 de838cd8-raspberrymatic-dev user.err rfd: CCU2CommController::improvedInit() - Identify response string not handled:
May 20 09:25:10 de838cd8-raspberrymatic-dev user.err rfd: () CCU2CommController::setCSMACAEnabled(): Error disabling CSMA/CA.
May 20 09:25:10 de838cd8-raspberrymatic-dev user.err rfd: No BidCoS-Interface available
May 20 09:25:35 de838cd8-raspberrymatic-dev user.err monit[917]: 'rfd' failed to restart (exit status -1) -- '/etc/init.d/S61rfd restart': Program timed out -- start-stop-daemon: warning: killing process 1250: No such process
May 20 09:25:35 de838cd8-raspberrymatic-dev user.err monit[917]: Filesystem '/media/usb1' not mounted
May 20 09:25:35 de838cd8-raspberrymatic-dev user.err monit[917]: 'usb1' unable to read filesystem '/media/usb1' state
May 20 09:25:35 de838cd8-raspberrymatic-dev user.info monit[917]: 'usb1' trying to restart
May 20 09:25:49 de838cd8-raspberrymatic-dev user.err monit[917]: 'HMIPServer' failed protocol test [DEFAULT] at [localhost]:39292 [TCP/IP] -- Connection refused
May 20 09:25:49 de838cd8-raspberrymatic-dev user.info monit[917]: 'HMIPServer' trying to restart
May 20 09:25:49 de838cd8-raspberrymatic-dev user.info monit[917]: 'HMIPServer' restart: '/etc/init.d/S62HMServer restart'
May 20 09:26:19 de838cd8-raspberrymatic-dev user.err monit[917]: 'HMIPServer' failed to restart (exit status -1) -- '/etc/init.d/S62HMServer restart': Program timed out -- Stopping HMIPServer: OK Starting HMIPServer: ...............
May 20 09:26:20 de838cd8-raspberrymatic-dev user.err monit[917]: 'hasUSB' status failed (1) -- no output
May 20 09:26:21 de838cd8-raspberrymatic-dev user.err monit[917]: 'rfd' process is not running
May 20 09:26:21 de838cd8-raspberrymatic-dev user.info monit[917]: 'rfd' trying to restart
May 20 09:26:21 de838cd8-raspberrymatic-dev user.info monit[917]: 'rfd' restart: '/etc/init.d/S61rfd restart'
May 20 09:26:21 de838cd8-raspberrymatic-dev user.err rfd: CCU2CommController::improvedInit() - Identify response string not handled:
May 20 09:26:26 de838cd8-raspberrymatic-dev user.err rfd: () CCU2CommController::setCSMACAEnabled(): Error disabling CSMA/CA.
May 20 09:26:26 de838cd8-raspberrymatic-dev user.err rfd: No BidCoS-Interface available
May 20 09:26:51 de838cd8-raspberrymatic-dev user.err monit[917]: 'rfd' failed to restart (exit status -1) -- '/etc/init.d/S61rfd restart': Program timed out -- start-stop-daemon: warning: killing process 1355: No such process
May 20 09:27:05 de838cd8-raspberrymatic-dev user.err monit[917]: 'HMIPServer' service restarted 1 times within 1 cycles(s) - exec
May 20 09:27:05 de838cd8-raspberrymatic-dev user.info monit[917]: 'HMIPServer' exec: '/bin/triggerAlarm.tcl HMIPServer restarted WatchDog: hmipserver-restart true'
May 20 09:27:05 de838cd8-raspberrymatic-dev user.info monit[917]: 'HMIPServer' process is running after previous exec error (slow starting or manually recovered?)
May 20 09:27:05 de838cd8-raspberrymatic-dev user.info monit[917]: 'HMIPServer' process is running after previous restart timeout (manually recovered?)
May 20 09:27:05 de838cd8-raspberrymatic-dev user.err monit[917]: 'HMIPServer' failed protocol test [DEFAULT] at [localhost]:39292 [TCP/IP] -- Connection refused
May 20 09:27:05 de838cd8-raspberrymatic-dev user.info monit[917]: 'HMIPServer' trying to restart
May 20 09:27:05 de838cd8-raspberrymatic-dev user.info monit[917]: 'HMIPServer' restart: '/etc/init.d/S62HMServer restart'
`

**Comment by jens-maus** [comment]
Well, your output suggests that multimacd is at least able to create the two mmd devices. However, rfd and hmipserver does not seem to be able to correctly use these devices and end up saying that they are inaccessible.

So sorry, but I am more or less out of ideas. Here the same thing works in another context (within Ubuntu...) Thus this must be a local issue on your end and not a general issue within RaspberryMatic. As said, using a HA Supervised installation is anyway not the best way to go these days anymore. Better would be you go for a full-fledged HomeAssistantOS installation (e.g. virtualized) and refrain from all the trouble that you buy with such a HA Supervised environment (as you can see from here). And this is especially true if you don't have the full knowhow yourself to solve/debug such issues.

So I am afraid, but this seems to be that we won't find a solution here. Also note, please, that this is no discussion fora here but a bug/issue tracker. But the problem you show here is no systematic issue in RaspberryMatic itself but a local issue on your end. So please transfer this issue to a discussion fora in trying to find help.

P.S: Please always use code tags here for actualy textual logfile/text output! I don't want to have to re-edit it all the time... And please make sure not to flood this ticket here. This is no discussion fora here but a bug/issue tracker!

**Comment by cocktailyogi** [comment]
Okay thx for checking.

**Comment by sriegler** [comment]
Well I'm exactly in the same pickle. Updated underlying OS and Home Assistant, now it suddenly does not recognize the RF interface anymore.

* HA Supervised, kernel module, boot options, all ok.
* Board is identified: Identifying Homematic RF-Hardware: ....HmRF: HM-MOD-RPI-PCB/HB-RF-USB-2@usb-0000:01:00.0-1.3, HmIP: HM-MOD-RPI-PCB/HB-RF-USB-2@usb-0000:01:00.0-1.3, OK
* /dev/mmd_* are created and accessible on the host

But they are not accessible from inside the container:

```
/ # ls -la /dev/mmd_*
crw-------    1 root     root      239,   2 May 23 17:49 /dev/mmd_bidcos
crw-------    1 root     root      239,   1 May 23 17:49 /dev/mmd_hmip

/ # less /dev/mmd_bidcos 
less: can't open '/dev/mmd_bidcos': Operation not permitted
```

Currently trying to debug and fiddling around with AppArmor, right now it's my only idea who could deny access, even though /dev is specified in the profile. If you have any other pointers, I'll gladly take them. Thanks.

RPI4: Raspbian 5.15.32-v7l+ - 11.3
Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05
RaspberryMatic CCU: 3.63.9.20220521

**Comment by jens-maus** [comment]
> Well I'm exactly in the same pickle. Updated underlying OS and Home Assistant, now it suddenly does not recognize the RF interface anymore.
> 
> * HA Supervised, kernel module, boot options, all ok.
> * Board is identified: Identifying Homematic RF-Hardware: ....HmRF: HM-MOD-RPI-PCB/HB-RF-USB-2@usb-0000:01:00.0-1.3, HmIP: HM-MOD-RPI-PCB/HB-RF-USB-2@usb-0000:01:00.0-1.3, OK
> * /dev/mmd_* are created and accessible on the host
> 
> But they are not accessible from inside the container:

That's exactly why I always prefer and would always suggest to use HomeAssistantOS to run HomeAssistant rather than installing a HA supervised installation - which is know to cause such trouble sooner or later as you can see.

> RPI4: Raspbian 5.15.32-v7l+ - 11.3 Home Assistant Core 2022.5.5 Home Assistant Supervisor 2022.05 RaspberryMatic CCU: 3.63.9.20220521

Well, you mentioned "boot options, all ok" above, but are you sure to have the `GRUB_CMDLINE_LINUX_DEFAULT="systemd.unified_cgroup_hierarchy=false"` workaround in place like mentioned in the documentation (cf. https://github.com/jens-maus/RaspberryMatic/wiki/Installation-HomeAssistant#using-homeassistant-supervised)?

**Comment by sriegler** [comment]
> That's exactly why I always prefer and would always suggest to use HomeAssistantOS to run HomeAssistant rather than installing a HA supervised installation - which is know to cause such trouble sooner or later as you can see.

Yea I know, I would, but for my purposes it's too limited.

> Well, you mentioned "boot options, all ok" above, but are you sure you have the `GRUB_CMDLINE_LINUX_DEFAULT="systemd.unified_cgroup_hierarchy=false"` workaround in place like mentioned in the documentation (cf. https://github.com/jens-maus/RaspberryMatic/wiki/Installation-HomeAssistant#using-homeassistant-supervised)?

Yes, in place. And I can access other devices with the same perms. e.g.
```
crw-------    1 root     root      239,   0 May 23 17:58 eq3loop
crw-------    1 root     root      239,   1 May 23 17:59 mmd_hmip
crw-------    1 root     root      239,   2 May 23 17:59 mmd_bidcos
```

eq3loop is accessible inside without problems, the other mmd_* devs are not.

**Comment by jens-maus** [comment]
> > That's exactly why I always prefer and would always suggest to use HomeAssistantOS to run HomeAssistant rather than installing a HA supervised installation - which is know to cause such trouble sooner or later as you can see.
> 
> Yea I know, I would, but for my purposes it's too limited.

It's not really. You can run all kind of docker containers there as well and thus have all functionality you would have with a full-fledged Raspbian, just the other way around. But it's up to you. But IMHO you are simply asking for such trouble if you use a HA Supervised installation for such applications like RaspberryMatic which require direct and partly priviledged hardware/kernel access...

> Yes, in place. And I can access other devices with the same perms. e.g.
> 
> ```
> crw-------    1 root     root      239,   0 May 23 17:58 eq3loop
> crw-------    1 root     root      239,   1 May 23 17:59 mmd_hmip
> crw-------    1 root     root      239,   2 May 23 17:59 mmd_bidcos
> ```
> 
> eq3loop is accessible inside without problems, the other mmd_* devs are not.

Well, then this `systemd.unified_cgroup_hierarchy=false` workaround does not seem to work anymore for newer or all kind of different Linux distributions with all there different cgroup/apparmor/seccomp combinations. Perhaps @pvizeli or @agners are having some further idea here. But as said: Using HA Supervised is asking for such trouble!

**Comment by sriegler** [comment]
Ok I fixed it. I just "reinstalled" supervised HA using the guide: https://github.com/home-assistant/supervised-installer

Reinstalled over existing installation, worked. Had to start all add-ons manually after "re-installation", but everything works afterwards. (with boot options)

The OS-agent and Supervised package are seemingly not automatically updated. Just for the future and others to keep in mind.

@cocktailyogi, try this. I think we can close the issue.

**Comment by pvizeli** [comment]
Correct, you need manual updates on the os-agent and the installer from time to time. The current beta will also show your system as unsupported with cgroup2. I guess we should do the same for the old os-agent. So people see if the system is supported or not. 

@jens-maus we limited the scope to https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md . If you want a support supervisor, I would suggest that it has to show as a supported system.

**Comment by smoki3** [comment]
For me it looks like this: rfd is going well. 

```
Mounting` /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying host system: oci, OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.2, OK
Identifying Homematic RF-Hardware: ....HmRF: RPI-RF-MOD/GPIO@fe201000.serial, HmIP: RPI-RF-MOD/GPIO@fe201000.serial, OK
Updating Homematic RF-Hardware: RPI-RF-MOD: 4.4.22, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: creating new SSL cert... OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: .OK
Starting rfd: .OK
Starting HMIPServer: .......................................................................................................................................................ERROR
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: OK
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.63.9.20220625 (raspmatic_oci_arm)
```

**Comment by smashingchrische** [comment]
Hey I have the same issue, but I am using RaspberryMatic on HomeAssistant OS.
I recently upgraded to 2022.9.6, but downgraded since I have issue with my Raspberrymatic.
The problem started once I restarted HomeAssistant since lovelace hanged. I could still reach my Raspberrymatic on Port 8080, but I restarted HomeAssistant (power plug method). Now I have a proper ssh setup, but it was my only option once it hang up.
Can you help me?
> 
> Mounting /data as /usr/local (Home Assistant Add-On): OK
> Starting watchdog...
> Identifying host system: oci, OK
> Initializing RTC Clock: no hardware found
> Running sysctl: OK
> Checking for Factory Reset: not required
> Checking for Backup Restore: not required
> Initializing System: OK
> Setup ca-certificates: OK
> Starting logging: OK
> Init onboard LEDs: init, OK
> Starting irqbalance: OK
> Starting iptables: OK
> Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.1, OK
> Identifying Homematic RF-Hardware: ....HmRF: HM-MOD-RPI-PCB/GPIO@3f201000.serial, HmIP: HM-MOD-RPI-PCB/GPIO@3f201000.serial, OK
> Updating Homematic RF-Hardware: HM-MOD-RPI-PCB: 2.8.6, not necessary, OK
> Starting hs485dLoader: disabled
> Starting xinetd: OK
> Starting eq3configd: OK
> Starting lighttpd: OK
> Starting ser2net: disabled
> Starting ssdpd: OK
> Starting ha-proxy: OK
> Starting NUT services: disabled
> Initializing Third-Party Addons: OK
> Starting LGWFirmwareUpdate: ...OK
> Setting LAN Gateway keys: OK
> Starting hs485d: disabled
> Starting multimacd: .OK
> Starting rfd: ....................ERROR
> Starting HMIPServer: ..................OK
> Starting ReGaHss: .OK
> Starting CloudMatic: OK
> Starting NeoServer: disabled
> Starting Third-Party Addons: OK
> find: /usr/local/etc/monit*.cfg: No such file or directory
> Starting crond: OK
> Setup onboard LEDs: booted, OK
> Finished Boot: 3.65.8.20220831 (raspmatic_oci_arm64)

**Comment by jens-maus** [comment]
> Hey I have the same issue, but I am using RaspberryMatic on HomeAssistant OS.

Well, this is currently a known issue (https://github.com/jens-maus/RaspberryMatic/issues/1942) with HomeAssistantOS 9.x and the current stable version of RaspberryMatic. Either downgrade to 8.x, wait for the next RaspberryMatic version or use the latest snapshot version.

**Comment by smashingchrische** [comment]
> > Hey I have the same issue, but I am using RaspberryMatic on HomeAssistant OS.
> 
> Well, this is currently a known issue (#1942) with HomeAssistantOS 9.x and the current stable version of RaspberryMatic. Either downgrade to 8.x, wait for the next RaspberryMatic version or use the latest snapshot version.

Thanks, for the answer. I have downgraded to 2022.9.5 and after rebooting and rebuilding ha core Raspberrymatic started working again. I have confirmed that the issue persists with 2022.9.6. I will skip some updates, but I wanted to let you know that I don't have rfd issues on 2022.9.5, only right now.
