### ISSUE TITLE
Neustart oder Herunterfahren nicht mehr möglich

### ISSUE THREAD

**Issue by jtrouvain** [jens-maus/RaspberryMatic#1845]
### Describe the issue you are experiencing

Hallo,

seit einiger Zeit funktioniert der Neustart oder auch das Herunterfahren des Systems nicht. 
-Habe eine neue SD Karte geflasht., 
-neuestes Release eingespielt
-Backup eingespielt
-einmal Neustart funktioniert
-2. Neustart nicht mehr
-System zeigt an, dass ein Neustart gemacht wird, aber es passiert nicht (Nachverfolgung Konsole)
-auch über die Konsole nein Neustart möglich

### Describe the behavior you expected

SYtem soll neu starten

### Steps to reproduce the issue

1.Systemsteuerung->Zentralenwartung->Neustart
2.
3.
...

### What is the version this bug report is based on?

3.63.9.2022021 (rpi3)

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
No. Log zeigt nichts an.
```

**Comment by jens-maus** [comment]
Sorry, but this is no support or discussion fora here. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. This was also already mentioned in the ticket template!
___
Tut mir leid, aber das hier ist kein Supportforum, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen.  Dies stand übrigens auch so im Ticket Template!
