### ISSUE TITLE
Keypad HmIP-WKP - Kanäle als Bedingung (WENN) nicht auswählbar

### ISSUE THREAD

**Issue by mbhomie007** [jens-maus/RaspberryMatic#1846]
### Describe the issue you are experiencing

Keine Kanäle außer Kanal 0 als Bedingung [Wenn] in Programmen auswählbar.

https://homematic-forum.de/forum/viewtopic.php?f=58&t=74115&start=80

### Describe the behavior you expected

Alle Kanäle als Bedingung auswählbar, wie in der original CCU-Firmware

### Steps to reproduce the issue

1. Programm anlegen
2. Wenn Bedingung auswählen

### What is the version this bug report is based on?

3.63.9.20220521

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
-
```

### Additional information

https://youtu.be/G5M14LadFg8
Ab Minute 15:30

**Comment by jp112sdl** [comment]
Der große Unterschied zur CCU3 ist ja, wie es bisher mitbekommen habe, dass in RM _nur_ Kanal 0 angeboten wird und in der CCU3 alle (un)geraden? Kanäle, außer Kanal 0.

Vielleicht kommt irgendwas durcheinander durch diesen Patch:
https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0108-WebUI-ShowInvisibleHmIPChannelsInPrograms.patch

Sieht erstmal unscheinbar aus, aber vielleicht kann ein WKP-Besitzer in seiner `webui.js` diese 3 Änderungen mal rückgängig machen.

**Comment by jp112sdl** [comment]
Komisch. Dann verstehe ich den WebUI-Code nicht.

**Comment by jens-maus** [comment]
Kommen wir wohl doch nicht drumrum das sich jemand erbarmt und dir oder mir so ein HmIP-WKP spwndiert 😜

**Comment by nemex** [comment]
gerne kann ich ein backup zur verfügung stellen.Lg

**Comment by jens-maus** [comment]
Dann schick das mal über irgendwelche privaten kanäle an uns (@jp112sdl, @Baxxy13 und ich)

**Comment by nemex** [comment]
> Dann schick das mal über irgendwelche privaten Kanäle an uns (@jp112sdl,@Baxxy13und ich)

Alles klar mail ist raus

**Comment by Ho-Ecker** [comment]
Wenn das nicht hilft, ich könnte meinen Keypad zur Verfügung stellen. 
@jens-maus habe dir eben schon eine Mail geschickt wegen der Adresse.

**Comment by jens-maus** [comment]
Nachdem ich nun das Backup von @nemex kurz testen konnte scheint da Problem wohl banaler Natur zu sein, denn bereits im Kanalauswahlfenster scheint nur Kanal 0 aufgelistet zu werden. Siehe hier:

<img width="999" alt="Bildschirmfoto 2022-05-31 um 11 30 19" src="https://user-images.githubusercontent.com/5887769/171141782-23a0e54d-82be-41a1-8e8c-819e5ee0297a.png">

Die Frage wäre also wo/wie genau unterscheidet sich jetzt die Kanalauswahl für dieses Keypad von der Kanalauswahl anderer HmIP Geräte...

**Comment by nemex** [comment]
Naja es fehlen ja die Kanäle 1-16 in der Auswahl. Mit nur Kanal 0 kann man keine Bedingung mit Lock oder unlock wählen. Das Keypad arbeitet so nur im Toggelbetrieb.

![Eingan-Keypad_edit_660448283759118.jpg](https://user-images.githubusercontent.com/5516018/171143769-96b2a94c-9bc8-4aa2-bd0b-cd4458c2f923.jpg)

**Comment by jp112sdl** [comment]
> Die Frage wäre also wo/wie genau unterscheidet sich jetzt die Kanalauswahl für dieses Keypad von der Kanalauswahl anderer HmIP Geräte...

Siehe EDIT im https://github.com/jens-maus/RaspberryMatic/issues/1846#issuecomment-1135533537
Der Code befindet sich in der `webui.js`

**Comment by jp112sdl** [comment]
> Ich denke daher das hier der Fehler daran liegt das channel.isReadable false ist.

Hmm, das wird ja direkt vom Interface geholt, oder?
Entweder von hier:
https://github.com/eq-3/occu/blob/master/WebUI/www/api/methods/device/listalldetail.tcl#L20-L68
oder
https://github.com/eq-3/occu/blob/master/WebUI/www/api/methods/device/get.tcl#L25-L70

Wird auf der CCU3 eine andere HMIPServer Version ausgeliefert als im OCCU veröffentlicht ist?

**Comment by jens-maus** [comment]
> > Ich denke daher das hier der Fehler daran liegt das channel.isReadable false ist.
> 
> Hmm, das wird ja aus Datenpunkt mit `dp.Operations();` direkt vom Interface geholt, oder? Entweder von hier: https://github.com/eq-3/occu/blob/master/WebUI/www/api/methods/device/listalldetail.tcl#L20-L68 oder https://github.com/eq-3/occu/blob/master/WebUI/www/api/methods/device/get.tcl#L25-L70

Das ist ein guter Hinweis. Mit dem folgenden curl Aufruf kann man ja die `Device.listAllDetail` Methdoe einfach mal aufrufen:
```
curl -vvvv "http://localhost/api/homematic.cgi" -H 'Content-Type: application/json; charset=iso-8859-1' --data-raw '{"version": "1.1", "method": "Device.listAllDetail", "params": {"_session_id_": "XXXXXX"}}'
```
hier muss man natürlich bei `_session_id_` eine momentan gültige session ID eingeben.

Und dann spuckt der folgendes aus:
```
{"id":"62975","name":"Keypad Benutzer 1:1","address":"002E9FXXXXXX:1","deviceId":"62923","index":1,"partnerId":"","mode":"MODE_AES","category":"CATEGORY_SENDER","isReady":true,"isUsable":true,"isVisible":true,"isLogged":false,"isLogable":true,"isReadable":false,"isWritable":true,"isEventable":false,"isAesAvailable":false,"isVirtual":false,"isInternal":false,"channelType":"ACCESS_TRANSCEIVER"}
```

Insofern ist das was die WebUI macht wohl konsistent zu dem was die JSON RPC API hier direkt von der ReGa zurück bekommt, nämlich das der Kanal 1, usw. eben `isReadable: false` ist und insofern in der WebUI auch nicht auslesbar ist und damit im Kanalchooser auch nicht korrekterweise angeboten wird.

> Wird auf der CCU3 eine andere HMIPServer Version ausgeliefert als im OCCU veröffentlicht ist?

Das ist ne gute Frage. Leite ich weiter. Die Frage ist jedoch, woher bekommt der diese Infos? Die Gerätebeschreibungen stecken doch nicht im HmIPServer sondern eigentlich in der Geräte-Firmware und werden bei der Inclusion bzw. Anlernen dann entsprechend ausgelesen und übernommen. So zumindest mein Wissensstand. Das würde bedeuten, das das vielmehr ein Geräte-Firmware "Problem" ist bzw. sich dann eine CCU3 mit dem selben Backup exakt gleich verhalten müsste. Das würde dann darauf deuten, das eQ3 hier wohl noch eine neuere/aktuellere Firmware für den HmIP-WKP liegen hat bzw. für das generieren des Videos genutzt hat und damit die Verwirrung bzgl. CCU3 vs. RaspberryMatic WebUI erst ihren Lauf genommen hat.

**Comment by Baxxy13** [comment]
> Das würde dann darauf deuten, das eQ3 hier wohl noch eine neuere/aktuellere Firmware für den HmIP-WKP liegen hat

Diese These hatte ich schon am 21.05. im verlinkten Thread aufgestellt. 

> Entweder ist es ein Fehler in RM oder...
Spekulation: Das HmIP-WKP wird mit interschiedlichen Firmware-Ständen ausgeliefert die dann unterschiedliche Features bieten.
In der HmIP-Device-Documentation werden jedenfalls "PRESS_LOCK" und "PRESS_UNLOCK" in den Kanälen :1 - :16 nicht erwähnt.

Es gab aber bisher (soweit ich weiß) keine Rückmeldung(en) von CCU3 Nutzern (bei denen die Kanäle verfügbar sind) zur Firmware des Gerätes.

**Comment by jp112sdl** [comment]
Oder CCU3 Firmware runterladen, entpacken und den HMIPServer mal austauschen.
https://homematic-ip.com/sites/default/files/downloads/ccu3-3.63.9.tgz

**Comment by jens-maus** [comment]
> Oder CCU3 Firmware runterladen, entpacken und den HMIPServer mal austauschen. https://homematic-ip.com/sites/default/files/downloads/ccu3-3.63.9.tgz

Da bin ich gerade schon dabei. :) Nach meinen Analysen scheint es da in der Tat unterschiede bzgl. HMIPServer in CCU3 vs. OCCU zu geben die sich nicht erklären lassen.

**Comment by jens-maus** [comment]
So, nun hab ich den `HMIPServer.jar` von der CCU3 direkt für das nächste nightly snapshot übernommen. Bitte mal entsprechend testen ob damit bzgl. des `HmIP-WKP` Verbesserungen eintreten (habe selbst so ein Gerät ja nicht). Vmtl. wird aber wohl ein frischen Anlernen bzw. "Drüberlernen" mindestens notwendig sein damit die als non-readable geflaggten Kanäle entsprechend dann als readable geflagged werden.

So @mbhomie007, @Ho-Ecker, @nemex dann bitte mit dem nächsten nightly snapshot morgen entsprechend testen und hier Rückmeldung geben.

**Comment by jens-maus** [comment]
So, und zu guter letzt hab ich jetzt mal die `dp.Operations()` der beiden Datenpunkte von Kanal 1 und Kanal 2 auf Readable (`OPERATION_READ`) gesetzt. Nun wird der Kanal im ChannelChooser angezeigt und auch nach der Auswahl kann man ihn jetzt in den WebUI Programmen unter Bedingungen "nutzen". Allerdings kann man da kein `PRESS_LOCK` oder so auswählen, sondern lediglich "Berechtigung erteilt" und "Berechtigung nicht erteilt" wie man hier sehen kann:

<img width="715" alt="Bildschirmfoto 2022-05-31 um 16 42 24" src="https://user-images.githubusercontent.com/5887769/171202621-8c37732d-f696-469a-98c8-375e8056032a.png">

Und nichtmal eine suche nach `PRESS_LOCK` über den gesamten WebUI-Quellcode fördert da irgendetwas zu tage. Ist also alles etwas verworren und vmtl. hat der YouTube-Autor hier entweder eine frühe Development-Version verwendet um das Video zu drehen oder eine neuere HmIP-WKP Firmware, denn mit diesen Zusatzinfos sieht es nicht danach aus das die hier aufgedeckte `HMIPServer.jar` Differenz was mit diesem Problem hier zu tun hat, sondern nur ein zusätzliches "Problem" ist.

Auch sehe ich z.B. im Kanal 2 lediglich den folgenden Datenpunkt der auch nicht auf `PRESS_LOCK` schließen lässt:
```
HmIP-RF.002E9F2XXXXXX:2.ACCESS_AUTHORIZATION
```

Alles also ein wenig verworren momentan und ich bezweifle sogar das es einen CCU3 Nutzer gibt der mit der aktuellen 3.63.9 die Kanäle > 0 bzgl. `PRESS_LOCK` nutzen kann wie das im YouTube Video präsentiert wurde.

**Comment by jp112sdl** [comment]
> Auch sehe ich z.B. im Kanal 2 lediglich den folgenden Datenpunkt der auch nicht auf PRESS_LOCK schließen lässt:

Hmm, laut XML sollte es da mehr geben.
```XML
                <!-- User 1 lock -->
                <channel type="ACCESS_TRANSCEIVER" version="2" index="1" maxLinks="10" >
                        <parameter type="config" subtype="16channels_1">ABORT_EVENT_SENDING_CHANNELS</parameter>
                        <parameter type="config" subtype="default">NUMERIC_PIN_CODE</parameter>
                <parameter type="state" subtype="default">PRESS_LOCK</parameter>
                </channel>
                <!-- User 1 unlock -->
                <channel type="ACCESS_TRANSCEIVER" version="2" index="2" maxLinks="10">
                        <parameter type="config" subtype="16channels_2">ABORT_EVENT_SENDING_CHANNELS</parameter>
                <parameter type="state" subtype="default">PRESS_UNLOCK</parameter>
                </channel>
... bis User 8
```

Und der Channel Type `ACCESS_TRANSCEIVER` hat dann wiederum `ACCESS_AUTHORIZATION`
```XML
<channel type="ACCESS_TRANSCEIVER" typeversion="2">
        <link role="SENDER">
        <type>REMOTE_CONTROL</type>
    </link>
        <configuration>
                <!-- will be overwritten for default values
                <parameter>ABORT_EVENT_SENDING_CHANNELS</parameter>
                 -->

                <parameter>ALARM_MODE_TYPE</parameter>
                <parameter>ALARM_MODE_ZONE_1</parameter>
                <parameter>ALARM_MODE_ZONE_2</parameter>
                <parameter>ALARM_MODE_ZONE_3</parameter>
                <parameter>ALARM_MODE_ZONE_4</parameter>
                <parameter>ALARM_MODE_ZONE_5</parameter>
                <parameter>ALARM_MODE_ZONE_6</parameter>
                <parameter>ALARM_MODE_ZONE_7</parameter>
        </configuration>
        <state>
                <parameter>ACCESS_AUTHORIZATION</parameter>
        </state>
</channel>
```

**Comment by jens-maus** [comment]
> Hmm, laut XML sollte es da mehr geben.

Wo genau ist das her?

**Comment by jp112sdl** [comment]
Wenn man die HMIPServer.jar in .zip umbenennt (oder im Kontext die .jar direkt mit einem Unzipper öffnet), bekommt man alle Dateien. u.a. die `device_wkp.xml`

**Comment by Baxxy13** [comment]
> und ich bezweifle sogar das es einen CCU3 Nutzer gibt der mit der aktuellen 3.63.9 die Kanäle > 0 bzgl. `PRESS_LOCK` nutzen kann

Nunja, der [Screenshot](https://github.com/jens-maus/RaspberryMatic/issues/1846#issuecomment-1135992237) besagt anderes.

**Comment by jens-maus** [comment]
> Wenn man die HMIPServer.jar in .zip umbenennt (oder im Kontext die .jar direkt mit einem Unzipper öffnet), bekommt man alle Dateien. u.a. die `device_wkp.xml`

Ah, danke für den Hint. Das scheint es zu sein. Siehe hier:

```diff
--- hmipserver_ccu3/de/eq3/cbcs/devicedescription/devicespecification/eQ-3/device_wkp.xml	2022-04-22 09:48:22.000000000 +0200
+++ hmipserver/de/eq3/cbcs/devicedescription/devicespecification/eQ-3/device_wkp.xml	2022-03-11 10:30:56.000000000 +0100
@@ -1,5 +1,5 @@
 <?xml version="1.0" encoding="UTF-8"?>
-<deviceDescription id="WKP_V2" type="WKP" version="2" description="Keypad">
+<deviceDescription id="WKP_V1" type="WKP" version="1" description="Keypad">
 	<devTypes>
 		<devType label="HmIP-WKP" id="441" manufacturerCode="1" updateable="true" minVersion="0" />
 	</devTypes>
@@ -69,89 +69,73 @@
 		<channel type="ACCESS_TRANSCEIVER" version="2" index="1" maxLinks="10" >
 			<parameter type="config" subtype="16channels_1">ABORT_EVENT_SENDING_CHANNELS</parameter>
 			<parameter type="config" subtype="default">NUMERIC_PIN_CODE</parameter>
-        	<parameter type="state" subtype="default">PRESS_LOCK</parameter>
 		</channel>
 		<!-- User 1 unlock -->
 		<channel type="ACCESS_TRANSCEIVER" version="2" index="2" maxLinks="10">
 			<parameter type="config" subtype="16channels_2">ABORT_EVENT_SENDING_CHANNELS</parameter>
-        	<parameter type="state" subtype="default">PRESS_UNLOCK</parameter>
 		</channel>
 		<!-- User 2 lock -->
 		<channel type="ACCESS_TRANSCEIVER" version="2" index="3" maxLinks="10" >
 			<parameter type="config" subtype="16channels_3">ABORT_EVENT_SENDING_CHANNELS</parameter>
 			<parameter type="config" subtype="default">NUMERIC_PIN_CODE</parameter>
-        	<parameter type="state" subtype="default">PRESS_LOCK</parameter>
 		</channel>
 		<!-- User 2 unlock -->
 		<channel type="ACCESS_TRANSCEIVER" version="2" index="4" maxLinks="10" >
 			<parameter type="config" subtype="16channels_4">ABORT_EVENT_SENDING_CHANNELS</parameter>
-        	<parameter type="state" subtype="default">PRESS_UNLOCK</parameter>
 		</channel>
 		<!-- User 3 lock -->
 		<channel type="ACCESS_TRANSCEIVER" version="2" index="5" maxLinks="10" >
 			<parameter type="config" subtype="16channels_5">ABORT_EVENT_SENDING_CHANNELS</parameter>
 			<parameter type="config" subtype="default">NUMERIC_PIN_CODE</parameter>
-        	<parameter type="state" subtype="default">PRESS_LOCK</parameter>
 		</channel>
 		<!-- User 3 unlock -->
 		<channel type="ACCESS_TRANSCEIVER" version="2" index="6" maxLinks="10" >
 			<parameter type="config" subtype="16channels_6">ABORT_EVENT_SENDING_CHANNELS</parameter>
-        	<parameter type="state" subtype="default">PRESS_UNLOCK</parameter>
 		</channel>
 		<!-- User 4 lock -->
 		<channel type="ACCESS_TRANSCEIVER" version="2" index="7" maxLinks="10" >
 			<parameter type="config" subtype="16channels_7">ABORT_EVENT_SENDING_CHANNELS</parameter>
 			<parameter type="config" subtype="default">NUMERIC_PIN_CODE</parameter>
-        	<parameter type="state" subtype="default">PRESS_LOCK</parameter>
 		</channel>
 		<!-- User 4 unlock -->
 		<channel type="ACCESS_TRANSCEIVER" version="2" index="8" maxLinks="10" >
 			<parameter type="config" subtype="16channels_8">ABORT_EVENT_SENDING_CHANNELS</parameter>
-        	<parameter type="state" subtype="default">PRESS_UNLOCK</parameter>
 		</channel>
 		<!-- User 5 lock -->
 		<channel type="ACCESS_TRANSCEIVER" version="2" index="9" maxLinks="10" >
 			<parameter type="config" subtype="16channels_9">ABORT_EVENT_SENDING_CHANNELS</parameter>
 			<parameter type="config" subtype="default">NUMERIC_PIN_CODE</parameter>
-        	<parameter type="state" subtype="default">PRESS_LOCK</parameter>
 		</channel>
 		<!-- User 5 unlock -->
 		<channel type="ACCESS_TRANSCEIVER" version="2" index="10" maxLinks="10">
 			<parameter type="config" subtype="16channels_10">ABORT_EVENT_SENDING_CHANNELS</parameter>
-        	<parameter type="state" subtype="default">PRESS_UNLOCK</parameter>
 		</channel>
 		<!-- User 6 lock -->
 		<channel type="ACCESS_TRANSCEIVER" version="2" index="11" maxLinks="10" >
 			<parameter type="config" subtype="16channels_11">ABORT_EVENT_SENDING_CHANNELS</parameter>
 			<parameter type="config" subtype="default">NUMERIC_PIN_CODE</parameter>
-        	<parameter type="state" subtype="default">PRESS_LOCK</parameter>
 		</channel>
 		<!-- User 6 unlock -->
 		<channel type="ACCESS_TRANSCEIVER" version="2" index="12" maxLinks="10" >
 			<parameter type="config" subtype="16channels_12">ABORT_EVENT_SENDING_CHANNELS</parameter>
-        	<parameter type="state" subtype="default">PRESS_UNLOCK</parameter>
 		</channel>
 		<!-- User 7 lock -->
 		<channel type="ACCESS_TRANSCEIVER" version="2" index="13" maxLinks="10" >
 			<parameter type="config" subtype="16channels_13">ABORT_EVENT_SENDING_CHANNELS</parameter>
 			<parameter type="config" subtype="default">NUMERIC_PIN_CODE</parameter>
-        	<parameter type="state" subtype="default">PRESS_LOCK</parameter>
 		</channel>
 		<!-- User 7 unlock -->
 		<channel type="ACCESS_TRANSCEIVER" version="2" index="14" maxLinks="10" >
 			<parameter type="config" subtype="16channels_14">ABORT_EVENT_SENDING_CHANNELS</parameter>
-        	<parameter type="state" subtype="default">PRESS_UNLOCK</parameter>
 		</channel>
 		<!-- User 8 lock -->
 		<channel type="ACCESS_TRANSCEIVER" version="2" index="15" maxLinks="10" >
 			<parameter type="config" subtype="16channels_15">ABORT_EVENT_SENDING_CHANNELS</parameter>
 			<parameter type="config" subtype="default">NUMERIC_PIN_CODE</parameter>
-        	<parameter type="state" subtype="default">PRESS_LOCK</parameter>
 		</channel>
 		<!-- User 8 unlock -->
 		<channel type="ACCESS_TRANSCEIVER" version="2" index="16" maxLinks="10" >
 			<parameter type="config" subtype="16channels_16">ABORT_EVENT_SENDING_CHANNELS</parameter>
-        	<parameter type="state" subtype="default">PRESS_UNLOCK</parameter>
 		</channel>
 		
 		<channel type="ALARM_COND_SWITCH_TRANSMITTER" version="1" index="17" maxLinks="8" />
```

Dann besteht wohl doch Hoffnung das mit dem morgigen nightly snapshot die `PRESS_LOCK`/`PRESS_UNLOCK` conditions auftauchen werden in der WebUI. Muss ich nur nochmal klären welche der beiden HMIPServer nun definitiv der aktuellere ist und es nicht dazu kommt das dann am Schluss beim nächsten Update auch die CCU3 Nutzer beschnitten werden.

Bin ich also gespannt was dann morgen die HmIP-WKP Nutzer hier berichten werden.

**Comment by nemex** [comment]
Gerade von einem anderen User mit Orig. CCU3 bekommen

![FB_IMG_1654019226756.jpg](https://user-images.githubusercontent.com/5516018/171251965-a16af23b-faa2-401f-9611-2c66a4953c34.jpg)

**Comment by nemex** [comment]
@jens-maus 

Warum eigentlich erst morgen?

also ich habe jetzt die Version 531 drauf.
![Screenshot_20220531_212742_com.android.chrome.jpg](https://user-images.githubusercontent.com/5516018/171269627-b84ffc6f-37d4-47ff-9edb-488fb1e7e2e4.jpg)

 leider keine Änderung. Ich habe das WKP neu angelernt. Und es wird nur kanal 0 angeboten. 

![Screenshot_20220531_212917.jpg](https://user-images.githubusercontent.com/5516018/171269802-a5d894ac-471b-4da3-8a79-d4c6afbdb298.jpg)

**Comment by jp112sdl** [comment]
> Warum eigentlich erst morgen?

@nemex Weil dann die heute durchgeführten Änderungen durch den nächtlichen Bau-Automaten in den Snapshot-Build eingebaut werden. Und der steht erst morgen zur Verfügung. Also nix 0531... erst 0601

**Comment by nemex** [comment]
> > Warum eigentlich erst morgen?
> 
> @nemex Weil dann die heute durchgeführten Änderungen durch den nächtlichen Bau-Automaten in den Snapshot-Build eingebaut werden. Und der steht erst morgen zur Verfügung. Also nix 0531... erst 0601

Ahhh danke für die Erklärung. Dann doch morgen😅

**Comment by nemex** [comment]
Einen wunderschönen guten morgen. So Version 601 erfolgreich installiert und siehe da es funktioniert 😁

![IMG-20220601-WA0000_edit_1259642381384874.jpg](https://user-images.githubusercontent.com/5516018/171332250-81f14a21-7ae6-495f-834c-aa8dbd4e61cd.jpg)

**Comment by mifricke** [comment]
Das sind ja gute Nachrichten. Musste das Keypad neu angelernt werden? Sitze gerade viele km entfernt und hätte mit dem anlernen für einen Test gerade so meine Probleme.

**Comment by nemex** [comment]
> Das sind ja gute Nachrichten. Musste das Keypad neu angelernt werden? Sitze gerade viele km entfernt und hätte mit dem anlernen für einen Test gerade so meine Probleme. 

Achso nein ich musste es nicht neu anlernen.

**Comment by jp112sdl** [comment]
Dann fehlen ja nur noch die Übersetzungen für `PRESS_[UN]LOCK`

**Comment by mifricke** [comment]
Aber die fehlen auf der original CCU3 ja auch, oder? Hat EQ3 das vergessen, oder ist es vielleicht überhaupt nicht gewollt, dass diese Bedingung ausgewählt werden kann?

Grundsätzlich ist das keypad ja auch ohne die PRESS_[UN]LOCK Bedingung voll Funktionsfähig. Das ist ja eher ein Schönheitsfehler als wirklich relevant für den Betrieb.

**Comment by nemex** [comment]
> Aber die fehlen auf der original CCU3 ja auch, oder? Hat EQ3 das vergessen, oder ist es vielleicht überhaupt nicht gewollt, dass diese Bedingung ausgewählt werden kann?
> 
> Grundsätzlich ist das keypad ja auch ohne die PRESS_[UN]LOCK Bedingung voll Funktionsfähig. Das ist ja eher ein Schönheitsfehler als wirklich relevant für den Betrieb.

Also ich finde schon das es relevant ist für den Betrieb. Sonst arbeitet das Keypad ja nur im Toggelbetrieb. Es wäre schon wichtig auf Lock oder Unlock regieren zu können. Voll funktionsfähig wäre es für mich so nicht.

**Comment by Alexxx2005** [comment]
Ok , ja sowas dachte ich mir schon aber ich find irgendwie nicht wo ich die Programmversionen in der Raspberrymatic einstellen kann

**Comment by mifricke** [comment]
Das ist ein sicheres Zeichen dafür, dass du nicht ganz die Zielgruppe für Entwicklungsversionen bist! 🙃

**Comment by volbrene** [comment]
@jens-maus Vielen Dank für die mühe! Wann wird die stable Version erwartet?

**Comment by volbrene** [comment]
Ok, schade, dass es noch so lange dauert. Ich werde diesen Aktor einfach zurücksenden und es anders lösen. Trotzdem danke :)

**Comment by jens-maus** [comment]
> Ok, schade, dass es noch so lange dauert.

Lange? Wow, Ihr Nutzer seid schon ganz schön verwöhnt inzwischen muss ich sagen. Aber wenn du nicht warten kannst oder willst, dann nimm halt auf eigene Gafhr hin einen aktuellen nightly snapshot (siehe https://github.com/jens-maus/RaspberryMatic/releases/tag/snapshots) - beschwer dich dann aber nicht wenn dir alles andere dann um die Ohren fliegt :)

**Comment by mbhomie007** [comment]
Hier auch nochmal meine verspätete Rückmeldung, dass das Keypad mit dem Nightly Build/Testversion 3.63.9.20220601-9bd32be einwandfrei funktioniert und die Kanäle alle nun als Bedingung auswählbar sind.
Viele Dank für den Fix! 🎉🎉🎉

**Comment by mifricke** [comment]
Eine kleine Ungereimtheit in der WebUI zu dem Thema habe ich gerade noch entdeckt. Vielleicht kann das mal jemand gegenprüfen:

<img width="920" alt="image" src="https://user-images.githubusercontent.com/5204755/172045059-41e417f3-108e-443c-980f-94b3e01c6428.png">

Wie man sieht, ist die "Wenn" Bedingung jeweils leicht unterschiedlich. Legt man die Bedingung des jeweiligen Keypad Kanals direkt an, kann man "bei Änderung auslösen" und "nur prüfen" nicht auswählen. Das mag für das Keypad auch korrekt sein. 
Lege ich die Wenn Bedingung allerdings vorher für ein anderes Gerät an und tausche das Gerät nachträglich aus, wird die Auswahlmöglichkeit beibehalten. Das macht dan dieser Stelle dann keinen Sinn mehr.

**Comment by jens-maus** [comment]
> Eine kleine Ungereimtheit in der WebUI zu dem Thema habe ich gerade noch entdeckt.

Das gehört hier (in dieses Ticket/Issue) nicht her weil nicht teil der Problembeschreibung! Bitte nicht einfach diesen Thread kapern, sondern erst einmal in einem Diskussionsforum dazu diskutieren/analysieren. Ticket/Issue-System ist Ticket/Issue-System, Diskussionsforum ist Diskussionforum.
