### ISSUE TITLE
Einstellungen > Geräte --> Spalte: Interface/Kategorie --> "Zuordnung" verschwindet nach editieren von Geräteparametern

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1848]
### Describe the issue you are experiencing

Filtert man seine Geräteliste (Einstellungen > Geräte) nach Interface/Kategorie und ändert dann etwas in den Einstellungen eines Gerätes aus dieser Kategorie ist es abschließend nicht mehr aufgelistet.
Genauer gesagt ist die Interface/Kategorie Spalte dann bei diesem Gerät leer und dementsprechend fällt es aus dem Filter-Raster.

### Describe the behavior you expected

Die Spalte "Interface/Kategorie" sollte niemals leer sein sondern immer das entsprechende Interface anzeigen. 

### Steps to reproduce the issue

1. siehe Screencam
2.
3.
...

### What is the version this bug report is based on?

3.63.9.20220521

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
-
```

### Additional information

- die Spalte "Interface/Kategorie" wird erst nach Browser-Refresh (F5) bzw. nach aus/einloggen wieder gefüllt

verschwundenes Gerät dank "Interface-Filter":
![GIF 24 05 2022 16-22-41](https://user-images.githubusercontent.com/54898249/170061021-d6a24671-e117-4b18-bd1f-fa4aad415ed5.gif)

verschwundene Interface Zuordnung:
![GIF 24 05 2022 16-34-19](https://user-images.githubusercontent.com/54898249/170061847-7f69b5eb-666d-4813-9e56-4c994737061f.gif)

**Comment by jp112sdl** [comment]
Interessant, dass das noch niemandem vorher aufgefallen ist.
Der Bug besteht seit `0161-WebUI-Add-ShowRFGatewayInDeviceList`.

Da fehlt das Setzen des `interface_displayname`, wenn nur ein Gerät (und nicht die gesamte Liste) aktualisiert wird.

**Comment by Baxxy13** [comment]
Das fiel ja tatsächlich nur "direkt" auf wenn man die entsprechende Filterung genutzt hat. 
Wenn ich mir Screenshots aus dem Forum so ansehe nutzt wohl kaum jemand die Filter.
Ich nutze das häufig und war letztens echt erschrocken (Interface+Namensfilter) das das Gerät auf einmal "weg" war.
