### ISSUE TITLE
Lost connection to CCU2 LANGW since update to 3.63.9.20220521

### ISSUE THREAD

**Issue by martinroehder** [jens-maus/RaspberryMatic#1851]
### Describe the issue you are experiencing

Since the update to 3.63.9.20220521 from 3.59.6.20210703 the connection to a CCU2 LANGW is not possible anymore. Downgrading to 3.59.6.20210703 brings back the connection.

### Describe the behavior you expected

CCU should connect to CCU2 LANGW like before.

### Steps to reproduce the issue

1. Setup CCU2 LANGW in Raspberry Matic 3.59.6.20210703
2. Update Raspberry Matic to 3.63.9.20220521
3. Check connectivity to CCU2 LANGW

### What is the version this bug report is based on?

3.63.9.20220521

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?
Same errors are present in both versions
```txt
May 29 08:36:13 homematic-raspi user.info root: Updating RF Lan Gateway Coprocessor Firmware
May 29 08:36:13 homematic-raspi user.debug update-coprocessor: firmware filename is: coprocessor_update_hm_only.eq3
May 29 08:36:13 homematic-raspi user.info update-coprocessor: performGatewayCoproUpdate(): updating CCU2GW0001
May 29 08:36:15 homematic-raspi user.err update-coprocessor: Could not find gateway by unicast with ip 10.55.5.224. Trying search by serial number.
May 29 08:36:23 homematic-raspi user.err update-coprocessor: Could not find Lan Gateway using ip and serial number
May 29 08:36:23 homematic-raspi user.err update-coprocessor: UnifiedLanCommController::connect(): Unable to connect.
May 29 08:36:23 homematic-raspi user.err update-coprocessor: Could not connect to Lan Gateway ip: 10.55.5.224.
May 29 08:36:23 homematic-raspi user.info root: Updating RF Lan Gateway Firmware
May 29 08:36:23 homematic-raspi user.info update-lgw-firmware: LAN Gateway Firmware Update...
May 29 08:36:23 homematic-raspi user.info update-lgw-firmware: Gateway CCU2GW0001
May 29 08:36:25 homematic-raspi user.err update-lgw-firmware: Could not find gateway by unicast with ip 10.55.5.224. Trying search by serial number.
May 29 08:36:33 homematic-raspi user.err update-lgw-firmware: Could not find Lan Gateway using ip and serial number
```

**Comment by ajscat** [comment]
The problem still exists with version 3.65.6.20220723. Same errors

**Comment by jp112sdl** [comment]
> Same errors are present in both versions

Hi, AFAIK are these messages ignorable, because the builtin update process cannot (even try) to update a "homebrew gateway". IMHO, this applies to all `hmlangw`-based gateways.

**Comment by ajscat** [comment]
Yes that is correct these messages can bei ignored. I could not get connected to the HM-LGW-O-TW-W Gateway after updating to > 3.63.9.20220430. After downgrade it worked again

**Comment by ajscat** [comment]
HMW-LGW-O-DR-GS-EU is also affected by this

**Comment by friedpa** [comment]
I am running 3.65.6.20220723 and I cannot reproduce it with my CCU2 LANGW, but my RPM (RPi 3+) Gateway loses now the connection almost every day, it starts with a connection loss, which obviously can be established again, and continuous until the connection is finally broken ... maybe there is something, which is related to the error above. If necessary, I can provide Logs.
e.g. WhatsApp Bot Messages:

![grafik](https://user-images.githubusercontent.com/42890695/182370953-720ebf97-b136-4137-a2d1-bdb96fa93388.png)
