### ISSUE TITLE
Docker-Container ohne privileged Rechte

### ISSUE THREAD

**Issue by timwegenerDE** [jens-maus/RaspberryMatic#1856]
### Describe the solution you'd like

Der Docker-Container erfordert aktuell privileged ausgeführt zu werden. Da dies der Kapselung, den Grundsätzen "least privileges" sowie "zero trust" widerspricht und Durchgriff bis auf das Host-OS ermöglicht würde damit die Sicherheit erhöht werden und z.B. vor Plugins schützen, die sich schädlich verhalten. Der Container sollte nur zugreifen dürfen, worauf er auch zugreifen muss z.B. über die --device Option, siehe auch: https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities

### Describe alternatives you've considered

-

### Is your feature request related to a problem?

-

**Comment by jens-maus** [comment]
Das ist aus verschiedenen Gründen nicht ohne starken Eingriff im Host Betriebssystem möglich. Im Falle von HomeAssistant z.B. - welches ja RaspberryMatic als Addon auch prinzipiell als Docker Container laufen lässt - ist das möglich weil die Entwickler vom HomeAssistantOS in verschiedenen Schritten bei AppArmor und CGroups Einstellungen des Betriebssystems mit offiziellen Methoden so eingegriffen haben, das der RaspberryMatic Docker Container trotz non-priviledged dann z.B. seine notwendigen Kernel module selbst laden lassen kann (welche für die GPIO/USB HomeMatic Funkmodule notwendig sind) und auch device nodes anlegen kann usw. was normalerweise im non-privileged mode nicht möglich ist.

Dies alles müsste man jetzt bei allen möglichen anderen Linux-basierten Betriebssystemen (Debian, RaspberryPiOS, etc.) nachbilden, welches ein recht großer Aufwand darstellt. Deshalb existiert hier einfach momentan die Limitation, das wenn man RaspberryMatic als Docker Container unter einem generischen Linux-System einsetzen will, das man dann eben diesen privileged betreiben muss.

Deshalb ist hier der bevorzugte Weg momentan eben am besten auf HomeAssistantOS zu wechseln, da hier alle die besagten Gegebenheiten direkt integriert sind, die es ermöglichen RaspberryMatic mit all seinen Geräte- und Kernelmoduldependencies  auch non-privileged laufen zu lassen. Oder aber jemand setzt sich hin und bildet genau all diese besagten AppArmor, CGroups, etc. Einstellungen für die allgemeinen Betriebssysteme nach damit der RaspberryMatic Docker Container auch non-privileged laufen gelassen werden kann.

**Comment by timwegenerDE** [comment]
Ich weiss nicht, ob ich mich dazu in er Lage fühle. Außer den Capabilities in der Apparmor (s. unten) kann ich da wenig rauslesen.

`capability setgid,
  capability setuid,
  capability dac_override,
  capability ipc_lock,
  capability sys_admin,
  capability sys_module,
  capability sys_nice,
  capability sys_rawio,
  capability sys_resource`
  
Grundsätzlich startet der Container ohne privileged Rechte mit o.a. Capabilities und ich kann mich da jetzt durchtesten, bis das Log gut / besser aussieht… Aber ob das irgendjemandem hilft sei mal dahin gestellt.
