### ISSUE TITLE
Konfig daten können nicht gesendet werden HA mit Raspmatic

### ISSUE THREAD

**Issue by sven34466** [jens-maus/RaspberryMatic#1867]
### Describe the issue you are experiencing

es kommt immer zu einen Kommunikation Störung seit update Stick hat auch update auf 4.18

### Describe the behavior you expected

Konfiguration übertragen

### Steps to reproduce the issue

1.ändern der Konfig
2. senden 
3.
...

### What is the version this bug report is based on?

3.63.9.20220625

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
kann ich nicht beurteilen
```

**Comment by jens-maus** [comment]
Das Problem lässt sich hier nicht reproduzieren. Alles funktioniert (auch bei anderen Nutzern) problemlos. Daher bitte zuerst das Problem in einem Forum entsprechend erörtern und dann ggf. wieder hierher kommen wenn Konsens unter > 1 Nutzern besteht das hier ein Problem existiert und man mehr technische Zusatzinfos liefern kann als nur "geht nicht".
