### ISSUE TITLE
WebUI Home Assistant Add-on: HomeMatic lässt sich nicht öffnen

### ISSUE THREAD

**Issue by FG148** [jens-maus/RaspberryMatic#1868]
### Describe the issue you are experiencing

Hallo zusammen, 
ich versuche auf Rasperry Matic zu wechseln und meine Konfiguration mit der Backup-Routine zu sichern. Nachdem ich das Home Assistant Add-on HomeMatic hierzu auf die neueste Version aktualisiert habe (99.0.5) kann ich die WebUI nicht mehr öffnen. (Die Homematic CCU ist noch nicht bereit Bitte warten. Sie werden automatisch auf die Startseite weitergeleitet.)

Die Steuerung von Home-Assistant funktioniert noch einwandfrei. Neustart etc. hatte auch keinen Effekt.

In den Logs wird fleissig versucht die Seite aufzurufen (172.30.32.2 - - [29/Jun/2022:21:01:50 +0200] "GET /ise/checkrega.cgi HTTP/1.1" 200 35 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0")

Ist das ein bekanntes Problem, oder gibt es ein Skript mit dem man die Backup-Datei erstellen kann?
Vielen herzlichen Dank schon einmal!

### Describe the behavior you expected

Öffnen der WebUI ohne Probleme

### Steps to reproduce the issue

1. Öffnen WebUI aus Home-Assistant
2.
3.
...

### What is the version this bug report is based on?

99.0.5

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
172.30.32.2 - - [29/Jun/2022:21:01:13 +0200] "GET /ise/checkrega.cgi HTTP/1.1" 200 35 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0"
172.30.32.2 - - [29/Jun/2022:21:01:16 +0200] "GET /ise/checkrega.cgi HTTP/1.1" 200 35 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0"
172.30.32.2 - - [29/Jun/2022:21:01:19 +0200] "GET /ise/checkrega.cgi HTTP/1.1" 200 35 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0"
172.30.32.2 - - [29/Jun/2022:21:01:23 +0200] "GET /ise/checkrega.cgi HTTP/1.1" 200 35 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0"
172.30.32.2 - - [29/Jun/2022:21:01:26 +0200] "GET /ise/checkrega.cgi HTTP/1.1" 200 35 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0"
2022-06-29 21:01:27,794 [INFO] DeviceBackgroundUpdateSubsystem - SYSTEM: 0 Accesspoints in Queue
2022-06-29 21:01:27,794 [INFO] DeviceBackgroundUpdateSubsystem - SYSTEM: Permanent-/Burstlistener Handler utilization: 0/50 used
2022-06-29 21:01:27,794 [INFO] DeviceBackgroundUpdateSubsystem - SYSTEM: Eventlistener Handler utilization: 0/50 used
172.30.32.2 - - [29/Jun/2022:21:01:29 +0200] "GET /ise/checkrega.cgi HTTP/1.1" 200 35 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0"
172.30.32.2 - - [29/Jun/2022:21:01:32 +0200] "GET /ise/checkrega.cgi HTTP/1.1" 200 35 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0"
```

**Comment by jens-maus** [comment]
> ich versuche auf Rasperry Matic zu wechseln und meine Konfiguration mit der Backup-Routine zu sichern. Nachdem ich das Home Assistant Add-on HomeMatic hierzu auf die neueste Version aktualisiert habe (99.0.5) kann ich die WebUI nicht mehr öffnen. (Die Homematic CCU ist noch nicht bereit Bitte warten. Sie werden automatisch auf die Startseite weitergeleitet.)

Tut mir leid, aber das ist wohl ganz offensichtlich ein Problem des alten, obsoleten Homematic Addon von Home Assistant selbst. Gehört hier also nicht her sondern entsprechend an der richtigen Stelle gegenüber dem Homematic Addon Projekt reported.

**Comment by jens-maus** [comment]
Da Issue Ticket hier ist geschlossen. Es geht hier alao nicht weiter. Auch ist daa ein bug/issue tracker und kein support forum. Also bitte est entsprechend in einem Forum diskutieren und dann ein problem melden.
