### ISSUE TITLE
Falmot-c12 config nach reboot gelöscht, auch in Backup nicht vorhanden

### ISSUE THREAD

**Issue by manna57** [jens-maus/RaspberryMatic#1869]
### Describe the issue you are experiencing

Any time, after reboot, update.. etc. the config of my Falmot-c12 is no more available.
Even in backup, when loaded the config of the Falmot is not 
reloaded.

Falmot Hardware checked by service
System Layout
System Raspberry 4
Build 3.63.9.20220625
16Gb sad
256gb ssd 

### Describe the behavior you expected

Config stay in after reboot, or be reloaded by backup

### Steps to reproduce the issue

1. reboot
2. reload backup
4. 
5.
6.
...

### What is the version this bug report is based on?

3.63.9.20220625

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
No
```

### Additional information

Config file too big for upload(28mb)

**Comment by jens-maus** [comment]
Sorry, but this must be a local problem and not a general issue. I have a FALMOT-C12 myself and it is working without any issues with the latest RaspberryMatic version. So please report/discuss your issues in a discussion fora first and do not immediately report this as an issue in RaspberryMatic if you are unsure if this isn't just an issue in your local installation. So please try to get this reproduced with > 1 users and then you can come back here.

**Comment by manna57** [comment]
Thx Jens for the quick response.
Sorry, but I already checked a lot of things, forum, how check by elv and waited for 2 new releases of firmware for the raspberry 4 hoping that this would fix the problem.
Now I will Setup the raspberry from scratch, hoping that this will fix my problem.

Mit freundlichen Grüßen
Michael Anna
+49 152 22715294
