### ISSUE TITLE
Saving weekday program for (e.g. HMIP-BROLL) doesn't work

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#187]
When trying to save the weekday program of e.g. a HMIP-BROLL device saving the settings doesn't work and never finishes.

After some investigation (see https://homematic-forum.de/forum/viewtopic.php?f=60&t=39501&p=398020#p398020) it seems that the reason seems to be that the maximum request header size results in the following lighttpd error messages to appear in `/var/log/lighttpd-error.log`:

```
2017-11-13 09:16:02: (connections.c.906) oversized request-header -> sending Status 431 
```

After some more investigation it seems that this issues is caused due to modified max request header size setting in newer lighttpd versions (>= 1.4.43). (see https://redmine.lighttpd.net/issues/2130). Thus, lighttpd >= 1.4.43 limits request header size to 8k now which is substantially smaller than what seems to be required to save the weekday programs in devices like the HMIP-BROLL via the `ic_ifacecmd.cgi` interface.

**Comment by sanoi** [comment]
@jens-maus I still have this issue, not sure why. I am using latest raspberrymatic HA addon. When I change other values for HMIP-BROLL, it is working after change weekly program and press apply, it shows 'please wait' popup forever and not transfer the data. Any help?
