### ISSUE TITLE
Systemvariable Energiezähler

### ISSUE THREAD

**Issue by Bono1969** [jens-maus/RaspberryMatic#1870]
### Describe the solution you'd like

Wenn bei einem Gerät welches einen Energiezähler besitzt (zB. HmIP-FSM16) und beim anlegen des Gerätes die Option "Kanäle umbenennen" inkl. eigener Namen, dann sollte auch die automatisch angelegte Systemvariable umbenannt werden.

### Describe alternatives you've considered

nichts ändern

### Is your feature request related to a problem?

kein Problem, nur eine Tätigkeit die jetzt manuell gemacht werden muss.

### Additional information

mein System: Homeassistant aktuelle Version mit RaspberryMatic (3.63.9.20220625).

**Comment by jens-maus** [comment]
Bitte konkret werden und ein Beispiel zeigen. Von welcher "anlegte Systemvariable" sprichst du? Beispiele und mehr detaillierte Beschreibungen bitte.

**Comment by Bono1969** [comment]
![Gerätekanal](https://user-images.githubusercontent.com/37637519/176618987-4b89d38d-e612-45e5-ac18-0c5c00379e23.PNG)
Dies ist der Kanal des Gerätes (welcher schon mit der Funktion "Kanäle umbenennen" richtig benannt ist.
![Systeminterne Variable](https://user-images.githubusercontent.com/37637519/176619312-72cc8d65-13b1-41be-8b75-33987b8bb08b.png)
So sieht die Systeminterne Variable aus.

**Comment by jens-maus** [comment]
Und wo genau soll jetzt bitte etwas anders umbenannt werden?!?

**Comment by Bono1969** [comment]
Der Name, analog wie beim Gerät.

**Comment by jens-maus** [comment]
> ![Energiezähler](https://user-images.githubusercontent.com/37637519/176622155-8ce3329f-7d1b-4ebf-838f-d2d93ddeb8b6.PNG) Ja, und das sieht dann so aus. Die Angabe der Einheit wäre auch Sinnvoll.

Ich sagte doch: Diese sind IMHO **nicht** für den eigenen Gebrauch bzw. separate Anzeige gedacht und genau deshalb ja als "systemintern" markiert. Wenn ein Nutzer diese Werte selbst anzeigen wiederverwenden will muss/sollte er eine eigene Systemvariable mit eigener Benennung dafür anlegen die diese Werte selbst dann trägt oder eigene berechnungen stattfinden lassen oder eben mit dieser Benennung leben. von einer eigenen Umbenennung kann ich hier nur abraten, da das ggf. gewisse negative Effekte hervorrufen kann.
