### ISSUE TITLE
HomeAssistant HMIP Server startet nicht

### ISSUE THREAD

**Issue by smoki3** [jens-maus/RaspberryMatic#1873]
### Describe the issue you are experiencing

Hi,

ich habe das Problem, dass bei meiner HA Installation der HMIP Server nicht startet. Nutze ich allerdings den letzten Snapshot build started er erfolgreich.

Ich habe einer Supervisor Installation. Alle Versionen sind aktuell.

```

Update-Channel | stable
Supervisor-Version | supervisor-2022.06.2
Agent-Version | 1.2.2
Docker-Version | 20.10.17
Speicherplatz gesamt | 58.4 GB
Speicherplatz genutzt | 7.4 GB
Gesund | true
Unterstützt | true
Supervisor-API | ok
Versions-API | ok
Installierte Add-ons | Terminal & SSH (9.4.0), RaspberryMatic CCU (snapshot) (3.65.6.20220628-34f28dd), Studio Code Server (5.1.2), Simple Scheduler (0.60), Duck DNS (1.15.0), RaspberryMatic CCU (3.63.9.20220625)


````

### Describe the behavior you expected

HMIP Server startet

### Steps to reproduce the issue

1. Start Addon

### What is the version this bug report is based on?

3.63.9.20220625

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Mounting /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying host system: oci, OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.2, OK
Identifying Homematic RF-Hardware: ....HmRF: RPI-RF-MOD/GPIO@fe201000.serial, HmIP: RPI-RF-MOD/GPIO@fe201000.serial, OK
Updating Homematic RF-Hardware: RPI-RF-MOD: 4.4.22, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: .OK
Starting rfd: .OK
Starting HMIPServer: .......................................................................................................................................................ERROR
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.63.9.20220625 (raspmatic_oci_arm)
```

**Comment by jens-maus** [comment]
Verstehe ich das richtig? Mit dem aktuellen development snapshot (3.65.6.20220628-34f28dd) funktioniert es, nur mit dem aktuellen stable release nicht?

**Comment by smoki3** [comment]
ja genau  

mit dem Snapshotbuild:

```
Mounting /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying host system: oci, OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.1, OK
Identifying Homematic RF-Hardware: ....HmRF: RPI-RF-MOD/GPIO@fe201000.serial, HmIP: RPI-RF-MOD/GPIO@fe201000.serial, OK
Updating Homematic RF-Hardware: RPI-RF-MOD: 4.4.22, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: .OK
Starting rfd: .OK
Starting HMIPServer: .............OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.65.6.20220628 (raspmatic_oci_arm64)
```

**Comment by jens-maus** [comment]
Na dann ist doch alles gut prinzipiell, denn der Snapshot wird ja die nächste Stable version werden. Wäre jetzt mühselig bei der älteren Verison zu schauen was da ggf. schief läuft nur um dann festzustellen das mit der nächsten version alles klappt.

Das einzige was mich jetzt aber noch verwirrt ist folgendes:

```
Finished Boot: 3.63.9.20220625 (raspmatic_oci_arm)
````

vs.

```
Finished Boot: 3.65.6.20220628 (raspmatic_oci_arm64)
```

Ich kann mir gerade nicht erklären warum hier 1x `raspmatic_oci_arm` und bei dem snapshot `raspmatic_oci_arm64` ausgegeben wird. Bist du wirklich sicher das das auf der selben hardware betrieben wird? normalerweise sollte (wenn dein host ein arm64 system ist auch bei der stable version `raspmatic_oci_arm64` ausgegeben werden.

**Comment by smoki3** [comment]
Ja generell läuft alles soweit. 

Ja ist der selbe Host. Läuft alles auf einem Raspberry und einer Homeassistent Installation

**Comment by Baxxy13** [comment]
Nur als Information:
Unter Homeassistant-OS werden die Stable 3.63.9.20220625, sowie der Nightly 3.65.6.20220705-f6a956 auf einem Pi4B als
raspmatic_oci_arm64 gebootet.

**Comment by smoki3** [comment]
Bleiben noch irgendwelche Reste stehen, wenn ich das addon nur über den deinstallationsbutton entferne? Oder gibt es eine möglichkeit das addon auf arm64 zu zwingen?

**Comment by jens-maus** [comment]
Nein, gibt es nicht. Du kannst in der Tat probieren das nicht-snapshot Addon komplett entfernen/löschen und dann neu installieren und schauen ob dann die arm64 variante danach bootet.

**Comment by smoki3** [comment]
das habe ich schon mehr mals versucht. leider hat das nichts gebracht

**Comment by jens-maus** [comment]
Dann müsstest du mal die HA Logfiles durchsuchen warum er beim installieren meint er muss die non-arm64 variante installieren... hab ich so noch nicht gesehen in der Tat.

**Comment by smoki3** [comment]
So jetzt habe ich das geschafft was ich nicht wollte. Hatte nun Release und Snapshot entfernt. Nun sind beide non-arm64 und funktionieren nicht mehr

**Comment by jens-maus** [comment]
Das ist in der Tat komisch und sollte nicht passieren. Ich probiere mal ob ich das reproduziert bekomme

**Comment by jens-maus** [comment]
Allerdings bräuchte ich mehr Infos dazu wie du HomeAssistant genau installiert hast. Nutzt due HomeAssistantOS oder betreibst du das "Supervised"? Welche HomeAssistantOS version nutzt du, welche Supervisor version, etc. etc.

**Comment by smoki3** [comment]
Das ist ein Auszug meiner Installation: Es handelt sich um das Supervised.


## System Health

version | core-2022.7.0
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.32-v8+
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4942
Installed Version | 1.25.5
Stage | running
Available Repositories | 1073
Downloaded Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 21. Juli 2022 um 02:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-west-2-3.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2022.07.0
agent_version | 1.2.2
docker_version | 20.10.17
disk_total | 58.4 GB
disk_used | 7.9 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.6.0), Studio Code Server (5.1.2), Simple Scheduler (0.60), Duck DNS (1.15.0), RaspberryMatic CCU (3.63.9.20220625)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 1
views | 11
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 28. Juni 2022 um 07:26
-- | --
current_recorder_run | 7. Juli 2022 um 09:25
estimated_db_size | 43.57 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

**Comment by smoki3** [comment]
Ich konnte das problem nun temporär lösen:

Ich habe die Docker Images manuell mit ```Docker rmi``` entfernt

Dann habe ich sie manuell mit ``` docker pull ghcr.io/jens-maus/raspberrymatic:3.63.9.20220625@sha256:80ccb61c9e779e228e6760b03010b144af8e00f6495b069be890b6539e5a25c2```
neu geladen.

nun habe ich ```Finished Boot: 3.63.9.20220625 (raspmatic_oci_arm64)``` und auch der HMIP Server started. 

Allerding nach einem update oder neu installation zieht er wieder die non arm64 version. Woher holt er diese information?

**Comment by jens-maus** [comment]
> Allerding nach einem update oder neu installation zieht er wieder die non arm64 version. Woher holt er diese information?

Tja, das kann ich dir leider auch nicht beantworten. Das müsstest du mit den HA Entwicklern klären. Aber auch dieses Problem zeigt nun wohl das der Betrieb einer HA Supervised Installation nicht wirklich das gelbe vom Ei ist und man wirklich besser daran ist doch gleich auf "HomeAssistant OS" als Basisplatform seiner HA Installation zu setzen. Das läuft einfach viel runder und ist auch von den HA Entwicklern viel stärker getestet als diese Krücke von HA Supervised unter einem beliebigen Linux OS. Ich würde dir also definitiv dazu raten doch mal zu überlegen nicht doch einfach HomeAssistantOS einzusetzen und zur not darin dann ein zusätzliches dockerisiertes LinuxOS laufen zu lassen um allgemeine Funktionen zu haben, als es anders herum zu betrieben mit diesen und anderen bekannten Limitationen/Problemen.

**Comment by smoki3** [comment]
Ich bin den Problem auf die Schliche gekommen.

Seltsamer weise hat die GUI aarch64 angezeigt. Habe ich in der Konsole aber ein ```ha info``` eingegeben kam armv7

**Comment by jens-maus** [comment]
Ich schätze mal hier kann zugemacht werden weil seit neuem release nicht mehr aktuell/relevant und das hier ist ja auch kein Diskussionsforum.
