### ISSUE TITLE
Using RasbPi4 + HMIP-RFUSB +HIMP-HAP contradictory information in documentation

### ISSUE THREAD

**Issue by Taxxian** [jens-maus/RaspberryMatic#1878]
### Describe the issue you are experiencing

My RaspberryMatic instance seems to be unable to communicate with my HMIP-HAP. It does not bind and it does not register as firmware updatable.

This wiki page:
https://github.com/jens-maus/RaspberryMatic/wiki/Einleitung#voraussetzungen
Lists HMIP-HAP as usable with either or: + RPI-RF-MOD/ HmIP-RFUSB

While this wiki page:
https://github.com/jens-maus/RaspberryMatic/wiki/Tipps
Says I can only use RPI-RF-MOD

I found other sites partly not on this wiki which support one statement or the other.

So can I use the HMIP-HAP + HMIP-RFUSB or not? 

Thanks

PS: I know its not technically a bug, but it seems to me there is wrong information in the documentation. so thats very close to a bug^^

### Describe the behavior you expected

HMIP-HAP does not bind or register as firmware updatable.

### Steps to reproduce the issue

1.
2.
3.
...

### What is the version this bug report is based on?

latest

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
No
```

**Comment by Taxxian** [comment]
I bought it from the eq3 shop and soldered myself so i am quite sure its genuine. Still does not work. Some list which firmware is the newest for any given device would also be helpful. At the moment I am unable to determine if the firmware part fails, or if there simply is no newer firmware and just the binding part fails...

**Comment by jens-maus** [comment]
When booting with the stick connected RaspberryMatic automatically flashes the latest firmware to it. So simply have a look at the start log.

**Comment by Taxxian** [comment]
HMIP HAP Firmware: 2.4.24
HMIP RFUSB Firmware: 4.4.18
RaspberryMatic Version: 3.63.9.20220625 (oci)

That is what I have, and it does neither update nor bind. All devices are brandnew, i bound a wall thermostat to check if it works at all, and that does work.

Regards
Martin

**Comment by jens-maus** [comment]
Sorry, but this is no discussion or support fora here, but a bug/issue tracker. However, the "issue" you have brought up here isn't a bug in RaspberryMatic itself but some local issue in your environment like other has before when trying to teach in a HAP.

So please allow me to close this issue and ask you to move the discussion/support problem you have to a proper discussion fora like homematic-forum.de so that you can find a solution there!

**Comment by Baxxy13** [comment]
Es geht um das Homeassistant Add-On.
Da gilt weiterhin... kein HAP, kein DRAP. 
Siehe #1373

**Comment by jens-maus** [comment]
Ah ok, diese wichtig Info (das hier das HomeAssistant Addon verwendet wird) gabs leider ursprünglich nicht bzw habe ich aus dem ticket nicht rauslesen können. Also ja, aktuell geht das leider wegen einer Limitation in HomeAssistant nicht.
