### ISSUE TITLE
Gerätekonfiguration Wochenprogramm HmIP-Broll funktioniert nicht wegen zu vieler Parameter

### ISSUE THREAD

**Issue by Motorpsycho123** [jens-maus/RaspberryMatic#188]
Die Gerätekonfiguration für das Wochenprogramm beim Rollladenaktor HmIP-Broll lässt sich nicht setzen. Wenn man das Programm konfiguriert hat und auf ok klickt, bleit das WebUI beim Fortschrittsbalken endlos stehen und das Wochenprogramm wird auf dem Aktor nicht gesetzt.

Ursache hierfür ist, dass das Wochenprogramm für HmIP-Broll 75 Einträge mit je 9 Werten zulässt, die alle über eine URL an die CCU übergeben werden. Das ist für diese zu lang und sie verweigert den Request mit dem Fehler `"HTTP431: ANFORDERUNGSHEADER ZU GROSS: Der Server verweigert die Verarbeitung der Anforderung, weil ein Headerfeld oder alle Headerfelder zusammen größer sind als vom Server verarbeitet werden können. (XHR)GET - "`

Fehler ist auch hier beschrieben: https://homematic-forum.de/forum/viewtopic.php?f=60&t=39501&start=10#p398020

**Comment by jens-maus** [comment]
Bereits beseitigt: siehe #187

**Comment by Motorpsycho123** [comment]
Ja, gerade schon gelesen. Danke dir.

**Comment by jens-maus** [comment]
Nein, Danke Dir! 👍
