### ISSUE TITLE
Update HmIP-FWI wird nicht ausgeführt

### ISSUE THREAD

**Issue by stmb-100** [jens-maus/RaspberryMatic#1881]
### Describe the issue you are experiencing

Ich versuche das Update auf das HMIP Device zu bekommen.
von Version 1.0.12 nach Version 1.0.14

### Describe the behavior you expected

Das Update wird auf dem Device : HmIP-FWI nicht ausgeführt

An was kann das liegen ?

### Steps to reproduce the issue

1. kopieren der Firmwaredatei über (Geräte Firmware Neu) (1.0.14 min. CU Version 3.61.5) 
2. In der Geräte Firmware Übersicht stehr : Die Updatedatei wird zum Gerät übertragen
3. 3-4 Tage keine Veränderung des Stausses

### What is the version this bug report is based on?

3.63.9.20220625

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
noch keine passendes Logs gefunden
```

**Comment by jens-maus** [comment]
Das ist kein Bug, sondern vollkommen normal. Die Übertragung solcher Gerätefirmwares kann Tage bis Wochen dauern je nachdem wie start das Funkband auf der CCU ausgelastet ist. Einfach laufen lassen und das nächste mal bitte zuerst in einem Forum wie homematic-forum.de nach solchen Dinge fragen/suchen bevor man einen Bugreport aufmacht.
