### ISSUE TITLE
HmIP-SWSD (Rauchmelder): "Weiterleiten von empfangen Datentelegrammen" nicht aktivierbar

### ISSUE THREAD

**Issue by martinpichlo** [jens-maus/RaspberryMatic#1887]
### Describe the issue you are experiencing

Hallo,

ich habe mehrere HmIP-SWSD Rauchmelder im Einsatz. Leider erreichen diese sich nicht durchgängig. Im Channel 1 haben diese die Checkbox "Weiterleiten von empfangenen Datentelegrammen", welche das Problem lösen sollte. Die Checkbox ist per Default inaktiv. Aktiviere ich diese Checkbox und drücke Übernehmen, wird die erfolgreiche Datenübertragung per Popup bestätigt. Schließe ich dieses Popup mit ok wieder, ist die Checkbox wieder inaktiv.

Auf Nachfrage bei ELV wurde mir gesagt, dass dieses Verhalten in der Testumgebung nicht nachgestellt werden könne. Ich habe leider keine Chance, dass mit einer physischen CCU zu bestätigen oder zu widerlegen. Kann das Verhaltet tatsächlich einzig ein Bug in RasbberryMatic sein?

Gibt es irgendwelche Möglichkeiten, wie ich mich der Fehlerursache nähern kann? Ein Fehlerlog vielleicht? Oder eine Chance die individuellen Geräteeinstellungen direkt im Gerät zu lesen oder zu verändern?

System und Firmware:
RasberryMatic als Home Assistant Addon: 3.63.9.20220625
Radiomodule: HB-RF-USB-2
HmIP-SWSD Firmware: 1.0.12 

Danke!
Martin

### Describe the behavior you expected

Ich würde erwarten, dass die aktivierte Checkbox nach dem Übertragen an das Gerät, aktiviert bleibt.

### Steps to reproduce the issue

1. Rauchmelder an CCU anlernen bzw. hinzufügen
2. Status und Bedienung > Geräte > Rauchmelder auswählen > Kanal 1 auswählen
3. Checkbox "Weiterleiten von empfangenen Datentelegrammen" aktivieren
4. Übernehmen klicken
5. Popup mit OK bestätigen
6. Prüfen, welchen Status die Checkbox "Weiterleiten von empfangenen Datentelegrammen hat" (bei mir ist sie erneut inaktiv)

### What is the version this bug report is based on?

3.63.9.20220625

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
can add this, if someone point me out, what is useful
```

**Comment by jens-maus** [comment]
Danke für den Report. Tut mir allerdings leid, ich kann das hier angesprochene Verhalten selbst nicht nachvollziehen. Siehe hier:

![Jul-21-2022 11-42-10](https://user-images.githubusercontent.com/5887769/180183715-4c98588f-e3cc-44da-8b15-f2b1fddcd984.gif)

Das einzige was ich mir vorstellen kann ist (da du das HomeAssistant Add-on wohl verwendest) das das ein ähnlicher Bug wie https://github.com/jens-maus/RaspberryMatic/issues/1418 oder https://github.com/jens-maus/RaspberryMatic/issues/1189 ist bei dem ein Problem bei der Nutzung von innerhalb der HomeAssistant Weboberfläche es dazu kommt das manche Geräteparameter nicht übertragen werden können. Das mündete dann z.B. in folgendem HomeAssistant Supervisor Ticket (https://github.com/home-assistant/supervisor/issues/3737) das leider immer noch nicht fertig bearbeitet wurde von den HA Entwicklern.

Was du ggf. probieren kannst ist, einmal Port 80 vom Add-on auf Port 8080 oder so umzuleiten und dann auf das direkte Webinterface vom RaspberryMatic CCU Add-on zuzugreifen ohne das das über ingress d.h. innerhalb der HomeAssistant Weboberfläche geroutet wird. Auch solltest du ausschau nach irgendwelchen Browser Consolefehlern halten.

**Comment by martinpichlo** [comment]
Danke für deine schnelle Antwort. Ich habe deinen letzten Tipp als Erstes ausprobiert:

Ich habe die Addon Einstellungen wie folgt geändert:
![settings](https://user-images.githubusercontent.com/32057610/180216806-f675d6a2-370f-4847-b293-231a7f91d809.png)

Leider klappt es auch "außerhalb" von Home Assistent nicht. Fehler in der Browser Console gibt es keine:
![change](https://user-images.githubusercontent.com/32057610/180216809-67ff9a0c-3d11-4a4c-814b-a8391141352b.gif)

Gibt es irgendwelche Ansätze die Fehlerursache einzugrenzen? Wie erkenne ich, ob der Fehler eine ähnliche Ursache wie die von dir genannten Issues haben? Kann ggf. irgendjemand bestätigen, dass es den Fehler auch in anderen HA Addon Instanzen gibt?

Als Workarround: Kann es funktionieren, dass ich ein "standalone" RasberryMatic aufsetze, die Einstellungen per Backup übertrage, die Änderung durchführe und wieder zurück ins Addon portiere?

**Comment by martinpichlo** [comment]
Laut Home-Matic Forum ist dieser Fehler mindestens auch im Release 3.63.8.20220330 aufgetreten.

Ich habe gerade mit dem Nightly 3.65.6.20220721 getestet. Hier funktioniert alles fehlerfrei!

**Comment by jens-maus** [comment]
Ups. Das hab ich selbst so bereits schon selbst reproduziert? Gott bin ich vergesslich geworden. Aber gut, dann ist der Fehler also bereits weg, dann ist ja auch gut. Neue Version wird morgen erscheinen und dann ist das auch abgehakt.
