### ISSUE TITLE
Seit homematic-raspi-3.63.9.20220430 im Email keine richtige Sonderzeichdarstellung

### ISSUE THREAD

**Issue by WernerKr** [jens-maus/RaspberryMatic#1888]
### Describe the issue you are experiencing

Seit dem Update auf homematic-raspi-3.63.9.20220521 und neuer werden beim Email-Empfang die Sonderzeichen nicht 
mehr richtig darstellt. 
Gesendet wird mit E-Mail (jetzt 1.7.4). 

Sonst keine Änderung an dieser Hardware:
CCU Hardware Info
Serial Number:	5A4993E6BE
Hardware Model:	Raspberry Pi 3 Model B Rev 1.2 (rpi3)
CPU / Memory:	Cortex-A53 (4), 955.2M
Storage:	29.7G /dev/mmcblk0
Real-Time-Clock:	rx8130

und ab 24.05. nach Update:
HomeMatic raspi Wetterdaten (24.05.2022, 00:00:00):
AIR Min. Temperatur: 04:43:00 : 10.2 �C 
AIR Max. Temperatur: 17:29:01 : 21.8 �C 
AIR Min. Luftfeuchte: 10:05:01 : 46.7 % 
AIR Max. Luftfeuchte: 05:33:01 : 83.0 % 

Hab überhaupt keine Idee wo ich ansetzen könnte. 

### Describe the behavior you expected

So war es bis 23.05.  (alle Sonderzeichen richtig): 
HomeMatic raspi Wetterdaten (23.05.2022, 00:00:00):
AIR Min. Temperatur: 05:17:00 : 7.6 °C 
AIR Max. Temperatur: 13:15:01 : 21.9 °C 
AIR Min. Luftfeuchte: 13:07:01 : 43.6 % 
AIR Max. Luftfeuchte: 05:55:00 : 85.7 % 

### Steps to reproduce the issue

1. täglich
2.
3.
...

### What is the version this bug report is based on?

3.63.9.20220625 und neuer

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
email.log:
Jul 21 00:00:01 host=securesmtp.t-online.de tls=on auth=on user=werner.krenn@t-online.de from=werner.krenn@t-online.de recipients=check.krenn@t-online.de mailsize=1367 smtpstatus=250 smtpmsg='250 2.0.0 Message accepted. / Nachricht akzeptiert. 1oEHjd-14z3eD@fwd89.t-online.de' exitcode=EX_OK

Auszug: messages
Jul 20 23:09:00 homematic-raspi daemon.info cuxd[786]: rename '/tmp/devlog.txt' -> '/tmp/devlog.txt.0'
Jul 20 23:09:00 homematic-raspi daemon.info cuxd[19549]: move '/tmp/devlog.txt.0' -> '/media/usb0/cuxd/devlog/devlog.txt.20220720-2309'
Jul 21 01:07:00 homematic-raspi daemon.info cuxd[786]: rename '/tmp/devlog.txt' -> '/tmp/devlog.txt.0'
Jul 21 01:07:00 homematic-raspi daemon.info cuxd[31432]: move '/tmp/devlog.txt.0' -> '/media/usb0/cuxd/devlog/devlog.txt.20220721-0107'
Jul 21 03:00:30 homematic-raspi daemon.info cuxd[786]: save paramsets(/usr/local/addons/cuxd/cuxd.ps) size:8882
Jul 21 03:07:53 homematic-raspi daemon.info cuxd[786]: rename '/tmp/devlog.txt' -> '/tmp/devlog.txt.0'
```

**Comment by blackbasket** [comment]
Dazu gibt es auch ein Ticket (28) im hm_email-Projekt...

**Comment by jens-maus** [comment]
Genau da gehört es auch hin und stellt kein Problem in RaspberryMatic dar. Siehe:
https://github.com/homematic-community/hm_email/issues/28
