### ISSUE TITLE
WebUI: Integrate option to redirect plain HTTP to secure HTTPS

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#189]
To improve security (e.g. for passwords to be transferred encrypted) we should consider introducing an option in WebUI where users can force the lighttpd web server to redirect all http requests to Port 80 directly to https (443) requests, potentially also forcing HSTS security (see https://github.com/jens-maus/RaspberryMatic/commit/02d36d28186d1b6fb9ca8dd36920630eea8cc6d2).

**Comment by lampi87** [comment]
Hi!
Any news on this topic? Unfortunately every firmware update overwrites my changes for a http to https redirect.

**Comment by jens-maus** [comment]
Please note that upstream has decided to implement this functionality in version 3.55.x. Thus closing this issue accordingly since this version is already integrated in our master branch.
