### ISSUE TITLE
Node RED Server Connection lost

### ISSUE THREAD

**Issue by stemaka** [jens-maus/RaspberryMatic#1892]
### Describe the issue you are experiencing

In the latest release 3.65.6.20220723 but also in the former 3.63.9.20220625 the server connection in Noder RED gets lost and will not re-connect. Have to revert back to release 3.63.9.20220521 to solve this issue

### Describe the behavior you expected

stable server connection

### Steps to reproduce the issue

1. Open Node RED (https://raspimatic/addons/red/#flow/...)
2. wait 5 sec
3. error message appears, that server connection was lost and will try to re-connect... which fails...
...

### What is the version this bug report is based on?

3.65.6.20220723

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
Don't know what to look for?
Give advice, so I can post.
```

**Comment by Sineos** [comment]
Same setup here. Both mentioned versions are working as intended together with NR

**Comment by jens-maus** [comment]
Sorry, but Node-Red/RedMatic is a third-party addon and not an integral part of RaspberryMatic. So please report issues in using it in the respective project there and not RaspberryMatic.

**Comment by hammerandpick** [comment]
There is a discussion on this Topic over there #1951.
