### ISSUE TITLE
Umlaut-Probleme bei Systemname in WebUI

### ISSUE THREAD

**Issue by Klaus-Lucas** [jens-maus/RaspberryMatic#1897]
### Describe the issue you are experiencing

Du hattest den Bug "Weiterhin Umlaut-Probleme in der WebUI #1821" als erledigt geschlossen.
Ich sehe aber weiterhin in der akt. Version 3.65.6.20220723, dass mein Systemname "Möwenweg" 
als "MÃ¶wenweg 13" dargestellt wird. Gerätenamen mit Umlaute sind kein Problem (mehr).

### Describe the behavior you expected

korrekte Darstellung von Umlauten im Systemnamen

### Steps to reproduce the issue

Um das Nachzuvollziehen, brauchst du nur in den erweiterten Einstellungen den Systemnamen 
mit Umlauten zu schreiben und zu speichern. Dann wieder aufrufen und du siehst dann, dass 
die Umlaute falsch dargestellt werden.

### What is the version this bug report is based on?

3.65.6.20220723

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
nein
```

**Comment by Klaus-Lucas** [comment]
Hallo Jens,

ja.
Wie geschrieben: Gerätenamen mit Umlaute sind kein Problem.
Hatte wegen der damaligen falschen Darstellung von Umlauten alle Gerätenamen mit Umlauten entsprechen geändert (ü->ue..).
Jetzt wieder mit Umlauten geschrieben und sind alle korrekt dargestellt. Überpüft auch bei Verküpfungen und Programmen.


Grüße
Klaus

**Comment by jens-maus** [comment]
> Hallo Jens,
> Grüße Klaus

Ansprachen+Grüße brauch mal hier nicht. GitHub ist eine Entwicklungsumgebung, da wird sich kurz und knapp und technisch orientiert formuliert. Aber soviel nur nebenbei.

> ja. Wie geschrieben: Gerätenamen mit Umlaute sind kein Problem. Hatte wegen der damaligen falschen Darstellung von Umlauten alle Gerätenamen mit Umlauten entsprechen geändert (ü->ue..). Jetzt wieder mit Umlauten geschrieben und sind alle korrekt dargestellt. Überpüft auch bei Verküpfungen und Programmen.

Ok, dann bitte trotzdem weiterhin testen und überall wo es ein Freifeld in der WebUI gibt in dem man auch Texte mit Umlauten versehen kann bitte weiterhin testen und separate Tickets/Issues dazu aufmachen.

**Comment by Klaus-Lucas** [comment]
Ich melde mich nochmal zum obigen Thema. Habe Version 3.67.10.20230114 im Einsatz und finde nur in der Direktverküpfung weiterhin Umlautdarstellungsprobleme in den Feldern "Name" und "Beschreibung":
Hier ist das "ü" ok:
![klu_025](https://user-images.githubusercontent.com/36620907/215588183-274ff843-098e-48e9-84a8-70f4c842765c.jpg)

Hier nicht:
![klu_026](https://user-images.githubusercontent.com/36620907/215588189-d3d9dd7e-ef63-4b9d-ac7a-554b4356fa34.jpg)

Hier mal falsch und mal richtig:
![klu_027](https://user-images.githubusercontent.com/36620907/215588192-e6da6e8d-9b06-4799-bae9-ff4273817f5b.jpg)

In "Außenhaut" wird das ß auch noch anders dargestellt:
![klu_028](https://user-images.githubusercontent.com/36620907/215588197-f88e9238-926c-45dc-9016-bb49eed6ea30.jpg)

**Comment by jens-maus** [comment]
> Ich melde mich nochmal zum obigen Thema. Habe Version 3.67.10.20230114 im Einsatz und finde nur in der Direktverküpfung weiterhin Umlautdarstellungsprobleme...

Auch das ist bereits für die nächste kommende Version gelöst. Siehe #2160
