### ISSUE TITLE
Hardware Support for ROCK64 board

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#190]
To support more 2GB type hardware boards we should evaluate the possibilities to support the ROCK64 board in RaspberryMatic. See here for more information on the board:

https://www.pine64.org/?page_id=7147
https://github.com/ayufan-rock64/linux-build

**Comment by alexreinert** [comment]
I did some research for Rock64 support in piVCCU and found, that the HM-MOD-RPI-PCB will not work with the Rock64:
https://github.com/alexreinert/piVCCU/issues/2

**Comment by jens-maus** [comment]
Thanks for the hint. This is very sad. However, with HmIP-RF-USB coming up soon, there will be a very good alternative for HM-MOD-RPI-PCB together with the old HM-CFG-USB-2 to support HmIP and BidCos-RF at the same time ;)
