### ISSUE TITLE
HMIP Bewegungsmelder mit Taster zeigt in "Status & Bedienung" -> "Geräte" keine bedienbare Taster an

### ISSUE THREAD

**Issue by shinzan111** [jens-maus/RaspberryMatic#1903]
### Describe the issue you are experiencing

In der HomeMatic WebUI wird seid einigen Versionen speziell beim

HMIP SMI55 die Taster nicht mehr angezeigt. (Pfad:  "Status & Bedienung" -> "Geräte" -> HMIP SMI55)
Die Taster der alten HM Bewegungsmelder-Taster werden angezeigt. 
Wäre schon gut, wenn man die Taster der HMIP Bewegungsmelder in der Bedienung auch sehen vs. integrieren könnte.

Danke

### Describe the behavior you expected

the older HM WM55 Sensors are showing 2 switches if you go to "Status & Bedienung" -> "Geräte" -> HM WM55

### Steps to reproduce the issue

1. go to HM WebUI
2. go to "Status & Bedienung"
3. go to "Geräte"
4. choose any "HMIP SMI55" sensor
5. you will see the switches are not appearing vs. don't exists
6. if you choose an older HM WM55 sensor you will see it shows switches

### What is the version this bug report is based on?

3.65.6.20220723 and previous versions

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
not needed as obvious
```

**Comment by Baxxy13** [comment]
Ich sehe hier keinen wirklichen Bug in RaspberryMatic.
IP-Taster können eh nur physisch (direkt am Gerät) betätigt werden. Weder die WebUI noch irgendeine App oder externe Steuerung kann diese "drücken".

Das einzige was man sehen könnte wäre der Zeitstempel "letzte Änderung" wenn die Tasten physisch gedrückt wurden, aber braucht man das?
