### ISSUE TITLE
RM crashes on checkBadBlocks.sh

### ISSUE THREAD

**Issue by fischmir** [jens-maus/RaspberryMatic#1906]
### Describe the issue you are experiencing

RM crahses every night after checkBadBlocks.sh

### Describe the behavior you expected

RM should not crash, instead a "Bad Blocks" Message should appear.

### Steps to reproduce the issue

1. I do not know

### What is the version this bug report is based on?

3.65.6.20220723

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
Logs are not available due to crash.
```

### Additional information

If you want me to reproduce anything, please let me know. Maybe we could the store the log-file somewhere, where it is not deleted?

**Comment by jens-maus** [comment]
If your system crashes after or while a bad block check is performed this is a clear and consistent indication that your sd card/storage has a problem or is broken. The reason why there is no real technical possibility to prevent RaspberryMatic from such hard crashes is, that in such cases the SD card/ storage is so severely broken that the same situation occurs like you would have when you would manually unplug the storage during operation - the kernel simply hard crashes or ends up in an OOPS crash situation. 

Therefore, the only solution for such a situation is to replace your SD card / storage right away. RaspberryMatic cannot in any way prevent such crashes or show an error message instead!
