### ISSUE TITLE
HmIP-WRC2, HmIP-eTRV-C, HmIP-STHD don't communicate after firmware update.

### ISSUE THREAD

**Issue by Ivanverdonck** [jens-maus/RaspberryMatic#1909]
### Describe the issue you are experiencing

Since the latest device firmware update of the following Homematic components, the devices stopped communicating:
- HmIP-WRC2
- HmIP-eTRV-C
- HmIP-STHD

WebUI repoted "Update Succesfull" but the communication to Raspberrymatic and also the "direct device" communication stopped working.
The problem is also reported at the ELV forum: https://de.elv.com/forum/nach-udapte-auf-fw-1.18-geraet-nicht-mehr-erreichbar-20021

ELV and eQ-3 is refusing to give any support because a HmIP-RFUSB in combination with Raspberrymatic is used.
Could the problem be related to Raspberrymatic? Or is it a Homamatic problem.

I am very disapointed in ELV and eQ-3.

### Describe the behavior you expected

Succesfull device firmware update, and working communication afterwards.

### Steps to reproduce the issue

1. download device firmware form WebUI
2. upload firmware to WebUI
3. transfer update to device (automatically, can take serveral days)
4. Push "Update" button on WebUI Firmware page, when transfer ready
5. wait for update to complete, "Update Successfull" recieved

### What is the version this bug report is based on?

3.65.6.20220723

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
no logs
```

### Additional information

I contacted ELV and eQ-3, they don't give any support...

**Comment by Ivanverdonck** [comment]
For everyone's information:

- ELV and e3-Q reffused to give me any support because i use Raspberrymatic. If u want support u need to buy a CCU3 ;-)

- Without the help of ELV and e3-Q I managed to fix the problem: restoring a 6 month old backup AND performing a device factory reset, resolved the issue. I am not sure if the problem is related to Raspberrymatic like ELV/e3-Q sugguest. But if u have similar problems: Restore a previous backup and do a device factory reset using the buttons on the device.


Kind regards,
Ivan Verdonck

----------------------------------------------------------------------------
Zur Information aller:

- ELV und e3-Q verweigerten mir jegliche Unterstützung, da ich Raspberrymatic verwende. Wenn du Unterstützung willst, musst du eine CCU3 kaufen ;-)

- Ohne die Hilfe von ELV und e3-Q gelang es mir, das Problem zu beheben: Das Wiederherstellen einer 6 Monate alten Sicherung UND das Zurücksetzen des Geräts auf die Werkseinstellungen löste das Problem. Ich bin mir nicht sicher, ob das Problem mit Raspberrymatic zusammenhängt, wie ELV/e3-Q vorschlägt. Aber wenn Sie ähnliche Probleme haben: Stellen Sie eine vorherige Sicherung wieder her und führen Sie mit den Tasten am Gerät einen Werksreset durch.


Mit freundlichen Grüßen,
Iwan Verdonck

**Comment by jens-maus** [comment]
Gut das das Problem wohl irgendwie selbst gelöst wurde, wenn auch wohl weiterhin unklar ist wie genau es zu einer Lösung kam. Ein Problem in RaspberryMatic kann jedoch ausgeschlossen werden da ich selbst Teile dieser Geräte habe mit den neuesten Firmwareversionen und auch andere RaspberryMatic Nutzer diese erfolgreich einsetzen.

Hier muss also ein lokales Problem
existiert haben das nun wohl weg ist.

Bitte noch beachten, das dies hier kein Diskussionsforum für das finden von Problemlösungen ist. Das ist ein Big/Issuetracker in dem nur Dinge gemeldet werden sollten nachdem diese von anderen Nutzern in einem Forum wie homematic-forum.de bestätigt wurden.
