### ISSUE TITLE
Geräteeinstellungen auf Raspberrymatic nicht mehr erreichbar

### ISSUE THREAD

**Issue by mbokor** [jens-maus/RaspberryMatic#191]
wenn man bei den Geräten auf Einstellen drückt erscheint immer folgende Meldung:

Das Gerät mit der Seriennummer 'KEQ0365746' vom Interface 'BidCos-RF' konnte nicht abgefragt werden!

Was muss ich tun ?

Die direkten Verbindungen der Geräte werden auch nicht mehr angezeigt, obwohl sie funktionieren.

**Comment by jens-maus** [comment]
Bitte diesbzgl. vor allem zuerst an das homematic forum wenden (https://homematic-forum.de/forum/viewforum.php?f=65). Das hier ist ein Bugtracker wo man verifizierte Probleme meldet und kein Support Forum. Meine Vermutung ist aber das dies passiert weil nur LAN-Gateways eingesetzt werden und kein Funkmodul auf dem GPIO und in der aktuellen RaspberryMatic Version ein Bug existiert. Mit der nächsten kommenden Version sollte dieser behoben sein.
