### ISSUE TITLE
Consider using "arm_boost=1" for RaspberryPi4 platform

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#1913]
### Describe the solution you'd like

I just noticed starting with https://github.com/home-assistant/operating-system/pull/2073 that in a standard RaspberryPiOS installation the `config.txt` option `arm_boost=1` seem to be the new default setting for all RaspberryPi4 systems. Even in the official documentation this is mentioned:

See the official [documentation on arm_boost](https://www.raspberrypi.com/documentation/computers/config_txt.html#arm_boost-raspberry-pi-4-only), which states the following:

> This change should be safe for all such boards [...]
> New Raspberry Pi OS images from Bullseye onwards come with this setting by default.

Question, remains, however if it would be a wise/good decision for us (RaspberryMatic) to also enable `arm_boost=1` as a new default setting in `config.txt`? Given the point that a RaspberryPi4 is anyway quite problematic regarding RF interferences, I am still skeptical if it would be a good idea to do the same like the RaspberryPiOS developers obviously decided. So more testing seems to be at least required here.

### Describe alternatives you've considered

We should make sure to perform adequate testing for the `arm_boost=1` option to not introduce and additional RF interferences if a RPI-RF-MOD, HM-MOD-RPI-PCB is connected to the GPIO or if a HmIP-RFUSB is connected to the USB2 or USB3 connectors.

### Is your feature request related to a problem?

n/a

**Comment by jens-maus** [comment]
@Baxxy13 As you seem to have a quite broad RaspberryPi4 testing farm at your end, can you please consider doing some testing regarding this ticket here? All you would need to do is to add the `arm_boost=1` option to the `/boot/config.txt` file of a RaspberryPi4 RaspberryMatic installation and then check the increased CPU frequency (1.8GHz instead of 1.5GHz) and then check if the Carrier Sense will have the same level and if teaching HmIP devices is still equally possible or not.

**Comment by jens-maus** [comment]
BTW: Best would be to perform these tests based on the latest development snapshot as newer RaspberryPi4 firmwares and eeprom images are included there as well, which might affect using that `arm_boost=1` setting as well.

**Comment by Baxxy13** [comment]
Interessant. Mehr Leistung "für lau" sieht man ja immer gerne.
Leider kann ich nicht einspringen da alle meine Pi4B's ältere Revisionen sind bei denen die Option (`arm_boost=1`) nicht zieht.
Manuell overclocken möchte ich aber auch nicht unbedingt...

> But remember: playing with clocks and voltages can render your SD card (temporarily) unbootable, so make sure you have another card (or another computer) on hand that you can boot with to restore your config.txt to good sense.

Die Frage wäre ja auch ob es sinnvoll ist einen Pi4B bis zum Maximum zu betreiben wenn er als dauerlaufende Zentrale eingesetzt wird. Andererseits wird er wohl so gut wie nie mit Maximaltakt laufen. 

Ich würd's aktivieren. Die paar User die mit einem Pi4B unterwegs sind wissen hoffentlich worauf es ankommt und bräuchten ja auch noch die neue Revision für den automatischen Boost auf 1.8GHz. Die alten Revisionen laufen ja weiterhin mit default 1.5GHz.

**Comment by jens-maus** [comment]
> Ich würd's aktivieren. Die paar User die mit einem Pi4B unterwegs sind wissen hoffentlich worauf es ankommt und bräuchten ja auch noch die neue Revision für den automatischen Boost auf 1.8GHz. Die alten Revisionen laufen ja weiterhin mit default 1.5GHz.

Ok, das bestätigt mein Gefühl und meine Tests. Dann werd ich das mal entsprechend aktivieren - schauen wir dann mal was in der breiten Masse dann daraus wird.

**Comment by ghiathkamel** [comment]
i added arm_boost=1 to my config file, but i have already #arm_freq=800, do i need to remove it ? Thanks

**Comment by jens-maus** [comment]
This issue is closed and not a discussion fora. Please discuss in the discussion area instead
