### ISSUE TITLE
WebUI: Anlernen neuer Geräte trotz abgelaufener Session möglich

### ISSUE THREAD

**Issue by dennisfabri** [jens-maus/RaspberryMatic#1914]
### Describe the issue you are experiencing

Ich habe versucht ein Gerät anzulernen und die Maske war bereits einige Zeit offen. Die Session war abgelaufen, aber das Gerät wurde jedoch trotzdem korrekt angelernt.

### Describe the behavior you expected

Ich habe erwartet, dass mit abgelaufener Session die Zentrale nicht in den Anlernmodus versetzt werden kann.

### Steps to reproduce the issue

1. Login
2. Maske "Anlernen öffnen" (anlernen aber nicht starten)
3. Warten bis die WebUI-Session abgelaufen ist (z.B. 10 Minuten).
4. HMIP-Gerät in Anlernmodus versetzen.
5. In der Maske auf "HmIP Gerät anlernen" klicken
6. Im Posteingang erscheint ein angelerntes Gerät
7. Beim Klick auf Posteingang erhält man die Meldung, dass die Session abgelaufen ist.

### What is the version this bug report is based on?

3.65.6.20220723

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
-
```

**Comment by jens-maus** [comment]
Tut mir leid, aber das wird nicht zu vermeidener Sideeffect sein das die Anlernroutinen teilweise im Schnittstellenprozess (HMIPServer) und eben die Darstellung davon in der WebUI stattfindet. Wenn man also ein HmIP Gerät in den Anlernmodus versetzt hat nachdem (oder bevor) man in der WebUI den Anlernmodus aktiviert hat wird dieses sich auch entsprechend im Posteingang wiederfinden. Was aber definitiv nicht funktionieren darf ist, das man im Normalbetrieb (ohne das aktivieren des Anlernmodus in der WebUI) ein Homematic Gerät in den Anlernmodus versetzt und dann dieses im Posteingang auftaucht. Und genau das habe ich noch nie wahrgenommen das das so ist, denn ansonsten müssten meine zich Testplatformen ja immer neue Gerät im Posteingang aufzeigen.

Ergo wird dein "Problem" daher rühren, das du davon ausgehst das nach exakt XX Sekunden der Anlernmodus beendet ist. Das läuft aber nicht absolut synchron ab. Warte mal 60 Sekunden oder so nachdem der Anlernmodus abgelaufen ist. Dann sollte sich definitiv kein Gerät mehr anlernen lassen.

**Comment by dennisfabri** [comment]
Da habe ich mich offenbar missverständlich ausgedrückt. Mein Problem ist nicht der Anlernprozess an sich, sondern dass ich die Zentrale trotz abgelaufener WebUI-Session in den Anlernmodus versetzen konnte.

**Comment by jens-maus** [comment]
Dann musst du das nochmal genauer / technischer beschreiben wie genau du das bitte exakt geschafft hast.

**Comment by dennisfabri** [comment]
Ich habe die Schritte noch einmal angepasst. Der ehemalige Schritt 3 ist nicht notwendig und damit wird die Beschreibung deutlich klarer.

**Comment by jp112sdl** [comment]
> 4. HMIP-Gerät in Anlernmodus versetzen.
> 5. In der Maske auf "HmIP Gerät anlernen" klicken

Die Reihenfolge ist schon falsch.

Geht/ging es hier bei diesem Versuch um ein Gerät, das schon mal an diesem System angelernt war?

Ist es dann bei HmIP nicht so, dass sie - auch ohne CCU-Anlernmodus - beim Drücken des Configtasters wieder im Posteingang landen?

**Comment by dennisfabri** [comment]
Die Reihenfolge ist für das Problem egal. Der Anlernzeitraum muss sich nur ausreichend überschneiden, damit das Gerät gefunden wird. Eigentlich könnte ich auf die Punkte 4 und 6 in der Beschreibung auch noch weglassen, weil ich beim Klick auf "Gerät anlernen" wegen der abgelaufenen WebUI-Session eine entsprechende Fehlermeldung erwarten würde und nicht die Meldung, dass der Anlernmodus jetzt aktiv ist.

**Comment by honsma235** [comment]
Kann das Verhalten so bestätigen. Habe ich auch des öfteren in der Version 3.65.6.20220723 beobachtet. Bin mir aber recht sicher, dass ich das Verhalten bereits im Winter/Frühjahr schon mal bemerkt hatte.

Man hat z.B. am Smartphone die WebUI Seite offen, weil man grad irgendwas nachgeschaut hat. Dann montiert man z.B. einen neuen (noch nie angelernt) Heizkörperthermostat, wobei eine gewisse Zeit vergeht, z.B. 15 Minuten. Fertig montiert und Batterie eingelegt will man das Thermostat gleich ans System anlernen, und geht dafür auf den Tab am Browser mit der noch geöffneten WebUI Seite. Dort kann man trotz abgelaufener Session mit dem Button oben rechts das "Geräte anlernen" Fenster aufrufen und dort den Anlernmodus aktivieren, samt Rückmeldung, dass dieser nun aktiv sei, inkl. Countdown. Will man dann aber auf den Posteingang wechseln wird die abgelaufene Session erst erkannt, und man muss sich neu anmelden.
