### ISSUE TITLE
LED des RPI-RF-MOD inaktiv bei GPIO-Anbindung auf Pi3B

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1916]
### Describe the issue you are experiencing

Seit Nightly 3.65.8.20220824-601160 funktioniert die LED eines RPI-RF-MOD (auf GPIO) nicht mehr.
Mit dem direkten "Vorgänger-Nightly" 3.65.8.20220822-4c176e-rpi3 passt noch alles.

### Describe the behavior you expected

Die LED eines RPI-RF-MOD auf GPIO sollte funktional sein.

### Steps to reproduce the issue

1. irgendeinen Nightly >3.65.8.20220822-4c176e flashen 
2. beim automatischen Reboot auf die LED des Funkmoduls achten
3.
...

### What is the version this bug report is based on?

Nightly 3.65.8.20220824-601160 und neuer

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Initializing RTC Clock: cat: can't open '/sys/module/rtc_rx8130/drivers/i2c:rtc-rx8130/1-0032/name': No such file or directory
sh: rx8130-legacy: unknown operand
```

**Comment by jens-maus** [comment]
Danke für den schnellen Test. Dann bitte mit dem nächsten nightly mal testen!
