### ISSUE TITLE
Thermostat low_battery ist false trotz Servicemeldung in WebUI

### ISSUE THREAD

**Issue by multiholle** [jens-maus/RaspberryMatic#1921]
### Describe the issue you are experiencing

Im WebUI wird für ein Thermostat die Servicemeldung "Leere Batterie" angezeigt. In Home Assistant ist der Wert für low_battery false.

### Describe the behavior you expected

Der Wert für low_battery ist true.

### Steps to reproduce the issue

HM-CC-RT-DN Thermostat mit Batteriespannung von 2,3 V
<img width="1074" alt="Screenshot 2022-09-02 at 20 16 56" src="https://user-images.githubusercontent.com/5654539/188214842-cfd2c551-7d4d-4a17-9b9b-725b50bd5205.png">
<img width="1080" alt="Screenshot 2022-09-02 at 20 17 06" src="https://user-images.githubusercontent.com/5654539/188214856-c91185e5-16ae-49e8-b8a9-4b2f5739f952.png">
<img width="676" alt="Screenshot 2022-09-02 at 20 17 19" src="https://user-images.githubusercontent.com/5654539/188214870-7908b9b0-3531-4669-9d71-1235a61405b8.png">

### What is the version this bug report is based on?

3.65.8.20220831

### Which base platform are you running?

intelnuc (intel NUC)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
-
```

**Comment by jens-maus** [comment]
Tut mir leid. Aber hier (im RaspberryMatic GitHub) hat das nix verloren. Das gehört in das GitHub Project der "Homematic(IP) Local" HomeAssistant Integration:

https://github.com/danielperna84/custom_homematic
