### ISSUE TITLE
% (Prozent) - Zeichen im Wertebereich von Text-SysVars macht diese "unbearbeitbar" 

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#1925]
### Describe the issue you are experiencing

Das Schreiben eines % - Zeichens in eine Text-SysVar führt dazu das diese nicht mehr "bearbeitbar" ist. 

### Describe the behavior you expected

% - Zeichen in Text-SysVars sollten keine Probleme verursachen.

### Steps to reproduce the issue

1. Text-SysVar anlegen "SV_Text"
2. % - Zeichen per WebUI-Programm oder Script als Wert in die SysVar schreiben
3. die SysVar bearbeiten, z.B. versuchen den Wert zu ändern oder umzubenennen
...

### What is the version this bug report is based on?

3.65.8.20220831

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Browser-Konsolen-Log beim Bearbeiten der SysVar:

prototype.js:603 Uncaught URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at loadChar8859Edit (eval at <anonymous> (prototype.js:399:64), <anonymous>:287:54)
    at eval (eval at <anonymous> (prototype.js:399:64), <anonymous>:293:68)
    at prototype.js:399:64
    at prototype.js:640:20
    at prototype.js:600:9
    at Array.forEach (<anonymous>)
    at Array.each (prototype.js:599:12)
    at Array.collect (prototype.js:639:10)
    at String.evalScripts (prototype.js:399:34)
```

**Comment by jp112sdl** [comment]
`decodeURIComponent` hat wohl ein Problem mit dem Prozentzeichen?

https://stackoverflow.com/questions/7449588/why-does-decodeuricomponent-lock-up-my-browser

**Comment by MichaelN0815** [comment]
In der 3.63.9.20220625 war der Fehler auch schon drin, falls das weiter hilft.

**Comment by Baxxy13** [comment]
Der Fix steht ja dank Jérôme schon bereit, es muss ihn bloß jemand einbauen. ;-)

**Comment by MichaelN0815** [comment]
Habe ich glatt übersehen ;-)
