### ISSUE TITLE
S-USV Version 1

### ISSUE THREAD

**Issue by Gluehwurm** [jens-maus/RaspberryMatic#193]
Habe ein altes basic-Board (Firmware 1.32). Die Statusmeldung bricht mittendrin ab.
https://homematic-forum.de/forum/viewtopic.php?f=65&t=39482&p=398772#p398772

Software-File und Bild im Beitrag

Danke

Gruß
Bruno

**Comment by jens-maus** [comment]
Das ist kein Bug sondern eine Support Anfrage. Das hat hier (mit Verlaub) nichts verloren sondern gehört nur in das Forum. Das hier ist ein Bug- und Feature-Tracker.
