### ISSUE TITLE
 RaspberryMatic als USB Device Server nutzen

### ISSUE THREAD

**Issue by flyinghuman** [jens-maus/RaspberryMatic#1933]
### Describe the solution you'd like

Hallo, es wäre genial wenn man den RaspberryMatic auf einen RaspbeeryPi auch als USB Device Server nutzen könnte. Dann kann man anderen Geräten im Netzwerk die angeschlossenen USB-Geräte wie bspw. ZigBee Sticks bereitstellen. Bei mir ist es bspw. so, dass der Standort von meiner iobroker-Installation sehr ungünstig für einen ZigBee Stick wäre und auch noch virtualisiert ist sodass es dort zwar machbar ist USB zur VM lokal am PC zu verbinden aber dort der Empfang sehr schlecht wäre. Wenn man nun den RaspberryMatic als DeviceServer mit "usbip" (apt-get install usbip) im Host-Modus nutzen könnte wäre das echt hilfreich.

Hier ein kleines Tutorial für usbip: https://derushadigital.com/other%20projects/2019/02/19/RPi-USBIP-ZWave.html

Wäre schön wenn es das als Addon gäbe. Oder gibts das schon und ich habe es nur übersehen?

Danke und Gruß...

### Describe alternatives you've considered

Use it locally.

### Is your feature request related to a problem?

no

**Comment by jens-maus** [comment]
Auch wenn ich diese Idee prinzipiell nachvollziehen kann, so muss ich trotzdem ein klares "Nein" diesbzgl aussprechen. Der Sinn und Zweck von RaspberryMatic ist eine Homematic/homematicIP Zentrale bereit zu stellen und keine Eierlegende Wollmichsau zu bauen bzw. eine Smarthome-Zentrale für alles. Das ist in der Tat etwas für Middlewares wie HomeAssistant, ioBroker, etc. RaspberryMatic ist ein einfacher SmartHome-Gateway in die HomeMatic welt und nicht gedacht verschiedene Protokollwelten zu ereinen. Im übrigen gibt es USB/IP inzwischen in HomeAssistant. Insofern sollten interessierte USB/IP Nutzer also eher darauf mal einen Blick werfen.
