### ISSUE TITLE
Verbindung zum RaspberryMatic kann nicht aufgebaut werden

### ISSUE THREAD

**Issue by hesnuks** [jens-maus/RaspberryMatic#1934]
### Describe the issue you are experiencing

Hallo,

ich hatte bereits ein Thread bei Homeassistant aufgemacht, aber dort konnte man mir nicht wirklich weiter helfen :(
Ich verlinke es einmal, da man dort glaube ich alles ganz gut erfährt, was man wissen muss 
[Zum-Thread](https://community.home-assistant.io/t/raspberrymatic-integration-connection-problems/458259/16)

### Describe the behavior you expected

Das Verbinden von Integration zu RaspberryMatic klappt nicht.
Ich habe bereits etwas in einem anderen Thread gefunden:  [Github](https://github.com/jens-maus/RaspberryMatic/issues/613)
Weiß aber nicht, wie oder wo ich das ` monit unmonitor HMIPServer` ausführen soll.

### Steps to reproduce the issue

Installieren der Integration und dann konfigurieren...

### What is the version this bug report is based on?

3.65.8.20220831

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Die logs sind auch in dem Link zu Home-assistant gepostet.
```

**Comment by Baxxy13** [comment]
Laut verlinktem Thread hast du keinen HmIP-RFUSB sondern den HmIP-RFUSB-TK.
Das ist auch so auf den Logausgaben zu sehen.

Dieser kann kein BidCos-RF (Homematic Klassik Funk).
Deshalb musst du bei der Konfiguration den (standardmäßig gesetzten) Haken bei "aktiviere Homematic (Bidcos-RF)" entfernen.

Dann sollte das klappen.

**Comment by hesnuks** [comment]
Oh mein gott.... Es war so simpel und ich suche mir einen ab...
Tausend dank!
