### ISSUE TITLE
Pi4 Watchdog Alert not working for USB3

### ISSUE THREAD

**Issue by Marcus1807** [jens-maus/RaspberryMatic#1941]
### Describe the issue you are experiencing

connecting devices to USB3 on a Pi4(+) raises no watchdog alert

### Describe the behavior you expected

connected devices to usb3 on a PI4(+) should raise a watchdog alert

### Steps to reproduce the issue

1. install rapberrymatic on a pi4(+)
2. connect an usb device to usb3 interface
--> no watchdog alert is raised

### What is the version this bug report is based on?

3.65.8.20220831

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
nothing interesting to find in logs.
```

### Additional information

https://homematic-forum.de/forum/viewtopic.php?f=65&t=75507
https://homematic-forum.de/forum/viewtopic.php?f=65&t=75507#p732573

**Comment by jens-maus** [comment]
fixed by 08da193daa9d396448ae55d3beba0557817f30fe
