### ISSUE TITLE
Nach Update auf 3.65.8 keine BidCos-RF und Ausfall sämtlicher Funkkomponenten

### ISSUE THREAD

**Issue by SebastianCismar** [jens-maus/RaspberryMatic#1948]
### Describe the issue you are experiencing

Nach dem Update auf 3.65.8 war keine Verbindung über "HOMEMATICIP_LOCAL-Interface not reachable
No connection to interface rasperrymatic-BidCos-RF" und anderer Funkanwendungen wie Raumthermostaten etc. möglich.

Habe das letze Backup auf 3.65.6 wieder eingespielt nun gibt es lediglich keine Verbindung mehr zum "rasperrymatic-BidCos-RF", alle anderen Funkkomponenten werden wieder angezeigt.

Homematic IP (Local) Version ist 1.16.5

### Describe the behavior you expected

Das sämtliche Komponeten der Homematicwelt ansteuerbar sind.

### Steps to reproduce the issue

1. Update von 3.65.6 auf 3.65.8
2.Partielles Backup von 3.65.6 wieder eingespielt
3.
...

### What is the version this bug report is based on?

3.65.6 und 3.65.8

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
Protokoll der Rasperrymatic Version 3.65.6 mit der Fehlermeldung "Starting rfd:..... Error

Mounting /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying host system: oci, OK
Initializing RTC Clock: no hardware found
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.1, OK
Identifying Homematic RF-Hardware: ....HmRF: HM-MOD-RPI-PCB/GPIO@3f201000.serial, HmIP: HM-MOD-RPI-PCB/GPIO@3f201000.serial, OK
Updating Homematic RF-Hardware: HM-MOD-RPI-PCB: 2.8.6, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting sshd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: .OK
Starting rfd: ....................ERROR
Starting HMIPServer: ........................OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.65.6.20220723 (raspmatic_oci_arm64)
```

**Comment by jens-maus** [comment]
Welche HomeAssistant Umgebung/Version nutzt du denn, denn ich sehe "Home Assistant Add-On" in deinen Ausgaben?

**Comment by SebastianCismar** [comment]
Hallo,

hier die gewünschten Informationen:

Home Assistant 2022.9.4
Supervisor 2022.08.6
Operating System 9.0
Frontend 20220907.2 - latest

Nach einem Neustart bekomme ich jetzt folgende Fehlermeldungen:

HOMEMATICIP_LOCAL-Interface not reachable
No connection to interface rasperrymatic-HmIP-RF

HOMEMATICIP_LOCAL-Interface not reachable
No connection to interface rasperrymatic-VirtualDevices

HOMEMATICIP_LOCAL-Interface not reachable
No connection to interface rasperrymatic-BidCos-RF

**Comment by jens-maus** [comment]
> hier die gewünschten Informationen,
> 
> Home Assistant Operating System 9.0 

Dann ist exakt das das Problem. Aktuell gibt es im Bezug auf das "RaspberryMatic CCU Add-on" Probleme mit Home Assistant OS 9.0. Siehe https://github.com/jens-maus/RaspberryMatic/issues/1942

D.h. du solltest auf HomeAssistantOS 8.5 downgraden, dann sollten die Probleme verschwinden.

**Comment by SebastianCismar** [comment]
Ok gibt es irgendwo eine Anleitung zum downgrade?

**Comment by jens-maus** [comment]
Lies das referenzierte Ticket durch! Hier geht es nicht weiter...
