### ISSUE TITLE
Home Assistant Add-on multimacd, rfd & HMIPServer ERROR

### ISSUE THREAD

**Issue by sjhimmel** [jens-maus/RaspberryMatic#1949]
### Describe the issue you are experiencing

Hallo zusammen,

ich habe am 12.09. nach der Video-Anleitung von simon42 das RaspberryMatic CCU Add-on installiert und eingerichtet. Bei der Installation gab es keine Probleme und auch keine ERROR im log. Ich habe dann problemlos meine vorhandenen Geräte vom HmIP Access Point ablernen und bei der neuen CCU anlernen können. Auch erste Programmierungen habe ich vorgenommen (Zeitsteuerung) für die Gartenbeleuchten. All das ging und funktionierte einwandfrei. Ich habe dann am Mittwoch eine Home Assistant Core Update gemacht von 2022.9.3 auf 2022.9.4. Hiermit ging auch ein Reboot des Systems einher. Seither bekomme ich oben genannte Fehlermeldungen im Log und nichts geht mehr. Es werden keine Geräte in der Raspberrymatic angezeigt und auch nicht der HmIP-RFUSB-Stick. Zudem kommt es im Add-on zu „One oft he Homatic devices is not responding“ Meldungen (HmIP-RF, VirtualDevices, BidCos-RF).

Info zum System:
Home Assistant 2022.9.4 / 2022.9.3
Supervisor 2022.08.6
Operating System 9.0
Frontend 20220907.2 - latest

### Describe the behavior you expected

Meine Erwartung wäre, dass nach einem Neustart des Systems dieses wie zuvor funktioniert.

### Steps to reproduce the issue

1. Restart des Add-on
2. Stoppen + Starten des Add-on
3. Restart von Home Assistant
4. Reboot des Host
5. Reboot des Host (ohne Autostart der CCU) mit manuellem Start

### What is the version this bug report is based on?

3.65.8.20220831

### Which base platform are you running?

odroid-n2 (ODROID N2/N2+)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Mounting /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying host system: oci, OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.3, OK
Identifying Homematic RF-Hardware: ....HmRF: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-xhci-hcd.1.auto-1.3, HmIP: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-xhci-hcd.1.auto-1.3, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: 4.4.18, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: creating new SSL cert... OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: ..........ERROR
Starting rfd: ERROR: /dev/mmd_bidcos missing, no BidCos-RF hardware found
Starting HMIPServer: ERROR: /dev/mmd_hmip missing
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: OK
Starting Third-Party Addons: OK
find: /usr/local/etc/monit*.cfg: No such file or directory
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.65.8.20220831 (raspmatic_oci_arm64)
```

### Additional information

Folgendes habe ich probiert:

1. Ich habe einen Rollback auf die Version 2022.9.3 gemacht => gleiche Fehler, kein Effekt
2. Ich habe das Add-on gestoppt und die Snapshot-Version installiert => gleicher Fehler, kein Effekt
3. Ich bin zurück auf 2022.09.4 per Backup => gleiche Fehler, kein Effekt
4. Ich habe das Add-on und die Integration deinstalliert und das Add-on neu installiert => gleiche Fehler, kein Effekt

Nach einigem Lesen hier scheint mein Fehlerbild sehr den Issues #1707 und #1752 zu ähneln, für dies es ja bereits eine Lösung gibt (Stichwort: sleep 5). Leider bin ich noch zu neue im HA / Raspberrymatic Kosmos und weiß daher nicht wo / wie ich diese Anpassung einzubringen habe.

**Comment by jens-maus** [comment]
Duplicate of #1942

**Comment by maglat** [comment]
Bei mir genau die selbe Problematik. Brauch dringend Hilfe!

**Comment by jens-maus** [comment]
Wie gesagt! Ein Duplicate! Im anderen Ticket/Issue geht es weiter!
