### ISSUE TITLE
Rega Process Crashes after update

### ISSUE THREAD

**Issue by ncc1701ski** [jens-maus/RaspberryMatic#195]
After installing the last version v2.29.23.20171118 and restoring the update an error occured telling a process had been crashed. Nothing more is working.

Also my three LAN gateways HM-LGW-O-TW-W-EU-2 do not connect all to Raspi 3. Don't know why.

**Comment by jens-maus** [comment]
Sorry, thsi report is not sharp enough. Please be more verbose with details.
