### ISSUE TITLE
ReGaHss: mangelhaft implementierte Funktion zum Löschen von "Geistervariablen" 

### ISSUE THREAD

**Issue by BadenPower** [jens-maus/RaspberryMatic#196]
Die Funktion zum automatischen Löschen der einem Benutzer zugeordneten "falschen" ID, zur Anzeige auf der Startseite, wurde mangelhaft implementiert.

Durch die falsche Verwendung von .UserSharedObjects() werden beim Start der ReGaHss Beta24 nicht alle IDs der "Geistervariablen" und "Schläfer" gelöscht.

**Comment by jens-maus** [comment]
Danke für die Information. Bitte entsprechenden Beispielcode bereitstellen damit das Problem reproduziert werden kann.

**Comment by litti** [comment]
Eventuell hilft https://homematic-forum.de/forum/viewtopic.php?f=26&t=39972#p396376 und die nachfolgenden Beiträge?

**Comment by jens-maus** [comment]
Die Beiträge sind bekannt. Trotzdem sollte hier IMHO genauer spezifiziert werden unter welchen Randbedingungen noch ein Problem mit UserSharedObjects() existiert.

**Comment by BadenPower** [comment]
Das verlinkte Skript unter https://homematic-forum.de/forum/viewtopic.php?f=26&t=39972#p396376 hilft Betroffenen Usern keineswegs, da es nicht das macht, was es soll, da es "fehlerhaft" geschrieben ist.

Es ist dort im Forum auch nicht der einzige fehlerhafte Rekonstruktions-Versuch meines Original-Skript zur Beseitigung aller Geistervariablen und Schläfer. Wenn man schon abschreibt, dann sollte man dies auch richtig machen. Und wenn man es anderst versucht zu lösen, dann sollte man sich dessen bewußt sein, was man macht und es nicht halt irgendwie nach dem Motte "Jugend forscht" probieren.

Den Fehler kann man nachstellen, in dem man dieses Skript ausführt um einige "Schläfer" einzufügen:

`string lUserName = "Admin";
object lUser;
string lEnum;
lUser = (dom.GetObject(ID_USERS)).Get(lUserName);
if(lUser)
{
  lUser.UserSharedObjects().Add("33333");
  lUser.UserSharedObjects().Add("33334");
  lUser.UserSharedObjects().Add("33335");
  lUser.UserSharedObjects().Add("33336");
  lUser.UserSharedObjects().Add("33337");
  WriteLine("IDs hinzugefügt");
}
else
{
  WriteLine("User " # lUserName # " nicht gefunden!");
}
WriteLine("Ende");.` 

Danach einfach die ReGaDom speichern und dann die ReGaHss neu starten.

Und siehe da, es wird immer nur der 1. von zwei aufeinanderfolgenden Fehlern gelöscht, da sich die Array-Liste beim Herauslöschen einer ID jeweils um 1 verkürzt.
.

**Comment by jens-maus** [comment]
Danke für den Hinweis und den Beispielcode. Den Rest des Beitrages habe ich bewusst entfernt. Das hier ist kein Forum sondern ein Bug- und Issuetracker ohne Diskussions- oder Meinungscharakter und alle anderen Dingen waren nicht relevant für die Lösung des Problems.

**Comment by litti** [comment]
Abschreiben? Ehrlich? Das es andere oder bessere Möglichkeiten gibt, keine Frage. Aber abgeschrieben war es nun definitiv nicht - es gab ja nichts mehr zum Abschreiben, da Du es selbst alles gelöscht hast ;-)
Abgesehen davon sollte es Jens nur das Problem zeigen. 

Beitrag nur als Antwort für die automatische Mail-Notifikation, wird hier gleich wieder gelöscht um den Tracker nicht vollzumüllen.
