### ISSUE TITLE
Deinstallation von NeoServer schlägt mit Fehlern fehl

### ISSUE THREAD

**Issue by klada** [jens-maus/RaspberryMatic#1964]
### Describe the issue you are experiencing

Wenn man aus der WebUI heraus das NeoServer-Addon über den Button "Deinstallieren" entfernt, erscheint die Meldung "Deinstallation des AddOns mit Fehlern fehlgeschlagen".

### Describe the behavior you expected

Erwarten würde man, dass die Deinstallation des AddOns ohne Fehler beendet wird.

### Steps to reproduce the issue

1. Login in RaspberryMatic Web-UI
2. **Systemsteuerung** -> **Zusatzsoftware** öffnen
3. Beim Addon **NeoServer** auf **Deinstallieren** klicken

### What is the version this bug report is based on?

3.65.8.20220831

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?
Der Uninstall-Log `/var/log/addon-uninstall-error.log` sieht wie folgt aus:

```txt

[Wed Sep 28 15:54:41 CEST 2022] /usr/local/etc/config/rc.d/97NeoServer stopping neo server ...
[Wed Sep 28 15:54:41 CEST 2022] /usr/local/etc/config/rc.d/97NeoServer neo_server stopped
cannot find symbol "Tclrega_Init": tclsh: undefined symbol: _Tclrega_Init
    while executing
"load tclrega.so"
    (in namespace eval "::HomeMatic" script line 5)
    invoked from within
"namespace eval ::HomeMatic {
        namespace export Addon Script Session Util GetSerialNumber

        if { ![info exists rega_script] } then {
                load tclrega.so..."
    (file "/usr/lib/tcl8.6/homematic/homematic.tcl" line 2)
    invoked from within
"source /usr/lib/tcl8.6/homematic/homematic.tcl"
    ("package ifneeded HomeMatic 1.0" script)
    invoked from within
"package require HomeMatic"
    (file "/bin/updateAddonConfig.tcl" line 18)
```
```


### Additional information

_No response_

**Comment by Baxxy13** [comment]
Aktuell liefert Jens noch die Version 2.10 des NEO-Server mit.

Ich habe den mal auf 2.11 aktualisiert und anschließend fehlerfrei deinstalliert.
