### ISSUE TITLE
multimacd: ..........ERROR with HASSOS (ODROID-N2+)

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#1969]
> I'm running HomeAssistantOS on an Odroid N2+.

Ok, I could finally reproduce it here with my test ODROID N2+:

```
Starting multimacd: ..............ERROR
Starting rfd: ERROR: /dev/mmd_bidcos missing, no BidCos-RF hardware found
Starting HMIPServer: ERROR: /dev/mmd_hmip missing
```

However, with a RaspberryPi or OVA-based HomeAssistantOS everything seems to work fine. Thus, this seems to be a ODROID-N2 limited issue which needs some dedicated investigation+fixes.

_Originally posted by @jens-maus in https://github.com/jens-maus/RaspberryMatic/issues/1968#issuecomment-1264373923_

**Comment by katter** [comment]
Anyone has a cheap N2+ for sale? I think I need to invest more time on testing dev HASSOS and RM and my only N2+ is running Prod 😔

**Comment by jens-maus** [comment]
After having debugged this a bit further I can see the following `multimacd` messages appearing:

```
~# multimacd -f /var/etc/multimacd.conf -l 0 -c
2022/10/01 18:25:11.672 <Debug> FastMacResponder::ThreadFunction() started Id=1425
2022/10/01 18:25:11.672 <Debug> SubsystemManager::ThreadFunction() started. Id=1427
2022/10/01 18:25:11.672 <Debug> MacController::ThreadFunction() started. Id=1426
2022/10/01 18:25:11.672 <Warning> Could not set scheduling priority: Operation not permitted
2022/10/01 18:25:11.672 <Debug> C<: #0 COMMON IdentifyRequest
2022/10/01 18:25:11.672 <Debug> C< @9604888: bin:FD 00 03 FE 00 01 14 1E
2022/10/01 18:25:11.672 <Warning> Could not set scheduling priority: Operation not permitted
2022/10/01 18:25:11.672 <Warning> Could not set scheduling priority: Operation not permitted
2022/10/01 18:25:11.673 <Debug> UpstreamCharConnection slave mmd_hmip ThreadFunction() started Id=1428
2022/10/01 18:25:11.673 <Debug> Subsystem 1 ThreadFunction() started. Id=1429
2022/10/01 18:25:11.673 <Warning> Could not set scheduling priority: Operation not permitted
2022/10/01 18:25:11.673 <Debug> UpstreamCharConnection slave mmd_bidcos ThreadFunction() started Id=1430
2022/10/01 18:25:11.673 <Debug> Subsystem 2 ThreadFunction() started. Id=1431
2022/10/01 18:25:11.673 <Warning> Could not set scheduling priority: Operation not permitted
2022/10/01 18:25:12.672 <Debug> C<: #1 HmSystem Identify 
2022/10/01 18:25:12.672 <Debug> C< @9605888: bin:FD 00 03 00 01 00 9E 03
2022/10/01 18:25:17.672 <Error> No Coprocessor detected!!! 
2022/10/01 18:25:17.672 <Debug> SubsystemManager::ThreadFunction() ended
2022/10/01 18:25:17.672 <Debug> Subsystem 1 ThreadFunction() ended
Signal 10 caught
2022/10/01 18:25:17.673 <Debug> UpstreamCharConnection slave device mmd_hmip ThreadFunction() ended
2022/10/01 18:25:17.673 <Debug> Subsystem 2 ThreadFunction() ended
Signal 10 caught
2022/10/01 18:25:17.673 <Debug> UpstreamCharConnection slave device mmd_bidcos ThreadFunction() ended
2022/10/01 18:25:17.673 <Debug> MacController::ThreadFunction() ended
```

Take special note on the "Operation not permitted" messages. To me this looks like some limitations of the kernel or cgroups environment specific to the ODROID build of HomeAssistantOS not allowing `multimacd` to set/modify the scheduling priority using a `sched_setscheduler()` call. Does this ring a bell for you @agners  or @pvizeli ?

**Comment by jens-maus** [comment]
FYI: This smells like there might be a regression in the ODROID builds related to https://github.com/home-assistant/operating-system/issues/1235

**Comment by jens-maus** [comment]
More info (especially for @agners) regarding the above mentioned `Operation not permitted` error due to obviously `sched_setschulder()` not being able to be used on the ODROID build of HomeAssistantOS 9.0:

Executed within the RaspberryMatic CCU Addon on a ODROID-N2+ with HAos 9.0:
```
# chrt -f -p 16 1121
pid 1121's current scheduling policy: SCHED_OTHER
pid 1121's current scheduling priority: 0
chrt: can't set pid 1121's policy: Operation not permitted
```

Executed within the RaspberryMatic CCU Addon on a OVA-driven system:
```
# chrt -f -p 16 1212
pid 1212's current scheduling policy: SCHED_OTHER
pid 1212's current scheduling priority: 0
pid 1212's new scheduling policy: SCHED_FIFO
pid 1212's new scheduling priority: 16
```

And just out of curiosity I installed HomeAssistantOS 8.5 again on my ODROID-N2+ and it shows that with 8.x the `chrt` command does not come up with an `Operation not permitted` error:

```
# chrt -f -p 16 1231
pid 1231's current scheduling policy: SCHED_OTHER
pid 1231's current scheduling priority: 0
pid 1231's new scheduling policy: SCHED_FIFO
pid 1231's new scheduling priority: 16
```

Thus, there really have to be a regression in HomeAssistant 9.0 in the ODROID builds which affect the rt scheduling capabilities and are the root cause that the RaspberryMatic CCU Addon is not able to run correctly on HAos 9.x ATM.

**Comment by jens-maus** [comment]
More results/info after more testing. I tried to use the `chrt` command directly on an ova and ODROID-based HomeAssistantOS within the context of HAos itself (in a `ha login` session). In addition, I also checked and modified the value of the `kernel.sched_rt_runtime_us` sysctl variable. See the results here:

HAos 9.0 (ova-based where the RaspberryMatic CCU addon works nicely):
```
# sysctl kernel.sched_rt_runtime_us
kernel.sched_rt_runtime_us = 950000
# chrt -f -p 16 4247
pid 4247's current scheduling policy: SCHED_FIFO
pid 4247's current scheduling priority: 0
pid 4247's new scheduling policy: SCHED_FIFO
pid 4247's new scheduling priority: 16
```

HAos 9.0 (ODROID-N2+ with a non-working RaspberryMatic CCU addon):
```
# sysctl kernel.sched_rt_runtime_us
kernel.sched_rt_runtime_us = 950000
# chrt -f -p 16 4247
pid 4247's current scheduling policy: SCHED_FIFO
pid 4247's current scheduling priority: 0
chrt: can't set pid 4247's policy: Operation not permitted
```

As can be seen, the `kernel.sched_rt_runtime_us` values are the same, but the `chrt` command also fails within the context of HAos itself and not only within the RaspberryMatic CCU Addon docker container.

After this observation, I set `kernel.sched_rt_runtime_us` to -1 and funnily this immediately seem to have been enough to get the `chrt` command (thus, the `sched_setscheduler()` call) going:

HAos 9.0 (ODROID-N2+):
```
# sysctl kernel.sched_rt_runtime_us=-1
kernel.sched_rt_runtime_us = -1
# chrt -f -p 16 4247
pid 4247's current scheduling policy: SCHED_FIFO
pid 4247's current scheduling priority: 0
pid 4247's new scheduling policy: SCHED_FIFO
pid 4247's new scheduling priority: 16
```

So, this seem to support my first initial observation, that for the ODROID-N2+ version of HAos 9.x some regression seem to exist which results in the "Operation not permitted" error message since HAos 9.0 but as soon as `kernel.sched_rt_runtime_us` is set to -1 `chrt` can be used correctly.

**Comment by jens-maus** [comment]
FYI: With the latest HomeAssistantOS development build ([10.0.dev20221003](https://os-builds.home-assistant.io/10.0.dev20221003/)) I was able to successfully boot the latest [snapshot version](https://github.com/jens-maus/RaspberryMatic/releases/snapshots) of the RaspberryMatic CCU Addon and note that `multimacd` is starting up correctly and that the HomeMatic and homematicIP teach-in mode is accessible now:

```
Starting multimacd: .......OK
Starting rfd: .OK
Starting HMIPServer: .........OK
```

Thus, with the next HomeAsistantOS 9.x release and the upcoming RaspberryMatic CCU Addon version RaspberryMatic should work correctly on a ODROID-N2+ now.
