### ISSUE TITLE
Internal Wifi (WLAN) on Raspberry Pi 3 does not work

### ISSUE THREAD

**Issue by Motorpsycho123** [jens-maus/RaspberryMatic#197]
After configuring the _/etc/config/wpa_supplicant.conf_ file the network does not start.

Starting wpa_supplicant manually gives these errors.

wlan0: CTRL-EVENT-SCAN-FAILED ret=-22 retry=1

**Comment by Motorpsycho123** [comment]
Seems to be a kernel problem introduced with 4.9.62-1:

https://www.spinics.net/lists/stable/msg198380.html
https://raspberrypi.stackexchange.com/questions/75400/internal-wlan-broken-after-kernel-and-firmware-update

**Comment by jens-maus** [comment]
Thanks for the hint, this definitly points into the right direction. Will see if 4.9.63 fixes this issue if not I will revert to an older kernel for the next release of RaspberryMatic.

**Comment by Motorpsycho123** [comment]
According to the mailing list discussion that I attached above 4.9.63 does not fix it yet.

"I just upgraded from 4.9.61 to 4.9.63 and noticed that there are no longer any WiFi networks found after upgrading."

**Comment by jens-maus** [comment]
Ok, thanks. Then lets wait until they fix the issue. There is still enough time till the next scheduled RaspberryMatic release (mid of December)

**Comment by jens-maus** [comment]
I just tested kernel 4.9.65 and `iw wlan0 scan` now works correctly. Thus, the issue should be fixed with the next upcoming release.
