### ISSUE TITLE
Favoritenlisten bleiben nach dem löschen im Hintergrund erhalten

### ISSUE THREAD

**Issue by gitandy** [jens-maus/RaspberryMatic#1972]
### Describe the issue you are experiencing

Nach dem Löschen kann eine neue Favoritenliste nicht unter demselben Namen angelegt werden.
Bei einem Backup ist die gelöschte Favoritenliste trotzdem im homematic.regadom enthalten.

### Describe the behavior you expected

Nach dem Löschen einer Favoritenliste kann einen neue Liste mit gleichem Namen angelegt werden

### Steps to reproduce the issue

1. Favoritenliste anlegen
2. Favoritenliste löschen
3. Favoritenliste mit gleichem Namen anlegen geht nicht mehr

### What is the version this bug report is based on?

3.65.8.20220831

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
-
```

### Additional information

https://homematic-forum.de/forum/viewtopic.php?f=65&t=75841

**Comment by McPan** [comment]
### Steps to reproduce the issue
1.) Create new favorite list
2.) Add a channel
3.) Click "OK" to create the list
4.) Edit the new list
5.) Click on users
6.) Uncheck all users of the list and apply user settings with "set"
7.) Click on "OK" to return to favorite lists

The newly created favorite list won't be displayed anymore for none of the users but still exists. The used name is locked.

**Comment by jp112sdl** [comment]
@McPan Thanks, now it is clear and reproducable!

**Comment by gitandy** [comment]
Hi,
I manged to get a list of all favorites with a script
`var favs=dom.GetObject(ID_FAVORITES);
    string fav;
    foreach(fav,favs.EnumUsedNames())
    {
      var fav_id = favs.Get(fav).ID();
      WriteLine(fav+":"+fav_id);
    }`

and manually got rid of the hidden favorites with:

`dom.DeleteObject(3985);
dom.RTUpdate(true);`

**Comment by MichaelN0815** [comment]
Also wenn man von einer vorhandenen Favoritenliste alle User entfernt, Dann ist klar, daß die immer noch existiert. Der richtige Weg wäre diesen Favoriten zu löschen. 

Man müsste also entweder das entfernen des letzten Users verhindern oder dieses als Trigger zum Löschen der Liste interpretieren.

**Comment by jp112sdl** [comment]
> Also wenn man von einer vorhandenen Favoritenliste alle User entfernt, Dann ist klar, daß die immer noch existiert. Der richtige Weg wäre diesen Favoriten zu löschen.

Das darf trotzdem nicht passieren. Und ich habe in meiner Spiele RM auch Favoritenlisten angezeigt, die keinem Nutzer zugeordnet sind.
<img width="1276" alt="Bildschirmfoto 2022-10-04 um 16 45 19" src="https://user-images.githubusercontent.com/18190139/193850595-40291eed-be08-4c4b-a5a0-d7f768a5c5e9.png">

**Comment by gitandy** [comment]
Hi all,
I think theres a misunderstanding. No user was changed. The list was just deleted and left hidden so that the name couldn't be used once again.
I'll try to reproduce once again.
KR
