### ISSUE TITLE
HmIP-RFUSB - Geräte anlernen und steuern nicht möglich

### ISSUE THREAD

**Issue by Holger-H** [jens-maus/RaspberryMatic#1974]
### Describe the issue you are experiencing

HomeMatic  Geräte können nicht angelernt oder gesteuert werden.

Das Anlernen eines _HM-CC-RT-DN_ Thermostats führt nicht zu einer Meldung im Posteingang. Am Thermostat wird nach dem Starten vom Anlernen **AC** und das Antennen Symbol angezeigt (verbunden).  Das Thermostat  hat eine Verbindung aber im RaspberryMatic ist das Gerät nicht vorhanden. Nach X Versuchen und einem Neustart vom RaspberryPi wurde das Thermostat im Posteingang angezeigt, jedoch kann es nicht gesteuert werden.
Nach den Anlernversuchen wurde irgendwann einmal gemeldet das die Firmware  für _HM-CC-RT-DN_ (1.4) veraltet ist, jedoch ohne das Thermostat  anzuzeigen.

Das Wiederherstellen eines Backups aus der CCU2 führte dazu das alle Geräte vorhanden sind, aber nicht gesteuert werden können.

In der Geräteübersicht wird die Signalstärke mit -80 dBm angezeigt.
Der HmIP-RFUSB ist an einem USB2 Port mit ca. 1,5m Kabel angeschlossen, 

Ein angelernter HM-ES-PMSw1-Pl kann angesteuert werden.

Das Systemprotokoll enthält keine Einträge.
Das Thermostat  wurde in vor dem Einbinden in RaspberryMatic aus der CCU2 mit der Option "auf Werkseinstellung zurücksetzen" gelöscht.

### Describe the behavior you expected

Geräte sollte angelernt und gesteuert werden können.

### Steps to reproduce the issue

RaspberryMatic in HomeAssistant installieren, HmIP-RFUSB verbinden und neues Gerät anlernen.

### What is the version this bug report is based on?

3.65.8.20220831

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Mounting /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying host system: oci, OK
Initializing RTC Clock: no hardware found
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, XXX.XX.XX.X, OK
Identifying Homematic RF-Hardware: ....HmRF: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-0000:01:00.0-1.3, HmIP: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-0000:01:00.0-1.3, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: 4.4.18, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: .OK
Starting rfd: ....................ERROR
Starting HMIPServer: .............OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting Third-Party Addons: OK
find: /usr/local/etc/monit*.cfg: No such file or directory
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.65.8.20220831 (raspmatic_oci_arm64)


***** hmserver.log *****
2022-10-05 14:26:26,230 de.eq3.cbcs.server.core.vertx.KeyServerWorker ERROR [vert.x-worker-thread-2] Missing key server configuration parameter (Network.Key) for  mode: KEYSERVER_LOCAL 
2022-10-05 14:26:37,701 de.eq3.ccu.bidcos.dispatcher.BidCosRpcDispatcher ERROR [Thread-2] BidCosCache could not be initialized 
2022-10-05 14:26:37,703 de.eq3.ccu.bidcos.dispatcher.BidCosRpcDispatcher ERROR [Thread-2] java.net.ConnectException: Connection refused (Connection refused) 
2022-10-05 14:26:39,295 de.eq3.ccu.bidcos.dispatcher.BidCosRpcDispatcher ERROR [Timer-2] Could not register BidCos-RF_java 
2022-10-05 14:26:44,284 de.eq3.ccu.bidcos.dispatcher.BidCosRpcDispatcher ERROR [Timer-2] Could not register BidCos-RF_java 
2022-10-05 14:26:49,286 de.eq3.ccu.bidcos.dispatcher.BidCosRpcDispatcher ERROR [Timer-2] Could not register BidCos-RF_java 
2022-10-05 14:26:54,284 de.eq3.ccu.bidcos.dispatcher.BidCosRpcDispatcher ERROR [Timer-2] Could not register BidCos-RF_java 
2022-10-05 14:26:59,284 de.eq3.ccu.bidcos.dispatcher.BidCosRpcDispatcher ERROR [Timer-2] Could not register BidCos-RF_java
```

### Additional information

Firmware:
- HmIP-RFUSB:  4.4.18
- HM-CC-RT-DN: 1.5
- HM-ES-PMSw1-Pl: 2.6

Der RasperberryPi 4 verwendet eine SSD, welche in einem Argon-Case verbaut ist.

**Comment by jens-maus** [comment]
Duplicate of #1373 1942
