### ISSUE TITLE
Umzug von Pi3 ---> Pi2 (ja, von 3 zurück auf 2)

### ISSUE THREAD

**Issue by Torben80** [jens-maus/RaspberryMatic#198]
Hallo, da ich entweder zu doof zum Suchen bin ODER es wirklich noch keiner gemacht hat, hier die Frage.

Wie ziehe ich mit meinem Pi3 zum Pi2 um?

Hintergrund: Ich habe einen Pi2 liegen, den ich nicht mehr brauche, und einen Pi3, den ich jetzt brauche (für andere Dinge).

Meine RaspberryMatic läuft auf dem Pi3 mit Lan-Kabel am Netz. Jetzt möchte ich gerne umziehen, zum Pi2.

Selbst di micrSD kann mit getauscht werden...

Was wäre nun die leichteste Variante (Achtung Frau überwacht alles, dass auch ja alles bleibt wie es ist und keine Ausfälle entstehen ;-) ), jetzt auf den Pi2 umzuziehen?

Vielen Dank fürs Lesen & Grübeln UND evtl auch Lachen.

Gruß Torben

**Comment by cyber-age** [comment]
Backup erstellen, raspberry matic für pi 2 auf eine sd karte brutzeln, einstecken und starten, backup einspielen. 

So würde ich es versuchen, zur Sicherheit würde ich eine frische/andre sd karte nehmen damit man einen fall back hat...

**Comment by jens-maus** [comment]
Tschuldigung, aber das hier ist kein Support-Forum sondern ein Bug/Issue-Tracker. Solche Fragen gehören ins HomeMatic-Forum.
