### ISSUE TITLE
3.65.11.20221005 - Status und Bedienung - Systemvariablen - Spalte Status zeigt "if(action == "dcCreate") { Call("datapointconfigurator.fn::dcCreate()"); }"

### ISSUE THREAD

**Issue by TeraX** [jens-maus/RaspberryMatic#1981]
### Describe the issue you are experiencing

Sobald eine Systemvariable automatisch aktualisiert wird, wird auf der Seite "Status und Bedienung" - "Systemvariablen" der Code 
`if(action == "dcCreate") { Call("datapointconfigurator.fn::dcCreate()"); }`
unterhalb der Variable angezeigt, welche automatisch aktualisiert wurde.

Im Screenshot sieht man, dass ein Teil der Variablen diesen Code enthalten.
Ruf man die Seite neu auf, ist dieser erstmal nicht zu sehen.

### Describe the behavior you expected

Zeige nur den Variablen Status ohne Code

### Steps to reproduce the issue

1. Öffne Menü Status und Bedienung 
2. Öffne Menüeintrag Systemvariablen
3. Warte bis eine Systemvariable automatisch aktualisiert wird und prüfe den Status der betroffenen Variable

Ansicht nach Variablenaktualisierung
![image](https://user-images.githubusercontent.com/912577/194504083-de2b6c1d-47dc-4bf2-8bfa-e13a4d1fc52e.png)

Ansicht nach Aufruf / Neuladen der Systemvariablen - Soll Ansicht
![image](https://user-images.githubusercontent.com/912577/194504263-9fe05143-0b26-4497-bacc-4741eccb3d64.png)

### What is the version this bug report is based on?

3.65.11.20221005

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Ansicht nach automatischer Variablenaktualisierung:
```

**Comment by jens-maus** [comment]
Bitte neustart durchführen und Browser-Cache löschen. Wenn danach das Problem immer noch existent ist das bitte hier melden. Solche Probleme sind wie die hin- und wieder stattfindende doppelte  darstellung von Elementen in der WebUI auf noch nicht eingrenzbare Probleme in ReGaHss selbst zurückzuführen. Siehe https://github.com/jens-maus/RaspberryMatic/issues/1467

**Comment by TeraX** [comment]
Neustart der CCU und löschen des Browser-Cache hat das Problem behoben.
Vielen Dank
