### ISSUE TITLE
Sensoren und Aktoren aus dem Bereich Heizung seit 3.65.11.20221005 Update nicht connected

### ISSUE THREAD

**Issue by McSpitz** [jens-maus/RaspberryMatic#1989]
### Describe the issue you are experiencing

Ich habe das Online Update auf die Version 3.65.11.20221005 durchgeführt. Soweit lief alles prima ab. Leider ist es dazu gekommen, dass auffällig die Sensoren um Heizung, also HMIP WTH2 sowie die Aktoren HMIP-FAL230 und HMIP-FALMOT nicht mehr an der "Raspberrymatic" hingen, allerdings auch ohne Systemmeldung. Ich musste bei den Geräten durch Entnahme der Batterie oder Stecker ziehen einen Reconnect erzwingen.
Durch Änderungen an der Config konnte auch kein Reconnect erzwungen werden, ebenfalls auch durch Änderungen am Sensor selbst nicht.

### Describe the behavior you expected

Ich hätte erwartet, dass sich die Geräte wieder korrekt anmelden bzw. die Raspberrymatic eine Systemmeldung über nicht erreichbare Geräte erzeugt. Beides war nicht der Fall. Das "Nicht Funktionieren" habe ich zufällig herausgefunden.

### Steps to reproduce the issue

1. Online Update durchführen

### What is the version this bug report is based on?

3.65.11.20221005

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
keine weiteren Infos
```

**Comment by jens-maus** [comment]
Wie schon sehr sehr oft thematisiert ist ein RaspberryPi4 eine sehr ungünstige Platform für die Nutzung mit einem GPIO basierten Funkmodul wie dem HM-MOD-RPI-PCB. Bitte daher einfach das hier durchgehen und entsprechend Veränderungen vornehmen:

https://homematic-forum.de/forum/viewtopic.php?f=31&t=65293

Und das geschilderte Verhalten ist definitiv kein Bug bzw. technisches Problem innerhalb von RaspberryMatic sondern gehört (wenn schon thematisiert) in einen Diskussionsbeitrag verwandelt.
