### ISSUE TITLE
WebUI: Localization fails on initial rooms, functions and system variables

### ISSUE THREAD

**Issue by mdzio** [jens-maus/RaspberryMatic#199]
**Steps to reproduce:**
Install a fresh RaspberyMatic V2.29.23.20171118.
Rename function _Energiemanagement_ to _Energiemanagement2_ and then back to _Energiemanagement_.
Execute skript:
```
WriteLine(dom.BuildLabel());
string funcId; foreach(funcId, dom.GetObject(ID_FUNCTIONS).EnumUsedIDs()) {
  var func = dom.GetObject(funcId);
  if (func) {
   WriteLine(func.ID() # "	" # func.Name() # "	" # func.EnumInfo());
  }
}
```
Result:
```
R1.00.0388.0124
1222	funcButton	
1223	funcCentral	
1217	funcClimateControl	
1224	Energiemanagement	
1219	funcEnvironment	
1216	funcHeating	
1215	funcLight	
1221	funcLock	
1220	funcSecurity	
1218	funcWeather
```
Expected result:
```
1222    Taster
1223    Zentrale
1217    Klima
...
```

**Also seen on other versions:**
```
1220	${funcCentral}
1214	${funcClimateControl}
1221	${funcEnergy}
1216	${funcEnvironment}	
```
```
17035	${sysVarRainToday}
```

**Work around:** 
Rename object and then rename it back again.

This issue may be associated with issue #183.

Reference:
https://homematic-forum.de/forum/viewtopic.php?f=19&t=22802&start=10#p373701

**Comment by jens-maus** [comment]
How is this handles on a plain CCU2? It should behave exactly the same, I guess.

Another question is how do you think it should behave? Should it initially already put the german names there?

**Comment by BadenPower** [comment]
It is'nt a bug, but normal behavior.
The returned names are the original placeholder names, so the visible output can be translated before displaying it in e.g. WebUI.

The only thing that was changed, are the names of rooms and functions.
In earlier versions they look like => ${funcClimateControl}. In newer versions the names are stored without dollar-sign and without braces => funcClimateControl
.

**Comment by mdzio** [comment]
I was also able to reproduce the error with a CCU2 V2.29.23 Legacy-ReGa.

In the HomeMatic forum I have opened a [corresponding topic](https://homematic-forum.de/forum/viewtopic.php?f=38&t=40407). Many users and other third-party software (e. g. OpenHAB, XML-API add-on) are also affected.

Even though it was the normal behaviour of the CCU up to now, I think it should be considered a bug. The method Name() should always return the name displayed in the Web UI, whether it is initial or not.

Maybe the translation of the placeholders can be determined via HomeMatic script. However, this would mean correcting the error in all external applications instead of fixing it centrally.

The search for objects is also affected. Although a function "Licht" is displayed in the web UI, it cannot be searched by name:
```
var func=dom.GetObject(ID_FUNCTIONS).Get("Licht");
if (func) {
   WriteLine(func.ID() # "	" # func.Name() # "	" # func.EnumInfo());
} else {
WriteLine("Not found");
}
```
Result:
```
Not Found
```
Remark: A search for "funcLight" succeeds.

**Comment by sailor79** [comment]
fyi:
i)
Here i summarized a workaround month ago: [Link](https://homematic-forum.de/forum/viewtopic.php?f=19&t=22802&start=10#p373701)
ii)
Additionally i opened a ticket@eq3 in july/2017. 
Ticketnumber: EED0F7659AAF8, EQ3_SUPPORT-999. After getting no feedback i asked yesterday after status with the answer that the topic is still in progress

**Comment by jens-maus** [comment]
Well, I can understand that the current situation looks somewhat strange. The question is, however, how to solve it or if there is a general solution at all. The reason for these identifiers have been explained already: being the possibility to display a different translation if you switch languages in the WebUI. You can just test this by switching the language of the WebUI using the user configuration settings in the WebUI. If you switch there to english it will immediately translate the default names ('funcXXXX') to english. However, if you rename one of these items beforehand (e.g. "Energiemanagement" -> "Energiemanagement") then switching to english will keep the german name.

While I fully understand that these generic "funcXXXX" "sysVarXXXX" names look somewhat strange and are also somehow inconvenient, I currently don't know how we can avoid them or programmatically provide a solution that does not mean that we will lose the multi-language functionality.

The only solution I can currently think of is, that upon the first initial start of a CCU the WebUI will present a requester where a user would have to select his preferred language and then the WebUI will automatically fix the names to the selected language. Or are there some other ideas?

**Comment by mindhunt** [comment]
Notice: Renaming is not mandatory, just click in every field one after the other and then log off to save.
--
@jens-maus 
Interesting behavior after i set up a blank new raspimatic with rev.18.11. an hour ago:
i) After 1st boot: No rooms, no lots, no standard Sysvars (Alarmzone, Anwesenheit) available
ii) Set up localization (geodata and DE) and network, reboot
iii) all initial rooms, lots and sysvars are available

**Comment by sailor79** [comment]
Notice: 
Renaming is not mandatory, just click in every field one after the other and then log off to save.

@jens-maus
Interesting behavior after i set up a blank new raspimatic with rev.18.11. an hour ago:
i) After 1st boot: No rooms, no lots, no standard Sysvars (Alarmzone, Anwesenheit) available
ii) Set up localization (geodata and DE) and network, reboot
iii) all initial rooms, lots and sysvars are available

**Comment by jens-maus** [comment]
@sailor79 It is clear that clicking in every field is enough to actually internally rename these objects from 'funcXXXX' to a fixed name. However, the question is how we can possibly get rid of this necessity. Currently, I think the mentioned popup upon first connection to the WebUI might actually be a valid solution. Or does anyone have a different suggestion?

**Comment by sailor79** [comment]
The suggestion would be a good workaround until eq3 will fix the topic generic whenever
But as in many forum-topics since years is documented, the problem should be more differentiated between
i) Clear names vs. localization (see this topic), all rooms, lots, standard Sysvars available
ii) Missing (all or some) rooms, lots, standard Sysvars (clear names and EnumIDs' too!)
iii) Both i) and ii) together

Thats only from a users experience point of view; but in what way these 3 points mentioned above would be affected by your proposed solution i cannot estimate, but to point to :-)

**Comment by jens-maus** [comment]
@sailor79 If I am not fixing it, eQ3 won't fix it ;)

Regarding (ii), this might be caused due to non synchronous execution of the /bin/hm_startup script upon first start of ReGa. I will try to investigate this further, but I think a simple reboot should usually solve this in most cases.

**Comment by sailor79** [comment]
@jens-maus I feared that :-)

Regarding ii) i could repeat this behavior also after several boots. As far as i can remember, there were several people, but hard to verify if the problem exist from inital boot without realise it.

Perhaps a initial boot as you proposed with asking after localization, and one automatic immediate reboot (with waiter between) and after verifying of "right" exisiting rooms, lots and Sysvars and if necessary correction and 2nd automatic reboot (before the user can access 1st time the webui )could bypass later issues; even though it sounds more like a symtom-based workaround.

**Comment by mdzio** [comment]
If a dialog is presented to the user at the first start of the CCU which queries the language, this is in my opinion a good solution.

**Comment by robdg80** [comment]
One Idea will be to add new RegaHss Script functionality which will be able to translate a name to a placeholder.

Example: NameToPlaceholder("Licht") should deliver functionLight

So the script could handle the placeholder names and real names.

**Comment by jens-maus** [comment]
see https://homematic-forum.de/forum/viewtopic.php?f=65&t=50698&p=508756#p508756 for reference to other `${...}` being used in devices (e.g. to count amount of rain, etc.)
