### ISSUE TITLE
Device HmIP-PSM-2 not found in Home Assistant

### ISSUE THREAD

**Issue by Columbus1964** [jens-maus/RaspberryMatic#1993]
### Describe the issue you are experiencing

The device HmIP-PSM-2 is not disvcovered in Home Assistant 
I use Raspberrymatic 3.65.11.20221005 and Home Assistant 2022-10-3
 

### Describe the behavior you expected

The device should be exist as entity

### Steps to reproduce the issue

1.I restart the RaspberryMatic and the Home Assistant 
2. No device found
3.
...

### What is the version this bug report is based on?

3.65.11.20221005

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
No
```

**Comment by jens-maus** [comment]
Which base platform are using? Which Pi/ODROID, whatsoever?!?

And please note in advance that device tech-in issues are in 99% of all cases local issues due to either user doing it wrong or due to the fact that you have RF interferences where the rf module is not able to reach the device. This is definitely NO bug, thus does not belong here but in a discussion fora!

**Comment by Columbus1964** [comment]
Hallo Mr. Maus

Sorry for declaring it an error.

I'm using Home Assistant in a VM on a Synology and the RasberryMatic add-on inside Home Assistant.

The device has been successfully trained in the RasberryMatic and also works, it is just not transferred to the Home Assistant. I figured that because it's relatively new, it might need some additions.

Many greetings

Columbus1964

 

Von: Jens Maus ***@***.***> 
Gesendet: Mittwoch, 12. Oktober 2022 09:27
An: jens-maus/RaspberryMatic ***@***.***>
Cc: Columbus1964 ***@***.***>; Author ***@***.***>
Betreff: Re: [jens-maus/RaspberryMatic] Device HmIP-PSM-2 not found in Home Assistant (Issue #1993)

 

Which base platform are using? Which Pi/ODROID, whatsoever?!?

And please note in advance that device tech-in issues are in 99% of all cases local issues due to either user doing it wrong or due to the fact that you have RF interferences where the rf module is not able to reach the device. This is definitely NO bug, thus does not belong here but in a discussion fora!

**Comment by Baxxy13** [comment]
If you are using the Homematic(IP) Local Integration then this is the wrong place for an issue-ticket.

Place your Ticket [here](https://github.com/danielperna84/hahomematic/issues)

**Comment by Columbus1964** [comment]
Hallo Baxxy13,
I use the RaspberryMatic AddOn and not the Homematic AddOn in Home Assistant

**Comment by jens-maus** [comment]
> Hallo Baxxy13, I use the RaspberryMatic AddOn and not the Homematic AddOn in Home Assistant

Sorry, but you are mixing things up, thus lack some knowledge regarding difference in "integration" vs. "addon". Please consult more documentation and read especially through ALL the installation documentation on the RaspberryMatic add-on **including** the "Homematic(IP) Local integration" part. See: https://github.com/jens-maus/RaspberryMatic/wiki/Installation-HomeAssistant
