### ISSUE TITLE
a short question

### ISSUE THREAD

**Issue by TMHBOFH** [jens-maus/RaspberryMatic#201]
Hi,
**Thanks for the great project.**

Does the shop raspberrymaticshop.de(raspberrymaticshop.com) support this project?

best regards

**Comment by jens-maus** [comment]
Not officially. RaspberryMatic is open source and as such anyone can sell whatever they want. However, I already asked the makers of this shop to at least provide some donations based on their sold numbers. Unfortunately, I haven't received a single donation yet.

BTW: This is no discussion fora but a bug tracker, so please use the homematic forum for such requests.
