### ISSUE TITLE
UI von CCU addon "CCU-Jack" unter Homeassistant mit Raspberrymatic nicht aufrufbar (404, Port 2121)

### ISSUE THREAD

**Issue by guenter-ms** [jens-maus/RaspberryMatic#2011]
### Describe the issue you are experiencing

Hallo,

ich habe auf dem pi3b das Raspberrymatic addon unter Homeassistant erfolgreich installiert.

Dann habe ich das CCU-addon "CCU-Jack" über die CCU-Zentrale/Systemeinstellungen/Zusatzsoftware ebenfalls erfolgreich installiert. https://github.com/mdzio/ccu-jack

Wenn ich dann den neuen Button "CCU-Jack" betätige, erhalte ich im Browser eine 404-Fehlermeldung, not found.

Das Problem: Die ports 2121 (+2122 +1883 +8883) sind nicht aufrufbar (404), ob wohl in der Firewall der CCU freigegeben, siehe auch https://github.com/mdzio/ccu-jack/wiki/Installation-AddOn

Installation:

![image](https://user-images.githubusercontent.com/6253315/197530440-40d5849a-d9b0-40a2-8acb-e3058740f04e.jpeg)

Fehlermeldung:

![image](https://user-images.githubusercontent.com/6253315/197530480-a3040b1b-86a8-49e9-bd1a-2cc5f1f9c12a.jpeg)

Firewall-Config:

![image](https://user-images.githubusercontent.com/6253315/197530539-42cda5e7-9430-4db1-8d6b-76c805936a05.jpeg)

Das Prob habe ich bereits beim CCU-Jack gemeldet (https://github.com/mdzio/ccu-jack/issues/104), dort wird auf dieses Projekt verwiesen.

Habe mal das respository von https://github.com/jens-maus/RaspberryMatic runtergeladen und entzippt.

Im folder home-assistant-addon finde ich die Datei config.yaml.

![image](https://user-images.githubusercontent.com/6253315/197532218-60285dbd-f7ca-4505-827a-f46daafc015a.jpeg)

Diese Datei enthält Konfigurationsinfos für die ports.

Die CCU-Jack ports sind da nicht enthalten (2121,...)

[config.yaml.pdf](https://github.com/jens-maus/RaspberryMatic/files/9851842/config.yaml.pdf)

Demzufolge kann ich in der HA-Raspberrymatic-Konfiguration diese ports auch nicht freigeben:

![image](https://user-images.githubusercontent.com/6253315/197532718-c9836ba8-c60f-44aa-be35-c98341c37ee0.jpeg)

Was kann ich tun?

### Describe the behavior you expected

Erwartet hätte ich die UI des CCU-Jacks: https://github.com/mdzio/ccu-jack/wiki/Web-UI

Ferner müssten die weiteren Ports erreichbar sein, z.B. von Nodered aus.

### Steps to reproduce the issue

1. Install Homeassistant. 
2. Install RaspberryMatic addon
3. Install CCU-Addon "CCU-Jack" (https://github.com/mdzio/ccu-jack)
4. Press "CCU-Jack" Button in Systemsteuerung der CCU

### What is the version this bug report is based on?

3.65.11.20221005

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
see screenshots below
```

### Additional information

![Bildschirmfoto 2022-10-24 um 15 14 24](https://user-images.githubusercontent.com/6253315/197534131-6f8a9726-de9d-49ad-9069-1217c7440f9c.jpg)

![Bildschirmfoto 2022-10-24 um 15 16 48](https://user-images.githubusercontent.com/6253315/197534636-63979117-22ce-4142-8f96-f724a92dd34e.jpg)

![Bildschirmfoto 2022-10-24 um 15 13 43](https://user-images.githubusercontent.com/6253315/197533958-564efb1c-b073-47a1-9c77-fe29801f4ed9.jpg)

**Comment by jens-maus** [comment]
Das wird nicht das Problem sein. Der Punkt ist, das die Ports die CCU-Jack anscheinend von "aussen" zugänglich haben möchte auch im RaspberryMatic addon einstellbar/konfigurierbar sein müssen und das sind sie aktuell in der Addon konfig nicht wie man in den Screenshots sehen kann. Ob man das ermöglichen kann/will muss man dann mal sehen...

**Comment by mdzio** [comment]
Generell betrifft das alle CCU-Add-Ons (z.B. auch CUxD), die irgendwelche Netzwerkports nach außen bringen wollen (z.B. für einen eigenen Web-Server).

**Comment by Baxxy13** [comment]
Mal ganz nüchtern betrachtet macht es m.E. wenig Sinn den CCU-Jack innerhalb des RaspberryMatic-HA-AddOns zu installieren. 

MQTT kann man auch direkt in HA nutzen und alle Geräte (außer CUxD) und SysVars holt die Homematic(IP) Local - Integration in den Homeassistant. CUxD-Geräte wiederum kann man auch mittels NodeRed-HA-AddOn aus dem RaspberryMatic-HA-AddOn in den Homeassistant holen.

Da ich aber Fan vom Jack bin und frei nach dem Motto "jeder wie er mag" plädiere ich für eine Aufnahme der, für den Jack nötigen, Ports in die AddOn-Konfiguration.

**Comment by guenter-ms** [comment]
Naja, der Jack macht schon sehr viel Sinn, wenn man berücksichtigt, dass [Redmatic ](https://github.com/rdmtc/RedMatic) nicht mehr supported wird und auf einem uralten Stand ist. Da hat man mit [ptweety/node-red-contrib-ccu](https://github.com/ptweety/node-red-contrib-ccu) in Verbindung mit CCU-Jack eine geniale Einbindung der CCU in nodered. Da bitte mal lesen: https://github.com/mdzio/ccu-jack

Und wenn ich das richtig verstanden habe, sind auch andere CCU-addons betroffen, wenn sie eine eigene UI haben. Und davon gibt es eine ganze Menge (CuxD, Sonos Player, Highcharts oder diese Sammlung: https://www.homematic-inside.de/software/tag/Zusatzsoftware). 

Was also spricht dagegen, wenn benötigte ports frei konfigurierbar sind, so wie in der firewall von RaspberryMatic?

**Comment by jens-maus** [comment]
> Was also spricht dagegen, wenn benötigte ports frei konfigurierbar sind, so wie in der firewall von RaspberryMatic?

Da spricht nicht viel dagegen. Nur, das man bei einem HomeAssistant addon nicht ports vom user komplett frei/beliebig konfigurierbar/umleitbar machen kann, sondern eben wie die anderen die beim aktuellen Addon konfigurierbar sind explizit angeben muss. D.h. Also es muss hier eine feste Liste der Ports angegeben werden die vom Nutzer für eine Umleitung konfiguriert werden kann.

**Comment by guenter-ms** [comment]
OK, aber warum muss die Liste "fest" sein statt ein individuelles mapping ergänzend zu der Liste (die ja hilfreich ist) zu ermöglichen? In einer Non-HA Installation gibt es diese Beschränkung des RaspberryMatic eh nicht. Und wer sich seine Installation zerschießt, hat ja immer ein Backup dafür :-)

However, können die 4 ports des CCU-Jacks denn irgendwie freigeschaltet werden? Wäre ein Workaround zum Testen möglich?

Gruß G

**Comment by jens-maus** [comment]
> OK, aber warum muss die Liste "fest" sein statt ein individuelles mapping ergänzend zu der Liste (die ja hilfreich ist) zu ermöglichen?

Weil das nunmal so in HomeAssistanz funktioniert.

> However, können die 4 ports des CCU-Jacks denn irgendwie freigeschaltet werden? Wäre ein Workaround zum Testen möglich?

Doch können und werden sie auch. Deshalb ist das Ticket ja auch entsprechend geflaggt. Musst du halt nur Geduld aufbringen. Wenn dann werden diese aber manuell vom Nutzer freigeschaltet werden müssen genauso wie das bei den anderen Ports gerade läuft!

**Comment by guenter-ms** [comment]
Supi, Danke!

**Comment by andbez** [comment]
Gleiches Thema habe ich auch. Vielen Dank.

**Comment by guenter-ms** [comment]
Danke!!
