### ISSUE TITLE
Diagrams not working correctly with wall theremostats

### ISSUE THREAD

**Issue by martinm95** [jens-maus/RaspberryMatic#202]
There seems to be a problem with diagrams when logging HM-IP wall thermostat data. It isn't saving data although there are no RF signal problems. With radiator thermostats, diagrams work great, no data loss. Have anyone experienced a similar problem and is there any fix for it right now?

**Comment by jens-maus** [comment]
Please ask such questions in the homematic forum. This is a bug/issue tracker and no support forum.

**Comment by drose28357** [comment]
watch this on the OCCU issue tracker. seems to be similar.
https://github.com/eq-3/occu/issues/59
