### ISSUE TITLE
Proxmox 7.2 - HB-RF-USB-2 mit HM-MOD-RPI-PCB wird nicht erkannt

### ISSUE THREAD

**Issue by wolwin** [jens-maus/RaspberryMatic#2022]
### Describe the issue you are experiencing

Nach einigen Tests kann ich sagen, dass in meiner Proxmox 7.2 Installation die aktuelle Raspberrymatic (installiert mit der vereinfachten Proxmox Installation) die Kombination von 'HB-RF-USB-2' mit 'HM-MOD-RPI-PCB' nicht als RF-Hardware erkennt. Gleichwohl wird die Kombination von 'HB-RF-USB-TK' mit 'HM-MOD-RPI-PCB' korrekt erkannt.

Die Hardware Kombination von 'HB-RF-USB-2' mit 'HM-MOD-RPI-PCB' wird an einem RPI3+ mit aktuelle Raspberrymatic problemlos erkannt. 

Unter Proxmox wurden alle USB-Kombinationen (USB2 / USB3 Hardware-Ports + Proxmox Einstellung USB3-Support) ohne Erfolg durchprobiert.

Als Hardware wird eine ZBOX CI327 nano eingesetzt:
https://www.zotac.com/at/product/mini_pcs/ci327-nano

Der ursprüngliche Thread findet sich auch im HM-Forum:
https://homematic-forum.de/forum/viewtopic.php?f=76&t=58988&start=90#p739204

### Describe the behavior you expected

Da die HB-RF-USB-2 Platine korrekt von Proxmox und auch der Raspberrymatic erkannt wird, sollte auch die Initialisierung des RF-Funkmoduls funktionieren.

### Steps to reproduce the issue

**Kombination 'HB-RF-USB-2' mit 'HM-MOD-RPI-PCB'**
boot.log:
```
fsck 1.46.5 (30-Dec-2021)
userfs: clean, 1628/4857856 files, 950338/19399406 blocks
Identifying host system: ova-KVM, OK
Initializing ZRAM Swap: OK
Initializing RTC Clock: onboard, OK
Starting acpid: OK
Running sysctl: OK
Initializing urandom: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Populating /dev using udev: done
Init onboard LEDs: init, OK
Starting qemu-guest-agent: OK
Starting irqbalance: OK
Starting rngd: OK
Starting system message bus: done
Starting iptables: OK
Starting bluetooth: disabled
Starting network: eth0: link up, static, firewall, inet up, 192.168.100.64, wlan0: missing, OK
Starting Network Interface Plugging Daemon: eth0.
Starting chrony: OK
Identifying Homematic RF-Hardware: ...HmRF: n/a, HmIP: n/a, OK
Updating Homematic RF-Hardware: no GPIO/USB connected RF-hardware found
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting sshd: OK
Starting NUT services: OK
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: not required
Starting rfd: no BidCos-RF hardware found
Starting HMIPServer: ......OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting Third-Party Addons: OK
find: /usr/local/etc/monit*.cfg: No such file or directory
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.65.8.20220831 (raspmatic_ova)
```

/var/log/messages:
```
Oct 27 14:31:20 localhost kern.info kernel: [   12.739399] Free page reporting enabled
Oct 27 14:31:20 localhost kern.warn kernel: [   12.783240] generic_raw_uart: loading out-of-tree module taints kernel.
Oct 27 14:31:20 localhost kern.info kernel: [   12.823858] usb 2-1: DKey: 3565633630323430 3131616565393862 3664373632666439 3133666166396566
Oct 27 14:31:20 localhost kern.info kernel: [   12.823868] usb 2-1: HKey: 74c1c5ce7054c290 42d2617a1f9fa7be 5dc23c1aa6fc03ed 6bf84cf281032900
Oct 27 14:31:20 localhost kern.info kernel: [   12.823871] usb 2-1: SKey: e0baf435dbcc4fd4 6824654b5e5f050c 3e91bb446c1bbb11 607b8bd4da162236
Oct 27 14:31:20 localhost kern.info kernel: [   12.823874] usb 2-1: SKey: 3f54cc9a3f912120 d7fa2a118b56ed02 0bea294602538b87 aa528a05dae5264e
Oct 27 14:31:20 localhost kern.info kernel: [   12.823877] usb 2-1: PKey: f50048a8d7cc3f44 ae8460d13cf61d60 2dc161f5272a5876 88c996b27737fbae
Oct 27 14:31:20 localhost kern.info kernel: [   12.823879] usb 2-1: PKey: dd24b0aced521e88 cc457acb4b7c49a4 6745032ab2079847 becfb9f3af25d41f
Oct 27 14:31:20 localhost kern.info kernel: [   12.826533] usb 2-1: Successfully verified device signature
Oct 27 14:31:20 localhost kern.info kernel: [   12.826538] usb 2-1: Found HB-RF-USB-2 with serial 04206ce5b89eea119df267d6fe9faf31 at usb-0000:01:1b.0-1
Oct 27 14:31:20 localhost kern.info kernel: [   12.855259] raw-uart raw-uart: Reset radio module
Oct 27 14:31:20 localhost kern.info kernel: [   12.958959] raw-uart raw-uart: Registered new raw-uart device using underlying device HB-RF-USB-2@usb-0000:01:1b.0-1.
Oct 27 14:31:20 localhost kern.info kernel: [   12.960772] usbcore: registered new interface driver hb_rf_usb_2
Oct 27 14:31:21 localhost syslog.info syslogd exiting
Oct 27 14:31:21 VM-RM-T syslog.info syslogd started: BusyBox v1.35.0
Oct 27 14:31:21 VM-RM-T kern.notice kernel: klogd started: BusyBox v1.35.0 (2022-08-31 08:03:40 UTC)
Oct 27 14:31:22 VM-RM-T user.info firewall: configuration set
Oct 27 14:31:22 VM-RM-T kern.info kernel: [   14.292942] NET: Registered PF_INET6 protocol family
Oct 27 14:31:22 VM-RM-T kern.info kernel: [   14.294233] Segment Routing with IPv6
Oct 27 14:31:22 VM-RM-T kern.info kernel: [   14.294249] In-situ OAM (IOAM) with IPv6
Oct 27 14:31:22 VM-RM-T daemon.info ifplugd(eth0)[1308]: ifplugd 0.28 initializing.
Oct 27 14:31:22 VM-RM-T daemon.info ifplugd(eth0)[1308]: Using interface eth0/E6:28:55:72:83:37 with driver <virtio_net> (version: 1.0.0)
Oct 27 14:31:22 VM-RM-T daemon.info ifplugd(eth0)[1308]: Using detection mode: SIOCETHTOOL
Oct 27 14:31:22 VM-RM-T daemon.info ifplugd(eth0)[1308]: Initialization complete, link beat detected.
Oct 27 14:31:22 VM-RM-T daemon.info ifplugd(eth0)[1308]: Executing '/etc/ifplugd/ifplugd.action eth0 up'.
Oct 27 14:31:22 VM-RM-T daemon.warn ifplugd(eth0)[1308]: client: ifup: interface eth0 already configured
Oct 27 14:31:22 VM-RM-T daemon.info ifplugd(eth0)[1308]: Program executed successfully.
Oct 27 14:31:32 VM-RM-T daemon.notice ntpdate[1314]: step time server 193.203.3.170 offset +1.052001 sec
Oct 27 14:31:32 VM-RM-T daemon.info chronyd[1317]: chronyd version 4.2 starting (+CMDMON +NTP +REFCLOCK +RTC -PRIVDROP -SCFILTER -SIGND +ASYNCDNS -NTS -SECHASH +IPV6 -DEBUG)
Oct 27 14:31:32 VM-RM-T daemon.warn chronyd[1317]: Running with root privileges
Oct 27 14:31:32 VM-RM-T kern.info kernel: [   23.852285] raw-uart raw-uart: Reset radio module
Oct 27 14:31:38 VM-RM-T user.info qemu-ga: info: guest-ping called
Oct 27 14:31:49 VM-RM-T user.info qemu-ga: info: guest-ping called
Oct 27 14:31:53 VM-RM-T daemon.err xinetd[1411]: Unable to read included directory: /etc/config/xinetd.d [file=/etc/xinetd.conf] [line=14]
Oct 27 14:31:53 VM-RM-T daemon.crit xinetd[1411]: 1411 {init_services} no services. Exiting...
Oct 27 14:31:53 VM-RM-T auth.info sshd[1447]: Server listening on 0.0.0.0 port 22.
Oct 27 14:31:53 VM-RM-T auth.info sshd[1447]: Server listening on :: port 22.
Oct 27 14:31:53 VM-RM-T daemon.info upsmon[1458]: Startup successful
```

### What is the version this bug report is based on?

3.65.8.20220831 und 3.65.11.20221005

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

In der Kombination 'HB-RF-USB-2' mit 'HM-MOD-RPI-PCB' wird das Funkmodul korrekt erkannt:

boot.log:
```
Identifying Homematic RF-Hardware: ....HmRF: HM-MOD-RPI-PCB/HB-RF-USB@usb-0000:01:1b.0-1, HmIP: HM-MOD-RPI-PCB/HB-RF-USB@usb-0000:01:1b.0-1, OK
Updating Homematic RF-Hardware: HM-MOD-RPI-PCB: 2.8.6, not necessary, OK
```

**Comment by dg0ojo** [comment]
Das selbe Problem habe ich auch. Hab dann ein Backup einspielen müssen. Ähnliche Konfiguration Proxmox 7.2 und OVA und die USB-Platine mit dem Funkmodul.

**Comment by zaphod2** [comment]
Damit gehts.

Identifying Homematic RF-Hardware: ....HmRF: RPI-RF-MOD/HB-RF-USB@usb-0000:01:1b.0-1, HmIP: RPI-RF-MOD/HB-RF-USB@usb-0000:01:1b.0-1, OK
Updating Homematic RF-Hardware: RPI-RF-MOD: 4.4.22, not necessary, OK

**Comment by dg0ojo** [comment]
Nachdem ich jetzt die neue Version eingespielt und damit der Adapter auch nicht ging, hab ich mal einen anderen USB-Port benutzt. Jetzt funktioniert es. Vielleicht mag es keine Front-USB....?

**Comment by manny4566** [comment]
Hallo,

ich habe genau die gleiche Konstellation. Der rfd kommt nicht hoch.
Neues RaspberryMatic installiert unter Proxmox, der HM-MOD-RPI-PCB wird nicht erkannt. 
Der HB-RF-USB-2 wird erkannt.
Woran könnt das liegen ? 
Wenn ich noch was anderes an Infos liefern kann, lasst es mich wissen.
Danke

boot.log:
Identifying Homematic RF-Hardware: ...HmRF: n/a, HmIP: n/a, OK
Updating Homematic RF-Hardware: no GPIO/USB connected RF-hardware found

messages
Feb  2 13:53:20 localhost kern.info kernel: [    1.342227] usb 2-1: New USB device found, idVendor=10c4, idProduct=8c07, bcdDevice= 2.00
Feb  2 13:53:20 localhost kern.info kernel: [    1.342231] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Feb  2 13:53:20 localhost kern.info kernel: [    1.342232] usb 2-1: Product: HB-RF-USB-2
Feb  2 13:53:20 localhost kern.info kernel: [    1.342233] usb 2-1: Manufacturer: Alexander Reinert
Feb  2 13:53:20 localhost kern.info kernel: [    1.342234] usb 2-1: SerialNumber: 1ce22b1eb99eea1193546dd6fe9faf31

Feb  2 13:53:20 localhost kern.info kernel: [    9.520420] usb 2-1: DKey: 6531623232656331 3131616565393962 3664643634353339 3133666166396566
Feb  2 13:53:20 localhost kern.info kernel: [    9.520426] usb 2-1: HKey: c9dc068f4ac24235 7bfe4373680d0aad 53afc086f6987331 7b485c3e39c6d0f7
Feb  2 13:53:20 localhost kern.info kernel: [    9.520427] usb 2-1: SKey: 6680a37521644dc0 95e8067c938c4082 0a7a430b39e144d8 cc75bdf68c1397ea
Feb  2 13:53:20 localhost kern.info kernel: [    9.520429] usb 2-1: SKey: fb2fc3bcae68d3c2 81825a3fcd6f4d2b 9459c0d1d9c847a7 6b46e414f6aa1cca
Feb  2 13:53:20 localhost kern.info kernel: [    9.520430] usb 2-1: PKey: f50048a8d7cc3f44 ae8460d13cf61d60 2dc161f5272a5876 88c996b27737fbae
Feb  2 13:53:20 localhost kern.info kernel: [    9.520432] usb 2-1: PKey: dd24b0aced521e88 cc457acb4b7c49a4 6745032ab2079847 becfb9f3af25d41f
Feb  2 13:53:20 localhost kern.info kernel: [    9.521356] usb 2-1: Successfully verified device signature
Feb  2 13:53:20 localhost kern.info kernel: [    9.521358] usb 2-1: Found HB-RF-USB-2 with serial 1ce22b1eb99eea1193546dd6fe9faf31 at usb-0000:01:1b.0-1

**Comment by reddevil156** [comment]
Hallo zusammen,

ich kann das Problem genau so bestätigen.
Ich habe mir das HB-RF-USB-2 vor über 1 Monat gekauft und seitdem schon verschiedene Versionen von raspberrymatic und proxmox versucht, leider ohne Erfolg. Das Modul wird korrekt erkannt, jedoch fehlt dem 2102N auf der Platine irgendwas in der Initialisierung. Er gibt die 3,3V für den HM-MOD-RPI-PCB nicht frei.
Anscheinend ging das ganze ja mal. Hätte jemand eine Info für mich, in welcher Konstellation von raspberrymatic und proxmox (Versionen) das ganze funktioniert hat? Dann hätte ich einen Anhaltspunkt und könnte versuchen den Fehler einzugrenzen.

**Comment by jens-maus** [comment]
> Hab jetzt einen Workaround gefunden, die Ursache leider nicht. Der HM-MOD-RPI-PCB bekommt einfach keine anständige Spannung von 3,3V. Diese sollte durch den CP2102N nach der Initialisierung freigegeben werden, was allerdings nicht funktioniert. Ich hab jetzt die Platine mit einem Draht gepatched. Der Draht geht von der +3,3V Seite von C4/C3 an den Ausgang von Q1 bzw. Pin 1 des Headers. Somit umgehe ich Q1 und das PWREN-Signal komplett. Nicht Sinn der Sache aber für mich aktuell einzige Lösung.

Vielleicht kann @alexreinert sich diesbzgl. etwas zusammenreimen? Vielleicht gibt es da ja auch etwas was im Treiber des `HB-RF-USB-2` übersehen wurde bzw. in neueren Version problematisch wurde oder es gibt halt irgendein Hardwaredefekt auf deinem `HB-RF-USB-2`?!?!.... @alexreinert kann da bestimmt weiterhelfen.

**Comment by jens-maus** [comment]
@reddevil156 Du könntest auch mal probieren/testen ob in früheren Versionen von RaspberryMatic (wo ältere Versionen des kernel modules für das HB-RF-USB-2 bzw. generic_raw_uart dabei sind) besser funktionieren auch ohne dein Hardware-Patch. So z.B. einfach mal Version 3.67.10.20230225, 3.63.9.20220521 oder sogar 3.63.9.20220430 probieren. Wäre gut das als Feedback zu bekommen falls es hier doch irgendein Bug/Problem im Treiber gibt...

**Comment by alexreinert** [comment]
Q1 wird automatisch vom CP2102N angesteuert, wenn die USB Initialisierung erfolgreich durchgeführt wurde und der per USB Enumeration angeforderte Strom vom Host freigegeben wird. Das sind Mechanismen die komplett unabhängig vom Treiber in der Hardware und dem Linux USB Subsystem passieren.
Ich sehe daher nur zwei potentielle Ursachen: Defekt der HB-RF-USB-2 oder einen USB Port der nicht den angeforderten Strom liefern darf/will.

**Comment by alexreinert** [comment]
Interessant wäre auch ein Test auf einer Debian VM mit debmatic. Dann würde das dem Setup entsprechen, mit der ich den Treiber entwickle und primär teste.

**Comment by jens-maus** [comment]
> Interessant wäre auch ein Test auf einer Debian VM mit debmatic. Dann würde das dem Setup entsprechen, mit der ich den Treiber entwickle und primär teste.

Das ist eine gute Idee. Ich hab leider selbst kein `HB-RF-USB-2` übrig um das selbst zu testen, aber in meiner produktiven Umgebung funktioniert das `HB-RF-USB-2` mit aktuellen RaspberryMatic tadellos – zwar mit `RPI-RF-MOD`, aber da konnte ich noch keine Probleme feststellen. Oder könnte das auch am Kernel 6.x liegen der vielleicht ein anderes verhalten aufweist oder power management etwas stärker umsetzt? Wie gesagt, wenn @reddevil156 das nochmal mit früheren Versionen von RM testen könnte wäre das schon ein Anfang...

**Comment by jens-maus** [comment]
@reddevil156 Du sprichst in deinem letzten reply von `RPI-RF-MOD`. Dachte du nutzt ein `HM-MOD-RPI-PCB` am `HB-RF-USB-2`?

**Comment by reddevil156** [comment]
Habs eben editiert, bin schon selbst etwas durcheinander. Ist ein HM-MOD-RPI-PCB am HB-RF-USB-2

**Comment by jens-maus** [comment]
Weitere Frage wäre bzgl. RaspberryMatic: Wie weit bist du mit den Versionen zurückgegangen?

**Comment by jens-maus** [comment]
> Die letzte Version, die mir dein Download Script angeboten hat

Und das wäre? Ansonsten bitte einfach mal direkt von der releases-page das *.ova eine noch älteren Version herunterladen und entsprechend in Proxmox importieren...

**Comment by dg0ojo** [comment]
Auch wenn das nicht hilft: Ich hatte keine Lust mehr drauf und bin wieder auf einen Raspi umgezogen.

**Comment by jens-maus** [comment]
> ich schätze ich kann den Fehler jetzt eingrenzen. Bei den ganzen Versuchen hab ich mir den CP2102N gegrillt, ging dann gar nichts mehr. Der Gute hatte einen Kurzschluss und wurde heiß. Hab mir in China einen neuen Satz bestellt und aufgelötet.
> [...] und siehe da: Er funktioniert so wie er soll.

Das liest sich für mich jetzt aber nach einem Hardwareproblem das du ursprünglich mit deinem HB-RF-USB-2 hattest, denn wenn es jetzt aktuell mit der gleichen RaspberryMatic Version funktioniert nachdem du den CP2102N getauscht hast auf der Platine kann es ja eigentlich nicht an RaspberryMatic bzw. am treiber des HB-RF-USB-2 liegen der in RaspberryMatic integriert ist. Insofern könnte man dieses Ticket/Issue hier also zu machen, denn auch bei den anderen ist hier ja anscheinend "Stille" eingekehrt was dieses Problem hier angeht und es scheint mir kein systematisches Problem zu sein, sondern immer nur Einzelfallprobleme im lokalen Setup...

**Comment by alexreinert** [comment]
Ich fertige die Platinen nicht, daher kann ich nicht wirklich was dazu sagen.
Was ich aber sagen kann, den A02 kann man nicht vollständig lauffähig mit dem Simplicity Studio flashen, zumindest nicht mit meinen direkt von Silabs gelieferten Dev Samples. Ich habe daher einen eigenen Programmer, den ich aber bisher noch nicht soweit fertig habe, dass man den auf die Community loslassen könnte.

**Comment by reddevil156** [comment]
@alexreinert Besten Dank für das Feedback. Eine Frage hätte ich allerdings noch. Du schreibst "nicht vollständig lauffähig", bei mir funktioniert erstmal alles. Was genau geht denn nicht? Hab ich jetzt ein Risiko meine selbst geflashte Platine zu benutzen?
