### ISSUE TITLE
3.65.11.20221005 - HmIP-eTRV-2 in Heizungsgruppe - Entkalkungsfahrt und Fehlerposition nicht mehr einstellbar

### ISSUE THREAD

**Issue by imwebgefunden** [jens-maus/RaspberryMatic#2027]
### Describe the issue you are experiencing

Sofern ein HmIP-eTRV-2 in einer Heizungsgruppe eingebunden ist, können weder bei den Geräteeinstellungen des eTRV selbst noch in den Einstellungen der Heizungsgruppe die Werte für die Entkalkungsfahrt (Tag und Uhrzeit) noch die Ventilposition im Fehlerfall sowie die maximale Ventilöffnungsposition eingestellt werden. HW ist eine Original-CCU.

### Describe the behavior you expected

Verhalten wie in der Vorgängerversion - Einstellbarkeit der Werte mittels WebUI. Oder - und das wäre der negativste Fall - Aufführen der Änderungen im Changelog

### Steps to reproduce the issue

1. Einstellungen Geräte
2. Auswahl eines HmIP-eTRV-2, der einer Heizungsgruppe zugewiesen wurde oder Auswahl einer Heizungsgruppe
3. Klick auf den Einstell-Button

### What is the version this bug report is based on?

3.65.11.20221005

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
Leider nein
```

**Comment by Stefan-Linux** [comment]
Hi,
same with installation in VM on Synology NAS.
Using: 3.65.11.20221005 (ova)
Please fix it :)
Thanks, Stefan

**Comment by ALM007cs** [comment]
Same problem on CCU3 with RM.
The error occurs regardless of whether the HMIP-eTRV-2 is in a heating group or not.

**Comment by Baxxy13** [comment]
Der Fehler steckt auch in der CCU3-Firmware und wurde schon mehrfach an eQ-3 gemeldet. 
"Vermutlich" wird das in der nächsten CCU3-Firmware gefixt sein so das auch die nächste RM dahingehend keine Fehler mehr haben sollte.
Jetzt extra dafür einen Patch (für RM) zu bauen wäre m.E. unnützer Aufwand.

Wer die Werte dringend ändern muss kann das z.B. mit dem Homematic-Manager machen.

**Comment by steffen-mecke** [comment]
Ich habe das gleich Problem. Ich habe auch zwei HmIP-eTRV-2 Thermostat, welche im Frühjahr noch gut geregelt haben und welche nun nicht mehr regeln. Die Verbindung zur Zentrale ist in Ordnung, die Motoren laufen beim Adaptieren, nur öffnen die Ventile nicht(Motoren laufen nicht an), egal ob man Boost betätigt oder eine hohe Temperatur wählt. 

Eine Einstellung der Ventilöffnungsposition finde ich nicht mehr in den Einstellungen.

**Comment by Baxxy13** [comment]
> das ich bei meinen HmIP-eTRV-B den Ventil-Level nicht mehr einstellen, sondern nur noch anzeigen kann

Das ist so gewollt und hat mit dem Problem hier so gar nichts zu tun.
Hast du das Changelog der Integration nicht gelesen?
Oder den Abschnitt in der [Readme](https://github.com/danielperna84/custom_homematic/blob/devel/README.md#hmip-etrv--level-number-to-sensor-entity)?

**Comment by Headkillah** [comment]
> > das ich bei meinen HmIP-eTRV-B den Ventil-Level nicht mehr einstellen, sondern nur noch anzeigen kann
> 
> Das ist so gewollt und hat mit dem Problem hier so gar nichts zu tun. Hast du das Changelog der Integration nicht gelesen? Oder den Abschnitt in der [Readme](https://github.com/danielperna84/custom_homematic/blob/devel/README.md#hmip-etrv--level-number-to-sensor-entity)?

SORRY, Danke für den A***tritt, ich hab es echt nicht gelesen :/ Kommt davon, wenn man sich nicht wirklich darauf konzentriert was man macht ^^

**Comment by jens-maus** [comment]
@Baxxy13 Kannst du mal bitte schauen ob das Problem mit dem aktuellsten 3.67.x nightly build gelöst ist? Vielleicht ist hier eQ3 aktiv geworden?!?

**Comment by Baxxy13** [comment]
Ich habe leider kein eTRV-2, nur ein eTRV-B und mit diesem ist in der aktuellen Version soweit alles i.O.

**Comment by Stefan-Linux** [comment]
Hi,
(wo) gibt es den Nightly, am besten als OVA? (Ich find nix :( )
Dann würde ich das mal auf meiner Test VM zum Laufen bringen.
Danke, Stefan

**Comment by jens-maus** [comment]
> Hi, (wo) gibt es den Nightly, am besten als OVA? (Ich find nix :( ) Dann würde ich das mal auf meiner Test VM zum Laufen bringen.

Ist doch alles auf der Haupt GitHub seite zu erkennen. Einfach auf den "Snapshot Build" badge button drücken oder diesem Link hier folgen:

https://github.com/jens-maus/RaspberryMatic/releases/tag/snapshots

**Comment by Stefan-Linux** [comment]
Danke für den Link, und ja ist alles da. Sind mir nur zuviele Links gewesen ... ich hab nix mehr gesehen (Wald und Bäume ...)

OK, nö, geht nicht.
Die Menüs sehen an der Stelle leicht unterschiedlich aus, was die Aufteilung angeht.
Schaut für mich so aus, als ob da jemand an der Darstellung gespielt hat und nebenbei ein paar Optionen verschwunden sind. :(

**HmIP-eTRV-B**: Alles da (Entkalkungsfahrt, auch maximaler Ventil Öffnungsposition)
![image](https://user-images.githubusercontent.com/117478560/208790076-eb15a1fd-f0a0-4356-808d-518df1369bd7.png)
**HmIP-eTRV-2**, fehlt: Entkalkungsfahrt, Max V. Öffnungspos., Ventil in Fehl Position
![image](https://user-images.githubusercontent.com/117478560/208790258-43cb0fd8-0333-4ef5-bec7-4edcd446b21f.png)

Und noch das Versionsfoto, der Vollständigkeit halber (RaspberryMatic-3.67.9.20221220-f865fa-ova.zip):
![image](https://user-images.githubusercontent.com/117478560/208791147-010403fb-14b0-44e4-901b-50ad48b48bd0.png)

**Comment by Baxxy13** [comment]
Na dann hat eQ-3 nix dran gemacht. 
Laut Forum hatten aber einige User (mit CCU3) das direkt an eQ-3 gemeldet.

**Comment by jens-maus** [comment]
> Na dann hat eQ-3 nix dran gemacht. Laut Forum hatten aber einige User (mit CCU3) das direkt an eQ-3 gemeldet.

Dann müssen wir da ggf. vielleicht mit einem WebUI den Leuten aus der Patsche helfen. Muss ich mal schauen ob ich einen HmIP-eTRV-2 noch im Schrank irgendwo habe und das dann testen. Ist das bestätigt das das mit der originalen CCU3 3.65.x Firmware auch nicht geht?

**Comment by Baxxy13** [comment]
Ja, gibt mehrere Berichte darüber im Forum.
z.B.
[Link](https://homematic-forum.de/forum/viewtopic.php?f=26&t=75878&start=10#p737658)

**Comment by jens-maus** [comment]
> Ja, gibt mehrere Berichte darüber im Forum. 

Alles klar, danke. Vielleicht hilft ja bereits ein schneller Blick in den WebUI code um die defekte Bedingung zu finden die diese Elemente fälschlicherweise ausblendet und dann können wir vorab da nen WebUI patch für die Januarversion fertig bauen. Jemand Interesse? @jp112sdl ;-)

**Comment by jp112sdl** [comment]
> Vielleicht hilft ja bereits ein schneller Blick in den WebUI code um die defekte Bedingung zu finden die diese Elemente fälschlicherweise ausblendet und dann können wir vorab da nen WebUI patch für die Januarversion fertig bauen

Ich hatte damals schon geschaut und nix gefunden.
https://homematic-forum.de/forum/viewtopic.php?f=65&t=76178&p=739898#p739898

**Comment by Moo1988** [comment]
Ich kann es auch bestätigen das bei folgenden Thermostaten die Einstellung der Entkalkungsfahrt fehlt:
-etrv
-etrv-2
-etrv-B1
-etrv-E
Ver. 3.65.11.20221005

**Comment by jens-maus** [comment]
Ok, ich denke ich hab das Problem gefunden. Siehe hier:

https://github.com/eq-3/occu/commit/26f63a4820907230a589a1654387001c62a7aa51#diff-494548a354df8afe0acefd509845ec5642dbd5c8a32ddf91e6cea6390a35e42cL13

D.h. hier wurde wohl im 3.65.11 release fäschlicherweise in der Datei `/opt/HmIP/legacy-parameter-definition.config` in Zeile 13 der Eintrag `HmIP-eTRV-2=hmip-etrv` entfernet weil man gedacht hat der drüber mit dem uppercase `M` bei `HmIP` würde ausreichen. Ist aber wohl nicht so und so ist es ist, das wenn man diese Zeile wieder zurückbringt und zusätzlich zu dem Uppercase `HMIP-eTRV-2=hmip-etrv` auch noch die falsch entfernte `HmIP-eTRV-2=hmip-etrv` hinzufügt nach einem neustart von HMIPServer dann sofort die verschwundenen Bedienungselemente wieder auftauchen.

Ein entsprechender Bugfix patch werde ich entsprechend dann umsetzen und dann sollte das mit dem nächsten nightly snapshot auch Geschichte sein :) Wenn das aber jemand vorab gerne testen will, einfach diese Zeile wieder hinzufügen, HMIPServer neustarten und schon sollten die Parameter wieder einstellbar sein.

**Comment by jp112sdl** [comment]
Sollte für die Controls eigentlich egal sein, oder? Steht beides drin. Mit m und M
https://github.com/eq-3/occu/blob/master/WebUI/www/rega/esp/controls/heating_control.fn#L380-L381

**Comment by Stefan-Linux** [comment]
Hi,
auf der 3.65.11.* scheint das nicht zu reichen ... oder ich hab da was falsch gemacht. - Egal. Ich warte da mal auf die nächste offizielle Version und teste das nochmal. (Und spiel noch vorsichtig ein bisschen rum)

Aber noch ein anderer Gedanke: Wurde da die falsche Zeile gelöscht?
H**M**IP-**eTRV*** Geräte scheint es nicht zu geben. Dagegen HMIP-SWDO aber schon.

Danke und gutes Neues,
 Stefan

**Comment by Baxxy13** [comment]
War das wirklich so einfach?
Das ärgert mich ein bisschen denn ich hatte das mehrfach vor Augen und dabei nicht auf die Schreibweise geachtet. :worried:
![occu_3_65_11_diff](https://user-images.githubusercontent.com/54898249/210806271-b365062a-5b35-4752-b248-59af7a74c937.JPG)

**Comment by jp112sdl** [comment]
https://homematic-forum.de/forum/viewtopic.php?f=65&t=76178&p=739898#p739768
<img width="904" alt="Bildschirm­foto 2023-01-05 um 16 06 15" src="https://user-images.githubusercontent.com/18190139/210811861-792f5dc2-80d0-4179-9598-9e3924c291c7.png">

**Comment by jens-maus** [comment]
> War das wirklich so einfach? Das ärgert mich ein bisschen denn ich hatte das mehrfach vor Augen und dabei nicht auf die Schreibweise geachtet. 😟 

Probier es mit dem aktuellen nightly snapshot aus. Bei meinen Tests zeigte sich das sofort alle Optionen des eTRV-2 wieder da sind. Denke hier hat der eQ3-Autor genau draufgeschaut wie du und das nicht gesehen. Ohnehin sehr zweifelhaft warum hier überhaupt ein case-sensistive vergleich irgendwo intern stattfindet. Wenn ich da der Autor wäre würde ich das an der Stelle dann reparieren statt alle möglichen Groß/Kleinschreibungsvarianten abzudecken.

**Comment by jp112sdl** [comment]
Dann hat das auf meinen Hinweis hin im Oktober niemand wirklich getestet. :(

**Comment by jens-maus** [comment]
> Dann hat das auf meinen Hinweis hin im Oktober niemand wirklich getestet. :(

Dann ging das wohl unter, ja. Bzw. es war nicht klar genug und sowas sollte IMHO immer mit diffs hinterlegt werden oder noch besser hier diskussionstechnisch besser im GitHub stattfinden. Oder es müssen beide Einträge existieren damit das geht. Keine Ahnung. Ich weiss nur das ich das gestern mit einem HmIP-eTRV-2 ausgiebig getestet habe und nach hinzufügen der lowercase "m" Variante hat das sofort nach neustart des HmIPServer funktioniert. Wäre aber natürlich schön ein betroffener versucht das selbst nochmal zu reproduzieren.

**Comment by gradius-v** [comment]
Beim Home Assistant Add-On funktioniert das nicht. Die Einstellungen fehlen weiterhin. Aktueller Snapshot.

**Comment by jens-maus** [comment]
> Beim Home Assistant Add-On funktioniert das nicht. Die Einstellungen fehlen weiterhin. Aktueller Snapshot.

Der Fix ist ja auch erst im **nächsten** nightly snapshot mit dabei (d.h. erst mit dem der mit 20220106 enden wird...

**Comment by gradius-v** [comment]
> > Beim Home Assistant Add-On funktioniert das nicht. Die Einstellungen fehlen weiterhin. Aktueller Snapshot.
> 
> Der Fix ist ja auch erst im **nächsten** nightly snapshot mit dabei (d.h. erst mit dem der mit 20230106 enden wird)...

Ich meinte das manuelle hinzufügen von HmIP-eTRV-2=hmip-etrv in die legacy-parameter-definition.config.

**Comment by jens-maus** [comment]
> > > Beim Home Assistant Add-On funktioniert das nicht. Die Einstellungen fehlen weiterhin. Aktueller Snapshot.
> > 
> > 
> > Der Fix ist ja auch erst im **nächsten** nightly snapshot mit dabei (d.h. erst mit dem der mit 20230106 enden wird)...
> 
> Ich meinte das manuelle hinzufügen von HmIP-eTRV-2=hmip-etrv in die legacy-parameter-definition.config.

Warte halt bis morgen und probiere dann erneut. Und wenn es immer noch nicht geht, melde hier die genaue Typbezeichnung deines Gerätes...

**Comment by gradius-v** [comment]
Funktioniert wieder.👍
