### ISSUE TITLE
Gerätefilter usw. mit Regexpattern

### ISSUE THREAD

**Issue by IT-VBFK** [jens-maus/RaspberryMatic#2028]
### Describe the solution you'd like

Anstatt nur mit string matches zu filtern, wäre es hin und wieder ganz hilfreich, mittels Regex-Pattern zu filtern.

Hintergrund: Ich habe Aktoren und Thermostate die bis auf das Prefix gleich heißen. zB. Ak1_Raum1 und Th1_Raum1
Da die beiden mehr oder weniger zusammengehören, möchte ich nun zB hiermit filtern: `(Th|Ak)1.*`, mit genau diesen zwei Ergebnissen.

### Describe alternatives you've considered

Manuell filtern

### Is your feature request related to a problem?

Manuell filtern fühlt sich halt ein bisschen umständlich an :)

**Comment by jp112sdl** [comment]
**1.) Einstellungen->Geräte**
Dort geht es jetzt schon so, dass man Pattern, getrennt `|` angeben und suchen kann.

<img width="461" alt="Bildschirm­foto 2022-11-01 um 17 20 50" src="https://user-images.githubusercontent.com/18190139/199283948-f2324470-70b1-4b44-82fa-31178c51cff2.png">

Allerdings nicht "Regex-like", sondern es wird nur geschaut, ob die Suchzeichenfolge irgendwo im Text vorkommt.

Lässt sich jedoch relativ einfach in der `webui.js` anpassen (aktuellen Code habe ich // auskommentiert):

```
  /**                                                                                                                                                           
   * Pr?ft, ob der Filter auf einen Text zutrifft                                                                                                               
   **/                                                                                                                                                          
  this.match = function(text)                                                                                                                                   
  {                                                                                                                                                             
    if (false === isSet()) { return true; }                                                                                                                     
                                                                                                                                                                
    var patternList = m_value.toLowerCase().split("|");                                                                                                         
    //var patternList = m_value.split("|");                                                                                                                     
    text            = text.toLowerCase();                                                                                                                       
                                                                                                                                                                
    //for (var i = 0, len = patternList.length; i < len; i++)                                                                                                   
    //{                                                                                                                                                         
    //  if (0 <= text.indexOf(patternList[i])) { return true; }                                                                                                 
    //}                                                                                                                                                         
    var r = new RegExp(m_value.toLowerCase());                                                                                                                  
    if (r.test(text) === true) {return true; }                                                                                                                  
                                                                                                                                                                
    return false;                                                                                                                                               
  };   
```

**2.) Status und Bedienung, sowie Einstellungen->Systemvariablen**

Hier funktioniert 1. nicht.

Ich bin jetzt nicht so der Regex-Guru.
Aber wenn ich auch hier in der `webui.js` aus
```
    if (this.filName !== "")                 
    {                                                                                 
      if (typeof obj['name'] != 'undefined')                                          
      {                                                                               
        if (obj['name'] === "")                      { return false; }                    
        var transName = translateString(obj['name']);              
        //if (transName.toLowerCase().indexOf(this.filName) == -1) { return false; }
        var r = new RegExp(this.filName);                                           
        if (r.test(transName.toLowerCase()) === false) {return false; } 
      }                                             
    } 
```
die aktuell genutzte Such-Methode auskommentiere und gegen eine Regex-Funktion austausche, dann sieht es erstmal gut aus.

Und es funktioniert dann auch noch weiterhin wie gehabt: Teilstrings werden als Ergebnis ausgeworfen.

Wobei man auf die Groß-/Kleinschreibung weiterhin verzichten müsste, da sowohl Filtertext als auch Wert in `lowerCase` gewandelt werden. 

Das würde ich auch so beibehalten wollen.

<img width="508" alt="Bildschirm­foto 2022-11-01 um 17 01 47" src="https://user-images.githubusercontent.com/18190139/199279579-89f1fb5a-5534-41fd-993b-d2876a60b9c8.png">

**Comment by IT-VBFK** [comment]
Cool :)

Danke fürs checken

Wenn mir noch jemand erklärt, wie man das hier via PR einreicht, kann ich mir das mal anschauen ;)

Wenn diese Änderung überhaupt gewünscht ist..

**Comment by jp112sdl** [comment]
> Wenn mir noch jemand erklärt, wie man das hier via PR einreicht, kann ich mir das mal anschauen ;)

- Fork ziehen
- in [buildroot-external/patches/occu](https://github.com/jens-maus/RaspberryMatic/tree/master/buildroot-external/patches/occu) anschauen, wie andere Patche aussehen
- neues Patchverzeichnis erstellen und betroffene/benötigte Patchdateien darin ablegen
- `create_patches.sh` ausführen
- Änderungen in einem **neuen** eigenen Branch committen 
- PR erstellen

**Comment by jens-maus** [comment]
Bin mir nicht mal sicher ob es so eine gute Idee ist jetzt Otto-Normal-Verbraucher so etwas wie eine RegExp erklären zu müssen. Auch wird das sicherlich wieder irgendwelche Nebeneffekt haben wenn jemand jetzt nur ein `*` oder so anderes Sonderzeichen dort eingibt....

**Comment by jp112sdl** [comment]
@jens-maus Denk in Ruhe drüber nach. 
Ggf. könnte man auch eine extra `[ ] Regex-Suche`-Checkbox in das Filter-Popup einbauen.

@IT-VBFK : Du kannst es ja mal testen. Ich bin vorerst zufrieden damit. 
Falls das hier in RM nicht reinkommt, kannst du den Patch ja auch in einem Homematic-Forenbeitrag bereitstellen und dann kann sich das jeder, der meint damit umgehen zu können, selbst installieren.

[1006-WebUI-RegexFilter.txt](https://github.com/jens-maus/RaspberryMatic/files/9924064/1006-WebUI-RegexFilter.txt)

**Comment by IT-VBFK** [comment]
> @jens-maus Denk in Ruhe drüber nach. Ggf. könnte man auch eine extra `[ ] Regex-Suche`-Checkbox in das Filter-Popup einbauen.
> 
> @IT-VBFK : Du kannst es ja mal testen. Ich bin vorerst zufrieden damit. Falls das hier in RM nicht reinkommt, kannst du den Patch ja auch in einem Homematic-Forenbeitrag bereitstellen und dann kann sich das jeder, der meint damit umgehen zu können, selbst installieren.
> 
> [1006-WebUI-RegexFilter.txt](https://github.com/jens-maus/RaspberryMatic/files/9924064/1006-WebUI-RegexFilter.txt)

Kann man diesen Patch einfach so mit Boardmitteln anwenden?

**Comment by jp112sdl** [comment]
Ja natürlich.
`mount -o remount,rw / ; cd / ; patch -p 1 -i /pfad/zum/patchfile`

**Comment by IT-VBFK** [comment]
Herzlichen Dank für die Hilfe :)

**Comment by IT-VBFK** [comment]
> neues Patchverzeichnis erstellen und betroffene/benötigte Patchdateien darin ablegen

Noch eine Frage: da braucht man eine `webui.js.orig` woher bekomm ich die? aus dem OCCU-Package?

**Comment by jp112sdl** [comment]
Schau mal in die anderen Patchverzeichnisse. Dann nimmst die neueste die du da finden kannst

**Comment by jens-maus** [comment]
Optimalerweise nimmt man immer die `webui.js` direkt aus dem OCCU als basis bzw. orig patchdatei und fügt dort seine änderungen ein. Wenn man allerdings an der selben stelle wie ein anderer WebUI Patch agiert bzw. etwas ändert, dann muss man natürlich die `webui.js` dieses früheren Patches nutzen. Deshalb auch die aufsteigenden Patch IDs die auch nicht recyclt werden dürfen.
