### ISSUE TITLE
Restore of sbk-file asks for security key even though none was set

### ISSUE THREAD

**Issue by hicksel** [jens-maus/RaspberryMatic#203]
Hi,
First of all I want to thank everyone involved for this great software.
I moved from a CCU2@2.29.23 to Raspberrymatic on a PI1B@2.29.23.20171022 and now to a PI3@2.29.23.20171118. The switch from CCU2 to Raspberrymatic worked fine. But when importing my Backup from the PI1 to the PI3 I was asked for a security key even though I had never set one. Also just entering a new combination like 12345 failed with an error message telling me to look into the service reports for a detailed error information. Of course there were no error messages. After creating a diff between the config folders from the old to the new backup I noticed that only a few config files had changed since I renamed some components. But the files which could be related to the security key like ssh and shadow files were identical between both backups. The only other differences in the archive were the signature and the firmware version. Since the signature obviously had to be different I tried changing the firmware version to 2.29.23 and now I could restore the backup without a password prompt. So there seems to be the bug that the software expects a security key to be set when importing a backup from a previous Raspberrymatic version.

**Comment by jens-maus** [comment]
This is the first time I heard about such a problem. However, to further investigate the issue it would be good to see the previous content of the `firmware` file before you modified it.

**Comment by hicksel** [comment]
Sorry if my description of the solution was unclear. I did edit the version info in the sbk file and not in the firmware.

**Comment by jens-maus** [comment]
I understood that. But please present the version info file before and after you edited it as I am not able to reproduce the problem here.

**Comment by hicksel** [comment]
Even though I don´t think there is anything special about removing the raspberrymatic version substring from the firmware_version file but I have added a zip with both versions from the sbk archive.
[changes.zip](https://github.com/jens-maus/RaspberryMatic/files/1519415/changes.zip)

**Comment by jens-maus** [comment]
Sorry, but I just tried to reproduce the problem without success. Are you able to reproduce the problem yourself?

**Comment by hicksel** [comment]
Sorry after trying to reproduce the issue I noticed that the prompt for the security key was a quirk of Firefox in combination with small displays that led to focusing on the set a security key section if your backup filename was too long. But still when trying to enter the security Key "Aa1234" I just get the error in the screenshot.
![set_key_error](https://user-images.githubusercontent.com/10339125/33455091-4c13ab10-d61b-11e7-8e2b-1bc7f95b5603.PNG)

**Comment by jens-maus** [comment]
Sorry, but I think this is again a problem on your end. Are you sure you have a working BidCos-RF interface? Changing the security key only works if there is a working BidCos-RF Interface. That means, either you have to have an install HM-MOD-RPI-PCB installed or LAN Gateways installed. Just booting a plain RaspberryMatic without any RF interface won't work.

**Comment by hicksel** [comment]
Ok that was exactly my issue. To avoid that other ask the same questions I have added a Pull Request #204 to add this to the Limitations section in the readme. Of course having such a warning in the security key description in the OCCU Software itself would be even better. I will extend my port report once I have modified the translations files accordingly.
