### ISSUE TITLE
CCU3 mit HmIP-HAP: Geräte an HAP zeigen keinen Signalpegel an.

### ISSUE THREAD

**Issue by SThomae** [jens-maus/RaspberryMatic#2051]
### Describe the issue you are experiencing

Ich habe meine CCU3 mit einem HmIP-HAP erweitert.
Alle Geräte, welche die Verbindung zum HAP haben, zeigen in der Geräteübersicht 128 dBm an und nicht wie die Geräte an der CCU3 -xx dBm. 
![Signalpegel](https://user-images.githubusercontent.com/59518751/201903162-bbb83f72-4cad-4249-8e5a-87cb5251b6f5.png)

### Describe the behavior you expected

Die gleiche Anzeige wie bei der CCU3.
![Signalpegel-CCU](https://user-images.githubusercontent.com/59518751/201903731-e2f48025-8b82-4e75-882e-ef767bedf81f.png)

### Steps to reproduce the issue

1. CCU3 um HmIP-HAP erweitern.
2. Gerät über HmIP-HAP anbinden.
3. Signalpegel in der Geräteübersicht überprüfen.

### What is the version this bug report is based on?

3.65.11.20221005

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
unbekannt
```

### Additional information

HmIP-HAP Firmware: 2.4.28

**Comment by jens-maus** [comment]
Tut mir leid, aber dafür gibt es keine API. Es ist nicht möglich herauszubekommen mit welcher Sende-/Empfangsstärke ein Gerät über ein HAP verbunden ist. Das ist auch nichts was wir hier im Rahmen des RaspberryMatic Projektes erledigen/implementieren könnten, sondern das gehört an den Hersteller (eq3) herangetragen da nur er hierfür anpassungen in den closed source teilen machen kann die RaspberryMatic nutzt.
