### ISSUE TITLE
evaluating the valve positions of my HMIPW-FALMOT-C12

### ISSUE THREAD

**Issue by Gerd1967** [jens-maus/RaspberryMatic#2056]
### Describe the issue you are experiencing

I have a problem evaluating the valve positions of my HMIPW-FALMOT-C12. With this, the individual channels are not made available when importing the AIO Creator NEO application. An HMIP-FALMOT-C12 is also installed in my project, with which the channel transmission works perfectly (see attached file). The individual channels are visible in the device status of the RaspberyMatic.

### Describe the behavior you expected

Please the data of the HMIPW-FALMOT-C12. provide as with the HMIP-FALMOT-C12

### Steps to reproduce the issue

1.
2.
3.
...
![Geräte_Import_AIO](https://user-images.githubusercontent.com/118558402/202765601-a645dba0-f840-4bd8-a7b9-6439e3475b53.JPG)

### What is the version this bug report is based on?

3.63.9.20220625

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
no
```

**Comment by jens-maus** [comment]
This is a bug/issue tracker for the development of RaspberryMatic and not a support/help fora. So please use an appropriate discussion fora to seek for help using RaspberryMatic or a CCU/Homematic in general. This here is definitely the wrong place!
