### ISSUE TITLE
RaspberryMatic EMail Add-on

### ISSUE THREAD

**Issue by mash727** [jens-maus/RaspberryMatic#2059]
### Describe the issue you are experiencing

Guten Tag,

Ich habe etwas langer ein Problem mit meinen E-Mail-Add-on. Wenn, ich versuche eine vorhandene E-Mail Text zu anderen oder eine neue zu erstellen würde die nicht gespeichert. Bin Anfang des Jahres von CCU Charley auf Raspberrymatic umgestellt. Raspberrymatic lauft unter Docker. Alle vorhandene E-Mail Scripts funktionieren. Es wäre auch möglich im Anfang E-Mail Textinhalte zu änden. 
Zeit c.a. 3 Monaten bei einem Versuch um eine E-Mail Text zu ändern, meldet Homeassistant:

 “Fehler beim Speichern der E-Mail (ERROR Unknown Command ).

Ich habe alles versucht um das Problem zu finden und komme nicht weiter. Gibst da etwas Rat, was ich noch machen konnte?

System:

Raspberry Pi 4 B
RaspberryMatic SW 3.65.11.20221005(OCI)
Cux-Daemon 2.10.1
E Mail 1.7.4 
HA Core 2022.11.1
Supervisor 2022.10.2
Operating System 9.0

Die Logs geben keine Information.

### Describe the behavior you expected

Eine neue E-Mail zu generieren und speichern

### Steps to reproduce the issue

1.
2.
3.
...
Beim einfache Versuchen eine vorhandene E-Mail zu ändern oder eine neue zu erstellen

### What is the version this bug report is based on?

3.65.11.20221005(OCI)

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Logs geben keine info
```

**Comment by Baxxy13** [comment]
Solche Problem treten häufiger auf wenn man die WebUI und die AddOns über Ingress (also direkt über die Homeassistant Oberfläche) aufruft.

Ich würde mir das abgewöhnen und die WebUI "direkt" aufrufen.

Also in der AddOn - Konfiguration einen Port Vergeben und dann damit die WebUI aufrufen.
Beispiel:
![HA_RM_AddOn_externer_Zugriff](https://user-images.githubusercontent.com/54898249/203335712-0867baf7-a0de-4846-be8e-dde3c3712522.JPG)

Zugriff dann mit `http://<ip.des.home.assistant:8088`

Dann klappts auch mit dem Emil-AddOn

**Comment by jens-maus** [comment]
> Solche Problem treten häufiger auf wenn man die WebUI und die AddOns über Ingress (also direkt über die Homeassistant Oberfläche) aufruft.

Ist das wirklich so und reproduzierbar? Denn eigentlich sollte alles über die Ingress-Weiterleitung genauso gut funktionieren wie direkt via Port 80 / 8088. Wenn nicht müsste ich mir die aufrufende URL mal anschauen un könnte im `ha-proxy` (https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/overlay/base-raspmatic_oci/bin/ha-proxy.js) der für die translation der URLs zuständig ist ggf. optimierungen vornehmen.

**Comment by Baxxy13** [comment]
> Ist das wirklich so und reproduzierbar?

Ja, ist es. 
Bin zwar auf aktuellem Nightly, sollte aber keine Rolle spielen.
Über Ingress bekomme ich den gleichen Fehler wie von @mash727 beschrieben.
Zugriff über "extern" und alles läuft. 

Hier mal die Ingress url:
`http://192.168.1.211:8123/api/hassio_ingress/jLHjTGDNvRmxuNA8YaOFsvRAnVK5JcISILUeLSfKo4M/addons/email/?sid=@ZwejvZ8Icu@`

**Comment by mash727** [comment]
Besten Dank für die schnelle Antwort, so habe ich es jetzt gemacht.
Andy

Baxxy13 ***@***.***> schrieb am Di., 22. Nov. 2022, 15:14:

**Comment by mash727** [comment]
Nochmals Danke läuft jetzt Perfekt.

Am Di., 22. Nov. 2022 um 16:27 Uhr schrieb Baxxy13 ***@***.***

**Comment by jens-maus** [comment]
Nach etwas Analyse scheint dies kein problem von RaspberryMatic, sondern vom Email Addon selbst zu sein (siehe https://github.com/homematic-community/hm_email). Das sollte dann aber mit der nächsten Version dieses Addons (1.7.6) behoben sein.
