### ISSUE TITLE
Kein Wlan Support beim Raspberry 3

### ISSUE THREAD

**Issue by akriol** [jens-maus/RaspberryMatic#206]
Hallo,

ich habe das Update neu aufgespielt und wollte wie gewohnt den Raspi 3 im Wlan in Betrieb nehmen. Er baut allerdings keine Verbindung auf und ich kann auch nicht über den Befehl iw wlan0 scan via putty auf meine Netzwerke zugreifen. Es erfolgt immer wieder der Fehler command failed: Invalid argument (-22)

**Comment by jens-maus** [comment]
Duplicate of #197 (also see https://homematic-forum.de/forum/viewtopic.php?f=65&t=40649)
