### ISSUE TITLE
Homematic classic-Geräte nach ca. 3 Wochen nicht erreichbar

### ISSUE THREAD

**Issue by hce** [jens-maus/RaspberryMatic#2060]
### Describe the issue you are experiencing

After an uneventful uptime of 3 weeks the Homematic Classic devices were unreachable, could not be controlled from the CCU anymore, *and* the duty cycle of the CCU was not displayed in the UI anymore. Only the duty cycle of the HmIP-HAP I am also running. However, as far as I see that duty cycle does not increase significantly. I am not sure if the CCU modem failed or if it is a software bug. After restrating the CCU, everything worked again. Approx. 3 weeks later, it happened again. Again I restarted the CCU.

### Describe the behavior you expected

The CCU should not fail, the Homematic devices should stay reachable and the duty cycle should not disappear from the CCU UI after 3 weeks runtime.

### Steps to reproduce the issue

Unfortunately, unknown. It did run for over a year without problems. I started to add more Homematic classic devices the last few months, but I really cannot say how to reproduce the issue.

### What is the version this bug report is based on?

3.65.11.20221005

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
I am using an original CCU as sold by elv/eQ3 with the latest stable raspberrymatic on it. :-)
```

**Comment by jens-maus** [comment]
Sorry, but this is no support or discussion fora here. This is a bug and issue tracker. So please open a new discussion thread in the [discussion fora](https://github.com/jens-maus/RaspberryMatic/discussions) of this GitHub project or use the external german speaking RaspberryMatic Discussion fora (https://homematic-forum.de/) for discussing your matter. This was also already mentioned in the ticket template!
___
Tut mir leid, aber das hier ist kein Supportforum, sondern ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen sind. Daher bitte entweder hier im [Diskussusionsteil](https://github.com/jens-maus/RaspberryMatic/discussions) des GitHub Projektes einen neuen Beitrag eröffnen oder das externe RaspberryMatic Forum (https://homematic-forum.de/) dafür nutzen.  Dies stand übrigens auch so im Ticket Template!

**Comment by hce** [comment]
How is this not a bug? I am surprised by the harsh tone in this project.

**Comment by jens-maus** [comment]
This is not a harsh tone, this is clear procedure of not getting overwhelmed by tons of open issue reports which in the end in 80% of the cases often are local user problems. So sorry, if this sounds harsh, but the clear procedure for such things is (and is also clearly documented in the issue template): Find help in a user community forum like homematic-forum.de or the github discussion part here and if you find other users who can reproduce your problem or you have detailed technical information/details pointing at a specific bug come back here and reopen the issue or create a new one.

**Comment by hce** [comment]
Okay, well, I was trying to describe the issue as best as I can and was hoping to get some hints what exactly you want me to do to try to narrow down and identify the issue. Experiencing communication loss with your devices is most certainly a bug. But don't worry, I will not make any more reports.
