### ISSUE TITLE
Not able to uninstall HM IP devices

### ISSUE THREAD

**Issue by sailor79** [jens-maus/RaspberryMatic#207]
Hello,
while moving all devices to new hardware from both Rasperrymatic 2.29.23.20171118 on rpi3 i cannot uninstall all existing types of IP-devices (in my case: HMIP-SWDO-I, HMIP-PS, HMIP-PSM, HMIP-STHD, HMIP-BSM, HMIP-SMI,HMIP-eTRV) while attached image is shown in infinite loop. Restarting RPI etc. does'nt help. 
<img width="329" alt="bildschirmfoto 2017-12-06 um 10 57 30" src="https://user-images.githubusercontent.com/1407792/33656173-87220806-da75-11e7-8e65-0ce114b7f8d1.png">

Concurrent no IP-device is configurable:
<img width="736" alt="bildschirmfoto 2017-12-06 um 11 07 47" src="https://user-images.githubusercontent.com/1407792/33656275-de4e9b80-da75-11e7-998f-c4760ada8a68.png">

But each device is operable as is.

**Comment by jens-maus** [comment]
Bitte im Forum erst nachfragen und wenn das ein bestätigtes Problem ist dann bitte hier als Bug melden.

**Comment by sailor79** [comment]
Ich kein Mitglied "des" Forums. 
Schade, das Bugs nur über eine Zwangsmitgliedschaft in einem Forum Dritter beachtet werden.

**Comment by jens-maus** [comment]
Das hier ist ein Bugtracker und kein Supportforum. Hier sollten nur verifizierte Bugs oder Feature Requests gepostet werden. Ich kann einfach aus Zeitgründen hier kein Support leisten - das muss die Community (d.h. das Forum) erledigen.

**Comment by sailor79** [comment]
Ich habe **keinen** Support angefordert, 
sondern einen Fehler neutral/sachlich gemeldet (=Bug Tracker).

Mir war neu, das auf Github die Möglichkeit zur Verifizierung nicht besteht. Schade

**Comment by sailor79** [comment]
Bin ich, danke :-)
Im Logfile taucht einzig Folgendes auf:
`Dec  6 12:26:50 homematic-raspi local0.err ReGaHss: Error: IseESP::ScriptRuntimeError:  {   Write( '<script type="text/javascript">' );    string sTime = system.Date( "%H:%M" );   string sDate = system.Date( "%d.%m.%Y" );   WriteLine('setTime("' # sTime # '");');   WriteLine('setDate("' # sDate # '");'); !  Write( 'if( $("maintime") ) $("maintime").innerHTML = "'#sTime#'";' ); !  Write( 'if( $("maindate") ) $("maindate").innerHTML = "'#sDate#'";' );      object oPresence = dom.GetObject( ID_PRESENT );   if( oPresence )   {     Write( 'if( $("presence") ) $("presence").innerHTML = "'#oPresence.ValueName()#'";' );   }      integer iAlCount = 0;   object svCollection = dom.GetObject( ID_SYSTEM_VARIABLES );   string sSVID;   WriteLine( 'if( typeof(alarmLogSystem) == "object" ) alarmLogSystem.deleteAll();' );      foreach( sSVID, svCollection.EnumIDs() )   {     object oSV = dom.GetObject( sSVID );          if( oSV )     {       if( oSV.IsTypeOf( OT_ALARMDP ) )       {         !if( oSV.AlState() == asOncoming )         if( (oSV.AlStat`

**Comment by sailor79** [comment]
<img width="449" alt="bildschirmfoto 2017-12-06 um 12 30 59" src="https://user-images.githubusercontent.com/1407792/33659672-5b050668-da81-11e7-987a-bb99233268ab.png">

**Comment by jens-maus** [comment]
@sailor79 Warum zeigst du hier die Ausgabe deiner Uhrzeit? Und bzgl. des ScriptRuntimeError. Kommt die Meldung immer wenn du versuchst ein HmIP abzulernen? D.h. ist es reproduzierbar das genau diese Aktion den ScriptRuntimeError erzeugt?

**Comment by sailor79** [comment]
Die (einzig vorhandene) Fehlermeldung kommt alle 1-3 min. Ob Sie durch den Versuch des Ablernens getriggert wurde, kann ich leider nicht nachvollziehen. An einer fehlenden RTC liegt es nicht, Ausgabe hwclock gelöscht.

**Comment by litti** [comment]
Das ist mysteriös. Das Skript kommt aus der system.fn, Funktion UpdateUI, es ist eine der zentralen Funktionen der WebUI. Hast Du nur Hm-IP-Geräte oder auch andere HM-Geräte? Um herauszufinden, was genau an dem Skript nicht geht könntest Du es teilweise ausführen.

Poste bitte einmal die Ausgabe von ```ps -ef``` auf der Konsole, evtl. läuft ein Dienst nicht.

```
Write( '<script type="text/javascript">' );

  string sTime = system.Date( "%H:%M" );
  string sDate = system.Date( "%d.%m.%Y" );
  WriteLine('setTime("' # sTime # '");');
  WriteLine('setDate("' # sDate # '");');
!  Write( 'if( $("maintime") ) $("maintime").innerHTML = "'#sTime#'";' );
!  Write( 'if( $("maindate") ) $("maindate").innerHTML = "'#sDate#'";' );
  
  object oPresence = dom.GetObject( ID_PRESENT );
  if( oPresence )
  {
    Write( 'if( $("presence") ) $("presence").innerHTML = "'#oPresence.ValueName()#'";' );
  }
  
  integer iAlCount = 0;
  object svCollection = dom.GetObject( ID_SYSTEM_VARIABLES );
  string sSVID;
  WriteLine( 'if( typeof(alarmLogSystem) == "object" ) alarmLogSystem.deleteAll();' );
  
  foreach( sSVID, svCollection.EnumIDs() )
  {
    object oSV = dom.GetObject( sSVID );
    
    if( oSV )
    {
      if( oSV.IsTypeOf( OT_ALARMDP ) )
      {
        !if( oSV.AlState() == asOncoming )
        if( (oSV.AlState() == asOncoming) && (oSV.State() == true) )
        {
          iAlCount = iAlCount + 1;
          string sTimestamp = oSV.AlOccurrenceTime();
          Call( "/esp/TimeStamp.fn::TimeStampToString2()" );
          string sDateTimeTmp = sTimestamp;
          !string sMessageTmp = oSV.Name()#" ausgelöst";
          string sMessageTmp = oSV.Name()#" ${lblTriggered}";
          WriteLine( 'if( typeof(alarmLogSystem) == "object" ) alarmLogSystem.add("'#sDateTimeTmp#'","","'#sMessageTmp#'");' );
        }
      }
    }
  }
  WriteLine("setAlarmMessageCount(" # iAlCount # ");");

  WriteLine( 'if( typeof(serviceLogSystem) == "object" ) serviceLogSystem.deleteAll();' );
  integer iSvcCount = 0;
  integer stickyCounter = 0;
  object servicesCollection = dom.GetObject( ID_SERVICES );
  string sAID;
  foreach( sAID, servicesCollection.EnumIDs() )
  {
    object oAlarm = dom.GetObject( sAID );
    if( oAlarm )
    {
      if( oAlarm.IsTypeOf(OT_ALARMDP) )
      {
        if( oAlarm.AlState() == asOncoming )
        {
          iSvcCount = iSvcCount + 1;
          string sTimestamp = oAlarm.AlOccurrenceTime();
          Call( "/esp/TimeStamp.fn::TimeStampToString2()" );
          string sDateTime = sTimestamp;
          string sChannelName = "(ohne Kanal)";
          string sServiceMessage = "";
          object oLastTrigger = dom.GetObject( oAlarm.LastTriggerID() );
          if( oLastTrigger )
          {
            if (oLastTrigger.HSSID() == "STICKY_UNREACH")
            {
              stickyCounter = stickyCounter + 1;
              Write(' if (WebUI.HIDESTICKYUNREACH) {ReceiptAlarm('#oAlarm.ID()#');} ');
            }
            string sTimestamp = oAlarm.LastTriggerTime();
            Call( "/esp/TimeStamp.fn::TimeStampToString()" );
            string sLastUse = sTimestamp;
            
            sTimestamp = oAlarm.Timestamp();
            Call( "/esp/TimeStamp.fn::TimeStampToString()" );
            string sLastTimestamp = sTimestamp;
          
            object oLastTriggerChannel = dom.GetObject( oLastTrigger.Channel() );
            if( oLastTriggerChannel )
            {
              sChannelName = oLastTriggerChannel.Name();
              
              if( oLastTrigger.IsTypeOf( OT_HSSDP ) )
              {
                string sLongKey = oLastTriggerChannel.ChnLabel()#"|"#oLastTrigger.HSSID();
                string sShortKey = oLastTrigger.HSSID();
                if( (oLastTrigger.ValueType() == ivtInteger) && (oLastTrigger.ValueSubType() == istEnum) )
                {
                  sLongKey = sLongKey#"="#web.webGetValueFromList( oLastTrigger.ValueList(), oAlarm.Value() );
                  sShortKey = sShortKey#"="#web.webGetValueFromList( oLastTrigger.ValueList(), oAlarm.Value() );
                }
                if( (oLastTrigger.ValueType() == ivtBinary ) && (oLastTrigger.ValueSubType() == istGeneric) )
                {
                  sLongKey = sLongKey#"=TRUE";
                  sShortKey = sShortKey#"=FALSE";
                }
                sServiceMessage = web.webKeyFromStringTable( sLongKey );
                if( !sServiceMessage.Length() )
                {
                  sServiceMessage = web.webKeyFromStringTable( sShortKey );
                  if( !sServiceMessage.Length() )
                  {
                    sServiceMessage = "${unknownMessage} ("#sLongKey#")";
                  }
                }
                !sServiceMessage = sServiceMessage#" "#oLastTrigger.ValueType()#" "#oLastTrigger.ValueSubType();
                !sServiceMessage = sServiceMessage#" "#ivtBinary#" "#istGeneric;
              }
            }
            Write("if ($('sgu"#sAID#"'))");
              Write("$('sgu"#sAID#"').innerHTML = '"#sLastUse#"';");
            Write("if ($('sla"#sAID#"'))");
              Write("$('sla"#sAID#"').innerHTML = '"#sLastTimestamp#"';");
          }
          Write( 'if( typeof(serviceLogSystem) == "object" ) serviceLogSystem.add("'#sDateTime#'","'#sChannelName#'","'#sServiceMessage#'");' );
        }
      }
    }
  }

  Write( "if (WebUI.HIDESTICKYUNREACH) {" );

  Write( "var svcCount = "#iSvcCount#";" );
  Write( "var stickyCount = "#stickyCounter#";" );
  Write( "var visibleSvcCount = svcCount - stickyCount;" );

  ! This should never happen
  Write( "if(visibleSvcCount < 0) {visibleSvcCount = 0;}" );

    Write( "if( typeof(updateMessageView) == 'function' )" );
      Write( "updateMessageView(visibleSvcCount);" );
    WriteLine( "setServiceMessageCount(visibleSvcCount);" );
  Write( "} else {" );
    Write( "if( typeof(updateMessageView) == 'function' )" );
      Write( "updateMessageView("#iSvcCount#");" );
    WriteLine( "setServiceMessageCount(" # iSvcCount # ");" );
  Write(" } ");



  Write( 'if(urlParamInterfaces == "true") showRFInterfaces();');

  !###################
  !# Systemvariablen #
  !###################
  
  var oUser = dom.GetObject(system.GetSessionVar("sessionUserID"));
  WriteLine("// oUser: " # oUser);
  if (oUser)
  {
    string svId;
    foreach(svId, oUser.UserSharedObjects().EnumIDs())
    {
      var oSV     = dom.GetObject(svId);
      var svValue = "";
      
      ! Systemvariable vom Typ Alarm oder Logikwert
      if ( (oSV.ValueSubType() == istAlarm) || (oSV.ValueSubType() == istBool) ) {
        svValue = oSV.ValueName();
      }
      
      ! Systemvariable vom Typ Zahl
      if (oSV.ValueSubType() == istGeneric) {
        svValue = oSV.Value();
        if (svValue == "") { svValue = "0"; }
      }
      ! Systemvariable vom Typ Enum
      if (oSV.ValueSubType() == istEnum) {
        svValue = web.webGetValueFromList(oSV.ValueList(),oSV.Value());
      }
      ! Systemvariable vom Typ Zeichenkette
      if (oSV.ValueSubType() == istChar8859) {
        svValue = oSV.Value();
      }
      
      WriteLine("updateSysVar('" # svId # "', '" # svValue # "');");
    }    
  }

  string s;
  foreach(s,dom.TestReadyIDs().EnumIDs())
  {
    object oTestObject = dom.GetObject( s );
    if( oTestObject )
    {
      if( oTestObject.IsTypeOf( OT_CHANNEL ) )
      {
        object oTestChannel = oTestObject;
        Write("if($('TestButtonCH"#s#"'))$('TestButtonCH"#s#"').className = 'TestButton';" );
        Write("if($('OkButtonCH"#s#"'))$('OkButtonCH"#s#"').className = 'OkButton';" );
        string sTimestamp = oTestChannel.TestCompletedTime();
        Call("/esp/TimeStamp.fn::TimeStampToString3()");
        Write("if($('TestDateCH"#s#"'))$('TestDateCH"#s#"').innerHTML = '"#sTimestamp#"';" );
        object oTestDevice = dom.GetObject( oTestChannel.Device() );
        if( oTestDevice )
        {
          string sID = oTestDevice.ID();
          Write("if($('TestButtonCH"#sID#"'))$('TestButtonCH"#sID#"').className = 'TestButton';" );
          Write("if($('OkButtonCH"#sID#"'))$('OkButtonCH"#sID#"').className = 'OkButton';" );
          string sTimestamp = oTestDevice.LastTestCompletedTime();
          Call("/esp/TimeStamp.fn::TimeStampToString3()");
          Write("if($('TestDateCH"#sID#"'))$('TestDateCH"#sID#"').innerHTML = '"#sTimestamp#"';" );      
        }
        object oPartnerTestChannel = dom.GetObject( oTestChannel.ChnGroupPartnerId() );
        if( oPartnerTestChannel )
        {
          if( !dom.TestRunningIDs().Get( oPartnerTestChannel.ID() ) )
          {
            if( oTestChannel.TestCompletedTime() > oPartnerTestChannel.TestCompletedTime() )
            {
              string sTimestamp = oTestChannel.TestCompletedTime();
            }
            else
            {
              string sTimestamp = oPartnerTestChannel.TestCompletedTime();
            }
            Call("/esp/TimeStamp.fn::TimeStampToString3()");
            
            string sID = oTestChannel.ID()#"T"#oPartnerTestChannel.ID();
            Write("if($('TestButtonCH"#sID#"'))$('TestButtonCH"#sID#"').className = 'TestButton';" );
            Write("if($('OkButtonCH"#sID#"'))$('OkButtonCH"#sID#"').className = 'OkButton';" );
            Write("if($('TestDateCH"#sID#"'))$('TestDateCH"#sID#"').innerHTML = '"#sTimestamp#"';" );      
          
            string sID = oPartnerTestChannel.ID()#"T"#oTestChannel.ID();
            Write("if($('TestButtonCH"#sID#"'))$('TestButtonCH"#sID#"').className = 'TestButton';" );
            Write("if($('OkButtonCH"#sID#"'))$('OkButtonCH"#sID#"').className = 'OkButton';" );
            Write("if($('TestDateCH"#sID#"'))$('TestDateCH"#sID#"').innerHTML = '"#sTimestamp#"';" );
          }
        }
      }
    }
    if( oTestObject.IsTypeOf( OT_DEVICE ) )
    {
      object oTestDevice = oTestObject;
      string sID = oTestDevice.ID();
      Write("if($('TestButtonCH"#sID#"'))$('TestButtonCH"#sID#"').className = 'TestButton';" );
      Write("if($('OkButtonCH"#sID#"'))$('OkButtonCH"#sID#"').className = 'OkButton';" );
      string sTimestamp = oTestDevice.LastTestCompletedTime();
      Call("/esp/TimeStamp.fn::TimeStampToString3()");
      Write("if($('TestDateCH"#sID#"'))$('TestDateCH"#sID#"').innerHTML = '"#sTimestamp#"';" );
    }
  }
  
  string s;
  foreach( s, dom.TestRunningIDs().EnumIDs() )
  {
    object oTestChannel = dom.GetObject( s );
    if( oTestChannel )
    {
      Write("if($('TestButtonCH"#s#"'))$('TestButtonCH"#s#"').className = 'TestButtonDisabled';" );
      Write("if($('OkButtonCH"#s#"'))$('OkButtonCH"#s#"').className = 'OkButtonRunning';" );
      Write("if($('TestDateCH"#s#"'))$('TestDateCH"#s#"').innerHTML = '--:--:--';" );
      object oTestDevice = dom.GetObject( oTestChannel.Device() );
      if( oTestDevice )
      {
        string sID = oTestDevice.ID();
        Write("if($('TestButtonCH"#sID#"'))$('TestButtonCH"#sID#"').className = 'TestButtonDisabled';" );
        Write("if($('OkButtonCH"#sID#"'))$('OkButtonCH"#sID#"').className = 'OkButtonRunning';" );
        Write("if($('TestDateCH"#sID#"'))$('TestDateCH"#sID#"').innerHTML = '--:--:--';" );   
      }
      object oPartnerTestChannel = dom.GetObject( oTestChannel.ChnGroupPartnerId() );
      if( oPartnerTestChannel )
      {
        string sID = oTestChannel.ID()#"T"#oPartnerTestChannel.ID();
        Write("if($('TestButtonCH"#sID#"'))$('TestButtonCH"#sID#"').className = 'TestButtonDisabled';" );
        Write("if($('OkButtonCH"#sID#"'))$('OkButtonCH"#sID#"').className = 'OkButtonRunning';" );
        Write("if($('TestDateCH"#sID#"'))$('TestDateCH"#sID#"').innerHTML = '--:--:--';" );           
        string sID = oPartnerTestChannel.ID()#"T"#oTestChannel.ID();
        Write("if($('TestButtonCH"#sID#"'))$('TestButtonCH"#sID#"').className = 'TestButtonDisabled';" );
        Write("if($('OkButtonCH"#sID#"'))$('OkButtonCH"#sID#"').className = 'OkButtonRunning';" );
        Write("if($('TestDateCH"#sID#"'))$('TestDateCH"#sID#"').innerHTML = '--:--:--';" );           
      }
    }
  }
  
  if( system.IsVar("channels") && system.IsVar("timestamps") )
  {
    string sTM = "";
    integer i1 = 0;
    string s1;
    foreach( s1, system.GetVar("channels") )
    {
      i1 = i1 + 1;
      integer i2 = 0;
      string s2;
      foreach( s2, system.GetVar("timestamps") )
      {
        i2 = i2 + 1;
        if( i2 == i1 )
        {
          sTM = s2;
        } 
      }
      integer cId = s1;
      object oTmp = dom.GetObject( cId );
      if( oTmp )
      {
        string sLastTime = "";
        Call("/esp/system.fn::getLastTime()");
        if ( oTmp.IsTypeOf(OT_PROGRAM) ) {
          if ( ( sTM != sLastTime # oTmp.Active() ) ) {
            Write( 'recreateControl('#cId#',"'#sLastTime#'");' );
          }
        } else {
          if ( (sLastTime != "") && ( sTM != sLastTime ) ) {
            Write( 'recreateControl('#cId#',"'#sLastTime#'");' );
          }
        }
        Call("/esp/system.fn::writeWarnStateJS()");
      }
    }
  }
  Write( 'SwitchOffFlashLight();' );
  Write( '</script>' );
```

**Comment by sailor79** [comment]
Hallo,

ja da kommen noch ca. 50 normale HM-Geräte hinzu, wobei ich die meisten schon abgelernt und auf die neue Zentrale übertragen konnte.

Ausgabe ps:

> # ps -ef
PID   USER     TIME   COMMAND
    1 root       0:00 init
    2 root       0:00 [kthreadd]
    3 root       0:00 [ksoftirqd/0]
    5 root       0:00 [kworker/0:0H]
    7 root       0:00 [rcu_preempt]
    8 root       0:00 [rcu_sched]
    9 root       0:00 [rcu_bh]
   10 root       0:00 [migration/0]
   11 root       0:00 [lru-add-drain]
   12 root       0:00 [cpuhp/0]
   13 root       0:00 [cpuhp/1]
   14 root       0:00 [migration/1]
   15 root       0:00 [ksoftirqd/1]
   17 root       0:00 [kworker/1:0H]
   18 root       0:00 [cpuhp/2]
   19 root       0:00 [migration/2]
   20 root       0:00 [ksoftirqd/2]
   22 root       0:00 [kworker/2:0H]
   23 root       0:00 [cpuhp/3]
   24 root       0:00 [migration/3]
   25 root       0:00 [ksoftirqd/3]
   26 root       0:00 [kworker/3:0]
   27 root       0:00 [kworker/3:0H]
   28 root       0:00 [kdevtmpfs]
   29 root       0:00 [netns]
   30 root       0:00 [khungtaskd]
   31 root       0:00 [oom_reaper]
   32 root       0:00 [writeback]
   33 root       0:00 [kcompactd0]
   34 root       0:00 [crypto]
   35 root       0:00 [bioset]
   36 root       0:00 [kblockd]
   37 root       0:00 [watchdogd]
   39 root       0:00 [rpciod]
   40 root       0:00 [xprtiod]
   41 root       0:00 [kswapd0]
   42 root       0:00 [vmstat]
   43 root       0:00 [nfsiod]
   53 root       0:00 [kthrotld]
   54 root       0:00 [bioset]
   55 root       0:00 [bioset]
   56 root       0:00 [bioset]
   57 root       0:00 [bioset]
   58 root       0:00 [bioset]
   59 root       0:00 [bioset]
   60 root       0:00 [bioset]
   61 root       0:00 [bioset]
   62 root       0:00 [bioset]
   63 root       0:00 [bioset]
   64 root       0:00 [bioset]
   65 root       0:00 [bioset]
   66 root       0:00 [bioset]
   67 root       0:00 [bioset]
   68 root       0:00 [bioset]
   69 root       0:00 [bioset]
   70 root       0:00 [bioset]
   71 root       0:00 [bioset]
   72 root       0:00 [bioset]
   73 root       0:00 [bioset]
   74 root       0:00 [bioset]
   75 root       0:00 [bioset]
   76 root       0:00 [bioset]
   77 root       0:00 [bioset]
   78 root       0:00 [iscsi_eh]
   79 root       0:00 [dwc_otg]
   80 root       0:00 [DWC Notificatio]
   81 root       0:00 [VCHIQ-0]
   82 root       0:00 [VCHIQr-0]
   83 root       0:00 [VCHIQs-0]
   84 root       0:00 [VCHIQka-0]
   85 root       0:00 [SMIO]
   87 root       0:00 [irq/92-mmc1]
   89 root       0:00 [bioset]
   90 root       0:00 [mmcqd/0]
   91 root       0:00 [kworker/1:1]
   92 root       0:00 [kworker/2:1]
   93 root       0:00 [jbd2/mmcblk0p2-]
   94 root       0:00 [ext4-rsv-conver]
   99 root       0:00 [jbd2/mmcblk0p3-]
  100 root       0:00 [ext4-rsv-conver]
  101 root       0:00 [kworker/3:1]
  104 root       0:00 /usr/bin/psplash -n
  209 root       0:00 /usr/sbin/crond -f
  216 root       0:00 /sbin/syslogd -n -m 0
  219 root       0:00 /sbin/klogd -n
  225 root       0:00 /sbin/udevd -d
  245 root       0:00 [spi0]
  246 root       0:00 [cfg80211]
  247 root       0:00 [kworker/2:2]
  248 root       0:00 [brcmf_wq/mmc1:0]
  249 root       0:00 [brcmf_wdog/mmc1]
  263 root       0:00 /usr/sbin/irqbalance
  270 root       0:00 watchdog -t 5 /dev/watchdog
  277 root       0:00 /usr/sbin/rngd
  287 dbus       0:00 dbus-daemon --system
  295 root       0:00 [kworker/u9:0]
  296 root       0:00 [hci0]
  297 root       0:00 [hci0]
  298 root       0:00 /usr/bin/hciattach /dev/ttyS1 bcm43xx 921600 noflow -
  300 root       0:00 [kworker/u9:2]
  305 root       0:00 /usr/libexec/bluetooth/bluetoothd --compat
  332 root       0:00 [kworker/u8:2]
  357 root       0:00 [ipv6_addrconf]
  396 root       0:00 /usr/sbin/ifplugd -i eth0 -fI -u0 -d10
  412 root       0:00 /usr/sbin/ntpd -g 10.1.13.10
  437 root       0:00 /bin/eq3configd
  440 root       0:00 /bin/ssdpd
  447 root       0:00 /usr/sbin/lighttpd-angel -f /etc/lighttpd/lighttpd.conf -D
  449 root       0:00 /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf -D
  456 root       0:00 /usr/sbin/sshd
  461 root       0:00 /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf -D
  462 root       0:01 /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf -D
  463 root       0:00 /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf -D
  465 root       0:00 /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf -D
  507 root       0:00 /usr/local/addons/cuxd/cuxd
  525 root       0:00 {dutycycle.tcl} /bin/tclsh /usr/local/addons/cuxd/extra/dutycycle.
  564 root       0:01 /usr/sbin/snmpd -Lsd -Lf /dev/null -c /etc/config/snmp/snmpd.conf 
  582 root       0:00 /bin/multimacd -f /var/etc/multimacd.conf -l 4
  611 root       0:02 /bin/rfd -f /etc/config/rfd.conf -l 4
  630 root       0:15 java -Xmx128m -Dos.arch=arm -Dlog4j.configuration=file:///etc/conf
  637 root       0:00 [kworker/0:1H]
  663 root       0:00 [kworker/1:1H]
  962 root       0:00 sshd: root@pts/0
  964 root       0:00 -sh
  995 root       0:13 /bin/ReGaHss -f /etc/rega.conf -l 2
 1042 root       0:00 init
 1064 root       0:00 [kworker/u8:0]
 1065 root       0:00 [kworker/1:2]
 1377 root       0:00 [kworker/0:1]
 1495 root       0:00 [kworker/0:0]
 1629 root       0:00 [kworker/0:2]
 1646 root       0:00 [sh]
 1647 root       0:00 [sh]
 1651 root       0:00 ps -ef

**Comment by sailor79** [comment]
Das obige Script gibt das aus:
JSON:
`{
  "oTmp": "null",
  "oTestChannel": "null",
  "oLastTriggerChannel": "null",
  "servicesCollection": "Root Service Messages",
  "oSV": "Zone I6sMarc",
  "sAID": "29232",
  "sMessageTmp": "",
  "sessionId": "",
  "sDate": "06.12.2017",
  "sDateTimeTmp": "",
  "i1": "0",
  "i2": "0",
  "s": "",
  "sLastTimestamp": "",
  "STDOUT": "<script type=\"text\/javascript\">setTime(\"13:53\");\r\nsetDate(\"06.12.2017\");\r\nif( $(\"presence\") ) $(\"presence\").innerHTML = \"Normalbetrieb\";if( typeof(alarmLogSystem) == \"object\" ) alarmLogSystem.deleteAll();\r\nsetAlarmMessageCount(0);\r\nif( typeof(serviceLogSystem) == \"object\" ) serviceLogSystem.deleteAll();\r\nif (WebUI.HIDESTICKYUNREACH) \{var svcCount = 0;var stickyCount = 0;var visibleSvcCount = svcCount - stickyCount;if(visibleSvcCount < 0) \{visibleSvcCount = 0;}if( typeof(updateMessageView) == 'function' )updateMessageView(visibleSvcCount);setServiceMessageCount(visibleSvcCount);\r\n} else \{if( typeof(updateMessageView) == 'function' )updateMessageView(0);setServiceMessageCount(0);\r\n } if(urlParamInterfaces == \"true\") showRFInterfaces();\/\/ oUser: \r\nSwitchOffFlashLight();<\/script>",
  "sTM": "",
  "oPartnerTestChannel": "null",
  "sShortKey": "",
  "oAlarm": "AL-0002170990E1C9:0.UPDATE_PENDING",
  "sChannelName": "",
  "svCollection": "Root System Variables",
  "sLastTime": "",
  "svValue": "null",
  "svId": "",
  "iSvcCount": "0",
  "oLastTrigger": "null",
  "stickyCounter": "0",
  "sTimestamp": "",
  "cId": "0",
  "sID": "",
  "sDateTime": "",
  "sServiceMessage": "",
  "sSVID": "14678",
  "sTime": "13:53",
  "s1": "",
  "sLongKey": "",
  "sLastUse": "",
  "oPresence": "CCU SV Status",
  "s2": "",
  "oTestObject": "null",
  "oUser": "",
  "httpUserAgent": "",
  "oTestDevice": "null",
  "iAlCount": "0"
}
`
STDOUT:
`<script type="text/javascript">setTime("13:53");
setDate("06.12.2017");
if( $("presence") ) $("presence").innerHTML = "Normalbetrieb";if( typeof(alarmLogSystem) == "object" ) alarmLogSystem.deleteAll();
setAlarmMessageCount(0);
if( typeof(serviceLogSystem) == "object" ) serviceLogSystem.deleteAll();
if (WebUI.HIDESTICKYUNREACH) {var svcCount = 0;var stickyCount = 0;var visibleSvcCount = svcCount - stickyCount;if(visibleSvcCount < 0) {visibleSvcCount = 0;}if( typeof(updateMessageView) == 'function' )updateMessageView(visibleSvcCount);setServiceMessageCount(visibleSvcCount);
} else {if( typeof(updateMessageView) == 'function' )updateMessageView(0);setServiceMessageCount(0);
 } if(urlParamInterfaces == "true") showRFInterfaces();// oUser: 
SwitchOffFlashLight();</script>`

**Comment by jens-maus** [comment]
@sailor79 Die Frage ist nicht was das Skript ausgibt, die Frage ist ob bei der Ausführung des Skriptes es im Logfile parallel dazu zu einem ScriptRuntimeError kommt bei dir.

**Comment by sailor79** [comment]
Achso, ja:

`Dec  6 15:17:35 homematic-raspi local0.err ReGaHss: Error: IseESP::SyntaxError= Error 1 at row 1 col 14 near ^( OT_DEVICE ) )     {       object oTestDevice = oTestObject;       string sID =^M  [iseESP.cpp:1121]
Dec  6 15:17:35 homematic-raspi local0.err ReGaHss: Error: ParseProgram: SyntaxError= ( OT_DEVICE ) )     {       object oTestDevice = oTestObject;       string sID = oTestDevice.ID();       Write("if($('TestButtonCH"#sID#"'))$('TestButtonCH"#sID#"').className = 'TestButton';" );       Write("if($('OkButtonCH"#sID#"'))$('OkButtonCH"#sID#"').className = 'OkButton';" );       string sTimestamp = oTestDevice.LastTestCompletedTime();       Call("/esp/TimeStamp.fn::TimeStampToString3()");       Write("if($('Te
tDateCH"#sID#"'))$('TestDateCH"#sID#"').innerHTML = '"#sTimestamp#"';" );     }   }      string s;   foreach( s, dom.TestRunningIDs().EnumIDs() )   {     object oTestChannel = dom.GetObject( s );     if( oTestChannel )     {       Write("if($('TestButtonCH"#s#"'))$('TestButtonCH"#s#"').className = 'TestButtonDisabled';" );       Write("if($('OkButtonCH"#s#"'))$('OkButtonCH"#s#"').className = 'OkButtonRunning';" );       Write("if($('TestDateCH"#s#"'))$('TestDateCH"#s#"').innerHTML = '--:--:--';" );       
bject oTestDevice = dom`
