### ISSUE TITLE
RasperrbyMatic auf CCU über Ingress / HA zugreifbar machen

### ISSUE THREAD

**Issue by Bascht74** [jens-maus/RaspberryMatic#2080]
### Describe the solution you'd like

Hallo, 

ich betreibe RasperryMatic auf einer CCU3 und HA auf einer anderen Maschine. 
Ich habe versucht, über https://github.com/tux2000/home-assistant-addons eine Ingress-Verbindung zur CCU herzustellen, damit ich auch unterwegs auf die CCU3 zugreifen kann. 

Es wird zwar die Startseite geladen, aber scheinbar keine Bilder / scripts, usw.

ich habe gelesen, dass die CCU auf HA selbst dazu eine Besonderheit implementiert, damit der Zugriff über Ingress funktioniert: 
https://github.com/jens-maus/RaspberryMatic/blob/e7c5bf51ae973861a5ecf4fe26619b6d33ac86d5/buildroot-external/overlay/base-raspmatic_oci/bin/ha-proxy.js

Wäre es möglich, dies auch für das native RaspberryMatic zu ermöglichen, so dass über Ingress als Proxy aus der Ferne auf die separate CCU zugegriffen werden kann?

Auch z2m hat gerade einen solchen "Proxy" raus gebracht, um genau dieses Ziel zu ermöglichen: 
https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/tree/master/zigbee2mqtt-proxy

Aktuell bekomme ich folgende Meldungen:
![image](https://user-images.githubusercontent.com/66269310/205171491-f2911625-7e24-4534-909d-4abc764dfa86.png)

### Describe alternatives you've considered

Ich habe verschiedene Varianten versucht. Allerdings scheint es so, also ob eine Änderung an RaspberryMatic notwendig ist.

### Is your feature request related to a problem?

Kein echtes Problem. 
Allerdings ist es natürlich gut, wenn man dezidierte Systeme hat und diese trotzdem von einer Stelle aus verwalten kann. 
Über den Zugriff über NabuCasa, HA (inkl. Anmeldung) und Ingress-Proxy ist das vielleicht eine gute Alternative zu anderen Lösungsansätzen (CCU direkt über Portfreigabe wird nicht emfohlen, VPN-Verbindung geht nicht von einem fremden Rechner direkt usw.)

### Additional information

Vielleicht lässt sich ja eine Option einbauen, den o.a. nodejs proxy auch auf einer normalen CCU RaspberryMatic-Installation zu aktivieren, so dass die Oberfläche Proxy-fähig wird.
Vielleicht kenn auch noch jemand eine andere Möglichkeit, wie man das realisieren kann.
ich freue mich auf ein Feedback zu der Idee / Überlegung.

Gruß

Sebastian

**Comment by olafnorge** [comment]
Moin, für Haproxy würde ich diese Konfiguration empfehlen.

```
listen ccu
  bind :80
  bind :443 ssl crt /p<th/to/certificate.pem alpn h2,http/1.1
  mode http
  option forwardfor except 127.0.0.0/8
  http-request set-header X-Forwarded-Proto https if { ssl_fc }
  http-request set-header X-Forwarded-HTTPS on if { ssl_fc }
  http-after-response add-header Content-Security-Policy 'upgrade-insecure-requests'
  http-after-response replace-value Location ^http://(.*)$ https://\1 if { ssl_fc } # <-- rewrite any location header that want's to redirect to insecure connections
  http-request redirect scheme https code 301 if !{ ssl_fc }
  
  server ccu (ccu.your-local-domain.tld|ip-of-ccu):443 check inter 2500 ssl verify none # <-- speak TLS upstream
```

**Comment by jens-maus** [comment]
> Moin, für Haproxy würde ich diese Konfiguration empfehlen. Anpassungen an RaspberryMatic sind eigentlich nicht nötig. Man kann auch den Haproxy in `tcp`-Modus konfigurieren. Dann terminiert die CCU die Anfragen.

Mehr Details! Ich denke du sprichst hier von unterschiedlichen dingen. Haproxy != [ha-proxy.js](https://github.com/jens-maus/RaspberryMatic/blob/e7c5bf51ae973861a5ecf4fe26619b6d33ac86d5/buildroot-external/overlay/base-raspmatic_oci/bin/ha-proxy.js). Wüsste also nicht wo man deine Konfiguration die du hier vorschlägst nutzen sollte?

**Comment by olafnorge** [comment]
Moin Jens. Für [Haproxy](http://www.haproxy.org/) ist die Konfiguration. Habe dann wohl die Terminologie in der Beschreibung falsch verstanden.

**Comment by jens-maus** [comment]
> Moin Jens. Für [Haproxy](http://www.haproxy.org/) ist die Konfiguration. Habe dann wohl die Terminologie in der Beschreibung falsch verstanden.

Ich denke so ist es, ja. Es geht hier um einen Proxy für HA = HomeAssistant und nicht um den [HAProxy](http://www.haproxy.org/) um einen load balancer oder ähnliches umzusetzen.

**Comment by olafnorge** [comment]
Haproxy kann auch als Reverse-Proxy benutzt werden um einen Dienst nach außen verfügbar zu machen. Und ich hatte es so verstanden, dass dies über HomeAssistent gerade versucht wird. Vielleicht ist das nicht der richtige Ansatz und deshalb schlug ich Haproxy vor. Es ginge natürlich auch Nginx, Apache, oder welcher andere Webserver mit Reverse Proxy Eigenschaften sonst noch denkbar ist. 

Ich denke, dass mich dieser Satz getriggert hat:
> Ich habe versucht, über https://github.com/tux2000/home-assistant-addons eine Ingress-Verbindung zur CCU herzustellen, damit ich auch unterwegs auf die CCU3 zugreifen kann.

**Comment by olafnorge** [comment]
Möchte mich aber auch gar nicht weiter einmischen.

**Comment by Bascht74** [comment]
@olafnorge Trotzdem danke, dass Du Deine Idee hier geteilt hast. 
In der Tat geht es darum, dass man über den HA Ingress-Proxy auf eine "echte" CCU3 mit RaspberryMatic zugreifen kann. 
Quasi genau so, wie bei dem HA-Addon, wo das "out of the box" funktioniert, weil dort - wenn ich es richtig verstehe - etwas über node.js getan wurde. 

Die Frage/der Vorschlag wäre, dass dies auch für eine native CCU3 "aktivierbar" ist, so dass diese über ingress/HA von außen "gesichert" erreichbar ist. 
Analog dem Z2M-Plugin, was dazu gerade heraus gebracht wurde.

Ich hoffe @jens-maus verschwendet einen weihnachtlichen Gedanken daran :-)
Wobei ich nicht weiß, ob es überhaupt möglich ist.
