### ISSUE TITLE
Keine WLan Anbindung mehr möglich

### ISSUE THREAD

**Issue by gironhimo** [jens-maus/RaspberryMatic#209]
Nachder beschriebenen neuinstallation des neuesten raspMatic Images RaspberryMatic-2.29.23.20171118-rpi3 und der beschriebenen Datenrücksicherung funktioniert das WLan nicht mehr. Auch mit der beschriebenen aktivierung
iw wlan0 scan(invalid argunment -22) und den darauf folgenden befehlen kann Wlan nicht aktiviert werden.

Mit dem vorherigen Image
RaspberryMatic-2.29.23.20171022-rpi3 funktioniert WLan ohne Probleme

**Comment by Motorpsycho123** [comment]
https://github.com/jens-maus/RaspberryMatic/issues/197

**Comment by jens-maus** [comment]
Bereits bekannt und auch bereits repariert. Siehe #197 Und morgen kommt der neue, reparierte Release...
