### ISSUE TITLE
Cannot connect LAN gateway

### ISSUE THREAD

**Issue by baflo** [jens-maus/RaspberryMatic#2094]
### Describe the issue you are experiencing

My fundamental issue is, that I cannot connect a LAN gateway with a RasperryMatic CCU. I am creating a new setup without any legacy configuration. My target is to use a HMIP-RFUSB as LAN gateway and run RaspberryMatic in a virtualized environment.

I configure the LAN gateway in the CCU and restart. After it restarted, I check the gateway configuration I find no "status" or "connected" information on the configured gateway.

### Describe the behavior you expected

The CCU should connect to the LAN gateway.

### Steps to reproduce the issue

1. Setup a system with RasberryMatic and configure as CCU
    1. Configure static IP address
    4. Open the LAN gateway configuration page
    5. Note the "serial numbers" shown in columns "Serial Number" and "Gateway"
    6. Connect display and note the serial number shown there
    7. Go in maintenance console and run touch the file `/usr/local/HMLGW`
    8. Restart
1. Setup a second system with RasberryMatic and configure as CCU
    1. Add LAN gateway using the static IP address and one of the serial numbers
    10. Restart CCU
3. Check whether LAN gateway was successfullly configured

I tried with different setups:
* on every physical system I used RaspberryMatic version: 3.65.11.20221005
* on Hyper-V I used RaspberryMatic version: 3.61.7.20211218
* Raspi 1 LAN Gateway and Raspi 3 LAN Gateway
* Raspi 1, Raspi Zero 2, Raspi 3 and Hyper-V CCU
* different serial number, as I was not sure:
   * the one found in the column "Serial Number" in LAN gateway overview
   * the one found in the column "Gateway" in LAN gateway overview
   * the one found in the display output of the LAN gateway

### What is the version this bug report is based on?

3.65.11.20221005

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
2022-12-15 12:19:53,621 de.eq3.ccu.bidcos.dispatcher.BidCosRpcDispatcher ERROR [Timer-1] Could not register BidCos-RF_java
```

and 

```
Dec 15 12:28:22 homematic-raspi user.err monit[1639]: 'rfd' failed to restart (exit status -1) -- '/etc/init.d/S61rfd restart': Program timed out -- start-stop-daemon: warning: killing process 1401: No such process
Dec 15 12:28:22 homematic-raspi user.err monit[1639]: Lookup for '/media/usb1' filesystem failed  -- not found in /proc/self/mounts
Dec 15 12:28:22 homematic-raspi user.err monit[1639]: Filesystem '/media/usb1' not mounted
Dec 15 12:28:22 homematic-raspi user.err monit[1639]: 'usb1' unable to read filesystem '/media/usb1' state
Dec 15 12:28:22 homematic-raspi user.info monit[1639]: 'usb1' trying to restart
Dec 15 12:28:40 homematic-raspi user.warn monit[1639]: 'hasUSB' status failed (1) -- no output
Dec 15 12:28:40 homematic-raspi user.err monit[1639]: 'wlan0CheckEnabled' status failed (1) -- no output
Dec 15 12:28:40 homematic-raspi user.warn monit[1639]: 'eMMCLifeTimeCheck' status failed (1) -- no output
Dec 15 12:28:40 homematic-raspi user.warn monit[1639]: 'rpi4usb3Check' status failed (1) -- no output
Dec 15 12:28:40 homematic-raspi user.err monit[1639]: 'rfd' service restarted 1 times within 1 cycles(s) - exec
Dec 15 12:28:40 homematic-raspi user.info monit[1639]: 'rfd' exec: '/bin/triggerAlarm.tcl rfd restarted WatchDog: rfd-restart true'
Dec 15 12:28:40 homematic-raspi user.err monit[1639]: 'rfd' process is not running
Dec 15 12:28:40 homematic-raspi user.info monit[1639]: 'rfd' trying to restart
Dec 15 12:28:40 homematic-raspi user.info monit[1639]: 'rfd' restart: '/etc/init.d/S61rfd restart'
Dec 15 12:28:40 homematic-raspi user.err rfd: UnifiedLanCommController::connect(): Unable to connect.
Dec 15 12:28:40 homematic-raspi user.crit rfd: CCU2LGWCommController::init(): Cannot connect to HomeMatic Lan Gateway with serial number xxxxxxxxx.
Dec 15 12:28:40 homematic-raspi user.err rfd: No BidCoS-Interface available
```
```


### Additional information

_No response_

**Comment by Baxxy13** [comment]
This is not a bug. 
Only the HM-MOD-RPI-PCB can be used for RaspberryMatic as LGW.

**Comment by erhanlale** [comment]
Are you sure? 
I was using HM-cfg-lan as LGW. A few weeks ago I had connection issues with some devices. I checked today and saw, that hm-cfg-lan not connected anymore. It has still same IP-Address, SN and other code can not change anyway. 
![hm-lan](https://user-images.githubusercontent.com/94985546/208252918-b134f732-8574-4ca5-87da-8f0af27cf39d.png)

**Comment by Baxxy13** [comment]
Yes, sure. 
But my english isn't very well, maybe you missunderstand my writing.

What i mean is...
You cannot convert a normal RaspberryMatic (with HmIP-RFUSB or RPI-RF-MOD) to LGW to connect it as LGW with another RaspberryMatic. This is only possible with HM-MOD-RPI-PCB (in the RaspberryMatic to convert).

**Comment by erhanlale** [comment]
I was looking for a solution to my problem and misinterpreted the first post and your answer. 

I think, I have to open a new issue.

**Comment by baflo** [comment]
Hey @Baxxy13, sorry it took me so long to answer. I was just lacking time to confirm things...

I own an "official" HomeMatic CCU2. Just to verify I connected the LAN gateway with HM-RFUSB to the CCU2 and it worked like a charm. 

However, another try with the Raspberrymatic CCU again did not succeed in connecting the LAN gateway.

**Comment by Baxxy13** [comment]
Weil mein Englisch wohl missverständlich ist...

Nochmal auf deutsch:

Aktuell kann eine RaspberryMatic nur zum LGW gemacht werden wenn man ein HM-MOD-RPI-PCB darauf einsetzt!

Möglicherweise ändert sich das demnächst so das dann auch RaspberryMatic's mit HmIP-RFUSB oder RPI-RF-MOD zum LGW gemacht werden können.

**Comment by jp112sdl** [comment]
Meanwhile, the HMIP-RFUSB is supported since [3.67.10.20230114](https://github.com/jens-maus/RaspberryMatic/releases/tag/3.67.10.20230114) https://github.com/jens-maus/RaspberryMatic/pull/2132, so this can be closed.
