### ISSUE TITLE
Fresh Install causes reboot which hangs

### ISSUE THREAD

**Issue by HarryHpd** [jens-maus/RaspberryMatic#2095]
### Describe the issue you are experiencing

after first boot of a fresh imaged SD Card with RP4 + RPI-RF_MOD Raspimatic will reboot after a couple of minutes. Webui will only be available for a couple of seconds.
Reboot will hang immediatly.
Repowering the RP4 will lead to the same result as described before. It takes about 10 Minutes from Boot to Reboot.
Reboot will not happen with RPI-RF-MOD removed frm RP4. This allowed me to activate ssh. 
/var/log shows  a countdowntimer in file piupsmon.log. After killing /opt/piusvd/piupsmon the timer via ssh this misbeviour appears to be stopped.
Everything appears to work as expected (as far as a CCU3 newbie can tell). Devices can be teached in, Thermostats and valve motors can be coupled etc.

But repowering the RP4 leads to behaviour as described above

### Describe the behavior you expected

no halt after installation

### Steps to reproduce the issue

1. described above
2.
3.
...

### What is the version this bug report is based on?

3.65.11.20221005

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
/var/log/piupsmon.log
2022-12-15 14:51:13 [NOTICE] Shutdown timer: 157 / 300
2022-12-15 14:51:14 [NOTICE] Shutdown timer: 158 / 300
2022-12-15 14:51:15 [NOTICE] Shutdown timer: 159 / 300
2022-12-15 14:51:16 [NOTICE] Shutdown timer: 160 / 300
2022-12-15 14:51:18 [NOTICE] Shutdown timer: 161 / 300
2022-12-15 14:51:19 [NOTICE] Shutdown timer: 162 / 300



/log/lighttpd-error.log 
2022-12-15 14:57:23: (../src/gw_backend.c.993) all handlers for /esp/system.htm?sid=@OSchE7eB6a@&action=UpdateUI on
2022-12-15 14:57:25: (../src/gw_backend.c.360) gw-server re-enabled: tcp:127.0.0.1:8183 127.0.0.1 8183
2022-12-15 14:57:26: (../src/gw_backend.c.283) establishing connection failed: socket: tcp:127.0.0.1:8183: Connecti
2022-12-15 14:57:26: (../src/gw_backend.c.993) all handlers for /esp/system.htm?sid=@OSchE7eB6a@&action=UpdateUI on
2022-12-15 14:57:28: (../src/gw_backend.c.360) gw-server re-enabled: tcp:127.0.0.1:8183 127.0.0.1 8183
2022-12-15 14:57:29: (../src/gw_backend.c.283) establishing connection failed: socket: tcp:127.0.0.1:8183: Connecti
2022-12-15 14:57:29: (../src/gw_backend.c.993) all handlers for /esp/system.htm?sid=@OSchE7eB6a@&action=UpdateUI on
2022-12-15 14:57:31: (../src/gw_backend.c.360) gw-server re-enabled: tcp:127.0.0.1:8183 127.0.0.1 8183



/var/messages
Dec 15 14:57:37 homematic-raspi local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1009, params:
Dec 15 14:57:37 homematic-raspi local0.err ReGaHss: ERROR: CallGetValue failed; sVal = 0 [ReadValue():iseDOMdpHSS.c
Dec 15 14:57:37 homematic-raspi local0.warn ReGaHss: WARNING: XMLRPC 'getValue': rpcClient.isFault() failed (url: x
Dec 15 14:57:37 homematic-raspi local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1009, params:
Dec 15 14:57:37 homematic-raspi local0.err ReGaHss: ERROR: CallGetValue failed; sVal = 0 [ReadValue():iseDOMdpHSS.c
Dec 15 14:57:37 homematic-raspi local0.warn ReGaHss: WARNING: XMLRPC 'getValue': rpcClient.isFault() failed (url: x
Dec 15 14:57:37 homematic-raspi local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1009, params:
Dec 15 14:57:37 homematic-raspi local0.err ReGaHss: ERROR: CallGetValue failed; sVal = 0.000000 [ReadValue():iseDOM
Dec 15 14:57:37 homematic-raspi local0.warn ReGaHss: WARNING: XMLRPC 'getValue': rpcClient.isFault() failed (url: x
Dec 15 14:57:37 homematic-raspi local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1009, params:
Dec 15 14:57:37 homematic-raspi local0.err ReGaHss: ERROR: CallGetValue failed; sVal = 0 [ReadValue():iseDOMdpHSS.c
Dec 15 14:57:37 homematic-raspi local0.warn ReGaHss: WARNING: XMLRPC 'getValue': rpcClient.isFault() failed (url: x
Dec 15 14:57:37 homematic-raspi local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1009, params:
Dec
```

### Additional information

After some further investigation, I realized that this behaviour is probabaly derived from a USV Monitoring system implemented in Raspberrymatic. It appears to me this monitor thinks there is a Power failure with my setup.

I am powering via Pi4-USB-C jack using a powerfull Power supply

I am aware of the fact, that RP4 is not the ideal platform for Raspimatic. But due the actual shortage of PI3 I currently have no other choice than this or some older P2 Model B Devices. But I had no lock with theses devices neither.

Interesting to say, that there are no radio interfearance problems so far with this device. (finger crossed)

**Comment by jens-maus** [comment]
Well, the main question here actually is: do you have such a PiUPS HAT installed on your Pi4 at all or not? Because if not, this might actually mean RaspberryMatic is falsly identifying it during bootup. So please have a look at the `/var/log/boot.log` and post the results here for further analysis.

**Comment by HarryHpd** [comment]
... No, there is no such "HAT" installed.

beside the problem reported, the system is happily doing what it is
supposed to do and I have not rebooted it since 21.12.2022.

Please find enclosed the boot.log you asked for.



Am Sa., 7. Jan. 2023 um 10:56 Uhr schrieb Jens Maus <
***@***.***>:

**Comment by jens-maus** [comment]
> Please find enclosed the boot.log you asked for.

Please don't reply to GitHub ticket emails, but use the web interface to answer and upload attachments, because your boot.log did not make it into the issue ticket due to you replying via your mail client.

**Comment by jens-maus** [comment]
And do you have any other HAT installed on the GPIO bus? Because RaspberryMatic will execute the `piusvd` daemon in case it identifies something on address `0x18` at the i2c bus. So please try to execute the following command and present the output here:

```
i2cdetect -y 1
```

**Comment by HarryHpd** [comment]
..yes, just noticed it, just a minute ago :-).

[boot.log](https://github.com/jens-maus/RaspberryMatic/files/10373564/boot.log)

I hope, thats better now

**Comment by jens-maus** [comment]
> ..yes, just noticed it, just a minute ago :-).
> 
> [boot.log](https://github.com/jens-maus/RaspberryMatic/files/10373564/boot.log)
> 
> I hope, thats better now

Better, yes. However, there are some suspicious outputs in your boot.log. Like:

```
Starting ArgonONE/FAN daemon: OK
Starting PIco UPS daemon: OK
Starting PiUSV+ daemon: FAIL
Starting S.USV daemon: WARNING: couldn't identify firmware version, OK
```

So somehow, all these startup services seem to identify third-party hardware being installed on your GPIO bus while this probably is not the case. Do you have any of these things (e.g. ArgoneONE/FAN, etc.) installed at all? So how did you connect the RPI-RF-MOD to the GPIO of your Pi4? Perhaps you have some hardware issues there with the stacking header or something else.

And if not this could point at some hardware problems with the GPIO bus of your Pi4 itself. Therefore post the output of `i2cdetect -y 1` for a more detailed investigation. However, as you can see from boot.log, RaspberryMatic seem to falsly identify third-party hardware being located on your GPIO bus which certainly is not the case.

**Comment by HarryHpd** [comment]
There is nothing else installed. 

Results of 
i2cdetect -y 1

root@homematic-raspi:~# i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         08 09 0a 0b 0c 0d 0e 0f
10: 10 11 12 13 14 15 16 17 18 19 1a 1b 1c 1d 1e 1f
20: 20 21 22 23 24 25 26 27 28 29 2a 2b 2c 2d 2e 2f
30: 30 31 UU 33 34 35 36 37 38 39 3a 3b 3c 3d 3e 3f
40: 40 41 42 43 44 45 46 47 48 49 4a 4b 4c 4d 4e 4f
50: 50 51 52 53 54 55 56 57 58 59 5a 5b 5c 5d 5e 5f
60: 60 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e 6f
70: 70 71 72 73 74 75 76 77

**Comment by jens-maus** [comment]
Oh, this doesn't look so good indeed. usually all these register show be `00` if there is nothing connected. Thus, this completly explain why upon startup RaspberryMatic things there is something connected. Thus, either the stacking header you are using to connect the RPI-RF-MOD to the GPIO is broken or the I2C pins on the GPIO bus itself. So please retry with a different/other RaspberryPi4 first. Nevertheless, this is definitly no bug within RaspberryMatic but a local issue on your end.

**Comment by HarryHpd** [comment]
You are right. I accept this. Yu can close this is
