### ISSUE TITLE
Direktverknüpfung – DLD "open" funktioniert nicht, DLD entriegelt nur

### ISSUE THREAD

**Issue by brennermax** [jens-maus/RaspberryMatic#2099]
### Describe the issue you are experiencing

Mittels einer Direktverknüpfung habe ich einem WKP-Keypad-Benutzer das Öffnen ("open") des DLDs erlaubt. Nach Eingabe des Codes entriegelt das DLD (bei Locked-State) nur, sodass man erneut den Code eingeben muss. Dann erst wird durch das DLD die Türfalle gezogen. Die Buttons des DLD auf der Startseite funktionieren aber wie sie sollen (beim Betätigen des "open"-Buttons, öffnet das DLD wie gewohnt aus jedem State die Tür).

### Describe the behavior you expected

Bei Locked-State sollte das DLD beim "open"-Befehl die Tür entriegeln und dann öffnen.

### Steps to reproduce the issue

S.o.

### What is the version this bug report is based on?

3.65.11.2022100

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
No.
```

**Comment by Baxxy13** [comment]
Klingt für mich jetzt nicht nach einem Bug in RaspberryMatic.
Das was der Aktor macht wenn er z.B. ein PRESS_SHORT vom Verknüpfungspartner empfängt wird direkt in der Aktorfirmware festgelegt (Empfängerprofil).
Es könnte natürlich sein das beim anlegen/editieren des Empängerprofils was schiefläuft.
Da müsste man mal einen Vergleichstest mit original CCU3 machen. Vielleicht im Homematic-Forum mal fragen ob das jemand mit original CCU mal testen kann.

Kann man denn eine virtuelle Taste (statt des WKP) mit der gleichen Funktion (mit dem DLD) verknüpfen und wenn ja, geht das dann wie erwartet?

**Comment by paulcombuse** [comment]
Also bei mir läuft das mit DLD, allerdings WICHTIG ist, dass man nach dem Anlegen der Direktverknüpfung auf Bearbeiten geht und dort die korrekte Aktion auswählt - in diesem Fall "Öffnen". Standardmäßig ist dort "Toggle" ausgewählt, was zu dem von Dir beschriebenen Verhalten führen könnte.
![image](https://user-images.githubusercontent.com/65916471/215086910-7cd502ac-877c-4940-8df9-51db8d76a725.png)

**Comment by brennermax** [comment]
> @brennermax bei mir läuft das mit DLD, allerdings WICHTIG ist, dass man nach dem Anlegen der Direktverknüpfung auf Bearbeiten geht und dort die korrekte Aktion auswählt - in diesem Fall "Öffnen". Standardmäßig ist dort "Toggle" ausgewählt, was zu dem von Dir beschriebenen Verhalten führen könnte.
> 
> ![image](https://user-images.githubusercontent.com/65916471/215086910-7cd502ac-877c-4940-8df9-51db8d76a725.png)
> 
> 

Danke dir! Habe ich beim Anlegen der Verknüpfung schon eingestellt :-)

**Comment by paulcombuse** [comment]
@brennermax ja, stimmt - nach Deinem Kommentar habe ich gerade erneut das Verhalten geprüft und irgendwie hatte das nach meinem Update gestern (auf 3.67.10-2023.01.14) noch kurzzeitig bei mir funktioniert, aber nun habe ich das gleiche Verhalten wie Du. Welche Firmware nutzt Du? Firmware hatte ich nämlich auch aktualisiert. Bei mir hat das Keypad HmIP-WKP nun die **FW 1.0.10**.

**Comment by brennermax** [comment]
> @brennermax ja, stimmt - nach Deinem Kommentar habe ich gerade erneut das Verhalten geprüft und irgendwie hatte das nach meinem Update gestern (auf 3.67.10-2023.01.14) noch kurzzeitig bei mir funktioniert, aber nun habe ich das gleiche Verhalten wie Du. Welche Firmware nutzt Du? Firmware hatte ich nämlich auch aktualisiert. Bei mir hat das Keypad HmIP-WKP nun die **FW 1.0.10**.

Meins hat auch 1.0.10 - liegt das an ELV oder an der CCU?

**Comment by paulcombuse** [comment]
Ich denke es liegt eher an der Raspberrymatic Software, denn ich hatte zwischen HmIP-WKP und HmIP-DLD vier Direktverknüpfungen für zwei User (1+3) - jweils zum Verriegeln und zum echten Öffnen.
Da ich nach dem Update auf die neuste Raspberrymatic Version dann [folgenden Bug](https://github.com/jens-maus/RaspberryMatic/issues/2187#issue-1559721182)  entdeckt hatte, habe ich die Direktverknüpfung vom User 1 beiden gelöscht und neu angelegt. Bei User 1 beobachte ich das von Dir genannte Verhalten "Entriegeln" (mit der neuen "Öffnen" Direktverknüpfung), wohingegen ich bei User 3 mit der alten Direktverknüpfungen "Öffnen" das gewünschte Verhalten "Öffnen" habe. Alt und Neu kann ich dabei durch die neu eingebauten Fehler mit der Verarbeitung von Umlauten auch sehr schön auseinanderhalten (siehe Screenshot im von mir gemeldeten Bug).
