### ISSUE TITLE
Übersetzung nicht korrekt / Gerät nicht bedienbar

### ISSUE THREAD

**Issue by mbhomie007** [jens-maus/RaspberryMatic#2102]
### Describe the issue you are experiencing

https://homematic-forum.de/forum/viewtopic.php?p=748456#p748456

Aufruf über Gewerk "Licht":
![image](https://user-images.githubusercontent.com/64688879/208318728-cd8a4dda-6c95-4e3f-ae7a-3852c791689e.png)

Auch Gewerk "Licht" CUXD RGBW-Gerät:
Außerdem Bild weg.
![image](https://user-images.githubusercontent.com/64688879/208318741-df3b9984-8245-4aad-80f4-535247c18365.png)

Direkt über Aufruf "Gerät":
Fenster lässt nicht nicht mehr schließen.
Gerät lässt sich nicht mehr bedienen.
![image](https://user-images.githubusercontent.com/64688879/208318751-130b1c0a-97df-45ec-b8df-59e53ca4f2f8.png)

Aufruf über "Gewerke":

![image](https://user-images.githubusercontent.com/64688879/208318772-3ae882f2-ea07-460d-b256-795bc6a8bb4e.png)

Über "Geräte" sieht alles okay aus.

@jp112sdl

```
Uncaught ReferenceError: preferredFormat is not defined
    convertWhiteValue http://192.168.1.254/webui/js/extern/spectrum.js:970
    updateOriginalInput http://192.168.1.254/webui/js/extern/spectrum.js:959
    clickout http://192.168.1.254/webui/js/extern/spectrum.js:717
```     

### Describe the behavior you expected

Richtige Anzeige
Geräte funktionieren

### Steps to reproduce the issue

1. Aufruf Gewerke
2. Aufruf Geräte

### What is the version this bug report is based on?

3.65.11.20221218

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Uncaught ReferenceError: preferredFormat is not defined
    convertWhiteValue http://192.168.1.254/webui/js/extern/spectrum.js:970
    updateOriginalInput http://192.168.1.254/webui/js/extern/spectrum.js:959
    clickout http://192.168.1.254/webui/js/extern/spectrum.js:717
```

**Comment by jens-maus** [comment]
@mbhomie007 @jp112sdl 
Bitte mal probieren die `spectrum.js` in `/www/webui/js/extern` gegen die Version hier zu ersetzen und zu schauen ob damit das Problem gelöst ist:

https://raw.githubusercontent.com/jens-maus/RaspberryMatic/master/buildroot-external/overlay/WebUI-raspmatic/www/webui/js/extern/spectrum.js

**Comment by jp112sdl** [comment]
Der `spectrum.js`-Fehler ist damit behoben. 👍

Zu den fehlenden Übersetzungen innerhalb des Colorpickers hatte ich hier was geschrieben:
https://homematic-forum.de/forum/viewtopic.php?f=37&t=76348#p742022

**Comment by jens-maus** [comment]
Super! Danke fürs querchecken. Danke auch für den Hint bzgl. der falschen Übersetzungen. Hatte mich schon gewundert warum da Rot/Grün/Blau gegen "Farbton", "Sättigung" und "Helligkeit" eingetauscht wurde/wird.... Müssten wir das also zurücknehmen und die fehlenden Übersetzungen dafür dann wohl in eine der `translate.js` Dateien unterbringen oder was meinst du? Da muss doch korrekterweise Rot/Grün/Blau stehen oder übersehen wir hier einen Fall in der WebUI wo Farbton,Sättigung,Helligkeit passen würde?

**Comment by jp112sdl** [comment]
Puh, gute Frage.

Ich weiß nicht, ob sich der gesamte Colorpicker nun in der 3.67 auf die Hue-Skala bezieht und in den Feldern tatsächlich die Angaben Farbton, Sättigung und Helligkeit dargestellt werden.

**Comment by jens-maus** [comment]
Im aktuellen eq-3/occu wurde mit den 3.67.x release candidates ja explizit auf "Farbton", "Sättigung", "Helligkeit", etc. das `spectrum.js` geändert. Siehe https://github.com/eq-3/occu/commit/53f45b9d618865d80df417e1ca55d376ed1fc013#diff-395d77336421ca79ea54386162b4aa92a074dcab33b399317502711e26ef6995

**Comment by jp112sdl** [comment]
Aber dort auch nur die Labels. 
Wurde das Popup mit dem Colorpicker selbst auch angefasst?
Hab grad nicht wirklich Zeit, um mich durch die Diffs zu wühlen und mich im Detail damit zu befassen.

**Comment by jens-maus** [comment]
> Aber dort auch nur die Labels. Wurde das Popup mit dem Colorpicker selbst auch angefasst?

Wenn ich wüsste wo ich da suchen muss... Bin froh das ich die 3.67.x nun prinzipiell gemerged bekommen habe. Morgen wird ja der nightly build dann mehr zeigen/verraten...

> Hab grad nicht wirklich Zeit, um mich durch die Diffs zu wühlen und mich im Detail damit zu befassen.

Ja, verstehe ich. Ist immer so ne Sache die Änderungen von eQ3 nachzuvollziehen. Meine Vermutung ist aber es wurden nur die Labels angefasst. Am Colorpicker selbst (spectrum.js) hat sich sonst nichts geändert...

**Comment by jp112sdl** [comment]
Neu ist auch die `/www/webui/js/extern/iro.js` wo ein Haufen Farbkram gerechnet wird.

> Meine Vermutung ist aber es wurden nur die Labels angefasst.

In der `/www/rega/esp/functions.fn` hat sich auch was geändert.

**Comment by mbhomie007** [comment]
Habe nun die Nightly Testversion 3.67.9.20221220-f865fa auf meinem RPI3+ installiert und getestet.

Es funktioniert nun wieder alles und die Geräte sind wieder bedienbar.
Außerdem ist die "komische" Übersetzung weg und es sieht alles wieder normal aus.

Vielen Dank für die schnelle Fehlerbehebung! :-)

**Comment by jens-maus** [comment]
Dann kann ich ja nun hier dicht machen. Danke fürs testen.
