### ISSUE TITLE
HmIP Heizungsgruppen erstellen hängt bei Erstellung der Verbindungen

### ISSUE THREAD

**Issue by eNBeWe** [jens-maus/RaspberryMatic#2111]
### Describe the issue you are experiencing

Ich versuche eine HomematicIP Heizungsgruppe zu erstellen. Ich kann Gruppen ohne Geräte erstellen, aber sobald ich versuche Geräte zu ergänzen (egal ob bei der ersten Erstellung oder danach) hängt das UI bei der Erstellung der Verbindungen.
Wenn ich die Seite nue lade, sind keine Verbindungen registriert.

DAs Problem besteht sowohl direkt auf einem RasPi4, als auch als Home Assistant Addon.

In Version 3.65.11.20221005 funktioniert noch alles problemlos.

### Describe the behavior you expected

Die Heizungsgruppe und die dazugehörigen Verbindungen werden erstellt.

### Steps to reproduce the issue

1. Lerne Geräte in der Software an.
2. Erstelle eine neue HmIP-Heizungsgruppe mit mindestens einem Gerät.

### What is the version this bug report is based on?

3.65.11.20221218

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
-
```

**Comment by jens-maus** [comment]
Duplicate of #2105
