### ISSUE TITLE
Firmware Update obwohl eine neuere Version auf dem Gerät ist

### ISSUE THREAD

**Issue by Andy2020-DE** [jens-maus/RaspberryMatic#2113]
### Describe the issue you are experiencing

Ich bekomme seit einigen Versionen immer ein Geräte-Update für zwei Geräte (HmIP-SMO-A) angezeigt.
Diese Geräte haben aber eine aktuellere Version wie die zum Update angebotene Version aufgespielt.

Gerät	        Seriennummer	Aktuell	Neu
HmIP-SMO-A	000BDD898ADXXX	1.2.9        1.2.8
HmIP-SMO-A	000BDD898ADXXX	1.2.9	        1.2.8

Nun habe ich heute die RaspberryMatic Version 3.65.11.20221218 installiert und erhalte nach wie vor die Meldung Geräte-Update

![HM-Bild](https://user-images.githubusercontent.com/81467080/208978263-cf178bef-578c-407b-91db-efda678e9fc6.jpg)

### Describe the behavior you expected

Normalerweise sollte es keine Info bezüglich eines Geräte-Updates geben, da die Installierte Version aktueller ist wie die "neue" Version. 

### Steps to reproduce the issue

1. Siehe Startseite
2.
3.
...
![HM-Bild](https://user-images.githubusercontent.com/81467080/208978988-afc53c66-c4b8-45dc-bfab-575840112d5b.jpg)

### What is the version this bug report is based on?

3.65.11-20221218

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
Steht auf der Startseite, kein log nötig.
```

**Comment by jens-maus** [comment]
Kein Bug, sondern ein Feature. Hier wird dir bewusst ein Downgrade vorgeschlagen weil eQ3 für die Nutzung mit einer CCU eben gewisse Gerätefirmwares vorschlägt bzw. diese damit getestet hat. Insofern ist das kein Problem oder Bug, sondern eben einfach ein Hinweis darauf das die Firmware dieser Geräte nicht mit der Firmwareversion übereinstimmt die die jeweilige CCU/RaspberryMatic Version eben benötigt. Höhere Versionsnummer heisst eben zwangsläufig nicht immer besser/passender!
