### ISSUE TITLE
Kann keine Geräte zu HmIP-Heizungsgruppe hinzufügen

### ISSUE THREAD

**Issue by agroezinger** [jens-maus/RaspberryMatic#2116]
### Describe the issue you are experiencing

Eine HmIP-Heizungsgruppe konnte ich erstellen. Es lassen sich aber keine Geräte hinzufügen. Ich bleibe nach dem Bestätigen in einer endlosen Schleife (Bitte warten. Die direkten Verknüpfungen werden konfiguriert.) hängen. Ich habe extra die CCU3 (ELV-Charly) komplett auf Werkseinstellungen zurückgesetzt und nur 2 Geräte testweise erneut angelernt.

![Animation](https://user-images.githubusercontent.com/12061647/209351006-dad7a95a-97f2-4a79-bbaf-e7112715d0d9.gif)

### Describe the behavior you expected

Hinzufügen von Geräten in die Gruppe sollte funktionieren

### Steps to reproduce the issue

siehe Screecast

### What is the version this bug report is based on?

3.65.11.20221218

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
-
```

**Comment by agroezinger** [comment]
Update: Da mein letztes Backup vor Reset für die Version 3.65.11.20221005 war, habe ich eben auf diese Version wiederhergestellt. Bei dieser Version kann ich die Gruppe problemlos anlegen. Ich trau mich jetzt aber nicht mehr, nochmals auf die aktuelle Version upzudaten

**Comment by jens-maus** [comment]
Same, same, but different:

https://github.com/jens-maus/RaspberryMatic/issues/2105

**Comment by heinrich45** [comment]
same here
