### ISSUE TITLE
firmware update via eq3configcmd macht HM-MOD-UART kaputt

### ISSUE THREAD

**Issue by jp112sdl** [jens-maus/RaspberryMatic#2120]
### Describe the issue you are experiencing

Will man die Firmware eines HM-MOD-RPI-PCB mithilfe des Tools `eq3configcmd` up-/downgraden ( 1.4.1 <> 2.8.6) schlägt das Update fehl und der HM-MOD-UART hängt im Bootloader fest.

Siehe auch https://homematic-forum.de/forum/viewtopic.php?f=65&t=76910

### Describe the behavior you expected

Flashvorgang wird von `eq3configcmd` korrekt ausgeführt.

### Steps to reproduce the issue

1.  eq3configcmd update-coprocessor -t HM-MOD-UART -p /dev/raw-uart -c -u -l 0 -d /firmware/HM-MOD-UART/

### What is the version this bug report is based on?

3.67.9.20221220

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
Von 2.8.6 auf 1.4.1:

root@homematic-raspi:~# eq3configcmd update-coprocessor -t HM-MOD-UART -p /dev/raw-uart -c -u -l 0 -d /firmware/HM-MOD-UART/
2022/12/25 07:00:59.785 <Debug> firmware filename is: coprocessor_update.eq3

2022/12/25 07:01:00.392 <Debug> () CCU2CommControllerMod::handleIdentifyEvent(): Coprocessor is in dual coprocessor application.
2022/12/25 07:01:00.392 <Debug> () CCU2CommControllerMod::handleIncomingSerialFrame(): Command not parseable. Expected was frame of type HmIP
2022/12/25 07:01:00.654 <Debug> CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): lowlevelmac frame
2022/12/25 07:01:00.654 <Debug> () CCU2CommControllerMod::handleIncomingSerialFrame(): Command not parseable. Expected was frame of type HmIP
2022/12/25 07:01:01.293 <Debug> () CCU2CommControllerMod::handleIncomingSerialFrame(): Command not parseable. Expected was frame of type HmIP
2022/12/25 07:01:01.876 <Debug> CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): lowlevelmac frame
2022/12/25 07:01:01.876 <Debug> () CCU2CommControllerMod::handleIncomingSerialFrame(): Command not parseable. Expected was frame of type HmIP
2022/12/25 07:01:02.286 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
2022/12/25 07:01:02.286 <Error> CCU2CommControllerMod::performIdentify(): Unable to determine coprocessor state.
2022/12/25 07:01:02.291  getApplicationVersion()
2022/12/25 07:01:02.291  CoprocessorUpdate::startApplication()
2022/12/25 07:01:02.292 <Debug> CoprocessorUpdate::startApplication():Coprocessor entered application.
2022/12/25 07:01:02.899 <Debug> CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): TrxAdapter frame
2022/12/25 07:01:02.901 <Info> Version: 2.8.6

2022/12/25 07:01:02.902 <Info> Update necessary, installed: 2.8.6, avaiable 1.4.1

2022/12/25 07:01:02.905  CoprocessorUpdate::startBootloader()
2022/12/25 07:01:02.906 <Debug> () CCU2CommControllerMod::startCoprocessorBootloader(): Trying to start coprocessor bootloader
2022/12/25 07:01:02.914 <Debug> () CCU2CommControllerMod::handleIncomingSerialFrame(): Command not parseable. Expected was frame of type HmIP
2022/12/25 07:01:02.959 <Debug> CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): lowlevelmac frame
2022/12/25 07:01:02.960 <Debug> () CCU2CommControllerMod::handleIncomingSerialFrame(): Command not parseable. Expected was frame of type HmIP
2022/12/25 07:01:03.149 <Debug> CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): System frame
2022/12/25 07:01:03.151 <Debug> () CCU2CommControllerMod::handleIdentifyEvent(): Coprocessor is in bootloader.
2022/12/25 07:01:03.408 <Debug> CoprocessorUpdate::startBootloader():Coprocessor entered bootloader.
2022/12/25 07:01:03.410 <Debug>  deliver firmware...
2022/12/25 07:01:03.966 <Debug> CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): System frame
2022/12/25 07:01:03.968 <Debug> CCU2CoprocessorCommandMod::isResponseStatusOk(): System status OK
2022/12/25 07:01:03.969 <Debug> CCU2CommControllerMod::handleIncomingResponse() System response OK
2022/12/25 07:01:04.636 <Debug> CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): System frame
2022/12/25 07:01:04.638 <Debug> CCU2CoprocessorCommandMod::isResponseStatusOk(): System status OK
2022/12/25 07:01:04.639 <Debug> CCU2CommControllerMod::handleIncomingResponse() System response OK
2022/12/25 07:01:05.313 <Debug> CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): System frame
2022/12/25 07:01:05.314 <Debug> CCU2CoprocessorCommandMod::isResponseStatusOk(): System status OK
2022/12/25 07:01:05.315 <Debug> CCU2CommControllerMod::handleIncomingResponse() System response OK
2022/12/25 07:01:05.985 <Debug> CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): System frame
2022/12/25 07:01:05.987 <Debug> CCU2CoprocessorCommandMod::isResponseStatusOk(): System status OK
2022/12/25 07:01:05.989 <Debug> CCU2CommControllerMod::handleIncomingResponse() System response OK
2022/12/25 07:01:06.407 <Debug> CCU2CommControllerMod::sendSystemCommand(): Start Application / Bootloader
2022/12/25 07:01:06.657 <Debug> CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): System frame
2022/12/25 07:01:07.409 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
2022/12/25 07:01:07.411 <Debug> CCU2CommControllerMod::sendSystemCommand(): Start Application / Bootloader
2022/12/25 07:01:07.842 <Debug> CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): System frame
2022/12/25 07:01:07.842 <Debug> CCU2CommControllerMod::handleIncomingResponse() System response failed
2022/12/25 07:01:07.843 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
2022/12/25 07:01:07.843 <Debug> Firmwareupdate not successfull, at frame 5 of 43



Von 1.4.1 auf 2.8.6

2022/12/25 07:11:58.463 <Info> Update necessary, installed: 1.4.1, avaiable 2.8.6

2022/12/25 07:11:58.464  CoprocessorUpdate::startBootloader()
2022/12/25 07:11:58.464 <Debug> () CCU2CommControllerMod::startCoprocessorBootloader(): Trying to start coprocessor bootloader
2022/12/25 07:11:58.465 <Debug> CCU2CommControllerMod::sendSystemCommand(): Start Application / Bootloader
2022/12/25 07:11:58.473 <Debug> CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): System frame
2022/12/25 07:11:58.475 <Debug> CCU2CoprocessorCommandMod::isResponseStatusOk(): System status OK
2022/12/25 07:11:58.475 <Debug> CCU2CommControllerMod::handleIncomingResponse() System response OK
2022/12/25 07:11:59.513 <Debug> CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): System frame
2022/12/25 07:11:59.516 <Debug> () CCU2CommControllerMod::handleIdentifyEvent(): Coprocessor is in bootloader.
2022/12/25 07:11:59.966 <Debug> CoprocessorUpdate::startBootloader():Coprocessor entered bootloader.
2022/12/25 07:11:59.967 <Debug>  deliver firmware...
2022/12/25 07:12:00.122 <Debug> CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): System frame
2022/12/25 07:12:00.122 <Debug> CCU2CommControllerMod::handleIncomingResponse() System response failed
2022/12/25 07:12:00.122 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
2022/12/25 07:12:00.123 <Debug> Firmwareupdate not successfull, at frame 1 of 154
```

### Additional information

Einzige Möglichkeit, um dem Funkmodul wieder Leben einzuhauchen, ist die Verwendung von `flash-hmmoduart` aus https://github.com/dettmering/hmcfgusb

Wenn ich es richtig sehe, wurde seit der 3.55 am `eq3configcmd` nichts verändert
https://github.com/eq-3/occu/tree/master/arm-gnueabihf-gcc8/packages-eQ-3/LinuxBasis/bin

Daher bin ich auch grad etwas ratlos, woher das komische Verhalten kommt.

**Comment by jens-maus** [comment]
Interessant. Passiert das auch mit vorherigen Versionen? Vllt mal einige versionen zurückspringen und schauen ab wann das passiert? Und schätze es ist immer reproduzierbar? Vielleicht hat ja auch @alexreinert eine Idee was hier ggf. schief geht? Er hat da ja recht viel Erfahrung mit. Oder wir verwenden für das Firmware Update/Downgrade in Zukunft das von dir referenzierte Tool statt eq3configcmd? Hattest du das ausreichend genug testet das das mit verschiedensten Firmware Updates/Downgrades auch stabil funktioniert?

**Comment by jp112sdl** [comment]
Hardwareseitig konnte ich es nur mit nem HM-MOD-UART auf einem HB-RF-USB  an der x86 OVA testen.
Da geht es selbst mit der alten 3.53.x nicht.

Firmware-Updates des RPI-RF-MOD funktionieren jedoch am HB RF USB, davon gehe ich zumindest aus. Denn da gab es in letzter Zeit häufiger Updates und es wurde von keinem Fehlschlag berichtet.

Vielleicht meldet sich [tomo_2403](https://homematic-forum.de/forum/memberlist.php?mode=viewprofile&u=52546) die Tage ja noch mal in dem Foren-Thread. Bei ihm steckt das Modul ja direkt auf dem Pi3B+

**Comment by jens-maus** [comment]
Und mit dem `flash-hmmoduart` tool geht das reproduzierbar besser und in beide Richtungen up/downgrade und egal ob dualcopro fw oder nicht?

**Comment by jp112sdl** [comment]
Damit geht es. Hin und her, hoch und runter.

**Comment by jp112sdl** [comment]
Wenn ich den HB-RF-USB erst ranstecke, nachdem  das System hochgefahren ist, geht es auch mit dem `eq3configcmd`.

Starte ich mit angestecktem HB-RF-USB, stoppe dann HMIPserver, multimacd und rfd, geht es nicht.
Auch wenn ich den HB-RF-USB noch mal abziehe und stecke.

**Comment by jens-maus** [comment]
Verstehe. Das kann aber gut sein, denn nachdem HMIPServer, rfd, multimacd & co schon auf das funkmodul losgelassen wurden kann es gut sein das das funkmodul in einem komischen modus ist und deshalb kein update/downgrade geht. Da hilft es dann eigentlich erst ein funkmodul reset via GPIO zu initiieren und dann das fw update/downgrade nochmal zu versuchen... warum das bei dem andere fw tool auch ohne reset geht ist interessant und müsste man sich nochmal anschauen/testen...

**Comment by tomo2403** [comment]
> Vielleicht meldet sich [tomo_2403](https://homematic-forum.de/forum/memberlist.php?mode=viewprofile&u=52546) die Tage ja noch mal in dem Foren-Thread. Bei ihm steckt das Modul ja direkt auf dem Pi3B+

Bei mir funktioniert das Modul auch wieder. Danke @jp112sdl!

**Comment by jp112sdl** [comment]
Ich hab es gerade noch mal versucht und kann das Verhalten jetzt nicht mehr reproduzieren 😮 
In selber Hardware-Konstellation klappt es nun wie eh und je... 

Ticket schließen?

**Comment by jens-maus** [comment]
Oh.. wollte mir das bald mal anschauen und selbst noch einmal testen.. aber wenn es nicht voll reproduzierbar ist, ist das natürlich schwierig. Aber wenn wir eh irgendwann auf hmlangw mit dualcopro fw umstellen dann brauchen wir kein dauerndes fw up/downgrade mehr machen. Oder ist es trotzdem sinnvoll statt eq3configcmd auf diese andere Tool umzustellen?!?

**Comment by jp112sdl** [comment]
> Aber wenn wir eh irgendwann auf hmlangw mit dualcopro fw umstellen dann brauchen wir kein dauerndes fw up/downgrade mehr machen

Genau,wenn es wirklich alles so klappt und ein Downgrade in Zukunft nicht mehr notwendig ist, würde ich an der Updateprozedur nichts verändern.

**Comment by jens-maus** [comment]
Sehe ich auch so. #2132 ist ja nun implementiert und daher sollte es für dieses Problem hier (hoffentlich) kein Bedarf mehr geben.

**Comment by ChR-iSz** [comment]
Mhh, ich habe heute gemert, das bei BidCos ansheinend garnicht mehr läuft auf ein RPI3 mit Raspberrymatic.

Folgendes bekomme ich nach einen Versuch des Firmware Updates angezeigt:

```
root@homematic-ccu2:~# eq3configcmd update-coprocessor -t HM-MOD-UART -p /dev/raw-uart -c -u -l 0 -d /firmware/HM-MOD-UART/
2023/05/22 22:32:11.068 <Debug> firmware filename is: dualcopro_si1002_update_blhm.eq3

2023/05/22 22:32:13.569 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
2023/05/22 22:32:13.569 <Error> CCU2CommControllerMod::performIdentify(): Unable to determine coprocessor state.
2023/05/22 22:32:13.586  getApplicationVersion()
2023/05/22 22:32:13.586  CoprocessorUpdate::startApplication()
2023/05/22 22:32:13.586 <Debug> () CCU2CommControllerMod::startCoprocessorApp(): Trying to start coprocessor application
2023/05/22 22:32:15.587 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
2023/05/22 22:32:15.587 <Error> CCU2CommControllerMod::performIdentify(): Unable to determine coprocessor state.
2023/05/22 22:32:17.587 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
2023/05/22 22:32:17.587 <Error> CCU2CommControllerMod::performIdentify(): Unable to determine coprocessor state.
2023/05/22 22:32:18.588 <Error> CoprocessorUpdate::startApplication():Could not start Coprocessor application.

2023/05/22 22:32:18.589 <Error> Could not start Application, maybe no application on device, do update with dummy Version: 0.0.0

2023/05/22 22:32:18.590 <Info> Update necessary, installed: 0.0.0, avaiable 2.8.6

2023/05/22 22:32:18.590  CoprocessorUpdate::startBootloader()
2023/05/22 22:32:18.591 <Debug> CoprocessorUpdate::startBootloader():Coprocessor entered bootloader.
2023/05/22 22:32:18.592 <Debug>  deliver firmware...
2023/05/22 22:32:19.588 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
2023/05/22 22:32:19.588 <Error> CCU2CommControllerMod::performIdentify(): Unable to determine coprocessor state.
2023/05/22 22:32:22.184 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
2023/05/22 22:32:22.184 <Debug> Firmwareupdate not successfull, at frame 1 of 48
```

Ist das Funkmodul evtl. defekt ?

**Comment by jp112sdl** [comment]
@ChR-iSz Hast du es mit dem `flash-hmmoduart` mal probiert?

**Comment by ChR-iSz** [comment]
Gerade eben, muss aber mit STRG-C abbrechen, da nichts mehr passiert:

```
root@homematic-ccu2:/tmp# /tmp/flash-hmmoduart -U /dev/raw-uart /firmware/HM-MOD-UART/coprocessor_update.eq3 
HM-MOD-UART flasher version 0.103-git

Reading firmware from /firmware/HM-MOD-UART/coprocessor_update.eq3...
Firmware with 43 blocks successfully read.

Initializing HM-MOD-UART...


# INFO: Nach 10 Minuten abgebrochen... mit STRG-C
^C
```

**Comment by jp112sdl** [comment]
Waren vorher alle Dienste, die auf das Funkmodul zugreifen könnten, beendet? - `rfd`,`multimacd`,`HMIPServer`

**Comment by ChR-iSz** [comment]
Wenn ich nichts vergessen habe, eigentlich ja:

```
root@homematic-ccu2:/tmp# /etc/init.d/
S00watchdog            S05avahi-setup.sh      S20seedrng             S47InitRFHardware      S51nut                 S59snmpd               S97NeoServer
S01InitHost            S06InitSystem          S21rngd                S48UpdateRFHardware    S51picod               S60hs485d              S98StartAddons
S01InitZRAMSwap        S07ca-certificates     S30dbus                S49hs485d              S51piusvd              S60multimacd           S98crond
S01USBGadgetMode       S07logging             S35iptables            S49xinetd              S51raspi-fanshim       S60openvpn             S99SetupLEDs
S02InitRTC             S08argononed           S40bluetooth           S50eq3configd          S51strompi2d           S61hmlangw             fuse3
S02sysctl              S08pidesktopd          S40network             S50lighttpd            S51susvd               S61rfd                 rcK
S03InitURandom         S10udev                S45ifplugd             S50ser2net             S55InitAddons          S62HMServer            rcS
S04CheckFactoryReset   S11InitLEDs            S46chrony              S50ssdpd               S58LGWFirmwareUpdate   S70ReGaHss
S05CheckBackupRestore  S13irqbalance          S46tailscaled          S50sshd                S59SetLGWKey           S97CloudMatic

root@homematic-ccu2:/tmp# /etc/init.d/S61rfd stop
Stopping rfd: OK

root@homematic-ccu2:/tmp# /etc/init.d/S62HMServer stop
Stopping HMIPServer: OK

root@homematic-ccu2:/tmp# /tmp/flash-hmmoduart -U /dev/raw-uart /firmware/HM-MOD-UART/coprocessor_update.eq3 
HM-MOD-UART flasher version 0.103-git

Reading firmware from /firmware/HM-MOD-UART/coprocessor_update.eq3...
Firmware with 43 blocks successfully read.

Initializing HM-MOD-UART...

# steht immernoch
```

**Comment by jp112sdl** [comment]
In RaspberryMatic nicht mit den init-Skripten arbeiten!
Der monit-Watchdog startet die Dienste sonst sofort wieder neu.
Also beenden mit
`monit stop rfd`
`monit stop HMIPServer`
`monit stop multimacd`

Der `multimacd` ist eigentlich der wichtigste, da das der Prozess ist, der direkt auf das Funkmodul zugreift.

**Comment by ChR-iSz** [comment]
Ohhhh, den watchdog hab ich auch gerade gesehen....!! Danke für Deinen Tipp!!

```
root@homematic-ccu2:/tmp# /tmp/flash-hmmoduart -U /dev/raw-uart /firmware/HM-MOD-UART/coprocessor_update.eq3 
HM-MOD-UART flasher version 0.103-git

Reading firmware from /firmware/HM-MOD-UART/coprocessor_update.eq3...
Firmware with 43 blocks successfully read.

Initializing HM-MOD-UART...
Waiting for bootloader to settle...
HM-MOD-UART opened.

Flashing 43 blocks: |

Firmware update successfull!
```

**Comment by ChR-iSz** [comment]
Jetza.....

```
...
2023/05/22 23:23:49.417 <Debug> CCU2CoprocessorCommandMod::isResponseStatusOk(): System status OK
2023/05/22 23:23:49.417 <Debug> CCU2CommControllerMod::handleIncomingResponse() System response OK
2023/05/22 23:23:49.961 <Debug> CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): System frame
2023/05/22 23:23:49.962 <Debug> CCU2CoprocessorCommandMod::isResponseStatusOk(): System status OK
2023/05/22 23:23:49.962 <Debug> CCU2CommControllerMod::handleIncomingResponse() System response OK
2023/05/22 23:23:50.757 <Debug> CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): System frame
2023/05/22 23:23:50.758 <Debug> CCU2CoprocessorCommandMod::isResponseStatusOk(): System status OK
2023/05/22 23:23:50.758 <Debug> CCU2CommControllerMod::handleIncomingResponse() System response OK
2023/05/22 23:23:51.070 <Debug> CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): System frame
2023/05/22 23:23:51.071 <Debug> CCU2CoprocessorCommandMod::isResponseStatusOk(): System status OK
2023/05/22 23:23:51.071 <Debug> CCU2CommControllerMod::handleIncomingResponse() System response OK
2023/05/22 23:23:51.072 <Info> Firmwareupdate successfull
```

Mal eine Anektode zu meinen Fehler. Ich hatte am Freitag einen Telekom-Techniker in der Wohnung, der mit extremen Equitment versucht hat meine DSL-Störung zu finden (Interferenzen check). Am Freitag Abend ist mir aufgefallen, dass HMIP nicht mehr läuft.

Ich vermute jetzt einfach mal, dass seine Gerät irgendiw den HM-MOD-UART in den bootmodus gesetzt haben muss. Natürlich nur ne Vermutung, aber der Zeitraum ist einfach zu passend...

**Comment by jp112sdl** [comment]
> Natürlich nur ne Vermutung

Sehr abstrakt, zumal der Modus Bootloader/Applikation nicht persistent ist.


> Am Freitag Abend ist mir aufgefallen, dass HMIP nicht mehr läuft.

Nur die Steuerung der HmIP-Geräte? 

Oder war die Funkmodul-Info auf der "Hilfe"-Seite auch leer?
War noch der Anlern-Button vorhanden?
Falls nur der erste Punkt zutrifft, kannst du deine Theorie gänzlich begraben ;-)

**Comment by ChR-iSz** [comment]
Wiso ist der überhaupt doppelt in der Hilfe Seite drin ?

Address: 0xB744DD (0xB744DD)
und
Address: 0x583ECE (5783246)

Ist das RX, TX ?

Werde mich dann mal die Nacht rumschlagen, wo hier der Fehler ist....

**Comment by jp112sdl** [comment]
> Leider zu früh gefreut:

Warum? In der Hilfe ist doch alles da, korrekt ausgelesen.
Ich vermute, du hast das `detect_radio_module` mit laufenden Diensten ausgeführt.

> Wiso ist der überhaupt doppelt in der Hilfe Seite drin ?


Die BidCos Adresse ist eine andere als die HmIP Adresse

**Comment by ChR-iSz** [comment]
> > Leider zu früh gefreut:
> 
> Warum? In der Hilfe ist doch alles da, korrekt ausgelesen. Ich vermute, du hast das `detect_radio_module` mit laufenden Diensten ausgeführt.
> 

Argh, du hast Recht...

> > Wiso ist der überhaupt doppelt in der Hilfe Seite drin ?
> 
> Die BidCos Adresse ist eine andere als die HmIP Adresse

Ah ja, sehe gerade HmIP und HmRF...

**Comment by ChR-iSz** [comment]
Was ich nur noch nicht verstehe, iat warum in Raspberrymatic bei allen Funkaktoren UNREACHABLE steht, und der Tuerkontakt beim oeffnen erst gwlb und dann rot blinkt. 🤷‍♂️
