### ISSUE TITLE
Proxmox VM - Zweite Netzwerkkarte mit statischer IPv4 persistieren

### ISSUE THREAD

**Issue by samydoesit** [jens-maus/RaspberryMatic#2123]
### Describe the issue you are experiencing

Hallo ich betreibe eine RaspberryMatic Instanz als VM auf einem Proxmox Server.

Ich habe das Installations skript aus der Anleitung benutzt. Funktioniert soweit.

Jetzt habe ich der RaspberryMatic VM eine weitere Netzwerkkarte hinzugefügt.
Wenn ich diesem zusätzlichen Netzwerk Adapter per Console mit `ifconfig` eine statische IP Adresse gebe funktioniert alles wie gewünscht - bis zum nächsten Neustart dann muss ich wieder per ifconfig eine statische IPv4 Adresse setzen, dann passts wieder. 

Die neue Netzwerkkarte bezieht immer eine IPv6 Adresse egal was ich in die `/etc/network/interfaces` schreibe.

Als alternativen workaround habe ich probiert über die `rc.init` beim Starten den `ifconfig` Befehl abzusetzen - klappt nicht. Wo muss in der Proxmox VM das `rc.init` abgelegt werden? Bei mir greift es nicht wenn ich es wie hier beschrieben mache. [https://github.com/jens-maus/RaspberryMatic/wiki/Experten-Features#eigene-aktionen-w%C3%A4hrend-des-bootvorgangs](https://github.com/jens-maus/RaspberryMatic/wiki/Experten-Features#eigene-aktionen-w%C3%A4hrend-des-bootvorgangs)

### Describe the behavior you expected

Kann mir jemand auf die Sprünge helfen das meine VM nicht immer die Settings vergisst? :)

### Steps to reproduce the issue

1. Proxmox VM eine zusätzliche Netzwerkkarte hinzufügen
2. per `ifconfig eth1 <ip> netmask <netmask>` eine Statische IPv4 Adresse hinzufügen
3. VM Neustarten -`ifonfig` Einstellung ist weg

### What is the version this bug report is based on?

3.65.11.20221218

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
keine interessanten logs dazu
```

**Comment by jens-maus** [comment]
> Jetzt habe ich der RaspberryMatic VM eine weitere Netzwerkkarte hinzugefügt.

Und genau das ist eben unter einer RaspberryMatic VM genauso wenig supportet wie unter einem RaspberryMatic System das direkt auf einem RaspberryPi, Tinkerboard, whatsoever läuft. RaspberryMatic benötigt nur ein einzelnes Netzwerkinterface und ich sehe auch keinen wirklich Grund wieso man mehr als ein Interface benötigt. Es handelt sich bei RaspberryMatic um ein simple Homematic Zentrale die mit einer einzelnen IP bzw. einzelnen Zugang ins LAN konnektiert wird und die keine mehreren Interfaces benötigt. Da hilft auch nicht zu versuchen an der `/etc/network/interfaces` irgendetwas zu drehen, denn diese liegt auf der read-only Partition und wird folglich nach einem Firmwareupdate wieder komplett zurückgesetzt sein.
