### ISSUE TITLE
Fehler nach Einspielung vom Debmatic Backup

### ISSUE THREAD

**Issue by tofrie** [jens-maus/RaspberryMatic#2127]
### Describe the issue you are experiencing

Hallo,

ich habe mir eine VM unter Proxmox erstellt. Diese läuft nach der Installation ohne Probleme. Ich kann mich auf der Weboberfläche anmelden, passt… zuvor habe ich mir ein Backup von Debmactic erstellt. Dieses kann ich ganz normal einspielen. Alles startet neu. Die Konsole sieht gut aus und gibt den Link zum einloggen aus. Nur der ein Zugriff auf die Weboberfläche ist mit keinem Browser möglich.

### Describe the behavior you expected

Nach dem einspielen des Backups möchte ich mich auf der Weboberfläche einloggen und diese nutzen können.

### Steps to reproduce the issue

1. VM laut Anleitung in Proxmox installieren 
2. Debmatic Backup per Weboberfläche erstellen
3. Backup in Raspberrymatic einspielen
...

### What is the version this bug report is based on?

3.65.11.20221218

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
…
```

**Comment by jens-maus** [comment]
Bevor man hier sagen kann was das Problem ist (bei RaspberryMatic, beim Backup, beim Nutzer) muss man hier erst einmal mehr Informationen haben als nur "Hier geht was nicht". Tut mir also leid, aber mit der bis jetzt gelieferten Fehlerbeschreibung ist keinerlei Analyse oder sonstiges möglich. Hier müssten erst einmal Logfiles, Browser-Console auszüge usw. geliefert werden.

**Comment by tofrie** [comment]
Sorry... hatte von unterwegs keinen Zugriff. Folgendes wiederholt sich die ganze zeit im Log:

`
Dec 28 20:04:00 ccu3-webui user.info monit[1700]: 'lighttpd' trying to restart
Dec 28 20:04:00 ccu3-webui user.info monit[1700]: 'lighttpd' restart: '/etc/init.d/S50lighttpd restart'
Dec 28 20:04:18 ccu3-webui user.err monit[1700]: 'lighttpd' service restarted 1 times within 1 cycles(s) - exec
Dec 28 20:04:18 ccu3-webui user.err monit[1700]: 'lighttpd' process is not running
Dec 28 20:04:18 ccu3-webui user.info monit[1700]: 'lighttpd' trying to restart
Dec 28 20:04:18 ccu3-webui user.info monit[1700]: 'lighttpd' restart: '/etc/init.d/S50lighttpd restart'
Dec 28 20:04:36 ccu3-webui user.err monit[1700]: 'lighttpd' process is not running
Dec 28 20:04:36 ccu3-webui user.info monit[1700]: 'lighttpd' trying to restart
Dec 28 20:04:36 ccu3-webui user.info monit[1700]: 'lighttpd' restart: '/etc/init.d/S50lighttpd restart'
Dec 28 20:04:54 ccu3-webui user.err monit[1700]: 'lighttpd' service restarted 1 times within 1 cycles(s) - exec
Dec 28 20:04:54 ccu3-webui user.err monit[1700]: 'lighttpd' process is not running
Dec 28 20:04:54 ccu3-webui user.info monit[1700]: 'lighttpd' trying to restart
Dec 28 20:04:54 ccu3-webui user.info monit[1700]: 'lighttpd' restart: '/etc/init.d/S50lighttpd restart'
Dec 28 20:05:12 ccu3-webui user.err monit[1700]: 'lighttpd' process is not running
Dec 28 20:05:12 ccu3-webui user.info monit[1700]: 'lighttpd' trying to restart
Dec 28 20:05:12 ccu3-webui user.info monit[1700]: 'lighttpd' restart: '/etc/init.d/S50lighttpd restart'
Dec 28 20:05:18 ccu3-webui auth.info sshd[2509]: Accepted password for root from 192.168.178.33 port 63427 ssh2
Dec 28 20:05:30 ccu3-webui user.err monit[1700]: 'lighttpd' service restarted 1 times within 1 cycles(s) - exec
Dec 28 20:05:30 ccu3-webui user.err monit[1700]: 'lighttpd' process is not running
Dec 28 20:05:30 ccu3-webui user.info monit[1700]: 'lighttpd' trying to restart
Dec 28 20:05:30 ccu3-webui user.info monit[1700]: 'lighttpd' restart: '/etc/init.d/S50lighttpd restart'
Dec 28 20:05:48 ccu3-webui user.err monit[1700]: 'lighttpd' process is not running
Dec 28 20:05:48 ccu3-webui user.info monit[1700]: 'lighttpd' trying to restart
Dec 28 20:05:48 ccu3-webui user.info monit[1700]: 'lighttpd' restart: '/etc/init.d/S50lighttpd restart'
Dec 28 20:06:06 ccu3-webui user.err monit[1700]: 'lighttpd' service restarted 1 times within 1 cycles(s) - exec
Dec 28 20:06:06 ccu3-webui user.err monit[1700]: 'lighttpd' process is not running
Dec 28 20:06:06 ccu3-webui user.info monit[1700]: 'lighttpd' trying to restart
Dec 28 20:06:06 ccu3-webui user.info monit[1700]: 'lighttpd' restart: '/etc/init.d/S50lighttpd restart'
Dec 28 20:06:24 ccu3-webui user.err monit[1700]: 'lighttpd' process is not running
Dec 28 20:06:24 ccu3-webui user.info monit[1700]: 'lighttpd' trying to restart
Dec 28 20:06:24 ccu3-webui user.info monit[1700]: 'lighttpd' restart: '/etc/init.d/S50lighttpd restart'
Dec 28 20:06:42 ccu3-webui user.err monit[1700]: 'lighttpd' service restarted 1 times within 1 cycles(s) - exec
Dec 28 20:06:42 ccu3-webui user.err monit[1700]: 'lighttpd' process is not running
Dec 28 20:06:42 ccu3-webui user.info monit[1700]: 'lighttpd' trying to restart
Dec 28 20:06:42 ccu3-webui user.info monit[1700]: 'lighttpd' restart: '/etc/init.d/S50lighttpd restart'
`

**Comment by jens-maus** [comment]
Dann solltest du mal einen Blick in die `/var/log/lighttpd-error.log` Datei werfen um den eventl. Grund herauszufinden warum sich lighttpd dauernd neustarten will.

**Comment by tofrie** [comment]
Es möchte einfach nicht...

```
root@ccu3-webui:~# cat /var/log/lighttpd-error.log
cat: can't open '/var/log/lighttpd-error.log': No such file or directory
```
