### ISSUE TITLE
Problem mit CUxD Geräten

### ISSUE THREAD

**Issue by 37wh5r** [jens-maus/RaspberryMatic#213]
Seit dem Einspielen der neuen Version vom 16.12. tauchen neu angelegte CUxD-Geräte nicht mehr in Pocket Control (iOS-Version) auf. Hier wird bei "Aktualisieren" lediglich mein schon länger bestehendes Email-Gerät (91) gelistet, neu angelegte Geräte (z.B. System (28)) werden partout nicht erkannt, egal wie oft ich auf "Aktualisieren" drücke. Gab es in diesem Bereich Änderungen in RaspberryMatic? Die CUxD-Geräte funktionieren einwandfrei im WebUI, nur nach extern scheinen sie nicht sichtbar zu sein.

**Comment by jens-maus** [comment]
Das muss andere Ursachen haben. Bitte mal einen Nustart versuchen.

**Comment by 37wh5r** [comment]
Habe schon sowohl den Raspberry als auch den CUxD-Daemon allein als auch Pocket Control durchgestartet... ioBroker sieht die Devices, Pocket Control nicht. Ich habe vor 3 Tagen dasselbe Szenario erfolgreich getestet, und seitdem habe ich nur RaspberryMatic aktualisiert.

**Comment by 37wh5r** [comment]
Werde trotzdem zur Sicherheit mal einen Downgrade durchführen.

**Comment by jens-maus** [comment]
Bitte mal die Firewall Einstellungen in RaspberryMatic kontrollieren

**Comment by 37wh5r** [comment]
Beide APIs stehen auf "Eingeschränkt" und erlaubt sind "192.168.10.1;192.168.10.0/16". Sollte passen.

**Comment by jens-maus** [comment]
Schalte mal temporär auf vollzugriff. Ubd du nutzt auch 192.168. ?

**Comment by 37wh5r** [comment]
Vollzugriff hat nichts bewirkt, ich nehme an ich muss nicht neustarten? Mein Raspberry liegt auf 192.168.10.225, das Gateway auf 192.168.10.1.

**Comment by jens-maus** [comment]
Dann mal bitte in die logfiles schauen ob da beim Zeitpunkt der Nutzung von pocketcontrol es zu fehlern kommt.

**Comment by 37wh5r** [comment]
Ich habe allerdings *sehr oft* Probleme beim Durchstarten derart, dass der Raspi nicht ins Netzwerk kommt (oder unter einer ganz anderen IP-Adresse, obwohl ich die 192.168.10.225 statisch gesetzt habe). Da hilft dann oft nur Netzwerkkabel ziehen und neu stecken. Irgendwas beim Booten scheint sich regelmäßig zu verklemmen. Ich traue mich schon gar nicht mehr durchzustarten, wenn ich nicht zuhause bin...

**Comment by 37wh5r** [comment]
Im CUxD-Syslog und im Full Syslog passiert nichts. Pocket Control liefert 38 Geräte mit Interface=Alle, und 37 mit Interface=HomeMatic. Und das eine Device Unerschied ist das 91er Mail-Device.

**Comment by 37wh5r** [comment]
Habe gerade nochmal mit poweroff runtergefahren und Stecker gezogen. Beim Neustart hat er diesmal gleich seine IP-Adresse bekommen, das Problem bleibt allerdings bestehen.

**Comment by 37wh5r** [comment]
Nach Downgrade funktioniert es.

**Comment by cyber-age** [comment]
Aktualisierst du in Pocket Control manuell? Also ich meine das hier: 
![9f8040a1-33c8-4f98-b668-8699d992dfc7](https://user-images.githubusercontent.com/32206514/34083448-5284e71c-e371-11e7-94ac-2565a1713bc1.jpeg)

**Comment by 37wh5r** [comment]
Ja, genau. Mit der RaspberryMatic vom 18.11. klappt alles (neue Geräte werden direkt gefunden), mit der neuesten Version von RM klappt es nicht mehr. Vielleicht muss CUxD neu kompiliert werden?

**Comment by cyber-age** [comment]
Ich hab leider keine zeit im moment das selber zu testen, bin noch auf der vorgänger Version.

**Comment by jens-maus** [comment]
@37wh5r Welche PocketControl Version ist das? Hier habe ich mit PocketControl selbst keinerlei Probleme und das manuelle "Aktualisieren" funktioniert problemlos.

**Comment by 37wh5r** [comment]
Pocket Control HM 8.4 auf iOS 10.2. Falls es bereits eine neuere Version unter iOS 11 geben sollte, nützt mir das nichts, da ich auf absehbare Zeit nicht updaten werde. Ich fühle mich mit meinem Jailbreak unter 10.2 sehr wohl. :-)

**Comment by HMside** [comment]
Hast Du überhaupt in den Einstellungen der App unter Geräteauswahloptionen bei Interface CUxD bzw. Alle gesetzt?

**Comment by 37wh5r** [comment]
Ja, wie schon beschrieben. Ich verwende "Alle".

**Comment by 37wh5r** [comment]
D.h. Sie haben ein neues CUxD-Gerät angelegt, im Posteingang bestätigt, in Pocket Control aktualisiert und ein zusätzliches Gerät gesehen?

**Comment by 37wh5r** [comment]
Ich muss meine Aussage, dass ein Downgrade von RaspberryMatic hilft, zurückziehen. Vielmehr ist es so: wenn ich RaspberryMatic frisch installiere und danach cuxd_1.12_ccurm.tar.gz aufspiele, klappt alles. Sobald ich aber mein CCU2-Backup (inkl. CUxD) zurückspiele und danach nochmal cuxd_1.12_ccurm.tar.gz drüber installiere, klappt es nicht mehr. Übrigens kann ich durchaus neue Geräte vom Typ 91 anlegen, oder z.B. EnOcean, und sie werden anstandslos in pocket control angezeigt. Lediglich bei Typ 28 und 40 gibt es die beschriebenen Probleme, und das sind leider genau die Geräte, die ich für den angedachten Einsatz mit Philips Hue brauche.

**Comment by jens-maus** [comment]
Existiert das Problem noch?

**Comment by 37wh5r** [comment]
Ja. Der Autor von pocketControl fühlt sich leider nicht berufen, Problemen mit CUxD nachzugehen.

**Comment by jens-maus** [comment]
Tut mir leid, aber ich kann keine Probleme im Bezug auf PocketControl und CUxD erkennen. Habe das selbst erfolgreich in Betrieb. Daher "worksforme".

**Comment by member1980** [comment]
same here. Does not work. :(
