### ISSUE TITLE
Suche im Script Editor (Strg-F und anschließend F3) nur im sichtbaren Bereich, nicht aber im kompletten Script.

### ISSUE THREAD

**Issue by UCaGk** [jens-maus/RaspberryMatic#2131]
### Describe the issue you are experiencing

Aktuelle Firmware und auch schon in den vorherigen FWs.
Bei groesseren Scripten wird bei der Suche nur im sichtbaren Bereich des Script Editors nach dem gesuchten String gesucht, nicht aber im kompletten Script.

### Describe the behavior you expected

Besser wäre ein Suche im kompletten Script, da es ansonsten zu Verwirrungen führt.

### Steps to reproduce the issue

1. Großes Script im Script Testen Editor öffnen
2. Im nicht sichtbaren Teil das Suchwort verstecken
3. Im sichtbaren Teil, ohne dass das eingetragene Suchwort zu sehen ist Strg-F und Suchwort eingeben, CR, -> Suchwort sollte nicht angezeigt werden
4. Mit F3 weiter Suchen, -> Suchwort sollte nicht angezeigt werden

### What is the version this bug report is based on?

3.65.11.20221218

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Nope
```

**Comment by jens-maus** [comment]
Kann das Problem nicht reproduzieren:

![Jan-04-2023 14-45-43](https://user-images.githubusercontent.com/5887769/210568538-8e1b1954-c77e-4551-a5b8-0c79618e0e4a.gif)
