### ISSUE TITLE
Falsche Anzeige der Umlaute, Eszett und Sonderzeichen in der Diagrammkonfiguration

### ISSUE THREAD

**Issue by GHJester** [jens-maus/RaspberryMatic#2139]
### Describe the issue you are experiencing

Umlaute, Eszett und Sonderzeichen werden in Einstellungen/Diagramme nicht korrekt gespeichert und somit auch nicht unter Status/Diagramme korrekt angezeigt

### Describe the behavior you expected

Umlaute, Eszett und Sonderzeichen sollten korrekt dargestellt werden

### Steps to reproduce the issue

1. Mouse over Einstellungen
2. Diagramme auswählen
3. Neues Diagramm "Temperaturmessung" anlegen
4. Im Feld Name und Beschreibung "Ä ä Ö ö Ü ü ß °" eintragen
5. Speichern
6. Auf "Bearbeiten" des neu erstellten Diagramms klicken
7. "Name", "Beschreibung" und "Angezeigte Einheit" °C werden nicht korrekt dargestellt

![grafik](https://user-images.githubusercontent.com/91785966/210279453-cdde1652-67e0-43ce-b4c0-1aa8edf5ad33.png)

![grafik](https://user-images.githubusercontent.com/91785966/210279520-017510f0-717d-4f3a-9ddd-e585b46519f8.png)

### What is the version this bug report is based on?

3.65.11.20221218

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
nope
```

**Comment by jp112sdl** [comment]
Hat wohl was mit Homeassistant zu tun.

Auf meiner RaspberryPi 3B+ Installation ist alles i.O.

**Comment by GHJester** [comment]
Hmmm... das läuft doch einfach "nur" in einem Docker Container, Da hat Home Assistant normalerweise keinen Einfluss drauf? Alles andere sieht korrekt aus, nur die Diagramme zicken rum.

Ich habe mir jetzt mal die Konfigurationsdatei angeschaut. Dort steht das drin:
```
Description=Temperatur K\u00FCche
Type=1
TemplateId=1
YScalingMaxValue=0.0
Id=3
DisplayedUnit=\u00B0C
Active=true
YScalingMinValue=0.0
Name=Temperatur K\u00FCche
```
Ist das denn korrekt?

**Comment by jp112sdl** [comment]
Ich hab es gerade noch einmal versucht, dieses Mal mit der 3.65.11.20221218 OVA Version:
```
Description=\u00C4 \u00E4 \u00D6 \u00F6 \u00DC \u00FC \u00DF \u00B0
Type=1
TemplateId=1
YScalingMaxValue=0.0
Id=1
DisplayedUnit=\u00C4 \u00E4 \u00D6 \u00F6 \u00DC \u00FC \u00DF \u00B0C
Active=true
YScalingMinValue=0.0
Name=\u00C4 \u00E4 \u00D6 \u00F6 \u00DC \u00FC \u00DF \u00B0
DataSources=JPRCDISTH1\:5_5,JPRCDISTH1,TEMPERATURE,0,0
YScalingModeMin=false
DefaultPeriod=1
Operable=true
Visible=true
DefaultConsolidationFunction=3
YScalingModeMax=false
```

![grafik](https://user-images.githubusercontent.com/18190139/210308037-b6bc1b37-a560-4820-ad48-6c6b21c2c984.png)

**Comment by Baxxy13** [comment]
Wie wird denn hier die WebUI aufgerufen?
Über Ingress (Seitenleiste in HA) oder über "extern" mit angehängtem Port (z.B. 8088)?

Tritt das Problem bei beiden Varianten auf?

**Comment by GHJester** [comment]
Ich werd' verrückt. Tatsächlich scheint das ein Problem der Integration in den Home Assistant zu sein. Wenn ich die UI direkt aufrufe wird alles korrekt dargestellt. Ich hatte bis jetzt den Port einfach noch nicht aktiviert. Somit konnte ich die UI auch noch nicht direkt aufrufen. Somit hat sich das erledigt.
Aber komisch ist das schon, dass alles andere korrekt dargestellt wird, nur in den Diagrammen nicht

**Comment by Baxxy13** [comment]
Der Weg über Ingress ist natürlich komfortabler wenn man schon auf der Homeassistant UI ist. Der hat aber in der Vergangenheit immer mal wieder an diversen Stellen Probleme bereitet. 
Daher empfehle ich nur noch den "Direktaufruf".

Das eigentliche Problem müsste sich dann Jens mal angucken, daher hätte ich das Ticket noch nicht zu gemacht.

**Comment by GHJester** [comment]
OK, dann öffne ich den noch mal. Jens kann ja dann schließen wenn er sich das nicht mehr anschauen möchte.

**Comment by jens-maus** [comment]
Um dieses Problem mit der Benennung der Diagramme über den Ingresszugang zur WebUI näher zu analysieren bräuchte ich aber am besten mal einen konkreten testcase. Dazu wäre es gut hier ggf ein Backup der Diagrammdaten oder ein komplettes sbk backup zur hand zu haben das nach dem restore auf einer frischen RaspberryMatic das Problem unmittelbar zeigt.

**Comment by GHJester** [comment]
Das Backup als sbk habe ich dir per E-Mail geschickt. Ich habe eine virtuellen Umgebung aufgesetzt und mein reguläres Backup eingespielt. Ich habe alles bereinigt was du nicht benötigst. Leider lassen sich aus irgendeinem Grund die Geräte nicht löschen (Löschen/in den Werkszustand/Löschen/Aus Homematic Zentrale löschen), sonst hätte ich die Geräte bis auf eins auch noch entfernt.
Jedenfalls benötigst du Home Assistant auch noch, denn nur darüber kannst du das Problem beobachten.

![grafik](https://user-images.githubusercontent.com/91785966/210388250-bf595316-3f96-454e-aa2e-1c03fab3d098.png)

In der Diagrammansicht besteht das Problem auch:

![grafik](https://user-images.githubusercontent.com/91785966/210388402-b608c701-e6f5-4383-95d0-fad738e89713.png)

Ich habe überhaupt beobachtet, dass RaspberryMatic über den Home Assistant **sehr** träge reagiert.

**Comment by jens-maus** [comment]
Ich konnte/kann das problem jetzt hier mit der entsprechenden `.dic` Datei aus `/etc/config/measurement` reproduzieren. Das selbe bzw. etwas ähnliches passiert übrigens auch bei den Gruppen wenn man diese innerhalb der Ingress umgeleiteten WebUI editiert, anpasst. Siehe:

![Bildschirm­foto 2023-01-04 um 11 52 07](https://user-images.githubusercontent.com/5887769/210539698-9bcfae46-419a-4f2e-bb3e-742797f22c19.png)

Wenn man allerdings die RaspberryMatic WebUI direkt via Port 8080 (wenn man den so in der Add-on konfig eingestellt hat) editiert/anschaut, passt alles, wohl auch bei den Diagrammen.

**Comment by jens-maus** [comment]
So, ich denke ich hab nun eine möglichkeit gefunden das die WebUI seiten die der HMIPServer ausliefert nicht falsch umkodiert werden. Problem scheint zu sein, das der HMIPServer wohl immer `utf-8` kodierte Seiten zurückliefert, dies aber nicht explizit beim ausliefern `charset=utf-8` im content-type so definiert. Das führte wohl dazu, das dann die Charset Konvertierungsroutinen in `ha-proxy.js` fälschlicherweise das ganze in `latin1` konvertiert hatte was genau zu den oben gezeigten Problemen geführt hat. Das sollte nun korrigiert sein und mit der nächsten nightly snapshot bzw. dem nächsten Release sollten die WebUI Seiten von HMIPServer auch über den Ingress Proxy korrekt funktionieren. Bitte entsprechend durchtesten natürlich!

**Comment by jp112sdl** [comment]
**Ohne** https://github.com/jens-maus/RaspberryMatic/commit/e4418b685b87070194c902f9a31f73cc3553a0fe , dafür aber **mit** dem gestern ausgelieferten HMIPServer im OCCU https://github.com/eq-3/occu/commit/8bd52d59758e284e554d45e29b04f8bdcf0dd5e1 ging es auch nicht?

**Comment by jens-maus** [comment]
> **Ohne** [e4418b6](https://github.com/jens-maus/RaspberryMatic/commit/e4418b685b87070194c902f9a31f73cc3553a0fe) , dafür aber **mit** dem gestern ausgelieferten HMIPServer im OCCU [eq-3/occu@8bd52d5](https://github.com/eq-3/occu/commit/8bd52d59758e284e554d45e29b04f8bdcf0dd5e1) ging es auch nicht?

Nein, definitiv nicht. Das ist in der Tat ein shortcoming vom HMIPServer das er seine Seiten zwar mit `content-type: text/html` ausliefert, es aber unterlässt da das genutzt charset via `charset=utf-8` parameter explizit zu benennen...
