### ISSUE TITLE
unknown interface (HmIP-RF)

### ISSUE THREAD

**Issue by marclindemann** [jens-maus/RaspberryMatic#214]
Beim anlernen von IP passiert nichts. I
homematic.cgi gibt folgendes zurück:
`{
  "version": "1.1",
  "result": null,
  "error": {
    "name": "JSONRPCError",
    "code": 500,
    "message": "unknown interface (HmIP-RF)"
  }
}
`
Ist eine frische Installation mit eingespieltem Backup

**Comment by jens-maus** [comment]
Welche (Funk)-Hardware wird verwendet?

**Comment by marclindemann** [comment]
raspberry 2 mit einem HomeMatic RF-LAN Gateway.
Ich glaube das ist auch das Problem wie ich grad bei ELV gesehen habe, das kann kein Homematic IP, richtig?

**Comment by jens-maus** [comment]
Vollkommen richtig!
