### ISSUE TITLE
Homematic(IP) Local integration in Home assi schlägt fehl

### ISSUE THREAD

**Issue by niceguy0815** [jens-maus/RaspberryMatic#2140]
### Describe the issue you are experiencing

Beim Versuch RaspberryMatic CCU in Home Assi zu inregrieren kommt der Fehler "Verbindung fehlgeschlagen"
![grafik](https://user-images.githubusercontent.com/43955022/210288853-e3f2aeaa-1d08-4a2c-992e-2e4116377fec.png)

Im Log sagt er das die " Service Unavailable" sind
![grafik](https://user-images.githubusercontent.com/43955022/210288177-08a4f7c4-f47f-489b-997b-3bcc3b92be34.png)

### Describe the behavior you expected

Er müsste die Integration eigentlich verbinden da ich genau der Anleitung gefolgt bin.

### Steps to reproduce the issue

Ich habe ien neues Home Assistent OS in einer VM auf meinem esxi Server installiert.
Dort habe ich dann RaspberryMatic CCU als Add-one installiert wie in der original Anleitung beschrieben.
![grafik](https://user-images.githubusercontent.com/43955022/210286722-ffee7b4f-40ae-4e01-bcfc-dc9a5097a235.png)
Dann habe ich im RaspberryMatic mein HM-LGW-O-TW-W-EU-2 verbunden und ein Thermostat zu testen gekoppelt
![grafik](https://user-images.githubusercontent.com/43955022/210286847-6d7cb4f6-8087-42e5-8455-49f9b8063a7d.png)
Das hat soweit alles geklappt.
Nun habe ich, wie in der git Anleitung den HACS installiert und die Integration "Homematic(IP) Local"  v1.25.1 heruntergeladen und Home Assi neu gestartet.
![grafik](https://user-images.githubusercontent.com/43955022/210287155-ae60632f-c0d5-4460-a6f0-e9dd05d9ca59.png)
Nun wollte ich die eigentliche Integration starten
![grafik](https://user-images.githubusercontent.com/43955022/210287255-b3473dfd-734c-4b78-a5a4-e8f4001017e9.png)
Es läd...
![grafik](https://user-images.githubusercontent.com/43955022/210287288-11bd808d-d52b-4325-8dc2-3053047f8e90.png)
Ich gebe alle Daten wie in der Anleitung, auf "https://github.com/jens-maus/RaspberryMatic/wiki/HomeAssistant-Integration" beschrieben ein:
![grafik](https://user-images.githubusercontent.com/43955022/210287361-14ed9ae9-6e35-4306-aff2-207261a2d7c6.png)
drücke Absenden...
Setze im nächsten Bild alle Haken und drücke Absenden:
![grafik](https://user-images.githubusercontent.com/43955022/210287447-b616d44c-c716-4757-ade1-61366fdb07d6.png)
Jetzt lande ich wieder auf der ersten Eingabemaske und es erscheint "Verbindung fehlgeschlagen".
![grafik](https://user-images.githubusercontent.com/43955022/210288864-0a04f2ac-baea-47df-85d1-e7252d2b2dc8.png)

Ich habe auch dei Firewall Einstellungen geprüft und es müsste eigentlich alles offen und erreicbar sein:
![grafik](https://user-images.githubusercontent.com/43955022/210287614-90bbd7a9-2aa7-4a9a-b495-94fe45e8fa29.png)
Die Zugangsdate wurden auch alle wie in der Anleitung beschieben eingegeben.
Im Log sagt er das er den Host / die Ports nicht erreichen kann?

### What is the version this bug report is based on?

3.65.11.20221218

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

HM-CFG-LAN

### Anything in the logs that might be useful for us?

```txt
2023-01-03 01:29:08.070 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-03 01:29:08.072 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration homematicip_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-03 01:30:32.589 ERROR (MainThread) [frontend.js.latest.202212131] :0:0 ResizeObserver loop completed with undelivered notifications.
2023-01-03 01:30:36.451 ERROR (MainThread) [frontend.js.latest.202212131] :0:0 ResizeObserver loop completed with undelivered notifications.
2023-01-03 01:38:33.042 WARNING (MainThread) [custom_components.homematicip_local.config_flow] Unable to connect (<ProtocolError for de838cd8-raspberrymatic:2010/RPC2: 503 Service Unavailable>,).
2023-01-03 01:54:33.435 WARNING (MainThread) [custom_components.homematicip_local.config_flow] Unable to connect (<ProtocolError for de838cd8-raspberrymatic:2000/RPC2: 503 Service Unavailable>,).
```

### Additional information

Ich habe dann auch nochmal selbst eine Komplette Debian VM mit Home Assi und Supervisor installiert und dort auch nochmal probiert aber bekomme genau den selben Fehler

**Comment by niceguy0815** [comment]
Hi und ganke für die Antwort.
das hab ich leider auch schon ausprobiert aber auch heir kommt der Selbe Fehler:
![grafik](https://user-images.githubusercontent.com/43955022/210333760-8541d93e-d328-41be-b7a3-9536bea4fae1.png)
Das Lan Gatway " HM-LGW-O-TW-W-EU-2" habe ich als "HomeMatic RF-LAN Gateway" an die  RaspberryMatic CCU gekoppelt.
Und wird da auch als berbunden gezeigt und ich konnte Geräte verbinden und steuern

**Comment by jens-maus** [comment]
Auch ich sehe hier keinen Zusammenhang/Grund das das ein Problem in RM selbst sein sollte. Das Problem gehört in der Tat im Projekt der Homematic(IP) Integration reportet!
