### ISSUE TITLE
Neuinstallation bietet zum Update eines neuen DRAP ältere Version an 

### ISSUE THREAD

**Issue by BeOCeKa** [jens-maus/RaspberryMatic#2145]
### Describe the issue you are experiencing

Ich habe eine Neuinstallation von RaspberryMatic (3.65.11.20221218) auf Proxmox. Heute habe ich meine neuen HmIPW Komponenten in Betrieb genommen.

Bei Geräte Firmware Übersicht bietet RaspberryMatic ein Update für DRAP auf Version 2.4.14 an, obwohl auf dem DRAP bereits 2.4.28 ab Werk läuft.

![Screenshot_20230106_191059_Chrome](https://user-images.githubusercontent.com/122117910/211074975-a9dfe167-7a95-4d7f-88d0-bc1cce4b6585.jpg)

### Describe the behavior you expected

Es sollte kein Update Button erscheinen.

### Steps to reproduce the issue

Komplett neues System mit neuen Komponenten
Einlernen
Geräte Firmware Übersicht 

### What is the version this bug report is based on?

3.65.11.20221218

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Screenshot
```

**Comment by jens-maus** [comment]
> Bei Geräte Firmware Übersicht bietet RaspberryMatic ein Update für DRAP auf Version 2.4.14 an, obwohl auf dem DRAP bereits 2.4.28 ab Werk läuft.

Dies muss daran liegen das du die 2.4.14 Firmware unter `Systemsteuerung -> Geräte-firmware Übersicht -> Geräte-Firmware` selbst hochgeladen hast oder du eben die 2.4.28 dort nicht eingespielt hast und damit quasi die 2.4.14 als die Aktuelle ist. Die 2.4.28 ist definitiv die aktuelle und hier kann ich dein vorgetragenes verhalten auch nicht reproduzieren bzw. nachvollziehen, denn bei mir ist die aktuelle die 2.4.28.

**Comment by BeOCeKa** [comment]
Da muss ich enttäuschen.Ich habe per OVA installiert und bin den Wizard zu Beginn durchgegangen.Gestern Nachmittag habe ich das erste Mal in meinem Leben Homematic Geräte in eine RaspberryMatic Instanz angelernt. Ich klicke mich derzeit durch alle Bereiche, benenne Räume und dergleichen. Und ein Bereich ist eben dieser.In meinen Augen kein Anwenderfehler.
-------- Ursprüngliche Nachricht --------Von: Jens Maus ***@***.***> Datum: 06.01.23  23:14  (GMT+01:00) An: jens-maus/RaspberryMatic ***@***.***> Cc: BeOCeKa ***@***.***>, Author ***@***.***> Betreff: Re: [jens-maus/RaspberryMatic] Neuinstallation bietet zum Update eines neuen DRAP ältere Version an  (Issue #2145) 



Bei Geräte Firmware Übersicht bietet RaspberryMatic ein Update für DRAP auf Version 2.4.14 an, obwohl auf dem DRAP bereits 2.4.28 ab Werk läuft.



Dies muss daran liegen das du die 2.4.14 Firmware unter Systemsteuerung -> Geräte-firmware Übersicht -> Geräte-Firmware selbst hochgeladen hast oder du eben die 2.4.28 dort nicht eingespielt hast und damit quasi die 2.4.14 als die Aktuelle ist. Die 2.4.28 ist definitiv die aktuelle und hier kann ich dein vorgetragenes verhalten auch nicht reproduzieren bzw. nachvollziehen, denn bei mir ist die aktuelle die 2.4.28.

**Comment by BeOCeKa** [comment]
Ich weiß jetzt, wie man Geräte Firmware Manuell hochlädt. Beim FALMOT-C12 wurde mir eine neue Version vorgeschlagen über die Startseite.
Aber wie kommt man an eine bestimmte Version einer Geräte Firmware? 
Schade, dass hier direkt geschlossen wurde. Den Einstieg hätte ich mir anders erhofft.

**Comment by jens-maus** [comment]
Das hier ist kein Diskussionsforum, sondern ein Bug/IssueTracker und nur für das Tracken/Bearbeiten bzw organisieren dee bugfixes, etc. gedacht. Support/Problemfindubgen gehören in Diskussionsforen wie hier unter Discussions or in homematic-forum.de.

Trotzdem mache ich hier nochmal auf damit ich mir später nochmal anschauen kann ob die DRaP Firmware die mit OCCU gleich mitkommt dem aktuellen (2.4.24) entspricht und ob wir die gleich in RM aktualisiert ausliefern können.

**Comment by BeOCeKa** [comment]
Ich weiß, dass das kein Diskussionsforum ist. 
Nun habe ich die Update-Datei RaspberryMatic-3.65.11.20221218-ova frisch heruntergeladen und entpackt. In diesem Image liegt die Version 2.4.14, was meine Vermutung bekräftigt.

![image](https://user-images.githubusercontent.com/122117910/211141961-5bb06f64-843f-4417-b3eb-f3a8c1000504.png)

**Comment by BeOCeKa** [comment]
Danke für die Weiterverarbeitung.
Vielleicht wäre es auch gut, wenn die verfügbare Version kleiner als die auf dem Gerät installierte ist, dass der Button "Downgrade" statt "Update" heißen würde. Das wäre aber wohl eher Kosmetik.

**Comment by jens-maus** [comment]
Der Punkt das hier die Version 2.4.14 für ein vermeintliches Update angeboten wird rührt daher, dass in OCCU (ein upstream Projekt von RaspberryMatic) und folglich auch in der aktuellen offiziellen CCU3 Firmware von eQ3 immer noch die alten DRAP Firmwaredaten unter `/etc/firmware/access-controller` standardmäßig ausgeliefert werden und das dort mal angepasst/aktualisiert gehört. Glücklicherweise können wir im Rahmen des RaspberryMatic Projektes diese Firmware selbst in unserem Fork von OCCU aktualisieren (was mit https://github.com/jens-maus/occu/commit/437e0ca4cc16deef6e42c67222ec54cf4e50ae5a und https://github.com/jens-maus/RaspberryMatic/commit/86d4e22d47aface5a42f95ea14f7e6860cf6ab50 erledigt wurde). 

Konkret heisst das nun, einfach auf die nächsten nightly snapshot wechseln oder auf die nächsten offiziellen Release von RaspberryMatic warten. Dann sollte diese Benachrichtigung eines vorgeschlagenen Downgrades verschwinden. Oder das Downgrade durchführen und warten bis RaspberryMatic wieder ein Upgrade vorschlägt weil die es dann via web-request bei eQ3 nach der aktuellsten Version nachfragt und dann man dort die 2.4.28 herunterladen und manuell hochladen kann.
