### ISSUE TITLE
Error: Error fetching proxied request: aborted

### ISSUE THREAD

**Issue by SBBS1981992** [jens-maus/RaspberryMatic#2146]
### Describe the issue you are experiencing

I haven't been able to open the RaspberryMatic overlay on my Homeassistant for a while. When you click on it in the sidebar, an Index.html is downloaded that contains the following text: Error fetching proxied request: aborted
It only works if the system has just rebooted.

### Describe the behavior you expected

Es müsste sich das Overlay Öffnen.

### Steps to reproduce the issue

Think it's clear

### What is the version this bug report is based on?

 3.65.11.20221218 (

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Mounting /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying host system: oci, OK
Initializing RTC Clock: grep: /proc/device-tree/model: No such file or directory
grep: /proc/device-tree/model: No such file or directory
rx8130, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.2, OK
Identifying Homematic RF-Hardware: ....HmRF: RPI-RF-MOD/GPIO@fe201000.serial, HmIP: RPI-RF-MOD/GPIO@fe201000.serial, OK
Updating Homematic RF-Hardware: RPI-RF-MOD: 4.4.22, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: .......OK
Starting rfd: ..OK
Starting HMIPServer: .....................OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.65.11.20221218 (raspmatic_oci_arm64)
```

**Comment by jens-maus** [comment]
Sorry, but this is not reproducible here. Please try with a fresh testinstallation to reproduce this yourself. Here everything works as expected.
