### ISSUE TITLE
WebUI Freezes after a while

### ISSUE THREAD

**Issue by regnets** [jens-maus/RaspberryMatic#215]
After 5 minutes of on-time the webui isn't accessible anymore.

Already switched sd card, power brick and lan cable.

The error message looks as you can see in the attached screenshot.
![image](https://user-images.githubusercontent.com/1339599/34111682-bb393c06-e40a-11e7-88db-ed11a1718772.png)

I already had a look at the log files in /var/log while the webui wasn't responsible, however i didn't see anything suspicous. 

I switched the SD-Card and imported a backup, this didn't change anything.

So far i got no clue what's happening.

I will greatly provide any log files, if needed.

After looking at the chrome developer tools, a few request are just staying at pending, maybe that will help?
![image](https://user-images.githubusercontent.com/1339599/34111880-4519d476-e40b-11e7-903b-0d4eebb6eb18.png)

**Comment by regnets** [comment]
So ok, after a lot of tinkering arround with backups etc. i suspect that my uart dongle got some kind of issue, it will work for arround 5 to 10 minutes after powering on and than will do nothing. 

I am not sure what to do now. I ordered a new modul which. Hopefully this will arrive before christmas.

**Comment by jens-maus** [comment]
Please check your DutyCycle.

**Comment by regnets** [comment]
Tried that already, can't get any of these scripts to work. 

I tried the homematic script with the cux deamon and the tcl script on the command line.

It is really curious, that the uart module will work for 5 to 10 minutes after powering on and the the whole homematic webui will lock up.
