### ISSUE TITLE
Heizgruppe kann nicht erzeugt werden

### ISSUE THREAD

**Issue by duffy6** [jens-maus/RaspberryMatic#2152]
### Describe the issue you are experiencing

Heizgruppe kann ich nicht angelegt werden (HmIP-eTRV-2).
Andre Thermostate konnte ich nicht testen.
![gruppe](https://user-images.githubusercontent.com/30000750/211850794-8f1be55c-e6e2-4464-b645-e6681deb8eea.PNG)

### Describe the behavior you expected

Heizgruppe sollte angelegt werden

### Steps to reproduce the issue

1. Heizgruppe anlegen

### What is the version this bug report is based on?

3.65.11.20221218

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
habe dazu nix gefunden (bin aber auch kein Fachmann)
```

**Comment by jens-maus** [comment]
Duplicate of #2105
