### ISSUE TITLE
Device Firmware Update information is missing / cannot be fetched

### ISSUE THREAD

**Issue by liebehentze** [jens-maus/RaspberryMatic#2153]
### Describe the issue you are experiencing

"Device Firmware Update" is missing / can't be fetched on 'Home' below firmware version.

### Describe the behavior you expected

Device Firmware Updates are listed if existing.

### Steps to reproduce the issue

1. Have Devices with non up to date firmware
2. Login 
3. No Updates listed

### What is the version this bug report is based on?

3.65.11.20221218

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
see additional information
```

### Additional information

It seems that the infos requested is trying to get from (seen via chrome developer tools):

https://ccu3-update.homematic.com:8443/firmware/api/firmware/search/DEVICE?product=HM-CCU3&version=3.65.11.20221218&ts=1673452251339

-> this leads to ERR_NETWORK_ACCESS_DENIED

using port 443 solves the problem.

**Comment by jens-maus** [comment]
Well, this isn‘t a bug really. The URL for checking for device firmware updates is supplied by the vendor (eQ3) and there is nothing the RaspberryMatic project can change that. And eQ3 has somehow decided to use port 8443 for their service.

The reason why your browser can‘t access this resource mist be related to some internal firewall blocking in the environment of the system from which you access the WebUI. Thus, make sure to unblock port 8443 if you have firewall rules preventing this.

Nevertheless, this is definitely no bug in RaspberryMatic itself, thus doesn‘t belong here.

**Comment by liebehentze** [comment]
Thanks a lot for this quick feedback, I will have a look.
