### ISSUE TITLE
Geräte lassen sich nicht zu erstellten Gruppen hinzufügen

### ISSUE THREAD

**Issue by GameWatchProjects** [jens-maus/RaspberryMatic#2156]
### Describe the issue you are experiencing

Unter der Version 3.65.11.20221005 hatte ich Heizungsgruppen erstellt, Geräte hinzugefügt und die Verknüpfungen wurden automatisch erstellt. Im Dezember hatte ich dann ein Update auf die Version 3.65.11.20221218 getätigt. In den letzten Tagen wurden dann mal endlich weitere HmIP Geräte geliefert und und lernte diese wie gewohnt in der Zentrale (CCU3) an. Als ich diese Geräte dann in die jeweiligen Gruppen hinzufügen wollte, geschah bis auf den Hinweis, das die Verknüpfungen erstellt werden absolut nichts. Auch 2 Stunden später veränderte sich an diesem Status nichts. Anschließend habe ich alle Geräte aus den Gruppen entfernt und die Gruppen gelöscht. Eine Gruppe neu erstellt, Geräte hinzugefügt und es blieb an der gleichen Stelle hängen, ohne das etwas geschah. Die Gruppe wurde zwar angelegt, aber keine Verknüpfungen erstellt. Da ich keine Erklärung dafür fand, das in der aktuellen Version es nicht funktionierte, aber in der vorherigen Version, hatte ich ein downgrade zur Version 3.65.11.20221005 vorgenohmmen. Gruppen erstellt, und auch das hinzufügen der Geräte zu den gewünschten Gruppen funktionierte erstaunlicherweise auf Anhieb und ohne Probleme. Genutzt wird eine EQ3 CCU3 ...

### Describe the behavior you expected

n/a

### Steps to reproduce the issue

n/a

### What is the version this bug report is based on?

3.65.11.20221218

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
n/a
```

**Comment by jens-maus** [comment]
Duplicate of #2105
