### ISSUE TITLE
Frontendfehler bei VIR-LG-RGBW-DIM

### ISSUE THREAD

**Issue by etofi** [jens-maus/RaspberryMatic#2157]
### Describe the issue you are experiencing

Das scheint nur ein Problem im Frontend zu sein da ich die Geräte über TinyMatic noch einwandfrei steuern kann.

- Weder Farbwert noch Farbtemperatur werden korrekt angezeigt
- Farbwert und die Farbtemperatur können nicht mehr einstellen.
- Nach dem ersten Gerät des Typs VIR-LG-RGBW-DIM wird der Dimmerschieber nicht mehr angezeigt.
- Nach dem ersten Gerät des Typs VIR-LG-RGBW-DIM werden keine Gerätesymbole mehr angezeigt.

![grafik](https://user-images.githubusercontent.com/19774831/212009674-df100192-ad90-4702-a357-68255a24b9d0.png)

- Beim Öffnen wird auch das PopUp Fenster nicht mehr richtig geladen

![grafik](https://user-images.githubusercontent.com/19774831/212010103-f4faadc5-77e1-4694-9f0b-231031141ad4.png)

### Describe the behavior you expected

So sollte das eigentlich aussehen

![grafik](https://user-images.githubusercontent.com/19774831/212012688-62c2ada6-0c0f-45fd-a509-fc9f6c1b022f.png)

### Steps to reproduce the issue

Entweder im Frontend über

- Status => Geräte oder
- Status => Räume (in den die Geräte sind)

gehen.

### What is the version this bug report is based on?

3.65.11.20221218

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Fehlermeldung in der Web Konsole:

Uncaught ReferenceError: preferredFormat is not defined
    initialize http://192.168.178.253/webui/js/extern/spectrum.js:429
    spectrum http://192.168.178.253/webui/js/extern/spectrum.js:1049
    spectrum http://192.168.178.253/webui/js/extern/spectrum.js:1289
    jQuery 2
        each
        each
    spectrum http://192.168.178.253/webui/js/extern/spectrum.js:1287
    <anonymous> http://192.168.178.253/webui/js/extern/prototype.js line 645 > eval:2
    evalScripts http://192.168.178.253/webui/js/extern/prototype.js:645
    wrapNative http://192.168.178.253/webui/js/extern/prototype.js:1275
    evalScripts http://192.168.178.253/webui/js/extern/prototype.js:645
    delay http://192.168.178.253/webui/js/extern/prototype.js:439
    setTimeout handler*delay http://192.168.178.253/webui/js/extern/prototype.js:438
    defer http://192.168.178.253/webui/js/extern/prototype.js:445
    update http://192.168.178.253/webui/js/extern/prototype.js:2295
    _methodized http://192.168.178.253/webui/js/extern/prototype.js:461
    updateContent http://192.168.178.253/webui/js/extern/prototype.js:2000
    onComplete http://192.168.178.253/webui/js/extern/prototype.js:1979
    respondToReadyState http://192.168.178.253/webui/js/extern/prototype.js:1839
    onStateChange http://192.168.178.253/webui/js/extern/prototype.js:1765
    request http://192.168.178.253/webui/js/extern/prototype.js:1746
    initialize http://192.168.178.253/webui/js/extern/prototype.js:1709
    wrap http://192.168.178.253/webui/js/extern/prototype.js:452
    value http://192.168.178.253/webui/js/extern/prototype.js:125
    initialize http://192.168.178.253/webui/js/extern/prototype.js:1983
    wrap http://192.168.178.253/webui/js/extern/prototype.js:452
    klass http://192.168.178.253/webui/js/extern/prototype.js:85
    loadChannels http://192.168.178.253/webui/js/extern/prototype.js line 645 > eval:29
    onclick http://192.168.178.253/pages/index.htm?sid=@fKDkLtoyPX@:1
spectrum.js:429:17
```

**Comment by jens-maus** [comment]
Duplicate of #2102
