### ISSUE TITLE
Ethernet Gadget mode on RPi Zero

### ISSUE THREAD

**Issue by Jojo-A** [jens-maus/RaspberryMatic#216]
Hi,

the ethernet gadget mode seems to be not working properly.

Usecase:
Raspberrymatic is running on a Raspberry Pi Zero, while main home autoamtion system is running on another system (host).
To simplify the setup, I'd like to connect the RPiZ to the host via USB to provide both power **and** share the network/internet connection of the host to the RPiZ. In this scenario, the RpiZ needs to be detected as a USB network device by the host.

I modified the config.txt file to load the corresponding device tree overlay, as well as the boot command to load the corresponding driver modules according to various tutorials.

After these changes, the RPi _should_ show up as a USB ethernet device, when plugged in into another host system. But it doesn't.

Problem: I can not debug this by myself, because the RPiZ has only one USB port, which needs to be used exclusively for ethernet (via USB). So I can not connect any input devices without cutting the (planned) network connection. But without network connection (via USB), I can not trace down the cause of the problem :( .

Greetings

**Comment by jens-maus** [comment]
As you correctly identified, Ethernet Gadget mode (see https://learn.adafruit.com/turning-your-raspberry-pi-zero-into-a-usb-gadget/ethernet-gadget) ist currently not supported by RaspberryMatic. In fact, you ware the first one requesting it. Thus, I will flag this as a feature request but give it somewhat low priority, I am afraid.

**Comment by Jojo-A** [comment]
Hi and thanks a ton for that quick reply!
Actually I am happy to hear, that it is really not supported. Otherwise I would have had to rearch the fault on my side ;) .

I fully understand, that this feature is flagged as "low priority", because nobody else requested it before. Nevertheless I think it will by a very valuable feature, as it opens up a broad range of possible system setups. I could imagine, that there are other people but me out there, who use the RPi (Zero) exclusively for Raspberrymatic, because the RF module is only supported on that platform, while having their main home automation system on another platform. In this case, the wiring setup would be simplified.

In case of the RPi Zero, it would be even more valuable, because there were people (in the past), who had problems with the initial WiFi network setup, because they had no SSH access because the network credentials were not configured, yet. No network, no SSH, no SSH, no way to edit network...
So another enhencement would be, if there would be an option to choose to use the USB normally (for USB-WiFi for example) or to use it as a USB ethernet device.

Long story made short: I understand and accept, that this feature is low prioritized. But maybe it is worth to have a look at how complicated it is to implement it. I have no idea about that. So if you say "no", then it is a "no" :) .

Thank you anyway!

**Comment by Jojo-A** [comment]
Just in case, that you decide not to implement the gadget mode:
would it work the ather way around OOTB? If there is another device (like another SBC with g_ether module and USB-OTG port), which provides Ethernet-over-USB as RNDIS-interface, will this be usable by Raspberrymatic as network interface?

Greetings

**Comment by fhirschmann** [comment]
@Jojo-A, have you had any success with this by now? I'm also quite interested in this feature.

**Comment by fhirschmann** [comment]
I just gut this to work, but it's slightly involved:

1. Mount the SD card on a Linux machine
2. Download [dwc2.dtbo](https://www.dropbox.com/s/4iq46zsv10spbys/dwc2.dtbo?dl=0) to `bootfs/overlays/` on the sd card. I grabbed this during the compilation of RaspberryMatic.
3. Add `dtoverlay=dwc2` to `bootfs/config.txt` on the sd card
3. Paste the following into `rootfs/etc/init.d/` on the sd card
```
#!/bin/sh
#
# Enable USB Gadget mode
#

case "$1" in
  start)
	printf "Starting usb gadget mode: "
	/sbin/modprobe dwc2
	/sbin/modprobe g_ether
	echo "OK"
	;;
  stop)
	printf "Stopping usb gadget mode: "
	/sbin/rmmod g_ether
        /sbin/rmmod dwc2
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
```
4. Add the following to rootfs/etc/networking/interfaces
```
auto usb0
iface eth0 inet dhcp
```

Optionally, you might want to:

1. Add a static MAC address to your init script
2. Assign a static IP address in your interfaces file

In my use case, I use the pi zero on another home automation linux computer. I wanted the pi zero to be bridged to my home network like any other devices (and thus get an IP from my router's dhcp server). For this, I created a network bridge using netplan and udev:

1. Adapt this into your /etc/netplan/01-netcfg.yaml
```
network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:
      dhcp4: no
      dhcp6: no
  bridges:
    br0:
      interfaces: [enp1s0]
      dhcp4: yes
      dhcp6: yes
```
2. Add the following udev rule ``/etc/udev/rules.d/72-raspberrymatic.rules``
```
SUBSYSTEM=="net", ACTION=="add", ATTRS{idVendor}=="0525", ATTRS{idProduct}=="a4a2", NAME="enp0ccu", RUN="/bin/bash -c '/sbin/ifconfig enp0ccu up && /sbin/brctl addif br0 enp0ccu'"
```

As far as adding official support to RaspberryMatic for this, I can imagine that it's easy to add dwc2.dtbo to the RaspberryMatic image. It's already compiled by buildroot but not included.

The other modifications are rather hard to make optional, but I think they shouldn't break anything on systems not using usb ethernet. Maybe @jens-maus can comment on this.

**Comment by fhirschmann** [comment]
Update:

Instead of doing 4. in the description above, an easier solution for networking is creating `rootfs/lib/udev/rules.d/76-netnames.rules` and adding:

```
ENV{ID_PATH}=="", IMPORT{builtin}="path_id"
SUBSYSTEM=="net", ACTION=="add", ENV{ID_PATH}=="*-usb-0:1.*", NAME="eth%n"
```

This will cause the network interface to be named `eth0` instead of `usb0` and the rest of raspberrymatic works untouched.

**Comment by jens-maus** [comment]
Thanks for all these hints and suggestions. Feel free to pack all that into a proper PullRequest and propose it for integration as I would love to integrate gadget mode in one of the next releases.

**Comment by jens-maus** [comment]
Thanks to @fhirschmann USB Ethernet Gadget mode is now available for the Pi Zero (W). Coming up with next upcoming RaspberryMatic release...

**Comment by jens-maus** [comment]
Hi. As @fhirschmann nicely implemented USB ethernet gadget mode now in RaspberryMatic I would like to ask anyone interested to test it in the latest release candidate version of RaspberryMatic. You can download the rpi0 version from here:

https://cloud.light-speed.de/s/xby5d4B7YFRCxyH

Any feedback is highly appreciated. If no issues are found this version will then be released during the next week.

**Comment by fhirschmann** [comment]
Awesome! I'm happy to test this out, but I'm currently abroad and unable to test it for the next three weeks.
