### ISSUE TITLE
wieder Umlautprobleme beim Anlegen von Direktverknüpfungen gesichtet

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#2160]
### Describe the issue you are experiencing

Beim Anlegen von Direktverknüpfungen werden wieder "krumme Zeichen" statt korrekter Umlaute in die Beschreibung geschrieben.

### Describe the behavior you expected

Korrekte Anzeige der Umlaute

### Steps to reproduce the issue

1. DV anlegen, z.B. virt.Taste <--> Schaltakter
2. Text in der Beschreibung der DV betrachten
3.
...

### What is the version this bug report is based on?

3.67.10.20230110-82325d

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
- keine auffälligen Logs
```

### Additional information

Ich kann nicht sagen ab wann das Problemchen wieder Einzug hielt da ich nicht mit jeder Testversion DV's anlege.

Screenshot:
A: alte schon vorhandene DV's
B: mit 3.67.10.20230110-82325d angelegte DV's
![RM_DV_Umlautprobleme](https://user-images.githubusercontent.com/54898249/212265802-d996c669-0ed3-4810-9f06-e09e82e96f4b.JPG)

**Comment by jp112sdl** [comment]
Jup, ist bei mir auch so.
Neu angelegte DVs machen Umlautschrott
<img width="2014" alt="Bildschirm­foto 2023-01-14 um 13 35 02" src="https://user-images.githubusercontent.com/18190139/212471770-2e156256-95d4-4dcb-a47f-7caa3ca22e36.png">

**Comment by jens-maus** [comment]
Komisch. Wo kommt denn das jetzt schon wieder her?!? Bitte mal versuchen auf Vorversionen zurückzugehen um rauszubekommen wann das Problem denn wieder Einzug gehalten hat.

**Comment by jp112sdl** [comment]
Mit der `3.65.11.20221218` ist es noch ok

**Comment by jp112sdl** [comment]
Was mir nur spontan einfällt, wär die Umstellung von `GET` auf `POST` bzgl. `ic_ifacecmd.cgi`

**Comment by jens-maus** [comment]
Stimmt, das könnte es sein. Müsste man mal den commit zurücknehmen und schauen ob das das Problem löst. Und dann ne Lösung dafür finden wenn die Parameter an der stelle falsch/anders kodiert ankommen…

**Comment by jens-maus** [comment]
Kann es nun selbst reproduzieren hier. Wenn jemand jedoch den commit mal testweise zurücknehmen könnte kommen wir dem ganzen aber vllt. etwas schneller auf die schliche.

**Comment by jp112sdl** [comment]
Wenn ich das hier rückgängig mache, geht es wieder:
https://github.com/jens-maus/RaspberryMatic/blob/48b6fc8815c1bc0eaece9bedf119b7276b40d4ab/buildroot-external/patches/occu/0173-WebUI-SendPOSTRequest.patch#L186-L187

**Comment by jens-maus** [comment]
UIuiui. Da haben wir (bzw. @Baxxy13) wohl ne uralt Regression erwischt. Good Job!

Siehe:
https://github.com/jens-maus/RaspberryMatic/commit/b76024513e5f0e65766aad6d0f81ceb3d67986dc#diff-db9c2b95585f64bc2e32e7ecca0791bd1a1543e513a3a382a7ada4d7b89b4457R1309

Damals (2018) hatte ich diese Zeilen eingebaut um Probleme mit dem EDGE Browser auszumerzen (siehe #315) und da ist mir wohl ein Missgeschick passiert weil ich das `$` vor der variablen wohl vergessen habe. Komisch das das nicht aufgefallen war. Bitte also einfach mal in der `/www/extern/cgi.tcl` an besagter Stelle (Zeile 1309) das `$` hinzufügen und einfach nochmal probieren mit aktiviertem `SendPOSTRequest()`. Sollte nun hoffentlich funktionieren.

Und wäre natürlich gut jetzt vllt. nochmal das EDGE Problem von damals nachzutesten wenn das geht und auch wieder breit auf die Suche zu gehen ob dieser Fix hier jetzt nicht wiederum an anderen Stellen die Umlaute kaputt macht (hoffen wir es mal nicht!). Aber dieses Problem hier sollte damit hoffentlich gelöst sein.

**Comment by blackbasket** [comment]
Den alten Edge gibt es doch gar nicht mehr @jens-maus

**Comment by MichaelN0815** [comment]
> Bitte also einfach mal in der `/www/tcl/extern/cgi.tcl` an besagter Stelle (Zeile 1309) das `$` hinzufügen

Ich habe diese Änderung durchgeführt und danach eine DV erstellt. Umlaute werden korrekt dargestellt. (mit Firefox & Edge getestet)

**Comment by jens-maus** [comment]
Na dann war das dieses mal ne recht einfache Sache… puh. Butte aber wie gesagt jetzt mal hingehen un an verschiednsten Stelle testen ob umlaute da auch noch korrekt gehen. Z.b. in Gruppen, anderen DVs, Geräteeinstellungen, etc. etc. Nicht das uns das beim nächsten Release dann wieder auf die Füße fällt…
