### ISSUE TITLE
Fehler "eq3_char_loop"

### ISSUE THREAD

**Issue by tschmitt1605** [jens-maus/RaspberryMatic#2163]
### Describe the issue you are experiencing

Bei mir tritt seit heute morgen folgender Fehler auf: 
`Starting multimacd: modprobe: FATAL: Module eq3_char_loop not found in directory /lib/modules/5.15.76-v7+
,..........ERROR: couldn't setup /dev/eq3loop
,Starting rfd: ERROR: /dev/mmd_bidcos missing, no BidCos-RF hardware found
,Starting HMIPServer: ERROR: /dev/mmd_hmip missing
`

Dies passiert bei jedem restart der Raspberrymatic Instanz in einem Docker Container auf dem Pi 3. Somit kann ich leider das System nicht nutzen. Ich habe schon probiert, jegliche Modul Software neu zu installieren, aber nichts funktioniert. Auf das Web Ui komme ich weiterhin, aber dort wurden heute morgen dann zwei Alarmmeldungen angezeigt.

### Describe the behavior you expected

Ich möchte die Web Ui bzw. Home Assistant (anderer Server) aufrufen und meine Thermostate steuern.

### Steps to reproduce the issue

1. Portainer öffnen
2. Raspberrymatic starten
3. Fehler
...

### What is the version this bug report is based on?

3.65.11.20221218

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
Anhang unten.
```

### Additional information

<img width="788" alt="Bildschirm­foto 2023-01-13 um 14 08 03" src="https://user-images.githubusercontent.com/79532009/212328649-0c207742-9108-4b81-ac30-95de617bed77.png">

**Comment by jens-maus** [comment]
Das wird sicherlich mit einem Kernelupdate zusammenhängen das du manuell oder ggf. automatisch einspielen lassen hast und deshalb fehlt jetzt eben das eq3_char_loop kernel modul das du damals als du den docker container lauffähig gemacht hast anhand der offiziellen Anleitung installieren lassen hast. Und das muss man eben konsequenterweise mit jeder neu installierten kernel version des host system dann wieder/erneut machen. Insofern ist das kein Bug, sondern ein Nutzerproblem und gehört in Diskussions-/Supportforen diskutiert/analysiert und gelöst.

**Comment by tschmitt1605** [comment]
Ok, trotzdem danke für Ihre schnelle Hilfe.
