### ISSUE TITLE
Die Einstellung der Entkalkungsfahrt fehlt in den Einstellungen vom eTRV-E

### ISSUE THREAD

**Issue by Moo1988** [jens-maus/RaspberryMatic#2167]
### Describe the issue you are experiencing

In den Geräte-Einstellungen vom eTRV-E fehlt die Option zum wählen an welchem Tag/Uhrzeit die Entkalkungsfahrt erfolgen soll. 

### Describe the behavior you expected

In den Einstellungen des eTRV-E lässt sich der Tag und Uhrzeit auswählen, wann die Entkalkungsfahrt stattfinden soll.

### Steps to reproduce the issue

1. Einstellungen - Geräte - HmIP-eTRV-E Einstellen
2. Ch.:1 Entkalkungsfahrt Tag/Uhrzeit

### What is the version this bug report is based on?

3.67.10.20230114

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
nein
```

**Comment by jens-maus** [comment]
Meines Wissen ist das kein Bug, sondern ein Feature. Denn der HmIP-eTRV-E (Evo) benötigt keinerlei regelmäßige Entkalkungsfahrt, sondern erledigt das meines Wissens vollständig selbstständig.

Siehe dazu auch:
https://homematic-forum.de/forum/viewtopic.php?t=70966#p690379
https://de.elv.com/homematic-ip-smart-home-heizkoerperthermostat-evo-hmip-etrv-e-155105

Dort auf der ELV Seite ist unter anderem auch das hier einzusehen unter FAQ:
<img width="1266" alt="Bildschirm­foto 2023-01-14 um 20 43 49" src="https://user-images.githubusercontent.com/5887769/212493392-ea8dd90d-ac41-4889-9508-95d2649e64fa.png">

**Comment by Moo1988** [comment]
@jens-maus 
wieder was dazu gelernt. Klingt auch logisch. 
Vielen lieben Dank für die schnelle Reaktion!
