### ISSUE TITLE
Home Assistant Addon breaks other uses of USB devices

### ISSUE THREAD

**Issue by eikowagenknecht** [jens-maus/RaspberryMatic#2170]
### Describe the issue you are experiencing

I'm using the RaspberryMatic addon on a Pi 4.

The following devices are connected to the Pi:
- USB - Enocean 300 (used by RaspberryMatic / CuxD)
- USB - HmIP-RFUSB (used by RaspberryMatic)
- USB - SkyConnect (should be used by Home Assistant itself or an other addon)

When the RaspberryMatic addon is not running, Home Assistant can use the SkyConnect just fine.

![image](https://user-images.githubusercontent.com/1475672/212657678-a27ecfb5-eb85-45fc-a608-1ea22de14a70.png)

As soon as I start Raspberrymatic though, it stops working.

![image](https://user-images.githubusercontent.com/1475672/212657922-0c888f21-8c8b-4f5b-8bc2-8fd0c5861e02.png)

I suspect that the device somehow gets routet to the raspberrymatic addon and thus cannot be used any more by anything else?

### Describe the behavior you expected

Please add the option to *not* route some USB device through to the Raspberrymatic addon or to have to manually select which devices are to be routed through.

### Steps to reproduce the issue

1. Connect Zigbee USB Stick
2. Start RaspberryMatic Addon
3. Try to read the info with the Terminal (pip install silabs-flasher && silabs-flasher --device /dev/tty... info)

### What is the version this bug report is based on?

3.67.10.20230114

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
No
```

**Comment by jens-maus** [comment]
As you seem to use CUxD within RaspberryMatic, I think you have to make sure CUxD will not grab other USB serial devices once it is starting up. So please consult the CUxD manuals to pervent it from grabbing any third-party serial devices (which it actually does per default!).

**Comment by Baxxy13** [comment]
Yesterday in Homematic-Forum...
[Link](https://homematic-forum.de/forum/viewtopic.php?f=37&t=77586)

**Comment by eikowagenknecht** [comment]
Thanks!
