### ISSUE TITLE
LED des RPI-RF-MOD inaktiv bei GPIO-Anbindung auf RPi1B+

### ISSUE THREAD

**Issue by msebald** [jens-maus/RaspberryMatic#2173]
### Describe the issue you are experiencing

Die LED des RPI-RF-MOD (auf GPIO) ist nicht in Betrieb (immer aus). Habe den RPI-RF-MOD und RaspberryMatic heute neu in Betrieb genommen auf einem RPi1B+ (lag noch rum, andere RPi Modelle müssten beschafft werden).

### Describe the behavior you expected

Die LED eines RPI-RF-MOD auf GPIO sollte funktional sein.

### Steps to reproduce the issue

1.
2.
3.
...

### What is the version this bug report is based on?

3.67.10.20230114 (rpi0)

### Which base platform are you running?

rpi0 (RaspberryPi)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Habe spontan nichts bei der Durchsicht der Logs gesehen, was spannend sein könnte. Liefere ich aber gerne bei Hinweis auf passende Suchbegriffe nach.
```

**Comment by jens-maus** [comment]
Wie genau soll das bitte gehen? Ein RaspberryPi1 hat doch eine verkürzte Pfotenleiste und da fehlen dann halt einfach die notwendigen GPIO Pins um die LEDs des RPI-RF-MOD anzusteuern. Dachte das müsste klar sein wenn man es versucht draufzustecken und merkt das die Pfostenleiste des RPI-RF-MOD länger ist als die des Pi1. Ergo: geht nicht!

**Comment by msebald** [comment]
> Wie genau soll das bitte gehen? Ein RaspberryPi1 hat doch eine verkürzte Pfotenleiste und da fehlen dann halt einfach die notwendigen GPIO Pins um die LEDs des RPI-RF-MOD anzusteuern. Dachte das müsste klar sein wenn man es versucht draufzustecken und merkt das die Pfostenleiste des RPI-RF-MOD länger ist als die des Pi1. Ergo: geht nicht!

Halt Moment, ich habe das Modell 1B+ im Einsatz. Das hat ebenso wie alle nachfolgenden Modelle 26 Pins (siehe [https://de.wikipedia.org/wiki/Raspberry_Pi#Raspberry_Pi](https://de.wikipedia.org/wiki/Raspberry_Pi#Raspberry_Pi)) und die Pfostenleiste des RPI-RF-MOD passt perfekt drauf.

Es könnte also schon funktionieren?!?

Muss dazu das Image angepasst werden oder kann ich gar das 2er Image verwenden?

**Comment by msebald** [comment]
@jens-maus Ich habe nun mal genau geschaut. Die 40 (nicht 26 wie oben geschrieben, bin da in der Zeile verrutscht) GPIO PINs  GPIO sind ausnahmslos identisch für die Modelle 1B+, 2B und 3B. Bei 4 habe ich nicht verglichen. Hier zwei URLs dazu:

[https://www.raspberry-pi-geek.com/howto/GPIO-Pinout-Rasp-Pi-1-Model-B-Rasp-Pi-2-Model-B](https://www.raspberry-pi-geek.com/howto/GPIO-Pinout-Rasp-Pi-1-Model-B-Rasp-Pi-2-Model-B)
[https://www.etechnophiles.com/raspberry-pi-3-b-pinout-with-gpio-functions-schematic-and-specs-in-detail/](https://www.etechnophiles.com/raspberry-pi-3-b-pinout-with-gpio-functions-schematic-and-specs-in-detail/)

Aufgrund der aktuellen Preise für die Raspberries wäre es toll, wenn der 1B+ auch LED-Unterstützung hätte.

K.A., wie aufwändig das ist. Kann ich ggf nach Installation oder Upgrade per SSH ein paar Befehle oder ein Script laufen lassen?
