### ISSUE TITLE
An internal error was detected in the service software

### ISSUE THREAD

**Issue by AVRnet** [jens-maus/RaspberryMatic#2176]
### Describe the issue you are experiencing

Beim Versuch in der Version 3.65.11.20221005 (Dockerimage auf einem Odroid N2+ mit Debian Buster)
über das Menü "Einstellungen" -> "Systemsteuerung" die "Zentralen-Wartung" aufzurufen,
poppt ein "An internal error was detected in the service software" Fehler auf.
Eine weitere Eingabe ohne die Webseite neu zu laden ist nicht mehr möglich.

Alle anderen Menüs funktionieren einwandfrei und tadellos.

Die Ausgabe der Datei **/usr/local/tmp/cgimail.*** ergibt:

```
cookie:
errorInfo:
can't use non-numeric string as operand of "/"
    while executing
"expr {$USERFSFREE_MB / 1024.0}"
    (procedure "action_put_page" line 6)
    invoked from within
"action_put_page"
    invoked from within
"if {[session_requestisvalid 8] > 0} then action_$action"

```

**Comment by jens-maus** [comment]
Please show the output of `df -h` from within the container. Also show your container startup command, especially the connected volumes / mountpoint dependencies

**Comment by jens-maus** [comment]
> Beim Versuch in der Version 3.65.11.20221005...

Ah, sehe den Hinweis jetzt erst. In dieser uralt Version ist dieser Bug natürlich noch vorhanden, das ist klar. Wurde erst mit commit https://github.com/jens-maus/RaspberryMatic/commit/e2befa128311d0abd4c06aaca3fe0182b9682bdf beseitigt und folglich seit der 3.65.11.20221218. Daher ist es ja immer gewünscht (und so auch explizit im Ticket Template erwähnt) doch bitte nur Bugreports zu reporten die auf der jeweils aktuellsten Version basieren bzw. damit auch reproduziert wurden.
