### ISSUE TITLE
new Systemvariables are gone after reboot

### ISSUE THREAD

**Issue by guny74** [jens-maus/RaspberryMatic#218]
Hello,

in the release 2.29.23.20171118 and 2.29.23.20171216 (RPI 3) new system variables disappear after reboot.
So program and script using them are no longer running.

Any idea ?

Thanks Regards
   Thorsten

**Comment by jens-maus** [comment]
Works here without issues. Make sure to properly save (press Logout) on the WebUI before you restart the Pi.

**Comment by guny74** [comment]
Hello,

corresponding to your hint, it disappears also after logout (without reboot).
I add the variable. After that I see ist in the list. I am also able to filter to it and change the description....I also can use/select it in Webui programms. After logout it is gone....and the place in the programms are empty.

As I found that, I did an upgrade to the latest release. The same issue.

**Comment by guny74** [comment]
Hello,

I tested a little bit more.... It is a special case I think..... the variable name I used was "PrgStep" (Program Step" only the variable with this name disappears, all others are ok... If I name it "prgStep" it also works.... 
So I think I hit a special (not allowed) internal variable name...

So now it works for me also

Thanks
