### ISSUE TITLE
Integration der /var/log/boot.log in die Funktion "Logdatei herunterladen"

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#2186]
### Describe the solution you'd like

Die `/var/log/boot.log` ist ja sehr nützlich um nach dem Bootvorgang Probleme während des vorausgegangenem Bootvorganges zu erkennen.
Das Problem ist aber (für die nicht so erfahrenen User), an diese Datei zu kommen bzw. diese für Analysezwecke bereitzustellen.

Meine Idee ist die `boot.log` mit in das Fehlerprotokoll zu integrieren welches man über > Einstellungen > Systemsteuerung > Zentralen-Wartung -> Fehlerprotokoll --> "Logdatei herunterladen" herunterladen kann.

### Describe alternatives you've considered

aktuell fällt mir da keine sinnvolle Alternative ein

### Is your feature request related to a problem?

Nicht direkt problembezogen, aber nützlich um leicht an die `boot.log` zu kommen um diese zu Analysieren.

**Comment by jp112sdl** [comment]
https://github.com/eq-3/occu/blob/18bbbbe769e599f976f737a2bc37aac0bbe49e9e/WebUI/www/config/cp_maintenance.cgi#L1381

`boot.log` in die Aufzählung einfügen
