### ISSUE TITLE
HmIP-WKP: Kanalbeschreibungen fehlerhaft bei Direktverknüpfungen

### ISSUE THREAD

**Issue by paulcombuse** [jens-maus/RaspberryMatic#2187]
### Describe the issue you are experiencing

Bei einer Direktverknüpfung von HmIP-WKP (Keypad) mit einem HmIP-DLD (Türschlossantrieb) werden die Kanalbeschreibungen fehlerhaft/durcheinander angezeigt, obwohl in den Geräten selbst die Bezeichnungen korrekt sind.
Korrekt beim Gerät:
![image](https://user-images.githubusercontent.com/65916471/215089200-22493ba7-fc5f-4908-944f-f36b3d52ac88.png)
aber bei Direktverknüpfung fehlerhafte Anzeige (**nur erste Spalte wesentlich**):
![image](https://user-images.githubusercontent.com/65916471/215195089-eea5b0f1-e046-4b36-8332-691c1d8ea452.png)

### Describe the behavior you expected

Die Kanalbezeichnungen sollten entsprechend der Kanalnummern bei Gerät und Direktverknüpfungen identisch sein und korrekt. 

### Steps to reproduce the issue

1. Erstellen einer neuen Direktverknüpfung zwischen HmIP-WKP Kanal 1 (User 1 - Verriegeln) oder Kanal 6 (User 3 - Entriegeln) und HmIP-DLD Kanal 2 (User 1) oder Kanal 4 (User 3)
2. Vergleich der Kanalbezeichnungen bei der Direktverknüpfung mit denen vom HmIP-WKP (siehe Screenshots oben)

### What is the version this bug report is based on?

3.67.10-20230114

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
no
```

**Comment by jens-maus** [comment]
Bekannt, erkannt und bereits für die nächste Version gefixt. Siehe #2160

**Comment by mbhomie007** [comment]
@jens-maus

Es geht hier aber nicht nur um die Umlaut- Problematik... Die bereits gefixt ist. 

Kanal 1 und Kanal 6 können nicht beide Benutzer 2 sein.

Benutzer 2 müssten Kanal 2 und Kanal 3 sein. 

Die Kanalbezeichnung passt nicht zum Kanalnamen in der ersten Spalte.

Das konnte ich auch schonmal beobachten. 
Da stand dann bei mir "Keypad Kanal 1 - Benutzer 26" also ein viel zu hoher Wert.... 

Nach einem Neustart war wieder alles optisch okay. 
Eventuell ein Cache Problem? 

@paulcombuse
Richtig?

**Comment by jens-maus** [comment]
> @jens-maus
> 
> Es geht hier aber nicht nur um die Umlaut- Problematik... Die bereits gefixt ist.

Ah ok. Das passiert wenn man halt zwei Sachen miteinander vermengt in einem Issue. Hab beim Durchscrollen nur die umrandeten Umlaute gesehen und fertig. Dann öffne ich das hier mal wieder, mahne aber an bitte beim nächsten mal nicht zwei getrennte Probleme in einem Issue zu posten.

**Comment by mbhomie007** [comment]
Danke dir.

Wenn es bei mir auch wieder auftreten sollte, poste ich auch mal ein Screenshot, vielleicht kann man das dann nochmal aufgreifen.

**Comment by paulcombuse** [comment]
Ich hatte das versucht an mehreren Stellen und im Titel herauszustellen, aber beim Screenshot hätte ich mich auf eine Sache fokussieren sollen. Bilder lenken halt ab...

**Comment by paulcombuse** [comment]
> Nach einem Neustart war wieder alles optisch okay. Eventuell ein Cache Problem?
> 
> @paulcombuse Richtig?

Nein, das kann ich leider nicht bestätigen - ich habe mehrfach neu gestartet und auch mehrfach den Cache geleert.
