### ISSUE TITLE
WebUI: Add default Display of DutyCycle

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#219]
Outputting the DutyCycle is currently only possible via external scripts. However, to be able to monitor the DutyCycle values of all RF interfaces we should add a possibility to display the DutyCycle on the front page of the WebUI (e.g. within the Favorites section). In addition, it would be great if there could by dedicated system variables holding the current dutycycle values of all RF interfaces (including LAN-Gateways).

**Comment by drose28357** [comment]
I would prefer the sugested "system variable" solution because we are then enabled to trigger programms on value changes within homematic. But we have to deal with more than one rf module (for example lan gateway).

**Comment by jp112sdl** [comment]
I would prefer to show it fixed on the right side (below "Aktuelle Firmwareversion").

Another way could be adding a "Servicemeldung" at a specific threshold (e.g. if DC is > 70%).

**Comment by Norbl** [comment]
Would be great to have the duty Cycle automatically in a System Variable, to Check it and to use it in programs

**Comment by HMside** [comment]
I have played little bit and built in an output of two dutycycle system variables on the right side of the WebUI startpage. But now we have to create a automatism which is created the DC variables for the CCU and all gateways. For the CCU we can create a fixed variable name such as "DC-CCU" and for the installed gateways it should set the given name from the gateway-section such as "DC-OG1". But this is problematic if the user has set a gateway name.

The next question is: what is the best way to read out the DC?
Currently, I use this script from the user "black": https://homematic-forum.de/forum/viewtopic.php?f=26&t=31397#p289915

![dc](https://user-images.githubusercontent.com/13312068/36872315-30f0e84e-1da5-11e8-8f4f-245a15c99452.png)

If any of you has suggestions or concrete ideas, then please give it to me

**Comment by jp112sdl** [comment]
@HMside 
I am not using a gateway, but does it appear in the WebUI with its serial number such as OEQ1234567? 
So it could be shown as DC-OEQ1234567

Btw.: I am using the same script to determine the DC value.

**Comment by jens-maus** [comment]
@HMside Thanks for looking at how we can integrate a DC display. Can you please present your currently solution by submitting a pull request so that we can test and further work on it?

**Comment by HMside** [comment]
Now I found a way to read out the DC inclusive the gateway names or if not set the serial numbers. With this solution we dont need an external script. At present this solution do not create system variables automatically. It were also possible to show the gateway connection status. I think i can submit a pull request tomorrow. See results in the following GIF.

CCU = Central / KEQ1022949 = HM-CFG-LAN / NEW = HM-LGW-O-TW-W-EU
![dutycycle](https://user-images.githubusercontent.com/13312068/36940181-6961b614-1f3e-11e8-9555-c96476a2ae28.gif)

**Comment by jens-maus** [comment]
@HMside Thanks Andreas. This really looks promising and I am looking forward to your PR. However, please note my initial ideas for the feature because I also already thought about how this could be potentially implemented in a future version:

- I would prefer to implement such a feature by always creating and using system variables to store the DutyCycle values so that these system variables could be queried/used in programs, etc.
- The user could then either add these system variables to his user shared objects himself so that these values are shown on the front page of the WebUI. Potentially we could then add these system variables by default to the front page similar to how you have done this – however, each RF gateway/device should get an own row in the variables display and not be combined like in your solution.

My idea was:

1. modify the external DutyCycle .tcl script to not only query the duty cycle values but also to create proper system variables (for each Gateway/RF device one system variable) per default and then create a default cronjob that executes this tcl script regularly (e.g. every 3 or 7 minutes).
2. modify the webui to display these duty cycle system variables per default on the front page of the WebUI similar to how you have implemented it in your solution.

However, I am looking forward to your PR to review it and to actually start a discussion how this could be implemented in a most practical way.

**Comment by HMside** [comment]
Thank you for your suggestions. I also think that the DC variables should be automatically added and I will try to implement this. For the Central DC I think it should shown on the front page by default, because most users only use the CCU without a gateway. Your idea, that the gateway users can add the gateway DC variables to the front page by itself is great.

**Comment by jens-maus** [comment]
@HMside Any news regarding your PR? I would really like to see your approach so that we can start discussion on it and find a way to finalize how this can be implemented in a smooth, nice way.

**Comment by HMside** [comment]
@jens-maus I have now completely revised it and added the requested features. Before I push the PR i will still perform a few tests with more the two gateway. I therefore ask for a few more days patience

**Comment by jens-maus** [comment]
@HMside
No problem. Whenever you are ready!

**Comment by jens-maus** [comment]
@HMside Any progress regarding this ticket?

**Comment by jens-maus** [comment]
@HMside Sorry to bug you again. But any progress on the DutyCycle changes you were about to provide?

**Comment by HMside** [comment]
First Part #301
Second Part:
Is one tcl script which create automatically the variables. This file should be triggered  all 3 minutes by a cron. The question is, what is the best place for this file and the best way to add cron entry
