### ISSUE TITLE
HmIP-BWTH does not show value of Channel 10 (open/closed state)

### ISSUE THREAD

**Issue by HBIoT** [jens-maus/RaspberryMatic#2192]
### Describe the issue you are experiencing

After updating to 3.67.10.20230114 the Status of Channel:10 of HmIP-BWTH isn't shown anymore

![image](https://user-images.githubusercontent.com/96540048/215293198-cdce149a-f893-46e0-9a57-241fad81d4a3.png)

### Describe the behavior you expected

Status should be displayed.

### Steps to reproduce the issue

1.
2.
3.
...

### What is the version this bug report is based on?

3.67.10.20230114

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
?
```

**Comment by jens-maus** [comment]
Und wie sah das ganz in vorherigen Versionen aus? Hab selbst kein HmIP-BWTH und kann das daher nicht testen hier.

**Comment by HBIoT** [comment]
Vorher wurden die Werte angezeigt. Der Screenshot zeigt den Zustand nach Rollback auf Release 3.65.11.20221218
![image](https://user-images.githubusercontent.com/96540048/215353472-3c7aac2d-620f-4c06-bfdb-3d1e2caaf39c.png)

**Comment by jp112sdl** [comment]
Kommt in der Browserkonsole eine Fehlermeldung?
Sieht optisch erstmal so aus, als würde nach dem ersten Gerät die (Java)Skript-Verarbeitung abbrechen

**Comment by jens-maus** [comment]
Kurze Zwischeninfo. Scheint wohl auch in der reinen CCU3 Firmware zu passieren. Siehe:

https://homematic-forum.de/forum/viewtopic.php?f=34&t=77852&p=755902#p755901

D.h. ein upstream bug in der WebUI von OCCU seit 3.67.10? Habe leider selbst kein `HmIP-BWTH` und kann das daher leider nicht testen. Wir sind also auf Mithilfe von anderen (@HBIoT) angewiesen wenn das Problem beseitigt werden soll.

**Comment by jp112sdl** [comment]
Die Änderung kam in der `heating_control.fn` mit 3.67.5 (https://github.com/eq-3/occu/commit/53f45b9d618865d80df417e1ca55d376ed1fc013)

Da wurde die `CreateBWTHSwitchState()` komplett überarbeitet:
https://github.com/eq-3/occu/commit/53f45b9d618865d80df417e1ca55d376ed1fc013#diff-5ccd21ec028b6606c74db5ca77a791e52f5fac85510dde697204a1833c023b63L550-R602

**Comment by HBIoT** [comment]
> Kommt in der Browserkonsole eine Fehlermeldung? Sieht optisch erstmal so aus, als würde nach dem ersten Gerät die (Java)Skript-Verarbeitung abbrechen

@jp112sdl : wie du vermutest, wird offenbar das erste Gerät auf eine Seite korrekt angezeigt. Ich erkenne das daran, daß ich zwei Favoriten Seiten eingerichtet haben. Auf jeder Seite wird jeweils der erste Eintrag aus den BWTH's korrekt angezeigt.
Mit der Browserkonsole müsstest Du mir mal helfen. Wo genau müsste ich da hinschauen?

**Comment by jp112sdl** [comment]
Kommt auf den Browser und das Betriebsystem an...
Chrome oder Firefox unter Windows: F12 drücken. Dann gibt es da unten den Tab "Konsole" oder "Console"

**Comment by HBIoT** [comment]
Aufgrund der Ausgabe der XML-API nehme ich an, daß hier ein boolscher Wert verarbeitet werden muss.

```
<channel name="Thermostat Bad:10" ise_id="1826">
<datapoint name="HmIP-RF.00xxxxxxxxxxxx:10.STATE" type="STATE" ise_id="1827" value="false" valuetype="2" valueunit="" timestamp="1675346301"/>
</channel>
```

**Comment by jp112sdl** [comment]
> Aufgrund der Ausgabe der XML-API nehme ich an, daß hier ein boolscher Wert verarbeitet werden muss.

Darum ging es nicht. Es geht um  `HEATING_VALVE_TYPE` des Kanal 8.
https://github.com/eq-3/occu/blob/master/WebUI/www/rega/esp/controls/heating_control.fn#L593-L597

Bei den Konsolenmeldungen wird das noch nicht alles sein.
Da müssten mindestens noch einige Warnungen auftauchen
Evtl. findet sich noch jemand hier, der sich in der Konsole auskennt.

**Comment by jp112sdl** [comment]
> Das "riecht" für mich danach, das state hier weder true noch false wird, sondern vmtl. ein string wird weil valveState als string ausgeliefert wird bzw. die folgende Zeile aus valveState dann eben ein String macht...

Ich hatte nicht auf dem Schirm, dass die Deklaration `boolean` nicht verbindlich ist.

Meine Vermutung zielte eher darauf ab, dass 
`chn8Description.HEATING_VALVE_TYPE` nicht 0 oder 1 zurück gibt, sondern einen String und das JS abbricht, weil es bei `parseInt` knallt.

**Comment by jens-maus** [comment]
> Meine Vermutung zielte eher darauf ab, dass `chn8Description.HEATING_VALVE_TYPE` nicht 0 oder 1 zurück gibt, sondern einen String und das JS abbricht, weil es bei `parseInt` knallt.

Stimmt, das kann auch sein. Oder da `getParamset()` geht an der stelle schief oder liefert einfach ggf. nur mal einen empty string zurück oder so... Laut der offiziellen homematicIP doku (https://homematic-ip.com/sites/default/files/downloads/hmip-device-documentation.pdf) liefert dieser Kanal wohl schon einen integer, aber er ist auch als ENUM vermerkt mit Namen dahinter:

<img width="641" alt="Bildschirm­foto 2023-02-03 um 11 30 09" src="https://user-images.githubusercontent.com/5887769/216579062-9ab78748-7ea3-4c21-bdea-fb694bcef442.png">

Wer weiss was da so passiert. Aktuelle Vermutung von mir ist das der `getParamset()` aufruf irgendwie ins leere rennt für gewisse geräte (gleicher Firmwarestand? Fehlende Datenpunkt weil mit FW-Update irgendwann nachgeliefert?), denn anscheinend sind nicht alle BWTH Nutzer von dem Problem betroffen... Leider hab ich keinerlei Geräte in meinem Fuhrpark der diesen `HEATING_VALVE_TYPE` DP hat.

**Comment by isi07** [comment]
Kann das Problem bei mir bestätigen.
Meine Raspberrymatic läuft auf 3.67.10.20230114 (ova).
Die HmIP-BWTH sind auf der beta firmware 2.8.10.

Anzeige von mehreren gleichzeitig:
nur beim ersten Kanal 10 wird der Status angezeigt, bei den folgenden nicht mehr

![grafik](https://user-images.githubusercontent.com/65848350/217915781-859ecff0-c6e9-409b-ae43-4e4f25b40c06.png)

Meldungen in der Konsole / Firefox unter Windows

Jedes BWTH einzeln funktioniert
![grafik](https://user-images.githubusercontent.com/65848350/217915254-018da4e5-e43f-46ae-b9c3-62642688087a.png)

![grafik](https://user-images.githubusercontent.com/65848350/217915336-2789a55a-a2c7-43ca-9d3d-b372e3161bf7.png)

![grafik](https://user-images.githubusercontent.com/65848350/217915402-59860029-546d-4960-ac9a-16665a6fe823.png)

**Comment by jp112sdl** [comment]
Ah okay. Jetzt ist es eindeutig:
https://stackoverflow.com/questions/902839/how-to-select-all-elements-with-a-particular-id-in-jquery

> When you use
jQuery("#elemid") 
it selects only the first element with the given ID.

Die Lösung könnte dann Stackoverflow zufolge lauten:
Aus `WriteLine("jQuery('#idValveState').text(lblValveState);");`
mach `WriteLine("jQuery('[id=idValveState]').text(lblValveState);");`

**oder** man arbeitet in der Tabelle statt mit `id` 
` WriteLine("<td><div id='idValveState'></div></td>");`
mit einer `class`
` WriteLine("<td><div class='clsValveState'></div></td>");`

und dann
`WriteLine("jQuery('.clsValveState').text(lblValveState);");`


Testen kann ich es nicht.

**Comment by jens-maus** [comment]
Das ist ein super Hinweis! Allerdings würde ich wohl besser die id ändern und da z.b. die objekt/device id einfach hinzufügen!

**Comment by jp112sdl** [comment]
>Allerdings würde ich wohl besser die id ändern und da z.b. die objekt/device id einfach hinzufügen! 

Ach ja, sonst steht ja bei allen der selbe Text 🤓 
Also einfach noch die `chnId` mit anhängen, dann sollte es passen?

```
586: WriteLine("<td><div id='idValveState"#chnId#"'></div></td>");
...
615: WriteLine("jQuery('#idValveState"#chnId#"').text(lblValveState);");
```

**Comment by jens-maus** [comment]
> > Allerdings würde ich wohl besser die id ändern und da z.b. die objekt/device id einfach hinzufügen!
> 
> Ach ja, sonst steht ja bei allen der selbe Text 🤓 Also einfach noch die `chnId` mit anhängen, dann sollte es passen?

Genau so ist es und so würde ich das jetzt auch umsetzen wollen. Danke also nochmal für den Denkanstoß!

**Comment by jens-maus** [comment]
Ok, das Problem sollte nun für die nächste Version behoben sein. Interessierte könnten bereits mit dem morgen erscheinenden nightly snapshot entsprechend testen ob das Problem nun wirklich beseitigt ist und hier bitte entsprechendes Feedback geben.

**Comment by bropat** [comment]
@jens-maus 

Ich habe die letzten nightly snapshot Version getestet und erhalte dabei noch folgenden Fehler:

![image](https://user-images.githubusercontent.com/2305255/218523447-1399028b-50dd-4a45-8cb8-c86b68d96531.png)

![image](https://user-images.githubusercontent.com/2305255/218523316-0ff44cc3-de6f-4d78-bea9-20734489e833.png)

**Comment by jp112sdl** [comment]
> vom Typ HmIP-FROLL

Das ist wirklich sehr merkwürdig und hat glaub ich mit diesem Bug hier nix zu tun.

Die Funktion `CreateBWTHSwitchState()` an sich dürfte beim FROLL schon gar nicht aufgerufen werden.

`CreateBWTHSwitchState()` wird nur aufgerufen, wenn im `Label()` des Kanals der Teilstring `BWTH` enthalten ist:
https://github.com/eq-3/occu/blob/master/WebUI/www/rega/esp/datapointconfigurator.fn#L983-L990

**Comment by jens-maus** [comment]
Würde mir ehrlich gesagt auch interessieren wie das zustande kommt das ein FROLL diese Funktion aufrufen lässt die nur für BWTH bestimmt ist. Ist das reproduzierbar?

**Comment by bropat** [comment]
Ja ist reproduzierbar. Der Fehler tritt seit der Version 3.67.10.20230114 immer beim laden der Startseite auf (denke liegt an der Favoritenansicht). Nach dem auftreten des Fehlers wird nichts mehr weiter geladen:

![image](https://user-images.githubusercontent.com/2305255/218813506-077c2e00-7df3-401c-90d8-6bb3d0351856.png)

**Comment by jp112sdl** [comment]
Jetzt wird es ja wirklich komisch.
Hast du in der Favoritenansicht ein BWTH ?

Unabhängig davon wäre es - auch wenn es nicht auftreten sollte - sinnvoll, `chn8Description` auf `null` zu prüfen, bevor damit irgendwas gemacht wird (`parseInt` usw.)

**Comment by bropat** [comment]
Ja hab ich.

**Comment by jens-maus** [comment]
> Unabhängig davon wäre es - auch wenn es nicht auftreten sollte - sinnvoll, chn8Description auf null zu prüfen, bevor damit irgendwas gemacht wird (parseInt usw.)

Ja, denke auch das man das machen sollte (wie immer!). Trotzdem wäre es interessant herauszubekommen wie der auf die idee kommt das auszuwerten auch wenn das ein FROLL ist.
