### ISSUE TITLE
Raspberrymatic auf HA auf Intel NUC

### ISSUE THREAD

**Issue by colognebroker** [jens-maus/RaspberryMatic#2197]
### Describe the issue you are experiencing

Habe den Homeasist auf einem Intel Nuc und darauf das RaspMatic Ads-on
, allerdings bekomme ich über den HmIP RFUSB stick nix angelernt

Der Stick wird im Protokoll erkannt mit "ok"

auch im Posteingang zu finden , aber er erkennt halt nix findet kein Gerät

** /var/log/boot.log **
Mounting /data as /usr/local (Home Assistant Add-On): OK
Identifying host system: oci, OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: OK: backup successfully restored
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.6, OK
Identifying Homematic RF-Hardware: ....HmRF: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-0000:00:14.0-2, HmIP: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-0000:00:14.0-2, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: 4.4.18, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting sshd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: .......OK
Starting rfd: .OK
Starting HMIPServer: ........OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.67.10.20230130 (raspmatic_oci_amd64)

### Describe the behavior you expected

Stick müsste Homematic geräte sehen und anlernen können, das ist aber nicht so

### Steps to reproduce the issue

1. ich habe das add on mehrfach gelöscht und neu installiert
2.ich habe den HmIP RFUSB an verschiedene USB Ausgänge gehängt
3.
...

### What is the version this bug report is based on?

latest

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
i dont know
```

**Comment by Baxxy13** [comment]
Als erstes mal den Carrier Sense auf der Startseite begutachten.
Dauerhafte Werte > 5% deuten schon auf einen Funkstörer hin, vielleicht der NUC selbst.

Ist da beim CS alles i.O. dann mal meine [Anlern-Problem-Analyse-Anleitung](https://homematic-forum.de/forum/viewtopic.php?f=65&t=76473&hilit=anlernkatastrophe#p741589) lesen und Step-by-Step durchführen.
Am Ende wird das TRACE-Log sowie die letzten 4 Zeichen der SN des anzulernenden IP-Gerätes für die Analyse benötigt.
Das am Besten im verlinkten Thread posten, da es erstmal nicht nach Bug in RaspberryMatic aussieht.
