### ISSUE TITLE
HASS Addon Broken on HASSOS 9.5

### ISSUE THREAD

**Issue by ElGauchooooo** [jens-maus/RaspberryMatic#2201]
### Describe the issue you are experiencing

I've seen a similar bug at https://github.com/jens-maus/RaspberryMatic/issues/1942, which is already closed and was related to HASSOS 9.0 - now apparently this reappears on HASSOS 9.5, running HA Core 2023.2.0 (was already broken on 2023.1.7 - tested aswell), running on a Intel NUC in a proxmox environment, RaspberryMatic is installed via AddOn

RaspberryMatic addon runs and works without issues, devices are recognized and update flawlessly.

Home-assistant logs regarding "homematic":

```
2023-02-02 14:05:29.923 WARNING (SyncWorker_6) [pyhomematic._hm] Failed to initialize proxy for homeassistant-wired
2023-02-02 14:05:37.691 WARNING (MainThread) [hahomematic.central_unit] create_clients failed for RaspberryMatic
2023-02-02 14:05:37.701 WARNING (MainThread) [hahomematic.central_unit] check_connection failed: No clients exist. Trying to create clients for server RaspberryMatic
2023-02-02 14:05:37.723 WARNING (MainThread) [hahomematic.central_unit] create_clients failed for RaspberryMatic
2023-02-02 14:05:52.734 WARNING (MainThread) [hahomematic.central_unit] check_connection failed: No clients exist. Trying to create clients for server RaspberryMatic
2023-02-02 14:05:52.813 WARNING (MainThread) [hahomematic.central_unit] create_clients failed for RaspberryMatic
```

RaspberryMatic CCU Logs:

```Mounting /data as /usr/local (Home Assistant Add-On): OK
Identifying host system: oci, OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.3, OK
Identifying Homematic RF-Hardware: ....HmRF: n/a, HmIP: HMIP-RFUSB-TK/eQ-3 HmIP-RFUSB@usb-0000:01:1b.0-2, OK
Updating Homematic RF-Hardware: HMIP-RFUSB-TK: 4.2.14, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: not required
Starting rfd: no BidCos-RF hardware found
Starting HMIPServer: .....OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.67.10.20230114 (raspmatic_oci_amd64)
```

All my devices are now listed as "unavailable" in HomeAssistant.

### Describe the behavior you expected

All devices show up in HomeAssistant

### Steps to reproduce the issue

Install latest HA Core + HA OS + RaspberryMatic CCU Addon, all devices report as "unavailable". 

### What is the version this bug report is based on?

3.67.10.20230114

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
No.
```

**Comment by jens-maus** [comment]
Sorry, don't get it. How is this new issue here in any way related to #1942? To me this only had one thing in common: It's about HomeAssistant. But your issue here seems not to be related to the other one in any way.

All you report is that the addon works in principle and that even the homematic devices are working. But then you are telling us that all devices report as "unavailable". Don't get it really. Are the homematic devices now working in the Addon, yes or no. And if yes then this is rather an issue / problem in the "Homematic(IP) local" integration and not in any way related to RaspberryMatic itself. Thus, you should report / ask in the integration project instead.

**Comment by SukramJ** [comment]
Moin @jens-maus,
von so einem Problem hab ich schon mehrfach gehört.
Nach einem Update von HAOS gibt es Verbindungsprobleme von der Integration zum Addon, wobei das Addon eigentlich normal zu laufen scheint. Hier hilft meistens ein Restart des Addon. 
Klassiker ist eigentlich der PI3 Benutzer, aber hier geht es um einen NUC mit Proxmox.

Ob das HAOS Update tatsächlich der Auslöser ist, oder ansonsten HAOS nur nicht durchgestartet wird, kann ich nicht sagen.

Ich konnte den Fehler bisher nicht reproduzieren.

**Comment by ElGauchooooo** [comment]
I'll ´stick to english as it might be interessting for many users. The devices are working flawlessly in the RaspberryMatic AddOn, i've created an issue on their repo, which has been linked  by @SukramJ . He mentioned there that there's a post in the [community forum ](https://community.home-assistant.io/t/homematic-devices-not-available-in-ha-anymore-homematic-ip-local-failed-to-connect/529114) which is not mine, so it looks like others are affected aswell. 

if i can provide more information helping to resolve the issue, i'm willing to do so. Please tell me, if you need anything.

**Comment by SukramJ** [comment]
In diesem Fall war es eine Fehlkonfiguration der Integration.
Das Ticket kann hier geschlossen werden.
