### ISSUE TITLE
Entering a Program name/title shows internal code and destroys the name

### ISSUE THREAD

**Issue by Shaker1978** [jens-maus/RaspberryMatic#2206]
### Describe the issue you are experiencing

The name of a program contains some internal code after editing.

### Describe the behavior you expected

After editing, the name looks like this:
![grafik](https://user-images.githubusercontent.com/25076389/217016219-637a0c6c-7f0b-40be-bf04-a6434cc3fe3d.png)

### Steps to reproduce the issue

1. Go to "Programme und Verknüpfungen" -> "Programme und Zentralenverknüpfungen"
2. Edit or create a program
3. Edit the name and leave the field.

### What is the version this bug report is based on?

3.67.10.20230114

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
N/A
```

**Comment by jens-maus** [comment]
Sorry, but where is the reproducible description? All I can see in your screenshot is an obvious error which might be caused to some internal caching being broken, thus outputing some internal Rega code here. Is this actually reproducible for you in some way? That means, perform a fresh reboot and try to reproduce again. If not, and the issue is gone after a reboot my guess is that this might be related to #1467.

**Comment by Shaker1978** [comment]
It is reproducible, as I wrote under "Steps to reproduce the issue" according to the bug report template. Only these 3 steps are necessary, and the problem remains even after a fresh restart. I've just tried it.

**Comment by Baxxy13** [comment]
I cannot reproduce this.
![GIF 07 02 2023 16-02-25](https://user-images.githubusercontent.com/54898249/217282250-fe726be6-5033-4554-9fe2-f9431e4ed032.gif)

**Comment by jens-maus** [comment]
> I cannot reproduce this.

Me neither. I really think that this is a pure local issue @Shaker1978 which could point at some broken rootfs installation. So please try to reinstall and use a new/fresh SD card.

**Comment by Shaker1978** [comment]
Damn... thank you. I hope restoring my backup in a fresh installation doesn't include the error again, but I will try!
