### ISSUE TITLE
node.js has no available internationalization (icu/unicode) support.

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#2212]
Das bedeutet das die Node.JS VErsion die auf dem Host ist nicht mit Unicode support für Regex gebaut wurde. Das benmtigt ioBroker aber. Bitte Issue bei Raspberrymatic anlegen das dort eine "korrekte" Nodejs verison genutzt wird.

_Originally posted by @Apollon77 in https://github.com/zautrix/hm-iobroker/issues/9#issuecomment-1423794903_

**Comment by jens-maus** [comment]
Folgende Tests bestätigen das wohl der libicu support nicht korrekt ist (wohl weil die libicu nicht auch kompiliert wird):

```
root@homematic-raspi2:~# node 
Welcome to Node.js v16.18.1.
Type ".help" for more information.
> typeof Intl === 'object';
false
> typeof process.versions.icu === 'string';
false
```

Auf einem standard Ubuntu Linux wird beides mit `true` ausgegeben. Folglich scheint hier also in der Tat etwas zu fehlen (vmtl. die `libicu`).

**Comment by Apollon77** [comment]
ja "icu" kommt mir aus vergangenen Threads dazu bekannt vor ...  Am Ende kannst Du mit der Regex prüfen die beim anderen Issue zum Fehler führt wo unicode charranges drin sind. Ich erinner emkich dunkel das man da "nur" ein compile flag setzen muss und die lib da haben muss. Aber mehr details weiss ich gerade nicht mehr, sorry
