### ISSUE TITLE
Nach Update von 3.65.11.20221218 nach 3.67.10.20230114 wird die HB-RF-ETH nicht mehr erkannt

### ISSUE THREAD

**Issue by marc965** [jens-maus/RaspberryMatic#2219]
### Describe the issue you are experiencing

Home Assistant 2023.2.5
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

After update from 3.65.11.20221218 to 3.67.10.20230114  HB-RF-ETH is not recognized anymore.

no RF Hardware recognized. HmRF: n/a ok HmIP: n/a ok

### Describe the behavior you expected

Thats normal behavior:

Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.5, OK
Identifying Homematic RF-Hardware: ......HmRF: RPI-RF-MOD/HB-RF-ETH@192.168.133.110, HmIP: RPI-RF-MOD/HB-RF-ETH@192.168.133.110, OK
Updating Homematic RF-Hardware: RPI-RF-MOD: 4.4.22, not necessary, OK

### Steps to reproduce the issue

1. installing 3.67.10.20230114: nothing works, no RF Hardware found
2. revert to 3.65.11.20221218, RF Hardware ok

Ich kann das leider nicht wiederholen.
Habe nur das eine Produktivsystem.
Die Heizungssteuerung ist komplett ausgefallen...
Die Anlage läuft schon seit über einem Jahr tadellos.
Das war der erste Ausfall bisher.

### What is the version this bug report is based on?

3.67.10.20230114

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Das ist das log wenn alles läuft:
Mounting /data as /usr/local (Home Assistant Add-On): OK
Identifying host system: oci, OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.5, OK
Identifying Homematic RF-Hardware: ......HmRF: RPI-RF-MOD/HB-RF-ETH@192.168.133.110, HmIP: RPI-RF-MOD/HB-RF-ETH@192.168.133.110, OK
Updating Homematic RF-Hardware: RPI-RF-MOD: 4.4.22, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting sshd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: .......OK
Starting rfd: .OK
Starting HMIPServer: ........................OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.65.11.20221218 (raspmatic_oci_amd64)
```

### Additional information

Habe leider kein Log wenn es nicht funktioniert.
Muss mal das Wochenende abwarten...vielleicht liefere ich das nach.

**Comment by jens-maus** [comment]
Existiert das Problem noch mit der aktuellsten RaspberryMatic Version?

**Comment by marc965** [comment]
> Existiert das Problem noch mit der aktuellsten RaspberryMatic Version?

Ich warte noch bis es wieder etwas wärmer über Nacht wird, habe leider kein Testsystem. Bis das wieder läuft ist echt langwierig...
Melde mich wieder.
Muss das mit der Family klären.

**Comment by marc965** [comment]
Hallo Jens!

Hab jetzt die neue Version drauf(3.67.10.20230225).

Musste zwar die ganze Maschine neu starten, aber jetzt geht alles. Home Assistant Core hat nicht gereicht, musste das Betriebssystem booten.

Läuft jetzt 5h stabil. Danke.

Viele Grüße
