### ISSUE TITLE
WebUI: Provide functionality to prevent service messages for certain devices.

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#222]
If devices are temporarily not required it would be a good idea to be able to select these devices as "inactive" so that service messages are completely suppressed for these devices. Otherwise service and alarm messages are being issued for these "on-hold" devices.

This would probably require changes to ReGaHss as well as the WebUI.

**Comment by fabz5** [comment]
+1.
I also would like have to this. Really useful for the devices which one uses for the christmas lighting.

**Comment by mike-bee** [comment]
Same here: is a perfect idea for e.g. garden eqipment removed in Winter. I have been advised by EQ-3 to remove the devices from the CCU temporarily and teach again when used again, but decided to waste an outlet in my cellar to connect it as dummy.

**Comment by jp112sdl** [comment]
+1
Would be great for reasons like @fabz5 and @mike-bee mentioned!

**Comment by FraatRamski** [comment]
I also would like to see this!

**Comment by Norbl** [comment]
+1 super Idee, finde ich eine tolle Funktion, die ich sehr gut nutzen könnte.

**Comment by nowev** [comment]
+1 Warum auch immer diese Funktion nicht von Anfang an enthalten ist? Sollte natürlich sofort umgesetzt werden!

**Comment by gerassimo** [comment]
ja bitte!

**Comment by Baenker** [comment]
+1

**Comment by darkiop** [comment]
+1

**Comment by loewi1979** [comment]
+1 Super Idee. Gerade für Ersatz-Geräte oder auch der Steckdosen-Aktor für die Weihnachtsbeleuchtung, oder Heizungs-Umwälzpumpen, welche über den Sommer "offline" sind oder oder oder...

**Comment by jens-maus** [comment]
voila, finally had the time to work out a solution for this long standing issue in being able to disable service messages for an individual device. With the next RaspberryMatic update a user can disable service message for each device and thus silent a device over a certain season.

**Comment by FraatRamski** [comment]
This is great, the winter is coming and I have a lot of devices in the garden which I need to power down. Thanks!

**Comment by jens-maus** [comment]
@FraatRamski That's why I have implemented it for myself and share it with you guys :) Note, however, that this will silence ALL service messages including Sabotage, LOWBAT, etc. Apart from that anything else still continues to work (e.g. RSSI display, Status display in Einstellungen->Geräte, etc.).

**Comment by picoflops** [comment]
Where can we find this feature in the actual release?

**Comment by jens-maus** [comment]
@picoflops In each device settings dialog there is a "Servicemeldungen" checkbox which you can uncheck to let the WebUI ignore any service message for this particular device.

And BTW: This is NO support/discussion fora but a bug/issue tracker! So please use the homematic-forum.de in future to ask such questions, please!

**Comment by Mercur13** [comment]
ok, the checkbox "Servicemeldungen" is unchecked. No Service-Meldung on the screen. But the Info-LED flashes the hole time !
