### ISSUE TITLE
Home Assistant Add-on

### ISSUE THREAD

**Issue by detLAN** [jens-maus/RaspberryMatic#2221]
### Describe the issue you are experiencing

- Unter "Direkte Verknüpfungen" gibt es ein Problem mit den deutschen Sonderzeichen.
![SCR-20230216-mhj](https://user-images.githubusercontent.com/64675966/219413656-a66ba0ad-4bda-4338-a9d5-f13f286c55d9.jpg)
- Nagware "CloudMatic" nach reboot wieder da.

### Describe the behavior you expected

Ich migriere meine CCU gerade von meinem RaspberryPi4 auf meine RackStation in Home Assistant (oci_amd64) - Gerät auf RaspberryPi4 ablernen und auf RackStation wieder anlernen.
Dabei ist mir aufgefallen, dass alte RaspberryMatic Probleme, welcher unter RaspberryPi4 behoben wurden, offensichtlich in der OCI Variante noch bestehen.
- Unter "Direkte Verknüpfungen" gibt es Probleme mit den deutschen Sonderzeichen in den Feldern "Verknüpfung Name / Beschreibung".
- Die Nagware "CloudMatic" habe ich deinstalliert, jedoch nach einem reboot ist diese unter OCI wieder da, unter RaspberryPi4 wurde das Problem vor einiger Zeit behoben.

### Steps to reproduce the issue

Siehe Beschreibung

### What is the version this bug report is based on?

3.67.10.20230114

### Which base platform are you running?

oci (Open Container Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
nein
```

### Additional information

Altes System:
![SCR-20230216-mvc](https://user-images.githubusercontent.com/64675966/219412895-a485d59e-1359-4972-84b3-d84a53d6d4ea.jpg)
Neues System:
![SCR-20230216-mvq](https://user-images.githubusercontent.com/64675966/219412962-0015651d-c40b-4fc5-8663-a17e7a24ce6d.jpg)

**Comment by Baxxy13** [comment]
A: Das Umlaut-Problem wurde erst mit Nightly 3.67.10.20230116-dbe8c31 behoben, ist also in deiner Version "normal".
B: Es gibt keinen ("offiziellen") Weg Cloudmatic zu deinstallieren. 

Du müsstest also erstmal darlegen wie du das gemach hast.

Das RM-HA-AddOn ist ein Docker Container. 
Jegliche Änderungen außerhalb des /userfs sind nur temporär, also nach einem Reboot wieder weg.
(einer der Gründe warum ich kein Fan des RM_HA-AddOn's bin)

**Comment by detLAN** [comment]
> A: Das Umlaut-Problem wurde erst mit Nightly 3.67.10.20230116-dbe8c31 behoben, ist also in deiner Version "normal". B: Es gibt keinen ("offiziellen") Weg Cloudmatic zu deinstallieren.
> 
> Du müsstest also erstmal darlegen wie du das gemach hast.
> 
> Das RM-HA-AddOn ist ein Docker Container. Jegliche Änderungen außerhalb des /userfs sind nur temporär, also nach einem Reboot wieder weg. (einer der Gründe warum ich kein Fan des RM_HA-AddOn's bin)
> 
> Also ist A ein Duplikat von #2160 und B mit ziemlicher Sicherheit kein Bug.

Wie ich geschrieben habe, wird die Nagware nach Deinstallation  **unter RaspberryPi4 bei einem reboot nicht neu installiert**. Die Deinstallation sieht wie folgt aus:
 
`mount -o remount,rw /`
`rm -r /opt/mediola/`
`rm -r /opt/mh/`
`rm -r /usr/local/etc/config/addons/mh/`
`rm -r /usr/local/etc/config/addons/www/mh`
`rm -r /etc/init.d/S97NeoServer`
`rm -r /etc/init.d/S97CloudMatic`
`rm -r /etc/config/hm_addons.cfg`
`cp /etc/config/hm_addons.cfg.SICHERUNG /etc/config/hm_addons.cfg`
`rm -r /root/.ash_history`
`mount -o remount,ro /`

**Comment by jens-maus** [comment]
Kann ich nicht verstehen warum
Man diesen aufwand für etwas treibt das standardmäßig abgeschalten ist, keinerlei Ressourcen frisst und nur dasitzt und wartet für den fall der fälle wenn man es ggf doch braucht...

Auch jeden fall ist dieses Ticket hier ja bereits abgefrühstückt wie @Baxxy13 ja bereits dargelegt hat und dies hier ja kein Diskussionsforum ist.

**Comment by detLAN** [comment]
> Kann ich nicht verstehen warum Man diesen aufwand für etwas treibt das standardmäßig abgeschalten ist, keinerlei Ressourcen frisst und nur dasitzt und wartet für den fall der fälle wenn man es ggf doch braucht...

Deine Einstellung hierzu ist bekannt. Nichts desto trotz verhalten sich die genannten Versionen unterschiedlich!

**Comment by Baxxy13** [comment]
Du verstehst das nicht, oder nicht richtig.

Stell dir das AddOn als Software vor die von CD gestartet wird, nen Live-Linux z.B. 
Da kannst du auch alles mögliche machen (z.B. die Sprache auswählen) aber nach einem Neustart ist alles wieder weg und default. Eben weil man auf eine normale CD nix schreiben kann. 
So ist das auch bei Docker-Containern. Es wird beim jedem Start einfach das Container-Image geladen.
Änderungen am Container-Image sind nicht vorgesehen. 

Nutzt man z.B. irgend eines der HB-Devices-AddOn's für RaspberryMatic (für die Selbstbau-Geräte) so wird die RaspberryMatic bei jedem (neu)Start auf's neue gepatcht. Eben weil das Container-Image immer wieder "jungfräulich" ist. 
Unschön, aber so ist es nun mal. 

Kleiner Auszug von: [wie-funktionieren-docker-container](https://www.claranet.de/blog/wie-funktionieren-docker-container)

**Es sollten keine Nutzdaten, also persistente Daten im Container gespeichert werden. Container sind nämlich standardmäßig als „Immutable Infrastructure“ zu verstehen. Das heißt, dass sie nur so lange existieren wie sie etwas tun. Beim Beenden bzw. beim Neu-Deployment verschwinden auch alle Daten die innerhalb der Laufzeit erzeugt wurden. Entsprechend muss für Nutzdaten ein externes, persistentes Volume verwendet werden.**

**Comment by detLAN** [comment]
> Du verstehst das nicht, oder nicht richtig.

Vielen Dank, dass Du gewillt bist zu helfen, zu unterstützen 🤗
Ich kann nachvollziehen was Du sagen willst. Was mich jedoch wundert - wenn ich den vorinstallierten NeoServer lösche, dann bleibt dieser gelöscht. CloudMatic ist doch auch nix anderes als eine Zusatzsoftware, nur mit dem Unterschied, dass im Image eine automatische Installation inbegriffen ist. Warum kann diese Installationsroutine nicht einfach aus dem Image entfernt werden, so die in den anderen Images wie z.B. beim RaspberryPi4.
