### ISSUE TITLE
Raspberrymatic as HomeMatic-Addon kills zigbee communications (zigbee2mqtt)

### ISSUE THREAD

**Issue by matmoeh** [jens-maus/RaspberryMatic#2225]
### Describe the issue you are experiencing

After moving raspberrymatic to HomeAssistant, i noticed that my zigbee devices arent working.

Start raspberrymatic addon after zigbee2mqqt: zigbee stops working. In zigbee2mqtt it shows: sendZclFrameToEndpointInternal error
Start zigbee2mqtt addon after raspberrymatic addon already startet: zigbee2mqtt does not boot. Opening in homeassistant shows: 502: Bad Gateway

### Describe the behavior you expected

raspberrymatic should not affect other addons in homeassistant

### Steps to reproduce the issue

1. Install zigbee2mqtt
2. install raspberrymatic
3. maybe have problems?

### What is the version this bug report is based on?

3.67.10.20230114

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
I have one clue what could couse this problems.
Maybe raspberrymatic are trying to use/connect/break the USB Connection of the SkyConnect USB-Stick?
Im using HB-RF-ETH to connect the radiointerface to raspberrymatic
Homeassistant supervised in Proxmox

zigbee2mqtt Log stops at: Zigbee2MQTT:info  2023-02-19 21:49:46: zigbee-herdsman started (resumed)
... then it freezes

The next log line should be the info about the coordinator/USB-Stick
Zigbee2MQTT:info  2023-02-19 21:49:46: Coordinator firmware version: '{"meta":{"maintrel":"1 ","majorrel":"7","minorrel":"1","product":9,"revision":"7.1.1.0 build 273"},"type":"EZSP v9"}'

Is it possible to "deactive USB" in raspberrymatic?
```

**Comment by jens-maus** [comment]
This is certainly the same root cause like here:

https://github.com/jens-maus/RaspberryMatic/discussions/2182

Thus, definitly no bug/issue in RaspberryMatic itself. Next time please use the discussion fora as well.
