### ISSUE TITLE
Nach Neustart sind die Heizungen auf OFF

### ISSUE THREAD

**Issue by cblochi** [jens-maus/RaspberryMatic#2235]
### Describe the issue you are experiencing

Ich nutze Raspberrymatic als Homeassistant Integration auf esxi.

Wenn ich Raspberrymatic neu starte oder Update installieren, dann sind danach meine Heiz-Gruppen auf 0FF gestellt. 
Die Automatisch Steuerung erfolgt über Raspberrymatic.

### Describe the behavior you expected

Ich würde erwarten, dass der vorherige Zustand erhalten bleibt.

### Steps to reproduce the issue

1. Neustart Raspeberrymatic

### What is the version this bug report is based on?

3.67.10.20230225

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
13:47:04	26.02.2023	Heizung Küche:1	
Auto mode, Actual temperature 20.20°C, Setpoint temperature 20.00°C, Holiday temperature 5.00°C, Holiday start time 0minutes, Holiday start day 1day, Holiday start month 1month, Holiday start year 0year, Holiday end time 0minutes, Holiday end day 1day, Holiday end month 1month, Holiday end year 0year
13:47:13	26.02.2023	Heizkörper Arbeitszimmer:4	
Manu mode, no error, Battery status 2.50V, Valve position 0%, Boost state 0min, Actual temperature 20.80°C, Setpoint temperature 4.50°C, Holiday temperature 5.00°C, Holiday start time 0minutes, Holiday start day 1day, Holiday start month 1month, Holiday start year 0year, Holiday end time 0minutes, Holiday end day 1day, Holiday end month 1month, Holiday end year 0year


13:47:28	26.02.2023	Heizkörper Bad:4	
Manu mode, no error, Battery status 2.40V, Valve position 0%, Boost state 0min, Actual temperature 20.80°C, Setpoint temperature 4.50°C, Holiday temperature 5.00°C, Holiday start time 0minutes, Holiday start day 1day, Holiday start month 1month, Holiday start year 0year, Holiday end time 0minutes, Holiday end day 1day


13:47:28	26.02.2023	Heizkörper Bad:4	
Holiday end month 1month, Holiday end year 0year


13:47:56	26.02.2023	Heizung Kinderzimmer:1	
Manu mode, Actual temperature 20.90°C, Setpoint temperature 4.50°C, Holiday temperature 5.00°C, Holiday start time 0minutes, Holiday start day 1day, Holiday start month 1month, Holiday start year 0year, Holiday end time 0minutes, Holiday end day 1day, Holiday end month 1month, Holiday end year 0year


13:47:57	26.02.2023	HM-ES-PMSw1-Pl OEQ0768721:2	
Energy counter device 12834.60Wh, Power 0.00W, Current 0.00mA, Voltage 226.10V, Frequency 50.01Hz


13:48:19	26.02.2023	Heizung Kinderzimmer:1	
Manu mode, Actual temperature 21.30°C, Setpoint temperature 4.50°C, Holiday temperature 5.00°C, Holiday start time 0minutes, Holiday start day 1day, Holiday start month 1month, Holiday start year 0year, Holiday end time 0minutes, Holiday end day 1day, Holiday end month 1month


13:48:19	26.02.2023	Heizung Kinderzimmer:1	
Holiday end year 0year


13:48:49	26.02.2023	Heizung Küche:1	
Auto mode, Actual temperature 19.90°C, Setpoint temperature 20.00°C, Holiday temperature 5.00°C, Holiday start time 0minutes, Holiday start day 1day, Holiday start month 1month, Holiday start year 0year, Holiday end time 0minutes, Holiday end day 1day, Holiday end month 1month, Holiday end year 0year
```

**Comment by MichaelN0815** [comment]
Du solltest dir deine Programme ansehen, die die Heizung auf off stellen.

**Comment by cblochi** [comment]
Vielen Dank Michael.

Der Hinweis war nicht schlecht, dort schlummerte tatsächlich noch eine deaktiviertes Program. Erklärt auch, warum nichtg alle Zimmer betroffen waren. Sollte ja aber trotzdem nicht aufregrufen werden sollte, da deaktivert. 

Ich hatte vor Homeassistant eine reine Raspeberrymatic Installation. Ich habe für die Migration das Backup eingespielt, kann mich nicht errinnner, dass das Program dort zu dem Heizungs-OFF Problem geführt hat.

Ich habe das Programm gelöscht, nachdem Neustart tritt das Problem in dem oben genannten Zimmern nicht mehr auf.
Nur meine HmIP Heizgruppen sind jetzt auf OFF, nache einem Neustart.

Also irgendwas passt immer noch nicht. Weitere Programm und Systemvariablen gibt es nicht mehr.

**Comment by Baxxy13** [comment]
Hast du mal bei einem der Gruppengeräte direkt am Gerät geschaut ob es wirklich "off" ist?

Das die WebUI nach Reboot erstmal default Werte anzeigt ist ein alter Hut. Erst wenn sich eins der Thermostate aus der Gruppe "gemeldet" hat ist die WebUI Anzeige wieder korrekt.  Man kann das forcieren indem man die Gruppe "ansteuert".

Siehe auch: [Neue IP-Geräte nach CCU2 Neustart auf "AUS"](https://homematic-forum.de/forum/viewtopic.php?f=34&t=37993&hilit=aus)
