### ISSUE TITLE
HmIP-PSM-2 Entitäten sind in HA nicht vorhanden

### ISSUE THREAD

**Issue by teppic01** [jens-maus/RaspberryMatic#2236]
### Describe the issue you are experiencing

Hallo Zusammen,
ich bin ratlos. Ich habe diverse HM-IP Geräte problemlos laufen. Unter anderem auch HM-IP PSM. Vor einiger Zeit habe ich zwei
neue HM-IP PSM2 problemlos angelernt. Sie sind in Rapsberrymatic vorhanden und funktionieren einwandfrei. Nur sie tauchen in HA nicht auf. Das ist mir erst jetzt aufgefallen. Andere Sensoren lassen sich auch jetzt noch anlernen und sind dann in HA vorhanden. Ein Umbennenen, löschen und neu anlernen der Sensoren hilft auch nicht. Konnte jemand diese Sensoren in HA nutzen oder hat vielleicht einen Tip?
Gruß
T.

### Describe the behavior you expected

Entitäten sollten in HA vorhanden sein.

### Steps to reproduce the issue

1. Neu angelernt, gleiches Ergebnis
2.
3.
...

### What is the version this bug report is based on?

3.67.10.20230225

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
Neuste Hass und HA Version.
```

**Comment by jens-maus** [comment]
Dies ist und wird ein "Problem" der Homematic Integration (https://github.com/danielperna84/custom_homematic) sein. Insofern gehört das problem auch dort reportet, da offensichtlich innerhalb von RaspberryMatic ja alles korrekt funktioniert.
