### ISSUE TITLE
Can't disable automatic update checks

### ISSUE THREAD

**Issue by igotgit** [jens-maus/RaspberryMatic#2245]
### Describe the issue you are experiencing

During every logon my raspberrymatic is connecting to: https://raspberrymatic.de/LATEST-VERSION.js?v=<CurrentVersion>&p=<Platform>

It is blocked by my Browser, since it's a Cross-Site-Request but I'd like to be able to disable it for privacy reasons without modifying the source code.

In Settings > Advanced settings I disabled the obvious options:
* Internet Monitoring
* Security Check
* Check for additional Software updates

### Describe the behavior you expected

I'd appreciate, If there was a button in System Settings like "Disable automatic update Checks"

### Steps to reproduce the issue

1. Open your Browsers Debug Interface
2. Open the Debug Interfaces Network Tab
3. Watch for Calls to https://raspberrymatic.de

### What is the version this bug report is based on?

3.67.10.20230225

### Which base platform are you running?

oci (Open Container Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Will append that if needed
```

**Comment by igotgit** [comment]
A Button for manual update checks would be nice :)

**Comment by jens-maus** [comment]
> During every logon my raspberrymatic is connecting to: https://raspberrymatic.de/LATEST-VERSION.js?v=&p=
> 
> It is blocked by my Browser, since it's a Cross-Site-Request but I'd like to be able to disable it for privacy reasons without modifying the source code.

Please show a screenshot / more info on the actual cross-site-request blocking that takes place. Here I can't see such a cross-site-request blocking taking place with a standard/vanilla RaspberryMatic system. In addition, please tell us in which docker (oci) environment you are actually using RaspberryMatic which could also potentially explain your issues.

**Comment by igotgit** [comment]
Just checked: My previous debmatic installation does the check too. So this is probably rather a feature request than a bug.

Screenshot of blocked update request: https://i.postimg.cc/s2FjLB5H/raspberrymatic-update-check.png

The CSR is blocked by NoScript. When disabling the Firefox Addon, the request is "200 OK"

I'm using podman rootless, so no (yet) supported installation, but I guess that doesn't change the update check behavior.

**Comment by jens-maus** [comment]
> Just checked: My previous debmatic installation does the check too. So this is probably rather a feature request than a bug.

Well, the question is, what kind of feature?!?!

> Screenshot of blocked update request: https://i.postimg.cc/s2FjLB5H/raspberrymatic-update-check.png

Please no external services for image upload, etc. Put your screenshots, etc. right into here.

> The CSR is blocked by NoScript. When disabling the Firefox Addon, the request is "200 OK"

Well, then the "Issue" is, that you are using this "NoScript" Addon which IMHO you should not require. As said, I don't see any issue here with Google Chrome which itself also has enough CSR protections but isn't complaining about anything right now.

**Comment by jens-maus** [comment]
> I have no Idea when and if I can do it but: Would you accept a pull request If I added:
> 
> * A button "Check for update" in Settings > Maintenance nearby the current version that triggers the request that is fired during login
> * A checkbox in Settings > Advanced "Disable automatic update check"

I am not sure if these things are desirable in a brought context. In addition, there are more similar firmware update checks in the WebUI, e.g. a device firmware update check against eq3 server which we do not have control for. Thus, I am really unsure if these changes would not produce more problems than they are trying to solve.

**Comment by jens-maus** [comment]
BTW: I just added a `Access-Control-Allow-Origin` wildcard header to the `LATEST-VERSION.js` resource on the raspberrymatic.de webserver. So please check if your issue should now be solved, thus the Noscript addon not blocking the cross access resource anymore.

**Comment by igotgit** [comment]
Thanks for your quick responses and adding the header The header will be helpful for most people.
If the occu would have to be changed to disable auto update checks I guess it's not worth it.
