### ISSUE TITLE
Vorhandene HMIP-Heizgruppe wird nicht angezeigt

### ISSUE THREAD

**Issue by Good3vil** [jens-maus/RaspberryMatic#2248]
### Describe the issue you are experiencing

Ich habe das Problem, dass eine vorhandene und vorallem funktionierende Heizgruppe nicht mehr angezeigt wird.
Wenn ich in der Gruppenübersicht schaue bekomme ich drei Gruppen angezeigt, aber es müssten vier sein.
INT0000001
INT0000002
INT0000004

Kann sie somit auch nicht löschen und neu anlegen um dem Problem ggf. entgegenwirken zu können.

### Describe the behavior you expected

?

### Steps to reproduce the issue

Kann ich nicht.

### What is the version this bug report is based on?

3.67.10.20230225

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
.
```

**Comment by Baxxy13** [comment]
Es gibt 3 primäre Stellen an denen man die Gruppengeräte normalerweise zu Gesicht bekommt.

- Einstellungen > Gruppen
- Einstellungen > Geräte
- Status und Bedienung > Geräte

Fehlt deine Gruppe überall?

Auf Dateiebene (ssh / winscp) findet man in `/usr/local/etc/config` normalerweise Dateien nach dem Schema: `INT0000001`, die enthalten die Einstellungen von IP-Gruppen.
Dann gibt es im selben Verzeichnis noch die `groups.gson`, die sollte alle Gruppen (HM/IP) enthalten.
Wenn du da dran kommst dann guck mal rein.

Mit dem SDV aus dem Homematic-Forum kann man auch prüfen was da ist und was nicht.

**Comment by Good3vil** [comment]
In diesen drei Rubriken ist die eine Gruppe nicht zu sehen. 
Wenn ich aber einen neue Gruppe anlegen möchte mit den dazugehörigen HMIP Produkten, wird mir angezeigt, dass sich diese bereits in einer Verknüpfung befinden zudem eine neue Gruppe zu INT0000005 statt die INT0000003 zu "füllen".

Nutze am Handy PocketControl und dort kann ich die Temperatur verstellen die in der Heizgruppe drin sind/sein sollten.

Unter /usr/local/etc/config gibt es nur die drei aufgeführten 
INT0000001
INT0000002
INT0000004

Somit fehlt auch hier die INT0000003.

In der Datei groups.gson bekomme ich viel kuddelmudel angezeigt, aber sowei ich das sehe existiert hier nur INT000001 + 2 (keine Linuxkenntnisse)

Sehe gerade in den Direktverknüfungen, dass es hier auch keine INT000003 gibt. Allerdings wurden die Heizkreise die eigentlich in der INT3 sein sollten dort verknüpft. Bin mir aber zu 100% sicher, dass ich eine Heizgruppe erstellt habe.

Dann lösche ich die Verknüpfung mal und erstelle eine neue Gruppe. 

Aber warum ist dann die INT000003 "verschwunden" und wird nicht neu angelegt?

**Comment by Good3vil** [comment]
Habe die Verknüpfungen löschen können und habe eine neue Heizgruppe angelegt.
Habe jetzt 
INT0000001
INT0000002
INT0000004
INT0000006

Warum die Gruppe nun weg war ist und bleibt mir ein Rätsel, aber sei es drum.
Ab der Bug letztenlich evtl. doch bei mir Lag
