### ISSUE TITLE
HM Classic Heizungsgruppen Settings speichern schlägt fehl.

### ISSUE THREAD

**Issue by eli4711** [jens-maus/RaspberryMatic#2265]
### Describe the issue you are experiencing

HM Heizungsgruppen lassen sich nicht mehr einstellen. 

Bei klicken auf OK oder Übernehmen gibt es die untenstehende Fehlermeldung in den Chrome Entwicklertools.

![HM_Heating](https://user-images.githubusercontent.com/40276118/226115726-e1675aa6-1676-4ed6-bc5a-afc5ce3df5f6.gif)

### Describe the behavior you expected

Einstellungen werden gespeichert. Wie bei HMIP.

![HMIP_Heating](https://user-images.githubusercontent.com/40276118/226118552-b9f93498-08ce-4635-8cdd-e5d4dd425e4c.gif)

### Steps to reproduce the issue

1.
2.
3.
...

### What is the version this bug report is based on?

3.69.3.20230318

### Which base platform are you running?

intelnuc (intel NUC)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
HTML Dev Tools ausgabe

4webui.js:45571 Uncaught TypeError: Cannot read properties of undefined (reading 'typeName')
    at SetParameters (webui.js:45571:18)
    at SaveDeviceParameters (webui.js:45379:5)
    at HTMLDivElement.onclick (index.htm?sid=@SvkrOEVjmc@:1:15)
4webui.js:45571 Uncaught TypeError: Cannot read properties of undefined (reading 'typeName')
    at SetParameters (webui.js:45571:18)
    at SaveDeviceParameters (webui.js:45379:5)
    at HTMLDivElement.onclick (index.htm?sid=@SvkrOEVjmc@:1:15)
```

**Comment by jens-maus** [comment]
Ich hoffe die ist bewusst das du hier ein Problem basierend auf einem nightly snapshot meldest und nicht basierend auf der stable version.

Vielleicht kann @Baxxy13 das mal schnell testen ob das wirklich im aktuellen nightly snapshot nicht geht und ab wann das genau passiert ist?!?

Bitte auch mal in der Browserkonsole schauen ob es da zu irgendwelchen Fehler kommt.

**Comment by eli4711** [comment]
Servus Jens.
Klar ist mir bewusst das es sich um eine non stable Version handelt.
Die Ausgabe der Konsole hängt schon dran. Oder brauchst du noch was anderes? Grüße Thomas

**Comment by jens-maus** [comment]
Ok. konnte es jetzt auch bereits reproduzieren. Siehe:

<img width="1031" alt="Bildschirm­foto 2023-03-18 um 20 53 20" src="https://user-images.githubusercontent.com/5887769/226134718-27ae0ab0-5079-4395-a6a7-787b9f0b6376.png">

Dann muss da eQ3 wohl nochmal Hand anlegen an die 3.69.x weil das wohl erst mit der 3.69.x reingewandert ist und wohl auf die kommende Geräteintegration des neuen `HmIP-DRG-DALI` Gerätes zurückzuführen ist...

**Comment by jens-maus** [comment]
Ok. please test the night upcoming nightly snapshot, since I integrated a fix/workaround in https://github.com/jens-maus/RaspberryMatic/commit/072cf31b06548ed112332c7ef1af18dd911c18d1. And please report back if the issue is not properly solved or other related issues appear.

**Comment by eli4711** [comment]
Thx for the quick sollution. :-)

**Comment by jens-maus** [comment]
Thank you for finding that issue so quickly. Please continue to check the 3.69.x nightlies so that we could potentially identify any further issue before eQ3 officially releases it to the public.

**Comment by eli4711** [comment]
Problem solved. :-) will continue testing.
