### ISSUE TITLE
Programme - Erweiterung Zeitmodul im Bereich Astrofunktiom

### ISSUE THREAD

**Issue by murksmax66** [jens-maus/RaspberryMatic#2267]
### Describe the solution you'd like

Wenn man Geräte zu einem festen Zeitpunkt - z. B. 07:00 Uhr mit der Bedingung "nur vor SA" - schalten will, sollte eine entsprechende Auswahlmöglichkeit vorhanden sein wie bei den Wochenprogrammen bspw. von Schaltsteckdosen, damit das Gerät nicht eingeschaltet wird, wenn der SA vor der Uhrzeit liegt.
Gleiches gilt auch für SU sowie die Zeitpunkte nach SA/SU (siehe Auswahlmöglichkeiten Zeitpunkte im Wochenprogramm).
![C1B0FDF0-C012-4F41-9B19-7636AF643C5A](https://user-images.githubusercontent.com/111336739/226542140-be76cf60-6aa5-451b-8f1e-837074808f34.png)

### Describe alternatives you've considered

Zur Verfügung stellen von Systemvariablen SU/SA, damit die Zeitpunkte direkt abgegriffen werden können.

### Is your feature request related to a problem?

Mit dem ggw. Möglichkeiten muss man Verrenkungen machen, damit die Beleuchtungen u. ä. bei den jahreszeitbedingten Verschiebungen von SA/SU im Grenzbereich sauber geschaltet bzw. vor SU/nach SA nicht  ungewollt aktiviert werden.

**Comment by MichaelN0815** [comment]
Du musst da nichts verrenken. Du "darfst" einfach 2 Zeitmodule sinnig logisch verknüpfen.
