### ISSUE TITLE
Nightly - 3.69.4.20230323 HmIP-WKP keine PIN-Eingabe möglich

### ISSUE THREAD

**Issue by Quarkmax** [jens-maus/RaspberryMatic#2269]
### Describe the issue you are experiencing

Nightly - 3.69.4.20230323 auf PROXMOX 
In den Settings für das Keypad HmIP-WKP kann keine PIN, für jeden Benutzer, hinterlegt werden. Nach dem Öffnen der Einstellungen ist statt des leeren PIN-Feldes dort der Eintrag **name=NUMERIC_CODE** vorgegeben. Mit dem Löschen und Eintragen der PIN mit anschließenden Speichern, wird die PIN nicht übernommen. Es erscheint wieder der Eintrag **name=NUMERIC_CODE**.  Zurück auf die 3.67.10.20230225 ist das Verhalten so, wie es sein soll, die PIN kann gesetzt werden.

### Describe the behavior you expected

Die PIN sollte angenommen werden

### Steps to reproduce the issue

Zurücksetzen auf  3.67.10.20230225 und erneute Update auf Nightly ergab den gleichen Fehler. Wieder zurück auf 3.67.10.20230225 alles normal.

### What is the version this bug report is based on?

3.69.4.20230323 

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
.
```

**Comment by jens-maus** [comment]
@Quarkmax Nun da das aktuellste nightly snapshot auf OCCU 3.69.6 basiert in dem das Problem beseitigt sein sollte würde ich drum bitten dieser version mal bitte einen Test zu unterziehen und hier zurückzumelden ob das Problem nun in der Tat beseitigt wurde.

**Comment by jens-maus** [comment]
@Quarkmax Kannst du mal bitte ein Screencast (animated gif) davon hier zeigen damit man sich ein Eindruck davon machen kann auch wenn man selbst kein HmIP-WKP hat?

**Comment by Quarkmax** [comment]
@jens-maus 
Danke für Deine Nachfrage. Es ist gar kein Anführungszeichen, es sind zwei **Apostrophe**. Sorry.
Und hier der Screencast
![HmIP-WKP](https://user-images.githubusercontent.com/93822511/228877006-146eae8e-3b70-4cb3-9c3e-06aa8fe56667.gif)

**Comment by Quarkmax** [comment]
@jens-maus 
Ja, die beiden `''` sind nur im leeren Feld. Und ja, pro Benutzer einen PIN. Wenn nur vier Benutzer, vergebe ich nur vier PIN. Außerdem müssen/können die Nutzer noch ein Zeitfenster zugeordnet bekommen, also berechtigt sind. Ich habe nicht die maximal mögliche Benutzer/PIN-Anzahl ausgenutzt und es funktioniert. Ich habe jetzt nochmals ein Rollback durch und Update ausgeführt, die Berechtigungen und PIN gesetzt, die Direktverknüpfungen  danach angelegt (wie sonst auch für die Tests). Nutzer 3 und 4 haben sofort funktioniert, Nutzer 7 nicht. Dann beim Nutzer 7 nochmal eine andere PIN neu gesetzt und jetzt ist die Funktion für alle angelegten Nutzer gegeben.  Dachte erst, es liegt daran, weil zwei inaktive Nutzer dazwischen liegen, aber das kann es ja nicht sein.  Lange Rede gar kein Sinn... es funktioniert jetzt. Ich lass die Nightly drauf und beobachte weiter. 

Vielen Dank

**Comment by Quarkmax** [comment]
Korrekt

**Comment by jens-maus** [comment]
@Quarkmax Kannst du bitte mal probieren in der Datei `/www/config/easymodes/etc/uiElements.tcl` auf der Zentrale in Zeile  188 die folgende Änderung umzusetzen:

```diff
- if {[string equal $value ""] == 1} {set value ''}
+ if {[string equal $value ""] == 1} {set value ""}
```

um zu schauen das das `''` dann ggf. Weg ist wenn das Feld leer gelassen wird?

**Comment by Quarkmax** [comment]
@jens-maus 
Die `''` sind weg! Kann die Funktionalität leider  erst morgen testen. Bis dahin...

**Comment by jens-maus** [comment]
So, hab nun noch einen eignen WebUI patch hinzugefügt der das `''` Problem in der Anzeige beseitigen sollte. Bitte mit dem nächsten kommenden nightly snapshot testen ob nun alles wie erwartet funktioniert und gut aussieht.

**Comment by Quarkmax** [comment]
@jens-maus 
Sieht jetzt aus wie vorher und damit gut und alles funktioniert wie erwartet.

Danke
