### ISSUE TITLE
HmIP E-TRV2 Gerätekonfigurationsseite - Maximale Ventilposition für Boostmode fehlt

### ISSUE THREAD

**Issue by MaHe801310** [jens-maus/RaspberryMatic#2270]
### Describe the issue you are experiencing

Hallo, seitdem ich von meinem Uraltbackup auf eine frische Installation umsteigen wollte, musste ich feststellen dass der erwähnte Menüpunkt in den Geräteeinstellungen fehlt und nur noch über die freigeschaltete "DevConfig"-Seite erreichbar ist.

Dies ist mir aber der zugänglichkeit wegen nicht probat.

Eine Gegenprüfung mittels Ursprungsbackup zeigt jedoch diesen Menüpunkt 
sowie ihn auch als konfigurierbar mittels Dropdown an.

Was mir aufgefallen ist, war erst das Fehlen erwähnten Menüpunktes inklusive der Einstelloptionen 
für die Entkalkungsfahrt bis zur Firmware 3.67.10.20230113 bzw. vom Januar 2023.

Nach einem Upgrade dorthin unter einer laufenden Installation waren alle Einstelloptionen
wie gewohnt zur Verfügung.

Ein Freshinstall jedoch führt zu dem erwähnten Issue.

### Describe the behavior you expected

Maximaler Ventilöffnungsgrad für Boostmode sollte direkt über die Gerätekonfigurationsseite einstellbar sein.

### Steps to reproduce the issue

1. CCU3 auf Werkszustand zurücksetzen
2. Umstieg auf Raspberrymatic
3. Aktor zurücksetzen.
4. Aktor neu anlernen
...

### What is the version this bug report is based on?

3.69.4.20230323-1c2c90

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
N/A.
```

### Additional information

Bei Bedarf kann ich mit besagtem Vollbackup zum Beleg aufwarten.

**Comment by Baxxy13** [comment]
Kannst du das präzisieren mit welcher Version was geht und was nicht?
Du erwähnst die alte 3.67.10.20230113 und einen Nightly vom 23.03.

Gut wäre das mit Screenshots zu zeigen. 
Der vereinfachte Modus in der Benutzerverwaltung ist bei beiden Tests deaktiviert?

Ich habe nur ein eTRV-B1 und bei dem sieht es mit Nightly 3.69.4.20230323-1c2c90 (und normalem Modus) so aus.
![eTRV-B1_full-Settings_Ch1_3_69_4](https://user-images.githubusercontent.com/54898249/227766433-691f4898-5709-412d-8773-87b0a3df556c.JPG)

**Comment by MaHe801310** [comment]
`Gut wäre das mit Screenshots zu zeigen.
Der vereinfachte Modus in der Benutzerverwaltung ist bei beiden Tests deaktiviert?`

Asche über mein Haupt. Ich hatte (meine eigentlich) standardgemäß deaktivierte "Einfache Verknüpfungskonfiguration" schlicht und ergreifend vergessen.

![Geräteseite](https://user-images.githubusercontent.com/128842376/227777562-cbc56c1e-6f16-4a6b-a3e9-0a68972d8e8d.jpg)

@Baxxy13 Auf deine Hinweis hin habeich nun das gewünschte Ergebnis erhalten. 

Nur noch die Frage: 
Bei Modus wird aber immernoch trotz erweiterter Verknüpfungskonfiguration "Einfach" angezeigt. (Siehe Screenshot).
Ist das normal ?

**Comment by MaHe801310** [comment]
`Nur noch die Frage:
Bei Modus wird aber immernoch trotz erweiterter Verknüpfungskonfiguration "Einfach" angezeigt. (Siehe Screenshot).
Ist das normal ?`

EDIT: Ab- und wieder Anmeldenhat das Anzeigeproblem gelöst.
<CLOSED>
