### ISSUE TITLE
Nightly - 3.69.6.20230331 HmIP-WRCD gesendeter Text wird nicht übermittelt

### ISSUE THREAD

**Issue by Quarkmax** [jens-maus/RaspberryMatic#2273]
### Describe the issue you are experiencing

Mit der Zeile
```
dom.GetObject("HmIP-RF.002A5F299XXXXX:3.COMBINED_PARAMETER").State("{DDBC=WHITE,DDTC=BLACK,DDI=3,DDA=CENTER,DDS=UNLOCKED ,DDID=3,DDC=true}")
```
kann im DANN-Zweig eines Programmes Text (im Beispiel an Zeile 3 des Displays) gesendet werden. In der Nightly - 3.69.6.20230331 und Nightly - 3.69.4.20230323 wird kein Text übermittelt. LOG-Eintrag siehe unten. Rollback auf Stable 3.67.10.20230225 ist das Verhalten so, wie erwartet, der Status/Text wird übermittelt.
Edit:
Das Falsch-Verhalten tritt auch bei der Konfiguration über die Display-Konfigurationseite auf. Siehe zweiten LOG-Eintrag

![HmIP-WRCD](https://user-images.githubusercontent.com/93822511/229136170-35a76d9a-4b6b-427c-be40-efaa64daeb99.gif)

### Describe the behavior you expected

DIe Statuszeilen sollten übermittelt werden

### Steps to reproduce the issue

Zurücksetzen auf 3.67.10.20230225 und erneute Update auf Nightly - 3.69.6.20230331 oder  Nightly - 3.69.4.20230323 ergab den gleichen Fehler. Wieder zurück auf 3.67.10.20230225 alles normal.

### What is the version this bug report is based on?

 3.69.6.20230331

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Mar 31 14:29:10 raspberrymatic local0.warn ReGaHss: WARNING: XMLRPC 'setValue': rpcClient.isFault() failed (url: xmlrpc://127.0.0.1:32010, params: {"002A5F299XXXXX:3","COMBINED_PARAMETER","{DDBC=WHITE,DDTC=BLACK,DDI=3,DDA=CENTER,DDS=UNLOCKED,DDID=3,DDC=true}"}, result: [faultCode:-321,faultString:"Dangling meta character '?' near index 0\x0a??\x0a^"]) [CallXmlrpcMethod():iseXmlRpc.cpp:2618]
Mar 31 14:29:10 raspberrymatic local0.err ReGaHss: ERROR: XMLRPC 'setValue' call failed (interface: 1009, params: {"002A5F299XXXXX:3","COMBINED_PARAMETER","{DDBC=WHITE,DDTC=BLACK,DDI=3,DDA=CENTER,DDS=UNLOCKED,DDID=3,DDC=true}"}) [CallSetValue():iseXmlRpc.cpp:1515]
Mar 31 14:29:10 raspberrymatic local0.err ReGaHss: ERROR: rpc.CallSetValue failed; address = 002A5F299XXXXX:3 [WriteValue():iseDOMdpHSS.cpp:76]
_________________________________________________
2. LOG
Mar 31 15:33:59 raspberrymatic local0.warn ReGaHss: WARNING: XMLRPC 'setValue': rpcClient.isFault() failed (url: xmlrpc://127.0.0.1:32010, params: {"002A5F299XXXXX:3","COMBINED_PARAMETER","{DDBC=WHITE,DDTC=BLACK,DDI=0,DDA=CENTER,DDS=locked,DDID=3,DDC=true}"}, result: [faultCode:-321,faultString:"Dangling meta character '?' near index 0\x0a??\x0a^"]) [CallXmlrpcMethod():iseXmlRpc.cpp:2618]
Mar 31 15:33:59 raspberrymatic local0.err ReGaHss: ERROR: XMLRPC 'setValue' call failed (interface: 1009, params: {"002A5F299XXXXX:3","COMBINED_PARAMETER","{DDBC=WHITE,DDTC=BLACK,DDI=0,DDA=CENTER,DDS=locked,DDID=3,DDC=true}"}) [CallSetValue():iseXmlRpc.cpp:1515]
Mar 31 15:33:59 raspberrymatic local0.err ReGaHss: ERROR: rpc.CallSetValue failed; address = 002A5F299XXXXX:3 [WriteValue():iseDOMdpHSS.cpp:76]
```

**Comment by jp112sdl** [comment]
Das Problem kommt vom HMIPServer.
Das, was da geändert wurde, hat definitiv niemand getestet.

Spoiler: Das Problem betrifft auch Akustik-Signalgeber.

**Comment by friedpa** [comment]
Bei mir geht auch nicht der Textübertrag auf den WRCD mittels dem Combined_Parameter. Ist das auch eine Folge des Bugs?

**Comment by jens-maus** [comment]
> Bei mir geht auch nicht der Textübertrag auf den WRCD mittels dem Combined_Parameter. Ist das auch eine Folge des Bugs?

Ja. Entweder downgrade auf 3.67.x oder auf den entsprechenden Fix durch eQ3 warten.

**Comment by FrankGiesecke** [comment]
Ich habe auf mein Ticket bei eQ3 Rückmeldung erhalten.

> Das beschriebene Verhalten wird in Verbindung mit der kommenden CCU3 Firmware (Version 3.69.7) korrigiert. Bis zur Veröffentlichung des Updates bitten wir Sie jedoch noch um etwas Geduld. Alternativ lässt sich solange auch die vorherige Firmwareversion 3.67.10 verwenden.

**Comment by CirculusVitiosus** [comment]
Wir haben 3xWRCD in Betrieb. Bei allen ist das beschriebene Verhalten zu beobachten. Allerdings sind bei uns nur die Zeilen 1, 4 und 5 betroffen. Bei den Zeilen 2 und 3 funktioniert die Textübertragung wie vor dem Update.

**Comment by jens-maus** [comment]
Im nächsten kommenden nightly snapshot der auf OCCU 3.69.7 basiert sollte das Problem nun behoben sein. Interessierte können das bitte entsprechend testen.

**Comment by StClaus63** [comment]
I just have installed the nightly snapshot based on OCCU 3.69.7 and my two HmIP-WRCDs are working fine again.
Many thanks for your effort to solve this issue

**Comment by friedpa** [comment]
Did also install the nightly snapshot based on OCCU 3.69.7 and I can confirm the snapshot is also working on my system. Thanks for the quick fix!
