### ISSUE TITLE
Übersetzungsfehler (englisch)  - Experimental Nightly Build

### ISSUE THREAD

**Issue by andrzejgilas** [jens-maus/RaspberryMatic#2275]
### Describe the issue you are experiencing

der letzte RaspberryMatic-**3.69.6.20230402-edc442-rpi3** Nightly Build enthält einen Übersetzungsfehler: 
![2023-04-02 05 06 44](https://user-images.githubusercontent.com/81189856/229329128-aedfc15b-c803-4918-adba-d285ad132d02.jpg)

### Describe the behavior you expected

...

### Steps to reproduce the issue

RaspberryMatic-3.69.6.20230402-edc442-rpi3 installieren und Sprache auf Englisch umstellen
Home page > Settings > Control panel > network settings

### What is the version this bug report is based on?

RaspberryMatic-3.69.6.20230402-edc442-rpi3

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
...
```

### Additional information

...

**Comment by jens-maus** [comment]
fixed in 470b411b317a009cfd076dbeb758ec5660235a6f
