### ISSUE TITLE
Setzen von Raum&Gewerk für alle Kanäle eines Geräts

### ISSUE THREAD

**Issue by TinkyWonky** [jens-maus/RaspberryMatic#2284]
### Describe the solution you'd like

Beim Einrichten eines Gerätes dürfen / müssen die Einstellungen „Raum” und „Gewerk” für jeden Kanal einzeln eingestellt werden. Das kann je nach Anzahl der Geräte recht mühselig werden.

Als Nutzer der Attribute „Raum” und „Gewerk” wünsche ich mir eine Möglichkeit, diese für alle Kanäle eines Gerätes setzen zu können -- analog zum Umbenennen aller Kanäle.

### Describe alternatives you've considered

- Alle Kanäle einzeln einrichten.
- Die Attribute nicht  nutzen.

### Is your feature request related to a problem?

Nein.

**Comment by jp112sdl** [comment]
Schneller geht es, wenn du Einstellungen->Räume öffnest _(, ggf. einen Filter setzt )_ und vorne in der ersten Spalte die Haken der Kanäle setzt

**Comment by mbhomie007** [comment]
Hatte ich mir auch mal gewünscht. 
Hier: #1066

**Comment by TinkyWonky** [comment]
Uh. Hatte ich nicht gefunden. Mea culpa!

**Comment by TinkyWonky** [comment]
duplicates https://github.com/jens-maus/RaspberryMatic/issues/1066
