### ISSUE TITLE
Gesetztes Sessiontimeout wird nicht in GUI angezeigt

### ISSUE THREAD

**Issue by Maik2208** [jens-maus/RaspberryMatic#2288]
### Describe the issue you are experiencing

Das in der Systemsteuerung --> Sicherheit --> Timeout gesetzte Sessiontimeout wird dort nach dem Speichern nicht angezeigt:
![image](https://user-images.githubusercontent.com/79879510/231529447-780747e6-51cc-46bd-af91-6aba2d353c2e.png)

### Describe the behavior you expected

Gesetztes Timeout wird nach dem Aufruf der Seite angezeigt.

### Steps to reproduce the issue

1. Systemsteuerung --> Sicherheit aufrufen
2. Timeout setzen und speichern
3. Seite erneut aufrufen
4. Wundern, dass nichts zu sehen ist

### What is the version this bug report is based on?

3.69.6.20230407

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
n/a
```

**Comment by jp112sdl** [comment]
Puh... Weniger ein Bug, eher ein Feature Request. 😄 

Den gesetzten Wert dort anzuzeigen ist gar nicht implementiert und war es auch m.W. in der Vergangenheit nicht.
