### ISSUE TITLE
RaspberryMatic hangs after upgrade

### ISSUE THREAD

**Issue by the78mole** [jens-maus/RaspberryMatic#2293]
### Describe the issue you are experiencing

After an upgrade to the latest release on my Pi, the system was stuck and only the "Wait for start" web UI was shown, even if I waited the whole night. After a few restarts, I looged in with SSH and killed the eq3configcmd processes after waiting quite some time in the hope that one of it completes:

```
/bin/eq3configcmd update-coprocessor -lgw -u -rfdconf /etc/config/rfd.conf -l 1
/bin/eq3configcmd update-lgw-firmware -m /firmware/fwmap -c /etc/config/rfd.conf -l 1
```

and after killing that, the system boots, but (not suprisinlgy), no devices are shown. Content of `/var/status` is as follows:

```
-rw-r--r--    1 root     root             0 Jan  1  1970 SDinitialised
-rw-r--r--    1 root     root             0 Jan  1  1970 USBinitialised
-rw-r--r--    1 root     root             0 Jan  1  1970 hasIP
-rw-r--r--    1 root     root             0 Jan  1  1970 hasInternet
-rw-r--r--    1 root     root             0 Jan  1  1970 hasLink
-rw-r--r--    1 root     root             0 Apr 16 11:58 hasNTP
-rw-r--r--    1 root     root             0 Jan  1  1970 hasSD
-rw-r--r--    1 root     root             0 Jan  1  1970 hasUSB
-rw-r--r--    1 root     root             4 Apr 16 12:12 multimacd.status
```

### Describe the behavior you expected

I expect, the system boots up regularly.

### Steps to reproduce the issue

1. Did an upgrade from a version a few month ago with with `Zentralenwartung -> Automatisches Update durchführen`.
2. Watched the update progress
3. After restart has competet, the system was hanging
4. Some restart tries (also `reboot` did only execute when killing the above processes
5. Installed the update again (also with `Zentralenwartung -> Automatisches Update durchführen`)
6. Same problem

### What is the version this bug report is based on?

3.69.6.20230407 (rpi3)

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
/var/log/messages:

Jan  1 01:00:14 localhost kern.info kernel: [   14.601489] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
Jan  1 01:00:14 localhost kern.warn kernel: [   14.603060] brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43455-sdio.raspberrypi,3-model-b-plus.bin failed with error -2
...
Apr 16 11:58:41 homematic-ccu2 daemon.err xinetd[1330]: Unable to read included directory: /etc/config/xinetd.d [file=/etc/xinetd.conf] [line=14]
...
Apr 16 11:58:42 homematic-ccu2 user.info root: Updating RF Lan Gateway Coprocessor Firmware
Apr 16 11:58:42 homematic-ccu2 user.debug update-coprocessor: firmware filename is: coprocessor_update_hm_only.eq3
[...killing process /bin/eq3configcmd update-coprocessor -lgw -u -rfdconf /etc/config/rfd.conf -l 1...]
Apr 16 12:12:11 homematic-ccu2 user.info root: Updating RF Lan Gateway Firmware
[...killing process /bin/eq3configcmd update-lgw-firmware -m /firmware/fwmap -c /etc/config/rfd.conf -l 1...]
Apr 16 12:20:01 homematic-ccu2 user.err monit[2235]: 'rfd' service restarted 1 times within 1 cycles(s) - exec
Apr 16 12:20:01 homematic-ccu2 user.info monit[2235]: 'rfd' exec: '/bin/triggerAlarm.tcl rfd restarted WatchDog: rfd-restart true'
Apr 16 12:20:01 homematic-ccu2 user.info monit[2235]: 'rfd' process is running after previous exec error (slow starting or manually recovered?)
Apr 16 12:20:01 homematic-ccu2 user.info monit[2235]: 'rfd' process is running after previous restart timeout (manually recovered?)
Apr 16 12:20:01 homematic-ccu2 user.err monit[2235]: 'rfd' failed protocol test [DEFAULT] at [localhost]:32001 [TCP/IP] -- Connection refused
Apr 16 12:20:01 homematic-ccu2 user.info monit[2235]: 'rfd' trying to restart
Apr 16 12:20:01 homematic-ccu2 user.info monit[2235]: 'rfd' restart: '/etc/init.d/S61rfd restart'
Apr 16 12:20:31 homematic-ccu2 user.err monit[2235]: 'rfd' failed to restart (exit status -1) -- '/etc/init.d/S61rfd restart': Program timed out -- Stopping rfd: OK Starting rfd: ..............
Apr 16 12:20:49 homematic-ccu2 user.info monit[2235]: 'rfd' process is running after previous exec error (slow starting or manually recovered?)
Apr 16 12:20:49 homematic-ccu2 user.err monit[2235]: 'rfd' failed protocol test [DEFAULT] at [localhost]:32001 [TCP/IP] -- Connection refused
Apr 16 12:20:49 homematic-ccu2 user.info monit[2235]: 'rfd' trying to restart
Apr 16 12:20:49 homematic-ccu2 user.info monit[2235]: 'rfd' restart: '/etc/init.d/S61rfd restart'
```

**Comment by the78mole** [comment]
Now I have it working again...

1. I first tried to downgrade the firmware to the 2023-12-18 release, but the hang with eq3configcmd was not solved. 
2. Then I completely reinstalled the SDcard using Raspberry Pi Imager and the latest Raspberrymatic image (as described [here](https://github.com/jens-maus/RaspberryMatic/wiki/Installation-RaspberryPi))
3. Restored one of the automatic backups from the day before yesterday. I furtunately fetched this (using WinSCP) from the Raspberrymatic when I had not yet fixed it. It was located in /media/usb1/backups/homematic-ccu2-3.65.11.20221005-2023-04-15-0007.sbk, which tells, that the previously installed version was 3.65.11 from 2022-10-15.

I'll close the issue now.

**Comment by MichaelN0815** [comment]
Ich an der Stelle würde mir zeitnah eine neue SD-Karte besorgen

**Comment by the78mole** [comment]
Naja, eigentlich sollte die noch völlig in Ordnung sein. Das root-fs ist ja read-only eingehängt und /var/log ist auf einer RAM-disk:
```
/dev/root on / type ext4 (ro,relatime)
devtmpfs on /dev type devtmpfs (rw,relatime,size=454548k,nr_inodes=113637,mode=755)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
tmpfs on /tmp type tmpfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime,mode=777)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noatime,mode=755)
tmpfs on /var type tmpfs (rw,noatime,size=489144k)
tmpfs on /media type tmpfs (rw,noatime)
/dev/mmcblk0p3 on /usr/local type ext4 (rw,noatime,nodiratime,commit=30)
/dev/mmcblk0p1 on /boot type vfat (ro,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
/dev/sda1 on /media/usb1 type vfat (rw,nodev,noexec,noatime,nodiratime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro)
```

Schaut man sich die Änderungszeitpunkte (der letzten2 Stunden) in `/usr/local` und den anderen RW-eingehängten Dateisystemen mal an, dann bestätigt das die Behauptung (die letzten Änderungen scheinen vom Zeitpunkt des Backup Recoveries):
```
root@homematic-ccu2:~# date
Sun Apr 16 16:38:52 CEST 2023
root@homematic-ccu2:~# find /usr/local/ -type f -mmin -120 -exec ls -l {} \;
-rw-r--r--    1 root     root          1434 Apr 16 14:56 /usr/local/etc/config/eshlight/mapdb/storage.mapdb.t
-rw-r--r--    1 root     root           719 Apr 16 14:55 /usr/local/etc/config/rfd.conf
-rw-r--r--    1 root     root          5863 Apr 16 15:09 /usr/local/etc/config/rfd/MEQ187xxxx.dev
-rw-r--r--    1 root     root          5508 Apr 16 15:11 /usr/local/etc/config/rfd/NEQ012xxxx.dev
-rw-r--r--    1 root     root           167 Apr 16 14:56 /usr/local/etc/config/crRFD/data/3014F711A061A7DAxxxxxxxx.ap
-rw-r--r--    1 root     root            63 Apr 16 14:56 /usr/local/etc/config/addons/mh/ids
root@homematic-ccu2:~# find /boot -type f -mmin -120 -exec ls -l {} \;
-rwxr-xr-x    1 root     root            12 Apr 16 16:46 /boot/System Volume Information/WPSettings.dat
-rwxr-xr-x    1 root     root            76 Apr 16 16:46 /boot/System Volume Information/IndexerVolumeGuid
root@homematic-ccu2:~# find /media/usb -type f -mmin -120 -exec ls -l {} \;
usb0/  usb1/  usb2/  usb3/  usb4/  usb5/  usb6/  usb7/  usb8/
root@homematic-ccu2:~# find /media/usb1 -type f -mmin -120 -exec ls -l {} \;
-rwxr-xr-x    1 root     root       1566816 Apr 16 15:27 /media/usb1/measurement/16.rrd
-rwxr-xr-x    1 root     root       1566816 Apr 16 15:27 /media/usb1/measurement/17.rrd
-rwxr-xr-x    1 root     root       1566816 Apr 16 15:27 /media/usb1/measurement/18.rrd
```

Das ganze Zeug mit häufigen Änderungen landet auf dem USB stick und auch sonst gibt es wenig Änderungen. 

Anmerkung: Wie die Änderung auf /boot in der Zukunft liegen kann, weiß ich nicht genau. Es scheint, dass Windows das kurz vor dem Auswerfen in localtime geschrieben hat und Linux die Zeitstempel als UTC interpretiert.

Wenn also die SD-Karte in den Schrott-Mode übergeht, dann ist das halb so wild. Neue SD-Karte bespielen und Revocery-Settings draufbügeln, fertig.

**Comment by bitsbeauty** [comment]
Hallo zusammen,
ich denke ich habe das selbe Problem, verstehe aber den Lösungsweg nicht? Hast Du nur die SD Card getauscht, dann ging es? 

Meine Hardware
- RaspberryPi 3b 
- HM-MOD-RPI-PCB

Meine Steps:
1. Backup gespeichert
2. Upgrade von 3.73.9.20231130 auf 3.79.6.20250118
3. System bootet nicht mehr
4. Neue SD Kard genommen und mit Rasberry Pi Imager neu geflashed -> sytsem fährt hoch und Backup eingespielt
5. RF Modul wird nicht geladen und gibt Fehlermeldung in der WebUI

DAs System hängt sich immer wieder beim "Updating RF Lan Gateway Coprocessor Firmware" auf. Hab den Process über SSH gekillt und neu gestartet - keine Veränerung

Ist das das selbe Problem, oder mach ich ein neues Issue auf?

Hier ein Log
tail -f /var/log/messages
Jan 29 23:12:39 ccu3-webui auth.info sshd[1454]: Server listening on :: port 22.
Jan 29 23:12:39 ccu3-webui user.info root: Updating RF Lan Gateway Coprocessor Firmware
Jan 29 23:12:39 ccu3-webui user.debug update-coprocessor: firmware filename is: coprocessor_update_hm_only.eq3
Jan 29 23:13:29 ccu3-webui auth.info sshd-session[1523]: Connection closed by 192.168.178.40 port 58698 [preauth]
Jan 29 23:13:40 ccu3-webui daemon.info chronyd[1313]: Selected source 194.36.144.87 (0.de.pool.ntp.org)
Jan 29 23:14:44 ccu3-webui daemon.info chronyd[1313]: Selected source 193.203.3.171 (3.de.pool.ntp.org)
Jan 29 23:15:07 ccu3-webui auth.info sshd-session[1547]: Failed password for root from 192.168.178.40 port 58761 ssh2
Jan 29 23:15:12 ccu3-webui auth.info sshd-session[1547]: Accepted password for root from 192.168.178.40 port 58761 ssh2
Jan 29 23:19:18 ccu3-webui daemon.debug /usr/sbin/irqbalance: IRQ ttyS0(71) guessed as class 0
Jan 29 23:25:25 ccu3-webui user.info root: Updating RF Lan Gateway Firmware (Neustart nach Process Kill)
