### ISSUE TITLE
HmIP-WRCD Text Aktualisierung funktioniert nicht mehr seit Version 3.69.6.20230407

### ISSUE THREAD

**Issue by fl4shp01nt** [jens-maus/RaspberryMatic#2294]
### Describe the issue you are experiencing

Seit version 3.69.6.20230407:
Beim Senden in der Raspberrymatic passiert nichts (HmIP-WRCD Display wird nicht aktualisiert).

### Describe the behavior you expected

In Version [3.67.10.20230225](https://github.com/jens-maus/RaspberryMatic/releases/tag/3.67.10.20230225) funktioniert es.
Display Text wird kurz nach update von 3.COMBINED_PARAMETER aktualisiert.
Display Text wird aktualisiert über die GUI in der Rasberrymatik.

### Steps to reproduce the issue

Display text setzten.

### What is the version this bug report is based on?

3.69.6.20230407

### Which base platform are you running?

intelnuc (intel NUC)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Fehlercode von CUU Jack bei senden von COMBINED_PARAMS:
(RPC fault (code: -321, message: Dangling meta character '?' near index 0 ?? ^))

Error from IOBroker:
Cannot call setValue: XML-RPC fault: Dangling meta character '?' near index 0 ?? ^
```

**Comment by jens-maus** [comment]
Duplicate of #2273 and already repaired in latest nightly snapshot and upcoming 3.69.7.xxxxxx version.
