### ISSUE TITLE
Gateway Feature (HMLGW) für Raspberrymatic Add-On in Home Assistant

### ISSUE THREAD

**Issue by aksnet** [jens-maus/RaspberryMatic#2295]
### Describe the solution you'd like

Realisierung eines Homematic LAN Gateway basierend auf einem Home Assistant System mit Raspberrymatic Add-On und RPI-RF-MOD.

Siehe auch: https://homematic-forum.de/forum/viewtopic.php?p=764402#p764402

### Describe alternatives you've considered

Ein normales GW funktioniert ja bereits, dennoch würde man mit einem Pi der Home Assistant am laufen hat auch ein prima GW realisieren können und somit einfach Hardware einsparen.

### Is your feature request related to a problem?

Nur ein Feature Request

**Comment by jens-maus** [comment]
Tut mir leid, aber der HMLGW Modus scheint bereits seit langem zu funktionieren. Zumindest konnte ich das mit der letzten Stable Version und der aktuellen keinerlei Probleme wahrnehmen. Siehe:

```
Mounting /data as /usr/local (Home Assistant Add-On): OK
Identifying host system: oci, OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, inet up, 172.30.33.0, OK
Identifying Homematic RF-Hardware: ....HmRF: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-0000:02:1b.0-1, HmIP: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-0000:02:1b.0-1, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: 4.4.18, not necessary, OK
Starting xinetd: OK
Starting eq3configd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting sshd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Starting multimacd: .......OK
Starting LAN Gateway Daemon: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.69.7.20230626 (raspmatic_oci_amd64)
```

Wie man sieht fährt nach Existenz der `/usr/local/HMLGW` Datei (die natürlich im Kontext des RaspberryMatic Add-on, d.h. innerhalb des Add-on) angelegt werden muss der `hmlangw` daemon problemlos hoch und stellt auch via Port 2000/2001 alle Dienste entsprechend zur Verfügung:

```
# netstat -tulpn | grep hmlangw
tcp        0      0 0.0.0.0:2001            0.0.0.0:*               LISTEN      1038/hmlangw
tcp        0      0 0.0.0.0:2000            0.0.0.0:*               LISTEN      1038/hmlangw
```

Insofern sehe ich also nicht warum das ganze nicht auch als HA Add-on funktionieren sollte (muss man nur Port `2000` und `2001` im RaspberryMatic Add-on entsprechend nach aussen hin freigeben).
