### ISSUE TITLE
Backup/Restore and Addon install not working for filled up /usr/local partition

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#23]
The main backup/restore functionality in a CCU is using the /tmp partition to create a backup and to actually restore an old one. However, as /tmp is placed in Memory on RaspberryMatic and RAM is limited to 1GB on a Pi3 this can easily end up in a non-working backup/restore functionality if the user has installed large amount of data on /usr/local.

To fix this situation one has to rewrite the backup/restore functionality (found here: https://github.com/eq-3/occu/blob/master/WebUI/www/config/cp_security.cgi#L279) so that not /tmp is used but the backup/restore is performed on-disk (e.g. in `/usr/local/backup`) while checking if there is enough space.

The same applied for installing new CCU Addons in case the /usr/local partition is filled up too much.

**Comment by TitusP** [comment]
If the backup procedure is not working after installing the CCU-Historian addon, is this the same issue or shall I raise a ticket for this?

**Comment by jens-maus** [comment]
@TitusP This is the same issue, yes. So no need to report it again.
