### ISSUE TITLE
Home Assistant Add On  - Clean up of unused volumes created by Raspberrymatic

### ISSUE THREAD

**Issue by hklages** [jens-maus/RaspberryMatic#2303]
### Describe the solution you'd like

Any restart of the Add On creates a new volume. In my installation there are already more then 500 unused volumes. 

Suggestion is to clean up (delete unused) regularly unused volumes (created by Raspberrymatic Add On).

### Describe alternatives you've considered

No idea. 

### Is your feature request related to a problem?

Currently it is not related to a problem. There is a enough space available on my system.

### Additional information

see Home Assistant [issue](https://github.com/home-assistant/operating-system/issues/2498)

**Comment by jens-maus** [comment]
This issue should be fixed with the next nightly snapshot. So please try again to install+run the nightly snapshot version of the add-on by tomorrow and report back (@Baxxy13 ?).

**Comment by Baxxy13** [comment]
So, getestet und für gut befunden.
Es wird beim Start kein Volume mehr erzeugt und entsprechend bleibt natürlich dann auch kein Volume zurück.
