### ISSUE TITLE
Programs do not run after restart of docker container 

### ISSUE THREAD

**Issue by mpietruschka** [jens-maus/RaspberryMatic#2312]
### Describe the issue you are experiencing

When I restart raspberrymatic by `docker restart $containerid` it does not run all programs after it has started again.

Rebooting by the maintain menu does run all programs.

***Background***
I do initialize a systemvariable to the value 'unknown' by a simple program. It comes without any conditions and has been run on the original CCU after every boot.

Is that by design? Can I change that somehow?

thanks!

### Describe the behavior you expected

I expect the programs to be run after system start.

### Steps to reproduce the issue

1. Start raspberrymatic in docker
2. Create a program that sets a systemvariable
3. Restart  by `docker restart $containerid`
4. Nothing changed in your systemvariable
5. Reboot by the maintain menu 
6. Programm has been run and systemvariable is beeing set
...

### What is the version this bug report is based on?

3.69.6.20230407

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HM-LGW-O-TW-W-EU-2

### Anything in the logs that might be useful for us?

```txt
nope
```

**Comment by Baxxy13** [comment]
Die Programme führt die ReGa aus. Die wird kurz vor Ende des Bootvorganges gestartet.
Du kannst ja mal nach den jeweiligen Reboots in die /var/log/boot.log schauen und gucken bzw. vergleichen ob da soweit alles identisch / korrekt aussieht.

**Comment by fnt-cb** [comment]
Gibt dazu auch schon in einem anderem Forum die gleichen geschilderten Probleme.
Habe RaspberryMatic auch in einem Docker-Container unter Proxmox mit Debian 11 am laufen.
Seit der 3.69.x läuft da RaspberryMatic nicht mehr.

Log aus Portainer:
Starting multimacd: ...........ERROR
Starting rfd: ERROR: /dev/mmd_bidcos missing, ....................ERROR
Starting HMIPServer: ERROR: /dev/mmd_hmip missing
Starting ReGaHss: ....................ERROR

Bin jetzt einfach mal auf die Version 3.67.10.20230114 zurück gegangen, damit läuft alles noch wunderbar.

**Comment by Baxxy13** [comment]
Für mich sind das erstmal 2 völlig verschiedene Probleme.
Bei @mpietruschka laufen einige Programme nicht wenn der Container über die Shell neu gestartet wird.

Bei dir, @fnt-cb starten diverse Dienste erst gar nicht sauber durch.

Ohne Vergleich der `/var/log/boot.log` kann man da nicht weiter viel zu sagen.

**Comment by mpietruschka** [comment]
Thanks for your patience!

I tried to reproduce my issue on a clean system with the latest version of raspberrymatic. Everything worked. I don't know what might have been wrong with my productive system.

I'll have an eye on that behavior and will reopen this issue, when know more about the possible circumstances.
