### ISSUE TITLE
Umlaute in Namen von Philips Hue Leuchten führen zu Problemen

### ISSUE THREAD

**Issue by bmarzeion** [jens-maus/RaspberryMatic#2324]
### Describe the issue you are experiencing

Wenn im Philips Hue System Leuchtennamen mit Sonderzeichen oder Umlauten benannt sind und das Gateway dann gekoppelt wird, erscheinen zwar die Hue Bridge und alle Leuchten unter "Einstellungen -> Geräte", aber die Geräteliste unter "Status und Bedienung -> Geräte" bleibt vollständig leer (auch keinerlei andere Geräte werden mehr angezeigt, auch nicht der Tabellen-Header etc.).
Durch löschen der Leuchten mit Umlaut/Sonderzeichen lässt sich das Problem beheben, genauso durch Umbenennung in der Hue Bridge und erneute Kopplung.

### Describe the behavior you expected

Umlaute/Sonderzeichen sollten "abgefangen" werden (oder die Einschränkung dokumentiert werden)

### Steps to reproduce the issue

1. Leuchte in Philips Hue mit Umlaut im Namen benennen.
2. Hue koppeln
3. Status und Bedienung -> Geräteliste einsehen

### What is the version this bug report is based on?

3.69.6.20230407

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
ich bin Newbie und habe in den logs nichts hilfreiches erkennen können
```

**Comment by Baxxy13** [comment]
Kannst du mal ein konkretes Namensbeispiel nennen was Probleme macht?
Ich habe zwar keine HUE-Integration aber doch einige HM/IP-Geräte die z.B. "Küchenlampe" heißen und keine Probleme machen.

**Comment by bmarzeion** [comment]
Ja, zum Beispiel "Gästezimmer". In der Liste "Einstellungen -> Geräte" sind die Umlaute dann auch durch andere Sonderzeichen "ersetzt", so bin ich drauf gekommen.

Bei meinem HMIP-Geräten machen Umlaute auch kein Problem.

**Comment by Baxxy13** [comment]
Hmm, möglicherweise werden die Namen irgendwie komisch/falsch codiert von HUE ausgelesen.

Du könntest im Problemfall mal gucken ob es Fehlermeldungen in der Browserkonsole gibt.
