### ISSUE TITLE
FALMOT on 1.4.8 pending config

### ISSUE THREAD

**Issue by townlema** [jens-maus/RaspberryMatic#2329]
### Describe the issue you are experiencing

After upgrading the FALMOT heating control to firmware 1.4.8 Raspberrymatic gets stuck in pending config. 
Raspberrymatic on 3.69.7.20230506
It has been in this state for at least 1 month.
Device Tests in the webgui to the FALMOT work fine just the config is not sent.  I do not want to delete and train in again due to all my settings

### Describe the behavior you expected

Config is sent to the device

### Steps to reproduce the issue

1. Just upgraded the FALMOT to 1.4.8 firmware
2.
3.
...

### What is the version this bug report is based on?

3.69.7.20230506

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
no
```

**Comment by Baxxy13** [comment]
Seems that this is related to the FALMOT-Firmware, not really to RaspberryMatic.
You could read here (in German): [Falmot C12 neue FW 1.4.8 -> ? Konfig ?](https://homematic-forum.de/forum/viewtopic.php?f=58&t=78713&hilit=falmot)

**Comment by townlema** [comment]
Yes I read that one before but of no great help.  Came down to deleting the device and relearning which is not a great solution.

I raised the issue here as I thought the CCU was responsible for pushing out any pending config changes to the device?

**Comment by jens-maus** [comment]
This is definitely nothing we (the RaspberryMatic project) can do anything about. All these things (firmware update, etc.) are managed in the closed source parts of the OCCU project. In addition, I cannot reproduce this since my two FALMOT updated perfectly to 1.4.8 back then.
