### ISSUE TITLE
/usr/local/etc/rc.local not executed in HMLANGW mode

### ISSUE THREAD

**Issue by not1337** [jens-maus/RaspberryMatic#2338]
### Describe the issue you are experiencing

/etc/init.d/S98StartAddons exits if HM_MODE != NORMAL, thus not executing any existing /usr/local/etc/rc.local script.

### Describe the behavior you expected

/usr/local/etc/rc.local should be executed in all regular operating modes, e.g. NORMAL and HM-LGW.

### Steps to reproduce the issue

reboot :-)

### What is the version this bug report is based on?

3.69.7.20230506

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
n/a
```

**Comment by jens-maus** [comment]
This behaviour (that all `rc.XXXX`) startup scripts are ignored in HMLANGW mode has been added on purpose. Please elaborate why you need to be able to start any third-party application in HMLANGW mode or why you need that functionality at all, because HMLANGW mode is partly a legacy and not meant to be used to run complex environments, etc.

**Comment by not1337** [comment]
e.g. to switch of the Phy LEDs on a Pi 3B.

**Comment by Baxxy13** [comment]
Just uncheck "LED-Nutzung" in normal Mode via Advanced Settings or create...
`/usr/local/etc/config/disableLED`
`/usr/local/etc/config/disableOnboardLED`
...manually.

That turns off all LED's even in HMLGW-Mode.

**Comment by jens-maus** [comment]
> That turns off all LED's even in HMLGW-Mode.

If I understood it correctly @not1337 wants to turn of the LEDs of the Ethernet ports which is not performed with the status files you mentioned. For this either the `/boot/config.txt` has to be modified or a special tool have to be used to switch of even the LEDs of the Ethernet port of a RaspberryPi.

**Comment by not1337** [comment]
As a suggestion, why not execute /usr/local/etc/rc.langw when in lan gateway mode? This would keep things separate from the regular rc.local and make clear that this script is only for lan gateway mode.

**Comment by hotroot** [comment]
> Please elaborate why you need to be able to start any third-party application in HMLANGW mode or why you need that functionality at all, because HMLANGW mode is partly a legacy and not meant to be used to run complex environments, etc.

I‘m using my LAN-Gateway via WLAN and to get al stable connection between my RaspberryMatic CCU and the RaspberryMatic LAN Gateway I need to disable Wi-Fi Power Save in the LAN-Gateway via `iw wlan0 set power_save off`
Without this command the connection is very unstable. After executing this command the connection is stable.
