### ISSUE TITLE
WebUI: Allow to change content of system variables directly via WebUI.

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#234]
It should be fairly easy to modify the WebUI so that it allows to modify the content of system variables which is an often wanted basic feature so that users are able to quickly modify the content of a system variable within the WebUI.

**Comment by mdzio** [comment]
I noticed a small problem when a string system variable is set with a multiline value: The value is taken over, but the dialog for editing the system variable is broken.

![002_12012021_215637](https://user-images.githubusercontent.com/24684496/104373895-5c8da300-5521-11eb-9db3-a8c398718dcf.jpg)
![003_12012021_215654](https://user-images.githubusercontent.com/24684496/104373896-5d263980-5521-11eb-888a-8855738dd1af.jpg)

RM-Version: 3.55.5.20201226
Browser: Opera, Edge

**Comment by mdzio** [comment]
@jens-maus: I think this issue can be closed here. My error reported above corresponds to #1177 reported by @Baxxy13 and is fixed in the current version.
