### ISSUE TITLE
Matter bridge

### ISSUE THREAD

**Issue by hubertmeier** [jens-maus/RaspberryMatic#2342]
### Describe the solution you'd like

A cool feature would be an integration (perhaps as an addon) of matter bridge functionality in the raspberrymatic which presents all sensors and actors as matter devices. I think its a lot of work ... Homematic components could later be accessed by any APP over any border-router (ok, thats theory ... 😉).

Are there any ideas for that?

Thank you for your work ...

### Describe alternatives you've considered

Raspberrymatic works well ... this feature request expands raspberrymatic. For now, i stop to buy further components because no one knows what the future is. A matter bridge would solve this problem.

### Is your feature request related to a problem?

No

**Comment by jens-maus** [comment]
Sorry, but this is totally out of scope of RaspberryMatic (or a CCU).

**Comment by domdorn** [comment]
@hubertmeier (and everyone else coming to this thread): 
see this for a possible "solution"
https://www.techlover.de/2023/03/01/all-in-one-home-assistant-homematic-ip-ssd-die-perfekte-kombi/

**Comment by jens-maus** [comment]
This is a issue tracker here and no discussion fora. Thus, no reason to continue here.
