### ISSUE TITLE
ReGaHss/WebUI: preserve active/inactive state after editing/saving programs

### ISSUE THREAD

**Issue by jp112sdl** [jens-maus/RaspberryMatic#235]
If an existing program is **not** set to `Aktiv` and is edited, then saving, it becomes `Aktiv`.
Please provide the possibility to keep them not `Aktiv`.
Maybe it could be an extension to #228

**Comment by drose28357** [comment]
Shoud'nt it be "ReGaHss/WebUI: keep programs active state after editing and saving them" ?

**Comment by jp112sdl** [comment]
@drose28357 
No, they should be kept **inactive**!

Actually it is:
1.) Set a program to "inactive"
2.) Edit the program. Save it.
3.) The program is now "active"

Why should it be active now?

**Comment by drose28357** [comment]
That's what I wanted to express. Keep the state ...
If it is active befor saving  then set active after saving
If it is not active befor saving then set "not active"

I don't want to set all programs to not active after saving.

**Comment by jens-maus** [comment]
better title? ;)

**Comment by drose28357** [comment]
Yes. simly thatDitmar (vom Samsung S7)Am 11.01.2018 08:14 schrieb Jens Maus <notifications@github.com>:better title? ;)
