### ISSUE TITLE
AppArmor issues with HA Supervised on Debian 12

### ISSUE THREAD

**Issue by sbyx** [jens-maus/RaspberryMatic#2353]
### Describe the issue you are experiencing

Since upgrading from Debian 11 to 12 (soon to be only supported Debian release for HA supervised) there seems to be an issue with AppArmor. Without changing any HA components, simply upgrading to Debian 12 and reinstalling the supervisor Raspberrymatic fails to startup due to permission issues.

rfd etc. cannot start due to socket binding being denied

```
[  335.095168] audit: type=1400 audit(1688207445.848:417): apparmor="DENIED" operation="create" profile="de838cd8_raspberrymatic" pid=11312 comm="Timer-1" family="inet" sock_type="stream" protocol=0 requested_mask="create" denied_mask="create"
[  335.095822] audit: type=1400 audit(1688207445.848:418): apparmor="DENIED" operation="create" profile="de838cd8_raspberrymatic" pid=11312 comm="Timer-2" family="inet" sock_type="stream" protocol=0 requested_mask="create" denied_mask="create"
[  335.097214] audit: type=1400 audit(1688207445.848:419): apparmor="DENIED" operation="create" profile="de838cd8_raspberrymatic" pid=11312 comm="Timer-1" family="inet" sock_type="stream" protocol=0 requested_mask="create" denied_mask="create"
[  335.098668] audit: type=1400 audit(1688207445.852:420): apparmor="DENIED" operation="create" profile="de838cd8_raspberrymatic" pid=11312 comm="Timer-2" family="inet" sock_type="stream" protocol=0 requested_mask="create" denied_mask="create"
[  340.090651] audit: type=1400 audit(1688207450.844:421): apparmor="DENIED" operation="create" profile="de838cd8_raspberrymatic" pid=11312 comm="Timer-2" family="inet" sock_type="stream" protocol=0 requested_mask="create" denied_mask="create"
[  340.091015] audit: type=1400 audit(1688207450.844:422): apparmor="DENIED" operation="create" profile="de838cd8_raspberrymatic" pid=11312 comm="Timer-1" family="inet" sock_type="stream" protocol=0 requested_mask="create" denied_mask="create"
[  340.092491] audit: type=1400 audit(1688207450.844:423): apparmor="DENIED" operation="create" profile="de838cd8_raspberrymatic" pid=11312 comm="Timer-2" family="inet" sock_type="stream" protocol=0 requested_mask="create" denied_mask="create"
[  340.093039] audit: type=1400 audit(1688207450.844:424): apparmor="DENIED" operation="create" profile="de838cd8_raspberrymatic" pid=11312 comm="Timer-1" family="inet" sock_type="stream" protocol=0 requested_mask="create" denied_mask="create"
[  340.094404] audit: type=1400 audit(1688207450.848:425): apparmor="DENIED" operation="create" profile="de838cd8_raspberrymatic" pid=11312 comm="Timer-2" family="inet" sock_type="stream" protocol=0 requested_mask="create" denied_mask="create"
[  340.094805] audit: type=1400 audit(1688207450.848:426): apparmor="DENIED" operation="create" profile="de838cd8_raspberrymatic" pid=11312 comm="Timer-1" family="inet" sock_type="stream" protocol=0 requested_mask="create" denied_mask="create"
```

Disabling AppArmor with apparmor=0 on kernel commandline works around the issue.

### Describe the behavior you expected

Regular startup / operation

### Steps to reproduce the issue

1. Run Raspberrymatic on Debian 12 as HA addon in HA supervised

### What is the version this bug report is based on?

 3.69.7.20230626

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Jun 30 16:24:31 de838cd8-raspberrymatic user.err : Could not create socket
Jun 30 16:24:57 de838cd8-raspberrymatic user.err rfd: Could not bind to TCP port 32001
```
```


### Additional information

**Comment by sbyx** [comment]
I have opened this against HA supervisor as well: https://github.com/home-assistant/supervisor/issues/4417

**Comment by jens-maus** [comment]
Sorry, but I don't think that this is a bug in the HA Supervisor. Moreover this (that a HA Supervised installation) stops partly working after underlying OS upgrade is a common problem and that's exactly why HA supervised installations and highly discouraged these days and instead HomeAssistantOS based HA installation should be preferred.

Regarding this issue IMHO this could easily be related to cgroups beased differences regarding Debian11 vs 12 which do not allow the supervisor to set the docker / RaspberryMatic container permissions correctly anymore and therefore it fails to create the necessary dependencies during startup.

**Comment by sbyx** [comment]
Thanks for the quick reply. HA supervised with Debian 11 already required setting `systemd.unified_cgroup_hierarchy=false`. This has been kept at least in my setup here. I think the main difference between Debian 11 and 12 is the change from Apparmor 2.x to 3. I would gladly change back to HA OS since it is less trouble but it never has been running or even starting up consistently for me and that on regular Intel NUC 11 hardware.

**Comment by jens-maus** [comment]
> I would gladly change back to HA OS since it is less trouble but it never has been running or even starting up consistently for me and that on regular Intel NUC 11 hardware.

Well, not a real topic for here, but: I would suggest (if you anyway use a full-fledged IntelNUC11) that you install ProxmoxVE instead as a Virtualization Hypervisor solution and then run your HomeAssistant as a VM as well as RaspberryMatic as another VM alongside and if you need another "normal" debian box, feel free to startup a third Linux VM, a IntelNUC11 is way powerful enough to run all these three VMs (and more) without any performance issues. Just using a full NUC11 for HA or basic Debian is IMHO a waste. And in the end ProxmoxVE 8 is also based on Debian12, btw :)

**Comment by sbyx** [comment]
Good point, I guess I messed around enough with HA on bare metal already. Let's give the new Proxmox 8 a try next week if that can safely contain HAOS and run it in a more stable manner so be it. In any case someone setting up supervised with Debian 12 might or might not run into the same issue here. At your discretion if you want to keep this open or not.

**Comment by lmagyar** [comment]
FYI: Downgrading AppArmor from 3.0.8-3 to 2.13.6-10 maybe can solve this issue also (it helped in a similar situation), for steps see https://github.com/lmagyar/homeassistant-addon-mariadb-inmemory/issues/44#issuecomment-1631729232

**Comment by jens-maus** [comment]
As stated in #2358 this seems to be an issue of the HA Supervised installation itself and the corresponding AppArmor dependencies in HA Supervisor&Co. However, definitely nothing for this project here but better reported in the HomeAssistant projects accordingly.

**Comment by jens-maus** [comment]
In 643fa75bd182d70142dd4e7649bc51adc7936a15 I added `network` now to the apparmor profile of the HA addon. So please try to test if the issue is resolved now when re-installing the RaspberryMatic HA add-on in a Debian12 driven supervised installation.

**Comment by jens-maus** [comment]
I will flag this ticket/issue as solved. Please reopen in case you identify that the fix in the apparmor profile did not work.
