### ISSUE TITLE
Falscher CCU-Jack Port im HASS Addon

### ISSUE THREAD

**Issue by dega2** [jens-maus/RaspberryMatic#2360]
### Describe the issue you are experiencing

Der MQTT-Port des CCU-Jack läst sich nicht ansprechen, wenn RaspberryMatic als HASS-Addon läuft. Über den MQTT-Secure Port funktioniert der Zugriff. nur über den nicht-SSH Port kommt keine Verbindung zu stande. Im config.yaml ist der falsche Port für eine nicht Secure-Verbindung eingetragen. Anstelle dem Standard MQTT-Port 1883 ist hier 1833 eingetragen.

### Describe the behavior you expected

Getestet mit dem MQTT-Explorer und zigbee2mqtt auf Port 1833.

### Steps to reproduce the issue

Standart installation von RaspberryMatic als HASS-Addon.
Installieren von CCU-Jack.

### What is the version this bug report is based on?

3.69.7.20230626

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
-
```

### Additional information

Ich habe einen Fork auf https://github.com/dega2/RaspberryMatic erstellt und das home-assistant-addon/config.yaml geändert auf 1883.
Nach Einbindung des Repos und neuinstallation des Addons funktioniert CCU-Jack

**Comment by jens-maus** [comment]
Dann schick doch einen PullRequest mit den Änderungen ein und dann kann man das entsprechend einpflegen.

**Comment by jens-maus** [comment]
Das Problem sollte inzwischen behoben sein.
