### ISSUE TITLE
Gruppenfunktion (Startseite > Einstellungen > Gruppen) in Nightly's 3.71.8.xxx verbuggt

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#2364]
### Describe the issue you are experiencing

Auf einem frischen Testsystem mit 2 angelernten Aktoren (HmIP-PSM und HM-LC-Sw1-Pl-DN-R1) zeigen sich mehrere Probleme bei der Gruppenfunktion.

**A - HmIP:**

- neue IP-Gruppe anlegen und die PSM hinzufügen geht
- erneutes Öffnen der Gruppe zeigt "Es sind keine Geräte in der Gruppe" und die PSM wird unter "Bereits verknüpfte Geräte" gelistet, dadurch lässt sich die PSM auch nicht aus der Gruppe entfernen
- die  `groups.gson` sieht aber passig aus

`{"id":1,"groupMembers":[{"memberType":{"id":"SWITCH_ACTUATOR"},"properties":{},"id":"0001D3C99CA0D2:2"}],"groupType":{"id":"hmip.heating.group","label":"HmIP-Heizungssteuerung","version":131072},"groupProperties":{"FORBID_SINGLE_OPERATION":false,"GROUP_DEVICE_NAME":"IP-Gruppe-1-BX INT0000001","NAME":"IP-Gruppe-1-BX"}}`

**B - HM:**
- neue HM-Gruppe anlegen geht, hinzufügen lässt sich der HM-Aktor nicht (wird nicht gelistet)
- erneutes Öffnen der Gruppe zeigt "Es sind keine Geräte in der Gruppe" (klar ich konnte es nicht hinzufügen) 
- die PSM wird unter "Bereits verknüpfte Geräte" gelistet obwohl ich eine HM-Gruppe öffnete
- auffällig: der Gruppentyp steht auf HmIP, ist ausgegraut und lässt sich demzufolge nicht ändern
- die  `groups.gson` sieht aber auch hier passig aus

`{"id":7,"groupMembers":[],"groupType":{"id":"HomeMatic.heating","label":"Heating_Control","version":3},"groupProperties":{"FORBID_SINGLE_OPERATION":false,"GROUP_DEVICE_NAME":"HM-Test-Gruppe-2-BX ","NAME":"HM-Test-Gruppe-2-BX"}}`

### Describe the behavior you expected

Die Gruppenfunktionalität sollte weiterhin (wie in 3.69.7.xxx) fehlerfrei gegeben sein. 

### Steps to reproduce the issue

1. neue HM / IP Gruppe anlegen oder bestehende öffnen
2. alle bestehenden Gruppen zeigen "Es sind keine Geräte in der Gruppe"
3. in bestehende HM-Gruppen können nur unverknüpfte IP-Geräte aufgenommen werden 
...

### What is the version this bug report is based on?

3.71.8.20230716 Nightly

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
- keine Fehlermeldungen in der Browserkonsole
- HmIP steht auf TRACE aber beim Überfliegen nichts auffälliges, ich weiß aber auch nicht nach was ich suchen müsste
```

### Additional information

-

**Comment by jens-maus** [comment]
Wie bereits in https://github.com/jens-maus/RaspberryMatic/discussions/2363 erwähnt scheint das ein bekanntes Problem zu sein an dem eQ3 auch bereits dran ist und dafür zeitnah ein OCCU Update zur verfügung stellen will.

**Comment by Baxxy13** [comment]
Ja, hatte ich leider erst nach Ticketerstellung gelesen.

**Comment by jens-maus** [comment]
Kein Problem. Ticket aufmachen ist immer gut, dann vergessen wir das nicht oder können es referenzieren wenn es nicht zu 100% gefixt ist oder später wieder auftaucht :)

**Comment by jens-maus** [comment]
So, mit der aktuellen nightly snapshot (3.71.11 basierend) sollte das Problem gelöst sein. Bitte einfach mal testen und wenn das Problem immer noch besteht hier bitte wieder aufmachen.
