### ISSUE TITLE
HTTPs Zertifikat kann nciht ausgetauscht werden

### ISSUE THREAD

**Issue by KoMa1978** [jens-maus/RaspberryMatic#2366]
### Describe the issue you are experiencing

Das Austauschen eines HTTPs Zertifikats funktioniert nicht per WebUI.

### Describe the behavior you expected

Das Zertifikat sollte getausch werden.

### Steps to reproduce the issue

1.
2.
3.
...

### What is the version this bug report is based on?

3.69.7.20230626

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
Das Löschen der /etc/config/server.pem sorgt dafür, dass ein neues Zertifikat erstellt wird.
Das Einfügen des Inhalts aus dem PEM-Zertifikats, das ich hochgeladen habe mittels vi und neustart des lighthttp mittels /etc/init.d/S50lighttpd restart aktiviert das gewünschte Zertifikat.

Ein Hochladen dieser PEM Datei (identischer Inhalt) sagt zwar, dass der WEbserver neu gestartet wird, es bleibt aber das alte Zertifikat aktiv.
```

**Comment by jens-maus** [comment]
Wurde hiermit (https://github.com/jens-maus/RaspberryMatic/commit/0b75a839a3c9b2749861ba707c55662e467ca096) bereits vor ein paar Tagen gefixt und wird so auch im nächsten offiziellen Release dann mit drin sein.

**Comment by jens-maus** [comment]
Duplicate of #2322
