### ISSUE TITLE
eigenes Zertifikat lässt sich nicht installieren

### ISSUE THREAD

**Issue by dirk99** [jens-maus/RaspberryMatic#2368]
### Describe the issue you are experiencing

Installation eines Zertifikats schlägt fehl. Eingesetzt wird die Raspberrymatic. Das Zertifikat wurde auf einer CA erstellt mit einem 2048 oder auch mit einem 4096 Bit Key. Abgespeichert in einer Chain in der Reihenfolge private key, Public Key, Root Certificate. Jeder Block mit begein und End... Das Root CA Certifikat hat eine Gültigkeit von 10 Jahren und das Server Certifikate von 720 Tagen. Den CN sowie auch der SAN Eintrag ist gefüllt.

### Describe the behavior you expected

Nach der Installation via Einstellungen - Systemsteuerung - Netzwerkeinstellungen - Datei Auswählen und Hochladen. Es erscheint Keine Fehlermeldung und der Webdienst wird neu gestartet. Auch nach einem Komplett Neustart der Raspberrymatic ist immer noch das Self signed der Rasberry Matic vorhanden. 

### Steps to reproduce the issue

1. Chain Hoch laden
2. Neustart 
3. Im Browser Zertifikat checken
...

### What is the version this bug report is based on?

3.69.7.20230626

### Which base platform are you running?

rpi2 (RaspberryPi2)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
keine Fehlermeldungen in Bezug auf Zertifikat oder Installation des Zertifikats
```

### Additional information

keine

**Comment by jens-maus** [comment]
Duplicate of #2322
