### ISSUE TITLE
HM-Sen-MDIR-X Kanalparameter verschwunden

### ISSUE THREAD

**Issue by eli4711** [jens-maus/RaspberryMatic#2377]
### Describe the issue you are experiencing

Kanalparameter nicht mehr einstellbar. Scheint alle HM-Classic Bewegungsmelder zu betreffen.

MDIR-O
![MDIR-O](https://github.com/jens-maus/RaspberryMatic/assets/40276118/034b3573-583b-49d7-ba50-dc27db70bec9)

MDIR-SM
![MDIR-SM](https://github.com/jens-maus/RaspberryMatic/assets/40276118/89bbe9b2-64b9-4d7d-90c3-18dc50304f00)

MDIR-WM55
![MDIR-WM55](https://github.com/jens-maus/RaspberryMatic/assets/40276118/63e52933-b348-404f-aebf-de9e24dfe2bc)

### Describe the behavior you expected

Kanalparameter in den Geräteeinstellungen sollten angezeigt werden.

### Steps to reproduce the issue

1. Geräteeinstellungen öffnen.
2. Bewegungsmelder Einstellungen öffnen.
3.
...

### What is the version this bug report is based on?

3.71.12.20230727 (intelnuc)

### Which base platform are you running?

intelnuc (intel NUC)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Aus der Browser Console:

Uncaught TypeError: Cannot read properties of undefined (reading 'firstChild')
    at MD_init (webui.js:48042:33)
    at eval (eval at <anonymous> (prototype.js:500:64), <anonymous>:1:1)
    at prototype.js:500:64
    at prototype.js:751:29
    at prototype.js:711:18
    at Array.forEach (<anonymous>)
    at Array.each (prototype.js:710:12)
    at Array.collect (prototype.js:750:10)
    at String.evalScripts (prototype.js:500:34)
    at Function.<anonymous> (prototype.js:296:23)
```

**Comment by Baxxy13** [comment]
Mal schnell aus der Ferne auf mein "Zuhause-System" mit 3x MDIR geguckt, ja kann ich so bestätigen.
Gut möglich das eQ-3 da wieder was verhauen hat.

**Comment by jens-maus** [comment]
Also ich kann das zumindest hier auch bestätigen das die Geräteparameter für die MDIR Gerätefamilie aus irgendwelchen Gründen (noch nicht tiefer analysiert) nicht mehr einsehbar sind mit der 3.71.x snapshot version. Ich erhalte die selben Fehlermeldungen in der Browserkonsole. Unter `/usr/local/tmp` ist hingegen keine cgimail Datei zu finden. Muss also irgendein Javascript problem sein. Wenn ich versuche das zu debuggen erhalte ich zumindest folgendes Bild das auf einige `undefined` Werte zeigt die dann final in Zeile 48042 der `webui.js` dann in der besagten Exception endet:

<img width="961" alt="Bildschirmfoto 2023-07-31 um 20 24 27" src="https://github.com/jens-maus/RaspberryMatic/assets/5887769/bf5a9102-2a8e-4df3-830d-abd312215693">

Wo genau nun der Root-Cause, d.h. die Quelle des übels ist muss man nun wohl sich etwas genauer anschauen und vllt. auch einfach mal einen Blick in die Änderungen von eQ3 werfen die mit der 3.71.x einhergegangen ist. Ist aber auf jeden Fall schon einmal "reproduzierbar". Immerhin :)

**Comment by jp112sdl** [comment]
https://github.com/eq-3/occu/blob/b7cd484b6e9c6d151ed3c559c2dec00567ed96fb/WebUI/www/config/easymodes/md_ch_master.tcl#L118

```
  append HTML_PARAMS(separate_1) " \${motionDetectorMinumumOfLastValuesA} <span class=\"brightness _$chn\">\${motionDetectorMinumumOfLastValuesB1} [expr $ps(BRIGHTNESS_FILTER) + 1] \${motionDetectorMinumumOfLastValuesC}</span> \${motionDetectorMinumumOfLastValuesD}</td></tr>"
```

=> 

```
  append HTML_PARAMS(separate_1) " \${motionDetectorMinumumOfLastValuesA} <span class=\"brightness_$chn\">\${motionDetectorMinumumOfLastValuesB1} [expr $ps(BRIGHTNESS_FILTER) + 1] \${motionDetectorMinumumOfLastValuesC}</span> \${motionDetectorMinumumOfLastValuesD}</td></tr>"
```

**Comment by jens-maus** [comment]
Super finding! Wie ist denn dieses Leerzeichen da reingerutscht?!?

**Comment by jp112sdl** [comment]
> Wie ist denn dieses Leerzeichen da reingerutscht?!?

Rhetorische Gegenfrage: Warum ist das umgebaut worden, ohne anschließend _mit wenig Aufwand_ zu testen? :wink:

Aber vielleicht hat man den Fehler bereits erkannt, gefixt und in Kürze aktualisiert gepusht.

**Comment by jens-maus** [comment]
In der Urlaubszeit ist das unwahrscheinlich das das zeitnah gefixt bzw ne Aktualisierung im OCCU auftaucht.

**Comment by jens-maus** [comment]
> Problem gelöst! :-) Das nenn ich mal schnell! Danke Jerome! 🥇 

Gelöst? Wo ist denn da bitte was allgemein gelöst? Da muss erst einmal ein Bugfix von eQ3 her oder wir einen WebUI Patch dafür machen damit das dann auch in der nächsten Releaseversion definitiv gelöst sein wird.

**Comment by eli4711** [comment]
Ach so ja, also ich meinte natürlich mein kurzfristiges Problem beim ändern der Parameter. 😐 Nach ändern der betreffenden Zeile in der md_ch_master geht das wieder.

**Comment by jens-maus** [comment]
Ok, danke für die Rückmeldung. Dann fehlt nur noch der entsprechende Fix gegenüber OCCU und schon ist wieder ein Problem abgehakt 😜 Danke @jp112sdl
