### ISSUE TITLE
HmIP-SMO-A-2: Programmierschnipsel sporadisch im Feld Bedienung bei Geräte

### ISSUE THREAD

**Issue by CBRocker** [jens-maus/RaspberryMatic#2387]
### Describe the issue you are experiencing

Ich habe mehrere Bewegungsmelder HmIP-SMO-A-2 bzw. andere HmIP BWM.
Ist erst seit kurzem so. Ich nutze eine originale CCU3.

![grafik](https://github.com/jens-maus/RaspberryMatic/assets/96444759/1d692956-1982-4cb6-a1e1-32b4cc24adfb)

### Describe the behavior you expected

Bei allen taucht nach Bewegungserkennung ein Programmierschnipsel auf.

### Steps to reproduce the issue

offenbar nur sporadisch

### What is the version this bug report is based on?

3.69.7.20230626

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
ich denke, der Screenshot ist sicher ausreichend
```

**Comment by jens-maus** [comment]
Duplicate of #1467
