### ISSUE TITLE
Home Assistant - Addon Download nicht möglich | 404 Client Error

### ISSUE THREAD

**Issue by bennySB** [jens-maus/RaspberryMatic#2393]
### Describe the issue you are experiencing

Beim Versuch das Addon zu installieren kommt immer folgende Fehlermeldung:

`Can't install ghcr.io/jens-maus/raspberrymatic:3.69.7.20230626: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/jens-maus/raspberrymatic:3.69.7.20230626/json: Not Found ("No such image: ghcr.io/jens-maus/raspberrymatic:3.69.7.20230626")`

### Describe the behavior you expected

Ohne Installation kann ich leider meine Homematic Geräte nicht einbinden.
Grundsätzlich war es bereits installiert, jedoch konnte ich die angelernten Geräte nicht mehr steuern und auch keine neuen hinzufügen, also dachte ich mir eine Neuinstallation vom Addon könnte helfen, leider nicht.

### Steps to reproduce the issue

Im Addon-Store "RaspberryMatic CCU" auswählen und auf Installieren klicken.

### What is the version this bug report is based on?

3.69.7.20230626

### Which base platform are you running?

tinkerboard (ASUS Tinkerboard)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Im Log steht leider nur das gleiche drin:

2023-08-20 07:46:34.232 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/de838cd8_raspberrymatic/install - Can't install ghcr.io/jens-maus/raspberrymatic:3.69.7.20230626: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/jens-maus/raspberrymatic:3.69.7.20230626/json: Not Found ("No such image: ghcr.io/jens-maus/raspberrymatic:3.69.7.20230626")
```

### Additional information

Home Assistant etc. ist soweit alles auf dem aktuellen Stand.

**Comment by Baxxy13** [comment]
Das Problem gab es schon mal auf Pi4B. 
Mit einem 32bit HA-OS trat der gleiche Fehler auf, mit einem 64bit HA-OS klappte die Installation.
Hilft nicht wirklich weiter da es für das Tinker wohl nur das 32bit HA-OS gibt.

Siehe auch: [Link - Homematic Forum](https://homematic-forum.de/forum/viewtopic.php?f=65&t=79155&hilit=64bit)

**Comment by jens-maus** [comment]
Hat aber IMHO hier definitiv nix verloren und gehört eher in das Ticket System des HAos github projektes. An RaspberryMatic liegt das soweit ich sehen kann nicht.

**Comment by bennySB** [comment]
Schade, wäre ja auch zu einfach gewesen.

Hätte ja sein können das die Plattform info nicht richtig ausgewertet wird und er deswegen nicht weiß welches Image er genau ziehen soll.
Sollte denn in der Fehlermeldung nicht die Image Angabe mit drin stehen?

**Comment by jens-maus** [comment]
Keine Ahnung. Müsstest du im HA Projekt mal genauer analysieren/fragen. Es scheint auf jeden fall nicht auf RaspberryMatic beschränkt zu sein und auch bei anderen Add-ons aufzutreten:

https://github.com/home-assistant/supervisor/issues/4402

**Comment by bennySB** [comment]
Danke dir fürs verknüpfen.

**Comment by jens-maus** [comment]
cf. https://github.com/home-assistant/supervisor/issues/4507

**Comment by bennySB** [comment]
Habe jetzt eine Übergangslösung für mich gefunden. Problem aktuell ist das er das Docker Image nicht runter laden kann, somit habe ich mit dem SSH-Addon folgenden Befehl ausgeführt:

`docker pull ghcr.io/jens-maus/raspberrymatic:3.71.12.20230826`

Danach konnte ich die Installation ganz normal nutzen und es war sofort installiert.
