### ISSUE TITLE
Netzwerkeinstellungen - Felder für die "fixen Netzwerkeinstellungen" mit sinnvollen Daten vorbelegen

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#2394]
### Describe the solution you'd like

Der allererste Start von RM erfolgt mittels Netzwerkkonfiguration über DHCP.
Will man dann (später) auf fixe Netzwerkeinstellungen umstellen muss man den Haken setzen und die Template-Daten selbstständig durch plausible Daten ersetzen.

Für "Netzwerker" kein Problem, aber der ein oder andere Laie kommt da vielleicht ins straucheln.

Die Idee ist also die "Template-Daten" sinnvoll vorzubelegen, vielleicht einfach mit den Daten die per DHCP ermittelt wurden.

### Describe alternatives you've considered

-

### Is your feature request related to a problem?

Eher ein Komfortgewinn statt wirkliches Problem.
Das würde die Umstellung von DHCP auf "fixe Konfig" erleichtern.
Auch wenn bisher scheinbar nur einer von 100 die Umstellung versemmelt hat. 😉 

[Diskussion im Homematic-Form](https://homematic-forum.de/forum/viewtopic.php?f=65&t=79337&p=775029#p775029)

### Additional information

Wie man das am besten umsetzt weiß ich aktuell nicht.

Meine Ideen dazu wären aber:

- Beim RM-Erststart einmalig die Templates mit den per DHCP ermittelten Werten ausfüllen
- Einen Button nutzen der die DHCP-Konfiguration für die Templates übernimmt.

**Comment by jp112sdl** [comment]
Ich würde die darüber liegenden Zeilen der [/www/config/cp_network.cgi#L908-L912](
https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0136-WebUI-Add-Tailscale-VPN/occu/WebUI/www/config/cp_network.cgi#L908-L912) :
```
  if {! [get_property $netconfig "IP" ip] } {return 0}
  if {! [get_property $netconfig "NETMASK" mask] } {return 0}
  if {! [get_property $netconfig "GATEWAY" gw] } {return 0}
  get_property $netconfig "NAMESERVER1" dns1
  get_property $netconfig "NAMESERVER2" dns2
```
ändern in
```
  set current_prefix ""
  if { $dhcp } { set current_prefix "CURRENT_" }
  if {! [get_property $netconfig "${current_prefix}IP" ip] } {return 0}
  if {! [get_property $netconfig "${current_prefix}NETMASK" mask] } {return 0}
  if {! [get_property $netconfig "${current_prefix}GATEWAY" gw] } {return 0}
  get_property $netconfig "${current_prefix}NAMESERVER1" dns1
  get_property $netconfig "${current_prefix}NAMESERVER2" dns2
```

Wenn DHCP aktiviert ist, werden in den Edit-Feldern die aktuellen Werte (beginnend mit `CURRENT_` aus der `netconfig`-Datei) eingetragen.

Wird DHCP dann deaktiviert, bleiben die Werte auch so erhalten, so dass der Anwender im besten Fall nur das letzte Oktett ändert.

Ist der manuelle Modus aktiv, dann bleibt das Auslesen der `netconfig` wie bisher.

Diese aus meiner Sicht recht einfache Umsetzung mit wenig Umbauten würde jedoch momentan mit dem Patch [0136-WebUI-Add-Tailscale-VPN](https://github.com/jens-maus/RaspberryMatic/tree/master/buildroot-external/patches/occu/0136-WebUI-Add-Tailscale-VPN) kollidieren, da die Anpassungen diesen Block beträfen:
https://github.com/jens-maus/RaspberryMatic/blob/3a0860727ba17de08f07ea1a812e3c65d174a5c9/buildroot-external/patches/occu/0136-WebUI-Add-Tailscale-VPN.patch#L99-L108


Daher die Frage: Soll ich als `.orig` die `cp_network.cgi` aus dem Patch [0136-WebUI-Add-Tailscale-VPN](https://github.com/jens-maus/RaspberryMatic/tree/master/buildroot-external/patches/occu/0136-WebUI-Add-Tailscale-VPN) nehmen?

**Comment by jens-maus** [comment]
Ja, wenn es da Kollisionen zwischen Patches gibt ist das oftmals die einzige lösung. Müsstest du also bitte so umsetzen in deinem neuen webui patch.
