### ISSUE TITLE
Cloudmatic Reserve Proxy startet nicht mehr

### ISSUE THREAD

**Issue by pekae** [jens-maus/RaspberryMatic#2395]
### Describe the issue you are experiencing

Um auf Fremdgeräte zugreifen zu können wird der ReversProxy benötigt. Dieser lässt sich nicht mehr starten

Fehlermeldung : /opt/mh/user/nginx: error while loading shared libraries: libpcre.so.1: wrong ELF class: ELFCLASS64

### Describe the behavior you expected

Dass er normal startet :-)

### Steps to reproduce the issue

root@homematic-ccu2:/opt/mh/user# /bin/sh /etc/config/addons/mh/dienstausngx.sh
root@homematic-ccu2:/opt/mh/user# /bin/sh /etc/config/addons/mh/dienstanngx.sh
/opt/mh/user/nginx: error while loading shared libraries: libpcre.so.1: wrong ELF class: ELFCLASS64
root@homematic-ccu2:/opt/mh/user#

root@homematic-ccu2:/opt/mh/user# find / -name libpcre.so.1
/usr/lib/libpcre.so.1
root@homematic-ccu2:/opt/mh/user# file /usr/lib/libpcre.so.1
/usr/lib/libpcre.so.1: symbolic link to libpcre.so.1.2.13

### What is the version this bug report is based on?

 3.69.7.20230626 

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
keine Logeinträge gefunden
```

**Comment by Baxxy13** [comment]
Ja, das ist schon bekannt und soweit ich weiß auch schon in den Nightly-Snapshots gefixt.
Also bist zur nächsten Version warten oder mal nen aktuellen Nightly ausprobieren.

**Comment by jens-maus** [comment]
Genau so ist es. Dieser Bug wurde mit commit https://github.com/jens-maus/RaspberryMatic/commit/48ad3ab76fafca2c5f05ed725278b4b2a27c5969 bereits vor einiger Zeit beseitigt und hier gemeldet/bearbeitet worden: https://github.com/EasySmartHome/CloudMatic-CCUAddon/issues/10

**Comment by pekae** [comment]
mit dem nightly funktioniert es - vielen Dank
