### ISSUE TITLE
Wrong / missing implementation of HmIP-WRC6 in WebUI

### ISSUE THREAD

**Issue by martz170** [jens-maus/RaspberryMatic#240]
Not possible to use / control the device HmIP-WRC6 in WebUI:
![2018-01-11_180855](https://user-images.githubusercontent.com/27149945/34837274-90e60ee0-f6fa-11e7-8618-174f6eff79bc.jpg)

Funktion should be like this on older device HM-PB-6-WM55:
![2018-01-11_181309](https://user-images.githubusercontent.com/27149945/34837440-1d448b64-f6fb-11e7-821c-dd1f144537fe.jpg)

Firmware is 2.29.23.20171216

**Comment by jens-maus** [comment]
Please try to test it with a CCU2 and with the latest 2.31.x firmware

**Comment by HMside** [comment]
That's normal. The transmitters of the HmIP series can be not operated via virtual key press.

**Comment by martz170** [comment]
Really ? I can operate for example this HmIP device without problem: 
![2018-01-11_222217](https://user-images.githubusercontent.com/27149945/34848173-1fa341fc-f71e-11e7-854b-87d28d4610e0.jpg)

**Comment by HMside** [comment]
Okay, this is new

**Comment by martz170** [comment]
sorry wrong button.. case is not closed

**Comment by HMside** [comment]
I think my above answer was right. Your screenshot (a month ago) shows a actuator not a transmitter. To my knowledge there are no push-buttons in the WebUI for any HmIP transmitter.

**Comment by jens-maus** [comment]
Are you really running 2.29.23.20171216? Have you tried the latest one?

**Comment by martz170** [comment]
@HMside you may be right... i checked again ... here is the correct picture. 
![2018-02-13_214422](https://user-images.githubusercontent.com/27149945/36172782-3ec224ba-1107-11e8-84e2-8d8dfc86482b.jpg)
I am really dissapointed that this device is not manageble over the Web interface. There is no information in the manual that it is not supported / implemented in the web interface. Where did you got this information?

@ Jens -  i think it is not a bug in RaspberryMatic, because it is also not working int the last CCU2 Firmware, but maybe you can foreward this request to your Eq3 contacts to implementate this - if technically possible.
