### ISSUE TITLE
Bug: Energiezähler-Anzeige für HM-ES-TX-WM wird fehlerhaft berechnet

### ISSUE THREAD

**Issue by Nudgiator** [jens-maus/RaspberryMatic#241]
Die Anzeige "Energie-Zähler RaspMatic" des HM-ES-TX-WM wird im RaspberryMatic 2.29.2320171216 fehlerhaft berechnet, wenn man einen Neustart des Raspberry Pi 3B via Zentralen-Wartung des RaspberryMatic durchführt.

Nach jedem Neustart wird der aktuelle Gesamt-Energieverbrauch auf den bereits vorhandenen Gesamt-Energieverbrauch hinzuaddiert.

Beispiel:
---------
1. Wert von "Energie-Zähler _RaspMatic_" in RaspberryMatic = 10 kWh
2. Neustart des Raspi via Zentralen-Wartung durchführen
3. Nach erfolgtem Neustart neu anmelden
4. Wert von "Energie-Zähler _RaspMatic_" in RaspberryMatic = 10 kWh
5. Aktualisierung des Wertes "Energie-Zähler _RaspMatic_" abwarten
6.  Wert von "Energie-Zähler _RaspMatic_" in RaspberryMatic = 20,xx kWh (xx = 10 kWh + in der Zwischenzeit von Punkt 1-5 verbrauchte Energie)

Das kann man beliebig oft wiederholen: nach JEDEM Neustart und REFRESH des Wertes wird der Energiewert neu hinzuaddiert.

Ich vermute, daß der Effekt auch dann auftritt, wenn man den Raspi runterfährt, die Stromversorgung zum Raspi trennt und wiederherstellt und den Raspi dann neu startet.

**Comment by jens-maus** [comment]
Tritt das Problem auch mit einer CCU2 auf?

**Comment by Nudgiator** [comment]
Ich hatte meine CCU2 nur etwa 2 Wochen in Betrieb, bevor ich auf RaspberryMatic umgestiegen bin. Da ist mir diesbezüglich nichts aufgefallen. Da ich bereits damals sehr stark mit Diagrammen gearbeitet habe, wäre mir das aber sicherlich aufgefallen, da ich auch die CCU2 runter- und hochgefahren habe. 
Daher gehe ich davon aus, daß es in der CCU2 korrekt funktioniert, aber explizit getestet (wie oben beschrieben) habe ich es nicht.
Leider habe ich auch schon meine CCU2 komplett "platt gemacht" (zwecks Weiterverkauf), so daß ich das nicht mal eben schnell testen kann. 
Aber man kann das Problem ja innerhalb von 2 Minuten nachstellen, so wie ich es oben beschrieben habe.
Kannst Du das selbst bei Dir ausprobieren? Andernfalls stelle ich das Problem mal ins Homematic-Forum, damit andere Leute es überprüfen können.

**Comment by jens-maus** [comment]
Ja, bitte immer zuerst im Forum diskutieren und verifizieren lassen bevor hier ein Ticket eröffnet wird.

**Comment by cyber-age** [comment]
Hallo,
ich hä das gerade mal mit Firmware 2.29.23.20171118 auf einem PI2 getestet  und kann es nicht reproduzieren. Vielleicht mache ich dieses we ein Update auf die neue Version und werde es dann nochmal testen falls das was hier hilft.

**Comment by Nudgiator** [comment]
Es wäre sicherlich hilfreich, wenn Du das noch einmal mit der neuesten Version testen könntest. Ich kann es bei mir nach jedem Neustart des Raspi 3B nachvollziehen. Parallel stelle ich das Thema mal im Homematic-Forum mit ein.

**Comment by cyber-age** [comment]
Alles klar, dann werde ich heute Abend mal das Update machen & testen sofern meine (kleinen) Kinder es zulassen ;-).

**Comment by Nudgiator** [comment]
Aktueller Zwischenstand, den mir ein User im Homematic-Forum geschickt hat:

> Das Problem gab es auf der CCU2 vor einigen Firmwareversionen. Ist schon > 1 Jahr her.
> 
> Die Berechnung erfolgt im systeminternen Script, dass mit dem Energiesensor verbunden ist und bei Aktualisierung des Zählerstandes ausgeführt wird. Das Script wird beim Anlernen des Gerätes angelegt.
> 
> Du hast jetzt mehrere Möglichkeiten
> 
> - ein aktuelles Script von einem anderen User besorgen und Zeile für zeile vergleichen. Der einzige Unterschied dürfte die ID des Zählers am Anfang des Scriptes sein. Der Rest muss gleich sein.
> 
> - wenn Du eine aktuelle FW benutzt, dann das Gerät ablernen. Prüfen, ob das systeminterne Programm zu dem Energiezähler gelöscht wurde, sonst manuell löschen. Gerät neu anlernen. Script wird mit der aktuellen Vorlage neu erstellt.
> 
> - warten bis ein RasPiMatic Besitzer antwortet

**Comment by jens-maus** [comment]
Wie hier (https://homematic-forum.de/forum/viewtopic.php?f=34&t=38418#p377885) beschrieben ist das wohl ein genereller CCU bug und nichts RaspberryMatic spezifisches.

**Comment by Nudgiator** [comment]
Da scheint es wohl so manche Probleme seitens ELV/eQ-3 mit dem Energiezähler zu geben. Das systeminterne Script arbeitet einfach nicht korrekt.

Ich habe zunächst das systeminterne Script, wie im Homematic-Forum von einem User beschrieben, abgeändert. Damit scheint das Reboot-Problem behoben zu sein.

Da es aber auch noch andere Probleme damit gibt (z.B. Zählerüberlauf), hab ich gestern Abend noch das von Dir erstelltes Script (für mehrere Gas-, Strom-, Wasserzähler) bei mir integriert. Lief zwar nicht auf Anhieb, aber hab's mittlerweile zum Laufen gebracht.

**Comment by jens-maus** [comment]
@Nudgiator Das das systeminterne Skript abgeändert werden muss kann schon sein. Aber der Zählerüberlauf ist ein hardwarebedingtes problem das so auch eQ3 nicht auf anhieb lösen werden kann. Bitte hier aber entsprechend dokumentieren was du genau abgeändert hast damit das systeminterne Skript dann lief und nach einem reboot nicht fälschlicherweise die Energiezählerwerte summiert.

**Comment by Nudgiator** [comment]
Ich habe das systeminterne Script, wie im Homematic-Forum von einem User beschrieben, abgeändert: [https://homematic-forum.de/forum/viewtopic.php?f=65&t=41518#p412402](url)

Hab danach den Raspi mehrfach neu gestartet und konnte das Problem nicht mehr nachstellen.

**Comment by jens-maus** [comment]
Im Prinzip sollte es recht einfach sein für eine zukünftige Version die internen Skript so abzuändern das diese dann korrekt funktionieren. Diese sind an folgender Stelle im WebUI code hinterlegt:

https://github.com/eq-3/occu/blob/master/WebUI/www/rega/pages/tabs/admin/views/newdevices.htm#L684

Ergo müsste man diese wie folgt/vorgeschlagen einfach abändern und ggf. auch noch optimieren.

**Comment by jens-maus** [comment]
Das Problem sollte mit der 3.45.5 Version der CCU Firmwares behoben sein. Es kann jedoch sein das man das Gerät 1x komplett ablernen und neu anlernen muss damit der interne Zählerskript dann entsprechend aktualisiert/angepasst wird.
