### ISSUE TITLE
Restart button

### ISSUE THREAD

**Issue by Eckart0** [jens-maus/RaspberryMatic#242]
Hello,
is it possible to integrate a short script in RaspberryMatic for an optional hardware restart button? Such a button is more family friendly than a restart via SSH or WebUI, if a reboot is necessary a the expert is not at home.

Script like:

```
#!/usr/bin/python3
# file /home/pi/reboot.py
import os, sys, time, RPi.GPIO as gpio
gpio.setmode(gpio.BOARD)   # Pin of the P1/J8-header
gpio.setup(21, gpio.IN)    # Pin 21  (reset-button to LOW)
while 1:
  if gpio.input(21)==gpio.LOW:
    os.system("reboot")
    sys.exit()
  time.sleep(0.3)
```

**Comment by jens-maus** [comment]
First of all, python is no standard package available on RaspberryMatic. However, you can of course create an own CCU Addon and install such scripts/tools in user space (`/usr/local`). But, a global script/functionality like this for all RaspberryMatic users doesn't make any sense IMHO and is a very specific request for single users only (which should create a CCU Addon instead).
