### ISSUE TITLE
WebUI: Übergeordnete Filter sollten bestehen bleiben

### ISSUE THREAD

**Issue by darkbrain85** [jens-maus/RaspberryMatic#243]
Wenn ich in der WebUI einen Filter gesetzt habe und dann ein Objekt öffne um es zu konfigurieren oder zu Ändern, ist der Filter beim Verlassen dieser Ansicht wieder raus. Mich nervt das extrem, vor allem wenn man eine vernünftige Namensgebung hat. Wenn ich meine Alarm Programme ändern will, möchte ich nur einmal den Filter "Alarm" setzen und dann in einem Rutsch mehrere Objekte ändern können.

Dies betrifft vor allem "Einstellungen -> Systemvariablen" sowie "Programme und Zentralverknüpfungen".

**Comment by HMside** [comment]
Innerhalb eines Programms sollten wir zudem versuchen eine Clone Funktion einzufügen, so das eine bereits vorhandene Aktivitätszeile einfach dupliziert werden kann.

**Comment by psi-4ward** [comment]
Dieser Punkt nervt mich auch **sehr**. Ich nutze mittlerweile die Browser Funktion "auf Seite suchen" damit ich meine Geräte in der Liste finde.

Ich würde den aktuellen Filter in der SessionStorage speichern: Nach dem der Browser geschlossen wird ist der Filter wieder weg. In einem neuen Tab/Fenster wird der Filter NICHT übernommen.

Gerne würde ich hier etwas beisteuern aber weiß aktuell nicht ganz wie. Für den Build von RaspberryMatic werden für die Änderungen patch-Files eingespielt wenn ich das richtig sehe?
Die Filter-Persistence könnte man sehr wahrscheinlich auch komplett über Javascript lösen.
Soll ich hierfür eine Funktion erstellen?

**Comment by psi-4ward** [comment]
@jens-maus wärest du hier an nem Patch interessiert?

**Comment by oradke** [comment]
Ich glaube mal, daß sich hier ganz viele über so einen Patch freuen würden!

Ich wäre Dir auf jeden Fall sehr dankbar.

Oliver

Am 11.12.2018 um 00:00 schrieb Christoph Wiechert <notifications@github.com<mailto:notifications@github.com>>:


@jens-maus<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjens-maus&data=02%7C01%7C%7C077ebef1680243c18dd108d65ef34c75%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636800796378441693&sdata=SV3HfsY1rA%2FErXblG9kS7YIjdp2uVsXcdCyDnv1lRw4%3D&reserved=0> wärest du hier an nem Patch interessiert?

**Comment by jens-maus** [comment]
@psi-4ward Ich wäre sogar sehr an einem solchen Patch interessiert! Allerdings müsste dieser sich wirklich sehr gut in die bestehende WebUI integrieren damit dieser Patch auch potentiell von eQ3 irgendwann übernommen werden kann.

**Comment by Bastian007** [comment]
Auch von meiner Seite ist dies das meist gewünschte fehlende Feature:
Permanenter Filter, der erst durch "Filter zurücksetzen" wieder augehoben wird.

**Comment by psi-4ward** [comment]
Leider hab ich aktuell extrem viel um die Ohren aber es steht nach wie vor auf der TODO.

**Comment by jens-maus** [comment]
@psi-4ward Wenn du hier zumindest einen Prototypen entwickelst wo das exemplarisch für einen Filter umgesetzt ist kann ich das gerne dann selbstständig für den Rest pbernehmen bzw einarbeiten.

**Comment by psi-4ward** [comment]
Hi,
also die Filter sind leider doch überall etwas anders umgesetzt. 
Hier mal ne Version für `Einstellungen > Geräte`

```patch
--- webui.js-org        2019-04-12 10:58:24.210193488 +0200
+++ webui.js    2019-04-12 10:58:24.006858225 +0200
@@ -6954,7 +6954,22 @@
     this.callback = callback;
     this.id       = name.replace(/\./g, "_");
     this.formId   = this.id + "Form";
-    this.reset();
+
+    var filterValues = localStorage.getItem(this.id);
+    if(filterValues) {
+      try {
+        filterValues = JSON.parse(filterValues);
+        var values = $(this.formId).values;
+        for (var i = 0, len = values.length; i < len; i++) {
+          if(filterValues.indexOf(values[i].value) !== -1) {
+            values[i].checked = true;
+          }
+        }
+        this.set();
+      } catch(e) {}
+    }
+
+   // this.reset();
   },

   /**
@@ -7065,12 +7080,17 @@
     if ($(this.formId))
     {
       var values = $(this.formId).values;
+
+      var filterValues = [];

       for (var i = 0, len = values.length; i < len; i++)
       {
         this.select(values[i].value, values[i].checked);
+        if(values[i].checked) filterValues.push(values[i].value);
       }

+      // JSON.stringify encodes twice???
+      localStorage.setItem(this.id, JSON.parse(JSON.stringify(filterValues)));
       if ($(this.id))    { $(this.id).hide(); }
       if (this.callback) { this.callback(); }
     }
```

**Comment by psi-4ward** [comment]
Zudem sollten wir erkenntlich machen, ob ein Filter gesetzt ist: 
```css
.Filter_Active .FilterCaption {
  color: red;
}
```

**Comment by jens-maus** [comment]
@psi-4ward Das hört sich doch nach einem guten Plan an. Dann bereite doch mal einen entsprechenden PullRequest vor sodass das dann leichter zu integrieren/testen ist.

**Comment by jens-maus** [comment]
Dieses Issue wurde nun dankenswerterweise von @psi-4ward bearbeitet und wird in der nächsten kommenden Version in einem ersten Ansatz umgesetzt sein. Danke dafür an @psi-4ward für die Umsetzung!!
