### ISSUE TITLE
Text-SysVar Eingabe-PopUp... Eingabefeld horizontal veränderbar gestalten 

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#2440]
### Describe the solution you'd like

Für kleine schnelle Test's nutze ich gerne einen Favoriten auf der Startseite gepaart mit den PopUp's für die Änderung von Systemvariablen. Das klappt sehr gut, nur Text-SysVars händeln sich etwas spröde.
Das liegt daran das sich diese nur vertikal, aber nicht horizontal aufziehen lassen.

Die Idee ist also das Eingabefeld auch horizontal größenveränderbar zu gestalten.

### Describe alternatives you've considered

-

### Is your feature request related to a problem?

- kein wirkliches Problem, eher Komfortgewinn

### Additional information

Hier mal ein Beispiel für eine Text-SysVar mit etwas mehr Inhalt:
![GIF 21 09 2023 11-59-31](https://github.com/jens-maus/RaspberryMatic/assets/54898249/b405a03c-31f2-4c48-8201-ad615fb6c234)

**Comment by jp112sdl** [comment]
Die fixe Breite von 240 muss raus
https://github.com/jens-maus/RaspberryMatic/blob/a89792a6359dddce28e7aa57aadce3764c45f1b7/buildroot-external/patches
/occu/0097-WebUI-SetSysvarValueByUser.patch#L535C1-L535C1

und im Stylesheet muss das `resize: vertical` für die Textarea muss raus (oder auf `both` geändert werden).
https://github.com/jens-maus/RaspberryMatic/blob/a89792a6359dddce28e7aa57aadce3764c45f1b7/buildroot-external/patches/occu/0002-WebUI-Bootstrap/occu/WebUI/www/webui/css/extern/main.min.css#L6C8591-L6C8591

**Comment by jens-maus** [comment]
Haben wir das nicht explizit und mit absicht so gesetzt weil dieses Fenster bzw. der Inhalt dessen 1:1 auch in den Einstellungen der Systemvariablen so auftaucht?

**Comment by jp112sdl** [comment]
Die 240 hat dort keine Auswirkungen.
Resize=both sorgt hingegen schon dafür, dass man auch in den Einstellungen dann die Textbox in beide Richtungen verändern _kann_. Ist dann dort jedoch nicht gerade hübsch, weil das Popup (auch) eine feste Breite hat.

**Comment by jp112sdl** [comment]
Ich wollte auch zunächst Baxxy nur einen Tipp geben, an welchen Stellen er suchen kann, um einen Patch zu bauen.

Wie (und ob überhaupt) das umgesetzt wird, könnt ihr ja dann noch besprechen.

**Comment by jens-maus** [comment]
Genau deshalb hatte ich das AFAIK eben so beschränkt. Ggf. müsste man darüber nachdenken wie man diese beiden Anwendungsfälle voneinander ggf. trennen kann, denn wenn dann jemand in dem Popup (das ja eine feste breite hat) dieses Textfeld horizontal erweitert kommt es da ggf. zu anderen Problemen. Oder man bekommt es irgendwie hin das diese Popups auch mal dynamische größen haben können. Ist ja eigentlich schon sehr unschön das all diese Popups nach dem erzeugen nicht mehr angepasst werden können in Ihrer Breite/Höhe. Da müsste man ggf. mal mit CSS etwas rumjonglieren. Würde dann auch anderen Bereichen gut tun, z.B. den Script-Editor oder Script test popup wo es ja auch noch ein ticket dazu gibt...

**Comment by Baxxy13** [comment]
Ich habe leider von css/html so gar keine Ahnung, kann da also nicht wirklich was zur Lösung / Optimierung beitragen.

**Comment by jp112sdl** [comment]
> Ich habe leider von css/html so gar keine Ahnung

Hatte und habe ich auch nicht. 
99% der Zeit für die Patch-Erstellung meinerseits gingen immer für Google drauf. ^^

**Comment by jens-maus** [comment]
> > Ich habe leider von css/html so gar keine Ahnung
> 
> Hatte und habe ich auch nicht. 99% der Zeit für die Patch-Erstellung meinerseits gingen immer für Google drauf. ^^

Ich bin da bei weitem auch kein CSS/HTML/Javascript Geek und eigentlich find ich das auch "eklig" und uninteressant ;-) Aber was muss das muss. Was mich nur nervt das das im Grunde nur try&error ist bis man eine Lösung gefunden hat die dann hoffentlich auch in allen anderen Browser Engines funktioniert.

**Comment by Baxxy13** [comment]
Optimierungen weiterhin gewünscht. 
Z.B. auch für Wertelinsten-SysVars. siehe: [Homematic-Forum](https://homematic-forum.de/forum/viewtopic.php?f=65&t=81174&p=790720&hilit=text#p790719)
