### ISSUE TITLE
"CCU-Jack" in den Interface/Kategorie - Filter [Einstellungen > Geräte] aufnehmen 

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#2445]
### Describe the solution you'd like

Gefühlt steigt die Beliebt/Bekanntheit des CCU-Jack in letzter Zeit stark an. 
Speziell die virtuellen Jack-Geräte sind äußerst nützlich zur Integrierung "HomeMatic-fremder" Geräte in die WebUI-Logik.

Wie einst für die CUxD-Geräte sollte der Interface/Kategorie - Filter [Einstellungen > Geräte] auch einen Eintrag für das CCU-Jack Interface haben, wenn das AddOn installiert ist.

### Describe alternatives you've considered

-

### Is your feature request related to a problem?

- kein wirkliches Problem, eher Komfortgewinn
- den Filter anzuklicken ist einfach komfortabler als z.B. beim Seriennummernfilter "Jack" einzutippen

### Additional information

![RM_add_Jack-Interface_to_Filter](https://github.com/jens-maus/RaspberryMatic/assets/54898249/c5a819f1-e22a-4acf-92d1-63b1bd316442)

**Comment by jens-maus** [comment]
Das sollte eine leichte Fingerübung sein. Wenn du magst kannst du gerne einfach den entsrpechenden WebUI Patch für CUxD hier entsprechend um CCU-Jack erweitern und einen PR einreichen. Siehe:

https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0041-WebUI-CUxD-DeviceOverview-Sorting.patch

P.S: Im Übrigen (da ich mich noch nicht tief mit CCU-Jack) auseinandergesetzt habe würde mich mal interessieren wie damit das von CCU-Jack propagierte koppeln zweier CCU Systeme praktisch funktioniert. Vielleicht könnte man das ja mal im Diskussionsteil hier zusammen mit @mdzio erörtern und ggf. noch fehlende Sachen dann dahingehend erweitern das vielleicht in zukunft sowas wie ne automatische Synchronisierung von Geräten zweier CCUs dann gibt wo dann die Events/State hin-/her geschickt werden können.

**Comment by Baxxy13** [comment]
Ich gucke mal.
Da ich die "Regeln" nicht so recht kenne, soll das dann...
- ein komplett neuer Patch werden
- der bestehende Patch umbenannt werden
- oder das einfach so in den bestehenden Patch integriert werden

Kurz zur "Jack CCU-Bridge":
M.E. ist es nicht das Ziel eine komplette Zentrale auf eine andere zu spiegeln (und andersherum).
Dazu müsste es für jedes HM/IP Gerät ein Jack-Pendant geben, Und das ist wohl ein riesen Aufwand.

Selektiv zu spiegeln ist was anderes. Das geht jetzt schon sehr gut mit Schaltaktoren/Tastern/Kontakten/Temp-Sensoren.

**Comment by jens-maus** [comment]
> Ich gucke mal. Da ich die "Regeln" nicht so recht kenne, soll das dann...
> 
> * ein komplett neuer Patch werden
> * der bestehende Patch umbenannt werden
> * oder das einfach so in den bestehenden Patch integriert werden

Du kannst den existierenden Patch nehmen, deine Änderung einbongen und dann diesen aber umbenennen in sowas wie `0041-WebUI-ThirdPartyDevice-Sorting` oder so. Und dann den einfach als neuen PR einreichen und gut ist.

> Kurz zur "Jack CCU-Bridge": M.E. ist es nicht das Ziel eine komplette Zentrale auf eine andere zu spiegeln (und andersherum). Dazu müsste es für jedes HM/IP Gerät ein Jack-Pendant geben, Und das ist wohl ein riesen Aufwand.
> 
> Selektiv zu spiegeln ist was anderes. Das geht jetzt schon sehr gut mit Schaltaktoren/Tastern/Kontakten/Temp-Sensoren.

Verstehe. Finde es aber trotzdem irgendwie die Idee interessant es doch vllt. irgendwie hinzubekommen doch eine ganze Zentrale vllt. von der einen zur anderen seite zu synchroniseren auch wenn das ggf. in Punkto Gerätebeschreibung etwas aufwand wäre. Dann würde man vmtl. einfach auf der einen Seite nen haufen realer HomeMatic/HmIP Geräte haben und dann lässt man JACK diese dann auf eine andere Zentrale synchroniseren und dort tauchen sie dann als Geräte auf die aber dem JACK Interface zugeordnet sind und vice versa. Das man da ggf. ne auswahl treffen können will ist klar, aber das könnte man ja ggf. umsetzen. Müssten wir wir gesagt mal gesondert im Diskussionsteil oder im homematic-forum.de weiter diskutieren.

**Comment by mdzio** [comment]
@jens-maus Eine interessante Idee. [Ich habe meine Gedanken mal im Forum verfasst.](https://homematic-forum.de/forum/viewtopic.php?f=43&t=79999)
