### ISSUE TITLE
Eigene Aktion beim Herunterfahren der RaspberryMatic

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#2448]
### Describe the solution you'd like

Wir können über die `rc.xxx` Dateien nun zu jedem relevanten Zeitpunkt des Bootvorganges eigene Aktionen ausführen.

Mir fehlt tatsächlich noch eine eigene Aktion die beim Herunterfahren / Reboot ausgeführt wird.
Idealerweise gleich "als erstes" und auch im LGW-Mode.

Dazu würde ich wieder die `/etc/init.d/S99SetupLEDs` benutzen, also deren "Stop-Bereich".
Namensschema für die Datei dann `rc.shutdown`.

### Describe alternatives you've considered

Alternative Herangehensweisen kommen natürlich auch in Betracht.
Aktuell habe ich aber keine Idee wie die aussehen könnten.

### Is your feature request related to a problem?

Meine RM's führen verschieden Aktion beim Shutdown aus. 
- es werden Nachrichten verschickt
- ein kleiner Tasmota-Aktor wird geschalten
- ein "Connection-Sensor" in Homeassistant wird auf disconnected gesetzt

Umgesetzt ist das aktuell über ein eigenes Start/Stop - Script in `/usr/local/etc/config/rc.d` 

Funktioniert auch problemlos.

M.E. besser wäre es aber wenn es eine "offizielle" und dann auch dokumentierte Methode für "eigene Aktionen beim Herunterfahren" gäbe.

**Comment by jens-maus** [comment]
Ein Problem das mir diesbzgl. in den Kopf kommt ist, das sich damit ein Nutzer in den Fuß schiessen kann in dem er in diesen Shutdown Skripten dann ggf. aktionen ausführt die minuten bis stunden brauchen könnten oder eben nie zum abschluss kommen. Und damit kann er dann die Zentrale dann ggf. nicht mehr herunterfahren. Es gibt beim shutdown eben nicht sowas wie ein "safemode" bzw. man müsste den ggf. zuerst noch einführen, aber auch wenn der da ist ist es dann ggf. schon zu spät wenn der nutzer dann erst auf das normale shutdown gedrückt hat und dieser schon im gange ist.

Wenn dann müsste man sich darüber noch einmal tiefer gedanken machen und ggf. sowas wie eine maximale zeit vorgeben bevor dann der normale shutdown prozess weitergeht und dann ggf. den nutzerdefinierten skript hart abbrechen. Im übrigen müsste man sich auch da übei den addon rc.d diesbzgl. mal gedanken machen, denn auch da kann der shutdown skript ja ggf. zu lange dauern bzw. den shutdown prozess aufhalten. Mach da doch nur mal ein `sleep 1000` rein oder so und du solltest es sehen.

**Comment by Baxxy13** [comment]
Ja, das das alles vorzüglich dafür geeignet ist bei Unbedachtheit sein System zu blockieren hatten wir ja schon mal diskutiert. 
Soweit ich mich erinnere war der Konsens damals, "wir geben die Möglichkeiten, verantwortlich bleibt aber der User".

Wenn wir den Wiki-Abschnitt um eine dicke Warnung erweitern sollte das m.E. ausreichen.

Wenn man die Ausführung der `rc.xxx` mit Timeouts belegen könnte wäre das natürlich praktisch, aber da habe ich aktuell keinen Plan.

Was ich aber noch irgendwann machen wollte ist:
In die jeweiligen `SXX` init-Scripte (die ggf. eine `rc.xxx` aufrufen) ein Echo einbauen (welches nur bei vorhandener `rc.xxx` gezeigt wird) so das zumindest in der `/var/log/boot.log` ersichtlich ist das da was User-eigenes läuft.

**Comment by jens-maus** [comment]
> Wenn man die Ausführung der `rc.xxx` mit Timeouts belegen könnte wäre das natürlich praktisch, aber da habe ich aktuell keinen Plan.

Das sollte kein Problem sein. Einfach dafür das `timeout` kommando nutzen. Dort kann man z.B. ein Skript/Programm einfach auf der Kommandozeile oder in Skripten wie folgt aufrufen:

```
timeout 10 sleep 10000
```

und dann wird das `sleep 10000` das ja eigentlich 10.000 sekunden warten soll schon nach max 10 sekunden hart abgebrochen.

Und nun könnte man einfach bei diesen shutdown skripten eben `timeout X` davorschreiben und wäre quasi "safe". Die Frage wäre nur was wohl ein sinnvoller Wert für X sein sollte?

> Was ich aber noch irgendwann machen wollte ist: In die jeweiligen `SXX` init-Scripte (die ggf. eine `rc.xxx` aufrufen) ein Echo einbauen (welches nur bei vorhandener `rc.xxx` gezeigt wird) so das zumindest in der `/var/log/boot.log` ersichtlich ist das da was User-eigenes läuft.

Hmm, wie willst du das sinnvoll darstellbar machen. IMHO sollte die boot.log und eben auch das /var/log/boot.log wirklich nur ein bare minimum darstellen. Aber klar, vllt einfach ein "rc.local" irgendwo dann in der zeile des jeweiligen SXX skriptes mit auszugeben ist vllt. gar nicht so ne schlecht idee damit man sehen kann das das beim bootup eben ausgeführt wird... Mach mal nen PR und dann kann ich den ja nochmal verfeinern ;)

**Comment by jens-maus** [comment]
> also beispielhaft dann so?
> 
> ```
> # call rc.local
>     if [[ -x /usr/local/etc/rc.local ]]; then
>      timeout 10 sleep 10000  /usr/local/etc/rc.local
>     fi
> ```

Nein, der Aufruf müsste dann so sein:

```
timeout 10 /usr/local/etc/rc.local
```
Hoffe nun ist das klarer wie ich das gemeint habe. Und dann würde er ALLES was in rc.local ausgeführt wird hart nach 10 sekunden abbrechen, egal was das ist...

> > Die Frage wäre nur was wohl ein sinnvoller Wert für X sein sollte?
> 
> Also eigentlich würden wohl 2-3s reichen denke ich. Selbst wenn wir jetzt max 5s nehmen würde der Bootvorgang im Fall der Fälle (5s x 5 rc.xxx) um maximal 25s verlangsamt.

Naja, und was ist wenn aber der Nutzer dort Dinge machen will die ggf. 10 Sekunden dauern? Dann würde das alles nach der spezifizierten Zeit hart abgebrochen werden... Ist eben schwer hier einen optimalen Schwellwert zu finden.

> Und beim Shutdown reichen auch max 5s, alles was länger dauert ist eh Murks.
> 
> > Hmm, wie willst du das sinnvoll darstellbar machen.
> 
> Sieht jetzt rudimentär hier erstmal so aus:
> 
> ```
> Setup onboard LEDs: 
> ### executing rc.postlocal...
> booted, OK
> ```
>
> Ist auch eher für "Support-Zwecke" gedacht damit man sieht, "aha der hat eine der `rc.xxx` aktiv und führt irgendwas aus."

Verstehe ich, gefällt mir trotzdem nicht. Das muss alles in eine zeile. Ergo `echo -n "BLAH"` nutzen und das dann hinter "Setup onboard LEDs" ausgeben lassen damit das dann ggf. wie folgt aussieht:

```
Setup onboard LEDs: rc.postlocal, booted, OK
```

wenn es das gibt und wenn nicht dann:
```
Setup onboard LEDs: booted, OK
```

**Comment by Baxxy13** [comment]
Alles klar soweit.
Da ich beides in einem Rutsch umsetzen würde, 2 konkrete Fragen:
Timeouts einbauen und wenn ja mit welchem Wert?

Den Output würde ich an 2 Bedingungen knüpfen:
Beispiel:
```
# call rc.local
    if [[ -x /usr/local/etc/rc.local ]] && [[ -s /usr/local/etc/rc.local ]]; then
     timeout 10 /usr/local/etc/rc.local
     echo -n "rc.local, "
    fi
```

**Comment by jens-maus** [comment]
> Alles klar soweit. Da ich beides in einem Rutsch umsetzen würde, 2 konkrete Fragen: Timeouts einbauen und wenn ja mit welchem Wert?

Das wäre noch zu diskutieren. Ich tendiere hier für eine reine Notfalllösung um sicherzustellen das die zentrale überhaupt noch bootet oder runterfährt wenn da einer in solch einem skript ein `sleep 10000` eingebaut hat. Deshalb würde ich sagen 2-3 Minuten timeout? D.h. `timeout 120` oder `timeout 180`.

> Den Output würde ich an 2 Bedingungen knüpfen: Beispiel:
> 
> ```
> # call rc.local
>     if [[ -x /usr/local/etc/rc.local ]] && [[ -s /usr/local/etc/rc.local ]]; then
>      timeout 10 /usr/local/etc/rc.local
>      echo -n "rc.local, "
>     fi
> ```

warum noch `-s`? `-x` sollte doch reichen. Ist doch egal ob der skript 0 bytes hat oder nicht...

**Comment by Baxxy13** [comment]
> warum noch `-s`? `-x` sollte doch reichen. Ist doch egal ob der skript 0 bytes hat oder nicht...

Weil eine vorhandene ausführbare aber komplett leere rc.xxx uninteressant ist.
Die kann ja nix und muss m.E. auch nicht erwähnt werden.

**Comment by jens-maus** [comment]
> > warum noch `-s`? `-x` sollte doch reichen. Ist doch egal ob der skript 0 bytes hat oder nicht...
> 
> Weil eine vorhandene ausführbare aber komplett leere rc.xxx uninteressant ist. Die kann ja nix und muss m.E. auch nicht erwähnt werden.

ist aber auch wurscht, der zusätzlich check frisst nur cpu zeit und am schluss kann es schon auch interessant sein zu sehen das da einer ne 0 bytes große rc.local am start hat die ggf. probleme dann macht...

**Comment by Baxxy13** [comment]
Ok, geht klar.

**Comment by Baxxy13** [comment]
Das echo dann aber vor den execute, oder?
```
# call rc.local
    if [[ -x /usr/local/etc/rc.local ]] && [[ -s /usr/local/etc/rc.local ]]; then
     echo -n "rc.local, "
     timeout 120 /usr/local/etc/rc.local
    fi
```

**Comment by jens-maus** [comment]
> Das echo dann aber vor dem execute, oder?

Ja, klar.

**Comment by Baxxy13** [comment]
So, der erste PR (zum sekundären Thema) ist raus.
Da du jetzt wohl nichts gegen die Idee mit der `rc.shutdown` hast würde ich dann dazu einen extra PR machen.

`rc.shutdown` ist namentlich ok?
