### ISSUE TITLE
HmIPW-DRAP --> WatchDog: hs485d-restart all 2 minutes

### ISSUE THREAD

**Issue by PatrikRindlisbacher** [jens-maus/RaspberryMatic#2459]
### Describe the issue you are experiencing

in the CCU3 HmIPW-DRAP --> trigger the WatchDog: hs485d-restart all 2 minutes

### Describe the behavior you expected

1. HmIPW-DRAP with DHPC or fixed IP
2. with or without Tailscale
3. HmIPW-DRAP --> reset --> no change

### Steps to reproduce the issue

every time

### What is the version this bug report is based on?

	3.71.12.20230826

### Which base platform are you running?

rpi3 (RaspberryPi3) CCU3

### Which HomeMatic/homematicIP radio module are you using?

CCU3 original

### Anything in the logs that might be useful for us?

```txt
Gerät	       Seriennummer	Aktuell	   Neu
HmIPW-DRAP	00179F29A784CE	3.0.16	   2.4.28 ????????? Firmware older ??
```

### Additional information
ct 5 22:32:47 ccu3-webui user.crit hs485d: Could not find HomeMatic Lan Gateway with serial number 00179F29A784CE.
Oct 5 22:32:47 ccu3-webui user.crit hs485d: Cannot determine IP Address for HomeMatic Wired Lan Gateway.
Oct 5 22:32:57 ccu3-webui user.err monit[1840]: 'hs485d' service restarted 1 times within 1 cycles(s) - exec
Oct 5 22:32:57 ccu3-webui user.info monit[1840]: 'hs485d' exec: '/bin/triggerAlarm.tcl hs485d restarted WatchDog: hs485d-restart true'
Oct 5 22:32:57 ccu3-webui user.info monit[1840]: 'hs485d' process is running after previous restart timeout (manually recovered?)
Oct 5 22:33:15 ccu3-webui user.err monit[1840]: 'hs485d' failed protocol test [DEFAULT] at [localhost]:32000 [TCP/IP] -- Connection refused
Oct 5 22:33:15 ccu3-webui user.info monit[1840]: 'hs485d' trying to restart
Oct 5 22:33:15 ccu3-webui user.info monit[1840]: 'hs485d' restart: '/etc/init.d/S60hs485d restart'
Oct 5 22:33:23 ccu3-webui user.crit hs485d: Could not find HomeMatic Lan Gateway with serial number 00179F29A784CE.
Oct 5 22:33:23 ccu3-webui user.crit hs485d: Cannot determine IP Address for HomeMatic Wired Lan Gateway.
_No response_

**Comment by PatrikRindlisbacher** [comment]
ct  5 22:32:47 ccu3-webui user.crit hs485d: Could not find HomeMatic Lan Gateway with serial number 00179F29A784CE.
Oct  5 22:32:47 ccu3-webui user.crit hs485d: Cannot determine IP Address for HomeMatic Wired Lan Gateway.
Oct  5 22:32:57 ccu3-webui user.err monit[1840]: 'hs485d' service restarted 1 times within 1 cycles(s) - exec
Oct  5 22:32:57 ccu3-webui user.info monit[1840]: 'hs485d' exec: '/bin/triggerAlarm.tcl hs485d restarted WatchDog: hs485d-restart true'
Oct  5 22:32:57 ccu3-webui user.info monit[1840]: 'hs485d' process is running after previous restart timeout (manually recovered?)
Oct  5 22:33:15 ccu3-webui user.err monit[1840]: 'hs485d' failed protocol test [DEFAULT] at [localhost]:32000 [TCP/IP] -- Connection refused
Oct  5 22:33:15 ccu3-webui user.info monit[1840]: 'hs485d' trying to restart
Oct  5 22:33:15 ccu3-webui user.info monit[1840]: 'hs485d' restart: '/etc/init.d/S60hs485d restart'
Oct  5 22:33:23 ccu3-webui user.crit hs485d: Could not find HomeMatic Lan Gateway with serial number 00179F29A784CE.
Oct  5 22:33:23 ccu3-webui user.crit hs485d: Cannot determine IP Address for HomeMatic Wired Lan Gateway.

**Comment by Baxxy13** [comment]
Hast du den DRAP als LAN-Gateway eingetragen?

**Comment by PatrikRindlisbacher** [comment]
Eingetragen JA funktionierte auch mit dem Glas Display

**Comment by PatrikRindlisbacher** [comment]
> Hast du den DRAP als LAN-Gateway eingetragen?
Eingetragen JA funktionierte auch mit dem Glas Display
Aber dort spinnt es auch nicht verbunden

**Comment by Baxxy13** [comment]
Der DRAP ist kein LAN-Gateway und darf daher auch nicht dort eingetragen werden.

**Comment by PatrikRindlisbacher** [comment]
> Der DRAP ist kein LAN-Gateway und darf daher auch nicht dort eingetragen werden.
--> Glöscht !!!!!
--> Funktioniert !!!!

Danke tausend mal !!!!!!!!!!!

Kapitel: 7.6.1 hatte ich gelesen und verwirrt
Der nicht IP "wired" Adapter hatte ich dort drin

**Comment by PatrikRindlisbacher** [comment]
Der HmIPW-DRAP Wired Access Point darf nicht im LAN-Gateway eingetragen werden !!!!!

WatchDog: hs485d-restart all 2 minutes
