### ISSUE TITLE
das RedMatic-Deinstallations-Überbleibsel "monit-redmatic.cfg" ist nicht wegzubekommen

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#2464]
### Describe the issue you are experiencing

Mir ist das heute im Forum wieder aufgefallen das es RaspberryMatic's gibt auf denen mal RedMatic getestet wurde und das leidige Überbleibsel (nach RedMatic-Deinstallation) `/usr/local/etc/monit-redmatic.cfg` den Monit und das Gesamtsystem ins schwitzen bringt.

Soweit ich mich erinnere wurde das Problem ja schon mal angegangen, und die `/etc/init.d/S98StartAddons` modifiziert, so das folgendes das Problem "lösen" sollte.

```
# cleanup stale /usr/local/etc/monit*.cfg symlinks or monit will
  # report an error later on (thus, workaround broken monit config cleanups)
  find /usr/local/etc/monit*.cfg -type l ! -exec test -e {} \; -exec rm -f {} \; 2>/dev/null
```

Das funktioniert aber leider nicht.

### Describe the behavior you expected

Ganz klar,
`/usr/local/etc/monit-redmatic.cfg` wegputzen wenn RedMatic nicht (mehr) installiert ist. 

### Steps to reproduce the issue

1. RedMatic installieren / deinstallieren oder alternativ einfach die `/usr/local/etc/monit-redmatic.cfg` händisch erzeugen
2. rebooten
3. Syslog kontrollieren oder gucken ob die `/usr/local/etc/monit-redmatic.cfg` entfernt wurde
...

### What is the version this bug report is based on?

3.71.12.20231010 - Nightly

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Oct 12 18:31:32 RM-Test-VM-96 user.warn monit: /usr/local/etc/monit-redmatic.cfg:6: Program does not exist: '/etc/config/rc.d/redmatic'
Oct 12 18:31:32 RM-Test-VM-96 user.warn monit: /usr/local/etc/monit-redmatic.cfg:7: Program does not exist: '/etc/config/rc.d/redmatic'
Oct 12 18:31:32 RM-Test-VM-96 user.warn monit: /usr/local/etc/monit-redmatic.cfg:8: Program does not exist: '/etc/config/rc.d/redmatic'
Oct 12 18:31:32 RM-Test-VM-96 user.warn monit: /usr/local/etc/monit-redmatic.cfg:20: Program does not exist: '/usr/local/addons/redmatic/bin/monit-du'
Oct 12 18:31:32 RM-Test-VM-96 user.err monit: A 'check program' statement requires the program to exist '/usr/local/addons/redmatic/bin/monit-du'
Oct 12 16:31:32 RM-Test-VM-96 daemon.info : process '/usr/bin/monit -Ic /etc/monitrc' (pid 2092) exited. Scheduling for restart.
Oct 12 16:31:33 RM-Test-VM-96 daemon.info : starting pid 2093, tty '/dev/null': '/usr/bin/monit -Ic /etc/monitrc'
Oct 12 18:31:33 RM-Test-VM-96 user.warn monit: /usr/local/etc/monit-redmatic.cfg:6: Program does not exist: '/etc/config/rc.d/redmatic'
Oct 12 18:31:33 RM-Test-VM-96 user.warn monit: /usr/local/etc/monit-redmatic.cfg:7: Program does not exist: '/etc/config/rc.d/redmatic'
Oct 12 18:31:33 RM-Test-VM-96 user.warn monit: /usr/local/etc/monit-redmatic.cfg:8: Program does not exist: '/etc/config/rc.d/redmatic'
Oct 12 18:31:33 RM-Test-VM-96 user.warn monit: /usr/local/etc/monit-redmatic.cfg:20: Program does not exist: '/usr/local/addons/redmatic/bin/monit-du'
Oct 12 18:31:33 RM-Test-VM-96 user.err monit: A 'check program' statement requires the program to exist '/usr/local/addons/redmatic/bin/monit-du'
Oct 12 16:31:33 RM-Test-VM-96 daemon.info : process '/usr/bin/monit -Ic /etc/monitrc' (pid 2093) exited. Scheduling for restart.
Oct 12 16:31:34 RM-Test-VM-96 daemon.info : starting pid 2094, tty '/dev/null': '/usr/bin/monit -Ic /etc/monitrc'
```

### Additional information

Wenn ich die Zeile zum entfernen auf der Konsole ausführe...
```
root@RM-Test-VM-96:/root# find /usr/local/etc/monit*.cfg -type l ! -exec test -e {} \; -exec rm -f {} \;
root@RM-Test-VM-96:/root#
```
... passiert nix.

**Comment by jens-maus** [comment]
Na dieses `find` kommando putzt ja auch nur stale symbolic links weg und nicht symbolische links auf dateien die noch existieren.

Also einfach mal das hier machen:

```
ln -s /tmp/blah /usr/local/etc/monit-redmatic.cfg
```

Dann legst du quasi unter /usr/local/etc einen solchen "stale" symbolischen link nach /tmp/blah an (das es ja nicht gibt). Und das von dir referenzierte `find` kommando putzt dann dieses aber korrekt weg.

Wenn aber der symbolische link von `/usr/local/etc/monit-redmatic.cfg` auf eine valide Datei zeigt, wie soll man dann bitte wissen ob diese *.cfg Datei valid ist oder nicht? Offensichtlich existiert ja diese "monit-redmatic.cfg" Datei auf die `/usr/local/etc/monit-redmatic.cfg` referenziert, nur steht da drin eben leider mumpitz. Deshalb ja auch dieses `Program does not exist`. Für mich sieht das danach aus, das da jemand von Hand redmatic deinstalliert hat, statt das Uninstall zu verwenden. Denn das sollte doch nur diesen stale Link übrig haben der dann aber korrekt weggeputzt wird.

**Comment by Baxxy13** [comment]
Ah ok, hab's nun selbst nochmal "live" getestet. 
Und ja, funktioniert doch.
Wer weiß was die User da auf ihren Systemen gemacht haben.
Oberer Abschnitt:
RedMatic deinstalliert (noch kein Reboot)
Unterer Abschnitt:
nach Reboot
![RM_RedMatic_uninstall](https://github.com/jens-maus/RaspberryMatic/assets/54898249/218702d4-6324-45bf-bf0c-1fbbefd223c2)

Also alles ok und eben ein individuelles User-Problem.
