### ISSUE TITLE
(Home Assistant Add-On) LED config is being ignored

### ISSUE THREAD

**Issue by dawid-woitaschek** [jens-maus/RaspberryMatic#2466]
### Describe the issue you are experiencing

I'm using the current integration on Home Assistant.

Dunno why but suddenly the blue LED on my RPI-RF-MOD started to blink blue every second.

I read about messy internet connection, etc. but it seems to work just fine.

### Describe the behavior you expected

Well, the LED settings shouldn't be ignored - at least it seems like so.

### Steps to reproduce the issue

Don't know how to reproduce this... But I already disabled the "Info-LED" settings under "General settings" and disabled every check in the "Advanced settings", including the LED options there.

### What is the version this bug report is based on?

3.71.12.20231014

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
/etc/config # ls
InterfacesList.xml     addons                 firewall.conf          homematic.regadom.bak  measurement            rfd.conf               time.conf
NoAddonUpdateCheck     cloudmaticDisabled     firewallConfigured     hs485d                 neoDisabled            rpi4usb3CheckDisabled  timezone
NoBadBlocksCheck       crRFD                  firmware               hss_led_info.conf      netconfig              server.pem             tweaks
NoFSTRIM               crypttool.cfg          hideStickyUnreach      ids                    nut                    shadow                 userAckSecurityHint
NoPortForwardingCheck  disableLED             hm_addons.cfg          internetCheckDisabled  rc.d                   snmp                   userprofiles
ReGaHssVersion         disableOnboardLED      hmip_address.conf      localtime              rega.conf              syslog
TZ                     eshlight               homematic.regadom      log4j2.xml             rfd                    systemLanguage
```

**Comment by KHismoom** [comment]
I have the exact same problem, as described in the bug report, even on a fresh installation of HomeAssistant and Raspberrymatic CCU.

**Comment by dawid-woitaschek** [comment]
I'm pretty sure this has something to do with @jens-maus changes to hss_led in this merged commit:
https://github.com/jens-maus/RaspberryMatic/commit/ef8ebf3ed1c29e42808eedc0f9e801033e04abe3

Maybe a permission problem?

Oh and btw, I restored a backup of the add-on and disabled automatic updates for now. Everything's fine again now.
