### ISSUE TITLE
Available Firmware update shows old Firmware updates for HmIP-SWDO-I

### ISSUE THREAD

**Issue by ThomasWein** [jens-maus/RaspberryMatic#2469]
### Describe the issue you are experiencing

I migrated from HomeMaticIP to RaspberryMatic. All of my device have the latest firmaware installed.
However, RaspberryMatic shows new updates for my HmIP-SWDO-I which is older than the one which is currently installed
Latest update for HmIP-SWDO-I is  1.18.10 but RaspberryMatic offers 1.16.10 for installation.
![Screenshot 2023-10-15 202319](https://github.com/jens-maus/RaspberryMatic/assets/17967768/73d01b74-0e89-4e16-88a4-6145f0b2a395)

### Describe the behavior you expected

 RaspberryMatic should offer latest firmware updates.

### Steps to reproduce the issue

1. Configure HmIP-SWDO-I for HomematicIP
2. Install lates Update (currently 1.18.10)
3. Remove HmIP-SWDO-I from HomematicIP
4. Onboard HmIP-SWDO-I to RaspberryMatic
5. Check device updates - RaspberryMatic offers 1.16.10

### What is the version this bug report is based on?

3.71.12.20231014

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
didn't find anything related to this issue
```

### Additional information

kann auch Deutsch ;-)

**Comment by jp112sdl** [comment]
Dafür kann RaspberryMatic nichts. 
Über den Server von eQ-3 wird offiziell die 
`{"type":"HmIP-SWDO-I","version":"1.16.10"}` 
angeboten.

https://ccu3-update.homematic.com/firmware/download?cmd=js_check_version&product=HmIP-SWDO-I&serial=0

**Comment by jens-maus** [comment]
Genau so ist es. `Not a bug, but a feature`. In der Tat ist die Version die als "Neu" angezeigt wird die mit dem Betrieb unter einer CCU empfohlene Firmware die man auch am besten damit nutzen sollte. Auf eigene Gefahr hin kann man gerne auch die mit der Versionsnummer höhere ggf. nutzen, aber damit kann es mitunter dann zu gewissen Inkompatibilitäten oder nicht unterstützten Features in der CCU WebUI kommen. Also einfach Downgraden oder eben mit dieser Notification leben...

@jp112sdl Vielleicht sollten wir überlegen in dem Firmware Requester die Spalte "Neu" besser in "Empfohlen" umzubenennen!?!

**Comment by Baxxy13** [comment]
Einfach ignorieren. 😉 
Die 1.18.10 für die SWDO-I bekommt man aktuell im Beta-Bereich bei homematic-ip.com.
Die sind als "beta-offiziell" für aktuelle Zentralen freigegeben.

Hab die auch drauf...
![FW-Update_SWDO-I](https://github.com/jens-maus/RaspberryMatic/assets/54898249/7c755930-03e6-4317-bf11-df2ef7a83e69)
(die andere Anzeige gibt es so aktuell nicht auf der RM... )

**Comment by jens-maus** [comment]
@Baxxy13 
>  (diese geänderte Anzeige gibt es so aktuell nicht auf der RM... )

Reich doch mal nen neuen PullRequest mit diesem Popup in adequater Form ein, dann kann man den zusammen noch verfeinern ;)

**Comment by Baxxy13** [comment]
Ja, ich schieb das vor mich her...
Wird noch ein bisschen dauern da ich in Kürze erstmal in den Urlaub fliege.

**Comment by jens-maus** [comment]
> Ja, ich schieb das vor mich her... Wird noch ein bisschen dauern da ich in Kürze erstmal in den Urlaub fliege.

Super, sobald du nen Draft hast, reich ihn einfach ein, dann können wir zusammen daran basteln. Vielleicht schafft man es ja auch so dann mal die Updates direkt auf die Zentrale runterladbar hinzubekommen damit die Nutzer dieser nicht mehr von Hand runter+hochladen müssen... Aber nun sind wir hier OT... Viel Spass im Urlaub!
