### ISSUE TITLE
No connection to HomeMatic IP Thermostats after upgrading to RaspberryMatic 3.71.12.20231014

### ISSUE THREAD

**Issue by martinbrose** [jens-maus/RaspberryMatic#2474]
### Describe the issue you are experiencing

After upgrading to [RaspberryMatic 3.71.12.20231014](https://github.com/jens-maus/RaspberryMatic/releases/tag/3.71.12.20231014) from [RaspberryMatic 3.71.12.20230826](https://github.com/jens-maus/RaspberryMatic/releases/tag/3.71.12.20230826), I loose connection to my Homematic IP Smart Home Radiator Thermostats.
I'm using RaspberryMatic directly on a Raspberry Pi Model B Rev 2 with HM-MOD-RPI-PCB.

I performed a second install of 3.71.12.20231014 via the "Manual update procedure" with the downloaded [RaspberryMatic-3.71.12.20231014-rpi0.zip](https://github.com/jens-maus/RaspberryMatic/releases/download/3.71.12.20231014/RaspberryMatic-3.71.12.20231014-rpi0.zip), but the problem persisted.
I had to downgrade to version 3.71.12.20230826 and everything is working again.

### Describe the behavior you expected

RaspberryMatic communicating with my Homematic IP Smart Home Radiator Thermostats.

### Steps to reproduce the issue

1. Update to RaspberryMatic 3.71.12.20231014
2. Restart the RaspberryMatic
3. Try to communicate with Homematic IP Smart Home Radiator Thermostats

### What is the version this bug report is based on?

3.71.12.20231014

### Which base platform are you running?

rpi0 (RaspberryPi)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
I don't have these logs available now, but I'm happy to perform an update again to replicate the error and provide any logs needed.
```

**Comment by jens-maus** [comment]
Please test the current nightly snapshot (https://github.com/jens-maus/RaspberryMatic/releases/snapshots) because there was an issue in the used java version which hopefully this version fixes. So please try and report back.

**Comment by jens-maus** [comment]
> ### Describe the issue you are experiencing
> After upgrading to [RaspberryMatic 3.71.12.20231014](https://github.com/jens-maus/RaspberryMatic/releases/tag/3.71.12.20231014) from [RaspberryMatic 3.71.12.20230826](https://github.com/jens-maus/RaspberryMatic/releases/tag/3.71.12.20230826), I loose connection to my Homematic IP Smart Home Radiator Thermostats. I'm using RaspberryMatic directly on a Raspberry Pi Model B Rev 2 with HM-MOD-RPI-PCB.
> 
> I performed a second install of 3.71.12.20231014 via the "Manual update procedure" with the downloaded [RaspberryMatic-3.71.12.20231014-rpi0.zip](https://github.com/jens-maus/RaspberryMatic/releases/download/3.71.12.20231014/RaspberryMatic-3.71.12.20231014-rpi0.zip), but the problem persisted. I had to downgrade to version 3.71.12.20230826 and everything is working again.
> 
> ### Describe the behavior you expected
> RaspberryMatic communicating with my Homematic IP Smart Home Radiator Thermostats.
> 
> ### Steps to reproduce the issue
> 1. Update to RaspberryMatic 3.71.12.20231014
> 2. Restart the RaspberryMatic
> 3. Try to communicate with Homematic IP Smart Home Radiator Thermostats
> 
> ### What is the version this bug report is based on?
> 3.71.12.20231014
> 
> ### Which base platform are you running?
> rpi0 (RaspberryPi)
> 
> ### Which HomeMatic/homematicIP radio module are you using?
> HM-MOD-RPI-PCB
> 
> ### Anything in the logs that might be useful for us?
> ```
> I don't have these logs available now, but I'm happy to perform an update again to replicate the error and provide any logs needed.
> ```
> 
> ### Additional information
> _No response_

**Comment by martinbrose** [comment]
Hi @jens-maus,

many thanks for the prompt reply.
I just installed [RaspberryMatic-3.71.12.20231017-871882-rpi0.zip](https://github.com/jens-maus/RaspberryMatic/releases/download/snapshots/RaspberryMatic-3.71.12.20231017-871882-rpi0.zip) and as far as I can tell, it's working without problems.
