### ISSUE TITLE
RaspberryMatic als Docker Image

### ISSUE THREAD

**Issue by kcdarook** [jens-maus/RaspberryMatic#248]
Wäre es nicht interessant das RaspberryMatic als Docker Image zu entwickeln, so wäre es möglich das RaspberryMatic als Container auf einem Raspberry Pi laufen zu lassen. Dadurch wäre man in der Lage beispielsweise openhab (ebenfalls als Container) und RaspberryMatic zusammen auf einer Hardware auszuführen.

**Comment by jens-maus** [comment]
This is a duplicate of #192.
