### ISSUE TITLE
HomematicIP Präsenzmelder does not exist anymore after restart

### ISSUE THREAD

**Issue by SidOmsa** [jens-maus/RaspberryMatic#249]
Everytime after a reboot the Präsenzmelder does noch exist anymore.

**Comment by HMside** [comment]
Have you made the firmware update 1.2.4 under 2.29.23? Did you read the firmware note:

Only use the firmware file in connection with the CCU2 from version 2.31.25
After the update has been successfully transferred, it is necessary to disconnect the HmIP-SPI from the CCU2 and teach-in the device again. So that all new functions are displayed in the CCU2.

**Comment by SidOmsa** [comment]
ThxThats itSolved
-------- Ursprüngliche Nachricht --------Von: Andreas Bünting <notifications@github.com> Datum: 21.01.18  22:35  (GMT+01:00) An: jens-maus/RaspberryMatic <RaspberryMatic@noreply.github.com> Cc: SidOmsa <github@berkentien.de>, Author <author@noreply.github.com> Betreff: Re: [jens-maus/RaspberryMatic] HomematicIP Präsenzmelder does not exist anymore after restart (#249) 
Have you made the firmware update 1.2.4 under 2.29.23? Did you read the firmware note:
Only use the firmware file in connection with the CCU2 from version 2.31.25

After the update has been successfully transferred, it is necessary to disconnect the HmIP-SPI from the CCU2 and teach-in the device again. So that all new functions are displayed in the CCU2.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jens-maus/RaspberryMatic","title":"jens-maus/RaspberryMatic","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jens-maus/RaspberryMatic"}},"updates":{"snippets":[{"icon":"PERSON","message":"@HMside in #249: Have you made the firmware update 1.2.4 under 2.29.23? Did you read the firmware note:\n\nOnly use the firmware file in connection with the CCU2 from version 2.31.25\nAfter the update has been successfully transferred, it is necessary to disconnect the HmIP-SPI from the CCU2 and teach-in the device again. So that all new functions are displayed in the CCU2."}],"action":{"name":"View Issue","url":"https://github.com/jens-maus/RaspberryMatic/issues/249#issuecomment-359283022"}}}
