### ISSUE TITLE
At HomeAssistant Add-on with RaspberryMatic CCU with HmIP-RFUSB and Zigbee SkyConnect both sticks not working together

### ISSUE THREAD

**Issue by EQ5** [jens-maus/RaspberryMatic#2499]
### Describe the issue you are experiencing

If I use the HmIP-RFUSB together with RaspberryMatic CCU and a Zigbee USB stick (I have tested ConbeeII and SkyConnect) for ZHA then the Zigbee USB stick breaks off and the ZHA network is no longer accessible. 

However, as soon as I exit the RaspberryMatic CCU (no start on boot) and the HA does a full reboot, the ZHA network is available again until I start the RaspberryMatic CCU again. 

I can repeat the whole process at will.

### Describe the behavior you expected

Both sticks used to work without any restrictions. Unfortunately, I can't say exactly when the problem started.  It took me a while to narrow down the cause.

I reinstalled the HA several times and put it back into operation bit by bit. The error can also be reproduced with a newly installed HA.

### Steps to reproduce the issue

1. install HA
2. setup ZHA and devices
3. install HACS
4. install RaspberryMatic CCU and restore Homematic Backup
5. ZHA devices are no longer available

### What is the version this bug report is based on?

3.71.12.20231020

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
I have also documented the problem here, which I was able to recognize on the HA. However, this was before I was able to recognize how RaspberryMatic and ZHA interact.
https://community.home-assistant.io/t/zha-failed-to-set-up-with-skyconnect/622550
```

### Additional information

I am aware that there is an interaction between the RaspberryMatic CCU and ZHA as well as the drivers for the USB sticks. But I hope that there is a solution and that the easiest way to influence this is via the add-on.

Inteln NUC x64
Core 2023.11.0
Supervisor 2023.10.1
Operating System 11.1
Frontend 20231030.1

**Comment by Baxxy13** [comment]
Zufällig CUxD als AddOn innerhalb des RaspberryMatic - AddOn's installiert?
Wenn ja, dann muss CUxD so konfiguriert werden das es nicht den Zigbee-Stick initialisiert. 
Details dazu im CUxD-Handbuch.

**Comment by Baxxy13** [comment]
Zum Zeitpunkt der Ticketerstellung von @EQ5 am 02.11. war noch HAOS 11.1 aktuell und das hat er auch so angegeben.
Was ich so gelesen habe gab es mit 11.1 und den Sticks wohl keine Probleme.
Entweder ist das ganze nicht so wichtig oder der Hinweis mit CUxD hat's gebracht und es wurde nur die Rückmeldung "vergessen".

**Comment by Cruiser13** [comment]
This issue does still exist for me. Both HA and Raspberrymatic are running as docker containers. If I put the official skyconnect stick from homeassistant in and restart homeassistant everything is fine and it works - as long as raspberrymatic is not being restarted. On the raspberrymatic restart (because of backups, updates or whatever) it'll somehow "grab" the stick and homeassistant can no longer access it. If I shutdown raspberrymatic again and reboot HA, the stick is available again.

**Comment by Baxxy13** [comment]
> it'll somehow "grab" the stick

RaspberryMatic itself grabs nothing excerpt the rf-module/stick.
What about CUxD? Do you use it as AddOn?
If not correctly configurated, CUxD grabs every tty-device it founds.

**Comment by blackbird0589** [comment]
> > it'll somehow "grab" the stick
> 
> RaspberryMatic itself grabs nothing excerpt the rf-module/stick. What about CUxD? Do you use it as AddOn? If not correctly configurated, CUxD grabs every tty-device it founds.

Had the same problem, just for all who are running in the same error: that was the solution for me. Uninstall CUxD-Addon in Raspberrymatic solved that for me.

**Comment by Cruiser13** [comment]
I don't think that I have the CUxD Addon installed, this is my whole list:

![Image](https://github.com/user-attachments/assets/5675cfb2-f331-4601-bf35-c5bf4806d935)
