### ISSUE TITLE
HmIP-SWDO-A recognized as "unknown device"

### ISSUE THREAD

**Issue by oestreicher42** [jens-maus/RaspberryMatic#2501]
### Describe the issue you are experiencing

I have connected two HmIP-SWDO-A devices. They are connected as "unknown devices".
They seem to work (I have succesfully configured a direct connection to my heater) but they are listed as device type "DEVICE" and without a picture.

### Describe the behavior you expected

Devices should show up with a picture and as device type "HmIP-SWDO-A".

### Steps to reproduce the issue

1. buy HmIP-SWDO-A
2. connect HmIP-SWDO-A
3.
...

### What is the version this bug report is based on?

3.71.12.20231020

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Hardware is a CCU3.
```

**Comment by jens-maus** [comment]
Please show a screenshot.

**Comment by jens-maus** [comment]
Sorry, but I just found out that the HmIP-SWDO-A (anthrazit version) is only supported with the next upcoming CCU 3.73.x firmware since unfortunately this other colorized version of the HmIP-SWDO requires some adaptions in HMIPServer which will be shipped with (O)CCU firmware version 3.73.x.

**Comment by Baxxy13** [comment]
Im aktuellen HmIP-Server ist der zumindest schon in der xml gelistet.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<deviceDescription id="SWD_V3" type="SWD" version="3" description="Wireless Window/Door Sensor">
	<devTypes>
		<!-- 1.18.0 as min-->
		<devType label="HMIP-SWDO" id="258" manufacturerCode="1" updateable="true" minVersion="70144" />
		
		<devType label="HmIP-SWDO-2" id="472" manufacturerCode="1" updateable="true" minVersion="70144" />
		<devType label="HmIP-SWDO-A" id="525" manufacturerCode="1" updateable="true" minVersion="70144" />
	</devTypes>
```

**Comment by jp112sdl** [comment]
> Im aktuellen HmIP-Server ist der zumindest schon in der xml gelistet.

Ja, aber der komplette WebUI Kram fehlt.
Wobei du ja jetzt auch weißt, wie das mit den Patchen geht... 😄 
webui.js und DEVDB.tcl sind hier primär an der Reihe.

**Comment by Baxxy13** [comment]
Ach, das soll mal eQ-3 machen. 
Gab es ja schon häufiger das Geräte verkauft wurden aber noch nicht implementiert waren. 
Mit dem HAP geht der SWDO-A bestimmt. 😉

**Comment by jens-maus** [comment]
Wie erwähnt hat eQ3 meines Wissen schon alles für die (O)CCU 3.73.x erledigt die in den nächsten Wochen erscheinen sollte.

**Comment by jens-maus** [comment]
@oestreicher42 The next upcoming nightly snapshot should now be based on the latest release candidate of OCCU 3.73.x, thus the HmIP-SWDO-A should be support. So if you dare you should be able to install/update to that nightly snapshot to check that the SWDO-A is now perfectly working.
