### ISSUE TITLE
RPI-RF-MOD LED keine Funktion

### ISSUE THREAD

**Issue by eli4711** [jens-maus/RaspberryMatic#2507]
### Describe the issue you are experiencing

Die LED vom RPI-RF-MOD leuchtet nicht mehr im normalen Betrieb. Währen einem Firmware Update ist die Funktion normal.

Hard und Software : 

```
CCU Hardware Info
Serial Number:	58A992xxxx
Hardware Model:	Intel Corporation NUC6CAYB (nuc)
CPU / Memory:	Intel(R) Celeron(R) CPU J3455 @ 1.50GHz (4), 7.6G
Storage:	55.9G TEAM L7 EVO SSD 60GB /dev/sdb
Real-Time-Clock:	onboard
CCU Software Info
Product:	raspmatic_intelnuc (3.73.6.20231113)
ReGaHss:	R1.00.0388.0235
Engines:	Tcl (8.6.12), Java (11.0.21), NodeJS (v18.18.2)
Status:	SD(1) NTP(1) Link(1) Internet(1) IP(1)
Operating System Info
OS Type/Kernel:	Buildroot 2023.08.2 (Linux 6.1.62 x86_64)
Uptime:	0 d, 0 h 4 min
Load Average:	0.75 0.54 0.23
System Temperature:	48.0 °C
Memory / Swap Utilization:	11.9 % / 0.0 %
NTP Offset (Server):	-4.101 ms (217.91.77.17)
rootfs / userfs Free Space:	80.2 MB [8.2%] / 50.6 GB [94.6%]
IP address:	192.168.0.210 (eth0, MANUAL)
Gateway / Netmask:	192.168.0.254 / 255.255.255.0
Nameservers:	192.168.0.1, 1.1.1.1
Hostname:	raspmatic
homematicIP-RF (HmIP) Info
RF-Module/Firmware:	RPI-RF-MOD (4.4.22)
Device-Node:	/dev/raw-uart (HB-RF-USB-2@usb-0000:00:15.0-4)
Address:	0xB06AF7 (0xB06AF7)
SGTIN:	3014F711A0001F58A992xxxx
Serial:	58A992xxxx
DC / CS:	9 % / 10 %
HomeMatic-RF (HmRF) Info
RF-Module/Firmware:	RPI-RF-MOD (4.4.22)
Device-Node:	/dev/raw-uart (HB-RF-USB-2@usb-0000:00:15.0-4)
Address:	0xFFxxxx (4554273)
Serial:	58A992xxxx
DC / CS:	9 % / 10 % 
```

### Describe the behavior you expected

LED leuchtet je nach zustand.

### Steps to reproduce the issue

1.
2.
3.
...

### What is the version this bug report is based on?

raspmatic_intelnuc (3.73.6.20231113)

### Which base platform are you running?

intelnuc (intel NUC)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Ausgabe beim Firmware Update: 
Displaying running firmware update output:
==========================================
/bin/fwinstall.sh: line 880: can't create /sys/class/leds/rpi_rf_mod:red/delay_on: Permission denied /bin/fwinstall.sh: line 881: can't create /sys/class/leds/rpi_rf_mod:red/delay_off: Permission denied /bin/fwinstall.sh: line 882: can't create /sys/class/leds/rpi_rf_mod:blue/delay_on: Permission denied /bin/fwinstall.sh: line 883: can't create /sys/class/leds/rpi_rf_mod:blue/delay_off: Permission denied Preparing firmware update:
[1/7] Checking uploaded data... 357119268 bytes received, OK
[2/7] Calculating SHA256 checksum....4f474e57df0b3dc5ef34a49ba2b6e4a520ef6a85518ffc832d85ede39f409014
[3/7] Checking free disk space... 53967294464 bytes, OK
[4/7] Checking storage performance.....sequential write: 187.25 MB/s (OK: > 10.0 MB/s), random write: 21445 IOPS (OK: > 500 IOPS), random read: 12365 IOPS (OK: > 1500 IOPS), PASSED
[5/7] Preparing uploaded data... zip identified, unarchiving........OK
[6/7] Verifying uploaded data.....OK (sha256sum), DONE
[7/7] Preparing firmware update... OK, DONE
Finished preparation successfully.

Starting firmware update (DO NOT INTERRUPT!!!):
[1/5] Validate update directory... OK
[2/5] Checking update_script... no 'update_script', OK
[3/5] Checking for rootfs filesystem images... none found, OK
[4/5] Checking for bootfs filesystem images... none found, OK
[5/5] Checking for image file... found, flashing bootfs....OK, updating bootloader (GRUB)... OK, flashing rootfs............OK, DONE
Finished firmware update successfully.

==========================================
Browser closed connection.
```

**Comment by jens-maus** [comment]
Bitte den Inhalt der `/var/log/boot.log` aus dem normalen Betrieb heraus hier zeigen.

**Comment by eli4711** [comment]
Servus Jens
Inhalt der `/var/log/boot.log` 
***** /var/log/boot.log *****
fsck 1.47.0 (5-Feb-2023)
userfs: clean, 859/3588096 files, 671271/14325760 blocks
Identifying host system: Intel Corporation NUC6CAYB (nuc), OK
Initializing ZRAM Swap: OK
Initializing RTC Clock: onboard, OK
Starting acpid: OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Running seedrng: OK
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Populating /dev using udev: done
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting system message bus: done
Starting iptables: OK
Starting bluetoothd: disabled
Starting network: eth0:.. link up, static, firewall, inet up, 192.168.0.210, wlan0: disabled, OK
Starting Network Interface Plugging Daemon: eth0 wlan0.
Starting chrony: OK
Starting tailscaled: OK
Identifying Homematic RF-Hardware: ....HmRF: RPI-RF-MOD/HB-RF-USB-2@usb-0000:00:15.0-4, HmIP: RPI-RF-MOD/HB-RF-USB-2@usb-0000:00:15.0-4, OK
Updating Homematic RF-Hardware: RPI-RF-MOD: 4.4.22, not necessary, OK
Starting hs485dLoader: OK
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting sshd: OK
Starting NUT services: .OK
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...cryptEnabled trueOK
Setting LAN Gateway keys: OK
Starting hs485d: OK
Starting multimacd: ....OK
Starting rfd: ......OK
Starting HMIPServer: ..........OK
Starting ReGaHss: .OK
Starting CloudMatic: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.73.6.20231113 (raspmatic_intelnuc)

**Comment by jens-maus** [comment]
Bitte mit dem nächsten nightly snapshot erneut testen und berichten.

**Comment by eli4711** [comment]
Servus Jens
Die LED leuchtet wieder. 
Bist der beste 🥇 

Grüße Thomas
