### ISSUE TITLE
HMIP-HAP Range Extend on HA

### ISSUE THREAD

**Issue by colognebroker** [jens-maus/RaspberryMatic#2508]
### Describe the issue you are experiencing

Is there any way to extend range if a Raspberrymatic is running on Homeassistant?
It is not working as jens mentioned
is there anny other way to extend Range?

### Describe the behavior you expected

no laerning of device

### Steps to reproduce the issue

1.
2.
3.
...
no!

### What is the version this bug report is based on?

latest

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
no!
```

**Comment by jens-maus** [comment]
Duplicate of #1373
