### ISSUE TITLE
Energiezähler Zentrale für HM-ES-TX-WM funktioniert nicht bei Zweirichtungszähler Strom

### ISSUE THREAD

**Issue by drose28357** [jens-maus/RaspberryMatic#2512]
### Describe the issue you are experiencing

Ich habe zwei Issues, die jedoch ev. die gleiche Ursache in den Zwei Kanälen des HM-ES-TX-WM haben.

Mein HM-ES-TX-WM wird mit dem Lesekopf ES-IEC an einem digitalen Zweirichtungszähler betrieben. Über die Solaranlage kann Strom in das Netz eingespeist werden.

Probleme : 
1) Der Energiezähler Zentrale zweigt N/A (Siehe Anlage)
2) Es gibt keinen Energierzähler Zentrale für die Einspeisung, d.h. den zweiten Kanal von GM-ES-TX-WM

In den Versteckten Systemvariablen für die Berechnung per Script sind nur Varaiblen für den ersten Kanal angelegt (Siehe Anlagen).
Es gibt auch Systemvariablen für den Gas-Zähler, obwohl der in meinem System nicht verwendet wird. (siehe Anlage)

### Describe the behavior you expected

Zwei Energiezähler Zentrale, die Einspeisung und Netzentnahme aufadieren.
Zwei Sätze an versteckten Systemvariablen für Einspeisung und Entnahme.

### Steps to reproduce the issue

1. Energiezähler HM-ES-TX-WM mit passenden Zweirichtungszähler 
2. Geräteansicht Öffnen  für HM-ES-TX-WM => Nur ein Zähler mit "n/a" (Siehe Anlagen)
3. oder Systemvariablen mit verstecken Systemvariablen anzeigen, dort gibt es nur einen Eintrag für Kanal 1 von HM-ES-TX-WM (Siehe Anlagen)

### What is the version this bug report is based on?

3.71.12.20231020

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Firmware-Version von HM-ES-TX-WM : 2.5, also aktuell
```

### Additional information

<img width="586" alt="CCU-Fehler_FM-ES-TX-WM Konfiguration" src="https://github.com/jens-maus/RaspberryMatic/assets/11533286/ef234502-dee7-4377-9bed-cb01d02aa1b3">
<img width="878" alt="CCU-Fehler_FM-ES-TX-WM Geräte-Anzeige" src="https://github.com/jens-maus/RaspberryMatic/assets/11533286/86ae250c-89b9-4c65-b00f-70e2a82bb0e1">
<img width="575" alt="CCU-Fehler_FM-ES-TX-WM Systemvariable_Strom" src="https://github.com/jens-maus/RaspberryMatic/assets/11533286/6405c26a-3638-42ad-a0a0-81921612f4c7">
<img width="568" alt="CCU-Fehler_FM-ES-TX-WM Systemvariable_Gas" src="https://github.com/jens-maus/RaspberryMatic/assets/11533286/41e05849-3e73-4022-9e42-c47efc4dd439">

**Comment by jp112sdl** [comment]
Das ist alles by Design so und eher ein Feature Request

**Comment by drose28357** [comment]
Wenn ich das richtig verstanden habe (I might be wrong), sind diese Systemvariablen basierten Zähler der Zentrale durch interne Scripte der RaspberryMatic implementiert. Mit der Implementierung von zwei Kanälen für Zweirichtungszähler durch die Firmware 2.5 ist ja seitens des HM-ES-TX-WM ein funktionaler Update erfolgt, der im UI nicht unterstützt wird. Fühlt sich für mich eher wie ein Bug an.

**Comment by GernotS** [comment]
Bei mir funktionieren beide Richtungen:
![image](https://github.com/jens-maus/RaspberryMatic/assets/8414450/abab5ddd-96ec-4914-9214-ddf72154cc7f)

**Comment by drose28357** [comment]
Das Auslesen der beiden Daten aus dem Zähler im Hausanschluss funktioniert auch bei mir.
Siehe bitte in der Ansicht "Status und Bedienung/Geräte" auf deinen Zählerstand. Dort gibt es bei mir einen zusätzlichen internen Zähler, der in der RaspberryMatic auf der CCU durch Scripte berechnet wird. Diese Scripte funktionieren bei absoluten Zählern (wie diese Zweirichtungszähler) nicht. Daher steht bei diesem berechneten internen Zähler bei mir "na" (etwa "nicht verfügbar"). Vorteil von diesem internen Zähler ist, das man den im UI oder per Programm reseten kann (z.B. für Jahresverbrauch).

**Comment by ChristophCaina** [comment]
also ich habe zwei geräte im Einsatz - einmal einen zwei-Richtungszähler MIT angeschlossener PV und einmal einen zweiwege Zähler ohne PV... wo also nur der eine Zähler auch wirklich läuft.

Bei mir wird auch der Wert "Zentrale" angegeben...
![grafik](https://github.com/jens-maus/RaspberryMatic/assets/26391061/de6dc48a-deed-4544-b674-d7ca57adc9f4)
![grafik](https://github.com/jens-maus/RaspberryMatic/assets/26391061/5a5274d9-6503-4565-af44-21c54e227d3b)

Die Geräte-Einstellungen sind bei mir wie folgt:
![grafik](https://github.com/jens-maus/RaspberryMatic/assets/26391061/2578adac-0a06-495d-8da5-a56dffad0ea1)

Es scheint also m.E. kein Grundlegendes / Generelles Problem der Implementierung in RaspberryMatic zu sein

**Comment by ChristophCaina** [comment]
Ehrlich gesagt, weiß ich nicht mehr, warum ich 1-02:2.7 gewählt hatte... Ich meine, das war aus einer Tabelle, die ich im elv Forum gefunden hatte... 

Bin mir nicht mehr sicher, ob dies mit dem zählertyp zusammen hing...
