### ISSUE TITLE
WebGUI, Bereich Status und Bedienung, CodeText in Spalte Bedienung

### ISSUE THREAD

**Issue by hodiet** [jens-maus/RaspberryMatic#2514]
### Describe the issue you are experiencing

Im WebGUI, im Bereich Status und Bedienung, tauchen sowohl bei Variablen (dann Spalte Status) als auch im Bereich Geräte (egal ob Räume,Gewerke oder Geräte) bei Updates durch veränderte Inhalte zusätzliche Texte auf. Der Text ist immer derselbe, aber nicht in jeder Zeile wird der eingeblendet. Das ist der Text:

if(action == "dcCreate") { Call("datapointconfigurator.fn::dcCreate()"); } 

Er taucht sowohl bei normalen CCU _Geräten (Beispiel Fenster-Sensor HmIP-SWDO-I), CUxD Geräten (Timer) als auch bei Variablen auf. Dabei sind sowohl interne (DutyCycle) als auch Variablen, welche von ccu-Scripten (das bekannte ASTRO-Script als Beispiel) als auch von RedMatic veränderte Variablen auf

Ich kann keinen Zusammenhang zu meinen Scripten herstellen, von dort ist mir dieser Text nicht bekannt.

Mein System: ccu3 mit Raspmatic Version 3.71.12.20231020 (rpi3)
Zusatzsoftware CUxD 2.11, hm_pdetect 1.16, RedMatic 7.2.1
![Bildschirmfoto 2023-11-17 um 09 28 45](https://github.com/jens-maus/RaspberryMatic/assets/44953572/ea56dafb-4924-4d44-a27b-dbfe6ad8489f)
![Bildschirmfoto 2023-11-17 um 09 23 24](https://github.com/jens-maus/RaspberryMatic/assets/44953572/1519385e-0b2f-4aed-92f4-2bc5d4fa33fd)
![Bildschirmfoto 2023-11-17 um 09 22 26](https://github.com/jens-maus/RaspberryMatic/assets/44953572/0fba4d8b-886b-4017-b0a0-d7359a22ec52)

### Describe the behavior you expected

Keine nicht dahin gehörenden Texte einblenden.

### Steps to reproduce the issue

1. Open one of the affected pages form web-ui and wait for updates of values. it is possible to force such an update, e.g. opening a window 
2.
3.
...

### What is the version this bug report is based on?

3.71.12.20231020

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
none
```

**Comment by hodiet** [comment]
Das vierte Bild (Fritz) gehört nicht dazu, wie kann ich das entfernen?

**Comment by jens-maus** [comment]
Duplicate of #1467

**Comment by jens-maus** [comment]
Dieses Problem ist bereits bekannt. Einzige bekannte Lösung aktuell: Neustart der CCU/RaspberryMatic
