### ISSUE TITLE
WEBUI: prototype.js: SyntaxError: Invalid regular expression: nothing to repeat

### ISSUE THREAD

**Issue by gcarls** [jens-maus/RaspberryMatic#2521]
### Describe the issue you are experiencing

Bei Navigation nach Einstellungen - Geräte "hängt" WebUI im Zustand Loading. DIe Liste der Geräte wird nicht angezeigt.
In der Developer Tools Console des Web Browsers gibt es die folgende Fehlermeldung:
SyntaxError: Invalid regular expression: nothing to repeat
bei Ausführung von Prototype.js
<img width="374" alt="image" src="https://github.com/jens-maus/RaspberryMatic/assets/98746887/98b5fd6e-04c5-4d92-afbc-2234c7b26154">

### Describe the behavior you expected

Bei Navigation Einstellungen -> Geräte sollte die Geräteliszte angezeigt werden

### Steps to reproduce the issue

1. Click Einstellungen
2. Click Geräte
3. Loading Animation wird angezeigt. Die Anzeige der Geräteliste bleibt aus
...

### What is the version this bug report is based on?

3.71.12.2023.10.12

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
siehe Screenshot:
prototype.js
SyntaxError: Invalid regular expression: nothing to repeat
```

### Additional information

Als Radio Module wird HB-RF-ETH verwendet

**Comment by gcarls** [comment]
Das scheint eine Browser Inkompatibilität zu sein.
Der Fehler tritt bei mir nur im Safari Browser auf. Firefox ist OK.

**Comment by jens-maus** [comment]
Bis jetzt hat das außer dir noch niemand berichtet? Das für sich alleine genommen ist schon sehr sonderbar und deutet daraufhin das es ein reines Problem deines Systems bzw. deiner Nutzungsumgebung ist. Daher bitte andere Leidensgenossen finden wäre der erste Ansatz...

**Comment by gcarls** [comment]
Fehler gefunden:
Dieses Problem tritt auf, wenn Devicenamen ein "+" enthalten.
Im vorliegenden Fall war das erste Zeichen im Devicename ein '+'.

**Comment by jens-maus** [comment]
Ok, aber das bedeutet wir müssten hier ggf. in den Filtern nachbessern. Deshalb bleibt das Ticket erst einmal offen. Vielleicht kann @jp112sdl hiee ja mal schauen was die Regexp in den Filtern da durcheinander bringen wenn da ein + im Namen ist. Er hatte meiner Erinnerung nach ja die Filter um wildcards usw erweitert..

**Comment by IT-VBFK** [comment]
Kann das daher kommen?

https://github.com/jens-maus/RaspberryMatic/blob/262d37745a94d0d1bd3b2d2e0e15b09a0fde8e47/buildroot-external/patches/occu/0170-WebUI-RegexSearchInDeviceLists.patch#L7-L13

**Comment by jens-maus** [comment]
Kann gut sein das es daher kommt. Kam selbst noch nicht das in der webui nachzustellen und zu debuggen... wurde ja auch gesagt das es ggf. auch browserabhängig ist. Muss man also mal debuggen dort..

**Comment by Baxxy13** [comment]
Also mit "Chromium based Browsern" kann ich das auch nicht reproduzieren.
Egal ob ein Namensfilter gesetzt ist oder nicht.
![RM_plus_vor_Geraetenamen](https://github.com/jens-maus/RaspberryMatic/assets/54898249/cddb4036-bda6-4396-ad2d-188431dc16d5)

**Comment by IT-VBFK** [comment]
> Der Fehler tritt bei mir nur im Safari Browser auf. Firefox ist OK.

Kann das nicht nachvollziehen.. Bei mir (ebenfalls Safari) und einem Gerät mit einem `+` im Namen.. kein Fehler in der Konsole und die Geräteliste lädt ebenfalls korrekt.

Auch die Suche (beides: als Regex oder nicht) funktioniert, sowohl Suche nach dem jeweiligen Gerät, als auch die Suche nach einem beliebigen Anderen.

**Comment by gcarls** [comment]
Nachdem ich die "+" aus den Devicenamen entfernt habe war der Fehler verschwunden. Ich habe aber eben weiter experimentiert und festgestellt, dass ein + im Filter reicht um den Fehler hervorzurufen.
Ich habe nur "+UV1" im Filter der Spalte "Name" eingegeben, nach Bestätigung passiert zunächst nichts. Verlässt man die Liste und geht anschließend wieder über Einstellungen und Geräte in die Liste, hängt die Liste. 
 Dummerweise merkt sich der Browsercache dieses Suchkriterium. Wenn man die Liste verlässt und anschließend wieder über Einstellungen/Geräte in die Liste wechselt bleibt es wieder mit der obigen Fehlermeldung hängen.
Erst das Löschen des Browsercache löszt das Problem.
Bei mir ist das Probklem im Firefox nur deswegen nicht aufgetreten, weil im cache des Firefox kein Suchkriterium mit "+" gespeichert war.
Durch obige Vorgehensweise ließ sich das Problem bei mit in Firefox und Safari nachstellen.

**Comment by Baxxy13** [comment]
Ah ja, mit dem "+" im Filter bekomme ich das jetzt auch reproduziert.

**Comment by IT-VBFK** [comment]
Ahh.. damit kann ich es reproduzieren.

Ich glaube es liegt hier nicht an RM oder sonstiger Logik.. Der Regex is hier einfach fehlerhaft. `+` im Regex bedeutet, dass der vorangehende Token (in dem Fall "") > 1x vorkommen muss.

Das passt auch zum Fehler: "...nothing to repeat".

Behen lässt sich das ganze indem man das `+` escaped; also `\+UV` würde gehen

**Comment by jens-maus** [comment]
Dann müsste man prüfen ob es ggf. irgendeine Funktion gibt um erst prüfen zu lassen ob der eingegebene Suchstring auch ein valider mit/ohne Regexp ist um dann Event das new Regexp aufzurufen oder eben nicht... So wäre zumindest mein Ansatz.

**Comment by IT-VBFK** [comment]
Straight forward wäre das dann sowas hier:

```js
let text = '+Hello$world+';
text = text.toLowerCase();
let regexString = '+Hello.*'.toLowerCase();

function isValidRegex(possibleInvalidRegex) {
  try
  {
    const r = new RegExp(possibleInvalidRegex);
  }
  catch (err){
    return false;
  }
  
  return true;
}

if(isValidRegex(regexString)){
  const r = new RegExp(regexString);

  if(r.test(text) === true){
    console.log("True");
  }
}

```

**Comment by jens-maus** [comment]
Sowas in der Art, ja. Wundert mich aber das es da nicht schon was fertiges/vorhandenes bei Tante Google gibt...

**Comment by IT-VBFK** [comment]
Naja.. das war von Onkel StackOverflow :D

**Comment by jens-maus** [comment]
Na dann her mit dem PR sodass dieses Problem dann hoffentlich nicht mehr auftritt in Zukunft...

**Comment by IT-VBFK** [comment]
Alles klar :)

Da das ja erst meine zweite contrib ist.. ich hoffe ich habe alles korrekt ausgeführt :)

**Comment by jens-maus** [comment]
Ja, das passt leider nicht! Die Webui.js muss erst ein einzelne Zeilen mit \n umgewandelt werden bevor man Änderungen in dem Bereich vornehmen kann. Also bitte nochmal nacharbeiten und/oder einfach mal das diff deiner Änderung da mit einpflegen/zeigen.

**Comment by IT-VBFK** [comment]
Ok. Habs mir fast gedacht :)

Gibts dafür irgendein script?

**Comment by jens-maus** [comment]
Ein Script nicht direkt leider. Aber das folgende Kommando sollte aus der webui.js mit gewrappten Zeilen eine machen die dann auf mehrere Zeilen umgewandelt ist damit man die dann entsprechend bearbeiten kann:

```
sed -i '1,10s/\\n/\\n\n/g' webui.js
```

Und dann legt man die dort im Patchverzeichnis ab und nutzt immer die, denn der Build Skript baut die dann automatisch wieder zusammen mit der Gegenteiligen Operation.

Da ist leider die webui.js ein special case wegen diesen gewrappten \n Zeilen wie eQ3 die in OCCU ausliefert...

**Comment by IT-VBFK** [comment]
Ok, dh. zum committen des Patches
1) `\n` unwrap mit erstem Kommando 
2) Änderungen durchführen, Patch erzeugen, committen
3) `\n` wrap mit zweitem Kommando

Ich kann das leider nicht testen, da ich keine Testumgebung habe; das Docker-Image kann ich schon bauen, aber ohne Funkmodul wird das Starten nichts

**Comment by IT-VBFK** [comment]
Ok, jetzt hab ichs denke ich :)

**Comment by jens-maus** [comment]
Ok, hab den PR nach keinen Änderungen und einem Fix meinerseits nun mal gemerged. Bitte mit dem nächsten nightly snapshot schauen ob nun alles passt.
