### ISSUE TITLE
manifest unknown

### ISSUE THREAD

**Issue by efmaster** [jens-maus/RaspberryMatic#2523]
### Describe the issue you are experiencing

Das Addon kann nicht installiert werden.
Es kommt zu einer Fehlermeldung. Auch das manuelle ziehen des Docker-Images bringt nichts =>
"manifest unknown".

### Describe the behavior you expected

the addon should be installed

### Steps to reproduce the issue

1.try to install on a new new homeassistant device
2.
3.
...

### What is the version this bug report is based on?

3.71.12.20231020

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
-
```

**Comment by efmaster** [comment]
sorry .. its a raspberry pi 4.

**Comment by Baxxy13** [comment]
Kann ich soweit für Pi4B bestätigen:
Core 2023.11.2
Supervisor 2023.11.3
Operating System 11.1
Frontend 20231030.2
![HA_Pi4B_RM_AddOn_cant_install](https://github.com/jens-maus/RaspberryMatic/assets/54898249/95fd48c2-710c-4a44-b5fb-0e0da72a76b2)

**Comment by jens-maus** [comment]
Oh, und was ist mit dem nightly snapshot?

**Comment by Baxxy13** [comment]
Updaten des Nightly ging gerade.
Ich versuche mal ne Neuinstallation.

**Comment by jens-maus** [comment]
Ja scheint nur den letzten offiziellen Release zu betreffen. Komisch. Siehe:

```sh
:~$ docker pull ghcr.io/jens-maus/raspberrymatic:3.71.12.20231020@sha256:d9496248f57f3daa2b3b1fe632dbc7dbc135f15473df353639f8efb3be8dfc57
Error response from daemon: manifest unknown
:~$ docker pull ghcr.io/jens-maus/raspberrymatic:3.71.12.20231020@sha256:d9496248f57f3daa2b3b1fe632dbc7dbc135f15473df353639f8efb3be8dfc57
Error response from daemon: manifest unknown
:~$ docker pull ghcr.io/jens-maus/raspberrymatic:3.71.12.20231020@sha256:2deb1728b52c1efb59dfdce76d7c6ce83a26347ce00621935e10338fad27c57b
Error response from daemon: manifest unknown
:~$ docker pull ghcr.io/jens-maus/raspberrymatic:3.71.12.20231020@sha256:27029763cb60c88e74e749adc569740316d25892fcc3c2ec29ff5039fb4b3664
Error response from daemon: manifest unknown
:~$ docker pull ghcr.io/jens-maus/raspberrymatic:3.71.12.20231020@sha256:987d65d4d603831178b9bd0afe8bdd62de4e9c6eae8489e2a08d4f04ddd58c52
Error response from daemon: manifest unknown
:~$ docker pull ghcr.io/jens-maus/raspberrymatic:3.71.12.20231020
3.71.12.20231020: Pulling from jens-maus/raspberrymatic
manifest unknown
```

Komisch das hier anscheinend der container irgendwie in der GitHub container registry kaputt gegangen ist....

**Comment by efmaster** [comment]
Genau .das Nightly geht Problemlos :-)

**Comment by jens-maus** [comment]
Ok, dies scheint hiervon zu kommen:

https://github.com/snok/container-retention-policy/issues/43

D.h. der nächtliche Aufräumjob der alte, obsolete docker container löscht/rauswirft scheint hier zu fleissig zu sein.

**Comment by Baxxy13** [comment]
Unschön. 
Man kann ja auch nicht einfach so zum Nightly wechseln wenn man das AddOn mittels "Homematic(IP) Local" integriert hat.
(anderer Hostname)
Ich bleibe dabei und meide das AddOn.

**Comment by efmaster** [comment]
Das ganze betrifft doch nur Neuinstallationen, von daher sehe ich das persönlich unkritisch (wenn auch nicht schön :-) )
Dafür kann man solche Fehler melden.

**Comment by jens-maus** [comment]
Ok, das Problem sollte nun beseitigt sein. Hab die docker images nochmal frisch gepusht und nun sollte eine frische Installation wieder funktionieren.
