### ISSUE TITLE
Universalsensor HB-UW-Sen-THPL-I und HB-UW-Sen-THPL-O 

### ISSUE THREAD

**Issue by erwin23** [jens-maus/RaspberryMatic#253]
Hallo Jens,
kannst du bitte in der RaspberryMatic die Universalsensoren von Dirk  HB-UW-Sen-THPL-I und HB-UW-Sen-THPL-O einbauen. Es git ein Addon, das funktioniert nur auf der CCU2, bei mir läuft es in der LXCCU.
Hier der Link vom Addon https://github.com/kc-GitHub/Wettersensor/releases/tag/v0.14_beta.
Vielleicht gibts ja auch schon ein Vorab von dir zum händischen Einpflegen.
Beste Grüsse und Dank im voraus von Erwin

**Comment by jens-maus** [comment]
Meiner Meinung nach sollte der Autor dieses Addons die notwendigen Anpassungen machen damit das Addon auch unter RaspberryMatic funktioniert.

**Comment by erwin23** [comment]
Hallo Jens,
Sehe ich auch so, nur ist der Entwickler und Vertreiber dieser Sensoren imFHEM Board seit einem Jahr nicht mehr unterwegs. Ich, mit meiner kleinen Ahnung in der Linux Shell scheitert schon mit dem Einspielen der Dateien z. B. unter firmware/rftypes, Schreibschutz des Dateisystemes.
Arbeite sonst mit Ubuntu, aber wenig in der Shell.
Beste Grüße aus Bremen erwin23


Am 8. Februar 2018 10:44:59 MEZ schrieb Jens Maus <notifications@github.com>:
>Meiner Meinung nach sollte der Autor dieses Addons die notwendigen
>Anpassungen machen damit das Addon auch unter RaspberryMatic
>funktioniert.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jens-maus/RaspberryMatic/issues/253#issuecomment-364056603

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by jp112sdl** [comment]
@jens-maus 
Ich würde mich der Sache annehmen, bzw. scheitere nur an einem Problem:
Kann ich aus dem Installations-Prozess eines Addons das Root-Verzeichnis nicht rw mounten?
Es müssen Dateien nach /firmware/rftypes kopiert werden.
Rufe ich das update_script aus der Shell heraus auf, läuft auch alles einwandfrei durch.
Auch `mount -o remount,rw /` funktioniert.
Jedoch nicht, wenn ich es über die WebUI einspielen möchte.

Kennst du eine Dokumentation, wie ein HomeMatic Addon aufgebaut sein muss?

**Comment by jens-maus** [comment]
@jp112sdl 

Eigentlich sollte man sowas generell nicht machen. D.h. ein Addon sollte eigentlich nicht irgendwas im RootFS modifizieren. Allerdings macht das selbst CUxD weil es manche Dinge gibt die nicht anders zu lösen sind. Man muss nur eben sehr vorsichtig vorgehen und das ganze so designen das die Modifikationen selbst ein Firmware-Update überleben. D.h. die Modifikationen des RootFS sollten im init script vorgenommen werden und nicht über die `update_script` Installationsroutinen des Addons selbst.

Dokumentation gibt es dazu leider nicht. Allerdings kannst du dir das ganze ja von existierenden Addons mal abschauen. z.B. eben bei cuxd:

https://github.com/jens-maus/cuxd

Dort findest du ein "generate_img.sh" das das tar.gz generiert mit allen notwendigen dingen. Die besagten Modifikationen des RootFS findet man im rc.d Skript:

https://github.com/jens-maus/cuxd/blob/master/common/rc.d/cuxdaemon

Allerdings solltest du nicht wie CuxD eine eigene init datei in /etc/init.d anlegen sondern wie bei anderen Addons üblich eine init datei in /usr/local/etc/rc.d ablegen.

**Comment by jp112sdl** [comment]
@jens-maus 
Danke für die ausführliche Antwort!
Ich verstehe die Bedenken bzgl. des root-fs.
Jedoch gibt es leider keinen user-space für xml-Deskriptoren.

Mit dem Umweg über rc.d wird das Ganze unnötig komplex und (mir zu) kompliziert.

Einerseits handelt es sich auch nicht wirklich um ein Addon - es werden lediglich ein paar Dateien verteilt - und andererseits ist es auch nicht mit großem Aufwand verbunden, das update_script von Hand auf der Shell auszuführen (wo sich auch / rw mounten lässt).

Vielen Dank!

**Comment by jens-maus** [comment]
@jp112sdl 

Das ist kein Umweg, das ist der einzig mögliche, spezifizierte und sinnvolle Weg. Du kannst im update_script nicht das rootfs rw remounten, das kannst du nur beim hochfahren. Und komplexer oder komplizierter ist das auch nicht, eben nur eine rc.d datei ablegen und fertig. 

Und es ist in der Tat ein Addon das du korrekt und mit ordentlicher rc.d datei in /usr/local ablegen solltest wie das andere Addons auch machen und dann auch Uninstall Routinen zur verfügung stellen solltest damit man das alles auch geordnet entfernen kann. Alles andere ist nicht spezifiziert und gelinde gesagt pfusch :)

Auch das update_script manuell innherlab eines laufenden Systems einfach in einer SSH Sitzung auszuführen sollte nicht gemacht und auch nicht irgendwelchen Leuten angeraten werden!

**Comment by jp112sdl** [comment]
Ja, das ist wohl "quick & dirty". Es ist dann halt nur die Lösung für mich...

Hatte gehofft, dass es

**Comment by erwin23** [comment]
Hallo Jens,
Ich finde den Ansatz von Jerome gehabt. Die Dateien im /Top ausgepackt und dann ein Script laufen lassen. Ich glaube das können die meisten. Der Weg über rc.d erscheint mir auch zu aufwendig, schon gar nichts mit meinem gesunden Halbwissen.
Beste Grüsse

Am 11. Februar 2018 14:25:12 MEZ schrieb "Jérôme" <notifications@github.com>:
>@jens-maus 
>Danke für die ausführliche Antwort!
>Ich verstehe die Bedenken bzgl. des root-fs.
>Jedoch gibt es leider keinen user-space für xml-Deskriptoren.
>
>Mit dem Umweg über rc.d wird das Ganze unnötig komplex und (mir zu)
>kompliziert.
>
>Einerseits handelt es sich auch nicht wirklich um ein Addon - es werden
>lediglich ein paar Dateien verteilt - und andererseits ist es auch
>nicht mit großem Aufwand verbunden, das update_script von Hand auf der
>Shell auszuführen (wo sich auch / rw mounten lässt).
>
>Vielen Dank!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jens-maus/RaspberryMatic/issues/253#issuecomment-364751419

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by jens-maus** [comment]
Natürlich geht das prinizipiell, muss dann aber nach jedem update von RaspberryMatic erneut durchgeführt werden und ist potentiell gefährlich und hart einfach ein „dirty hack“

**Comment by jp112sdl** [comment]
Ich bin ja des Lernens willig :) und auch gerade dabei, mir die Installationspakete verschiedener Addons anzuschauen. 
Ich befasse mich heute das erste Mal mit sowas... also es wird sicher nicht in 20 Minuten fertig sein - aber im Laufe der Woche - hoffe ich :) 

Ich hab nur noch nicht verstanden, weshalb es gefährlich ist, schon direkt im Installationsskript das rootfs rw zu mounten und die Dateien zu kopieren. 
Der Umweg über rc.d, bei dem letztlich auch nur ein Skript aufgerufen wird, das dasselbe macht (denn anders bekommt man die Dateien wohl nicht nach /firmware kopiert), wäre ja genau so gefährlich.

Aber der Vorteil liegt dennoch klar auf der Hand - über diesen Weg können die Files im /usr/local liegen und sind somit im Backup enthalten bzw. nach einem Update + Restore wieder mit drin.

**Comment by jp112sdl** [comment]
@erwin23 
Ging nun doch schneller als gedacht... vielleicht kannst du es mal testen. Bei mir lief es zumindest durch. 
Hab nur noch keinen HB UW Sensor zum Anlernen.
Die angehängte ZIP-Datei musst du entpacken - die darin enthaltene .tgz kannst du dann installieren.
Ein direktes Anhängen der .tgz war hier nicht möglich. 

[hb.tgz.zip](https://github.com/jens-maus/RaspberryMatic/files/1714815/hb.tgz.zip)

**Comment by erwin23** [comment]
Hallo Jens,

habe das Addon gerade in eine jungfeuliche Raspberryimatic eingespielt.

Sieht genausso aus wie meine händisch editierten Eintragungen, also o.k.

Habe auch den HB-UW-Sen-THPL-I angelernt, funktioniert auch. Heute abend oder morgen kann ich

mir einen HB-UW-Sen-THPL-O ausleihen und dann anlernen. Melde mich dann.

Besten Dank für deine Super Arbeit.

cu erwin23


Gesendet: Sonntag, 11. Februar 2018 um 21:42 Uhr
Von: Jérôme <notifications@github.com>
An: jens-maus/RaspberryMatic <RaspberryMatic@noreply.github.com>
Cc: erwin23 <erwin23@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [jens-maus/RaspberryMatic] Universalsensor HB-UW-Sen-THPL-I und HB-UW-Sen-THPL-O (#253)


@erwin23
Ging nun doch schneller als gedacht... vielleicht kannst du es mal testen. Bei mir lief es zumindest durch.
Hab nur noch keinen HB UW Sensor zum Anlernen.
Die angehängte ZIP-Datei musst du entpacken - die darin enthaltene .tgz kannst du dann installieren.
Ein direktes Anhängen der .tgz war hier nicht möglich.

hb.tgz.zip

**Comment by jp112sdl** [comment]
@erwin23 
Das hört sich gut an!

Ich habe mir den Sketch gestern mal bei mir geflasht. 
Das Anlernen klappt leider nicht. 
Können wir uns außerhalb dieses Issue, weil es hier fehl Platz ist, über das HB UW Projekt unterhalten?
Ich habe zu diesem Zweck in meinem Repository einfach mal ein [Issue](https://github.com/jp112sdl/Beispiel_AskSinPP/issues/1) eröffnet.
Wäre nett, wenn du dort mal einen "Hallo"-Beitrag hinterlassen kannst, dann kann ich darauf antworten und du bekommst auch die Benachrichtigungen darüber.

Vielen Dank!

@jens-maus 
Ich glaub, das kann dann hier geschlossen werden.

**Comment by jens-maus** [comment]
@erwin23 Das ist nicht meine Arbeit. @jp112sdl hat das Addon angepasst und ihm gebührt der Dank. 

Allerdings sollte das überarbeitete Addon nun jedoch einen anderen Platz als hier finden und am besten direkt ein neues GitHub Projekt werden das ich dann auch gerne als unterstütztes Addon hier benennen kann.

Allerdings hätte ich nach Durchsicht des Addons noch folgende Hinweise and @jp112sdl:

1.  das `installHBUW` sollte im rc.d `start` nur aufgerufen werden wenn die Modifikationen wirklich notwendig sind. Momentan wird das bei jedem neuen booten wieder aufgerufen. Hier sollte ein Versionscheck eingebaut werden und dann nur die dinge dort erledigt werden wenn sie wirklich notwendig sind. Momentan wird jedesmal das rootfs als rw remountet was potentiell gefährlich sein kann.
2. das `update-check.cgi` fehlt im bundle incl. eines brauchbaren links zur Projektseite des Addons.

Ich werde nun aber auf jeden fall dieses ticket hier schliessen denn das ganze hat mit RaspberryMatic nicht wirklich etwas zu tun sondern gehört in das "HB UW Projekt"
