### ISSUE TITLE
Kommunikationsstörung HmIP-DRDI3 nach Update auf V1.4.8

### ISSUE THREAD

**Issue by cRemE-fReSh** [jens-maus/RaspberryMatic#2533]
### Describe the issue you are experiencing

After updating HmIP-DRDI3 to version 1.4.8, different users experience communication issues. The device neither communicates nor it's able to (re-)couple.

Users describe that it works with the HmIP-HAP combined with the Homematic Cloud / App.

References:
https://homematic-forum.de/forum/viewtopic.php?p=786788#p786788
https://de.elv.com/forum/hmip-drdi3-update-auf-1.4.8-fuehrt-zu-geraeteausfall-27739

### Describe the behavior you expected

Working communication.

### Steps to reproduce the issue

1. Update to V1.4.8.
2. Test it.

### What is the version this bug report is based on?

3.71.12.20231020

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
-
```

**Comment by cRemE-fReSh** [comment]
User Christoph93 describes in the linked ELV topic, that it works with Nightly Build 3.73.9.20231128.

@jens-maus It would be great to have an release soon, provided this is confirmed.

**Comment by jens-maus** [comment]
> User Christoph93 describes in the linked ELV topic, that it works with Nightly Build 3.73.9.20231128.

If this is the case, there is no reason for this issue ticket here. What is already fixed/working in a nightly snapshot/build does not need to be reported (again). Thus, closing. And the official release will come when 3.73.x is officially released by eQ3.

**Comment by Baxxy13** [comment]
eQ-3 hat im Firmware-Update-File eine falsche "Min-Version" für die CCU3 angegeben.
`CCU3FirmwareVersionMin=3.51.6`

Damit dürften viele DRDI3 Nutzer, die neue Firmware gleich installieren, auf die Nase fallen.
Sehr unschön.
