### ISSUE TITLE
Home Assistant Ingress not Working Correct

### ISSUE THREAD

**Issue by minmaxat** [jens-maus/RaspberryMatic#2534]
### Describe the issue you are experiencing

Since the latest Update i mostly cannot access the Web UI through Home Assistant. When i click on the Sidebar-Icon its is Downloading a index.htm -> if i reboot the RaspberryMatic CCU Addon it works a little time.
The Devices seem to work normaly while the Web UI dont. 

### Describe the behavior you expected

a click on the Sidebar should open the Web UI

### Steps to reproduce the issue

1. Click on the Web UI

### What is the version this bug report is based on?

3.71.12.20231020

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Home Assistant Yellow, 2023.11.3
```

**Comment by minmaxat** [comment]
It seems that this behaviour appears only if on device have an FW-Update Available - if all Devices are up to Date or the FW-Update is not ready to install yet it is working

**Comment by jens-maus** [comment]
Please provide a screencast where this issue is demonstrated.

**Comment by minmaxat** [comment]
![Aufnahme #1](https://github.com/jens-maus/RaspberryMatic/assets/79483719/0cf97497-d413-4e37-aba5-992926b16eac)
this Morning the Same Save As Happend when i click on Benutzeroberfläche öffnen in the Add on

**Comment by jens-maus** [comment]
Sorry, but I can't reproduce this issue. So please try to open the browser console yourself and try to debug what is going on here. Especially strange is that while in the sidebar it obviously does not work (as seen in your screencast) the link on the Addon page works as expected as it seems. That is quite odd and could point to a generic HomeAssistant issue rather than to a RaspberryMatic addon issue...

**Comment by jens-maus** [comment]
Sorry, but I have extensively tested it and cannot reproduce it in different browser engines.

**Comment by Bascht74** [comment]
Hi, I freshly installed the HA add-on on two systems: a Pi4 with 8GB and HAOS on it and an Ondroid N2 with HAOS on it. 
On both systems I got the same result as @minmaxat . It tries to download an index.htm file. If you do and open it, it says "Error fetching proxied request: aborted"
