### ISSUE TITLE
Status LED`s der CCU

### ISSUE THREAD

**Issue by audiraudi** [jens-maus/RaspberryMatic#254]
Hallo
Wäre es sehr aufwendig die Status LED`s der CCU mit in den Rapy zu übernehmen?

Ich hoffe das ich kein Einzelgänger bin der mehrmals täglich einen Blick auf seine CCU wirft um mit diesem einen kurzen Blick zu erkennen ob es nötig ist den Rechner an zu machen um im WebUI nachsehen zu müssen was los ist.

**Comment by jens-maus** [comment]
Ein direktes Abbilden der CCU Status LEDs ist nicht möglich (die CCU hat 3, der RaspberryPi maximal zwei). Auch muss man sagen gehört so ein RaspberryMatic in den Schaltschrank, in den Keller aber sicher nicht auf den Schreibtisch damit man damit gar den WebUI-Status überprüfen können muss.

In der nächsten Version werden allerdings die LEDs des RaspberryPi den aktuellen Hardwarestand wiedergeben. D.h. die Grüne LED wird bei erfolgreichem, hochgefahrenem RaspberryMatic einen grünen heartbeat abgeben und die rote LEDs im Sekundentakt blinken wenn es am Booten oder herunterfahren ist. Damit kann man dann zumindest den Stand der Hardware bzw. des laufenden Systems überprüfen. Den WebUI Status oder gar ein blinken bei WebUI Events umzusetzen ist IMHO zuviel des guten.

**Comment by audiraudi** [comment]
Danke für die schnelle Antwort. 
Eine Frage dazu allerdings noch, werden die LED`s in der zukünftigen Firmware einstellbar sein über die HM  Oberfläche ?oder sind dies einfach dann feste Bestandteile des Programms ?

**Comment by jens-maus** [comment]
Da wird genausowenig/viel von der WebUI einstellbar sein wie bei der CCU2. Wenn man allerdings weiss wie (an das homematic forum wenden) dann kann man die LEDs zur Laufzeit abändern wie man lustig ist.
