### ISSUE TITLE
HmIP DLD sometimes report wrong ACTIVITY_STATE

### ISSUE THREAD

**Issue by ZTHawk** [jens-maus/RaspberryMatic#2550]
### Describe the issue you are experiencing

My setup:
- Fingerprint scanner
- HmIP FWI
- HmIP DLD

Most of the time I get state changes as expected, but sometimes are are weird.
When using the fingerprint scanner to open the door (unlock + open) then the ACTIVITY_STATE is sometimes "Locking".

Values that I see in HomeAssistant (see attached protocolls from RaspberryMatic; the seconds information is comming from HA; protocol: [RM_History - Kopie.csv](https://github.com/jens-maus/RaspberryMatic/files/13610510/RM_History.-.Kopie.csv)):
- The DLD is in state "Unlocked"
  - I use the Fingerprint scanner
- DLD changed to "Is locking" (16:01:51)
- DLD changed to "Is Unlocking" (16:01:52)
- DLD changed to "Was unlocked" (16:01:53)

Sometimes I have also this behaviour:
- The DLD is in state "Unlocked"
  - I use the Fingerprint scanner
- DLD changed to "Is locking"
- DLD changed to "Was unlocked"

And sometimes I have this behaviour:
- The DLD is in state "Unlocked"
  - I use the Fingerprint scanner
- DLD changed to "Is Unlocking" (14:13:34)
- DLD changed to "Is locking" (14:13:35)
- DLD changed to "Was unlocked" (14:13:37)

I have discovered this issue through HA and posted it first in the HA HmIP local repository: https://github.com/danielperna84/hahomematic/issues/1314

### Describe the behavior you expected

- The DLD is in state "Unlocked"
  - I use the Fingerprint scanner
- DLD changed to "Is Unlocking"
- DLD changed to "Was unlocked"

### Steps to reproduce the issue

Not reproducable easily. It happens randomly.

### What is the version this bug report is based on?

3.73.9.20231130

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Logs have been overwritten already.
```

**Comment by ZTHawk** [comment]
This is still applicable (happened yesterday).

**Comment by BadBull86** [comment]
I have the same problem:
Pressed the open door button -> state switched to IS LOCKING for a second and switches then to IS UNLOCKING.

happens I would say 1 of 30 times

**Comment by ZTHawk** [comment]
Still applicable (RM v3.77.7.20240826 and DLD v1.4.12)
