### ISSUE TITLE
1wire usb not working anymore

### ISSUE THREAD

**Issue by hooker78** [jens-maus/RaspberryMatic#2552]
### Describe the issue you are experiencing

After upgrading to **3.73.9.20231130** the 1wire interface is not available anymore.

`cat /sys/bus/w1/devices/28-000001de1d0d/w1_slave`
gives error message:

`cat: can't open '/sys/bus/w1/devices/28-000001de1d0d/w1_slave': No such file or directory`

The folder w1 is not available.

### Describe the behavior you expected

expected behaviour is printing out temperatures like this:

```
a0 00 4b 46 7f ff 10 10 53 : crc=53 YES
a0 00 4b 46 7f ff 10 10 53 t=10000
```

### Steps to reproduce the issue

1.
2.
3.
...

### What is the version this bug report is based on?

3.73.9.20231130

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
root@homematic-raspi:/sys/bus# lsusb
Bus 001 Device 007: ID 04fa:2490
Bus 001 Device 001: ID 1d6b:0002
Bus 001 Device 003: ID 0424:2514
Bus 001 Device 002: ID 0424:2514 
```
This here is the device, it is available when plugged in the usb port: **Bus 001 Device 007: ID 04fa:2490**

### Additional information

Downgrading to **3.71.12.20231020** re-enabled the 1wire connection again.

**Comment by jens-maus** [comment]
> After upgrading to **3.73.9.20231130** the 1wire interface is not available anymore.
> 
> `cat /sys/bus/w1/devices/28-000001de1d0d/w1_slave` gives error message:
> 
> `cat: can't open '/sys/bus/w1/devices/28-000001de1d0d/w1_slave': No such file or directory`
> 
> The folder w1 is not available.

That's correct. With development on 3.73.9.20231130, the kernel dependencies were revised and as 1wire usability was never officially part of RaspberryMatic it was disabled in the kernel to save same resources/dependencies.

Please outline your exact use-case (which device are you trying to integrate) so that we can evaluate to potentially re-enable 1wire support in some upcoming version again.

**Comment by hooker78** [comment]
thank you for the confirmation.
I am using a DS9490R USB Dongle that connects to various 1wire temp sensors for measuring water and air temperature. The values a read out in a HM script using a system exec and then written into a systemvariable for further usage and information to display.

If this could be somehow re-enabled I would be very happy.
