### ISSUE TITLE
Alarm- oder Servicemeldungen

### ISSUE THREAD

**Issue by Mephisto090** [jens-maus/RaspberryMatic#2561]
### Describe the issue you are experiencing

Hallo,

ich habe eine Fehlermeldung (F1, 'Ventil schwergängig / Ventil klemmt') an meinem HmIP-eTRV-2 Heizungsthermostat.
Leider wird mir der Fehler nicht in der Servicemeldung oder Alarmmeldung angezeigt.

### Describe the behavior you expected

Eine Übersicht der Fehler der Geräte. Ich will nicht jeden tag diese überprüfen müssen

### What is the version this bug report is based on?

3.73.9.20231130

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

[homematic-raspi-2023-12-14.log](https://github.com/jens-maus/RaspberryMatic/files/13672862/homematic-raspi-2023-12-14.log)

**Comment by Maik2208** [comment]
Kann ich bestätigen. Servicemeldungen wurden die Tage noch angezeigt und waren plötzlich von der Startseite verschwunden. Seit dem ist dort alles auf Null, in der Geräteliste sind sie noch da.

Was zwischenzeitlich vorgefallen ist weiß ich leider nicht.

**Comment by Baxxy13** [comment]
Kann mal jemand einen Screenshot zeigen, wo da welche Servicemeldungen angezeigt werden?

@Mephisto090 du solltest mal deine ioBroker-Verbindung in Ordnung bringen, da wird dir alle paar Minuten ein ERROR generiert.

`2023-12-14 10:03:35,875 de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer ERROR [vert.x-worker-thread-4] IO Exception: Could not add interface: iobroker:hm-rpc.0:4fd3241b7ba034eec6c0c9860da8dd33`

**Comment by Maik2208** [comment]
Hier sieht es seit paar Tagen plötzlich gut aus:
![image](https://github.com/jens-maus/RaspberryMatic/assets/79879510/a99bc0ae-ce42-4b0a-a3b4-459c93ec8621)

Aber es gäbe definitiv etwas zum Meckern:
![image](https://github.com/jens-maus/RaspberryMatic/assets/79879510/43c4bf15-da18-490b-8f1d-c460e6af966e)

**Comment by Baxxy13** [comment]
Ok, und was davon ist "wahr"? 
Hast du ggf. die Servicemeldungen für den SRH deaktiviert?

**Comment by Maik2208** [comment]
Nein, nicht deaktiviert:
![image](https://github.com/jens-maus/RaspberryMatic/assets/79879510/c70ccbbc-8fbc-4780-80fb-4219ebea282f)

Tatsache ist, dass seit ein paar Wochen dort die Batterie leer ist und die UNREACH-Meldung definitiv stimmt.

**Comment by Mephisto090** [comment]
> @Mephisto090 du solltest mal deine ioBroker-Verbindung in Ordnung bringen, da wird dir alle paar Minuten ein ERROR generiert.

Ich nutze es erst seit ein paar Tagen.... Ich habe die Verbindung mittlerweile aus, da das mein Raspberrymatic komplett stört und komplett ausbremst und die UI abschmiert. Warum auch immer, wenn du weißt warum, schieß los? :D @Baxxy13

**Comment by Mephisto090** [comment]
![image](https://github.com/jens-maus/RaspberryMatic/assets/85995176/8f0ceb8f-b923-41b1-8b4b-ca7b10b12b73)
![image](https://github.com/jens-maus/RaspberryMatic/assets/85995176/deb316c0-b7a4-4902-9a2d-361f2bbf8535)


Bei mir ist heute leider wieder keine Meldung gekommen

**Comment by Baxxy13** [comment]
Warum bist du so knauserig mit den Screenshots?
Ich habe so eine Meldung noch nie gesehen daher habe ich keine Ahnung wo die auftauchen sollte.
Bitte mal in Gänze zeigen, etwa so:
![RM_eTRV_Bedienung](https://github.com/jens-maus/RaspberryMatic/assets/54898249/dc887170-8bc3-4a48-af4b-669f1ea9726b)

Läuft dein System nun sauber? Wenn nicht, hat es vielleicht damit was zu tun?
Ansonsten könnte es ja auch sein das die eTRV's generell bei solchen Fehlern keine Servicemeldung generieren..

**Comment by Mephisto090** [comment]
> Ich habe so eine Meldung noch nie gesehen daher habe ich keine Ahnung wo die auftauchen sollte.

Der kommt unter Fensterstatus: Verschlossen, genau darunter ist die box

> Läuft dein System nun sauber? Wenn nicht, hat es vielleicht damit was zu tun?

Ja solange die Verbindung zum ioBroker aus ist läuft das System sauber und ohne Probleme

> Ansonsten könnte es ja auch sein das die eTRV's generell bei solchen Fehlern keine Servicemeldung generieren..

Das weiß ich leider nicht und das müsste einer sagen der davon Ahnung hat :D

**Comment by Mephisto090** [comment]
> Warum bist du so knauserig mit den Screenshots?

![image](https://github.com/jens-maus/RaspberryMatic/assets/85995176/2af1943d-1727-42ae-97d2-87dcb3812036)

**Comment by Baxxy13** [comment]
Ah ja, besser. 
Ich konnte das nun auf meinem Testsystem durch simulieren eines schwergängigen Ventils nachstellen. 
Die Information kommt aus Kanal:1 vom Datenpunkt "VALVE_STATE" und generiert keine Servicemeldungen.
Alarmmeldungen generieren Geräte generell nicht. 
Von RaspberryMatic-Seite kann man da nix machen würde ich sagen. 
Das müsste eQ-3 in die Gerätefirmware oder in den HmIP-Server integrieren. Aussichten darauf gehen eher gegen null.

Also kein RaspberryMatic-Problem was gefixt werden müsste/könnte. 
Und als Feature-Request auch ziemlich aussichtslos.

**Comment by Mephisto090** [comment]
Alles klar. Von mir aus kann das dann wohl zu :D

**Comment by Baxxy13** [comment]
Denke ich auch. Kannst du ja selbst schließen.
@Maik2208 müsste ein separates Ticket öffnen da sein Issue nicht mit diesem hier korreliert.
