### ISSUE TITLE
Apple "Home" - Devices nach Update nicht mehr verfügbar

### ISSUE THREAD

**Issue by dennis-zielke** [jens-maus/RaspberryMatic#2565]
### Describe the issue you are experiencing

Nach dem Update der CCU3 auf 3.73.9.20231130 funktionieren die Devices in der Home App nicht. (nicht verfügbar).
Ich nutze in Redmatic die "redmatic-homekit 3.3.0". Diese wird auch nach dem Update "grün" angezeigt - connected.

### Describe the behavior you expected

In der Apple "Home App" sind die von der CCU3 importierten Devices verfügbar.

### Steps to reproduce the issue

1. Durchführen des Updates von 3.71.12.20231020 auf 3.73.9.20231130
2. Devices sind nicht mehr verfügbar in der Home App
3. Restore zurück auf 3.71.12.20231020 alles OK
4.
...

### What is the version this bug report is based on?

3.73.9.20231130

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
.
```

**Comment by jens-maus** [comment]
Da es sich hier um ein Problem mit RedMatic handelt sollte es erst einmal in dem entsprechenden Projekt diskutiert werden und erst wenn bei dieser Diskussion ggf. herauskommt das das Problem an technischen Veränderungen in RaspberryMatic liegt sollte hier ein entsprechendes Ticket aufgemacht werden.
