### ISSUE TITLE
HmIP-RFUSB

### ISSUE THREAD

**Issue by Grewamor** [jens-maus/RaspberryMatic#257]
Das neue HmIP-RFUSB-Modul wird nicht erkannt.
Ist es überhaupt schon möglich, damit Geräte anzulernen?

**Comment by Grewamor** [comment]
Danke für die schnelle Antwort. Habe eben die aktuellste Version (2.31.25.20180120) runtergeladen.
Gibt es auch eine Möglichkeit, die benötigten Infos über SSH abzurufen? Habe leider keine Tastatur zur Verfügung.

**Comment by jens-maus** [comment]
Ja, einfach mal den Inhalt der `/var/hm_mode` datei zeigen.

**Comment by Grewamor** [comment]
HOST=rpi3
HM_MODE=NORMAL
HMRF_DEV=
HMRF_DEVNODE=
HMIP_DEV=HMIP-RFUSB
HMIP_DEVNODE=/dev/ttyUSB0
UART_GPIO=

**Comment by jens-maus** [comment]
Na das sieht doch danach aus das alles korrekt funktioniert. Was genau ist denn dann bitte das Problem? HmIP-Geräte sollten sich damit problemlos anmelden lassen.

**Comment by Grewamor** [comment]
Wenn ich auf "HmIP Geräte anelernen" klicke, ist nach den 30 Sekunden der Posteingang noch immer leer. :-(

**Comment by jens-maus** [comment]
Das alleine sagt ja nicht das der HmIP-RFUSB nicht geht. Eher umgedreht wird ein Schuh draus: wenn er die 30 Sekunden runterzählt dann funktioniert der HmIP-RFUSB und der fehler ist eher beim Gerät bzw. beim Anlernprozess des users zu suchen. D.h. HmIP Gerät werksresetten und nochmal machen. 

Wenn es dann immer noch nicht geht dann ohne Internetzugang anlernen versuchen mit eingäbe der SGTIN und des KEY. Auch mal die Datei `/var/board_serial` anschauen. Wenn da drin eine sinnige Seriennummer zu finden ist sollte von Seiten des HmIP-RFUSB alles i.O. sein.

**Comment by Grewamor** [comment]
Ok, danke für die Hilfe. Ich versuche weiter und melde mich, wenn ich eine Lösung gefunden habe.

**Comment by HMside** [comment]
Hallo Jens, der Stick wird bei mir zwar erkannt, aber es lassen sich keine Geräte anlernen. 

Die `/var/board_serial` ist bei mir leer. 

Die hm_mode:
```
HOST=rpi3
HM_MODE=NORMAL
HMRF_DEV=
HMRF_DEVNODE=
HMIP_DEV=HMIP-RFUSB
HMIP_DEVNODE=/dev/ttyUSB0
UART_GPIO=
```

HMServer Log Level habe ich mal auf DEBUG gesetzt, allerdings werden Funk-Frames eines im Anlernmodus befindlichen Geräts gar nicht angezeigt.

[hmserver.log](https://github.com/jens-maus/RaspberryMatic/files/1731803/hmserver.log)
[messages.log](https://github.com/jens-maus/RaspberryMatic/files/1731804/messages.log)

Klickt man in den Posteingang, erscheint zudem die Meldung "BidCos-RF Anlernmodus konnte nicht aktiviert werden".

Des Weiteren ist mir beim testen aufgefallen, das wenn man den Pi ohne HM-MOD-RPI-PCB betreibt und eine oder mehrere CCUs im Netzwerk betreibt, das es dann zu IP Adresskonflikten kommt. Auch der NetFinder zeigt dann für die CCUs und den Pi die gleiche Adresse an.

**Comment by litti** [comment]
Hallo Andreas,

holen sich die Geräte die IP alle dynamisch? Oder ziehen die Ihre IP-Adresse alle aus demselben Backup :-)
Wenn Du rfd, multimacd und HMServer beendest, kannst Du dann die Firmware-Version des Sticks auslesen? https://homematic-forum.de/forum/viewtopic.php?f=65&t=40808&p=404957#p404957

**Comment by HMside** [comment]
Hallo Andre, alle dynamisch. 

Nur zur Info, das Problem besteht, sofern nur der Stick verwendet wird. Das HM-MOD-RPI-PCB ist nicht aufgesteckt.

Wie genau muss der Aufruf für den Stick lauten?
`/bin/eq3configcmd update-coprocessor -p /dev/ttyUSB0 -t HmIP-RFUSB -c -v`
wirft folgendes aus:
```
2018/02/16 21:00:58.154 <Error> () CCU2CommControllerMod::handleIdentifyEvent(): Coprocessor returned unknown identify string: HMIP_TRX_App.
2018/02/16 21:01:00.143 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
2018/02/16 21:01:00.143 <Error> CCU2CommControllerMod::performIdentify(): Unable to determine coprocessor state.
```

**Comment by Grewamor** [comment]
Habe mir ein neuen Stick bestellt. Damit gibt es sofort problemlos.

**Comment by HMside** [comment]
`/opt/java/bin/./java -jar /opt/HmIP/hmip-copro-update.jar -p /dev/ttyUSB0 -v`
wirft
```
WARNING: The library file '/opt/java-azul/lib/aarch32/client/libjvm.so' is corrupted! Further execution might lead to unexpected behavior. Ensure that you have downloaded the build from http://zulu.org/download/
[dlchck]: Failed to create log file
WARNING: The library file '/opt/java-azul/lib/aarch32/libverify.so' is corrupted! Further execution might lead to unexpected behavior. Ensure that you have downloaded the build from http://zulu.org/download/
[dlchck]: Failed to create log file
WARNING: The library file '/opt/java-azul/lib/aarch32/libjava.so' is corrupted! Further execution might lead to unexpected behavior. Ensure that you have downloaded the build from http://zulu.org/download/
[dlchck]: Failed to create log file
WARNING: The library file '/opt/java-azul/lib/aarch32/libzip.so' is corrupted! Further execution might lead to unexpected behavior. Ensure that you have downloaded the build from http://zulu.org/download/
[dlchck]: Failed to create log file
[DEBUG] Start bootloader ...
[DEBUG] Bootloader running
[DEBUG] Request bootloader version ...
[INFO] SGTIN = 3014f711a000041709adfb68
[INFO] Checking coprocessor firmware version ...
[INFO] Bootloader version = 1.0.12
[DEBUG] Start application ...
[DEBUG] Application 'HMIP_TRX_App' running
[DEBUG] Request application version ...
[DEBUG] Request application version ...
[INFO] Application version = 2.8.6
```

**Comment by jens-maus** [comment]
Diese Ausgaben sind völlig normal. All diese Warnungen über java azul kann man auch ignorieren.

**Comment by jens-maus** [comment]
nach mehreren eigenen Tests muss ich sagen das meiner Meinung nach der HmIP-RFUSB problemlos mit neuen RaspberryMatic Versionen funktioniert. Wenn nicht, dann bitte dieses Ticket erneut öffnen und entsprechende reporten.

**Comment by HMside** [comment]
Hallo Jens, der Stick scheint ja bei mir auch korrekt erkannt zu werden, ich kann aber kein Gerät anlernen und das seltsame ist, das ich eben auch im HMServer Log null traffic sehe. 

Hast bei deinen Tests nur den Stick am Pi und konntest Du dann ein Gerät anlernen? 

Was für Infos brauchst Du noch von mir um es weiter zu analysieren?

**Comment by jens-maus** [comment]
Also hab es mir gerade nochmal prinzipiell angeschaut und eigentlich müsste/sollte das gehen egal ob das HmIP-RFUSB das einzige Device ist oder der HM-MOD-RPI-PCB auch noch aufgesteckt ist. Ich werde es heute Abend aber nochmal mit HmIP-Gerät anlernen probieren. Was genau steht denn in deiner `/var/hm_mode` Datei wenn alles mit angeschlossenem HmIP-RFUSB hochgefahren ist? Zählt die Anlernzeit denn runter? Was steht in der `/var/etc/crRFD.conf` Datei ganz oben als "Adapter.1.Port = XXXX`? Dort sollte `/dev/ttyUSB0` stehen.

**Comment by jens-maus** [comment]
Also ich habe es gerade nochmal mit und ohne HM-MOD-RPI-PCB probiert und ich kann hier problemlos HmIP Devices mit dem HMIP-RFUSB anlernen und auch bedienen. Kann das hier beschriebene Problem also definitiv nicht nachvollziehen und bräuchte mehr Infos wie oben beschrieben damit man schauen kann ob es da wirklich ein Problem gibt oder nicht (wovon ich momentan nicht ausgehe).

**Comment by HMside** [comment]
@jens-maus 
Anlernzeit läuft sauber durch, klickt man in den Posteingang, erscheint die Meldung "BidCos-RF Anlernmodus konnte nicht aktiviert werden". Die board_serial ist nach wie vor leer. HMServer Log zeigt trotz DEBUG Loglevel keine Kommunikation an. Ich werde mir mal einen zweiten Stick zum testen besorgen.

hm_mode:
```
HM_HMIP_DEV='HMIP-RFUSB'
HM_HMIP_DEVNODE='/dev/ttyUSB0'
HM_HMRF_DEV=''
HM_HMRF_DEVNODE=''
HM_HOST='rpi2'
HM_MODE='NORMAL'
HM_RF_SERIAL=''
HM_RTC=''
```

crRFD.conf:
```
# USB HM/IP TRX Adapter Configuration
Adapter.1.Type=HMIP_CCU2
Adapter.1.Port=/dev/ttyUSB0

Config.Dir=/etc/config/crRFD
Config.Include=hmip_user.conf

# Directory Configuration
Persistence.Home=/etc/config/crRFD/data
FirmwareUpdate.BG.OTAU.Home=/etc/config/firmware

# Legacy API Configuration
API.1.Type=XML-RPC
Legacy.Encoding=ISO-8859-1
Legacy.ResponseTimeout=20
Legacy.ReplacementURL=127.0.0.1
Legacy.Parameter.Definition.File=/opt/HmIP/legacy-parameter-definition.config
# Legacy.RemoveUnreachableClients=false
Legacy.AddressPrefix=3014F711A0
Legacy.SwitchTypeAndSubtype=true
Legacy.HandlersFilename=/var/LegacyService.handlers
Legacy.DiscardDutyCycleEvents=true
Legacy.SendUDPServiceMessages=true

# Miscellaneous Configuration
CyclicTimeout.TimerStartMaxDelay=90
CyclicTimeout.TimerCycleTime=600
Legacy.Parameter.ReplaceEnumValueWithOrdinal=true

### Configuration for Inclusion with key server (internet) or local key (offline)
KeyServer.Mode=KEYSERVER_LOCAL
KeyServer.Gateway.URL=secgtw.homematic.com
Vertx.WorkerPoolSize=5
```

**Comment by jens-maus** [comment]
@HMside Ok, das erklärt schon ein bisschen mehr. Schaue ich mir heute Abend noch einmal an.

**Comment by jens-maus** [comment]
@HMside Wie im letzten checkin zu sehen habe ich zwei init skripte angepasst um potentielle Probleme bei der Initialisierung des HmIP-RFUSB zu beseitigen. Kannst du ja mal bei Gelegenheit testen (einfach die Datei `/etc/init.d/S11InitRFHardware` und `/etc/init.d/S12UpdateRFHardware` aus dem repository nehmen und lokal ersetzen)

**Comment by jens-maus** [comment]
Da es keine Rückmeldung gab und bei mir bzgl. HmIP-RFUSB alles geht schliesse ich nunmehr dieses ticket.

**Comment by Soc007** [comment]
Hallo Jens,

ich habe das gleiche Problem, dass die Zeit zwar runter zählt, aber der Türkontakt nicht angelernt wird.

**hm_mode:**
root@homematic-raspi:/var# cat hm_mode
HM_HMIP_ADDRESS='0x149E7A'
HM_HMIP_ADDRESS_ACTIVE='0xB34538'
HM_HMIP_DEV='HMIP-RFUSB'
HM_HMIP_DEVNODE='/dev/ttyUSB0'
HM_HMIP_DEVTYPE='USB'
HM_HMIP_SERIAL='1BE99B38F5'
HM_HMIP_SGTIN='3014F711A000041BE99B38F5'
HM_HMIP_VERSION='2.8.6'
HM_HMRF_ADDRESS=''
HM_HMRF_ADDRESS_ACTIVE=''
HM_HMRF_DEV=''
HM_HMRF_DEVNODE=''
HM_HMRF_DEVTYPE=''
HM_HMRF_SERIAL=''
HM_HMRF_VERSION=''
HM_HOST='rpi4b4g'
HM_LED_GREEN='/sys/class/leds/led0'
HM_LED_GREEN_MODE1='mmc0'
HM_LED_GREEN_MODE2='heartbeat'
HM_LED_RED='/sys/class/leds/led1'
HM_LED_RED_MODE1='timer'
HM_LED_RED_MODE2='mmc0'
HM_LED_YELLOW=''
HM_LED_YELLOW_MODE1='none'
HM_LED_YELLOW_MODE2='none'
HM_MODE='NORMAL'
HM_RTC=''

**crRFD.conf:**

root@homematic-raspi:/var# cat ./etc/crRFD.conf
# USB HM/IP TRX Adapter Configuration
Adapter.1.Type=HMIP_CCU2
Adapter.1.Port=/dev/ttyUSB0 
......

Soweit scheint es ja zu passen. Habe ich eine Möglichkeit festzustellen ob der Stick defekt ist?
Ich habe sonst keine weitern Sticks angeschlossen und das RM ist frisch auf den Raspi4 installiert worden.

**Comment by jens-maus** [comment]
@Soc007 Das hier ist ein ziemlich altes Issue Ticket und die vorherigen Dinge haben ganz sicher nichts mit deiner aktuellen Situation zu tun. Bitte im HomeMatic Forum suchen und klären. Meine aktuelle Vermutung ist das es am Einsatz des RaspberryPi4 liegt. Ein RaspberryPi4 ist leider dafür bekannt eine große Funkstörwolke um sich herum zu haben und gerade auch im Hinblick auf die Nutzung von USB. Also entweder auf einen Pi3 wechseln und noch besser gleich Abstand von diesem veralteten HmIP-RFUSB USB Stick nehmen da dieser leider dafür bekannt ist probleme zu machen. AUf jeden fall brauch man das hier in diesem Beitrag aber nicht weiter zu diskutieren, denn dafür ist ein Diskussionsforum bzw. HomeMatic forum da.

**Comment by Soc007** [comment]
Hallo Jens,

Alles klar und danke für die Info.

Gruß

Soc007
