### ISSUE TITLE
Release 3.73.9.20231130 not booting on Odroid C2

### ISSUE THREAD

**Issue by Jojo-A** [jens-maus/RaspberryMatic#2571]
### Describe the issue you are experiencing

The release version 3.73.9.20231130 seems not to boot on the Odroid C2.

### Describe the behavior you expected

- Normal boot both after update and/or after fresh install
- operation indication by blinking heartbeat LED

### Steps to reproduce the issue

1. update system through web UI 
or
2. flash new system to SD card (tried with two different SD cards)

Both on the updated system as well as on the fresh flashed system the LED does not blink (kernel not running) and the systems are not reachable by ping.

### What is the version this bug report is based on?

3.73.9.20231130

### Which base platform are you running?

odroid-c2 (ODROID C2)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
no logs available because no boot :(
```

### Additional information

1. I tried flashing the previous release which booted without any issues
2. Offtopic: There is (and has always been) this strange behavior that the C2 does not reboot on its own. After the reboot command it shuts down but does not come up again on its own. One has always to power-cycle the C2 after a reboot command has been issued. This was a well known issue even at Hardkernel and in the Armbian community. I think this has been fixed through the device tree, but not sure currently...

**Comment by Baxxy13** [comment]
Siehe: #2546 

Sollte in den Nightly-Snapshots gefixt sein.

**Comment by Jojo-A** [comment]
> Siehe: #2546
> 
> Sollte in den Nightly-Snapshots gefixt sein.

Yeah, this looks like the very same issue indeed :D ! Sorry for not finding that one by myself...
And feeling even more stupid: could you please tell me where to find the nightly builds to download?

**Comment by Jojo-A** [comment]
> > Siehe: #2546
> > Sollte in den Nightly-Snapshots gefixt sein.
> 
> Yeah, this looks like the very same issue indeed :D ! Sorry for not finding that one by myself... And feeling even more stupid: could you please tell me where to find the nightly builds to download?

Found them by myself:
https://github.com/jens-maus/RaspberryMatic/releases/tag/snapshots

I report back when I have tested it.

**Comment by Jojo-A** [comment]
Okay, the resent nightly snapshot boots perfectly fine. I just had to restore my WiFi settings as well as the configuration. But thanks to the previously made backup this restore process was relatively easy.

Thank you!

**Comment by jens-maus** [comment]
Duplicate of #2546
