### ISSUE TITLE
JSON-API: Session-ID läuft nicht ab

### ISSUE THREAD

**Issue by bruns8234** [jens-maus/RaspberryMatic#2573]
### Describe the issue you are experiencing

Eine per Session.Login erhaltene ID nur ab wenn:
- man die Session per Logout beendet
- die Zentrale neu gestartet wird.

### Describe the behavior you expected

Nach einer (ggf. anpassbaren) Zeit sollte die Session-ID ungültig werden, wenn keine Zugriffe auf die API erfolgen.

### Steps to reproduce the issue

1. Funktion "Session.Login" mit einer gültigen Kombi aus Benutzername und Passwort aufrufen
    --> man bekommt eine Session-ID
2. 3 Tage warten  :-)  und in dieser Zeit keine Requests mit dieser Session-ID senden.
3. Eine bel. Funktion, die eine Session-ID erfordert, aufrufen (z.B. "Interfaces.listInterfaces") mit der Session-ID aus Schritt 1.
    -->  Die Zentrale liefert die gewünschten Daten anstatt einem zu erwartenden "Error 400: access denied".

Falls zwischenzeitlich (also zwischen Schritt 1 und Schritt 3) ein Neustart der Zentrale erfolgt wird der Request aus Schritt 3 korrekt mit einem "Error 400: access denied" beantwortet.
Natürlich auch wenn man zwischenzeitlich einen Logout durchführt.

### What is the version this bug report is based on?

3.73.9.20231130

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
Keine Einträge im Log dazu gefunden.
```

### Additional information

Keine Einträge in den Logs dazu gefunden.

**Comment by jens-maus** [comment]
Ist dieses Problem noch relevant? @Baxxy13 kannst du das bitte mal testen und Reporten ob das wirklich ein generelles Problem ist?

**Comment by bruns8234** [comment]
Nach dem ich heute auf die aktuelle RM-Version 3.75.6.20240316 aktualisiert habe hat eine erneute Überprüfung ergeben, dass die Session-ID jetzt abläuft. Damit ist dieser Report hinfällig.
