### ISSUE TITLE
XML-RPC für VirtualDevices liefert teileweise keine Datentyp bei getParamset

### ISSUE THREAD

**Issue by Nall-chan** [jens-maus/RaspberryMatic#2574]
### Describe the issue you are experiencing

Aus einer HM-Heizgruppe (legacy Homematic) wird das Wochenprogramm per getParamset ausgelesen.
Ab dem zweiten Wochenplan wird der `value` von TEMPERATURE und ENDTIME (z.B. P2_ENDTIME_THURSDAY_7) ohne Datentyp ausgeliefert und somit als string statt als float/integer verarbeitet.
getParamsetDescription meldet jedoch die korrekten Datentypen der Parameter.
[getParamsetResponse.txt](https://github.com/jens-maus/RaspberryMatic/files/13759361/getParamsetResponse.txt)
[getParamsetDescriptionResponse.txt](https://github.com/jens-maus/RaspberryMatic/files/13759362/getParamsetDescriptionResponse.txt)

### Describe the behavior you expected

Values sollten immer mit dem korrekten Datentyp ausgeliefert werden. z.B:
```
<value>
	<i4>1440</i4>
</value>
...
<value>
	<double>12.0</double>
</value>
``` 

### Steps to reproduce the issue

1. Zugriff mit Drittsoftware auf den RPC Server der VirtualDevices
2. getParamsetDescription auf MASTER einer Gruppe z.B. INT0000001 als XML-PRC senden
3. Auswerten der Antwort
![fe02340687e4e3c0e28766a7448d7d25a41217b6_2_432x500](https://github.com/jens-maus/RaspberryMatic/assets/12008505/ff1c1bc7-431b-43ac-9db2-826b79a463c9)

### What is the version this bug report is based on?

3.73.9.20231130

### Which base platform are you running?

rpi2 (RaspberryPi2)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
.
```

### Additional information

Tritt eventuell auch sporadisch bei anderen Parametern auf, wie DECALCIFICATION_TIME

**Comment by jens-maus** [comment]
@Baxxy13 lässt sich das von deiner Seite reproduzieren?

**Comment by Baxxy13** [comment]
Tut mir leid, ich bin aktuell in den Osterferien am Hauptsystem. 
Das hat keine HM-Heizgruppen. 
Ich wüsste auch nicht wie ich das prüfen sollte da ich keinen eigenen RPC-Server für solche abfragen nutze.
