### ISSUE TITLE
WebUI System variables (boolean) Toggle

### ISSUE THREAD

**Issue by KnutSchweinfurth** [jens-maus/RaspberryMatic#2577]
### Describe the solution you'd like

Derzeit kann im Menüpunbg "Programme und Verknüpfungen" / "Programme & Zentrale Verknüpfungen" als Aktion für eine boolean Sytemvariable als Aktivität zu einer Bedingung nur "an" bzw. "aus" (also "true" oder "false") fix gesetzt werden.
Ein Wechsel des aktuellen Zustandes (NOT ....)  ist nicht möglich bzw. nur über Script-Steuerung realisierbar.
Das Gleiche gilt auch für die Gerätewauswahl beim Schalten des Zustandes (zB LICHT-Aktoren), dort steht immer nur "Schaltzustand: an" bzw. "Schaltzustand: aus" zur Auswahl.

### Describe alternatives you've considered

Die Aktivität sollte neben den vorhandenen Möglichkeiten auch "toggle" beinhalten, um einen schnellen unkomplizierten Wechsel des Systemzustandes der Variablen bzw. des Aktors zu realisieren.

### Is your feature request related to a problem?

-

### Additional information

-

**Comment by Maik2208** [comment]
Finde die Idee immernoch wichtig
