### ISSUE TITLE
Home Assistant Ingress not Working Correct

### ISSUE THREAD

**Issue by Bascht74** [jens-maus/RaspberryMatic#2580]
### Describe the issue you are experiencing

I cannot access the Web UI through Home Assistant. When I click on the Sidebar-Icon its is downloading a index.htm. If you do and open it, it says "Error fetching proxied request: aborted".
I tried with different browers, deleted the browser cache ...

The Devices seem to work normaly while the Web UI dont. I can open a seperate http port, that is working fine.

I have that problem with two seperate and new (!) HA installations (one with Ondroid, one with PI4, both newest HA- & HAOS-Versions).
With two older installation, it is working fine (same HA- & HAOS-Version, both Ondoid and PI4).

I don't know what is causing this, as it makes no sense to me.

### Describe the behavior you expected

I can access it via HA Ingress.

### Steps to reproduce the issue

1. Install an new HA on a e.g. PI4. 
2. Install the RaspberryMatic-AddOn.
3. Start the AddOn
4. Access it via HA Ingress

### What is the version this bug report is based on?

3.73.9.20231130

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Mounting /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying host system: Raspberry Pi 4 Model B Rev 1.5 (oci), OK
Initializing RTC Clock: no hardware found
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Running seedrng: OK
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.1, OK
Identifying Homematic RF-Hardware: ....HmRF: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-0000:01:00.0-1.2, HmIP: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-0000:01:00.0-1.2, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: 4.4.18, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: .......OK
Starting rfd: .OK
Starting HMIPServer: .............OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.73.9.20231130 (raspmatic_oci_arm64)
```

### Additional information

I posted it first here: https://github.com/jens-maus/RaspberryMatic/issues/2534 , but the issue is closed an there was no response. 
I have a slight different problem, as I don't faced it after an update, but with brand new installations (two of them).

Other add-ons are working quite fine.

**Comment by jens-maus** [comment]
@Baxxy13 Can you try to reproduce this in a fresh HomeAssistant Installation?

**Comment by Baxxy13** [comment]
Konnte ich auf meinen Systemen bisher nicht beobachten.
Habe hier auch nen recht frischen HA auf Pi4B und keine Probleme ein frisch installiertes RM-AddOn von der Seitenleiste heraus "zu öffnen".

Ganz unauffällig ist das Setup aber nicht...
`24-01-05 19:36:27 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon RaspberryMatic CCU (snapshot) to start, took more than 120 seconds`

Das AddOn ist jungfräulich, keine Geräte, AddOns oder sonstiges nur ein durchgereichter HmIP-RFUSB.

**Comment by Baxxy13** [comment]
Eben mal schnell HA-OS 11.3 auf einem Pi5 installiert und das RaspberryMatic AddOn drauf gepackt.
Keinerlei Probleme festgestellt. Aber auch hier braucht das AddOn "gefühlt" recht lange um zu starten.
Da die Startzeit aber unter 2Min bleibt gibt es die Warnung, wie beim Pi4B, nicht.

**Comment by jens-maus** [comment]
Was war die Lösung?

**Comment by Bascht74** [comment]
Ich weiß es leider nicht. Auf einmal hat es von "selbst" einfach
funktioniert.
Vorher konnt man machen, was man will: Neuinstallation, Browser-Cache
löschen, anderer Broswer.
Ich habe leider nicht herausbekommen können, woran es gelegen hat.

Ich hatte ja sogar ein Vergleichssystem, dass 1:1 gleichartig aufgesetzt
war (bis auf andere CPU) und bei einem funktionierte es, beim anderen nicht.

Am Sa., 6. Apr. 2024 um 16:48 Uhr schrieb Jens Maus <
***@***.***>:
