### ISSUE TITLE
Soll-Temp aus HA wird nicht an alle Themostate weitergegeben

### ISSUE THREAD

**Issue by lennartschulte** [jens-maus/RaspberryMatic#2585]
### Describe the issue you are experiencing

Wenn ich in HA die Temperatur an einem Gerät ändere, wird diese nur an das Gerät und nicht an verknüpfte Geräte weitergegeben. Beispiel:
HA Änderung der Soll-Temp am Wandthermostat
-> Wandthermostat übernimmt die neue Soll-Temp
-> Heizkörperthermostat macht/ändert nichts

Ändere ich allerdings die Temperatur an den Gräten selbst wird diese wie gewünscht über die Sender/Empfänger-Verknüpfung an das jeweilige andere Gerät übertragen. 
![image](https://github.com/jens-maus/RaspberryMatic/assets/89683004/e7694409-0530-474f-af20-8ca351a8429e)

Bisher habe ich das in HA über eine custom component climate_group gelöst. Dadurch konnte ich beide Thermostate parallel ändern. Mit dem neuen Update funktioniert aber diese custom-component nicht mehr.

### Describe the behavior you expected

Anpassen der Temp in HA am Wandthermostat oder Heizkörperthermostat sollte diese auch entsprechend der Verknüpfung an das jeweilige andere Gerät übertragen.

### Steps to reproduce the issue

1. HA Änderung der Soll-Temp am Wandthermostat
2. Überprüfen der neuen Soll-Temp an 2 miteinander verknüpften Geräten

### What is the version this bug report is based on?

3.73.9.20231130

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
none?
```

**Comment by Baxxy13** [comment]
Das ist weder ein Issue von RaspberryMatic, noch von HA bzw. der Integration.
Wenn du lange genug wartest wird der Sollwert irgendwann vom WTH auf das eTRV übertragen.

Empfehlung:
- lösche deine selbst angelegten DV's
- erzeuge eine HmIP-Heizgruppe und konfiguriere erstmal die Wochenprogramme und andere Einstellungen
- packe alle Teilnehmer nacheinander in die Gruppe
- aktiviere die Gruppen in der Integration
- steuere nur noch das Gruppengerät aus HA

**Comment by Baxxy13** [comment]
Was macht keinen richtigen Sinn?
Die Ansteuerung aus HA ist identisch zur Ansteuerung aus der WebUI.

Der Hinweis im WebUI-Handbuch (19.6.1 Gruppe erstellen und bearbeiten) wurde gelesen?

> Änderungen an den „physikalischen“ Geräten wirken sich auf alle Geräte einer Gruppe
> aus. Änderungen an den Geräten über die WebUI wirken sich hingegen nicht auf die
> Gruppe aus.

**Comment by lennartschulte** [comment]
Ist ja auch alles richtig. Es funktioniert wie im Handbuch. Mein Punkt ist: Ich mache eine Verknüpfung zwischen den Geräten, weil ich diese haben möchte. Bediene ich das Gerät nun manuell in der realen Welt, wird auch alles an das andere Gerät übertragen. Bediene ich aber das **gleiche** Gerät digital wird es nicht übertragen. Das ergibt für mich keinen Sinn. Daher dieses Issue.

**Comment by lennartschulte** [comment]
Aber die Erstellung einer Heizungsgruppe macht natürlich noch mehr Sinn. Hätte ich viel früher machen sollen. Hab mir schon gedacht, dass es keinen Sinn macht, alle Profile mehrfach bei jedem Gerät zu pflegen. Habe mich aber dann auch nicht weiter damit befasst. Vielen Dank also für den Tipp

**Comment by Baxxy13** [comment]
Ich verstehe schon was und meinst und stimme grundsätzlich zu. 
Es ist aber nunmal so (und auch so dokumentiert).
Ändern könnte das nur eQ-3 indem sie für alle IP-Thermostate eine dahingehend angepasste Firmware rausbringen würden.
Die Chancen dafür gehen gegen null.

**Comment by lennartschulte** [comment]
Ich stimme zu ;-)
