### ISSUE TITLE
HmIP-SPI Presence Detector - Problem with device firmware update v1.2.4

### ISSUE THREAD

**Issue by tobiman64** [jens-maus/RaspberryMatic#259]
There is a problem with the device firmware update for the HomeMatic Ip Presence Detector HmIP-SPI. I got the information about the available update to the version v1.2.4 in the WebUI.
That's why I downloaded the new firmware and placed it in the RaspberryMatic under device firmware.
Then I waited 5 days and the firmware was not updated.
I have also newly learned on the HmIP-SPI, no change.
Then I did the same in my test installation on the CCU2. After one day, the firmware for the HmIP-SPI was updated to version v1.2.4.
Is there possibly a problem in RaspberryMatic here or am I doing something wrong?

**Comment by cyber-age** [comment]
For me it has worked...

**Comment by jens-maus** [comment]
Here, too - several times already.

**Comment by HMside** [comment]
My device has been updated overnight. I thinks in your case it was a dutycycle problem or you not use the last RaspberryMatic Version.
