### ISSUE TITLE
WebUI: Tabelle "zu viel" in Geräteansicht bei CUxD Geräten

### ISSUE THREAD

**Issue by jp112sdl** [jens-maus/RaspberryMatic#260]
Unter **Status und Bedienung** -> **Geräte** stellt sich ein gewöhnlicher **HomeMatic-Aktor** wie folgt dar:

<img width="1361" alt="bildschirmfoto 2018-02-14 um 19 45 44" src="https://user-images.githubusercontent.com/18190139/36222409-779d1096-11c1-11e8-9345-f39b27ac6acf.png">

Bei einem **CUxD Gerät (28)** erscheint unter den Schalter-Flächen eine zusätzliche Tabelle, was die Zeilen (insbesondere bei 16 Kanälen) unnötig vergrößert.

<img width="1636" alt="bildschirmfoto 2018-02-14 um 19 45 51" src="https://user-images.githubusercontent.com/18190139/36222392-6b063dc6-11c1-11e8-9cff-34dad5c4e535.png">

Ich bin mir nicht sicher, ob das Ticket hier richtig ist - oder eher zu CUxD gehört (oder sogar zum OCCU?)

Beste Grüße,
Jérôme

**Comment by jens-maus** [comment]
Wie immer bin ich offen für jeglichen Pull Request zum Thema WebUI Verbesserungen. ;)

**Comment by jp112sdl** [comment]
Dat kommt ja irjendwo her, weils ein anderer da irjendwann mal reinprogrammiert hat ;)
Hatte gehofft du schreibst jetzt: Ah, das kommt vom CUxD Addon mit... oder so.
Fällt dann in die Rubrik: Is so, bleibt so, war schon immer so :) 
Nicht weiter wild.

**Comment by jens-maus** [comment]
Könnte ich mit anschauen, ja. Aber meine Hoffnung war das sich mal langsam mehr und mehr Leute finden mitzuentwickeln, gerade wenn sie offensichtlich mit den Entwicklertools ihres Webbrowsers umgehen können ;)

Aber gut, dann kommt das halt auf die Liste, aber eben mit Low Priority. Auf der anderen Seite könntest du ja mal den Verursacher finden und damit das notwendige KnowHow aufbauen um in Zukunft noch mehr an der WebUI zu verbessern...

**Comment by jp112sdl** [comment]
Ich bin nicht ganz abgeneigt (mit dem Addon hat es dann ja auch zum Schluss noch zu einem guten Ergebnis geführt!) - fange aber in Sachen WebUI bei Null (0 nicht null) ;) an.

Kannst du mir einen Hinweis geben, wo in den Tiefen des Ordners /www ich suchen muss?

Ich hatte schon nach Fragmenten des HTML-Elements gegrept, aber entweder *keine* oder *sehr viele* Ergebnisse bekommen :/

**Comment by jp112sdl** [comment]
Nach etwas Recherche: Ich finde die CLASS ID nur in der 
`/www/rega/esp/datapointconfigurator.fn`

Aber ich kann da ändern (und speichern [`/` ist rw gemountet] so viel ich will... ReGaHss neu gestartet, RaspberryMatic neu gestartet, Browsercache gelöscht... Ich bekomme die Änderungen im Browser nicht angezeigt.

Habe ich noch einen Denkfehler?
