### ISSUE TITLE
home-assistant-addon: USB3 warning never gets displayed, leads to restart loop

### ISSUE THREAD

**Issue by oliverrahner** [jens-maus/RaspberryMatic#2602]
### Describe the issue you are experiencing

When using HomeAssistant OS and plugging in a USB3 device, the RaspberryMatic addon is constantly restarted after the configured timeout of 120s.

The container health check checks, amongst others, for `monit report down`, which will return 1 if the USB 3 check indicates that a USB 3 device is being used. This means that the container is never seen as healthy, leading to the supervisor restarting it.

However, due to the configured delays in `monit`, the intended warning never gets output to the logs.

### Describe the behavior you expected

The addon should probably not restart because of the use of an USB 3 device.
But at the very least, the reason for the restart should have the chance to hit the logs before the restart is triggered.

### Steps to reproduce the issue

Prerequisites: Raspberry Pi 4 + HM GPIO Module

1. Using HomeAssistant OS, install RaspberryMatic as an add-on
2. RaspberryMatic will show the mentioned behavior

### What is the version this bug report is based on?

3.73.9.20231130

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
N/A
```

**Comment by Baxxy13** [comment]
Ja, da kann man sich einen schönen Boot-Loop erzeugen.
Abhilfe schafft das deaktivieren der USB3-Überwachung in den erweiterten Einstellungen (WebUI) oder das deaktivieren des HA-Watchdogs für das AddOn.

Geloggt wird das Ereignis innerhalb des AddOns nach /var/log/messages. Man müsste einen Syslogserver mit dem AddOn verbinden um das extern zu sehen. Durch den Neustart des AddOns geht ja auch dessen Log (von vor dem Neustart) verloren.

**Comment by oliverrahner** [comment]
Gefixt hab ich das schon, es hat mich nur über ne Stunde gekostet, rauszufinden, _warum_ das Addon ständig neustartet... Das kann ja eigentlich nicht das Ziel sein.
Ich würde grundsätzlich argumentieren, dass das Vorhandensein einer (wenn auch wichtigen) Warnung nicht dazu führen sollte, dass ein Container "unhealthy" ist...

**Comment by oliverrahner** [comment]
Bzgl. des Kommentars zu temporären Logs: Ja, das ist grundsätzlich richtig. Aber ich hätte zumindest die Chance gehabt, beim live Beobachten der Situation mittels `docker logs -f addon_xxx_raspberrymatic` rauszufinden, was los ist.

**Comment by jens-maus** [comment]
> Ich würde grundsätzlich argumentieren, dass das Vorhandensein einer (wenn auch wichtigen) Warnung nicht dazu führen sollte, dass ein Container "unhealthy" ist...

Da hast du vollkommen recht. Deshalb ist dieser bugreport durchaus berechtigt. Die Frage wäre nur wie man das am besten korrigiert. Entweder müsste man hier für die oci / ha-addon platform eine exception einbauen das der den USB3 check gänzlich unterlässt oder aber der healthy check für den container müsste verfeinern bzw. diesbzgl. verbessert werden. Tendieren tue ich zu letzterem.

**Comment by Baxxy13** [comment]
Der USB3-Check hat doch seine Daseinsberechtigung. 
Ob nun HA-OS mit RaspberryMatic AddOn oder RaspberryMatic direkt auf dem Pi4B läuft beeinflusst doch nicht die möglichen Funkstörungen bei USB3 Nutzung am Pi4B.

**Comment by jens-maus** [comment]
Genau deshalb plädiere ich ja dafür am besten den health check für das HA-Addon anzupassen und dafür zu sorgen das die nutzung eines USB3 ports zwar weiterhin die WebUI alarmmeldungen bringt, aber nicht verhindert das der container korrekt startet oder vom watchdog neugestartet wird.

**Comment by Baxxy13** [comment]
Vom Prinzip müsste man irgendwie Prioritäten setzen.
Also nur "kritische" Sachen sollten den Container als "unhealthy" deklarieren. 
Wobei natürlich fraglich ist was dann als "kritisch" eingestuft wird.

Heute im Forum war's ja der zickende hs485d der den AddOn-Watchdog auf den Plan rief.

**Comment by jens-maus** [comment]
Das stimmt. Aber das wird unterm Strich vmtl zu komplex und doch irgendwie wieder falsch. Denke daher es wäre besser ich deaktiviere das einbeziehen der Monitore stati für den healthy check..
