### ISSUE TITLE
Button: "Access Points mit inkompatibler FW" nicht sichtbar

### ISSUE THREAD

**Issue by heitec11** [jens-maus/RaspberryMatic#2609]
### Describe the issue you are experiencing

Nach dem neusten Update auf raspmatic_rpi3 (3.73.9.20231130) habe ich Probleme mit Gerätekommunikation gestört.
Die Anbindung zweier betroffener Sensoren erfolgt per HMIP-HAP.
Nun ist mir aufgefallen, das der Button in der Systemsteuerung " "Access Points mit inkompatibler FW" nicht sichtbar.

### Describe the behavior you expected

Ist das so richtig?

### Steps to reproduce the issue

1.HAP angeschlossen
2.
3.
...

### What is the version this bug report is based on?

3.73.9.20231130

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Hap wird auf der Startseite angezeigt
```

**Comment by Baxxy13** [comment]
> Ist das so richtig?

Ja, wurde mit RaspberryMatic 3.69.6.20230407 entfernt und stand auch so im Changelog.
