### ISSUE TITLE
ReGaHss: Add posibility to run set DataPoints or SysVar values with a delay

### ISSUE THREAD

**Issue by Hypnos3** [jens-maus/RaspberryMatic#262]
In scripts sometimes it will be nice to have a posibility to set a datapoint or a sysvar with a delay for e.g. radio hygiene (Funkhygiene).

e.g. a new `StateDelay(value,delay)` command with the Parameter of the value and a delay in milliseconds.

example:
```
dom.GetObject("BidCos-RF.012345678:4.SET_TEMPERATURE").StateDelay(9, 500);
```
A similar solution exists as a tcl script in the Homematic Forum, but it would be nice to have this function out of the box in the Homatic Script:
https://homematic-forum.de/forum/viewtopic.php?uid=12697&f=31&t=42056&start=0

**Comment by jens-maus** [comment]
Starting with `ReGaHss R1.00.0388.0208` the `State()` method can take two additional (optional) parameters to delay a state call for a certain specified time period now. Thus, starting with this version one can perform the following calls:

1. Will set the temperature immediately returning the result of the state operation accordingly:
```
var result = dom.GetObject("BidCos-RF.012345678:4.SET_TEMPERATURE").State(9);
```

2. Will add a state() operation to set the temperature after 500 ms wait time returning the result of the scheduling accordingly (existing waiting state() calls for this datapoint will be cleared):
```
var result = dom.GetObject("BidCos-RF.012345678:4.SET_TEMPERATURE").State(9, 500);
```

3. Will add a state() operation to set the temperature after 1 second wait time and NOT clearing already waiting state calls, returning the result of the scheduling accordingly:
```
var result = dom.GetObject("BidCos-RF.012345678:4.SET_TEMPERATURE").State(9, 500, false);
```

I hope that this will actually implemented your request accordingly.
