### ISSUE TITLE
Das root Verzeichnis ist unter Docker rw statt ro 

### ISSUE THREAD

**Issue by kmbach** [jens-maus/RaspberryMatic#2629]
### Describe the issue you are experiencing

Bin gerade von piVCCU auf RaspberryMatic auf docker umgezogen. Nach einem boot erwarte ich eigentlich, dass / ro ist. Bei mir ist / jedoch rw.
von mount:
overlay on / type overlay (rw,relatime,lowerdir=/var/lib/docker/ove ...

### Describe the behavior you expected

overlay on / type overlay (ro,relatime,lowerdir=/var/lib/docker/ove

### Steps to reproduce the issue

boot host
Ich habe alle Startskripte (/usr/local/etc/config/rc.d) testweise entfernt um auszuschliessen, dass ein addon schuld ist.

### What is the version this bug report is based on?

3.73.9.20231130 (oci)

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
nein
```

**Comment by jens-maus** [comment]
> Bin gerade von piVCCU auf RaspberryMatic auf docker umgezogen. Nach einem boot erwarte ich eigentlich, dass / ro ist. 

Und warum genau ist es ein Problem/Bug das es "rw" ist? Unter HomeAssistant ist das z.B. vollkommen wurscht ob es rw/ro ist weil sämtliche Änderungen bei einem frischen container start wieder weg sind.

**Comment by kmbach** [comment]
Sorry für meine Anfrage. Ich war davon ausgegangen, dass ro das System etwas härtet - war bei der CCU3 doch auch immer so. Der Container läuft im Idealfall ja viele Monate, wird also nicht häufig zurückgesetzt.
Wenn das so okay ist habe ich aber auch kein Problem damit,

**Comment by jens-maus** [comment]
Sagen wir es mal so, im Docker betrieb ist das nicht ganz so kritisch. Aber ja, auch den kann man read-only per default. Sollte/müsste allerdings dann schon beim docker aufruf passieren. Das müsste ich dann noch entsprechend anpassen... Ich schau es mir mal an..
