### ISSUE TITLE
Freshly flashed Pi Zero not connecting to WiFi

### ISSUE THREAD

**Issue by michaelosthege** [jens-maus/RaspberryMatic#2651]
### Describe the issue you are experiencing

Just like I tried [in May 2023](https://github.com/jens-maus/RaspberryMatic/discussions/2311#discussioncomment-5891934) I flashed my Pi Zero W v1.1 with the current version "RaspberryPi Zero W, RaspberryPi Zero, RaspberryPi Compute Module 1, RaspberryPi1 (A+/B+)" [release 3.73.9.20240130](https://github.com/jens-maus/RaspberryMatic/releases/tag/3.73.9.20240130) but it won't connect to WiFi, and doesn't respond on the USB connection either.
About half a minute after connecting to power it's green LED goes into a double-flash cycle with about 1s intervals.

If instead I flash it with a Raspberry Pi OS Lite (32 bit), it connects and the LED is on almost continuously 🤔

Strictly speaking I don't even know if it booted up. I can't see any log files on the boot partition, and if I try to add `ssh` and `wpa_supplicant.conf` files they are not removed either.

### Describe the behavior you expected

It should have connected to the WiFi after booting.

### Steps to reproduce the issue

1. Flash a microSD using the Raspberry Pi Imager
2. Put it into a Pi Zero W and connect power
3. Wait for it to show up in the WiFi (it does not)

### What is the version this bug report is based on?

3.73.9.20240130

### Which base platform are you running?

rpi0 (RaspberryPi)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
can't access the logs, unfortunately :(
```

### Additional information

I'll try to get my hands on a mini HDMI to check if the screen shows anything useful.

**Comment by Baxxy13** [comment]
Dem Wiki bist du gefolgt und hast die nötige Datei samt korrektem Inhalt angelegt?
https://github.com/jens-maus/RaspberryMatic/wiki/Experten-Features#wlanwifi-nutzung

**Comment by michaelosthege** [comment]
Wow, danke, das hat geholfen!

Die Seite war in den Raspberry Pi Installation Instructions nicht verlinkt. Ich habe den Schritt jetzt hinzugefügt: https://github.com/jens-maus/RaspberryMatic/wiki/Installation-RaspberryPi
