### ISSUE TITLE
Anlegen von Direktverknüpfungen mit HmIP-RCV-50 HmIP-RCV-1 (virt. HmIP Tasten) nicht möglich

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#2660]
### Describe the issue you are experiencing

In den aktuellen 3.75.2 - Nightlys kann man keine DV's mehr zu den virt. HmIP-Tasten anlegen.
Mit bestehenden DV's zu virt. HmIP-Tasten gibt es keine Probleme.

### Describe the behavior you expected

DV's zu virt. HmIP-Tasten sollten sich wie gehabt anlegen lassen

### Steps to reproduce the issue

1. neue DV erstellen mit Sender HmIP-RCV-50 HmIP-RCV-1 und irgendeinem HmIP-Empfänger (egal welches Gerät)
2. Erstellen oder Erstellen und Bearbeiten wählen
3. es wird keine DV erzeugt bzw. eine leere Seite angezeigt
...

### What is the version this bug report is based on?

3.75.2.20240217 - Nightly

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
keine Fehlermeldungen zu sehen
```

### Additional information

Ein Fall für eQ-3 würde ich sagen.

**Comment by jp112sdl** [comment]
Ich habe schon eine ungefähre Ahnung.

Hast du beide Möglichkeiten im Direktverknüpfungs-"Wizard" mal probiert?
- A)
  - zuerst Gerätekanal auswählen
  - danach virt. Taster auswählen
- B)
  - zuerst virt. Taster auswählen
  - danach Gerätekanal auswählen

**Comment by Baxxy13** [comment]
Es funktioniert weder A noch B.

An der WebUI vorbei geht's auch nicht.
`echo 'load tclrpc.so; puts [xmlrpc http://127.0.0.1:32010 addLink [list string HmIP-RCV-1:11] [list string 00199A4992FB42:4]]' | tclsh`

Ebensowenig mit dem Homematic Manager.
"anlegen":
![GIF 19 02 2024 08-43-42](https://github.com/jens-maus/RaspberryMatic/assets/54898249/7dbc7451-f2a0-45d6-b8c6-610d03c8ab6b)

"anlegen und bearbeiten":
![GIF 19 02 2024 08-45-06](https://github.com/jens-maus/RaspberryMatic/assets/54898249/5ed13e3f-a03f-4762-a6f6-2d129cdefd99)

**Comment by jens-maus** [comment]
@Baxxy13 Bitte mit dem nächsten nightly snapshot erneut probieren. mit der 3.75.4+ sollte das wieder gehen...

**Comment by andrzejgilas** [comment]
Mit der neuen Version 3.75.4 ist alles wieder in Ordnung.



![2](https://github.com/jens-maus/RaspberryMatic/assets/81189856/4df58a1b-292a-4ce6-8cce-88a2fcc65697)
![1](https://github.com/jens-maus/RaspberryMatic/assets/81189856/7a7dfcf1-3e15-4c12-8c15-1b49cd14fcd2)
