### ISSUE TITLE
Pi 5 von PCIe booten geht nicht

### ISSUE THREAD

**Issue by Troubadix** [jens-maus/RaspberryMatic#2665]
### Describe the issue you are experiencing

Hallo,

ich habe mir einen Raspi 5 plus SSD-HAT Bottom von Pineberry Pi zugelegt, dazu eine Waveshare PoE HAT, um mir das externe Netzteil zu sparen.
Das gleiche Setup habe ich für ein anderes Projekt schon am laufen mit Raspberry Pi OS und funktioniert einwandfrei..

Ich habe nun den Pi5 von SD-Karte gebootet mit dem Pi OS, eine Runde "apt update && apt upgrade" samt Reboot gespielt, den NVMe-Boot im Bootloader aktiviert (https://docs.pineberrypi.com/tutorial-booting-from-nvme) und danach mit dem Raspberry Pi Imager das Raspberrymatic Image auf die SSD geschrieben.
Das hat auch ohne Fehlermeldungen geklappt.

Aber leider bootet das System nicht. 
Der Monitor geht für einige Sekunden an, zeigt aber nichts an. Dann geht der Monitor aus und kurz danach wieder an und das Spiel beginnt von vorne.

Wenn ich statt Raspimatic das PiOS auf die SSD flashe bootet das System einwandfrei von der SSD.

Es ist dabei egal, ob die Homematic-Funkplatine aufgesteckt ist oder nicht.

### Describe the behavior you expected

Einwandfreier Boot von PCIe SSD

### Steps to reproduce the issue

s. oben

### What is the version this bug report is based on?

3.73.9.20240130

### Which base platform are you running?

rpi5 (RaspberryPi5)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
da kein boot auch keine logs
```

**Comment by jens-maus** [comment]
Das ist bekannt. Jedoch leider eine Limitation des verwendeten Bootloaders (U-Boot). Dieser unterstützt in der aktuellen 2024.01 Version lediglich das Booten von SD Karte und auch nicht von USB oder PCIe. Insofern bedarf es leider noch etwas an Geduld bis die Macher hinter U-Boot dann den entsprechenden Support für USB und/oder PCIe Boot dort einbauen.

**Comment by Troubadix** [comment]
Urgs. Ich meine mich zu erinnern, das es ähnliches schon damals beim Pi3 oder 4 gab.
Warum wird denn nicht den originalen Bootloader vom Raspberry Pi OS genutzt?

Aber danke für die Antwort! Hilft also wohl nur abwarten...

**Comment by jens-maus** [comment]
> Warum wird denn nicht den originalen Bootloader vom Raspberry Pi OS genutzt?

Weil dieser leider (noch) nicht die Features bietet die es für RaspberryMatic braucht: Alternatives booten in ein initrd basiertes RecoverySystem anhand eines Statusfiles oder via GPIO Button (Button des RPI-RF-MOD).

**Comment by Miki433** [comment]
Gibt es bzgl. USB-/PCIe-Boot auf dem Pi5 schon was Neues? Danke vorab für eure Rückmeldung.

**Comment by jens-maus** [comment]
> Gibt es bzgl. USB-/PCIe-Boot auf dem Pi5 schon was Neues? Danke vorab für eure Rückmeldung.

Wenn das so wäre würde es hier stehen bzw. das Ticket wäre dann geschlossen. Also Nein: Keine Veränderung. U-Boot unterstützt immer noch nicht USB/PCIe-boot für einen RaspberryPi5.

**Comment by loki-sft** [comment]
Hallo Jens, 
gibt es eine Quelle im Web, wo man laufende Aktivitäten bezügliches dieses Themas im Netz nachverfolgen kann? Ich habe dazu selbst leider nichts gefunden.

**Comment by Lupo-1** [comment]
Hallo,
gibt es mittlerweile ein Lösung für diese Problem? Finde es sehr schade, dass raspberrymatic nicht auf einer ssd installiert werden kann.
