### ISSUE TITLE
HmIP-ESI liefert Werte in Wh, aber im UI als kWH angezeigt.

### ISSUE THREAD

**Issue by drose28357** [jens-maus/RaspberryMatic#2676]
### Describe the issue you are experiencing

Das HmIP-ESI liest die Werte aus dem Stromzähler korrekt aus.
Laut statelist.cgi weden die Werte vom Sensor in Wh ausgelesen.
In der Anzeige unter "Status und Bedienung/Geräte" werden die Werte korrekt angezeigt, jedoch mit der Einheit kWh.

### Describe the behavior you expected

Entweder den Anzeige-Text im UI von "kWh" auf "Wh" ändern
oder
Die Messwerte durch 1000 dividieren. Das entspräche der bisherigen Anzeige des HM-Energiemessers in kWh.

Eigentlich ist es ein Fehler in der OCUU, aber vielleicht kann das Jemand an E3Q weiterleiten ;-) Die Issues in dem OCCU-Github werden ja kaum beachtet.

### Steps to reproduce the issue

1. HmIP aktivieren/anlernen
2. das Gerät unter "Status und Bedienung/Geräte" anzeigen lasssen

### What is the version this bug report is based on?

3.73.9.20240130

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Auszug aus  statelist.cgi. Dort ist z.B. in Channel 2 der Energie-Counter mit valueunit="Wh" angegeben.

<device name="Sen_Haus_Stromzähler" ise_id="74667" unreach="false" config_pending="false">
<channel name="Sen_Haus_Stromzähler:0" ise_id="74668" index="0" visible="true" operate="true">
<datapoint name="HmIP-RF.003FA0C9AD7162:0.CONFIG_PENDING" type="CONFIG_PENDING" ise_id="74669" value="false" valuetype="2" valueunit="" timestamp="1710332306" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:0.DUTY_CYCLE" type="DUTY_CYCLE" ise_id="74673" value="false" valuetype="2" valueunit="" timestamp="1710332306" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:0.ERROR_CODE" type="ERROR_CODE" ise_id="74674" value="0" valuetype="16" valueunit="" timestamp="1710332306" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:0.ERROR_COMMUNICATION_SENSOR" type="ERROR_COMMUNICATION_SENSOR" ise_id="74675" value="false" valuetype="2" valueunit="" timestamp="1710332306" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:0.LOW_BAT" type="LOW_BAT" ise_id="74680" value="false" valuetype="2" valueunit="" timestamp="1710332306" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:0.OPERATING_VOLTAGE" type="OPERATING_VOLTAGE" ise_id="74684" value="0.000000" valuetype="4" valueunit="" timestamp="0" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:0.OPERATING_VOLTAGE_STATUS" type="OPERATING_VOLTAGE_STATUS" ise_id="74685" value="0" valuetype="16" valueunit="" timestamp="0" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:0.RSSI_DEVICE" type="RSSI_DEVICE" ise_id="74686" value="-94" valuetype="16" valueunit="" timestamp="1710332306" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:0.RSSI_PEER" type="RSSI_PEER" ise_id="74687" value="0" valuetype="16" valueunit="" timestamp="0" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:0.SENSOR_ERROR" type="SENSOR_ERROR" ise_id="74688" value="false" valuetype="2" valueunit="" timestamp="1710332306" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:0.UNREACH" type="UNREACH" ise_id="74692" value="false" valuetype="2" valueunit="" timestamp="1710332306" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:0.UPDATE_PENDING" type="UPDATE_PENDING" ise_id="74696" value="false" valuetype="2" valueunit="" timestamp="1710331620" operations="5"/>
</channel>
<channel name="Sen_Haus_Stromzähler:1" ise_id="74700" index="1" visible="true" operate="true">
<datapoint name="HmIP-RF.003FA0C9AD7162:1.CHANNEL_OPERATION_MODE" type="CHANNEL_OPERATION_MODE" ise_id="74701" value="4" valuetype="16" valueunit="" timestamp="1710331753" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:1.GAS_FLOW" type="GAS_FLOW" ise_id="74702" value="0.000000" valuetype="4" valueunit="m3/h" timestamp="0" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:1.GAS_FLOW_STATUS" type="GAS_FLOW_STATUS" ise_id="74703" value="0" valuetype="16" valueunit="" timestamp="0" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:1.POWER" type="POWER" ise_id="74704" value="75.450000" valuetype="4" valueunit="W" timestamp="1710332326" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:1.POWER_STATUS" type="POWER_STATUS" ise_id="74705" value="0" valuetype="16" valueunit="" timestamp="1710332306" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:1.SELF_CALIBRATION" type="SELF_CALIBRATION" ise_id="74706" value="" valuetype="16" valueunit="" timestamp="0" operations="2"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:1.SELF_CALIBRATION_RESULT" type="SELF_CALIBRATION_RESULT" ise_id="74707" value="4" valuetype="16" valueunit="" timestamp="1710331751" operations="4"/>
</channel>
<channel name="Sen_Haus_Bezug:2" ise_id="74708" index="2" visible="true" operate="true">
<datapoint name="HmIP-RF.003FA0C9AD7162:2.ENERGY_COUNTER" type="ENERGY_COUNTER" ise_id="74709" value="2159780.800000" valuetype="4" valueunit="Wh" timestamp="1710332306" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:2.ENERGY_COUNTER_STATUS" type="ENERGY_COUNTER_STATUS" ise_id="74710" value="0" valuetype="16" valueunit="" timestamp="1710332306" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:2.GAS_VOLUME" type="GAS_VOLUME" ise_id="74711" value="0.000000" valuetype="4" valueunit="m3" timestamp="0" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:2.GAS_VOLUME_STATUS" type="GAS_VOLUME_STATUS" ise_id="74712" value="0" valuetype="16" valueunit="" timestamp="0" operations="5"/>
</channel>
<channel name="Sen_Haus_Stromzähler:3" ise_id="74713" index="3" visible="true" operate="true">
<datapoint name="HmIP-RF.003FA0C9AD7162:3.ENERGY_COUNTER" type="ENERGY_COUNTER" ise_id="74714" value="0.000000" valuetype="4" valueunit="Wh" timestamp="0" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:3.ENERGY_COUNTER_STATUS" type="ENERGY_COUNTER_STATUS" ise_id="74715" value="1" valuetype="16" valueunit="" timestamp="1710332306" operations="5"/>
</channel>
<channel name="Sen_Haus_Lieferung:4" ise_id="74716" index="4" visible="true" operate="true">
<datapoint name="HmIP-RF.003FA0C9AD7162:4.ENERGY_COUNTER" type="ENERGY_COUNTER" ise_id="74717" value="1613802.900000" valuetype="4" valueunit="Wh" timestamp="1710332306" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:4.ENERGY_COUNTER_STATUS" type="ENERGY_COUNTER_STATUS" ise_id="74718" value="0" valuetype="16" valueunit="" timestamp="1710332306" operations="5"/>
</channel>
</device>
```

### Additional information

Screenshots
<img width="836" alt="HmIP-ESI_Datenanzeige" src="https://github.com/jens-maus/RaspberryMatic/assets/11533286/8a8f8762-549a-4da4-9a68-d56f20c0c242">
<img width="736" alt="HmIP-ESI_Einstellungen" src="https://github.com/jens-maus/RaspberryMatic/assets/11533286/9c011c7d-80c1-4762-a844-e8f4337bd8b8">

**Comment by drose28357** [comment]
P.S. "Energiebezug HT" meint "Energie-Bezug Hoch-Tarif"ö
Für den Fall, das man noch einen Wärmepumpen-Tarifzähler als NT zu unterscheiden hat.

**Comment by jens-maus** [comment]
Vielleicht müsste man mal verifizieren das das Problem auch mit der originalen CCU3 Firmware auftritt und daher nicht an RaspberryMatic liegt...

**Comment by drose28357** [comment]
Ich kann am Montag in einer alten statecgi.list nachsehen, welche Werte der alte HM-Energiezähler mit IEC-Sensor geliefert hat. 
Hab meinen HmIP-ESI produktiv in der Wärmepumpensteuerung integriert. Kann daher nicht mit der originalen CCU testen.

**Comment by isi07** [comment]
bei mir sieht es ok aus
der Rohwert in Wh abgelesen aus iobroker
![image](https://github.com/jens-maus/RaspberryMatic/assets/65848350/34bd15c2-32ce-4f36-88b9-775f1a45ad00)
stimmt überein mit dem Wert in kWh angezeigt in der Raspberrymatic WebUI
![image](https://github.com/jens-maus/RaspberryMatic/assets/65848350/cb06d08c-d231-4a80-88b7-4c0889c3d394)

vielleicht ist es in einer neueren Version schon behoben?

CCU Software Info
Product:	raspmatic_ova (3.75.6.20240316)
ReGaHss:	R1.00.0388.0237

**Comment by drose28357** [comment]
Ich mache Montag das Update und teste.

**Comment by jens-maus** [comment]
> Ich mache Montag das Update und teste.

Wie jetzt? Das hab ich ja total überlesen das du da ein Issue basierend auf einer alten Version gemacht hast. Eigentlich ein NoGo ;-)

**Comment by drose28357** [comment]
Na na na, keine vorschnelle Verurteilung. 
Zum Zeitpunkt der Issue-Erstellung war das die aktuelle RM-Version vom Januar. Das HmIP-ESI kam halt mit zwei Monaten Verspätung an.

**Comment by drose28357** [comment]
Mit der neuen Version aspmatic_rpi4 (3.75.6.20240316) funktioniert die HmIP-ESI-IEC.
HM-ES-TX-WM-IEC und HmIP-IES-ICE  liefern in der statelist.xml den Wert in "kWh", verhalten sich diesbezüglich also identisch.
Das Issue kann geschlossen werden.

Der vollständigkeit halber und zur Info die statelist.cgi.xml für den "HM-ES-TX-WM" mit IEC-Sensor:
`<device name="Sen_Haus_Stromzähler" ise_id="18559" unreach="false" sticky_unreach="false" config_pending="false">
<channel name="Sen_Haus_Stromzähler:0" ise_id="18560" index="0" visible="" operate="">
<datapoint name="BidCos-RF.MEQ0703669:0.UNREACH" type="UNREACH" ise_id="18580" value="false" valuetype="2" valueunit="" timestamp="1700851089" operations="5"/>
<datapoint name="BidCos-RF.MEQ0703669:0.STICKY_UNREACH" type="STICKY_UNREACH" ise_id="18576" value="false" valuetype="2" valueunit="" timestamp="1700851089" operations="7"/>
<datapoint name="BidCos-RF.MEQ0703669:0.CONFIG_PENDING" type="CONFIG_PENDING" ise_id="18562" value="false" valuetype="2" valueunit="" timestamp="1700851089" operations="5"/>
<datapoint name="BidCos-RF.MEQ0703669:0.LOWBAT" type="LOWBAT" ise_id="18570" value="false" valuetype="2" valueunit="" timestamp="1700851089" operations="5"/>
<datapoint name="BidCos-RF.MEQ0703669:0.RSSI_DEVICE" type="RSSI_DEVICE" ise_id="18574" value="-65535" valuetype="16" valueunit="" timestamp="1700851089" operations="5"/>
<datapoint name="BidCos-RF.MEQ0703669:0.RSSI_PEER" type="RSSI_PEER" ise_id="18575" value="-72" valuetype="16" valueunit="" timestamp="1700851089" operations="5"/>
<datapoint name="BidCos-RF.MEQ0703669:0.DEVICE_IN_BOOTLOADER" type="DEVICE_IN_BOOTLOADER" ise_id="18566" value="false" valuetype="2" valueunit="" timestamp="1700851089" operations="5"/>
<datapoint name="BidCos-RF.MEQ0703669:0.UPDATE_PENDING" type="UPDATE_PENDING" ise_id="18584" value="false" valuetype="2" valueunit="" timestamp="1700851089" operations="5"/>
</channel>
<channel name="Sen_Haus_Netzentnahme" ise_id="18588" index="1" visible="true" operate="true">
<datapoint name="BidCos-RF.MEQ0703669:1.IEC_ENERGY_COUNTER" type="IEC_ENERGY_COUNTER" ise_id="32953" value="352.629500" valuetype="4" valueunit="kWh" timestamp="1700997935" operations="5"/>
<datapoint name="BidCos-RF.MEQ0703669:1.IEC_POWER" type="IEC_POWER" ise_id="32954" value="-6.800000" valuetype="4" valueunit="W" timestamp="1700997935" operations="5"/>
</channel>
<channel name="Sen_Haus_Netzeinspeisung" ise_id="32955" index="2" visible="true" operate="true">
<datapoint name="BidCos-RF.MEQ0703669:2.IEC_ENERGY_COUNTER" type="IEC_ENERGY_COUNTER" ise_id="32956" value="1579.979399" valuetype="4" valueunit="kWh" timestamp="1700997935" operations="5"/>
<datapoint name="BidCos-RF.MEQ0703669:2.IEC_POWER" type="IEC_POWER" ise_id="32957" value="0.000000" valuetype="4" valueunit="W" timestamp="1700997935" operations="5"/>
</channel>
</device>`

Mit der neuen Raspberrymatic-Version güt HmIP-ESI-IEC sieht es jetzt so aus:
`<device name="Sen_Haus_Stromzähler" ise_id="74667" unreach="false" config_pending="false">
<channel name="Sen_Haus_Stromzähler:0" ise_id="74668" index="0" visible="true" operate="true">
<datapoint name="HmIP-RF.003FA0C9AD7162:0.CONFIG_PENDING" type="CONFIG_PENDING" ise_id="74669" value="false" valuetype="2" valueunit="" timestamp="1711440752" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:0.DUTY_CYCLE" type="DUTY_CYCLE" ise_id="74673" value="false" valuetype="2" valueunit="" timestamp="1711440752" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:0.ERROR_CODE" type="ERROR_CODE" ise_id="74674" value="0" valuetype="16" valueunit="" timestamp="1711440752" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:0.ERROR_COMMUNICATION_SENSOR" type="ERROR_COMMUNICATION_SENSOR" ise_id="74675" value="false" valuetype="2" valueunit="" timestamp="1711440752" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:0.LOW_BAT" type="LOW_BAT" ise_id="74680" value="false" valuetype="2" valueunit="" timestamp="1711440752" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:0.OPERATING_VOLTAGE" type="OPERATING_VOLTAGE" ise_id="74684" value="0.000000" valuetype="4" valueunit="" timestamp="0" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:0.OPERATING_VOLTAGE_STATUS" type="OPERATING_VOLTAGE_STATUS" ise_id="74685" value="0" valuetype="16" valueunit="" timestamp="0" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:0.RSSI_DEVICE" type="RSSI_DEVICE" ise_id="74686" value="-64" valuetype="16" valueunit="" timestamp="1711440752" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:0.RSSI_PEER" type="RSSI_PEER" ise_id="74687" value="0" valuetype="16" valueunit="" timestamp="0" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:0.SENSOR_ERROR" type="SENSOR_ERROR" ise_id="74688" value="false" valuetype="2" valueunit="" timestamp="1711440752" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:0.UNREACH" type="UNREACH" ise_id="74692" value="false" valuetype="2" valueunit="" timestamp="1711440752" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:0.UPDATE_PENDING" type="UPDATE_PENDING" ise_id="74696" value="false" valuetype="2" valueunit="" timestamp="1711440071" operations="5"/>
</channel>
<channel name="Sen_Haus_Stromzähler:1" ise_id="74700" index="1" visible="true" operate="true">
<datapoint name="HmIP-RF.003FA0C9AD7162:1.CHANNEL_OPERATION_MODE" type="CHANNEL_OPERATION_MODE" ise_id="74701" value="4" valuetype="16" valueunit="" timestamp="1711440029" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:1.GAS_FLOW" type="GAS_FLOW" ise_id="74702" value="0.000000" valuetype="4" valueunit="m3/h" timestamp="0" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:1.GAS_FLOW_STATUS" type="GAS_FLOW_STATUS" ise_id="74703" value="0" valuetype="16" valueunit="" timestamp="0" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:1.POWER" type="POWER" ise_id="74704" value="11.930000" valuetype="4" valueunit="W" timestamp="1711440752" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:1.POWER_STATUS" type="POWER_STATUS" ise_id="74705" value="0" valuetype="16" valueunit="" timestamp="1711440752" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:1.SELF_CALIBRATION" type="SELF_CALIBRATION" ise_id="74706" value="" valuetype="16" valueunit="" timestamp="0" operations="2"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:1.SELF_CALIBRATION_RESULT" type="SELF_CALIBRATION_RESULT" ise_id="74707" value="" valuetype="16" valueunit="" timestamp="0" operations="4"/>
</channel>
<channel name="Sen_Haus_Bezug:2" ise_id="74708" index="2" visible="true" operate="true">
<datapoint name="HmIP-RF.003FA0C9AD7162:2.ENERGY_COUNTER" type="ENERGY_COUNTER" ise_id="74709" value="2191907.200000" valuetype="4" valueunit="Wh" timestamp="1711440752" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:2.ENERGY_COUNTER_STATUS" type="ENERGY_COUNTER_STATUS" ise_id="74710" value="0" valuetype="16" valueunit="" timestamp="1711440752" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:2.GAS_VOLUME" type="GAS_VOLUME" ise_id="74711" value="0.000000" valuetype="4" valueunit="m3" timestamp="0" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:2.GAS_VOLUME_STATUS" type="GAS_VOLUME_STATUS" ise_id="74712" value="0" valuetype="16" valueunit="" timestamp="0" operations="5"/>
</channel>
<channel name="Sen_Haus_Stromzähler:3" ise_id="74713" index="3" visible="true" operate="true">
<datapoint name="HmIP-RF.003FA0C9AD7162:3.ENERGY_COUNTER" type="ENERGY_COUNTER" ise_id="74714" value="0.000000" valuetype="4" valueunit="Wh" timestamp="0" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:3.ENERGY_COUNTER_STATUS" type="ENERGY_COUNTER_STATUS" ise_id="74715" value="1" valuetype="16" valueunit="" timestamp="1711440752" operations="5"/>
</channel>
<channel name="Sen_Haus_Lieferung:4" ise_id="74716" index="4" visible="true" operate="true">
<datapoint name="HmIP-RF.003FA0C9AD7162:4.ENERGY_COUNTER" type="ENERGY_COUNTER" ise_id="74717" value="1671207.500000" valuetype="4" valueunit="Wh" timestamp="1711440752" operations="5"/>
<datapoint name="HmIP-RF.003FA0C9AD7162:4.ENERGY_COUNTER_STATUS" type="ENERGY_COUNTER_STATUS" ise_id="74718" value="0" valuetype="16" valueunit="" timestamp="1711440752" operations="5"/>
</channel>
</device>`

**Comment by drose28357** [comment]
Erneuter Nachtest nach 5 Tagen Laufzeit mit n euer RM-Version vom März:   
Der Fehler ist noch vorhanden!
Der Sensor liefert nach wie vor "Wh" als Wert und Einheit, im UI wird der Wert in "Wh" ausgegebenen und als Einheit "kWh" angezeigt.
Der Fehler scheint weiterhin zu existieren. 
Interessant ist, das die Wochenzähler in der korrekten Einheit "kWh" angezeigt werden. D.h. in der internen Berechnung wird entweder die richtige Einheit "kWh" angewendet bzw. die Ausgabe in "kWh" umgerechnet.
Nur beim aktuellen Zählerwert fehlt die Umrechnung.

Siehe Anlagen.
<img width="734" alt="20240330_HmIP-ESI-IEC_Anzeigefehler_Wh_Screenshot 2024-03-30 120150" src="https://github.com/jens-maus/RaspberryMatic/assets/11533286/0f8a2871-0354-4e39-a4e9-6ce3736e9ba7">
An dem "statelist.cgi-xml" des HmIP-ESI-IEC gegenüber von vor 5 Tagen hat sich nichts geändert.
[20240330_HmIP-ESI-IEC_satelist.cgi.zip](https://github.com/jens-maus/RaspberryMatic/files/14811651/20240330_HmIP-ESI-IEC_satelist.cgi.zip)

**Comment by jens-maus** [comment]
Ziemlich Ping-Pong hier. Geht, geht nicht, geht, geht nicht... @isi07 hat ja auf der anderen Seite schon berichtet und auch via ioBroker ansicht belegt das es bei ihm funktioniert. Selbst kann ich das auf grund des fehlenden HmIP-ESI hier nicht reproduzieren. Es ist auch vollkommen irrelevant was in der statelist.cgi des XML-API Addons angezeigt wird. Schau dir die Rohdaten via ReGa-Skripting bzw. XMLRPC Ausgabe dieses Kanals an und vergleich es mit der WebUI. Vielleicht ist das ja auch ein Bug im XML-API, etc...

**Comment by drose28357** [comment]
Das hin und her finde ich auch nicht gut, bin aber nicht fehlerfrei. Da korrigiere ich mich lieber selber..
Ich versuche mal die ReGa-Scripting-Abfragen bzw. XMLRPC und melde mich hier.

**Comment by drose28357** [comment]
So, habe einige Recherchen per RegaScript und statelist.cgi hinter mir. Der Fehler ist behoben. 

Hier der Lösungsweg als Erfahrungsbericht:
1) Der HmIP-ESI mit IEC wurde unter der Vor-Version "raspmatic_rpi4 (3.75.6.20240130)" in Betrieb genommen. Diese Version zeigt den oben beschriebenen Fehler. Dadurch wurden die internen CCU-internen Referenzzähler mit dem Sensorwert in Wh (z.B. 2147283,00) belegt.

2) Mit dem Update auf "raspmatic_rpi4 (3.75.6.20240316)" wurde der o.a. Fehler korrigiert und die Sensorwerte auf kWh skaliert. Jedoch waren die internen Zählerstände noch mit den alten Werten in Wh beschrieben, so das die aktuelle auflaufenden Zählerwerte nur zu einen Tausendstel auf die Wh-Werte aufaddiert wurden. Daher weiterhin die viel zu hohen Anzeigewerte.

3) Durch Setzen der aktuellen Zählerwerte (in kWh) in den Geräteeinstellungen konnten die alten "Wh"-Zählerwerte überschrieben werden und die angezeigten Werte sind jetzt korrekt in kWh.

Screenshot der Geräteeinstellungen HmIP-ESI gemäß 3) :
<img width="508" alt="20240402_HmIP-ESI_Korrektur_alte Zählerstände_in_Wh" src="https://github.com/jens-maus/RaspberryMatic/assets/11533286/b59bc1a5-85c6-419e-a479-d38041c69a8d">

**Comment by drose28357** [comment]
Gelöst
