### ISSUE TITLE
Instabilität seit Updates größer November 2017

### ISSUE THREAD

**Issue by mbokor** [jens-maus/RaspberryMatic#268]
Hallo,

ich habe das Problem dass wenn ich Updateds höher dieser Version einspiele dass mir dann der Raspberry teilw. über Nacht hängen bleibt (ich starte in der Nacht automatisch). Spiele ich allerdings wieder den Novemberstand ein, funktioniert es. An was kann das liegen ?

Gruß Michael

**Comment by jens-maus** [comment]
Diese Anfrage ist leider zu allgemein.

Mehr Infos snd notwendig:

- Was bedeutet „hängen bleiben“? Geht ein ping? Was zeigt ein Monitor am HDMI? Geht noch ein SSH Login? Etc.
- was bedeutet es wird in der nacht automatisch neugestartet? Wenn er stehen bleibt oder automatischer neustart jede nacht egal ob absturz oder nicht?
- welche addons sind installiert?

Des Weiteren wäre es sicherlich besser das HomeMatic-Forum zu verwenden um die ursache des problems zu finden da es kein allgemein gültiges problem sein kann und das hier ein bugtracker ist und kein Diskussionsforum.

**Comment by thomasjockel** [comment]
Hallo,
ich habe auch so ein Problem seit 1 Woche. Auch das Update 25.2. hat keine Abhilfe gebracht. Der RasPi verliert die Geräte. Auf der WEBGui sind sie da, ich kann sie aber nicht mehr bedienen, die PocketControlHM finden dann nur noch 2 der 79 Geräte. Starte ich den RasPi neu, läuft wieder alles, wobei sich zum Teil einige Geräte erst sehr spät melden, aber das kann auch sein, dass nach dem Strat zu viel Funkverkehr ist, das dann erst mal nicht alle Geräte durchkommen. Dann läuft es wieder einen halben Tag und ich habe den gleichen Zustand. SD neu formatiert und Backup eingespielt ... bringt nichts. Hat jemand eine Idee?

DANKE Thomas

**Comment by jens-maus** [comment]
Bitte solche Dinge im HomeMatic Forum diskutieren. Das hier ist ein BugTracker und kein Diskussionsforum. Meine Vermutung ist das irgendetwas sporadisch deinen DutyCycle Hochtreiben. Diesen am besten loggen und entsprechend beobachten. Aber wie gesagt, bitte solche Dinge im Forum diskutieren.

**Comment by thomasjockel** [comment]
ok, sorry, die Überschrift klang so treffend.
