### ISSUE TITLE
LXC installation fails when multiple bridges are present (i.e. docker) or brctl is missing

### ISSUE THREAD

**Issue by c0ldtech** [jens-maus/RaspberryMatic#2683]
### Describe the issue you are experiencing

The installation script fails with ` Network setup of host system is not adequate as a default network bridge interface is required.` when multiple bridges are present (for example because of docker bridges), or if `brctl` is not installed.

My output of `/usr/sbin/brctl show`

```
bridge name     bridge id               STP enabled     interfaces
br-93c7aa4f4831         8000.0242ad1cd134       no
br0             8000.be5aa1b33219       no              enp1s0
docker0         8000.0242a77899d7       no              veth1b7e457
```

### Describe the behavior you expected

Expected nehaviour would be to pass this test.

### Steps to reproduce the issue

1. Have docker installed with network bridges
2. Change network configuration afterwords to create default bridge br0 as stated in LXC part of documentation
3. try to install RaspberryMatic using the documentation

### What is the version this bug report is based on?

3.75.6.20240316

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Everything should be mentioned already.
```

**Comment by jens-maus** [comment]
Please try again. The new default `install-lxc.sh` (version 1.14) should now allow to have the default network bridge at different positions in the `brctl` output.

**Comment by c0ldtech** [comment]
Thanks, it works now!
