### ISSUE TITLE
Favoritenliste wird genausooft angezeigt wie man User dafür verbindet

### ISSUE THREAD

**Issue by grmpf72** [jens-maus/RaspberryMatic#2684]
### Describe the issue you are experiencing

Unter Einstellungen/Favoriten wird die Favoritenliste (habe nur eine) genausooft angezeigt wie man Benutzer damit verbindet!

### Describe the behavior you expected

Favoritenliste wird nur einmal angezeigt - egal wie viele Benutzer damit verbunden sind.

### Steps to reproduce the issue

In Einstellungen/Favoriten die Favoriten bearbeiten, mehrere User damit verbinden und dann speichern.

### What is the version this bug report is based on?

 	3.75.6.20240316

### Which base platform are you running?

rpi3 (RaspberryPi3, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
no, sorry
```

**Comment by jens-maus** [comment]
Bitte mit Screenshot zeigen was du meinst.

**Comment by grmpf72** [comment]
<img width="1144" alt="Screenshot 2024-03-18 105401" src="https://github.com/jens-maus/RaspberryMatic/assets/163859179/1c57411f-b11b-4bda-9d7f-754f4c4c2c0c">
Alle 5 vorhandenen Benutzer mit der Favoritenliste verbunden = 5x Anzeige der Liste

**Comment by jens-maus** [comment]
Du unterschlägst in deinem Screenshot leider die wichtige Spalte "Benutzer" ganz rechts.

**Comment by jens-maus** [comment]
Nein, ich meinte exakt in dem 1. screenshot den du da gezeigt hast fehlt recht doch noch zwei spalten... du hast hier nur einen teil der ansicht gezeigt.

**Comment by grmpf72** [comment]
![Screenshot 2024-03-18 141537](https://github.com/jens-maus/RaspberryMatic/assets/163859179/d2b42cd0-eefd-4c6c-a72f-d0227b7aa48e)

**Comment by grmpf72** [comment]
![Screenshot 2024-03-18 142002](https://github.com/jens-maus/RaspberryMatic/assets/163859179/ffb94dfe-050f-4048-8fad-2a1e5d4bd04b)

**Comment by jens-maus** [comment]
na sieht doch gut und normal aus. jeder der 5 benutzer hat hier natürlich seine eigene Ansicht damit man dort in den Ansichten auch die Reihenfolge nutzerbasiert machen kann. Das ist kein Bug, sondern schlichtweg ein Missverständnis deinerseits.

**Comment by grmpf72** [comment]
Sorry, aber da steht bei Reihenfolge überall 1. Das kann nicht korrekt sein. Ich habe gerade nochmal auf der Original-CCU geguckt: Da ist es genau einmal zu sehen wenn 5 Nutzer angehakt sind. Außerdem woher soll man wissen, welche der 5 Favoriten für welchen User ist. Nene! Da stimmt was gar nicht.
Ist doch auch ganz einfach zu testen: Leg mal Favoriten an, verbinde die mit mehr als einem Benutzer und dann guck mal was passiert.
