### ISSUE TITLE
/status und Bedienung/  SCHALT AKTOR device zeigt 3 zusätzliche buttons 

### ISSUE THREAD

**Issue by kw123** [jens-maus/RaspberryMatic#2686]
### Describe the issue you are experiencing

Nach click auf ein/aus werden 2 zusätzliche knopfreihen angezeigt (gleicher Inhalt), nach refresh (neu auf /status und Bedienung/  hinein) ist alles wieder normal
[Screenshot 2024-03-18 at 22 34 12](https://github.com/jens-maus/RaspberryMatic/assets/17803572/84c0620c-c25e-492e-8835-0b518abe3b44)

### Describe the behavior you expected

sollten keine zusaetzlichen Knöpfe zu sehen sein.

### Steps to reproduce the issue

1.click auf an aus
2.
3.
...

### What is the version this bug report is based on?

3.75.6.20240316

### Which base platform are you running?

rpi3 (RaspberryPi3, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
nichts dazu im log
```

### Additional information

war  gestern noch nicht so. upgrade  heute auf 3.75.6.20240316 upgrade,  dann Fehler

**Comment by jens-maus** [comment]
Duplicate of #1467
