### ISSUE TITLE
Mediola 2.3.1

### ISSUE THREAD

**Issue by Ritschi75** [jens-maus/RaspberryMatic#269]
Hallo
Ich habe mir gestern die neue Raspi Version 2.31.25.20180225-rpi3.zip installiert.
Seit da funktioniert die Steuerung über Mediola 2.3.1 nicht mehr.
Ebenfalls wird der Status nicht mehr angezeigt, oder nicht korrekt angezeigt.
Ich habe nun wieder die alte Version installiert, wo alles funktioniert.
Ist das ein Bug bei allen, oder nur bei mir?
Gruss
Ritschi75

**Comment by jens-maus** [comment]
Bitte genauer ins detail gehen. Was genau geht bitte nicht, welche RaspberryMatic vorversion ist installiert die geht. Wird RaspberryMatic überhaupt gefunden von mediola wenn man nach CCUs sucht? Und natürlich auch mal im HomeMatic-Forum bach Hilfe fragen. Das hier ist ein bugtracker und kein support-Forum.

**Comment by Ritschi75** [comment]
Tja, dann bin ich hier wohl falsch. Werde meine Frage im Forum stellen, obwohl ich denke dass das ja irgend ein Bug sein muss ;)
Zu deinen Fragen:
Vorversion Installiert: 2.31.25.20180120
RaspberryMatic wird von Mediola gefunden.
Ebenfalls wurden die Geräte nochmal neu über den Gerätemanager hinzugefügt.
Leider ohne erfolg.

Gruss
Ritschi
