### ISSUE TITLE
Fehlerhafte Kanaleinstellungen von HM-LC-RGBW-WM

### ISSUE THREAD

**Issue by Knallochse** [jens-maus/RaspberryMatic#270]
Bei dem Aktor HM-LC-RGBW-WM lässt sich unter Programme erstellen 
die Auswahl „Kanalaktion“ in der WebUI nicht bedienen.

Es ist nichts zum einstellen da. Weder unter Farbe (Kanal:2) noch unter Programme (Kanal:3).
Getestet unter Safari, Chrome und IE - gleiche Ergebnis.

Laut EQ3 tritt dieses Problem auf der CCU2 nicht auf. 
Bei mir sieht das auf dem RaspberryMatic unter 2.29.23 so aus.
![2755f471-4698-4c8c-86a5-e0a48e010a46](https://user-images.githubusercontent.com/36857242/36683169-2cd0750c-1b1d-11e8-8866-bea14cbe08bb.jpeg)

**Comment by jens-maus** [comment]
Bitte zuerst RaspberryMatic auf die aktuellste 2.31.25.20180225 updaten und dann erneut probieren und Reporten ob das eine Lösung bringt.

**Comment by HMside** [comment]
Hallo Jens, leider besteht das Problem auch mit der aktuellen Version nach wie vor. Ich werde mir das morgen mal genauer anschauen. Auf der CCU2 ist alles i.O.

**Comment by jens-maus** [comment]
@HMside Danke das du dir das anschauen willst. Die einzige Stelle an der ich mir vorstellen könnte wo etwas ggf. anders ist bzgl. CCU2 und RaspberryMatic im Hinblick auf den RGBW ist:

https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0019-WebUI-Fix-SideIncControls.patch#L19

Ggf. löst das ja irgendetwas negatives aus? Alternativ wäre es natürlich gut ggf. mal so einen HM-LC-RGBW-WM zur Hand zu haben damit ich sowas genauer debuggen kann.

**Comment by HMside** [comment]
Mit folgenden Anpassungen ist wieder alles im Lot. @jens-maus magst Du die Patches kurzerhand selber einchecken, ich bin immer noch dazu gekommen meinen Fork zu cleanen. Diese Patches sind zumindest aktuell nur für RaspberryMatic, auf der CCU2 wird noch oCH.HSSID und nicht oDP.HSSID verwendet. 
```

--- side.inc.orig
+++ side.inc
@@ -448,12 +448,12 @@
 
                 if (iV == "0") {
 
-                  if (oDP.HSSID().Find("RGBW_COLOR") != -1) {
+                  if (oDP.HSSID().Find("USER_COLOR") != -1) {
                     ! deprecated iV = "0,200,0.5,0";
                     iV = "{'ACT_HSV_COLOR_VALUE_STORE':0,'ACT_BRIGHTNESS_STORE':200,'RAMP_TIME_STORE':0.5,'ON_TIME_STORE':0}";
                   }
 
-                  if (oDP.HSSID().Find("RGBW_AUTOMATIC") != -1) {
+                  if (oDP.HSSID().Find("USER_PROGRAM") != -1) {
                     ! deprecated iV = "0,200,0.5,0,0,199";
                     iV = "{'ACT_COLOR_PROGRAM_STORE':0,'ACT_BRIGHTNESS_STORE':200,'RAMP_TIME_STORE':0.5,'ON_TIME_STORE':0, 'ACT_MIN_BORDER_STORE':0, 'ACT_MAX_BORDER_STORE':199}";
                   }
```

```
--- webui.js.orig
+++ webui.js
@@ -13177,7 +13177,7 @@
        jQuery("#RGBWControllerBrightness").show();
        break;
        */
-      case "RGBW_COLOR" :
+      case "USER_COLOR" :
         /*
          Array curValues
          0 Color val
@@ -13225,7 +13225,7 @@
         jQuery("#RGBWControllerColor").show();
         this.__activateColorPicker();
         break;
-      case "RGBW_AUTOMATIC":
+      case "USER_PROGRAM":
         /*
          Array curValues
          0 Program
@@ -13397,7 +13397,7 @@
       case "BRIGHTNESS" :
         this.configString = this.__getBrightness();
         break;
-      case "RGBW_COLOR" :
+      case "USER_COLOR" :
         var freeRampTimeHour = jQuery("#colorRGBEnterFreeRampTimeHour").val(),
           freeRampTimeMin = jQuery("#colorRGBEnterFreeRampTimeMin").val(),
           freeRampTimeSec = jQuery("#colorRGBEnterFreeRampTimeSec").val();
@@ -13420,7 +13420,7 @@
 
         this.configString = this.__getColor();
         break;
-      case "RGBW_AUTOMATIC":
+      case "USER_PROGRAM":
 
         var freeRampTimeHour = jQuery("#prgRGBEnterFreeRampTimeHour").val(),
           freeRampTimeMin = jQuery("#prgRGBEnterFreeRampTimeMin").val(),

```
