### ISSUE TITLE
Eingabefeld für Gerätekonstante bei HmIP-ESI lässt keine zweite Nachkommastelle zu

### ISSUE THREAD

**Issue by cmd-sam** [jens-maus/RaspberryMatic#2712]
### Describe the issue you are experiencing

https://github.com/jens-maus/RaspberryMatic/assets/54635772/38cae62a-e0b6-4174-823a-3102dee8ef2e

### Steps to reproduce the issue

siehe Video

### What is the version this bug report is based on?

3.75.6.20240316

### Which base platform are you running?

intelnuc (intel NUC, AMD64/x86_64)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Additional information

Ich habe es in Safari, Firefox und DuckDuckGo Browser auf MacOS 14.3 ausprobiert. Sowie in WIN11 in Chrome.

**Comment by Baxxy13** [comment]
eQ-3 hatte da was gefixt (und heute eine neue CCU3-Version veröffentlicht) was möglicherweise dein Problem angeht.
Der Fix ist in den RM-Nightly's drin, du könntest also mal einen installieren und gucken ob das damit vielleicht schon gelöst ist.

**Comment by jens-maus** [comment]
Ehrlich gesagt bin ich mir selbst nicht so sicher ob der mini-fix den eQ3 da in die 3.75.7 eingebaut hat wirklich die Lösung auch für dieses HmIP-ESI Gerät hier ist. Die Routinen die eQ3 angefasst hatte um da was für die Nachkommastellenanzeige in der WebUI zu reparieren hatten wir im Rahmen von RaspberryMatic ja schon länger angepasst und verbessert. Würde mich nicht wundern wenn sich da diesbzgl. nichts tut mit der 3.75.7.

Wäre aber auch gut wenn du (@Baxxy13) hier vielleicht mal kurz querchecken könntest ob bei anderen Geräten mit der Nachkommastellenanzeige und eingabe mit dem aktuellen 3.75.7 nightly snapshot noch alles soweit gut ist...

**Comment by Baxxy13** [comment]
Das ist gar nicht so einfach einen passenden Parameter, der 2 Nachkommastellen erlaubt, zu finden.

Die Schwellwerte von IP-Messaktoren erlauben 2 Nachkomastellen, die kann ich auch problemlos mit aktuellem 3.75.7er Nightly setzen. Ich weiß aber nicht ob man das mit der Zählerkonstante des ESI vergleichen kann.
![ESI_GAS_Zaehlerkonstante](https://github.com/jens-maus/RaspberryMatic/assets/54898249/01c5b156-60ff-42eb-a318-d18c8ba7a420)

**Comment by jens-maus** [comment]
Hmm. Dann brauchen wir für diese HmIP-ESI Sacher wohl mehr tester die einfach mal den nightly snapshot installieren und konkret testen...

**Comment by PhilippEngler** [comment]
In der 3.57.7 von EQ3 lässt sich die Gerätekonstante mit zwei Nachkommastellen angeben, in der RaspberryMatic 3.75.7.20240420 und auch in der letzten Nightly 3.75.7.20240519-751e2c funktioniert das nicht.

Es liegt an dem Aufruf der `ProofAndSetValue`-Funktion in der folgenden Zeile (leider nur aus den Entwicklertools des Browsers)

`<input id="separate_CHANNEL_1_2" type="text" size="5" value="0.01" name="METER_CONSTANT_VOLUME" onblur="ProofAndSetValue(this.id, this.id, '0.0', '65.5', 1);">`

werden die Parameter wie folgt geändert

`ProofAndSetValue(this.id, this.id, '0.00', '65.53', 1);`

werden zwei Nachkommastellen übernommen. Kann es sein, dass das Problem durch einen WebUI-Patch entsteht?

**Comment by Baxxy13** [comment]
Hmm, die `ProofAndSetValue`-Funktion arbeitet nach meinen Tests richtig.
Das Problem scheint das sie nicht mit der korrekten Anzahl Nachkommastellen gefüttert wird.
Warum das an dieser Stelle passiert kann ich aktuell nicht sagen.
Der Gegentest mit den Grenzwerten einer PSM passt jedenfalls:
![RM_PSM_Grenzwerte_ProofAndSet](https://github.com/jens-maus/RaspberryMatic/assets/54898249/3f14cfdd-f769-40bc-b495-9ace45996902)

**Comment by PhilippEngler** [comment]
Ja, die `ProofAndSetValue`-Funktion arbeitet korrekt (habe ich auch in keinster Weise angezweifelt). Aber die übergebenen Minimum- und Maximum-Werte sind nicht korrekt. Wenn man die ändert, werden auch für den ESI zwei Nachkommastellen übernommen.

**Comment by jens-maus** [comment]
Dann sollte man jemand herausfinden wo genau im WebUI Quellcode der proofandset Aufruf stattfindet damit man da sicherstellen kann das diese dann mit zwei nachkommastellen aufgerufen wird. D.h. Jemand müsste man konkret im Dateisystem die Datei+Zeile herausfinden wo die für den ESO aufgerufen wird, dann könnte ich die ggf. anpassen.

**Comment by jens-maus** [comment]
Hab mir das jetzt mal selbst ein wenig angeschaut und vielleicht die Lösung dazu bereits gefunden und dafür den entsprechenden WebUI Patch modifiziert damit er auch mit `METER_CONSTANT_ENERGY` klar kommt und hier zwei Nachkommastellen ausgibt und zur Eingabe zulassen sollte. Bitte also Betroffene den nächsten nightly snapshot am besten einmal testen und zurückmelden ob diese Anpassung das hier diskutierte Problem wirklich löst.

**Comment by jens-maus** [comment]
> Zumindest bei mir haben Deine Änderungen in der RaspberryMatic `3.75.7.20240521-7d6677` leider nicht den gewünschten Erfolg gehabt.

Danke, das hat weitergeholfen. Mit dem nächsten nightly snapshot sollte das dann hoffentlich komplett behoben sein und eine zweistellige Eingabe von Werten dann mit einem HmIP-ESI möglich sein. Bitte dann reporten dann können wir hier dicht macht.

**Comment by PhilippEngler** [comment]
Danke Jens, in der `3.75.7.20240522-b64307` funktioniert das nun korrekt.
