### ISSUE TITLE
Update Issue 2.31.25.20180225

### ISSUE THREAD

**Issue by Marrom77** [jens-maus/RaspberryMatic#272]
Hallo zusammen,
verstehe nicht, was hier los ist. Nach dem Update auf das FEB-Release funktioniert das Raspi3-System nicht mehr wie gewollt. Langsam, scheint zu hängen, sieht man wenn man auf <Status und Bedienung> auf <Gewerke> klickt und das System minutenlang hängt. Alte SD-Karte JAN-2018 rein in der Hoffnung, dass alles wieder funktioniert, aber gleiches Problem. Nix geht. System ist grottenlangsam, hängt, und Interfaces zu Osram Lightify über Programme tun nix mehr. Hat jemand ähnliche Erfahrungen gemacht und eine Idee, wie man aus der Nummer raus kommt?
Danke und Gruß
Matsche

**Comment by Marrom77** [comment]
Wenn man auf "Status und Bedienung" "Gewerke" klickt, ist es furchtbar langsam bzw. es passiert scheinbar nix. Das Problem hatte ich in der Vergangenheit schon beobachtet, wenn eigene Programme hinzugefügt wurden, bei denen möglicherweise irgendwelche Schleifen provoziert wurden. Das ist aber heute nicht passiert, es wurde nichts geändert, ausser natürlich dem Update auf die aktuelle Rasperriematic...

**Comment by jens-maus** [comment]
Bitte an das HomeMatic Forum wenden, das hier ist ein BugTracker und kein Diskussionsforum

**Comment by Marrom77** [comment]
Sorry, mach ich...
