### ISSUE TITLE
HomeKit HomeMatic 

### ISSUE THREAD

**Issue by PatrickKozar** [jens-maus/RaspberryMatic#2724]
### Describe the issue you are experiencing

HomeKit HomeMatic funktioniert nicht mehr! 

Neustart wurde mit Fehlern abgeschlossen:

Please see /var/log/addon-uninstall-error.log on the central for more details.

### Describe the behavior you expected

Die Geräte zeigen in der App an Keine Antwort und lassen sich über die App nicht steuern 

### Steps to reproduce the issue

1firmwareversion 3.75.7.20240420 installiert 
2.
3.
...

### What is the version this bug report is based on?

3.75.7.20240420

### Which base platform are you running?

rpi3 (RaspberryPi3, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
***** /var/log/addon-uninstall-error.log *****
start-stop-daemon: warning: killing process 1878: No such process
kill: you need to specify whom to kill
start-stop-daemon: warning: killing process 4957: No such process
kill: you need to specify whom to kill
start-stop-daemon: warning: killing process 5184: No such process
kill: you need to specify whom to kill
start-stop-daemon: warning: killing process 6162: No such process
kill: you need to specify whom to kill




***** /var/log/hmhapinstall.log *****
[Installer]Check existency of the daemon [Installer] daemon exists lets light this candle [Installer] Check existency of the daemon [Installer] daemon exists lets light this candle [Installer] Check existency of the daemon [Installer] daemon exists lets light this candle [Installer] Check existency of the daemon [Installer]daemon exists lets light this candle [Installer] Check existency of the daemon [Installer] daemon exists lets light this candle
```

**Comment by jens-maus** [comment]
Die ist kein Problem von RaspberryMatic selbst, sondern vielmehr vom HAP Homematic (HomeKit) Addon (siehe https://github.com/thkl/hap-homematic). Dieses ist leider inzwischen wie es aussiehst nicht mehr maintained, d.h. es kommen keinerlei Updates mehr dafür raus. Bitte daher dort im Projekt melden. Aktuell rate ich sogar davon ab dieses überhaupt noch zu verwenden da dieses darüberhinaus auch noch die Stabilität von RaspberryMatic bzw. der CCU selbst gefährdet.

**Comment by PatrickKozar** [comment]
Hallo danke für die schnelle Antwort ! Wissen  Sie zufällig eine Alternative  ? Danke.
