### ISSUE TITLE
rfd startet nicht, LXC auf Tinker-S mit Armbian 24.2.5 Bookworm CLI

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#2729]
### Describe the issue you are experiencing

Nachdem ich mit Hilfe der Anleitung von Alex für piVCCU die Kernel-Header installiert hatte (siehe: #2728) sah soweit alles gut aus.
Problem ist nun das der rfd nicht startet.

### Describe the behavior you expected

Problemloses starten aller Dienste inklusive rfd.

### Steps to reproduce the issue

1. frisches Armbian 24.2.5 Bookworm CLI auf einem Tinker-S aufsetzen
2. System nach Anleitung vorbereiten
3. nötige Kernel-Header nach Anleitung von piVCCU installieren
4. install-lxc.sh aufrufen und durchlaufen lassen
5. System neu starten
6. in die LXC-Konsole einloggen....
...

### What is the version this bug report is based on?

3.75.7.20240501-3c8648-lxc_arm

### Which base platform are you running?

lxc_arm (Linux Container Infrastructure, ARM/armhf)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
root@tinkerboard:~# sudo lxc-console raspberrymatic

Connected to tty 1
Type <Ctrl+a q> to exit the console, <Ctrl+a Ctrl+a> to enter Ctrl+a itself
Identifying host system: Rockchip RK3288 Asus Tinker Board S (lxc), OK
Initializing RTC Clock: no hardware found
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Running seedrng: OK
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting iptables: OK
Starting network: eth0: link up, dhcp, firewall, inet up, 192.168.113.189, OK
Identifying Homematic RF-Hardware: ....HmRF: RPI-RF-MOD/GPIO@ff190000.serial, HmIP: RPI-RF-MOD/GPIO@ff190000.serial, OK
Updating Homematic RF-Hardware: RPI-RF-MOD: 4.4.22, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: ...OK
Starting rfd: ....................ERROR
Starting HMIPServer: ..........OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.75.7.20240501 (raspmatic_lxc_arm)

Please press Enter to activate this console.
```

### Additional information

Eine piVCCU3 Installation lief dann problemlos.

**Comment by Baxxy13** [comment]
Ich bräuchte mal nen Denkanstoß wie ich ggf. das Startproblem des rfd debuggen könnte.
Irgendwelche debug/logging - Parameter vielleicht.

**Comment by jens-maus** [comment]
Ruf einfach mal rfd so auf der kommandozeile auf und schau was passiert. Vielleicht fehlen ja irgendwelche libs oder dependencies

**Comment by Baxxy13** [comment]
```
root@homematic-raspi:~# /bin/rfd
/bin/rfd: error while loading shared libraries: libusb-1.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by jens-maus** [comment]
> ```
> 
> root@homematic-raspi:~# /bin/rfd
> 
> /bin/rfd: error while loading shared libraries: libusb-1.0.so.0: cannot open shared object file: No such file or directory
> 
> ```

Das ist interessant. Liest sich als wenn da ein Paket in der Buildroot Umgebung für lxc_arm fehlt... muss ich mir dann mal anschauen.

**Comment by Baxxy13** [comment]
Grundsätzlich ist das hier eher "Spielerei" weil ich mal gucken wollte wie sich RM als LXC (statt nativ) auf dem Tinker-S schlägt.
Wenn das aber problemlos läuft (#2728 gefixed)  dann haben wir quasi einen 1:1 Pendant zu piVCCU3 auf dem Tinker. 😉

**Comment by jens-maus** [comment]
So, ich denke ich hab das Problem gefunden und repariert. Da hat in der tat für die 32bit LXC platform das LIBUSB paket gefehlt sowie `rfd` nicht starten wollte. Bitte mit dem nächsten nightly snapshot einfach mal probieren. Nun sollte `rfd` hoffentlich starten.

**Comment by Baxxy13** [comment]
Auch hier kommt der Haken dran. 
Läuft, und das im Gegensatz zur nativen (aktuellen) RaspberryMatic auf dem Tinker-S, rasend schnell.

```
root@tinkerboard:~# sudo lxc-console raspberrymatic

Connected to tty 1
Type <Ctrl+a q> to exit the console, <Ctrl+a Ctrl+a> to enter Ctrl+a itself
Identifying host system: Rockchip RK3288 Asus Tinker Board S (lxc), OK
Initializing RTC Clock: no hardware found
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: OK: backup successfully restored
Running seedrng: OK
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting iptables: OK
Starting network: eth0: link up, dhcp, firewall, inet up, 192.168.113.189, OK
Identifying Homematic RF-Hardware: ....HmRF: RPI-RF-MOD/GPIO@ff190000.serial, HmIP: RPI-RF-MOD/GPIO@ff190000.serial, OK
Updating Homematic RF-Hardware: RPI-RF-MOD: 4.4.22, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting sshd: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: ...OK
Starting rfd: .OK
Starting HMIPServer: ..........OK
Starting ReGaHss: .OK
Starting CloudMatic: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.75.7.20240508 (raspmatic_lxc_arm)

Please press Enter to activate this console.
```

**Comment by jens-maus** [comment]
> Auch hier kommt der Haken dran. 
> 
> Läuft, und das im Gegensatz zur nativen (aktuellen) RaspberryMatic auf dem Tinker-S, rasend schnell.

Da ist wirklich interessant, denn Armbian nutzt ja auch kernel 6.6 mit gerade den gleichen patches. Dann kann es prinzipiell nur an den kernel config settings liegen. Kannst du bitte mal /proc/config bzw /proc/config.gz ziehen und irgendwo ablegen damit ich die vergleichen kann mit RM?

**Comment by Baxxy13** [comment]
Hast du da einen passenden Konsolenbefehl zur Hand? 
Dann könnte ich das nachher noch erledigen bevor das lange Wochenende beginnt.

**Comment by jens-maus** [comment]
> Hast du da einen passenden Konsolenbefehl zur Hand? Dann könnte ich das nachher noch erledigen bevor das lange Wochenende beginnt.

Schau einfach mal auf das System. Da sollte es eine Datei `/proc/config.gz` bzw. `/proc/config` geben und die Dateien bräuchte ich. Unter RaspberryMatic gibts die auch und das sind im Grunde Textdateien wo die Kernelkonfigurationen drinstehen. Für RM hab ich die ja, aber für Armbian wäre es gut die zu haben – und ich hab hier gerade kein Armbian für Tinkerboard am laufen.

**Comment by Baxxy13** [comment]
Die einzige `config.gz` habe ich in `/usr/share/doc/u-boot-tools/` gefunden.
Weiß aber nicht ob das die richtige Datei ist.

Bin jetzt aber auch das lange Wochenende unterwegs.

[config.gz](https://github.com/jens-maus/RaspberryMatic/files/15250079/config.gz)
