### ISSUE TITLE
HmIPW-DRI32 zeigt nicht alle Felder in der Gerätekonfiguration an

### ISSUE THREAD

**Issue by Alexander060101** [jens-maus/RaspberryMatic#2736]
### Describe the issue you are experiencing

Wenn man die Einstellungen des Gerätes öffnet, sieht man nur diese beiden Einstellungen pro Kanal (bei Kanalverhalten "Kontakt"):
![image](https://github.com/jens-maus/RaspberryMatic/assets/12053064/08c9ab6f-371f-4a51-afd9-4f1c41759990)

Man muss die Einstellung Kanalverhalten erst zu etwas anderem und dann wieder zurück zu "Kontakt" ändern, um alle Einstellungen zu sehen:
![image](https://github.com/jens-maus/RaspberryMatic/assets/12053064/62b78efd-e3c2-493a-9bc5-98374af99255)

### Describe the behavior you expected

Es sollten sofort alle Einstellungen angezeigt werden

### Steps to reproduce the issue

N/A

### What is the version this bug report is based on?

3.75.7.20240420

### Which base platform are you running?

ova (Open Virtual Infrastructure, AMD64/x86_64)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
N/A
```

**Comment by Maik2208** [comment]
Kann ich bestätigen.
Das Kanalverhalten steht initial auf "Taster", zeigt aber die Feldauswahl von "Schalter" an.
Betrifft den DRI16 ebenfalls.

**Comment by Alexander060101** [comment]
Problem besteht auch in Version 3.77.6.20240720 noch.

**Comment by Baxxy13** [comment]
Wurde das damals ausführlich getestet?
Und kann mal jemand mit den HmIPW-DRI16 / DRI32 den Patch 0186 rückgängig machen und schauen wie sich das mit der aktuellen RM 3.79.6.20241122 verhält.

Das Problem ist das diese Änderung (auf aktueller RM 3.79.6.20241122) Auswirkungen auf andere MULTI_MODE_INPUT_TRANSMITTER - Kanäle hat, z.B. beim HmIP-MOD-RC8.
Hier werden nun immer alle verfügbaren Parameter dargestellt obwohl diese, abhängig vom eingestellten Kanalverhalten, teilweise ausgeblendet werden sollten.

RM 3.79.6.20241122 **mit** [0186-WebUI-Fix-HmIPW-DRI16_DRI32-Channel WebUI patch](https://github.com/jens-maus/RaspberryMatic/commit/c787a5cd092e5d856af625a6194eb976c4d3ff20)
![MOD-RC8_with_0186_Patch](https://github.com/user-attachments/assets/003fba3d-5480-46c5-a51e-5a01c544e4a1)

RM 3.79.6.20241122 **ohne** [0186-WebUI-Fix-HmIPW-DRI16_DRI32-Channel WebUI patch](https://github.com/jens-maus/RaspberryMatic/commit/c787a5cd092e5d856af625a6194eb976c4d3ff20)
![MOD-RC8_without_0186_Patch](https://github.com/user-attachments/assets/afeb5b3b-a3cf-4d6d-b39f-e839a8e7e4dd)

**Comment by jens-maus** [comment]
Vielleicht braucht es dann in der `/www/config/easymodes/etc/hmipChannelConfigDialogs.tcl` ne unterscheidung nach "if HmIPW-DRI16 oder DRI32, dann wie jetzt, ansonsten wie früher?"

**Comment by Baxxy13** [comment]
Möglich.

eQ-3 nutzt selbst: 
`append html "var elmOperationMode = jQuery(\"#separate_$CHANNEL\_2\"),"`

Und ich habe noch nirgends gelesen das es da Probleme mit den HmIPW-DRI16 / DRI32 gibt. 
Das muss aber nichts heißen.
Wie geschrieben, idealerweise wird das auf aktueller RM mal ohne den Patch getestet dann können wir ihn ggf. entfernen.

Mangels IP-Wired bin ich da aber raus. 😉

**Comment by Baxxy13** [comment]
Hmm, hab jetzt mal auf dem Hauptsystem geguckt.
Das ist eigentlich "raus" weil noch 3.77.7.

Da sind die Eingänge der DRSIx auch `MULTI_MODE_INPUT_TRANSMITTER`.
Da ist das nur "mit Patch" korrekt. 
Wenn das mit 3.79.7 so bleibt dann... 

> ne unterscheidung nach "if HmIPW-DRI16 oder DRI32, dann wie jetzt, ansonsten wie früher?"

... eher "if HmIP-MOD-RC8, dann wie füher, ansonsten wie jetzt?"

**Comment by jens-maus** [comment]
> eQ-3 nutzt selbst: `append html "var elmOperationMode = jQuery(\"#separate_$CHANNEL\_2\"),"`
> 
> Und ich habe noch nirgends gelesen das es da Probleme mit den HmIPW-DRI16 / DRI32 gibt. Das muss aber nichts heißen. > Mangels IP-Wired bin ich da aber raus. 😉

Ich kann das heute abend mal testen und berichten ob es auch ohne den Patch geht. Aber @Alexander060101 hat das ja hier berichtet und @Maik2208 hat es dann via PR korrigiert. Muss also irgendwie was dran sein.

**Comment by Maik2208** [comment]
Natürlich konnte ich nicht alle Geräte testen, da ich sie schlichtweg nicht besitze. Aber für den DRI16 und DRI32 konnte ich es testen und da war der Fehler vor der Anpassung da und danach definitiv behoben.

**Comment by jens-maus** [comment]
> > eQ-3 nutzt selbst: `append html "var elmOperationMode = jQuery(\"#separate_$CHANNEL\_2\"),"`
> > Und ich habe noch nirgends gelesen das es da Probleme mit den HmIPW-DRI16 / DRI32 gibt. Das muss aber nichts heißen. > Mangels IP-Wired bin ich da aber raus. 😉
> 
> Ich kann das heute abend mal testen und berichten ob es auch ohne den Patch geht. 

Also hab das jetzt getestet, und es geht OHNE diesen patch hier nicht mit meinem HmIPW-DRI32. D.h. das Problem ist auch prinzipiell noch in der 3.79.6 vorhanden. Die Frage wäre nur wie schränkt man das jetzt ein? Welche Geräte sind noch vom Typ `MULTI_MODE_INPUT_TRANSMITTER` die prinzipiell davon betroffen wären? Ich tendiere immer noch dazu diesen patch hier nochmal umzuarbeiten und ne explizite Prüfung nach HmIPW-DRI16/32 einzubauen, denn bisher gab es nur diesbzgl. die Klagen und kein anderer `MULTI_MODE_INPUT_TRANSMITTER` hatte ähnliche Probleme, oder?

**Comment by Baxxy13** [comment]
Also meine Eingänge der DRSIx sind auch `MULTI_MODE_TRANSMITTER` und bei denen funktioniert es auch nur mit Patch.
Laut Device-Doku gibt es aktuell 18 Geräte die `MULTI_MODE_TRANSMITTER` nutzen, unmöglich alle zu testen.

Da eure HmIPW-DRI16/32 und meine HmIP-DRSIx den Patch "brauchen" sollten wir eher auf das HmIP-MOD-RC8 prüfen und aktuell nur dafür "die alte Version" `append html "var elmOperationMode = jQuery(\"#separate_$CHANNEL\_2\"),"` nehmen.

Ich bekomme leider kein `if else` hin, daher hab ich das für einen Test einfach so gemacht.

```tcl
if {[string equal $dev_descr(TYPE) "HmIP-MOD-RC8"] == 0} {
    append html "console.log('Typ: $dev_descr(TYPE)');"	
	append html "window.setTimeout(function() {"  
      append html "var elmOperationMode = jQuery(\"#separate_$CHANNEL\_1\"),"
      append html "mode = elmOperationMode.val(),"
      append html "chn = elmOperationMode.prop(\"id\").split(\"_\")\[2\];"
      append html "showHideKeyParams(mode, chn);"
    append html "},100);"
}

if {[string equal $dev_descr(TYPE) "HmIP-MOD-RC8"] == 1} {
    append html "console.log('Typ: $dev_descr(TYPE)');"	
	append html "window.setTimeout(function() {"  
      append html "var elmOperationMode = jQuery(\"#separate_$CHANNEL\_2\"),"
      append html "mode = elmOperationMode.val(),"
      append html "chn = elmOperationMode.prop(\"id\").split(\"_\")\[2\];"
      append html "showHideKeyParams(mode, chn);"
    append html "},100);"
}
```
Nicht schön, aber zum Testen geeignet.
https://github.com/eq-3/occu/blob/742b3aa8c561025a531d8729617f1db091d905eb/WebUI/www/config/easymodes/etc/hmipChannelConfigDialogs.tcl#L1121-L1126

**Comment by jens-maus** [comment]
So müsste es jetzt gehen – und siehst auch IMHO schöner aus :)

https://github.com/jens-maus/RaspberryMatic/commit/1ad619812e2faa7a319531d7960ef27bd4830ef5

**Comment by Baxxy13** [comment]
Sehr schön, kurz und knackig.
Funktioniert auf dem System mit MOD-RC8 und auch auf dem anderen mit DRSI4 korrekt.

Hoffen wir mal das das MOD-RC8 der einzige "Sonderfall" ist und bleibt... es gibt ja leider noch viele andere mit dem `MULTI_MODE_INPUT_TRANSMITTER`. 
Ich halte die Augen offen. 😉
