### ISSUE TITLE
RaspberryMatic 3.75.7.20240420 startet nicht auf Odroid C4

### ISSUE THREAD

**Issue by Gluehwurm** [jens-maus/RaspberryMatic#2740]
### Describe the issue you are experiencing

RaspberryMatic 3.75.7.20240420 startet nicht auf Odroid C4 -> "Bitte warten.Sie werden automatisch auf die Startseite umgeleitet".
Diese Umschaltung erfolgt nicht. (auf Odroid N2 funktioniert es)

### Describe the behavior you expected

Login-Maske soll erscheinen

### Steps to reproduce the issue

Neue Version auf eMMc laden
C4 mit Strom versorgen
C4 bootet und auf dem HDMI-Bildschirm läuft es hoch bis Alt+F2 und Angabe der IP
EIngabe der IP im Browser -> keine Startseite, nur "BlueScreen" (auf N2 kommt die Startseite)

### What is the version this bug report is based on?

3.75.7.20240420 und 

### Which base platform are you running?

odroid-c4 (ODROID C4, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

HM-CFG-LAN

### Anything in the logs that might be useful for us?

```txt
no logs
```

**Comment by jens-maus** [comment]
Dieses Problem ist/war bereits bekannt und ist in den aktuellen nightly snapshots bereits gelöst (siehe https://github.com/jens-maus/RaspberryMatic/commit/c547b7bec7c72e1e74cc0f53e737e3052f702256) und sollte somit mit der nächsten stabilen Version beseitigt sein.
