### ISSUE TITLE
Firefox: Button Geräte-Firmware wird falsch dargestellt.

### ISSUE THREAD

**Issue by manny4566** [jens-maus/RaspberryMatic#2741]
### Describe the issue you are experiencing

Hi, der Button "Geräte-Firmware" wird im Firefox scheinbar falsch angezeigt mit einem Zeilenumbruch

Firefox:
![grafik](https://github.com/jens-maus/RaspberryMatic/assets/23473485/c699193d-c908-4726-a37d-21ef5283409f)
Scrollen innerhalb des Buttons:
![grafik](https://github.com/jens-maus/RaspberryMatic/assets/23473485/d5db934c-bbe5-4061-8fab-da2e3176edac)

Chrome:
![grafik](https://github.com/jens-maus/RaspberryMatic/assets/23473485/26251f98-6007-46b1-8e3a-6578dcfc0bb5)

### Describe the behavior you expected

Korrekte Darstellung wie im Chrome

### Steps to reproduce the issue

1. Firefox -> Einstellungen -> Geräte-Firmware - Übersicht

### What is the version this bug report is based on?

3.75.7.20240420

### Which base platform are you running?

ova (Open Virtual Infrastructure, AMD64/x86_64)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
n/a
```

**Comment by Baxxy13** [comment]
Kann ich hier auf einem Testsystem nicht verifizieren.
(Firefox im Vollbild / 1080p)
![RM-Firefox_Geräte-Firmware Button](https://github.com/jens-maus/RaspberryMatic/assets/54898249/fb8ed50a-b3ea-48d1-bc1f-5eb7f2d41f06)
