### ISSUE TITLE
HmIP-PSM-2 QHJ Einheit der Grenzwerte fehlt

### ISSUE THREAD

**Issue by grunes** [jens-maus/RaspberryMatic#2746]
### Describe the issue you are experiencing

Ich habe bereits mehrere HMIP-PSM am laufen, auf den Aktoren kann ich den Grenzwert des Kanals 7 (Entscheidungswert) in Wall eingeben. Auf den neuen HmIP-PSM-2 QHJ ist die Eingabe eines Wertes von 0-16777215 (ohne Einheit) möglich.

![image](https://github.com/jens-maus/RaspberryMatic/assets/36551079/f6f65a9e-f302-43b4-b4ff-f2a061ed6042)

### Describe the behavior you expected

Eine Einheit (Watt) währe hier sehr hilfreich: (Beispiel HmIP-PSM)

![image](https://github.com/jens-maus/RaspberryMatic/assets/36551079/ed4e51a7-8fa1-4d0b-84fd-a4606e432a0e)

### Steps to reproduce the issue

1. Konfigurationsseite der Aktoren aufrufen
2. Aktor auswählen
3. Einstellungen des Kanals 7 aufrufen

### What is the version this bug report is based on?

3.75.7.20240420

### Which base platform are you running?

tinkerboard (ASUS Tinkerboard, ARM/armhf)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Nothing
```

### Additional information

Laut ELV Holtine entsprechen die angezeigten Werte folgenden Standardwerten auf der CCU3:

1000 = 10 Watt
10000 = 3600 Watt

Laut diesem [Foreneintrag](https://homematic-forum.de/forum/viewtopic.php?f=58&t=78296&p=788370&hilit=HmIP+PSM2#p788370) ist der Eingabewert = W * 56,11, was den Angaben von ELV widerspricht.

**Comment by Baxxy13** [comment]
Auch wenn das nicht das ist was du ggf. hören möchtest...
Das muss eQ-3 fixen!

Klar könnten wir da jetzt (in RM) ne Einheit dranpappen, aber was bringt das wenn der einzutragende Wert Einheitslos ist bzw. erstmal mit nicht verifizierten Formeln umgerechnet werden muss.

Das eQ-3 informiert werden muss steht auch über und unter dem verlinkten Forenbeitrag.
Entweder macht's keiner, oder eQ-3 juckt's halt nicht.

**Comment by grunes** [comment]
Ich habe mit dem Support gesprochen (nachdem meine Mail unbeantwortet bleib). Dort wurde mir gesagt das RaspberryMatic das fixen muss und eQ-3 da nichts damit zu tun hat. :-/ 

Ggf. war es der falsche Ansprechpartner?! Gibt es eine bestimmte Kontaktadresse für solche Fälle?

**Comment by Baxxy13** [comment]
Hmm, man müsste erstmal verifizieren ob das nur in RM so ist oder auch bei Original-CCU3.
Ich tippe auf letzteres.
Ist dem so dann kannst du das dem eQ-3 Support auftischen, solltest aber vermeiden RaspberryMatic zu erwähnen bzw. bei Screenshots drauf achten das keine Indizien auf RaspberryMatic verweisen.
Wollen sie ein Backup kannst du die Sache knicken, da müsste man dann eine Vanilla-CCU3 aufsetzen wo nur das Gerät angelernt ist und der Fehler deutlich zu sehen ist.
Viel Erfolg!
https://homematic-ip.com/de/kontakt

**Comment by grunes** [comment]
Wie gesagt, laut ELV ist der Wertebereich auf der **original CCU3**: 0W - 3680W. (bei ELV im Lab)

Daher liegt auch die Vermutung nahe das es doch an RaspberryMatic liegt!

Ich habe leider keine originale CCU, nur mein tinkerboard, daher kann ich hier nicht weiter testen, ich befürchte aber das eQ-3 auf ihrer original Firmware auch 0 - 3680 Watt angezeigt bekommt.

**Comment by Maik2208** [comment]
Dann probier doch selber mal aus, ob die Angabe von ELV oder der seltsame Faktor stimmen.

**Comment by grunes** [comment]
sieh oben:

> ...
> Laut diesem [Foreneintrag](https://homematic-forum.de/forum/viewtopic.php?f=58&t=78296&p=788370&hilit=HmIP+PSM2#p788370) ist der Eingabewert = W * 56,11, was den Angaben von ELV widerspricht.

**Comment by Maik2208** [comment]
Wir haben jetzt zwei verschiedene Aussagen, wobei ich mir auch eine dritte Variante vorstellen könnte.

Also gerne mal selbst testen

**Comment by Baxxy13** [comment]
Was es auch ist, es ist Murks.
Niemand will da irgendwas umrechnen müssen sondern einfach seine Grenzwerte "so wie bei der alten PSM" intuitiv eintragen.

"Wenn der Plasma-TV mehr als 300W zieht schalte die Klimaanlage ein"... oder so. 😉 

Jedenfalls habe ich mal im Forum um Hilfe gefragt, damit zumindest mal verifiziert wird ob es ein RaspberryMatic only - Problem ist, oder eben nicht. Ich bleibe bei meiner Meinung... es ist kein RM - only Problem.

Schauen wir mal...
https://homematic-forum.de/forum/viewtopic.php?f=60&t=82499#p804366

**Comment by jp112sdl** [comment]
Wie sieht es denn bei der PSM-2 (ohne QHJ) aus? Passt es da?

Hängt evtl. was in den ReGa Metadaten quer?

**Comment by Baxxy13** [comment]
Ich habe mal die Anfrage (im Forum) bezüglich des Einstellungs-Screenshots auf die HmIP-PSM-2 erweitert.

Ich habe hier nur die "original" HmIP-PSM, kann also nichts weiter testen.
Wenn jemand ein Backup zur Verfügung stellt (mit HmIP-PSM-2 / PSM-2 QHJ) könnte ich dieses auf eine abgeschottete Test-CCU3 restoren und mir die Sache selbst mal angucken.

**Comment by Baxxy13** [comment]
So, die Screenshot's sind im Forenthread eingetroffen.
Wie vermutet betrifft es auch original CCU3 und auch die HmIP-PSM-2 (ohne QHJ).

**Comment by grunes** [comment]
> So, die Screenshot's sind im Forenthread eingetroffen. Wie vermutet betrifft es auch original CCU3 und auch die HmIP-PSM-2 (ohne QHJ).

Dann weiß ich jetzt auch warum der eQ-3 Support gar keine Auskunft geben wollte. Und ELV hat anscheinend eine andere Firmware in ihrem Lab oder der Support Mitarbeiter hat mich einfach eiskalt angelogen. Schwierige Firmenpolitik!

**Comment by jens-maus** [comment]
> https://github.com/eq-3/occu/blob/master/WebUI/www/config/easymodes/etc/uiElements.tcl#L21-L42 https://github.com/eq-3/occu/blob/master/WebUI/www/config/easymodes/etc/uiElements.tcl#L172-L185
> 
> Absolut ins Blaue geraten... Da mal noch `hmip-psm-2` hinzufügen?

Das könnte in der Tat klappen. Müsste aber mal jemand testen der solch einen HmIP-PSM-2 auch besitzt...

**Comment by PhilippEngler** [comment]
> https://github.com/eq-3/occu/blob/master/WebUI/www/config/easymodes/etc/uiElements.tcl#L21-L42 https://github.com/eq-3/occu/blob/master/WebUI/www/config/easymodes/etc/uiElements.tcl#L172-L185
> 
> Absolut ins Blaue geraten... Da mal noch `hmip-psm-2` hinzufügen?

Das war ein sehr guter Hinweis, danke @jp112sdl. Zusätzlich muss jeweils noch `"hmip-psm-2 qhj"` (mit den Anführungszeichen wegen des Leerzeichens) hinzugefügt werden.

Außerdem muss in der `hmip_helper.tcl` der Funktion [`devIsPowerMeter`](https://github.com/eq-3/occu/blob/master/WebUI/www/config/easymodes/etc/hmip_helper.tcl#L2682-L2691) ebenfalls `hmip-psm-2` und `"hmip-psm-2 qhj"` eingefügt werden. Danach stimmen die Werte wieder und die Einheiten sind da.

Ich kann es nur für den PSM-2 QHJ testen, damit klappt es nun.

![PSM-2 QHJ](https://github.com/jens-maus/RaspberryMatic/assets/77169354/29c0002a-7e3a-4b92-841c-c446ac2b3277)

Lohnt es sich dafür einen Patch zu erstellen bzw. einen vorhandenen zu erweitern?

**Comment by jens-maus** [comment]
Na wenn das alles verifiziert funktioniert, dann her mit einem neuen WebUI Patch! Bitte einen PullRequest wie immer einsenden und los geht es 😎

**Comment by PhilippEngler** [comment]
Vielleicht können HmIP-PSM-2 und/oder HmIP-PSM-2 QHJ Nutzer die Änderungen vornehmen und testen?

Falls jemand mit einer HmIP-PSM (ohne Anhänge) [diese hier markierte Zeile aus der Datei `www/config/easymodes/etc/hmip_helper.tcl`](https://github.com/eq-3/occu/blob/master/WebUI/www/config/easymodes/etc/hmip_helper.tcl#L2687) löschen könnte und folgendes nachsehen könnte ob:
- die Minimal- und Maximalwerten  in diesem Falle ebenfalls `0` und `16777215` betragen
- die Werte in den beiden Textboxen um den Faktor 100 höher sind als mit der Zeile

Einen [WebUI Patch](https://github.com/PhilippEngler/RaspberryMatic/commit/985321b60f3d02e49f22288f8181ceb15101d972) habe ich testweise erzeugt. Es ist mein erster Versuch, bin mir nicht sicher, ob das so korrekt ist.

**Comment by Baxxy13** [comment]
Bitte beachten das die PSM-2 (und vermutlich auch die PSM-2 QHJ) nur noch einen Messbereich von 0-3000W haben. Nur das Original (PSM) geht bis 3680W. 

Ich bleibe dabei das von eQ-3 gefixt werden sollte.
Es nützt nichts da einfach einen Wertebereich dranzuschreiben wenn das was man eingibt nicht zu dem Ergebnis (wegen irgendwelcher Umrechnungen) führt das man erwartet.

**Comment by jens-maus** [comment]
> Ich bleibe dabei das von eQ-3 gefixt werden sollte.

eQ-3 ist darüber schon informiert und liest hier auch still mit.

**Comment by PhilippEngler** [comment]
> Bitte beachten das die PSM-2 (und vermutlich auch die PSM-2 QHJ) nur noch einen Messbereich von 0-3000W haben. Nur das Original (PSM) geht bis 3680W.

Danke @Baxxy13, das mit dem Messbereich bis 3000 W stimmt, das [habe ich eben noch angepasst](https://github.com/PhilippEngler/RaspberryMatic/commit/1b870c4ea13977431c01c44d7f6aa3f117e126c7) (auf der Website von ELV beim 3er Pack steht noch 3680 W).

Ansonsten kann ich nach diversen Tests nur sagen, dass die Werte nach der Änderung passen sollten und keine Umrechnungen benötigen (ohne die Änderungen ist der Wert in den Textfeldern um den Faktor 100 zu hoch; kann man im [zugehörigen Forums-Eintrag](https://homematic-forum.de/forum/viewtopic.php?f=60&t=82499#p804472) sehen).

**Comment by jens-maus** [comment]
Na dann her mit dem PullRequest 😜

**Comment by grunes** [comment]
Funktioniert perfekt!
Vielen Dank. 

![image](https://github.com/jens-maus/RaspberryMatic/assets/36551079/c6cf8959-8c1c-4c7c-8194-be21ae0ade5e)
