### ISSUE TITLE
Rasperry Matic startet nicht mehr nach update auf ubuntu.6.8.0-1024

### ISSUE THREAD

**Issue by pstestos** [jens-maus/RaspberryMatic#2748]
### Describe the issue you are experiencing

Ich habe meinen raspi mit ubuntu 24.4 mal updated. Danach ging Raspberrymatic im docker nicht mehr. Die Oberfläche sagt man sollle warten - aber da passiert nichts. 

im log sieht es so aus:
```
Identifying host system: Raspberry Pi 4 Model B Rev 1.4 (oci), OK
Initializing RTC Clock: no hardware found
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Running seedrng: OK
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Populating /dev using udev: done
Init onboard LEDs: init, OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 10.112.10.2, OK
Identifying Homematic RF-Hardware: ....HmRF: HM-MOD-RPI-PCB/HB-RF-USB@usb-0000:01:00.0-1.3, HmIP: HM-MOD-RPI-PCB/HB-RF-USB@usb-0000:01:00.0-1.3, OK
Updating Homematic RF-Hardware: HM-MOD-RPI-PCB: 2.8.6, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting sshd: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: ..........ERROR
Starting rfd: ERROR: /dev/mmd_bidcos missing, no BidCos-RF hardware found
Starting HMIPServer: ERROR: /dev/mmd_hmip missing
Starting ReGaHss: ....................ERROR
Starting CloudMatic: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.75.7.20240510 (raspmatic_oci_arm64)
```

oder mit dem original EQ Stick:
```
Identifying host system: Raspberry Pi 4 Model B Rev 1.4 (oci), OK
Initializing RTC Clock: no hardware found
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Running seedrng: OK
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Populating /dev using udev: done
Init onboard LEDs: init, OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 10.112.10.2, OK
Identifying Homematic RF-Hardware: ....HmRF: HM-MOD-RPI-PCB/HB-RF-USB@usb-0000:01:00.0-1.3, HmIP: HM-MOD-RPI-PCB/HB-RF-USB@usb-0000:01:00.0-1.3, OK
Updating Homematic RF-Hardware: HM-MOD-RPI-PCB: 2.8.6, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting sshd: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: ...........ERROR
Starting rfd: ERROR: /dev/mmd_bidcos missing, no BidCos-RF hardware found
Starting HMIPServer: ERROR: /dev/mmd_hmip missing
Starting ReGaHss: ....................ERROR
Starting CloudMatic: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.75.7.20240510 (raspmatic_oci_arm64)
```
Ich habe dann das kernel modul für den usb stick rasugeworfen und neu instalalliert (mit den 1004 kernel headern) weil er ja beim starten vom rfd keine Hardware findet obwohl er vorher schon das modul erkennt - aber wer weiss das schon.
Jetzt sieht es immer noch genauso aus ( das log ist das aktuelle).
Ich habe verschiedene raspberrymatic Versionen ausprobiert ( von vor 2monaten, von vor 3monaten , latest und snapshot ) 
aber immer das gleiche Problem. 

Was mache ich falsch ? Zur grössten not muss ich halt den snaptshot von gestern (root auf zfs) einspielen, aber dann verliere ich halt die Daten von heute ;-(

Ein großes Lob fürs maintainen von RaspberryMatic !

### Describe the behavior you expected

after upgrade to newest ubuntu version it should continue working as in the past

### Steps to reproduce the issue

1. apt-get update 
2.apt-get dist-upgrade
3.no step 3
...

### What is the version this bug report is based on?

3.75.7.20240510

### Which base platform are you running?

rpi4 (RaspberryPi4, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
s.o.
```

**Comment by jens-maus** [comment]
Duplicate of #2733

**Comment by pstestos** [comment]
Ok, ich kenne mich nicht mit linux aus, aber wie schon geschrieben habe ich das kernel modul neu kompiliert und das funktioniert auch denke ich:
```
lsmod |grep raw
generic_raw_uart       45056  1 hb_rf_usb
```
also ist das modul wohl geladen ?

das /dev/raw-uart  ist vorhanden 
und eq3_char_loop 
```
sudo modprobe -vvvvvvvv eq3_char_loop
modprobe: INFO: ../libkmod/libkmod.c:405 kmod_set_log_fn() custom logging function 0xaaaad06f6660 registered
modprobe: DEBUG: ../libkmod/libkmod-index.c:757 index_mm_open() file=/lib/modules/6.8.0-1004-raspi/modules.dep.bin
modprobe: DEBUG: ../libkmod/libkmod-index.c:757 index_mm_open() file=/lib/modules/6.8.0-1004-raspi/modules.alias.bin
modprobe: DEBUG: ../libkmod/libkmod-index.c:757 index_mm_open() file=/lib/modules/6.8.0-1004-raspi/modules.symbols.bin
modprobe: DEBUG: ../libkmod/libkmod-index.c:757 index_mm_open() file=/lib/modules/6.8.0-1004-raspi/modules.builtin.alias.bin
modprobe: DEBUG: ../libkmod/libkmod-index.c:757 index_mm_open() file=/lib/modules/6.8.0-1004-raspi/modules.builtin.bin
modprobe: DEBUG: ../libkmod/libkmod-module.c:579 kmod_module_new_from_lookup() input alias=eq3_char_loop, normalized=eq3_char_loop
modprobe: DEBUG: ../libkmod/libkmod.c:635 kmod_search_moddep() use mmaped index 'modules.dep' modname=eq3_char_loop
modprobe: DEBUG: ../libkmod/libkmod.c:443 kmod_pool_get_module() get module name='eq3_char_loop' found=(nil)
modprobe: DEBUG: ../libkmod/libkmod.c:451 kmod_pool_add_module() add 0xaaab0a9844e0 key='eq3_char_loop'
modprobe: DEBUG: ../libkmod/libkmod-module.c:202 kmod_module_parse_depline() 0 dependencies for eq3_char_loop
modprobe: DEBUG: ../libkmod/libkmod-module.c:584 kmod_module_new_from_lookup() lookup=eq3_char_loop found=1
modprobe: DEBUG: ../libkmod/libkmod.c:540 lookup_builtin_file() use mmaped index 'modules.builtin' modname=eq3_char_loop
modprobe: DEBUG: ../libkmod/libkmod-module.c:469 kmod_module_unref() kmod_module 0xaaab0a9844e0 released
modprobe: DEBUG: ../libkmod/libkmod.c:459 kmod_pool_del_module() del 0xaaab0a9844e0 key='eq3_char_loop'
modprobe: INFO: ../libkmod/libkmod.c:372 kmod_unref() context 0xaaab0a97e5c0 released
```
liefert auch keine fehler - zumindest sieht es genauso aus wie auf einem anderen raspi der funktioniert.

Die ccu sieht auch korrekt welches modul ich angeschlossen habe aber später im bootprozess bei dem 
```
Starting multimacd: ...........ERROR
Starting rfd: ERROR: /dev/mmd_bidcos missing, no BidCos-RF hardware found
Starting HMIPServer: ERROR: /dev/mmd_hmip missing
Starting ReGaHss: ....................ERROR
```
wird es nicht gefunden ? 

oder misinterpretiere ich das alles und das kernel modul ist doch nicht da ?

**Comment by jens-maus** [comment]
Das ist hier kein Diskussionforum, sondern ein Issue/Bugreportsystem und hier handelt es sich definitiv nicht um einen Bug direkt in RM sondern wohl eher in der Installationsumgebung. Für mich sieht das so aus als ob da permissions nicht stimmen. Deshalb bitte einfach Dokumentation und `install-docker.sh` und Foren nutzen um Fehlersuche zu betreiben und nicht ein vermeintlichen Bug hier melden der kein Bug ist. Und wenn selbst zu wenig Expertise im Bereich Linux, Docker usw existiert wäre es wohl angebracht abstand von einer Docker-basierten RaspberryMatic Installation zu nehmen!

**Comment by pstestos** [comment]
Vielen Dank für die schnelle Antwort und überhaupt das supporten den Projekts.

Ich habe mir sehr genau überlegt ob den Bug als Bug aufmache oder ins Diskussionsforum gehe. Besonders weil ich auch zuerst mir genau den refernzierten duplicate bug angesehen hatte und die dort beschriebenen Versuche gemacht habe das Problem zu beheben und das Kernel modul wird ja geladen sonst würde das raw-uart device nicht existieren und am Anfang des Bootprozesses ja nicht das Modul gefunden werden oder ? 
Was ich nicht verstehe ist, dass im Bootprozess zuerst die Hardware gefunden wird, und später dann nicht mehr. Aber da  das kein Bug ist werde ich nun ins Diskussionsforum gehen.

**Comment by schacka** [comment]
Hallo zusammen,
der Fehler ist meiner Meinung nach kein Duplikat.
```
Starting multimacd: ..........ERROR
Starting rfd: ERROR: /dev/mmd_bidcos missing, no BidCos-RF hardware found
```
Er tritt auch bei mir auf. Alles neu installiert. Module laden einwandfrei. Gefühlt hat er was mit Ubuntu, Docker, dem Laden des Moduls in der Dockerumgebung und Berechtigungen (cgroups?) zu tun. Leider bin ich nicht firm genug selber zu helfen. Vielleicht hilft ja zumindest mein Hinweis. Einen entsprechenden Kommentar mit weiteren Details habe ich bei piVCCU hinterlassen.
[piVCCU ](https://github.com/alexreinert/piVCCU/issues/523#issuecomment-2132053772)

Viele Grüße und danke für die wirklich gute Software! Nutze sie seit Jahren.
