### ISSUE TITLE
Shipped Tailscale 1.64.0 has known security vulnerability

### ISSUE THREAD

**Issue by slartibartfass** [jens-maus/RaspberryMatic#2753]
### Describe the issue you are experiencing

Version: 3.75.7.20240420 (rpi3)

This machine is running a version with a known security vulnerability. It’s recommended to update to 1.66.4.

### Describe the behavior you expected

Expect at least v  1.66.4.

### Steps to reproduce the issue

Activate Tailscale VPN

### What is the version this bug report is based on?

3.75.7.20240420

### Which base platform are you running?

rpi3 (RaspberryPi3, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

HM-CFG-LAN

### Anything in the logs that might be useful for us?

```txt
-
```

**Comment by steffenxx** [comment]
Hab das Problem selbst gefunden. Scheinbar fehlt in den Debian Distributionen für den OrangePi 5(b) der QEMU Gast Agent. Dementsprechend war das Problem schnell mit einem 

`apt install qemu-guest-agent` 

und einem Reboot behoben. Läuft jetzt auf "Orangepi5b_1.0.8_debian_bookworm_server_linux6.1.43"
