### ISSUE TITLE
web interface not usable from within ha when port is changed to anything else than 80

### ISSUE THREAD

**Issue by joe16joe16** [jens-maus/RaspberryMatic#2757]
### Describe the issue you are experiencing

in the current version the "open user interface" in the add-ons settings and also the icon in the sidebar not working when the http port is changed in the configuration.
But access is possible if opening <ha-ip>:<otherport>

### Describe the behavior you expected

The ingress integration should use the port configured in the settings and not the default port 80

### Steps to reproduce the issue

1. change the http port to something else. As example 8085
2. restart HA
3. the Sidebar button and the "open user interface" button in the add-on overview do not work anymore

### What is the version this bug report is based on?

3.75.7.20240420

### Which base platform are you running?

rpi5 (RaspberryPi5, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
No logs from raspberry matic because it is a HA integration issue
```

### Additional information

This was working in the past, but I am not sure when it stops.

**Comment by Baxxy13** [comment]
> 1. change the http port to something else. As example 8085

Where? In the AddOn - Configuration? Please show a screenshot.
That is only for external access and has nothing to do with ingress-access.
I can enter your "8085" within 'CCU WebUI HTTP (Extern)' and after AddOn-Restart acces per ingress is working normally like bevore.

**Comment by joe16joe16** [comment]
Yes, in the Add-On confuguration tab, AFAIK the only place to set the web ui port.

When I change the port and restart (even the whole OS) I get the error that raspberry matic is not ready, retry.

In the supervisor log are this line:
2024-05-29 16:25:52.677 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.1:8099 ssl:default [Connect call failed ('172.30.33.1', 8099)]

This are my raspberry-matic settings:
![image](https://github.com/jens-maus/RaspberryMatic/assets/169074579/96ca4766-249c-48d2-ae61-401fd2856712)

**Comment by Baxxy13** [comment]
Da du eine deutsche UI nutzt...
Man sieht ja das der Port aus der Fehlermeldung (8099) anders ist als der eingestellte Port (8085).
Oder passen Fehlermeldung und Screenshot nicht zusammen?

Wie lange hast du denn nach dem AddOn-Neustart gewartet bis du per Ingress drauf zugreifen wolltest?
Wie oben geschrieben, der Port den du da konfigurierst hat nichts mit dem Ingress-Zugriff zu tun.
Was passiert denn wenn du den wieder rausnimmst?

**Comment by joe16joe16** [comment]
Auch wenn ich das http Port auf 8099 stelle Funktioniert es nicht, in der Fehlermeldung des HA Supervisor steht doch SSL und bei meiner Installation (ist schon zwei Jahre alt) ist bei https Port gar nichts eingestellt.

Wenn ich mir in der HA Add On Konfiguration alle Ports anzeigen lasse und bei http wieder 8085 Einstelle und bei https Port 8099 Funktioniert die ingress Integration in HA trotzdem nicht.

Aber ein direchter Aufruf von:
http://<ha ip>:8085
https://<ha ip>:8099 
klappt schon.

Kann es sein das ich noch eine andere Konfiguration aus einer Alten Version nicht in HA Add On oder CCU eingestellt habe die Ingress für die Integration in die HA UI nun braucht?

**Comment by jens-maus** [comment]
Kann es sein das du einfach in dieses alte Problem hier reingerannt bist?

https://github.com/jens-maus/RaspberryMatic/issues/2720

D.h. einfach mal das Addon frisch pullen und dann geht das?

**Comment by Baxxy13** [comment]
Ach, die zurückgezogene fehlerhafte Erstausgabe der 3.75.7.20240420 hatte ich gar nicht mehr auf dem Schirm. Könnte in der Tat hier der Problemverursacher sein.

**Comment by joe16joe16** [comment]
@jens-maus genau das war die Lösung.

- Also in der Raspberry Matic selbst ein Backup der CCU erstellt
- Das Add-On Komplett Deinstalliert
- Erneut Installiert
- Nach dem Start Assistenten in der RaspberryMatic das Backup wiederhergestellt

Vielen Dank auch an @Baxxy13 für seine super schnelle Reaktion!

**Comment by Maik2208** [comment]
> Ach, die zurückgezogene fehlerhafte Erstausgabe der 3.75.7.20240420 hatte ich gar nicht mehr auf dem Schirm.

Mit einer neuen Versionsnummer wäre das auch schneller aufgefallen 😉

**Comment by jens-maus** [comment]
wäre, wäre, Fahrradkette ;-)
