### ISSUE TITLE
WebUI: Doppelte Ein-Aus-Schalter 

### ISSUE THREAD

**Issue by Dodai** [jens-maus/RaspberryMatic#277]
Nach neuem Raspberrymatic-Release: Wenn ich über Webui / Status-Bedienung/Geräte z.B. einen Lichtschalter anwähle ist alles wie früher:
![raspberry-knoepfe-1](https://user-images.githubusercontent.com/36998237/36913188-0cd1114a-1e41-11e8-83d2-43727cb501aa.jpg)
Drücke ich allerdings auf "Ein", so verdopppeln sich die Knöpfe (Anlage); die untere Reihe ist "passiv".
![raspberry-knoepfe-2](https://user-images.githubusercontent.com/36998237/36913198-12f8383c-1e41-11e8-97cc-c5c422ba7f84.jpg)

**Comment by jens-maus** [comment]
Das liest sich für mich nach einem Webbrowser problem bzw. Browser-Cache problem.

**Comment by Dodai** [comment]
Stimmt höchstwahrscheinlich! Vielen Dank übrigens für die tolle Arbeit!!

 

Von: Jens Maus <notifications@github.com> 
Gesendet: Freitag, 2. März 2018 22:01
An: jens-maus/RaspberryMatic <RaspberryMatic@noreply.github.com>
Cc: Dodai <daiser.w@t-online.de>; Author <author@noreply.github.com>
Betreff: Re: [jens-maus/RaspberryMatic] WebUI: Doppelte Ein-Aus-Schalter (#277)

 

Das liest sich für mich nach einem Webbrowser problem bzw. Browser-Cache problem.
