### ISSUE TITLE
Status HmIP-SAM bei Lageerkennung nur 'undefined'

### ISSUE THREAD

**Issue by eli4711** [jens-maus/RaspberryMatic#2783]
### Describe the issue you are experiencing

Der Status des HmIP-SAM zeigt seit der OCCU Version 3.77.X keine Werte mehr an.
![State](https://github.com/jens-maus/RaspberryMatic/assets/40276118/aa2a8043-0fc6-486b-801a-fee0eced68b0)

Alle verknüpften Programme funktionieren aber weiterhin. In der Auswahl im Programm wird auch weiterhin der Status "geneigt" oder "wagrecht" zur Auswahl angeboten.

### Describe the behavior you expected

Früher wurde der Ststus geneigt oder Wagrecht angezeigt.

### Steps to reproduce the issue

1. System auf 3.77.X updaten
2. Status eines HmIP-SAM in der WebUI abfragen
3.
...

### What is the version this bug report is based on?

3.77.4.20240619 (generic-x86_64)

### Which base platform are you running?

generic-x86_64 (Generic UEFI capable system, AMD64/x86_64)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
-
```

**Comment by jens-maus** [comment]
I kann das hier bei meine eigenen Installation reproduzieren. Sobald man den HmIP-SAM auf "Lageerkennung" gestellt hat wird wie im Screenshot zu sehen dort `undefined` angezeigt. Sieht man sich die upstream/eQ3 Änderungen in der 3.77.x an, so sieht man das dort an besagten Routinen Dinge verändert wurden (z.B. https://github.com/eq-3/occu/commit/b6a142049322853a8950938fe8da4c319483f72c#diff-4e196715860c31f103b7a3da1c5c51c985071d28499b698061f9d7e331b80305) die jetzt wohl nicht mehr so ganz zur aktuellen HmIP-SAM Firmware passen. Hier muss eQ3 also nochmal etwas nacharbeiten. Danke für den Report!

**Comment by jens-maus** [comment]
Gibt es diesbzgl. Verbesserungen/Veränderungen mit dem aktuellen nightly (3.77.5.20240626-8e0bb2)?

**Comment by eli4711** [comment]
Issue behoben! :-)
