### ISSUE TITLE
HmIP-HAP update icon missing

### ISSUE THREAD

**Issue by Guenni9** [jens-maus/RaspberryMatic#2785]
### Describe the issue you are experiencing

just cosmetics, if going to device > firmware overview > device firmware, there is the icon for the HmIP-HAP missing

### Describe the behavior you expected

the icon should be viewed, like all other devices

### Steps to reproduce the issue

klicking the buttons:
sorry for german;-)

1. Einstellungen
2. Geräte-Firmware - Übersicht
3. Geräte-Firmware
...

### What is the version this bug report is based on?

3.75.7.20240601

### Which base platform are you running?

rpi3 (RaspberryPi3, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Using web-developer, I see, "src" is empty 

<img id="idHMIP-HAP" src="" alt="HMIP-HAP">
```

### Additional information

![image](https://github.com/jens-maus/RaspberryMatic/assets/101923813/07c3e50e-ae8a-4cce-a205-317444fbad78)

**Comment by Guenni9** [comment]
![image](https://github.com/jens-maus/RaspberryMatic/assets/101923813/56e859cc-f43b-4819-a6c5-8c3ae17e9e06)

maybe because HMIP-HAP <> HmIP-HAP ?

**Comment by Baxxy13** [comment]
Klingt jetzt vielleicht etwas überheblich, aber für sowas lohnt es sich nicht irgendwas anzufassen.
Das HAP-Update lädt man hoch, führt es aus und löscht es dann wieder. Ist ne Sache von maximal 5 Minuten währenddessen man ggf. das nicht vorhandene Bild sieht.

Nebenbei... das Update für den HAP-JS1 nimmt das Bild der CCU3... sieht also "schöner aus" 😉 
`<img id="idHmIP-HAP JS1" src="/config/img/devices/50/CCU3_thumb.png" alt="HmIP-HAP JS1">`

**Comment by Maik2208** [comment]
> Klingt jetzt vielleicht etwas überheblich, aber für sowas lohnt es sich nicht irgendwas anzufassen.
> 
Da gebe ich dir prinzipiell Recht, nur erlebe ich grad wieder selbst im beruflichen Umfeld, dass man sich auf Dauer die Akzeptanz der Anwender verspielt wenn der Eindruck entsteht, dass man sich nicht einmal um so Kleinigkeiten kümmert. Dass auf der anderen Seite große Dinge bewegt werden, wird gern mal übersehen wenn diese  (belanglosen) 2-Minuten-Aufgaben Ewigkeiten dauern oder gar ganz ausgesessen werden.

**Comment by Baxxy13** [comment]
Das kann ich natürlich nicht gutheißen das wir die Akzeptanz wegen so einer Lapalie verspielen.
Bitteschön: 
[HMIP-HAP_3_0_18_230929.tgz.txt](https://github.com/user-attachments/files/15934179/HMIP-HAP_3_0_18_230929.tgz.txt)
(.txt am Ende natürlich entfernen)

Der "Fehler" ist mal wieder eQ-3 zuzuschreiben, die bringen ja gerne ihre Groß/Kleinschreibung durcheinander.
Er steckt in der "info" innerhalb der Firmware-Update-Datei.
Es lag tatsächlich am HMIP-HAP <> HmIP-HAP.

**Comment by Guenni9** [comment]
Super, sorry und vielen, vielen Dank für die Zeit! Sieht nun perfekt aus! Mein innerer Monk ist bedient😂
