### ISSUE TITLE
HmIP-FROLL Bedienung per WebUI nicht möglich

### ISSUE THREAD

**Issue by eli4711** [jens-maus/RaspberryMatic#2786]
### Describe the issue you are experiencing

Die HmIP-FROLL lassen sich nicht mehr über die WebUI bedienen.
Weder mit "Auf - Ab" Buttons, noch über die Eingabe eines Prozentsatzes im Bedienfeld.

Das Problem tritt nur mit der OCCU Version 3.77.X auf.

### Describe the behavior you expected

HmIP-FROLL reagiert auf eingaben in der WebUI.

### Steps to reproduce the issue

1. System auf 3.77.X updaten.
2. Gerät via WebUI bedienen.
3.
...

### What is the version this bug report is based on?

3.77.4.20240619 (generic-x86_64)

### Which base platform are you running?

generic-x86_64 (Generic UEFI capable system, AMD64/x86_64)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
In der Browser Konsole sind keinerlei Fehler. Vermutlich wieder mal ein Upstream Issue.
```

**Comment by Baxxy13** [comment]
Sehr gutes "finding". Du solltest dich bei eQ-3 als "Tester" bewerben. 😉 
Mein BROLL ist auch betroffen, Bedienung über die WebUI unmöglich.
Selbst an der WebUI vorbei (SDV) kann ich z.B. keine 50% mehr einstellen.

**Comment by eli4711** [comment]
Ja, via Tinymatic gehts auch, und Programme laufen auch einwandfrei.

**Comment by jp112sdl** [comment]
https://github.com/eq-3/occu/blob/master/WebUI/www/webui/webui.js#L40347-L40401

Zum Test, mach in Zeile 40348 aus `_saveValue` wieder `saveValue` und in Zeile 40383 aus `saveValue` ein `_saveValue`.

**Comment by Baxxy13** [comment]
Wenn ich die "alte Funktion" wieder aktiviere läuft's mit meinem BROLL.

Was auch immer eQ-3 mit der "neuen Funktion" bezweckt, da müssen sie wohl nochmal ran.

**Comment by eli4711** [comment]
Kann Baxxys Meldung bestätigen. Der FROLL läuft so auch wieder.

**Comment by eli4711** [comment]
Issue behoben! :-)

**Comment by Baxxy13** [comment]
Jap, mein BROLL lässt sich auch wieder über die WebUI "bedienen".
Brauche ich zwar eigentlich nicht... aber wie sagt man so schön... "besser haben als brauchen" 😉
