### ISSUE TITLE
Hallo; Probleme mit HM-IP

### ISSUE THREAD

**Issue by Je023** [jens-maus/RaspberryMatic#279]
Hallo
bin lgs. am verzweifeln; hatte 1/2 Jahr Yahm am laufen; alles gut; 2 Raspberry mit 2 simulierten CCU2s; habe dann den neuen Durchgangszähler auf der einen CCU angelernt; hatte dafür die CCU geupdated auf die neue 2.31.25 FW; der lief dann auch; seitdem geht aber alles schief; kann keine HM-IP Geräte mit Schaltern mehr richtig anlernen;
Dachte es liegt an der neuen FW; alles wieder downgegradet; Probleme blieben; dachte, es liegt an meinen fehlenden Kenntnissen bzgl. Linux etc.; 
bin dann auf RaspMatic umgestiegen; genau nach deiner Anleitung aus dem FHZ-Formu vorgegangen -den Umstieg gemacht; sah alles gut aus; kann den HM-IPWRC2 Schalter anlernen; Test für den Schalter als solches wird auch als korrekt erkannt signalisiert; die bd. Taster 1 und 2 des Schalters werden aber nicht richtig erkannt, bestehen den Test nicht; auch das Löschen des Gerätes sieht anders aus als sonst;: früher bei der YAHM oder originären CCU2 waren da immer mehrer Auswahlen zu sehen (ablernen, Werkszustand, aus Homematic löschen); da sehe ich jetzt immer nur ablernen-Werkszustand; irgendwie muß das ganze an der HP-IP-Konfiguration liegen;
Langsam bin ich am verzweifeln;
Gruß, Jens

**Comment by jens-maus** [comment]
Tut mir leid, das hier ist ein BugTracker und kein Support Forum. Bitte an das homematic-forum (https://homematic-forum.de/forum/viewforum.php?f=65) wenden da 1. dann die mögliche Lösung auch anderen zugute kommt und 2. dort mehr als nur die Entwickler rund um RaspberryMatic mithelfen können.
