### ISSUE TITLE
HmIP-WKP Bedienung per WebUI nicht möglich

### ISSUE THREAD

**Issue by friedpa** [jens-maus/RaspberryMatic#2792]
### Describe the issue you are experiencing

Die HmIP-WKP lassen sich nicht mehr über die WebUI bedienen.
Alle Versuche einen Benutzer zu- oder abzuschalten funktionieren nicht mehr.

### Describe the behavior you expected

HmIP-WKP reagiert auf Eingaben in der WebUI.

### Steps to reproduce the issue

1.  System auf 3.75.X updaten.
2.  Gerät via WebUI bedienen.

### What is the version this bug report is based on?

3.75.7.20240601

### Which base platform are you running?

rpi4 (RaspberryPi4, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
Radio Modul: HB-RF-ETH
```

**Comment by Baxxy13** [comment]
Das heißt jetzt der Problem steckt seit März im System und es hat noch keiner bemerkt? 
(Die erste 3.75.x erschien am 16.03.24)

Oder kannst du das .x etwas präzisieren?

**Comment by friedpa** [comment]
Ich dachte, die SW Version muss man in "What is the Version this Bub report is based on" angeben...

![grafik](https://github.com/jens-maus/RaspberryMatic/assets/42890695/6686b572-22e9-4463-a8d3-2de211723d46)

**Comment by Baxxy13** [comment]
Ja, war soweit richtig.
Mich irritierte dein Schritt 1 in "Steps to reproduce the issue"
Nach dem tritt das Problem mit einer 3.75.x Version auf von denen es inzwischen 3 gibt.

**Comment by Baxxy13** [comment]
Gut, der Fehler trat also mit Installation der 3.75.7.20240601 auf.
Das heißt im Gegenzug das in der vorherigen Version 3.75.7.20240420 noch alles ok war?

Kannst du vielleicht mal nen Screencast o.ä. machen damit man sich mal ein Bild vom Problem machen kann?
