### ISSUE TITLE
Geräteeinstellung HmIP-STHO werden nicht angezeigt

### ISSUE THREAD

**Issue by eli4711** [jens-maus/RaspberryMatic#2793]
### Describe the issue you are experiencing

In der WebUI werden die Einstellungen, in den Geräteeinstellungen nicht mehr angezeigt.
![STHO](https://github.com/jens-maus/RaspberryMatic/assets/40276118/fe76b258-a13b-4052-b121-a349164cc330)

### Describe the behavior you expected

Parameter werden in der Geräteinstellung angezeigt

### Steps to reproduce the issue

1. Geräteeinstellungen eines HmIP-STHO aufrufen.
2.
3.
...

### What is the version this bug report is based on?

3.77.5.20240626 (generic-x86_64)

### Which base platform are you running?

generic-x86_64 (Generic UEFI capable system, AMD64/x86_64)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Im Log keine Auffälligkeiten.
```

### Additional information

Das Problem ist Vermutlich wieder, auf Änderungen in der OCCU 3.77.X zurückzuführen. Also wieder ein upstream issue.

**Comment by Baxxy13** [comment]
Ach ja, kann ich bestätigen.

**Comment by andrzejgilas** [comment]
Ich bestätige auch (rpi5)
![22](https://github.com/jens-maus/RaspberryMatic/assets/81189856/1aa89408-c9c3-4862-b462-ce548bef796f)
![33](https://github.com/jens-maus/RaspberryMatic/assets/81189856/46cb0c60-e009-40b4-9fdb-02407822cf50)

**Comment by jens-maus** [comment]
Irgendetwas in der Browser Konsole oder unter `/usr/local/tmp` auffindbar um rauszubekommen aus welcher neuen richtung das ggf. kommt?

**Comment by andrzejgilas** [comment]
`Return-Path: <CGI script - do not reply>
From:  <CGI script - do not reply>
To: root
Subject:  CGI problem

CGI environment:
REQUEST_METHOD: POST
SCRIPT_NAME: /config/ic_deviceparameters.cgi
HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0
HTTP_HOST: 192.168.1.138
REMOTE_ADDR: 192.168.1.192
cgi.tcl version: 1.10.0
input:
iface=HmIP-RF&address=000EDBE98B950F&redirect_url=GO_BACK
cookie:
errorInfo:
invalid command name "hmip-stho-a"
    while executing
"hmip-stho-a"
    (procedure "getCondTXThresholdUnit" line 4)
    invoked from within
"getCondTXThresholdUnit $devType $chn"
    (procedure "getCondSwitchTransmitter" line 159)
    invoked from within
"getCondSwitchTransmitter $chn ps psDescr"
    (procedure "set_htmlParams" line 13)
    invoked from within
"set_htmlParams $iface $ch_address ch_ps ch_ps_descr CHANNEL_$ch_descr(INDEX) """
    (procedure "put_channel_parameters" line 129)
    invoked from within
"put_channel_parameters"
    (procedure "put_page" line 133)
    invoked from within
"put_page"
`

**Comment by jens-maus** [comment]
@andrzejgilas Danke. Das erklärt das Problem. Mit der 3.77.x wurde diese Änderung in der Datei `/www/config/easymodes/etc/uiElements.tcl` vorgenommen:

```diff
@@ -154,7 +158,10 @@ proc getUnit {param} {
 
 proc getCondTXThresholdUnit {devType chn} {
    switch [string tolower $devType] {
-        hmip-stho  {
+        hmip-stho
+        hmip-stho-a
+        elv-sh-cth
+        {
           if {$chn == "2"} {return "<B0>C"}
           if {$chn == "3"} {return "%"}
         }
```

Allerdings fehlt hier hinter dem `hmip-stho` bzw. `hmip-stho-a` noch ein `-` damit die eigentlich gewollte Änderung (die wohl blind umgesetzt wurde) auch wirklich funktioniert. Das ganze müsste dann wie folgt aussehen:

```tcl
  proc getCondTXThresholdUnit {devType chn} {
     switch [string tolower $devType] {
          hmip-stho -
          hmip-stho-a -
          elv-sh-cth
          {
            if {$chn == "2"} {return "°C"}
            if {$chn == "3"} {return "%"}
          }
          hmip-slo {return "Lux"}
          hmip-scth230 {
            if {$chn == "2" || $chn == "3"} {return "ppm"}
            if {$chn == "5"} {return "°C"}
            if {$chn == "6"} {return "%"}
          }
        default {return ""}
      }
  }
```

Kannst ja mal probieren die Datei zu editieren und die fehlenden `-` hinzuzufügen. Würde mich nicht wundern wenn das das Problem bereits behebt.

**Comment by eli4711** [comment]
Jepp, das wars. Läuft wieder. 🤗

**Comment by jens-maus** [comment]
> Jepp, das wars. Läuft wieder. 🤗

Wunderbar. eQ3 ist auch schon informiert und wird den Fix dann hoffentlich in der 3.77.x noch umsetzen.

**Comment by andrzejgilas** [comment]
> Jepp, das wars. Läuft wieder. 🤗

Entschuldigung für die dumme Frage
Wie soll ich diese Datei bearbeiten?

![44](https://github.com/jens-maus/RaspberryMatic/assets/81189856/3ec08c85-48c5-4c5d-9dd8-73dc6b6ce49d)

**Comment by jens-maus** [comment]
> > Jepp, das wars. Läuft wieder. 🤗
> 
> Entschuldigung für die dumme Frage Wie soll ich diese Datei bearbeiten?

Wenn du das nicht weisst, dann solltest du die in der Tat nicht bearbeiten weil du ansonsten mitunter zuviel kaputt machen kannst. Warte also einfach auf den Fix im offiziellen Release. Aber eins ist klar, mit einer GUI editiert/modifiziert man diese Dateien definitiv nicht :)

**Comment by andrzejgilas** [comment]
@jens-maus 
Ich habe es schon geschafft :-)
Ich bestätige, dass Ihr Fix funktioniert ;-)
![44](https://github.com/jens-maus/RaspberryMatic/assets/81189856/9a6fe1c1-be2b-4118-8e22-ff832a8120bc)

**Comment by MichaelN0815** [comment]
Ich bin immer wieder entsetzt wie bei eq3 gearbeitet wird.

**Comment by jp112sdl** [comment]
> Ich bin immer wieder entsetzt wie bei eq3 gearbeitet wird.

Naja, einerseits ist hat die 3.77.x noch Beta-Status. Es gab schon immer einige Pre-Releases hier im OCCU, bevor die finale Version kam. Die anderen gefundenen und zwischentlich behobenen WebUI-Bugs in der 3.77 waren auch mehr oder weniger Flüchtigkeitsfehler.
Aber es entsteht schon der Eindruck, dass man nur noch versucht, sich irgendwie über Wasser zu halten, bis die HCU endlich draußen ist.

**Comment by Baxxy13** [comment]
eQ-3 hat das im OCCU 3.77.6 (3.77.X Beta 5) "gefixt". 
Hoffen wir mal das nun Ruhe einkehrt. 😉
