### ISSUE TITLE
sshd startet nicht mit Nightly 3.77.6.20240703

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#2796]
### Describe the issue you are experiencing

Mit Nightly 3.77.6.20240703 startet der `sshd` nicht.

### Describe the behavior you expected

Normaler Start vom `sshd`

### Steps to reproduce the issue

1. Nightly 3.77.6.20240703 installieren
2. ssh aktivieren und rebooten
3. Fehlermeldung in /var/log/boot.log oder folgend im syslog ansehen
...

### What is the version this bug report is based on?

3.77.6.20240703 - Nightly

### Which base platform are you running?

lxc_arm64 (Linux Container Infrastructure, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Starting sshd: /usr/libexec/sshd-session does not exist or is not executable
FAIL


Jul  3 16:27:02 rm-lxc-193 user.err monit[1524]: 'sshd' failed to restart (exit status 1) -- '/etc/init.d/S50sshd restart': /usr/libexec/sshd-session does not exist or is not executable^M
```

### Additional information

Neben dem LXC konnte ich das auch auf einem Pi3B sehen.

**Comment by jens-maus** [comment]
Danke für die Info. Scheint wohl damit zusammenzuhängen:

https://lore.kernel.org/buildroot/0731d879-631d-49af-9c42-57ae774471ba@mind.be/T/

**Comment by Baxxy13** [comment]
Kurze Rückmeldung:
Mit dem heutigen Nightly 3.77.6.20240704 startet der `sshd` wieder problemlos.
