### ISSUE TITLE
Not needed to mount /data as Home Assistant add-on

### ISSUE THREAD

**Issue by pvizeli** [jens-maus/RaspberryMatic#2800]
### Describe the solution you'd like

It's not needed anymore to bind mount the `/data` partition to a different location. There is a new format that allow to define the path.

### Describe alternatives you've considered

Well, currently it use the alternative and not the native way

### Is your feature request related to a problem?

Need less permission and using mount inside a container is also not that nice

### Additional information

https://github.com/home-assistant/developers.home-assistant/pull/1974

**Comment by jens-maus** [comment]
latest dev version seems to work nicely with the updated `config.yaml`. Thus, closing issue as solved.
