### ISSUE TITLE
Direkte Verbindung zeigt falschen Wert im Experten Modus an

### ISSUE THREAD

**Issue by HookHM** [jens-maus/RaspberryMatic#2813]
### Describe the issue you are experiencing

Das Problem ist hier beschrieben und reproduzierbar: 

https://homematic-forum.de/forum/viewtopic.php?f=19&t=83012

### Describe the behavior you expected

*

### Steps to reproduce the issue

1.
2.
3.
...

### What is the version this bug report is based on?

3.77.6.20240720

### Which base platform are you running?

ova (Open Virtual Infrastructure, AMD64/x86_64)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
*
```

**Comment by jens-maus** [comment]
Einfach nur einen Link zu einem externen Forum zu posten (welches irgendwann weg sein kann) ist kein adequater Bugreport. Also bitte nochmal machen und dabei hier anhand des templates das Problem usw beschreiben.

**Comment by Maik2208** [comment]
Fixen lässt sich das wohl kaum bzw. nur mit riesigen Aufwand.

Für die Auswahl des angezeigten Profils wird nur geprüft, ob der Wert in einer gewissen Range liegt. Tut er es, wird ein "normales" Profil geladen. Ist jedoch der Wert nicht im
DropDown vorhanden, wird mit 0 vorbelegt.

Einzige Chance wäre, das DropDown um Einerschritte zu ergänzen, so dass dort auch die 14 auswählbar ist.
