### ISSUE TITLE
devconfig.cgi RSSI list is empty

### ISSUE THREAD

**Issue by Jensilein** [jens-maus/RaspberryMatic#282]
Hello, 

I have a PI3 with a HM-MOD-RPI-PCB and newest RaspberryMatic 2.31.25.20180225. 
When I open : "http://192.168.xxx.xxx/tools/devconfig.cgi?cmd=show_rssi&sid=@xxxxxxxx@" and click on RSSI only an empty page appears.

Maybe you can fix it or what else can i do to view the RSSI values?

**Comment by Jensilein** [comment]
Hello, can you please give me an answer how to overcome the issue with the missing RSSI values?

Thank you.

**Comment by jens-maus** [comment]
Sorry, but for me the RSSI values are not missing. Is this still the case?

**Comment by Jensilein** [comment]
Unfortunately yes, the values are not shown, the page is empty.

**Comment by martz170** [comment]
Hello,
i had this issue also some weeks ago - it was a problem with the Brower in combination with Kaspersky.
Actually it works with Firefox 59.0.2 and 2.31.25.20180324 without any Problems.

**Comment by Jensilein** [comment]
Not here. Tried it on Windows as well as on MacOSX. RSSI values are not shown. Maybe it has something to to with the fact that I’m running Homematic IP devices?

**Comment by moclub4** [comment]
Hi,
same issue here. RSSI List is empty. Firefox, Chrome and Safari in newest versions on Mac 10.13.6. All the other views within devconfig are  interpreted without any problems.

**Comment by HMside** [comment]
The RSSI list is displayed with HM-MOD-RPI-PCB and also RPI-RF-MOD. But i use HM-RF and HmIP-RF devices. Perhaps this behavior may only occur in systems where only HmIP-RF device are used.

**Comment by jens-maus** [comment]
This problem should be solved in the 3.41.x firmware line already. Please reopen ticket, if not.
