### ISSUE TITLE
Problem einen RGB Controller anzusprechen

### ISSUE THREAD

**Issue by ruediger218** [jens-maus/RaspberryMatic#2829]
### Describe the issue you are experiencing

wenn ich versuche den status des HMIP-RGBW LED Controller zu verändern funktionieren die kanäle soweit gut. ich kann level und hue ansprechen. allerdings funktioniert bei dem kanal saturation nur das auslesen und nicht das schreiben.
ursprünglich hatte ich das von openhab aus versucht mit genau diesem effekt. 
jetzt habe ich das allerdings direkt mit dem rest interface der raspberrymatic versucht mit genau dem gleichen effekt.
daher scheint hier tatsächlich ein bug vorzuliegen.

### Describe the behavior you expected

auszug aus der statelist
`<datapoint name="HmIP-RF.0033E0C9923FDE:1.HUE" type="HUE" ise_id="4925" value="83" valuetype="16" valueunit="" timestamp="1724508143" operations="7"/>`
`<datapoint name="HmIP-RF.0033E0C9923FDE:1.SATURATION" type="SATURATION" ise_id="4935" value="0.750000" valuetype="4" valueunit="100%" timestamp="1724508143" operations="7"/>`

### Steps to reproduce the issue

schreiben hue (funktioniert)

`https://192.168.0.93/addons/xmlapi/statechange.cgi?ise_id=4925&new_value=10`

schreiben saturation (funktioniert nicht)

`https://192.168.0.93/addons/xmlapi/statechange.cgi?ise_id=4935&new_value=0.25`

im rest interface wird das neue value angezeigt, aber nicht wirklich übernommen

### What is the version this bug report is based on?

3.77.6.20240720

### Which base platform are you running?

rpi3 (RaspberryPi3, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
nichts
```

**Comment by Baxxy13** [comment]
Zunächst mal... es gibt kein "rest interface" auf CCUx/RM. 
Wir haben eine XML-RPC und eine JSON-RPC Schnittstelle.
Das was du nutzt ist quasi ein "Wrapper", das XML-Api AddOn. 

Nichtsdestotrotz ist der Datenpunkt SATURATION in der Device-Doku mit read/write/event angegeben und sollte sich mit Werten von 0.0 - 1.01 beschreiben lassen. 

Hast du mal andere Wege (WebUI-Programm) probiert?

**Comment by ruediger218** [comment]
ah, ok
meinst du mit webui die normale raspberry ui? dort funktioniert es ganz normal - damit habe ich auch kontrolliert daß die werte die ich über den wrapper ändere nicht übernommen werden.
der ausgangspunkt war ja, wie geschrieben openhab. damit läßt sich der datenpunkt auch nicht beschreiben...
was gibt es denn noch für möglichkeiten - wie komme ich z.b. an die json-rpc ?

**Comment by Baxxy13** [comment]
Hmm, versuch's mal direkt auf der Zentrale über "Script testen"

```
var testval = 0.25;
object dp = dom.GetObject('HmIP-RF.0033E0C9923FDE:1.SATURATION');
if (dp) {
 WriteLine("DP Value: "#dp.Value()#" "#dp.ValueUnit());
 dom.GetObject(dp).State(testval);
}
```

Mit testval ein bisschen experimentieren wenn es so nicht geht, also auch mal 25 (statt 0.25) für 25% probieren. 

XML-RPC funktioniert nur mit einem entsprechenden Client, JSON-RPC findet man unter:
 `http: ip_homematic_ccu/api/homematic.cgi` 
JSON-RPC lässt sich ganz gut mit POSTMAN testen, aber das ist schon recht anspruchsvoll.

**Comment by ruediger218** [comment]
erstmal vielen dank für deine hilfe.

egal was ich eingebe, wird nach dem script immer ausgegeben:
DP Value: 0.090000 100%
das ist auch der aktuelle wert (9%) den ich im ui sehe

**Comment by Baxxy13** [comment]
Das heißt also der Wert lässt sich mit dem Script nicht ändern. 
Das ist unschön, war aber zu erwarten da die XML-Api (aus deinen Versuchen) auf die gleiche Methode zugreift.

Was du noch probieren kannst... DevConfig.
Über die erweiterten Systemeinstellungen aktivieren, danach über die Systemsteuerung aufrufen.
In "Channel List" den Kanal suchen, dann sollte unter "Values" der Datenpunkt zu sehen sein. 

Ansonsten mal den Thread im Forum durchackern, vielleicht verstecken sich da Hinweise:
https://homematic-forum.de/forum/viewtopic.php?f=58&t=78404

**Comment by ruediger218** [comment]
devconfig ging tatsächlich ein mal
danach leider statisch nicht mehr

**Comment by Baxxy13** [comment]
Mehr Ideen habe ich leider nicht.
Da ich auch das Gerät nicht besitze kann ich da selbst auch nichts testen.

**Comment by ruediger218** [comment]
ich habe in o.g. thread tatsächlich einen guten hinweis gefunden
es gibt einen combined_parameter string in dem man alle werte auf einmal übergeben kann
der war bisher immer als leerstring zu sehen. deshalb kannte ich den aufbau nicht, aber wenn man ein programm im ui macht sieht man den aufbau. damit hat es funktioniert.

vielen dank

**Comment by ruediger218** [comment]
thread closed
