### ISSUE TITLE
RaspberryMatic-3.77.7.20240826-generic-x86_64 lässt sich auf einem NUC8i3BEH nicht installieren

### ISSUE THREAD

**Issue by shwarzkittel** [jens-maus/RaspberryMatic#2834]
### Describe the issue you are experiencing

Eine Installation von RaspberryMatic-3.77.7.20240826-generic-x86_64 von einem USB-Stick auf einem NUC8i3BEH ist fehlerhaft nicht möglich

### Describe the behavior you expected

Installation RaspberryMatic auf NUC8 bricht ab.

### Steps to reproduce the issue

1. RaspberryMatic-3.77.7.20240826-generic-x86_64 mit Etcher auf einen 16GB-Stick geflasht
2. BIOS vom NUC8 auf UEFI umgestellt
3. Stick wird im UEFI-Bios erkannt und zum Booten ausgewählt
4. Beim Booten vom Stick wird auf den Stick kurz zugegriffen (blaue LED) und am Monitor kommen die 2 Zeilen:
*RaspberryMatic
RaspberryMatic-recovery
5. Nach etwa 2 Sekunden kommt dann am Monitor mit kurzem Stickzugriff:
Booting 'RaspberryMatic'
6. Weiter passiert dann nichts mehr, auch kein Zugriff auf den Stick.
7. Installation nicht möglich.

### What is the version this bug report is based on?

3.77.7.20240826-generic-x86_64

### Which base platform are you running?

generic-x86_64 (Generic UEFI capable system, AMD64/x86_64)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
See 'Steps to reproduce the issue'
```

**Comment by gmhome001** [comment]
Habe genau die gleichen Probleme. IntelNuc 8i3BEK2 als auch 7i3BNK getestet. Image mit Raspberry Pi Imager geflashed, aber ansonsten völlig identisches Ergebnis.
Auf dem NUC7i3BNK lief 3.75.7.20240601 einwandfrei. Nach Umstellung auf UEFI ist keine Installation mehr möglich.

**Comment by shwarzkittel** [comment]
Der Jens Maus wird es reparieren, möglicherweise ist er in Urlaub. Er bekommt eine Spende von mir wenn der Fehler beseitigt ist.

**Comment by jens-maus** [comment]
So, sollte mit dem nächsten nightly snapshot wieder funktionieren bzw. RaspberryMatic via UEFI Boot mit neueren NUC Systemen korrekt hochfahren.

**Comment by shwarzkittel** [comment]
Ja, prima, hat funktioniert, eine Spende ist umterwegs.

**Comment by gmhome001** [comment]
Eben gerade installiert und hat alles perfekt funktioniert. Spende ging eben raus. BTW - habe durch dieses Problem die Vorzüge von Promox kennengelernt und werde wohl erstmal dabei bleiben. Die pure NUC Installation bleibt als Backup.

Vielen Dank nochmal für die schnelle Hilfe!
