### ISSUE TITLE
Raspberry does not start with RedMatic version 7.1.3.

### ISSUE THREAD

**Issue by HolgerFoe** [jens-maus/RaspberryMatic#2838]
### Describe the issue you are experiencing

I have version 3.75.6.20240316 installed and run RedMatic 7.1.3. All newer versions of RaspberryMatic reset with RedMatic 7.1.3. after first start and will never return. Only a recover to old version brings back the system.

### Describe the behavior you expected

Latest version should be compatible with RedMatic 7.1.3

### Steps to reproduce the issue

1. System Running 3.75.6.20240316 and RedMatic 7.1.3.
2. update latest version
3.one start possible but system resets and does not boot again.
4.
...

### What is the version this bug report is based on?

3.77.7.20240826

### Which base platform are you running?

rpi3 (RaspberryPi3, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
.
```

**Comment by jens-maus** [comment]
Sorry, but it should be the other way around: RedMatic should be compatible with RaspberryMatic and not the other way around.

However, there are reports that the latest RaspberryMatic works nicely with RedMatic. See here:

https://homematic-forum.de/forum/viewtopic.php?t=83200&view=unread#p812585

**Comment by Baxxy13** [comment]
Maybe updating RedMatic could help...
https://homematic-forum.de/forum/viewtopic.php?f=77&t=81303
