### ISSUE TITLE
rega.conf Setting for time.conf

### ISSUE THREAD

**Issue by tkoroscha** [jens-maus/RaspberryMatic#284]
Hello,

since a period of time I have some log entries showing time out of sync.
After some investigation  I have seen, that the TimeConfigFileName used by rega service does not exist.
I don´t know if it is intended or not, or if time is set somewhere else?!:

```
# rega.conf

# TimeConfigFileName
# Enthält Zeit- und Positionseinstellungen.
# Standard: /etc/config/time.conf
TimeConfigFileName=/etc/config/time.conf
```

can someone confirm if that is correct or not, or if the TimeConfigFile needs to be existing at definite path, if yes, how is the File formated and syntaxed?

Greets Thorsten

**Comment by jens-maus** [comment]
AFAIR this is intended. Please show the out of sync messages you are getting so that I can tell you what this is all about.

And please consider to continue the discussion on the homematic forum. This is no support fora but a bug tracker

**Comment by jens-maus** [comment]
After some investigation, the time.conf is not required to exist. There are internal fallback values that we will be used in that case. Thus, this cannot be related to your issues.
