### ISSUE TITLE
WebUI hängt nach Anmeldung einige Sekunden

### ISSUE THREAD

**Issue by KoMa1978** [jens-maus/RaspberryMatic#2842]
### Describe the issue you are experiencing

Hallo zusammen,

seit ein paar Versionen habe ich das Phänomen, das nach der Authentifizierung der WebUI für ca 20-30s "hängt".

Danach ist alles gut und auch wenn ich auf die Startseite klicke, ist alles gut. Man kann es sehr gut testen, indem man mit der Maus auf die Schaltflächen oben fährt, ist alles OK, klappen die Drop Downs auf. Hängt die WebUI, klappen sie nicht auf.

Wenn ich im Browser ein Refresh mache, passiert das ganze ebenfalls, das System hängt.

Was kann ich hier tun, um das zu vermeiden, bzw. was kann ich an Debugs/Tests liefern, um das Phänomen zu beseitigen?

### Describe the behavior you expected

System sollte nicht hängen.

### Steps to reproduce the issue

Login in die WebUI oder Refresh im Browser

### What is the version this bug report is based on?

3.77.6.20240720

### Which base platform are you running?

rpi3 (RaspberryPi3, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
In /var/log/lighttpd-access.log sind sehr viele POST Zugriffe auf /api/homematic.cgi zu sehen:

[10/Sep/2024:16:45:28 +0200] "POST /api/homematic.cgi HTTP/2.0" 200 59 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
[10/Sep/2024:16:45:28 +0200] "POST /api/homematic.cgi HTTP/2.0" 200 46 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
[10/Sep/2024:16:45:29 +0200] "POST /api/homematic.cgi HTTP/2.0" 200 59 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
[10/Sep/2024:16:45:29 +0200] "POST /api/homematic.cgi HTTP/2.0" 200 46 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
[10/Sep/2024:16:45:29 +0200] "POST /api/homematic.cgi HTTP/2.0" 200 59 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
[10/Sep/2024:16:45:29 +0200] "POST /api/homematic.cgi HTTP/2.0" 200 46 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
[10/Sep/2024:16:45:29 +0200] "POST /api/homematic.cgi HTTP/2.0" 200 59 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
[10/Sep/2024:16:45:30 +0200] "POST /api/homematic.cgi HTTP/2.0" 200 2364 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
[10/Sep/2024:16:45:30 +0200] "POST /esp/system.htm?sid=@6mgbXmm7TH@&action=UpdateUI HTTP/2.0" 200 867 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
[10/Sep/2024:16:45:30 +0200] "POST /api/homematic.cgi HTTP/2.0" 200 45 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
[10/Sep/2024:16:45:30 +0200] "POST /api/homematic.cgi HTTP/2.0" 200 2733 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
```

### Additional information

Ähnliches wie aus den Logs oben sehe ich auch in den Developer Tools von Chrome. Viele Zugriffe auf /api/homematic.cgi mit wenig Datenübertragung:
![image](https://github.com/user-attachments/assets/1e6c0e84-31d1-4340-bbc4-ccf5824fef47)

Irgendwann "fängt" er sich wieder und es werden mehr Daten übertragen und die WebUI kann wieder genutzt werden:
![image](https://github.com/user-attachments/assets/5fa5ad63-82a9-4855-a72f-e94f2d568ea7)

Der erste Payload scheint ein "Event.poll" zu sein, dann kommt ein "Interface.ListDevices" und "BidCoS_RF.getConfigurationRF" und jetzt hängt er während immer im Wechsel ein "Interface.getMasterValue" und "Interface.setMetadata" für diverse Objekte kommt. Am Schluß kommt ein "Room.getAll" und die WebUI reagiert wieder:
![image](https://github.com/user-attachments/assets/8bc11d13-2a48-4704-9b79-95847d6c1ecc)

**Comment by Baxxy13** [comment]
Das Thema ist ja schon eine Weile im Forum präsent, Ursache aber bisher unklar.
[WebUI hängt nach Anmeldung ein paar Sekunden](https://homematic-forum.de/forum/viewtopic.php?f=26&t=82965)
Zumindest trifft es original CCU3 und RM wohl gleichermaßen.

Ich selbst sehe das hier auf keinem meiner Testsysteme, das "schwächste" ist ein Pi3B+.

Leg doch mal einen neuen User an und log dich mit dem ein. Der hat ja erstmal keine SysVars oder Favoriten so das man ggf. das Problem eingrenzen kann.

**Comment by jens-maus** [comment]
> Das Thema ist ja schon eine Weile im Forum präsent, Ursache aber bisher unklar. [WebUI hängt nach Anmeldung ein paar Sekunden](https://homematic-forum.de/forum/viewtopic.php?f=26&t=82965) Zumindest trifft es original CCU3 und RM wohl gleichermaßen.
> 
> Ich selbst sehe das hier auf keinem meiner Testsysteme, das "schwächste" ist ein Pi3B+.

Ich selbst sehe das hier auch auf meinem eigenen produktiven System. Dort loggt man sich ein und dann dauert es einige Sekunden (definitiv keine 20-30s) bis man mit der Maus die Menüstruktur oder ähnliches auswählen und somit "weitermachen" kann. Erste eigene Analysen haben nichts auffälliges gezeigt. Und da die CCU3 selbst auch betroffen ist kann es gut sein das es einfach am `HMIPServer` bzw. an der Abfrage des selbigen liegt. Beim initialen einloggen werden ja alle Geräte, usw. abgefragt und das kann natürlich mitunter dauern. Eine Lösung hab ich nicht wirklich parat und leider auch aktuell keinen Ansatz das ordentlich zu debuggen und kann nur sagen das es wohl auch mit der Gesamtanzahl der Geräte/Kanäle zusammenhängt.

**Comment by KoMa1978** [comment]
@jens-maus
OK, die 20-30s sind gefühlt gewesen ;-) Ich hab eben mal gestoppt und es sind so ca. 12-15s ;-)
Bei mir tritt es auch beim Browser Refresh auf, es ist also nicht nur nach dem ersten Login.

Und ja, es ist zum Glück nur nervig, ich habe noch keine wirkliche Einschränkung gesehen.

**Comment by Baxxy13** [comment]
Hmm, die Geräteanzahl könnte eine Rolle spielen. 
Da kann ich schlecht mitreden weil alle meine Testsystem eher klein sind. 
Aber selbst das Hauptsystem mit 40 Geräten (38 IP / 2 HM) zeigt das Phänomen nicht.

Wenn ich das Einloggen auf dem Pi3B+ mit dem Firefox-Profiler mitschneide sehe ich teils Zeiten von max. 3,5s, also nichts außergewähnliches.

**Comment by grmpf72** [comment]
Ich habe dasselbe Problem (entspricht exakt der obigen Beschreibung) - allerdings nicht auf RM sondern auf HM Original und CCU3. Installation ist recht umfangreich mit HMIPW und HMIP.
Siehe auch hier: [https://homematic-forum.de/forum/viewtopic.php?f=26&t=82965](url)

**Comment by grmpf72** [comment]
Ich habe gerade eben auf meinem eigenen System die RM (auf PI3B+ mit RFUSB) 3.77.7 vom 26.8. eingespielt - und schwupp: Jetzt ist die Wartezeit auch dort angekommen!

**Comment by jens-maus** [comment]
> Ich habe gerade eben auf meinem eigenen System die RM (auf PI3B+ mit RFUSB) 3.77.7 vom 26.8. eingespielt - und schwupp: Jetzt ist die Wartezeit auch dort angekommen!

Und von welcher Version kamst du wo das nicht aufgetreten ist? Diese wichtige Info fehlt.

**Comment by grmpf72** [comment]
Vorher (ohne Wartezeit): 3.75.7.20240601

**Comment by KoMa1978** [comment]
Das deckt sich ja auch mit meiner Erfahrung, dass es "seit ein paar Releases" auftritt und nicht erst seit dem letzten Release.

**Comment by jens-maus** [comment]
Im Umkehrschluss bedeutet das aber – da es ja auch unter einer CCU3 auftritt – das es nicht nur hochwahrscheinlich am closed-source`HMIPServer` liegt, sondern das von RaspberryMatic-Seite aus wir daran dann nichts ändern können.

**Comment by grmpf72** [comment]
So sehe ich es auch. Aber was kann unsereins schon bei elv ausrichten?! Da kommen doch eh immer dieselben, stereotypen Antworten! Hilfe ist da kaum zu erwarten.
Noch mal ein paar Details:
- Ich habe im System vorher länger nix gemacht
- Der Update erfolgte über eine neue SDcard weil die alte laut Ansage im Update-Prozess recht langsam war
- Nach dem Update, beim ersten Anmelden stand die "Sanduhr" für ca. 10-15 Seiten auf der ansonsten leeren WebUI!
- Danach wie oben geschildert...

**Comment by KoMa1978** [comment]
Dazu kommt, dass vermutlich nur ein Service Request von jemandem eröffnet werden kann, der das Problem auch mit einer CCU3 und originaler FW hat.

**Comment by grmpf72** [comment]
Ab 3.75.7 oder 3.77.6 - da bin ich mir relativ sicher

**Comment by Baxxy13** [comment]
> Steht alles im Forum! Link oben.

Ja ich kenn den Thread, habe ihn ja selber verlinkt. (dein Link geht nicht)
Man sieht die `homematic.cgi` - Aufrufe, aber leider nicht was da wirklich dahinter steckt.
Speziell der Aufruf (die Methode) mit der Schildkröte wäre interessant. 

> Wie war die Antwort?? ;-)

`{"version": "1.1","result": false,"error": null}`
😎

**Comment by grmpf72** [comment]
Wenn ihr mir etwas detailierter sagt, was genau ich tun soll, dann probier ich das auch.
Aber ich kann nur ANSI 74 COBOL und folgende oder IBM Assembler/370...

**Comment by Baxxy13** [comment]
Im Grunde genommen muss man erstmal die gesamte Verarbeitungszeit aller Aktionen beim Einloggen in einem A/B Vergleich untersuchen. 

Also die letzte "gute Version" flashen und analysieren, danach die erste "schlechte Version".
Mal als Beispiel:
![GIF 11 09 2024 18-26-08](https://github.com/user-attachments/assets/4eca2344-0dd7-4b22-810c-29be3f5e789c)

**Comment by Baxxy13** [comment]
Firefox dröselt die Aufrufe leider nicht so detailliert auf wie die Dev-Console von "Chromium-based-Browsern", siehst du ja selber.
Man sieht nicht welche Methode da so lange braucht.

Und ohne A/B Vergleich kommt man eh nicht weiter.
Wenn sich also niemand findet der das akribisch analysiert um das Problem festzunageln (oder ihr schafft es eQ-3 einzuspannen) dann wird man sich wohl damit abfinden müssen.

**Comment by jens-maus** [comment]
Ich hab nun einmal selbst nochmal danach geschaut und auch die Chrome Developer Umgebung mal aktiviert und Profiling betrieben. Probiert mal bitte die folgenden Zeilen in der `/www/webui/webui.js` auszukommentieren. Bei mir bringt das eine merkliche Beschleunigung des ganzen:

https://github.com/eq-3/occu/blob/c7b28663068518996ebeebfd9c60c8edad66e5f3/WebUI/www/webui/webui.js#L10310-L10315

Meiner Erinnerung nach sind das auch Sachen die in der Tat erst in den letzten Versionen einzug gehalten haben und das langsame Reagieren nach dem Login erklären könnte. Wenn das bei euch auch ohne diese Zeilen besser klappt müsste man mal schauen wie man das beschleunigt bekommt bzw. was da der root-cause ist.

**Comment by jens-maus** [comment]
Ok, noch mehr neue Erkenntnisse nachdem ich die besagte Stelle in der `webui.js` mit der aktuellsten Version (3.79.1) im OCCU verglichen habe. Dort ist die folgende Änderung gegenüber der 3.77.7 vorgenommen worden:

<img width="1302" alt="Bildschirmfoto 2024-09-11 um 21 40 37" src="https://github.com/user-attachments/assets/c4f76a90-62fb-4952-9b4d-81622a879cd7">

Diese Änderung habe ich gerade mal kurzerhand auf meine produktive 3.77.7 angewendet und was soll ich sagen? Nun ist der Loginprozess genauso flott wie wenn dieser ganze Bereich auskommentiert ist.

Daher mal die bitte hier in die Runde bitte die besagten Zeilen in der `webui.js` auch gegen die aus der `webui.js` aus der Betaversion der 3.79.1 zu ersetzen (oder aber kurzerhand auf das aktuelle 3.79.1 nightly build zu updaten) um zu schauen ob damit dann wieder alles schnell ist. Wenn ja, war wohl eQ3 hier bereits tätig und hat das Problem bereits selbst erkannt und beseitigt.

**Comment by grmpf72** [comment]
Wäre es eine Möglichkeit die Test-webui.js hier zum Download einzustellen? Ich komm gerade nicht damit klar, was ich wo austauschen soll. Die Zeilen 10292ff sehen bei meiner webui ganz anders aus (notepad++)

**Comment by jens-maus** [comment]
> Wäre es eine Möglichkeit die Test-webui.js hier zum Download einzustellen? Ich komm gerade nicht damit klar, was ich wo austauschen soll. Die Zeilen 10292ff sehen bei meiner webui ganz anders aus (notepad++)

Installier dir doch einfach den aktuellsten 3.79.1 nightly snapshot und teste damit (siehe https://github.com/jens-maus/RaspberryMatic/releases/snapshots)

**Comment by grmpf72** [comment]
Naja - ich wollte die webui.js im Live-System ersetzen weil ich ja nur da den Hänger habe...
Im Testsystem würde ich es nicht merken!

**Comment by jens-maus** [comment]
Na du sollst ja auch im Live-System das Update zur 3.79.1 nightly machen und damit testen... Soviel Mut muss sein! ;-)

**Comment by grmpf72** [comment]
Niemals!!!! In 12 Jahren HM habe ich schon soviel Sch... erlebt dass ich mir das nicht antue!

**Comment by jens-maus** [comment]
> Niemals!!!! In 12 Jahren HM habe ich schon soviel Sch... erlebt dass ich mir das nicht antue!

Dann musst du zwangsläufig warten bis 3.79.1 draussen ist oder dich fortbilden wie man die webui.js entsprechend direkt unter RaspberryMatic patcht und keinen download auf windows und wieder upload auf RM macht und damit potentiell mehr kaputt macht als man gewinnen will.... Wer nicht wagt, der nicht gewinnt...

**Comment by Baxxy13** [comment]
Man kann sich bei einem laufenden System nicht an den Zeilennummern aus der OCCU orientieren weil sich die durch die ganzen RM-Patches verschieben.

Einfach den Abschnitt suchen und dann ersetzen.

**Comment by KoMa1978** [comment]
Ich bin schon mal happy, dass das Problem (vermutlich) gefunden und schon beseitigt ist. Was das patchen angeht, ja ist ein wenig aufwändiger, auch mit dem RO Dateisystem, ich warte und teste, sobald das Release raus ist.

**Comment by grmpf72** [comment]
Ich bin geduldig und warte dann mal auf die offizielle 3.79.x! Danke an alle "Macher"!

**Comment by jens-maus** [comment]
So, nachdem ich die 3.79.x nightly snapshots nun selbst mal mit meiner produktiven Umgebung testen konnte, kann ich bestätigen das damit das hier geschilderte Problem wohl von eQ3 selbst beseitigt wurde und das hängen der WebUI beim Anmelden nicht mehr auftritt. Ergo kann hier zugemacht werden.

**Comment by timoHGA** [comment]
Hallo in die Runde, ich habe das Problem nur bei der Anmeldung als Admin. Die Seite wird nur teilweise geladen und dann steht sie fest und es ist keine weitere Aktion mehr möglich. Mein Rasp läuft weiter, alle Programme und Funktion bleiben aktiv und kein Störung im Betrieb. Eine Anmeldung als "normaler" Benutzer über Web ist möglich und dort sind alle Funktion und Favoriten zugänglich und einstellbar.

![Image](https://github.com/user-attachments/assets/d64c111d-5241-495e-9f69-343bd319154b)
![Image](https://github.com/user-attachments/assets/313583b7-6d22-4204-b43f-b044b36e6bca)

**Comment by jens-maus** [comment]
Tut mir leid, aber das ist kein Diskussionsforum hier, sondern ein Bug-/Issue-Tracker. Und das Problem an das du dich hier vermeintlich ranhängst ist abgeschlossen. Wenn es ein neue/anderes Problem gibt ein neues Ticket/Issue aufmachen und ggf. dieses hier referenzieren wäre der richtige Weg (wenn es denn ein allgemeines Problem ist und nicht nur ein Problem in deiner Installation).
