### ISSUE TITLE
Jalousieaktoren HM-IP BBL können in Programmen nicht mehr richtig angesprochen werden (Kanalaktion nur noch Behanghöhe möglich)

### ISSUE THREAD

**Issue by petemaster1978** [jens-maus/RaspberryMatic#2851]
### Describe the issue you are experiencing

Jalousieaktoren HM-IP BBL können in Programmen nicht mehr richtig angesprochen werden (Kanalaktion nur noch Behanghöhe möglich). 
<img width="1192" alt="Bildschirmfoto 2024-09-15 um 10 19 54" src="https://github.com/user-attachments/assets/4231e2ff-7c13-4208-9a63-6d83c6f80a2b">

### Describe the behavior you expected

Im alten Auswahldialogfeld konnten Lamellenneigung und Behanghöhe eingestellt werden. 

### Steps to reproduce the issue

1. ist 100% reproduzierbar
2.
3.
...

### What is the version this bug report is based on?

3.77.7.20240826

### Which base platform are you running?

rpi3 (RaspberryPi3, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
weiß nicht wie das geht
```

**Comment by jens-maus** [comment]
Mehr Infos bitte. Was geht konkret nicht mehr, was ging vorher (mit welcher Vorversion?) usw. Und einfach nur "Ist 100% reproduzierbar" reinzuschreiben ist nicht die feine englische Art. 

Bitte mehr bereit sein eigene Zeit in einen ordentlichen Bugreport zu stecken wenn man Hilfe erwartet. Das ganze bitte mit mehr Screenshots hinterfüttern und Beispiele vor/nachher zeigen damit man der Problembeschreibung besser gedanklich folgen kann.

**Comment by Baxxy13** [comment]
Ja, die Info's sind äußerst mager.
Meine Glaskugel sagt der BBL ist im Modus "Rolllade" und nicht wie benötigt im Modus "Jalousie".

Das sollte mal in den Geräteeinstellungen geprüft werde.

**Comment by petemaster1978** [comment]
Hallo Jens, hallo Baxxy13,

das Verhalten tritt erst seit ca. Juni Update auf, leider kann ich es nicht genau sagen.
An den Geräteeinstellungen Habich selber nicht verändert. Baxxy hat aber recht, alle Jalousienaktoren sind nun in den Gerätereinstellungen auf Rolladen-Modus umgestellt. 
Ich wollte es nun zurückstellen dazu müsste ich aber die interne Verknüpfung des Tasters löschen, da habe ich Angst etwas kaputt zu machen.

Gibt es eine Alternative die Autoren wieder auf Jalousienmodus zu bekommen. Es sind aktuell alle 14 Aktoren auf Rolladenmodus umgestellt. Ich kann wirklich ausschließen, dass ich das manuell gemacht habe. Alte Programme, die Jalousienkanalfunktionen hinterlegt haben, funktionieren auch noch (die Aktoren verhalten sich wie Jalousien). Nur neue Programme kann ich nur noch als Rolladen konfigurieren.

Besten dank für eure Hilfe 
Peter




<img width="1284" alt="Bildschirmfoto 2024-09-15 um 14 09 36" src="https://github.com/user-attachments/assets/00b3ca35-7829-40e5-8aa0-42bc77c4a9d0">

**Comment by Baxxy13** [comment]
Ja, diese Phänomen hat im Homematic-Forum auch schon Wellen geschlagen. 
Ich weiß aber nicht ob es durch ein Gerätefirmware-Update oder Zentralen-Update in Erscheinung trat.

Um das sauber umzustellen musst du wohl den steinigen Weg nehmen.
Also erstmal die DV's zu den Tasten löschen, dann gucken ob der Modus umstellbar ist. Wenn nicht dann die Geräte auch aus den Programmen entfernen. 
Jetzt den Modus umstellen und alles wieder "zurückbauen". 

Keine Frage, das ist extrem unschön. Beschwerden darüber an eQ-3 richten und nicht erwähnen das du RaspberryMatic einsetzt.

Es gäbe sicher alternative Wege, das wäre mir aber zu unsicher weil man nicht sicher sein kann das dann alles so gestellt ist wie es sein soll.

Viel Erfolg.
