### ISSUE TITLE
HM-LC-RGBW-WM Dimmer funktioniert seit Version 2.31.25.20180225 nicht mehr

### ISSUE THREAD

**Issue by merlincu2n8** [jens-maus/RaspberryMatic#286]
Hallo zusammen, 
der oben angegebene RGB-W Dimmer "produziert" nur noch Geräte-Kommunikationsfehler seit dem Update.
Ablernen; Werksreste bereits durchgeführt; ein erneutes Anlernen ist dann nicht mehr möglich; Gerät wird nicht im Posteingang gefunden. 
Mit der letzte Version: 2.31.25.20180120 arbeitet er problemlos.

Mit freundlichen Grüßen

Thomas

**Comment by HMside** [comment]
Kann ich mit zwei RGBW-Dimmern hier nicht nachvollziehen. Habe kein Kommunikationsfehler und auch das ab- und anlernen ist kein Problem. Hast mal den Browser Cache geleert? Was genau ist mit Kommunikationsfehlern gemeint bzw. wie steuerst Du das Gerät an?

**Comment by jp112sdl** [comment]
Bei mir auch keinerlei Probleme feststellbar

**Comment by jens-maus** [comment]
Dann reichen mir die beiden Aussagen und Bestätigungen um das Ticket hier zu schliessen. Bei weiteren Problemen bitte an das HomeMatic Forum wenden.

**Comment by merlincu2n8** [comment]
Problem gefunden: Nähe zwischen RGB-Aktor und Raspberry war zu nah.. **schäm**
