### ISSUE TITLE
Firmware Verfügbarkeit als Service Meldung

### ISSUE THREAD

**Issue by kaimimue** [jens-maus/RaspberryMatic#2860]
### Describe the solution you'd like

Es ist möglich über HomeAssistant die Geräte upzudaten, Dazu muss ich die Firmware vorher auf die CCU/RaspberryMatic hochladen. Dies funktioniert auch soweit. Allerdings gibt es keine Möglichkeit über dir Verfügbarkeit von neuen Versionen in Homeassistant informiert zu werden.
Eine einfache Möglichkeit dies zu beheben wäre, die Verfügbarkeit von neuen Gerätefirmware / RaspberryMatic-Version auch als Service Meldung anzuzeigen.
![image](https://github.com/user-attachments/assets/fa39ca30-4b0c-4f62-8775-0796665211f0)

### Describe alternatives you've considered

-

### Is your feature request related to a problem?

-

**Comment by h3ndrik** [comment]
Bei mir wird das im Home Assistant angezeigt sobald ein verfügbares Update vorliegt. Ganz oben in "Einstellungen" wo auch die anderen Updates auftauchen. Ich benutze das RaspberryMatic CCU Addon, die Homematic (IP) Local Integration (custom_homematic) 1.67 und Home Assistant in der Version 2024.10

**Comment by jens-maus** [comment]
Ich denke auch das das bereits in der Homematic (IP) Local Integration so der Fall ist und umgesetzt wurde vor einigen Versionen. Es geht hier aber ohnehin hier nicht wirklich her, sondern wäre ein feature/enhancement request für diese HA Integration die nicht teil des RaspberyMatic projektes ist. Daher mache ich hier zu.
