### ISSUE TITLE
CSS does not load

### ISSUE THREAD

**Issue by bumbummen99** [jens-maus/RaspberryMatic#2867]
### Describe the issue you are experiencing

I have updated my Raspberrymatic docker container, now the stylesheet is not longer working. 
When i navigate to `/webui/style.cgi` i do see the "redirection" page but nothing does happen.
Resetting `ccu_data` volume does not do anything at all.
When i revert to `3.65.11.20221005` it does work as intended.

### Describe the behavior you expected

I would have expected it to just work.

### Steps to reproduce the issue

1. Update Raspberrymatic container via docker pull
2. Start the container
3. Open the WebUI
4. `Refused to apply style from 'http://homematic.lan/webui/style.cgi' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

### What is the version this bug report is based on?

3.77.7.20240826

### Which base platform are you running?

oci_amd64 (Open Container Infrastructure, AMD64/x86_64)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
ccu  | Identifying host system: Dell Inc. 0XCR8D (oci), OK
ccu  | Initializing RTC Clock: onboard, OK
ccu  | Running sysctl: OK
ccu  | Checking for Factory Reset: not required
ccu  | Checking for Backup Restore: not required
ccu  | Running seedrng: OK
ccu  | Initializing System: OK
ccu  | Setup ca-certificates: OK
ccu  | Starting logging: OK
ccu  | Populating /dev using udev: done
ccu  | Init onboard LEDs: init, OK
ccu  | Starting iptables: OK
ccu  | Starting network: eth0: link up, fixed, firewall, inet up, 172.2.0.2, OK
ccu  | Identifying Homematic RF-Hardware: ....HmRF: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-0000:00:14.0-5, HmIP: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-0000:00:14.0-5, OK
ccu  | Updating Homematic RF-Hardware: HMIP-RFUSB: 4.4.18, not necessary, OK
ccu  | Starting hs485dLoader: disabled
ccu  | Starting xinetd: OK
ccu  | Starting eq3configd: OK
ccu  | Starting lighttpd: OK
ccu  | Starting ser2net: disabled
ccu  | Starting ssdpd: OK
ccu  | Starting NUT services: disabled
ccu  | Initializing Third-Party Addons: OK
ccu  | Starting LGWFirmwareUpdate: ...OK
ccu  | Setting LAN Gateway keys: OK
ccu  | Starting hs485d: disabled
ccu  | Starting multimacd: ...OK
ccu  | Starting rfd: .OK
ccu  | Starting HMIPServer: ........OK
ccu  | Starting ReGaHss: .OK
ccu  | Starting CloudMatic: OK
ccu  | Starting NeoServer: disabled
ccu  | Starting Third-Party Addons: OK
ccu  | Starting crond: OK
ccu  | Setup onboard LEDs: booted, OK
ccu  | Finished Boot: 3.77.7.20240826 (raspmatic_oci_amd64)
```

**Comment by jens-maus** [comment]
Please check if `/bin/tclsh` exists within the container as these kind of error appear if style.cgi cannot be executed.

**Comment by jens-maus** [comment]
Sorry, but I just tested this myself and I cannot reproduce it here. Here the official 3.77.7.20230826 container works as expected and shows a working WebUI with a perfect CSS loading. Also `tclsh` exists in the container, etc. See:

```
docker exec -it ccu /bin/sh
/ # ls -la /bin/tclsh
lrwxrwxrwx    1 root     root            14 Aug 26 10:43 /bin/tclsh -> /usr/bin/tclsh
/ # tclsh
%
```

**Comment by bumbummen99** [comment]
> Please check if `/bin/tclsh` exists within the container as these kind of error appear if style.cgi cannot be executed. So please also try to execute `/bin/tclsh` to see if it works correctly in case it exists.

It does exist and i can execute the .cgi manually with the expected missing variable errors. But whenever i try to load the WebUI i do get missing stylesheets or just a lot of 500 errors in the console. Right now i have no clue how to reproduce it.

**Comment by bumbummen99** [comment]
Did not come behind what did cause the issue but the same image does work when starting completely fresh and importing the last daily backup.

**Comment by schmidt-gp** [comment]
I have the same problem. 
After updating to the "latest" image, the WebUI no longer works. 
The login page loads without CSS and HTTP 500 errors are visible in the network traffic.
style.cgi can be called manually. Here will an 500 error when calling /ise/checkrega.cgi.

Details:
ghcr.io/jens-maus/raspberrymatic:latest@sha256:aab3c23579294dba83738b02f695e148bc7524d7b2deae4c4fcfe8f0cd318179
org.opencontainers.image.revision	351344c97f4398739d2d431a2af109bea3a3292d
org.opencontainers.image.version	3.65.6.20220723

Screens calling login.html and style.cgi
![RaspberryMatic WebUI-login html-error](https://github.com/user-attachments/assets/b53c619b-01cf-4bc7-9747-5401c96976f3)
![RaspberryMatic WebUI-style cgi-error](https://github.com/user-attachments/assets/72b6ec0a-4188-44e9-996f-ab48d78da210)

**Comment by schmidt-gp** [comment]
Could fix my issue with updating the linux kernel (update ubuntu release).
see also: https://github.com/jens-maus/RaspberryMatic/issues/2648
