### ISSUE TITLE
ReGaHss crash Programme ändern

### ISSUE THREAD

**Issue by eli4711** [jens-maus/RaspberryMatic#2868]
### Describe the issue you are experiencing

Bei einem klick auf den OK Button im Programm Editor, stürtzt die ReGaHss sofort ab.
![3](https://github.com/user-attachments/assets/1026723c-fe67-4c4b-a19c-e7ba36ed83f5)
Man fliegt dann direkt aus der WebUi.
![1](https://github.com/user-attachments/assets/356ddc7d-8de7-42a4-b1be-59efec40c8ca)
Nach einem erneuten Login dann Alarm.
![2](https://github.com/user-attachments/assets/037c485a-f6ec-4632-a4c5-c13760b61354)

Dabei ist es egal, ob man was im Programm ändert oder nicht. Es reicht schon der klick auf OK.

In den Logs finde ich keinen passenden Eintrag, ausser den von monit.

### Describe the behavior you expected

Programme lassen sich durch klick auf OK ändern.

### Steps to reproduce the issue

1.Im Programm Editor auf OK klicken
2.
3.
...

### What is the version this bug report is based on?

raspmatic_generic-x86_64 (3.79.4.20241003)

### Which base platform are you running?

generic-x86_64 (Generic UEFI capable system, AMD64/x86_64)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Oct  5 10:35:02 raspmatic user.err monit[2872]: 'ReGaHss' service restarted 1 times within 1 cycles(s) - exec
Oct  5 10:35:02 raspmatic user.info monit[2872]: 'ReGaHss' exec: '/bin/triggerAlarm.tcl ReGaHss restarted WatchDog: regahss-restart true'
Oct  5 10:35:02 raspmatic user.info monit[2872]: 'ReGaHss' process is running after previous restart timeout (manually recovered?)
Oct  5 10:35:04 raspmatic user.err monit[2872]: 'ccu-jack' process is not running
```

### Additional information

Nightly Test

**Comment by jens-maus** [comment]
Danke für den Report. Das Problem existiert nur im aktuellen nightly snapshot und wird mit einer der nächsten nightly wo dann die ReGaHss R1.00.0388.0242 mitkommen wird behoben sein.

**Comment by jens-maus** [comment]
Du meinst mit dem "3.79.4.20241006-68ffd9" wurde das Problem beseitigt. Danke für die Rückmeldung. Bitte basierend auf dieser Version mal umfangreiche/verschiedene Tests machen und weitere Problem bzw. Abstürze von ReGaHss hier melden damit wir vor dem finalen Release etwaige restliche Probleme in den 64bit Versionen von ReGaHss noch ausmerzen können.

**Comment by eli4711** [comment]
Ja genau Jens. Mit der aktuellen Nightly kann man die Programme wieder editieren. Werde weiter testen. 👍
