### ISSUE TITLE
adding HMIP-ESI to favorites only allows channel 0

### ISSUE THREAD

**Issue by Rosi2143** [jens-maus/RaspberryMatic#2877]
### Describe the issue you are experiencing

I want to see values for the HMIP-ESI device in the favorite view.
But the only selection I get is the channel 0 with device status data.

![Screenshot 2024-10-12 175154](https://github.com/user-attachments/assets/62d283a8-a840-4290-ba1d-0d81a3221a20)

[homematic-raspi-2024-10-12.log](https://github.com/user-attachments/files/17350719/homematic-raspi-2024-10-12.log)

### Describe the behavior you expected

As for any other HMIP device I want to be able to select the channel I want - not limited to a single one.

Please also allow channel-1 data to be displayed.

### Steps to reproduce the issue

1. Add any HMIP-ESI device (LED/GAS)
2. create a new favorite view and try to add the device data channel

### What is the version this bug report is based on?

3.77.6.20240720

### Which base platform are you running?

rpi3 (RaspberryPi3, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
log attached above
```

**Comment by Baxxy13** [comment]
Wenn du das Kanalauswahl-Popup offen hast filtere mal nach der Seriennummer deines ESI: `003FA2698A9D64`
Eventuell andere vorhandene Filter löschen und dann nen Screenshot bitte.

**Comment by Rosi2143** [comment]
Sorry - user error.

I forgot to rename the channels as well - so the channels appeared at a different place in the list.

Pro-Tip: Filter for device-ID instead of channel name.

**Comment by oradke** [comment]
User errors are both the easiest and hardest to fix. ;)

**Comment by Baxxy13** [comment]
Und genau das hatte ich im Hinterkopf weil es ein häufig anzutreffendes User-Problem ist.
