### ISSUE TITLE
/usr/local/etc auf FAT32 auslagern

### ISSUE THREAD

**Issue by leonsio** [jens-maus/RaspberryMatic#288]
Hi

es wäre Überlegung Wert darüber nachzudenken die Konfigurationsverziechnisse auf FAT32 auszulagern.
Vorteil:
Alle Windows und Mac User können so auf die CCU Konfiguration ohne extra Tools oder Umwege über Linux zugreifen. 
Falls RPi abraucht, kann man ohne Umwege auf die Konfiguration zugreifen und Backup anlegen.
Nachteil:
Das Problem ist die Größe der Partition, wenn die überläuft durch diverse Erweiterungen hat man ein Problem :(

**Comment by jp112sdl** [comment]
Aber nur, wenn man die SD-Karte aus dem Raspberry entnimmt und ins Notebook/PC steckt.
Mir fällt gerade kein Szenario ein, warum man das machen sollte.

Ansonsten kommt man "online" ja mit WinSCP oder Cyberduck gut an alles ran.

**Comment by leonsio** [comment]
Genau dafür ist es auch gedacht. 
So kommt jeder 0815 User an seine Daten wenn raspi abraucht. (Wobei Sd Karte wahrscheinlich vorher den Geist aufgibt)

Boot ist ja bereits auf FAT also warum nicht auch userfs?

Von meinem iPhone gesendet

**Comment by jp112sdl** [comment]
Ja ok, das wäre wirklich nur für den Wurst Käse Fall... - aber was will ich mit den Daten, wenn ich keinen Raspi mehr habe? 

Mit installierten CCURM-Addons ist ein Wechsel auf die CCU2 wohl auch nicht so einfach möglich. Ich denke da insbesondere an CUxD.

Ich müsste so oder so einen neuen Raspi beschaffen und dort würde die SD dann wieder laufen.

**Comment by jens-maus** [comment]
In der Tat hatte ich auch sowas mal kurz überlegt, aber dann eben recht schnell wieder verworfen. Der Punkt ist einfach, das 

1. FAT32 jetzt nicht das zuverlässigste Filesystem ist das man kennt
2. FAT32 Beschränkungen in der Namensgebung von Dateien hat
3. FAT32 eben obsolete/alt ist und kein Linux-natives Betriebsystem

Und das der rpi bootloader ein FAT32 /boot braucht ist einfach dem geschuldet weil es recht gut dokumentiert ist und leicht von den Entwickler implementiert werden konnte damit der bootloader seine daten findet. Andere Boards machen das anders bzw. board die via u-boot booten nutzen meist kein FAT32 /boot sondern direkt dann gleich ein ext3/4.

Des Weiteren muss man sagen das es nur auf den ersten Blick wirklich sinn macht alles in eine FAT32 Partition zu legen was der nutzer so konfiguriert hat. Bitte auch beachten das dann alle Addons, Alle Diagramme, etc. eigentlich darauf landen und mit einbußen zwangsläufig zu rechnen ist.

Und das jeder 0815 User dann so an seine Daten kommt stimmt zwar irgendwie. Aber so kann auch jeder 0815 Nutzer eben auch sein /usr/local auf der SD karte kaputt machen wenn mal wieder ein Windows Programm durchdreht oder der Virenscanner meint das eine Datei ein Virus wäre. Ergo, IMHO  wäre das eher nachteilshaft als das es Vorteile hat. 

Damit man aber trotzdem an seine Nutzerdaten kommt auch wenn das rootfs nicht mehr geht arbeite ich gerade an einem recovery system  für raspberrymatic. in den nächsten Versionen wird das rauskommen und dann erlauben wie bei einer CCU2 in ein recovery system zu booten in dem man dann über den Webbrowser verschiedene Administrative Dinge durchführen kann. Vom Recovery-Image hochspielen bis hin zum Notfall-backup erstellen, etc. etc. Ich denke das ist der bessere Weg als gar jetzt alles auf FAT32 umzustellen welches wirklich nicht gerade das beste Filesystem auf dem Markt ist (und das aus gutem Grund!).

**Comment by jens-maus** [comment]
Tschuldigung, aber nach reichlich Überlegung denke ich immer noch das es keine wirklich gute Idee wäre sämtliche Konfiguratiosndateien auf die FAT32 partition zu bringen.
