### ISSUE TITLE
COSMETIC: Icon für HMIP-HAP fehlt in Firmware Update-Seite

### ISSUE THREAD

**Issue by KoMa1978** [jens-maus/RaspberryMatic#2881]
### Describe the issue you are experiencing

In der FW Update-Seite wird für den HMIP-HAP kein Thumbnail angezeigt.

### Describe the behavior you expected

Es sollte ein Thumbnail angezeigt werden

### Steps to reproduce the issue

1. Klick auf Einstellungen / Geräte-Firmware - Übersicht
2. Dann unten auf "Geräte-Firmware".
3. Bei einem HMIP-HAP wir kein Thumbnail angezeigt

### What is the version this bug report is based on?

3.77.6.20240720

### Which base platform are you running?

rpi3 (RaspberryPi3, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Im Screenshot ist der Code-Schnipsel zu sehen wo der SRC Tag fehlt.
```

### Additional information

![image](https://github.com/user-attachments/assets/06e23e6e-ca57-42f7-86b1-841b4ea09b75)

**Comment by jens-maus** [comment]
Duplicate of #2785
