### ISSUE TITLE
DV von HmIPW-SPI mit HmIPW-DRD3 unter 3.79 geht nicht

### ISSUE THREAD

**Issue by tknetsch** [jens-maus/RaspberryMatic#2887]
### Describe the issue you are experiencing

Hallo, nach dem neu anlegen einer DV lässt sich diese nicht bearbeiten (HmIPW-SPI mit HmIPW-DRD3). Die Seite bleibt weiß und kann nicht über: Übernehmen, oder OK beendet werden. Bestehende DV´s lassen sich problemlos bearbeiten. Ander DV, z.B.: HmIPW-SPI mit HmIPW-DRS4 lassen sich erstellen und bearbeiten. Neustart, sowie warten brachten keinen Erfolg. System: Homematic Wired. RM auf Proxmox in einer VM. Update Datei: OVA.Zip

### Describe the behavior you expected

DV lässt sich nicht bearbeiten - Präsenzmelder mit Dimmaktor Wired

### Steps to reproduce the issue

1. Erstellung einer DV
2. Auswahl der Geräte
3.Erstellen und bearbeiten
...

### What is the version this bug report is based on?

3.79.6.20241031

### Which base platform are you running?

ova (Open Virtual Infrastructure, AMD64/x86_64)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
nein
```

**Comment by jens-maus** [comment]
Bitte schauen ob unter /usr/local/tmp irgendwelche cgimail Dateien zu finden sind und den Inhalt hier posten.

**Comment by tknetsch** [comment]
Nein, habe ich nicht...
![temp](https://github.com/user-attachments/assets/e65c7631-1487-46ca-a4fe-905fc1a7d221)

**Comment by tknetsch** [comment]
> Bitte schauen ob unter /usr/local/tmp irgendwelche cgimail Dateien zu finden sind und den Inhalt hier posten.

Ich komme nicht auf den Ordner. Wenn ich mich versuche anzumelden kommt: Zugriff verweigert. Versucht habe ich Putty, Winscp und die Konsole in Proxmox. Habe die IP der Raspmatic genommen. Danach die der Konsole in Proxmox. Kein Erfolg. Beides versucht mit und ohne ssh aktiviert in der webui.

**Comment by Baxxy13** [comment]
ssh ist über die WebUI > Einstellungen > Systemsteuerung > Sicherheit aktiviert?
Wenn ja dann loggst du dich mit root und deinem Passwort ein.

**Comment by tknetsch** [comment]
> ssh ist über die WebUI > Einstellungen > Systemsteuerung > Sicherheit aktiviert? Wenn ja dann loggst du dich mit root und deinem Passwort ein.

Wie ich geschrieben habe... habe mich zu blöd angestellt ;-)... Habe versucht, mich mit meinem Login Namen und nicht mit root anzumelden. Danke

**Comment by tknetsch** [comment]
> Bitte schauen ob unter /usr/local/tmp irgendwelche cgimail Dateien zu finden sind und den Inhalt hier posten.

![cgi](https://github.com/user-attachments/assets/3262537d-22b9-49ed-b706-86c5b7a6bc41)

**Comment by jp112sdl** [comment]
Den Fehler zu finden könnte schwierig werden... im Vergleich zur vorherigen Firmware Version finde ich zum Thema `SHORT_ON_MIN_LEVEL` 77 Änderungen im WebUI-Code 

Kannst du mal einen anderen Sender-Typ (z.B. eine virtuelle CCU-Taste) mit dem Dimmaktor als Empfänger testweise verknüpfen?

**Comment by tknetsch** [comment]
Bewegungsunterdrückung:

Virtueller Taster:
![1](https://github.com/user-attachments/assets/31f6514d-0399-4c7e-a7ce-4c67ffc2fe61)
![2](https://github.com/user-attachments/assets/91f7e1e4-76db-4375-8e9e-31e09bb98c41)

Mit einem Taster von einem DRI32 Eingang:
![3](https://github.com/user-attachments/assets/3b1a6cf2-6d7e-4413-917a-6639f1b5879f)
![4](https://github.com/user-attachments/assets/c0c85ac6-13ef-4e2b-8e41-fe4a5aa7a075)

Es klappt. Bei beiden wird die Bewegungsunterdrückung eingeschaltet.

**Comment by Baxxy13** [comment]
Falsch verstanden. 😉 

Das Problem liegt eher beim Empfänger, also dem Dimmer.
Zum testen also die virt. Taste mit dem Dimmer verknüpfen und idealerweise die DV so einstellen wie auch die DV mit dem SPI wäre.

**Comment by jp112sdl** [comment]
Hmm ja, bei
> Dimmaktor als Empfänger

...dachte ich, es wäre eindeutig 🙈

**Comment by tknetsch** [comment]
Was mir aber auch aufgefallen ist: (Taster) In den DV, welche vor dem Update erstellt worden sind, ist der SHORT_ON_MIN_LEVEL bei 0.100. Jetzt erstellt er sie mit 0.050

Jaaaa, du hast recht. Ehrlich gesagt, habe ich mich auch gefragt, was der Präsenzmelder damit zu tun haben soll. Egal...

Verknüpfungen gemacht: Virtuell, sowie Physisch. Beides klappt.

**Comment by jp112sdl** [comment]
Also ich war wirklich bemüht... aber ich finde den Fehler nicht.

An allen Stellen, wo der Parameter `SHORT_ON_MIN_LEVEL` in den Easymode Profilen verwendet wird, wird vorher geprüft, ob er im `ps`-Array enthalten ist:
```TCL
if {[info exists ps(SHORT_ON_MIN_LEVEL)] == 1} {
...
append HTML_PARAMS(separate_$prn) [get_ComboBox options SHORT_ON_MIN_LEVEL separate_${special_input_id}_$prn\_$pref PROFILE_$prn SHORT_ON_MIN_LEVEL "onchange=\"ActivateFreePercent4InternalKey(\$('${special_input_id}_profiles'),$pref);Disable_SimKey($ch, $prn, '${special_input_id}');\""]
...
}
``` 

Heißt für mich: Ist `SHORT_ON_MIN_LEVEL` nicht in `ps` enthalten, wird den `HTML_PARAMS` gar nicht erst `get_ComboBox options SHORT_ON_MIN_LEVEL...` angehängt.

Von daher dürfte die CGIMail Exception eigentlich gar nicht auftreten...

Das kam auch jetzt erst mit der 3.79 (rechts) mit rein. Im Screenshot der Vergleich zur 3.77 (links):

<img width="2031" alt="Bildschirmfoto 2024-11-03 um 13 05 01" src="https://github.com/user-attachments/assets/c4da7114-39e0-43ef-9d20-53ee96cbb387">

**Comment by jens-maus** [comment]
@jp112sdl Liegt es vielleicht daran das `SHORT_ON_MIN_LEVEL` zwar im `PROFILE_1` existiert, aber nicht in `PROFILE_2`? 

Siehe https://github.com/eq-3/occu/blob/b07931489a0d4a2f7a442a385e384edb8177a590/WebUI/www/config/easymodes/DIMMER_VIRTUAL_RECEIVER/PRESENCEDETECTOR_TRANSCEIVER.tcl#L57

**Comment by jp112sdl** [comment]
Hmmm `SHORT_PROFILE_REPETITIONS` ist auch nur in `PROFILE_1` vorhanden und macht keine Probleme.
Und durch die IF-Abfrage "dürfte" ja gar nicht in die Combobox-Geschichte eingestiegen werden.
In `PROFILE_3` gibt es ganz und gar nur wenige Params.

Aber ja, wer weiß... Jetzt müsste @tknetsch mal die Zeile
```
set PROFILE_2(SHORT_ON_MIN_LEVEL) {0.1 range 0.0 - 1.0}
```
hinzufügen.

@tknetsch Mach mal per SSH das hier:
```
mount -o remount,rw / ;sed -i '103i set PROFILE_2(SHORT_ON_MIN_LEVEL) {0.1 range 0.0 - 1.0}' /www/config/easymodes/DIMMER_VIRTUAL_RECEIVER/PRESENCEDETECTOR_TRANSCEIVER.tcl ; mount -o remount,ro / 
```

Danach mindestens 1x mit F5 den Browser refreshen bzw. die WebUI komplett neu laden

**Comment by tknetsch** [comment]
Ja, das hat funktioniert. Jetzt lassen sich die DV´s zwischen Präsenzmelder und Dimmaktoren erstellen und bearbeiten. Funktioniert auch, wie es soll. Habe es mit 3 verschiedenen Präsenzmeldern, sowie 3 verschiedenen (nicht Kanälen) Aktoren erstellt und getestet. 

SHORT_ON_MIN_LEVEL wird beim erstellen auf 0.100 gesetzt.

**Comment by jp112sdl** [comment]
Sehr gut. Wenn das das Problem löst, dann fehlt die `set PROFILE_2(SHORT_ON_MIN_LEVEL) {0.1 range 0.0 - 1.0}`-Zeile in insgesamt "nur" 19 Files...
```
/www/config/easymodes/
ACOUSTIC_SIGNAL_VIRTUAL_RECEIVER/MOTIONDETECTOR_TRANSCEIVER.tcl
ACOUSTIC_SIGNAL_VIRTUAL_RECEIVER/MOTIONDETECTOR_VIRTUAL_TRANSCEIVER.tcl
ACOUSTIC_SIGNAL_VIRTUAL_RECEIVER/PRESENCEDETECTOR_TRANSCEIVER.tcl
ACOUSTIC_SIGNAL_VIRTUAL_RECEIVER/WATER_DETECTION_TRANSMITTER.tcl
DIMMER_VIRTUAL_RECEIVER/MOTIONDETECTOR_TRANSCEIVER.tcl
DIMMER_VIRTUAL_RECEIVER/MOTIONDETECTOR_VIRTUAL_TRANSCEIVER.tcl
DIMMER_VIRTUAL_RECEIVER/PRESENCEDETECTOR_TRANSCEIVER.tcl
DIMMER_VIRTUAL_RECEIVER/WATER_DETECTION_TRANSMITTER.tcl
SERVO_VIRTUAL_RECEIVER/DISPLAY_INPUT_TRANSMITTER.tcl
SERVO_VIRTUAL_RECEIVER/DISPLAY_LEVEL_INPUT_TRANSMITTER.tcl
SERVO_VIRTUAL_RECEIVER/KEY_TRANSCEIVER.tcl
UNIVERSAL_ACTOR/MOTIONDETECTOR_TRANSCEIVER.tcl
UNIVERSAL_ACTOR/MOTIONDETECTOR_VIRTUAL_TRANSCEIVER.tcl
UNIVERSAL_ACTOR/PRESENCEDETECTOR_TRANSCEIVER.tcl
UNIVERSAL_ACTOR/WATER_DETECTION_TRANSMITTER.tcl
UNIVERSAL_LIGHT_RECEIVER_PWM/MOTIONDETECTOR_TRANSCEIVER.tcl
UNIVERSAL_LIGHT_RECEIVER_PWM/MOTIONDETECTOR_VIRTUAL_TRANSCEIVER.tcl
UNIVERSAL_LIGHT_RECEIVER_PWM/PRESENCEDETECTOR_TRANSCEIVER.tcl
UNIVERSAL_LIGHT_RECEIVER_PWM/WATER_DETECTION_TRANSMITTER.tcl
```

@jens-maus Ich passe die mal alle an und mach nen PR ?

**Comment by jens-maus** [comment]
Nicht schließen solange das Problem
Nicht via PR oder Release behoben wurde. Das ist ja kein Diskussionsforum hier, sondern ein technischer Bugtracker.

**Comment by sschirr** [comment]
Ich kann mit der aktuellen RM Version (3.79.6.20241122) das gleiche Problem beobachten, wenn ich einen Farbkanal eines HmIPW-WRC6 als Verknüpfungsziel in einer DV verwenden möchte.

**Comment by jens-maus** [comment]
> Ich kann mit der aktuellen RM Version (3.79.6.20241122) das gleiche Problem beobachten, wenn ich einen Farbkanal eines HmIPW-WRC6 als Verknüpfungsziel in einer DV verwenden möchte.

Neues Issue aufmachen, beschreiben mit Screenshot und Screencast und dann zu dem hier verlinken. Bitte nicht einfach ein geschlossenes Ticket/Issue für ein anderes Problem wiederverwenden.

**Comment by Aelfot** [comment]
Auch mit Durchgangsensor passiert das gleiche. Keine Direktvektnüpfung zwischen Durchgangsensor und Dimmer ist bearbeitbar.
