### ISSUE TITLE
ReGaHss: 100% CPU Auslastung nach Update auf 2.31.25.20180225

### ISSUE THREAD

**Issue by McLive** [jens-maus/RaspberryMatic#289]
![image](https://user-images.githubusercontent.com/5620071/37489435-e177cad2-2897-11e8-9de1-b095ebe908c1.png)

Die WebUI ist nach dem Update nahezu unbedienbar, via SSH kann ich eine sehr hohe Auslastung beobachten.

Ich hänge mal meine logs an:
**messages**
https://hastebin.com/agimajuqos.vbs

**hmserver.log**
https://hastebin.com/elamocorez.pas

**Comment by jens-maus** [comment]
Passiert das reproduzierbare nach jedem reboot?

**Comment by McLive** [comment]
Nach einem harten reboot via Stecker ziehen kann ich das Problem nun nicht mehr reproduzieren.

Nach dem Upgrade auf die neue Version habe ich lediglich einen Neustart über das Webinterface ausgelöst. Vielleicht lag es ja daran. 

Ich melde mich sonst wieder.. 👍
