### ISSUE TITLE
Keypad HmIP-WKP Kanal-Beschreibung passt nicht zum Name des Kanals

### ISSUE THREAD

**Issue by mbhomie007** [jens-maus/RaspberryMatic#2895]
### Describe the issue you are experiencing

Die Kanal-Beschreibung passt nicht zum Name des Kanals.

### Describe the behavior you expected

Die Kanal-Beschreibung passt zum Name des Kanal.
Z. B. Keypad Garage vorne Benutzer 1 Verriegeln zu Benutzer 1 Verriegeln

### Steps to reproduce the issue

Gerät unter Einstellungen aufrufen

### What is the version this bug report is based on?

3.79.6.20241031

### Which base platform are you running?

rpi3 (RaspberryPi3, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Cache leeren und Neustart bringt keine Besserung
```

### Additional information

Hier falsch:
![Screenshot 2024-11-04 164308](https://github.com/user-attachments/assets/8c55ffce-31f4-432b-9690-eb8c6ad2f57a)

Hier richtig.
![image](https://github.com/user-attachments/assets/a793ff83-5a99-46dc-a222-ed4d59a1cc03)

**Comment by jens-maus** [comment]
Mehr Erklärung bitte. Was genau ist falsch, was wird erwartet.

**Comment by mbhomie007** [comment]
Habe es noch etwas geändert und ergänzt.
Siehe Screenshots.

**Comment by jens-maus** [comment]
Wie gesagt, beschreibe es! Es hilft nicht nur einem screenshots unter die Nase zu halten – vor allem wenn man dieses Gerät nicht selber hat und die Logik bzw. Erwartungshaltung nicht kennt. Beschreibe dein problem ausführlich und versuche nicht zeit zu kosten des Entwicklers zu sparen. Ich sehe/verstehe hier immer noch nicht was falsch sein soll und was du erwartest richtig stellen zu wollen. Und wenn das ein generelles Problem ist wundert es mich das der Aufschrei bei diesem Gerät nicht größer ist -> Ergo, auch im Homematic forum mit Leidensgenossen diskutieren weil sonst kommt der nächste um die ecke wenn wir das anpassen und es wieder nicht zu dessen erwartungen passt...

**Comment by jens-maus** [comment]
Tut mir leid wenn ich hier andere Ansprüche habe. Aber ich reagiere extrem allergisch darauf wenn man mir Einzeiler als Beschreibung um die Ohren hat und offensichtlich nicht die Zeit nimmt sein problem für Fremde in der notwendigen Tiefe zu beschreiben. Du schreibst nur "Problem: Die Kanal-Beschreibung passt nicht zum Name des Kanals." und dann "Erwartet: Die Kanal-Beschreibung passt zum Name des Kanal." Tut mir leid, aber das ist zu wenig. Beschreibe konkret und nicht nur mit gelber markierung im Screenshot was man dort sieht und was erwartet wird dort eigentlich stehen zu haben. Du zeigst auch zwei screenshots mit "Hier richtig" und "Hier falsch" und dann sind die komplett unterschiedlich bzw. aus unterschiedlichen Bereichen. Das kapiert vielleicht nur einer der das Gerät selbst hat und das reproduzieren kann bzw. selbst bereits darüber gestolpert ist. Ich kapier es jedenfalls nicht. Und wenn du es repariert/geändert haben willst musst du eben detallierter werden. So die Vorgehensweise...

**Comment by Baxxy13** [comment]
Wo kommen denn die Kanalbeschreibungen her?
Werden die beim Anlernen erzeugt?
Ich habe gar keine Kanalbeschreibungen (mehr), warum auch immer und hier nicht relevant.

**Comment by jp112sdl** [comment]
Es gab da schon mal was... #2187 
Dort sieht man zumindest im 1. Screenshot, wie es eigentlich aussehen müsste.

**Comment by jp112sdl** [comment]
Evtl. schafft der Patch #2902 hier Abhilfe.
Die Nummerierung der WKP Kanäle erfolgt auch in der `getExtendedDescription`-Funktion.
An der Nummerierung selbst wurde jedoch über die letzten CCU Versionen nicht verändert
```JS
    if (deviceType.toLowerCase() == "hmip-wkp") {
      tmpCounter = (typeof tmpCounter == "undefined") ? 1 : tmpCounter;
      result = translateKey("lblUser") + " " + tmpCounter + " ";

      if (channelIndex % 2 != 0) {
        result += translateKey("chType_ACCESS_TRANSCEIVER_LOCk");
      } else {
        result += translateKey("chType_ACCESS_TRANSCEIVER_UNLOCk");
        tmpCounter++;
      }

      if (typeof tmpTimer == "undefined") {
        tmpTimer = window.setTimeout(function () {
          delete tmpCounter;
          delete tmpTimer;
        }, 1000);
      }
      //result += (channelIndex % 2 == 0) ? translateKey("chType_ACCESS_TRANSCEIVER_UNLOCk") : translateKey("chType_ACCESS_TRANSCEIVER_LOCk");
    }
```

**Comment by jens-maus** [comment]
@mbhomie007 Bitte nochmal mit dem aktuellsten nightly snapshot probieren um zu verifizieren das das Problem noch existent ist seitdem #2902 umgesetzt wurde.

**Comment by mbhomie007** [comment]
Mit dem heutigen Snapshot 3.79.6.20241118-4a64ab sieht alles wieder normal aus.
Vielen Dank! 💯
