### ISSUE TITLE
"Status und Bedienung -> Gewerke" - Sortierung/Reihenfolge (A-Z/0-9) fehlerhaft

### ISSUE THREAD

**Issue by mbhomie007** [jens-maus/RaspberryMatic#2897]
### Describe the issue you are experiencing

Leider haben die Ticktes #1508 #1492 keinen Erfolg gebracht.

Das Problem ist leider auch mit der aktuellen 3.79.6.20241031 noch vorhanden.

Unter "Status und Bedienung -> Gewerke" muss man 2 Mal auf den Tabellenkopf "Name" klicken um zur üblichen Sortierung (A-Z/0-9) zu kommen.
Verlässt man die Seite, so ist die Einstellung für die Sortierung wieder weg.

Unter "Status und Bedienung -> Geräte" hingegen bleibt die Sortierung richtig erhalten -> funktioniert.
Es wir standartmäßig von (A-Z/0-9) sortiert.

### Describe the behavior you expected

Gleiche Sortierung wie über "Status und Bedienung -> Geräte" (A-Z/0-9).
Die Einstellung sollte standartmäßig hinterlegt sein.

### Steps to reproduce the issue

Unter "Status und Bedienung -> Gewerke" muss man 2 Mal auf den Tabellenkopf "Name" klicken um zur üblichen Sortierung (A-Z/0-9) zu kommen. Sonst ist alles durcheinander.

### What is the version this bug report is based on?

3.79.6.20241031

### Which base platform are you running?

rpi3 (RaspberryPi3, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
-
```

### Additional information

![140375289-7f05db33-d32f-4c4d-9c69-141d3669a895](https://github.com/user-attachments/assets/64900ecc-01b1-4a2b-841f-d9fef14d6727)

![140375143-9e880c64-188a-4b7a-a2a2-4e920b7cc174](https://github.com/user-attachments/assets/9153eba4-d384-4292-935d-70676be816d9)

**Comment by jens-maus** [comment]
Bitte Screencast (animated gif oder kurzes mp4) generieren um das Problem via video zu demonstrieren.

**Comment by jp112sdl** [comment]
Es geht um das "human sorting"
In Status und Bedienung => 
Geräte ist es numerisch aufsteigend:
- 1
- 2
- 3
- 4
- 5

Gewerke ist es alphabetisch aufsteigend:
- 1
- 10
- 11
- 2
- 20

sortiert.

Woher nun der Unterschied?
Das liegt daran, dass in "Geräte" einfach über die Kanäle des Geräts iteriert wird und diese beim Anlernen in aufsteigender Reihenfolge eine ISE ID bekommen. Die Ansicht ist per Default also erstmal nach gar nichts sortiert und wirkt nur augenscheinlich so, da die IDs hintereinander weg gelesen werden.

Zu den Gewerken:
Man kann ja auch nur einzelne Kanäle aus unterschiedlichen Geräten ins Gewerk nehmen... somit ist das Vorgehen wie in "Geräte" nicht so ohne Weiteres möglich.
In "Gewerke" gibt es zunächst ein `oTmpArray.SortByName();` um erstmal eine alphabetische Sortierung zu haben.

Eine Möglichkeit wäre, in der `/www/rega/pages/tabs/control/hfuncchannels.htm` beim ` Write("//IseSort(arChns, 'name', true);");` die Kommentarzeichen zu entfernen.
Dann wird beim Aufruf eines Gewerks jedes Mal der Klick auf 'Name' automatisch ausgeführt. Was wiederum zu einem Reload des Contents führt und sich nicht schon "anfühlt".

**Comment by jens-maus** [comment]
> Eine Möglichkeit wäre, in der `/www/rega/pages/tabs/control/hfuncchannels.htm` beim ` Write("//IseSort(arChns, 'name', true);");` die Kommentarzeichen zu entfernen.
> Dann wird beim Aufruf eines Gewerks jedes Mal der Klick auf 'Name' automatisch ausgeführt. Was wiederum zu einem Reload des Contents führt und sich nicht schon "anfühlt".

D.h. dann muss hier der Browser jedesmal das ganze sortieren? Dann ist das definitiv ja langsamer als vorher. Die Frage wäre also einfach: Lohnt der Aufwand?

**Comment by jp112sdl** [comment]
P.S.: Die eingehende Behauptung
> Unter "Status und Bedienung -> Geräte" hingegen bleibt die Sortierung richtig erhalten -> funktioniert.
Es wir standardmäßig von (A-Z/0-9) sortiert.

ist halt nur gefühlt so... Sie funktioniert dort genau so wenig und es ist dort anfangs auch nichts alphabetisch sortiert, bis man auf den Tabellenkopf klickt.
<img width="1612" alt="Bildschirmfoto 2024-11-04 um 18 24 46" src="https://github.com/user-attachments/assets/aa9f3e96-d87c-4b6d-981f-d1a4bb659bc7">

**Comment by jp112sdl** [comment]
> D.h. dann muss hier der Browser jedesmal das ganze sortieren? Dann ist das definitiv ja langsamer als vorher. 

Korrekt

> Lohnt der Aufwand?

Das ist wohl subjektiv zu beurteilen ;)

**Comment by jens-maus** [comment]
> > Lohnt der Aufwand?
> 
> Das ist wohl subjektiv zu beurteilen ;)

Das stimmt. Gibt es denn ne möglichkeit gleich via ReGa Abfrage die sortierung "richtig" zu machen und nicht einfach nur die ISEids hintereinander durchzugehen und dann später den Browser das sortieren zu lassen?

**Comment by jp112sdl** [comment]
>Gibt es denn ne möglichkeit gleich via ReGa Abfrage die sortierung "richtig" zu machen 

Cool wäre, wenn die ReGa auch `NaturalSortByName()` könnte ;-)
https://en.wikipedia.org/wiki/Natural_sort_order

**Comment by jens-maus** [comment]
Das sollte sich machen lassen 😜
