### ISSUE TITLE
Kanalbeschreibungen in > Einstellungen > Geräte fehlen komplett seit 3.77.6.20240720

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#2898]
### Describe the issue you are experiencing

Seit Version 3.77.6.20240720 fehlen bei allen meinen HmIP-Geräten (auf allen meinen Live/Testsystemen) die Kanalbeschreibungen die man normalerweise bei > Einstellungen > Geräte bei den Kanälen sieht.
Das erschwert es ungemein den Kanälen funktionelle Namen zu geben weil man erstmal überhaupt nicht weiß welche Funktion ein Kanal hat.

### Describe the behavior you expected

Kanalbeschreibungen der HmIP-Geräte-Kanäle sollten auch mit >= 3.77.6.20240720 vorhanden sein.

### Steps to reproduce the issue

1. 3.75.7.20240601 flashen, ein HmIP-Gerät (bspw. STHD) anlernen und die Kanalliste in > Einstellungen > Geräte mittels + aufklappen
2. sehen das alle Kanäle (außer :0) eine Beschreibung haben
3. Punkt 1 mit 3.77.6.20240720 oder höher wiederholen
4. sehen das alle Kanäle keinerlei Beschreibung haben
...

### What is the version this bug report is based on?

ab 3.77.6.20240720

### Which base platform are you running?

rpi4 (RaspberryPi4, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
keine Fehler im Logfile oder in der Browserkonsole
```

### Additional information

3.75.7.20240601:
![STHD_Kanalbeschreibungen ok 3 75 7 20240601](https://github.com/user-attachments/assets/cfd11361-4f88-432b-92b8-5283862d031d)

3.77.6.20240720 und aufwärts:
![STHD_Kanalbeschreibungen nicht ok 3 77 6 20240720](https://github.com/user-attachments/assets/0ae71875-cd5a-4c53-9411-90f825a66570)

**Comment by Baxxy13** [comment]
Ok, scheint wider mal an eQ-3 zu liegen...
CCU3 mit 3.79.6 sieht genauso aus.
![STHD_Kanalbeschreibungen nicht ok CCU3 3 79 6](https://github.com/user-attachments/assets/31105bd3-d9ff-4569-b39a-8789354cdf81)

**Comment by jens-maus** [comment]
Könnte gut sein das das vllt sogar Absicht war das das eQ3 entfernt hat?!?

**Comment by Baxxy13** [comment]
Möglich ist alles, ich glaube aber eher an ein "Missgeschick" seitens eQ-3.
Beim durchschauen meiner Systeme habe ich wirklich keine einzige Kanalbeschreibung mehr gefunden,

Durchexerziert habe ich das mit STHD und HmIP-PS. Und alles in "eQ-3 Originalkonfiguration" also kein Local-ReKeying. 😉

**Comment by jp112sdl** [comment]
Patch kommt morgen. Nur für mich als Clipboard:
```JS
  if (typeof channelType != "undefined") {
    chType = channelType;
  } else if (typeof channelAddress != "undefined") {
    var channel = DeviceList.getChannelByAddress(channelAddress);
    if (channel) {
      chType = channel.channelType;
      channelIsVisible = channel.isVisible;
    }
  } 
```

**Comment by Baxxy13** [comment]
Danke an @jp112sdl ...
Die Kanalbeschreibungen sind wieder vorhanden.
Können wir abhaken.

**Comment by eli4711** [comment]
Hallo zusammen. Glaube da ist noch was nicht ganz korrekt. Bei mir sind seit dem Patch nur noch 2 Geräte in der Geräteliste. 
![GeräteListe](https://github.com/user-attachments/assets/a0519fb2-a505-4031-8ecf-350d661104cd)
Getestet mit den letzten 2 Nightlys.
In der Browser Console taucht beim öffnen der Geräte Liste folgendes auf:
`TypeError: values is undefined
    restoreFilters https://192.168.0.210/webui/webui.js:9324
    fltrHandler https://192.168.0.210/webui/webui.js:9312
    fire https://192.168.0.210/webui/webui.js:28824
    each https://192.168.0.210/webui/js/extern/prototype.js:711
    each https://192.168.0.210/webui/js/extern/prototype.js:710
    fire https://192.168.0.210/webui/webui.js:28824
    updateView https://192.168.0.210/webui/webui.js:26026
    <anonymous> https://192.168.0.210/webui/webui.js:25524
`

In der Bediener Geräteliste sind alle noch da.

![GeräteListe2](https://github.com/user-attachments/assets/648b4e51-ef2b-4545-9c2a-184060c4da3e)

Soll ich da mal noch n Issue für aufmachen?

**Comment by Baxxy13** [comment]
Hmm, wenn du kannst dann mache doch die Änderungen mal rückgängig.
War ja überschaubar.

Ich sehe hier auf 3 (kleinen) Testsystemen keine Probleme.

**Comment by jp112sdl** [comment]
Auf meinem Kraut-und-Rüben-Testsystem auch keine Probleme.

Versuch mal den Browser Cache zu löschen oder die Seite in einem neuen "privaten Fenster" aufzurufen

**Comment by eli4711** [comment]
Kann erst heute abend testen. Bin auf Geschäftsreise. Den Cache hab ich schon mal gelöscht. Getestet mit Chrome und Firefox. Was mir noch aufgefallen ist, das bei den zwei PSM die Gewerke und Raum Zuordnungen fehlen. Wenn ich da auf den Filter klicke, kommt nur das Feld mit den zwei Buttons (wie oben im Bild). Hoffe ich kann heute Abend noch eingehend testen.

**Comment by eli4711** [comment]
Hab jetzt noch mal alle Homematic Logs durchgesehen. Dort sind keine Fehler zu finden.
Im Browser hab ich noch folgende Meldung gefunden.
`Uncaught TypeError: chn is undefined
    getExtendedDescription https://192.168.0.210/webui/webui.js line 2 > srcScript:35568
    m_extendName https://192.168.0.210/webui/webui.js line 2 > srcScript:11280
    update https://192.168.0.210/webui/webui.js line 2 > srcScript:11271
    initialize https://192.168.0.210/webui/webui.js line 2 > srcScript:11211
    klass https://192.168.0.210/webui/js/extern/prototype.js:94
    updateChannel https://192.168.0.210/webui/webui.js line 2 > srcScript:12235
    update https://192.168.0.210/webui/webui.js line 2 > srcScript:11780
    each https://192.168.0.210/webui/js/extern/prototype.js:711
    each https://192.168.0.210/webui/js/extern/prototype.js:710
    update https://192.168.0.210/webui/webui.js line 2 > srcScript:11779
    initialize https://192.168.0.210/webui/webui.js line 2 > srcScript:11737
    klass https://192.168.0.210/webui/js/extern/prototype.js:94
    reload https://192.168.0.210/webui/webui.js line 2 > srcScript:12413
    each jQuery
    reload https://192.168.0.210/webui/webui.js line 2 > srcScript:12399
    homematic https://192.168.0.210/webui/webui.js line 2 > srcScript:28573
    onreadystatechange https://192.168.0.210/webui/webui.js line 2 > srcScript:8174`

Die Geräte sind in allen Einstellungsseiten verschwunden, also Gewerke, Räume, Geräteupdates usw.
Liegt es eventuell an der menge an Geräten? Dauert da irgend was zu lange, und läuft in irgend einen Timeout?
Hab irgendwas um die 350 Geräte im System, inclusive cuxd und ccujack.

Wo könnte der Fehler noch versteckt sein? Hat jemand n Tip wo ich suchen kann?

**Comment by jp112sdl** [comment]
Hmpf, schon wieder das `DeviceList.getChannelByAddress(channelAddress)`

Das ist irgendwie kaputt.
Speziell geht es um den Block:
```JS
    if (getMode) {
      if ((multiMode != "--") && (typeof multiMode != "undefined")) {
        typeExt = "_" + multiMode;
      } else {
        if (channelAddress != "undefined") {
          var chn = DeviceList.getChannelByAddress(channelAddress),
          chnMode = parseInt(chn.multiMode);
          if (! isNaN(chnMode)) {
            typeExt = "_" + chnMode;
          } else {
            typeExt = "";
          }
        } else {
          typeExt = "_1";
        }
      }
    }
```

Insbesondere der Teil
```JS
          var chn = DeviceList.getChannelByAddress(channelAddress),
          chnMode = parseInt(chn.multiMode);
```

Das muss mal noch genauer analysiert werden.

**Comment by eli4711** [comment]
Wenn ich irgendwas testen soll, bin allzeit bereit! Sofern ich zu Hause bin ;-)

**Comment by jp112sdl** [comment]
Wenn du weißt, wie du die `webui.js` editierst, dann gern...
Bau mal **über** der Zeile (die gibt es in der Datei nur an 1 Stelle)
```JS
          var chn = DeviceList.getChannelByAddress(channelAddress),
```
ein 
```JS
          console.log("multiMode = "+multiMode);
```
ein.

Und dann schau mal in der Konsole, was da als `multiMode` ausgegeben wird.

**Comment by eli4711** [comment]
Wird gemacht, aber du meinst dann die `webui.js`, aus dem Patch oder? Ich versuchs gleich mal.

**Comment by eli4711** [comment]
![multimode](https://github.com/user-attachments/assets/00dd3941-dea1-4b23-99a1-e5fe10d74ef7)

Das kam dabei raus. Ist das Plausiebel für dich?

**Comment by jp112sdl** [comment]
Hmm hatte mir was anderes erhofft.
Ändere die Ausgabe mal in `console.log(oChannelDescr)`.
Dann bekommst du in der Konsole das ganze Objekt mit allen Eigenschaften angezeigt.

Für mich wäre es interessant, ob der eingestellte Channel-Mode schon mit im Objekt übergeben wird und wir das `getChannelByAddress` gar nicht brauchen. _(Die Funktion ist eigentlich total unspektakulär, hängt aber beim Iterieren über alle IDs immer um 1 daneben und mir ist unklar, warum)_

**Comment by eli4711** [comment]
Scheint gar nicht zu funktionieren. 

![Console2](https://github.com/user-attachments/assets/054e5d5d-dd23-4193-8d1f-67184e4c4a3e)

Received message : ......

**Comment by jp112sdl** [comment]
Ich habe jetzt schon mal verstanden, was da schief läuft, habe aber momentan noch keine Lösung parat.

**Comment by eli4711** [comment]
Wenn du noch was brauchst, einfach melden. ;-)

**Comment by Baxxy13** [comment]
Das ist wieder das "Metadaten-Ding" beim HmIP-MOD-RC8.
Wenn die Metadaten `channelMode` für alle 8 relevanten Kanäle vorhanden und gesetzt sind (0/1/2/3), dann sind wieder alle Geräte unter > Einstellungen > Geräte sichtbar und es gibt keine Fehler in der Browserkonsole.

Das war ja auch schon beim Anzeigen des (korrekten) Modus (#2892) ein Problem das wir umgehen mussten.

Eigentlich muss eQ-3 nachbessern. 
Wenn die Metadaten `channelMode` genutzt werden sollen, dann müssen diese auch in die Kanäle geschrieben werden.
Das passiert aber aktuell nicht.

**Comment by jp112sdl** [comment]
> Das ist wieder das "Metadaten-Ding" beim HmIP-MOD-RC8. 

Kann ich mir eigentlich nicht vorstellen.
Der JS Fehler kommt, weil `getChannelByAddress` über die Kanal-Liste iteriert, die zu dem Zeitpunkt genau den zu erfassenden Kanal noch nicht enthält.

Deshalb würde ich den einzigen verbliebenen `getChannelByAddress` dort gern weg haben und schauen, ob man den eingestellten Mode nicht schon beim `getExtendedDescription` mit übergeben kann. 

> Der HmIP-FSI16 ist auch einer der verschwundenen Geräte.

@Baxxy13 hast du auch so einen FSI16 zum Testen ?

**Comment by Baxxy13** [comment]
Ok, dann wird wohl erst gar nicht zur problematischen Funktion abgebogen wenn die Metadaten vorhanden sind.

**Mit** `channelMode` - Metadaten beim HmIP-MOD-RC8:
![RM_MultiMode_ok](https://github.com/user-attachments/assets/449f6dc9-6839-4ab0-8d26-f5ccd25edf2c)

**Ohne** `channelMode` - Metadaten beim HmIP-MOD-RC8:
![RM_MultiMode_not_ok](https://github.com/user-attachments/assets/c5814b0e-7b97-49b2-a663-3e70dbd70aa8)

HmIP-FSI16 habe ich nicht. 
Laut Doku ist dessen Kanal:1 auch `MULTI_MODE_INPUT_TRANSMITTER`, ich denke aber schon immer.
(kannst du ja mal gucken ob da die xml geändert wurde)
Dann müsste man noch prüfen ob der die Metadaten hat. 
Denke ja, meine DRSI's auf dem Hauptsystem haben diese zumindest auch.

Außerdem wird anhand der Metadaten die Kanalbeschreibung generiert.
![RM_MOD-RC8_ChnMode_set](https://github.com/user-attachments/assets/13c1dcb3-449f-4241-9f6c-89e3ca78a836)

Testsystem ist bereit, ab Nachmittag hätte ich Zeit. 😉

**Comment by Baxxy13** [comment]
@eli4711 

Du kannst mal den gepatchen Block (webui.js) durch folgendes ersetzen:
```js
    if (getMode) {
      if ((multiMode != "--") && (typeof multiMode != "undefined")) {
        typeExt = "_" + multiMode;
      } else {
        if (channelAddress != "undefined") {
          var chn = DeviceList.getChannelByAddress(channelAddress);
          if (typeof chn != "undefined") {  
            chnMode = parseInt(chn.multiMode);
            if (! isNaN(chnMode)) {
              typeExt = "_" + chnMode;
            } else {
              typeExt = "";
            }
          }
        } else {
          typeExt = "_1";
        }
      }
    }
    result = translateKey("chType_MULTI_MODE_INPUT_TRANSMITTER" + typeExt);
  }
```

Das müsste das Problem (fehlende Metadaten z.B. bei MOD-RC8 und FSI16) abfangen und es sollten wieder alle Geräte gelistet werden.

**Comment by eli4711** [comment]
Jepp, das läuft. Sieht gut aus. Werde weiter mit dem Setup testen. Denke man sollte bei EQ3 doch mal langsam über einen Support von euch nachdenken! 🥇

**Comment by jp112sdl** [comment]
> Jepp, das läuft. 

Es behebt nur leider nicht das eigentliche Problem.

> Denke man sollte bei EQ3 doch mal langsam über einen Support von euch nachdenken! 🥇

Mit der orig. CCU3 FW 3.79.6 tritt der Fehler gar nicht erst auf, weil die Metadaten korrekt angelegt werden.

Im Moment besteht das Problem wohl nur in RM und wir finden den Fehler nicht.

**Comment by jp112sdl** [comment]
So - da hat uns eQ-3 aber ein echtes Ei ins Nest gelegt!

Das Ganze geht kaputt, wenn die `hmip-mod-rc8_*_master.tcl` aus [/www/config/easymodes/hmip](https://github.com/eq-3/occu/tree/master/WebUI/www/config/easymodes/hmip) dynamisch zur Laufzeit geladen werden.

Diese Dateien existieren auf der CCU3 gar nicht!
Wenn man sie auf der RM auch löscht, ist der ganze Spuk vorbei...

**Comment by jens-maus** [comment]
@jp112sdl Ah, mal wieder eine typische OCCU Inkonsistenz weil die in ihren OCCU Updateskripten nur neue Dateien hinzufügen aber gelöschte dateien nicht automatisch entfernen. Na dann liste mal die Dateien im OCCU auf die es in der CCU3 Firmware nicht gibt und dann lösche ich die raus... oder schick mir nen PR auf meine OCCU Fork.

**Comment by jens-maus** [comment]
Komplett entfernt werden? Und diese tcl dateien gibt es definitiv nicht in der CCU3 Firmware?

**Comment by Baxxy13** [comment]
Definitiv nicht. Weg damit.
![OCCU vs CCU3](https://github.com/user-attachments/assets/88e396db-80b2-45c2-97bf-8b894c007e7f)
(links OCCU | rechts CCU3)

**Comment by jens-maus** [comment]
Ok, danke. Sollte mit OCCU 3.79.6-5 erledigt sein. Hab auch den 0189 WebUI patch inzwischen entfernt. Der morgige nightly snapshot sollte also hoffentlich das problem beseitigen.

**Comment by Baxxy13** [comment]
Hoffen wir mal das es das nun endgültig war. 
Ziemlich mühsame Sache.

**Comment by Baxxy13** [comment]
Also auf meinem Testsystem mit dem HmIP-MOD-RC8 passt mit dem heutigen Nightly nun alles.

Vielleicht kann @eli4711 das auf seinem System auch noch mal prüfen.

**Comment by eli4711** [comment]
Jepp, jetzt passt es wieder 👍
