### ISSUE TITLE
rp0 Image seit dem neuesten Update, leitet nicht auf Login-Seite um

### ISSUE THREAD

**Issue by Mitch187** [jens-maus/RaspberryMatic#2899]
### Describe the issue you are experiencing

Hallo,

seit dem neusten Image RaspberryMatic 3.79.6.20241031 startet mein Raspberry PI Zero W zwar, aber ich kann mich nur noch per SSH einloggen. Die Eingangseite erscheint, leitet aber nicht auf die Login-Seite um.

Nachdem ich eine Neuinstallation der 3.79.6.20241031 gewwagt habe, war es das selbe Bild.

Nachdem ich die Vorversion RaspberryMatic 3.77.7.20240826 eingespielt habe und ein Backup funktioniert mein Installation und die Login-Seite wieder tadelos.

LG, Mitch

### Describe the behavior you expected

-

### Steps to reproduce the issue

-

### What is the version this bug report is based on?

3.79.6.20241031

### Which base platform are you running?

rpi0 (RaspberryPi, ARM/armhf)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
.
```

**Comment by jens-maus** [comment]
Duplicate of #2888
