### ISSUE TITLE
Keine Verbindung zwischen CCU und Funk LAN-Gateway (HMLGW) unter 2.31.25.20180225

### ISSUE THREAD

**Issue by firecat76** [jens-maus/RaspberryMatic#290]
Nach dem Upgrade von CCU und HMLGW auf 2.31.25.20180225 wird das Gateway als "nicht verbunden" in der CCU angezeigt. Das Problem kann nur dadurch umgangen werden, dass man das Gateway auf die Version 2.31.25.20180120 downgraded.

**Comment by TitusP** [comment]
Kann ich so generisch nicht bestätigen. Habe dieses Problem in selber Konfiguration nicht.

**Comment by cotonila** [comment]
Kann ich auch nicht bestätigen. Hab 3 LAN GW im System welche ohne Probleme auch mit der neuesten Version funktionieren.

**Comment by HMside** [comment]
Bei mir laufen die Gateways auch.

**Comment by jens-maus** [comment]
Bitte nochmal detailliert bestätigen: Ihr habt RaspberryMatic 2.31.25.20180225 als LAN Gateways im Einsatz (Fake LAN Gateway) und diese funktionieren problemlos?

**Comment by cotonila** [comment]
Also bei mir läuft nur der Zentralen RPi auf der aktuellen FW 2.31.25.20180225. Die 3 LAN GW auf älteren Versionen. Welche weiß ich leider nicht mehr genau. Sind vermutlich sogar 3 verschiedene, da ich die GW innerhalb von ca 1 oder 1,5 Jahren installiert hab.

**Comment by cotonila** [comment]
Werden denn die GW automatisch mit neuer FW versorgt? Versteh scheinbar die Frage von firecat76 falsch. Wieso macht man denn ein Update eines laufenden LAN GW? Aber ok - es muss natürlich auch mit der neuesten FW funktionieren. Ob das explizit funktioniert, kann ich für meinen Teil nicht beantworten...

**Comment by TitusP** [comment]
Ok, dann war das wohl ein Missverständnis. HMLGW klang für mich nicht nach einem RPi mit RaspberryMatic im LGW-Modus.
Bei mir läuft die Kombination HM-LGW (Original) mit RaspiMatic in Version 2.31.25.20180225 ohne Probleme.

**Comment by cotonila** [comment]
Da ich mich jetzt seit 3 oder 4 der letzten Versionen auch mit meinen LAN GW (Rai) rumärgere, muss ich mein Kommentar vom 20.03. revidieren. Nutze auf dem zentralen Rai aktuell 2.35.16.20180826.
Bei mir fallen mittlerweile leider regelmäßig, etwa 1x täglich, jedoch nie zu selben Zeiten, 2 von 3 LAN GW aus (nicht verbunden). Ein reboot über ssh reicht, damit sie sich wieder mit der Zentrale verbinden.
Schön ist das manuelle Hand anlegen jedoch nicht.
Die RPiMatic auf den LAN GW wurde seit ca. Mitte 2017 nicht geupdatet. Habe mittlerweile Netzteile und Raspberry's getauscht. Die SD Karten noch nicht, da es laut Forum mit den neuen RPi Versionen auch Probleme gibt.

**Comment by TitusP** [comment]
Bist du denn sicher, dass es keine Unterbrechung der LAN-Verbindung gibt?

**Comment by cotonila** [comment]
Das es keine Kurzzeitigen Unterbrechungen gibt - nein. Dagegen spricht aber, dass ich erstens noch ein 3. RPi LAN GW (baugleich) im Einsatz habe was überhaupt nichts hat und zweitens, dass sich die RPI LAN GW nach Unterbrechung selbstständig wieder verbinden. Da sie aber normal erreichbar sind und nur das Problem auf HM SW besteht weis ich da auch nicht mehr weiter...
