### ISSUE TITLE
Seit Release 3.79.6.20241031 startet die WebGUI nicht mehr

### ISSUE THREAD

**Issue by AlexViridi** [jens-maus/RaspberryMatic#2907]
### Describe the issue you are experiencing

Ich habe einen Pi 1 Modell B+ mit dem Homematic-Funkmodul. Seit der Installation des Raspberry-Matic Releases 3.79.6.20241031 startet die Weboberfläche nicht mehr. Die WebGUI bleibt stets auf dem blauen Startbildschirm hängen und teilt mir mit, dass ich gleich weitergeleitet würde. 
Folgende Dinge habe ich bisher versucht:
•	Vollständige Neuinstallation des Betriebssystems auf der vorhandenen MicroSD
•	Rollback auf älteres Release
•	Anschluss eines Monitors/Tastatur, um mehr Infos zu erhalten, scheinbar wurden alle Dienste gestartet.
•	Neue MicroSD Karte gekauft und Betriebssystem neu installiert.

### Describe the behavior you expected

Die WebGUI startet nach Aufruf der URL/IP-Adresse.

### Steps to reproduce the issue

1. SD-Karte einlegen
2. Raspi mit LAN und Strom verbinden
3. Versuchen, die WebGUI unter ihrer IP-Adresse oder DNS-Alias zu erreichen
...

### What is the version this bug report is based on?

3.79.6.20241031

### Which base platform are you running?

rpi0 (RaspberryPi, ARM/armhf)

### Which HomeMatic/homematicIP radio module are you using?

HM-MOD-RPI-PCB

### Anything in the logs that might be useful for us?

```txt
boot.log:
[..]
Starting HMIPServer: ......................................................................................OK
Starting ReGaHss: ....................ERROR
Starting CloudMatic: OK
[..]

lighttpd-error.log:
[..]
2024-11-09 11:45:02: (../src/gw_backend.c.288) establishing connection failed: socket: tcp:127.0.0.1:8183: Connection refused
2024-11-09 11:45:02: (../src/gw_backend.c.971) all handlers for /? on  are down.
2024-11-09 11:45:05: (../src/gw_backend.c.365) gw-server re-enabled: tcp:127.0.0.1:8183 127.0.0.1 8183
```

**Comment by jens-maus** [comment]
Duplicate of #2888
