### ISSUE TITLE
Minor UI Error : missing </select> in prototype.js:1907 

### ISSUE THREAD

**Issue by drose28357** [jens-maus/RaspberryMatic#2913]
### Describe the issue you are experiencing

Auf der Suche nach einem Bug bin ich über diese Ausgabe in der Browser-Konsole gestoßen:

Für HmIP-Geräte:
![Fehlerkonsole in Chrome bei öffnen von Einstellungen-Geräte-Einstellungen](https://github.com/user-attachments/assets/daad90d6-9e4f-4d2f-acce-83d8df7c445b)
Für HM-Geräte:
![Fehlerkonsole in Chrome bei öffnen von Einstellungen-Geräte-Einstellungen_hm](https://github.com/user-attachments/assets/a1235f95-b182-4c51-93c0-11007a869058)

Der Fehler tritt immer in prototype.js:1907 auf.

Die Funktion scheint nicht beeinträchtigt zu sein. Für Zeiteingaben werden die erlaubten Werte msec, sek, 4 min etc etc. korrekt in der UI angezeigt. Anscheinend wird das automatische durch den Browser gefixed, jedoch kann sich hier das Browserverhalten in Zukunft ändern.
Daher minor Issue.

### Describe the behavior you expected

Keine Fehlerausgaben in der Konsole, wenn man die Einstellungen eines Gerätes öffnet.

### Steps to reproduce the issue

1. Browser-Konsole (hier  Chrome) öffnen
2. Öffnen von Einstellungen/Geräte
3. Ein Gerät auswählen und dort für das Gerät oder einen Kanal die Einstellungen öffnen.

### What is the version this bug report is based on?

3.79.6.20241031

### Which base platform are you running?

rpi3 (RaspberryPi3, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Konsolen Ausgabe siehe oben.
```

**Comment by jens-maus** [comment]
Um welche konkreten Gerätetypen handelt es sich?

**Comment by jens-maus** [comment]
Himmel, hört das denn nie auf mit diesen eQ3 leichtsinnfehlern.... wäre nur die Frage wer bastelt dafür jetzt nen fix? Ich kann das übernehmen, hab gerade eh paar Stunden Zugfahrt vor mir 😃

**Comment by jp112sdl** [comment]
Ja mach mal. Ich bin momentan geheilt, nach dem MOD-RC8

**Comment by jp112sdl** [comment]
@drose28357 Auf jeden Fall vielen Dank für die gute Vorarbeit! Das hat das Finden der Ursache wesentlich vereinfacht.
