### ISSUE TITLE
Astro-Zeit-Funktion - Laufzeit wird seit letzten Update anders ausgewertet

### ISSUE THREAD

**Issue by nehkaa** [jens-maus/RaspberryMatic#2914]
### Describe the issue you are experiencing

Seit dem letzten Update der RespberryMatic Software (auf 3.79.6.20241031 vor ca. 2 Wochen) habe ich das Problem, dass einige meiner Scripte nicht mehr wie vorher arbeiten. Ich habe dazu jetzt ein Minimalbeispiel erstellt. Dabei habe ich mich an https://github.com/jens-maus/RaspberryMatic/wiki/Tipps#zeitmodul-mit-erweiterter-astro-funktion-offset-und-limit orientiert.
Bisher konnte ich z.b. aus dem Zeitmodul als bool auswerten mit den Eigenschaften 30 Minuten vor den Sonnenaufgang bis 30? Minuten vor Sonnenuntergang legen, indem ich "von Sonnenaufgang versetzt um -30 Min ..." eingerichtet habe (wie in dem Beispiel) und das Feld "oder für XXX min" leer gelassen habe. Laut Doku läuft es dann bis zum nächsten Wechsel von Sonnenauf-/unter-gang.
Wenn ich das Feld jetzt leer lasse setzt das System automatisch eine 0 dort ein. Das führt dazu, dass nur genau der Zeitpunkt genommen wird und keine Zeitspanne mehr, die die gesamte Sonnenzeit darstellt möglich ist.

### Describe the behavior you expected

Ich würde erwarten, dass ich einen Systemzeitzustand erzeugen kann der von Sonnenauf- bis untergang (und andersherum) mit einem vorgegebenen Offset gilt.
Ich würde erwarten das z.B. durch die leere Einstellung beim "oder für xxx min" Feld, wie in der Doku beschrieben funktionieren.

### Steps to reproduce the issue

1. Neue Systemvariable Debug anlegen
2. Neues Programm erstellen: 
- Wenn--> Zeitsteuerung --> Zeitspanne --> Von Sonnenaufgang, versetzt um -30 Minuten, bis Sonnenuntergang oder für <leer> min
- Aktivität --> Systemzustand -> Debug -> Sofort -> "Sonnenaufgang"
- Sonst, Wenn--> Zeitsteuerung --> Zeitspanne --> Von Sonnenuntergang, versetzt um 30 Minuten, bis Sonnenaufgang oder für <leer> min
- Aktivität --> Systemzustand -> Debug -> Sofort -> "Sonnenuntergang"
- Aktivität --> Sonst --> Systemzustand -> Debug -> Sofort -> "else-fall"
3. in der Variable Debug steht dann mehr oder weniger den ganzen Tag "else-Fall" drin und in der alten Version der Software wäre der Else-Fall nie aufgetreten.
...

### What is the version this bug report is based on?

3.79.6.20241031

### Which base platform are you running?

rpi3 (RaspberryPi3, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Im Protokoll kann ich sehen, dass die Variable auf den Else-Fall gesetzt wird, weil die anderen Bedingungen nicht gelten.
```

**Comment by friedpa** [comment]
Die Funktion wurde im Nightly Snapshot von Jens gefixt. Also diesen Snapshot einspielen, dann funktioniert alles wieder wie vorher.

**Comment by Baxxy13** [comment]
Um das noch etwas zu präzisieren.
Der Bug betrifft das Zeitmodul wenn ein negativer Offset verwendet wird.

**Comment by nehkaa** [comment]
Danke für die schnelle Rückmeldung. Das Update läuft!
