### ISSUE TITLE
Zeitmodul - Astrofunktion --> Option "Versetzt um X Minuten .." funktioniert nicht mehr mit negativen Zahlen ab Ver. 3.79.6.20241031

### ISSUE THREAD

**Issue by HaggiHM** [jens-maus/RaspberryMatic#2916]
### Describe the issue you are experiencing

Nach dem Einspielen der neuen Firmware 3.79.6.20241031 funktioniert bei mir die Rollladensteurung nicht mehr. Dank CCU-Historian konnten sehr schnell alle Fehlerquellen, bis auf das Zeitmodul ausgeschlossen werden. Um das Zeitmodul zu testen wurde ein kleines Programm erzeugt, mit dem ich die Funktion vor und nach dem Update auf V.3.79 optisch darstellen kann.
Mann sieht relativ schnell das vor dem Update negative Zahlen in der Option "Versetzt um x Minuten" kein Problem waren. Mit der V.3.79 funktionieren keine negativen Zahlen mehr in der Astrofunktion. Mit dem Eintrag 0 Minuten funktioniert die Astrofunktion wieder.
![Test Zeitmodul mit V3_79](https://github.com/user-attachments/assets/dfb6c41a-5065-481a-9430-99e29438bfbd)

### Describe the behavior you expected

Ich hätte erwartet, dass auch negative Zahlen in der Astrofunktion auch mit der Version V. 3.79... noch funktionieren.
**Das ist ja auch eine geniale Fuktion.**

Achtung, ich verwende eine Synology NAS mit HB-RF-ETH als Funkmodul.

### Steps to reproduce the issue

1.Testvariable und Testprogramm erstellen, welches die Astrofunktion mit negativen Minuten Angaben verwendet (Siehe Scrennshot)
2. Mit CCU-Historian die Testvariable sichtbar machen
3. Jetzt testen mit V. 3.77.. + 3.79.6.20241031 und negativen Minutenangaben bei der Option "versetzt um"
4.Gegenprobe bei der Version 3.79.6.20241031 mit einer Minutenangabe von 0 Minuten.
...
![Programm Test Zeitmodul](https://github.com/user-attachments/assets/0ec51f60-af1e-44b1-b6bd-d359d338b047)

### What is the version this bug report is based on?

3.79.6.20241031

### Which base platform are you running?

ova (Open Virtual Infrastructure, AMD64/x86_64)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
Leider nein. Mangels tieferer Kenntnisse, kann ich das Zeitmodul nicht weiter debuggen.
```

### Additional information

Sollten weitere Tests nötig sein, bitte melden.

**Comment by jens-maus** [comment]
Duplicate of #2914

Problem schon lange bekannt und auch schon lange gebannt für die nächste kommende version.
