### ISSUE TITLE
Nach Erstellung einer direkten Verknüpfung bleibt die Seite der Profileinstellung leer - keine Profileinstellungen möglich

### ISSUE THREAD

**Issue by marianchr** [jens-maus/RaspberryMatic#2917]
### Describe the issue you are experiencing

Wenn ich eine direkte Verknüpfung zwischen einem Bewegungsmelder: HmIP-W-SMI55 (firmware: 1.0.20) und einem Dimmaktor: HmIPW-DRD3 (firmware: 2.0.6) erstellen möchte, wird die Verknüpfung angelegt aber der folgende Bildschirm -Profileinstellung bleibt weiß, sodass keinerlei Eintellungen für die Verknüpfung eingestellt werden können. 
In der Liste der direkten Verküpfungen wird diese "fehlerhafte" Verknüpfung angezeigt. Nach dem Button "Bearbeiten" kommt jedoch weiterhin nur eine leere Seite.

![grafik](https://github.com/user-attachments/assets/dba563f9-3af7-45c2-8c8d-cf2d1dbb6042)

![grafik](https://github.com/user-attachments/assets/4a771e19-3d72-4ce7-a4e4-4a650ac57b9f)

Raspberry Firmwareversion: 3.79.6.20241031

Dieses Problem tritt nur bei einem einzigen Dimmaktor in Verbindung mit einer Direktverknüpfung mit beliebigen Bewegungsmeldern auf. 
Eine Direktverknüpfung dieses Dimmaktors mit einem Taster ist problemlos möglich.

Lösungversuche: Werkseinstellung des Dimmaktor, Löschen des Dimmaktors in CCU3 + Neuanlernen. Werkseinstellung des DRAP, Direktverknüpfung mit einem anderen der 3 Kanäle des Dimmaktors.
alles mit und ohne Neustarts der RaspberryMatic bringen keinen Erfolg. 

Ich freue mich sehr über Ideen zur Problemlösung.

Vielen Vielen Dank!

### Describe the behavior you expected

Ich erwarte, dass ich nach der Erstellung einer Direktverknüpfung in den Profileinstellungen Auswahlmöglichkeiten sehe, die ich verändern kann. siehe expl. Bild

![grafik](https://github.com/user-attachments/assets/5d095eb9-bfe5-4692-82ee-ca760dc10f71)

### Steps to reproduce the issue

1. Ich erstelle eine Direktverknüpfung mit Bewegungsmelder A oder B oder C mit Dimmaktor A mit Kanal 2, 6 oder 10  - ich sehe keine Profileinstellmöglichkeiten
2. Ich erstelle eine Direktverknüpfung mit Bewegungsmelder A oder B oder C mit anderem Dimmaktor B - alles funktioniert
3. Ich erstelle eine Direktverknüpfung mit Taster und dem Dimmaktor A - alles funktioniert
...

### What is the version this bug report is based on?

3.79.6.20241031

### Which base platform are you running?

tinkerboard (ASUS Tinkerboard, ARM/armhf)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
no
```

**Comment by jp112sdl** [comment]
Siehe #2887
