### ISSUE TITLE
Homeassistant Proxy Addon [FATAL tini (7)] exec /app/entrypoint.sh failed: Exec format error

### ISSUE THREAD

**Issue by pvillmann** [jens-maus/RaspberryMatic#2920]
### Describe the issue you are experiencing

Hi,

i've installed the HomeAssistant Proxy Addon for Raspberrymatic.
i just installed, set the ip address of Raspberrymatic and started the addon.

Log File:
[FATAL tini (7)] exec /app/entrypoint.sh failed: Exec format error

:)

### Describe the behavior you expected

Addon should be started

### Steps to reproduce the issue

1. Install Raspberrymatic Proxy Addon on Homeassistant
2. Start Addon
3.
...

### What is the version this bug report is based on?

Homeassistant 2024.11.2

### Which base platform are you running?

ova (Open Virtual Infrastructure, AMD64/x86_64)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
[FATAL tini (7)] exec /app/entrypoint.sh failed: Exec format error
```

**Comment by jens-maus** [comment]
Sorry, but that new Proxy addon is not yet ready. That's why it is flagged as "experimental". Thus, please wait until is it done and properly announced and distributed...

**Comment by pvillmann** [comment]
no problem, is see the flag :)

**Comment by jens-maus** [comment]
So, now the 0.3.0 version of the RaspberryMatic Proxy HA-Addon should work as expected and has left its experimental status. So please give it a try and enjoy to link your RaspberryMatic CCU into HA...
