### ISSUE TITLE
GUI-footer no function

### ISSUE THREAD

**Issue by timmertechnik-RTI** [jens-maus/RaspberryMatic#2921]
### Describe the issue you are experiencing

Using the GUI on a 5120x1440 resolution, half the screen (left or right also using 2560x1440) the footer buttons don't work. Cursor doesn't change from arrow to select (pointing hand). Equal if using Chrome ore Edge. First noticed in this version (3.79.6.20241031)

### Describe the behavior you expected

Should work as usually

### Steps to reproduce the issue

1.
2.
3.
...
-

### What is the version this bug report is based on?

3.79.6.20241031

### Which base platform are you running?

tinkerboard (ASUS Tinkerboard, ARM/armhf)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
-
```

### Additional information

-

**Comment by jens-maus** [comment]
Provide a Screencast please.

**Comment by timmertechnik-RTI** [comment]
Sorry to have bothered you. 

Preparing for the Screencast I turned off HDR, from then the failure was gone. Turned it on again and everything was still OK.

When I think about it, this behavior must be related to the issue I have every now and then, related to show and hide the Taskbar. This is a Windows issue and have nothing to do with the GUI (or WebUI, as you call it).

Keep on doing the good work!
