### ISSUE TITLE
Anzeigefehler GUI Hysterese HmIP-WTH-2 & Heizgruppe

### ISSUE THREAD

**Issue by franky1275** [jens-maus/RaspberryMatic#2929]
### Describe the issue you are experiencing

In der GUI kann man für HmIP-WTH-2 und die Heizgruppe eine Hysterese einstellen
Sobald diese auf 0.6K gestellt wird, wird in der GUI allerdings 0.2K angezeigt.
Gesetzt wird die Hysterese aber korrekt auf 0.6K (laut devconfig)

### Describe the behavior you expected

Korrekte Anzeige der Hysterese

### Steps to reproduce the issue

1. Hysterese Einstellungen des  HmIP-WTH-2 auf 0.6K stellen
2. Überprüfen der Anzeige => GUI zeigt 0.2K , devconfig zeigt 0.6K
3.
...

### What is the version this bug report is based on?

3.79.6.20241031

### Which base platform are you running?

rpi3 (RaspberryPi3, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
n/a
```

**Comment by jens-maus** [comment]
Screenshots bzw screencast bitte dazu zeigen!

**Comment by franky1275** [comment]
Sorry, hatte vergessen die Bilder anzuhängen:


![devconfig](https://github.com/user-attachments/assets/9a1d2fce-b2e9-4e31-9c8a-4d4337afc3c3)
![GUI](https://github.com/user-attachments/assets/49270840-421b-4948-9375-eb34aa0b222a)

**Comment by jens-maus** [comment]
Danke, kann das selber auch entsprechend reproduzieren. Komisch ist in der Tat das wohl nur die Einstellung 0.6K nicht funktioniert. Wenn man 0.4K einstellt wird die übernommen und auch in der WebUI korrekt dargestellt. Riecht stark nach einem Rundungsfehler oder so.

@Baxxy13 Kannst du das mal vielleicht selbst testen und reproduzieren? Und vielleicht findet @jp112sdl ja fix die Ursache vor dem nächsten Release :)

**Comment by Baxxy13** [comment]
> nur die Einstellung 0.6K nicht funktioniert

1.6K wird am Ende auch als 0.2K dargestellt.
Gesetzt werden aber alle 10 möglichen Werte korrekt im Thermostat bzw. Gruppengerät.

```tcl
  set param TWO_POINT_HYSTERESIS
  if {[info exists ps($param)] == 1} {
    incr prn
    if {$climateFunction == 0} {set paramVisibility ''} else {set paramVisibility 'hidden'}
    array_clear options
    for {set val 0.0} {$val <= 2.0} {set val [expr $val + 0.2]} {
        set options($val) "$val K"
    }
    append html "<tr id='twoPointHysteresis' class=$paramVisibility>"
      append html "<td>\${stringTableSwitchTransmitTwoPointHysteresis}</td>"
      if {$onlyHeatingCooling == 0} {
        append html  "<td>[getOptionBox '$param' options $ps($param) $chn $prn]&nbsp;[getHelpIcon $param\_A]</td>"
      } else {
        append html  "<td>[getOptionBox '$param' options $ps($param) $chn $prn]&nbsp;[getHelpIcon $param]</td>"
      }
    append html "</tr>"
  }
```
