### ISSUE TITLE
CloudMatic Konfigurationsseite zeigt nur HTML Quellcode

### ISSUE THREAD

**Issue by tobiman64** [jens-maus/RaspberryMatic#293]
Guten Morgen Zusammen,

ich habe gestern zeitnah auf die neue RaspberryMatic umgestellt und der Update über "rmupdate" hat schnell und problemlos funktioniert. Er nach mehreren Stunden bei dem ersten Versuch über Handy zuzugreifen fiel mir auf, das ich keine Verbindung zu meiner Raspberry über VPN von Cloudmatic aufbauen konnte.

Bei Kontrolle in der WebUI und dem Versuch über Systemsteuerung / Zusatzsoftware auf die CloudMatic Seite zu kommen, wurde mir lediglich der Quellcode angezeigt, aber nicht wie gewohnt das Dashboard von CloudMatic angezeigt.

Nachdem ich wieder auf die Vorgängerversion von RaspberryMatic zurück gegangen bin, lief alles wieder wie gewohnt.

Im Forum habe ich gesehen, das ich nicht der einzige Anwender bin, der dieses Problem hat, aher eröffne ich diesen Issue und bitte um Hilfe, da ich gerne auf die neue Version gehen möchte.
https://homematic-forum.de/forum/viewtopic.php?f=65&t=42897&start=20#p426993
https://homematic-forum.de/forum/viewtopic.php?f=65&t=42897&start=30#p427034
https://homematic-forum.de/forum/viewtopic.php?f=65&t=42897&start=30#p427084

Ich werde heute im Laufe des Tages mal versuchen über das Flashen einer micro-SD Karte auf die neue Version zu wechseln und berichten.

Danke und Gruss
Tobias

**Comment by jens-maus** [comment]
Konnte das Problem bereits verifizieren und habe dazu auch bereits eine Lösung erarbeitet nur noch nicht ganz verstanden warum diese nun notwendig ist. Daher bitte folgenden Patch testen:

```patch
--- /opt/mh/www/index.cgi
+++ /opt/mh/www/index.cgi
@@ -19,8 +19,7 @@ set register_pending unknown
 set content [::HomeMatic::Util::LoadFile "/etc/config/addons/mh/register_pending"]
 catch { [regexp -line {status=(.*)} $content dummy register_pending] }
 
-puts {
-<!DOCTYPE html>
+puts { <!DOCTYPE html>
 <html>
   <head>
     <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection">
```

D.h. bitte mal in Zeile 23 in der Datei /opt/mh/www/index.cgi das `<!DOCTYPE html>` eine Zeile hochziehen hinter das `puts {`

Bitte Rückmeldung geben ob damit ALLE Probleme mit CloudMatic dann beseitigt sind.

**Comment by tobiman64** [comment]
Hallo Jens,

ich habe jetzt wieder die neue RaspberryMatic Version installiert und versucht wie von dir beschrieben die Datei Index.cgi zu ändern.

Bekomme aber dabei die folgende Fehlermeldung, obwohl ich eigentlich der Meinung war, mich als root anzumelden im SSH.

![grafik](https://user-images.githubusercontent.com/36469596/37874115-ab71d016-3028-11e8-9c76-eee609d5191a.png)

Was mache ich falsch?

**Comment by tobiman64** [comment]
Hier noch ein Screenshot des Verzeichnisses mit allen Angaben:

![grafik](https://user-images.githubusercontent.com/36469596/37874132-41acddfa-3029-11e8-9f21-2d27fb4648ac.png)

**Comment by jens-maus** [comment]
Es sollte doch hinlänglich bekannt sein das das rootfs standardmäßig read-only geschalten ist. D.h. Du musst vorher via ``mount -o rw,remount /` das rootfs beschreibbar machen und danach wieder via `ro` read-only schalten.

Das alles macht aber nur sinn wenn du natürlich die neueste RaspberryMatic installiert hast die das Problem zeigt.

**Comment by tobiman64** [comment]
Hallo Jens,

kaum macht man es richtig, funktioniert es auch.

Nachdem ich jetzt die "index.cgi" nach deinen Vorgaben angepasst habe, funktioniert sowohl in der WebUI der Zugriff auf die CloudMatic Konfigseite, als auch der Zugriff über CloudMatic/VPN vom Handy aus.

Vielen Danke für die tolle Hilfe Jens.

Gruss
Tobias

**Comment by MichaelGJett** [comment]
Kann ich bestätigen, nach der o.g. Änderung funktioniert der Webseitenaufruf.

**Comment by widmann-it** [comment]
Ich kann auch bestätigen das der Webseitenaufruf wieder klappt über Cloudmatic :-)

**Comment by darkbrain85** [comment]
Ja, klappt! Hast Du mittlerweile herausgefunden warum das so ist? Ein bisschen merkwürdig ist das ja schon...

**Comment by jens-maus** [comment]
@darkbrain85 Nicht wirklich. Meine Vermutung ist das sich etwas im Webserver geändert hat und er nun die Header&Co anders ausliefert und die Art der Ausgabe (1x mit Newline, 1x ohne) dann dazu führt das das HTML Tag eben abgeschnitten wird wenn man es so ausgibt.

**Comment by jens-maus** [comment]
Inzwischen wurde mir von Easy-Smarthome mitgeteilt das meine hier dargelegten Modifikationen am CloudMatic Addon übernommen wurden und auch in das AutoUpdate integriert wurden das durch das AutoUpdate von CloudMatic die Webseiten auf allen Systemen die CloudMatic bereits nutzen ausgeliefert werden sollten.

**Comment by ric-hermann** [comment]
Hallo,

habe das gleiche Problem wie in "CloudMatic Konfigurationsseite zeigt nur HTML Quellcode #293"... Allerdings habe ich die genannte Datei index.cgi gecheckt und den Fehler nicht gefunden. Woran kann das liegen? Version 20190223
