### ISSUE TITLE
Homematic HM-LC-Sw1-DR Schaltaktor: Parameter Aktion bei Spannungszufuhr fehlt

### ISSUE THREAD

**Issue by joe1678** [jens-maus/RaspberryMatic#2931]
### Describe the issue you are experiencing

Für den Schaltaktor HM-LC-Sw1-DR fehlt in der Parameterliste die Auswahl "Aktion bei Spannungszufuhr". Laut Doku von ELV gibt es diese Auswahl jedoch für das Gerät.

### Describe the behavior you expected

In der Parameterliste des Gerätes die Auswahl "Aktion bei Spannungszufuhr" ergänzen.

### Steps to reproduce the issue

1.
2.
3.
...

### What is the version this bug report is based on?

3.79.6.20241031

### Which base platform are you running?

rpi4 (RaspberryPi4, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
no
```

**Comment by friedpa** [comment]
Ich habe in meinem System nachgeschaut:

![image](https://github.com/user-attachments/assets/11cdfe31-f3f7-4550-86c8-8b4190f3d929)

**Comment by joe1678** [comment]
Genau dieser Parameter wird bei mir nicht angezeigt.

![grafik](https://github.com/user-attachments/assets/6851ba17-f216-4012-9eb4-0df6477a36de)

**Comment by jens-maus** [comment]
Liegt das vielleicht an der Firmware? Mein HM-LC-Sw1-DR hat die Firmwareversion 2.7 und deiner wird hier mit 2.8 angezeigt? Wo kommt die eigentlich her? Bei https://jp112sdl.github.io/HMDeviceFirmware/ bzw. https://github.com/jp112sdl/HMDeviceFirmware finde ich die nicht!?! Vielleicht weiss @jp112sdl diesbzgl. mehr?

**Comment by jp112sdl** [comment]
Nein, liegt nicht an der Firmware. Vielleicht am "Einfach" Modus.

**Comment by jens-maus** [comment]
> Nein, liegt nicht an der Firmware. Vielleicht am "Einfach" Modus.

Das ist ein guter Hinweis.. Dieser "Kinder-Modus" in der WebUI geht mir so langsam auf die Nerven.. Vielleicht sollte man den ohnehin mal entfernen weil jeder der die CCU/RaspberryMatic nutzt ohnehin ein "Experte" ist? ;-)

**Comment by jp112sdl** [comment]
Ja, ich wäre auch dafür, dass es nur noch den Expert-Only Modus gibt

**Comment by joe1678** [comment]
Mit Deaktivierung der Option "Modus vereinfachte Verknüpfungskonfiguration aktivieren" in der Benutzerverwaltung erscheint der vermisste Parameter. Wenn man diesen wie gewünscht setzt und anschließend die Option wieder aktiviert, bleibt die zuvor getroffene Wahl des Parameters erhalten, aber eben ausgeblendet. Ich würde das daher als kleinen Bug sehen.

Danke für eure Unterstützung

**Comment by jens-maus** [comment]
> Ich würde das daher als kleinen Bug sehen.

Wieso sollte das ein "Bug" sein? Du aktivierst doch den "Vereinfachten" Modus (auch Kinder-Modus genannt) und sagst damit der CCU/RaspberryMatic WebUI das du kein "Experte" bist und daher Parameter/Optionen die dich verwirren könnten bitte ausgeblendet werden sollten. Wie schon erwähnte, ist das ganze Konstrukt rund um diesen Kinder-Modus vs. Experten-Modus nicht ganz schlüssig aus heutiger sicht und sollte IMHO entfernt werden (@Baxxy13 Meinung?). Für dich bedeutet das aber: Lass den Experten-Modus an damit du nicht wieder in die selber Verwirrung rennst, denn das ist kein Bug in RaspberryMatic oder WebUI, sondern ein Missverständnis deinerseits.

**Comment by joe1678** [comment]
@jens-maus: Ok, mach ich so. Vielen Dank, mein Problem ist damit gelöst.

**Comment by Baxxy13** [comment]
Also von mir aus kann der vereinfachte Modus auch weg. Das dürfte aber nicht allen gefallen. 
Warum drehen wir den Spieß nicht um und machen den "Expertenmodus" zum default?
Wirkt dann zwar nur bei Neuinstallationen, aber besser als nichts. 

Ansonst hat ja eQ-3 irgendwann entschieden welche Parameter im einfachen Modus ausgeblendet werden. 
Wenn wir da jetzt anfangen dran rum zu schrauben ist das ein Fass ohne Boden.
