### ISSUE TITLE
Bad Gateway in Home Assistant

### ISSUE THREAD

**Issue by SeriousPat** [jens-maus/RaspberryMatic#2932]
### Describe the issue you are experiencing

I have still the Bug in HA.
I can Access the GUI inside HA. After some Time/Days i want access again the GUI, the Bad Gateway Error occurs.
Like in : https://github.com/jens-maus/RaspberryMatic/issues/2720
If i restart the Addon, i cann access the Gui again for some time.
I allready tried reinstalled the whole AddOn.

### Describe the behavior you expected

I can allways acces the Raspberrymatic GUI inside HA.

### Steps to reproduce the issue

...

### What is the version this bug report is based on?

3.79.6.20241031

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Identifying host system: QEMU Standard PC (Q35 + ICH9, 2009) (oci), OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Running seedrng: OK
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.1, OK
Identifying Homematic RF-Hardware: ....HmRF: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-0000:00:07.0-1, HmIP: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-0000:00:07.0-1, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: 4.4.18, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: .......OK
Starting rfd: .OK
Starting HMIPServer: .........OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.79.6.20241031 (raspmatic_oci_amd64)
```

**Comment by jens-maus** [comment]
Sorry, but this must be a different issue than #2720. So please enable ssh and next time the issue happens report back to analyze the issue or if someone else come up with the same or a similar issue. But for now this isn't reproducible by me, I am afraid.

**Comment by SeriousPat** [comment]
> Sorry, but this must be a different issue than #2720. So please enable ssh and next time the issue happens report back to analyze the issue or if someone else come up with the same or a similar issue. But for now this isn't reproducible by me, I am afraid.

Alles klar, ich kann mich auch melden wenn der Fehler wieder da ist und wir können im Jitsi oder sonst wo gemeinsam drauf schauen wenn du mal Zeit hast.

**Comment by SeriousPat** [comment]
Es ist sowet.
Am Samstag hatte ich HA komplett neugestartet (ganze VM). Heute 2 Tage später ist der fehler da. Gestern Abend ging es noch.
![image](https://github.com/user-attachments/assets/872deaae-6343-45cf-ba83-bbff5c3a9fe2)

**Comment by jens-maus** [comment]
Hast du in den Add-on settings bei den Netzwerk-Ports den Port 80 unter einem anderen Port (z.B. 8080) exposen lassen um darauf von extern auch zugreifen zu können? Und wie steht es mit SSH Add-on? Hast du das installiert um die situation zu debuggen?

**Comment by SeriousPat** [comment]
Ne, das mit dem Port habe ich noch nicht ausprobiert.  Kann ich machen,  aber dann muss ich das add on neustarten und dann geht es erst wieder.  Ssh add on ist drauf,  muss ich nur starten. Ist aber nicht msg außen (internet) freigegeben. Hab dir meine handy nr per mail geschickt.

**Comment by jens-maus** [comment]
> Ne, das mit dem Port habe ich noch nicht ausprobiert. Kann ich machen, aber dann muss ich das add on neustarten und dann geht es erst wieder. Ssh add on ist drauf, muss ich nur starten.

Dann mach doch mal ein SSH auf den HA Host und versuch mit `docker exec -it XXXXX /bin/sh`, usw. in den RaspberryMatic Container reinzukommen um zu schauen was da so alles läuft.

> Ist aber nicht msg außen (internet) freigegeben. Hab dir meine handy nr per mail geschickt.

Sorry, aber für den direkten Support fehlt mir die Zeit. Da musst du selbst Hand anlegen.

**Comment by SeriousPat** [comment]
Hi Jens, meine Backup-Routine kam mir dazwischen und hat die HA-VM neugestartet. Ich habe aber dann jetzt mal den Port des AddOns auf 8080 geändert. Nach ca. 2 Tagen habe ich den beschriebenen Fehler innerhalb der HS Gui aber über 8080 kann ich die RPIMatic Gui weiterhin aufrufen.

**Comment by jens-maus** [comment]
Das ist insofern "gut", denn das bedeutet nur der haproxy.js Dienst schmiert dann ab. Ist das System jetzt noch in dem Status? Denn dann könntest du ein paar Tests dran machen.

**Comment by SeriousPat** [comment]
Ja ist es. Morgen nachmittag kann ich mich dran setzen.  Was soll ich überprüfen?

**Comment by jens-maus** [comment]
Schalte bitte den SSH Zugang frei damit du von aussen via SSH auf die Zentrale kommst und dann geb mal folgende Befehle ein:

```
ps aux | grep ha-proxy
```

```
cat /var/run/ha-proxy.pid
```

**Comment by SeriousPat** [comment]
Ich bin mal über VNC rein.
Direkt zu beginn:
![image](https://github.com/user-attachments/assets/de4416c7-c0f7-42f6-846f-ad8bec7e7133)

Hier die Rückgabe der befehle
![image](https://github.com/user-attachments/assets/f4dd1048-3b60-454a-bdb4-ff35770f9f41)

**Comment by jens-maus** [comment]
Uiui. Das sieht nach zu hohem Speicherverbrauch aus der dann dazu führt das HomeAssistant meint Prozesse zu killen und wohl auch den `ha-proxy` dienst innerhalb von RaspberryMatic.

**Comment by SeriousPat** [comment]
Ich hatte der VM nur 2 GB Ram zugewiesen. Habe mich schon gewundert das er in HA sagt er würde nur 0,7 GB Ram davon nutzen.
Ich habe nun mal 8 GB Ram vergeben. Jetzt gibt er nach dem starten bereits 1,4GB in Nutzung an. Ich melde mich in 2 oder mehr Tagen ob der Fehler erneut auftaucht.

**Comment by SeriousPat** [comment]
Das scheint es gewsen zu sein. Bisher trat der Fehler nicht mehr auf.
