### ISSUE TITLE
Zeitverzögerung innerhalb eines Programmes lässt sich nicht einstellen

### ISSUE THREAD

**Issue by hugo18192** [jens-maus/RaspberryMatic#2935]
### Describe the issue you are experiencing

Beim Einstellen einer Zeitverzögerten Aktion werden Zeiteinheit und Wert nicht angenommen.

### Describe the behavior you expected

Gewählte Zeiteinheiten und Werte sollen angenommen werden.

### Steps to reproduce the issue

Verweise auf Issues #1832. Hier wird das Ganze im Video sehr gut beschrieben.

Selbes verhalten auch in der vor Version.

### What is the version this bug report is based on?

3.79.6.20241122

### Which base platform are you running?

ova (Open Virtual Infrastructure, AMD64/x86_64)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
no
```

https://github.com/user-attachments/assets/b400b297-416b-4a66-b2bf-274bb2148cef

**Comment by jens-maus** [comment]
Bitte Screenshot und screencast nachliefern um das Problem zu demonstrieren

**Comment by Baxxy13** [comment]
Trag einfach erst die Zeit ein und dann wähle die Einheit.

**Comment by MichaelN0815** [comment]
Faszinierend. Aber eben vollkommen logisch. 0 Minuten oder auch 0 Stunden, sind eben 0 Sekunden.

**Comment by hugo18192** [comment]
Früher konnte man erst die einheit wählen und dann die Zeit.
