### ISSUE TITLE
"Device constant" cannot be changed on HmIP-ESI (10000 imp/kwh -> 1000 imp/kwh)

### ISSUE THREAD

**Issue by oszczech** [jens-maus/RaspberryMatic#2937]
### Describe the issue you are experiencing

When opening the device setting page (of  HmIP-ESI + "ES-LED") and detecting the sensor a default value of "10000" is set for the "device constant"
This value is not correct as some/my smartmeter only output at a rate of 1000 imp/kwh

When I try to change the value to "1000" and apply, it briefly shows up as "1000.00", but changes quickly back to "10000" after a refresh

could be realted to issue #2712 

video:
[Screencast_20241125_155923.webm](https://github.com/user-attachments/assets/6ad59dce-b742-4a84-ae7c-8bbe8058e28b)

### Describe the behavior you expected

The device constat will be changed to 1000 imp/kwh and show the correct values in homeassistant

### Steps to reproduce the issue

1. go to HmIP-ESI/ES-LED setting
2. change device constat value to 1000
3. click apply/ok
4. reload -> wrong setting

### What is the version this bug report is based on?

3.79.6.20241122

### Which base platform are you running?

rpi5 (RaspberryPi5, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
I do not see any related logs in the homematic addon page in homeassistant.
```

**Comment by jens-maus** [comment]
Bitte mal folgenden Patch lokal anwenden um zu verifizieren das damit das Problem seitigt sein sollte:

```patch
--- /www/config/easymodes/etc/uiElements.tcl
+++ /www/config/easymodes/etc/uiElements.tcl
@@ -297,9 +297,12 @@ proc getTextField {param value chn prn {extraparam ""} {superExtra ""}} {
       set maxValue "stringUTF8"
       set maxLength "maxLength=16"
       set sizeTextfield 16
-    } elseif {($param == "METER_CONSTANT_VOLUME") || ($param == "METER_CONSTANT_ENERGY")} {
+    } elseif {($param == "METER_CONSTANT_VOLUME")} {
       set minValue [format {%1.2f} $param_descr(MIN)]
       set maxValue [format {%1.2f} $param_descr(MAX)]
+    } elseif {($param == "METER_CONSTANT_ENERGY")} {
+      set minValue [format {%1.0f} $param_descr(MIN)]
+      set maxValue [format {%1.0f} $param_descr(MAX)]
     }
   }
 
```

**Comment by oszczech** [comment]
Funktioniert jetzt bei mir.

vielen Dank für die sehr schnelle Lösung :)

**Comment by jens-maus** [comment]
Stopp mal. Das ist hier kein Diskussionsforum wo man den Beitrag einfach schließst wenn man selbst das Problem beseitigt hat. Die Frage war ja eigentlich recht klar: Löst der vorgeschlagene Patch das Problem? Wenn ja muss hier erst das problem auch für den nächsten Release beseitigt werden und DANN schließst man dieses Ticket hier.

Ergo, also bitte beantworten ob du diesen Patch jetzt selbst temporär angewendet hast und wenn ja, dann kann ich das für den nächsten Release auch so einbauen und erst dann wird das permanent beseitigt sein.

**Comment by jens-maus** [comment]
@Baxxy13 Hast du einen HmIP-ESI und kannst meinen "Fix" von hier vielleicht verifizieren?

**Comment by jens-maus** [comment]
Ok, dann müsstest sich bitte der ursprünglich Autor dieses Reports hier (@oszczech) noch einmal zu Wort melden, ansonsten bleibt es vmtl. so wie es ist und dann wird mit der nächsten offiziellen Version das Problem auch bei ihm wieder auftauchen...

**Comment by oszczech** [comment]
Wie gesagt, es funktioniert bei mir mit den vorgeschlagenen Änderungen. Ich habe es manuell im homeassistant addon Container über SSH geändert und konnte nach dem Neustart des Containers den Wert am HmIP-ESI ändern.

Sorry fürs schließen. War nicht absicht, ich nutze github sonst nicht als issue tracker
