### ISSUE TITLE
Q: Startreihenfolge der Skripte in /etc/config/rc.d

### ISSUE THREAD

**Issue by jp112sdl** [jens-maus/RaspberryMatic#294]
Nabend!

Nur kurze Frage: 
Werden die Skripte in `/etc/config/rc.d` beim Booten parallel gestartet, oder nacheinander?

**Comment by jens-maus** [comment]
Nacheinander anhand der Standard-Sortierreihenfolge. Es kann daher z.B. von Vorteil sein dort abgelegte Skripte wie init-skripte zu benennen. Z.B.

```
0001-skript1.sh
0002-skript2.sh
````

**Comment by jp112sdl** [comment]
Ok, danke, dann muss ich den Fehler an anderer Stelle suchen.

Folgendes Problem:
Die Addon-Installation (selbst gebaut) klappt soweit - alles schick.

Wenn aber das Addon nach dem Einspielen einer Backup-Datei re-installiert werden soll, fehlt die Hälfte.

Was ich im Installskript, aufgerufen aus rc.d, mache ist ein:
```
mount -o remount,rw /
cp -a firmware/rftypes/* /firmware/rftypes/
cp -ar www/config/img/devices /www/config/img/
...
mount -o remount,ro /
```

Spiele ich ein Backup auf eine frisches RaspberryMatic-Image ein, liegt meine Custom-Firmware-XML in /firmware/rftypes/, aber die Images in /www/config/img/ fehlen.
Wie gesagt - bei normaler Addon-Installation zur Laufzeit geht es.
Dabei wird auch zunächst nur das Addons selbst ins Dateisystem kopiert und beim Reboot dann mittels rc-Skript (nach Prüfung auf Fehlen bestimmter Dateien) installiert.

Nun war meine Vermutung, dass evtl. andere Skript in /etc/config/rc.d parallel laufen.
Wie z.B. XML-API oder CUxD, die in ihren Startskripten auch das Dateisystem kurz `rw` und dann `ro`mounten und mir quasi die Schreibberechtigung mitten in meinem Skript entziehen.

**Comment by jp112sdl** [comment]
P.S.: 
Ich habe eben beim Booten gesehen, dass 2 Prozesse, die aus 2 verschiedenen Start-Skripten in /etc/config/rc.d gestartet werden, gleichzeitig in `top` zu sehen waren. 

Heißt das also, dass die Skripte zwar in Reihenfolge
```
0001-skript1.sh
0002-skript2.sh
```
gestartet werden, jedoch **nicht** mit der Ausführung von `Skript2` gewartet wird, bis `Skript1` beendet ist?

Das wäre dann wirklich ein Problem, da von vielen Addons offensichtlich das root-fs gern mal `rw` / `ro` gemountet wird und sich dadurch dann Prozesse in die Quere kommen könnten.

**Comment by jens-maus** [comment]
Nein, das sollte definitiv nicht passieren. Verlinke mal bitte hier direkt deine start skripte die du da in /etc/config/rc.d legst. Du hast sicherlich nur irgendein Flüchtigkeitsfehler gemacht.

**Comment by jp112sdl** [comment]
Den Flüchtigkeitsfehler kann ich wirklich nicht ausschließen.
Vielen Dank fürs Drüberschauen.

Es geht um 2 Addon-Installation die sich in die Quere kommen:

Zum Einen der 8fach Universal-Temperatursensor:
Dessen [rc-Skript](https://github.com/jp112sdl/HB-UNI-Sen-TEMP-DS18B20/blob/master/Addon/HB-UNI-Sen-TEMP-DS18B20-addon-src/rc.d/hbunisentemp) ruft jenes [Installationsskript](https://github.com/jp112sdl/HB-UNI-Sen-TEMP-DS18B20/blob/master/Addon/HB-UNI-Sen-TEMP-DS18B20-addon-src/addon/install) bei Bedarf auf.

Zum Anderen der künftige Bodenfeuchtesensor:
Dessen [rc-Skript](https://github.com/jp112sdl/HB-UNI-Sen-CAP-MOIST/blob/master/Addon/HB-UNI-Sen-CAP-MOIST-addon-src/rc.d/hbunisencapmoist) ruft dieses [Installationsskript](https://github.com/jp112sdl/HB-UNI-Sen-CAP-MOIST/blob/master/Addon/HB-UNI-Sen-CAP-MOIST-addon-src/addon/install) bei Bedarf auf.

Wo ich gerade hier diesen Text schreibe - 
ist mein Flüchtigkeitsfehler evtl. das `&` in [#L18](https://github.com/jp112sdl/HB-UNI-Sen-TEMP-DS18B20/blob/6c29246fb17062fb3c7cde4b870ba567086a5da9/Addon/HB-UNI-Sen-TEMP-DS18B20-addon-src/rc.d/hbunisentemp#L18) des rc-Skripts?
Dadurch wird ja das Installationsskript im Hintergrund ausgeführt und das rc-Skript beendet sich sofort.

Ich setze an der Stelle heut Abend mal an.

**Comment by jens-maus** [comment]
Genau sowas wird es sein. Das & darfst du in dem Kontext natürlich nicht nutzen

**Comment by jens-maus** [comment]
Übrigens möchte ich noch einem betonen, das es trotzdem nicht so eine gute idee ist dinge im rootfs zu installieren (via rw remount). Es wäre besser du könntest z.b. Einen pullrequest bzw patch gegen die WebUI/RaspberryMatic  ausarbeiten das man z.b. Die rftypes+images im userspace speichern kann und die webui die notwendigen daten da findet.

**Comment by jp112sdl** [comment]
> Es wäre besser du könntest z.b. Einen pullrequest bzw patch gegen die WebUI/RaspberryMatic ausarbeiten das man z.b. Die rftypes+images im userspace speichern kann und die webui die notwendigen daten da findet.

Da gebe ich dir grundsätzlich recht. 
Jedoch wäre dann die Kompatibilität zur CCU2 nicht mehr gegeben, oder sehe ich das falsch?

Zumindest beim `rfd` hatte ich zunächst gedacht, man könnte die rftypes-xml im user space ablegen, da beim Starten folgende Meldung kommt:
```
# /bin/rfd -f /etc/config/rfd.conf -c -l 0
2018/03/29 07:25:04.755 <Info> BidCoS-Service started
2018/03/29 07:25:04.762 <Info> XmlRpc Server is listening on TCP port 2001
2018/03/29 07:25:04.769 <Warning> opendir(/etc/config/firmware//) failed
...
```

Ich habe das Verzeichnis mal angelegt und auch einen Unterordner `rftypes` jedoch wird aus keinem der beiden Verzeichnisse die XML geladen.
Dort werden wohl lediglich Gerätefirmware-Updates abgelegt.

**Comment by jens-maus** [comment]
Was die CCU2/CCU3 angeht so würde mitunter eq3 ja solch ein Patch dann irgendwann in ihre Firmware übernehmen wenn diese Anpassungen im Zuge des RaspberryMatic Projektes ausreichend anklangt gefunden und getestet wurden.

**Comment by jens-maus** [comment]
Auf jedenfall sind llte man hier mal ein Issue als Feature Request aufmachen und technisch beschreiben was man will und an welchen Stellen Anpassungen geschehen müsste damit solch projekte wie deine kein rw remount mehr machen müssten.

**Comment by jp112sdl** [comment]
> Auf jedenfall sind llte man hier mal ein Issue als Feature Request aufmachen und technisch beschreiben was man will und an welchen Stellen Anpassungen geschehen müsste damit solch projekte wie deine kein rw remount mehr machen müssten.

Ja, das sollten wir mal angehen. 

<hr> 

Ich konnte die `&`-Modifikation soeben doch schon mal testen und nun funktioniert alles korrekt, auch nach dem Einspielen eines Backups.

Dann mache ich hier das Ticket zum ursprünglichen Thema erstmal zu.

Vielen Dank für die Tipps und Unterstützung!
