### ISSUE TITLE
crontab -e only works till next restart

### ISSUE THREAD

**Issue by Mitch187** [jens-maus/RaspberryMatic#2947]
### Describe the issue you are experiencing

Hallo,

ein crontab -e Eintrag fliegt immer aus der Tabelle, wenn ich den Raspberry PI neu starte.

Wo muss ich die Änderung einfügen, damit der Eintrag erhalten bleibt?

Ich möchte nicht die Möglichkeit nutzen, Skripte über deas CCU-Webadminpanel auszuführen. Sondern direkt per Console.

Gruss,
Mitch

### Describe the behavior you expected

restart

### Steps to reproduce the issue

1. restart
2. crontab entry missing

### What is the version this bug report is based on?

3.77.7.20240826

### Which base platform are you running?

rpi0 (RaspberryPi, ARM/armhf)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
see above
```

**Comment by Baxxy13** [comment]
Du kannst deine eigenen Cron-Jobs in die `/usr/local/crontabs/`root eintragen. 
Das übersteht Reboots und Updates und ist auch Teil des Backups.

**Comment by jens-maus** [comment]
> Du kannst deine eigenen Cron-Jobs in die `/usr/local/crontabs/`root eintragen. 

Genau so ist es. Es ist nicht vorgesehen das nutzer selbst via `crontab -e` aktiv werden. Wie von @Baxxy13 angemerkt einfach die "notwendigen" cron einträge manuell in die Datei `/usr/local/crontabs/root` eintragen. Das ist quasi die crontab Datei der Nutzer. Von den anderen Einträgen lässt man als Nutzer die Finger ;-)

**Comment by Mitch187** [comment]
Ich habe meinen Eintrag in der root Crontab eingefügt, aber er wird nicht ausgeführt (von der normalen crontab übernommen):
0 10 * * * /usr/local/addons/backup.sh > /var/log/backup.log

oder muss ich noch etwas tun?

**Comment by jens-maus** [comment]
Ja, 1x corn daemon neustarten

**Comment by Mitch187** [comment]
Oh, das wusste ich nicht. Das Script nutzt die in RaspberryMatic enthaltene Backup-Funktion um diese sbk Dateien zu erzeugen. Das Backup wird dann auf mein NAS per NFS verschoben, sodass es nicht lokal liegt.

**Comment by jens-maus** [comment]
> Oh, das wusste ich nicht. Das Script nutzt die in RaspberryMatic enthaltene Backup-Funktion um diese sbk Dateien zu erzeugen. Das Backup wird dann auf mein NAS per NFS verschoben, sodass es nicht lokal liegt.

Na genau das kannst du doch out-of-the-box via RaspberryMatic internen funktionen machen die es schon lange gibt. Siehe hier:

https://github.com/jens-maus/RaspberryMatic/wiki/Administration#automatisches-backup-cronbackup-auf-usb-stick--nas-laufwerk
https://github.com/jens-maus/RaspberryMatic/wiki/Experten-Features#individueller-diagrammbackup-speicherpfad

Denn ich mach das genauso mit automatischem nächtlichen Backup auf eine NFS-Freigabe des zentralen NAS. Dafür braucht es kein extra bash skript das man via cron selbst aufruft.
