### ISSUE TITLE
Raspberrymatic auf pi 3 reagiert manchmal nicht mehr

### ISSUE THREAD

**Issue by pekae** [jens-maus/RaspberryMatic#295]
Hallo
Ich poste das erste Mal

Habe ein Problem welches  ich seit der allerneuesten Version mehrfach beobachtet habe. 
In der GUI stehe ich das kreisende Wartesymbol und es werden keine Befehle mehr angenommen- eingefroren 
SSH auf pi zeigt eine geringe CPU Last (<10%) 
Sync dauert Sekunden 
Reboot now gefühlt 30 Sekunden 

Wie kann ich herausfinden wo das Problem liegt ?

**Comment by jens-maus** [comment]
Tschuldigung, das hier ist kein Support Forum, aber ein Bug/Issue-Tracker. Bitte solche Supportdinge bzw. Nutzerbezogenen Probleme im homematic-forum diskutieren.
