### ISSUE TITLE
RaspberryPi3+ does not boot with RaspberryMatric

### ISSUE THREAD

**Issue by IceBoosteR** [jens-maus/RaspberryMatic#296]
Hi,
mit dem ganz neuen RaspberryPi3 Model B+ bootet der Pi nicht. Die rote Lampe leuchtet, die grüne aktivitäts-LED meldet ishc aber nicht. Das Gerät funktioniert super mit Noobs und derselben SD-Karte, aber mit Raspi-Matic wilöl es leider nicht. Ethernet wird auch nicht initialisert und taucht auch dementsprechend nicht als Gerät im Netzwerk auf. Es gibt auch nur einen schwarzen Bildschirmoutput....
Geflash wurde die Karte sowohl mit Etcher, als auch mit Win32DiskImager ...

**Comment by jens-maus** [comment]
Das kann ich so leider nicht bestätigen. Hier funktioniert die aktuellste Version von RaspberryMatic (2.31.25.20180324) problemlos auf den beiden RaspberryPi 3b+ die ich hier zum testen habe.

Wurde auch definitiv die "-rpi3.img" Variante geflasht auf die SD Karte?

**Comment by IceBoosteR** [comment]
Hallo Herr Maus,
Sie dürfen mich ab nun einen "Deppen" nennen ;)
Ich habe tatsächlich die RPI3 Varinte als separate Datei nicht gesehen - Danke für die schnelle Antwort!
Mit der Pi0 Variante werde ich hoffentlich nichts kaputt gemacht haben (macht auch irgendwie keinen Sinn..).
Ich bekomme aber wie Sie diese Meldung:
https://github.com/raspberrypi/linux/issues/2447

Danke für Ihre Arbeit und Support!
-Can be closed due to Layer 8 problem.
