### ISSUE TITLE
Bestehende DV mit HmIP-FDT als Partner lässt sich nicht mehr bearbeiten

### ISSUE THREAD

**Issue by cb53359** [jens-maus/RaspberryMatic#2961]
### Describe the issue you are experiencing

Probleme mit DVs:

1) Zwei bereits lange bestehende DVs:
HmIP-FSM zu HmIP-FDT und
HmIP-SCI zu HmIP-FDT

lassen sich nicht mehr editieren (Klick auf Bearbeiten öffnet leere Seite) analog zu #2887 

Stand: 3.79.6.20241122 UND 3.79.6.20241215 

Neue DVs in diesem Szenario lassen sich korrekt anlegen und auch bearbeiten,

2) Es besteht zudem der Verdacht, dass die DVs unter 3.79.6.20241122 nicht mehr funktionierten. HmIP-FDT war allerdings kurzzeitig wegen Wartungsarbeiten vom Netz getrennt - die Aussage wäre daher noch einmal zu verifizieren. Unter 3.79.6.20241215  funktionieren die DVs jedenfalls korrekt. 

3) Unter  3.79.6.20241215 gibt es eine DV, die keinen "Löschen"-Button mehr hat. DV ist HmIP-PSM:1 zu HmIP-PSM:3. Ob dies auch schon unter 3.79.6.20241122 so war wäre noch zu verifizieren.

### Describe the behavior you expected

Normales Bearbeiten der DV via "Bearbeiten"-Button

### Steps to reproduce the issue

1. Bearbeiten einer bereits bestehenden DV mit HmIP-FDT als Partner
2.
3.
...

### What is the version this bug report is based on?

3.79.6.20241122

### Which base platform are you running?

rpi3 (RaspberryPi3, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
bitte Hinweis
```

### Additional information

Standard-CCU3

**Comment by jens-maus** [comment]
Bitte Screenshots und konkrete Screencasts anfertigen und hier zeigen damit man die vermeintlichen Probleme konkret visuell sehen und verfolgen kann.

**Comment by cb53359** [comment]
https://github.com/user-attachments/assets/d9c3c2b9-85e0-42b8-9b37-79a188755fbe

**Comment by jens-maus** [comment]
Bitte mal auf der Zentrale unter `/usr/local/tmp` nach Dateien mit dem Schema `cgimail.XXXX` schauen und falls existent hier den Inhalt der Datei mit dem aktuellsten Datum posten.

**Comment by cb53359** [comment]
Return-Path: <CGI script - do not reply>
From:  <CGI script - do not reply>
To: root
Subject:  CGI problem

CGI environment:
REQUEST_METHOD: POST
SCRIPT_NAME: /config/ic_setprofiles.cgi
HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
HTTP_HOST: 192.168.178.44
REMOTE_ADDR: 192.168.178.71
cgi.tcl version: 1.10.0
input:
iface=HmIP-RF&sender_address=001E1BE9941BE4%3A1&receiver_address=000E1BE9A7409B%3A3&_=
cookie:
errorInfo:
can't read "ch": no such variable
    while executing
"get_ComboBox options SHORT_ON_MIN_LEVEL separate_${special_input_id}_$prn\_$pref PROFILE_$prn SHORT_ON_MIN_LEVEL "onchange=\"ActivateFreePercent4Inter..."
    (procedure "set_htmlParams" line 94)
    invoked from within
"set_htmlParams $iface $receiver_address receiver_ps ps_descr_receiver "receiver" $dev_descr_sender(TYPE)"
    (procedure "put_profile_body" line 171)
    invoked from within
"put_profile_body "SENDER""
    (procedure "put_page" line 47)
    invoked from within
"put_page"

**Comment by Baxxy13** [comment]
Kurz zu 3.
Das ist schon immer so und völlig normal das automatisch erzeugte "interne" DV's keinen Löschen-Button haben.

**Comment by cb53359** [comment]
Danke Baxxy13, das könnte natürlich sein - störend ist die "Nicht-Löschbarkeit" insofern eh nicht.

**Comment by jens-maus** [comment]
@Baxxy13 @jp112sdl 
Hab mal eine grobe Suche in den Untiefen der WebUI gemacht und folgende Dateien gefunden die potentiell diesbzgl. in Betracht kommen könnten:

```
/www/config/easymodes/DIMMER_VIRTUAL_RECEIVER/WATER_DETECTION_TRANSMITTER.tcl
/www/config/easymodes/DIMMER_VIRTUAL_RECEIVER/PASSAGE_DETECTOR_DIRECTION_TRANSMITTER.tcl
/www/config/easymodes/DIMMER_VIRTUAL_RECEIVER/MULTI_MODE_INPUT_TRANSMITTER_5.tcl
/www/config/easymodes/DIMMER_VIRTUAL_RECEIVER/COND_SWITCH_TRANSMITTER_PARTICULATE_MATTER.tcl
/www/config/easymodes/DIMMER_VIRTUAL_RECEIVER/COND_SWITCH_TRANSMITTER_WIND_SPEED.tcl
/www/config/easymodes/DIMMER_VIRTUAL_RECEIVER/RAIN_DETECTION_TRANSMITTER.tcl
/www/config/easymodes/DIMMER_VIRTUAL_RECEIVER/PASSAGE_DETECTOR_COUNTER_TRANSMITTER.tcl
/www/config/easymodes/DIMMER_VIRTUAL_RECEIVER/COND_SWITCH_TRANSMITTER_RAIN_DROP.tcl
/www/config/easymodes/DIMMER_VIRTUAL_RECEIVER/COND_SWITCH_TRANSMITTER_RAIN_QUANTITY.tcl
/www/config/easymodes/DIMMER_VIRTUAL_RECEIVER/COND_SWITCH_TRANSMITTER_TEMPERATURE.tcl
/www/config/easymodes/DIMMER_VIRTUAL_RECEIVER/SHUTTER_CONTACT.tcl
/www/config/easymodes/DIMMER_VIRTUAL_RECEIVER/MULTI_MODE_INPUT_TRANSMITTER_3.tcl
/www/config/easymodes/DIMMER_VIRTUAL_RECEIVER/COND_SWITCH_TRANSMITTER.tcl
/www/config/easymodes/DIMMER_VIRTUAL_RECEIVER/COND_SWITCH_TRANSMITTER_BRIGHTNESS.tcl
/www/config/easymodes/DIMMER_VIRTUAL_RECEIVER/COND_SWITCH_TRANSMITTER_WIND_DIRECTION.tcl
/www/config/easymodes/DIMMER_VIRTUAL_RECEIVER/COND_SWITCH_TRANSMITTER_HUMIDITY.tcl
```

Bei all diesen Dateien gibt es eine `Disable_SimKey($ch, $prn, '${special_input_id}')` Anweisung die auf die oben gezeigte `get_ComboBox options SHORT_ON_MIN_LEVEL ...` Anweisung folgt. Und bei all diesen Dateien fehlt aber augenscheinlich eine definition der `ch` Variable via `set ch ...`. D.h. die `$ch` Variable ist/sollte in diesen Dateien nicht definiert sein und folglich müsste das ursächlich für diese `can't read "ch": no such variable` Meldung in der gezeigten `cgimail` Ausgabe sein.

Bei anderen ähnlichen Dateien ist die definition von `ch` jedoch gegeben. Siehe:

```
/www/config/easymodes/DIMMER_VIRTUAL_RECEIVER/MULTI_MODE_INPUT_TRANSMITTER_1.tcl
```

Dort taucht dann folgendes auf:

```
set ch $dev_descr_sender(INDEX)
```

Warum/Wieso die `ch` Definition fehlt ist mir noch unklar und ob diese dort fehlt oder man stattdessen diesen `Disable_SimKey()` Aufruf entfernen sollte?!?! 

Vielleicht bekommt ihr das ja reproduziert bzw. selbst einmal nachgeprüft und analysiert, denn aktuell scheint mir da in der Tat etwas nicht richtig zu sein was ursächlich für dieses Problem hier zu sein scheint.

**Comment by jens-maus** [comment]
Ohweh, ohweh. Das sieht "mal wieder" nach einem typischen eQ3 Copy&Paste fehler aus mit dem 3.79.x release. Siehe:

https://github.com/eq-3/occu/blame/master/WebUI/www/config/easymodes/DIMMER_VIRTUAL_RECEIVER/MULTI_MODE_INPUT_TRANSMITTER_5.tcl#L302

<img width="1110" alt="Bildschirmfoto 2024-12-18 um 13 31 19" src="https://github.com/user-attachments/assets/0e809e06-5a1c-4173-a375-8049efc90db8" />

D.h. man ist wohl einfach davon ausgegangen das die Variable `ch` wohl schon überall definiert sein wird ohne dies zu kontrollieren...

**Comment by jens-maus** [comment]
@cb53359 Bitte mal mit dem nächsten nightly snapshot morgen erneut probieren und hier zurückmelden ob das Problem damit gelöst ist? Habe einmal einen WebUI patch anhand meiner Erkenntniss hier hinzugefügt und vielleicht löst das ja bereits das Problem.

**Comment by cb53359** [comment]
Moin Jens,

Test mit dem letzten nightly snapshot:
1) Klick auf "Bearbeiten" ergibt nun das gewünschte Ergebnis = normal editierbar
2) Abspeichern geht auch

...mehr habe ich nicht getestet.

Danke für Deine schnelle Reaktion!

VG Carl

**Comment by eiGelbGeek** [comment]
Hallo Jens,

das Problem scheint noch an weiteren Stellen vorhanden zu sein.

DV HmIP SRH ->  HmIP-FDT lassen sich weiterhin nicht erstellen oder bearbeiten. 

DV zwischen HmIP-FSM und FDT funktionieren nun wieder.
