### ISSUE TITLE
Dokumentation WLAN-Einrichtung

### ISSUE THREAD

**Issue by jp112sdl** [jens-maus/RaspberryMatic#299]
Hallo Jens,

in deiner [Doku](https://homematic-forum.de/forum/viewtopic.php?t=26917#p328057) im homematic-forum ist beschrieben:
Via Zugang zur Konsole das folgende Kommando ausführen um zu überprüfen ob das WLAN interface prinzipiell die NetzwerkID (SSID) des WLANs in das man sich verbinden möchte sehen kann:

`iw wlan0 scan`

Das führt seit Neuestem zu:
`command failed: Network is down (-100)`

Weil in `eQ3StartNetwork` das WLAN erst freigegeben wird, wenn eine `/etc/config/wpa_supplicant.conf` existiert.

Somit ist im Vorfeld kein Test/Auflisten der WLANs möglich

**Comment by ScharffenbergFrank** [comment]
Hallo Jens,

wenn nach `rfkill unblock wifi` noch ein `ifconfig wlan0 up` ausgeführt wird, dann kommt das IF hoch und mit `iw wlan0 scan` kann man die verfügbaren WLANs testen, auch ohne dass schon eine `/etc/config/wpa_supplicant.conf` existiert. 

Gruß Frank

P.S. Ich habe mit ein paar WLAN-Sticks experimentiert, die ich noch rumliegen hatte: Edimax EW-7811Un (Realtek RTL8188CUS), Logilink WL0084A (Realtek RTL8188CUS) und Sitecom WL-172 (Ralink  RT73/RT2573), alle 3 funktionieren. Im Anhang putty-logs, u.a. mit gekürztem dmesg-log.
[RaspberryMatic_WLAN.txt](https://github.com/jens-maus/RaspberryMatic/files/2083134/RaspberryMatic_WLAN.txt)
