### ISSUE TITLE
HmIP support not working on RaspberryPi3

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#30]
While the current master branch has some basically working HomeMaticIP (HmIP) support, this seems to be only true when using a RaspberryPi2. Due to the different UART setups between RaspberryPi2 + RaspberryPi3 the required `bcm2835-raw-uart` kernel module seems to be currently unable to work correctly on a RaspberryPi3.

When booting the current RaspberryMatic SD card image a RaspberryPi3 stalls right after trying to run `multimacd`. After some investigation the issue seems to be due to `bcm2835-raw-uart` not accessing the hardware correctly. When disabling the `multimacd` startup and manually trying to use `eq3configcmd update-coprocessor` the following error occur:

```
# modprobe bcm2835-raw-uart
# eq3configcmd update-coprocessor -p /dev/bcm2835-raw-uart -c -se
2016/12/11 16:54:31.624 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
2016/12/11 16:54:31.624 <Error> CCU2CommControllerMod::performIdentify(): Unable to determine coprocessor state.
2016/12/11 16:54:33.625 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
2016/12/11 16:54:33.625 <Error> CCU2CommControllerMod::performIdentify(): Unable to determine coprocessor state.
2016/12/11 16:54:35.626 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
2016/12/11 16:54:35.626 <Error> CCU2CommControllerMod::performIdentify(): Unable to determine coprocessor state.
2016/12/11 16:54:36.625 <Error> CoprocessorUpdate::startApplication():Could not start Coprocessor application.
```

Here normally the serial number of the RF module should be returned (which works for a RaspberryPi2). Disabling the `modprobe bcm2835-raw-uart` line in `/etc/init.d/S00eQ3SystemStartup` and replacing it with `modprobe amba-pl011` so that `/dev/ttyAMA0` appears allows to perform a correct request for the serial number like:

```
# modprobe amba-pl011
# eq3configcmd update-coprocessor -p /dev/ttyAMA0 -c -se
2016/12/11 19:04:41.891 <Info> SerialNumber: MEQXXXXXXX
```

Please also note that the current master branch of RaspberryMatic uses the `pi3-disable-bt` overlay  (see https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/board/raspberrypi3/config.txt#L31) to free the PL011 and turn off the Bluetooth module so that /dev/ttyAMA0 uses the PL011 like the RaspberryPi2 does. However, this unfortunately doesn't seem to immediately help for the bcm2835-raw-uart module.

**Comment by ToSa27** [comment]
Wie [hier](https://github.com/eq-3/occu/issues/33#issuecomment-269798265) erwähnt könnte das Problem mit der geänderten UART0-Clock Frequenz zusammenhängen (3MHz -> 48MHz). Auf einem Pi3 mit Jessie Lite funktioniert das Modul auf jeden Fall nach der Frequenzänderung. Wenn ich wüsste wie man die aktuelle Frequenz per code aus dem device-tree ausliest würde ich einen pull-request erstellen. Natürlich ginge für RaspberryMatic auch ein simples "if Pi2 then 3 else 48" aber da sich die Frequenz auch für den Pi3 mit einem neueren Bootloader ändert ist das nicht ser elegant.

**Comment by jens-maus** [comment]
Danke auch hier nochmal für deine Analysen und Hilfe beim Lösen des Problems. Sobald ich das selber testen konnte werd ich mir das auch nochmal anschauen und dann eine dauerhafte Lösung in RaspberryMatic einbauen. Da der unterschied von 3MHz zu 48MHz ja anscheinend auch mit der dpi-firmware version zu tun hat werd ich wohl auch gleich mal versuchen die buildroot version auf 2016.11 zu bringen da damit dann auch die aktuellste rpi-firmware mitkommen sollte und somit dann auch automatisch 48MHz für den RPi2 verwendet werden sollte (wenn ich das anhand deinen Analysen richtig verstanden habe). Natürlich wäre eine dynamische Lösung durch auslesen der aktuellen UART0-Clock Frequenz das beste. Aber das müssten wir erst einmal rausfinden wie man das am besten/optimalsten umsetzt.

**Comment by jens-maus** [comment]
After tests with the above mentioned changes HmIP support for RaspberryPi3 finally started to work. Thus closing this ticket.
