### ISSUE TITLE
HM-TC-IT-WM-W-EU & HM-CC-RT-DN : Datenpunkt falsch konfiguriert / programmiert

### ISSUE THREAD

**Issue by Vyrus0711** [jens-maus/RaspberryMatic#300]
Hallo,

ich glaube, daß ich einen Programmierfehler gefunden habe.

**Mein Setup**
HM-TC-IT-WM-W-EU (Firmware 1.3) - Funk-Wand-Thermostat
HM-CC-RT-DN (Firmware 1.4) - Funk-Heizkörperthermostat
Raspberrymatic (2.29.23.20171216)

**Betroffene Datenpunkte von Wandthermostat**
```
xxxxxx:2.AUTO_MODE
xxxxxx:2.MANU_MODE
xxxxxx:2.BOOST_MODE
......
```

**Auffälligkeit / Fehler**
Die o.g. Datenpunkte konnten früher (zu CCU2-Zeiten) mit TRUE/FALSE verändert werden. 
In der Raspberrymatic ist (aus irgendeinem Grund) der **MANU_MODE nicht über TRUE/FALSE** veränderbar.
Ich kann diesen nur über den Wert "1" ansteuern.

**Beispiel-Skript**
```
! ----------------------------------------------------------------------------------------------
! ----Variablen definieren:
real MODEToggle;
real MODESchreiben;
! ----------------------------------------------------------------------------------------------
! ----Betriebszustand einlesen:
MODEToggle = dom.GetObject("BidCos-RF.LEQ0440217:2.CONTROL_MODE");
! ----Toggle-Modus des Betriebszustandes (1=Manuell; 0= Automatik):
if (MODEToggle.Value() == 1)
{
MODESchreiben = dom.GetObject("BidCos-RF.LEQ0440217:2.AUTO_MODE");
MODESchreiben.State(true);   ! <=== Befehl bei CCU2 und Raspberrymatic
}
else
{
MODESchreiben = dom.GetObject("BidCos-RF.LEQ0440217:2.MANU_MODE");
MODESchreiben.State(true);  !  <=== Befehl bei CCU2
MODESchreiben.State(1);    !    <=== Befehl bei Raspberrymatic
}
! ----------------------------------------------------------------------------------------------
WriteLine("Programmende");
```

Ich hoffe, daß meine Erklärung verständlich war und freue mich über ein kurzes Feedback.

Gruß
Axel

**Comment by jens-maus** [comment]
Folgende Dinge fallen mir an dem Skript auf:

1. `MODEToggle` und `MODESchreiben` haben den Typ `real`. Hier sollte aber `var` genutzt werden, denn da drin landen definitiv keine Floating Point werte.
2. Bitte mal für `dom.GetObject("BidCos-RF.LEQ0440217:2.MANU_MODE")` mittels `.Value()` den wert zurückgeben lassen und schauen ob da auch `1/0` oder `true/false` drin landet. Meine Vermutung ist das es bisher mit `true` und `false` eher zufällig funktioniert hat und man hier immer `0` und `1` verwenden sollte (auch bei einer CCU2).

**Comment by Vyrus0711** [comment]
1. Ich habe die Variablen mit dem Typ `real` versehen
2. Als Ergebnis bekomme ich NICHTS (LEER) zurück, d.h. keine `0/1` oder `true/false`

Sobald ich die Datenpunkte mit `1/0` quasi per `.State(1)` ansteuere (anstatt wie bei der CCU2 mit `true/false`) funktioniert alles.

Warum sich das in der Raspberrymatic geändert hat, bzw. warum das NUR bei dem MANU_MODE jetzt nicht mehr funktioniert, ist mir schleierhaft!

**Du kannst den Vorgang schließen!**

**Comment by Vyrus0711** [comment]
Hallo Jens,

 

du kannst das Ticket schließen, da mir ein Fehler unterlaufen ist.

 

Ich danke Dir für Deine Hilfe! Ich finde es super, daß Du mir/uns bei Problemen hilfst.

 

Bitte treibe die Raspberrymatic weiter voran!

 

 

Gruß

Vyrus0711

 

 

Gesendet: Donnerstag, 05. April 2018 um 20:20 Uhr
Von: "Jens Maus" <notifications@github.com>
An: jens-maus/RaspberryMatic <RaspberryMatic@noreply.github.com>
Cc: Vyrus0711 <vyrus@gmx.net>, "State change" <state_change@noreply.github.com>
Betreff: Re: [jens-maus/RaspberryMatic] HM-TC-IT-WM-W-EU & HM-CC-RT-DN : Datenpunkt falsch konfiguriert / programmiert (#300)


Warum kann ich das ticket jetzt plötzlich schliessen?!?
