### ISSUE TITLE
flock binary nicht kompatibel zu ccu2

### ISSUE THREAD

**Issue by koppenho** [jens-maus/RaspberryMatic#306]
RaspberryMatic enthält in Version 2.31.25.20180120 (und vermutlich auch noch die neueste) eine flock-Implementierung aus busybox. Die ccu2 dagegen hat ein flock aus dem util-linux-Paket.
Leider habe ich eine große Anzahl von Skripten, die "flock -w <timeout> ..." verwenden. Die busybox-flock kennt die Option "-w" leider nicht.
Spricht etwas dagegen, auch in RaspberryMatic die Version aus dem util-linux-Paket zu verwenden bzw. einzubauen?

Hier die Gegenüberstellung der beiden Versionen
RaspberryMatic
```
# flock -h
flock: invalid option -- 'h'
BusyBox v1.27.2 (2018-01-20 09:31:31 CET) multi-call binary.
Usage: flock [-sxun] FD|{FILE [-c] PROG ARGS}
[Un]lock file descriptor, or lock FILE, run PROG
        -s      Shared lock
        -x      Exclusive lock (default)
        -u      Unlock FD
        -n      Fail rather than wait
```
CCU2
```
# flock -V
flock (util-linux 2.20.1)
# flock -h
Usage:
 flock [-sxun][-w #] fd#
 flock [-sxon][-w #] file [-c] command...
 flock [-sxon][-w #] directory [-c] command...
Options:
 -s  --shared     Get a shared lock
 -x  --exclusive  Get an exclusive lock
 -u  --unlock     Remove a lock
 -n  --nonblock   Fail rather than wait
 -w  --timeout    Wait for a limited amount of time
 -o  --close      Close file descriptor before running command
 -c  --command    Run a single command string through the shell
 -h  --help       Display this text
 -V  --version    Display version
```

**Comment by jens-maus** [comment]
Nein, dagegen spricht nichts. Werde ich für die nächste RaspberryMatic Version so vorsehen. Danke für die Info.

**Comment by koppenho** [comment]
Vielen Dank. Ich bereite gerade die Umstellung auf Raspberymatic vor. Dabei ist mir die Abweichung aufgefallen.
