### ISSUE TITLE
Cloudmatic-Button funktioniert nicht

### ISSUE THREAD

**Issue by Micha3582** [jens-maus/RaspberryMatic#309]
Hallo zusammen,
ich wollte den Service von Cloudmatic mal ausprobieren, nur leider funktioniert der Button nicht.
Sobald ich in der Systemsteuerung auf den Cloudmatic-Button Drücke, wird mir der Quelltext der aufgerufenen Seite dargestellt, also der Code. Die Seite wird also nicht vernünftig im Browser geladen.
Habe auch mehrere Browser getestet, auch Mobilgeräte, daran liegt's jedenfalls nicht...

habe auch die neuste Version von Raspberrymatic installiert (2.31.25.20180324)

Wie kann man das Problem fixen?!

Gruß, Micha3582

**Comment by tobiman64** [comment]
Hallo,

schau dir mal den folgenden Issue an, dort gibt es eine Lösung, welche in der nächsten Raspberrymatic Version implementiert ist.
https://github.com/jens-maus/RaspberryMatic/issues/293

Gruss   Tobi

**Comment by Micha3582** [comment]
Hi Tobi, danke für die Info! Leider bin ich erstmal genau so "dumm" wie Du, ich bekomm das mit dem schreibrecht über mein FTP Programm (WinSCP) nicht hin. Wie ist das mit dem Mounten gemeint bzw. wie wird's gemacht?

**Comment by Micha3582** [comment]
Ok Problem gelöst - habs gefunden wie es funktioniert. klappt!

Danke Tobi!!!
