### ISSUE TITLE
Add IP adress to start up display on monitor

### ISSUE THREAD

**Issue by drose28357** [jens-maus/RaspberryMatic#31]
When RaspberryMatic starts up it shows a start screen at the HDMI output. When the boot prozess is finished it shows a logo an an url. A user has to copy this url to his browser by typing. 

For debuging the router configuration in an multiple RaspberryMatic environment there should be an additional display of the actual ip adress (IP4 format xx.xx.xx.xx) or the max adress or both.

This is a minor feature request.

**Comment by drose28357** [comment]
Hello Jens, thanks for your solution. 
but i requestet an additional ( or enhanced) display.

Could you please change line 40 from 

     /usr/bin/psplash-write "MSG RaspberryMatic ${VERSION} -- http://${IP}/" 

to 

    /usr/bin/psplash-write "MSG RaspberryMatic ${VERSION} -- http://$(hostname)/  ( http://${IP}/ )"

So we display the DNS-URL and an additional IP-URL.

Ditmar

**Comment by jens-maus** [comment]
I am sorry, but this display of the final message is already quite wide, so I decided to just display the IP-address since this is the most reliable way of reaching a CCU anyway. Therefore I decided against displaying both URL or there might be problems for some users using not so wide displays.

**Comment by drose28357** [comment]
O.K. If it is a dsign decision its up to you.
