### ISSUE TITLE
Lux auswahl kann nicht gespeichert werden

### ISSUE THREAD

**Issue by vdemden** [jens-maus/RaspberryMatic#310]
betrifft den Sensor HM-SenLI-O - Lichtsensor für innen und außen. Bei der Außwahl Gert im Wertebereich wird per default ausgewählt: Wertebereich von 1.0 Lux bis kleiner 0.0 Lux. Wenn man diese default Werte nun anpassen möchte, kann man das nicht abspeichern, sprich der OK-Button reagiert nicht. Andere Einstellungen wie gößer als, kleiner gleich etc. funktionieren.

**Comment by jens-maus** [comment]
Tritt dieses Problem auch mit einer CCU2 auf?

**Comment by vdemden** [comment]
Kann ich nicht sagen, habe nur die raspberry… jetzt hat sichs übers handy speichern lassen… vielleicht

Nur ein Problem meines Browser gewesen. 

Trotzdem schon mal vielen Dank fürs Prüfen….

 

 

Von: Jens Maus <notifications@github.com> 
Gesendet: Freitag, 20. April 2018 14:10
An: jens-maus/RaspberryMatic <RaspberryMatic@noreply.github.com>
Cc: vdemden <vdemden@web.de>; Author <author@noreply.github.com>
Betreff: Re: [jens-maus/RaspberryMatic] Lux auswahl kann nicht gespeichert werden (#310)

 

Tritt dieses Problem auch mit einer CCU2 auf?
