### ISSUE TITLE
Homematic Geräte nicht anlernbar 

### ISSUE THREAD

**Issue by mcchickents** [jens-maus/RaspberryMatic#311]
Guten abend bin letzt Woche vonn CCU2 auf Pi umgestiegen, hat auch alles so weit funktioniert. Heute ist mir jedoch aufgefallen das bei Geräte anlernen irgentwas nicht stimmt . Siehe Foto 
![fehler](https://user-images.githubusercontent.com/38571527/39072380-a0735dca-44ea-11e8-9e8d-1b92e09e6f7e.JPG)

**Comment by Digitus80** [comment]
Sieht bei mir genauso aus. Bin auch vor 1 Woche von CCU2 auf Pi 3 umgestiegen. Auch wenn man kein Backup einspielt, können HMIP-Geräte nur mit Keycode angelernt werden. Mit Backup sind alle HMIP-Geräte weg und es können gar keine angelernt werden. Angeblich (siehe Forum) sind die Key Server von eq3 nicht verfügbar.

**Comment by jp112sdl** [comment]
Siehe diesen [Beitrag](https://homematic-forum.de/forum/viewtopic.php?f=65&t=43277) und diesen [Beitrag](https://homematic-forum.de/forum/viewtopic.php?f=65&t=43309).

**Comment by jens-maus** [comment]
@mcchickents Abgesehen von dem hier geschilderten Problem sehe ich gerade das du den "Watchdog" noch installiert hast. Dieser ist leider immer noch nicht mit RaspberryMatic kompatibel und verursacht nur Probleme. Also bitte mindestens diesen deinstallieren oder deaktivieren.

**Comment by libertyx82** [comment]
@jens-maus 
Dann sollte man den Watchdog vielleicht einmal aus der Liste kompatibler Addons nehmen.
[https://github.com/jens-maus/RaspberryMatic#telescope-compatible-third-party-ccu-addons](url)

**Comment by jens-maus** [comment]
@libertyx82 Da hast du prinzipiell recht. Oder aber es finden sich eben auch mal andere ausser mir die aktiv Dinge betreuen und anpassen ;)

**Comment by libertyx82** [comment]
Dann sollte aber zumindest dabei stehen, dass er aktuell nicht kompatibel ist.
Denn auch beim Watchdog selbst steht, dass er mit der RaspberryMatic kompatibel ist.
Daher werden den immer wieder, welche installieren und dann ggf. Probleme haben.

**Comment by mcchickents** [comment]
Ok werde heute Abend den Watchdog deinstallieren. Ich hab folgenden Befehl "- rm -rf /etc/config/hmip_*.conf /etc/config/crRFD/*" per SSh ausgeführt und den Pi neugestartet.  Danach ist der Pi mal deutlich schneller gestartet. Die Ip Geräte sehe ich nun auch wieder. Das ganze Wired Zeugs ist aber immer noch nicht verfügbar.

**Comment by libertyx82** [comment]
@mcchickents Hast du denn auch ein Wired Interface? Wenn nein, dann wird dir das auch nicht als Methode zum anlernen angezeigt.

**Comment by mcchickents** [comment]
nein habe ich nicht. Was ist ein Wired Interface?

**Comment by libertyx82** [comment]
Ein Gateway an dem die Wired Komponenten angeschlossen werden.
https://www.elv.de/homematic-rs485-gateway-1.html

**Comment by jens-maus** [comment]
Das Problem scheint inzwischen von eQ-3 repariert worden zu sein. Siehe:
https://homematic-forum.de/forum/viewtopic.php?f=65&t=43309&start=30#p432511

**Comment by Digitus80** [comment]
Leider nicht oder nicht für alle.

**Comment by jens-maus** [comment]
Dann ein entsprechendes Ticket bei eQ-3 aufmachen da ich keinen Einfluss darauf habe.
