### ISSUE TITLE
Add option to set the filename of /bin/createBackup.sh

### ISSUE THREAD

**Issue by jd1** [jens-maus/RaspberryMatic#314]
I wanted to automate the backup of my RaspberryMatic installation. Therefore I automatically log in via ssh to the Pi, create the backup and move it to my NAS. The problem is that I don't know the exact name of the sbk file since it is created with the current date. I could guess the name, but it might happen that the minute from my NAS and Pi differ and then the script will fail.

My current solution is to copy all sbk files, but it would be easier to if I could specify the name of the backup file, e.g. `/bin/createBackup.sh /tmp/backup.sbk`.

**Comment by HMside** [comment]
If cuxd is installed, you can do this with the following two script lines. The second line must be executed with a delay of a few minutes.

```
dom.GetObject("CUxD.CUX2801001:2.CMD_EXEC").State("/usr/local/addons/cuxd/extra/ccu_backup /usr/local/sdcard/backup");
dom.GetObject("CUxD.CUX2801001:2.CMD_EXEC").State("/usr/local/addons/cuxd/extra/export_ftp.sh user:passwd NAS-IP NAS-Folder CCU-Folder");
```

**Comment by jens-maus** [comment]
Thanks Andreas for clarification. However, I would suggest that users create themselves a cronjob on the CCU which calls `createBackup.sh` to backup to a directory mounted (e.g. via NFS) from a NAS instead. This seems to be somewhat more straight forward than using this approach or to actually remotely trigger a backup.

**Comment by jd1** [comment]
@HMside Thanks, I will try if the first command works for me.

@jens-maus What happens when the SD card fails? Will the cronjob be part of the backup?
I want to avoid having backup logic on every machine, therefore I try to implement pull backups.

**Comment by jens-maus** [comment]
@jd1 Yes, cronjob are part of the backup itself. However, closing this ticket sind @HMside pointed out a solution for your problem. Please use the homematic forum next time to find a solution first.
