### ISSUE TITLE
crond erzeugt 8-10 Sek. Zombie Prozess

### ISSUE THREAD

**Issue by bulli-mh** [jens-maus/RaspberryMatic#316]
Hallo
jeder cronjob erzeugt einen 8-10 Sekunden Zombie Prozess auch wenn der eigentlich Prozess in unter einer Sekunde fertig ist. Egal ob Raspimatic oder CCU2. Fehler ist wahrscheinlich schon bei jeder Firmware drin.

```
 while true
 do
 date
 ps -ostat,pid,user,group,comm,args | grep ^Z
 sleep 1
 done
Sun Apr 29 06:59:57 CEST 2018
Sun Apr 29 06:59:58 CEST 2018
Sun Apr 29 06:59:59 CEST 2018
Sun Apr 29 07:00:00 CEST 2018
Sun Apr 29 07:00:01 CEST 2018
Z     4392 root     root     sh               [sh]
Z     4393 root     root     sh               [sh]
Z     4394 root     root     sh               [sh]
Sun Apr 29 07:00:02 CEST 2018
Z     4392 root     root     sh               [sh]
Z     4393 root     root     sh               [sh]
Z     4394 root     root     sh               [sh]
Sun Apr 29 07:00:03 CEST 2018
Z     4392 root     root     sh               [sh]
Z     4393 root     root     sh               [sh]
Z     4394 root     root     sh               [sh]
Sun Apr 29 07:00:04 CEST 2018
Z     4392 root     root     sh               [sh]
Z     4393 root     root     sh               [sh]
Z     4394 root     root     sh               [sh]
Sun Apr 29 07:00:05 CEST 2018
Z     4392 root     root     sh               [sh]
Z     4393 root     root     sh               [sh]
Z     4394 root     root     sh               [sh]
Sun Apr 29 07:00:06 CEST 2018
Z     4392 root     root     sh               [sh]
Z     4393 root     root     sh               [sh]
Z     4394 root     root     sh               [sh]
Sun Apr 29 07:00:07 CEST 2018
Z     4392 root     root     sh               [sh]
Z     4393 root     root     sh               [sh]
Z     4394 root     root     sh               [sh]
Sun Apr 29 07:00:08 CEST 2018
Z     4392 root     root     sh               [sh]
Z     4393 root     root     sh               [sh]
Z     4394 root     root     sh               [sh]
Sun Apr 29 07:00:09 CEST 2018
Z     4392 root     root     sh               [sh]
Z     4393 root     root     sh               [sh]
Z     4394 root     root     sh               [sh]
Sun Apr 29 07:00:10 CEST 2018
Sun Apr 29 07:00:11 CEST 2018
```

![cronzombi](https://user-images.githubusercontent.com/37998717/39427833-83e8588e-4c85-11e8-929c-b22966b263a1.jpg)

Gruß
Bulli

**Comment by jens-maus** [comment]
Tschuldigung, aber hier sehe ich nur die Symptome und keinen Hinweis bzw. Beispiel für solch ein cronjob. Auch wurde nicht darauf eingegangen welche Firmware und welche ReGaHss version auf den jeweiligen Systemen zum Einsatz kommt. Bitte entsprechend ergänzen.

**Comment by jens-maus** [comment]
@bulli-mh Tut mir leid. Aber ich kann deinen Ausführungen immer noch nicht so richtig folgen (irgendwie steh ich auf dem Schlauch). Die crontab Ausgabe die du zeigst ist das Standard-Crontab und das erzeugt in dieser Form zumindest in meiner Umgebung keinerlei Zombies. Bitte also hier mal ein Step-by-Step Beispiel bringen und genauer erklären was hier denn bitte ein Zombie Prozess erzeugt?!?

**Comment by bulli-mh** [comment]
Hi
gut neuer Versuch. Nimm dein neues Image und stell z.B den cronjob  * * * * * /bin/updateDCVars.tcl
auf eine Minute. Jetzt eine Shell öffnen und eine Schleife bauen.
while true
do
date
ps -ostat,pid,user,group,comm,args | grep ^Z
sleep 1
done

Jetzt wir du sehen das alle Minute von ca. xx:xx:01-09 Sekunden der Zombie Prozess da ist. Das kommt auf jeden Fall vom crond sieht man ja auch schön in der htop Ausgabe.

![cronzombi1](https://user-images.githubusercontent.com/37998717/39471491-bc1769ca-4d43-11e8-8338-58a7a638b07e.jpg)


@Alle vielleicht könnte das mal jemand anderes auch machen. Ist auch egal mit was Raspi oder CCU der Fehler ist ja schon immer da.

**Comment by jens-maus** [comment]
@bulli-mh Ok, danke für deine Geduld im erklären der Problematik. Nun habe ich mir das ganze selbst auch mal angeschaut und versucht anhand deiner letzten Anmerkungen zu reproduzieren. In der Tat sehe ich auch die von den cron jobs generieren Zombie Prozesse. Allerdings muss ich auch sagen bleiben die nicht auf ewig bestehen sondern existieren wohl nur für den Zeitraum der Ausführung eines Cronjob wie man hier wie folgt sehen kann:

```
# while true; do date; ps -ostat,pid,user,group,comm,args | grep ^Z; sleep 1; done
Wed May  2 13:03:57 CEST 2018
Wed May  2 13:03:58 CEST 2018
Wed May  2 13:03:59 CEST 2018
Wed May  2 13:04:00 CEST 2018
Z     4863 root     root     sh               [sh]
Wed May  2 13:04:01 CEST 2018
Z     4863 root     root     sh               [sh]
Wed May  2 13:04:02 CEST 2018
Z     4863 root     root     sh               [sh]
Wed May  2 13:04:03 CEST 2018
Z     4863 root     root     sh               [sh]
Wed May  2 13:04:04 CEST 2018
Z     4863 root     root     sh               [sh]
Wed May  2 13:04:06 CEST 2018
Z     4863 root     root     sh               [sh]
Wed May  2 13:04:07 CEST 2018
Z     4863 root     root     sh               [sh]
Wed May  2 13:04:08 CEST 2018
Z     4863 root     root     sh               [sh]
Wed May  2 13:04:09 CEST 2018
Z     4863 root     root     sh               [sh]
Wed May  2 13:04:10 CEST 2018
Z     4863 root     root     sh               [sh]
Wed May  2 13:04:11 CEST 2018
Wed May  2 13:04:12 CEST 2018
Wed May  2 13:04:13 CEST 2018
Wed May  2 13:04:14 CEST 2018
Wed May  2 13:04:15 CEST 2018
```

Wie man hier sehr gut erkennen kann besteht der Zombie Prozess lediglich für rund 10 Sekunden und verschwindet dann genauso wie er zur vollen Minute aufgetaucht ist.

Insofern erscheint mir das ein recht marginales Problem zu sein da der/die zombie nicht ewig existiert. Wie schon erwähnt kommt es bei Unix-Systemen unter gewissen Bedingungen immer mal dazu das Zombie-Prozesse entstehen. Lediglich wenn diese überhand nehmen oder niemals aufgeräumt werden sollte das ein Problem sein. So etwas kann ich hier aber z.B. nicht erkennen. Oder übersehe ich etwas?

**Comment by bulli-mh** [comment]
Hallo
ne alles gut. Sind halt Zombie Prozesse nicht schön aber auch nicht ganz schlimm weil sie von selbst wieder weg sind. Wäre halt schön wenn du das Problem wann auch immer weg bekommst. Ich habe das Problem auch erst jetzt gemeldet weil ich die Hoffnung(oder dachte) das das Problem in der Version (vielleicht) weg ist.
Wenn du das Problem findest und in 2 Sätzen erklären kannst warum das einen 10 Sekunden Zombie erzeugt, wäre es schön wenn du es schreibst. Wenn es aber länger wie 2 Sätze dauert spar dir BITTE die Zeit dann ist es nicht so wichtig. Du hast besseres zu tun.

Gruß
Bulli

**Comment by jens-maus** [comment]
Ich hab da nur die Vermutung das es was mit dem cron daemon zu tun hat das dort Subprozesse gestartet werden um die Ausführung der cronjobs durchzuführen. Und cron räumt dann ggf. in gewissen Intervallen hinter sich auf. Verifiziert habe ich das aber nicht. Da das Problem aber in der Tat marginal zu sein scheint und das System in keinsterweise irgendwie negativ beeinflusst werde ich dieses ticket vorerst schliessen da ich denke das man es nicht weiter analysieren braucht.
