### ISSUE TITLE
Gateway loses the connection again and again

### ISSUE THREAD

**Issue by micropet** [jens-maus/RaspberryMatic#320]
I have configured a RPI3 with LAN port as a gateway and one as CCU.
The current version of RaspberryMatic is installed on the CCU and on the Gateway

RaspberryMatic says every 10 seconds "RPI3 Gateway: CONNECTED - NOT CONNECTED"

**Comment by jens-maus** [comment]
Is this still the case with the latest RaspberryMatic Version?

**Comment by micropet** [comment]
Just flasht, will look.

**Comment by micropet** [comment]
Now I can no longer connect to the gateway.
I have flashed the RPI3 with your latest version.
touch / usr / local / HMLGW and reboot.

The RPI Gateway is on the network but is not recognized by the RPI3 with RaspberryMatic.

**Comment by jens-maus** [comment]
Does this problem still happen with the latest version of RaspberryMatic?

**Comment by jens-maus** [comment]
This ticket has been closed because of inactivity of the ticket owner and due to the fact that no developer could reproduce the issue. Please reopen the ticket once it can be reproduced again or the ticket owner can reply accordingly.
