### ISSUE TITLE
Problem mit route

### ISSUE THREAD

**Issue by spacyt** [jens-maus/RaspberryMatic#322]
Hallo, 
ich habe da ein Problem mit einer route die scheinbar vom System gesetzt wird.
Das ist der Auszug von route

```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         10.149.5.1      0.0.0.0         UG    0      0        0 eth0
10.0.0.0        *               255.0.0.0       U     0      0        0 eth0
224.0.0.0       *               240.0.0.0       U     0      0        0 eth0
```

Mein Problem ist nun das ich mir nicht klar bin woher 
```
10.0.0.0        *               255.0.0.0       U     0      0        0 eth0
```
kommt.

Meine Landschaft ist in verschiedene VLAN's aufgeteilt, aber durch das setzten dieser Route kommt ich nur aus dem 10.149.5. Netz auf die Raspimatic.
Mein DHCP ( WINDOWS) verteilt das so nicht. Das Problem besteht nur mir der Raspimatic.
Wenn ich die Route von Hand lösche geht alles wie gewohnt und ist auch von allen anderen Netzten erreichbar.

**Comment by alexreinert** [comment]
Ich vermute mal, dass du eine falsche Subnet Mask eingetragen hast bzw. über DHCP verteilen lässt.

**Comment by spacyt** [comment]
Nein das ist nicht möglich, im Subnet sind sieben weitere Gerät,die haben
das problem nicht

Alexander Reinert <notifications@github.com> schrieb am Fr., 4. Mai 2018,
10:45:

**Comment by alexreinert** [comment]
Hast du eine statische Adresse eingetragen oder DHCP?
Was gibt ifconfig aus?

**Comment by spacyt** [comment]
wenn ich unter /etc/config/netconfig schaue sieht das so aus

HOSTNAME=homematic-raspi
MODE=DHCP
CURRENT_IP=10.149.5.11
CURRENT_NETMASK=255.255.255.0
CURRENT_GATEWAY=10.149.5.1
CURRENT_NAMESERVER1=192.168.1.5
CURRENT_NAMESERVER2=10.1.100.6
IP=192.168.1.225
NETMASK=255.255.255.0
GATEWAY=192.168.1.1
NAMESERVER1=192.168.1.1
NAMESERVER2=0.0.0.0
CRYPT=0

Ich verteile per dhcp.
Wenn die Einträge die sind die vom DHCP kommen ist es auf jeden fall richtig.
Wie bereits gesagt alle weiteren Geräte indem Subnet haben dieses Problem nicht

**Comment by spacyt** [comment]
ifconfig: Auch hier zusehen das es nicht stimmt
eth0      Link encap:Ethernet  HWaddr B8:27:EB:FA:DC:92  
          inet addr:10.149.5.11  Bcast:10.255.255.255  Mask:255.0.0.0
          inet6 addr: fe80::ba27:ebff:fefa:dc92/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:19112 errors:0 dropped:0 overruns:0 frame:0
          TX packets:17582 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:6519652 (6.2 MiB)  TX bytes:10466161 (9.9 MiB)

**Comment by jens-maus** [comment]
Es ist in der Tat komisch das in deiner `/etc/config/netconfig` zwar die Netzmaske mit dem von dir über DHCP verteilten 255.255.255.0 range angezeigt wird (denn das trägt normal auch der DHCP client ein), dann aber im `ifconfig` man sieht das das interface auf 255.0.0.0 gesetzt wurde. 

Die Frage wäre also nun in der Tat was genau dafür verantwortlich ist das deine Netzmaske so gesetzt wird. Dafür bitte einmal ein komplett frisches/leeres RaspberryMatic aufsetzen und dann entsprechen den Skript `/bin/dhcp.script` Debugger. Dort am besten in der `handle_renew()` Funktion eine Ausgabe von `${subnet}` mal einbauen damit man sieht ob der DHCP in der Tat die richtige Netzmaske erhält.

**Comment by jens-maus** [comment]
Gibt es diesbzgl. bereits weitere Neuigkeiten?

**Comment by spacyt** [comment]
nein noch nicht, bin zurzeit im Urlaub.
Was genau soll ich den da einbauen?

**Comment by jens-maus** [comment]
am besten sowas wie `echo ${subnet} >/tmp/SUBNET`. und dann schaust du nach dem Hochfahren in die Datei `/tmp/SUBNET` was da drinsteht.

**Comment by spacyt** [comment]
Hallo, 
so bin nun dazugekommen das mal zu machen.
Wie ihr seht ist die Angabe schon das was ich auch per DHCP verteile.

cat /tmp/SUBNET 
255.255.255.0

Kann ich noch was tun um zu helfen?

**Comment by jens-maus** [comment]
Erst einmal sei gesagt das es um diese Funktion hier geht:

https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/overlay/base/bin/dhcp.script#L23

in dieser `handle_renew()` wird genau das gemacht was man erwarten würde, d.h. es wird via `ifconfig` das interface mit der entsprechenden `${subnet}` angabe angelegt. Insofern erstaunt es mich das danach dein interface aber einem anderen subnetz zugeordnet werden soll. Um den Grund hierfür zu finden bitte mal in Zeile 35 dieser Datei (https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/overlay/base/bin/dhcp.script#L35) die folgende Zeile hinzufügen:

```
/sbin/ifconfig -a 2>&1 >>/tmp/output
```

Und dann nach dem hochfahren mal schauen was in /tmp/output gelandet ist und diesen hier zeigen. Dann am besten das gleich noch am ende der `handle_renew()` Funktion das selbe statement einfügen und dann schauen was die zweite ifconfig ausgabe zeigt.

**Comment by spacyt** [comment]
cat /tmp/output_L35 
eth0      Link encap:Ethernet  HWaddr B8:27:EB:88:CD:C1  
          inet addr:10.149.5.10  Bcast:10.255.255.255  Mask:255.0.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:674 (674.0 B)  TX bytes:738 (738.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:536 (536.0 B)  TX bytes:536 (536.0 B)

eth0      Link encap:Ethernet  HWaddr B8:27:EB:88:CD:C1  
          inet addr:10.149.5.10  Bcast:10.255.255.255  Mask:255.0.0.0
          inet6 addr: fe80::ba27:ebff:fe88:cdc1/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:6 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:960 (960.0 B)  TX bytes:1411 (1.3 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:536 (536.0 B)  TX bytes:536 (536.0 B)

**Comment by spacyt** [comment]
ich habe jetzt noch mal die SUBNET Abfrage am Anfang der Routine gesetzt.
cat /tmp/SUBNET_start 
255.255.255.0

**Comment by jens-maus** [comment]
danke. Kannst du nochmal ganz an den Anfang (vor dem ifconfig) die ausgabe des ifconfig zeigen? Find das wirklich komisch das das die broadcast und Netzwerkadresse auf ein class-A Netzwerk gesetzt wird wo doch eigentlich direkt class-C angegeben wird.

**Comment by jens-maus** [comment]
Bitte auch mal `${broadcast}` ausgeben lassen.

**Comment by alexreinert** [comment]
Interessant dürfte es auch sein, mal ```/sbin/ifconfig -a 2>&1 >>/tmp/output``` in Zeile 28 zwischen dem ```ifconfig``` und dem ```eq3configcmd``` auszuführen.

**Comment by jens-maus** [comment]
@alexreinert Das stimmt natürlich. Allerdings erwarte ich davon nicht all zu viel, da das `netconfigcmd` lediglich die Daten in der `/etc/config/netconfig` datei setzt und keinerlei eigene Anpassungen an den interfaces selbst durchführt.

**Comment by alexreinert** [comment]
Eine verrückte Idee noch: In den man-Pages wird bei ifconfig immer die netmask vor der broadcast angegeben, hier wird es aber andersrum gemacht. Vielleicht triggert das einen Edge-Case in ifconfig, welcher dafür sorgt, dass die default netmask für das Class A verwendet wird.
Es wäre daher ein Versuch wert, dass beim ifconfig Aufruf einfach mal zu tauschen.

**Comment by jens-maus** [comment]
Das kann natürlich auch sein. Ich würde jedoch gleich versuchen `ifconfig` gegen folgenden `ip` Aufruf zu tauschen:

```
/sbin/ip addr add ${ip}/${subnet} broadcast ${broadcast} dev ${interface}
```

Da ich ohnehin vorhabe die ifconfig aufrufe komplett gegen das neuere `ip` zu tauschen.

**Comment by spacyt** [comment]
Also ${broadcast} bleibt durchgängig leer. Die Temp Datei wird nicht mit einer Ausgabe gefüllt.
Habe das echo sowohl am Anfang als auch am Ende gesetzt.

**Comment by jens-maus** [comment]
Wenn ${broadcast} leer bleibt bedeutet das das der DHCP wohl diese Information nicht mitsendet und der ifconfig Befehl dann wohl deshalb abbricht weil die kommandozeilenoption nicht korrekt ausgefüllt ist. das erklärt dann in der tat warum die Netzmaske nicht gesetzt ist.

In dem Falle würde ich an deiner Stelle nun mal prüfen warum die broadcast-adresse vom DHCP nicht mit übertragen wird. Auf der anderen Seite bitte mal den "ip addr add" Aufruf einsetzen und schauen ob das hilft. und wenn das auch zu dem Fehler führt dann bitte mal das ${boardcast} mit dem ${netmask} tauschen.

**Comment by jens-maus** [comment]
@spacyt Das ist nur bedingt richtig das es jetzt komplett funktioniert. Jetzt bricht das `ifconfig` Kommando eigentlich auch mit einem Fehler ab, nur das netmask wird nun eben als erstes ausgewertet. Um das Problem permanent zu beheben musst du deinem Windows DHCP beibringen auch die broadcast-adresse zu senden. Würde mich nicht wundern wenn andere Geräte in deinem Netzwerk sonst ähnliche Fehler zeigen werden.

Nichtsdestotrotz arbeite ich den Skript nun um und poste ihn dann wenn ich eine version fertig habe die besser auf solche kaputten DHCP server Konfigurationen reagieren kann.

**Comment by alexreinert** [comment]
Die Broadcast Adresse ist keine Pflicht in den DHCP Options, der Bug ist also in RaspberryMatic (bzw. auch in der CCU) zu suchen...

**Comment by jens-maus** [comment]
@alexreinert Ist das wirklich so? Wo ist dazu die Spec?

**Comment by jens-maus** [comment]
Ok, danke für den Input. Dann ist das in der Tat ein reiner RaspberryMatic bug, denn in der CCU2 wird die broadcast Adresse in `/bin/dhcp.script` nicht beachtet wie ich gerade sehe.

**Comment by spacyt** [comment]
Cool, danke für die Super Arbeit.

**Comment by jens-maus** [comment]
@spacyt Solange ich das nicht als "geclosed" markiere ist da noch nix passiert. Also bitte nicht selber schliessen. :)

**Comment by jens-maus** [comment]
Bitte mal den `/bin/dhcp.script` Skript gegen den folgenden ersetzen und ein letztes mal testen:

https://github.com/jens-maus/RaspberryMatic/raw/0975a118d84b5fb37de421c6b5b1f8b539449476/buildroot-external/overlay/base/bin/dhcp.script

Damit sollte das Problem hoffentlich behoben sein.

**Comment by jens-maus** [comment]
Ok, danke für das Feedback. Dann kann man das hier jetzt schliessen.
