### ISSUE TITLE
Start von 0 und Namenvergabe (DHCP)

### ISSUE THREAD

**Issue by JanHBade** [jens-maus/RaspberryMatic#323]
Hallo,

ich habe eben das neuste Release frisch auf einer SD-Karte auf einem RPiB+ aufgespielt.

Leider startet nur das CCU Recovery System und nicht das eigentliche System. Wieso?
(Eine alte Config/Backup habe ich nicht, ich starte gerade neu mit Homematic)

Die DHCP Namensauflösung scheint auch nicht richtig zu funktionieren, meine Fritz.box meldet den Pi als Musicbox (anscheinend ein alter gespeicherter Name für den Pi).

Über IPv4/v6 ist der Pi aber ansprechbar, nur wie oben geschrieben nur das Recovery System.

**Comment by jens-maus** [comment]
@JanHBade Wenn das ein RaspberryPi 1 ist mit lediglich 26 Pins, dann sollte der Recovery Button auf Pin 18 (GPIO 24) liegen (siehe https://developer-blog.net/raspberry-pi-gpio-schnittstelle-teil-1/). D.h. sobald du den Pin mit GND verbindest geht der automatisch beim hochfahren in das Recovery System. Aber wie gesagt, am besten HDMI anschliessen und ganz am Anfang beobachten was U-boot so ausgibt als Grund für den Gang in das Recovery System.

**Comment by JanHBade** [comment]
Da war doch wirklich noch eine Bastelei vom letzen Mal vorhanden, nur fährt der Pi richtig hoch.

Vielen Dank für die Hilfe!

Die fritz.box hat aber leider den neuen Namen nicht gefressen... :(
Hinweis in der Richtung (hatte ich schon Mal) https://forum.ubuntuusers.de/topic/fritz-box-erkennt-netzwerkgeraet-nicht-richti/#post-1324658

**Comment by jens-maus** [comment]
@JanHBade Na dann ist ja gut das nun alles geht. Bzgl. DHCP, RaspberryMatic sendet bereits den hostname an den DHCP server mit. Wenn die FRITZBox aber darauf nicht reagiert kann ich auch nix machen... ;)

**Comment by JanHBade** [comment]
ein Neustart der FritzBox brauchte dann die passenden Namen 👍 

Vielen Dank nochmal!
