### ISSUE TITLE
Problem...Systemsteuerung nach Update nicht mehr zu erreichen

### ISSUE THREAD

**Issue by Seppel1982** [jens-maus/RaspberryMatic#324]
Nach dem Update auf RaspberryMatic 2.31.25.20180428 friert die WebUI nach dem Klick auf egal welchen Reiter in der Systemsteuerung ein.
Bitte um eine Info zur Lösung des Problems.
Durch einen Klick auf Aktualisieren im Browser lande ich auf der Startseite, komme dann auch wieder nur bis zur Systemsteuerung, aber wie oben beschrieben nicht weiter.

**Comment by jens-maus** [comment]
Duplikat von #315
