### ISSUE TITLE
CUxD & rfd Warnmeldung beim erstellen von Direkt Verknüpfungen

### ISSUE THREAD

**Issue by libertyx82** [jens-maus/RaspberryMatic#325]
Wenn Konfigurationsdaten zur Übertragung an ein Gerät anstehen, wird von der ReGaHss eine Funktion aufgerufen die nicht aufgerufen werden dürfte und daher wird vom CUxD eine Warnmeldung ausgegeben.

```
May  6 14:12:24 homematic-raspi daemon.warn cuxd[579]: 127.0.0.1 called unknown request method 'system.multicall' 'updateDevice'
May  6 14:12:24 homematic-raspi daemon.warn cuxd[579]: 127.0.0.1 called unknown request method 'system.multicall' 'updateDevice'
```
Siehe Beitrag im [Forum](https://homematic-forum.de/forum/viewtopic.php?f=37&t=43585)

**Comment by jens-maus** [comment]
Bitte ein entsprechendes Beispiel angeben mit Step-by-Step Anleitung damit man das einfach und unkompliziert nachvollziehen kann statt nur diese CUxD-spezifischen Fehlermeldungen deuten zu müssen.

**Comment by libertyx82** [comment]
Das ganze tritt beim Erstellen einer Direkt Verknüpfung auf in dem Beispiel ein Bewegungsmelder und ein Rollladenaktor. Beim erstellen der Verknüpfung werden sofort diese Fehlermeldungen ausgegeben sowohl vom CUxD als auch vom rfd

`May  7 17:50:45 homematic-raspi user.err rfd: HSSParameter::SetValue() 100 exception type error
May  7 17:50:46 homematic-raspi daemon.warn cuxd[582]: 127.0.0.1 called unknown request method 'system.multicall' 'updateDevice'
May  7 17:50:46 homematic-raspi daemon.warn cuxd[582]: 127.0.0.1 called unknown request method 'system.multicall' 'updateDevice'
May  7 17:50:46 homematic-raspi user.err rfd: XmlRpcClient error calling system.multicall({{[methodName:"updateDevice",params:{"rcux","NEQ011xxxx:1",1}],[methodName:"updateDevice",params:{"rcux","OEQ003xxxx:1",1}]}}) on binary://127.0.0.1:8701/RPC2:
May  7 17:50:46 homematic-raspi user.err rfd: XmlRpc fault: [faultCode:-1,faultString:"system.multicall: unknown.method name"]`

**Comment by jens-maus** [comment]
Wie man im Diskussionsthread auf homematic-forum sieht ist dies kein Problem der CCU bzw. ReGaHss, aber wohl einfach dem geschuldet, das CUxD diese Methode in einem system.multicall Aufruf nicht erwartet bzw. verarbeiten kann.
