### ISSUE TITLE
/etc/hosts not updated when the host name is changed via web UI

### ISSUE THREAD

**Issue by mdzio** [jens-maus/RaspberryMatic#326]
Steps to reproduce: The host name was changed to **test-raspi**. The Raspberry Pi was rebooted:
```
# hostname
test-raspi
# ping test-raspi
ping: bad address 'test-raspi'
# cat /etc/hosts
127.0.0.1       localhost
127.0.1.1       homematic-raspi
```

Other applications cannot resolve the name either (mdzio/ccu-historian#90).

**Comment by jens-maus** [comment]
Thanks for the hint. Please note, however, that changing `/etc/hosts` is simply not supported yet. It is also questionable if this is really required.

In your example the ping should normally work if your DNS would work if expected. Please check the content of `/etc/resolv.conf` in which the `domain` and `nameserver` setting should normally match what your DNS (e.g. fritzbox) expects. If this is correctly setup, then a simple `ping test-raspi` should work if your DNS (e.g. FritzBox) is also using that name.

**Comment by mdzio** [comment]
I ran some more tests: It works as expected, if **not** a fixed IP address is configured in RaspberryMatic.
`/etc/resolv.conf` has now the expected content. For all I care, this issue can be closed. Workarounds exist for the other case.

**Comment by mdzio** [comment]
Content of `/etc/resolv.conf` with a fixed IP address:
```
nameserver 192.168.1.1
nameserver 0.0.0.0
```

The router now shows the correct name and ip address. The error characteristics are very diffuse. I am still waiting for further feedback from other users.
