### ISSUE TITLE
HM-Sec-SFA-SM Fehler

### ISSUE THREAD

**Issue by Knallochse** [jens-maus/RaspberryMatic#327]
Ich habe bei der Sirenen/Blitzsteuerung (HM-Sec-SFA-SM) wiederholt Kommunikationsfehler obwohl der RSSI Wert um die 60db anzeigt. Nun sind mir dazu im Log ein Fehler aufgefallen.

```
May  7 17:12:06 homematic-raspi local0.err ReGaHss: Error: IseXmlRpc::CallXmlrpcMethod: execute result isFault; method =setValue Params = {"LEQ0801502:2","STATE",false} result= [faultCode:-1,faultString:"Failure"] [iseXmlRpc.cpp:2605]
May  7 17:12:06 homematic-raspi local0.err ReGaHss: Error: IseXmlRpc::CallSetValue: CallXmlrpcMethod failed [iseXmlRpc.cpp:1502]
May  7 17:12:06 homematic-raspi local0.err ReGaHss: Error: IseHssDP::WriteValue: CallSetValue failed; address = LEQ0801502:2 [iseDOMdpHSS.cpp:77]
```

Vielleicht können Sie damit etwas anfangen und ggf. reparieren.

**Comment by jens-maus** [comment]
Tschuldigung, aber dies ist kein Bug in RaspberryMatic/CCU sondern wohl dem geschuldet das das Gerät wohl einfach eben nicht via RF erreichbar war. Die Fehlerausgabe ist ein reines Resultat davon das das Gerät eben nicht erreichbar ist/war.

Bitte solche Dinge auch in Zukunft im HomeMatic Forum diskutieren und hier im GitHub nur verifizierte Bugs/Requests absetzen die mehr als eine Person verifizieren konnten.
