### ISSUE TITLE
teilweise doppelte Anzeigen in Status und Bedienung

### ISSUE THREAD

**Issue by Berndpaulus** [jens-maus/RaspberryMatic#329]
in Version  2.31.25.20180324 und  2.31.25.20180428 habe ich seit ein paar Tagen teilweise doppelte Einträge. 
![doppelte eintrage](https://user-images.githubusercontent.com/27635036/39866818-b1cad236-5441-11e8-979d-aec30969bae5.jpg)
Liebe Grüße
Bernd

**Comment by libertyx82** [comment]
Hi,
hast du deine RM mal neu gestartet und während des reboots den Cache des Browsers geleert?
Das hat bei mir bei doppelten Anzeigen (und Anzeigefehlern) bis jetzt immer geholfen.
MfG
Dirk

**Comment by Berndpaulus** [comment]
Hi,
scheint geholfen zu haben. Danke!
