### ISSUE TITLE
Restoring a CCU-Backup results in non-working HmIP support

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#33]
No matter if the source CCU had working HmIP support or no HmIP devices registered at all, as soon as a CCU Backup from a foreign CCU system (CCU2, YAHM, etc.) is restored teaching/registering new HmIP devices doesn't work anymore (even if a RaspberryPi2 with working HmIP support is used). It seems as some radio module device dependent ID is also restored with the backup which results in a state that the complete HmIP Support stops working even though HmIP is working on a freshly installed version of RaspberryMatic.

**Comment by TitusP** [comment]
It was possible to register HMIP components after deleting the directory '/etc/config/crRFD/data'.

**Comment by jens-maus** [comment]
We should test it again because in FW 2.27.7 this should be in principle possible (as said by eQ3).

**Comment by jens-maus** [comment]
@wowi1968 I just tested it again and did the following:

1. factory reset my ccu2 with 2.27.7
2. factory reset my raspberrymatic with 2.27.7
3. added HMIP-ASIR to CCU2
4. create backup on CCU2
5. switched of CCU2
6. restored CCU2 backup in raspberryMatic
7. after reboot the HMIP-ASIR ist listed in device list but neither device settings can be shown nor can the device be used at all.

Thus, with latest master branch of RaspberryMatic we still can't switch to a new central as it seems (at least not from CCU2 -> RaspberryMatic)

**Comment by jens-maus** [comment]
rescheduling for next release because we need some more help from others to actually see if the latest RaspberryMatic already works when installing a CCU2 Backup with HmIP components. This isn't yet clear.

It seems, however, that switching RF-modules in RaspberryMatic itself seems at least to work (see https://homematic-forum.de/forum/viewtopic.php?f=65&t=36486) properly.

**Comment by mdzio** [comment]
Successfully I have a restored a CCU2 backup with HmIP devices on the latest version (2.27.8.20170410, beta6). All HmIP devices are working without further actions. I have not testet pairing new devices.

**Comment by jens-maus** [comment]
@mdzio This is very good news. Can you please also test pairing new HmIP and verify that it works?

**Comment by mdzio** [comment]
Pairing of a new device is now also tested.

**Comment by jens-maus** [comment]
Recent reports suggest that this issue seems to be resolved since 2.27.8.20170410. Thus flagging it as solved.
