### ISSUE TITLE
Längeres Systemprotokoll (WEB GUI)

### ISSUE THREAD

**Issue by Bernd-Joras** [jens-maus/RaspberryMatic#330]
Hallo Jens,
im Moment wird bei meinem System nur für ca. 5 h das Systemprotokoll (WEB GUI) vorgehalten.
Nun könnte ich natürlich das „Protokolliert“ an den Geräten deaktivieren um hier einen größeren Zeitraum im Systemprotokoll vorzuhalten, jedoch geht das aus meiner Sichtweise am Sinn und Zweck vorbei.
Ich würde gerne mehr als nur wenige Stunden im Systemprotokoll sehen und dachte dass es ja nun zumindest auf RASBERRYMATIC“ keine physische Speicherplatzbegrenzung geben muss, da ja die SD Karte groß genug sein könnte.
Anders ist es nun wahrscheinlich mit den ominösen 3000 Einträgen, die maximal im System hinterlegt werden können. => keine Ahnung ob man das Erhöhen / verändern kann.

Ich hatte die Hoffnung hier nicht alleine den Bedarf (Wunsch) zu haben.
Die Hoffnung war (ist) dass die technische Umsetzung auf Rasberrymatic, auch Aufgrund der Speicherkarte und stärkeren Hardware gegenüber einer CCU2, möglich ist.

Siehst Du hier prinzipiell Möglichkeiten? ... Danke, Bernd

---------------------------------------------------
Hello Jens,
at the moment my system only keeps the system log (WEB GUI) for about 5 hours.
Now I could of course deactivate the "logged" on the devices to keep a longer period of time in the system log, but from my point of view this misses its purpose.
I would like to see more than a few hours in the system log and thought that at least on RASBERRYMATIC" there doesn't have to be a physical space limit, since the SD card could be large enough.
Now it is probably different with the ominous 3000 entries, which can be stored in the system at most. no idea if you can increase/change this.

I had the hope not to have the need (wish) here alone.
The hope was (is) that the technical implementation on Rasberrymatic is possible, also due to the memory card and stronger hardware compared to a CCU2.

Do you see possibilities here in principle? ... Thank you, Bernd

**Comment by jens-maus** [comment]
Seit der Version 3.45.7.20190504 wurde die Anzahl von 3000 Einträgen auf 10000 erhöht.
