### ISSUE TITLE
Programme unter "Systemsteuerung / Sicherheit " nicht verfügbar.

### ISSUE THREAD

**Issue by vdemden** [jens-maus/RaspberryMatic#331]
Version:   2.31.25.20180428 , Cux  2.0.1 , rmupdate 1.11.3., Raspberry PI3

ich kann in keinem Browser mehr den Menüpunkt starten, sieht aus als wollte das programm laden, dann hängt der browser und ich kan nur über ein komplettes neu laden zurück auf die Startseite.

geht nicht in IE, Edge und Chrome. Unter IE und Edge hängen auch andere Programmaufrufe manchmal.

Über RM-Update zurück auf eine ältere Version schlägt fehl.  die Version ein zweites mal zu installieren hab ich auch gemacht, bringt aber keine Änderung.

Wicht wäre mir, wie kann ich meine derzeitige Config jetzt erst mal sichern (ssh zugriff funktioniert)

Danke und grüße
Sabine

**Comment by vdemden** [comment]
Anleitung zum Backup über die linux-console habe ich gefunden. :-)

**Comment by libertyx82** [comment]
Ich vermute dein Problem ist das hier.

https://github.com/jens-maus/RaspberryMatic/issues/315
