### ISSUE TITLE
RaspberryMatic mit der Smartphone App steuern

### ISSUE THREAD

**Issue by ACE2xxx** [jens-maus/RaspberryMatic#334]
Hallo zusammen,
ich habe mich eine Zeit lang nun mit dem System auseinander gesetzt und finde es grundsätzlich super. Jedoch stehe ich im Moment vor dem Problem, dass ich mein System nicht mit der Smartphone App verbinden kann, da ich nach einem SGTIN & KEY gefragt werde. Ich habe nochmal in die mitgelieferten Unterlagen zum HM-OCCU-SDK geschaut, jedoch habe ich keinen QR Code Aufkleber oder ähnliches entdeckt.

Übersehe ich hier etwas, oder wie bekommt man die Integration in die Smartphone App hin?
Beste Grüße
Toni

**Comment by jens-maus** [comment]
Erst einmal sei gesagt das das hier kein Support-Forum ist, sondern ein Bugtracker! Also bitte in Zukunft and das homematic-forum wenden (https://homematic-forum.de/forum/viewforum.php?f=65).

Im Bezug auf SGTIN&KEY wird hier leider übersehen das es sich bei einer RaspberryMatic um eine CCU handelt und eine CCU kann man nicht an die eQ3 Smartphone App binden. Das ist bei RaspberryMatic nicht anders als mit einer CCU2. Wenn man die eQ3 Smartphone App mit der Cloud-Funktion verwenden will muss man auch den HmIP AccessPoint (http://www.eq-3.de/produkte/homematic-ip/home-control-access-point.html) einsetzen.

Wenn man allerdings eine CCU mit NoCloud Funktion bevorzugt/haben will, dann kann man als Smartphone App alternativ zur eQ3 App die "PocketControl" App (http://www.pocket-control.de) oder andere CCU taugliche Apps einsetzen.
