### ISSUE TITLE
HM-WDS30-T-O: No parameter display

### ISSUE THREAD

**Issue by avobert** [jens-maus/RaspberryMatic#338]
Hello,

the external thermometer works: I can set the parameters and see the temperatures in diagrams. But at "Status and Bedienung" -> "Geräte" I get a table header (Kanal ... Control), a "Filter" row and nothing more.

Bye,
Alexander

**Comment by jens-maus** [comment]
Sorry, but this is a Ticket/Bug Tracker and not a support fora. Please discuss your problem in the the homematic-forum (https://homematic-forum.de/forum/viewforum.php?f=65)
