### ISSUE TITLE
Cannot teach HM-Sec-RHS

### ISSUE THREAD

**Issue by avobert** [jens-maus/RaspberryMatic#339]
Hello,

For years I have operated lots of rotary handle sensors HM-Sec-RHS. ON CCU-1 and CCU-2 they work fine. But now I cannot teach them. I tried it with three units: I set them to teaching, they blink, the Raspimatic GUI is set to "Geräte Anlernen" -> "HM Gerät anlernen" -> "Anlernmodus ... aktiv" but nothing more happens.

I am aware of the limited operation range of these sensors - I am the one who showed how this problem can be solved. This is not the problem.

Bye,Alexander

**Comment by jens-maus** [comment]
Sorry, but this is a Ticket/Bug Tracker and not a support fora. Please discuss your problem in the the homematic-forum (https://homematic-forum.de/forum/viewforum.php?f=65)

**Comment by avobert** [comment]
Hallo,

 

 

Ich verstehe ja, wenn Sie Dummies weghalten wollen. Deswegen auch mein Hinweis vonwegen Reichweite. Im Lauf der Jahre habe ich mehrere 100 Homematic-Komponenten angelernt. Allein vom HM-Sec-RHS sind hier rund 30 in Betrieb.

 

Aus meiner Sicht ist das ein Software-Bug, der sich wohl bei der Umstellung auf den Raspi eingeschlichen hat. Mit der CCU-2 funktionierte das problemlos. Der Raspi ist die einzige Änderung meiner Installation.

 

 

Mit freundlichen Grüßen
Alexander von Obert


Alexander von Obert (Dipl.-Ing. Univ.), freelance technical communicator
Ringstr. 35, 85764 Oberschleißheim, Tel. +49-89-612 09 173
a.v.obert@techwriter.de, http://www.techwriter.de, http://www.tw-h.de
  

 

 

 

Von: Jens Maus [mailto:notifications@github.com] 
Gesendet: Sonntag, 20. Mai 2018 12:01
An: jens-maus/RaspberryMatic
Cc: avobert; Author
Betreff: Re: [jens-maus/RaspberryMatic] Cannot teach HM-Sec-RHS (#339)

 

Sorry, but this is a Ticket/Bug Tracker and not a support fora. Please discuss your problem in the the homematic-forum (https://homematic-forum.de/forum/viewforum.php?f=65)

**Comment by jens-maus** [comment]
Ich kann Ihre Kritik verstehen. Allerdings mag das vielleicht ein Software-Bug sein, allerdings müsste hier erst einmal rausbekommen werden ob dieses Problem auch bei N>1 Personen auftaucht. Und hierfür ist eben das Forum geeigneter als dieser GitHub Bugtracker. Auch hilft leider eine einfache Meldung "Geht nicht" leider recht wenig hier. In Bug/Issue-Tracker gehören IMHO mehr technische Details und genauere Infos die eben erst einmal im Forum gesammelt werden müssten (z.B. Auszüge aus dem rfd log oder ähnliches). Also bitte nicht gefrustet sein, sondern bitte erst an das Forum wenden und wenn dann dort das Problem bestätigt und ggf. sogar mit weiteren technischen Details genauer beschrieben wird dies dann hierher übertragen. Das erscheint mir zielführender zu sein.
