### ISSUE TITLE
/bin/createBackup.sh backing up recursively

### ISSUE THREAD

**Issue by noppingen** [jens-maus/RaspberryMatic#341]
2.31.25.20180526 - Calling `/bin/createBackup.sh /usr/local/sdcard/backup/` adds existing backups from /usr/local/sdcard/backup/ to backups in /usr/local/sdcard/backup/ recursively. 

Temporary fix: Add `--exclude=/usr/local/sdcard/backup` to tar command line in /bin/createBackup.sh.

Nixer fix: Add $1/$BACKUPDIR to tar --exclude to prevent recursion

Mahlzeit,

Stefan

**Comment by jens-maus** [comment]
Oder einfach eine leere Datei `.nobackup` in dem jeweiligen Verzeichnis das NICHT gebackupt werden soll ablegen und schon übergeht er das Verzeichnis.

**Comment by noppingen** [comment]
Thanks
