### ISSUE TITLE
Kein Backup im LAN Gateway Modus möglich

### ISSUE THREAD

**Issue by Iceteax** [jens-maus/RaspberryMatic#342]
Versucht man im Lan Gateway Modus ein Backup über /bin/createBackup.sh zu erzeugen, so schlägt dies mit der Fehlermeldung "Error connecting to peer" fehl. Startet man den Pi dagegen als ccu, kann man das Backup ohne weiteres ausführen.

**Comment by jens-maus** [comment]
Der `/bin/createBackup.sh` Skript ist auch nicht dazu gedacht von einem RaspberryMatic im LAN Gateway Modus ein Backup zu machen. Das ist übrigens auch vollkommen unnötig, denn es werden keine substantiellen Daten unter /usr/local gespeichert die in irgendeiner weise gebackupt werden müssten. Von einem echten LAN Gateway kann man ja (logischerweise) auch kein Backup machen.

**Comment by Iceteax** [comment]
Ah, ok. Vielleicht einmal der Doku bei Punkt 5 hinzufügen. Das Wissen hätte mir 1-2h Zeit gespart.
