### ISSUE TITLE
GPIO Pins 20 and 21 on RPi 3b

### ISSUE THREAD

**Issue by jp112sdl** [jens-maus/RaspberryMatic#344]
With Release **2.31.25.20180526** the GPIO Pins 20 and 21 on my RPi 3b are not longer usable as output pins.

```
echo out > /sys/class/gpio/gpio20/direction
echo out > /sys/class/gpio/gpio21/direction
```
creates the output:
```
./initGPIO.sh: line 17: can't create /sys/class/gpio/gpio20/value: nonexistent directory
./initGPIO.sh: line 18: can't create /sys/class/gpio/gpio21/value: nonexistent directory
```

Other pins I am using (19, 26) are still working fine.

On release **2.31.25.20180428**, the pins 20 and 21 worked as expected.

EDIT:
On an RPi0 **all** GPIO Pins mentioned above are working with **2.31.25.20180526**.

**Comment by jens-maus** [comment]
These pins are now required for the new upcoming RPI-RF-MOD. If you really need them and you stay with the old Rf module you can comment out the rpi-rf-mod leds overlay in `/boot/config.txt` and then they should be usable again.

An alternative to this could be to simply use the `gpio` wiringpi command-line tool to work with your GPIOs

**Comment by jp112sdl** [comment]
Thanks for the explanation. 
I did not know, that these pins are used for the new RF-board.
I moved my LEDs to pins 23 and 24 which is working _now_.
Are they also reserved for the new board?

I have seen, that GPIO12 is used for a button to boot in recovery mode.
Are there plans or restrictions to GPIO pins I _should_ not use?

**Comment by jens-maus** [comment]
Sorry, but please don't mix up the term "pin" with gpio numbers ;). The occupied gpios of the new RPI-RF-MOD model are:

```
Pin 32 - GPIO12 - Recovery Button (Pull-up active)
Pin 36 - GPIO16 - red LED
Pin 38 - GPIO20 - green LED
Pin 40 - GPIO21 - blue LED
```

In addition to that the new RPI-RF-MOD comes with a new RTC clock that will use the 0x32 i2c address for communication.

However, as said. If you don't use the new RPI-RF-MOD module you can still use GPIO16, GPIO20 and GPIO21 by simply using the `gpio` command-line tool from the wiringpi package. This allows to query/set GPIOs no matter if they are use by something else. IMHO using the `gpio` command-line tool should be preferred over directly addressing gpios via sysfs.
