### ISSUE TITLE
WebUI: Temperatur des Raspberry anzeigen

### ISSUE THREAD

**Issue by JensBonse** [jens-maus/RaspberryMatic#347]
Wäre es möglich, die Temperatur des Raspberry anzeigen zu lassen? So könnte man ggf. eine Lüftersteuerung realisieren, da z.B. die neuen Rapsberry Pi 3 B+ ziemlich warm werden.

**Comment by jens-maus** [comment]
Dazu braucht es keine Anpassungen denn das ist bereits mit einem einfachen reGaScript möglich. Siehe hier:

https://technikkram.net/2017/10/raspberrymatic-ueberwachung-und-auswertung-der-raspberry-pi3-temperatur
