### ISSUE TITLE
DHCP netmask is ignored

### ISSUE THREAD

**Issue by mulder999** [jens-maus/RaspberryMatic#348]
The DHCP network mask option is completely ignored by raspberryMatic.

I confirmed using Wireshark that DHCP option 1 is indeed properly set by my DHCP server and verified no other devices on my network is experiencing the same issue.

For example serving DHCP /24 network addresses within a class A range.

Sample dhcp router configuration:
`/ip dhcp-server network`
`add address=10.39.200.0/24 dns-server=10.39.200.254 gateway=10.39.200.254 ntp-server=10.39.200.254`

The netmask on raspberryMatic is 255.0.0.0 instead of the expected 255.255.255.0 for this scenario.
`eth0      Link encap:Ethernet  HWaddr B8:27:EB:xx:xx:xx`
`          inet addr:10.39.200.1  Bcast:10.255.255.255  Mask:255.0.0.0`

Same with WLAN
`wlan0     Link encap:Ethernet  HWaddr B8:27:EB:yy:yy:yy`
`          inet addr:10.39.200.2  Bcast:10.255.255.255  Mask:255.0.0.0`

Attempted several other netmasks and always observed the same wrong behavior from raspberryMatic.

**Comment by jens-maus** [comment]
Which version of RaspberryMatic are you using? In the latest 2.31.25.20180526 a similar bug had been already fixed:

https://github.com/jens-maus/RaspberryMatic/issues/322

**Comment by mulder999** [comment]
Thanks for quick reply, indeed I was still on 2.31.25.20180225. Will upgrade asap.

**Comment by jens-maus** [comment]
"Always work with the latest brand" ;-)

**Comment by mulder999** [comment]
Upgrading those beast is not always easy especially when you have to manage remotely lots of them, then test all devices, sometimes rollback and so on...

**Comment by mulder999** [comment]
Confirm fix working. Also noticed the nice improvement for future upgrades. Thanks for the hard work.
