### ISSUE TITLE
Installation von Addons nicht möglich

### ISSUE THREAD

**Issue by FerryIcker** [jens-maus/RaspberryMatic#350]
Hallo,
Vielen Dank für die Mühe diese Projekt zu warten.
Nach Installation diese Betriebssystems auf einen neuen RasberryPi 3 B ist es leider nicht möglich die hier aufgeführten Addons zu installieren.
Ich habe diese als zip heruntergeladen und auf dem üblichen weg installieren wollen.

Muss das zip-file vorher in ein *.gz konvertiert werden?

MfG
Ferry Icker

**Comment by jens-maus** [comment]
Erst einmal sei gesagt das das hier ein Bug/Issue-Tracker ist und kein Support Forum. Hier sollten nur bekannte/bestätigte Bugreports landen oder Verbesserungewünsche. Alles andere gehört ins homematic-forum.

Auch ist das Ticket leider unvollständig da hier kein Addon gelistet wird das angeblich nicht geht. Es sei nur kurz gesagt: CCU-Addons muss man als tar.gz Dateien hochladen und in keinem falle als *.zip Dateien.

**Comment by FerryIcker** [comment]
Hallo H Maus,

Sorry für die Unannehmlichkeiten und Dank für die Antwort.
Ich gelobe Besserung.

MfG
Ferry Icker
