### ISSUE TITLE
Update Button nicht vorhanden

### ISSUE THREAD

**Issue by IceBoosteR** [jens-maus/RaspberryMatic#351]
Hallo,
auf meiner RaspberryMatic ist die Möglichkeit nicht gegeben, ein Update durchzuführen. Gemäß der Anleitung habe ich das letzte Release als .zip heruntergeladen, ein Backup erstellt, etc. 
Allerdings kann ich keine neue Version einspielen, da der Button dafür fehlt (Anleitung: Nun unter Einstellungen->Systemsteuerung->Zentralen-Wartung->Heruntergeladene Software auswählen die Zip-Datei auswählen (nicht das ausgepackte Verzeichnis!) und dann darunter Hochladen drücken.
">Heruntergeladene Software" existiert bei mir nicht. Es wird allerdings angezeigt, dass eine neuere Version verfügbar ist.
Ein Screenshot gibts natürlich auch:
https://pasteboard.co/Hp8LBCc.png
Übersehe ich wohlmöglich etwas?
Danke.

**Comment by jens-maus** [comment]
Ja, es wird leider übersehen das die version die hier versucht wird auf einen neuen Stand zu bringen eben die WebUI Update-Funktion hat. D.h. das Uodate muss hier einmalig auf der alten Art und Weise passieren. D.h. Durch austausch der SD Karte und zurückspielen des Backups.

**Comment by jens-maus** [comment]
Übrigens ist dies hier kein Supportforum sondern ein bugtracker. Für solche probleme bitte in Zukunft an das HomeMatic-Forum wenden
