### ISSUE TITLE
Keine Script oder Programmausführung nachdem der NUT Server Alarm gemeldet hat

### ISSUE THREAD

**Issue by KoenigTH** [jens-maus/RaspberryMatic#352]
Hallo Jens,
ich habe seit kurzem meine USV (Back UPS ES 550) an meine Raspberrymatic Zentrale angeschlossen. Seit neuestem löst das System alle paar Tage aus (Alarmzone 1):
![grafik](https://user-images.githubusercontent.com/29251580/41221406-5be695d0-6d64-11e8-9458-9c63e4aed835.png)

Anschließend wenn ich den Alarm bestätige, habe ich folgendes Phänomen: Es werden keine automatischen Programme mehr getriggert und auch mit den Geräten HM-PB-4Dis-WM-2 oder dem HMIP-RC8 lassen sich keine Programme mehr starten. Ich muss dann den Pi einmal stromlos machen und wieder starten damit alles einwandfrei klappt.

Wenn ich die Alarmmeldung nicht bestätige kann ich weiterhin alles normal bedienen, erst nach der Bestätigung der Meldung beginnen die Probleme.

Dazu muss man sagen, dass kein Stromausfall oder ähnliches vorliegt. Ich weiß nciht warum die USV einen Alarm meldet. 

Vielen Dank schon mal und Gruß
Thorsten

**Comment by KoenigTH** [comment]
Achso, es ist die Version 2.31.25.20180526 installiert und zudem folgende Addons:
![grafik](https://user-images.githubusercontent.com/29251580/41221950-f8a364a6-6d65-11e8-9ee6-617d5e22541b.png)

**Comment by jens-maus** [comment]
Bitte im Homematic-Forum dieses problem bestätigen/analysieren lassen denn eigentlich gibt es keine verlinkung von der Alarmauslösung und der Ausführung automatischer Programme.

Bitte auch noch folgendes Testen:

Auf der Kommandozeile (SSH Zugang) einen eigenen Alarm ausführen lassen:

```
$ triggerAlarm.tcl TESTALARM
```

Und dann schauen ob da dann das verhalten gleich ist.

**Comment by KoenigTH** [comment]
Hallo Jens, 

dann wende ich mich mal an das Forum. Nach Auslösung und Bestätigung des Testalarms reagiert das System so langsam dass ich beim Aufruf der Räume teilweise mehrere Minuten warten muss bis die Seite geöffnet wird.

**Comment by KoenigTH** [comment]
und der Duty cycle geht immer höher von 8% auf mittlerweile über 33%

**Comment by jens-maus** [comment]
Bist du sicher das du kein Programm irgendwo hast das auf die Auslösung eines Alarms reagiert? bzw. auf die Auslösung der "Alarmzone 1" Systemvariablen? Weil wenn der DutyCycle dann höher geht zeigt das das irgendein Gerät wohl anfängt wie wild rumzufunken.

**Comment by KoenigTH** [comment]
Das einzige Programm das auf die Alarmzone 1 reagiert führt ein Script aus dass mir per Telegram eine Nachricht schickt, mehr nicht. Ich kann mir das Verhalten nicht erklären. Das komische ist ja auch, dass der NUT Server auslöst obwohl kein Stromausfall vorliegt.

**Comment by jens-maus** [comment]
Existiert dieses Problem noch in der aktuellen RaspberryMatic version?

**Comment by KoenigTH** [comment]
Hallo jens, sorry hatte garnicht mehr geschrieben. Nach dem Update auf die aktuellere Version und auch in der jetzigen aktuellen Version besteht das Problem nicht mehr. Der Threat kann geschlossen werden.
