### ISSUE TITLE
Bootvorgang hängt ca. 10min im Status "Starting susyd"

### ISSUE THREAD

**Issue by Jensner** [jens-maus/RaspberryMatic#355]
Hallo,

ich habe heute meinen Raspberry pi 3 auf die neue Version "RaspberryMatic-2.31.25.20180526-rpi3.zip" umgestellt. (Backup - Neuinstallation - Restore)
Seit dem dauert der Neustart extrem lange.
Das System startet scheinbar problemlos sämtliche Dienste und bleib dann für fast 10 min. im Status "Starting susyd..." hängen.
Danach startet das System normal.

Vielen Dank und viele Grüße
Jens

**Comment by jens-maus** [comment]
Bitte hier mehr Informationen liefern. Eine Ausgabe "Starting susyd..." gibt es nicht beim Startvorgang der RaspberryMatic... Bzw. bitte ein Screenshot liefern damit klar wird was hier gemeint ist.

**Comment by Jensner** [comment]
Hallo,

hier mal ein "manueller" Screenshot.
Leider kann ich nicht genau lesen was das heißen soll...

Viele Grüße
Jens
![img_4318](https://user-images.githubusercontent.com/40335897/41509303-03c61c70-7252-11e8-8603-997f4eec5b80.JPG)

**Comment by jens-maus** [comment]
Bitte mal ALT+F2 drücken und zeigen was dort zu sehen ist.

**Comment by jens-maus** [comment]
Irgendwelche Neuigkeiten hierzu?

**Comment by Jensner** [comment]
Oh, sorry.
Hatte Deine Antwort nicht gesehen.
Ich melde gebe Dir später ein Feedback..

**Comment by jens-maus** [comment]
Und bitte auch mal berichten was für zusätzliche Hardware eingesetzt wird am RaspberryPi3. Ist da überhaupt eine S.USV installiert oder eine andere Hardware auf dem GPIO Bus. Bitte mal Zusammenfassung geben.

**Comment by jens-maus** [comment]
Gibt es das Problem noch? Wenn nicht werde ich das Ticket demnächst einfach mal schließen.
