### ISSUE TITLE
Cloudmatic - VPN läuft nicht

### ISSUE THREAD

**Issue by dg1kwa** [jens-maus/RaspberryMatic#356]
Hi,
das VPN kommt nicht ans laufen. Zertifikate habe ich testweise schon neu installiert. Firewall und Netzwerkeinstellungen habe ich ebenfalls alle kontrolliert.

Start ich die Diagnose von Cloudmatic kann ich sehen das kein openvpn gestartet wurde.

Danke.

MfG Andreas

**Comment by jens-maus** [comment]
Dies ist ein Bug/Issue-Tracker und kein Support-Forum. Bitte erst einmal an das HomeMatic-Forum wenden um Hilfe zu suchen und wenn daraus ein bestätigter Bugverdacht entsteht hier noch einmal melden.

**Comment by dg1kwa** [comment]
Das muss wohl ein Bug sein, wenn ich das Ganze von Hand starten will bekomme ich die Meldung:
insmod: ERROR: could not load module /opt/mh/tun.ko: No such file or directory

Das Modul ist auch nicht vorhanden:
# ls /opt/mh/ -la
total 476
drwxr-xr-x    4 root     root          4096 Jun 22 14:46 .
drwxr-xr-x   10 root     root          4096 May 26 11:03 ..
-rwxr-xr-x    1 root     root           483 May 26 10:32 install.tcl
-rwxr-xr-x    1 root     root        462348 May 26 11:03 nginx
lrwxrwxrwx    1 root     root            17 May 26 10:32 openvpn -> /usr/sbin/openvpn
-rwxr-xr-x    1 root     root          1374 Jun 22 14:46 startup.sh
drwxr-xr-x    4 root     root          4096 May 26 11:03 user

Da es auf eine CCU2 funktioniert kann es nur ein Fehler in RaspberryMatic sein!

**Comment by jens-maus** [comment]
Das `tun.ko` Modul braucht es nicht bei RaspberryMatic denn das ist bereits standardmäßig geladen bzw. existiert im Linux-System bereits (siehe `modprobe tun`). Insofern kann diese Meldung getrost ignoriert werden. Bitte wie gesagt an das HomeMatic-Forum oder an CloudMatic selbst wenden. Wenn CloudMatic nicht gehen würde wärst du nicht der einzige der aufschreien würde denn das ist eine breit/groß genutzte Funktion. Bitte also von N>1 Personen Gegenchecken lassen bevor man das hier als vermeintlichen Bug meldet.
