### ISSUE TITLE
RaspberryMatic in einer virtuellen Umgebung

### ISSUE THREAD

**Issue by schneidy76** [jens-maus/RaspberryMatic#357]
Ist es möglich die ganze RaspberryMatic Umgebung in einer virtuellen Umgebung abzubilden?
Also ähnlich der Docker von deimos.
Gibt Linux das her? 
Dann könnte RaspberryMatic auf einer Umgebung gepflegt werden - die virtuelle Umgebung dagegen dann auf fast allen IoTs mit weniger Aufwand portiert werden.

**Comment by MathiasJZ** [comment]
Eine wichtige kleinigkeit vergessen:
Was macht er dann mit den ganzen Homematic-Aktoren? Wegwerfen?
Dieser Stick ist nur für Homematic IP-Geräte.
Das wäre interessant, wenn er auch nur HMIP-Geräte hätte.
Gruß,
Mathias

**Comment by jp112sdl** [comment]
Docker-Appliance der CCU2 für x86-64:
https://hub.docker.com/r/litti/dccu2-x86_64/

> Was macht er dann mit den ganzen Homematic-Aktoren? Wegwerfen?

Die kann er über ein LAN-Gateway nutzen

**Comment by schneidy76** [comment]
Ich habe mich wahrscheinlich nicht so klar ausgedrückt. Es geht um die Raspberrymatic nicht um die CCU2/3. Diese könnte als virtuelle Version dann sowohl auf einer NAS, einen Raspi, Bananapi, OrangePi, Thinkerboard und wie sie alle heißen in einer npm Instanz laufen. Dann kann parallel darauf noch ioBroker oder ähnliches laufen, wenn es das IoT Board her gibt. 
Und richtig hier geht es um Entwicklung - deswegen habe ich das auch hier rein geworfen...
VG Torsten

**Comment by JSurf** [comment]
Moin, ich habe einen Docker-Container basierend auf der von eq 3 bereitgestellten occu für Raspberry PI, der z.B. mit einem Lan-Gateway betrieben werden kann

https://hub.docker.com/r/jsurf/rpi-occu/
https://github.com/JSurf/occu

Firmware ist aber schon etwas älter. Bin da nicht so heiss hinterher immer auf die aktuellste Version zu aktualisieren. Raspberrymatic ist sicher das besser gepflegte projekt

**Comment by jens-maus** [comment]
In absehbarer Zeit ist geplant RaspberryMatic auch für virtuelle Umgebungen bereit zu stellen inkl. Docker. Bereits jetzt gibt es eine rudimentäre docker config im Repository die allerdings nicht mehr aktuell ist!

**Comment by schneidy76** [comment]
na denn warte ich eben noch eine Weile :-) Der zusätzliche Raspi zieht ja nicht soviel Strom...

**Comment by jens-maus** [comment]
Man kann natürlich auch einfach dran mitarbeiten statt darauf zu warten ;)

**Comment by MathiasJZ** [comment]
Wenn Du Dich auf Mitarbeit mit jemandem einlassen willst, der von 
Programmierung 0-Ahnung hat.........
Gruß,
Mathias

Am 23. Juli 2018 13:56:42 schrieb Jens Maus <notifications@github.com>:

**Comment by schneidy76** [comment]
Ich kann dir auch nur mit Ideen weiterhelfen... Das letzte was ich mal "programmiert" habe war Basic zu Zeiten von MS DOS 3.3 :-)
Da bin ich leider raus aus der Nummer
VG Torsten

**Comment by schneidy76** [comment]
ich denke ich verlagere die Diskussion mal ins Forum:
[https://homematic-forum.de/forum/viewtopic.php?f=65&t=44578](url)

**Comment by admir86** [comment]
Gibt es News bezüglich Docker? Wird daran gearbeitet? Oder gibt es eine konkrete Planung?

**Comment by jens-maus** [comment]
Nein, da gibt es keine Neuigkeiten und konkrete Pläne. Wer auch immer aber möchte kann mithelfen und das umsetzen was er selber gerne hätte!

**Comment by jens-maus** [comment]
So, vielleicht hat es der Eine oder Andere noch nicht mitbekommen, aber bzgl. RaspberryMatic in virtuellen Umgebungen hat sich was getan und wird zum nächsten offiziellen Release dann auch was geben: https://homematic-forum.de/forum/viewtopic.php?f=65&t=54055#p538104

Das Ticket hier kann/wird also daher geschlossen, da das nun im Grunde implementiert ist (wenn auch nicht via Docker).

**Comment by hackToxa** [comment]
Hallo Jens, siehst Du es dennoch als eine Option es auf Docker verfügbar zu machen? VG
