### ISSUE TITLE
Update über WebUI  nicht möglich

### ISSUE THREAD

**Issue by muggel8378** [jens-maus/RaspberryMatic#359]
Update über WebUI gestartet(raspi 3... und daher rpi3.zip genommen). Keine Fehlermeldung erhalten, jedoch nach reboot nur im RecoveryMode gelandet.
Hierüber erneut das Update gestartet, Teil 1 ist problemlos durchlaufen, bei Teil 2 gab es im letzten Schritt ein Error (dd).

**Comment by jens-maus** [comment]
Für eine ordentliche Analyse braucht man schon mehr Detail-Informationen als nur "gab es im letzten Schritt ein Error (dd)". Was für ein System wird eingesetzt, welche Addons sind installiert, usw. usw.

**Comment by muggel8378** [comment]
ja, das ist korrekt. ich habe das system über den raspberryMaticShop bezogen. Ich wusste nicht, dass da Addons vorinstalliert sind. Wie kann ich dieses addon abstellen / deinstallieren oder wie sehe ich überhaupt, welche addons noch installiert sind. (sorry.. das mit rmupdate wusste ich nicht!)

**Comment by jens-maus** [comment]
Du solltest das rmupdate Addon selbst auf eine neue/aktuelle Version bringen und dann sollte das Update funktionieren. Bitte In Zukunft direkt an den RaspberryMaticShop wenden. Da dieser "Hersteller" keine frischen RaspberryMatic-Versionen ausliefert sondern das rmupdate Addon verwendet kann ich hier nur eingeschränkt bis keinen Support leisten...
