### ISSUE TITLE
WebUI: Integration einiger devconfig Informationen ins UI (RSSI Anzeige, etc.)

### ISSUE THREAD

**Issue by JensBonse** [jens-maus/RaspberryMatic#360]
Hallo,

ich fände es sehr interessant, ggf. einige Daten und Funktionen aus der devconfig auch im normalen UI darzustellen bzw. bedienbar zu machen.
Z.b. wären die Empfangswerte der Geräte zu den jeweiligen Gateways interessant.
Auch die Funktion 'Reset config Cache' bruache ich in letzter Zeit bei den Fenster Dreh Kontakten immer häufiger.

**Comment by jens-maus** [comment]
Na dann sag ich mal, einfach mal loslegen und umsetzen und ein PullRequest mit den Änderungen einsenden und dann integriere ich das. Ansonsten heisst es genau spezifizieren was es denn bitte sein soll was da übernommen werden soll mit einer ordentlichen Begründung und dann lässt sich das besser einschätzen. Ansonsten ist dieser Request nämlich viel zu allgemein verfasst!

**Comment by HMside** [comment]
@jens-maus 
Schieb das mal auf die Projekt Liste, ich habe diese beiden Punkte auch noch auf meiner internen Liste stehen. Bezüglich RSSI war ich sogar schon mal angefangen und habe die Geräteliste um eine RSSI-Spalte erweitert. Lediglich zum füttern mit Werten war ich bisher nicht gekommen. Vielleicht hast Du an der Stelle noch einen Tipp wie bzw. wo man sich die RSSI-Werte am besten abgreifen kann. Hier müssten ja dann auch die Werte der HmIP-Geräte angezeigt werden.

![rssi](https://user-images.githubusercontent.com/13312068/42113212-c3f8ac96-7bea-11e8-9d64-461523225883.png)

@JensBonse 
Für "Config Restore" würde ich versuchen in die Geräte-Einstellungen unten einen Button "Konfiguration erneut senden" einzufügen. Da ich dies selber bisher wenig genutzt habe, wäre hier noch die Frage ob mit einem Restore z.B. bei Channel 0 nur Daten für diesen Kanal, oder für alle gesendet werden.

**Comment by jens-maus** [comment]
@HMside Danke Andreas, das sieht bereits schon sehr gut aus und bzgl. RSSI Anzeige hatte ich auch eine ähnliche Idee. Ich denke man müsste die RSSI Werte eben in gewissen Abständen (ggf. Cronjob) abgreifen und zwischenspeichern. Kannst deine Anpassungen ja mal in ein PullRequest packen und dann schau ich mal das ich den rest bzgl. cronjob usw. entwickle.
