### ISSUE TITLE
rcu_preempt detected stalls on CPUs/tasks

### ISSUE THREAD

**Issue by briearn** [jens-maus/RaspberryMatic#361]
Hi Jens,

about a year the Pi was stable with RaspberryMatic. No issues at all in all the releases. But around in Feb/March this year it became unstable. The problem is no accessibility on IP anymore. As it is headless, the usual unplug / plug in sorted the issue. Unfortunately only for a period of time. A day or a week, sometimes only hours.... then the issue reappeared.
Now, I have found the time to get a monitor down there into the cellar and found this error messages (see picture attached).
![grafik](https://user-images.githubusercontent.com/40994885/42444498-8bb2322a-8370-11e8-8ddf-739b3295758f.png)
Is that a known issue? I seached for stalled already, with no results. Do you need any further logs?

Cheers
Arne

**Comment by jens-maus** [comment]
Your image is way to low-res to see anything substantial from that. However, which version of RaspberryMatic are you using and have you tried the very latest one to check that the issue still appears?

**Comment by briearn** [comment]
The release I have is 2.31.25.20180625
attached a higher res picture

![grafik](https://user-images.githubusercontent.com/40994885/42446268-f08b5532-8375-11e8-8e0f-b064c26ad5bf.png)
I thought I have the very latest one, but you chap have worked your a** off and released one yesterday, so let me udate to this one in the meantime and we will see....

**Comment by jens-maus** [comment]
And in the meantime, please let me know which hardware you are using? RaspberryPi3, or Pi2?

**Comment by briearn** [comment]
Pi3
update done, stable so far.
![grafik](https://user-images.githubusercontent.com/40994885/42449888-ac63c684-8382-11e8-801e-e054d08212a8.png)

**Comment by jens-maus** [comment]
Great. Side Note: Clear your browser cache, it is still showing the old logo ;-)

**Comment by briearn** [comment]
Hi Jens, 
as a matter of heads up: So far still stable.
cheers buddy

**Comment by jens-maus** [comment]
Ok, then we are done, I guess.
