### ISSUE TITLE
RaspiMatic nach Abruch Stromzufuhr kein erneuter Start

### ISSUE THREAD

**Issue by BerkTam** [jens-maus/RaspberryMatic#363]
…nach Installation der RaspiMatic und Übernahme des BackUps aus der alten RaspiMatic lief zunächst alles korrekt. 
Wird nun aber die Stromzufuhr durch ziehen des Netzsteckers abrupt abgebrochen, erfolgt kein Neustart mehr der RaspiMatic. 
Mehrmals und mit einigen Neu-Installationen versucht. 

Nach Anschließen der RaspiMatic an den Monitor, sah ich dass beim Start alles normal verlief bis es anfing den HMServer zu starten. Von da hing es ungefähr 3-5 min. bis dann die Anzeige mit der IP-Adresse kommt. Hier steht ja in der Regel eine IP-Adresse. In meinem Fall steht dahinter nur " 2.35.16.20188788 -- ERROR: No IP address set"  
Und dabei bleibt es dann auch.

**Comment by jens-maus** [comment]
Bitte beim Hochfahren ALT+F2 auf der Tastatur drücken und beobachten was genau er beim hochfahren so ausgibt. Ggf. zeigt er da einen Fehler beim Initialisieren des Netzwerkes.

**Comment by BerkTam** [comment]
Zeigt exakt das an, was ich geschrieben hatte. 
Aber am Netzwerk kann es nicht liegen, denn wenn ich den RaspiMatic normal über die Systemeinstellungen herunterfahre, dann taucht er auch nach erneutem Anschließen wieder regulär auf. 
Nur bei abruptem Stromabruch, erfolgt kein Start des HMServers mehr … und im Netzwerk taucht er auch nicht mehr auf.

**Comment by jens-maus** [comment]
Wie gesagt, drücke ALT+F2 auf einer Tastatur die via USB angeschlossen ist und dann sollte er alle Dienste "Starting ...." anzeigen und dann siehst du ja was da passiert. Zeig das hier bitte mal mit einem Screenshot, dann kann ich ggf. genauer sehen warum das angeblich bei einem Stromabbruch sich anders verhält als bei einem reboot.

**Comment by BerkTam** [comment]
ich hab ALT und F2 gedrückt, aber da sehe ich nichts anderes wie das was ich beschrieben hatte. 
Screenshot kann ich nicht machen, aber ich mach mal mit dem Handy ein Foto und poste es hier rein.

**Comment by jens-maus** [comment]
Natürlicj gleichzeitih

**Comment by jens-maus** [comment]
Also kann das Problem hier nicht reproduzieren mit einem RaspberryPi3. Wenn das Problem noch weiterhin existiert wie gesagt ein screenshot/bild des Bildschirms posten nachdem dort ALT+F2 gedrückt wurde. Ansonsten wird das ticket nach einer Karenzzeit automatisch als invalid geschlossen.

**Comment by BerkTam** [comment]
Hallo Jens, 

sorry aber so schnell bin ich nicht. 
Das Problem besteht immer noch. 

Gruss
Berk

**Comment by Pepperronny** [comment]
Hallo Jens habe das selbe Problem 
![image](https://user-images.githubusercontent.com/43115157/45266333-e6ad3480-b459-11e8-8793-f0f4590490d0.png)

Eine schöne Zeit 
Ronald

**Comment by chaertl1** [comment]
Ich komm noch weiter, bei mir ist es wie bei berkTam, 
Bei mir kommt auch die Meldung ERROR: No IP address set.

Mir ist das diese Woche schon das zweite mal passiert,
Ich hab die aktuelle release Version mit etcher noch mal auf die gleiche SD Karte gespielt und es hat wieder funktioniert.

Ich würde das gern analysieren, aber ich kann mich auf der Konsole nicht anmelden.

**Comment by jens-maus** [comment]
@chaertl1 Bitte ein Screenshot der Fehlermeldungen zeigen nachdem du beim hochfahren auf einer angeschlossenen Tastatur ALT+F2 gedrückt hast.

**Comment by chaertl1** [comment]
Hier die screenshots
![20180914_095516](https://user-images.githubusercontent.com/43263702/45537788-8aedfd00-b805-11e8-8079-25e88a5e8cf5.jpg)
![20180914_095548](https://user-images.githubusercontent.com/43263702/45537789-8aedfd00-b805-11e8-8487-4605e5d07afe.jpg)

**Comment by jens-maus** [comment]
@chaertl1 Ja, definitiv eine kaputte /usr/local partition. Einzige Lösung hier: Neue/frische SD karte nehmen, neues RaspberryMatic drauf und backup zurückspielen. Und die alte Karte in den Müll befördern.

**Comment by chaertl1** [comment]
Ok ich werd's probieren.
Danke für die info.

**Comment by chaertl1** [comment]
So, 
Hab jetzt schon wieder das gleiche Problem.
Die SD Karte war nagelneu.
Ich glaub nicht mehr, daß es an der Karte liegt.
Entweder ist da wo ein Bug, oder das Image schreibt die Karte kaputt.

**Comment by libertyx82** [comment]
Wenn das so wäre, gäb es viele mit ständig defekten Karten.

Du gehst aber schon über Einstellungen->Systemsteuerung->Zentralenwartung->"Herunterfahren" oder ziehst du einfach den Stecker?

**Comment by chaertl1** [comment]
Nein war ein Stromausfall

**Comment by libertyx82** [comment]
Gut da kann das passieren, du solltest dem PI eine USV verpassen.

**Comment by chaertl1** [comment]
Der Superblock der 3. Partition war defekt.

Das hat geholfen:
[https://www.bitblokes.de/bad-superblock-erst-einmal-kein-grund-zur-panik/](url)

Die Karte läuft wieder einwandfrei.
Gottseidank hab ich die alte Karte noch nicht entsorgt.

Für Das Problem Stromausfall muss es aber auch eine andere Lösung geben.

**Comment by libertyx82** [comment]
Joar, du erzeugst deinen eigenen Strom :)
Ansonsten bleibt dir nichts als eine USV.

**Comment by chaertl1** [comment]
Das hab ich jetzt mal so laufen vielleicht hilft das jetzt:
# mount  /dev/mmcblk0p1 /boot -o remount
# echo fsck.repair=yes > cmdline.txt

Ich hoffe das sorgt für einen Autorepair des Filesystems wenn mal wieder was schief geht.

**Comment by Andreas-78** [comment]
@jens-maus gibt es denn eine Möglichkeit bei einer defekten Karte die rasberrymatic doch noch einmal hochfahren zu lassen?Sie bleibt in der webui im startbildschirm hängen.
Mein letztes Backup liegt leider schon länger zurück weshalb es schön wäre sie wenigstens noch einmal zu starten um ein Backup zu machen.
Leider fährt sie nach einem Stromausfall nur noch bis zum Startbildschirm hoch
