### ISSUE TITLE
Fehler nach Installation

### ISSUE THREAD

**Issue by skypatrol77** [jens-maus/RaspberryMatic#366]
Hi,

ich bin neu bei RaspberryMatic und habe den Bausatz von ELV mit Pi3B+ und der neuen Funk-Modulplatine RPI-RF-MOD installiert. Die aktuelle Raspberrymatic Software 2.35.16.20180708 ist drauf und das System startet auch ohne Probleme. Allerdings kommt immer wieder der Fehler das HmIP-RF und Virtual Devices nicht reagieren. Zudem passiert nichts wenn ich in Allgemeine Einstellungen gehe. Hier bleibt der Bildschirm grau. Was mache ich falsch?

**Comment by jens-maus** [comment]
Bitte erst einmal beachten das github kein supportforum ist sondern eine Entwicklungsplattform und das hier ein bugtracker. D.h. Für supportthemen bitte das homematic forum nutzen.

Bzgl dieses Anliegen ist dies vmtl das selbe Problem wie bereits gestern identifiziert und repariert:

https://homematic-forum.de/forum/viewtopic.php?f=65&t=43344&p=444165#p444163

Es wird dazu voraussichtlich morgen eine Hotfixversion geben.
