### ISSUE TITLE
ReGa: dom.GetObject("...").State(1) liefert false trotz Erfolg

### ISSUE THREAD

**Issue by jp112sdl** [jens-maus/RaspberryMatic#367]
Der Rückgabewert von `dom.GetObject("BidCos-RF.xxxxx").State(1)` ist immer false, obwohl in der Dokumentation anders erwähnt.

Details siehe https://homematic-forum.de/forum/viewtopic.php?f=19&t=44458

**Comment by jens-maus** [comment]
I just tried to reproduce this and I was able to verify it accordingly.
