### ISSUE TITLE
WebUI: Specifying a Webpage Icon for Apple Web Clip

### ISSUE THREAD

**Issue by roe1974** [jens-maus/RaspberryMatic#368]
Hallo Jens

Könntest Du dir vorstellen in einer der nächsten Versionen diesen HTML code auf der index.htm bzw. login.htm zu implementieren:

https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

Die notwednigen PNG's würde ich beisteuern.
Damit würde auf Apple Geräten im Browser bei den Favoriten bzw. wenn man die Raspberrymatic per Webclip auf den Homescreen legt das entsprechende icon erscheinen :-)

lg Richard

**Comment by roe1974** [comment]
alles klar, mache mich an die Arbeit ;-)

**Comment by roe1974** [comment]
habe in der /www/rega/login.htm folgendes ergänzt:

<link rel="apple-touch-icon" href="/ise/img/touch-icon-iphone.png" /> 
<link rel="apple-touch-icon" sizes="180x180" href="/ise/img/touch-icon-iphone-retina.png" />

...und die zwei PNGs entdprechend hochgeladen.....

Wenn ich jedoch die seite neu lade (cache geleert, anderer browser getestet) und mir den quelltext anzeigen lasse, fehlen diese zeilen in der login.htm?!?!?!?!?

Steh gerade auf der Leitung .......

**Comment by jens-maus** [comment]
ReGaHss muss neugestartet werden wenn man die Seiten ändert.

D.h.:
```
/etc/init.d/S70ReGaHss restart
```

**Comment by roe1974** [comment]
ahhhhh ok ;-) DANKE

**Comment by roe1974** [comment]
Wegen der icons .... was hälst du von diesem vorschlag ? (einmal mit raspi logo einmal ohne)
Habe die favicon.ico auch angepasst und ein bisschen hochauflösender gestaltet ;-)

[Icons.zip](https://github.com/jens-maus/RaspberryMatic/files/2197059/Icons.zip)

**Comment by jens-maus** [comment]
Ja, bitte zwei Versionen machen. D.h. mit Himbeere drin und eine ohne und dann jeweils die png und ico Dateien mit und ohne Himbeere mitliefern damit ich das entsprechend integrieren kann.

**Comment by roe1974** [comment]
So, da ich mich mit Pull request hier nicht auskenne ;-) ... anbei alle icons + PNGs inkl. der geänderten login.htm (von der aktuellen Version 2.35.16.20180715 (Neu sind Zeile 5 und 6)

[Raspberrymatic apple icons.zip](https://github.com/jens-maus/RaspberryMatic/files/2197922/Raspberrymatic.apple.icons.zip)

lg Richard

**Comment by jens-maus** [comment]
So, ich hab deine Anpassungen versucht entsprechend umzusetzen (siehe https://github.com/jens-maus/RaspberryMatic/commit/2b5c31ecd52f3a9023ebe32926fb6992d7826848). Das einzige was ich noch zusätzlich machen musste war auch noch die index.htm datei in gleicher weise zu patchen wie die login.htm. Danke aber auf jedenfalls für das nettere favicon mit der Himbeere in der Mitte ;-)
