### ISSUE TITLE
WiFi support

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#37]
We should evaluate how we can implement WiFi support (either through RaspberryPi3's WiFi chipset or via a dedicated USB-WiFi stick).

See here for more resources on WiFi support in buildroot:
https://github.com/danielnilsson9/buildroot-rpi3
https://delog.wordpress.com/2014/10/10/wireless-on-raspberry-pi-with-buildroot/
http://www.digitalpeer.com/blog/wireless-on-raspberry-pi-with-buildroot
http://www.walavalkar.co.in/home/wirelessrouterwithbuildrootandraspberrypi3
http://www.walavalkar.co.in/home/buildingalinuxfilesystemonraspberrypi3

**Comment by kroimon** [comment]
Where are the issues in using the integrated WiFi chipset?
I think it would be great to use that instead of the need for an additional USB adapter.

**Comment by jens-maus** [comment]
There is no "issue". This simply requires time to implement, that's why this is an "enhancement" flagged ticket. In additio to implementing the hardware support for the integrated WiFi-chip of the RPi3 we also have to implement/develop a way users can setup the WiFi-parameters (SSID, password, etc.). Thus, this simply requires time to be implemented which I currently lack (or other things having a higher priority).
