### ISSUE TITLE
With RaspberryMatic 2.35.16.20180715 no IP devices can be registered

### ISSUE THREAD

**Issue by micropet** [jens-maus/RaspberryMatic#370]
I use a RPI 3B + and the RPI-RF-MOD radio module.
Learning the device is missing the part for the IP devices.

**Comment by jens-maus** [comment]
After installing the latest 2.35.16.20180715 version you have to perform a complete factory reset in your test system if you have initially used 2.35.16.20180708 to build this test system.

**Comment by jens-maus** [comment]
see https://homematic-forum.de/forum/viewtopic.php?f=65&t=44479#p444999

**Comment by micropet** [comment]
Jens, ich habe das nicht ganz verstanden.
Ich habe eine neue Hardware mit 08 geflasht, dann Reset. Jetzt die 15er Version.
Dann ein Backup von der 08er eingespielt - kein IP
Wieder Reset, die 15er Version drauf und ein Backup von der 2.31.25.20180625 eingespielt - auch kein IP.

Gibt es eine Change meine 40 Geräte aus dem Backup wieder ans laufen zu bekommen?

**Comment by micropet** [comment]
ok mach ich. Die 3 IP Geräte sind nicht so schlimm, die anderen 40 würde ich nur ungern wieder anlernen.

**Comment by jens-maus** [comment]
Dann sollte reichen das folgende Kommando in einer SSH Sitzung auszuführen:

```
rm -rf /etc/config/hmip_*.conf /etc/config/crRFD/*
```

Dann neustarten und kontrollieren ob danach der HmIP Anlernmodus wieder geht und danach die 3 HmIP Geräte neu anlernen, etc. Und natürlich das alles mit der neuesten RaspberryMatic Version und nicht mit einer älteren.

**Comment by micropet** [comment]
Der start der RaspberryMatic-2.35.16.20180715 Version dauert unendlich lange.
Kurz was ich gemacht habe. Ich hatte vorher einen RPI3B mit den alten Funkmodul - alles war perfekt.
Jetzt habe ich einen RPI3B+ mit dem neuen Funkmodul und den schicken Gehäuse.

rm -rf /etc/config/hmip_*.conf /etc/config/crRFD/*
bring den IP Lernmodus wieder zurück.

Sieht gut aus.

**Comment by micropet** [comment]
Jetzt geht der Start wieder superschnell.

**Comment by micropet** [comment]
Prima Jens,
die IP Geräte funktionieren auch wieder und ich habe nichts verloren.
Vielen Dank für die schnelle Hilfe und Deine tolle Arbeit.

Vielleicht solltest Du den Trick mit dem löschen an zentraler Stelle veröffentlichen.

Gruss Peter

**Comment by micropet** [comment]
Sag mal, wo ich Dich gerade habe:
Ich habe auch den 8fach IP Handsender. Er lässt sich auch anlernen, aber dann kann man nichts damit machen. 
Im Homematic Status steht nur: Der Kanal hat hier keine Funktion

openHAB erkennt den Sender auch, aber man kann keine Aktion damit auslösen.
Die nicht IP Handsender arbeiten dagegen einwandfrei.

**Comment by jens-maus** [comment]
@micropet Ne, sorry. das ist hier kein Support-Forum sondern ein Bugtracker. Sowas gehört im Forum diskutiert.

**Comment by micropet** [comment]
OK

**Comment by Lars271** [comment]
Hallo,
wegen gleicher Hardware möchte ich diesen Thread fortsetzen, weil die oben angegeben Lösung nicht Funktionierte.
Ich habe gestern von meiner CCU2 mit der Firmware 2.35.16 ein Backup ohne Skripte gemacht.
Meine zukünftige Hardware soll ein Raspberry 3b+ mit einer Erweiterung DS3231 RTC IC und einer Samsung SDHC-Karte. Als BidCos-RF Geräte kommen zwei LAN-Gateways: HM-LGW-O-TW-W-EU und als Software kommt RaspberryMatic-2.35.16.20180715-rpi3.zip zum Einsatz
Nachdem Ich nun also den Rasberry gestartet habe, versuche ich "Geräte anlernen". Es erscheint ein Fenster, aber weder HM-IP noch HM werden angezeigt. Habe dann die obige Lösung zuerst versucht - ohne Erfolge, keine Änderung.
Also habe ich das BackUp von der CCU2 eingespielt. Das BackUp funktionierte für die HM-Geräte. Nicht jedoch für HM-IP_Geräte. Das heißt eine Steuerung der HM-Geräte ist nach Einspielen des BackUp möglich.
Also habe ich "Geräte anlernen" aufgrufen und es wäre möglich HM-Geräte anzulernen. Jedoch keine HM-IP, wodurch sich Probleme ergeben.
Also habe ich die von Ihnen oben vorgeschlagene Lösung wiederholt. Ohne Erfolg, es ist mir nicht möglich HM-IP-Geräte anzulernen. Es erscheint nur das Menü für HM nicht aber für HM-IP.

**Comment by Lars271** [comment]
Ja, ich benutze nur die beiden LAN-Gateways, auch in der CCU2. Die LAN-Gateways können das. Denn ich habe in der CCU2 keine Geräte mehr direkt an der CCU2 angelernt.
Wenn ich das richtig überlege, wie sich der "Fehler" verhält, dann scheint es so, dass die Funktion "Geräte anlernen" dynamisch erzeugt wird, je nach dem welche "Antennen" installiert sind. Denn wie ich schon schrieb, war nach der Erstinstallation gar kein anlernen möglich und erst nachdem die LAN-Gateways hinzugefügt wurden (durch das BackUp), waren diese verfügbar.
Ich müsste also nur dafür sorgen, dass ab dem Booten das HM-IP-Software-Modul geladen wird, damit das entsprechende System initialisiert wird.
Könntest Du mir einen Hinweis geben, wie ich das erreiche?

**Comment by libertyx82** [comment]
Nein, dass kann das LAN-Gateway definitiv nicht. Siehe [https://www.elv.de/homematic-funk-lan-gateway.html](hier)

`Das LAN Gateway unterstützt ausschließlich das Homematic Funkprotokoll und kann nicht zur Reichweitenverlängerung von Homematic IP eingesetzt werden`

**Comment by Lars271** [comment]
@libertyx82 : Wie ich bereits schrieb: Es sind keinerlei HM-IP-Geräte mehr an der CCU2 angelernt und es funktioniert alles mit der CCU2 (weil diese den Treiber geladen hat?).

**Comment by Lars271** [comment]
Na ja, mit Rechthaberei komme **ich** meistens nicht weit, also lass ich das letzte Posting mal unbeantwortet.
@jens-maus : Gerne möchte ich aber nochmal meine Frage wiederholen, ob man den Treiber laden kann? Oder bist du da an die NDA gebunden?

**Comment by libertyx82** [comment]
Mit Rechthaberei hat das nichts zu tun.

Das HM-LGW-O-TW-W-EU ist technisch nicht in der Lage mit HM-IP zu kommunizieren, da hilft dir auch das Laden des Treibers nicht.

**Comment by jens-maus** [comment]
Genau so ist es.

@Lars271 Wie schon hier gesagt wurde: Ein HomeMatic LAN Gateway kann technisch bedingt nicht mit HmIP Geräten kommunizieren. Das ist in Kopplung mit einer RaspberryMatic genauso wie in Kopplung mit einer CCU2 so. Der einzige Grund wieso mit einer CCU2 du trotzdem in der Lage warst mit HmIP Geräten zu kommunizieren ist, das in dem Falle das interne Funkmodul der CCU2 selbst die Kommunikation mit den HmIP Geräten pbernommen hat. Und weil dein RaspberryPi nun eben selbst kein internes Funkmodul besitzt fällt diese Möglichkeit/Funktionalität jetzt weg. Du misst also, wenn du mit HmIp Geröten kommunizieren willst den RaspberryPi um ein internes Funkmodul erweitern, d.h. Ein RPI-RF-MOD auf das interne GPIO stecken, dann tauchen auch wieder die HmIP Anlernfunktionen in der WebUI auf.
