### ISSUE TITLE
WebUI: Fehlermeldung nach Anlernen bei Wechsel in Posteingang (HMIP-RFUSB)

### ISSUE THREAD

**Issue by Messiahs** [jens-maus/RaspberryMatic#372]
folgende Fehlermeldung erscheint, wenn ich ein Gerät neu angelernt habe (über Button "Gerät anlernen" oben rechts).
"Fehler: BidCos-RF Anlernmodus konnte nicht aktiviert werden."

Vorgehensweise:
Button "HMIP Gerät anlernen"
Gerät wird korrekt gefunden.
Betätige ich nun den Button "Posteingang" erscheint obige Fehlermeldung.

Sonst funktioniert das Gerät allerdings korrekt und kann weiter eingerichtet werden. 

Image:
RaspberryMatic-2.35.16.20180715-rpi3

Hardware:
HmIP-RFUSB (getestet mit Raspi 3 B+ und Raspi 1 B)

Grüße
Markus

**Comment by Messiahs** [comment]
Kann dies jemand bestätigen (mit HMIP-RFUSB)?
Habe heute neues Gerät angelernt und wieder den gleichen Hinweis bekommen.
Das Gerät lässt sich danach allerdings ganz normal konfigurieren.

Grüße
Markus

**Comment by jens-maus** [comment]
Das ist ein Bug in der CCU Firmware selbst in Kombination mit dem HmIP-RFUSB. Recht unkritisch, aber trotzdem unschön.

**Comment by m4k5ym** [comment]
Ich würde mich jetzt auch mal in die Schlange stellen.

Ich hab momentan das Thema, wenn ich den HmIP-RFUSB an einen NUC anstecke mit virtualsiertem (Proxmox) RaspberryMatic, dann kann ich Beispielhaft einen HmIP-SLO wunderbar anlernen.

Sobald ich jetzt aber her gehe und das ganze an einer Synology 718+ mit VMM probiere bekomme ich nichts angelernt. Sobald ich in das Postfach versuche zu wechseln, bekomme ich folgenden Meldung zu Gesicht in Form eines JavaScript Popup: "Homematic Funk Anlernmodus konnte nicht aktiviert werden." und das Postfach ist entsprechend leer.

Der HmIP-RFUSB wird von RaspberryMatic korrekt erkannt, das UpdateTool sagt, die Firmware ist aktuell und die Konfigurationen scheinen auch zu passen. Die CCU3 findet entsprechend auch den HmIP-SLO, aber nur der RaspberryMatic mit HmIP-RFUSB in kombination mit einer Synology DS718+ macht zicken.

Gibt es hier noch etwas was ich übersehe?

**Comment by m4k5ym** [comment]
bump

**Comment by jckoester** [comment]
Gleiches Problem hier in einer VM unter qemu/kvm auf debian 10. RFUSB wird erkannt, das Anlernen scheitert aber.

**Comment by m4k5ym** [comment]
@jens-maus

**Comment by m4k5ym** [comment]
@jens-maus Verstehe ich vollkommen. Jedoch fasziniert mich hierbei warum es nur unter Synology knallt und qemu/kvm (Proxmox) out of box experience bietet. Wie es aussieht bis du aber auch schwer begeistert von dem Stick ;-) Hast du da vielleicht eine Idee was ich da auf der Synology vm debuggen könnte?

**Comment by jens-maus** [comment]
@m4k5ym Ich kann mir nur vorstellen das die Synology einfach ein zu großes HF Störfeld erzeugt und daher in der unmittelbaren Nähe der Synology der HmIP-RFUSB einfach untergeht. Deshalb der Tipp den HmIP-RFUSB einfach mal mit einem ~2m USB Verlängerungskabel von der Synology abzusetzen um zu schauen ob dann der Empfang besser ist.

**Comment by m4k5ym** [comment]
Wollte mal kurzes Feedback geben. 

Ich hab das ganze jetzt mal auf einen Raspberry Pi 4 Model B 2GB RAM umgezogen. So auf den ersten Blick scheint das ganze erstmal Fehlerfrei zu laufen. Muss das anlernen noch testen, aber ich konnte ohne Probleme auf das Postfach zugreifen was für mich schon ein 50/50 win ist.
