### ISSUE TITLE
Size of backup-file

### ISSUE THREAD

**Issue by HJS72** [jens-maus/RaspberryMatic#374]
In current Version 2.35.16.20180715 the file size of a backup-file is 30 times larger then before
(from 6.9 Mb to 188.8 MB)

**Comment by jens-maus** [comment]
Are you using the "rmupdate" CCU Addon? If so you have to delete all previous firmware files in the addon configuration page.

In addition, if you are using the CCU Historian Addon make sure to update to the latest on and amcheck that you are puttibg the data outside the /usr/local user partition

**Comment by jens-maus** [comment]
@j-a-n Can you please make sure that the directory where "rmupdate" is storing downloaded firmware files will have an empty `.nobackup` file because then the standard backup routines in RaspberryMatic will ignore this directory during backup.

**Comment by j-a-n** [comment]
By default, the downloaded firmware files will be deleted after installation, but I can add the .nobackup file anyway.

**Comment by jens-maus** [comment]
That would be great, yes!

**Comment by HJS72** [comment]
@jens-maus: I'm using rmupdate, but previous versions cannot be deleted. Your hint with the .nobackup file was the right conclusion. Now then backup file is back to 7 MB. Thanks for your Sunday support :-)

**Comment by jens-maus** [comment]
@HJS72 it's even Holiday support as I am currently on vacation. So where to send the bill? ;)
