### ISSUE TITLE
Fehlende Übersetzung unter Einstellungen

### ISSUE THREAD

**Issue by widmann-it** [jens-maus/RaspberryMatic#376]
Hier fehlt der Text unter Einstellungen - Geräte Firmware (Übersicht)

${thName}
${thTypeDescriptor}
${thPicture}
${thSerialNumber}
${thFirmware}
${firmwareAvailOnCCU}
${thAction}

**Comment by HMside** [comment]
Sofern Du Philips Hue eingebunden hast, liegt es daran. Hat Jens schon gefixt 3725ba1

**Comment by widmann-it** [comment]
?? Was hat die Meldung mit HUE zu tun - rein Intressenhalber ;-)

**Comment by libertyx82** [comment]
Der Anzeigefehler wird von einem gekoppelten HUE Gerät verursacht
