### ISSUE TITLE
Update der Firmware unter USB nicht möglich

### ISSUE THREAD

**Issue by MathiasJZ** [jens-maus/RaspberryMatic#377]
Ich finde es toll, dass man die Raspberrymatic auch auf USB-Stick bzw SSD laufen lassen kann. Großes Lob an Jens.
Leider muß man ein Update der Firmware dann manuell machen, Weder per WebUI noch über rmupdate ist eine Firmware-Aktuallisierung möglich.
Das System bleibt im Recovery-Mode stehen. Alle Eingaben werden mit Error quittiert.
Dann heißt es, Stecker ziehen.
Gruß,
Mathias

**Comment by StefanGubler** [comment]
Also wenn das so ist, dann bringt die schöne Funktion nichts. 
Wenn man bei einer Raspberrymatic vor Ort ist, geht das gut, wenn man dies über Remote machen möchte geht dies nicht. Schade

**Comment by MathiasJZ** [comment]
Es ist egal, ob Du vor Ort bist oder nicht.
Ein Update geht weder über rmupdate noch über der WebUI. Das heißt, SSD 
raus, neu flashen und wieder rein.
Gruß,
Mathias

Am 18. September 2018 18:19:51 schrieb StefanGubler <notifications@github.com>:

**Comment by bibo09** [comment]
ich finde es auch sehr schade, das dieses tolle feature nicht mehr gegeben ist.
Habe jetzt auch erstmal meine SSD gegen eine Micro SD ausgetauscht :(

**Comment by StefanGubler** [comment]
Das mit dem Tinkerboard werde ich mal ausprobieren, das hört sich interessant an,
wenn das Tinkerboard mit der eMMC dann stabil läuft und mit Stabil meine ich für Jahre.

Dann würde sich auch das Problem des Raspberry PI lösen, dass die Bootreihenfolge der USB drives sich ändert, wenn man zwei USB drives hat (OS und HomeMatic Daten).

**Comment by jens-maus** [comment]
Genau so ist es. Und der nächste RaspberryPi kommt sicher dann auch mit eMMC Unterstützung wieso sich dann noch mehr die Frage stellt warum man unbedingt eine über USB 2.0 angeschlossene SSD braucht. Trotzdem werde ich mir das nochmal bei Gelegenheit anschauen und ggf. lässt sich ja schnell eine Lösung finden damit man RaspberryMatic wieder auf externen USB Medien installieren kann – wenn man es denn will.

**Comment by MathiasJZ** [comment]
Genau dieser Meinung bin ich auch
Warum sollen wir jetzt auf ein Tinkerboard S umsteigen?
In ein paar Monaten sollen wir dann auf was wechseln, weil das Tinkerboard 
wieder zu alt ist?
Gruß,
Mathias

Am 27. September 2018 07:08:05 schrieb bibo09 <notifications@github.com>:

**Comment by jens-maus** [comment]
Ihr *sollt* gar nichts, ihr könnt. Es gibt auch hunderte Leute die benutzen erfolgreich eine SD karte und haben damit auch keine Probleme. Die CCU3 wird auch mit einer SD karte ausgeliefert und die gehen auch nicht dauernd kaputt.

**Comment by libertyx82** [comment]
Wenn man auf Nummer sicher gehen möchte nimmt man [die](https://www.sandisk.de/oem-design/industrial/industrial-cards)
Bei 384TBW sollte es da noch weniger Probleme geben und der Boot über USB mach alleine schon wegen der eingeschränkten Performance keinen Sinn.

**Comment by StefanGubler** [comment]
Das mit dem Tinkerboard wäre eine feine Sache.
Die SD-Card Mechanik im Tinkboard ist viel besser, Gutes ein- und ausrasten, nicht so wie beim Raspberry Pi, dazu dann noch der e-Mmc.
Sobald Jens Maus den Bug im Backup Restore für Tinkerboard behoben hat wird das verwendbar.

**Comment by MathiasJZ** [comment]
Ja ich weiß.
In ein paar Wochen sollen wir dann wieder umrüsten, weil es etwas neueres 
gibt, als das Tinkerboard.
Es müsste eigentlich jedem einleuchten:
Du bestellst Dir heute einen neuen Rechner.
Bevor er bei Dir ankommt, ist der längst überholt.
Ich bleibe erst mal beim PI3 B+. Wenn man dann noch von SSD aus booten 
kann, ist alles perfekt.
Ach ja, die Mechanik bzgl der Micro-SD gab es schon im PI 2B.
Mit freundlichen Grüßen,
Mathias Zaspel
Max-Kolmsperger-Str. 19
81735 München
Tel:  +49-89-21545410
Fax: +49-89-420955813
mail: mathias@zaspel.org

Am 30. September 2018 14:12:47 schrieb StefanGubler <notifications@github.com>:

**Comment by libertyx82** [comment]
Du kannst von einer SSD booten, nur macht das keinen Sinn, da über USB (2.0) angeschlossen du nur eine Raten von max 40MB/s hast.
Ich benutze seit über einem Jahr die gleiche SD Karte, daher kann ich nicht nachvollziehen, wo hier das Problem sein soll.

**Comment by StefanGubler** [comment]
Stimmt. Booten von SD-Card war stabil, auch bei mir, aber auf einer Raspberry PI in meinem Ferienhaus.
Liefe über Jahre stabil an der USV.
Mit dem neuen Pi B+ und dem neuen Funkmodul und einer neuen SC-Card hatte ich Probleme.
Nach einem Neustart und nach einem langen Stromausfall startete der Raspi von der SD-Card nicht mehr.
Alles andere startete einwandfrei auf, nur der Raspi nicht.
Dummerweise ist dies 1000km entfernt, da wird es schweirig mit der Fern Diagnose
deshalb suche ich etwas das stabil läuft und auch Stromausfälle und Reboots übersteht.

**Comment by MathiasJZ** [comment]
Dann erzähle mir doch mal, wie ich auf dieser SSD Updates installieren soll..
Weder über der WebUI noch über rmupdate ist das möglich.
Nach dem Neustart bootet der Raspberry  in den Recovery Modus,  jede 
Eingabe wird mit Error quittiert.
Leider hat der Raspberry nur eine USB2-Schnittstelle. Da hast Du recht. 
Aber meiner Meinung nach überwiegen die Vorteile gegenüber den Nachteilen.
Ich habe früher auf einem PI2 B eine Festplatte laufen lassen. Die 
Bootpartition blieb auf der SD.
Da gab's auch keine Probleme mit freepbx.

Am 30. September 2018 14:48:35 schrieb Dirk Schneider 
<notifications@github.com>:
