### ISSUE TITLE
Fehler in Geräte Firmware installieren

### ISSUE THREAD

**Issue by Rossini999** [jens-maus/RaspberryMatic#378]
![screenshot 2018-07-23 17 11 28](https://user-images.githubusercontent.com/41587772/43089806-eb89f350-8ea5-11e8-9f6a-752080650b0a.png)
Firmware: 2.35.16.201807.15
Man kann unter "Einstellungen/Geräte-Firmware-Übersicht" keine Firmware für Geräte hochladen. Die  Buttons "Zurück / Filter setzen / Geräte-Firmware" sind nicht vorhanden bzw. teilweise werden falsche Buttons angezeigt.
Zusätzlich werden die Spaltenüberschriften in der Tabelle nicht richtig angezeigt (Schönheitsfehler).
Fehler tritt bei Windows 10 Edge, Firefox und MacOS Safari gleichermaßen auf.
Der Fehler war auch schon in der vorherigen Version vorhanden.
Gruß
Dieter

**Comment by HMside** [comment]
Siehe #376

**Comment by Rossini999** [comment]
Hängt auch der Fehler mit den fehlenden Buttons an der Einbindung von HUE?

Von meinem iPad gesendet

**Comment by HMside** [comment]
Ja
