### ISSUE TITLE
Update via Webinterface schlägt fehl

### ISSUE THREAD

**Issue by tis-cs** [jens-maus/RaspberryMatic#379]
Hallo, 

habe gerade auf einem Raspi 3 versucht das Update zu installieren und bekomme immer folgenden Fehler, wenn ich die .zip über das WebIf hochlade:

<img width="480" alt="pastedgraphic-1" src="https://user-images.githubusercontent.com/24519878/43142546-f4a60376-8f58-11e8-8db9-2c984acef178.png">

Aktuell ist die 2.35.16.20180708 drauf, die ich zuvor über das Webinterface von einer frisch geflashten 2.31.25.20180625 geupdated hatte. Da ging es noch.

Danke und LG,
Timo

**Comment by HMside** [comment]
Und Du hast auch das richtige Update für den Pi3 geladen?
Zip nicht entpackt?
Mal mit einem anderen Browser probiert?
Welcher Browser wurde verwendet?

https://github.com/jens-maus/RaspberryMatic/releases/download/2.35.16.20180715/RaspberryMatic-2.35.16.20180715-rpi3.zip

**Comment by tis-cs** [comment]
Jap, war das rpi3 Archiv, welches ich nicht entpackt habe und via Chrome unter Mac updaten wollte.
Habe mal von meinem File sha256 kontrolliert, war auch passt. Bin ratlos... Ich teste gleich mal mit Firefox und Safari

**Comment by jens-maus** [comment]
Bei RaspberryMatic landet das new_firmware.tar.gz jedoch in /usr/local/tmp

**Comment by tis-cs** [comment]
unter  /usr/local/tmp liegt nur "last_backup.sbk".
Ich flashe dann heute mal auf eine neue Karte...

**Comment by dehell** [comment]
Ich habe auch Probleme mit dem Update, es bleibt bei mir im Fenster "Das Firmware-Update wird auf die RaspMatic übertragen.

Bitte haben Sie einen Augenblick Geduld. "
hängen. Aktuell ist die 2.35.16.20180715 drauf, die auch schon mit der WebGUI geladen wurde.
Die Homematic arbeitet ganz normal weiter.
Getestet mit Firefox, Edge und Chrome.

**Comment by DerChecker** [comment]
Bei mir startet die Prozentanzeige des Chrome Browsers immer wieder neu. manchmal bei 60% manchmal bei 81 PRozent. Das nervt ganz schön. Woran kann es liegen? Wie kann das Update mal sauber durchlaufen? Das ist leider seit mehreren Versionen bei mir so. Ich kann es mir nicht erklären.

**Comment by MrDart27** [comment]
Habe vor ca. 4 Monaten die RaspberryMatic in Betrieb genommen und mittlerweile mehrmals erfolglos versucht über die WebGUI (Browser: Firefox) ein Update einzuspielen. Auch bei bleibt das Update jedesmal in dem Dialog Fenster "Das Firmware-Update wird auf die RaspMatic übertragen. Bitte haben Sie einen Augenblick Geduld." hängen.
Letzte Konsequenz: Nach ca. 2-3h ziehe ich dann den Netzteilstecker und fahre das System wieder hoch. Eben dann ohne Update.
Übrigens: Der Versuch mit verschiedenen Browser hat leider auch keinen Erfolg gebracht. Jedoch ist interessant, daß jeder der Browser die RaspMatic WebGUI als "Diese Website ist nicht sicher." einstuft und erst mit Nachdruck (ja ich will diese unsichere Seite aufrufen!!) sich zum Aufruf der Seite bewegen läßt. Ist das normal?

Meine Software Version ist: 3.45.7.20190511

**Comment by Pepperronny** [comment]
Also das Problem habe ich auch schon seit länger Zeit.
Update via Chorme oder Firexox am Macbook bleibt beim Hochladen hängen.
Aber am  Android Tablet funktioniert es komischer weise.
Habe die letzten Versionen dann immer mit meinem Tablet via Chrome aufgespielt.

**Comment by IT-VBFK** [comment]
> Jedoch ist interessant, daß jeder der Browser die RaspMatic WebGUI als "Diese Website ist nicht sicher." einstuft und erst mit Nachdruck (ja ich will diese unsichere Seite aufrufen!!) sich zum Aufruf der Seite bewegen läßt. Ist das normal?
> 
> Meine Software Version ist: 3.45.7.20190511

Ja, ganz normal. Hängt nur mit einem SSL-Zertifikat zusammen, dass nicht von einer offiziellen CA autorisiert wurde.
