### ISSUE TITLE
Kein onboard WLAN mit ASUS Tinkerboard

### ISSUE THREAD

**Issue by RonVogt** [jens-maus/RaspberryMatic#380]
RaspiMatic 2.35.16.20180715 läuft auf meinem Tinker Board S aktuell nur mit Ethernet. Die Anleitung zur Aktivierung von WLAN funktioniert beim Tinkerboard S nicht. Verwendet wird das Funkmodul  RPI-RF-MOD. Gibt es bereits eine Möglichkeit WLAN für das Tinkerboard S mit dem RPI-RF-MOD zu aktivieren?

**Comment by jens-maus** [comment]
In den Testsystemen hier funktioniert das WLAN prinzipiell problemlos. Folgende Kommandosequenz zeigt alle verfügbaren WLANs in der Umgebung z.B. an:

```
rfkill unblock wlan0
iw wlan0 scan
```

Nach dem letzten Befehl sollte dann eine Ausgabe aller gefundenen WLANs ausgegeben werden.

**Comment by RonVogt** [comment]
Vielen Dank für die Antwort.

Nach Eingabe der Befehle werden mir auch alle WLAN aufgelistet. Dennoch verbindet sich das Tinker Board S nach einem Neustart (Ethernetkabel abgezogen) nicht mit dem eingetragenen WLAN. Bei meinem Raspberry 3b hat das problemlos funktioniert.

Ronald Günther
Gartenweg4
39245 Gommern OT Vogelsang
Am 28. Juli 2018, 15:32 +0200 schrieb Jens Maus <notifications@github.com>:

**Comment by jens-maus** [comment]
Alles klar, dann muss ich das noch bei Gelegenheit testen.

**Comment by RonVogt** [comment]
Danke schon mal.

Ronald Günther
Gartenweg4
39245 Gommern OT Vogelsang
Am 28. Juli 2018, 17:17 +0200 schrieb Jens Maus <notifications@github.com>:

**Comment by RonVogt** [comment]
Seit dem letzten Update werden die WLAN  nach einem Scan nicht mehr angezeigt.

**Comment by jens-maus** [comment]
@RonVogt Was wird denn an einem HDMI Monitor angezeigt sobald man beim booten auf einer Tastatur ALT+F2 drückt um Statusmeldungen auszugeben?!?

**Comment by ramazotti7** [comment]
Hallo Herr Maus,
ich habe heute mein neues Tinker Board S in Betrieb genommen, mit LAN auch kein Problem. Leider mit WLAN. Recherchen haben mich auf diese Seite gebracht, leider finde ich hier keine Hilfe zur Lösung meines Problems. 
Folgende vorgehensweise hat bei meinem pi 3b+ funktioniert, beim tinker board leider nicht:

rfkill unblock wifi
iw wlan0 scan		--> zeigt die Netzwerke an
--> in der Ausgabe nach der SSID suchen (xxx)
//Dann folgende Datei kopieren:
cp /etc/config_templates/wpa_supplicant.conf /etc/config/
wpa_passphrase "xxx" "abcabcyxxx" >>/etc/config/wpa_supplicant.conf
und Neustart ohne Lan-Kabel.
Gibt es hier tatsächlich Probleme oder mache ich etwas falsch?
Vielen Dank im Voraus für Ihre Mühe.
Rainer

**Comment by jens-maus** [comment]
Diese Symptome habe ich auch bereits festgestellt. Leider habe ich dafür jedoch noch keine Lösung/Grund gefunden warum man trotz gefundener SSIDs die WLAN Verbindung mit dem onboard-WLAN eines Tinkerboard nicht aufgebaut werden kann. Schaue ich mir bei Gelegenheit einmal näher an. Jedoch sei ohnehin noch einem darauf hingewiesen das ein aktiviertes WLAN auf dem Tinkerboard oder RaspberryPi auf dem auch das HM-MOD-RPI-PCB bzw RPI-RF-MOD am GPIO betrieben wird keine gute Idee ist da ws zu Störungen des HomeMatic Funkverkehres kommen kann. Daher hat das für mich niedrige Priorität.

Auch würde ich dazu raten besser einen externen WLAN USB Stick zu verwenden der mit langem USB Kabel abgesetzt wird. Dieser sollte problemlos am Tinkerboard funktionieren.

**Comment by libertyx82** [comment]
Wäre bei einem Thinkerboard S eine abgesetzte Antenne für's WLAN nicht ausreichend?
Ein i-PEX Anschluss ist ja beim S vorhanden.

**Comment by jens-maus** [comment]
Das könntest du probieren. Es kann auch gut sein das das onvoard WLAN eonfach nur nicht geht weil mit dem Funkmodul auf dem GPIO keine Verbindung zustande kommt. Also winfach probieren. Auf der anderen Seite sollte das mit einem USB WLAN Stick ja auch kein Problem sein...

**Comment by angler180** [comment]
Auch ich habe dieses Problem mit der fehlenden Wlan Verbindung.
Ich habe an den i-PEX Anschluss eine externe Antenne mit einem Kabel angeschlossen und direkt neben die Fritzbox gestellt.
Der SSID wird mit super Signalstärke gefunden, lässt sich aber nicht Verbinden.

**Comment by jens-maus** [comment]
Gut, dann können wir zumindest ausschliessen das das WLAN wegen der internen Antenne nur nicht geht. Vmtl. ist das alles irgendetwas kernel/software seitig und müsste mal debuggt werden.
