### ISSUE TITLE
usb ports keine fixe zuordnung

### ISSUE THREAD

**Issue by alexander-kog** [jens-maus/RaspberryMatic#381]
Die USB ports haben keine fixe zuordnung (usb0, usb1, ...). Daher passiert es wenn 2 USB Sticks am Raspi hängen und Stick1-usb0 und Stick2-usb1 zugeordnet ist, nach Herunterfahren oder Strom aus Stick1 auf usb1 geschaltet wird und Stick2 auf usb0, also vertauscht.

**Comment by jens-maus** [comment]
Das lässt sich leider nicht vermeiden denn es kommt drauf an welches USB gerät sich als erstes am System meldet, dann wird dieses eben zuerst unter `/media/usb1` gemountet und das zweite unter `/media/usb2`. Sehe auch momentan keinen Ansatz für Verbesserungen hier.
