### ISSUE TITLE
Possibility to add extra ca-certs

### ISSUE THREAD

**Issue by hobbyquaker** [jens-maus/RaspberryMatic#382]
In a future Release of RedMatic there will be flow-versioning via git (local and remote). For remote access to a repository via git+https it would be beneficial to have the possibility to add extra ca-certs in the systemwide certificate store. I guess it will be necessary to do that in an extra location (e.g. `/usr/local/etc/ssl/certs`?) because `/etc/ssl/certs` is on the readonly partition and would not survive updates?

(@jens-maus no need to do smth, will investigate on my own how this could be done and contact you then to discuss that. Issue just as reminder)

**Comment by jens-maus** [comment]
Just a hint from my side. Usually, if an application requires on ca-certs to be considered, they are specifying the path to the ca file/dir themself somewhere in the configuration (e.g. apache Webserver, etc.) So there must be a way to tell git to look in a certain different path (e.g. within the redmatic add-on directory) for other ca certificates.

**Comment by grusin** [comment]
i have just faced the same issue. I am getting CA cert errors while trying to push notifications to external service (Slack). 

buildroot contains package "CA Certs" in "→ Target packages → Libraries → Crypt" I am checking it out now, as i hope it will work like the debian's update-ca-certs one...

**Comment by jens-maus** [comment]
@grusin This package is already selected and part of RaspberryMatic.

**Comment by grusin** [comment]
issue resolved on my end, it was related to the fact that i run .net code in mono, and that has it's own cert store it seems. I had to run:

$ /usr/bin/mono /usr/lib/mono/4.5/mozroots.exe --import --machine --ask-remove

and it added 151 missing certs.

**Comment by jens-maus** [comment]
Is this issue still required? IMHO apps should carry their own ca-cert directories somehow...
