### ISSUE TITLE
Add git

### ISSUE THREAD

**Issue by hobbyquaker** [jens-maus/RaspberryMatic#383]
Do you think it would have any downsides to add `git` to the RaspberryMatic build? Would you accept a PR to include it in the build? 
Right now I'm shipping it with RedMatic, it's needed for npm installs, sometimes dependencies aren't on npmjs.org but referenced via Github repos. Will also be needed for a future feature of Redmatic (as mentioned in #382). I think it would be nice to have it systemwide available and then I could remove it from RedMatic in future. Wouldn't be surprised if other addons will need it too in future.

**Comment by jens-maus** [comment]
I can of course understand your reasoning, but I think that shipping RM per default with git is way to much for all users. In addition, even if shipped with RM something like git won't probably be added to the CCU3 firmware, so you anyway would need it to be shipped with your RedMatic add-on. So sorry, but I don't think that it makes sense to add it as a default package to RM. Perhaps it would fit better in the https://github.com/fhetty/hm-tools add-on, but of course this won't be a solution for you, I guess.

**Comment by hobbyquaker** [comment]
No problem, then I will keep it in the Addon, doesn't hurt. Just thought that future Addons (e.g. your planned ioBroker Addon) will need it too and the space requirements are relatively low, so I still see no downsides - but you decide :-)
