### ISSUE TITLE
raise an alarm message in case hss_led identifies a process is not running as expected (status red)

### ISSUE THREAD

**Issue by eberproducts** [jens-maus/RaspberryMatic#386]
Da ich gelesen habe, das die RGB LED über GPIO angesteuert wird, hätte ich den "Verbesserungsvorschläge-Vorschlag" den Status dieser LED im WEB UI ebenfalls abzubilden.
Bei mir hängt die CCU an einer nicht sehr übersichtlichen Stelle, und ich hatte bereits zweimal den Fall dass die LED rot war und ich aber in der Oberfläche und in der Funktion nichts großartiges bemerkt habe - ausser das etwas mehr Fehlermeldungen bzgl "Communication Error" kamen.
Hier wäre der Status der LED im Web Interface sehr hilfreich gewesen. Vielleicht lässt sich da ja implementieren ohne großen Aufwand.

**Comment by Erbit** [comment]
Something like that.
I have chosen my GPIO numbers experimentally.

`string RGB_R='gpio -g read 16';
string RGB_G='gpio -g read 20';
string RGB_B='gpio -g read 21';
string LED_RGB='';
string stdout;
string stderr;
 
system.Exec(RGB_R, &stdout, &stderr);
LED_RGB=LED_RGB#stdout.Trim();
system.Exec(RGB_G, &stdout, &stderr);
LED_RGB=LED_RGB#stdout.Trim();
system.Exec(RGB_B, &stdout, &stderr);
LED_RGB=LED_RGB#stdout.Trim();
WriteLine(LED_RGB);`

**Comment by Fiiti** [comment]
+1

**Comment by eberproducts** [comment]
Hi Erbit and Jens your script is working pretty good - so far -, but to get "all" modes from the LED - I mean the flashing modes as well - you have to trigger the script very often - nearly every second.
It would be much more better to implement some code into the main Program that can watch the status "change" and then shows the status within the same way under the other two status signs on the top of the WebUI (Alarm messages and Service messages)

**Comment by Erbit** [comment]
I think all statuses are in "Alarm messages" and "Service messages". I'm wrong?

**Comment by eberproducts** [comment]
here are (all?) statuses the RGB LED will show...
https://files.elv.com/Assets/Produkte/15/1529/152941/Downloads/152941_charly_fehlercodes.pdf

well - those statuses like the ccu startup sequence or the network startup sequence can not be shown - that is clear :-)

**Comment by jens-maus** [comment]
Sorry guys, but I have no plans to implement/integrate such an LED display in the WebUI because there are enough installations without any RPI-RF-MOD and the potential benefit of such a feature is IMHO very limited.

**Comment by eberproducts** [comment]
Well - the initial Intention was to Show the „red“ or „blue“ condition. Because my ccu is placed at a not really good visible place and i allready had the Situation of Status red and i didn’t saw it...

**Comment by eberproducts** [comment]
Hey Jens, thats great !! 
I just changed the request to your suggestion. 
Thanks a lot in advance !!!

**Comment by jens-maus** [comment]
Please note that with the latest version (3.45.5.20190330) this should be implemented now with the `Monit` based monitoring/watchdog. Thus, an alarm message should now be raised for all the conditions `hss_led` is also using.
