### ISSUE TITLE
No Ip Adress - ausgesperrt

### ISSUE THREAD

**Issue by jklasen** [jens-maus/RaspberryMatic#387]
Hallo,
habe mich ausgesperrt und versuche mich grade per direkt console vis ALT F2 anzumelden.
Bis jetzt erfolglos.
Kann mir da jemand einen tipp geben wie ich mir die IP wieder setzen kann oder zumindest auf DHCP wieder zurück kann?

Danke,

Jens

**Comment by jklasen** [comment]
btw. Ich habe zwei weitere LAN-GW im Einsatz und ausprobiert ob ich mich vertippt habe. Das SSH Passwort geht bei der ALT F2 console mit root definitiv nicht. :-(

**Comment by jklasen** [comment]
Neues Update - Habe ein Backup eingespielt bzw. neue SD Karte mit etcher re-imaged und ein backup eingespielt. Es geht wieder - bis auf 6 "Gerätekommunikation gestört" scheint alles OK zu sein. Habe die "alte" SD mal behalten. Kann mich auch auf der jetzt aktiven per ssh anmelden aber nicht in der ALT F2 console direkt ?

**Comment by jens-maus** [comment]
Bitte ans homematic forum wenden. Das hier ist ein bugtracker und kein Diskussionsforum.

**Comment by jklasen** [comment]
It's not a BUG it's a feature. Habe keine Lust das im forum zu diskutieren. Es er-scheint mir wie ein BUG (oder auch einfach nur ein "Un-Ding" zu sein) das ich mich so aussperren kann das noch nichtmal eine Anmeldung an der DCUI per root möglich ist... aber sei es drum.. Dennoch danke für die ganze Arbeit und das drumherum...
