### ISSUE TITLE
Unspezifisches Umbenennen von Programmnamen

### ISSUE THREAD

**Issue by RalphPungaKronbergs** [jens-maus/RaspberryMatic#388]
Seit dem Update auf 2.35.16.20180715 (Raspi3) zeigen sich zwei Probleme im Bereich der Programme:

Öffne ich aus der Liste der Programme unter "Programme und Verknüpfungen > Programme" ein Programm zur Bearbeitung mit Klick auf den Button "bearbeiten", wird ohne mein Zutun dem Namen des Programmes eine "1" oder "2" hinzugefügt und auch direkt so angezeigt, obwohl beim Öffnen des Programmes der Name des Programmes ohne diese Ziffer in der Übersicht angezeigt wird. Speichert man das Programm dann, wird diese Ziffer auch dem Programmnamen angehängt. Versucht man die Ziffer zu löschen, wird die Ziffer nach dem Editiervorgang wieder automatisch an den Programmnamen angehangen. Ein gleichnamiges Programm existiert in der Liste nicht. Das Löschen und Neuerstellen des Programmes bietet nur kurze Abhilfe - einige Versuche später trat hier das Problem erneut auf. Auch ein Neustart des Raspi brachte keine Besserung.

Dieses Problem tritt sporadisch und nicht reproduzierbar auf.

Hingegen, wenn ich ein Programm via Button "Einstellung als neues Programm speichern" abspeichern lasse, wird der Name nicht mehr automatisch um eine Ziffer ergänzt, sondern unter exakt dem Originalnamen gespeichert, so dass daraufhin zwei Programme mit dem gleichen Namen existieren.

![grafik](https://user-images.githubusercontent.com/2270478/43610701-2f8c53d2-96a7-11e8-9213-dcd7d7cb5da3.png)

Dieses Verhalten ist reproduzierbar und tritt immer auf. 

Grundsätzlich zeigen sich seitdem auch Probleme beim Abarbeiten der Programme - auf manche Trigger verschiedener Programme wird plötzlich nicht mehr reagiert. Hier lässt sich jedoch keine reproduzierbare Systematik erkennen.

**Comment by libertyx82** [comment]
> Grundsätzlich zeigen sich seitdem auch Probleme beim Abarbeiten der Programme - auf manche Trigger verschiedener Programme wird plötzlich nicht mehr reagiert. Hier lässt sich jedoch keine reproduzierbare Systematik erkennen.

Dieses Verhalten tritt bei mir auch auf, teilweise werden Programme sehr verzögert oder gar nicht ausgeführt.

**Comment by jens-maus** [comment]
Diese Verhalten kann ich leider hier nicht nachvollziehen. Es scheint wohl etwas in der Konfiguration bzw. dem Setup hier unterschiedlich zu sein. Um das Problem reproduzieren zu können wäre es hilfreich ein Backup einer solchen Umgebung (wo das passiert) hier zu haben. Kann das jemand zur verfügung stellen?
