### ISSUE TITLE
iobroker mit RM gemeinsam auf einem Tinker S (eMMC)?

### ISSUE THREAD

**Issue by medicusdkfz** [jens-maus/RaspberryMatic#389]
Hallo Jens,

danke für deine brilliante Arbeit mit RM... Ich habe problemlos von einem RaspberryPi3 auf ein Tinker Board S gewechselt. Dein Image läuft nun auf dem eMMC tadellos und das Einspielen des Backups funktionierte tadellos.

a) Wie führe ich jetzt Updates durch?
b) Läßt sich zusätzlich „iobroker“ auf dem TBS installieren? (Um die 2 IP-Adressen weiß ich...) Ideal wäre ein fertiges TBS-Image ;-)

Danke für deine Antwort im Vorraus.

Beste Grüße,
Pierre

**Comment by jens-maus** [comment]
Bitte solche Dinge im Homematic-Forum diskutieren. Das hier ist ein Bug/Issue-Tracker und kein Support-Forum.
