### ISSUE TITLE
lighttpd runs out of file descriptors

### ISSUE THREAD

**Issue by kroimon** [jens-maus/RaspberryMatic#39]
I am running a build of the latest commit 013d96f9e9deded24704a0a47cc88cd83189de8a on a Raspberry Pi 3 (with HMIP, working great so far).

I'm not sure about the cause for the problem, but every few hours, the webserver stops working. `/var/log/lighttpd-error.log` shows the line

```
2017-01-05 16:46:52: (server.c.1759) [note] sockets disabled, out-of-fds 
```

Restarting the webserver fixes the problem. A single `/etc/init.d/S50lighttpd restart` will not work because one lighttpd process keeps running, blocking port 80. I have to `/etc/init.d/S50lighttpd stop`, identify and kill the hanging process, and then `/etc/init.d/S50lighttpd start` again.

An example output of `lsof | grep lighttpd` shows no unusual file desriptor count:

```
297     /usr/sbin/lighttpd      /dev/null
297     /usr/sbin/lighttpd      /dev/null
297     /usr/sbin/lighttpd      /dev/null
297     /usr/sbin/lighttpd      /var/run/lighttpd.pid
297     /usr/sbin/lighttpd      socket:[1187]
297     /usr/sbin/lighttpd      /var/log/lighttpd-error.log
297     /usr/sbin/lighttpd      anon_inode:[eventpoll]
297     /usr/sbin/lighttpd      /var/log/lighttpd-access.log

300     /usr/sbin/lighttpd      /dev/null
300     /usr/sbin/lighttpd      /dev/null
300     /usr/sbin/lighttpd      /dev/null
300     /usr/sbin/lighttpd      /var/run/lighttpd.pid
300     /usr/sbin/lighttpd      socket:[5188]
300     /usr/sbin/lighttpd      /var/log/lighttpd-error.log
300     /usr/sbin/lighttpd      anon_inode:[eventpoll]
300     /usr/sbin/lighttpd      /var/log/lighttpd-access.log
```

In this example, process 300 terminated gracefully using the init.d script, while process 297 had to be killed manually using `kill 297`.

As far as I can see, `/etc/lighttpd/lighttpd.conf` contains `server.max-fds = 2048`. I can't see how this value should ever be reached.

**Comment by jens-maus** [comment]
This really sounds strange and doesn't reflect what I am seeing here with my test systems. The question is, however, if you can reproduce this issue with the old 4.4.36 kernel (one commit before the one you are using). To me this currently looks more like an issue of your local build environment. Have you tried to reproduce the issue also with the official 20161220 release?

**Comment by jens-maus** [comment]
I just checked my two test systems again and here I don't see any of these "out-of-fds" notifications. Thus, this worksforme. Are you sure your system is not simply flooded by http requests so that lighttpd might really run out of file descriptors?

**Comment by kroimon** [comment]
I found [this lighthttpd bug](https://redmine.lighttpd.net/issues/2771) which sounds similar and mentions problems with mod_cgi with constant polling.

I will keep an eye on my system and check the lighttpd access and error logs for any irregularities when it happens again. However, I don't think there were any request floods when it happened the last times.

**Comment by kroimon** [comment]
I just had the issue again. I was logged on to the webinterface and left it open for an hour or so. The access log just shows the regular update requests from my browser, nothing else. `killall lighttpd` followed by `/etc/init.d/S50lighttpd start` restores operation. The lsof output shows the ususal few file descriptors, so the lighttpd-internal fd counter seems to be off. I feel like we really run into the above-mentioned bug.

I still don't understand all of the buildroot build process. What do I have to change to use the latest lighttpd version 1.4.44 in my build? The changelog mentions the "mod_cgi: fix out of sockets error for POST to CGI (1.4.43)" bugfix, so that might resolve my issue.

**Comment by kroimon** [comment]
I modified the `buildroot-2016.11\package\lighttpd\lighttpd.mk` and corresponding hash file to use the latest version of lighttpd. I will now flash the image to my raspberry and test if that helped.

**Comment by jens-maus** [comment]
Thanks for the followup. 1.4.44 might really fix that issue. However, I still don't get why I don't suffer from these kind of issues. However, if the issue is resolved for you with 1.4.44 I will see if I can either introduce the fix as a patch for the lighttpd package or introduce a patch that bumps the whole build process for lighttpd to use 1.4.44 as its base version. In addition, we should also see if this issue was already reported to the buildroot developers so that they will bump to 1.4.44 as well.

**Comment by kroimon** [comment]
I'm running my build for about 2 hours now, with about 4000 requests in my `lighttpd-access.log`. So far, the lighttpd server did not report any issues.

The buildroot team did already update lighttpd to version 1.4.44 in commit buildroot/buildroot@b36b2d023fc30a1b6fd2616e6f53d61b90ca0ab3, to be included in the next buildroot version 2017.02. As this release is at least a month away, we could either include the linked commit as a patch until then, or change to a snapshot build of buildroot.

**Comment by jens-maus** [comment]
Thanks for the hint. I also noticed that in 2017.02 it will be fixed. However, until this release is out I will add a buildroot patch to our repository which will simply bump the lighttpd version to 1.4.44.

**Comment by kroimon** [comment]
Nevermind, I failed with my build:
```
# lighttpd -v
lighttpd/1.4.43 (ssl) - a light and fast webserver
Build-Date: Jan  5 2017 23:25:01
```
For some reason, it overwrote my changes to the buildroot config?! I'll try again tomorrow and report back...

**Comment by jens-maus** [comment]
Ok, not my latest checkin. I added a buildroot patch to bump the requested version of lighttpd to 1.4.44 and then run the buildroot build. While this should work out-of-the-box, it is untested by me. So please rebuild your whole raspberrymatic buildroot environment. So make a `make distclean` and then run `make dist` again. Afterwards you should have 1.4.44 installed for your tests. If this finally works, please report ASAP so that I can close this ticket.

**Comment by kroimon** [comment]
Had my c249e8872c41added0bbe83cf4075dbdbb53f388 build running for about 18 hours now, with my browser logged in and polling updates for the last 12 hours, still no issue.

```
# lighttpd -v
lighttpd/1.4.44 (ssl) - a light and fast webserver
Build-Date: Jan  6 2017 02:46:43
# uptime
 21:14:16 up 17:48,  load average: 0.00, 0.06, 0.02
# wc -l /var/log/lighttpd-access.log
21639 /var/log/lighttpd-access.log
# cat /var/log/lighttpd-error.log
1970-01-01 01:00:13: (log.c.217) server started
1970-01-01 01:00:13: (log.c.217) server started
2017-01-06 03:26:21: (mod_proxy.c.1041) establishing connection failed: Connection refused
2017-01-06 03:26:21: (mod_proxy.c.1153) proxy-server disabled: 127.0.0.1 8181 9
2017-01-06 03:26:21: (mod_proxy.c.523) no proxy-handler found for: /
2017-01-06 03:26:21: (mod_proxy.c.523) no proxy-handler found for: /esp/system.htm
2017-01-06 03:26:26: (mod_proxy.c.1417) proxy - re-enabled: 127.0.0.1 8181
```

I therefore think updating lighttpd to 1.4.44 fixed the bug, closing this issue now. Thanks a lot for your support and quick response times!
