### ISSUE TITLE
Tinkerboard + Elements14 AddonBoard - korrekt nur bis Version ...428

### ISSUE THREAD

**Issue by piotek** [jens-maus/RaspberryMatic#390]
Bei Einsatz des Tinkerboards oder Tinkerboards S mit dem Element14 AddonBoard funktioniert
das Handling des Power Knopfes incl. LED bei Einsatz des alten Funkmoduls bis Tinker Raspi Version 0428 
korrekt. Danach leider gar nicht mehr .... Siehe auch 
https://homematic-forum.de/forum/viewtopic.php?f=65&t=44194&start=30

**Comment by jens-maus** [comment]
Tut mir leid. Ich sehe hier aktuellen keinen Handlungs- bzw. Reparaturbedarf. Das PiDesktop ist rein für RaspberryPi Geräte ausgelegt und nicht für Tinkerboard. Insofern sind diese Problem bekannt und nicht zu vermeiden.
