### ISSUE TITLE
Battery threshold for service messages

### ISSUE THREAD

**Issue by foxriver76** [jens-maus/RaspberryMatic#392]
Recently I experienced the following behaviour according to the battery service messages:

The battery threshold value, which can be configured by the user in the configuration of the thermostat is set to 2.1 V -- a few days ago the value dropped to 2.3 V and the Homematic Web UI showed me a service message that the battery is empty. 

In my honest opinion the configured threshold value should be used to define when it's time to generate the service message.

Firmware: 2.35.16.20180715

best regards and thanks for the good work

**Comment by jens-maus** [comment]
Sorry, but this is no RaspberryMatic specific issue but rather a potential issue of the general CCU firmware. So please discuss that in the homematic forum and report that issue to the vendor (eq3) instead.
