### ISSUE TITLE
Homematic IP gerate lassen sich nicht anlernen 

### ISSUE THREAD

**Issue by manna57** [jens-maus/RaspberryMatic#394]
Ich habe 3 neue Homematic IP Geräte zum anlernen 2 x HMIP-PSM und  1x´den einen Lichtsensor.
alle Geräte kann ich nicht anlernen, auch nicht über den lokalen weg.
alle Geräte wurden Biets auf factory default zurückgesetzt, Raspberrymatic, rebooted. Alles ohne Erfolg .
Hat jemand eine Idee, wie ich das lösen kann?

**Comment by jens-maus** [comment]
Das hier ist ein Bug-/Featuretracker und kein Diskussions/Hilfeforum. Bitte an homematic-forum.de wenden.
