### ISSUE TITLE
Port 2001 for OpenHAB connection not available

### ISSUE THREAD

**Issue by BenjaminHae** [jens-maus/RaspberryMatic#395]
I'm trying to connect RaspberryMatic with OpenHAB using the [homematic binding](https://docs.openhab.org/addons/bindings/homematic/readme.html).

The documentation says it needs access to port 2001 for accessing the rf components.

When I try to setup the connection in OpenHab it tries to connect to this port on RaspberryMatic, but the connection fails.
netstat on RaspberryMatic shows there is nothing behind this port:
```
# netstat -tlpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:1999            0.0.0.0:*               LISTEN      601/ReGaHss
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      420/lighttpd
tcp        0      0 0.0.0.0:8181            0.0.0.0:*               LISTEN      420/lighttpd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      436/sshd
tcp        0      0 0.0.0.0:8183            0.0.0.0:*               LISTEN      601/ReGaHss
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      420/lighttpd
tcp        0      0 0.0.0.0:8700            0.0.0.0:*               LISTEN      479/cuxd
tcp        0      0 0.0.0.0:8701            0.0.0.0:*               LISTEN      479/cuxd
tcp        0      0 127.0.0.1:705           0.0.0.0:*               LISTEN      512/snmpd
```

Do I need to activate something in RaspberryMatic?

**Comment by jens-maus** [comment]
Sorry, but which RaspberryMatic Version are you using? Here I can perfectly see lighttpd listeninh for requests on port 2001:

```
# netstat -tlpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      484/lighttpd
tcp        0      0 127.0.0.1:705           0.0.0.0:*               LISTEN      563/snmpd
tcp        0      0 0.0.0.0:1999            0.0.0.0:*               LISTEN      725/ReGaHss
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      484/lighttpd
tcp        0      0 0.0.0.0:2001            0.0.0.0:*               LISTEN      607/rfd
tcp        0      0 0.0.0.0:8181            0.0.0.0:*               LISTEN      484/lighttpd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      499/sshd
tcp        0      0 0.0.0.0:8183            0.0.0.0:*               LISTEN      725/ReGaHss
tcp        0      0 :::2010                 :::*                    LISTEN      624/java
tcp        0      0 :::443                  :::*                    LISTEN      484/lighttpd
tcp        0      0 :::9292                 :::*                    LISTEN      624/java
tcp        0      0 :::80                   :::*                    LISTEN      484/lighttpd
tcp        0      0 :::8181                 :::*                    LISTEN      484/lighttpd
tcp        0      0 :::22                   :::*                    LISTEN      499/sshd
```

Have you checked your firewall settings? Please check the settings for access to the remote scripting engine.

Also note that this is not a support forum but a bug/issue tracker. Thus, please discuss this issue at homematic-forum.de instead.

**Comment by BenjaminHae** [comment]
When it should be on by default and isn't on my installation I'd call it a bug.
I've installed the latest release of Raspberrymatic on a pi zero and I use the latest firmware: 2.35.16.20180715

**Comment by jens-maus** [comment]
Please check if "rfd" is running because that's the process listening on port 2001 usually. Which hardware are you usibg to conmunicate with homematic devices? HM-MOD-RPI-PCB?

**Comment by BenjaminHae** [comment]
I'm using HM-MOD-RPI-PCB on a pi zero.

The rfd process is not running, starting it generates the log
```
Aug 25 12:21:04 homematic-raspi user.info rfd: BidCoS-Service started
Aug 25 12:21:04 homematic-raspi user.info rfd: XmlRpc Server is listening on TCP port 2001
Aug 25 12:21:04 homematic-raspi user.warn rfd: opendir(/etc/config/firmware//) failed
Aug 25 12:21:04 homematic-raspi user.err rfd: No BidCoS-Interface available
Aug 25 12:21:04 homematic-raspi user.warn rfd: Error initializing interfaces
```
So I'm looking into that error.
Thanks for pointing me into this direction.

**Comment by BenjaminHae** [comment]
Weird thing is in the WebUI everything seems to work.

**Comment by jens-maus** [comment]
But if rfd is not running no communication to BidCos devices are possible.

**Comment by BenjaminHae** [comment]
Ok, I doesn't work now. So I'm going to check the hardware. Must be a user-problem.
Sorry for keeping you in the loop. Thanks for your support.

**Comment by jens-maus** [comment]
Connect a hdmi monitor and press ALT+F2 to see bootup messages and error messages during bootup. Also show in the /var/hm_mode file if your interface was recognized correctly.
