### ISSUE TITLE
Raspi3 als LAN Gateway: "nicht verbunden"

### ISSUE THREAD

**Issue by 37wh5r** [jens-maus/RaspberryMatic#397]
Ich habe zwei identische schwarze ELV-Kästchen mit Raspi3 und RPI-RF-MOD im Einsatz, beide unter RaspberryMatic 2.35.16.20180826. Das eine habe ich als LAN Gateway konfiguriert (gemäß https://technikkram.net/2017/03/raspberrymatic-raspberry-pi3-als-lan-gateway-verwenden, startet auch korrekt im "LAN-Gateway Mode"), das andere ist seit längerem meine Zentrale. Egal was ich mache, die Zentrale erkennt beim Neustart nur mein ebenfalls vorhandenes altes LAN-Gateway (im weißen CCU2-Look), aber der Raspi erscheint immer als "nicht verbunden". Was kann ich tun zwecks genauerer Diagnose?

**Comment by 37wh5r** [comment]
Ich habe diese Einträge in /var/log/messages der Zentrale. Das Raspi-Gateway ist PEQ0627785. Offensichtlich muss man ein Gateway mittlerweile anders konfigurieren als in obigem Link beschrieben, einfach nur "touch /usr/local/HMLGW" reicht nicht?

Aug 28 18:15:35 homematic-raspi user.info root: Updating RF Lan Gateway Firmware
Aug 28 18:15:35 homematic-raspi user.info update-lgw-firmware: LAN Gateway Firmware Update...
Aug 28 18:15:35 homematic-raspi user.info update-lgw-firmware: Gateway NEQ0218880
Aug 28 18:15:37 homematic-raspi user.info update-lgw-firmware: Gateway type is eQ3-HM-LGW-App
Aug 28 18:15:37 homematic-raspi user.info update-lgw-firmware: Available Firmware Version:   1.1.5
Aug 28 18:15:37 homematic-raspi user.info update-lgw-firmware: Lan Gateway Firmware Version: 1.1.5
Aug 28 18:15:37 homematic-raspi user.info update-lgw-firmware: Firmware is up to date
Aug 28 18:15:37 homematic-raspi user.info update-lgw-firmware: LAN Gateway Firmware Update...
Aug 28 18:15:37 homematic-raspi user.info update-lgw-firmware: Gateway PEQ0627785
Aug 28 18:15:39 homematic-raspi user.info update-lgw-firmware: Gateway type is eQ3-HM-CCU2-App
Aug 28 18:15:39 homematic-raspi user.err update-lgw-firmware: Wrong type of gateway. Should be HMLGW2, but found 
Aug 28 18:15:39 homematic-raspi user.info root: Updating Wired Lan Gateway Firmware
Aug 28 18:15:39 homematic-raspi user.info update-lgw-firmware: No gateway found in config file /etc/config/hs485d.conf
Aug 28 18:15:47 homematic-raspi user.err setlgwkey: Could not determine IP Address of Lan Gateway with serial number PEQ0627785
Aug 28 18:15:47 homematic-raspi user.err setlgwkey: Error reading network configuration.
Aug 28 18:15:47 homematic-raspi daemon.info snmpd[628]: Created directory: /var/lib/snmp
Aug 28 18:15:47 homematic-raspi daemon.info snmpd[628]: Created directory: /var/lib/snmp/cert_indexes
Aug 28 18:15:47 homematic-raspi daemon.info snmpd[628]: Created directory: /var/lib/snmp/mib_indexes
Aug 28 18:15:47 homematic-raspi daemon.info snmpd[628]: Turning on AgentX master support.
Aug 28 18:15:47 homematic-raspi daemon.info snmpd[630]: NET-SNMP version 5.7.3
Aug 28 18:15:47 homematic-raspi user.info kernel: [   64.273266] eq3loop: created slave mmd_hmip
Aug 28 18:15:47 homematic-raspi user.info kernel: [   64.273530] eq3loop: created slave mmd_bidcos
Aug 28 18:15:50 homematic-raspi user.info kernel: [   66.480361] eq3loop: eq3loop_open_slave() mmd_bidcos
Aug 28 18:15:52 homematic-raspi user.err rfd: UnifiedLanCommController::connect(): Unable to connect.
Aug 28 18:15:52 homematic-raspi user.crit rfd: CCU2LGWCommController::init(): Cannot connect to HomeMatic Lan Gateway with serial number PEQ0627785.

**Comment by 37wh5r** [comment]
Ok, habe es gefunden - es funktioniert gar nicht mit dem RPI-RF-MOD...

**Comment by jens-maus** [comment]
Gensu so ist es. Mit einem RPI-RF-MOD geht der LAN Gateway Modus nicht.
