### ISSUE TITLE
PRESS_LONG and PRESS_LONG_RELEASE behaviour

### ISSUE THREAD

**Issue by Sineos** [jens-maus/RaspberryMatic#399]
### Description
I'm using RedMatic to query a `HM-PB-6-WM55` and I want to use the `PRESS_LONG` / `PRESS_LONG_RELEASE` events.
The sequence in which the events are produced makes it IMHO impossible to control something useful with it.
Here is a long press as seen by a Node-Red debug node:

![grafik](https://user-images.githubusercontent.com/4459312/44955436-8a736f00-aeb3-11e8-82aa-58d5ba0b65e8.png)

At 13:13:52 I started pressing the switch and at 13:13:58 I released the switch again.

### Actual behavior:
- With a pressed switch a continuous flow of `INSTALL_TEST` events is created.
- The `PRESS_LONG` event is actually generated when the switch is released
- The `PRESS_LONG_RELEASE` is generated right after the `PRESS_LONG` event

### Expected behavior
- The `PRESS_LONG` event shall be issued after the specified `PRESS_LONG` time in the device
- The `PRESS_LONG_RELEASE` shall be generated when the switch is released

Ping @hobbyquaker although I do not think this behavior is RedMatic related.

**Comment by hobbyquaker** [comment]
Afaik this depends on the Device, some behave strange regarding `PRESS_CONT` and `PRESS_LONG_RELEASE` events. For the HM-PB-6-WM55 I'm working around that by just using the `INSTALL_TEST` event as a `PRESS_CONT` replacement... 
Some Devices also need to have a `setValueUsage` registered on the Channel, otherwise they don't generate all events. You can do that via the RPC interface with e.g. Homematic Manager or by just creating a "Dummy" Rega Program that is triggered by that channel and does nothing. I fear this is nothing Jens can fix, I suppose this behavior depends on the Device Firmware and rfd solely.

**Comment by Sineos** [comment]
True, `PRESS_CONT` is not even send for the `HM-PB-6-WM55`, although it should acc. to the documentation.

> For the HM-PB-6-WM55 I'm working around that by just using the INSTALL_TEST event as a PRESS_CONT replacement...

Thought about this, but since `PRESS_SHORT` also generates one of these, it gets quite uncomfortable (though doable).

> Some Devices also need to have a setValueUsage registered on the Channel, otherwise they don't generate all events. You can do that via the RPC interface with e.g. Homematic Manager or by just creating a "Dummy" Rega Program that is triggered by that channel and does nothing.

I did not find `setValueUsage`  Homematic Manager's RPC console, so i tried:
![grafik](https://user-images.githubusercontent.com/4459312/44956578-87ce4500-aec6-11e8-9ae2-a88e7c2d7a5c.png)

but this does not change anything in the device's behavior. But anyway good to know that this might be changing a device behavior.

> I fear this is nothing Jens can fix, I suppose this behavior depends on the Device Firmware and rfd solely.

I was already afraid, that it might be device firmware related. 
Which, in combination with RedMatic is a real pity, since it would allow for a true "continuously pressed button simulation" just like a hardware push button.

**Comment by hobbyquaker** [comment]
> I did not find setValueUsage

Oh, yes, sorry. It's called `reportValueUsage` :)

**Comment by Sineos** [comment]
@lukicsl you made my day. Many thanks for this input, it works. 
Disabling AES makes the device send `PRESS_LONG`, `PRESS_CONT` and `PRESS_LONG_RELEASE` in the correct sequence.
Absolutely makes no sense, but hey 👍

**Comment by FrankHomeMatic** [comment]
I would also like to have these events `PRESS_CONT` and `PRESS_LONG_RELEASE` as usable additional events in WebUI programs. Espacially when you want to dim wired components with remote controls it would be very useful.
The drop-down menu with `PRESS_SHORT` and `PRESS_LONG` should be enhanced with the 2 other events. To prevent unfamiliar users from using these events to trigger other radio commands, perhaps they only should be visible in expert mode.

**Comment by jens-maus** [comment]
Is this issue still valid? Is there still something in the WebUI / RaspberryMatic that needs to be adapted?

**Comment by jens-maus** [comment]
Ich hoffe mal @jp112sdl kann hier vielleicht als alter BidCos-RF HomeMatic Feedback geben da ich hier gerade am Tickets aufräumen bin und schlecht selber einschätzen kann inwieweit dieses Ticket/Issue hier noch relevant ist bzgl. `PRESS_LONG` und `PRESS_LONG_RELEASE`?

**Comment by jp112sdl** [comment]
Hmm, hier kenne ich mich gar nicht aus.
Müsste nicht zunächst die ReGaHss diese beiden Events als Condition verarbeiten können?
