### ISSUE TITLE
irtrans unter raspberrymatic steuern

### ISSUE THREAD

**Issue by Lars271** [jens-maus/RaspberryMatic#400]
Hallo,

Ich habe ein raspberry 3b+ mit RPI-RF-MOD. Nachdem ich das Backup ingespielt hatte laufen die normalen programme. 
Auch Skripte als push-mitteilungen über cloudmatic funktionieren.
Jedoch gibt es ein problem bei irtrans. Unter der CCU2 lief es im Legacy modus. Dieser ist in der raspberrymatic nicht erreichbar. Gibt es eine neue Möglickeit?

Die Bespreibung des Herstellers habe ich angehängt.
[IRTrans + Homematic.pdf](https://github.com/jens-maus/RaspberryMatic/files/2358614/IRTrans.%2B.Homematic.pdf)
Die Herstellerseite ist hier zu finden http://www.irtrans.com/en/homeautomation/
Lars

**Comment by jens-maus** [comment]
Das Problem ist der in der Anleitung nicht mehr korrekte Skript bzw. das dort verwendete `system.Exec()` Kommando:

```
string stdout;
string stderr;
string url="http://192.168.153.26/send.htm?remote=klima01&command=an23";
system.Exec("wget -q -O /dev/null " # url, &stdout, &stderr);
```

Dieses muss in das folgende Skript abgeändert werden:

```
string url="http://192.168.153.26/send.htm?remote=klima01&command=an23";
system.Exec("wget -q -O /dev/null '" # url # "' &");
```

D.h. die `url` variable muss im Aufruf in einfache Anführungszeichen gesetzt werden damit die Sonderzeichen in der URL `&` korrekt interpretiert werden.

In Zukunft bitte jedoch solche Dinge im HomeMatic Forum besprechen/diskutieren. Das hier ist ein Bugtracker und kein Support-Forum.

**Comment by Lars271** [comment]
hui, das ging ja schnell.  Danke
