### ISSUE TITLE
Update auf 2.35.16.2018-08-26 schlug fehl

### ISSUE THREAD

**Issue by Lars271** [jens-maus/RaspberryMatic#401]
Hallo,

Habe auf die Version upgedatet und nach einem Neustart lief es auf einmal nicht mehr.
Blaue LED leuchtete dauerhaft.
Die Googlesuche ergab, dass neu installiert werden muss und das BackUp neu einspielen.
Ich vermute das dies an dem zwischenzeitlich intsallierten AddOn HM-print-1.2a.tar.gz lag.
Konnte ich aber nicht genauer eingrenzen, da ich befürchtete das die HW beschädigt ist. Ich war mit der Neuinstallation wohl etwas vorschnell.

Jetzt läuft wieder alles
Somit ist dies wohl nur zur Info.
Für das nächste mal: Kann ich auf die raspberrymatic noch Online rauf und den fehlenden Dienst von Hand starten?
Oder kann ich nach solch einem Crash nur noch den ErrorLog der Karte auslesen und dann Neuinstallieren?

Alles Gute und viel Erfolg.
Lars

**Comment by jens-maus** [comment]
Wie schon im anderen Ticket gesagt: GitHub ist kein Diskussionsforum sondern eine Entwicklungsplatform und das hier ein Bugtracker und kein Diskussionsforum. Daher bitte im Homematic Forum diskutieren.
