### ISSUE TITLE
ssh password can't be set

### ISSUE THREAD

**Issue by johannsele** [jens-maus/RaspberryMatic#402]
Hello there,

I just insalled the latest RasberryMatic downloaded today. Enabling SSH an saving was possible.
Enabling SSH and set a new password leads to a timeout after about 10 min "Die Einstellungen werden gespeichert!"-Message.

Trying to login via Putty (V0.7) gives me an acces denied response even if I'm using the user: root without password after enabling ssh without password.

Is this an issue or just an user mistake?

Thanks in advance for helping.

**Comment by jens-maus** [comment]
User problem!

**Comment by johannsele** [comment]
any advice?

**Comment by jens-maus** [comment]
Please ask in the homematic fora this is a big/issue tracker! Thanks

**Comment by johannsele** [comment]
thank you.
