### ISSUE TITLE
ping gpio18 already requested

### ISSUE THREAD

**Issue by StefanGubler** [jens-maus/RaspberryMatic#403]
**Describe the bug and the tests done **

The Raspberrymatic was no more working. So I did a reboot.
As no connection was possible, connected a monitor to the raspberrymatic.
It showed the error message and below it mentioned :  NO IP Addresss

Then flashed a new SD-Card with the newest raspberrymartic image and started up.
it showed then the same error message and showed the IP-Address  192.168.25.138
Bug1:     The IP-Address listed was wrong, it had the DHCP Address  192.168.25.130

Then restored the latest backup.

On the screen, the same error message, but with the correct IP Address,

Bug 2:

![20180918_094230small](https://user-images.githubusercontent.com/43369612/45674346-3ad8a880-bb2d-11e8-8d1c-10f5f769b5bd.jpg)
Error message on this screen. 
Then at the end

**Additional tests to Reproduce and  to find the cause**

- flashed again the SD-Card that had the error, flashing with verify without errors (I use alsways Samsung or SanDisk SD-Cards, no cheap ones.)

- changed to use a USB-Stick as the disk. The same error message on the screen.

**Screenshots**
see above

**System information (please complete the following information):**
 - Version 
 - Hardware Raspberry Pi 3B+ with new HM-Transmission Module  RPI-RF-MOD | 

**Additional context**

I'm a bit afraid of the new RPI-RF-MOD.  
I have three installations. The  Rapsberrymatic with the HM-MOD-RPI-PCB was working very stable.
Running for a year without issues. 

Now with the new Raspberry Pi 3B+ and the RPI-RF-MOD I have lots of issues.
Event that the Raspberrymatics are all running on UPS to protect them the issues are more than before.
The SD-Cards do not work for a long time,  after a rebvoot or after a power loss they do not work or they have a defect.  
With the LAN-Gateways I never had issues, but now, sometimes the LAN-Gateways show a Duty-Cycle of -1 .....

You can also respond me in german, as you like.

**Comment by jens-maus** [comment]
These messages are no bug and can be safely ignored.

**Comment by StefanGubler** [comment]
Was macht man denn beim ursprünglichen Fehler ?
wenn steht:  NO IP Adress ?

"It showed the error message and below it mentioned : NO IP Addresss"

**Comment by jens-maus** [comment]
Das hier ist ein bugtracker und kein Diskussions- oder Hilfeforum. Bitte an homematic-forum.de wenden.
