### ISSUE TITLE
Defektes Journal auf der 3. Partition

### ISSUE THREAD

**Issue by Fishy78** [jens-maus/RaspberryMatic#406]
Ich habe jetzt auf Grund von Stromausfällen zweimal dass Problem gehabt, dass das Journal der mmcblk0p3 korrupt war und der Raspberry nicht startete, da er dorthin scheinbar eine Kopie der Konfiguration generiert. Die einzige/einfachste Möglichkeit, die ich dann habe (Netzwerk funktioniert nicht, ssh daher auch nicht), ist die SD-Karte in einem debian zu prüfen und zu reparieren.

Zwei Vorschläge daher:
Wenn die Konfiguration nicht generiert werden kann, sollte das System entweder eine RAM-Disk generieren und dort eine Notfallkonfiguration erstellen, so dass die Raspberrymatic ersteinmal „läuft“ und eine Servicemeldung ausgibt und man dann via ssh eingreifen kann oder (gefährlicher) ein entsprechendes fsck selbstständig durchführen....

**Comment by jens-maus** [comment]
Mit dem bereits gemergten pull request #405 sollte das problem behoben sein und RaspberryMatic automatisch bei einem korrupten `/usr/local` den filesystem check automatisch während des bootens ausführen und ein solches filesystem reparieren.
