### ISSUE TITLE
Cloudmatic installation nicht möglich 

### ISSUE THREAD

**Issue by AndynordSee** [jens-maus/RaspberryMatic#407]
Moin Moin 
erstmal vielen dank für deine arbeit, mag mir nicht vorstellen was ich ohne deinen Port der ccu2 auf den pi gemacht hätte, wäre wahrscheinlich zu HmIP( eher nicht ) oder zu irgendwas anderes abgewandert wäre.

Aber zum Issue  : 
Habe die Anlage  (Pi 3 B + RPI-RF-MOD und ELV Steckernetzteil 5V, 2,5 A) neu aufgesetzt .
Dein neues Image :  RaspberryMatic-3.37.8.20180922-rpi3.zip, 
per Etcher auf eine 16GB Class 10 sandisk geschrieben.
Anschließend das Backup was auf einer RaspberryMatic 2.35.16.20180826 erstellt wurde eingespielt.
Dann noch einen neustart durchgeführt und über "Zusatzsoftware die "vpnkey_ccu2.tar.gz" für CCU2, CCU3 oder RaspberryMaticvon von Cloudmatic versucht einzuspielen.

Bekomme erst die Meldung :  
" Die Zusatzsoftware wurde hochgeladen. Sie können jetzt durch Klick auf die Schaltfläche unten die Installation starten"

Dann auf "Installation Starten" 
geklickt und ca 2 sec später:

"Error (1)"
"Ein unerwarteter Fehler ist während der Addon-Installation aufgetreten. Bei der hochgeladenen Datei handelt es sich entweder nicht um ein Addon-Archiv, ist defekt oder ist für eine andere Hardware vorgesehen. Bitte versuchen Sie es erneut oder kontaktieren Sie den Autor des Addons."

Habe dann die "vpnkey_ccu2.tar.gz" bei Cloudmatic erneut heruntergeladen, 
auch wieder die für "CCU2/CCU3"  (Ihr persönlicher Schlüssel für die CCU2, CCU3 oder RaspberryMatic .)

Trotzdem Das gleiche Ergebnis.

Habe das ganze getestet unter Windows 10 mit :  
1.mit Chrome 68.0.3440.106 (Offizieller Build) (64-Bit) (cohort: Stable)
2. Microsoft Edge 42.17134.1.0.

Habe dann das ganze nochmal mit der RaspberryMatic 2.35.16.20180826 und der CCU3 mit Orginal Software ohne Probleme getestet.

Somit gehe ich davon aus das die "vpnkey_ccu2.tar.gz" nicht das Problem ist. 

Werde es jetzt noch mal mit einem update von:
RaspberryMatic 2.35.16.20180826 auf RaspberryMatic 3.37.8.20180922 testen.

Schöne Grüße Andy 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
 - Version [e.g. RaspberryMatic 3.37.8.20180922]
 - Hardware [e.g. RaspberryPi3, TinkerboardS, etc.]

**Additional context**

**Comment by jens-maus** [comment]
Doch, das problem existiert in den `vpnkey_ccu2.tar.gz` Installationsroutinen. Der Hersteller muss hierbei diese Anpassen. Allerdings ist der Fehler nicht kritisch, d.h. hier sollte trotzdem eine korrekte Installation durchgeführt werden. D.h. der Fehler kann ignoriert, aber sollte trotzdem den Machern von CloudMatic bekannt gemacht werden.
