### ISSUE TITLE
Automatisches Backup abschaltbar bzw. auf anderen Pfad anwendbar machen.

### ISSUE THREAD

**Issue by MathiasJZ** [jens-maus/RaspberryMatic#409]
Kann man bei einem neuen Release von Raspberrymatic das automatische Backup wieder entfernen?
Zum einen macht ein Backup auf einem angeschlossenem USB-Stick nicht wirklich Sinn, zum anderen ist es (ich hoffe nicht nur für mich) störend. Ein Backup gehört (meiner Meinung nach) auf eine NAS mit einer gespiegelten Festplatte und nicht auf ein System von dem das Backup kommt.
Gruß,
Mathias

**Comment by jens-maus** [comment]
Du kannst gerne den cronBackup.sh Aufruf auf einen anderen Pfad lenken dann führt er die Backups eben auf ein NFS Laufwerk aus. Oder eben kein USB Stick verbinden. Momentan sehe ich hier aber ehrlich gesagt keinen großen Handlungsbedarf.

**Comment by libertyx82** [comment]
@MathiasJZ Ein Backup gehört immer auf einen externen Speicher, wenn der dann auch noch selbst gesichert wird, wäre das das Optimum.
Da der USB Stick an einem PI ein externer Speicher ist, ist es nicht generell so falsch, dass Backup hier abzulegen.

Allerdings fände ich es auch besser, wenn man den Pfad einfacher anpassen könnte. Die ReGa anzupassen wird wahrscheinlich schwierig, aber @jens-maus wie wäre es mit 2 SysVar´s,
Eine mit dem Pfad die andere mit der Anzahl der max Backups?
Dann braucht das Skript nur prüfen, ob die SysVar´s vorhanden sind, dann nutzt es diese und wenn nicht standard.

**Comment by jens-maus** [comment]
@libertyx82 Das automatische Backup hat mit der ReGa nichts zu tun. Das "einzige" was ich anbieten kann ist, das man unter /etc/config ggf. eine Datei anlegen kann wo der Pfad drinsteht auf das das `cronBackup.sh` dann versucht die Backups abzulegen.

**Comment by libertyx82** [comment]
Das es mit der ReGa nix zu tun hat ist mir klar. mit "anpassen der ReGa" meinte ich, dass du auf der WebUI in den Einstellungen, dann eine entsprechende Auswahl hast.

Aber das mit der der Datei unter /etc/config, finde ich dann sogar besser als 2 SysVar´s

**Comment by MathiasJZ** [comment]
Das wäre super.
Dann entferne ich die automatischen Backups der Raspberrymatic aus der 
Backmeup Instanz und ich kann weiter wie gewohnt auf der NAS ablegen.
Den USB-Stick brauche ich leider für die Diagramme und Highcharts.

Mit freundlichen Grüßen,
Mathias Zaspel
Max-Kolmsperger-Str. 19
81735 München
Tel:  +49-89-21545410
Fax: +49-89-420955813
mail: mathias@zaspel.org

Am 23. September 2018 11:45:31 schrieb Jens Maus <notifications@github.com>:

**Comment by jens-maus** [comment]
Der Teil zum abschalten des CronBackups wurde bereits dankenswerterweise von @jp112sdl für die nächste Version wie folgt implementiert: https://github.com/jens-maus/RaspberryMatic/commit/7cee2dc32cf154adee5079af24aa5ff6614d731e

**Comment by MathiasJZ** [comment]
Dankeschön!
Wie bereits geschrieben,  meine Backups landen auf der NAS
Gruß,
Mathias


Am 24. September 2018 11:52:52 schrieb Jens Maus <notifications@github.com>:

**Comment by libertyx82** [comment]
Bei mir auch, ich würde das Script daher schon gerne Nutzen, nur eben mit angepasstem Pfad.

**Comment by jens-maus** [comment]
Bitte schön, der letzte commit sollte beides nun umsetzen für die nächste RaspberryMatic Version. D.h. dort dann einfach eine Datei  `/etc/config/CronBackupPath` mit dem Backuppfad anlegen und eine Datei `/etc/config/CronBackupMaxBackups` mit der Anzahl maximaler Backups (`*.sbk` Dateien) die in dem Verzeichnis behalten werden sollen (0 entspricht unendlich).

**Comment by libertyx82** [comment]
@jens-maus 
für das Andere Thema mit dem TMP Dir bei createBackup.sh hab ich mal einen Pull Request erstellt. ;)
Ich hoffe richtig :)

**Comment by MathiasJZ** [comment]
Und wenn man gar kein Backup will?
Ich habe es wie bereits geschrieben mit der IObroker-Instanz Backmeup 
umgesetzt.
Sie macht die Backups sehr zuverlässig und ich würde auch gerne dabei 
bleiben.. Einige Tests haben auch ergeben, dass das Restore auch 
einwandfrei funktioniert.
Was ich natürlich ganz toll finde, ist, dass die Zwangsneustarts beim 
Installieren bzw Aktualisieren der Addons wegfällt. Nun werde ich rmupdate 
auch vom System entfernen.
Mit freuauchndlichen Grüßen,
Mathias Zaspel
Max-Kolmsperger-Str. 19
81735 München
Tel:  +49-89-21545410
Fax: +49-89-420955813
mail: mathias@zaspel.org

Am 24. September 2018 13:27:15 schrieb Dirk Schneider 
<notifications@github.com>:

**Comment by jens-maus** [comment]
Bitte beiträge komplett lesen: https://github.com/jens-maus/RaspberryMatic/issues/409#issuecomment-423924820

**Comment by Schmello** [comment]
Ich habe eine Datei angelegt /etc/config/CronBackupPath 
In die Datei habe ich meinen Pfad eingetragen den ich über Cuxd Mounte. Cuxd hat in dem Pfad auch schon Dateien abgelegt. 
/media/cuxd
Doch werden die Backups weiterhin auf den angeschlossenen USB Stick gemacht.. Was mache ich da falsch?
