### ISSUE TITLE
Virtuelle Heizungsgruppen Geräteliste

### ISSUE THREAD

**Issue by eli4711** [jens-maus/RaspberryMatic#410]
RaspberryMatic 3.37.8.20180922 

-> In der Geräteliste wird für die Virtuellen Heizungsgruppen "LOW BAT und UNREACH" angezeigt. 

![heizung](https://user-images.githubusercontent.com/40276118/45927798-0142db80-bf39-11e8-97a5-782486f760d0.JPG)

   Funktion der Gruppen ist aber Normal.

Grüße Thomas

**Comment by Fiiti** [comment]
+1

**Comment by mike-bee** [comment]
+1
Aber bislang nur 2 von 5 ...
![heizungsgruppen](https://user-images.githubusercontent.com/30027622/45928266-1de31180-bf41-11e8-94d9-6b223705f6df.png)

**Comment by jens-maus** [comment]
Das hatte ich auch schon bemerkt. Werde wohl die Statusanzeigen für Virtuelle Geräte kompletz abschalten weil Sie da eigentlich keinen Sinn machen.
