### ISSUE TITLE
Status immer UNREACH und LOWBAT

### ISSUE THREAD

**Issue by dehell** [jens-maus/RaspberryMatic#415]
![zwischenablage02](https://user-images.githubusercontent.com/26470288/45965278-5c9fc700-c028-11e8-8d51-cbc1aff4a5bc.jpg)

**Describe the bug**
In der Geräteansicht wird der Status einer 'Gruppe Heizungssteuerung' immer mit LOWBAT und UNREACH angezeigt. Kein Teilnehmer der Gruppe hat einen dieser Meldungen.

**To Reproduce**
Einstellungen / Geräte aufrufen.

**Expected behavior**
Die Gruppe sollte garkeine oder eine Sammelmeldung der Teilnehmer zeigen.

**Screenshots**

**System information (please complete the following information):**
 - Version RaspberryMatic 3.37.8.20180922]
 - Hardware RaspberryPi3
 - Patch für liststatus.tcl eingespielt.

**Comment by jens-maus** [comment]
Dies ist ein duplicate von #410 das auch bereits repariert wurde für die nächste Version.
