### ISSUE TITLE
Raspberrymatic on Tinkerboard. No backup restore possible

### ISSUE THREAD

**Issue by StefanGubler** [jens-maus/RaspberryMatic#425]
**Describe the bug**
1. Auf eine neue Samsung evo 32 GB SD Card 
RaspberryMatic-3.37.8.20180929-tinkerboard mit Etcher installiert

2. Browser Cache gelöscht (Chrome + IE11)

3. Tinkerboard S fährt hoch und stell HomeMatic Portal dar

4. Backup einspielen aber ohne Datei auszuwählen: Anzeige Fehlermeldung,
dass keine Backup Datei ausgewählt wurde. das ist i.o.

5. Backup Datei auswählen. Ausgewählte Datei wird angezeigt.

6. Backup einspielen. Keine Aktion ersichtlich. In der Konsole bzw. Netzwerk wird Fehler angezeigt
siehe Screenshot.

7. Die Funktion  Backup erstellen erzeugt auch Fehler.

8. Auf dem Homematic Portal werden rechts keine Daten angezeigt (Version, Uhrzeit etc.)

9. Die Farbgebung im RaspMatic Sicherhit ist ev. auch falsch. es ist alles grün hinterlegt.

Fehler ist reproduzierbar. Mehrere Male SD-Card geflasht. Mehrere Starts.
Rasperrymatic Versionen  für Tinkerboard:
RaspberryMatic-3.37.8.20180929-tinkerboard 
RaspberryMatic-2.35.16.20180922-tinkerboard
weisen denselben Defekt auf.

Version RaspberryMatic-2.35.16.20180826-tinkerboard hat diesen Bug nicht und funktioniert.

**System information (please complete the following information):**
 - RaspberryMatic-3.37.8.20180929-tinkerboard 
-  RaspberryMatic-2.35.16.20180922-tinkerboard
   flashed on new SD-.Cards

 - Hardware [e.g. RaspberryPi3, TinkerboardS, etc.]
   New   Tinkerboard-S

![raspberrrymatic-2 35 16 20180826 2018-09-30 12_32_02-tinkerboard-sicherheit-menu und farbe](https://user-images.githubusercontent.com/43369612/46257443-5d61ae80-c4a9-11e8-898c-22c0660e88f7.png)

![browser-netwrok-error-on-backup-einspielen](https://user-images.githubusercontent.com/43369612/46257445-68b4da00-c4a9-11e8-8185-378d7fd6e5a0.png)

![raspberrymatic-3 37 8 20180929-tinkerboard-create-backup-error](https://user-images.githubusercontent.com/43369612/46257447-70747e80-c4a9-11e8-810e-e8408fa7dfe4.png)

![raspberrymatic-3 37 8 20180929-tinkerboard-create-backup-error-2](https://user-images.githubusercontent.com/43369612/46257448-75d1c900-c4a9-11e8-9138-0b9f66dcdf89.png)

**Comment by jens-maus** [comment]
Bitte mal in `/usr/local/tmp` nach einer Datei die mit `cgimail` anfängt suchen wenn dieser "internal error" auftaucht. Und dann den Inhalt dieser Datei hier präsentieren.

**Comment by jens-maus** [comment]
P.S: Warum machst du eigentlich eine Installation auf eine SD Karte bei einem Tinkerboard S und nicht auf die eMMC?

**Comment by StefanGubler** [comment]
Unglaublich aber war.  RaspberryMatic-3.37.8.20180929-tinkerboard auf dasselbe Tinkerboard installiert, aber direkt auf die eMMC und siehe da. 
Es funktioniert !!!  Es sieht alles so auf wie auf einem Raspi 3B+, also kein Unterschied.

ich kann keine Fehler mehr erkennen.
Aber was macht nun den Unterschied ? Die SD-Card kann doch nicht falsch programmiert gewesen sein.
Theorie und Praxis sind hier 'mal wieder schön auseinander.
