### ISSUE TITLE
Umbennen von Standardsystemvariablen

### ISSUE THREAD

**Issue by atriebel** [jens-maus/RaspberryMatic#426]
Hallo,

ich glaube es besteht noch ein Minor Bug in der GUI. Ich würde gerne die Standardsystemvariablen "DutyCycle" und "Wired-Status" umbennen, damit sie besser in mein Namenskonzept/Struktur passen.

Wenn ich sie im Bereich "Einstellungen" umbenenne erscheint das zunächst als erfolgreich. Es wird jedoch im Hintergrund eine neue Systemvariable (mit den bestätigten Einstellungen) angelegt.

 - Version RaspberryMatic 3.37.8.20180929
 - Hardware RaspberryPi3

**Comment by jens-maus** [comment]
Tut mir leid, aber das ist kein Bug sondern die in RaspberryMatic implementierten Berechnungen des DutyCycle und des Wired-Status  unterstützen keine anderen Namen.

**Comment by atriebel** [comment]
Ok, dann ggf. Den Bearbeiten Button ausblenden/deaktivieren. Hat aber Prio 100.

Danke für die schnelle Antwort und die gute Arbeit an der Software!

André 
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 30.09.18, 20:11, Jens Maus <notifications@github.com> schrieb:
Tut mir leid, aber das ist kein Bug sondern die in RaspberryMatic implementierten Berechnungen des DutyCycle und des Wired-Status  unterstützen keine anderen Namen.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jens-maus/RaspberryMatic","title":"jens-maus/RaspberryMatic","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jens-maus/RaspberryMatic"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jens-maus in #426: Tut mir leid, aber das ist kein Bug sondern die in RaspberryMatic implementierten Berechnungen des DutyCycle und des Wired-Status  unterstützen keine anderen Namen."}],"action":{"name":"View Issue","url":"https://github.com/jens-maus/RaspberryMatic/issues/426#issuecomment-425739790"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jens-maus/RaspberryMatic/issues/426#issuecomment-425739790",
"url": "https://github.com/jens-maus/RaspberryMatic/issues/426#issuecomment-425739790",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [jens-maus/RaspberryMatic] Umbennen von Standardsystemvariablen (#426)",
"sections": [
{
"text": "",
"activityTitle": "**Jens Maus**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@jens-maus",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"jens-maus/RaspberryMatic\",\n\"issueId\": 426,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/jens-maus/RaspberryMatic/issues/426#issuecomment-425739790"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 386155656\n}"
}
],
"themeColor": "26292E"
}
]
