### ISSUE TITLE
symbolic link to /opt/jre instead in addition to /opt/java

### ISSUE THREAD

**Issue by wagner4u** [jens-maus/RaspberryMatic#427]
Hi,
habe neueste Raspberrymatic-Vesion installiert.
Bei Installation von hm2mqtt (unter Link von Raspberrymatic) startet der Prozess nicht, weil der Java-Pfad nicht (mehr ?) richtig gesetzt wird.
Habe das bei hm2mqtt bereits als issue gemeldet und man kann dies beheben.
Der bessere Weg ist vermutlich, dass unter
/opt ein zusätzlicher Link auf /opt/jre (genauso wie /opt/java) erzeugt wird, damit alte addons, etc.
noch den alten Pfad finden.
Bei hm2mqtt war das damit behoben, aber es sollte in der Distribution standardmäßig aufgenommen werden. Ggfs. gibt es noch andere addons, die sich auf den Pfad /opt/jre verlassen.

**Comment by jens-maus** [comment]
Tut mir leid, aber bei einer CCU2 existiert `/opt/jre` auch nicht und dessen JRE ist lediglich unter `/opt/jre-1.8.0_121-compact3` erreichbar. Der korrekte Pfad zur jeweils aktiven JRE ist `/opt/java` bei einer CCU3 und RaspberryMatic. Und Addons müssen das entsprechend unterstützten/berücksichtigen.
