### ISSUE TITLE
Geräte-Firmware - Übersicht Fehlen Fast alle Geräte

### ISSUE THREAD

**Issue by AndynordSee** [jens-maus/RaspberryMatic#428]
Startseite > Einstellungen > Geräte-Firmware - Übersicht
Fehlen fast alle Geräte

![startseite - einstellungen - gerate-firmware - ubersicht](https://user-images.githubusercontent.com/34406013/46299688-320eba80-c5a2-11e8-9144-e0ca62b683ab.png)

![startseite - einstellungen - gerate-firmware - ubersicht-2](https://user-images.githubusercontent.com/34406013/46299704-376c0500-c5a2-11e8-8480-fd297cbc6331.png)

System information
 - Version :  RaspberryMatic 3.37.8.20180929
 - Hardware : RaspberryPi3B + RPI-RF-MOD

**Comment by jens-maus** [comment]
Gibt es denn ein Gerät in der Geräteliste für das definitiv in der Firmware-Übersicht eine Geräte-Firmware angezeigt werden müsste? Bitte auch mal in `/usr/local/tmp` reinschauen ob da eine Datei `cgimail*` zu finden ist wenn die Geräte-Firmware-Liste nicht komplett ist.

**Comment by AndynordSee** [comment]
Schuldigung die später antwort: 
Ist mir nur auf gefallen weil ein update für ein HmIP-WTH-2 auf der Startseite 
angezeigt wurde.
unter "/usr/local/tmp" ist nur die "last_backup.sbk"
<img width="202" alt="428" src="https://user-images.githubusercontent.com/34406013/46404229-da3c9480-c704-11e8-9840-1dc75140dfa2.PNG">

**Comment by jens-maus** [comment]
Existiert das Problem noch mit der aktuellen RaspberryMatic Version?

**Comment by jsv2020** [comment]
Ja, bei mir besteht das Problem noch. Es fehlen einige Geräte die auf der Startseite als updatebar angezeigt werden.

**Comment by agger83** [comment]
Ich habe ein ähnliches Problem. In der Raumansicht fehlen meine Thermostate, obwohl sie zugeordnet sind.
Beispiel: Raum Bad enthält ein Thermostat und einen Fensterkontakt. In der Raumansicht wird nur der Fensterkontakt angezeigt.
Auf der Startseite habe ich eine Favoritenliste mit allen Thermostaten, hier wird das Thermostat aus dem Bad angezeigt.
Das Problem besteht nicht von Anfang an, es kam später ohne eine Fehlermeldung auf.
Im der Firmware Übersicht werden die Thermostate angezeigt.
Meine Version der Raspberrymatic ist die aktuelle 3.41.11.20181222. Aufgesetzt habe ich das System mit der Version davor, ist also noch relativ frisch.

**Comment by HMside** [comment]
Ist auch bei unter EQ3_SUPPORT-1655 bekannt. Problem ist auch in der CCU3 unter 3.41.11 noch bzw. wieder vorhanden und soll mit dem kommenden Update behoben sein.

**Comment by jens-maus** [comment]
Fixed with 3.45.x
