### ISSUE TITLE
Geräte fehlen und Backup einspielen schlägt fehl

### ISSUE THREAD

**Issue by RobiMo** [jens-maus/RaspberryMatic#429]
Nach dem Update auf Version 3.37.8.20180929 fehlen alle Geräte ausser von CUXD in dem Status und Bedienungsmenue. Das vor dem Update erstellte Backup kann nicht mehr eingespielt werden. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
 - Version [e.g. RaspberryMatic 3.37.8.20180922]
 - Hardware [e.g. RaspberryPi3, TinkerboardS, etc.]

**Additional context**

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!
