### ISSUE TITLE
WebUI: Keymatic-Status in Favoriten-Ansicht verdoppelt

### ISSUE THREAD

**Issue by 37wh5r** [jens-maus/RaspberryMatic#430]
Neueste RaspberryMatic Version (3.37.8.20180929)

Ich habe gerade per WebUI die Keymatic bedient (Tür verschlossen; Tür öffnen führt ebenfalls zum Fehler), und die Anzeige in der Favoriten-Ansicht war verdoppelt. Erst ein Neuladen der Seite führt wieder zu einer normalen Ansicht. Screenshot anbei.
![keymatic](https://user-images.githubusercontent.com/7123146/46362474-a3b53a00-c670-11e8-9f6b-f7d900a9d22d.jpg)

**Comment by 37wh5r** [comment]
Browser wo der Fehler auftritt: Chrome und Safari auf macOS.

**Comment by libertyx82** [comment]
Kann ich nicht bestätigen.  Hast du die RaspMatic mal neu gestartet?

![image](https://user-images.githubusercontent.com/22996350/46363325-f98ae180-c672-11e8-98f4-dc3f4d7b1c11.png)

**Comment by 37wh5r** [comment]
In der Tat, nach einem Neustart tritt das Phänomen nicht mehr auf.
