### ISSUE TITLE
Diagramm Durchschnittswerte nicht Plausibel 

### ISSUE THREAD

**Issue by AndynordSee** [jens-maus/RaspberryMatic#432]
Diagramm Durchschnittswerte nicht Plausibel 

CCU Firmware Version: 3.37.8.20180929
HmIP-STHO Firmware Version:1.0.6

1.	( Minimalwerte ) 03.10.18 22:00:00,,15.028
2.	( Maximalwerte ) 03.10.18 22:00:00,15.028,
3.	( Durchschnittswerte ) 03.10.18 22:00:00,,12.2

[Git-01-2.pdf](https://github.com/jens-maus/RaspberryMatic/files/2443937/Git-01-2.pdf)
[Git-02-2.pdf](https://github.com/jens-maus/RaspberryMatic/files/2443939/Git-02-2.pdf)
[Git-03-2.pdf](https://github.com/jens-maus/RaspberryMatic/files/2443940/Git-03-2.pdf)

**Comment by jens-maus** [comment]
Tschuldigung? Warum genau muss ich hier pdfs mit reinem Text runterladen und anschauen? Reiner text gehört nicht in pdf Dateien sondern in *.txt Dateien die jeder dann auch parsen und bandbreitschonend anschauen kann.

Abgesehen davon ist dies hier aber kein spezieller Bug in RaspberryMatic, wenn ich mich nicht irre. Sondern das wird auch auf einer reinen CCU2 sowie CCU3 genauso passieren/auftreten. Ergo ist das ein Upstream Bug der von eQ3 beseitigt gehört. Des Weiteren bitte solche Dinge erst im homematic-forum diskutieren und erst wenn klar ist das das ein definitiver bug in RaspberryMatic ist hier einen entsprechenden Bugreport aufmachen.

**Comment by AndynordSee** [comment]
Tschuldigung? Warum genau muss ich hier pdfs mit reinem Text runterladen und anschauen? Reiner text gehört nicht in pdf Dateien sondern in *.txt Dateien die jeder dann auch parsen und bandbreitschonend anschauen kann.

Sorry gemerkt für die Zukunft war keine Böse Absicht, nutze pdf für fast alles.

Abgesehen davon ist dies hier aber kein spezieller Bug in RaspberryMatic, wenn ich mich nicht irre. Sondern das wird auch auf einer reinen CCU2 sowie CCU3 genauso passieren/auftreten. Ergo ist das ein Upstream Bug der von eQ3 beseitigt gehört. 

Mail Ist schon an eQ-3 raus.
War mir bei der CCU3 noch nicht aufgefallen. 
Werde jetzt gleich einen HmIP-STHO an die CCU3 Packen und werte aufnehmen.

Des Weiteren bitte solche Dinge erst im homematic-forum diskutieren und erst wenn klar ist das das ein definitiver bug in RaspberryMatic ist hier einen entsprechenden Bugreport aufmachen.

Also erstmal alles in Forum.
