### ISSUE TITLE
Raspberrymatic does not boot without ETH ready / power down @ home

### ISSUE THREAD

**Issue by madjack84** [jens-maus/RaspberryMatic#433]
**Describe the bug**
When power of my home is interrupted and repaired (happened twice those days) both fritzbox and rpi do reboot the same time.
fritzbox is slower than rpi with matic. Therefore rpimatic does not find network on ETH and stops booting completely, even if fritzbox is up and running then. I always have to restart rpimatic again.
I use 2.29.23.20171118 (i know it is old... but is this fixed in newer versions?)

**To Reproduce**
1. start rpimatic without ETH connection
2. connect fritzbox to rpimatic
3. rpimatic does not boot further

**Expected behavior**
rpimatic should either:
1. boot and run all scripts on its own even without ETH/webconnection
2. continue booting when network is available

**Screenshots**
-

**System information (please complete the following information):**
 - Version [e.g. RaspberryMatic 2.29.23.20171118]
 - Hardware [e.g. RaspberryPi3, etc.]
- FRITZ!OS: 06.83

**Comment by jens-maus** [comment]
Sorry, but in the ticket template it was clearly written that tickets should only be openend on the two most recent versions! So please update and see if this issue still exists or I will close this ticket.

**Comment by madjack84** [comment]
Ok, sorry. Did not see that. I set up a Support request for updating this Version 2.29. Can you answer?
Did you try with newest Version? Otherwise I will integrate a Powerbank (Just read this) to prevent Power downs.

By the way: Jens, many Thanks for your Motivation on this! Great work!

**Comment by jens-maus** [comment]
@madjack84 It is your job to try this with the new version and then report back if the problem still exists with the latest 3.37.x version or not,

**Comment by madjack84** [comment]
updated and tested.

Version 3.37.8.20180929 does boot until it requires Ethernet and stops at that point!
Plugging in Ethernet with a router leads to continue the boot procedure.

>> Problem of power down solved with the current version.

BUT: Does it stop requiring ethernet or does the CCU anyhow work in the background (controlling and processing all scripts). Unfortunately I wasn't able to test that.
>> Target: CCU work should be done independant of network connection. 
@jens-maus : Do you have an answer on this?

in general 👍 good work :)
