### ISSUE TITLE
WebUI Update von 2.29.23.20171118

### ISSUE THREAD

**Issue by madjack84** [jens-maus/RaspberryMatic#434]
Hallo 

ich nutze die veraltete Version 2.29.23.20171118.
Auf der Seite https://homematic-forum.de/forum/viewtopic.php?t=26917 (siehe unten) steht, dass ab 2.31.25.20180428 der Updateprozess über die komfortabel WebUI stattfinden kann. Meine 2.29. bietet das in der WebUI auch an... aber verstehe ich das richtig, dass die Updatebarkeit auch in der 2.29. vorhanden ist oder ginge das Update aus der 2.29. heraus schief muss ich diese Version noch manuel flashen?

Anhang: 
Firmware Update / Upgrade:
Da an RaspberryMatic regelmäßig weiterentwickelt wird, wird man zwangsläufig irgendwann zu dem Punkt kommen das man seine RaspberryMatic Installation auf eine neuere Version updaten muss/sollte. Seit der Version 2.31.25.20180428 funktioniert ein Firmware-Update von RaspberryMatic genauso wie bei einer CCU2. D.h. man lädt wie bei einer CCU2 die Firmware-Update-Datei über die WebUI hoch und lässt dieses dann anwenden. Dieses (wenn auch einfache) Prozedere soll hier kurz Schritt-für-Schritt erklärt werden:

**Comment by jens-maus** [comment]
In der 2.29.23.20171118 sollte es definitiv keine Möglichkeit geben via WebUI ein Firmware Update dirchzuführen. Insofern wird es das nicht geben. D.h. Am besten gleich auf die 3.37.x manuell updaten.

Und übrigens gilt auch hier was im Ticket template stand: das ist hier kein Support Forum sondern ein Bugtracker in dem definitive Bugs+FeatureRequests gemeldet werden und keine Hilfe/Supportanfragen. Dafür bitte das homematic forum nutzen!
