### ISSUE TITLE
HomeMenuX does not work anymore with RaspiMatic 3.37.8.20180929

### ISSUE THREAD

**Issue by BerkTam** [jens-maus/RaspberryMatic#435]
Seit RaspiMatic Version 3.37.8.20180929

funktioniert mein HomeMenuX auf dem Mac nicht mehr. 
Genauer gesagt, es werden zwar Kanäle, Programme, Variable und Räume angezeigt, aber die 
gesamten Geräte tauchen nicht mehr. 
Ich habe das überwiegend dafür genutzt über den Mac die gesamten Servicemeldungen zu bestätigen, wenn welche anlagen. 
Woran kann das liegen bzw. wie kann Fehler behoben werden?
Bitte nicht gleich alles auf den Programmierer von HomeMenuX geben, denn man sollte hier 
gemeinsam daran arbeiten.

Ferner, gibt es denn keine Möglichkeit diese verdammten Service-Meldungen über einen 
zentralen Button bestätigen?  Diese Meldungen nerven ziemlich und ergeben meines Erachtens keinen Sinn, wenn man sie manuell nicht einfach bestätigen kann. 

HomeMenuX habe ich 
Danke im Voraus.

**Comment by jp112sdl** [comment]
Hallo!

> Ich habe das überwiegend dafür genutzt über den Mac die gesamten Servicemeldungen zu bestätigen, wenn welche anlagen.

> Ferner, gibt es denn keine Möglichkeit diese verdammten Service-Meldungen über einen
zentralen Button bestätigen? 

Um die Meldung "Kommunikation **war** gestört" automatisch zu quittieren, muss lediglich die Option "Automatische Bestätigung der Servicemeldung..." in der _verdammten_ Benutzerverwaltung aktiviert werden...
![ccu_ben](https://user-images.githubusercontent.com/18190139/46594146-71bd3100-cad1-11e8-874d-0d5d0d68e94c.PNG)

> Bitte nicht gleich alles auf den Programmierer von HomeMenuX geben, denn man sollte hier
gemeinsam daran arbeiten.

<hr>

HomeMenuX 1.2.14 ist aus 2014, die Beta 2.0.11 ist aus dem Jahre 2015.
Es sieht für mich nicht danach aus, dass da noch irgendwelche Aktivitäten in der Entwicklung existieren.

Ich habe die App (beide Versionen) mal kurz getestet.
Es erscheint beim "Einlesen der CCU" ein Skriptfehler auf Seiten der ReGa.
```
 ReGaHss: Error: IseESP::ExecAlarmDP: WARNING: incorrect use of Variable() (use AlType()): WriteLine('(rooms)');    var roomVar=dom.GetObject(ID_ROOMS);    string rid;string sChannelId;    foreach(rid, dom.GetObject(ID_ROOMS).EnumIDs()){    var roomObj = dom.GetObject(rid);Write(rid+'     '+roomObj.Name()+'      ');    WriteLine(roomObj.EnumUsedIDs());    }    WriteLine('(/rooms)');WriteLine('(subsections)');     string sid;     foreach(sid, dom.GetObject(ID_FUNCTIONS).EnumIDs()){     Write(sid+'   '+dom.GetObject(sid).Name()+' ');    WriteLine(dom.GetObject(sid).EnumUsedIDs()); }     WriteLine('(/subsections)');WriteLine('(Variables)');  string vid;foreach(vid, dom.GetObject(ID_SYSTEM_VARIABLES).EnumUsedIDs()){  var sysVar = dom.GetObject(vid);  var vch = dom.GetObject(sysVar.Channel());  Write(vid#'        '#sysVar.Name()#'       '#sysVar.DPInfo()#'     '#sysVar.Unerasable().ToString()#'    '#sysVar.State()#'      ');  Write(sysVar.ValueType().ToString()#'      '#sysVar.ValueSubType().ToString()#'    '#sysVar.Variable()#'   '#sysVa
Oct  8 08:23:29 hp-k8t9hj local0.err ReGaHss: Error: IseESP::ScriptRuntimeError: WriteLine('(rooms)');    var roomVar=dom.GetObject(ID_ROOMS);    string rid;string sChannelId;    foreach(rid, dom.GetObject(ID_ROOMS).EnumIDs()){    var roomObj = dom.GetObject(rid);Write(rid+'   '+roomObj.Name()+'      ');    WriteLine(roomObj.EnumUsedIDs());    }    WriteLine('(/rooms)');WriteLine('(subsections)');     string sid;     foreach(sid, dom.GetObject(ID_FUNCTIONS).EnumIDs()){     Write(sid+'   '+dom.GetObject(sid).Name()+'   ');    WriteLine(dom.GetObject(sid).EnumUsedIDs()); }     WriteLine('(/subsections)');WriteLine('(Variables)');  string vid;foreach(vid, dom.GetObject(ID_SYSTEM_VARIABLES).EnumUsedIDs()){  var sysVar = dom.GetObject(vid);  var vch = dom.GetObject(sysVar.Channel());  Write(vid#'      '#sysVar.Name()#'       '#sysVar.DPInfo()#'     '#sysVar.Unerasable().ToString()#'      '#sysVar.State()#'    ');  Write(sysVar.ValueType().ToString()#'      '#sysVar.ValueSubType().ToString()#'    '#sysVar.Variable()#'   '#sysVar.ValueUnit()#'  ');  if (sysVar.ValueType()==2
```

Die Anwendung wieder lauffähig zu machen liegt nun in der Tat beim Entwickler. 
Es gab in den letzten Jahren einige Änderungen an der ReGa.

**Comment by BerkTam** [comment]
Hallo Jens, 

besten Dank für Deine Antwort. 

Dass mit der „Automatischen Bestätigung der Servicemeldung“ in der „verdammten Benutzerverwaltung 
WEISS ICH SEHR WOHL UND HAB ICH AUCH!

HILFT ABER BEI MANCHEN GERÄTEN TROTZDEM NICHT. 
Es lassen sich nunmal nicht alle Geräte damit bestätigen und das kann ich mit über 180 Geräten völlig 
untermauern. 
Daher war auch meine Frage, ob man hier nicht noch ein Feature bzw. Button einbauen kann, der ganz 
rigoros sämtliche Meldungen bestätigt. 
Wenn das der Entwickler bei HomeMenuX hinbekommen hat, denn da geht das super gut, dann wird doch 
irgendwie die Möglichkeit bestehen, dieses in die Benutzeroberfläche einbauen zu können?

Vielen Dank für Deine Mühe. 

Gruss
Berkant

**Comment by jens-maus** [comment]
@BerkTam Das hat jetzt aber nix mehr mit dem eigentlichen Ticket hier zu tun. Und da @jp112sdl schon korrekt beantwortet hat das HomeMenuX einfach halt um längen zu alt ist und daher nicht mehr mit neueren CCU Firmwares funktioniert schliesse ich dieses Ticket hier als invalid.

**Comment by BerkTam** [comment]
Sorry, aber das ist weder sehr hilfreich noch eine höfliche Art!!!!!!!!!!!!!!

Ich kann nur sagen, dass der Progammierer von  HomeMenuX das hinbekommen hat, 
was bisher nicht in der CCU, RaspberryMatic usw. funktioniert hatte. 

Eure Arbeit in allen Ehren, aber dieser Umgang passt mir gar nicht. 

Danke!

**Comment by jens-maus** [comment]
Das mag vielleicht so sein das dir das nicht recht in den Kram passt, aber das hier (GitHub) ist kein Diskussionsforum sondern eine Entwicklungsplatform und du hast hier ein Ticket in einem Bugtracker eröffnet mit der Benennung eines Problems wo es keines gibt (ist ja ein Bug in HomeMenuX wie sich gezeigt hatte). D.h. den Bug den du benannt hast gibt es in RaspberryMatic nicht sondern gehört in HomeMenuX repariert. Also bleibt nichts anderes übrig als dieses Ticket wieder zu schliessen.

Und das du dann vom Thema abweichst und ein spez. feature von HomeMenuX gerne in RaspberryMatic sehen würdest ist zwar nett, gehört aber in ein Diskussionsforum wie das HomeMatic Forum.

Und bzgl. "unhöflich" sei nur mal erwähnt das du hier derjenige bist der mit sätzen voll Großbuchstaben und mit tonnenweise Aufrufezeichen andere anschreit.

**Comment by BerkTam** [comment]
Sorry, aber das sehe ich anders. 

1. die Grossbuchstaben stehen nicht für Anschreien.  
     Nach 20 Jahren Typografie unter renomierten Designer, verweise ich auf die deutsche Sprache, dass
    Grossbuchstaben nicht gleich Anschreien ist und ein Ausrufezeichen steht in der deutschen Sprache eigentlich nach einer 
    Aussage und nicht zwangsläufig auf einen Befehl verweist. Sie kann sogar hinter einer Frage stehen. Ich verweise hier gerne auch auf Wiki. 
    Mir ist aber wohl bekannt, dass in der IT-Welt gerne die Schrift so abartig genutzt und deformiert wird. 

   Ferner wollen wir doch die Kirche im Dorf lassen, es war gerade mal bei der letzten Email am Ende des ersten Satzes, in der ich 
    Ausrufezeichen angebracht hatte. Von „tonnenweise“ kann hier wohl nicht die Rede sein.

2. Die Grossbuchstaben habe ich genutzt, um die Aussage hervorzuheben und das ist sicherlich nicht böse gemeint. 
    Zudem war es explizit darauf bezogen, dass eine Antwort von Euch kam mit  „verdammte Benutzerverwaltung“  was schon sehr genervt klingt!
    Und, wie ich bereits mitgeteilt hatte, war diese bei mir ohnehin schon in der Benutzerverwaltung markiert. 

Wenn man mit dem Finger auf Jemanden zeigt, dann bitte vorher den Thread genau durchlesen und nicht gleich auf Angriff blasen. 


Mit dem Anbringen der Anregung ins Diskussionsforum stimme ich Dir zu, aber nicht über die Reaktion und die Art und Weise wie hier 
geantowortet wird. Ich glaube, dass man diese Sachen auch sachlich durchnehmen kann. 

Auch dass ein Update von HomeMenuX hier nicht am richtigen Platz ist kann ich ebenfalls verstehen. 
Aber ich stecke nunmal nicht so in der Entwicklung drin, wie ihr. Ferner lief HomeMenuX bis zum letzten Update von RaspiMatic 
einwandfrei. 
Da wird man wohl schon mal fragen können, woran das liegen könnte?
 

Danke

**Comment by Fiiti** [comment]
,@jens-maus: du hast meinen vollen Respekt das du bei solchen Gesellen noch höflich bleibst. Manche merken wohl nicht,  wenn sie provozieren und sich im Ton vergreifen.
