### ISSUE TITLE
Fehlende Hilfetexte

### ISSUE THREAD

**Issue by Crazor** [jens-maus/RaspberryMatic#436]
**Describe the bug**
Es fehlen einige Hilfetexte in den Dialogen, die durch die "?"-Symbole geöffnet werden.

**To Reproduce**
1. Gehe in die Einstellungen eines eTRV
2. Klicke bei Reset per Gerätetaste sperren auf "?"
3. Es öffnet sich ein Dialog mit "LOCAL_RESET_DISABLED"

**Expected behavior**
Es sollte der Hilfetext zu genannter Option angezeigt werden.

**System information (please complete the following information):**
 - Version: RaspberryMatic 3.37.8.20180929
 - Hardware: RaspberryPi3B

**Additional context**
Es fehlt auch der Hilfetext für "Routing aktiv" ("ENABLE_ROUTING")

**Comment by jens-maus** [comment]
Das hier Hilfetexte fehlen ist keine Besonderheit von RaspberryMatic, sondern diese fehlen auch in der CCU3 Firmware. Insofern erscheint mir das ein upstream bug bei eQ3 zu sein. Trotzdem werde ich dieses Bugentry offen halten. Ich bitte jedoch darum jedes einzelne Textfragment hier zu benennen für das Hilfetexte fehlt.

**Comment by jens-maus** [comment]
Bitte auch mal probieren den BrowserCache zu löschen und schauen ob dann das Problem vielleicht gelöst ist.

**Comment by jens-maus** [comment]
Dann bitte jeden Parameter einzeln beschreiben für den die Hilfetexte fehlen.

**Comment by Crazor** [comment]
Bisher sind mir nur LOCAL_RESET_DISABLED und ENABLE_ROUTING aufgefallen. Dies betrifft wohl neben dem eTRV auch andere HmIP Geräte, wie z.B. die SWDO.

**Comment by jens-maus** [comment]
Ist dieses Issue noch relevant / aktuell? AFAIK sollten diese dinge von eQ3 in bereits freigegebenen updates repariert worden sein...
