### ISSUE TITLE
Großes Bild vom HM-CC-RT-DN fehlt

### ISSUE THREAD

**Issue by Crazor** [jens-maus/RaspberryMatic#437]
**Describe the bug**
Das große bild für HM-CC-RT-DN fehlt. Das kleine Bild für die Übersichtstabellen funktioniert.

**To Reproduce**
1. Gehe auf die Geräteeinstellungen zu einem HM-CC-RT-DN
2. Das große Bild fehlt. Die URL des fehlenden Bildes lautet "config/img/devices/250/83_hm-cc-rt-dn.png"

**Expected behavior**
Es sollte die große Variante des Bildes angezeigt werden.

**System information (please complete the following information):**
 - Version: RaspberryMatic 3.37.8.20180929
 - Hardware: RaspberryPi3B

**Comment by jens-maus** [comment]
Das kann ich hier leider nicht reproduzieren. Daher bitte mal Browsercache löschen und erneut versuchen.

**Comment by Crazor** [comment]
Tatsächlich, ein Cache-Problem! Das Bild war bei mir an zwei Rechnern und schon seit ewigkeiten kaputt, und beide Geräte gehen nach dem Leeren des Caches wieder.
