### ISSUE TITLE
No data shown from HM-ES-TX-WM

### ISSUE THREAD

**Issue by friedpa** [jens-maus/RaspberryMatic#438]
**Describe the bug**
No data at "Energie Zähler RaspMatic" field since change from CCU2 to RaspberryMatic from HM-ES-TX-WM

**Expected behavior**
Counter 

**Screenshots**
![image](https://user-images.githubusercontent.com/42890695/46616354-a99c9680-cb1a-11e8-87ae-221984142f6f.png)

**System information:**
 - RaspberryMatic: 3.37.8.20180929
 - Hardware: RaspberryPi3

**Comment by jens-maus** [comment]
Der "Energie-Zähler RaspMatic" wird mittels eines versteckten "systeminternen" Programmes aktualisiert. Ich würde daher erst einmal dieses Programm überprüfen. D.h. unter "Programme & Zentralenverknüpfungen" die Option "systeminterne Programme einblenden" anschalten und dann das Programm finden das anhand der Seriennummer zum HM-ES-TX-WM passt und dann schauen was da ggf. faul ist. Ein komplettes Ablernen und anlernen des HM-ES-TX-WM ode einfach ein "drüberlernen" kann hier bereits die Lösung bringen. Und natürlich danach kontrollieren das nicht zwei identische interne Programme dann existieren.

**Comment by friedpa** [comment]
Hi Jens,

it seems that both suggested solutions are not working.

 

The script behind is, before and after, the same:

 

object chn = dom.GetObject('5636');

object oBoot = chn.DPByControl('POWERMETER_IGL.BOOT');

object oEnergyCounter = chn.DPByControl('POWERMETER_IGL.ENERGY_COUNTER');

object oSysVarEnergyCounter = dom.GetObject('svEnergyCounter_5636_NEQ0864211:1');

object oSysVarEnergyCounterOldVal = dom.GetObject('svEnergyCounterOldVal_5636');

object oSysVarEnergyCounterResetPressed = dom.GetObject('svEnergyCounter_5636_NEQ0864211:1_RESET');

object oSysVarEnergyCounterTmpOldVal = dom.GetObject('svEnergyCounter_5636_NEQ0864211:1_TMP_OLDVAL');

object oSysVarEnergyCounterDeviceReset = dom.GetObject('svEnergyCounter_5636_NEQ0864211:1_DEVICE_RESET');

boolean bootFlag = oBoot.Value();

real devVal = oEnergyCounter.Value();

real devValMax = oEnergyCounter.ValueMax();

real oldDevVal = oSysVarEnergyCounterOldVal.Value();

real tmpOldDevVal = oSysVarEnergyCounterTmpOldVal.Value();

integer ioldDevVal = (tmpOldDevVal.ToString().ToFloat() * 100000).ToInteger();

real diffVal = 0.0;

real sysVarVal = oSysVarEnergyCounter.Value();

integer tmp_devVal = (devVal.ToString().ToFloat() * 100000).ToInteger();

integer tmp_oldDevVal = (oldDevVal.ToString().ToFloat() * 100000).ToInteger();

if ( oBoot.Value() == true ) {

   oSysVarEnergyCounterDeviceReset.State(true);

   if (ioldDevVal <= 0) {

     oSysVarEnergyCounter.State(0);

   }

} else {

   boolean resetPressed = oSysVarEnergyCounterResetPressed.Value();

   ! boolean devReset = oSysVarEnergyCounterDeviceReset.Value();

   if ( (resetPressed == true) && (oSysVarEnergyCounterDeviceReset.Value() == true) ) {

       oSysVarEnergyCounterTmpOldVal.State(0);

       tmpOldDevVal = 0;

   }

  !Normales Hochzaehlen. Geraetwert > vorheriger Wert

  if ((tmp_devVal >= tmp_oldDevVal) && (oSysVarEnergyCounterDeviceReset.Value() == false)) {

   if (resetPressed == false) {

      diffVal = oEnergyCounter.Value() - oldDevVal;

    } else {

      !Reset pressed

      diffVal = oEnergyCounter.Value() - tmpOldDevVal;

      if ((diffVal.ToString().ToFloat() * 100000).ToInteger() < 0 ) {

                                   diffVal = oEnergyCounter.Value();

      }

      oSysVarEnergyCounterResetPressed.State(0);

    }

  } else {

    !Geraetewert ist kleiner vorheriger Wert

   !Entweder Ueberlauf, oder Batterietausch

    if (oSysVarEnergyCounterDeviceReset.Value() == false) {

      !Normaler Geraeteueberlauf

      if(tmp_devVal > 0) {

         diffVal = (oEnergyCounter.Value() + devValMax) - oldDevVal;

      }

    } else {

         !Zaehle Geraetewert zum CCU-Zaehler

          diffVal = oEnergyCounter.Value();

          if ((diffVal.ToString().ToFloat() * 100000).ToInteger() == 0) {

                           oSysVarEnergyCounterDeviceReset.State(true);

           } else {

            oSysVarEnergyCounterDeviceReset.State(false);

          }

    }

  }

  !Erhoehe den CCU-Zaehler

  oSysVarEnergyCounter.State(sysVarVal + diffVal);

  oSysVarEnergyCounterOldVal.State(oEnergyCounter.Value());

  oSysVarEnergyCounterTmpOldVal.State(oEnergyCounter.Value());

} 

 

Thanks and Kind Regards

Paul

 

Von: Jens Maus <notifications@github.com> 
Gesendet: Montag, 8. Oktober 2018 17:04
An: jens-maus/RaspberryMatic <RaspberryMatic@noreply.github.com>
Cc: friedpa <paul@fried.at>; Author <author@noreply.github.com>
Betreff: Re: [jens-maus/RaspberryMatic] No data shown from HM-ES-TX-WM (#438)

 

Der "Energie-Zähler RaspMatic" wird mittels eines versteckten "systeminternen" Programmes aktualisiert. Ich würde daher erst einmal dieses Programm überprüfen. D.h. unter "Programme & Zentralenverknüpfungen" die Option "systeminterne Programme einblenden" anschalten und dann das Programm finden das anhand der Seriennummer zum HM-ES-TX-WM passt und dann schauen was da ggf. faul ist. Ein komplettes Ablernen und anlernen des HM-ES-TX-WM ode einfach ein "drüberlernen" kann hier bereits die Lösung bringen. Und natürlich danach kontrollieren das nicht zwei identische interne Programme dann existieren.

**Comment by jens-maus** [comment]
Duplicate of #241
