### ISSUE TITLE
WebUI: Spaltenbreite optimieren

### ISSUE THREAD

**Issue by harvey637** [jens-maus/RaspberryMatic#439]
Hallo Jens-Maus,
raspberrymatic funktioniert bei mir sehr gut, allerdings sehe ich Verbesserungspotential
in der tabellarischen Darstellung z.B. der Programme:

Das ist mein Lieblingswunsch:
Die **1. Spalte** ist der "Programmname", wäre schön, wenn die zulässige Länge dargestellt werden könnte, ein Zeilenumbruch ist ärgerlich z.B bei cut_n_paste: Spaltenbreite bitte **breiter**

Die **2. Spalte** enthält den Kommentar, hier kann sinnvoller Text erfasst werden. Aus meiner persönlichen Sicht kann diese Spalte so **breit** wie die echte Textbreite sein.
Eigentlich fehlt es mir immer an Kommentarmöglichkeit, Feld ist doch recht kurz, Darstellung auch.

Die **3 Spalte** enthält den "Auslöser", ist aber bei mir meist sinnfrei, da z.B mehrere Bedingungen verknüpft werden oder das Zeitmodul aktiv ist: Diese Spalte kann deutlich **schmaler** werden,
Inhalt reduziert dargestellt werden. Ev nur sowas wie "drei Bedingungen" ???
Die **4. Spalte** enthält die "Aktion", auch hier nur bedingt taugliche Info, Spalte kann auch **schmale**r werden. Inhalt ebenfalls reduziert dargestellt werden. Ev. nur "drei Aktionen" ev. Zeilenanzahl/Anzahl der Aktionen???

In einen 1920x1080 Display können dann alle Programme/Geräte/... in einer Zeile stehen.

Weitere optische Wünsche (bereits angefragt) bei mir auch "Zurück" auf das letzt-selektierte Element
und Editieren von Variablen (Zahlen, Zeichenketten) im Webgui.

Vielen Dank!
Harveyx

**Comment by harvey637** [comment]
push push ...
Also die erste und zweite Spalte könnte wirklich etwas breiter sein, die dritte und vierte eher schmaler.
Vermutlich ist der Aufwand geringer als die Freude daran :-)

**Comment by jens-maus** [comment]
@harvey637 Na dann sag ich mal: "Los geht's". RaspberryMatic ist OpenSource und ich freue mich über jeden PullRequest... Ansonsten heisst es halt "abwarten und Tee trinken" ;-)

**Comment by jens-maus** [comment]
This issue has been marked obsolete because time has passed and the content/topic of the issue seem to be not relevant anymore or does not match the current state-of-affairs. Thus, the issue had been closed. If you feel it is still relevant, please update the ticket accordingly with newer information and explain why you feel it is still relevant and should still be taken care of.
