### ISSUE TITLE
Anzeigefehler bei HMIP BROLL bei 100 % Öffnung

### ISSUE THREAD

**Issue by Zippochonda** [jens-maus/RaspberryMatic#442]
**Describe the bug**
Anzeigefehler bei HMIP BROLL bei 100 % Öffnung

**To Reproduce**
1. Go to 'WEBUi'
2. Click on 'Räume oder Gewerke'
3. Scroll down to 'HMIP BROLL Aktor'

**Expected behavior**

**Screenshots**
![grafik](https://user-images.githubusercontent.com/16080775/46720105-da421480-cc6f-11e8-894b-3b4139c9c0f8.png)
![grafik](https://user-images.githubusercontent.com/16080775/46720150-ff368780-cc6f-11e8-8bab-9f75c7e43ac7.png)

**System information (please complete the following information):**
3.37.8.20180929
 RaspberryPi3]

**Additional context**

**Comment by jens-maus** [comment]
Bitte mal probieren den Browsercache zu löschen, dann sollte es wieder gehen. Leider scheint das ein teilweise bekanntes Problem zu sein das von eQ3 repariert werden müsste.

**Comment by PinkiePieStyle** [comment]
![broll](https://user-images.githubusercontent.com/7350146/67943249-e9c53000-fbd9-11e9-9cf2-f0feee7e82dc.PNG)

Ja, habe hier selbes Problem.
Alle Versionen auf neustem Stand.

```
BROLL Firmware 1.6.2
RaspMatic 3.47.22.20191026
```

Mal zeigt es ?? oder -100%
In gängigen Foren liest man, dass der reale Status in Kanal 3 zu finden ist und von dort ausgelesen werden muss. Daher müsste das webui irgendwie von 3 in 4 schreiben
