### ISSUE TITLE
Anzeige im WEBUI für Thermostat HM-CC-RT-DN erweitern

### ISSUE THREAD

**Issue by Bratmaxe1981** [jens-maus/RaspberryMatic#444]
Der User jp112sdl hat einen kleinen Patch für die Anzeige von Batteriezustand und Ventilposition des Heizkörperthermostat HM-CC-RT-DN veröffentlicht.

Es wäre schön, wenn dieser Patch Standard in Raspberrymatic werden könnte.
Hier der Link zu dem GitHub-Projekt: https://github.com/jp112sdl/HM-WebUI-CC-Mod

Es scheint nur eine kleine Anpassung in einer Datei notwendig zu sein.

**Comment by jens-maus** [comment]
Tut mir leid, aber wenn ich diesen Patch 1:1 übernehmen können sollte muss der Autor einer Veröffentlichung unter der Apache 2.0 Lizenz zustimmen da er momentan unter der GPL 3.0 Lizenz veröffentlich ist und diese beist sich mit Apache 2.0. Ansonsten müsste ich diesen komplett selbst neu entwickeln müssen und das kann dauern ;)

@jp112sdl Stimmst du einer Integration dieser Anpassung unter der Apache 2.0 Lizenz zu?

**Comment by jp112sdl** [comment]
Hi zusammen!

Ja, das ist kein Problem. 
Die Modifikation kann gern übernommen werden.

_Ich hatte bei der Wahl der GPL Lizenz den Schwerpunkt auf den Passus "Disclose source" gelegt.
Aber das ist ja hier gewahrt. Und letztlich bei der kleinen Modifikation auch nicht so wild._

Also 🔥 frei.

**Comment by jens-maus** [comment]
Alles klar, dann wird das für die nächste RaspberryMatic übernommen werden. Und in Zukunft bitte gleich ein PullRequest mit solchen WebUI Anpassungen stellen :) Daran bin ich immer interessiert...

**Comment by Bratmaxe1981** [comment]
Da bedanke ich mich schon mal bei euch beiden.

**Comment by jens-maus** [comment]
Voila, integriert!

**Comment by Bratmaxe1981** [comment]
Perfekt danke, das nenne ich mal ne schnelle Anpassung!

**Comment by jp112sdl** [comment]
Top 👍

**Comment by MathiasJZ** [comment]
Cool! Ich freue mch schon drauf! 👍
