### ISSUE TITLE
Raspberrymatic Dienste per PRTG prüfen

### ISSUE THREAD

**Issue by darkbrain85** [jens-maus/RaspberryMatic#445]
Hi!

Ich nutze zur Überwachung meines Netzwerks die Softwarelösung PRTG. 
Ich würde damit gerne prüfen, ob wichtige Dienste wie ReGaHss laufen oder nicht. 

Um das ganze mit dem SSH Sensor prüfen zu können, wäre ein Skript in /var/prtg/scripts nötig. 
Wäre es möglich dieses zu integrieren damit es bei updates überlebt?

Die ausführbare Datei prozess_prüfen.sh (Name beliebig) mit folgendem Inhalt ist in diesem Ordner nötig:

```
#!/bin/sh

pgrep $1  2>&1 1>/dev/null

if [ $? -ne 0 ]; then \rn 
  echo "1:$?:$1 Down"
else
  echo "0:$?:OK"
fi
```

In PRTG kann nun ein SSH Skript Sensor erstellt werden. Das Skript sollte bei korrekten SSH Zugangsdaten automatisch erkannt werden. Als parameter muss in dem Sensor dann noch der Prozessname z.B. ReGaHss definiert werden. Auf diese Weise lassen sich beliebige Prozesse mit einem einizgen Skript abgfragen. 

Das ganze wurde von mir getestet und funktioniert absolut schmerzfrei. Das kleine Skript sollte auf Raspberrymatic nicht weiter dramatisch sein.

Wäre eine Integration denkbar?

**Comment by jp112sdl** [comment]
Hi!

> Um das ganze mit dem SSH Sensor prüfen zu können, wäre ein Script in /var/prtg/scripts nötig.

An welcher Stelle ist der Pfad `/var/prtg/scripts` denn hart codiert?

Sofern sich dieser Pfad anpassen ließe, wäre es sinnvoll, die prtg-scripts unter `/usr/local/...` abzulegen. 
Der Pfad wird im Backup mit gesichert und ist auch nach einem Backup-Restore (und auch RaspberryMatic-Update) weiterhin verfügbar.

**Comment by darkbrain85** [comment]
Hi!

> An welcher Stelle ist der Pfad `/var/prtg/scripts` denn hart codiert?

Leider ist das in PRTG hart codiert. Das begleitet mich schon seit Jahren auf verschiedenen Linux büchsen..

**Comment by jens-maus** [comment]
@darkbrain85 Das ist leider eine sehr speziell auf PRTG zugeschnittene Sache und ich kann nicht erkennen warum man für eine Person aus Zehntausenden das fest in jede RaspberryMatic Version mit aufnehmen sollte.

Da das `/var` Verzeichnis unter RaspberryMatic jedoch in einem tmpfs liegt und somit folglich im RAM und eben auch beschreibbar ist, sollte es ein leichtes sein ein dediziertes CCU-PRTG-Client-Addon zu schreiben das beim hochfahren dann dieses Verzeichnis anlegt wenn es denn hart `/var/prtg/scripts` sein muss und das passende Skript dann da auch ablegt sodass PRTG via remote-SSH Zugang den Status entsprechend abfragen kann.

Eine feste aufnahme solcher Spezialitäten für jedermann wäre aber IMHO keine gute Idee. Genau dafür gibt es ja die Möglichkeit CCU-Addons zu schreiben.

**Comment by jp112sdl** [comment]
Okay, hab gerade einen [KB-Artikel](https://kb.paessler.com/en/topic/56503-ssh-sensor-folder) gefunden, in dem genau dieses unschöne Verhalten diskutiert wurde.
In dem Artikel wird ein anderer [Beitrag verlinkt](https://kb.paessler.com/en/topic/27553-is-there-a-way-to-write-custom-ssh-sensors) mit einer Art "Workaround"...
Vielleicht wäre das ja eine Lösung...

**Comment by jens-maus** [comment]
@jp112sdl Wie schon gesagt. Ich sehe hier eher den Weg eines dedizierten CCU-Addons für PRTG genau so wie es ein Check_MK CCU-Addon gibt. Jeder der dann PRTG nutzt kann dieses ja dann gerne installieren und wenn dann dort eine Verzeichnisstruktur unter /var gemacht wird (welches das Addon beim starten dann entsprechend anlegt) sollte das auch kein Problem sein.

**Comment by darkbrain85** [comment]
Die Einwände verstehe ich. Allerdings ist ein Addon für das einfache erstellen einer 1 KB Datei in einem Ordner etwas übertrieben. Oder nicht?

Wäre ein Symlink eventuell eine Alternative um den Ordner /var/prtg/scripts auf irgendwas innerhalb des /usr/local Verzeichnisses umzubiegen?

**Comment by jens-maus** [comment]
Nein, sowas ist nicht übertrieben. Damit gebe ich die Zuständigkeit+Kontrolle darüber ab an den Addon-Entwickler. Und es ist nur legitim zu sagen, für solch spezielle Funktionalität das <1% der RaspberryMatic Nutzer brauchen sollten sich die zusammenfinden die sowas brauchen und ein Addon schreiben oder eine Anleitung wie man das umsetzen kann was man möchte. Also sorry, sowas werde ich definitiv nicht als integralen Bestandteil von RaspberryMatic aufnehmen. Denn ansonsten haben wir hier bald eine Eierlegende Wollmilchsau die nicht mehr gewartet werden kann.

**Comment by jens-maus** [comment]
.. und bitte weitere Diskussionen zu dem Thema ins Homematic-Forum auslagern.

**Comment by darkbrain85** [comment]
Auch eine Art die Diskussion zu beenden!
Ich werde dich hier nicht weiter belästigen...

**Comment by jens-maus** [comment]
@darkbrain85 Sorry, das hat nichts damit zu tun das ich eine Diskussion beenden möchte. Sondern es hat damit zu tun das GitHub kein Diskussionsforum ist. Wenn du Ideen/Bugs hast dann bringe die zuerst ins HomeMatic Forum, diskutiere das dort durch und wenn es dann zu einem Konsens kommt kann man hier einen entsprechenden Feature Request aufmachen. Das hat einfach was damit zu tun das die wenigstens im GitHub hier unterwegs sind sondern auf das HomeMatic Forum zählen und daher gehört sowas IMHO weiter diskutiert.
