### ISSUE TITLE
Nach Update "microSD-Karte" weg

### ISSUE THREAD

**Issue by dg1kwa** [jens-maus/RaspberryMatic#446]
Hallo,
ich habe gestern auf die aktuelle Version geupdatet. Heute fällt mir auf das die Diagramme nicht laufen, stattdessen bekomme ich folgende Fehlermeldung:
"Es ist keine microSD-Karte für die Speicherung der Diagrammdaten eingelegt oder auf diese konnte nicht zugegriffen werden. Um die Diagrammdaten zu speichern, ist eine microSD-Karte erforderlich."

Unter Systemsteuerung und allgemeine Einstellungen steht:
"microSD Karte vorhanden, aber nicht initialisiert"

Wie bekomme ich das gefixt?

MfG
 Andreas

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!

**Comment by dg1kwa** [comment]
Wieso das? Der Fehler tritt doch nur bei RaspberryMatic auf und nicht auf der CCU2.

Also kann es nur ein Fehler bei RaspberryMatic sein!
