### ISSUE TITLE
user.err kernel: eth0: hw csum failure

### ISSUE THREAD

**Issue by hoedlmoser** [jens-maus/RaspberryMatic#449]
**Describe the bug**
some users are facing error in syslog
`eth0: hw csum failure`
since upgrade to RM 3.37.8.20181026 with RaspberryPi Linux kernel 4.14.71 (raspberrypi-kernel_1.20180924-1)

**Expected behavior**
no checksum errors on ethernet interfaces.

**System information**
 - Version 3.37.8.20181026
 - Hardware RaspberryPi3

**Additional context**
first report by LibertyX https://homematic-forum.de/forum/viewtopic.php?f=65&t=46300&start=30#p463520
maybe as a workaround you could execute
`ethtool -K eth0 rx off`
anyhow, looks like a bug in kernel 4.14.71 according https://github.com/raspberrypi/linux/pull/2717 and should be solved in 4.14.77 which is not yet released.

**Comment by stan23** [comment]
Ich habe die gleiche Meldung auf eine Raspberry Pi 3, allerdings bisher erst 3 Mal, und die letzte ist 24 Stunden her.
Beeinträchtigungen habe ich nicht bemerkt.

**Comment by libertyx82** [comment]
Das deaktivieren der RX CSUM (ethtool -K eth0 rx off) hält aber nur bis zu einem Reboot des PI danach tritt die Meldung wieder auf und man muss den RX CSUM wieder deaktivieren.

**Comment by jens-maus** [comment]
Problem sollte mit der nächsten RaspberryMatic beseitigt sein, denn dann nutzt diese den RaspberryPi kernel der auf 4.14.80 basiert.
