### ISSUE TITLE
WebUI: battery/valve state for heating control device not shown when added as a favourite.

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#452]
**Describe the bug**
The new battery/vale display (new WebUI patch) in heating control devices doesn't seem to work in a favorite display. However, the current "temperature" display is also not shown perhaps on purpose because it seems not to be possible to show the temperature in the favourite display?

**To Reproduce**
see https://homematic-forum.de/forum/viewtopic.php?f=65&t=46300&start=90#p463898

**Expected behavior**
When adding a heating device to a favourite either the battery/valve state should be either displayed or the display completely hided if not possible at all.

**Screenshots**
see https://homematic-forum.de/forum/viewtopic.php?f=65&t=46300&start=90#p463903

**System information (please complete the following information):**
 - RaspberryMatic 3.37.8.20181026

**Comment by jens-maus** [comment]
@jp112sdl Can you please investigate this issue and adapt your patch accordingly?

**Comment by jp112sdl** [comment]
Yes, I will check this within the next days.

**Comment by jp112sdl** [comment]
I took a look at my system and I cannot reproduce it.
Neither in "Status und Bedienung" -> "Favoriten" nor in the favorite list shown at the start page.
All values are printed correctly.

<img width="520" alt="bildschirmfoto 2018-10-28 um 11 14 29" src="https://user-images.githubusercontent.com/18190139/47614602-b91c5900-daa2-11e8-953d-2881fab2dfbd.png">

**Comment by jp112sdl** [comment]
Ah, thanks. Now I can see the behaviour.

Btw: The actual temperature has never been visible on that page?
