### ISSUE TITLE
RaspberryMatic install script

### ISSUE THREAD

**Issue by juehv** [jens-maus/RaspberryMatic#453]
I would prefer installing RaspberryMatic on a already running Linux system, to use other smart home software on the same hardware (such as OpenHab and ioBroker). Since there is no documentation how RaspberryMatic is designed to work, I don't think it's possible for me to extract the needed components by myself (without a painful code reading and understanding phase). However I guess it's not that much work since I would just need a script installing everything in place as it is done with the current install script, just without adding Linux parts.

If there is already a way to achieve my desired goal, I'd appreciate every hint to build my own script :)

**Comment by jens-maus** [comment]
What you are searching for is piVCCU (https://github.com/alexreinert/piVCCU). This is the currently only solution to run the CCU firmware within a, e.g. raspbian operating system within a LXC Container. While RaspberryMatic could in principle be modified to also be installable within a LXC Container, nobody has modified it accordingly yet. 

So if you really want to run run other third party software in parallel to the CCU/WebUI software either develop own CCU Addon packages to actually allow to install OpenHAB/ioBroker within RaspberryMatic. Or simply use piVCCU. Both ways, kerp in mind there are always oros and cons in putting more and more functionality on one single hardware device.

And of course, if you want to create an LXC Container version of RaspberryMatic, feel free to do so and submit it as a PullRequest.
