### ISSUE TITLE
Anlernen von IP Komponenten (fast) nicht möglich

### ISSUE THREAD

**Issue by younggun79** [jens-maus/RaspberryMatic#454]
Hallo Jens, Ich bin fast am Verzweifeln. Mir gelingt es leider fast nicht, IP Komponenten (Raspberrymatic 3b+ ) anzulernen. Beider Varianten, mit und ohne Internet, funktionieren nicht. 
Nach stundenlangen versuchen habe ich nun 2 (von 6) Rauchmelder anlernen können.
Funkwandthermostat auch nicht möglich.

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!

**Comment by younggun79** [comment]
Hallo Jens,

sry, hab das in meiner Verzweiflung übersehen.

 

Hast vielleicht trotzdem einen Tipp was ich eventuell falsch mache?!

 

Danke 
LG

 

Von: Jens Maus [mailto:notifications@github.com] 
Gesendet: Sonntag, 28. Oktober 2018 14:32
An: jens-maus/RaspberryMatic
Cc: younggun79; Author
Betreff: Re: [jens-maus/RaspberryMatic] Anlernen von IP Komponenten (fast) nicht möglich (#454)

 

Closed #454 <https://github.com/jens-maus/RaspberryMatic/issues/454> .
