### ISSUE TITLE
WebUI: battery/valve state for heating control device wrong on HmIP-BWTH.

### ISSUE THREAD

**Issue by Hypnos3** [jens-maus/RaspberryMatic#456]
**Describe the bug**
The new battery/valve display (new WebUI patch) in heating control devices is wrong for HmIP-BWTH. It shows a valve position, where HmIP-BWTH does not have a valve.

**To Reproduce**
1. Go to 'Status und Bedienung'
2. Open a room with a HmIP-BWTH assigned to.
3. you will see a "Ventilstatus unbekannt".

**Expected behavior**
Do not display any valve state for HmIP-BWTH. As it was with RaspberryMatic 3.37.8.20180929.

**Screenshots**
![image](https://user-images.githubusercontent.com/12692680/47637826-2db3ce00-db5d-11e8-8240-58fb3a0943f8.png)

**System information (please complete the following information):**
 - RaspberryMatic 3.37.8.20181026
 - Hardware RaspberryPi 2b

**Comment by jp112sdl** [comment]
Is it possible that this comes from `CreateBWTHSwitchState`?
There is a typo in the actual version delivered by eq3...
_/www/rega/esp/controls/heating_control.fn:_
 object oValveState = cObj.DPByControl("**SWTICH**.STATE"); 

It is fixed in https://github.com/eq-3/occu/commit/f1a713609068d7b819d55bfefbef0c9ce7781b25

**Comment by jens-maus** [comment]
@jp112sdl This could of course be the case ;) Great that you are watching the changes in eq3/occu so closely. In fact, this is one of the fixes eq3 pulled from the RaspberryMatic repository recently after I have notified them about this minor typo and fixed mysql (see https://github.com/jens-maus/RaspberryMatic/commit/ca62df42af6e5d0c3d86d303c27d321963fd3481#diff-a72cf41b0f01f97d6fe5de8966a66a45R184) :)

**Comment by jp112sdl** [comment]
@jens-maus Ok, now it's clear :) 
I was really confused because this issue occured at the same time with the newly displayed values for the classic HM RF thermal controls. ;)

**Comment by jens-maus** [comment]
This issue should be fixed with the next release due to the SWITCH.STATE fix.
