### ISSUE TITLE
HMIP-eTRV battery/valve status not displayed 

### ISSUE THREAD

**Issue by ThomasLoeffel** [jens-maus/RaspberryMatic#457]
### Describe the bug
The new battery/valve display (new WebUI patch) in heating control devices is not visible for HmIP-eTRV. 

### To Reproduce
    Go to 'Status und Bedienung'
    Open a room with a HmIP-eTRV assigned to.
    you will see no "Ventilstatus or Battery".

### Expected behavior
Display valve state and battery status for HmIP-eTRV in 'Status und Bedienung'.

### Screenshots
![20181030 hmip-etrv](https://user-images.githubusercontent.com/44590735/47685805-44e3d180-dbd8-11e8-9774-b2397ff513fd.JPG)

### System information (please complete the following information):
    RaspberryMatic 3.37.8.20181026
    Hardware Asus-Tinker+

**Comment by jens-maus** [comment]
After some investigation I found that at least the HmIP-eTRV does not allow to query the battery status and return it in volts. It only has a LOWBAT warning as it seems. However, I don't know for the eTRV2. So can you please use devconfig and try to display the Channel values for Channel :1  for the eTRV2 and list them here. Thanks.

**Comment by ThomasLoeffel** [comment]
Hallo Jens,

ich habe die gewünschten Daten. Ich habe die Kanalliste mit einem Skript ausgelesen (ohne Werte) und dann mit ioBroker (mit Werten). Meiner bescheidenen Meinung nach kann man die Arbeitsspannung auslesen. Ich habe die beiden Positionen "gelb" markiert. Nach Batterie Wechsel ging die ausgelesene Spannung auf 3.0 (vorher 2,6V siehe Bild ioBroker) also 2*1,5V Mignon.

Skript: Wert eines HMIP-eTRV2 auslesen, hier Arbeitsspannung:
..............................................................
var ipserial = (datapoints.Get("HmIP-RF.Sernummer:0.OPERATING_VOLTAGE")).Value();
..............................................................

Danke Gruß Thomas 

### Anhang:

![20181030 hmip-etrv2 skriptauswertung](https://user-images.githubusercontent.com/44590735/47740914-4a452880-dc79-11e8-94f6-7d35d7506703.JPG)


### Hier ein Auszug aus ioBroker mit Werten:
![20181030 hmip-etrv2 iobroker](https://user-images.githubusercontent.com/44590735/47740924-4fa27300-dc79-11e8-8274-7ac2f7794eb3.JPG)

**Comment by jens-maus** [comment]
@ThomasLoeffel Danke für die Auflistung. Allerdings liegt der `OPERATING_VOLTAGE` Datenpunkt in einem anderen Kanal `:0` als bei den BidCos-RF Geräten und daher muss ich schauen inwieweit ich diesen Abgreifen kann da die Darstellung in der Geräteliste ja Kanalbasiert ist und der `:1` Kanal der ja dargestellt wird diesen Datenpunkt faktisch nicht beinhaltet.

**Comment by jens-maus** [comment]
Also den Status des Ventils konnte ich nun für die nächste version implementieren. Da der Wert der battery allerdings in Kanal :0 steckt habe ich mich dagegen entschieden nun etwas zu implementieren das in der Statusanzeige des Kanal :1 trotzdem die Batterieanzeige umsetzt. Ggf. sollte man solche Dinge besser in der Statusspalte unter Einstellunge->Geräte verankern oder in der Liste der Geräte direkt anzeigen. Definitiv aber nicht in Kanal :1
