### ISSUE TITLE
Internen Fehler abfangen bei Systemvariable Info

### ISSUE THREAD

**Issue by Bratmaxe1981** [jens-maus/RaspberryMatic#458]
Hallo,

Ich weiß nicht, ob das als Bug, oder als Feature Request besser eingeordnet ist, mich habe mich nun hierfür entschieden.

Wenn ich mit einem Skript eine Systemvariable anlege, und dort unter ValueUnit einen Wert mit einem Leerzeichen am Ende eintrage (z.B. "°C "), dann wird die Variable erstellt, aber die Anzeige in der WEBUI Einstellungen-->Systemvariable bleibt dann leer. Hier scheint intern ein Fehler aufzutreten.
Dies betrifft nur die Anzeige unter: Einstellungen--> Systemvariable! 
Ich kann also sobald das passiert keine Variable mehr bearbeiten/löschen.

Unter der WebUI wird hier anscheinend automatisch das Leerzeichen am Ende entfernt wenn ich die Variable hier manuell anlege. 

Es wäre schön, wenn hier der Anzeigefehler behoben werden könnte. Denn mit einem fehlerhaften Skript oder gewollter Manipulation, kann ich hiermit den direkten Zugriff auf alle Systemvariabeln verhindern!

Anbei noch ein Skript zum testen:
Skript 1: Legt eine Systemvariable an mit dem Namen "TestVariable" und setzt die Einheit auf "°C ".

```
object svObject = dom.GetObject("TestVariable");
object svObjectlist = dom.GetObject(ID_SYSTEM_VARIABLES);
if (!svObject)
{
    svObjectlist = dom.GetObject(ID_SYSTEM_VARIABLES);
    svObject = dom.CreateObject(OT_VARDP);
    svObjectlist.Add(svObject.ID());
    svObject.Name("TestVariable");
    svObject.ValueType(ivtString);
    svObject.ValueSubType(istChar8859);
    svObject.DPInfo("IrgendeinText");
    svObject.ValueUnit("°C ");!!Hier das Leerzeichen hinter dem C macht die Probleme!!!
    svObject.Internal(false);
    svObject.Visible(true);
    dom.RTUpdate(0);
}
```

Nun erhält man unter Einstellungen->Systemvariablen keine Ausgabe mehr!
Mit diesem Skript kann man die Variable wieder löschen:

```
string  svName = "TestVariable";
object  svObj  = dom.GetObject(svName); 
dom.DeleteObject(svObj.ID());
```

**Comment by jens-maus** [comment]
Tut mir leid, aber ich bekomme das Problem hier nicht reproduziert. Die Systemvariable (auch wenn ein Leerzeichen hinter dem Unit ist) wird problemlos unter Einstellungen->Systemvariable dargestellt und angezeigt.

Welche RaspberryMatic Version wird eingesetzt? Ist das auch dann von dir reproduzierbar wenn du nicht als Unit Grad Celsius nimmst sondern ein unit ohne das Gradzeichen?

**Comment by Bratmaxe1981** [comment]
Hallo der Fehler ist bei mir mit der Version "RaspberryMatic 3.37.8.20180929" aufgetreten.
Ich habe vor 14 Tagen auf die Version "RaspberryMatic 3.37.8.20181026" aktualisiert, und dort ist es auch bei mir nicht reproduzierbar. 
Kann es sein, das der Fehler "zufällig" behoben wurde? Ich hatte es bestimmt 10x mit verschiedenen Variabeln getestet bevor ich es hier gepostet hatte.

Danke dir, das du es dir angeschaut hast!

**Comment by jens-maus** [comment]
Ich denke nicht. Aber gut das du es auch nicht reproduziert bekommst. Einfach das Ticket wieder aufmachen wenn das Problem wieder auftritt und dann etwas genauer hinschauen.
