### ISSUE TITLE
Update does not work via standard procedure

### ISSUE THREAD

**Issue by omo2002** [jens-maus/RaspberryMatic#460]
When I click Einstellungen->Systemsteuerung->Zentralen Wartung and use the RaspiMatic Software Update function nothing happens. 

I use:
cat /proc/device-tree/model
Raspberry Pi 3 Model B Rev 1.2#

cat VERSION
VERSION=3.37.8.20180922
PRODUCT=raspmatic_rpi3
PLATFORM=rpi3

1. I download the new software release eg. "RaspberryMatic-3.37.8.20181026-rpi3.zip"
2. I select the downloaded file for upload and press "Hochladen"
3. I see the file being uploaded via the progress counter in the browser footer. 
    A window appears "Das Firmware Update wird auf die RaspiMatic übertragen. Bitte haben Sie einen Augenblick Geduld.
4. After 10 minutes my patience is over. I reload the page, but the firmware is not updated.
 
What's wrong with my Raspi_Matic ?
Thanks for your support.

**Comment by jens-maus** [comment]
Nothing is wrong. Keep going! Depending on your Pi model and SD card speed it can take up to 30/45minutes. So simply wait and please contact the homematic forum in future with support requests! This is a bug and enhancement tracker no support fora.
