### ISSUE TITLE
Proxy-Einstellungen hinzufügen

### ISSUE THREAD

**Issue by Wanderer2129** [jens-maus/RaspberryMatic#461]
Bei der Installation und späteren Nutzung der Raspberrymatic (auf Tinkerboard) wurde einigemale eine Internetverbindung vorausgesetzt (Einspielen des Backups, Anlernen HmIP-Geräte).
Das hat zunaächst nicht funktioniert, weil ich Forwarding in der Firewall gesperrt habe. Alles, was ins Internet muss, läuft also über einen Proxyserver.
Ist es möglich,  z.B. unter "Einstellungen/Systemsteuerung/Netzwerkeinstellungen/" eine Konfigurationsmöglichkeit für "Proxy" hinzuzufügen, wo man diese Einstellungen vornehmen kann?
(Wie beispielsweise im FireFox)

**Comment by jens-maus** [comment]
Bitte ein Beispiel einer solchen Proxy Konfiguration hier zeigen und erläutern wie das Problem selbst gelöst wurde.

**Comment by Wanderer2129** [comment]
Am Sa, 24. 11 18, 23:28:51 schrieb Jens Maus:
> Tut mir leid, ich verstehe immer noch nicht was du meinst oder willst.
> 
> 
Hallo Jens,

Entschuldigung, das war mir nicht klar. 

Alle Geräte in meinem Heimnetzwerk, welche sich mit dem Internet verbinden 
wollen, müssen über ein Gateway/Router mit integrierter Firewall und einem 
Proxyserver.
Die Firewall ist auch für ausgehende Verbindungen gesperrt, die Geräte bzw. 
Anwendungen müssen ihre Anfragen an den Proxy stellen, der diese dann ins 
Internet weiterleitet.
Das muss den Anwendungen, konkret der Raspberrymatic, irgendwie mitgeteilt 
werden.
Z.B. im Firefox-Browser gibt es dazu eine Einstellung, wie sich Fiorefox mit dem 
Internet verbinden soll. Dort gibt man die Ports an, getrennt oder gemeinsam für 
FTP, HTTP(S) etc.
Ich dachte, es wäre einfach, das in der RpiMatic zu realisieren.

Für HmIP gibt es, wie für HM auch, zwei Möglichkeiten, Geräte anzulernen, einmal 
mit der Eingabe von KEY/STGIN oder Gerätenummer, zum Anderen, indem man die 
Geräte einfach in den Anlernmodus versetzt.
Letzeres funktioniert bei HM und ist die von mir bevorzugte Methode.
Bei HmIP wird in diesem eine Internetverbindung vorausgesetzt, ich verstehe nicht, 
warum.

Genau das aber funktioniert nicht, da der RaspberryMatic, der Port des 
Proxyservers nicht bekannt ist, an den die Anfrage gerichtet werden müsste.

Ich benutze seit Kurzem die Raspberrymatic auf Tinkerboard und bin begeistert, 
danke für Deine Arbeit.

Vielleicht weiß auch jemand anderes, ob und wie das grrundsätzlich in der CCU zu 
konfigurieren ist, es wäre schon hilfreich, wenn es ohne GUI ginge.

Vielleicht kann man die Internetverbindung auch umgehen, was passiert da 
eigentlich im Internet, wenn ich nur in meinem Heimnetz ein HmIP-Gerät anlernen 
möchte? Ginge es nicht gänzlich ohne?

Klaus, der Wanderer

**Comment by hoedlmoser** [comment]
Du wirst damit leben müssen, daß sich die homematic
- zu secgtw.homematic.com:8443 bzgl hmIP,
- zu einem NTP server Deiner wahl und
- zu einem Google server zwecks internet-connectivity feststellung
verbindet.

gib das halt in Deiner firewall (mit logging) frei, ein proxy ist da nur hinderlich bzw unbequem.

**Comment by Wanderer2129** [comment]
Danke!
Zum Anlernen von HmIP-Geräten genügt es, den genannten Port temporär freizugeben, funktioniert.
Als NTP-Server verwende ich einen eigenen im LAN, der sich seinerseits natürlich die Zeit aus einem anderen Zeitserver holt. Die CCU selbst kann und muss nicht ins Internet.
Was den Google Server betrifft: Vielleicht gar nicht nötig für die CCU (Raspberrymatic). Funktioniert, bisher, alles ohne Internetverbindung.

**Comment by jens-maus** [comment]
Das mag sein, so ist es trotzdem nicht spezifiziert und ich denke es ist IMHO auch ein zu ängstliches vorgehen eine CCU so weit abzuschotten denn es spricht faktisch nichts dagegen das eine CCU mit den Homematic Servern, externen NTP Servern und zwecks Konnektivität auch google server anpingt in regelmäßigen Abständen.

Aber seis drum. Bzgl. dieses Ticket gibt es jedoch nichts weiteres zu tun denn nach weiteren Überlegungungen und den Hinweisen von @hoedlmoser ist es nicht wirklich sinnvoll irgendwelche Proxy-Settings nun versuchen in die CCU zu implantieren.
