### ISSUE TITLE
if-condition cannot be enhanced for system internal programs

### ISSUE THREAD

**Issue by mkrill** [jens-maus/RaspberryMatic#462]
When rebooting the Raspberrymatic, the counters for rain and sunshine of the hmip-swo-pl (weather sensor) are updated with wrong figures due to the execution of the corresponding system internal programs during reboot:

- prgSunshineCounter_14877_00181709ADB1C5:1
- prgRainCounter_14877_00181709ADB1C5:1
- prgSunshineCounter_14877_00181709ADB1C5:1

To avoid the execution of these programs during startup, I tried to add a condition to the if-clause of the programs above (see https://homematic-guru.de/homematic-programme-bei-neustart-verhindern for general mechanism). 

However, after clicking on the "+" Symbol in the if-clause, neither "UND" nor "ODER" are displayed, but a "?" instead. Enhancing if-clauses for my own programs works without any issues. The error only seems to appear in system internal programs.

**Screenshots**
<img width="990" alt="if-clause-error" src="https://user-images.githubusercontent.com/44435282/47868667-1991fa00-de05-11e8-8349-300d322ec1fd.PNG">

**System information (please complete the following information):**
 - Version 3.37.8.20181026
 - Hardware RaspberryPi3B

**Additional context**

**Comment by jens-maus** [comment]
@jp112sdl Kannst du das bei dir reproduzieren? Vmtl. wird hier in der WebUI das Eine oder Andere zuviel deaktiviert in internen Programmen?!? Sollte sich ggf. einfach lösen lassen.

**Comment by jp112sdl** [comment]
Ja lässt sich einfach reproduzieren.

Das `?` kommt, wenn `CndOperatorType` = 0 (`OPERATOR_NONE`)  ist
https://github.com/eq-3/occu/blob/master/WebUI/www/rega/esp/rule.inc#L78

Schau dir mal die
https://github.com/eq-3/occu/blob/master/WebUI/www/rega/pages/tabs/admin/views/newdevices.htm
an.

Dort werden die internen Programme beim Anlernen von Geräten angelegt.
Sie haben alle `"condition.CndOperatorType(OPERATOR_NONE);"`

_Könnte_ man sicher ändern... hab aber keine Ahnung, warum man dort bewusst `OPERATOR_NONE` gewählt hat.

**Comment by jens-maus** [comment]
> _Könnte_ man sicher ändern... hab aber keine Ahnung, warum man dort bewusst `OPERATOR_NONE` gewählt hat.

Danke für den Hint. Hab mal schnell in ReGa reingeschaut und da passiert bei `OPERATOR_NONE` im Grunde genau das gleiche wie `OPERATOR_OR`. Ich vermute, das das nur von eQ3 dahingehend verwendet wird das man damit vmtl. verhindern will das Otto-Normal-Verbraucher hier die internen Programme ändert. Könnte und IMHO sollte man dann entsprechend ändern weil wie hier im Ticket gezeigt es nur verwirrung und unbehagen stiftet. Was denkst du? Du/Wir könnten also einfach hier entweder die internen Programme nach OPERATOR_OR ändern oder nur die Anzeige gleich wie OPERATOR_OR machen in der WebUI. Die Frage wäre nur ob es sich dann trotz OPERATOR_NONE noch bedienen lässt?

**Comment by jp112sdl** [comment]
> passiert bei OPERATOR_NONE im Grunde genau das gleiche wie OPERATOR_OR

Dann würde ich vorschlagen, in der `rule.inc` die beiden Vorkommen von
`if( oC.CndOperatorType() == 2 ) { Write( '${ruleSelectOR}' ); }` 
zu ändern in
`if(  (oC.CndOperatorType() == 2) || (oC.CndOperatorType() == 0)  ) { Write( '${ruleSelectOR}' ); }`
sowie die Zeile
`if( oC.CndOperatorType() == 0 ) { Write( '?' ); }` 
ganz zu entfernen.

**Comment by jens-maus** [comment]
Probier das mal aus und check mal ob sich danach die internen programme normal editieren lassen, weil ich bin mir nicht sicher wie die WebUI im weiteren dann damit umgeht wenn ein Programm weiterhin die eigenschaft OPERATOR_NONE trägt.

**Comment by jp112sdl** [comment]
Die WebUI hat kein Problem damit.
Für die Darstellung des Verknüpfungstyps gibt es nur die beiden Stellen.

Fügt man eine weitere Bedingung hinzu, bekommt sie zwangsweise einen der beiden Typen `OPERATOR_OR` oder `OPERATOR_AND`. Die bestehende mit `OPERATOR_NONE` bleibt einfach bei `OPERATOR_NONE`.

Bei einem kurzen Klick-Test konnte ich keine Nachteile feststellen.
Wäre vielleicht was für einen Nightly Build und Powertester Baxxy ^^

_Verwirrend ist auch, dass die internen Programme zum Teil in der `newdevices.htm` angelegt werden und zum Teil via `hm_autoconf`_

**Comment by jens-maus** [comment]
> Bei einem kurzen Klick-Test konnte ich keine Nachteile feststellen.
> Wäre vielleicht was für einen Nightly Build und Powertester Baxxy ^^

Gut, dann würde ich mal sagen: Feuer frei! ;-)

> _Verwirrend ist auch, dass die internen Programme zum Teil in der `newdevices.htm` angelegt werden und zum Teil via `hm_autoconf`_

Das ist in der Tat verwirrend. Aber die `hm_autoconf` gehört einfach mal kräftig aufgeräumt genauso wie die `hm_startup`. Auch wegen so anderen Dingen wie dem "Klarnamenbug" z.B. den ich noch auf meiner engeren Agenda habe, aber das sollten wir dann mal im passenden Ticket diskutieren wie wir das auch dann noch lösen können. Jetzt erst einmal das Problem hier noch lösen, würde ich sagen :)

**Comment by mkrill** [comment]
Hallo zusammen, 

hatte das Thema schon fast aus den Augen verloren. Vielen Dank für den Fix.

BG, Michael
