### ISSUE TITLE
Renameing a device, what is used in a program, opening that program let the Raspberrymatic crash.

### ISSUE THREAD

**Issue by LTNightshade** [jens-maus/RaspberryMatic#464]
**Describe the bug**
Nach dem Umbenennen eines Devices (bei mir ein HUE-Licht), lässt das Öffnen eines Programms mit diesem Object die Rapsberrymatic abstürzen.

After renaming a device (for me a HUE-Light), opening a programm using this device let the Respberrymatic crash. 

**To Reproduce**
Ein Device umbenennen, das in einem Programm genutzt wird, anschliessendd das Programm öffnen

Rename a device, what is used in a Program, than open the program.

**Expected behavior**
Das Umbenannte Device  im Programm sehen.

See the renamed device in the program.

**System information (please complete the following information):**
 - Version: 3.37.8.20181026
 - Hardware:: RaspberryPi3 B+

**Comment by jens-maus** [comment]
Please present an example program and example procedure that it is more easy to reproduce the problem. Show screenshots, etc.

**Comment by LTNightshade** [comment]
i tried to  reproduce it, but can't get to crash again.
We may close this....
