### ISSUE TITLE
Doppelter/Falscher Status eines Gerätes bei Bedienung über WebUI oder Programm

### ISSUE THREAD

**Issue by Gerti1972** [jens-maus/RaspberryMatic#466]
Wenn ich unter Version RaspberryMatic 3.37.8.20181026 ein Gerät über die WebUI oder ein Programm bediene (ich habe es bei der Keymatic bemerkt und kann nicht sagen, ob es generell oder nur für die Keymatic gilt), dann wird der Status des Gerätes doppelt und teilweise sogar falsch an die Raspberrymatic übetragen. Im Systemprotokoll tauch das Gerät dann wie folgt auf:
Schloss verriegelt, Schloss entriegelt, Schlosszustand bekannt, Kein Fehler

Mit der Vorversion RaspberryMatic 3.37.8.20180929 tritt das Problem nicht auf, und im Systemprotokoll sieht es so aus:
Schloss entriegelt, Schlosszustand bekannt, Kein Fehler

Durch das Fehlverhalten unter der neuen Version werden Programme fälschlicherweise getriggert, die nicht hätten getriggert werden dürfen.
Ein Programm, dass z.B. auf Änderung "Keymatic verschlossen" triggert, wird dadurch manchmal auch ausgeführt, wenn die Keymatic verschlossen war und entriegelt wird.

Der Fehler konnte durch einen weiteren User bereits reproduziert werden.

**Comment by gmoerth** [comment]
**Doppelter Status**
Ich habe den selben Fehler und zwar bei dem Gerät "**HM-OU-LED16**". Es werden im Systemprotokoll alle Meldungen doppelt ausgegeben. Das war bei der vorigen Version noch nicht.

![hm-ou-led16](https://user-images.githubusercontent.com/34843746/47979989-ed58d080-e0c5-11e8-9dfb-beb0f19e03b5.png)

**Comment by jens-maus** [comment]
Nun, die Frage ist dich ob das lediglich ein Anzeigefehler des Systemprotokolles ist. Daher bitte ein die loglevel von RFD hochsetzen und beobachten ob hier in der Tat doppelt gesendet wird.

**Comment by cotonila** [comment]
Hab ein ähnliches Problem bei den Werten (zugeordnete Variablen) der Wetterstation 	HM-WDS100-C6-O-2. Wird alles doppelt angezeigt. Auch bei anderen Geräten tritt das sporadisch auf. Außerdem wird die Regenmenge (day) nicht mehr angezeigt. Gehe von einem Zusammenhang aus...

VG

**Comment by Gerti1972** [comment]
Du liest schon, was ich hier und im Forum geschrieben habe? Durch den Fehler werden nachweislich Programme getriggert, daher ist es kein Anzeigefehler.

**Comment by jens-maus** [comment]
@Gerti1972 Hab ich schon gelesen, allerdings bräuchte ich einen allgemeingültigen Testcase sonst kann ich hier nicht auf irgendeine Fehlersuche gehen. Hab kein KeyMatic oder die LED Anzeige. Muss ja ggf. auch mit anderen Geräten auftreten. Das Systemprotokoll selbst ist nicht aussagekräftig genug. Deshalb die bitte nach einem vollwertigen RFD Logfile der den Case nachbildet. D.h. den Loglevel von RFD hochstellen, Problem nachstellen und das Logfile abspeichern und dann analysieren.

**Comment by herbylfs** [comment]
Hi,
es betrifft auch die CCU3 selbst. Hier sind es vor allen die Schalt- und Messsteckdosen.
mfg
herby

**Comment by jens-maus** [comment]
Bitte Beispiel mit Schalt-/Messsteckdosen/aktoren zeigen.

**Comment by Gerti1972** [comment]
Da der kritische Fehler auch bei der CCU3 auftritt, habe ich Ihn direkt an eQ-3 gemeldet und ein Ticket erzeugt.

**Comment by jens-maus** [comment]
Mit der gerade erschienenen 3.41.11 der CCU3 Firmware sollte das Problem nun behoben sein. Das selbe passiert mit RaspberryMatic mit dem nächsten kommenden Release der dann auch auf der 3.41.11 basieren wird.
