### ISSUE TITLE
passwd segmentation fault

### ISSUE THREAD

**Issue by MarkThielen** [jens-maus/RaspberryMatic#469]
Hallo zusammen,

Beim Versuch das Passwort des root users zu ändern tritt ein segmentation fault auf (siehe unten).
System ist auf einem PI 3 Model B mit 16GB SD installiert. Alles andere funktioniert einwandfrei, habe meine alte CCU2 entsprechend auf das neue System umgezogen und bin beim ändern des Passwortes über dieses Problem gestolpert. 

Kann das jemand nachvollziehen ?

# Image
```
RaspberryMatic-3.37.8.20181026-rpi3
```

# Kommando
```
#passwd
Changing password for root
New password: 
Retype password: 
Segmentation fault
```

# Linux Version
```
#uname -a
Linux homematic 4.14.71 #1 SMP PREEMPT Thu Oct 25 11:31:56 CEST 2018 armv7l GNU/Linux
```
# CPU Info
```
# cat /proc/cpuinfo 
processor	: 0
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: BCM2835
Revision	: a22082
Serial		: 000000001ceae3c8
```

Viele Grüße,
Mark

**Comment by MarkThielen** [comment]
Liegt vermutlich daran das "/" read-only gemountet ist.

Ich denke man kann das issue schliessen. Danke :)

**Comment by MarkThielen** [comment]
Remounting "/" von RO nach RW löst das Problem nicht wirklich. Vielleicht ein Problem mit einer System Library oder ist das ändern das Passwortes nicht erwünscht/vorgesehen ?

```
# passwd
Changing password for root
New password: 
Retype password: 
double free or corruption (out)

**Comment by jens-maus** [comment]
Doch, das sollte/müsste gehen

**Comment by MarkThielen** [comment]
Leider nein, ich habe es auf mit unten angegebenen Versionen versucht (rpi0 und rpi3) beide zeigen das gleiche Verhalten. Leider ist auf der Distro kein gdb um dem Ganzen auf den Grund zu gehen.

```
VERSION=3.37.8.20181026
PRODUCT=raspmatic_rpi3
PLATFORM=rpi3

```
# mount -o rw,remount /
# passwd
Changing password for root
New password: 
Retype password: 
Segmentation fault
# mount
/dev/root on / type ext4 (rw,relatime,data=ordered)
devtmpfs on /dev type devtmpfs (rw,relatime,size=492456k,nr_inodes=123114,mode=755)
proc on /proc type proc (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime,mode=777)
tmpfs on /tmp type tmpfs (rw,noatime)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noatime,mode=755)
sysfs on /sys type sysfs (rw,relatime)
tmpfs on /var type tmpfs (rw,noatime,size=497068k)
tmpfs on /media type tmpfs (rw,noatime)
/dev/mmcblk0p3 on /usr/local type ext4 (rw,noatime,nodiratime,nodelalloc,data=journal)
/dev/mmcblk0p1 on /boot type vfat (ro,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro)
# passwd
Changing password for root
New password: 
Retype password: 
double free or corruption (out)
Aborted

**Comment by jens-maus** [comment]
Als Workaround bis das Problem beseitigt ist kann man aber über die WebUI einfach das SSH Passwort ändern, das entspricht der Änderung des root Passwortes.

**Comment by MarkThielen** [comment]
Ja, der angegebene Workaround funktioniert. Vielen Dank Jens !

PS.: Sehr cooles Projekt, Glückwunsch !
