### ISSUE TITLE
Feste IP nicht zugewiesen wenn beim Start Netz nicht verfügbar

### ISSUE THREAD

**Issue by psi-4ward** [jens-maus/RaspberryMatic#471]
Ich habe RaspberryMatic (latest) per LAN an nem Speedport. Fällt der Strom aus scheint der Raspi schneller zu starten als der Telekom Router. Auffällig ist hier, dass ich auch nach längerem Warten RaspiMatic nicht erreichen kann. Stecke ich den Raspi dann später noch mal aus und wieder an funktioniert es wie gewünscht.

Dieses Problem zu debuggen ist etwas schwierig, da ich ja erst nach nem Neustart drauf komme.
Ich vermute, dass `if-up.d/eQ3StartNetwork` hier Schluckauf hat.

Ggf ein Bug? Ideen wie ich das Problem eingrenzen könnte?
Warum wird die IP überhaupt manuell über ein Script gesetzt und nicht direkt in der `interfaces`?

**Comment by mema0007** [comment]
Hallo, in Kombination mit einer Fritzbox 7362 SL mit FritzOS habe ich einen ähnlichen  Fehler. Bei im Schnitt mindestens jedem dritten Neustart (in der Regel Reboot) des Pi bekommt dieser anscheinend auch nicht seine statische IP gesetzt. Nach dem Trennen und wieder Einstecken der LAN-Verbindung oder ersatzweise einem Reboot der Fritzbox ist der Pi dann wieder unter der statischen IP erreichbar.

**Comment by jens-maus** [comment]
Existiert dieses Problem noch mit der aktuellen RaspberryMatic Version?

**Comment by psi-4ward** [comment]
Ja, allerdings trat das Problem nun "nur noch" bei 2 von 3 Versuchen auf.

**Comment by mema0007** [comment]
Hallo Jens, sorry für die späte Rückmeldung, war erst über Ostern wieder am Standort. 
Der Fehler tritt auch mit der aktuellen Version weiterhin auf.
