### ISSUE TITLE
Taster schaltet nur 1 Gerät (WebUI) statt wie verknüpft 2

### ISSUE THREAD

**Issue by AdlerCentauri** [jens-maus/RaspberryMatic#473]
Hallo!

Ich verweise auf diesen Thread mit dem darin beschriebenen Problem:

https://homematic-forum.de/forum/viewtopic.php?f=65&t=46816

**Comment by jens-maus** [comment]
Tschuldigung, aber so schreibt man keinen Bugreport, einfach mit einem verweis auf etwas anderem wo sich dann der Entwickler die Informationen aufwendig zusammensuchen muss. Nicht ohne Grund haben die Bugtickets templates die ausgefüllt gehören und nicht einfach gelöscht werden sollen. Daher bitte das Ticket entsprechend anlegen ansonsten wird es hier keine Bearbeitung geben.
