### ISSUE TITLE
Taster schaltet nur 1 Gerät (WebUI) statt wie verknüpft 2

### ISSUE THREAD

**Issue by AdlerCentauri** [jens-maus/RaspberryMatic#476]
**To Reproduce**

1. Go to 'Status und bedienung -> Geräte z.B. "HM-PB-2-WM55"'
2. Click on 'Langer Tastendruck'
4. See error (Es gibt keine WebUI Fehlermeldung)

**Expected behavior**
Es sollten alle mit dem Gerät z.B. HM-PB-2-WM55 an Sirene und KeyMatic verknüpften (DV) Geräte geschalten werden.

**Screenshots**
Das Problem ist an einem Screenshot nicht zu zeigen.

**System information (please complete the following information):**
 - Version: RaspberryMatic 3.37.8.20181026
 - Hardware: RaspberryPi3 B+

**Additional context**
Ich habe auf diversen Tastern z.B. HM-PB-2-WM55 und Fernbedienungen z.B HM-RC-Key3-B (Keine HmIP Taster o. Fernbedienungen) auf derselben Taste eine DV mit der Sirene (HM-Sec-Sir-WM) und der KeyMatic (HM-Sec-Key-S) erstellt. 

Wenn ich (hier ist das schalten der Geräte über die WebUI gemeint - An den Geräten direkt funktioniert alles.) z.B. die Taste "Türe schliessen" (Langer Tastendruck) drücke, dann wird die Sirene in den Hüllschutz geschaltet und die KeyMatic verriegelt. Seit der RaspberryMatic Version 3.37.8.20181026 funktioniert das nicht mehr.

Wenn ich die Taste (Langer Tastendruck) in der WebUI drücke, dann wird nur die Sirene in den Hüllschutz geschaltet, die KeyMatic wird nicht geschaltet. Ich bin gerade zum Test wieder zurück auf die Version RaspberryMatic 3.37.8.20180929 und mit dieser Funktioniert es wieder wie es soll. Wenn ich die Taste (Langer Tastendruck) drücke, wird die Sirene in den Hüllschutz geschaltet und die KeyMatic verriegelt.

Dann bin ich wieder auf die 3.37.8.20181026 und dann funktioniert es nicht, es wird nur die Sirene geschaltet.

**Comment by jens-maus** [comment]
Dieses Problem könnte mit #466 zusammenhängen das jedoch inzwischen behoben wurde. Bitte dazu die nächste erscheinende RaspberryMatic version kontrollieren. Vmtl. repariert diese dieses Problem auch bereits.

**Comment by jens-maus** [comment]
Dieses Problem sollte mit der Version 3.41.11.20181124 behoben sein. Bitte wieder eröffnen falls nicht.

**Comment by AdlerCentauri** [comment]
Hallo, das Problem besteht aktuell mit der RaspberryMatic 3.41.11.20181126 wieder.

**Comment by jens-maus** [comment]
Da es anscheinend Anzeichen gibt das der Bug ggf. doch noch nicht behoben ist eröffne ich das Ticket hier mal wieder und bitte um Mithilfe und exakter Beschreibung (mit schritt-für-schritt Anleitung) wie das Problem auf einer frischen RaspberryMatic installation mit neuester 3.41.11.20181226 Firmware reproduziert werden kann.

**Comment by TheRoolBool** [comment]
Same here

**Comment by TheRealTremes** [comment]
Das Problem besteht mit aktueller RaspberryMatic 3.43.15.20190223 Version immer noch.

**Comment by LevelOne2k** [comment]
Das Problem besteht nach wie vor exakt genau so.

Das Problem existiert nur auf einer RaspberryMatic. Das Problem existiert nicht auf einer CCU3 Firmware.

**Comment by jens-maus** [comment]
Existiert dieses Problem noch mit aktuellem RaspberryMatic Release?

Wenn ja dann bitte eine Schritt-für-Schritt Anleitung für eine frische RaspberryMatic Version posten mit angaben von beispielgeräten (Keine KeyMatic, da ich die nicht habe!) mit denen das passiert damit ich mir das detailliert dann anschauen kann.
