### ISSUE TITLE
HmIP-SMO(-A) does not reset its status automatically

### ISSUE THREAD

**Issue by kais0r** [jens-maus/RaspberryMatic#477]
**Describe the bug**
HmIP-SMO setzt den Status "Bewegung erkannt" nicht von selbst zurück

**To Reproduce**
1. Gerät anlernen: HmIP-SMO
2. Bewegung erkennen lassen
3. Problem: Bewegung wird niemals vom Gerät nach der eingestellten Zeit zurückgesetzt.

**Expected behavior**
Der Status "Bewegung erkannt" sollte nach der eingestellten Zeit ohne Bewegung (Nach Werkseinstellung 4min) zurückgesetzt werden.

**Screenshots**
Systemprotokoll und Setup
![hmip-hmo](https://user-images.githubusercontent.com/42624158/48945110-73c83b80-ef29-11e8-89a0-0bd10e6b0c15.png)

Einstellung (=Werkseinstellung nach Geräte-Reset)
![image](https://user-images.githubusercontent.com/42624158/48945295-1aacd780-ef2a-11e8-89c6-959c240cba7f.png)

(Geräte Status)
![image](https://user-images.githubusercontent.com/42624158/48945326-31532e80-ef2a-11e8-9fd1-db9b3f538e88.png)

**System information (please complete the following information):**
 - Version RaspberryMatic 3.37.8.20181026
 - Firmware Version HmIP-SMO 1.0.2
 - Hardware RaspberryPi 3
 - Funkmodul für Raspberry Pi HM-MOD-RPI-PCB
 - 2x Homematic IP Bewegungsmelder HmIP-SMO
 - 2x Homematic IP Präsenzmelder HmIP-SPI – innen
 - 3x Homematic IP Rauchmelder HmIP-SWSD

**Additional context**
Es wurden bereits weitere "IT-Übliche" Tests gemacht...
Wir beistzen auch einen zweiten SMO, welcher das gleiche Problem hat.
Außerdem haben wir noch die Präsenzmelder innen, welche tadellos funktionieren.
Auch wurden mal beide angelernt, die Zeiten verändert, etc...
ELV ist laut Telefonsupport auch erst mal ratlos. Über die Bewegungsmelder sind keine generellen Fehler bekannt.

**Comment by kais0r** [comment]
Der Bewegungsmelder befindet sich noch immer im verschlossenen Schrank, welcher seither nicht geöffnet oder bewegt wurde. Hier ein Zwischenstand des Systemprotokolls:

![image](https://user-images.githubusercontent.com/42624158/48954168-ac2b4200-ef48-11e8-8b3b-41ccafbf7926.png)

**Comment by kais0r** [comment]
Stand 24.11.2018: Immernoch in Status "Bewegung erkannt". Der Melde befindet sich aber 
in einem verschlossenen Schrank.

Hier die Log als Zip:

[2018-11-24_1914History.zip](https://github.com/jens-maus/RaspberryMatic/files/2612484/2018-11-24_1914History.zip)

Screenshot: 
![image](https://user-images.githubusercontent.com/42624158/48971694-b408e600-f01d-11e8-9155-03808e618cbd.png)

Fazit:
Der Bewegungsmelder übermittelt offenbar Telegramme, denn die Helligkeit wurde aktualisiert.
Der Bewegungs-Status kommt entweder falsch an oder wird falsch Interpretiert.
ELV / eQ3 melden keine Beschwerden im Einsatz mit der original CCU...

**Comment by libertyx82** [comment]
Original CCU? welche? 2 oder 3 oder ggf. IP AccessPoint?

Ich bezweifle das dies ein Problem der RaspMatic ist, daher wäre interessant, ob dies auch auf einer CCU3 auftritt, denn nur die ist identisch zur RaspMatic.

**Comment by kais0r** [comment]
Siehe **System information** und **Additional context** .

Ich besitze derzeit zwei vom Typ HmIP-SMO, welche beide das Problem haben. Mit nur einem Melder hätte ich mich nicht getraut ein issue zu erstellen. Da aber zwei betroffen sind, ist ein Hardwaredefekt unwahrscheinlicher.

ELV gab die Rückmeldung, dass mit der CCU? es keine Probleme gibt.
Der nette Herr von ELV hat einen sogar Privat im Einsatz an AccessPoint - ohne Probleme.

Er vermutet auch, dass es nur an RaspberryMatic liegen kann. Zwei Defekte SMO sind unwahrscheinlich.

Ich habe das Logging oben mit einem gemacht, der Übersicht halber.

**Comment by libertyx82** [comment]
ELV ist aber auch nicht der Hersteller sondern nur ein Vertriebspartner, Hersteller ist eq-3 und das ELV nichts bekannt ist, heißt nicht das dem auch so ist.

Ein AccessPoint hat auch mit einer CCU nichts zu tun, ein AccessPoint ist nur ein Gateway, der die Verbindung der Geräte mit der Cloud herstellt, sonst kann der nix.

Zwei defekte Geräte sind in der Tat eher unwahrscheinlich, denn och würde ich diese einmal ablernen, auf Werkseinstellungen zurücksetzten und neu anlernen.

Tritt das Problem weiterhin auf, würde ich eher den Fehler in der OCCU suchen, daher wäre es dann interessant, ob noch mehr das gleiche Verhalten haben, heißt, du solltest im Homematic-Forum mal ein Thema dazu erstellen.

CCU3 wäre besser, denn die ist identisch mit der RaspMatic.

**Comment by kais0r** [comment]
> Die eQ-3 AG ist ein 2007 von der ELV Elektronik AG ausgegründetes deutsches Technologieunternehmen im Bereich Smart Home mit Hauptsitz in Leer.
Also ich würde sagen etwas mehr als nur der Vertriebspartner.

Man beachte nur mal die Telefonnummern des technsichen Supports:
ELV: 0491 / 6008 245
EQ3: 0491 / 6008 680

Wie im ersten Beitrag erwähnt, wurden die Melder selbstverständlich mehrmals auf Werkseinstellungen zurück gesetzt. Mit Originaleinstellungen sowie mit verschiedensten Einstellungen getestet.

Die Geräte wurden auch mehrmals ab- und angelernt. Zusammen, einzeln, nacheinander, hintereinander... Natürlich wurde auch der Raspi mehrmals durchgestartet etc...

Bitte nur melden wer den BUG bestätigen oder tatsächlich mit eigener Hardware wiederlegen kann. Danke.

**Comment by libertyx82** [comment]
> > Die eQ-3 AG ist ein 2007 von der ELV Elektronik AG ausgegründetes deutsches Technologieunternehmen im Bereich Smart Home mit Hauptsitz in Leer.
> 
> Also ich würde sagen etwas mehr als nur der Vertriebspartner.
> 
> Man beachte nur mal die Telefonnummern des technsichen Supports:
> ELV: 0491 / 6008 245
> EQ3: 0491 / 6008 680

Danke, ich kenne die Geschäftsstruktur und eq-3 ist eine Tochter im Unternehmensverbund.
Aber dennoch nur für den Vertrieb zuständig. 

> Wie im ersten Beitrag erwähnt, wurden die Melder selbstverständlich mehrmals auf Werkseinstellungen zurück gesetzt. Mit Originaleinstellungen sowie mit verschiedensten Einstellungen getestet.
> 
> Die Geräte wurden auch mehrmals ab- und angelernt. Zusammen, einzeln, nacheinander, hintereinander... Natürlich wurde auch der Raspi mehrmals durchgestartet etc...
> 
> Bitte nur melden wer den BUG bestätigen oder tatsächlich mit eigener Hardware wiederlegen kann. Danke.

Es ist ja schön was du schon alles getan hast, du solltest aber einmal verifizieren, ob der Fehler auch noch bei anderen auftritt und ggf ob er auch auf einer CCU3 auftritt.
Es wäre durchaus möglich, dass es sich um einen Bug handelt, der dann wohl aber eher in der OCCU zu suchen ist, somit wärst du hier falsch.

**Comment by kais0r** [comment]
Folgender Forenbeitrag behandelt das gleiche Problem.
[https://homematic-forum.de/forum/viewtopic.php?t=42372](url)

Die Änderung dieser Option führt tatsächlich dazu dass die Melder laufen.
![image](https://user-images.githubusercontent.com/42624158/48985601-71bcd300-f109-11e8-9a78-6134ee213442.png)

Funktionierende Settings: Checkbox Deaktiviert!
![image](https://user-images.githubusercontent.com/42624158/48985609-89945700-f109-11e8-9643-f321d0841159.png)

Weiterer Link:
[https://www.elv.de/topic/meldet-dauerbewegung-firmwareproblem.html](url)

Bleibt nun die Frage ob es ein BUG auf Melder-Seite ist oder in der CCU/RaspberryMatic...

**Comment by libertyx82** [comment]
Entweder Firmware des Gerätes oder Firmware der CCU also kein alleiniges Problem der RaspMatic

**Comment by kais0r** [comment]
> Sehr geehrter Herr Kaiser,
>
> hiermit möchten wir uns für das von Ihnen entgegengebrachte Interesse an unseren Produkten 
> bedanken.
> 
> Das beschriebene Verhalten tritt voraussichtlich auch mit Raspberrymatic-Version 3.41.11.20181124 auf > und wird derzeit bereits vom Hersteller untersucht.
> Eine Lösung wird voraussichtlich mit einer kommenden Zentralenfirmware bereitgestellt werden.
> 
> Bis die Lösung verfügbar ist, empfehlen wir Ihnen, in den Geräteeinstellungen des Bewegungsmelders > den Haken bei "innerhalb des Sendeabstandes erkannte Bewegungen senden" zu entfernen.
> Erkannte Bewegungen sollten anschließend korrekt zurückgesetzt werden.
> 
> Sollten Sie weitere Fragen haben, kontaktieren Sie uns gerne per E-Mail, FAX oder Telefon.
> Unsere Kontaktdaten und Erreichbarkeiten entnehmen Sie bitte unserem Serviceportal unter ...
> 
> Mit freundlichen Grüßen
> ELV Elektronik AG
> Ihr Team der Technischen Kundenbetreuung

**Comment by jens-maus** [comment]
Na dann können wir das ja auf die Liste der Dinge setzen die eQ3 selbst reparieren muss und auf das RaspberryMatic keinen Einfluss hat.

**Comment by HMside** [comment]
Der Bug dürft mit der SMO Firmware 1.2.8 behoben sein. Wichtig, wie [hier](https://www.homematic-ip.com/service/faq/warum-werden-einige-firmware-dateien-nicht-zum-download-in-der-webui-angeboten.html) beschrieben muss das Gerät nach dem Update von der Zentrale ab- und anschließend erneut angelernt werden!

[Update File für HmIP-SMO-A](https://www.homematic-ip.com/downloads/software/firmware/homematic_ip/HmIP-SMO-A_update_V1_2_8_180326.tgz)
[Update File für HmIP-SMO](https://www.homematic-ip.com/downloads/software/firmware/homematic_ip/HmIP-SMO_update_V1_2_8_180326.tgz)

**Comment by jens-maus** [comment]
Existiert dieses Problem noch mit der aktuellen RaspberryMatic Version?

**Comment by xconsult** [comment]
Das Problem tritt auch mit einer original CCU3 und aktueller CCU3 Firmware auf.
Mein HmIP-SMO-A hat aktuell die Firmware 1.0.2 und ich mache gerade das Update auf 1.2.8.

**Comment by kais0r** [comment]
Sorry, war etwas update-faul. Teste ich die Tage.

**Comment by jens-maus** [comment]
Ist das Problem mit dem FW-Update auf die 1.2.8 für das Gerät nun behoben oder nicht?

**Comment by kais0r** [comment]
Tut mir Leid - heute habe ich Zeit gefunden mir das anzusehen...

**Test 1** 
RaspMatic: 3.45.5.20190330
HmIP-SMO-A: 1.0.2
--> Problem vorhanden und reproduzierbar

**Test 2**
RaspMatic: 3.47.18.20190918
HmIP-SMO-A: 1.0.2
--> Problem vorhanden und reproduzierbar

**Test 3**
RaspMatic: 3.47.18.20190918
HmIP-SMO-A: 1.2.8
--> Problem behoben

**Comment by jens-maus** [comment]
Ok, dann kann das Problem also nun geschlossen werden. Danke für das testen.
