### ISSUE TITLE
"hue" script fehlt

### ISSUE THREAD

**Issue by Tscherno** [jens-maus/RaspberryMatic#478]
Ich  habe seit einem IP Wechsel des Hue-Hubs Probleme ihn wieder zum Laufen zu bringen. Laut community
https://homematic-forum.de/forum/viewtopic.php?f=65&t=45578&p=470129#p470129

soll ein Löschen / Neuanlegen helfen:

> cd /usr/local/etc/config/rc.d
> ./hue uninstall

Leider fehlt das Script scheinbar komplett (ich habe auch gesucht).

**Comment by jens-maus** [comment]
`hue` ist und war noch nie Teil von RaspberryMatic sondern ist teil eines Drittanbieteraddons. Von daher ist das Melden in diesem Issue Tracker leider nicht die richtige stelle.
