### ISSUE TITLE
Zusatzsoftware: Prüfung auf verfügbare Version in Safari nicht möglich 

### ISSUE THREAD

**Issue by jp112sdl** [jens-maus/RaspberryMatic#480]
Seit 3.41.11.20181124 wird beim Aufruf von Systemeinstellungen->Zusatzsoftware die Datei<br> `update-check.cgi` heruntergeladen. Sie enthält nur die Versionsnummer.

Unter 3.37.8.20181026 ging es.

<img width="1009" alt="bildschirmfoto 2018-11-25 um 12 04 20" src="https://user-images.githubusercontent.com/18190139/48978358-bf562300-f0aa-11e8-9f2c-96cdd40e5813.png">

**Comment by jp112sdl** [comment]
Siehe auch: https://homematic-forum.de/forum/viewtopic.php?f=65&t=47031

**Comment by darkbrain85** [comment]
Es wird sogar pro installierten Addon eine Datei heruntergeladen. Ich habe 6  Addons und auch 6 Dateien. 5 Davon nur als "Temp" Datei die nicht vollständig geladen wird. 

<img width="881" alt="bildschirmfoto 2018-11-25 um 12 18 04" src="https://user-images.githubusercontent.com/5204755/48978477-422bad80-f0ac-11e8-8394-be239b28b3b2.png">

**Comment by jens-maus** [comment]
Ich kann das Problem bestätigen, jedoch scheint es lediglich mit Safari aufzutreten.

**Comment by hobbyquaker** [comment]
Das Problem hängt glaube ich mit dem `Content-Type` Header zusammen, trat bei mir auch an anderen Stellen auf (RedMatic Settings Seite wurde als text/plain statt als text/html an den Browser gesendet). Hab das nun umschifft indem ich in allen .cgi in RedMatic explizit den Header setze, damit funktioniert auch wieder die Anzeige der verfügbaren Version in Safari.

**Comment by jens-maus** [comment]
@hobbyquaker Ich bin schon dabei eine Lösung bzgl. fehlendem Content-Type zu erarbeiten sodass nicht alle Addons (schon wieder) ihre update-check.cgi anpassen müssen.
