### ISSUE TITLE
openHAB Verbindung seit 3.41.11.20181124 nicht mehr möglich

### ISSUE THREAD

**Issue by chrostek** [jens-maus/RaspberryMatic#481]
**Describe the bug**
openHAB Verbindung zu RaspberryMatic seit 3.41.11.20181124 nicht mehr möglich

**System information (please complete the following information):**
 - Version RaspberryMatic 3.41.11.20181124
 - Hardware RaspberryPi3
 - openHAB 2.3.0

Seit dem Update schlägt die Verbindung von openHAB zu RaspberryMatic mit folgender Meldung fehl:

> 2018-11-25 12:29:50.054 [INFO ] [ommunicator.AbstractHomematicGateway] - HmGatewayInfo[id=CCU,type=CCU2,firmware=3.41.11.20181124,address=123456789,wired=false,hmip=true,cuxd=false,group=true]
> 2018-11-25 12:30:05.081 [ERROR] [matic.handler.HomematicBridgeHandler] - Homematic bridge was set to OFFLINE-COMMUNICATION_ERROR due to the following exception: Read timed out
> java.net.SocketTimeoutException: Read timed out
>         at java.net.SocketInputStream.socketRead0(Native Method) ~[?:?]
>         at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:?]
>         at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:?]
>         at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:?]
>         at org.openhab.binding.homematic.internal.communicator.message.BinRpcMessage.<init>(BinRpcMessage.java:74) ~[?:?]
>         at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:77) ~[?:?]
>         at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:66) ~[?:?]
>         at org.openhab.binding.homematic.internal.communicator.client.RpcClient.init(RpcClient.java:87) ~[?:?]
>         at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.init(BinRpcClient.java:54) ~[?:?]
>         at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.startServers(AbstractHomematicGateway.java:249) ~[?:?]
>         at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.initialize(AbstractHomematicGateway.java:183) ~[?:?]
>         at org.openhab.binding.homematic.handler.HomematicBridgeHandler.lambda$0(HomematicBridgeHandler.java:87) ~[?:?]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
>         at java.lang.Thread.run(Thread.java:748) [?:?]
> 

Auf der RaspberryMatic ist in den Logs folgendes zu dem Zeitpunkt zu sehen:

/var/log/lighttpd-access.log:

> 172.17.2.16 172.17.0.72:2010 - [25/Nov/2018:12:30:20 +0100] "POST / HTTP/1.1" 200 123 "-" "Jetty/9.3.21.v20170918"
> 172.17.2.16 172.17.0.72:9292 - [25/Nov/2018:12:30:20 +0100] "POST /groups HTTP/1.1" 200 123 "-" "Jetty/9.3.21.v20170918"
> 172.17.2.16 172.17.0.72:2001 - [25/Nov/2018:12:30:30 +0100] "POST / HTTP/1.1" 200 2378 "-" "Jetty/9.3.21.v20170918"
> 172.17.2.16 172.17.0.72:2001 - [25/Nov/2018:12:30:30 +0100] "POST / HTTP/1.1" 200 1138 "-" "Jetty/9.3.21.v20170918"
> 172.17.2.16 172.17.0.72:2000 - [25/Nov/2018:12:30:30 +0100] "POST / HTTP/1.1" 503 2896 "-" "Jetty/9.3.21.v20170918"
> 172.17.2.16 172.17.0.72:2010 - [25/Nov/2018:12:30:30 +0100] "POST / HTTP/1.1" 200 123 "-" "Jetty/9.3.21.v20170918"
> 172.17.2.16 172.17.0.72:9292 - [25/Nov/2018:12:30:30 +0100] "POST /groups HTTP/1.1" 200 123 "-" "Jetty/9.3.21.v20170918"
> 

/var/log/lighttpd-error.log:

> 2018-11-25 12:30:30: (gw_backend.c.245) establishing connection failed: Connection refused socket: tcp:127.0.0.1:32000
> 2018-11-25 12:30:30: (gw_backend.c.960) all handlers for /? on  are down.
> 2018-11-25 12:30:32: (gw_backend.c.324) gw-server re-enabled: tcp:127.0.0.1:32000 127.0.0.1 32000
> 

Vor dem Update hat alles funktioniert. Nach einem Downgrade funktioniert auch wieder alles. Die neuen Firewall-Einstellungen sind testweise komplett offen eingestellt gewesen (Alle Ports offen, Vollzugriff, etc).

**Comment by jp112sdl** [comment]
@libertyx82 Hmm...
https://homematic-forum.de/forum/viewtopic.php?f=26&t=46282&p=466109#p466109

>  da lighttpd als Proxy für BINRPC nicht eingesetzt werden kann


Jetzt bin auch ich verwirrt. 😕

**Comment by libertyx82** [comment]
Ooh... diese Diskussion ist mir entgangen :(

Dann ist es wohl so das diese nicht mehr unterstützt wird, im changelog ist auch nur von der XMLRPC die Rede und nicht von der BINRPC.

Mein CUxD verbindet sich aber noch, wenn man die "Firewall-Richtlinie" auf Ports offen einstellt und der kann ja auch nur BINRPC

**Comment by jens-maus** [comment]
Als erstes sollte man ImmOpenHabnFotum klären das XMLRPC Unterstützung hinzugefügt wird bzw wie man die aktivieren kann. Soweit ich weiss wurden dazu bereits Arbeiten vorgenommen in OpenHab. Und nur wenn das nicht geht kann man natürlich alternativ dazu momentan noch (irgendwann wird das ggf auch nicht mehr gehen) den jeweiligen 3xxxx Port in der Firewall der CCU/RaspberryMatic freigeben und dann diesen in OpenHab als den BINRPC port eintragen. Aber wie gesagt, vorderrangig sollte man natürlich versuchen OpenHab auf XMLRPC umzustellen.

**Comment by chrostek** [comment]
openHAB kann scheinbar XML-RPC (und BIN-RPC) ... werde die Tage mal versuchen rauszufinden, wie man XML-RPC erzwingt:

https://www.openhab.org/addons/bindings/homematic/

**Comment by chrostek** [comment]
@jens-maus vielleicht wäre ein Hinweis in den Changelogs gut, damit andere openHAB Nutzer nicht auch unvorbereitet auf das Problem stoßen. Man sieht zwar, dass durch den reverse-proxy und die Firewall viel an der Stelle gemacht wurde - aber dass BIN-RPC/openHAB dadurch nicht mehr geht, hatte ich jetzt nicht rausgelesen

**Comment by jens-maus** [comment]
Dann schreib einen entsprechenden Beitrag im OpenHab Forum! Ich als Einzelperson kann wirklich nicht auf jede Belange der externen Anwendungen angehen. Und die Änderungen an den Sicherheitseinstellungen sind nichts RaspberryMatic spezifisches sondern das gleiche tritt auch mit einer CCU3 mit Original 3.41.11 Firmware auf.

**Comment by chrostek** [comment]
Das war kein Vorwurf! Sorry, wenn das so rüber kam. Ich meinte nur jetzt, wo es festgestellt wurde, könntest du es in den Changelogs aufnehmen. Ich hatte nicht gemeint, dass du das vorher hättest feststellen und aufnehmen müssen!

**Comment by hoedlmoser** [comment]
ich hab das uneigennützig auf https://homematic-forum.de/forum/viewtopic.php?f=64&t=46979 kundgetan.

> dass openHAB 2.4.0.M6 nun XMLRPC unterstützt, da ja mit der CCU3 3.41.x aufgrund der verbesserten firewall das BINRPC nicht mehr für extern zur verfügung steht. siehe https://community.openhab.org/t/openhab-2-4-milestone-builds/50359/119 und https://github.com/eclipse/smarthome/issues/6446

**Comment by jens-maus** [comment]
Danke!

**Comment by jens-maus** [comment]
Damit sollte das Problem erklärt und gelöst sein.

**Comment by c--r** [comment]
zur Info: nicht ganz, denn die Aussage, dass openhab ja jetzt XMLRPC unterstützt, gilt nur für das Openhab Homematic 2.x Add-on. 

User, die noch Openhab1.x nutzen (oder Openhab2 mit dem Homematic 1.x Add-on) haben leider das Problem, sich nicht zur CCU3.41 connecten zu können!

**Comment by c--r** [comment]
warum so gereizt?
Das war ja keine Kritik, sondern ein gutgemeinter Hinweis für alle (im Sinne des Community-Gedankens), die das gleiche Problem haben (s. Titel des Issues) und zugleich die Suche nach einem Tipp. Es sind vielleicht gar nicht so wenige User, die noch nicht migriert haben und z.B. noch Openhab1 einsetzen. Dafür kann es ja auch gute Gründe geben. In meinem Fall ist es z. B. so, dass das Homematic2 Add-on in einem kleinen, aber für mich entscheidenden Punkt sich anders verhält als das alte. Zudem ist es auch ein gewisser Aufwand, 3000+ Zeilen Rules inkl. etwas komplexerer Lambdas zu migrieren und zu testen.
