### ISSUE TITLE
iptables default policy

### ISSUE THREAD

**Issue by hoedlmoser** [jens-maus/RaspberryMatic#483]
a default policy of an iptables chain should be always set to ACCEPT to avoid blocking all access to the CCU in case of flushing of the chain.

instead of using the default policy, make an explicit DROP or REJECT rule at the bottom of the chain that matches everything.

better use the REJECT target rather than DROP to get an immediate rejection of your traffic instead of wondering if your packet is being dropped or if it’s making it to your CCU at all.

see also https://homematic-forum.de/forum/viewtopic.php?f=65&t=47044

I already have a patch for /lib/libfirewall.tcl

```diff
--- /lib/libfirewall.tcl.orig
+++ /lib/libfirewall.tcl
@@ -37,7 +37,7 @@
 
 ##
 # @const Firewall_MODE_RESTRICTIVE
-# Firewall Modus RESTRICTIVE. INPUT Policy DROP
+# Firewall Modus RESTRICTIVE. INPUT Policy ACCEPT. Last Rule REJECTs all.
 ##
 set Firewall_MODE_RESTRICTIVE "RESTRICTIVE"
 
@@ -435,8 +435,10 @@
   global Firewall_SERVICES Firewall_IPS Firewall_USER_PORTS
   
 #IPv4
+  # flush rules
   try_exec_cmd "/usr/sbin/iptables -F"
-
+  # default INPUT policy ACCEPT
+  try_exec_cmd "/usr/sbin/iptables -P INPUT ACCEPT"
   # allow all loopback
   try_exec_cmd "/usr/sbin/iptables -A INPUT -i lo -j ACCEPT"
   # allow all established and related packets to pass  
@@ -460,8 +462,8 @@
   if { $has_ip6tables } {
     # flush rules
     try_exec_cmd "/usr/sbin/ip6tables -F"    
-    # default INPUT policy DROP
-    try_exec_cmd "/usr/sbin/ip6tables -P INPUT DROP"  
+    # default INPUT policy ACCEPT
+    try_exec_cmd "/usr/sbin/ip6tables -P INPUT ACCEPT"
     # allow all loopback
     try_exec_cmd "/usr/sbin/ip6tables -A INPUT -i lo -j ACCEPT"
     # allow all established and related packets to pass  
@@ -548,8 +550,11 @@
     try_exec_cmd "/usr/sbin/iptables -A INPUT -p icmp --icmp-type echo-request -m state --state NEW -j ACCEPT"
   }
 
-    # default INPUT policy DROP (do this at very last step)
-  try_exec_cmd "/usr/sbin/iptables -P INPUT DROP" 
+  # default INPUT rule REJECT (do this at very last step)
+  try_exec_cmd "/usr/sbin/iptables -A INPUT -j REJECT" 
+  if {$has_ip6tables} {
+    try_exec_cmd "/usr/sbin/ip6tables -A INPUT -j REJECT" 
+  }
 
 }
 

```

**Comment by jens-maus** [comment]
Passiert hier noch etwas und in PR #486? Die default policy würde ich wie gesagt nicht ändern wollen weil ich es durchaus für sinnvoll erachte das diese auf DROP steht.

**Comment by hoedlmoser** [comment]
wenn wir uns darauf einigen können, daß die default policy auf DROP bleibt, die letzte rule aber eine REJECT auf den rest sein wird, dann würde ich am mittwoch noch was nachliefern.

**Comment by hoedlmoser** [comment]
die ansichten bzgl DROP und REJECT divergieren. ich begeb mich auf die suche nach stichhaltigeren argumenten.

**Comment by mkninc** [comment]
Die default policy auf DROP zu lassen ist sicherlich sinnvoll.
Dann stell ich mal die Frage, welche echten Vorteile bringt ein DROP am Ende gegenüber einem REJECT?

**Comment by mkninc** [comment]
Deshalb ja auch die Frage nach „echten“ Vorteilen.  
http://www.chiark.greenend.org.uk/~peterb/network/drop-vs-reject

**Comment by jens-maus** [comment]
@mkninc Danke für den Link. Das hat mich überzeugt :) Macht durchaus sinn was da beschrieben ist und ich denke unter den Umständen kann ich #486 wieder aufmachen und wohl auch akzeptieren.

**Comment by jens-maus** [comment]
Done, hab den PR nun gemerged. Danke!
