### ISSUE TITLE
XML-RPC HmIP ParseError bei newDevices

### ISSUE THREAD

**Issue by Maro25** [jens-maus/RaspberryMatic#489]
Nach dem Hinzufügen eines hmip-psm Aktors kann man sich nicht mehr an der HMIP-Schnittstelle Port 2010 anmelden. Nach dem Init-Befehl kommt als Antwort "listDevices". Auf listDevices antwortet meine Software mit einem leeren Array. Normalerweise werden jetzt alle vorhandenen Devices mittels "newDevice" Aufruf zurück gegeben. Die CCU löst intern jedoch eine Exception aus. Entsprechendes Log ist angehängt. 
Wenn ich den Aktor ablerne, werden alle Devices zurück gegeben. Sobald er wieder angemeldet ist, kommt wieder die Exception. Ich kann mangels Aktoren leider nicht testen, ob der Fehler auch mit einem anderen Aktor-/Typ auftritt. 

**System information**
 - Version RaspberryMatic 3.41.11.20181124
    gleiches Problem auch schon in der vorherigen Version 3.37.8.20181026
 - Hardware Raspberry Pi 2

[ccu-Error hmip-psm-log.txt](https://github.com/jens-maus/RaspberryMatic/files/2614773/ccu-Error.hmip-psm-log.txt)

**Comment by jens-maus** [comment]
Ist in der CCU/RaspberryMatic unter "Einstellungen -> Sicherheit" auch die Authentifizierung abgeschaltet? Wenn ja, dann bitte mehr infos zu der Anwendung liefern die via "init()" sich registrieren will.

**Comment by jens-maus** [comment]
Bitte auch exaktes Beispiel der XMLRPC Verarbeitung hier zeigen und am besten ein testcase mittels XMLRPC aufrufen machen und das nicht nur mit Worten beschreiben sondern Beispiel-code zeigen.

**Comment by Maro25** [comment]
Die Authentifizierung ist deaktiviert. Die Anwendung ist in C# selbst geschrieben. Ich kann, sobald ich Zeit habe, nochmal die XML- Befehle hochladen, die hin und her geschickt werden. 
An der CCU sind aktuell ca. 140 HM- Geräte und 6 HMIP Geräte (4* Hm-SRH und 2* Hm-PSM) angemeldet. Alles funtioniert einwandfrei. Sobald ich den dritten Hm-PSM- Aktor anmelde, kommt nach listDevices keine Nachricht mehr von der CCU. Wenn er abgemeldet wird kommt für alle 6 Geräte die entsprechenden newDevice- Meldungen.

**Comment by jens-maus** [comment]
Hmm. bitte das ganze mal mittels Kommandozeilen XMLRPC nachstellen ausserhalb der eigenen C# Applikation. Wenn es damit auch passiert könnte das ein Bug im HMIPServer XMLRPC sein. 

Bitte auch mal die Antworten nicht mit "Windows-1252" encoding verfassen sondern mit ISO-8859-1 antworten, vielleicht bringt das ja bereits etwas. Und bitte auch mal das hmserver.log Logfile checken und das loglevel des HMIPServer hochschrauben. Ggf. gibt es da ja nützliche Informationen warum das newDevices nicht gesendet wird.

**Comment by Maro25** [comment]
Änderung des Encodings habe ich schon ausprobiert. Gibt leider das gleiche Ergebnis. Die anderen Sachen werde ich wohl erst morgen schaffen.

**Comment by hobbyquaker** [comment]
related: https://github.com/eq-3/occu/issues/83

**Comment by jens-maus** [comment]
Please note that a new issue #843 came up and essentially ended up in having this issue fixed by the vendor. Thus, this issue should also then be fixed with the final integration of a new HmIPServer version by the vendor. Thus, closing this as a duplicate.
