### ISSUE TITLE
WebUI: Missing error message after click on Install additional Software

### ISSUE THREAD

**Issue by sailor79** [jens-maus/RaspberryMatic#49]
(minor but existing fault)
Missing error message after click on "Zusatzsoftware installieren" while no file is selected (user fault hint)

**Comment by jp112sdl** [comment]
I think this issue can be closed because an error message now appears:
<img width="418" alt="Bildschirmfoto 2020-02-04 um 07 13 56" src="https://user-images.githubusercontent.com/18190139/73718835-e92ebf00-471d-11ea-9e04-e4b45b30245d.png">

**Comment by jens-maus** [comment]
Thanks for having tested it again!
