### ISSUE TITLE
Web password is not being used

### ISSUE THREAD

**Issue by ptc** [jens-maus/RaspberryMatic#490]
**Describe the bug**
When going to the raspberrymatic page, I doesn't ask for a password and you're logged in instantly. 

**To Reproduce**
1. Go to 'the ip of your web interface'
2. Click on 'Logout'
3. Type in your ip address again.
4. you're still logged in. 

**Expected behavior**
On new browsers or after being logged out, system should ask for password. 

**Screenshots**

**System information (please complete the following information):**
 - Version [e.g. RaspberryMatic 3.37.8.20180922]
 - Hardware [e.g. RaspberryPi3]

**Additional context**

**Comment by jens-maus** [comment]
This is not a bug, but a Feature. Go to "Settings -> User management -> Log in automatically" and disable the auto-logon feature if you don't want to use it.
