### ISSUE TITLE
Fehler bei Spannungsanzeige Fenster Tür Kontakt Version: 3.41.11.20181124

### ISSUE THREAD

**Issue by Kalliw** [jens-maus/RaspberryMatic#491]
Ich habe festgestellt, dass die Spannungsanzeige bei den Fenster Tür Kontakten nicht 1,5 Volt sondern 3 Volt anzeigt. Ist wohl nicht richtig oder?

**Comment by jens-maus** [comment]
Tschuldigung, beim Eröffnen des Tickets war doch sicherlich eindeutig gestanden das das hier ein bug/issue tracker ist und kein Diskussionsforum. Auch war das ticket mit einem Template gefüllt wo eben auch eine klare warnung stand ds für solche fragen/dinge das HomeMatic-Forum genutzt werden sollte. Insofern bitte dort diskutieren und erst wenn sich da herausstellt das es einen definitiven Fehler gibt der auch definitiv in RaspberryMatic ist und nicht auch in der generellen CCu Firmware dann kann man hier ein ticket aufmachen. Für alles andere ist das HomeMatic-Forum zu Rate zu ziehen.

**Comment by Kalliw** [comment]
Ok hab ich nicht so verstanden. Ich bin davon ausgegangen, dass man hier Fehler melden soll.
Tschuldigung meiner Seitz.
