### ISSUE TITLE
HVL not working 

### ISSUE THREAD

**Issue by hauvol** [jens-maus/RaspberryMatic#492]
HVL auf externem PI:

Nach dem Upgrade will HVL auf einem separaten PI laufend nicht mehr mit dem Raspberrymatic kommunizieren. Der Handshake zwischen beiden funktioniert, allerdings kann HVL keine Werte mehr schreiben. Ich hab verschiedene weitere Tests gemacht - und ja, die Firewall habe ich komplett deaktiviert. Es werden definitiv keine Werte von Sensoren (bei mir Netatmo) mehr aktualisiert. Ich konnte leider nicht wirklich bis in die Tiefen testen, woher das Problem kommt, es ist aber auf jedenfalls auch noch da.

Meldung seitens HVL

"0 aktive Verbindungen (Letze Meldung Mon Nov 26 2018 10:39:14 GMT+0100 (CET))
Es scheint, das die CCU nichts vom Homematic-Virtual-Layer weiss. Wenn Du sicher bist, das die IP richtig ist und die Einstellungen in der InterfacesList.xml der CCU stimmen, dann kann ein CCU Neustart für Abhilfe sorgen."

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
 - Version RaspberryMatic 3.41.11.20181124
 - Hardware RaspberryPi3

**Additional context**

**Comment by jens-maus** [comment]
Bitte den Inhalt der `/etc/config/InterfacesList.xml` Datei zeigen.

**Comment by hauvol** [comment]
moment. starte gerade mein testpi

**Comment by hauvol** [comment]
# cat /etc/config/InterfacesList.xml
<?xml version="1.0" encoding="utf-8" ?> 
<interfaces v="1.0">
	<ipc>
	 	<name>BidCos-RF</name>
	 	<url>xmlrpc_bin://127.0.0.1:32001</url> 
	 	<info>BidCos-RF</info> 
	</ipc>
	<ipc>
	 	<name>VirtualDevices</name>
	 	<url>xmlrpc://127.0.0.1:39292/groups</url> 
	 	<info>Virtual Devices</info> 
	</ipc>
	<ipc>
	 	<name>HmIP-RF</name>
	 	<url>xmlrpc://127.0.0.1:32010</url> 
	 	<info>HmIP-RF</info> 
	</ipc>
	<ipc>
	 	<name>CUxD</name>
	 	<url>xmlrpc_bin://127.0.0.1:8701</url> 
	 	<info>CUxD</info> 
	</ipc>
<ipc><name>HVL</name><url>xmlrpc://172.17.203.15:7000</url><info>HVL</info></ipc></interfaces>
#

**Comment by hauvol** [comment]
`# cat /etc/config/InterfacesList.xml
<?xml version="1.0" encoding="utf-8" ?> 
<interfaces v="1.0">
	<ipc>
	 	<name>BidCos-RF</name>
	 	<url>xmlrpc_bin://127.0.0.1:32001</url> 
	 	<info>BidCos-RF</info> 
	</ipc>
	<ipc>
	 	<name>VirtualDevices</name>
	 	<url>xmlrpc://127.0.0.1:39292/groups</url> 
	 	<info>Virtual Devices</info> 
	</ipc>
	<ipc>
	 	<name>HmIP-RF</name>
	 	<url>xmlrpc://127.0.0.1:32010</url> 
	 	<info>HmIP-RF</info> 
	</ipc>
	<ipc>
	 	<name>CUxD</name>
	 	<url>xmlrpc_bin://127.0.0.1:8701</url> 
	 	<info>CUxD</info> 
	</ipc>
<ipc><name>HVL</name><url>xmlrpc://172.17.203.15:7000</url><info>HVL</info></ipc></interfaces>
# 
`

**Comment by hauvol** [comment]
ich bin zu doof:


[interfaces.pdf](https://github.com/jens-maus/RaspberryMatic/files/2617259/interfaces.pdf)

**Comment by hauvol** [comment]
Moin Jens, ich hab' mir heute morgen noch eine komplette Testumgebung mit neuster Version (Danke) und einem separaten HVL System gebaut. Anbei die LogFiles. Leider funktioniert HVL auch mit der neuesten Version nicht :-(

[3.41.11.20181126_log.txt](https://github.com/jens-maus/RaspberryMatic/files/2618981/3.41.11.20181126_log.txt)
[hvl_log.txt](https://github.com/jens-maus/RaspberryMatic/files/2618984/hvl_log.txt)

**Comment by jens-maus** [comment]
Dann bitte an den Entwickler von HVL wenden. Erstens formt der die einträge in der InterfacesList.xml etwas ungünstig und die sollten exakt so formatiert werden wie die anderen weil es da leider Prozesse gibt die diese einträge zeilenbasiert passt und daher mitunter nicht die URL exakt extrahieren kann. Und zweitens kann nur er wissen was in der Firewall geöffnet gehört das sein HVL weiterhin mit 3.41.x firmware funktioniert.

**Comment by hauvol** [comment]
ok, ich mach ein issue bei thkl auf. Scheinbar lag es tatsächlich an der Firewall. Habe den Port 31999 auf der ccu geöffnet und siehe da, die Netatmo devices werden angelegt.

Danke Jens,
Gruss Volker

**Comment by jens-maus** [comment]
Das deutet dann stark darauf hin das hier der Autor von HVL ggf. einiges Umstellen muss da er wohl die InterfacesList.xml datei ausliest und dann versucht auf diese Ports zuzugreifen die in den URLs stehen. Das sollte man so nicht machen und man sollte auch nicht die internen Ports (3xxxx) in der firewall nach aussen freigeben (müssen). In Zukunft kann es da mitunter dann auch eine weiteres Firmware-Update geben das die internen 3xxxx Ports dann lediglich für das localhost interface zur verfügung stellt und damit wird man die dann gar nicht mehr nach aussen hin freigeben können. Externe Applikationen sollten sich darauf bereits jetzt einstellen.
