### ISSUE TITLE
Kanalaktion von HM-LC-RGBW-WM in einem Programm wird als "Code" angezeigt

### ISSUE THREAD

**Issue by LevelOne2k** [jens-maus/RaspberryMatic#493]
Hallo,

wenn man das Gerät HM-LC-RGBW-WM in einem Programm einbindet und die Kanalaktion auswählt, dann sieht man in dem Fenster der Kanalaktion nur den "Code?".

**Screenshots**
<img width="1397" alt="bildschirmfoto 2018-11-27 um 11 49 07" src="https://user-images.githubusercontent.com/25386824/49077025-a2505a00-f23a-11e8-818a-099871edac93.png">

**System information**
 - Version: RaspberryMatic 3.41.11.20181126
 - Hardware: RaspberryPi3

**Comment by jens-maus** [comment]
Was steht denn da bitte komplett drin in dem Feld? Bitte hier mal posten.

**Comment by LevelOne2k** [comment]
Das weiß ich nicht. Ich habe versucht es zu kopieren, aber keine Chance bisher, dann geht sofort dieses Fenster auf wenn man in das Kästchen klickt.
<img width="600" alt="bildschirmfoto 2018-11-27 um 11 51 22" src="https://user-images.githubusercontent.com/25386824/49077081-c90e9080-f23a-11e8-94c1-941da5a07172.png">

**Comment by jens-maus** [comment]
Dann bitte mittels Webbrowser den Seitenquelltext durchsuchen und die Passage im Quelltext finden und hier posten.

**Comment by LevelOne2k** [comment]
`{'ACT_HSV_COLOR_VALUE_STORE':0,'ACT_BRIGHTNESS_STORE':200,'RAMP_TIME_STORE':0.5,'ON_TIME_STORE':0}`

**Comment by jens-maus** [comment]
Danke. Abgesehen von diesem rein kosmetischen Problem gibt es aber de facto kein praktisches Problem dann in den Einstellungen wenn man das so nutzt, oder?

**Comment by LevelOne2k** [comment]
Nein, es sieht nur doof aus :)

**Comment by jens-maus** [comment]
Danke. Mal sehen ob das jemand anderes mit einem HM-LC-RGBW-WM auch noch verifizieren kann.

**Comment by AdlerCentauri** [comment]
Bei mir ist es auch so
<img width="637" alt="bildschirmfoto 2018-11-27 um 12 21 37" src="https://user-images.githubusercontent.com/37038767/49078709-0412c300-f23f-11e8-9e8e-e64fa9ed23b1.png">

**Comment by TheRealTremes** [comment]
Same here
<img width="1440" alt="bildschirmfoto 2018-11-27 um 12 41 40" src="https://user-images.githubusercontent.com/19434912/49079773-d8450c80-f241-11e8-9b66-bb9a128c78a7.png">

**Comment by Fiiti** [comment]
> 
> 
> Danke. Mal sehen ob das jemand anderes mit einem HM-LC-RGBW-WM auch noch verifizieren kann.

Kann ich. Exakt das Gleiche auch bei mir.:
![2018-11-28 12_40_01-window](https://user-images.githubusercontent.com/25975978/49149607-ced3a700-f30a-11e8-9b62-4919c6847bd0.png)

**Comment by TheRealTremes** [comment]
Hallo, sollte das nicht mit der aktuellen CCU3 Firmware 3.43.15 behoben sein? Oder wie verstehe ich dies hier:
"Das Konfigurationsfenster des RGBW-Controller in Programmen wiederhergestellt."

**Comment by jens-maus** [comment]
Ist das Problem inzwischen in der aktuellen RaspberryMatic / CCU3 Firmware behoben?

**Comment by LevelOne2k** [comment]
Das Problem besteht immer noch
<img width="914" alt="Bildschirmfoto 2019-10-16 um 15 42 46" src="https://user-images.githubusercontent.com/25386824/66924851-a68c8e00-f02b-11e9-9e05-e8f1d9ce22ae.png">

**Comment by jens-maus** [comment]
Danke für die Info. Allerdings wäre natürlich ne legitime Frage was statt des `{ ... }` Textes dort angezeigt werden sollte? Ich denke das ist auch der Grund wieso eQ3 hier nichts anderes implementiert hat bis jetzt.

**Comment by jens-maus** [comment]
Hast du davon ein Beispiel parat wie es vorher aussah und wie es jetzt dargestellt wird?

**Comment by LevelOne2k** [comment]
Nein das ist schon zu lange her. Weiß auch nicht mehr welche Version das war.

**Comment by jens-maus** [comment]
This issue has been marked obsolete because time has passed and the content/topic of the issue seem to be not relevant anymore or does not match the current state-of-affairs. Thus, the issue had been closed. If you feel it is still relevant, please update the ticket accordingly with newer information and explain why you feel it is still relevant and should still be taken care of.
