### ISSUE TITLE
Einstellungsansicht bei Geräten scrollt automatisch runter

### ISSUE THREAD

**Issue by LevelOne2k** [jens-maus/RaspberryMatic#494]
**Describe the bug**
Das Problem tritt meiner Beobachtung nach nur bei HmIP Geräten auf, jedoch nicht bei allen.

**To Reproduce**
1. Go to 'Einstellungen > Geräte'
2. Click on 'Interface/Kategorie > HmIP-RF > Setzen > Bei einem (HmIP) Gerät auf Einstellen'
3. Scroll down to 'X'
4. See error > Die Seite scrollt automatisch ein wenig nach unten.

Safari Version 12.0.2 & macOS 10.14

**Screenshots**
![bildschirmaufnahme-2018-11-27-um-12 04](https://user-images.githubusercontent.com/25386824/49078608-c746cc00-f23e-11e8-8a91-034a5f75ec4d.gif)

**System information**
 - Version: RaspberryMatic 3.41.11.20181126
 - Hardware: RaspberryPi3

**Comment by TheRealTremes** [comment]
Same here

**Comment by jens-maus** [comment]
Does this also happen with Firefox or Chrome?

**Comment by AdlerCentauri** [comment]
Bei mir scrollt die Seite auch von alleine runter. Nutze auch Safari, habe es aber gerade mit FF getestet und dort ist es auch so.

**Comment by TheRealTremes** [comment]
Also with Firefox

**Comment by jens-maus** [comment]
Hmmm, komisch. Ich bekomm das hier auf meinen Systemen nicht reproduziert.

**Comment by LevelOne2k** [comment]
Bei mir ist es auch so mit FireFox und Chrome.

Mit welchem HmIP Gerät hast du das getestet? Dann schaue ich mal ob das bei dem Gerät (wenn ich es habe) auch passiert oder eben nicht. Es ist wie gesagt bei mir komischerweise nicht bei jedem Gerät so.

**Comment by jens-maus** [comment]
Dann bitte mal ein Gerät benennen bei dem es passiert. Bei dem oben im Video dargestellten Gerät kann ich das nicht nachvollziehen weil ich das nicht habe.

**Comment by LevelOne2k** [comment]
Wie ich gerade bemerkte, passiert das tatsächlich nur bei dem HmIP-SPDR Gerät.

**Comment by AdlerCentauri** [comment]
Bei mir nur bei den Geräten HmIP-SPI und HmIP-SPDR.

**Comment by jens-maus** [comment]
Ich hab zwar HmIP-SPI, aber da passiert es nicht. Kann es also nicht nachvollziehe, leider.

**Comment by TheRealTremes** [comment]
Only at HmIP-SPDR

**Comment by jens-maus** [comment]
Ich kann das hier geschilderte Verhalten weiterhin nicht nachvollziehen oder selbst bestätigen. Bitte melden bei wem es alles noch mit der aktuellen RaspberryMatic passiert.
