### ISSUE TITLE
Support of HmIP-Mod-TM

### ISSUE THREAD

**Issue by tts0815** [jens-maus/RaspberryMatic#495]
Hallo,

wollte meinen Garagentorantrieb White800 aus dem ELV-Set in Betrieb nehmen,
Leider bekomme ich den Antrieb nicht mit Raspberrymatic v3.41.11.2018.1124 in betrieb.
Ich verwende RPi als CCU2 oder auch CCU3 Charly.

Hilfe, wie komme ich hier weiter ?!?

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!
