### ISSUE TITLE
Zusatzsoftware keine Installation/Update möglich

### ISSUE THREAD

**Issue by hhochmuth** [jens-maus/RaspberryMatic#497]
Hallo, seit dem letztem Firmware Update ist mir aufgefallen, dass sich keine Updates (Zusatzsoftware) installieren und/oder aktualisieren lassen. Beim Click auf "herrunterladen" erscheint nur der HTML-Zeile im browserfenster (chrom). Nach manuellem Download und Start des Updates erscheint die FM:
Error (104)    Ein unerwarteter Fehler ist während der Addon-Installation aufgetreten. Bei der hochgeladenen Datei handelt es sich entweder nicht um ein Addon-Archiv, ist defekt oder ist für eine andere Hardware vorgesehen. Bitte versuchen Sie es erneut oder kontaktieren Sie den Autor des Addons.

Ich habe die Installation verschiedener Addons von verschiedenen Geräten aus versucht, Ergebnis gleich.

**Comment by jens-maus** [comment]
Tut mir leid, aber ich kann das Problem nicht reproduzieren. Auf einer frischen RaspberryMatic 3.41.11.20181126 lassen sich problemlos allerlei Addons installieren und es kommt zu keinerlei Fehlermeldung. Kann das jemand anders noch reproduzieren?

**Comment by libertyx82** [comment]
Jap tritt bei mir auch auf, allerdings nicht bei jedem Addon, tritt u.A bei CUxD, CCU-Historian und auch nur in Chrome auf.
![screencapture_244526906_2879750865_0](https://user-images.githubusercontent.com/22996350/49137816-d2a50080-f2ed-11e8-88b8-15c767475854.jpg)

**Comment by jens-maus** [comment]
@libertyx82 Bitte Ticket exakt durchlesen. Der Ersteller sagt man kann gar kein Aden mehr aktualisieren. D.h. nicht nur den "Herunterladen" knopf drücken und erwartend as man dann auf die download Seite kommt.

**Comment by jens-maus** [comment]
Und das bei CUxD, CCU-Historian diese HTML Seite nun kommt liegt einfach daran, das die Addons da noch einen Bug haben den die Autoren beseitigen müssten. Dieser Bug schränkt allerdings nur die Funktionalität ein das der "Herunterladen" Knopf direkt funktioniert. Das manuelle herunterladen des Raddons und installieren sollte trotzdem gehen. Der Autor dieses Tickets sagt jedoch, nein. Was ich allerdings nicht bestätigen konnte. Addons kann man prinzipiell ohne Probleme installieren (wenn man das Addon tar.gz selbst runterlädt).

**Comment by libertyx82** [comment]
> Hallo, seit dem letztem Firmware Update ist mir aufgefallen, dass sich keine Updates (Zusatzsoftware) installieren und/oder aktualisieren lassen. Beim Click auf "herrunterladen" erscheint nur der HTML-Zeile im browserfenster (chrom). 

Meine Aussage bezog sich auf diesen Teil.

Die Installation des CCU-Historian funktionierte gestern ohne Probleme.

**Comment by jens-maus** [comment]
Da sich Addons prinzipiell installieren lassen und das HTML Anzeigeproblem an den jeweiligen Addons liegen kann dieses Ticket geschlossen werden.

**Comment by hhochmuth** [comment]
Hallo, ich habe gerade ein Downgrade auf die Version 3.37.8.20181026 durchgeführt. Gleiches Problem, liegt also nicht an der neuen Version. Noch eine Idee wie ich das Neuimagen umgehen kann?
-------- Ursprüngliche Nachricht --------Von: Jens Maus <notifications@github.com> Datum: 28.11.18  14:53  (GMT+01:00) An: jens-maus/RaspberryMatic <RaspberryMatic@noreply.github.com> Cc: hhochmuth <h.hochmuth@web.de>, Author <author@noreply.github.com> Betreff: Re: [jens-maus/RaspberryMatic] Zusatzsoftware keine Installation/Update möglich (#497) 
Da sich Addons prinzipiell installieren lassen und das HTML Anzeigeproblem an den jeweiligen Addons liegen kann dieses Ticket geschlossen werden.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jens-maus/RaspberryMatic","title":"jens-maus/RaspberryMatic","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jens-maus/RaspberryMatic"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jens-maus in #497: Da sich Addons prinzipiell installieren lassen und das HTML Anzeigeproblem an den jeweiligen Addons liegen kann dieses Ticket geschlossen werden."}],"action":{"name":"View Issue","url":"https://github.com/jens-maus/RaspberryMatic/issues/497#issuecomment-442454020"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jens-maus/RaspberryMatic/issues/497#issuecomment-442454020",
"url": "https://github.com/jens-maus/RaspberryMatic/issues/497#issuecomment-442454020",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [jens-maus/RaspberryMatic] Zusatzsoftware keine Installation/Update möglich (#497)",
"sections": [
{
"text": "",
"activityTitle": "**Jens Maus**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@jens-maus",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"jens-maus/RaspberryMatic\",\n\"issueId\": 497,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/jens-maus/RaspberryMatic/issues/497#issuecomment-442454020"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 417051278\n}"
}
],
"themeColor": "26292E"
}
]
