### ISSUE TITLE
Funktioniert nicht mehr mit Homebridge seit V 24.11.

### ISSUE THREAD

**Issue by pekae** [jens-maus/RaspberryMatic#498]
Homebridge erkennt Geräte, kann diese aber nicht mehr steuern seit der Version vom 24.11. . Geräte und Szenen werden angezeigt und anscheinend auch ausgeführt, die Homematic Geräte werden aber nicht geschaltet. Zb Licht An, zeigt in Homebridge AN, Licht aus, schaltet in Homebridge auch wieder AUS, in Homematic kommen aber keine Befehle an, die Geräte reagieren nicht. Downgrade Auf V24.10 - alles wieder ok

**Comment by libertyx82** [comment]
Siehe
https://github.com/thkl/homebridge-homematic/issues/354

**Comment by jens-maus** [comment]
Dies ist kein Problem in RaspberryMatic sondern eine notwendige Anpassung die Homebridge selbst umsetzen muss.
