### ISSUE TITLE
The progress of the device software update and the final message

### ISSUE THREAD

**Issue by Erbit** [jens-maus/RaspberryMatic#499]
Hi.
Ideas:
- I would like to see progress in the marked place.
- message in "service messages" about the completion of the firmware update

![homematic_webui_-_2018-11-29_11 48 09](https://user-images.githubusercontent.com/35191543/49217715-9bf2e700-f3ce-11e8-921f-28676ad49548.png)

**Comment by jens-maus** [comment]
This is something eQ3 would have to implement themselves and is not something we as a community could do ourself IMHO.

**Comment by Erbit** [comment]
OK
Thank you
