### ISSUE TITLE
CUxD devices no longer working after upgrade from beta3 to beta4

### ISSUE THREAD

**Issue by jewesta** [jens-maus/RaspberryMatic#50]
I ran RaspberryMatic beta3 on an rbpi2 and updated to beta4 by following the "official" process. I had the following plugins installed on beta3 during the backup process:
hm_pdetect, CUxD, XML-API
Restoring the backup under beta4 went flawlessly with one exception: My CUxD devices were still there but stopped working. I had two of those installed: One System-->Exec with id CUX2801001 (which I will just call exec) and one System-->Timer with id CUX2800001 (which I will just call timer).

The exec produced the following error log (CUxD console):
```
[1] homematic-raspi daemon.warn cuxd[599]: setValue 'CUX2801001:1.CMD_EXEC=tclsh /usr/local/setparam_virtdev.tcl INT0000004 WEEK_PROGRAM_POINTER int 1' not found!
[2] homematic-raspi daemon.info cuxd[599]: delete CUX2801001
[3] homematic-raspi daemon.info cuxd[599]: create CUX2801001 '' dtype=28&dtype2=1&dserial=1&dname=&dbase=10022&dcontrol=0'
```

What the script attempted to do (first log entry) was to set the data point WEEK_PROGRAM_POINTER of a virtual device (heating group) to 1. I suspect the actual command does not matter and any call to the exec would have failed ("not found"). As shown in the logs I then deleted the exec and created it again. The script has since been run several times and is working again.

The timer stopped working as well. It had lost all channel configuration (I actively use two timer channels). After having configured it again it still would not trigger the related programmes. So as with the Exec I removed and recreated the timer which corrected the issue.

The problem is that by removing CUxD devices they have to be added to all HM programmes again.

**Comment by jens-maus** [comment]
Please provide the `/usr/local/setparam_virtdev.tcl` program for better debugging this issue. Also potentially provide the file `/usr/local/addons/cuxd/cuxd.ps` file (but please make sure it doesn't contain any secret information) so that I can check what the problem might be all about.

**Comment by jens-maus** [comment]
Please also note that I did the same switch like you did several times and I never had the situation that my Exec CUxD devices stopped working.

**Comment by jewesta** [comment]
Thanks for pretty printing the log entries. I did not know how to do that. :-)

I attached the files. They should not contain secret information. I did not tinker with those files manually ever before. Just so you know. They should have always been in "factory" state or have been manipulated only by the system.

Note that I made the switch to RaspberryMatic in February of 2016. So beta2 was probably my first beta and I upgraded to every beta since then (skipped the alpha). I also did not have this problem before and iirc at least the exec device was carried over from the CCU2.

Also note that I still have the beta3 backup. Since the process is relatively straight forward - use ApplePi baker to write the image and restore the backup - I might be able to reproduce it. I will order an additional SD-Card today which I wanted to do anyway for backup purposes. So I might be able to recreate the inconsistent state if that helps.

[rpbimatic_issue_#50_tcl_ps.zip](https://github.com/jens-maus/RaspberryMatic/files/713952/rpbimatic_issue_.50_tcl_ps.zip)

**Comment by HMside** [comment]
I think i had the same issue after migrate from CCU2 with an older CUxD Version as on the RaspberryMatic was installed. In my case i manually copied the cuxd.ps, cuxd.ps.bak and cuxd.ps.old and changed the second line of this files to the CUxD Version of the Pi. The line looks like this: `1.8a 0` After a reboot the old config are back and working fine.

**Comment by jens-maus** [comment]
I am sorry, but I couldn't reproduce the problem at all. Until someone else can provide more evidence that there is something wrong, I will close that ticket.
