### ISSUE TITLE
Homematic IP Komponenten lassen sich nicht löschen

### ISSUE THREAD

**Issue by KnutSchweinfurth** [jens-maus/RaspberryMatic#501]
Angelernte Homematic IP Komponenten lassen sich nicht mehr in der WebUI löschen.
RaspberryMatic stürzt nach längerem Scannen der driekten verknüpfungen ab.

**Comment by jens-maus** [comment]
Es tut mir leid, das ist kein generelles Problem denn bei anderen funktioniert das und hier auch bei sämtlichen Testinstallationen. Daher bitte an HomeMatic Forum wenden für persönliche Fehlersuche.
