### ISSUE TITLE
Fehler bei direkten Homematic IP Verknüfungen

### ISSUE THREAD

**Issue by KnutSchweinfurth** [jens-maus/RaspberryMatic#502]
**Describe the bug**
Ich habe zwie HM-IP Komponenten direkt miteinander verknüpft.
zB Fernbedienung IP mit Schalt-Steckdose IP
Die verknüpfung dauert ewig lange und danch wird eine Verknüpfung angelegt, bei der es nur noch einen "Bearbeiten" Button gibt, der aber auch nicht funktioniert. Löschen gibt es gar nicht mehr.

**Expected behavior**
Verhalten wie bei den normalen Komponenten erwünscht

**System information (please complete the following information):**
 - Version [e.g. RaspberryMatic 3.37.8.20180922]
    neueste Version (3.41.11.20181126)
 - Hardware [e.g. RaspberryPi3, TinkerboardS, etc.]
    Rasp PI3

**Comment by jens-maus** [comment]
Auch dies ist kein generelles Bug/Problem von RaspberryMatic denn es geht vielfach. Dies hier ist kein Support Forum wo man persönliche Hilfe sucht, sondern lediglich von meheren Nutzern gefundene und bereits analysierte  Bugs melden kann. Für Hilfe bitte an HomeMatic Forum wenden.
