### ISSUE TITLE
Alexa local Node läuft nicht mehr nach Update

### ISSUE THREAD

**Issue by unixweb** [jens-maus/RaspberryMatic#504]
Hallo 

seit Update 3.41.11.20181126 hab ich das Problem, dass Amazon Echo (1) keine Geräte mehr findet. Mit 3.41.11.20181124 geht es noch. 

Ich nutze keine Skills von Amazon Echo sondern node-red-contrib-alexa-local in Node-Red

- Version 3.41.11.20181126
- Raspberry Pi 3B+ 
- RedMatic 1.9.11
- node-red-contrib-alexa-local 0.3.24

Grüße , Joachim

**Comment by jens-maus** [comment]
Das hört sich nach einem klaren firewall Problem auf RaspberryMatic an. Abschalten bzw auf Relaxed stellen und die Authentifizierung abschalten. Und bitte an das HomeMatic-Forum wenden. Das hier ist kein support Forum wie übrigens immTicket Template stand.

**Comment by unixweb** [comment]
ich habe hier 8 Stunden mit der Fehlersuche verbracht und den Fehler nachzustellen. Du machst innerhalb 5 Minuten den Issue zu ohne einmal sich die Mühe zu machen den Fehler nachzugehen. Aber ok , es war mir eine Lehre in Zukunft nicht jeden Update mehr von Dir zu installieren. Soviel zur Wertschätzung von anderen Menschen die bei Dir nach >/dev/null geht.
