### ISSUE TITLE
Das WEBUI zeigt Fehlfunktionen beim HMIP-BSL beim Programmieren.

### ISSUE THREAD

**Issue by ThomasLoeffel** [jens-maus/RaspberryMatic#506]
**System:**
Asus Tinker+ mit der Firmware: 3.41.11.20181126

Hallo Jens,
bei dem Einsatz eines HMIP-BSL sind mir diese Fehler aufgefallen.

Punkt 1: z.B. Kanal 8, LED „blau“ wird immer vorgewählt egal was man auswählt.
Wenn ich im WEBUI ein Programm erzeugen möchte passiert folgender Fehler bei der ersten Auswahl. 
-	Geräteauswahl -> HMIP-BSL und dann der Kanal 8 (Dimmer für LED).
-	Farbauswahl (aus, blau, ……), ich wähle dann z.B. rot, oder grün, ist egal….
-	Mit ok beenden.
Wenn ich dann erneut in das Programm gehe ist aber die Farbe „blau“ ausgewählt. Wenn ich dann erneut die Farbe wechsele bleibt dann meine gewollte Auswahl.

Punkt2: z.B. Kanal 8, Einheit Rampenzeit: 10 mS hat keinen Effekt
Wenn ich im WEBUI ein Programm erzeugen möchte passiert folgender Effekt. 
-	Geräteauswahl -> HMIP-BSL und dann der Kanal 8: Farbe (z.B. rot).
-	Geräteauswahl -> HMIP-BSL und dann der Kanal 8: Einheit Zeitdauer: Sekunden.
-	Geräteauswahl -> HMIP-BSL und dann der Kanal 8: Wert Zeitdauer = 1
-	Geräteauswahl -> HMIP-BSL und dann der Kanal 8: Einheit Rampenzeit: 10 mS
-	Geräteauswahl -> HMIP-BSL und dann der Kanal 8 Wert Rampenzeit = 500
-	Geräteauswahl -> HMIP-BSL und dann der Kanal 8 Dimmwert = 100%
-	Mit ok beenden.

Effekt LED geht ohne wirklichen Rampenlauf an. Wobei der Wert von mir auf folgende Werte gesetzt wurde: 1, 50, 100, 500, 800, 1500, 5000, 10000. Benutze ich Einheit Rampenzeit: Sekunden klappt alles wie erwartet. In der direkten Verknüpfung kann ich auch Einheit Rampenzeit mS auswählen und da klappt es auch mit der Rampe.

Gruß Thomas

**Comment by ThomasLoeffel** [comment]
**System:**
Asus Tinker+ mit der Firmware: 3.41.11.20181126

Hallo Jens,
bei dem Einsatz eines HMIP-BSL sind mir diese Fehler aufgefallen.

Punkt 1: z.B. Kanal 8, LED „blau“ wird immer vorgewählt egal was man auswählt.
Wenn ich im WEBUI ein Programm erzeugen möchte passiert folgender Fehler bei der ersten Auswahl. 
-	Geräteauswahl -> HMIP-BSL und dann der Kanal 8 (Dimmer für LED).
-	Farbauswahl (aus, blau, ……), ich wähle dann z.B. rot, oder grün, ist egal….
-	Mit ok beenden.
Wenn ich dann erneut in das Programm gehe ist aber die Farbe „blau“ ausgewählt. Wenn ich dann erneut die Farbe wechsele bleibt dann meine gewollte Auswahl.

Punkt2: z.B. Kanal 8, Einheit Rampenzeit: 10 mS hat keinen Effekt
Wenn ich im WEBUI ein Programm erzeugen möchte passiert folgender Effekt. 
-	Geräteauswahl -> HMIP-BSL und dann der Kanal 8: Farbe (z.B. rot).
-	Geräteauswahl -> HMIP-BSL und dann der Kanal 8: Einheit Zeitdauer: Sekunden.
-	Geräteauswahl -> HMIP-BSL und dann der Kanal 8: Wert Zeitdauer = 1
-	Geräteauswahl -> HMIP-BSL und dann der Kanal 8: Einheit Rampenzeit: 10 mS
-	Geräteauswahl -> HMIP-BSL und dann der Kanal 8 Wert Rampenzeit = 500
-	Geräteauswahl -> HMIP-BSL und dann der Kanal 8 Dimmwert = 100%
-	Mit ok beenden.

Effekt LED geht ohne wirklichen Rampenlauf an. Wobei der Wert von mir auf folgende Werte gesetzt wurde: 1, 50, 100, 500, 800, 1500, 5000, 10000. Benutze ich Einheit Rampenzeit: Sekunden klappt alles wie erwartet. In der direkten Verknüpfung kann ich auch Einheit Rampenzeit mS auswählen und da klappt es auch mit der Rampe.

Gruß Thomas

**Comment by ThomasLoeffel** [comment]
Ich habe auf meiner CCU2 dieses gestestet. Leider zeigt sich das gleiche Bild. Bei der ertsen Verwendung wird immer auf "LED: blau" angewendet egal was man vorher einstellt. Werde ein Ticket an eq3 schreiben.

**Comment by zwetkow** [comment]
ich habe festgestellt, dass in der neuen Raspberrymatic Software (3.41.11.20181126) sich die 1. Dimmaktor Kanäle der BSL nicht mit einem Programm ansprechen lassen. In der Geräteliste werden diese korrekt angezeigt.
Testweise bin ich zurück auf 3.37.8.20181026. Hier funktioniert es korrekt.
Jemand eine Idee ?
Dankeschön

**Comment by jens-maus** [comment]
Ist das Problem mit aktueller RaspberryMatic Version noch existent?

**Comment by ThomasLoeffel** [comment]
Hallo Jens,

mit spätestens der Version: 3.55.5.20201226

sind beide Fehler behoben.

Gruß und Danke Thomas
