### ISSUE TITLE
HM-LC-AO-SM  Datapoint RAMP_TIME missing/not working since 3.41.11

### ISSUE THREAD

**Issue by Kroki0815** [jens-maus/RaspberryMatic#508]
Hi,

since 3.41.11 it is not possible to set on HM-LC-AO-SM the datapoint RAMP_TIME.
The device always uses the default of 0.5 seconds. That is very bad for dimmimg scenarios.
Also in the rule configuration the action selection for this datapoint is missing.

Kind regards
Thorsten

**Comment by Kroki0815** [comment]
I checked it now via xmlapi:

Before: 
datapoint name="BidCos-RF.OEQ0662919:1.RAMP_TIME" type="RAMP_TIME" ise_id="6432" value="" valuetype="4" valueunit="s" timestamp="0"

Set:
changed id="6432" new_value="3600"

After:
datapoint name="BidCos-RF.OEQ0662919:1.RAMP_TIME" type="RAMP_TIME" ise_id="6432" value="" valuetype="4" valueunit="s" timestamp="0"


Nothing changed !

Same procedure with LEVEL works like expected.

**Comment by jens-maus** [comment]
Please check if the same happens with a CCU3 with the same firmware version. If yes, then this is a bug in the CCU firmware itself where eQ3 is in charge.

**Comment by Kroki0815** [comment]
Hi,
sorry for my late response.
Now with last version (3.41.11.20181222) the problem is solved.

Best Thorsten
