### ISSUE TITLE
HMIP-PSM firmware upgrade does not work.

### ISSUE THREAD

**Issue by Erbit** [jens-maus/RaspberryMatic#509]
RapsberryPi3 B+ and RPI-RF-MOD
RaspberryMatic 3.41.11.20181126
 HMIP-PSM original firmware 2.2.2

After the teach-in, a message about the software update appeared. Duty cycle peptide remained unchanged for 3 days. I have transferred HMIP-PSM to CCU2. The software has been updated after 8 hours.

In the previous version of RaspberryMatic, the firmware upgrade of another HMIP-PSM ran smoothly. Duty cycle increased to a high level right after the teach-in and remained high until the end of the update.

**Comment by jens-maus** [comment]
Which "previous version" are you referring to where the update seem to work?

**Comment by Erbit** [comment]
With RaspberryMatic 3.37.8.20181026 the HMIP-PSM update was correct. 

Today I am updating HM-CC-RT-DN and HM-TC-IT-WM-W-EU with RaspberryMatic 3.41.11.20181126. The update for these devices is correct.
