### ISSUE TITLE
Homematic standard time control only triggers a few intervals and then stops

### ISSUE THREAD

**Issue by jewesta** [jens-maus/RaspberryMatic#51]
Before the move to RaspberryMatic I used a CCU2. I used the built in time control module in two programmes to trigger programme execution on a regular basis. The first programme calculated azimuth and elevation of the sun once per minute. The second programme set all heating groups to "auto" mode and "button lock" every night at 3am. This had worked flawlessly since I had bought CCU2 and just until the move to RaspberryMatic.

After the move to a rbpi2 the built in time control was broken. Upon saving a programme that was set to be triggered e.g. every 15 seconds the programme would be executed for approx. 3 intervals and then the timer would just stop. Loading and saving the programme again would re-trigger the cyclical execution, but again only for approx. 3 cycles.

As a result of this the time module (for me) is no longer usable under RaspberryMatic and I had to move to the (much more cumbersome) CUxD timer.

**Comment by jewesta** [comment]
I should add that the rbpi2 has access to an NTP time server but does not feature an RTC.

**Comment by jens-maus** [comment]
This is no specific issue in RaspberryMatic, but well-known (even to eQ3) to be a flaw even in a CCU2. The point that you didn't suffer from this problem in your CCU2 might be just pure of luck. But at the time I had my CCU2 still running I also suffered from the problem quite badly and changed all programs to use a CUxD timer instead. This also doesn't have anything todo with not having a RTC clock in your RaspberryPi. It is simple a bug/flaw in ReGaHss in the CCU platform software.

**Comment by jewesta** [comment]
Thank you very much for your answer. I suspected as much. But since I did not find any references to this issue in direct relation to RaspberryMatic I thought I should file a bug. Especially since it was my observation that it worked on CCU2 and didn't on RaspberryMatic. I had heard of this issue but didn't know it was so fundamental. I guess - as you just said - that I was just being lucky when I still used CCU2. I must say that as much as I like Homematic this is a bit embarassing. After all, timers are an integral part of home *auto*mation. Anyway, thanks for clarifying. -- Jens

**Comment by jens-maus** [comment]
I know that this issue is really frustrating and therefore I will keep this bug report open as long as it exists (eQ3 knows about it). Please also note, however, that the problem only exists for short timers of several seconds/minutes. Daily timers at a specific time (e.g. always at 0:00) seem to work fine - at least that's my observation.

**Comment by jens-maus** [comment]
See here for more info/debug information on this issue:
https://homematic-forum.de/forum/viewtopic.php?f=26&t=32341#p302889

**Comment by jens-maus** [comment]
This should be fixed with latest commit (see b8696e7c6c56e79fab207f3712b177805cc1d429) using a recent beta version of ReGaHss.
