### ISSUE TITLE
Moving Popup Windows inconsistent

### ISSUE THREAD

**Issue by dehsgr** [jens-maus/RaspberryMatic#510]
**Describe the bug**
Moving the Firewall Popup Window does work only on the Title Bar. All other Windows can be moved from the Title Bar **and** from dragging other Window Locations. This is cosmetical but an Issue on Systems with smaller Browser Window Sizes as sometimes user won't get Window moved to correct Position to reach Buttons such as OK and Cancel.

**To Reproduce**
1. Open Settings > Firewall Configuration
2. Click on the Title Bar and drag the Window -> Working as expected
3. Click on another Location of the Window (such as a descriptive Text) and try do drag the Window -> doen't work

**Expected behavior**
The Window shouldn't be draggable only from the Window Title.

**Screenshots**
n/a

**System information (please complete the following information):**
 - RaspberryMatic 3.41.11.20181126
 - Raspberry Pi 3b (without +)

**Additional context**
Issue might be caused by using different techniques/CSS. Normal Popups are using CSS classes "ui-draggable ui-draggable-handle" and Firewall Popup is using CSS class "UIFrame" .

**Comment by jens-maus** [comment]
Since recent versions all popup windows should now having scrollbars, thus should be better usable. Thus this issue can be closed.
