### ISSUE TITLE
Verbindungsprobleme mit Bluetooth Low Energy devices

### ISSUE THREAD

**Issue by DorfNKB** [jens-maus/RaspberryMatic#511]
Hallo Jens,

klasse Projekt hast du hier!

Mir ist ein Fehler aufgefallen, den ich nicht lösen konnte.
Der Versuch mit Hilfe von hcitool zu einem Bluetooth Low Energy device zu verbinden schlägt fehl. Ddie Verbindung wird direkt wieder getrennt.

**Getestet habe ich mit den Versionen:**
RaspberryMatic

 3.41.11.20181126
RaspberryMatic 2.31.25.20180526
sowohl für den RPI1 und den RPI3 mit einem externen BT dongle.

Als funktionierende Version habe ich ein aktuelles Raspbian genutzt. Hier funktioniert der Verbindungsaufbau ohne Probleme.
 
Vorgehen zum nachstellen:

```
rfkill unblock hic0
hicconfig hci0 up
hictool lecc 00:1A:22:0B:4D:A1
```

Ich habe mal zwei ausgaben von hicdump angehängt. Den Unterschied sieht man am besten mit nem diff tool,

[Raspbian.txt](https://github.com/jens-maus/RaspberryMatic/files/2650389/Raspbian.txt)
[RaspberryMatic.txt](https://github.com/jens-maus/RaspberryMatic/files/2650390/RaspberryMatic.txt)

Vielen Dank für deine Arbeit!

Viele Grüße
Jens

**Comment by DorfNKB** [comment]
Hallo Zusammen,

es sieht so aus, als ob der Slave einen"Rcvd Connection Parameter Update Request" sendet und der Master (RaspberryMatic) diesen ablehnt und daraufhin die Verbindung trennt. 

Leider verstehe ich nicht warum der Master das Verbindungsupdate ablehnt. Sind die vorgeschlagenen Zeiten außerhalb der config des Masters? Wenn ja, wo kann man die einstellen?

Vielleicht

 hat ja jemand ne Idee wo ich weiter suche kann.[raspberryMatic.log](https://github.com/jens-maus/RaspberryMatic/files/2660488/raspberryMatic.log)

Viele Grüße
Jens

**Comment by jens-maus** [comment]
Existiert das problem noch mit aktuellen RaspberryMatic Versionen? Bitte auch mal versuchen das BT dongle via USB verlängerungskabel vom Rpi wegzubringen um intereferenzen auszuschliessen.

**Comment by DorfNKB** [comment]
Hab's erneut mit der neusten Version getestet. Leider das gleiche Ergebnis.

Dongle ist direkt im PI eingesteckt. Gleicher Aufbau mit Raspbian und RaspberryMatic.

\# hcidump
HCI sniffer - Bluetooth packet analyzer ver 5.50
device: hci0 snap_len: 1500 filter: 0xffffffff
\< HCI Command: LE Create Connection (0x08|0x000d) plen 25
    bdaddr 00:1A:22:0B:4D:A1 type 0
    interval 4 window 4 initiator_filter 0
    own_bdaddr_type 0 min_interval 15 max_interval 15
    latency 0 supervision_to 3200 min_ce 1 max_ce 1
\> HCI Event: Command Status (0x0f) plen 4
    LE Create Connection (0x08|0x000d) status 0x00 ncmd 1
\> HCI Event: LE Meta Event (0x3e) plen 19
    LE Connection Complete
      status 0x00 handle 72, role master
      bdaddr 00:1A:22:0B:4D:A1 (Public)
\< HCI Command: LE Read Remote Used Features (0x08|0x0016) plen 2
\> HCI Event: Command Status (0x0f) plen 4
    LE Read Remote Used Features (0x08|0x0016) status 0x00 ncmd 1
\> HCI Event: LE Meta Event (0x3e) plen 12
    LE Read Remote Used Features Complete
      status 0x00 handle 72
      Features: 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00
\> ACL data: handle 72 flags 0x02 dlen 16
    L2CAP(d): cid 0x0005 len 12 [psm 0]
\< ACL data: handle 72 flags 0x00 dlen 10
    L2CAP(d): cid 0x0005 len 6 [psm 0]
\> HCI Event: Number of Completed Packets (0x13) plen 5
    handle 72 packets 1
\< HCI Command: Disconnect (0x01|0x0006) plen 3
    handle 72 reason 0x13
    Reason: Remote User Terminated Connection
\> HCI Event: Command Status (0x0f) plen 4
    Disconnect (0x01|0x0006) status 0x00 ncmd 1
\> HCI Event: Disconn Complete (0x05) plen 4
    status 0x00 handle 72 reason 0x16
    Reason: Connection Terminated by Local Host
>

**Comment by jens-maus** [comment]
Und wie sieht es aus wenn das dongle vom Pi mit einem USB Verlängerungskabel abgesetzt wird?

**Comment by jens-maus** [comment]
This ticket has been closed because of inactivity of the ticket owner and due to the fact that no developer could reproduce the issue. Please reopen the ticket once it can be reproduced again or the ticket owner can reply accordingly.
