### ISSUE TITLE
Keine Verbindung HM<->ioBroker mit Auth

### ISSUE THREAD

**Issue by vr6syncro** [jens-maus/RaspberryMatic#513]
Moin,
habe leider noch keinen Verursacher  für das Problem finden können.
Vielleicht auch einfach nur eine Fehleinstellung.

Vielleicht kann mal einer drüber schauen.

https://github.com/ioBroker/ioBroker.hm-rpc/issues/120

https://forum.iobroker.net/viewtopic.php?f=20&t=18429&p=200960#p200960

**Comment by libertyx82** [comment]
Was für eine Version hat dern hm-rpc Adapter?

**Comment by vr6syncro** [comment]
direkt vom git die letzte version

**Comment by vr6syncro** [comment]
https://github.com/ioBroker/ioBroker.hm-rpc/issues/120
