### ISSUE TITLE
Device Firmware Update: Interface Fehlermeldung wird nicht angezeigt.  

### ISSUE THREAD

**Issue by thkl** [jens-maus/RaspberryMatic#515]
Wenn bei mehreren Geräten ein Firmwareupdate eingespielt wird, kommt es zu einem hohem DutyCycle. Soweit so gut. Das RF Interface prüft daher vor dem Einspielen, ob noch genügend DC vorhanden ist.  Wenn man jetzt ein Update über das WebUI anstößt, das Interface aber eine fault Message zurück liefert, bekommt man im WebUI nur eine leere Box mit OK Button angezeigt. Aber keinen Hinweis auf den nicht mehr ausreichenden DC.

**Comment by sahomm** [comment]
Gleiches Verhalten kann ich bestätigen. Bei dem Update mehrer Stellantriebe HM-CC-RT-DN und Thermostate HM-TC-IT-WM-W-EU war es bei mir genau wie thkl beschrieben hat, nur das ich es nicht mit DC in Verbindung gebracht habe. SH ak Saho

**Comment by herbylfs** [comment]
Selbe verhalten bei der CCU3
Herbert

**Comment by HMside** [comment]
Vielleicht konnten man hier gleich die Übersetzung der Meldung, sowie einen ausführlicheren Hinweis inkl. aktuellen DC-Wert einbauen. Z.b. wie folgt:

`Das Sendelimit (DutyCycle) der Zentrale ist zu x% ausgelastet, daher kann aktuell kein weiteres Update durchgeführt werden. Zu beachten ist zudem, das bei einer Auslastung des Sendelimits von nahezu 100%, die Kommunikation mit Geräten nicht mehr möglich ist. Bitte warten Sie 1 Stunde, oder starten Sie die Zentrale neu.`

**Comment by jens-maus** [comment]
Gerne! Ich warte auf den PullRequest ;)

**Comment by herbylfs** [comment]
Den Duty Cycle kann man sich doch anzeigen lassen.
https://homematic-guru.de/quicktipp-homematic-duty-cycle-anzeigen
Auf die Startseite gelegt und gut ist.
herby

**Comment by jens-maus** [comment]
Bitte mal einen Screenshot zeigen wo solch eine Meldung lediglich mit OK button angezeigt wird damit man sich einfacher ein Bild davon machen kann und ich weiss wo ich das genau implantieren muss in die WebUI.

**Comment by jens-maus** [comment]
This ticket has been closed because of inactivity of the ticket owner and due to the fact that no developer could reproduce the issue. Please reopen the ticket once it can be reproduced again or the ticket owner can reply accordingly.
