### ISSUE TITLE
Kein WLAN mehr möglich nach Update.

### ISSUE THREAD

**Issue by MikeEcho0815** [jens-maus/RaspberryMatic#517]
Hallo.
Seit dem Update heute habe ich ein Problem, mich per WLAN mit dem Raspi zu verbinden. Ethernet klappt ohne Probleme.
Auf der Konsole kann ich erkennen, dass wlan0 gestartet wird und auch per dhcp eine IP erhält. Auch der HMIPServer startet mit "OK!" Allerdings ist das WebInterface nicht aufrufbar. 

Version: 3.41.11.20181126
Raspi 3 mit OnBorad WiFi

Vielen Dank im Voraus
Mike

**Comment by jens-maus** [comment]
Das kann kein generelles Problem (Bug) sein, denn bei anderen Nutzern funktioniert das. Bitte im HomeMatic Forum entsprechend informieren/diskuierten. Das hier ist ein Bug/Issue Tracker für Probleme die definitiv repariert werden müssen.
