### ISSUE TITLE
Raspi und HM-Gateway

### ISSUE THREAD

**Issue by holgerhermann1968** [jens-maus/RaspberryMatic#518]
Seit dem Update des Raspi 3 auf Version 3.41.11.20181126 zeigt mein HM-CCU Gateway im Status "nicht verbunden" obwohl die Netzwerk LED im Gateway grünes Dauerlicht hat ! 
Habe den Gateway mehrmal gelöscht den Raspi neu gestartet und dann wieder hinzugefügt Raspi neu immer ohne Erfolg.
Was mich stuzig macht das die DutyCycle einen Wert anzeigt und die firmware aus dem Gateway Stand 1.4.1 ausgelsen wird

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!
