### ISSUE TITLE
raspimatic update 2 ccu3-firmware- iobroker connection error

### ISSUE THREAD

**Issue by LeonVos** [jens-maus/RaspberryMatic#519]
after latest update to ccu3 firmware for raspimatic, no connection to HM-RPC ?
connects to host and there is a heartbeat connection.
also updated CUXD and XML-api
HM-REGA connects normal.

was there a change on portnumbers ??

thx

**Comment by libertyx82** [comment]
Since Version 3.41.X there are new Firewall policies and settings, that you must take care of it.

https://github.com/jens-maus/RaspberryMatic/releases/tag/3.41.11.20181124

**Comment by jens-maus** [comment]
Exactly! So this is no RaspberryMatic problem or bug but a change in the 3.41.11 line of firmware you have to take care of yourself in your installations!

**Comment by LeonVos** [comment]
THX !!
That made it happen, and me happy again, GOOD WORK, default all ports closed !!

i will support you

regards Leon vos
