### ISSUE TITLE
Verbindungsprobleme ioBroker zu 3.41.11.20181222 mit XML-API 1.20

### ISSUE THREAD

**Issue by andreasploetz** [jens-maus/RaspberryMatic#520]
Hardware: RPI3B+
Software: ioBroker, 3.41.11.20181222, XML-API 1.20

Nach dem aufspielen der neuen Firmware konnte sich der hm-rpc.0 Adapter im ioBroker nicht mehr verbinden..

Fehlermeldung: init error: Error: Unknown XML-RPC tag 'TITLE'

**Comment by jens-maus** [comment]
Duplikat von #519
