### ISSUE TITLE
Update not possible, no coprocessor found

### ISSUE THREAD

**Issue by IceBoosteR** [jens-maus/RaspberryMatic#521]
Hi,

this is from this thread:
https://homematic-forum.de/forum/viewtopic.php?f=65&t=45787

After this was not picked up I do now open a bugfix to hope that this got fixed.
So I have a RPi3+ with "SmartHome Funkstick für HomeMatic IP " for HMIP functionality. This stick is just a rebranded HmIP-RFUSB.
I am on a very old version from March and still want to update, but this issue is preventing me from doing so.
I need to import/export my backup but this is not working due to the error message (in german):
Beim Einspielen des System-Backups ist ein Fehler aufgetreten [...]. **Es ist kein Coprozessor verfügbar**

I have tried this with the most recent version, 3.41.11.20181222.

Please fix the issue.

**Comment by IceBoosteR** [comment]
With the actual version from January 19 it is still not working :/

**Comment by jens-maus** [comment]
Das ist keine Überraschung. An dem Teil habe ich nichts modifiziert, auch weil ich das Problem bis jetzt selber noch nicht reproduzieren konnte. Ich denke aber es wird daher kommen, das ein reiner betrieb nur mit einem HmIP-RFUSB bisher nicht vorgesehen ist von eQ3 und daher die Backup Restore Funktionen nicht vorgesehen haben das es kein GPIO-basiertes Funkmodul gibt. Aber das muss ich bei Gelegenheit erst einmal verifizieren.

Alternativ kann auch einfach mal probiert werden das Backup als `*.sbk` Datei in eine frische RaspberryMatic Version via scp/sftp z.b. in `/tmp` hochzukopieren und dann das kommandozeilenprogramm `restoreBackup.sh` statt die WebUI für das einspielen des Backups zu verwenden.

**Comment by jens-maus** [comment]
@IceBoosteR Danke für die Info. Es würde mich aber trotzdem interessieren was nun passiert wenn du mal ein Backup mit der aktuellen 3.41.11.xxxx version generiert und versuchst das wieder in die gleiche Version einzuspielen. Meine Vermutung ist, das es dann wieder zu dem hier genannten Problem einer Fehlermeldung "No coprocessor found" kommt. Kannst du das bitte noch testen?

**Comment by IceBoosteR** [comment]
Hallo @jens-maus ,

ich habe das soeben ausprobiert, die Meldung ist dieselbe. "Es ist ein Fehler aufgetreten [...] Kein Co-Prozessor verfügbar".

-IceBoosteR

**Comment by jens-maus** [comment]
Dann stimmt meine Vermutung das er wohl einfach nicht damit rechnet das man lediglich ein HmIP-RFUSB nutzt und keinerlei GPIO basiertes Funkmodul. Die Restorefunktionen machen nämlich einige Zusätzliche Prüfungen um sicherzustellen das das einzuspielende Backup passt und diese Routinen kommen wohl mit einem reinen HmIP-RFUSB betrieb nicht klar... so zumindest die aktuelle Vermutung.

**Comment by advorsky73** [comment]
Gerade eben mit einem Backup eines Raspi 1B+ nach Raspi 3B+ versucht mit eben NUR einem HmIP-RFUSB daran. -> Oben genannte Fehlermeldung. Ich kann das Backup nicht einspielen. Version ist jeweils die aktuelle Release.

**Comment by quinnens** [comment]
Für alle mit dem selben Problem: ich kann bestätigen, dass dieser Workaround mit der aktuellen Version funktioniert:

> Alternativ kann auch einfach mal probiert werden das Backup als `*.sbk` Datei in eine frische RaspberryMatic Version via scp/sftp z.b. in `/tmp` hochzukopieren und dann das kommandozeilenprogramm `restoreBackup.sh` statt die WebUI für das einspielen des Backups zu verwenden.

**Comment by danielperna84** [comment]
Der Vollständigkeit halber möchte ich erwähnen, dass eine frisch geschriebene MicroSD mit `3.59.6.20210703` auch den genannten Fehler wirft, wenn man ein Backup einspielt, welches von Version `3.49.17.20191225` erstellt wurde. Hierzu sei noch zu sagen, dass ich den Charly-Bausatz habe, also eigentlich ein GPIO-basiertes Modul.

Das wichtigste hierbei jedoch: nach einem Neustart hat trotzdem alles funktioniert und alle Geräte waren wieder da. In meinem Fall war es also nur ein kosmetisches Problem.

**Comment by hetti72** [comment]
Ich kann das von  @danielperna84 beschriebene verhalten exakt bestätigen, ich bin gestern auf das gleiche Problem gestoßen. 
Das update auf einer CCU3 mit original SD Karte auf die 3.59.6.20210703 von einer 3.57er Version funktionierte nicht. Ich habe deshalb das aktuelle Image auf eine 32GB Karte geschrieben und wollte dann das Backup der 3.57er Version einspielen, was in o.g. Fehlermeldung resultierte. Nach dem Neustart der CCU waren dann aber trotzdem alle Geräte da und es funktioniert auch alles

**Comment by jens-maus** [comment]
> Der Vollständigkeit halber möchte ich erwähnen, dass eine frisch geschriebene MicroSD mit `3.59.6.20210703` auch den genannten Fehler wirft, wenn man ein Backup einspielt, welches von Version `3.49.17.20191225` erstellt wurde. 

Hier hast du leider ein altes Ticket rausgekramt, statt dich an #1333 zu hängen wo ich bereits bemerkt hatte das das Problem ein Bug in der 3.59.6.20210703 ist den ich für die nächste Version bereits beseitigt habe (siehe https://github.com/jens-maus/RaspberryMatic/commit/4673610cba6af1bbdcec383d879339e66ef3123c).
