### ISSUE TITLE
Is CC1101 Raspberry Pi SPI Modul V0.3 supported?

### ISSUE THREAD

**Issue by jsponz** [jens-maus/RaspberryMatic#523]
https://shop.codm.de/module/3/cc1101-raspberry-pi-spi-modul-v0.3?c=5

Thanks!
Jorge

**Comment by jens-maus** [comment]
No it is not. It only works with the RF modules listed in the README and sold by eQ3. However, using the CUxD Addon software it might be supported somehow.
