### ISSUE TITLE
rfkill unblock funktioniert nur bis Neustart

### ISSUE THREAD

**Issue by Dud3z** [jens-maus/RaspberryMatic#524]
Hallo zusammen,

ich versuche die bluetooth schnittstelle zu aktivieren um diese in redmatic mit der bluetooth presence node zu nutzen. hci0 wird allerdings nach jedem reboot erneut softblocked. meines wissens muss man eine schnittstelle per rfkill unblock nur einmalig entsprerren. Sie sollte danach funktionieren.

Kann mir jemand weiterhelfen?

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!
