### ISSUE TITLE
@Home Zugriff --> keine Gerätewerte

### ISSUE THREAD

**Issue by Sobernheim99** [jens-maus/RaspberryMatic#525]
Habe die Version 10/18 ohne Login im Einsatz gehabt, Zugriff über @Home (auf iOS) problemlos. Nach Update auf Version 12/18 und einrichten des Admin-Accounts werden alle Räume und Geräte angezeigt, jedoch ohne Werte (sprich keine Temperatur, keine Statusmeldung Rauchmelder, etc.).
Was nun?

**Comment by jens-maus** [comment]
Problem ist bekannt und der Entwickler von @Home arbeitet wohl bereits daran. Siehe:

https://homematic-forum.de/forum/viewtopic.php?f=65&t=47737

Momentan bleibt nur auf die Vorversion von RaspberryMatic zu gehen oder statt @Home z.B. PocketControl einzusetzen.
