### ISSUE TITLE
Status Only in Favorites does not work for all devices

### ISSUE THREAD

**Issue by StefanGubler** [jens-maus/RaspberryMatic#526]
Anleitung zum Reproduzieren des Fehlers:
1. Erstelle Favoriten und füge HM und HmIP Geräte hinzu
2. Funktion aller Geräte in den Favoriten auf Status ändern
3. Erstellte Favoriten anzeigen.

Erwartetes Ergebnis:	
Alle Messwerte werden angezeigt.
Keine Änderung von Parametern möglich.
Keine Schaltvorgänge möglich.

Tatsäschliches Ergebnis:
Die erwartete Funktion funktioniert bei den getesteten HM Geräten
und bei HmIP Schaltsteckdosen.

Getestete Geräte, welche in der Favoritenansicht mit Funktion Status korrekt funktionieren,
bzw. nur eine Anzeige möglich ist, aber keine Bedienung.
HM-TC-IT-WM-W-EU
HM-ES-PMSw1-Pl-DN-R5
HM-LC-Sw1-FM
HM-Sen-MDIR-WM55
HM-CC-RT-DN
HmIP-PSM-CH
HmIP-FSM
HmIP-SMI55

Getestete Geräte, welche in der Favoritenansicht mit Funktion Status NICHT korrekt funktionieren,
da die Sollwerte veränderbar / bedienbar sind und auch Schaltaktionen ausgeführt werden können,
genauso wie wenn die Favoriten mit Funktion Bedienung konfiguriert werden.
HmIP-BWTH
HmIP-STHD
HmIP-STH
HmIP-SWO-PR
HmIP-FBL

Getestet auf zwei Homematic Installationen,
mit mehreren Browsern und auch mit Browser Cache löschen,
auch mehrere Neustarts des Hoemmatic Servers brachte keine Änderung.

Getestet auf Raspberrymatic mit Firmware 3.41.11.20181222 auf einem Tinkerboard S
und mit Raspberrymatic 3.41.11.20180428 auf einem Raspberry Pi 3B

Funktionseinschränkung auf Status-only über die der Favoriten
ist der einzige Weg, wie die Berechtigung für einzelne Geräte und Datenpunkte für Benutzer eingeschränkt werden kann,
ohne auf Fremdprodukte oder Drittsoftware zurückzugreifen.

Eine mögliche Ursache habe ich nicht gefunden.
Vielleicht sind die Stammdaten der HmIP Geräte teilweise falsch in der Applikation hinterlegt, 
und das WebGui stellt dann dies falsch dar.

Den Bug werde ich auch an ELV + EQ-3 weiterleiten und warte auf deren Reaktion.
ich kann gerne Unterstützung geben bei der Diagnose oder für allfällige Tests.

**Comment by jens-maus** [comment]
Ist das Problem mit aktuellen RaspberryMatic Verisonen noch reproduzierbar? Wenn ja bitte Screenshot zeigen und noch einmal kurz erklären was erwartet wird wie das aussehen/verhalten sollte.

**Comment by StefanGubler** [comment]
Ja, der Fehler besteht weiterhin und ist sogar noch schlimmer als im ersten Test ermittelt.
Es hängt auch noch davon ab, welcher User angemeldet ist (Administrator/ Benutzer/Gast).
Es gibt sogar den Fall, dass in einer Favoritenanzeige (mit Control ) für Benutzer Gast, ein Aktor geschaltet werden kann (HM-ES-PMSw1-Pl-DN-R5) sich die Anzeige aber nicht aktualisiert.
Oder die Lamellenposition einer Jalousiesteuerung (HmIP-FBL) verschoben werden kann, aber keine Aktion erfolgt. Jalousie hoch/runter funtkioniert.

Umgekehrt, in einer Favoritenanzeige (alle nur mit Status) gibt es weiterhin Aktoren, welche geändert werden können, wie beschrieben, abhängig von den Benutzerrechten.
Ich hoffe ich finde nächste Woche Zeit für systematische,dokumentierte Tests.
Es ist leider wieder etntäuschend, dass in der WebUI nach so vielen Jahren immer noch so viele Bugs drin sind.

Getestet auf Raspberrymatic 3.47.18.20190918 auf Tinker S / Hm Geräte mit aktueller Firmware
