### ISSUE TITLE
Docs about how to write Addons?

### ISSUE THREAD

**Issue by andygrunwald** [jens-maus/RaspberryMatic#53]
Hey,

thanks for this project. Initial installation worked like a charm.
I ask myself if there is any (technical) documentation for software engineers how to write addons?
I saw you have a few already, but i might want to do more features.

My current use case is to create a virtual smoke detector to be able to (reuse) the homematic smoke detectors as an alarm system.
In general i want to trigger them when i want + when fire is ongoing (this will be automatic).

FHEM supports this feature. See https://wiki.fhem.de/wiki/HM-SEC-SD_Rauchmelder#virtueller_TeamLead

Any hint how to reach this?

**Comment by jens-maus** [comment]
First of all, there is no official technical documentation on how to writing Addon package for a CCU. However, there are enough open source CCU add-on packages available of GitHub from which you should be able to gather the required knowhow.

Besides that, for the functionality you want to implement IMHO there is no need to create a CCU add-on but simply create rega scripts or tclsh scripts that will actually do what you want. In addition, there are already hardware solutions to actually trigger an alarm on the smoke detectors (see homematic-forum.de).

Last not least this ticket is not specific to RaspberryMatic but requesting general documentation on how to write addons. Thus, this ticket/request should be better suited directly in the OCCU GitHub project.
