### ISSUE TITLE
Please add compatibility for HmIP-FCI1

### ISSUE THREAD

**Issue by drMaxxi** [jens-maus/RaspberryMatic#537]
Current error message: “Der Kanal hat hier keine Funktion”

**Comment by jens-maus** [comment]
Bitte mehr Information! Solche One-Liner Issues sind ein No-Go und schreien danach einfach rejected zu werden...

**Comment by drMaxxi** [comment]
Hallo Jens,

Das Gerät soll den Status von Magnetkontakten ausgeben (was es aber nicht tut) - sondern nur die obige Meldung.
In den Einstellungen hingegen wird das Gerät korrekt als “Homematic IP Kontakt-Schnittstelle Unterputz - 1-fach” erkannt.

Somit fuerchte ich, dass entweder das Geraet defekt ist, oder noch nicht unterstuetzt wird...

Danke fuer deine Muehen.

**Comment by drMaxxi** [comment]
Konnte das Problem in der Zwischenzeit lösen. Nach erneutem Ablernen, Neustart der Zentrale und erneutem Anlernen, war es möglich es korrekt einzustellen.
