### ISSUE TITLE
how to enable wlan on the raspi 3a+?

### ISSUE THREAD

**Issue by svidoso** [jens-maus/RaspberryMatic#538]
There is no ethernet to begin with, so enabling ssh from the web-ui is not possible. Is there any manual available?

**Comment by libertyx82** [comment]
Have you tried it over the console on HDMI ?

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!
