### ISSUE TITLE
createBackup.sh: Option für Dateiname

### ISSUE THREAD

**Issue by methodus** [jens-maus/RaspberryMatic#539]
Hallo Jens,

dieser Request ist ähnlich zu #314, der Use Case aber ein anderer: ich nutze KEIN NAS und verwende daher auch nicht den bestehend cronBackup.sh-Job, da der ja nur auf einen angeschlossenen USB-Storage speichert.

Ich habe unter /usr/local/ ein eigenes Backup-Script, welches ich über die /usr/local/crontab/root ausführen lasse und somit auch automatisch selbst mit gesichert wird. Mein Backup-Script sichert nach G-Drive. Damit das möglich ist, muss ich den exakten Dateinamen wissen, den ich hochladen möchte. Da createBackup.sh allerdings keine Ausgabe bereitstellt, welche Datei wohin geschrieben wurde, musste ich mir das Script anpassen, so dass es auch den Dateinamen als Option erlaubt.

So kann ich innerhalb meines g-drive_backup.sh-Script die createBackup.sh $BACKUPFILE ausführen und die Datei sofort hochladen und anschließend löschen.

Im Anhang habe ich meine Änderungen als Patch. Das Standardverhalten (ohne Optionen) hat sich nicht geändert, stattdessen sind die Optionen -o für den Outputordner und -f für den Dateinamen dazu gekommen.

[createBackup.sh.patch.txt](https://github.com/jens-maus/RaspberryMatic/files/2798970/createBackup.sh.patch.txt)

**Comment by jens-maus** [comment]
@methodus So, hab mir mal erlaubt das createBackup.sh etwas zu pimpen. Schau mal ob das deinen Anforderungen so immer noch entspricht und ich nicht irgendein Fehler ausversehen eingebaut habe :)

**Comment by methodus** [comment]
Hmmm... ein Kritikpunkt: in Zeile 39 (https://github.com/jens-maus/RaspberryMatic/commit/9693a9589e2f71b8187e31f7227f6177918165cd#diff-727c14dd52e00ad7d3daf24e4589ddb7R39) prüfst du, ob als Pfad ./ angegeben ist und hängst den Standardpfad vorn an. Das halte ich für kritisch, da die Semantik von ./ die aktuelle Verzeichnisebene im Kontext der ausführenden Applikation beschreibt.

Beispiel:
```
# cd /usr/local/backup
# /bin/createBackup.sh ./myBackup.sbk
```
hier würde ich jetzt erwarten, das im Verzeichnis /usr/local/backup die Datei ./myBackup.sbk angelegt wurde. Ohne deine Version getestet zu haben, würde ich vermuten, wird sie trotzdem in /usr/local/tmp/ abgelegt.

Genau diesen Aspekt meinte ich mit Semantik ins Parsen des Pfads stecken, da unerwartete Ergebnisse rauskommen könnten.

**Comment by jens-maus** [comment]
Da hast du natürlich vollkommen recht. Aber in den Fuß schiessen kann man sich natürlich immer und muss schon wissen was man tut. Und diejenigen die createBackup manuell nutzen werden schon wissen was sie tun, würde ich sagen. Trotzdem geben ich dir natürlich recht das man den von dir gezeigten Fall noch abdecken sollte. Ich werde es mir dann mal näher anschauen und versuchen diesen Fall noch entsprechend abzudecken.
