### ISSUE TITLE
RTC clock modules (PiFace Shim RTC, DS3231) fehlermeldung multimacd restarted 

### ISSUE THREAD

**Issue by charlphyro** [jens-maus/RaspberryMatic#54]
Hallo Jens,
Bekomme im Watchdog eine Fehlermeldung multimacd restarted alle 3 Minuten.
Davor lief alles nur die RTC Clock habe ich jetzt mit dran gemacht?

Vielleicht hilft dir das ja

Viele Grüße Charly

**Comment by jens-maus** [comment]
Es tut mir leid, aber mit dieser knappen Fehlerbeschreibung und ohne jeglichen Debugoutput kann ich wenig damit anfangen oder den Fehler eingrenzen.
