### ISSUE TITLE
WebUI: Speichern und Laden von Programmen

### ISSUE THREAD

**Issue by ThomasLoeffel** [jens-maus/RaspberryMatic#542]
Hallo Jens,

im Falle das ein Aktor abgelernt wird, werden natürlich auch alle Programme gelöscht. Meine Idee ist nun das man Programme einzeln speichern und auch wieder einspielen kann. Des Weiteren wäre es super, wenn man einzelne Zeilen im Programmiermodus des WEBUI kopieren, einfügen oder verschieben könnte. Dieses würde einiges vereinfachen.

Lieben Gruß Thomas

**Comment by jens-maus** [comment]
Duplicate of #974
