### ISSUE TITLE
HmIP-BSL Kanal 8 (Oberes LED-Licht) fehlt bei der Programm-Auswahl

### ISSUE THREAD

**Issue by mgrulich** [jens-maus/RaspberryMatic#544]
Der Kanal Nummer 8 für die Steuerung der oberen Beleuchtung des Taster ist nicht innerhalb der Programme auswählbar.

Zentrale: Raspberry Pi 3
Firmware-Version: 3.41.11.20190126

**Comment by jens-maus** [comment]
Das ist natürlich ein guter Hinweis. Also bitte unter `Einstellungen -> Benutzerverwaltung -> Bearbeiten` das `Modus vereinfachte Verknüpfungskonfigruation aktivieren` deaktivieren und dann noch einmal schauen ob der Kanal dann entsprechend auftaucht.

**Comment by mgrulich** [comment]
Hallo zusammen,

tatsächlich ist der Kanal nun wählbar.

**Comment by jens-maus** [comment]
Ok, danke für die Info.
