### ISSUE TITLE
RPI-RF-MOD LED blinkt blau/gelb ohne Servicemeldung 3.41.11.20190126

### ISSUE THREAD

**Issue by roe1974** [jens-maus/RaspberryMatic#545]
In der aktuellen RM 3.41.11.20190126 konnte ich folgendes Phänomen beobachten:

Wenn ich in der WebUI bei einem Gerät die Servicemeldungen deaktiviere (Habe es jetzt bei mir bei Geräten die am LGW hängen getestet) ... dieses Gerät bzw. das LGW dann vom Strom nehme ... nach zB. 5min das Gerät/bzw. LGW wieder online nehme ... dann bei diesem Gerät die Servicemeldungen  wieder aktiviere...blinkt das LED des RPI-RF-MOD blau/gelb obwohl keine Servicemeldung da ist.

Kann das wer bestätigen ?

lg Richard

**Comment by roe1974** [comment]
niemand der das bestätigen kann ?

**Comment by HMside** [comment]
Hast Du im Benutzerkonto die automatische Bestätigung der „war gestört“ Meldungen an? Falls ja, ist das verhalten „normal“, weil die Meldungen eben nicht automatisch, sondern erst mit dem anklicken des Buttons „Servicemeldungen“ bestätigt werden. Der Bubble ist aber trotzdem grün und die Meldungsanzahl 0.

**Comment by roe1974** [comment]
nein, automatische Bestätigung ist nicht aktiviert...

**Comment by roe1974** [comment]
alles aktuell .... kannst du mal bei einem gerät die servicemeldungen deaktivieren .... am besten von einem der regelmäßig sendet ... und nach ca 5min wieder aktivieren ... weil dann blinkt es bei mir ohne dass eine servicemeldung da ist ...

**Comment by ThomasPoett** [comment]
Bei mir dito mit dem akutellen Release.
Ich habe jetzt mehrfach versucht from the scratch anzufangen, aber sobal ich das erste Hm-IP anlerne kommt sofort das gelbe blaue Binken und das war es dann. 
Erst wenn ich eine frische Image aufspiele ist es weg und nur das normal blaue Leuchten ist vorhanden. 
Dann selbes Spiel und es blinkt wieder.
Ich verzeifel und das trotz Werkreset alle Hm-IP Geträte.

**Comment by ThomasPoett** [comment]
So, jetzt bin ich etwas sprachlos.... ich habe die vorletzte Version 41 gerade mal installiert und siehe da.
Ich habe gleich in einem Cycle 2x Hm-IP Geräte angelernt.
PS: Bin Donnertag etwas frei falls Du @jens-maus es Dir anschauen magst.

**Comment by mamama1** [comment]
Habe jetzt die Widerstände R12, R9 und R15 ausgelötet und somit die LED ein für alle Mal hardwareseitig deaktiviert. Die Helligkeit der LED und dass man diese nicht per Software einfach ausschalten kann ist völlig lächerlich. Es soll Menschen geben, deren Leben nicht von der Homematic ablenkt und denen es egal ist, wenn da mal ein paar Statusmeldungen offen sind und man sich erst nach Tagen oder Wochen drum kümmert.

Ich brauch keinen Flutlichtscheinwerfer im Wohnzimmer.

**Comment by jens-maus** [comment]
Natürlich kann man die dauerhaft ausschalten. Einfach die Datei `/etc/config/disableLED` anlegen, fertig.

**Comment by PhilipHanebeck** [comment]
> Habe jetzt die Widerstände R12, R9 und R15 ausgelötet und somit die LED ein für alle Mal hardwareseitig deaktiviert. Die Helligkeit der LED und dass man diese nicht per Software einfach ausschalten kann ist völlig lächerlich. Es soll Menschen geben, deren Leben nicht von der Homematic ablenkt und denen es egal ist, wenn da mal ein paar Statusmeldungen offen sind und man sich erst nach Tagen oder Wochen drum kümmert.
> 
> Ich brauch keinen Flutlichtscheinwerfer im Wohnzimmer.

Sorry, aber man kann auch mit Kanonen auf Spatzen schießen, wäre etwas schwarzes Klebeband oder ein schwarzer Edding nicht auch gegangen?

**Comment by mamama1** [comment]
Keine Softwarebasierte Lösung hat bei mir funktioniert. Edding und Klebeband ist ja wohl Pfusch, ich werd mir nächstes Mal beim Mouser ein paar größere Widerstände bestellen, dann soll das Ding von mir aus blinken, aber in normaler Helligkeit.

**Comment by jens-maus** [comment]
Das hier ist kein Diskussionsforum, daher bitte Diskussion ins HomeMatic-Forum verlagern. Die von mir angegebene Variante mit anlegen einer leeren `/etc/config/disableLED` Datei funktioniert mit neuesten Firmwareversionen (egal ob RaspberryMatic oder CCU3 Firmware). Und es gibt daher IMHO nichts weiter hier hinzuzufügen.

**Comment by mamama1** [comment]
seit wann gibts diese Option und wo ist sie dokumentiert? Ich habe vor ca. 1 Monat gesucht wie ein Irrer und habe alle im Internet aufzufindenden, softwareseitigen "Lösungen" ausprobiert, alle ohne Erfolg.

**Comment by friedpa** [comment]
Nochmals: Das ist kein Diskussionsforum. 

Jens arbeitet hier für unsere Community und macht einen super Job. E-Mails in diesem Stil sind ein NoGo, man kann auch höfflich fragen, da bricht keinem etwas ab. 

 

Von: mamama1 <notifications@github.com> 
Gesendet: Freitag, 22. März 2019 10:36
An: jens-maus/RaspberryMatic <RaspberryMatic@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [jens-maus/RaspberryMatic] RPI-RF-MOD LED blinkt blau/gelb ohne Servicemeldung 3.41.11.20190126 (#545)

 

seit wann gibts diese Option und wo ist sie dokumentiert? Ich habe vor ca. 1 Monat gesucht wie ein Irrer und habe alle im Internet aufzufindenden, softwareseitigen "Lösungen" ausprobiert, alle ohne Erfolg.

**Comment by libertyx82** [comment]
> seit wann gibts diese Option und wo ist sie dokumentiert? Ich habe vor ca. 1 Monat gesucht wie ein Irrer und habe alle im Internet aufzufindenden, softwareseitigen "Lösungen" ausprobiert, alle ohne Erfolg.

https://github.com/jens-maus/RaspberryMatic/commit/ad78925231f713a072213484da8cab4f30f5da92

**Comment by jens-maus** [comment]
@mamama1 Dann hast du nicht richtig gesucht im Homematic Forum. Siehe:
https://homematic-forum.de/forum/viewtopic.php?f=65&t=47186&p=473755&hilit=disableLED#p473755

**Comment by mamama1** [comment]
Ich habe so viele Lösungen probiert, ich kann dir ehrlich nicht mehr sagen ob diese hier dabei war. Bis grade eben hatte ich noch 3.41 von Dezember oder Jänner drauf, jetzt mit 3.43.15.20190223 gibt die LED mit dieser Lösung Ruhe (auf meiner anderen RaspberryMatic).
Danke für deine Hilfe.
Ich weiß, dass dies kein Diskussionsforum ist. Wenn die LED leuchtet, wenn sie es nicht sollte, ist dies aber durchaus als Issue zu werten.
Mein Ärger hat vielleicht die falschen getroffen, dafür entschuldige ich mich. Was mich dermaßen getriggert hat, war u.a., dass an anderer Stelle absolutes Unverständnis dafür zu lesen war, diese LED abschalten zu wollen. Das Argument war "dann weißt du ja nicht, wenn deine Homematic ein Problem hat, stell dir nur mal vor!".

Meine Meinung: Wenn ich ein Tamagotchi haben will, dann kauf ich mir eins. Wenn sich in meiner Umgebung die Welt auch ohne HM weiterdreht, dann will ich auch diese Scheinwerfer LED abdrehen können ;-)

Danke für die tolle Raspberrymatic, vor dem Gedanken eine CCU2 o.ä. nutzen zu müssen graut mir.
