### ISSUE TITLE
Versionsbeschriftung???

### ISSUE THREAD

**Issue by Bischof-Mak** [jens-maus/RaspberryMatic#547]
Ich denke, dass die "neue" Version in der Übersicht falsch beschriftet ist!
![image](https://user-images.githubusercontent.com/38432207/51903966-c3a9ff80-23bd-11e9-9bfd-dea8d5276ff2.png)

Wie im Bild zu sehen, wird "2018.... " aufgeführt.
Eingespielt wurde definitiv "2019......"

**Comment by jens-maus** [comment]
Wenn dort "3.41.11.20181222" steht dann wurde das update definitiv nicht angewendet. Am besten mal schauen was im `/VERSION` file drinsteht (SSH login) und dann wirst du sehen das das definitiv die 20181222 noch ist.

**Comment by Bischof-Mak** [comment]
Habs gerade gemerkt! Sorry, Problem kann geschlossen werden!!
Hatte ein Cache Problem!
