### ISSUE TITLE
WebUI: Systemname vergeben können

### ISSUE THREAD

**Issue by josefbry** [jens-maus/RaspberryMatic#548]
![webui](https://user-images.githubusercontent.com/45110686/51922720-e5b97700-23e9-11e9-98d7-d01e2e5d1817.PNG)
Guten Tag. Ich habe eine bitte. Wir nutzen 4 CCUs in haus. Meistens hab ich 3 ständig offen in Browser. Wäre machbar das man schön auf dem Tabs anhand HomeMatic WebUI eigen Name geben (sehen) kann. Oder wenigstens auf Oberfläche wie auf dem Bild eigen Name den CCU geben. Vielen Dank

**Comment by jens-maus** [comment]
Das ist etwas was eQ3 in der originalen firmware implementieren müsste damit das auch kompatibel ist/bleibt. Also bitte an eQ3 melden.

Alternativ dazu würde ich eben im angezeigten Browser die browserzeile anzeigen lassen damit es klarer erkenntlich ist um welche CCU es sind hier handelt. Des Weiteren gäbe es noch die Möglichkeit die Farbgebung auf jeder CCU anders ausfallen zu lassen (siehe https://homematic-forum.de/forum/viewtopic.php?f=26&t=48479&hilit=color.map).

Ich sehe aber momentan nicht das das etwas ist was direkt in RM implementiert gehört, zumal das ja schon ein starker Sonderwunsch ist weil 99.9% der homematic Nutzer nur 1 CCU besitzen. Und wenn hier ein Hotel (wie hier anscheinend) gerne RM einsetzen will dann könnte man ja mal über ein sponsoring einen solchen Features, nachdenken, oder? :-)

**Comment by josefbry** [comment]
Ich bin leider keine Hotel Besitzer. Da hab ich stinknormales Haustechniker lohn. Schön das system in Hotel durchzusetzen war 2 jähriges kamp um Budget. Es solte dann auf dem BETTERSPACE Lösung laufen. Leider der war den Vorsetzungsrat zu teuer. Dann musste ich für eine 0 Chf Lösung zu suchen. Es ist war das jeder Anbieter wie BETTERSPACE so seine dienste baut das Mann dan verpflichtet ist jedes Jahr nicht kleine geld zu zahlen. Heiss für Einrichtung 7000,- + 3000,- jährlich, Schnitselle zu Hotel Software (automatische unter und hochfahren vom Heizungen nach Buchung) 7000,- einmalig + 1700,- pro Jahr. Heisst was ich pro Jahr an Heizung sparen kann zahl ich für Software. Da verstehe ich Vorsetzungsrat schön das die mir das geld dafür nicht geben.

**Comment by libertyx82** [comment]
Mit deinem Anliegen bist du hier https://homematic-forum.de/ definitiv besser aufgehoben.

Ich verstehe jetzt nicht ganz, was du an den Thermostaten ständig verändern musst, was sich mit einem Wochen/Tagesprogramm im Thermostat nicht programmieren lässt.

Prinzipiell wenn du auf allen Thermostaten z.B. die gleiche Soll Temperatur einstellen willst, sollte sich das mit einem Script erledigen lassen.

**Comment by josefbry** [comment]
Ja gerade die Grundeinstellungen Max/Min temperatur, Erkennung vom geöffneten fenster temperatur, reset am gerät sperren usw. usw. Ja Wochen/Tages Programm kan ich am hotel nicht nutzen. Es muss ständig auf manual sein. Weil der Gast ist der König.
Das gruppen einstellen vom Thermostaten mithilfe vom Skripten ist mir nicht bekannt. Da muss ich mich klug machen. Vielleicht eine Link hilft.

**Comment by jp112sdl** [comment]
Ich würd das hier gern noch mal aufgreifen.
Da ich manchmal mit Test- und Produktivsystemen parallel arbeite, wäre das benutzerdefinierte Vergeben des HTML `<title>`-Attribut schon viel wert. 
So sieht man in der Tab-Bezeichnung im Browser sofort um welches System es sich handelt.

Meine Idee wäre, die nirgends offiziell verwendete ReGa-Methode `system.Name()` zu verwenden.
Diese gibt default den Wert `ReGaRA Demo` zurück; lässt sich aber auch überschreiben.

In der `/www/rega/pages/index.htm` bräuchte es nur einen Einzeiler im JavaScript:
`document.title = "<% Write(system.Name()); %>";`

Lediglich das Vergeben des Namens müsste implementiert werden.

Da bin ich mir nicht sicher, in welches Systemsteuerungs-Panel das mit rein soll.
- Erweiterte Einstellungen? _(eigens für RaspberryMatic geschaffen)_
- Netzwerkeinstellungen? _(über/unter Hostname)_
- _Allgemeine Einstellungen fällt wie immer aus, da die Seite aus HMIPServer kommt_

Alternativ: Nur die Anpassung in der `/www/rega/pages/index.htm` machen und "Expertenuser" setzen sich den Namen mittels "Skript testen" (`system.Name("HM Hauptsystem");`) 1x selbst.
