### ISSUE TITLE
Switch init system to use "systemd" instead

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#55]
For a future version we should switch to "systemd" and convert all our functionality to use systemd instead.

**Comment by kleini** [comment]
I am familiar with systemd unit file development. I will try to get buildroot up and running and RaspberryMatic build with it. When you can give me any hints in this way, my contribution may come earlier :-D

**Comment by jens-maus** [comment]
Thanks for your support. I would simply suggest you try to build RaspberryMatic yourself first (`make dist`) and then see how you can integrate systemd support. Perhaps it might be a good idea to create a dedicated 'systemd' branch where we can start to apply the changes for systemd support so that the master branch can continue to be our somehow stable branch. Because I think switching to systemd would take a while and need some special care in not to break backward compatibility (e.g. to third-party addons, etc.)

**Comment by kleini** [comment]
Got `make dist` running, a final sdcard.img is created. I switched to the buildroot config to systemd and will run then the created image. Is it possible to emulate everything with the X86_32_docker BOARD on my x86 based development system?

**Comment by jens-maus** [comment]
@kleini No, this is currently not possible. But feel free to update the Docker based build root config if you feel you want to do this and actually get it working.

**Comment by kleini** [comment]
Okay, I'll try then qemu-system-arm.

**Comment by kleini** [comment]
Still have problems to get generated kernel booted in qemu-system-arm with machine raspi2. No idea, if this ever will work. Developing systemd by writing the sdcard.img to a real SD card and placing that into a Raspberry Pi does not seem to be feasible. This will slow down the whole development process by factor 5 or so.

**Comment by jens-maus** [comment]
Well, that's exactly how I am developing on RaspberryMatic :) SD card in, SD card out and remote SSH sessions where possible. But I agree that a new qemu driving development environment would be way better. So if you have a solution for it, let me know, I would love to setup a similar qemu environment for myself as well then.

**Comment by kleini** [comment]
`qemu-system-arm \
-M raspi2 \
-cpu arm1176 \
-smp 4 \
-m 512 \
-kernel build-raspberrypi3/images/zImage \
-drive file=build-raspberrypi3/images/sdcard.img,format=raw \
-append "dwc_otg.lpm_enable=0 lapic sdhci_bcm2708.enable_llm=0 consoleblank=0 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 console=tty1 elevator=deadline root=/dev/mmcblk0p2 rootfstype=ext4" \
-dtb build-raspberrypi3/images/bcm2709-rpi-2-b.dtb`

This boots the kernel not completely, it is stuck somewhere.

**Comment by jens-maus** [comment]
@kleini Sorry, but here it doesn't find the "raspi2" machine type. How/Where did you install QEmu from?

**Comment by kleini** [comment]
Ubuntu 16.10 yakkety
qemu-system-arm 2.6.1+dfsg-0ubuntu5.2

**Comment by jens-maus** [comment]
Sorry, but after some long thought about that I won't switch to system anytime soon. I am anyway no fan of systemd and think that it is IMHO too much of a hassle to switch to it and there is no immediate benefit for such an embedded system which should be lightweight.
