### ISSUE TITLE
Ich kann kein Backup einspielen, seit ich einen Sicherheitsschlüssel eingerichtet habe.

### ISSUE THREAD

**Issue by chrisbeth1000** [jens-maus/RaspberryMatic#550]

**Comment by jens-maus** [comment]
Tut mir leid, aber das sind definitiv zu wenig Informationen. Auch ist dies hier kein Hilfeforum oder ähnliches. Wenn es sich hierbei also um keinen definitiven Bug handelt dann bitte an das HomeMatic Forum wenden.
