### ISSUE TITLE
Anderen Dateinamen für Update-Dateien

### ISSUE THREAD

**Issue by rossiniscarface** [jens-maus/RaspberryMatic#551]
Für die Updatedateien, wäre es von Vorteil, wenn sie z.B. "-update" am Ende des Dateinamens dabeistehen haben. Somit könnte man eindeutig unterscheiden zwischen den Image-Zips und den Update-Zips. 
Da der Update-Prozess doch eine gefühlte Ewigkeit dauert (Zip runterladen, auf raspberrymatic hochladen, warten auf was auch immer) und dann wird man mit der Meldung "Keine gültige Updatedatei" belohnt, wäre das sicher eine gute Idee um hier neuen Benutzern einen etwas frustfreieren Einstieg zu bieten.

**Comment by jens-maus** [comment]
Was für „Updatedateien" bitte? Es gibt nur die zip dateien und die können für eine frische Installation wie für ein Update gleichermaßen genutzt werden.

**Comment by rossiniscarface** [comment]
Hmm, das File unter Assets hat als Update nicht funktioniert.  
Das weiter unten schon. 

Warum dann extra:

The following installation archives (*.zip files) can be downloaded for selected hardware platforms (including a *.tgz update archive to upgrade from a CCU3 firmware to RaspberryMatic). To verify their integrity a sha256 checksum is listed as well. Please upload these zip files using the WebUI-based update mechanism available:

**Comment by rossiniscarface** [comment]
Okey, hab eben gesehen, dass die Links auf die gleiche Datei gehen. 
Trotzdem eigenartig dass das Update mehrmals nicht funktioniert hat.
