### ISSUE TITLE
Fehler bei Cloudmatic web If Aufruf

### ISSUE THREAD

**Issue by Matten-Matten** [jens-maus/RaspberryMatic#552]
Wenn ich das Cloud Matic Webinterface aufrufen will kommt nur folgendes:

```html
 <!DOCTYPE html>
<html>
  <head>
    <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection">
    <link type="text/css" rel="stylesheet" href="css/cloudmatic.css"  media="screen,projection">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>CloudMatic (v20180325)</title>
  </head>
<body>
[...]
</body>
</html>

```

**Comment by jens-maus** [comment]
Welche RaspberryMatic Version? welcher Browser?

**Comment by jens-maus** [comment]
Nach kurzer Recherche scheint dies definitiv eine alte RaspberryMatic Version zu sein denn die aktuelle RaspberryMatic nutzt als CloudMatic Version `CloudMatic (v20181025)`, d.h. eine neuere Version die einen entsprechenden Bugfix beinhaltet. Daher bitte einfach auf die aktuellste RaspberryMatic Version updaten und das Problem sollte gelöst sein.

**Comment by Matten-Matten** [comment]
CCU-Firmware: 3.41.11.20190126

**Comment by jens-maus** [comment]
Dann stimmt da aber was in der Tat nicht. Denn dort sollte wie ich gesagt hatte 20181025 in der CloudMatic Seite stehen. Bitte Browser Cache, etc. löschen und browser Neustarten.

**Comment by Matten-Matten** [comment]
OK das Teste ich

**Comment by Matten-Matten** [comment]
Das scheint ein Chrome Problem zu sein, beim Internet Explorer geht es

**Comment by jens-maus** [comment]
Nein, ist es nicht. Chrome ist nur strikter was gewisse dinge angeht. Wie gesagt das WAR ein bug in CloudMatic der beseitigt wurde aber anscheinend deine RaspberryMatic Version ggf doch nicht aktuell ist ?!? Denn ansonsten sollte das problem nicht mehr auftreten bzw sich zeigen.

**Comment by Matten-Matten** [comment]
Was kann ich da tun?

**Comment by Matten-Matten** [comment]
![screenshot_20190204_121253](https://user-images.githubusercontent.com/32074970/52205175-82f72e00-2876-11e9-9076-e3366e5c17d7.jpg)
 Denn Raspberry Matic ist aktuell gibt es eine Möglichkeit Cloud Matic über die Zusatz Software Funktion zu aktualisieren?

Gruß
Matten Matten
