### ISSUE TITLE
Time in Group Settings is wrong by 1 Hour

### ISSUE THREAD

**Issue by sotatech** [jens-maus/RaspberryMatic#553]
**Describe the bug**
Time set in Group Settings is fast by one hour.

**To Reproduce**
1. Go to 'Settings, Groups'
2. Click on 'Set' for a group
3. Scroll down to 'Edit Week Programme'
4. Set the time for a temperature change. The change will happen one hour before the set time

**Expected behavior**
It should happen at the expected time.

**Screenshots**

**System information (please complete the following information):**
 - Version [ RaspberryMatic 3.41.11.20190126 and earlier versions]
 - Hardware [Both RaspberryPi3 and TinkerboardS]

**Additional context**
I live in Ireland, time zone EU/Dublin. The correct time is displayed in RaspberryMatic, and if I use time in a program, it works correctly. Also, the Last Modified time in Device Status is correct.
![raspmatic time](https://user-images.githubusercontent.com/9580066/52304957-d7400200-298b-11e9-8fc5-0528e2eecd6b.PNG)

**Comment by jens-maus** [comment]
Thanks for your report. Is this the only place where there seems to be a time issue? How about WebUI programs and the time module there when you want to e.g. execute a script on a certain time? So is there really only a time issue in the group settings of heating devices when you define a "week programme" to switch temperatures or is there also an issue on other places in the WebUI?

**Comment by jens-maus** [comment]
And some more questions: Which heating devices are you using? Please specify the exact type of homematic/homematicIP devices used to control your heating.

**Comment by sotatech** [comment]
I use a HM-LC-Sw4-DR-2 4 relay controller to drive the zone pumps of my heating. I have a mixture of 3 HM-CC-RT-DN TRVs in one group and 12 HMIP-eTRV in two other groups along with some HMIP-WTH thermostats and a HM-WDS30-OT2-SM to control hot water.
I have a WebUI program to turn on the hot water channel at 06:00 and this work correctly. The rest of the heating schedule is set by the time and temperature in the Groups setting, which is where I have the problem. The time displayed on the home page of RaspberryMatic is correct. Also, this has been happening for several months, so well before the time change to Winter time
Here are images of the Group Setting for one zone:
![settings 1](https://user-images.githubusercontent.com/9580066/52330141-87455780-29ec-11e9-8aba-2917c79f32c9.png)
![settings 2](https://user-images.githubusercontent.com/9580066/52330159-962c0a00-29ec-11e9-950a-76b51f90fda7.png)

Thank you for your help!

**Comment by jens-maus** [comment]
@sotatech Have you checked the DST settings in your HMIP-eTRV devices? Check the device settings page of each of these devices. They should contain Daylight saving configuration settings which you could modify. While the HM-CC-RT-DN devices usually get their time/DST information from the CCU device itself, the eTRV devices maintain own DST routines internally. Also, what does the time on the HM-CC-RT-DN devices show on the LCD?

**Comment by sotatech** [comment]
@jens-maus I have checked the DST settings and they seem OK to me, but I am not an expert on this topic! The DST setings are the same on the device as the group. I don't want to change it as this will affect how my WebUI programs run, also there is no DST settings for HM-CC-RT-DN devices, so they would be on different time to the eTRV devices. Also, the problem is the same with HM-IP and non HM-IP devices. The time on the HM-CC-RT-DN devices is correct. The HMIP-eTRV devices do not display the time.
![dst setting](https://user-images.githubusercontent.com/9580066/52340875-e022e900-2a08-11e9-8afa-d9f4c1c16eba.png)

**Comment by jens-maus** [comment]
Ok, thanks for checking. Unfortunately this rather seems to be a bug in the upstream software of the vendor (eQ3) and not specifically in RaspberryMatic itself. Thus, I do not currently see how I could fix this issue without the vendor actually trying to reproduce it themself. Thus, please open a ticket/request at the vendor and use this GitHub ticket as a reference so that they can check it accordingly.

**Comment by sotatech** [comment]
OK, thank you for your help and excellent English! I apologise for my lack of German. I will contact EQ3 support and report back if there is a solution.

**Comment by jens-maus** [comment]
@sotatech Oh, I just saw in your last screenshot that there the "UTC DEST offset" and "UTC offset" are 120 and 60 minutes. However, I do think that in my understanding for Ireland that should be 60 and 0 instead. see https://www.timeanddate.com/time/zone/ireland

So please check all your HmIP devices carrying this DST setting in its setting and check if changing it to the right DST offsets fixes your issues for the HmIP-eTRV.

**Comment by sotatech** [comment]
@jens-maus Success! I changed one group as you suggest, and the temperature changed at tthe correct time. I now realize that the HM-CC-RT-DN devices were getting the correct time zone from the CCU (GMT/IST UTC 0/1) while the HmIP-eTRV devices were using +1/+2. 
Many thanks for your help!

**Comment by jens-maus** [comment]
Great that we solved it. Take care.
