### ISSUE TITLE
HM-LC-Sw1-FM anlernen: Erscheint als HM-LC-Sw2-FM

### ISSUE THREAD

**Issue by schmidhorst** [jens-maus/RaspberryMatic#555]
**Describe the bug**
Wenn ein HM-LC-Sw**1**-FM neu angelernt wird, erscheint das Gerät mit der falschen Bezeichnung HM-LC-Sw**2**-FM. 

**To Reproduce**
1. Neuen HM-LC-Sw**1**-FM an RaspberryMatic anlernen
2. Geräte im Posteingang oder Geräteliste anschauen: Typenbezeichnung und Bild ist falsch, vom HM-LC-Sw**2**-FM.

**Expected behavior**
Anmerkungen:
- In alter RaspberryMatic-Version angelernte HM-LC-Sw**1**-FM sind nach wie vor o.k. 
- Der neu angelernte HM-LC-Sw**1**-FM hat trotz falscher Typenbezeichnung korrekter Weise nur einen Kanal. 
- Der Bug hat keinen Einfluss auf die Funktion.

**Screenshots**
![sw1sw2](https://user-images.githubusercontent.com/4062333/52596721-4e283f80-2e51-11e9-8b2e-1a87dd4b47c0.png)

**System information (please complete the following information):**
 - Version RaspberryMatic 3.41.11.20190126
 - Hardware RaspberryPi3

**Additional context**

**Comment by jp112sdl** [comment]
Hmm, das sieht ja echt komisch aus.
Wenn ich ein Gerät mit der Model ID des HM-LC-Sw**1**-FM unter derselben RaspberryMatic Version anlerne, wird es korrekt als 1-fach Aktor angezeigt:
<img width="1560" alt="bildschirmfoto 2019-02-12 um 07 37 10" src="https://user-images.githubusercontent.com/18190139/52616596-54daa500-2e99-11e9-9c3a-711dcf898e87.png">

Mit der "falschen" Model ID im Gerät, kann ich das von dir gezeigte Verhalten auch provozieren.
Aber das ist dann ein Fehler auf Seiten des **Geräts**:
<img width="1550" alt="bildschirmfoto 2019-02-12 um 07 43 33" src="https://user-images.githubusercontent.com/18190139/52616772-e9dd9e00-2e99-11e9-8f45-b927b26e4c39.png">


Es ist auch seltsam, dass bei dir keine Kanalparameter konfiguriert werden können.
Die werden eigentlich "live" versucht aus dem Gerät abgerufen, wenn du auf die Einstellungs-Seite wechselst.
Also irgendwie sieht es mir so aus, als würde entweder beim Anlernen was am Telegramm verfälscht werden (z.B. durch Funkstörungen) oder die Firmware des Aktors hat einen Fehler.

**Comment by jens-maus** [comment]
Existiert dieses Problem mit der neuesten RaspberryMatic version noch?

**Comment by Jonny-Controlletti** [comment]
Bei mir wird der selbe Aktor HM-LC-Sw1-FM ebenfalls als HM-LC-Sw2-FM dargestellt, hab Ihn aber erst seit der 3.41.11.20190126 angelernt. Er funktioniert bis jetzt ebenfalls als 1-Kanal-Gerät ohne probleme.
Hardware: RaspberryPi1 B+ 512MB
