### ISSUE TITLE
RaspberryMatic startet nach update auf 3.43.15.20190223 nicht mehr

### ISSUE THREAD

**Issue by Andi0r** [jens-maus/RaspberryMatic#559]
Hi, 
nach dem Update auf 3.43.15.20190223 startet raspberrymatic gar nicht mehr. 
es bleibt bei folgenden punkt hängen: 
![grafik](https://user-images.githubusercontent.com/47927511/53290826-e3102e80-37a9-11e9-9af8-2063d6d67e52.png)

Das ganz läuft auf einem Raspberry PI 3. 
Gibt es hierfür eine lösung?

LG
Andreas

**Comment by jens-maus** [comment]
ALT+F2 auf einer angeschlossenen Tastatur drücken um die Debugmeldungen zu sehen.

**Comment by Andi0r** [comment]
Bleibt bei mounting file system stehen und es kommen viele Punkte die nie enden.

**Comment by jens-maus** [comment]
Hast du einen externen USB Stick dran? Nutzt du eine SD karte oder ein USB Stick als RootFS? Kommst du ins RecoverySystem rein? Wenn ja würde ich von diesem aus noch einmal die aktuelle Version brennen.

**Comment by Andi0r** [comment]
Das ganz läuft über eine micro SD Karte. Sorry für die blöde Frage aber wie komm ich ins recover rein?

**Comment by jens-maus** [comment]
Wenn du das RPI-RF-MOD Funkmodul hast kannst du einfach die Taste darauf gedrückt halten. Wenn nicht wird das ein schwieriges unterfangen. Dann würde ich dir raten krizerhand dein aktuelles Backup zu nehmen, eine neue SD karte mit frischem RaspberryMatic zu flashen und dort dann dein Backup einzuspielen.

**Comment by Andi0r** [comment]
Habe leider das hm-mod-rpi-pcb also keinen Knopf, sieht wohl nach Neuinstallation aus. Trotzdem danke für die rasche Hilfe
