### ISSUE TITLE
backup restore mit "restoreBackup.sh" ohne sha256 File nich tmöglich

### ISSUE THREAD

**Issue by roe1974** [jens-maus/RaspberryMatic#560]
Ich habe festgestellt, dass ein restore eines bestehenden Backups ohne sha256 File mit der aktuellen RM nicht möglich ist. Es kommt folgender Fehler:

starting restore...
sha256sum: signature.sha256: No such file or directory
ERROR: inconsistent backup archive identified (sha256).

lg Richard

PS: ich restore mit:
/bin/restoreBackup.sh /mnt/last_backup.sbk

d.h. direkt von der NAS. der point wird vorher gemountet mit 
mount -t nfs 192.168.xxx.xxx:/volume1/hmconfig/ -o rw,nolock /mnt

**Comment by jens-maus** [comment]
Siehe diff des commits. Da hatte sich ein kleiner Bug eingeschlichen den ich gerade für die nächste Version repariert habe. Danke für den Report!
