### ISSUE TITLE
Keine "Einstellungen" mehr verfügbar bei HmIP-FCI1 seit FW 3.43.15.20190223

### ISSUE THREAD

**Issue by eberproducts** [jens-maus/RaspberryMatic#561]
**Describe the bug**
Keine Einstellungen mehr vorhanden bei HmIP-FCI1 ich dem Update auf FW 3.43.15.20190223

**To Reproduce**
1. Go to 'Einstellungen'
2. Click on 'Geräte'
3. Scroll down to 'HmIP-FCI1'
4. Click on 'Einstellungen' 
4. Seite öffnet aber keine Einstellungen mehr vorhanden.

**Expected behavior**
Hier sollten Einstellungen vorhanden sein um das Verhalten des IP Gerätes konfigurieren zu können.
Ebenfalls fehlen die Werte der Sende- / Empfangsleistung.
 
**Screenshots**

**System information (please complete the following information):**
 - Version [RaspberryMatic 3.43.15.20190223]
 - Hardware [RaspberryPi3]

**Additional context**

**Comment by jens-maus** [comment]
Da dies anscheinend auch auf einer reinen CCU3 mit 3.43.15 passiert sieht das nach einem generellen Problem in der CCU Firmware aus.

**Comment by eberproducts** [comment]
Alles klar - dann heist es abwarten bis eq3 das fixed.
Vielen Dank für die Info !!

**Comment by jens-maus** [comment]
Der folgende bereits in RaspberryMatic integrierte Patch sollte das Problem beheben:

https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0051-WebUI-Fix-eventDelayPrn.patch

D.h. die nächste kommende Version sollte das Problem der fehlenden KonfigParameter beheben.
