### ISSUE TITLE
deaktivierte Aktoren von Servicemeldungen ausnehmen?

### ISSUE THREAD

**Issue by fs-plugins** [jens-maus/RaspberryMatic#564]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
vorübergehend abgehängte Aktoren/Sensoren (Zwischenstecker ausgesteckt, Batterie aus Sensor genommen usw.) verursachen permanent Servicemeldungen - theoretisch richtig, sind ja nicht erreichbar
praktisch aber verhindern dauerhafte Servicemeldungen das Bemerken einer tatsächlichen wichtigen Meldung
ob/wie sich ein 'Gerät ist deaktiviert-Schalter' realisieren lässt weiß ich natürlich nicht - aber es wäre eine Idee bzw. ein Wunsch von mir ;-)

**Comment by jens-maus** [comment]
Das ist doch alles bereits seit einigen Versionen in RaspberryMatic implementiert!

Einfach mal die Geräteeinstellungen aufrufen (wo man auch Raum/Gewerk eines Aktors einstellt) und dort dann die Servicemeldungen für das Gerät deaktivieren.

**Comment by fs-plugins** [comment]
ach ich Narr - daran hab ich überhaupt nicht gedacht
vielen Dank für den Zaunpfahl

**Comment by jens-maus** [comment]
"Wer lesen kann, ist klar im Vorteil" fällt mir da ein ;)

Aber alles gut, sowas passiert
