### ISSUE TITLE
HM Sonnenauf- und Sonnenuntergangszeiten

### ISSUE THREAD

**Issue by beckerpa** [jens-maus/RaspberryMatic#565]
EQ3 - Ticket EBF21755C6F0D

Zeiten in der WebUI stimmen nicht überein mit den Zeiten von HmIP-Aktoren.
Nutzen der Astro-Zeit (WebUI) in Programmen durch unterschiedliche Zeiten für mich fraglich, da verschiedene Zeiten verwendet werden.
EQ3 hat diese Abweichung bestätigt, hält es aber für vertretbar und nicht für einen Fehler.

Wäre schön, wenn man sich der Sache irgendwann annimmt.

https://homematic-forum.de/forum/viewtopic.php?f=34&t=49351#p494588

**Comment by jens-maus** [comment]
Kannst du dazu bitte mal ein Testcase mit schritt für schrittanleitung beschreiben damit ich das hier zuhause mit meiner Testumgebung nachstellen kann. Auch wäre noch zu ergepnden welche Astrozeiten denn nun die vermeintlich korrekten sind? Die der Aktoren oder die der Geräte? Hier bräuchte ich definitiv mehr Mithilfe um ggf einen potentiellen Fix zu erarbeiten.

**Comment by beckerpa** [comment]
Vorausgesetzt, dass alle Längen- und Breitenangaben in den Aktoren, in der WebUI und - wenn vorhanden - im Accesspoint gleich sind dann:
**1) Verhalten:** Sonnenaufgang / Sonnenuntergang der HmIP Aktoren sind absolut zeitgleich mit den angezeigten Zeiten des Accesspointes. D.h. (mein Beispiel) HmiP-FROLL´s im Accesspoint fahren zeitgleich mit HmIP-FROLL´s der Raspberrymatic. Das gleiche gilt für ALLE anderen HmIP-Geräte, welche die Zeitfunktionen benutzen.
**Also: HmIP Aktoren/Geräte haben die richtige Astro-Zeit (identisch der Anzeige AP)**

**2) Testvorschlag:** Zweckentfremdung eines beliebigen HmIP-Aktors (haben in meinem Fall den HmIP-FSM vom Fernseher genommen), dort einfach einen Kanal zweckentfremden und die Astro-Zeit nutzen.
Diese Zeit dann entsprechend mitplotten, wenn der Kanal seine Einstellung ändert.
--> Ergebnis ist dann: Die Zeit in der WebUI weicht bis zu 2 Minuten von der richtigen Zeit ab.

**Comment by jens-maus** [comment]
Welche "Zeit in der WebUI“ meinst du denn genau? Die als sonnenaufgang/untergang angezeigt wird? Wie genau vergleichst du das den mit den zeiten der internen astro berechnung eines aktors? Wartest du jedesmal bis sonnenaufgang/untergang ist?

Eine weitere Frage wäre eben welche astroberechnungsroutinen die aktoren bzw die WebUI nutzen und wer hier falsch liegt? Hast du schon einmal im internet die sonnenaufgang/untergangszeiten quer gecheckt mit den angegebenen in der WebUI? Sollte sixh ja rausfinden lassen wer hier denn gwnau falsch liegt?!?

**Comment by beckerpa** [comment]
Ja, die Zeit die in der WebUI angezeigt wird als Sonnenaufgang/Sonnenuntergang.
Die Frage wer falsch liegt, welche Astro-Berechnungsroutinen benutzt werden kann ich als einfacher Nutzer sicherlich nicht beantworten.
Ich für meinen Teil habe lediglich, vollkommen wertfrei festgestellt in meinen Installationen:
Raspberrymatic - 12 HmIP FROLL (Astrogeführt) gehen Zeitgleich mit
Accesspoint - 2 HmIP FROLL (Astrogeführt) hoch und runter. Alle Aktoren, Raspberrymatic/Accesspoint und auch weitere (FSM, etc.) haben exakt die gleichen Längen und Breitenangaben wie auch der Accesspoint und auch Raspberrymatic.
Um sicherzugehen, dass dies kein Zufall ist, hatte ich das mal für mich protokolliert und auch im Urlaub täglich merken können.
Die Zeiten Sonnenaufgang und Sonnenuntergang die im Accesspoint angezeigt werden stimmen exakt mit allen FROLL überein. (Das gilt auch für andere Aktoren, die über die Astro-Möglichkeit verfügen.)
Da ich diese Zeiten auch für andere Steuerungen nutze, ist mir aufgefallen, dass die Zeiten der WebUI nicht exakt übereinstimmen.
Das ist schon alles. Kein riesiges Problem für mich- dachte eben, dass das nicht so gewollt ist.
Habe einfach einen Kanal eines Aktors zweckentfremdet, der Astrogeführt ein-, bzw. ausgeschaltet wird. Das ganze halt eben zeitgleich zu den Anderen.
Meine Erkenntnis war deswegen, dass die einzige Zeit die anders ist, die Zeit der WebUI ist. Ob diese nun falsch oder richtig ist kann ich nicht bewerten- jedenfalls ist sie anders, warum auch immer.

**Comment by HMside** [comment]
Werden die Aktoren an der CCU über das Aktorinterne Zeitprofil oder ein Zentralenprogramm gesteuert? Sofern das Aktorinterne Zeitprofil genutzt wird, sind die Standort Daten jeweils in den Aktor-Einstellungen einzutragen.

**Comment by beckerpa** [comment]
Die Aktoren an der Raspberrymatic sowie die Aktoren am Accesspoint werden alle durch das aktorinterne Zeitprofil gesteuert.
Die Standortdaten sind in allen Aktoren, der WebUI und des Accesspointes identisch.

**Comment by jens-maus** [comment]
Das Problem mit den unterschiedlichen Sonnenuntergang/aufgangszeiten sollte mit der nächsten kommenden 3.45.5.20190330 Version behoben sein.
