### ISSUE TITLE
Wrong default firewall config file?

### ISSUE THREAD

**Issue by udochrist** [jens-maus/RaspberryMatic#569]
**Describe the bug**
Default Ports in /etc/config/firewall.conf seem wrong

**To Reproduce**
see file on RaspberryMatic

**Expected behavior**
The ports for hm and hmip had been changed from 2001 and 2010 to 32001 and 32010 for xmlrpc.
yet these new ports are not listed as default in the section
```
[SERVICE XMLRPC]
Id = XMLRPC
Ports = 2000 2001 2002 2010 9292 42000 42001 42010 49292
Access = restricted
```
while the non used binrpc ports are listed. 
in order to call xmlrpc on this ports from home bridge i had to add them to the User-Defined List
despite allowing "restricted" access to the subnet of the homebridge. this seems wrong.

**Comment by hoedlmoser** [comment]
from process point of view, yes, ports have changed to 32xxx, but from application point of view they are still on 2xxx and for https on 42xxx and get proxied by lighttpd to ports 32xxx.

maybe you also want to have a look into [CCU3 - empfohlene Firewall-Einstellungen](https://homematic-forum.de/forum/viewtopic.php?f=26&t=47259&p=475481#p472997) which gives you an overview of the firewall rules used in RaspberryMatic (and CCU3).

what I think is wrong on your side, that authentication is still enabled.
authentication is done by lighttpd for non-localhost on ports 2xxx and 42xxx. with enabling ports 32xxx as user-defined ports you just bypassed the authentication.
to disable authentication just go to Einstellungen - Systemsteuerung - Sicherheit - Authentifizierung and remove the tick from Authentifizierung aktiv. maybe you need to reboot the RM afterwards.

if I'm wrong, maybe you wanna list here your iptables rules by doing command
`iptables -L -n`

**Comment by udochrist** [comment]
Thx for the fast reply. Checked the doc and looked at the screenshot. 
If i‘m not completely mistaken if taken the following from these:

if another host needs to access the ports it should go through the proxied ports (32001, 32010) instead of 2001 and 2010. the latter ones are the ones to be used internally on the ccu/raspberry if so needed. 

In this case i would expect that the 2001/2010 are not part of the firewall config but never reachable from external addresses at all whereas the 3xxxx should be opened when the firewall is set to public or restricted    - based on the clients in-adress.

**Comment by udochrist** [comment]
Sorry.  Just noticed. It’s the other way around. External applications should use the 2001 and 2010. internally they are on 32001 and 32010. so my config of homebridge ist wrong when I try to access the services using the 32001 and 32010 ports as outlined in their docu/issues

**Comment by hoedlmoser** [comment]
yes, now you got it. ;-)

**Comment by jens-maus** [comment]
Yes exactly! All 3xxxx are for internal (127.0.0.1) use only and only the original ports should be used for unencrypted XMLRPC use and the 4xxxx ports for SSL encrypted XMLRPC. BINRPC is retired for external applications. Thus, everything is correct. So this is not a bug, but a feature!
