### ISSUE TITLE
Allgemeine Verbesserungsvorschläge

### ISSUE THREAD

**Issue by FlexerJR** [jens-maus/RaspberryMatic#572]
Hallo Jens Maus, erstmal herzlichen Dank für deine Arbeit. 

Hier eine kleine Liste. 

-Neue Optik der WebUi. 
Neutral betrachtet soll HM über die WebUI nur bedienbar sein, jedoch wäre eine modernes Design angelehnt an die Homematic IP App wirklich, wirklich, wünschenswert. Darkmode zusätzlich wäre auch genial. 

-Systemvariablen Räumen und Gewerken zuordnen. 
Ich benutze Systemvariablen unter anderem für eine Alarmanlage. Es wäre klasse wenn man z. B. eine Systemvariable names Alarmanlage dem Gewerk Sicherheit zuordnen kann. 

-Schalten von Systemvariablen in der WebUI
Leider lassen sich Systemv. nicht direkt über die WebUI wie ein Gerät schalten true/false

Es sind keine dringende Änderungen aber aus meiner Sicht notwendige. Gerade in der Optik. 

Viele smarte Grüße

**Comment by Nachtfux** [comment]
Please... if the Hardware is enough for a new UI

**Comment by jens-maus** [comment]
Erst einmal sei gesagt das dies hier ein Bug und Issue Tracker ist und kein Diskussionsforum. Solche Dinge gehören IMHO erst einmal im HomeMatic-Forum diskutieret und auseinander klamüsert. Und wenn sich daraus dann separate, sinnvolle Dinge ergeben kann man das in entsprechende Enhancement Tickets verwandeln. Das hier ist aber ein solch ein allgemeines Ticket das ich damit faktisch leider nichts anfangen kann und es daher besser schliesse und darum bitte die Diskussion bzgl. dieser Dinge erst einmal im HomeMatic-Forum zu führen.

Des Weiteren sei erneut betont das RaspberryMatic OpenSource ist. Es steht also jedem Frei hier Änderungen (gerade in der oft kritisierten Optik der WebUI) vorzunehmen und dann als Änderung hier vorzuschlagen. In der Vergangenheit sind bereits mehrfach Personen auf mich zugetreten und hatten grandiose Ideen für eine komplett neue WebUI. Leider hat sich daraus nie etwas praktisch nutzbares ergeben und diese vermeintlichen "Projekte" sind immer in einer recht frühen Phase bereits abgestorben. Trotzdem bin ich natürlich auch an solchen Änderungen sehr sehr interessiert. Ich kann hier allerdings auch nicht alleine die Welt retten und Dinge in kurzer Zeit entwickeln für das eQ3 Jahre benötigt hat.

Aber auch das gehört, IMHO im HomeMatic Forum diskutiert statt hier im Bug/IssueTracker diskutiert zu werden. Das ist einfach IMHO der falsche Platz dafür.

**Comment by jens-maus** [comment]
Achja, und zu dem letzten Punkt "direktes Editieren von Systemvariablen innerhalb der WebUI" gibt es schon ein entsprechendes Ticket das auch als zukünftiges Enhancement geflaggt ist. Siehe https://github.com/jens-maus/RaspberryMatic/issues/234

Allerdings gilt auch hier: Mithilfe an der Entwicklung solcher Erweiterungen ist wie immer gewollt!
