### ISSUE TITLE
Eine Komponente der Homematic Zentrale reagiert nicht mehr.

### ISSUE THREAD

**Issue by 12-uhr-mittags** [jens-maus/RaspberryMatic#574]
Hallo,
ich mache gerade meine allererste Erfahrung mit Raspberrymatic.
Bin sehr begeistert, weil ich gleich am Start in Probleme laufe und mir die Frage stelle,
wenn das so weitergeht, ob ich da Lust drauf habe mich mit so etwas zu beschäftigen.
Bevor ich aufgebe werde ich noch ein paar Test`s machen.
Aber zu meinem Problem:
1. Ein neuer Raspi 3+ den ich im letzten jahr gekauft habe
2. Ein Homamatic funkmodul welchen ich ebenfalls im letzten Jahr gekauft habe
3. Ich habe das aktuellste Betriebssystem in dieser Woche runter geladen und mit Etcher auf eine 64G SD Karte gespielt.
4. Nachdem der erste Start Feheler gezeigt hat (Die Gleichen wie jetzt auch) habe ich das ganze nochmals neu auf die SD Karte gespielt.
5. Ich werde die SD Karte anschließend in meinen alten Raspi stecken, das Funkmodul umbauen und schauen ob das Problem immer nocht besteht.
6. Ich habe in den Foren gelesen dass diese Fehlermeldung öfter auftaucht.
7. Ich stelle mir folgende Frage: Wenn diese Fehlermeldung erscheint, dann hat sie jemand programmiert, damit sie wenn X/Y nicht ok ist, angezeigt wird. Aber ich habe keine Information gefunden wonach ich genau schauen soll.
8. Die Fehlermeldung sagt nur unspezifisch wo das Problem ist. ICh habe beim Netzteil die Spannung von 5,07V auf 5,18V hochgestellt.
Es hat nichts geändert.
9. Eine Netzwerkverbindung per Kabel besteht und arbeitet (Ich sehe das an den Lichtern des Switches)
10. Folgende Fehlermeldung:
++++++++++++++++++++++++++++++
Eine Komponente der Homematic Zentrale reagiert nicht mehr.
Hierfür kann es eine Reihe von Ursachen geben:
* es besteht keine Netzwerk-Verbindung
* die Stromversorung der HomeMatic Zentrale wurde unterbrochen
* mindestens eine Komponente der HomeMatic Zentrale ist abgestürzt
Überprüfen Sie die Netzwerk-Verbindung und die Stromversorgung der HomeMatic Zentrale. Starten Sie ggf. die HomeMatic Zentrale neu.
+++++++++++++++++++++++++++++++
(Oben im Fenster steht: "VirtualDevices") Damit kann ich auch nichts anfangen.

11. Im Log taucht die nachfolgende Meldung auf:
+++schnipp++++++++++++++++++ 
Mar 8 23:20:32 de.eq3.cbcs.vertx.management.ertxManager INFO [vert.x-eventloop-thread-6] SYSTEM: start of LocalServerAdapterInitialization succeeded (2658326f-5038-4bf9-a912-2b7959e5be6f)
Mar 8 23:20:32 de.eq3.cbcs.vertx.management.VertxManager INFO [vert.x-eventloop-thread-6] SYSTEM: start of AccessPointAuthorisationHandler succeeded (973a82df-98d1-4368-9de3-1f6737b86f36)
Mar 8 23:20:33 de.eq3.cbcs.vertx.management.VertxManager INFO [vert.x-eventloop-thread-0] SYSTEM: start of RemoteCommAdapterFinalization succeeded (583ddecd-082e-4d92-a670-b124a710ace2)
Mar 8 23:20:34 de.eq3.cbcs.lib.remotecommadapter.AccessPointCommDevice INFO [vert.x-eventloop-thread-1] SYSTEM: Started Access Point WebSocket server with port 9293
Mar 8 23:20:34 de.eq3.cbcs.lib.remotecommadapter.AccessPointCommDevice INFO [vert.x-eventloop-thread-1] SYSTEM: connector open
Mar 8 23:20:37 de.eq3.cbcs.vertx.management.VertxManager WARN [vert.x-eventloop-thread-4] SYSTEM ADVICE: pre-conditions for deployment of LocalServerFirmwareUpdateInitialization still not met - check deployment configuration (still unfulfilled: [connector.open])
Mar 8 23:20:37 de.eq3.cbcs.vertx.management.VertxManager WARN [vert.x-eventloop-thread-3] SYSTEM ADVICE: pre-conditions for deployment of LegacyAPIWorker still not met - check deployment configuration (still unfulfilled: [connector.open])
+++++++++cut#++++++++++++++++
Mar 9 18:45:46 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-7] SYSTEM ADVICE: pre-conditions for deployment of LegacyInitializion still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
Mar 9 18:45:52 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-0] SYSTEM ADVICE: long-lasting deployment, check deployment configuration - currently deployed 25 out of 31 
Mar 9 18:45:53 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-1] SYSTEM ADVICE: pre-conditions for deployment of LanRoutingWorker still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
Mar 9 18:45:53 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-4] SYSTEM ADVICE: pre-conditions for deployment of LegacyNotificationHandler still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
Mar 9 18:45:53 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-2] SYSTEM ADVICE: pre-conditions for deployment of LegacyAPIWorker still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
Mar 9 18:45:53 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-3] SYSTEM ADVICE: pre-conditions for deployment of LegacyBackendNotificationHandler still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
Mar 9 18:45:53 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-3] SYSTEM ADVICE: pre-conditions for deployment of LocalServerFirmwareUpdateInitialization still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
Mar 9 18:45:53 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-7] SYSTEM ADVICE: pre-conditions for deployment of LegacyInitializion still not met - check deployment configuration  (still unfulfilled: [connector.open])
+++++++++++++schnipp+++++++++++++++++

12. Ich habe noch nicht herausgefunden wo ich das Log löschen kann.
13. Auf dem Raspi schaltet sich der Bildschirm beim Booten ab und das System ist nur über Web erreichbar.
Ich habe noch nicht herrausgefunden wie ich auf dem Raspi ans System komme.
14. Unter Systemsteuerung / "Allgemeine Einstellungen" bekomme ich keine Anzeige. Der Hintergrund wird milchig dargestellt
14. Alles in allem sehr unbefriedigend

**Comment by jens-maus** [comment]
Erst einmal sei gesagt (und das stand auch so im Ticket Template) ist das hier KEIN Support forum sondern ein Bug/Issue Tracker für Fehler/Bugs in RaspberryMatic. Deine Meldung hier deutet aber nicht daraufhin das dies ein Problem in RaspberryMatic selbst ist der repariert werden muss sondern das ist etwas Nutzerspezifisches das eigentlich im homematic forum diskutiert gehört (siehe 
https://homematic-forum.de/forum/viewforum.php?f=65). Daher bitte alles weitere im Forum diskutieren, da sind mehr als ein Nutzer unterwegs die versuchen anderen Nutzern zu helfen.

Bzgl. des beschriebenen Problems ist leider nicht klar welche Hardware exakt eingesetzt wird. RaspberryPi3+ ist klar, Funkmodultyp aber z.B. nicht (HM-MOD-RPI-PCB oder RPI-RF-MOD). D.h. zu einer effektiven Hilfestellung muss man schon erst einmal genauer auflisten was für Hardware man denn genau einsetzt damit hier eine Hilfestellung erfolgen kann. Aber wie gesagt, am besten ist solch eine Diskussion im HomeMatic Forum aufgehoben und nicht in einem Bug/Issue Tracker in GitHub.

**Comment by 12-uhr-mittags** [comment]
Danke für die info.
Ich setze ein Funkmodul von ELV (HM-MOD-RPI-PCB)
Hatte das schon im Homematic Forum gepostet aber jemand hat mir gesagt dass es hierher gehört.
Das tut mir jetzt leid, dass ich da zu wenig Erfahrung habe und gerade etwas hin und her geschoben werde.
Beste Grüße
Michael

**Comment by jens-maus** [comment]
Kein Problem. Wenn du ein HM-MOD-RPI-PCB hast sollte in der Tat diese Fehlermeldung "VirtualDevices" nicht kommen. Hast du homematicIP (HmIP) Geräte im Einsatz?

**Comment by 12-uhr-mittags** [comment]
Hallo,
Ich habe den Raspi ausgebaut, meine Frau hat das Funkmodul untersucht und eine schlechte Lötstelle gefunden. Jetzt läuft alles ohne Fehlermeldungen. Ich habe für den Anfang zwei Silvercrest Homematic Heizungsregler die ich jetzt anlernen wollte. Leider geht es aus einem mir unbekannten Grund nicht. Vielleicht hat Funkmodul einen Schaden. Ich habe jetzt ein RPI-RF-MOD Modul bestellt und werde schauen ob es dann geht. Wenn nicht dann fällt mir erst mal nicht mehr ein.
Beste Grüße
