### ISSUE TITLE
Update auf 3.43.15.20190223 nicht möglich

### ISSUE THREAD

**Issue by terfurt** [jens-maus/RaspberryMatic#576]
Ich versuche das System von 3.41.11.20190126 auf 3.43.15.20190223 upzudaten.
![image](https://user-images.githubusercontent.com/48403482/54083415-33979800-4323-11e9-98d0-7778ad6f54e6.png)

Rassperrymatic läuft auf einem Rpi3 habe auch das korrekte *rpi3.zip File geladen bekomme aber nach dem upload die Fehlermeldung das die hoch geladenen Datei keine gültige Software enthält.
![image](https://user-images.githubusercontent.com/48403482/54083447-dc45f780-4323-11e9-9114-7aec0fc5830c.png)

Habe auch schon diverse andere Browser versucht, leider mit dem gleichen Ergebnis.
Als Addons sind installiert: 
![image](https://user-images.githubusercontent.com/48403482/54083557-34c9c480-4325-11e9-83e6-53185dd93c63.png)

Was hätte ich noch für Möglichkeiten das System auf den aktuellen Stand zu bringen?

**Comment by libertyx82** [comment]
Hast du darauf geachtet, dass das heruntergeladene ZIP File nicht entpackt wurde?
Manche Browser entpacken automatisch nach dem Download.

**Comment by terfurt** [comment]
Ja sicher, muss ja als zip File hochgeladen werden. Hab's ja auch mit Chrome,Opera und Edge versucht, leider ohne Erfolg.

**Comment by hoedlmoser** [comment]
das forum https://homematic-forum.de/forum/viewforum.php?f=65 sollte die erste anlaufstelle für unbekannte probleme sein.
vielleicht hilft Dir aber auch das kapitel Update in https://homematic-forum.de/forum/viewtopic.php?t=26917#p328057 weiter.

**Comment by terfurt** [comment]
Danke, das Forum hab ich schon durch forstet. Ich hab keine Lösung gefunden, sonst hätte ich ja auch nicht hier hin geschrieben. ;-) Möchtest du mit dem zweiten Link andeuten ich sollte ein neues Image auf die Karte schreiben, Backup zurück usw.? Ist ja nicht das erste Update welches ich einspielen möchte....
Wird mir aber anscheinend nix anderes übrig bleiben. Schade!

**Comment by jens-maus** [comment]
@terfurt Also ich vermute hier immer noch ein Problem auf deiner Seite. z.B. das das zip file entweder nicht richtig untergeladen wurde oder den RaspberryPi am Schluss nicht korrekt bzw. ganz erreicht. Generier dir mal die SHA256 Checksumme der zip Datei und vergleiche Sie mit der Checksumme die im Download-Bereich von RaspberryMatic benannt ist. Wenn diese nicht übereinstimmen kommt das Problem davon. Stimmen Sie jedoch überein dann kommt die Datei vermutlich aus irgendwelchen Gründen nicht ganz oder verstümmelt in der Zentrale an und wird deshalb als invalide Datei tituliert. Du könntest (wenn diese Fehlermeldung kommt) mal via SSH auf die Zentrale einloggen und schauen was unter `/usr/local/tmp` zu finden ist zu dem Zeitpunkt.

**Comment by terfurt** [comment]
Danke  @jens-maus der Hashwert stimmt schon mal überein!
Nachdem ich nochmal versucht habe die neue Version zu installieren und die besagte Fehlermeldung kam steht in der Datei /usr/local/tmp :
```# cd tmp
# ls
tmp.cPIiPs      tmp.cPIiPs-dir

```
Hilft das?

**Comment by jens-maus** [comment]
@terfurt Führ mal bitte statt einfachem `ls` ein `ls -la` an der stelle aus damit man auch datei Attribute sehen kann, etc.

**Comment by terfurt** [comment]
Natürlich...
Im Ordner */tmp
```# ls -la
total 194596
drwxr-xr-x    3 root     root          4096 Mar 13 22:50 .
drwxr-xr-x    7 root     root          4096 Jan 28 18:54 ..
-rw-------    1 root     root     199246586 Feb 27 21:44 tmp.cPIiPs
drwxr-xr-x    2 root     root          4096 Feb 27 21:49 tmp.cPIiPs-dir
```

und im Ordner *-dir
```total 1313760
drwxr-xr-x    2 root     root          4096 Feb 27 21:49 .
drwxr-xr-x    3 root     root          4096 Mar 13 22:50 ..
-rw-r--r--    1 root     root          2767 Feb 27 21:54 EULA.de
-rw-r--r--    1 root     root          2698 Feb 27 21:54 EULA.en
-rw-r--r--    1 root     root         11357 Feb 27 21:54 LICENSE
-rw-r--r--    1 root     root     1345249792 Feb 27 21:54 RaspberryMatic-3.43.15.20190223-rpi3.img
-rw-r--r--    1 root     root           107 Feb 27 21:54 RaspberryMatic-3.43.15.20190223-rpi3.img.sha256
```

**Comment by jens-maus** [comment]
Dann log dich mal ein und führe noch das folgende kommando aus:

sha256sum RaspberryMatic-3.43.15.20190223-rpi3.img und vergleiche die sha256 checksumme mit der in der *.sha256 datei.

**Comment by terfurt** [comment]
Sehr merkwürdig, habe nach einem Neustart weil die hmtools noch nicht richtig funktionierten, nano wurde noch nicht gestartet, wegen dem leeren tmp Ordner die zip Datei nochmal hochgeladen und siehe da...
jetzt funktioniert es!
Das war übrigens nicht der erste Neustart seit dem ich versuchte die Firmware zu aktualisieren!
Habe auch mal das Updatetool entfernt...

Trotzdem ein großes DANKESCHÖN für die Mühe!
