### ISSUE TITLE
Undeleteable devices in the devices list

### ISSUE THREAD

**Issue by cgatnet** [jens-maus/RaspberryMatic#578]
Hi, is there a possibility to delete devices from the list of devices, when they reappear after deleting? Can I get rid of them, by manually removing them from a file? (which?)
I tried it (), but there seems to be a trick? :o) 
Thanks for your thoughts, ideas and tools. :o)
best regards,
Christian

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!

**Comment by cgatnet** [comment]
Hi, danke fürs Feedback.
Ich ging eigentlich davon aus, das es sich zm ein Bug handelt, wenn Geräte nicht gelöscht werden können, daher war es für mich eine Grauzone.
War nicht böse gemeint.
Suche nur Hilfe.



---
Viele Grüße
Christian
Am 18. März 2019, 18:10 +0100 schrieb Jens Maus <notifications@github.com>:
