### ISSUE TITLE
Stromzähler Skript für Raspberymatic

### ISSUE THREAD

**Issue by Monsterberti** [jens-maus/RaspberryMatic#579]
Könnte man das an Raspberrymatic anpassen ?
https://homematic-forum.de/forum/viewtopic.php?f=31&t=12232&start=20

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jens-maus** [comment]
@Monsterberti Tut mir leid, aber das hier ist kein Diskussions/Hilfeforum sondern ein Bug/Issue Trecker. Das stand so auch im Ticket Template und daher bitte an das Forum selbst wenden und dort solche Dinge diskutieren.
