### ISSUE TITLE
"No internet connection detected" should not be an alarm (Monit)

### ISSUE THREAD

**Issue by calllib** [jens-maus/RaspberryMatic#582]
**Describe the bug**
My RaspberryMatic is **deliberately** not connected to the internet. However, since having updated to 3.45.5.20190330 I get an Alarm message "No internet connection detected".

**Expected behavior**
No alarm, no warning, unlesss user explicitely wishes to have such a warning.

**System information (please complete the following information):**
 - Version: RaspberryMatic 3.45.5.20190330
 - Hardware: RaspberryPi3B

**Additional context**
Unfortunately I cannot edit the monitrc file as this resides in a read-only filesystem.

**Comment by jens-maus** [comment]
A working internet connection is a mandatory requirement for a CCU and especially for a working HmIP interconnection. Please explain why you don‘t want your CCU to be directly connected to the internet. To me this does not make real sense.

**Comment by calllib** [comment]
HomeMatic is perhaps the last remaining home control system which does not require a cloud connection. I do not use HmIP. For security reasons I do not want this box connected to another network, and it works perfectly without. An alarm should not ring as long as everything is perfectly allright and operable without any problem.

I understand that there may be users who wish to have an Internet connection, but that is just an option.

**Comment by cgatnet** [comment]
I agree. This might be wanted by some users, but it is not an error. 
What happens, when that alarm goes off? Only a message? Seems more?

**Comment by jens-maus** [comment]
Of course it is just an informational alarm message, nothing more. However, even if I still find it somewhat paranoidic to be afraid that a CCU can access the internez itself (of course the other way around it should and is blocked) you can simply disable the monit monitoring for a working internet connection via the following command-line call:

```
monit unmonitor hasInternet
```

Just execute this after bootup (e.g. Within a WebUI program using system.Exec() or via adding this to `/usr/local/etc/rc.local`) and the monitoring for the internet connection should be disabled for you.

**Comment by calllib** [comment]
Didn't get this to work yet. Since `/usr/local/etc/rc.local` does not exist, I created that file:
`-rwxr-xr-x    1 root     root           127 Mar 30 15:38 /usr/local/etc/rc.local`
and added these lines:
`#!/bin/sh
# Disable RaspberryMatic's alarm for failing Internet connection:
monit unmonitor hasInternet

exit 0`
Running `/usr/local/etc/rc.local` does not throw any output. Looks good.

However, it seems it is not run during boot. `monit status hasInternet` after reboot shows:
`Program 'hasInternet'
  status                       Status failed
  monitoring status            Monitored
  monitoring mode              active
  on reboot                    start
  last exit value              1
  last output                  -`
and the RaspberryMatic GUI still shows the Alarm. Can you please advise?

**Comment by jens-maus** [comment]
@calllib You are right. Monit is only started **after** all init scripts are executed (including `rc.local`). Thus, you cannot use my mentioned method, but will have to wait a longer time before you actually execute the `monit unmonitor hasInternet` call. You could of course, e.g. fork a sub shell in `rc.local` and wait until monit is started and then execute `monit unmonitor hasInternet`.

**Comment by calllib** [comment]
@jens-maus But then I will probably already have the alarm in the RaspberryMatic GUI.
Would it be possible for you to remove the monitoring of 'hasInternet' in RaspberryMatic's Monit implementation as a short term measure, and then implement a GUI switch to turn this on for whoever wishes to? (With hm-watchdog we did not have this specific alarm, so nobody is used to it as of today.)
I would really appreciate this approach.

**Comment by jens-maus** [comment]
@callib: Nope, this is no option ATM. I haven't planned to add any GUI component for monit configuration as this should work for 99% of the users out-of-the-box and without any hassle and including the internet check as most of the users want this. So sorry, but you would have to add your own workaround to disable the internet check in monit. As said, I would do this with a sub shell call and if you time this precisely enough there should not be any alarm message in the WebUI as the internet check has a alarm delay of about 1 minute.

BTW: it just appears to me that the following lines in `/usr/local/etc/rc.local` should probably also solve the situation for you:

```
echo "127.0.0.1 google.com" >>/var/etc/hosts
```

With this you could actually "fake" the internet status because `/bin/checkInternet` tries to ping google.com as the first action and if this works it will generate `/var/status/hasInternet` and thus monit&co should not notice any missing internet connection.

**Comment by calllib** [comment]
Well, that would be a simple workaround but it does not work. The ping is OK:
# ping google.com
PING google.com (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: seq=0 ttl=64 time=0.372 ms
But a new alarm is still shown in the WebUI after reboot. Where can I see how you test "hasInternet"?

**Comment by jens-maus** [comment]
Well, it only checks if the file `/var/status/hasInternet` exists or not. And if not it will raise an alarm message. See here:

https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/overlay/base-raspmatic/etc/monitrc#L348

So in principle it should work to simply add google.com to the hosts file like you just did. It might be however, that you are simply to late when adding it to `/usr/local/etc/rc.local`. So please try to add the `echo` call to `/usr/local/etc/rc.init` instead. This should be executed way earlier.

**Comment by BenjaminHae** [comment]
I have also placed my RaspberryMatic in a vlan without internet access. 
Would it be a solution to create the file `/var/status/hasInternet` in `/usr/local/etc/rc.local`?

**Comment by jens-maus** [comment]
Please read all postings in this ticket and you should get the solution!

**Comment by calllib** [comment]
It seems `/usr/local/etc/rc.init` is not called at startup. (When running it manually, it works.)

**Comment by jens-maus** [comment]
It should be definitive called. Please make sure the script is an actual shell script with `#!/bin/sh` header and has executable permissions.

**Comment by calllib** [comment]
The file is:
```
-rwxr-xr-x    1 root     root           191 Mar 30 20:16 /usr/local/etc/rc.init*
```
and its content is:
```
#!/bin/sh
# Disable RaspberryMatic's Monit alarm for failing
# Internet connection by faking the test's ping destination:
echo "127.0.0.1 google.com" >>/var/etc/hosts

exit 0
```
Tried a reboot for a second. Doesn't work:
```
# ping google.com
PING google.com (172.217.21.238): 56 data bytes
```
Then I run it manually, and it works:
```
# /usr/local/etc/rc.init
# ping google.com
PING google.com (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: seq=0 ttl=64 time=0.426 ms
```

**Comment by jens-maus** [comment]
A damn it. then rc.init is too early because it is called before setting up the network connection which actually creates a fresh hosts file. Hmmm, have to think about other possibilities first.

**Comment by BenjaminHae** [comment]
One possible solution:
Testing for the existence of files like `hasInternet`in another directory that is a bind mount of `/var/status` and a `unionfs` of another directory where the user can store things he doesn't want to check (for example `/usr/local/status_override`). To disable the `hasInternet` check the user would place `hasInternet` in `/usr/local/status_override`.

**Comment by jens-maus** [comment]
@BenjaminHae Feel free to submit a PR.

**Comment by calllib** [comment]
I still think this should not be an alarm, since having a RaspberryMatic without Internet connection is perfectly alright and not alarming. Can you please change this into an "informational"message?

**Comment by jens-maus** [comment]
Nope. This is currently not possible.

**Comment by calllib** [comment]
Just noticed this was fixed after somebody had asked in German. See [#664](https://github.com/jens-maus/RaspberryMatic/issues/664). Thanks anyway.
