### ISSUE TITLE
HB-UNI-Sen-TEMP nur noch im Geräte Posteingang

### ISSUE THREAD

**Issue by Ricomat** [jens-maus/RaspberryMatic#583]
**Describe the bug**

**To Reproduce**

**Expected behavior**
ich habe das Update 3.45.5.20190330 rpi0.zip auf meinen Rasberry B+ gemacht.

Leider war danach mein wichtigstes Gerät HB-UNI-Sen-TEMP-DS18B20 mit 6 Fühlern für die Heizungssteuerung nur noch im Geräte-Posteingang.
Damit fehlen die Fühler auch in allen 6 Heizungs Programmen.
Genauso der HB-UNI-Sensor1 den ich aber nur zum Anzeigen von Wetterdaten nutze.
**Screenshots**

**System information (please complete the following information):**
 - Version 3.45.5.20190330 rpi0.zip
 - Hardware  Raspberry B+

**Additional context**
Genauso der HB-UNI-Sensor1

**Comment by jens-maus** [comment]
Bitte an den Entwickler des HB-UNI-Sen-TEMP-DS18B20 @jp112sdl wenden damit erst einmal dort versucht werden kann das Problem zu reproduzieren/analysieren. Und erst wenn dabei herauskommt das es sich um ein Problem in RaspberryMatic bitte hier ein Ticket aufmachen.

**Comment by jp112sdl** [comment]
@Ricomat kannst du noch mal das alte System starten?
**Vor** dem Update von RaspberryMatic unbedingt mein Addon V 2.0.1 installieren, dann sollte das mit dem Posteingang nicht passieren.

_Das Problem ist, dass bei der Addon-Installation die Dienste rfd und ReGaHss angehalten werden müssen. Das klappt aufgrund des neuen `monit` nicht mehr wie bisher, weshalb Anpassungen am Addon notwendig waren._

@jens-maus Ja, hier kann m.M. nach zu
