### ISSUE TITLE
keine Geräteupdates - wo kann ich den Fehler suchen?

### ISSUE THREAD

**Issue by fs-plugins** [jens-maus/RaspberryMatic#585]
nachdem ich gestern die neue Version eingespielt hatte, wunderte ich mich das länger schon  keine Geräteupdates gemeldet werden (insbesondere weil der silentmodus für Thermostate erwähnt war), das ging doch mal?
habe dann mal händisch im Netz gesucht:

HMIP-SWDO vorhanden: 1.12.1 -> verfügbar: 1.12.2
HMIP-eTRV vorhanden: 1.0.16 -> verfügbar: 2.0.2
HMIP-PSM vorhanden: 2.2.2 -> verfügbar: 2.6.2

irgendwas läuft hier verquer...
ich möchte äußerst ungern alle Geräte einzeln auf Werkszustand und wieder anmelden, um ein komplett neues System aufzusetzen - zumal ja bisher nichtmal sicher ist das ich das Provblem dann nicht mehr habe

**Comment by jens-maus** [comment]
Und was genau soll da das RaspberryMatic Projekz dran ändern? Die Gerätefirmwares werden von eQ3 entwickelt und vertrieben und auch announced und nicht vom RaspberryMatic Projekt. Ergo sollte man das dann auch eQ3 melden.

**Comment by fs-plugins** [comment]
danke für's sonntägliche Reagieren!

ich hab nach einem Fehler bei mir gesucht - nicht einen am Projekt angenommen
mir ist ja auch nicht bekannt in welcher Form das Projekt agiert, ob und wie Abrufen von evtl. Updates beeinflusst werden usw.
irgendwo muss ich ja anfangen zu fragen, hat dich getroffen  ;-)

bei eQ3 melden mach ich - halte es allerdings fast für sinnfrei (zwei unterschiedlich bestückte Quellen für Firmware mühsam zu ergogeln, kaum Reaktionen auf Fragen/Meldungen) - bekomme langsam den Eindruck dass Kundenmenge und Supportbemühen umgekehrt proportional laufen

**Comment by jens-maus** [comment]
@fs-plugins Bitte beachten das das hier kein Diskussionsforum ist sondern ein Bug/Issue Tracker. Diskussionen zu dem Thema bitte ins HomeMatic Forum auslagern. Das stand übrigens so auch im Ticket Template das einfach gelöscht wurde.
