### ISSUE TITLE
Nach Umstellung auf Sommerzeit - Aktoren schalten weiter nach Winterzeit

### ISSUE THREAD

**Issue by friedpa** [jens-maus/RaspberryMatic#586]
**Describe the bug**
Nach Umstellung auf Daylight Time reagieren alle z.B. Markisen Aktoren nach der "alten" Uhrzeit

**Expected behavior**
Umstellen auf Sommerzeit und schalten der z.B. Markisen nach der "neuen" Uhrzeit.

**System information (please complete the following information):**
 - RaspberryMatic 3.45.5.20190330]
 - Hardware RaspberryPi3

**Comment by jens-maus** [comment]
Bitte hier ein konkretes Beispiel inkl. Screenshot des WebUI Programmes liefern und detaillierte Fehlerbeschreibung liefern und morgen bitte noch einmal testen denn es kann gut sein das das Problem morgen automatisch behoben ist. Trotzdem aber eine detaillierte Fehlerbeschreibung liefern damit das ganze am Tag der Zeitumstellung noch einmal reproduziert werden kann.

**Comment by heitec11** [comment]
Habe das selbe Verhalten. Rollo soll bei Sonnenuntergang runterfahren. Laut Startseite ist dies um 20 Uhr. Trotzdem ist das Rollo bereits um 19 Uhr runtergefahren. Welches auch so geloggt wurde. Habe es dann manuel noch einmal geöffent. Programm ist um 20 Uhr nicht noch einmal getriggert worden. Habe das Rollo dann manuel wieder geschlossen.

**Comment by jens-maus** [comment]
@heitec11 Auch hier bitte mal einen Screenshot des WebUI Programmes  zeigen inkl. Detailansicht der Zeitmodul-Einstellungen.

**Comment by heitec11** [comment]
![grafik](https://user-images.githubusercontent.com/44260876/55294548-baf89880-5403-11e9-8236-4b2b4e2380e6.png)

**Comment by heitec11** [comment]
![grafik](https://user-images.githubusercontent.com/44260876/55294555-d5327680-5403-11e9-945a-f2c929167972.png)

**Comment by heitec11** [comment]
Ausgeführt wurde das Programm um:
![grafik](https://user-images.githubusercontent.com/44260876/55294591-3f4b1b80-5404-11e9-9798-e93113ecfe57.png)

**Comment by jens-maus** [comment]
@heitec11 Danke. Wärst du noch so freundlich und würdest die in der CCU eingetragenen Koordinaten mitteilen. Die brauch man zur Astrozeit-Berechnung und damit ich das entsprechend versuchen kann das damit zu reproduzieren.

**Comment by nRaecheR** [comment]
Bei mir genau dasselbe. Wir haben gestern bei strahlenden Sonnenschein plötzlich im Dunkeln gesessen, da alle Rolladen und Radffstore aktoren (HMiP-BROLL, HMiP-BRL) exakt eine Stunde zu früh herunter gefahren worden sind. Sie werden über Programme zeitvertzögert zum Sonnenuntergang automatisch herunter gefahren.
Auch ein Neustart des RPI3s hat nicht geholfen, das Gerät bestand darauf weiterhin die Programme nach Winterzeit auszuführen, obwohl die Systemzeit laut WebUI und der Zeitpunkt des Sonnenuntergangs korrekt ist.
Das ist ein echter Killer. Ich frage mich, ob ein Downgrade der Firmware auf 3.43.xxx hilft. Hier muss ein ganz schneller Fix her....

**Comment by nRaecheR** [comment]
Intereressanterweise hat die Programmierung des Sonnenaufgangs eben gerade korrekt funktioniert.

**Comment by jens-maus** [comment]
@nReacheR Dann stimmt meine Vermutung das das Problem auf den jeweiligen Tag der Zeitumstellung beschränkt ist, im besagten Fall eben der 31.3.2019 und ab dem darauffolgenden Tag es sich wieder alles eingependelt hat.

**Comment by nRaecheR** [comment]
Ich hoffe es, das es so ist. Ich werde es heute abend beobachten und berichten. Allerdings könnte es auch sein, das es gestern morgen korrekt funktioniert hat, wegen der Frühe und der Tatsache das es Sonntags war, hätte ich einen Fehler allerdings nicht mitbekommen.

**Comment by nRaecheR** [comment]
So, heute abend hat es anscheinend normal, d.h. nach Sommerzeit, geklappt. Die Rollläden und Raffstores sind erst nach 20 Uhr herunter gefahren.

**Comment by heitec11** [comment]
Kann ich ebenfalls betätigen. Heute war alles korrekt.
