### ISSUE TITLE
Option um nicht abgeholte Konfigurationsnachrichten zu löschen.

### ISSUE THREAD

**Issue by Apfelcheck** [jens-maus/RaspberryMatic#588]
**Is your feature request related to a problem? Please describe.**
Es passiert gar nicht so selten, dass aus irgendwelchen Gründen die Konfiguration eines Gerätes nicht ausgeliefert wird. Ich habe keine Ahnung warum das so ist. Dann wird das Gerät leergesaugt aber auch der Duty Cycle ist immer bei 100%. Es wäre zwar interessant zu wissen, warum das ganze passiert und diese Kondition nicht mehr zulassen aber im ersten Moment würde eine Funktionalität ausreichen, diese zu löschen.
**Describe the solution you'd like**
Im Systemmenü müsste es einen Punkt geben wo alle ausstehenden Konfigurationen (oder nur ausgewählte?) gelöscht werden.

**Describe alternatives you've considered**
Sehe ich keine. Derzeit gibt es ja nur die Möglichkeit das Gerät abzulernen und es wieder neu anzulernen.

**Additional context**
Gerne Fragen stellen, ich versuche dann noch genauer zu beschreiben (waldemar.cichon.de@gmail.com)

**Comment by HMside** [comment]
Sofern die Daten nicht übertragen werden, hast Du entweder die Config-Taste nicht betätigt, oder aber es gibt ein anderes Problem welches zu lokalisieren ist. Die Meldung der Konfigurationsdaten zu unterdrücken ist aber in jedem Fall nicht der richtige weg. Wende dich mit deinem Fall bitte einfach mal an das homematic-forum.de.

**Comment by Apfelcheck** [comment]
Hallo,

ich bin ja anscheinend nicht der einzige denn gerade dort findet man zuhauf
solche Fehler bei denen als Lösung dann schlichtweg "bitte ablernen und neu
anlernen" als Lösung steht. Es häuft sich ja nicht. Und ich habe gerade so
ein Zustand - also kann ich gerne mit Logs oder ähnlichem dienen.
Kurioserweise, wenn man neue Konfiguration schickt, wird diese ausgeliefert
(in dem Fall ist es ein Classic Wandthermostat). Vielleicht kann man die
Ursache ermitteln - ich sende gerne weitere Dateien zum debuggen -
womöglich ist die Konfigurationsnachricht defekt - irgendwo ist diese ja
persistiert, da auch ein Reset nicht hilft. Aber ich werden es in kürze
löschen, da es wahnsinnig die Batterie belastet.

Grüße

Waldemar Cichon

**Comment by jens-maus** [comment]
Bitte als erstes beachten das dies hier kein Diskussionsforum ist sondern ein Bug- und Enhancement tracker. Da es sich bei dem Issue hier aber weder um einen Bug handelt und auch das Verhalten so gewollt ist (wenn Konfigurationsdaten nicht übertragen werden können gibt es einen Grund dafür und die Meldungen sollten in keinem Falle unterdrückbar sein!) rate ich auch dazu sich bitte an das Homematic forum (https://homematic-forum.de/) zu wenden und dort zu versuchen das Problem zu diskutieren und dafür eine Lösung zu finden. Hier jedenfalls hat das IMHO nichts zu suchen.

**Comment by Apfelcheck** [comment]
Wenn ich das letzte Mal hier noch direkt antworten darf - und ja, ich werde
Euch nicht mehr stören.
Auch ich bin Entwickler und definitiv - ein solches Verhalten kann nicht
gewollt werden sondern ist ein Issue - aus meiner Sicht mindestens Major.
Eine Konfigurationsnachricht müsste nach einer gewissen Zeit, wenn sie
nicht vom aktiven Empfänger abgeholt werden kann muss auf "Error" gehe und
keinen weiteren Versuch der Abholung verursachen. Ich arbeite an einem
Projekt, wo auch viel mit Kommunikation zwischen verschiedenen Systemen
passiert. Und ein solches Verhalten, wie hier an den Tag gelegt wird, würde
da zu Schadensersatzforderungen seitens der Kunden führen. Aus meiner Sicht
müsste man doch untersuchen können, warum die Daten nicht abgeholt werden.
Aber auch solche Nachrichten löschen können - das tun de facto alle, dessen
Posts ich gelesen habe - halt nur auf dem dafür nicht vorgesehenen Weg des
Ablernens.

Sorry, dass ich da anderer Meinung bin und sorry, dass ich gestört habe -
das ist nicht ironisch, bitte nicht missverstehen.

Grüße aus Braunschweig

Waldemar Cichon

**Comment by libertyx82** [comment]
Das reine löschen einer anstehenden Konfiguration würde zu einer Divergenz zwischen der in der CCU gespeicherten Gerätekonfiguration und der tatsächlichen Konfiguration auf dem Gerät führen, daher geht um ein Ablernen nichts herum um eben genau das zu vermeiden.

**Comment by adx-git** [comment]
Die Frage ist doch dann eher wie es sein kann dass eine Konfiguration nicht am Gerät ankommt, weiter ansteht und spätere Konfigurationen problemlos geschrieben werden können. 
Da sehe ich den Bug.

**Comment by libertyx82** [comment]
Das kannst du gerne so sehen, solltest dieses dann aber mit dem verantwortlichen Hersteller diskutieren
https://www.eq-3.de/service/support.html

Ich kann mich auch nicht erinnern, jemals das Verhalten gehabt zu haben, wo eine Konfiguration anstand   die nicht übermittelt wurde und ich weitere Problemlos übertragen konnte.

**Comment by adx-git** [comment]
> Das kannst du gerne so sehen, solltest dieses dann aber mit dem verantwortlichen Hersteller diskutieren
> https://www.eq-3.de/service/support.html
Danke für die Info, ist auch wichtig zu verstehen in welchem Teil der Software das Problem liegt.
