### ISSUE TITLE
Cloudmatic Reverse Proxy dysfunctional in latest release (3.45.5.20190330)

### ISSUE THREAD

**Issue by mike-bee** [jens-maus/RaspberryMatic#589]
**Describe the bug**
1. The Cloudmatic reverse proxy service does not start automatically after (re)start of RaspberryMatic since I am using it (starting from 2.27.8.20170501).
2. Since release 3.45.5.20190330 the service does not work anymore at all.

**To Reproduce**

0. Subscribe to "Cloudmatic connect" service
1. Register a network device under "Einstellungen/Netzwerkgeräte" at cloudmatic.de
2. Click on "DIENST BEENDEN"/"DIENST STARTEN" unter "Dienste" in the WebUI of the "Cloudmatic"-AddOn (to workaround bug 1)
3. Try to access your network device over VPN using a browser link like "https://**YourCloudmaticId**.meine-homematic.de:**YourPort**" (to reproduce bug 2)
4. See error message "502 Bad Gateway, openresty/1.9.3.1"

**Expected behavior**
Secure access to your network device through the Cloudmatic VPN channel

**Screenshots**

**System information (please complete the following information):**
 - RaspberryMatic 3.45.5.20190330
 - RaspberryPi3+

**Additional context**

**Comment by jens-maus** [comment]
Can you please try to completely disable/delete the add-on and reinit it again. My current guess is, that then the reverse proxy functionality will start working again as the user directory of the add-on will then be refreshed accordingly and the correct binaries being installed so that the reverse proxy can be started again.

**Comment by mike-bee** [comment]
Sure. But can you please be a bit more specific? As Cloudmatic is integral part of the image it can't be disable/deleted via WebUI (or I simply don't know). So I guess I have to use the command line. Not being a Lunix guru I will need some support here.

**Comment by Matten-Matten** [comment]
Moin, auch ich habe das Problem. Ich hab sogar Den Cloudmatic Support via TeamV. auf meiner RM gelassen...

Auch ich werde das, was eben von J. Maus empfohlen wurde testen.

sollte aber alles nicht funktionieren hab ich vom Cloudmatic Support den Tipp bekommen wie ich
den via "root" Login manuell starten kann:
---------------------------------
im Verzeichnis:
/etc/config/addons/mh

folgendes ausführen:
./dienstanngx.sh
----------------------------------
Gruß
Matten Matten

**Comment by mike-bee** [comment]
Oops, accidentally closed.

**Comment by mike-bee** [comment]
Oops, accidentally closed.

**Comment by Matten-Matten** [comment]
@jens-maus 

bei mir hat es nicht funktioniert. 

Ich bin auf das Cloudmatic Addon gegangen habe den reiter "entfernen" ausgewählt und dann auf Daten löschen. 
Danach hab ich den Schlüssel wieder auf die RM geladen, den Reverse Proxy Dienst gestartet, aber ohne erfolg.
Auch ich habe keine Ahnung wie man das Cloudmatic Addon  vollständig löscht!?

**Comment by jens-maus** [comment]
@Matten-Matten Das kannst du tun in dem du wie folg vorgehst:

1. CloudMatic Daten alle Löschen (wie vorher)
2. Dann in der Kommandozeile folgenden Befehl ausführen: `rm -rf /etc/config/addons/mh`
3. Danach Neustarten und das CloudMatic komplett neu einrichten.

**Comment by Matten-Matten** [comment]
Ok also wird das was ich mit der Kommandozeile lösche automatisch bei einen neustart wiedergeholt?
Ich teste das.

**Comment by Matten-Matten** [comment]
ok,
`/etc/config/addons/mh` gelöscht

RM bootet gerde neu. ich habe den neustart über die Weboberfäche gemacht. ich hoffe das war richtig...

**Comment by Matten-Matten** [comment]
leider ohne Erfolg.

**Comment by mike-bee** [comment]
Same here.

**Comment by mike-bee** [comment]
Hi Jens
The issue is labeled "awaiting feedback". Is there anything you need from me (us) to resolve this one?
Thanks
MikeBee
