### ISSUE TITLE
Update auf 3.45 endet in Bootloop

### ISSUE THREAD

**Issue by Zersch87** [jens-maus/RaspberryMatic#590]
**Describe the bug**
Nach anstoßen des Updates (egal ob per WebUI oder per neuer SD Karte) startet das System einwandfrei. Sobald aber das Backup eingespielt wird gerät das System in einer Bootschleife. Dabei tritt das Problem auf egal ob per Update aus der WebUI heraus oder als neue Installation.
Das Backup an sich kann aber nicht defekt sein da ich die Version 3.43.15.20190223 auch schon Clean auf eine neue SD Karte installiert habe und danach das Backup eingespielt habe. Es lief dann wieder ohne Probleme mit der Version 3.43.15.20190223.
Ich habe auch daran gedacht das Watchdog Addon zu deinstallieren vor dem Update.

In seltenen Momenten der Neustarts bekomme ich auch eine Alarmmeldung vom Monit das die RegaHss neugestalteten wird.

**System information (please complete the following information):**
 - Version 3.43.15.20190223
 - Hardware RaspberryPi3 mit RPI-RF-MOD

**Additional context**
Ich weiß nicht wie ich an ein Error Log heran kommen soll wenn das System in einer Schleife hängt.

**Comment by jens-maus** [comment]
Am besten einfach mal Monitor+Tastatur anschliessen, dann beim hochfahren wenn das RaspberryMatic Logo kommt ALT+F2 drücken und beobachten was da beim hochfahren passiert. Ggf. kann man daraus erkennen was der Grund für den Bootloop ist.

**Comment by Zersch87** [comment]
![IMG_20190405_112746](https://user-images.githubusercontent.com/49302344/55619150-6dc84e00-5798-11e9-9c7b-245caf7b8e7c.jpg)

Also wie auf dem Bild zu sehen bootet die CCU. Danach bleibt es so wie auf dem Bild zu sehen aber die RegaHss geht in einen Dauerneustart. Die LED des RF-Mod blinken dann auch blau und rot abwechselnd.

Aus irgendeinem Grund funktionierte heute die zweite SD Karte die ich bespielt hatte problemlos. Ich hatte eigentlich nix geändert zu gestern. SD Karte eingelegt. CCU hochgefahren und jetzt läuft es. Gestern ging es nicht. Bin ein wenig konfus jetzt. Wenn du allerdings noch weiter dem Dauerneustart auf dem Grunde gehen möchtest kann ich da gerne noch weiterhelfen wenn du mir sagst was du brauchst. Ich lasse die nicht funktionierende SD Karte erst einmal auf der Seite.

**Comment by jens-maus** [comment]
Also verstehe ich das richtig, nicht der ganze RaspberryPi startete sich dauernd neu sondern lediglich ReGaHss, richtig? Wenn dem so ist muss es ja einen Grund geben warum ReGaHss abschmiert und das kann natürlich sehr gut eine defekte Konfigurationsdatei sein die auf Grund einer schwächelnden SD karte defekt gegangen ist. Wenn es jetzt mit einer anderen/neuen SD Karte geht würde ich sagen das es vmtl. daran lag. Weiter beobachten und wenn es keine Probleme mehr gibt kann dieses Ticket hier ja geschlossen werden, oder?

**Comment by Zersch87** [comment]
Hallo Jens,

Ich vermute auch das es an einer defekten SD Karte lag. Ticket kann daher
zu.


Mit freundlichen Grüßen

Simon Ehrig


Jens Maus <notifications@github.com> schrieb am Fr., 5. Apr. 2019, 11:54:
