### ISSUE TITLE
HmIP-RF not running 

### ISSUE THREAD

**Issue by Ralfs07** [jens-maus/RaspberryMatic#591]
Hallo Jens,

seit einem Gestrigen Stromausfall funktionieren die HMIP Geräte nicht mehr.
Die Gerätekommunikation aller HMIP Geräte ist gestört.

Über die Systemsteuerung DevConfig -- Service Messages kann ich folgende Meldung sehen.
HmIP-RF not running

Aus-Einshalten habe ich bereits mehrfach versucht.
Über Putty den Service gestartet bringt mir ein ok zurück /etc/init.d/./S62HMServer start
Hilft aber auch nicht.
Andere SD Karte auch nicht besser. 

Gruß
Ralf

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!

**Comment by Ralfs07** [comment]
Hallo Jens,

 

                ja ich habs gelesen. Sorry wollte kein Umstände machen.

                Ich hab mich jetzt im HomeMatic Forum angemeldet und Versuche über diesen Weg Hilfe zu bekommen.

 

Gruß

Ralf

 

 

 

Von: Jens Maus [mailto:notifications@github.com] 
Gesendet: Samstag, 6. April 2019 12:06
An: jens-maus/RaspberryMatic <RaspberryMatic@noreply.github.com>
Cc: Ralfs07 <ralf.schueller@posteo.de>; Author <author@noreply.github.com>
Betreff: Re: [jens-maus/RaspberryMatic] HmIP-RF not running (#591)

 

Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das HomeMatic Forum <https://homematic-forum.de/>  wenden! Das stand übrigens auch im Ticket Template!
