### ISSUE TITLE
Webinterface Zusatzsoftware mit Scrollbalken

### ISSUE THREAD

**Issue by VisitorSam** [jens-maus/RaspberryMatic#592]
**Describe the bug**
No Scroll Bars on "Zusatzsoftware" (Additional Plugins?)

**To Reproduce**
Install more Software, and no Scroll Bars would shown.

**Expected behavior**
Need Scrollbars for Additional Software.

**Screenshots**
![Screen](https://user-images.githubusercontent.com/49361103/55680939-b4e14b00-5920-11e9-9782-2e0977c72a05.PNG)

**System information (please complete the following information):**
 - Version: RaspberryMatic 3.45.5.20190330
 - Hardware RaspberryPi2

**Additional context**

**Comment by libertyx82** [comment]
Thats not a Bug.

Click on an Area of the "Additional Software" PopUp while you click you can slide the PopUp

**Comment by VisitorSam** [comment]
Perhaps not a bug, but could be better to put Scrollbars ;) (Like PopUp RaspiMatic Security / RaspiMatic Sicherheit)

**Comment by jens-maus** [comment]
Dieses issue sollte mit der nächsten kommenden version behoben sein.
