### ISSUE TITLE
Nach Firmwareupdate der Aktoren sind Systemvariablenverknüpfung in Webui nicht mehr sichtbar.

### ISSUE THREAD

**Issue by ThomasLoeffel** [jens-maus/RaspberryMatic#593]
**Describe the bug**
Nach dem Firmwareupdate eines Aktors sind die dem Aktor hinterlegten Systemvariablen nicht mehr im WEBUI sichtbar. Siehe Bilder im Forum: [https://homematic-forum.de/forum/viewtopic.php?f=65&t=49960&start=270#p502485](url)

**To Reproduce**
- Firmware in WEBUI hinterlegen
- Auf den Update Button drücken

Schwupp sind die verknüpften Systemvariablen nicht mehr unter "Status/Bedienung" sichtbar

**Expected behavior**
Meine Erwartung war das die verknüpften Systemvariablen unter dem Aktor in "Status/Bedienung" sichtbar sind.

**Screenshots**
Vor dem Update:
![grafik](https://user-images.githubusercontent.com/44590735/55683247-077d3000-593e-11e9-9cf3-dd254dfb6732.png)

Nach dem Update:
![grafik](https://user-images.githubusercontent.com/44590735/55683262-267bc200-593e-11e9-9ec7-239a6d742af5.png)

**System information (please complete the following information):**
 - Version [e.g. RaspberryMatic 3.45.5.20190330]
 - Hardware [TinkerboardS]

**Additional context**
Ich habe heraus gefunden das wenn man bei der Systemvariable, welche man mit dem Aktor verknüpft hat, auf bearbeiten klickt und dann ohne Änderung mit "ok" abschließt alles wieder ok ist. Somit die Anzeige im WEBUI wieder richtig anzeigt. Im Falle man hat 3 Systemvaiablen verknüpft, dann braucht man dieses nur für eine Systemvariable machen aber sichtbar sind dann alle!

**Comment by jens-maus** [comment]
Ist das mit aktuellen RaspberryMatic Versionen noch reproduzierbar?

**Comment by ThomasLoeffel** [comment]
Leider laufen derzeit keine vergleichbaren Firmware Updates. Hast Du einen Tipp wie ich den Fehler reproduzieren kann? Ansonsten kann ich es Dir nicht bestätigen.
Gruß Thomas

**Comment by ThomasLoeffel** [comment]
Hallo Jens,
ich habe das mit einem Update eines HMIP-SRH probiert (vorher HMIP-BROLL) hierbei kommt der Fehler nicht mehr vor.

Gruß Thomas
