### ISSUE TITLE
3.45.5.20190330 nicht einspielbar?

### ISSUE THREAD

**Issue by TinkyWonky** [jens-maus/RaspberryMatic#594]
**Describe the bug**
Das Release 3.45.5.20190330 kann per WebUI nicht eingespielt werden. Fehlermeldung: "Softwareupdate - Fehler: Die hochgeladene Datei enthält keine gültige Software."

**To Reproduce**
1. Release 3.43.15.20190223 verwenden.
2. Release 3.45.5.20190330 per WebUI hochladen, auf Fertigstellung des Entzippens warten.
3. WebUI meldet Fehler (s.o.).

**Expected behavior**
Erwartet wurde die Möglichkeit, die hochgeladene Datei einzuspielen.

**System information (please complete the following information):**
 - RaspberryMatic 3.43.15.20190223
 - Raspberry Pi 3 mit RPI-RF-MOD

**Comment by jens-maus** [comment]
Das kann ich leider nicht reproduzieren und scheint auch kein allgemeines Problem zu sein weil tausende andere Nutzer bereits geupdatet haben. Daher bitte neustarten, anderen browser nutzen. SHA256 Checksum über die heruntergeladene tar.gz Datei berechnen und mit der checksumme im downloadbereich vergleichen...

**Comment by TinkyWonky** [comment]
Vielen Dank für die Rückmeldung! Das Problem konnte gelöst werden, das Issue kann bitte geschlossen werden.

**Lösung:** 

Aus mir unbekannten Gründen war /usr/local/tmp vollgelaufen (/dev/mmcblk0p3). Es hielt sich dort noch ein 1.3GB großes Verzeichnis auf, in dem anscheinend Daten eines vorherigen Uploads enthalten waren. Dieser scheint aus anderen Gründen fehlgeschlagen zu sein.

**Abilfe**, falls das Problem erneut auftritt:

1. Login auf RPI per SSH (`ssh root@MeinRPI`).
2. Wechsel in das Verzeichnis, in dem hochgeladene Images landen und entpackt werden (`cd /usr/local/tmp`).
3. Probe, ob dort noch alte Dateien liegen. Ggf löschen (`rm -ri *` oder `rm -r *` falls Du _genau_ weißt, was Du da gerade löschst).
4. Neuer Upload.

**Comment by myprs** [comment]
Ich hatte hier offensichtlich im letzten Monat das gleiche Problem und konnte es beheben, indem ich heute meine Charly rebootet habe. Das benutzte tmp verzeichnis ist ja auf tmpfs gemountet und wird damit zu jedem Reboot "geleert". Ich muss allerdings zugeben, vor dem Reboot habe ich nicht auf das FS geschaut. ICh hatte aber nach meinen ersten Versuchen, das Update einzuspielen, auf ein Bugfix gewartet. Als alter Linux User ist man an die Problemlösungsstrategie "reboot" nicht so gewöhnt ;-)

Das würde dann aber auch erklären, warum der Fall hier so selten als Support-Fall auftaucht. 

Ich fände es schon technisch angebracht die tmp verzeichnisse von altem Ballast zu befreien (Stichwort "tmpreaper" o.ä.) um solche Situationen nicht mit einem Reboot lösen zu müssen. Auch nimmt die jetzige Strategie dann in Kauf, dass das Upgrade dann eine Reboot vor dem Upgrade und einen danach braucht.
