### ISSUE TITLE
unable to install addons

### ISSUE THREAD

**Issue by smindorf** [jens-maus/RaspberryMatic#60]
Hi,

I'm unable to install any kind of addon.

I tried:

- WebMatic
- Watchdog
- HQ-WebUI

but after upload nothing happend.

My System:

Raspberry PI 3
Software-Version:	2.25.15.20170114
RF: HM-MOD-RPI-PCB

Kind Regards,
Sören

**Comment by jens-maus** [comment]
Please specify what exactly happens after the installation and what should actually happen. Have you checked that the addons are definitely not there and have you tried to see if the same happens with a complete new RaspberryMatic installation?

**Comment by smindorf** [comment]
I'm  using RaspberryMatic since Sonday (it's the first time), so it is fresh, only one Actor installed.
I see the uploading in Browser (different browser, always the same), after it is finished no refresh of the site and no reboot. 
Press back and again addon, no addon are listed.
For example WebMatic:
I try to get the URL:
http://IP-of-RaspberryMartic/addons/webmatic
404 - Not Found.
Where can I check if it is uploaded?
Can I do it manually?

**Comment by jens-maus** [comment]
@smindorf First of all, this is no support forum here but a bug tracker. However, your issue seems to be that the upload of the addon didn't finish correctly and therefore RaspberryMatic doesn't reboot automatically (which it should). Also please make sure that the Addon package you downloaded is valid (make sure that your browser didn't automatically unarchive the `.tar.gz` as an Addon package *always* have to be a `.tar.gz` file compressed with gzip).

**Comment by smindorf** [comment]
@jens-maus yes I know.
Where will the package be uploaded to (so I can check the uploaded file)?
I've extract the package before I write this issue, and it seems to be valid.
Yes the file is a tarball with tar.gz extension. No automatically extraction while downloading.

**Comment by HMside** [comment]
Please tell use which addon versions your are using and try to install one of the rpi optimized addons eg https://github.com/jens-maus/cuxd/releases/latest or https://github.com/jens-maus/hm_email/releases/latest after correct upload the install button has to appears

**Comment by smindorf** [comment]
I've tried to install webmatic-2.2.3.tar.gz, hm-watchdog-0.5.tar.gz and hq_webui_2.5.4.tar.gz without success.
Now I've tried hm_email-1.6.6.tar.gz and it is installed successfully. After installing hm_email-1.6.6 successfully I tried webmatic-2.2.3 with success. I tied the other plugins with success.
Thank you very much!
