### ISSUE TITLE
Mehr Zeitzonen in WebUI

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#602]
Es sollten in der WebUI mehr verschiedene (auch seltene) Zeitzonen einstellbar sein die das Linux System prinzipiell ja unterstützt.

https://homematic-forum.de/forum/viewtopic.php?f=26&t=48583

**Comment by libertyx82** [comment]
In der Liste fehlen ja einige Einträge aber eher willkürlich, wäre es daher ggf möglich, dass diese mit Absicht weggelassen wurden?
Da z.B. das HomeMatic System in den Ländern, die in den fehlenden Zeitzonen liegen, keine Zulassung (Betriebserlaubnis) aufgrund der genutzten Frequenz besitzt?

**Comment by jens-maus** [comment]
@libertyx82 Das glaube ich weniger, sondern es wurde wohl einfach sich auf die hauptsächlichen beschränkt. Und selbst wenn, was kümmert das das RaspberryMatic Projekt :) Wir können machen was wir wollen...

**Comment by libertyx82** [comment]
War nur ein Hinweis.
