### ISSUE TITLE
Programme versagen

### ISSUE THREAD

**Issue by MathiasJZ** [jens-maus/RaspberryMatic#603]
Bei der Version 3.45.5 lassen sich einige Programme nicht mehr ausführen.
Nur zu dumm, dass es ausgerechnet das Programm der Alarmanlage erwischt hat.
Wenn ich vor der Türe stehe, um den Einbruchmelder scharf zu schalten, betätige ich den Funkhandsender HM-RC-4-3. Er leuchtet grün, aber es passiert nichts.
Wenn ich wieder in die Wohnung gehe, ist alles ok.
das heißt, der 1. Teil wenn..... wird nicht ausgeführt. der 2. Teil sonst wenn...... aber schon.
Ich bin deshalb wieder zur Version 3.41.11.20190126 zurück gegangen. nun funktioniert wieder alles.

**Comment by jens-maus** [comment]
Tut mit leid, aber hierbei kann es sich nicht um ein generelles problem handeln denn das ist der erste report seiner art und viele tausend nitzer scheinen kein problem zu haben. 

Und leider hilft es auch nicht das hier nur ganz allgemein berichtet wird das etwas nicht geht und man zurück auf eine alte version gegangen ist. Ohne eigenes logging bzw analysen bzw debugging werden wir so hier nicht weiterkommen. Wie denn auch? 

Auch ist github dazu das falsche medium. Hier sollten nur dinge gemeldet werden die definiziv und reproduzierbar ein problem beschreiben das mehr als eine Person haben und dann auch mit entsprechenden Informationen um das reproduzieren zu können.

Daher bitte entsprechend im homematic forum diskutieren und analysieren und hier erst melden wenn dort von mehreren nutzern das Problem bestätigt werden konnte.
