### ISSUE TITLE
MONIT RegaHSS

### ISSUE THREAD

**Issue by tonischabloni** [jens-maus/RaspberryMatic#604]
**Describe the bug**
Monit time is to short. Had the issue that i could not add rooms.. while loading rooms regahss restartet.. ich have a powerfull config, 200 devices, 20 rooms, etc...  
loading device list takes long. unmonitor regahass all works. please tell us where config for services is stored or change "fault" time

**Comment by jens-maus** [comment]
If monit identifies that ReGaHss has crashed it indeed crashed and changing the time will not solve this issue.

**Comment by jens-maus** [comment]
Please show the logfile entries when monit actually restarted ReGaHss so that I can identify the reason why it was restarted.

**Comment by tonischabloni** [comment]
hi jens,

here is the logfile when klicking on "Räume", same happens with Gewerke. If i do "monit unmonitor regahss" it works, nothing breakes... 
As i have huge config it takes time to load.. 
I investigated some hours to find this out.. on other systems (small installations) i dont have this issue.

`# cat messages
Apr 14 08:03:18 KOXHOM01 user.warn monit[1254]: 'ReGaHss' failed protocol test [HTTP] at [localhost]:8183 [TCP/IP] -- HTTP: Error receiving data -- Resource temporarily unavailable
Apr 14 08:03:21 KOXHOM01 daemon.warn cuxd[657]: process_rpc_request(192.168.20.24) - illegal XMLRPC(init) request
Apr 14 08:03:21 KOXHOM01 daemon.warn cuxd[657]: process_rpc_request(192.168.20.24) - illegal XMLRPC(listDevices) request
Apr 14 08:03:31 KOXHOM01 user.warn monit[1254]: 'ReGaHss' failed protocol test [HTTP] at [localhost]:8183 [TCP/IP] -- HTTP: Error receiving data -- Resource temporarily unavailable
Apr 14 08:03:44 KOXHOM01 user.err monit[1254]: 'ReGaHss' failed protocol test [HTTP] at [localhost]:8183 [TCP/IP] -- HTTP: Error receiving data -- Resource temporarily unavailable
Apr 14 08:03:44 KOXHOM01 user.info monit[1254]: 'ReGaHss' trying to restart
Apr 14 08:03:44 KOXHOM01 user.info monit[1254]: 'ReGaHss' restart: '/etc/init.d/S70ReGaHss restart'
Apr 14 08:03:50 KOXHOM01 local0.err ReGaHss: ERROR: Send failed (errno=32)! [Send():iseSysLx.cpp:1596]
Apr 14 08:03:50 KOXHOM01 local0.err ReGaHss: ERROR: Send failed (errno=32)! [Send():iseSysLx.cpp:1596]
Apr 14 08:03:50 KOXHOM01 local0.err ReGaHss: ERROR: Send failed (errno=32)! [Send():iseSysLx.cpp:1596]
Apr 14 08:03:54 KOXHOM01 user.info ReGaHss: SIGTERM: ReGaHss Halting
Apr 14 08:03:59 KOXHOM01 user.err rfd: XmlRpcClient error calling event({[methodName:"event",params:{"1009","OEQ0770027:2","BOOT",true}],[methodName:"event",params:{"1009","OEQ0770027:2","ENERGY_COUNTER",75256.200000}],[methodName:"event",params:{"1009","OEQ0770027:2","POWER",0.000000}],[methodName:"event",params:{"1009","OEQ0770027:2","CURRENT",0.000000}],[methodName:"event",params:{"1009","OEQ0770027:2","VOLTAGE",229.000000}],[methodName:"event",params:{"1009","OEQ0770027:2","FREQUENCY",50.020000}]}) on binary://127.0.0.1:31999/RPC2:
Apr 14 08:03:59 KOXHOM01 user.err rfd: XmlRpc transport error
Apr 14 08:03:59 KOXHOM01 user.err rfd: XmlRpcClient error calling event({[methodName:"event",params:{"1009","NEQ0861870:1","BOOT",false}],[methodName:"event",params:{"1009","NEQ0861870:1","ENERGY_COUNTER",485709.200000}],[methodName:"event",params:{"1009","NEQ0861870:1","POWER",820.000000}]}) on binary://127.0.0.1:31999/RPC2:
Apr 14 08:03:59 KOXHOM01 user.err rfd: XmlRpc transport error
Apr 14 08:04:00 KOXHOM01 daemon.err cuxd[657]: sendbinrpc(127.0.0.1:31999) - write() Connection refused
Apr 14 08:04:00 KOXHOM01 daemon.err cuxd[657]: sendscript(127.0.0.1:8183) connect(0s) Connection refused
Apr 14 08:04:00 KOXHOM01 daemon.err cuxd[657]: query_CCU_device_params() is NULL
Apr 14 08:04:00 KOXHOM01 daemon.err cuxd[657]: sendbinrpc(127.0.0.1:31999) - write() Connection refused
Apr 14 08:04:00 KOXHOM01 daemon.warn cuxd[657]: disable events to 127.0.0.1:31999
Apr 14 08:04:05 KOXHOM01 user.err rfd: XmlRpcClient error calling event({[methodName:"event",params:{"1009","OEQ1665726:7","DECISION_VALUE",0}]}) on binary://127.0.0.1:31999/RPC2:
Apr 14 08:04:05 KOXHOM01 user.err rfd: XmlRpc transport error
Apr 14 08:04:07 KOXHOM01 user.err rfd: XmlRpcClient error calling event({[methodName:"event",params:{"1009","OEQ0772139:2","BOOT",true}]}) on binary://127.0.0.1:31999/RPC2:
Apr 14 08:04:07 KOXHOM01 user.err rfd: XmlRpc transport error
Apr 14 08:04:07 KOXHOM01 user.err rfd: XmlRpcClient error calling event({[methodName:"event",params:{"1009","OEQ0772139:2","ENERGY_COUNTER",25920.100000}]}) on binary://127.0.0.1:31999/RPC2:
Apr 14 08:04:07 KOXHOM01 user.err rfd: XmlRpc transport error
Apr 14 08:04:07 KOXHOM01 user.err rfd: XmlRpcClient error calling event({[methodName:"event",params:{"1009","OEQ0772139:2","POWER",0.040000}]}) on binary://127.0.0.1:31999/RPC2:
Apr 14 08:04:07 KOXHOM01 user.err rfd: XmlRpc transport error
Apr 14 08:04:07 KOXHOM01 user.err rfd: XmlRpcClient error calling event({[methodName:"event",params:{"1009","OEQ0772139:2","CURRENT",0.000000}]}) on binary://127.0.0.1:31999/RPC2:
Apr 14 08:04:07 KOXHOM01 user.err rfd: XmlRpc transport error
Apr 14 08:04:07 KOXHOM01 user.err rfd: XmlRpcClient error calling event({[methodName:"event",params:{"1009","OEQ0772139:2","VOLTAGE",228.700000}]}) on binary://127.0.0.1:31999/RPC2:
Apr 14 08:04:07 KOXHOM01 user.err rfd: XmlRpc transport error
Apr 14 08:04:07 KOXHOM01 user.err rfd: XmlRpcClient error calling event({[methodName:"event",params:{"1009","OEQ0772139:2","FREQUENCY",50.020000}]}) on binary://127.0.0.1:31999/RPC2:
Apr 14 08:04:07 KOXHOM01 user.err rfd: XmlRpc transport error
Apr 14 08:04:08 KOXHOM01 user.err rfd: XmlRpcClient error calling event({[methodName:"event",params:{"1009","OEQ1676039:1","TEMPERATURE",19.400000}]}) on binary://127.0.0.1:31999/RPC2:
Apr 14 08:04:08 KOXHOM01 user.err rfd: XmlRpc transport error
Apr 14 08:04:09 KOXHOM01 user.err monit[1254]: 'ReGaHss' service restarted 1 times within 1 cycles(s) - exec
Apr 14 08:04:09 KOXHOM01 user.info monit[1254]: 'ReGaHss' exec: '/bin/triggerAlarm.tcl ReGaHss restarted WatchDog-Alarm'
Apr 14 08:04:09 KOXHOM01 user.info monit[1254]: 'ReGaHss' process is running after previous restart timeout (manually recovered?)
Apr 14 08:04:32 KOXHOM01 local0.err ReGaHss: ERROR: invalid object ID = 65535, 65535 [GetValData():iseCondition.cpp:695]
Apr 14 08:04:32 KOXHOM01 local0.err ReGaHss: ERROR: invalid object ID = 65535, 65535 [GetValData():iseCondition.cpp:695]
Apr 14 08:04:33 KOXHOM01 daemon.info cuxd[657]: INIT 'xmlrpc_bin://127.0.0.1:31999' '1481'
Apr 14 08:04:33 KOXHOM01 local0.err ReGaHss: ERROR: invalid object ID = 65535, 65535 [GetValData():iseCondition.cpp:695]
Apr 14 08:04:33 KOXHOM01 local0.err ReGaHss: ERROR: invalid object ID = 65535, 65535 [GetValData():iseCondition.cpp:695]
Apr 14 08:04:35 KOXHOM01 daemon.info cuxd[657]: setup CUX9000002:1 read(CUX-SYSTEM:0) => CUxD.CUX-SYSTEM:0 (SYSTEM) DP(|CPU10|LAVG1M|LAVG5M|LAVG15M|PROCS|CUXDMEM|MEMUSED|)
Apr 14 08:04:35 KOXHOM01 daemon.info cuxd[657]: setup CUX9000003:1 read(CUX-SYSTEM:0) => CUxD.CUX-SYSTEM:0 (SYSTEM) DP(|CPU10|LAVG1M|LAVG5M|LAVG15M|PROCS|CUXDMEM|MEMUSED|)
Apr 14 08:04:35 KOXHOM01 daemon.info cuxd[657]: setup CUX9001001:1 read(OEQ0926130:1) => BidCos-RF.OEQ0926130:1 (SHUTTER_CONTACT) DP(|STATE|ERROR|LOWBAT|INSTALL_TEST|)
Apr 14 08:04:35 KOXHOM01 daemon.info cuxd[657]: setup CUX9001002:1 read(OEQ0926154:1) => BidCos-RF.OEQ0926154:1 (SHUTTER_CONTACT) DP(|STATE|ERROR|LOWBAT|INSTALL_TEST|)
Apr 14 08:04:35 KOXHOM01 daemon.info cuxd[657]: setup CUX9001003:1 read(OEQ0421598:1) => BidCos-RF.OEQ0421598:1 (SHUTTER_CONTACT) DP(|STATE|ERROR|LOWBAT|INSTALL_TEST|)
Apr 14 08:04:35 KOXHOM01 daemon.info cuxd[657]: setup CUX9001004:1 read(OEQ0422610:1) => BidCos-RF.OEQ0422610:1 (SHUTTER_CONTACT) DP(|STATE|ERROR|LOWBAT|INSTALL_TEST|)
Apr 14 08:04:35 KOXHOM01 daemon.info cuxd[657]: setup CUX9001005:1 read(OEQ0479472:1) => BidCos-RF.OEQ0479472:1 (SWITCH) DP(|STATE|ON_TIME|INHIBIT|INSTALL_TEST|WORKING|)
Apr 14 08:04:37 KOXHOM01 user.info monit[1254]: 'ReGaHss' connection succeeded to [localhost]:8183 [TCP/IP]`

**Comment by jens-maus** [comment]
Ok, this makes sense now! Thanks for the log. So I will try to tune the timeout settings to a more appropriate value. The problem in your case is, that while trying to display your long list of devices the http port seems to be stalles and thus monit thinks that ReGaHss crashed.

**Comment by tonischabloni** [comment]
hi jens,
thanks a lot for your great work on rapsberrymatic! 
This is Issue is not really dramatic as the work around is a simpel "monit unmonitor regahss"...

**Comment by FraatRamski** [comment]
Hallo, It seems i have the same issue. Have a large setup. When I open Gewerke the window will freeze, ReGaHss reboot, .......

**3.47.22.20191130**

I would like to test with unmonitor regahss. Can you please tell me how I can do this?

P.s.: please let me know if I have to create a new issue request for this.

Fraat.

> Dec 14 14:24:40 homematic user.err rfd: HSSParameter::GetValue() id=STATE failed getting physical value.
Dec 14 14:24:40 homematic local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1007, params: {"OEQ0205843:5","STATE"}) [CallGetValue():iseXmlRpc.cpp:1435]
Dec 14 14:24:40 homematic local0.err ReGaHss: ERROR: CallGetValue failed; sVal = 0 [ReadValue():iseDOMdpHSS.cpp:124]
Dec 14 14:24:40 homematic user.err rfd: RFPhysicalDataInterfaceCommand::GetData SendFrame failed for LEVEL_GET
Dec 14 14:24:40 homematic user.err rfd: HSSParameter::GetValue() id=STATE failed getting physical value.
Dec 14 14:24:40 homematic local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1007, params: {"OEQ0205843:6","STATE"}) [CallGetValue():iseXmlRpc.cpp:1435]
Dec 14 14:24:40 homematic local0.err ReGaHss: ERROR: CallGetValue failed; sVal = 0 [ReadValue():iseDOMdpHSS.cpp:124]
Dec 14 14:24:40 homematic user.err rfd: RFPhysicalDataInterfaceCommand::GetData SendFrame failed for LEVEL_GET
Dec 14 14:24:40 homematic user.err rfd: HSSParameter::GetValue() id=STATE failed getting physical value.
Dec 14 14:24:40 homematic local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1007, params: {"OEQ0205843:7","STATE"}) [CallGetValue():iseXmlRpc.cpp:1435]
Dec 14 14:24:40 homematic local0.err ReGaHss: ERROR: CallGetValue failed; sVal = 0 [ReadValue():iseDOMdpHSS.cpp:124]
Dec 14 14:24:40 homematic user.err rfd: RFPhysicalDataInterfaceCommand::GetData SendFrame failed for LEVEL_GET
Dec 14 14:24:40 homematic user.err rfd: HSSParameter::GetValue() id=STATE failed getting physical value.
Dec 14 14:24:40 homematic local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1007, params: {"OEQ0205843:8","STATE"}) [CallGetValue():iseXmlRpc.cpp:1435]
Dec 14 14:24:40 homematic local0.err ReGaHss: ERROR: CallGetValue failed; sVal = 0 [ReadValue():iseDOMdpHSS.cpp:124]
Dec 14 14:24:46 homematic user.warn monit[1095]: 'hasUSB' status failed (1) -- no output
Dec 14 14:24:46 homematic user.err monit[1095]: Filesystem '/media/usb1' not mounted
Dec 14 14:24:46 homematic user.err monit[1095]: 'usb1' unable to read filesystem '/media/usb1' state
Dec 14 14:24:46 homematic user.info monit[1095]: 'usb1' trying to restart
Dec 14 14:25:04 homematic user.err monit[1095]: 'hasUSB' status failed (1) -- no output

Click on Gewerke:

> 

Dec 14 14:31:07 homematic user.warn monit[1095]: 'ReGaHss' failed protocol test [HTTP] at [localhost]:8183 [TCP/IP] -- HTTP: Error receiving data -- Resource temporarily unavailable
Dec 14 14:31:30 homematic user.warn monit[1095]: 'ReGaHss' failed protocol test [HTTP] at [localhost]:8183 [TCP/IP] -- HTTP: Error receiving data -- Resource temporarily unavailable
Dec 14 14:31:52 homematic user.warn monit[1095]: 'ReGaHss' failed protocol test [HTTP] at [localhost]:8183 [TCP/IP] -- HTTP: Error receiving data -- Resource temporarily unavailable
Dec 14 14:32:15 homematic user.warn monit[1095]: 'ReGaHss' failed protocol test [HTTP] at [localhost]:8183 [TCP/IP] -- HTTP: Error receiving data -- Resource temporarily unavailable
Dec 14 14:32:37 homematic local0.err ReGaHss: ERROR: Send failed (errno=32)! [Send():iseSysLx.cpp:1596]

Click on Bearbeiten in Gewerke

> 
Dec 14 14:34:29 homematic user.warn monit[1095]: 'ReGaHss' failed protocol test [HTTP] at [localhost]:8183 [TCP/IP] -- HTTP: Error receiving data -- Resource temporarily unavailable
Dec 14 14:34:52 homematic user.warn monit[1095]: 'ReGaHss' failed protocol test [HTTP] at [localhost]:8183 [TCP/IP] -- HTTP: Error receiving data -- Resource temporarily unavailable
Dec 14 14:35:15 homematic user.warn monit[1095]: 'ReGaHss' failed protocol test [HTTP] at [localhost]:8183 [TCP/IP] -- HTTP: Error receiving data -- Resource temporarily unavailable
Dec 14 14:35:38 homematic user.warn monit[1095]: 'ReGaHss' failed protocol test [HTTP] at [localhost]:8183 [TCP/IP] -- HTTP: Error receiving data -- Resource temporarily unavailable
Dec 14 14:36:01 homematic user.err monit[1095]: 'ReGaHss' failed protocol test [HTTP] at [localhost]:8183 [TCP/IP] -- HTTP: Error receiving data -- Resource temporarily unavailable
Dec 14 14:36:01 homematic user.info monit[1095]: 'ReGaHss' trying to restart
Dec 14 14:36:01 homematic user.info monit[1095]: 'ReGaHss' restart: '/etc/init.d/S70ReGaHss restart'
Dec 14 14:36:11 homematic user.info ReGaHss: SIGTERM: ReGaHss Halting
Dec 14 14:36:11 homematic local0.err ReGaHss: ERROR: Send failed (errno=32)! [Send():iseSysLx.cpp:1596]




Dec 14 14:36:16 homematic user.err rfd: XmlRpcClient error calling event({[methodName:"event",params:{"1007","KEQ0846712:1","LOWBAT",false}]}) on binary://127.0.0.1:31999/RPC2:
Dec 14 14:36:16 homematic user.err rfd: XmlRpc transport error
Dec 14 14:36:16 homematic user.err rfd: XmlRpcClient error calling event({[methodName:"event",params:{"1007","KEQ0846712:1","STATE",2}]}) on binary://127.0.0.1:31999/RPC2:
Dec 14 14:36:16 homematic user.err rfd: XmlRpc transport error
Dec 14 14:36:23 homematic user.err rfd: XmlRpcClient error calling event({[methodName:"event",params:{"1007","LEQ0639274:1","LEVEL",0.845000}],[methodName:"event",params:{"1007","LEQ0639274:1","WORKING",false}],[methodName:"event",params:{"1007","LEQ0639274:1","DIRECTION",0}]}) on binary://127.0.0.1:31999/RPC2:
Dec 14 14:36:23 homematic user.err rfd: XmlRpc transport error
Dec 14 14:36:24 homematic daemon.err cuxd[654]: sendbinrpc(127.0.0.1:31999) - write() Connection refused
Dec 14 14:36:24 homematic daemon.warn cuxd[654]: disable events to 127.0.0.1:31999
Dec 14 14:36:29 homematic user.err rfd: XmlRpcClient error calling event({[methodName:"event",params:{"1007","MEQ1848414:3","MOTION",false}]}) on binary://127.0.0.1:31999/RPC2:
Dec 14 14:36:29 homematic user.err rfd: XmlRpc transport error
Dec 14 14:36:36 homematic user.err monit[1095]: 'ReGaHss' service restarted 1 times within 1 cycles(s) - exec
Dec 14 14:36:36 homematic user.info monit[1095]: 'ReGaHss' exec: '/bin/triggerAlarm.tcl ReGaHss restarted WatchDog-Alarm'
Dec 14 14:36:36 homematic user.info monit[1095]: 'ReGaHss' process is running after previous restart timeout (manually recovered?)
Dec 14 14:36:36 homematic user.err rfd: XmlRpc transport error calling system.listMethods({"1007"}) on binary://127.0.0.1:31999/RPC2:
Dec 14 14:36:36 homematic user.err rfd: XmlRpc transport error calling listDevices({"1007"}) on binary://127.0.0.1:31999/RPC2:
Dec 14 14:36:36 homematic local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 30153, params: {"001A58A9A23DF4:4","STATE"}) [CallGetValue():iseXmlRpc.cpp:1435]
Dec 14 14:36:36 homematic local0.err ReGaHss: ERROR: CallGetValue failed; sVal = 0 [ReadValue():iseDOMdpHSS.cpp:124]
Dec 14 14:36:36 homematic local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 30153, params: {"001A58A9A23F28:4","STATE"}) [CallGetValue():iseXmlRpc.cpp:1435]
Dec 14 14:36:36 homematic local0.err ReGaHss: ERROR: CallGetValue failed; sVal = 0 [ReadValue():iseDOMdpHSS.cpp:124]
Dec 14 14:36:42 homematic user.err rfd: RFPhysicalDataInterfaceCommand::GetData SendFrame failed for LEVEL_GET
Dec 14 14:36:42 homematic user.err rfd: HSSParameter::GetValue() id=LEVEL failed getting physical value.
Dec 14 14:36:42 homematic local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1007, params: {"JEQ0107499:1","LEVEL"}) [CallGetValue():iseXmlRpc.cpp:1435]
Dec 14 14:36:42 homematic local0.err ReGaHss: ERROR: CallGetValue failed; sVal = 0.000000 [ReadValue():iseDOMdpHSS.cpp:124]
Dec 14 14:36:44 homematic user.err rfd: RFPhysicalDataInterfaceCommand::GetData SendFrame failed for LEVEL_GET
Dec 14 14:36:44 homematic user.err rfd: HSSParameter::GetValue() id=LEVEL failed getting physical value.
Dec 14 14:36:44 homematic local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1007, params: {"JEQ0031875:1","LEVEL"}) [CallGetValue():iseXmlRpc.cpp:1435]
Dec 14 14:36:44 homematic local0.err ReGaHss: ERROR: CallGetValue failed; sVal = 0.000000 [ReadValue():iseDOMdpHSS.cpp:124]
Dec 14 14:36:44 homematic local0.err ReGaHss: ERROR: ScriptRuntimeError: string incoming = dom.GetObject("RFID01-CMD").State();  if (incoming != "") {   boolean isSet = false;   string command = incoming.StrValueByIndex(";", 0);   string rfid = incoming.StrValueByIndex(";", 1);   dom.GetObject("RFID01-Last").State(rfid);   var allowed_rfids = dom.GetObject("RFID01-AllowedID").ValueList();   string allowed_rfid;   foreach(allowed_rfid, allowed_rfids.Split(";")) {          if (rfid == allowed_rfid) {       
       dom.GetObject("RFID01-CMD2").State(command);        var SprinklerAddresse="BidCos-RF.OEQ0623269:1" ;       dom.GetObject(SprinklerAddresse # ".ON_TIME").State(1);       dom.GetObject(SprinklerAddresse # ".STATE").State(true);              isSet = true;     }   } dom.GetObject("RFID01-CMD").State("");    }      [ExecError():iseESPexec.cpp:12798]
Dec 14 14:36:45 homematic local0.err ReGaHss: ERROR: incorrect data type 'Binary' (2) for content 'Trocken' [SetVar():iseDOMdpVar.h:62]
Dec 14 14:36:45 homematic user.err rfd: RFPhysicalDataInterfaceCommand::GetData SendFrame failed for LEVEL_GET
Dec 14 14:36:45 homematic user.err rfd: HSSParameter::GetValue() id=LEVEL failed getting physical value.
Dec 14 14:36:45 homematic local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1007, params: {"JEQ0030683:1","LEVEL"}) [CallGetValue():iseXmlRpc.cpp:1435]
Dec 14 14:36:45 homematic local0.err ReGaHss: ERROR: CallGetValue failed; sVal = 0.000000 [ReadValue():iseDOMdpHSS.cpp:124]
Dec 14 14:36:46 homematic daemon.info cuxd[2752]: pclose(/usr/local/addons/cuxd/curl --data "<key state="press" sender="Gabbo">PRESET_2</key>" http://10.xx.xx.x:8090/key) exit(7) 0s
Dec 14 14:36:46 homematic daemon.info cuxd[654]: INIT 'xmlrpc_bin://127.0.0.1:31999' '25078'
Dec 14 14:36:46 homematic daemon.info cuxd[2754]: pclose(/usr/local/addons/cuxd/curl --data "<key state="release" sender="Gabbo">PRESET_2</key>" http://10.xx.xx.x:8090/key) exit(7) 0s
Dec 14 14:36:48 homematic daemon.info cuxd[2756]: pclose(/usr/local/addons/cuxd/curl --data "<volume>22</volume>" http://10.xx.xx.xx:8090/volume) exit(7) 0s
Dec 14 14:36:48 homematic daemon.info cuxd[2758]: pclose(/usr/local/addons/cuxd/curl -s -k -L http://10.xx.xx.xx:8090/volume) exit(7) 0s
Dec 14 14:36:53 homematic daemon.info cuxd[2785]: system(/usr/local/addons/cuxd/curl -s -k -L "http://10.xx.xx.xx:8082/set/broadlink.0.learnedSignals.CODE_b2001e03091e0a1d1e0a0a1d0a1d0a1e1d0a0a000131091e0a1d0a1e091e0a1d0a1e091e0a1d0a1e1d0a0a1e1d0a0a1d1e090a1e1e090a1e091e0a1d1e0a0a1d0a1e091e1d0b090001310a1d0a1e091e0a1d0a1e091e0a1d0a1e091e1e090a1e1d0a0a1d1e0a0a1d1e0a091e0a1d0a1e1d0a0a1d0a1e0a1d1e0a090001310a1e091e0a1d0a1e091e0a1d0a1e091e0a1e1d0a091e1e0a091e1d0a0a1e1d0a0a1e091e091e1e0a091e0a1d0a1e1d0a0a00013
091e00131091e01e1d0b091e1d0a0a1e1d0a0a1d1e0a091e0a1e091e1d0a0a1e091e0a1d1e
a090001310a1e091e0a
Dec 14 14:36:54 homematic user.info monit[1095]: 'ReGaHss' connection succeeded to [localhost]:8183 [TCP/IP]`

**Comment by tonischabloni** [comment]
login via ssh to your rapsberrymatic

when you are logged in try

monit unmonitor regahss

thats it
