### ISSUE TITLE
Anzeige Fensterstatus fehlerhaft

### ISSUE THREAD

**Issue by alekob** [jens-maus/RaspberryMatic#606]
**Describe the bug**
Die Anzeige "Fensterstatus" ist für Gruppengeräte des Typs "HmIP-Heizungssteuerung" fehlerhaft / inkonsistent. Statt "Fenster offen" wird lediglich die Nummer "2" angezeigt

**Screenshots**
![HmIP-Heizung](https://user-images.githubusercontent.com/16241783/56094384-1df23100-5ed4-11e9-989b-37fe367a4790.jpg)

**System information (please complete the following information):**
Firmware: 3.45.5.20190330
RaspberryPi: 3B+

**Comment by mkrill** [comment]
Ich habe das Problem ebenfalls. Der Fehler scheint lediglich in Heizungsgruppen aufzutreten, in denen ein Wandthermostat HmIP-WTH oder HmIP-WTH-2 Teil der Heizungsgruppe ist.

Meine Firmware: 3.45.7.20190504
RaspberryPi: 3B

**Comment by jens-maus** [comment]
Ich kann das Problem leider nicht reproduzieren. Habe hier dafür extra auf einem Testsystem frisch einen HmIP-WITH-2 angelernt und mit 3.45.7.20190511 sehe ich folgendes in der HmIP Heizungsgruppen:

![screenshot_208](https://user-images.githubusercontent.com/5887769/57726973-9fcea900-7690-11e9-8349-5fdd6cd3e774.png)

**Comment by mkrill** [comment]
Hallo Jens,

Der Status „Geschlossen“ wird auch richtig angezeigt. Problematisch ist der Status „offen“. Statt „offen“ steht im Gruppenstatus einfach „2“.

BG,

Michael

Gesendet von meinem Smartphone

**Comment by Herbert-Testmann** [comment]
Bei meiner CCU3  mit eq-3 FW tritt der Fehler auch auf. 
Virtuelle Heizungsgruppe mit HMIP-SRH.  
Zustand "geschlossen" ist richtig.
Egal ob der Drehgriff "gekippt" oder"offen" ist, wird in der virtuellen Gruppe der Fensterstatus in der WebU mit " 2 "   angezeigt.

**Comment by alekob** [comment]
BTW: in meiner Heizungsgruppe sind lediglich HMIP-eTRV und HMIP-eTRV2 Geräte enthalten, aber kein Wandthermostat

**Comment by mkrill** [comment]
Bei mir tritt das Problem bei geöffnetem Fenster in 2 Heizungsgruppen auf:

1) Im Badezimmer mit jeweils einem HmIP-SWDO (Fensterkontakt), HmIP-eTRV (Heizungsthermostat) und HmIP-WTH-2 (Wandthermostat)
2) Im Wohnzimmer mit 3 HmIP-SRH (Drehgriffsensoren), 1 HmIP-SWDO, 3 HmIP-eTRV und einem HmIP-WTH (auch Wandthermostat) als Teil der Gruppe

Da ich auch für andere Räume Heizungsgruppen habe, das Problem dort nicht auftritt und das Besondere an diesen beiden Gruppen die Einbindung eines Wandthermostats ist, hatte ich die Vermutung, dass es daran liegt. Zugegebenermaßen passt das nicht zur Beobachtung von alekob. :-(

**Comment by alekob** [comment]
Die Gemeinsamkeit der Gruppen von mkrill & mir wäre also, dass jeweils mindestens ein HmIP-TRV verwendet wird. Kann es evtl. daran liegen?

**Comment by mkrill** [comment]
Bei meinen anderen Heizungsgruppen sind i.d.R. 1-2 Fensterkontakte und ein Heizthermostat enthalten. Dort gibt es bei mir keine Statusfehler...

**Comment by mkrill** [comment]
Mit der aktuellen Raspberrymatic-Version 3.47.10.20190713 tritt das Problem bei mir nicht mehr auf.
