### ISSUE TITLE
Rücksprung zu Ausgangszeile bei Unterdialogen

### ISSUE THREAD

**Issue by raschl68** [jens-maus/RaspberryMatic#608]
**Is your feature request related to a problem? Please describe.**
Bei Konfigurationsdialogen, wie z.B. Programme, Verknüpfungen oder Geräten erfolgt kein Rücksprung in die Ursprungszeile, aus der der Unterdialog aufgerufen wurden. Auch Filtereinstellungen sind nicht mehr aktiv.

**Describe the solution you'd like**
Beim Rücksprung aus Unterdialogen soll die ursprünglichen Filter wieder aktiv sein und in die Ursprungszeile gesprungen werden.

**Describe alternatives you've considered**

**Additional context**

**Comment by jens-maus** [comment]
Duplicate of #255 and #601
