### ISSUE TITLE
devconfig.cgi RSSI List empty

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#61]
The following command returns an empty RSSI list while the same command allows to display the current RSSI list on a standard CCU2:

```
http://homematic-raspi/tools/devconfig.cgi?cmd=show_rssi&sid=XXXXXX
```

**Comment by jens-maus** [comment]
After some short investigation the following line seems to be returning an empty result:

https://github.com/eq-3/occu/blob/master/WebUI/www/tools/devconfig.cgi#L359

Thus, on line 359 in devconfig.cgi the `rssi_list` variable seems to be empty after the xmlrpc call.

**Comment by jens-maus** [comment]
Please note that the following short tclsh script seems to work fine on a CCU2 but fails on RaspberryMatic:

```
#!/bin/tclsh
source once.tcl
loadOnce tclrpc.so
puts [xmlrpc "xmlrpc_bin://127.0.0.1:2001" rssiInfo]
```

On a CCU (within the `/www/tools` directory) it returns proper list of RSSI values, but on RaspberryMatic it returns an empty list (no RSSI values).

**Comment by jens-maus** [comment]
This problem seems to be solved with the latest 2.27.x release candidate version. Thus, closing it.

**Comment by AndynordSee** [comment]
Moin Jens 

i have the same problem 

i ran an PI3 with a HM-MOD-RPI-PCB an 2.29.23.20171118

i open : "http://192.168.xxx.xxx/tools/devconfig.cgi?cmd=show_rssi&sid=@xxxxxxxx@"

but i got only this 
"
  | <title>RSSI List</title>
-- | --
  | <body >
  | <h2>RSSI List</h2><table></body>
"

What can i do ?

**Comment by Jensilein** [comment]
Have exactly the same problem. Using the latest RaspberryMatic Version (2.31.25.20180225) but RSSI-List is empty. Maybe you can fix that? Or what else can I do?
