### ISSUE TITLE
Alarmmeldung USV (NUT) über WatchDog statt Alarmzone 1

### ISSUE THREAD

**Issue by Gerti1972** [jens-maus/RaspberryMatic#610]
Wo es jetzt die WathDog Systemvariable gibt, wäre es vielleicht sinnvoll, auch die Meldungen der USV über NUT entsprechend dem WatchDog zuzuweisen, statt der Systemvariablen Alarmzone 1. Auch wenn es eigentlich keine Meldung des WatchDog ist, passt sie hier doch deutlich besser. Soweit ich die Skripte überblicken kann, müsste die Änderung wohl in der nut_notify.sh passieren und wie folgt aussehen:

```
/bin/triggerAlarm.tcl "${UPSNAME}: ${NOTIFYTYPE}" "WatchDog-Alarm"
```

**Comment by jens-maus** [comment]
Die `nut_notify.sh` Datei ist ein reines Template die bei einer frischen installation in das Nutzerverzeichnis `/etc/config/nut` kopiert wird. D.h. jeder Nutzer kann diese Datei nach seinem Willen anpassen und dann passiert genau die Aktion die dort hinterlegt ist.

Auch wurde das Template dieser Datei bereits in der Vergangenheit abgeändert und der triggerAlarm Aufruf sieht aktuell wie folgt aus:

```
/bin/triggerAlarm.tcl "${NOTIFYTYPE}" "${UPSNAME}-Alarm"
```

D.h. es ist schon so das die Alarmmeldung für die USV nicht mehr in der allgemeinen "Alarmzone 1" passiert sondern es wird nun der Alarm in einer Variable "${UPSNAME}-Alarm" ausgelöst und diese Variable ggf. neu angelegt (siehe https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/overlay/base-raspmatic/etc/config_templates/nut/nut_notify.sh).

Aktuell sehe ich daher kein weiteren Anpassungsbedarf da jeder das machen kann wie er gerne möchte und darüberhinaus auch das default des templates schon länger nicht mehr in "Alarmzone 1" auslöst.
