### ISSUE TITLE
monit verhindert die erfolgreiche Ausführung von /bin/restoreBackup.sh

### ISSUE THREAD

**Issue by mema0007** [jens-maus/RaspberryMatic#612]
Mehre Versuche ergaben ein korruptes System und Error bei Diensten, die durch das Skript gestoppt werden sollten.

Mit "monit unmonitor all" vor der Ausführung von restoreBackup.sh läuft die Wiederherstellung wieder korrekt durch.

**Comment by roe1974** [comment]
Habe immer noch "Probleme" mit restoreBackup.sh

Diesmal kommt in der Konsole:

`Cannot create socket to [localhost]:2812 -- Connection refused
Cannot create socket to [localhost]:2812 -- Connection refused
Cannot create socket to [localhost]:2812 -- Connection refused
Cannot create socket to [localhost]:2812 -- Connection refused
Cannot create socket to [localhost]:2812 -- Connection refused
Cannot create socket to [localhost]:2812 -- Connection refused`

Muss der Port bevor das backup eingespielt wird geöffnet werden ?

lg Richard

**Comment by libertyx82** [comment]
Hast du das Web Interface das monit aktiviert? 2812 ist der standard Port des WebInterface.

**Comment by roe1974** [comment]
ja, im backup das ich einspiele, ist das Web Interface von Monit aktiviert.....

**Comment by libertyx82** [comment]
Hmm ist bei mir ebenfalls der Fall und ich hatte bis dato noch keine Probleme, ich spiele das Backup aber nicht über die Konsole sondern über die WebUI ein.

Der Port ist im Backup aber auch in der FW eingetragen?

**Comment by roe1974** [comment]
im backup ja.....
auf der „nackten  RM“ wo ich das backup einspiele via konsole war der port nicht eingetragen ....

**Comment by libertyx82** [comment]
Da das restoreBackup.sh nur alle Dienste stoppt, /usr/local bis auf temp löscht und aus dem Backup wiederherstellt und danach die Dienste startet.

Müsstest du den Port nach meinem Verständnis hier vor dem Restore in der FW eintragen, sonst ist er in der iptables ggf. geblockt.

**Comment by roe1974** [comment]
alles klar ... werde ich bei der nächsten version ausprobieren 
lg richard

**Comment by libertyx82** [comment]
@jens-maus 
Müsste in dem restoreBackup.sh nach dem Restore der Dateien nicht das libfirewall.tcl ausgeführt werden, bevor die Dienste wieder gestartet werden, damit ggf. individuelle Ports aus dem Restore in die iptables eingetragen werden?
