### ISSUE TITLE
Version 3.45.7 Backup einspielen

### ISSUE THREAD

**Issue by xmasmc** [jens-maus/RaspberryMatic#614]
Hallo,
gibt es eine Möglichkeit das Backup von einer Homematic CCU3 Version 3.45.7 in die RaspberryMatic 3.45.5 einzulesen ?
Oder ab wann wird für die RaspberryMatic die Version 3.45.7 verfügbar sein ?

**Comment by xmasmc** [comment]
Hallo,
gibt es eine Möglichkeit das Backup von einer Homematic CCU3 Version 3.45.7 in die RaspberryMatic 3.45.5 einzulesen ?
Oder ab wann wird für die RaspberryMatic die Version 3.45.7 verfügbar sein ?

**Comment by jens-maus** [comment]
Kommendes Wochenende!

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!

**Comment by xmasmc** [comment]
Sorry,
Vielen Dank über die schnelle Info
