### ISSUE TITLE
nfs mount stopped working after upgrading to 3.45.7.20190504

### ISSUE THREAD

**Issue by briearn** [jens-maus/RaspberryMatic#615]
**Describe the bug**
I upgraded to the new (above mentioned) release yesterday. That worked like a charm. However, when the system came back online again it missed its nfs mounts.
Downgrading to the 3.45.5.20190330 did not fix the issue. NFS server is reachable and I can work with the same mount points on other nodes in the same network segment still perfectly fine.

**To Reproduce**
1. Go to 'RaspMatic-Wartung'
2. Click on 'Datei hochladen'
3. let the system reboot
4. log in with root
5. execute mount -t nfs -o rw,soft,nolock 10.5.50.20:/mnt/REH /usr/local/addons/Scripts/results.nfs
6. get the error: mount: mounting 10.5.50.20:/mnt/REH on /usr/local/addons/Scripts/results.nfs failed: Connection timed out

**Expected behavior**
expected behaviour so far was to have the mount point again

**Screenshots**

**System information (please complete the following information):**
 - Version [e.g. RaspberryMatic 3.45.5.20190330; then 3.45.7.20190504 and back to 3.45.5.20190330 again]
 - Hardware [RaspberryPi3]

**Additional context**
The downgrade to the former version worked fine, but the problem remains. It probably is related to the upgraded firmware files??? 
I repeated the upgrade on the backup Pi3 and I was able to repeat the problem there after the upgrade too.

**Comment by libertyx82** [comment]
Try it with these nfs Options

mount -o soft,rw,port=2049,nolock,proto=tcp

**Comment by jens-maus** [comment]
Sorry, but this cannot be a general problem. Here mounting via NFS works without any problem like in previous versions using the following mount command:

```
mount -t nfs -o nolock,hard,intr,relatime,fsc 192.168.X.X:/volume1/XXX /mnt
```

So this must be an issue on your side only. And this is also supported by the fact that downgrading to the previous version didn't solve your issue. And the RaspberryPi firmware cannot have a negative effect on this.

**Comment by briearn** [comment]
Hi Jens&Dirk,

the problem is with the release. no matter what you try, if there was no issue before there is one now.
I narrowed it down to a fact that there is an internal application firewall running on the Pi and you set some configuration which was or was at least not that way active before. 
telnet to nfsserver's IP on port 2049 brought back a timeout before. When I moved the firewall settings in the GUI to Eingeschränkt and back to Vollzugriff again, the tings started working again.
This is the case on the primary as on the backup Pi. And this can be repeated. over and over again with each update.

I will try it again :-)

Cheers
Arne

**Comment by jens-maus** [comment]
Please check if you have a file /etc/config/wpa_supplicant.conf existing

**Comment by briearn** [comment]
checked, negative, no such file in the upgraded version. Shall I also check this on the original version?

**Comment by briearn** [comment]
just out of curiosity, the file /etc/config/firewall.conf has changed after editing it and switching it back to original. It now contains a line

USERPORTS = 

which wasn't there before...

**Comment by jens-maus** [comment]
Sorry, but I definitely cannot reproduce the problem. So please try to replicate it with the latest version and reopen this ticket if the bug still exists for you.
