### ISSUE TITLE
Feature-Request: Versionsupdates: Download optimieren

### ISSUE THREAD

**Issue by IT-VBFK** [jens-maus/RaspberryMatic#616]
**Is your feature request related to a problem? Please describe.**

Ich verwalte RM (vormals eine CCU2) zu 90% nur über VPN. Somit ist mir schon bei der CCU2 aufgefallen, dass es mehr oder weniger umständlich ist, ein Update auf die CCU zu übertragen. (Download des Updates auf den Rechner (lokal) --> Upload des Updates auf die CCU/RM). Mein Problem hierbei ist nicht der Download, sondern der anschließende Upload (über VPN mit (zugegeben) eher schlechter Uploadgeschwindigkeit). 

**Describe the solution you'd like**
Es wäre doch eine sinnvolle Ergänzung (von mir aus auch nur optional), dass der ganze Upload-/Downloadprozess quasi nur ein Klick auf "Herunterladen" ist, dann der Download direkt auf den RPi (schon in das richtige Verzeichnis) ausgeführt wird und nur eine Mitteilung gesendet wird, dass das neue Update auf einen Neustart wartet. Im Endeffekt spart das Bandbreite.

VT: 
Man wäre nicht von ständiger Internetverbindung abhängig,

**Describe alternatives you've considered**

**Additional context**

Ansonsten bin ich sehr zufrieden mit der Arbeit die hier geleistet wird! 
Herzlichen Dank dafür

LG Lukas

**Comment by jens-maus** [comment]
Hier der Hinweis das upstream mit der kommenden 3.55.x version entschieden hat solch ein Feature zum automatischen Download the aktuellen Version über die Zentrale selbst umzusetzen. Und da diese version bereits auf unserem master branch ist werde ich dieses Ticket hier entsprechend schließen und für die Integration in die nächste offizielle Version vorsehen.

**Comment by IT-VBFK** [comment]
Das ist eine super Nachricht!
Danke
