### ISSUE TITLE
WebUI Filter  

### ISSUE THREAD

**Issue by HM-klana** [jens-maus/RaspberryMatic#617]
**Describe the bug**
Bei den neuen Filtern sind mir ein paar Sachen aufgefallen, welche in 3 verschiedenen Teilen vorkommen (siehe Beschreibung "Filter 1 - 3").

In der Zusammenfassung sind das: 
- Rückkehr zur Ausgangsseite mit dem gesetzten Filter nicht möglich
- Filter verliert die Farbe "Rot", obwohl gesetzt.  

**Filter 1:**
1. Auswählen Button "Status und Bedienung"
2. Auswählen Menüpunkt "Geräte"
3. Filter setzen - Anzeige Filter ist jetzt rot
4. Irgend ein Gerät anklicken - Anzeige Filter ist jetzt wieder schwarz (Filter ist aber weiter gesetzt)

**Filter 2:**
1. Button "Einstellungen" Menü "Gewerke"
2. setzen eine Filters 
3. In den gefilterten Geräten rechts ( in Spalte "Verknüpfungen")  auswählen des Buttons "Programme"
4. es werden die Programm angezeigt in denen das Gerät genutzt wird.
5. wenn jetzt der Button "Zurück" ausgewählt wird, landet man nicht in der Gewerkeübersicht mit dem gesetzten Filter, sondern auf der WebUI Startseite.
6. bei Auswahl des Button "Direkte" (in der Spalte "Verknüpfungen") kommt man wieder zu den Gewerken mit dem gesetzten Filter zurück - OK

**Filter 3:**
1. Auswählen Button "Einstellungen" - Menü Systemvariablen
2. Filter setzen in der Spalte Variablentyp z.B. "Alarm"
3. jetzt rechts den Button "Programme" anklicken
4. Wenn die zugehörigen Programme angezeigt werden, dann auf den Button "Zurück" klicken
5. Es werden wieder alle Systemvariablen angezeigt - Filter nicht mehr gesetzt
   Andere Spalten sind OK

**To Reproduce**
Siehe unter der Beschreibung des Fehlers.

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
RaspberryMatic 3.45.7.20190504
TinkerboardS

**Additional context**

**Comment by jens-maus** [comment]
@psi-4ward Könntest du dich dem Ticket bitte annehmen und ggf. noch Anpassungen an den Stickt-Filtern nachliefern? Wäre super. Danke!

**Comment by Hypnos3** [comment]
@jens-maus: Die Antwort von psi kann etwas dauern. Er ist aktuell in seinem wohl verdienten Urlaub (für 2 Wochen).

**Comment by psi-4ward** [comment]
Hi,
ich kann mich in den kommenden zwei Wochen leider nicht drum kümmern, danach werde ich es hoch priorisieren.

Greets

**Comment by jens-maus** [comment]
@psi-4ward Alles klar, dann assigne ich die Tickets zu dir damit du die nicht vergisst :9 Danke und dir noch nen ruhigen Urlaub :)

**Comment by psi-4ward** [comment]
**Zu Filter 1:** Ich pushe einen Fix.

**Zu Filter 2:** Dies war schon immer so und hat nichts mit den Filtern zu tun. 

Siehe: 
```javascript
loadProgramList = function(filter)
{
  doClearTempView = true;
  if( typeof filter == "string" )
  {
    conInfo("loadProgramList: Filter = ["+filter+"]");
    updateContent("/pages/tabs/admin/views/programlist.htm", "", 'system.SetSessionVar("sessionPrgIsFiltered", true);system.SetSessionVar("sessionPrgFilter","'+filter+'");' );
  }
  else
  {
    updateContent("/pages/tabs/admin/views/programlist.htm");
  }
};
```
Hier wird die previousPage nicht gesetzt da der Aufruf nicht über `WebUI.enter()` vollzogen wird.

**Zu Filter 3:** Leider wird hier wieder ein anderen Filtermechanismus für die Checkboxen verwendet. Dieser ist in der aktuellen Ausbaustufe _noch_ nicht enthalten.

**Comment by psi-4ward** [comment]
Wenn ich das richtig überblicke ist "nur" noch der Support für Checkbox- und Radio-Filter offen richtig?

**Comment by jens-maus** [comment]
This ticket has been closed because of inactivity of the ticket owner and due to the fact that no developer could reproduce the issue. Please reopen the ticket once it can be reproduced again or the ticket owner can reply accordingly.
