### ISSUE TITLE
WebUI Fenster Benutzerkonto / Konfiguration 

### ISSUE THREAD

**Issue by HM-klana** [jens-maus/RaspberryMatic#618]
**Is your feature request related to a problem? Please describe.**
Das Fenster, welches bei Auswahl von Benutzerkonto / Konfiguration erscheint, ist immer gleich groß und nicht anpassbar.

**Describe the solution you'd like**
Da hier auch die Benutzervariablen eingestellt werden, wäre es schön wenn man das Fenster 
anpassen könnte. So muss man immer scrollen.
<img width="2105" alt="1  Fenster Benutzerkonto Konfiguration nicht änderbar" src="https://user-images.githubusercontent.com/50288602/57196265-84122700-6f5b-11e9-90f3-9d2dfe62d373.png">
<img width="2108" alt="2  Fenster Benutzerkonto Konfiguration nicht änderbar" src="https://user-images.githubusercontent.com/50288602/57196266-84122700-6f5b-11e9-8715-8a81efe75936.png">

 

**Describe alternatives you've considered**

**Additional context**

**Comment by jens-maus** [comment]
Das Problem kann ich hier leider nicht reproduzieren (zumindest mit Chrome). D.h. hier ist das Fenster zwar auch immer gleich groß, allerdings muss ich hier nie in irgendeiner weise horizontal scrollen sondern es ist eigentlich immer ausreichend groß um den darin enthaltenen Text darzustellen.

**Comment by libertyx82** [comment]
Das passiert, wenn man eine SV des Typs "Werteliste" mit einer langen Liste an Werten hinzufügt.

**Comment by jens-maus** [comment]
Dann bitte mal ein Beispiel einer solchen SysVar mit langer Warteliste zeigen...

**Comment by libertyx82** [comment]
Sorry hab versehentlich auf "comment" gedrückt und der Anhang fehlte noch.

Bei der SV "Alarm-Modus" passiert das nicht, da wird die Zeile nach einem "-" umgebrochen.

**Comment by HM-klana** [comment]
Stimmt, ich habe auch lange Wertelisten
![ScreenHunter_21 May  07 15 12](https://user-images.githubusercontent.com/50288602/57302160-d7f74a00-70da-11e9-8fb9-fba55db76479.jpg)

**Comment by jens-maus** [comment]
Das Problem sollte mit der 3.55.5.20201226 bereits gelöst sein.
