### ISSUE TITLE
Support PiModules UPS PIco HV3.0A Stack with 450mAh Battery

### ISSUE THREAD

**Issue by renne** [jens-maus/RaspberryMatic#62]
The [PiModules UPS PIco HV3.0A Stack with 450mAh Battery](http://www.pimodules.com/_pdf/UPS%20PIco%20HV3.0A_Prospectus.pdf) is a **30,- €** Uninterruptable-Power-Supply-Hat for the Raspberry Pi.

It supports the following features:
- Raspberry Pi B+ HAT Compliant
- Plug and Play
- **Smart Uninterruptible Power Supply** (UPS)
- Integrated LiPO Battery (8-10 Minutes of Power Back-Up)
- Intelligent Automatic Charger
- No Additional External Power Required
- Optional 3000 mAh Battery for 8 Hours Run-Time (Not Included)
- 5V 2A Power Backup (Peak Output 5V 3A)
- **Integrated Software Simulated Real Time Clock (RTC) with Battery Back-Up**
- File Safe Shutdown Functionality
- Raspberry Pi B+ Activity Pin
- PWM fan control (Fan Not Included)
- 2 User Defined LEDs
- 2 User Defined Buttons
- Integrated Buzzer for UPS and User Applications
- Status Monitoring - Powering Voltage, UPS Battery Voltage and Temperature
- I2C PICo Interface for Control and Monitoring
- RS232 Raspberry Pi Interface for Control and Monitoring
- XTEA Based Cryptography User Software Protection
- **2 Level Watch-dog Functionality with FSSD and Hardware Reset**
- Raspberry Pi B+ Hardware Reset Button via Spring Test Pin
- **Stackable Header for Add-On Boards**
- Boot Loader for Live Firmware Update
- Compatible with Intelligent IR Remote Power ON/OFF (PowerMyPi)
- Integrated ESD-Protected 2 Channel A/D 10 Bit Converters 0-5.2V
- Integrated ESD-Protected 1-Wire Interface
- Labeled J8 Raspberry Pi B+ GPIO Pins for Easy Plug & Play
- Infra Red Receiver Sensor Interface (IR Not Included)
- Upgradable with PIco Add-on Boards
- Fits Inside Most Existing Cases

Please support this RPi-Hat in RaspberryMatic! :-)

**Comment by jens-maus** [comment]
Thanks for this nice suggestion in supporting this UPS HAT for a RaspberryPi. So please feel free to donate this type of HAT and send it over to me so that I can work on integrating support for it :)

**Comment by renne** [comment]
What's the current state?

**Comment by jens-maus** [comment]
@renne The RTC clock should be supported in beta5. However, for the other UPS functions I am afraid, but the software for the software watchdog (FSSD) that is supplied with this HAT is largely based on python modules while python isn't supplied with RaspberryMatic. Thus this would require to create a dedicated CCU Addon which adds support for all the detailed UPS functions this HAT provides.

**Comment by renne** [comment]
@jens-maus 
Should the RTC work out of the box or do I need to configure something in RaspberryMatic?

If I understand correctly the Pi has to send pulse trains to GPIO 22 (watchdog function). On a power-down event the UPS switches GPIO 27 from high to low.

The UPS is available at [Rasppishop](https://www.rasppishop.de/UPS-PICO-HV30A-TopEnd-USV-fuer-Raspberry-Pi), now.

**Comment by jens-maus** [comment]
@renne As you know, I have such a model here, but haven't had a lot of time to test it deeply. But indeed, the RTC should work out-of-the-box with beta5 and later. Have you tested it? However, for all the other support of the hardware including the watchdog function we would require more deep modifications of the system. For this, however, I would (as I said) prefer that someone (I simply lack the time) integrates the required changes in a dedicated CCU Addon package which users with this particular UPS system can install.

**Comment by renne** [comment]
The RTC works! I wrote a ASH-script which triggers the watchdog on the Pico UPS and queries for power-loss events via GPIO 22/27. It has no error-handling, yet and lacks all the I²C-features but works. It seems the Pico UPS activates the RTC when the watchdog-triggering/power-state querying starts. ;-)

**Comment by jens-maus** [comment]
@renne This sound great. Can you please provide your ash script so that I might investigate it and see if I can actually integrate something like this directly in RaspberryMatic or for reference for other Pico UPS users.

**Comment by renne** [comment]
@jens-maus I just created a fork of RaspberryMatic. In which directory do you want the script?

**Comment by jens-maus** [comment]
@renne You don't need to create a fork because I probably won't integrate it directly as said before. I just want to have a quick look over it to see what it actually does and how and then see what might be the next step to take.

**Comment by renne** [comment]
[filesave-shutdown.txt](https://github.com/jens-maus/RaspberryMatic/files/907748/filesave-shutdown.txt)

**Comment by jens-maus** [comment]
Thanks, I just inlined your script here instead providing it as an attachment so that it can be immediately be viewed. Also please provide information how and when are you starting this script during boot up.

**Comment by renne** [comment]
I haven't started it on boot, yet, but only manually. As it only depends on the Linux-kernel it should be possible to start it whenever you want if the Pico UPS is up and running. I suggest to start it at least before the RTC initialization an make sure only one instance is running at the same time.

**Comment by jens-maus** [comment]
Thanks, however, I am still not sure if we should really directly integrate it into RaspberryMatic for all users. 99% of the users won't have a Pico UPS and yet I don't see that the script tries to detect the UPS and just start its while loop if the UPS is installed. Thus, I currently think it wouldn't be wise to actually start this script for all users automatically.

**Comment by renne** [comment]
You can create an init-script which starts the script as a daemon. If the init-script is NOT enbabled by default users without a Pico UPS are not affected while users with a Pico UPS need only one command to activate it. ;-)

**Comment by jens-maus** [comment]
Of course this would be possible. However, I would actually prefer to automatically identify if a Pico UPS system is installed. There have to be a way to identify if a working Pico UPS system is installed on the GPIO of the RaspberryPi!?!?

**Comment by renne** [comment]
I haven't found a way, yet. But I just found https://github.com/ef-gy/rpi-ups-pico :-) :-)

**Comment by renne** [comment]
You can check for a UPS Pico with `i2cget -y 1 0x69 0x26 b`. It returns the current firmware version (exit status 0) or an error (exit status e.g. 2). The daemon seems to have a bug with firmware version 0x30. I already opened an issue.

**Comment by jens-maus** [comment]
Thanks for the hint and reference to the `picod` issue. So please let me know as soon as picod works fine for you so that I can start working on integration into a future RaspberryMatic version.

**Comment by jyujin** [comment]
Heh, just saw the shoutout there for the daemon. I'll see about fixing those issues @renne opened against it - haven't quite seen most of them on my Pi, but I assume most of that is that I haven't updated the firmware on the pico in quite a bit :).

**Comment by johnwlawrence88** [comment]
Hello, what is the purpose of the watchdog? could it be used to reset the pi if a python script fails ?
