### ISSUE TITLE
New lighttpd response headers break device firmware update checks

### ISSUE THREAD

**Issue by hobbyquaker** [jens-maus/RaspberryMatic#620]
`Refused to load the script 'https://ccu3-update.homematic.com:8443/firmware/api/firmware/search/DEVICE?ts=1557084332747' because it violates the following Content Security Policy directive: "script-src 'unsafe-inline' 'unsafe-eval' 'self' *.homematic.com https://gitcdn.xyz ". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

**Comment by libertyx82** [comment]
I have a similar problem by accessing the webui over a reverse proxy

> Refused to load the script 'https://ajax.cloudflare.com/cdn-cgi/scripts/a2bd7673/cloudflare-static/rocket-loader.min.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-inline' 'unsafe-eval' 'self' *.homematic.com https://gitcdn.xyz ". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
