### ISSUE TITLE
WebUi Filter: Verschachtelungsfehler

### ISSUE THREAD

**Issue by OnkelTommy** [jens-maus/RaspberryMatic#621]
**Describe the bug**
Filter setzt sich selbst auf anderen Filter um

**To Reproduce**
1. z.B. Programme editieren, z.B. eine SV etc hinzufügen
2. Filter setzen in Programmliste auf z.B. XYZ - Filter zeigt Programme mit XYZ
3. Programm öffnen, darin eine SV hinzufügen - es öffnet die Auswahlliste für die SVs
4. Diese Liste erneut filtern, z.B. auf SVs mit Text "ABC"
6. Filter wird rot, die SVs werden angezeigt- SV wählen und wieder ins Programm zurück.
7. Programmbearbeitung schliessen (nach SV Auswahl kann man Filter nicht mehr löschen)
8. Mit "OK" Programm verlassen
9. Nun wird aber der Sucheintrag "ABC" in den ersten Filter geschrieben und somit ist dann
    die Programmliste leer. Der Filter bleibt (rot) gesetzt, aber statt XYZ steht nun ABC drinnen.

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
 - RaspberryMatic 3.45.7.20190504
 - TinkerboardS

**Additional context**

**Comment by jens-maus** [comment]
@psi-4ward Kannst du dich bitte auch um dieses Ticket kümmern? Danke!

**Comment by psi-4ward** [comment]
Oh, das ist etwas schwierig. In der WebUI gibt es ein paar verschiedene "Filtertechniken", wird die selbe "Technik" auf verschiedenen Seiten angewandt wird das eigentlich durch Konstanten unterschieden. In diesem Fall wird wohl die Selbe für zwei Listen genutzt. Löschen sollte er sich aber schon lassen.

Schau mir auch dieses Thema in ca 2 Wochen noch mal genauer an.

**Comment by OnkelTommy** [comment]
Ja, löschen geht.
Eine "Kleinigkeit" ist mir auch noch aufgefallen:

Ich setze den Filter bei Programmen, editiere eines, erweitere dieses um Funktionen etc, bestätige mit OK- dann ist der Filter gelöscht und der Text nicht mehr rot.....und man sieht die ganze Programmliste wieder

viele Grüße und Danke !  Thomas
