### ISSUE TITLE
Anzeige der Geräte nach Aktion in WebUI doppelt

### ISSUE THREAD

**Issue by HM-klana** [jens-maus/RaspberryMatic#623]
**Describe the bug**
In der WebUI wird unter dem Button "Status und Bedienung" / Menü "Geräte" nach Betätigung einer Geräteaktion die Anzeige doppelt (falsch) dargestellt.

**To Reproduce**
1. Auswählen Button "Status und Bedienung" in der WebUI
2. dann auswählen Button "Geräte"
3. ein Gerät auswählen, bei dem Einstellungen möglich sind (z.B. Heizkörperthermostat HM-CC-RT-DN oder Schaltaktor HM-LC-Sw4-WM oder Fernbedienung HM-RC-8 usw.)
4. jetzt eine Aktion auswählen (z.B. Temperatur erhöhen o.ä.)
5. die Anzeige verdoppelt sich (siehe Screenshots)

 
**Expected behavior**

**Screenshots**

**Anzeige normal**
<img width="2560" alt="1_HM-CC-RT-DN_Anzeige_Normal" src="https://user-images.githubusercontent.com/50288602/57241877-51872d80-7032-11e9-9ecf-ae3d875b0981.png">

**Anzeige nach Aktion**
<img width="2560" alt="2_HM-CC-RT-DN_Anzeige_Nach_Aktion" src="https://user-images.githubusercontent.com/50288602/57241879-521fc400-7032-11e9-997b-f4fdc5711799.png">

**Anzeige normal**
<img width="2560" alt="1_HM-LC-Sw4-WM _ Anzeige normal" src="https://user-images.githubusercontent.com/50288602/57241878-521fc400-7032-11e9-8c8b-96f7bdaa4140.png">

**Anzeige nach Aktion**
<img width="2560" alt="2_HM-LC-Sw4-WM_Anzeige_Nach_Aktion " src="https://user-images.githubusercontent.com/50288602/57241880-521fc400-7032-11e9-9515-68385472acb4.png">

**Anzeige normal**
<img width="2560" alt="3_HM-RC-8_Anzeige_Normal" src="https://user-images.githubusercontent.com/50288602/57242101-e427cc80-7032-11e9-9539-5988e6421bcd.png">

**Anzeige nach Aktion**
<img width="2560" alt="4_HM-RC-8_Anzeige_Nach_Aktion" src="https://user-images.githubusercontent.com/50288602/57242102-e427cc80-7032-11e9-8d06-7d5c23f54865.png">

**System information (please complete the following information):**
- RaspberryMatic 3.45.7.20190504
- ASUS TinkerBoard S

**Additional context**

**Comment by libertyx82** [comment]
Kann ich nicht Reproduzieren und sieht auch sehr nach Browser Cache aus.

Also Browser Cache löschen und an besten währenddessen die CCU neu starten.

**Comment by IT-VBFK** [comment]
> sieht auch sehr nach Browser Cache aus.

Obwohl das ja eigentlich nicht mehr stören dürfte..

**Comment by jens-maus** [comment]
Das ist in der Tat einer der "Klassiker" und immer wieder gerne reporteten Probleme in der WebUI. Hat nicht direkt was mit Browser Cache zu tun, sondern passiert unter gewissen Laufzeit-Bedingungen in der WebUI das diese aus unerklärlichen Gründen manche Elemente verdoppelt. Leider ist mir bis dato noch kein Fall bekannt der absolut und immer wieder nach einem Neustart der Zentrale/Webbrowser das ganze reproduzieren lässt. Insofern wüsste ich momentan nicht wie ich dem Problem auf dich schliche kommen könnte...

**Comment by libertyx82** [comment]
Also wenn es bei mir auftritt, hat es sich bis jetzt immer durch einen reboot und gleichzeitigem löschen des Cache und Cockie beseitigen lassen.

**Comment by HM-klana** [comment]
Hi,
Browsercache hatte ich als erstes gelöscht und Browser neu gestartet.
Könnte es evtl. am Fernzugang per Cloudmatic Connect liegen, dass dort noch was gespeichert wird?

**Comment by HM-klana** [comment]
Gerade nochmal den Browesercache gelöscht und von Cloudmatic ab und wieder angemeldet.
Browser neu gestartet und neu an RM angemeldet.
Problem besteht weiterhin.
Reboot möchte ich erst am Donnerstag wenn ich Vorort bin machen.

**Comment by OnkelTommy** [comment]
Kenne ich auch, kommt seeeeelten vor, aber Reboot half da meistens, eventuell auch 2x reboot warum auch immer

**Comment by jens-maus** [comment]
@OnkelTommy Genau so sind auch meine Erfahrungen. Wenn also jemand einen reproduzierbaren Fall hinbekommt der mich das in jedem falle reproduzieren lässt hätte ich einen Ansatzpunkt um ggf. das zu Debuggen. Aber so mit "geht mal, geht mal nicht" hilft das leider nicht wirklich weiter...

**Comment by HM-klana** [comment]
Hallo Jens,

ich hatte keine Ruhe und habe jetzt 2 x Reboot durchgeführt.
Nach dem ersten Mal war das Problem noch vorhanden, nach dem 2. Reboot ist es jetzt weg.
Kannst also dieses Issue zumachen.
Sorry für die Aufregung!
Gruß
Klana

**Comment by jens-maus** [comment]
Nein, lass es offen. Das Problem existiert ja noch prinzipiell, ist aber eben nur schwer zu fassen. Normal sollte es eben nicht auftreten und noch habe ich nicht rausbekommen was das genau triggert.

**Comment by HM-klana** [comment]
Ok

**Comment by rene-gates** [comment]
Seit dem Update auf Version 3.45.7.20190511 tritt das Problem auch erstmals bei mir auf. 
Ich habe mal die Ajax Requests geprüft und soweit feststellen können, dass der Aufruf der "datapointconfigurator.htm" die Control Elemente doppelt zurückliefert. Vielleicht kann dies bei der Suche nach der Ursache helfen. Screenshot habe ich angehängt.

![Unbenannt](https://user-images.githubusercontent.com/20499623/58340451-2ed78000-7e4c-11e9-9e6e-90b28d8a898c.JPG)

**Comment by jens-maus** [comment]
@rene-gates Guter Hinweis! Jetzt muss man nur noch rausfinden unter welchen Bedingungen das passiert und wie man das reproduzierbar hinbekommt um das Problem dann fassen zu können. Ich vermute ein Runtime Problem wo durch Laufzeitprobleme die generierenden Routinen doppelt aufgerufen werden. Die Frage ist nur "warum"?!?

**Comment by rene-gates** [comment]
@jens-maus Ich beobachte es mal. Wenn du mir sagst wie ich - wenn's wieder auftritt - dir am Besten weitere Infos raussuchen kann, würde ich schaun ob ich dir so weiterhelfen kann.

**Comment by jens-maus** [comment]
Gibt es schon neuere Erkenntnisse hier? Hat schon jemand einen reproduzierbaren fall gesehen, wahrgenommen? Ich denke immer noch ein eine race-condition und wüsste aktuell nicht wie man das verhindern könnte das die WebUI in solchen fällen dann die bedienelemente fälschlicherweise mehrmals darstellt...
