### ISSUE TITLE
Extierende /etc/config/wpa_supplicant.conf lässt watchdog wlan0 interface aktivieren

### ISSUE THREAD

**Issue by Andreas0211** [jens-maus/RaspberryMatic#624]
**Describe the bug**
Seit RM Version 3.45.7.20190504 funktioniert bei mir die Auflösung von DNS-Namen im Heimnetz nicht mehr. Ich nutze die AddOns HM-pdetect und System-Update. HM-pdetect war so konfiguriert, dass es mit den FRITZ! Hostnamen: fritz.box und fritz.repeater kommuniziert. Diese Verbindung war nach dem Update auf RM 3.45.7.20190504 nicht mehr möglich. Nach Eintragen der konkreten IP-Adressen funktioniert es wieder.
Beim Aufrufen des Addons System-Update bekomme ich die Fehlermeldung "BAD GATEWAY".

Zurück in der Paspberrymatic-Systemsteuerung unter Zusatzsoftware erscheint bei sämtlichen Addons unter "verfügbare Version" lediglich der Hinweis: "n/a", vermutlich auch aufgrund einer inkorrekten Namensauflösung.

**System information (please complete the following information):**
 - Version RaspberryMatic 3.45.7.20190504 on Raspberry Pie 3 B

**Comment by jens-maus** [comment]
Bitte mal via SSH einloggen und die Ausgaben folgender Kommandos hier posten:

```
cat /etc/config/netconfig
```

```
cat /etc/resolv.conf
```

```
route -n
```

```
ifconfig -a
```

```
ls -la /etc/config/wpa_supplicant.conf
```

**Comment by Andreas0211** [comment]
# cat /etc/config/netconfig                                                                                                
HOSTNAME=homematic-ccu2                                                                                                    
MODE=DHCP                                                                                                                  
CURRENT_IP=192.168.0.14                                                                                                    
CURRENT_NETMASK=255.255.255.0                                                                                              
CURRENT_GATEWAY=192.168.0.1                                                                                                
CURRENT_NAMESERVER1=192.168.0.1                                                                                            
CURRENT_NAMESERVER2=0.0.0.0                                                                                                
IP=192.168.2.120                                                                                                           
NETMASK=255.255.254.0                                                                                                      
GATEWAY=192.168.2.1                                                                                                        
NAMESERVER1=192.168.2.1                                                                                                    
NAMESERVER2=0.0.0.0                                                                                                        
CRYPT=0               

------------------------------------------------------------------------------

# cat /etc/resolv.conf                                                                                                     
cat: can't open '/etc/resolv.conf': No such file or directory   

------------------------------------------------------------------------------

# route -n                                                                                                                 
Kernel IP routing table                                                                                                    
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface                                              
0.0.0.0         192.168.0.1     0.0.0.0         UG    10     0        0 eth0                                               
0.0.0.0         0.0.0.0         0.0.0.0         U     1003   0        0 wlan0                                              
10.200.0.0      10.206.0.1      255.255.0.0     UG    0      0        0 tun0                                               
10.206.0.1      0.0.0.0         255.255.255.255 UH    0      0        0 tun0                                               
10.251.0.0      10.206.0.1      255.255.0.0     UG    0      0        0 tun0                                               
169.254.0.0     0.0.0.0         255.255.0.0     U     0      0        0 wlan0                                              
192.168.0.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0 

------------------------------------------------------------------------------

# ifconfig -a                                                                                                              
eth0      Link encap:Ethernet  HWaddr B8:27:EB:52:0A:0F                                                                    
          inet addr:192.168.0.14  Bcast:192.168.0.255  Mask:255.255.255.0                                                  
          inet6 addr: fe80::ba27:ebff:fe52:a0f/64 Scope:Link                                                               
          inet6 addr: 2003:e9:f729:1700:ba27:ebff:fe52:a0f/64 Scope:Global                                                 
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1                                                               
          RX packets:73203 errors:0 dropped:17539 overruns:0 frame:0                                                       
          TX packets:50177 errors:0 dropped:0 overruns:0 carrier:0                                                         
          collisions:0 txqueuelen:1000                                                                                     
          RX bytes:9721984 (9.2 MiB)  TX bytes:12460007 (11.8 MiB)                                                         
                                                                                                                           
lo        Link encap:Local Loopback                                                                                        
          inet addr:127.0.0.1  Mask:255.0.0.0                                                                              
          inet6 addr: ::1/128 Scope:Host                                                                                   
          UP LOOPBACK RUNNING  MTU:65536  Metric:1                                                                         
          RX packets:171011 errors:0 dropped:0 overruns:0 frame:0                                                          
          TX packets:171011 errors:0 dropped:0 overruns:0 carrier:0                                                        
          collisions:0 txqueuelen:1000                                                                                     
          RX bytes:35091143 (33.4 MiB)  TX bytes:35091143 (33.4 MiB)                                                       
                                                                                                                           
tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00                                        
          inet addr:10.206.136.93  P-t-P:10.206.0.1  Mask:255.255.255.255                                                  
          inet6 addr: fe80::7406:b303:11ff:41df/64 Scope:Link                                                              
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1                                                       
          RX packets:38163 errors:0 dropped:0 overruns:0 frame:0                                                           
          TX packets:38777 errors:0 dropped:0 overruns:0 carrier:0                                                         
          collisions:0 txqueuelen:100                                                                                      
          RX bytes:5820267 (5.5 MiB)  TX bytes:14295449 (13.6 MiB)                                                         
                                                                                                                           
wlan0     Link encap:Ethernet  HWaddr B8:27:EB:07:5F:5A                                                                    
          inet6 addr: fe80::ba27:ebff:fe07:5f5a/64 Scope:Link                                                              
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1                                                               
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0                                                               
          TX packets:2469 errors:0 dropped:0 overruns:0 carrier:0                                                          
          collisions:0 txqueuelen:1000                                                                                     
          RX bytes:0 (0.0 B)  TX bytes:679072 (663.1 KiB)                                                                  
                                                                                                                           
wlan0:avahi Link encap:Ethernet  HWaddr B8:27:EB:07:5F:5A                                                                  
          inet addr:169.254.6.81  Bcast:169.254.255.255  Mask:255.255.0.0                                                  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1   

------------------------------------------------------------------------------

# ls -la /etc/config/wpa_supplicant.conf                                                                                   
-rw-r--r--    1 root     root           249 Mar 20 08:31 /etc/config/wpa_supplicant.conf

**Comment by jens-maus** [comment]
Ok, dann ist das letztere das Problem. Wenn du nicht explizit WLAN verwendest dann bitte die Datei `/etc/config/wpa_supplicant.conf` mit folgendem Befehl löschen:

```
rm -f /etc/config/wpa_supplicant.conf
```

Danach Neustarten und dann sollte es wieder gehen. Der Fehler wird dann mit der nächsten kommenden Version behoben sein.

**Comment by Andreas0211** [comment]
Hat funktioniert!
Vielen Dank für die superschnelle Unterstützung!!

**Comment by jens-maus** [comment]
Das ist ein BugTracker. Geclosed wird nur durch den Maintainer wenn der ursprüngliche Bug beseitigt ist :)
