### ISSUE TITLE
New SunAltitude function for max Altitude at the actual Date

### ISSUE THREAD

**Issue by drose28357** [jens-maus/RaspberryMatic#625]
**Is your feature request related to a problem? Please describe.**
Not a Problem

**Describe the solution you'd like**
There are new Script function for SunAzimuth() und SunAltitude().
I use a modifyed script to calculate the max sun altitude once a day. I uses the altitude values to determin seasonal behavior of programs. For example if altitude is hight then 30 degree then start summer programm for garden watering.

We can have to possible solutions:
1) new additional function like system.SunMaxAltitude(). This funtion takes the aktual date an for example the 12:00 time (for simplificatzion. one can also calculate the correkt value)
2) pass a DateTime parameter to SunAltitude whre Date is actual date and time is 12:00.

**Describe alternatives you've considered**
use a dedicated self coded script

**Additional context**
Of course programs can be changing behavior dependiung on sensors like temperatur, humidity and (astro) time. so it is not an important feature request, but easy to implement.

**Comment by drose28357** [comment]
Sorry there is a typo in the title replace Azimut with Altitude.

**Comment by jens-maus** [comment]
Starting with `ReGaHss R1.00.0388.0208` it will be possible to specify a time variable as an optional parameter to `system.SunAltitude()` and `system.SunAzimuth()` so that you can then use the following command to get the altitude of the sun @ 12:00:

```c++
var alt = system.SunAltitude(@12:00@);
```
