### ISSUE TITLE
v3.45.7.20190511 - hsd485d constantly restarts

### ISSUE THREAD

**Issue by r4m3u5** [jens-maus/RaspberryMatic#627]
**Describe the bug**
hsd485d constantly restarts

**To Reproduce**
1. install v3.45.7.20190511
2. watch hs485d crashing

**Expected behavior**
stable hs485d

**Screenshots**

![image](https://user-images.githubusercontent.com/17406423/57571104-eeb6dd00-7409-11e9-8db7-daf3d9c7deeb.png)

**System information (please complete the following information):**
 - Version v3.45.7.20190511
 - Hardware RaspberryPi2

**Additional context**
Downgrade to an earlier version doesn't seem to be possible in that state.

**Comment by BOFH90** [comment]
Same here. My wired-gateway is not connected after the upgrade.

**Comment by jens-maus** [comment]
Then please check the content of `/var/log/messages` and see which reason it outputs for restarting hs485d.

**Comment by r4m3u5** [comment]
A bit more detail from /var/log/messages:

# cat /var/log/messages | grep hs485
May 11 18:19:24 homematic-ccu2-2 user.err monit[911]: 'hs485d' failed protocol test [DEFAULT] at [localhost]:32000 [TCP/IP] -- Connection refused
May 11 18:19:24 homematic-ccu2-2 user.info monit[911]: 'hs485d' trying to restart
May 11 18:19:24 homematic-ccu2-2 user.info monit[911]: 'hs485d' restart: '/etc/init.d/S60hs485d restart'
May 11 18:19:24 homematic-ccu2-2 user.info hs485d: Using configuration file: /var/etc/hs485d.conf
May 11 18:19:26 homematic-ccu2-2 user.err hs485d: UnifiedLanCommController::connect(): Could not connect.
May 11 18:19:27 homematic-ccu2-2 user.crit hs485d: Could not connect to HomeMatic Lan Gateway with IP Address 192.168.222.171
May 11 18:19:42 homematic-ccu2-2 user.err monit[911]: 'hs485d' service restarted 1 times within 1 cycles(s) - exec
May 11 18:19:42 homematic-ccu2-2 user.info monit[911]: 'hs485d' exec: '/bin/triggerAlarm.tcl hs485d restarted WatchDog-Alarm'
May 11 18:19:42 homematic-ccu2-2 user.info monit[911]: 'hs485d' process is running after previous restart timeout (manually recovered?)
May 11 18:20:00 homematic-ccu2-2 user.err monit[911]: 'hs485d' failed protocol test [DEFAULT] at [localhost]:32000 [TCP/IP] -- Connection refused
May 11 18:20:00 homematic-ccu2-2 user.info monit[911]: 'hs485d' trying to restart
May 11 18:20:00 homematic-ccu2-2 user.info monit[911]: 'hs485d' restart: '/etc/init.d/S60hs485d restart'
May 11 18:20:00 homematic-ccu2-2 user.info hs485d: Using configuration file: /var/etc/hs485d.conf
May 11 18:20:02 homematic-ccu2-2 user.err hs485d: UnifiedLanCommController::connect(): Could not connect.
May 11 18:20:03 homematic-ccu2-2 user.crit hs485d: Could not connect to HomeMatic Lan Gateway with IP Address 192.168.222.171
May 11 18:20:18 homematic-ccu2-2 user.err monit[911]: 'hs485d' service restarted 1 times within 1 cycles(s) - exec
May 11 18:20:18 homematic-ccu2-2 user.info monit[911]: 'hs485d' exec: '/bin/triggerAlarm.tcl hs485d restarted WatchDog-Alarm'
May 11 18:20:18 homematic-ccu2-2 user.info monit[911]: 'hs485d' process is running after previous restart timeout (manually recovered?)
#

**Comment by jens-maus** [comment]
Well, obviously hs485d cannot connect to your LAN gateway with the IP 192.168.222.171

**Comment by r4m3u5** [comment]
@jens-maus 

Pretty sure I'm having a Déjà-vu here ...didn't we have the same problem a few versions in the past as well?
I can't remember what the fix was though ... darn ...

**Comment by r4m3u5** [comment]
Yeah well, no issue with v3.45.7.20190504 and I've got it on 2 different RPIs with different gateways.

**Comment by BOFH90** [comment]
same here, works after a downgrade. tested on 2 different systems

**Comment by jens-maus** [comment]
Please state which Pi Models you use for your tests.

**Comment by BOFH90** [comment]
I tested with an Raspberry Pi 3B (non plus)

**Comment by darkbrain85** [comment]
In my case it is a rpi3 ( no +).

**Comment by jens-maus** [comment]
Ok, then this could be the issue. Already building a version with a downgraded kernel for you guys to test. I will send you the link for the test, so please keep tuned so that you can test it quickly and give feedback accordingly so that I can replace the current rpi3 image.

**Comment by r4m3u5** [comment]
Both of them RPi2ModB

**Comment by jens-maus** [comment]
Ok, so please try the following alternative `*-rpi3.zip` archive potentially fixing the issue:

https://cloud.light-speed.de/s/goMg97A3sKkcmJk/download

**Comment by darkbrain85** [comment]
This version is working! Thank you very much for this testing release!

**Comment by jens-maus** [comment]
Ok, thanks for the tests. I just replaced the official `-rpi3.zip` file so that this version should work again:

https://github.com/jens-maus/RaspberryMatic/releases/download/3.45.7.20190511/RaspberryMatic-3.45.7.20190511-rpi3.zip

**Comment by r4m3u5** [comment]
Can confirm that it works well with the fix version.

Thanks Jens! Have a good one.

**Comment by jens-maus** [comment]
9321d5b9bd0d45091468a3b4c5170cac8bb0cc8e fixes the issue.
