### ISSUE TITLE
Wlan Verbindungsproblem PI Zero

### ISSUE THREAD

**Issue by vr6syncro** [jens-maus/RaspberryMatic#628]
Moin,

habe heute die neueste Version: RaspberryMatic 3.45.7.20190511 für den Pi Zero (RaspberryMatic-3.45.7.20190511-rpi0.zip) installiert.

Es wurde alles installiert. Wlan Verbindung hat er auch übernommen. Beim Booten kommt auch die Meldung im Browser das er bootet und er mich automatisch weiterleitet. Soweit so gut. Irgendwann verwirft er dann aber die Wlan Verbindung ab dem Punkt HMIPServer. Ab dann ist auch im Wlan Gerät zu sehen das der Zero nicht mehr damit verbunden ist.

Versucht habe ich rfkill unblock wifi sowie wlan aus angeschaltet. Auch der iw wlan0 scan befehl geht.

Ich kann es mir nicht erklären wieso der Fehler auftritt.

**Comment by jens-maus** [comment]
Bitte die `-rpi0.zip` Release Datei erneut herunterladen und installieren lassen. Es gab in den Releasedateien ein Problem mit den RaspberryPi und die neue Datei (mit sha256sum: 73d2332f1a955cc436c2865cb658aca83454d08d22a27891ae46c2cdf109b663) sollte das Problem lösen. Bitte testen und zurückmelden ob die neue Datei das Problem beseitigt.

**Comment by vr6syncro** [comment]
Moin, das Problem besteht leider immer noch.

**Comment by jens-maus** [comment]
Gut, dann ist das ein separates Problem und du solltest dich damit mal an das HomeMatic Forum wenden. Das hier ist ein Bugtracker und kein Diskussionsforum. Das stand übrigens so auch im Ticket Template das du einfach so gelöscht hast statt es auszufüllen wie es dort beschrieben stand.

**Comment by vr6syncro** [comment]
bin zurück auf RaspberryMatic-3.45.5.20190330-rpi0.zip dort geht es.

**Comment by jens-maus** [comment]
Wenn das so ist müsstest du selbst das ganze etwas debuggen und herausfinden warum das mit der aktuellsten Version nicht mehr geht und wenn sich dabei ein Fehler in raspberryMatic herauskristallisiert dann kannst du das gerne hier  posten

**Comment by jens-maus** [comment]
Duplicate of #635
