### ISSUE TITLE
3.45.7.20190511 - LAN Gateways nicht mehr erreichbar

### ISSUE THREAD

**Issue by friedpa** [jens-maus/RaspberryMatic#629]
**Describe the bug**
Nach dem Einspielen der letzten Version sind meine beiden Gateways (Original eQ-3 Gateway und mein Raspberry Gateway) nicht mehr erreichbar.

**Expected behavior**
Beide Gateways sollten weiterhin erreichbar sein

**System information (please complete the following information):**
 - Version 3.45.7.20190511
 - Hardware RaspberryPi3

**Additional context**
Bitte um rasche Fehleranalyse... ich kann Teile meiner Installation nicht mehr steuern (e.g. Pumpen laufen im Pool Technikschacht)

**Comment by jens-maus** [comment]
Bitte das "*-rpi3.zip" Archiv erneut herunterladen denn es hatte sich ein Bug eingeschlichen der in der neuen Datei beseitigt sein sollte:

https://github.com/jens-maus/RaspberryMatic/releases/download/3.45.7.20190511/RaspberryMatic-3.45.7.20190511-rpi3.zip

Hier nur sicherstellen das man dann die richtige *rpi3.zip datei für das erneute Update verwendet. Diese Datei muss die folgende SHA256 Checksumme haben:
8a03c490b39f6ade0d04d706b14083b2975ede1320f8ea21bdf35e20ed08f29a

Bitte dann melden ob das Problem damit beseitigt ist.

**Comment by friedpa** [comment]
Hallo Jens,

nach dem „Panikmodus“ ist nun alles wieder OK. Kann beide LAN-Gateways erreichen. DANKE!!!

Musste allerdings eine neue SD Karte nehmen, da die alte Karte anscheinend kein Schreiben mehr zugelassen hat. 

LG Paul

 

Von: Jens Maus <notifications@github.com> 
Gesendet: Samstag, 11. Mai 2019 21:24
An: jens-maus/RaspberryMatic <RaspberryMatic@noreply.github.com>
Cc: friedpa <paul@fried.at>; Author <author@noreply.github.com>
Betreff: Re: [jens-maus/RaspberryMatic] 3.45.7.20190511 - LAN Gateways nicht mehr erreichbar (#629)

 

Bitte das "*-rpi3.zip" Archiv erneut herunterladen denn es hatte sich ein Bug eingeschlichen der in der neuen Datei beseitigt sein sollte:

https://github.com/jens-maus/RaspberryMatic/releases/download/3.45.7.20190511/RaspberryMatic-3.45.7.20190511-rpi3.zip

Hier nur sicherstellen das man dann die richtige *rpi3.zip datei für das erneute Update verwendet. Diese Datei muss die folgende SHA256 Checksumme haben:
8a03c490b39f6ade0d04d706b14083b2975ede1320f8ea21bdf35e20ed08f29a

Bitte dann melden ob das Problem damit beseitigt ist.
