### ISSUE TITLE
Ausnahmen für Content Security Policy definieren

### ISSUE THREAD

**Issue by JensBonse** [jens-maus/RaspberryMatic#630]
**Is your feature request related to a problem? Please describe.**
Seit dem Sicherheitsupdate kann ich die Bilder einer Web Cam nicht mehr anzeigen lassen. Die Bilder werden über eine externe URL geladen. Hier die Fehlermeldung im Safari:
Refused to load <External URL> because it does not appear in the img-src directive of the Content Security Policy.

**Describe the solution you'd like**
Es wäre super, wenn man 'Ausnahmen' für die Content Security Policy definieren könnte. 

**Describe alternatives you've considered**
Könnte man in der CCU ggf. einen CORS Proxy einbauen, um die Externe URL über diesen abzufragen?

**Comment by jens-maus** [comment]
Heute wurde eine neue Version von RaspberryMatic released in der die CSP header bis auf weiteres wieder deaktiviert wurden. Es sollte also wieder gehen.
