### ISSUE TITLE
CCU3 startet nach Update auf RaspberryMatic 3.45.7.20190511 nicht mehr

### ISSUE THREAD

**Issue by superpower10** [jens-maus/RaspberryMatic#631]
Die Haupt-LED ist aus und nichts passiert. Auch nach 20 Minuten (ich habe gestoppt) nicht.

Und nun?

Soll ich den Stecker ziehen oder warten?

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!

**Comment by superpower10** [comment]
Sorry!
