### ISSUE TITLE
Feature Request: WebUI Filter: Entfernen-Button, der den Filter entfernt

### ISSUE THREAD

**Issue by MichaelKlar** [jens-maus/RaspberryMatic#633]
**Is your feature request related to a problem? Please describe.**
Als ein Entwickler finde ich die neuen sticky Filter toll. Jedoch komme ich öfter in die Situation, einen bestehenden Filter wieder entfernen zu wollen. Das geht derzeit nur, wenn ich den Filtertext markiere, entferne und dann auf "Setzen" klicke

**Describe the solution you'd like**
Unter dem "Setzten" Button einen "Entfernen" Button, der den Filter entfernt, den Dialog schließt, und den Filter anwendet, d.h. wieder alles anzeigt

**Describe alternatives you've considered**
Der Entfernen Button leert nur das Filterfeld und setzt den Cursor in selbiges. Mit Enter bin ich dann den Filter los

**Additional context**
n/a

**Comment by libertyx82** [comment]
Der Button zum zurücksetzten des Filters befindet sich unten auf der Seite.

![image](https://user-images.githubusercontent.com/22996350/57582836-f6d65180-74c9-11e9-8e59-5b563813818b.png)

**Comment by MichaelKlar** [comment]
Solved
