### ISSUE TITLE
Probleme mit restorbackup.sh wenn monit web interface aktiviert ist....

### ISSUE THREAD

**Issue by roe1974** [jens-maus/RaspberryMatic#634]
Habe immer noch "Probleme" mit restoreBackup.sh

Diesmal kommt in der Konsole:

```
Cannot create socket to [localhost]:2812 -- Connection refused
Cannot create socket to [localhost]:2812 -- Connection refused
Cannot create socket to [localhost]:2812 -- Connection refused
Cannot create socket to [localhost]:2812 -- Connection refused
Cannot create socket to [localhost]:2812 -- Connection refused
Cannot create socket to [localhost]:2812 -- Connection refused
```
Auch wenn ich alle Ports öffne kommt dieser Fehler.
Siehe Kommentare: 
https://github.com/jens-maus/RaspberryMatic/issues/612

lg Richard

**Comment by libertyx82** [comment]
Hast du nur die Firewall auf "Ports offen" eingestellt oder auch den Port 2812 in die Liste "Port-Freigabe" eingetragen?

**Comment by roe1974** [comment]
ja .... keine Änderung
Fehler kommt trotzdem

**Comment by roe1974** [comment]
@jens-maus ..... kontest du das schon nachstelen ?
lg Richard

**Comment by jens-maus** [comment]
@roe1974 Nein, noch nicht. bitte mal die eigenen Anpassungen in der Monit Konfiguration hier zeigen damit ich das besser/einfacher/schneller versuchen kann zu reproduzieren.

**Comment by roe1974** [comment]
Ich habe nur in der monit.cfg (/usr/local/etc) die web Oberfläche aktiviert mit:

set httpd
	port 2812
	allow 192.xxx.xxx.xxx/24
	allow user:password

lg Richard

**Comment by roe1974** [comment]
Habe die letzten restores jetzt immer in der webui durchgeführt ....
werde es bei der kommende RM wieder mit der restorebackup.sh testen und gebe Dir bescheid 
lg Richard
