### ISSUE TITLE
monit on Raspberry Zero ifplugd.eth0-pid

### ISSUE THREAD

**Issue by MReinisch** [jens-maus/RaspberryMatic#635]
Hardware : Raspberry Zero
Raspberrymatic : 3.45.7.20190511

Nach dem Update auf die oben genannte Version war es mir nicht mehr möglich den Pi via WLAN zu erreichen.

Lt. FritzBox hat dieser aber seine IP-Adresse abgerufen und wenn ich einen Monitor angeschlossen haben wurde diese mir auch richtig angezeigt im "Welcome Screen".

Während des Bootens sieht man beim starten auch das WLAN aktiviert wurde und auch via DHCP eine IP-Adresse bekommen hat.

Dann ist er aber nicht mehr erreichbar. In de Logs (leider nicht gesichert) konnte ich sehen das der ifplugd amok gelaufen ist und immer das wlan0 inteface hoch und runter gefahren hat.

in der monitrc habe ich dann die prüfung für ifplugd.eth0-pid auskommentiert und neu gestartet danach geht wieder alles.

Hoffe die Fehlerbeschreibung hilft notfalls fragen.

**Comment by jens-maus** [comment]
Bitte genau auflisten was in der `/etc/monitrc` deaktiviert wurde.

**Comment by MReinisch** [comment]
Hallo folgendes habe ich auskommentiert:

```
#ifplug daemon monitoring
check process ifplugd with pidfile /var/run/ifplugd.eth0.pid
  group system
  start = "/etc/init.d/S45ifplugd start"
  stop= "/etc/init.d/S45ifplugd stop"
  restart = "/etc/init.d/S45ifplugd restart"
  if not exist for 1 cycles then restart
  if 1 restart within 1 cycles then
    exec "/bin/triggerAlarm.tcl 'ifplugd restarted' WatchDog-Alarm"
```

Da ein Zero ja kein eth0 dreht er in diesem bereich sich wohl im Kreis.

**Comment by jens-maus** [comment]
Bitte mal ausprobieren statt den gesamten ifplugd block auszukommentieren folgende Zeile unterhalb der `exec` Zeile hinzuzufügen:

```
depends on eth0LinkCheck
```

**Comment by MReinisch** [comment]
damit klappt es.

**Comment by pgollor** [comment]
Damit hat es bei mir auch geklaptt. Hoffe es wird in eins der späteren releases mit eingebaut.

**Comment by Paytrix** [comment]
Ok, ich habe gerade einen rpi zero w laufen mit dem raspberrymatic zero image. Ich hab GLAUBE ich das selbe problem. Mein pi bekommt eine ip adresse, ist aber nicht erreichbar unter dieser. 
Mein jetziges image hat die "depends on eth0LinkCheck" zeile integriert, funktioniert aber trotdem nicht. Was kann ich dagegen unternehmen?
