### ISSUE TITLE
beide Mai Versionen fehlerhaft!?

### ISSUE THREAD

**Issue by martinataustria** [jens-maus/RaspberryMatic#636]
Ich habe mit beiden neuen Versionen massive Probleme festgestellt. Dieerste Version die im Mai herausgekommen ist hat extreme Probleme mit HomematicIP Geräten gezeigt (Bewegungsmelder und Thermostat). Beide Geräte waren nur mehr sporadisch erreichbar. Ich verwende zwei Raspimatics und auf beiden trat das Problem auf. Nach dem Update auf die neue Maiversion ist auf beiden Raspimatic´s Alarmmeldungen in 20 Sekundentakt eingegegangen. Es waren alle Gateways nicht mehr erreichbar (Homatic LAnGW und die RS485 Gateways. Ein update auf  eine ätere Version ging auch nicht mehr. Beide Raspimatics hängen sich auf. Abhilfe: Die Version vom 30.3.2019 auf eine SD Karte spielen und danach das Backup einspielen (sofern man eines hat).

Hat jemand die selben oder ähnliche Probleme feststellen können

lg
Martin

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
 - Version [e.g. RaspberryMatic 3.37.8.20180922]
 - Hardware [e.g. RaspberryPi3, TinkerboardS, etc.]

**Additional context**

**Comment by jens-maus** [comment]
Einfach das *.zip neu runterladen und erneut installieren. Es hatte sich ein Fehler in der ersten Version eingeschlichen. D.h. zip frisch runterladen und dann sollte das gehen.

**Comment by martinataustria** [comment]
Die neue 2019511 Version werde ich gleich testen. Danke f&uuml;r die schnelle Antwort.
  
  ps.: kannst du mir noch eine Frage beantworten. Kann man die Homatic LAN Gateways und die HomematicIP Repeatersteckdosen an der gleiche Raspimatic verwenden oder schlie&szlig;st sich das aus? Grund hab ein gro&szlig;es Haus und daher immer wieder keinere Funkschatten (d&uuml;rfte auch Wetterbedingt sein).
  
  danke
  Martin 

  ---- jens-maus/RaspberryMatic schrieb ----
  &nbsp; >

**Comment by IT-VBFK** [comment]
lt. HomeMatic-Forum: https://homematic-forum.de/forum/viewtopic.php?f=65&t=50667&p=508216#p508216

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!
