### ISSUE TITLE
Update 3.45.5 => 3.45.7 funktioniert nicht

### ISSUE THREAD

**Issue by Tscherno** [jens-maus/RaspberryMatic#637]
Ich versuche eben von 3.45.5 => 3.45.7 zu aktualisieren. Nach dem Upload kommt der Ladebildschirm "Das Firmware-Update wird auf die RaspMatic übertragen". Das war es dann. Auch nach einer Stunde keine Verbesserung. Mehrere Versuche mit abgesicherten Modus bringen leider auch keinen Erfolg. Kann ich irgendwas kontrollieren?

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!
