### ISSUE TITLE
Backup restore not possible

### ISSUE THREAD

**Issue by steveddorf** [jens-maus/RaspberryMatic#639]
**Describe the bug**
In the version RaspberryMatic 3.45.7.20190511 the restore of a backup files fails. After writing the image file to the SD card the RaspberryMatic start up process is a expected. The Web GUI is shown as always after a first start of a new system. When I try to load the backup file from the previous version this didn't work.

**To Reproduce**
1. Write image file to SD card
2. Start Raspberry
3. Go to the Webinterface and follow the first start wizard
4. Go to System Backup file restore 
5. See error

**Expected behavior**
The normal behavior should be the upload of the backup file.

**System information (please complete the following information):**
 - Version RaspberryMatic 3.45.7.20190511
 - Hardware RaspberryPi Model B

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen. Das geschilderte Problem kann jedoch nicht genereller Natur sein das viele andere Nutzer hier keinerlei Problem damit haben.

Bitte daher an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!

**Comment by steveddorf** [comment]
Hallo, ich kann die Argumentation "Das geschilderte Problem kann jedoch nicht von genereller Natur sein, da viele andere Nutzer hier keinerlei Problem damit haben". Das Homematic Forum ist voll mit Nachrichten, die Probleme mit dem Laden der Backup Datei haben. Es ist mir vollkommen unverständlich warum dies ignoriert wird.
