### ISSUE TITLE
LED bei HB-RF-USB 

### ISSUE THREAD

**Issue by MathiasJZ** [jens-maus/RaspberryMatic#640]
Eine Ansteuerung der LED des Funkmoduls RPI-RF-MOD wird in Verbindung mit der Platine HB-RF-USB wohl nicht unterstützt.
Es wäre toll, wenn man das ändern könnte, da ich im Moment den Watchdog überwachen muß.
Es würde ein Blick genügen. So muß ich mich jetzt laufend in der WebUI anmelden.
Gruß,
Mathias

**Comment by sammykd** [comment]
Hallo, ich bin sehr verlegen um die LED Steuerung, da meine Raspimatic im Wohnumfeld steht, das gelbe Licht ist auch mit Abklleben ein Graus. Wie lange ist denn wohl so "low priority"?
Was sagt die Glaskugel
Gruß Dietmar

**Comment by jens-maus** [comment]
Na wenn du doch ein hb-rf-usb hast kannst du es doch auf den kopf drehen das die led verdeckt wird. Auch wirkt ein schwarzes klebeband wunder ;)

Aber ja, hab ich auf meiner liste, ist aber eben nicht so einfach umzusetzen zumal wenn man versucht zur ccu3 firmware kompatibel zu bleiben.

**Comment by MathiasJZ** [comment]
Hi Dietmar,
Du weißt aber schon, dass es eben nicht darum geht, die LED abzuschalten. 
Das Funkmodul hat diese LED, um verschiedene Status-Meldungen  anzuzeigen 
Den Farbcode, den ich jetzt auch nicht im Kopf habe, findest Du im Homematic-forum.

**Comment by jens-maus** [comment]
Jetzt wird die LED des RPI-RF-MOD bei Einsatz eines HB-RF-USB ja unterstützt. D.h. Die normalen Methoden zum kompletten Abschalten der LED gehen nun auch damit (`/etc/config/disableLED`)

**Comment by MathiasJZ** [comment]
ah ja, ok.
Danke für die Info. Das wusste ich jetzt nicht. Ist für mich auch nebensächlich.
Hauptsache, er spuckt jetzt die richtigen Farben aus, wenn etwas schief läuft.

**Comment by sammykd** [comment]
Hallo Jens, Mathias,
bei direktem stecken des Moduls auf dem GPIO in der von mir benutzten Version 3.47.22.20191026 funktioniert ja auch die RGB LED, nur über HB-RF-USB-TK wird sie nach dem einschalten des Pi's ~gelb und bleibt auch so, lässt sich nicht verändern.
In welcher Version funktioniert denn die RGB LED auch über den HB-RF-USB-TK?
 
@ Mathias, ich habe mir mehrere kleine Programme geschrieben, bei denen ich die Alarm / Statusmeldungen >0 abfrage und damit die LED einschalte, sind dann alle Meldungen =0 schalte ich die LED wieder aus. Beim starten wir die LED nach dem die CCU fertig ist auch ausgeschaltet, das hat direkt auf dem GPIO super funktioniert, so ist im Normalbetrieb die blaue LED aus und geht nur bei Ereignissen an.

**Comment by jens-maus** [comment]
@sammykd Na natürlich funktioniert die LED mit HB-RF-USB erst mit der nächsten Version (siehe Milestone: "next version"), weil eben erst gestern das von mir implementiert wurde.

**Comment by sammykd** [comment]
Hallo Jens,
danke noch mal für die Aufklärung, GitHub lesen muss ich erst noch üben.
