### ISSUE TITLE
HomeMatic RF-LAN Gateway: nicht verbunden

### ISSUE THREAD

**Issue by diablolot** [jens-maus/RaspberryMatic#642]
**Describe the bug**
Seit der Version 3.45.7.20190511 lassen sich scheinbar Orginal LAN Gateways nicht mehr verbinden. Ich habe heute zur Sicherheit ein weiteres neues getestet. Sie blieben immer im Status "nicht verbunden". Über Netfinder sind die Gateways ansprechbar, nur in der Zentrale nicht.

Log:
```
May 29 17:25:37 192 user.info root: Updating RF Lan Gateway Coprocessor Firmware
May 29 17:25:47 192 user.err update-coprocessor: Could not find Lan Gateway using ip and serial number
May 29 17:25:51 192 user.err update-coprocessor: UnifiedLanCommController::connect(): Unable to connect.
May 29 17:25:51 192 user.err update-coprocessor: Could not connect to Lan Gateway ip: 192.168.1.8.
May 29 17:25:55 192 user.err update-coprocessor: UnifiedLanCommController::connect(): Could not connect.
May 29 17:25:56 192 user.err update-coprocessor: Could not connect to Lan Gateway ip: 192.168.1.6.
May 29 17:25:56 192 user.info root: Updating RF Lan Gateway Firmware
May 29 17:25:56 192 user.info update-lgw-firmware: LAN Gateway Firmware Update...
May 29 17:26:06 192 user.err update-lgw-firmware: Could not find Lan Gateway using ip and serial number
May 29 17:26:06 192 user.info update-lgw-firmware: LAN Gateway Firmware Update...
May 29 17:26:08 192 user.info update-lgw-firmware: Lan Gateway Firmware Version: 1.1.3
May 29 17:26:38 192 user.err rfd: UnifiedLanCommController::connect(): Unable to connect.
May 29 17:26:38 192 user.crit rfd: CCU2LGWCommController::init(): Cannot connect to HomeMatic Lan Gateway with serial number KEQ1065258.
May 29 17:26:40 192 user.err rfd: UnifiedLanCommController::connect(): Could not connect.
May 29 17:26:41 192 user.crit rfd: CCU2LGWCommController::init(): Cannot connect to HomeMatic Lan Gateway with serial number PEQ1716379.
```
**To Reproduce**
LAN Gateway einbinden.

**Expected behavior**
LAN Gateway verbinden.

**Screenshots**

**System information (please complete the following information):**
 - Version 3.45.7.20190511
 - Hardware RaspberryPi3

**Additional context**

**Comment by jens-maus** [comment]
Das wäre mir in der Tat neu?!? Wurde das Problem bereits im HomeMatic Forum diskutiert bzw dort von anderen so bestätigt?!?

Bitte auch sicherstellen das alle notwendigen Ports zu/von den LAN Gateways freigeschalten sind bzw die Firewall in RaspberryMatic testweise komplett deaktiviert ist.

**Comment by diablolot** [comment]
Ich finde dazu nichts, versuche es gerne dort auch nochmals. Es hat ja immer funktioniert, daher dieser Report. Habe mir heute extra ein neues Gateway bestellt. Gleiches Ergebnis. :-( Habe die Ports auch alle geöffnet. Bisher klappte alles. Bin aktuelles ratlos.

**Comment by diablolot** [comment]
https://homematic-forum.de/forum/viewtopic.php?f=26&t=51009

**Comment by diablolot** [comment]
Ich habe nun mal folgende Firmwares auf einer frischen SD-Karte und dem RaspberryPi3 installiert.

Ergebnis:
3.45.7.20190504 -> verbunden (Web-Interface meldet Firmware 1.4.1, Netfinder meldet Version 1.1.5)
3.45.7.20190511 -> verbunden (Web-Interface meldet Firmware 1.4.1, Netfinder meldet Version 1.1.5)

Crazy. Habe danach ein Backup eingespielt. Ergebnis. Verbunden. 

Danke Jens für die tolle Arbeit und das schnelle Feedback!

**Comment by dehelm** [comment]
Hallo,

nutze ein Raspberry mit RaspMatic. Soweit alles OK. nun Wollte ich meine CCU2 als Lan-Gateway nutzen. Leider steht im Web UI nicht verbunden. LanGAteway lässt sich aber über Putty ansprechn und die Einstellungen Feste IP scheint auch alles zu funktionieren. 
Habe die Version der RaspMatic 20200131 nochmal als Update aufgespielt jedoch funktioniert es immer noch nicht. Was mache ich falsch?
