### ISSUE TITLE
Bug setting HM-CC-RT-DN into manual mode

### ISSUE THREAD

**Issue by Groofertje** [jens-maus/RaspberryMatic#643]
**Describe the bug**
When i try to program a HM-CC-RT-DN to manual mode, i can only choose a temp

**To Reproduce**
1. Go to 'all devices'
2. Click on 'programs'
3. Scroll down to 'select new program'

I have a system variable "Stookperiode" to declare of the periode the heater works or not (Sort of summer/winter declaration) to saving the batteries.

Heizpauze aktivieren/Heizkorper ausstellen Installations und bedieningaanleitung pag 45 und 46

4. Depending system variable "Stookperiode" i want to set a thermostaat 'HM-CC-RT-DN'  into manual mode with the value ON or OFF for Heizpauze aktivieren/Heizkorper ausstellen,
but i can only choose a temp.
even when i manual put the value "ON" or "OFF" , the returning value is temp 

**Expected behavior**
Set  the mode of the HM-CC-RT-DN into the manual mode with Heizpauze aktivieren/Heizkorper ausstellen

Srr for very bad and poor english

**Screenshots**
Manu mode state selection trying to set the mode to ON or OFF
Manu mode state after selection after manual changing value to 'OFF'

**System information (please complete the following information):**
 - Version [e.g. RaspberryMatic 3.45.7.20190504
But i suppose also for version 3.45.7.20190511 (not yet updated) because this is not marked into bugfixes
 - Hardware RaspberryPi3

**Additional context**
![Manu mode state after selection](https://user-images.githubusercontent.com/25877218/58612551-429f3e00-82b3-11e9-9a90-7fd93c257e21.jpg)
![Manu mode state selection](https://user-images.githubusercontent.com/25877218/58612552-4337d480-82b3-11e9-873b-37b52ef4a2e0.jpg)

**Comment by jens-maus** [comment]
Sorry, but I think you mix up things here. Of course the current behaviour seems to be correct IMHO. When setting your thermostat to manual mode you have to define a temperature for it as well. And if you want to set Manu mode to off you set it to AUTO mode again with another target temperature. I really cannot see that there is something wrong here.
