### ISSUE TITLE
Diagramme mit mehr als 3 Datenquellen

### ISSUE THREAD

**Issue by hellman23** [jens-maus/RaspberryMatic#644]
**Describe the bug**
Diagramme mit mehr als 3 Datenquellen werden in der Wochen- Monatsansicht nicht korrekt dargestellt.
In der Tagesansicht sind alle Datenquellen sichtbar, schaltet man auf Woche oder Monat, sind nur die letzten 3 eingefügten Datenquellen sichtbar.

**To Reproduce**
1. Diagramm mit 5-10 Datenquellen erstellen
2. nach 3-x Tagen das Diagramm anzeigen lassen, die Tagesansicht zeigt alle Datenquellen, die 
Wochen- und Monatsansicht nur die letzten 3.

**Expected behavior**

**Screenshots**
https://up.picr.de/35891355gf.jpg
https://up.picr.de/35891356lt.jpg

**System information (please complete the following information):**
 - Version [RaspberryMatic 3.45.5.20190330]
 - Hardware [RaspberryPi3]

**Additional context**

**Comment by jens-maus** [comment]
Sorry, but the whole diagram functionality in the CCU is completely closed source java stuff we don't have access to. Thus, we can't help here really. But we keep that report open for eQ3 to pick up. However, you should probably open a separate ticket with eQ3 if you want to get the issue solved.

**Comment by jens-maus** [comment]
This ticket has been closed because of inactivity of the ticket owner and due to the fact that no developer could reproduce the issue. Please reopen the ticket once it can be reproduced again or the ticket owner can reply accordingly.
