### ISSUE TITLE
Gruppen in Raspberry Matic

### ISSUE THREAD

**Issue by schneidy76** [jens-maus/RaspberryMatic#645]
**Is your feature request related to a problem? Please describe.**

In Homematic IP gibt es die Möglichkeit diverse Gruppen zu erstellen, Schaltgruppen, Beschattungsgruppen und so weiter. In der CCU sind diese auf Heizungsgruppen limitiert. Es wäre super, wenn man diese Einschränkung nicht mehr hätte. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jens-maus** [comment]
Tut mir leid. Aber die gesamte Gruppenfunktionen sind im Javateil der HomeMatic/CCU Platform umgesetzt/implementiert auf das RaspberryMatic keinerlei Einfluss/Modifizierungsmöglichkeiten hat. Also bitte diese Wünsche direkt an eQ3 herantragen.
