### ISSUE TITLE
Dokumentation - Wiki

### ISSUE THREAD

**Issue by ghost** [jens-maus/RaspberryMatic#646]

**Comment by jens-maus** [comment]
Danke erst einmal dafür das du dich bereit erklärt hast an der Dokumentation mitzuarbeiten!

Wie du ja bereits bemerkt hast habe ich im Wiki Bereich im GitHub bereits eine grundlegende Struktur für eine mögliche Dokumentation rund um RaspberryMatic generiert. Das beste wird sein, das du dich erst einmal in die grundsätzliche Arbeitsweise bei der Generierung einer Wiki-Dokumentation einarbeitest. Dazu kannst du am besten dir selbst mal ein test repository anlegen und dann entweder über die Webseite hier die markdown Seiten ändern und dich mit der Markdown-Syntax vertraut machen. Zusätzlich kannst du die Wiki Seite direkt via Git via https://github.com/jens-maus/RaspberryMatic.wiki.git auschecken und schauen ob du mit der grundsätzlichen Struktur klar kommst bzw. ob du vielleicht bereits Ansätze für Verbesserungen siehst.

**Comment by tedNAL** [comment]
Hab mal etwas copy and paste probiert - https://github.com/tedNAL/RaspberryMatic/wiki

**Comment by tedNAL** [comment]
Hab jetzt ein wenig experimentiert. Seiten mit Inhalt zu füllen - kein Problem. Allerdings gefällt mir die Navigation der einzelnen Seiten nicht, da diese unter Pages alphabetisch sortiert werden. Vielleicht wäre eine Lösung über die Sidebar, in welcher das Inhaltsverzeichnis abgebildet wird.

**Comment by ThomasLoeffel** [comment]
Hallo Zusammen,
ich würde mich gerne zum füllen von Artikel beteiligen. Allerdings kenne ich mich in GitHub nicht aus. 
@Jens: ich bin den Link gefolgt. Dieser zeigt mir 404 an. Mag an meinen fehlenden Erfahrungen liegen.

Gruß Thomas

**Comment by tedNAL** [comment]
Hi Thomas,
guckst du hier https://help.github.com/en/articles/adding-or-editing-wiki-pages
Mit einem Fork der Seite kannst du diese nach Lust un Laune bearbeiten und experimentieren.
Was mir noch nicht wirklich gefällt ist die Navigation, die Navigation von Deutsch <-> Englisch. So wie ich es herausgefunden habe, kann man nur EINE Sidebar erstellen. Schön wäre wenn man zwei hätte, eine für Deutsch, die andere für Englisch.
Gruß Theo

**Comment by tedNAL** [comment]
Hi Thomas,
guckst du hier https://help.github.com/en/articles/adding-or-editing-wiki-pages
Mit einem Fork der Seite kannst du diese nach Lust un Laune bearbeiten und experimentieren.
Was mir noch nicht wirklich gefällt ist die Navigation, die Navigation von Deutsch <-> Englisch. So wie ich es herausgefunden habe, kann man nur EINE Sidebar erstellen. Schön wäre wenn man zwei hätte, eine für Deutsch, die andere für Englisch.
Gruß Theo

**Comment by tedNAL** [comment]
@jens-maus Ist mein Entwurf so okay oder soll ich noch etwas ändern? Ansonsten müsstest Du mich nur entsprechend berechtigen, dass ich los legen kann. Habe in meinem Fork nicht alle Seiten erstellt, soll ja nur ein Beispiel sein.
