### ISSUE TITLE
RaspberryMatic is in reboot-loop | (SSH not possible)

### ISSUE THREAD

**Issue by Grashee** [jens-maus/RaspberryMatic#647]
**RaspberryMatic is in reboot-loop**
I´ve started working with the raspberry-matic for the first time, so I´ve setup the SD-card with the image put it into the raspberry-pi and started the machine. 

It begans starting up first the normal LED-indicators of the raspberry pi, than with a green/yellow led on the platine after this it beguns with a blue blinking led. After a while all leds turned off except the red one of the raspberry-pi. This behavior always repeats itself. 

The web-interface is shown if the blue LED of the platine is shown, but the screen says that the raspi is not ready yet. I should wait and I will be redirected, but this never happens.

What can I do?

**Screenshots**
![image](https://user-images.githubusercontent.com/18228345/59551026-95dfe480-8f73-11e9-8e9c-58c0f6b4010c.png)

**System information (please complete the following information):**
 - Version 3.45.7.20190511
 - RaspberryPi3

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!
