### ISSUE TITLE
WebUI - I can not run some functions in the control panel

### ISSUE THREAD

**Issue by Erbit** [jens-maus/RaspberryMatic#649]
**Describe the bug**
I can not run some functions in the control panel. The window does not open "CCU maintenance", "Additional software", "Network settings","Security", "Time-/position settings".

**To Reproduce**
1. Go to Settings -> Control panel
2. Click on ''CCU maintenance" or "Additional software" or "Network settings" or "Security" or "Time-/position settings"
3. See error

**Expected behavior**
Windows with functions should open.

**Screenshots**

![HomeMatic_WebUI_-_2019-06-23_22 38 56](https://user-images.githubusercontent.com/35191543/59981777-cf19f380-9608-11e9-8ea3-0c9bf9b2486f.png)

**System information (please complete the following information):**
 - Version RaspberryMatic 3.45.7.20190622
 - Hardware RaspberryPi3
- Firefox browser (67.0.4  64 bit)
- Google Chrome browser (75.0.3770.100 )

**Additional context**
There was no problem in the previous version of RaspberryMatic. I have cleared the browser cache, I launched it on a browser where WebUi was not running. The error is still there.

**Comment by Erbit** [comment]
Also, the "Teach-in devices" window does not open.

**Comment by jens-maus** [comment]
Which RF module do you use to communicate with Homematic devices?!?

**Comment by Erbit** [comment]
RPI-RF-MOD.
All devices on the BidCos-RF, HmIP-RF and BidCos-Wired interfaces seem to work properly. 
Should I show any logs?

**Comment by Erbit** [comment]
Wait a moment.
Not having access to "CCU maintenance" I made a "reboot" with SSH. Previously reported errors have disappeared.

I will check and let you know.

**Comment by Erbit** [comment]
jens-maus Your hands heal ;)

The next time I restarted CCU this time from the "CCU maintenance" menu. It seems that everything works correctly. If you want me to check something, write what.

For me, the case is closed. Thank you for your support.
