### ISSUE TITLE
Support for RaspberryPi4

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#650]
Now that a new RaspberryPi hardware generation (RaspberryPi4) is out we should add support for it ASAP.

**Comment by friedpa** [comment]
I just read that Eben Upton is announcing the delivery only in 2020 ….. nevertheless the performance is outstanding www.tomshardware.com/articles/review/

 

Von: Jens Maus <notifications@github.com> 
Gesendet: Montag, 24. Juni 2019 13:15
An: jens-maus/RaspberryMatic <RaspberryMatic@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [jens-maus/RaspberryMatic] Support for RaspberryPi4 (#650)

 

Now that a new RaspberryPi hardware generation (RaspberryPi4) is out we should add support for it ASAP.

**Comment by MathiasJZ** [comment]
I already ordered my Raspberry PI4. It will arrive my home approximately at 15th of July 2019.
But my PI3 B+ is running very well. So I'll install IObroker at my new device.
For what I need a computer with 4GB RAM for Raspberrymatic?
I'm only a bit sad cause it supports only micro SD as well.

**Comment by roessi** [comment]
Hallo Jens
Ich habe mir auch einen Pi4 bestellt, sollt kommende Woche ankommen. 
Würd mich als Beta Tester anbieten. 
Lg Rudi

**Comment by friedpa** [comment]
Received my Raspberry PI 4 today. So ready for testing!

**Comment by jens-maus** [comment]
Anyone interested in testing the latest RaspberryPi4 version of RaspberryMatic (release candidate) can download the `-rpi4.zip` archive from here:

https://cloud.light-speed.de/s/xby5d4B7YFRCxyH

Any feedback on the RaspberryPi4 version would be highly appreciated.

**Comment by friedpa** [comment]
I have the problem that the RPI-RF-MOD doesn´t fit mechanically onto the Raspberry 4 anymore.
I will look for an GPIO extension cable this week. Hope that I can start testing next week.

**Comment by friedpa** [comment]
Hallo Jens,
habe nun heute die SW getestet. Bei mir startet die RM SW bleibt aber dann irgendwo hängen. Das RPI-RF-MOD Modul leuchtet grün und die Pi4 blinkt rot. Alle versuche über SSH auf den Pi4 zu kommen waren erfolglos. Habe es mit Putty und WinSCP probiert.
Nachtrag: Am Router meldet sich der Pi4 auch nicht an.

**Comment by jens-maus** [comment]
An updated test version  is now uploaded and the pi4 support is complete now for the upcoming release. Please note, however, that due to some unresolved RaspberryPi firmware problems the console does not show up on a HDMI connection. But you simply should have to wait until the pi4 booted up completely (green LED start heartbeat flashing) and then the pi4 should be up&running. 

Upcoming versions will hopefully fix this minor issue in future. But in principle rpi4 support should work fine.

**Comment by friedpa** [comment]
Hi Jens,
habe nun 3 Stunden getestet.
- RM läßt sich starten und kommt mit der WebUI hoch :)
Das einzige was mir aufgefallen ist:
- nach einspielen des Backups funktioniert der automatische reboot nicht.

**Comment by friedpa** [comment]
Nachtrag: Auch der _Neustart_ und das _Herunterfahren_ des PI4 aus der WebUI heraus gehen bei mir nicht.
