### ISSUE TITLE
Web-UI Update won't work with 3.45.7.20190511

### ISSUE THREAD

**Issue by nRaecheR** [jens-maus/RaspberryMatic#651]
**Describe the bug**
Updating the device from 3.45.7.20190511 to a newer version (e.g. 3.45.7.20190622) won't work. After choosing the downloaded file RaspberryMatic-3.45.7.20190622-rpi3.zip the upload stalls and nothing happens after that. 

I see a tmp file in /usr/local/tmp but this file seems to stuck at ~ 1 MB size and before that the increase of size is in the kB/sec range. SCPing the same file to the same location shows a performance of ~ 5.5 MB/sec.

Tested it with Chromium and Firefox, both with a clean profile. 

**To Reproduce**
1. Start Firmware Update in Web-UI
2. Choose File, use RaspberryMatic-3.45.7.20190622-rpi3.zip
3. Click button "Update"
4. No progress

**Expected behavior**
The device should show a disclaimer dialog after the file has been uploaded. In /usr/local/tmp the unpacked firmware update is present. 

**Screenshots**
n/a

**System information (please complete the following information):**
 - Version [RaspberryMatic 3.45.7.20190511]
 - Hardware [RaspberryPi3]

**Additional context**
I've updated the device with this method a lot of times, it always took a lot of time to upload, but now it seems to stall during the upload process and after several minutes the upload progress seems to be restarted, at least a second tmp.* file show up.

**Question**
Is there any script to update the device from a ssh shell?

**Comment by jens-maus** [comment]
Boot into recovery mode and update the firmware from there.

**Comment by MathiasJZ** [comment]
I can't confirm this foul.
I made my update and it works fine.

**Comment by jens-maus** [comment]
Please use the Homematic forum for such "issues"!
