### ISSUE TITLE
Update der RasPi vom 22.06.2019 "hängt"  - Das Firmware-Update wird auf die RaspMatic übertragen.  Bitte haben Sie einen Augenblick Geduld. 

### ISSUE THREAD

**Issue by MaHa2005** [jens-maus/RaspberryMatic#652]
Hallo,
ich habe mir das aktuelle Update zum RasPi3 geladen. Bisher lief das Update immer problemlos - auch als zip gepackt !! Seit vorgestern versuche ich die aktuelle Version "RaspberryMatic-3.45.7.20190622" zu laden. Es funktioniert weder per *.zip-Datei noch als *.img-Datei.
Es wird nur der Hinweis:
 "Das Firmware-Update wird auf die RaspMatic übertragen.
Bitte haben Sie einen Augenblick Geduld. "
angezeigt. 
Ich habe den Upload bereits mehrmals versucht - leider erfolglos!
Sind eventuell auf dem Raspberry Dateien korrupt die eventuell händisch gelöscht werden müssen oder hilft ein kurzzeitiges Trennen vom Stromnetz ?!?
Viele Grüße
Martin

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!

**Comment by MaHa2005** [comment]
Sorry !
Martin
