### ISSUE TITLE
NEO Server - Bei Aufruf wird WebUI Startseite angezeigt

### ISSUE THREAD

**Issue by HM-klana** [jens-maus/RaspberryMatic#653]
**Describe the bug**
Wird der Button NEOServer angeklickt wird, anstelle der NEO Server Seite, die WebUI Startseite angezeigt. Ein Online oder Offline schalten des NEO Servers ist nicht mehr möglich.

**To Reproduce**
1. In der WebUI auswählen der Einstellungen/Systemsteuerung
2. Anklicken des Buttons "NEOServer"
3. Hier sollte jetzt die Einstellungsseite des NeoServers erscheinen.
4. Es wird aber die WebUI Startseite angezeigt

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
 - Firmwareversion:  3.45.7.20190622
 - NEO Server : 2.4.5
 - HardwareTinkerboardS

**Additional context**
Bisher versucht:
- Löschen des NEO Servers per WebUI mit anschliessender Installation des aktuellen Pakets
- Löschen des NEO Servers per Terminal (SSH) mit anschliessender Installation des aktuellen Pakets
- Neuinstallation des TinkerboardS mit der aktuellen Firmware
   Hier direkt nach der Installation den NEO Server aufgerufen. Das Problem ist auch hier vorhanden.

**Comment by roe1974** [comment]
same here ......

**Comment by jens-maus** [comment]
Kann das leider nicht reproduzieren hier. Auf einer frischen RM kann ich problemlos das NEO Server Addon starten. Es muss hier also ein anderes Problem geben das wir noch nicht durchschaut / aufgedeckt haben.

**Comment by jens-maus** [comment]
Bitte mal die folgende URL manuell in den Browser eingeben und schauen ob dann die NEO Server Konfigurationsseite des Adens kommt:

```http://XXXXXXXX/addons/mediola/index.html?sid=@XXXXXXXX@```

Hier natürlich den vorderen "XXXX" teil mit der IP-Adresse und den hinteren zwischen @XXXX@ mit einer validen sessionID ausfüllen. Dann sollte man auf der Seite landen.

**Comment by roe1974** [comment]
PS: Auf einer neuen RM habe ich es auch nicht, nur sobald ich das backup einspiele bzw. die bestehende RM update .... werde am Abend deinen Vorschlag testen...

**Comment by HM-klana** [comment]
Mit dem Direktaufruf bekomme ich die Konfigurationsseite angezeigt !!
Und den Status konnte ich von Offline auf Online schalten...Zurück zu Offline hab ich nicht gefunden.

**Comment by jens-maus** [comment]
@HM-klana Dann zeigt nur dein "NEO-Server" Button in der WebUI auf das falsche Ziel. Dann bitte mal den Inhalt deiner `/etc/config/hm_addons.cfg` Datei hier zeigen.

.. und ein "Zurück zu Offline" gab es leider noch nie. Das hat Mediola anscheinend nie vorgesehen gehabt...

**Comment by HM-klana** [comment]
Bitteschön...
`email {CONFIG_URL /addons/email CONFIG_DESCRIPTION {de
{<li>Email-Integration</li><li>Alarmierung und Weiterleitung von
Systemzustaenden</li><li>Einfache Benachrichtigungen</li><li>...</li>}
en {<li>Email-Integration</li><li>Alerting and routing of
System-States</li><li>Simple Notifications</li><li>...</li>}} ID email
CONFIG_NAME "Email"} mh {CONFIG_URL /addons/mh/index.cgi
CONFIG_DESCRIPTION {de {<li>Sicherer VPN Fernzugriff</li><li>SMS
Versand</li><li>Versand von PUSH Nachrichten</li><li>Mail Versand per
Skript</li>} en {<li>Secure VPN remote access</li><li>Send SMS
Messages</li><li>Send push notifications</li><li>Send dynamic
eMails</li>}} ID mh CONFIG_NAME CloudMatic} rmupdate {CONFIG_URL
/addons/rmupdate/index.html CONFIG_DESCRIPTION {de
{<li>System-Update</li>} en {<li>System-update</li>}} ID rmupdate
CONFIG_NAME "System-Update"} mediola {CONFIG_URL
/addons/mediola/index.html CONFIG_DESCRIPTION {de {<li>NEO Server</li>}
en {<li>NEO Server</li>}} ID mediola CONFIG_NAME NEOServer} cuxd
{CONFIG_URL /addons/cuxd/index.ccc CONFIG_DESCRIPTION {de
{<li>System</li><li>FS-20</li><li>EnOcean</li><li>...</li>} en
{<li>System</li><li>FS-20</li><li>EnOcean</li><li>...</li>}} ID cuxd
CONFIG_NAME CUx-Daemon}`

**Comment by jens-maus** [comment]
Hmm, komisch. der Eintrag sieht soweit i.O. aus. Welchen Webbrowser verwendest du denn?

Und kannst du versuchen rauszukommen auf welche URL der "NEOServer" Button verlinkt? Am besten rechte Maustaste drauf und dann in den Browser Debugmodus gehen (sowas wie "Inspect Element") dann sollte da angezeigt werden auf welche URL er denn dann springen will wenn du den Button drückst.

**Comment by HM-klana** [comment]
mediola {CONFIG_URL /addons/mediola/index.html CONFIG_DESCRIPTION {de {<li>NEO Server</li>} en {<li>NEO Server</li>}} ID mediola CONFIG_NAME NEOServer}

die Datei "/addons/mediola/**index.html** " gibt es bei mir nicht....

**Comment by jens-maus** [comment]
@HM-klana Vorsicht, nicht URLs mit Dateien verwechseln. Das eine hat mit dem anderen nix zu tun!

**Comment by roe1974** [comment]
Das spannende ist, dass die Seite kurz "aufpoppt" .... und dann sofort die login Seite kommt.
Also ganz kurz ist die richtige Seite da.....

**Comment by roe1974** [comment]
Browsaer: Chrome, Firefox, IE, Safari .... überall das gleiche (Chrome sogar extra installiert, also cache & cookies alles leer9

**Comment by HM-klana** [comment]
`<td>
<div class="cpButton">
<div class="StdTableBtn CLASS21701" onclick="window.open('/addons/email?sid=@qNi2g4VNtT@');">Email</div>
<div id="btnAddOn_email" class="StdTableBtnHelp j_addOn"><img id="showAddonInfo_email" src="/ise/img/help.png"></div>
<ul id="description_email" style="display:none"><li>Email-Integration</li><li>Alarmierung und Weiterleitung von Systemzustaenden</li><li>Einfache Benachrichtigungen</li><li>...</li></ul>
</div>
</td>`

**Comment by jens-maus** [comment]
@roe1974 Das riecht dann danach das er versucht die Seite ohne gültige sessionID aufzurufen. D.h. ohne `?sid=@XXXXX@` Komponente in der URL.

**Comment by HM-klana** [comment]
Kopieren funktioniert nicht (
<img width="992" alt="Bildschirmfoto 2019-06-26 um 13 27 49" src="https://user-images.githubusercontent.com/50288602/60176306-38228680-9816-11e9-88f8-4e1916bbd141.png">

**Comment by roe1974** [comment]
dachte ich auch, wenn ich aber auf "zurück" gehe, poppt es wieder auf und es kommt login.
Wenn man das oft genug machtm, sieht man dass die URL die kurz aufscheint die gleiche Session ID hat wie der TAB der RM

**Comment by jens-maus** [comment]
@HM-klana Du bist fast an der richtigen stelle. aber das ist die ausgabe der URL für das CUxD Addon und nicht für Mediola NEO. scrolle/suche weiter.

**Comment by jens-maus** [comment]
@roe1974 Wie gesagt, prüfe du erst einmal ob der direkte Aufruf der index.html mit sid=XXXX klappt bei dir. Dann kannst du dich nochmal melden :)

**Comment by roe1974** [comment]
OK :-)

**Comment by HM-klana** [comment]
OH, vertan....

<img width="1215" alt="Bildschirmfoto 2019-06-26 um 13 31 53" src="https://user-images.githubusercontent.com/50288602/60176515-ca2a8f00-9816-11e9-96b1-c04cad7a7107.png">

**Comment by jens-maus** [comment]
@HM-klana Ok, das sieht gut aus. Welcher Browser ist das? Und wenn du jetzt das gesamte `/addons/mediola/.....` inkl. der sid da rauskopierst und an `http://IP` anhängst kommst du auf die Seite, ja?

**Comment by HM-klana** [comment]
Ja genau

gerade noch mal probiert:
http://homematic-raspi/addons/mediola/index.html?sid=@7idUFyAxfT@

Browser ist Safari unter OS X

**Comment by HM-klana** [comment]
So sieht das im Browser aus


<img width="2560" alt="Bildschirmfoto 2019-06-26 um 13 42 04" src="https://user-images.githubusercontent.com/50288602/60177059-3b1e7680-9818-11e9-9d82-443c8f27120f.png">

**Comment by jens-maus** [comment]
@HM-klana Dann verstehe ich aktuell nicht warum das drücken auf den Knopf nicht zu exakt der gleichen URL weiterleitet. Komisch. Das müsste du selber dann mal Debugger und rausfinden warum der `window.open()` Befehl da nicht geht. Das müsste dann aber übrigens beim aktuellen CUxD genauso aussehen d.h. da dürftest du auch nicht mehr auf die CUxD Seite kommen.

**Comment by HM-klana** [comment]
Alle anderen Buttons (z.B. CuxD, E-Mail usw) funktionieren so wie gewünscht, nur der NEO Server nicht.
Hmm, das mit dem Debug bekomme ich nicht hin...Ich kann mir das Element anzeigen lassen, aber unter dem Debug finde ich das nicht wieder um den Breakpoint zu setzen

**Comment by jens-maus** [comment]
Gehen die anderen Buttons wirklich? Du musst darauf achten ob nach dem Aufruf der CUxD Seite der webbrowser oben in der URL wirklich dann die URL mit der sid zeigt. Und wenn du nicht die aktuellste CUxD installiert hast (2.3.0) wird sich auch ohne sid kein problem zeigen denn die sid Überprüfung wurde in CUxD erst in der 2.3.0 version hinzugefügt.

**Comment by HM-klana** [comment]
CuxD 2.3.1
Urls alle so wie es sein sollte.

**Comment by jens-maus** [comment]
@HM-klana Dann bleibt nur noch ein Bug im Mediola NEO Server Addon. In der neuesten version 2.4.5 hat mediola da nämlich eine sessionID Prüfung eingebaut und wer weiss, vielleicht geht die unter bestimmten Bedienungen schief und leitet dann einfach auf die Hauptseite wieder um....

**Comment by HM-klana** [comment]
Das könnte sein.
mit der 2.4.4 konnte ich die Seite noch korrekt aufrufen.
Allerdings konnte ich dort nicht Online schalten, blieb immer Offline.
Irgendwas is immer ;-)

**Comment by HM-klana** [comment]
Wäre es schwer die 2.4.4 wieder zu installieren und vorher die 2.4.5 komplett zu entfernen?

**Comment by jens-maus** [comment]
wegen solch einem kleinen Problem ist das IMHO unnötig. Du hast doch jetzt den workaround über die direkte eingabe der URL.

**Comment by HM-klana** [comment]
Deinstall ist fehlgeschlagen! soviel dazu....

<img width="805" alt="Bildschirmfoto 2019-06-26 um 14 16 14" src="https://user-images.githubusercontent.com/50288602/60179034-0660ee00-981d-11e9-9c8e-2d9f49b8d6aa.png">

**Comment by jens-maus** [comment]
@HM-klana Wie gesagt, ich würde mich jetzt mit was wichtigerem/anderen beschäftigen. der NEO Server geht doch jetzt prinzipiell. Du kannst halt nur die Konfiguration Seite momentan nicht aufrufen. die braucht doch aber eh niemand wirklich wenn er erstmal läuft.

**Comment by HM-klana** [comment]
Eigentlich hast Du recht, aber mich nervt so etwas einfach....ist genauso mit den WebUI Programmen, welche nach ein-,zweimal editieren plötzlich nicht mehr funktionieren und neu angelegt werden müssen...
Hab die 2.4.4 einfach drübergebügelt. Da wird die Seite wieder angezeigt.

**Comment by roe1974** [comment]
@HM-klana 
wo hast Du die 2.4.4 her ?
lg Richard

**Comment by psytester** [comment]
Mediola bietet das im Nachhinein leider nicht direkt an, aber Amazon Cloud sei dank, den offiziellen Download Link einkürzen auf: https://s3-eu-west-1.amazonaws.com/mediola-download/
Der Release 2.4.4 ist dann in diesem Block sichtbar als:```<Key>ccu3/2.4.4/neo_server.tar.gz</Key>```
Somit lautet der finale DL Link auf das 2.4.4 Tarball: https://s3-eu-west-1.amazonaws.com/mediola-download/ccu3/2.4.4/neo_server.tar.gz

**Comment by roe1974** [comment]
danke !!!!!

**Comment by roe1974** [comment]
@jens-maus 
Mir ist gerade aufgefallen, dass dieses Phänomen nur bei einer https Anmeldung auf der CCU auftritt.
Wenn ich mich über http anmelde, kommt die Seite vom NEO Server.
Hilft diese Info, oder ist es ein Mediola Thema ?

lg Richard

**Comment by jens-maus** [comment]
@roe1974 Das war wohl der final Hint den @HM-klana übersehen hatte. In der Tat passiert das nur wenn man via https auf seine Zentrale zugreift. mit http passiert das nicht. Dann habe ich schon einen Ansatzpunkt für eine Reparatur des Problems. Danke dafür!
