### ISSUE TITLE
WebUI - Nach Programmausführung Anzeige doppelt

### ISSUE THREAD

**Issue by HM-klana** [jens-maus/RaspberryMatic#656]
**Describe the bug**
Wenn in der WebUI ein Programm ausgeführt wird ist danach die Anzeige des Programmes verdoppelt (siehe Screenshots)

**To Reproduce**
1. WebUI Menü Status/Bedienung auswählen
2. Menüpunkt Programme auswählen
3. Beliebiges Programm per Button "Start" ausführen
4. Anzeige in der WebUI zeigt nur das ausgeführte Programm doppelt an.

**Expected behavior**

**Screenshots**

Hier wurden die Programme "Sonne_SetAzimut1" und "Sonne_SetAzimut2" ausgeführt.
Der rechte Teil mit der Anzeige AKTIV und START sind doppelt.

<img width="2216" alt="Bildschirmfoto 2019-06-27 um 10 15 19" src="https://user-images.githubusercontent.com/50288602/60256571-171f6b80-98d2-11e9-8134-472909f94707.png">
<img width="2216" alt="Bildschirmfoto 2019-06-27 um 10 23 54" src="https://user-images.githubusercontent.com/50288602/60256583-1981c580-98d2-11e9-8f71-bc47e9032261.png">

**System information (please complete the following information):**
 - Version: RaspberryMatic 3.45.7.20190622
 - Hardware : TinkerboardS

**Additional context**
Dies ist genauso wie schon mal mit der doppelten Geräteanzeige

**Comment by jens-maus** [comment]
Das ist ein bekannter Bug den momentan nur eQ3 selbst beseitigen kann und wie du schon geschrieben hast ist das exakt das gleiche wie mit der doppelten Geräteanzeige. Insofern ist dieses Ticket hier ein Duplikat davon.

**Comment by jens-maus** [comment]
Momentanes Workaround: Browser-Cache Löschen und Zentrale Neustarten - oder einfach ignorieren.

**Comment by HM-klana** [comment]
OK, wollte es nur erwähnt haben.

**Comment by jens-maus** [comment]
Duplicate of #623
