### ISSUE TITLE
Wertevergleich / Werteabgleich in WebUI Programmen

### ISSUE THREAD

**Issue by ScienceFiction-by-HM** [jens-maus/RaspberryMatic#658]
Hi Jens, 

wie die meisten hier bin ich ein glücklicher RaspberryMatic User. Danke erstmal dafür. 

Da ich jedoch selbst nicht programmiere, klicke ich alles über die WebUI Programme zusammen (trotz inzwischen über 100 Aktoren). 

Eine Funktion die ich mir wünschen würde, wäre ein Wertevergleich über die WebUI Programme. 

1. Beispiel: 

**WENN** _Lichtsensor Süd_ 2000 Lux heller als _Lichtsensor Nord_ 
**UND** _Temperatur außen_ über 26°C 
**DANN** _Rollos auf Südseite_ runter.

Aktuell kann ich nur 

**WENN** _Temperatur außen_ über 27°C 
**DANN** _Rollos runter_ 

Das ist sehr schlecht für den WAF (**Schatz** die Sonne scheint überhaupt nicht auf das Fenster**!** **WARUM** ist dann der Rollo unten **???**, **Schatz** die Haustiere waren wieder den ganzen Tag im dunklen **!!!**....)

Für meinen häuslichen Segen und auch ein funktionaleres Smart Home wäre das sehr von nutzen. Wenn du das auch so siehst und dir die Umsetzung möglich erscheint, würde mich das freuen. 

Gruß 
Science Fiction

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jens-maus** [comment]
Diese Art von Wertevergleiche bzgl. Sensorwerten in der WebUI müssen vom Hersteller selbst für jeden Sensor umgesetzt/implementiert werden. Deshalb geht das für teilwerte bei Sensoren. Das heisst also das eQ3 hier selbst tätig werden muss und ich bzw. das RaspberryMatic Projekt hier wenig bis nichts ausrichten kann.

Insofern bitte diesen Umstand im HomeMatic-Forum diskutieren/beleuchten, etc. da er IMHO nicht direkt eine Limitation von RaspberryMatic selbst darstellt.

**Comment by libertyx82** [comment]
Mit einem Lichtsensor lässt sich auch ohne einen solchen Vergleich eine Beschattung realisieren.
Dazu sollte der Lichtsensor auf der Hausseite montiert sein, auf der sich auch das zu beschattende Fenster befindet, alternativ und auch am besten geht es auch ein Sonnensensor ([](https://smart-wohnen.org/homematic-sonnensensor/))

Hier mal mein Programm mit dem ich die Fenster auf der Ostseite meiner Wohnung bei Bedarf beschatte.
![screencapture-homematic-pages-index-htm-2019-07-03-14_41_31](https://user-images.githubusercontent.com/22996350/60592627-51d94600-9da1-11e9-8ebb-2211e40ff17f.png)
