### ISSUE TITLE
An internal error was detected in the service software

### ISSUE THREAD

**Issue by holgerhermann1968** [jens-maus/RaspberryMatic#662]
Bei der Version 3.45.7.20190622 tritt seit neusten folgender Fehler auf :
An internal error was detected in the service software. The diagnostics are being emailed to the service system administrator (root).
Dieser kommt im Gerätemanager wenn man den Button Einstellungen drückt.
Nach einen Durchbooten des Raspberry kann ich einmal das Untermenü aufrufen.
Wenn ich dann ein anders gerät anwähle und Funktion "Einstellen" drücke kommt erneut die Fehlermeldung,
![Raspberry](https://user-images.githubusercontent.com/45963176/61072797-542c4780-a414-11e9-93af-6289e55b677c.jpg)

**Comment by jens-maus** [comment]
Bitte mal den Inhalt der Dateien mit dem Muster `cgimail.*` aus dem Ordner `/usr/local/tmp` hier posten.

**Comment by holgerhermann1968** [comment]
Return-Path: <CGI script - do not reply>
From:  <CGI script - do not reply>
To: root
Subject:  CGI problem

CGI environment:
REQUEST_METHOD: GET
SCRIPT_NAME: /config/ic_deviceparameters.cgi
HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763
HTTP_REFERER: http://192.168.178.81/pages/index.htm?sid=@yqQcGxoJby@
HTTP_HOST: 192.168.178.81
REMOTE_ADDR: 192.168.178.127
cgi.tcl version: 1.10.0
input:
sid=@yqQcGxoJby@&iface=BidCos-RF&address=OEQ1970628:1&redirect_url=GO_BACK
cookie:
errorInfo:
no space left on device
    while executing
"close $f"
    (procedure "write_sessions" line 22)
    invoked from within
"write_sessions"
    (procedure "session_getsessiondata_ise" line 26)
    invoked from within
"session_getsessiondata_ise"
    (procedure "session_isvalid_ise" line 9)
    invoked from within
"session_isvalid_ise"
    (procedure "session_requestisvalid_ise" line 5)
    invoked from within
"session_requestisvalid_ise $needed_upl"
    (procedure "session_requestisvalid" line 6)
    invoked from within
"session_requestisvalid 0"

**Comment by jens-maus** [comment]
Das Problem kommt daher:

```
errorInfo:
no space left on device
    while executing
```

Und bedeutet das der RAM in dem die logfiles liegen vollgelaufen ist. Das kommt daher, das ein zu starkes logging in der WebUI eingestellt ist und eben etwas auf "Alles loggen" konfiguriert ist. In der kommenden RaspberryMatic Version wird hierfür eine Verbesserung eingearbeitet sein. In der jetzigen Version sollte man in dem Fall die CCU neustarten und die Loggingeinstellungen nicht auf "Alles loggen" stellen.
