### ISSUE TITLE
Überwachung der Internetverbindung durch Benutzer deaktivierbar

### ISSUE THREAD

**Issue by TomMajor** [jens-maus/RaspberryMatic#664]
**Is your feature request related to a problem? Please describe.**
Die Überwachung der Internetverbindung mittels monit hat in RaspberryMatic ab Version 3.45.5.20190330 Einzug gehalten.
Dieser Alarm sollte m.E. durch den Benutzer generell abschaltbar sein (z.B. wenn der Router nachts automatisch abgeschaltet wird wie bei mir).

**Describe the solution you'd like**
jmaus brachte diese Variante ins Spiel:
> Edit:
Ich kann aber ka auch mal überlegen ob ich für diesen hasInternet check in /etc/config ggf. eine Datei prüfen lasse und wenn die existiert wird der hasInternet Check keinen Alarm mehr auslösen.

https://homematic-forum.de/forum/viewtopic.php?f=65&t=51306&start=10#p518179

**Describe alternatives you've considered**
- Bootskript in /usr/local/etc/config/rc.d mit
`monit unmonitor hasInternet`
bringt keinen Erfolg da monit zu dem Zeitpunkt noch nicht läuft.
- Momentane Lösung mit HM Skript
https://github.com/TomMajor/SmartHome/tree/master/Info/Skripte#01-no-internet-connection-detected---%C3%BCberwachung-deaktivieren
potentiell kann damit immer noch der allererste Check nach Reboot als Alarm durchkommen, je nach Timings, HW usw.
- Schöner wäre eine generelle Abschaltmöglichkeit mittels Config

**Comment by Ratlos** [comment]
Danke, die Abschaltungsmöglichkeit hat mir erstmal geholfen, obwohl mein Problem etwas anders gelagert ist. Ich habe 2 Internet Verbindungen, von denen eine nur bei entsprechendem Durchsatz aktiviert wird, oder die Hauptverbindung mal ausfällt. Der Watchdog erkennt aber jede Änderung der Verbindungen als Fehler, was ich nicht wirklich verstehe, da ja, solange noch eine Verbindung aktiv ist, kein Fehler vorliegt.

**Comment by egeu5** [comment]
Wie realisierst du denn die zwei Internetverbindungen inkl. Umschaltung? (Load-Balancer?)

**Comment by Ratlos** [comment]
Draytek Vigor 2925

**Comment by egeu5** [comment]
Beim Failover ist es ja klar, dass es als fehler erkannt wird da du ja offline bist.

Bedeutet du hast ja auch zwei IPs. Ich weiß nun nicht wie der Watchdog arbeitet, aber könnte es damit zusammenhängen?

Schaltet der Router wirklich nahtlos um? Mal probiert zb mit einem durchgängigen Ping auf einen externen Server ob auch keine Datenpakete während des Umschaltens verloren gehen?

**Comment by libertyx82** [comment]
> Ich weiß nun nicht wie der Watchdog arbeitet

Es wird ein PING an www.google.de gesendet

**Comment by Ratlos** [comment]
Den Failover Fall hatte ich noch gar nicht. Die Hauptverbindung ist immer an. Bei Bedarf(zeitgesteuert) wird die 2. Leitung zugeschaltet. Ca. 30 min später schlägt der Watchdog an.
Wird die 2. Leitung wieder zeitgesteuert abgeschaltet, schnappt der Watchdog wieder zu.
Datentransfers zu den Schaltzeiten laufen klaglos weiter. Ich komme mit der Deaktivierung klar, denn was kümmerts die Homematic Zentrale, obs Internet da ist oder nicht. Dafür habe ich ja den Router, der dokumentiert alles und gut ist. Und nahtlos umschalten bräuchte ich ja auch nur, wenn der ping 30 mal oder so in der Sekunde ausgeführt wird. Ich werde aber mal ausprobieren, was mit dem ping  passiert, wenn die Leitung zugeschaltet wird und dann berichten.

**Comment by jens-maus** [comment]
Tut mir leid, aber ich sehe hier kein Grund für weitere Anpassungen. Die Internetüberwachung kann jetzt deaktiviert werden und wer speziallösungen wie hier dargestellt fallback Internetverbindungen hat kann diese Abschaltung nutzen. Auch bitte hier dazu nicht weiter diskutieren da das ein Ticketsystem ist und kein diskussionsforum. Wenn weiterer diskussionsbedarf dazu existiert diese diskussion bitte ins homematic forum verlagern.

**Comment by afrixx** [comment]
Kurz und knapp:
Zum Deaktivieren der Internet-Überwachung ein "Programm" in der CCU erstellen: Ohne Bedingung, mit einem Skript als Aktion:
`! DISABLE (ENABLE) INTERNET MONITORING ON CCU3
! Source: https://homematic-forum.de/forum/viewtopic.php?f=65&p=616782#p616782
system.Exec("touch /etc/config/internetCheckDisabled"); ! // to disable
! system.Exec("rm /etc/config/internetCheckDisabled"); ! // to enable

! restart:
system.Exec("monit restart internetCheck");`
Dann Skript einmal ausführen / testen.

**Comment by jens-maus** [comment]
Statt sowas hier in einem Ticket untergehen zu lassen wäre es IMHO besser sowas in einem Beitrag in der Wiki Dokumentation z.B. hier unterzubringen: https://github.com/jens-maus/RaspberryMatic/wiki/Tipps

**Comment by afrixx** [comment]
Danke für den Tipp, @jens-maus ! Habe soeben die Wiki-Seite um einen Abschnitt "Überwachung der Internet-Verbindung deaktivieren" ergänzt!
