### ISSUE TITLE
RaspberryMatic als LAN-Gateway: Verhalten nach CCU Update

### ISSUE THREAD

**Issue by friedpa** [jens-maus/RaspberryMatic#666]
**Describe the bug**
Seit ungefähr 3 oder 4 Releases ist mir aufgefallen, dass bei jedem Update zwar das original LAN-Gateway von ELV sich mit der CCU nach dem Update verbindet, dass RaspberryMatic LAN-Gateway aber nicht. Man muss jedes Mal zuerst das RaspberryMatic LAN-Gateway neu starten und dann einen Restart auf der CCU durchführen, dann sind die beiden Devices wieder verbunden.

**Comment by friedpa** [comment]
Da keiner antwortet, werde ich den Report schliessen.

**Comment by libertyx82** [comment]
Vielleicht auch mal ein bisschen mehr Geduld mitbringen...

Jens und auch die anderen beschäftigen sich hiermit in Ihrer Freizeit.

Zumal dieses Thema als erstes einmal etwas für das Forum ist.

**Comment by friedpa** [comment]
Hallo Dirk,

danke für die Rückmeldung! Ich bin leider etwas entnervt, da die Gateways dauernd in den „nicht verbunden“ Status gehen und damit einige Aktoren nicht mehr angesprochen werden können (zB Pumpensteuerung im Technikschacht des Pools). Das regt mein Frau auf 😊 und damit „No happy wife, no happy life“ 😉

Ich werde das Forum durchsuchen, man kann aber sehen, dass das Problem erst seit 2-3 Versionen der RaspberryMatic auftritt, da das System vorher 1,5 Jahre stabil gelaufen ist.

Vielen Dank nochmals für die Rückmeldung!

 

Von: Dirk Schneider <notifications@github.com> 
Gesendet: Montag, 22. Juli 2019 10:27
An: jens-maus/RaspberryMatic <RaspberryMatic@noreply.github.com>
Cc: friedpa <paul@fried.at>; State change <state_change@noreply.github.com>
Betreff: Re: [jens-maus/RaspberryMatic] RaspberryMatic als LAN-Gateway: Verhalten nach CCU Update (#666)

 

Vielleicht auch mal ein bisschen mehr Geduld mitbringen...

Jens und auch die anderen beschäftigen sich hiermit in Ihrer Freizeit.

Zumal dieses Thema als erstes einmal etwas für das Forum ist.

**Comment by friedpa** [comment]
**Describe the bug**
Seit ungefähr 3 oder 4 Releases ist mir aufgefallen, dass bei jedem Update zwar das original LAN-Gateway von ELV sich mit der CCU nach dem Update verbindet, dass RaspberryMatic LAN-Gateway aber nicht. Man muss jedes Mal zuerst das RaspberryMatic LAN-Gateway neu starten und dann einen Restart auf der CCU durchführen, dann sind die beiden Devices wieder verbunden.
**Hier noch ein Nachtrag:** 
Seit der letzten Release verabschieden sich nun auch die Gateways ohne Update. Ich habe das Forum durchforstet und zwar einige dbzgl Einträge gefunden, aber es wird meist so gelöst, dass die Gateways über die CCU stromlos gemacht werden (es wird der DC Status -1% abgefragt) und dann auf das reconnected gehofft wird. 
Das LAN-Gateway von ELV zeigt nun immer öfter DC -1% an und im Status steht "Verbunden".  Das RaspberryMatic LAN-Gateway zeigt sofort DC -1% und "Nicht verbunden".
Das Problem lässt sich nur beheben indem man zuerst das RaspberryMatic LAN-Gateway neu startet und dann die CCU. Das LAN-Gateway von ELV braucht man nicht neu starten, oder stromlos machen. Es connected sich in 75% der Fälle ohne wiederholte restarts der CCU.
Gerne stehe ich für weitere Details (e.g. Logfiles) zur Verfügung.
Hinweis: die LAN_Gateways sind folgendermaßen angebunden:
- LAN-Gateway von ELV: mittels Power-Line Adapter (da in Technikschacht vom Pool verbaut)
- RaspberryMatic LAN-Gateway: über WiFi

Bilder:
![image](https://user-images.githubusercontent.com/42890695/62456142-1652e280-b778-11e9-8653-04daadcc7ee3.png)
![image](https://user-images.githubusercontent.com/42890695/62456206-3c788280-b778-11e9-8ae8-41f01a4e6d5d.png)

**Comment by mhoellein** [comment]
Hallo,

bei mir läuft alles stabil. 2 original GW, eins per WLan das ander per PowerLine angebunden und 3 Raspis mit MOD-RPI-PCB per WLan. Die GWs sind immer verbunden und verbinden sich auch nach Neustart der CCU als auch nach dem Update der CCU.

**Comment by mike-bee** [comment]
+1
Ich habe 2 LAN Gateways auf einem älteren RaspberryMatic Stand. Die werden zuverlässig mit jedem Neustart der CCU mit Stand 3.47.10.20190713 verbunden. Nun möchte ich ein 3. Gateway auf RaspberryPi ZeroW und aktuellem Firmware-Stand hinzufügen.
Selbst nach allen Restart-Kombinationen kommt keine Verbindung zustande.

**Comment by jens-maus** [comment]
Duplicate of #978
