### ISSUE TITLE
Fehler beim Speichern von Diagrammen

### ISSUE THREAD

**Issue by OliverGeist** [jens-maus/RaspberryMatic#667]
Leider wird der Report nicht nach oben geschoben wenn ich diesen kommentiere. Darum ist er leider aus dem Fokus geraten. Darum bin ich einfach mal so frei und versuche ihn "so" wieder zu pushen:

Fehler beim Speichern von Diagrammen:
https://github.com/jens-maus/RaspberryMatic/issues/532

Tut mir leid für "diese Variante!!"

**Comment by jens-maus** [comment]
Das ist nicht die richtige Art & Weise mehr Fokus zu bekommen. Die richtige wäre ins Homematic forum zu gehen, Leidensgenossen zu finden und zu versuchen den Fehler zu analysieren und ggf. gemeinschaftlich einen Lösungsansatz zu erarbeiten. Hier einfach jedes mal zu kommentieren das der Fehler immer noch da ist und jetzt auch noch ein weiteres ticket zu öffnen ist IMHO nicht die feine englische Art... Daher bitte ein anderes Vorgehen wählen...
