### ISSUE TITLE
HmIP-MOD-RC8 Kanal Auswahl für Skript Event fehlerhaft

### ISSUE THREAD

**Issue by hooker78** [jens-maus/RaspberryMatic#668]
**Describe the bug**
Wenn man die Kanäle des HmIP-MOD-RC8 als Tür/Fensterkontakt konfiguriert, sind sie in der Auswahl für Trigger eines Skriptes nur als Tastendruck-Event auswählbar und damit nicht nutzbar.

**To Reproduce**

1. HmIP-MOD-RC8 Kanal als Tür/Fensterkontakt einstellen
2. Neus Programm auswählen
3. Als "Bedingung wenn" den Kanal vom HmIP-MOD-RC8 auswählen
4. Jetzt stehen dort fälschlicherweise nur die Tastendruck Events zur Auswahl

**Expected behavior**
Eigentlich sollte dort geöffnet / geschlossen stehen.

**Screenshots**
![bug1](https://user-images.githubusercontent.com/52243785/61568920-6138de80-aa85-11e9-9337-34000677b89a.png)

![bug2](https://user-images.githubusercontent.com/52243785/61568933-6d24a080-aa85-11e9-9b79-d21647855fb8.png)

**System information (please complete the following information):**
 - Version RaspberryMatic 3.47.10.20190713
 - Hardware RaspberryPi3

**Comment by jens-maus** [comment]
This ticket has been closed because of inactivity of the ticket owner and due to the fact that no developer could reproduce the issue. Please reopen the ticket once it can be reproduced again or the ticket owner can reply accordingly.
