### ISSUE TITLE
HmIP-PCBS version 2.10.2 is corrupt

### ISSUE THREAD

**Issue by koegel** [jens-maus/RaspberryMatic#669]
**Describe the bug**
The firmware for HmIP-PCBS version 2.10.2 is corrupt. The following message is displayed when I try to add it to my Pi: "The info file is corrupt or not available!"
I have retried the download several times with the same result. Strangely the .tgz even contains an info file.
The download points to
https://ccu3-update.homematic.com:8443/firmware/download?cmd=download&serial

**To Reproduce**
1. Go to home screen
2. Click on "New device firmware available"
3. Download the firmware for HmIP-PCBS by clicking on the link
4. Goto Settings -> Device firmware - Overview -> Device Firmware
5. Click "New"
6. Upload the tgz that was downloaded before
7. System will show this error:  "The info file is corrupt or not available!"

**Expected behavior**
Firmware is added to the list of available firmware.

**System information (please complete the following information):**
 - Version: RaspberryMatic 3.47.10.20190713
 - Hardware: RaspberryPi3

**Comment by jens-maus** [comment]
Die Firmware stammt von Hersteller (eQ3) und nicht vom raspberryMatic Projekt. Insofern gehört hier dee Hersteller benachrichtigt und muss die Firmwaredatei entsprechend korrigieren.

**Comment by jens-maus** [comment]
Workaround bis der Hersteller reagiert:
 https://homematic-forum.de/forum/viewtopic.php?f=65&t=51682&start=90#p519086

**Comment by koegel** [comment]
Danke für die schnelle Rückmeldung!
