### ISSUE TITLE
WebUI: Skripteditor-Fenster zu groß

### ISSUE THREAD

**Issue by jp112sdl** [jens-maus/RaspberryMatic#671]
✅ Skripteditor startet grundsätzlich in einer optimalen Fenstergröße
<img width="1143" alt="Bildschirmfoto 2019-07-27 um 07 44 10" src="https://user-images.githubusercontent.com/18190139/61990541-b73bf200-b042-11e9-9f87-c393f5e424f7.png">

❌ Wird die `WriteLine()`-Ausgabe einer Zeile zu lang, vergrößert sich das Fenster auf die gesamte Textlänge, so dass die Buttons "Fehlerprüfung" und "Ausführen" nicht mehr erreichbar sind.
<img width="1167" alt="Bildschirmfoto 2019-07-27 um 07 44 52" src="https://user-images.githubusercontent.com/18190139/61990562-2b769580-b043-11e9-8253-c4821bf0b89e.png">
Der Skripteditor muss zum erneuten Ausführen des Skripts erst geschlossen und erneut geöffnet werden.

▶️ getestet mit Firefox und Chrome

🔸 Als Lösung wäre ein automatischer Zeilenumbruch oder ein Scrollbalken im Ausgabefenster sinnvoll.

**Comment by jens-maus** [comment]
Danke für den Report. Das ist in der Tat komisch und scheint wohl nur im Editor aufzutreten. Wenn man den selben Skript unter "Skript testen" aufruft dann findet da ein korrekter LineWrap statt und das ohne scrollbalken oder ähnliches. Dort erfolgt keine automatisch Vergrößerung wie beim SkriptEditor wo es die "Ausführen" und "Fehlerprüfung" Knöpfe gibt.

Momentan weiss ich allerdings nicht wieso/weshalb. Vielleicht kann hier ja mal jemand nachschauen was die beiden Editorfenster grundsätzlich so unterscheidet, denn die CodeMirror Objekte scheine ich exakt gleich initialisiert zu haben...

**Comment by jens-maus** [comment]
Ok, ich denke ich habe es gefunden. Es war ein fehlendes `table-layout: fixed` und `width: 100%` CSS statement in den alten `<table>` Definitionen in editScript.htm. Wenn man die besagte table definition um die beiden style parameter ergänzt sollte sich die fensterbreite nicht mehr ändern und CodeMirror sollte korrektes line wrapping machen.
