### ISSUE TITLE
HmIP-BROLL: Nach Upgrade auf 3.47.10 funktioniert das Kommando "UP" mittels Openhab nicht mehr

### ISSUE THREAD

**Issue by Wirrkopf76** [jens-maus/RaspberryMatic#672]
**Describe the bug**
Nach dem Upgrade auf 3.47.10 habe ich das Problem, dass meine HmIP-BROLL nicht mehr nach oben fahren, wenn ich mittels OpenHAB das Kommando UP sende. Das Rollo fährt im Gegenzug weiter nach unten und nicht nach oben.
Nach einem Downgrade auf 3.45.7 funktioniert das Zusammenspiel mit Openhab wieder.

**To Reproduce**
1. Openhab 2.4 in Verbindung mit RaspberryMatic 3.45.7
2. Upgrade auf 3.47.10 
3. Versuch das Rollo mittels Kommando "UP" aus Openhab nach oben zu fahren. 
4. Rollo fährt nicht nach oben, sondern nach unten.

**Expected behavior**
Beim Senden des Befehls UP sollte das Rollo auch nach oben fahren.

**Screenshots**

**System information (please complete the following information):**
 - Version 3.47.10
 - Hardware RaspberryPi3

**Additional context**
Das scheint ein grundsätzliches Problem zu sein. Siehe https://community.openhab.org/t/homematic-shutters-hmip-broll-always-close-when-sending-command-up/78648

**Comment by libertyx82** [comment]
Wie aber aus deinem Link hervorgeht, ist das kein reines RaspberryMatic Problem sondern tritt auch auf einer CCU & piVCCU auf. Daher dürfte die Lösung des Problems bei eq-3 liegen.

**Comment by 8cH9azbsFifZ** [comment]
Workaround in OpenHAB:

// Test Rolladen mit Status
rule "TR Control"
when Item TR_Proxy received command
then
 switch (receivedCommand)
 {
  case DOWN: TR_Control1.sendCommand(receivedCommand)
  case UP:   TR_Control1.sendCommand(1)
  case STOP: TR_Control1.sendCommand(receivedCommand)
 }
end

rule "TR Status"
when Item TR_Status changed
then
 TR_Proxy.postUpdate(TR_Status.state)
end

**Comment by Wirrkopf76** [comment]
ist mit RaspberryMatic 3.53.30.20200919 gefixt und damit kann das Issue geschlossen werden.
