### ISSUE TITLE
HomeMatic looses mapping to Philips Hue devices

### ISSUE THREAD

**Issue by fl0wde** [jens-maus/RaspberryMatic#676]
**Setup:**
Using current HomeMatic firmware: 3.47.10.20190713 on RasperryPi3 and HomeMatic is up2date with all AddOns etc.

Using Philips Hue Bridge and it's connected fine. With Philips Hue I use Osram Smart+ soclkets which are connected via ZigBee. This setup is working also fine.

**Issues:**
After setting up everything in Hue and HomeMatic jacks are working correct in general, but I have 2 issues:
1. Mapping is getting lost between HomeMatic and Philips Hue connected Osram Smart+ jacks.
2. Turning on the Philips Hue connected Osram Smart+ jacks needs 2 or more clicks (actions) in the application to turn on.

**Details about both issues:**
1. After set up e.g. 2 devices and naming them everything is working (except 2.). After some reboots later the mapping is not right anymore. This means devices are visible but by turning a socket on the "worng" one is turned on because the mapping is not correct anymore.

2. In the Hue app everything is working fine with one 1 click of on. This only happens via HomeMatic (WebGUI and TinyMatic) - so this must be a push command topic?

**Investigation:**
Tried to get logs of Hue but can't find it ti identify the issues. Also a mapping table of devices was not found to compare with backups I made before.

Thanks for your help to get aware of the reason and maybe some others also had such issue. I'm not using light bulps from Hue at the moment, so I can's say if this would change also...

**Comment by fl0wde** [comment]
@jens-maus I really appreciate to get some feedback to identify the issue and solve it. Thanks.

**Comment by jens-maus** [comment]
Sorry, but the whole Philips Hue implementation in the CCU is within the closed source Java part of the CCU platform to which I do not have source code access and this I cannot debug it.

**Comment by fl0wde** [comment]
> 
> 
> Sorry, but the whole Philips Hue implementation in the CCU is within the closed source Java part of the CCU platform to which I do not have source code access and this I cannot debug it.

Thanks Jens, that's what i expectec unfortunately. :(

How to go on the get this issue fixed? Anything I can check or provide to whom ever?

**Comment by bvol** [comment]
I was struggeling with this issue too. Solution: After renaming bulbs in hue app, delete the corresponding bulb in Homematic. Reboot raspberrymatic, bulbs will appear with new serial (name) in WebUi. From that point on everything works stable. In my point of view hue integration leaks as the names are used as serial number to address bulbs...

**Comment by HMside** [comment]
Genau dort scheint der Hund begraben! Es wird ein Name anstelle einer eindeutigen SN oder ID verwendet, zudem gab es meines Wissens noch das Problem, das am Ende des Namens aus unerklärlichen Gründen teilweise ein Leerzeichen angehängt wird. Was schon bei einigen User dazu geführt hat, das sich die Geräte nicht mehr ohne weiteres löschen lassen.

**Comment by jens-maus** [comment]
This ticket has been closed because of inactivity of the ticket owner and due to the fact that no developer could reproduce the issue. Please reopen the ticket once it can be reproduced again or the ticket owner can reply accordingly.
