### ISSUE TITLE
Kanäle (z.B. bei HM-LC-Sw4-DR) fehlen in der Geräteübersicht

### ISSUE THREAD

**Issue by cRemE-fReSh** [jens-maus/RaspberryMatic#678]
Hallo,

bei mir fehlen in der Geräteübersicht einige Sensoren/Aktoren.
Auffällig ist das beispielsweise bei den HM-LC-Sw4-DR. Hier fehlen 2-3 Kanäle (Aktoren).
Es kann gut sein, dass es sich hierbei um ursprünglich "nicht sichtbare" Kanäle handelt. Allerdings sollten die doch wenigstens in der Geräteübersicht noch auftauchen.
![Fehlende Kanäle](https://user-images.githubusercontent.com/42785404/62485211-65226b80-b7bc-11e9-87f7-94724699d7f5.png)

Ich war bisher auf der Version 3.43.15.20190223. Nachdem mir der Fehler aufgefallen ist, habe ich auf die aktuellste Version (3.47.10.20190713) aktualisiert, bzw. neue SD Karte geflasht und Backup wiederhergestellt). In beiden Versionen verhält es sich identisch.

Bedienungsfehler? Oder wie komm ich an meine ausgebledeten Kanäle wieder ran? Brauch nämlich einen, der bisher Reserve war...

Anmerkung: In Webmatic, cloudmatic und CCU Historian werden die Kanäle angezeigt. Nicht aber in der Geräteübersicht.

Viele Grüße und Danke

**Comment by mifricke** [comment]
Das war doch schon immer so, oder nicht? Ich meine es hilft wenn man über den Button unten die Baumstruktur komplett öffnet. Dann sollten auch alle versteckten Kanäle angezeigt werden. Natürlich sollte man dann die Sichtbarkeit wieder aktivieren.

**Comment by cRemE-fReSh** [comment]
@mifricke Danke. Das wars.
Ist mir bisher ehrlich gesagt nie aufgefallen.
