### ISSUE TITLE
Complete native eq3 Philips HUE integration in RaspberryMatic 

### ISSUE THREAD

**Issue by steckenpferd** [jens-maus/RaspberryMatic#679]
Next to the Addons there exists a Philips HUE integration from eq3 to couple it with the HUE bridge. This integration as eq3 confirms is only a BETA version and also does not receives any status feedbacks from e.g. a HUE remote control.
Also eq3 shows no signs in to improve those function.
Instead using the Addons for HUE it makes more sense to complete the eq3 HUE Beta version with additional functions to have a real native Philips HUE integration with status feedback.

**Comment by jens-maus** [comment]
And what should this project (RaspberryMatic) do all about that? Sorry, but we are an independent open source project and the Philips Hue part of the CCU platform is completely closed source java stuff we don't have access to. Thus, open a ticket @ eq3 instead!

**Comment by steckenpferd** [comment]
Thank you for the feedback - did not know about the restrictions
