### ISSUE TITLE
Filter gehen verloren

### ISSUE THREAD

**Issue by HM-klana** [jens-maus/RaspberryMatic#680]
**Describe the bug**
Ein gesetzter Filter bei "Startseite > Programme und Verknüpfungen > Programme" in der Spalte "Name" und auch in der Spalte "Beschreibung" ist nach Aufruf von "Bearbeiten" und anschliessender Rückkehr (egal ob mit Abbruch oder OK) der Filter nicht mehr vorhanden.

**To Reproduce**
1. Menüpunkt Startseite > Programme und Verknüpfungen > Programme aufrufen
2. Filter in der Spalte "Name" oder Beschreibung setzten
3. Dann eines der angezeigten Programme mittel "Bearbeiten" öffnen
4. Schließen des Programms mit "Abbruch" oder "Ok"
5. Filter ist weg und alle Programm werden angezeigt.

**Expected behavior**
In der letzten RM Version wurden die Filter beibehalten

**Screenshots**

**System information (please complete the following information):**
 - Version : RaspberryMatic 3.47.10.20190713
 - Hardware [RaspberryPi3+ und Tinkerboard S]

**Additional context**

**Comment by jens-maus** [comment]
@psi-4ward Can you reproduce and perhaps fix that filter related issue?

**Comment by HM-klana** [comment]
Jetzt bitte in Deutsch.
Aber ich kann dies jederzeit reproduzieren - gerade noch gemacht

**Comment by HM-klana** [comment]
Sorry ich habe den Klammeraffen  nicht gesehen...war gar nicht für mich...

**Comment by jens-maus** [comment]
@HM-klana Also ich hab das gerade selbst mal mit Chrome probiert und es geht hier problemlos. Ich kann einen Filter unter Programme gesetzt haben und dann in eins der Programme zum editieren wechseln, dann Abbruch drücken und er kehrt problemlos zurück und zeigt weiterhin nur die vom filter ausgewählten Programme an.

**Comment by HM-klana** [comment]
Hallo Jens,
habe mir den Chrome gerade runter geladen und nochmal probiert.
Hier geht es auch bei mir...die Filter werden behalten wie es sein soll.
Ich verstehe nur nicht, dass es bei allen anderen Filtern quer durch die Menüs funktioniert und nur bei den Programmen nicht mehr (hat doch schon mal funktioniert)
Gruß
Klaus

**Comment by jens-maus** [comment]
Das müsste sich @psi-4ward einmal genauer anschauen warum in dem Falle es nur mit Chrome funktioniert. Du hattest aber auch noch nicht gesagt mit welchem Browser es bei dir NICHT geht.

**Comment by HM-klana** [comment]
Safari Version 12.1.2 (14607.3.9)
Mojave macOS 10.14.6 (18G87)

**Comment by psi-4ward** [comment]
Hab leider keinen Safari. Kannst du mal in die Dev-Console schauen und sehen ob hier vllt iwelche Errors fliegen? 

Allgemein muss ich gestehen, dass dieses ganze Filter-Zeug schon etwas _hacky_ ist. Leider ist die WebUI **stark** in die Jahre gekommen.

**Comment by HM-klana** [comment]
Hi, es hat etwas gedauert bis ich die richtigen Anzeigen hatte...kenne mich mit den Dev Tools in Safari gar nicht aus. Es erscheint nirgends ein Fehler oder Warning (siehe Screenshot)

Aber das seltsamste kommt ja noch....ich bin seit fast 40 Jahren in der EDV tätig, aber manchmal muss man nicht alles verstehen...
Nachdem ich die Dev-Konsole offen hatte und versuchte den Fehler nachzustellen ...geht es plötzlich wieder!! ich brech' zusammen! Erklären kann ich es nicht!
Der Fehler bestand schon seit der Installation der aktuellen Firmware RM und jetzt ist es weg.

@jens-maus "Ich wurde sagen ...mach das Ticket zu" 
Sorry für viel Wind um nix (oder was auch immer)

Klaus
![Bildschirmfoto 2019-08-14 um 18 55 23](https://user-images.githubusercontent.com/50288602/63040382-a229e480-bec5-11e9-8c50-f9d566434981.jpg)
