### ISSUE TITLE
Kein Update AOI NEO Server auf TinkerboardS, auf Raspberry PI 3+ schon

### ISSUE THREAD

**Issue by HM-klana** [jens-maus/RaspberryMatic#682]
**Describe the bug**
Ein Update des NEO Servers ist mit dem Tinkerboard nicht möglich.
Mit dem gleichen System nur auf einem Raspberry Pi 3+ funktioniert das einwandfrei.

**To Reproduce**
1. Runterladen des Updates im AddOn NEO Server (Menüpunkt ganz unten)
2. Update über "Startseite > Einstellungen > Systemsteuerung->Zusatzsoftware
3. Fehlermeldung bei Tinkerboard "Es ist ein Fehler aufgetreten..." genauen Text habe ich nicht mehr...war aber nichts aussagefähiges. Aus dem Kopf "ist keine passende Datei..."

**Expected behavior**
Updates des NEO Servers sollten wieder funktionieren

**Screenshots**

**System information (please complete the following information):**
 - Version: RaspberryMatic 3.47.10.20190713
 - Hardware: Raspberry Pi3+ und Tinkerboard S

**Additional context**

**Comment by HM-klana** [comment]
Hab mir so beholfen:
Backup des Raspberry PI mit installiertem Update des NEO Servers gemacht und im Tinkerboard eingespielt. NEO Server läuft

**Comment by jens-maus** [comment]
Tut mir leid, das bekomme ich nicht reproduziert. Hier funktioniert das Update des Addons problems, egal ob Tinkerboard oder RaspberryPi. Es ergibt auch absolut keinerlei Sinn das es bei dir angeblich nur unter einem Pi funktioniert hat. Vermute ein anderweitiges Problem.

Zusätzlich dazu hättest du natürlich auch einfach auf die nächste RaspberryMatic warten können, wie von mir angekündigt. Hier scheinst du etwas zu ungeduldig zu sein ;)

**Comment by HM-klana** [comment]
Hallo Jens,
Nein nicht ungeduldig - es kann ja sein, dass da irgendwo der Wurm drin ist und es bei nächsten Update des NEO Servers wieder nicht funktioniert.
Ich kann wirklich mit 100% Sicherheit sagen das beide Systeme aus dem selben Backup erzeugt wurden (der Tinker sogar mehrfach, weil ich dachte da wäre was schief gelaufen)
Gruß
Klaus

**Comment by jens-maus** [comment]
@HM-klana Es ist aber so wie es ist, es geht auch auf einem Tinkerboard. Ging halt nur bei dir nicht, das nächste mal aber sicher. (Achja, und BTW: Bitte nicht auf die GitHub Emails antworten sondern das Webinterface nehmen zum beantworten).
