### ISSUE TITLE
WebUI Anzeige der Startseiten Systeminformationen - Fenster zu klein

### ISSUE THREAD

**Issue by HM-klana** [jens-maus/RaspberryMatic#683]
**Describe the bug**
Der Fehler wurde vor längerem schon mal gemeldet - ich finde da aber nix mehr.
Unter "Startseite > Einstellungen > Benutzerverwaltung->Bearbeiten" werden die Variablen für die Startseite ausgewählt. Hier ist das Fenster zu schmal, wenn die Variableninhalte etwas länger sind (siehe Screenshot)
So muss man immer hin und herscrollen - echt lästig...

**Wenn sich der alte Issue irgendwo versteckt hat, dann lösch diesen hier bitte.**

**To Reproduce**

**Expected behavior**

**Screenshots**
![Bildschirmfoto 2019-08-13 um 17 58 45](https://user-images.githubusercontent.com/50288602/62957170-8a366000-bdf4-11e9-9e32-c86b7565cc2b.jpg)

**System information (please complete the following information):**
 - Version [e.g. RaspberryMatic 3.37.8.20180922]
 - Hardware [e.g. RaspberryPi3, TinkerboardS, etc.]

**Additional context**

**Comment by jens-maus** [comment]
Duplicate of #618

**Comment by HM-klana** [comment]
Da hat er sich versteckt !!!
