### ISSUE TITLE
Raspberrymatic Backup / Restore Failed

### ISSUE THREAD

**Issue by Sschhsd** [jens-maus/RaspberryMatic#684]
Hallo zusammen,

ich habe vor kurzem mein Raspberry Pi 3B mit dem Funk-Modulplatine RPI-RF-MOD und Raspberrymatic (3.47.10.20190713) in Betrieb genommen.
Ich verwende nur Homematic IP Wandthermostate, Heizkörperthermostate und Tür-/Fensterkontakte.

Heute wollte ich testen, ob das Backup (Systemsteuerung / Sicherheit / Backup erstellen) funktioniert.
Dazu habe ich eine zweite SD-Karte genommen und dort das Raspberrymatic-Image drauf gespielt.
Anschließend habe das Backup eingespielt (Systemsteuerung / Sicherheit / Backup erstellen).

Nach einem Reboot war die Oberfläche wieder erreichbar, jedoch konnte ich nicht mehr auf die Geräte zugreifen!
Die Oberfläche hat sich immer wieder aufgehangen und ist neu gestartet.
Anschließend habe ich meine "produktive" SD-Karte wieder in den Raspberry Pi gesteckt.
Nach einem Reboot war die Oberfläche wieder erreichbar, jedoch konnte ich nicht mehr auf die Geräte zugreifen!
Das gleiche Verhalten wie bei der SD-Karte mit eingespieltem Backup.

Anbei befindet sich das Log.

Ist das normal? Habe ich einen Schritt vergessen?

Ich habe jetzt Raspberrymatic neu installiert und alle Geräte neu angelernt...

Viele Grüße,
sschhsd
[homematic-raspi-2019-08-15.log](https://github.com/jens-maus/RaspberryMatic/files/3513058/homematic-raspi-2019-08-15.log)

**Comment by Sschhsd** [comment]
Hallo zusammen,

ich habe heute den RasperryPi ausgeschaltet, damit ich eine externe Antenne anlöten kann.
Nach dem Reboot das gleiche Problem. Ich habe eine zweite SD-Karte aufgesetzt, dort funktioniert das Funkmodul wieder.
Jetzt kann ich alle Endgeräte zurücksetzen und neu anlernen.

Kennt jemand das Problem? Anscheinend tritt das Problem nach jeder Stromunterbrechung auf.

Ich bin für jede Unterstützung dankbar.

**Comment by jens-maus** [comment]
Man sollte generell die Pi nicht einfach so ausschalten, das macht die SD karte mitunter defekt. D.h. man sollte ordentlich den Pi via WebUI herunterfahren und dann erst ausschalten wenn dieser den entsprechenden Status via LED zeigt (rote dauerhaft leuchtende LED). Ein generelles Problem bei anderen Personen kann ich hier nicht entdeckten, daher lässt sich das hier leider auch nicht reproduzieren.
