### ISSUE TITLE
HM-MOD-EM-8bit / Parametereinstellung verschwunden, Version 3.47.10.20190713

### ISSUE THREAD

**Issue by Nooblucker1** [jens-maus/RaspberryMatic#685]
**Describe the bug**

Das Modul HM-MOD-EM-8bit sollte beim Öffnen unter Geräte, dann Einstellen, die Möglichkeit zum Einstellen der Kanäle öffnen bzw. anbieten, dieses geschieht leider nicht - es wird kein Kanal angeboten. Der wichtigste Kanal Nr. 3, hier sollten die Eingänge, der Modus bzw. die Datenübertragungsbedingungen, Max. Sendeversuche aufgelistet werden, dem ist aber nicht so, es erscheint ein weisser Bereich. Ich habe 2 solcher Module, beide weisen das gleiche Verhalten auf.

**To Reproduce**
1. Go to -> Einstellungen, Geräte
2. Click on -> Einstellen
3. Scroll down to -> braucht man nicht
4. See error -> eben der weisse Bildschirm und kein Kanalauswahl bzw. das Modul sollte hier konfiguriert werden können was ja nicht geht da es nichts anzeigt wird.

Es sollte zumindest das erscheinen, siehe unter Screen Shot

**Expected behavior**
Es sollte das Auswahl Menü erscheinen (welches auch in der Gebrauchsanleitung ersichtlich ist), wo das Modul konfiguriert werden kann, was es muss denn ohne diese Konfiguration kann es nicht in die HM-welt eingebunden werden

**Screenshots**
![transmitter-config](https://user-images.githubusercontent.com/46654726/63275916-aa599980-c2a2-11e9-875a-57db5582ccb1.png)

**System information (please complete the following information):**
 - Version: RaspberryMatic 3.47.10.20190713
 - Hardware: RaspberryPi3+, auf einem leeren neu installierten System (RM) sowie auf dem Arbeits-RM ist das gleiche Problem, auf Windows und MAC-Rechner und 3 verschieden Browser (mit gelernten Cache) ist die gleiche Ansicht. 

**Additional context**
Habe das im H-Forum besprochen, keiner konnte weiterhelfen oder kennt das Problem.

**Comment by IT-VBFK** [comment]
@Nooblucker1 sag mal... dein Ernst??

**Comment by IT-VBFK** [comment]
na bitte.. war das so schwer?

**Comment by libertyx82** [comment]
siehe -> https://www.eq-3.de/Downloads/Software/CCU3-Firmware/CCU3-3.47.15/CCU3-Changelog.3.47.15.pdf

```
[HMCCU-354] Bei dem HM-MOD-EM-8Bit Modul (Version 1.0) wurden die Kanalparameter des Kanal 3
in der Gerätekonfiguration nicht mehr dargestellt.
```

**Comment by jens-maus** [comment]
This should be fixed in the just released 3.47.15.20190831 version!
