### ISSUE TITLE
HM-MOD-EM-8Bit kein Parametereinstellungen mehr vorhanden

### ISSUE THREAD

**Issue by Nooblucker1** [jens-maus/RaspberryMatic#686]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
 - Version [e.g. RaspberryMatic 3.37.8.20180922]
 - Hardware [e.g. RaspberryPi3, TinkerboardS, etc.]

**Additional context**

**Comment by Nooblucker1** [comment]
Hallo, hab es auch schon im H-Forum diskutiert, leider kann mir niemand helfen und ja es muss ein BUG sein.

Ich habe das Modull auf einen Backup RaspMatic installiert, komplett neu aufgesetzt und es ist nur das Modul angelernt worden auf der Version 3.47.10.20190713 und leider ist dei Parametereinstellung nicht mehr vorhanden.

Das Modul ist somit unbrauchbar geworden.

LG

Uwe
![Bildschirmfoto 2019-08-05 um 17 16 48](https://user-images.githubusercontent.com/46654726/63247986-a576f480-c266-11e9-977c-38b43f0282a1.png)
![Bildschirmfoto 2019-08-04 um 11 01 21](https://user-images.githubusercontent.com/46654726/63247987-a6a82180-c266-11e9-8d96-91d711c49a24.png)

**Comment by Nooblucker1** [comment]
hab versehentlich geschlossen ... sorry...

**Comment by libertyx82** [comment]
Auf den Bilder kann man leider nichts erkennen und die Fehlerbeschreibung fehlt auch...

**Comment by jens-maus** [comment]
@Nooblucker1 Tut mir leid, aber du musst noch einmal alles schritt-für-schritt beschreiben. Eine wage Aussagen "Habe alles schon im Hm-Forum diskutiert" reicht hier nicht. Das ist kein Diskussionsforum sondern ein Bugtracker wo man im Ticket Template alles ordentlich und mit schritt-für-schritt Anleitung ausführt damit Entwickler hier auch das ganze nicht nur reproduzieren können sondern nicht unnötig zeit damit verbrennen zu verstehen was eigentlich gemeint ist/war. Also bitte zurück aus LOS und neu anfangen mit einem frischen neuen Ticket und dann die zeit nehmen alles ordentlich zu beschrieben und nicht zwischen Tür+Angel einfach schnell mal ein Ticket aufmachen...

**Comment by Nooblucker1** [comment]
Hallo, was soll ich beschreiben ausser das die Parametereinstellungen nicht mehr vorhanden und sichtbar sind ... sie sind einfach weg. und das man auf den Bilder nichts erkennt ist logisch, die Parametereinstellungen sind ja weg (nicht vorhanden) und der andere Printscreen ist aus der Gebrauchsanweisung aus dem Internet. Werde ein neues Ticket machen ab auf Los....

**Comment by jens-maus** [comment]
@Nooblucker1 Die Bilder haben schlechtweg zu niedrige Auflösung und man kann da absolut nix erkennen. und einfach ein Bild aus der Gebrauchsanweisung zu nehmen kannst du dir auch sparen. Zeig was nicht geht und beschreibe wie es sein sollte und nimm dir die zeit das Ticket Template zu lesen und auszufüllen...
