### ISSUE TITLE
HM-MOD-EM-8Bit keine Parametereinstellung mehr vorhanden

### ISSUE THREAD

**Issue by Nooblucker1** [jens-maus/RaspberryMatic#687]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
 - Version [e.g. RaspberryMatic 3.37.8.20180922]
 - Hardware [e.g. RaspberryPi3, TinkerboardS, etc.]

**Additional context**

**Comment by Nooblucker1** [comment]
Hallo,
Nachdem ich auf dem RasberryMatic feststellen musste, dass keine Einstellungen mehr auf dem Modul vorgenommen werden konnte, wandte ich mich an das Forum, und habe alles was dort beschrieben wurde ausgeführt (Cache leeren, Windows- und Macrechner, 3 verschiedene Browser, Neuinstallation, BackUp etc.) nichts hat geholfen. 

Also habe ich einen 2ten RasberryMatic mit der neusten Version aufgesetzt und nur das besagte Modul installiert, kein anderes Modul  ist angelegt und hier das gleiche Bild, keine Einstellungen in Bezug auf ** CH.: 3** hier sollten die 8 Eingänge aufgelistet werden, die MAX Sendeversuche, die Übertragungsbedinungen und Datenstabilitätsfilterzeit vor der Sendung angezeigt werden, es ist einfach nichts vorhanden. Ich habe 2 solcher Module, bei beiden Modulen wird unter Einstellungen die Geräte LED, LOW-Bat-Schwelle, Max. Sendeversuche und Reset Funktion angezeigt, es fehlt der Ch. 2 & 3. 

Ich gehe davon aus dass es ein BUG in der Version sein muss und von daher habe ich diesen Weg gewählt, sollte er falsch sein entschuldige ich mich mal vorab. 

LG
Uwe

**Comment by jens-maus** [comment]
@Nooblucker1 Entschuldigung, aber du machst schon wieder die selben Fehler. Das Ticket Template gehört ausgefüllt und nicht einfach abgeschickt. Das hier ist ein Ticket System und kein Forum wo man "Posts"/"Beiträge" schreibt. Bitte halte dich daran, les das template durch und füll es aus und schreib dein Text da rein ohne "Hallo" oder "LG" oder sowas. das ist alles nicht notwendig weil Ticket System wo man ein Problem beschreibt und nicht mehr oder weniger.
