### ISSUE TITLE
Alarmzone 1 wird automatisch angelegt

### ISSUE THREAD

**Issue by mcchickents** [jens-maus/RaspberryMatic#690]
Guten Tag zusammen,

wenn ich meine CCU neustarte erstellt sich immer eine neue Alarmzone  1 hinzu. Hab etwas gebraucht um herauszufinden das immer ein neustart der Auslöser ist.  

3.45.7.20190511

  ACHTUNG / ATTENTION:
  ===================
  BITTE DIESES TEMPLATE NICHT LÖSCHEN (!!) SONDERN AN DEN JEWEILIGEN
  STELLEN MIT EIGENEN INFORMATION ERGÄNZEN/AUSFÜLLEN.

  BITTE HIER KEINE HILFEANFRAGEN FÜR DIE BEDIENUNG/NUTZUNG VON
  RASPBERRYMATIC, SONDERN HIERFÜR DAS RASPBERRYMATIC FORUM VERWENDEN:
  https://homematic-forum.de/forum/viewforum.php?f=65

  HINWEIS:
  =======
  - GitHub ist KEIN Diskussionsforum -> RaspberryMatic Forum verwenden
  - Bitte NUR Meldungen absetzen die auf einen direkten Fehler/Bug
    in RaspberryMatic schliessen lassen oder nachvollziehbare
    Featurewünsche sind (am besten erst im Forum diskutieren)
  - Bitte NUR Fehler melden die mit der aktuellen RaspberryMatic
    Version bereits reproduziert werden konnten.
  - Im Zweifel das Anliegen zuerst im RaspberryMatic Forum mit anderen
    Nutzern diskutieren und erst bei Konsens hier ein Ticket eröffnen.

  == ENGLISH VERSION ==

  PLEASE DON'T DELETE THIS TEMPLATE (!!) BUT FILL IT WITH YOUR
  OWN INFORMATION AT THE SPECIFIC POINTS.

  DON'T USE THIS TICKET SYSTEM FOR FINDING HELP IN USING RASPBERRYMATIC.
  USE THE RASPBERRYMATIC FORA INSTEAD:
  https://homematic-forum.de/forum/viewforum.php?f=65
  
  NOTE:
  =====
  - Do NOT submit anything other than bug reports or feature requests via the issue tracker!
  - Do NOT submit bug reports about anything but the two most recently released versions!
--->

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
 - Version [e.g. RaspberryMatic 3.37.8.20180922]
 - Hardware [e.g. RaspberryPi3, TinkerboardS, etc.]

**Additional context**

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template, das man übrigens ausfüllen und nicht einfach ignorieren soll!

**Comment by mcchickents** [comment]
was ist daran kein Bug, das bei  jedem neustart eine System variabel erzeugt wird?

**Comment by jens-maus** [comment]
@mcchickents Wie schon geschrieben ist dies hier kein Diskussionsforum! Und du hast das Ticket Template einfach mal geschickt ignoriert und einfach dein Text oben hingeschrieben statt es ordentlich auszufüllen wie es im Template geschrieben steht. Auch würde ich darum bitte das erst einmal im Homematic forum zu diskutieren um herauszufinden ob du der einzige bist (nachdem sieht es nämlich aus) oder ob andere dein problem bestätigen können. Und erst wenn es von anderen bestätigt wurde oder du dir 100% sicher bist da es ein Bug in RaspberryMatic selber ist (was in dem falle unwahrscheinlich ist da du der einzige von tausenden bist der das problem aktuell meldet) dann kannst du hier unter Beachtung des Templates ein Ticket aufmachen in dem du das Problem auch mit mehr als einem Satz beschreibst.

**Comment by friedpa** [comment]
Habe das getestet. Tritt bei mir nicht auf.

**Comment by mcchickents** [comment]
Alles klar hab ein Thread im Forum eröffnet hier der Link dazu.
https://homematic-forum.de/forum/viewtopic.php?f=65&t=53003
