### ISSUE TITLE
WebUI: DutyCycle-Display der Startseite zeigt sich bei Neuladen in unlogischer Darstellung

### ISSUE THREAD

**Issue by Papi32** [jens-maus/RaspberryMatic#694]
**Describe the bug**
Das DutyCycle-Display auf der Startseite zeigt sich bei Neuladen der Startseite in unlogischer Darstellung, siehe Screenshot 1. Nach kurzer Zeit springt die Anzeige dann in eine realistische Darstellung um, obwohl sich die DCs nur marginal bis gar nicht verändert haben.
(Ich hoffe, dass ich das hier korrekt verfasse, stehe mit Github noch auf Kriegsfuß)

**To Reproduce**
1. Go to Startseite
2. Click on gar nichts
3. Scroll down to Seitenende
4. See error oder eher missbehaviour

**Expected behavior**
Ich würde erwarten, dass bereits direkt nach dem Laden der Seite die korrekte Darstellung gezeigt wird.

**Screenshots**
1 und 2, siehe Anhang

**System information (please complete the following information):**
 - Version 3.47.15.20190831
 - Hardware RaspberryPi3

**Additional context**
Verwendeter Browser: Chrome Version 76.0.3809.132 (Offizieller Build) (64-Bit)
IE kann ich zurzeit nicht testen, das Webgui lässt sich aktuell darin nicht aufrufen (mein Fehler?)
<img width="405" alt="1" src="https://user-images.githubusercontent.com/43516312/64077351-163ef780-ccd0-11e9-964e-abbb27325f86.png">
<img width="395" alt="2" src="https://user-images.githubusercontent.com/43516312/64077352-16d78e00-ccd0-11e9-8688-e2e842272479.png">

**Comment by libertyx82** [comment]
Das kann ich bestätigen, teilweise wird beim Aufruf der Startseite ist der Anzeigebalken falsch, der Wert ist aber korrekt.

![image](https://user-images.githubusercontent.com/22996350/64077532-b1849c80-ccd1-11e9-876c-b956d817a7d2.png)

Teilweise reicht eine Aktualisierung aus, damit der Anzeigebalken korrekt ist, teilweise muss aber auch mehrfach aktualisiert werden.

**Comment by jp112sdl** [comment]
Das Ticket hier kann doch auch zu, oder?
Sollte spätestens seit Umstellung auf Bootstrap nicht mehr auftreten
