### ISSUE TITLE
Schreibfehler in Menü für Systemvariable

### ISSUE THREAD

**Issue by ptweety** [jens-maus/RaspberryMatic#696]
**Is your feature request related to a problem? Please describe.**
In den Untermenüs von "_Status und Bedienung_" und "_Einstellungen_" sollte "_Systemvariable_" im Plural geschrieben werden.

**Describe the solution you'd like**
Hier ein möglicher Patch:

```
--- translate.lang.js.orig
+++ translate.lang.js
@@ -62,7 +62,7 @@
     "submenuFavorites" : "Favoriten",
     "submenuCreateFavorite" : "Favoriten erstellen",
     "submenuPrograms" : "Programme",
-    "submenuSysVar" : "Systemvariable",
+    "submenuSysVar" : "Systemvariablen",
     "submenuSysProtocol" : "Systemprotokoll",
     "submenuDirectLinks" : "Direkte Verkn%FCpfungen",
     "submenuProgramsLinks" : "Programme & Zentralenverkn%FCpfung",
@@ -319,7 +319,7 @@
     "lblSettingsFunctions5" : "Gewerkeigenschaften bearbeiten",
     "commentSettingsBtnFunctionsEnd" : "***********************************************",
     "commentSettingsBtnSysVar" : "***********************************************",
-    "btnSettingsSysVar" : "Systemvariable",
+    "btnSettingsSysVar" : "Systemvariablen",
     "lblSettingsSysVar1" : "%DCbersicht aller Systemvariablen",
     "lblSettingsSysVar2" : "Bestehende Systemvariablen bearbeiten",
     "lblSettingsSysVar3" : "Neue Systemvariablen anlegen",
@@ -445,7 +445,7 @@
     "lblMenuStatusControlFavorites1" : "%DCbersicht aller verf%FCgbaren Favoriten",
     "btnMenuStatusControlPrograms" : "Programme",
     "lblMenuStatusControlPrograms1" : "Direkter Zugriff auf alle Programme",
-    "btnMenuStatusControlSysVars" : "Systemvariable",
+    "btnMenuStatusControlSysVars" : "Systemvariablen",
     "lblMenuStatusControlSysVars1" : "Status%FCbersicht aller verwendeten Systemvariablen ohne Kanalzuordnung",
     "btnMenuStatusControlSysProtocol" : "Systemprotokoll",
     "lblMenuStatusControlSysProtocolTime" : "Zeit",
```

**Comment by jens-maus** [comment]
Fixed in e04ae18022a44a6bf45c4690293bbcbb958bf949

**Comment by roe1974** [comment]
Hallo Jens

Hier noch meine Ergönzung, hoffe es passt ;-)

`--- translate.lang.js.orig
+++ translate.lang.js
@@ -62,10 +62,10 @@
     "submenuFavorites" : "Favoriten",
     "submenuCreateFavorite" : "Favoriten erstellen",
     "submenuPrograms" : "Programme",
-    "submenuSysVar" : "Systemvariable",
+    "submenuSysVar" : "Systemvariablen",
     "submenuSysProtocol" : "Systemprotokoll",
     "submenuDirectLinks" : "Direkte Verkn%FCpfungen",
-    "submenuProgramsLinks" : "Programme & Zentralenverkn%FCpfung",
+    "submenuProgramsLinks" : "Programme & Zentralenverkn%FCpfungen",
     "submenuDeviceInbox" : "Ger%E4te - Posteingang",
     "submenuUserManagement" : "Benutzerverwaltung",
     "submenuSysControl" : "Systemsteuerung",
@@ -109,7 +109,7 @@
     "thValues" : "Werte",
     "thUnit" : "Ma%DFeinheit",
     "thLastUpdate" : "Letzte<br/>Aktualisierung",
-    "thControl" : "Control",
+    "thControl" : "Bedienung",
     "thFilter" : "Filter",
     "thDescription" : "Beschreibung",
     "thActivity" : "Aktivit%E4t",
@@ -319,7 +319,7 @@
     "lblSettingsFunctions5" : "Gewerkeigenschaften bearbeiten",
     "commentSettingsBtnFunctionsEnd" : "***********************************************",
     "commentSettingsBtnSysVar" : "***********************************************",
-    "btnSettingsSysVar" : "Systemvariable",
+    "btnSettingsSysVar" : "Systemvariablen",
     "lblSettingsSysVar1" : "%DCbersicht aller Systemvariablen",
     "lblSettingsSysVar2" : "Bestehende Systemvariablen bearbeiten",
     "lblSettingsSysVar3" : "Neue Systemvariablen anlegen",
@@ -445,7 +445,7 @@
     "lblMenuStatusControlFavorites1" : "%DCbersicht aller verf%FCgbaren Favoriten",
     "btnMenuStatusControlPrograms" : "Programme",
     "lblMenuStatusControlPrograms1" : "Direkter Zugriff auf alle Programme",
-    "btnMenuStatusControlSysVars" : "Systemvariable",
+    "btnMenuStatusControlSysVars" : "Systemvariablen",
     "lblMenuStatusControlSysVars1" : "Status%FCbersicht aller verwendeten Systemvariablen ohne Kanalzuordnung",
     "btnMenuStatusControlSysProtocol" : "Systemprotokoll",
     "lblMenuStatusControlSysProtocolTime" : "Zeit",`

lg Richard
