### ISSUE TITLE
HmIP-PSM (Kanalparameter Kanal:7 - Konfiguration Entscheidungswert) Eingabemaske fehlerhaft

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#702]
**Describe the bug**
Bei HmIP-Komponenten mit Leistungsmessung (gestestet HmIP-PSM) kann in der Gerätekonfiguration bei Kanal 7 (Konfiguration Entscheidungswert) der obere und untere Grenzwert in W (0 - 3680) eingegeben werden. Gebe ich z.B. 25 (unterer) und 105 (oberer) ein, schließe die Einstellungen mit "OK" und öffne sie erneut, steht plötzlich 250.0 (Unterer GW) und 1050.0 (Oberer GW) drin. 

**To Reproduce**
1. Go to 'Einstellungen > Geräte > HmIP-PSM > Geräte-/ Kanalparameter einstellen'
2. Scroll down to 'Konfiguration Entscheidungswert'
3. Enter '25' at 'Unterer Grenzwert'
4. Click on 'OK' to close and save the Settings
5. reopen > 'Geräte > HmIP-PSM > Geräte-/ Kanalparameter einstellen'
6. look at the Value at 'Unterer Grenzwert' to see it's now '250.0' instead of '25'

**Expected behavior**
The Input-Value i have made should be the same after reopening the settings.

**Screenshots**
25 (bei Unterer Grenzwert) und 105 (bei Oberer Grenzwert) eingegeben...
![PSM_Entscheidungswert_Maske_RM3 47 15 20190831_vorher](https://user-images.githubusercontent.com/54898249/64262722-d164cc00-cf2e-11e9-8443-264b6d31c271.JPG)

Nach dem erneuten Öffnen stehen 250 (bei Unterer GW) und 1050 (bei Oberer GW) drin.
![PSM_Entscheidungswert_Maske_RM3 47 15 20190831_reopen](https://user-images.githubusercontent.com/54898249/64262803-f35e4e80-cf2e-11e9-90e5-18db50ad893e.JPG)

**System information (please complete the following information):**
 - Version [RaspberryMatic 3.47.15.20190831]
 - Hardware [RaspberryPi3B]

**Comment by jens-maus** [comment]
Kann das jemand reproduzieren? Ist das verhalten gleich mit der originalen CCU3 Firmware?

**Comment by Baxxy13** [comment]
Hallo Jens. Habe heute mal zum testen CCU3 FW 3.47.18  aufgesetzt und konnte exakt das gleiche Verhalten beobachten.
**Screenshots** 
25 (bei Unterer Grenzwert) und 150 (bei Oberer Grenzwert) eingegeben...
![PSM_Entscheidungswert_Maske_HM3 47 18_vorher](https://user-images.githubusercontent.com/54898249/65495034-4f751c80-deb6-11e9-8c8b-16d557cd6028.JPG)

Nach dem erneuten Öffnen stehen 250 (bei Unterer GW) und 1500 (bei Oberer GW) drin.
![PSM_Entscheidungswert_Maske_HM3 47 18_reopen](https://user-images.githubusercontent.com/54898249/65495092-69166400-deb6-11e9-9046-a119b7530f1c.JPG)

**System information (please complete the following information):**

- Version [CCU3 Firmware 3.47.18]
- Hardware [RaspberryPi3B]

**Comment by jens-maus** [comment]
Ok danke. Dann ist klar das das wohl ein genereller Bug in der CCU WebUI ist und nichts spezielles von RaspberryMatic. Ergo müsste hier eQ3 tätig werden und diesen Bug reparieren.

**Comment by Baxxy13** [comment]
Hallo Jens, seit dem letzten Release (RaspberryMatic 3.49.17.20191225) ist das Problem behoben.
Grüße
Baxxy
