### ISSUE TITLE
Firmware-Update: Update-Button wird nicht angezeigt

### ISSUE THREAD

**Issue by ThorstenNauroth** [jens-maus/RaspberryMatic#704]
**Describe the bug**
Die Firmware wird offensichtlich auf die jeweiligen Geräte geladen. Unter "Einstellungen" fehlt dann aber der Button um das Update durchzuführen.

**To Reproduce**
1. Neue HMIP Firmware in CCU3 bereitstellen
2. Firmware wird an die jeweiligen Geräte übertragen
3. Firmware-Update kann nicht durchgeführt werden, da der Button "Update starten" in den Geräteeinstellungen fehlt (Beispiel-Screenshots beigefügt)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/43105965/64470986-f71aec80-d14b-11e9-857e-6612e8be1870.png)
![grafik](https://user-images.githubusercontent.com/43105965/64470998-1580e800-d14c-11e9-9e65-a366dabf318b.png)

**System information (please complete the following information):**
 - Version: 3.47.15.20190831
 - Hardware: CCU3

**Comment by jens-maus** [comment]
Das ist kein Bug. Der Knopf ist nun unter "Einstellungen -> Gerätefirmware-Übersicht" zu finden und nicht mehr unter den Einstellungen des jeweiligen Gerätes wie früher. Das wurde im Zuge von 3.47.15 von eQ3 so implementiert.

**Comment by ThorstenNauroth** [comment]
Großes Sorry und vielen Dank für die super schnelle Antwort! Ich hatte extra im Forum gesucht etc. aber diese Änderung leider nicht gefunden.
