### ISSUE TITLE
Funkverbindung HmIP gestört

### ISSUE THREAD

**Issue by pitje-87** [jens-maus/RaspberryMatic#705]
**Describe the bug**
Anscheinenend ist erneut die Funkverbindung zu HmIP gestört _(hatten wir vor einigen Versionen schon mal, ich glaube die Lösung war irgendwie was mit dem HDMI Port. Bin mir aber nicht mehr sicher)_. Speziell ist mir das bei den Fenstergriffsensoren (HmIP-SRH, Firmware 1.2.10 und 1.0.1 ) aufgefallen. Nach dem betätigen der Sensoren blinken diese mehrfach orange und anschließend einmal rot. 

Programme mit den Fenstersensoren werden jedoch jedes Mal zeitnah nach Betätigung wie gewohnt ausgeführt. Ich vermute, dass hier die Antwort/ Bestätigung vom RaspberryMatic an den Griffsensor nicht ankommt. Dies hatten wir vor einiger zeit hier schonmal.

**Expected behavior**
Wie gewohnt sollten die Griffsensoren nach betätigung einmal orange und anschließend grün Blinken und eine erfolgreiche bidirektionale Kommunikation _(CCU <--> Sensor)_ signalisieren.

**System information**
 - Version: RaspberryMatic 3.47.15.20190831
 - Hardware RaspberryPi2b, Homematic Funkmodul 1

**Additional context**
Update von 3.45.7.20190511 (HmIP i.O.) -> 3.47.15.20190831 (HmIP n.i.O.) wurde zuvor durchgeführt.

Danke Jens.

**Comment by 10-11-12-13** [comment]
Ich nutze einen Raspi 3B und kann das Verhalten so nicht bestätigen mit der 3.47.15.20190831 und SRH 1.2.10. Mit der alten SRH Version 1.0.1 hatte ich ebenfalls noch Kommunikationsprobleme. Nach dem Update ist dies aber nicht mehr der Fall.
Nutze auch das alte Homematic Funkmodul.

**Comment by pitje-87** [comment]
Leider habe ich heute festgestellt, dass das Problem auch den HmIP-RCB1 betrifft und dieser keine Rückmeldung von der CCU bekommt und mit "Rot" bestätigt.

Das Problem besteht weiterhin auch bei den Fenstergriffsensoren mit der neueren Firmware 1.2.10. 

LG

**Comment by pitje-87** [comment]
Habe heute ein Rollback auf die Version RaspberryMatic-3.47.10.20190713-rpi3 gemacht. Hier funktioniert die Kommunikation problemlos. Muss sich also um einen Softwarefehler der aktuellen Version handeln.

"Never touch a running system!"

**Comment by jens-maus** [comment]
Bitte mal die aktuelle 3.47.18.20190918 probieren. Hier wurden noch ein paar Änderungen bzgl. HDMI consolendarstellung integriert die ggf. einen positiven Effekt auf die Funkqualität haben könnten.

**Comment by jens-maus** [comment]
This ticket has been closed because of inactivity of the ticket owner and due to the fact that no developer could reproduce the issue. Please reopen the ticket once it can be reproduced again or the ticket owner can reply accordingly.
