### ISSUE TITLE
Nur optional: alphabetische Favoriten-Sortierung

### ISSUE THREAD

**Issue by TomMajor** [jens-maus/RaspberryMatic#706]
**Is your feature request related to a problem? Please describe.**

Das neue Feature Favoriten-ComboBox-Sortierung sowie alphabetische Sortierung der Menüeinträge finden einige Benutzer inklusive mir nicht gelungen. Solche UI Änderungen sollten optional sein.
Ich zitiere mal hier ein paar Argumente die mir gefallen bzw. auch meine eigenen:

> Menüpunkte nach Funktionsgruppen oder Nutzungsverhalten zu sortieren macht ja noch (in vielen Fällen) Sinn, aber nach Alphabet? Lustig auch, wenn man mal die Sprache wechselt, dann sind plötzlich alle Menüpunkte in einer anderen Reihenfolge.
Aber vielleicht kann ja mal jemand erklären, wo die Steigerung des User-Experiences liegt, wenn man Menüpunkte alphabetisch sortiert. ...
mule

> es gibt genug (auch wissenschaftliche) Abhandlungen darüber, wie gutes UX Design funktioniert. Viel läuft darauf hinaus, dass die Augen des Benutzers nicht weit schweifen müssen und man in der jeweiligen Situation nicht suchen muss, sondern die jeweils benötigte Funktion schnell erreicht. Mit einem alphabetisch sortierten Menü wird man das sehr sicher nicht erreichen. ...
Jetzt kann man natürlich vortrefflich darüber streiten, ob das Menü vorher bereits sinnvoll aufgebaut war oder ob die Sortierung das verbessert hat. Aber in jedem Fall wird das sortierte Menü nicht das Optimum darstellen.
deimos

> Aus meiner Sicht wäre Jens möglicherweise gut beraten, bei derart polarisierenden Themen die Abschaltmöglichkeit von sich aus gleich mit einzubauen, wenn er Änderungen dieser Art vornimmt - im Gegensatz zu Sachen wie dem Autologin, bei einer solchen notwendigen Security Änderungen muss man nicht viel fragen.
Wie viele RaspberryMatic user mag es geben, 10000 oder mehr? Bei einer Abstimmungsquote von (heute) 28:15 usern zu vermuten, die Mehrheit wollte das Feature Menüsortierung ist imho etwas problematisch.
TomMajor

**Describe the solution you'd like**

1. Abschaltung der alphabetischen Menüsortierung falls eine Datei /usr/local/etc/config/sortMenusDisabled
existiert

2. Abschaltung der alphabetischen Favoritensortierung falls eine Datei /usr/local/etc/config/sortFavoritesDisabled
existiert

**Describe alternatives you've considered**

- nicht auf die 3.47.15.20190831 updaten, auf Dauer keine Lösung
- den patch per Hand nach jedem Update machen, nervt auch auf Dauer

Das wäre mein Startpunkt:

An geeigneter Stelle Code dieser Art ausführen:

```
if [ -f /usr/local/etc/config/sortMenusDisabled ]; then
    # not sure about the path
    # is the patch command correct?
    patch -R < ??/buildroot-external/patches/occu/0061-WebUI-MenuSortedIcons.patch
fi
```

```
if [ -f /usr/local/etc/config/sortFavoritesDisabled ]; then
    # not sure about the path
    # is the patch command correct?
    patch -R < ??/buildroot-external/patches/occu/0062-WebUI-Fix-SortFavoritesCombobox.patch
fi
```
Ich kenne mich jedoch nicht mit buildroot und dem Installationsmechanismus von RaspberryMatic aus so dass ich hier definitiv Hilfe bräuchte um einen PR zu machen.

Wo wäre die geeignete Stelle um während der Installation die beiden Patches zu reversen?

Danke,

**Comment by jens-maus** [comment]
Eine eigene Menüsortierung kann nun seit 3.47.18.20190918 wie im entsprechenden PullRequest beschrieben vorgenommen werden:

https://github.com/jens-maus/RaspberryMatic/pull/709

Bzgl. manueller Favoritensortierung muss hier allerdings noch etwas Arbeit erledigt werden, dann aber nicht wie hier beschrieben sondern via WebUI Möglichkeiten zur eigenen Sortierung von Favoriten.

**Comment by ptweety** [comment]
@jens-maus Ist denn wirklich die Sortierung des Drop-Down das Problem einiger Nutzer?

M.E. ist es eher der Fall, dass Nutzer einen ganz bestimmten Favoriten auf der Startseite angezeigt bekommen wollen. Einen vorausgewählten Favoriten also.

Damit geht es also gar nicht so sehr darum, die Favoriten nach Wunsch zu sortieren, sondern einen ganz Bestimmten als Default / Voreingestellt zu markieren und dann eben auch als erstes anzuzeigen.

Als Ergebnis kann dann sicher die Liste der Favoriten im Drop-Down alphabetisch sortiert sein, solange nur der Default dann ausgewählt und angezeigt wird.

**Comment by jens-maus** [comment]
@ptweety Da hast du sicher recht. Allerdings denke ich ist es einfacher eine manuelle Sortiermöglichkeit des Favoritendropdown umzusetzen als jetzt irgendwo noch zu vermerken welcher favorite der default sein soll.

**Comment by jens-maus** [comment]
FYI: Mit der letzten Änderung (siehe oben) kann man nun Nutzer-Favoriten manuell sortieren. Siehe:

![screenshot_327](https://user-images.githubusercontent.com/5887769/65584780-b7dd0000-df81-11e9-8a5d-d95a151c0212.png)

Das sollte dann dazu führen das die Einträge in der ComboBox entsprechend dann sortiert werden.

**Comment by TomMajor** [comment]
War im Urlaub und sehe jetzt das beide enhancements schon drin sind, werde ich die nächsten Tage testen.
Vielen Dank @jens-maus und @ptweety für die Implementierung! :+1:
