### ISSUE TITLE
HmIP-SMI Firmware Update: RM meldet alle Geräte mit Status "Gerätekommunikation gestört"

### ISSUE THREAD

**Issue by friedpa** [jens-maus/RaspberryMatic#707]
**Describe the bug**
Nachdem eine neue Firmware für das Gerät HmIP-SMI verfügbar ist, wollte ich diese installieren.
Nach Download und Zuweisung startet der Download Prozess zum HmIP-SMI. Nach einiger Zeit ging der HmIP-SMI in den Status "Gerätekommunikation gestört" Dieser Zustand kam und ging.
Nach zwei Tagen ging dann der DC der RM auf 0% und alle Geräte die auf der CCU eingeloggt sind gingen auch in den "Gerätekommunikation gestört" Status. Es war nicht mehr möglich diese Geräte zu bedienen. Nach Neustart der RM funktioniert wieder alles normal, aber der gleiche Prozess wie oben beschrieben startet von vorne. Erst das Entfernen der Firmware des HmIP-SMI stoppte dieses Verhalten.

**To Reproduce**
1. Firmware downloaden
2. Firmware update starten

**Expected behavior**
Erfolgreicher Firmware Update wie auch bei anderen Geräten

**System information (please complete the following information):**
 - Version RaspberryMatic 3.47.15.20190831]
 - Hardware RaspberryPi3+

**Screenshots**
![image](https://user-images.githubusercontent.com/42890695/64511413-8d821600-d2e4-11e9-9f81-b1e0124c0684.png)

**Comment by pitje-87** [comment]
Hallo, das Problem könnte auch mit meinem Kommunikationsproblem zusammenhängen.
https://github.com/jens-maus/RaspberryMatic/issues/705

**Comment by jens-maus** [comment]
Ich kann in dem Verhalten kein Fehler entdecken. Das Firmware-Update von Geräten lässt den DutyCycle nunmal hochsteigen und hier kann es mitunter sogar zu Kommunikationsstörungen kommen bis die Updates durch sind. Ergo, normales Verhalten.
