### ISSUE TITLE
Unable to boot on raspberry pi 4

### ISSUE THREAD

**Issue by jrester** [jens-maus/RaspberryMatic#708]
**Describe the bug**
Trying to boot RaspberryMatic results in (random) led blinking of both the red and green led:
At first the red led runs on with the green led blinking but slowing going off. After some time the green led starts blinking with 2 flashes with the red led randomly blinking in between somtimes. This flash pattern of the green led indicates it is a problem with reading the SD card. I tried with 3 different SD cards: one 16 GB Intenso, 32 GB SanDisk and a 64 GB SanDisk, so I don't think it is a problem with the SD card. The red blinking normally indicates insufficient power supply voltage, but I tried multiple power supplies and USB-C cables but nothing helped, and the raspberry pi works perfectly fine with the standard raspian buster and arch linux image. 

I also tried building the master branch of RasberryMatic but is didn't help either.

**Expected behavior**
Raspberry pi booting RaspberryMatic
**System information**
 - Version: RaspberryMatic 3.47.15.20190831 and RaspberryMatic master branch
 - Hardware: Raspberry Pi 4 4GB

**Comment by friedpa** [comment]
I tried a RM for Modell 3 on a Modell 4 and I got almost the same behaviour as described above. Are you sure you downloaded the RM for the Raspberry PI 4?

**Comment by jens-maus** [comment]
If this doesn‘t solve your problems please also try the test/release candidate version from here:

https://cloud.light-speed.de/s/xby5d4B7YFRCxyH

This version should fix some pi4 issues, I hope.

**Comment by jrester** [comment]
> I tried a RM for Modell 3 on a Modell 4 and I got almost the same behaviour as described above. Are you sure you downloaded the RM for the Raspberry PI 4?

When booting the image for RM for model 3 only the red led is on and nothing else happens

> If this doesn‘t solve your problems please also try the test/release candidate version from here:
> 
> https://cloud.light-speed.de/s/xby5d4B7YFRCxyH
> 
> This version should fix some pi4 issues, I hope.

Flashing the new image results in the same led blinking pattern.

Is there any way to access any kind of log on the raspberry PI when booting?

**Comment by jens-maus** [comment]
You can only connect a hdmi monitor an report what you see.

**Comment by jrester** [comment]
When connecting the monitor the signal indicator on the monitor lights up for a short amount of time and then just goes off without the monitor displaying anything.

**Comment by jens-maus** [comment]
Then I am out of ideas, I am afraid.

**Comment by friedpa** [comment]
One more question: does the Raspberry Pi 4 start with a normal Debian Buster Image?

**Comment by jrester** [comment]
> One more question: does the Raspberry Pi 4 start with a normal Debian Buster Image?
Yeah, it works perfectly with the buster but not with RM. 


> Then I am out of ideas, I am afraid.

Has anyone got RM running on an Raspberry PI 4 with 4GB? It would be good to know if this is a general problem with the 4GB Version or just with my specific unit. If that is the case I might just get a new one...

**Comment by jens-maus** [comment]
I just bought a 4GB model for my test environment and it works perfectly.

**Comment by friedpa** [comment]
Same with me, using a PI4 with RM without any problems. Question: are you using the RPI-RF-MOD? If yes, how did you to the Stacking Header? Have a look at:
https://technikkram.net/2019/07/pivccu3-umstieg-homematic-auf-den-neuen-raspberry-pi-4

**Comment by jrester** [comment]
I'm using the old HM-MOD-RPI-PCB which should fit on the GPIO pins without any problems.

Could it cause a problem if the module is not working properly? I tried it with and without the module both times I got the same result.

How far is the docker development? Maybe it is possible to run RaspberryMatic in a container.

**Comment by friedpa** [comment]
I used only the new RPI-RF-MOD and it worked fine. Sorry, I do not have any experience with the "old" RPI-PCB

**Comment by jens-maus** [comment]
Is the problem still valid for the latest 3.47.18.20190918 release?

**Comment by jrester** [comment]
Yes, the problem wasn't fixed

**Comment by jens-maus** [comment]
Sorry, but then I am out of ideas. The two test RaspberryPi4 I have (one 2GB and one 4GB) work without any issues with the latest RaspberryMatic.

**Comment by jens-maus** [comment]
Sorry, but for me the rpi4 version works on multiple rpi4 versions. As this must be an issue on your side, I will close this issue.

**Comment by BenjaminZimbal** [comment]
Hey there folks!

I just wanted to share my experience here because I got to fix this issue.

I flashed RM onto a 64 GB SDXC card and the exact same problems showed up. 
As I have little but existing knowledge about file systems so I then searched if it could be the problem.

And voila! RM seems to need the FAT32 format, which windows simply cannot use on cards bigger than 32 GB space. It will usually format them to exFAT. There is a program made by HP out there which **might** work to format your SDXC card to FAT32, but Etcher will most likely get rid of this whilst flashing. I went out and bought a SD**HC** card with 16 GB of space, flashed and it worked like a charm first try.

Maybe this is the case here too?

Hope I could help you out here!

**Comment by jens-maus** [comment]
@BenjaminZimbal Sorry, but I don't really understand here. Etcher simply flashes the *.img as it is to the SD card, no matter if it is a 16GB or 64GB card. This has nothing todo with FAT32 being used. So I really can't see why the 64GB SDXC card should not work. IMHO either your used card reader cannot work with SDXC cards or the card was broken. Here I have several 64GB cards working flawlessly with RaspberryMatic.

**Comment by BenjaminZimbal** [comment]
@jens-maus I don't really know what was going on. I used the 64 GB card before with Raspbian and OpenHAB2 and it worked well, only had some trouble with RM now. But as I said, the 16 GB card works fine.

I just looked through the internet and found some people having this problem with other OS' so I thought this might apply here too.
