### ISSUE TITLE
Falsche Helligkeitsangabe beim HMIP-SPI

### ISSUE THREAD

**Issue by Gluehwurm** [jens-maus/RaspberryMatic#710]
Seit einiger Zeit wird die Helligkeitsangabe beim HMIP-SPI falsch dargestellt. Bewegt sich trotz hellem Raum nur im unteren Bereich 0-1xx.

Forenthema hier
https://homematic-forum.de/forum/posting.php?mode=reply&f=58&t=51902#pr529266

Mit der 3.47.10.20190713 funktioniert es wohl noch richtig, danach nicht mehr.

**Comment by LevelOne2k** [comment]
Ich kann das bestätigen. Bis Version 3.47.10.20190713 funktioniert es ganz normal. Auch mit der aktuelle CCU3 Firmware gibt es keine Probleme.

**Comment by Macem79** [comment]
Ich habe auch das Problem. Mein Präsenzmelder kommt nicht über 4 in der Helligkeit. Getestet mit RaspberryMatic 3.47.15.20190831

Wenn ich zurück auf die RaspberryMatic Version von Juli gehe, dann funktioniert die Helligkeit von dem Präsenzmelder einwandfrei.

**Comment by jens-maus** [comment]
Um zu klären ob hier wirklich ein Problem vorliegt bitte mal einen SPI mit der CCU3 3.47.x firmware und einen mit RaspberryMatic 3.47.x anlernen und am besten die rohen Helligkeitswerte mit XML-API oder ähnlichem ausgeben damit das ganze wie folgt aussieht:

```
<channel name="Präsenzmelder-Küche" ise_id="55162" index="1" visible="true" operate="true">
<datapoint name="HmIP-RF.XXXXXXXXXXXXX:1.CURRENT_ILLUMINATION" type="CURRENT_ILLUMINATION" ise_id="55163" value="1.000000" valuetype="4" valueunit="" timestamp="1568404230" operations="5"/>
<datapoint name="HmIP-RF.XXXXXXXXXXXXX:1.CURRENT_ILLUMINATION_STATUS" type="CURRENT_ILLUMINATION_STATUS" ise_id="55164" value="0" valuetype="16" valueunit="" timestamp="1568404230" operations="5"/>
<datapoint name="HmIP-RF.XXXXXXXXXXXXX:1.ILLUMINATION" type="ILLUMINATION" ise_id="55165" value="0.900000" valuetype="4" valueunit="" timestamp="1568661280" operations="5"/>
</channel>
```

**Comment by Macem79** [comment]
Ich kann das nicht mehr testen da ich wieder zurück auf die 1.2.5 gehe wo es keine Probleme mit gab.

**Comment by LevelOne2k** [comment]
Auf der CCU3 FW habe ich aktuell 13 an Helligkeit und nur weil das Licht eingeschaltet ist. Mit der RaspberryMatic komme ich nichtmal ansatzweise an 13 heran obwohl der Raum knalle hell von der Sonne ist.

```
<channel name="HmIP-SPI XXXXXXXXXXXXX:1" ise_id="1420" index="1" visible="true" operate="true">
<datapoint name="HmIP-RF.XXXXXXXXXXXXX:1.CURRENT_ILLUMINATION" type="CURRENT_ILLUMINATION" ise_id="1421" value="13.800000" valuetype="4" valueunit="" timestamp="1568668251" operations="5"/>
<datapoint name="HmIP-RF.XXXXXXXXXXXXX:1.CURRENT_ILLUMINATION_STATUS" type="CURRENT_ILLUMINATION_STATUS" ise_id="1422" value="0" valuetype="16" valueunit="" timestamp="1568668251" operations="5"/>
<datapoint name="HmIP-RF.XXXXXXXXXXXXX:1.ILLUMINATION" type="ILLUMINATION" ise_id="1423" value="12.900000" valuetype="4" valueunit="" timestamp="1568668251" operations="5"/>
<datapoint name="HmIP-RF.XXXXXXXXXXXXX:1.ILLUMINATION_STATUS" type="ILLUMINATION_STATUS" ise_id="1424" value="0" valuetype="16" valueunit="" timestamp="1568668251" operations="5"/>
</channel>
```

**Comment by HookHM** [comment]
Ich habe auch wieder die Firmware 1.2.4 auf den SPI installiert.

Das sieht jetzt schon ganz anders aus im Vergleich zu gestern Morgen und fast der selben Zeit.
Gestern hatte ich 0 bis 1 in der Helligkeit um diese Zeit: https://homematic-forum.de/forum/viewtopic.php?f=58&t=51902&start=50#p529700 (Edit2).

Nun sieht es so aus:
`<channel name="HmIP-SPI xxx:1" ise_id="1460" index="1" visible="true" operate="true">
<datapoint name="HmIP-RF.xxx:1.CURRENT_ILLUMINATION" type="CURRENT_ILLUMINATION" ise_id="1461" value="32.300000" valuetype="4" valueunit="" timestamp="1568708708" operations="5"/>
<datapoint name="HmIP-RF.xxx:1.CURRENT_ILLUMINATION_STATUS" type="CURRENT_ILLUMINATION_STATUS" ise_id="1462" value="0" valuetype="16" valueunit="" timestamp="1568708708" operations="5"/>
<datapoint name="HmIP-RF.xxx:1.ILLUMINATION" type="ILLUMINATION" ise_id="1463" value="96.300000" valuetype="4" valueunit="" timestamp="1568709267" operations="5"/>`

Allerdings habe ich auch aktuell die CCU3 Firmware 3.45.7 installiert mit der es ja eh besser war als mit RaspberryMatic ab 3.47.15.20190831. Allerdings hatte der SPI da die Firmware 1.4 drauf und mit dieser fingen die Probleme ja an.

Ich werde nun wieder RaspberryMatic 3.47.15.20190831 installieren und beobachten wie sich die Helligkeit dort am SPI mit Firmware 1.2.8 verhält. Da die RaspberryMatic 3.47.15.20190831 und der SPI mit 1.2.8 jedoch schon normal lief bevor es die Firmware 1.4 überhaupt gab, wird es auch jetzt wieder mit der 1.2.8 vernünftig laufen.

**Comment by HookHM** [comment]
Und so sieht das ganze jetzt mit der Firmware 1.2.4 auf der RaspberryMatic 3.47.15.20190831 aus:

`<channel name="Präsenzmelder:1" ise_id="5624" index="1" visible="true" operate="true">
<datapoint name="HmIP-RF.xxx:1.CURRENT_ILLUMINATION" type="CURRENT_ILLUMINATION" ise_id="5625" value="71.900000" valuetype="4" valueunit="" timestamp="1568711611" operations="5"/>
<datapoint name="HmIP-RF.xxx:1.CURRENT_ILLUMINATION_STATUS" type="CURRENT_ILLUMINATION_STATUS" ise_id="5626" value="0" valuetype="16" valueunit="" timestamp="1568711611" operations="5"/>
<datapoint name="HmIP-RF.xxx:1.ILLUMINATION" type="ILLUMINATION" ise_id="5627" value="70.100000" valuetype="4" valueunit="" timestamp="1568711683" operations="5"/></channel>`

**Comment by jens-maus** [comment]
Ok. Es sieht für mich also nach einem Problem bzw Änderung in der HmIP-SPI Gerätefirmware aus und nicht nach einem Bug/Problem in der CCU/RaspberryMatic Firmware. Der richtige Adressat für Bugreports zu dem Thema wäre also eQ3 wenn ich das richtig sehe.

**Comment by Macem79** [comment]
@jens-maus ich sehe das etwas anders. In der aktuellen CCU3 FW und mit der RaspberryMatic 3.47.10.20190713 Version verhält sich der SPI mit FW 1.4 ganz normal. Erst ab RaspberryMatic 3.47.15.20190831 trat dieses Problem im Zusammenhang mit der SPI FW 1.4 auf. 

Natürlich habe ich das Problem eQ-3 schon gemeldet, allerdings hatte ich da RaspberryMatic 3.47.15.20190831 installiert. Deren Antwort war natürlich, dass sie das Problem nicht reproduzieren können. Kein Wunder, denn die haben natürlich eine CCU3 FW installiert und mit dieser gibt es das Problem ja auch nicht, auch bei mir nicht. Denn nach der Antwort von eQ-3 habe ich auch die CCU3 FW installiert und damit verhielt sich der SPI (FW 1.4) direkt normal. Dann wieder zurück auf die RaspberryMatic 3.47.15.20190831 und der SPI hatte wieder das Problem. Dann mal auf die RaspberryMatic 3.47.10.20190713 gegangen und der SPI lief auch damit normal mit FW 1.4 dann wieder auf die RaspberryMatic 3.47.15.20190831 und der SPI spinnt wieder bzw. Die Helligkeit.

**Comment by jens-maus** [comment]
@Macem79 Es gibt aber meiner Erinnerung nach keinerlei substantielle Unterschiede zwischen der CCU3 und RaspberryMatic im Hinblick auf diese Helligkeitswerte des SPI. Nicht ohne Grund habe ich darauf hingewiesen bitte via XML-API z.B. die rohen Gerätedaten einmal auszugeben. Um eben ein event. Problem in der reinen WebUI Darstellung auszuschliessen. Wenn aber in der XML-API die gleichen Werte wie in der WebUI zu sehen sind sind das einfach defakto die werte die der Sensor zu der Zeit an die CCU/RaspberryMatic liefert und da der HMIPServer dienst exakt der selbe ist wie bei einer CCU3 FW kann ich mir momentan nicht erklären wieso bei RaspberryMatic andere Werte rauskommen sollten als bei einer CCU3 FW. Ich vermute weiterhin ein Firmware-Problem in der 1.4 Firmware des HmIP-SPI. 

Um dem Problem also Herr zu werden wäre es sicherlich sinnvoll hier einmal systematischer vorzugehen. D.h. zwei getrennte Zentralen mit 1x CCU3 FW und einmal Raspberrymatic zu haben, sort dann zwei nebeneinander liegende SPI zu testen und eben nicht einfach die WebUI Werte hier zu melden sondern das was an "Rohdaten" via XML-API bzw. ioBroker, etc. z.B. ausgelesen werden kann. Denn meine Vermutung ist einfach das durch das ständige Switches und Neustarten der Zentrale ggf. die Helligkeitswerte auch beeinflusst werden (diese sind ja ohnehin nur gemittelten werte).

**Comment by libertyx82** [comment]
Die CCU3 hat inzwischen FW 3.47.18
Aus den Changelog
```
Robustheit der Homematic IP XML-RPC Schnittstelle gegenüber nicht mehr erreichbaren Clients wurde
verbessert. Hierdurch konnte es zum Ausbleiben von Geräte Events kommen.
```

**Comment by Macem79** [comment]
Das da oben sind doch die Rohdaten aus der XML-API. 

Es ist definitiv so das der SPI an der Helligkeit ab RaspberryMatic 3.47.15.20190831 nicht wirklich hoch geht. Bei mir nicht höher als 4.

**Comment by jens-maus** [comment]
Kann ich mir trotzdem nicht erklären. Hier gibt es AFAICS keine nennenswerten Unterschiede in der zuständigen Komponente zwischen CCU3 und RaspberryMatic. Und wenn es eben mit der alten SPI Gerätefirmware funktioniert tippe ich weiter darauf und würde vorschlagen einfach bei der alten zu bleiben oder die nächste RaspberryMatic Version abzuwarten.

**Comment by jens-maus** [comment]
@Macrm79 Achja, und von dir sehe ich oben trotzdem keine SPI Rohdaten. Nur von anderen.

**Comment by Macem79** [comment]
Kann ich gerne später posten allerdings bin ich jetzt wieder auf der SPI Firmware 1.2.8 und RaspberryMatic 3.47.15.20190831

**Comment by Macem79** [comment]
@jens-maus Das hier sind meine Werte

`<channel name="Praesenzmelder:1" ise_id="5624" index="1" visible="true" operate="true">
<datapoint name="HmIP-RF.xxxxxx:1.CURRENT_ILLUMINATION" type="CURRENT_ILLUMINATION" ise_id="5625" value="62.700000" valuetype="4" valueunit="" timestamp="1568712175" operations="5"/>
<datapoint name="HmIP-RF.xxxxxx:1.CURRENT_ILLUMINATION_STATUS" type="CURRENT_ILLUMINATION_STATUS" ise_id="5626" value="0" valuetype="16" valueunit="" timestamp="1568712175" operations="5"/>
<datapoint name="HmIP-RF.xxxxxx:1.ILLUMINATION" type="ILLUMINATION" ise_id="5627" value="9148.000000" valuetype="4" valueunit="" timestamp="1568727726" operations="5"/></channel>

**Comment by jens-maus** [comment]
Ist das eine Bestätigung meiner Vermutung das es an der Gerätefirmware liegt?

Siehe https://homematic-forum.de/forum/viewtopic.php?p=530077#p530077

**Comment by jens-maus** [comment]
Nun habe ich das Verhalten hier mal mit meinen eignen HmIP-SPI und HmIP-SMI reproduziert und beide geben für mich sinnvolle Werte aus (wohl in Lux). Mit der alten 1.2.8 firmware waren die Werte die der HmIP-SPI ausgegeben hat wohl eben nicht Lux sondern 10x zu hoch und daher nicht mit dem SMI kompatibel. Insofern schliesse ich diese Ticket hier als not-a-bug.
