### ISSUE TITLE
Bootvorgang mit HMIP-SPM

### ISSUE THREAD

**Issue by friedpa** [jens-maus/RaspberryMatic#711]
**Describe the bug**
Wenn man die RM neu startet werden meine beiden HMIP-PSM in den Servicemeldungen als Gerätekommunikation gestört angezeigt. Man sieht das alle 3-4 Sekunden der Zeitstempel upgedated wird und der DC rauf geht. Nach circa gefühlten 2 Minuten hört der Spuk auf und die beiden Meldungen verschwinden (manchmal).

**To Reproduce**
1. Boot
2. Look at Servicemeldungen
3. Look at Time Stamps from HMIP-PSM devices
4. Look at increasing DC of RM

**Expected behavior**
No related Servicemeldungen of HMIP-PSM devices

**System information (please complete the following information):**
 - RaspberryMatic 3.47.18.20190918]
 - Hardware RaspberryPi3+

**Comment by jens-maus** [comment]
Das ist vollkommen normal bzw abhängig davon wie der startvorgang abläuft. Insgesamt ist man gut beraten einem neu gestartetem ccu system ungefähr eine stunde bos zur Stabilität zu geben.

Kann hier also kein fehler erkennen.
