### ISSUE TITLE
HmIP-KRC4 Tastendrücke kommen nicht an und ablernen funktioniert nicht

### ISSUE THREAD

**Issue by Xento** [jens-maus/RaspberryMatic#712]
**Describe the bug**
Ich habe eine HmIP-KRC4 an die Raspberrymatic angelernt.
Ich habe dann einige Tasten in Programmen genutzt und die Informationen wurden auch an die Fernbedienung übertragen (benutzte Tasten bestätigen mit grün, unbenutzte Tasten zeigen nur gelb).
Allerdings lösen die Programme nicht aus. Ich habe auch die Protokollierung auf den Tasten aktiviert, dies brachte aber auch keine Erkenntniss. Es sieht so aus alsob die Tastendrücke garnicht richtig ankommen und dadurch auch nicht protokolliert werden.

Also dachte ich mir, lerne ich die Fernbedienung mal ab und versuche es erneut.
Nun kommt allerdings das nächste Problem.
Die Fernbedienung wird zwar abgelernt (keine LED leuchtet beim Druck auf eine Taste und sie ist im Anlernmodus), allerdings bleibt sie noch in der Geräteliste eingetragen nur ohne Spannung und Empfangsqualität.
Wenn ich nun erneut versuche sie zu löschen, dann wird nur ewig "Programme und direkte Geräteverknüpfungen werden geprüft..." angezeigt.
Ich kann sie wieder erneut anlernen, dann wird auch wieder die Batteriespannung und der Empfang angezeigt ...
Beim erneuten anlernen landet sie aber nicht im Posteingang sondern ist immer noch direkt unter den Geräten aufgelistet.

Ich habe auch schon mehrere Neustarts versucht und auch im abgesicherten Modus.

**To Reproduce**
-

**Expected behavior**
Tastendrücke werden korrekt verarbeitet und ablernen funktioniert

**Screenshots**
-

**System information (please complete the following information):**
 - Version 3.47.18.20190918
 - Hardware Raspberry 3B mit RPI-RF-MOD

**Additional context**

**Comment by Xento** [comment]
Nach einem Downgrade auf 3.47.15.20190831 geht wieder alles.
Hab danach wieder ein Upgrade gemacht und schon gehts wieder nicht.

**Comment by mr-spooner** [comment]
Jupp, betrifft auch andere Schaltaktoren. Sämtliche virtuelle Tasten funktionieren in Version 3.47.18.20190918 nicht mehr. Downgrade auf 3.47.10.20190713 (meine Ursprungsversion, da die Raspberrymatic sich schon bei 3.47.15.20190831 aufhing) funktioniert alles bestens.

Meine Hardwarekonfiguration ist dieselbe (Raspberry 3B+ mit RPI-RF-MOD).
