### ISSUE TITLE
Fehler fluten Log dach Redmatic-Deinstallation

### ISSUE THREAD

**Issue by pacco81** [jens-maus/RaspberryMatic#713]
Hallo !

Nach Deinstallation von RedMatic wird mein RaspiMatic-Log geflutet mit diesen Meldungen:

`Sep 23 19:53:30 ks-ccu12 user.err monit: /etc/monitrc:399: Cannot include file '/usr/local/etc/monit-redmatic.cfg' -- No such file or directory '/usr/local/etc/monit*.cfg'`

Kann es sein, dass monit versucht Redmatic weiterhin zu überwachen ?
Funktionell habe ich keine probleme mit der RaspiMatic

Aktuelle Firmwareversion: | 3.47.18.20190918

Besten Dank,
Sebastian

-- | --

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
 - Version [e.g. RaspberryMatic 3.37.8.20180922]
 - Hardware [e.g. RaspberryPi3, TinkerboardS, etc.]

**Additional context**

**Comment by jens-maus** [comment]
Das scheint mir ein RedMatic deinstallationsproblem zu sein.

@hobbyquaker Kann es sein das nach Deinstallation von RedMatic du die monit Konfiguration nicht neu einlesen lässt und er dann eben die redmatic monit config vermisst bei den nächsten Ausführungen von monit?

**Comment by hobbyquaker** [comment]
Ist in der aktuellen RedMatic Beta bereits gefixt: https://github.com/rdmtc/RedMatic/issues/241
Wenn man eine Version <= 4.7.1 deinstalliert muss man das File leider noch von Hand löschen.

**Comment by jens-maus** [comment]
Danke für die Aufklärung. Dachte mir das das ein RedMatic Problem sein muss.

**Comment by pacco81** [comment]
Danke euch !
