### ISSUE TITLE
Farblicher Statusbalken für DutyCycle skaliert falsch

### ISSUE THREAD

**Issue by kafetzke** [jens-maus/RaspberryMatic#714]
der Farb-Indikatiorbalken für den DutyCycle auf der Startseite skaliert regelmäßig falsch. Der Wert des DutyCycles ist aber augenscheinlich korrekt. Interessanter Weise korrigiert sich dies immer wieder mal im laufenden Betrieb von selbst und taucht später wieder auf. Anbei ein Screenshot...

![grafik](https://user-images.githubusercontent.com/54636474/65493127-86493380-deb2-11e9-8e21-9afcd0dd8dae.png)

**Comment by jens-maus** [comment]
Das ist bekannt und momentan zumindest von mir nicht zu lösen. Auch passiert das soweit ich weiss nur jeweils beim frischen verbinden zur WebUI und klärt sich dann nach wenigen Sekunden. Die gesamte DutyCycle par ist leider nicht meine Erfindung sondern die hat sich eQ3 ausgedacht und ist leider suboptimal umgesetzt. Muss man also erst einmal damit leben ist auch IMHO nicht so tragisch das man hier sofort tätig werden muss.

**Comment by jens-maus** [comment]
Achja, und ich sehe gerade. Das "Problem" wurde bereits in #694 gemeldet. Ergo ist das ein Duplikat und gehört geschlossen.

**Comment by kafetzke** [comment]
Jup, alles klar. Das Problem ist definitiv nur ein "Schönheitsfehler" und unkritisch - das Duplikat habe ich leider übersehen (sry...)
