### ISSUE TITLE
Schaltaktoren funktionieren nicht mehr richtig

### ISSUE THREAD

**Issue by mr-spooner** [jens-maus/RaspberryMatic#715]
Schaltaktoren können zwar eingeschaltet werden (z.B. Schaltsteckdosen, 8-Kanal Schaltaktoren), aber weder wird der Schaltstatus angezeigt, noch können diese Aktoren dann durch den entsprechenden Button wieder ausgeschaltet werden.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
 - Version [e.g. RaspberryMatic 3.37.8.20180922]
 - Hardware [e.g. RaspberryPi3, TinkerboardS, etc.]

**Additional context**

**Comment by mr-spooner** [comment]
Betrifft die aktuelle Version RaspberryMatic 3.47.18.20190918

**Comment by Flauschi83** [comment]
bei mir gehts. Ohne korrekte Fehlermeldung wirst Du wohl keine Lösung finden.

**Comment by rhsdat** [comment]
Kann ich so bestätigen, das Problem habe ich auch. Zurück auf die Vorgängerversion und alles geht wieder...
