### ISSUE TITLE
Verbindungsart (LAN/WLAN) in Webui anzeigen

### ISSUE THREAD

**Issue by TobiasSt78** [jens-maus/RaspberryMatic#718]
**Describe the solution you'd like**
Direkt in der WebUI Anzeigen, welcher Adapter gerade aktiv ist.

**Describe alternatives you've considered**
In FritzBox in 3ter Unterebene die Verbindungsart raussuchen.

**Additional context**
Es ist nicht ersichtlich, ob per WLAN oder LAN verbunden, wenn beides konfiguriert ist. WLAN sollte eigentlich nur das Backup-Lösung sein.

**Comment by jens-maus** [comment]
Sicherlich ein nice-to-have. Allerdings gibt es ja nicht mal eine WebUI Konfigurationsmöglichkeit für WLAN und WLAN Support in RaspberryMatic ist ohnehin etwas das nur nebenbei unterstützt wird und IMHO sollte man ohnehin seine CCu nicht via WLAN anbinden weil es sonst instabil und ggf negative effekt auf die Funkverbindung mit der HomeMatic Welt geben könnte.

**Comment by TobiasSt78** [comment]
Jep, nice to have und LAN hat natürlich Prio. 
Wenn das LAN ausfällt, läuft bei mir dank 3 WLAN Stationen das WLAN auf jeden Fall noch. Und es gibt nichts ärgerlicheres als wenn die komplette Haussteuerung im Urlaub nicht mehr erreichbar ist...
