### ISSUE TITLE
WebUi: Filter auf "Name" in "Programme" und "Systemvariablen-Auswahl" werden verwechselt.

### ISSUE THREAD

**Issue by TomItNet** [jens-maus/RaspberryMatic#720]
**Describe the bug**
WebUi: Filter auf Name wird von Systemvariablen-Auswahl auf "Programme" übernommen.

**To Reproduce**
Wenn unter „Programme und Verknüpfungen“ --> „Programme und Zentralenverknüpfungen“ in Spalte „Name“ ein Filter gesetzt ist, dann ein gefiltertes Programm bearbeitet wird und ein Systemzustand mit Systemvariable hinzugefügt wird, wobei auch hier ein Filter zur Filterung der Systemvariablen auf „Name“ verwendet wird, so wird nach Abschluss der Bearbeitung des Programms mit „OK“ der zuvor zur Filterung des Systemvariablen verwendete Filter für Name nun auf die Programme (Name) angewendet.

Dies hat wahrscheinlich damit zu tun, dass beide Filter auf eine Spalte mit der Überschrift "Name" angewendet werden.

**Expected behavior**
Namensfilter werden einzeln je Tabelle (Programme/Systemvariablen) gespeichert.

**System information (please complete the following information):**
 - Version: 3.47.18.20190918
 - Hardware: RaspberryPi3b
 - Browser: Firefox 69.0.1

**Comment by TomItNet** [comment]
See OCCU
sysVarsSelection.htm row 95
programlist.htm row 74
(btnFilterNameSub)

**Comment by jens-maus** [comment]
@psi-4ward Kannst du das reproduzieren bzw. fixen?
