### ISSUE TITLE
Ständiger request an google.com

### ISSUE THREAD

**Issue by m50434** [jens-maus/RaspberryMatic#721]
Ich habe seit kurzem Pi-Hole bei mir im System installiert. Dabei ist mir aufgefallen, dass meine CCU2 mit RaspberryMatic in sehr regelmäßigen Abständen (ca. alle 2 bis 5 Minuten) einen Request an die Domain google.com stellt.
Als einziges Addon habe ich redmatic installiert. 
Ich habe das Ganze einfach blockiert... und mir ist jetzt nicht aufgefallen, das irgendetwas nicht geht. Trotzdem finde ich den Zugriff auf google.com sehr seltsam.
Gibt es dafür eine Erklärung?!

**Comment by libertyx82** [comment]
Ja, ist der Test für die Internetverbindung

**Comment by m50434** [comment]
...und muss das unbedingt alle 2 Minuten erfolgen?
Wozu wird die Internetverbindung denn benötigt (Mal abgesehen von Hinweisen für Updates)? 
Zeitsynchronisation?! Das würde ja vlt. auch einmal täglich genügen...

**Comment by McLive** [comment]
Für eine schnelle Benachrichtigung ist ein kurzer Intervall sinnvoll. 
Wird dich vom Traffic her sicher nicht umbringen ;)

**Comment by jens-maus** [comment]
@m50434 Auch hier wieder leider das Ticket template einfach gelöscht und komplett ignoriert wie man es eigentlich auffüllen sollte :/ Aber gut, und dann zeigst du leider nicht in technischer form wie der google.com zugriff bitte deiner Meinung nach aussieht und wohin er genau geht. Auch das sollte teil des tickets hier sein denn ansonsten kann das hier keiner reproduzieren. 

Und ja, die Internetprüfung findet zyklisch statt. Ist so und tut aber auch nicht weg und ist in keinem falle kritische da es sich hierbei lediglich um einfach IDCMP bzw. ein simpler HTTP zugriff handelt. Ergo unkritisch.

**Comment by m50434** [comment]
@jens-maus Sorry, ich habe einen "Support-Request" erstellt, da gibt es kein Template.
Es war ja auch weder ein Bug, noch ein Feature-Request.
Nächstes Mal also auch das ins Forum.
