### ISSUE TITLE
HMIP Kanal Angaben von HMIP-STH und -STHD fehlen

### ISSUE THREAD

**Issue by hellman23** [jens-maus/RaspberryMatic#723]
**Describe the bug**
HMIP Kanal Angaben von HMIP-STH und -STHD fehlen seit mehren RM Versionen.
(Update auf 3.47.18.20190918 brachte auch keine Änderung)
Die Gerät funktionieren ansonsten einwandfrei und die Werte lassen sich auch über Scripte und Diagramme auslesen.
Nur unter "Status und Bedienung" sind keinerlei Kanalangaben mehr vorhanden.
Andere HMIP Geräte sind auch mit Kanalangaben verfügbar, z.B. : HMIP-BROLL

**To Reproduce**
1. Gute Frage

**Expected behavior**
Ein Ab- und wieder Anlernen ist leider nicht die Lösung für mich, da viele der Werte in Langzeitdiagrammen verwendet werden und diese dann nicht mehr korrekt arbeiten.
(anderer offener Bug hier,  der aber als upstream Problem gekennzeichnet wurde)

**Screenshots**
![image](https://user-images.githubusercontent.com/5887769/66990213-118aa300-f0c6-11e9-80d0-c4ef991fbf33.png)
![image](https://user-images.githubusercontent.com/5887769/66990245-20715580-f0c6-11e9-8395-3bead3a6667c.png)
![image](https://user-images.githubusercontent.com/5887769/66990289-34b55280-f0c6-11e9-9211-2cc913f87230.png)

**System information (please complete the following information):**
 - Version [RaspberryMatic 3.47.10.20190713]
 - Hardware [RaspberryPi3]

**Additional context**

**Comment by jens-maus** [comment]
Können das andere mit einem HMIP-STH bzw. -STHD reproduzieren mit der aktuellen RaspberryMatic Version?

**Comment by StefanGubler** [comment]
Ich habe 3 Homematic installationen mit einigen HmIP-STH und STHD Sensoren und kenne das Problem nicht, das wäre mir aufgefallen.  

Ich kann das Verhalten reproduzieren, wenn ich  bei der Gerätekonfiguration "Sichtbar" deaktiviere.

![STHD-Sichtbarkeit](https://user-images.githubusercontent.com/43369612/67145634-46902480-f283-11e9-9225-4d162c601e35.PNG)

Bitte prüfen ob die Geräte korrekt konfiguriert sind, zum entscheiden ob es ein Bug ist oder nicht.

Getestet auf Raspberrymatic 3.47.18.20190918 auf Tinker S / Hm Geräte mit aktueller Firmware

**Comment by jens-maus** [comment]
Das ist in der Tat win sehe guter Hinweis! Ggf wurde die sichtbarkeit dieser geräte ja mit einer externen App (pocketControl &co) geändert.

Also bitte nochmal nachschauen ob hier einfachbin den Geräteeinstellungen fälschlicherweise die sichtbarkeit abgeschalten wurde

**Comment by ThomasLoeffel** [comment]
Hallo Zusammen,

ich kann das Verhalten bestätigen! 

Wenn die Sichbarkeit nicht angehakt dann zeigt sich das Bild vom Hellmann23. Ich denke er hat den Haken warum auch immer nicht mehr gesetzt.

Gruß Thomas

**Comment by hellman23** [comment]
Der Haken "Sichtbarkeit" war überall gesetzt, aber aus unerfindlichen Gründen war der Haken "Bedienbarkeit" nicht mehr aktiv.
Trotzdem hat mich der Tip auf die richtige Spur geführt, vielen Dank!

Also eigentlich kein wirklicher Bug, sondern nur eine irgendwann "ungewollte Veränderung" der Parameter nach einem Update.
