### ISSUE TITLE
Logo Styling

### ISSUE THREAD

**Issue by Matten-Matten** [jens-maus/RaspberryMatic#724]
Hallo @jens-maus,
ich hätte noch drei Logo Vorschläge und packe die passenden .pngs mit in den Anhang.
![logo](https://user-images.githubusercontent.com/32074970/66703783-8a7caa00-ed16-11e9-9763-49bae7639422.png)

Gruß
Matten Matten

bsp1 in schwarz
![raspmatic2](https://user-images.githubusercontent.com/32074970/66703791-99635c80-ed16-11e9-9df5-5094836e7280.png)
bsp1 in weiß
![raspmatic2w](https://user-images.githubusercontent.com/32074970/66703793-99635c80-ed16-11e9-9f14-3e4497d63bdf.png)
bsp2 in schwarz
![raspmatic3](https://user-images.githubusercontent.com/32074970/66703794-99635c80-ed16-11e9-8638-cb1ace873e14.png)
bsp2 in weiß
![raspmatic3w](https://user-images.githubusercontent.com/32074970/66703795-99635c80-ed16-11e9-8c49-ead6de3c0972.png)
bsp3
![raspmatic3](https://user-images.githubusercontent.com/32074970/66703954-13e0ac00-ed18-11e9-8feb-144c6a7ec0df.png)

**Comment by jens-maus** [comment]
Danke. Aber RaspberryMatic hat doch aktuelle/brauchbare Logos. Warum also sollte man die ersetzen?!?

**Comment by Matten-Matten** [comment]
Ich finde die schwarzen bzw weißen Logos  zu Schrift einfach einheitlicher. Ist ja nur ne Idee. 
Schönes Wochenende noch.

Gruß
Matten Matten

**Comment by jens-maus** [comment]
Tut mir leid. Da sollte man schon konkreter werden welche logos damit genau ersetzt werden sollten und dann ein Beispiel Screenshot zeigen und entsprechend diskutieren. Aber hier einfach Irgendwelche Logos in ein Ticket legen scheint mir nicht zielführend zu sein.
