### ISSUE TITLE
Deaktivierung der Servicemeldungen greift beim HM-MOD-Re-8 nicht

### ISSUE THREAD

**Issue by HMside** [jens-maus/RaspberryMatic#725]
Trotz der Deaktivierung der Servicemeldungen für den Aktor Typ "HM-MOD-Re-8" erhält man weiterhin Servicemeldungen.
Wo lässt sich nachprüfen, ob das Flag korrekt gesetzt wurde?

<img width="803" alt="Bildschirmfoto 2019-10-14 um 17 28 23" src="https://user-images.githubusercontent.com/13312068/66763469-2689eb00-eea8-11e9-86d4-d90cf573d0ec.png">

**Comment by jens-maus** [comment]
Wüsste nicht was am HM-MOD-Re-8 anders sein sollte das dieser anscheinend weiterhin Servicemeldungen bei dir in der WebUI bringt? Und wenn dort der Knopf ausgeschalten ist sollte das als Status reichen das  Servicemeldungen für das Gerät deaktiviert sind. Können das andere reproduzieren das es exakt diesen Gerätetype betrifft?

**Comment by HMside** [comment]
@jens-maus
wird beim deaktivieren ggf. etwas ins regadom oder dev-File des Geräts geschrieben, was ich prüfen kann? Oder wie funktioniert das technisch?

**Comment by jens-maus** [comment]
@HMside Ja. in der regadom müsste es ein `enabledServiceMsg` metadaten eintrag beim device geben der dann auf false steht wenn das ausgeschalten ist und wenn das so ist sollte dann die WebUI die servicemeldung einfach kurzerhand unterdrücken.

Hier mehr zu der umgesetzten Logik:
https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0044-WebUI-DisableDeviceServiceMsg.patch#L79-L152

**Comment by jp112sdl** [comment]
Also ich kann es nicht reproduzieren.

- HM Mod RE 8 angelernt
- Geräteübersicht: Servicemeldung deaktiviert
  - NO_SERVICEMSG wird angezeigt
- Gerät vom Strom getrennt
- Status und Bedienung->Geräte: Aktor Kanal schalten
-> es wird **keine** Servicemeldung generiert.
- Geräteübersicht: Servicemeldung aktiviert
- Status und Bedienung->Geräte: Aktor Kanal schalten
-> Servicemeldung **wird** generiert.
- Geräteübersicht: Servicemeldung deaktiviert
-> noch anstehende Servicemeldung **verschwindet** sofort
