### ISSUE TITLE
WebUI: Download button should open URLs in a new tab

### ISSUE THREAD

**Issue by manny4566** [jens-maus/RaspberryMatic#727]
Hi,
i request to change the download fuction from additional software so, that a new tab open for the download or directly the download begin.
Currently the same browser tab is refreshed by the download where RaspberryMatic is open. 
So you need to login always new, only because you download a plugin.
Thank you

**Comment by jens-maus** [comment]
Please give examples and show what you mean. In fact I think the addon itself defines how a link to the download page of the addon is opened and RaspberryMatic itself does and partly cannot enforce how the download link is opened.

**Comment by Hypnos3** [comment]
![image](https://user-images.githubusercontent.com/12692680/67149811-0eeba180-f2b0-11e9-920d-4add15a3b2a3.png)
Die gelb hinterlegten Buttons öffnen die Seite immer direkt und nicht auf einer neuen Seite.

**Comment by jens-maus** [comment]
Danke für den Tipp. Konnte es reproduzieren und die Lösung sollte mit der nächsten Version dann kommen.

**Comment by jens-maus** [comment]
Voila. Neuen WebUI Patch dafür umgesetzt. Sollte also mit der nächsten kommenden Version dann so funktionieren.

**Comment by manny4566** [comment]
Super, danke, ging ja schnell und das nervende neu laden der Oberfläche entfällt endlich :)
