### ISSUE TITLE
Nach Reboot Watchdog löst aus: lighttpd restarted

### ISSUE THREAD

**Issue by jaschkopf** [jens-maus/RaspberryMatic#728]
**Describe the bug**
After reboot the RPi the Web UI is not reachable but the system runs without a error. After a few minutes the watchdog restarts the lighttpd and the web ui is available again. 

**To Reproduce**
Everytime the system boots. Doesn't matter if the system was restarted manually, after a firmware update or power loss. 

**Expected behavior**
Maybe a bug that should be fixed? 

**Screenshots**

**System information (please complete the following information):**
 - RaspberryMatic 3.47.22.20191026
 - RaspberryPi3 

**Additional context**

**Comment by jens-maus** [comment]
This can't be a general issue but might be local to your own installation only. Haven't heard of it before. So please provide some more information on logging (`/var/log/lighttpd-error.log`) which might provide some more information.

**Comment by jaschkopf** [comment]
This is the log file:
[lighttpd-error.log](https://github.com/jens-maus/RaspberryMatic/files/3789994/lighttpd-error.log)

**Comment by jens-maus** [comment]
Das logfile alleine hilft leider nicht. da müsste man ggf. noch `/var/log/messages` parallel dazu sehen um zu schauen warum lighttpd da neu gestartet wurde. Bitte noch beifügen.

**Comment by jaschkopf** [comment]
Hallo Jens,

anbei noch die messages Datei. 
[messages.txt](https://github.com/jens-maus/RaspberryMatic/files/3819653/messages.txt)

**Comment by jens-maus** [comment]
Inzwischen gibt es wohl einen weiteren Nutzer der das selbe Problem zu haben scheint. Ich versuche daher diese beiden Issues mal zu vereinen und schliesse daher als duplicate von #730 . Bitte dort weiter diskutieren und herausfinden welches die gemeinsamkeiten sind die solch ein Fehlerverhalten von lighttpd verursachen könnten.

Und dort bitte dann auch noch die lighttpd-access.log datei nachliefern die das problem auch aufzeigt.
