### ISSUE TITLE
WebUI - HM-CC-RT-DN shows double entries

### ISSUE THREAD

**Issue by friedpa** [jens-maus/RaspberryMatic#729]
**Describe the bug**
After Update to 3.47.22.20191026 the WebUI shows for the HM-CC-RT-DN in the Favorites:

**Screenshots**
![image](https://user-images.githubusercontent.com/42890695/67894900-d2def900-fb59-11e9-95df-4a8b9970caee.png)
 
**Expected behavior**
No double entry of Batteriestatus and Ventilöffnungsgrad

**System information (please complete the following information):**
 - RaspberryMatic 3.47.22.20191026
 - RaspberryPi3

**Comment by libertyx82** [comment]
Hmm kann ich so nicht bestätigen.

![image](https://user-images.githubusercontent.com/22996350/67895664-30c01080-fb5b-11e9-9317-256755a06685.png)

**Comment by friedpa** [comment]
Ich habe jetzt vier mal das System rebooted und jetzt scheint der Spuk vorbei zu sein......
