### ISSUE TITLE
Direct connections don't show up with beta5

### ISSUE THREAD

**Issue by dehell** [jens-maus/RaspberryMatic#73]
After updating from beta4 to beta5 and playing back a backup from beta4 no direct connections show up under 'programs and connections'. The following message is displayed:
An internal error was detected in the service software. The diagnostics are being emailed to the service system administrator (root).
Heck, since you're debugging, I'll show you the errors right here:

```
can't read "sender_type": no such variable
while executing
"set SENTRY(SENDER_TYPE) $sender_type"
(procedure "put_tablebody" line 129)
invoked from within
"put_tablebody"
(procedure "put_page" line 42)
invoked from within
"put_page"
```

These backups work all right playing back into a beta4 image.

**Comment by tomac01** [comment]
Bei mir funktioniert alles. Die Direktverknüpfungen werden korrekt angezeigt.

Eingesetzt auf Raspi2 mit eingespielter Sicherung von Beta4.

**Comment by jens-maus** [comment]
Also here I don't see any such problems in my own RaspberryMatic beta5 system. Thus flagging it as worksforme.

**Comment by dehell** [comment]
Yes, everyone has to restore a backup with beta5, so this seems to be a very rare case of failure. I hoped, the error message could lead to a hint, what could be wrong.
That maybe a problem with 2.27 and not beta5 in special but I can't find any complains regarding 2.27.

**Comment by eq-3-occu** [comment]
Yust a guess. This problem may be possible, if a direct connection has no sender device. A direct connection with no sender device have a red circle with a with rectangle in the direct connection list.

**Comment by dehell** [comment]
Yes, that seems to be the reason. I have an (to the CCU) unknown) sender which is directly connected to a receiver. But that's a legal configuration and should not lead to this behavior. Older versions marked this sender simply as 'unknown device'.

**Comment by jens-maus** [comment]
Reopening this issue until it is being solved upstream

**Comment by eq-3-occu** [comment]
This problem will be fixed in CCU2 /OCCU 2.27.8 version (will be released in the next view days)

**Comment by jens-maus** [comment]
Great news! Thanks for keeping us updated. Please also have a look at #80 which IMHO is also an upstream issue which would be great to be solved in one of the next CCU/OCCU updates.

**Comment by jens-maus** [comment]
CCU2 2.27.8 has just been released. Thus closing this issue until there are further reports that the issue still exists in the next RaspberryMatic release.
