### ISSUE TITLE
Changes in one Tab only

### ISSUE THREAD

**Issue by PaulMerk** [jens-maus/RaspberryMatic#732]
if changes are done in WebUI, prevent saving of changes in other tabs

Jens:

> _man sollte definitiv nicht z.B. in einem Tab ein Programm editieren und in einem anderen Tab ein weiteres, das kann ziemlich in die Hose gehen was die Konsistenz der hinterlegten Datenbank angeht._

**Comment by jens-maus** [comment]
Das lässt sich Programmteile sch nicht verhindern und es ist auch nicht gewollt das zu verhindern.
