### ISSUE TITLE
update von 3.47.18.20190918 nach RaspberryMatic 3.47.22.20191026

### ISSUE THREAD

**Issue by anb0s** [jens-maus/RaspberryMatic#733]
Ich habe meine CCU3 auf RaspberryMatic 3.47.18.20190918 aktualisiert mit Hilfe von RaspberryMatic-3.47.18.20190918-ccu3.tgz.

Jetzt versuche ich die Version 3.47.22.20191026 aufzuspielen leider ohne Erfolg. Es kommt eine Fehlermeldung, dass das Paket keine gültige Software beihaltet nach Upload von RaspberryMatic-3.47.22.20191026-rpi3.zip, auch mit RaspberryMatic-3.47.22.20191026-ccu3.tgz
klappt es nicht.

P.S.: der Download der Dateien (aus GitHub) ist sehr langsam (dauert ca. 3 Stunden), ich probiere schon seit über einer Woche, ständig Abbrüche. Der Anschluss ist nicht das Problem habe es nur mit GitHub aktuell...

**Comment by jens-maus** [comment]
Das kann leider kein generelles problem sein da weder in den Testumgebungen noch bisher eine größere Menge von Nutzern ähnliche Probleme gemeldet haben. Auch bitte beachten das GitHub kein Diskussionsforum ist, sondern hier nur definitiv bugs gemeldet werden sollten und vorher man bitte im homematic forum nach hilfe suchen sollte.
