### ISSUE TITLE
HmIP

### ISSUE THREAD

**Issue by joti63** [jens-maus/RaspberryMatic#734]
**Describe the bug**
Version RaspberryMatic-3.47.22.20191026-rpi3:
It's no longer possible to teaching-in Homematic IP devices.

**To Reproduce**
1. Backstep to RaspberryMatic-3.47.18.20190918-rpi3
2. Teaching-in of HmIP-Devices works
3. tested with HmIP-FDT and HmIP-SRH

**Expected behavior**
It should be possible to teaching-in HmIP devices.

**Screenshots**
no screenshots available.
Teach-in timer runs out, no device in the inbox.

**System information (please complete the following information):**
 - Version  RaspberryMatic-3.47.22.20191026
 - Hardware RaspberryPi3

**Additional context**
-

**Comment by jens-maus** [comment]
Sorry, this isn`t a general issue. I have several test installations were this perfectly works. So please retry with a factory reset and if teaching works afterwarfa, then this isn't a geneal issue.
