### ISSUE TITLE
DV 2 x HmIP-BDT oder mehr mit virtueller Taste blockiert CCU bei Aktivierung

### ISSUE THREAD

**Issue by comtel2000** [jens-maus/RaspberryMatic#735]
**Describe the bug**
Direkte Verknüpfung von 2 x HmIP-BDT Kanal 4 oder mehr mit virtueller Taste (HmIP-RCV-50) blockiert nach aktivieren der virtuellen Taste für ca. 20sec. die komplette HmIP Event Verarbeitung in der CCU.
Bei 2 x HmIP-BDT mit einer realen Hardware (RC8 Remote) und bei 1:1 Verlinkung HmIP-BDT/HmIP-RCV-50 gibt es kein Delay/Problem.

**To Reproduce**
1. DV HmIP-BDT Kanal 4 Gerät A mit HmIP-RCV-50 Taster 1 (kurz) und Dimmwert 100%
2. DV HmIP-BDT Kanal 4 Gerät B mit HmIP-RCV-50 Taster 1 (kurz) und Dimmwert 100%
3. Aktiviere HmIP-RCV-50 Taster 1 in WebUI oder via App.
4. HmIP-BDT Gerät A + B dimmen auf 100%
5. Versuche eine HmIP-BDT Änderungen innerhalb der nä. 10 - 20 sec. auszulösen

**Expected behavior**
DV mit mehreren HmIP-BDT sollte auch mit virtuellen Tastern ohne 20sec. Delay funktionieren

**Screenshots**
![image](https://user-images.githubusercontent.com/2266347/68234618-e7137200-0001-11ea-9c33-ac9c30ebb19a.png)

**System information:**
 - Version: RaspberryMatic 3.47.22.20191026
 - Hardware: ELV Charly3
 - 2 x HmIP-BDT Firmware: 1.4.8

**Additional context**
hmserver.log [DEBUG]
```
Nov 5 12:40:00 de.eq3.cbcs.devicemanagement.TransactionManager INFO  [vert.x-eventloop-thread-3] Transaction State: true | Size: 1 
Nov 5 12:40:00 de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler DEBUG [vert.x-worker-thread-2] send event(s) to interface: 1009 http URL: http://127.0.0.1:31999 
Nov 5 12:40:00 de.eq3.cbcs.devicemanagement.TransactionManager INFO  [vert.x-eventloop-thread-3] Transaction State: false | Size: 2 
Nov 5 12:40:00 de.eq3.cbcs.devicemanagement.TransactionManager INFO  [vert.x-eventloop-thread-3] Transaction State: false | Size: 3 
Nov 5 12:40:00 de.eq3.ccu.server.internal.BasicAPIHttpVertxHandler DEBUG [vert.x-eventloop-thread-2] io.vertx.ext.web.impl.HttpServerRequestWrapper@bd50ae 
Nov 5 12:40:00 de.eq3.ccu.server.internal.RpcMessageHandler DEBUG [vert.x-eventloop-thread-5] rpc.api.bidcos Incoming Request: event 
Nov 5 12:40:00 de.eq3.ccu.bidcos.dispatcher.BidCosRpcDispatcher DEBUG [vert.x-eventloop-thread-5] event interface: HmIP-RF_java device 001F58A9A72427:10: key:PRESS_SHORT = true 
Nov 5 12:40:00 de.eq3.ccu.server.internal.RpcMessageHandler DEBUG [vert.x-eventloop-thread-5] rpc.api.bidcos Send Response for : event 
Nov 5 12:40:00 de.eq3.ccu.server.internal.BasicAPIHttpResponseHandler DEBUG [vert.x-eventloop-thread-2] io.vertx.ext.web.impl.HttpServerRequestWrapper@bd50ae 
Nov 5 12:40:01 de.eq3.cbcs.devicemanagement.TransactionManager INFO  [vert.x-eventloop-thread-6] Transaction State: false | Size: 4 
Nov 5 12:40:01 de.eq3.cbcs.devicemanagement.TransactionManager DEBUG [vert.x-eventloop-thread-6] Suspend transaction 34 task SendFrameCommand [frame=UnconditionalSwitchCommandFrame : ApplicationHeader [frameType= UNCONDITIONAL_SWITCH_COMMAND, macSource=000000, macDestination=F00001, ipSource=000000, ipDestination=F00001], sendMode=PERMANENT_LISTENER], start fast lane transaction 37 task SendFrameCommand [frame=AnswerFrame : ApplicationHeader [frameType= ANSWER, macSource=000000, macDestination=912310, ipSource=000000, ipDestination=912310], sendMode=PERMANENT_LISTENER]

..

Nov 5 12:40:17 de.eq3.cbcs.server.core.vertx.handler.TransactionTimeoutHandler DEBUG [vert.x-worker-thread-1] Abort Transaction with ID: 34 and Timer ID: 144 from AP: 3014F711A0001F58A9A72427 currentTask: SendFrameCommand [frame=UnconditionalSwitchCommandFrame : ApplicationHeader [frameType= UNCONDITIONAL_SWITCH_COMMAND, macSource=000000, macDestination=F00001, ipSource=000000, ipDestination=F00001], sendMode=PERMANENT_LISTENER] 

```

**Comment by Baxxy13** [comment]
Nachdem inzwischen im Homematic Forum über mehrere Fälle dieser "Funk-Blockade" zu lesen war habe ich nochmal eigene Test's gemacht. 
Zusammenfassung:

- 2x HmIP-PSM (Kanal:3) mit einer HmIP-RCV-50-Taste per Direktverknüpfung (Schalter EIN /AUS) verknüpft
- HmIP-RCV-50-Taste gedrückt, beide PSM's gehen an
- nun innerhalb 0-20s über die WebUI einen weiteren HmIP-Aktor versuchen zu schalten
- HmIP-Aktor schaltet stark verzögert nach ca. 15-20s

 Ein leicht anderes Setup und etwas detaillierter habe ich das [hier beschrieben.](https://homematic-forum.de/forum/viewtopic.php?f=34&t=59715)

Setup: Pi4b-2GB mit RaspberryMatic 3.51.6.20200621 und RPI-RF-MOD auf HB-RF-USB-TK

**Comment by comtel2000** [comment]
Mit Update auf 3.53.30 gefixed
