### ISSUE TITLE
Nach update auf 3.47.22.20191026 läuft kein Prog mehr

### ISSUE THREAD

**Issue by Marco4223** [jens-maus/RaspberryMatic#736]
**Describe the bug**
Nach dem update kann ich über die homebridge keine Variablen mehr setzten.
Fehlermeldung der Homebridge:

```
Nov 06 07:59:48 cubietruck homebridge[1126]: [11/6/2019, 7:59:48 AM] [HomeMatic CCU2] Error Error: socket hang upwhile executing rega script var d = dom.GetObject("Essen");if (d){Write(d.State());}
```

Wenn ich versuche per xml interface ein Program zu starten passiert nichts.
Log der Rasberrymatic:
```
Nov  6 09:03:25 homematic-ccu2 local0.info ReGaHss: Info: start web processing, worker thread #0 {"HTTP-Listener"} [spawnNewProcess():httpListener.cpp:208]
Nov  6 09:03:25 homematic-ccu2 local0.info ReGaHss: Info: recvd 176 bytes by web server #1 [ThreadFunction():httpServer.cpp:767]
Nov  6 09:03:25 homematic-ccu2 local0.info ReGaHss: Info: IseSession GetSessionId from URL: /tclrega.exe [GetSessionId():iseSession.cpp:185]
Nov  6 09:03:25 homematic-ccu2 local0.debug ReGaHss: Verbose: called Program ID = 4475 'prgEssen' [ExecuteProgram():iseDOMPrg.cpp:587]
Nov  6 09:03:25 homematic-ccu2 local0.debug ReGaHss: Verbose: execute Program ID = 4475 'prgEssen'; Destination ID = 4477 [ExecuteProgram():iseDOMPrg.cpp:593]
Nov  6 09:03:25 homematic-ccu2 local0.debug ReGaHss: Verbose: execute Program ID = 4475 'prgEssen'; Destination ID = 4477 [Execute():iseDOMPrg.cpp:611]
Nov  6 09:03:25 homematic-ccu2 local0.debug ReGaHss: Verbose: start execute Destination within the trigger delay 0 [Execute():iseDOMPrg.cpp:615]
Nov  6 09:03:25 homematic-ccu2 local0.info ReGaHss: Info: added element id=1381; oid=1381; val=3.000000; time=0; oidTrigger=65535 [Add():iseRTScheduler.cpp:368]
Nov  6 09:03:25 homematic-ccu2 local0.info ReGaHss: Info: added element id=1376; oid=1376; val=0.400000; time=0; oidTrigger=65535 [Add():iseRTScheduler.cpp:368]
Nov  6 09:03:25 homematic-ccu2 local0.info ReGaHss: Info: added element id=1287; oid=1287; val=3.000000; time=0; oidTrigger=65535 [Add():iseRTScheduler.cpp:368]
```
Wenn ich versuche eine Variable per skript zu setzen friert mit der Rasberrymatic ein:
bsp:
```
var x = dom.GetObject("Essen");
x.Variable(true);
```
Mehr infos habe ich leider gerade nicht. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
 - Version  RaspberryMatic 3.47.22.20191026
 - Hardware RaspberryPi3B

**Additional context**

**Comment by jens-maus** [comment]
Tut mir leid, aber was genau soll ich mit diesen Infos bitte anfangen? Das scheint mir ein reines Problem auf Nutzerseite zu sein, denn zehntausende Installation können wunderbar via solcher remote skripte auf die ReGa zugreifen. Auch sehe ich in den angegebenen Logfiles keinerlei Fehlermeldung oder ähnliches!?!? Das einzige was ich diesem Ticket entnehmen kann ist eine Fehlermeldung die Homebridge ausgibt. Ergo, sollte man das Problem auch IMHO dort melden und nicht hier.

**Comment by Marco4223** [comment]
Hallo jens,
es lief ja alles vor dem update und ich weis leider nicht welche infos ich dir mehr geben kann.
Ist das den mt dem Variable setzen so richtig? Oder warum könnte der Rasberrymatic einfrieren!?

**Comment by jens-maus** [comment]
Tut mir leid, aber nur weil etwas vorher lief und danach nicht heisst nicht immer automatisch das der fehler dann an der gerade angefassten version liegen muss. Ich weiss das viele immer geneigt sind so zu denken, das ist aber zu kurz gedacht. Du musst da wirklich bei dem ansetzen der den Fehler auch ausgibt und das ist hier nunmal homebridge und nicht RaspberryMatic und auch nicht die ReGa. Ergo, Leidensgenossen finden, mit dem Autor von homebridge reden und wenn sich dann mit debugging auf der seite herausstellen sollte das es in der Tat ein Problem gibt auf seiten von RaspberryMatic (mit belegen, beispielen, etc.) dann kannst du gerne das Ticket hier wieder aufmachen.

**Comment by Marco4223** [comment]
Hätte die Homebridge wohl raus lassen sollen. Die RaspberryMatic friert ja ein und Programme steuern keine lampen. Es geht halt nur noch direkte einschlaten und ncht mehr per programm. Hätte einfach nur gerne einen tipp gehabt wie man hier mehr Informationen herraus bekommt die auf Fehler deuten!

**Comment by jens-maus** [comment]
Ich kann das gut verstehen, aber GitHub ist kein Diskussionsforum und auch nicht der direkte Draht zu mir, sondern das ist hier ein Ticket system wo man einfach Fehler meldet wo man sich entweder 100% sicher sein muss das es ein fehler in RaspberryMatic ist oder das Problem von mehreren Personen verifiziert wurde und alles darauf hindeutet das es sich um ein Problem in RaspberryMatic handelt – nicht mehr nicht weniger.

Für solche Support-Sachen ("hier geht etwas nach einem update irgendwie nicht mehr") ist das HomeMatic Forum da und das sollte dafür genutzt werden weil da mehr als nur meine Person antworten und einem dort kompetent geholfen werden kann.

**Comment by Marco4223** [comment]
Kein Problem, in dem Forum stehen meine Anfragen auch immer unbeantwortet. 
Aber für dich (und alle anderen) zur Info:
Downgrade auf die Version 2.35.16.20180826 und alles läuft wieder ohne Probleme.
Gehe ich dann erneut auf die oben genannte Version geht wieder nichts mehr.

**Comment by jens-maus** [comment]
Na das ist doch mal ne Zusatzinfo die du gleich hättest geben können, das du eben von solche einer Uralt-version (2.x) versuchst ein Update auf eine aktuelle (3.x) zu machen. Dann leg ich dir schonmal den ratschlag nahe dich mit all den änderungen zu beschäftigen die die 3.x mit sich bringt, nämlich z.B. ein verbessertes Sicherheitskonzept/Firewall das es aber notwendig machen das du einstellungen vornimmst in der WebUI die zu deinem homebridge setup passen bzw. umgedreht, veränderungen/updates an hombridge vornimmst die zu  der 3.x version von RaspberryMatic/CCU3 passen. Geholfen wird dabei im Forum.

**Comment by Marco4223** [comment]
Ich bin von der letzten 3.x Version auf die neue Version gewechselt. Der Downgrade war gerade eine Verzweifklungstat die es aber gebracht hat. 
Es ist also egal von welcher Version man af die aktuelle wechselt. Bei der neuen Versn stimmt zumindest in meiner Konstellation nicht. 
Aber gibt ja nicht nur mich der die aktuelle Version meiden wird da bei ihm dann das ganze System schon garnicht mehr startet. Siehe hier: https://github.com/jens-maus/RaspberryMatic/issues/730#issuecomment-550172678
Die Version scheint also berechtigt ein Problem zu haben....kann aber auch an der aktuellen HomeBridge liegen die mit der letzten 3.x und der 2.x läuft! 
Sorry, das wird mir hier leider ein bischen zu blöde. In der Zeit hättest Du mir sehr warscheinliich schon ein paar iniformationen zum debuggen geben könnne und man hätte den Fehler eingrenzen können.

**Comment by jens-maus** [comment]
Na wenn dir das "zu blöde" wird, dann ist ja gut das ich das Ticket geschlossen habe.
