### ISSUE TITLE
Prozent-Systemvariable beginnt mit -1

### ISSUE THREAD

**Issue by henrydiesner** [jens-maus/RaspberryMatic#737]
**Describe the bug**
Die Systemvariablen DutyCycle und DutyCycle-RaspberryMaticLGW sind Prozentvariablen, beginnen aber mit -1 (Minimalwert). 
![grafik](https://user-images.githubusercontent.com/5823795/68397400-6f655480-0173-11ea-85f7-6588776f71a4.png)
Das führt bei der Übernahme in openHab zu Fehlermeldungen, weil bei Prozentangaben Werte von 0 bis 100 erwartet werden.
**To Reproduce**
OpenHab Logfile:
![grafik](https://user-images.githubusercontent.com/5823795/68398125-8ce6ee00-0174-11ea-846e-475bf6daf347.png)

**Screenshots**
sieh oben
**System information (please complete the following information):**
 - RaspberryMatic 33.47.22.20191026
 - RaspberryPi3

**Additional context**
Natürlich ist openHab nicht Thema des (hervorragenden!) RaspberryMatic. Jedoch ist openHab eine sehr gute Ergänzung und Brücke zu anderen Systemen im intelligenten Haus.
Vielleicht besteht die Möglichkeit, die Systemvariablen wieder mit einer 0 beginnen zu lassen.

**Comment by friedpa** [comment]
The -1 is only used when the Gateway(s) are not accessible, which would mean something different, if it would show e.g. 0% for not accessible, as my Gateways are often showing 0% (when I do not switch e.g. anything in the Garden).
![image](https://user-images.githubusercontent.com/42890695/68421232-25459880-019e-11ea-96fb-d57d774cb2ad.png)

**Comment by jens-maus** [comment]
Wie schon geschrieben wurde ist -1 ein besonderer Status hier. Und zwar eben für die Nichterreichbarkeit eines LAN-GW. Es ist also momentan nicht geplant dies zu ändern, weil das in RaspberryMatic entsprechend genutzt wird. 

Auch kann ich ehrlich gesagt nicht wirklich nachvollziehen warum openHab da anscheinend prozenzwerte auf 0-100% limitiert?!? Mathematisch sind prozentwerte definitiv nicht auf diesen Bereich beschränkt und abgesehen von dieser automatischen Systemvariablen kann ein Nutzer sich ja in der WebUI selbst auch Prozentuale Systemvariablen über einen breiteren Bereich definieren (wenn er es denn will/braucht). Insofern würde ich vorschlagen das eben im OpenHab Projekt als Enhancement-Request/Fix zu melden da es wie gesagt IMHO unangebracht ist das OpenHab hier prozentwerte auf 0-100% beschränkt und abgesehen davon sollte das definitiv auch keine exception werfen.

**Comment by kaikreuzer** [comment]
> Auch kann ich ehrlich gesagt nicht wirklich nachvollziehen warum openHab da anscheinend prozenzwerte auf 0-100% limitiert?!?

Naja, weil in 99% der Fälle, wo es was anderes gibt, dies meist eine sehr spezifische Semantik hat, so wie das hier der Fall zu sein scheint. Ein -1 heißt ja gerade nicht, dass der Dutycycle bei -1% Auslastung liegt, obwohl dieser Prozentwert angeblich den Dutycycle angibt...

Aber schon richtig, das kann gerne im Homematic-Binding von openHAB gefixt werden: Das muss einfach wissen, dass -1 hier eine andere Bedeutung hat und darf dies nicht einfach auf den Channel durchreichen.

**Comment by henrydiesner** [comment]
Herzlichen Dank an die beiden Vorreiter der jeweiligen Systeme openHAB und RaspberryMatic für die promte Reaktion. Ich bin begeistert!

**Comment by jens-maus** [comment]
@kaikreuzer Danke für den Hinweis. Allerdings ist es ja so das hier eine allgemeine Systemvariable der CCU/RaspberryMatic abgefragt wird und nicht irgendetwas festes. Diese heisst jetzt in diesem Fall einfach "DutyCycle". Und Nutzer können eben weitere Systemvariablen ganz frei definieren und auch deren Min/Max Werte. Daher erscheint es mir immer noch sinnvoll doh darüber nachzudenken im openhab Binding von homematic prozentwerte nicht auf irgendwelche festgelegten grenzen zu beschränken. Sonst legt sich hier ein nutzer ggf. selbst eine Systemvariable vom typ zahl an die prozentwerte im bereich [-100 - 100]% liegt, dann kann aber openhab damit nicht umgehen bzw. diese abfragen, soweit ich das sehe.

**Comment by kaikreuzer** [comment]
Wie gesagt, das semantische Mapping muss im openHAB Binding gelöst werden.
Momentan scheint hier ein DimmerItem als openHAB-Datenpunkt definiert zu sein - denn nur für diese gibt es Prozentwerte (neben Rollläden). Und der Prozentwert bewegt sich damit auf einer Range von 0-100%.
Sinnvoller ist es hier wohl, einfach ein openHAB-NumberItem zu verwenden - das kann beliebige Zahlenwerte annehmen und auch mit beliebigen Einheiten (oder eben "%") ausgestattet werden (wobei ein "-1 %" hier immer noch nicht wirklich Sinn macht...).
