### ISSUE TITLE
Add X509v3 Extension "subjectAltName" to SSL Certificate

### ISSUE THREAD

**Issue by libertyx82** [jens-maus/RaspberryMatic#738]
**Is your feature request related to a problem? Please describe.**
Without the SAN "subjectAltName" Extension newer Browsers are blocking self signed Certificates also when the Certificate was imported to the Client Certificate Store as "Trusted Root Certification Authorities"

**Describe the solution you'd like**
Add the SAN Extension to the openssl Certificate creation

https://www.heise.de/security/artikel/Chrome-blockt-Zertifikate-mit-Common-Name-3717594.html

**Comment by jens-maus** [comment]
Thanks for the hint. I just added changes that should now add the subjectAltName to newly generated certificates starting with the next version. So, if required, existing certificates should be newed by pressing "Create Certificate" in the WebUI.
