### ISSUE TITLE
HMIP Devices showing "Gerätekommunikation gestört"

### ISSUE THREAD

**Issue by friedpa** [jens-maus/RaspberryMatic#739]
**Describe the bug**
Since the last update of the RM all my HMIP devices are in "Gerätekommunikation gestört". There are only three of them, but I tried several things to get them functional again, but so far no success.

**To Reproduce**
1. Go to Servicemeldungen
2. Find HMIP Devices with Service issues

**Expected behavior**
Did work with previous Version of RM

**Screenshots**

![image](https://user-images.githubusercontent.com/42890695/68892144-96e39080-0722-11ea-9975-9c72746e0794.png)

If I press the button on the HMIP Device the AskSinAnalyser shows:

![image](https://user-images.githubusercontent.com/42890695/68892299-f93c9100-0722-11ea-866d-3e87e9c14ee9.png)

**System information (please complete the following information):**
 - Version RaspberryMatic 3.47.22.20191026
 - Hardware RaspberryPi3 Charly

**Comment by jens-maus** [comment]
Dies scheint ein Duplikat von #746 zu sein. Wenn auch das Anlernen von HmIP Geräten nicht mehr geht ist es nur logisch das es bei anderen zu Gerätekommunikationsproblemen kommt. Aber auch hier gilt. Das kann kein allgemeingültiges Problem sein da zich andere Installationen problemlos mit HmIP kommunizieren können. Bitte also an das HomeMatic Forum wenden um in Diskussionen andere Leidensgenossen zu finden und Lösungen zu erarbeiten.
