### ISSUE TITLE
problem with my-homematic service after reboot

### ISSUE THREAD

**Issue by schneidy76** [jens-maus/RaspberryMatic#74]
After the RaspberryMatic has rebootet or the System is restore from a backup file, the service my-homematic is not available. 
The problem is unique to the beta 4&5.

**Comment by aberghoff** [comment]
Start manually:
/usr/local/etc/config/addons/mh/cloudmaticcheck.sh

**Comment by jens-maus** [comment]
Please note the comments (bottom) in the CloudMatic FAQ regarding problems with RM:

http://kb.easy-smarthome.de/cloudmatic/connect/faq

**Comment by TitusP** [comment]
I've the same issue. Neither the official work around, nor starting it manually works for me.

With Beta4 release I had cloudmatic connection issues as well. But that could be solved deleting the cloudmatic credentials and connecting again (this has been raised and solved in homematic forum). This time it doesn't work for me.

**Comment by jens-maus** [comment]
@TitusP Can you try to apply my latest patch (see https://github.com/jens-maus/RaspberryMatic/commit/a0245aa49d8cebc1c4de8e4327f3d310372b091e) to `/etc/init.d/S00eQ3SystemStart` and see if this solves the CloudMatic related issues upon startup?

**Comment by TitusP** [comment]
@jens-maus Unfortunately I'm receiving an error message, if I want to edit (save) or exchange this file in the running system.
_scp: /etc/init.d/S00eQ3SystemStart: Read-only file system_

**Comment by jens-maus** [comment]
Of course because the root fs is mounted read only per default. You have to remount it for rw mode via the following command first:

```
mount -rw,remount /
```

Then you can do modifications. Afterwards mount it read-only again via

```
mount -ro,remount /
```

**Comment by TitusP** [comment]
Ok, thx. Following status:
At first the posted remount command did not work for me in this way. I had to use:
`mount -o remount, rw /`
After exchanging the file, it still did not work. Then I had a look on the following troubleshooting
[https://www.meine-homematic.de/fehlersuche](url) and extended the firewall settings as described, and **now it works**.

**Comment by jens-maus** [comment]
@TitusP Sorry, but please be more specific. What didnyou change now exactly to get it finally work? What was you first step and which one was you last and the final change to get it working. Be more verbose here please

**Comment by TitusP** [comment]
1. I logged in with SSH and remounted the file system in rw mode.
2. I saved the existing `/etc/init.d/S00eQ3SystemStart` and exchanged it with your patched [https://github.com/jens-maus/RaspberryMatic/commit/a0245aa49d8cebc1c4de8e4327f3d310372b091e](url) version.
3. I remounted the file system as read only and did a reboot.
4. I logged in at the WebUI and opened the CloudMatic dashboard. There I stopped and restarted the VPN service and triggered the system testing.
5. I tested the direct link (CloudMatic connect service) on the CloudMatic dashboard. After entering the CloudMatic credentials I have been routed directly to the WebUI. _Remark: I haven't tested this before._
6. I opened the EASY App on iOS. Connection was not possible!
7. I changed the firewall settings in the WebUI by adding 10.192.0.0/12 to "IP addresses for limited access" (free translation; german wording: "IP-Adressen für den eingeschränkten Zugriff").
8. Re-opened the EASY App and tested the connection. This time it worked.

**Comment by jens-maus** [comment]
@TitusP Thanks for the detailed information. Now that it works please perform another reboot and see if cloudmatic works right away after boot or if you require to perform additional actions again (hopefully not)

**Comment by TitusP** [comment]
I tried several reboots and until now everythings works fine.

But one thing I recognized. This evening I updated the firmware of my router. After that I was not able to establish a connection with CloudMatic. So I made a reboot of the RPi and the connection has been re-established.
So I'm not sure how the VPN to the CloudMatic service is designed, but seem so that a reconnection mechanism is missing or not working currently.

**Comment by jens-maus** [comment]
@TitusP Thanks for having clarified that it works now even after reboot. Thus, I will close this ticket as finished. Regarding the VPN reconnect interval, please ask the developers of CloudMatic if and how the VPN should automatically reconnect.
