### ISSUE TITLE
Kommunikation Rolladenaktor (HM-LC-Bl1PBU-FM)

### ISSUE THREAD

**Issue by pitje-87** [jens-maus/RaspberryMatic#740]
Guten Morgen,

bei der aktuellen Raspimatic Version 3.47.22.20191026 kommt es bei der Kommunikation mit dem bei mir am weitesten entfernten Funk-Rolladenaktor zu Kommunikationsproblemen.

Der Aktor reagiert auf die Buttons Hoch/ Runter übermittelt aber anschließend nicht den Status zurück. So fährt der Rolladen runter, signalisiert aber nicht, dass dieser auf wirklich geschlossen ist. Im Status bleibt das Zahnrad erhalten.

Komme von 3.47.10.20190713 wo alles tadellos funktioniert hat. Nach einem Rollback funktioniert es wieder tadellos. Dabei wurde die Hardwarekonfiguration nicht geändert (Antenne, Ausrichtung etc.)

Gibt es ähnliche Probleme bzw. eine Lösung?

**Comment by jp112sdl** [comment]
Hast du mal den Browsercache gelöscht oder einen anderen Browser verwendet?

Habe mehrere Geräte in Verwendung und es wird alles korrekt angezeigt.

**Comment by pitje-87** [comment]
Hallo, die Anzeige ist nicht das Problem sondern die Funktion.

Was ich vielleicht noch erwähnen sollen: Auch die Fehlermeldung "Kommunikationsstörung" wird angezeigt.

Das ist das selbe Phänomen wie bei den HmIP Komponenten von neulich. Aktion wird ausgeführt aber die Fertigmeldung durch den Aktor kommt nicht durch.

Lg


-------- Ursprüngliche Nachricht --------
Von: "Jérôme" <notifications@github.com>
Gesendet: 17. November 2019 23:27:32 MEZ
An: jens-maus/RaspberryMatic <RaspberryMatic@noreply.github.com>
CC: pitje-87 <luckyluke@geekmail.de>, Author <author@noreply.github.com>
Betreff: Re: [jens-maus/RaspberryMatic] Kommunikation Rolladenaktor (HM-LC-Bl1PBU-FM) (#740)

Hast du mal den Browsercache gelöscht oder einen anderen Browser verwendet?

Habe mehrere Geräte in Verwendung und es wird alles korrekt angezeigt.

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen. Auch tritt das Problem hier in einigen eigenen Testinstallation nicht auf und kann daher nicht reproduziert werden.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!

**Comment by pitje-87** [comment]
Hallo Jens,
danke für deine Rückmeldung. Jedoch verstehe ich deine Aussage nicht.

- Die Hardware wurde vor dem Update nicht geändert. Software alles fehlerfrei.
- Nach dem Update treten die genannten Probleme auf.
- Nach einem Rollback auf die vorherige Version funktioniert alles ohne Probleme.

--> d.h. für mich als Laie: Hier muss ein **Fehler im Update** sein und kein "Userproblem".

Nach einem Update auf die aktuellste Version ist der Fehler übrigens auch weg. Nun könntest du dir die Arbeit machen und prüfen was geändert wurde, was ich aber keinesfalls von dir verlange.

Du redest in deinen Vorträgen immer über "Community". Dann meldet man einen Fehler und wird nicht erhört und abgestempelt? Schade.

LG

**Comment by libertyx82** [comment]
Ein generelles Problem kann es aber auch nicht sein, denn ich habe 6 HM-LC-Bl1PBU-FM und bin auf der 3.47.22.20191026 und habe keine Probleme.

**Comment by jens-maus** [comment]
@pitje-87 Das hat hier nichts mit "abstempeln" zu tun. Leider verwechseln aber viele (so wie du) GitHub mit einem Forum. Dies ist hier aber ein Bug/Issue Tracker, d.h. ein Tool wo man vermeintliche Fehler melden kann damit diese nicht vergessen und geordnet abgearbeitet werden können und nicht um Hilfe zu leisten oder gar in einer langwierigen Diskussion ein Problem zu ergründen. Und wenn ich hier ein Ticket schliesse ist das auch nichts persönliches, sondern schlichtweg dem geschuldet das ich als Maintainer das nicht nachvollziehen/reproduzieren kann und damit eben darum bitte erst einmal in einem großen Kreis im HomeMatic Forum um Hilfe zur ergründung der Probleme zu bitten und wenn dann dabei rauskommt das es definitiv ein problem ist und man das auch technisch begründen kann und nicht nur weil es in der vorversion nicht ging, dann kann man gerne ein ticket wieder aufmachen.

Und das du mit der aktuellsten wieder kein problem zu haben scheinst spricht für mich dafür das es einfach nur ein Ausrutscher bei dir in irgendeiner form war. Ggf. hätte auch einfach schon ein oder mehrere reboots mit zeitlichem abstand das problem wieder beseitigt. Also nicht übel nehmen...
