### ISSUE TITLE
Add Slovakia into the country list

### ISSUE THREAD

**Issue by buzzdev** [jens-maus/RaspberryMatic#741]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i see Slovakia (which is BTW part of EU and Shengen) still **NOT listed** in the country list. Even though in the latest version i see many countries added, Slovakia is still missing.

**Describe the solution you'd like**
Please add Slovakia into the country list. Capital of Slovakia is called Bratislava.

**Describe alternatives you've considered**
N/A

**Additional context**
<img width="1432" alt="Screenshot 2019-11-17 at 23 54 21" src="https://user-images.githubusercontent.com/6644151/69015583-a585ae00-0995-11ea-83f4-4f570ed85f47.png">

**Comment by jens-maus** [comment]
Thanks for your enhancement request. Of course making the list of selectable locations in the WebUI would be great. However, this is probably an endless job and in the end this just is a list that would make homematic users in these countries it more easily to directly select almost appropriate GPS coordinates and the right timezone settings.

Nevertheless, I fully agree that adding more (and specificallly Slovakia) would be great. But I would put this on low priority.  So if you have some free time, have a look at my WebUI patch which already added a lot more locations compared to the original CCU3 WebUI. And if you have some free time feel free to add more to it and submit it via a pull request against this patch:

https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0054-WebUI-AddTimeZones.patch#L57

**Comment by buzzdev** [comment]
Many thanxs Jens! :)
