### ISSUE TITLE
jQuery.url().param in /www/rega/pages/index.htm bleibt leer

### ISSUE THREAD

**Issue by jp112sdl** [jens-maus/RaspberryMatic#742]
**Describe the bug**
Additional parameters to `index.htm` are left out.

**To Reproduce**
Open `http://ccu/pages/index.htm?sid=@...@&debug=true` in a browser
The variable `urlDebug` stays undefined.

**Expected behavior**
Set `urlDebug` to the value of the parameter `debug` as it is implemented in
https://github.com/eq-3/occu/blob/master/WebUI/www/rega/pages/index.htm#L110

**System information (please complete the following information):**
 - Version [RaspberryMatic 3.47.22.20191026]
 - RaspberryPi3

**Additional context**
_The feature is necessary for webui development_

**Comment by psi-4ward** [comment]
The Problem is that the [RegEx](https://github.com/eq-3/occu/blob/master/WebUI/www/webui/js/extern/jqueryURLPlugin.js#L42) used to parse the URL is not able to handle the `@`-sign, used in `sid` correctly. 

A Solution could be this parseUri function:

```js
	function parseUri( url, strictMode ) {
		var str = decodeURI( url ),
		res   = parser[ strictMode || false ? 'strict' : 'loose' ].exec( str ),
		uri = { attr : {}, param : {}, seg : {} },
		i   = 14;

		while ( i-- ) {
			uri.attr[ key[i] ] = res[i] || '';
		}

		var qs = (function(a) { 
			if (a == "") return {};
			var b = {}; 
			for (var i = 0; i < a.length; ++i) { 
				var p=a[i].split('=', 2); 
				if (p.length == 1) b[p[0]] = ""; 
				else b[p[0]] = decodeURIComponent(p[1].replace(/\+/g, " ")); 
			} 
			return b; 
		})(window.location.search.substr(1).split('&')); 

		// build query and fragment parameters
		uri.param['query'] = qs;
		uri.param['fragment'] = parseString(uri.attr['fragment']);

		// split path and fragement into segments
		uri.seg['path'] = uri.attr.path.replace(/^\/+|\/+$/g,'').split('/');
		uri.seg['fragment'] = uri.attr.fragment.replace(/^\/+|\/+$/g,'').split('/');

		// compile a 'base' domain attribute
		uri.attr['base'] = uri.attr.host ? (uri.attr.protocol ?  uri.attr.protocol+'://'+uri.attr.host : uri.attr.host) + (uri.attr.port ? ':'+uri.attr.port : '') : '';

		return uri;
	};
```

It does **NOT** support custom url-parsings in `parseUri( url )` but the WebUI always uses `window.location` anyways.

**Comment by jens-maus** [comment]
Thanks for the report. Do you have a simple testcase at hand which I could use for testing? Thanks.

**Comment by psi-4ward** [comment]
You can execute `jQuery.url().param("sid")` within your javascript console

**Comment by jens-maus** [comment]
Ok, thanks. Now I could reproduce the issue. Also thanks to @psi-4ward for the suggested fix. I will see if I implement that or try to get the original regex fixed to recognize all url parameters correctly.

**Comment by jens-maus** [comment]
Ah, isn't GitHub and its PullRequests not a nice thing. Here  I found a pull request on the url parser class that seems to fix the issue (already suggested 2014):

https://github.com/allmarkedup/purl/pull/83

**Comment by psi-4ward** [comment]
Theres also a better approach with the WebAPI [URLSearchParams](https://developer.mozilla.org/de/docs/Web/API/URLSearchParams) but it's not supported in older browser.

**Comment by jens-maus** [comment]
@psi-4ward There are of course better URL parser classes these days, but we are not here to rewrite the CCU WebUI from scratch. So replacing the existing one with the latest 2.3.1 version and integrating the suggested fix is already invasive enough, I guess.
