### ISSUE TITLE
Rolladenaktor HmIP-FROLL Behanghöhe

### ISSUE THREAD

**Issue by agroezinger** [jens-maus/RaspberryMatic#743]
Servus,

Seite dem Update auf 3.47.22.20191026 habe ich das Problem, dass sich die Behanghöhe getauscht hat. Ich hatte seither schon immer bei mir eingestellt, dass 100% Behanghöhe Rolladen unten ist und 0% Behanghöhe Rolladen oben.

Das ist auch in den Geräte-Einstellungen so hinterlegt. Bei der Gerätebedienung wird mit aber 100% oben und 0% unten angezeigt, und der Rolladen verhält sich auch genau so. Also genau spiegelverkehrt wie es vorher war. In den Geräte-Einstellungen kann ich setzen was ich will.

LG,
Alex

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!
