### ISSUE TITLE
Guest-Agent für Proxmox vorinstallieren

### ISSUE THREAD

**Issue by SpezialAgent** [jens-maus/RaspberryMatic#744]
Hallo Jens,
ich teste gerade deine RaspberryMatic Version für X86 virtualisiert unter Proxmox.
In der letzten Version kann ich Raspberrymatic aus der Proxmox Gui runterfahren. 
Es wäre trotzdem besser, die Guest-Agents von Proxmox vorzuinstallieren.
Oder gibt es hierbei rechtliche Probleme?

Gruß
Martin

**Comment by jens-maus** [comment]
Wo gibt es die als OpenSource damit man die entsprechend integrieren kann?

**Comment by SpezialAgent** [comment]
Hallo Jens,

ich installiere unter Debian (9 oder 10) folgendes Paket:

Qemu-guest-agent <https://pve.proxmox.com/wiki/Qemu-guest-agent>

Sie liegen in den Repositories von Debian Buster oder auch Ubuntu.

Sie sollten frei sein, sonst wären sie nicht im Debian Repository.

Gruß

Martin
