### ISSUE TITLE
Nach Update auf 3.47.22.20191130 Totalversagen bei Gerätekommunikation

### ISSUE THREAD

**Issue by Tscherno** [jens-maus/RaspberryMatic#745]
**Describe the bug**
Update auf 3.47.22.20191130 durchgeführt. Seitdem kann zwar die Weboberfläche noch aufgerufen werden, aber sobald man versucht ein Gerät zu steuern oder Gerät zu konfigurieren entweder Endlosspinner oder Fehlermeldung. Beispiel bei Aufruf einer Gerätekonfiguration (Einstellungen):
"Das Gerät mit der Seriennummer '000A1709ACBC74' vom Interface 'HmIP-RF' konnte nicht abgefragt werden!"

Die letzten Einträge im Log sehen so aus:

![grafik](https://user-images.githubusercontent.com/5594674/69976653-9ec87080-1529-11ea-8897-19a2a0c1988d.png)

![grafik](https://user-images.githubusercontent.com/5594674/69976541-6fb1ff00-1529-11ea-9cb5-ec544cc34b54.png)

Auch Zugriff über Pocketcontrol ist nicht mehr möglich.

**To Reproduce**
1. Update auf 3.47.22.20191130
2. Reboot
3. Versuch Geräte zu bedienen

**Expected behavior**
Alles funktioniert wie vor dem Update.

**Screenshots**
Screenshots und Logfile angefügt

**System information (please complete the following information):**
 - Version 3.47.22.20191130  
 - RaspberryPi3

**Additional context**
[All_2019-12-2-17_25_15.zip](https://github.com/jens-maus/RaspberryMatic/files/3912578/All_2019-12-2-17_25_15.zip)

**Comment by Tscherno** [comment]
Ein Rollback auf die Vorgängerversion scheint es wieder gelöst zu haben.

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen. Auch in Testinstallationen konnte das Problem bisher nicht beobachtet bzw. reproduziert werden.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!
