### ISSUE TITLE
3.47.22.20191130 - HMIP Geräte lassen sich nicht mehr anlernen

### ISSUE THREAD

**Issue by friedpa** [jens-maus/RaspberryMatic#746]
**Describe the bug**
Nachdem ich die neue Version der RB installiert habe, mache ich immer ein paar basic Tests, dabei bin ich auf das Problem gestossen, dass ich keine HMIP Geräte mehr anlernen kann. Zumindest mein HMIP-PS den ich dazu immer verwende, wird nicht mehr erkannt.
Ich habe auch versucht eine andere HMIP-PS zu löschen, was auch nicht mehr ging. WebUI hat sich "aufgehängt"

**Expected behavior**
Auch ein HMIP Gerät lässt sich wie immer neu anlernen

**System information (please complete the following information):**
 -RaspberryMatic 3.47.22.20191130

**Comment by friedpa** [comment]
Ergänzung: über den AskSin Analyser bekomme ich bei HM IP Geräten nun:

![image](https://user-images.githubusercontent.com/42890695/70119757-4b5e3b80-166b-11ea-958b-d2a3a4b95592.png)

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen. Das gemeldete "Problem" kann leider kein allgemeingültiges Problem sein da es in einigen Testinstallation zu keinem solch einem Problem kommt.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!
