### ISSUE TITLE
WebUI-Update funktioniert nicht

### ISSUE THREAD

**Issue by winnall** [jens-maus/RaspberryMatic#748]
Nach einer Diskussion auf https://homematic-forum.de/forum/viewtopic.php?f=65&t=54850 bin ich zum Schluss gekommen, dass ein Bug möglicherweise vorliegt...

Schon seit einer Woche versuche ich, meinen RaspberryMatic von 3.45.7.20190511 auf zunächst 3.47.22.20191026 und seit gestern auf 3.47.22.20191130 zu updaten. Es bleibt aber beharrlich bei 3.45.7.20190511. Ich benutze das Verfahren unter Einstellungen > Systemsteuerung > Zentralen-Wartung.

Ich habe einen Raspberry Pi 3B+ mit RPI-RF-MOD und einem USB-DIsk mit 32Gb und Ethernetanschluss.

Kann es sein, dass der Update nicht funktioniert, wenn das System auf einem USB-Disk läuft?

Steve

**Comment by jens-maus** [comment]
Das kann sehr gut der Fall sein, weil das booten via USB Stick immer noch zu den experimental Features gezählt wird. Es kann aber auch gut sein, das in der aktuellen Version das Problem bereits beseitigt ist. Daher würde ich vorschlagen ein sbk Backup zu generieren, den USB Stick komplett neu mit der aktuellsten RaspberryMatic aufzusetzen und dann das Backup wieder einzuspielen. Dann wird sich spätestens mit der nächsten Version zeigen ob das WebUI Update dann geht.

**Comment by winnall** [comment]
OK. Danke, Jens.

**Comment by jens-maus** [comment]
Bitte auch die Kommentare in #416 beachten da es hier RaspberryPi bedingt auch eine Hardwarelimitation gibt die den Einsatz von USB Geräten als Bootmedium kritisch machen.
