### ISSUE TITLE
EDIMAX EW-7811UN Wireless USB Adapter not working

### ISSUE THREAD

**Issue by NetSecond** [jens-maus/RaspberryMatic#75]
"the" EDIMAX EW-7811UN Wireless USB Adapter is not working in the actual Image.
This issue is a remember for the Diskussion in homematic Forum.
More Details you find there.

The EDIMAX EW-7811UN is the most sold WLan Adapter for Raspberry Pi from Zero (without "W") to Pi2B. So it would be nice to Support it .... ;):D

Here is the relevant dames output of the device:
```
....
[    0.000000] Linux version 4.4.50-rt62-v7 (damato@bilbo) (gcc version 4.9.4 (Buildroot 2017.02-00363-g7789524) ) #1 SMP PREEMPT RT Wed Mar 15 22:00:01 CET 2017
....
[    0.000000] Machine model: Raspberry Pi 2 Model B Rev 1.1
....
[    2.179011] usb 1-1.3: new high-speed USB device number 4 using dwc_otg
[    2.280927] usb 1-1.3: New USB device found, idVendor=7392, idProduct=7811
[    2.280954] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Hier folgen die Angaben zum EDIMAX 7811un
[    2.280975] usb 1-1.3: Product: 802.11n WLAN Adapter
[    2.280994] usb 1-1.3: Manufacturer: Realtek
[    2.281013] usb 1-1.3: SerialNumber: 00xxxx0000xx
[    7.851030] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f200000
[    8.479728] usbcore: registered new interface driver rtl8192cu
[    8.884044] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   10.545626] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0xCDE1
[   15.866560] NET: Registered protocol family 10
[   15.890161] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
```

**Comment by jens-maus** [comment]
From the debug output you provide here (I added it from the homematic forum) I can see that the wlan interface seems to be actually active and should work. So please login via SSH again and execute the following command:

```
ifconfig -a
```

Also please see if the following command actually works and outputs all SSIDs found in your environment:
```
iw wlan0 scan
```

**Comment by NetSecond** [comment]
ifconfig -a
`eth0      Link encap:Ethernet  HWaddr B8:27:EB:D4:7A:67
          inet addr:192.168.178.28  Bcast:192.168.178.255  Mask:255.255.255.0
          inet6 addr: 2003:xx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx/64 Scope:Global
          inet6 addr: fe80::xxxx:xxxx:xxxx:xxxx/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:727 errors:0 dropped:0 overruns:0 frame:0
          TX packets:615 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:62129 (60.6 KiB)  TX bytes:695449 (679.1 KiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1262 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1262 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:460109 (449.3 KiB)  TX bytes:460109 (449.3 KiB)

wlan0     Link encap:Ethernet  HWaddr xx:xx:xx:xx:xx:xx
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)`

iw wlan0 scan:
`Here Comes a lot of wifi Networks incl. my own.`
