### ISSUE TITLE
Problem mit RPi 3 B+

### ISSUE THREAD

**Issue by ikarstein** [jens-maus/RaspberryMatic#750]
Ich möchte kurz meine Erfahrung von gestern teilen, ohne dass ich darauf "bestehe", dass es ein Bug ist. Aber vielleicht ist es einer und somit ist es vielleicht gut, folgendes zu melden:

Ich habe versucht, das aktuelle Image vom 30.11. (CCU3 ) auf einem Modell "B+" von RPi 3 zu installieren. Das hatte nicht geklappt. Ich habe viele Kombinationen versucht. Verschiedene SD-Schreibprogramme, verschiedene microSD-Card, verschiedene RPi 3 B+. Letztlich hab ich ein Raspbian ohne Probleme mit einer microSD auf einem RPi3 B+ problemlos zum Laufen bekommen.

Aufgesteckt auf den RPi 3 B+ war das Funkmodul von ELV. Auch ohne dieses Modul ging es nicht.

Lösen konnte ich mein Problem dadurch, dass ich einen RPi 3 B (ohne +) verwendete. Damit ging es sofort.

**Comment by jens-maus** [comment]
Tschuldigung, aber das kann ich heir leider nicht mit mehereren 3b+ rpi reproduzieren. Insofern ist das für mich leider nicht weiter bearbeitbar.

**Comment by ikarstein** [comment]
Danke, Jens. Leider hab ich nur diesen einen RPi 3 B+ und kann es nicht gegentesten.

**Comment by jens-maus** [comment]
Kann das Problem weiterhin nicht reproduzieren und bekomme auch sonst keine Rückmeldungen von anderen Nutzern das es ein prinzipielles Problem mit RaspberryPi3b+ support gibt. Daher schliesse ich dieses Ticket bis auf weiteres.
