### ISSUE TITLE
ReGaHss freeze bei Gewerkeauflistung => monit restart RegaHSS

### ISSUE THREAD

**Issue by FraatRamski** [jens-maus/RaspberryMatic#751]
**Describe the bug**
RaspberryMatic freeze > monit restart RegaHSS on larger setup > timeout?

**To Reproduce**
See in below.

**Expected behavior**
I Have a bigger setup ~ 140 Homematic devices. When I open "Gewerke/Bearbeiten" it seems that RaspberryMatic freeze. When I look to the log so it seems that monit run into "timeout" and is restarting RegaHSS. There is no entry in "Alarmmeldungen". I can reproduce this.  

LOG:

`
> Click on Gewerke:
> 
> Dec 14 14:31:07 homematic user.warn monit[1095]: 'ReGaHss' failed protocol test [HTTP] at [localhost]:8183 [TCP/IP] -- HTTP: Error receiving data -- Resource temporarily unavailable
> Dec 14 14:31:30 homematic user.warn monit[1095]: 'ReGaHss' failed protocol test [HTTP] at [localhost]:8183 [TCP/IP] -- HTTP: Error receiving data -- Resource temporarily unavailable
> Dec 14 14:31:52 homematic user.warn monit[1095]: 'ReGaHss' failed protocol test [HTTP] at [localhost]:8183 [TCP/IP] -- HTTP: Error receiving data -- Resource temporarily unavailable
> Dec 14 14:32:15 homematic user.warn monit[1095]: 'ReGaHss' failed protocol test [HTTP] at [localhost]:8183 [TCP/IP] -- HTTP: Error receiving data -- Resource temporarily unavailable
> Dec 14 14:32:37 homematic local0.err ReGaHss: ERROR: Send failed (errno=32)! [Send():iseSysLx.cpp:1596]
> 
> Click on Bearbeiten in Gewerke
> 
> Dec 14 14:34:29 homematic user.warn monit[1095]: 'ReGaHss' failed protocol test [HTTP] at [localhost]:8183 [TCP/IP] -- HTTP: Error receiving data -- Resource temporarily unavailable
> Dec 14 14:34:52 homematic user.warn monit[1095]: 'ReGaHss' failed protocol test [HTTP] at [localhost]:8183 [TCP/IP] -- HTTP: Error receiving data -- Resource temporarily unavailable
> Dec 14 14:35:15 homematic user.warn monit[1095]: 'ReGaHss' failed protocol test [HTTP] at [localhost]:8183 [TCP/IP] -- HTTP: Error receiving data -- Resource temporarily unavailable
> Dec 14 14:35:38 homematic user.warn monit[1095]: 'ReGaHss' failed protocol test [HTTP] at [localhost]:8183 [TCP/IP] -- HTTP: Error receiving data -- Resource temporarily unavailable
> Dec 14 14:36:01 homematic user.err monit[1095]: 'ReGaHss' failed protocol test [HTTP] at [localhost]:8183 [TCP/IP] -- HTTP: Error receiving data -- Resource temporarily unavailable
> Dec 14 14:36:01 homematic user.info monit[1095]: 'ReGaHss' trying to restart
> Dec 14 14:36:01 homematic user.info monit[1095]: 'ReGaHss' restart: '/etc/init.d/S70ReGaHss restart'
> Dec 14 14:36:11 homematic user.info ReGaHss: SIGTERM: ReGaHss Halting
> Dec 14 14:36:11 homematic local0.err ReGaHss: ERROR: Send failed (errno=32)! [Send():iseSysLx.cpp:1596]
`

I have disabled monit  with "monit unmonitor regahss" and tried again. It tooks arround 2Minutes to open "Gewerke" and another 1-2minutes to open "Gewerke/Bearbeiten" after click OK it tooks another 1-2 to close the windows. During this time it seems that RaspberryMatic is frozen but it is only very slow. When I look to the log there are no additional entries.

**Screenshots**

**System information (please complete the following information):**
 - Version  3.47.22.20191130
 - Hardware RaspberryPi3

**Additional context**

**Comment by jens-maus** [comment]
Danke für den Bugreport. Wie im Forum bereits an verschiedenen Stellen aufgezeigt scheint das Problem unter gewissen Bedingungen bzw. Gewerkeauflisteung aufzutreten die aber noch nicht genau verstanden sind. Auch bekomme ich das selbst hier nicht reproduziert und das obwohl ich selbst >160 Geräte angebunden habe. Die Frage wäre also ob hier ggf. jemand im besagten WebUI codeteil mehr debugging machen könnte damit wir dem ursprung des problems mehr auf die schliche kommen können. Denn das was hier gemeldet wird scheinen lediglich die symptome zu sein (das eben monit auf grund des blockierens von ReGaHss dieses gezwungenermaßen neustartet)...

@jp112sdl Wir hatten ja schonmal angefangen dazu im WebUI Quellcode rumzusuchen. Gibt es von deiner Seite noch neuere Erkenntnisse bzw. können wir irgendwie daran anknüpfen rauszufinden welcher Teil im WebUI code dieses ReGaHss freeze auslöst?

**Comment by jp112sdl** [comment]
Nein, ich hab mich nicht weiter damit befasst.
Zumal es bei mir auch nicht zum Absturz kommt, sondern lediglich eine Warnung erzeugt wird.
Was Warnungen betrifft, bzw. alles was _nicht Error_ ist, da bin ich eh relaxt.

Ich könnte mir höchstens noch vorstellen, dass externe Prozesse (ioBroker & Co.) evtl. ein Problem damit haben, wenn sie längere Zeit auf Antwort der ReGa verzichten müssen.

Die vom Monit ausgelösten Rega-Restarts könnte man ja vielleicht erstmal mit einer höheren Monit-Fehlertoleranz unterbinden?

Das "Hängen" des ReGa-Prozesses wird ja nicht neu sein.

**Comment by jens-maus** [comment]
In dem Kontext ist mir das Hängenbleiben von ReGa schon eine Neuheit und kenne ich so nicht. Das sollte auch so IMHO nicht passieren und ich verstehe momentan nicht warum das bei manchen Personen anscheinend reproduzierbar immer auftritt nur bei mir nicht und das obwohl ich auch >160 Geräte habe. Ich würde im ersten schritt einfach gerne durch patchen des WebUI codes rausfinden wollen welcher Teilbereich dafür verantwortlich ist das ReGaHss anscheinend soweit busy ist das es während der zeit nichts anderes machen kann. ggf. kann ich dann ja daran (wenn wir die entsprechende HomeMatic Skript anweisungen für die reproduzierbarkeit des problems isoliert haben) ja dann innerhalb von ReGaHss etwas optimieren damit es nicht mehr so lange bzw. gar nicht mehr blockiert wird und folglich der Webserver in ReGa nicht blockiert wird und somit dann auch Monit kein Problem mehr haben sollte.

**Comment by jp112sdl** [comment]
Auf der CCU2 ist es übrigens das selbe (und war es m.E. auch schon immer).
Egal ob ReGa "Kompatibilitätsmodus" oder "Standard".
Während die Gewerke geladen werden, wird in einem neuen Browser-Tab keine neue Session aufgebaut.
Erst wenn Gewerkeliste fertig gehts weiter.

**Comment by jens-maus** [comment]
Danke für die Info. Umso mehr würde mich interessieren was genau denn daran bitte die ReGa so lange blockiert. Vielleicht kannst du als betroffener ja mal die besagte WebUI codezeile herausfinden welche diese blockierung auslöst und dann kann ich schauen ob ich hierfür eine Lösung auch ggf. in ReGa selbst erarbeiten kann.

**Comment by FraatRamski** [comment]
..."Vielleicht kannst du als betroffener ja mal die besagte WebUI Codezeile herausfinden welche diese blockierung auslöst" gerne, kannst du mir sagen ich wie ich das mache?

**Comment by jens-maus** [comment]
Damit meinte ich eigentlich @jp112sdl weil der auch davon betroffen ist.

**Comment by jp112sdl** [comment]
Ich habe jetzt mal allen TCL-Kram aus der functions.htm extrahiert (https://pastebin.com/jUv71mh8) und über "Skript testen" laufen lassen. Es wird ne Menge HTML generiert und auch ausgegeben.
Zwischen einzelnen Funktionsblöcken habe ich noch die Zeit in einer Variable gespeichert, um zu schauen, wo es lange dauert (offenbar im letzten Block nach `var c = ...`.
Die gesamte Laufzeit ist dieselbe. Bei mir ~ 14 Sekunden.
```
Startzeit a = 22:48:40
Startzeit b = 22:48:40
Startzeit c = 22:48:40
Endzeit   d = 22:48:57
```

Aber: Die ReGa reagiert währenddessen komplett normal. Auch lassen sich neue Session öffnen.

Scheint hier der Laufzeitkontext entscheidend zu sein?
Kontext _Skripte über Aufruf Menü "Gewerke"_ != _Skripte über Skript testen_ ?

**Comment by jp112sdl** [comment]
Was mir dabei noch aufgefallen ist:
- Skript testen: Der Heartbeat im Logo blinkt während der Wartezeit weiter
- Menü Gewerke: Heartbeat bleibt stehen

**Comment by jens-maus** [comment]
Danke für die Analysen, die sind wirklich sehr hilfreich. Um zu verstehen warum es sich anscheinend unter Skript testen anders verhält wäre es vllt eine gute Idee einfach sukzessive dinge in der functions.htm auszukommentieren bis man den teil gefunden hat der die blockade auslöst bzw den größten teil des processing ausmacht....

**Comment by jp112sdl** [comment]
>  den größten teil des processing ausmacht....

```
      foreach( tmp, elem.EnumEnabledIDs() )
      {
        object chnTmp = dom.GetObject(tmp);
        if( chnTmp && chnTmp.IsTypeOf(OT_CHANNEL) )        
        {
          iLinkCount = iLinkCount + chnTmp.ChnLinkCount();
          if( chnTmp.ChnDPUsageCount() != ID_ERROR )
          {
            iProgCount = iProgCount + chnTmp.ChnDPUsageCount();
            iProgCount = iProgCount + chnTmp.ChnDPUsageCount();
          }
      !    if( !sEnumPrgFilter.Length() )
      !    {
      !      sEnumPrgFilter = chnTmp.ChnEnumDPUsagePrograms();
      !    }
      !    else
      !    {
      !      sEnumPrgFilter = sEnumPrgFilter#"\t"#chnTmp.ChnEnumDPUsagePrograms();
      !    }
        }
      }
```

Bei jedem `chnTmp.ChnDPUsageCount` (über alle `elem.EnumEnabledIDs()`) dauert es 4-5 Sekunden. 
Wird 3x aufgerufen => macht meine üblichen ~14-15 Sekunden.

**Comment by jp112sdl** [comment]
Ich bau das _morgen_ (unter Vorbehalt!) mal um nach

```
          var chnusagecount = chnTmp.ChnDPUsageCount();
          if( chnusagecount != ID_ERROR )
          {
            iProgCount = iProgCount + chnusagecount;
            iProgCount = iProgCount + chnusagecount;
          }
```

Das sollte das Ganze schon mal wesentlich schneller machen.

**Comment by jp112sdl** [comment]
Beim ☕️ mal schnell den Workaround durch den Skripttester gejagt:
```
Startzeit = 06:33:00
Endzeit   = 06:33:07
```

von [hier](https://github.com/jens-maus/RaspberryMatic/issues/751#issuecomment-566765778) noch **17 Sekunden**!


Ich bin begeistert! 🎉

**Comment by jens-maus** [comment]
@jp112sdl Also ich hab mir mal in der WebUI die besagte Stelle (https://github.com/eq-3/occu/blob/master/WebUI/www/rega/pages/tabs/admin/views/functions.htm#L368-L392) nun selber mal angeschaut und ehrlich gesagt kapier ich gerade schon gar nicht warum es diese `iLinkCount` und `iProgCount` Berechnungen überhaupt gibt?! Denn ich sehe in der Datei keinerlei weitere Referenzen auf diese sodass ich momentan das gefühl habe das diese und die Nutzung von `ChnDPUsageCount()` IMHO komplett entfernt werden könnten. Auch gibt es an anderen Stellen in der WebUI noch weitere Nutzungen dieser `ChnDPUsageCount()` Funktion die man entsprechend optimieren könnte. Innerhalb der ReGa sehe ich momentan zumindest keine unmittelbare möglichkeit zur optimierung da diese funktion einfach eben durch alle collections geht und die Anzahl von Referenzen zählt und das dauert eben entsprechend und ist abhängig davon wieviele programme, direktverknüpfungen, kanäle, etc. man eben insgesamt hat...

**Comment by jp112sdl** [comment]
Hab den [Block](https://github.com/eq-3/occu/blob/master/WebUI/www/rega/pages/tabs/admin/views/functions.htm#L368-L392) mal komplett auskommentiert. 
Ich kann in der WebUI optisch keinen Unterschied feststellen.
Hab grad nur die CCU2 hier... aber da musste ich vorher extrem lange warten. Nun gehts in wenigen Sekunden 🤓 

Man müsste diesen Workaround mal als Patch anbieten, damit noch mehr Leute das testen können!?

**Comment by jens-maus** [comment]
Bin schon dabei einen Patch zu erarbeiten der diese Stelle wegoptimiert und auch die anderen zich stellen wo diese `...Count()` Funktionen IMHO zu exzessiv verwendet werden  beseitigt. Denke ich werd dann heute einen neuen Release-Candidate mit einem entsprechenden Patch anbieten. Danke nochmal für den Testen und sobald der Patch fertig ist kannst du den ja gerne mal auf deine System loslassen und berichten!

**Comment by jens-maus** [comment]
So, dieser Fix hier sollte hoffentlich das Problem mit der langsamen Gewerkeauflistung beheben und damit auch das problem das Monit sich gezwungen fühl ReGaHss auf grund der nicht-erreichbarkeit neuzustarten: https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0065-WebUI-Fix-CountUsageStalling.patch

Auch hab ich an verschiedenen anderen Stellen wo die besagte ReGa Funktionen genutzt wurden Optimierungen vorgenommen die auch hier/da Beschleunigungen bringen sollten.

Wäre schön wenn soviele Tester wie möglich sich dafür finden könnten. Lade auch gerade neue release candidates unter folgender cloud URL hoch wo der Fix integriert sein sollte: 
https://cloud.light-speed.de/s/mfMsM8S3kAHmJYo

**Comment by FraatRamski** [comment]
Ich habe es jetzt mit der RC ausprobiert.
Ladezeit alt: 118 Sekunden
Ladezeit neu: 28 Sekunden

Es gab 2x RegaHss Error, kein Neustart von RegaHss bis jetzt.

 Dec 18 19:24:12 homematic local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1007, params: {"NEQ1100490:1","BRIGHTNESS"}) [CallGetValue():iseXmlRpc.cpp:1435]
Dec 18 19:24:12 homematic local0.err ReGaHss: ERROR: CallGetValue failed; sVal = 0 [ReadValue():iseDOMdpHSS.cpp:124]
Dec 18 19:24:22 homematic user.warn monit[1152]: 'hasUSB' status failed (1) -- no output
Dec 18 19:24:22 homematic user.err monit[1152]: Filesystem '/media/usb1' not mounted
Dec 18 19:24:22 homematic user.err monit[1152]: 'usb1' unable to read filesystem '/media/usb1' state
Dec 18 19:24:22 homematic user.info monit[1152]: 'usb1' trying to restart
Dec 18 19:24:40 homematic user.err monit[1152]: 'hasUSB' status failed (1) -- no output

Klick  Gewerke
> 
### 
>

Dec 18 19:30:51 homematic daemon.info chronyd[569]: Selected source 212.18.3.19
Dec 18 19:32:49 homematic user.warn monit[1152]: 'ReGaHss' failed protocol test [HTTP] at [localhost]:8183 [TCP/IP] -- HTTP: Error receiving data -- Resource temporarily unavailable
Dec 18 19:32:57 homematic local0.err ReGaHss: ERROR: Send failed (errno=32)! [Send():iseSysLx.cpp:1596]

**Comment by jp112sdl** [comment]
Das Problem scheint irgendwie zu sein, dass immer wenn eine Seite synchron geladen wird, alles steht. 
Es fällt nur nicht wirklich auf, weil alle anderen Seiten in 1...2 Sekunden spätestens geladen sind.
Nur halt bei den Gewerken... Hmm, aber es ist ja zumindest schon mal eine Verbesserung eingetreten.

**Comment by jens-maus** [comment]
@jp112sdl Die Frage wäre welches nach der Optimierung nun in der Gewerkeauflistung immer noch dafür verantwortlich ist das diese anscheinend immer noch nicht so performant ist wie die anderen Seiten. Immerhin wurden die `ChnDPUsageCount()` Aufrufe ja komplett entfernt in der `functions.htm`. Aber vielleicht gibt es ja noch andere Funktionen die ähnlich die Bearbeitung immer noch ausbremsen oder in anderen Dateien gibt es immer noch irgendwie bottlenecks...

**Comment by jens-maus** [comment]
Eine Frage wäre z.B. ob die folgende weitere Nutzung von `ChnDPUsageCount()`& Co wirklich dort notwendig ist (Ich kann keine weitere referenz von "devC"  finden... Kannst du mal schauen ob das entfernen dieser Zeilen ggf. möglich ist weil `devC` und `progC` ohnehin nirgends genutzt wird?

https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0065-WebUI-Fix-CountUsageStalling/occu/WebUI/www/rega/pages/tabs/admin/views/functionchannels.htm#L107-L112

**Comment by jp112sdl** [comment]
Wo wird die `functionchannels.htm` aufgerufen?
Ohne `devC` und `progC` sehe ich visuell zumindest keine Veränderung in den Gewerken, auch nicht wenn ich am :heavy_plus_sign: die Kanäle aufklappe.
_Und ich kann ebenfalls nicht erkennen, dass die beiden Felder in dem Array noch irgendwo verwendet werden._

**Comment by jp112sdl** [comment]
> welches nach der Optimierung nun in der Gewerkeauflistung immer noch dafür verantwortlich ist das diese anscheinend immer noch nicht so performant ist wie die anderen Seiten.

Das einzige, was bei mir jetzt noch dauert, ist `ChnEnumDPUsagePrograms` in
https://github.com/eq-3/occu/blob/14b4d073ec2ad199889f29a2d3326096afbffbbc/WebUI/www/rega/pages/tabs/admin/views/functions.htm#L383-L390

Wenn ich das rausnehme, dann ist bei mir die Gewerkeliste in unter 1 Sek. geladen.
Ansonsten dauert es 4 Sek.


Aber ich fürchte, das lässt sich nicht entfernen, da hier die entsprechenden Programme gefiltert werden.
