### ISSUE TITLE
HmIP-WRCD kompatibel?

### ISSUE THREAD

**Issue by richardmayer** [jens-maus/RaspberryMatic#754]
Hallo,

ich habe gestern meinen HmIP-WRCD ePaper-Display Bausatz bekommen und schaffe es nicht, diesen an Raspberrymatic anzulernen.
Der Anlernmodus ist aktiv (orange LED blinkt alle 10 Sekunden) aber ich bekomme das Gerät nicht angelernt.

Sollte das Status-Display denn grundsätzlich kompatibel/untersützt sein von Raspberrymatic?

Schöne Grüße

Richard

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!

**Comment by patrick-werner** [comment]
@jens-maus: Anlernen eine WRCDs ist nicht im Onlinemodus möglich, nur per Key. Das würde ich als Bug/fehlendes Feature werten.

**Comment by jens-maus** [comment]
Da kann nur eQ3 etwas dran drehen/ändern. Die komplette HmIP Funktionalität ist im Closed Source Java Teil der CCU/OCCU Firmware und insofern kann da nur eQ3 was dran ändern *wenn* das wird ein Problem ist. Kann auch gut sein das einfach deine Internetverbindung nicht stabil läuft und daher der online anlernmodus nicht geht...

**Comment by patrick-werner** [comment]
Danke für die Erläuterung, ich hatte schon closed Source Code befürchtet. Ich gehe davon aus, dass das Problem bei eQ3 liegt. Alle Foreneinträge enden mit der Offlinemethode, keiner hatte raspberrymatic im online modus mit dem Taster verbinden können.
