### ISSUE TITLE
Mehrere HB-RF-USB(TK) an einer Raspberrymatic betreiben

### ISSUE THREAD

**Issue by peoples0815** [jens-maus/RaspberryMatic#755]
**Is your feature request related to a problem? Please describe.**
Mein Feature Request hat den Ursprung dass man HM-IP-Geräte nicht an Funk-Lan-Gateways betreiben kann.

**Describe the solution you'd like**
Die Lösung wäre es nun wenn man zwei HB-RF-USB(TK) Module an einer Raspberrymatic betreiben könnte, denn so könnte man bspw. über einen USB-to-Ethernet-Extender die Module dort positionieren wo man sie benötigt. Würde sich zum einen das Gateway für die normalen Hm Geräte sparen und die Reichweite der Ip-Geräte wäre ohne "Repeater" möglich.

Nur ein nice to have ob technisch möglich müsstest du als Profi wissen.

**Comment by libertyx82** [comment]
Das dürfte schwierig werden, denn zwei Funkmodule an einer Zentrale dürfte nicht gehen.
HM Geräte können auch immer nur mit einer Zentrale (Funkmodul) verbunden werden.

**Comment by jens-maus** [comment]
Wünschen kann man sich natürlich vor allem heute ja prinzipiell alles, aber man sollte schon realist bleiben auch bei seinen wünschen und hier ist es leider dass zwei HB-RF-USB genauso technisch nicht möglich sind wie auch zwei RPI-RF-USB...
