### ISSUE TITLE
FS20-Devices nicht erreichbar

### ISSUE THREAD

**Issue by McMike63** [jens-maus/RaspberryMatic#757]
**Describe the bug**
Nach dem Update auf die neueste Version war es nicht möglich mit Hilfe von FS-20 Wandtaster Verbraucher zu schalten, die über HM-Schalter angeschlossen sind.

**To Reproduce**

**Expected behavior**
Klärung, ob es für das Problem einen Workaround gibt.

**Screenshots**

**System information (please complete the following information):**
 - Version RaspberryMatic 3.49.17.20191225 
 - Hardware RaspberryPi3, PIGATOR4P

**Additional context**

**Comment by jens-maus** [comment]
Tut mir leid, aber mit FS20 Komponenten hab ich selbst keinerlei Erfahrung und kann diesbzgl. auch nicht helfen. Bitte im HomeMatic Forum erst diskutieren ob es sich hierbei definitiv um ein Problem in RaspberryMatic handelt.
