### ISSUE TITLE
BuildError - '.././configure: line 2304: config.log: Invalid argument'

### ISSUE THREAD

**Issue by Hoytron** [jens-maus/RaspberryMatic#758]
Ich versuche gerade die RaspberryMatic Images selbst zu bauen, um in Zukunft hier und da bei der Entwicklung zu Helfen. Jedoch schlägt der build-Prozess fehl. 
Vielleicht kann mir hier jemand Helfen. 

Ich verwende das [build enviroment](https://github.com/mdzio/rm-build-env) im Dockercontainer von @mdzio und bekomme immer wieder diesen Fehler: 

```[...]
configure: WARNING: unrecognized options: --disable-gtk-doc, --disable-gtk-doc-html, --disable-doc, --disable-documentation, --with-xmlto, --with-fop, --disable-nls
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
continue configure in default builddir "./x86_64-pc-linux-gnu"
....exec /bin/sh .././configure "--srcdir=.." "--enable-builddir=x86_64-pc-linux-gnu" "linux
gnu"
configure: WARNING: unrecognized options: --disable-gtk-doc, --disable-gtk-doc-html, --disable-doc, --disable-documentation, --with-xmlto, --with-fop, --disable-nls
.././configure: line 2304: config.log: Invalid argument
.././configure: line 2314: config.log: Invalid argument
make[2]: *** [/rmbuild/RaspberryMatic/build-raspmatic_rpi3/build/host-libffi-3.3-rc0/.stamp_configured] Error 1
make[2]: Leaving directory `/rmbuild/RaspberryMatic/buildroot-2019.11'
make[1]: *** [build] Error 2
make[1]: Leaving directory `/rmbuild/RaspberryMatic'
make: *** [raspmatic_rpi3] Error 2
```
Den build starte ich mit `make raspmatic_rpi3`.
Ich verwende für den Build jeweils den Master von RaspberryMatic und rm-build-env. Docker wird auf Windows ausgeführt. 

Danke!

**Comment by jens-maus** [comment]
Geht denn das bauen ohne dockercontainer environment?

@mdzio Kannst du hier helfen?

**Comment by Hoytron** [comment]
Das native bauen ohne Container habe ich noch nicht getestet, da ich auf meinem PC nicht alle Buildtools installieren wollte. 

Ich finde die Containerlösung eigentlich sehr elegant. 
Werde das aber mal testen, sobald ich wieder Zeit dafür habe.

**Comment by mdzio** [comment]
Ich habe es soeben getestet: Der aktuelle Stand (Commit 080234c) lässt sich ohne Probleme im Docker-Container (v1.0.0) bauen.

**Comment by jens-maus** [comment]
Ok, Danke @mdzio Dann kannst hoffentlich @Hoytron dabei helfen seine Dockerumgebung repariert zu bekommen bzw den Bedienungsfehlernzubfinden...

**Comment by mdzio** [comment]
@Hoytron Hast Du das Image über `docker pull mdzio/rm-build-env` gezogen oder selber neu vom `Dockerfile` gebaut?

**Comment by Hoytron** [comment]
Danke für eure Hilfe. Ich bin erst jetzt dazu gekommen das ganze nochmal sauber zu testen. Und konnte das Problme lösen.
 
Der Fehler lag darin, dass ich das Verzeichnis /rmbuild des Linux Containers auf ein Verzeichnis meines Windows Dockerhosts gemounted habe und darin dann den build durchführen wollte. 
Die buildumgebung kommt anscheinend mit dem veränderten filesystem (evtl fehlende dateieigenschaften / rechte) nicht klar.

Lösung (für Container auf einem Windwos Dockerhost): 
In einem nicht-gemounteten Verzeichnis den build durchführen und danach die Image Datei oder was außerhalb des Containers benötigt wird, in ein gemountetes Verzeichnis kopieren.
