### ISSUE TITLE
Backup von Version 2.31.25.20180324 läßt sich nicht in Version 3.49.17.20191225 einspielen

### ISSUE THREAD

**Issue by PhilipHanebeck** [jens-maus/RaspberryMatic#759]
Hallo Jens,

ich wollte meine RaspberryMatic endlich mal auf die neueste Version anheben, leider konnte ich das zuvor erstellte Backup nicht in die aktuelle Version einspielen (Fehlermeldung lautete ; Backup fehlerhaft/unvollständig  (z.B. *.apkx Datei fehlt)).
Kannst Du mir hier einen Rat geben was ich tun muss.

Viele Grüße
Philip

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!

**Comment by PhilipHanebeck** [comment]
Sorry, das sehe ich anders, für mich ist das ein Bug.

**Comment by libertyx82** [comment]
Kein Bug und googlen hilft

https://homematic-forum.de/forum/viewtopic.php?t=45696

**Comment by PhilipHanebeck** [comment]
super, danke für den Hinweis, schaue ich mir gleich mal an.
