### ISSUE TITLE
erhebliche Probleme seit letztem Update

### ISSUE THREAD

**Issue by honk0504** [jens-maus/RaspberryMatic#760]
Hallo zusammen,

ich habe seit ca 4 Tagen erhebliche Probleme mit meinem RaspberryMatic. Ich kann leider nicht genauer sagen seit wann ...
Die Kommunikation zu diversen Aktoren (HM _nicht_ IP und auch _nicht_ wired) ist gestört und löst sich auch nicht mehr aus. Nach diversen Neustarts kommt erst die Meldung, dass es wohl ein Problem mit dem Netzteil gibt (undervoltage), was eigentlich nicht sein kann, aber die lässt sich quitieren. Danach fallen immer mehr Kompontenen, bzw. die Kommunikation zu selbigen, aus. Binnen 30 Minuten sind 8 Stück nicht mehr erreichbar (Raumregler, Dimmer, Rollladensteller, ...).
Ich führe es auf das letzte Update zurück (RaspberryMatic 3.49.17.20191225), da vorher alles anstandslos funktioniert hat.
Jemand eine Idee/gleiche Erfahrung und Lösung?

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!
