### ISSUE TITLE
device firmware update not displayed

### ISSUE THREAD

**Issue by handy80** [jens-maus/RaspberryMatic#761]
**Describe the bug**

**To Reproduce**
1. Go to 'Einstellungen -> Geräte-Firmware-Übersicht
2. See missing Firmware Update for Device HM-LC-Sw1PBU-FM (SN LEQ0762516) (attached three screenshots one from eq3 homepage and one from my RaspberryMatic (and one showing that I run the latest version)
2.a current FW is 2.3
2.b available FW is 2.8.2

**Expected behavior**
I would expect that firmware device updates are consistently shown in RaspberryMatic as on the eq3 support website.
I also would like to mention that for other devices it works. like for HM-CC-RT-DN (Heizkörperthermostat)
I was also able to earlier update the firmware of the same model HM-LCSw1PBU-FM in RaspberryMatic with SN NEC0273114

If the behaviour is to be expected then the rules which firmware-update will be displayed for which hardware device (revision/sn-range) should be made visible to the user of the webUI.

Plus there is also an inconsistency in the former mentioned HM-CC-RT-DN devices. RaspberryMatic is showing highest Version 1.5.1 whereas eq3 homepage is displaying 1.4 only. 1.5.1 is working for me at least on 5 devices from different charges. 

**Screenshots**
![image](https://user-images.githubusercontent.com/16490823/72252217-31672f80-35ff-11ea-9b24-9c08b5c20695.png)
![image](https://user-images.githubusercontent.com/16490823/72252314-5cea1a00-35ff-11ea-992d-6a1aa20e60a5.png)
![image](https://user-images.githubusercontent.com/16490823/72252474-991d7a80-35ff-11ea-811b-e0c37a83ecee.png)

**System information (please complete the following information):**
 - Version RaspberryMatic 3.49.17.20191225
 - Hardware RaspberryPi4

**Additional context**

**Comment by jens-maus** [comment]
I am sorry, but currently, eQ3 is in charge which firmware update is announced in the WebUI and which not based on their own firmware update database on eQ3 servers. And RaspberryMatic is just using/querying this database. Thus, it would be best if you could forward your request/question directly to eQ3 instead.

**Comment by handy80** [comment]
done! answer was:

> Zukünftig werden alle Geräte über die CCU oder RaspberryMatic Oberfläche zu beziehen sein. Sollte eine Firmware oder ein Geräteupdate bereit stehen, wird dieses auf der WebUI mitgeteilt.
Die Geräteupdates für HomeMatic wie auch Homematic IP Geräte einschließlich der Firmwares für die CCU werden nicht mehr weiter auf die Homepage eingestellt.

**Comment by handy80** [comment]
fine. it's going to be more close (apple-like) think I will not buy more devices. thanks eq3

**Comment by HMside** [comment]
@handy80

Why do you think eQ-3 is probably closing more? You can download all the firmware versions offered directly via the WebUI or the following link.

Example HmIP-KRCA (replace device short term in the link): https://update.homematic.com:8443/firmware/download?cmd=download&product=HmIP-KRCA&serial=0

**Comment by ProfDrYoMan** [comment]
Same for me, and another guy.
See here: https://homematic-forum.de/forum/viewtopic.php?f=65&t=58953

RPM: 3.51.6.20200420

**Comment by jens-maus** [comment]
@ProfDrYoMan This is not an RaspberryMatic issue but an issue of the firmware file itself. So please provide the link to the firmware file in question so that we can analyze it and identify a potential workaround.

**Comment by ProfDrYoMan** [comment]
@jens-maus 
I already investigated with EQ3: This is one email answer:

"Soeben haben wir das Updatefile erfolgreich auf eine bestehende CCU3 aufspielen können. Die Firmwaredatei können wir somit als Fehlerquelle ausschließen."

2-fach Taster HMIP-WRC2 in Version 1.4.2. Soll auf 1.10.0.

**Comment by ProfDrYoMan** [comment]
http://ccu3-update.homematic.com/firmware/download?cmd=download&amp;serial=0&amp;product=HMIP-WRC2

**Comment by ProfDrYoMan** [comment]
`<td align="center" class="UILink" onclick="window.location.href='http://ccu3-update.homematic.com/firmware/download?cmd=download&amp;serial=0&amp;product=HMIP-WRC2'">1.10.0</td>`

Wie man daraus den richtigen Link baut, weiß ich nicht.

**Comment by jens-maus** [comment]
@ProfDrYoMan Tschuldigung. Aber ich kann bei der Firmwaredatei auch kein Fehler entdecken. Ich konnte die 1.10.0 für den HMIP-WRC3 problemlos hochladen. Siehe:

<img width="1082" alt="Bildschirmfoto 2020-06-05 um 21 09 36" src="https://user-images.githubusercontent.com/5887769/83914159-f8c42000-a770-11ea-84a8-283b1d5a08fc.png">

Also bitte mal den Fehler konkret zeigen und auch mal eine md5 Checksumme der runtergeladenen Datei erstellen lassen. Bei mir hat die runtergeladene `*.tgz` Datei die md5 Summe:

```
MD5 (HmIP-WRC2_update_V1_10_0_200226.tgz) = a8301af9894673b07eb1bb15ebe5f458
```

**Comment by ProfDrYoMan** [comment]
Ich habe nie gesagt das dies nicht geht. Der nächste Schritt geht nicht. 

![CB70346E-B0F1-41A1-B579-C5ACF6E8BFF6](https://user-images.githubusercontent.com/510353/83920480-9709b300-a77c-11ea-90a8-4022b3a944bf.jpeg)

MD5 schaue ich morgen. Aber ich habe die Datei mehr als einmal herunter und hochgeladen.

**Comment by jens-maus** [comment]
@ProfDrYoMan eQ3 hat es so aber anscheinend auch verstanden. Aber gut, warum die Firmware nicht als "verfügbar" angezeigt wird kann ich leider nicht sagen und folglich auch nicht debuggen, da ich selbst kein HmIP-WRC2 besitze.

**Comment by ProfDrYoMan** [comment]
Ich hab den Hash getestet. Gleich wie bei Dir.

**Comment by jens-maus** [comment]
@ProfDrYoMan Ja, dachte ich mir. Problem wird also irgendwo weiter hinten sein und weil ich selnst keinen HmIP-WRC2 habe kann ich das folglich auch nicht testen/fixen. Bleibt dir nur dich nochmal an eQ3 zu wenden und eindeutig darauf hinzuweisen das das problem nicht beim upload der firmware besteht, sondern die firmware nicht als HmIP-WRC2 firmware im system erkannt wird wenn es HmIP-WRC2 existiert. Da muss also an irgendeiner stelle etwas falsch sein das er die Firmware nicht einem existierenden HmIP-WRC2 zuordnet und daher auch diese nicht an das Gerät überträgt.

**Comment by ProfDrYoMan** [comment]
Genau das habe ich getan. Der Hinweis, dass die FW nicht erkannt wird. 

Aber das war spät am Freitag. Ich denke Antwort kommt am Montag.

Ich habe auch explizit gefragt ob sie ein Update versucht und durchgeführt haben. Mit aktuellem CCU3 System.

**Comment by Pezi1978** [comment]
@ProfDrYoMan ist das Gerät von wesmartify? Habe das selbe Problem. 
Gibtvesceine Lösung?

Grüße

**Comment by ProfDrYoMan** [comment]
Ja. Wesmartify. Keine Lösung. Keine Antwort vom Wesmartify Support.

**Comment by Pezi1978** [comment]
Na Klasse. Dann werde ich da nichts mehr kaufen. Wobei andere Geräte von denen saubere Updates gemacht haben.

**Comment by ProfDrYoMan** [comment]
Schreib dem Wesmartify support. Ebenso wie EQ3. Vllt. bewegt sich was, wenn mehr Leute agieren.

**Comment by Pezi1978** [comment]
Wesmartify fühlt sich nicht zuständig, da sie keine CCU vertreiben.
HaHa...

EQ3 keine Antwort!

Grüße
