### ISSUE TITLE
Alarmmeldung bei fehlendem/verlorenem Funkmodul

### ISSUE THREAD

**Issue by pacco81** [jens-maus/RaspberryMatic#765]
Hallo zusammen !

Ich nutze die 3.49.17.20191225 sowohl als VM aus Synology als auch auf Raspi-Hardware.
Insb. bei der Nutzung der VM kommt es schonmal vor, dass das abgesetzte USB-Funkmodul nicht angeschlossen ist, beim Frickeln am Schrank rausgefriemelt wird oder in der VM nicht korrekt zugeordnet ist.

**IST-Zustand**
Wenn die RM hochfährt und kein Funkmodul angeschlossen ist, erscheint keine Servicemeldung und keine Alarmmeldung. 

**Wunsch-Zustand**
Wenn die RM kein Funkmodul findet wird eine Alarmmeldung ausgelöst.

Leider kann ich mangels Programmier/Linux-Kenntnisse nichts außer die Idee beisteuern.

Besten Dank und Gruß,
Sebastian

**Comment by jens-maus** [comment]
Tut mir leid. Aber es ist gewollt das man RaspberryMatic auch vollkommen ohne Funkmodul betrieben kann. Es ist also alles so wie gedacht.

**Comment by HMside** [comment]
Die Meldung kannst Du dir doch selber bauen. Schick Dir einfach eine Push oder Mail, wenn die DutyCycle Variable auf -1 geht. Ich denke, das dies immer noch so, wie in meiner ursprünglichen Version des DC-Scripts welches in RaspberryMatic eingeflossen ist funktioniert.

**Comment by pacco81** [comment]
Hi HMside !
Danke für den Tip. 
Klappt mit der internen DC_Sysvar von RM leider nicht.
Wenn ich im Synology VMM die RM 3.49.17.20191225 hochfahre ohne zugewiesenen USB-Funkmodul zeigt die Sysvar: 1%

Welches der vielen Skripte die im Umlauf sind, sollte denn -1 anzeigen ?
<img width="1014" alt="Bildschirmfoto 2020-01-24 um 13 26 48" src="https://user-images.githubusercontent.com/29131107/73069112-305eb980-3ead-11ea-9798-10d678d1c232.png">

**Comment by HMside** [comment]
Das in RM implementierte, aber wenn ich mich recht erinnere ging das nur für die LAN-Gateways. Zudem hat Jens das Script einmal komplett neu geschrieben und optimiert.

@jens-maus
Könnte man das nicht eventuell für alle Funk-Module so umsetzen?

**Comment by pacco81** [comment]
Ich habe jetzt ein skript von hier: [https://homematic-forum.de/forum/viewtopic.php?t=35097](url) in der letzten Zeile geändert, so dass meine eigene DC sysvar auf -1 geht, wenn das skript den DC mangels Funkmodul nicht lesen kann.

Wäre schön, wenn das RM interne Skript sich ähnlich verhält und eine eindeutige Zahl (z.B. -1) in die interne sysvar schreibt um zu signalisieren, dass der DC mangels Funkmodul nicht ausgelesen werden kann.


`! DutyCycle mit HM Script und CUxD.exec für Fehlerprotokoll und optional Systemvariable
! v 1.0 by Alchy 
!mod: falls kein DC gelesen werden kann wird sysvar -1 gesetzt
dom.GetObject("CUxD.CUX2801001:1.CMD_SETS").State('echo "load tclrpc.so; puts [xmlrpc ' # interfaces.Get("BidCos-RF").InterfaceUrl() # ' listBidcosInterfaces ]" |tclsh |grep -o "DUTY_CYCLE.[0-9]*."');
dom.GetObject("CUxD.CUX2801001:1.CMD_QUERY_RET").State(1);
if (!dom.GetObject("CUxD.CUX2801001:1.CMD_RETS").State() == ""){
dom.GetObject("CUxD.CUX2801001:1.SYSLOG").State("[DutyCycle "#(dom.GetObject("CUxD.CUX2801001:1.CMD_RETS").State().StrValueByIndex(" ",1))#"] a DutyCycle mit HM Script und CUxD.exec v 1.0 by Alchy");
if (dom.GetObject(ID_SYSTEM_VARIABLES).Get("DC")){dom.GetObject(ID_SYSTEM_VARIABLES).Get("DC").State((dom.GetObject("CUxD.CUX2801001:1.CMD_RETS").State().StrValueByIndex(" ",1)).ToFloat());} 
WriteLine((dom.GetObject("CUxD.CUX2801001:1.CMD_RETS").State().StrValueByIndex(" ",1)).ToFloat()); }else{dom.GetObject(ID_SYSTEM_VARIABLES).Get("DC").State(-1);} `

**Comment by pacco81** [comment]
RaspberryMatic Version (3.49.17.20200131): Änderung des /bin/updateDCVars.tcl Skriptes um im Falle das kein Funkmodul installiert ist die DutyCycle Systemvariable auf -1 zu setzen.

@jens
Besten Dank für die Umsetzung dieser Funktion ! Das erleichtert die Überwachung von einem USB-abgesetzen Funkmodul.
