### ISSUE TITLE
RaspberryMatic-3.49.17.20200131-rpi3.zip

### ISSUE THREAD

**Issue by friedpa** [jens-maus/RaspberryMatic#766]
Hallo Jens,
habe mir die letzte RM SW RaspberryMatic-3.49.17.20200131-rpi3 (1).zip für den RPi3 heruntergeladen und bekomme beim Installieren:

![image](https://user-images.githubusercontent.com/42890695/73595208-1d379380-4516-11ea-8486-531bc635dbf1.png)

Liebe Grüße
Paul

**Comment by alexkoester** [comment]
Gleicher Fehler bei mir auch. 

OVA auf Proxmox.

**Comment by jens-maus** [comment]
Das kann kein genereller Fehler sein denn hunderte andere haben bereits rpi3 und ova updates durchgeführt. Also entweder sind eure zip archive nach dem download defekt oder der browser pakt sie fälschlicherweise selbst aus oder ihr habt unter /usr/local nicht genügend freien Speicherplatz mehr (>= 2GB sollten schon frei sein!)

**Comment by alexkoester** [comment]
Perfekt, das war es :) Mehr Speicherplatz freigegeben, läuft 😁👍

**Comment by jens-maus** [comment]
Dann mal nicht so geizen mit dem virtuellen Speicherplatz unter proxmox!

**Comment by friedpa** [comment]
deto, thanks for the hint!
