### ISSUE TITLE
 2.27.7.20170316 - No IP given to device

### ISSUE THREAD

**Issue by uniquoo** [jens-maus/RaspberryMatic#77]
Heya,

i've setup everything accordingly. Once my device boots up, it doesnt get any ip attached for whatever reason. My DHCP hands out the ipv4 and ipv6 just fine, the RPi just does not see it for reasons not known.

Attached is a screenshot.
![img_20170321_214218](https://cloud.githubusercontent.com/assets/970999/24169994/9d9d481a-0e7f-11e7-97fd-af192bdb02a1.jpg)

**Comment by jens-maus** [comment]
@uniquoo If RaspberryMatic would get a valid IP address from your DHCP it should show this in the line starting with `Starting network: ` but there I can only see that it outputs "OK" which is somewhat awkward. And if you want to login on the HDMI console you have to use "root" as username. The you can use `ifconfig` and `dmesg` to analyse why you don't receive any IP address.

**Comment by uniquoo** [comment]
Tested, nothing spectecular in there. Here is my login-screen which shows that there is no ip attached. Any further ideas?
![img_20170321_220937](https://cloud.githubusercontent.com/assets/970999/24171048/3ceb5daa-0e83-11e7-8f1e-d3e12213ad31.jpg)

**Comment by uniquoo** [comment]
Okay this can be closed. Bug found, my wife get me rid of the network cable while walking around in my dev-room [..].
