### ISSUE TITLE
Add information for backup process

### ISSUE THREAD

**Issue by HolgerJeromin** [jens-maus/RaspberryMatic#771]
**Is your feature request related to a problem? Please describe.**
Downloading a backup says in german:
"Das System-Backup wird jetzt erstellt. Dieser Vorgang kann einige Minuten dauern."
Below we have an OK button. I am always confused if I should press OK, or just wait.

**Describe the solution you'd like**
Add to the text:
"Das System-Backup wird jetzt erstellt. Dieser Vorgang kann einige Minuten dauern. Bitte warten. Der Download startet automatisch."

I would have made an PR, but have no idea where to change the strings:
https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0019-WebUI-EqualThanCondition/occu/WebUI/www/webui/js/lang/de/translate.lang.js#L535
or
https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0001-RaspberryMatic/occu/WebUI/www/webui/js/lang/de/translate.lang.js.orig#L540

**Comment by HolgerJeromin** [comment]
I am really ready to help here with this small improvement.

**Comment by jens-maus** [comment]
Then go ahead and add a new WebUI patch which modifies these strings to your likings and then submit it as a PR so that I can review your proposal and potentially integrate it.

**Comment by HolgerJeromin** [comment]
I wrote in the first comment that I have no idea which is the correct place:
> I would have made an PR, but have no idea where to change the strings

**Comment by jens-maus** [comment]
The correct place would be to submit a PR with a patch against the WebUI/OCCU sources. See here for the directory where we collect hundreds of patches against WebUI/OCCU which change different aspects in the WebUI:

https://github.com/jens-maus/RaspberryMatic/tree/master/buildroot-external/patches/occu

All you have to do is, fork this repository, create a dedicated branch and then add a similar WebUI patch in this directory and then execute `create_patches.sh` to generate the `*.patch` file automatically. And if this works and the patch looks reasonable feel free to submit your branch as a PR here on GitHub.
