### ISSUE TITLE
rgnd-Meldungen

### ISSUE THREAD

**Issue by garosp** [jens-maus/RaspberryMatic#772]
Hallo,
seit dem letzten Release habe ich eine Menge LOG-Einträge von rgnd.
Beispiel :
<31>Feb  8 05:47:20 rngd: Added 3143/4096 bits entropy
<31>Feb  8 05:47:20 rngd: Added 3232/4096 bits entropy
<31>Feb  8 05:47:20 rngd: Added 3313/4096 bits entropy
<31>Feb  8 05:47:20 rngd: Added 3386/4096 bits entropy
<31>Feb  8 05:47:20 rngd: Added 3453/4096 bits entropy
<31>Feb  8 05:47:20 rngd: Added 3513/4096 bits entropy
<31>Feb  8 05:47:20 rngd: Added 3567/4096 bits entropy
<31>Feb  8 05:47:20 rngd: Added 3617/4096 bits entropy
<31>Feb  8 05:47:20 rngd: Reading entropy from Hardware RNG Device
usw.
alle 20 Minuten
kann man dies unterdrücken ?
Gruß

**Comment by jens-maus** [comment]
In welcher Datei tauchen die auf?!?

**Comment by garosp** [comment]
Habe in der "Zentralenverwaltung->Fehlerprotokoll" einen Syslog-Server eingetragen, der "Nur Fehler" loggen soll. Der Syslog-Server ist eine eigene Node.js-Anwendung die ein Logfile schreibt. Diese Meldungen habe ich seit dem Dezember-Release.

**Comment by garosp** [comment]
Habe den Syslog-Server rausgenommen -> keine Meldungen mehr. Hätte ja sein können, dass die Meldungen einen anderen Ursprung haben.

**Comment by libertyx82** [comment]
Ich nutze auch einen Syslog Server und habe diese Meldungen nicht.

Die Meldung sieht mir auch eher nach Verschlüsselung etc aus.

**Comment by garosp** [comment]
Mein "Syslog-Server" ist eine einfache node-Anwendung, die auf udp port 514 lauscht und alles was ankommt in ein Logfile schreibt. Wahrscheinlich liegt es dann an meiner fehlerhaften Implementierung.

**Comment by jens-maus** [comment]
Diese Meldungen sollten unkritisch sein, werden aber eben vom zufallszahlengenerator erzeugt. Welche RaspberryMatic version setzt du denn ein @garosp denn diese Meldungen sollten eigentlich mit der aktuellen RaspberrryMatic Version nicht mehr auftreten.

**Comment by garosp** [comment]
Ich setze Version 3.49.17.20200131 auf RaspberryPi3 Model B+ und Tinker Board S ein. Ich teste mal ob die Meldungen von beiden Instanzen kommt.

**Comment by garosp** [comment]
Die Meldungen kommen vom Tinker Board, sind die Versionen nicht gleich ?

**Comment by garosp** [comment]
<13>Feb 11 04:52:00 kernel: klogd started: BusyBox v1.31.1 (2020-01-31 17:45:35 CET)
<31>Feb 11 04:52:00 rngd: Added 3148/4096 bits entropy
............

**Comment by HM-klana** [comment]
Hab ich im normalen Systemprotokoll (nur Fehler eingestellt) ebenfalls.
Die Übersicht leidet doch sehr unter dieser Menge von Meldungen....

`Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3013/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3114/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3206/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3290/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3365/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3433/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3495/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3552/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3603/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3649/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3691/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3728/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3763/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3794/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3822/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3848/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3871/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3892/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3911/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3928/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3944/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3958/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3971/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3982/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 3993/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 4002/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 4011/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Reading entropy from JITTER Entropy generator
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: xread_jitter requests 2500 bytes from pipe
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: xread_jitter gets 2500 bytes
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 4019/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 4026/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Added 4033/4096 bits entropy
Feb 19 02:55:00 homematic-raspi daemon.debug rngd: Pool full at 4096, sleeping!`

**Comment by psytester** [comment]
rgnd ist dafür bekannt das System mit Logeinträgen unnötig zu füllen.
Das es auch noch im debug Level passiert und man es nicht einstellen kann, ist besonders unschön.
Es gibt 3 Ansätze:
1. Damit leben. Ist aber nicht das gewünschte.

2. Mit einer rsyslog Config die Einträge in eine eigene Datei umleiten, um syslog sauber zu halten. Siehe 
https://www.raspberrypi.org/forums/viewtopic.php?t=247510#p1549237

3. Wechsel von rngd auf haveged als random Generator.
Dann kann auch das loglevel eingestellt werden.
https://www.raspberrypi.org/forums/viewtopic.php?t=247510#p1511771
Oder auch hier
https://forum-raspberrypi.de/forum/thread/43025-rngd-flutet-die-logs/?postID=379066#post379066

**Comment by garosp** [comment]
Danke für Eure Hinweise - ich denke nur an Reduktion der Schreibvorgänge auf die SD-Karte - vielleicht ist aber auch die Menge der I/O's unkritisch wenn auch unnütz

**Comment by jens-maus** [comment]
Da gibt es keinerlei schreibvorgänge auf die SD Karte wegen dieser rngd meldungen. /var/log liegt komplett im RAM also ist das alles unkritisch!
