### ISSUE TITLE
Erstellen von virtuellen Taster unter Raspberrymatic auf CCU3, zum teil nicht möglich.

### ISSUE THREAD

**Issue by svenruprecht** [jens-maus/RaspberryMatic#774]
seit Aktualisierung auf die aktuelle Version kann ich keine virtuellen Taster auf der CCU3 mehr erstellen.
Auch wenn ich den HM-PB-2-WM55-2
![Erfolg - HmIP-WTH-2 und HmIPW-FAL230-C6 Direktverknüpfung](https://user-images.githubusercontent.com/60965601/74327097-da828080-4d8b-11ea-9f00-16fffd41b4bf.png)
![Fehler - HM-PB-2-WM55-2 Direktverknüpfung](https://user-images.githubusercontent.com/60965601/74327099-dbb3ad80-4d8b-11ea-84ba-1158235a2238.png)
![Fehler -virtuelle Taster Direktverknüpfung](https://user-images.githubusercontent.com/60965601/74327100-dc4c4400-4d8b-11ea-960f-e70dcf2b23cd.png)

 auswähle, bleibt die Liste der Verknüpfungspartner, leer.

Meine Hardware ist:

CCU3 mit Raspberrymatic 3.49.17.20200131
HmIPW-DRAP
Mix zwischen HM, HMIP und HMIP Wired.

Screenshot anhängend. 

Bitte um Hilfe.

Vielen Dank und DANKE für die tolle Entwicklung und entsprechenden Entwicklungsarbeiten.

**Comment by jens-maus** [comment]
Wurde unter "Systemsteuerung -> Benutzerverwaltug -> Benutzer" auch der "Modus vereinfachte Verknüpfungskonfiguration aktivieren" entsprechend deaktiviert?

**Comment by svenruprecht** [comment]
Hallo Jens,

ja der Haken ist raus. Siehe Screenshot.

VG
Sven

Von: Jens Maus <notifications@github.com>
Gesendet: Montag, 24. Februar 2020 09:40
An: jens-maus/RaspberryMatic <RaspberryMatic@noreply.github.com>
Cc: Sven Ruprecht <info@network2000.eu>; Author <author@noreply.github.com>
Betreff: Re: [jens-maus/RaspberryMatic] Erstellen von virtuellen Taster unter Raspberrymatic auf CCU3, zum teil nicht möglich. (#774)


Wurde unter "Systemsteuerung -> Benutzerverwaltug -> Benutzer" auch der "Modus vereinfachte Verknüpfungskonfiguration aktivieren" entsprechend deaktiviert?

**Comment by jens-maus** [comment]
Bitte die GitHub Webseiten nutzen für das Reply und nicht im Email Client ein reply mit attachment machen. Das kommt so im entsprechenden Ticket sonst nicht korrekt an.

**Comment by svenruprecht** [comment]
![benutzerverwaltung](https://user-images.githubusercontent.com/60965601/75143696-d2b0cd80-56f5-11ea-9ff1-532a96a5d1a3.PNG)

**Comment by svenruprecht** [comment]
Ja der Haken ist raus. 

Sorry, ist Gewohnheit, auf Email zu antworten :-D

**Comment by jens-maus** [comment]
Dann fällt mir leider kein weiterer Grund ein. Hast du mal auf der originalen CCU3 Firmware versucht das verhalten zu bestätigen?!? Ich kann hier nämlich problemlos Direktverknüpfungen mit den virtuellen Tastern erstellen.

**Comment by svenruprecht** [comment]
Nein, das habe ich nicht, denn ich kann nicht zurück auf die Originale CCU3 Firmware. ich hatte dies mal versucht, dabei habe ich mir das System, also die CCU3, komplett abgeschossen. Die Struktur von RaspberryMatic ist eine andere wie die CCU3 Firmware. Ich musste dann mit der RM Firmware wieder herstellen, so dass ich die CCU3 wieder nutzen konnte.

**Comment by tobsi57** [comment]
Gibt's hierzu schon neue Infos? Habe dasselbe Problem das ich vom Wechsel der Ccu2 auf Raspberrymatic keine Direktverknüpfung herstellen kann. Es sind angeblich keine Verknüpfungspartner vorhanden!

**Comment by widmann-it** [comment]
Ich hatte das gleiche Problem. In meinem Fall war der Auslöser ein Aktor der aus der CCU entfernt wurde - leider wurden die Verknüpfungen nicht mit gelöscht. Wenn ich mich recht erinnere dürfen Geräte nur gelöscht werden wenn alle Direktverknüpfungen oder Programme vorher gelöscht wurden ?

**Comment by jens-maus** [comment]
Existiert das Problem noch mit der aktuellsten RaspberryMatic Version? Kann es noch nachgestellt werden?
