### ISSUE TITLE
Geräte Firmware Update nicht möglich

### ISSUE THREAD

**Issue by drohne200** [jens-maus/RaspberryMatic#775]
**Describe the bug**
Ich habe immer Statusprobleme mit meinem HmIP-BSM - Lösung soll ein Gerätefirmware Update von 1.10.12 auf 1.12.6 bringen. Im Change Log werden meine Fehler auch beschrieben und behoben. Ich habe die Firmware unter Einstellungen -> Geräte Firmware hochgeladen. 
Auf der Startseite bekomme ich auch den Hinweis:

![image](https://user-images.githubusercontent.com/5902229/74378156-b3f13380-4de5-11ea-955a-56b68148d52e.png)

Aber unter Einstellungen -> Geräte Firmware kann ich nicht auf Update klicken?!

![image](https://user-images.githubusercontent.com/5902229/74378291-fb77bf80-4de5-11ea-9126-44033d6528b3.png)

Wo ist der Fehler? 

Danke Marcel

**Comment by HMside** [comment]
Die HmIP Updates werden im Hintergrund automatisch an das Gerät übertragen, dies kann 1 bis 2 Tage dauern. Anschließend kannst Du das Update unter Einstellungen > Geräte-Firmware-Übersicht final abschließen.

**Comment by drohne200** [comment]
Einfach warten ;-)

**Comment by friedpa** [comment]
Ich habe das selbe Problem, warten nützt leider gar nichts, es rennt nur der DC von der RM gegen 100% Seit dem Dezember Update ist die RM leider mit allen meinen HMIP Geräten auf Kriegsfuß. Die Lichtschalter schalten, wenn überhaupt nur verzögert, die Schaltsteckdosen lassen sich nicht mehr konfigurieren und hängen ständig im _Geräte Kommunikation Gestört_ Mode, Senden aber Ihren Status.... Alles sehr unerfreulich ...... 
Der AskSinAnalyser meldet auch immer:
![image](https://user-images.githubusercontent.com/42890695/75009570-501cd980-547b-11ea-9215-8291c9a035d6.png)
Habe dieses Verhalten schon mehrfach gemeldet, werde aber immer aufs Forum verwiesen.....

**Comment by friedpa** [comment]
Nachtrag: Das passiert wenn man den HMIP-SMI versucht auf die letzte Version 1.4.8 zu bringen:

![image](https://user-images.githubusercontent.com/42890695/75014231-1ac9b900-5486-11ea-9a47-8de6eef98331.png)
Schlussendlich gehen alle Devices Offline.

Der HMIP-SMI geht auf unreach, das Ganze läßt sich nur beheben, wenn man das Update dann nach 12 Stunden abbricht (da man ja die Geräte, wie Rollos ja steuern möchte/muss)  und die RM neu startet.

![image](https://user-images.githubusercontent.com/42890695/75014449-9461a700-5486-11ea-90e1-501e603c16c1.png)
