### ISSUE TITLE
Wireguard VPN

### ISSUE THREAD

**Issue by renne** [jens-maus/RaspberryMatic#776]
**Is your feature request related to a problem? Please describe.**
A lot of routers (e.g. Telekom Speedport Smart 3, Unitymedia ConnectBox) do not provide a VPN tunnel option. Setting up a VPN tunnel for e.g. a Smartphone needs additional devices and is quite complicated for John Does.

Viele Router (z.B. Telekom Speedport Smart 3, Unitymedia ConnectBox) haben keine VPN-Funktion.  Für einen VPN-Tunnel (z.B. für Smartphones) wird ein extra Gerät benötigt und das Aufsetzen ist für Normalnutzer kompliziert.

**Describe the solution you'd like**
[Wireguard VPN](https://www.wireguard.com/) is a simple to set up VPN solution with clients/apps for Linux, Windows, MacOS, Android, iOS, etc. The modern encryption algorithms offer about 10 times the throughput of OpenVPN or IPSec on the same hardware. It needs only one UDP port and can handle IP address changes transparently without loss of connection. It also supports tunneling IPv6 in IPv4 and vice versa.

[Wireguard VPN](https://www.wireguard.com/) ist eine einfach aufzusetzende VPN-Lösung mit Clients/Apps für Linux, Windows, MacOS, Android, iOS, etc. Die modernen Verschlüsselungsalgorithmen bieten den zehnfachen Durchsatz gegenüber OpenVPN oder IPSec auf derselben Hardware. Es benötigt nur einen UDP-Port und kann IP-Addresswechsel transparent ohne Verbindungsverlust handhaben. Wireguard kann IPv6 in IPv4 tunneln und umgekehrt.

**Describe alternatives you've considered**
SSH tunneling, OpenVPN, IPSec, PPTP, L2TP

**Additional context**
The Wireguard kernel module needs to be compiled for the Linux kernel. Beginning with [Linux kernel 5.6](https://www.heise.de/ct/artikel/Highlights-von-Linux-5-6-Wireguard-und-USB4-Support-4655269.html) it will be part of the mainstream kernel.

Das Wireguard Kernelmodul muss für den Linux-Kernel kompiliert werden. Ab [Linux kernel 5.6](https://www.heise.de/ct/artikel/Highlights-von-Linux-5-6-Wireguard-und-USB4-Support-4655269.html) wird es Bestandteil des Mainstream-Kernels sein.

**Comment by Baxxy13** [comment]
Wireguard Unterstützung direkt in RaspberryMatic fände ich super. Dann könnte mein 2. Raspi der momentan den WG-Server/Client stellt, wegrationalisiert werden.

**Comment by djtfmineijizm** [comment]
der Speedport Smart 3 unterstützt das inzwischen:
https://www.telekom.de/hilfe/downloads/firmware-aenderungen-speedport-smart-3-v010137-4-0-001-2.pdf
