### ISSUE TITLE
Gerätesuche im script

### ISSUE THREAD

**Issue by Tariot** [jens-maus/RaspberryMatic#777]
**Is your feature request related to a problem? Please describe.**
In der geräte Liste ist es möglich nach Programmen zu suchen in dem die Geräte genutzt werden. 
Leider geht das nicht mit scripte.

**Describe the solution you'd like**
Wäre es möglich über denn gleichen Knopf auch Programme anzeigen zu lassen die scripte enthalten in dem  die datenpunkte dieses Gerätes verwendet wurden.

**Describe alternatives you've considered**

**Additional context**

**Comment by jens-maus** [comment]
Das ist leider so nicht (einfach) möglich, denn wie genau soll denn herausgefunden werden ob ein Gerät in einem Skript verwendet wird oder nicht?!? Es kann ja der Gerätename oder ISE ID verwendet werden und dann kann das beliebig komplex werden solche Abhängigkeiten überhaupt herauszufinden. Ich sehe daher keine wirklich praktikable möglichkeit solche etwas umzusetzen.
