### ISSUE TITLE
WebUI [Feature Request]: Inaktive/unbedienbare Programme ausgrauen/ghosten –> bessere Übersicht

### ISSUE THREAD

**Issue by Wookbert** [jens-maus/RaspberryMatic#779]
Je mehr Programme man hat, je mehr Programme an denen man noch am „basteln“ ist, desto unübersichtlicher wird die Programmliste.

Eine kleine Verbesserung wäre es, wenn inaktive und/oder nicht bedienbare Programme in der Liste deutlich „ausgegraut“ (aber noch lesbar) dargestellt würden, so wie im nachstehenden Screenshot. Nicht nur wird die Liste der aktiven/bedienbaren Programme überschaubarer, auch werden andersrum inaktive Programme, die evtl. Ursache irgendeines Nichtfunktionierens sind, augenscheinlicher.

![RaspberryMatic inaktiv geghosted](https://user-images.githubusercontent.com/3104762/74486724-e4a49c00-4ebd-11ea-9445-7090450a2232.png)

**Comment by jens-maus** [comment]
Gerne nehme ich PullRequests für solch eine einfache Anpassung an. Ansonsten muss das eben warten bis Zeit dafür da ist.

**Comment by Wookbert** [comment]
War ja auch kein Vorwurf... 🙃

Interessant wäre allerdings mal zu erfahren, wo die Reise mit dem WebUI langfristig hingeht. Zeitgemäß ist das – sowohl vom Optischen, als auch der Usability – ja schon lange nicht mehr. eq-3 kann sich das eigentlich nur erlauben, weil es im Gesamtumfang der Hardware-Komponenten und der Möglichkeit selbst „frickeln“ zu können, nichts vergleichbares gibt.

Sollte bspw. – was _**nicht**_ passieren wird – Apple auf den Trichter kommen, so etwas wie Homematic (mit all seinen Hardware-Komponenten) konsequent zu entwickeln, dann stünde eq-3 ziemlich schnell auf dem Abstellgleis. Homekit ist ja bislang nur eine nette Spielerei.

**Comment by jens-maus** [comment]
Das ist ist kein Diskussionsforum über das Warum/Weshalb etwas so ist wie es ist, sondern ein Bug und Issue Tracker bezogen auf das RaspberryMatic Projekt. Ob und wann eQ3 vielleicht mal eine neue WebUI anbieten wird muss schon eQ3 selbst befragt werden. Das hier ist ein freies/unabhängiges OpenSource Projekt das versucht dinge an der existierenden (O)CCU Firmware von eQ3 zu verbessern. Nicht mehr und nicht weniger. Daher bitte solche Diskussionen im HomeMatic Forum führen und nicht hier in den Bug/Issue Tracker tragen...

**Comment by Wookbert** [comment]
Hätte ja sein können, daß Du da mehr Inneneinsicht hast. Ich weiß von einem der eq-3 Entwickler, dass da mal die nächste Generation des WebUIs intern angestoßen wurde, aber recht schnell wohl wieder auf Eis gelegt wurde. Der Stand ist allerdings auch schon wieder ein paar Jahre alt.

Diskussion zu dem Thema hier an dieser Stelle beendet.
