### ISSUE TITLE
IPv4 / IPv6 Setup bug

### ISSUE THREAD

**Issue by uniquoo** [jens-maus/RaspberryMatic#78]
Okay, networking works but as long as u hand out IPv6-addresses, you can only reach the system over IPv6. Via IPv4 does not reply to ping, neither to any service at all. It only works over IPv6.

**Comment by jens-maus** [comment]
@uniquoo Here it works. So please provide more information before you claim this is a bug.

**Comment by uniquoo** [comment]
It works if ip set manually. It does not work if IPv4 is setup via DHCP. Reason seems to be wrong routes setup by the system itself. 

System puts up a /8 instead of the proper announced /24 of my network.

**Comment by jens-maus** [comment]
@uniquoo As said, here it seem to work. I have also a IPv4/IPv6 environment with IPv4 being supplied by a Fritz!Box DHCP and I don't see any problems. So please elaborate a bit more.

**Comment by jens-maus** [comment]
Any news on this issue?

**Comment by jens-maus** [comment]
Closing since there haven't been any further reports/comments.
