### ISSUE TITLE
Regular increase of DC and problems reaching HM-IP BSM Actors in actual release

### ISSUE THREAD

**Issue by glowfishDE** [jens-maus/RaspberryMatic#780]
Hi,

Problem occured on a system with version 3.49.17.20200131 on a RPI3b+

It turned out, that some of my HM-IP BSM Light switches were not responding after a firmware upgrade from 3.49.17.20191225 to 3.49.17.20200131 Sometimes they reacted but with a massive delay. Most of the times they were not responding at all anymore.

Every now and then there was a sudden 100% duty cycle increase for no sane reason. I had no programs with a loop or something. Also tried to deactivate my 2 programs i had without any improvement.

The dutycycle still increased to 100% every few hours, while i permanently got communication issues with various actors that were working on version 3.49.17.20191225 absolutely fine.

I resoldered my antenna connection and checked my antenna cable and everything. I re-positioned my antenna and raspberry pi which did not help too.

Then i tried a downgrade to 3.49.17.20191225 and tadaaa.. everything works like a charm again.

I have no clue why. I attach a log file of the time period when the problems occured in version 3.49.17.20200131
[homematic-raspi-2020-02-14.log](https://github.com/jens-maus/RaspberryMatic/files/4202601/homematic-raspi-2020-02-14.log)

PS: Please tell me to remove the log in case it contains sensible information. I checked and couldnt see anything problematic in it.

KR
Daniel

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
 - Version [e.g. RaspberryMatic 3.37.8.20180922]
 - Hardware [e.g. RaspberryPi3, TinkerboardS, etc.]

**Additional context**

**Comment by friedpa** [comment]
I have exactly the same issue as described by GlowFishDE.

**Comment by friedpa** [comment]
Das Problem mit den HM-IP devices in der Version 3.49.17.20200131 nehmen soweit überhand, dass ich ständig 100% DC habe. Eine Rückkehr zu 3.49.17.20191225 hat das Problem beseitigt. Gerne stelle ich Log Files oder AskSinAnalyser Files zur Verfügung. Es ist aber mein Produktivsystem somit muss ich genaue Anleitungen bekommen was ich liefern muss um das Problem zu analysieren.

**Comment by jens-maus** [comment]
Tut mir leid. Aber bzgl. 3.49.17.20191225 und 3.49.17.20200131 hat sich definitiv nichts in der DC Behandlung geändert. Auch werden HmIP Geräte komplett im ClosedSource Teil der CCU Firmware (HmIPServer) gemanaged. Auch sind DutyCycle Problem zu >90% auf Nutzerkonfigurationsprobleme bzw. andere Probleme zurückzuführen. Ich sehe also aktuell keinen Weg das in irgendeiner weise technisch lösen/behandeln zu können. Auch betriebe ich selbst mit der  3.49.17.20200131 eine größere Installation mit HmIP Geräten und sehe keine solche DC Probleme.
