### ISSUE TITLE
Label Eingabefeld "Mindestsendeabstand" falsch

### ISSUE THREAD

**Issue by TinkyWonky** [jens-maus/RaspberryMatic#781]
**Describe the bug**
Das Eingabefeld für den Mindestsendeabstand des Geräts HmIP-FSM16 trägt das Label "Wert Zufallsanteil" anstatt z.B. "Wert Mindestsendeabstand".
Wird für den Zufallsanteil ebenfalls "Wert eingeben" gewählt, trägt das Eingabefeld hier korrekterweise das Label "Wert Zufallsanteil".

**To Reproduce**
1. Einstellungen > Gerät > HmIP-FSM16
2. Kanal 5 (Statusmeldung Messwertkanal): Mindestsendeabstand setzen auf "Wert eingeben"
3. Eingabefeld wird eingeblendet, jedoch mit fehlerhaftem Label.

**Expected behavior**
Eingabefeld trägt passendes Label, z.B. "Wert Mindestsendeabstand".

**Screenshots**

**System information (please complete the following information):**
 - RaspberryMatic 3.47.22.20191130
 - RaspberryPi3

**Comment by jens-maus** [comment]
Bitte einen entsprechenden Screenshot des Problem beifügen.

**Comment by TinkyWonky** [comment]
Aber gern!

![Unbenannt](https://user-images.githubusercontent.com/40147250/75145290-f4f81a80-56f8-11ea-901d-4f75341bf124.jpg)
