### ISSUE TITLE
WebUI - Firmware Update wird angezeigt obwohl älter

### ISSUE THREAD

**Issue by wod71** [jens-maus/RaspberryMatic#783]
Hallo,

Es wird im WebUI für ein Homematic IP Gerät ein Firmware-Update angezeigt obwohl bereits eine neuere Version auf dem Gerät vorhanden ist.

![grafik](https://user-images.githubusercontent.com/61112344/74606574-ddee7280-50d1-11ea-90b3-469b43a3e188.png)

![grafik](https://user-images.githubusercontent.com/61112344/74606589-0f673e00-50d2-11ea-9944-af32e2535503.png)

 - RaspberryMatic 3.49.17.20200131
 - Hardware: Raspberry Pi 4

**Comment by jens-maus** [comment]
Das Problem sollte mit der kommenden 3.51.x.XXXXXXX firmware behoben sein.
