### ISSUE TITLE
HmIP-DSD-PCB lässt sich nicht anlernen

### ISSUE THREAD

**Issue by bhuertgen** [jens-maus/RaspberryMatic#784]
**Describe the bug**
automatic / manuell Geräte anlernen
Es wird kein Gerät gefunden,
HmIP-DSD-PCB blinkt nur alle 10 sek.

**Expected behavior**
Show 1 Gerät gefunden

**System information (please complete the following information):**
 - Version [3.49.17.20200131]
 - Hardware [RaspberryPi3]

**Comment by outsider2017** [comment]
kann das ganze bestätigen.

Auch ich habs nicht geschafft, den HmIP-DSD-PCB anzulernen.

Version [3.49.17.20200131]
Hardware [RaspberryPi3]

**Comment by Zippochonda** [comment]
Das ist kein Wunder, denn der HmIP-DSD-PCB wird erst ab Firmware 3.51.6 unterstützt. Die ist von EQ3 am 4. Februar released worden und bisher nicht in Raspberrymatic integriert

**Comment by jens-maus** [comment]
Wie schon geschrieben sollte dieses "Problem" mit der kommenden 3.51.x basierten RaspberryMatic verison behoben sein.

**Comment by bhuertgen** [comment]
Hallo,

 

hat sich erledigt in der aktuellsten Release funktioniert er…

 

MfG

Boris Hürtgen

 

Von: outsider2017 <notifications@github.com> 
Gesendet: Donnerstag, 20. Februar 2020 21:43
An: jens-maus/RaspberryMatic <RaspberryMatic@noreply.github.com>
Cc: bhuertgen <bhuertgen@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [jens-maus/RaspberryMatic] HmIP-DSD-PCB lässt sich nicht anlernen (#784)

 

kann das ganze bestätigen.

Auch ich habs nicht geschafft, den HmIP-DSD-PCB anzulernen.

Version [3.49.17.20200131]
Hardware [RaspberryPi3]
