### ISSUE TITLE
WebUI [Feature Request]: Möchten Sie das Programm wirklich löschen? – Ja, welches denn!?

### ISSUE THREAD

**Issue by Wookbert** [jens-maus/RaspberryMatic#785]
Mir ist gerade aufgefallen, daß im Programm-löschen-Bestätigungs-Dialog der Programmname nicht auftaucht. Aber gerade wenn das WebUI-Fenster besonders breit ist, hat man sich in der Zeile schnell verhauen und löscht irreversibel das falsche Programm.

Einziger Hinweis auf das zu löschende Programm ist momentan die sehr dezente Highlight-Umrandung um den gedrückten Löschen-Button.

Mein Vorschlag wäre die komplette Zeile des zu löschenden Programms gut sichtbar rot einzufärben.

### **Momentan:**

![Delete](https://user-images.githubusercontent.com/3104762/74800252-32147500-52d3-11ea-9a87-6f7c00a2f24d.png)

### **Besser, weil augenscheinlicher:**

![DeleteHighlight](https://user-images.githubusercontent.com/3104762/74800344-73a52000-52d3-11ea-8227-a4d312d34008.png)

**Comment by jens-maus** [comment]
Auch hierfür nehme ich keiner PullRequests an die diese Funktionalität umsetzen. Alternativ könnte man einfach im "Sicherheitsabfrage" Requester ja den Namen des Programmes mit ausgeben um mehr Sicherheit zu haben.
