### ISSUE TITLE
Programme: Trigger bei Türkontakt - offen - bei Änderung auslösen funktioniert nicht

### ISSUE THREAD

**Issue by michl-b** [jens-maus/RaspberryMatic#787]
Die Änderung des Gerätezustandes nach "offen" wird nicht korrekt erkannt und ausgeführt.
Stattdessen wird das gleiche Programm mit Status "geschlossen" sowohl beim öffnen, als auch beim schließen ausgelöst.

Momentan installierte Version: 3.49.17.20200131

Programm siehe Screenshot:
![image](https://user-images.githubusercontent.com/11937795/74965299-4a8ca880-5415-11ea-8ac6-a0d7cc5afe26.png)

**Comment by jens-maus** [comment]
Kann das hier jemand bestätigen?

**Comment by jp112sdl** [comment]
Funktioniert bei mir korrekt mit `HM-Sec-SCo`
