### ISSUE TITLE
Friday evening to be considered as weekend and Sunday evening as working day

### ISSUE THREAD

**Issue by AxelG-DE** [jens-maus/RaspberryMatic#792]
**Is your feature request related to a problem? Please describe.**
I think a vast majority of people start their weekend at Friday afternoon (so they can party Friday night :smile: ) and we have to be fit on blue Monday morning, hence Sunday evening we go to bed earlier, as we do during the week.

The 'time module' window does not provide me that freedom. Even I cannot have a single one day programmed (like every Friday). And if so, it would make me anyhow headaches, because my light control is programmed in a way, that I say 
```
if time 6:00 to 8:00; light = on
else-if time 18-23` ; light =on
else; light = off
```
(in reality more complex as I use dimming ramp up and ramp down times)

**Describe the solution you'd like**
in the time module I would like to see two additional options:
1) the option to chose separately "every Monday/Tuesday/Wednesday..../Sunday" 
2) two checkboxes, which say "consider Friday p.m. as weekend" and "Consider Sunday p.m. as working day"

**Describe alternatives you've considered**
Besides checkboxes in the time-module, it can be an separate operator in the if/then/else boxes

**Comment by Hypnos3** [comment]
I can recommend you to have a look at the RedMatic addon.  This gives you the freedom you want.

**Comment by AxelG-DE** [comment]
@Hypnos3 TNX, I'll have a look

**Comment by AxelG-DE** [comment]
I checked RedMatic, and yes, it seems it can resolve almost every wishes. It will be on my device soon. 
I still hope, above logic will be implemented in RaspberryMatic and atm wouldn't like to close this FR

**Comment by jens-maus** [comment]
Sorry, but I think your request goes far beyond the standard request, especially the  request to consider friday already as a "weekend" day. This really should go to another/external logic engine. And I am happy you found RedMatic. Thus will close this request.

**Comment by AxelG-DE** [comment]
Sorry, I see it exactly opposite. 
Using RedMatic for this rather **simple request** is using **canons for birds**. 

So I must say, I am pretty sad, to see this case gets closed that easily. I cannot imagine, I am the only one, who stays awake longer on Fridays and need to go to work on Mondays.... :-(
