### ISSUE TITLE
Update auf RaspberryMatic 3.51.6.20200229 meldet Error 404

### ISSUE THREAD

**Issue by herbylfs** [jens-maus/RaspberryMatic#793]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
 - Version [e.g. RaspberryMatic 3.37.8.20180922]
 - Hardware [e.g. RaspberryPi3, TinkerboardS, etc.]

**Additional context**

**Comment by jens-maus** [comment]
Bitte das Ticket Template nicht einfach ignorieren sondern ausfüllen! Und screenshot beifügen, etc.!

**Comment by metaneutrons** [comment]
Ich vermute mal, er meint, dass der Link https://github.com/jens-maus/RaspberryMatic/releases/download/3.51.6.20200229/RaspberryMatic-3.51.6.20200229-rpi4.zip einen 404 liefert. :)

**Comment by IT-VBFK** [comment]
Und ich vermute es liegt an diesem Wunsch:
https://homematic-forum.de/forum/viewtopic.php?p=566717#p566717
