### ISSUE TITLE
HM-LC-Ja1PBU-FM -Jalousieaktor - nicht mehr bedienbar seit 3.51.6.20200229

### ISSUE THREAD

**Issue by Jailbraik** [jens-maus/RaspberryMatic#794]
**Describe the bug**
Unter Einstellungen sind die Jalousieaktoren noch vorhanden, aber selbst nach neuanlernen nicht einstellbar. 

**Screenshots**
![Fehler](https://user-images.githubusercontent.com/61645495/75621264-3756a700-5b92-11ea-9c71-fbe8b432b5e3.png)

**Comment by jens-maus** [comment]
Wie sieht das unter der eQ3 eigenen CCU3 Firmware aus? Passiert das dort auch?

**Comment by jp112sdl** [comment]
Die Meldung "Der Kanal kann nicht konfiguriert werden" erscheint, wenn der Aktor nicht live abgefragt werden kann.
Da auch einige Servicemeldungen anstehen, dürfte dort wahrscheinlich auch der HM-LC-Ja1PBU-FM mit "Kommunikationsstörung" aufgeführt sein?

**Comment by roe1974** [comment]
Bug kann ich nicht bestätigen ....
Alle 6 Stk. HM-LC-Ja1PBU-FM bei mir hier lassen sich normal bedienen und sind konfigurierbar.

lg Richard
