### ISSUE TITLE
RPI4B ... deaktiviertes BT in /boot/config.txt ... RM bootet nicht mehr

### ISSUE THREAD

**Issue by roe1974** [jens-maus/RaspberryMatic#796]
Hallo Jens
Wenn in der /boot/config.txt wie beschrieben die beiden Zeilen auskommentiert werden, um Bluetooth zu deaktivieren, bootet die RM nicht mehr (rote led des PI4B leuchtet). Bei einem PI3B funktioniert es normal.

"# for disabling bluetooth alltogether"
"# you can uncomment the following two lines"
"#dtoverlay=pi3-disable-bt"
"#dtparam=uart1=off"

Wenn nur die Zeile "dtoverlay=pi3-disable-bt" auskommentiert wird, bootet der PI4B ganz normal (ich weiss allerdings nicht ob das reicht um BT zu deaktivieren).
Irgend etwas passt beim PI4B mit der Zeile "dtparam=uart1=off" nicht.

lg Richard
PS: Mit dem HM-MOD-RPI-PCB tritt das Phänomen nicht auf, nur mit dem RPI-RF-MOD :(

**Comment by jens-maus** [comment]
Es ist nicht notwendig Bluetooth in der config.txt abzuschalten bei RaspberryMatic. Bluetooth wird automatisch beim hochfahren (wenn keine konfiguration vorliegt) via `rfkill` kommando von RaspberryMatic deaktiviert. Das sollte vollkommen ausreichend sein.
