### ISSUE TITLE
HMIP Server is not working on RASPBERRYMATIC with RPi4

### ISSUE THREAD

**Issue by NOPIEPER1** [jens-maus/RaspberryMatic#799]
**Describe the bug**
After update to 3.51.6.20200229 RaspberryMatic System shows Failure and Restart of HMIP Server.
After that no HMIP device show response. 
After restart same behavior. Also after restart and repeat installation of the Firmware Update same behaviour.

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
 - Version [e.g. RaspberryMatic 3.37.8.20180922]
3.51.6.20200229
 - Hardware [e.g. RaspberryPi3, TinkerboardS, etc.]
Raspberry Pi4

**Additional context**

**Comment by torstenkn** [comment]
I also had significant issues with the version 3.51.6.20200229, but with the RPI3. The Homematic IP device were no longer working, while the legacy Homematic devices worked. Rebooting has not helped, but now after downgrading everything works well again!

**Comment by jens-maus** [comment]
@NOPIEPER1 Please upon bootup of RaspberryMatic on your Pi4, please show the output of the following command:

```
cat /var/hm_mode
```

This should help me investigating the issues.
