### ISSUE TITLE
HMIP-WRC2 nicht bedienbar nach anlernen

### ISSUE THREAD

**Issue by glitchracer** [jens-maus/RaspberryMatic#804]
Hallo,

habe mehrere neue HMIP-WRC2 Wandtaster 2-fach gekauft und angelernt. 
Taster quittiert jegliche Bedienung mit  mit orangner  LED.
Nachdem erfolgreichen anlernen kann man die Taster nicht bedienen.

Folgendes habe ich probiert:

- Werkseinstellungen am Taster direkt durchgeführt
- Werkseinstellungen per Zentrale durchgeführt
- Neustart der Zentral nach Anlernvorgang

Ich habe noch einen bestehenden Wandtaster auch HMIP-WRC2 der tadellos funktioniert.
Dieser wurde vor Firmware RaspberryMatic 3.51.6.20200229 (rpi3) eingebunden.

**Comment by glitchracer** [comment]
Konnte das Problem mittels eines älteren [Beitrags](https://www.symcon.de/forum/threads/33504-Einbinden-eines-HomeMatic-IP-Funk-Wandtaster-HmIP-WRC6) lösen.

Es reicht bereits aus wenn man nachdem anlernen unter
**[Programme und Verknüpfungen ->  Programme & Zentralenverknüpfungen** ] ein neues Programm mit den Kanälen die nicht funktionieren anlegt.

![image](https://user-images.githubusercontent.com/47540049/77078865-76408580-69f7-11ea-8b72-1171e033da78.png)

Danach kann man das Programm direkt wieder löschen und der Taster funktioniert, 
dieses Verhalten konnte ich bei allen vier Tastern reproduzieren.

Im Hintergrund verändert sich die `.dev` Datei die man zu jedem HMIP Gerät unter `/usr/local/etc/config/crRFD/data` sehen kann. 

In der Datei kommt am Ende folgendes hinzu:
`de.eq3.cbcs.devicemanagement.LinkPartne~BFBCFCENTRAL_DEVIC~e.eq3.cbcs.server.core.persistence.PersistentDeviceLinkConfiguration ~BFBCFCENTRAL_DEVIC`

**Comment by kianimo** [comment]
> Konnte das Problem mittels eines älteren [Beitrags](https://www.symcon.de/forum/threads/33504-Einbinden-eines-HomeMatic-IP-Funk-Wandtaster-HmIP-WRC6) lösen.
> 
> Es reicht bereits aus wenn man nachdem anlernen unter
> **[Programme und Verknüpfungen -> Programme & Zentralenverknüpfungen** ] ein neues Programm mit den Kanälen die nicht funktionieren anlegt.
> 
> ![image](https://user-images.githubusercontent.com/47540049/77078865-76408580-69f7-11ea-8b72-1171e033da78.png)
> 
> Danach kann man das Programm direkt wieder löschen und der Taster funktioniert,
> dieses Verhalten konnte ich bei allen vier Tastern reproduzieren.
> 
> Im Hintergrund verändert sich die `.dev` Datei die man zu jedem HMIP Gerät unter `/usr/local/etc/config/crRFD/data` sehen kann.
> 
> In der Datei kommt am Ende folgendes hinzu:
> `de.eq3.cbcs.devicemanagement.LinkPartne~BFBCFCENTRAL_DEVIC~e.eq3.cbcs.server.core.persistence.PersistentDeviceLinkConfiguration ~BFBCFCENTRAL_DEVIC`

Danke fürs Posten des Workarounds, das hat mir den Tag gerettet. Ich hatte das gleiche Problem und stundenlang herum probiert, den Taster ab- und wieder angelernt ohne Erfolg, zwischenzeitlich ging mal eine der beiden Tasten, vermutlich weil ich testhalber ein Programm angelegt hatte. Mit Einrichten des Dummyprogramms geht es nun auch bei mir. Leider ist das nirgends in der Anleitung dokumentiert und auch nicht sonderlich intuitiv, denn eigentlich wollte ich den Taster nur über NodeRed verknüpfen.

**Comment by Sineos** [comment]
https://github.com/rdmtc/RedMatic/wiki/Faq#hmip---tastendruck-erzeugt-keine-events

**Comment by kianimo** [comment]
Ok, in den Redmatic FAQ steht es. Aber in der Bedienungsanleitung zum Gerät nicht. Einfacher wäre es sicher trotzdem, wenn die CCU das ohne den Workaround verarbeiten könnte.
