### ISSUE TITLE
HMIP Geräte lassen sich nicht steuern

### ISSUE THREAD

**Issue by friedpa** [jens-maus/RaspberryMatic#805]
**Describe the bug**
Seit dem letzten Update lassen sich alle meine HMIP Geräte nicht mehr schalten. Der Status der Geräte wird aber übertragen, man kann die Geräte also manuell schalten.
Ich habe schon ziemlich viel probiert, auch Neuinstallation und Backup einspielen, stehe jetzt aber an, da auch ein zurücksteigen auf die vorherige Version nichts mehr bringt (liegt der Fehler vielleicht im Backup?). Man kann auch keine Konfigurationsdaten mehr übertragen. Im Systemlog kommen solche Meldungen:

![grafik](https://user-images.githubusercontent.com/42890695/76795685-1fa23400-67ca-11ea-9d5b-29cf21d9c363.png)

Im RaspberryMatic Log messages steht, wenn ich versuche den HMIP-PS einzuschalten:

![grafik](https://user-images.githubusercontent.com/42890695/76796742-61cc7500-67cc-11ea-923a-754281429b75.png)

Mar 16 21:21:08 homematic-raspi local0.warn ReGaHss: WARNING: XMLRPC 'setValue': rpcClient.isFault() failed (url: xmlrpc://127.0.0.1:32010, params: {"00021A498B49A5:3","STATE",true}, result: [faultCode:-1,faultString:"Generic error (TIMEOUT)"]) [CallXmlrpcMethod():iseXmlRpc.cpp:2608]

Mar 16 21:21:08 homematic-raspi local0.err ReGaHss: ERROR: XMLRPC 'setValue' call failed (interface: 1009, params: {"00021A498B49A5:3","STATE",true}) [CallSetValue():iseXmlRpc.cpp:1505]

Mar 16 21:21:08 homematic-raspi local0.err ReGaHss: ERROR: rpc.CallSetValue failed; address = 00021A498B49A5:3 [WriteValue():iseDOMdpHSS.cpp:76]

**Expected behavior**
HMIP Geräte lassen sich schalten wie vor dem Upgrade

**Screenshots**
wie oben in der Beschreibung

**System information (please complete the following information):**
 - Version: RaspberryMatic 3.51.6.20200229]
 - Hardware: RaspberryPi3

**Additional context**
Ich bitte um Hilfe, wende mich an Euch, da ich nicht weiß, ob das ein Bug, oder ein User Fehler ist.
Vielen Dank!

**Comment by Jemeins** [comment]
Es ist kein User Fehler!
Ich habe ebenfalls diese Probleme. 

- Beispielsweise lässt sich mein Licht meiner HmIP-BDT direkt am Schalter dimmen und der Status wird auch übertragen. 
- Ein Dimmen über das UI führt jedoch immer zu der Servicemeldung "Gerätekommunikation gestört" und das Licht wird nicht gedimmt.

- Version: RaspberryMatic 3.51.6.20200229
- Hardware: RaspberryPi3b

Aus lauter Verzweiflung habe ich meine Zentrale schon komplett frisch eingerichtet, jedoch liegt der Fehler weiterhin vor.

Ich bitte um Hilfe!
Vielen Dank

**Comment by Homa856** [comment]
Ich kann das Problem ebenfalls bestätigen. Ein Manuelles bedienen mit Statusübermittlung ist möglich, dass schalten über die Website funktioniert jedoch nicht mehr.
Ebenfalls: RaspberryMatic 3.51.6.20200229 und ein RaspberryPi3b.

Ich freue mich über jede Hilfe, da mein RM aktuell so nicht mehr nutzbar ist :(

**Comment by dg1kwa** [comment]
Ich kann das nicht bestätigen. Bei mir lassen sich alle HMIP-Geräte
normal steuern. 

3.51.6.20200229 auf einem RPI3b 

Am 2020-03-20 10:42, schrieb Homa856:

> Ich kann das Problem ebenfalls bestätigen. Ein Manuelles bedienen mit Statusübermittlung ist möglich, dass schalten über die Website funktioniert jedoch nicht mehr.
> Ebenfalls: RaspberryMatic 3.51.6.20200229 und ein RaspberryPi3b. 
> 
> Ich freue mich über jede Hilfe, da mein RM aktuell so nicht mehr nutzbar ist :( 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1]
https://github.com/jens-maus/RaspberryMatic/issues/805#issuecomment-601611046
[2]

**Comment by Jemeins** [comment]
Auch Konfigurationsdaten lassen sich nicht übertragen.
Trotz der scheinbar guten Verbindung?

<img width="1251" alt="Bildschirmfoto 2020-03-20 um 10 54 46" src="https://user-images.githubusercontent.com/44979117/77153120-80b35b80-6a99-11ea-8080-3ed489d967c0.png">

**Comment by dg1kwa** [comment]
Habe ich gerade auch mal probiert, läuft ebenfalls fehlerfrei.

Steht was im Log? 

Am 2020-03-20 10:57, schrieb Jemeins:

> Auch Konfigurationsdaten lassen sich nicht übertragen.
> Trotz der scheinbar guten Verbindung? 
> 
> [1] 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].

 

Links:
------
[1]
https://user-images.githubusercontent.com/44979117/77153120-80b35b80-6a99-11ea-8080-3ed489d967c0.png
[2]
https://github.com/jens-maus/RaspberryMatic/issues/805#issuecomment-601616882
[3]

**Comment by Jemeins** [comment]
[homematic-raspi-2020-03-20.log](https://github.com/jens-maus/RaspberryMatic/files/4358905/homematic-raspi-2020-03-20.log)
Ich persönlich kann mit dem Log leider nicht sehr viel anfangen, denke aber das nichts auffällig ist.

**Comment by Jemeins** [comment]
Es scheint keine dauerhafte Störung zu sein, eben ging eine Nachricht durch.
Jedoch ist das Gerät jetzt schon wieder gestört.

**Comment by friedpa** [comment]
Es ist bei mir so, dass von 25 über das WebUI manuell getriggerte Schaltänderungen 1 funktioniert (mehrfach getestet). Im Log steht immer dann das selbe:

Mar 16 21:21:08 homematic-raspi local0.warn ReGaHss: WARNING: XMLRPC 'setValue': rpcClient.isFault() failed (url: xmlrpc://127.0.0.1:32010, params: {"00021A498B49A5:3","STATE",true}, result: [faultCode:-1,faultString:"Generic error (TIMEOUT)"]) [CallXmlrpcMethod():iseXmlRpc.cpp:2608]

Mar 16 21:21:08 homematic-raspi local0.err ReGaHss: ERROR: XMLRPC 'setValue' call failed (interface: 1009, params: {"00021A498B49A5:3","STATE",true}) [CallSetValue():iseXmlRpc.cpp:1505]

Mar 16 21:21:08 homematic-raspi local0.err ReGaHss: ERROR: rpc.CallSetValue failed; address = 00021A498B49A5:3 [WriteValue():iseDOMdpHSS.cpp:76]

**Comment by Jemeins** [comment]
Ich habe noch ein bisschen romprobiert und festgestellt, das das deaktivieren des HDMI ports eine kurze Besserung mit sich bringt. Oder ist das doch nur Zufall, da dieser ja standardmäßig deaktiviert dein sollte? #500 

Als nächstes werde ich noch mal die Batterien von den Funk Geräten tauschen und ein original Netzteil habe ich mir auch bestellt.

Gibt es noch andere Lösungsansätze?

Ich bin für jede Hilfe Dankbar!

**Comment by friedpa** [comment]
Ich habe auch schon so viel probiert, wie z.B. alle Hausgeräte abgesteckt usw. Leider ohne Erfolg, bin wenigstens erleichtert, dass ich nicht alleine vor dem Problem stehe, da es dann gleich wieder heißt, das ist ein Bug Tracker ..... ich gehe nun davon aus, dass es in irgendeinem Teil der RM SW (kann auch im geschlossenen Teil sein) einen Fehler gibt, der durch ein Backup mitgezogen wird. Das einzige was ich noch nicht probiert habe und das werde ich auch nicht tun ... alle Geräte und Programme neu in einer frischen Installation einpflegen.

**Comment by Jemeins** [comment]
Ich habe soeben eine Komplette Neuinstallation der Zentrale vorgenommen (Version 3.49.17.20200131)

Leider bleiben die Verbindungsprobleme bestehen...

Hat jemand Erfahrungen ob es tatsächlich an der Micro-USB Spannungsversorgung liegen kann?
Das original ELV Netzteil ist bereits bestellt.

Mit freundlichen Grüßen

**Comment by friedpa** [comment]
Ich habe seit circa zwei Jahren das selbe Netzgerät und vorher funktionierten die HMIP Geräte, an dem kann es also (bei mir) nicht liegen.

**Comment by Jemeins** [comment]
Das System läuft jetzt doch wieder ohne Probleme auf FW: 3.49.17.20200131

Ich werde erst mal bei der Version bleiben, da ich auf ein stabiles System angewiesen bin.

**Comment by friedpa** [comment]
Irgendwas geändert?

**Comment by Jemeins** [comment]
Nichts geändert, einfach nur abgewartet.
Noch funktioniert es glücklicherweise

**Comment by friedpa** [comment]
Für alle die auf die gleichen Probleme stossen:
Nachdem ich das (geschirmte) Kabel für die abgesetzte Antenne aus meinem Kabelkanal genommen habe funktioierte auf einmal die gesamte Kommunikation mit HMIP Geräten wieder. Dieses Verhalten was reproduzierbar!

**Comment by markusklein01** [comment]
Ich habe dasselbe Problem auch. Keine HMIP Geräte verlässlich gesteuert werden. Die funktionieren nur teilweise. Die HM Funk laufen bestens. Ich habe das aktuelle Release im Einsatz.

**Comment by BlackBeast2020** [comment]
Hallo zusammen, bin im Release 3.51.6.20200420 und habe das gleiche Problem: HMIP Dimmaktor sowie HMIP Schaltsteckdose können zwar angelernt werden, laufen jedoch auf Störung -> Programme werden nicht ausgeführt. Andere HMIP Geräte (Fußbodenheizungsregler) sowie Türsensoren laufen ohne Probleme. 

Hilfe gerne genommen.

**Comment by jens-maus** [comment]
Bitte hier die Diskussion beenden. GitHub ist eine Entwicklugsplatform und das hier ein Bugtracker bzw. Ticket System und kein Diskussionsforum wie homematic-forum. Deshalb bitte dise diskussionen ins homematic-forum verschieben.
