### ISSUE TITLE
Pull of system variables in beta 4 and 5

### ISSUE THREAD

**Issue by clemz1986** [jens-maus/RaspberryMatic#81]
On my raspbi 2 with beta 5 installed "the pull" of system variables is not working
On my raspbi 3 with beta 4 installed "the pull" of system variables is working perfect

I use this raspbi as a satellite for a c-comatic  box of contronics only for the management of 12 system variables. There is on both systems an addon by contronics installed "http://www.contronics.de/download/InstctlcecoRaspMatic.IMG" which is required to connect the raspbi to the c-comatic box. The addon was designed for raspberrymatic by contronics.
 ((4 other raspbi 2 an 3  are steered by the c-comatic box to handle 320 devices (not channels) in a llarge environment working perfect with the same addon AND beta5)) #

**Comment by jens-maus** [comment]
I verstehe leider nicht ganz was genau das Problem sein soll. Bitte also noch einmal auf deutsch das eigentliche Problem beschreiben.

**Comment by clemz1986** [comment]
Vier raspberrymatic Beta5 sind als Peripherie an eine c-comatic Steuerzentrale von Contronics per Ethernet verbunden. Über diese Raspberrymatic werden ohne Probleme 320 Geräte (nicht Kanäle) gesteuert. Der Umstieg von CCU2 zu Raspberrymatic lief unproblematisch von Beta 2 bis Beta 5.

Ein weiterer Raspberrymatic wird ausschließlich in diesem Verbund genutzt, um Systemvariablen zu verwalten (4 Stück), mit vier Programmen: Diese sind ein z.B. eine Systemvariable für den Sonnenstand oder eine Systemvariable für die Alarmierung. Diese vier Systemvariablen werden von der c-comatic Zentrale per dort laufender Programme und Abfragen abgerufen.  

Sowohl mit einem 2er als auch mit eine 3er Raspberry Hardware werden die Systemvariablen korrekt verwaltet und angezeigt. Nun kann weder der 2er noch der 3er Raspberry unter der Beta5  Abfragen der Systemvariablen von der c-comatic Zentrale beantworten: Unter Beta 4 ist das mit beiden Hardwareversionen kein Problem. Auf allen des Raspberrymatic läuft als Addon Software "http://www.contronics.de/download/InstctlcecoRaspMatic.IMG". Diese ist nötig um alle Raspberrymatic an die c-comatic Zentrale anzubinden. Die Software wurde speziell für die Raspberrymatic entwickelt. 
 Danke!

**Comment by jens-maus** [comment]
Danke für die Information, c-comatic kannte ich in der Tat noch gar nicht. Interessant das man damit mehrere vollwertige RaspberryMatic/CCUs koppeln kann.

Das Problem das hier beschrieben wird scheint mir jedoch nicht RaspberryMatic spezifisch zu sein sonder hört sich vielmehr so an das durch die Anpassungen in der 2.27.7 CCU Firmware im Bereich Firewall und Port 8181 proxy Nutzung deshalb keine Verbindungen mehr von c-comatic zu den jeweiligen beta5 RaspberryMatic Versionen aufgebaut werden kann. Dann sollte das Problem in der Tat auch mit CCU2 Geräten mit Firmware 2.27.7 auftreten.

Bei 2.27.7 gilt eben zu beachten das damit gegenüber der 2.15.x zwei essentielle Dinge im Bezug auf externe Netzwerkzugriffe sich geändert haben:

1. Die Firewall ist nun standardmäßig aktiv. D.h. unter Systemsteuerung->Firewall werden die dort eingetragenen Dinge (IP-Range, Einstellung "Eingeschränkter Zugriff") beachtet. Hier sollte mind die IP-Adresse der c-comatic steuerzentrale eingetragen werden oder eben alles auf "Vollzugriff" eingestellt werden damit die Firewall komplett deaktiviert ist.

2. Zugriffe auf den ReGaHss Port 8181 (tcl scripting via http) finden nun nicht mehr direkt statt sondern via eine lighttpd proxy. D.h. wenn man auf eine CCU/RaspberryMatic mit Firmware 2.27.x auf Port 8181 zugreift dann leitet hierbei lighttpd den Zugriff via seines proxy modules an ReGaHss weiter das Wiederrum nun auf einen anderen Port konfiguriert ist der nur intern von localhost erreichbar ist. Während solch ein proxy getriebener Zugriff auf die Port 8181 scripting Schnittstelle von ReGaHss transparent funktionieren sollte überprüft nun jedoch lighttpd mit strengerem Auge die HTTP Requests die auf Port 8181 ankommen. Dies führte z.B. in der Tat von CUxD dazu das eben seit Firmware 2.27.x man mindesten CUxD 1.9 einsetzen muss da dort ein Bug in CUxD beseitigt wurde der dazu führte das CUxD auch nicht auf Port 8181 zugreifen konnte. D.h. also, das hier auch gut sein kann das c-comatic erst an diese Gegebenheit von Firmware 2.27.x angepasst werden muss genauso wie CUxD angepasst wurde.

**Comment by jens-maus** [comment]
Gibt es hierzu noch irgendwelche weitere Information? Ansonsten würde ich dieses Issue als "User problem" verbuchen da ich nicht erkennen kann was genau hier das Problem bzgl. RaspberryMatic sein soll.

**Comment by clemz1986** [comment]
Contronics und ich sind auf der Problemsuche. Sobald es eine Rueckmeldung gibt, werde ich einen neuen Kommentar schreiben. Alle Ihre Hinweise aus diesem Thread landen selbstverstaendlich auch bei Contronics.

**Comment by jens-maus** [comment]
Gibt es diesbzgl. Schon Neuigkeiten?

**Comment by clemz1986** [comment]
Ja es gibt gute Neuigkeiten mit deiner neuesten Beta und einem Update von Contronics geht jetzt alles so wie es soll. Das Ticket kann also zu gemacht werden.
Danke für die Hilfsbereitschaft und frohe Ostern noch
