### ISSUE TITLE
Verschwundene/falsche Kanäle bei WENN & DANN Geräteauswahl --> Kanalauswahl in WebUI-Programmen nach umbenennen der Kanäle

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#810]
**Describe the bug**
Information: Betrifft nur Systeme bei denen in der Benutzerverwaltung der Haken bei "Modus vereinfachte Verknüpfungskonfiguration aktivieren gesetzt ist. ("Kindersicherung" aktiv)

Wird der Kanal eines Gerätes unter Einstellungen --> Geräte umbenannt ist er anschließend in einem WebUI-Programm unter WENN/DANN --> Geräteauswahl nicht mehr auffindbar oder es werden völlig falsche Kanäle angezeigt. Mit bestimmten Filtern ist der Kanal weiterhin zu finden aber die "Logik", so es denn eine gibt habe ich nicht durchschaut. 

**To Reproduce**
1. Ein Gerät am System anlernen und ohne umbenennen aus dem Posteingang übernehmen.
![PSM_0D2_frisch angelernt_Geräteinformationen](https://user-images.githubusercontent.com/54898249/78681673-5660fb00-78ed-11ea-9eab-dd13ce2cd29d.JPG)
2. Ein WebUI Programm erstellen und bei DANN --> Geräteauswahl den Kanal finden.
![PSM_0D2_frisch angelernt_Kanalauswahl OK](https://user-images.githubusercontent.com/54898249/78681872-93c58880-78ed-11ea-8f2f-6e1417a4c293.JPG)
- Bis hierhin ist alles ok.
3. Den entsprechenden Kanal in den Geräteeinstellungen umbenennen.
![PSM_0D2_Kanal3_umbenannt_Geräteinformationen](https://user-images.githubusercontent.com/54898249/78682021-c5d6ea80-78ed-11ea-9b1f-817e2ad213f5.JPG)
4. Erneut ein WebUI Programm erstellen und bei DANN --> Geräteauswahl Kanalauswahl taucht nun nicht mehr der gewünschte (umbenannte Kanal:3) des Gerätes auf sondern Kanal:4 der eigentlich durch die Kindersicherung ausgeblendet sein sollte.
![PSM_0D2_Kanal3_umbenannt_Kanalauswahl nicht OK](https://user-images.githubusercontent.com/54898249/78682399-341bad00-78ee-11ea-99f4-316183d6818d.JPG)
5. Es ist möglich den umbenannten Kanal:3 durch Filter zum Vorschein zu bringen.
Aber hier erschließt sich mir wie gesagt die Logik nicht.
- Filter auf die Seriennummer --> Ergebnis: Kanal:4
- Namensfilter auf "PSM" --> Ergebnis: Kanal:4
![PSM_0D2_Kanal3_umbenannt_Kanalauswahl nicht OK_Filter PSM](https://user-images.githubusercontent.com/54898249/78683455-9b862c80-78ef-11ea-8785-4f2f754511ff.JPG)
- Namensfilter auf "Device" --> Ergebnis: Kanal:3 (also **OK**)
![PSM_0D2_Kanal3_umbenannt_Kanalauswahl nicht OK_Filter Device](https://user-images.githubusercontent.com/54898249/78683545-b48edd80-78ef-11ea-9840-f3fe4be91a57.JPG)
- Namensfilter auf "0D2" --> Ergebnis: Kanal:4
- Namensfilter auf "0D2:3" --> Ergebnis: Kanal:3 (also **OK**)

**Expected behavior**
Egal ob Kindersicherung oder nicht und egal wie die Kanäle heißen, sie sollten immer angezeigt werden.

**System information (please complete the following information):**
 - RaspberryMatic 3.51.6.20200229 (OVA-Version)
 - Keine Add-On's oder sonstige Zusätze
 - Nur die eine PSM angelernt
 - Windows PC mit Oracle VirtualBox 6.1.4 r136177

Der Gegentest mit der Original CCU Software steht leider noch aus. Mal schauen ob sich ein Tester findet. 

Grüße
Baxxy

**Comment by Baxxy13** [comment]
Ich habe den Gegentest mit der Original CCU3 Firmware 3.51.6 selbst durchgeführt und es zeigte sich das das Problem dort nicht auftritt. 
![PSM_0D2_Kanal3_umbenannt_Kanalauswahl OK_OCCU](https://user-images.githubusercontent.com/54898249/78692267-e73dd380-78f9-11ea-8a39-fa6a5406efc5.JPG)

Grüße
Baxxy

**Comment by Baxxy13** [comment]
Alchy hat seine CCU (3.51.4) auch mal auf das Problem hin untersucht. Und in­te­r­es­san­ter­wei­se trat das Problem auch bei ihm auf. Das widerspricht sich leider mit dem Ergebnis meines Test's einer frischen CCU3 (siehe Post zuvor).
[https://homematic-forum.de/forum/viewtopic.php?f=26&t=57950#p573926](url)

Grüße
Baxxy

**Comment by jens-maus** [comment]
Nach kurzer Analyse scheint es wohl damit zu tun zu haben das RaspberryMatic die in 3.49.17 von eQ3 deaktivierte Sortierfunktion in der Kanalliste wieder via eines Patches (https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0066-WebUI-Fix-ListSorting.patch#L7-L9) reaktiviert hat. Wenn man diese Änderung wieder rückgängig macht taucht der Kanal 3 wieder korrekt auf.

**Comment by Baxxy13** [comment]
Nicht gerade für jedermann einfach zu handhaben. Habe es aber hinbekommen. 
![WebUI_js_Kanäle](https://user-images.githubusercontent.com/54898249/78772748-86aea500-7992-11ea-8459-6662552cca32.JPG)
Links im Bild: Original-CCU, rechts RaspberryMatic vor der Rückmachung. 

Grüße
Baxxy

**Comment by jens-maus** [comment]
@Baxxy13 Dann muss ich erst noch einen adequaten Fix dafür finden. Weil wenn du es einfach so zurücksetzt bist du nicht weiter als die CCU3, dort kann man nämlich im Kanalmodus nicht mehr die Kanäle umsortieren lassen...
