### ISSUE TITLE
Firmware update downloads/installs intelnuc firmware on rpi3

### ISSUE THREAD

**Issue by jovermann** [jens-maus/RaspberryMatic#812]
**Describe the bug**
I just tried to update RaspberryMatic from version 3.47.22.20191026 to the newest version, on a rpi3 (The ELV case, RaspberryMatic CCU3). 

There are two sub-issues: 

1. There seem to be two alternative way to update the system and it is not clear which one is the preferred one. There should be only one way for clarity. (There is Einstellungen -> System Steuerung -> Zentralen Wartung, and there is Einstellungen -> System Steuerung -> System-Update.)

2. Using the method "Einstellungen -> System Steuerung -> System-Update -> Aktuellste Firmware Installieren" resulted in downloading and apparently installing the "intelnuc" version, plus some git hash in the filename, _not_ the newest release released on github. After the installation I ended up in some kind of recovery mode. After a normal reboot I was back in the working old rpi3 firmware. 

The bugs are:
- On an rpi3 system it should never even start to download the intelnuc version.
- It should not attempt to unpack and install it.

I am right now trying the other way through "Zentralen Wartung" which requires me to manually select the file which matches my hardware (rpi3 in my case I assume).

**To Reproduce**
0. On RaspberryMatic 3.47.22.20191026 on an rpi3:
1. Go to Einstellungen -> System Steuerung -> System-Update
2. Click on Aktuellste Firmware Installieren
3. See downloaded filename containing intelnuc and not matching the latest released version number (but an even later one).

**Expected behavior**
When clicking on "Aktuellste Firmware Installieren" I expect the latest _released_ firmware to be installed.

**Screenshots**

**System information (please complete the following information):**
 - RaspberryMatic from version 3.47.22.20191026
 - RaspberryPi3 (RaspberryMatic CCU3 in the ELV case).

**Comment by jens-maus** [comment]
Sorry, but in a standard environment there is no `Einstellungen -> System Steuerung -> System-Update` menu entry. This is coming from a dedicated third-party addon named "rmupdate" (see https://github.com/j-a-n/raspberrymatic-addon-rmupdate). The standard and default RaspberryMatic/CCU way of updating to newer firmware version is to use `Einstellungen -> System Steuerung -> Zentralen Wartung`. The other one is introduced by the named CCU Addon which you can find under `Einstellungen -> Zusatzsoftware`.

So please forward your problems to the author of this third-party addon or use the only official way to update via `Einstellungen -> System Steuerung -> Zentralen Wartung`. And yes, currently you have to manually download the firmware and then upload it to your RaspberryMatic system. But this is intentially and no bug.
