### ISSUE TITLE
Systemsteuerung nicht mehr angezeigt

### ISSUE THREAD

**Issue by CKMartens** [jens-maus/RaspberryMatic#814]
**Describe the bug**
Nach Update auf Version 3.51.6.20200420 wird die Seite "Systemsteuerung" nicht mehr angezeigt. 

In Chrome wird in den Entwicklertools folgendes angezeigt:
```
/config/control_panel.cgi?sid=@5bazHFomio@:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
3prototype.js:1234 GET http://192.168.178.26/config/control_panel.cgi?sid=@5bazHFomio@ 500 (Internal Server Error)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/19702758/79860200-8a9ae800-83d2-11ea-87f2-b63c2f9f1600.png)

**System information (please complete the following information):**
 - Version  3.51.6.20200420
 - Hardware RasPi 3B+

**Comment by jens-maus** [comment]
Sorry, but this can't be a general issue as this version works perfectly for >10k users with RaspberryPi3 systems already. So please try to use a new microSD card as I suppose yours might run into its lifeend soon.

**Comment by CKMartens** [comment]
After I logged in via ssh, I saw that the file /config/control_panel.cgi is empty (only 13 bytes), all other files seem to be ok. The SD card is new (8 weeks old) and shows no errors via fsck. I will now create a new map and test it again

**Comment by CKMartens** [comment]
After creating a new SD card and importing the backup with the old configurations, the same problem occurred again.

**Comment by jens-maus** [comment]
@CKMartens There is actually no `/config/control_panel.cgi` file in the filesystem. This is only the path for the webserver. So please show the filesystem output for the file that seem to be has only 13 bytes. Normally the `control_panel.cgi` is located in `/www/config/control_panel.cgi` in the rootfs of a RaspberryMatic installation,.

**Comment by jens-maus** [comment]
@CKMartens Have you tried wiping your browser cache or using a different browser? It could be that things are now cached in your browser.

**Comment by CKMartens** [comment]
Yes, I have cleared the cache. And I also tested it on Chrome 80, Firefox 75 and Edge with the same result

**Comment by jens-maus** [comment]
Then please check the logfiles under /var/log, especially the lighttpd webserver logfiles. There must be something logged especially the 500 Internal server error you mentioned. And sorry, but I can't reproduce it here, definitly.

**Comment by CKMartens** [comment]
Good morning, it is very mysterious because there is no error in the lighttpd-error.log. Access to the /pages/tabs/admin/systemconfig.htm page is also displayed in the lighttpd-access.log, but no result or error. I have added the log files.

lighttpd-error.log:
`2020-04-21 15:48:59: (server.c.1488) server started (lighttpd/1.4.55) 
2020-04-21 15:49:00: (gw_backend.c.236) establishing connection failed: Connection refused socket: tcp:127.0.0.1:8183 
2020-04-21 15:49:00: (gw_backend.c.939) all handlers for /xy.exe?antwort=dom.GetObject(%22w_azimut%22).State(228.3) on  are down. 
2020-04-21 15:49:02: (gw_backend.c.315) gw-server re-enabled: tcp:127.0.0.1:8183 127.0.0.1 8183  
2020-04-21 15:49:03: (gw_backend.c.236) establishing connection failed: Connection refused socket: tcp:127.0.0.1:8183 
2020-04-21 15:49:03: (gw_backend.c.939) all handlers for /xy.exe?antwort=dom.GetObject(%22w_wind_spitze%22).State(2.6) on  are down. 
2020-04-21 15:49:05: (gw_backend.c.315) gw-server re-enabled: tcp:127.0.0.1:8183 127.0.0.1 8183  
2020-04-21 15:49:06: (gw_backend.c.236) establishing connection failed: Connection refused socket: tcp:127.0.0.1:32010 
2020-04-21 15:49:06: (gw_backend.c.939) all handlers for /? on  are down. 
2020-04-21 15:49:06: (gw_backend.c.236) establishing connection failed: Connection refused socket: tcp:127.0.0.1:8183 
2020-04-21 15:49:06: (gw_backend.c.939) all handlers for /xy.exe?antwort=dom.GetObject(%22w_wind_dir%22).State(135) on  are down. 
2020-04-21 15:49:08: (gw_backend.c.315) gw-server re-enabled: tcp:127.0.0.1:8183 127.0.0.1 8183  
2020-04-21 15:49:08: (gw_backend.c.315) gw-server re-enabled: tcp:127.0.0.1:32010 127.0.0.1 32010  
`
lighttpd-access.log:
`192.168.178.154 192.168.178.26 - [22/Apr/2020:06:49:39 +0200] "POST /pages/tabs/admin/systemconfig.htm?sid=@V4ZDLzFeRt@ HTTP/1.1" 200 6055 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"
192.168.178.154 192.168.178.26 - [22/Apr/2020:06:49:41 +0200] "POST /esp/system.htm?sid=@V4ZDLzFeRt@&action=UpdateUI HTTP/1.1" 200 830 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"
192.168.178.154 192.168.178.26 - [22/Apr/2020:06:49:44 +0200] "POST /api/homematic.cgi HTTP/1.1" 200 56 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"
192.168.178.154 192.168.178.26 - [22/Apr/2020:06:49:44 +0200] "POST /esp/system.htm?sid=@V4ZDLzFeRt@&action=UpdateUI HTTP/1.1" 200 830 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"
192.168.178.154 192.168.178.26 - [22/Apr/2020:06:49:47 +0200] "POST /esp/system.htm?sid=@V4ZDLzFeRt@&action=UpdateUI HTTP/1.1" 200 830 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"
192.168.178.154 192.168.178.26 - [22/Apr/2020:06:49:49 +0200] "POST /api/homematic.cgi HTTP/1.1" 200 56 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"
192.168.178.154 192.168.178.26 - [22/Apr/2020:06:49:50 +0200] "POST /esp/system.htm?sid=@V4ZDLzFeRt@&action=UpdateUI HTTP/1.1" 200 830 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"
192.168.178.154 192.168.178.26 - [22/Apr/2020:06:49:51 +0200] "GET /upnp/basic_dev.cgi HTTP/1.1" 200 989 "-" "Microsoft-Windows/10.0 UPnP/1.0"
192.168.178.3 192.168.178.26:8181 - [22/Apr/2020:06:49:52 +0200] "POST /rega.exe HTTP/1.1" 200 2162 "-" "-"
192.168.178.86 192.168.178.26 - [22/Apr/2020:06:49:53 +0200] "GET /xy.exe?antwort=dom.GetObject(\"w_windrichtung\").State(\"O\") HTTP/1.1" 200 108 "-" "-"
192.168.178.154 192.168.178.26 - [22/Apr/2020:06:49:53 +0200] "POST /esp/system.htm?sid=@V4ZDLzFeRt@&action=UpdateUI HTTP/1.1" 200 830 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"
192.168.178.154 192.168.178.26 - [22/Apr/2020:06:49:54 +0200] "POST /api/homematic.cgi HTTP/1.1" 200 56 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"
192.168.178.86 192.168.178.26 - [22/Apr/2020:06:49:55 +0200] "GET /xy.exe?antwort=dom.GetObject(\"w_wind_dir\").State(90) HTTP/1.1" 200 108 "-" "-"
`

![image](https://user-images.githubusercontent.com/19702758/79942287-c97a7d80-8466-11ea-8f47-67b9f122a6d0.png)

**Comment by jens-maus** [comment]
And what happens with a clean install before you restore your backup? Does a clean/fresh RM install work?

**Comment by CKMartens** [comment]
On a clean installation is the system config menu avaiable. If the backup is loaded the problem comes again

**Comment by jens-maus** [comment]
@CKMartens Then I would suggest you provide a copy of your backup for investigation. You can of course upload it to a private cloud where I can download it (send me an email) and then I can investigate if I can reproduce the problem or not.

**Comment by jens-maus** [comment]
@CKMartens And can your first please check if other pages (Einstellungen -> Geräte) work? And do you see any javascript/webbrowser error if you open the developer menu, e.g. in Chrome?

**Comment by CKMartens** [comment]
> And can your first please check if other pages (Einstellungen -> Geräte) work? And do you see any javascript/webbrowser error if you open the developer menu, e.g. in Chrome?

All pages except the control panel work. Only the previously mentioned error is displayed in the Chrome developer tool.
`jquery.js:2 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
n Chrome wird in den Entwicklertools folgendes angezeigt:
/config/control_panel.cgi?sid=@5bazHFomio@:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error) 3prototype.js:1234 GET http://192.168.178.26/config/control_panel.cgi?sid=@5bazHFomio@ 500 (Internal Server Error)`

> Then I would suggest you provide a copy of your backup for investigation. You can of course upload it to a private cloud where I can download it (send me an email) and then I can investigate if I can reproduce the problem or not.

You have mail

**Comment by jens-maus** [comment]
Ok, I think I located the problem. Please have a look in the content of your `/etc/config/hm_addons.cfg` file:

```
$ cat hm_addons.cfg 
ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
```

So it seems your `/etc/config/hm_addons.cfg` file is corrupted (probably due to crash). So either you restore it from an older backup where it still contains valid text or you simply delete it (you only have CUxD and Mediola Addon installed anyway).

**Comment by CKMartens** [comment]
Thank you very much for your help and time, that solved the problem. I close the issue
