### ISSUE TITLE
HM-Dis-EP-WM55 does not work through the XML interface

### ISSUE THREAD

**Issue by Apfelcheck** [jens-maus/RaspberryMatic#815]
I´m using the mentioned display through ioBroker. I write occasionally new text into the three changeable lines into the display. After the last update i get generally an exception visible in the logs when my script tries to change the display.

```
hm-rpc.0 | 2020-04-22 21:21:48.751 | error | (13983) Error: XML-RPC fault: Failure
hm-rpc.0 | 2020-04-22 21:21:48.751 | error | (13983) xmlrpc -> setValue ["3","SUBMIT","0x02,0x0A,0x12,0x32,0x30,undefined,0x43,0x13,0x86,0x0A,0x12,0x61,0x62,0x63,0x65,0x13,0x85,0x0A,0x12,0x42,0x61,0x72,0x62,0x61,0x72,0x61,0x13,0x85,0x0A,0x14,0x
hm-rpc.0 | 2020-04-22 21:21:45.462 | error | (13983) Error: XML-RPC fault: Failure
hm-rpc.0 | 2020-04-22 21:21:45.460 | error | (13983) xmlrpc -> setValue ["3","SUBMIT","0x02,0x0A,0x12,0x32,0x30,undefined,0x43,0x13,0x86,0x0A,0x12,0x65,0x65,0x65,0x65,0x65,0x13,0x85,0x0A,0x12,0x42,0x61,0x72,0x62,0x61,0x72,0x61,0x13,0x85,0x0A,0x
```

I volunteer to test the fix.

**Comment by jens-maus** [comment]
Can you please provide the script you are using in ioBroker to set the HM-Dis-EP-WM55.

**Comment by jp112sdl** [comment]
Die übergebene Zeichenfolge ist falsch:
`...0x30,undefined,0x43...`

**Comment by jens-maus** [comment]
Das habe ich auch bereits wahrgenommen ;) Allerdings würde ich trotzdem gerne mal den besagten ioBroker Skript sehen wollen.

**Comment by Apfelcheck** [comment]
Sorry, war definitiv meine Schuld. Habe irgendwie parallel zum Update der
Homematic-Version in meinem Skript ein ° eingebaut, woraus BlueFox' Adapter
wohl ein undefined macht. Ich werde mal beim Adapter vorschlagen, dass man
solche Zeichenfolgen wohl komplett auslässt. So wie ich das gesehen habe,
kann das Display 7 bit ASCII nach der zu Beginn der 80er gültigen deutschen
Kodierung.

Nochmals sorry, bitte Issue schließen

Grüße

Waldemar Cichon
