### ISSUE TITLE
Möglichkeit in der WebUI, eine Bedingung negiert auszuwerten

### ISSUE THREAD

**Issue by HMMike** [jens-maus/RaspberryMatic#816]
**Describe the solution you'd like**
Ein WebUI Programm besteht im Bedingungsteil aus Conditions und Singleconditions, die bei Triggerung des Programmes dann entsprechend überprüft werden. In der regaHss gibt es die offiziell undokumentierte Funktion `oSCD.NegateCondition()`, mit der eine Invertierte (`true`) bzw eine Standart (`false`) Auswertung der SingleCondition gesetzt werden kann. mittels `[boolean]=oSCND.NegateConfition()` kann der Zustand abgefragt werden.

Auswertereihen dokumentiere ich im Moment noch hier: 
https://homematic-forum.de/forum/viewtopic.php?f=65&t=58295

In der Rega ist die Funktion wohl vollständig implementiert, zur Umsetzung muss sowohl eine Anzeige in der WebUI als auch eine Änderungsmöglichkeit zwischen invertiert/normal neu implementiert werden.  Dabei bräuchte ich entsprechende Unterstützung.

so sieht eine Bedingung jetzt aus:
![grafik](https://user-images.githubusercontent.com/42892466/80140452-3ea19c00-85a8-11ea-9b9b-d77f7e28defd.png)

bei berücksichtigung der `NegateCondition()` würde immer VOR dem Texte des Conditiontypes (hier in dem beispiel bei, ansonsten auch um, im bereich von, halt die textliste für die Conditionstypes) bei aktivierter invertierung das wort NICHT von mir aus auch in fett geschrieben (englisch NOT, also anlegen als Übersetzfähoigen text) dargestellt. Dies wiesst dann auf eine negierte Auswertung hin. an der richtigen Stelle wäre es grof auch nur eine Zeile:

```
if(sCOND.NegateCondition()) { Write("NICHT "); }
```

Das wäre auch die Form, wie es in einer SPS darstellelt würde.

dann muss es noch anwählbar bzw änderbar sein... da kommts drauf an, was einfache rist oder was besser in dein UsabilityKonzept der WebUI passt: Entweder ganz am Ende der zeile (vor oder nach dem Roten x für das löschen der Singlecondition) ein Dropdown für z.b. ...., invert und damit ändern von Nicht in der Darstellung oder was ich präferieren würde

Die darstellugn könnte so aussehen bei Invertierung
![grafik](https://user-images.githubusercontent.com/42892466/80140632-81fc0a80-85a8-11ea-8dd8-a7bbc81d9db3.png)
Für die Umsetzung denke ich ist `programs.fn` der richtige Ansatz, für die Darstellugn müsste eine Zeile in function `::WriteConditionText()` eingefügt werden.
Bei einer Implmentierung einer Togglemöglichkeit für eine Implementierung scheiter ich aber leider. sollte für geübte allerdings kein hexenwerk sein.

**Describe alternatives you've considered**

**Additional context**

**Comment by HMMike** [comment]
Ich bräuchte für weitere Umsetzung jemanden, edr sich mit der WebUI Programmierung auskennt. Regatechnisch sollte dies kein problem machen bzw laufen syntetisch per Script bzw mit dem SDV erzeugte Programme mit diesem Feature nun seit mehreren Monaten auf meinen System stabil

**Comment by jp112sdl** [comment]
Habe mal einen Versuch gewagt.
[0077-WebUI-NegateCondition.patch](https://github.com/jp112sdl/RaspberryMatic/blob/master/buildroot-external/patches/occu/0077-WebUI-NegateCondition.patch)

Bitte mal testen, ob das so passt.

<img width="690" alt="Bildschirmfoto 2020-07-30 um 08 21 38" src="https://user-images.githubusercontent.com/18190139/88888075-e8469800-d23d-11ea-8434-08da50c404a0.png">
