### ISSUE TITLE
Kein boot von USB möglich mit Version 3.51.6.20200420

### ISSUE THREAD

**Issue by Takero1978** [jens-maus/RaspberryMatic#817]
Umgebung: 
RPi 3 Modell B+
USB HDD WD 250GB
Keine SD Karte - USB only

Das System startet nicht mehr nach dem Update. 
Der boot von einem neu ausgesetzten System mit frischem Image ist auch nicht Möglich. Der RPi erkennt die HDD und erkennt sie als Bootdevice, danach geschieht nichts mehr.

**Comment by jens-maus** [comment]
Tut mir leid, aber das sind zu wenig Informationen. Bitte einmal ein HDMI Monitor + Keyboard anschliessen und schauen was angezeigt wird.

**Comment by Takero1978** [comment]
Also ich versuche es nochmal genauer zu beschreiben. Ich kann Leider keine Screenshots im Moment machen da mein System wieder mit der alten Firmware läuft.

- An meinem RPi ist eine USB HDD angeschlossen von WD (PiDrive)
- Auf dieser HDD lief schon immer RaspberryMatic
- Beim letzten Update auf 3.51.6.20200420 wollte das System nicht mehr starten
- Daraufhin habe ich ein HDMI Kabel und eine Tastatur angeschlossen um den Bootvorgang zu beobachten
- Das System gibt auf dem Monitor aus das es keine SD gefunden hat und nun von Device USB booten möchte, es erkennt auch die HDD richtig
- Danach geschieht nichts mehr, das System steht

- Danach habe ich mittels balenaEtcher das Image auf eine Baugleich HDD gespielt und versucht von dieser zu starten
- Gleiches Fehlerbild

- Anschließend habe ich ein anderen RPi genommen (Version 3 Model B)
- Diesen auf USB Boot eingerichtet 
- Gleiches Fehlerbild

- Gegenprobe mit der Vorherigen Firmware 3.51.6.20200229
- Zunächst auf dem RPi 3 Modell B wieder mittels balenaEtcher 
- System bootet ganz normal

- Gleicher Versuch auf dem RPi 3 Modell B+ 
- System bootet ganz normal 

- nochmal versucht mit dem Image von 3.51.6.20200420 
- bootet nicht
