### ISSUE TITLE
ALT+F2 Return bei RPiZERO W führt beim Startvorgang zu keiner Reaktion.

### ISSUE THREAD

**Issue by sammykd** [jens-maus/RaspberryMatic#818]
Hallo,
ich habe den aktuellsten RPiZERO-Image von RaspberryMatic geflasched Ver.3.51.6-20200420. Nun möchte ich den RPIZero als WLANGATEWAY einsetzten und muss zur Einrichtung auf die Konsole des Systems. Die benutzte Hardware ist ein RPIZERO W mit einem 5,1 Volt und 3 A Netzteil einem HDMI KABEL und bisher drei versuchte USB-Tastaturen. Beim Starten des Zero führt ALT+F2 Return oder nur ALT+F2 zu keinerlei Reaktion, der Pi läuft bis zum Error der fehlenden IP-Adresse und dann ist Schluss. Zum Vergleich habe ich die gleiche HW an einem RPi3 angeschlossen bei dem ALT+F2 ohne Probleme funktioniert. Um nun die Tastatur und das Netzteil bei dem RPIZ auszuschließen habe ich RASBIAN auf dem ZERO geflashed und siehe da, die Taststatur funktioniert. Ein weiterer RPIZERO W zeigt das gleiche verhalten mit RasberryMatic und sträubt sich auch ALT+F2 anzunehmen. Ich habe dann beobachtet, dass vor dem starten des Kernels 2 Device per USB erkannt werden. Verifizierung durch abziehen der Taststatur ergab dann nur noch 1 Device leider kann man nicht sehen was es genau ist. Fakt ist keine Reaktion mit RasberryMatic auf einem RPI ZERO W nach Kernelstart durch die Tastatur. Bin mit meinem Latein am Ende. Bitte um Hilfe.
Hier mal ein Foto vom Bootvorgang.
![RPiZero RaspberryMatic_Boot](https://user-images.githubusercontent.com/57226083/80369940-60906c80-888f-11ea-891c-6255763a2255.jpg)

**Comment by GitTomahawk** [comment]
Bei mir hängt sich das aktuelle Release 3.51.6.20200621 mit frisch geflashter sd auf rpizerowauch direkt nach dem "starting kernel" auf. 3.51.6.20200613 funktioniert.

**Comment by GitTomahawk** [comment]
Ich habe bei meinem mittlerweile die Ursache gefunden - beim ersten booten hat er scheinbar immer wieder was am filesystem kaputt geschrieben. Nach dem x-ten mal re-Flashen ist es sauber durch gelaufen. 
Nach etwas Ladezeit kommt die meldung "init udev" - dannach funktioniert auch die usb-Tastatur und die tastenkombination ALT+F2. 
Beim Ersten boot muss man mit viel gedult bis zum Ende warten.
Dann kann man sich mit root und leerem passwort einloggen und ihn dann auch sauber mit "halt" anhalten. 
Anschließend kann man die sd karte in nem anderen Linux system mounten und die Konfiguration anpassen. (dann muss man nicht alles abtippen)
Wichtig ist auch hier sie wieder sauber zu unmounten.
