### ISSUE TITLE
Connect HB-RF-USB-TK via virtual serial port and WIFI-Serial converter

### ISSUE THREAD

**Issue by roesl** [jens-maus/RaspberryMatic#819]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Because of problems with mapping the USB to the VM at a Synology DS918+ ( the USB mapping will every time deleted after rebooting the Synology)   and no way, to get the Raspberrymatic VM started at bootup with the mapped USB device, it would be the best, when the device is connected over a VSP ( I did this for my second VM with IP-Symcon and Zigbee2mqtt - Device and it works fine for Zigbee.)

**Comment by roesl** [comment]
isnt it possible to use the HM-LGW-O-TW-W-EU Lan gateway instead of the HB-RF-USB-TK for the VM ?

**Comment by jens-maus** [comment]
Sorry, but using a virtual serial port or even routing a HB-RF-USB via WiFi is not possible because a RPI-RF-MOD/HM-MOD-RPI-PCB requires garanteed  low latency which WiFi or Ethernet cannot provide. And using a HM-LGW-O-TW-W-EU is of course possible but only allows to use BidCos-RF homematic devices and isn't homematicIP compatible. So sorry, but I don't see any way for any improvement yet.

**Comment by roesl** [comment]
I use the HM-MOD-RPI-PCB in the moment with the HB-RF-USB-TK in VM on Aynology but I cannot connect HM-IP devices - whats the problem

**Comment by roesl** [comment]
How to connect the HM-LGW-O-TW-W-EU ?

**Comment by jens-maus** [comment]
Sorry, but this is a bug/issue tracker and no support fora. Please ask for help in the homematic-forum.de fora instead.

**Comment by roesl** [comment]
Mit einem LAN-seriell Konverter wie z.B. dem Xport sollte die Latenz ja nicht so groß sein.
Ich habe das Teil hier auf Lager und könnte es mit der  RPI-RF-MOD ausprobieren, falls ich Infos bekomme, wie ich den Lan-Adapter in der VM anmelden kann.

**Comment by roesl** [comment]
der HM-LGW-O-TW-W-EU läuft mittlerweile problemlos aber leider ohne HM-IP.
Dachte erst die Homematic macht Probleme, wenn beim Start kein USB Adapter verfügbar ist, das Gateway wird aber problemlos aktiviert.
Da ich aber einige HM-IP Geräte habe, brauche ich eine Lösung über LAN oder Wlan, die HM-IP unterstützt, da ich neben der Synology keine weitere Hardware mehr betreiben möchte-
Leider schläft das EQ3

**Comment by jens-maus** [comment]
@roesl Noch einmal: Das ist hier KEIN Diskussionsforum sondern dient nur dazu Bugs und Feature Enhancements technisch zu verwaltung und deren Lösung/Implementierung zu besprechen. Bitte also die Diskussion im Homematic Forum weiterführen und erst wenn sich aus diesen Diskussionen ein konkreter Bug in RaspberryMatic oder eine konkrete technische Verbesserungsmöglichkeit aufzeigt ist das eröffnen eine GitHub Tickets sinnvoll.
