### ISSUE TITLE
'No BidCoS-Interface available' nach initialer Installation (ohne Backup)

### ISSUE THREAD

**Issue by edddymax** [jens-maus/RaspberryMatic#82]
Habe Image neu installiert ( beta 5, mehrfach und auf 2 Raspis). Kein Backup eingespielt. Folgende Meldungen:
BidCos-RF ... reagiert nicht.
In log:
```
CCU2CommControllerMod::sendSystemCommand(): failed
Mar 26 15:24:56 homematic-raspi user.info kernel: [ 109.912491] eq3loop: created slave ttyS0
Mar 26 15:24:56 homematic-raspi user.info kernel: [ 109.913006] eq3loop: created slave mmd_bidcos
Mar 26 15:24:47 homematic-raspi user.info update-coprocessor: Mar 26 15:25:02 homematic-raspi user.err multimac: No Coprocessor detected!!! 
Mar 26 15:25:02 homematic-raspi user.info kernel: [ 115.915683] eq3loop: eq3loop_close_master() mmd_bidcos
Mar 26 15:25:02 homematic-raspi user.info kernel: [ 115.915710] eq3loop: eq3loop_close_master() mmd_bidcos destroy device
Mar 26 15:25:02 homematic-raspi user.info kernel: [ 115.916081] eq3loop: eq3loop_close_master() ttyS0
Mar 26 15:25:02 homematic-raspi user.info kernel: [ 115.916098] eq3loop: eq3loop_close_master() ttyS0 destroy device
Mar 26 15:25:06 homematic-raspi user.err rfd: CCU2CommController::improvedInit() - Identify response string not handled: 
Mar 26 15:25:06 homematic-raspi cron.err crond[254]: time disparity of 24842244 minutes detected
Mar 26 15:25:11 homematic-raspi user.err rfd: () CCU2CommController::setCSMACAEnabled(): Error disabling CSMA/CA.
Mar 26 15:25:11 homematic-raspi user.err rfd: No BidCoS-Interface available
...
```
Damit kein Anlernen von HM- oder HM-IP -Geräten  möglich. Die Dienste laufen nicht.
Nach Installieren des Backups läuft alles mit den bereits angelernten HM-Geräten, auch ein Neuanlernen klappt. HM-IP - Geräte können nicht angelernt werden. Dienst läuft nicht.

**Comment by jens-maus** [comment]
Dieses verhalten kann ich hier leider nicht nachvollziehen. Das einzig komische was ich hier aus deinem Logoutput herauslesen ist die `time disparity` zeile die darauf hindeutet das die lokale Zeit anscheinend nicht ganz mit der realen synchron ist. Du scheinst also auch keine RTC einzusetzen. Hierbei kann es auch gut sein das du eben in deinem Backup andere NTP Server angegeben hast und deshalb in irgendeinerweise das HmRF und HmIP nicht geht wenn du kein Backup eingespielt hast.

Da ich jedoch dieses verhalten noch nie wahrgenommen habe bei all meinen Testsystemen kann ich leider  nicht mehr dazu sagen und man müsste abwarte ob andere Personen das gleiche problem melden.

**Comment by edddymax** [comment]
Ich glaube, dass es daran liegt, dass rfd nicht läuft:
Mar 27 11:38:48 homematic-raspi user.err rfd: CCU2CommController::improvedInit() - Identify response string not handled:
Mar 27 11:38:53 homematic-raspi user.err rfd: () CCU2CommController::setCSMACAEnabled(): Error disabling CSMA/CA.
Mar 27 11:38:53 homematic-raspi user.err rfd: No BidCoS-Interface available

Nach Einspielen des Backups wird der Dienst bei ps angezeigt.

Ein Neustart mit  /bin/rfd -f /etc/config/rfd.conf -l 5 stürzt auch ab.

**Comment by jens-maus** [comment]
@edddymax Mit was für einer Meldung stürzt rfd denn bitte ab? Gibt es dazu irgendwelche Informationen im Logfile oder via `dmesg`? Bis wir die wahre Ursache gefunden haben werde ich das Ticket auch mal wieder öffnen.

**Comment by edddymax** [comment]
Sorry. Alles ok, habe an der falschen Stelle gesucht. Mein Funkmodul war defekt und im Backup wurde mein HM-CFG-LAN (LAN-GW) eingespielt. Darüber liefen die Neuanmeldungen. 
Vielleicht auch gleich eine neue Variante für RaspberryMatic: Ohne Funkmodul , sondern mit einem Gateway (aber über HM_CFG-LAN funktionierte kein HMIP-Anlernen).
