### ISSUE TITLE
Programm Eigenschaften / Filter wird falsch angewendet in WebUI

### ISSUE THREAD

**Issue by StefanGubler** [jens-maus/RaspberryMatic#820]
**Describe the bug**
Die Filter bzw. die Eigenschaften der Programme werden zur Anzeige und für die Aktivität der Programme werden in der Anzeige und in den Favoriten falsch umgesetzt.  Die Eigenschaft "bedienbar"  entscheidet über die Anzeige eines Programms und nicht die Eigenschaft "sichtbar"

**To Reproduce**
Siehe Anhanh

**Expected behavior**
Die Filter werden korrekt umgesetzt im WebUI

**Screenshots**
See attachement

**Comment by jens-maus** [comment]
Duplicate of #821
