### ISSUE TITLE
No HM-IP with HM-MOD-RPI-PCB  and the HB-RF-USB-TK in VM on Synology 

### ISSUE THREAD

**Issue by roesl** [jens-maus/RaspberryMatic#822]
I use the HM-MOD-RPI-PCB in the moment with the HB-RF-USB-TK in VM on Synology but I cannot connect HM-IP devices - whats the problem

**Comment by roesl** [comment]
How to connect the HM-LGW-O-TW-W-EU ? If the HM-MOD-RPI-PCB dont work with HM-IP I better use the gateway

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!
