### ISSUE TITLE
HMIP-PS Geräte nicht schaltbar

### ISSUE THREAD

**Issue by dietmarhein** [jens-maus/RaspberryMatic#824]
**Describe the bug**
Seit FW Release 3.51.6.20200420 sind HMIP-PS nicht mehr schaltbar.
Servicemeldung: "Gerätekommunikation gestört".
Bei manueller Schaltung wird der Status korrekt rückübermittelt.
Funktionstest über Webgui mit Button "Test starten" funktioniert in der Regel korrekt.

**Logs attached**
[homematic-2020-04-28.log](https://github.com/jens-maus/RaspberryMatic/files/4548279/homematic-2020-04-28.log)

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!
