### ISSUE TITLE
USB nicht mehr korrekt erreichbar per CUxD

### ISSUE THREAD

**Issue by heitec11** [jens-maus/RaspberryMatic#825]
bei mir funktioniert die Funktion Log-File auf einen USB-Stick per CUxD nicht mehr, nachdem ich auf RaspberryMatic 3.51.6.20200420 abgedatet habe.

**Comment by jens-maus** [comment]
Bitte mehr Details! Das löschen des ticket templates statt dieses korrekt auszufüllen ist leider ziemlich kontraproduktiv. Bitte daher mehr details, beispiele, screenshots liefern und begründen wieso das ein bug in RaspberryMatic statt in CUxD sein soll.

**Comment by heitec11** [comment]
Hallo,
sorry. Ich habe folgendes festgestellt.
Mein an der Raspberrymatic (Ri 3+) angeschlossener USB Stick ist durch das Update zum Read-only Medium geworden.
Habe den Stick nun neu formtiert und es scheint wieder zu laufen.
Das ganze wurde mit dem Raspberrymatic Update ausgelöst.
