### ISSUE TITLE
ser2net / USB enocean stick stopped working after upgrade to 3.51.6.20200420

### ISSUE THREAD

**Issue by SturmMichael** [jens-maus/RaspberryMatic#827]
**Describe the bug**
I use a FTDI based enocean stick connected by USB to a raspberrymatic driven RPI3B+. The tool ser2net is used to enable a TCP connection to the stick. This worked stable until the last version. After the upgrade the TCP connection is still working and also /dev/ttyUSB0 exists, but no data is transmitted. As an intermediate solution I connected the enocean stick to another RPI3B+ running raspbian and ser2net. This works ...

**To Reproduce**
1. Install Raspbian 3.51.6.20200420
2. Connect a USB based enocean stick to the USB port -> /dev/ttyUSB0 will appear
3. Activate ser2net by editing the config file e.g. "5000:raw:0:/dev/ttyUSB0:57600 8DATABITS NONE 1STOPBIT"
4. Connect with telnet to the configured port (5000)
5. Operate some enocean devices -> no data is transmitted via telnet

**Expected behavior**
In step 5 there shoud be some data showing up

**System information (please complete the following information):**
 - Version 3.51.6.20200420
 - Hardware RPI3B+

**Additional context**
Could be related to other USB problems as mentioned from other users (Tinker board USB stick mount problems)

**Comment by jens-maus** [comment]
Have you tried a recent experimental nightly build test version (e.g. 20200501) which you can download from here: https://github.com/jens-maus/RaspberryMatic/releases/tag/snapshots ? I recently updated the kernel version which seem to have solved the usb problems with a Tinkerboard.

**Comment by SturmMichael** [comment]
Just tested with the latest build test version. No, the problem is still there. Are there any documented changes in the USB area of the used kernel? Anyway, not highest prio for me, as the solution with an additional rapberry pi helps running my homeautomation.

**Comment by SturmMichael** [comment]
Just installed the 3.51.6.20200613 release ... and it works again! Thanks for maintaining this great software :)
