### ISSUE TITLE
Skriptanlage / Änderung funktioniert mit 3.51.6.20200420 nicht mehr

### ISSUE THREAD

**Issue by willow999** [jens-maus/RaspberryMatic#829]
**Describe the bug**
Beim Einfügen / Ändern eines Skriptes wird dieses nicht gespeichert.

**To Reproduce**
1. Auf "Programme und Zentralenverknüpfungen" gehen.
2. Neues Programm erstellen / existierendes Programm bearbeiten (es muss ein Programm mit Skript sein)
3. Beliebige "WENN" Bedingung anlegen
4. Im "DANN"-Zweig "SKRIPT" auswählen
5. Skript bearbeiten und auf "OK" klicken
6. Das Skript wird nicht übernommen:
![image](https://user-images.githubusercontent.com/65049269/81472671-f7e3b100-91f9-11ea-8101-b67f69b88ee5.png)
7. Programm mit "OK" speichern
8. Programm neu öffnen
9. Im "DANN"-Zweig erscheint jetzt bei "Skript" nur noch "..." (=leeres Skript ohne Code)

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
 - Version 3.51.6.20200420
 - Hardware CCU3

**Additional context**
Zusatzsoftware verwendet:
- CuxD
- Sonos Player
- XML-API
- Redmatic

**Comment by jens-maus** [comment]
Bitte den Inhalt des Skriptes hier zeigen der versucht wird zu speichern.

**Comment by willow999** [comment]
Der Inhalt des Skriptes hat keinerlei Einfluss auf den Fehler. Ich habe es gerade einmal mit 
"WriteLine("Hello World");" probiert. Fehler der gleiche.

Das Skript selbst zeigt keine Fehler und ich kann es auch erfolgreich ausführen (=testen). Telegram gibt die korrekte Meldung aus.
Der Fehler tritt auch auf, wenn ich ein vorhandenes Skript editiere und einfach nur ein Leerzeichen irgendwo einfüge und wieder lösche.

Mein Skript ist das folgende:
! HomeMatic-Script
! TELEGRAM-FRAMEWORK
! http://www.christian-luetgens.de/homematic/telegram/telegramframework/T-Framework.htm

 object o = dom.GetObject ("xxxx");
 string s = o.Value();

if (s != "") {
  string s_cmd = "wget --no-check-certificate --quiet -O /dev/null \"https://api.telegram.org/XXX&text=" #" Alarm: ausgelöst:" # s.ToUTF8().UriEncode() # "\"";
  dom.GetObject("CUxD.CUX2801001:1.CMD_EXEC").State(s_cmd);
  o.State ("");
}

**Comment by jens-maus** [comment]
Tut mir leid, aber das kann ich nicht reproduzieren und auch andere Nutzer scheinen damit bisher kein Problem zu haben. Werde daher bis auf weiteres dieses Issue/Ticket schliessen.
