### ISSUE TITLE
HMIP-BDT Dimmbereich

### ISSUE THREAD

**Issue by Jemeins** [jens-maus/RaspberryMatic#830]
**Problem:**
Beim Verwenden des HMIP-BDT mit LEDs wird häufig nicht der Dimmbereich von 0 bis 100% genutzt, da die LEDs im unteren Bereich (unter 10%) flackern oder im oberen Bereich (ab 80%) schon auf voller Helligkeit betrieben werden. 

**Funktionserweiterung:**
Eine Möglichkeit zum Voreinstellen des Ausgangs-Dimmbereichs, sodass die volle Range der drei virtuellen Kanäle wider genutzt werden kann.

**Comment by jens-maus** [comment]
Tut mir leid, aber das ist ein Hardware bzw. Geräte-Firmware Verbesserungs/Änderungsvorschlag der nicht vom RaspberryMatic Projekt abgedeckt werden kann. Bitte daher direkt an eQ3 wenden da im Rahmen dieses OpenSource Projektes kein direkter Einfluss auf solche verbesserungen gemacht werden kann.
