### ISSUE TITLE
Raspberrymatic startet nicht mehr nach Update des VMM auf Synology

### ISSUE THREAD

**Issue by roesl** [jens-maus/RaspberryMatic#831]
Hallo,

nach dem Update des Virtual Machine Managers auf der Synology auf Version 2.5.1-9623 startet die Raspberrymatic nicht mehr und bleibt nach der Initiialisierung des RF-Moduls hängen.
Dies passiert auch ohne ein USB Modul wenn nur das LAN Gateway verwendet wird.

**Comment by roesl** [comment]
Tippfehler : es muß ..420 heißen

**Comment by roesl** [comment]
hängt bei "starting rngd ..."

**Comment by jens-maus** [comment]
Bitte mehr Infos liefert, insbesondere ausgaben von `dmesg`& co.

**Comment by roesl** [comment]
Leider habe ich auch nicht mehr Informationen - ich sehe nur den Screen mit "lade dmesg..." - da hängt dann das System und ich habe auch keine Netzwerkverbindung um auf die Konsole zu kommen

**Comment by jens-maus** [comment]
ALT+F2 drücken sollte die bootup meldungen zeigen.

**Comment by roesl** [comment]
![image](https://user-images.githubusercontent.com/23452986/81964895-8fd90480-9617-11ea-8eee-8a4309592d1b.png)

**Comment by jens-maus** [comment]
Thanks, I also just tested it myself and could reproduce it. However, it seems that the `/dev/hwrng` device of the newer VMM version seem to behave way slower and that's why starting the rng daemon takes so long. But it seems to finish at some point. Just wait until it finishes its startup.

Nevertheless, I will try to add some workaround for the next version which will have a nicer check if the `/dev/hwrng` device works fast enough or as expected.

**Comment by roesl** [comment]
after 30 minutes it has started - but ist a Long time :) 
When do you think, a new version is available ?
Thanks !

**Comment by jens-maus** [comment]
If I add this you can of course use a nightly build if you are brave enough. But to me this currently looks like a problem in the VMM version from synology. I can just workaround this in the startup, but reading from the hardware random devices definitly slowed down a lot, thus there might further issues up the road when trying to use random numbers in a VMM hosted linux system like RaspberryMatic. Thus, somebody should report this to Synology IMHO.

**Comment by jens-maus** [comment]
So, the next nightly snapshot should hopefully work around that issue. So please test it accordingly or apply the minor change shown in b6d01bb

**Comment by roesl** [comment]
I already opened a case at Synology and I will send the information you have provided

**Comment by Homie13** [comment]
Hallo Jens, ich habe das gleiche Problem mit meiner DS918+ und der aktuellen Firmware. Kenne mich nicht so aus im github. Bzw. weiß jetzt nicht wie ich deinen Workaround in die VM bekomme.

Grüße

**Comment by MattN82** [comment]
Ich hatte das VMM Update ne Weile links liegen lassen, vorhin raufgespielt und hab jetzt natürlich dasselbe Problem :-(
Gottseidank hab ich diesen Thread gefunden.
Nur...meine DS918+ wartet jetzt seit einer Stunde auf "rngd"...lohnt sich da weiteres warten? Sind jedenfalls schon deutlich über 30 Minuten. Wie lange "darf" das denn dauern?

**Comment by roesl** [comment]
bei mir hats mal zuerst auch über ne Stunde gedauert. dann mal wieder ca 30 Minuten.
Ich habe derzeit das Debmatic auf einem Ubuntu Linux laufen, bis das Problem gelöst ist.

**Comment by MattN82** [comment]
Ich habe eben grad das Update gestartet auf die neuste Version. Beim reboot nach dem Update bleibt er nach wie vor bei "starting rngd" hängen. Erst seit etwa 10 Minuten, aber da es in den Releasenotes der neusten Version als "gelöst" drinsteht, dachte ich, ich sollte das vielleicht posten

**Comment by jens-maus** [comment]
Tut mir leid, kann ich hier selbst nicht nachvollziehen. Bei mir geht das boot problemlos an "starting rngd" vorrüber..

**Comment by MattN82** [comment]
Kommando zurück :-) Nach erneutem Reboot, bleibt es jetzt auch bei mir nicht mehr hängen. Trotzdem Danke für die superschnelle Reaktion,Jens.

**Comment by makuris** [comment]
Vielen Dank zuerst für Raspberrymatic. Ich liebe es... Ich habe heute auch das Update gemacht in der Hoffnung das Reboot-Problem (das uns Synology eingebrockt hat) zu lösen. Jetzt hängt es bei "Starting rngd" seit 20 Minuten.... Ich hoffe es wird noch...

**Comment by jens-maus** [comment]
@makuris Tut mir leid, aber bist du dir sicher das du auch wirklich die aktuelle RaspberryMatic für das Update nutzt und das RaspberryMatic auch schon fertig war mit dem Update? Es kann gut sein das er beim hochfahren des recovery systems ist in dem er das eigentlich update vornehmen um dann erst danach dann in die 3.56.1.20200613 zu booten. Weil um das Update durchzuführen muss er natürlich in das Recovery System booten und da gibt es dann natürlich erneut das gleiche problem. Also einfach warten bis im recovery system das update durchführen konnte und dann sollte er nach dem neustart dann definitiv die 20200613 installiert haben und das problem nicht mehr auftreten. Ich denke das gleiche wird sicherlich auch @MattN82 passiert sein.

**Comment by makuris** [comment]
@jens-maus Lieben Dank, jetzt hab ich es auch verstanden. Es war tatsächlich der Zwischen-Neustart um die neue Version zu installieren. Hat aber einfach mal 1,5h gedauert....
Alles gut, jetzt läuft es wieder. Danke!
