### ISSUE TITLE
split  key / cert also in two files so redmatic (nodejs) could use it 

### ISSUE THREAD

**Issue by simonbuehler** [jens-maus/RaspberryMatic#832]
hi,

it would be handy to have the key also in a seperate file and use it in nodejs config

https://github.com/jens-maus/RaspberryMatic/blob/404cc86365c7a581747c228651d1223a5d4d2efd/buildroot-external/overlay/WebUI/etc/init.d/S50lighttpd#L12

**Comment by jens-maus** [comment]
Why can redmatic not simply use `/etc/config/server.pem` but need a splitted key/cert file?

**Comment by simonbuehler** [comment]
can't answer the *why*, the files just get read in and no splitting logic is there out of the box see [here](https://nodejs.org/en/knowledge/HTTP/servers/how-to-create-a-HTTPS-server/)

**Comment by jens-maus** [comment]
And if you supply the file twice? once for the key and cert? IMHO it should be already smart enough to extract the cert+key itself even thought everything is in one file.

**Comment by simonbuehler** [comment]
i'll try that tomorrow

**Comment by thkl** [comment]
I use the RasberryMatic certificate from /etc/config/server.pem also in one of my addons (based on nodejs) and its working well when key and certificate are the same file. So i think, it will work with redmatic.

**Comment by jens-maus** [comment]
Perhaps @hobbyquaker, the author of RedMatic, can comment on this?

**Comment by jens-maus** [comment]
@simonbuehler Any progress here? Otherwise I think this ticket can be closed.

**Comment by simonbuehler** [comment]
Sorry for the delay, got it working!
