### ISSUE TITLE
HmIP-SWO-PR: Wert für Batteriespannung fehlt

### ISSUE THREAD

**Issue by detLAN** [jens-maus/RaspberryMatic#833]
Bei all meinen batteriebetriebenen HmIP-Geräten wird in dem rot unterlegten Feld (siehe Screenshot) die aktuelle Batteriespannung des jeweiligen Geräts angezeigt. Nur bei meiner Wetterstation (HmIP-SWO-PR) fehlt diese Angabe.
Fehler auf RaspberryMatic (3.51.6.20200420) unter "Startseite > Einstellungen > Geräte":
<img width="1044" alt="Bild" src="https://user-images.githubusercontent.com/64675966/81988593-05ef6280-963c-11ea-828d-dc61299bd060.png">

**Comment by jens-maus** [comment]
Das scheint wohl eher ein Problem der Gerätefirmware des HmIP-SWO-PR zu sein da der betreffende Datenpunkt wohl immer 0V zurück gibt und folglich dies in der RaspberryMatic WebUI dann nicht angezeigt wird. Das wurde an folgender Stelle bereits vor Monaten einmal gemeldet: https://github.com/ioBroker/ioBroker.hm-rpc/issues/224 Bitte also einmal selbsz via Skript testen kontrollieren ob für den OPERATING_VOLTAGE der Wert auch in diesem Fall immer mit 0V zurückgegeben wird.

**Comment by detLAN** [comment]
Okay, WriteLine(dom.GetObject('HmIP-RF.xxx:0.OPERATING_VOLTAGE').State()); ergibt bei mir auch "null". Habe mal in die HmIP Device Dokumentation geguckt. Unter "149.3.1.1. Channel state parameters" gibt es bezüglich der Batterie nur "149.3.1.1.6. Parameter LOW_BAT". Der Parameter OPERATING_VOLTAGE fehlt!

**Comment by jens-maus** [comment]
Gut, dann verhält es sich sogar so, das dieses HmIP Gerät gar keinen Datenpunkt für die Batteriespannung hat. Welche Firmwareversion hat denn das Gerät bei dir?

Und es ist ja so. Nicht jedes Hm bzw HmIP Gerät verfügt über einen Datenpunkt für die Batteriespannung und dann ist es ja i.O. Das RaspberryMatic diese auch nicht in der Geräteauflistung mit anzeigt.

**Comment by detLAN** [comment]
Firmwareversion 1.0.18
https://ccu3-update.homematic.com:8443/firmware/download?cmd=download&serial=0&product=HmIP-SWO-PR
