### ISSUE TITLE
PopUp "Zusatzsoftware" lässt sich nicht scrollen

### ISSUE THREAD

**Issue by detLAN** [jens-maus/RaspberryMatic#834]
RaspberryMatic (3.51.6.20200420) unter "Startseite > Einstellungen > Systemsteuerung" läßt sich dass PopUp "Zusatzsoftware" nicht scrollen, wenn ein kleines Browserfenster oder eine niedrige Bildschirmauflösung mit mehren installierten Zusatzsoftware konfrontiert wird. Man kommt dann nicht an die Schaltfläche "Zurück" bzw. die unteren Einträge. Nur durch verschieben des Fensters gelangt man dort hin. Bei allen anderen PopUp Fenstern (z.B. Sicherheit) kann man scrollen.

**Comment by jens-maus** [comment]
Das ist bekannt und deshalb kann man als workaround/alternative einfach mit einem gedrückten Mausklick auf das Fenster dieses zurechtschieben wie man will. Ist eben eine Limitation der WebUI für die es bisher keinen erarbeiteten Patch gibt der die Situation beseitigt. Aber man kann sich eben wie geschildert behelfen. Nehme es aber als Enhancement-Request auf.

**Comment by jens-maus** [comment]
Duplicate of #592
