### ISSUE TITLE
Direkte Verknüpfungen - Fehlerhaft?

### ISSUE THREAD

**Issue by tobsi57** [jens-maus/RaspberryMatic#836]
Nach einem Upgrade auf den Charly und dem Backup einspiel bekomme ich keine Direkte Verknüpfung mehr hin. Laut RaspberryMatic fehlen die Verknüpfungspartner... 

![Screenshot 2020-05-02 13 10 23](https://user-images.githubusercontent.com/63971659/82153503-213eb580-9868-11ea-936d-87379b7ea407.png)

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!
