### ISSUE TITLE
Zeichen ° lässt sich im Skript-Editor nicht speichern (keine Anzeige am WRCD möglich)

### ISSUE THREAD

**Issue by Aquaplex** [jens-maus/RaspberryMatic#841]
**Describe the bug**
Gibt man im Skript-Editor das Zeichen ° oder alternativ ^ ein um z.B. die Temperatur auf einem WRCD-Display als 10°C anzeigen zu lassen, wird das Zeichen nicht korrekt gespeichert. Es ist allerdings möglich.

**To Reproduce**
Im Skript-Editor die Übermittlung eines Datensatzes für das WRCD vorbereiten, z.B.:
var MinTemp = dom.GetObject("SV_Temperatur_Min").Value().ToString(1) # "°C ";

**Expected behavior**
Das Zeichen wird nicht gespeichert. Beim nächsten Öffnen des Skript-Editors ist es verschwunden.

**Screenshots**

**System information (please complete the following information):**
RaspPI 4 mit aktueller RasperberryMatic

**Additional context**

**Comment by detLAN** [comment]
Hilfreich wäre vielleicht, mit welchem Browser unter welchem Betriebsystem Du arbeitest.
Bei mir mit Safari 13.1 unter MacOS 10.15 hab kann ich Dein beschriebenes Problem nicht reproduzieren. Hier funktioniert es wie es soll.

**Comment by jens-maus** [comment]
Das Problem ist prinzipiell bereits bekannt uns es existiert dazu bereits dazu ein Ticket: #225
