### ISSUE TITLE
Fehler bei RSSI Anzeige - devconfig

### ISSUE THREAD

**Issue by Kryzon** [jens-maus/RaspberryMatic#845]
**Describe the bug**
Beim Aufruf der RSSI-Werte über devconfig erscheint die Meldung:

An internal error was detected in the service software. The diagnostics are being emailed to the service system administrator (root).

**To Reproduce**
1. Devconfig aufgeruft über `http://<Raspi-IP>/tools/devconfig.cgi?sid=@<SessionID>@`
2. Menüpunkt "RSSI" aufgerufen.

**Expected behavior**
Normal sollten ja dann alle Geräte angezeigt werden, es werden aber nur ein paar angezeigt.

**Screenshots**
![Bildschirmfoto 2020-05-24 um 19 16 43](https://user-images.githubusercontent.com/36007152/82760343-274a0e80-9df3-11ea-8ab3-1f0071d454d8.png)

**System information (please complete the following information):**
 - Version Raspberrymatic 3.51.6.20200420
 - Hardware Raspberrymatic 3b

**Additional context**

In einem anderen Issue habe ich gelesen, dass der Output, der E-Mail aufschlussreich ist.

```
root@Homematic-GW:/usr/local/tmp# cat /usr/local/tmp/cgimail.29058 
Return-Path: <CGI script - do not reply>
From:  <CGI script - do not reply>
To: root
Subject:  CGI problem

CGI environment:
REQUEST_METHOD: GET
SCRIPT_NAME: /tools/devconfig.cgi
HTTP_USER_AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
HTTP_HOST: IP-Raspi
REMOTE_ADDR: IP-Laptop
cgi.tcl version: 1.10.0
input:
cmd=show_rssi&sid=<Session-ID>
cookie:
errorInfo:
can't read "devnames(000A5A49987442)": no such element in array
    while executing
"set rssi_list "\"$devnames($dev_descr(ADDRESS)) $dev_descr(ADDRESS)\" { $dev_descr(ADDRESS) { $rssi_device $rssi_peer }} $rssi_list""
    ("foreach" body line 9)
    invoked from within
"foreach dev $devlist {
                            array_clear dev_descr
                            array set dev_descr $dev
                        ..."
    ("foreach" body line 17)
    invoked from within
"foreach iface [array names interfaces] {
                set url $interfaces($iface)
                if {[string match *groups* $url] == 0} {
  #     ..."
    ("uplevel" body line 2)
    invoked from within
"uplevel 1 [lindex $args end]"
    (procedure "cgi_table" line 9)
    invoked from within
"table { 
            foreach iface [array names interfaces] {
                set url $interfaces($iface)
                if {[string match *groups* $..."
    ("uplevel" body line 3)
    invoked from within
"uplevel 1 [lindex $args end]"
    (procedure "cgi_body" line 7)
    invoked from within
"body {
    	h2 "RSSI List"
   	    table { 
            foreach iface [array names interfaces] {
                set url $interfaces($iface)
         ..."
    (procedure "cmd_show_rssi" line 10)
    invoked from within
"cmd_$cmd"
```

**Comment by Kryzon** [comment]
Ich habe noch mal die Seriennummer kontrolliert, welche erwähnt wird (can't read "devnames(000A5A49987442)": no such element in array), es handelt sich dabei um einen Rauchmelder, genauer gesagt HmIP-SWSD, dieser ist lt. Geräteübersicht auch vorhanden und der Verbindungstest über die Geräte ist erfolgreich.

**Comment by jens-maus** [comment]
@Kryzon Bitte mal folgenden ReGa/HomeMatic Skript unter "Skript testen" ausführen und das Ergebnis hier posten:

```
string dev_id;                                                           
string devs;                                               
foreach(dev_id, dom.GetObject(ID_DEVICES).EnumUsedIDs()) {   
  object dev=dom.GetObject(dev_id);                                               
  if( (dev.Interface() != 65535) && (dev.Address() != "") && dev.CreatingCompleted() ) {
    devs = devs # " " # dev.Address() # " {" # dev.Name() # "} ";                      
  }                                                                                      
}
WriteLine(devs);                                                                                       
```

**Comment by Kryzon** [comment]
@jens-maus:
Folgendes ist der Output von dem o.g. Script:

 CUX2803001 {CUxD-Ping}  HU-Deckenlicht {Deckenlicht Flur oben}  HU-Deckenlic01 {Deckenlicht Schlafzimmer 1}  HU-Dimmable 02 {Deckenlicht Schlafzimmer 2}  001558A9978929 {Fensterkontakt Büro Links}  001558A99D55FF {Fensterkontakt Büro Rechts}  001558A99D5369 {Fensterkontakt Esszimmer}  001558A99D524F {Fensterkontakt Gästebad}  001558A99EF6BE {Fensterkontakt Kleiderzimmer}  001558A99EDA1E {Fensterkontakt Küche}  001558A99D67AE {Fensterkontakt Schlafzimmer Links}  001558A99D55CF {Fensterkontakt Schlafzimmer Rechts}  001558A997895F {Fensterkontakt Wohnzimmer Links}  001558A99D6072 {Fensterkontakt Wohnzimmer Rechts}  002018A99D3072 {Heizung Bad}  INT0000011 {Heizung Badezimmer Gruppe}  002018A9975F97 {Heizung Büro}  INT0000009 {Heizung Büro Gruppe}  002018A99D1613 {Heizung Esszimmer}  002018A99D19DA {Heizung Flur EG}  002018A99D169D {Heizung Gästebad}  INT0000010 {Heizung Gästebad Gruppe}  002018A99EBF6F {Heizung Kleiderzimmer}  INT0000006 {Heizung Kleiderzimmer Gruppe}  002018A99EB3DD {Heizung Küche}  INT0000007 {Heizung Küche Gruppe}  002018A99D1D9F {Heizung Schlafzimmer}  INT0000005 {Heizung Schlafzimmer Gruppe}  INT0000008 {Heizung Wohn-Esszimmer Gruppe}  002018A9975F7C {Heizung Wohnzimmer Links}  002018A99D3641 {Heizung Wohnzimmer Rechts}  BidCoS-RF {HM-RCV-50 BidCoS-RF}  001F58A9A70897 {HmIP-RCV-50}  LTK0050680 {Lichtschalter Keller}  PEQ1922824 {Lichtschalter Küche}  PEQ2181344 {Lichtschalter Schlafzimmer}  LTK0050467 {Lichtschalter Schlafzimmer Tür}  000A58A990F80C {Rauchmelder Büro}  000A5A499872DB {Rauchmelder Dachgeschoss Flur}  000A58A990F926 {Rauchmelder Esszimmer}  000A5A49987442 {Rauchmelder Flur Oben}  000A5A49A04C67 {Rauchmelder Flur Unten}  000A5A49A04D93 {Rauchmelder Gästebad}  000A58A990F947 {Rauchmelder Keller}  000A5A49A04C4C {Rauchmelder Kleiderzimmer}  000A5A499875CF {Rauchmelder Wohnzimmer}  00099A499041A5 {Schlüsselanhänger Janis}  CUX2801001 {SonOff-Basic}  000218A9ABB9BC {Steckdose Luftbefeuchter}  0001D3C99C8A81 {Steckdose Serverschrank}  0001D3C99C8CBE {Steckdose Waschmaschine}  HU-Dimmable 01 {Stehlampe Esszimmer}  HU-Dimmable li {Stehlampe Wohnzimmer}  000E5A498E1124 {Temperatursensor DG}  000E5A498E112C {Temperatursensor Keller}  000A9A499F57CC {Thermostat Bad}  000A9A4996ABBC {Thermostat Küche}  000313C9933CAA {Thermostat Wohn-Esszimmer}  CUX2801002 {TP-Link-HS100/110}  0000DA498D18DB {Türkontakt Garagentor}  OEQ1982106 {Türkontakt Haustür}  0000DA498D3F56 {Türkontakt Kellertür}  0000DA498D4780 {Türkontakt Terassentür}  HU-Philips hue {VIR-HUE-GTW HU-Philips hue}  QEQ0052414 {Vor -und Rücklaufsensor}  0017D709AE2CAE {Wetterstation}

**Comment by jens-maus** [comment]
@Kryzon Danke. Das besagte Gerät scheint jedoch im devnames Array mit drin zu sein:

```
000A5A49987442 {Rauchmelder Flur Oben}
```

Komisch. Die Frage wäre also warum das bei dir trotzdem schiefgeht wenn du die devconfig.cgi versuchst aufzurufen.

Ich hab aber mal eine Änderung in der devconfig.cgi vorgenommen (siehe c575651) die den Absturz verhindern sollte. Bitte entweder den nächsten nightly experimental build verwenden oder die oben referenzierte Anpassung auf die devconfig.cgi anwenden und testen.
