### ISSUE TITLE
ReGaHss: Stdin parameter for system.Exec

### ISSUE THREAD

**Issue by mdzio** [jens-maus/RaspberryMatic#847]
**Is your feature request related to a problem? Please describe.**

Passing larger data (e.g. JSON documents) to child processes using system.Exec() as command line parameters is time-consuming and error-prone. Usually, the tools also support reading data via standard input.

**Describe the solution you'd like**

system.exec() should be extended by a third parameter of type string to serve the standard input of the started process.

**Describe alternatives you've considered**

Using the echo command together with pipes is much more complex.

**Additional context**

For a better usability, #848 would be helpful.

**Comment by jens-maus** [comment]
Please provide an example use case with some `system.Exec()` execution how you suggest it should be.

**Comment by mdzio** [comment]
Example:
```
string in="{\"a\": 123,\"b\": \"c\"}";
string out;
string err;
system.Exec("curl -d @- http://a/b", &out, &err, in);
```

**Comment by jens-maus** [comment]
@mdzio Ok, now I get the point. I will see if I can implement that in some backward compatible fashion. But please note that as a workaround you can of course also do something like:

```
string in="{\"a\": 123,\"b\": \"c\"}";
string out;
string err;
system.Exec("echo \"" # in # "\" | curl -d @- http://a/b", &out, &err);
```

And BTW: For a JSON structure you should anyway use the `'` character for quotation. Thus, your "in" string definition should look like:

```
string in="{'a': 123,'b': 'c'}";
```
This should then solve or make your quotation mess a little bit easier.

**Comment by mdzio** [comment]
Thanks for the tips, but still the feature would help a lot. Now I wouldn't know how to send multiple lines (separeted by new line character) to the standard input.

**Comment by jens-maus** [comment]
Please note, that starting with ReGaHss R1.00.0388.0223 and newer this had been implemented now and a default stdin can now be specified using an optional 4th parameter to `system.Exec()`.
