### ISSUE TITLE
Skript Editor Fehler

### ISSUE THREAD

**Issue by TimR36** [jens-maus/RaspberryMatic#849]
Der WEB UI Skript Editor hat einen Fehler.
Wenn man das Zeichen "^" als Text setzt und auf OK & Speichern drückt, wird das Skript nicht gespeichert und geht anschließend immer auf die letzte Version zurück.

**Comment by jens-maus** [comment]
Nein, der Editor ist i.O. Das `^` zeichen ist ein besonderes zeichen in der ReGa Skriptsprache. Siehe dazu #225
