### ISSUE TITLE
HmIP-WRCD statt Pegel wird ein Spannungswert angezeigt in der Geraeteuebersicht

### ISSUE THREAD

**Issue by jogicom** [jens-maus/RaspberryMatic#850]
**Describe the bug**
Bei dem Gerät HmIP-WRCD wird in der Geräteübersicht statt des Pegels ein Spannungswert ausgegeben

**To Reproduce**
1. Go to 'Einstellungen'
2. Click on 'Geräte'
3. Scroll down to 'Device HmIP-WRCD '

**Screenshots**
![SpannungStattPegel](https://user-images.githubusercontent.com/25620021/83925719-28325700-a788-11ea-8936-3587f02cf84f.PNG)

**System information :**
 - Version [3.51.6.20200420]
 - Hardware [RaspberryPi3B]

**Comment by jens-maus** [comment]
Das ist kein Bug. Es werden nicht immer beide RSSI Pegel angezeigt/dargestellt. Je nachdem ob das Gerät in letzte Zeit gesendet/empfangen hat und der RSSI Pegel in die jeweilige Richtung der CCU/RaspberryMatic bekannt ist wird dieser dargestellt, oder eben nicht.

**Comment by jogicom** [comment]
OK! Danke für die Info!
