### ISSUE TITLE
Support F2FS als Boot Medium

### ISSUE THREAD

**Issue by ProfDrYoMan** [jens-maus/RaspberryMatic#851]
Hi,

In anderen Raspi Systemen stirbt mir regelmäßig immer mal wieder eine SD-Karte (kein billiger Kram).

F2F2 sollte das etwas verbessern. Es ist auf externen Laufwerken schon möglich. Kann man das auch (wahlweise) als default für root bekommen?

**Comment by jens-maus** [comment]
Nein, kann man nicht. Das würde an vielen Stellen eine generelle Änderung notwendig machen. Und für das rootfs ist das ja auch nicht notwendig da immer read-only. Wenn jemand aber gerne F2FS einsetzen will kann er natürlich gerne einfach mal probieren für /usr/local das selbst in Betrib zu nehmen und darunter laufen zu lassen. Ob das was hilft kann ich aber schwer sagen.

**Comment by ProfDrYoMan** [comment]
Stimmt, root ist RO, das hatte ich gar nicht bedacht. Dann ist der Nutzen gering.

**Comment by mkninc** [comment]
Habe das bei mir seit einiger Zeit so am laufen, also /usr/local als F2FS.

Wird die /etc/fstab bei einem Update überschrieben?

Wenn dem so ist, gäbe es dort zwei kleine Problem zu lösen.
 - Das Dateisystem wird fest vorgegeben, als ext4. Könnte man lösen durch Angabe von auto.
 - Zum anderen wird die Option data=journal nicht von F2FS unterstützt. Bei ext4 werden dadurch die Daten immer doppelt geschrieben. Erst ins Journal und dann nochmal normal ins Dateisystem. Bei F2FS ist das nicht nötig, da es ein Copy-On-Write Dateisystem ist.

**Comment by Baxxy13** [comment]
> seit einiger Zeit so am laufen, also /usr/local als F2FS.

Interessant. Meine Speichermedien (Stick / SSD) laufen auch schon seit Ewigkeiten mit F2FS.
Wie bekommt man denn das userfs umformatiert?

**Comment by mkninc** [comment]
> Wie bekommt man denn das userfs umformatiert?

Geht aktuell nur durch manuelles umformatieren.
Also Inhalt der User Partition sichern, neu formatieren als F2FS und Daten zurückschreiben.
Darauf achten, beim formatieren das Label 'userfs' wieder zu setzen.

**Comment by Baxxy13** [comment]
Hatte das mal testweise so umgesetzt.
Im normalen Betrieb läuft das soweit problemlos.
```
root@RM-Test-Pi3Bplus-27:~# blkid
/dev/mmcblk0p3: LABEL="userfs" UUID="fac4b08a-5b48-4c86-8cae-17c824e6ab7b" BLOCK_SIZE="4096" TYPE="f2fs" PARTUUID="deedbeef-03"
/dev/mmcblk0p1: SEC_TYPE="msdos" LABEL_FATBOOT="bootfs" LABEL="bootfs" UUID="FFF6-433C" BLOCK_SIZE="512" TYPE="vfat" PARTUUID="deedbeef-01"
/dev/mmcblk0p2: LABEL="rootfs" UUID="fcc5402c-f6cd-4710-89e4-a416c692f646" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="deedbeef-02"
/dev/zram0: UUID="fce163d6-789d-4324-9c24-4ad7be357453" TYPE="swap"

```
Jetzt ist mir aber aufgefallen das kein Zentralenupdate möglich ist. 
Lädt man das Update über die WebUI hoch startet das System anschließend ganz regulär (ohne upzudaten) neu.
Versuche ich "Neustart im Recovery Modus" wird auch normal rebootet (kein Recovery).
Erzwinge ich das Recovery (Taste auf RPI-RF-MOD) komme ich zwar ins Recovery, aber auch dort klappt ein Update nicht.

Irgendwo hakelts da noch oder ich habe was falsch gemacht.

**Comment by jens-maus** [comment]
> Jetzt ist mir aber aufgefallen das kein Zentralenupdate möglich ist.

Kann gut sein das an verschiedensten Stellen bei den Updateroutinen im Recovery-System explizit davon ausgegangen wir das die userfs partition auch via ext4 formatiert ist. Das müsste man erst einmal analysieren um zu ermöglichen das das userfs auch ein anderes Dateisystem haben kann. Würde ich als "nice-to-have" ansehen - kannst aber gerne dazu ein extra ticket/issue dazu aufmachen und dann kann ich mir das bei Gelegenheit gerne mal anschauen um dann eine Aussage zu treffen inwieweit es wirklich praktikabel/sinnvoll ist das umzusetzen.
