### ISSUE TITLE
HmIP-BROLL wird in NodeRed nicht gefunden

### ISSUE THREAD

**Issue by franksto** [jens-maus/RaspberryMatic#852]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
 - Version [e.g. RaspberryMatic 3.37.8.20180922]
 - Hardware [e.g. RaspberryPi3, TinkerboardS, etc.]

**Additional context**

Hi zusammen,

nach erfolgreicher Testeinbindung eines HmIP-BROLL wollte ich noch ein paar mehr meiner Rolladen einbinden, nur leider bekomme ich in Node-RED den neuen HmIP-BROLL warum auch immer nicht angezeigt.

HmIP-BROLL installiert, Gerät auf meinem Raspberrymatic angelernt (FW: 3.51.6.20200420), Kalibrierfahrt gemacht, lässt sich auch vom Web-UI bedienen alles gut.

Gehe ich nun in mein Node-RED und will mir einen Channel in einen Value Node mappen, finde ich auf Teufel komm raus den neuen HmIP-BROLL nicht gelistet, auch manuelles eintippen mag er einfach nicht.

Node-RED: 1.06, node-red-contrib-ccu 3.2.0
Node-RED läuft auf einem anderen Board nicht dort wo der Raspberrymatic läuft.

Es werden alle Devices gefunden, nur der neue HmIP-BROLL nicht.

Topic: ${CCU}/${Interface}/${channel}/${datapoint}
Interface: HmIP-RF

weder per Suche unter Devices ist er da, noch per Eingabe der SGTIN in den Channel, nicht ein einziger Kanal von dem Device ist sichtbar.

Zwischenzeitlich:
- raspberrymatic komplett neu installiert, Backup eingespielt - gleiches Spiel - alles geht nur die zwei neuen BROLL nicht - hat sich irgendwas an deren Hardware geändert? Die FW ist auf allen drei 1.6.2 - einer geht, die anderen beiden neueren sind nicht in Node-Red sichtbar...

weitere Beobachtung:

Wenn ich Redmatic auf dem raspberrymatic installiere - sehe ich die neuen HM-BROLLs in Node-Red, also lokal auf dem gleichen Board wo raspberrymatic läuft.

Das Node-Red auf dem separaten Board, sieht die neuen HM-BROLLS aber nicht - anscheinend zieht sich das Node-Red auf dem separaten Board nicht die aktuelle Device-Liste vom raspberrymatic.

Irgendjemand eine Idee, z.B. irgendein Cache in Node-Red löschen oder irgendwas anderes um ein Update zu erzwingen?

**Comment by franksto** [comment]
und noch einen Schritt weiter:

habe nun ein drittes Device aktiviert mit raspberrymatic drauf, d.h.
- Device 1: raspberrymatic mit NodeRed und mit allen meinen Homatic Komponenten inklusice 1 neuen HM-BROLL
- Device 2: nur NodeRed
- Device 3: zweiter rasberrymatic mit nur einem neuen HM-BROLL angelernt

Status jeweils aus Node-Red heraus:
Device 2:
Kann den HM-BROLL von Device 3 nicht finden.
Kann alles bis auf den neuen HM-BROLL von Device 1 finden
-> Das Device zieht sich irgendwie nicht alle Devices, insbesondere die zwei neuen HM-BROLL

Device 1 (Redmatic)
- Kann vom lokal raspberrymatic alles finden inklusice dem HM-BROLL
- Findet ebenfalls den neuen separierten HM-BROLL von Device 3

Unterschiede:
NodeRed device 2:
node-red 1.0.6
node-red-contrib-ccu 3.2.0

NodeRed device 1:
node-red 1.0.5
node-red-contrib-ccu 3.1.4

Ergo:
- raspberrymatic scheint in Ordnung (v 3.51.6.20200420)
- Entweder ist ein BUG in node-red-contrib-ccu 3.2.0 oder in node-red 1.0.6

**Comment by jens-maus** [comment]
Tut mir leid, aber du bist hier im falschen GitHub Projekt. Hier geht es rund um die Entwicklung bzgl. RaspberryMatic und nicht NodeRed, RedMatic oder node-red-contrib-ccu. Und du beschreibst ja selbst das das Gerät problemlos in RaspberryMatic selbst geht, nur eben nicht in RedMatic/NodeRed. Ergo, gehört das Issue auch an RedMatic gemeldet und nicht RaspberryMatic.
