### ISSUE TITLE
[3.51.6.20200420-621] WLAN funktioniert nicht RPI3

### ISSUE THREAD

**Issue by pr3mi3r3** [jens-maus/RaspberryMatic#853]
**Describe the bug**
Mein RaspberryPi3 mit der RaspberryMatic 3.51.6.20200420-621 verbindet sich nicht mehr mit meinem WLAN. Das Device ist nur noch per LAN erreichbar. 
Mit der Vorversion RaspberryMatic 3.51.6.20200229 funktioniert mein WLAN wieder. 
Ich bin also wieder zurück auf die Version 3.51.6.20200229.

**To Reproduce**
An der Konfiguration wurde nichts angepasst. Nach dem Update auf RaspberryMatic 3.51.6.20200420-621 funktioniert das WLAN nicht mehr.
Mit der alten Version 3.51.6.20200229 funktioniert die WLAN Verbindung wieder.

**Expected behavior**
Das Device sollte sich beim Booten automatisch mit meinem WLAN verbinden.

**System information (please complete the following information):**
 - Version: RaspberryMatic 3.51.6.20200420-621
 - Hardware: RaspberryPi3

**Comment by jens-maus** [comment]
Existiert dieses Problem noch mit der aktuellen 3.51.6.20200613 Version?

**Comment by pr3mi3r3** [comment]
Ja das Problem auch bei der aktuellen RaspberryMatic-3.51.6.20200621-rpi3

**Comment by jens-maus** [comment]
@pr3mi3r3 Um hier irgendetwas zu "fixen" müsste bitte mehr Infos gegeben werden. Welche WLAN Hardware wird verwendet (onboard WLAN oder USB-WLAN Stick?). Zu welchen Fehlermeldungen kommt es in `/var/log/messages` und wie sieht die wpa supplicant konfiguration aus?

**Comment by pr3mi3r3** [comment]
Ich benutze das onboard WLAN, hier das log.
Anscheinend wird der Treiber nicht mehr korrekt geladen:

Jul  6 14:52:56 localhost user.err kernel: [    9.827364] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
Jul  6 14:52:56 localhost user.info kernel: [    9.827555] usbcore: registered new interface driver brcmfmac
Jul  6 14:52:56 localhost user.warn kernel: [    9.848851] **brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43430-sdio.raspberrypi,3-model-b.txt failed with error -2**
Jul  6 14:52:56 localhost user.err kernel: [   10.041839] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
Jul  6 14:52:56 localhost user.err kernel: [   10.052206] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM43430/1 wl0: May  2 2019 02:39:18 version 7.45.98.83 (r714225 CY) FWID 01-e539531f
Jul  6 14:53:09 localhost daemon.warn /usr/sbin/irqbalance: Daemon couldn't be bound to the file-based socket.
Jul  6 14:53:09 localhost user.notice rfkill: block set for type bluetooth

**Comment by pr3mi3r3** [comment]
Mit neuer RaspberryMatic Version läuft es wieder
