### ISSUE TITLE
CCU -> RaspMatic

### ISSUE THREAD

**Issue by detLAN** [jens-maus/RaspberryMatic#854]
CCU wurde fast über all in RaspMatic umbenannt. In den Netzwerkeinstellungen gibt es noch ein verwaistes CCU - Zertifikat von der CCU löschen.

**Comment by jens-maus** [comment]
RaspMatic = CCU

**Comment by detLAN** [comment]
Das ist mir schon klar, nur hast Du Dir ja die (unnötige) Mühe gemacht an allen anderen Stellen dies umzubenennen. Aber okay, der Ton, in diesem Fall die Antwort, macht die Musik. Ich wollte nur nett sein.

**Comment by jens-maus** [comment]
Nein, ich hab das nicht an allen Stellen manuell umbenannt. Es gibt stattdessen eine Datei da steht definitionen für den Namen drin und die hab ich angepasst. Siehe

https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0001-RaspberryMatic.patch#L537-L542

Und wenn das jetzt aber nicht zu 100% alles andeckt liegt das nicht daran das ich eins vergessen habe, sondern das eQ3 hier anscheinend der Meinung war das man das anders benennen möchte. Und ehrlich gesagt ist RaspberryMatic trotzdem eine CCU und insofern sehe ich das als nicht so tragisch an wenn hier/da auch noch von "CCU" die Rede ist.

Und das hier hat auch nichts mit "Der Ton macht die Musik" zu tun. Das ist ein Ticket/Issue system und kein Diskussionsforum. Also tschuldigung wenn ich dir auf den Schlipps getreten bin, das war nicht meine Absicht.
