### ISSUE TITLE
Neue Firmware 3.51.6.20200613

### ISSUE THREAD

**Issue by herbylfs** [jens-maus/RaspberryMatic#858]
Nach der Installation gibt es eine Alarmmeldung des Watchdog.
![start](https://user-images.githubusercontent.com/40141478/84685752-10eb2a80-af3b-11ea-8b0c-af82fcf98c2f.JPG)
![alarm](https://user-images.githubusercontent.com/40141478/84685763-15afde80-af3b-11ea-9d2d-24a15219a3e6.JPG)
Wo kann mann den Wert korrigieren?.
mfg
herby

**Comment by Newbie-2** [comment]
Das hatte ich bei der aktuellen Version auch erstmalig ?
Aber schon nach kurzer Zeit, oder einem Neustart liegen die Temperaturwerte wieder in normalen Bereich. Vielleicht werden nach der Erstinstallation einmalig viele Daten verarbeitet, die für die Erhöhung der CPU Temperatur sorgen. Seit einem Tag läuft die neue Firmware bei mir ohne weitere Temperatur Auffälligkeiten.

**Comment by jens-maus** [comment]
Das Problem ist bereits bekannt und wurde auch schon für die nächste kommende Version in Commit 2ff3642d7f97fbf4db93b19b0825e2bcd39797ab von mir repariert.

**Comment by Newbie-2** [comment]
Super Jens und Wahnsinn wie schnell Du immer bist !!!
