### ISSUE TITLE
Super string ^ escaping fehlerhaft in 3.51.6.20200613

### ISSUE THREAD

**Issue by HMMike** [jens-maus/RaspberryMatic#859]
**Describe the bug**
In der Aktuellen Raspberrymatik version wurde die String Master quote funktion mit dem ^ fehlerhaft implementiert. Es ist nicht mehr möglich, den Backslash in einem String zu verwenden, dieser wir mit interpretiert obwohl das ^keinerlei interne Interpretation durchführen sollte

**To Reproduce**
```
string s="abcd\zui";
s=s.Replace(^\^,^\\^);  
WriteLine(s);  
```

führt in der aktuellen Version z ueinem Scriptruntime Error,

in alen Vorgängerversionen wird im dem teststring richtigerweise das 
`abcd\zui` zu einem `abcd\\zui` ersetzt

**Expected behavior**
Diese Fehlfunktion verhindert das ersetzen eines einfachen Backslashes in einen Doppelbackslah

**Screenshots**

**System information (please complete the following information):**
 - 3.51.6.20200613
 - PI3

**Additional context**

**Comment by jens-maus** [comment]
Wird mit der kommenden ReGa Version R1.00.0388.0219 wieder behoben sein.

**Comment by libertyx82** [comment]
Ich habe ein Problem, was wie ich vermute, durch diese Änderung verursacht wird

Ich nutze in einem Script den folgenden Aufruf

`string cmd = "/bin/sh -c 'cat /etc/config/energyPrice|sed -r \"s/\\"//g\"'";`

Seit der Version 3.51.6.20200621 wird das Script mit folgendem Fehler abgebrochen

`SyntaxError: Error 1 at row 24 col 71 near ^g\"'"; `

**Comment by jens-maus** [comment]
@libertyx82 
Das problem ist die falsche `\\"` sequenz in dem string. In der alten Rega ergibt das `\"` in der neuen fehlt aber ein zusätzliches backslash. Das war leider vorher ein Bug. Ich empfehle am besten das dritte backslash hinzuzufügen oder noch besser stattdessen eine raw/super string zu verwenden, dann fällt auch das backslash quoting komplett weg und es ist dann rückwärtskompatibel. Also so z.B.

```C++
string cmd = ^/bin/sh -c 'cat /etc/config/energyPrice|sed -r "s/\"//g"'^;
```
