### ISSUE TITLE
Servicemeldungen lassen sich nicht löschen

### ISSUE THREAD

**Issue by Rolfhartmut** [jens-maus/RaspberryMatic#86]
Nach "Bestätigen" bleibt die Servicemeldung (Kommunikation gestört) aktiv (Raspi3 mit aktuellem Version 2.27.7)

**Comment by jens-maus** [comment]
Dies ist kein RaspberryMatic spezifisches Problem sondern wohl ein Problem in der generellen CCU Firmware ab 2.27.7. Siehe https://homematic-forum.de/forum/viewtopic.php?f=34&t=36269
