### ISSUE TITLE
Standard-Systemvariablen werden ohne Funkmodul nicht korrekt bei einer frischen Installation angelegt

### ISSUE THREAD

**Issue by MathiasJZ** [jens-maus/RaspberryMatic#861]
Wenn man eine neue Installation hat, sieht man die Systemvariablen Anwesenheit, Alarmmeldungen und Alarmzone 1 nicht.
Könnte man die Systemvariablen beim ersten Start nicht sichtbar machen?
Das betrifft nur Nutzer, die die RM neu aufsetzen müssen und kein Backup haben.
In meinem Fall stehe ich kurz vor einem Umzug. Ich möchte natürlich kein Backup einspielen, in dem schon Altlasten (Dateileichen) liegen.

**Comment by Baxxy13** [comment]
Ich habe die Sache analysiert und es hat sich herausgestellt das das Phänomen auftritt wenn beim ersten Start von RaspberryMatic kein Funkmodul angeschlossen ist.
Kurz gesagt: 
- die beiden SysVars "Anwesenheit"(ID 950) & "Alarmzone 1"(ID 1235) werden gar nicht erstellt.
- die anderen beiden SysVars "Alarmmeldungen" & "Servicemeldungen" sind auch nicht vorhanden, stattdessen hat jetzt eine SysVar Namens "Gateway-SysAlDP" die ID 40 und eine SysVar Namens "Gateway-SysSrvDP" die ID 41. 

Ein bisschen ausführlicher habe ich es im Homematic-Forum beschrieben. [https://homematic-forum.de/forum/viewtopic.php?f=65&t=59427&p=589769#p589769](url)

Testsystem: RaspberryMatic 3.51.6.20200621 als ova-Version unter VirtualBox auf einem Windows PC.

Grüße
Baxxy

**Comment by jens-maus** [comment]
Danke für die Info. In der Tat hatte ich das auch schon vermutet und soweit ich mich schwach erinnere auch einmal so selbst erlebt aber nie entsprechend dokumentiert.

**Comment by MathiasJZ** [comment]
Ich habe es nochmal mit/ohne alten Funkmodul getestet. 
Mit Funkmodul waren die SysVar da, ohne jedoch nicht, was für mich keinen Sinn ergibt.
Wenn man nur HMw-Komponenten hat, braucht man das Funkmodul ja nicht. Bei HMIPw sieht es dann wieder anders aus.
Gruß,
Mathias

**Comment by jp112sdl** [comment]
Offensichtlich wird die SV `DutyCycle` angelegt, bevor `hm_autoconf` läuft.

Bei der Prüfung, [ob keine SV existiert](https://github.com/eq-3/occu/blob/master/WebUI/bin/hm_autoconf#L538), wird die Bedingung nicht erfüllt und die Standard-Variablen werden nicht angelegt.

Wenn man die SV `DutyCycle` löscht _und schneller ist, als das DC Skript, das diese SV wieder anlegt 🤓_ , anschließend `/bin/hm_autoconf` aufruft, werden auch die Standard-SV angelegt.

Das Anlegen der SV `DutyCycle` ohne Vorhandensein eines Funkmoduls ist auch eigentlich nicht notwendig, oder?

_Warum das Problem überhaupt nur auftritt, wenn kein Funkmodul angeschlossen ist, verstehe ich grad noch nicht. Ist es evtl. eine race condition?_

**Comment by jens-maus** [comment]
@jp112sdl Danke für die Analysen. Das hört sich in der Tat fishy an. Denn nicht ohne grund starte ich den cron daemon eigentlich als letzten Dienst und da sollte die ReGa doch schon längst das `hm_autoconf` aufgerufen und abgearbeitet haben.

Und deine Hinweise sind natürlich korrekt. updateDCVars sollte zumindest nur dann aktiv werden wenn es bereits Standard-variablen wie Anwesenheit, etc. gibt. Aber warum jetzt hm_autoconf nicht korrekt die standardvariablen anlegt. Das muss ich mir noch einmal im Detail anschauen. Danke für den Tipp.

**Comment by alexreinert** [comment]
Nachdem mich das Problem in ähnlicher Weise jetzt auch bei debmatic betrifft, habe ich mal etwas genauer geforscht.
Mit ist nicht klar, weshalb die Systemvariablen, Räume und systeminternen Funktionen erst über die hm_autoconf angelegt werden. Ich würde vermuten, dass der Teil besser in der hm_startup aufgehoben wäre. Da ich aber nicht in den Code der Rega schauen kann, fehlt mir die Info, ob hm_startup erst aufgerufen wird, wenn die Rega komplett initialisiert ist, oder ob da ggf. noch Code innerhalb des Rega Binaries ausgeführt, bevor man von einer kompletten Initialisierung sprechen kann. @jens-maus Könntest du das mal prüfen?
Wenn nichts dagegen spricht würde ich sonst einen Teil des Codes von der hm_autoconf rüberziehen in die hm_startup. PR könnte ich dafür dann auch einen machen.

**Comment by alexreinert** [comment]
Habe einen Fix mit #1021 eingekippt.
