### ISSUE TITLE
Firewall missachtet Portfreigaben nach Neustart

### ISSUE THREAD

**Issue by Kerschten** [jens-maus/RaspberryMatic#862]
**Describe the bug**
Nach jedem Neustart missachtet die Raspmatic in meinem Fall die Freigabe des Ports 501 für die Kommunikation mit meiner Heizung via Modbus. Ich muss daher nach jedem Neustart die Firewall Einstellungen öffnen, ein Leerzeichen vor dem Port 502 entfernen und schließen. Danach wieder die Firewall Einstellungen öffnen und erneut schließen. Erst dann funktioniert die Kommunikation zur Heizung wieder. 

**Expected behavior**
Ein einmal freigegebener Port sollte auch nach einem Neustart noch freigegeben sein.

**System information (please complete the following information):**
 - Version 3.51.6.20200613
 - Hardware RPi3

**Comment by jens-maus** [comment]
Kannst du bitte einen detaillierten Screenshot deiner Firewall-Einstellungen hier zeigen wie die aussehen WENN es funktioniert und ein Screenshot wie diese nach dem Neustart aussehen BEVOR du das leerzeichen entfernst?

Auch bitte den Inhalt der Datei `/etc/config/firewall.conf` hier zeigen.

**Comment by Kerschten** [comment]
Das kuriose ist, dass die Einstellungen in beiden Fällen genau gleich sind. Daher auch jeweils nur ein Bild.

![grafik](https://user-images.githubusercontent.com/64777869/85942436-91d9f700-b929-11ea-96d7-f56cb246cbe7.png)
![funktioniert](https://user-images.githubusercontent.com/64777869/85942826-1d548780-b92c-11ea-9922-5a2009a92381.JPG)

**Comment by jens-maus** [comment]
Ich kann hier leider keinen Fehler erkennen. Auch ein eigener Test auf einer Testzentrale zeigt das der Port 502 nach dem Booten korrekt von der Firewall freigegeben. Dazu kann man folgendes Kommando verwenden:

```sh
root@homematic-raspi:~# iptables -L -n -v | grep :502
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:502 state NEW
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:502
```

Was man hieran erkennen kann ist, das der Port 502 hier korrekt aufgelistet wird und folglich dann auch freigegen sein sollte.

Des Weiteren kann man dann mittels des folgenden Kommandos aus RaspberryMatic einen Dienst auf Port 502 starten:
```sh
root@homematic-raspi:~# nc -l -p 502
```

Und dann führt man auf einem anderen Host das folgenden `nmap` kommando aus und sieht das der Port definitiv offen ist nach einem frischen Reboot:
```sh
$ nmap -p 502 192.168.X.X
Starting Nmap 7.80 ( https://nmap.org ) at 2020-06-30 15:48 CEST
Nmap scan report for XXX (192.168.X.X)
Host is up (0.00077s latency).

PORT    STATE SERVICE
502/tcp open  mbap

Nmap done: 1 IP address (1 host up) scanned in 0.03 seconds
```

Die Frage wäre also ob nicht ggf. einfach die Anwendung die auf den Port 502 hört ggf. ein Problem damit hat das ggf. während des boot vorganges der Port noch nicht komplett freigeschalten ist, sondern dies erst am schluss passiert. Die Frage wäre also wer steckt hinter Port 502 auf der RaspberryMatic?!? Und kann es ggf. daran liegen?!?

Ein prinzipielles Problem kann ich hier aber definitiv nicht erkennen. Daher bitte das hier gezeigte einmal nachspielen und selbst analysieren.

**Comment by Kerschten** [comment]
Vielen Dank für deine Tipps und die Versuche.
Tatsächlich funktioniert bei mir nach einem Neustart bereits der o.g. iptables Befehl nicht, bzw. es wird kein Ergebnis ausgegeben. Wenn ich dann allerdings auf der WebUI die Firewall Einstellungen öffne und wie oben beschrieben das Leerzeichen entferne und mit OK bestätige, kann der Befehl wieder ausgeführt werden und ergibt das gleivhe Ergebnis wie bei dir.
Hier der Screenshot dazu:

![grafik](https://user-images.githubusercontent.com/64777869/86168636-c8299900-bb18-11ea-9517-e3932134cfd1.png)

**Comment by jens-maus** [comment]
Das ist in der Tat sehr komisch. Dann verrate mal bitte was zu deiner Netwerkanbindung? Ist RaspberryMatic via LAN oder WLAN angebunden? Auch bitte mal den Inhalt der Datei `/var/hm_mode` hier zeigen. Und beim Hochfahren bitte mal einen HDMI Monitor + Tastatur anschliessen, dann ALT+F2 beim hochfahren drücken und dort dann mal zeigen was beim Punkt `Starting network...` so ausgegeben wird bei dir.

**Comment by Kerschten** [comment]
RaspberryMatic ist via LAN angebunden.

Hier der Inhalt von /var/hm_mode. Den Rest muss ich nachliefern:

`
HM_HMIP_ADDRESS='0x4702a6'
HM_HMIP_DEV='HM-MOD-RPI-PCB'
HM_HMIP_DEVNODE='/dev/raw-uart'
HM_HMIP_SERIAL='NEQ0231441'
HM_HMIP_SGTIN='3014F711A061A7D5698CF011'
HM_HMIP_VERSION='2.8.6'
HM_HMRF_ADDRESS='0x4702a6'
HM_HMRF_DEV='HM-MOD-RPI-PCB'
HM_HMRF_DEVNODE='/dev/raw-uart'
HM_HMRF_SERIAL='NEQ0231441'
HM_HMRF_VERSION='2.8.6'
HM_HOST='rpi3'
HM_HOST_GPIO_RESET='18'
HM_HOST_GPIO_UART='/dev/raw-uart'
HM_LED_GREEN='/sys/class/leds/led0'
HM_LED_GREEN_MODE1='mmc0'
HM_LED_GREEN_MODE2='heartbeat'
HM_LED_RED='/sys/class/leds/led1'
HM_LED_RED_MODE1='timer'
HM_LED_RED_MODE2='mmc0'
HM_LED_YELLOW=''
HM_LED_YELLOW_MODE1='none'
HM_LED_YELLOW_MODE2='none'
HM_MODE='NORMAL'
HM_RTC=''
`

**Comment by jens-maus** [comment]
Ok, in der Datei sehe ich nichts unauffälliges. Dann bitte in der Tat mal Monitor+Tastatur anschliessen und schauen was beim booten ausgegeben wird.

**Comment by Kerschten** [comment]
Ok, hier der Screenshot

![26E8142B-267E-4B17-B856-19A3A83BEFD1](https://user-images.githubusercontent.com/64777869/86402424-16bb6c80-bcac-11ea-93e5-7bb811f75c4b.jpeg)

**Comment by jens-maus** [comment]
Ok, noch komischer. Da steht ja explizit `firewall` und das wird nur ausgegeben wenn der `/bin/setfirewall.tcl` dann auch ausgeführt wird. Das einzige was du noch probieren kannst ist, einen frischen boot machen sodass port 502 wieder nicht freigegeben ist, dann via SSH einloggen und mal von hand `/bin/setfirewall.tcl` aufrufen und beobachten ob danach der port wieder freigeschalten. Auch bitte mal in `/var/log/messages` reinschauen ob da irgendwas bzgl. firewall zu finden ist denn der `/bin/setfirewall.tcl` skript sollte da drin was loggen.

**Comment by Kerschten** [comment]
Jetzt wird’s nochmal komischer. Um den PI an einen Bildschirm anzuschließen, musste ich ihn vom Strom nehmen und woanders aufbauen. Nun steht er wieder da, wo er immer stand und aktuell funktioniert die Kommunikation über Port 502 wieder - direkt nach einem Neustart, ohne mein Zutun. Da muss sich irgendwas aufgehangen haben?!?

 

Wenn ich nach dem Neustart /bin/setfirewall.tcl ausführe, wird nichts in /var/log/messages geschrieben. Aber da die Portfreigabe ja aktuell scheinbar funktioniert, ist das ja auch richtig so.

 

Von: Jens Maus [mailto:notifications@github.com] 
Gesendet: Donnerstag, 2. Juli 2020 21:42
An: jens-maus/RaspberryMatic <RaspberryMatic@noreply.github.com>
Cc: Kerschten <suschten@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [jens-maus/RaspberryMatic] Firewall missachtet Portfreigaben nach Neustart (#862)

 

Ok, noch komischer. Da steht ja explizit firewall und das wird nur ausgegeben wenn der /bin/setfirewall.tcl dann auch ausgeführt wird. Das einzige was du noch probieren kannst ist, einen frischen boot machen sodass port 502 wieder nicht freigegeben ist, dann via SSH einloggen und mal von hand /bin/setfirewall.tcl aufrufen und beobachten ob danach der port wieder freigeschalten. Auch bitte mal in /var/log/messages reinschauen ob da irgendwas bzgl. firewall zu finden ist denn der /bin/setfirewall.tcl skript sollte da drin was loggen.

**Comment by jens-maus** [comment]
This ticket has been closed because of inactivity of the ticket owner and due to the fact that no developer could reproduce the issue. Please reopen the ticket once it can be reproduced again or the ticket owner can reply accordingly.
