### ISSUE TITLE
RaspberryMatic-3.51.6.20200621 doesn't boot without HDMI connected

### ISSUE THREAD

**Issue by domotiquefacile** [jens-maus/RaspberryMatic#864]
**Describe the bug**
When updating from RaspberryMatic-3.51.6.20200420 to RaspberryMatic-3.51.6.20200621 on a Raspberry Pi 4 4GB, I cannot access the Raspberrymatic anymore (ping to the Raspberry doesn't even work, not even sure if it boots).
As soon as I connect the HDMI cable, it works normally.

I added hdmi_force_hotplug=1 to /boot/config.txt and now it boots normally without requiring the HDMI cable.

**To Reproduce**
Just try to boot with firmware RaspberryMatic-3.51.6.20200621

**Expected behavior**
Being able to ping the Raspberrmatic after boot

**System information (please complete the following information):**
 - Version RaspberryMatic-3.51.6.20200621
 - Hardware Raspberry 4 4GB with RPI-RF-MOD

**Comment by jens-maus** [comment]
Can you please show the output of the `vcgencmd bootload_version` command which in fact should indicate which latest bootloader you are using. In addition, please boot the lastest Raspbian/RaspberryPiOS version once so that the bootloader version gets updated and see if this might solve the issue without having to manually add the `hdmi_force_hotplug=1` workaround again.

**Comment by Baxxy13** [comment]
Just for Information:
My Raspberry Pi4B-2GB (Model: Raspberry Pi 4 Model B Rev 1.1) with bootloader 
`Apr 16 2020 18:11:26`
`version a5e1b95f320810c69441557c5f5f0a7f2460dfb8 (release)`
`timestamp 1587057086`
boots without problems into RaspberryMatic.
I have not connected an HDMI-Monitor and non `hdmi_force_hotplug=1` entry in /boot/config.txt

**Comment by domotiquefacile** [comment]
I updated to the latest bootloader:
```
Apr 16 2020 18:11:26
version a5e1b95f320810c69441557c5f5f0a7f2460dfb8 (release)
timestamp 1587057086
```
But it still fails to boot without HDMI.
The issue is quite early in the boot process; for instance with HDMI I can see the RPI-RF-MOD lighting up quite quickly (20 seconds after booting). But without HDMI, the RPI-RF-MOD is not lighting at all.
I got regular message about under-voltage though. Perhaps that's the issue. I will need to order a new power supply to confirm (but it is a bit strange as having HDMI is consuming more, so...).

**Comment by tlesmann** [comment]
I had the same issue after updating from ...420 to ...621 on a Raspberry Pi 4 4GB. System doesn't boot and was not pingable. The Led indicator was dark so I also assume that the boot had failed. Now I'm running the predecessor version ...613 which works well.

**Comment by Baxxy13** [comment]
> Now I'm running the predecessor version ...613 which works well.

That's clear. Because Version 3.51.6.20200613 has the enty: `hdmi_force_hotplug=1` in /boot/config.txt and Version 3.51.6.20200621 hasn't it.

**Comment by jens-maus** [comment]
Well, I really don't know why some Pi4 require `hdmi_force_hotplug=1`while some others (with the same bootloader version) obviously don't. Hence, I think I need to readd `hdmi_force_hotplug=1` for the next release until I find a better solution.

**Comment by domotiquefacile** [comment]
If it helps, my Raspberry is a Raspberry Pi 4 Model B Rev 1.2.

**Comment by jens-maus** [comment]
@domotiquefacile Thanks

Can the others which are also affected by the issue please show their `cat /proc/cpuinfo | tail -4` output.

**Comment by jens-maus** [comment]
As I do not have a `c03112` model at hand I cannot reproduce the issue anymore I am afraid and thus I readded the `hdmi_force_hotplug=1` workaround in config.txt so that all Pi4 models continue to work headless without any HDMI cable connected.
