### ISSUE TITLE
Web Interface: Not Found

### ISSUE THREAD

**Issue by jaschkopf** [jens-maus/RaspberryMatic#865]
**Describe the bug**
Web Interface is not reachable, SSH doesn't work, too. CCU seams to works normal, connection to ioBroker works, too. Network connection is ok (connected via cable to Fritzbox 7590, IP didn't change). Error occurs since updating to 3.51.6.20200613.

**To Reproduce**
1. Open webinterface over IP Adress (bookmarked) 
2. Webinterface is not reachable, only shows "Not Found". SSH connection doesn't work, too
3. After reboot (disconnect power) everything works for some while

**Expected behavior**
Webinterface should work normally 

**Screenshots**
<a href="https://abload.de/image.php?img=error4tjue.png"><img src="https://abload.de/thumb/error4tjue.png" /></a> <a href="https://abload.de/image.php?img=error29ak5n.png"><img src="https://abload.de/thumb/error29ak5n.png" /></a> 

**System information (please complete the following information):**
 - RaspberryMatic 3.51.6.20200621
 - Hardware RaspberryPi3 with RPI-RF-MOD

**Additional context**

**Comment by jens-maus** [comment]
Sorry, but I cannot see how this could be a general issue. Thousands of users are not having any issues including myself. IMHO this all sounds like a local issue on your network/end. So please perform additional investigations yourself as this definitly "worksforme" without any way to investigate on my end. In addition, please use the resources of the homematic forum to discuss your problems and potentially find a solution for it or to help you identify the root cause of the issue which thus might perhaps in the end indicate to a bug in RaspberryMatic but then with a much more verbose information than just "does not work".

In addition, please stop uploading screenshots to third-party services but directly include them here in the issue description. There is really no reason to upload such screenshots to third party sites which in fact just mainly show commercial advertising rather than simply the screenshot.

**Comment by bipson** [comment]
I have the same issue, usually once or twice a week.
And others too it seems:
[https://homematic-forum.de/forum/viewtopic.php?f=65&t=57875](https://homematic-forum.de/forum/viewtopic.php?f=65&t=57875)

The thread above indicates an issue with "corrupt" filesystems or SDCards. Unfortunately I think I already replaced the SDCard, once a few months ago and the issue remained. I cannot guarantee though that I completely replaced the card, nor that I had a fresh install and recreated from a backup, or if I just took an image...

I also already did a manual "badblocks -n" on the whole card using another PC and **no issues** were found.

The best thing I could currently do was pushing the logs to a remote host (see file attached). I don't know if that's enough...
[rm.log](https://github.com/jens-maus/RaspberryMatic/files/5868713/hm.log)


The issue appeared exactly at 02:00 or 03:00 (it seems klog and syslog have diverging time-zones or at least diverging clocks? This also can't be right). So it _seems_ to be related to a badblocks check, or something scheduled at that time least.

After that the log is just repetitive spam. Lot's of it.

But it also does not happen _every_ night, which is also weird (I don't know how often badblocks is started).

So I currently don't think it is really a bad sector on the SDCard that causes it, it rather seems something around the test failed and through cascading effects RM is unable to recover/remount the disk? Maybe it is an issue on the attached USB drive? Even if it is a bad sector, I don't think RM going into an unrecoverable state is the intended behavior?

Of course I could just try with a fresh installation, but I think maybe the error could be handled more gracefully by RM - if we could at least find out what causes it?

Please let me know if there is something else I could provide.

**Comment by bipson** [comment]
So, I reliably have this every week on Sunday night, which would suggest it is the badblocks check that triggers it.

So, just for posterity (if somebody stumbles upon this).

Googling for `mmc0: timeout waiting for hardware interrupt.` (see log above) yields a vast number of (mostly RPi related) issues and threads hunting for causes.

https://github.com/raspberrypi/linux/issues/2392
https://github.com/raspberrypi/linux/issues/3092
https://forums.xilinx.com/t5/Embedded-Linux/mmc0-Timeout-waiting-for-hardware-interrupt/td-p/1103158


Some reports also mention **badblocks** as trigger, but I did not find a cause. Updates or changes to boot parameters seem to be a remedy for some. Possible causes could be anything from bug in the SDCard driver, insufficient power supply (not in my case), boot parameters, etc. This could be anything.

In my particular case I have no clue how to continue besides aimlessly trying random stuff... Maybe attaching via serial modem and triggering it yields something *shrug*.

**Comment by rene-re** [comment]
Having the same issue. A power cycle fixes the issue for some time (days?).
