### ISSUE TITLE
Compatibility Problems with Raspberry Pi 4, 8GB?

### ISSUE THREAD

**Issue by ThomasLukasiewicz** [jens-maus/RaspberryMatic#866]
**Describe the bug**
Homematic RF teach-in mode could not be activated.

**System information (please complete the following information):**
 - RaspberryMatic 3.51.6.20200613 
 - Raspberry Pi 4, 8GB
 - HM-MOD-RPI-PCB

**Comment by jens-maus** [comment]
Nope, there is no compatibility issue with a Pi4/8GB. At least with my test hardware I could perfectly teach in BisCos-RF an HmIP with a Pi4/8GB without any issues. So this mist be a user issue an your side Iam afraid.

**Comment by ThomasLukasiewicz** [comment]
Hi, 

Thanks for your reply, however, one cannot really do anything wrong here:
-- RaspberryMatic 3.51.6.20200613 correctly installed and running 
-- original Raspberry Pi 4, 8GB (bought in the UK)
-- HM-MOD-RPI-PCB bought assembled from "technikkram.net"
-- the radio module is correctly fixed on the Pi

From the above, this looks like a bug in RaspberryMatic or an incompatibility problem with the 8GB Pi; log file below.

[homematic-raspi-2020-07-18.log](https://github.com/jens-maus/RaspberryMatic/files/4941759/homematic-raspi-2020-07-18.log)
.

**Comment by jens-maus** [comment]
Sorry, but again: With my Rpi4, 8GB I don't see any issue. So olease connect a HDMI Monitor and keyboard and while booting press Alt+F2 and monitor the bootup process especially when initializing the RF module and then send over the screenshot if there is an error shown.

**Comment by ThomasLukasiewicz** [comment]
The RF module is not found: 

![RM](https://user-images.githubusercontent.com/12201653/87855473-7e122700-c910-11ea-94b7-ad54aa85a0d3.png)

**Comment by jens-maus** [comment]
Well, then either the RF module is broken or the GPIO on the RPi4 or you have it wrongly attached. Show an image of the RF module attached where we can also see how it was assembled.

**Comment by ThomasLukasiewicz** [comment]
No, the RF module is perfectly attached: 
![screenshot_pi4](https://user-images.githubusercontent.com/12201653/87860008-a2cac680-c931-11ea-9f4e-8de533eaaaaf.png)

Besides hardware problems (which are extremely unlikely here), this can also very well be an incompatibility bug inside the software (RaspberryMatic, firmware on Pi, or firmware on RF module).

**Comment by jens-maus** [comment]
@ThomasLukasiewicz Sorry, but as said before all this works here for me and a lot of others. So I would suggest you try a different RaspberryPi and see if the issue still persists.
