### ISSUE TITLE
Reboot/Crash every day at the same hour

### ISSUE THREAD

**Issue by domotiquefacile** [jens-maus/RaspberryMatic#867]
**Describe the bug**
I have installed the latest RaspberryMatic-3.51.6.20200621 and now I can see that the system is rebooting everyday at 02:07 (CEST).
Perhaps it was also the case before, I don't know because the feature to detect the crash watchdog was only recently added (3.51.6.20200613).
As all the logs started from the reboot, I don't know what is happening or provoking the reboot.

**To Reproduce**
1. Wait one day, do nothing
2. System reboot at 02:07 CEST

**Expected behavior**
No reboot everyday

**System information (please complete the following information):**
 - Version RaspberryMatic-3.51.6.20200621
 - Hardware:
```
Hardware	: BCM2711
Revision	: c03112
Serial		: 1000000019702021
Model		: Raspberry Pi 4 Model B Rev 1.2
```

**Additional context**
RPI-RF-MOD module added to the Raspberry.

**Comment by jens-maus** [comment]
If your system is unexpectably booting every day at around 02:00 in the night then this points at the "bad block check" that is regularly executed every night to identify bad blocks on the used SD card. See the following crontab entry:

```
0 2 * * * [ ! -e /etc/config/NoBadBlocksCheck ] && /bin/nice /bin/checkBadBlocks.sh >/dev/null 2>/dev/null
``` 

Thus, this seems to point at a (perhaps slightly) broken SD card being used. So please go and use a new microSD card, flash a fresh RaspberryMatic on it and restore your latest backup. This should solve the issue.

**Comment by domotiquefacile** [comment]
I was a bit skeptical because I ran badblocks manually and didn't find any issue.
I also commented the badblocks cron job at 2am.
But still the Raspberry was rebooting everyday at 02:07.

However I ordered a new SD card as advised and now the problem is gone !
