### ISSUE TITLE
Hardwareunterstützung für NanoPi Hardware von FriendlyARM/FriendlyElec?!?

### ISSUE THREAD

**Issue by Wookbert** [jens-maus/RaspberryMatic#871]
Gibt es irgendeine Chance, dass die RaspberryMatic auf die teilweise sehr interessanten, weil kompakten, günstigen und je nach Modell recht leistungsstarken nanoPis von FriendlyARM/FriendlyElec portiert wird ... vorausgesetzt das 868 MHz-Modul passt von der Pin-Belegung her auf die GPIO-Leiste?

Z.B. der [NanoPi NEO3](https://www.friendlyarm.com/index.php?route=product/product&path=69&product_id=279&sort=p.price&order=ASC) ([Wiki-Seite](http://wiki.friendlyarm.com/wiki/index.php/NanoPi_NEO3)), oder der Raspberry-Killer [NanoPi M4B](https://www.friendlyarm.com/index.php?route=product/product&path=69&product_id=275) ([Wiki-Seite](http://wiki.friendlyarm.com/wiki/index.php/NanoPi_M4B)).

**Comment by jens-maus** [comment]
Ich sage es mal so: Die Chancen sind nicht gleich null. Trotzdem muss man sagen muss man hier natürlich Aufwand vs. Nutzung abwägen. RaspberryMatic unterstützt ja z.B. auch das ASUS Tinkerboard, aber eben weil es nicht nur von der Hardware 1:1 mit der eines RaspberryPi3 kompatibel ist und darüberhinaus bessere Hardwarefeatures (2GB RAM, etc.) mit sich bringt. Auch war bei der damaligen Entscheidung das ASUS Tinkerboard zu unterstützen ausschlaggebend das die Linux kernel unterstützung für dieses Board sehr gut ist und sich das ganze sehr gut und schnell integrieren liest.

Ob das nun bei den NanoPi auch der Fall ist müsste man sich dediziert einmal anschauen und auch entsprechende Testhardware vor Ort haben (welche ich nicht habe). Rein von den Specs sollte das NanoPi M4B wohl am besten passen (weil es vmtl. 1:1 in ein ELV Charly Gehäuse passt. Und auch die Aktualisierung des Kernels scheint was man so recherchieren kann recht gut zu sein. Was hingegen für die Nutzung in RaspberryMatic weiterhin kritisch ist, ist die Tatsache das RaspberryMatic bzw. die CCU Firmware weiterhin ausschliesslich auf eine 32bit Unterstützung setzt da die unter dem OCCU Projekt veröffentlichten HomeMatic Softwarekomponenten lediglich 32bit binaries sind und buildroot darüberhinaus momentan noch keine multiarch unterstützung mit sich bringt. D.h. Es müsste erst einmal geklärt werden ob und mit welchem Aufwand man diese Boards auch mit einem reinen 32bit Kernel/Umgebung betreiben kann. Das kann natürlich nun von der Community-Seite aus passieren oder jemand stellt mir die passende NanoPi M4B Hardware zur Verfügung und ich schaue in einer freien Minute welcher Aufwand das wäre oder ob es mitunter momentan aus genannten Gründen nicht möglich oder nur mit zuviel Aufwand möglich wäre.

**Comment by Wookbert** [comment]
Vorschlag: Schau Dir doch mal die verschiedenen NanoPi-Modelle an, und sag mir, welche für eine RaspberryMatic in Frage kämen. Ich könnte dann FriendlyElec mal anstubsen, sie auf die RaspberryMatic aufmerksam machen und vorschlagen, daß sie Dir ein paar Muster zur Verfügung stellen. (Machen die für Reviews ja auch).

Eine weitere RPi3b+-Alternative wäre noch der [NanoPi M4V2](https://www.friendlyarm.com/index.php?route=product/product&path=69&product_id=268&limit=100) (nahezu identisch mit dem NanoPi M4B, aber 4 GB RAM, 4 statt 2 USB 3.0 Ports, dafür aber nur BT 4.1 statt BT 5.0.

Vielleicht gibt es auch noch eine günstige Low-End-Variante unter deren PIs, die interessant wäre, à la RaspberryPi Zero.

Der Armbian/Debian-Support ist eigentlich recht gut, siehe armbian.com.
