### ISSUE TITLE
Status als Ampel bei der Programmierung

### ISSUE THREAD

**Issue by andispammonyer** [jens-maus/RaspberryMatic#874]
Hallo,

ich fände das Feature lohnenswert, wenn bei der Programmierung der Bedingungen dahinter direkt der Status (True/False) als Ampel visualisiert stünde.
Siehe dazu mein Beispielbild.
![BSP](https://user-images.githubusercontent.com/68514976/87883049-e0e4ea80-ca04-11ea-8693-f6ec7541a961.jpg)
Ich habe ein Programm bei dem die DANN Aktion ausgeführt wird, obwohl die Bedingungen vorher eigentlich alle False sein müssten.
Mit solch einer Status-Anzeige wäre die Fehlersuche um einiges einfacher.

**Comment by jens-maus** [comment]
Tut mit leid, aber den tieferen Sinn dahinter kann ich nicht erkennen. Bei der WebUI Programmierung werden ja nicht nur statische Bedingungen via "nur prüfen" abgeprüft die man ggf visualisieren könnte, sondern man nutzt oftmals die "bei Änderungen auslösen" Funktionalität und das bedeutet das WebUI Programme ja event-getrieben arbeiten und folglich die Auswertung der Bedingung erst dann true/wahr wird wenn das entsprechende Event eintritt. Folglich kann ich nicht erkennen inwieweit einem eine solche Darstellung des momentanen true/false status eines teils einer condition bringen sollte noch wie man so etwas graphische adequat dort darstellen könnte. Tschuldigung also, aber ich denk weiterhin das der nutzen einer solchen Erweiterung wirklich überschaubar bis nicht existent ist und folglich schließe ich das Ticket entsprechend.
