### ISSUE TITLE
ReGaHss: optionale Möglichkeit, bei dom.GetObject() den Ergebnisobjekttyp einzugrenzen

### ISSUE THREAD

**Issue by HMMike** [jens-maus/RaspberryMatic#876]
Wenn dom.GetObject einen zweiten optionalen Parameter bekäme, bei Nichtverwendung vorbesetzt mit OT_ALL , damit wäre die Funktion wie jetz auch gegeben,

In dem zweiten Parameter angeben liesse sich aber angeben, welchen Objecttyp ich als Ergebnis haben will.

Beispielsweise:
```
dom.GetObject ("123456789:9",OT_OBJECT);
```
liefert das Object mit dem Namen "123456789:9" wenns dieses vom Typ OT_OBJECT IST

gibt es nur ein Object, was "123456789:9" heisst aber z.b. vom Typ OT_CHANNEL ist, wäre das Ergebnis von dom.GetObject ("123456789:9",OT_OBJECT) = null

gebe es zwei Objecte, die "123456789:9" heissen, eins vom Typ OT_OBJECT, eins vom Typ OT_CHANNEL so würde dom.GetObject ("123456789:9",OT_OBJECT); das Object vom Typ OT_OBJECT finden, nicht den OT_CHANNEL

**Comment by jens-maus** [comment]
So, mit dem nächsten ReGaHss R1.00.0388.0223 Update sollte die nutzung von `dom.GetObject()` mit zusätzlichem, optionalen object type parameter nun möglich sein.
