### ISSUE TITLE
Neuer HmIP-SMO-A - meldet falsche Firmware

### ISSUE THREAD

**Issue by drohne200** [jens-maus/RaspberryMatic#877]
Neuer HmIP-SMO-A meldet nach anlernen falsches FW Update. 

**To Reproduce**
Orginal FW eQ3 1.29 

**Screenshots**
![image](https://user-images.githubusercontent.com/5902229/88217617-1ab12d80-cc5f-11ea-807a-5f2bb7cfe7eb.png)

**System information (please complete the following information):**
 - Version : RaspberryMatic 3.51.6.20200621
 - Hardware: Pi 3

**Comment by jens-maus** [comment]
Tut mir leid, aber dieses Verhalten (das mitunter Gerätefirmware downgrades angebiten werden) ist normal und bekannt. Die verteilten Gerätefirmwarestände zwischen einem HmIP Accesspoint für die Cloud unterscheiden sich mitunter von denen für die jeweilige CCU Firmware. Daher verteilz eQ3 hier mitunter unterschiedliche versionen und wenn man ein neu erworbenes Gerät mit einer CCU koppelt kann es sein das dann ein Firmware-Downgrade angeboten wird. Das ist kein Bug, sondern ein feature bzw so von eQ3 gewollt da nur so sichergestellt werden kann das die Gerätefirmware zu den WebUI Features der eingesetzten CCU Firmware passt.
