### ISSUE TITLE
ReGaHss: Abbruch von geschachtelten foreach / while-Schleifen mittels "break"

### ISSUE THREAD

**Issue by mabel-gh** [jens-maus/RaspberryMatic#878]
**Describe the bug**
Wenn mehrere Schleifen verschachtelt programmiert werden, ist es aktuell entscheidend, an welcher Stelle der Abbruchbefehl "break" verwendet wird, damit das Programm überhaupt ausgeführt wird. Das sollte aber so nicht sein! siehe Beispiel unten

**To Reproduce**
1. Folgendes Beispielskript funktioniert problemlos:

```c++
WriteLine("Start Skript!");
string LISTE1 = ("A\tB\tC\tD");
string ELEMENT1; 
string LISTE2 = ("1\t2\t3\t4");
string ELEMENT2; 
boolean GEFUNDEN = false;
foreach(ELEMENT1, LISTE1) 
{
  Write("-");
  if(GEFUNDEN) { Write("break1"); break; }
  
  foreach(ELEMENT2, LISTE2)
  {
    Write(".");
    if((ELEMENT2 == 3) && (ELEMENT1 == "C")) { GEFUNDEN = true; }
  }
            
  Write("x");
  ! if(GEFUNDEN) { Write("break2"); break; }
}
WriteLine("\nEnde Skript");
```
und es wird folgendes korrektes Resultat zurückgegeben:
```
Start Skript!
-....x-....x-....x-break1
Ende Skript
```
2. Sobald nun jedoch die Zeile mit dem `break2` nach dem `Write("x");` auskommentiert wird (d.h. das `!` davor entfernt wird kommt es fälschlicherweise zu folgendem Syntax-Error:

```
Error 1 at row 19 col 41 near ^; }
}
WriteLine("\nEnde Skript");
Error 1 at row 19 col 41 near ^; }
}
WriteLine("\nEnde Skript");
Error 1 at row 19 col 41 near ^; }
}
WriteLine("\nEnde Skript");
```

**Expected behavior**
Es sollte egal sein, an welcher Stelle der äußeren Schleife der Abbruch via `break` erfolgen soll!

**Screenshots**

**System information (please complete the following information):**
 - Version [RaspberryMatic  [3.51.6.20200613]
 - Hardware [RaspberryPi3]

**Additional context**
Das exakt selbe Probleme existiert mit der Verwendung von `continue` statt `break`. D.h. beide Statements verlieren nach der zweiten inneren Schleife Ihre Gültigkeit und können fälschlicherweise nicht mehr angewendet werden.

**Comment by jens-maus** [comment]
Starting with ReGaHss R1.00.0388.0223 this issue with `break` and `continue` uses after a nested `foreach()` or `while()` loop should be solved. Thanks for the bugreport.
