### ISSUE TITLE
Gerätetausch wird in der WebUI nicht beendet

### ISSUE THREAD

**Issue by jp112sdl** [jens-maus/RaspberryMatic#879]
**Describe the bug**
Am Ende des Vorgangs "Gerätetausch" erscheint der Hinweis "Konfigurationsdaten werden geladen" endlos.
Der Tausch wurde jedoch _augenscheinlich_ durchgeführt.

**To Reproduce**
- neues Gerät anlernen
- im Posteingang den Button "Tauschen" betätigen
- Tauschvorgang durchführen

**Screenshots**
<img src="http://g.recordit.co/1LVKp5r21L.gif" />

**System information (please complete the following information):**
 - RaspberryMatic 3.51.6.20200621
 - Hardware: Virtualbox VM

**Additional context**
siehe auch: https://homematic-forum.de/forum/viewtopic.php?f=65&t=59980

**Comment by jp112sdl** [comment]
Nach weiterer Recherche konnte ich feststellen, dass beim Gerätetausch nur der Tauschpartner gelöscht wird.
Das neue Gerät wird nicht in Direktverknüpfungen oder Programmen ersetzt.

Soweit ich es nachvollziehen konnte, bleibt der Vorgang bei `ConfigData.check(...` in der [/www/webui/webui.js](https://raw.githubusercontent.com/eq-3/occu/master/WebUI/www/webui/webui.js) hängen
```
...
var  performReplaceDevice = function(iface, oDevices) {
...
    var result = homematic("Interface.changeDevice" , {
      "interface" : iface,
      "addressOldDevice" : oDevices.oldDevAddr,
      "addressNewDevice" : oDevices.newDevAddr
    }, function() {
      window.setTimeout(
        function() {
          var self = this;
          ProgressBar.hide();
          ProgressBar.StopKnightRiderLight();
          ConfigData.destroy();
          // 
          // Die Methode ConfigData.destroy(); wird noch ausgeführt
          // 
          ConfigData.check(function() {
            // 
            // Hier erfolgt bereits kein Einstieg mehr
            // 
            WebUI.enter(DeviceListPage);
            MessageBox.show(translateKey("replaceDeviceHintTitle"), translateKey("replaceDeviceHintContent"));
...
```

Im Methodenaufruf `ConfigData.check` wird noch `this.configDataLoader.showMessage();` **erfolgreich** durchgeführt.
```
ConfigData = Singleton.create({
...
  check: function(callback)
  {
    this.callback = callback;
    if (this.isPresent === false)
    {
      //this.isPresent = true;
      //new ConfigDataLoader(callback);
      this.configDataLoader.showMessage();
      this.showMessage = true;
    }
    else
    {
      if (callback) { callback(); }
    }
  },
```

In der `ConfigDataLoader`-Klasse wird auch `showMessage` bis zum Ende(`Layer.add(this.m_layer);`) abgearbeitet.

Danach ist schluss...

Es werden **keine Tasks (`WEBUILOADER_DEVICES`, `WEBUILOADER_ROOMS`, `WEBUILOADER_FUNCTIONS`) angelegt oder abgearbeitet**

Mehr Ideen zum Debuggen habe ich nicht.

_Wenn das Verhalten auch mit der originalen CCU2 / CCU3 Firmware auftritt, wäre das dann wohl eher was für eQ-3._

**Comment by MathiasJZ** [comment]
Frage:
Kann man die CCU3-Firmware auch mit dem alten Funkmodul betreiben, oder braucht man da unbedingt das große?
ich habe noch 2 baugleiche Aktoren übrig, die von mir nicht verwendet werden. Damit könnte ich es ja testen, wenn es geht.

**Comment by jp112sdl** [comment]
m.W. geht da nur das RPI-RF-MOD

**Comment by MathiasJZ** [comment]
Schade dann geht's leider nicht. Sonst hätte ich aus einem Raspberry schnell eine CCU gemacht. Ich habe leider nur ein großes Funkmodul. Das läuft produktiv.

**Comment by jp112sdl** [comment]
Bis einschließlich OCCU Version 3.43 ging es noch wie gewohnt.

Danach wurden die `ConfigData` und `ConfigDataLoader` Klassen umgebaut.
Der Autor (lt. Kommentar `F. Werner (eQ-3)`) kann dazu vielleicht mehr sagen ^^ 

Wenn man die alte Funktionsweise reaktiviert (in der eine neue `ConfigDataLoader` Instanz verwendet wird), läuft auch der Gerätetausch durch:
```
    this.callback = callback;
    if (this.isPresent === false)
    {
      this.isPresent = true;
      new ConfigDataLoader(callback);
      //this.configDataLoader.showMessage();
      //this.showMessage = true;
    }
```
_(Zeilennummern lassen sich bei der `webui.js` ja leider nicht verlinken)_

Ich bin dann hier fertig

**Comment by jens-maus** [comment]
@jp112sdl Ich kann gerne mal nachhaken bei eQ3. Allerdings wäre es auch sicherlich ne gute Idee aus deiner Erkenntnis einfach mal ein neuen WebUI Patch zu machen um zu sehen ob andere Nutzer das bessere/reparierte Verhalten dann reproduzieren können. Was hältst du davon?

**Comment by jp112sdl** [comment]
> Was hältst du davon?

Eher weniger.
Der Patch würde einfach nur den alten Stand wiederherstellen (vor FW 3.45). 
Der Umbau von `ConfigDataLoader` und `ConfigData` seitens eQ-3 wird schon seine Gründe haben. 
Die Klassen werden auch beim Aufruf von Einstellungen->Geräte benutzt.
Ich habe keine Ahnung, ob die Modifikation nur dem Einblenden des "Konfigurationsdaten werden geladen"-Popups dienen soll, oder ob es noch andere Auswirkungen hat.

> nachhaken bei eQ3

halte ich da erstmal für sinnvoller
