### ISSUE TITLE
Restore auf beta6 nicht möglich

### ISSUE THREAD

**Issue by bprskalo** [jens-maus/RaspberryMatic#88]
hallo zusammen. 

erst mal ein grosses DANKESCHÖN für diese wahnsinnsarbeit hier ! 

zu meinem "problem".

auf der beta6 lässt sich mein restore nicht installieren (habe es mehrmals versucht). die gleiche sicherung (von heute morgen) geht ohne probleme auf der beta5. 

eine randnotiz, ich bin schon länger mit dabei und denke zu wissen wie es funktionieren sollte, lasse mir aber sehr gern erklären falls ich etwas falsch machen sollte :-) 

gruss

bosi

**Comment by jens-maus** [comment]
@bprskalo Was genau passiert denn bzw. kommt denn als Fehlermeldung?

**Comment by bprskalo** [comment]
der ablauf an und für sich bringt keine fehler. nach dem geppanten neustart sind keine wiederhergestellten daten auf dem system.

es ist dann wie das erste mal gestartet nach dem image restore.

**Comment by jens-maus** [comment]
@bprskalo Bitte mal hier (https://homematic-forum.de/forum/viewtopic.php?f=65&t=36588) beteiligen. Dort wird zumindest gesagt es würde zumindest ein Teil des Backups wieder da sein. Ist das bei dir auch der Fall?

**Comment by bprskalo** [comment]
nein, bei mir ist es wirklich ohne eigenen inhalt. wie anfangs beschrieben die gleiche sicherung mit der beta5 ohne probleme
