### ISSUE TITLE
Update Dialog: Datei-Upload – Bezeichnung von „Software“ zu „ZIP-Datei“ ändern / Überprüfung auf .zip-Extension

### ISSUE THREAD

**Issue by Wookbert** [jens-maus/RaspberryMatic#880]
Ein Problem, in das ich zum wiederholten Mal reingerannt bin: mac OS X entpackt runtergeladene ZIPs standardmäßig sofort und ohne zu fragen. Ziehe ich also bspw.  _RaspberryMatic-3.51.6.20200621-rpi3.zip_, dann befindet sich Sekunden später das Image _RaspberryMatic-3.51.6.20200621-rpi3.img_ im Download-Ordner, während das ZIP-Archiv schon im Papierkorb weilt.

Weil ein .img jetzt auch nicht so unsinnig erscheint, lade ich jedes mal das .img auf die RaspberryMatic. Ich kann den Fortschritt des Uploads verfolgen, und wenn 100% abgeschlossen sind, wartet man wie üblich auf die Verarbeitung ... die aber (logischerweise) bis zu Unendlichkeit dauert, weil das System mit dem .img nichts anzufangen weiß.

Man vergisst das, wenn man alle 8 Monate mal auf die RaspberryMatic schaut und dann aktualisiert...

Folgende Möglichkeiten:

a) man verändert das Post-Processing so, dass die Update-Logik mit dem entpackten .zip, also dem darin enthaltenen .img umgehen kann

–– oder ––

b) man ändert das Wording im Dialog-Schritt 2, dem Upload auf die RPmatic von „Software“ zu „ZIP-Datei“ (am besten noch in fett und rot. Zusätzlich könnte man die Datei-Endung, und wenn diese nicht .zip ist, noch einmal explizit darauf hinweisen, daß der Download nicht entpackt werden darf.

![Bildschirmfoto 2020-07-24 um 18 47 41](https://user-images.githubusercontent.com/3104762/88416327-4f98be00-cde0-11ea-96f4-954446a8d07f.png)

**Comment by jens-maus** [comment]
Tut mir leid, aber die vorgeschlagenen Änderungen sind teilweise IMHO zuviel des guten, gehören in den Bereich den eQ3 als upstream bearbeiten/entscheiden sollten. Darüberhinaus ist es aber z.b. Eigentlich möglich auch das .img direkt hochzuladen. Das ist in der Tat so implementiert worden. Wenn das allerdings nicht funktioniert, dann muss das andere Ursachen haben.

Ich würde daher vorschlagen, statt Anpassungen an der WebUI dafür zu wünschen, einfach diese automatische entpackfunktion von macOS bzw Safari zu deaktivieren.
