### ISSUE TITLE
Zertifikat erstellen geht nicht

### ISSUE THREAD

**Issue by hkissler** [jens-maus/RaspberryMatic#881]
**Describe the bug**
Habe die aktuelle Version auf einen PI3B. Beim Versuch ein Zertifikat zu erstellen kommt nur die Meldung „Der Webserver wird jetzt neu gestartet.“ Ein Download des Zertifikats ist nicht möglich.
Ist das ein Fehler von mir oder ein Bug?

Getestet mit Safari (MacOS und iPadOS) und unter Windows mit Edge

**To Reproduce**
1. Go to Einstellungen, Systemsteuerung, Netzwerkeinstellungen 
2. Click on Zertifikat erstellen 

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
 - Version 3.51.6.20200621
 - Hardware RaspberryPi3

**Additional context**

**Comment by libertyx82** [comment]
Weder noch, es funktioniert wie es soll.

Ein Download des Zertifikates ist nicht notwendig, dieses wird automatisch ausgetauscht.

**Comment by hkissler** [comment]
Ok, danke für die Info.
Allerdings ist die Anleitung dann etwas verwirrend.
