### ISSUE TITLE
Firmware update not possible

### ISSUE THREAD

**Issue by Havoc85** [jens-maus/RaspberryMatic#882]
**Describe the bug**
Firmware update is not possible. UI shows Loading Screen even for hours. Restarted and updated System a couple of times - doesn't change the behavior. 

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Device firmware - overview'
3. Click on 'Device firmware' (at the bottom)
4. See error (never ending loading screen - you need to forcely reload the web page to become responsive again)

**Expected behavior**
Upload new firmware for devices and not "freezing" the web page.

**Screenshots**
![image](https://user-images.githubusercontent.com/2799774/88785148-22a62b80-d191-11ea-9be5-c896c6440b96.png)

**System information (please complete the following information):**
 - Version 3.51.6.20200621 (but happend also in earlier versions)
 - Hardware: rpi3 - ELV Charly

**Additional context**
UI shows me some new device firmware versions, but I can't upload them and I can't find another way.
![image](https://user-images.githubusercontent.com/2799774/88785719-d7404d00-d191-11ea-8c13-6b62125c8c18.png)

**Comment by jens-maus** [comment]
Can you please have a look if there is any error/crash message in the local `/usr/local/tmp` directory when this happens. In addition, please open the debug console of your web browser to have a look for potential issues/errors being displayed.

**Comment by Havoc85** [comment]
Sadly, either way there is no error or any other message:

![image](https://user-images.githubusercontent.com/2799774/89103518-c5b9a800-d412-11ea-9d7e-d40c5843fc2a.png)

```
root@neptunium:/usr/local/tmp# ll
total 8
drwxr-xr-x    2 root     root          4096 Aug  1 16:16 ./
drwxr-xr-x    7 root     root          4096 Jul 29 11:09 ../
-rw-r--r--    1 root     root             0 Jul 29 11:09 .nobackup
-rw-r--r--    1 root     root             0 Jan  1  1970 .watchdog
root@neptunium:/usr/local/tmp#
```

**Comment by jens-maus** [comment]
Nope, sorry. Currently I am out of ideas since all these firmware update routines, etc. are an integrated feature of HMIPServer which in fact is closed source.

**Comment by Havoc85** [comment]
> Nope, sorry. Currently I am out of ideas since all these firmware update routines, etc. are an integrated feature of HMIPServer which in fact is closed source.

Is there any other way to update the devices firmwares?

**Comment by slankes** [comment]
I am seeing the exact same issue (running 3.53.34.20201121).

I suspect a faulty SD-Card because whenever I click that link I get this in dmesg:

```
[Thu Nov 26 12:18:52 2020] EXT4-fs error (device mmcblk0p3): __ext4_find_entry:1541: inode #260284: comm vert.x-worker-t: checksumming directory block 0
[Thu Nov 26 12:29:52 2020] EXT4-fs warning (device mmcblk0p3): ext4_dirblock_csum_verify:370: inode #260347: comm vert.x-worker-t: No space for directory leaf checksum. Please run e2fsck -D.
```

I am going to try replacing the SD-Card and report back here if that fixed it.

**Comment by Havoc85** [comment]
> I am seeing the exact same issue (running 3.53.34.20201121).
> 
> I suspect a faulty SD-Card because whenever I click that link I get this in dmesg:
> 
> ```
> [Thu Nov 26 12:18:52 2020] EXT4-fs error (device mmcblk0p3): __ext4_find_entry:1541: inode #260284: comm vert.x-worker-t: checksumming directory block 0
> [Thu Nov 26 12:29:52 2020] EXT4-fs warning (device mmcblk0p3): ext4_dirblock_csum_verify:370: inode #260347: comm vert.x-worker-t: No space for directory leaf checksum. Please run e2fsck -D.
> ```
> 
> I am going to try replacing the SD-Card and report back here if that fixed it.

That was a good idea. But I don't see this messages in dmesg. Maybe I should try it with another SD Card anyway. Please keep me updated, if this fixed it for you.

Also to mention that: I checked again every (for me) known log file. There is not one error message anywhere. Even with the newest firmware.

Thank you.

Regards,
Jens

**Comment by slankes** [comment]
Replacing the sd card did indeed fix this issue for me. Now the firmware update functionality is back.

The backup / flash new sd card / restore backup was painless and it took me less than 30 minutes to get back to a working installation.

**Comment by Havoc85** [comment]
> Replacing the sd card did indeed fix this issue for me. Now the firmware update functionality is back.
> 
> The backup / flash new sd card / restore backup was painless and it took me less than 30 minutes to get back to a working installation.

Thank you for sharing. Maybe I should try it, too. But besides the Firmware-Update Problems, everything is working fine since a year or so. I will let you know, if changing the SD Card worked for me, too.

**Comment by Havoc85** [comment]
> Replacing the sd card did indeed fix this issue for me. Now the firmware update functionality is back.
> 
> The backup / flash new sd card / restore backup was painless and it took me less than 30 minutes to get back to a working installation.

Sadly, this didn't work for me.
I installed Raspberrymatic on a new SD Card. On first (empty) boot, I could access the Firmware Update Menu. After I imported a Backup, it again didn't work.

Is there any other help for this? I would appreciate any support, without reconfiguring EVERYTHING.

**Comment by mh-82** [comment]
Exact same issue here regarding the firmware upload.

I did have a faulty SD card, too. 
Realized this as the UI was not loading at all sometimes and only way to recover was to restart the Raspberry.

However flashing a new SD card and importing the backup did not solve my issue. 
So I suspect the problem is imported again with the backup.

Here is how i worked around the problem:

1. Connect to the Raspberry via FTP
2. Navigate to /usr/local/etc/config/firmware
3. Upload newer firmware versions to their respective folders (delete old files first)
4. In case it is a firmware of a device without an existing folder just create one with a random number and upload (number does not seem to matter)
5. Execute firmware update via UI

Hope this helps to update your firmware and maybe find a solution to the problem.

**Comment by Havoc85** [comment]
> Exact same issue here regarding the firmware upload.
> 
> I did have a faulty SD card, too.
> Realized this as the UI was not loading at all sometimes and only way to recover was to restart the Raspberry.
> 
> However flashing a new SD card and importing the backup did not solve my issue.
> So I suspect the problem is imported again with the backup.
> 
> Here is how i worked around the problem:
> 
> 1. Connect to the Raspberry via FTP
> 2. Navigate to /usr/local/etc/config/firmware
> 3. Upload newer firmware versions to their respective folders (delete old files first)
> 4. In case it is a firmware of a device without an existing folder just create one with a random number and upload (number does not seem to matter)
> 5. Execute firmware update via UI
> 
> Hope this helps to update your firmware and maybe find a solution to the problem.
> 
> Thanks @slankes for redirecting me here!

This didn't work for me either. 

**BUT...** There was an empty folder at that location (/usr/local/etc/config/firmware/288). As I played around, I just deleted everything. After clearing everything inside the folder firmware, the "Upload Firmware" at the UI worked again. **THANK YOU SO MUCH!**

And by the way... Why is that a) closed source and b) that buggy?

**Comment by jens-maus** [comment]
@Havoc85 DO you have an older backup with the broken `/usr/local/etc/config/firmware` before you deleted it? This would give us potentially the chance to investigate and create a fix/workaround here.

**Comment by Havoc85** [comment]
> @Havoc85 DO you have an older backup with the broken `/usr/local/etc/config/firmware` before you deleted it? This would give us potentially the chance to investigate and create a fix/workaround here.

Yes. I have. Every Backup had that problem.
Is there any way to anonymize the backup?

**Comment by jens-maus** [comment]
If you know how, you can also simply archive the whole /usr/local/etc/config/firmware content and send it over here. This should not contain any sensible / private information. Are you send me your whole backup in a private email, if you trust me.
