### ISSUE TITLE
ReGaHss: ToFloat() sollte bei Anwendung auf einen Integer/Float keinen Fehler erzeugen

### ISSUE THREAD

**Issue by MichaelN0815** [jens-maus/RaspberryMatic#883]
**Is your feature request related to a problem? Please describe.**
Die Anwendung von .ToFloat() auf Integer oder Real Werte verursacht einen ReGaHss: ERROR: ScriptRuntimeError
Da Homematic-Script keine saubere Typ-Behandlung verwendet, sondern den Typ bei Bedarf anpasst benötigt man eine sichere Methode um für Berechnungen einen konsistenen Datentyp sicherzustellen. Dies ist aber nicht möglich, wenn .ToFloat() nur auf Strings angewendet werden darf. Ist auch inkonsistent zu .ToInteger(), das fehlerfrei auch bei Integer/Float arbeitet. 

**Describe the solution you'd like**
.ToFloat() sollte unabhängig vom Datentyp String/Integer/real/var immer ein Realwert ausgeben

**Additional context**
Beispielskript

```
! Test = 2 / 2.0 erzeugt mit ToFloat() Fehler / "2.00" nicht
! Test = 2 / 2.0 / "2.00" erzeugt mit ToInteger() keinen Fehler
var Test = 2; 

var Test2;
Test2 = Test.ToFloat();   ! FEHLER
WriteLine(":"#Test2);

var Test3;
Test3 = Test.ToInteger(); ! OK
WriteLine(":"#Test3);          
```

**Comment by jens-maus** [comment]
Starting with ReGaHss R1.00.0388.0223 the use of .ToFloat() on integer, float and time variable types should be possible. Thanks for the suggestion/hint.
