### ISSUE TITLE
update Linux kernel to 4.9.x

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#89]
In some future version of RaspberryMatic we should update the linux kernel to the current 4.9.x line. This seems to be also the currently stable branch of the raspberrypi crew (as can be seen here: https://github.com/raspberrypi/linux).

However, one current issue seems to be that our bcm2835-raw-uart kernel module isn't currently compatible to kernel 4.9.x (see https://github.com/eq-3/occu/issues/33#issuecomment-282728391). We should therefore review if we should first work on #38 before we can switch to kernel 4.9 which might be required in future.

**Comment by leonsio** [comment]
habe meine YAHM Installation mit 4.9er Kernel am laufen, einzige Anpassung wäre

```bash
        if [ $(ver ${kernel_version}) -ge $(ver 4.9.0) ]
        then
            cd /tmp/kernel-modules/bcm2835_raw_uart
            sed -i bcm2835_raw_uart.c -e "s/CLK_IS_ROOT/0/"
        fi
```

da die Variable nicht länger im Kernel 4.9 existiert, ist zwar unschön, aber funktioniert wunderbar

Gruß

Leo

**Comment by jens-maus** [comment]
Kernel 4.9.y support is now on master branch. Thus, done.
