### ISSUE TITLE
Backup fehlerhaft/unvollständig (z.B. *.apkx Datei fehlt)

### ISSUE THREAD

**Issue by alexirion** [jens-maus/RaspberryMatic#890]
"Backup einspielen" führt zur Fehlermeldung:
Backup fehlerhaft/unvollständig (z.B. *.apkx Datei fehlt)

Die Backupdatei wurde dabei unmittelbar zuvor auf einer frisch installierten Raspberrymatic gemacht.

Reproduktion:
1. Raspberrymatic Image auf SD Karte schreiben
2. Sicherheit/Backup erstellen, ".sbk" Datei lokal speichern
3. Unmittelbar Sicherheit/Backup wieder einspielen (Durchsuchen +  ".sbk" Datei auswählen +  Sicherheit/Backup einspielen)
5. Error: "Backup fehlerhaft/unvollständig (z.B. *.apkx Datei fehlt)"

Erwartet: Backup kann erfolgreich eingespielt werden

Version: 3.51.6.20200822
RaspberryPi4

**Comment by alexirion** [comment]
In occu-3.51.6-10/WebUI/www/config/cp_security.cgi, Zeile 813 (siehe unten) wird für eine CCU3 geprüft ob das Backup vollständig ist. Wenn nicht, wird hier die besagte Fehlermeldung ausgegeben und backuperror wird auf "true" gesetzt.
Durch das backuperror == true, wird dann der Neustart in den Zeilen darauf nicht ausgeführt. Allerdings wird in diesem Fall, das Backup auch nicht gelöscht, im Gegensatz zu dem Fall einer CCU2, Zeile 618.

Die Meldung an den Benutzer "Backup fehlerhaft / unvollständig" und das Verhalten der Software sind hier also nicht konsistent. Das Backup wird ja bei einem manuellen Neustart auch in diesem Fehlerfall ausgeführt.

Wenn man also das Backup sowieso ausführt, obwohl der Check negativ war, sollte man dann nicht lieber die Fehlermeldung und den Check weg lassen? Oder man bringt die Fehlermeldung, und dürfte dann aber auch das Backup nicht ausführen.

Einen Pull Request könnte ich erstellen, wenn mir jemand beantwortet was hier gewünscht ist.

if { "CCU2_CCU2" != $migration_mode } {
    if {($source_major >= 3) || (($source_major == 2)  && ($source_minor > 17)) || (($source_major == 2) && ($source_minor == 17) && ($source_patch >= 14))} {
      set checkBackupState [checkUserBackupValidility $migration_mode]
      if {$checkBackupState != 10} {
        # It's not possible to use the backup
        set backuperror true
        # Start /etc/init.d/S62HMServer start
        cgi_javascript {puts "homematic('User.restartHmIPServer');"}
        put_message "\${dialogSettingsSecurityMessageSysBackupErrorTitle}" "\${dialogSettingsSecurityMessageSysBackupErrorContent} [getBackupErrorMessage $checkBackupState $migration_mode]"
      }
    }
  }

**Comment by jens-maus** [comment]
> Wenn man also das Backup sowieso ausführt, obwohl der Check negativ war, sollte man dann nicht lieber die Fehlermeldung und den Check weg lassen? Oder man bringt die Fehlermeldung, und dürfte dann aber auch das Backup nicht ausführen.
> 
> Einen Pull Request könnte ich erstellen, wenn mir jemand beantwortet was hier gewünscht ist.

Nun, nach meinem Verständnis is gewünscht zu erkennen das kein Funkmodul zur Zeit des Restore installiert ist und dann die Fehlermeldung entsprechend zu übergehen bzw. in `checkUserBackupValidity` die entsprechende Ausnahme für diesen Fall (kein Funkmodul existent) einzubauen und entsprechend dann keine Fehlermeldung zurück zu geben. Wenn du dafür ein PullRequest machen könntest wäre das super. Hatte das eigentlich schon lange auf der Agenda, komme nur nicht dazu :)

**Comment by alexirion** [comment]
> > Wenn man also das Backup sowieso ausführt, obwohl der Check negativ war, sollte man dann nicht lieber die Fehlermeldung und den Check weg lassen? Oder man bringt die Fehlermeldung, und dürfte dann aber auch das Backup nicht ausführen.
> > Einen Pull Request könnte ich erstellen, wenn mir jemand beantwortet was hier gewünscht ist.
> 
> Nun, nach meinem Verständnis is gewünscht zu erkennen das kein Funkmodul zur Zeit des Restore installiert ist und dann die Fehlermeldung entsprechend zu übergehen bzw. in `checkUserBackupValidity` die entsprechende Ausnahme für diesen Fall (kein Funkmodul existent) einzubauen und entsprechend dann keine Fehlermeldung zurück zu geben. Wenn du dafür ein PullRequest machen könntest wäre das super. Hatte das eigentlich schon lange auf der Agenda, komme nur nicht dazu :)

Das checkUserBackupValidility ruft das checkUsrBackup.sh auf, welches den Fehlercode(11) von /opt/HMServer/HMIPServer.jar erhält. Da das HMIPServer.jar aber Closed Source ist können wir hier drin nichts ändern, richtig?

Es bleibt also nur, den Fehlercode 11 in dem Fall, dass kein Funkmodul installiert ist, wegzufiltern. Allerdings, entgehen einem dann dadurch auch echte Fehler, die den gleichen Code in HMIPServer.jar verursachen würden.

Wie könnte ich in cp_security.cgi überprüfen, ob ein Funkmodul installiert ist, oder nicht?

Weiss man welche fehlenden Dateien das sind, die den Fehlercode 11 verusachen? Könnte man nicht vielleicht auch Dummy Dateien erzeugen, so dass der HMIPServer.jar keinen Fehlercode zurückgibt?
