### ISSUE TITLE
RaspberryMatic 3.51.6.20200621 reports running low on disk space for /media/usb1 while creating a backup

### ISSUE THREAD

**Issue by tnick61** [jens-maus/RaspberryMatic#891]
**Describe the bug**
While creating a backup (automated via cronjob or manual via WebGUI), low disk space for /media/usb1 is being reported.
System has been working stable and correctly before.
No external SD memory card is installed!

**To Reproduce**
Backup via cronjob or manual system backup via WebGUI.
Tests showed diskspace runs low when the sbk file is being created and the tmp file still exists.

**Expected behavior**
Correct backup created.

**Screenshots**
None.

**System information (please complete the following information):**
 - Version : RaspberryMatic 3.51.6.20200621
 - Hardware : TinkerboardS

**Additional context**
I am also having troubles with existing HMIP devices not communicating correctly, though no error is being reported.

**Comment by jens-maus** [comment]
Sorry, but if your system is running low on disk space while you are trying to create a backup, then you should switch to a larger USB stick or lower the amount of data that is required to be backed up. I can currently not see any way of fixing here something that is related to not enough disk space being available on your device.

**Comment by tnick61** [comment]
In the meantime I've found the root cause of the problem. The backup script (started via the cronjob) tried also to backup the former backups stored under /usr/local/backup as well though it should have been excluded in the createBackup.sh . This caused an exponential increase of the backup files after a few days. I have no idea why this is suddenly happening. The problem happens when the /media/local/backup/ path is being used. After writing /usr/local/backup/ into the CronBackupPath file in /etc/config the problem disappeared.

**Comment by jens-maus** [comment]
@tnick61 Where does this `/usr/local/backup` folder come from? AFAIR this is not a directory path RaspberryMatic creates/uses itself.

**Comment by tnick61** [comment]
@jens-maus Interesting. I installed RaspberryMatic on a TickerboardS with no additional SD card installed. The problem with the memory size started after upgrading RaspberryMatic to the latest release 3.51.6.20200621. Using the **df** command from the root directory it shows that /dev/mmcblk2p3 is mounted twice ether to /media/usb1 and to /usr/local. Funny, they point both to the same directory! Meaning cd to /media/usb1 or cd to /usr/local end up in the same directory with the backup directory in it. usb0 is symlinked to usb1 as it should be.
