### ISSUE TITLE
Connection to HmIP-SMI55 Channel 1+2 broken

### ISSUE THREAD

**Issue by floriandrott** [jens-maus/RaspberryMatic#895]
**Describe the bug**
The connection with HmIP-SMI55 is broken for the channels 1 and 2. It works perfectly with only one HmIP-SMI55 but since if have two of them in my setup ... the second one is not working on the channels 1 and 2. The HmIP-SMI55 is not just blinking orange when pressing the button for channel 1 or 2 and not getting the submit confirmation (green light).

**To Reproduce**
1. Register a new HmIP-SMI55
2. Configure HmIP-SMI55, e.g. timeout for long press
3. Do the self check for the channels
4. Channel 1 and 2 not working; channel 3 is working correctly.

**Expected behavior**
Channel 1 and 2 are working correctly and also if more then one HmIP-SMI55 is registered.

**Screenshots**

**System information (please complete the following information):**
 - Version: RaspberryMatic 3.51.6.20200621
 - Hardware: Virtual RaspberrryMatic; HmIP-SMI55 1.0.12

**Additional context**
Could be related to issue #705

**Comment by floriandrott** [comment]
Just an update on it: If I link HmIP-SMI55 channel 1 or 2 to a different action like HmIP-BROLL channel 6 then it works. It seems like that the events from HmIP-SMI55 channel 1/2 are not populated anymore as an RPC event.

**Comment by jens-maus** [comment]
Sorry, but the RaspberryMatic firmware does not have any way to deal with these kind of issues. So please explain in somewhat more detail what the problem is (show screenshots/screencasts where one can see what is going wrong) and what you expect RaspberryMatic to do.
