### ISSUE TITLE
WEB_UI Status von alten Wired-Geräten wird nicht mehr korrekt angezeigt

### ISSUE THREAD

**Issue by RoHa78** [jens-maus/RaspberryMatic#896]
**Describe the bug**
Wird in RaspberryMatic mit Softwareversion 3.51.6.20200621 (möglicherweise auch schon zuvor ...) bei einer "alten" Wired Komponente mit dem WEB-UI der Status des Aktors angesehen steht dieser generell auf 'AUS' unabhängig vom tatsächlichen Status. Wird nun in der WEB-UI dieser Aktor eingeschaltet, regiert zwar der Aktor selbst und der Verbraucher wird tatsächlich eingeschaltet, der Status im WEB-UI bleibt aber auf 'AUS'.
Dieses Verhalten konnte ich beim Dimmaktor HMW-LC-Dim1L-DR und beim Schaltaktor HMW-LC-Sw2-DR beobachten.
Funkaktoren scheinen nicht betroffen zu sein.

**To Reproduce**
Siehe oben.

**Expected behavior**
Status sollte in WEB-UI korrekt angezeigt werden, bzw. bei Betätigung im WEB-UI korrekt übernommen werden
**Screenshots**

**System information (please complete the following information):**
 - Version [RaspberryMatic 3.51.6.20200621]
 - Hardware [RaspberryPi3]

**Additional context**

An dieser Stelle nochmals vielen Dank für die tolle Arbeit!

**Comment by jens-maus** [comment]
Können das andere BidCos-Wired Nutzer bestätigen? Ich habe hier leider keine BidCos-Wired Komponenten da zum testen und kann daher nicht sagen ob das ein generelles Problem ist oder nur deine Installation betroffen ist. Daher bitte Leidensgenossen finden und etwas mehr ins Detail gehen hier und auch Screenshots/Screencasts hier zeigen um das Problem besser zu illustrieren.

**Comment by RoHa78** [comment]
[Demo.zip](https://github.com/jens-maus/RaspberryMatic/files/5157969/Demo.zip)
Hi,
kenne leider niemanden, der diese Hardware benutzt (haben mittlerweile alle IP-Wired), hab aber versucht durch das angehängte Video diesen Fall zu demonstrieren.
Links sind 3 Kanäle in der Favoritenansicht von RaspberryMatic (Fehler tritt auch bei Ansicht Bedienung auf) rechts die gleichen Kanäle im IOBroker, dort wird der richtige Schaltzustand angezeigt.
Die ersten beiden Kanäle zeigen einen BidCos-Wired Dimmer und ein BidCos-Wired Schaltaktor, der 3. Kanal als Referenz einen Standard BidCos-Funkschalter. Wie auf dem Video zu erkennen ist, wechselt der Schaltzustand im GUI nicht auf "an" wenn der "AN" Button angeklickt wird. Seltsamerweise funktioniert beim Dimmer dies aber, wenn der Level verstellt wird. Beim Schaltaktor (Kanal 2) gleiches Problem. Beim 3. Kanal dem Funkaktor wird der Status hingegen nach Betätigung, wenn auch etwas verzögert, korrekt angezeigt. Dieser Effekt tritt mit Edge, Chrome und Firefox auf, sowohl in Windows als auch unter Android (nur Firefox und Chrome).
Ich glaube auch nicht, dass dies ein Problem meiner Installation ist, denn dies hat mit dieser Konfiguration schon mal korrekt funktioniert, habe jeweils nur die aktuellen Updates von RaspberryMatic und den Addons installiert. Da ich nun seit einiger Zeit das Ganze mit IOBroker steuere, ist mir dieser Effekt bisher nicht aufgefallen, kann also nicht sagen, wie lange dies nun bereits so ist.
Wenn ich noch weitere Details testen soll, einfach melden!

**Comment by jp112sdl** [comment]
Hi,
nur kurz nachgefragt: Das HVL-Addon hast du nicht zufällig installiert, oder?
Ich kann mich entsinnen, im Homematic Forum mal von Problemen mit Wired im Zusammenhang mit dem Addon gelesen zu haben (wobei es dann wohl gar nicht mehr geht: https://homematic-forum.de/forum/viewtopic.php?f=65&t=58484)

**Comment by RoHa78** [comment]
Hi Jérôme,
das HVL-Addon ist nicht installiert, solche Dinge lassen sich ja über IOBroker einfacher lösen. Das Schalten funktioniert ja auch tadellos, es scheint nur so, das die Anzeige im WEB-UI bei den BidCos-Wired Komponenten nicht aktualisiert werden. Trotzdem vielen Dank für Deinen Hinweis! 
Versuche mal am WE vielleicht noch das eine oder andere Addon zu entfernen, glaube aber eher dass einfach der Status irgendwo in der Anzeige nicht übernommen wird.
Gruß Ronald

**Comment by RoHa78** [comment]
Habe offenbar das Problem gelöst bekommen. Vermutlich waren irgendwelche Einstellung verbogen. Abhilfe schaffte ein Backup und anschließendes wieder einspielen desselben. An den Scripten und Einstellungen scheint sich dadurch vordergründig nichts verändert zu haben! Auch sind alle Addons wie vorher verfügbar und funktionieren!
Viele Grüße und nochmals vielen Dank für die tolle Arbeit!
