### ISSUE TITLE
HmIPW-DRAP mit aktuellster Firmware nicht kompatibel

### ISSUE THREAD

**Issue by c0d35io** [jens-maus/RaspberryMatic#901]
Vor der Installation von RaspberryMatic wurde auf der CCU3 ein Update auf die aktuellste Version (2.2.6) vorgenommen und dabei auch die Firmware des Homematic IP Wired Access Point (HmIPW-DRAP) aktualisiert. Nach anschließender Installation von RaspberryMatic (3.51.6.20200621) sind die Geräte des HmIPW-DRAP nicht mehr vorhanden und der Access Point lässt sich mit dem Fehler "Access Point Firmware is not compatible to the CCU" nicht verbinden:

![image](https://user-images.githubusercontent.com/37975503/92721945-24a20380-f367-11ea-97af-9df0f27b80d4.png)

**Comment by jens-maus** [comment]
Das ist natürlich normal, da die aktuelle RaspberryMatic Version auf der 3.51.6 CCU Firmware basiert (wie die Versionsnummer ja verrät). D.h. es muss hier entweder auf die 3.53.x version von RaspberryMatic gewartet werden oder die offizielle CCU3 3.53.x firmware genutzt werden. Alternativ dazu kann natürlich auch ein nightly snapshot von RaspberryMatic genutzt werden, allerdings würde ich das für das produktive System momentan nicht empfehlen.

**Comment by c0d35io** [comment]
Nachdem ich versucht habe die aktuelle CCU3 Firmware einzuspielen ([3.51.6 von der eq3 Homepage](https://www.eq-3.de/service/downloads.html?id=547)) konnte die CCU3 nicht mehr starten (led auf Raspberry leuchtet rot, sonst tut sich nichts -> Ethernet leuchtet nicht). Ein Boot in das CCU3 Recovery System war möglich aber auch hier war Backup einspielen bzw. Werkseinstellung wiederherstellen keine Lösung. RasperyMatic in 3.51.6 lässt sich aufspielen dann bootet die CCU3 wieder, spiele ich dann von der Weboberfläche wieder die originale CCU3 Firmware 3.51.6 ein das gleiche Fehlerbild. [Hier wird ein ähnliches Problem aus der Vergangenheit](https://homematic-forum.de/forum/viewtopic.php?t=53137#p529224) beschrieben. Gibt es noch eine Versionsinkompatibilität die ich übersehe? Ansonsten werde ich den Raspy wohl ausbauen müssen und an einen Monitor anschließen um Fehler sehen zu können oder gibt es da noch andere Möglichkeiten?
