### ISSUE TITLE
WebUI Ansicht soll nach Laden kein Mausklick benötigen, damit per Keyboard navigiert werden kann

### ISSUE THREAD

**Issue by TinkyWonky** [jens-maus/RaspberryMatic#904]
**Is your feature request related to a problem? Please describe.**
Es ist nervig, dass eine neu geladene WebUI-Ansicht (z.B. Liste der Systemvariablen, der Geräte o.Ä.) immer erst per Mausklick aktiviert werden muss, bevor per Tastatur gescrollt werden kann.

Geprüft mit Chromium-Browser 85.0.4183.83 und Firefox 80.0.1, beide unter Ubuntu Linux.

**Describe the solution you'd like**
Ich wünschte, der DIV "content" würde automatisch den Fokus erhalten, wenn die Seite geladen wird. Damit könnte mit den Tasten _PageUp/Down_ und _Home/End_ sehr viel schneller navigiert werden.

**Additional context**
Screenshot des betroffenen DIVs:
![grafik](https://user-images.githubusercontent.com/40147250/93013640-9b7b0e80-f5aa-11ea-98e0-1c2e3110a881.png)

**Comment by jens-maus** [comment]
Danke für den Hinweis. Es werden natürlich gerne auch PullRequests angenommen um diese Situation zu verbessern. Wenn hier also genügend KnowHow verhanden ist würde ich mich über einen entsprechenden PR hier freuen.
