### ISSUE TITLE
WebUI soll Scrollposition speichern und wiederherstellen, wenn in eine Ansicht zurückgekehrt wird

### ISSUE THREAD

**Issue by TinkyWonky** [jens-maus/RaspberryMatic#905]
**Is your feature request related to a problem? Please describe.**
Ich empfinde es als nervig, dass beim Zurückkehren in eine lange Liste (z.B. Geräteliste, Programmliste, Systemvariablen) immer der Beginn der Liste angezeigt wird. Das Verändern oder Neuanlegen eines Programms oder einer Variablen, das Editieren eines Geräts, das alles führt dazu, dass die Seite im Anschluss neu geladen wird und dabei stets zum Anfang der Liste zurückgekehrt wird.

**Describe the solution you'd like**
Ich wünschte, WebUI würde sich merken, an welcher Position in der Liste ich mich befand, als die Liste verlassen wurde, um die alte Position wiederherzustellen, wenn die Liste erneut angezeigt wird.

Zusammen mit Feature Request [904](https://github.com/jens-maus/RaspberryMatic/issues/904) würde dies die Arbeit in der WebUI erleichtern.

**Comment by jens-maus** [comment]
Duplicate of #869 

Hierfür bzw für #869 werden natürlich auch gerne PullRequests angenommen.
