### ISSUE TITLE
Geräteaustausch - "Konfigurationsdaten werden geladen" bleibt hängen (Firefox) 

### ISSUE THREAD

**Issue by friedpa** [jens-maus/RaspberryMatic#909]
**Describe the bug**
Beim Ersetzen eines Gerätes bleibt der Browser mit der Meldung "Konfigurationsdaten werden geladen" hängen...". Ein manueller Reload der Seite ist notwendig. Gerätetausch geht durch, aber die Konfigurationsdaten werden nicht übertragen.

**Expected behavior**
""Konfigurationsdaten werden geladen..." wird mit einem Reload der Seite oder einer Weiterleitung auf eine andere WebUI Seite abgeschlossen.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/42890695/93326236-c8345d80-f818-11ea-8d1e-8cd5b78abda1.png)

**System information (please complete the following information):**
 - Version: 3.51.6.20200621
 - Hardware: RaspberryPi4

**Comment by jens-maus** [comment]
Duplicate of #879
