### ISSUE TITLE
Art der Funkmodulanbindung (GPIO, HB-RF-USB, HB-RF-USB-2, HB-RF-ETH) im System hinterlegen

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#910]
**Describe the solution you'd like**
Beim Starten der RaspberryMatic sehe ich am Monitor das z.B. die HB-RF-USB erkannt wurde.
Diese Information sollten auch in eine Datei geschrieben werden bspw. /var/rf_connector
wo dann entsprechend GPIO | HB-RF-USB | HB-RF-USB-2 (und in Zukunft) HB-RF-ETH steht.

Als Alternative würde ich neue Einträge in der /var/hm_mode vorschlagen. Das hätte den Vorteil das alle relevanten Funkmoduldaten aus einer Datei auslesbar wären.

**Comment by alexreinert** [comment]
@jens-maus Bevor du da was einbaust: Ich habe da was fast Fertiges in den raw-uart Kernel Modulen, was die Info dann in einem sysfs Eintrag bereitstellt.

**Comment by jens-maus** [comment]
@alexreinert Das klingt super und wird sicher hilfreich dann sein. Dann muss ich nur noch bzgl. HmIP-RFUSB und ggf. HM-CFG-USB auf anderem Wege prüfen

**Comment by alexreinert** [comment]
HmIP-RFUSB wird auch von detect_radio_module unterstützt. HM-CFG-USB ist speziell, einfach deswegen, weil es kein Block Device hat, sondern rein per libusb angesteuert wird.
Bei beidem ist aber klar, das es per USB angeschlossen ist, da ist die Frage, ob es überhaupt eine weitere Info braucht?

**Comment by jens-maus** [comment]
Stimmt, das HmIP-RFUSB wird ja auch von detect_radio_module unterstützt. kannst du das vielleicht um die Ausgabe erweitern über welches interface (USB, GPIO, HB-RF-USB, HB-RF-USB-2, HB-RF-ETH) das radio module angeschlossen ist? Das würde das ganze ggf. noch etwas mehr vereinfachen dann.

**Comment by alexreinert** [comment]
Nein, bis jetzt nutzt das Tool einfach irgendeinen Pfad und es ist dabei vollkommen egal, ob das ein raw-uart Device, ein TTY, ein Block Device oder sogar ein Socket ist. Das würde ich gerne so belassen, Stichwort "Separation of Concerns".

**Comment by jens-maus** [comment]
Soviel würde das IMHO doch nicht ändern. Du müsstest ja nur ne zusätzlich prüfung einbauen ob es ein raw-uart device ist und wenn ja das neue sysfs entry zusätzlich auslesen und mit ausgeben. Und für den Fall das es ein HmIP-RFUSB ist eben einfach "USB" ausgeben und als fallback ggf. GPIO. Aber es ist natürlich deine Entscheidung, sonst muss ich halt diese unterscheidung selbst im erkennungsscript weiterhin machen.

**Comment by alexreinert** [comment]
Die Erkennung, ob es ein raw-uart ist, ist nicht so wirklich trivial, außer man geht den dreckigen Weg über string pattern matching.
Du wirst aber in meinem Erkennungs-Script sehen, dass das Auslesen nicht wirklich schwierig ist und keinen Mehraufwand ggü. dem Parsen aus der Ausgabe vom detect_radio_module erzeugt, aber man im Erkennungs-Script sehr genau weiß, ob und welches raw-uart Device es ist und welchen sysfs Eintrag man da braucht.

**Comment by alexreinert** [comment]
Commit ist durch, hier sieht man, wie man an die Info kommt: https://github.com/alexreinert/debmatic/blob/a7df7ed58a2b31e26cc2313c60169ea881d91db9/debmatic/usr/share/debmatic/bin/detect_hardware.inc#L108
Die if Abfrage außendrum lönntest du dir einsparen, bei dir ist ja klar, dass du die Version drr Kernel Module aktiv hast, welche das unterstützen.

**Comment by jens-maus** [comment]
So, nun habe ich die entsprechenden Änderungen eingearbeitet sodass das neue `detect_radio_module` tool von @alexreinert mit dem nächsten nightly snapshot dann verwendet werden sollte. Ich würde daher darum bitten (vor allem @Baxxy13) alle verschiedensten Funkmodul-Konstellationen noch einmal unter den Gesichtspunkten dieses Issues, des #900 issues sowie des #911 issues einmal ausführlich zu testen und entsprechend zu berichten ob alles korrekt funktioniert.

**Comment by Baxxy13** [comment]
> ob alles korrekt funktioniert.

Direkt auf GPIO werden beide Funkmodultypen sauber erkannt. 
Auf meiner HB-RF-USB-TK (Version 1.3 - 01/2019) wird keines der beiden Funkmodule (RPI-RF-MOD / HM-MOD-RPI-PCB) erkannt. 
(Testsystem Pi4B)
```
Identifying Homematic RF-Hardware: ......ERROR: /dev/raw-uart: HmRF: none, HmIP: none, OK
Updating Homematic RF-Hardware: no GPIO/USB connected RF-hardware found
```
Um Hardwareprobleme mit der HB-RF-USB auszuschließen habe ich sie mit beiden Modultypen an einer RaspberryMatic 3.53.30.20200919 (OVA VirtualBox unter Windows) getestet. Hierbei wurden beide Module erkannt und waren benutzbar.

**Comment by jens-maus** [comment]
@Baxxy13 Ok, danke für die Rückemeldung. Denke ich hab das Problem gefunden. Bitte das nächste nightly snapshot probieren und dann zurückmelden und bitte auch gleich mal testen/anschauen ob die anderen Dinge auch noch gehen (siehe z.B. #900)

**Comment by Baxxy13** [comment]
> gleich mal testen/anschauen ob die anderen Dinge auch noch gehen

So, beim Morgenkäffchen die Konstellation Pi4B mit HM-MOD-RPI-PCB auf HB-RF-USB getestet. Sieht gut aus. 
Anschluss und Modul werden korrekt erkannt, alle Funkmodul-Daten passen und stehen an den korrekten Stellen.
```
Auflistung der gefundenen BidCos-Adressen:
BidCoS-Adresse der HM-RCV-50 (nutzt das Analyzer-Script für seine Anzeige): 6969857
BidCoS-Adresse aus /etc/config/ids (die aktuell genutzte Adresse): 0x6A5A01
BidCoS-Adresse aus /var/ids (beim Systemstart ausgelesene Adresse): 0x6A5A01

Funkmodul-Daten des aktuellen Moduls:
Funkmodul Typ: 'HM-MOD-RPI-PCB'
Funkmodul Anschluss: 'HB-RF-USB@usb-0000:01:00.0-1.3'
Funkmodul RF-Firmware: 2.8.6 |	RF-Seriennr.: PEQ0532930
Funkmodul IP-Firmware: 2.8.6 |	IP-Seriennr.: PEQ0532930

Funkmodul-Daten des initialen Moduls:
Funkmodul Seriennr.: PEQ0532930 
```
Testergebnisse zu den anderen Konstellationen reiche ich später nach.

**Comment by jens-maus** [comment]
> Eine Sache ist mir aber noch aufgefallen bzw. nicht ganz klar. Haben beide Modultypen 2 verschiedene Seriennummern? Also für den IP und BidCos Teil? Man sieht ja das beim kleinen Modul immer eine PEQxxxxxxx Serial rauskommt und beim großen Modul ein anderes "Format". Scanne ich aber den QR-Code auf den RPI-RF-MOD's erhalte ich auch eine PEQxxxxxxx Seriennummer.
> 
> Hier geht es mir nur um's Wissen, Handlungsbedarf sehe ich nicht. Würde man hier etwas ändern müsste @HMMike wohl einige SDV Lizenzen neu vergeben da diese an die, in der /var/ids hinterlegte, SerialNumber gekoppelt sind.

Dazu müsste @alexreinert noch einmal etwas sagen. Sein `detect_radio_module` kennt nur eine Seriennummer je Modul und beim RPI-RF-MOD entspricht das immer den letzten 10 Zeichen der SGTIN und beim HM-MOD-RPI-PCB ist das eine solche PEQxxxxxx oder ähnlich lautendes Seriennummer. Allerdings kann/konnte man mit den eQ3 eigenen Tools (`eq3configcmd`) auch für das RPI-RF-MOD die alte Seriennummer im PEQxxxxxx Format auslesen lassen. Das geht mit `detect_radio_module` nicht – was per se zwar nicht kritisch ist, aber ggf. fragwürdig ob man dem tool nicht auch das auslesen dieser (nennen wir es einmal) "BidCos-Seriennummer" beibringen könnte.

**Comment by alexreinert** [comment]
Du hattest zu Anfangszeiten des RPI-RF-MOD ja den Wunsch von eQ-3 an mich rangetragen, beim RPI-RF-MOD nicht die Serial zu nehmen, welche vom Funkmodul geliefert wird, sondern die letzten 10 Ziffern der SGTIN. Genau so ist das im detect_radio_module umgesetzt.
Das jetzt zu ändern wäre ein ziemlicher Breaking Change und mir fehlt jetzt grade die Fantasie, warum man das jetzt ändern sollte.

**Comment by jens-maus** [comment]
@alexreinert Du hast natürlich vollkommen Recht, Alex. Das hatte ich gänzlich vergessen. Für eQ3 gibt es faktisch für die RPI-RF-MOD Platinen lediglich die Seriennummer als die letzten 10 Ziffern der SGTIN auch wenn man die alte Art der Seriennummerierung auch noch aus dem Modul herausbekommt erscheint es mir richtig das nun so zu belassen, auch wenn dann in Logfiles, etc. hier/da immer noch die alte art der Seriennummer auftaucht (z.b. im rfd log). Aber das sollte verschmerzbar sein.

**Comment by Baxxy13** [comment]
So wie es aussieht hat eQ-3 mit der 3.53.34 seine Hausaufgaben gemacht. Hier werden nun soweit auch alle relevanten Funkmoduldaten korrekt ausgelesen und gespeichert. Nur das...  

> Für eQ3 gibt es faktisch für die RPI-RF-MOD Platinen lediglich die Seriennummer als die letzten 10 Ziffern der SGTIN

passt nicht ganz zur Ausgabe meines Analysescriptes.
**CCU3 3.53.34:**
```
Auflistung der gefundenen BidCos-Adressen:
BidCoS-Adresse der HM-RCV-50 (nutzt das Analyzer-Script für seine Anzeige): 16743948
BidCoS-Adresse aus /etc/config/ids (die aktuell genutzte Adresse): 0xFF7E0C
BidCoS-Adresse aus /var/ids (beim Systemstart ausgelesene Adresse): 0xFF7E0C

Funkmodul-Daten des aktuellen Moduls:
Funkmodul Typ: 'RPI-RF-MOD'
Funkmodul Anschluss: 'RPI-RF-MOD'
Funkmodul RF-Firmware: 4.2.6 |	RF-Seriennr.: PEQ1840652
Funkmodul IP-Firmware: 4.2.6 |	IP-Seriennr.: 98A9A57E0C

Funkmodul-Daten des initialen Moduls:
Funkmodul Seriennr.: 98A9A57E0C
```
**RaspberryMatic-3.53.30.20201027:**
```
Auflistung der gefundenen BidCos-Adressen:
BidCoS-Adresse der HM-RCV-50 (nutzt das Analyzer-Script für seine Anzeige): 16743948
BidCoS-Adresse aus /etc/config/ids (die aktuell genutzte Adresse): 0xFF7E0C
BidCoS-Adresse aus /var/ids (beim Systemstart ausgelesene Adresse): 0xFF7E0C

Funkmodul-Daten des aktuellen Moduls:
Funkmodul Typ: 'RPI-RF-MOD'
Funkmodul Anschluss: 'GPIO'
Funkmodul RF-Firmware: 4.2.6 |	RF-Seriennr.: 98A9A57E0C
Funkmodul IP-Firmware: 4.2.6 |	IP-Seriennr.: 98A9A57E0C

Funkmodul-Daten des initialen Moduls:
Funkmodul Seriennr.: 98A9A57E0C

```
RF-Seriennr.: PEQ1840652 (CCU3) <---> RF-Seriennr.: 98A9A57E0C (RM)

**Comment by jens-maus** [comment]
> So wie es aussieht hat eQ-3 mit der 3.53.34 seine Hausaufgaben gemacht. Hier werden nun soweit auch alle relevanten Funkmoduldaten korrekt ausgelesen und gespeichert. Nur das...

Na 3x darfst du raten von wem Sie Ihre Hausaufgaben vorgelegt bekommen haben? ;-)

> > Für eQ3 gibt es faktisch für die RPI-RF-MOD Platinen lediglich die Seriennummer als die letzten 10 Ziffern der SGTIN
> 
> passt nicht ganz zur Ausgabe meines Analysescriptes.
[...]
> RF-Seriennr.: PEQ1840652 (CCU3) <---> RF-Seriennr.: 98A9A57E0C (RM)

Das ist in der Tat noch ein Unterschied. Ist aber auf ein geringfügiges Problem in der CCU3 Firmware (bzw. des init skriptes) zurück zu führen und wir von Seiten der CCU noch angeglichen werden damit es wieder mit früheren Versionen konsistent ist. Es bleibt also dabei, ein RPI-RF-MOD is lediglich an einer Seriennummer auszumachen und das ist die auf 10 zeichen gekürzte Endung der SGTIN.
