### ISSUE TITLE
Diagrammdaten (*.rrd's) werden in der .ova-Version nicht permanent gespeichert

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#913]
**Describe the bug**
In der .ova-Version der RaspberryMatic werden die Diagrammdaten anscheinend nicht in das automatisch gemountete Dateisystem (/usr/local/sdcard) geschrieben. Es gibt zwar ein /tmp/measurement Verzeichnis in dem zur Laufzeit auch *.rrd's vorhanden sind, aber es gibt weder ein /usr/local/sdcard/measurement Verzeichnis noch werden die *.rrd's anderweitig abgespeichert.
Demzufolge sind nach einem Reboot alle Diagrammdaten weg. 

**To Reproduce**
1. erstelle ein Diagramm mit einigen Sensorwerten und lasse es ein paar Stunden laufen
2. starte die RM neu
3. rufe das erstellte Diagramm auf
4. es erscheint "Für dieses Diagramm stehen noch keine Daten zur Verfügung."

**Expected behavior**
Wie in den anderen RM-Versionen auch sollten die Diagrammdaten sauber gespeichert und auch nach einem Neustart noch vorhanden sein.

**System information (please complete the following information):**
 - Version [RaspberryMatic 3.53.30.20200919]
 - Hardware [Windows-Host mit VirtualBox 6.1.12 r139181]

**additional Content**
[Probleme eines Nutzers der .ova-Version im Homematic-Forum](https://homematic-forum.de/forum/viewtopic.php?f=65&t=61042)

**Comment by jens-maus** [comment]
Danke! Ist bekannt ob das Problem erst mit der 3.53.30.20200919 auftritt?

**Comment by Baxxy13** [comment]
Hmm, glaube nicht wenn man den Thread im HomeMatic-Forum so liest. Da wurde ja noch nicht auf die 3.53.30.20200919 geupdated. 
Aber ich teste das mal mit einer RaspberryMatic 3.51.6.20200621 über Nacht.

**Comment by Baxxy13** [comment]
Ging etwas schneller:
Die 3.51.6.20200621 hat das gleiche Problem.
Mit der RaspberryMatic 3.51.6.20200229 tritt das Problem nicht auf.

Dazwischen lag ja die RaspberryMatic 3.51.6.20200420 mit folgender Änderung.
>>implemented a new delayed diagram storage mechanism which will make sure that the rrd files of the HMIPServer diagram functionality are only saved in fixed time intervals (every 10 minutes) rather than as soon as they are updated. This should prevent that USB/SD cards die way to early since the rrd files can be updated too often. In addition, they usually store the updated data on the same disk blocks and thus run too fast into the maximum memory cell limitation. Now the new mechanism will also make sure that different cells are used on every rrd file update and thus prevent the wear levelling to be exhausted too fast.

Könnte das die Ursache sein?

**Comment by jens-maus** [comment]
@Baxxy13 So, hab mir mal das ganze angeschaut und denke ich ab die Ursache gefunden und repariert. Bitte mal mit dem nächsten kommenden nightly snapshot probieren und melden falls das Problem noch bestehen sollte.
