### ISSUE TITLE
Speicherpfad der Diagrammdaten (*.rrd's) durch den User anpassbar machen

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#914]
**Is your feature request related to a problem? Please describe.**
Die Diagrammdaten (*.rrd's) werden ja "zwingend" in ein fest vorgegebenes  Verzeichnis geschrieben... oder halt gar nicht.

- bei einem RaspberryPi / Tinkerboard mit USB-Stick: `/media/usb0` --> `/media/usb1/measurement`
- bei der .ova-Version: `/media/usb0` --> `/usr/local/sdcard/measurement`
- bei einem USB-Boot only Pi: --> keine Speicherung möglich
 
Das finde ich insgesamt gesehen recht unflexibel (.ova) und unschön (Pi USB-Boot only).

**Describe the solution you'd like**
Mir würde ein Lösung gefallen die ähnlich der Anpassung der Backup-Pfade funktioniert. Also eine Datei in `/etc/config` z.B. `chartSavePath`  anlegen in der der vollständige Pfad zum Speicherverzeichnis für die Diagrammdaten angegeben wird. Dieser Pfad kann dann bspw. ein Netzwerkmount oder ähnliches sein.

**Comment by jens-maus** [comment]
Ab dem kommenden nightly snapshot sollte es nun möglich sein eine `/etc/config/CustomStoragePath` Datei zu setzen in der der Pfad zur Speicherung der Diagramme und Backups hinterlegt werden kann. Hier kann nun ein Netzwerkpfad oder ein lokaler Pfad angegeben werden und dieser sollte dann enstprechend genutzt werden.

**Comment by roe1974** [comment]
Kurze Frage dazu: wo ist der Unterschied zur "CronBackupPath" Datei in /etc/config/ ?

lg Richard

**Comment by Baxxy13** [comment]
> Hier kann nun ein Netzwerkpfad oder ein lokaler Pfad angegeben werden und dieser sollte dann enstprechend genutzt werden.

Hi Jens,
da jetzt die Zeit für mich gekommen ist das einzusetzen bin auch auf Probleme gestoßen.

Ich erzeuge über die `/usr/local/etc/rc.local` den Netzwerk-Mount mit...
`mount -t cifs -o noserverino,vers=3.0,username=USER,password=PASS //192.168.1.1 /fritz.nas /mnt`
Das funktioniert, das Netzlaufwerk ist erreichbar.
Um das als "Standardpfad" zu nutzen habe ich die `/etc/config/CustomStoragePath` mit dem Inhalt: `/mnt` angelegt.
Die WebUI zeigt auch...
![customstoragepath_1](https://user-images.githubusercontent.com/54898249/125488664-9845f516-9045-4336-87c9-ddc5773c4b1b.JPG)
Klicke ich jetzt aber auf "Daten sichern" passiert das...
![GIF 13 07 2021 18-21-28](https://user-images.githubusercontent.com/54898249/125489041-b117ade4-3486-48d8-b0a8-1b8328c21ea9.gif)
Man sieht auch das im Netzlaufwerk das Verzeichnis "measurement" nicht angelegt wird.
Führe ich testweise `/bin/cronBackup.sh` aus wird aber korrekt im Netzlaufwerk das Backup angelegt.

Ich vermute hier ein "Timing-Problem", also der mount durch `rc.local` wird erst durchgeführt wenn der `CustomStoragePath` schon festgelegt ist.

SummaSummarum...:
`CustomStoragePath` funktioniert, aber nicht für den Speicherpfad der Diagramme.
