### ISSUE TITLE
Firmware upload dauert ewig

### ISSUE THREAD

**Issue by alexhass** [jens-maus/RaspberryMatic#917]
Ich nutze raspmatic noch nicht lange, aber ist es normal, dass der upload über 1h dauert?

Beim initialen wechsel von ccu3 nach raspmatic habe ich locker 1,5h gewartet bis der upload abgeschlossen war.ich finde das für 300mb nicht normal. Da steckt doch sicher eine sd karte typ 10 drin? Selbst wenn das über die lahme netzwerk zu usb bridge geschoben wird sollte das nicht soooo lange dauern.

Jetzt habe ich heute das update von 3.51 auf 3.53 gestartet und jetzt läd er schon wieder seit 45 minuten die datei hoch.

Keine ahnung wann das dieses mal fertig wird.

**Comment by jens-maus** [comment]
Nein, das ist nicht normal und deutet eher darauf hin das es irgendein Problem mot der SD Karte gibt. Würde einen Wechsel der SD Karte vorschlagen mit neuinstallation und zurückspielen des Backups.

Da dies aber definitiv kein Problem/Bug ist gibt es hier auch nichts weiter zu diskutieren, weil dies hier eben der Bug/Issue Tracker ist und kein Diskussionsforum

**Comment by alexhass** [comment]
Was ist eine normale Zeit?

**Comment by jens-maus** [comment]
?

**Comment by alexhass** [comment]
Hab es jetzt mal mit einer neuen SD card (SanDisk MAX ENDURANCE, 32GB) gestoppt, damit zukünftig jeder der Abweichungen sieht, weiß, dass etwas nicht stimmt. Zuletzt konnte ich keinerlei Update mehr von 3.51 auf 3.53 machen. Auch nach mehreren Stunden wurde der Lizenzvertrags-Dialog nicht angezeigt. Der Upload war aber vorher mit 100% completed.

1. Upload der ZIP Datei abgeschlossen nach 00:35
2. Dialog mit Lizenzvertrag erscheint bei 04:30
3. Software Update vom Lizenzdialog bis zum reboot (3.51.6.20200621 -> 3.53.20.20200919) dauert 03:25 bis **DONE**.

Das wird erst angezeigt, nachdem man einen Reload macht - und nicht von allein.

Displaying running firmware update output:
==========================================
Starting firmware update (DO NOT INTERRUPT!!!):
[1/5] Validate update directory... OK
[2/5] Checking update_script... no 'update_script', OK
[3/5] Checking for rootfs filesystem images... none found, OK
[4/5] Checking for bootfs filesystem images... none found, OK
[5/5] Checking for sdcard image... found, flashing bootfs...........OK, flashing rootfs......................................OK, DONE
Finished firmware update successfully.

==========================================
Browser closed connection.

4. Der Reboot zu 3.53 dauert ca. 20 Sekunden. Sicherlich alles reproduzierbar auf jeder CCU3.
