### ISSUE TITLE
IP-Dimmer: Einschaltzeit wird auch als Rampenzeit ausgewiesen

### ISSUE THREAD

**Issue by dehell** [jens-maus/RaspberryMatic#918]
**Describe the bug**
Bei den Dimmern HmIP-BDT und HmIP-DRDI3 wird die Einschaltdauer bei Schaltpunkten im Wochenprogramm auch als Rampenzeit angezeigt
**To Reproduce**
1. Einen Schaltzeitpunkt im Wochenprogramm des Gerätes erstellen Einstellungen/Geräte/Dimmerxy
2. Helligkeit auf einen Wert ungleich 'aus' setzen, es erscheint eine Eingabemöglichkeit für die Rampenzeit und eine für die Einschaltdauer.
3. Einschaltdauer auf z.B. 1x Stunde setzen, Rampenzeit auf 0 belassen
4. Einstellungen zum Gerät übertragen
5. Gerät auslesen, in dem Schaltpunkt steht jetzt auch die Rampenzeit auf 1x Stunde

**Expected behavior**
Die Rampenzeit sollte völlig unabhängig einstellbar sein, es ist entweder ein Darstellungs- oder Funktionsproblem.

**Screenshots**
![image](https://user-images.githubusercontent.com/26470288/94027145-d35c3000-fdba-11ea-8c35-71698e087493.png)

**System information (please complete the following information):**
 - RaspberryMatic 3.53.30.20200919
 - RaspberryPi3
 - HmIP-BDT V1.4.8
 - HmIP-DRDI3 V1.2.0

**Additional context**

**Comment by dehell** [comment]
Hier die Antwort des eq3 Supports:
Guten Tag Herr xxx,

vielen Dank für Ihre Nachricht.

Einen Support für die Verhaltensweise von Geräten an Communitylösungen, wie z.B. Raspberrymatic, DepMatic o.ä., bieten wir im Rahmen unseres Kundenservice nicht an.
Daher können wir Ihnen zu Ihrer Anfrage keine Unterstützung anbieten.

Wir empfehlen Ihnen daher sich hierzu an den Anbieter der Lösung oder an das Homematic Forum zu wenden.

Sofern Sie einen Herstellersupport wünschen, empfehlen wir auf eine Smarthomezentrale CCU3 zu wechseln.

Mit freundlichen Grüßen aus Leer

Ihr eQ-3 Support-Team

**Comment by Sineos** [comment]
Immer wieder herzerwärmend zu sehen, wie viel den Firmen an einem vernünftigen Kundendienst liegt. Engagement, Kundenähe ... einfach toll.

**Comment by jens-maus** [comment]
Oh, ich hatte natürlich vergessen zu erwähnen das man das Problem natürlich erst mit der originalen CCU3 Firmware versuchen muss zu reproduzieren um es dann auch so an eQ3 zu melden. Bleibt also nichts anderes übrig als das Problem ggf. in der Community selbst zu reparieren (wenn das geht und es in der Tat eins ist). Wer das also reproduzieren kann einfach hier mal vortreten und sagen was stattdessen an der Stelle in der WebUI auftauchen müsste.

**Comment by isi07** [comment]
Hallo
ich kann das Problem in meinem System bestätigen bzw. reproduzieren.
Für mich sieht es nach einem Darstellungsproblem in der WebUI aus.
Ich habe das Problem mit einem HmIP-PDT, version 1.4.8
Man kann in der WebUI zwar die Rampenzeit unanabhängig einstellen, aber die WebUI-Anzeige scheint dann bei einem weiteren Aufruf in der Rampenzeit dann fälschlicheriweise die Anschaltdauer anzuzeigen.
Wenn ich mir das Wochenprogramm auf dem iPhone mit pocketControl anschaue, sieht alles richtig aus.

Mein System:
VERSION=3.53.34.20201121
PRODUCT=raspmatic_rpi4
PLATFORM=rpi4

![HomeMatic WebUI und 4 weitere Seiten - Persönlich – Microsoft​ Edge 29 11 2020 09_40_30_LI](https://user-images.githubusercontent.com/65848350/100537486-4ce42480-3229-11eb-8d17-c0af5e6c0e35.jpg)
![IMG_3600](https://user-images.githubusercontent.com/65848350/100537500-700ed400-3229-11eb-894b-17aab7c0e632.PNG)
![IMG_3601](https://user-images.githubusercontent.com/65848350/100537501-70a76a80-3229-11eb-99bf-b7bcdf2b4836.PNG)

Viele Grüße
Christian

**Comment by jp112sdl** [comment]
Die Config-Seiten von HmIP-Geräten werden m.W. nur aus dem HMIPServer geladen.
Kann dann also nur von eQ-3 gefixt werden.

**Comment by isi07** [comment]
OK, ich habe die HmIP-PDT an einer original CCU3 und habe dort das gleiche Fehlverhalten.
Ich melde das an eQ-3 und warte mal ab, was jetzt zurück kommt.

**Comment by isi07** [comment]
Antwort von eQ-3 => kein Support von eQ-3 für diese Funktion


Guten Tag Herr ,

vielen Dank für Ihre Nachricht.

Unsere Systeme nutzen eine offene Plattform für die Kommunikation. Dieses bietet Partnern, sowie der Community diverse Möglichkeiten der individuellen Entwicklung von Hard- und Software. Diese Gegebenheit stellt uns im Support vor die Herausforderung, Sie nicht bei all Ihren Fragen unterstützen zu können. Hierzu zählt u.a. Zusatzsoftware der Smarthome Zentralen, OEM-Bausätze/ -Produkte sowie Open Source Projekte sowie Raspberry PI. Wir empfehlen Ihnen daher sich direkt an den Partner oder die Community zu wenden.

Die bewusst offen gehaltene Plattformstruktur führt dazu, dass wir in unseren Smarthome Zentraleinheiten Funktionen (z.B. Expertenparameter, Skriptschnittstelle oder dem Automatisierungseditor) bereitstellen, welche wir nicht bis ins letzte Detail dokumentieren und supporten.

Aus Kosten- und Kapazitätsgründen besteht die Grenze unseres Supports darin, dass wir Ihnen Fragen zur allgemeinen Anwendung und Konfiguration unserer Produkte beantworten. Durch die vielfältigen Möglichkeiten in der Programmierung und Automatisierung ist eine Individualbewertung nicht möglich.

Unsere speziell geschulten Installationspartner beraten Sie gerne bei allen Fragen rund um die Smarthomewelt.

Anhand von Ihren Wünschen, den örtlichen Gegebenheiten und der vielfältigen Möglichkeiten der Systeme kann dieser eine optimale Auslegung durchführen. Hierbei kann er ebenfalls Partnerlösungen oder Komplementärprodukte aus dem Elektrogroßhandel mit einbeziehen. Durch einen lokalen Installationspartner haben Sie zudem den Vorteil eines kompetenten Ansprechpartners in Ihrer Nähe, welcher mit Ihrer Anlage vertraut ist.

Eine Übersicht der Installationspartner finden Sie hier:
https://www.eq-3.de/partner/installationspartner.html

Mit freundlichen Grüßen aus Leer

Ihr eQ-3 Support-Team

eQ-3 AG
Maiburger Straße 29
26789 Leer
www.eq-3.de
support@eq-3.de

**Comment by Puddle-Jumper** [comment]
Ich hatte auch an eq3 geschrieben. Folgende Antwort:

vielen Dank für Ihre Nachricht.

Wir haben Ihr Anliegen geprüft und können Ihnen keine kurzfristige Lösung anbieten. Daher wurde Ihr Sachverhalt zur Prüfung und Bewertung weitergegeben.
Sofern Optimierungen möglich sind, fließen diese in die Releaseplanung ein. Bitte haben Sie Verständnis, dass eine individuelle Rückmeldung in diesem Fall leider nicht erfolgen kann.

Sollten Sie Rückfragen zu diesem Ticket haben, achten Sie bitte darauf, die folgende Ticketnummer oben im Betreff anzugeben.
Ticket: xxx

Mit freundlichen Grüßen aus Leer

Ihr eQ-3 Support-Team

**Comment by dehell** [comment]
Mit dem Update vom 26.12.20 ist der Fehler behoben.
