### ISSUE TITLE
Öffnen von "Allgemeine Kanaleinstellungen" dann schließen mit "OK" wirft ERROR Meldungen ins Log

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#919]
**Describe the bug**
Beim Öffnen der "Allgemeine Kanaleinstellungen und anschließendem druck auf "OK" wird jedes mal eine ERROR-Meldung im Log nach folgendem Schema generiert:
```
Sep 24 23:38:48 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: foreach(): invalid expression used [ExecForEach():iseESPexec.cpp:515]
Sep 24 23:38:48 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: integer devId = 22949;string action= 'setVisible';integer iVis = 1; [ExecError():iseESPexec.cpp:12885]

```
Die sichtbare ID entspricht dabei dem Kanal dessen "Allgemeine Kanaleinstellungen" geöffnet waren. 
Negative Auswirkungen konnte ich auf die Schnelle nicht feststellen, buggy ist es aber allemal.

**To Reproduce**
1. zu Startseite > Einstellungen > Geräte gehen 
2. einen Kanal eines Gerätes anklicken 
3. das Fenster "Allgemeine Kanaleinstellungen: xxxxxxx:x mit "OK" schließen
4. im syslog die generierte ERROR-Meldung sehen

**Expected behavior**
Ein simples Öffnen und Schließen der "Allgemeinen Kanaleinstellungen" sollte keine Fehlermeldungen produzieren.

**Screenshots**

**System information (please complete the following information):**
 - Version [RaspberryMatic 3.53.30.20200919]
 - Hardware [RaspberryPi3B+]

**Additional context**
Ein Kurzer Gegentest mit einer RaspberryMatic 3.51.6.20200621 erzeugte keine ERROR-Meldungen.
Auf einer CCU3 3.53.30 werden die ERROR-Meldungen ebenso generiert.

**Comment by jens-maus** [comment]
Danke für den Bugreport. Den Fehler kann ich in der Tat hier bestätigen. Das ganze scheint auf die Nutzung der `EnumChannelGroups()` Funktion zurückzuführen zu sein. Genutzt wird diese anscheinend hier:

https://github.com/eq-3/occu/blob/master/WebUI/www/rega/esp/devices.fn#L135

Und folgendes kurzes ReGa-Testprogramm liefert den selben Fehler im `/var/log/messages` logfile:

```
object oid = dom.GetObject(1012);
WriteLine(oid);
string tmp="";
foreach(tmp, oid.EnumChannelGroups(false))
{
  WriteLine(tmp);
}
```

Auch ein noch simpleres Skript liefert den selben fehler:
```
object oid = dom.GetObject(1012);
WriteLine(oid);
WriteLine(oid.EnumChannelGroups(false));
```

Was mich allerdings wundert ist das angeblich der Fehler in der 3.51.6.20200621 nicht auftreten soll. Meinen kurzen Tests nach sollte auch dort der Fehler auftreten. Bitte also noch einmal mit den oberen Skripten testen. Vielleicht kann ja @HMMike dazu selbst einmal recherchieren während ich in ReGa selbst auf Ursachenforschung gehe.

**Comment by Baxxy13** [comment]
Deine Testscripte erzeugen den Fehler auch in der 3.51.6.20200621. Die oben angegeben Schritte zum reproduzieren des Fehlers
aber nicht. Sonst wäre das sicher schon früher jemandem aufgefallen.

**Comment by jens-maus** [comment]
Nun wäre eben die Frage was sich seit der 3.53.x nun geändert hat was zum auftauchen dieses Fehlers führt?!? Noch kann ich das leider nicht einschätzen. ReGaHss selbst wurde ja diesbzgl. nicht geändert. Es muss also irgendetwas anderes dazu geführt haben das die `EnumChannelGroups()` funktion nun diese ScriptRuntimeError erzeugt (vmtl. weil sich irgendetwas an den Objekten geändert hat?!?)

**Comment by jens-maus** [comment]
Ok, etwas weiter. Die Funktion `EnumChannelGroups()` ist eigentlich nur auf Geräte (Devices) anwendbar. D.h. wenn du mal versuchst direkt ein Gerät umzubenennen sollte das keinen Fehler werfen, sondern nur wenn du einen Kanal eines Gerätes umbenennen willst. Wenn sich das bestätigt dann hat sich irgendetwas in der WebUI von 3.53.x geändert da diese `EnumChannelGroups()` Funktionen nun ausgeführt werden obwohl sie das nicht sollten (sind wie gesagt nur auf ein Gerät und nicht auf ein Kanal anwendbar).

**Comment by Baxxy13** [comment]
> D.h. wenn du mal versuchst direkt ein Gerät umzubenennen sollte das keinen Fehler werfen, sondern nur wenn du einen Kanal eines Gerätes umbenennen willst.

So ist es. Nur bei den Kanälen wird die ERROR-Meldung generiert, beim Gerät selber nicht.

**Comment by jens-maus** [comment]
Na dann wissen wir ja was schuld ist: Eine von eQ3 vorgenommene Änderung in der WebUI die dazu führt das dieser teil der WebUI ausgeführt wird und dann `EnumChannelGroups()` auf Kanäle nun ausgeführt wird – was allerdings nicht passieren sollte. Muss man sich also mal die Differenzen zwischen 3.51.x und 3.53.x anschauen um rauszubekommen welche Änderung das war und diese dann ggf. zurückbauen...

**Comment by jp112sdl** [comment]
> Muss man sich also mal die Differenzen zwischen 3.51.x und 3.53.x anschauen um rauszubekommen welche Änderung das war und diese dann ggf. zurückbauen...

Aber keine der WebUI-Files, die man im OCCU bei der Suche nach `EnumChannelGroups` findet, wurde in den letzten FW-Versionen verändert...

**Comment by jens-maus** [comment]
@jp112sdl Das stimmt, jedoch gibt es Änderungen bzgl. "Visible" wenn man einmal im Diff nachschaut und ich denke hier handelt es sich um irgendeine regression durch diese Änderungen...
