### ISSUE TITLE
Wiederherstellung von Backup funktioniert nicht

### ISSUE THREAD

**Issue by alexhass** [jens-maus/RaspberryMatic#920]
**Describe the bug**
Uploading a CCU3 v3.51 backup to 3.53 OVA does not restore the backup

**To Reproduce**
1. Create Backup with button on CCU3 with Raspmatic v3.51
2. Save backup to disk
3. Open OVA 3.53 and upload this backup
4. A login dialog appear, enter credentials
5. Nothing happend. Devices are not visible.

**Expected behavior**
Backup should be restored

**System information (please complete the following information):**
 - Version 3.51/3.53
 - Hardware CCU3

**Comment by jens-maus** [comment]
@alexhass Was kommt denn für eine Fehlermeldung?

**Comment by alexhass** [comment]
Gibt keine Fehlermeldung. Nach dem Upload kommt der Login und dann bin ich wieder auf der Hauptseite.

Da ich nicht weiß, wie der normale Ablauf hier wäre (erster Restore in meinem Leben), weiß ich leider nicht wie es aussehen sollte/könnte. Die OVA ist jungfräulich. Habe nichts außer einem Usernamen und Passwort eingegeben.

**Comment by Baxxy13** [comment]
Kurz getestet.
Keinerlei Probleme ein mit RaspberryMatic 3.53.30.20200919 (Pi3B+) erstelltes Backup auf einer jungfräulichen RaspberryMatic 3.53.30.20200919-ova (Windows VirtualBox) einzuspielen.

**Comment by jens-maus** [comment]
@Baxxy13 Der Autor (@alexhass) hat wohl ein CCU3 3.51 backup versucht in eine OVA zu installieren. Das müsste man ggf. noch einmal verifizieren.

**Comment by Baxxy13** [comment]
> hat wohl ein CCU3 3.51 backup versucht in eine OVA zu installieren.

Kann man so oder so lesen / deuten. 


> 1. Create Backup with button on CCU3 with Raspmatic v3.51

Da bräuchte man nochmal eine klarere Angabe von @alexhass

**Comment by alexhass** [comment]
Ich habe eine RaspberryMatic 3.51.6.20200621 backup in eine RaspberryMatic 3.53.30.20200919-ova (Windows, VirtualBox 6.1.14) eingespielt. Ich kann gern ein Video machen...

**Comment by jens-maus** [comment]
@alexhass Ok, dann hab ich das missverstanden. Das sollte natürlich gehen und so wie @Baxxy13 das auch probiert hat scheint es auch in der Tat zu gehen. Wichtig dabei ist natürlich das man vor Umstieg von einer CCU3 zur OVA auch alle Addons deinstalliert wie das hier beschrieben ist: https://github.com/jens-maus/RaspberryMatic/wiki/Installation#umstieg-zu-virtuellem-raspberrymatic

**Comment by alexhass** [comment]
Also ich habe mal definitiv keine Addons deinstalliert. Ich will ja, dass die Addons auf dem VM dann auch drauf sind. Ok, diesen Satz der Dokumentation kannte ich nicht, das ist aber wirklich unerwartet. Muss das sein? Ich hätte erwartet, dass man die Dateien einfach mit einspielen kann und gut is?

Eigentlich wollte ich nur testen, ob sich mein Backup überhaupt wiederherstellen lässt. Also ein klassischer Backup/Restore Test und genau das geht nicht. Nicht das ich mal geliefert bin, wenn die CCU3 komplett den Geist aufgibt.

**Comment by jens-maus** [comment]
@alexhass Und hatte die OVA beim einspielen schon ein Funkmodul angebunden oder hast du ohne jegliches Funkmodul versucht das Backup einzuspielen? Das kann mitunter dann nänlich auch probleme machen.

**Comment by alexhass** [comment]
Ne, hab keine Funkmodule in der vm Ich will ja nicht umstellen. 

Wollte nur wissen ob der Restore funktioniert und bissi spielen.

So ein Restore test scheint ja wirklich kompliziert zu sein... aber zugegeben ich wusste nicht, dass so viel dran hängt. klingt so, dass ich ne Notfalll Hardware brauche oder no risk no fun system fahren muss... eigentlich wollte ich nicht jeden Tag eine Kerze anzünden....

Sag mal... jetzt wo man die homematic ip points als router / bridge einspannen kann - könnte man da nicht ne vm nutzen und mit hmip-hap den funk machen? Ich hab da mehrere starterpacks... also kein mangel an hmip-hap :-). Eine vm ausfallsicher zu machen finde ich einfacher wie eine ccu3 ausfallsicher zu machen.

Wenn ihr schon am testen seid... ich hab in der vm den neuen button in der systemsteuerung gedrückt, um die hmip-hap points zu finden. Das geht in der vm nicht. Da kommt ein graues overlay und sonst nichts mehr. Aber vieleicht geht das nur mit unkonfigurierten hmip-hap. Muss ich nochmal nen brandneuen auspacken.

**Comment by jens-maus** [comment]
Für die vollumfängliche Funktion (auch das mit dem HmIP-HAP) ist auch hier ein Funkmodul (RPI-RF-MOD) notwendig. Also hier ohne funkmodul "rumspielen" zu wollen ergibt keinen Sinn und provoziert nur solche Fehler.

Und für die anderen Dinge das HomeMatic Forum verwenden, das hier ist ein Bugtracker und eine Entwicklungsplatform und kein Diskussionsforum.

**Comment by alexhass** [comment]
Ist der redtore bug schon gelöst, oder warum machst fu den case zu?

**Comment by alexhass** [comment]
Naja, ich finde es ist offensichtlich. Vieleicht ein Feature aber man kann es auch als Designfehler sehen

Wenn ein backup eingespielt wird, das teilweise inkompatibel ist, sollte man alles beim import ausnehmen, dass inkompatibel ist. Alles was nicht importiert werden konnte sollte aber dem user angezeigt werden, dass es aus dem backup nicht hergestellt werden konnte. Vieleicht kann ich damit leben, dass nur 90% hergestellt wird, dann muss ich nur 10% nachziehen.

Backup software stellt auch alles her und wenn es irgendwo ein problem gibt sagt es, z.b. datei / datenbank konnte nicht wiedehergestellt werden. Dann habe ich eine option und kann suchen warum. Vieleicht war nur eine von 30 datenbanken durch etwss geblockt, oder ich hab vergessen alle sessions zu killen, etc.

Aber einfach nichts zu machen und nicht mal zu sagen was nicht geht - kann nur falsch sein.

**Comment by alexhass** [comment]
Backup einer CCU3 ließ sich auf einer neuen SD-Card in einer CCU3 wiederherstellen und auf den ersten Blick ist alles an seinem gewohnten Platz,
