### ISSUE TITLE
Boolsche Variablen / Regensensor Abfrage

### ISSUE THREAD

**Issue by friedpa** [jens-maus/RaspberryMatic#921]
**Describe the bug**
Ich habe fogendes Problem seit dem Einspielen von 3.53.30.20200919: Bis jetzt hat meine Regenerkennung mit folgender Abfrage funktioniert:

![grafik](https://user-images.githubusercontent.com/42890695/94272216-0a5d4d80-ff43-11ea-8b12-04cf6531e954.png)

In dem Feld gleich neben der Systemvariable kann ich entweder ein Leerfeld oder "nicht" auswählen. 
Aber aus irgendeinem Grund funktioniert diese Abfrage nun nicht mehr, wenn ich das leere Feld auswähle.
Mache ich da jetzt was falsch, oder ist das ein Bug?

Das gleiche passiert, wenn ich bei meinem Regensensor HM-Sen-RD-O den Zustand "Regen" abfrage ....

**Comment by jens-maus** [comment]
Gibt es irgendwelche Meldungen im `/var/log/messages` logfile zu der Zeit wenn dieses Programm ausgeführt wird?

**Comment by Baxxy13** [comment]
Keine Probleme solcher Art hier mit der 3.53.30.20200919 (Pi4B)
![SysVar_Bool_Trigger_Test_Prg](https://user-images.githubusercontent.com/54898249/94289972-d7728400-ff59-11ea-9c23-185b75ce4fbe.JPG)
![SysVar_Bool_Trigger_Test_Protokoll](https://user-images.githubusercontent.com/54898249/94290004-e5c0a000-ff59-11ea-9f53-5bd368f9f45e.JPG)

**Comment by friedpa** [comment]
Hallo Jens,
das LogFile: messages ist voll mit folgender Meldung:

![grafik](https://user-images.githubusercontent.com/42890695/94291179-8d8a9d80-ff5b-11ea-834a-98d665028ae9.png)

Sonst steht da nichts drinnen.
Redmatic wurde von mir deinstalliert, obwohl der Butto in der Systemsteuerung ist noch immer da.

**Comment by friedpa** [comment]
Ich habe jetzt nochmals die RedMatic installiert und werde ein Update des Logfiles in kürze hier posten.

**Comment by friedpa** [comment]
Das steht im LogFile:

![grafik](https://user-images.githubusercontent.com/42890695/94293050-0d196c00-ff5e-11ea-92a3-d303ad7540f0.png)

PEQ2220642 ist der Regensensor HM-Sen-RD-O

**Comment by jens-maus** [comment]
Das alles scheint mir mit deinem beschriebenem Problem nichts zu tun zu haben. Das Redmatic wurde damals nicht korrekt deinstalliert (war nen bug in früheren versionen). Aber bzgl deines beschriebenen problems sehe ich keine ausgaben die darauf schliessen lassen das es da ein problem mit booleschen bedingungen gibt. Bitte daher ein frisches programm anlegen mit einer einzelnen Bedingung und da dann entsprechend prüfen ob es da auch nicht geht.

**Comment by friedpa** [comment]
Auch nachdem ich jetzt die RedMatic korrekt deinstallieren konnte (danke für den hint) kommt jetzt periodisch der unten dargestellte Fehler. Die Boolsche Variablen lösen jetzt wieder aus, Der Regensensor geht auch weiterhin nicht (meaning: er löst nicht aus bei e.g. "Regen")

![grafik](https://user-images.githubusercontent.com/42890695/94307649-7ce72100-ff75-11ea-89a8-5557ca8266e8.png)

**Comment by jens-maus** [comment]
Na wenn die boolschen variablen wieder korrekt auslösen ist das hier diskutierte problem doch gelöst. Bitte hier nicht verschiedene dinge miteinander verzwirbeln. Ein Problem = ein Ticket. Jedoch bitte auch immer solche Probleme vorher am besten im HomeMatic Forum erst vorbringen und dort diskutieren bevor hier ein Bugreport aufgemacht wird.

**Comment by friedpa** [comment]
Hi Jens,
Ich werde das nicht Auslösen des Regensensors bei Status "Regen" in Programmen (mit obiger Fehlermeldung) im Forum behandeln.
Danke soweit für Deine Hilfe.
