### ISSUE TITLE
ReGaHss: Probleme mit Parser und verschachtelten Methodenaufrufen (z.B. neues GetObject() mit 2. optionalem Parameter)

### ISSUE THREAD

**Issue by HMMike** [jens-maus/RaspberryMatic#922]
GetObject wirft einen fehler, wenn es als Parameter in Methoden benutzt wird, wo ein Object Parameter möglich ist:

```
! Fall 1 geht nicht!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
xmlrpc.PutParamset(dom.GetObject("BidCos-RF"),"MEQ0330450:1","MEQ0330450:1","LONG_ON_TIME",0.6);
```

```
! Fall 2 geht
xmlrpc.PutParamset(interfaces.Get (1009),"MEQ0330450:1","MEQ0330450:1","LONG_ON_TIME",0.6);
````

```
! Fall 3geht
xmlrpc.PutParamset(interfaces.Get ("BidCos-RF"),"MEQ0330450:1","MEQ0330450:1","LONG_ON_TIME",0.6);
```

```
! Fall 4geht
xmlrpc.PutParamset(dom.GetObject("BidCos-RF",OT_INTERFACE),"MEQ0330450:1","MEQ0330450:1","LONG_ON_TIME",0.6);
```

```
! Fall 5geht
xmlrpc.PutParamset((dom.GetObject("BidCos-RF")),"MEQ0330450:1","MEQ0330450:1","LONG_ON_TIME",0.6);
```

```
! Fall 6geht
xmlrpc.PutParamset((dom.GetObject("BidCos-RF",OT_INTERFACE)),"MEQ0330450:1","MEQ0330450:1","LONG_ON_TIME",0.6);
```

Der erste Fall, den der Kollege hatte, geht reproduzierbar nicht !. tuts aber auf Vorgängerversionen. Geklammert wie in Fall 5 geht das auch. 

Referent Thread im HM Forum: https://homematic-forum.de/forum/viewtopic.php?f=65&t=61118

**Comment by jens-maus** [comment]
Hast du mal geschaut ob das nur bei diesen xmlrpc Aufrufen der Fall ist? Weil wenn das was generelles ist muss das doch eigentlich häufiger auftreten bzw. weisst das auf einen fundamentalen Fehler im Parser von ReGaHss hin und das wäre sehr komisch und unerwartet...

**Comment by jens-maus** [comment]
Nach etwas tieferen Recherchen und Tests zeigt sich das dies wohl ein tieferes Problem im Skriptparser von ReGaHss zu sein scheint. Schau dir mal folgenden Skript an:

```c++
string str="XXecho hallo123";
string stdout;

! Funktioniert
string str2=str.Substr(2);
system.Exec(str2, &stdout);
WriteLine(stdout);

! Funktioniert nicht
system.Exec(str.Substr(2), &stdout);
WriteLine(stdout);

WriteLine("END");
```

Dieser erzeugt folgende Ausgaben:
```
hallo123
```

Es sollte hier jedoch 2x das `hallo123` ausgegeben werden. Was man auch bei der Ausführung dieses Skriptes dann in `/var/log/messages` findet ist ein `ScriptRuntimeError` der darauf hindeutet das es sich hier um ein tieferes Problem zu handeln scheint.

Nach weiteren Analysen sieht es so aus, das folgende Bedingungen existieren müssen damit der Fehler austritt:

1. Die äußere Methode (hier `system.Exec()`) muss mehr als einen Parameter annehmen (d.h. 2 oder mehr)
2. Die innere Methode (hier `str.Substr()`) muss ebenfalls mehr als einen Parameter annehmen (d.h. 2 oder mehr)

Sobald diese Bedingungen gegeben sind und man verbindet die beiden Methoden in einem Aufruf wie oben gezeigt (`system.Exec(str.Substr(2), &stdout)`) kommt es zu dem hier beschriebenen Problem das der Parser fälschlicherweise das `&stdout` in der Auswertung des `str.Substr(2)` aufrufes versucht als vermeintlichen 2. Parameter der `Substr()` Funktion auszuwerten was wiederum zu dem ScriptRuntimeError führt. Entfernt man daraufhin z.B. das `&stdout` aus dem `system.Exec()` Aufruf kann er jedoch das `str.Substr(2)` korrekt auswerten und es kommt zu keinem ScriptRuntimeError und folglich zur korrekten Abarbeitung. Auch kann man z.B. einfach `str.Substr(2).ToString()` oder `(str.Substr(2))` (extra Klammerung) nutzen und der Parser löst das dann korrekt auf und auch dieser Aufruf funktioniert dann problemlos.

Wie also gesagt scheint das Problem völlig unabhängig der letzten Änderungen der `dom.GetObject()` Methode (Hinzufügen eines 2. Parameters) wohl bereits schon viel länger zu existieren und tritt jetzt eben nur bei `dom.GetObject()` zu Tage weil die Methode nun eben auch einen 2. optionalen Parameter annimmt und daher Analysen durchführt ob der zweite Parameter angegeben wurde oder nicht.

Die Frage wäre also ob frühere/frühe ReGaHss Versionen dieses Parser Problem noch nicht haben, oder ob der Parser schon immer dieses Defizit hatte und ich mir das dann gesondert anschauen müsste ob man das mit wenig Aufwand repariert bekommt. Wäre natürlich schön andere könnten hier noch weitere solche Tests durchführen und ggf. eben frühe ReGaHss Versionen einmal entsprechend durchtesten (was ich bei Gelegenheit natürlich dann auch noch machen werde).

**Comment by jens-maus** [comment]
Also ich bin mal schnell hingegangen und bin die ReGaHss binaries im OCCU zurück bis zur "Ursprungsversion" R1.00.0388.0102 (CCU Firmware 2.15.5 von 2106) gegangen und es sieht in der Tat so aus das selbst mit dieser Version das Problem bereits schon existiert und es wohl in der Tat kein in neuester Zeit reingewandertes Problem zu sein scheint. Vielleicht kann das ja mal jemand mit ähnlichen Tests mit dem oben gezeigten Testskript bestätigen.

**Comment by jens-maus** [comment]
Mit der nächsten kommenden ReGaHss Version (R1.00.0388.0224) sollte das Problem nun behoben sein und solche "nested Method Calls" problemlos möglich sein auch wenn die äußere und innere Methode mehr als ein Parameter annehmen können. Und nach weiteren Tests hat sich auch bestätigt das das Problem anscheinend schon immer in ReGaHss existiert hat und jetzt erst durch die Änderungen an `GetObject()` zu Tage gefördert wurde.
