### ISSUE TITLE
HmIP-BROLL-Firmware (1.6.2 => 1.8.16) - Shutterstate = 99.01 anstatt 100

### ISSUE THREAD

**Issue by oggy79** [jens-maus/RaspberryMatic#923]
Hallo!

Nachdem ich nun die aktuelle Version 3.53.30.20200919 auf meiner CCU3 installiert habe, musste ich nach dem Update der HmIP-BROLL-Firmware (1.6.2 => 1.8.16) feststellen, dass der Wert des vollständig geöffneten Rolladens nun nicht mehr 100 sondern 99,01 beträgt (so zumindest die Anzeige des States im ioBroker (Kanal 3 + 4).
Auch eine Kallibrierfahrt hat nichts geändert.

Im Zusammenhand mit Blocklys und dem Shuttercontrol-Adapter (im ioBroker) werden aber eben 100% erwartet.
Bei den Autoren, wo die neue Firmware noch nicht installiert ist, tritt der Fehler nicht auf!

Viele Grüße,

Christian

**Comment by jens-maus** [comment]
Da kann auch im Rahmen des RaspberryMatic Projektes nichts dagegen gemacht werden wenn das ein Bug in der neuen BROLL Firmware ist. Da ist dann alleine eQ3 zuständig und fähig etwas zu verbessern/fixen/reparieren.

Allerdings kann ich mir auch vorstellen das dies mitunter auch an hm-rpc ioBroker Adapter liegt. Vor längerem hatte ich einmal ein ähnliches Problem mit meinen HmIPWired DRBL Aktoren als ioBroker der Meinung war diese wäre nicht exakt auf 100%. Ein komplett neues Geräteeinlesen im hm-rpc hat dann bei mir geholfen. Und soweit ich weiss wird im hm-rpc adapter einiges gemacht mit den rohwerten eines rollladenaktors um diesen am schluss auf % zu konvertieren. Vielleicht kann da @foxriver76 ja was dazu sagen.

Auf jeden Fall wäre ein Blick in die anzeige der WebUI selbst sicher hilfreich um zu sehen ob die anzeige/wert dort selbst jedoch stimmt, denn das ist der repräsentative wert und nicht das was iobroker am schluss ausgibt.

**Comment by foxriver76** [comment]
Also ich habe leider nur FROLLs laufen, diese haben kurzzeitig auch ein Update bekommen, laufen jedoch nach wie vor wie erwartet. Die `%` Berechnung wird grundsätzlich anhand der `Paramsets` vorgenommen, welche die CCU liefert. Auch wenn die CCU manchmal nicht ganz schicke Werte liefert, sollen die beiden ioBroker Adapter damit umgehen können (z. B. https://github.com/ioBroker/ioBroker.hm-rpc/blob/master/main.js#L783). Wenn du mal hiner dem `.LEVEL` State im Objekte-Tab auf den Stift gehst und mir das zukommen lässt, kann ich mal schauen ob da was neu dazu gekommen ist, was nicht behandelt wird. Gerne auch bei hm-rpc als Issue oder im ioBroker Forum um hier nicht den Issue-Tracker von Jens zu missbrauchen.

**Comment by oggy79** [comment]
Erledigt ☑️ 

Das neu einlesen aller Geräte im
IoBroker und die anschließenden Fahrten, alles runter und wieder rauf, hat es gebracht!

Danke, schönen Sonntag noch 😀

Gruß,
Christian

**Comment by jens-maus** [comment]
Schade das es nun einfach so erledigt ist, denn das deutet (auch meiner Erfahrung nach) auf einen Bug im ioBroker hm-rpc Adapter hin der such jetzt ja leider durch deine vorschnellen Aktionen sich nicht mehr reproduzieren bzw reparieren lässt. @foxriver76 hattw dich ja um weitere Infos gebeten um das Problem einzugrenzen und vllt so einen Bug zu fixen. Das wird so nun nicht mehr möglich sein und du/andere werden somit irgendwann wieder in diesen Bug rennen. Schade.

**Comment by oggy79** [comment]
Hallo Jens!

Ich habe noch 3 nicht aktuelle BRoll im Einsatz.
Werde das Verhalten dort nochmal testen und dann auf foxriver76 zukommen.
Viele Grüße

**Comment by oggy79** [comment]
> Also ich habe leider nur FROLLs laufen, diese haben kurzzeitig auch ein Update bekommen, laufen jedoch nach wie vor wie erwartet. Die `%` Berechnung wird grundsätzlich anhand der `Paramsets` vorgenommen, welche die CCU liefert. Auch wenn die CCU manchmal nicht ganz schicke Werte liefert, sollen die beiden ioBroker Adapter damit umgehen können (z. B. https://github.com/ioBroker/ioBroker.hm-rpc/blob/master/main.js#L783). Wenn du mal hiner dem `.LEVEL` State im Objekte-Tab auf den Stift gehst und mir das JSON unter `RAW` zukommen lässt, kann ich mal schauen ob da was neu dazu gekommen ist, was nicht behandelt wird. Gerne auch bei hm-rpc als Issue oder im ioBroker Forum um hier nicht den Issue-Tracker von Jens zu missbrauchen.


#######################################################
ALT - BAD
#######################################################


```
{
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1601197977990,
  "common": {
    "name": "Fenster OG1_Badezimmer_Rolladen",
    "icon": "/icons/PushButton-2ch-wm_thumb.png"
  },
  "native": {
    "TYPE": "HmIP-BROLL",
    "SUBTYPE": "BROLL",
    "ADDRESS": "00111A499150A0",
    "PARENT": "",
    "PARENT_TYPE": "",
    "FIRMWARE": "1.8.16",
    "AVAILABLE_FIRMWARE": "1.8.16",
    "FIRMWARE_UPDATE_STATE": "UP_TO_DATE",
    "LINK_SOURCE_ROLES": "",
    "LINK_TARGET_ROLES": "",
    "GROUP": "",
    "TEAM": "",
    "TEAM_TAG": "",
    "INTERFACE": "",
    "RF_ADDRESS": 3073366,
    "INDEX": 0,
    "AES_ACTIVE": 1,
    "VERSION": 4,
    "FLAGS": 1,
    "DIRECTION": 0,
    "ROAMING": 0,
    "RX_MODE": 0,
    "UPDATABLE": true,
    "CHILDREN": [
      "00111A499150A0:0",
      "00111A499150A0:1",
      "00111A499150A0:2",
      "00111A499150A0:3",
      "00111A499150A0:4",
      "00111A499150A0:5",
      "00111A499150A0:6",
      "00111A499150A0:7"
    ],
    "PARAMSETS": [
      "MASTER",
      "SERVICE"
    ],
    "TEAM_CHANNELS": []
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "_id": "hm-rpc.2.00111A499150A0",
  "type": "device"
}
```



```
{
  "type": "state",
  "common": {
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": 0,
    "max": 101,
    "unit": "%",
    "role": "level",
    "name": "Fenster OG1_Badezimmer_Rolladen 2.LEVEL"
  },
  "native": {
    "MIN": 0,
    "UNIT": "100%",
    "OPERATIONS": 5,
    "MAX": 1.01,
    "FLAGS": 1,
    "ID": "LEVEL",
    "TYPE": "FLOAT",
    "DEFAULT": 0,
    "CONTROL": "SHUTTER_TRANSMITTER.LEVEL"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1601197992748,
  "_id": "hm-rpc.2.00111A499150A0.3.LEVEL",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

**Comment by foxriver76** [comment]
Welche Version von hm-rpc läuft denn?

**Comment by oggy79** [comment]
> Welche Version von hm-rpc läuft denn?

1.14.21 (2020-08-18)

**Comment by foxriver76** [comment]
Schau mal bitte ob das mit der 1.14.23 noch passiert, kann es nicht nachstellen damit.

**Comment by oggy79** [comment]
> Schau mal bitte ob das mit der 1.14.23 noch passiert, kann es nicht nachstellen damit.
> 
> Es gab allerdings kürzlich Änderungen diesbezüglich, also gut möglich dass da was kaputt war zwischenzeitlich.

Ist erledigt mit dem neuen ioBroker Modul 🥰

**Comment by Christoph-sans-e** [comment]
Also ich nutze raspberrymatic (aktuelle fw) und iobroker (alles auf dem aktuellsten Stand). Bei mir hat sich das Problem mit meinen HMIP-BROLLs leider nicht gelöst. Weiterhin fahren die Rollladen bei Sprachkommando über Alexa auf 100% zu statt auf...

**Comment by foxriver76** [comment]
Du musst einen Start mit Geräte neu einlesen machen oder das fehlerhafte Device löschen.

**Comment by Christoph-sans-e** [comment]
> Du musst einen Start mit Geräte neu einlesen machen oder das fehlerhafte Device löschen.

Also im iobroker habe ich testweise einen Rollladen gelöscht und neu eingelesen. Da hat sich nichts verändert. iobroker habe ich mehrfach neu gestartet und auch raspberrymatic...
