### ISSUE TITLE
Rock64 installation

### ISSUE THREAD

**Issue by detafun** [jens-maus/RaspberryMatic#924]
Hallo,
ist es möglich, es auch auf einen Rock64 zu installieren?
Da in der Docu nichts davon zu lesen ist.
Linux ist ja Linux.

Finde auch keine Doc für Manuelle Installation, nur Fertige Images immer.

cu Deta

**Comment by jens-maus** [comment]
Nein ist nicht möglich (sonst würde es ja in der Doku stehen). Und Linux ist eben nicht gleich Linux denn es gibt ja noch unterschiede wie Hardware, Bootloader, Endianness usw. momentan wird der Rock64 also nicht unterstützt. Du kannst aber natürlich gerne entsprechende Arbeiten aufnehmen die Rock64 Unterstützung einzubauen und das als PullRequest einzusenden.
