### ISSUE TITLE
"neue" Firmware hat eine niedrigere semantische Version als die bereits installierte

### ISSUE THREAD

**Issue by michl-b** [jens-maus/RaspberryMatic#925]
**Describe the bug**
Geräte Firmware-Update wird angezeigt, obwohl die "neue" Firmware eine niedrigere semantische Version hat als die bereits installierte.

**To Reproduce**
1. Go to 'Main Page'
4. See device firmware update available message
3. Click the message
4. Get modal dialog with update information for update from 2.6.0 to 2.2.2 (see screenshot)

**Expected behavior**
Firmware Update anzeige nur bei höherer Versionsnummer

**Screenshots**
![image](https://user-images.githubusercontent.com/11937795/94394709-491b1f80-015e-11eb-91f0-5bbd4045ac7b.png)

**System information (please complete the following information):**
 - Version RaspberryMatic 3.53.30.20200919
 - Hardware RaspberryPi3

**Additional context**
-

**Comment by jens-maus** [comment]
Das ist ein vollkommen normales Verhalten. Es passiert nicht selten das neu gekaufte homematicIP Geräte eine neuere/andere Standard-Firmware als die für die CCU3/RaspberryMatic vorgesehene Zentrale aufweisen und daher im Grunde ein Firmware-Downgrade durchgeführt werden muss um voll kompatibel mit der angebotenen Funktionalität in der CCU/WebUI der Zentrale aufzuweisen. Dies kommt auch daher da innerhalb der Cloud-Lösung von eQ3 (HomeMatic-IP) andere Firmware-Stände verwendet/ausgeliefert werden.

Der vorgeschlagene Weg zur Lösung des Problems ist das Downgrade durchführen zu lassen da in diesem Fall die 2.2.2 Firmware eben die Geräte-Firmware ist die zu der eingesetzten Zentralen/CCU-Firmware kompatibel ist.
