### ISSUE TITLE
Devices "+"-button fails on some devices, but not all

### ISSUE THREAD

**Issue by alexhass** [jens-maus/RaspberryMatic#926]
**Describe the bug**
"+" Button in Einstellungen > Geräte does not work on all devices.

**To Reproduce**
1. Chrome / Firefox or Firefox with no Addons
2. Go to 'Einstellungen > Geräte'
3. Click on 

    - 'HM-RCV-50' named "CCU HM BidCoS-RF"
    - "HmIP-RCV-50" named "CCU HmIP"
    - "HmIP-FALMOT-C12" named "FBH - Hauptwohnung"

4. Tree view does not open
5. Other devices like HmIP-eTRV-2,HmIP-BROLL, HmIP-STH open the tree view successful
6. You can still open the tree structure via "Baumstruktur öffnen/schließen"
7. No errors/warnings in developer console

**Expected behavior**
Tree view should open

**Screenshots**
Can provided if needed / not reproducible.

**System information (please complete the following information):**
 - Version: RaspberryMatic 3.51.6.20200621
 - Hardware: CCU3

**Comment by jens-maus** [comment]
Kann ich leider nicht bestätigen oder reproduzieren:
![Sep-28-2020 14-02-54](https://user-images.githubusercontent.com/5887769/94430166-c2813500-0193-11eb-9788-d098e19adafe.gif)

**Comment by alexhass** [comment]
Kannst Du bitte mal den Namen ändern? Vielleicht ist das der Grund.

**Comment by jens-maus** [comment]
@alexhass Nein, das ist nicht der Grund, drunter das "HM-RCV-50" verhält sich genau gleich. Übrigens ist die Funktion des aufklappen des Baumes etwas das komplett im Browser stattfindet, insofern kann ich mir schwer vorstellen das es hier ein problem gibt. Aber du kannst ja mal nach eventl. Fehlern in der Browserkonsole ausschau halten.

**Comment by alexhass** [comment]
Die Console ist leer. Keine Fehler.

**Comment by jens-maus** [comment]
Das ist komisch, dann musst du das leider selbst debuggen in der Console oder auf jemanden hoffen der hier auftaucht und das selbe problem hat bzw. da helfen kann.

**Comment by alexhass** [comment]
Man kann sehen, dass `style Display: None` bei +/- kommt und geht, aber die Tabelle wird nicht geladen. Klicke ich den "Baumstruktur öffnen" button scheinen die TR's von dem Unterbaum.

Weißt Du wann die Tabelle geladen werden sollte? Beim ersten Laden der ganzen Seite und dann sollte nur per toogle das display umgeschaltet werden?

Kannst Du die Meldungen im Verbose mode nachvollziehen?
![2020-09-28_150103](https://user-images.githubusercontent.com/4450722/94435556-9073d100-019b-11eb-9767-fb952ea019a0.jpg)

**Comment by alexhass** [comment]
Heute habe ich eine neue SanDisk MAX ENDURANCE (32GB) mit dem rpi3 image geflashed und dann in die CCU3 eingebaut. Jetzt habe ich auf 3.53 aktualisiert und gerade festgestellt, dass dieses Problem erfreulicherweise weg ist. Leider habe ich nicht nach dem Flashen der 3.51 bzw. Restore des Backups unter 3.51 getestet. Somit ist es noch im Bereich des Möglichen, dass dies auch ein Bug der 3.51 war und in 3.53 gefixt wurde.

Wie schon gesagt, haben alle TRs im Quelltext gefehlt. Vielleicht findest Du etwas in den DIFFs der Tabellenskripte zwischen 3.51 und 3.53.

Ansonsten legen wir das Thema mal unter SD-Card (SanDisk Edge 8GB) der CCU3 war _ab Werk_ defekt ab.

**Comment by jens-maus** [comment]
Da das problem ja nun anscheinend behoben ist, schließe ich dieses Ticket.
