### ISSUE TITLE
RedMatic nach Deinstallation

### ISSUE THREAD

**Issue by friedpa** [jens-maus/RaspberryMatic#928]
**Describe the bug**
Ich habe RedMatic wieder entfernt und im LOG steht nach einem Reboot:

![grafik](https://user-images.githubusercontent.com/42890695/94620940-b7bbc280-02af-11eb-970d-4e4c9d5f9e9c.png)

 - Version 3.53.30.20200919
 - Hardware RaspberryPi4

**Comment by jens-maus** [comment]
Das ist natürlich ein RedMatic Problem. Also bitte dort im Projekt melden. Meines wissens ist das aber ein bug bei älteren versionen und sollte bereits repariert sein. Aber wie geaagt, bitte im RedMatic Projekt melden.

**Comment by banjamann** [comment]
Das hatte ich auch - wenn Du den SoftwareLink "/usr/local/etc/monit-redmatic.cfg" löscht kehrt wieder Ruhe ein im Logfile.

**Comment by friedpa** [comment]
Danke für den Tipp!!
