### ISSUE TITLE
CCU3 with brand new SD card and flashed RaspberryMatic 3.51 cannot updated to RaspberryMatic 3.53

### ISSUE THREAD

**Issue by alexhass** [jens-maus/RaspberryMatic#929]
**Describe the bug**
Cannot upgrade CCU3 firmware with running RaspberryMatic firmware.

**To Reproduce**
1. Flash new SD card with RaspberryMatic 3.51 https://github.com/jens-maus/RaspberryMatic/releases/download/3.51.6.20200621/RaspberryMatic-3.51.6.20200621-rpi3.zip in your computer, because EQ3 does not provide images.
2. Install the flashed SD card in your CCU3.
3. Start up CCU3.
4. Restore your backup.
5. Try upgrading to https://github.com/jens-maus/RaspberryMatic/releases/download/3.53.30.20200919/RaspberryMatic-3.53.30.20200919-rpi3.zip and you get this:

```
Displaying running firmware update output:
==========================================
Starting firmware update (DO NOT INTERRUPT!!!):
[1/5] Validate update directory... OK
[2/5] Checking update_script... no 'update_script', OK
[3/5] Checking for rootfs filesystem images... none found, OK
[4/5] Checking for bootfs filesystem images... none found, OK
[5/5] Checking for sdcard image... found, flashing bootfs...........OK, flashing rootfs......................................OK, DONE
Finished firmware update successfully.

==========================================
Browser closed connection.
```

6. System comes up and says it is 3.51.6.20200621 and you see that update to 3.53 has failed.

**Expected behavior**
An upgrade to 3.53.30.20200919 completes.

**System information (please complete the following information):**
 - Version RaspberryMatic 3.51.6.20200621
 - Hardware CCU3

**Workaround**
Installed https://github.com/jens-maus/RaspberryMatic/releases/download/3.53.30.20200919/RaspberryMatic-3.53.30.20200919-ccu3.tgz over running RaspberryMatic-3.51.6.20200621-rpi3. Based on documentation the RaspberryMatic-3.53.30.20200919-ccu3 release is needed **_(only for initial CCU3 Firmware -> RaspberryMatic Upgrade)_**. No word that this is also needed if the machine was running RaspberryMatic out of the box via SD card replacement.

**TODO**
Fix the underlying bug or document this behaviour at least, please. If you think this is not a bug - tell the user after upload that it failed for this reason.

**Comment by alexhass** [comment]
Zu allererst habe ich das Webgui das mir noch immer 3.51 angezeigt hat. In ersten Moment habe ich noch auf eine Cache bug gehofft, aber ein Shift reload zeigte noch immer die 3.51 an. Cache clear habe ich nicht gemacht. Shift reload umgeht den cache.

Anschliesend habe ich mir die /var/log/messages angeschaut und habe gesehen, dass die CCU  noch immer mit 3.51 bootet. Z.b. zeigt der cuxd an, dass er mit 3.51 oder 3.53 hochfährt.

Ich bin nicht blöde. Ich mach seit fast 30 jahren firmware und software updates von open source und professionellen produkten. 

Ich weiss was ich mache und hier gibt es definitiv einen bug. Wie geschrieben, ich habe das update 3 mal erfolglos durchgeführt. Beim 4ten mal habe ich das ccu3 zip benutzt und dann hat das Update geklappt.

**Comment by alexhass** [comment]
Weil ich es nicht glauben wollte habe ich beim 3ten mal auch noch einen anderen Download vom RPI3 Paket genutzt. Ich habe zudem eine 32GB SD Card SanDisk MAX ENDURANCE genutzt, wenn vielleicht die Größe die Ursache ist. Außerdem habe ich gesehen, dass die CCU3 komisch geblinkt hat. Ich weiß nicht mehr in welchen Farben, aber bei einem der fehlgeschlagenen Updates habe ich ihr 45min zeit gelassen. Nach einem Power Cycle war sie dann wieder blau, das Update aber immer noch nicht drauf.

Man kommt nicht wirklich Servicefreundlich an die Karte und den HDMI-Port und jetzt ist die CCU wieder zu.

**Comment by jens-maus** [comment]
Meine Vermutung ist, das das Dateisystem der CCU3 wohl soweit gefüllt sein wird das das RaspberryMatic firmware update nicht eingespielt werden kann. Leider hatte sich eQ3 damals dazu entschieden /usr/local nicht den gesamten Speicherplatz zu gönnen, deshalb vmtl diese problem.

Daher vorschlag einen werksreset der ccu3 vor dem versuch das RaspberryMatic upgrade einzuspielen zu machen. Vielleicht hilft das ja bereits platz zu schaffen.

**Comment by alexhass** [comment]
Ich hatte eine brandneue 32 GB SD Card. Darauf habe ich dein RPI3 Image 3.51 in ausgebautem Zustand auf einem Windows PC mit balenaEtcher-Portable-1.5.109 eingespielt.

Anschließend hat man 3 Partitionen mit:

1. 256GB
2. 1GB
3. 3MB

Dann die Karte in die CCU3 eingebaut. Beim ersten Start (?) wird die 3te Partition auf volle SD Card Größe extended (28.5GB). Dann habe ich mein Backup eingespielt.

Mit dieser Partitionierung mache ich dann ein Update auf 3.53 über das Web GUI.

Was das mit EQ3 zu tun hat, kann ich gerade nicht nachvollziehen, weil hier nur RaspberryMatic am Start war.

**Comment by jens-maus** [comment]
Ok, das hatte ich nicht mitbekommen das du die sd karte in der CCU3 ausgetauscht hattest. Dann passt es.

Hast du auch mal ein direktes update auf die 3.53 probier VOR einspielen deines Backups?

**Comment by alexhass** [comment]
Nein. Ich denke aber nicht das mein backup sowas verursachen kann.

**Comment by jens-maus** [comment]
Ist das Problem mit neueren Versionen noch existent/relevant?
