### ISSUE TITLE
Raspberrymatic auf NUC6CAYH

### ISSUE THREAD

**Issue by henrydiesner** [jens-maus/RaspberryMatic#930]
Auf einem NUC6CAYH läuft Raspberrymatik in der neuesten Version leider nicht.
Die Installation stoppt bereits nach der ersten Meldung "vga=792 is deprecated. Use set ... command instead."
Eine frühere Version (3.49.17.20191225) hat funktioniert. Nach deren Aktualisierung stoppt der Neustart nach diesen Meldungen:
![raspberrymatic_nuc](https://user-images.githubusercontent.com/5823795/94837722-e7d0a600-0414-11eb-8474-497d75c63d8c.jpg)
Siehe auch Forumsbeitrag: 
https://homematic-forum.de/forum/viewtopic.php?f=65&t=61127
Wäre super, wenn es da eine Lösung gäbe :-)

**Comment by jens-maus** [comment]
Ich kann das hier leider bis jetzt auf meinen Test-NUC Systemen (D34010WYB) nicht reproduzieren. Was passiert denn wenn man das Recovery-System auswählt? Kommt dann eine sinnvolle anzeige? Und wurde mal probiert einfach zu warten? Ggf. kann es sein das nur das Display nicht angezeigt wird, das System aber ansich problemlos bootet,

**Comment by henrydiesner** [comment]
Heute habe ich mehrere Möglichkeiten getestet:
Version 20193011 Standardboot: Cursor blinkt kurz und verschwindet dann, keine Netzwerkvebindung
                              Recovery: Cursor blinkt kurz und verschwindet dann, keine Netzwerkvebindung
Version 20191225 Standardboot: Cursor blinkt kurz und verschwindet dann, keine Netzwerkvebindung
                              Zu Anfang ging hier einmalig alles, einschließlich dem Clonen - bis zum Update auf Version 20200919
                              Recovery: System startet, Netzwerkverbindung steht, Clonen geht nicht, da SSD nicht zur Auswahl
Version 20200621 Standardboot: Cursor blinkt kurz und friert dann ein, keine Netzwerkvebindung
                              Recovery: Cursor blinkt kurz und friert dann ein, keine Netzwerkvebindung
Version 20200919 Standardboot: Cursor blinkt kurz und friert dann ein, keine Netzwerkvebindung
                              Recovery: Cursor blinkt kurz und friert dann ein, keine Netzwerkvebindung
Auch langes Warten bringt nichts.

Muss ich mir jetzt eine neue NUC mit i3-Prozessor kaufen? :-(

**Comment by jens-maus** [comment]
@henrydiesner Danke für die weiteren Tests. Dann gibt es hier wohl noch ein irgendwie geartetes Problem mit dieser generation von NUCs. Ich werde versuchen in den nächsten Tagen noch andere NUC Generationen selbst zu testen. Aber solch eine NUC6CAYH habe ich leider selbst nicht. Wenn du magst kannst du gerne mal darüber nachdenken mir diese leihweise zukommen zu lassen dann kann ich mir das problem näher anschauen und einen Fix erarbeiten.

**Comment by henrydiesner** [comment]
@jens-maus Oh, das ist eine gute Idee. Gerne sende ich dir die NUC zum Test. Von einem erfolgreichen Fix würden sicherlich auch andere Nutzer profitieren. Bitte lass mir dazu deine Postadresse zukommen (ggf. direkt henry@diesner.de), dann geht das Päckchen mit Rücksendeschein gleich Montag weg.
Danke und Gruß
Henry

**Comment by jens-maus** [comment]
@henrydiesner Inzwischen ist die Leih-NUC von dir bei mir ja eingetroffen und ich konnte das Problem auch bereits reproduzieren und auch inzwischen reparieren. D.h. im nächsten Release von RaspberryMatic sollte es problemlos auf einer NUC6CAYH funktionieren.

**Comment by henrydiesner** [comment]
Hallo Jens,Das freut mich sehr! Da kann ich ja bald auf die NUC umstellen.Herzlichen Dank und beste GrüßeHenryAm 08.10.2020 23:34 schrieb Jens Maus <notifications@github.com>:

@henrydiesner Inzwischen ist die Leih-NUC von dir bei mir ja eingetroffen und ich konnte das Problem auch bereits reproduzieren und auch inzwischen reparieren. D.h. im nächsten Release von RaspberryMatic sollte es problemlos auf einer NUC6CAYH funktionieren.

**Comment by henrydiesner** [comment]
@jens-maus 
Hallo Jens, 
vielen Dank, die NUC ist wieder da :-) Ich habe versucht ein Backup vom bisherigen System einzuspielen. Da kommt diese Fehlermeldung: 
![image](https://user-images.githubusercontent.com/5823795/96747835-149b2c00-13c9-11eb-8cc5-08767ef59409.png)
Vermutlich liegt das an den unterschiedlichen Releases?
![image](https://user-images.githubusercontent.com/5823795/96748321-a99e2500-13c9-11eb-8e33-0c628b8c8103.png)
Soll ich auf die nächste stabile Version warten oder auf die NUC Testversion (3.53.30.20201020) einspielen?

**Comment by jens-maus** [comment]
> Übrigens ist noch kein Funkmodul an der NUC!

Genau das ist der Grund für die Fehlermeldung.

**Comment by henrydiesner** [comment]
@jens-maus 
Jetzt ist alles wunderbar! NUC läuft mit der von dir installierten Zwischenversion - ein Update mache ich erst mit der stabilen Version 1021 am Wochenende.
![image](https://user-images.githubusercontent.com/5823795/96884887-50de9300-1482-11eb-9741-e051a6ac54b4.png)

Herzlichen Dank für deine Hilfe und bleib gesund!

**Comment by jens-maus** [comment]
@henrydiesner Danke dir nochmal für die Leihhardware, das hat definitiv zum Erfolg beigetragen!
