### ISSUE TITLE
Updating rootfs freezes system during dd

### ISSUE THREAD

**Issue by alexirion** [jens-maus/RaspberryMatic#933]
**Bug description**

System updating by using the recovery system with a tar.gz, that contains rootfs.ext4 and boot.vfat freezes the system completely during dd in fwinstall.sh. (Tested on a rpi4 with official and freshly installed RaspberryMatic-3.53.30.20200919). In the middle of flashing the rootfs, the system LEDs stop blinking, cursor stops blinking on the display and the target is not accessible at all. Watchdog then triggers a reset with a half flashed system. Behavior is 100% reproducible on my side, tested with different SD cards.

For nailing the problem closer down, I copied a update.tar.gz, containing just rootfs.ext4 and boot.vfat to /usr/local/update.
I boot the target into recovery mode, and ssh into it.
Then I do:
_tar --warning=no-timestamp --no-same-owner -xmf update.tar.gz_
Now, rootfs.ext4 and boot.vfat are extracted beside the archive.
Then flash the rootfs by:
_dd if=rootfs.ext4 of=/dev/mmcblk0p2 bs=4M conv=fsync status=none_
System will completely freeze after written about 700MB.

(This sequence is equivalent to what fwinstall.sh is doing)

Now, the interesting part: I boot again into recovery system and do the same dd again, but with the rootfs.ext4, that has been already extracted during the last try. This time flashing works completely without freezing the system.

Quite hard to understand, but clearly the direct sequence of tar + dd leads to the freeze, while copying or extracting the file in one boot cycle and doing the dd in the next boot cycle works without freezing. Also, when I directly copy the rootfs.ext4 from my host to the target, reboot into recovery mode and then do the dd, this also works. Sounds like this problem is related to a file caching issue. When I drop the cache after tar and then do the dd, it does not freeze. (This could be a possible workaround fix for fwinstall.sh).

To summarize, booting into recovery system and then doing:

_tar --warning=no-timestamp --no-same-owner -xmf update.tar.gz
dd if=rootfs.ext4 of=/dev/mmcblk0p2 bs=4M conv=fsync status=none_
=> **Causes FREEZE**

In contrast:

_tar --warning=no-timestamp --no-same-owner -xmf update.tar.gz
**sync; echo 1 > /proc/sys/vm/drop_caches**
dd if=rootfs.ext4 of=/dev/mmcblk0p2 bs=4M conv=fsync status=none_
=> **NO FREEZE**

I also tried to use cat instead of dd, but with the same result.

**To Reproduce**
Manual steps described above or:
1. Create update.tar.gz containing rootfs.ext4 and boot.vfat on host
2. Normal boot of  RaspberryMatic
3. Copy update.tar.gz to /usr/local/tmp/upload on rpi4
4. ln -s /usr/local/upload /usr/local/.firmwareUpdate
5. touch /usr/local/.recoveryMode
6. reboot
-Recovery System is now booted and S90AutoUpdate calls fwinstall.sh
-fwinstall.sh extracts tar.gz file and freezes while doing the dd for the rootfs
-Watchdog silently triggers a restart of the half flashed system
-Now you have a pretty inconsistent setup, where anything obscure can happen!

**Expected behavior**
Flashing of rootfs and bootfs works completely without system freezing inbetween.

**System information**
 - RaspberryMatic-3.53.30.20200919
 - RaspberryPi4, 8GB

I hope someone else can confirm this issue! It's quite a nightmare when flashing the system is not reliable, especially when you don't notice, that flashing was not complete, because the watchdog has triggered a reboot, and in my cases the system was at least still coming up, but of couse with a nice mixture of root file systems and an old bootfs.

**Comment by jens-maus** [comment]
Sorry, can't reproduce it here as I have reflashed my Pi4,8GB quite some time already in the past. The only thing I could think of is that your power supply is perhaps overwhelmed with the sudden load. So please elaborate which power supply you are using.

**Comment by alexirion** [comment]
I already tried two different power supplies, the original rpi4 one and a stronger one for a Laptop. No difference. Also, as I explained, when doing the dd not directly after the tar, flashing works fine. Did you flash it in the same way? When flashing the official way by using the Web UI, the Web UI extracts the archive before booting into recovery mode. Also, this works for me.
