### ISSUE TITLE
Geräte Firmware-Update-Status anzeigen

### ISSUE THREAD

**Issue by alexhass** [jens-maus/RaspberryMatic#934]
Suche nach einem Update Status der Firmware updates. 

Wenn man nur 8 x BROLLs aktualisiert sieht man auch nach 5 Tagen nicht, was der aktuelle Stand ist und kein einziger ist bis jetzt completed. Ehrlich gesagt vermute ich, dass die Updates parallel laufen und nicht hintereinander weg. Dann würde man vieleicht sehen, ob überhaupt noch etwas passiert bzw. ein Fortschritt stattfindet.

Was den Fortschritt anbelangt wäre es auch sehr hilfreich, wenn man bei jedem Gerät eine % Anzeige hätte. Aktuell wird nur „Die Updatedatei wird zum Gerät übertragen“ angezeigt, was wirklich wenig aussagekräftig ist.

**Comment by alexhass** [comment]
Nach 9 Tagen erschien der Update button in den Geräten... unglaublich.

**Comment by jens-maus** [comment]
Das ist leider vollkommen normal und leider gibt es im Zuge der RaspberryMatic Entwicklung auch keinen Weg hier einen Fortschrittbalken oder ähnliches anzuzeigen weil diese Funktionalität komplett im Closed Source HMIPServer.jar von eQ3 ist. Hier hilft also leider nur sich an eQ3 zu wenden und um eine entsprechende Implementierung zu bitten.

**Comment by alexhass** [comment]
Soll ich dir das jar decompilen?

**Comment by jens-maus** [comment]
> Soll ich dir das jar decompilen?

Nein, das ist via Lizenz des HMIPserver strikt untersagt und würde nur dazu führen das ich dich dann hier blockieren müsste weil du gegen das code of conduct verstößt.

Und selbst wenn man es dekompilieren dürfte und würde, würde das nichts daran ändern das hier die zuständige Instanz eQ3 selbst ist und die den entwicklungsweg vorgeben solange dieser Teil Closed Source ist. Der richtige weg wäre also auch hier den wunsch an eQ3 heranzutragen und dann abzuwarten oder sie dazu bewegen den HMIPserver als open source freizugeben. Dann könnte man da etwas modifizieren.

**Comment by slankes** [comment]
Ich habe den Fall im Wiki dokumentiert:

https://github.com/jens-maus/RaspberryMatic/wiki/Support

ich würde vorschlagen, das Issue hier zu schliessen.

**Comment by uneart** [comment]
Ich habe ein ähnliches Problem. Acht Geräte hängen seit 1,5 Wochen im Status "Update wird übertragen". Den eq3-Support habe ich um Hilfe gebeten, jedoch bisher keine Antwort. Zumal ich mit RaspberryMatic ja sowieso nur bedingt Anspruch darauf habe.

@jens-maus Sind selbst Übertragungszeiten von 1-2 Wochen noch normal in einer Installation mit 60+ Geräten bei Übertragung von Firmware-Update auf 4-5 Geräte, wie sind da deine Erfahrungen?

**Comment by alexhass** [comment]
unstale

**Comment by alexhass** [comment]
Ich dachte du hast da besonders gute kontakte und bekommst das transferiert.

**Comment by cmorty** [comment]
O.T., weil ich gerade drüber gestolpert bin.

> > Soll ich dir das jar decompilen?
> 
> Nein, das ist via Lizenz des HMIPserver strikt untersagt und würde nur dazu führen das ich dich dann hier blockieren müsste weil du gegen das code of conduct verstößt.

Die Lizenz spielt in diesem Fall keine Rolle. Nach EU-Recht darf man Decompilieren um Fehler zu beheben oder die Interoperabilität herzustellen (und nur dazu). Nur darf man das dann nicht weitergeben (@alexhass)! Wahrscheinlich darf dokumentiert werden, wie man den Fehler behebt. Besser wäre es natürlich wenn eQ-3 den Code freigeben würde.

Siehe auch https://www.google.com/search?q=decompilieren+software+wartung

Was das Verletzten des Copyrights (was rechtlich natürlich ein Problem ist) mit dem CoC zu tun hat ist mir gerade nicht klar, ist aber auch eigentlich egal.
