### ISSUE TITLE
HMIP-HAP FW update doesnt work from ESXi + ova

### ISSUE THREAD

**Issue by q3ok** [jens-maus/RaspberryMatic#935]
I am unable to update the firmware on HMIP-HAP using RaspberryMatic on ESX.
The option for firmware update im Control panel are graying out the webpage but no modal window is shown
I have found that the system is trying to open a page, but 404 error is returned instead.

Is there any other option to flash the firmware? I want to migrate to raspberymatic from the Access point, but using it as a entry point to the system.

**Comment by jens-maus** [comment]
Which RF Module do you use apart from the HmIP-HAP? A RPI-RF-MOD or the old one?

**Comment by q3ok** [comment]
Thank you for the quick reply. I do not have any other module, I want to use HMIP-HAP as gateway to the whole ecosystem, I understood from the documentation that it is possible. :)

I have a clean installation of RaspberryMatic.

**Comment by jp112sdl** [comment]
To use the _HMIP-HAP as gateway_ , the RPI-RF-MOD is mandatory (because shared encryption functions are used from this rf module)

**Comment by jens-maus** [comment]
> Thank you for the quick reply. I do not have any other module, I want to use HMIP-HAP as gateway to the whole ecosystem, I understood from the documentation that it is possible. :)

Sorry, but then you read incorrectly. See here:
https://github.com/jens-maus/RaspberryMatic/wiki/Einleitung#vorraussetzungen

And sorry that the documentation is only availabel in german.
