### ISSUE TITLE
RaspberryMatic : Neuer Nutzer und nun geht es nicht mehr

### ISSUE THREAD

**Issue by GNoelle** [jens-maus/RaspberryMatic#937]
Hallo,

seid gestern war ich neuer Nutzer von RaspberryMatic. Nach einem kurzen Stromausfall (Stecker aus der Dose gerutscht), geht hier leider nichts mehr...

Ich komme bis zu dem Punkt : Starte HMServer und dann nach der bekannten Zeit kommt : No IP Adresse set.

Was ich bisher gemacht habe -->

Raspberry neu gestartet, neue SD - Karte gekauft und Image neu auf die neue Karte geschrieben.

Mit und ohne HM - Funk - Modul gestartet... Eigentlich alles, was einem normalen Windows User so einfällt, mit dem Ergebnis,
dass der Fehler bleibt.

Mit einer anderen Karte habe ich dann mal den iobroker installiert um die Funktion des PI4 zu prüfen, das hat funktioniert, hilft mir nur leider im meinem Homematic - Projekt nicht weiter, da ich keine andere CCU besitze und sowohl Homematic als auch Homematic IP Geräte betreiben möchte.

Hat von Euch jemand eine Idee, was ich noch anstellen kann ?

Ich muss jedoch zugeben, von Linux habe ich so gar keine Ahnung.

Ich hoffe ihr habt eine Lösung für mich.

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!
