### ISSUE TITLE
WebUI-Programm: Ändern eines "Sonst..." in ein "Sonst, wenn..." wirft ERROR-Meldung ins Log

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#938]
**Describe the bug**
Wenn man in einem WebUI-Programm ein "Sonst..." zu einem "Sonst, wenn..." ändert wird folgende ERROR-Meldung im Log angezeigt:
`Oct 10 15:39:23 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string action = "AddNewElseRule";string rid = "25231"; [ExecError():iseESPexec.cpp:12885]`

**To Reproduce**
1. Ein simples WebUI-Programm anlegen (mit leerem oder gefülltem "Sonst...") und mit OK beenden/speichern
2. Das WebUI-Programm wieder öffnen und aus dem "Sonst..." ein "Sonst, wenn..." machen. Dann mit OK oder Abbrechen das Programm schließen.
3. Im Systemlog die ERROR-Meldung sehen

**Expected behavior**
Ein Ändern von "Sonst..." zu einem "Sonst, wenn..." in WebUI Programmen sollte keine Fehlermeldung generieren.

**System information (please complete the following information):**
 - Version [RaspberryMatic 3.53.30.20200919]
 - Hardware [RaspberryPi4B]

**Additional context**
Die in der ERROR-Meldung gezeigt ID gehört zur SubRule des eigentlichen WebUI-Programm's.
Die umgedrehte Aktion "Sonst, wenn..." zu "Sonst..." bringt keine Fehler.
Bis auf die Fehlermeldung im Log konnte ich keine negativen Auswirkungen feststellen.

**Comment by jens-maus** [comment]
Kannst du das gleiche mal bitte mit einem aktuellen nightly snapshot probieren und sagen ob dort auch die selben fehler kommen?

**Comment by Baxxy13** [comment]
> aktuellen nightly snapshot

RaspberryMatic-3.53.30.20201010 läuft seit heut morgen auf einem Pi4B.
Hier werden bei gleicher Vorgehensweise keinerlei Fehlermeldungen erzeugt.

Kurioserweise bekomme ich das nun auf der 3.53.30.20200919 auch nicht mehr reproduziert. Obwohl ich vorhin mehrere dieser Meldungen hatte.
```
Oct 10 11:42:25 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string action = "AddNewElseRule";string rid = "24418"; [ExecError():iseESPexec.cpp:12885]
Oct 10 14:46:54 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string action = "AddNewElseRule";string rid = "24934"; [ExecError():iseESPexec.cpp:12885]
Oct 10 15:39:23 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string action = "AddNewElseRule";string rid = "25231"; [ExecError():iseESPexec.cpp:12885]
Oct 10 15:55:09 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string action = "AddNewElseRule";string rid = "25231"; [ExecError():iseESPexec.cpp:12885]
Oct 10 16:01:22 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string action = "AddNewElseRule";string rid = "25267"; [ExecError():iseESPexec.cpp:12885]
Oct 10 16:04:39 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string action = "AddNewElseRule";string rid = "25267"; [ExecError():iseESPexec.cpp:12885]
```

**Comment by jens-maus** [comment]
Dann versuch mal nen muster zu finden dann können wir hier weitermachen. Danke

**Comment by Baxxy13** [comment]
Ich konnte es nicht mehr reproduzieren. Werde es aber im Auge behalten.
