### ISSUE TITLE
Funktionstest in den allgemeinen Geräteeinstellungen wirft ca. alle 3s ERROR-Meldungen ins Log

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#939]
**Describe the bug**
Klickt man in den "Allgemeinen Geräteeinstellungen" eines Gerätes bei Funktionstest auf "Test starten" und wartet auf das Ergebnis wird währenddessen ca. alle 3s eine ERROR-Meldung folgender Art ins Log geschrieben. Getestet mit HmIP-PS, HmIP-PCBS2, HmIP-SRH; HmIP-SWDO

```
Oct 10 20:44:41 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "";string timestamps = ""; [ExecError():iseESPexec.cpp:12885]
Oct 10 20:44:44 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "";string timestamps = ""; [ExecError():iseESPexec.cpp:12885]
Oct 10 20:44:47 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "";string timestamps = ""; [ExecError():iseESPexec.cpp:12885]
Oct 10 20:44:50 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "";string timestamps = ""; [ExecError():iseESPexec.cpp:12885]
Oct 10 20:44:53 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "";string timestamps = ""; [ExecError():iseESPexec.cpp:12885]
Oct 10 20:44:56 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "";string timestamps = ""; [ExecError():iseESPexec.cpp:12885]
Oct 10 20:44:59 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "";string timestamps = ""; [ExecError():iseESPexec.cpp:12885]
Oct 10 20:45:02 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "";string timestamps = ""; [ExecError():iseESPexec.cpp:12885]
Oct 10 20:45:05 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "";string timestamps = ""; [ExecError():iseESPexec.cpp:12885]
```
Zusätzlich gibt es noch eine extra ERROR-Meldung "am Anfang" bei den Batteriesensoren (SRH / SWDO).
```
Oct 10 20:45:38 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: no event dp exists for chn id = 7557 [StartCommunicationTest():iseManageChannel.cpp:1341]
Oct 10 20:45:41 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "";string timestamps = ""; [ExecError():iseESPexec.cpp:12885]
Oct 10 20:45:44 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "";string timestamps = ""; [ExecError():iseESPexec.cpp:12885]
Oct 10 20:45:47 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "";string timestamps = ""; [ExecError():iseESPexec.cpp:12885]
Oct 10 20:45:50 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "";string timestamps = ""; [ExecError():iseESPexec.cpp:12885]
Oct 10 20:45:53 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "";string timestamps = ""; [ExecError():iseESPexec.cpp:12885]
```
Behält man das Fenster offen und wartet auf den Abschluss des Tests wird die ERROR-Meldung so lange weiter generiert bist der Test erfolgreich war. 
Schließt man das Fenster vorzeitig mit OK oder Abbrechen wird trotzdem weiter die ERROR-Meldung generiert. Vermutlich bis zur nächsten zyklischen Meldung des Aktors / Sensors. So lange habe ich aber nicht gewartet sondern die Aktoren / Sensoren manuell dazu bewegt ihren Status zu übermitteln.

**To Reproduce**
1. zu Startseite > Einstellungen > Geräte gehen und dort einen IP Aktor / Sensor anklicken um in die allgemeinen Geräteeinstellungen zu kommen
2. Den Funktionstest starten 
3. warten bis der Test abgeschlossen (grün) ist oder mit OK oder Abbrechen das Fenster verlassen
4. Im Systemlog die ERROR-Meldungen anschauen

**Expected behavior**
Der Funktionstest sollte ohne Fehlermeldungen im Log abgeschlossen werden.

**System information (please complete the following information):**
 - Version [RaspberryMatic 3.53.30.20200919 & RaspberryMatic-3.53.30.20201010]
 - Hardware [2x Pi4B]

**Additional Info**
Hab es noch kurz am Live System mit 3.51.6.20200621 und einem WTH-2 getestet. Sagen wir mal so... sieht anders, aber nicht wirklich besser aus.
```
Oct 10 21:23:29 Duene-116-CCU3 local0.err ReGaHss: ERROR: no event dp exists for chn id = 4880 [StartCommunicationTest():iseManageChannel.cpp:1341]
Oct 10 21:23:29 Duene-116-CCU3 local0.err ReGaHss: ERROR: no event dp exists for chn id = 4881 [StartCommunicationTest():iseManageChannel.cpp:1341]
Oct 10 21:23:29 Duene-116-CCU3 local0.err ReGaHss: ERROR: no event dp exists for chn id = 4882 [StartCommunicationTest():iseManageChannel.cpp:1341]
Oct 10 21:23:29 Duene-116-CCU3 local0.err ReGaHss: ERROR: no event dp exists for chn id = 4883 [StartCommunicationTest():iseManageChannel.cpp:1341]
Oct 10 21:23:29 Duene-116-CCU3 local0.err ReGaHss: ERROR: no event dp exists for chn id = 4884 [StartCommunicationTest():iseManageChannel.cpp:1341]
Oct 10 21:23:29 Duene-116-CCU3 local0.err ReGaHss: ERROR: no event dp exists for chn id = 4885 [StartCommunicationTest():iseManageChannel.cpp:1341]
Oct 10 21:23:32 Duene-116-CCU3 local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "37711	62872	28273	63084	63083	13072	35269	48060	7230	31075	38243	23518	58460	7229	55529	2651	9502";string timestamps = "02.10.2020 09:18:29		10.10.2020 17:19:20	10.10.2020 21:16:56	10.10.2020 21:16:56	10.10.2020 21:15:39	10.10.2020 21:15:39	10.10.2020 14:26:53	09.10.2020 08:48:04	02.10.2020 09:19:46	02.10.2020 09:18:35	02.10.2020 09:18:43	02.10.2020 09:18:31	04.10.2020 09:32:03	23.09.2020 17:10:23	10.10.2020 0
:15:00	10.10.2020 21:16:58"; [ExecError():iseESPexec.cpp:12798]
Oct 10 21:23:35 Duene-116-CCU3 local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "37711	62872	28273	63084	63083	13072	35269	48060	7230	31075	38243	23518	58460	7229	55529	2651	9502";string timestamps = "02.10.2020 09:18:29		10.10.2020 17:19:20	10.10.2020 21:16:56	10.10.2020 21:16:56	10.10.2020 21:15:39	10.10.2020 21:15:39	10.10.2020 14:26:53	09.10.2020 08:48:04	02.10.2020 09:19:46	02.10.2020 09:18:35	02.10.2020 09:18:43	02.10.2020 09:18:31	04.10.2020 09:32:03	23.09.2020 17:10:23	10.10.2020 0
:15:00	10.10.2020 21:16:58"; [ExecError():iseESPexec.cpp:12798]
Oct 10 21:23:38 Duene-116-CCU3 local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "37711	62872	28273	63084	63083	13072	35269	48060	7230	31075	38243	23518	58460	7229	55529	2651	9502";string timestamps = "02.10.2020 09:18:29		10.10.2020 17:19:20	10.10.2020 21:16:56	10.10.2020 21:16:56	10.10.2020 21:15:39	10.10.2020 21:15:39	10.10.2020 14:26:53	09.10.2020 08:48:04	02.10.2020 09:19:46	02.10.2020 09:18:35	02.10.2020 09:18:43	02.10.2020 09:18:31	04.10.2020 09:32:03	23.09.2020 17:10:23	10.10.2020 0
:15:00	10.10.2020 21:16:58"; [ExecError():iseESPexec.cpp:12798]
Oct 10 21:23:41 Duene-116-CCU3 local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "37711	62872	28273	63084	63083	13072	35269	48060	7230	31075	38243	23518	58460	7229	55529	2651	9502";string timestamps = "02.10.2020 09:18:29		10.10.2020 17:19:20	10.10.2020 21:16:56	10.10.2020 21:16:56	10.10.2020 21:15:39	10.10.2020 21:15:39	10.10.2020 14:26:53	09.10.2020 08:48:04	02.10.2020 09:19:46	02.10.2020 09:18:35	02.10.2020 09:18:43	02.10.2020 09:18:31	04.10.2020 09:32:03	23.09.2020 17:10:23	10.10.2020 0
:15:00	10.10.2020 21:16:58"; [ExecError():iseESPexec.cpp:12798]
Oct 10 21:23:44 Duene-116-CCU3 local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "37711	62872	28273	63084	63083	13072	35269	48060	7230	31075	38243	23518	58460	7229	55529	2651	9502";string timestamps = "02.10.2020 09:18:29		10.10.2020 17:19:20	10.10.2020 21:16:56	10.10.2020 21:16:56	10.10.2020 21:15:39	10.10.2020 21:15:39	10.10.2020 14:26:53	09.10.2020 08:48:04	02.10.2020 09:19:46	02.10.2020 09:18:35	02.10.2020 09:18:43	02.10.2020 09:18:31	04.10.2020 09:32:03	23.09.2020 17:10:23	10.10.2020 0
:15:00	10.10.2020 21:16:58"; [ExecError():iseESPexec.cpp:12798]
Oct 10 21:23:47 Duene-116-CCU3 local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "37711	62872	28273	63084	63083	13072	35269	48060	7230	31075	38243	23518	58460	7229	55529	2651	9502";string timestamps = "02.10.2020 09:18:29		10.10.2020 17:19:20	10.10.2020 21:16:56	10.10.2020 21:16:56	10.10.2020 21:15:39	10.10.2020 21:15:39	10.10.2020 14:26:53	09.10.2020 08:48:04	02.10.2020 09:19:46	02.10.2020 09:18:35	02.10.2020 09:18:43	02.10.2020 09:18:31	04.10.2020 09:32:03	23.09.2020 17:10:23	10.10.2020 0
:15:00	10.10.2020 21:16:58"; [ExecError():iseESPexec.cpp:12798]
Oct 10 21:23:50 Duene-116-CCU3 local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "37711	62872	28273	63084	63083	13072	35269	48060	7230	31075	38243	23518	58460	7229	55529	2651	9502";string timestamps = "02.10.2020 09:18:29		10.10.2020 17:19:20	10.10.2020 21:16:56	10.10.2020 21:16:56	10.10.2020 21:15:39	10.10.2020 21:15:39	10.10.2020 14:26:53	09.10.2020 08:48:04	02.10.2020 09:19:46	02.10.2020 09:18:35	02.10.2020 09:18:43	02.10.2020 09:18:31	04.10.2020 09:32:03	23.09.2020 17:10:23	10.10.2020 0
:15:00	10.10.2020 21:16:58"; [ExecError():iseESPexec.cpp:12798]
Oct 10 21:23:53 Duene-116-CCU3 local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "37711	62872	28273	63084	63083	13072	35269	48060	7230	31075	38243	23518	58460	7229	55529	2651	9502";string timestamps = "02.10.2020 09:18:29		10.10.2020 17:19:20	10.10.2020 21:16:56	10.10.2020 21:16:56	10.10.2020 21:15:39	10.10.2020 21:15:39	10.10.2020 14:26:53	09.10.2020 08:48:04	02.10.2020 09:19:46	02.10.2020 09:18:35	02.10.2020 09:18:43	02.10.2020 09:18:31	04.10.2020 09:32:03	23.09.2020 17:10:23	10.10.2020 0
:15:00	10.10.2020 21:16:58"; [ExecError():iseESPexec.cpp:12798]
Oct 10 21:23:56 Duene-116-CCU3 local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "37711	62872	28273	63084	63083	13072	35269	48060	7230	31075	38243	23518	58460	7229	55529	2651	9502";string timestamps = "02.10.2020 09:18:29		10.10.2020 17:19:20	10.10.2020 21:16:56	10.10.2020 21:16:56	10.10.2020 21:15:39	10.10.2020 21:15:39	10.10.2020 14:26:53	09.10.2020 08:48:04	02.10.2020 09:19:46	02.10.2020 09:18:35	02.10.2020 09:18:43	02.10.2020 09:18:31	04.10.2020 09:32:03	23.09.2020 17:10:23	10.10.2020 0
:15:00	10.10.2020 21:16:58"; [ExecError():iseESPexec.cpp:12798]
Oct 10 21:23:59 Duene-116-CCU3 local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "37711	62872	28273	63084	63083	13072	35269	48060	7230	31075	38243	23518	58460	7229	55529	2651	9502";string timestamps = "02.10.2020 09:18:29		10.10.2020 17:19:20	10.10.2020 21:16:56	10.10.2020 21:16:56	10.10.2020 21:15:39	10.10.2020 21:15:39	10.10.2020 14:26:53	09.10.2020 08:48:04	02.10.2020 09:19:46	02.10.2020 09:18:35	02.10.2020 09:18:43	02.10.2020 09:18:31	04.10.2020 09:32:03	23.09.2020 17:10:23	10.10.2020 0
:15:00	10.10.2020 21:16:58"; [ExecError():iseESPexec.cpp:12798]
```
Zusammengefasst: Sehr kurios. Aber da vermutlich niemand den Test Button drückt zwar unschön, aber nicht weiter tragisch.

Klassische HM Geräte wurden nicht gestestet.

Nachtrag: Auch bei einer CCU3 3.53.30 werden die ERROR-Meldungen generiert

**Comment by jp112sdl** [comment]
Hallo Baxxy!

<hr/>

- wegen
```
ReGaHss: ERROR: ScriptRuntimeError: string channels = "";string timestamps = ""; [ExecError():iseESPexec.cpp:12885]
```
Ändere mal die [/www/rega/esp/system.fn:537](https://github.com/eq-3/occu/blob/msater/WebUI/www/rega/esp/system.fn#L537) in
```
if( (oTestChannel) && (oTestChannel.IsTypeOf( OT_CHANNEL ) ) )
```

Der Skriptfehler taucht auf, wenn `.Device()` nicht auf einen Channel erfolgt.

Anschließend Browsercache löschen und CCU - oder ReGaHss -  neustarten.

<hr/>

- wegen
```
ReGaHss: ERROR: no event dp exists for chn id = 4885 [StartCommunicationTest():iseManageChannel.cpp:1341]
```

Das hängt mit der [/www/rega/esp/channels.fn](https://github.com/eq-3/occu/blob/master/WebUI/www/rega/esp/channels.fn#L16) und auch der /www/webui/webui.js (Zeilennummern lassen sich da leider nicht verlinken) zusammen:
```
  /**
   * Startet den Funktionstest.
   **/
  startTest: function() {
      var _this_ = this;
      this.m_isTestRunning = true;
      $(this.TEST_RESULT_ID).setStyle({backgroundColor: WebUI.getColor("testActive")});
      homematic("Device.startComTest", {id: this.device.id}, function (testId) {
        _this_.m_testId = testId;
        _this_.pollTest();
      });
  },
```
Das ruft `device.DevStartComTest();` in /www/api/methods/device/startcomtest.tcl auf.

Nicht alle DEVICE habe scheinbar die Methode `DevStartComTest()`.

Ob es eine Möglichkeit gibt, mit der man prüfen kann, ob ein DEVICE die Methode `DevStartComTest()` besitzt, weiß ich nicht.

**Comment by jens-maus** [comment]
@jp112sdl Wie immer: DANKE für deine Analysen. Wirklich sehr hilfreich. Kannst du dir zumindest schon einmal für den ersten Teil (`oTestChannel` check) vorstellen einen WebUI Patch als PR zu submitten? Dann hätten wir das bereits vom Tisch.

Bzgl. des zweiten Problems mit dem `startComTest`: Hast du mal geschaut ob es nicht auch ein Device vs. Channel problem ist weil es gibt ja nicht nur das `o.DevStartComTest()` in der ReGa, sondern auch ein `o.ChnStartComTest()`?

**Comment by jp112sdl** [comment]
> Kannst du dir zumindest schon einmal für den ersten Teil (oTestChannel check) vorstellen einen WebUI Patch als PR zu submitten? 

Ja das würde ich machen, wenn Baxxy (oder auch jeder andere außer mir) bestätigen kann, dass das tatsächlich das Problem löst.

> Hast du mal geschaut ob es nicht auch ein Device vs. Channel problem ist weil es gibt ja nicht nur das o.DevStartComTest() in der ReGa, sondern auch ein o.ChnStartComTest()?

In der Fehlermeldung steht _chn id_ (`no event dp exists for chn id`), obwohl man den Test auf das Gerät macht.
Es wird aber tatsächlich die Methode [`Device.startComTest`](https://github.com/eq-3/occu/blob/master/WebUI/www/api/methods.conf#L543) aufgerufen (hab grad noch mal Debugausgaben eingebaut).

Ob es aber auch Channel gibt, die keinen `ChnStartComTest()` besitzen, weiß ich nicht.

**Comment by jens-maus** [comment]
> In der Fehlermeldung steht _chn id_ (`no event dp exists for chn id`), obwohl man den Test auf das Gerät macht.
> Es wird aber tatsächlich die Methode [`Device.startComTest`](https://github.com/eq-3/occu/blob/master/WebUI/www/api/methods.conf#L543) aufgerufen (hab grad noch mal Debugausgaben eingebaut).
> 
> Ob es aber auch Channel gibt, die keinen `ChnStartComTest()` besitzen, weiß ich nicht.

Nun, beide Methoden machen (soweit ich das hier sehen kann) intern genau das gleiche bzw. die `DevStartComTest()` ruft für jeden Channel einfach die `ChnStartComTest()`auf. Vorher findet aber eine interne Prüfung in `ChnStartComTest()` statt ob der angegebene Channel über das Flag `OPERATION_EVENT` verfügt oder nicht. Und wenn nicht wird eben der Fehler zurückgegeben. In der ReGa Skriptsprache bekommt man das gleiche ja mit `o.Operations() & OPERATION_EVENT` geliefert bzw. ausgeführt. Die Frage ist nur (und da steck ich zu wenig drin) ob es normal ist das es eben Channels gibt die nicht über das `OPERATION_EVENT` flag verfügen und wenn ja dann könnte ich in ReGa einfach die ERROR message dort in eine WARNING oder gar Verbose ausgabe verwandeln wenn das ganze eher daraufhin als unkritisch einzustufen ist.

**Comment by jp112sdl** [comment]
> Die Frage ist nur (und da steck ich zu wenig drin) ob es normal ist das es eben Channels gibt die nicht über das OPERATION_EVENT flag verfügen

Ich habe zum Testen leider nur eine VM mit 1x CUxD Device (da tritt der Fehler nicht auf) und den beiden nativen virtuelle RCV-Devices (da tritt der Fehler auf, wenn man den Test direkt auf das Gerät startet).

Die ChannelI D, die bei mir hier als Fehler angegeben wird, ist Kanal 0 der virtuellen HM-/HmIP-Fernbedienung.
Kanal 0 ist üblicherweise bei "normalen Geräten" (ich kann da auch nur für BidCos sprechen) unsichtbar bzw. internal.
`channel index="0" type="MAINTENANCE" ui_flags="internal" class="maintenance"`

Ich denke mal, dass der Test auf Kanal 0 grundsätzlich nicht erfolgen kann/darf?

In der homematic.regadom sehe ich auch in der Eigenschaft "MASTERDESC" den Wert OPERATIONS:1 bei Kanal 0 der virt. Fernbedienung.
Bei dem CUxD Gerät ist OPERATIONS:3

**Comment by jp112sdl** [comment]
@Baxxy13 Handelt es sich bei dir bei der DP ID 7557 auch um Kanal 0 des Geräts?

**Comment by jp112sdl** [comment]
@jens-maus Ich habe jetzt noch mal mit einem Testskript über alle Datenpunkte geschaut.
```
string id;
foreach(id, dom.GetObject(ID_CHANNELS).EnumIDs()) {  
  var channel = dom.GetObject(id); 
  
  string dpId;
  foreach (dpId, channel.DPs()) {
     var dp         = dom.GetObject(dpId);
     var operations = dp.Operations();
    
     Write(id#":"#channel.Name()#" -> "#operations);

     if (OPERATION_EVENT & operations) { WriteLine(" -> HAS EVENT"); } else { WriteLine("");}
  }
 }
}
```
gibt bei mir aus
```
13:Gateway -> 7 -> HAS EVENT
13:Gateway -> 7 -> HAS EVENT
24:Communication -> 2
24:Communication -> 2
1012:Zentrale:0 -> 3
1014:HM-RCV-50 BidCoS-RF:1 -> 6 -> HAS EVENT
1014:HM-RCV-50 BidCoS-RF:1 -> 6 -> HAS EVENT
1014:HM-RCV-50 BidCoS-RF:1 -> 2
...
1210:HM-RCV-50 BidCoS-RF:50 -> 6 -> HAS EVENT
1210:HM-RCV-50 BidCoS-RF:50 -> 6 -> HAS EVENT
1210:HM-RCV-50 BidCoS-RF:50 -> 2
1240:HmIP-RCV-50 HmIP-RCV-1:1 -> 6 -> HAS EVENT
...
1387:HmIP-RCV-50 HmIP-RCV-1:50 -> 6 -> HAS EVENT
1396:HM-RC-19 CUX2801001:0 -> 5 -> HAS EVENT
1396:HM-RC-19 CUX2801001:0 -> 5 -> HAS EVENT
1396:HM-RC-19 CUX2801001:0 -> 7 -> HAS EVENT
1409:HM-RC-19 CUX2801001:1 -> 7 -> HAS EVENT
...
1814:HM-RC-19 CUX2801001:16 -> 2
```

Der Fehler `no event dp exists for chn id = ` tritt bei mir bei der ID 1012 sowie 1239 auf.
Die 1239 (:0 der HmIP RCV) wird bei meinem Skript gar nicht ausgegeben!? Komisch... Gibt es dort gar keine Datenpunkte?

**Comment by jens-maus** [comment]
Danke für die weiteren Tests. Da stellt sich also wirklich dann die Frage bei mir wie man damit umgehen sollte? Entweder irgendwie einen WebUI Patch entwickeln der checkt ob ein Kanal OPERATION_EVENT hat oder nicht und wenn nicht dann gar keinen ComTest loslassen? Oder soll ich einfach in der ReGa die ERROR ausgabe in eine WARNING oder Verbose ausgabe verwandeln, dann wäre auch ruhe (zumindest im Logfile).

**Comment by jp112sdl** [comment]
> irgendwie einen WebUI Patch entwickeln der checkt ob ein Kanal OPERATION_EVENT hat

hilft nicht, wenn jemand direkt beim Gerät auf den "Test" Button klickt. Dann wird ja lediglich `DevStartComTest()` für das Gerät auf die ReGa losgelassen.

Ich denke, es reicht, wenn die ReGa das als INFO verbucht. Es gibt ja offensichtlich bei `no event dp exists for chn id` ohnehin keinen Abbruch im Ablauf des weiteren Geschehens.

**Comment by jens-maus** [comment]
Ok, dann einigen wir uns darauf. Dann änder ich die ReGa dementsprechend ab. Dann fehlt nur noch ein WebUI patch deinerseits zum ersten "oTestChannel" Problem ;-)

**Comment by jp112sdl** [comment]
Okay, ist erstmal drin, auch wenn es nicht weiter getestet wurde. Ggf. muss noch nachgearbeitet werden

**Comment by Baxxy13** [comment]
Oh ihr wart ja schon fleißig...

> Handelt es sich bei dir bei der DP ID 7557 auch um Kanal 0 des Geräts?

Das war Kanal:2 eines HmIP-SWDO - "VerknüpfungspartnerBackup Alarmsirene" noch nie vorher gesehen/benutzt

Die ID's 4880 - 4885 (aus dem 3.51.6.20200621 Test) sind die Kanäle 2-7 eines HmIP-WTH-2

Nochmal kurz einen HmIP-SRH getestet:
```
Oct 12 14:04:47 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: no event dp exists for chn id = 19331 [StartCommunicationTest():iseManageChannel.cpp:1341]
Oct 12 14:04:47 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "9134	10471";string timestamps = "12.10.2020 13:58:01	11.10.2020 23:45:00"; [ExecError():iseESPexec.cpp:12885]
Oct 12 14:04:50 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "9134	10471";string timestamps = "12.10.2020 13:58:01	11.10.2020 23:45:00"; [ExecError():iseESPexec.cpp:12885]
Oct 12 14:04:53 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "9134	10471";string timestamps = "12.10.2020 13:58:01	11.10.2020 23:45:00"; [ExecError():iseESPexec.cpp:12885]
Oct 12 14:04:56 Test-CCU-RaspiMatic-Pi4B local0.err ReGaHss: ERROR: ScriptRuntimeError: string channels = "9134	10471";string timestamps = "12.10.2020 13:58:01	11.10.2020 23:45:00"; [ExecError():iseESPexec.cpp:12885]
```
Hier entspricht die ID wieder Kanal:2 - "VerknüpfungspartnerBackup Alarmsirene"

Nun teste ich mal deinen Patch und gebe Rückmeldung.
