### ISSUE TITLE
The newest build come with http:/// no ip no connection old version worked fine

### ISSUE THREAD

**Issue by FraatRamski** [jens-maus/RaspberryMatic#94]
the newest build 2.27.8.28178413 come with http:/// no ip no coeection old version2.25.15. is working fine

raspi v2

![2017-04-14_19h10_23](https://cloud.githubusercontent.com/assets/21004642/25050250/a3b1b3e2-2146-11e7-9cbf-478bd0cf7f29.jpg)
![2017-04-14_19h10_09](https://cloud.githubusercontent.com/assets/21004642/25050254/ad37f4c6-2146-11e7-9b59-b15e81934956.jpg)
![2017-04-14_19h10_23](https://cloud.githubusercontent.com/assets/21004642/25050255/ad3b894c-2146-11e7-8c99-38f522ce168f.jpg)

**Comment by jens-maus** [comment]
Please press ALT+F2 on your keyboard and see why you got no IP address or what might be the reason.

**Comment by FraatRamski** [comment]
![2017-04-14_19h33_00](https://cloud.githubusercontent.com/assets/21004642/25050733/52ac9b76-2149-11e7-93bb-d14b5f8e7aec.jpg)
here the screenshot.

**Comment by jens-maus** [comment]
This looks more like the SD card image is somewhat broken or was not written correctly to the microSD card. please try to flash the *.img on the microSD card again. Also verify that the *.img matches the sha256 checksum so that you can be 100% sure that the downloaded *.img is not broken.

**Comment by jens-maus** [comment]
Any news on this?

**Comment by FraatRamski** [comment]
Yes, SD recreated. 

Frohe Ostern!
