### ISSUE TITLE
Issues mit .State()

### ISSUE THREAD

**Issue by MichaelN0815** [jens-maus/RaspberryMatic#942]
a) State(x) bricht keine laufende Verzögerung ab, im Gegensatz zur WebUI
b) State(x,0,true) oder State(x,0,false) ergibt einen ScriptRuntimeError
c) State(x,1,true) oder State(x,1,false) wird ausgeführt

a) ist das das gewünschte Verhalten? _EDIT: offensichtlich, denn  Version 2.7.8 (Dezember 2013) auf der CCU2 zeigt das gleiche Verhalten_

mein Verständnis war bisher, das der Befehl State() folgendermaßen definiert ist, den dies würde dem Verhalten der WebUI entsprechen:

State(var Value,{integer Delay in ms[0]},{boolean Retrigger[true]})
! Value = Wert der geschrieben wird
! Delay = Verzögerung in ms (optional, Standard 0)
! Retrigger = bisheriger Delay wird abgebrochen/überschrieben (optional, Standard true)

allerdings bricht .State(x) keine laufende Verzögerung ab:

```
! Systemvariable Protokolleintrag, Zeichenkette, protokolliert
! Systemvariable XXLogik, Logikwert, protokolliert
dom.GetObject (ID_SYSTEM_VARIABLES).Get ("Protokolleintrag").State("nach 20sec auf 1 (wahr)");
dom.GetObject (ID_SYSTEM_VARIABLES).Get ("XXLogik").State(1,20000);

dom.GetObject (ID_SYSTEM_VARIABLES).Get ("Protokolleintrag").State("sofort auf 0 (falsch)");
dom.GetObject (ID_SYSTEM_VARIABLES).Get ("XXLogik").State(0);  
```

Sollte eigentlich zum Abbruch der in Zeile 1 gesetzten Verzögerung führen
Ergebnis ist aber: 

> 15:48:24	11.10.2020	Protokolleintrag	nach 20sec auf 1 (wahr)
> 15:48:24	11.10.2020	Protokolleintrag	sofort auf 0 (falsch)
> 15:48:24	11.10.2020	XXLogik			ist falsch
> 15:48:44	11.10.2020	XXLogik			ist wahr

Erst

```
dom.GetObject (ID_SYSTEM_VARIABLES).Get ("Protokolleintrag").State("nach 20sec auf 1 (wahr)");
dom.GetObject (ID_SYSTEM_VARIABLES).Get ("XXLogik").State(1,20000);

dom.GetObject (ID_SYSTEM_VARIABLES).Get ("Protokolleintrag").State("sofort auf 0 (falsch)");
dom.GetObject (ID_SYSTEM_VARIABLES).Get ("XXLogik").State(0,1);
```

führt zum Abbruch:

> 15:50:03	11.10.2020	Protokolleintrag	nach 20sec auf 1 (wahr)
> 15:50:03	11.10.2020	Protokolleintrag	sofort auf 0 (falsch)
> 15:50:03	11.10.2020	XXLogik			ist falsch
> 

b)
Dieser Code führt zu einem ScriptRuntimeError, obwohl es gültiger Code sein sollte:

```
dom.GetObject (ID_SYSTEM_VARIABLES).Get ("XXLogik").State(1,0,true);
dom.GetObject (ID_SYSTEM_VARIABLES).Get ("XXLogik").State(1,0,false);
```

c) Mit Verzögerung >0 verhält sich der Befehl erwartungsgemäß.

```
dom.GetObject (ID_SYSTEM_VARIABLES).Get ("XXLogik").State(1,1,true); ! bricht laufende Verzögerung ab
dom.GetObject (ID_SYSTEM_VARIABLES).Get ("XXLogik").State(1,1); ! bricht ebenfalls laufende Verzögerung ab
```

Herleitung siehe [https://homematic-forum.de/forum/viewtopic.php?f=19&t=61630](https://homematic-forum.de/forum/viewtopic.php?f=19&t=61630)

**Comment by jens-maus** [comment]
Danke für den Hinweis. Ab der Version `R1.00.0388.0225` von ReGaHss sollte das Verhalten entsprechend geändert sein. D.h. ein `State(x, 0, true/false)` sollte möglich sein und das Default des retrigger Arguments sollte nun standardmäßig `false` sein damit es mit dem standardmäßigen `State(x)` Aufruf ohne Argumente nun entsprechend kompatibel ist.
