### ISSUE TITLE
Hue-Verknüpfung löschen

### ISSUE THREAD

**Issue by QuoxelNet** [jens-maus/RaspberryMatic#943]
**Is your feature request related to a problem? Please describe.**
Nein.

**Describe the solution you'd like**
In den Einstellungen sollte ein Button existieren, mit dem man eine bestehende Hue-Kopplung aufheben kann.

**Describe alternatives you've considered**
Ein Herauslöschen der Hue Bridge IP aus dem Dialog und anschließendes Löschen der Geräte würde auch reichen.

**Additional context**

**Comment by jens-maus** [comment]
Duplicate of #1001
