### ISSUE TITLE
Raumliste ist leer

### ISSUE THREAD

**Issue by wernersv** [jens-maus/RaspberryMatic#944]
**Describe the bug**
Raumliste in den Einstellungen ist leer

**To Reproduce**
1. Gehe auf Einstellungen -> Räume
2. Die Raumliste ist leer. Es werden auch keine Schaltfächen zur Erstellung eine Raumes angezeigt.
3. In der JS Console steht folgender Fehler: 
```
prototype.js:399 Uncaught SyntaxError: missing ) after argument list
    at prototype.js:399
    at prototype.js:640
    at prototype.js:600
    at Array.forEach (<anonymous>)
    at Array.each (prototype.js:599)
    at Array.collect (prototype.js:639)
    at String.evalScripts (prototype.js:399)
    at Function.<anonymous> (prototype.js:214)
    at prototype.js:236
```
**Expected behavior**
Die Raumliste sollte angezeigt werden und zu bearbeiten sein.

**Screenshots**
![image](https://user-images.githubusercontent.com/22543570/96104991-cb833d80-0ed9-11eb-8f61-df5c03e9d5f5.png)

**System information (please complete the following information):**
 - RaspberryMatic 3.53.30.20200919
 - RaspberryPi

**Additional context**
 Es wurden neue HM-IP Thermostate angelernt. Diese sind auch in der Geräteliste sichtbar. 
 Das Verhalten ist mit aktuellem Chrome, Firefox und IE 11 nachvollziehbar. Getestet wurde jeweils im Inkognito-Modus.
 Über die Unterkanäle in der Geräteliste können die Geräte weiterhin zu definierten Räumen hinzugefügt oder entfernt werden.

**Comment by jens-maus** [comment]
Tut mir leid, aber das bekomme ich hier nicht reproduziert. Siehe:

![Oct-15-2020 22-10-16](https://user-images.githubusercontent.com/5887769/96180840-55abc000-0f33-11eb-91cb-a9ec0f35437e.gif)

**Comment by wernersv** [comment]
Das ist Wenger schön.
Ich hab es gerade nochmal auf meinem Telefon getestet und hab dort auch keine List mit Räumen. 

Hast du eine Idee wie ich das weiter debuggen könnte?

**Comment by wernersv** [comment]
Die prototype.js ist ja schon etwas älter. Zwischen der verwendeten Version 1.6.1 und der neuesten Version 1.7.3 liegen immerhin 5 Jahre. Könnte es damit zusammenhängen?

Alles was ich finden konnte deutet auf einen Syntax-Fehler im JS hin bei dem Parameter für eine Funktion nicht korrekt getrennt wurden.
![image](https://user-images.githubusercontent.com/22543570/96429636-76a93500-1201-11eb-991b-03b1128346d3.png)
Hilft es wenn ich das Ergebnis von "eval(script)" anhänge?

**Comment by jens-maus** [comment]
@wernersv Nein, ich denke nicht das hier ein genereller Fehler in der prototype.js vorliegt. Ja, Sie ist älter, aber das alleine ist noch kein Merkmal. Und der von dir gezeigte Fehler taucht sehr oft auf wenn es irgendwelche Probleme in der Skriptabarbeitung gibt oder ähnliches, denn der `eval(script)` Aufruf ist der zentrale Punkt wo die Abarbeitung passiert. Für mich sieht das also nach einem Folgefehler aus und nicht nach der eigentlichen Ursache.

Du müsstest also erst einmal IMHO herausfinden was deine Installation von den anderen tausend unterscheidet wo die Gruppenfunktion offensichtlich problemlos funktioniert.

**Comment by jens-maus** [comment]
Was mir gerade einfällt. Hast du vielleicht irgendwann mal einen Raum mit Sonderzeichen oder ähnlichem ausgestattet? Vielleicht liegt hier ja schon das Problem begraben.

**Comment by wernersv** [comment]
Es gab bis vor einer Stunde einen Eintrag in der Favoritenliste mit dem Namen "Tür-/ Fenstersensoren", welchen ich nach "Tuer-Fenstersensoren" umbenannt habe.

Hier die Liste der Räume, wie sie von dem "eval(script)" zurückgegeben wird:
'Badezimmer';
'Dachboden';
'Erdgeschoss';
'Hobbyraum';
'Keller';
'Kinderzimmer Jessi';
'Kinderzimmer Lucy';
'Küche';
'Obergeschoss';
'Schlafzimmer';
'Terasse';
'Wohnzimmer';

Das einzige "Sonderzeichen", wenn man das so nennen kann, ist das "ü" in Küche.
Ich kann mich auch nicht erinnern, dass ich da irgendwas geändert hätte. Die Liste der Räume existiert in der Form schon seit mind. 8 Jahren.
Die letzten Änderungen an der Konfiguration waren die HMIP-Rauchmelder HmIP-SWSD vor 2 Jahren und zuletzt die HMIP Thermostate HmIP-eTRV-B und ein HMIP Schaltaktor HmIP-DRSI4 (hierzu gibt es ein neu angelegtes Programm). Keiner der Namen enthält Sonderzeichen wie "<>/\,;:&". Umlaute finden Verwendung wie in dem Namen "Heizung Gäste-WC" (HMIP), welches neu ist. Das hat aber vorher bei dem Nicht-IP Thermostat in "Heizung Küche" keine Rolle gespielt.

Ist vielleicht eine Ausgabe der xmlapi hilfreich?

**Comment by jens-maus** [comment]
@wernersv Du kannst mir auch gerne privat ein Backup deiner Zentrale zukommen lassen, dann kann ich versuchen mit deiner Konfiguration das nachzustellen.

**Comment by wernersv** [comment]
@jens-maus , Mail ist raus.

**Comment by jens-maus** [comment]
@wernersv Danke dafür. Eine kurze Frage vorab (weil ich mir gerade anschaue was da so in deinem Backup an allgemeinen Dingen zu finden ist): Welches Funkmodul bzw. Funkmodullösung setzt du ein?

**Comment by wernersv** [comment]
@jens-maus, ich habe das folgende Modul: https://wiki.fhem.de/wiki/Datei:HM-MOD-UART-Oben.jpg

Und was fange ich jetzt mit der regadom an?
Da fällt mir ein, dass mein HmIP-DRSI4 schon der zweite ist. Der erste war defekt und ließ sich nur mit hängen und würgen nach einem Telefonat mit den Jungs von ELV entfernen.

**Comment by jens-maus** [comment]
@wernersv Ok, das ist das alte `HM-MOD-RPI-PCB` wie es richtig heisst. Was mir bereits aufgefallen ist, ist das du eine Datei `/etc/config/no-coprocessor-update` in deiner Konfiguration hast. Die solltest du entfernen, denn sonst bekommt dein Funkmodul niemals Firmware-Updates beim Neustart von RaspberryMatic und das kann zu potentiellen Problemen führen.

Und an deiner regadom sitze ich noch dran. Muss noch verstehen warum die oben gezeigten Fehlermeldungen "device pointer is null" kommen. Das sind auf jeden fall die auslöser dafür das die Raumliste nicht angezeigt wird. In der regadom findet man mit der `id=6078` auch ein Objekt mit dem komischen Namen "HaustürC". Sieht mir so aus als ob das wohl mal ein Raum war der nicht korrekt gelöscht wurde. Ggf. ist das eine Objektleiche in deiner regadom datei die ursächlich für das nun aufgetauchte problem ist das die raumliste sich gar nicht mehr aufrufen lässt.

**Comment by jens-maus** [comment]
@wernersv Noch hab ich zwar nicht verstanden was da genau schief läuft und ich kapier auch nicht warum du da eine Objektleiche hast, aber wenn du das folgende Kommando unter "Skript testen" mal ausführst sollte danach sich die Kanalliste bei dir wieder öffnen lassen:

```
dom.DeleteObject(6147);
```

Und natürlich beachten: Vorher ein Backup machen!

**Comment by jens-maus** [comment]
@wernersv Hab zumindest rausgefunden das dieses verwaiste Objekt anscheinend zu einem Gerät mit der SGTIN `00259BE9950552` gehört, das es allerdings in der WebUI bei dir nicht mehr gibt. War/Ist das ein altes Gerät von dir? Wenn ja, würden die Einträge wohl nicht alle korrekt rausgelöscht.

**Comment by wernersv** [comment]
WriteLine(dom.DeleteObject(6147)); lieferte ein true zurück.
Und siehe da... Die Räume sind auch wieder sichtbar. Ich konnte auch neue Räume anlegen.

Sind da noch mehr Leichen zu SGTIN 00259BE9950552 ? Wenn nicht, dass kann der Issue aus meiner Sicht, sofern du es nicht für die Implementierung einer Fehlerbehandlung für ähnliche Fälle benötigst, geschlossen werden. 

Zu "HaustürC":
Es hing also wie ich schon vermutet hatte mit dem defekten 4-Fachaktor zusammen. 
Jedes einzelne der 4 Relais lässt sich ja über 3 verschiedene Inputs (hier Haustür[ABC]) steuern. HaustürC war beim defekten Aktor der 3. Input von Relais 1. Das war ein Krampf das überhaupt wieder zum laufen zu bringen. Die CCU hatte sich komplett weggehangen und wollte nicht mehr reagieren. Auch der Versuch das Ding zu löschen war erst nach mehreren Anläufen erfolgreich.

Sei es drum. Die CCU ist jetzt erfolgreich neu gestartet und es schaut auf den ersten Blick alles gut aus.

Danke für deine schnelle Hilfe

**Comment by jens-maus** [comment]
Nun, ich schaue gerade noch ob ich diesen speziellen fall irgendwie abfangen kann und die raumliste sich trotzdem darstellen lässt, trotz dieser offensichtlichen Objektleiche. Und du kannst ja selber gerne mal in der `/etc/config/homematic.regadom` Datei nachschauen ob du zu der SGTIN weitere leichen/einträge findest. Kann gut möglich sein das du da mehr findest. Und wenn sich da die CCU damals eben genau dann verabschiedet hat als du versuchst hast da was zu löschen kann es gut sein das das die inkonsistenz in der regadom hervorgerufen hat. Ein mulmige gefühl gegenüber der konsistenz der regadom hätte ich allerdings mitunter weiterhin.

Und lösche mal doe `no-coprocessor-update` Datei in /etc/config und wechsel irgendwann mal auf das neue Funkmodul weil das alte/kleine eher ein Auslaufmodell ist und zunehmend es zu problemen kommt...
