### ISSUE TITLE
Einrichtung von Gruppen für Homematic Geräte nicht mehr möglich.

### ISSUE THREAD

**Issue by Ako3004** [jens-maus/RaspberryMatic#945]
**Describe the bug**
Ich habe seit gerade eben erst die neueste RaspberryMatic Version aufgesetzt und stoße jetzt beim Anlegen von Gruppen auf einen Fehler. Es können für Homematic Geräte keine Gruppen mehr angelegt werden.

**To Reproduce**
Wechsle ich unter Einstellungen auf Gruppen und versuche dort mit "Neu" eine neue Gruppe anzulegen und diese dann nach Eingabe des Gruppennamens zu speichern, so bleibt die Oberfläche im Browser stehen mit der Meldung "Gruppe wird gespeichert...Bitte warten. Die direkten Verknüpfungen werden konfiguriert.".
Es passiert nichts mehr. In der Browserconsole erscheint der JS Fehler:

```
Uncaught TypeError: Cannot read property 'id' of undefined
    at <anonymous>:361:72
    at Object.p (knockout.js:8)
    at _SaveGroup (<anonymous>:360:18)
    at SaveGroup (<anonymous>:335:16)
    at HTMLDivElement.onclick (index.htm?sid=@yUbspNoRQ4@:1)
```

Es spielt keine Rolle ob man nur die Gruppe selbst anzulegen versucht, oder gleich ein paar Geräte zuweisen möchte.
Der Fehler bleibt, es können keine Gruppen mehr angelegt werden. Interessanterweise tritt das Problem beim Anlegen einer HomematicIP Gruppe nicht auf. Diese können angelegt werden.

**Additional context**
Ausganslage ist die aktuelle Version 3.53.30.20200919, clean installiert sowie resettete Homematic Heizkörper- und Wandthermostate. Keine Extras, keine weiteren Konfigurationen. Ausprobiert in Edge, FF und Chrome (Neueste Versionen)

Spoiler:
ich bin grade eben erst nach Firmwareupdate der CCU2 wegen genau diesem Fehler den Schritt auf die RaspberryMatic gegangen, dort tritt mit der neuesten Firmware der Fehler auch auf. Habe den Fehler bereits an EQ-3 gemeldet. Es scheint also mit der neuesten Version von EQ-3 zusammenzuhängen. Noch keine Antwort. Ich werde heute noch mal versuchen das Problem mit älterer Firmware zu reproduzieren.  Melde mich hier wieder mit Ergebnis.

**Comment by Ako3004** [comment]
Hab jetzt auf der CCU2 zurück auf die alte Firmware 2.49.18 gewechselt. Hier tritt das Problem noch nicht auf. Es ist also ein Problem mit der Firmware von EQ-3 das hier in RaspberryMatic übernommen wurde.

**Comment by jens-maus** [comment]
> Wenn man an die Gruppen ran muss sollte man aktuell von der neusten Version absehen.

Also von solchen pauschalisierten Aussagen sollte man vielleicht etwas abstand nehmen und mal eher sachlich bleiben, denn hier kann es noch ganz andere Ursachen geben. Denn ich habe hier (vmtl. wie viele anderen tausend andere Nutzer) bis jetzt davon noch nichts gemerkt. Siehe:

![Oct-15-2020 20-14-04](https://user-images.githubusercontent.com/5887769/96170024-52103d00-0f23-11eb-917f-8c4937affef1.gif)

Also bitte mal einfach, sachlich und vollkommen normal noch einmal die einzelnen Schritte erklären oder einfach auch mal einen Screencase (animated gif) hier hochladen der das Problem zeigt.

**Comment by Ako3004** [comment]
Hallo Jens, was war daran jetzt nicht einfach, unsachlich oder nicht neutral? Nichts weiter als eine vollkommen logische Schlussfolgerung und auch keinerlei Kritik am Projekt. Entschuldigung wenn ich dich verärgert haben sollte, das war nicht meine Absicht.

Wie auch immer, es stellt sich noch so dar wie beschrieben. Browser/Geräteabhängigkeit kann ich ausschließen (Tablet, Notebook, DesktopPC getestet, Edge, FF, Chrome). Es tritt so auf in RaspberryMatic wie auch auf der CCU2 mit der neuesten Firmware. Ich hab heute Abend die CCU2 auf eine ältere Firmware zurückgesetzt und dann konnte ich dort wieder ganz normal Gruppen anlegen. Hier mal die Screenshots zum Ablauf auf RaspberryMatic:

![screen-recording](https://user-images.githubusercontent.com/46303527/96185365-12a11b00-0f3a-11eb-8867-7d409b5aff1c.gif)

Der Screen verändert sich nicht mehr, das System friert an dieser Stelle ein.

![SharedScreenshot](https://user-images.githubusercontent.com/46303527/96185892-e6d26500-0f3a-11eb-93e0-d60d00976df6.jpg)

Ich hab die Gegenprobe gemacht, auf der CCU2 wie auch beim Test mit einer Gruppe für HomematicIP tritt der JS Fehler nicht auf. Die Tests habe ich im "Factory reset" gemacht, also ohne weitere Extras.

**Comment by jens-maus** [comment]
Tut mir leid, aber auch die Abfolge die man aus deinem Screencast hier herauslesen kann, kann ich hier problemlos durchführen und es kommt zu keinerlei Fehlverhalten oder Exception egal ob ich eine HmIP-Heizungsgruppe oder traditionelle BidCos Heizungsgruppe erstellen lasse. Ich kann den Fehler hier leider auf mehreren Testsystemen nicht reproduzieren. Aber vielleicht kann hier jemand anderes ja noch weiteren Input geben und versuchen dein Problem nachzustellen.

**Comment by Ako3004** [comment]
Danke, ich werds noch mal versuchen indem ich auf der CCU2 nochmal die neueste Firmware aufspiele und schaue ob der Fehler dann wieder auftaucht. Dann werd ich mal noch versuchen ob der Fehler auf dem Raspi mit einer älteren RaspberryMatic Version verschwindet. Und die Supportanfrage bei EQ-3 ist ja auch noch offen ;)
Sobald ich was weiss meld ich mich hier wieder.

**Comment by oradke** [comment]
Ich kann den Fehler auch nicht reproduzieren auf meinem System mit der neuesten Firmware.

Von: Ako3004 <notifications@github.com>
Gesendet: Donnerstag, 15. Oktober 2020 23:10
An: jens-maus/RaspberryMatic <RaspberryMatic@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [jens-maus/RaspberryMatic] Einrichtung von Gruppen für Homematic Geräte nicht mehr möglich. (#945)


Hallo Jens, was war daran jetzt nicht einfach, unsachlich oder nicht neutral? Nichts weiter als eine vollkommen logische Schlussfolgerung und auch keinerlei Kritik am Projekt. Entschuldigung wenn ich dich verärgert haben sollte, das war nicht meine Absicht.

Wie auch immer, es stellt sich noch so dar wie beschrieben. Browser/Geräteabhängigkeit kann ich ausschließen (Tablet, Notebook, DesktopPC getestet, Edge, FF, Chrome). Es tritt so auf in RaspberryMatic wie auch auf der CCU2 mit der neuesten Firmware. Ich hab heute Abend die CCU2 auf eine ältere Firmware zurückgesetzt und dann konnte ich dort wieder ganz normal Gruppen anlegen. Hier mal die Screenshots zum Ablauf auf RaspberryMatic:

[screen-recording]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F46303527%2F96185365-12a11b00-0f3a-11eb-8867-7d409b5aff1c.gif&data=04%7C01%7C%7Cbfe7b7aab07640339b1608d8714eb0cb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637383930070842784%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VNzHeEv5zM3moIDm0FeBelSTwWLrLm7xgXwA88Y7U5g%3D&reserved=0>

Der Screen verändert sich nicht mehr, das System friert an dieser Stelle ein.

[SharedScreenshot]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F46303527%2F96185892-e6d26500-0f3a-11eb-93e0-d60d00976df6.jpg&data=04%7C01%7C%7Cbfe7b7aab07640339b1608d8714eb0cb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637383930070852676%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RkL2YJCQvxXZ1qya5RY7KgKHLla3K2fQMEi%2F8dJB0iQ%3D&reserved=0>

Ich hab die Gegenprobe gemacht, auf der CCU2 wie auch beim Test mit einer Gruppe für HomematicIP tritt der JS Fehler nicht auf. Die Tests habe ich im "Factory reset" gemacht, also ohne weitere Extras.

**Comment by jens-maus** [comment]
Ok, danke für die Bestätigung. Dann bitte die Diskussion über dieses vermeintliche Problem ins HomeMatic Forum verlagern und dieses Ticket hier gerne wiedereröffnen wenn neue Erkenntnisse daraus entstehen die darauf hindeuten das es sich hier in der Tat um einen Bug handelt.

**Comment by Ako3004** [comment]
Ich geb noch kurz einen Abschlussbericht:
Downgrade von RaspberryMatic hat den Fehler behoben (zurück auf 3.49.17.20200131)
(Und upgrade der CCU2 auf die neueste Firmware: hier taucht der Fehler wieder auf)
Mir ist soweit erst mal geholfen, mal sehen was sich vom EQ3 Support und dem hm forum noch ergibt...

**Comment by Thorsten1982** [comment]
Hallo, wollte einmal mitteilen das ich genau den gleichen Fehler habe. Wollte eine Gruppe anlegen und hat mit dem gleichen Fehler nicht funktioniert. Habe Version 2.53.34.

**Comment by Thorsten1982** [comment]
Habe jetzt gerade bemerkt das der Fehler nur auftritt wenn sich noch Geräte im Posteingang befinden, habe diese zuerst als fertig markiert so das diese nicht mehr im Posteingang gewesen sind und dann konnte ich eine Gruppe erstellen.

**Comment by Ako3004** [comment]
Ich bin zwar derzeit mit einer älteren Version glücklich :D 
Werde das mal mit der neuesten Version ausprobieren demnächst, danke für die Info.

**Comment by MartinEckes** [comment]
> Habe jetzt gerade bemerkt das der Fehler nur auftritt wenn sich noch Geräte im Posteingang befinden, habe diese zuerst als fertig markiert so das diese nicht mehr im Posteingang gewesen sind und dann konnte ich eine Gruppe erstellen.

Kann ich so bestätigen. Erst ging es, dann hatte ich ein HmIP Drehkontakt hinzugefügt und irgendwie auch ein komisches Fragment davon in der Geräte Liste gehabt. Leider hab ich davon kein Bild mehr, auch das Symbol Bild war kaputt. Ich wollte danach das Gerät der Grupe hinzufügen, ging nicht mehr. Die Gruppe gelöscht ging noch, eine leere Gruppe ging auch nicht mehr. Dieses Eintrag von Thorsten oben gefunden und tatsächlich Posteingang hatte noch mal den FensterDreh Kontakt drin, diesen noch mal hinzugefügt (Gefühlt zwei mal gemacht) und schon war das Fragment in der Geräteliste weg. Und man konnte eine Gruppe wieder bilden. Der JavaScript Fehler war der selbe wie oben abgebildet.

**Comment by jens-maus** [comment]
Danke für die Info. Vielleicht kann das jemand ja noch einmal genauer analysieren udn testen dann könnten @jp112sdl und ich ggf einen Bugfix Patch dafür entwickeln damit andere nicht auch noch in die Falle tappen.

**Comment by jp112sdl** [comment]
Der eingangs aufgezeigte Fehler kommt scheinbar irgendwo von 
[/opt/HMServer/pages/GroupEditPage.ftl:L503-L595](https://github.com/eq-3/occu/blob/master/HMserver/opt/HMServer/pages/GroupEditPage.ftl#L503-L595)

Diese wurde für die CCU FW 3.53.27 angepasst.
Eingefügt ab Zeile 521:
```
            homematic("Interface.setMetadata", {"objectId":item.device.id, "dataId": "inHeatingGroup", "value" : "true"});
        });

        ko.utils.arrayForEach(viewModel.assignableDevices(), function(item) {
            homematic("Interface.setMetadata", {"objectId":item.device.id, "dataId": "inHeatingGroup", "value" : "false"});
```


Mein Vorschlag: 
Diese Zeilen mal entfernen und schauen, ob das Problem dann weg ist.
Ich habe keine HmIP Geräte und kann es daher nicht testen

Hier die Differenz noch mal als Bild:
<img width="1522" alt="Bildschirmfoto 2020-11-17 um 10 02 53" src="https://user-images.githubusercontent.com/18190139/99368918-10750800-28bc-11eb-9a80-dcc941c52b2b.png">

**Comment by Ximerox** [comment]
Hallo,
habe Firmware 3.53.34 und bin nun auf das Selbe Problem gestoßen. Und tatsächlich war die Ursache, dass noch ein Gerät im Posteingang war. Bei mir war es allerdings ein HmIP im Posteingang und folglich ging es auch nicht eine HmIP-Gruppe anzulegen. Und ich hatte schon Gruppen angelegt gehabt.

**Comment by Macius78** [comment]
Hallo, 

danke euch für den Hinweis... die Geräte aus dem Posteingang zu entfernen, hat auch bei mir das Problem mit den Einfrieren beim Anlegen von Gruppen behoben

**Comment by markusbauernschmitt** [comment]
Hallo @jens-maus ,

dieFrage eines Neulings. Warum wurde der Bug als Closed markiert? Der Bug wurde ja schon sehr genau analysiert. Ab welcher Version er auftritt und in welcher Konstellation. Sogar die Ursache des Fehlers wurde, soweit ich das gesehen habe, schon auf potentielle Codezeilen eingegrenzt.

Auch wenn glücklicherweise ein Workaround gefunden wurde, ist es doch ein harter Softwarefehler. Der übrigens in der Firmware Version 2.55.5 immer noch auftritt, weswegen ich auch auf diesen Thread gestoßen bin. 

Vg

P.S. Danke für den Workaround. Er hat auch bei mir geholfen.

**Comment by yppiks** [comment]
Hallo,
ich hatte soeben mit der aktuellen Version (3.55.5.20201226) RPi3 das gleiche Problem. Ich habe ein neues Wandthermostat angelernt und wollte es im Posteingang einer bestehenden Gruppe hinzufügen.

Beholfen habe ich mir dem Öffnen einer weiteren Weboberfläche. Im Posteingang habe ich das Wandthermostat fertig gestellt. Danach habe ich ihn der Gruppe hinzugefügt, was problemlos klappte. Vielleicht hilft es ja bei der Analyse..

Viele Grüße

**Comment by jp112sdl** [comment]
In der 3.55.10 wurde bzgl. der HmIP Heizgruppen was verändert.
Vielleicht ist das Problem mit der nächsten Version dann behoben

**Comment by yppiks** [comment]
Meine Heizgruppen verwenden normale Homematic - keine HMIP - Geräte

**Comment by ingwu** [comment]
Hallo,
ich muss leider mitteilen, dass ich das Problem in der 3.57.4.20210320 habe und zwar ohne das ich Geräte im Posteingang habe.
Leider habe ich daher auch keinen funktionierenden Workaround.
Bei mir hängt sich die GUI jedes mal auf, wenn ich eine Gruppe anlegen möchte.

**Comment by makuris** [comment]
Hallo,
ich habe dieses Problem leider auch. Tatsächlich tritt es immer auf, wenn ich über den Posteingang ein neues Gerät direkt in eine Gruppe hinzufügen möchte: Alles friert ein. Auch nach 20 Minuten immernoch die Meldung "Gruppe wird gespeichert". Wenn nichts im Posteingang ist, dann geht es.

**Comment by ako-3004** [comment]
Für die, die das Problem nicht wie oben genannt umgehen können, bei mir läuft es mit der etwas älteren Version 3.49.17.20200131 fehlerfrei. Ich sehe derzeit von einem Update ab bis das Problem sicher behoben wurde.

**Comment by ingwu** [comment]
Problem scheint bei mit 3.57.5.20210525 gelöst zu sein, Danke!

**Comment by hsteinhaus** [comment]
Das Problem tritt bei mir mit 3.61.7.20220305 (raspmatic_oci_arm64) nach wie vor auf, und zwar nach dem Anlernen von zwei HM-CC-RT-DN und einem HM-TC-IT-WM-W-EU, die naheliegenderweise eine Gruppe bilden sollen.

**Comment by sirvolcano** [comment]
Moin,
ich bin ein Neuling in diesem Gebiet (auch in GitHub) und hoffe, dass ich hier richtig bin. Ich habe seit ca. 1,5 Monaten Homematic IP Geräte (Fensterkontakte HMIP-SWDO, Wandthermostate HmIP-WTH-1 und Heizthermostate HmIP-eTRV-E) und steige gerade von der hausgemachten Cloud und Access Point Lösung auf Home Assistant und RaspberryMatic um. 

Das System ist auf ein Raspberry Pi 4B mit 8GB und 32GB SD-Karte wie im WEB beschrieben (RapberryMatic als Add On mit Aktuelle Firmwareversion: 3.65.11.20221218) aufgesetzt und die Verknüpfung zum Home Assistant geschaffen. Verwendete Funk-Stik ist HmIP-RFUSB.
Testweise habe ich erstmal nur Geräte aus einem Zimmer von Access Point abgelernt und resettet. Dann problemlos in RaspberryMatic neu angelernt. 

**Das oben beschriebenes Problem habe ich, auch wenn ich keine Geräte im Posteingang habe. Ich kann eine leere Gruppe mit "HmIP-Heizungssteuerung" anlegen. Sehe auch die IP-Geräte und kann diese auch der Gruppe hinzufügen. Sobald ich mit ok bestätige rödelt das System ohne Ende - zeigt "Bitte warten. Die direkten Verknüpfungen werden konfiguriert." - und es geschieht nix, egal wie lange ich warte! Das gleiche auch, wenn ich versuche die Gruppe mit einzelnen Geräte zu erstellen oder eine neue Gruppe erstelle und beim Erstellen die Geräte einfüge.** Derzeit gehe ich den Weg die Geräte und dessen Kanäle händisch direkt verknüpfe - was gut funktioniert. Das ist aber sehr mühselig und fehlerträchtig. 

Ich bin mir nicht sicher, ob das ein Bug ist oder ich hier ein Kardinalfehler mache! Ich hoffe, ich bin hier richtig. Sitze schon seit einigen Tagen daran und habe viel gesucht und gelesen. Der Thread hier ist das einig passende, was ich gefunden habe.

**Comment by gost4711** [comment]
Schließe mich meinem Vorredner an. Bin schon am verzweifeln. Ich hoffe das jemand helfen kann.

**Comment by jens-maus** [comment]
> Moin, ich bin ein Neuling in diesem Gebiet (auch in GitHub) und hoffe, dass ich hier richtig bin.

Nein, du bist hier nicht richtig. Das ist hier ein uraltes Issue Ticket von 2020 das du einfach so wieder auspackst und highjackst. GitHub ist kein Diskussionsforum, sondern eine Projektmanagementoberfläche und das Problem das hier ursprünglich eröffnet wurde ist bearbeitet und fertig. Bitte also offene Tickets suchen oder noch besser in einschlägigen Diskussionsforen/bereichen nach Lösungen suchen.
