### ISSUE TITLE
Ventilstände von HmIP-FALMOT-C12 im Status anzeigen

### ISSUE THREAD

**Issue by alexhass** [jens-maus/RaspberryMatic#946]
Bei meinen HmIP-FALMOT-C12 würde ich gern wissen, wie die Ventile gerade stehen. Dazu möchte ich nicht extra mehrere Heizkreisverteiler öffnen, um auf die Displays zu schauen. 

Versuchsweise habe ich schon 15 x Skripts erstellt und diese in 15 Variablen geschrieben. Alles echt unübersichtlich. Problem ist hier, dass es keinen passende Auslösung (Änderung/Aktualisierung funktionieren nicht) gibt und ich wegen dem DutyCyle nicht alle 1-5min abfragen möchte.

Warum das alles? Ich hab Räume die eisekalt sind und ich verstehe nicht warum. Das Thermometer zeigt 20 grad an, obwohl die SOLL temp bei 23 grad liegt und das Ventil LEVEL laut Historian bei maximum 0,05 liegt.

**Comment by jens-maus** [comment]
Auch hier gibt es im Zuge der RaspberryMatic Entwicklung keinerlei Ansatzpunkte für Verbesserungen da dies Dinge sind die in der Gerätefirmware des FALMOT implementiert sind und diese ist komplett closed source. 

Im HomeMatic Forum gibt es dazu eine entsprechende diskussion. Siehe:

https://homematic-forum.de/forum/viewtopic.php?f=58&t=50958

Daher bitte dort weiter diskutieren denn Dies hier bzw GitHub ist eine Entwicklungsplatform und kein Diskussionsforum.

**Comment by alexhass** [comment]
Den case kenne ich. Bringt einen aber nicht weiter. Ich dachte raspmatic ist das nächste ccu release? Deshalb war das hier ein feature request.

Nachdem ccu historian auf die werte LEVEL zugreifen kann, kann raspmatic das sicher auch und kann das ventil in dem hardware gerät anzeigen. So wie dies bei einem hezkörper auch geht.

Die hardware liefert die werte schon. Sie werden nur nicht angezeigt.

Sorry, dass ich die trennlinien zwischen dir und eq3 nicht kenne.

Das hier ist ein valider feature request.

**Comment by jens-maus** [comment]
Mag sein das das ein valider feature request im allgemeinen ist, aber eben nicht im bezug darauf was RaspberryMatic als Projekt oder ich leisten kann. Dein vorgebrachtes Problem ist ein Fehler in der FALMOT Gerätefirmware und daran kann einzig allein eQ3 etwas ändern und auch nur wenn du denen das via deren Support meldest! Genau deshalb geht es hier nicht weiter.

**Comment by alexhass** [comment]
Nachdem ich heute Feedback von EQ3 erhalten habe wegen teilweise kalten Räumen (ventil immer zu) wurde mit empfohlen den HMIP-FALMOT-C12 auf Werkseinstellungen zurückzusetzen.

Das geht, indem man die Taste-A (Homematic-Taste) für 4sekunden drückt bis sie blinkt und dann direkt nochmal 4 sekunden bis es wieder grün wird. Dadurch muss der FALMOT nicht aus dem System gelöscht werden und er zieht sich seine Konfiguration wieder von der CCU.

So... was ist anschliessend passiert? Lustiges Ventil auf/zu... ok... aber meine kalten Räume haben gerade mal ihre Ventile offen. Mal schauen, ob das anhält.

Und wie durch Zauberhand ist auf der CCU und in @Home-App plötzlich der Ventilstand augetaucht! Crazy was ein Werksreset des FALMOT für positive Effekte haben kann... hoffe das hilft noch anderen, die vieleicht das gleiche Problem haben.

**Comment by jens-maus** [comment]
@alexhass Meine Erfahrung ist, das auch einfach ein kurzzeitiges stromlos machen den selben Effekt bringt und der FALMOT danach wieder für eine gewisse Zeit wieder recht problemlos arbeitet - bis sich das problem jedoch wieder einstellt und man dann wieder irgendwann ihn stromlos machen muss. IMHO (und wie das im HomeMatic Forum auch diskutiert wurde) liegt hier ein gewisser Fehler in der Regelungstechnik des FALMOT das nur durch ein Firmwareupdate behoben werden kann.

**Comment by alexhass** [comment]
Mach mich fertig... Gibt es dieses Firmware Update schon - vieleicht auch nur inoffiziell?

**Comment by jens-maus** [comment]
Nein, nicht das ich wüsste.
