### ISSUE TITLE
HmIP-HAP: RSSI und verbundene Geräte

### ISSUE THREAD

**Issue by alexhass** [jens-maus/RaspberryMatic#947]
Aktuell scheint es absolut intransparent, welche Geräte mit dem HmIP-HAP verbunden sind. Ich würde gern sehen, welche Geräte damit verbunden sind und was sie für RSSI Werte haben.

Mein Gefühl ist, kein Gerät nutzt den Router... Ich habe einen HAP etwa 2m Luftlinie von einem BROLL positioniert. Trotzdem hat der BROLL seine RSSI Werte in der CCU nicht geändert. Deshalb vermute ich, dass er sich garnicht damit verbunden hat, sondern lieber die CCU im Keller durch Betondecke und mehrere Wände nutzt...

**Comment by jens-maus** [comment]
Und leider ist ws auch bei diesem Ticket so das dies kein Bug von RaspberryMatic selbst ist oder im Zuge der RaspberryMatic hier irgendetwas diesbzgl verbessert werden kann. Die Funktionalität des HmIP-HAP obgliegt closed source Funktionalitäten in den HMIPServer.jar und Gerätefirmware des HmIP-HAP.

Und auch hierzu findet man im Homematic Forum entsprechende diskussionsbeiträge. Daher auch hier die bitte die diskussion hierüver doch bitte im HomeMatic Forum fortzuführen und hier nur tickets zu eröffnen wenn hier ein direkter Entwicklungs/Verbesserungs/Problemanaatz in RaspberryMatic selbst bzw der WebUI zu erkennen ist bzw sich aus den Diskussionen im HomeMatic Forum entsprechende Ansätze hierfür ergeben.

In Zukunft würde ich auch darum bitte das Ticket/Issue Template nicht einfach zu löschen und hier freitext einzugeben sondern sich an das Template zu halten!

**Comment by alexhass** [comment]
Das war ein Feature Request!

Java code ist nie closed... zip extract, decompile und es ist alles offen.

**Comment by libertyx82** [comment]
@alexhass 
Wohl noch nie was von Urhaberecht gehört?

Nur weil man etwas kann, heißt das noch lange nicht, dass man das auch darf.

**Comment by jens-maus** [comment]
> Das war ein Feature Request!
> 
> Java code ist nie closed... zip extract, decompile und es ist alles offen.

Ich kann mich nur wiederholen: Vorsichtig mit solchen Aussagen oder gar solchen Aktionen. Bin mir sicher eQ3 wäre nicht erfreut wenn du hier das dekompilierte jar präsentieren/nutzen würdest. Da stehen die Anwälte sicherlich schon in den Startlöchern.

Abgesehen davon brauchst du aber nicht denken das mir solche Techniken unbekannt sind, nur halte ich mich eben an Urheberrechte, Vereinbarungen und Lizenzen und es würde auch zu nix führen jetzt hier eine eigene illegale version des HMIPserver zu präsentieren oder gar weiter zu entwickeln. Das würde nur dazu führen das man dann ständig hinterher entwickeln müsste und nebenbei eben auch noch ein Gerichtsverfahren am Hals hat. Also besser solche Wünsche eQ3 vorbringen oder eben überzeugungsarbeit leisten warum eine OpenSource Veröffentlichung des HMIPserver auch in deren Interesse wäre.
