### ISSUE TITLE
Systemvariable "protokolliert" wird nicht gespeichert, wenn Variable nicht "sichtbar" ist

### ISSUE THREAD

**Issue by Michael-K-at-GitHub** [jens-maus/RaspberryMatic#948]
**Describe the bug**
Setzt man eine Variable auf protokolliert, in dem man unter Einstellungen-Systemvariable das Kästchen "protokolliert" ankreuzt, so wird dies nur gespeichert, wenn zuvor "sichtbar" angekreuzt ist.

Beispiel
[x] sichtbar, dann ankreuzen von [x] protokolliert --> Seite neu aufrufen --> [x] sichtbar [x] protokolliert --> Korrekt
[ ] sichtbar, dann ankreuzen von [x] protokolliert --> Seite neu aufrufen --> [ ] sichtbar [ ] protokolliert --> Falsch, [x] bei protokolliert fehlt

Korrekt funktioniert aber
[x] sichtbar, dann ankreuzen von [x] protokolliert, dann [ ] sichtbar (also Haken entfernen) --> Seite neu laden --> [ ] sichtbar [x] protokolliert -->

Korrekt funktioniert auch
Jedes Entfernen von [ ] protokolliert

Es scheint also
Haken bei protokolliert setzen --> Setzt protokolliert auf den Wert von sichtbar <-- Bug
Haken bei protokolliert entfernen --> Setzt protokolliert auf aus.

**To Reproduce**
1. Einstellungen-Systemvariable aufrufen
2. Bei einer beliebigen Variable, bei der [ ] sichtbar nicht angehakt ist: [x] protokolliert anhaken
3. Einstellungen-Systemvariable neu aufrufen
--> [x] bei protokolliert fehlt

**Expected behavior**
[x] bei protokolliert bleibt erhalten

**System information (please complete the following information):**
- RaspberryMatic 3.51.6.20200420
- Nightly RaspberryMatic-3.53.30.20201016 
 
**Additional context**
Von Baxxy aus dem Forum verifiziert - tritt dort auch auf

**Comment by jens-maus** [comment]
Danke für dieses sehe gut ausgefüllte Issue Template (@alexhass - so würde ich mir das auch bei deine tickets wünschen!).

Ist das problem auch von anderen so reproduzierbar? Gibt es bereits Lösungsansätze (@jp112sdl ?)?

**Comment by Michael-K-at-GitHub** [comment]
Ich hab mal ein wenig debugged. Der HTML Code scheint korrekt erzeugt zu werden, insbesondere wird ein (wie mir scheint korrekter) `onclick="iseSystem.saveDpProto(23977, this)"` erzeugt, die Id der Variable ist auch korrekt. Der Ajax Event sieht auch unauffällig auf, und die `saveDpProto()` dahinter ebenso. Die ruft dann ein `obj.DPArchive(b);` auf. Da `b` an dieser Stelle nicht von "sichtbar" abhängt, geh ich mal davon aus, dass bis hierher alles richtig läuft.

Ins `obj.DBArchive` seh ich jetzt nicht rein (wo finde ich da den Code). Kann es sein, dass jemand dort sagt: "Wenn nicht sichtbar, dann auch nicht protokolliert"? Würde das Verhalten erklären (das Nicht-Setzen von "Protokolliert" wird ja nicht retour an den Client geliefert, es gäbe auch kein Callback das darauf reagieren kann).

**Comment by jp112sdl** [comment]
>  Gibt es bereits Lösungsansätze (@jp112sdl ?)?

Ich kann erstmal auch nix in den WebUI Dateien finden, was das Problem verursachen könnte.
In der system.fn ist alles ok.
https://github.com/eq-3/occu/blob/master/WebUI/www/rega/esp/system.fn#L869-L900

In der systemvars.htm ist auch alles schick
https://github.com/eq-3/occu/blob/master/WebUI/www/rega/pages/tabs/admin/systemvars.htm#L225-L243

Die get.tcl und getall.tcl haben auch alles korrekt inne
https://github.com/eq-3/occu/blob/master/WebUI/www/api/methods/sysvar/get.tcl#L50-L51
https://github.com/eq-3/occu/blob/master/WebUI/www/api/methods/sysvar/getall.tcl#L56-L57

Und die [webui.js#L24659-24673](https://github.com/eq-3/occu/blob/master/WebUI/www/webui/webui.js#L24659-24673) ist auch ok.

Bleibt ja fast nur noch, dass in der ReGa bei `DPArchive` was kaputt ist und dort beim Ändern irgendwas in `Visible` mit geändert wird.

Ich weiß nicht, ob mein Skript einen Denkfehler hat, aber das geht halt auch nicht:
```
var test = dom.GetObject(ID_SYSTEM_VARIABLES).Get("A");

var isArch = test.DPArchive();
var isVis  = test.Visible();

WriteLine("Sichtbar     : "#isVis);
WriteLine("Protokolliert: "#isArch);

test.Visible(false);
test.DPArchive(true);

WriteLine("Sichtbar     : "#isVis);
WriteLine("Protokolliert: "#isArch);
```

ergibt:
```
Sichtbar     : false
Protokolliert: false
Sichtbar     : false
Protokolliert: false
```

`DPArchive(true);` hat nix bewirkt.

Wenn  ich jedoch
```
test.Visible(true);
test.DPArchive(true);
```
mache, also `Visible` und `DPArchive` auf `true` setze, sind auch beide anschließend `true`
```
Sichtbar     : true
Protokolliert: true
```

Mehr Kombinationen hab ich nicht getestet... Da könnt ihr ja jetzt weitermachen ^^

**Comment by jens-maus** [comment]
Danke für diese Analysen. Sehr hilfreich und schaue ich mir demnächst mal direkt an. Wenn das soweit alles passt stellt sich nur die Frage ob es wirklich gewollt ist das DPArchive() aka "protokolliert" wirklich vollkommen autark von Visible() aka "sichtbar" funktionieren sollte und/oder ob dieser vermeintliche Bug vielleicht doch eher ein Feature und somit gewollt ist...

**Comment by jp112sdl** [comment]
> vielleicht doch eher ein Feature und somit gewollt ist...

Das WebUI-Handbuch sieht zumindest keine Abhängigkeit der beiden Optionen vor.

<img width="866" alt="Bildschirmfoto 2020-10-17 um 20 20 03" src="https://user-images.githubusercontent.com/18190139/96350443-25d8f580-10b6-11eb-8d13-add08ae722e2.png">

**Comment by jp112sdl** [comment]
Eine Abhängigkeit von sichtbar und protokolliert halte ich auch nicht für sinnvoll. 
Man kann ja eine SV ausblenden und trotzdem loggen wollen, was mit ihr passiert.

**Comment by Michael-K-at-GitHub** [comment]
> Man kann ja eine SV ausblenden und trotzdem loggen wollen, was mit ihr passiert.
Kann man auch, aber eben nur in der Reihenfolge: Sichtbar ein --> Protokolliert ein --> Sichtbar aus.
Ergo: Defect

**Comment by jens-maus** [comment]
Danke für die Inputs. Nun konnte ich das Problem nachstellen und in der Tat auf einen Fehler in ReGaHss zurückführen. Beginnend mit der `R1.00.0388.0225` Version sollte das Problem entsprechend behoben sein.
