### ISSUE TITLE
Device firmware update visualization

### ISSUE THREAD

**Issue by sailor79** [jens-maus/RaspberryMatic#95]
i) Not all devices with uploaded device firmware-updates (not installed yet) are visible in homescreen

ii) The firmware-update of a advisable device firmware-update has an older date than the installed device firmware update

<img width="805" alt="bildschirmfoto 2017-04-18 um 12 18 02" src="https://cloud.githubusercontent.com/assets/1407792/25126479/c09bb7d4-2432-11e7-9f4e-021d7061923c.png">

**Comment by jens-maus** [comment]
Is this reproducible on a CCU2 also or just RaspberryMatic?

**Comment by Gluehwurm** [comment]
War eigentlich schon im Forum beantwortet
https://homematic-forum.de/forum/viewtopic.php?f=27&t=36624#p355387

Zwischenzeitlich wurde es wohl auch behoben, leider hat sich ein neuer Fehler eingeschlichen
https://homematic-forum.de/forum/viewtopic.php?f=26&t=36721

Warum da nicht erst im Forum nachgeschaut/gefragt wird, ist mir schleierhaft.

Gruß
Bruno

**Comment by HMside** [comment]
Fixed by eq-3. Please clean your browser cache.

**Comment by jens-maus** [comment]
Please specify in which firmware release this was fixed or was it just corrected on the update server of eq3?

**Comment by dehell** [comment]
Yes, it was a problem with the eq3 update server.

**Comment by sailor79** [comment]
@Gluehwurm 
"Warum da nicht erst im Forum nachgeschaut/gefragt wird, ist mir schleierhaft."

Ganz einfach:
=>>
![asd](https://cloud.githubusercontent.com/assets/1407792/25311109/20b8cc92-27f8-11e7-87c9-dad5f493456c.jpg)

**Comment by Gluehwurm** [comment]
Richtig, Fehler und Bugs sollen gemeldet werden. Da es hier um Raspimatic geht, muss halt vorher abgeklärt werden, ob es wirklich ein Raspimatic-Bug ist. Wenn man das selber schon nicht erkennt, kann es im Forum einfach erfragt werden. Sollte sich dann ein Fehler abzeichnen ... eben melden.

Sehe das hier jedenfalls nicht als "Forenerweiterung", wo jeder Unsinn nochmal diskutiert wird.

**Comment by jens-maus** [comment]
@Gluehwurm Genau so ist es auch gemeint. Hier im GitHub sollen nur real bekannte/verifizierte Bugs gemeldet werden *nachdem* diese im Forum bzw. von Dritten diskutiert/bestätigt worden sind. GitHub  ist keine Diskussionsplattform sondern eine Entwicklungsplattform.
