### ISSUE TITLE
Add nano editor

### ISSUE THREAD

**Issue by alexhass** [jens-maus/RaspberryMatic#950]
Wäre echt geil, wenn man einen nano in raspmatic einbauen könnte. Also einen command line editor der spass macht in 2020 und nicht nur vi.

**Comment by jens-maus** [comment]
@alexhass Das gibt es (aus gutem Grund) schon alles als CCU-Addon:

https://github.com/fhetty/hm-tools

Und aus gutem Grund wird es den nano niemals direkt mit RaspberryMatic ausgeliefert geben.

P.S:
Und bitte: Hör auf das Ticket Templates hier dauernd zu löschen und Freitext einzugeben. Und informiere dich immer erst im HomeMatic Forum und der Suche darin ob es vielleicht schon eine Lösung für dein Anliegen gibt, ob das schon bekannt ist, ob das wirklich ein Bug ist oder ob es eine von dir angedachte Erweiterung schon gibt.

**Comment by alexhass** [comment]
Wenn ich nix finde kann ich sicher nen case aufmachen.

Glaube nicht, dass das template in allen fällen sinn macht. Oft ist es waste of time.

**Comment by jens-maus** [comment]
@alexhass Es geht nicht darum ob das Template für dich Sinn ergibt oder nicht. Das ist eben die Voraussetzung für die Mitarbeit hier.

Und das Prozedere für ein Case/Issue hier aufmachen ist klar und übrigens auch im Ticket Template so vermerkt: zuerst wendet man sich ans HomeMatic Forum und fragt da nach. Und erst wenn sich aus den Diskussionen dort herauskristallisiert das dies ein Problem bzw noch nicht geklärtes Feature Request ist geht man hier her und eröffnet das Case/Issue.
Und ich würde darum bitten das du dich an diese Klar definierten Prozedere hältst.
