### ISSUE TITLE
Zusatzsoftware nicht scrollbar / größer wie screen / kann nicht geschlossen werden

### ISSUE THREAD

**Issue by alexhass** [jens-maus/RaspberryMatic#951]
Das Zusatzsoftware Overlay ist bei mir größer als mein Screen. Ich kann das Fenster weder schliessen noch scrollen. Ich bin jetzt gefangen in dem Fenster.

Repro: Ipad pro 12“

**Comment by jens-maus** [comment]
Duplicate of #592
