### ISSUE TITLE
UNREACH RPC Events: leere rooms[] & functions[]

### ISSUE THREAD

**Issue by MichaelAnders** [jens-maus/RaspberryMatic#952]
Firmware: 3.53.30.20200919
redmatic: 6.0.4

Ich habe in redmatic einen rpc event node für den Datapoint "UNREACH" angelegt. Nur "Emit cached value on start" ist aktiv!

Ich bekomme damit die Daten, die ich möchte (um in etwa zu erkennen ob ein Device lebt oder nicht). Diese Daten verschicke ich per MQTT und füge in den MQTT Topic den "room" ein. Der "room" ist bei jedem anderen RPC Event enthalten, der Topic ist somit schön verständlich und gut auszuwerten in node-red.

Aber bei UNREACH klappt es nicht, denn "room" ist leer?!

Das Folgende sehe ich in redmatic (Auszug):
payload: object
ccu: "localhost"
iface: "HmIP-RF"
channelType: "MAINTENANCE"
datapoint: "UNREACH"
rooms: array[0] <----!!!!
functions: array[0] <----!!!!

Ergebnis ist dann z.B. das Folgende (payload als JSON):
fhem/undefined/hm/hm-cc-rt-dn ... whz mitte/unreach {"device":"...","deviceName":"HM-CC-RT-DN ... Whz mitte","deviceType":"HM-CC-RT-DN","channel":"...:0","channelName":"HM-CC-RT-DN ... Whz mitte:0","channelType":"MAINTENANCE","channelIndex":0,"datapoint":"UNREACH","value":false,"rooms":[],"functions":[],"ts":1603027159000,"lc":1603027159000}

Mit anderen Datapoints geht es für das gleiche Device:
fhem/eg/wohnzimmer/hm/hm-cc-rt-dn meq0788458 whz mitte/low_battery {"device":"...","deviceName":"HM-CC-RT-DN ... Whz mitte","deviceType":"HM-CC-RT-DN","channel":"...:4","channelName":"HM-CC-RT-DN ...:4","channelType":"CLIMATECONTROL_RT_TRANSCEIVER","channelIndex":4,"datapoint":"LOW_BATTERY","datapointControl":"NONE","value":2.5,"room":"eg/wohnzimmer","function":"Heizung","rooms":["eg/wohnzimmer"],"functions":["Heizung"],"ts":1603028678000,"lc":1603028678000}

Ich verstehe nicht, warum bei UNREACH nicht der Raum gesetzt wird? So kann ich damit recht wenig anfangen. Und ich möchte da nicht Hacken müssen um z.B. anhand des deviceName den "room" aus vorherigen MQTT Messages zu ermitteln

**Comment by jens-maus** [comment]
Da es in diesem Ticket inhaltlich um RedMatic geht wäre das Problem doch sicherlich zuerst besser im redmatic github projekt aufgehoben, oder was sagt @hobbyquaker dazu? Und wenn dann im RedMatic GitHub dabei der Hinweis aufkommt das es sich hierbei um ein Problem in RaspberryMatic handelt kann man das hier gerne vorbeingen und allgemeine details dann liefern...

**Comment by MichaelAnders** [comment]
Gibt es zwischen den "Servicemeldungen" von Raspberrymatic und dem "UNREACH RPC Event" in redmatic einen Zusammenhang?

Denn in Raspberrymatic sehe ich in den "Servicemeldungen" zwar die Geräte und den zugehörigen Fehler ("Gerätekommunikation war gestört"), aber die zugehörigen Werte "Gewerk" und "Raum" sind immer leer.

**Comment by jens-maus** [comment]
Ich bleibe dabei. Bitte das ganze erst im RedMatic Forum bzw. GitHub Projekt klären. Sehe hier bis jetzt keinen Lösungsansatz innerhalb von RaspberryMatic

**Comment by Sineos** [comment]
Ich würde mir das bzgl. Redmatic mal anschauen wollen.
@jens-maus: Sollte RaspberryMatic denn die Rauminformation theoretisch liefern?

Was mir aufgefallen ist:
Bei einem aktuellen STICKY_UNREACH ist am Gerät ein Raum gesetzt, aber in der Übersicht der Servicemeldungen wird der Raum nicht angezeigt. Siehe Screenshots

![grafik](https://user-images.githubusercontent.com/4459312/97206885-9b7d4980-17b9-11eb-8f3e-0ca3d8dea4ae.png)
![grafik](https://user-images.githubusercontent.com/4459312/97209845-1b58e300-17bd-11eb-8a40-3f4797e2c61e.png)

**Comment by Sineos** [comment]
Ich habe eine Idee wo das Problem liegt:
- node-red-contrib-ccu fragt die Datenpunkte der einzelnen Rega-Kanäle ab
- Die UNREACH Informationen sind im Kanal 0
- Rauminformationen hängen nur an Kanälen > 0

So wie ich das verstehe, wird in der Geräteübersicht die Rauminformation aus den Kanälen >0 quasi nach oben hin eingesammelt. Ggf. auch der Grund, warum unter den Servicemeldungen der Raum nicht angezeigt wird.

**Comment by MichaelAnders** [comment]
@Sineos: 
> Ich habe eine Idee wo das Problem liegt:
> So wie ich das verstehe, wird in der Geräteübersicht die Rauminformation aus den Kanälen >0 quasi nach oben hin eingesammelt. Ggf. auch der Grund, warum unter den Servicemeldungen der Raum nicht angezeigt wird.

Das war ja auch meine Vermutung...

Ich habe einen neuen Bugreport erstellt:  #976 in dem es um die Servicemeldungen ohne Raum/Gewerk geht - denn das ist ein Bug/fehlende Funktionalität in Raspberrymatic. Wenn das behoben wird (hoffentlich...) ist dieses Problem vermutlich/vielleicht auch sofort gelöst.

**Comment by jens-maus** [comment]
Bitte diesen Umstand hier nach den neuesten Erkenntnissen aus #976 noch einmal testen. Es scheint so zu sein das das drücken auf "Baumstruktur öffnen" den Kanal :0 erscheinen lässt und dann kann man dafür auch Raum+Gewerk zuordnen. Wie verhält sich das dann bzgl. dieses Tickets hier?

**Comment by MichaelAnders** [comment]
Der Button "Baumstruktur öffnen" scheint wohl ein identisch zu sein zu wie ein Klick auf "Kanäle anzeigen" für alle Geräte auf einmal?

Jedenfalls sehe ich keinen Kanal :0 bei dem Hm Bidcos Gerät - wie auch jp112sdl.

Vermutlich liegt das an "natürlich erstmal den "internal-Flag" bei Kanal:0 der HM-Geräte entfernen" was Baxxy13 angesprochen hat? Da bin ich raus, ich habe keine Ahnung was das ist und wo man das einstellen kann...

**Comment by jens-maus** [comment]
Mit der nächsten Version wird es nun möglich sein den Raum+Gewerk auch für alle MAINTENANCE Kanäle (:0) direkt in der WebUI zu setzen. Insofern sollten die Dinge hier entsprechend nun umgesetzt sein.
