### ISSUE TITLE
Inkonsistenzen bei den gesetzten Filtern in der WebUI - "sticky Filter Problem"

### ISSUE THREAD

**Issue by Baxxy13** [jens-maus/RaspberryMatic#953]
**Describe the bug**
**Fehler A:**
Setzt man einen Namensfilter z.B. "filter_sv" bei _Status und Bedienung --> Systemvariablen_ wird dieser Filter auch bei _Programme und Zentralenverknüpfungen_  sowie bei _Status und Bedienung --> Geräte_ (erstes Gerät ist automatisch selektiert) --> rechts bei Kanal gesetzt. 
Das gleiche tritt auf wenn man bei _Programme und Zentralenverknüpfungen_ mit dem setzen eines Filters beginnt.

**Fehler B:**
Dieser gesetzte Filter aus **A** lässt sich bei  _Status und Bedienung --> Systemvariablen_ sowie bei _Programme und Zentralenverknüpfungen_ durch setzen eines "leeren" Filters löschen. Das geht aber nicht bei _Status und Bedienung --> Geräte_ (siehe **A**). Hier lässt sich zwar der Filter augenscheinlich auch durch setzen eines leeren Filters löschen, ist aber bei Neuaufruf der Rubrik wieder vorhanden.

**Fehler C-1:**
Setzt man innerhalb eines WebUI Programms über Systemzustand -- > Systemvariablenauswahl im Fenster _Programme - Systemvariablenauswahl_ einen Namensfilter kommt es erstmal wieder zu Fehler **A** und **B**.

**Fehler C-2:** 
Wiederholt man **C-1** (um z.B. eine weitere SysVar im Programm hinzuzufügen) ist im Fenster _Programme - Systemvariablenauswahl_ der Filter nicht mehr gesetzt.

**Fehler C-3:** 
Wir sind fertig mit unserem Programm und haben den Filter wie unter **B** beschrieben gelöscht. Augenscheinlich sind alle Filter weg. Wir wiederholen **C-1** aber ohne im Fenster _Programme - Systemvariablenauswahl_ etwas zu filtern. Schon beim schließen des Programms sehen wir das es wieder zu **A** und **B** mit dem in **C-1** gesetzten Filter gekommen ist. 

Der durch **C-1** gesetzte Filter lässt sich effektiv nur löschen indem man im selben Fenster einen leeren Filter aktiv setzt.
D.h. Filter anklicken und das leere Eingabefeld mit setzen schließen.  
  
**To Reproduce**
1. Die Fehlerbeschreibung ist gleichzeitig ein Ablauf zum nachstellen.

**Expected behavior**
Zu A u. B u. C:

- So wie ich es verstanden habe und es mir vorstelle sollte jede Kategorie ihre eigenen Filter haben und auch behalten.
- Kein Filter einer Kategorie sollte den Filter einer anderen Kategorie beeinflussen (Ausnahme könnte hier _Status und Bedienung --> Systemvariablen_ + Systemvariablenauswahl im Fenster _Programme - Systemvariablenauswahl_ sein)

**System information (please complete the following information):**
 - Version [RaspberryMatic 3.53.30.20200919]
 - Hardware [RaspberryPi4B-2gb]

**Additional context**
Drauf gekommen bin ich [durch den Thread](https://homematic-forum.de/forum/viewtopic.php?f=65&t=61759) im Homematic Forum und anschließendem Trial and Error.
Da es bei einer CCU3 die "sticky Filter" und somit die Probleme nicht gibt könnte es mit den Patches:
[0029-WebUI-Fix-Variable-selection-and-filter.patch](https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0029-WebUI-Fix-Variable-selection-and-filter.patch)
und / oder 
[0056-WebUI-Sticky-Filters.patch](https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0056-WebUI-Sticky-Filters.patch)
zu tun haben. Danke an @jp112sdl  für die Info diesbezüglich.

**Comment by jp112sdl** [comment]
Der Filter wird sich ja zur `pageID` "gemerkt".

Meine Vermutung: Das SV-Auswahl-Popup hat keine eigene eindeutige `pageID` _(oder sie wird fälschlicherweise nicht berücksichtigt)_, so dass der Filter der Main-Page zugeordnet wird.

**Comment by jens-maus** [comment]
@jp112sdl danke für deine Analysen. Vielleicht kann @psi-4ward hier ja Licht ins Dunkel bringen der ja der ursprüngliche Autor des Sticky Filter WebUI Patches ist.

**Comment by psi-4ward** [comment]
Die Sache mit den Filtern ist leider etwas hacky (so wie die ganze extrem veraltete WebUI). Leider habe ich aktuell nicht die Zeit hier Arbeit rein zu stecken. Das "schön" zu machen ist bei dieser Code-Base nicht wirklich möglich.

**Comment by jens-maus** [comment]
@psi-4ward Ok, danke für die Klärung. Dann müssen wir uns da selber durchwühlen und schauen ob wir das noch repariert bekommen.

Das die WebUI veraltet ist steht ausser Frage, das ist so. Aber wir müssen vmtl. noch sehr lange damit leben. Ausser es setzt sich nen talentierter Webentwickler mit **viel** Zeit mit mir zusammen und wir klügeln einen Plan aus wie man die WebUI gegen etwas neues/modernes ersetzen kann. Wie angedeutet würde das aber bedeuten VIEL Zeit investieren zu wollen, denn der Anspruch wäre schon mindestens die Funktionalitäten abzubilden die die WebUI momentan zur Verfügung stellt. Und inwieweit man dann die Gerätekonfiguration, usw. mit ähnlichem Aufwand und kompatibel zu zukünftigen Anpassungen bzw. neuen Geräteintegrationen von eQ3 steht hier noch komplett in den Sternen ;)

**Comment by jp112sdl** [comment]
Ich glaube ein großes Manko an dem Sysvar-Auswahl-Popup ist, dass es nicht über die Methode `updateContent(...)` geladen wird und somit auch keinerlei Events, wie z.B. `ContentLoaded`  angehängt werden, was wiederum ein `restoreFilters` auslösen würde.

Kurzfristige Lösungen wären daher wohl,
- das Problem als "Known (non-critical) Bug" einstufen
- die `setSFilter`-Funktion auf _nicht-`fltSVS`_ zu begrenzen, so dass Filter in dem Popup gar nicht erst persistiert werden

**Comment by Baxxy13** [comment]
Da sich an der Problematik nichts geändert hat wäre es gut wenn das Issue wieder geöffnet wird.

**Comment by jens-maus** [comment]
Danke fürs checken. Geht voran :) Kannst du mir dann bitte noch für C-2 ein Screencast machen und hier posten, dann versuch ich das auch mal zu reproduzieren und vielleicht finden wir ja dann dafür auch noch ne Lösung.

**Comment by Baxxy13** [comment]
Ich denke wir sollten C2 "vergessen", bzw. ich bin mir nicht sicher was "besser" ist.
A: Bei der Systemvariablenauswahl immer ohne Filter beginnen
B: Bei der Systemvariablenauswahl immer mit dem "irgendwann mal" gesetzten Filter beginnen

Beides hat imho Vor/Nachteile, ich tendiere aber eher zu A da man ja i.d.R. verschiedene SysVars als Trigger/Bedingung nutzt.
Kommt natürlich auch auf die jeweilige Namensgebung an, z.B. xyz_Temperatur. Da könnte man mit "Temperatur" alle filtern egal wie der Präfix ist. 
Deine Entscheidung. 😉 
![GIF 08 11 2023 17-05-30](https://github.com/jens-maus/RaspberryMatic/assets/54898249/ed2fe0a9-74f9-4df9-b3ed-ce54a94bc084)

**Comment by jens-maus** [comment]
@Baxxy13 
So, mit den gerade vorgenommenen Änderungen in 92ad53c sollten die letzten beiden Sticky Filter Probleme hoffentlich auch der Vergangenheit angehören. 

Bitte aber nochmal ausführlich testen - lasse das Ticket hier solange offen. Und falls du noch andere Filterprobleme findest dann bitte zeitnah her damit da ich aktuell ja in dem Thema drinstecke ;-)

**Comment by Baxxy13** [comment]
Also C-1 ist ausgemerzt. Sehr gut.

Bei C-2 hast du dich entschieden den Filter drin zu lassen, das funktioniert soweit auch. 
Nur leider wirkt der Filter beim erneuten Öffnen von "Systemzustand -- > Systemvariablenauswahl im PopUp-Fenster Programme - Systemvariablenauswahl" nicht. 
Soll heißen der Filter steht drin aber es wird nicht gefiltert.
Kann das aktuell aber nicht aufzeichnen.

Ich hätt's gelassen wie es war. Nach dem "drüber schlafen" bin ich der Meinung das es "besser" ist an dieser Stelle immer ohne Filter zu beginnen.

**Comment by jens-maus** [comment]
> Ich hätt's gelassen wie es war (C-2). Nach dem "drüber schlafen" bin ich der Meinung das es "besser" ist an dieser Stelle immer ohne Filter zu beginnen.

Die beiden Probleme hingen im Grunde zusammen und hatten den selben Ursprung. Kann prinzipiell verstehen das man es auch für nützlich erachten könnte das dort bei der SysVarAuswahl in dem PopUp fenster quasi kein Filter aktiv war. Aber da das nur dort der Fall war und z.B. bei einer anderen PopUp-Art (Geräteauswahl) das nicht der Fall war und eben die beiden Dinge C-1/C-2 einen Ursprung hatten habe ich mich dafür entschieden das konsistenz wichtiger ist. Nun sollten alle sticky filter auch entsprechend agieren.

Danke nochmal für das melden dieser sticky filter probleme die nun hoffentlich alle gelöst sein sollten.
