### ISSUE TITLE
JSON-RPC: ungültiges JSON

### ISSUE THREAD

**Issue by jonaswre** [jens-maus/RaspberryMatic#957]
**Describe the bug**
I realized that the JSON-RPC has an bug. I tried the request on a standard CCU3 where it only gave me an empty array.
After the update to RapberryMatic I had data in that array. But the array was corrupt. rssiData was not always correctly filled.

` ...{
     "name": "HmIP-RCV-1",
     "partner": [
      {
         "name": "HmIP-RCV-1",
         "rssiData": [
              ,
          ]
       }
    ]
 }...`

**Steps to reproduce the behavior**
```
curl --location --request POST 'http://{{ccu-ip}}/api/homematic.cgi' \
     --header 'Content-Type: application/json' \
     --data-raw '{"version": "1.1", "method": "Interface.rssiInfo", "params": {"_session_id_": "{{session_id}}", "interface": "HmIP-RF"}}'
```

**Expected behavior**
rssiData should be empty or filled with an value that expresses no value found.

**Screenshots**
![image](https://user-images.githubusercontent.com/3731681/96858780-039df980-1461-11eb-8ae9-5a5baecc9f83.png)

**System information:**
 - RaspberryMatic Version: latest
 - Used Hardware: ccu3
 - Used HomeMatic RF-Module: ccu3 

**Additional context**

**Comment by jens-maus** [comment]
Bitte mal den entsprechenden Aufruf/payload hier zeigen der dies ausgibt damit das schnell und einfach hier versucht werden kann zu reproduzieren.

**Comment by jens-maus** [comment]
Und bitte in zukunft NICHT das Ticket template löschen! Das stand übrigens so auch ganz oben beim erzeugen dieses Issues und ich bitte darum sich auch daran zu halten!

**Comment by jonaswre** [comment]
> Und bitte in zukunft NICHT das Ticket template löschen! Das stand übrigens so auch ganz oben beim erzeugen dieses Issues und ich bitte darum sich auch daran zu halten!

Ich habe es irgendwie geschafft ohne das Template ein Issue zu erstellen... (Habs nicht gelöscht)

**Comment by jens-maus** [comment]
Bitte noch den vollen Textoutput auf den oben gezeigten "curl" payload zeigen bzw. dem Issue Template hinzufügen.

**Comment by jens-maus** [comment]
Und ist es sichergestellt das der Fehler bei einer CCU3 Firmware mit gleicher Versionsnummer (3.53.30) dieses Problem nicht zeigt?

**Comment by jens-maus** [comment]
Ok, ich denke ich hab den schuldigen gefunden:

https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0038-WebUI-DeviceOverview-StatusColumn/occu/WebUI/www/api/methods/interface/rssiinfo.tcl#L23-L36

Es scheint wohl in der Tat an diesem Patch zu liegen. dieser erlaubt ja erst HmIP Geräten mit in die rssiListe aufgenommen zu werden.

Die Frage wäre nur, was hättest du gerne statt dem `[ , ]` in der Liste? Was ich hier machen könnte wäre ein `[ 65536, 65536 ]` auszugeben um zu signalisieren das für dieses gerät es kein RSSI wert gibt.

**Comment by jens-maus** [comment]
Ok, das ging schneller als erwartet. Nun wird wie bei anderen nicht bekannten RSSI werten sichergestellt das dort "65536" im Array verwendet wird, was einem "n/a" gleich kommt.

Danke nochmal für den Bugreport. Kam genau zur richtigen Zeit ;-)

**Comment by jonaswre** [comment]
Ich habe zu danken!
