### ISSUE TITLE
WebUI: Addon-Installation erzeugt HTTP Fehler 500

### ISSUE THREAD

**Issue by jp112sdl** [jens-maus/RaspberryMatic#959]
**Describe the bug**
Die Installations von Zusatzsoftware (Addon) erzeugt HTTP Error 500

**Steps to reproduce the behavior**
1. Einstellungen->Systemsteuerung->Zusatzsoftware
2. Ein Addon hochladen
3. Installation starten

Zunächst erfolgt der Aufruf der `cp_software.cgi` (_mit doppelter `sid`-Parameter-Angabe_).
Anschließend wird die `cp_software.cgi` nochmals aufgerufen und unmittelbar HTTP Error 500 ausgegeben.

Die Installation des Addons erfolgt dennoch ordnungsgemäß!

**Expected behavior**
Addon-Installation ohne HTTP Fehlerausgabe

**Screenshots**
<img width="1122" alt="Bildschirmfoto 2020-10-22 um 14 31 10" src="https://user-images.githubusercontent.com/18190139/96872306-c131e800-1473-11eb-8791-2db5a8349356.png">

**System information:**
 - RaspberryMatic Version: 3.53.27.20200901
 - Used Hardware: VirtualBox

**Additional context**
...

**Comment by jens-maus** [comment]
Also ich kann das beschriebene Verhalten reproduzieren, weiss jedoch noch nicht woher das kommen soll das die `Ajax.request()` aufrufe manchmal ein 500 Fehler zurückgeben? Des Weiteren scheint das ganze auch noch an anderen Stellen zu passieren, z.B. wenn man die Zentrale via WebUI rebooten lassen will. Auch da kommt kurz vor dem reboot befehl so ein 500 Fehler.

Und was die doppelten `sid=XXXX` Einträge in der URL angeht so scheint das auch ein breites Problem zu sein und wohl daher herzurühren das z.B. teilweise in den `cp_XXXXX.cgi` skripten die `sid=` selbst angehängt wird, aber wohl seit einigen version die `webui.js` in der `LoadFromFile()` methode dies auch explizit tut. Somit kommt es dann zu den gezeigten doppeleinträgen welche aber wohl nicht kritisch – aber unschön – sind. Eine mögliche Lösung wäre entweder in den `cp_XXXX.cgi` files vor jedem `LoadFromFile()` aufruf die URL von den sid= hinzufügungen zu befreien, oder aber in der `LoadFromFile()` einen zusätzlichen Check einzubauen der überpüft ob die URL ggfs. bereits die sid trägt und dann dort das hinzufügen zu übergehen.

**Comment by jp112sdl** [comment]
Ich hatte gehofft, dass Fehler 500 irgendwo detailliert geloggt wird... Aber außer dass im lighttpd-access.log auch der Fehler 500 steht passiert nix

**Comment by jens-maus** [comment]
Kannst du ein replay des fehlers machen nur anhand des payload des requests? dann bekommen wir es vielleicht irgendwie festgenagelt. Und im lighttpd-access.log hab ich das nicht auf anhieb gefunden...

**Comment by jp112sdl** [comment]
Was für Abhilfe sorgt, ist das Einfügen eines einfachen `puts ""` in die leere `proc action_install_start {}`
```
proc action_install_start {} {
  puts ""
}
```

Wahrscheinlich darf die nicht einfach "`{}`"-leer sein.

Die Frage ist, ob man die ganze Sektion [cp_software.cgi#L124-L132](https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0085-WebUI-AddonPopupScrollable/occu/WebUI/www/config/cp_software.cgi.orig#L124-L132) ausbaut.
Einerseits weil der Aufruf von `install_start` ohnehin nicht notwendig ist und wenn dieser Block entfernt wird, erfolgt auch nicht mehr der 2. Aufruf von `cp_software.cgi`.

Die Installation von Addons funktioniert weiterhin.

**Comment by jens-maus** [comment]
> Was für Abhilfe sorgt, ist das Einfügen eines einfachen `puts ""` in die leere `proc action_install_start {}`
> 
> ```
> proc action_install_start {} {
>   puts ""
> }
> ```

Das ist ein super Hinweis, das muss ich gleich mal probieren ob das auch an den anderen Stellen die Probleme mit dem 500er Fehlermeldungen beseitigt. Wie gesagt passiert das an anderen Stellen (z.B. bei einem Reboot auch). Vielleicht ist das ja schon die Lösung das man da schon eine leeres "puts" einbaut wo das passiert.

> Die Frage ist, ob man die ganze Sektion [cp_software.cgi#L124-L132](https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0085-WebUI-AddonPopupScrollable/occu/WebUI/www/config/cp_software.cgi.orig#L124-L132) ausbaut.
> Einerseits weil der Aufruf der _nichts-tuenden_ `install_start` ohnehin nicht notwendig ist und wenn dieser Javascript-Block entfernt wird, erfolgt auch nicht mehr der 2. Aufruf von `cp_software.cgi`.

In den Fingern jucken würde mich das schon da mal gründlich aufzuräumen. Allerdings habe ich bisher davon abstand genommen weil ich eben das diff gegen die offizielle eQ3 Firmware nicht zu groß werden will. Deshalb existiert das `action_install_start{}` auch noch dort und das würde ich ehrlich gesagt auch gerne so beibehalten, eben um die Unterschiede bzw. diffs nicht zu groß werden zu lassen weil sonst eQ3 (sollten sie das mal übernehmen wollen) das erst aufwendig analysieren müssten.

**Comment by jens-maus** [comment]
Da morgen ja schon der release vor der tür steht verschiebe ich die beiden Dinge hier mal auf die nächste Version.

Nach ersten Analysen/Tests scheint es wohl in der Tat so zu sein das einfach `puts ""` Einträge an den Stellen wo diese `500` Error auftauchen bereits ausreichen das Problem zu lösen. Die Vermutung liegt nahe das es an den `Ajax.request()` Aufrufen liegt die wohl eine entsprechenden Fehler erzeugen wenn diese requests ohne response text beendet werden. Es müsste also im Grunde "nur" in den `cp_XXXX.cgi` skripten unter `/www/config` geschaut werden das die Ajax.request() aufrufe dann ein entsprechendes `puts ""` trägt.

Bzgl. des anderen Problems (doppelte `sid=` hinzufügungen) muss auch hier geschaut werden das nur die direkten `Ajax.request()` aufrufe eine manuellen `sid=` hinzufügung beinhaltet. Alle Aufrufe die die `LoadFromFile` Funktion aus `webui.js` verwenden sollten diese nicht bereits haben weil diese selbst die `sid=` hinzufügt. Am besten wäre hier wohl das entsprechend zu bereinigen und zusätzlich in den `LoadFromFile` Funktionen auch noch eine Prüfung hinzuzufügen ob die `sid=` bereits teil der URL ist oder nicht.

Aber wie gesagt sollten wir das nach dem kommenden Release dann umsetzen weil hier umfangreiche Tests durchgeführt werden müssten um regressions zu vermeiden.

**Comment by jp112sdl** [comment]
> Da morgen ja schon der release vor der tür steht verschiebe ich die beiden Dinge hier mal auf die nächste Version.

Sind ja auch wirklich nur kleine kosmetische Sachen.
_JLCPCB hat heute geliefert, von daher bin ich auch erstmal einige Zeit mit anderen Dingen beschäftigt_
