### ISSUE TITLE
Anlernen HmIP-DRAP nicht möglich

### ISSUE THREAD

**Issue by Mitsch74** [jens-maus/RaspberryMatic#960]
**Describe the bug**
RaspberryMatic kann nicht mit HmIP-DRAP verbunden werden

**Steps to reproduce the behavior**
1. Neuinstallation des Systems; Raspberry PI mit Raspberrymatic; HmIP-DRAP; HmIPW-DRI32; 2xHmIPW-DRBL4
2. DRAP zweimal resetet
3. in WEBUI "Access Points mit inkompatibler FW gewählt
4. Oberfläche wird ausgegraut, dann passiert nichts mehr; DRAP wird nicht gefunden

**Expected behavior**
DRAP sollte gefunden und Firmware update möglich sein; danach anlernen

**Screenshots**
![Bildschirmfoto 2020-10-23 um 21 14 05](https://user-images.githubusercontent.com/73362299/97045105-739da400-1575-11eb-8e4b-40e2cb9a84bf.png)

**System information:**
 - RaspberryMatic Version: 3.53.30.20200919
 - Used Hardware: Rasperry Pi4B 8GB
 - Used HomeMatic RF-Module: keines, nur LAN

**Additional context**
Button "Homematic IP Access Points" wie in der CCU3 nicht vorhanden

**Comment by jens-maus** [comment]
> **System information:**
> 
>  - RaspberryMatic Version: 3.53.30.20200919
> 
>  - Used Hardware: Rasperry Pi4B 8GB
> 
>  - Used HomeMatic RF-Module: keines, nur LAN

Genau das ist das Problem. Für die korrekt Funktionalität eines HmIP-DRAP oder eines HmIP-HAP ist es **zwingend** notwendig ein RPI-RF-MOD installiert zu haben und das egal ob man HmIP RF Geräte verwendet oder nicht. Hier unterscheidet sich RaspberryMatic auch nicht von einer CCU3 Firmware. In der Dokumentation ist das übrigens auch unter "Vorrausetzungen" so vermerkt.

Ergo, kein Bug!

**Comment by Mitsch74** [comment]
Hallo Jens,
Sorry mein Fehler, taste mich grad vor in das Thema … und ja: wer liest ist im Vorteil ;-)

Danke für die schnelle Antwort!!

Gruß,
Mitsch
