### ISSUE TITLE
HmIP-HAP-B1 anlernen nicht möglich

### ISSUE THREAD

**Issue by tis-cs** [jens-maus/RaspberryMatic#961]
**Describe the bug**

Moin!

Habe das HM-HAP-B1 von Lidl erhalten. Update verlief problemlos jedoch ist ein Anlernen bisher erfolglos. Internetzugriff im Router schon testweise gesperrt, Werksreset usw. durchprobiert. In der offiziellen HMIP App gehts sofort und das installierte Update wird auch angezeigt.

Habe bei mir ein Pi3 mit RPI-RF-MOD im Betrieb. Kann das die Ursache sein oder wird es von Raspberrymatic generell nicht unterstützt oder es die Kombination aus beidem?

**Steps to reproduce the behavior**
1. AP über Systemeinstellungen updaten 
2. HMIP manuellen Anmeldeversuch gestartet
3. Taste am AP gedrückt 
4. Posteingang geprüft 

**Expected behavior**
Neues Gerät im Posteingang 

**Screenshots**

**System information:**
 - RaspberryMatic Version: 	3.53.30.20200919
 - Used Hardware: Pi 3B
 - Used HomeMatic RF-Module: RPI-RF-MOD

**Additional context**
Das Anlernen an einer originalen CCU3 ist wohl problemlos möglich.

**Comment by jens-maus** [comment]
Wurde diese Anleitung zum Anlernen des HmIP-HAP befolgt?

https://github.com/jens-maus/RaspberryMatic/wiki/Tipps#homematicip-accesspoint-hmip-hap-als-hmip-gateway

**Comment by tis-cs** [comment]
Habe bisher nur die Anleitung von technikkram.net befolgt. Habe nun noch mal zwei Resets gemacht und anschließend mit dem normalen sowie dem manuellen lokalen Anmelden versucht. Anschließend zwei Mal die Zentrale gerebootet ohne Erfolg. 

Update der Firmware des HAPs war nicht mehr möglich/nötig, da sie schon aktuell war. 

Kann ich noch was versuchen/tun?
Habe extra einen non managed Switch zwischen Router, CCU und HAP gesteckt. 

Danke!

**Comment by jens-maus** [comment]
Nicht das ich wüsste. Bitte für solche Nutzer/Supportprobleme auch besser ans HomeMatic Forum wenden da das definitiv kein Bug in RaspberryMatic ist.
