### ISSUE TITLE
Heizungsregler laufen immer noch unter Sommerzeit 

### ISSUE THREAD

**Issue by hkissler** [jens-maus/RaspberryMatic#962]
**Describe the bug**
Auf der Startseite von RaspberryMatic wird die richtige Uhrzeit (Winterzeit) angezeigt. Alle Heizungsregler steuern aber noch nach Sommerzeit, sind also entweder zu spät auf oder zu früh zu.

**Steps to reproduce the behavior**
1. ...
2. ...
3. ...
4. ...

**Expected behavior**
...

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: 3.53.30.2020919
 - Used Hardware: raspy 4b
 - Used HomeMatic RF-Module: ...

**Additional context**
...

**Comment by jens-maus** [comment]
Von welchen "Heizungsreglern" sprichst du? Welche Geräte sind genau gemeint? Und wie genau wird festgemacht das diese um eine stunde versetzt agieren?

Und bitte das problem mit der aktuellsten Version reproduzieren.

**Comment by jp112sdl** [comment]
@jens-maus 
Weil es hier gerade thematisch passt: Wie ist das eigentlich mit `setInterfaceClock` ?
Wird das nach einer Zeitumstellung noch mal extra ausgeführt oder laufen die Geräte mit Uhrzeit (z.B. HM-CC-RT-DN) noch mit der alten Zeit bis der Cronjob kommt?

**Comment by jens-maus** [comment]
@jp112sdl Das ist ein guter Hinweis. Natürlich läuft das `/bin/SetInterfaceClock` wie im cronjob definiert alle 6h. D.h. das müsst dann um 0:01, 6:01, 12:01 und 18:01 der Fall sein. Ergo müsste es also um 6:01 nach der Zeitumstellung ausgeführt worden sein. Ich wüsste jetzt auch ehrlich gesagt nicht wie ich das zeitlich näher zum Umstellungszeitpunkt von 2:00->3:00 bzw. 3:00->2:00 Uhr bekomme.

Das SetInterfaceClock ist aber nur für BidCos-RF Geräte zuständig bei HmIP wird die Zeitsynchronisation zu Geräte völlig autark intern im `HMIPServer` erledigt. Deshalb meine Frage danach welche Heizungsregler hier genau gemeint sind.

**Comment by hkissler** [comment]
Hallo,

war ein HmIP-WTH und ein HmIP-WTH-2.
Allerdings ist das Problem mit den Update und einen Neustart verschwunden. Vielleicht hat es sich irgendwo verpackt.
Ich schließe das ticket.

Gruß
Heinz
