### ISSUE TITLE
aarch64 OVA build for arm based VMware RaspberryMatic

### ISSUE THREAD

**Issue by vMarkus** [jens-maus/RaspberryMatic#963]
**Is your feature request related to a problem? Please describe.**
Following up on https://github.com/jens-maus/RaspberryMatic/issues/903 and https://twitter.com/RaspberryMatic/status/1320876260218834952 - yeah, it's not a pull request, I know ;-) 

There's an OVA file for x86_64, as [#ESXionARM](https://twitter.com/search?q=%23ESXionARM) is a thing since a couple of weeks (see [https://flings.vmware.com/esxi-arm-edition](https://flings.vmware.com/esxi-arm-edition)) I'd like to port my Charly based installation over to a virtualized RaspberryMatic on RPi4 and for example HMIP-RF-USB module. x86_64 code won't run on aarch64
 
**Describe the solution you'd like**
provide aarch64 OVA file in the downloads section.
USB Passthrough should enable communication with the HMIP-RF-USB module like on x86_64 OVA
In a perfect world there would be or [USB/IP](https://www.linux-magazine.com/Issues/2018/208/Tutorial-USB-IP) support to provide access to HMIP-RF-USB module on a remote device, so the VM would not have to be pinned to a specific host where the RF module is connected 

**Describe alternatives you've considered**
Another option would be to have an aarch64 docker container to run RaspberryMatic

**Comment by jens-maus** [comment]
Thanks for this enhancement request. However, please note that support for the ESXionARM platform has low priority as this new vmWare platform is anyway still a technology preview and not officially supported by vmWare. In addition, we still do have our concerns and doubts that it make sense to use a hypervisor to only run RaspberryMatic on a RaspberryPi4. In addition, supporting ESXionARM would probably imply a lot of work to only support a hand-full of users interested in ESXionARM. However, I will keep this ticket open and active, also to see/monitor how many other users might pick up this idea and flag it as important.
