### ISSUE TITLE
Keine Kommunikation mit Aktoren nach Update auf 3.53.30.20201024 (rpi4)

### ISSUE THREAD

**Issue by ITCrowdIOB** [jens-maus/RaspberryMatic#964]
**Describe the bug**
Nach dem Update auf die neueste Version findet keine Kommunikation mit den Aktoren mehr statt.

**Steps to reproduce the behavior**
1. Sowohl nach einem Update als auch nach der Neuinstallation mit anschließendem Einspielen des Backups, wird keine Verbindung zu den Geräten mehr aufgebaut.
2. Nach einem Downgrade auf die Vorversion arbeitet das System wieder einwandfrei.
3. ...
4. ...

**Expected behavior**
...

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: 3.53.30.20201024 (rpi4)
 - Used Hardware: raspberry pi 4 4gb
 - Used HomeMatic RF-Module: HM-MOD-RPI-PCB

**Additional context**
...

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen. Und das von dir geschilderte Problem kann kein genereller Bug sein sonst würde hier der Aufschrei wesentlich größer sein.

Daher bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!

**Comment by ITCrowdIOB** [comment]
Na, ja.

 

largely reworked/simplified the RF module initialisation/setup so that the new detect_radio_module tool kindly developed by @alexreinert <https://github.com/alexreinert>  is used while keeping the basic functionality to combine multiple RF modules for a shared DutyCycle use. In addition, the device type (HB-RF-USB, GPIO, etc.) will be put into a new variable in /var/hm_mode. Furthermore we now can correctly query a HM-MOD-RPI-PCB connected to a HB-RF-USB or HB-RF-USB-2 (#910 <https://github.com/jens-maus/RaspberryMatic/issues/910> , #911 <https://github.com/jens-maus/RaspberryMatic/issues/911> ).

 

„sonst würde hier der Aufschrei wesentlich größer sein.“

Kommt vielleicht noch.

 

Dann überspringen wir dieses Release.

 

 

 

 

Von: Jens Maus <notifications@github.com> 
Gesendet: Dienstag, 27. Oktober 2020 13:05
An: jens-maus/RaspberryMatic <RaspberryMatic@noreply.github.com>
Cc: ITCrowdIOB <reg2@team-eul.de>; Author <author@noreply.github.com>
Betreff: Re: [jens-maus/RaspberryMatic] Keine Kommunikation mit Aktoren nach Update auf 3.53.30.20201024 (rpi4) (#964)

 

Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen. Und das von dir geschilderte Problem kann kein genereller Bug sein sonst würde hier der Aufschrei wesentlich größer sein.

Daher bitte an das HomeMatic Forum <https://homematic-forum.de/>  wenden! Das stand übrigens auch im Ticket Template!
