### ISSUE TITLE
Couldn't read file "methods/interface/reportvalueusage.tcl": no such file or directory

### ISSUE THREAD

**Issue by jonaswre** [jens-maus/RaspberryMatic#965]
**Describe the bug**
I know this is a bug in OCCU and I've reported it in OCCU repo but maybe you can provide a solution. The reportValueUsage function is in the JSON-RPC overview but not include. 
If i make a request I get response
```{name: JSONRPCError, code: 200, message: internal error:
couldn't read file "methods/interface/reportvalueusage.tcl": no such file or directory
    while executing
"source "methods/$method(METHOD_FILE)"
"
    (file "/www/api/methods/interface/dispatch.tcl" line 162)
    invoked from within
"source [file join $env(DOCUMENT_ROOT) "api/methods/$method(SCRIPT_FILE)"]"}
```

[OCCU Issue](https://github.com/eq-3/occu/issues/109)

Thanks in advanded
**Steps to reproduce the behavior**
1. Make request to the JSON-RPC reportValueUsage

**Expected behavior**
1. Successful response

**Screenshots**
![image](https://user-images.githubusercontent.com/3731681/97501172-281e3800-1971-11eb-85e4-0f3428fb662a.png)

**System information:**
 - RaspberryMatic Version: latest
 - Used Hardware: ccu3
 - Used HomeMatic RF-Module: ccu3

**Comment by jens-maus** [comment]
Please show the request execution and payload you are sending so that we can more easily reproduce this issue.

**Comment by jens-maus** [comment]
Bitte mal prüfen ob die folgende Datei die Funktionalität des `Interface.reportValueUsage` korrekt abbildet und das dann entsprechend korrekt funktioniert:

https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0088-WebUI-Fix-MissingReportValueUsage/occu/WebUI/www/api/methods/interface/reportvalueusage.tcl

**Comment by jonaswre** [comment]
Moin, danke für den schnellen fix. 

Ich kann die Datei leider nicht in meine RaspberryMatic Installation einfügen, da Read-Only Filesystem. Kannst du mir kurz beschreiben wie ich das rein kriegen kann. Wenn nicht ist auch nicht schlimm. Dann warte ich bis zum nächsten Release.

**Comment by jens-maus** [comment]
Das rootfs bekommst du als rw remountet mit folgendem befehl:

```
mount -o rw,remount /
```

Danach kannst du die Datei an ort&stelle kopieren und entsprechend testen.

**Comment by jonaswre** [comment]
Danke,
 die Datei hat den Fehler behoben.
