### ISSUE TITLE
Kommunikationsschwierigkeiten zwischen RPi und Thermostat nur bei WLAN

### ISSUE THREAD

**Issue by RhoIota** [jens-maus/RaspberryMatic#968]
Vorab möchte ich sagen, dass ich die Warnung zur Nutzung von WLAN gelesen habe.
Ich nutze einen Raspberry Pi 4 in Verbindung mit einem HmIP-RFUSB, dem Thermostat HmIP-eTRV-2 und Raspberrymatic Version 3.53.30.20201024. Ich habe das WLAN gemäß Doku aktiviert. Wenn der Raspi über WLAN läuft, bricht andauernd die Verbindung zum Thermostat ab. Wenn der Raspi jedoch über LAN verbunden ist, gibt es keine Probleme. Die WLAN Verbindung ist nicht gestört und die Signalstärke ist sehr gut. Der Router steht ca. 5 Meter entfernt. Zwischen Raspi und dem Thermostat sind es 2 Meter. Was ich nicht ganz verstehe: Warum stört der Einsatz des WLANs die Kommunikation zwischen USB Funksender und dem Thermostat?

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!
