### ISSUE TITLE
Gruppe überträgt nur selektiv die geänderten Temperaturzeitpunkte. Rest wird nicht aktualisiert

### ISSUE THREAD

**Issue by MacHannes** [jens-maus/RaspberryMatic#969]
**Describe the bug**
liegt Inkonsistent zwischen Gruppe und verknüpftem Gerät (Wandthermostat, Heizkörper-Thermostat) vor, und man korrigiert einzelne Werte in der Gruppe, werden nur genau die Geänderten übertragen. Alles andere verbleit (auch wenn es weiterhin inkonsistent zur Gruppe ist. Meiner Meinung nach müsste im Geräte erst alles gelöscht und dann der komplette Datensatz aus der Gruppe frisch übertragen werden ("drüberbügeln").

**Steps to reproduce the behavior**
1. in einem Gerät alle Temperatur-Zeitpunkte löschen. Übertragen
2. in der Gruppe, in der weiterhin zu jedem Tag etwas steht nur ein paar Zeitpunkte ändern. Übertragen
3. Gerät öffnen: Man sieht nur die geänderten Werte, alles andere ist leer.
4. ...

**Expected behavior**
Eigentlich sollte alles exakt spiegelbildlich zur Gruppeneinstellung sein.

**Screenshots**
Edit:

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/71350238/97799569-4618c080-1c2f-11eb-80e6-7d03c665845d.png">

<img width="1582" alt="image" src="https://user-images.githubusercontent.com/71350238/97799575-4c0ea180-1c2f-11eb-8286-73c7c9f89c60.png">

**System information:**
 - RaspberryMatic Version: 3.53.30.20201024
 - Used Hardware: Raspberry Pi 3B+ mit großem Funkmodul
 - Used HomeMatic RF-Module: großes Funkmodul von eq3

**Additional context**
Forum: https://homematic-forum.de/forum/viewtopic.php?f=65&t=62240

**Comment by jens-maus** [comment]
Danke für den Bugreport. Bitte aber noch einen entsprechenden Screencast bzw Screenshot hinzufügen um den ablauf/fehler besser/schneller verstehen zu können.

Leider ist es abee so, das die Gruppenfunktionalität der CCU Firmware komplett im Closed Source Teil von HmIPServer implementiert ist und darauf das RaspberryMatic Projekt keinerlei Einfluss bzw. Änderungen vornehmen kann. Trotzdem behalten wir das Ticket hier mal offen wenn die zusatzinfos noch geliefert werden damit das eQ3 ggf einsehen kann.

**Comment by MacHannes** [comment]
Screenshots eingefügt
