### ISSUE TITLE
WebUI: Programme - copy/paste, nachträglich und/oder-change, Zeilen verschieben

### ISSUE THREAD

**Issue by MacHannes** [jens-maus/RaspberryMatic#972]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
...
![image](https://user-images.githubusercontent.com/71350238/97799903-ec18fa80-1c30-11eb-9e13-6d0a4164d514.png)

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by jens-maus** [comment]
Mal abgesehen davon das dieses Ticket lediglich aus einem Screenshot besteht (bitte immer auch dein anliegen mit Text hinterlegen, darlegen) leg ich auch diesen Verbesserungswunsch gerne entgegen, kann ihn jedoch nur aktuell zur Seite lege weil diese Anpassungen kein Kinderspiel sind und umfangreiche Umbauarbeiten der UI beinhalten würden. Dazu kommt auch noch das die WebUI meiner Meinung nach ohnehin für komplexe Programmierungen meines Erachtens nicht genutzt werden sollte um man lieber auf externe Lösungen/Logikengines wie ioBroker, RedMatic, etc. ausweichen sollte.

Wenn aber hier jemand sich prädestiniert fühlt und in einem ersten Schritt solche Änderungen umsetzt und ein PullRequest einreicht, dann schaue ich mir das gerne an und integriere das auch gerne. Den Atem würde ich allerdings nicht anhalten das diese Änderungen von mir selbst kommen werden.
