### ISSUE TITLE
WebUI: Filter-reset-Button

### ISSUE THREAD

**Issue by MacHannes** [jens-maus/RaspberryMatic#973]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
...
![image](https://user-images.githubusercontent.com/71350238/97799923-1c609900-1c31-11eb-8e9d-374f98234057.png)

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by jens-maus** [comment]
Auch wenn die Umsetzung sicherlich recht einfach wäre, so bin ich mir nicht sicher ob das einführen zusätzlicher buttons neben jedem "Filter" wirklich zielführend werden. Meines Erachtens kann der Filter völlig ausreichend in jeder Ansicht im unteren Bereich durch drücken "Filter zurücksetzen" zurückgesetzt werden. Wüsste nicht warum man jetzt bei jedem Filter einen einzelnen Button braucht. WebUI Programmierung sollte ohnehin vermieden werden. Lasse das Ticket aber bis auf weiteres trotzdem bestehen falls sich hier jemand angesprochen fühlt eine Implementierung selbst umzusetzen und zur Integration vorzuschlagen.
