### ISSUE TITLE
Scripteditor verändert Programme, die &uuml; oder &nbsp; (oder ähnlich) enthalten.

### ISSUE THREAD

**Issue by Michael-K-at-GitHub** [jens-maus/RaspberryMatic#977]
Erstellt man ein Script
```
WriteLine("&nbsp;");
WriteLine("&uuml;");
```
wird dieses korrekt gespeichert. Öffnet man jedoch danach das script nochmals im Editor, wird das Programm verändert auf
```
WriteLine(" ");
WriteLine("ü");
```
Speichert man das Programm nun nochmals, ist es entsprechend verändert.

**Steps to reproduce the behavior**
1. Neues Programm erzeugen, Aktivität Script erzeugen
2. Programm wie oben in Scripteditor eingeben
3. Script speichern
4. Scripteditor nochmals aufrufen
5. Verändertes Programm wird angezeigt (DEFECT)

**Expected behavior**
5. Unverändertes Programm wird angezeigt.

**System information:**
 - RaspberryMatic Version: alle inkl. aktueller Snapshot 20201101

**Comment by jens-maus** [comment]
Duplicate of #528
