### ISSUE TITLE
Senden an hm-ip Geräte nicht möglich 

### ISSUE THREAD

**Issue by pekae** [jens-maus/RaspberryMatic#984]
Ich habe 2 hm-ip Geräte: Bewegungsmelder und Heizkörperthermosat. Von beiden Geräten erhalte ich Statusmeldungen ( Bewegung, Temperatur etc). Ich kann aber keine Befehle oder Konfiguration AN die Geräte senden „Kommunikationsfehler“
Geräte haben neue Batterien und der Bewegungsmelder wurde ab- und neu angelernt. Wie kann ich den Fehler einkreisen?

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!
