### ISSUE TITLE
Change username "Admin"

### ISSUE THREAD

**Issue by MathiasJZ** [jens-maus/RaspberryMatic#987]
**Is your feature request related to a problem? Please describe.**
...

**Describe the solution you'd like**
I like to change username 'Admin' in something special. 
...

**Describe alternatives you've considered**

I like to delete username 'Admin'
...

**Additional context**
I tried to change 
```
/www/rega/pages/tabs/admin/userAdministration.htm
``&& (user.Name()!='Admin')`
```
into:
`&& (user.Name()!='Username')``
Afterwards I tried to delete
`&& (user.Name()!='Admin')`
Both is impossible.
...

**Comment by MathiasJZ** [comment]
Jens you are fast!
I didn't thought you will add it already in this Release

**Comment by jens-maus** [comment]
@MathiasJZ It was @jp112sdl that was actually fast in doing the patch. So say thanks to him! I just merged it quickly onto master.

**Comment by MathiasJZ** [comment]
ok thank you and @jp112sdl 
I can delete user "Admin". But if I go back to user administration "Admin" is here again.
Greetings,
Mathias

**Comment by MathiasJZ** [comment]
ok thank you @jp112sdl 
I can delete user "Admin". But if I go back to user administration "Admin" is here again.
Greetings,
Mathias
