### ISSUE TITLE
Backup from CCU1 not working

### ISSUE THREAD

**Issue by dos-ise** [jens-maus/RaspberryMatic#99]
I am trying to import an backup from my CCU1 into the RaspberryMatic.
Everthing seems to work fine but after the restart the RaspberryMatic is still empty and no rooms or devices are present.

Is this an known issue or do I make something wrong?

Best regards Dennis

**Comment by mahiso** [comment]
Same issue.
No error messages during upload, only warning "CCU1 backup..."
After reboot: No configuration (devices, rooms, variables, progams etc.)
But all RF devices are listed in device inbox as new devices. Same to wired devices, all are listed in inbox after configuration RS485 gateway.

**Comment by jens-maus** [comment]
I am sorry, but this is no support forum here, but a bug / issue tracker. So if you have a problem with CCU1 backup import please use the homematic-forum.de: https://homematic-forum.de/forum/viewforum.php?f=65

And please note, that important a CCU1 backup hasn't been tested by me and thus it is not documented to work. So please use homematic-forum.de to clarify it.

**Comment by dos-ise** [comment]
I have tested my backup in regular CCU2 and there it works fine. So it is definitely a bug in the raspberrymatic.

I really appreciate your work and I understand that this is no supported use case. But it would be nice to know for other users that this doesn't work in raspberrymatic.

Best regards Dennis

**Comment by jens-maus** [comment]
Is therr a possibility you send me your ccu1 backup for testing?

**Comment by dos-ise** [comment]
Of course...

Here is a Link
https://www.dropbox.com/s/ps5myvz20znq6yi/homematic-2017-04-28_clean.sbk?dl=0

**Comment by jens-maus** [comment]
Thank you, will test it this evening. I hope this backup contains at least one device and addon installed so that I can see/test if after restore everything is correctly shown.

**Comment by jens-maus** [comment]
Ok, I could reproduce the problem and will try to prepare a fix/workaround for the problem for the next release.

**Comment by FUEL4EP** [comment]
Just some additional hint: I tried to restore a CCU1 backup with Raspberrymatic 
2.27.8.20170501 and it failed: Neither devices nor scripts were imported. However, the import of the same CCU1 backup was successful for a Raspberrymatic build from github version d9a35ddf7375ed19f90bdebac655be98b1705433 with ,make dist' 😄
