### ISSUE TITLE
Web UI-Oberfläche wird nicht vollständig angezeigt

### ISSUE THREAD

**Issue by PhilipHanebeck** [jens-maus/RaspberryMatic#990]
seit zwei Tagen funktioniert meine RaspberryMatic nicht mehr, wenn ich nach den Neustart das Web UI öffne und mich anmelde drehen sich die Punkte undendlich um das Wort "Loading". Auch wenn ich versuche über die Einstellungen zur Systemsteuerung zu gelangen komme ich dort nicht hin.
Einzig auf das Cuxd Addon komme ich drauf und dort funktioniert alles normal.
Gibt es irgendeine Möglichkeit zu prüfen wo das Web UI hängen geblieben ist?

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!
