### ISSUE TITLE
CCU3-Hardware, Raspymatic Version: 3.51.6.20200420:  Update auf Version 3.53.XX ist nicht möglich. (weder die September-Version, noch die Oktober-Version)

### ISSUE THREAD

**Issue by twoxx** [jens-maus/RaspberryMatic#994]
CCU3-Hardware, Raspymatic Version: 3.51.6.20200420:  Update auf Version 3.53.XX ist nicht möglich. (weder die September-Version, noch die Oktober-Version)
...

**Steps to reproduce the behavior**

Einspielen der Update-ZIP:
1. CCU3 mit 3.51.620200420
2. Update-Zip Version 3.53.XX in Zentralenwartung hochladen
3. Update läuft durch
4. Neustart
5. Nach hochfahren läuft WebUi sehr langsam, lange Ladezeiten. Dann Meldung "eine Homematic-Komponente funktioniert nicht" -> Ende
5.a Bei weiterem Update-Versuch (wieder von 3.51. auf 3.53.XX aus) keine Meldung das Komponennte nicht funktioniert, aber lange Ladezeiten bis dann rote Lampe an der CCU leuchtet

Komplett frisches Image:
1. IMG-Datei auf SD-Installiert
2. CCU fährt sauber mit leerer Version 3.53.XX hoch, WEbUI läuft stabil und schnell
3. Einspielen des SystemBackups der Version 3.51
4. Neustart
5. gleiche Probleme wie oben unter 5. bei Einspielen der Update-Zip

Ich habe 4x CCU3 im Einsatz. Nur diese eine CCU3 mag das Update nicht, die anderen konnten Problemlos geupdatet werden.

**Expected behavior**
-- CCU3 sollte nach Update fehlerlos laufen

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: siehe "Steps to reproduce"
 - Used Hardware: siehe "Steps to reproduce"
 - Used HomeMatic RF-Module: RF-Module der CCU3

**Additional context**
...

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template!

**Comment by twoxx** [comment]
> 
> 
> Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.
> 
> Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden! Das stand übrigens auch im Ticket Template!

Hallo Jens,
ich halte es durchaus für einen BUG.  Denn ich vermute, dass manche Varianten der CCU3-Hardware nicht mit den Änderungen der Version 3.53.XX zurecht kommen.   Denn wenn ich ein frisches Image der Version 3.51.6 auf die SD-Karte schreibe und anschliessend das Backup der 3.51.6 einspiele (dasselbe Backup das ich beim Einspielen auf 3.53.XX verwendet hatte),
dann läuft die CCU3 ganz normal und alles funktioniert.

**Comment by jens-maus** [comment]
Ich hab deinen Parallelbeitrag im Forum schon gesehen. Für die Diskussion dort weiter und öffne dieses ticket gerne wieder sobald jemand dein problem bestätigen konnte. Genau dafür ist das Forum eben da und dort sollten solche Dinge vorab geklärt werden..

**Comment by twoxx** [comment]
hallo jens,

ich glaube der kollece hier hat ein ähnliches problem:

https://homematic-forum.de/forum/viewtopic.php?f=65&t=62768
<https://homematic-forum.de/forum/viewtopic.php?f=65&t=62768>



------------------------------------------------------------------------
Gesendet mit der Telekom Mail App
<https://kommunikationsdienste.t-online.de/redirects/email_app_android_sendmail_footer>


--- Original-Nachricht ---
Von: Jens Maus
Betreff: Re: [jens-maus/RaspberryMatic] CCU3-Hardware, Raspymatic Version: 
3.51.6.20200420: Update auf Version 3.53.XX ist nicht möglich. (weder die 
September-Version, noch die Oktober-Version) (#994)
Datum: 20. November 2020, 21:04
An: jens-maus/RaspberryMatic
Cc: twoxx, Author



Ich hab deinen Parallelbeitrag im Forum schon gesehen. Für die Diskussion 
dort weiter und öffne dieses ticket gerne wieder sobald jemand dein problem 
bestätigen konnte. Genau dafür ist das Forum eben da und dort sollten 
solche Dinge vorab geklärt werden..

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jens-maus/RaspberryMatic/issues/994#issuecomment-731381332> 
, or unsubscribe

**Comment by twoxx** [comment]
auch dieser foren-teilnehmer hatte ein problem mit version 3.53.xx und 
funkmodul.

https://homematic-forum.de/forum/viewtopic.php?f=65&t=62489#p618947
<https://homematic-forum.de/forum/viewtopic.php?f=65&t=62489#p618947>

es sieht so aus als ob die version 3.53 und manche funkmodule empfindlicher 
aufeinander reagieren als in den vorherigen raspy-versionen.0



------------------------------------------------------------------------
Gesendet mit der Telekom Mail App
<https://kommunikationsdienste.t-online.de/redirects/email_app_android_sendmail_footer>


--- Original-Nachricht ---
Von: Jens Maus
Betreff: Re: [jens-maus/RaspberryMatic] CCU3-Hardware, Raspymatic Version: 
3.51.6.20200420: Update auf Version 3.53.XX ist nicht möglich. (weder die 
September-Version, noch die Oktober-Version) (#994)
Datum: 20. November 2020, 21:04
An: jens-maus/RaspberryMatic
Cc: twoxx, Author



Ich hab deinen Parallelbeitrag im Forum schon gesehen. Für die Diskussion 
dort weiter und öffne dieses ticket gerne wieder sobald jemand dein problem 
bestätigen konnte. Genau dafür ist das Forum eben da und dort sollten 
solche Dinge vorab geklärt werden..

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jens-maus/RaspberryMatic/issues/994#issuecomment-731381332> 
, or unsubscribe

**Comment by twoxx** [comment]
das "leere gerüst" hatte ich bei meinen update-versuchen auch ein paar mal.

genau wie dieser foren-teilnehmer, habe ich auch das gefühl das in den 
bisherigen 3.53er versionen etwas nicht stimmt.

https://homematic-forum.de/forum/viewtopic.php?f=65&t=62354&start=10#p617609
<https://homematic-forum.de/forum/viewtopic.php?f=65&t=62354&start=10#p617609>

vielleicht so ähnlich wie in der original-ccu-firmware der bug mit de 
favoriten? kann es sein das dieser bug irgendwie auch in der 
raspymatic-version vorhanden ist und hier nur das einspielen des backups 
stört oder das update stört?



------------------------------------------------------------------------
Gesendet mit der Telekom Mail App
<https://kommunikationsdienste.t-online.de/redirects/email_app_android_sendmail_footer>


--- Original-Nachricht ---
Von: Jens Maus
Betreff: Re: [jens-maus/RaspberryMatic] CCU3-Hardware, Raspymatic Version: 
3.51.6.20200420: Update auf Version 3.53.XX ist nicht möglich. (weder die 
September-Version, noch die Oktober-Version) (#994)
Datum: 20. November 2020, 21:04
An: jens-maus/RaspberryMatic
Cc: twoxx, Author



Ich hab deinen Parallelbeitrag im Forum schon gesehen. Für die Diskussion 
dort weiter und öffne dieses ticket gerne wieder sobald jemand dein problem 
bestätigen konnte. Genau dafür ist das Forum eben da und dort sollten 
solche Dinge vorab geklärt werden..

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jens-maus/RaspberryMatic/issues/994#issuecomment-731381332> 
, or unsubscribe

**Comment by twoxx** [comment]
auch hier ein ähnliches problem wie meines:

update von 3.51 auf 3.53 funktioniert nicht

https://homematic-forum.de/forum/viewtopic.php?f=65&t=53396&start=20#p618654
<https://homematic-forum.de/forum/viewtopic.php?f=65&t=53396&start=20#p618654>




------------------------------------------------------------------------
Gesendet mit der Telekom Mail App
<https://kommunikationsdienste.t-online.de/redirects/email_app_android_sendmail_footer>


--- Original-Nachricht ---
Von: Jens Maus
Betreff: Re: [jens-maus/RaspberryMatic] CCU3-Hardware, Raspymatic Version: 
3.51.6.20200420: Update auf Version 3.53.XX ist nicht möglich. (weder die 
September-Version, noch die Oktober-Version) (#994)
Datum: 20. November 2020, 21:04
An: jens-maus/RaspberryMatic
Cc: twoxx, Author



Ich hab deinen Parallelbeitrag im Forum schon gesehen. Für die Diskussion 
dort weiter und öffne dieses ticket gerne wieder sobald jemand dein problem 
bestätigen konnte. Genau dafür ist das Forum eben da und dort sollten 
solche Dinge vorab geklärt werden..

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jens-maus/RaspberryMatic/issues/994#issuecomment-731381332> 
, or unsubscribe
