### ISSUE TITLE
Duty Cycle gauge shows wrong values

### ISSUE THREAD

**Issue by litec-hilg** [jens-maus/RaspberryMatic#996]
**Describe the bug**
By switching between different "Favorites" pages, the gauge shows wrong values. This behaviour is reproduceable.

**Steps to reproduce the behavior**
1. Login to RaspberryMatic
2. Switch between different favourite pages with the dropdown menu

**Expected behavior**
The gauge should visualize the correct value.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/43265878/100066150-fa73c400-2e34-11eb-8be7-c6b901fb2cf7.png)

**System information:**
 - RaspberryMatic Version: 3.53.34.20201121
 - Used Hardware: CCU3
 - Used HomeMatic RF-Module: CCU3

**Additional context**
n.a.

**Comment by jens-maus** [comment]
Duplicate of #694
